### ISSUE TITLE
Social widgets link to 'personal' page

### ISSUE THREAD

**Issue by barraponto** [HabitRPG/habitica#1]
Since we do not have accounts yet, I think it's somewhat of a security issue that the social widgets for Facebook and Twitter actually share our 'personal' URL. They should instead point to to the main website.

**Comment by lefnire** [comment]
_whistles_ don't know how that one slipped! fixed

**Comment by lefnire** [comment]
though I don't know how to get rid of all that `/#.UD4WqjKL9Zs.twitter` stuff...
