### ISSUE TITLE
Header always viewable

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#100]
_wc8: Vote here for: [Constant Header](https://trello.com/c/mrbELa6J)_
Can you make the graphic on the header (avatar, health, xp and notifications) always visible on top? even if i scroll down in my todos, task and so on. 

Maybe is not very useful in small screens like phones.

**Comment by lefnire** [comment]
requested by a few people via email & Kickstarter actually, so +3 vicariously

**Comment by wc8** [comment]
+1
maybe also show coin

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.
