### ISSUE TITLE
Death / Ran out of Health modal can be dismissed without reviving

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10001]
When your health drops to zero, the "You ran out of Health!" modal appears, but it's possible to dismiss it by clicking outside the box, rather than by clicking the "Refill Health & Try Again" button. This means that you can then use healing or level-up skills or Fix Character Values to avoid the effects of death.

The correct behaviour is that once you've seen the "You ran out of Health" modal, it should not be possible to avoid death.

**Comment by paglias** [comment]
PR coming
