### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#1000]
I know it's not your job but I'll ask you anyway. I have another account with the original user badge and 4 gems. I didn't use the site a lot at the time so I made a new account 2 months later. I know it's a ridiculous and stupid request but you'd make me very happy if you could transfer just the badge to my other account. I'm a very active user now and request bugs/suggestions quite often. My ingame name is Salami Citrus. I'll understand if you decline. Thank you.

**Comment by wc8** [comment]
@lefnire is merge accounts possible?

**Comment by StanLindsey** [comment]
Firstly what is stopping you from just using the original account if its much better off? Spend 30mins remaking your tasks and then use Restore to give yourself your armour/weapons/gold/experience again?

Secondly we'd need UUIDs for both accounts if possible. If Tyler / @lefnire  approves then he'll ask you to email them to him.

**Comment by nikrage** [comment]
Sure. I'll lose a few pets and streaks but that's okay. I forgot about the restore option.

**Comment by nikrage** [comment]
The account I'm using right now is also linked to facebook.

**Comment by StanLindsey** [comment]
Ah if you've made progress in pets and streaks then its a bit of a bummer to lose. And FB. We shall wait on a free moment for @lefnire to consider your request. =D

**Comment by nikrage** [comment]
Ok. I'll use both for now just in case :D. Thanks

**Comment by lefnire** [comment]
I can't merge the accounts, but I can manually merge authentication
mechanisms, or transfer auth properties between accounts. So if you're
willing to ditch one account and keep the other, I can move over your
facebook / uname auth as preferred. I can also manually give you things you
may be missing (badges, gems to buy pets) if they existed on the previous
account

**Comment by nikrage** [comment]
It would be awesome if you can give my "main" account the Original user badge and 4 gems which are from an older account. I can give you API's to both accounts for proof and then I'll delete my older account. I'm not sure if I should write the API's here?

**Comment by lefnire** [comment]
got your old and new [UUIDs](https://github.com/lefnire/habitrpg/wiki/User-ID) handy?

**Comment by nikrage** [comment]
old account: c869a999-59a3-4b0f-80bd-ab931e3edc8b
new account : ac3cf98f-5b1a-457b-8496-8bc5d6c19c92

**Comment by lefnire** [comment]
@nikrage i added tokens so you can buy back your pet, and added the Original User achievement. Is there anythign else in there you want?

**Comment by nikrage** [comment]
I want you to know we love you :D. Listen to the community, keep up the good work and you will succeed :) Thanks

**Comment by lefnire** [comment]
_happy sigh_ - love that stuff. good to hear, my friend :)
