### ISSUE TITLE
some pinned items should not become unpinned when you buy them (quests, eggs, potions, food)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10012]
When you pin any of the following items to your Rewards column and then buy it from that column, it unpins itself as soon as the purchase has been made:
- Quest scroll
- Pet Egg
- Hatching Potion
- Food

The correct behaviour is that it should remain pinned until the user chooses to unpin it.

Other items such as the greetings cards, transformation buffs (Snowball, etc), subscriber Gems, etc should also not become unpinned but they are already working correct and so no changes are needed for them.
The fix for this issue should NOT affect Equipment - gear pieces SHOULD become unpinned as soon as they are bought.

_Thanks to Remedy (5a008b2d-aedf-4f9f-bcf7-c02e9a9faecc)  for reporting this in the Report a Bug guild._

**Comment by TheHollidayInn** [comment]
This was probably intended because gear items can only be purchased once. So We probably need to add a canPurchaseMultipe checks before removing.

**Comment by Alys** [comment]
It also occurs for Eggs, Hatching Potions, and Food. I'll update the top post and change the issue title.

**Comment by TNychka** [comment]
I can take this

**Comment by Alys** [comment]
@TNychka Thank you! Comment here if you have questions.
