### ISSUE TITLE
Streak achievement notfications are displaying like streak bonuses

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#10014]
EDIT by Alys 2018-07-29:

See [this comment](https://github.com/HabitRPG/habitica/issues/10014#issuecomment-408665995) for the current status of this bug.

---

### General Info
  * UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
  * Browser: Firefox ESR 52.6.0 (most up-to-date ESR version)
  * OS: Windows 7 SP1

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
![image of notifications in vertical order ... You gained some gold: +1.06, Streak Bonus!: +0.43, Streak Bonus!: 864, and +1.0 damage to boss](https://user-images.githubusercontent.com/14182450/36337069-da235b16-135c-11e8-9654-901cfa83d3d7.png)

Alys asked me to write this here: Streak achievements (21 day multiples of one streak) are displaying in the notifications as if they're streak bonuses: the "message" says "Streak Bonus!" and it displays the number of total streaks you have next to a gold icon (though without any sort of plus or minus indicator like an actual gold increase notification would have). That's misleading at best, since it's not a gold increase or decrease notification, it's just telling you about a number (and it's also not a streak bonus, it's a streak achievement, so that's incorrect too).

**Comment by Alys** [comment]
@citrusella Thank you!

I've marked this suggestion/discussion because I'm not sure whether the intention is for the number of streak achievements to be displayed in a snackbar notification with better labelling or if that notification is not supposed to happen at all.

**Comment by TNychka** [comment]
A simple temporary solution would to be changing the gold icon to the same thing as the habit streaks as below
![image](https://user-images.githubusercontent.com/8963665/36567250-d6dc4db4-17f3-11e8-991e-1c94517f1953.png)

**Comment by Alys** [comment]
Reopening to report new behaviour reported again by citrusella, the serving wench (2d6ef231-50b4-4a22-90e7-45eb97147a2c):

"Streak achievements don't seem to have any text on their snackbar notifications to let you know that's what they're supposed to be. I achieved one today and there was just a blue notification that had "1004" (the number of 21 day streaks I have) centered in it with no other context. I think there used to be context so maybe something recent got rid of the part that explains it's a streak achievement? 0_o"
