### ISSUE TITLE
locked class-specific gear for your own class should show error message

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10025]
When death has caused you to lose two or more equipment pieces that belong to your class and you try to buy back a more expensive one first, the website seems to let you buy it but the purchase fails with no notification.

What should happen is that the equipment should be locked with an explanation that you can't buy it using the `tierLockedItem` string ("This item is only available once you've purchased the previous items in sequence. Keep working your way up!"). I.e., the same behaviour should occur as for a new user who has not previously bought the equipment.

_Here's an example of a report from Dec (96749e48-ee70-4c3c-9829-e652a6836385) in the Report a Bug guild:_
_"I've died several times so I have quite a few items to buy again. I click Golden Sword, confirm purchase and it says "you bought golden sword!" but no gold is subtracted and gold sword is still in rewards and is not in the equipment tab. I resynced, closed habitica and opened, closed browser and opened - each time same behaviour. I realised, maybe I need to buy lower-tier items first. Ok, bought the axe fine. But why then is a) the golden sword displayed in rewards b) message "you bought golden sword" displayed to me instead of some error message."_

**Comment by TNychka** [comment]
I can take this

**Comment by Alys** [comment]
@TNychka thannks!

**Comment by TNychka** [comment]
Design question, should the higher tier equipment be hidden until unlocked? Or should we just make an error message

**Comment by Alys** [comment]
The higher gear should not be hidden. It should behave the same way as for a new user who has not yet bought any equipment - i.e., it should have a lock symbol and the on-hover text should say why it's locked, like this:

![screenshot_2018-02-24_16-23-42](https://user-images.githubusercontent.com/1495809/36626471-1484486a-197f-11e8-846a-b564420dacab.png)
