### ISSUE TITLE
Firefox freezing on search bar click

### ISSUE THREAD

**Issue by mike-sherman1** [HabitRPG/habitica#10020]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: b93e6cc8-29a2-4f84-89aa-eb6d3c1b821c
  * Browser: Firefox Quantum 58.0.2 (64-bit)
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Firefox freezing when I try to use the task search bar or the guild search bar. Have to force shutdown of Firefox or mash on the X of Habitica tab like 20 times, or wait 20+ seconds for page to unfreeze. Issue persists after system reboot, browser clean up (clearing cache / cookies / etc.), and with all addons disabled. After waiting the 30 seconds for page to unfreeze, I can use the search bar until page refresh. The search bar is a little laggy though. On page refresh, the search bar still freezes the browser, and the following is outputted to the console.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
Loading failed for the <script> with source “https://cloudfront.loggly.com/js/loggly.tracker-latest.min.js”.
habitica.com:1
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
k/<@https://habitica.com/static/js/vendor.6354a20dd523412c8696.js:1:13249
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:233285
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:17779
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:407338
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:761642
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:353451
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:757537
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:531867
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:955586
n@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:96
window.webpackJsonp@https://habitica.com/static/js/manifest.c19367abe729f625d9cf.js:1:418
@https://habitica.com/static/js/app.379642ca9524f7ebdd73.js:1:1
moment.js:297
Invalid URI. Load of media resource  failed.
habitica.com
Loading failed for the <script> with source “https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.2.0-min.gz.js”.
habitica.com:1
All candidate resources failed to load. Media load paused.
habitica.com

**Comment by paglias** [comment]
Hi, I'm unable to replicate the issue on the same Firefox version but on a Mac. Do you have any extension installed? If so can you try to disable them and see if the problem persists?

**Comment by mike-sherman1** [comment]
Ok, I tried that once before but will try again. Issue persists with all
addons disabled. Some more info: it is just the Habitica tab that is frozen
upon trying to activate the search bar, all my other tabs are fine.

**Comment by Mimi-Kr** [comment]
I am experiencing the same issue, on Firefox, with extensions disabled, Using 64-bit Windows 7 Home. For me once I type in the search box, it's terminal, I can no longer use that page of Habitica. Must close down the tab and open it up again. As a result I cannot use the search box at all.

**Comment by dknestaut** [comment]
I want to chime in as well. I'm experiencing the same issue of with Firefox 58.0.2 64-bit on MX LInux 17 (Debian Stretch). If I click in any text entry box, one core of my CPU gets pegged at 100% for 10-20 seconds, and then it clears up and I can use the page normally. But if I go to another page on Habitica, I have to repeat this process if I click in a text entry field. I only have this issue on the Habitica website, and I am only having this issue in Firefox. Chromium works just fine.

Edit: It is not every text entry box. I do not have this issue with chat boxes, and I do not have this issue with the fields in which I input Habits/Dailies/To-Dos/Rewards.

**Comment by TheHollidayInn** [comment]
I've seen reports of this and it may be related: 

```
I am using Firefox Quantum v.58.0.2 (64-bit). When I try to invite people, I get a pop up menu and a typing cursor. I can't close the pop up menu or click on any of the fields to type. I don't have this problem in Google Chrome. I would prefer to use Firefox, however.

```

**Comment by paglias** [comment]
It seems to be a windows specific problem, I can't replicate it on mac but on windows it seems widespread

**Comment by dknestaut** [comment]
I just want to say that I'm using Linux and I am having this problem.

**Comment by paglias** [comment]
Still can't replicate on mac, @TheHollidayInn and @SabreCat can you test on windows?

**Comment by lemoness** [comment]
This may be related: https://github.com/HabitRPG/habitica/issues/10071

**Comment by lemoness** [comment]
I am able to replicate freezing on Mac with both the Guild search bar (Discover Guilds, not My Guilds) and tasks page search bar.

**Comment by Alys** [comment]
I expect this will also be fixed by the fix for this issue but just in case it becomes relevant later:

Blaine Brubaker (c1ab1b33-09ee-4c94-920a-01aa58bb4541): "Whenever I click the "Tags" drop-down to sort my To-Dos by tag, the whole web page freezes and does not fix itself with a refresh of the page. I have to exit out of my browser (Firefox) to get Habitica to work again."

I've asked them to report it again if it's still happening in a week.

**Comment by TheHollidayInn** [comment]
This should be fixed on prod now. Feel free to open if we get more reports.
