### ISSUE TITLE
mana bar should not show in profile when user has not yet selected a class

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10026]
When a user has not yet selected a class, currently if you view their profile you see a mana bar. The correct behaviour is that no mana bar should be shown (the same as for a user who has opted out of the class system).

Below is data showing the problem. `flags.classSelected` is `false` when a player has not yet selected a class so that is what you can use to prevent the mana bar being displayed.
```
{
    "stats": {
        "class": "warrior",
        "lvl": 13
    },
    "flags": {
        "classSelected": false
    },
}
```
![screenshot_2018-02-20_09-26-24](https://user-images.githubusercontent.com/1495809/36400986-1cec2502-1620-11e8-826f-cc35dc0a3b99.png)

**Comment by seekheart** [comment]
I'm thinking someone would just need to have a conditional css style to say `if (classSelected) then show mana`?

**Comment by Alys** [comment]
No, because you'd also need to consider the case where the user has opted out of the class system, which is already covered by the existing code. Replacing that with the single `classSelected` conditional would break that case.

**Comment by tmkuba** [comment]
Hi @Alys, I've made a change to the members.hasClass() store method and added some tests.

**Comment by citrusella** [comment]
This appears to still be happening (assuming I've got the correct issue?). I got my test account (ID: 40fa1808-d2d0-40e5-bf19-71517481121b) opted out (by rebirthing and getting to level 10, if it matters) and found it in a guild and looked at its profile from my normal account and it showed a mana bar despite the account being opted out.

**Comment by Alys** [comment]
I've confirmed @citrusella's report (thank you!). With my account set as below, I see a mana bar in my account's profile when viewed from another account.
```
{
    "_id": "d904bd62-da08-416b-a816-ba797c9ee265",
    "profile": {
        "name": "Alys"
    },
    "preferences": {
        "allocationMode": "flat",
        "disableClasses": true,
        "automaticAllocation": true
    },
    "flags": {
        "classSelected": true
    },
    "stats": {
        "class": "warrior",
        "lvl": 15
    }
}
```

It's not quite this issue though. :) This one was for the case where the user had not yet selected a class (`"flags.classSelected": false`) but the bug now is for the case where they've opted out (`"preferences.disableClasses": true`).  I've logged it here: https://github.com/HabitRPG/habitica/issues/10558
