### ISSUE TITLE
iOS Push Notifications: switch to Provider Authentication Tokens and node-apn module

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#10023]
As explained here https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown#provider-certificates-vs-authentication-tokens they provide some beneifts over our current method and we should switch to them.

cc @phillipthelen

**Comment by fentie** [comment]
I think I can handle switching from `push-notify` to `node-apn`, although I'm not sure I've got all the credentials to make the switch from certs to tokens.

Do we have any tests for ios push notifications currently? I see a disabled unit test for APN, and some API tests that are more about the `push-devices` contract

**Comment by paglias** [comment]
@fentie thanks! if you want to make a PR to switch from certificates to tokens that would be great, we'll add the right credentials later. As per the tests if they're disabled it means they weren't working so feel free to change them in your pr

**Comment by fentie** [comment]
So I made a PR for this... my initial reaction would be to include the team ID and key ID in config.json but the wiki makes it pretty clear not to edit that file, so... here we are. Otherwise hardcode those 2 values and upload the key and if the planets align you should (continue to) have iOS push notifications. I don't have an iDevice to test with so sadly I can't verify this myself.

**Comment by Alys** [comment]
> in config.json but the wiki makes it pretty clear not to edit that file,

Ah! That's another thing that can be improved on the wiki. :) It's fine to modify `config.json.example` for the purposes of submitting a legit change in a PR. The wiki is just trying to say that you shouldn't try to modify the example file for your own local purposes (i.e., don't modify it by accident when you're trying to change `config.json`).

**Comment by fentie** [comment]
@Alys I assumed that was the case, but better safe than sorry. In that case I'll make new keys for those values unless you all would prefer them stored elsewhere
