### ISSUE TITLE
Debug inventory options not working

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10035]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Inventory options meant to award the user hatching potions, eggs, etc. don't actually award anything once you click "Apply Changes". Additionally, clicking the options meant to fill in fields with 999 etc. has no effect either.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None that turned up for me.

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by toivomattila** [comment]
I'd like to try this one :)

**Comment by SabreCat** [comment]
@toivomattila Go for it, thanks!

**Comment by toivomattila** [comment]
Apparently I can't for some reason even open the debug inventory but I haven't been able to figure out, why. Does this happen to you as well or is it just my installation?

**Comment by TheHollidayInn** [comment]
I commented this code out because it was loading all of the content which was causing severe memory leaks. So its possible you won't be able to open it.

**Comment by beffymaroo** [comment]
@toivomattila @TheHollidayInn Is this issue still in process?

**Comment by toivomattila** [comment]
@beffymaroo Yes, I'm still working on this.
The inventory isn't working because the logic is handled by Angular code so I'm in progress of changing it to Vue.

**Comment by beffymaroo** [comment]
@toivomattila Thanks so much for the update!

**Comment by SabreCat** [comment]
It's been a while since I've even felt the need for these--there are better tools available for filling out the inventory of a test user. It might be simplest just to remove these non-functional buttons from the debug toolbox.

**Comment by Tressley** [comment]
Closing as this is no longer needed. Habitica now has admin tools to handle these types of requests.
