### ISSUE TITLE
Tavern Chat Duplicating

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1003]
Probably related to the connectivity issue. I've tried over and over to delete the extras, but they just keep coming back. :/

**Comment by lefnire** [comment]
see the end of [this issue](https://github.com/codeparty/racer/issues/116) - a bit out of my jurisdiction unfortunately

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
