### ISSUE TITLE
Editing Profile Doesn't Save the First time

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#10032]
**Reported from the Bug Guild**

After a refresh, when I edit the my profile in the about section the edit doesn't save. However, without refreshing or closing the modal, if I edit again, the save, the update does change.

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by Hus274** [comment]
I can fix this.

**Comment by lemoness** [comment]
@Hus274 Thanks so much! Let us know if you have any questions. 

I've updated the labels on this ticket.
