### ISSUE TITLE
Stats over 3 digits overlap 

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#10033]
**From the Bug Build**

On the stats tab, in the stats section at the bottom, my intelligence is 5 characters long (105.5) and overlaps with the info on the right of the block in which it's contained, partially obscuring the other info.
See https://i.imgur.com/OmbbgcR.png

![s](https://i.imgur.com/OmbbgcR.png)

**Comment by Mahendran-Nadesan** [comment]
I'd like to work on this, but am not sure what the proper/preferred way of dealing with this is. I've not really looked at the codebase, and am not sure how long it would take to find a similar example. Could you point me in the correct direction? Should I look at the width of that div/container and conditionally set the font to something smaller? Or look for the length of that string and conditionally set the font then? Or conditionally decrease the size of the container on the right that is obscured?

**Comment by TheHollidayInn** [comment]
That would be great! Let's ask our ux designer @Tressley to see what he thinks the solution should be.

**Comment by Tressley** [comment]
I would prefer we only do whole numbers for stats.

**Comment by Mahendran-Nadesan** [comment]
Rounding up or down? Presumably for display purposes only, with the unrounded stats used for actions/events?

**Comment by Alys** [comment]
The stats should be rounded down so that players don't expect to do more damage / have greater effects from skills than they are actually capable of having.

It's unfortunate that displaying a rounded number will make them think they do less damage / effects, but that's better than being disappointed if they think they'll do more.

You are correct that this is for display purposes only - no change should be made to how the stats are used by the API. 

Ideally, hovering over the box for each stat should show an on-hover effect that tells the user their accurate stat (i.e., with no rounding) for the benefit of those users who like to calculate the effects of their skills and tasks.

**Comment by Mahendran-Nadesan** [comment]
Alright. May I have this assigned to me?
My plan of action is to add a filter for the display - I've seen some examples of this in the existing code-base. Does that sound fine?

**Comment by Alys** [comment]
@Mahendran-Nadesan  It's yours, thanks! I'm not commenting on whether the filter is the best way though - I'm not sure either way. :)

**Comment by Mahendran-Nadesan** [comment]
I've made a modification that achieves the desired aim, but I'd like to ask about the conventions that are used in this project. I am using a filter called 'wholeNum' and I have put it in profile.vue, as an export:
```
export default {
    directives : {
    // existing code
},
    filters: {
    // my filter
},
```
Is this an appropriate place to keep this function? Which, is really just returning `` Math.floor(value)``

**Comment by paglias** [comment]
@Mahendran-Nadesan you should add your filter to website/client/filter but it looks like we already have a floor filter, although it might be different from this one, and then register it in registerGlobals, then you'll be able to use it everywhere

**Comment by Mahendran-Nadesan** [comment]
Ah, alright. I had seen those filters, but had not gotten my new filter to work there because I hadn't looked at the registerGlobals file. FYI, it is a different floor function, so I will add it. Thanks for the info @paglias

**Comment by Mahendran-Nadesan** [comment]
I've been struggling with this for a while, so thought I'd try to get some help here.
The code is fine, but I've hit upon the line ending issue when testing - "Expected linebreaks to be 'LF' but found 'CRLF'". My autocrlf is set to true in my .gitconfig, and I'm sure it's going to be checking in as LF. I've read and tried various things to fix this, but to no avail. Is it fine to have a pull request in this state, or do I have to ensure that tests pass? Sorry if this has been mentioned somewhere, but I can't find a section that specifically mentions this.

**Comment by paglias** [comment]
@Mahendran-Nadesan hmm, this is weird but push the code and I'll give a look
