### ISSUE TITLE
Make certain error messages click-to-dismiss instead of automatically disappearing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10031]
After discussion with the staff and other mods, we decided it would be most useful if certain error messages generated a click-to-dismiss notification instead of the floating ones that quickly disappear. This would be useful both for people who read more slowly than others, and also improve accessibility for screenreaders by providing a static target to point at to get the text read out. It would prevent the issue we've seen several times where people don't read the full error message from the swear/slur blockers and repeatedly try to post the same message (which in the case of the slur blocker, spams the mod Slack with all their attempts as flags).

It's also worth applying this to similar circumstances where it would be useful. Quoting @alys:

"This would also be good for these messages:
- wrong password when logging in
- login name can't be used (e.g., contains spaces) when registering a new account or adding a new login name to a social media account or changing the login name for your existing login
- "messageGroupChatSpam": "Whoops, looks like you're posting too many messages! Please wait a minute and try again. The Tavern chat only holds 200 messages at a time, so Habitica encourages posting longer, more thoughtful messages and consolidating replies. Can't wait to hear what you have to say. :)",

All of those are important for the user to read and all disappear too quickly.

Sorry to hijack the swear/slur issue but the same tech can be used for them all. Also, because two of them occur before you're logged in that _might_ affect the method that can be used so it would be good to consider that from the start."

Related issues: 
https://github.com/HabitRPG/habitica/issues/9249 (Alys suggested closing this one)
https://github.com/HabitRPG/habitica-ios/issues/624 (iOS)

And Alys also suggested this partially completed PR might be of use: https://github.com/HabitRPG/habitica/pull/9868

**Comment by Alys** [comment]
As an example of how important this is, here's a message someone sent us by email after they'd been having trouble logging in:

"Problem solved. The little error message only stays on the screen for a couple of seconds. When I repeatedly tried to sign in incorrectly, I had time to read it all, and found out how to do it."

**Comment by paglias** [comment]
@Tressley is this okay for you?

**Comment by Tressley** [comment]
I'm fine with the snacks sticking around for longer when a user is logged in. I would prefer different validation for the registration and login pages.

**Comment by Alys** [comment]
Tressley can you tell us what different validation you're asking for when
the user is not logged in?

>

**Comment by Tressley** [comment]
Sure! I would prefer something along these lines.

![image](https://user-images.githubusercontent.com/2686586/36759070-3c2f6df6-1be4-11e8-9a88-2b8b3154eacc.png)

**Comment by Alys** [comment]
For the error messages that you do NOT see on the login and registration screens (e.g., about swear words), @khipkin is improving their visibility using a JavaScript alert as outlined in this issue: https://github.com/HabitRPG/habitica/issues/9249#issuecomment-370261197
