### ISSUE TITLE
Streak counter resets at midnight even if user's "day end" time is later than midnight.

### ISSUE THREAD

**Issue by dlwh** [HabitRPG/habitica#1004]
I went to bed a little late last night, and didn't get around to flossing until around 12:30am (pacific time). My streak counter reset before I got to it, but the day had not reset yet.

**Comment by nextmike** [comment]
Ugh just happened to me, i leveled up around midnight. Now I go to check of some Dailies this morning and find out that I'm back down a level and dailies were'nt checked.  Some weird behavior going on around midnight

**Comment by nextmike** [comment]
And yet again, lost a level and 12 HP just like that right after midnight :(

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
