### ISSUE TITLE
equipment does not become unpinned when purchased; next gear does not become pinned

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10049]
As posted by Kajakas (40e9985b-8acb-4110-aeb9-a5946a83a229) in the Report a Bug guild:

**When I buy a piece of class equipment, it stays pinned in the rewards column (and looks as if it's locked) while the next piece of equipment in the series does not automatically get pinned.**

I've confirmed that. If you reload, the bought item disappears and the next one becomes pinned, however the expected behaviour is that as soon as you've bought it, it should become unpinned and then next one should appear without a reload being needed.

**Comment by Hus274** [comment]
I'd like to work on this if possible

**Comment by Alys** [comment]
@Hus274 Thanks! That would be great!
