### ISSUE TITLE
hard to tell which Daily repeat days are ticked

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10041]
If a Daily has only some days selected, as in the screenshot below, it's hard to work out which day the tick marks apply to for any days except Sunday and Saturday. We had a bug report about this from someone whose Dailies were becoming due on the wrong days.

It would be clearer if the spacing on either side of the checkboxes wasn't equal (i.e., each checkbox was closer to its own label) or if something else more clearly tied the checkboxes to their labels.

![screenshot_2018-02-23_07-38-30](https://user-images.githubusercontent.com/1495809/36565565-8bd903ba-186c-11e8-8177-8b213d4de3fd.png)

@Tressley

**Comment by Tressley** [comment]
Trying to keep them all on one row doesn't make this any easier. They're 8px/16px margins respectively, but if that's causing visual confusion wrapping might be the better option.

**Comment by Tressley** [comment]
Updated design for the day selection.

![image](https://user-images.githubusercontent.com/2686586/52645720-4c8d6480-2eaf-11e9-985d-05fe2d6d66ca.png)

**Comment by nichwall** [comment]
I am interested in working on this issue. I plan to add a new css rule for this form of checkboxes, probably named `custom-weekly-checkbox`. Is that an acceptable way to update the design for the weekly repeats?

**Comment by paglias** [comment]
@nichwall that looks like a possible solution! If it comes out to be too difficult you could also give a look at styling bootstrap's (Habitica uses it under the hood, just with a different style) button group component https://getbootstrap.com/docs/4.3/components/button-group/

**Comment by nichwall** [comment]
@paglias Ah, that's a lot easier than what I was planning to do, thanks! I haven't done much with web dev, but that's still something I think I can do. In order to maintain consistent style, I should put the `btn-group` definition in the related Tasks `.vue`, correct? There is not a master `*.vue` that other scripts pull from?

**Comment by paglias** [comment]
> In order to maintain consistent style, I should put the btn-group definition in the related Tasks .vue, correct? 

yes, it should be part of the task vue file.

Just a quick warning that Habitica might not be the easiest project to begin with if you're new to web design since it uses many different components to work

**Comment by jacobguinther** [comment]
I would like to work on this issue.

**Comment by paglias** [comment]
Hi @jacobguinther ! Thanks for the offer but I just realized we didn't properly update the  tags on this issue and it's actually being fixed in this PR https://github.com/HabitRPG/habitica/pull/12142

**Comment by Alys** [comment]
I've marked this as in progress instead of help wanted since it's being fixed by @negue
