### ISSUE TITLE
Website down, app does not connect

### ISSUE THREAD

**Issue by plinnie** [HabitRPG/habitica#10054]
Website is down, can't connect with App

Website message:

> Server Error
> 502 - Web server received an invalid response while acting as a gateway or proxy server.
> There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.
>

**Comment by plinnie** [comment]
Well, now it works again. Sorry.

**Comment by Alys** [comment]
No worries. :) Thanks for letting us know! The staff restarted the server, which fixed the problem.
