### ISSUE TITLE
FAQ: make sub-sections linkable, adjust cursor

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10055]
Two unrelated changes for the FAQ:

1. On the old website, the sections in the FAQ could be linked to individually, which was very useful when pointing new players at the specific information they needed. It would be good if that could be done again.

2. As reported by Shadow53 (aa21c230-34a1-44e6-92ea-07a5c46cf516): "On the static FAQ, the CSS should be modified to include the following:
`.faq-question accordion:hover { cursor: pointer; }`
"The FAQ questions are clickable and expand the answer when clicked, but the cursor used is the "select text" cursor, which makes it appear as though you do not click the text. The above CSS changes the pointer to the same one used for clicking buttons and links so users know to click the titles."

**Comment by snowsignal** [comment]
I could work on this. For the first point, should make it so the website code automatically expands that section when a link to that specific section is opened?

**Comment by Alys** [comment]
@JacksonCoder I'm sorry we didn't reply sooner! We'd love you to work on it if you'd still like to!

Yes, when a link is used, having that section automatically expanded would be great.

**Comment by snowsignal** [comment]
Great! I'll get working on this.

**Comment by fentie** [comment]
I see this has been open for awhile... any objection to me taking a shot at it? I have a working solution, it's just a bit crude. I'm curious whether it's important to continue to support multiple expanded sections or not. It currently does, but I've got a scrolling issue still to work out.

**Comment by Alys** [comment]
@JacksonCoder how are you going with this? If you have a partial solution would you like to keep working on it or would you rather take up another issue?

**Comment by snowsignal** [comment]
@fentie, feel free to work on this issue. I've been really busy and haven't been able to work on it much. I actually wanted to take on another issue as well.

**Comment by Alys** [comment]
@JacksonCoder Thanks! @fentie please go ahead! Thank you!

**Comment by beffymaroo** [comment]
@fentie Are you still working on this issue? Please let us know when you have a moment. Thank you!

**Comment by fentie** [comment]
@beffymaroo not recently. I haven't done much to deal with the open/close scrolling oddity that @negue mentioned in his most recent code review. If anyone else wants to finish pushing that PR over the line that's fine, otherwise... it's still on my to-do list. I even have a Task created for it.

**Comment by fentie** [comment]
Status update: I've got the FAQ accordion implemented using bootstrap collapse, with no more page jumping. Now I need to re-add the URI hash changing, backport the HTML into pug, fix the styling, and resubmit.

**Comment by fentie** [comment]
ok I think this might finally be ready to check over again
