### ISSUE TITLE
"None" option appears twice for Hair Styles

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10051]
The "None" option appears twice on the Edit Avatar > Hair > Style screen. It's trivial to fix but which option is meant to be there - the one on the first row or the one on the row of free styles? @Tressley 

![screenshot_2018-02-25_11-53-04](https://user-images.githubusercontent.com/1495809/36637195-794fb538-1a22-11e8-995a-7f642879cc43.png)

**Comment by TheHollidayInn** [comment]
This is correct. I believe, because you can have both the top hair style and the pony tail lower options equipped. They were pushed together during the redesign via feedback, but we may have a better way to designate the difference now.

**Comment by Alys** [comment]
At the moment you can select only one item from that screen. Each of them becomes equipped at `preferences.hair.base` which holds a single integer. The two "none" options perform the same action to unequip any of those styles:
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/client/components/creatorIntro.vue#L117
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/client/components/creatorIntro.vue#L142

I'd be fully in favour of allowing two or more styles to be equipped at once but it would take significant reworking, and then we'd need to unequip them by tapping the equipped item, rather than having a "none" option (although "none" could still be used to unequip all at once). Until/if that's done, it would make more sense to have just one "none" option.

**Comment by Tressley** [comment]
Since we don't allow two or more styles to be equipped, we can just remove the second instance of the "none" option. Keep the top "none" option. Going to remove the "needs design" label.
