### ISSUE TITLE
Quest collected items displays twice

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#10065]
From the bug guild, the collected items is showing twice. The UI looks as if you have collected items for a particular type, but it is incorrect.
![2d76gqw](https://user-images.githubusercontent.com/1253400/36765250-e4d3fb8c-1bf5-11e8-8d9d-36674256683e.jpg)

Relevant code is here:
https://github.com/HabitRPG/habitica/blob/791d711298d5cd4a6633c539448ab040bc8fc746/website/client/components/groups/questSidebarSection.vue#L44

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by Hus274** [comment]
I'll pick this up.
