### ISSUE TITLE
Add Completion Text to Older Quests

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#10066]
Some of the older quest-lines lacked completion text, with their endings instead chaining into the beginning of the following quest. I've gone through and written some short completion text sentences for those quests. In some cases, the main quest text also needs some small edits.

The following changes should be made:

atom1 (Attack of the Mundane, Part 1: Dish Disaster!)

Completion Text: After some thorough scrubbing, all the dishes are stacked safely on the shore! You stand back and proudly survey your hard work.

atom2 (Attack of the Mundane, Part 2: The SnackLess Monster)

Completion Text: With a deafening cry, and five delicious types of cheese bursting from its mouth, the Snackless Monster falls to pieces. Well done, brave adventurer! But wait... is there something else wrong with the lake?

The beginning of atom3 (Attack of the Mundane, Part 3: the Laundromancer) should then be changed to the following:

Just when you thought that your trials had ended, Washed-Up Lake begins to froth violently. “HOW DARE YOU!” booms a voice from beneath the water's surface. (The rest of the quest text continues normally from there.)

vice1 (Vice, Part 1: Free Yourself of the Dragon's Influence)

Completion Text: "With Vice's influence over you dispelled, you feel a surge of strength you didn't know you had return to you. Congratulations! But a more frightening foe awaits..."

The beginning of vice2 (Vice, Part 2: Find the Lair of the Wyrm) should then be changed to the following:

Confident in yourselves and your ability to withstand the influence of Vice the Shadow Wyrm, your Party makes its way to Mt. Habitica. (The rest of the quest text continues normally from there.)

Completion Text: 

As you lift the final crystal aloft, the shadows are dispelled, and your path forward is clear. With a quickening heart, you step forward into the cavern.

goldenknight1 (The Golden Knight, Part 1: A Stern Talking-To)

Completion text: Look at all these testimonies! Surely this will be enough to convince the Golden Knight. Now all you need to do is find her.

goldenknight2 (The Golden Knight, Part 2: Gold Knight)

Completion text: The Golden Knight lowers her Morningstar in consternation. “I apologize for my rash outburst,” she says. “The truth is, it’s painful to think that I’ve been inadvertently hurting others, and it made me lash out in defense… but perhaps I can still apologize?”  

moonstone1 (Recidivate, Part 1: The Moonstone Chain)

Completion text: At last, you manage to pull the final moonstone from the swampy sludge. It’s time to go fashion your collection into a weapon that can finally defeat Recidivate!

moonstone2 (Recidivate, Part 2: Recidivate the Necromancer)

Completion text: Recidivate staggers backwards under your final blow, and for a moment, your heart brightens – but then she throws back her head and lets out a horrible laugh. What’s happening?

Beginning of moonstone3 (Recidivate, Part 3: Necro-Vice)

Laughing wickedly, Recidivate crumples to the ground, and you strike at her again with the moonstone chain. (The rest of the quest continues normally from here.)

**Comment by Alys** [comment]
As a note to whomever works on this, when you add new strings, put them next to the existing strings for the same quest to keep all the related texts together.

**Comment by EthanEFung** [comment]
I can take this one. Looking to make my first contribution to Habitica.

**Comment by EthanEFung** [comment]
@lemoness @Alys

**Comment by lemoness** [comment]
@EthanEFung Wonderful! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by adamweldonjohnson** [comment]
I'm still learning my way around the file structure for Habitica - in this issue, would these completion texts need to be added to other files than the json with the .t function?

**Comment by paglias** [comment]
Just to the json files in common/locales/en

**Comment by adamweldonjohnson** [comment]
@paglias Thank you. I thought so, but wasn't sure.
