### ISSUE TITLE
limit chat message flagging ability for new players

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10069]
Currently, when a player clicks the report button on a chat message to flag it for moderators' attention, the message's `flagCount` is increased by 1:
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/server/libs/chatReporting/groupChatReporter.js#L81

We don't want that to happen if the player's account is less than three days old. I.e., the flagCount should NOT be increased when a new player flags a message, All the other actions that occur when flagging should still happen.

There should be no change to the behaviour when a player with an account older than three days flags a message. 

This change should be made in the API so that it applies regardless of which platform the player is using.

The PR for this will need to include tests for players older and younger than three days to ensure the behaviour is correct for both.

_This issue was suggested by @phillipthelen to prevent a troll making a new account to flag innocent posts to hide them. It's unlikely to have a significant detrimental effect on moderation because moderators will still be notified about the flagged messages and can then hide them themselves._

**Comment by EthanEFung** [comment]
@Alys - New contributor here, and just submitted my first PR. 
I'm considering taking this ticket, but I wanted to get an okay if you feel this might be more suited for a dev who is more familiar with the repository.

**Comment by Alys** [comment]
@EthanEFung I think this should be okay for you! The code changes should be pretty easy and if you can't find anything you need, you can ask us here. This a good issue for starting to get familiar with the code base.

The date that the user created their account is stored in their user document in `auth.timestamps.created` (it's in the UTC time zone so you won't need to do any time zone conversions). We use [moment()](https://momentjs.com/) for date comparisons.

----

There's something I didn't think to include in the issue - sorry about that but it shouldn't make this much harder. Currently when a message is flagged, a notification is sent to a moderators' Slack channel as shown in the screenshot below. In that example, the user `AlysTest` made the bad post and the user `LadyAlys` flagged it. Part of that notification is produced by this line:
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/server/libs/slack.js#L34

We want that message to remain the same for users older than three days. For new users, all that's needed is to add these words at the end of that message:
". New user - FLAG COUNT NOT UPDATED."

So for the example in the screenshot below, if `LadyAlys` was a new user, the top line would be:

`LadyAlys (d904bd62-da08-416b-a816-ba797c9ee265) flagged a message (language: en). New user - FLAG COUNT NOT UPDATED.`

![screenshot_2018-03-03_07-10-19](https://user-images.githubusercontent.com/1495809/36921970-f9539568-1eb1-11e8-8f94-4ce2b2bcf487.png)

----

The fix for this issue will need new tests too as most pull requests do, but that should also be pretty easy and we can walk you through it if needed. If you wish, you could submit a WIP (Work In Progress) pull request with the fix in it for us to do a preliminary review on and then add the tests after that.

Here's one test that will need to be copied for the new case of a user less than three days old:
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/test/api/v3/unit/libs/slack.js#L50

And you'll find other relevant tests in 
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/test/api/v3/integration/chat/POST-groups_id_chat_id_clear_flags.test.js
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/test/api/v3/integration/chat/POST-chat.flag.test.js

----

I've marked this as in progress for you and I think you'll do fine with it but tell us here if you have questions or change your mind about working on it!

**Comment by EthanEFung** [comment]
Thanks @Alys ! I'll let you know if I have questions moving forward

**Comment by EthanEFung** [comment]
Actually @Alys, I do have a question. When running my local version of the site, I can usually get to the point where I run the `npm start` script. But on some occasions, I get this error message
```
2018-03-03T00:31:10.161Z - info: [Fri Mar 02 2018 16:31:10 GMT-0800 (PST)] [master:8709] worker:8770 disconnect! new worker:8773 fork
module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 59.
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
```
Any ideas why I keep getting this message? I usually start the build in this manner
```
    git checkout develop
    git fetch upstream
    git rebase upstream/develop 
    diff config.json.example config.json
    cp config.json.example config.json
    node -v
    npm -v
    npm install
    mongod
    // open an new terminal
    npm run client:dev
   //open a new terminal
   npm start
    
```

**Comment by EthanEFung** [comment]
Oh, just a correction, I usually have to switch versions of node after I check them with
`nvm use 6`

**Comment by EthanEFung** [comment]
You can ignore this, I found out it was just a compiling issue, and has been solved now

**Comment by EthanEFung** [comment]
@Alys - I do want to finish this ticket. But I'd like to release this if there is someone who can handle this issue this week. I will busy interviewing this upcoming week.

**Comment by beffymaroo** [comment]
@EthanEFung Are you still interested in working on this issue? Please let us know. Thank you!

**Comment by EthanEFung** [comment]
hey @beffymaroo , you can release this ticket again. Sorry for delaying!

**Comment by beffymaroo** [comment]
@EthanEFung That's fine, thank you for letting us know!

**Comment by Alys** [comment]
I'll work on this.
