### ISSUE TITLE
quest scroll should not be lost when leaving a solo party by invitation to another

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10068]
If you are in a solo party (i.e., only yourself in the party) and you are on a quest, if you accept a party invitation from another player, you are immediately removed from your party and you lose the quest. You don't regain the quest scroll.

The desired behaviour is that when you try to accept the party invitation, you see a message like the one below. The party invitation should be neither accepted nor rejected - it should remain in your account for you to use again later if you wish to.

This should be implemented in the API so that you can't accidentally lose the quest no matter what platform you're using.

Suggested message:
_"You cannot accept this party invitation while you are in a quest. If you'd like to join this party, you must first abort your quest, which you can do from your party screen. You will be given back the quest scroll."_
We don't have to use exactly that wording but that's the information that should be conveyed.

The message should be click to dismiss (not snackbars that disappear after a couple of seconds). If https://github.com/HabitRPG/habitica/issues/10031 has been fixed before this issue is worked on, you can use that method for displaying the notification, otherwise ti could be implemented as a javascript alert and then we can change it to a better notification as part of https://github.com/HabitRPG/habitica/issues/10031

**Comment by Alys** [comment]
This should be implemented in the API so that you can't accidentally lose the quest no matter what platform you're using.

**Comment by Hus274** [comment]
I can take a look at this.

**Comment by Alys** [comment]
@Hus274 Thanks :)
