### ISSUE TITLE
Error Page only

### ISSUE THREAD

**Issue by KellenM** [HabitRPG/habitica#1006]
I signed up today and started making up the habits, to do, etc. for myself, and after one too many changes, I started receiving "disconnected" messages at the top. I refreshed the page, changes I had made were gone, so I made them again. I got a bit frustrated, so I closed the window.

I came back half an hour later, and the page simply will not load. Cleared cookies, hoping to at least see a long-in, still nothing. Tried another device. Nothing. Every time, after 30 seconds or so, the page loads with "The server is experiencing issues...." and links me to issue 165, but clearly other people are still accessing the site successfully.

**Comment by storian** [comment]
I also have been stuck on the "experiencing issues" page all day.  But it's been unusual because it's been _all_ day -- usually it clears up after a short while -- and it also was affecting /static/.  I just got the main /static/ index page, but still can't get to the app logon view.  In case this helps.

**Comment by KellenM** [comment]
Main page worked for me once, just now, but when I tried to log in I still got the error message. Main page is now inaccessible again (even after another clearing of cookies, incognito, using another browser, etc.).

**Comment by storian** [comment]
I still can't log in either.  It's the same on Firefox, which I don't use except in emergencies.  Normally I use Chrome.

**Comment by KellenM** [comment]
It is working now from another location (and on a different PC). I will advise when I'm back at the previous location as to whether the bug persists at that location.

**Comment by KellenM** [comment]
Error now occurring also at second location (on different PC).

**Comment by BlackEdder** [comment]
I have the same problem. Using beta.habitrpg.com for a while worked, but that also seems to be down now.

**Comment by lefnire** [comment]
working hard on the downtime, see http://habitrpg.tumblr.com/post/51082061058/whats-with-the-downtime

**Comment by KellenM** [comment]
Thanks for the response! I've noticed that this sporadic issue continues, but it is a relief (I think) that it happens on all systems from all locations -- but only sporadically. I don't know if it matters, but after a few days, it seems to be worst in the middle of the day and early evening (high traffic times?).

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
