### ISSUE TITLE
Google OAuth Sometimes fails on Edge

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#10072]
**From the Bug Guild**

UserID: 7d97ff88-80b2-4fd6-bb6b-273f2e7c84b7
As far as I can tell, this bug hasn't been reported on the Login issues page. I occasionally use the Edge browser on Windows 10, and it appears that if a user has signed up for a Habitica account through Gmail OAuthentication, the login token is never sent to the initial page. After selecting my google account, the OAuth window closes and I am still on the login page, even after refreshing.

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by TheHollidayInn** [comment]
We've updated Google login. Closing.
