### ISSUE TITLE
inventory selected item should not be offset when selecting one item after another

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10077]
_The bug report below was posted by LeonZaLion (d4a926a7-9b69-4f50-aa0c-48c5d7afdb56) in the Report a Bug guild. I've confirmed it on Firefox on Linux._

In your inventory under items, when selecting on item and having it in your hand, and selecting another item of the same type (e.g. grabbing a base potion and selecting a desert potion without deselecting the base potion) will cause the image of the newly selected item's picture and description to pop up where the original item's image and description should appear until your cursor moves. Try selecting a potion, and then selecting another one but don't move your cursor after you've clicked it. Notice that the image & description of the new potion appears where the old potion's image and description should be, then move your mouse and it goes back to following your cursor.

I'm using Chrome...

I've got a link of a screen recording of the glitch: https://drive.google.com/open?id=1UJrcPyeM09dsnvo66gAnrhtX-SJBqXec

**Comment by SceptileKrash** [comment]
Fixed it

**Comment by lucubro** [comment]
I'd like to take a stab at this if help is still welcomed.

**Comment by TheHollidayInn** [comment]
@lucubro please do :D

**Comment by lucubro** [comment]
Actually, the same bug affects also food items in the stable. The fix is identical so, if you don't have objections, I'll add the fix for that as well to the same PR.
