### ISSUE TITLE
Mod Tool: Block/mute button directly in user profiles

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#10073]
Right now, users who are problematic can only be blocked or muted via the Hall of Heroes, which takes a lot of time. Usually this is okay, but sometimes there are situations of urgency where we need to  move as quickly as possible to protect the community.  In those situations, it would be helpful to have a block/mute button in the profile box. This button should ONLY be visible to moderators and staff.

This doesn't need to have a particularly polished design, as only staff and moderators see it, but they should be easily visible.

**Comment by Hus274** [comment]
I can take a look into this.

**Comment by lemoness** [comment]
@Hus274 Thanks so much! Let us know if you have any questions.

I've updated the labels on this ticket.
