### ISSUE TITLE
Can't edit profile in Firefox

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#10071]
In Firefox but not Safari, when you click to edit your profile it completely freezes up, and you cannot edit any of the text fields or click the Save/Cancel buttons. This issue is not solved by refreshing.

**Comment by citrusella** [comment]
I feel the need to note this doesn't happen in the ESR version of Firefox (52.6.0), which presumably means it only happens in the "standard" version (or more accurately, versions post-58 or whatever that update channel is on now, probably).

(I also don't have the related/referenced issues.)

**Comment by TheHollidayInn** [comment]
This should be fixed on prod now. Feel free to open if we get more reports.
