### ISSUE TITLE
Background overview could use some work

### ISSUE THREAD

**Issue by probaton** [HabitRPG/habitica#10076]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 6d7d6651-604d-4e7c-adff-a040770a6768
  * Browser: Chrome
  * OS: Linux

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Background sets that the user has purchased line out differently from sets not yet owned, as seen below. 
![image](https://user-images.githubusercontent.com/13566991/36833873-2a11c2d8-1d31-11e8-9cc7-252b404cff9e.png)

Also, the backgrounds page became very bloated since the recent overhaul. Totally pretty and responsive and awesome, but bloated. You have to scroll for half an hour to find the background you're looking for, and 90% of the page is white space. 

Some simple fixes, like boxes for the sets, and consolidating the title and controls, should spruce things up nicely. 

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by probaton** [comment]
I will shamelessly admit that I submitted this issue solely because I really want to take a stab at fixing it!

**Comment by probaton** [comment]
Preliminary improvements. 
![image](https://user-images.githubusercontent.com/13566991/36836911-fe87b46a-1d3a-11e8-95e3-13082f8553de.png)

**Comment by paglias** [comment]
cc @Tressley

**Comment by Tressley** [comment]
@probaton -- Thanks for taking a stab at this! I like the direction you're heading and think that this is great start. My only feedback is to remove the box-shadow from the gray containers and update the padding-bottom for a set you can no longer purchase.

Here's a mock-up to give you a better idea:

![image](https://user-images.githubusercontent.com/2686586/36904701-7444f3d8-1dff-11e8-83ee-720c59f491e4.png)

**Comment by lemoness** [comment]
I've updated the labels on this ticket.
