### ISSUE TITLE
clearing a tag filter does not show all tasks (Chrome)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10087]
This was reported by donotgogentle🌼🌷🌻 (65be576c-c412-41c7-a31f-94994c8c4fc6) in the Report a Bug guild. I haven't seen other reports yet but will record them here if I do.

On the website in Chrome, when donotgogentle🌼🌷🌻 selects a tag, they correctly see the tasks that have that tag assigned to it, but then when they deselect the tag, about 10% of the time they then see no tasks at all. Before using the [Clear Data button](https://habitica.com/static/clear-browser-data) a day or two ago, this was happening about 90% of the time.  They have to click "clear filters" to show their tasks again. The expected behaviour is that when you select a tag and then deselect it, all your tasks should reappear.

This has been happening for them ever since the new website.

They've said that the next time they see it happen, they'll show us anything that appeaars in the JavaScript Console. I've asked for a timestamp too so we can look for logs.  They've had quite a few notification not found and session outdated errors in the logs over the past day so _maybe_ that's related (e.g., deselecting a tag doesn't show all tasks if an unsynced condition exists??)

It might be browser specific. They said "I just tested many tags in Firefox, and the problem does not seem to occur there (though there are different issues when I use Firefox, such as tag text not appearing completely)" [I'll follow up on the missing tag text separately.]
Or it might just be intermittent enough that by coincidence it didn't occur in Firefox.

**Comment by Alys** [comment]
donotgogentle🌼🌷🌻 says it happened on 4 March 2018 at 02:21 UTC but unfortunately there's nothing in Loggly for that time.

They've given me the console logs (by PM because they didn't want to reveal them all publicly). There's one "Mixed Content... the page requested an insecure image..." warning which isn't unusual and shouldn't be causing any problems. There's quite a few "net::ERR_BLOCKED_BY_CLIENT" warnings so I'm going to ask them to run Habitica for a while in incognito mode with no extensions.

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by paglias** [comment]
I'm going to close this as I cannot replicate and we haven't had any update, reopen if you get new reports
