### ISSUE TITLE
quest completion modal reappears if you click the "x" button to close

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10083]
When your party finishes a quest and you see the quest completion modal, if you click the "x" button on the top right corner, the screen closes but then comes back again as soon as you take another action on the site. Reloading doesn't stop it so this isn't an example of the common bug where modals reappear inappropriately. Instead, it seems that the "x" button doesn't clear your `party.quest.completed` value.

The correct behaviour is for the "x" button to do the same thing as the "ok" button at the bottom of the screen.

**Comment by Hus274** [comment]
I can look at this.

**Comment by Alys** [comment]
@Hus274 Thanks!

**Comment by Hus274** [comment]
So it looks like there are a couple of ways the user can leave the modal without clicking the OK button. The main ones being, clicking off the modal, clicking the `x` in the upper right hand corner, and clicking the escape key. 

Should all of these acknowledge the message? Would it be better to simply remove the ability to dismiss the modal without the ok button?

**Comment by Hus274** [comment]
As a note, when I say remove, I mean the `x` button will go away and escape won't remove the modal.

**Comment by Alys** [comment]
My personal feeling is that using ESC and clicking off the modal should be disabled since it's easy to do those by accident when you actually wanted to read the completion message. I'd like to see the "x" button kept because it's a more convenient way to dismiss that modal than by scrolling down to the bottom, and so is useful for experienced players who are repeating each quest multiple times.

If any of the staff post an alternative opinion, go with theirs rather than mine.

**Comment by Hus274** [comment]
That seems reasonable to me. Unfortunately, it looks like the modal is created and hidden multiple times on a refresh which makes in nearly impossible to detect the click on the x to close compared to the other hides. I'll spend some time looking here to see if I can prevent it from popping up and hiding multiple times.
