### ISSUE TITLE
Can Not Connect to Facebook

### ISSUE THREAD

**Issue by alexarze** [HabitRPG/habitica#101]
I know that you are having a hard time getting all these bugs fixed, but just try and fix this one as soon as you can :)

When trying to sign up, I go to the Facebook Login/Sign Up button. It redirects to Facebook and then says "AppFog 404 Not Found"

This is the website it takes me to: https://habitrpg.aws.af.cm/#_=_

I'll sign up regular for the moment, but that'd be a good thing to fix ASAP!

**Comment by switz** [comment]
Tyler, I checked the logs and this is due to toobusy() being deployed to app fog. You can't use it there, unfortunately.

**Comment by lefnire** [comment]
fixed now that we're on Liquid Web
