### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#10102]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Server Error

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

Failed to load resource: the server responded with a status of 502 (Bad Gateway)

Failed to load resource: the server responded with a status of 502 (Bad Gateway): 68d4a01e-db97-4786-8ee3-05d612c5af6f

**Comment by paglias** [comment]
Should be fixed now
