### ISSUE TITLE
Flying pig flyght too high in profile

### ISSUE THREAD

**Issue by majestic-owl448** [HabitRPG/habitica#10104]
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Google Chrome
  * OS: Windows 7

### Description
![habitica gamify your life](https://user-images.githubusercontent.com/26656284/37076438-e45f34e6-21d6-11e8-9c7a-0a7b8690157b.png)
In the profile the Flying Pig it's outside the box.

**Comment by Alys** [comment]
labels updated
