### ISSUE TITLE
Hatched pet disappeared

### ISSUE THREAD

**Issue by caepenna** [HabitRPG/habitica#10106]
Same problem as issue #5347

I hatched a red fox and a desert bear. I got the normal message saying it hatched and to go to the pet page to view it, but when I went to view it it wasn't there.

User ID:7257f110-d8e0-473f-b54f-aa49c6249003

**Comment by paglias** [comment]
Hi @caepenna , thanks for the report, can you post about your issue in the Report a Bug Guild, https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac, a mod should be able to help you getting your pet back, I'm closing the issue since it's likely a one time syncing issue
