### ISSUE TITLE
Hippo-Crite quest icon is smaller than all others

### ISSUE THREAD

**Issue by majestic-owl448** [HabitRPG/habitica#10105]
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Google Chrome
  * OS: WIndows 7

### Description
![habitica gamify your life](https://user-images.githubusercontent.com/26656284/37076585-92d3917a-21d7-11e8-9b3c-e0c2170960ef.png)
In the selection quest modal the Hippo-Crite quest icon is smaller than all other quest icons

**Comment by Alys** [comment]
For the coder who works on this, the problem occurs when you try to start a quest - that's the quest selection screen.

It might be a problem with the image having been uploaded at the wrong size.


@Ieahleen Thanks for logging this and the other one. I'd forgotten about them! :scream:

**Comment by hathix** [comment]
Yes, compare [the Hippo image](https://github.com/HabitRPG/habitica/blob/develop/website/raw_sprites/spritesmith/quests/scrolls/inventory_quest_scroll_hippo.png) to [another quest image](https://github.com/HabitRPG/habitica/blob/develop/website/raw_sprites/spritesmith/quests/scrolls/inventory_quest_scroll_basilist.png). The Hippo scroll doesn't have the right padding; it's 48x51 but should be 68x68.
