### ISSUE TITLE
Ctrl-V in a chat message can cause it to send

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10117]
We've had two reports indicating that hitting Ctrl-V to paste text into a chat message can cause the message to be sent. 

The first was from donotgogentle (65be576c-c412-41c7-a31f-94994c8c4fc6) about six days ago:

_"Sorry for the double post. Whenever I use Ctrl+V my post gets sent automatically (happens in all guilds) without my clicking 'Send'"_

They never responded to my request for more information but I'll chase them about it now that we've had a second report. Here's what I asked: "Is that on both Firefox and Chrome? Are you using Windows or Mac OS or Linux? Does it still happen if you deliberately copy less than a full line of text? E.g., type a few words in a text editor, select only some of the words from the **middle** of the line, copy that, then paste it."

The second report is from kAbi, child of Light (7adf6ada-3c05-4054-b5df-fa7d49d3b9eb) today:

_"in guilds like the short and long term accountability guilds and in the tally board of the duelling grounds I have to write reports and for each bullet point I will use an emoji. I use the pc, so I will copy in my emoji with ctrl+V and then type my message, then hit enter 2 times, then hit ctrl+v to copy in my emoji (e.g white_check_mark for when the task got done, or x for when the task didn't got done) repeat._

_"it often happens, and I mean really often, that the message is getting send before I finish writting my whole report._

_"I'm aware there is the shortcut to hit ctrl+enter to send the message. now I'm wondering, whether I'm just too fast in typing, and so when I hit enter two times to create the space needed to separate the paragraph and then hit ctrl+v maybe I'm too fast in hitting ctrl and my computer interprets it as me hitting enter+ctrl, hence sends the message._

_"though, this all happens so fast, that usually I'm in the midst of the sentence I wanted to write when suddenly my message is gone from the writing space because it got posted. usually then a part of what I intended to write will appear in the writting window, the starting won't be there, probably because during that time it was sending the message._

_"I don't know how to hinder this from happening. I tried typing slower and it seemed to work, but I'm not a patient person and a fast typer. and this is happening sooo often I really wonder whether there might be a bug happening. Am I just too clumsy?"_

 kAbi, child of Light  says they are using Firefox version 58.0.2, Windows 10 Version 1709

**Comment by Alys** [comment]
kAbi, child of Light has given these details for their browser:

Firefox version 58.0.2, Windows 10 Version 1709

(I'm about to edit this into the top post for neatness)

**Comment by Cappycot** [comment]
[Confirmed this on Google Chrome 60.0.3112.113 64-bit on Ubuntu 16.04 LTS.](https://drive.google.com/open?id=1ssk55GFSm5M6uQBaMMFs4TBGPveT-OoF)

While I've been looking for ways to make my first contribution, I have zero experience in this (lol). I speculate that this is more of a quality-of-life issue as what happens (to at least me and kAbi, child of Light) is that we fail to let go of the Ctrl in Ctrl+V before we hit Enter. The script "caches" what exists in the textbox at that precise moment, and ignores anything else we type and just sends whatever was written at the moment of Enter being hit.

My question is what do we want to do about this? Do we want to make Ctrl+Enter create a pop-up confirmation before sending the text, or do we want to do something else with Ctrl+Enter like waiting for a set period of time to make sure the user isn't still typing in the box?

**Comment by siege918** [comment]
I've been looking for a good first issue to look at, this one seems right up my alley. Mind if I take a look at it? If it's happening this consistently, I'd suspect it's not just detecting ctrl-enter, but I'd have to take a closer look.

**Comment by Alys** [comment]
@siege918 please do work on this - thanks! Post here if you have questions or run into problems.

For @Cappycot's post : I think we wouldn't want a pop up confirmation for ctrl-enter. A short delay might be acceptable if necessary. Sorry we didn't reply to that before now. :(
