### ISSUE TITLE
Died because of inability to log in :(

### ISSUE THREAD

**Issue by kenziejustine** [HabitRPG/habitica#1011]
The server was down for me for like 2 days and I was unable to log in to check off my dailies, so I died. Is there any ways to reverse this? I lost all of my coins/etc and a level.

**Comment by wc8** [comment]
Yes. [Restore your account.](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account)

**Comment by baptiste30** [comment]
I think it will be the same for me, i can only check my profile the evening and it is never accessible at this time :( 
Solution will arrive ?

**Comment by StanLindsey** [comment]
Sorry about this guys! We've got our top guns on it at the moment, make sure to try out [the beta site](https://beta.habitrpg.com) if the main site is down.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
