### ISSUE TITLE
Quest Shop arithmetic follows its own rules. Laws of Mathematics are not the Habitica way.

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10115]
Bulk purchasing doesn't work correctly in quest shop. Number purchased is treated as integer for 1 and as string for 2 or more (i.e., string concatenation occurs when you buy the items, instead of integer arithmetic). The number is also treated as a string if you change the number to anything and then change it back to 1.

To reproduce:

- Give yourself a chunk of gold.
- Go to the quest shop. Pick a gold-purchasable quest that you don't have any of. 
- Buy 1. You now own 1.
- Buy another 1. You now own 2. This is good.
- Use the bulk purchase feature to buy 2 at once. You now own 22. This is wrong.
- Buy 10 at once. You now own 2210. This is getting silly.
- Pick another quest that you own none of.
- Buy 1000. You now own 1000.
- Buy another 1000. You now own 10001000. This is not how maths is meant to work.

**Comment by Alys** [comment]
I can't reproduce this for Gem-purchasable quests, which is nice.

**Comment by majestic-owl448** [comment]
I broke also the counter in Inventory... maybe I shouldn't have tried... XD

![habitica gamify your life 1](https://user-images.githubusercontent.com/26656284/37208636-59d31a5e-23a2-11e8-8304-e6d48b0eb1b7.png)

Syncing it's fixed, but it scared me for a moment

**Comment by Hus274** [comment]
I can look into this.

**Comment by Alys** [comment]
@Hus274 Thanks!
