### ISSUE TITLE
userAlreadyInGroup should not be used when a user joins a group

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10119]
The `userAlreadyInGroup` error message is designed for use when a group member tries to invite another player, as shown in the two code snippets below. That works well and should not be changed.
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/common/locales/en/groups.json#L225
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/server/controllers/api-v3/groups.js#L938

However the message is also being used when a player tries to join a guild that they are already a member of. They see an error message because the correct parameters aren't being passed to that locales string. `Error processing the string "userAlreadyInGroup"`
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/server/controllers/api-v3/groups.js#L558

The fix is to create a new string for this case, called something like `youAreAlreadyInGroup`, with the text "You are already a member of this Guild". Please add that string to groups.json immediately below the `userAlreadyInGroup` to keep the two similar messages together.

You'll then need to adjust the code that throws the error when the user tries to join the guild:
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/server/controllers/api-v3/groups.js#L557-L559

And you'll need to adjust the associated test to make it use the new string:
https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/test/api/v3/integration/groups/POST-groups_groupId_join.test.js#L47-L54

**Comment by tmkuba** [comment]
hi @Alys, I think I can take a crack at this.  it's my first Habitica contribution!

**Comment by Alys** [comment]
@tmkuba Thank you!
