### ISSUE TITLE
Group Plan creation modals have confusing title and non-standard buttons 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10118]
When creating a Group Plan, one of the modals has a confusing title and the payment buttons don't have the normal Stripe / Amazon button appearance.

1. Click on Group in the navigation menu
1. Click the "Create Your New Group" button
1. The screen that appears is titled "Select Payment" but there's nothing on the screen about payment. The expected title would be something like, "Name your new Guild" (using "Guild" here rather than "Group" would be preferable to help avoid some of the guilds with group plans that are created by mistake when the user just wanted to upgrade their party). See the first screenshot below.
1. The next screen that appears is also titled "Select Payment" which is correct.
1. That screen has buttons for payment methods but they don't follow the standard appearance for Stripe and Amazon buttons. @Tressley Are they meant to?

![screenshot_2018-03-10_11-14-36](https://user-images.githubusercontent.com/1495809/37236517-3d210ddc-2454-11e8-8232-d787227f5259.png)

![screenshot_2018-03-10_11-15-36](https://user-images.githubusercontent.com/1495809/37236528-53b0b0d4-2454-11e8-840a-5a5671da601b.png)

**Comment by Tressley** [comment]
We do have an updated design for these: https://zpl.io/bJNwA1W
![image](https://user-images.githubusercontent.com/2686586/39316360-f8e20fd2-4946-11e8-8fcf-9b5e2dc21a8e.png)
