### ISSUE TITLE
group plan "quantity" changes need to be more reliable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10124]
When the leader of a group plan invites new members or removes existing members, the group's `quantity` field is updated and I think the change is also sent to Stripe / Amazon at the same time, rather than at the next scheduled billing period.

This can sometimes fail. E.g., a few months back, shanaqui's group plan had three members in it, then one member was removed. However the guild's `quantity` field stayed at 3 and payments continued to be made for three members ($15 per month).

The code that adds or removes members to/from a group plan needs to have checking in place to ensure that all necessary actions succeed. If any don't succeed, the code should either try again (and again and again until successful) or notify admins (and check that the notification was successful).

------

With PR #12335 the Habitica codebase has been updated to support MongoDB 4.2 and transactions making it possible to fix this issue. 

Transactions allow operations on multiple documents to be executed ensuring that either all of them are executed correctly or none, making it possible to fix this issue.

An example on using transactions can be found at https://mongoosejs.com/docs/transactions.html while more info at https://docs.mongodb.com/manual/core/transactions/. If you want to work on this issue and have any question please leave a comment!

**Comment by shanaqui** [comment]
I thought you fixed the quantity problem with my group plan anyway, but this month it was still $15 as if there were three members (nope)...

**Comment by Alys** [comment]
Yes, I had adjusted the quantity field back when we first found that problem in your group plan but I think this part is important for correct billing: "the change is also sent to Stripe / Amazon at the same time, rather than at the next scheduled billing period". I think if that's not done automatically at the time that the membership is changed, then Stripe never finds out that it should be charging more/less. Basically the quantity field is irrelevant for that, I think. We hadn't realised that when we were investigating your plan's problem earlier this year.

**Comment by TheHollidayInn** [comment]
I did fix this a while back: https://github.com/HabitRPG/habitica/blob/develop/website/server/models/group.js#L1409
https://github.com/HabitRPG/habitica/blob/f59210375491c8a5de5cb30da53f016ba6e3e7b3/website/server/controllers/api-v3/groups.js#L574
https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/stripePayments.js#L102
https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/amazonPayments.js#L275

**Comment by shanaqui** [comment]
@Alys Aha, I understand now!

@TheHollidayInn I'm not entirely sure of when Alys tried to tweak my plan, etc, but I believe it was recently. Either your fix doesn't work [in some circumstances], or you haven't made it retroactive. I think the benefits of making it retroactive should speak for themselves; I hope we haven't got any other users sitting around paying Habitica extra each month and not noticing, but it's possible, and even when we've tried to fix my account it hasn't 'stuck'. So if anyone hasn't been reporting it... you see the problem.

**Comment by Alys** [comment]
So for shanaqui's case, this is the relevant code for adjusting the Stripe billing when removing a member from a group plan:

https://github.com/HabitRPG/habitica/blob/70500d7c98d67f1edd4a91aa26e176c5952ebae8/website/server/libs/stripePayments.js#L273-L286

That was modified on 2017-03-06. @shanaqui Do you remember if you removed the guild member before or after that date?

Regardless of the date though, that code does wait for await stripeApi.subscriptions.update() to finish but doesn't check any return value. I can't actually work out where that update function comes from. :(  Is it one of these  node_modules/stripe/lib/resources/Subscriptions.js node_modules/stripe/lib/resources/Accounts.js ?  None of them seem to do any checking of what's returned by Stripe so if there's any error messages returned from Stripe, we wouldn't be handling them. Also can there be timeouts there where the update() just never returns? You'd then get this await never finishing:
https://github.com/HabitRPG/habitica/blob/develop/website/server/models/group.js#L1420
but it doesn't look like there's any consequences for that - the group's membership would have been changed by then and if the payment update had failed, wouldn't it just keep on being wrong indefinitely?

For shanaqui's point about making this retroactive: even if that code always performs correctly now, any Stripe group plan that had membership adjusted before the code was changed would be making incorrect payments now. Ideally we'd run some sort of check for that although I'm not sure how much ability we have to query Stripe subscription amounts from a script.

**Comment by shanaqui** [comment]
It was after. I can't pin it down to an exact date, but from my records I didn't _have_ a group plan before March 2017, and I had an email conversation with @alys asking her to explain aspects of a receipt that included my third group member in which I asked if she would keep the jackalope if I removed her from the group on the 10th-11th April 2017, so I would have removed her from the group after receiving that reply.

**Comment by Alys** [comment]
I've confirmed from Habitica's records that shanaqui's group plan had three members on 11 April 2017, so the removal of one member did occur after that code was modified.

**Comment by shanaqui** [comment]
Is there any progress on this? I know my issue has been fixed now by Alys manually, but people being able to trust us with their financial details is important, and I feel uncomfortable about it personally right now.

**Comment by TheHollidayInn** [comment]
Right before `chargeForAdditionalGroupMember` is called we update the member count: https://github.com/HabitRPG/habitica/blob/ac973ee753c9001dd683f8a0764b5f2da2c4bf55/website/server/models/group.js#L1515

As far as retro active, I'll ping Sabe about a migration we can do. And we can add another member check here for extra: https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/groups.js#L199

**Comment by Alys** [comment]
It's not the memberCount that causes the problem, it's the fact that sometimes membership changes aren't successfully sent to Stripe - the second part of this comment: https://github.com/HabitRPG/habitica/issues/10124#issuecomment-372151710 ("that code does wait for await stripeApi.subscriptions.update() to finish but doesn't check any return value....") although I'm not totally sure if I'm on the right track there. My understanding is that unless our code has enough error checking to be sure that membership changes are always passed on to Stripe successfully and that any return codes from Stripe are checked for success/failure (and failures handled appropriately), then this problem could still occur.


A retroactive fix for this would need to compare the current number of members with the quantity that's stored in Stripe's recurring payment's data (i.e., we'd have to check in Stripe manually for each Group Plan or use Stripe's API to query the data). I'm not sure if that's needed though because I hope that anyone getting an incorrect payment would have told us about it. :(

**Comment by TheHollidayInn** [comment]
Ensuring Stripe actually completes is separate, but still something we can add.

The migration Sabe is working on will be retroactive for both Stripe and Amazon. It will also fix errors from in incomplete upgrades.

**Comment by SabreCat** [comment]
The migration in the associated PR has run, reconciling member counts and plan quantities for all active plans. We'll run it again in a week or two to see if the issue has recurred since!

**Comment by Alys** [comment]
Another example of this was reported by email yesterday, with a follow-up email today:

"I'm having a weird bug with my Habitica Group that has my account listed twice in the group.  There are only 4 people in the group - myself as the primary and my 3 siblings.  However, I have been charged for 5 people total (1 primary for $9.00 and 4 secondaries for $3.00 ea).  I'd like to remove the extra account and the extra payment."

"I joined last week and this bug has been present since I created the group on the first day...
The payment method is through Amazon Pay..."

groupID c392537f-28d5-41d1-bb2e-e0f02d00dc9a

Our Slack records show the times that the group plan was created and guild members added:
- Tue Jun 19 2018 01:24:19 GMT+0000 (UTC) - group plan created, leader added
- Tue Jun 19 2018 01:34:05 GMT+0000 (UTC) - member added
- Tue Jun 19 2018 15:00:45 GMT+0000 (UTC) - member added - the SAME member as the one at 01:34:05
- Tue Jun 19 2018 05:49:27 GMT+0000 (UTC) - a different member added
- Tue Jun 19 2018 01:57:37 GMT+0000 (UTC) - another different member added

For that user that was added twice, Amplitude shows the join/subscribe events and also an `unsubscribe` event at June 19, 2018 2:00:27 am UTC so I'm guessing that the user (accidentally) was removed from the guild or left the guild then but the memberCount wasn't updated.

Amazon shows a $9 payment for the group+leader and four $3 payments corresponding to the four group members addition events above. There is no refund corresponding to the person being removed from the guild (I've issued a refund manually).

So if the code that removes members from a group plan is modified to catch errors/timeouts and re-process the failed actions, over-payments might be prevented.

Interestingly, for this case, the group's `purchased.plan.quantity` field is wrong but in the opposite direction: it is set to 3 (i.e., a one-person group) when it should be 6 (four people). I have not changed that value in case anyone wants to confirm its current incorrect status, but it should be changed by an admin at some point. I don't recall seeing this specific problem before - iirc previously the `quantity` fields have been incorrect in the same direction as `memberCount`. @SabreCat I don't suppose a second migration was run between the 19th (UTC) and now? Could it have set `quantity` incorrectly? I'm guessing not since it would have adjusted `memberCount` too I assume, but I thought it worth asking just in case. :)

I can give User IDs if desired, although if I'm not around when its requested they can be obtained from the groupId of course, and searches for the User IDs in moderator Slack will show the records referred to above. I haven't copied the User IDs here to keep the group's member list private.

**Comment by SabreCat** [comment]
Hmm! No, I don't think we ran anything else after that first go....

**Comment by TheHollidayInn** [comment]
I think there is a chance we set quantity wrong during debug, but also Im pretty sure Amazon doesn't use the quantity field. We can run the migration again this week to debug the member count issues that still exist with Group plans

**Comment by SabreCat** [comment]
looking through the code, the `quantity` field is sort of vestigial--we either don't use it at all, or recheck what it ought to be and set it to the appropriate value whenever the list of members changes. And we haven't really seen issues with inappropriate quantity-based charges in recent memory (people getting confused by Stripe's invoice prorating, yes; people not realizing that they'll be charged more for inviting people to their upgraded party, yes; outright overcharges, no). Closing this issue as no longer extant or at least no longer important.
