### ISSUE TITLE
pinning Rainbow potion from different locations gives different pinned item, different unpin behaviour

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10135]
If you pin the Rainbow potion from the Featured Items section of the Shop, you get this in your `pinnedItems` array:
```
        {
            "path": "hatchingPotions.Rainbow",
            "type": "hatchingPotions",
            "_id": "5aa9a0516e390d0012d0e8c1"
        }
```

As soon as you buy it once from your Rewards column, it becomes unpinned.

If you pin it from the Magic Hatching Potions section of the Shop, you get this:
```
        {
            "path": "premiumHatchingPotions.Rainbow",
            "type": "premiumHatchingPotion",
            "_id": "5aa9a0ad6c3e55001e1879b5"
        }
```
When you buy it from the Rewards column, it remains pinned. This feels to me like the correct behaviour because people are more likely to want to make purchases at different times if they've pinned it.

I'm marking this as suggestion-discussion so that the staff can decide whether any of this needs to be changed.

**Comment by SabreCat** [comment]
Same for the Shimmer potions. `premiumHatchingPotion` and remaining pinned after purchase is definitely the better behavior.

**Comment by Alys** [comment]
I'm working on this.
