### ISSUE TITLE
"Like" button in inbox messages does not work

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10132]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

"Like" buttons appear on messages in the user's private inbox, but clicking it produces an error "Group not found or you don't have access".

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
The attempt produces a 404 error with a call to a URL of the form https://habitica.com/api/v3/groups/undefined/chat/a8f3994c-4643-42c8-b9bc-7e564c96b730/like

**Comment by ESWAT** [comment]
Are there even groups associated with these kinds of private messages between users?

I tried looking into this more and reading the API docs, but it seems the API endpoint being used doesn’t match the data these user messages actually have? (I don’t see a `groupId` being associated with these types of messages, or I don’t have a clear understanding of what the `Group` object is associated with.

**Comment by paglias** [comment]
Inbox messages aren't linked to any group but simply stored inside each user document under the inbox object

**Comment by Alys** [comment]
I think the fix for this should be to remove the like button.
