### ISSUE TITLE
Search box in Members modal not functioning

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10130]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The search box at the top of the View Party modal doesn't appear to do anything. It should filter the list based on the expression entered, but typing characters into the form doesn't update the displayed items.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

```
Uncaught (in promise) TypeError: this.$store.state.memberModalOptions.fetchMoreMembers is not a function
    at a.<anonymous> (https://habitrpg-staging.herokuapp.com/static/js/app.cf2f1c99f2b27df2b08c.js:1:449238)
    at r (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:228849)
    at Generator._invoke (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:229894)
    at Generator.t.(anonymous function) [as next] (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:229028)
    at r (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:228849)
    at e (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:229084)
    at https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:229407
    at new Promise (<anonymous>)
    at r (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:229381)
    at u.n [as _invoke] (https://habitrpg-staging.herokuapp.com/static/js/vendor.6189e50bf5078a3eb69a.js:6:229443)
```

**Comment by paglias** [comment]
Hmm, from a quick search that function doesn't exist, but it seems that in some places loadMembers is assigned to it

<img width="838" alt="schermata 2018-03-12 alle 13 34 17" src="https://user-images.githubusercontent.com/589911/37308083-266b7242-25fa-11e8-8b31-8d21987473f2.png">

cc @TheHollidayInn 

I'll wait to fix this one in case there's somethign I'm missing

**Comment by SabreCat** [comment]
Getting reports that this, or something very similar, also affects Guilds. @paglias did you have a fix in mind already?

𝕹𝖆𝖊𝕿𝖍𝖊𝕹𝖊𝖗𝖉 (8f89c805-334e-48cf-b095-0eba848f5974): 

>I keep having various bugs when looking at my guild members. Sometimes there's nothing there, sometimes it brings up the list from an entirely different guild, and always (not in my guild since I don't need to yet but others) when I search for someone it might, i'll type in a couple of letters and people will show up, but only for half a second and then It'll go back to the entire list.

**Comment by paglias** [comment]
Looking into this now

**Comment by paglias** [comment]
It's a bit messy, I can refactor it but it'll take a bit

**Comment by paglias** [comment]
I'll work on this as part of a bigger refactor of the members modals, so it'll take a few days

**Comment by TheHollidayInn** [comment]
If we can remove the member modal options from the state and create a new event for the modal (as I've been moving our modals to) this will improve. If you want me to take this on, let me know as I've been refactoring the launching of modals.

**Comment by TheHollidayInn** [comment]
This seems to be fixed. I'm going to post a PR to fix the modal code.
