### ISSUE TITLE
some locales strings can't be translated from Transifex due to errors in the key, code, etc

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10148]
alfill (e98e3a47-d06a-49d7-9a74-2a8b5deb9595) has very kindly worked with other translators to compile a list of translation problems: https://docs.google.com/document/d/1FSOjm782T8C0W9cZPXq_-1NDNM-p2ewJfjZwpAGMX_I/edit?usp=sharing

In the Report a Bug guild, alfill writes:

_"Hello. Commonwealth i18n guild found several non-localizable bugs, strings that can't be translated from transifex due to errors in the key/code, etc .. in [list](https://docs.google.com/document/d/1FSOjm782T8C0W9cZPXq_-1NDNM-p2ewJfjZwpAGMX_I/edit?usp=sharing) - need the participation of programmers"_

There'll likely be a variety of fixes needed for these, some easy, some perhaps harder. I'm going to leave this as suggestion-discussion for a few days in case the staff want to look it over, but if there's no objections after that or if they don't claim it themselves, I'll mark it as help wanted. We might want to allow coders to claim specific pieces rather than one person doing all of it.

**Comment by marvinrabe** [comment]
https://github.com/HabitRPG/habitica/pull/10317 fixes:

- Challenge Page Sidebar
- "Hide Missing"
- Guilds Page Sidebar

**Comment by alfill** [comment]
Hello there. Thank you, @marvinrabe very much for the corrections. Most of the amendments were later translated by Maximilian Antipenko, and this task looks decided. 
@Alys, @SabreCat, thank you too, now this issue is completed.

**Comment by Alys** [comment]
@alfill Oh awesome! Thanks for letting us know!
