### ISSUE TITLE
"User not found"

### ISSUE THREAD

**Issue by kylars** [HabitRPG/habitica#1014]
I have tried logging in countless times. I saved my password, so it's already filled in, and normally it works but I tried it today and it continually tells me it doesn't exist. I checked with my extension(which still works/tracks my websites), and the username's the same on there as what I'm entering. So clearly, it exists.. I also tried clicking the "forget password" but it tells me the email I'm entering hasn't been used to sign up. 
This happened once or twice before, but after refreshing the page, I was able to log in. However, I've done that and more, and it still says my account doesn't exist.

**Comment by lefnire** [comment]
what's a uname / email / somethign I can look you up by?

**Comment by kylars** [comment]
username is kylarski

**Comment by lefnire** [comment]
Not showing any users by that uname in current db, or any backup snaps.
Capitalization correct? Sure you didn't reg via facebook? I can find your
user if you can provide a super-specific task title I can search for, like
"Help James move Sunday"

**Comment by kylars** [comment]
Yeah, I'm positive it's all in lowercase.
I even have my API code, but when I tried to have someone invite me into their group with it, it seemed to not exist anymore. ( 8ffe64b1-380d-49b0-9edf-cab951eb0596 )
As for tasks, I can't remember any specific ones, any I made last night were deleted from the server acting up..

**Comment by kylars** [comment]
Sorry, that's my ID code, I think. I didn't realize there was a difference between API and ID. (It's the code under the "party" tab, whichever that one is.)

**Comment by lefnire** [comment]
When was the last time you successfully used the site? Looks like you got
hit by
https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found.
That user id sure enough shows you in the db, but the auth property is
empty as far back as my database snaps go. If you can tell me the last time
you successfully played, I can restore that time. Create a new user with
the uname / pw that you want, and tell me the new user id - i'll splice
that auth property into the old user object

**Comment by Elkian** [comment]
This is happening to me too, account Elkian. I logged out because I didn't want to refresh and lose five or six more hours on error pages, and now my account doesn't exist!

**Comment by lefnire** [comment]
still waiting for @kylars response, @Elkian can you give me same info? UUID, last successful site-usage, etc?

**Comment by Elkian** [comment]
I used it successfully last night, around 11 pm CST. Don't know what you mean by UUID.

**Comment by Elkian** [comment]
Weird, I managed to sign in with Facebook but not my actual username? Pretty sure I signed up with the username to begin with.

**Comment by kylars** [comment]
new user ID is 6f8cbeb4-9627-47f7-8777-ae661bbad487
the last time I was able to play was May 20th at 19:00 or so.

**Comment by wc8** [comment]
@Elkian you can find the user id under user>  settings> API

**Comment by lefnire** [comment]
Ok, so @Elkian you're sorted? All your data is there under your facebook one? 

@kylars you were definitely hit by the old whopper bug, which I profusely apologize for. I'm downloading a snapshot for 5/21 (which was before the last preen-cron was run, which would have hit your account) and I'll restore you as soon as that's running

**Comment by lefnire** [comment]
ok, @kylars you should be sorted now, give that a whirl

**Comment by kylars** [comment]
It seems to be working now. Thank you!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
