### ISSUE TITLE
Difficulty editing Guild category tags

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10155]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 7f14ed62-5408-4e1b-be83-ada62d504931
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Editing category tags for a Guild that lacks them is misbehaving; ~the behavior is worse on Staging~.

~In Staging,~ nothing happens if I click the "None" button under Categories.
~In Production, clicking "None" brings up the category list, and I can check the boxes, but I can't collapse the list back down. I have to instead click the "Update" button to finish my whole Guild editing session, after which it _looks_ like my changes haven't saved; once I refresh the page, however, the categories have been applied.~

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

Possibly unrelated, but:

```
vue.runtime.esm.js:1737 TypeError: Cannot read property 'profile' of undefined
    at a.currentLeader (2.8ae4074f1d36a513474b.js:1044)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.evaluate (vue.runtime.esm.js:3245)
    at a.currentLeader (vue.runtime.esm.js:3503)
    at a (groupFormModal.vue?0cd9:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.run (vue.runtime.esm.js:3215)
    at Rt (vue.runtime.esm.js:2977)
ot @ vue.runtime.esm.js:1737
```

**Comment by Alys** [comment]
I've edited the top post to remove the staging/production details, since the worse bug from staging is now on production.

**Comment by Alys** [comment]
This seems to be intermittent. A player who was unable to get the Category button to respond earlier has just reported that they tried again and it worked.

**Comment by TheHollidayInn** [comment]
This seems to be fixed.
