### ISSUE TITLE
Rewards have decimals

### ISSUE THREAD

**Issue by w13** [HabitRPG/habitica#1016]
My reward prices have decimal spaces in them like "21.27" and it's making that gold coin icon to go to the next line, making the layout look ugly.

**Comment by freakizoid82** [comment]
If you've bought armor or any other weapons you'll see that they increase your defense and Exp. gain on your profile, and they are usually percentages like 3%, 4%...etc. This is what is causing the decimal points, because you are earning 3%, 4% or whatever more per Exp. gain/reward.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
