### ISSUE TITLE
Sound effects no longer working

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10172]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The Web site no longer plays sound effects for relevant actions.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

```
vue.runtime.esm.js:1737 TypeError: Cannot read property 'load' of undefined
    at De.<anonymous> (generated:263)
    at De.t.$emit (vue.runtime.esm.js:2534)
    at a.<anonymous> (app.40a8b11f942dc4e3e19a.js:21832)
    at r (runtime.js:62)
    at Generator._invoke (runtime.js:296)
    at Generator.t.(/anonymous function) [as next] (https://habitrpg-staging.herokuapp.com/static/js/vendor.2d49d9f62410c93e6e62.js:6:229715)
    at r (runtime.js:62)
    at e (runtime.js:152)
    at runtime.js:162
```

**Comment by Alys** [comment]
According to https://github.com/HabitRPG/habitica/pull/10179#issuecomment-377031806 , this has been fixed.
