### ISSUE TITLE
Didn't lose money when purchasing items

### ISSUE THREAD

**Issue by freakizoid82** [HabitRPG/habitica#1017]
I had been saving up to buy the chain coif, but when I purchased it I didn't lose any coins from my purse. I even tried buying another item, the leather armor, and was able to do so. Only then did the coins get subtracted from my wallet. Is it a service error or just a bug? Or something else?

**Comment by nafoster** [comment]
This happened to me today as well around 1pm EST. I was able to buy the Enforcer Shield and Red Helm without losing money. However, when I went to purchase the Red Shield around 4pm EST, it subtracted the proper amount.

**Comment by lorian** [comment]
This happened to me as well a couple days ago; I bought the Golden Sword and still had my 120g. Buying a set of armor afterwards subtracted its normal cost, though.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
