### ISSUE TITLE
Task page search bar only searches task titles, not Notes

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10173]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Previously, users could include search terms in the Notes field of their tasks, and entering those search terms in the Search bar on the Tasks page would narrow down to tasks including those terms in their notes.

Now, however, the search only applies to task titles and checklist items, a substantial downgrade to the functionality.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None that occur while searching specifically.

**Comment by gabrielsiedler** [comment]
It seems that the logic stills the same, it searches also for `note`. But for some reason the **task** object has the key `notes` instead (some refactor maybe?).

```
return (
  task.text.toLowerCase().indexOf(searchTextLowerCase) > -1 ||
  (task.note && task.note.toLowerCase().indexOf(searchTextLowerCase) > -1) ||
  (task.checklist && task.checklist.length > 0 &&
  task.checklist.some(checkItem => checkItem.text.toLowerCase().indexOf(searchTextLowerCase) > -1))
);
```

To fix this just change `task.note` to `task.notes` on both calls on `/website/client/components/tasks/column.vue` line **587**.

I'm happy to create a PR to fix this if you want.
