### ISSUE TITLE
intermittent failures of website UI changes and syncing (guild joining, pet hatching, maybe others)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10178]
Over the past three days in the Report a Bug guild, @Ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b, currently called Mage in Habitica) has been reporting intermittent problems with the website not updating correctly when they take an action and with syncing not being enough to cause the correct UI elements to appear. I've copied their posts below with annotations for context.

**"I joined a guild, the 'Join' button didn't disappear so I clicked it again and _[received theuserAlreadyInGroup notification]_"**  _I.e., they had succcessfully joined the guild on their first click but the expected join/leave button change didn't occur._

**"I joined from the guild page"** _[i.e., not from the Discover Guilds page nor from an invitation]_

**"I am using chrome, and it is not a consistent issue. Sometimes I have sync hiccups, like one time I hatch my pets from the stables and they appear immediately, and the next instead I need to reload the page to have the pet appear (not even sync works)."**

@Ieahleen the next time it happens, could you please post here with a description of the event and the date and time it occurred, including the time zone you are in?

**Comment by majestic-owl448** [comment]
It happened right now, I have hatched first a Golden Whale, it didn't
appear right away so I started registering, and tried to hatch a White
Whale. Both appeared after Reloading.
https://drive.google.com/open?id=1moArMh_mDyfPFeezqUbetZ_oxI5LgjOa

It hadn't had the chance to happen before as I didn't have eggs to hatch.

Time: 10:15~10:20 AM UTC+2

**Comment by Alys** [comment]
@Ieahleen Thank you!

Nothing's showing up in our logs in Loggly for your account for that time so there were no server errors of the kind that we capture there.

If you still have that browser tab open, can you copy everything in the [console](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers) and paste it into a comment here? Don't worry about formatting.

**Comment by majestic-owl448** [comment]
I will when/if it happens again. I don't have the window open anymore.
Sorry, I didn't think of it.

**Comment by Alys** [comment]
No worries. I didn't think to ask for it in my first post here!

**Comment by majestic-owl448** [comment]
So, I had three T-Rex eggs, I hatched the first, and nothing unusual, I hatched the secold and it didn't appear, I hatched the third, same. Now I can keep clicking on the pawprints and then on "Hatch", and there is no error shown in the upper right corner, but there is a new one in the console everytime.

```
moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at g.zone (https://habitica.com/static/js/vendor.a9d104f02bc947765230.js:1:12941)
    at Object.<anonymous> (https://habitica.com/static/js/app.0fc32c695b2eae6986a8.js:1:243005)
    at n (https://habitica.com/static/js/manifest.3595f5bb30fab3fc376c.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.0fc32c695b2eae6986a8.js:1:18284)
    at n (https://habitica.com/static/js/manifest.3595f5bb30fab3fc376c.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.0fc32c695b2eae6986a8.js:1:348127)
    at n (https://habitica.com/static/js/manifest.3595f5bb30fab3fc376c.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.0fc32c695b2eae6986a8.js:1:583334)
    at n (https://habitica.com/static/js/manifest.3595f5bb30fab3fc376c.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.0fc32c695b2eae6986a8.js:1:342127)
x @ moment.js:293
vue.runtime.esm.js:1737 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (login-incentives.vue?fca4:74)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.evaluate (vue.runtime.esm.js:3245)
    at a.nextReward (vue.runtime.esm.js:3503)
    at a.s (login-incentives.vue?e357:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at Ti.get (vue.runtime.esm.js:3138)
    at new Ti (vue.runtime.esm.js:3127)
    at $t (vue.runtime.esm.js:2791)
ot @ vue.runtime.esm.js:1737
findChallenges:1 The SSL certificate used to load resources from https://images-na.ssl-images-amazon.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
vue.runtime.esm.js:1737 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (login-incentives.vue?fca4:74)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.evaluate (vue.runtime.esm.js:3245)
    at a.nextReward (vue.runtime.esm.js:3503)
    at a.s (login-incentives.vue?e357:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.run (vue.runtime.esm.js:3215)
    at Rt (vue.runtime.esm.js:2977)
ot @ vue.runtime.esm.js:1737
hatch.js:19 Uncaught t
2logs-01.loggly.com/inputs/undefined/tag/ClientJS Failed to load resource: the server responded with a status of 403 (Forbidden)
stable:1 Failed to load https://logs-01.loggly.com/inputs/undefined/tag/ClientJS: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://habitica.com' is therefore not allowed access. The response had HTTP status code 403.
hatch.js:19 Uncaught t
2logs-01.loggly.com/inputs/undefined/tag/ClientJS Failed to load resource: the server responded with a status of 403 (Forbidden)
stable:1 Failed to load https://logs-01.loggly.com/inputs/undefined/tag/ClientJS: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://habitica.com' is therefore not allowed access. The response had HTTP status code 403.
```

**Comment by Alys** [comment]
@Ieahleen Thank you for that! There's a couple of interesting parts:


```
The SSL certificate used to load resources from https://images-na.ssl-images-amazon.com
will be distrusted in M70. Once distrusted, users will be prevented from loading these
resources. See https://g.co/chrome/symantecpkicerts for more information.
```
That won't be related to this issue but it's good that we know about it!

```
hatch.js:19 Uncaught t
2logs-01.loggly.com/inputs/undefined/tag/ClientJS Failed to load resource: the server responded with a status of 403 (Forbidden)
stable:1 Failed to load https://logs-01.loggly.com/inputs/undefined/tag/ClientJS: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://habitica.com' is therefore not allowed access. The response had HTTP status code 403.
hatch.js:19 Uncaught t
2logs-01.loggly.com/inputs/undefined/tag/ClientJS Failed to load resource: the server responded with a status of 403 (Forbidden)
stable:1 Failed to load https://logs-01.loggly.com/inputs/undefined/tag/ClientJS: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://habitica.com' is therefore not allowed access. The response had HTTP status code 403.
```
I've seen those "No 'Access-Control-Allow-Origin' header" messages in other contexts when the server has been having trouble (e.g., when trying to fetch guild chats while 50* errors are common). Maybe what's happening here is that Habitica's just not able to load the images for the new pets due to server troubles.

**Comment by TheHollidayInn** [comment]
This sounds like oddities that have passed/fixed with code. Plus the fact that we don't have real time. Do we need to do anything here? I'd like to wait for new reports.

**Comment by Alys** [comment]
I'm closing it but we can reopen if anyone reports it still happening.
