### ISSUE TITLE
should not be able to buy equipment from a class that you are not currently playing

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10183]
When you lose an old Grand Gala equipment piece due to death and then change class and then try to buy the piece back, you get no notification that you're not able to buy it. If you try to buy it, you see a notification saying "You bought [gear name]" (although gold is not subtracted and the item is not actually bought).

The correct behaviour is:
- When you click on the buy button, you should see a message saying that you can't buy that item because you are not the right class. This message must come from the API so that it works regardless of how you try to buy the item (e.g., using a third-party tool or a direct API command).
- The buy button should not be clickable (you might want to implement this after fully implementing and testing the above point).

When you try to buy a non-Gala piece of gear from the wrong class, you CAN buy it. This is completely wrong - you should not be able to. The API and website's UI should both prevent it as described above.

(I suspect that the reason you can't buy the Gala gear is because the pieces I tested on were from a non-Spring gala and so the seasonal limitation was taking effect. If you tried to buy a piece from the current Gala that you'd lost recently due to death and then changed class, you'd probably be able to buy it.)

_Thanks to lulumiller (49e7da73-62a4-43eb-a292-a48beb43c5e5) for reporting this._

**Comment by allie5** [comment]
@Alys I'd like to take a look at this one as if no one else has claimed it

**Comment by Alys** [comment]
@alliemoon Thank you! Can you wait for a couple of days though? The staff were talking last week about maybe changing how this works and I'm not sure if a decision was reached.

**Comment by Alys** [comment]
@alliemoon there's been no more discussion about this and no comments here so I think it's good for you to work on if you still want to. Any final objections from anyone?

**Comment by flhat** [comment]
I'll add a PR for this one.
