### ISSUE TITLE
Solid purple background behind modals

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#10184]
A recent change has incorrectly caused the background behind modals to become a solid purple, instead of their normal translucent overlay. Additionally, the modals are now off-center, starting higher up on the page.
<img width="1418" alt="screen shot 2018-03-26 at 10 13 26 am" src="https://user-images.githubusercontent.com/3494081/37922168-b9b92c1a-30e0-11e8-8046-5be320c7d967.png">
<img width="1429" alt="screen shot 2018-03-26 at 10 11 18 am" src="https://user-images.githubusercontent.com/3494081/37922169-b9d409b8-30e0-11e8-88d0-245abcf9c2a4.png">

Both should be returned to normal.

**Comment by hathix** [comment]
Hello! Loyal Habitician here. I think I've isolated the background color problem. In `app.vue`, there's this CSS:

```
.modal-backdrop.show {
    opacity: 1 !important;
    background-color: #432874 !important;
}
```

When I remove the `opacity` line in my browser's dev console, the purple becomes transparent (as it was before, if I recall correctly) and not solid.

I'm not sure how to fix the off-center problem, but I did notice that the `modal-dialog` class has `1.75rem` of top margin, making the dialog appear 1.75rem below the top of the page, not in the middle.

I haven't contributed before but I can take a crack at the background color problem, if needed!

**Comment by lemoness** [comment]
@hathix Thank you so much! Let us know if you have any questions about contributing.

I've updated the labels on this ticket.

**Comment by citrusella** [comment]
Is it important to mention the inn banner at the top of the page when you're checked in is apparently behind the background? Is it supposed to be behind the background or on the same basic level as the navbar? (I suppose this could be an entirely different issue, though...)

**Comment by beffymaroo** [comment]
@hathix @SabreCat Are there lingering things with this issue that still need fixes after merging the above PR?

**Comment by TheHollidayInn** [comment]
The above PR is merged and the transparency seems to be fixed on production.
