### ISSUE TITLE
Multiple Problems

### ISSUE THREAD

**Issue by in2video** [HabitRPG/habitica#1018]
My account Brian Coleman / in2video

User ID:  d8db094b-5fc4-4197-b1d7-15764a61a49b

I have been having lots of problems logging in and syncing my data across multiple computers.  It takes a long time to load.  Also currently the application is not accepting entries into any fields.  I can type in the boxes, but they will not enter.  Currently now it won't even let me back to my task listings.  It stopped working right when I signed in with Chrome and was syncing my chrome details for the first time.  Since then it just has not worked at all.  Several days have passed and nothing seems to be getting better.  Perhaps you can just reset my account (which I have tried on my end and didn't seem to help) and I can start over.  I have tried uninstalling the chrome app and reinstalling as well.  Thanks.

**Comment by lefnire** [comment]
due to http://habitrpg.tumblr.com/post/51082061058/whats-with-the-downtime , it's been quite bad for about 3 days - we're working hard to get this fixed, stay tuned

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
