### ISSUE TITLE
Consider Moving Blacksmith/Developer Docs to Repository

### ISSUE THREAD

**Issue by ESWAT** [HabitRPG/habitica#10198]
Has there been discussion about moving the developer-specific documentation on Wikia to this repo, either as GitHub wiki pages or Markdown files in the actual git repo?

In my opinion it would be better for two reasons:
1. Trivial to update since we can continue to use Markdown in whatever editor we want to make changes
2. Closer to the “source of truth”

With those two reasons I think it would mitigate the main issue I have with the docs on Wikia as a contributor: *out-of-date information*

I’ve tried updating some documentation for getting Habitica running in Docker but editing through their Wikia page seems like a PITA when every other project I work on has an easier format to work with for these kinds of purposes and very close to the source code.

I’m not quite sure the Blacksmith docs being on Wikia makes them more accessible to new contributors either since it seems to do a poorer job of displaying `code` than GitHub would.

**Comment by Alys** [comment]
Having them on the wiki with the other documentation has significant advantages, such as allowing non-technical wiki editors to modiify them (useful for cases where non-technical details need to be changed), being able to use wiki templates throughout them (e.g., a message can be added  at the top of all blacksmith pages by editing a single Wikia file - that was helpful when API v3 was introduced; another example is the github label templates), and consistency with the documentation for the other contributor types. Markdown files in the repo have a higher barrier to entry - an editor needs to know advanced Markdown (albeit not a large barrier), and needs to be familiar with creating pull requests or willing to learn them (could be scary for non-tech users), and there'd be a delay until the pull request was merged by an admin (sometimes that will be a long delay when admins have several competing duties). GitHub wiki pages wouldn't have most of those disadvantages but I don't think they'd have advantages over Wikia pages either.

If you'd like to discuss it further, the Aspiring Blacksmiths guild would be a better place. GitHub issues are mostly for bugs that need fixing or features approved for implementation by the staff.

Out of date information in the blacksmith pages on the wiki is something we definitely want to fix. When you see any information that's incorrect, if you'd prefer to not fix it yourself, please mention it in either the Aspiring Blacksmiths guild (best if you want technical input from other players) or the Wizards of the Wiki guild (best if you don't need technical input and just want someone to edit the pages).

Display of <code> tags on the wiki is easy to fix - I or another wiki admin can adjust the css files. If you have ideas for how to improve the code display, mention it in the Wizards of the Wiki guild.
