### ISSUE TITLE
decorations cover Featured Quests label in Shops > Quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10195]
Butterflies cover the "Featured Quests" label in the Quest Shop:

![img](https://i.gyazo.com/4a978cbe59942e0fd9012d6309076bc9.png)

Something similar happened in Shops > Market in the previous Grand Gala as reported in https://github.com/HabitRPG/habitica/issues/10037
The fix for that was to change the z-index of the Featured Items sign so that it would never be covered by the background (https://github.com/HabitRPG/habitica/pull/10067/files ). The same fix might work for this, so I'm marking this as an easy issue.

**Comment by GabrielBarbosaGV** [comment]
Hello! I want to help, it would be my first contribution. However, here I see the butterflies around the button, not on top of it. If it's not much to ask, how do I move them to the button region so I can test the fix? Thank you very much!
![togq](https://user-images.githubusercontent.com/29243693/38061785-1ea8c53a-32c7-11e8-894b-112bdf91818f.png)

**Comment by Alys** [comment]
To reproduce this if it doesn't happen as soon as you load the page, try changing your browser's zoom level or window size.
