### ISSUE TITLE
Trend graphs behave oddly for multiple hits/day on a habit

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1019]
From what I can tell, each click on a Habit (up or down) generates a new column in the progress graph. That makes some sense, but since the X axis label shows dates, and a habit can be marked multiple times per day, this leads to several consecutive labels showing the same date. It looks strange!

Suggestions:
- Make the progress graphs strictly day-by-day, where each data point represents all the score you've racked up/decremented that day over however many clicks.
- Have them work click-by-click as they do now, but hide repeated labels on the axis.

**Comment by wc8** [comment]
I'm in favor of the day by day suggestion, each data point representing cumulative score for the day.

**Comment by ghost** [comment]
Day by day sounds most logical yes

**Comment by deilann** [comment]
Graphs are being seriously reworked, and have their own tickets now that are more up-to-date.
