### ISSUE TITLE
User interaction submenu on Party modal Invites tab does nothing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10196]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Under at least some circumstances (the issue doesn't reproduce 100% of the time, though it's not clear why not), the three-dots menu button next to a user in the "Invites" tab of the party members modal doesn't do anything.

To reproduce:

1. Invite someone to your party.
2. Go to View Party, then Invites.
3. Click the "..." button at the right. If you hit this issue, nothing will happen. Compare to clicking the same button under the Members tab, which lets you send a message to the party member.

You should at least be able to rescind the party invitation from here, and preferably also have the same option of sending a private message to the user.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None relevant.

**Comment by shanaqui** [comment]
For reference, this is what I can get (Windows, Chrome):

![image](https://user-images.githubusercontent.com/8144640/38063945-c6925690-32f3-11e8-9688-bda9aca9b5ed.png)

I can message the user by clicking on the avatar and going through their profile as usual, so the option isn't entirely absent, but to be consistent with the members tab it'd be handy and make sense to people if you could do it there too.

**Comment by ESWAT** [comment]
So I tried looking into this and able to reproduce it easily locally… actually I can’t get that button to work correctly as a group leader.

In my case it looks like the `members-modal` component doesn’t have all the `group` data necessary to determine if the user is the group leader, so it always shows actions that only a regular member would have access to.

But I’ve had no luck in actually fixing this, so I’m not claiming this issue.

**Comment by yb50110** [comment]
Hey all, I was the one who created a post about this on the bug guild. Today, I found out that the "Remove Invitation" shows up for the modal window that opens when access through the main party page's button:

<img width="203" alt="screen shot 2018-04-08 at 15 26 26" src="https://user-images.githubusercontent.com/31864715/38472160-3b8b580c-3b41-11e8-8e26-69786e4c606d.png"> 

Although my report on this bug was on the "View Party" button on the top-right of the page, thought I should share for more information.

**Comment by texastoland** [comment]
> Today, I found out that the "Remove Invitation" shows up for the modal window that opens when access through the main party page's button:

This was driving me crazy. They should be the same. Thank you @yb50110!
