### ISSUE TITLE
converting from moment().zone to moment().utcOffset

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10209]
`moment().zone is deprecated, use moment().utcOffset instead.` http://momentjs.com/guides/#/warnings/zone/

From the utcOffset docs:

> NOTE: Unlike moment.fn.zone this function returns the real offset from UTC, not the reverse offset (as returned by Date.prototype.getTimezoneOffset).

It's not a matter of merely changing the code to use `moment().utcOffset` instead of `moment().zone` because we store the `zone` value in the user document in two places. Here's an example taken just after a user changed time zones from UTC+0 to UTC+10:
```
    "preferences": {
        "timezoneOffset": -600,
        "timezoneOffsetAtLastCron": 0
    },
```
Despite the name of those preference values, they are actually `moment().zone` values.

Those preference values are set by both the mobile apps and the website so we can't change those values from `zone` to `utcOffset` because any player who used the website and a non-upgraded app would get inconsistent data stored in their account. Also the values might be used by third-party tools and so removing or changing them would be a breaking change.

**I guess we can change our code to use `moment().utcOffset` but keep storing `moment().zone` values in the preferences and have our own function to convert between the formats immediately after the preference data is read from the user's document and just before it's written back.** It's a bit messy but it would be backwards compatible. We could change the preferences values in API v4.

Any better ideas?

As @crookedneighbor said in https://github.com/HabitRPG/habitica/pull/7053 this isn't urgent until the next version of moment comes out and we want to upgrade.

Code that uses `moment().zone`:  _[EDIT 2020-03-31: this list of code will be outdated now]_
```
$ git grep "\.zone"
test/api/v3/integration/tasks/GET-tasks_user.test.js:161:    let startDate = moment().zone(timezone).subtract('4', 'days').startOf('day').toISOString();
test/api/v3/integration/tasks/GET-tasks_user.test.js:188:    let startDate = moment().zone(timezone).subtract('4', 'days').startOf('day').toISOString();
test/api/v3/integration/tasks/GET-tasks_user.test.js:214:    let startDate = moment().zone(timezone).subtract('4', 'days').startOf('day').toISOString();
test/api/v3/unit/libs/preening.test.js:12:      now: Number(moment('2013-10-20').zone(0).startOf('day').toDate()),
test/api/v3/unit/models/user.test.js:467:      const timezoneOffset = moment().zone('-06:00').zone();
test/api/v3/unit/models/user.test.js:484:      const timezoneOffset = moment().zone('-08:00').zone();
test/common/shouldDo.test.js:82:        day = moment().zone(options.timezoneOffset).startOf('day').add(6, 'hours').toDate();
test/common/shouldDo.test.js:83:        dailyTask.startDate = moment().zone(options.timezoneOffset).startOf('day').toDate();
test/common/shouldDo.test.js:89:        day = moment().zone(options.timezoneOffset).startOf('day').add(2, 'hours').toDate();
test/common/shouldDo.test.js:90:        dailyTask.startDate = moment().zone(options.timezoneOffset).startOf('day').toDate();
test/common/shouldDo.test.js:112:        day = moment().zone(options.timezoneOffset).startOf('day').add(6, 'hours').toDate();
test/common/shouldDo.test.js:118:        day = moment().zone(options.timezoneOffset).startOf('day').add(2, 'hours').toDate();
website/client/store/index.js:18:let browserTimezoneOffset = moment().zone(); // eg, 240 - this will be converted on server as -(offset/60)
website/common/script/cron.js:35:  let timezoneOffsetDefault = Number(moment().zone());
website/common/script/cron.js:49:  let now = o.now ? moment(o.now).zone(timezoneOffset) : moment().zone(timezoneOffset);
website/common/script/cron.js:109:  let startDate = moment(dailyTask.startDate).zone(o.timezoneOffset).startOf('day');
website/server/controllers/top-level/dataexport.js:290:      let timestamp = moment.utc(message.timestamp).zone(timezoneOffset).format(`${dateFormat} HH:mm:ss`);
website/server/libs/cron.js:114:    let thatDay = moment(now).zone(user.preferences.timezoneOffset + user.preferences.dayStart * 60).subtract({days: i});
website/server/libs/preening.js:36:  let now = timezoneOffset ? moment().zone(timezoneOffset) : moment();
```

**Comment by alecbrick** [comment]
I'm potentially interested in looking into this. I know it's not urgent, but the error message is bothering me enough that I'm willing to do whatever it takes to get rid of it.

**Comment by Alys** [comment]
@alecbrick Awesome, thank you! I suggest waiting a couple of days though for Habitica's staff to comment.

@paglias @phillipthelen Are you happy with the proposed fix in the top post (the bolded text)? Or do you have a better idea? Or @alecbrick did you have a different idea for how you wanted to fix it?

**Comment by paglias** [comment]
the fix proposed looks good to me, we should make sure the mobile apps / website don't get values in the new format, but that's pretty easy to do using the toJSON transform, but we should probably keep track of which values have been changed and which not in the database

**Comment by Alys** [comment]
@alecbrick I've marked this as in progress for you. Thanks again, and post here if you have any questions or run into any trouble! 

It will be lovely to stop seeing that warning message everywhere. :)

**Comment by shanaqui** [comment]
Hi @alecbrick, are you still interested in working on this one? If not, I'll mark it as help wanted again in about a week's time.

**Comment by alecbrick** [comment]
Not really. I think I might get back into it if I start getting back into the Habitica codebase, but I probably won’t be working on it soon.

**Comment by shanaqui** [comment]
Alright, I'll mark this as help wanted again, but feel free to let us know if you want to pick it back up!

**Comment by benkelaar** [comment]
I'd like to take a crack at this.

**Comment by Alys** [comment]
@benkelaar That would be fantastic, thank you! I've marked it in progress for you.
