### ISSUE TITLE
"Can't feed this pet" error message should be visible to user not shown in the console 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10217]
When you try to feed a Special pet (which can't be fed; e.g., Veteran Wolf), the message "Can't feed this pet" is reported in the browser's javascript console as shown below. The correct behaviour is that the user should see a "growl" notification showing that message (that's one of the notifications that appears near the top right of the website and then disappears after a couple of seconds).

```
Unhandled promise rejection 
httpCode: 401
​message: "Can't feed this pet."
​name: "t"
​stack: ""
```

This is the code:
https://github.com/HabitRPG/habitica/blob/e50bc189aa5afe211daf6f66cd88594140baaf80/website/common/script/ops/feed.js#L50-L52

I expect that the other errors listed there might also have the same problem so the fix for this issue should include them too.

**Comment by jerell-mendoza** [comment]
hi @Alys, can I take a look at this one?

**Comment by SabreCat** [comment]
@jerellmendoodoo It looks like @ESWAT already created a PR for this; let us take a look and see if that covers it before putting any of your own work in!

**Comment by ESWAT** [comment]
@jerellmendoodoo @SabreCat Feel free to grab this issue if you want; I won’t have time to develop a proper solution for it.

**Comment by beffymaroo** [comment]
@jerellmendoodoo Are you still interested in working on this issue? Let us know when you have a moment. Thank you!

**Comment by jerell-mendoza** [comment]
@beffymaroo, Hi yeah I'd like to have a go at it!

**Comment by Alys** [comment]
@jerellmendoodoo Thanks! Please do!

**Comment by paglias** [comment]
@jerellmendoodoo  have you made any progress on this?

**Comment by jerell-mendoza** [comment]
@paglias still interested/looking into it a little here and there - sorry it's been a bit slow though

**Comment by beffymaroo** [comment]
@jerellmendoodoo Thanks for the update! We'll leave this as in-progress for now, then, since you're still working on it.

**Comment by jerell-mendoza** [comment]
@Alys , I've created a PR to address the issue!
