### ISSUE TITLE
Modal for handling broken Challenge tasks does not dismiss after user action

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10224]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Looks like Chrome
  * OS: unknown

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

As reported by Mage in the Report a Bug Guild. If a user has a broken Challenge icon, and uses it to call up the Keep Them / Remove Them modal for unlinking Challenge tasks, choosing to delete tasks leaves the modal dangling. If the user interacts again, they get a "Task not found" error.

https://drive.google.com/file/d/1psxaPvbhElL1cLBAw1ZypWqxrRYdSoE1/view

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None reported

**Comment by haydenbetts** [comment]
@SabreCat I was able to replicate this, and would like to work on it!

**Comment by paglias** [comment]
Go ahead @haydenbetts !

**Comment by beffymaroo** [comment]
@haydenbetts Are you still working on this issue? Please check in when you have a moment. Thank you!
