### ISSUE TITLE
Purchasable avatar customizations disappear idiosyncratically as user changes active selection

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10225]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
  * Browser: Firefox
  * OS: Windows

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Making selections in the "Skin" or "Hair" tab of the avatar edit modal can cause not-yet-purchased items to disappear and reappear, with no particular rhyme or reason to when. Video: http://citrusella-flugpucker.tumblr.com/private/172581599183/tumblr_p6neomY0x01rl47k3

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None reported.

**Comment by SabreCat** [comment]
Doesn't only affect skins--saw this happen just now with hair colors, too. Updated.

**Comment by veeeeeee** [comment]
This issue is still happening as of this date.

**Comment by shanaqui** [comment]
User in RaB reports it on Chrome as well: Win 10, Chrome 79.0 (32 bit), 1920x1080

**Comment by spadletskysdev** [comment]
I saw a "hide" class on those "not-yet-purchased" that disappears. I'm new so I don't know what triggers that. 
![image](https://user-images.githubusercontent.com/77564401/133189854-b61ee15e-49e2-46fc-a7d1-73e4807ac521.png)

**Comment by harumhl** [comment]
I can take this. Let me know

**Comment by CuriousMagpie** [comment]
Go for it, @harumhl!

**Comment by harumhl** [comment]
My finding so far is that in 'website/client/src/mixins/avatarEditUtilities.js', `hideSet()` occasionally returns `true` for some items (like 0.5% of the time) from `moment(appearanceSets[setKey].availableUntil).isBefore(moment())`, thus hiding those items momentarily then unhide them?

It is consistent with what @spadletskysdev found in https://github.com/HabitRPG/habitica/issues/10225#issuecomment-918765524

**Comment by harumhl** [comment]
Fix: https://github.com/HabitRPG/habitica/pull/14974

**Comment by Tressley** [comment]
Closing as we believe this was fixed in the Customization shop release.
