### ISSUE TITLE
Clicking "clear completed" on filtered Todo list should be selective

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1023]
Currently, if you activate a tag such that you only see Todo items under a specific filter, then go to the Completed tab and click "Clear Completed", all your completed Todos are removed, not just the visible ones. That may be an unexpected result for the user. It would make sense to have the tag filter apply to which Todos are cleared upon clicking that button.
##

**Comment by lefnire** [comment]
Personally disagree, I think it should clear all - but we'll keep open and wait for some others to chime in

**Comment by SabreCat** [comment]
I have two reasons for my suggestion:
- It's a silent and invisible action from the user's perspective. I'm viewing a particular set of tasks, and clicking that button acts on tasks not present.
- I might very well want to only clear a specific tag's todos, while keeping others. Currently there's no way to do this.

At a minimum I'd suggest relabeling the button to say "Clear All Completed", or having a tooltip warning that all completed tasks will be removed, not just the currently visible ones.

**Comment by wc8** [comment]
Suggestions:
**Present user with the option**: Clear All or Clear Visible
I could see situations where I might want to remove only completed items from certain tag(s), but if the user wants to clear everything without changing his tag filters, Clear All would be useful, too.

Make a **Confirmation Dialog**, not just a tooltip warning. Allow the user to dismiss the confirmation dialog if they wish.
This is a powerful button, and in one accidental click a user could be unhappy to discover he just lost his completion logs.

**Comment by librarianmage** [comment]
@Alys Is this still being discussed?

**Comment by Alys** [comment]
@MathWhiz Does your question count? :)

It would probably be nice to have some more selective tools for bulk-deleting things. Perhaps something where you can select the type of tasks to delete (Dailies, To-Dos, completed To-Dos, etc), as well as filtering by tag. It's something that we should look into after the new API is released.

**Comment by lemoness** [comment]
API is done, so we can reopen this discussion. Personally, I think that a confirmation popup as well as changing the label to say "Clear All Completed To-Dos" would be plenty of warning. 

Having a Clear All versus a Clear Visible seems to add clutter without as much of a benefit, in my opinion, but I'd be interested to hear opposing views.
