### ISSUE TITLE
Radio button for daily frequency is broken

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10234]
[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Google Chrome
  * OS: Windows 10

### Description
[//]: # When trying to change the repeat options for a daily, the radio button for changing it to "day of the week" is highlighted without unhighlighting "day of the month". It can be unselected by opening the tab button, and does not persist when you save the task.

![image](https://user-images.githubusercontent.com/8144640/38458459-84714d70-3a96-11e8-84ce-a97324c162b3.png)

**Comment by fentie** [comment]
I'll take a crack at this

**Comment by paglias** [comment]
@shanaqui @Alys I've tested the fix locally and it seems to work well but if one of you can give another look on staging that would be great (it should deploy in the next 15 minutes)

**Comment by shanaqui** [comment]
Looks like it's fixed to me!
