### ISSUE TITLE
"Invite friends" button in header doesn't work as expected

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#10238]
When you have a party with only yourself and the header shows the Invite friends button and you click on it the list of party members is shown instead of the invite modal

**Comment by EthanEFung** [comment]
@paglias where would I be able to find the invite modal?

**Comment by paglias** [comment]
@EthanEFung I think it's in website/client/components/groups/inviteModal!

**Comment by EthanEFung** [comment]
@paglias hmm, okay, perhaps then I should get a little more familiar with the code base before committing to this ticket.

**Comment by paglias** [comment]
that's fine @EthanEFung, let me know if you have any question

**Comment by probaton** [comment]
I don't mind taking a look at this.

**Comment by paglias** [comment]
Go ahead!

Il Lun 4 Giu 2018, 09:43 Dexx Mandele <notifications@github.com> ha scritto:

**Comment by probaton** [comment]
Feeks!

**Comment by probaton** [comment]
Quick reminder that I finished my fix. If anyone with merge rights would be so kind as to give it a quick review, I'd be most appreciative.
