### ISSUE TITLE
Party member selection modal for transformation items no longer works

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10237]
[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Google Chrome
  * OS: Windows 10

### Description
[//]: # Originally reported in Report a Bug, confirmed by me. The avatar transformation items should open a modal that allows you to select which member of the party to use the item on. That no longer happens: a modal opens, but no party members are listed (see screenshot).

![image](https://user-images.githubusercontent.com/8144640/38496919-2ab137fc-3bf7-11e8-9b34-0bf9a97319ea.png)

#### Console Errors
[//]: # I see a lot of console errors on Habitica so I'm not sure what's relevant.

**Comment by Alys** [comment]
I've done brief testing. If you clear the console and then click the Shiny Seed, no new messages are added to the console.

If you reload the Inventory page, the only things in the console that might be relevant are:
```
Invalid URI. Load of media resource  failed.
items
All candidate resources failed to load. Media load paused.
items
```

**Comment by paglias** [comment]
I'm investigating but it doesn't happen all the times for me and right now I'm having an hard time trying to cause the error again

**Comment by paglias** [comment]
How to reproduce: click on "view party" in the header, then try to use the shiny seeds: the error will occur, if you haven't clicked the button before (loaded the party list) it doesn't happen

**Comment by TheHollidayInn** [comment]
Paglias' PR was merged. Is this issue fixed now?
