### ISSUE TITLE
Member List number in Guilds doesn't fit 

### ISSUE THREAD

**Issue by shadimoustafa** [HabitRPG/habitica#10249]
- **Description**
When in Discover Guilds, the member list number on the left side does not fit in the box if it's over 3 digits.

- **Changes**

Before:
![before_change](https://user-images.githubusercontent.com/35777080/38686114-917a5b98-3e41-11e8-92ec-7db97b51d90c.JPG)

After:
![after_change](https://user-images.githubusercontent.com/35777080/38686119-968860f8-3e41-11e8-9cd6-8cb288375e99.JPG)

- Chrome V65.0 on Windows 10, User ID 3b853dc8-4a8a-4992-a486-f2e961c71bb4 . No JS errors logged.

**Comment by paglias** [comment]
Hi @shadimoustafa thanks for this but maybe you wanted to open a PR instead of an issue?

**Comment by shadimoustafa** [comment]
Yes, I will go ahead and open a PR since I have the fix for this issue. Thanks
