### ISSUE TITLE
iOS: recreating ongoing subscriptions as new ones causes failure in cron's monthly subscription benefits

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10246]
This occurs for only Apple subscriptions but @phillipthelen says it's not occuring in the app (https://github.com/HabitRPG/habitica-ios/issues/684#issuecomment-380716620).

Mershmella (6c8e2dc6-d78a-4774-b33c-bda79d88192d) reported in the Report a Bug guild that their `gemsBought` value had not reset during cron at the beginning of this month (i.e., they couldn't buy gems with gold this month). I've confirmed that from Amplitude data and I've reset it manually. This also happened to them last month and at that time I suspected it was caused by them having too much history in some tasks (which can cause cron to time out part way through). I cleared all their history last month. This month they still have small history arrays, so I don't think that can be the cause of their gems not resetting this time.

I think the problem was caused by their subscription being recreated from scratch at the start of each month and that seems to be happening only for Apple subscriptions.

Mershmella has an Apple subscription:
```
{
    "_id": "6c8e2dc6-d78a-4774-b33c-bda79d88192d",
    "profile": {
        "name": "Mershmella"
    },
    "purchased": {
        "plan": {
            "consecutive": {
                "count": 8,
                "offset": 0,
                "gemCapExtra": 10,
                "trinkets": 0
            },
            "quantity": 1,
            "extraMonths": 0,
            "gemsBought": 35,
            "mysteryItems": [],
            "additionalData": "MIIhww...GYUA==",
            "customerId": "32...73",
            "dateCreated": "2017-07-01T17:38:21.482Z",
            "dateTerminated": null,
            "dateUpdated": "2018-04-01T16:14:01.847Z",
            "nextPaymentProcessing": "2018-04-10T18:02:51.592Z",
            "owner": "6c8e2dc6-d78a-4774-b33c-bda79d88192d",
            "paymentMethod": "Apple",
            "planId": "basic_earned"
        }
    },
}
```

Whenever a new subscription is created (not when an ongoing subscription renews), a message is posted to the moderators' Slack to help us troubleshoot subscription data, and we have multiple such records for Mershmella this year:
```
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Feb 15 2018 04:16:43 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Feb 15 2018 04:16:43 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Feb 15 2018 04:16:43 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Mar 01 2018 19:16:37 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Mar 01 2018 19:16:37 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Mar 01 2018 19:16:38 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Sun Apr 01 2018 16:14:01 GMT+0000 (UTC)
```
There's supposed to be just one of those records each time a subscription is created, so seeing seven makes it look as if the subscription was created from scratch seven times this year. I asked Mershmella if they've been manually cancelled and recreating their subscription each month, but they said "I have automatically renewed since I started my subscription (through the Apple store)".

So it looks like something in Habitica's code is causing an ongoing subscription to be recreated as if it's a new subscription. Looking through our Slack records, I can see similarly duplicated records for about 40 users in March, all for Apple subscriptions (none for any other payment method). This is a problem because when an ongoing subscription is recreated as if it were a new subscription at the beginning of the month, it causes a faiure in the process that adjusts the user's monthly subscription benefits. In detail:

From the above data, you can see that the new subscription was created for Mershmella at Apr 01 2018 16:14:01, and this resulted in their subscription's `dateUpdated` value being set to "2018-04-01T16:14:01.847Z" - that value is always set when a new subscription is created, by this code: https://github.com/HabitRPG/habitica/blob/fa945c768949bf00adba2281483677cb66dc2c8c/website/server/libs/payments/payments.js#L331

Mershmella's cron on 1 April ran a few minutes after their subscription was recreated: 2018-04-01T16:21 ("April 1, 2018 4:21:16 pm UTC" in Amplitude). Part of cron's processing is to check the `dateUpdated` value for a subscription - if it is in a previous month, then cron runs the code that resets the user's monthly gem cap and increases their consecutive month benefits:
https://github.com/HabitRPG/habitica/blob/fa945c768949bf00adba2281483677cb66dc2c8c/website/server/libs/cron.js#L65-L68

Because `dateUpdated` had already been set to a date in April before cron ran, cron couldn't tell that it needed to reset their gem cap.

I.e., having Apple subscriptions recreated from scratch each month is damaging if it happens before the user's first cron of the month. Users affected by this will never have their monthly gem caps reset and won't earn consecutive month benefits. So ideally we'd either work out what is causing Apple subscriptions to be recreated from scratch, or we'd need to adjust how cron assesses subscriptions so that it can cope with the dateUpdated value being reset before the first cron of the month.

Until this is fixed, admins will need to find all affected users each month and manually:
- reset their `purchased.plan.gemsBought` value (set to 0)
- increase their `purchased.plan.consecutive.count` by 1
- decrease their `purchased.plan.consecutive.offset` by 1 if it's not 0
- increase `purchased.plan.consecutive.gemCapExtra` by 5 if `count` is now at a multiple of 3 and `offset` is 0 and the value is not already 25 (never let it be higher!)
- increase `purchased.plan.consecutive.trinkets` (Hourglasses) by 1 if `count` is now at a multiple of 3 and `offset` is 0

@phillipthelen says "This might be caused by something in the habitica-email-server code, since that goes through the user data. Although I’m not sure right now that it actually updates anything on the subscription, since it should mostly just check with apple if the subscription is still active and cancel it on our side if not." -- https://github.com/HabitRPG/habitica-ios/issues/684#issuecomment-380716620

By the way, Mershmella is being affected by the "RECEIPT_ALREADY_USED" problem. I don't know if that's related. Here's one example from Loggly:
```
message:NotAuthorized: RECEIPT_ALREADY_USED
    at Object.subscribe (/usr/src/habitrpg/website/transpiled-babel/libs/applePayments.js:143:29)
    at <anonymous>
method:POST
originalUrl:/api/v3/iap/ios/subscribe
```
and screenshots of others from around 1 April:
![6c8e2dc6-d78a-4774-b33c-bda79d88192d](https://user-images.githubusercontent.com/1495809/38650047-22c0815e-3e3d-11e8-8268-93843e617365.png)

**Comment by Alys** [comment]
From examining the duplicates in our Slack records, it looks like the first recreated "new" subscription for an ongoing subscription happened around 2018-02-13 or 2018-02-14 - those are the dates when we start seeing entries that are likely to be recreated subscriptions and they're frequent from that time onwards (below are the dates that "new" subscriptions were reported in moderator Slack for people who already had existing subscriptions):
```
    2018-02-13 14:05:02
    2018-02-13 14:05:02
    2018-02-14 17:52:20
    2018-02-14 17:52:20
    2018-02-14 18:33:01
    2018-02-14 19:34:47
    2018-02-14 19:34:47
    2018-02-14 19:34:47
    2018-02-14 21:54:58
    2018-02-14 21:54:58
    2018-02-14 22:02:36
    2018-02-14 22:12:23
    2018-02-14 22:22:14
    2018-02-14 22:34:40
    2018-02-14 22:42:17
    2018-02-14 22:42:17
    2018-02-14 22:42:17
    2018-02-14 22:42:18
    2018-02-14 22:53:20
    2018-02-14 22:53:21
    2018-02-14 23:11:47
    2018-02-14 23:19:47
    2018-02-14 23:19:47
    2018-02-14 23:28:22
    2018-02-14 23:28:23
    2018-02-14 23:39:50
    2018-02-14 23:39:50
    2018-02-14 23:46:45
    2018-02-14 23:46:45
    2018-02-15 00:00:52
    2018-02-15 00:04:53
    2018-02-15 00:04:53
    2018-02-15 00:04:53
    2018-02-15 00:04:53
    2018-02-15 00:11:49
    2018-02-15 00:12:31
    2018-02-15 01:25:18
    2018-02-15 01:35:28
    2018-02-15 01:58:42
    2018-02-15 01:58:42
    2018-02-15 02:07:40
    2018-02-15 02:07:40
    2018-02-15 02:07:41
    2018-02-15 02:07:41
    2018-02-15 02:21:13
    2018-02-15 02:29:37
    2018-02-15 02:54:38
    2018-02-15 02:54:38
    2018-02-15 02:54:38
    2018-02-15 02:54:39
    2018-02-15 03:12:04
    2018-02-15 03:15:51
    2018-02-15 03:15:51
    2018-02-15 03:15:51
    2018-02-15 03:15:51
    2018-02-15 03:19:22
    2018-02-15 03:19:28
    2018-02-15 03:28:14
    2018-02-15 03:56:51
    2018-02-15 03:56:51
    2018-02-15 03:56:52
    2018-02-15 04:15:16
    2018-02-15 04:16:43
    2018-02-15 04:16:43
    2018-02-15 04:16:43
etc
```

This means that we'd expect the first problems from `gemsBought` not resetting at the start of the month to begin in March, which is in fact what @SabreCat and I observed in the Report a Bug guild: https://habitica.slack.com/archives/C0DTHS87Q/p1521236060000018 plus the following several posts.

The [habitrpg-email-server repo](https://github.com/HabitRPG/habitrpg-email-server/commits/master) did have a commit shortly before 2018-02-13: https://github.com/HabitRPG/habitrpg-email-server/commit/430f9ae2d0541ef5ebe4e3c9aad9a4937fe32b08 on 8 February but it was just to update a crypto algorithm so I don't think that's related. 

The habitica repo's [releases](https://github.com/HabitRPG/habitica/releases?after=v4.27.2) don't show any releases around 13 February: they jump from v4.26.1 on 10 February to v4.26.2 on 24 February. BUT there's actually quite a few releases dated for both those dates so I don't think those dates are accurate - maybe they're just the dates when the release notes were added - @SabreCat does that sound right? The list of commits for `upstream/release` is probably more reliable: https://github.com/HabitRPG/habitica/commits/release?after=c54ce960337dcd1f2ca9fac52ef58a706f38c972+279 
It shows "Refactor Purchase API - Part 1 (#9714)" on 10 Feb but I don't think it's related - it's a few days too early and at a glance it doesn't seem to affect subscription purchases. No other commits around that time look relevant, based on the descriptions of the commits, but we might want to look through them in detail.

There was a new iOS version around 14 February ([1.13](https://github.com/HabitRPG/habitica-ios/milestone/10?closed=1)) and it included a commit related to subscriptions: https://github.com/HabitRPG/habitica-ios/commit/cb43a64311036ac96fbdbe0050092c8ea91bae9f so maybe there's a hint in that code about which API route is causing this bug.

**Comment by Alys** [comment]
In terms of users affected, based on the data stored in Slack I think there's about 370 users who have had "new" subscriptions created when they've actually had ongoing subscriptions, but probably less than 30 who haven't been given the correct subscription benefits, perhaps significantly less than 30. To be detrimentally affected they have to have been unlucky enough for the "new" subscription to be created before their first cron of the month. There's 30 users who had a "new" subscription created on 1 March or 1 April, but at least some of those were after cron had run that day.

Unfortunately to determine exactly which users didn't have their monthly gems reset or didn't have their `count`, etc increased, we'd have to analyse data from Amplitude for all potential users (e.g., look for cron times after the "new" subscription times or look for users who have large values for `gemsBought` but haven't bought any gems with gold this month). That would be very time-consuming. I think we're better off assuming that all users who weren't able to buy gems with gold this month and last month did actually report it to us.

**Comment by TheHollidayInn** [comment]
It looks like the requests on Loggly are coming from iOS. So we should stop whatever is causing those to be sent.

In addition, we can add a check here: https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/payments/apple.js#L84 to ensure we don't create subs for users with an active subscription. I'll be doing that since I happen to already be working on some test coverage here.

**Comment by SabreCat** [comment]
Correct re: the release notes. I love Git, but figuring out chronological order on GitHub is an exercise in futility.
