### ISSUE TITLE
UI misleadingly suggests that a Royal Purple Gryphon can be hatched from a Royal Purple Potion + Gryphon egg

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10253]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you have a Royal Purple Hatching Potion, and a Gryphon egg, selecting one will highlight the other as if they are a valid combination. This is an unusual case, in that "Gryphon-RoyalPurple" does not represent an egg+potion combo, but a special pet only obtainable during specific site events.

Screenshot: https://snag.gy/6w2dez.jpg

**Comment by ghost** [comment]
@SabreCat Could I try to tackle this issue? Also, do you know where you guys store the valid egg+potion combos?

**Comment by ghost** [comment]
@Alys see above? :)

**Comment by paglias** [comment]
Go for it! Regarding where we store the valid egg+potion I'm not sure we do outside of the user's items where all valid combos are stored (set to false if an item is not valid)

**Comment by SabreCat** [comment]
@asherdale https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/stable.js is what you're after, I believe! The logic there assembles the following combination sets:

1. Base pet species + standard potion colors
2. Base pet species + premium (Magic) potion colors
1. Quest pet species + standard potion colors
2. Special pet species

The first three are hatchable, the last is not.

**Comment by ghost** [comment]
I fixed the bug, but before making a PR I want to ask whether the "Jackalope-RoyalPurple" pet-potion combination should be valid as well, because currently it is valid and I could quickly fix that as well and submit both fixes in the same PR (if that combination should also be invalid). Let me know :) @SabreCat @paglias

**Comment by SabreCat** [comment]
@asherdale Jackalopes are awards for subscribers, not hatchable pets, so that can indeed be fixed. (We don't have any non-purple jackalopes to see this bug in action with them as yet, but it doesn't hurt to be proactive!)

**Comment by kirsty-tortoise** [comment]
Can I attempt a fix for this?

**Comment by paglias** [comment]
@kirsty-tortoise sure!
