### ISSUE TITLE
prevent typing a private message when your chat privileges have been revoked

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10256]
When someone has their chat permissions revoked, they aren't allowed to PM another user. This is handled correctly by the API and if they type a PM in the website's Inbox, it doesn't go through to the recipient, but it appears to have been sent until refresh on the user's end. That can be quite confusing and wastes the user's time typing the message.

The desired behaviour is that when a muted user opens the private message modal, they should not see the Send button or the text box for typing a message. Instead they should see the text "You are not able to send private messages because your chat privileges have been revoked. If you have questions or concerns about this, please email admin@habitica.com to discuss it with the staff."

A muted user can be identified by `flags.chatRevoked` set to true.

Muted users should still be able to read any PMs they sent or received in the past.

**Comment by negue** [comment]
@Alys I think this can be closed, as of now there is no input to add a message once the `chatRevoked` is true

**Comment by Alys** [comment]
Yes, this was fixed by the PR linked above (https://github.com/HabitRPG/habitica/pull/10307). Closing.
