### ISSUE TITLE
Refreshing after downloading iCal restarts download

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1025]
This is in Firefox, and could conceivably be a problem there rather than in HabitRPG, but figured I'd report.

If I click the calendar icon to download an iCal of my Todos, then go about my Habiteering for a while, and at some point click Refresh, the download happens again. The only way I could find to get it to stop was to navigate manually via URL to the main site (in my case I'm using beta.habitrpg.com).

**Comment by lefnire** [comment]
it's because clicking the ical link actually redirects you to the URL for the file download. refreshing the page then is refreshing the download link. we should change this, but flagging as minor

**Comment by negue** [comment]
Should be closed, since currenty there isn't any iCal available. And re-open, If the new implementation has the same issue.

**Comment by lefnire** [comment]
good point
