### ISSUE TITLE
checklist checkboxes should not be clickable in Group Plan's "Task Board" page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10254]
If you try to complete a checklist item in the Task Board page in a Group Plan, a tickmark appears in the checkbox and you see the message "Task not found" (see screenshot).

The correct behaviour is that the checklist boxes should not be clickable at all, in the same way that the main checkbox for the entire task is not clickable.

The "Task not found" message should NOT be removed from the backend code - we still need an error to be thrown in case the user tries to complete a checklist item using an API command or a third-party tool.

![screenshot_2018-04-15_122237](https://user-images.githubusercontent.com/1495809/38774300-112e9a0c-40a9-11e8-8bdc-ca0fda0b962d.png)

**Comment by fentie** [comment]
I think this is something I can sort out

**Comment by Alys** [comment]
@fentie Thank you!
