### ISSUE TITLE
Quest information modal doesn't respond to changing window size

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10267]
From a user in the Bug Guild:

> Summary: Parts of quest preview is obstructed from view in smaller window width
> 
> Steps to Reproduce:
> 
> Go to Inventory > Items (or Shops > Quests)
> Locate Quests section (if you have quest items)
> Open a quest and reduce window size (approximately half a laptop screen)
> Notice that the side information for the quest is hidden and cannot be viewed
> Expected Behavior: I should be able to scroll sideways or the quest information modal should be responsive to the changing window width.
> 
> Observed Behavior:
> 
> In shop: https://ibb.co/mKONmn
> In inventory: https://ibb.co/dqNhmn

And:

> Summary: Horizontal and vertical scrollbars on quest preview/information modal window in shop
> 
> Steps to Reproduce:
> 
> Navigate to Shops > Quests
> Select a quest (I don't have all unlocked but I have confirmed that this is reproduced in all of what I can select)
> Expected Behavior: I should see no scrollbar in the information window (similar to the quest information window from the Inventory > Items page's Quests section)
> 
> Observed Behavior: I see a vertical and horizontal scrollbar.

*UPDATE*

The responsive part has been fixed in https://github.com/HabitRPG/habitica/pull/10354

**Comment by yb50110** [comment]
I have a quick idea for this that will prevent overlapping for smaller by fiddling with the CSS. Should I put up a pull request or just provide what I have adjusted as a comment?

**Comment by yb50110** [comment]
I added this to the `modal.scss` file:
```
#start-quest-modal, #buy-quest-modal {
  @media only screen and (max-width: 1200px) {

    .modal-dialog {
      max-width: 33%;

      .left-panel {
        left: initial;
        width: 100%;
        right: 100%;

        .col-4 {
          width: 100px;
        }
      }

      .side-panel, .right-sidebar {
        left: calc(100% - 10px);
        max-width: 100%;
        right: initial;

        .questRewards {
          width: 90%;

          .reward-item {
            width: 100%;
          }
        }
      }
    }
  }
}
```

I couldn't figure out why the CSS/SCSS changes weren't being reflected when I made changed in the `startQuestModal.vue`. And as my two cents, I think in smaller windows, stacking these side panels below the main content would be better (more legible?) than having them side by side.

**Comment by SabreCat** [comment]
@yb50110 Please do submit a PR and we'll take a look!

**Comment by yb50110** [comment]
I have a PR up (https://github.com/HabitRPG/habitica/pull/10354) for the responsiveness aspect of this issue!

**Comment by beffymaroo** [comment]
@SabreCat  @paglias Should this go back to Help Wanted status since the fix in PR 10354 is partial?

**Comment by TheHollidayInn** [comment]
I'm unable to reproduce: `Summary: Horizontal and vertical scrollbars on quest preview/information modal window in shop`

Is this still an issue? And if so, can the person confirming post a screenshot?
