### ISSUE TITLE
Habit Reset results in DEATH

### ISSUE THREAD

**Issue by BanktownUSA** [HabitRPG/habitica#1026]
I've had a lot of trouble logging onto Habit lately and I figure you guys were having server issues so I decided the minute I could log in I'd put my account on REST. Didn't want to have to worry about you possibly dying and subsequently losing all my hard work. Yesterday night i was finally able to log in and i noticed i was at 7HP so I quickly updated all my dailies etc (which had me at 86 gold, put me over level 13, and I had a Morning Star). I then put my account on REST and went to bed. When I got home from work and instinctively logged onto Habit all of the above things were gone because somehow Habit hadn't registered anything I'd done and because of that my dailies killed me. Is there anyway to get my stuff back. I worked freaking hard to get all my updates and I don't think I can use Habit if I think I'm going to lose everything at a moments notice.

**Comment by wc8** [comment]
Restore: click on your user icon and go to Settings. Under the Danger Zone section you will find tools to restore your account. Add enough gold to buy back Morningstar, etc.
You can also restore streaks for each task via the task's edit > advanced options.

**Comment by lefnire** [comment]
What @wc8 said. I'm gonna close this since it's just due to server instability, which most tickets are tracking.
