### ISSUE TITLE
Pet image / hatching / rehatching confusion in the Stable; inconsistency with mobile apps

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10273]
We've had some bug reports about the way that pets are displayed in the Stable on the website and how it's confusing for telling which pets/mounts you own, harder to tell how complete your pet/mount collection is, and inconsistent with the mobile apps:

"a large portion of the pets in my stable have reverted to the black paw with question mark. I had the full set of basic ones and now about 2/3 are reset to not hatched. i have tried logging in and out a few times no effect. The odd thing is that they are all still there on my iphone app!"

"On log on yesterday, I noticed that about half of my hatched pets and fed mounts had disappeared - I assumed it was a glitch of some sort and left it at that. It is still like that this morning. My OCD about completing the rows gets jittery every time I look at the page :("

"Having a similar issue as others here. My three pet snakes have reverted to empty paw prints, though they show in the mounts list. Incidentally, this happened right after I completed the quest that makes those eggs (though I hatched the ones missing a long while ago)."

"I have most of the pets (I am lacking some squirrels) and have fed almost all of them into mounts. Now, if I get new eggs, the black paw print shows up instead of the faded pet, so it looks like I don't have the mount. If I don't have eggs, the faded pet still shows."

"a large portion of my pets have dissappeared. My phone app still shows me as having all the basic pets hatched and my acheivements still supports this, but on my PC version more than half are reset back to "not there" I have tried logging in and our a few times."

"Did they change something in the Stables? Previously, pets that turn into mounts are grayed out but now, they turn back into a paw (which only shows if I haven't hatched that pet yet)."

"My stable on the mobile app appears to be full (I have 90/90) but on the desktop version I now have available spaces for all of the pets that have already grown into mounts. Deleting browser cache doesn't appear to help, nor does logging out and coming back in again. Seems to happen in both Safari and Chrome."

It's come from https://github.com/HabitRPG/habitica/pull/10243, which has resulted in these possible states on the Pets section of the Stable on the website (point 4 is the new one that's causing the bug reports):

1. You've never hatched the pet and you can't hatch it now: grey pawprint.
2. You've never hatched the pet but you can hatch it now: black pawprint.
3. You've hatched the pet and turned it into a mount and cannot re-hatch it now: greyed-out pet image.
4. You've hatched the pet and turned it into a mount and can re-hatch it now: black pawprint.

Previously for point 4, you'd see the greyed-out pet image for that condition, which was consistent with the mobile apps, made it clear which mounts you had, and promoted a better sense of completion towards collecting the full set of pets and mounts. Now it looks like you've never owned that pet.

https://github.com/HabitRPG/habitica/pull/10243 was intended to fix https://github.com/HabitRPG/habitica/issues/9368 but that issue is still happening, so I'm wondering if it would be acceptable for https://github.com/HabitRPG/habitica/pull/10243 to be reverted. Or was there an additional reason for that change to be made?

If the new behaviour is going to be kept, the same change might need to be considered for the mobile apps, if consistent behaviour across platforms is desired.

**Comment by majestic-owl448** [comment]
also the previous behaviour (3 and 4 with the same image) was causing confusion for people that use the quick hatch from the stables as people sometimes wouldn't realise they could hatch the pet again after having obtained the mount. But there weren't bug reports because they didn't realise the function was even there, there were instead people that realised the thing after being explained what Triad Bingo is or related things (like what to do with all the potions and eggs). It happened for only a small portion of users, so maybe it's not that important.

**Comment by shanaqui** [comment]
On reflection, I'm okay with this change but think there should be actual explanation on the page -- a visual key is the simplest, but any explanation is better than none. Having four states to intuit just seems like too much.

**Comment by citrusella** [comment]
I personally think there should be a visual difference between "pet you've never gotten" and "pet you can hatch again" (even if it's not the *same* visual difference there was before).

I feel like it's less important for "gen 1" pets but I used it to determine which magic potion pets I'd never hatched as pets at all to figure out how many magic potions I might want to buy at once (because I don't always buy a full set, but I usually leave myself with 1 sitting around at any given point in time because I'm weird), so the current layout's a tad more involved/confusing now (I have to take note of mounts *and* take note of pets and keep both "lists" (in order to remember which pets are already mounts) in my working memory long enough (or else write them down) to add them together/buy/use them, whereas before, it was like, "oh, so I've never hatched a shimmer lion or bear before; I'll buy two potions this go-around, then").

**Comment by Alys** [comment]
@citrusella makes a good point about the Magic Potion pets. It's highly advantageous to let the players see which pets and mounts they own at a glance to help them  buy the right number of potions. Buying too many potions adds a support burden since we have to manually remove them and return the gems.

----

Here's another bug report that helps to clarify why the black paw print is confusing for pets you have hatched:

MorganLeFlay (4485e177-2203-4a07-b4e7-6ab5cda3ef60):

**Ah! What happened to my stable? I have 88/90 pets found, but they seem to be "missing" in my stable view...**
**To make it easier, here is a screenshot from my desktop: https://drive.google.com/file/d/1v2ScloMmICTv0_acr6NIoTxDw6G2x_J3/view?usp=sharing**

This is the important part of the screenshot:

![image](https://user-images.githubusercontent.com/1495809/39099650-7ec36296-46c1-11e8-8539-df29a2e9625a.png)

It shows that MorganLeFlay has hatched 88 pets but only some of them are visible as hatched because the others have been converted to mounts and the black paw print doesn't make that clear.

If the image for a pet that was hatched but converted to a mount still showed the pet but had an extra feature to indicate it could be hatched again (maybe a tiny black paw print in one corner or something), then you'd have the best of both worlds: You'd see all the pets you'd hatched on your progress towards Beastmaster and you'd also see which ones could be rehatched immediately.

**Comment by Alys** [comment]
There's still reports of bugs because of this change (e.g., the conversation below from the Report a Bug guild today but there's been others too over the past month). While the new behaviour does make it clear which Pets you can re-hatch, it's no longer clear from looking at the Pets which Mounts you already own, so one problem has been swapped for another. Unless there's disagreement in the next few days, I'll mark this as help wanted with this as the desired solution: 

**For a pet that has been converted to a mount, display the greyed-out version of the pet regardless of whether you can re-hatch it or not. When the pet can be re-hatched, overlay a small black paw print in one corner of the greyed-out pet image.**

If anyone has a better idea, please comment!

@Tressley

----
From the Bug guild:

Cequinne: _"I don't know if this was an intentional change or not, but in my pet section, once I have changed the pet into a mount and I am able to hatch the pet again, instead of showing the pet as grayed out, it shows the black paw print with a question mark. It used to show the pet grayed out, which I preferred because then I would know which pet I already have the mount of but just need to rehatch the pet. It does show the pet grayed out when I am unable to rehatch the pet, but once I get another egg or potion for that combination, it becomes the black paw print with a question mark. This isn't a recent thing, it happened awhile ago, I just didn't report it until now."_

KimMath: _"That is intentional, as it allows people to easily see which pets they are currently able to hatch :)"_
 
citrusella, the serving wench: _"As an extra note, it *has* [been noted on Github](https://github.com/HabitRPG/habitica/issues/10273) that the change introduced a different confusion (namely: "do I have that mount or not? it's not clear now without keeping two lists in working memory instead of one"). (Also, the pawprint doesn't seem to have been implemented for the exact purpose of making it clear which are immediately hatchable, as far as its [PR](https://github.com/HabitRPG/habitica/pull/10243) and the [issue it was supposed to fix but didn't seem to have fixed](https://github.com/HabitRPG/habitica/issues/9368) seem to say. It's more like a side effect as far as I understand it. :P :) )"_

Cequinne: _"Gotcha. I agree with Aly's comment on Github: "If the image for a pet that was hatched but converted to a mount still showed the pet but had an extra feature to indicate it could be hatched again (maybe a tiny black paw print in one corner or something), then you'd have the best of both worlds." Although, imo, it would be even more awesome if a pet and mount of the same species/color were side by side, rather than having two separate areas for pets and mounts. That way when you hatch it, you can immediately see that the mount appeared (which would probably help reduce the amount of user support needed re: 'where did my pet go/why is my pet gray/etc'), plus equipping a matching pet/mount would be soooo easy."_

**Comment by Tressley** [comment]
@Alys -- I had actually worked on this in the past and the solution was finalized, but I don't think it was ever implemented or brought into GitHub.

Here's a quick screenshot to show you where the team landed after discussion.
![image](https://user-images.githubusercontent.com/2686586/40666620-2c29af16-632e-11e8-8314-b5792f71bd9c.png)

**Comment by davidgram505-droid** [comment]
That sounds like a frustrating glitch to deal with, especially when everything is showing up fine on the mobile app. Hopefully, the web team syncs the database display soon so your hard-earned collections reflect properly again. Speaking of keeping your companions safe, don't forget to protect them offline too by recognizing early signs of [heatstroke in pets](https://www.newsgram.com/world/2026/01/05/heatstroke-in-dogs-and-cats). Fingers crossed this gets patched in the next update!
