### ISSUE TITLE
"Show more" button persists in the stables even when the section it belongs to is hidden

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10279]
Reported in Report a Bug, confirmed by me:

> Summary: "Show More" button not hidden for group with no pet/mount when filtered to hide missing.
> 
> Steps to Reproduce:
> 
> Navigate to Inventory > Stable
> Identify that you have groups with no pets or mounts (for me, I have no Quest pets or Quest mounts)
> Toggle Hide Missing from the Filter panel on the left portion of the page
> Find the sections where you have no pets or mounts
> Expected Behavior: The "Show More" button should be hidden along with the hidden group OR the group label should be present along with the button.
> 
> Observed Behavior: The button is left by itself, making it seem like the "Show More" button of the previous group has doubled: https://ibb.co/cJi9bx

(Edited the title because I dunno where my brain was.)

**Comment by coder-extreme** [comment]
Can I try working on this?

**Comment by coder-extreme** [comment]
After a comment on the Aspiring Blacksmiths Guild, I have started work on this.

**Comment by Alys** [comment]
@coder-extreme Thanks! That's fine. :)  If there's another case where we don't reply to a comment you've made in an issue or pull request, after a few days post there again to remind us that you're waiting. Sorry about that!

**Comment by coder-extreme** [comment]
Thanks!



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by coder-extreme** [comment]
I'm so sorry, but there is so much going on right now in my life that I don't have the time to figure out how to contribute right now. I don't think I'll have the time to fix this right now, but I may come back to it later.

**Comment by TheHollidayInn** [comment]
This seems to have been fixed.
