### ISSUE TITLE
pinned quest equipment should become unpinned when earned from a quest

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10286]
If you earn a piece of equipment from a quest then lose that gear due to death and then pin it to your Rewards area, if you regain the equipment by repeating the quest, it does not automatically become unpinned. The expected behaviour is that when you are given the piece again, it is removed from your `pinnedItems` list.

However this is a bit of an edge case and can be fixed by the user unpinning manually, and most of the time when a quest completes there wouldn't be a pinned item to look for, so I'm not certain if we want an extra check in our code for this. I'm leaving this as suggestion-discussion for a few days for comment from the staff. If no one disagrees, I'll mark it as help wanted.

_Thanks to Il Mago for reporting it in the Report a Bug guild._

**Comment by TheHollidayInn** [comment]
Since we haven't had an recent users complaining. I'd rather just let the user unpin. Feel free to reopen if users feel differently.
