### ISSUE TITLE
Hovering over the megaphone icon in a challenge on its own page shows "undefined"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10280]
From Bug Guild, confirmed:

> really nice to now be able to know wich tasks belong to wich challenge just hovering with the mouse on the megaphone icon, but doing it on the challenge page it says "undefined"

![image](https://user-images.githubusercontent.com/8144640/39270919-bc2a7ed6-48d7-11e8-9ca1-d5ced38872b3.png)

**Comment by fentie** [comment]
I can probably take this on. It looks like the `challenge` data attached to the tasks on the Challenges page is just the ID, but on the user's Tasks page it also contains the shortName, which is used to populate that hover. 

Need to dig into how mongo querying works...

**Comment by Alys** [comment]
Thanks @fentie!

BTW, my feeling is that the on-hover effect could just be removed when you're viewing the challenge's own page. I don't think it serves any purpose there.

**Comment by fentie** [comment]
... right. that's way easier. good idea 😄

**Comment by fentie** [comment]
... right. that's way easier. good idea 😃
