### ISSUE TITLE
"likes" / "plus-one" count icon no longer shows +0 or turns green when you've liked

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10288]
When you click "like" on a chat message, the count increases but the count and its icon no longer turn green not even after you reload.

I'm pretty sure it turned green until very recently but I might be misremembering.

**Comment by citrusella** [comment]
The button on the website turns blue like it has since the redesign for me. The count hasn't been green (or blue) since before the redesign as far as I know.

**Comment by Alys** [comment]
Maybe I was imagining it being green. `confused` Cantras also thought it was. Don't know...

Maybe I'm thinking of the app??

**Comment by Alys** [comment]
From AnneLine (16a107de-d519-43ce-8c30-8da5cbcbb237) in the Report a Bug guild:

"... it looks as if the area stays blank near where the 'like' should show if no one has liked anything.  It used to show a "+0" ..."

Maybe that's what's been confusing me. `shrug`

Was that a deliberate design change?

**Comment by citrusella** [comment]
According to what I remember about the old site ([here (the No +1s section)](http://habitica.wikia.com/wiki/Chat?oldid=109709#No_.2B1s_Yet) and [here (the old site's behavior when you moused over, saw a post liked by others, and saw a post liked by you, respectively)](https://vignette.wikia.nocookie.net/habitrpg/images/4/48/Plus_One_Buttons.png/revision/20180130015350), it didn't work like that there, and [the age of this image](http://habitica.wikia.com/wiki/File:Party_Chat_Screen.png) and the [current Chat wiki page's Like section ("If the post hasn't received any likes yet, there will not be any visible counter at this area.")](http://habitica.wikia.com/wiki/Chat#The_Like_Button) suggests it hasn't been a thing on the new website, either. :thinking: 

The current app (well, Android, anyway) has, AFAIK, always shown a +0 for an unliked message, but I can't remember the site doing it at all. :confused: (Is the app not doing it now? I need to delete some pictures off my phone so I can update. 0_o)

~~\*queues up the X-Files theme*~~

**Comment by Alys** [comment]
I'm just going to close this. I'm clearly not remembering anything well enough. Thanks citrusella!
