### ISSUE TITLE
party/guild invitations should not be possible from a player you have blocked

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10282]
When you have blocked a player from sending private messages to you, currently that player is still able to send you invitations to a party or a guild. This should be changed so that the player cannot send you any invitations.

_(FYI, we've already removed the ability for the player to send you gifts of gems and subscriptions, as well as private messages.)_

**Comment by jerell-mendoza** [comment]
hi @Alys , I'd like to take a look at this!

**Comment by Alys** [comment]
@jerellmendoodoo Thanks! Go ahead.

**Comment by jerell-mendoza** [comment]
@Alys 
Just to see if I'm on the right track, I'm modifying the endpoint POST `/groups/:groupId/invite` to be able to check the `user.inbox.blocks` value to see if a user should be blocked from inviting them into a party or guild?

If this is the case, I'm wondering why `userFieldsToExclude: ['inbox'],` is included on all those endpoints and if it's ok to remove this condition for that endpoint. Also if this is the only endpoint which we need to address for this issue?

**Comment by Alys** [comment]
The inbox will be excluded for performance reasons (it can be very large) but you're right that the code will need to read `user.inbox.blocks` for this PR.

@paglias Pinging you since this is related to optimisations.
I'm wondering if the parts of `inbox` that aren't the messages themselves should be moved to `preferences`. I think we had trouble like this with the inbox opt in/out setting too.

@jerellmendoodoo Hold off on this until you see a reply from @paglias. Thank you for asking about this! Good point. :)

**Comment by paglias** [comment]
@jerellmendoodoo you can remove the `userFieldsToExclude: ['inbox'], ` from the route if you need to use any value inside the inbox object, go ahead

@Alys yes we should move them but it's a breaking change so maybe we'll be able to make it with the api v4

**Comment by jerell-mendoza** [comment]
@paglias @Alys Great! Thanks for the feedback, it looks like I'm on the right track then and I have a clear approach to how to finish up this issue. I think I should be able to wrap this up sometime early next week (hopefully)!
