### ISSUE TITLE
Webhooks explanation is needed on Settings > API page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10287]
On the [Settings > API](https://habitica.com/user/settings/api) page, there's a Webhooks section. It needs one or two sentences under the heading to explain what it's for (e.g., a very brief description of what webhooks are, maybe a link to a good website for more details, and a message that if you don't know what a webhook is, it's best to leave the section empty because incorrect values can cause errors/slowness).

I'll write a proposed message in the next few days.

----

This is necessary because some players have been using the webhooks section for recording normal website URLs (presumably pages that they use often) and I suspect that is the cause of server errors we've been seeing like the one below, from a user who had `https://oldgods.net/habitrpg/habitrpg_user_data_display.html?uuid=12345678-7b8f-435b-8152-06a502ebe37e` entered as a webhook.
```
http:
clientHost:....
contentType:application/json
json:
level:error
message:ParseError: Unexpected token < in JSON at position 0 in "https://oldgods.net/habitrpg/habitrpg_user_data_display.html?uuid=12345678-7b8f-435b-8152-06a502ebe37e":
<!doctype html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <title...
   at stream.catch.then.data (/usr/src/habitrpg/node_modules/got/index.js:366:15)
   at <anonymous>
   at process._tickDomainCallback (internal/process/next_tick.js:228:7)
timestamp:2018-04-16T19:17:52.002Z
fullError:
host:oldgods.net
hostname:oldgods.net
method:POST
name:ParseError
path:/habitrpg/habitrpg_user_data_display.html?uuid=12345678-7b8f-435b-8152-06a502ebe37e
protocol:https:
statusCode:200
statusMessage:OK
url:https://oldgods.net/habitrpg/habitrpg_user_data_display.html?uuid=12345678-7b8f-435b-8152-06a502ebe37e
```

**Comment by natfarleydev** [comment]
@Alys is this done now?

**Comment by Alys** [comment]
Ah no, I still need to write that message. :( I'll get that done this weekend. Thanks @nasfarley88

**Comment by natfarleydev** [comment]
No problem, the docs seemed pretty clear when I used them this week so I
thought this might've been done to satisfaction already :)

**Comment by Alys** [comment]
Here's my proposed message to be placed on on the [Settings > API](https://habitica.com/user/settings/api) page under the "Webhooks" title:

	Habitica provides webhooks so that when certain actions occur
	in your account, information can be sent to a script on another
	website. You can specify those scripts here. Be careful with this
	feature because specifying an incorrect URL can cause errors
	or slowness in Habitica. For more information, see the wiki's
	[Webhooks](https://habitica.wikia.com/wiki/Webhooks) page.

(You don't need to use that short-line-wrapped format; I'm just using it here so the message can be seen without horizontal scrolling.)

I'll wait a few days to see if the staff have comments about the message and then I'll mark this as help wanted.

**Comment by natfarleydev** [comment]
I'm happy to implement this once it is approved.

**Comment by Alys** [comment]
@nasfarley88 Thanks! I've marked it in progress for you.
