### ISSUE TITLE
"Points Available" title is visible when no points are available

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10293]
Currently this happens only on our staging site and in local installs.

When you have allocated all your unassigned points, the "Points Available" header remains visible in the Stats screen, even after reloading. Below are three screenshots:

A. From staging/production when you have points available (same on both sites).
B. From staging when no points are available.
C. From production when no points are available.

Possible fixes:
1. Remove the label when there are no points to be allocated.
2. Change the label to something else when there's no points ("No Points Available"? "Points Allocated"?)
3. Display a zero when there's no points.
4. Anything else?

I'm marking this as suggestion-discussion for a decision to be made.

----

A. From staging/production when you have points available (same on both sites).
![selection_003](https://user-images.githubusercontent.com/1495809/39391211-5e5257a8-4ae3-11e8-8015-24df03241a24.png)

----

B. From staging when no points are available.
![selection_001](https://user-images.githubusercontent.com/1495809/39391209-5dc70f68-4ae3-11e8-8be9-e4a5703495e4.png)

----

C. From production when no points are available.
![selection_002](https://user-images.githubusercontent.com/1495809/39391210-5e084122-4ae3-11e8-82e0-f4e351de794a.png)

**Comment by TheHollidayInn** [comment]
Eh, I did this on purpose. But didn't realize the title. We should just change the title text.
