### ISSUE TITLE
Death modal appears multiple times when dying after Record Yesterdays Activites

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10298]
Embrace (9030eb72-300a-4d82-997d-8094504a3c99) reports: 

**"When you die, it's super buggy. The modal div appears and then instantly goes away, and then appears and then instantly goes away, and then appears again. On the third time it finally stays put like it's supposed to."**

**"It's happening when I die from not completing dailies on the previous day. The modal pops up asking which ones you completed, and if I click 'Start my new day' and yesterday's uncompleted dailies then kill me, the 'you're dead' modal (paraphrasing) flashes on and off the screen and the sound plays multiple times."**

I was able to replicate it although the modal only appeared twice in my case.

**Comment by haydenbetts** [comment]
@Alys 

I tested with:
Browser: Chrome 66.0.3359.181 (Official Build) (64-bit)
OS: 10.12.6
Local Habitica installation

I was not able to replicate. I couldn't replicate this behavior with either the death modal that appears after you do not complete dailies or the regular death modal. 

Do you have replication tips?

**Comment by TheHollidayInn** [comment]
These things have been hard to replicate for me as well, but we do want to move to a new UX. -
- Basically, when you die, there should be a snackbar (top right notification like xp and gold) that does not disappear until clicked
- Then user can then click that notification to open the modal

That will prevent the death modal from going on our stack and causing the above issue. (we also want to do this with many other modals)

So, if you would like to move the death modal to that flow, we would be happy to accept a PR :D

**Comment by haydenbetts** [comment]
Ah got it. Ya you can assign this to me.

**Comment by TheHollidayInn** [comment]
Thanks :D

**Comment by beffymaroo** [comment]
@haydenbetts Are you still working on this issue? Please let us know when you have a moment. Thanks!

**Comment by haydenbetts** [comment]
@beffymaroo No I am not currently working on this issue.

**Comment by beffymaroo** [comment]
@haydenbetts Thank you for the update.

**Comment by TheHollidayInn** [comment]
@negue can you apply the same technique from: https://github.com/HabitRPG/habitica/pull/10493 to to the Death modal?

**Comment by negue** [comment]
On it

**Comment by negue** [comment]
@TheHollidayInn If I move it to a notification (without a timeout) then its maybe not that visible to a user instead of a modal, plus all of the website functionality itself still "works" even though the user isn't revived yet.

Should I put it on "readonly" mode or something else until a user is revived? 
Or should I call the revive already once the notification is shown and the modal wouldn't do anything else anymore?

**Comment by TheHollidayInn** [comment]
Hmm, yeah, let's try auto reviving and seeing how that feels

**Comment by negue** [comment]
Removing the death modal from my notification PR, but the issue that it opened multiple times should be fixed by my changes anyway.

**Comment by Alys** [comment]
I can't reproduce this and I don't recall seeing reports of it recently so I'm guessing this was fixed incidentally by code changes. I'm closing it.
