### ISSUE TITLE
show accurate Experience (XP) gain in notification on level-up

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10297]
As described in https://github.com/HabitRPG/habitica/issues/9339, the Experience notification was deliberately removed when you level up because it was reporting that you lost XP. Strictly speaking, it was correct that you'd lost XP because on level-up you go from a high XP to 0 XP, however it's demotivating to see a message about losing XP.

The Experience notification should appear and should correctly display how much XP you gained when you level up.

However this might not be a trivial fix because our notifications are based on the total change in stats.

**Comment by mcshakes** [comment]
If no one called dibs, I'd like to take a crack at this. Anything I need to know before I dive in?

**Comment by Alys** [comment]
@mcshakes Please go ahead, thanks!

**Comment by beffymaroo** [comment]
@mcshakes Are you still working on this issue? When you have a moment, let us know. Thank you!

**Comment by mcshakes** [comment]
Hey @beffymaroo, sorry for the delay. Was off on vacation and turned off notifications. Actually, I won't be able to work on this. I recently took over a couple large projects at work, so will have to focus my attention on those.

**Comment by beffymaroo** [comment]
Thanks for the update, @mcshakes !

**Comment by Arsnael** [comment]
Hi there ! May I take a shot at this one? Sounds like a good first issue to dive into the project :)

**Comment by paglias** [comment]
@Arsnael sure, go ahead!

**Comment by Arsnael** [comment]
Thanks @paglias , I'm on it !

**Comment by Arsnael** [comment]
So I think I fixed it. I recalculate the experience needed to level up from the previous level (as level already got updated before), reusing the function 'toNextLevel', then recalculating the xp gained from it. So in this level up case I pretty much do : 

``
toNextLevel(lvl - 1) - before + after
``

So for example, let's say I'm level 3, I have 290 XP and the limit for leveling up is 300. I then gain 20 XP from a task, allowing me to level up to level 4 and new state of XP at 10 : 

``
toNextLevel(4-1) - 290 + 10 = 300 - 290 + 10 = 20
``

The only problem is if the user gains multiple levels at once (a low level perhaps being in a party that just slained a big monster, is that could be possible?). Then I believe this would be an edge case (probably happens rarely, but still)... But with the notifications just being sent on the watch of the states of stats, we only get the two states of XP in that portion of code... I don't see how we could know there that we get multiple level ups... So let me know what you think on this matter.

**Comment by joedragons** [comment]
Disclaimer: Just a user of the site (who has seen/been affected by this) not an admin.

I'm 95% sure you can (or could) gain multiple levels at once.  I started a second account for work and jumped right into my main quests and pretty sure this happened.  That was a while ago now tho, maybe things have changed.

I do agree it's an edge case and if I understand the equation right would result in showing a smaller (but non-negative) number which I think is an improvement at least.
2 cents, thanks for your work=)

**Comment by Arsnael** [comment]
Thanks for the comment @joedragons , greatly appreciated :)

**Comment by majestic-owl448** [comment]
I am too not an admin, but maybe I could give some math advice.

There are two situations in which one could level up multiple times at once: first, when finishing a quest one could gain a lot of xp, and in this case you would have things like 1132/150 experience and your formula should work to show the experience gained when completing next task. (The level up happens only when completing a task, not on receiving exp from a quest) // edited to add that in this case your formula could show a negative number actually. It depends on how the `toNextLevel()` function get the level to use
The other case is when someone complete a todo with a lot of checklist items, in this case there is the gaining of a lot of experience and multiple levels all at once, and in this case your formula wouldn't show the exact amount gained, but maybe with some more variables it could work. The extra variables would be the max exp for each level that was jumped over.
For example, starting point is level 8 10/240 xp and ending point is level 13 100/310 xp. Your formula would give 330, to make it correct it would need to add the max exp for levels 9-12, so 330+250+260+270+280+290+300 = 1980

You would probably need to loop the `toNextLevel()` function between levels 8-12 to get the correct thing here.

Yes, thank you for your work :)

**Comment by Arsnael** [comment]
Well the problem is that the notification is being built on the watch of the XP stat. So I make the assumption that user gets one level up, and apply the math there. But it seems to me that there is no way of really knowing there if the user gains one or more levels... Or if there is one, well I would love somebody to tell me how, then indeed looping on this would be possible then !

Thank you for your comment as well :)

**Comment by paglias** [comment]
The PR that fixed this has been reverted due to #10635

**Comment by Arsnael** [comment]
Well I could try to rework more on it if @TheHollidayInn doesnt have much time on this. But let me know :)

**Comment by paglias** [comment]
@Arsnael sorry for the late response! If you want to work more on this it would be great :)

**Comment by Arsnael** [comment]
Yes I can give it an other shot :)

**Comment by Arsnael** [comment]
There you go ! This time it should do the trick ! (I hope^^)
