### ISSUE TITLE
To-Do audio sound effect plays only once

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10294]
If you mark a To-Do complete, you hear the expected sound effect but then if you mark others complete, you don't hear the sound.

If you then complete a different type of task and then a To-Do again, you hear the To-Do noise, but again it's just for one To-Do - further ones are silent again.

Note that when testing this on a local install, you can avoid interference from the drop sound effects by setting your `items.lastDrop.count` to a high value.

**Comment by Amethystix** [comment]
I'm actually not even hearing the first sound effect; to-dos are just completely silent for me.  I tried refreshing the page, checking off something else before checking off a to-do, and even just creating and checking off more, but it's still silent while the other sounds play normally.  I'm using Chrome.

**Comment by paglias** [comment]
Weird, this works locally but not on habitica.com (or staging)

**Comment by paglias** [comment]
https://habitica.com/static/audio/danielTheBard/Todo.ogg (for example) doesn't exist in prod, that's why it's not playing
