### ISSUE TITLE
Installation with 'npm install' failed because of 'memwatch-next@0.3.0'.

### ISSUE THREAD

**Issue by pengfluf** [HabitRPG/habitica#10291]
Hi.
I was following the [guide](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally_on_Linux), reached the node modules installation step and can't move on.
Here's what I got after ```npm install```:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Node version: 8.11.1
npm version: 5.8.0
node-gyp version (I'm not sure is it important or not): 3.6.2

In the proccess of searching, I came across the same problem, but those issues are out of date and all the solutions relate to the replacement of [memwatch](https://www.npmjs.com/package/memwatch) with [memwatch-next](https://www.npmjs.com/package/memwatch-next).

Also I checked [memwatch-next](https://www.npmjs.com/package/memwatch-next) package and found that it hasn't been updated for **two years**, [node-memwatch](https://github.com/marcominetti/node-memwatch) for more than a year since January 27, 2017 (and this is in view of the fact that the new 10 version of Node.js is already released and will be in active LTS since October 2018).

My questions are:
1. Maybe I'm doing something wrong?
- If so, what exactly?
2. Is there any point in continuing to use this outdated package?
- Why use memwatch, heapdump or node-inspector if since version 6.3 Node.js provides a built-in debugger?

**Comment by paglias** [comment]
Are we still using this @TheHollidayInn ? I'm fine with making it an optional dep since it's only used in production

**Comment by paglias** [comment]
btw, I'm having the same issue with node 10 (but not node 8)

**Comment by TheHollidayInn** [comment]
We are still using this. Making it optional for development is fine.

**Comment by paglias** [comment]
It's optional now
