### ISSUE TITLE
Lunar Battle quest scrolls show wrong unlock conditions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10295]
The three Lunar Battle quest scrolls are unlocked after a certain number of check-ins. However for the second and third scrolls, the Quest Shop says that you can unlock them by completing the preceding quests, which is wrong, as well as saying they unlock after check-ins, which is correct. 

In the two screenshots below, only the first sentence is correct. The second sentence should not appear.

![image](https://user-images.githubusercontent.com/1495809/39402445-c5d09c2c-4ba2-11e8-8bbd-0bd94f51f4e2.png)

![image](https://user-images.githubusercontent.com/1495809/39402447-d8822868-4ba2-11e8-935b-6f5abff754f9.png)

For comparison, the text for the first Lunar Battle quest scroll is correct:
![image](https://user-images.githubusercontent.com/1495809/39402449-f23494f8-4ba2-11e8-9614-1f7417556e60.png)

**Comment by DoguD** [comment]
I can work on this issue.

**Comment by paglias** [comment]
@DoguD thanks, go for it!
