### ISSUE TITLE
Lost all my stuff

### ISSUE THREAD

**Issue by machouette** [HabitRPG/habitica#103]
I started using Habit RPG yesterday. This morning, at first, it wouldn't let me login. When it finally did, I lost most of my stuff - habits, daily and todo - 3/4 of the stuff was gone. I also lost my tokens and health for no reason. 

Is that a bug, is it happening to anyone else

**Comment by JamPol** [comment]
@machouette there's currently a server side issue which is being worked out right now. You can follow the progress here: https://github.com/lefnire/habitrpg/issues/91

**Comment by lefnire** [comment]
#91
