### ISSUE TITLE
Party Member Issue

### ISSUE THREAD

**Issue by nuzzlebutt** [HabitRPG/habitica#1030]
Every time I, or someone else in my party invites a new member, all my party members disappear from my account and it says I'm in a party by myself.  But all the other people in my party can still see me.  The first time, they came back once the day reset in the morning.  But this time they've been gone for several days.

**Comment by lefnire** [comment]
when you're by yourself, click "leave party". There's a bug i need to fix ASAP where you can accidentally belong to multiple parties, and it's really a dice roll which one shows up on page refresh

**Comment by nuzzlebutt** [comment]
Thank you so much!  That worked, and I can see my friends again!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
