### ISSUE TITLE
"Your Skill backfires" message for Mage's Ethereal Surge skill is misleading

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10313]
As described in https://github.com/HabitRPG/habitica/pull/10121, Ethereal Surge does not give Mana to Mages, and when you cast the skill, if your Party contains other Mages, you see this message in a snackbar notification:
`"Your Skill backfires when mixed with another's magic. Only non-Mages gain MP."`
(That's the `spellWizardNoEthOnMage` string in spells.json.)

We tried to write that message carefully enough that it wouldn't be interpretted as an error condition or user mistake but unfortunately it is being misinterpretted. I've seen several questions about it, such as this one:
_"I'm confused: almost every time I cast Ethereal Surge, I get a pop-up that says: 'Your skill backfires when mixed with another's magic. Only non-mages gain MP.' What's confusing is 1) that this happens even when it has been more than 24 hours since anyone has cast Ethereal Surge for my party; and 2) I thought buffs 'stacked,' so aren't the non-mages in my party getting a mana-buff from my Ethereal Surge, plus their mana-buff from my party's other mage's Ethereal Surge, plus their mana-buff from my party's other mage's Ethereal Surge? (And if indeed they are, how is this 'back-firing'?) Thanks."_

It can also be a bit of a downer: _"This is so absurd but it's actually kind of demoralizing to see that my Ethereal Surge skill backfires every time I use it.  It feels like failure and makes the skill seem less worthwhile"_

So I think we should remove the message. It seemed great for gamification but not so good in practice alas.

Do we want to replace the message with something more mundane or just not show a notification at all? I'm leaning towards not showing a notification. The description of the skill says that it does not affect Mages so I don't know if an extra notification every time is necessary. No matter how we word it, some users might still think an error has occurred and it would likely always have a demotivating feeling.

**Comment by hathix** [comment]
I think a notification is useful, but it could be something as simple as `{player name} wasn't affected by your Ethereal Surge spell!`

**Comment by Yutsuten** [comment]
I see...
If we consider that no other skills have a custom (extra) notification, not having it in `Ethereal Surge` too really makes more sense, and it is less misleading. If the user is curious about what the spell does, the skill description have that information, as any other skill.

But somehow I still think that, at least as a temporary feature, the notification was a good idea. Now every mage (theoretically) knows about the change in the skill, therefore not being necessary anymore.

If a change is decided, may I take care of it? It was me who added it anyways...

**Comment by andrewschultz** [comment]
Maybe "Energy flows out to the non-mages in your party!" ... your non-mage companions

My feeling as a player is

* As-is, we may be in a catch-22. The long time players won't need the current message, but newer players may find it discouraging.
* hovering over "ethereal surge" does mention non-mages, but I think we should still have a succinct, positive message for each cast, since it is different from Tools or Valorous Presence. While mine is fewer letters than the current, I bet others can do better.
* I noticed the possibility for abuse in a party with 5+ mages pretty quickly, so I like the feature. Good work implementing it.

**Comment by Alys** [comment]
I think @Yutsuten makes a good point with this:
> But somehow I still think that, at least as a temporary feature, the notification was a good idea. 
> Now every mage (theoretically) knows about the change in the skill, therefore not being necessary anymore.

I feel that no matter how we worded the notification, it could still be misleading or demotivating, so I believe it's best to not have it now.
@Yutsuten I'll mark this as in progress for you since you've said you'd like to do it, but post here if you've changed your mind or are too busy now and we'll set it to help wanted. Thank you!
