### ISSUE TITLE
character limit on posts in Tavern, Guilds, Parties - client-side support only

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10312]
Posts in the Tavern, Guilds, and Parties should be limited to 3000 characters. Very long posts have been known to crash the mobile apps and also can be troublesome for moderation reasons.

The ideal situation is for this limit to be imposed by the API, however before that is done, there should be support for the in the website and both mobile apps. I.e., all three clients should prevent you typing or pasting posts that are too long BEFORE the API is modified. This is because if the API imposes the limit before the mobile apps do, then if someone types too much text on an app, their message will disappear when the API returns an error (highly undesirable for a long post).

So this issue is for **client-side** support for a character limit on Tavern, Guild, and Party messages in the **website** only. The textarea that allows you to enter your message should prevent more than the allowed number of characters being typed or pasted. As you are typing, you should see how many characters are remaining - I suggest doing something similar to the Summary field in the challenge creation form. When you've typed too many characters, you should see how far over the limit you are as you can for the Summary field however I suggest making it more obvious that you've typed too much - maybe the characters remaining field could become larger and red or something. Anyone who's absorbed in the process of writing won't notice that they've gone too far if it's not in-your-face. 

If you type or paste more than the limit, you should not be able to submit your post, however everything you've typed must remain in the text area so that you can edit it.

**NOTE: We might change the size of the limit in future. It would be great to be able to change that number in one place and have the API, website, and mobile apps pick up the change automatically and immediately. It would also be good if third-party tools could do the same. E.g., maybe the limit could be part of the content API? Or a separate route to return just the limit? I'm marking this as suggestion-discussion for staff to weigh in on this.**

I'll wait a few days for any comments about this issue and then create matching issues in the iOS and Android repos.

For anyone curious, this is what 3000 characters looks like:

123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789.

**Comment by marvinrabe** [comment]
I can do this if its needed.

**Comment by paglias** [comment]
@marvinrabe sorry for the delay, go ahead if you want to!

**Comment by beffymaroo** [comment]
@marvinrabe Are you still interested in or working on this issue? Please let us know. Thank you!

**Comment by Alys** [comment]
I've marked this as help wanted but @marvinrabe let us know if you'd like to claim it again.

I've created Android and iOS versions of this issue: https://github.com/HabitRPG/habitica-android/issues/993 and https://github.com/HabitRPG/habitica-ios/issues/722

When all three client-side issues have been completed, we can create a new one for API support.
