### ISSUE TITLE
Title of group creation modal is "Select Payment" rather than "Create Group"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10318]
From Bug guild:

> Ivan Ivanov (55a4ea34-b162-4183-9195-304b841d9422) 
> Hi! I just started creating a group and I noticed that the title of the form is "Select Payment", a bit strange I believe. Best regards!

![image](https://user-images.githubusercontent.com/8144640/39521508-1080ebbe-4e0f-11e8-887f-2088d20b10a8.png)

**Comment by Alys** [comment]
We have this recorded here: https://github.com/HabitRPG/habitica/issues/10118
along with some related problems. :)

**Comment by shanaqui** [comment]
Urgh, apparently I suck at searching today. XD
