### ISSUE TITLE
Unchecking dailies

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#1031]
I'm sure there is a card for just unchecking dailies but I can't find it 

My morning dailies have unchecked themselves from this morning.
Normally I would just recheck them and adjust my experience in the restore function (I have my experience from this morning) but today was day that I hit my 21st day on my streaks. I tried adjusting the streak in my daily and it gave me another streak achievement.

**Comment by wc8** [comment]
You can correct the streak under each task's Edit > Advanced Options

**Comment by Mihakuu** [comment]
Then I get another streak achievement because its past the 21 day mark

**Comment by wc8** [comment]
Oh, I see. The only workaround (while waiting for the developers) I can think of is to correct the streak tomorrow.

**Comment by Mihakuu** [comment]
That's a solution. Thank you

**Comment by AranelS** [comment]
For what it's worth, the other conversation is here: https://github.com/lefnire/habitrpg/issues/985

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
