### ISSUE TITLE
CPU loading in Habitica Tasks using Mac Safari (LastPass Related)

### ISSUE THREAD

**Issue by stuckfly** [HabitRPG/habitica#10310]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)
**On 4/26 Alys replied to my post (quoted below in Description) on the Report a Bug guild and requested me to report this here.**

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 7c998968-221e-49c5-a8fb-0b5a18ed7613
  * Browser: Safari 11.1
  * OS: MacOS 10.13.4

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
"Using Safari on a Mac. I've been getting [Safari] messages "This webpage is using significant energy. Closing it may improve the responsiveness of your Mac." in Safari for months now. Indeed, if I'm logged into Habitica I get a LOT of activity in the fans and a LOT of CPU use, plus the Habitica web content process takes about a gig of memory. I find nothing on your GitHub page on this, and nothing on the Trello suggestions. Known bug, or just me?"

From Habitica login to getting the Safari error took about 18 minutes and produced the Java console errors below. CPU for the Safari Web Content process for Habitica peaked at 151% (of 4GHz Intel Core i7 4-core processor) and averaged about 87% ONLY when the Habitica browser tab was the active one AND displaying Tasks. Memory consumption of that process runs about 650–750 MB (of 32GB)—it does not seem to be a memory leak (just saying, because I get a similar CPU problem logged into Gmail, but in addition to keeping the fans busy Gmail steadily hogs all available RAM until it crashes my computer after a day or so).

For the Java console error test (below) I first disabled all Safari plugins and extensions, and turned Little Snitch off. Then I did very little, just switched Habitica pages a few times and watched the CPU load and fan activity increase until Safari complained (Alys said to copy Java console contents at that point, but after login nothing produced any more console feedback).

In Safari, JavaScript is enabled, pop-up windows are not blocked. Cookies are enabled, website tracking is set to defaults (prevent cross-site tracking and ask sites not to track). I have not changed any Safari settings since long before this problem began—but I don't know what Apple may have done to Safari in their frequent updates…

I had a webhook setup in Habitica to attempt integration with Trello via a Zapier app a long time ago, but it is shown as not enabled in Habitica settings (it never worked well anyway). Besides, this problem is relatively recent.

I don't know whether I'll get notifications from GitHub or not (will check my settings after posting this), so if you need more info to figure this out and you get no response from me, shoot me an email to dzturbd@gmail.com

Cheers!

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
[Warning] Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/ (vendor.b91cfcde844f24cdc5d8.js, line 1)
Arguments: 
https://habitica.com/static/js/vendor.b91cfcde844f24cdc5d8.js:1:12950
https://habitica.com/static/js/app.556d286a21777a872250.js:1:243275
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:18285
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:348872
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:584640
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:342512
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:584002
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:583390
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
https://habitica.com/static/js/app.556d286a21777a872250.js:1:583088
n@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:105
webpackJsonp@https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:419
global code@https://habitica.com/static/js/app.556d286a21777a872250.js:1:13
[Error] Failed to load resource: the server responded with a status of 400 () (1896979_525640974215932_796646050_n.jpg, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (shinto_shrine.png, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (weight_lifting_man.png, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (pick.png, line 0)

### For anyone with the same problem

If you have LastPass enabled it's possible that the problem is caused by the Autofill feature of the LastPass extension, try disabling it and see if it helps.

**Comment by paglias** [comment]
Hi @stuckfly, have you tried if the same thing happens with Chrome or Firefox? Also can you try opening a private window in Safari and login from there and see if the problems persists? If it goes away you should try to clear your cache / cookies.

The fact that you're getting the same type of problems with gmail could indicate that there's a problem with your Mac, but myself with only 16gb of ram and a less powerful processor never had the same problem

**Comment by stuckfly** [comment]
Using a private window in Safari and logging into Habitica gives same CPU results, with one odd difference: it does not matter what tab, window, or app I go to—even if Safari is not the active active app it hogs resources (whereas in a non-private window it only happens with Habitica up front in Safari looking at the Tasks page. Weird.

It took me a lot of work to remove Chrome last year, because Google embeds login daemons with it and they were running amok. So, not going to install Chrome on a Mac ever again (or any Google app). I did install Firefox, and no CPU problem! Huh. So, that indicates it’s something to do with Habitica code versus Safari. But…Apple can’t be the problem, because they think different, so it has to be Habitica!

Yes, it could be a problem with my Mac, but the Gmail problem is a memory leak that takes a long time to matter, and it's been going on for almost a year (since I got this Mac). To test this I restarted into safe mode to rule out conflicts with third-party software and Habitica still overloads the CPU. So, it's almost certainly either my computer (probably not), MacOS (probably not), or your web code versus Safari. And Apple made Safari, so it must be Habitica’s code at fault. Not adhering to Apple’s standards! …do they still have those?

Fine. While Habitica tries to keep up with Apple’s Safari updates and proprietary standards (ahem…) I will use Firefox for Habitica. You may close this issue, except internally strive to satisfy Safari!

**Comment by marvinrabe** [comment]
I tried to reproduce it on my Macbook Pro 13 Retina 2015 with the latest version of macOS and Safari and current develop branch. I couldnt notice any increased CPU usage.

What Mac do you have? How many programs are running in the background (count the dots in the dock below the icons)?

**Comment by stuckfly** [comment]
Thanks for trying to reproduce the problem.

I'm on a Retina 5k 27-inch late 2015 iMac, latest versions of MacOS and Safari, and 32 GB RAM.
I average half a dozen apps running, but I've tested this with only Safari running, with only the Habitica Tasks tab and it still chews up the CPU.

Obviously, I've gotten cynical about Safari! (I hope you got that I'm leaning toward Safari at fault and not Habitica, but I did lay on the sarcasm overly thick in my previous post, sorry about that!)

Okay, you say you're also using the latest version, so…it must be some odd setting I've applied to Safari. I have confirmed the gmail memory problem also happens using Firefox, but the Habitica CPU problem does not. All indications are on the browser, but what could be odd about Safari that changed in the past month or two…on my system but not yours?

**Comment by buddhistpirate** [comment]
I've also seen this on my mackbook pro for a few months now. I just tried doing some profiling with safari, but with the minified javascript it is hard to diagnose anything specific. There are a lot of events firing and a lot of repainting even while I am not interacting with the page at all. I can spend some time digging into this more if someone can send me in a specific direction.

**Comment by buddhistpirate** [comment]
Just dug into this more. I used the "Tree" view in the Safari profiler. For me it was LastPass. I went into LastPass and turned on "Disable Autofill" for Habitica and the CPU usage returned to normal, and the message from Safari did not show up.

**Comment by stuckfly** [comment]
Huh. Well, for what it's worth I recently ditched LastPass (because it has for over a year annoyingly kept duplicating entries). So when I read your post, I re-tried Habitica on Safari (been using in on Firefox with no problem), and so far no memory issues. Conflict between LastPass and Habitica both on Safari seemingly confirmed. And now I can stop using Firefox. Thanks for your excellent sleuthing:)

**Comment by paglias** [comment]
@buddhistpirate thanks for investigating the problem, this is very useful! and thanks @stuckfly for confirming that it's LastPass in your case as well

**Comment by stuckfly** [comment]
Update. The CPU load problem has returned, with LastPass gone. No new software or system changes. What could cause the problem, and make it go away when LastPass is removed, and make it show back up again after a week or two?

**Comment by paglias** [comment]
@stuckfly do you have any other extension enabled? can you try to disable all of them and see if anything changes?

**Comment by paglias** [comment]
I see from an older comment that you already tried an incognito window which should disable all extensions anyway...

**Comment by paglias** [comment]
@buddhistpirate can you list the steps you used to find the problem? I'm not very familiar with the Safari debugger :) that would be very useful

**Comment by stuckfly** [comment]
3 other extensions (1Password, Pinbar, and JS Blocker 5). With all off, the problem persists.
Using Activity Monitor to watch CPU load. The problem only happens if Habitica is the active app and displaying the Tasks page while logged in.
In Safari Preferences/Advanced check Show Develop Menu, then in the Develop menu Show JavaScript Console and that's where I found the error messages I posted here. No idea what they mean. There are a lot of other options and tools in the Develop menu that might assist. Or maybe one of the Experimental Features that are on by default is causing the problem? No idea what any of them are for…

**Comment by stuckfly** [comment]
it takes about a minute for Habitica to max out its CPU usage between ~95% and 125%, then about 15 minutes later Safari displays a message at the upper-left of the Habitica tab saying it's using a lot of resources. Previously, Console would then show errors, but now I'm not seeing any (unless I click on the message, but I assume those errors are about the message itself; not Habitica).

@buddhistpirate I see the Debugger is just another tab in the Web Inspector along with the JS Console tab. No idea how to use any of these things. Good luck! Anything else you want I should try?

**Comment by buddhistpirate** [comment]
So when I am just sitting on the Tasks page, this is what the Safari profiler shows while the CPU usage is between 60-90%.


![screen shot 2018-10-21 at 6 55 03 pm](https://user-images.githubusercontent.com/1327812/47273495-08beca00-d563-11e8-9e42-c90c0a60b53f.png)

Not sure that's a lot of help, but without knowing how to debug/profile vue.js, I'm not sure I have much to offer. If someone wants to do a remote debugging session, I would be up for that.

**Comment by mrfcobf** [comment]
Any update on this?  I have never used LastPass (in fact, I hadn't heard of it until reading this), but I have the same problem.

I'm on a brand new MacBook Pro Intel Core i9 2.9 GHz, 32 Gb of 2400 MHz DDR4 RAM, and the new video card - Intel UHD Graphics 630 1536 MB, running Mojave 10.14.3 Beta 18D21c.  (This also happens on my wife's machine and she is not running the Beta.)

**Comment by manuelgrabowski** [comment]
Same problem here, after about a minute of having the Tasks page open my Mac goes from completely silent into "it's probably gonna explode soon"-mode.

**Comment by paglias** [comment]
@manuelgrabowski which browser are you using?

**Comment by manuelgrabowski** [comment]
Safari Version 12.0.2 (14606.3.4)

**Comment by rasbt** [comment]
Same issue here. I am not using LastPass though, and I think the problem is unrelated to LastPass.

The problem occurs primarily only on one of my MacBooks. I have two macbooks, a 2015 and a 2018 model which have the exact same setup (same OS, Safari version [v 12.0.3], etc.). One the 2018 model, this issue occurs pretty frequently, but on the 2015er model it doesn't, for some reason.

My guess is that there is maybe some javascript that sometimes (not always) gets out of control and then hogging up the whole CPU then. The only extension I have enabled is 1Password, but disabling it doesn't help. I think it's unrelated to extensions, although private tabs seem to solve the issue.

**Comment by paglias** [comment]
@rasbt sorry about that, you're probably right that there's some piece of js going out of control, unfortunately I've not been able to reproduce the issue on Safari myself and until we get a good reproduction it's difficult to find what causes it

**Comment by veeeeeee** [comment]
Closing for now as Safari has had quite a few updates since the last post in this issue. If something similar to this pops up again, please start a new issue ticket.
