### ISSUE TITLE
Market seems to force you to sell 0 of an item

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10316]
From Report a Bug:

> Hey folks. Windows 10/Edge user here. I'm experiencing a bug where when I try to sell eggs and potions in the Market, the count automatically drops to 0 if I try to input a value other than 1. Thanks

This is confirmed on Windows 10/Chrome, screenshot:

![image](https://user-images.githubusercontent.com/8144640/39472097-5f5f027a-4d47-11e8-9123-b4635def825f.png)

I suspect this is to prevent errors from people clicking to sell with no number entered, but right now if you try to erase the 0 to add a number, you can't. You *can* sell whatever number of items you want by entering the number and leaving the zero in (e.g. to sell two, it'll show 02, to sell twenty, 20), but it's confusing for users.

**Comment by DoguD** [comment]
I want to work on this issue

**Comment by paglias** [comment]
Go for it @DoguD !

**Comment by paglias** [comment]
@DoguD I'm going to fix this directly in develop
