### ISSUE TITLE
The page at http://www.habitrpg.com says:

### ISSUE THREAD

**Issue by janepernille** [HabitRPG/habitica#1032]
<html>
<head>
    <meta charset="utf-8">
    <title>HabitRPG | Error</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

```
<!-- CDN -->
<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css" rel="stylesheet">

<link href="/vendor/bootstrap/docs/assets/css/docs.css" rel="stylesheet">
<link href="/css/static-pages.css" rel="stylesheet">

<style type="text/css">
    .rotate-img {
        transform:rotate(90deg);
        -ms-transform:rotate(90deg); /* IE 9 */
        -moz-transform:rotate(90deg); /* Firefox */
        -webkit-transform:rotate(90deg); /* Safari and Chrome */
        -o-transform:rotate(90deg); /* Opera */
    }
</style>
```

</head>

<body>
    <div class='container'>
        <div class='marketing'>
            <img class='rotate-img' src="/img/sprites/armor3_m.png" />
            <h2>The server is experiencing issues.</h2>
            <p><a href="/">Try again</a> in a few, the developer has been notified. The most likely culprit is <a href="https://github.com/lefnire/habitrpg/issues/165">this issue</a> which Tyler is working to fix. (Any memory leak experts?)</p>
        </div>
    </div>
</body>
</html>

![screen shot 2013-05-23 at 20 52 11](https://f.cloud.github.com/assets/3949605/556492/05e70658-c3da-11e2-9f0a-59ccedf1f4f3.png)

I don't know what it means, but maybe it's interesting for you guys?
- cheers!

**Comment by lefnire** [comment]
yeah, this is when the server goes down. due to #165. let's follow up there
