### ISSUE TITLE
Can't purchase eggs or hatching potions

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1033]
I just unlocked the drops/pets system. I have 20 Gems from buying off the ads, but I can't purchase hatching potions or eggs. They're static images and text, not interactive. When I mouse over eggs in the shop, they get a background highlight, but clicking on them, drag/drop, etc. have no effect. Hatching potions don't even get a highlight.

This is in Chrome; I'll try Firefox later.

EDIT: Nope, no different in Firefox.

**Comment by lefnire** [comment]
Hmmm. is anyone else experiencing this issue? I can't replicate in either browser (I get the purchase dialog). Any javascript errors: http://community.habitrpg.com/content/submitting-bugs ?

**Comment by bobbyroberts99** [comment]
Using Safari on Mac OS X 10.8.2, I was able to buy and hatch a Zombie 
Cactus.

Tyler Renelle wrote:

**Comment by SabreCat** [comment]
Ah, today it's working. Weird! Closing.
