### ISSUE TITLE
Avatar's face disappeared

### ISSUE THREAD

**Issue by demhips** [HabitRPG/habitica#1035]
This isn't a huge issue but my avatar's face disappeared sometime last night.  Maybe my fox ate it? :P

**Comment by lefnire** [comment]
Oh no! Temp fix, go to Profile and choose your avatar's head, hair, and
skin. I'll investigate soon

**Comment by demhips** [comment]
That fixed it, thanks!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
