### ISSUE TITLE
Cannot allocate stat points after leveling up unless you reload the page first

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10353]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

In the last ~36 hours, we've received several Report a Bug Guild complaints similar to the following:

>Gumnos (43e2413a-f440-43c8-b96c-85b93024488c) 
>
>Problematic sequence: do something to gain XP (click on a task or use a skill that gives XP), get the "You went up a level" notification, go into my profile, bump up a stat by a point, click Save, get a "You don't have enough stat points" error.
>
>I can refresh the browser, go back into my profile, see the available stat point bump it up again, and then save, and it takes.
>
>If I refresh my browser after the "You went up a level", the allocation also sticks around.
>
>But for some reason, it needs me to refresh the page after the "You went up a level" before it will actually allow me to allocate those points in a way that takes.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None reported as yet, but can request if it'd help for diagnosis.

**Comment by Alys** [comment]
sounds related to this: https://github.com/HabitRPG/habitica/pull/10344#issuecomment-387560960
