### ISSUE TITLE
duplicate/multiple notifications for new guild/party messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10356]
As reported by Gumnos (43e2413a-f440-43c8-b96c-85b93024488c): 

"Until recently, I'd only get one notification per guild/party (3 guilds + 1 party meant usually no more than 4 notifications unless there was the occasional extra stat-point to allocate, a quest notification, or a DM).  Sometimes I'd hit a glitch and it would give me one duplicate, but refreshing my browser always fixed/consolidated duplicates down to a single instance.

Today I encountered multiple notifications for the same guild but it wouldn't compact them when I'd refresh. That said, clicking on one of the notifications cleared all of the duplicates."

![screenshot](http://thechases.com/tmp/habitica/notification_count.png)

**Comment by paglias** [comment]
This is probably due to the fact that we disabled versioning for notifications: https://github.com/HabitRPG/habitica/pull/10348/files#diff-7335e8e068fde8d7b2f308037cd04730R600

**Comment by negue** [comment]
While trying to create a test (having members of a party post a message) the notifications never exceeded the count of 1.

Then I saw this:

```
 const lastSeenUpdateRemoveOld = {
    $pull: {
      notifications: { type: 'NEW_CHAT_MESSAGE', 'data.group.id': this._id },
    },
  };
```
in `group.js`, the change is from January 2018.

So maybe those notifications are before this change ?

**Comment by paglias** [comment]
I think I've had this happening to me a few times and I think it happens when multiple people posts several messages at the same time

**Comment by Alys** [comment]
It's definitely still happening. The two below are in my `notifications` array now and I cleared all notifications a few days ago.
```
        {
            "id": "49d43a85-a169-49ec-8c6b-960fdb130cb0",
            "data": {
                "group": {
                    "id": "a7d0a7c8-f1cf-4813-b841-75308003f611",
                    "name": "Elven Grove"
                }
            },
            "seen": true,
            "type": "NEW_CHAT_MESSAGE"
        },
        {
            "id": "b3aa72bc-7791-4dc4-9d9e-e7bbd4c82759",
            "data": {
                "group": {
                    "id": "a7d0a7c8-f1cf-4813-b841-75308003f611",
                    "name": "Elven Grove"
                }
            },
            "seen": true,
            "type": "NEW_CHAT_MESSAGE"
        },
```
