### ISSUE TITLE
Tag checkboxes no longer appear within Tasks

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10351]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Checkboxes no longer appear for the list of tags selected within a task. This (a) makes it difficult to tell what tags have been selected if more than a couple apply, because the readout above simply says "+N more" with no further info; and (b) confuses users thinking there's no longer a way to add or remove tags from a task.

![image](https://user-images.githubusercontent.com/4501321/39850186-94838ad6-53d5-11e8-88f3-449def594b21.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None

**Comment by SabreCat** [comment]
Resolved by reverting `bootstrap` to version 4.1.0 (from 4.1.1). We'll wait for another version update and see if it continues to be trouble.

**Comment by paglias** [comment]
Could be this https://github.com/twbs/bootstrap/issues/26453

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitica/commit/6db412f7e683d7390c644a210a11d10a67cc7478 and then upgraded again
