### ISSUE TITLE
Group tasks not behaving as expected

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#10365]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID:  1e7fda50-e6b7-4047-9bcd-70110c713b01
  * Browser: Chrome v66
  * OS: Windows 7

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Tasks which are assigned to group members do not share progress between members. Assigning a task to multiple people seems to copy the task to the assignee rather than share it. From what I can tell, this means that even if two people are assigned the same task, if one person completes the task the other person still has to complete it too. Similarly, if a task is edited from the group page the changes are not updated on the users task page. They must unclaim and reclaim a task to get updated changes.

Steps to reproduce:

1. Go to the "Task Board" for a Group Plan you own.
2. Create a task.
3. Assign it to multiple Group Plan members.
4. In each member's account, sync to make the task appear in the user's Tasks screen.
5. In one of the member's account, mark the task as complete. On the second member's account, sync, observe that the task remains for the second member and its appearance is not changed.

**Comment by TheHollidayInn** [comment]
This is currently the expected behavior. Assigning a task to two users means that each of them must complete it. 

We have discussed the shared progress, let me share your suggestion internally.

**Comment by SabreCat** [comment]
There's some confusion in the Report a Bug Guild about this even now:

**Squatch** (e723a5b7-a58f-4871-96e7-61c1a1dc9d87):
> It seemed odd to me that when the member assigned to complete the task actually selected the complete checkmark it wouldn't update to complete on the group page.  It still shows up in the Active category of tasks (in fact I don't see any changes as to what tasks are listed on the group page when you filter by "Complete" vs "Active").  I also seem to not be able to mark the complete checkbox on the group page itself.

**Comment by SabreCat** [comment]
Another example:

**Gioconda herrera** (fa8cf0e6-d581-4d68-85ec-1fb79f026758):

>Les escribo porque pague para crear un grupo, y tenemos un problema. 
>Cuando colocamos tareas pendientes, a los dos nos sale en nuestra tareas pendientes (que esta bien) pero cuando alguno de los dos o los dos les da como realizada sigue apareciendo activa en las tareas de grupo."

**Comment by SabreCat** [comment]
'Nother today:

**Sarah Johnson** (1aee73b9-af77-4042-895e-fa8fc16f85bb) 
> I can assign the task to my team mate, he is able to complete it under his task page, but is not able to check it off on the group task page. Also, completing it on his task page doesn't mark it complete on the group page automatically. The error that he is receiving is: the error "Not Authorized to manage tasks".

**Comment by SabreCat** [comment]
Bumping to Important because this is a repeated concern raised by users who are paying extra for this functionality.

**Comment by SabreCat** [comment]
Another report today:

**IGetCarriedAway** (4f439510-6f8c-46b0-863d-04105a01d1f7) 
> Yesterday I created a To Do in the group tasks. The To Do was completed and I checked it off under my tasks. Today it is still appearing int he group To Dos and is not disappearing as if it was completed. So far it seems that none of the tasks that my team completes are removing from the group tasks when they check them off on their side. We're paying for a group plan, but it doesn't seem to really help us track anything at the moment.

**Comment by ghost** [comment]
Are there any plans to change how groups share tasks ?

**Comment by SabreCat** [comment]
@FenJai I just conferred a bit further with @TheHollidayInn about this, and I'm going to start working on a new feature/option to address this.

**Comment by monsterfurby** [comment]
Same issue here. Seems like changes to tasks do not propagate properly to Group. So right now, essentially the functionality seems to be limited to claiming (triggers message, changes claim state) and copying a task from the group to the individual task dashboard with no communication going the other way. **This behavior is not limited to tasks claimed by several users.**
This cannot be WAD.

**Comment by TheHollidayInn** [comment]
The default behavior is to not complete the group task automatically. Sabe is working on adding that option.

Are you also stating that you want other details to propagate? As in, edits to the task on the users side to update on the group side. We built the based on challenges which don't allow for that, but that seems like an obvious want if I am understanding correctly.
