### ISSUE TITLE
Death from habit

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#1036]
You cannot die from a - only habit. I click the - but it does nothing when you are at low hp.+/- work fine, but after some clicking they stopped working too. I clicked the - only habit a to bring me to death, then clicked on a +/- habit and nothing happened. So after some clicking the - on the +/- and "minus only" habits they are now not responding at all, but they still change their colour. If I click + it works fine. I'll try another anonymous account to investigate further

**Comment by nikrage** [comment]
Maybe it's a deeper issue. It happens on the beta. I tried it on the main site and there is no issue.

**Comment by nikrage** [comment]
Yes definitely a problem on the beta. Tried with another account. The main site has no problems.

**Comment by lefnire** [comment]
@nikrage thanks for pointing this out, good info. We made a big overhaul to beta's logic, which allows us to write unit tests (so we can be less buggy). I'm not going to merge to `master` till I get those tests squared away, but manually spotting bugs like this will help make the process go much faster, so thanks.

**Comment by nikrage** [comment]
Happy to help :)

**Comment by lefnire** [comment]
actually, I can't replicate m'self - can you see if there are any [javascript errors](http://community.habitrpg.com/content/submitting-bugs) per chance? What's your user id?

**Comment by nikrage** [comment]
No errors. I'm using firefox/windows 7. Using anonymous accounts for this. I think the problem occurs when the habit is the darkest red. Try to replicate again. Click the "-" on a habit until it stops working on the beta.

**Comment by lefnire** [comment]
Got it, now I see - thanks!

**Comment by lefnire** [comment]
fixed, thanks for your info https://github.com/HabitRPG/habitrpg-shared/commit/6e4f1a40f84b1cf09221c3a693f5adb6984e03df
