### ISSUE TITLE
Challenge formatting including text wrapping is wonky on the guild page

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10371]
Reported by Cinnamon Toast in Report a Bug, confirmed by me:

> Hello, I've got a petty little bug for you, in the new design for challenges.  While the markdown formatting for italics and such is working in the title of the challenges, it's not working in the challenge summary as it displays in the guild screen.  In the current challenge in The Society of Old Books guild, for example, the text in the summary just shows the asterisks on either side of the text and doesn't change the text to italics.  Also, the wraparound of the sentences does not divide at spaces, but in the middle of the word (it divides the word BY in between the B and the Y).  When I went in to edit the challenge, the formatting was correct in that screen, but shows up wrong when I go to the guild screen.  The guild is at https://habitica.com/groups/guild/a2af16f6-fcee-4f7f-a6ab-77b8f97c49b2

Examples:

![image](https://user-images.githubusercontent.com/8144640/40229012-40d8e31c-5a93-11e8-8af9-0e3d5b5fd00c.png)

![image](https://user-images.githubusercontent.com/8144640/40229022-4c729cd6-5a93-11e8-852a-b927f84ac93b.png)

**Comment by paglias** [comment]
So the issues here are both the text wrapping and the missing markdown formatting?

**Comment by shanaqui** [comment]
Yep!

**Comment by paglias** [comment]
Fixed in release, will go live soon
