### ISSUE TITLE
Redirect URI Mismatch errors with Google login

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10375]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info

Attempting to log in to specific pages on Habitica using Google authentication often throws a URI Redirect error. The user must head to e.g. the bare URL habitica.com in order to proceed cleanly.

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Example when trying to click the Report a Bug link while not logged in:

![screenshot](https://i.imgur.com/CFOVAzW.jpg)

**Comment by TheHollidayInn** [comment]
I'll fix this.

**Comment by FynnMazurkiewicz** [comment]
Not sure if the fix/PR hasn't been released yet, but I still experience this issue on the live version.
Example URL: _https://habitica.com/login?redirectTo=%2Fgroups%2Fguild%2Fa29da26b-37de-4a71-b0c6-48e72a900dac_

**Comment by paglias** [comment]
I'm reopening, @TheHollidayInn I think the problem is that with a `''` as the redirect url it uses the current url. we should redirect to the same url all the times instead

**Comment by SabreCat** [comment]
We're also seeing this happen with links from within Habitica emails, e.g. https://habitica.com/login?redirectTo=%2Fuser%2Fsettings%2Fnotifications

**Comment by paglias** [comment]
@SabreCat we can add it to the whitelist for the meantime but the solution is this https://stackoverflow.com/questions/7722062/google-oauth2-redirect-uri-with-several-parameters
