### ISSUE TITLE
Flicker when user mouses over the very leftmost edge of party member avatar

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10379]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: Various
  * Browser: Chrome, others?
  * OS: Windows 10, others?

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

There is a small area (1-2 pixels wide perhaps?) in the party header where if the user mouses over it, it flickers rapidly and unpleasantly between displaying and hiding the first party member's mouseover details.

Video: https://drive.google.com/file/d/1q7ONERmRuZXTo5VVq6GQ9sv_DHUAQSJj/view

**Comment by haydenbetts** [comment]
Hi @SabreCat !

I was able to replicate this 
Browser: Chrome (it doesn't affect Firefox)
OS: MacOS 10.12

I also found a one line CSS fix that doesn't result in any noticeable change to the UI. If you assign this to me, I am ready to submit a PR! 

Video of behavior in Chrome with fix: https://drive.google.com/open?id=1FSM-PFIjGzr1yEvs6OkjQ2vcQaUKd5i6

I believe that the issue had something to do with the way Chrome processes animation effects. I think a border animation was causing the cursor to repeatedly hover an unhover an element.

**Comment by paglias** [comment]
Go ahead @haydenbetts !

**Comment by beffymaroo** [comment]
@haydenbetts Are you still working on this issue? Please let us know when you have a moment. Thank you!

**Comment by haydenbetts** [comment]
Hi  @beffymaroo. No I am not currently working on this. I got stuck trying to write tests for my fix. The WIP PR that I submitted does contain a solution to the issue itself though!

**Comment by SabreCat** [comment]
This doesn't seem like the sort of fix we'd need a test for anyway! I'll take another look at that PR.
