### ISSUE TITLE
My Pet Went Back into Its Egg :(

### ISSUE THREAD

**Issue by ravvic** [HabitRPG/habitica#1038]
I hatched my panda cub a few days ago once I got a potion, and the cub was sitting in the stable. Then I went back the next day to find it was back in it's egg, like it never hatched! I'm being told I don't have any potions to hatch it, and to wait for one to drop, but obviously that already happened. What should I do?

**Comment by cleave29** [comment]
I had the same thing happen, except it gave me both the potion and the egg back.  No biggie for me personally.

**Comment by wc8** [comment]
duplicate/related to #952?
One possibility is a server connection issue...in which case refreshing the page to make sure changes registered might help, but I think #952 is the best place to follow up with missing pets and hatching potions.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by JohnKennex** [comment]
Hello! I would like to say that this happened to me last night. I had a Dragon egg that I hatched with a Shade Potion, and today I check in, and I see that I have both the Shade Potion and Dragon egg back. It let me hatch the dragon egg again, but it was still rather annoying.
