### ISSUE TITLE
Challenge owned / not owned / joined indicators don't update correctly after filtering

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10382]
_As reported by citrusella, the serving wench (2d6ef231-50b4-4a22-90e7-45eb97147a2c) in the Report a Bug guild:_

"If you check off 'owned' or 'not owned' on the challenges screen, the indicators for owning/joining stay the same/in the same order and don't seem actually connected to the challenges in question.

"For example: If your list of challenges has three 'joined' followed by an 'owned' in the fourth position (followed by, say, more 'joined'), and then you click the checkbox for 'not owned' in the sidebar, then the fourth challenge will still say 'owned' even though it's actually 'joined' since you're not displaying owned challenges. (This can happen the other way--that is, by hiding not-owned--as well.)"

**Comment by paglias** [comment]
Working on this one
