### ISSUE TITLE
Some users not receiving quest invitation emails as expected

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10389]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 221859e5-5d04-4753-9577-e0f4ca918b8c
  * Browser: Unknown
  * OS: Unknown

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The user noted above has quest invitation emails enabled in their preferences, but those emails aren't sending. They do get emails for other events, such as quests beginning. There's no record in Mandrill of the emails ever being sent, so it's not a spam trap issue.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

N/A

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitica/blob/026e1a5bca2783c48069751d84f423266a78129b/website/server/controllers/api-v3/quests.js#L80-L85

`auth.google` should be included there.  One report of this bug that I've just seen is from a player who uses Google sign-in exclusively.

**Comment by Alys** [comment]
I'm changing this to help wanted because I think it's likely that's the only thing that's wrong, but we can investigate further if it still happens after that's fixed.
