### ISSUE TITLE
lostMasterclasser achievement not given when earned ("Quest Completionist: Masterclasser Series")

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10398]
Two players (cyberserpent 29492073-15fc-41fd-9c98-b0719f038859 and TriggeredTigger 5e680aae-08ee-4590-9aa7-efc8fc7906f3) from the same party (47957e88-2464-49ca-a3ef-e169d8754e2a) participated in the `lostMasterclasser4` quest but were not given the "Quest Completionist: Masterclasser Series" achievement (`achievements.lostMasterclasser`) even though they had completed all the other quests needed to gain it (I confirmed that from their quest achievement lists). A third participant (3afb41d6-7307-43f0-b0b6-82e8cea0d217) was given `achievements.lostMasterclasser`.

All three participants have the achievement for completing the lostMasterclasser4 quest (`achievements.quests.lostMasterclasser4`). cyberserpent has confirmed that this was the only time cyberserpent had completed that quest. I.e., the [finishQuest method](https://github.com/HabitRPG/habitica/blob/9194e8226d8fbee81f5238c722346acdbb14791e/website/server/models/group.js#L852) must have run to set `achievements.quests.lostMasterclasser4` to true for cyberserpent but the part of that method that sets `achievements.lostMasterclasser` to true did not run or was not successful.

Loggly has no relevant error messages for those three players' User IDs or for the party's ID.

Below are the quest start and end messages for lostMasterclasser4 for that party.

```
{
	"_id" : "029dad34-33a1-4d88-bfdb-d94926178e21",
	"flagCount" : 0,
	"flags" : { },
	"id" : "029dad34-33a1-4d88-bfdb-d94926178e21",
	"text" : "`Your quest, The Mystery of the Masterclassers, Part 4: The Lost Masterclasser, has started.`",
	"timestamp" : ISODate("2018-04-26T14:42:36.721Z"),
	"likes" : { },
	"uuid" : "system",
	"groupId" : "47957e88-2464-49ca-a3ef-e169d8754e2a",
	"_meta" : {
		"participatingMembers" : "29492073-15fc-41fd-9c98-b0719f038859, 3afb41d6-7307-43f0-b0b6-82e8cea0d217, 5e680aae-08ee-4590-9aa7-efc8fc7906f3"
	},
	"__v" : 0
}
```

```
{
	"_id" : "8de58406-9404-4d89-84e2-0dabd0cd0b19",
	"flagCount" : 0,
	"flags" : { },
	"id" : "8de58406-9404-4d89-84e2-0dabd0cd0b19",
	"text" : "`You defeated Anti'zinnya! Questing party members receive the rewards of victory.`",
	"timestamp" : ISODate("2018-05-18T16:01:03.453Z"),
	"likes" : { },
	"uuid" : "system",
	"groupId" : "47957e88-2464-49ca-a3ef-e169d8754e2a",
	"__v" : 0
}
```

I've set `achievements.lostMasterclasser` to true for cyberserpent and TriggeredTigger so the problem is fixed for them now.

**Comment by Alys** [comment]
This might have been a once-off glitch so I'm marking it minor priority. We can increase the priority if it's reported again.

**Comment by Alys** [comment]
@SabreCat says he's noticed others reporting it (https://github.com/HabitRPG/habitica/issues/9461#issuecomment-395220326) so I'm increasing the priority.

**Comment by Alys** [comment]
Still happening, for example:
motobass (89739ec6-8338-4e5e-8df2-e488eca19832): "Hello.  I think I qualify now for the *Quest Completionist: Masterclasser Series* achievement.  I waited a few days and it hasn't appeared yet.  After finishing the last quest, realized I (and another in my party - @gbvr) missed part one of an earlier quest, so we did that. That was maybe three days ago.  Thanks!"

**Comment by Alys** [comment]
If I'm understanding the code correctly, I think this is what's going wrong:

When a quest finishes, the quest rewards and achievement are put into the `updates` variable that starts being defined here:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/group.js#L854-L856

Once all the rewards/achievement are in that variable, `promises` is defined and it contains a database query to execute the `updates`:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/group.js#L889-L895

Then the masterclasses quest achievements are considered here:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/group.js#L897-L929
That code ends with the `lostMasterclasserUpdate` database query being added to `promises`

All the promises are then executed here:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/group.js#L957

But if I understand correctly,`Promise.all(promises)` does not guarantee that the promises are completed in the order that they have been placed into the `promises` array.
Therefore sometimes the `updates` will be executed first (giving the user the new quest achievement) and AFTER that the `lostMasterclasserUpdate` is executed and it works correctly because it identifies that the user now has all of the masterclasser quest achievements.
Other times, the `lostMasterclasserUpdate` will be executed BEFORE `updates`, and so the user's final quest achievement has not been awarded soon enough for the `lostMasterclasserUpdate` to work correctly - this is the situation that causes the bug described in this issue.

Can someone who's more familiar with the Promise module than I am confirm this? Or deny it. :)

**Comment by TheHollidayInn** [comment]
You're correct. Promise.all only guarantees results will be stored in order, not that the promises will complete in order 👍

**Comment by Arsnael** [comment]
I could try taking a look into this :)

**Comment by paglias** [comment]
go ahead @Arsnael, thanks!
