### ISSUE TITLE
do not show "Notification not found" error messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10391]
For a while now it's been common to see "Notification not found" snack notifications (e.g., if you've already visited a guild that has new messages in another browser / app). The notifications now remain until you click on them (a side effect of the fix for https://github.com/HabitRPG/habitica/issues/9249), so they're more intrusive than they used to be.

Those messages aren't of any use to the user since there's no action the user needs to take due to the "error".

The "Notification not found" messages should be prevented from appearing in snack notifications.

**Comment by Alys** [comment]
I'm reopening this because it's still happening and the messages still aren't of any use. It's not uncommon for a notification to be cleared (e.g., if you're also reading chats in an app or third-party tool) and so while it's technically correct that the notification wasn't found by the website, the user doesn't need to know about that and it makes Habitica look buggier than it is.

**Comment by Alys** [comment]
As well as not showing this error to the user, it might be best to not treat it as a fatal error at all since doing so can cause other problems for the player:

_"Extra infos on the "Notification not found" thing: if a notification doesn't clear and I use the "Dismiss all" button, I get the error and the notifications are not dismissed"_ -- Il Mago, junior chemist   @ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b)

Instead, the code could just quietly recognise that a notification has already been dismissed and not halt processing because of it.

**Comment by Alys** [comment]
I'm changing this to suggestion-discussion for a few days to give the staff time to comment on that idea. Contributors should not attempt to implement that until/if it's changed back to help wanted.

**Comment by paglias** [comment]
Distinguishing between different error messages is difficult right now as you can only compare the error message (which changes based on the language). So before any change is made here we should start adding unique error codes like `NOTIFICATION_NOT_FOUND` or a numberic code in this case. Then we can handle them differently based on the error

**Comment by Alys** [comment]
The only places it occurs are here:
```
website/server/controllers/api-v3/notifications.js:40:      throw new NotFound(res.t('messageNotificationNotFound'));
website/server/controllers/api-v3/notifications.js:84:        throw new NotFound(res.t('messageNotificationNotFound'));
website/server/controllers/api-v3/notifications.js:132:      throw new NotFound(res.t('messageNotificationNotFound'));
website/server/controllers/api-v3/notifications.js:182:        throw new NotFound(res.t('messageNotificationNotFound'));
```

Can we just change those four pieces of code?

Another advantage of not treating this as an error would be to decrease our monthly volume of Loggly records (and also make real errors easier to find when investigating a user's bug).

**Comment by paglias** [comment]
The loggly volume isn't rest an issue and you can use isHandledError: false to filter for more important errors in loggly.

As far as the code itself I don't agree with removing the error, it's important to tell API clients if something went wrong and to distinguish between situations when an action was completed correctly and when not. 

It's the responsibility of the client to treat errors differently but without an unique error code it's difficult to distinguish between them so that's why i suggested adding one. It won't take long if someone works on it.

**Comment by paglias** [comment]
I wrote a fix for this, but I'm unable to replicate the error in production, can someone list the steps to replicate it?

**Comment by majestic-owl448** [comment]
Have some notifications, visit a guild or party from the notifications, check again the notifications and if the guild is still there try clicking on it or on "dismiss all". That makes the error appear usually

**Comment by paglias** [comment]
This has been fixed, it should go live next week
