### ISSUE TITLE
Home Page reset to default

### ISSUE THREAD

**Issue by crystaljae** [HabitRPG/habitica#104]
I signed up yesterday. Everything I did yesterday is gone today. I started a new account today and will see if the new account does the same thing as the old account. I see this issue was posted before but was closed 2 days ago. However, for me it is still an issue.

**Comment by hookang** [comment]
@crystaljae We're still working on the kinks in the app. We got a ton of traffic all of a sudden that we weren't ready for. Hold tight and thanks for trying the app.

**Comment by lefnire** [comment]
follow up on #91
