### ISSUE TITLE
link to "Contact the Moderation Team" form has disappeared

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10401]
As reported by Il Mago:

"I can't find anymore the link for the contacing moderation team form! It's not anymore under HELP"

**Comment by Alys** [comment]
It was removed in ba52a90d93edfa023eba0c7c4f68dab76443c3fe

**Comment by paglias** [comment]
this one https://github.com/HabitRPG/habitica/commit/ba52a90d93edfa023eba0c7c4f68dab76443c3fe#diff-1b90a260bd45f389e3f3458765cddc54L58?

**Comment by Alys** [comment]
Yes
