### ISSUE TITLE
Help menu links are inconsistent sizes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10402]
As reported by citrusella, the serving wench:

"... the three links at the bottom of the help dropdown menu are smaller than the rest of the text in the menu (or any other menu)"

**Comment by Andrew-Gaffney** [comment]
I would like to try looking into and tackling this as a first PR.

**Comment by TheHollidayInn** [comment]
Please do!

**Comment by citrusella** [comment]
This might be obvious, but I wanted to add that at least part of the issue is probably that they don't have the topbar-dropdown-item class. (That might be the whole issue, actually. XP)

**Comment by Andrew-Gaffney** [comment]
Hey, that was the whole issue. Going to submit a PR with the changes.
