### ISSUE TITLE
502 server error leaks CSS code to the rest of the site

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10404]
In the Report a Bug guild, RobotKing (7966165f-4b5c-4ad3-b761-e99f3b729400) writes:

"I was getting 502 errors occasionally on the right hand side (usually when they happen, the fonts and general formatting goes wonky, as visible in [screenshot below])."

![scr](https://i.snag.gy/9yHtKA.jpg)

In that screenshot, the chat post that says "Admins have left off here ...." should not be red. It's created by this markdown code:

```
## ----- Admins have left off here for now. If your post hasn't received a response from anyone, please post again briefly to ask us to look back for your message! -----

&nbsp;

This message will be deleted when an administrator next visits the Guild.
```

so the fact that it's red means that it must be picking up some CSS styles from the "502..." error message.

**Comment by Alys** [comment]
BTW, that h2 / red formatting problem might not be the only one caused by this issue. It's just the one that's most obvious to me from that screenshot.

**Comment by citrusella** [comment]
The fonts change slightly, though I don't know to what (that's always the most glaring issue for me), and I've noticed that headers (like display names on messages/in the header) can change size as well.

**Comment by bsoyka** [comment]
Does anyone know where the code is for the 502 error message?  I would like to help out.

**Comment by TheHollidayInn** [comment]
The 502 is a webpage response from our server. My guess is there is an iframe or something similar being displayed in the snackbar. I think we should not fix this issue though because 1. This just flashes. 2. 502 is not something we want to code around. Just something we need to prevent.

**Comment by TheHollidayInn** [comment]
I'm closing this for now. Other admins feel free to ping me if you think this should be fixed, but basically the 502 comes from a separate page and I think we shouldn't worry too much about the css leak.
