### ISSUE TITLE
Login Typo Closes Login Window

### ISSUE THREAD

**Issue by SpartanRedWing** [HabitRPG/habitica#1040]
The "Incorrect user name or password" message appears on my main page, forcing me to re-click "login" before I can try again. Admittingly minor, but can't that message appear on the login window without closing it?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
