### ISSUE TITLE
Remove Member option doesn't appear when clicking View Party from main tasks page

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10414]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When viewing a party's member list from the Party page proper, the party leader has the option to remove party members. This option is not, however, available from the View Party button on the main Tasks page, despite other options like Send Message and Promote to Leader showing up OK there.

**Comment by sanchitbansal10** [comment]
I would like to work on it..Waiting for the approval..thanks

**Comment by Alys** [comment]
@sanchitbansal10  Thanks! Please do! Comment here if you have questions.

**Comment by sanchitbansal10** [comment]
Hi..I have got some other commitments...Wont be able to work on it....Thanks..

**Comment by SabreCat** [comment]
Thanks for letting us know! Opening it back up.

**Comment by titchimoto** [comment]
Oooh, is this still up for grabs? Would like to work on it! :)

**Comment by TheHollidayInn** [comment]
Yep! Please do :D

**Comment by beffymaroo** [comment]
@titchimoto Are you still working on this issue? If so please let us know when you have a moment. Thank you.
