### ISSUE TITLE
Ctrl+Enter and similar hotkeys don't work to send private messages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10413]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Users can press Ctrl+Enter to send chat messages in Guilds, Parties, and the Tavern without use of the mouse, but this shortcut doesn't work in private messages. No reason it shouldn't!

**Comment by Peim8** [comment]
I would like to work on this

**Comment by Alys** [comment]
@PBeier Thank you! Please go ahead. Comment here if you have questions or run into trouble.
