### ISSUE TITLE
Justin box needs more room / better text flow for some languages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10410]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

In some languages, Justin's tutorial text can get partially hidden behind his nametag.

Screenshot: http://joxi.net/Dr8BkOLCkNdgP2

Ideally, the text box should expand a bit if necessary to fit the translated text, rather than cramming it partially out of view. At very least, the bounds of the box should be such that all currently supported languages fit OK.

**Comment by vinmegamitensei** [comment]
Hey, I can give it a try. I just need an 'ok'. Thank you!

**Comment by SabreCat** [comment]
@viniciusperuzza Go for it, with our thanks!

**Comment by beffymaroo** [comment]
@viniciusperuzza Are you still working on this issue? Please let us know when you have a moment. Thank you!

**Comment by vinmegamitensei** [comment]
@beffymaroo I won't be able to continue helping with this one, as I actually had a "promotion" at work and now I'm facing time issues. I'm sorry for this inconvenience, it was totally unexpected.

**Comment by SabreCat** [comment]
Thanks for letting us know, @viniciusperuzza !

**Comment by TheHollidayInn** [comment]
The name tag is now pulled up out of the intro, so this looks fixed to me.
