### ISSUE TITLE
Donation button falls outside of background area in some languages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10411]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

In languages where the term "Donate" runs substantially beyond the letter count of the English term, the button in the Social area of the footer can fly off to the side, beyond the background area. Screenshot: https://www.awesomescreenshot.com/image/3385818/7a06a139a95a50ddfb1132c8a4fe7b04

It should probably expand leftward as needed instead of anchoring to the left and spilling right.

**Comment by Peim8** [comment]
I would like to work on that issue!

**Comment by SabreCat** [comment]
Go for it, @PBeier !
