### ISSUE TITLE
"profile name not found" being used for profile names

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10423]
There are 1091 users who have the profile name "profile name not found". That's a string that we use to indicate that the real profile name has become lost or never set, due to a bug:
https://github.com/HabitRPG/habitica/blob/8fb67e79440aaaf4b5390241aacdc4c9ad727d26/website/server/models/user/hooks.js#L176

This has probably been happening for several days, maybe a few weeks. I've been seeing at least one user with that name for days without thinking about it (assuming that the user had chosen that name themselves - I'd forgotten we'd set up that string as a special label for a bug condition). Il Mago has very kindly pointed out in the Report a Bug guild that they've seen several users with that name and they've suggested it's a bug - I'm sure they're right since there's so many of them.

I suspect it's due to the recent facebook changes. A random sample of three affected users (a8d5890f-bbfb-42bf-97d1-df2271f77392, aaecf74a-2dc7-42e8-8b21-7e24d1888005, bc9eb1fa-9008-4bac-9e0c-50c79bf1a798) show they all use the Facebook authentication method exclusively. It's probably worth creating a test account using Facebook sign-in to see if the profile name starts out not being set, then deleting that test account so that the same test can be performed after related code is changed.

**Comment by Alys** [comment]
I'm marking this as important priority.

Once it's fixed, maybe a Bailey message should include instructions for how to change the profile name since there's so many users who don't know.

**Comment by paglias** [comment]
This might be worth a deploy @SabreCat

**Comment by SabreCat** [comment]
OK, thanks! This will go out with tomorrow's content deploy.
