### ISSUE TITLE
Bug Problem

### ISSUE THREAD

**Issue by Vallent** [HabitRPG/habitica#1042]
When I´d completed a task, i have received a base potion but instead i received 7 or 8 more or less, it´s a bug or it´s normal?

Thanks for read! ^^

**Comment by lefnire** [comment]
duplicate of #901 , let's follow up there. When did this happen last?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
