### ISSUE TITLE
Sort options in Stable should be persistent

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10432]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

As reported in the bug guild:

> 𝕹𝖆𝖊𝕿𝖍𝖊𝕹𝖊𝖗𝖉 (8f89c805-334e-48cf-b095-0eba848f5974) 
>This hasn't ever impacted badly so I've never reported it, but it's getting on my nerves. every time I go to the stable, I select "sort by colour" and every time I come back it's reverted to sorting by pet type. 

Sort options should stick within a session at least, and maybe even across sessions.

**Comment by vinmegamitensei** [comment]
I want to give it a try, may I?

**Comment by SabreCat** [comment]
@viniciusperuzza Sure!

**Comment by vinmegamitensei** [comment]
Just wanted to report that I'm still working on it, it's just that I'm quite new to development and this task is being quite the challenge (also, this and last week were really busy on work).

**Comment by vinmegamitensei** [comment]
I want to report that, as far as I was able to go, I found where the stable options are, but a friend and I couldn't get this to work. I've checked for cookie use or state manipulation, but still, my knowledge is very shallow to solve this issue and everything I tried didn't really worked out. I'm sorry for this inconvenience.

**Comment by TheHollidayInn** [comment]
If you'd like to try localstorage, that will help you solve this problem.

**Comment by TheHollidayInn** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by flhat** [comment]
I think I've got a fix for this.  Will publish a pull request shortly.

**Comment by Alys** [comment]
Thanks @BlkStormy 

Labels updated.

**Comment by Alys** [comment]
A comment from Il Mago in the Bug guild:

"considering issue "Sort options in Stable should be persistent" and that it seems directed inly to tbe stables, users could find confusing that instead other places that let you sort items (market, inventory, equipment pages for example) will not have the same persistency of sorting options once it goes live"

Should we create an issue for the other sorts to be persistent too?

**Comment by paglias** [comment]
I think one single issue that lists all the remaining sorts should be enough!
