### ISSUE TITLE
Error attempting to open profile of deleted user

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10433]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When a user clicks on the avatar of someone whose account has been deleted, nothing happens, with no feedback as to what went wrong. There should be a "Sorry! That user has deleted their account." or similar.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

```
xhr.js:178 GET https://habitica.com/api/v3/members/62b104a4-eaba-4250-a9d7-f8cd55523e96 404 (Not Found)
(anonymous) @ xhr.js:178
M @ es6.promise.js:177
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:57
(anonymous) @ es6.promise.js:75
(anonymous) @ es6.promise.js:89
l @ _microtask.js:18
characterData (async)
n @ _microtask.js:39
(anonymous) @ _microtask.js:66
$ @ es6.promise.js:56
L @ es6.promise.js:162
(anonymous) @ _ctx.js:8
t.exports @ _promise-resolve.js:9
resolve @ es6.promise.js:240
r.request @ Axios.js:40
r.(anonymous function) @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ members.js:30
r @ runtime.js:62
(anonymous) @ runtime.js:296
t.(anonymous function) @ runtime.js:114
r @ runtime.js:62
e @ runtime.js:152
(anonymous) @ runtime.js:195
M @ es6.promise.js:177
r @ runtime.js:194
n @ runtime.js:217
t.(anonymous function) @ runtime.js:114
S.async @ runtime.js:241
r @ members.js:28
value @ index.js:47
(anonymous) @ chatMessages.vue?e01b:204
r @ runtime.js:62
(anonymous) @ runtime.js:296
t.(anonymous function) @ runtime.js:114
r @ runtime.js:62
e @ runtime.js:152
(anonymous) @ runtime.js:195
M @ es6.promise.js:177
r @ runtime.js:194
n @ runtime.js:217
t.(anonymous function) @ runtime.js:114
S.async @ runtime.js:241
showMemberModal @ chatMessages.vue?e01b:129
e @ vue.runtime.esm.js:2023
t.$emit @ vue.runtime.esm.js:2534
showMemberModal @ chatCard.vue?8d1c:267
click @ chatCard.vue?446a:1
e @ vue.runtime.esm.js:2023
t._withTask.t._withTask @ vue.runtime.esm.js:1822
es6.promise.js:110 Unhandled promise rejection TypeError: Cannot read property 'data' of undefined
    at s.<anonymous> (chatMessages.vue?e01b:205)
    at r (runtime.js:62)
    at Generator._invoke (runtime.js:296)
    at Generator.t.(anonymous function) [as next] (https://habitica.com/static/js/vendor.d27c35f55e47c473e365.js:6:232039)
    at r (runtime.js:62)
    at e (runtime.js:152)
    at runtime.js:162
    at es6.promise.js:75
    at es6.promise.js:89
    at MutationObserver.l (_microtask.js:18)
```

**Comment by ulugbekna** [comment]
When a user deletes his/her account, the user document is completely deleted from the user collection. 
Hence, we cannot know if the user deleted the account or it never existed - API simply returns response status 404. 

In order to resolve this issue, I think we could: 
1. Bring up a modal with the text “Sorry, User deleted account…” every time the “api/v3/members/memberId” request returns 404 in chat messages view. 
2. Create a collection of deleted users with their ids. More work here - as we need to create a new model, edit the api controllers, etc. 

These ideas are what I have so far. What do you think?

**Comment by TheHollidayInn** [comment]
I think the first idea is good!

**Comment by TheHollidayInn** [comment]
@ulugbekna did you still want to fix this issue?

**Comment by thefifthisa** [comment]
Hi! I'd like to work on this if it's not yet taken.

**Comment by TheHollidayInn** [comment]
I believe this is free now, so go for it. The fix we are wanting is something similar to this: `Bring up a modal with the text “Sorry, User deleted account…” every time the “api/v3/members/memberId” request returns 404 in chat messages view.`
