### ISSUE TITLE
Unnecessary whitespace to the right of landing page

### ISSUE THREAD

**Issue by jrobind** [HabitRPG/habitica#10435]
### General Info
  * UUID: 7187b35d-3ae8-4b5c-8578-be7f582ff437
  * Browser: Chrome, Firefox, Internet Explorer
  * OS: Windows

### Description
I have noticed some unnecessary whitespace to the right of the landing page which causes a horizontal scroll to permanently appear at the bottom of the viewport. 

![screenshot 2018-06-06 11 59 45](https://user-images.githubusercontent.com/30320536/41035870-00f474d0-6986-11e8-8f01-bcad34766e59.jpg)

Additionally, the navbar at ~650px causes an even larger overflow:

![screenshot 2018-06-06 12 16 22](https://user-images.githubusercontent.com/30320536/41035978-5a6e2524-6986-11e8-8218-c3fa9185f63d.jpg)

I'm assuming this navbar overflow has something to do with the bootstrap sm grid breakpoint which does not take effect until 576px.

**Comment by jrobind** [comment]
I don't mind taking a look at this myself but thought I would see what you guys think first!

**Comment by beffymaroo** [comment]
@jrobind Sorry for the delay! If you'd like to take a look at this issue we'd be very grateful for the help. :)
