### ISSUE TITLE
Bailey issue

### ISSUE THREAD

**Issue by LordTovel** [HabitRPG/habitica#1043]
If reading what the NPC Bailey has to say, will often randomly close her pop-up window.

**Comment by lefnire** [comment]
Due to page re-render when model updates things. This should hopefully get fixed in the Derby 0.5 migration

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
