### ISSUE TITLE
Inn banner and nav bar behave oddly when scrolling

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10437]
Reported in Report a Bug by Il Mago:

> The "You are currently checked into the Inn" blue bar at the top disappear and reappear scrolling up and down near the top of the page: [here a video showing that behaviour](https://drive.google.com/file/d/1erOcBiQFoaJrUfYbH48zTj7yp0OPBMlC/view)

Confirmed by me on Google Chrome.

**Comment by vinmegamitensei** [comment]
I would like to give it a shot. I already did some testing here and found what might be the problem, but I want to ask for your guys permission to continue. May I?

**Comment by TheHollidayInn** [comment]
Please do! Thanks
