### ISSUE TITLE
"add multiple" tip interferes with editing a new task

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10440]
As reported by Ensorceled (4428e727-2a0e-4072-b578-fc28029b33f3):

"Is there anyway to make the [tip] for adding tasks go away once I've added a task? Or just make it go away altogether? It's very annoying that, when trying to edit an added task, I must first click to close the [tip] and then click to edit the task. ...  Here's what I mean:"

![scr]( https://i.imgur.com/cvR811J.png)

I.e., when you add a task, if you want to edit it immediately (a common desire), then you have to click twice on the task to make it open in the edit window because all that the first click does is make the tip disappear. You can work around that by rapidly double-clicking the new task but that's not intuitive.

**Comment by thefifthisa** [comment]
Hey @Alys! Can I work on this?

**Comment by thefifthisa** [comment]
Hey @Alys! Can I work on this?

**Comment by paglias** [comment]
Go ahead @thefifthisa !
