### ISSUE TITLE
timestamp needed in moderator Slack messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10441]
_I'm marking this "good first issue" but it might be a little harder than those often are. If you start this and find you need help with it, post here._

When a chat message is flagged, moderators receive a notification in a Slack channel as shown in the screenshot below. If you use `git grep flagSlack` you'll find the code responsible for it.

We'd like the date and time of the message to be included. That data is stored in the message's `timestamp` field like this:
```
{
	"_id" : "34df5f7f-205b-4797-ae7d-443777bae1ec",
	"flagCount" : 5,
	"flags" : {
		"d904bd62-da08-416b-a816-ba797c9ee265" : true
	},
	"id" : "34df5f7f-205b-4797-ae7d-443777bae1ec",
	"text" : "Test post for flagging.",
	"timestamp" : ISODate("2018-06-09T23:56:26.367Z"),
	"likes" : { },
	"uuid" : "3e595299-3d8a-4a10-bfe0-88f555e4aa0c",
	"user" : "ALittleYellowSpider",
	"groupId" : "85dd1be6-336b-4e53-9949-2c09150b4035",
	"userStyles" : { ... },
	"__v" : 0
}
```

The format in the message moderators see in Slack should be `yyyy-mm-dd HH:MM UTC`. For example, the timestamp for the message above would be reported as `2018-06-09 23:56 UTC`. We don't want the second or milliseconds to show - that would just be cluttery. :) moment().format() is the best way to format a date. You can see examples of it in our code with `git grep 'moment(' | grep 'format('`

The timestamp in the message is already in UTC and there's no need to try to convert it to any other time zone, so we just need the "UTC" label added as a reminder to mods that it's UTC not their own time zone.

The timestamp should appear in the Slack message on a line by itself directly above the guild's name, like this:
```
ALittleYellowSpider - alice.harris@oldgods.net - 3e595299-3d8a-4a10-bfe0-88f555e4aa0c
2018-06-09 23:56 UTC
Flag in Chaos Guild - (private guild)
Test post for flagging.
Flag this message
```

It should be in the same grey text as the user's name, email address, and User ID.

_When a message is flagged, other things happen too (e.g., an email is sent to various email addresses), but those other actions do NOT need to be changed._

**Comment by thefifthisa** [comment]
Hi @Alys, I'm new here and would love to try working on this!

**Comment by Alys** [comment]
@thefifthisa Thank you! Go ahead.

**Comment by thefifthisa** [comment]
Update: I think I got it. Is there any way to see what this looks like on Slack?

**Comment by Alys** [comment]
I don't think there is before the code is merged. However if you make a PR and it's merged, then moderators will be able to see the effects in Slack by using a private staging server (which uses the `develop` code). Merged pull requests sit in staging for a few days before they're deployed to production so if there's any urgent problems, there'd be time for them to be fixed before the habitica.com site was affected. So even though this can't be fully tested before merging, it'll be pretty safe. If you'd like to make a PR, please go ahead!
