### ISSUE TITLE
Tasks cannot be sorted by all/due/not due in group plan overview

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10444]
Reported in Report a Bug, confirmed by me. Trying to filter by due or not due doesn't change anything in the group plan task board.

![image](https://user-images.githubusercontent.com/8144640/41298063-7b23d62a-6e58-11e8-927a-f5c3d1c1edda.png)

![image](https://user-images.githubusercontent.com/8144640/41298150-a6acc036-6e58-11e8-9436-313afde069e8.png)

**Comment by thefifthisa** [comment]
Hi! Can I take this?

**Comment by TheHollidayInn** [comment]
Please do!

**Comment by thefifthisa** [comment]
Oh just realized, how do I get past the payment method so I can simulate a group plan?

**Comment by paglias** [comment]
@thefifthisa for stripe you should be able to use these https://stripe.com/docs/testing#cards cards

**Comment by thefifthisa** [comment]
Stuck with this error though 😕

![stripe](https://user-images.githubusercontent.com/30595954/43529410-37fe4202-9579-11e8-8f3a-d30dd224ec77.PNG)

**Comment by paglias** [comment]
Hmm I guess you have to setup a stripe account and use the tests keys from it... Not sure how viable that is, but if you live in a country supported by stripe it should be pretty straightforward.

The other option is to edit the local db directly to give yourself a group plan

**Comment by Alys** [comment]
@thefifthisa If you haven't already found it, see the [Creating Test Data](https://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API#Creating_Test_Data) section in "Using Your Local Install to Modify Habitica's Website and API" for advice about the local database modification required.

**Comment by thefifthisa** [comment]
Thanks @Alys!

I may have run into a problem though, because I can't check off any tasks in the group board (unless the task is assigned to me, then I see them on my own board). Is this proper behavior? Also, what does it mean when a group task has no shared completion and "does not complete"? (Sorry, I've never worked with the group plan before 😓)

**Comment by TheHollidayInn** [comment]
@thefifthisa this is correct. You don't complete tasks directly on the group board. The assigned user(s) complete them. You shouldn't need to complete for this task. Basically you should only filter dailies based on if they are due are not with respect to the `isDue` field. 

`does not complete` is the default behavior for tasks. Basically it allows for tasks to never complete and be recurring. For example, habits and dailies to complete in the same way a task completes. If this is confusing, I agree, it is something Sabe and I are currently working through :P

**Comment by thefifthisa** [comment]
Thanks @TheHollidayInn! Just opened a PR where the `isDue` filter works, but only on refresh for now.

I also noticed that the filter functions are different for users and groups. Is there a way to use the same one for both?
