### ISSUE TITLE
Immediate edit of newly created group throws Not Found error

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10448]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you create a group, then without further sync or reload attempt to edit that group, add Challenges, etc., you may get an error as if the group didn't exist:

![Challenge edit screen with "group not found" error](https://i.imgur.com/M8djCSj.jpg)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

TBD

**Comment by arunikayadav42** [comment]
@SabreCat can I get started with this issue :)

**Comment by SabreCat** [comment]
@arunikayadav42 You're welcome to it!

**Comment by arunikayadav42** [comment]
as an initial step can I please know how can I get started...I am newbie to open source :)

**Comment by SabreCat** [comment]
[This Wiki article on setting up a local instance](https://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) is probably your best starting point! You can also visit the Aspiring Blacksmiths Guild within Habitica to ask questions.

**Comment by arunikayadav42** [comment]
sure :)

**Comment by arunikayadav42** [comment]
I am having problem in running npm install.Can somebody please help me?

**Comment by Alys** [comment]
@arunikayadav42 Yes, we can help, but we'll need specific details about the problem. The best way to proceed is probably to see the "Prepare for Troubleshooting" section in the "Setting up Habitica Locally ..." wiki page for your operating system - that will tell you the sort of information to provide.

**Comment by beffymaroo** [comment]
@arunikayadav42 Are you still working on this issue or have you been able to set up your local install? Please check in when you have a moment.

**Comment by TheHollidayInn** [comment]
This seems to be fixed.
