### ISSUE TITLE
Streak bonus for habits

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#1044]
I just received a streak bonus for a habit - not a daily. It's also not something I've done recently. IIRC, I got about 5 of the small coins for it. I think this is the second time this is happened, and that the first time was earlier today, i.e. both were after the move to habitrpg-shared. (Not sure of that memory though.) I'm on the normal server, not any kind of test server.

[Edit: it just happened again; this time I got 12 coins of "streak bonus", for a habit I believe hadn't been done in even longer. On the other hand, no streak bonus for a habit I usually manage to do several times a day.]

**Comment by lefnire** [comment]
Note from another user

> I've just noticed a bug with the streak bonus.
> 
> If I tick off a Daily that I did yesterday, I get a streak bonus, as expected. If I then tick off a Todo, I also get a streak bonus! Which is nice but probably not what should happen. ;)
> 
> If I immediately click undo, and then tick off the same Todo again, I do NOT get a streak bonus.
> 
> If I tick off a Daily that I did NOT do yesterday, I get no streak bonus (as expected) and if I then tick off a Daily, I also get no streak bonus (also as expected).
> 
> The bug seems to be that if you tick off a Todo immediately after getting a streak bonus for a Daily, then you also get a streak bonus for that Todo.

**Comment by storian** [comment]
What I am seeing is that when I click a daily for which I should get a streak bonus, I get no bonus.  But then if I click a to-do or habit next, I get a streak bonus for that, which seems to be the correct amount for what I should have gotten for the previously clicked daily.  So, it appears the streak bonus is being delayed until the next-clicked-item.  I am still not 100% positive this is what I'm seeing but I am pretty sure (between my sporadic use and forgetfulness and the server being unavailable I haven't yet run a delibrate experiment yet).

**Comment by storian** [comment]
I ran a test: for an Easy Daily with a 23 streak, I clicked it and received no streak bonus, but the streak iterator did increase (to 24).  Then I clicked on a To-do, and received a 13 streak bonus.  I'm not actually sure if 13 is what one should get for an easy task at 23, the streak bonus levels appear to be based on task difficulty.

**Comment by lefnire** [comment]
Is this still happening for people? I can't replicate, and I pushed a
possible fix a little bit ago

**Comment by storian** [comment]
I am now seeing behavior where I see the streak bonus notification, but the streak bonus is not going into my gold/silver, just the usual task reward.  That's wrong, right?  Should I open a new bug for this?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
