### ISSUE TITLE
Can click and drag tasks within a Challenge to sort them, but it throws Not Found error

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10464]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When editing a Challenge, you can click and drag tasks to reorder them, but it doesn't actually work. A "Task not found." growl error appears, and on refresh the task order is back the way it was.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
(Staging version. Should be similar on production but with v3 API, methinks)

```
/api/v4/tasks/3dd4106e-fc5e-4401-b623-999afaf24196/move/to/0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.h.(anonymous function) (https://habitrpg-staging.herokuapp.com/static/js/vendor.bde64387d6877154167c.js:6:129075)
```

**Comment by paglias** [comment]
The corret behavior here is to prevent the reordering or it should work for challenges as well?

**Comment by SabreCat** [comment]
I think you should be able to reorder them, setting up the sequence that users will see when they look at the Challenge / what order the tasks will default to when the user joins the Challenge.

**Comment by paglias** [comment]
Okay, I checked the code and looks like it's not supported. It's supported for user and groups tasks but not for challenges. I can fix the error by disabling moving tasks in challenges but supporting it is IMHO a new feature and would require some time to implement

**Comment by Alys** [comment]
Sort order in Challenge tasks used to work, including in the user's copies when they joined. We've been treating it as a bug that it no longer works. There's an issue for it IIRC (on mobile so I can't search easily).

**Comment by paglias** [comment]
Ah, I couldn't find the code, there's one for groups and users tasks but nothing for challenges but I'll give a look if you can point me to the issue with more info when you have time

**Comment by Alys** [comment]
@paglias We have this issue for the Challenge owner being able to sort tasks in the Challenge's page: https://github.com/HabitRPG/habitica/issues/1703 ("challenge items don't retain sort when creating or editing a challenge").
It has a small amount of useful tech detail in it (in the last few comments), so this new issue might be redundant.

We also have https://github.com/HabitRPG/habitica/issues/7599 ("challenge tasks are in wrong order after joining") for making the Challenge's tasks appear in the same order in the user's own list when they join the Challenge.

Those two issues can be fixed independently - each one has value by itself even when the other isn't fixed.

**Comment by paglias** [comment]
Is this one needed then? It seems the same as #1703, the only difference is the error but it's the same bug.

I'll close this one
