### ISSUE TITLE
The static main page shows features we do not have

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10462]
Reported by Il Mago:

> On the website main static page (https://Habitica.com/static/home) there are some examples of dailies and habits with written "Done 1 day ago", "Done 2 days ago", "Done 15 minutes ago". It is confusing for new players when they find out that the feature is not actually implemented

**Comment by beffymaroo** [comment]
@Tressley I've added a "Needs Design" label here - let me know if that's not the case. Thanks!

**Comment by LaurenceJJones** [comment]
I can edit the image and remove the done tags if you like

**Comment by Tressley** [comment]
@beffymaroo -- This is definitely on me. I'll get the image corrected and into Zeplin. 👍 
@HUGODOS -- This is a quick one for me, but I appreciate you offering to help. 😃

**Comment by Tressley** [comment]
Done. Just need to update the landing page with the SVG located here: https://zpl.io/bo4NWg2

**Comment by vinmegamitensei** [comment]
I might be able to help, but I need an invitation to the Zeplin project, if possible.
My e-mail is: vinicius@pomodorify.me

**Comment by Tressley** [comment]
Sorry for the delay. I went ahead and fired off a Zeplin invite @viniciusperuzza. You can view the art board here: https://zpl.io/awYokyM

**Comment by vinmegamitensei** [comment]
Thank you kindly. I'll start to work on it right away!
