### ISSUE TITLE
Error message during sign-up for too long/too short usernames is uninformative

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10460]
Error message during sign-up is uninformative -- instead of showing that the length of the username is insufficient/too long, it just says "Invalid request parameters."

![image](https://user-images.githubusercontent.com/8144640/41653232-b8848c52-7485-11e8-9a31-7b8837566c7a.png)

**Comment by thefifthisa** [comment]
I'd like to take this!

**Comment by Alys** [comment]
@thefifthisa Thanks! Please go ahead!

**Comment by LaurenceJJones** [comment]
Can I also comment that I was going to open an issue since I could sign up but I didnt realise that spaces are not allowed within the username it isnt clearly stated within the text at the top just thought i'll add this
