### ISSUE TITLE
Scrolling issues with Bailey announcements

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10461]
A variety of reports from Report a Bug:

_Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72): "Not exactly a bug report...

So I finally updated to Windows 8.1 and this is the first time entering Habitica on it. The browser is Chrome 67.0.3396.87 64bit. And I had the issue where I couldn't scroll "New stuff by Bailey". There was only one scrollbar (before I updated, there were two when pop-ups appeared) and it scrolled the background page, and the mouse wheel did too. Besides, with the resolution 1920x1080 and middle-sized font, the "Dismiss" button was well beyond reach. I took a screenshot and was thinking on how to reach that guild, when I noticed ABP icon active (which meant I hadn't whitelisted Habitica in AdBlock Plus yet). I set it to be off on this site, which made me reload the page to apply the action, which, when the site loaded again, resulted in the news being scrollable. Still one scrollbar, so I figure it's the regular way it looks.

I don't know whether turning off AdBlock or reloading was what fixed the issue. It might have occured due to the site not being loaded fully, or something."_ 

_Patrick Mulcahy (a3199984-c1f7-4eb3-b008-88413a518aba): "I just ran into the scrolling issue for the dialog on chrome. After a few refreshes it started scrolling correctly again. I've been using the site for about a month and this is the first time its happened to me. Windows 10 / Chrome v67 / 1920x1080"_ 

_TheXNT (0f3fe803-65c6-4143-a0af-5981ffe43b8b): "@shanaqui I thought the same think so I tried disabling the ad blocker, in a chrome incognito and even in a vanilla (as in no extensions installed) firefox and it is the same in all three."_  

_ravenct (424fddad-986a-458b-8347-994ec39a3146): "@Qazzian @shanaqui - I had this same issue in Firefox. It seems to be a lack of compatibility with the browser. The scroll scolls the page behind and not the popup. the popup remains static. I switched to Chrome. The site redesign is not very robust in my experience on Android, Chrome and Firefox."_

**Comment by shanaqui** [comment]
Here's a screenshot from another user: https://ibb.co/hFH9Zd

**Comment by SabreCat** [comment]
Detail from Report a Bug:

**Qazzian** (d427e35a-b93d-411a-9c99-f9a260983436): 

>Re dialog scrolling bug. This was the first time I've had the issue. I'm on chrome. I had a play around in the developer tools. The modal window has 'overflow:hidden' set on it.  I disabled that rule and I was able to scroll the modal correctly and access the buttons.

**Comment by paglias** [comment]
This should help when it's deployed https://github.com/HabitRPG/habitica/commit/fb95d001abbc2090c78db97e06ccc60e3b5adfa7
