### ISSUE TITLE
leader changed in guild with an active group plan

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10474]
oakfernmama (0917fecb-cce2-4204-94be-c03f0a53f07c) reported: "I just signed up for the Group feature... somehow without my OK, the system changed my son to the group leader. I can't assign him tasks, nor can I change the group leader. Is there a way to fix this - and prevent the behavior in the future?"

I confirmed that they did pay for the group subscription (this is from our records in Slack):
```
oakfernmama 0917fecb-cce2-4204-94be-c03f0a53f07c xxx@xxx.xxx bought a 1-month recurring group-plan for 6ee57108-c276-478c-865d-0eacde01146d using [payment method] on Sat Jun 23 2018 21:03:58 GMT+0000 (UTC)
oakfernmama 0917fecb-cce2-4204-94be-c03f0a53f07c xxx@xxx.xxx bought a 0-month recurring subscription using Group Plan on Sat Jun 23 2018 21:03:58 GMT+0000 (UTC)
[other guild member] 0971bf46-ae4a-4fa2-890d-06f9e03d5d36 yyy@yyy.yyy bought a 0-month recurring subscription using Group Plan on Sat Jun 23 2018 21:05:36 GMT+0000 (UTC)
```

Here's the current guild data (irrelevant parts removed):
```
{
    "_id": "6ee57108-c276-478c-865d-0eacde01146d",
    "purchased": {
        "plan": {
            "consecutive": { },
            "quantity": 3,
            "extraMonths": 0,
            "gemsBought": 0,
            "mysteryItems": [],
            "customerId": ".........",
            "dateCreated": "2018-06-23T21:03:57.760Z",
            "dateTerminated": null,
            "dateUpdated": "2018-06-23T21:03:57.760Z",
            "owner": "0917fecb-cce2-4204-94be-c03f0a53f07c",
            "paymentMethod": ".......",
            "planId": "group_monthly"
        }
    },
    "memberCount": 3,
    "balance": 0,
    "type": "guild",
    "name": "...",
    "managers": {},
    "categories": [],
    "leader": "0971bf46-ae4a-4fa2-890d-06f9e03d5d36",
}
```

It's not supposed to be possible for a guild leader to be changed in any way (or for the guild leader to leave the guild) while the guild  has an active group plan.

Note that `memberCount` is 3 but it should be 2 (I've checked and there's only 2 members) so that's likely related.

I've asked oakfernmama for more information such as whether any error messages were seen or any guild leave/join events occurred. (Based on the timestamps in Slack, we already know that the son was invited to the guild after the group plan was created.) 

I can't find anything obviously relevant in Amplitude or Loggly. It wouldn't hurt for someone else to check in case I missed something.

I'm marking this as important priority, at least until we know what caused it and whether it's likely to happen again for this or other groups.

I'm about to change the guild leader back to oakfernmama.

**Comment by Alys** [comment]
Some useful details from oakfernmama:
**"I was signed in to both mine and my son's accounts to complete the invite & get added to the group. The invitation came through on my son's side, but I couldn't access our group. I logged out and logged back in, which caused the group to show up in the nav menu - but when I went back to my account and tried to assign him a task, I got the "Not authorized to manage tasks!" message. My gut tells me it has something to do with my son having a new login before me in the group... hope the extra details are helpful!"**

**Comment by TheHollidayInn** [comment]
From looking at Azure and Amplitude, it looks like (time is in UTC):
1. Group created at 9:03pm 
2. Son accepted invite around 9:05pm
3. Task was created at 9:14pm
4. Group was updated around 9:15pm (probably where the error happened)
5. Owner when to Bug guild to report at 9:17pm

There are other events. 

I am guess there might be an issue in the PUT request for groups as well. 

Can we ask the user what they were trying to update on the group? That might help. Also, can we give them some gems or free time for being so helpful? :D

**Comment by Alys** [comment]
Another example of this today for group ID 9d7fe60d-008e-44f2-9dcf-0d1893592f3e
The guild was created by one user and then about three minutes later a second user was added. That second user then became the guild leader, even though the `purchased` details and our Slack records clearly show the other user was the person who made the payment. The `memberCount` was also 3 instead of 2. The `quantity` and payment were correct (4 and $12). 
I've fixed the leader and the memberCount.

This therefore needs to remain as a high priority. Having the guild leader being someone other than the person who pays the bills is dangerous.

**Comment by Alys** [comment]
@TheHollidayInn 

> Can we ask the user what they were trying to update on the group? 

Yes, good idea! The best way to reach them is probably by PM since I'm not sure if they'll check back to the Report a Bug guild again (you can enter their User ID into the Hall and then click on their name to get to their profile). I like the idea of rewarding them - they were very pleasant to deal with. :)

**Comment by Alys** [comment]
Another report for guild e29315e8-2e25-4916-9ffc-44e60295d897 created about 10 hours ago (emphasis is mine):

"I tried to sign up for a group on my laptop using Chrome on windows 10. I had already added one member to my group. **When I added the second member to the group after paying for it, it made them the group leader. And it no longer showed the member that was there previously in the group list. However, it showed as there being three members on the top page.**  We had to cancel the subscription to be able to make me the group leader again. I added the first member again and now it shows all three of us in the group, however now it say there are four members but only shows us three in the list."

I've fixed the guild's memberCount (changed from 4 to 3). The `quantity` is currently set to 4, but it should be 5. I haven't changed that since they've cancelled the group plan.

**Comment by Alys** [comment]
I've fixed the guild's memberCount (changed from 4 to 3). The `quantity` is currently set to 4, but it should be 5. I haven't changed that since they've cancelled the group plan.

**Comment by Alys** [comment]
I've searched all current group plans. This bug also happened to groups a674acdb-13e7-4df4-8ad9-0756380aff1a and adb4a28f-86b8-4865-aaff-6f2c8c8d29e0, created on Jun 22 2018 12:46:46 and Jun 23 2018 15:45:11. I've fixed the leaders and memberCounts. The `quantity` values are probably still wrong.

**Comment by Alys** [comment]
I am guessing this code in `api.joinGroup` would be causing this bug if some other code is preventing memberCount from being correct:

https://github.com/HabitRPG/habitica/blob/e5d834b40aa4407ab8603dc911e94e052d15174a/website/server/controllers/api-v3/groups.js#L591


This memberCount code is relatively new:
```
diff --git a/website/server/controllers/api-v3/groups.js b/website/server/controllers/api-v3/groups.js
index 7e88d487b..b5f4ab5d8 100644
--- a/website/server/controllers/api-v3/groups.js
+++ b/website/server/controllers/api-v3/groups.js
@@ -196,6 +196,7 @@ api.createGroupPlan = {
 
     // @TODO: Change message
     if (group.privacy !== 'private') throw new NotAuthorized(res.t('partyMustbePrivate'));
+    group.memberCount = await User.count({ $or: [{ 'party._id': group._id }, { guilds: group._id }] }).exec();
     group.leader = user._id;
     user.guilds.push(group._id);
```
It looks like memberCount is being calculated before the new guild is added to the user's `guilds` array, so that would result in the count being zero.

**Comment by TheHollidayInn** [comment]
Nice find! I remember seeing that before, but I couldn't remember. I think we should add a line there checking if it is a group plan then!

**Comment by Alys** [comment]
That's certainly a workaround for now but it's worth noting that a private guild or party (with or without a group plan) can't ever be in the situation where there are no members because the guild/party is automatically removed as soon as the final member leaves. The root of the problem here is that the memberCount must be wrong when it says 0 when a player joins a private guild. The code that assigns a new leader when memberCount is 0 was intended for the case when a player joins a public guild that's been abandoned by all former members and the original leader.

Adjusting that recent change to the memberCount code might fix the problem and also related problems such as the memberCount still being wrong after a second member has been added to the guild.

**Comment by TheHollidayInn** [comment]
Oh I see. I misread the code above, sorry. Let me adjust that as well.
