### ISSUE TITLE
Habit history problem

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#1047]
There is a big problem with habits' history. "+" only habits have been having this for a lot of time and soon "+/-" habits are having a different problem. Yesterday I checked on a "+/-" habit it gave exp, gold etc. but didn't show the date in history. I'm positive this is a bug, I checked on other habits too, its the same. So i checked the habit today and it didn't show me 26.05 until I refreshed the page. You can see what I'm talking about here http://i.imgur.com/XFiQf1g.jpg
The "+" only habits have a messed up graph, all of them.

**Comment by nikrage** [comment]
All habits are having problems with their history

**Comment by lefnire** [comment]
fixed some graphing stuff recently, this still an issue?

**Comment by nikrage** [comment]
http://i.imgur.com/7ellNis.png?1

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by paglias** [comment]
Graphs are still to be ported
