### ISSUE TITLE
Mongoose NoSQL injection

### ISSUE THREAD

**Issue by dacappo** [HabitRPG/habitica#10478]
### Description
I found a NoSQL injection that allows me to unsubscribe specific or even all users from notifications through a bypass for the implemented unsubscribe-code encryption. Is there any contact for responsible disclosure?

**Comment by paglias** [comment]
Hi @dacappo ,

you can contact admin@habitica.com, thanks

**Comment by paglias** [comment]
I'm going to close this issue, feel free to comment again if there's any problem with the report
