### ISSUE TITLE
Guild / Party Invite members button does not work for some players

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10509]
Some players are reporting that the button to invite new members to a guild does not work for them.

I've seen several reports of this now so it's either a bug that affects only some OSes / user accounts or is an intermittent bug that's not platform-dependent or user-dependent. It does not occur for me. Some players report it happening in multiple browsers.

It seems to affect more than one guild for each player.

Here's one example and I'll post others soon:

----

Manifold (4bd2e5b3-7e24-43a8-9087-ced67ef6c9cb): "For the last week or so the invite button in any Guild I visit does not work when clicked. The button just shows the click animation but the pop over does not show allowing me to invite another member. I have tried Firefox and Chrome as well as Chrome Incognito to eliminate any extensions. Please let me know if you require further information."
 
Alys: "Please open the Developer Console or JavaScript Console in your browser (instructions here then if you can see the trash can icon in the Console, click that (it's probably at the top left of console but don't worry about this step if you don't see it). Then click on the invite button again. If anything appears in the Console, please paste it here. Don't worry about neat formatting for it."

Manifold: "Thanks for your reply. Nothing appears in the console when I click on the Invite button."

Alys: "I'm sorry we haven't got back to you before now. Please visit any guild you're a member of (this one will do if you've joined it), then after the guild page has fully loaded, reload the website using your brwoser's refresh button. Wait for it to fully load again, then click the invite button. Does that help? If it doesn't, please go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there, then reload the website using your browser's refresh button while you are holding down the "Control" or "Command" key on your keyboard. Log in again, navigate back to any guild you're a member of, and try to invite again."

Manifold: "Thanks for getting back to me! :) I tried everything you suggested but the Invite dialog is still not opening. **I can use the API to invite members still.** Please let me know if I can provide you with any logs or other information to help debug this issue."

_I've asked them what OS they're running._

----

**Comment by Alys** [comment]
Another report:

Chandra Ryder (ae890b60-0031-41cf-aa95-f98d45c9a2e1): I created a private guild last night for a specific group of people. When I click the "invite" button, nothing happens. I've tried this in both Chrome, and Mozilla with adblocking completely turned off. I've refreshed several times over a twelve hour period and nothing has changed.

shanaqui: Hm, I can't replicate this -- can you go through exactly the steps you're using that don't work? Is it literally just clicking on the "Invite" button in the guild and there's nothing, not even an error message?

Chandra Ryder: that's correct, I just click on the "invite" button and nothing happens. When I click on "edit" I get a pop-up screen with options. When I click on "invite" it acts like a dead like which doesn't work.

shanaqui: I can't replicate this at all, so I'm pretty sure it's something on your system, but I'm a bit stumped as to how to figure out what since you've tried two browsers! @Sabrecat, any ideas?

Chandra Ryder: I just updated both my browsers, and tried both browsers on my newer Mac desktop as opposed to the older PC laptop I was using before. No dice, I still just get a clickable link that doesn't do anything. But, new information, I also tried to invite someone to the other wordsmiths guild I'm a part of and the same thing happens. I'm a level four Warrior, is there a level requirement before you can invite people to join guilds?

SabreCat: That's really troublesome, sorry about that! Can you open the JavaScript console for your browser and try clicking one of the Invite buttons, then report any RED error messages you see in it here? That should help us track this down!
 
Chandra: None of these are red error messages, but I did get these yellow warning messages. _[just the "moment().zone is deprecated" messages]_

SabreCat: All right, those were unrelated (but thanks for going to the effort of pasting them over, we appreciate it!)... what's the Guild you're trying to invite folks to? Can you drop a link to it here?
 
Chandra Ryder: I'm a member of three guilds; this one, "The Wordsmiths", and the private one I created. I can't invite anyone in any of them.

Alys: Can you please tell us the link to the private guild? To get that, visit the guild in your browser and copy everything that's in your browser's address bar. Also please try disabling ALL browser extensions and custom styles/themes, even if they don't seem to be related, then reload the website and click the invite link again - does that make a difference?

Chandra Ryder: Here's the link. https://habitica.com/groups/guild/f24ad0e8-5da3-4109-9dd3-41da15e0ad50 I just tried in Chrome with nothing added, I also did this with Firefox when I upgraded it to the newest version this past week. Neither worked.

**Comment by Alys** [comment]
Note that that one ^^ has been happening on different computers as well as different browsers so it can't be a platform-dependent bug.

**Comment by Alys** [comment]
Two more reports, with no responses to our requests for more information:

----

Nicole Oré Kovacs (7c68c01f-5ac1-4f7d-9c1d-3d54739b4a1c): Hello! I'm returning to Habitica since absence of 5 months. I see I have been kicked out of my former party (which I understand) but there is an old invitation to a quest in the notification Icon which I cannot accept nor decline. I also created a new party for my team at work, and I cannot invite any of my friends, since none of the "invite" icons of the party work. What can I do?

----

drpachief3 (f044bb67-7f59-4565-91d5-38269889ebd5): The invite button doesn't always respond in my guild. Anyone else having this problem?

_That one was in the Tavern and I've asked them to post to the Bug guild with more details._

**Comment by Alys** [comment]
This is still happening on my local install which is up to date with `develop` - the most recent commit there is eb99b709e0d04dd5d57c11121189a22a1b0f433f (I'm not saying that commit is in any way related to this issue, I'm just referencing it since it's the most recent one and therefore does have the previous fix in it).

I'm not really sure what's going on in the vue code but I believe these are the relevant bits of code:

https://github.com/HabitRPG/habitica/blob/eb99b709e0d04dd5d57c11121189a22a1b0f433f/website/client/components/groups/group.vue#L447-L449

https://github.com/HabitRPG/habitica/blob/eb99b709e0d04dd5d57c11121189a22a1b0f433f/website/client/components/header/index.vue#L128-L133

https://github.com/HabitRPG/habitica/blob/eb99b709e0d04dd5d57c11121189a22a1b0f433f/website/client/components/header/index.vue#L191-L201

As you can see there, `inviteModalGroup` is `undefined` until the created() function runs but that function's code only executes if the user is in a party.

To test if that was likely to be responsible for the bug, I put my test user into a party and the invite button on a **guild** then worked. I took my test user back out of the party and the invite button on the guild stopped working. If you're trying to reproduce this, reload in between joining/leaving the party. I did that test a few times and every time I was in a party, a guild invite button worked; every time I was not in a party, the guild invite button did nothing when clicked.

**Comment by TheHollidayInn** [comment]
Oh interesting. I guess there was a second issue causing the button to break. I see it now. The code you linked does have the issue as it assumes the user will be a part of a party. Fixing now.
