### ISSUE TITLE
can't view participant list of active quest

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10508]
As reported by Ireanna (267135db-e7f8-42d9-bed2-f84b4261b64e):

**"once a quest is launched, the participant list can't be viewed anymore. this has been an issue since the whole big redesign of the site I think, just never got around to reporting it. there is the word "Participants" but clicking it does nothing."**

They're correct that it's been happening since the redesign and I recall that we were aware of it at the time but it looks like we never created an issue for it.

Clicking on "Participants" (shown below) should open a modal that shows the names of all the people who are participating in the quest. Ideally, clicking on each name should open that player's profile, but that's not essential.

![image](https://user-images.githubusercontent.com/1495809/42416246-9f448bfe-82ac-11e8-876a-396ee7129320.png)

**Comment by thefifthisa** [comment]
Hey! Can I try working on this?

**Comment by Alys** [comment]
@thefifthisa Thanks, that would be great! Post here if you have questions.
