### ISSUE TITLE
Health Potion insufficient Gold error message falls into console

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10519]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When the user doesn't have enough Gold to purchase the instant-buy Health Potion, and clicks the Health Potion reward, the resulting "Not enough Gold." error does not appear in a growl notification. It can only be found in the developer console.

This differs from the Enchanted Armoire, which spits a red "Not enough Gold." bubble onto the screen for the user to see and dismiss.

I did a bit of investigating into this myself, but couldn't pick out what was different in the refactored purchasing code https://github.com/HabitRPG/habitica/issues/10011 between the health potion and Armoire. @negue, maybe this is something you can clean up?

**Comment by negue** [comment]
The difference is that a `armoire` purchase is sent directly to the server, which throws an error and this error is shown in the webseite, a health potion is checked on the client first (the same routine) if that fails no error is catched which could show the message => fixing that
