### ISSUE TITLE
party members list is misformatted

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10510]
When you click on the "View Party" button or on the Party page's member list badge, the list of party members is no longer displayed properly. It now looks like the screenshot below. From memory, it used to be that all of the details for one member were in a single row (avatar, name, stats bars).

_Thanks to Ireanna for reporting this._

![scr](https://i.snag.gy/driyhW.jpg)

**Comment by paglias** [comment]
I think this is the same as https://github.com/HabitRPG/habitica/issues/10502, that's being fixed in https://github.com/HabitRPG/habitica/pull/10504

**Comment by Alys** [comment]
@paglias Ah yeah, thanks! I'm closing this and I've added extra keywords to the title of that issue.
