### ISSUE TITLE
Esc key with tags box active should dismiss only that, not entire task

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10520]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Minor usability issue reported in the bug guild:

>**whydidthetilda** (719c2e68-dd23-44fd-a27c-ef87dff4e3e1):
>this isn't really a bug (but it's happened to me enough times to be frustrating) but also not super worth putting in the features request thing either (I couldn't really work out where to put it there) - when setting the tags for a task, it would be v helpful if the esc key just closed the tag box rather than closing and losing the whole task.

**Comment by thefifthisa** [comment]
I'd like to take this!

**Comment by TheHollidayInn** [comment]
Thanks!

**Comment by thefifthisa** [comment]
So from what I learned, pressing esc closes a modal by default. I did find [this page](http://v4-alpha.getbootstrap.com/components/modal/#options) about modal options which says that setting the `keyboard` option to `false` can change it. I also found existing comments in the code base like this:
https://github.com/HabitRPG/habitica/blob/7bead74b495f23255b12b5dedc9a3831f9975b96/website/client/components/notifications.vue#L211

However, I'm having trouble implementing it for the task modal. I tried `this.keyboard = false` but it still closes on escape. Any help would be great!

**Comment by thefifthisa** [comment]
So from what I learned, pressing esc closes a modal by default. I did find [this page](http://v4-alpha.getbootstrap.com/components/modal/#options) about modal options which says that setting the keyboard option to false can change it. I also found existing comments in the code base like this:
https://github.com/HabitRPG/habitica/blob/7bead74b495f23255b12b5dedc9a3831f9975b96/website/client/components/notifications.vue#L211

However, I'm having trouble implementing it for the task modal. I tried `this.keyboard = false` but it still closes on escape. Any help would be appreciated!

**Comment by TheHollidayInn** [comment]
We actually use a Vue wrapper for bootstrap: https://bootstrap-vue.js.org/docs/components/modal#overview

My thought is you want to add a esc event to the modal: https://stackoverflow.com/questions/45568824/listening-to-esc-key-event-on-div-component-in-vue-js and a corresponding method. Inside that method, you can check if one of the submenus are open (e.g. tags box) and close them instead :D

**Comment by thefifthisa** [comment]
Oh okay, thanks! I think I got it!
