### ISSUE TITLE
"Save" button appears under Stat Points even when there's nothing to be saved

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10521]
When you don't have any Stat Points to be allocated, the "Save" button still appears under the Stats boxes even though there's nothing that can be saved:
![image](https://user-images.githubusercontent.com/1495809/42724260-5ea9b302-87b2-11e8-83f4-367ab179c469.png)

It also appears after you have had new points and have just allocated them, leading to a minor error condition as reported by Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) and confirmed by me. Aerilita's report is below.

---

Regarding assigning stat points on the website. (Just in case, it's in Chrome 67.0.3396.99 64-bit.)

1. Got a new stat point to assign. Clicked the notification. It took me to my profile, to the Stats page. There's a purple "Save" button under my stats.

2. Assigned the stat point to Int. A blue floating notification appeared, telling me I have 1 more max mana point.

3. Pressed the "Save" button. Don't quite remember what happened at that stage, something that confirmed I assigned the stat point (probably the arrows by stats disappeared). The purple "Save" button briefly changed to pale-purple "Loading...". Then it was back to the purple "Save" button (which, I guess, shouldn't be there at this point).

4. Pressed the "Save" button again. Got a red floating error notification "You don't have enough Stat Points" (the one that needs clicking to dismiss it). The button changed to pale-purple "Loading..." and got stuck like that.

5. Closed the profile, went to "Report a bug" guild. Opened my stats from the guild (User icon -> Stats). It still has the pale-purple "Loading..." button at the bottom.

6. Refreshed the page via F5. Opened my stats (User icon -> Stats). There's a purple "Save" button.

7. Pressed the "Save" button (just for the heck of it). Got a red floating error notification "You don't have enough Stat Points". The button changed to pale-purple "Loading..." and got stuck like that.

I guess that could cycle indefinitely. In short, the "Save" button doesn't hide when it should, gets clicked, errors ensue.

(No stat points were harmed during recording of that report.)

**Comment by dkenul** [comment]
It seems like the stat points are autosaved on allocation on level up as well (going off memory though, so could be wrong). Is the desired behavior that the stat points don't autosave (and use the save button) or that the save button is hidden except when it would actually do something?

**Comment by Alys** [comment]
@dkenul  Stat Points will be autosaved if one of the automatic allocation methods has been chosen (although that's buggy too at the moment so the behaviour is confusing).
The desired behaviour is that the save button should only appear when there's a change that needs to be saved (so it's invisible most of the time but as soon as you click the up button to assign one of your pending Stats Points, the save button appears).

**Comment by Alys** [comment]
There's another report from the Bug guild that's related to this from ari (252a53c4-111e-4021-9efe-964b444dfc75). It turned out to be just that ari didn't realise that the save button needed to be clicked because it looked to ari as if the change had applied itself automatically. Having the save button appear only when there was something needing to be saved would make this clearer. Here's their reports:

_"Unable assign stat points on website: When I get a new stat point, going to my profile on the website (whether through the notification or by clicking my username) and clicking the little up arrow to assign it appears to work (Intelligence goes up by 1, and I get a little popup that I've received 1 mana point). However, if I refresh the page, I get a popup that I've lost 1 mana point, and my Intelligence is back down to the original amount. If I click the purple "Save" button after assigning the point, I get a red popup saying "You don't have enough Stat Points.", and the "Save" button stays stuck with the text "Loading". Point assignment does work perfectly on the Android app (whoo! :)). Thank you!"_

...

_"Assigning points after reloading worked! But only if I clicked the "Save" button after clicking the up arrow. (which, it now occurs to me, must be desired behavior... but it's a bit confusing since I receive the extra Mana point before clicking Save, which kind of suggests the action has been done and isn't pending. But that's just my musings, not a bug). Thank you! :)"_


(BTW, it's correct that you get a Mana point for each point of INT that you assign, and due to the way that stat change notifications work, I don't think we can easily control when the notification appears, so that part of ari's report isn't something that necessarily needs to be fixed.)
