### ISSUE TITLE
Add New Wheelchair Options to Avatar Customization

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#10527]
We've had several requests for a wheelchair option without armrests or handles on the chair. These would be just be added as new options on the Avatar Customization menu under Extra>Wheelchairs. 

---

Suggested Label: I was thinking "Lite" since this is how this type most often seems to be described? But am happy to hear other ideas. 

e.g.: 

Label: Green Lite Wheelchair
Description: A green lite wheelchair. Confers no benefit.

---

Artwork is ready here: https://trello.com/c/Cc1Aw7OB/27-new-wheelchair-option

---

Links to possibly relevant past issues if needed: 

https://github.com/HabitRPG/habitica/issues/7854

https://github.com/HabitRPG/habitica/issues/6515

**Comment by fentie** [comment]
I'll take this one at least as far as I can :)

**Comment by beffymaroo** [comment]
@fentie Great, thank you!

**Comment by fentie** [comment]
So about this whole spritesmith business :) The wiki seems to be out of date, but I see that there's gulp tasks to package the individual assets into one or more large sprites, but I don't see where to find the resulting display window on the sprite sheet.

Also this asset set doesn't have the same "button" images as the last wheelchair set. Is that intentional? I can apply a 50% reduction in CSS to the provided images and get about the right size, otherwise we'd need additional PNGs.

**Comment by SabreCat** [comment]
@fentie: Spritesmith handles the window by creating a CSS class for you named the same as the sprite file itself. So for instance, `chair_pink.png` becomes a class `.chair_pink` with its background image set as the spritesheet it landed on and sized to the right window.

A side note on that: no need to commit spritesmith CSS or PNG files in a PR. Go ahead and run the task for testing, but when pushing, just commit the PNGs themselves. Including the CSS tends to create a bunch of unnecessary PR conflict headaches!

As for the buttons, those do need to be additional PNGs. I don't think we want to handle that using CSS. If you want, you can go ahead and autocrop the new images, recanvas to 60x60 and center, and save those as `button_chair_`whatever. Or if that's not in your wheelhouse, let us know and we can throw some together!

**Comment by fentie** [comment]
Looking at this again (sorry... frankly I got sucked into video games) I do think it'd be simplest if someone else made the button image adjustments. It wouldn't be impossible for me to do it but at the moment all I really have to work with is Preview.app unless I try to learn GIMP from scratch.

**Comment by fentie** [comment]
I also (disappointingly) haven't been able to find where those equipment/customization labels @beffymaroo is referencing actually live. I see that type of thing used in equipment descriptions but since this is solely an avatar customization and not a piece of equipment I don't see where it applies.

**Comment by beffymaroo** [comment]
@fentie I can take care of the icons! I'll attach them to this ticket shortly. 

I'm not sure about those description strings either, actually. There's no description for the chairs on mouse-over in avatar customization, and they don't appear in the Equipment modals either. @SabreCat do those currently live somewhere, or can/should we eschew those for now?

**Comment by fentie** [comment]
Oh that'd be wonderful @beffymaroo, thank you. I'm sure you're super busy so I really appreciate the help.

**Comment by SabreCat** [comment]
No need for the descriptions!

**Comment by beffymaroo** [comment]
@fentie The icons are now done and are attached to the same card where the other images are. :)

**Comment by fentie** [comment]
Oh wonderful, I'll get those added shortly :)

**Comment by fentie** [comment]
Ok the new assets are added, but they look a little odd next to the other chair images. Like the old images take up ~60% of the "button" space, and the new ones only take up about 25%?

<img width="806" alt="screen shot 2018-08-09 at 9 15 38 pm" src="https://user-images.githubusercontent.com/273815/43935398-723f365a-9c19-11e8-95dc-2eba9ce3c849.png">

They look great on the avatar though. I've noticed it seems like some of the images are at different scale than the others in other places too. ~Some of the equipment pieces are the same way, like the Anti-Procrastination Armor~ maybe that's just on Android. Nevermind that bit then :)

**Comment by SabreCat** [comment]
Hmm, I don't think they're supposed to be at a different resolution. (The avatar screen doesn't have rescaled images the way the equipment pages do.)

**Comment by beffymaroo** [comment]
@SabreCat Ah, so the buttons shouldn't be at 2x? Sorry, I'm so used to doing icons at 2x. I can resize them pretty quickly if needed.

**Comment by SabreCat** [comment]
@beffymaroo Yeah, should just be a recanvas rather than a resize, I believe!

**Comment by beffymaroo** [comment]
OK, buttons are now at standard Habitica pixel resolution.

**Comment by fentie** [comment]
OK cool, I'll re-pull them from Trello and update the PR

**Comment by fentie** [comment]
Looks good to me!

<img width="806" alt="screen shot 2018-08-10 at 6 58 07 pm" src="https://user-images.githubusercontent.com/273815/43985730-623a3014-9ccf-11e8-960d-7fe35e644e4c.png">
