### ISSUE TITLE
Reward List Downgraded

### ISSUE THREAD

**Issue by mbridgham** [HabitRPG/habitica#1053]
The reward list on the right side of the screen, the list supplied by HabitRPG, has turned into the list one level down from the items I've already obtained.  For example, I have purchased chain mail but the reward list is showing the leather armor at 20 pts.  Likewise I have the wooden shield and the reward is simply showing the wooden shield at the same level of protection and cost.  As is the sword.  I'm thinking I saw that the next shield was a buckler at a higher cost and giving greater protection but it's now disappeared to be replaced by the same wooden shield I already have (I know I'm repeating myself here).

**Comment by lefnire** [comment]
hmm. does it update when you refresh? (not the solution obv., just debugging)

**Comment by mbridgham** [comment]
Tyler,

It came back the next day so I'm not sure what caused it, I just assumed you'd been able to fix whatever was wrong!

HOwever, now the leather armor is back (a downgrade from the armor I'm wearing) but the rest of the rewards are at the appropriate level.

Thanks.

Marc

**Comment by StanLindsey** [comment]
Did you do a restore recently? I believe restoring updates your character but not the items in the rewards-shop/gold-store

**Comment by mbridgham** [comment]
not consciously

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
