### ISSUE TITLE
User receives "Joined Challenge" achievement for creating Challenge without joining it

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10544]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If a user does not have the `joinedChallenge` achievement, they receive it upon creating a Challenge. This used to make sense, when creating a Challenge automatically enrolled you in it, but now that it requires you to manually join your own created Challenges, the achievement is being awarded prematurely.

**Comment by alexfig** [comment]
Hi! Can I work on this?

**Comment by TheHollidayInn** [comment]
Please do!
