### ISSUE TITLE
3000 character limit on private messages (PMs) must be obvious to users

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10549]
_edited after discussion in comments below_

The 3000 character limit on posts made to groups was also inadvertently applied to private messages but we've decided to keep it, however currently there is no warning that your message will be cut off at 3000 characters. If you type more, the extra text is silently removed with no notification and no way to save it.

It's essential that private messages have the same character limit count that Tavern/guild/party messages have.

I'm marking this high priority because it's far too easy for an important part of the message to be lost without the sender realising that's happened.

_Thanks to Ceran the Superfish (aabe567b-aa55-42c1-b612-b7699a7ba9b7) for reporting this!_

**Comment by Alys** [comment]
Although.... thinking about this more... long PMs might be as problematic on mobile as long guild messages can be, especially for cases where troublesome users are spamming inappropriate messages. I'm moving this to "on hold" and I'll check with the other mods to see what they think. We might end up making the fix be putting the character limit warning on PMs. It will still be high priority.

**Comment by paglias** [comment]
I think a limit for PMs as well isn't a bad idea, it helps with perf problems, so I'm for adding the warning but keeping the limit

**Comment by Alys** [comment]
Yeah, that's fine with me, and none of the other mods expressed an opinion. I'm editing the top post to clarify.

**Comment by Alys** [comment]
Sorry, this should have been taken off hold when we made a decision. :(
