### ISSUE TITLE
No longer getting streak bonuses

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1054]
The streak counters on my dailies are adding up, as expected, but I no longer get any "+X Streak Bonus!" notification or extra coins.

I'm not sure when it started happening, but I suspect it was when I had to restore several streaks after a failed-sync episode.

**Comment by storian** [comment]
I am noticing that the streak bonus is being granted for the NEXT item I click.  So, if I should get a streak bonus of X on a daily, I don't get it when I click the daily, but I see a streak bonus for X on the next thing I click (whatever it is).

**Comment by storian** [comment]
Also, the streak counter might not be getting iterated until the FOLLOWING item is clicked.

**Comment by SabreCat** [comment]
Hmm, I'll see if that happens--if that's so, I'm probably running into #1044 . I may be accidentally working around the 1044 issue due to my compulsive refreshing in between each action, a habit I picked up after the aforementioned failed sync...

**Comment by octern** [comment]
I've been getting the same thing. I noticed streaks were acting funny for at least a couple of days, but today I was able to verify that it's doing exactly what storian described, granting the streak bonus for a given daily when I click the next daily. However, the streak counter on a daily does increment as soon as I check off that daily.  

If I reload the page after clicking a daily with a streak, and click a daily with no streak on it, there's no bonus applied -- the streak bonus is just lost.

**Comment by wildcate** [comment]
Me too - the streak bonus appears when I click the next item.

**Comment by SabreCat** [comment]
I'll leave this open since some people are still running into it, but it's been behaving fine for me the last couple of days.

**Comment by lefnire** [comment]
i can't seem to replicate this.. and https://github.com/lefnire/habitrpg/commit/1745ae6205b350f36537cd36b8805f56b3f11895#L2R42 should have fixed it actually. when was the last time someone experienced this issue?

**Comment by lefnire** [comment]
@SabreCat you're really helpful around the tickets, mind if i make you a mod?

**Comment by SabreCat** [comment]
@lefnire Hey, cool, I'd be happy to if it helps. Sign me up and let me know what you'd like me to do!
