### ISSUE TITLE
Healing Light should not be castable if the player already has 50 health

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10548]
Currently, it's possible to cast the Healer's "Healing Light" skill (which increases the player's own health) even when their health is already 50. 

The desired behaviour is that when the player tries to cast the skill, if they already have 50 HP, the skill cast should fail. 

The test for the current HP should be at the API level and NOT also at the UI level. I.e., even if the website is showing that your health is 50, you should still be able to try to cast the skill. The server would then read your actual health value and reject the cast (not take your mana) if your health is at maximum. This would avoid any problems with sync errors or local display errors causing the website to think you had full health when really you did need to cast the skill (admittedly, it wouldn't be often that a player would want to cast the skill if it looked like they had full health, but a player who is aware of sync errors and is using the DDT or an app might want to).

For reference, https://github.com/HabitRPG/habitica/issues/6384 was for the same problem for Health Potions. The PR that fixed it was https://github.com/HabitRPG/habitica/pull/7934/files and some of its code can be reused (for example, the `messageHealthAlreadyMax` string should be used for this issue).

_We could also do the same fix for the Blessing skill which adds health to all party members, but a server-side check for the health of all players might make the skill too slow? Perhaps we should ignore Blessing for now._

_Thanks to citrusella for pointing this out._

**Comment by citrusella** [comment]
This might be an unrelated thing but when buying a health potion fails, I don't see `messageHealthAlreadyMax` (in fact, I didn't even know it was supposed to display for the health-not-going-through when I reported this).

EDIT: Hmm, the reason for that could be similar to #10519 ?

**Comment by Arsnael** [comment]
Hi guys ! Could I take a look into this one? :)

**Comment by paglias** [comment]
Sure!

**Comment by Arsnael** [comment]
I made a PR fixing the issue. 

The current logic is that the cast is being made on client's side before doing the request to the server : 
https://github.com/HabitRPG/habitica/blob/develop/website/client/mixins/spells.js#L88 (client's cast call)
https://github.com/HabitRPG/habitica/blob/develop/website/client/mixins/spells.js#L95 (server request)

Wondering if we shouldn't make a call to the server first? Anyway the change has been made in the common script, used by both, so if user makes a direct call to the API server he gets the same result as well.

@citrusella : not unrelated at all, I had the same issue. Thanks for pointing that out :)
