### ISSUE TITLE
duplicating potions - not #901

### ISSUE THREAD

**Issue by Figlet** [HabitRPG/habitica#1055]
My potions are multiplying like rabbits. I currently have 18 Shades, 39 (yes, 39) Cotton Candy Blue,  2 whites, and a skeleton. I know there was the multiplying potions problem a while back; it seemed be resolved and now I have this.

**Comment by lefnire** [comment]
noted. but why is it not #901? sounds exactly it?

**Comment by Figlet** [comment]
I've only been on rpghabit for 3 weeks and I believe that my drops have been 1 egg, 1 white, 1 skeleton, 1 base (which I've used), 1 shade, and 1 CCB. I thought #901 was one or two duplicates as opposed to dozens and dozens. My apologies if this is the same - just ignore the thread and I'll follow up at 901.

**Comment by lefnire** [comment]
yep, #901. what happens is the slowness / reliability of the connection determines the amount of duplicates. Slower / less reliable, more duplicates. It could be when the server goes down, or when slow internet, etc. This stuff will be fixed in the migration to Racer 0.5

**Comment by Figlet** [comment]
Great, thanks! I'll follow up on the #901 thread.
