### ISSUE TITLE
Challenges and Guilds/Parties show cached details if you've viewed other challenges previously

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10554]
From AnneLine (16a107de-d519-43ce-8c30-8da5cbcbb237) in the Bug Guild:

> OK, Bug zapperes, I have a fun one for you. One of my monthly challenges is the Golden Badger challenge in the STAG guild. Here's a link (I think). Now here is what the question is -- the download and the number showing in the guild is 10 people participating, and that's about what I would expect. BUT if you drop down the 'participants' menu, there are about 20 names on there! What the heck is going on? No rush on this, but I will need to be able to award it at the end of the month....

> And so, of course, that link (below) just shows 9 or 10 people. Any idea why I would have gotten a list with a lot more people? It actually LOOKED like the list of the sister challenge, Badger 101, that I had just viewed a few seconds earlier. Thoughts?

Confirmed by me.

**Comment by alexfig** [comment]
Hi, can I work on this?

**Comment by Alys** [comment]
@alexfig Sure, thanks! Post here if you have questions.

**Comment by SabreCat** [comment]
We have a report from @saraolson that this is still happening in some flows:

>When I view the member list for a Guild then go to view the member list for a Challenge, the list displays the previous Guild’s members instead of updating to the Challenge’s members. Same thing happens if i view my Party member list then go to Challenges.

Maybe it's fixed for Challenge > Challenge flows, but not for Challenge > group flows?

**Comment by shanaqui** [comment]
Group > Group flows are also doing this, per a report in Report a Bug today:

> Star1412   @Star1412 (e0f8551d-4d74-4ba3-a065-762d985080c1) [web] 
> I think I've found a bug with the website. When I go to more than one guild pages in a row and then click on the member list, it always brings up the list for the guild I was previously on. I have to refresh the page to get the guild list for the guild I'm looking at. It's a minor problem, but I thought someone should know anyway

**Comment by paglias** [comment]
I think this was fixed by a PR I made a month or so ago
