### ISSUE TITLE
[Feature Request]:Autocomplete for habits,to-do and daily.

### ISSUE THREAD

**Issue by gosaingourav17** [HabitRPG/habitica#10571]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by gosaingourav17** [comment]
Autocomplete for common habits,to-do list and Dailies would be a good idea.

**Comment by TheHollidayInn** [comment]
Thanks for the request @gosaingourav17, but right now we only take feature requests here: https://trello.com/b/EpoYEYod/habitica. Feel free to add it :D
