### ISSUE TITLE
Time Traveler Hourglass not working 

### ISSUE THREAD

**Issue by seanloo777** [HabitRPG/habitica#10575]
Hey there, 

I have been subscribed for some time now but only have received one hourglass. Help!

My user ID is 889fefd3-ecda-4ee3-8b30-23fec77102d1

**Comment by Alys** [comment]
Can you please go to Help > Report a Bug from the Habitica website's menu and copy your post there? We use GitHub for bugs that need code fixes and what you describe will just need an admin to investigate briefly. The "new issue" form here in GitHub has more details about how to report bugs if you're curious - see the comments in it.
