### ISSUE TITLE
Equipment change needs reload before it can be seen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10586]
As [reported](https://github.com/HabitRPG/habitica/issues/10581#issuecomment-411902783) by @asktree (9ed86aed-d1a0-4618-b5eb-d64d1190b915):

"if I change my equipment, I have to reload the page in order for it to update. I just assumed that there was some underlying architectural reason that things might not sync as cleanly as in other softwares."

Copying @TheHollidayInn's question:

"@negue are you aware of this? I'm not seeing an existing issue, so we should add one/fix this."

**Comment by negue** [comment]
@asktree I can't reproduce any out-of-sync errors, I can select an equipment item, and its immediately visible on the avatar.

If you can reproduce your issue, pls tell me exact way (what and where do you select).

Is it for gear or costume, do you have your costume setting active? Are you on the gear/costume tab (at your drawer)?

Also what OS / Browser?

**Comment by asktree** [comment]
@negue 
Hi--
Windows 10, Chrome

How odd. I actually tested this before including it in my post, and didn't bother to record it. Now, I am trying again and it's showing changes immediately as you say for gear, costume, and pets. So as of now I'm unable to reproduce or demonstrate. I'll be sure to record while making any gear changes over the next week, for my sanity's sake if nothing else.

**Comment by TheHollidayInn** [comment]
@asktree no worries. It might happen under special circumstances. If you can find it, just let us know. We want the experience to be instant :)

Feel free to reopen if it happens again.
