### ISSUE TITLE
Hatched a pet, pet isn't available and potion+egg are gone

### ISSUE THREAD

**Issue by TheLemming** [HabitRPG/habitica#1059]
I just got a cotton Candy BLue Potion and tried to hatch a Lion Egg with it.

for around 5 seconds the Pet was shown in my list though i couldnt select it, then it vanished.
The Potion and the egg are gone too.

**Comment by lefnire** [comment]
what's your user id, i'll give you tokens to buy them back. will be hopefully solved in the [0.5 upgrade](http://habitrpg.tumblr.com/post/51476277225/upcoming-features-bugs-update-user-survey)
