### ISSUE TITLE
password reset emails aren't being sent

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10591]
We've had reports of password reset emails not being received, tests that I've done on the Android app and website have not given me any emails, and our records of password reset emails sent stop two days ago.

There's no obvious error in the API route:
```
$ curl -d"email=lady_alys@oldgods.net" -s -X POST https://habitica.com/api/v3/user/reset-password 
{"success":true,"data":{},"message":"If we have your email on file, instructions for setting a new password have been sent to your email.","appVersion":"4.56.3"}
```

This might be a problem with the mail service we use rather than a code bug

**Comment by TheHollidayInn** [comment]
This is an issue with our settings and not code. I'm working on fixing it.
