### ISSUE TITLE
Optional health bar

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#106]
From a Kickstarter user:

Dear Tyler, 
Hey there! First off, I just wanted to commend you for your game/program/gamifying life tool. It's really what I've been waiting for for a long time. It rewards good behaviors for people in a direct manner, something that life can't, at times.

I'm writing you about the health bar, though. I don't think it's a bad idea at all. It's meant to motivate through negative reinforcement of bad habits. This may work for many, but I'm not sure it covers a large demographic.

I believe the health bar may hurt many along their path to making better habits. Many may see that their health lowering as a sign of slipping and just give up, as many people trying to quit smoking or drinking tend to do when they "quit cold turkey."

This is why I propose the health bar being optional. That way, for those people, there is only positive reinforcement for their good actions. They can see their progress down the right path, whatever it may be for them, without feeling like they're failing.

I don't expect you to heed this, but I just want you to consider it. Perhaps you can think of a better solution? I only wish you well in this endeavor. As I said, I think this idea is spectacular and I fully endorse it.

**Comment by ghost** [comment]
I hadn't thought of that but it makes sense

**Comment by JamPol** [comment]
Makes sense to a point, how long currently does it take for the task to go red and begin hurting your health? If the event turns red in two/three days and begins hurting your health then yes after two/three days without performing the habit you're trying to form you are slipping up.

On the flip-side it wouldn't hurt to make it optional, it could be considered 'hard-mode'.

**Comment by antistic** [comment]
Good idea, although there is the option to buy a health potion to restore HP, so in a sense you can make up for slip-ups with more progress. Though that probably may not be good enough for everyone (as depending on how badly they're doing, it might be really difficult to get)

**Comment by racuna** [comment]
I disagree, 'cause in a future when habitRPG will have groups, there will be people running with advantages not having the "risk of death"

**Comment by the-economancer** [comment]
removing the health bar, or even making it optional would effectively make it like many other tracker apps I've seen/heard of. Negative reinforcement, imho, is integral to the concept of an RPG, as the motivation to keep your character alive by avoiding damage (doing what you're supposed to) is just as important (if not more so) as the rewards you earn, which is something you can easily find elsewhere.

**Comment by racuna** [comment]
@the-economancer +1

Other trackers (like TaskHammer) dont have "negative reinforcement" and in a couple of days of using it turn boring like every other todo list.

**Comment by JamPol** [comment]
Mmm good points are made here and I have to agree. The "holy crap this is awesome" moment was when I started losing health for the red "45min reading" daily task.

**Comment by jusomagna** [comment]
@economancer: then leave the health bar on, if it were optional. It just means that this way of motivation may not work for everyone.

**Comment by racuna** [comment]
@jusomagna in that case, a user whitout health bar off can't join in a (future implemented) group with members with the health bar on. IMHO.

**Comment by jusomagna** [comment]
@racuna : I can agree with that. I have a feeling most who wish to join a group would want a health bar, anyway.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
Should I open a trello card for this yet? Most of the commenters don't seem to be inclined towards it.
By the way, I think this discussion is related to the death discussion, #223.

My own 2¢ as far as the health meter goes: Don't change the health functionality, if that is the original commenters suggestion. Address the discouragement potential a different way if need be, such as by fun, encouraging notifications if the health points get low (see #223 and #59).
I wonder if the original poster realizes that beneath the Health meter is an XP meter. So, if you see negative, odds are you also see positive. Doing any good habit, daily or task will instantly boost the progress meter.
Would help to make the XP meter a contrasting color to the Health meter? Just a thought.

**Comment by lefnire** [comment]
Hear hear
