### ISSUE TITLE
Private message deletion deletes the wrong messages in a weird order

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10607]
From trele_morele (3b4cd0f7-1986-4068-a439-7f1df7b8e55a) in Report a Bug:

> Hello everyone :) I've just found a bug in private messages. When I wrote two or more messages in a row and I delete the last one, it's not deleted, but the first one is. Let's say my name is K and I'm chatting with T, then it would look like this:
> 
> T: Hi, how are you?
> K: Thanks, I'm fine
> T: Thats perfect
> K: what about you?
> K: and did you see that movie x yesterday?
> K: It was great btw imo
> So if I click delete on message 6, then the message 4 is being deleted. If I click the same again, then the message 5 would be deleted, and then at last when I click delete on message 6, it's gonna be itself deleted. It does not affect message 2.
> 
> I hope it's going to be helpfull :)

I have confirmed this, except that for me message 2 was deleted, then 3, then 4, then 5. Then 6 was finally itself deleted. Then I reloaded to check on [this bug](https://github.com/HabitRPG/habitica/issues/9530) and that's still true *except* for message one, which *had* been deleted.

**Comment by Alys** [comment]
I've marked this as important priority because we need a fix soon. People could be losing important messages because of this and it also could impact moderation if a flaggable PM is inadvertently removed. I expect that reloading before deleting would prevent the problem but we can't expect players to realise or remember that.

**Comment by TheHollidayInn** [comment]
So it seems to me that this bug is a side effect of #9530. If I refresh (or sync) before deleting everything seems to be okay. 

So I'm going to fixed #9530 to fix this as well.
