### ISSUE TITLE
subscription cancellations are setting dateTerminated too early

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10605]
When twelve-month recurring subscriptions are cancelled the termination date is too early. This might also apply to other multi-month subscriptions. I don't think it happens for one-month recurring.
Whether the bug happens might depend on when the cancellation occurs compared to when the subscription is created (in my test below both were on the same day) although in theory that shouldn't matter.

I created a twelve-month subscription on my test account:
```
"purchased.plan": {
	"consecutive": {
		"count": 0,
		"offset": 12,
		"gemCapExtra": 20,
		"trinkets": 4
	},
	"quantity": 1,
	"extraMonths": 0,
	"gemsBought": 0,
	"mysteryItems": [],
	"dateUpdated": "2018-08-15T08:01:05.738Z",
	"customerId": "I-CH58B11XLGTR",
	"dateCreated": "2018-08-15T08:01:05.738Z",
	"dateTerminated": null,
	"owner": "8b5a828d-a8df-4788-9374-8b5f277ca0cc",
	"paymentMethod": "Paypal",
	"planId": "basic_12mo"
}
```

A few hours later I cancelled it. The `dateTerminated` should have been around 2019-08-15 (one year after creation since I'd paid for one year) but it was one month from the date of creation:
```
"purchased.plan": {
	"consecutive": {
		"count": 0,
		"offset": 12,
		"gemCapExtra": 20,
		"trinkets": 4
	},
	"quantity": 1,
	"extraMonths": 0,
	"gemsBought": 0,
            "mysteryItems": [],
            "dateUpdated": "2018-08-15T08:01:05.738Z",
            "customerId": "I-CH58B11XLGTR",
            "dateCreated": "2018-08-15T08:01:05.738Z",
            "dateTerminated": "2018-09-14T00:00:00.000Z",
            "owner": "8b5a828d-a8df-4788-9374-8b5f277ca0cc",
            "paymentMethod": "Paypal",
            "planId": "basic_12mo"
        }
    },
```

I've seen other reports of this recently so I believe it's a consistent bug. It's also relatively new (weeks or months old maybe) because I'm sure it hasn't been happening forever.

**Comment by Alys** [comment]
It might also depend on the payment method - both my test and one recent other report that I'm aware of (763c8800-98b3-4b73-a607-2bed33a8aca7) were PayPal. I haven't gone searching for other reports to get their methods.

**Comment by Alys** [comment]
It's probably from this code in cancelSubscription() :
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/libs/payments/subscriptions.js#L278-L288

plus the code that passes `nextBill` into cancelSubscription() :
```
website/server/libs/payments/amazon.js:230:    nextBill: moment(lastBillingDate).add({ days: subscriptionLength }),
website/server/libs/payments/apple.js:173:    nextBill: dateTerminated,
website/server/libs/payments/google.js:168:    nextBill: dateTerminated,
website/server/libs/payments/paypal.js:235:  let nextBillingDate = customer.agreement_details.next_billing_date;
website/server/libs/payments/paypal.js:237:    throw new BadRequest(i18n.t('planNotActive', { nextBillingDate }));
website/server/libs/payments/paypal.js:245:    nextBill: nextBillingDate,
website/server/libs/payments/stripe.js:129:  let nextBill = moment().add(30, 'days').unix() * 1000;
website/server/libs/payments/stripe.js:139:      nextBill = subscription.current_period_end * 1000; // timestamp in seconds
website/server/libs/payments/stripe.js:146:    nextBill,
website/server/libs/payments/stripe.js:226:        nextBill: moment().add({days: 3}).toDate(),
```

For PayPal, I wonder if something is going wrong when getting the customer agreement details:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/libs/payments/paypal.js#L232-L235
...
`website/server/libs/payments/paypal.js:245:    nextBill: nextBillingDate,`


Anyway, I'm backing away slowly now and letting someone else dig into the details. :)

**Comment by TheHollidayInn** [comment]
I've noticed this bug last year on some payments. I added test and fixes for some but I wasn't sure if I got them all. Ill look into this.

**Comment by TheHollidayInn** [comment]
Did you see any API errors when you canceled?

**Comment by Alys** [comment]
No

**Comment by ohnoitsadalek** [comment]
I just subscribed to a twelve month subscription and then cancelled on the same day and have this issue. Interestingly, when I cancelled, I checked whether the date was correct and as far as I can remember, it was a date in 2019. When I checked back a day later however, it had changed to a month in the future, not a year. (I then commented in the report a bug guild and they manually changed it). Thought you should know that it was correct immediately after

**Comment by paglias** [comment]
This should be fixed in #10761, the issues was that (thanks to @SabreCat for finding it!) when a subscription is cancelled in Paypal an IPN message is then sent to our server resulting in a second cancellation that causes a mismatch in the remaining sub time.


The fix consists in not cancelling the subscription again if it was already cancelled

**Comment by paglias** [comment]
It'll go live later today

**Comment by Alys** [comment]
Reopening because there's a new report of this although we might want to make a new issue. I'll think about this a bit more on the weekend or early next week and see if I can find any relevant logs (e.g., from double cancellation attempts). For now I just want to get this recorded. I've already fixed the termination date for this player. [EDIT: There were no entries in Loggly relevant to this.]

From backup database containing data from two days ago (shows that the player had no existing subscription details that might have interfered with correct setting of dateTerminated):
```
{
    "_id": "83d91034-db02-4f9f-892b-21a7ff4b7bc5",
    "purchased": {
        "plan": {
            "consecutive": {
                "count": 0,
                "offset": 0,
                "gemCapExtra": 0,
                "trinkets": 0
            },
            "quantity": 1,
            "extraMonths": 0,
            "gemsBought": 0,
            "mysteryItems": [],
            "dateUpdated": "2019-07-02T19:41:51.981Z"
        }
    },
```

From production database before I fixed terminationDate:
```
    "purchased": {
        "plan": {
            "consecutive": {
                "count": 0,
                "offset": 3,
                "gemCapExtra": 5,
                "trinkets": 0
            },
            "quantity": 1,
            "extraMonths": 0,
            "gemsBought": 3,
            "mysteryItems": [],
            "dateUpdated": "2019-07-18T19:55:25.403Z",
            "customerId": "I-L......",
            "dateCreated": "2019-07-18T19:55:25.403Z",
            "dateTerminated": "2019-08-17T00:00:00.000Z",
            "lastReminderDate": null,
            "owner": "83d91034-db02-4f9f-892b-21a7ff4b7bc5",
            "paymentMethod": "Paypal",
            "planId": "basic_3mo"
        }
    },
```

**Comment by Alys** [comment]
Here's another case of this issue:

```
    "purchased": {
        "plan": {
            "consecutive": { "count": 0, "offset": 12, "gemCapExtra": 20, "trinkets": 4 },
            "quantity": 1,
            "extraMonths": 0,
            "gemsBought": 0,
            "mysteryItems": [ "head_mystery_201912", "back_mystery_201912" ],
            "dateUpdated": "2019-12-18T09:02:58.260Z",
            "customerId": "I-......",
            "dateCreated": "2019-12-18T09:02:58.260Z",
            "dateTerminated": "2020-01-17T00:00:00.000Z",  // This should be 2020-12-17
            "lastReminderDate": null,
            "owner": "94e28255-5f66-45dd-a13c-02e48cc0b5e2",
            "paymentMethod": "Paypal",
            "planId": "basic_12mo"
        }
```

**Comment by benkelaar** [comment]
Hi @Alys ! I could look in to this one next, but it kinda sounds like the issue might be in the way habitica communicates with Paypal. 

As such I'm not sure how doable it would be to reproduce locally. Is there some (technical) information on what that connection looks like?

**Comment by Alys** [comment]
@benkelaar Thanks! I've marked this as in progress for now but it's totally fine if you tell us to set it back to help wanted!

I don't know what the connection to PayPal looks like. @paglias or @SabreCat might be able to help.

It might be worth doing a quick check to make sure the fix described in https://github.com/HabitRPG/habitica/issues/10605#issuecomment-430953794 is still in place.

Keep in mind that it's possible that the more recent instances of this bug might have a different cause than the earlier ones. I wasn't able to find any data to indicate what might be going on with the recent ones.

**Comment by benkelaar** [comment]
Cool, thanks, I'll have a rummage through the relevant code tomorrow and see if I can see anything suspicious that might also be causing this same behaviour.

**Comment by benkelaar** [comment]
@Alys Are we sure this problem might not be an instance of this? https://github.com/HabitRPG/habitica/issues/11664 Or is that an entirely different kind of subscription? (The group kind?)

**Comment by Alys** [comment]
@benkelaar Short answer: no, it's not related. :)

The subscription that you get for free from a Group Plan works in the much same way as subscriptions that you pay for or get as a gift, except that subscription cancellation occurs automatically when you leave the Group Plan or when the Group Plan itself is cancelled. (In case it's not clear, the Group Plan is a paid feature that's applied to a guild or party and all members get the free subscription.) 

Despite the similarity in the subscription types, that https://github.com/HabitRPG/habitica/issues/11664 issue isn't related to this one. It was caused specifically by the Group Plans code and so couldn't happen with subscriptions from other sources. Also it didn't exactly set the `dateTerminated` value incorrectly in a direct sense. What the Group Plans cancellation code did was:
1. set `dateTerminated` _correctly_ using the user's current value of `extraMonths`
2. erase the user's `extraMonths` value since it was no longer needed (also correct)
3. re-run itself to set `dateTerminated` again (bug!) and since the user no longer had `extraMonths`, the new `dateTerminated` did not take account of those months and was set too early.

In case you don't know, `purchased.plan.extraMonths` is set into a user's account if they have a subscription, cancel it, and then start a new subscription before the time purchased from the previous one has expired. Those extra months of subscription time are added to the `extraMonths` value for use later if/when their new subscription ends.

**Comment by benkelaar** [comment]
Interesting. Both that issue and this (original issue) were cause by calling `#cancelSubscription` twice right? The original fix implemented for this one in the *Instant Payment Notification* handler is indeed still in place, so something else seems to be going wrong.

However, I think it's a bad idea to do these kinds of state-based calculations with payment-related data in the first place (Here I go again 🙄). I think a better solution might be to have an immutable transaction log of payments received so that all state based on payments can be recalculated and traced back to their source at all times (Should also make support questions a lot easier).

In that case `cancel` might even not be an action at all as it will simply naturally occur after stopped payments (But you'd probably still want to fire an event in case you're sending e-mails, metrics, logs or other notifications based on it, but it would not be necessary for the payment part).

Let me know what you think, I'll continue my search for the cause of this bug tomorrow.

**Comment by Alys** [comment]
> Both that issue and this (original issue) were cause by calling #cancelSubscription twice right?

Hmmm yes, that seems correct at least for the initial cause of this bug, based on paglias's comment above _("when a subscription is cancelled in Paypal an IPN message is then sent to our server resulting in a second cancellation")_. I'm not sure if that's still what's happening now.

What _might_ help is if any code that sets `dateTerminated` would first check to see if there's a current value for it. If the new value is earlier than the current value, then the code should not change the current value. That should prevent the damaging effects of this bug regardless of what the root cause is.
It would also work for any future causes of `dateTerminated` being reset twice, which I think is important to consider.
BUT I have not looked at the code to see if this would actually be suitable. :)

Of course we should find and fix the current root cause, but a quick workaround to prevent users losing time they paid real-world money for would be suitable in my opinion. If Habitica's staff disagree, listen to them not me. :)

Note though that it's possible that the current cause of this bug isn't actually from `dateTerminated` being changed twice. Maybe there's some incorrect data being read or some calculation being done wrongly that's setting the value once but too early. In that case of course the workaround wouldn't help, but I still think it might be worth adding it.


The rest of your post isn't something I can comment on so I'll leave that for the staff. :)

**Comment by benkelaar** [comment]
> What _might_ help is if any code that sets `dateTerminated` would first check to see if there's a current value for it. If the new value is earlier than the current value, then the code should not change the current value. That should prevent the damaging effects of this bug regardless of what the root cause is.
> It would also work for any future causes of `dateTerminated` being reset twice, which I think is important to consider.
> BUT I have not looked at the code to see if this would actually be suitable. :)
> 
> Of course we should find and fix the current root cause, but a quick workaround to prevent users losing time they paid real-world money for would be suitable in my opinion. If Habitica's staff disagree, listen to them not me. :)

Good idea, by checking the assumption of the method and failing early we get errors instead of faulty state. I'll see if I can implement something like that.

**Comment by benkelaar** [comment]
@Alys Did what you suggested, it should make the code more resilient against such failures, but I can't wrap my head around what exactly went wrong here.

Every time I get a new theory the code tells me I'm wrong. Could be some weird concurrency thing going on but there was not a clear issue I could find. Not sure if this is good enough to close this issue, but it's a start 😄

**Comment by paglias** [comment]
I just tried to replicate the issue with a 3 month Paypal test plan but it worked flawlessy.

That being said I'll merge the PR so we have an extra edge case covered

**Comment by SabreCat** [comment]
Still getting reports of this with PayPal subscriptions. Possibly only hits in the case when we get a cancel notification from the PayPal side, rather than when the user ends the subscription via Habitica?

**Comment by paglias** [comment]
> Possibly only hits in the case when we get a cancel notification from the PayPal side, rather than when the user ends the subscription via Habitica?

Yes that's likely, Paypal seems not to validate some of our requests, the error is not very informative unfortunately

**Comment by paglias** [comment]
In particular some requests paypal makes to the IPN route result in this error

```
Error: IPN Verification status: INVALID
```

**Comment by paglias** [comment]
The PR fixing the IPN issue has been deployed, I'm not sure it's linked to this issue but we might want to review this in a bit to see if it's still happening

**Comment by veeeeeee** [comment]
Closing this issue for now. Can reopen or start a new issue if recurring.
