### ISSUE TITLE
Outgoing private messages appear doubled on client

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10621]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 7f14ed62-5408-4e1b-be83-ada62d504931
  * Browser: Firefox
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When you first send off a private message to a user, the message is duplicated in the messages UI, making it appear to have been sent twice. After a refresh, the copy goes away. Reproduced in both staging and production environments.

![image](https://user-images.githubusercontent.com/4501321/44606430-b2c3e500-a7b2-11e8-835f-31848d6a7eae.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None.

**Comment by TheHollidayInn** [comment]
Does this happen when sending to a new user?

**Comment by SabreCat** [comment]
@TheHollidayInn That's when I'd noticed it--pull up profile of somebody you haven't messaged before, click message button, write up message, send.

**Comment by legitmaxwu** [comment]
maybe I could check this one out?

**Comment by Alys** [comment]
@legitmaxwu Sure, thank you! :)

**Comment by paglias** [comment]
Actually this has been fixed in https://github.com/HabitRPG/habitica/pull/10428 that will be merged soon
