### ISSUE TITLE
Dailies: Bogus damage followed by bogus check marks.

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#1062]
This morning, when I was finally able to connect, I took 3 points of damage, in spite of having completed all my dailies yesterday. Normally I'd assume that this meant the update just before I went to bed had been lost, but as it happened, I'd written down precisely how many xp and coins I had just before going to bed. _those_ numbers were unchanged - the only change was losing 3 HP. (I'd written that down too.) 

I'm on the regular server. 

[Update: It gets better. While I was typing this bug report, my habitrpg tab changed. The damage went away - to be replaced by finding most of my dailies checked off and greyed out. _My total experience and coins still haven't changed_  Reload didn't change anything.

There's no clear pattern to the set of dailies which haven't been inappropriately marked complete. It is notable that many of them are dailies which I don't require on a Sunday [ie yesterday] but 4 of them are 7-day-a-week dailies. It's also worth noting that I see a check mark on 2 greyed out only-on-a-Sunday dailies - they'd normally be greyed out without a check mark, on a Monday]

Changed the bug title to refer to both problems.]

**Comment by Aubec** [comment]
I experienced something similar.  All of my dailies were completed but I took damage anyway.  I'm not sure if this matters but the Chrome extension tells me that I have two dailies that I didn't enter and that I don't see in my list (1h Personal Project and 45m Reading)

UserID: 228a0207-6355-471a-84cd-7de7bba7feee

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
