### ISSUE TITLE
Death causes an incorrect notification that you gained Experience

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10635]
As reported by Il Mago (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) and confirmed by me:

"My character just died and I received a notification that said that I gained experience (when instead I lost them), about 1500xp which was the amount I needed to reach next level before death"

The user's level and experience are adjusted correctly, it's just the notification that's misleading.

This will be very confusing for new users who already often ask what the effects of death are so I'm marking this as high priority.

**Comment by majestic-owl448** [comment]
I think it was from the PR of this issue 
https://github.com/HabitRPG/habitica/issues/10297 merged without addressing the issues in the comments (the death case was something that didn't came to mind tho)

**Comment by TheHollidayInn** [comment]
I'll look into this. @Ieahleen your suggested about looping the max xp is good too. I'll add that in as well after testing if it works.

**Comment by Arsnael** [comment]
Oups my bad... Yeah didn't think of the death cause sorry (didn't die yet with my character, maybe why^^'). Obviously I don't know the code enough around yet... Will try to be more careful next time !

**Comment by paglias** [comment]
Should be gone since the previous PR has been reverted in the mean time
