### ISSUE TITLE
lvl 4 bear cub egg disappeared

### ISSUE THREAD

**Issue by liordon** [HabitRPG/habitica#1064]
when I reached lvl 4 I recieved a bear cub egg as a gift, but it recently disappeared from my inventory. a wolf egg I found later is still there though, so I wonder what happened. (since when are mammals hatching from eggs anyway? :P ) 
sorry to bother you, I sorta hope it really is a bug and I'm not bothering you guys for no reason.

**Comment by wc8** [comment]
it's legit: you can follow up here: #952

**Comment by StanLindsey** [comment]
Closing for house keeping, as per wc8s words; follow up in #952
