### ISSUE TITLE
List of possible usernames to mention doesn't close

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10646]
From Il Mago in the Bug guild, using Safari on iOS. Reproduced in Chrome on Windows 10.

> Bug: When you type a @, there is the list of names that appear, but if you delete the @ it stays there and disappear only when typing a space
> if the `@` is the first character you type in then deleting it makes the list of names disappear. If you instead type it immediately after an other character, (for example `hi@`) then the list disappear only typing in a space or deleting till the previous space

**Comment by paglias** [comment]
I'm not able to reproduce this on Chrome

**Comment by majestic-owl448** [comment]
@paglias : I can still reproduce them, I can try to record my screen if you want

**Comment by paglias** [comment]
@Ieahleen which browser are you using? Also the steps to reproduce it are the same as in the description above or some steps are different?

**Comment by majestic-owl448** [comment]
@paglias
Google Chrome Versione 69.0.3497.100 (Build ufficiale) (a 64 bit)
I keep being able to reproduce the issue in the way I have reported it the
first time. If I write "hi@" and then delete the "@", the dropdown with
names is still there and disappear only when tipying a space

**Comment by paglias** [comment]
thanks @Ieahleen !

**Comment by paglias** [comment]
Looks like this has been fixed during the username overhaul
