### ISSUE TITLE
some lost Armoire equipment is incorrectly locked and can't be found in Shop

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10659]
MarieFrog (26cace60-f1f3-4678-bd66-23d9571dfc8c):
"I've lost a level and lost a piece of equipment which is now pinned to my rewards column, so far so good. I can't buy it though because it says "locked until you've purchased the previous items in the sequence". It's the Jeweled Archer Armor"

Confirmed. When I set `items.gear.owned.armor_armoire_jeweledArcherArmor` to `false` on my account and add it to my `pinnedItems` array, it does appear in my pinned items on the website but is locked with the `tierLockedItem` message. It should be unlocked because it's an Armoire piece - when you lose it due to Death, you should be able to buy it back immediately.

Also the item does not appear in the Shop for me to buy back. It should appear under the "None" class, otherwise if you don't have it pinned, you can't rebuy it.

The same problems do not occur for `items.gear.owned.weapon_armoire_poisonedGoblet` - when I set it to have a false value, it is not locked and it does appear in the Shop.

The incorrect behaviour for the former piece might be because it has "armor" in its key - that might be triggering code that should be used only for the basic class-specific gear (which should be locked if you don't have cheaper items in the set).

**Comment by paglias** [comment]
cc @negue

**Comment by Alys** [comment]
> The incorrect behaviour for the former piece might be because it has "armor" in its key

Or it could be because the item is part of a set, maybe that's confusing the code. 
```
website/common/script/content/gear/sets/armoire.js:378:  jeweledArcherArmor: {
website/common/script/content/gear/sets/armoire.js:383:    set: 'jeweledArcher',
website/common/script/content/gear/sets/armoire.js:822:  jeweledArcherHelm: {
website/common/script/content/gear/sets/armoire.js:827:    set: 'jeweledArcher',
website/common/script/content/gear/sets/armoire.js:1352:  jeweledArcherBow: {
website/common/script/content/gear/sets/armoire.js:1358:    set: 'jeweledArcher',
```

**Comment by Alys** [comment]
This is still happening except that now the error message you see says just that you can't buy the item, without giving a reason. 

Once you have previously obtained an Armoire item, you should always be able to buy it back with gold, assuming you have enough gold. There should be no lock conditions on it.

**Comment by negue** [comment]
I especially tested this in the fix #10601.

- added myself an armoire item
- lost it during de-lvl
- could re-purchase it again no issues there


I guess its time to refactor the `checkMarketGearLocked` logic prevent something like that happen again

**Comment by Alys** [comment]
Which items did you test? It still fails for armor_armoire_jeweledArcherArmor but not necessarily for other Armoire pieces.

**Comment by Alys** [comment]
Ah, it's probably because the canOwn function has upper case J when it should be lower case. There's only two pieces affected by that:
```
$ grep -r canOwn website/common/script/content/gear/* | egrep "_[A-Z]"
website/common/script/content/gear/sets/armoire.js:    canOwn: ownsItem('armor_armoire_JeweledArcherArmor'),
website/common/script/content/gear/sets/armoire.js:    canOwn: ownsItem('head_armoire_JeweledArcherHelm'),
```
