### ISSUE TITLE
Daily checkboxes appear to roll back when using IE11 client

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10653]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 90145e45-71ca-4c83-8ecf-703e40ccdcda
  * Browser: IE11
  * OS: Windows (presumably)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

User reports the following flow:

1. Log in to Habitica using IE11.
2. Check off a Daily.
3. The Daily appears to uncheck itself--goes back to unchecked state.
4. Refresh or sync. The Daily is checked, suggesting that the server state is correct but the client displayed it incorrectly.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

User is planning to check Developer Tools later--if we hear from them, we'll add the details here!

**Comment by Zian** [comment]
Demonstration:

https://youtu.be/HqLPvlfyjXI

**Comment by VickyKoblinski** [comment]
I'd like to take a look at this ticket.

**Comment by paglias** [comment]
@VickyKoblinski thanks! let us know if you have any question

**Comment by beffymaroo** [comment]
A possibly related report from a player using Microsoft Edge browser:

"Edge is doing a thing, not consistently, of course, where it doesn't properly display a checked item. The screenshots show a Daily, but it does this with To-Do's, Habits, and checklist items. If the checked task is supposed to give rewards, it will display those (not shown here), but then display the reward being deducted. I don't know if it affects the displayed amount of gold; I haven't checked that.

This is in Edge, Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134, on Windows 10.

I opened the browser earlier this morning, after my custom day start, so it didn't have to check the undone Dailies for yesterday. In between then and now, the browser was closed and the computer was shut down and restarted.

In this case, I checked the top Daily, waited for the purple progress bar to run across the top, then checked the next Daily. The screenshots show what happened. I opened Habitica in Chrome (for some reason, it opens on the settings page and I have to click on Tasks) and both checked Dailies show properly as checked.

It also does that "session outdated" thing a lot, almost in between every check, even if I've just opened the page or just refreshed or synced."

In addition to this report, I did find syncing to be somewhat slow when I tested on Edge although I could not replicate the un-checking effect in the RYA modal.

**Comment by VickyKoblinski** [comment]
Thanks, I'll look out for it and test to see if this fix helps with that. But it sounds like it may be a different issue.

**Comment by Zian** [comment]
Some more findings.

If you disable browser caching, then the problem goes away completely.

No errors are generated when the error occurs. The below text  is the full IE11 console output from loading the entire website.

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: habitica.com
HTML1300: Navigation occurred.
File: habitica.com
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: habitica.com, Line: 1, Column: 1800
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
undefined
SEC7118: XMLHttpRequest for https://api.amplitude.com/ required Cross Origin Resource Sharing (CORS).
File: habitica.com
SEC7118: XMLHttpRequest for https://payments.amazon.com/cs/uedata required Cross Origin Resource Sharing (CORS).
File: habitica.com
SEC7118: XMLHttpRequest for https://coin.amazonpay.com/cs/uedata required Cross Origin Resource Sharing (CORS).
File: habitica.com
SEC7118: XMLHttpRequest for https://coin.amazonpay.com/rb/checkStatus required Cross Origin Resource Sharing (CORS).
File: habitica.com
SEC7118: XMLHttpRequest for https://payments.amazon.com/merchantAccount/AMQ3SB4SG5E91/accountStatus?countryOfEstablishment=US&ledgerCurrency=USD required Cross Origin Resource Sharing (CORS).
File: habitica.com
SEC7118: XMLHttpRequest for https://fls-na.amazon.com/1/batch/1/OE/ required Cross Origin Resource Sharing (CORS).
File: widgets
SEC7118: XMLHttpRequest for https://fls-na.amazon.com/1/batch/1/OE/ required Cross Origin Resource Sharing (CORS).
File: widgets
SEC7118: XMLHttpRequest for https://fls-na.amazon.com/1/batch/1/OE/ required Cross Origin Resource Sharing (CORS).
File: widgets

**Comment by beffymaroo** [comment]
@VickyKoblinski Are you still working on this ticket?  Let us know when you have a moment. Thank you!

**Comment by VickyKoblinski** [comment]
@beffymaroo Yes! I'm sorry for the big delay here. I'll look at this further tomorrow and update you with my status.

11/6/2018 - I have Habitica successfully running locally now
11/8/2018 - Having issues with Habitica client talking to server, reported problem in Aspiring Blacksmiths to get help

**Comment by shanaqui** [comment]
Hi @VickyKoblinski! Do you still want to work on this issue?

**Comment by shanaqui** [comment]
I'll set this back to help wanted since there was no reply. :)

**Comment by veeeeeee** [comment]
Closing since IE is being discontinued in favor Microsoft Edge. We don't have the resources to support more than MSFT does, unfortunately.
