### ISSUE TITLE
Strange behavior with some emoji in task titles

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10654]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Some emoji, when added to a task title, don't consistently display as the graphical character. They'll instead turn up as the English emoji string... unless, perhaps, you add a _different_ emoji to the line, at which point they display. Such as:

🤝 shows up as "handshake"
👊 shows up correctly as the punch emoji
🤝🤝 shows up as "handshake handshake"
🤝👊 shows up correctly as both emoji

**Comment by kartikpandey2** [comment]
hey,
Can I take this issue .?

**Comment by paglias** [comment]
sure @kartikpandey2 , thanks!

**Comment by kartikpandey2** [comment]
@SabreCat  can you tell me which file is responsible for emoji issue .?

**Comment by kartikpandey2** [comment]
Strange behavior with some emoji is because of CDN

![screenshot 91](https://user-images.githubusercontent.com/20434963/44957846-b236f700-aef4-11e8-9565-0e839194017b.png)

src for handshake emoji : https://s3.amazonaws.com/habitica-assets/cdn/emoji/handshake.png
is not working.
@SabreCat  @paglias

**Comment by SahajR** [comment]
This is related to #9128 .
Some emojis lack images in your AWS bucket

**Comment by beffymaroo** [comment]
@kartikpandey2 Are you still working on this issue? Please check in when you have a moment. Thank you!

**Comment by SabreCat** [comment]
@beffymaroo Actually, this is something we have to fix on our end. I'll assign it to myself.

**Comment by SabreCat** [comment]
Duplicate of #9128 and #10927

**Comment by tog22** [comment]
Thanks so much for looking into this @SabreCat! Are you still planning to work on this under either of those issues? It's a major pain
