### ISSUE TITLE
When cleared, the reward price shows 1.0 instead of empty, which can be confusing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10660]
Reported by Il Mago:

> Bug (display bug?) : when editing a reward, if you delete the content of the price field it appears written there 1.0, which can be misleading because if you see it and think you have already written in it it will seem strange to have the notice you need to write in it, also because with low connection the notice doesn't appear immediately

Confirmed by me, screenshot:

![image](https://user-images.githubusercontent.com/8144640/44959140-f53b9f00-aee1-11e8-9ec3-c172728895cb.png)

**Comment by paglias** [comment]
1.0 is the placeholder text, which is lighter than the usual text... maybe we can make it even lighter if it's being confused @Tressley ?

**Comment by shanaqui** [comment]
I think people are likely to expect it to stay empty, based on Il Mago's reaction. But it's true that on my screen at least (I have a blue light filter on) the placeholder text looks the same shade as the normal text.

**Comment by majestic-owl448** [comment]
@paglias : the text is black only if you have the cursor inside the price field, if instead the price field is unselected then the colour of the text inside it is grey, and at my eye it seems the exact same grey of the placeholder text

**Comment by Tressley** [comment]
Yeah, I can see how this is confusing. Cost starts with a default value of `10`, but when deleted has `1.0` as the placeholder. Inputs don't hide the placeholder until they take an initial value, so I don't think there is a state where the input is empty. The user will either have a value or see the placeholder.

For a solution -- I think the placeholder should just read "Enter the value". We don't need to worry about placeholder:active contrast for now.

**Comment by JesseRatt** [comment]
Hi, I am somewhat new at blacksmithing, so I thought this would be a good practice bug to fix, I have fixed it in my local build, I just did it for practice. But I see that there is no updates in 15 days, could I pick this up as my first bug to fix?

**Comment by paglias** [comment]
@JesseRatt yes, go ahead! and sorry for the late response

**Comment by JesseRatt** [comment]
I went with @Tressley 's suggestion but made it "Please Enter a Value" instead of "Enter the value", hope that is ok.

**Comment by Tressley** [comment]
Thanks for the suggestion @JesseRatt! I prefer keeping placeholders shorter, if possible, so let's go with "Enter a Value."

**Comment by JesseRatt** [comment]
No problem. I'll fix it and resubmit.  @Tressley

**Comment by JesseRatt** [comment]
Updated @Tressley , am I right to assume I don't need a new pull request?

**Comment by paglias** [comment]
@JesseRatt yes, you don't need a new PR, I'll check it tomorrow but it looks good!
