### ISSUE TITLE
My Guilds page shows "You aren't member of any Guilds" message while loading

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#10662]
### Description
The [My Guilds](https://habitica.com/groups/myGuilds) page displays a "You aren't member of any Guilds" message while it is loading my guilds from the server, which is kind of confusing (especially if the loading takes longer than a second for some reason). 

I think it would be better to display either nothing or similar "Loading..." text as the Discover Guilds page while the network request is pending, and only show "You aren't member of any Guilds" message after the request has finished and we actually know the user is not a member of any guilds.

I can make a PR for this if it's OK.

**Comment by paglias** [comment]
A PR would be great @cvuorinen :)

@Tressley what do you think?
