### ISSUE TITLE
Party creator leaving the party

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#1066]
An interesting issue discovered by accident:

1) I created a party
2) A friend joined the party
3) I left the party, friend stayed in the party
4) I created a new party
5) Friend left the old party
6) I tried to invite that friend to the new party, but the system stated that that person is still in another party or was already invited
7) To get an invitation, that friend had to create her own party, leave it and only then the system was able to forward the invitation

**Comment by StanLindsey** [comment]
Thanks for this report!

**Comment by AdrienLemaire** [comment]
I also accidentally left my party, and had to get invited by one of my buddies. Please make your system intelligent to find the party owner, for the day he gets some features to manage the party:
- take the oldest member A, check if he was invited by any member B
- if A invited, and member B is part of the party => B is party creator
- If A invited and not member B in party, or if A not invited => A is party creator

thanks !

**Comment by lefnire** [comment]
this should be fixed now with new groups system (which encompasses parties & guilds), re-open otherwise
