### ISSUE TITLE
There is no (single) Slavic language!

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#1067]
I wasn't sure where to put this, but as a linguist, I consider this an issue. Slavic languages are a whole family of languages that include Russian, Polish, Ukrainian etc., I'm not sure where you got an idea to put Slavic as a locale for HabitRPG. Did you mean Slovenian (sl) or Slovak (sk)?

**Comment by StanLindsey** [comment]
Ah, this will be semi my faulty. The Trello card had "Slavic" as a language to-do. I couldn't find the ISO code which completely makes sense now. 

I'll remove it from [the Trello card](https://trello.com/c/SvTsLdRF). We've already got Russian, Polish & Ukrainian on there so until somebody requests any extra languages it'll stay as is.

Thanks @Czuken !

**Comment by mczuchnowski** [comment]
Always happy to help :)
