### ISSUE TITLE
Award winner displays to those who are not challenge creators

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10678]
citrusella posted in Report a Bug:

> On the participant progress display on challenges, should the "award winner" button be visible to all or just the challenge owner? I can see it on the progress window for challenges I don't own. It doesn't work in that instance, so it's not, like, a scary bad fix-it-now thing, but...

Have not tested, but didn't want it to get lost before we have chance.

**Comment by Alys** [comment]
To replicate this bug, go to any challenge that you are not the owner/creator of, click on this dropdown and any one of the names: 
![image](https://user-images.githubusercontent.com/1495809/54066924-3d1df300-4284-11e9-805e-83daa420d718.png)

and you'll see this:
![image](https://user-images.githubusercontent.com/1495809/54066921-2a0b2300-4284-11e9-8b62-3b2121dcaad8.png)

The "award winner" button should appear for only the challenge owner (known as `leader` in the code) AND moderators and staff (anyone with the `admin` flag - you can see sample code for allowing leader and mods to manage challenges by looking at the challenge delete code).

**Comment by HydeHunter2** [comment]
I'd like to take this
