### ISSUE TITLE
Achievement modals generate broken static page links

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10675]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

A user in the Report a Bug Guild has reported that while we don't currently have specialized landing pages for different events, achievement modals still create URLs expecting them to be present:

>Sora （そら） (30647f40-eeb7-4d3a-a52a-40491b3eab84): "Hi. I'm japanese user. When I got a new achievement, I tweet it on the share button. but the URL(https://habitica.com/social/achievement) in this tweet transfer to 404 not found page（https://habitica.com/static/not-found）. is this a known issue?"

Eventually we would like to re-implement a sophisticated sharing setup with intelligent landing pages, but in the meantime we should certainly not be providing broken links for users to post to social media.

**Comment by jdsandifer** [comment]
I'm interested in helping with this issue. Is there a specific resolution in mind? That is, it sounds like we would want a more generic link that works. What would that be - the main website? Or is there a landing page designed for people who have friends using the app already? (I'm new to the project.)

The links could just be removed, but I imagine that could go against one of the purposes of having people share their progress... (to encourage people to check out the app).

**Comment by SabreCat** [comment]
@jdsandifer A simple link to the main page would be fine for now!

**Comment by jdsandifer** [comment]
Great, I'll take this one!

I have a little more to read in the Blacksmithing guide and then I'll get started.

Can you point me to the general area of the repo where I will find the code that handles the achievement modals? I can dig until I find it, too, but would love to save some time if you happen to know where that code is.

**Comment by jdsandifer** [comment]
Nevermind about pointing me in the right direction - the codebase was easy to navigate. It looks like website/client/components/achievements/achievementFooter.vue has the links I'll need to change on lines 73-75.

I'll spin up a local install to confirm the issue, make the changes locally, and verify they correct the issue.

**Comment by SabreCat** [comment]
Thankya! Sorry we missed your earlier message, but I'm glad it worked out. Note you can also check in on the Aspiring Blacksmiths guild for help with Habitica development!
