### ISSUE TITLE
amount to sell, maximum possible to sell, sell value/price are cached after selling one type of items in the Market

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10687]
Steps to show/reproduce bug:

1. Go to the drawer in the Market.
2. Find two items that you own a **different** number of (e.g., you might have 5 Wolf Eggs and 7 Tiger Cub Eggs).
3. For the item that you own **less** of (Wolf Eggs in my example), sell 2 of them (it can be any number more than 1, but I'm using 2 as an example).
4. Click on the second item (Tiger Cub Eggs).
5. **Observe that the amount to sell has already been set to 2**. It should default at 1. This is the first bug.
6. Use the arrow buttons to increase the amount as far as it will go.
7. **Observe that you cannot increase the amount to the full maximum you should be allowed to - you're given the maximum from the first item that you sold.** I.e., in my example, when selling Tiger Cub Eggs, the maximum will be set at 5. It should be set to 7. This is the second bug.

I.e., after you've sold one type of item, the number to sell and the total number permissible to sell are saved in the form for the next type of item you want to sell. They should not be cached like that.

---
EDIT:
In addition, the sell value (price) is cached as described in https://github.com/HabitRPG/habitica/issues/10720

**Comment by JesseRatt** [comment]
I'd like to attempt to fix this one. I have fixed some "first issue" bugs that were already assigned just as practice. I think I could handle this one.

**Comment by Alys** [comment]
@JesseRatt Thank you, please do! 

I don't think this will make any difference to the solution but there's actually been another report of this with a detail about a part of the behaviour that I hadn't noticed (the cached amount wasn't actually applied when selling): https://github.com/HabitRPG/habitica/issues/10708
"Quantities seem to persist when selling items, but do not actually persist"  -- "When you sell a second item, the sell dialog quantity box will indicate the quantity you sold last, but will only sell 1 item."

**Comment by JesseRatt** [comment]
@Alys Not sure who the right person is for this. There is something weird in Vue, where the v-model property for amount to sell is not being updated in the front end. Is it permissible to destroy the sell modal vue component on exit, so it loads a new one each time? I am researching how v-model wouldn't be working while I wait for an answer.

**Comment by JesseRatt** [comment]
Probably don't need to destory it after all, seems to be related to this: https://github.com/buefy/buefy/issues/401

**Comment by JesseRatt** [comment]
Seems to be related to bootstrap vue b-input not working with v-model...looking at some possible related bugs.

**Comment by paglias** [comment]
@JesseRatt destroying the modal every time is possible but expensive so better not to do it. I think you have 2 solutions here: modals fire `hide` and `show` events when they're shown/hidden so you could listen to them and reset the values to the initial ones on hide or on show.

The other option is to watch for changes in the `item` computed property and when it changes, reset the values. Otherwise it seems (but I haven't tried) that this event is called when the item changes https://github.com/HabitRPG/habitica/blob/develop/website/client/components/shops/market/sellModal.vue#L155

**Comment by JesseRatt** [comment]
@paglias Thanks. I think I almost have a work around. I won't need to destroy. Basically, its not just a matter of updating it, but the fact that selectedAmountToSell is NEVER bound to the b-input. If you select 4 eggs, it only sells one. selectedAmountToSell never changes from 1. So I am looking at how to work-around using v-model to bind it.

**Comment by JesseRatt** [comment]
It now actually sells the amount you see in the front end, I'm just trying to figure out how to manually reset it to one when the form reloads. I thought I could use this.$refs but it doesn't seem to let me access the value with that.

**Comment by JesseRatt** [comment]
Problem seems to be how to update a DOM item without using v-model. I though this.$refs would let me but it doesn't seem to like value property for binding in that direction. I will work on your suggestions @paglias

**Comment by JesseRatt** [comment]
I haven't made any progress fixing this, I am going to try to implement the slider in a different way.

**Comment by beffymaroo** [comment]
@JesseRatt Are you still working on this issue? Let us know when you have a moment. Thank you!

**Comment by JesseRatt** [comment]
Sorry I started a new job and haven’t had anymore time

**Comment by Alys** [comment]
Just to confirm, this is still happening, and in addition, if you accept the default value, the actual amount sold is just 1 as reported by @Chachee4 (77ac774b-4663-44a9-b00f-826b5a901767):

'After I select 2 or more in the "How many items would you like to sell?" box and move to a different egg or potion, the number (of items) remains the same in the new window, but if I select sell, it only sells one item. This means I have to click the up or down arrows every time I switch eggs or potions even if it I want to sell the same number as the last. For example: I want to sell 2 dragon eggs. I select 2 and sell 2 eggs no problem. But then I want to sell 2 wolf eggs. The wolf egg window still shows "2" in the "How many items would you like to sell?" box but when I click sell, it only sells one wolf egg.'

**Comment by JSn1nj4** [comment]
@Alys, after re-reading, it does seem like this issue contains information related to #11038. I'm confirming that it does seem like the price for 1 item does get cached, though not in the item object that's loaded into the modal. Somehow it's just the value shown in the modal that's cached. Looking into this.

Please feel free to close that other issue that was opened as a result of my bug report. And thanks for inviting me to jump in on this.

**Comment by JSn1nj4** [comment]
It looks to me like the entire `item` is being cached. The item name in the modal is updating, but this is contained directly in `itemContextToSell` instead of in the `item`. The value from `item.notes()` (shown under the item name) is also cached, showing a description of the first item clicked.

**Comment by JSn1nj4** [comment]
@Alys I think I found the issue preventing some things from updating in that modal. Looking to see if some related issues are fixed now too.

The only thing I'm not sure about is whether that `v-once` directive was important.

**Comment by JSn1nj4** [comment]
@Alys I'm not seeing your original reported issue anymore locally. Can you confirm?
