### ISSUE TITLE
Site Down all Day - Please fix so I don't die.

### ISSUE THREAD

**Issue by WhitneyFox** [HabitRPG/habitica#1068]
I'm going to die again if I can't get in today. That will be the 3rd time due to bugs.

**Comment by switz** [comment]
Sorry for the downtime. I've gone ahead and rebooted the machine. It should be back up already.  

We're working on upgrading Habit to the newest version of Derby. Hopefully once we are able to do that, most of these downtime issues will fade away. The new version of Derby will allow us to horizontally scale instances very easily - something that is not possible right now.

**Comment by switz** [comment]
Also, if habit is ever down. Try https://beta.habitrpg.com - it's hooked up to your account so any changes you make will be reflected on both sites.
