### ISSUE TITLE
Clicking + in habits SUBTRACTS from experience

### ISSUE THREAD

**Issue by Catmagnet** [HabitRPG/habitica#1069]
Yesterday my dailies never updated.  Today, when I clicked on a + in habits, it _subtracted_ from my experience rather than adding to it.  So now instead of almost being ready to level up at 350 (I think I had about 326 points), I have fewer than 300 points, and since I was out of town and couldn't do some of my dailies, I'm afraid I'll lose too much health!

**Comment by Catmagnet** [comment]
I just clicked on one of my To Do's, and it ALSO subtracted from my experience!  So I tried rebooting my page and got the "server is experiencing issues" page.  Not sure if the problem is being fixed or if the issues caused my problem.  Will try again later.

**Comment by lefnire** [comment]
still a problem? probly caught server on downtime. also, unfortunate bug but - make sure you don't have habit open in multiple browsers / computers

**Comment by Catmagnet** [comment]
Thanks! I've never seen it again. I never have Habit RPG open in multiple
browsers, so I'll remember not to do that.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
