### ISSUE TITLE
Text overlapping in Russian version

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10692]
From Report a Bug:

> KarmaSquared (b0d7a5e4-48ba-46ab-9bf9-b5c468e0c280) 
> Hello! Reporting a UI issue. PC + Russian interface. Go to Shop - Quests and at the bottom see the scrolls for quests (like cheetah, guinea pig etc). The boss HP text and bosses actual HP (number) is merged on top of each other and not readable

> Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) 
> Here's a screenshot of what @KarmaSquared reported, just in case.

![scr](https://pasteboard.co/HEsYMb1.png)![hesymb1](https://user-images.githubusercontent.com/1495809/45722640-ac2d5f80-bbf0-11e8-95c4-ca184c8b8980.png)

**Comment by paglias** [comment]
I think this should be moved to Transifex as an issue under the corresponding string, not much we can do from here

**Comment by Alys** [comment]
The problem is that the website code doesn't allow the element to expand to be large enough to hold the translated text. It could happen in other languages too where the translation is longer than the English version.

**Comment by fimion** [comment]
If the pop over's `dd` and `dt` classes were changed to `col-6` in stead of `col-4` and `col-8` this would give more space.

The other option would be to implement a flex-box styling that would allow them to grow or shrink as needed, though this would also potentially cause the boss power and star rating to line up correctly.

**Comment by negue** [comment]
@Tressley what do you think of increasing the width of the label ? as @fimion mentioned

**Comment by Tressley** [comment]
@negue -- I think increasing the width of the label would help, but I'd be interested in a tooltip that could grow or shrink as needed.
