### ISSUE TITLE
Fix display issues in mobile browsers

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#10695]
List of fixes, so that we can link users to a working settings page

- [x] Make banner for paused dailies display correctly
- [x] Display settings pages in one column instead of two.

**Comment by majestic-owl448** [comment]
Other things that could be considered:

often the modals are a nightmare to close (once I was blocked there trying to tap anywhere on the margins to close one until I figured out that as they have the little cross in the corner on the website I could use the same corner to close them - it was a profile modal and there it is not visible)

Scrolling through tasks, you need to use the margins of the screen or you will end moving the tasks around

**Comment by phillipthelen** [comment]
The modals are a good point, since these can pop up on every page. However regarding the tasks the focus right now is on the settings page, since we will send users to that page from an email. We want to work on improving the mobile website soon though!
