### ISSUE TITLE
State of Dailies does not change in Group Plan taskboard

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#10690]
When an assigned user (or any user) in a Group Plan completes a Daily that they are able to claim, the state of that Daily does not change on the Group Task board. E.g. the color stays the same, the streak count does not change, and the Daily remains in the "Due" tab rather than the "All" tab. Refreshing on the part of either party involved does not resolve this.
![group_task_board_view](https://user-images.githubusercontent.com/9218855/45653977-acade500-ba8e-11e8-8463-4862ee6261a9.png)
![assigned_user_view](https://user-images.githubusercontent.com/9218855/45653990-b1729900-ba8e-11e8-8067-e650d47ae0a8.png)

**Comment by kirsty-tortoise** [comment]
This behaviour just doesn't seem to be implemented, see the code that handles shared tasks.

https://github.com/HabitRPG/habitica/blob/71c0939a1595872096dcb0c12947b048d0b125dc/website/server/libs/groupTasks.js#L43-L56

The code only handles Todos. Habits, Dailies and Todos with the default "recurringCompletion" are independent for everyone assigned, and seem to be more like challenges that members of the group can join.

Possibly this behaviour either needs changing or needs to be made more clear to users.

The issue I see with making group Dailies possible to complete is that I'm not sure when a group would cron, and I'm not sure how it would handle users with different cron-times / timezones.

**Comment by RodEsp** [comment]
Has this actually been fixed? I'm seeing the same behavior on the group plan I just bought.
Could I suggest just allowing the group leader to select when a group would cron or by default do it on the leader's timezone?

**Comment by Alys** [comment]
@RodEsp This hasn't been fixed. When a fix is made and approved, you'll see the "open" button at the top of this issue change to "closed", and then the fix will appear on the website in about a week (the delay is for extra testing to be done on a staging server).

For feedback about Group Plans, including suggestions, you might like to email the staff at admin@habitica.com . My personal feeling (not an official answer) is that we possibly wouldn't change how cron works because that could have a significant negative impact on how Habitica works for any group members who are in a different time zone to the leader or who have different usage patterns, however if you email the staff with a description of what you are hoping to achieve with that feature, there might be an alternative that would do what you want.

**Comment by RodEsp** [comment]
Hmm... I thought I had seen this was closed... sorry! I might take a stab at fixing this then if that's alright.

After the proper discussions with the staff, of course.

**Comment by Alys** [comment]
If you'd like to fix the problem described in this issue, that would be great! You can start now without further staff discussion since it's been marked as help wanted by beffymaroo, but comment here if you have questions or want extra feedback.

**Comment by RodEsp** [comment]
Heya @Alys, sorry but I'm actually not going to be working on this.

**Comment by Alys** [comment]
@RodEsp No worries, thanks for letting us know!

**Comment by MeanderingCode** [comment]
I have created draft PR #11179 to add this functionality, as well as "uncompleting" Todos and Dailies.

The design of the implementation does the following:
* "Single" Shared Completion Dailies are marked completed for all assigned users when one assigned user completes
* Master Daily on Group Task Board is marked complete when one assigned user completes
* Dailies and Todos can be "uncompleted", updating/syncing that Task to assigned users and the Master Task
* Completed Dailies due/not due filters work in Group Task Board list

The way I have implemented updating Single Shared Completion Dailies on other user's lists is to mark them completed, without scoring. This has the following implications:
* The user who completes the Daily will score the task
* Other users will see the Daily is completed, will not score the task, will not lose their streak or take damage

One thought I had was to break the streak of the users who did not complete the single completion shared daily. This would create some competition among assigned users to be the one to maintain their streak, but might also disincentivize people who don't have a streak.

Another thing I am thinking about is Group Task scoring. Adding streak counting should be easy enough, though I haven't looked at the scoring functions, themselves, closely enough to think about what Party/Group scoring could be. I like the idea, though.

I would love feedback on the way the feature should work (as well as general JS and habitica-centric code feeback). I am not sure I am done with the feature, but wanted to put a draft up to get feedback.

**Comment by MeanderingCode** [comment]
One group tasks incentive, i think, could be to earn gems for the group.

Damage from unfinished dailies is already distributed, at each user's cron, in the work I did above. Rewards (XP, GP, drops, and damage to bosses) are also already included via the scoring by the member who completes the task (incentivizing members to do the tasks).

As gems can be awarded in challenges, etc, from the group's gem bank, it may be a good collective reward for doing well over time.

The simplest way I see to do this is to use something like streak achievements. It would be relatively simple to keep a streak counter on tasks (including habits, which are currently completely ignored in the `handleSharedCompletion()` code) and to calculate "perfect days". Adding a meter of some kind, like XP or HP, would be more complicated, but I would be willing to do the work if there was a feature idea around group rewards and "damage" that was worth it.

A simple gem reward system could look something like the following:
* All task types have streaks counted in the same way as individual ones: up on completion, down on cron without completion when due
* Cron for this happens at the leader's cron. A group cron setting could be added as an enhancement, if it made sense
* Gems are found in the same fashion as streak achievements: during [the leader's] cron, any streak at a multiple of 21 finds the party a gem

Additionally, there could be mechanisms for buffs on the party. I don't know about buffs much yet, but I'm thinking of the Rogue's Stealth. If buffs already apply to the party (which they do?), then this could easily just apply the party's stats directly.

Thoughts?

**Comment by SabreCat** [comment]
Closing this as it's a feature request rather than a bug. We are working on it, though!
