### ISSUE TITLE
WEB [Nov 2] Implement modal that forces users to change username

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#10697]
Once we release the username feature, users have to set/confirm their username

Fixes needed from review:

- [x] Allow modal to grow correctly to accommodate validation errors
- [x] Check on why z-indexing issue sometimes recurs
- [x] Implement modal stack quick fix suggested by Matteo
- [x] Move email validations to mixin using `validator` library https://github.com/HabitRPG/habitica/pull/10757#commitcomment-31038859
- [x] Remove unnecessary CSS prefixes https://github.com/HabitRPG/habitica/pull/10757#commitcomment-31038852
- [x] Allow length-1 usernames https://github.com/HabitRPG/habitica/pull/10757#pullrequestreview-166752463
- [x] Try another modal stack fix, sigh
- [x] Only import relevant methods from `validator`

**Comment by Tressley** [comment]
**Default:** https://zpl.io/aMvwPW3
**Error States:** https://zpl.io/brEA8LW

**Comment by Tressley** [comment]
Putting this back into Next Up due to updated design/copy.

**Comment by saraolson** [comment]
reviewed this-- only problem i found was when other modals follow it, it appears again for a second before dismissing (happened every time). or sometimes, its dismissed automatically by a certain following modal (only happened once).

**Comment by saraolson** [comment]
noticed that while autocomplete doesnt initially show before you type 1 character, if you type 1 character then delete it, it stays showing, reverting back to just displaying the 5 most recent chatters.

ideally if you type 1 character then delete it, the auto-complete window goes away until you type another character

**Comment by saraolson** [comment]
@SabreCat the image for the veteran pets on the forced modal isn't showing for me

**Comment by saraolson** [comment]
Also continuing to have modal stack issues, posted video in deploys.

**Comment by Tressley** [comment]
I was testing the new social user flow today and was prompted with both the Justin and forced username modal. Is that correct or is it just a lingering modal test?
