### ISSUE TITLE
Frontend changes for upcoming Username changes

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#10694]
For the upcoming username changes we still need the following changes:

Settings Page:
- [x] Allow users without local authentication to set a username
- [x] Remove Section with login name and email and put those values into the input fields themselves
- [x] Add option to change display name (below the part to change username)

General
- [x] Change text occurences of "Login name" to "Username"

**Comment by paglias** [comment]
Can be closed?
