### ISSUE TITLE
Quantities seem to persist when selling items, but do not actually persist

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10708]
> _MaxHedrm (b7fd010e-bf83-47af-a2a1-70144c224b93): "I was just cleaning up some things and noticed 2 bugs with the sale of food/eggs/potions.
> 1. When you sell a second item, the sell dialog quantity box will indicate the quantity you sold last, but will only sell 1 item.

[The second I could not replicate so haven't put on Github.]

Verified by me.

**Comment by Alys** [comment]
We have part of that but reported at https://github.com/HabitRPG/habitica/issues/10687 and I've added a comment with the extra information.
