### ISSUE TITLE
No easy way to see FAQ in other languages (missing feature from before Vue redesign)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#10710]
It used to be possible to see the FAQ (or overview, probably also other static pages) in other languages by adding ?lang=[iso code] to the end of the address. This was particularly useful for Socialites, because the FAQ are in the same order across languages AND you could open one question (eg "...static/faq#task-color"), add ?lang=zh (etc) to it, and the open question would remain open. 

Now, the only way to see the FAQ in other languages is by actually changing your language settings to the target language, which would make it potentially difficult to find the right question again, especially if it's a language with a different writing style.

**Comment by citrusella** [comment]
I think there was also a dropdown somewhere on the FAQ and/or static site that changed the language for you if you didn't know the URL bit.

**Comment by imnuvi** [comment]
Hi team.
Is this issue still available to be picked up? if yes, I would like to work on this.

**Comment by CuriousMagpie** [comment]
We're closing this for now.
