### ISSUE TITLE
cron failing to complete due to version error

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10711]
We have a verified report of cron not producing a quest progress message in party chat for a player who was in the quest, was not resting in the inn, and who did cron with a value in user.party.quest.progress.up recorded in Amplitude. Loggly showed a version error for one of their Dailies. This used to happen often but it's rare now so I thought it worth recording the details. I suggest that if we see any other instances, we could add them here to track how often it's still occuring.

The player is CinCrisis (faea8a98-ed8e-447d-8a32-b51500f1d706). They reported the problem in the Report a Bug guild at 2018-09-20T18:03:43.367Z

Amplitude shows this for the missing cron;
```
User Properties
AmplitudeUser ID faea8a98-ed8e-447d-8a32-b51500f1d706
AmplitudePlatform Web

Event Properties
category behavior
cronCount 706
loginIncentives 516
progressDown -0.057980966200000005
progressUp 661.728820743
resting false

Other
Client Event Time Sep 20, 6:00:22 pm UTC
```

There's no matching system message in party chat.

Loggly shows this (https://habitica.loggly.com/search#terms=faea8a98-ed8e-447d-8a32-b51500f1d706&from=2018-07-20T00:00:00.000Z&until=2018-09-22T23:08:57.571Z&source_group=&event=0adf7a17-bcff-11e8-8092-12b233ae723a,1537466421839,137567592219900439 ):
```
POST
originalUrl:/api/v4/cron
timestamp:2018-09-20T18:00:21.839Z
fullError: message:No matching document found for id "53f73b9f-5661-416c-a9b3-9cec8ed473ae" version 887
name:VersionError
version:887
modifiedPaths:["value", "streak", "history", "nextDue", "updatedAt"]
```

**Comment by SabreCat** [comment]
Closing in favor of keeping the discussion at #10806 etc. These all seem to be variations on the same theme.

**Comment by Alys** [comment]
There's another verified report of cron not producing a quest progress message in party chat for a player who was in the quest, was not resting in the inn, and who did cron with a value in user.party.quest.progress.up recorded in Amplitude. Loggly showed a version error for one of their Habits at the exact time that cron happened. User ID fd1917b1-20f5-42ee-baeb-ebed34d7ae82

```
httpCode:500
isHandledError:false
level:error
message:VersionError: No matching document found for id "14fb8460-f187-4122-9fe9-583d56bceaca" version 178 modifiedPaths "counterUp, history"
    at VersionError.MongooseError [as constructor] (/usr/src/habitrpg/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at new VersionError (/usr/src/habitrpg/node_modules/mongoose/lib/error/version.js:18:17)
    at generateVersionError (/usr/src/habitrpg/node_modules/mongoose/lib/model.js:395:10)
    at model.Model.save (/usr/src/habitrpg/node_modules/mongoose/lib/model.js:449:28)
    at /usr/src/habitrpg/website/transpiled-babel/middlewares/cron.js:158:47
    at Array.forEach (<anonymous>)
    at cronAsync (/usr/src/habitrpg/website/transpiled-babel/middlewares/cron.js:157:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
method:POST
originalUrl:/api/v4/cron
timestamp:2019-11-09T21:33:50.088Z
```

There's also some other reports of VersionErrors in https://github.com/HabitRPG/habitica/issues/10806 - my fault for logging them there not here.

I'm not reopening this because we have https://github.com/HabitRPG/habitica/issues/11059 open for a fix; I just wanted to record this case of it since it happened from a Habit not a Daily. I've edited the top post in https://github.com/HabitRPG/habitica/issues/11059 to say it can happen for Habits too.
