### ISSUE TITLE
Clicking does nothing until refresh

### ISSUE THREAD

**Issue by Bokai** [HabitRPG/habitica#1071]
Very rarely can I use habitRPG on the first visit, as all buttons do not work. Refreshing (sometimes repeatedly) fixes the problem. This includes the Death notice and profile, but not Bailey. I'm on Chrome.

**Comment by thegoodwifey** [comment]
I'm having this issue too, really frustrating

**Comment by ghost** [comment]
Same here. I'm also working on Chrome.

**Comment by lefnire** [comment]
Yeah, due to resetDom() after cron, which breaks bindings. Without calling
resetDom() however you don't see the updates to colors and avatar stats.
What I should do is do a refresh-page on cron. All 3 situations suck,
hopefully this will be solved in Derby 0.5

**Comment by mbridgham** [comment]
I have this problem, too.  Generally, however, if I wait a bit or refresh as others have it starts working.  Sometimes I have to click multiple times on a daily to get it to "stick".

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
