### ISSUE TITLE
Sell modal for items in Market doesn't reset correctly between items

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10720]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you sell several items in the Market with different values (that is, Hatching Potions with different rarities and Gem prices), the sell value doesn't update correctly when you move from one item to the next. If you select a Golden Hatching Potion first, for instance, it'll show all other potions you select within that session as being worth 5 Gold. Selling them produces the correct Gold amount from the server, but the client appears to be in a state of misleading confusion.

The quantity spinner also doesn't seem to reset correctly when opening several different items. If you sell 5 Golden Hatching Potions, then open up your stack of 3 Basic Hatching Potions, the spinner will still appear to be set to 5. Selling from there will only sell 1, however.

**Comment by Alys** [comment]
The quantity spinner not resetting is recorded at https://github.com/HabitRPG/habitica/issues/10687 

I suspect that the other part of this issue will also be fixed by @JesseRatt 's proposed solution there (note that they're asking for feedback about that; I'm not replying since I'm not strong in Vue) so I'm putting this on hold so we don't get two competing fixes. It should be taken off hold if I'm wrong or if the fix for that other issue doesn't pan out.

**Comment by Alys** [comment]
I've added a note about the sell value being cached to https://github.com/HabitRPG/habitica/issues/10687 so I'm closing this issue.
