### ISSUE TITLE
Contrast very low on reward control area

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#10721]
(Was asked by Alys to post here when I asked the best place to bring this up in Aspiring Socialites; spent a few days seeing if I could find other *glaring* issues (there are other places on the website I'm pretty sure also fail [WCAG (Web Content Accessibility Guidelines) AA contrast minimums](https://www.w3.org/TR/WCAG/#contrast-minimum), but the reward column was the most problematic and I didn't manage to get the chance to see if there were other especially bad areas in contrast or other accessibility)

The better part of a week ago, there was discussion in Aspiring Socialites about the similarity in color between tier 7 and the moderator color (though there are other non-color indicators, which helps on some level). That inspired me to run the site through a colorblindness simulation, at which point I remembered I'd thought a few times that the reward price area (the "checkoff" section of the reward) had very low contrast between the yellow price and the slightly paler yellow background, so I included it in the Imgur album I made of screenshots I took from colorblindness simulations: https://imgur.com/a/J7OtRGQ  (That was mostly comparison of tier colors since I was still doing it mostly out of curiosity when I started; the reward price is at the end and wasn't put through as many tests. The extensions I used are mentioned in the album description.)

After that, I got interested in some overall accessibility so I tried running the site through a few accessibility check extensions (specifically, [this](https://addons.mozilla.org/en-US/firefox/addon/wave-accessibility-tool) and [this](https://addons.mozilla.org/en-US/firefox/addon/tota11y-accessibility-toolkit)) and my browser wasn't having it so I didn't get other types of accessibility information (or much info about other low contrast areas).

However, I was concerned enough that I did put the values from the reward column's text and background color into a website and found out [its contrast ratio is approximately 1.59](https://contrastchecker.com/?c=ffa623&b=f3e6d5). (That's using the hex color I got from the eyedropper in Firefox's site inspector since the actual value used for the color is translucent so [this other site I used that allows for that kind of value](https://contrast-ratio.com/#%23FFA623-on-rgba%28255%2C%20217%2C%20160%2C%200.32%29) couldn't give anything firmer than between 1 (which would mean the background and foreground are the same color) and 4.72 (which would be a AA pass at the very least for any size). ...That feels like a functionally useless assessment.)

A ratio of 1.59 is below the [WCAG contrast ratio AA minimum guideline of 4.5 for that text size](https://www.w3.org/TR/WCAG/#contrast-minimum). ("That text size" being "smaller than 18pt" (or 14pt-in-bold).)

**So this was all a long-winded way of saying**: It might be hard for some users to differentiate the text of the reward price from the background due to its low contrast (I even have problems with this sometimes and I don't have any vision or color things).

(Also, to speak to the discussion that sparked this post, [the contrast ratio between tier 7 and mod is 1.07](https://contrastchecker.com/?c=277eab&b=167e87), but they're also not foreground and background for each other, just hard to tell apart if you disregard (or aren't acquainted with) what the different shapes next to each one mean.)

I feel like this is a relatively non-understandable ramble, so please let me know if anything need to be cleared up.

**Comment by citrusella** [comment]
Unrelated to the specific contrast issue above but related to contrast in general, someone on Trello mentioned the mod tools being hard to read due to contrast in [this comment on the accessibility card](https://trello.com/c/pxTcbKuD/381-accessibility-settings#comment-5bc71b5651d61f7bc2ca7494).

**Comment by paglias** [comment]
Ping @Tressley

**Comment by Tressley** [comment]
Hey @citrusella -- I really appreciate you taking charge and running through to identify some of the problem areas with respect to WCAG AA. We're aware of some of the lingering accessibility issues, but for color blindness and tiers, we tried introducing icons as well as a tooltip when hovering the display name.

In the mean time, I doubled back to correct the lingering issue on custom rewards to get that to use the yellows that were originally designed. Hopefully this helps alleviate some of the strain until we can prioritize a full-site accessibility audit.

**Comment by GiacomoLaw** [comment]
Is there any update on this?

**Comment by Tressley** [comment]
@GiacomoLaw -- The original issue regarding the contrast in the Reward area was fixed. As for a full accessibility audit, that is a very large, time-intensive project that the Habitica staff plans to tackle in the future when it can be properly prioritized. Thanks for checking in!

**Comment by GiacomoLaw** [comment]
Awesome thanks for the update 🙂

**Comment by SabreCat** [comment]
Sounds like the specific issue described in this ticket was addressed, so closing!
