### ISSUE TITLE
Discrepancy in sorting between Market and Equipment

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10728]
Per Il Mago again:

> In the Market if I sort by an attribute I have lower attribute first (https://snag.gy/zMOPoW.jpg), in the Equipment section it is instead higher attribute first

**Comment by kirsty-tortoise** [comment]
Can I have a go at this?
I suspect sorting with higher attribute first is generally more useful, so would be better in both cases?

**Comment by kirsty-tortoise** [comment]
Actually I've changed my mind as I'm going to be going to university soon and won't have time to do anything after that, so if someone else wants to have a go then that's good with me.

**Comment by trvrfrd** [comment]
I'll take a stab at this since it seems to be open again.

Proceeding under the assumption that equipment should be sorted by highest attribute first in both places, but happy to discuss/be corrected if anyone think's there's a better way to do it.
