### ISSUE TITLE
Cannot delete chat messages or challenges in Safari desktop/iOS

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#10736]
After reporting in the **Report A Bug** guild, Alys asked me to post my issue here:

Ever since the recent downtime I can no longer delete my own messages in the guilds. Safari (Version 12.0 (12606.2.11) on OS 10.12.6) just chokes when I hit the delete button. (This also happens on mobile in Safari on iOS 12). 

> Please include anything from Safari's JavaScript / Developers console (if it has one?) and any extensions you're using in Safari.

I'm not using any extensions. I don't have the foggiest idea how to access the console. There is no option to do that in any of the menu drop downs for Safari.

I've done a hard browser refresh and cleared the site data. No dice. I also cannot delete challenges. Everything works in Chrome. After I click 'Delete' in Chrome I get a confirmation dialog box, whereas Safari just does ... nothing when you hit the little trash can icon on a message. It was working before the downtime a few days ago.

**Comment by majestic-owl448** [comment]
I have Safari on the phone and I have the same issue, but it usually return working after I reload (I have no idea if I can use developer console on the phone though)

Anysia, you can try looking at here if it helps you in accessing developer console: https://support.apple.com/it-it/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac

**Comment by paglias** [comment]
@Anysia thanks for the report. I wasn't able to reproduce the issue with Safari on mac os Mojave. Can you try this: open the Habitica website, right click somewhere and on the menu choose `Inspect element`, a panel will open with several tabs, choose `Console`. Then try to delete a message or a challenge, if anything appears in the console could you post it here? Thanks

**Comment by ghost** [comment]
Thanks @Ieahleen, that helped. @paglias Nope, the page just freezes (spinning beach ball). Nothing new appears in the Console.

**Comment by ghost** [comment]
Hmm. Now I can't buy the October backgrounds either in Safari (I buy them every month and last month was fine). Same behaviour as when I try to delete. Chrome is fine.

Edit: Can't change classes either. Basically anything with a confirmation dialogue (which does not show up) doesn't work anymore.

**Comment by paglias** [comment]
@Anysia do you have any extension enabled? Unfortunately I'm still unable to replicate. I'd try with an Private window or by deleting the cache

**Comment by ghost** [comment]
I don't use extensions. It was also a problem on mobile (iOS), which doesn't allow extensions. It seems to have "fixed itself" in the last couple weeks, I think (I don't do that actions that trigger the problem very often). I have to close a challenge tomorrow, so I will check if it's still an issue on Safari but I don't think so. I'm now getting the pop up that I wasn't getting before asking to confirm actions in Safari and I think that was the point it was getting stuck at before.

**Comment by SabreCat** [comment]
Sounds like this hasn't been happening for a while. Closing!
