### ISSUE TITLE
Automatically pinned gala gear does not show as pinned in the market

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10743]
BrightBold (6cb6695a-abf5-48bf-bd02-9d2ac12c32ca): "You may already be aware of this (although I didn't see it on github), but automatically pinned gala gear doesn't show as pinned in the market. 

I changed classes and went to the equipment shop to pin some past-years' gala gear for repurchase. None of the gear there showed as pinned so I was skimming for anything that said "Autumn" in the description and clicking the pin. Partway through this process I noticed that one of the confirmation messages said I had *unpinned* the equipment. I realized I had been clicking the 2018 autumn gear along with earlier years, because the pin did not appear selected so it looked unpinned. But in fact it was already pinned, so clicking the pin icon unpinned the item instead of pinning it. I confirmed this behavior with a second class change and saw again that, while the 2018 gala gear is in fact pinned on the Tasks page, the items do not indicate they are pinned on the Market page (whereas items I pin manually do have the pin icon highlighted, as you would expect.)"

Confirmed by me on a testing account:

![image](https://user-images.githubusercontent.com/8144640/46635195-63136000-cb4b-11e8-8df6-8fd590e9f223.png)

They actually also have the unpinned icon colour when you mouse over in the rewards column, as opposed to e.g. the Enchanted Armoire, which has the pinned icon colour. 

![image](https://user-images.githubusercontent.com/8144640/46635251-9fdf5700-cb4b-11e8-9454-a5c42107f60a.png)

**Comment by Alys** [comment]
Some background information for any contributor who works on this:

When a player manually pins items, they're stored in the player's account in the `pinnedItems` array like this:
```
"pinnedItems": [
	{
		"type": "armoire",
		"path": "armoire"
	},
	{
		"type": "potion",
		"path": "potion"
	},
	{
		"path": "premiumHatchingPotions.Glow",
		"type": "premiumHatchingPotion"
	}
],
```

However automatically pinned items are not put in that array. Instead there's code that displays them in the Rewards area as if they were pinned. If the player chooses to unpin those items, they're stored in the player's account in the `unpinnedItems` array:

```
"unpinnedItems": [
	{
		"path": "gear.flat.shield_special_fall2018Healer",
		"type": "marketGear"
	}
],
```

**Comment by kirsty-tortoise** [comment]
I had a look and can see the line of code that needs changing to fix this, can I take this?

**Comment by paglias** [comment]
Sure!
