### ISSUE TITLE
When de-registering facebook, button does not update

### ISSUE THREAD

**Issue by bean5** [HabitRPG/habitica#10755]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)
### General Info
  * Browser: Chrome
  * OS: Ubuntu

### Description
When I click "De-register from Facebook" I got a success message, but the button did not update until I refreshed the page. All other changes I tested worked as expected, although the page has a lot of "Submit" buttons.

**Comment by aneesh4995** [comment]
Can I work on this issue if this is still open @paglias

**Comment by paglias** [comment]
sure @aneesh4995 !

**Comment by shanaqui** [comment]
@aneesh4995 Hi! Are you still interested in working on this? Please let us know! :)

**Comment by aneesh4995** [comment]
the development environment is not working on my computer so if anyone wants to take it please do

**Comment by bencelaszlo** [comment]
@Alys can I get this issue?

**Comment by Alys** [comment]
@bencelaszlo Sure, thank you! Although you might want to check first on the habitica.com site to see if it still is an issue since it's rather old. If you don't have a Facebook account that you're willing to use to test it with, post here and I will test. It'd also be worth you/me testing if the same bug happens with Google authentication.

**Comment by bencelaszlo** [comment]
Okay, so I'm just setting up the development environment, I will likely start to work on this issue tomorrow. Of course, I will check the existence of this bug first.

I can have a throwaway account for this and yes, I can have a check on the Google-auth, too.

**Comment by Alys** [comment]
@bencelaszlo Awesome, thanks so much! Comment here if you have questions or tun into trouble.

**Comment by bencelaszlo** [comment]
Can you give some help? How can I set Facebook and Google API keys and secrets?

Both Google and Facebook de-register buttons have this problem in the version hosted at "habitica.com". I can't test it locally without these.

Edit: sorry, I found it.
