### ISSUE TITLE
path `preferences.pushNotifications.onboarding` was not saved, as it's a protected path.

### ISSUE THREAD

**Issue by bean5** [HabitRPG/habitica#10756]
### General Info
  * Browser: Chrome
  * OS: Ubuntu

### Description
* Navigate to https://habitica.com/user/settings/notifications
* Click some of the checkboxes to enable push for everything, such as "Invited to Quest"

#### Console Errors
```
path `preferences.pushNotifications.onboarding` was not saved, as it's a protected path.
```

**Comment by paglias** [comment]
thanks for the report @bean5 ! it's been fixed and will go live soon
