### ISSUE TITLE
Available gear rewards suddenly overpowered

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#1075]
After refreshing the page (because of lack of response to clicks), my available rewards suddenly include Red Sword, Plate Armor etc. (while I currently have no armor on me and a basic sword in my hand).

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
