### ISSUE TITLE
Skills used on the party are not forwarded by the groupChatReceived webhook

### ISSUE THREAD

**Issue by natfarleydev** [HabitRPG/habitica#10751]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: ecc53331-4aa1-4b02-b3b3-e794d0ff6827
  * Browser: N/A
  * OS: Various Linux

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Using the `groupChatReceived` webhook does not forward system messages about skills. Currently, there is no way to use a webhook to forward on notifications about others using skills in the party.

(Side note: it's a little unintuitive that system messages to the chat are not forwarded by the `groupChatReceived` webhook, but I understand from @SabreCat that work is being done to revamp how these notifications work anyway.)

(Quest notifications are also not forwarded, but there was the previously undocumented `questActivity` webhook which provides this function, see #10750)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
N/A

**Comment by paglias** [comment]
This is due to the function `group.sendGroupChatReceivedWebhooks` that's used to send the webhook being called from the `sendChat` route instead of from `group.sendChat` which is used to send system chat messages

**Comment by natfarleydev** [comment]
What is the preferred behaviour here? Should we add `group.sendChat` to the `group.sendGroupChatRecievedWebhooks` hook or create a new hook? (This is my personal preference; it means that *everything* that happens in the party chat is forwarded)

**Comment by paglias** [comment]
Yes, I think we should change the existing hook to forward system messages as well

**Comment by natfarleydev** [comment]
I'm happy to implement this if it's fine with staff.

**Comment by paglias** [comment]
go ahead @nasfarley88 !

**Comment by nasfarley88** [comment]
There is a fix for this at https://github.com/nasfarley88/habitica/tree/groupchatrecieved-webhook-fix but github won't let me create a pull request since one 'already exists', but the link to it does not.

Any suggestions?
