### ISSUE TITLE
Usernames are automatically confirmed for all new local auth players with no visibility warning

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10766]
_(This is rewritten from my post in a staff channel a bit over a week ago.)_

The registration form for the local authentication option doesn't tell players that their username will be public, so new players might still be entering their real names without being willing for those names to be visible to other players. The username field on the registration form is still labelled "Login Name" so that could be taken as a hint that it will be private. 

In addition, all new accounts made recently have `flags.verifiedUsername` set to true automatically (i.e., the usernames of new accounts are being automatically confirmed). If I understand correctly, this means that all new players since that change went live will never see any reminders to consider changing their username, and when the usernames become visible, they'll see their login name become public without warning. I'm guessing there might be Bailey messages before then but not all players will read those.
   
The Settings page does say "We will be transitioning login names to unique, public usernames soon..." but new players might not have a reason to look at that section of the Settings page, and even if they do, they might not realise that the transitioning process has started. Their username is marked there as confirmed but that might not be meaningful to them since it doesn't say that the confirmation is related to public usernames ("Your username, Alys, is confirmed!")

Possible suggested changes that could be considered for this:
- Send an email to all new users since the automatic confirmation change went live (won't help if they mistyped their email address).
- Change `flags.verifiedUsername` to false for all new users since the automatic confirmation change went live so that they can benefit from the enforced reminders that their Login Name will become public.
- Perhaps consider removing the code that automatically confirms usernames on new accounts.  
- Put a message on the registration form to tell players that their Login Name will be public and so that they have a warning that they might not want to use their real name. For example, this message "Username must be 1 to 20 characters, containing only letters a to z, numbers 0 to 9, hyphens, or underscores, and cannot include any inappropriate terms." could have this added to it, maybe at the start for extra visibility: "Your Username will be visible to other players if you post any messages or join any Parties or Guilds."
- Perhaps change the "Login Name" label on the registration form to "Username" or even "Username (publicly visible)".

_I'm marking this as suggestion-discussion for the staff to consider._

**Comment by saraolson** [comment]
this doesn't concern me too much right now because we have been making their login name public for a long time by automatically setting it at their display name

**Comment by saraolson** [comment]
i do think we should have changed the placeholder text to username instead of login name when we made the change. it looks like we did on the login screen, and on the mobile apps, but missed it on the landing. however, we have been making their login name public for awhile by automatically setting it as their display name, so i feel updating the field to be username should cover this issue.

**Comment by SabreCat** [comment]
Fix for the placeholder is on its way live shortly. I missed it on my grep because the strings there were all hardcoded English, not translation tokens... -_-;

**Comment by majestic-owl448** [comment]
I just created a new account with "Log in with Google", Username is `hb-4oy1q0mj3e5z00wbk`
As a new user I imagine I would like to be asked to set that to something intelligible, instead of trying to search were it is as first thing after posting in the Tavern or in a guild (I see a future of new users panicking on that and socialites trying to explain how to change it to every newbie that create an account with the social options)

**Comment by Alys** [comment]
> we have been making their login name public for awhile by automatically setting it as their display name, so i feel updating the field to be username should cover this issue.

That label change won't be visible to any of the players who registered in the recent past; it only takes effect from now on. In addition, it still doesn't make it clear that the username will be public - that's not necessarily something that you expect when you sign up for a task management site.

It's not uncommon to see a new player posting in the Tavern using their real name to ask how they can change it, and then they post again later with a different name. Anyone who does that without knowing about the upcoming username feature will find that their real name becomes public again without warning. That's not a good experience for them and is a privacy concern.

Players who joined since automatic confirmation of usernames went live have basically the same privacy issue that older players had. We've covered the case of older players by notifying them about the change and by forcing them to confirm their name before it becomes visible. However for players who've registered over the past couple of weeks, the current code just allows their login name to become public without warning.

Changing that would be pretty easy. All that would be needed would be to temporarily turn off the code that automatically confirms usernames for new players (then turn it back on after the registration form explains the public aspect of it), and do a migration for recent new accounts to set the verifiedUsername flag to false (it will be easy to identify which accounts need that).

@Ieahleen also makes a good point about social auth users - having a random username become visible unexpectedly isn't as nice for them as it could be, and it would result in a large number of questions that the socialites would have to answer.

**Comment by saraolson** [comment]
we had an issue to fix the flow for social usernames before the actual change goes live to address the problem of social users getting stuck with something intelligible. we just finished designs for justin to ask upfront in the first screen of onboarding like so:
<img width="197" alt="screen shot 2018-10-24 at 2 47 44 pm" src="https://user-images.githubusercontent.com/12453119/47454031-2034c780-d79c-11e8-91d1-ec722b758e79.png">

**Comment by paglias** [comment]
I think this has been fixed, if you sign up now you're asked to confirm your username
