### ISSUE TITLE
Everything has been wiped

### ISSUE THREAD

**Issue by MdmeLibrarian** [HabitRPG/habitica#1076]
When I tried to log-in this morning (which failed multiple times before I reset my password), I was presented with a message saying that I had died, and with only the original default tasks, dailies, to-dos, and rewards. My habits and habit histories are gone, my gear is gone, and my pets are gone. 

I was away at a weekend convention for a few days, and my character was 'checked - in' at the tavern to preserve my health while I was away, which may be the root of the problem, but I have had trouble logging in before when not on my main computer.

**Comment by lefnire** [comment]
@MdmeLibrarian do you have your original [user id](https://github.com/lefnire/habitrpg/wiki/User-ID)? I wanna see if [this](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found) was the issue

**Comment by MdmeLibrarian** [comment]
I do. I have two that might work. I had originally been using a Facebook login, but had it manually switched over to username/password.

Email is best? I think I still have your email from last time.

**Comment by lefnire** [comment]
sure, [email me](mailto:tylerrenelle@gmail.com)

**Comment by lefnire** [comment]
we solved his offline, was a user transfer issue
