### ISSUE TITLE
filters on Challenge page and Group Plan Task Board for Habits, To-Dos, Rewards don't work (sort of works for Dailies)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10771]
_Edited by Alys 2019-12-04._

As described in detail below, most of the normal task filters (due, completed, etc), aren't of much use when looking at a Challenge's main page ([e.g., this page](https://habitica.com/challenges/14cf33bb-1e97-4a31-8f3d-49c0f9781d3a)) or at a Group Plan's "Task Board". The fixes described below should be done for both locations.

This does NOT apply to the screens you see when you are looking at an individual member's Challenge progress - those screens should keep all the filter options because they help the Challenge owner assess the player's progress.

For any Blacksmith wanting to work on this issue, [Using Your Local Install to Modify Habitica's Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) shows you how to add a Group Plan to a guild or party. 

Below are the problems that exist for filters. The bolded options are my preferred suggestions for fixes. There's been no objections to them since I bolded them, so they're probably the best fixes to do.

- [ ] For Habits, the "Weak" and "Strong" filters don't work (they show all Habits just like the "All" filter does). <strike>They should either be modified so that they show appropriate Habits based on the progress from all Challenge participants or</strike> **the "All", "Weak", and "Strong" filters should be removed**.

- [ ] For To-Dos, the "Scheduled" filter doesn't work (it shows all To-Dos). I think this one is actually useful so **I suggest keeping the "All" and "Scheduled" filters and making the "Scheduled" one show only To-Dos that have a due date.**

- [ ] For To-Dos, <strike>I'm not sure if the "Completed" filter works. If it did work, you'd want it to show To-Dos that ALL Challenge participants had completed. If that's too difficult,</strike> **the "Completed" To-Dos filter should be removed from the page**.

- [ ] For Rewards, the "All", "Custom", and "Wishlist" filters all show the same thing (all custom rewards). Wishlist rewards don't exist for Challenges so **the filters should be removed for Rewards**.

- [ ] For Dailies, the filters are working correctly except that they filter Dailies into due and not due based on the time zone of the person who created the Challenge, not the person looking at it, so it can be misleading. <strike>I'm not sure if we should try to do something about this, or leave it as it is so that at least the Challenge owner can use it, or</strike> **remove the filters for Dailies**.

---

Anyone testing a proposed fix should check that:
- [ ] the fix works on a Group Plan's Task Board page (e.g., a page with a URL like this: https://habitica.com/group-plans/85dd1be6-336b-4e53-9949-2c09150b4035/task-information)
- [ ] the fix works on a Challenge's main page (e.g., a page with a URL like this: https://habitica.com/challenges/14cf33bb-1e97-4a31-8f3d-49c0f9781d3a)
- [ ] the fix does NOT change the screen that shows an individual Challenge participant's progress (that screen should still have all the filters)
- [ ] the fix does NOT change the user tasks page (https://habitica.com/)

**Comment by Alys** [comment]
<strike>I'm thinking that for consistency and code simplicity (and therefore reliability) it's best to remove all filters from the challenges' page. Only some of the filters would be useful there if they worked and none are essential. Most challenges are small enough that you can easily find a task or review them all without needing filters.</strike>  _EDIT by Alice 2019-11-26_: I no longer think this. :)

**Comment by majestic-owl448** [comment]
There a couple of things to consider in my humble opinion:  
- all dailies should always be shown (so "All" Filter always active)  
- when viewings the progress of a participant is important to view both active and completed todos for eventual extra notes (as there is not an "All" Filter for todos, but for this situation it could be possible to introduce it, or keep "Active" and "Completed" filters when viewing a participant progress)

**Comment by Alys** [comment]
This also happens on the Group Plans task board (Rosamund17's report is below) so I'm about to update this issue's title and top post to include Group Plans.

I've also updated the top post to highlight in bold the options that I think would be best. If there's no disagreements in a week or two, I'll mark this as help wanted for those bolded changes.

It's important to note that these changes should be made to **only** the Challenge/Group Plan task overview pages, not to the screens you see when you are looking at an individual member's progress. As @Ieahleen says, it's very helpful to be able to use all the normal filters when examining one player's progess. The top post didn't make that distinction at all so I've edited it for that too.


@Rosamund17 (869b70d3-cb58-4650-b8b5-dbbb46032aec) reported:
_"Hi - the "scheduled" filter on To-Dos is not working in the group view. It does not filter out unscheduled To-Dos."_

**Comment by Alys** [comment]
I've marked this as help wanted and rewritten the top post to clarify the desired fixes. I've also included a short checklist of things that should be checked when testing a PR (e.g., make sure that the normal user tasks page isn't affected). I'm happy to help with testing if desired.

**Comment by veeeeeee** [comment]
Closing this issue in favor of starting a new one without extraneous Group Plan details, as filters for Group Plan (now Teams) have been removed.
