### ISSUE TITLE
survey troubles and account name/password not being recognized

### ISSUE THREAD

**Issue by LordTovel** [HabitRPG/habitica#1077]
I go to take the survey and it takes me to a place that I am not logged in on for some reason. so I go to log in and to my surprise my account is not recognized, nor is my E-mail address when I try out the send new password option.

**Comment by lefnire** [comment]
Do you have your original [user id](https://github.com/lefnire/habitrpg/wiki/User-ID)? I wanna see if [this](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found) was the issue

**Comment by LordTovel** [comment]
yes, my user id is ffe7b389-2d99-4d75-9a6f-6040005884ae

**Comment by lefnire** [comment]
can you try now? you could have just caught at a bad time, your auth looks fine in the database

**Comment by wizonesolutions** [comment]
@lefnire I think @LordTovel is talking about login to the community site. are we syncing logins yet?

**Comment by lefnire** [comment]
no, the accounts aren't synced. commuinty website separate from habitrpg website

**Comment by eru-neo** [comment]
Hi! I took the survey a few days ago, but didn't get my "reward". I copy-pasted my ID (26aeaa79-a23c-40cf-adb1-66b0b618a22f), but I was not logged in the community website... 
It did say "your submission was received" or something of the sort in the end though. Should I just take it again?

**Comment by switz** [comment]
http://community.habitrpg.com/blog/survey-feedback-concerns-quotes-graphs  

> > Firstly don’t worry about having not received your “Helped Habit” gems and achievement; its a manual process which we will be processing on Monday to allow as many people fill out the survey as possible. Make sure to follow us on Facebook and Twitter if you don’t already in order to keep yourselves up to date.

Give us some time, please :)

**Comment by eru-neo** [comment]
Oh, in that case I didn't say anything ^^. Thx for the great work!
