### ISSUE TITLE
Disconnected changes

### ISSUE THREAD

**Issue by fawques** [HabitRPG/habitica#1078]
I think it would be nice to store the changes made while disconnected, and when connected again, update the server with everything that changed.
For example, today I completed a task that gave me an egg (finally!) but my WiFi went down and my task-completion and everything I did after that wasn't saved. When I connected again, I didn't have the egg, and the tasks weren't marked.

What I propose is to save those changes, so that when I reconnect, the server receives everything I did, and updates all the data.

**Comment by switz** [comment]
That's how it works now. However, Racer (the data syncing framework we use) is quite buggy. It's in the midst of a **complete** rewrite from the ground up. This should make it more stable and accurate.

Thanks for stopping by.
