### ISSUE TITLE
challenge achievement going missing

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10788]
From Il Mago / @Ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) who uses the iOS app and website:

"I won a challenge while I wasn't online, and opening Habitica doesn't give any kind of notification about it
I checked the app, before checking the website and that may have deleted the notification, but the app doesn't have a notification for that, so no notification for me."

I haven't replicated (I'm not on iOS). Part of the problem might be that the app isn't yet configured to show challenge achievements but the notification should still remain until it's seen on the website.

I'm labelling this needs investigation.

**Comment by majestic-owl448** [comment]
I am going to do some testing with my test account once I have some time so
I can see if can reproduce it. (the testing account is under Username
testingMago)

Is fine if I post here with future updates?

**Comment by Alys** [comment]
Yes, please do! Thank you!

**Comment by majestic-owl448** [comment]
was something changed? I now just receive the modal after winning a challenge

**Comment by SabreCat** [comment]
With it looking irreproducible nearly a year ago, methinks it's time to close this.
