### ISSUE TITLE
filters in Seasonal Shop broken: only Main-Hand Item is tickable/untickable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10791]
In the Seasonal Shop (https://habitica.com/shops/seasonal ), in the Filter section on the left-hand side, when you try to untick any of the item types, the checkbox for "Main-Hand Item" is the only one that has the tick mark toggled.

This is reporducable even if you have no equipment pieces for sale there.

This does not occur in the filters for the other Shops or the Inventory pages.

_Thanks to The Tryer (106a20b7-4dd3-4bc9-b08a-2281f74819ec) for reporting this in the Report a Bug guild!_

**Comment by kirsty-tortoise** [comment]
Can I try to fix this?

**Comment by Alys** [comment]
@kirsty-tortoise Thank you!
