### ISSUE TITLE
Changing notifications for "kicked from group" fails (protected path)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10796]
> Mattias Willemsen (617d46a0-64b0-4d21-8409-9ff99ec3149b): "When changing my notification settings on the website, I get a red pop-up every time I try to check the Push box for "kicked from group".
> The notification reads: 
> ```
> path 'preferences.pushNotifications.kickedGroup' was not saved, as it's a protected path.
> ```
> 
> No biggie for me, but I figured it might be helpful to report it!"

Confirmed by me in Google Chrome.

**Comment by paglias** [comment]
Fixed, thanks for the report!
