### ISSUE TITLE
[just a fancy feature] Colors in rewards

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#108]
Having rewards with a different background color if the price is equal or less than my coins would be nice.

**Comment by The-Bard** [comment]
Just anything to be a small warning to reward to current gold relation would be nice.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
A variation of #158, which can be voted for here: [Confirmation on Spending Gold](https://trello.com/c/uEo7wjkH)
Noted the idea of shading rewards which cost more than available gold.
