### ISSUE TITLE
Clicking X doesn't dismiss Bailey

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1080]
When Bailey shows up with news, if I close her popover by clicking "close" then the Bailey image goes away until the next update. However, if I close it by clicking the X in the upper right, the Bailey image stays there as if there were still unread updates. This persists across multiple days and readings until I actually click "close." 

This is a pretty minor issue, but it was getting a little annoying before I figured it out. And if it leads to some people having Bailey on their screen constantly, then they'll miss when there actually are new announcements.

**Comment by SabreCat** [comment]
I actually think it'd be cool to have a way to keep Bailey around if you like seeing her there, but something more intuitive than this would be good!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
