### ISSUE TITLE
Add user contributor tier styling to conversations list in private messages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10805]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

While overhauling usernames, we've been trying to more consistently display users' contributor tier colors and icons wherever their display name appears. One place still needing attention is the conversations list in the private messages modal. It's currently possible to style the display names under some situations, but not consistently.

The best solution would be to remove the current conversation list implementation, which relies on data contained in the most recent message of the conversation, with a list that actually queries user records to correctly show display name, username, and contributor tier information for each entry. Given the potentially extensive list of conversations in an active user's private messages, it would also be advisable to lazy-load rather than query an unbounded set of users up-front.

**Comment by SabreCat** [comment]
Some of what's described has been addressed in the recent overhaul of private messages, so the time might be ripe to fix this up!

**Comment by Tressley** [comment]
This is no longer an issue. PMs now display contributor tiers.
