### ISSUE TITLE
Special Pets should not have feed bars

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10801]
_Currently this bug exists only in staging and delta, not production. If possible, it would be nice to have it fixed before it goes into production because it's the sort of thing users will notice and we'd have to handle reports. If it's not possible to fix by then, then when the next deployment from staging to production is made, the Socialites should be told that it's a known error and it doesn't need to be reported when anyone notices it. FYI @SabreCat since you'll likely be doing that deployment. :)_

Special Pets cannot be fed but some of them are displaying feed bars:

![image](https://user-images.githubusercontent.com/1495809/47896930-63d5b280-debb-11e8-8947-dbdf7bfa9d25.png)

The reason that some do not display feed bars is that matching Special Mounts exist, but that should be irrelevant for Special Pets - none of them should look feedable.

Here's how it should look (and how it currently does look in production):

![image](https://user-images.githubusercontent.com/1495809/47896989-97b0d800-debb-11e8-9629-cd813d6052ba.png)

**Comment by Alys** [comment]
I've marked this as help wanted but if any contributors want to work on it, post here and wait for the go-ahead from staff because it's not impossible that staff will fix this themselves. (Posting and waiting is always a good idea but is more likely than normal to be necessary for this issue.)

**Comment by paglias** [comment]
@negue I think it might be due to https://github.com/HabitRPG/habitica/pull/10768, can you give a look?

**Comment by probaton** [comment]
I don't mind taking a look. Obviously don't want to get in anyone's way though, just let me know if no one else can spare the time.

**Comment by negue** [comment]
@paglias will do once I'm home
