### ISSUE TITLE
can't leave guild with group plan: ParallelSaveError 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10814]
Ioannes, Novice Bookworm (43782084-136a-457b-b2e5-f9145f9c23a7) says in the Report a Bug guild:
_"Cant leave guid. An unexpected error occured https://habitica.com/groups/guild/e9000f4c-e4f0-4c37-90b4-131b56f27b3f"_

That guild has a group plan (I have not done any testing to be sure that is related to the bug).

Ioannes, Novice Bookworm is not the leader of the guild, nor a manager.

There are several errors in Loggly such as this one:

```
{"method":"POST", "originalUrl":"/api/v4/groups/e9000f4c-e4f0-4c37-90b4-131b56f27b3f/leave",
"headers":{"connection":"Keep-Alive", "content-type":"application/json;charset=UTF-8", "accept":"application/json,  text/plain,  */*", "accept-encoding":"gzip,  deflate,  br", "accept-language":"ru-RU, ru;q=0.9, en-US;q=0.8, en;q=0.7", "host":"habitica.com", "max-forwards":"10",
"referer":"https://habitica.com/group-plans/e9000f4c-e4f0-4c37-90b4-131b56f27b3f/information",
"user-agent":"....", "origin":"https://habitica.com", "x-user-timezoneoffset":"...", "x-api-user":"43782084-136a-457b-b2e5-f9145f9c23a7",
"x-client":"habitica-web",
"x-forwarded-proto":"https", "x-forwarded-port":"443", "x-original-host":"habitica.com", "x-original-url":"/api/v4/groups/e9000f4c-e4f0-4c37-90b4-131b56f27b3f/leave", "x-forwarded-for":"...", "x-arr-ssl":"...", "x-arr-log-id":"a287e0aa-0822-47de-be6e-00954349102a", "content-length":"53"},
"body":{"keep":true, "keepChallenges":"remain-in-challenges"},
"httpCode":500, "isHandledError":false,
"fullError":{"message":"Can't save() the same doc multiple times in parallel. Document: 43782084-136a-457b-b2e5-f9145f9c23a7", "name":"ParallelSaveError"},
"timestamp":"2018-11-04T13:04:33.384Z",
"level":"error",
"message":"ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 43782084-136a-457b-b2e5-f9145f9c23a7\n at ParallelSaveError.MongooseError [as constructor] (/usr/src/habitrpg/node_modules/mongoose/lib/error/mongooseError.js:13:11)\n at new ParallelSaveError (/usr/src/habitrpg/node_modules/mongoose/lib/error/parallelSave.js:18:17)\n at model.Model.save (/usr/src/habitrpg/node_modules/mongoose/lib/model.js:387:20)\n at model.groupUnlinkTask [as unlinkTask] (/usr/src/habitrpg/website/transpiled-babel/models/group.js:1370:16)\n at <anonymous>\n at process._tickDomainCallback (internal/process/next_tick.js:229:7)"}
```

I have **not** removed them from the guild manually since doing so would prevent the group plan charges being changed. I'm marking this as high priority since the guild leader is paying for Ioannes to stay in the guild.

**Comment by Alys** [comment]
I've marked this as help wanted since if there's a code bug a contributor might be able to find it, but contributors should be aware that the staff might fix this quickly so it's even more recommended than usual to post here before attempting a fix and then wait for a go-ahead message.

**Comment by paglias** [comment]
Should be due to this https://github.com/HabitRPG/habitica/blob/develop/website/server/models/group.js#L1146, if there are multiple tasks the user is saved multiple times

**Comment by Alys** [comment]
As soon as this goes live, the person who reported it should be told they can now leave the guild (important since the leader is paying for them). I'm reopening this to help us not  forget but if the staff would prefer to handle this some other way that's fine with me. :)

**Comment by paglias** [comment]
This is live now, so we should check with the user if the error is gone

**Comment by paglias** [comment]
I'm going to close this as the fix is live and loggly doesn't show similar errors
