### ISSUE TITLE
Changes to Challenge short name (tag name) do not save

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10829]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If, when editing a Challenge, you change the "Short Name" that's used to define the Challenge's tag, the edits do not save to the database. Next time you refresh, the Challenge will still have the old tag.

**Comment by VickyKoblinski** [comment]
Can I try this one?

**Comment by Alys** [comment]
Note that it's intentional that changes to the tag are not pushed out to the players who are already participating so that shouldn't be changed.

**Comment by CuriousMagpie** [comment]
I'll work on this one!
