### ISSUE TITLE
Forgot password does not email me the new password

### ISSUE THREAD

**Issue by Edgar729** [HabitRPG/habitica#1082]
I could not log in to my account so I assumed my password was wrong. I requested a new password and got a message saying "a new password has been sent to ....".

But I didn't receive anything in my email box. When the website was a bit more stable I tried to log in but apparently even though I did not receive my new password it was still reset in the process.

I am using proper capitalization. My account name is Edgar729.

Thank you

**Comment by Edgar729** [comment]
I don't have my id number btw

**Comment by BanktownUSA** [comment]
I'm having this issue as well I couldn't remember what type of caps i used in my screen name. So i thought that reseting my password would tell me. But now I have a reset password and no email. I do have my ID number.

**Comment by Edgar729** [comment]
Help please!

**Comment by lefnire** [comment]
@BanktownUSA can you give me your ID number? @Edgar729 i'm working on you right now

**Comment by Edgar729** [comment]
I don't know what happened but I tried the forgotten password thing again the moment I saw your post and it worked instantly.

Thank you! I am lost without my to do list!

**Comment by lefnire** [comment]
I haven't fixed anything yet, are you sure it's working?

**Comment by Edgar729** [comment]
Well, I am inside my log in screen adding to do's and what not. It looks like it normally does and is running smoothly.

If you want me to get you any info just let me know!

**Comment by lefnire** [comment]
@Edgar729 well phew! Will wait to hear from BankTown

**Comment by lefnire** [comment]
yeah, i think y'all just caught habit on a down time. re-open if still issues
