### ISSUE TITLE
pet feeding behaviour and display problems

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10834]
In the Report a Bug guild, Praxis (0ce6d43b-efa2-45a3-acaa-59daad7d658d) reported the bugs below. **All words in** normal font **below this line are theirs, not mine; my comments are added** _[in italics in brackets like this]_.
Below their report is a related report from Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72).

----

Hi, guys! It seems the Stable was recently changed, and glitches were introduced, sometime between November 1st and today.

When I hatched and raised a full set of Ghost pets and mounts on November 1st, the Stable interface was behaving normally, as it has been for some time: It worked smoothly, quickly and functioned perfectly (I use the web interface).

Today, when I hatched a couple of pairs of matching Gator pets and mounts, the following glitches occurred (all of these were new... and I've raised a LOT of pets):

The initial hatching (upon clicking the black pawprint for the first time) worked normally: Pop-up window with purple button to hatch, pet icon appeared in its proper spot in the lineup.

1) But then the feeding progress bar did not advance when the pet was fed. I had to manually re-synch to get it moving, even though the purple re-synching bar DID move across the top of the page each time (I know enough to wait for this) and even though I got the blue "really likes" confirmation message each time. After I manually re-synched (after about 3-4 feedings where feeding the progress bar did NOT move -- this happened on both pets I tested), then the feeding progress bar continued to advance properly in time with confirmation messages until the pet became a mount.

_[I've replicated everything up to here.]_

2) At this point the normal pop-up annoucing that I had successfully raised my pet into a mount appeared, and I clicked on the purple "onward" button. Then I noticed that the system had automatically equipped the PET that I had just raised into a MOUNT onto my Avatar, substituting it for the pet that I previously had equipped (this happened for sure on the second pet that I tested, not sure about the first one) -- even though now all I really had in my stable was the MOUNT of that color.

_[I can't replicate this (the Pet I just fed to a Mount was not equipped automatically) but this might be an inconsistent bug that depends on other factors. As I'll mention below, there seems to be some other inconsistencies with the new bugs. I suggest we fix the ones that can be replicated and then test again for the ones that can't. The initial fixes might solve the other problems anyway.]_

3) The pawprint position of the pet that I had just raised into a mount was still black (as normally expected) but it had become un-clickable -- completely unresponsive.

_[Confirmed that the pawprint was still shown; at this point it should be an image of the egg and potion. However it wasn't un-clickable for me - I could click it to bring up the modal for re-hatching the Pet.]_

4) When I re-synched, a new (full color) icon of a hatching potion next to a pet egg appeared in the spot where the black pawprint (to hatch a new pet) used to be.

_[Confirmed.]_

5) But alas, we were still not home free! That icon was ALSO completely unresponsive to clicking.

_[Not confirmed. It did respond to my click.]_

6) After I gave the page a full REFRESH (i.e. re-loaded the Stable interface), the pet that I really shouldn't even have (because it was raised into a mount and I hadn't hatched another one yet) was still equipped on my Avatar.

7) BUT! Once I clicked on that new (never saw it before today) color icon of the pet egg next to the hatching potion, I finally got the correct pop-up window with the purple button to click and hatched the pet.

8) At last, the correct pet appeared in its spot in the line-up... displaying the blue star in the upper left corner as though I had selected it (I hadn't) and still equipped to my avatar even though it didn't even truly exist until a few seconds ago.

_[Confirmed. When I adjusted my account in the database to put a pet that I didn't own into my avatar (to replicate Praxis's bug up to this point), and then hatched the pet, it stayed equiped and the star appeared. I suppose this is correct behaviour at this point, although the bug leading up to it wasn't.]_

It looks to me like all this glitchy behavior is the result of adding something that we really didn't need (a colored icon of a pet egg next to a hatching potion instead of the usual black pawprint) -- which I assume was added to make the Stable more "newbie friendly" or maybe just to add "flavor" to the experience (and it is a cute icon, in keeping with the rest of Habitica's lovely artwork).

_[Just noting that the different icons on unhatched pets are intended to make it clear:_
- _which ones are already mounts_
- _which ones can be hatched / rehatched_

_I'd like to suggest that whoever works on this issue writes a brief summary in their PR's description of the different states and what they're meant to represent. We can then use that for testing and we can also document it in the wiki.]_

If these issues can be fixed so that the Stable is once again as smooth and streamlined in its functioning as it was up until very recently, I'll really appreciate it.

Anyway, lots of details here, and possibly pointing to more than one newly-introduced bug in the Stable interface... I hope that this report is detailed and specific enough to help your coders find and fix the problems.

**For what it's worth:** I think the only newbie-related improvement that the Stable really needed was done several months ago: the pop-up announcing that you have raised the pet into a mount (since some people who were new to the process apparently thought that their pet had disappeared). You guys have created a visually and functionally beautiful web interface that is a constant joy to use. Please don't feel any need to keep changing things that are already looking good and working well! :wink:

Thanks so much for your help with these issues, and for all your great work!

_[This is the end of Praxis's report.]_

----

Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) reports:

Out of curiosity, I tried to reproduce the "feeding bar does not advance" part of the bug Praxis described. I couldn't - the bar did advance. 

But when I fed the pet fully, the pop-up that shows on mouse-over of the "you can hatch a pet icon" (cute icon!) still says "click the pawprint", even though the icon no longer represents one.

_[Confirmed - the on-hover text needs to change.]_

**Comment by paglias** [comment]
@negue is this something that could be due to your recent changes?

**Comment by negue** [comment]
my recent fix shouldn't break the feeding at all (rather fix all other possibles issues ^^, now the progress is read per pet-component instead of creating the array outside) - anyway I'll look into it

**Comment by negue** [comment]
@paglias there are some weird state-refresh issues, like its currently built in for example the progress (No 1 of the issues) getting the info right from the state ( `mapState`) but using it as a `computed property` the values only refreshing for already hatched pets, if I transform the computed prop to a `method` it also updates the progress for newly hatched pets (usually the normal computed way should work as expected^^)

and for example when a pet evolved to a mount it couldn't be selected as a mount, only after refreshed, this also seems to be an issue with state-refreshing ..

I'll continue looking into this issue(s)

**Comment by negue** [comment]
2. cant reproduce
3. fixed so that the behavior of 4. shows up
4. the expected behavior
5. can't reproduce (may be fixed ? )
6. can't reprodude this behavior either :(


I did however refactored the `mountItem` (where I had a different wrong behavior that after the hatch it wasn't listed as a mount)

on the technical side: its mostly that `computed` props not getting refreshed (even though the state got new values to work on), so using `methods` it fixes those kind of issues

**Comment by paglias** [comment]
I'm wondering why the computed props are not being refreshed, methods are fine although computed properties are faster

**Comment by paglias** [comment]
Now that some fixes have been merged and deployed can we see if the issues reported above are still present? I can't reproduce them anymore

**Comment by Alys** [comment]
The parts of this that I could replicate before are fixed for me. I'll close this. We will open a new one if other problems are reported.
