### ISSUE TITLE
Pet is gone, and now I have multiple eggs and no potions

### ISSUE THREAD

**Issue by ficklepenguin** [HabitRPG/habitica#1085]
I had a wolf egg and a desert hatching potion. I hatched a desert wolf. When I came back later, my wolf was gone, and now I have seven wolf eggs and no hatching potions.

Also, I lost a level. I'm level 3 from 4.

**Comment by ficklepenguin** [comment]
My user id is 60c09201-b893-41c3-bd34-0b208efb6417

**Comment by lefnire** [comment]
just gave you some gems so you can buy back. we have tons of lost pet / egg duplicate tickets, so closing this one
