### ISSUE TITLE
shadow-mute feature is needed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10851]
Currently Habitica has a mute feature. We want to add an additional "shadow mute" feature. (This comes from a discussion involving beffymaroo and the moderators.)

---

Shadow muting will work in a similar way to muting so here's a brief description of how the existing mute feature works (this feature does not need any changes so this description is just FYI):
- The current mute feature uses the `flags.chatRevoked` attribute in the User model ([user/schema.js](https://github.com/HabitRPG/habitica/blob/9a3cdb5deb6af9054c6566634005bf174f63d880/website/server/models/user/schema.js#L225))
- If a player has that flag set to `true`, then:
   - They are unable to post to the Tavern or public guilds. When they try to they are shown an error message that tells them their chat permissions have been revoked.
   - They can't send Private Messages to any player. When they try to they are shown an error message.
   - They CAN post to their party or any private guild they are a member of.
- A moderator can turn the feature on and off from the [Hall of Contributors](https://habitica.com/hall/contributors) ([heroes.vue](https://github.com/HabitRPG/habitica/blob/9a3cdb5deb6af9054c6566634005bf174f63d880/website/client/components/hall/heroes.vue#L57-L61)) or from icons at the top of a player's profile ([loadAdminTools](https://github.com/HabitRPG/habitica/blob/9a3cdb5deb6af9054c6566634005bf174f63d880/website/client/components/userMenu/profile.vue#L16-L31)).
- To find all relevant code for the existing mute feature, grep the code base for `chatRevoked`. You won't need to change that code but copying some of it will help you create the new shadow mute feature.

---

The new "shadow mute" feature will work in a similar way to the existing mute feature but the player will not see any obvious sign that it's been applied to them.
- [x] It will require a new user attribute `flags.chatShadowMuted` which by default will have no value (as for `flags.chatRevoked`).
- [x] If a player has that flag set to `true`, they will be shadow-muted. When the flag is set to false or does not exist, all shadow muting effects will cease to apply to the player. The effects are described below.
- [ ] The Hall of Contributors and the player profile screen will need to have controls for turning the flag on and off. Copy what's done for `chatRevoked` and use different icons / text. Those controls will be visible to only mods and staff so their appearance won't need any significant design decisions; the contributor that works on this feature can do something simple initially and if we think it's not quite clear enough we'll give feedback about tweaking it.

When a player has `flags.chatShadowMuted` set to `true`, then:
- [x] They CAN send Private Messages to any player. (We might change this later but initially I think it's the best and simplest approach, especially since we want shadow muting to be unnoticable.)
- [x] They CAN post to their party or any private guild they are a member of. Those posts will be seen by party/guild members as normal - no special treatment will be applied to those posts.
- [x] They CAN post to the Tavern and public guilds BUT those posts are automatically hidden at the moment they are created. The posts will still be visible to the player themself and to mods and staff, but to no one else. This can be achieved by setting the post's `flagCount` to greater than 1 (there is already code to hide those messages).
- [ ] When a shadow-muted player posts to the Tavern or a public guild, moderators need to be notified in two ways:
   - [x] an email should be sent to moderators (in the same way that an email is sent when a normal post is flagged)
   - [x] a Slack message should be sent to the moderator Slack "flagged-posts" channel (in the same way that a Slack message is sent when a normal post is flagged)
   - The code for notifying moderators when a normal post is flagged is at [groupChatReporter.js](https://github.com/HabitRPG/habitica/blob/9a3cdb5deb6af9054c6566634005bf174f63d880/website/server/libs/chatReporting/groupChatReporter.js#L52-L72)
   - [x] Something similar can be done for these shadow-muted posts but the email and Slack message must make it clear that the posts have been automatically hidden because the player is shadow-muted.

Regarding setting the post's `flagCount`:
This is the code that hides a post from everyone but mods and the player who posted it when the flagCount is 2:
https://github.com/HabitRPG/habitica/blob/9a3cdb5deb6af9054c6566634005bf174f63d880/website/server/models/group.js#L337
- [x] As you see, currently the value "2" is hard-coded there. It should be converted to a constant and then the constant can be used both there and in the new shadow-muting code

----

_For anyone curious about how this shadow muting feature will be used, moderators are expecting to use it in only very rare, extreme cases. For example, if we're trying to control a persistent troll who is making new accounts to avoid a normal mute, we would shadow-mute them to decrease their impact on the community until staff have had time to set up an IP address ban._

_The primary reason we want this feature is because its code will become the basis of the feature described in https://github.com/HabitRPG/habitica/issues/8063_

_The current `flags.chatRevoked` mute feature will continue to be used in almost all cases where muting is appropriate._

**Comment by wiktordaniec** [comment]
I think I can work on this one. It will take me some time though since I will be working on it mostly during weekends.

**Comment by Alys** [comment]
@andrzejZdobywca That's great, thanks so much! Comment here if you have questions or run into problems or if anything I've written above isn't clear.

**Comment by Alys** [comment]
@andrzejZdobywca Are you still working on this? If you're not, that's fine, just let us know! :)

**Comment by Alys** [comment]
@andrzejZdobywca I'll take this over but if you have any code you'd like to submit, just let us know!
