### ISSUE TITLE
Emoji don't work in tag hover, but do elsewhere

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10856]
> _Shoaling (52d07da8-722d-499e-896e-837b5a47309f): "Emoji don't work in the hovers:
> 
> hover with emoji not working
![image](https://user-images.githubusercontent.com/8144640/48772119-4d04cd80-ecbb-11e8-8319-0bcd960f7be1.png)
"_

Followed by:

> _@Shoaling (52d07da8-722d-499e-896e-837b5a47309f): "@shanaqui : emoji works for tags in other situations:
> 
> ![tags](https://i.imgur.com/MuWzwuL.png)
> 
> ![tags](https://i.imgur.com/Mw5EdxI.png)
> 
> Additionally, if I paste an emoji that Habitica doesn't support, such as 🧽 into my tags, then it works in the hover too.
> 
> I got the idea to add emoji to my tags from one of the Habitica tips that showed up while I was waiting for it to load my tasks."_
>

**Comment by paglias** [comment]
See also #10861. ~Do we want to keep support for emojis in tags @Tressley ?~ Nevermind, i see that emojis in tags are meant to be supported
