### ISSUE TITLE
Ghost pets (13 in stable, 15/90 listed)

### ISSUE THREAD

**Issue by VerbingNouns** [HabitRPG/habitica#1086]
I just hatched a Base Flying Pig and went from 12/90 to 15/90. There are only 13 pets in my stable. Not sure whether other information is relevant.

**Comment by VerbingNouns** [comment]
Okay, I just disconnected from the server, refreshed and lost my flying pig... but still have 14/90 with only 12 pets in the stable. God dammit. :(

**Comment by storian** [comment]
My own stable count does not match the real count.  I know at some point that pets I hatched were dropped somehow, but I wasn't paying close enough attention to give a good description, plus it might have been related to other pet bugs, e.g. receiving multiple potions when "one" dropped - perhaps I used a potion that wasn't supposed to be there.

**Comment by lefnire** [comment]
should be fixed, do a refresh in a bit and re-open if still an issue

**Comment by nextmike** [comment]
Fixed for me :)
