### ISSUE TITLE
Email address display breaks

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10875]
From RaB:

> I don't know that it's a valid email address anyhow, but I've seen email examples (or "blanked out" address names here in the report a bug guild) where the username part ends in a dot breaking the email link display like so:
> 
> @yahoo.com" target="_blank" rel="noopener">.....@yahoo.com [see screenshot]
> 
> Even if the address isn't real, I don't think that should happen. (I know at some point it was happening with all email address links. Similar issue?)

![image](https://user-images.githubusercontent.com/8144640/49116875-d35e7800-f296-11e8-8177-06bfe8f5e1cb.png)

**Comment by SemperDisco** [comment]
@shanaqui How can I reproduce this issue?

**Comment by shanaqui** [comment]
Presumably by posting an email address where the username part ends in a dot as described in the report -- I haven't tested this issue myself, so feel free to let us know if you *can* reproduce it.

**Comment by citrusella** [comment]
It might be reproduceable using any punctuation next to the @ sign from what I just tried in my party chat. (Specifically, I tried t.@yahoo.com, y,@yahoo.com, y-@yahoo.com, and 3=@yahoo.com (though it probably would do the same if it was only the punctuation as well? IDK))

(Also if it's not obvious, I'm the reporter? XP)

**Comment by Alys** [comment]
I'm reopening this because email addresses are still being corrupted in staging:

![image](https://user-images.githubusercontent.com/1495809/52516148-ae608b00-2c71-11e9-9c34-7cf2a7de9874.png)

**Comment by paglias** [comment]
@negue hmm it looks like only some instances got fixed, it fixed cases like `test y.@gmail.com test` but not stuff like `hello@example.com`

**Comment by negue** [comment]
Alright after some hours of hacking with regex, to try having the highlights and also inside the emails... I think this highlight shouldn't be inside an email anyway.

Tomorrow I'll have a rewritten highlight method which only allows normal mentions not emails. (email`@highlight`.com)

**Comment by Alys** [comment]
This is still broken in staging so I'm guessing there must be something different about local installs that allows the fix to work there. `noopener` implies that the conflict is related to markdown conversion. Maybe the markdown library is broken in local installs so no markdown conversion to a mailto link is being done there? I haven't run mine up to check though.

**Comment by paglias** [comment]
@Alys I can check on staging to see what is different than local installs but in the meantime could you post some examples of the test that cause the issues and the results on staging?

**Comment by paglias** [comment]
Actually it looks like staging wasn't properly deployed, I'm pushing it right now again

**Comment by paglias** [comment]
Deployed now

**Comment by Alys** [comment]
The examples and results had been the same as the ones already posted here, however it's working now! Thanks for deploying.
