### ISSUE TITLE
Everything I inputted gone?

### ISSUE THREAD

**Issue by Supajin** [HabitRPG/habitica#109]
Hi, last night I set up my HabitRPG and added a bunch of Habits/Daily/Todos and a Reward. Today I'm looking at it and the default page is there when I first started with the original list of things when I first joined.

Did I do something wrong... or is there a quick fix? Thanks!

**Comment by lefnire** [comment]
no quickfix, migration almost complete

**Comment by Supajin** [comment]
Ah, that's what the migration was for, thanks for the quick response!

**Comment by lefnire** [comment]
yea, this one issue right here is the source of 95% of problems people are
having with the website. super high priority

**Comment by Supajin** [comment]
Sounds like it haha, any ETA on when the migration will be complete so I can start back up :)

**Comment by lefnire** [comment]
server migrated. still some pain points, but much better now - follow up #84
