### ISSUE TITLE
Help with Chrome Extension: Applying Live Changes

### ISSUE THREAD

**Issue by jordanmehravar** [HabitRPG/habitica#10908]
Hello all,

For learning purposes, I'm building a simple Chrome Extension that scores tasks. I notice that my client only makes the changes after being refreshed. Without refreshing the client, the task(s) aren't scored.

How can I make live changes to my client? Do I always have to refresh the page to update my tasks?

Cheers,
Jordan

**Comment by paglias** [comment]
Hi @jordanmehravar, this issue tracker is used for bugs on the website / api not for help requests, I'm sorry. You can try on the Aspiring Blacksmiths guild https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f

But if for client you mean the habitica.com website, then yes, it doesn't have realtime updates so to see your changes you'll have to refresh the webpage / click on the sync button.
