### ISSUE TITLE
apidocs should say how to provide comment when flagging / reporting chat messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10916]
The apidocs for `/api/v3/groups/:groupId/chat/:chatId/flag` should specify how to provide a reason for the flag. If my reading of the associated code is correct, the reason should be specified in a body parameter called `comment`.

Docs to be updated:
https://github.com/HabitRPG/habitica/blob/de0c62a37ff05b63dd3a46ebeb664ba4662eb5b4/website/server/controllers/api-v3/chat.js#L272-L278

Code that references the comment so that you can check my assumption:
https://github.com/HabitRPG/habitica/blob/de0c62a37ff05b63dd3a46ebeb664ba4662eb5b4/website/server/libs/chatReporting/groupChatReporter.js#L47

**Comment by Juliusdotsh** [comment]
Can I take this issue?

**Comment by paglias** [comment]
sure @Juliusdotsh ! let us know if you have any question

**Comment by Juliusdotsh** [comment]
Thanks @paglias I'm fairly new to npm and node in general but watching the code and trying to log the variables i can already assume the that @Alys' fix is correct and needs to be applied only in the comment.
I have only a question that could save me a lot of time, how can i put the backend code in debug? I know that i can debug the frontend from the developer console.

**Comment by paglias** [comment]
@Juliusdotsh the version of Habitica that you run locally is already in development mode, but in this specific case I think that the only change needed is to a comment in the code, not to the code itself
