### ISSUE TITLE
The name of one of my To Dos has disappeared

### ISSUE THREAD

**Issue by KatjeiDa** [HabitRPG/habitica#1091]
One of my To Dos is gone. Even though the square remains it's blank.

**Comment by wc8** [comment]
What happens if you try to edit it, or can you not do that?

**Comment by KatjeiDa** [comment]
When I try to edit it the entry comes up blank. I hoped that it would
revert when I left edit mode but it's still blank.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
