### ISSUE TITLE
'@' in URL is incorrectly treated as a Username signifier

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10924]
If you post a URL that contains an '@' symbol, the website treats the URL as if it has a Username in it and it makes the URL unusable both for reading and clicking. For example, this URL was posted:

`https://medium.com/@schlaf/how-to-conduct-an-annual-life-review-that-will-catapult-you-into-the-new-year-d5aaffebac1f`

This is what the visible portion of the link looked like in the website:

`@schlaf/how-to-conduct-an-annual-life-review-that-will-catapult-you-into-the-new-year-d5aaffebac1f" target="_blank" rel="noopener">https://medium.com/@schlaf/how-to-conduct-an-annual-life-review-that-will-catapult-you-into-the-new-year-d5aaffebac1f`

This is the URL that the link tried to send you to:

`https://medium.com/%3Cspan%20class=`

_EDIT 2020-04-10: See the comments for additional important information._

**Comment by Alys** [comment]
One way to fix this and any other similar problems that might exist would be to limit the parsing of Usernames so that it only occurs if @xxxxx is surrounded on both sides by whitespace or by the start/end of the message.

There might be rare cases where that doesn't correctly handle something that should be treated as a Username (e.g., if a player types two Usernames with no spaces between them  @Alys@ALittleYellowSpider) but I think that's an acceptable risk, especially since some examples of @xxxxx@yyyyy might actually not be intended to be two Usernames.

I'll leave this as suggestion-discussion for a few days to give the staff time to comment and then if there's no objections I'll mark it as help wanted.

---

For the benefit of any contributor who will work on this regardless of what solution is chosen:

This is purely a client-side change - the website's Username parsing code in a vue file is what will need to be fixed.

**Comment by arjunchawla** [comment]
Hi Alys, I am willing to contribute and fix this problem.

**Comment by arjunchawla** [comment]
Please let me know if i should go ahead and work on it.

**Comment by Alys** [comment]
I've thought of one case where you would want the Username to be parsed when it has a character directly next to it on the left-hand side: if the user put the Username inside brackets like "(@alys )"
The best way of handling that and any other cases that we haven't thought of might be to automatically insert a space before any Username when it's been selected from the drop-down list. There's already automatically a space inserted after it.

**Comment by margsliu** [comment]
@Alys
Hello, @pskupinski and I are able to take on this issue and could have a pull request submitted within the coming week. Would it be okay for us to start working on it?

**Comment by Alys** [comment]
@arjunchawla How are you going with this? Do you want to keep working on it or can @margsliu  take it over?

**Comment by Alys** [comment]
@margsliu If you'd still like to do this, you're welcome to take it on. Thank you!

**Comment by shanaqui** [comment]
@margsliu Are you still interested in working on this issue? If so, please let us know!

**Comment by shanaqui** [comment]
I'll set this back to help wanted since there was no reply. :)

**Comment by nathanzhu144** [comment]
@shanaqui 

Do you mind if I work on the issue?  I had some ideas.  :)

**Comment by Alys** [comment]
@nathanzhu144 I've just done some testing for this issue and it looks like the situation is actually a lot better now than it was when this issue was logged - other changes must have improved things. When I make a post containing a URL with an @ in it such as `https://medium.com/@schlaf/how-to-conduct-an-annual-life-review-that-will-catapult-you-into-the-new-year-d5aaffebac1f` the URL works and the only issue is that the `@schlaf` portion has the wrong colour:

![image](https://user-images.githubusercontent.com/1495809/78957850-d1165a00-7b29-11ea-9972-fff7d1ff5bdc.png)

It would certainly be good if the  `@schlaf` portion wasn't coloured like that of course.

However there's actually a couple of other issues related to Username parsing being worked on at the moment (https://github.com/HabitRPG/habitica/issues/11504 and https://github.com/HabitRPG/habitica/issues/12033), and it's possible that fixes made for this issue at the same time _might_ conflict. That might mean that any changes you made for this issue now might have to be adjusted later or abandonded.

I'll leave this marked as help wanted just for now but if you'd still like to work on it given this new information, post again briefly and I'll mark it as in progress for you. You're also welcome to post if you have questions about anything I've written!

(BTW I've removed some previous comments from this issue that were just about earlier attempts to work on it, to help us focus on the active comments. No technical information was removed.)

**Comment by benkelaar** [comment]
@Alys Thank you for flagging this issue! 

I indeed think this would also be fixed by doing this username highlighting as part of the normal markdown parsing/rendering process by writing a dedicated plugin in habitica-markdown.

@nathanzhu144 You're welcome to join our efforts in fixing these rendering problems at the source. I'll throw up an issue on habitica-markdown so we can discuss the approach there.

**Comment by benkelaar** [comment]
@nathanzhu144 I've invited you as collaborator to my [fork of habitica-markdown](https://github.com/benkelaar/habitica-markdown), where I've also created a [branch](https://github.com/benkelaar/habitica-markdown/tree/habitica-markdown-mention-plugin) and [draft pull-request](https://github.com/HabitRPG/habitica-markdown/pull/87) in which we can discuss work in progress.

**Comment by benkelaar** [comment]
@nathanzhu144 The plugin only fixes the frontend part of this equation (the spans), the backend still injects user links if it is an existing user, do you want to take the backend part here as well or shall I look in to it?

**Comment by benkelaar** [comment]
Picking it up since it would be good to reuse some of the code I made in habitica-markdown to unify behaviour in front and backend.

**Comment by Alys** [comment]
@benkelaar thanks! I've marked it as in progress for you.
