### ISSUE TITLE
Staff of Sweetness duplicating part of description

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10929]
Lucas Heim @lucasheim (535a72cc-f949-4ba6-8570-639c5f763da8): "Hello!
The special item "Staff of Sweetness" is duplicating the "Two-handed item." description. Currently, it displays like this:
"This is no ordinary lollipop! The glowing orb of magic sugar atop this staff has the power to make good habits stick to you. Increases Intelligence by 15 and Perception by 7. Limited Edition 2018 Autumn Gear. Two-handed item. Two-handed item."

It seems to be a pretty easy fix, in the locale file the text was put explicitly on the item description, but I think this is added automatically (https://github.com/HabitRPG/habitica/blob/4f3536e88756001d8d1fb3da867a5a0cafbfd337/website/common/locales/en/gear.json)
If it's just this change on all locales, I can try to do it when I get home and issue a PR :)

Happy new year!"

**Comment by lucasheim** [comment]
I'd be happy to do it!

**Comment by paglias** [comment]
@lucasheim thanks, that'd be great :) Let us know if you have any question
