### ISSUE TITLE
UTF emoji are being incorrect replaced with our own (missing) images

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10927]
As reported in the Report a Bug guild by @Pledge (18a6bcb4-601e-4953-a71e-b6387b7f00e4), when UTF emoji characters are entered into tasks or chat messages, they're being replaced by Habitica-hosted images even when those images don't exist. For example, for this task:

```
{
    "_id": "605db73f-d34b-4ef4-899f-95a888c31156",
    "type": "habit",
    "text": "🤖",   //  \xf0\x9f\xa4\x96
    "notes": "Alys this one",
    "userId": "18a6bcb4-601e-4953-a71e-b6387b7f00e4",
    ....
}
```
This is what it looks like:
![image](https://user-images.githubusercontent.com/1495809/50572074-5c238300-0e04-11e9-8718-eed5a0a7c36c.png)

And this is what the broken image points to:
https://s3.amazonaws.com/habitica-assets/cdn/emoji/robot.png 
```
AccessDeniedAccessDeniedED5889D0CE28FDBCnrojHWV/yPHPzhlJqaOd8oVhSvStfbBS7AnbQqV2dnbdSJ4MFt6wbgAkKsdPUYY2a5ORc2LFw44=
```

I think the ideal situation is that when you enter the `:colon_and_words:` style of emoji, Habitica's hosted images should be used (that allows consistency across all Habitica platforms, which is especially useful when challenge creators want a consistent appearance for their tasks), but when you enter a UTC emoji, no conversion should be done - the platform-specific emoji should be allowed to be used.

We also have these two emoji issues but the behaviours described there don't seem exactly the same as this one:
https://github.com/HabitRPG/habitica/issues/9128
https://github.com/HabitRPG/habitica/issues/10654

**Comment by Alys** [comment]
I'm marking this as suggestion-discussion so we can discuss how to best resolve this.

**Comment by tog22** [comment]
The behaviour here is erratic - sometimes the exact same string with emoji will show the emoji, and sometimes it will show :colon text:. Here's an example of text which does this: http://prntscr.com/n98kwn

**Comment by tog22** [comment]
One emoji which is consistently doing this for me is 🌫 ('fog')

**Comment by veeeeeee** [comment]
Not a high priority in the grand scheme of things but we'd like to take a deeper look at it at some point in the future.

**Comment by Tressley** [comment]
Unfortunately, this is due to the way Habitica parses emoji into Markdown. We do not support all emoji to-date because Habitica has to carefully vet emoji to ensure they meet our community guidelines and each mobile update tends to introduce a handful of new emoji.

**Comment by tog22** [comment]
> Unfortunately, this is due to the way Habitica parses emoji into
Markdown. We do not support all emoji to-date because Habitica has to
carefully vet emoji to ensure they meet our community guidelines.

FWIW, lots and lots of innocent emoji intermittently break - ie. ~~70% of
the time they break, 30% of the time when you try retyping them in a
different order they work.

**Comment by Tressley** [comment]
@tog22 -- That's interesting. Thanks for that feedback. Knowing that now, it sounds like we'll need to do a deeper investigation when we are able to prioritize this issue.

**Comment by SabreCat** [comment]
Closing this in favor of a holistic emoji issue ticket, linked above.
