### ISSUE TITLE
Focus problem when modify existing tags

### ISSUE THREAD

**Issue by hugoattal** [HabitRPG/habitica#1092]
When I try to modify the existing tags ("Morning", "Afternoon", ...), the text input unfocus every time I press en letter.

So, to write "Matin" (yes, I'm french), I have to type "M", then clic on the text field, then type "a", then type on the text field, then type "t", and so on...

This problem does not appear when creating a new tag.

(I use the last version of Chrome)

**Comment by lefnire** [comment]
Private path nested if/else issue with arrays. Note to self

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
