### ISSUE TITLE
Challenge and Group Plan tags cannot be sorted

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10934]
Recently, https://github.com/HabitRPG/habitica/pull/10911 was done to allow a user's personal tags to be sorted. I'm opening this issue to allow sorting to be done for Challenge tags and Group Plan tags too.

I'm marking this as a medium level task since it's likely that the code that was created for personal task sorting can be reused or expanded to allow sorting the other types of tags.

Note that each type of tag can only be sorted separately. E.g., you can sort all Challenge tags into a particular order amongst themselves but you can't mix Challenge and Group Plan and personal tags together - the front-end structure of the new website no longer allows that. :(

**Comment by Mira-M** [comment]
I can take this one, please!

**Comment by Alys** [comment]
@Mira-M I'm sorry about the delay in us replying! Please do go ahead with this if you're still interested! Comment here if you have questions.

**Comment by shanaqui** [comment]
@Mira-M Are you still interested in working on this? If so, please let us know!

**Comment by shanaqui** [comment]
I'll set this back to help wanted since there was no reply. :)

**Comment by codexdelta** [comment]
hi, I would be very interested in resolving this. 

I can see that I can sort the tags over here but not the challenges. The desired behavior is to make the challenges and groups sortable over here, please correct me if I am wrong.


![image](https://user-images.githubusercontent.com/6303170/104452834-8ef2db00-55c9-11eb-8a8a-2f519279e465.png)

**Comment by lizapritchard** [comment]
Hi @Alys I noticed there hasn't been much activity here in a while, could I work on this issue?

**Comment by lizapritchard** [comment]
I was able to make the challenges draggable like the tags but am having a little trouble handling groups. Right now, groups aren't editable at all from this module (they can't be added, deleted, or dragged) should groups be editable? Or just draggable? 

I'm also having a little trouble adding groups to my local db to test the new functionality. I modified my groups document to include the following and I'm seeing the group under the groups tab but it still does not appear in my tags in the tasks tab
`"purchased" : {
        "plan" : {
            "consecutive" : {
                "count" : 0,
                "offset" : 0,
                "gemCapExtra" : 0,
                "trinkets" : 0
            },
            "quantity" : 3,
            "extraMonths" : 0,
            "gemsBought" : 0,
            "mysteryItems" : [],
            "customerId" : "cus_123456789",
            "dateCreated" : ISODate("2021-04-11T17:49:59.589Z"),
            "dateTerminated" : null,
            "dateUpdated" : ISODate("2020-04-11T17:49:59.589Z"),
            "lastReminderDate" : null,
            "owner" : "18d6ea8b-5ad1-4ff6-a9a1-3f2da1e976d8",
            "paymentMethod" : "Stripe",
            "planId" : "group_monthly",
            "subscriptionId" : "sub_123456789"
        }
    },`

**Comment by Alys** [comment]
@lizapritchard I've marked this as in progress for you. If you'd like to submit a pull request for only challenge tags, I think that would be fine! That's the part that's of most interest to the majority of Habiticans.

You could then keep working on Group Plan tags too if you wanted to, but currently the staff are making some changes to Group Plans so it's possible that they'll be adjusting tags for them. To answer your question though: Check that your test account is in that group (sorry, it's an obvious thing but I have to mention it just in case), and create a task in that group and assign it to your test account - that latter step is probably necessary to make the tag appear. It would also be fine if your test account claimed the task rather than having the task assigned to them.

@codexdelta I'm so very sorry that we all missed your post here from January. :(
