### ISSUE TITLE
Error on 'npm start' on a Ubuntu 18.4

### ISSUE THREAD

**Issue by jueast08** [HabitRPG/habitica#10930]
Just want to start out by saying that I love the application and really want to be able to say that I contribute to making it better. I'm starting a job in computers, but where I no longer code, and I really want to continue to grow and learn with you all.

Side note : 
$\> node --version
v10.15.0

$\> npm --version
6.4.1

# The problem 
$\> sudo service mongod start
$\> npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '--verbose' ]
npm info using npm@6.4.1
npm info using node@v10.15.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle habitica@4.77.5\~prestart: habitica@4.77.5
npm info lifecycle habitica@4.77.5\~start: habitica@4.77.5

\> habitica@4.77.5 start \~/proj_perso/habitica
\> gulp nodemon

[11:54:56] Using gulpfile \~/proj_perso/habitica/gulpfile.js
[11:54:56] Starting 'nodemon'...
[11:54:56] Finished 'nodemon' after 40 ms
[11:54:56] [nodemon] 1.18.7
[11:54:56] [nodemon] to restart at any time, enter `rs`
[11:54:56] [nodemon] watching: *.*
[11:54:56] [nodemon] starting `node ./website/server/index.js`
npm verb lifecycle habitica@4.77.5\~start: unsafe-perm in lifecycle true
npm verb lifecycle habitica@4.77.5\~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:\~/proj_perso/habitica/node_modules/.bin:/usr/local/bin/ensi_grades/:/usr/local/bin/pycharm/bin:.:\~/bin/georgeanna:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle habitica@4.77.5\~start: CWD: \~/proj_perso/habitica
npm info lifecycle habitica@4.77.5\~start: Failed to exec start script
npm verb stack Error: habitica@4.77.5 start: `gulp nodemon`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous\> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous\> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:962:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm verb pkgid habitica@4.77.5
npm verb cwd \~/proj_perso/habitica
npm verb Linux 4.15.0-43-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "start" "--verbose"
npm verb node v10.15.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.77.5 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitica@4.77.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 5846ms

npm ERR! A complete log of this run can be found in:
npm ERR!     \~/.npm/_logs/2019-01-02T10_54_58_738Z-debug.log

# What I've done
 $\> sudo apt-get install build-essential &\> habitica_install_output.txt
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

$\> node --version; npm--version
sudo apt-get purge nodejs -y; sudo apt-get purge node -y
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package node

$\> wget -qO- https://deb.nodesource.com/setup_8.x | sudo bash - sudo apt-get install nodejs
/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file
/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file

$\> wget https://deb.nodesource.com/setup_10.x
$\> chmod +x setup_10.x
$\> sudo ./setup_10.x

\#\# Installing the NodeSource Node.js 10.x repo...

\#\# Populating apt-get cache...

+ apt-get update
Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Ign:2 http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 InRelease
Hit:3 http://repo.steampowered.com/steam precise InRelease
Hit:4 http://download.virtualbox.org/virtualbox/debian artful InRelease
Ign:5 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:6 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu bionic InRelease
Hit:8 http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 Release
Hit:9 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:10 http://dl.google.com/linux/chrome/deb stable Release
Hit:11 https://deb.nodesource.com/node_10.x bionic InRelease
Hit:12 http://ppa.launchpad.net/jtaylor/keepass/ubuntu bionic InRelease
Hit:13 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:14 http://ppa.launchpad.net/noobslab/icons/ubuntu bionic InRelease
Hit:15 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:16 http://ppa.launchpad.net/numix/ppa/ubuntu bionic InRelease
Hit:17 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Reading package lists...

\#\# Confirming "bionic" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/bionic/Release'

\#\# Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

\#\# Creating apt sources list file for the NodeSource Node.js 10.x repo...

+ echo 'deb https://deb.nodesource.com/node_10.x bionic main' \> /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_10.x bionic main' \>\> /etc/apt/sources.list.d/nodesource.list

\#\# Running `apt-get update` for you...

+ apt-get update
Hit:1 http://download.virtualbox.org/virtualbox/debian artful InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:4 http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 InRelease
Hit:5 http://repo.steampowered.com/steam precise InRelease
Hit:6 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 Release
Hit:8 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu bionic InRelease
Hit:9 http://dl.google.com/linux/chrome/deb stable Release
Hit:10 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:11 http://ppa.launchpad.net/jtaylor/keepass/ubuntu bionic InRelease
Hit:12 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:13 https://deb.nodesource.com/node_10.x bionic InRelease
Hit:14 http://ppa.launchpad.net/noobslab/icons/ubuntu bionic InRelease
Hit:15 http://ppa.launchpad.net/numix/ppa/ubuntu bionic InRelease
Hit:16 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:17 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Reading package lists...

\#\# Run `sudo apt-get install -y nodejs` to install Node.js 10.x and npm
\#\# You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
\#\# To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

$\> sudo apt-get install nodejs 
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 0 B/15,1 MB of archives.
After this operation, 71,8 MB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 344013 files and directories currently installed.)
Preparing to unpack .../nodejs_10.15.0-1nodesource1_amd64.deb ...
Detected old npm client, removing...
Unpacking nodejs (10.15.0-1nodesource1) ...
Setting up nodejs (10.15.0-1nodesource1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

$\> node --version
v10.15.0

$\> npm --version
6.4.1

$\> sudo ln -s `which nodejs` /usr/bin/node
ln: failed to create symbolic link '/usr/bin/node': File exists

$\> sudo npm install -g mocha 
/usr/bin/mocha -\> /usr/lib/node_modules/mocha/bin/mocha
/usr/bin/_mocha -\> /usr/lib/node_modules/mocha/bin/_mocha
+ mocha@5.2.0
updated 1 package in 3.213s

$\> sudo rm -rf habitica/

$\> git clone git@github.com:jueast08/habitica.git

git clone git@github.com:jueast08/habitica.git
Cloning into 'habitica'...
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 231386 (delta 19), reused 19 (delta 3), pack-reused 231290
Receiving objects: 100% (231386/231386), 983.01 MiB | 7.55 MiB/s, done.
Resolving deltas: 100% (165686/165686), done.
Checking out files: 100% (10306/10306), done.

$\> cd habitica
$\> git branch
* develop

$\> git remote add upstream https://github.com/HabitRPG/habitica.git
$\> git fetch && git pull
git fetch && git pull
Already up to date.

$\> cp config.json.example config.json

$\> npm install --versbose

\> phantomjs-prebuilt@2.1.16 install /home/jueast/proj_perso/habitica/node_modules/phantomjs-prebuilt
\> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [==============================----------] 76%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/jueast/proj_perso/habitica/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1546426180251/phantomjs-2.1.1-linux-x86_64 -\> /home/jueast/proj_perso/habitica/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/jueast/proj_perso/habitica/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

\> bcrypt@3.0.2 install /home/jueast/proj_perso/habitica/node_modules/bcrypt
\> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[bcrypt] Success: "/home/jueast/proj_perso/habitica/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

\> chromedriver@2.44.1 install /home/jueast/proj_perso/habitica/node_modules/chromedriver
\> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip
Saving to file: /tmp/chromedriver/chromedriver_linux64.zip
Received 782K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3918K...
Received 4702K...
Received 5210K total.
Extracting zip contents
Copying to target path /home/jueast/proj_perso/habitica/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/jueast/proj_perso/habitica/node_modules/chromedriver/lib/chromedriver/chromedriver

\> node-sass@4.10.0 install /home/jueast/proj_perso/habitica/node_modules/node-sass
\> node scripts/install.js

Cached binary found at /home/jueast/.npm/node-sass/4.10.0/linux-x64-64_binding.node

\> puppeteer@1.11.0 install /home/jueast/proj_perso/habitica/node_modules/puppeteer
\> node install.js

Downloading Chromium r609904 - 106.4 Mb [====================] 99% 0.0s 
Chromium downloaded to /home/jueast/proj_perso/habitica/node_modules/puppeteer/.local-chromium/linux-609904

\> uglifyjs-webpack-plugin@0.4.6 postinstall /home/jueast/proj_perso/habitica/node_modules/uglifyjs-webpack-plugin
\> node lib/post_install.js

\> nodemon@1.18.7 postinstall /home/jueast/proj_perso/habitica/node_modules/nodemon
\> node bin/postinstall || exit 0

\> gifsicle@4.0.1 postinstall /home/jueast/proj_perso/habitica/node_modules/gifsicle
\> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

\> jpegtran-bin@4.0.0 postinstall /home/jueast/proj_perso/habitica/node_modules/jpegtran-bin
\> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

\> optipng-bin@5.0.0 postinstall /home/jueast/proj_perso/habitica/node_modules/optipng-bin
\> node lib/install.js

(node:30186) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
  ✔ optipng pre-build test passed successfully

\> bootstrap-vue@2.0.0-rc.11 postinstall /home/jueast/proj_perso/habitica/node_modules/bootstrap-vue
\> opencollective postinstall || exit 0

                                   Thanks for installing bootstrap-vue 
                              Please consider donating to our open collective
                                     to help us maintain this package.

                                        Number of contributors: 191
                                           Number of backers: 13
                                            Annual budget: $691
                                           Current balance: $784

                      Donate: https://opencollective.com/bootstrap-vue/donate

\> node-sass@4.10.0 postinstall /home/jueast/proj_perso/habitica/node_modules/node-sass
\> node scripts/build.js

Binary found at /home/jueast/proj_perso/habitica/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine

\> habitica@4.77.5 postinstall /home/jueast/proj_perso/habitica
\> gulp build

[11:50:15] Using gulpfile \~/proj_perso/habitica/gulpfile.js
[11:50:15] Starting 'build'...
[11:50:15] Starting '<anonymous\>'...
[11:50:15] Finished '<anonymous\>' after 1.04 ms
[11:50:15] Finished 'build' after 3.65 ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 3107 packages from 2687 contributors and audited 43593 packages in 106.575s
found 27 vulnerabilities (3 low, 17 moderate, 5 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

$\> sudo service mongod start

**Comment by paglias** [comment]
@jueast08 hmm never saw that error before, is there anything useful in `~/.npm/_logs/2019-01-02T10_54_58_738Z-debug.log`?

Otherwise some people with similar issues seems to have resolved them by deleting `node_modules` and running `npm install` again

**Comment by jueast08** [comment]
@paglias Thanks for your response. 

I've tried a clean delete and `npm install` as well as a `npm ci` but the results seem to be the same.

As far as my logs are concerned, its more or less the same information. Very vague.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '--verbose' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.77.5\~prestart: habitica@4.77.5
6 info lifecycle habitica@4.77.5\~start: habitica@4.77.5
7 verbose lifecycle habitica@4.77.5\~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.77.5\~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jueast/proj_perso/habitica/node_modules/.bin:/usr/local/bin/ensi_grades/:/usr/local/bin/pycharm/bin:.:\~/bin/georgeanna:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle habitica@4.77.5\~start: CWD: \~/proj_perso/habitica
10 silly lifecycle habitica@4.77.5\~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle habitica@4.77.5\~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.77.5\~start: Failed to exec start script
13 verbose stack Error: habitica@4.77.5 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid habitica@4.77.5
15 verbose cwd /home/jueast/proj_perso/habitica
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "--verbose"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.77.5 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the habitica@4.77.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


Frankly, I've tried to place console logs in files to see where the individual problems could be stemming from, but I haven't had much luck

**Comment by paglias** [comment]
I don't think placing console.logs would help as the error happens before anything is started... can you try `./node_modules/.bin/gulp nodemon`?

**Comment by jueast08** [comment]
$> \~/proj_perso/habitica$ ./node_modules/.bin/gulp nodemon
[13:27:41] Using gulpfile \~/proj_perso/habitica/gulpfile.js
[13:27:41] Starting 'nodemon'...
[13:27:41] Finished 'nodemon' after 45 ms
[13:27:42] [nodemon] 1.18.7
[13:27:42] [nodemon] to restart at any time, enter `rs`
[13:27:42] [nodemon] watching: *.*
[13:27:42] [nodemon] starting `node ./website/server/index.js`
$>:~/proj_perso/habitica$ (node:24868) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

**Comment by paglias** [comment]
so it started? This makes me think that it's a problem with NPM. I'd try `npm cache clean --force`, delete `node_modules`, `package-lock.json` and install again with `npm install`

**Comment by jueast08** [comment]
Same error here.

**Comment by jueast08** [comment]
And I reinstalled Ubuntu for good measure

**Comment by paglias** [comment]
Hmm the fact that you're able to start the server with `./node_modules/.bin/gulp nodemon` makes me think that the problem is with NPM :( We run our server on Ubuntu and never had this problem unfortunately. For the time being I'd suggest starting the server directly with `./node_modules/.bin/gulp nodemon` for the backed and `node ./webpack/dev-server.js` for the client side.

**Comment by jueast08** [comment]
I'm not actually sure that the server started, and not sure how to test it. Anyone running setting up on the newer versions of Ubuntu, 18.4 or 18.10 ?

**Comment by andrew-vicencio** [comment]
Hi, I have the same problem. I followed your steps for `npm cache clean --force` -> delete `node_modules`, `package-lock.json` -> `npm install`. Same error. Also using gulp nodemon directly does not start the server. No response from `localhost:8080 or :3000` as well as no node process found using `ps -aef | grep node` or `ps -ax | grep node`.

**Comment by paglias** [comment]
@jueast08 @andrew-vicencio after installing the dependencies you should open two separate terminal windows and run these commands:

```
./node_modules/.bin/gulp nodemon
```

and 

```
node ./webpack/dev-server.js
```

what's the output from these commands?

After they start (the second one will take 30-60s) the API should be available at `localhost:8080` and the API at `localhost:3000` (you can verify it's working by hitting `localhost:3000/api/v3/status`)

**Comment by andrew-vicencio** [comment]
This is what I get when running `node ./webpack/dev-server.js`

```
/home/andrew/code/habitica/node_modules/http-proxy-middleware/lib/config-factory.js:43
    throw new Error(ERRORS.ERR_CONFIG_FACTORY_TARGET_MISSING)
    ^

Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}
    at Object.createConfig (/home/andrew/code/habitica/node_modules/http-proxy-middleware/lib/config-factory.js:43:11)
    at new HttpProxyMiddleware (/home/andrew/code/habitica/node_modules/http-proxy-middleware/lib/index.js:17:30)
    at module.exports (/home/andrew/code/habitica/node_modules/http-proxy-middleware/index.js:4:10)
    at Object.keys.forEach (/home/andrew/code/habitica/webpack/dev-server.js:49:11)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/andrew/code/habitica/webpack/dev-server.js:44:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
and this is what I get when I run `./node_modules/.bin/gulp nodemon`

```
[15:56:32] Using gulpfile ~/code/habitica/gulpfile.js
[15:56:32] Starting 'nodemon'...
[15:56:32] Finished 'nodemon' after 26 ms
[15:56:32] [nodemon] 1.18.9
[15:56:32] [nodemon] to restart at any time, enter `rs`
[15:56:32] [nodemon] watching: *.*
[15:56:32] [nodemon] starting `node ./website/server/index.js`
```
Nodemon seems to start but then never starts the express server or connect to mongo. It exits immediately after the `starting node ./website/server/index.js` line.
I also get nothing at `localhost:3000` and `localhost:8080`

**Comment by paglias** [comment]
Hmm let's see if @SabreCat has some ideas

**Comment by paglias** [comment]
Unfortunately I don't use Ubuntu for my local development so I'm not able to troubleshoot but our server is running npm commands fine so my guess is there's something wrong in the npm or node installation process. 

Do you maybe need to run some npm commands with `sudo`?

**Comment by jueast08** [comment]
@paglias personally,`npm run client:dev` runs fine for me. and the only issue there is

`[HPM] Error occurred while trying to proxy request /api/v4/i18n/browser-script from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/v4/i18n/browser-script from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

but that's normal seeing how I can't get the server to work; I don't think this is a Nodejs or NPM problem.

**Comment by paglias** [comment]
@jueast08 thanks! that's quite useful. So the error seems related to the `npm start` command only, the output you're getting for `npm run client:dev` is totally expected. Could you try running `npm run client:dev` in one terminal and in another one try these three commands separately to see if one works

- `sudo npm start`
- `node ./website/server/index.js` (this should start the server but without automatic reloads after the code changes so you'll have to kill and restart it every time you make a change)
- `npm i -g nodemon` and then `nodemon`

thanks!

**Comment by jueast08** [comment]
@paglias Hey, buddy. You sure did put me on the right path to figuring out the problem.

@andrew-vicencio Let me know if this works for you, bud.

So I knew that `sudo npm start` wouldnn't work. I didn't need to test that. However, I had not tested `node ./website/server/index.js`. This command worked. Installing `nodemon` globably and then running `nodemon` was the most helpful command because it actually gave the reason that `nodemon` was failing (I should have thought of that :D ). The error that I got when running `nodemon` was: 

`[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '~/proj_perso/habitica/node_modules/for-own/LICENSE'`

So what I had to do was augment the number of files that could be watched on my machine:

`sudo sysctl fs.inotify.max_user_watches=582222 && sudo sysctl -p`

to temporarily change the max size. I tested again with `npm start --verbose` and this time everything started up just fine.


`echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

This command permenately changes the size so that it starts up correctly every single time.


Source:  https://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc

**Comment by paglias** [comment]
@jueast08 happy that it worked!

The weird thing is that `.nodemonignore` is set to ignore the files under `node_modules` https://github.com/HabitRPG/habitica/blob/develop/.nodemonignore#L1 so this shouldn't be happenign

**Comment by SabreCat** [comment]
@paglias Do we need to investigate the `.nodemonignore` issue, or can this be closed?

**Comment by paglias** [comment]
I think it can be closed, we can reopen if any report comes in

**Comment by Tokelin** [comment]
I seem to be getting a similar or even the same issue. So far I've launched the back end using `./node_modules/.bin/gulp nodemon`

Here is the full output of `npm start`
```
npm start

> habitica@4.146.7 start /home/tokelin/development/habitica
> gulp nodemon

[17:58:07] Using gulpfile ~/development/habitica/gulpfile.js
[17:58:07] Starting 'nodemon'...
[17:58:07] Finished 'nodemon' after 42 ms
[17:58:07] [nodemon] 2.0.2
[17:58:07] [nodemon] to restart at any time, enter `rs`
[17:58:07] [nodemon] watching dir(s): *.*
[17:58:07] [nodemon] watching extensions: js,mjs,json
[17:58:07] [nodemon] starting `node ./website/server/index.js`
2020-06-28T14:58:14.588Z - info Express server listening on port 3000
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.146.7 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitica@4.146.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tokelin/.npm/_logs/2020-06-28T14_58_21_043Z-debug.log
```

and the contents of `.npm/_logs/2020-06-28T14_58_21_043Z-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/tokelin/.nvm/versions/node/v12.18.1/bin/node',
1 verbose cli   '/home/tokelin/.nvm/versions/node/v12.18.1/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.146.7~prestart: habitica@4.146.7
6 info lifecycle habitica@4.146.7~start: habitica@4.146.7
7 verbose lifecycle habitica@4.146.7~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.146.7~start: PATH: /home/tokelin/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tokelin/development/habitica/node_modules/.bin:/home/tokelin/.nvm/versions/node/v12.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle habitica@4.146.7~start: CWD: /home/tokelin/development/habitica
10 silly lifecycle habitica@4.146.7~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle habitica@4.146.7~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.146.7~start: Failed to exec start script
13 verbose stack Error: habitica@4.146.7 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/tokelin/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/tokelin/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid habitica@4.146.7
15 verbose cwd /home/tokelin/development/habitica
16 verbose Linux 5.4.0-39-generic
17 verbose argv "/home/tokelin/.nvm/versions/node/v12.18.1/bin/node" "/home/tokelin/.nvm/versions/node/v12.18.1/bin/npm" "start"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.146.7 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the habitica@4.146.7 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I am running node v12.18.1 although I had v14 installed and I'm not sure if it was properly removed

P.S. After starting the front end with `npm run client:dev` and going to test it out the back end crashed, even when launching with `./node_modules/.bin/gulp nodemon`

**Comment by JalanshMunshi** [comment]
Hi, @Tokelin !

I received a similar error for `err code ELIFECYCLE`.

Did you try this?

> `npm ERR! code ELIFECYCLE`
> If you are using Linux or Docker, this error is likely to be because nodemon requires more file watchers than inotify provides. Increase the number of file watchers. On Ubuntu and similar Linux distributions, you can do that using this command:
> 
> `echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/50-max-user-watches.conf && sudo sysctl --system`

Search for ELIFECYCLE on [this page](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux) and you'll find this section. I hope this helps.

**Comment by Tokelin** [comment]
Yes, that fixed it, thank you.

I did see that comment earlier - should've tried it first, but decided to still comment since the issue is still present it seems.
