### ISSUE TITLE
Dropped to level 1, lost dailies and equipment

### ISSUE THREAD

**Issue by tynafish** [HabitRPG/habitica#1093]
I left the game open in a tab for an hour or 2 unsupervised and it told me I died when I came back. The message said I lost 1 level, but it actually dropped me from level 6 to level 1. My dailies are somehow in the negatives, even though I had the majority of them on a 6-day streak. I've also lost a sword. I understand there is a way to restore my levels and equipment, but I would like to get my streak back. Is there a way to do that?

**Comment by lefnire** [comment]
Yes, edit task - advanced - restore streak. This is one of those racer 0.5
bits, usually happens when two browsers are open and one runs cross (next
day rollover). Well be upgrading soon hopefully to fix these issues

**Comment by tynafish** [comment]
Thank you so much!
