### ISSUE TITLE
apidocs errors / omissions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10943]
There's some problems with the API documentation at https://habitica.com/apidoc/ as reported by Dan Dulaney @duplaja (801998d9-f208-4357-8d2a-c792f23059a1):

- [ ] "I noticed an API documentation bug, found here (possibly the same item in other sublinks): https://habitica.com/apidoc/#api-Task-CreateUserTasks  Under frequency, for allowed values, it lists only "daily" and "weekly", but it looks like "monthly" and "yearly" are also options on site."
- [ ] "The documentation also says that everyX only applies to frequency=daily, but it looks like you can now set this for weekly? (and I assume but haven't checked, monthly and yearly)"
- [ ] "It looks like monthly type has another parameter it receives that's undocumented, telling whether the task should be checked on day of the month, or day of the week."

I haven't verified these so if the person who works on this has questions or needs clarification, comment here.

**Comment by arjunchawla** [comment]
Hi Alys, Pleas welt me know if I can start working on this problem

**Comment by Alys** [comment]
@arjunchawla Please do, thanks!

**Comment by SunSparc** [comment]
I was just reading through the [API page on the wiki](https://habitica.fandom.com/wiki/Application_Programming_Interface#Errors_in_the_API_Documentation), and there was a reference to this issue. Is this an issue that will be ongoing? Looks like the original post was eleven months ago.

**Comment by Alys** [comment]
@SunSparc Thanks for asking! It looks like this one slipped through our checking process. I'm marking it as help wanted, but @arjunchawla if you want to take it up again, let us know. @SunSparc You'd also be welcome to claim it too if you wish! First person to post gets it. :)

**Comment by SunSparc** [comment]
I can take a stab at it.

**Comment by SunSparc** [comment]
Took a bit longer than I initially planned because I did some testing on my local install to make sure that what I was changing in the documentation was indeed accurate.

@Alys: As a side note, we may want to close this issue and perhap open another, if we want to maintain a link on the [wiki API page](https://habitica.fandom.com/wiki/Application_Programming_Interface#Errors_in_the_API_Documentation). Unless that was specifically added for the problems indicated in this issue only. In which case we could just remove any reference to that on the wiki. Or we could direct people to Trello, or suggest that they just open github issues for future problems. I am just thinking out loud.

**Comment by Alys** [comment]
@SunSparc Awesome, thanks, especially for the testing!

We'll close this issue and delete the comment from the wiki once the PR is merged (I've marked this issue with "notify helpers" as a reminder to me to look at it later). 

For any new apidocs error, I suggest that any one of these approaches is taken:
- create a PR to fix it straight away (if the error is found by a coder who wants to fix it)
- create an issue for it (if the error is found by a coder who doesn't have the time/desire to fix it or by a non-coder)
- report it in the Report a Bug guild and then I or another admin will create an issue for it

Trello's not as good because it's just for feature requests and I'd consider apidocs errors/omissions to be more like bugs.

**Comment by SunSparc** [comment]
Sounds great! I agree. In which case, what should we do about that comment/link on the wiki:

> Current known errors are documented at habitica Issue #10943 .

**Comment by Alys** [comment]
@SunSparc I'll delete that comment on the wiki after your PR is merged (might not be immediately after). You'd be welcome to delete it yourself if you wish, after the PR is merged.
