### ISSUE TITLE
Achievements tab in user profile not clickable on mobile website 

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#10944]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: Chrome
  * OS: Android

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
On narrow mobile phone screen the three "tabs" (Profile, Stats, Achievements) line wraps so that the Achievements tab goes to second line and it is not clickable (maybe gets behind some other elements etc) even though it's visible. 
![screenshot_20190111-213547__01](https://user-images.githubusercontent.com/1764167/51057187-838d0380-15ed-11e9-84c1-65af014a6aac.jpg)

[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
@cvuorinen Thanks! I've marked this in progress for you. Let's us know if you have any questions about creating a pull request.
