### ISSUE TITLE
Egg Hatching Issue

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#10947]
Hi! I started usung Habitica a little but ago, and ive aquited a few eggs. Specifically a dragon egg. I try hatching it, and once i press hatch all my items disappear until i refresh the page. So, i am not able to hatch the egg- possible glitch?

**Comment by Alys** [comment]
Can you please report this in the Report a Bug guild? You can reach it from the Help menu in the website. We can see your account there which helps us work out what's going wrong. :) The "new issue" form here in GitHub also has a note about where to find that guild.

When you post there, please say what browser you're using including its version number and what operating system you're running, including version (e.g., Windows 10).
