### ISSUE TITLE
lost an egg!

### ISSUE THREAD

**Issue by sabrinastarfire** [HabitRPG/habitica#1095]
I lost an egg when i came back habitrpg. this is not the first time ive lost potions because of it and now i've lost a wolf egg i've been waiting so long for.

**Comment by Shaners** [comment]
Please post your User ID, found on the settings tab.

**Comment by sabrinastarfire** [comment]
```
(80d34f3c-8231-4133-9406-391bdf4449a3)
```

**Comment by lefnire** [comment]
added gems so you can buy back. lots of lost-drop tickets around, closing for organization

**Comment by sabrinastarfire** [comment]
thank you 
:)
