### ISSUE TITLE
challenge export CSV file should include Usernames

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10955]
Currently, when a Challenge owner uses the export feature to get a CSV file, the participants are identified by only User ID and profile name. The CSV file should also have a column for Username.

I'm marking this as important priority because it makes it hard to judge challenges now as described by @Ceran (aabe567b-aa55-42c1-b612-b7699a7ba9b7):

_"With the new usernames vs display names, I find it very confusing and inconvenient that the challenge data downloads show only the display names. It's especially weird when someone changed their display name so that the spreadsheets show a different name for a person than the one they posted in a guild with. (And since the change many people enjoy changing their names often.) Since I can't see the user name in the spreadsheet, it can be difficult to assign posts that were required for the challenge to the user's data, for example."_

**Comment by Mira-M** [comment]
I can pick this one up.
