### ISSUE TITLE
"Apply Sort Options to Party Header" should not appear in Guilds

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10968]
As reported by @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c):

"... when I go to a Guild page and check the member list. After I choose a different sorting method from the drop-down menu, the "Apply Sort Options to Party Header" button will show up. Said button will then stay until I refresh my browser. If I click it, my party header will be sorted according to the method I picked. But I'm assuming this isn't actually the desired behaviour, since I'm on a Guild list, not my party list."

The correct behaviour is for that "Apply..." link to appear only when you're sorting while viewing the member list for your Party.

**Comment by CBillings92** [comment]
Hi! New to contributing here, but can I take a shot at this?

**Comment by Alys** [comment]
@CBillings92 Sure, thanks! Comment here if you have any questions!
