### ISSUE TITLE
Bug in tags edition

### ISSUE THREAD

**Issue by zeroos** [HabitRPG/habitica#1096]
When I try to edit tag name, after typing one character the input losts its focus and  I have to click on it again.

**Comment by lefnire** [comment]
https://github.com/codeparty/derby/issues/267

**Comment by lefnire** [comment]
hell yeah! fixed, deploying to develop. @zeroos could you test there for a bit? Then i'll merge to master. See previous referenced issue for what the issue was

**Comment by zeroos** [comment]
lgtm, thx for fixing it. :)
