### ISSUE TITLE
Subscription creation fails when Stripe webook "charge.succeeded" is received

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10969]
@BennyArt (81f4bf5d-26a5-471f-8deb-3f0db7cb3e55) reported that they tried to create a subscription using Stripe, it failed due to insufficient funds, then they tried again after adding money to their credit card, and the payment succeeded (which I've confirmed in our Stripe interface) but the subscription was not created (also confirmed).

Loggly shows these errors (links will work for Habitica admins only):

1. ["Your card has insufficient funds" from /stripe/checkout?a=a&sub=basic_3mo at 2019-01-28T22:39:35.255Z](https://habitica.loggly.com/search#terms=&from=2018-12-11T00:00:00.000Z&until=2019-01-29T01:18:30.426Z&source_group=&event=96608c6c-234d-11e9-804f-0e1a510a781c,1548715175255,137680079753874540) - `isHandledError:true` and obviously it's not a bug that we see that error message

2. ["Cannot read property 'start' of undefined" from /stripe/checkout?a=a&sub=basic_3mo at 2019-01-28T22:40:43.850Z](https://habitica.loggly.com/search#terms=&from=2019-01-27T00:00:00.000Z&until=2019-01-29T01:18:30.426Z&source_group=&event=bf4f39c6-234d-11e9-8013-0e21aa8a6b96,1548715243850,137680080440605126) - `isHandledError:false` but this _might_ be just a side-effect of the subscription not being created. [EDIT 2019-02-01 This has been fixed. It was from a misconfiguration in Mystery Items and was stopping all subscriptions from being created.]

3. ["Missing handler for Stripe webhook charge.succeeded" at Object.handleWebhooks (/usr/src/habitrpg/website/transpiled-babel/libs/payments/stripe.js:246:32) at 2019-01-28T22:40:44.341Z](https://habitica.loggly.com/search#terms=&from=2019-01-27T00:00:00.000Z&until=2019-01-29T01:18:30.426Z&source_group=&event=bf98a0bc-234d-11e9-80e7-06e403ed47d2,1548715244341,137680080445415612) - this is probably the bug that needs to be fixed

I'm marking this as important priority and help wanted **BUT any contributor who wants to work on it must post here first and wait for staff to say if they can go ahead** because staff might want to fix this themselves. (Ideally, contributors should follow that process for any issue, but it's especially important for this one so that your time isn't wasted.)

(I've fixed the bug for @BennyArt by cancelling the recurring payments and giving them a suitable length of gift subscription.)

**Comment by paglias** [comment]
I'll look into the second point, the 3rd one instead is expected although it shouldn't throw an error (I'll have to look into why the webhook is being sent).

The webhook handler is set to only receive and process some events related to subscriptions charges failing, the `charge.succeeded` shouldn't be sent at all so when it's received it causes an error because it's not implemented

**Comment by Alys** [comment]
There's another 
`Cannot read property 'start' of undefined` for a new person reporting subscription problems:
```
    at findMysteryItems (/usr/src/habitrpg/website/transpiled-babel/libs/payments/subscriptions.js:40:116)
....
originalUrl:/stripe/checkout?a=a&sub=basic_3mo
```
https://habitica.loggly.com/search#terms=53de1835-bda2-4dce-8265-997ca3a3c1b3&from=2018-12-11T00:00:00.000Z&until=2019-01-30T14:34:55.665Z&source_group=&event=1f91dfc1-2409-11e9-80ca-12c72a2782d6,1548795721225,137680885214470081

**Comment by Alys** [comment]
And another for a Google Play subscription attempt:
TypeError: Cannot read property 'start' of undefined
    at findMysteryItems (/usr/src/habitrpg/website/transpiled-babel/libs/payments/subscriptions.js:40:116)
https://habitica.loggly.com/search#terms=942cc218-ff5a-4463-8fa0-07678e0de370&from=2018-12-11T00:00:00.000Z&until=2019-01-30T14:39:27.262Z&source_group=&event=cbd8970a-247e-11e9-8004-0651554be0aa,1548846261390,137681390615959306

**Comment by Alys** [comment]
The `Cannot read property 'start'` error is from the 2019-01 Mystery Set not being in website/common/script/content/mystery-sets.js . All new subscriptions will be failing since the set is meant to be given as part of them.

The other error ("Missing handler for Stripe webhook charge.succeeded") isn't related to that of course. @paglias I was assuming that webhook was being sent because a previous attempt to subscribe had resulted in a failed charge.

**Comment by Alys** [comment]
The `Cannot read property 'start'` bug has been [fixed](https://github.com/HabitRPG/habitica/commit/e294ed836dbbc8e667e677975a024fb7ea4e6f6e) (it turned out to be from a typo, not from what I wrote in my previous comment; I'd thought it was an error in mystery-sets.js because `develop` didn't have the latest version of that file at the time).

The only fix needed now is for point 3 in the top post.

**Comment by zmontgo** [comment]
I'm kind of new, but I have a lot of programming experience. Could I give it a go?

**Comment by Alys** [comment]
@zmontgo Sorry it's taken us a few days to reply! Yes, please do go ahead with this if you'd like to! Post here if you have any questions.

**Comment by zmontgo** [comment]
Great! Do you think I need access to the link, or will the error code tell me all I need to know?
I know this is kind of a weird question from your perspective, but I don't know what that link leads to.

**Comment by Alys** [comment]
@zmontgo That's a valid question! The link leads to a site that's only accessible to admins because it can contain private data about user accounts, but below is most of the data from the log file record. However I think the only relevant details are `"Missing handler for Stripe webhook charge.succeeded" at Object.handleWebhooks (/usr/src/habitrpg/website/transpiled-babel/libs/payments/stripe.js:246:32)`

```
tag: Winston-NodeJS
logtype: json
http:
	contentType: application/json
json:
	level: error
	message: Error: Missing handler for Stripe webhook charge.succeeded
		at Object.handleWebhooks (/usr/src/habitrpg/website/transpiled-babel/libs/payments/stripe.js:246:32)
		at process._tickCallback (internal/process/next_tick.js:68:7)
	timestamp: 2019-01-28T22:40:44.341Z
event:
	api_version:2012-07-09
	created:1548715243
	id:evt_[xxxx]
	livemode:true
	object:event
	pending_webhooks:1
	request:req_[xxxx]
	type:charge.succeeded
data:
	object: { ... subscription details ... }
```

**Comment by paglias** [comment]
So I checked Stripe and the error is thrown because Stripe is set to send a webhook for `charge.succeeded` events which we're not handling, I'll disable it in the next few days

**Comment by Alys** [comment]
@paglias To clarify, you are saying that @zmontgo should stop working on this issue - right?

**Comment by paglias** [comment]
If the only remaining issue is number 3, yes it can be solved by changing a
setting in Stripe but first I want to be sure it wasn't enabled for any
other reason.

Il giorno Dom 17 Feb 2019, 13:51 Alys <notifications@github.com> ha scritto:

**Comment by zmontgo** [comment]
Oh, well that's good, because I can't get my local install to work for some reason.

**Comment by paglias** [comment]
Fixed
