### ISSUE TITLE
"Change Username" new text needed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10967]
From cTheDragons:

It appears the username in the settings on the web has not been updated since the changeover. It states:
"We will be transitioning login names to unique, public usernames soon. This username will be used for invitations, @mentions in chat, and messaging."

From shanaqui:
![image](https://user-images.githubusercontent.com/1495809/51815458-cd275f00-230c-11e9-8f95-457e57bc7c72.png)

`website/common/locales/en/settings.json`:
```
"setUsernameNotificationBody": "We will be transitioning login names to unique, 
public usernames soon. This username will be used for invitations, @mentions
in chat, and messaging.",

"changeUsernameDisclaimer": "We will be transitioning login names to unique,
public usernames soon. This username will be used for invitations, @mentions
in chat, and messaging.",
```

Both strings are in use. I suggest removing one.

~On hold until the staff have chosen new text.~

EDIT 2020-02-26: The staff have chosen new text and it's shown in this comment: https://github.com/HabitRPG/habitica/issues/10967#issuecomment-590968412

The desired fix is to remove `setUsernameNotificationBody` and use `changeUsernameDisclaimer` instead everywhere, and to put the new text into it.

**Comment by Chrisyee22** [comment]
Hi. Could I work on this once you have chosen the new text?

**Comment by GiacomoLaw** [comment]
Any update on this? If @Chrisyee22 doesn't want to do it anymore, I can do so.

**Comment by Chrisyee22** [comment]
Hi @GiacomoLaw, I'd still like to work on this issue. I was waiting for the new text to be decided upon.

**Comment by GiacomoLaw** [comment]
@Chrisyee22 awesome, thanks!

**Comment by Chrisyee22** [comment]
Hi @Alys. Just wondering if the staff has chosen a new text?

**Comment by Alys** [comment]
@Chrisyee22 No, they haven't yet. It will be posted here when they have.

**Comment by SunSparc** [comment]
Is the transition complete? Seems like it is. In which case both should probably be removed, instead of replaced. Unless that area is to be used for explaining what the Username is for and the length/character requirements.

**Comment by kmacart** [comment]
I'll get rid of the text?

**Comment by Alys** [comment]
@kmacart This issue is still on hold waiting for the staff to comment so
please don't make any changes yet. Once a decision, the "on hold" label
will change to "help wanted".

**Comment by kmacart** [comment]
Ok – thanks =) Just wondering, I can’t set up Vagrant – I download it, I try to set it up, and it gives me an error... Time Out for the webpage

And I can’t use Docker, because I don’t have windows 10 pro …

Any help would be much appreciated =)

Thanks a lot,
Kira

**Comment by naima-shk** [comment]
can i try this one please?

**Comment by Tressley** [comment]
We do have plans to update the Settings pages this year which will update this messaging. In the mean time, let's update the copy to:
> Your username is used for invitations, @mentions in chat, and messaging. It must be 1 to 20 characters, containing only letters a to z, numbers 0 to 9, hyphens, or underscores, and cannot include any inappropriate terms.

**Comment by Alys** [comment]
I've marked this issue as help wanted.

**Comment by jcholewa** [comment]
Hi, could I work on this please?

**Comment by paglias** [comment]
Sure @jcholewa ! I'll mark it as in progress

**Comment by jcholewa** [comment]
Just to clarify - is this making changes only in website/common/locales/en/settings.json and wherever the string is used, or modifying other settings.json files also?

**Comment by paglias** [comment]
Only the English file, the other languages are handled automatically by our translation service

**Comment by jcholewa** [comment]
Great, thanks!
