### ISSUE TITLE
Bought 42 Gems but never received them

### ISSUE THREAD

**Issue by debquigg** [HabitRPG/habitica#10966]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # I bought 42 gems yesterday and paid through PayPal. The payment went through but I have yet to receive the gems. My email for Habitica is webink@rogers.com and the order # is 151248673195

Thank you
DebQ

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by majestic-owl448** [comment]
You may want to write in the Report a Bug guild - in this way they can directly check your account and direct you as needed if they need more infos 
Here is much slower than than guild

**Comment by paglias** [comment]
@debquigg sorry about that, @Ieahleen is right, could you post about your problem in the Report a Bug guild? The address is https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac 

Thanks!
