### ISSUE TITLE
Profanity blocker keeps blocking even after blocked word removed

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10970]
_@thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a): "I attempted to post a message in a public guild (New Year's Resolutions) that inadvertently contained a banned word, and got the usual warning telling me to edit my message.  So I edited my message and tried to hit "send", but the warning remained in place even though the banned word was gone.  I couldn't figure out how to get the edit detected correctly, so eventually I had to copy my message to a scratch document, refresh the page, and then copy the message back into the chat pane.  It posted correctly after this procedure, without further editing, so I know that the banned word was definitely already gone."_

I've tested and confirmed this.

**Comment by ghost** [comment]
Hi! I'm new here - I might have a look at this for my first issue?

**Comment by Alys** [comment]
@bonnieetc Yes, thank you! Go ahead. Post here if you have questions.
