### ISSUE TITLE
Username should be searchable in Hall of Heroes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10972]
When moderators view the [Hall of Heroes](https://habitica.com/hall/contributors) (`website/client/components/hall/heroes.vue`) they have a search form to search for any user (not just a contributor) by User ID. See below for a screenshot.

That search feature should also accept Usernames (not Display Names).
 
The placeholder text in the search form should be changed from "User ID" to "Username or User ID".
A new text string will need to be created for that but it should NOT be put in the `habitica/website/common/locales` files because it won't need to be translated (admin-only features are just displayed in English). 
_There's a file somewhere else for storing such strings but I can never remember where. :scream: I'll update this issue later when I find it again. If I haven't done that by the time a contributor wants to work on this, ask here. There's website/common/errors/commonErrorMessages.js but that seems to be just for errors; I think there's another file like it somewhere else._

A contributor can see that search feature on their local install by changing their test user to an admin. One way to do that is with the "Make Admin" button in the Debug menu in the footer of the test site.

![image](https://user-images.githubusercontent.com/1495809/52085603-998c5380-25f0-11e9-9577-c98a3010a6a0.png)

**Comment by ChesterSng** [comment]
I'd like to give this issue a try!

**Comment by Alys** [comment]
@ChesterSng thanks! Post here if you have any questions.

**Comment by ChesterSng** [comment]
Hi @Alys can I ask where hall:getHero calls in the below code inside `website/client/components/hall/heroes.vue`?

`let hero = await this.$store.dispatch('hall:getHero', { uuid });`

**Comment by paglias** [comment]
@ChesterSng it comes from website/client/store/actions/hall

**Comment by ChesterSng** [comment]
Thanks @paglias!
Can I also ask where can I view/modify the API? 
Currently this link here is v3: https://habitica.com/apidoc/#api-Hall-GetHero
I noticed in the code that v4 is used also. Is there a seperate documentation for it?

Edit: I realised that it calls this function.

https://github.com/HabitRPG/habitica/blob/2eab8b2c8b78fb4f0cb681632c99c9f68c543773/website/server/controllers/api-v3/hall.js#L160-L184

Do you want me to modify this function so that it can take in either a UUID or a Username? Or create another function?

**Comment by ChesterSng** [comment]
How do I add someone to the contributor list? For example, if I have made another account, how to add that account to the contributor list to test?

**Comment by Alys** [comment]
That shouldn't be needed for testing since the search needs to work regardless of whether the searched-for user has a contributor tier, but you can add a tier to a user by filling in the fields that you see after you've searched for this User ID. The prompts in and under the empty fields should indicate what goes in there. The "Contributions" field can be left blank.

**Comment by Alys** [comment]
> Do you want me to modify this function so that it can take in either a UUID or a Username? Or create another function?

In my opinion, it would be best to modify that function but staff post here to say otherwise, do what they say.

**Comment by ChesterSng** [comment]
Thanks for your replies!

> That shouldn't be needed for testing since the search needs to work regardless of whether the searched-for user has a contributor tier, but you can add a tier to a user by filling in the fields that you see after you've searched for this User ID. The prompts in and under the empty fields should indicate what goes in there. The "Contributions" field can be left blank.

So all the accounts that I have created locally are supposed to appear under this list when I visit `/hall/contributors` right?

**Comment by Alys** [comment]
No, only accounts that have contributor tiers should appear there, but mods have the search form to search for any user (not just a contributor).

**Comment by ChesterSng** [comment]
Hi sorry got another question again:

1.) I made another account and got its user id:
![image](https://user-images.githubusercontent.com/39242483/52470683-de545380-2bc9-11e9-977a-72b1dbf8a8b9.png)

2.) I logged into another account and got admin rights and did a search using the user id copied from above.
3.) After clicking Find User:
![image](https://user-images.githubusercontent.com/39242483/52470817-2e331a80-2bca-11e9-8ed1-c96c27f40e65.png)
4.) Nothing appears and I get the following in console:
![image](https://user-images.githubusercontent.com/39242483/52470795-19568700-2bca-11e9-8f1a-40b99da70346.png)

**Comment by ChesterSng** [comment]
Hi @Alys I made a PR, can you see if it is correct, having a bit of problem testing as seen above. Sorry for the trouble!

**Comment by Alys** [comment]
I'm replying to this in the PR since this is specifically about the code in that PR, rather than about the issue itself. :)
