### ISSUE TITLE
cron health point loss notifications appearing twice

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10976]
As reported by webbie @webbie_at (03117605-1b3f-4b42-a0e2-a57b135f6457):

"for some time (many weeks) i noticed that the messages about how many health points i lost when starting the day appear twice. sometimes i can check if they are subtracted twice, too: they are not, i only lose them once."

I noticed that on my own account once a couple of days ago (I didn't check if the health was subtracted twice or just once).

**Comment by majestic-owl448** [comment]
I noticed that the same thing happens often with the notification for mana gained at cron, today it appeared twice

**Comment by SabreCat** [comment]
Happens to me constantly!

**Comment by paglias** [comment]
This was fixed by #12179
