### ISSUE TITLE
Grand Gala seasonal equipment should not appear locked when you already own it

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10989]
If you lose a piece of seasonal equipment due to death, you can buy it back at any time (which is the correct, desired behaviour) but in the Market and Rewards column the gear shows an icon and text that incorrectly indicate it's only available for a limited time (screenshots below). The icon and text should not be there.

This applies to any seasonal equipment which is in the user's account with a value of `false` (i.e., gear they used to own but lost).
This does not apply to any new seasonal equipment (i.e., gear that's not in the user's account at all - no `true` or `false` value).

In this screenshot, the purple clock icons in the top left of the gear boxes should not appear:
![image](https://user-images.githubusercontent.com/1495809/52698839-168bd580-2fc0-11e9-802d-49d8834ebd9c.png)

In this "buy now" confirmation screen, the "Available until [date]" text near the bottom should not appear:
![image](https://user-images.githubusercontent.com/1495809/52698906-42a75680-2fc0-11e9-8a65-31cae5d8984b.png)

NB: The "Limited Edition 2013-2014 Winter Gear" text near the top of that screen does not need to be removed. It's a permanent part of the gear's description.

**Comment by HydeHunter2** [comment]
I'd like to take this
