### ISSUE TITLE
I've died, but should have had 1 life

### ISSUE THREAD

**Issue by samoKroslak** [HabitRPG/habitica#1099]
hi, 

I was trying to get my rewards before levelling up. I've had 4 life and 0 gold, so I've tried to click on reward which costs 3 gold, so 3 life should have been dropped. What can I say, I like living on the edge :D 
Instead, my life dropped to 0 and I've suddenly died. 
Is it some kind of rounding issue/bug in current life calculation?

**Comment by wizonesolutions** [comment]
...wait, we can buy rewards with HP!?

**Comment by samoKroslak** [comment]
well, kind of, 

imagine you have 299/300 exp and full life and 50 gold 
now I would buy equipment for 45 gold, 5 golds remains in my wallet 
then I have a specific reward which costs 5 gold, I want to buy it 10 times, so I buy it first time - gold is subtracted from my wallet 
I buy it second time, warning comes up, that this will harm your HP, click OK and the reward is "bought" for HP 

that's what I meant

**Comment by wizonesolutions** [comment]
ah, I never even knew I could buy rewards for HP.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
