### ISSUE TITLE
removed from Challenges inappropriately

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10999]
As reported by @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c):

"I just noticed something very odd... Looking through my task list, several challenge tasks I had were no longer associated with the challenges I joined to get them (no megaphone icon, I could delete them as normal), but I'm certain I never left those challenges and the challenges had not ended. I have re-joined all of the challenges in question now, but this was very alarming... The challenges affected were: [Take This February](https://habitica.com/challenges/f0828ccc-f567-47ab-9c22-18c335c9cad9), [Humorous Haiku](https://habitica.com/challenges/81e4fc2f-fb6d-40b3-b80a-4c4839b302bb), [Flow 3.0](https://habitica.com/challenges/6681a01b-d0e3-4053-86dd-2160ffef5541), and [Imperfect is good](https://habitica.com/challenges/d35764fd-dd7b-42bb-866d-d3e4eb00eb4e). Not all of my challenges were affected. It was not simply ones I'd recently joined; I joined some at the beginning of February which were affected, but one that I joined yesterday was not affected."_

In Loggly, I've gone back to late January without finding anything obviously connected.

I've found evidence in the tasks that there definitely was a problem. I searched for only tasks related to the challenges, and stopped when I found these two so there might be more examples.
```
{
    "_id": "8918c3c9-0282-4bb2-8c62-7d1346c98168",
    "challenge": {
        "taskId": "3ffff4e1-b961-4bc8-9818-adc9f2b3ba2a",
        "id": "d35764fd-dd7b-42bb-866d-d3e4eb00eb4e",
        "shortName": "Sufficient"
    },
    "tags": [
        "d35764fd-dd7b-42bb-866d-d3e4eb00eb4e"
    ],
    "text": ":sunglasses: Share with the guild",
    "createdAt": "2019-02-17T02:08:22.515Z",
    "updatedAt": "2019-02-17T02:08:22.515Z"
}
 
{
    "_id": "c52d3ad0-08af-472c-855a-0021cd66ed70",
    "challenge": {},
    "tags": [
        "d35764fd-dd7b-42bb-866d-d3e4eb00eb4e"
    ],
    "text": ":sunglasses: Share with the guild",
    "createdAt": "2019-02-04T21:55:12.608Z",
    "updatedAt": "2019-02-13T05:09:49.923Z"
}
```

```
{
    "_id": "8a6a9f0e-67ef-4b03-b1a1-a901342bae52",
    "challenge": {
        "taskId": "5e57d1cb-be33-4375-958f-73bb643b302e",
        "id": "81e4fc2f-fb6d-40b3-b80a-4c4839b302bb",
        "shortName": "Humorous Haiku Challenge"
    },
    "tags": [
        "81e4fc2f-fb6d-40b3-b80a-4c4839b302bb"
    ],
    "text": ":laughing: Post a humorous haiku in the [Court Jesters Guild](https://habitica.com/#/options/groups/guilds/fddaeafc-125c-4b43-a339-14c1d37634e8)",
    "createdAt": "2019-02-17T02:11:10.344Z",
    "updatedAt": "2019-02-17T02:11:42.307Z"
}
 
{
    "_id": "7609855a-9c59-4402-86ed-10f460847025",
    "challenge": {},
    "tags": [
        "81e4fc2f-fb6d-40b3-b80a-4c4839b302bb"
    ],
    "text": ":laughing: Post a humorous haiku in the [Court Jesters Guild](https://habitica.com/#/options/groups/guilds/fddaeafc-125c-4b43-a339-14c1d37634e8)",
    "createdAt": "2019-01-30T19:10:57.026Z",
    "updatedAt": "2019-02-13T05:09:49.923Z"
}
```

**Comment by majestic-owl448** [comment]
May the user have left the guild in which the challenges were kept or that issue has been fixed and is impossible for that to happen now?

**Comment by Alys** [comment]
Ah, sorry, that's a good question and I meant to include a note about it! That issue was fixed (https://github.com/HabitRPG/habitica/issues/7764 "Leaving the guild removes you from the challenges") although looking at it again now I've realised that the Android version is still open: https://github.com/HabitRPG/habitica-android/issues/906
However all of the challenges that ravenlune listed are "public challenges" (Tavern challenges) so leaving the group isn't relevant in this case.

**Comment by majestic-owl448** [comment]
It used to happen if one was a member of the Tavern guild (the one found in
the list of guilds, it still found in the iOS guild list but I don't see it
on the website), leaving the Tavern guild would cause that with public
challenge. May it be worth asking if they were a member of that guild and
then left it? Just to be sure that that is not the case.

>

**Comment by Alys** [comment]
Ha! The Tavern guild is still visible in Android too - I hadn't realised that but I've just checked now and it's there.
Also our logs show that ravenlune joined the Tavern "guild" in mid-February. From what I can see they are no longer a member now. I'll PM them to double-check, but I'll bet you're right @Ieahleen - genius,  thanks!

**Comment by Alys** [comment]
@Ieahleen You were right! Excellent work, thanks very much!

I'm closing this issue because we have two others already open which will prevent this happening to anyone else: https://github.com/HabitRPG/habitica/issues/7431 ("API must not include Tavern in list of guilds") and https://github.com/HabitRPG/habitica-android/issues/906 ("player should not be automatically removed from Challenges when leaving a Guild or Party" for the Android app). They've both been open for a while unfortunately but this recent activity has moved them to the top of the list when it's sorted by date.
