### ISSUE TITLE
Dailies STILL won't reset

### ISSUE THREAD

**Issue by LordGreyroad** [HabitRPG/habitica#10991]
I hate to post yet another one of these complaints, but from all of the many posts of this issue cropping up in the past 5+ years, I haven't found any place it's actually been resolved. Many of them refer to each other and are connected by moderators, but I haven't been able to find a resolution on any of them. 
For basic info of the issue: 
I'm not checked into the inn, nor have I ever been.
This has happened before, and I resolved it by changing my reset time to 8 am (it was 7:55 at the time), but it's past the reset time, hasn't reset, and it won't save when I attempt to use that feature to fix it again. 

I'm rather frustrated because I absolutely love the concept behind this app, but I've been using it for 2 days and already I've found more bugs than legitimately working features. Is this issue being worked on? Because most of the posts I've found are 5+ years old.

**Comment by paglias** [comment]
Hi @LordGreyroad, sorry about this, are you using the website or the mobile app? in which case, is that on android or ios?

Also could you post this in the Report a Bug Guild at https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac? As that it's where we handle all support requests
