### ISSUE TITLE
Equipment name very faint and weirdly aligned

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10992]
Reported by Maybe Steve Rogers, confirmed by me, screenshot:

![image](https://user-images.githubusercontent.com/8144640/52857292-9def5b00-311e-11e9-93c7-50ebd0d4a345.png)

The name of the item is there, but faint and bottom-aligned (where I would expect it to be centered vertically in the space available).

**Comment by reisturm** [comment]
If this is still available, I'd like to try and fix it.

**Comment by paglias** [comment]
@reisturm sure! thanks for the help and let me know if you have any question

**Comment by reisturm** [comment]
Should this UI match when you hover equipment on other parts of the site (i.e. shows name and description), or should it just show the name?

**Comment by paglias** [comment]
Probably a question for @Tressley

**Comment by citrusella** [comment]
I'm not Tressley but unless I've got a strong case of Mandela effect and this was never actually the case, the past behavior was just the title properly aligned and in the right color, whether or not that's intended going forward.

**Comment by paglias** [comment]
> I'm not Tressley but unless I've got a strong case of Mandela effect and this was never actually the case, the past behavior was just the title properly aligned and in the right color, 

I agree but I'm not sure about the color to use :)

**Comment by Tressley** [comment]
I'm here! You're all correct in your assumptions, but I think the vertical centering is actually a result of the item description not being included. As you can see in the mock-up example below, the name of the item starts 12px from the top of the tooltip, but without a description it easily looks like a header. The font-color should be `#FFFFFF`

![image](https://user-images.githubusercontent.com/2686586/58030852-51d0ff80-7aed-11e9-9f32-58305e93e551.png)
