### ISSUE TITLE
[Suggestion] A Possible Easy To Implement RPG Element (With Marketing Value)

### ISSUE THREAD

**Issue by The-Bard** [HabitRPG/habitica#110]
To begin allow me to say the ingenuity of turning a task-tracking program into an RPG had me hooked immediately and has already begun to help keep me motivated and organized in jsut a matter of days. The RPG element and excellent rewards and penalties help make the program endearing to me, and I'm sure everyone else here. This thread is just to give my possible contribution if it hasn't been posted already.

I love the leveling system, and have achieved level two already. I've yet to see what the effect of leveling does except give me a feeling of accomplishment in my day (which is the goal for the End-User). I've read already that there will be party settings, and avatar decorations, pets, mounts(?), etc to be implemented.
I was just thinking what if we added an "Exploration" element. Some basic incentive that could simultaneously decorate the page, and possibly bring in revenue (See number 6).
Here's my idea:

1 - When the End-User first begins the program their character is level one, and has access to one Location (A new, more marketable name could be made... maybe "dungeon"?). The Location will have a generic, harmless name like "lollipop forest" or "peaceful meadow".

2 - The Location chosen will essentially be the "Background" of the program... OR be an environment the avatar is set upon. Either way it will have an aesthetic effect.

3 - As the avatar levels up more environments will become available (Maybe one more at level 5, 10, 20, 35, Etc^n)

4 - The End-User may change the Location at will, but perhaps a limit to once per day, or some equivalent control scheme.

5 - The Locations may have some effect besides aesthetics. An experience effect or health effect perhaps? Maybe certain rewards are cheaper while in a certain Location? I'm thinking that an effective method of implementing a change of game mechanics would be to lower one field of play and increase another (Maybe greater exp gain at the "Arena" but greater H.P. loss)

6 - A method of revenue would be to have certain Locations costs tokens. Maybe have the levels that new environments are gained less frequents than in point 3, so it encourages the End-User to purchase them for tokens. Some Locations could cost more (Exact price could be determined through the combination of the effects it grants and popularity). Perhaps make Locations buy able in packs, but still have a minimum Level to explore (In order to retain the RPG element.)

7 - Entering a certain Location could unlock new in game rewards that can be purchased... OR make certain rewards purchasable only in certain Location thus encouraging the End-User to change frequently.

8 - Special items could be found if many of tasks were accomplished while in a certain Location, such as avatar items, trophies, etc. This would also contribute to the RPG element. 
*Edit 8.1 - Perhaps make some of the items discovered become available in the shop instead of being granted to the player immediately. And perhaps make it available in the shop only once, then it must be "Re-Discovered"

*Edit 9 - Perhaps make it so each Location has a "Exploration" Value whcih would be used to track when discoveries are made (This could be hidden or given to the End-User, either has it's pros and cons). But alongside advancing in each area over time, if a player is acting on - Habits or missing dailies then the "Exploration" Value could decrease. If the Value is shown to the player it would be another motivational tool ( @the-economancer  )
*Edit 9.1 - Changing from one Location to the next may be a reward item that costs gold.
*Edit 9.2 - Maybe exploring the Location itself may be a reward item also.

I'll be adding to this list as I come up with new ideas and get feedback. For now something suddenly came up that I need to do so I'll return in a few hours and check back every so often.
I'd love to here @lefnire 's opinion of this, and how else revenue and Locations could be implemented.
(Also any better names for this idea)

**Comment by ghost** [comment]
I love all of those idea and item 8 is of particular interest to me. Care to elaborate further on it?

**Comment by the-economancer** [comment]
I think the central thing to consider for any new feature would be "How does this contribute to my ability to get things done/develop new habits", after all that is the point of this right. At least I'm viewing it as a game to help you get things done, rather than things you do irl to advance in a game. I don't really see how locations would change things. Not to say that they couldn't be implemented, but it isn't really necessary. :-/

**Comment by racuna** [comment]
Nice idea. But must be very simple to understand for the beginer and get more complex with levels.

**Comment by The-Bard** [comment]
@Neohuman Regarding item 8. While remaining in a particular Location, if there was particular progress made regarding Habits, and the Todo list (Not Dailies considering those are supposed to be completed everyday and their frequency would make it inappropriate to counts towards the "Discovered" items in locations.) Perhaps if each location for the End-User kept track of how many Todos and Habit +'s were made over time (Even if Location A has earned 3 one day and the next Location B earned 5, each Location would accumulate over time...). Upon reaching certain points the End-User found a Treasure Cache (+5 gold), or Slew a Boss (+5 Exp.), or found a Small Potion (+5 hp). Upon reaching extremely high point accumulations the rewards are greater: Found a Gem (+7 gold), or found a Token, or found a Spell Scroll (+25% exp gain for 24 hours). All of these rewards would encourage the player to get tasks done, especially an item such as the Spell Scroll which would encourage them to complete many tasks and habits in a short period of time. As for Avatar items or Pets they could be discovered but must be bought using in game gold to unlock... Just giving it to the End-User seems to generous for motivation... personally I would rather discover something and then have to decide what to spend my gold on: Reward such as an hour of video games or a nice looking helmet?

@the-economancer The possibility of Locations would motivate you so you could explore new area, or find new items such as the ones given above. But you do raise a good point, though a counter-point could be presented that even if the only reason a person is motivated is to advance in a game, then at least they're motivated. It's also an effective way to introduce new items and add to the RPG element.

@racuna Agreed, any element should be simple for the beginner, though I can't think of a way for this to grow in complexity over time besides finding new areas. Care to explain what you meant?

**Comment by The-Bard** [comment]
Also @the-economancer check Item 9 I edited in response to the very good point you made.

**Comment by lefnire** [comment]
brilliant guys. i skimmed, i'm gonna revisit this thoroughly when i get the time

**Comment by The-Bard** [comment]
Excellent, I'll keep updating as often as new ideas or solutions appear. I have a possible other implementation of HabitRPG but one designed towards Educational purposes, but I need to write it all down and organize properly before proposing the idea.

**Comment by the-economancer** [comment]
I guess I can see the value here. I'm just worried about detracting too much from the core features; exp to track your overall progress, rewards for positive reinforcement and hp for negative. Adding too many game elements runs the risk of shifting the incentive from doing things for their own sake (with tracking and rewards as motivators), and doing things for the sake of progress in the game i.e. adding frivolous tasks that are easily completed (not to mention outright dishonesty)

**Comment by horusofoz** [comment]
Only skimmed read but agree it's a great idea. I would add maybe movement points being added to the rewards for completing tasks with the character moving back and forth between areas where certain item types only available in certain items.

Would suggest not to go too far down this track though as focus is to get people doing things and not "playing the game".

**Comment by racuna** [comment]
Maybe put a text to describe every Location like the old Interactive fiction computer games (Zork)

**Comment by The-Bard** [comment]
Alright so some more possible tweaks...

@the-economancer Ultimately you're correct, my idea does detract from the main idea of the program. Perhaps it can be changed a bit more to guide the focus back to motivation and not the game so going to the next comment:

@horusofoz I like the idea of changing the Exploration of Locations from being a passive part of the program to being an active, but less frequent, part of the program. Perhaps not only does it take gold to move between Locations, but also gold to explore within a Location. The latter would work well, my only problem is that it costs gold just to explore an area... the former makes perfect sense though.

@racuna Of course!

**Comment by hookang** [comment]
Locations, Themes, Got it. Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
> 1 - When the End-User first begins the program their character is level one, and has access to one Location (A new, more marketable name could be made... maybe "dungeon"?). The Location will have a generic, harmless name like "lollipop forest" or "peaceful meadow". 

[Ongoing Adventure](https://trello.com/c/edwHxp5G)

> 2 - The Location chosen will essentially be the "Background" of the program... OR be an environment the avatar is set upon. Either way it will have an aesthetic effect. 
> 3 - As the avatar levels up more environments will become available (Maybe one more at level 5, 10, 20, 35, Etc^n)

[Ongoing Adventure](https://trello.com/c/edwHxp5G) and [Backgrounds](https://trello.com/c/6P9dDIly)

> 4 - The End-User may change the Location at will, but perhaps a limit to once per day, or some equivalent control scheme. 
> 5 - The Locations may have some effect besides aesthetics. An experience effect or health effect perhaps? Maybe certain rewards are cheaper while in a certain Location? I'm thinking that an effective method of implementing a change of game mechanics would be to lower one field of play and increase another (Maybe greater exp gain at the "Arena" but greater H.P. loss) 
> 6 - A method of revenue would be to have certain Locations costs tokens. Maybe have the levels that new environments are gained less frequents than in point 3, so it encourages the End-User to purchase them for tokens. Some Locations could cost more (Exact price could be determined through the combination of the effects it grants and popularity). Perhaps make Locations buy able in packs, but still have a minimum Level to explore (In order to retain the RPG element.)
> 7 - Entering a certain Location could unlock new in game rewards that can be purchased... OR make certain rewards purchasable only in certain Location thus encouraging the End-User to change frequently.
> 8 - Special items could be found if many of tasks were accomplished while in a certain Location, such as avatar items, trophies, etc. This would also contribute to the RPG element. 
> *Edit 8.1 - Perhaps make some of the items discovered become available in the shop instead of being granted to the player immediately. And perhaps make it available in the shop only once, then it must be "Re-Discovered"
> *Edit 9 - Perhaps make it so each Location has a "Exploration" Value whcih would be used to track when discoveries are made (This could be hidden or given to the End-User, either has it's pros and cons). But alongside advancing in each area over time, if a player is acting on - Habits or missing dailies then the "Exploration" Value could decrease. If the Value is shown to the player it would be another motivational tool ( @the-economancer )
> *Edit 9.1 - Changing from one Location to the next may be a reward item that costs gold.
> *Edit 9.2 - Maybe exploring the Location itself may be a reward item also.

Perhaps some form of #642 World Adventures would interest you. 
- A proposal there is completion of tasks allow for change of location.
- Perhaps certain backdrops or location design elements could cost tokens
- Quests through the locations would be one way to find items along the lines of [Quests](https://trello.com/c/VPPjVRlF)
