### ISSUE TITLE
closing one modal causes a second to close

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11009]
As reported by Alisa / @AntimonyCat (a1c898ea-8920-47f2-bf48-ef1f19d066c7):

"Whenever I check in for the first time on desktop, if I have two popups I never get to read the first one. (E.g. the one for my daily check in + one for a completed quest)."

"I'm not sure when exactly the first window closes. I see it for a split second before the second pop-up shows up either on top of the first one or in place of it. When I dismiss the second one the first one is no longer there."

"Chrome: Version 72.0.3626.109 (Official Build) (64-bit), Windows 10 Pro."

**Comment by shanaqui** [comment]
More info added today:

Alisa @AntimonyCat (a1c898ea-8920-47f2-bf48-ef1f19d066c7): "@Alys I paid more attention to how this bug looked this morning - the first pop-up window actually disappeared just before the second popped up, but too quickly for me to even have a chance to read it."

**Comment by thebat137** [comment]
I also have had this problem for a while.  For me, the specific popup that I never get to see is the check-in popup.  All the others (record yesterday's activity, quest completion, Bailey, etc.) always seem to be able to "take turns" properly, but the check-in one always goes away before I get to see it properly, without me having taken action on my own to dismiss it.

**Comment by paglias** [comment]
Is this still an issue? Login check ins and other modals all appear correctly after RYA

**Comment by thebat137** [comment]
@paglias, it seems to be working for me now.

**Comment by Alys** [comment]
I don't recall recent reports of it.
