### ISSUE TITLE
Can't type in who to award challenge to

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11006]
Reported by LaMama Fox: 

> Hi! I've been trying to award a winner to this challenge https://habitica.com/challenges/5e6a9727-da6c-47ef-ba70-99d28d19b50f. I can't type or copy into the "select participant" box in either their end challenge box or the participant box. Nor can I scroll down through the participants. The winner is Lonewarg.
> 
> I've tried refreshing, quitting Safari and reopening, waiting and trying again, waiting until everything has a chance to load. So far, no luck.

I've reproduced this in Chrome, and confirmed it applies to all challenges. Screenshot shows exactly the field we're referring to.

![image](https://user-images.githubusercontent.com/8144640/52978212-33f9de80-33c8-11e9-9116-970ffbc66f90.png)

**Comment by SabreCat** [comment]
The behavior I'm seeing is that you can tab to the field and type in it, but not click it. Is that what others are experiencing?

**Comment by shanaqui** [comment]
I can't tab into it either (Windows/Chrome).

**Comment by SabreCat** [comment]
fixed in ada09f3d5ae4d4
