### ISSUE TITLE
Tag text overlaps and tags are not in correct sort order and groupings in task edit screen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11008]
As reported by @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c) and confirmed by @cTheDragons:
"The text for longer tags now overlaps, making several tags unreadable as seen [below]"

ravenlune also says:
"it seems like the issue is this bit in the CSS:
`#task-modal .option label { max-height: 30px; }`
For the time being, overriding that part with max-height: none !important; seems to work fine and that formats it exactly like the tags filter at the top of the tasks screen. I don't know if saying this was needed or not, I guess I felt like I should point it out--but it's probably more complicated than just that, and I've personally got very little CSS knowledge."

Also from cTheDragons:
"When viewing tags on task (Not editing them at the top).It would be also good that the challenge and group tags are separate and the tags in Tag order" [That's how they used to be]

I'm marking this as high priority because it makes at least some of the tags unusable.

This is a recent problem and might have been introduced by https://github.com/HabitRPG/habitica/releases/tag/v4.84.1
![image](https://user-images.githubusercontent.com/1495809/52989703-5b948980-3450-11e9-835e-da55871990fc.png)

**Comment by Alys** [comment]
New information from ravenlune about the tags overlapping:

"it seems like the issue is this bit in the CSS:
`#task-modal .option label { max-height: 30px; }`
For the time being, overriding that part with max-height: none !important; seems to work fine and that formats it exactly like the tags filter at the top of the tasks screen. I don't know if saying this was needed or not, I guess I felt like I should point it out--but it's probably more complicated than just that, and I've personally got very little CSS knowledge."

**Comment by HydeHunter2** [comment]
Hey!
I'd like to take this

I managed to repeat this bug:
![github](https://user-images.githubusercontent.com/46248839/55675780-f85f9900-58cf-11e9-8390-2bce857551a9.png)

The bug also appears if you enter a very long word: 
![github](https://user-images.githubusercontent.com/46248839/55675828-1d084080-58d1-11e9-8c00-1a787c7aa42f.png)

**Comment by Alys** [comment]
@HydeHunter2 Thanks! Please go ahead! Comment here if you have questions.

**Comment by HydeHunter2** [comment]
I've corrected tag text overlapping:
![Github](https://user-images.githubusercontent.com/46248839/55685964-7e2d2400-5964-11e9-9278-a0f93803ec9b.png)

But I'm not completely sure what that means:
> "When viewing tags on task (Not editing them at the top).It would be also good that the challenge and group tags are separate and the tags in Tag order" [That's how they used to be]

I'm new in Habitica and I don't know how they used to be. Could you clarify?

**Comment by HydeHunter2** [comment]
I made two pull requests, as they fix different things

**Comment by fornsss** [comment]
sabe jones i kill you

W dniu poniedziałek, 22 kwietnia 2019 HydeHunter2 <notifications@github.com>
napisał(a):
