### ISSUE TITLE
Username no longer clickable in Hall of Heroes

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11014]
Previously, clicking on someone's username in the Hall of Heroes brought up their profile. It no longer does, so contributors can no longer use the Hall of Heroes to find and message each other.

> _@cTheDragons (bc10ec41-4213-4482-bbb8-558e3c3ea8d5): ''**FOUND BUG maybe?**
> 
> Not sure if this actually a new feature, or a bug, but I can no longer view the profile of users in the Hall of Heroes. 
> 
> I use to use the Hall of Heros as the Pirate Captain when finding users who can help with translation of text when hailing guilds. Thanks''_"_

**Comment by easyMaxi** [comment]
I am not sure, but I think this can be traced back to this change:
https://github.com/HabitRPG/habitica/commit/be4c777382f27f687c486938697bf644a8504f7f#diff-2e454d1deafd340139e9cff88b254c57L87

I just found this project and will try to run a local version in the next days and try to fix that. But can't promise anything.

**Comment by LinaJohnson** [comment]
@Alys interested in this one too.

**Comment by Alys** [comment]
@LinaJohnson Thanks! Please go ahead! :)

**Comment by paglias** [comment]
@LinaJohnson the pr https://github.com/HabitRPG/habitica/pull/11087 has most of the work already done if you want to start from that!

**Comment by LinaJohnson** [comment]
awesome thanks @paglias!

**Comment by pskupinski** [comment]
@Alys
Hello, @margsliu and I are able to take on this issue and could have a pull request submitted within the coming week. Would it be okay for us to start working on it?

**Comment by Alys** [comment]
@LinaJohnson How are you going with this? Do you want to keep working on it or can @pskupinski take it over?

**Comment by Alys** [comment]
@pskupinski I'm sorry about the delay! You're welcome to take this on if you'd still like it!
