### ISSUE TITLE
Official Challenges not sorting to top

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11018]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Challenges marked "Habitica Official", such as the monthly Take This challenges, should show up at the top of the "Discover Challenges" view. Currently they aren't--you have to either filter on the category or do some very painful manual scrolling to find them.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
None relevant in evidence.

**Comment by alecbrick** [comment]
I'll take a look at this.

**Comment by Alys** [comment]
@alecbrick Thanks! Post here if you have questions.

**Comment by alecbrick** [comment]
Bumping this issue. At the moment, there’s not an efficient solution. If we undeprecate the “official” property, though, we can easily query on that. Thoughts?
