### ISSUE TITLE
Using a skill on a task can check off checklist items

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11028]
_EDIT: See the first comment for a confirmation of the desired fix._

> thebat137   @thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a) [web] 
> I am seeing what I believe is a regression in the way using skills on tasks works.
> 
> What I expect (and what I think used to happen): I click on the skill, my cursor picks up the skill, and then I click anywhere on the box for a task and the skill is applied to that task, without checking any checkboxes or otherwise affecting the task status.
> 
> What actually happens: If, while my cursor is carrying a skill, I click on a task and happen to do it in an area belonging to one of that task's checklist items, not only is the skill applied to the task, the checklist item is also checked off (or unchecked if it was already checked).
> 
> I'm not sure if other skills have this problem, but the one I've been noticing it with is the warrior skill Brutal Smash.

Tested and confirmed in Windows 10 / Chrome.

I agree with the poster that this behaviour is unexpected, and I think at the very least should be consistent (i.e. clicking with the skill near the main checkbox should check off the whole task, if clicking with the skill can check off the subtasks).

**Comment by Alys** [comment]
The desired fix for this issue is the previous behaviour:
> I click on the skill, my cursor picks up the skill, and then I click anywhere on the box for a task and the skill is applied to that task, without checking any checkboxes or otherwise affecting the task status.

**Comment by rjbernaldo** [comment]
I'd like to give this one a try if it hasn't been fixed.

Please let me know @Alys :)

**Comment by Alys** [comment]
@rjbernaldo Thank you! Please go ahead. Comment here if you have questions.

**Comment by rjbernaldo** [comment]
Please take a look @Alys and let me know 👍

**Comment by rjbernaldo** [comment]
Updated my PR to fix the issue according to the desired behavior mentioned above. It's a simpler solution actually, just wrap `castEnd` inside a setTimeout to add the execution to the back of the queue and let the immediate event handlers handle the event.

**Comment by Alys** [comment]
@rjbernaldo Thanks! I've marked your PR as ready for review by the staff.

**Comment by rjbernaldo** [comment]
Any update or feedback on this @Alys ?

**Comment by Alys** [comment]
@rjbernaldo Nothing yet! :) The staff will post here when they've reviewed your PR with either a message stating that it's ready to be merged or with feedback about code that would need to be adjusted. If you'd like more information about the review process, have a look at [Using Your Local Install to Modify Habitica's Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API#Acceptance_of_Your_PR_and_the_Release_Cycle), in particular the sections for "Having your Pull Request Tested and Reviewed" and "Acceptance of Your PR and the Release Cycle".

**Comment by rjbernaldo** [comment]
Alright, thank you!
