### ISSUE TITLE
markdown should be parsed in Private Message (PM) previews

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11027]
As reported by @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c):

"Markdown doesn't render in PM previews, when it does in the actual message being previewed."

![image](https://user-images.githubusercontent.com/1495809/53297879-c854bd00-3870-11e9-9373-44b999235288.png)

I.e., markdown parsing needs to be done in the preview page on the left-hand side of the PM modal.

**Comment by paglias** [comment]
I think the preview should only show the text, rendering markdown there would ruin the design when using big elements, maybe we can just render normal text without the markdown formatting @Tressley

**Comment by Alys** [comment]
Those previews will often be messages written by other people, and if the user viewing the preview doesn't understand markdown (quite common), then the preview will appear weird and buggy. It would need to have the markdown parsed for them to understand it.

If the main objection is that header markdown will produce text that's too large, it might be best to parse the markdown normally but apply some extra css rules to the preview section so that headings are displayed in a non-heading font there.

**Comment by paglias** [comment]
I'd say it's pretty normal around the web to have a preview of 2 lines not show any formatting apart from the basics, also because it could create problems with clickable links since clicking on the preview also opens the message but let's see what @Tressley thinks

**Comment by Alys** [comment]
That's what adjusting the css could do - it could change the text that otherwise would have special formatting (large headings, also bold/italics/code text if you want) and would make it look like normal text. It's an easy way to "remove" markdown.

**Comment by Tressley** [comment]
I think @Alys suggestion is a good solution. We need to parse the Markdown so the message preview appears properly and without Markdown code. Alys suggestion just styles that Markdown to look like the preview styling in the preview column for all Markdown text elements.

**Comment by paglias** [comment]
The problem is that the moment you fully parse markdown you end up with
HTML tags like h1,h2, ... Which have their own default styling which isn't
super easy to remove.

Also, what you would need rules to hide images, links,...

If instead we have the preview only parse a subset of markdown like bold
and italics we can get some minor formatting without having to write
hundreds of lines of css

Il Mer 27 Feb 2019, 21:01 Tressley Cahill <notifications@github.com> ha
scritto:

**Comment by Tressley** [comment]
The preview shouldn't show any Markdown formatting though. Let's look at Alys' example -- What would we need to omit the `####` from the text, but still show the "Heading 4" text as it is styled in the preview column?

**Comment by paglias** [comment]
I think we can tell the markdown library to only parse some tags, so for
example headings would be formatted as plain text (removing the markdown
syntax) while formatting some tags that we choose like bold, italic,...

Il Lun 4 Mar 2019, 15:21 Tressley Cahill <notifications@github.com> ha
scritto:

**Comment by HydeHunter2** [comment]
I'd like to take this

**Comment by HydeHunter2** [comment]
@paglias -- I can't find the method that filters tags in `markdown-it` [documentation](https://markdown-it.github.io/markdown-it/#MarkdownIt).
There is `md.configure('zero')`, but it is not what we need (i.e. it doesn't parse anything)

I see no other way but to use `.replace('<tag>', '')`(not the best solution I think).
Could you(or someone else) help me?

**Comment by paglias** [comment]
@HydeHunter2 ah, I thought 

> There is md.configure('zero'), but it is not what we need (i.e. it doesn't parse anything)

would be the best solution but not if it doesn't parse anything...

What about rendering the markdown to html and then take the text from there? see https://stackoverflow.com/questions/822452/strip-html-from-text-javascript for example

**Comment by Tressley** [comment]
@HydeHunter2 -- Invited you to our Zeplin project. You can view the Messages artboard here: https://zpl.io/2GG0B1j

**Comment by HydeHunter2** [comment]
Thank you :]
