### ISSUE TITLE
profile URL for non-existent / deleted account should show an error message

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11020]
If you click on a profile URL for an account that does not exist (e.g., when someone has deleted their account), you see just whitespace where the body of the page should be - i.e., there's no message to indicate why loading the profile failed. You can see an example of this at https://habitica.com/profile/12345678-b5b9-4bb4-8b82-123456789abc which uses a User ID that isn't associated with any account.

There should be a message to say that the account does not exist. 

I suggest using the existing string `messageDeletedUser` ("Sorry, this user has deleted their account.") which is what you see when you click on a name in chat after the associated account has been deleted. If we decide that a different message would be appropriate, we might want to consider modifying `messageDeletedUser` instead of creating a new string to keep the message consistent in both places where it can appear.

@Tressley I'm marking this as needs design

_Thanks to citrusella for reporting this._

**Comment by Tressley** [comment]
I'm not entirely sure we need a new design for this. I propose we re-use our existing 404 page, but bring it within Habitica for logged in users so they have the correct navigation (instead of the one from /static).

![image](https://user-images.githubusercontent.com/2686586/53815494-c3a69d80-3f2f-11e9-949c-f0dade568854.png)

**Comment by Alys** [comment]
I think if I were a regular user, I wouldn't realise I was seeing a 404 because the player had deleted their profile; I'd think it was happening because of a bug. It would feel more like the profile page feature was broken/moved, not that the player didn't exist.

**Comment by Tressley** [comment]
While I could potentially see a small amount of friction, it is not an uncommon pattern to use a 404 page as the catch-all for non-existent URLs, including profiles. GitHub and Twitter are perfect examples.

https://github.com/Alys100200300
https://twitter.com/Alys100200300

Removing needs design as this is just bringing the 404 page in-app.

**Comment by kushpvo** [comment]
I can take this up. What's the final solution?
404 page or custom message page?

**Comment by Alys** [comment]
@kushpvo Thank you!

Tressley's decision is final so the 404 page should be shown.

**Comment by kushpvo** [comment]
@Alys Alright, I'll work on it! Thanks!

**Comment by Alys** [comment]
@kubiku I've marked this as help wanted again but if you still want to work on it, please post here and I'll label it as in progress for you again.

**Comment by jacobguinther** [comment]
Is this issue just scoped to the users actual profile page or does it involve the modal that pops up on the chats as well?
I noticed that there is different behavior depending on if you click the avatar vs the username.
I was curious what the desired behavior of this modal would be for a deleted user.
1) Behavior 2 (show deleted users profile along with Deleted Account message)
or 
2) 404 Inside of modal

![Screen Shot 2020-05-19 at 7 11 38 PM](https://user-images.githubusercontent.com/54478555/82393957-fd64a680-9a04-11ea-977f-bd2a7fd27ffd.png)


![Screen Shot 2020-05-19 at 7 06 52 PM](https://user-images.githubusercontent.com/54478555/82393689-63046300-9a04-11ea-8079-777d1f395ed2.png)

![Screen Shot 2020-05-19 at 7 06 43 PM](https://user-images.githubusercontent.com/54478555/82393688-613a9f80-9a04-11ea-9f34-7643390dd775.png)

**Comment by Alys** [comment]
@jacobguinther Excellent question and thanks for the very clear screenshots!

The behavior should  be the same for clicking the avatar vs the Username.

Behavior 2 (show deleted users profile) is incorrect. The avatar image and names are being taken from the chat message (which is tolerable) but the dates and check-in count are fake data. They'll always default to today's date and 0 since the actual data has been deleted along with the account. So, that profile screen should not be shown at all.

However I like the Deleted Account message in the red notification bubble. My personal feeling is that it would be nice to see that in addition to the default 404 modal, since that makes it clear why the 404 is being shown.

If you'd like to work on this, that would be great. Post briefly and I'll mark it as in progress for you.

**Comment by jacobguinther** [comment]
@Alys Thanks for the clarification. I will work on this.

**Comment by Alys** [comment]
@jacobguinther Great, thanks! I've marked it as in progress.
