### ISSUE TITLE
Selling a hatching potion displays the wrong price

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11038]
Reported by @JSn1nj4 (b1781515-6c3f-4314-a126-705b1e8390e8): "Hi. When I'm looking at hatching potion selling prices in the web app, it says 3 gold per potion. They still sell for the same prices that show in the mobile app (2 gold for some, 3 for others, 4 for the zombie and cotton candy, and 5 for the gold for example), but they display wrong on the web app. This may be trivial to fix (maybe), but I'd like to use this to finally be able to contribute if that's ok."

![image](https://user-images.githubusercontent.com/8144640/53648915-f18e9800-3c38-11e9-93ef-8d555a9bff86.png)

(Should net you 4 gold, and does: only the display is wrong.)

**Comment by JSn1nj4** [comment]
Reporting for duty! I'd like to use this as a way to finally start contributing to the codebase if that's alright.

**Comment by Alys** [comment]
@JSn1nj4 can you please look at https://github.com/HabitRPG/habitica/issues/10687 to see if that's the cause of the problem you noticed? If so, can you post there to say you'd like to work on it? We'd love to have your help!

If you think there's a different bug in addition to that one, let us know!

**Comment by JSn1nj4** [comment]
@Alys sure, I'll look at it. This may still be different though.

In my case, the sell price just says 3 across the board on hatching potions. I still have to finish getting the local instance set up, but I'll take a look once I'm finished getting it up and running.

**Comment by JSn1nj4** [comment]
@Alys I'm confirming that I do have the issue you linked to. I'm still planning to proceed at first as if these are separate issues unless I come across something suggesting otherwise. But thanks for linking me to that issue.

**Comment by JSn1nj4** [comment]
Confirming that, on a local install, the sale prices for hatching potions are all the same. Doesn't seem to be a caching issue (this is the first time I've gotten a local instance of Habitica running successfully).

**Comment by Alys** [comment]
For reference, there's comments about this at https://github.com/HabitRPG/habitica/issues/10687#issuecomment-469107911 and below.

@JSn1nj4 Thanks heaps for looking into this and posting the PR! We'll leave this issue open for now and it will be closed automatically upon merging of the PR.

**Comment by JSn1nj4** [comment]
@Alys glad to help!
