### ISSUE TITLE
API token is blank

### ISSUE THREAD

**Issue by jefah** [HabitRPG/habitica#1103]
I have a user ID but the API token field is blank.

**Comment by lefnire** [comment]
what's your user id?

**Comment by jefah** [comment]
7522bf38-341e-4fa1-ac45-510e91960117

Jeff

**Comment by lefnire** [comment]
updated, sorry bout that

**Comment by beingryu** [comment]
Hi, it seems I'm experiencing this issue too.

My user ID is e683d2d7-524a-4be4-b354-61f30bce5131.

Thanks!

**Comment by lefnire** [comment]
@beingryu I added an API token for you, you should be set. I'll look into what's causing this moment I can

**Comment by DeeDay** [comment]
This seems to be where to post this, so, I'm having the same problem. User ID is:  
c233db60-82b0-47a8-8992-6f0bad057cdc

**Comment by lefnire** [comment]
@DeeDay give that a shot

**Comment by DeeDay** [comment]
Thank you!

**Comment by tommuhm** [comment]
Hoi, i also have the same issue.

My UserID is: 33024ff8-a0ce-4dcd-ab98-b4b45e9d2641

**Comment by lefnire** [comment]
@tom-muhm fixed

**Comment by tommuhm** [comment]
Thanks :)
