### ISSUE TITLE
Help menu sub-items cannot be access on a mobile browser

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11043]
As reported by @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c) and confirmed by me:

"On the mobile/small window version of the site, if you expand the menu and then tap on Help, you cannot access any of the links in the dropdown menu (the one that appears when hovering over it in a larger window) because it immediately redirects you to the static FAQ."

The same problem doesn't occur for the other menu items because even though they do redirect you to the menu item's top-level page, the menu remains open and you can still click on the sub-items under the top-level item.

You can replicate the bug on a PC by shrinking your browser window until the menu changes to the mobile/small-window version. It's not a significant problem on a PC because you can hover over any top-level item to get access to the sub-items, but hovering is not possible on a mobile device.

I'm going to leave this as suggestion-discussion for a few days in case the staff want to comment on how this would best be fixed but I'll mark it as help wanted next week if there's no objections to that.

This bug occurs on mobile device browsers.

**Comment by HydeHunter2** [comment]
I'd like to take this.
Is it a good solution to add buttons with arrows, clicking on which will not cause a redirect?
They will be 20% (for example) of the width to make it easier to press.
Like this:
![GitHub](https://user-images.githubusercontent.com/46248839/57279115-dadd4500-70b0-11e9-98b9-bb6a94e0fcce.png)

## +

> ...even though they do redirect you to the menu item's top-level page, the menu remains open...

The fact that the menu remains open may seem buggy to someone(#11155).

If we fix this issue using the arrow buttons, then we can close the menu without losing the capability to click on sub-items.

How do you think?

**Comment by Tressley** [comment]
@HydeHunter2 -- I think this a good solution. Here's the Zeplin artboards: https://app.zeplin.io/project/59c16a1433075573feaa48fb/dashboard?seid=5cd1a9509941ae689f1fb3a3

**Comment by HydeHunter2** [comment]
it's excellent!
Thanks for the design.
