### ISSUE TITLE
Username searches in the Hall of Heroes should be case-insensitive

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11047]
As described in issue https://github.com/HabitRPG/habitica/issues/10972 and its pull request https://github.com/HabitRPG/habitica/pull/10980 , the Hall of Heroes allows moderators to search for users by the Username. Currently that search is case-sensitive. It should be case-insensitive. I.e., searching for "examplename" would let you find a user called "ExampleName". 

Any contributor who wants to work on this should read the top post at https://github.com/HabitRPG/habitica/issues/10972 to learn about how the moderator search feature works and how you can access it on your local install. https://github.com/HabitRPG/habitica/pull/10980/files will show you how the current case-sensitive search is implemented.

_(NB We're not considering this to be a bug in https://github.com/HabitRPG/habitica/pull/10980. We neglected to say that the search should be case-insensitive and so that PR did implement the search feature as intended at the time!)_

**Comment by JSn1nj4** [comment]
@Alys I'm willing to jump in on this.

**Comment by JSn1nj4** [comment]
@Alys can you confirm that the values searched on the back-end are always lowercase? I'm asking because I do see my UUID while testing contains only lowercase letters, and my user has a `lowerCaseUsername` value also.

**Comment by Alys** [comment]
@JSn1nj4 Thanks! Please go ahead, let us know if you have questions. :)
