### ISSUE TITLE
unallocated Stat Points count should be centred

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11049]
As DrPavelheer (3c2b1d99-c6f0-4e6e-a67a-bd8e023cfc7e) points out for the User Icon > Stats page:

"My unallocated stat points aren't centered in their circle, as seen here:"
![img](http://puu.sh/CWkXm/9d3f0ab315.png)

It's the same on my account.

Note that centreing should work correctly for 1 to 3 digits (unallocated stats ranging from 1 to 100 inclusive).

**Comment by Alys** [comment]
To be clear, it's the number in the orange circle after the "Stat Points" subheading.

**Comment by alecbrick** [comment]
I'll take a look at this.
