### ISSUE TITLE
Add "Firefox Chat Extension" to the Settings > API page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11042]
The [User Icon > Settings > API page](https://habitica.com/user/settings/api) contains a link to the Chrome Chat Extension. There should also be a link to the Firefox Chat Extension, which is at https://addons.mozilla.org/en-US/firefox/addon/habitica-chat-client-v2/

Both extensions do the same thing, the only difference being the browser they run on. Because of this, I think it would be most helpful if the same bullet-point entry was used for both extensions - that should make it obvious that you're not missing out on anything if you install only one of them. The bullet point line could read "[Chrome Chat Extension](https://chrome.google.com/webstore/detail/habitrpg-chat-client/hidkdfgonpoaiannijofifhjidbnilbb) and [Firefox Chat Extension](https://addons.mozilla.org/en-US/firefox/addon/habitica-chat-client-v2/)" and the paragraph under it could be changed to this:

"The Chat Extension for Habitica adds an intuitive chat box to all of habitica.com. It allows users to chat in the Tavern, their party, and any guilds they are in."

I'll leave this issue open as suggestion-discussion for a few days and then if there's no objections or changes to this approach, I'll change it help wanted. I'll mark it as good first issue since it will be ideal for a new contributor. EDIT: This is on hold while some changes are being made to the extension.

**Comment by Markkop** [comment]
Hey! This is a great first issue. Can I take it? I'm still setting up the development environment, but I'm pumped to contribute on Habitica and learn/practice VueJS

**Comment by Alys** [comment]
@Markkop Thanks, please go ahead! Comment here if you have questions.

**Comment by bmasetto** [comment]
@Markkop, do you still working on this issue? If not and if @Alys agrees, I could go ahead with this implementation.

**Comment by Markkop** [comment]
> @Markkop, do you still working on this issue? If not and if @Alys agrees, I could go ahead with this implementation.

I've finished this issue with #11375, but it can't be resolved before the extension being avaliable again in Firefox's marketplace.
https://github.com/HabitRPG/habitica-chat-extension/issues/49

**Comment by bmasetto** [comment]
Ok, @Markkop. What do you think about adding an “on hold” label to this issue in this case, @Alys?

**Comment by Alys** [comment]
@bmasetto "on hold" is usually used if an issue isn't suitable for someone to start working on it, but for this one there's already a full fix, so it's sort of borderline between the two situations. :) I'll leave it marked as "in progress".

As a general guideline, if you see an "in progress" issue that hasn't had any action for several weeks, it's okay to ask if the claimant is still working on it, but it's best to check first if there's already a pull request (which will be linked from the issue). Once there's a PR any conversation about it usually happens in the PR so you can follow the progress there.
