### ISSUE TITLE
config.jason/config.jason.example Does Not Exist

### ISSUE THREAD

**Issue by Grunksky** [HabitRPG/habitica#11040]
Hello, I am currently trying to [Set Up Habitica Locally on Windows](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Windows) and when I fork the Habitica repository then clone (git clone https://github.com/YourUsername/habitica.git), config.jason.example is not installed.

Windows 10

Any and all help is greatly appreciated
Thanks and Warmly,
IMC

**Comment by paglias** [comment]
Hi @InefableMusicalChemist the file is named `config.json.example` and it exists in your repo https://github.com/InefableMusicalChemist/habitica/blob/develop/config.json.example
