### ISSUE TITLE
"Start My New Day" button in RYA should not be clickable while a sync is progressing

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11058]
As discussed at https://github.com/HabitRPG/habitica/issues/10806#issuecomment-471237931 and at https://github.com/HabitRPG/habitica/issues/10386#issuecomment-464438026 (and its follow-up comments), when you are using the Record Yesterday's Activity (RYA) screen, if you complete a Daily and then click the "Start My New Day" button before the sync has finished, cron can halt part way through due to a VersionError.

The "Start My New Day" button should not be clickable while a sync is happening.

_(To anticpate a possible question, I do not know how to achieve this, but if any contributor has questions about it, post here and someone else might be able to help you!)_

_(~This would also be good to have in the mobile apps but I'll wait a few days for any comments about the website fix, and then ask the staff about the same being done on mobile apps. EDIT: [Done,  2019-03-14](https://habitica.slack.com/archives/C03P8RC34/p1552558905002000)~ EDIT: Phillip says this isn't needed on the mobile apps.)_

**Comment by Alys** [comment]
This would also be good to have in the mobile apps but I'll wait a few days for any comments about the website fix, and then ask the staff about the same being done on mobile apps.

**Comment by paglias** [comment]
If anyone wants to work on this the solution should work a bit like this: when you score a daily in the RYA modal a flag should be set that prevents clicking the start my day button until the request is complete

**Comment by LinaJohnson** [comment]
@Alys @paglias I'm interested in helping out with this one.

**Comment by Alys** [comment]
@LinaJohnson Great, thank you! Comment here if you have any questions.

**Comment by shanaqui** [comment]
@LinaJohnson Are you still planning to work on this? If so, please let us know!

**Comment by shanaqui** [comment]
I'll set this back to help wanted since there was no reply. :)

**Comment by Alys** [comment]
As an alternative to preventing the sync button being unusable until all syncs have finished, we could convert the RYA screen to use bulk task scoring, which was added in https://github.com/HabitRPG/habitica/pull/11389 , as indicated by matteo in this comment: https://github.com/HabitRPG/habitica/issues/8914#issuecomment-608553670

I'm marking this as suggestion discussion for the staff to comment on this suggested approach:

What I suggest is that we have two issues open for this, this easy one to adjust the button and another harder one to use bulk scoring (with clear links between them and we can close the easy one if someone starts on the harder one first). That would give us the best chance of getting a fix in sooner and then a better fix later. (However if that's not suitable, I think we should change this issue to make it solely about using bulk scoring.)

**Comment by Alys** [comment]
I've logged the new issue for using bulk scoring: https://github.com/HabitRPG/habitica/issues/12248
It's on hold until the bulk scoring PR is finished (sorry, when I wrote my previous comment here, I didn't realise that PR hadn't been finished yet).

**Comment by veeeeeee** [comment]
Closed in favor of using the bulk scoring approach in #12248

**Comment by paglias** [comment]
I think the idea behind this was, once bulk scoring is implemented, to disable the Start My New Day button after it's been clicked once to avoid issues where people click over it multiple times
