### ISSUE TITLE
Profile pages show previous player temporarily - loading is slow

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11051]
When you click on a player's avatar or name to view their profile, as soon as the profile modal appears, you see the details of the previous profile that you viewed. It's visible for long enough to be confusing (it looks like a bug or that you've clicked on the wrong person or that the person has dramatically changed their name and avatar since the time they posted a message). After a second or so (usually) the wrong profile is replaced by the correct one but the delay can be longer.

I think it would be less confusing if the profile modal initially appeared blank rather than showing cached data from the previous person, or if it didn't appear at all until the new player's data was ready to be displayed in it.

I'm leaving this as suggestion-discussion for the staff to comment on.

---

In addition to that, FolleMente / @OuttaMyMind (270f8744-3c6f-48d3-9bcf-e9dc79104168) has reported that sometimes the correct profile never appears:

"When I try to click on another persons profile, I have to reset the page in order to see their profile. I see the first person I originally clicked on pull up..."
"... As for the loading, it depends. Sometimes it'll load after a few seconds, but other times, it won't load at all. I usually keep it up for a few minutes."

I am guessing (although not with any evidence) that sometimes the new player's details weren't loading at all because of the recent server problems, and so I suggest that the slowness issue described above be fixed first, and then if we still have reports of the correct player's details never appearing, we can investigate further.

**Comment by godless-toast** [comment]
> When you click on a player's avatar or name to view their profile, as soon as the profile modal appears, you see the details of the previous profile that you viewed.

Yes, I've experienced this as well.

But another thing I experience is viewing a profile, and then I go to another page, say tasks. I open and start editing a task, then when I save it, sometimes that profile shows up again.

Then I might look at someone else's profile. Close it. Old one shows up again. It will keep showing up here and there, but refreshing fixes it. This is on desktop in Firefox.

My problem doesn't sound like this issue or #11066. Is there another issue for this?

**Comment by Alys** [comment]
@godless-toast I'm sorry we didn't reply to you before now. The issue you described with a profile reopening is https://github.com/HabitRPG/habitica/issues/11083

**Comment by SabreCat** [comment]
Do we have a good way of reproducing this? When I open profiles one after another, there is a bit of delay, but during that delay there's only a tiny strip of the modal visible, not the whole profile. Is it browser-specific?

I'll still flag this as worthy of help (in case we can just do a cache purge irrespective of visible issues), but it'd help contributors to know how to get this to happen!

**Comment by paglias** [comment]
I think this has been fixed by a PR this week, can anyone confirm?

**Comment by Alys** [comment]
Looking good to me! We can reopen if we see new reports of it.
