### ISSUE TITLE
German translation - question

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#1105]
I've just had a look at the German translatio, and it looks like a machine (or machine-assisted) translation for me, as it is at the moment.

I'm willing to help on translating, but German has two forms - the formal "Sie" (which is used at the moment) and the less formal "Du", which in my opinion would be better suited for a game. Is there a reason why the formal form was used? I would suggest switching to the less formal variation. As an alternative, one could offer a choice and do an additional version once the first one is done, it won't be too much change.

And is there a possibility to revert to the original, English, text to use that as a basis for translating? It will be easier to go from proper English than weird German for me (no offense meant for those who did the translation up to now).

**Comment by StanLindsey** [comment]
Take the file from the english translation and use that if you wish to use english. I don't speak german but it was by somebody named @cleave29

**Comment by wildcate** [comment]
Thanks @SlappyBag - I figured out I could just do that...
Any thoughts on the formal/less formal issue? (I went with the non-formal style for now - if there are no objections/questions/issues, we can close this.)

**Comment by cleave29** [comment]
@wildcate I did the translation.  I'm not a native speaker and I did the best I could with my limited German.
I did use Google translate as well as my German dictionary, and my own knowledge.  I also looked at Game of Thrones RPG youtube vids in German to get some ideas of how video games describe terms.  I apologize for any mistakes I made.  
I don't really care if we "duzen" or "siezen".  If you think it's best, I'll defer to you.
Just out of curiosity, is there a better translation for "pets"?  Does "Haustiere" imply that they're in a house?  I tried to look for "familiars" but I didn't find anything I liked.
I also had a question about "Watch 1 hour of Game of Thrones".  I wasn't sure whether to translate the title into German or leave it as is.  
If we have to start over, that's fine.  Whatever's best for the project.

**Comment by StanLindsey** [comment]
@cleave29 @wildcate  - You've both done stella jobs don't worry. And I'd vote more informal. 

Closing for housekeeping.

**Comment by wildcate** [comment]
@cleave29 You did really well for a non-native speaker with limited German! The language, however, can be quite tricky - especially when it comes to translating roleplay-related stuff. The concepts are not always the same even if the word is translated correctly according to dictionaries. The pet/familiar is such a thing - German stereotype witches tend to have a black cat, but the concept of a familiar is not so typical. 
And many roleplayers read and use English language sourcebooks, so the language tends to get liberate sprinkles of English, such as using "familiar" in German, too. Though we probably want to have real German to include those who are not familiar with the roleplaying lingo... (Oh, by the way. The official German title of Game of Thrones? "Game of Thrones". Yay German.)
And Haustiere usually implies tame animals that live at least partly inside the house... possible terms for pet would be Haustier, Begleittier (or Tierbegleiter, or tierischer Begleiter), Tiervertrauter, Tier, Begleiter, Vertrauter (that would be close-ish to familiar). Choices, choices...

**Comment by cleave29** [comment]
Ich bedanke mich bei euch!  :)  
Ooh, Tiervertrauter und Tierbegleiter gefallen mir!
