### ISSUE TITLE
 Sync bar / progress bar is not visible above Record Yesterday's Activity screen (RYA)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11057]
When you're completing Dailies in the Record Yesterday's Activity modal (the one whose current title is "Check off any Dailies you did yesterday"), there's no way to tell when each tick mark has been synced to the server and so you can take unfair damage from some of your clicks not being recorded if you click too quickly.

The solution is to have the sync bar above the overlay in the stack, as decided at https://github.com/HabitRPG/habitica/issues/9464#issuecomment-344601269 when this issue occured previously.

There was a fix for this issue at https://github.com/HabitRPG/habitica/pull/9781/files but it seems that a more recent change means that the fix needs to be done again. Possibly it just needs the z-index increased although anyone working on this should not take my word for that.

While you're fixing this issue, can you please change the comment in the code below so that it says "Push sync bar / progress bar above modals". That will let anyone find the comment when grepping for either term.
https://github.com/HabitRPG/habitica/blob/ee20b1eea8d761f16ba6ba3aba715f3f89a2467f/website/client/app.vue#L167-L170

**Comment by citrusella** [comment]
Is this still an issue? I can't replicate it (at least not locally) and the z-index is larger right now than the z-index of the modal background (and probably of the modal itself, though I didn't check that number; the bar is over top of everything).

(I was kind of excited to try my hand at trying to maybe fix that but if it ain't broken... XP  
~~I could theoretically edit the comment anyway but... XD~~)

**Comment by Alys** [comment]
Yeah, it seems to be fixed again. I'll close it. Thanks @citrusella !
