### ISSUE TITLE
long URLs in Inbox / private messages can prevent PMs wrapping correctly

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11060]
When someone sends you a private message with a long URL in it, the URL stops the rest of the message from wrapping correctly and so some words are cut off.

For example if you send this to a test account:

> http://example.com/this_is_a_long_url_that_goes_and_goes_and_goes_and_goes_look_at_it_go.html
> 
> This is a normal paragraph that should wrap normally like normal paragraphs should but it's not wrapping soon enough.

You'll see this in the test account:

![image](https://user-images.githubusercontent.com/1495809/54083555-9fecb880-4370-11e9-972c-0fdc999167d8.png)

Not all long URLs will do this - if they have hyphens or a few slashes, the URL can wrap at those points, allowing the rest of the message to wrap too. The sample URL above has only one internal slash and uses underscores rather than hyphens to display the problem.

This was reported by @citrusella who received a message with a real URL that caused this bug, but the message and link are private so I'm not showing them here.

A fix could be to force URLs to wrap at a certain width regardless of what characters are there (but that might also cause words to wrap mid-word), or to provide a horizontal scroll bar so that you can at least read all of the message. There might be other better fixes too.

~This is on hold for design. @Tressley~

EDIT: The design decision is to force wrapping not to add a scroll bar.

**Comment by Tressley** [comment]
This doesn't need a design. Just need to make URLs word wrap properly in the defined container. Here's an example of GitHub handling long URLs in comments:

![image](https://user-images.githubusercontent.com/2686586/54132028-dfa3b680-43e9-11e9-8141-143d49c81b08.png)

**Comment by Alys** [comment]
I've edited the top post to say that the design decision is to force wrapping not to use a scroll bar.

**Comment by randi2kewl** [comment]
Browser tests:

Firefox
<img width="1772" alt="Screen Shot 2019-03-23 at 3 25 43 PM" src="https://user-images.githubusercontent.com/392859/54870662-0cf44b00-4d80-11e9-9c61-8bdc1f29bcd3.png">

Chrome
<img width="1850" alt="Screen Shot 2019-03-23 at 3 24 33 PM" src="https://user-images.githubusercontent.com/392859/54870673-26959280-4d80-11e9-8b9e-42b1f11f077c.png">


Safari

<img width="1731" alt="Screen Shot 2019-03-23 at 3 23 21 PM" src="https://user-images.githubusercontent.com/392859/54870677-301efa80-4d80-11e9-8490-82f35dad5728.png">
