### ISSUE TITLE
informative error message needed when social auth user logs in incorrectly with password

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11062]
If you have an account that uses only social authentication (Google or Facebook sign-in) but you forget that and try to log in with your Username and any password, you get an uninformative message: "an unexpected error occurred"

Steps to reproduce the bug:

1. create a Habitica account that uses Google sign-in
1. change the Username to something typable or make a note of the automatically-assigned Username
1. do not set a password
1. log out
1. log in on the website by trying to use the Username and any characters for the password
1. see that the error message is "an unexpected error occurred"

The desired behaviour is that you see an informative message. For example this one:
"That account does not have a password because you registered using the Google or Facebook sign-in method. Please log in with that method."
That message will probably be adjusted by the staff.

The message should be placed in the the `front.json` locales file, just underneath the `invalidLoginCredentialsLong` string (which is for a similar purpose). While you're editing that file, please remove the `invalidLoginCredentials` string which is no longer used.

Here's the record from the server logs for an example of this error condition:
```
httpCode:500
isHandledError:false
level:error
message:Error: Invalid password hash method.
    at Object.compare (/usr/src/habitrpg/website/transpiled-babel/libs/password.js:73:11)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/auth.js:122:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
method:POST
originalUrl:/api/v4/user/auth/local/login
timestamp:2019-03-10T21:33:30.492Z
body:
username:ahtest
headers:{ referer: "https://habitica.com/login", ...  host: "habitica.com", x-client: "habitica-web" ... }
```

To help understand what's going on, here's an example of the `auth` object in an account that does have a password:
```
    "auth": {
        "local": {
            "email": "me@example.com",
            "hashed_password": "$2a$10$QDnJFFjW",
            "username": "Alys",
            "lowerCaseUsername": "alys",
            "passwordHashMethod": "bcrypt",
        },
        "facebook": {},
        "google": {},
        "blocked": false
    },
```

Here's an example for an account that does not have a password:
```
    "auth": {
        "local": {
            "username": "ahtest",
            "lowerCaseUsername": "ahtest"
        },
        "google": {
            "id": "123456789123456789123",
            "emails": [
                {
                    "value": "meme@example.com",
                    "type": "account"
                }
            ]
        },
        "facebook": {}
    },
```

So currently, when a user who uses only social authentication tries to log in with a password, the code tries to decrypt the password and the error occurs because the account has no value for `auth.local.passwordHashMethod`. The code should be adjusted so that before it gets to that point, it checks to see if a password actually exists on the account, and if not, it gives the informative message.

**Comment by paglias** [comment]
For security reasons we shouldn't reveal that an account is registered through google or fb. But we can show the same error that's shown when an email+pass user gets when the password is wrong

**Comment by ChesterSng** [comment]
I'd like to try this issue! @Alys
