### ISSUE TITLE
Text displaced off Member List button in large guilds

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11067]
> raventarte   @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c) [web] 
> It would appear that there was a CSS change to the website that now causes the text "Member List" to appear off the surrounding badge if a guild has a very large member count, and the number count itself to stop aligning with the shield icon. An example is the Habitica Help guild, versus this guild, which appears properly. Here is a screenshot comparison. I believe it is the fixed height/width values of the badge that causes this issue, and it seems to only occur if the member count is 10.1k or higher (as this is too large for the badge to handle).

Confirmed in Windows / Google Chrome.

**Comment by J-Sanderson** [comment]
I'd be happy to pick this one up if it's still outstanding.

**Comment by paglias** [comment]
@J-Sanderson thanks! I'm marking the issue as in-progress for you

**Comment by J-Sanderson** [comment]
Thanks. Can I confirm, should the badges both be the same height? e,g, if one has to be bigger to accommodate a large member count, should the other match?

**Comment by paglias** [comment]
Good question, pinging @Tressley to get an opinion on the design. I'm attaching a screenshot of the bug
<img width="464" alt="Schermata 2020-10-01 alle 16 33 55" src="https://user-images.githubusercontent.com/589911/94823227-eb0f6600-0403-11eb-85b5-a4fe2f2175ff.png">

**Comment by Tressley** [comment]
The container should accommodate the width, but both should be the same height (the height of the Guild Bank).

**Comment by J-Sanderson** [comment]
Thanks, how's this looking?

![Screenshot from 2020-10-01 19-29-41](https://user-images.githubusercontent.com/17064002/94848891-8f050b80-041c-11eb-99c6-61786a4ebc8c.png)

On a tangent I noticed the divs are clickable but not accessible by keyboard navigation, is this a known issue?

**Comment by paglias** [comment]
@J-Sanderson it's looking good, for the keyboard navigation if it's something that you can add in this pr it would be great!

**Comment by J-Sanderson** [comment]
No problem.There's a similar issue with the summary/description/challenges accordion at the right being inaccessible via keyboard, but I have left it as it's unrelated to the list buttons - maybe should be its own issue? Happy to fix if needed though!

**Comment by paglias** [comment]
We have plans to improve the accessibility of the website but right now we don't have a specific plan, so I'd say the current PR is good to go for now

**Comment by Tressley** [comment]
@J-Sanderson -- Thanks for your work on this! If you'd like to open an issue regarding the accessibility of this section, please feel free! As @paglias said, we have plans to improve accessibility, but it's a slow project at the moment. Targeting specific areas would be incredibly helpful!
