### ISSUE TITLE
Full screen profiles need "Stats" screen equipment text centred to match modal profiles

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11075]
_EDIT by Alys:_ 

As discussed in the comments below, most of the problems initially reported in this issue have been fixed. 

The only remaining problem is shown in the final screenshot in this comment below: https://github.com/HabitRPG/habitica/issues/11075#issuecomment-637490023
If you compare that final screenshot with the one just above it, you'll see that the text under each equipment image is not centred. 

The desired fix is that when you view a profile in full screen, the text should look the same as when you view the profile as a modal.

To reproduce the issue:
1. Click on your avatar in the website's header. Observe that your profile opens as a **modal** (a pop-up window).
2. Click on the Stats tab. Observe that the text under each equipment image is centred.
3. Reload the website using your browser's refresh button. Observe that you're still seeing your profile but now it's full screen, not a modal.
4. Click on the Stats tab. Observe that the text under each equipment image is NOT centred. That's the bug that needs to be fixed.

The fix for this may be just that the correct CSS needs to be loaded when the profile is viewed full screen or it may be a little more complex.

----

Ravenlune reports:

> On the full-screened version of a player profile, there are some display issues. The equipment names under the Battle Gear and Costume sprites don't centre align to the sprite boxes. For stackable achievements, the number badge is far off from where the actual achievement icon is. Hovering over equipment or achievements doesn't show the info tooltips. These issues don't happen on the pop-up profiles that appear when you click an avatar in chat or in the header. Pretty sure it's not on my end because it's persisted through multiple sessions and it's not any user styles I'm running. Screenshotted some of these [here](https://snag.gy/9XxfJR.jpg). My window size is 1024x768 and I'm using Chrome, if that helps.

I've confirmed the same issues. [Link to the view we're discussing.](https://habitica.com/profile/bb089388-28ae-4e42-a8fa-f0c2bfb6f779)

**Comment by shanaqui** [comment]
I've changed the title of the issue to be a bit more descriptive after a new report today:

RedmeDaily @Remeday (d0a3217a-7b92-48d6-b39a-b1b1be96702e): "Bug: when a profile loads as its own page, hovering over an achievement doesn't show its description."

**Comment by Alys** [comment]
I'm marking this as "on hold - needs design" for a design-related decision. FYI @Tressley

**Comment by shanaqui** [comment]
The issue with stackable achievements seems much improved to me:
![image](https://user-images.githubusercontent.com/8144640/83516779-98fb1a00-a4cf-11ea-9b91-3dfe324ee8d3.png)

The issue with the tooltips also seems to be solved. The only thing remaining (I think) is the right-aligned text above the slots:

Modal:
![image](https://user-images.githubusercontent.com/8144640/83516880-d1025d00-a4cf-11ea-8263-b088516caff7.png)

Direct link: 
![image](https://user-images.githubusercontent.com/8144640/83516923-e8414a80-a4cf-11ea-81d8-248e390a5764.png)

Should we change the title to reflect that and just ask a contributor to center that text? It seems less like a full design is needed at this point.

**Comment by Tressley** [comment]
@shanaqui -- Yeah, I think updating the title is fine. Might be a good first issue as well!

**Comment by AlexanderColen** [comment]
Has this issue been resolved but not been closed?

I cannot seem to reproduce the issue when following the following steps: (Neither in English nor in a different language, nor even in different browsers [Firefox/Edge])
> 1. Click on your avatar in the website's header. Observe that your profile opens as a modal (a pop-up window).
> 2. Click on the Stats tab. Observe that the text under each equipment image is centred.
> 3. Reload the website using your browser's refresh button. Observe that you're still seeing your profile but now it's full screen, not a modal.
> 4. Click on the Stats tab. Observe that the text under each equipment image is NOT centred. That's the bug that needs to be fixed.

**Comment by Tressley** [comment]
Yeah, I believe this was fixed in #12395. Thanks for catching it @AlexanderColen!
