### ISSUE TITLE
header misformatted in Firefox when browser default font size is reduced

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11071]
@LillaSmith (b5a69bc4-e325-417f-befe-32e3ce6f0f80) reported: **"MacOS Mojave's latest firefox version renders the header strangely, see on this image [below]. i checked on chrome (same machine), looks goog there"**

shanaqui asked: "does that persist even after a hard refresh? Just wondering if it was a single odd loading or if it looks like that permanently."

LillaSmith replied: **"yes, it still exist after cache clearing. i have checked the inspector tool, it renders the following css attribute for the "app-header": max-height: 10.25rem; if i turn this off in the inspector tool the issue is gone."**

![image](https://user-images.githubusercontent.com/1495809/54527551-ffc50e00-49c5-11e9-892d-ea88efd1988e.png)

I'm asking LillaSmith if there's any extensions that might be causing it and will report back with the answer. I wanted to record all this first though so it can't go missing if we need it.

**Comment by randi2kewl** [comment]
Tested on Mojave with FF Quantum 65.0.1 (64 bit) and FF Developer Edition 67.0b2 (64 bit) with no luck reproducing on my end.

**Comment by lillaqa** [comment]
Hi, 

I am LillaSmith from the site. :) The extensions won't affect the header, however, I have found what caused it. the default font size of the firefox was 16, and making it smaller has this effect on the header. you can try it out easily by changing it in the browser's settings. 

I'll test the same thing with other browsers and other parts of the site to see what else could be affected. 

ps.: sorry to write here, I thought it is easier. :) feel free to delete it

**Comment by paglias** [comment]
@lillaqa to write here is fine once a bug has been opened! It helps with keeping all information in one place

**Comment by Alys** [comment]
Just as confirmation, reducing the default font size in my Firefox causes the same problem and thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a) reported it too:

![scr](https://lh3.googleusercontent.com/ZvMDFbpNROrOZTighbEDOoT0Uzmo4SFo9v9mLfEirfuWtimt8yJ8-i_oYrfzTJ7GFpIGmxErQIIGC_2i6PbS1fA14YboNeQaQFHVprklfzSmoA5lNQf0p_OQtOraRjB9n-YIfh7wMRQBFgLsS4Vyfblupc8MiW2LDSkjIHGQZh-Vvw98QmH-SolCyQBWER0ZuriKHb1zSYMaI9wCPqPkL3y0dPCAGH7DZ89-O2V2tsyr6qcReI2RwL5yjAMZp4J05Ob-zNC1zwSiSXWnyqhOvAcvpbL1hInxqcxKuhTe09uQYPDZ56X4elXfnvXTybr_CEKeSIROzcF9npQUs2h_RQVO780DjftKbIgyRtFt0kegH36oohLqs1aadsQfFbpKYzo2exQXH8zYZ_21IWTmsqtsTlgh-nd66Hr-6RmSEOft-p2MC36C5WnePgoZzyqdg45p7FDKeSVCIP-NoTNreHK2ObNy-qOgCblZLIRq2qp7dMqcaMWiOMg95tsDAAOrw1LcZZy6rrkZc1tuXu_hkjtLjUuL8ki9alY0xIW7U2vpusCJhZSeC6EfKL_yoANRIH3bEDyHTSE-mh4Oju1FwwgnkXGvIr9vNLF8tkaKOfwDMrvQAeG2y-q_as8N6TrlqfnB9T4Spvu93XR84BdzjN22zFj_ecAu52yvNxBkh5xk1cF8lSwtVEHRqvrJXSf2A_uXUp0yt_9daIstyCBkUnBh=w991-h160-no)

**Comment by thebat137** [comment]
I encountered another bug recently that had a similar cause --- the text entry boxes in the "Fix Character Values" modal displayed badly when the default font size was altered, and it seemed to have to do with discrepancies in the measurement units used to set the text box size.  I'm not seeing that other problem currently, so I assume it's been fixed, and I wonder if the fix for this might be similar.

**Comment by Alys** [comment]
I've put this on hold for the reasons described in this comment on a similar issue: https://github.com/HabitRPG/habitica/issues/11822#issuecomment-613189930
