### ISSUE TITLE
Equipment shop "Change your class" message is confusing for new players

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11082]
Mara Jade (@MxMaraJade, 13eed6b5-c1b1-4b85-ba24-de75f5f01bf7, a new player currently below level 10) makes a great point about the message that you see in the Equipment shop if you try to buy a gear piece for a class you're not playing. For a new player it's misleading to the point of seeming buggy.

_"I tried buying a dagger from the store, but couldn't because I'm a Warrior class. It told me to change my class in settings, and I went to settings. It wasn't there. Upon further digging, I discovered that because I'm a mere level two I can't change my class yet. Totally legit, just would like the little pop-up telling me to change my class in settings to stop lying to me. It feels bug-adjacent."_

We see a lot of new players asking questions about how they can change class so avoiding this confusion will likely help them.

The current message is:
**"This item is only available to a specific class. Change your class under the User icon > Settings > Character Build!"**
(code snippet below).

There's a couple of options for improving this:  [EDIT: We'll go with option 1 for now since it's simplest and option 2 can done later if it still looks like there's a need for it.]

1. **Change it so that all players regardless of level see a message that includes the level 10 restriction. For example:**
**"This item is only available to a specific class. At level 10 or above, you can change your class under the User icon > Settings > Character Build!"**
The staff might change that suggested text.

2. Change it so that players at level 10 or above see the current message while players below level 10 see a different message. For example:
"This item is only available to a specific class. When you reach level 10, you'll be able to select a different class under the User icon > Settings > Character Build!"
The staff might change that suggested text.
The new message should be added to the file shown below, just underneath the current message to keep them both together.
If we go with this option, the coder who works on it must test that the message changes as soon as the user reaches level 10 - i.e., level up to 10, go to the Shop, ensure that the message has changed without the need for a sync or reload. 

~I'll leave this as suggestion-discussion for a few days for the staff to comment on it.~
~If there's no comments opposing this, I'll mark it as help wanted for the first option since it's simplest and has no chance of producing bugs with the text not changing appropriately (and we could always implement the second option later if it appeared to be necessary).~

https://github.com/HabitRPG/habitica/blob/a2261e35919a0396d2e74ea70f209b68ebc004c6/website/common/locales/en/gear.json#L13

**Comment by Alys** [comment]
I've marked this as help wanted for option 1.

**Comment by miketoth** [comment]
@Alys can I take this issue?

**Comment by Alys** [comment]
@miketoth Thanks for the PR! 

I've removed the "help wanted" label from this issue.
