### ISSUE TITLE
[Suggestion] April fool's day idea

### ISSUE THREAD

**Issue by chenl** [HabitRPG/habitica#11088]
Wouldn't it be fun replacing all the pets and mounts for everybody with Emojis on April first?
Just a thought -- feel free to close this issue.

**Comment by Alys** [comment]
You might like to go to Help > Request a Feature from the habitica.com website's navigation menu to suggest that. :)  That same menu has an entry for bug reports too, so you don't need to post to GitHub. In case it's helpful, you'll see reminders about that in the default text when you click the "new issue" button here in GitHub.
