### ISSUE TITLE
closing one modal sometimes causes previous modal to reopen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11083]
We've known this bug exists for a while but I can't find an issue for it.

Sometimes when you close a modal, a previous one that you looked at reopens itself.  Once this starts, it generally keeps happening until you reload the website.

Here's a report from @minervathene (d3de6635-37f7-4369-99c3-399d036d0898) today:

"Every time I hatch a pet (doing the new celestial ones) when I click the 'onward' confirmation it reopens the last dialog (a user lookup) that I had open. Happens repeatedly, but not in a fresh session."

**Comment by jackcogdill** [comment]
Hey, wondering if I can work on this? Just encountered this bug myself.

**Comment by paglias** [comment]
sure @jackcogdill ! thanks for the help and let me know if you have any question

**Comment by jackcogdill** [comment]
Has anyone discovered clear steps to reproduce this? I'm having a hard time debugging. Although I suspect it has to do with `modalStack`

**Comment by Alys** [comment]
Just to confirm, this is still happening. There's a new report below. I've never found a way to reproduce it delibeately.

@JohnJSal (624e48a3-cbea-4bbe-ae44-ca9183f49626): "Recently I'm noticing on the website whenever I click away from a popup screen (like the Messages window, or someone's profile), instead of just going straight back to the page I'm on, another popup screen will appear first, usually my own profile window, or that of a random other user."

**Comment by shanaqui** [comment]
@jackcogdill Are you still interested in working on this issue, or should I mark it as help wanted again? Thanks!

**Comment by jackcogdill** [comment]
@shanaqui You can mark it as help wanted.

**Comment by shanaqui** [comment]
Alright, I've done that! Thanks for letting me know.
