### ISSUE TITLE
wrong player names associated with guild chat posts

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11085]
Under some circumstances (possibly a rare browser-side glitch), it's possible for the wrong names to be associated with guild chat posts.

A report from MEmry, the pink pirate (@MEmry, e495bd8b-f2f1-48e8-8f5f-9a52710999cf) is below in bold. It's referring to chat in the Report a Bug guild. At the time that MEmry was writing the message below (i.e., just before posting it), the five posts most recent posts in the guild were by:

- ravenlune, #ffb6b8 / @ravenlune?6 _(the most recent)_
- Lulianne / @annatheandroid?9
- Alys / @Alys
- Alys / @Alys
- Alys / @Alys

**"Really weird thing happening. I'm seeing wrong names all over the place. Right now, I see @ravenlune displayed as MEmry, the Projectionist (my alter ego), @annatheandroid as gilr, @Alys as Alys but the next @Alys as MEmry, the Projectionist and the third @Alys as lindanmarie. After I press send, I expect it to change, because that happened when I was in guild chat."**

After posting that, the top six posts were written by

- MEmry, the pink pirate / @MEmry
- ravenlune, #ffb6b8 / @ravenlune?6 _(the most recent)_
- Lulianne / @annatheandroid?9
- Alys / @Alys
- Alys / @Alys
- Alys / @Alys

and MEmry posted a second message:

**"I am correct. Now I see MEmry, the pink pirate displayed as MEmry, the Projectionist, @ravenlune as gilr, @annatheandroid as herself, and then the three Alys posts as MEmry, the Projectionist, lindanmarie, and then as Alys. I'm using Chrome."**

Just before MEmry came to the Report a Bug guild, she was posting to a private guild so I can't see any details about which guild or whose names she was seeing there.

I'm asking her for more information such as screenshots and console logs if possible.

**Comment by SabreCat** [comment]
If there haven't been any new cases of this happening since March, there's been enough tweaking done to chat that it's likely to have been incidentally fixed. Closing for now!
