### ISSUE TITLE
participant list for challenge shows content of member list from guild/party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11091]
If you view the member list of a guild or party then try to view the member list of a challenge, you see the member list of the guild/party again.

The expected behaviour is that you see the member list (participant list) of the challenge.

I'm marking this important priority because it's impossible for the challenge creator to properly judge the challenge when they can't see the member list.

This was reported by Týr / @-Tyr- (38009d36-5a27-4ef0-a890-e81f4c847425) in the post below and I've confirmed it in my own account.

_"Hi! I am a member of a party, and I looked at the Member List for my party. That was fine. Then, I went to a challenge (not a challenge from my party) and clicked the button to look at challenge participants. Instead of showing the challenge participants, the Member List for my party popped up. I waited a while, and it didn't change. I closed the list and clicked the participant button again, I navigated away from the page and back and clicked the button again, and the same thing happened. After reloading the page, the issue was fixed."_

**Comment by paglias** [comment]
The issue seems to be that loading challenge members seems to be broken. Opening a challenge and then trying to see the members list open an empty modal with no network request being made

**Comment by paglias** [comment]
<img width="1440" alt="Schermata 2019-03-31 alle 20 27 46" src="https://user-images.githubusercontent.com/589911/55293152-77962e00-53f3-11e9-88b0-eb8ce82e4b66.png">

**Comment by paglias** [comment]
I'm not able to replicate locally but the problem seems to be that in the members modal `this.group` is undefined

**Comment by Alys** [comment]
Reopening because this is still happening in staging (and production). If you view a group's member list first, you see that list when you try to view a challenge's members. If you reload and view the challenge's members first, you get a blank list (even for challenges that have members). 

Reported by AnneLine in production; confirmed by me in production and staging.

![image](https://user-images.githubusercontent.com/1495809/55677406-1823ab00-592a-11e9-843d-591dc49e4d7b.png)
```
TypeError: "this.group.purchased is undefined"
    groupIsSubscribed 
```

**Comment by paglias** [comment]
Sorry about this, fixed again (in staging) and can't reproduce the error anymore
