### ISSUE TITLE
Gem icon in navigation bar sometimes fails, prevents scrollbar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11095]
ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c) has been noticing intermittent problems with the gem icon in the menu bar:

From about two days ago:
"Clicking the gem icon in the navbar 1) does not bring up a pop-up 2) disables the scrollbar. I presume this is related to the scrollbar issue/quick fix."

From about a day ago:
"Re gem icon: It's fixed now, I guess there was a website update that addressed it."

From two hours after that:
"Oh, actually it seems to have broken again now... how strange? It happens on every page, it seems."

Console log messages are below but I suspect they've been truncated by the message limit in Habitica (I forgot about that when I asked her to post them there), so I haven't bothered trying to neaten the formatting. I'll ask her to post them here when she notices the problem again.

---

cloudfront.loggly.com/js/loggly.tracker-latest.min.js:1 Failed to load resource: the server responded with a status of 499 (Request has been forbidden by antivirus) moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/ Arguments: Error at g.zone (https://habitica.com/static/js/vendor.0c12dd6348e4ce721b9d.js:1:13987) at Object.<anonymous> (https://habitica.com/static/js/app.955a7a582a34cf24277c.js:1:286269) at n (https://habitica.com/static/js/manifest.f7db30c405d9861be02d.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.955a7a582a34cf24277c.js:1:21302) at n (https://habitica.com/static/js/manifest.f7db30c405d9861be02d.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.955a7a582a34cf24277c.js:1:403027) at n (https://habitica.com/static/js/manifest.f7db30c405d9861be02d.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.955a7a582a34cf24277c.js:1:640825) at n (https://habitica.com/static/js/manifest.f7db30c405d9861be02d.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.955a7a582a34cf24277c.js:1:395871) x @ moment.js:293 (anonymous) @ moment.js:320 (anonymous) @ index.js:19 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ analytics.js:1 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ app.955a7a582a34cf24277c.js:20568 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ menu.vue?8318:1 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ app.955a7a582a34cf24277c.js:19880 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ app.vue?70c3:1 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ main.js:1 n @ bootstrap e2f5cd45fdf569a69c4b:54 (anonymous) @ app.955a7a582a34cf24277c.js:43327 n @ bootstrap e2f5cd45fdf569a69c4b:54 window.webpackJsonp @ bootstrap e2f5cd45fdf569a69c4b:25 (anonymous) @ app.955a7a582a34cf24277c.js:1 cloudfront.loggly.com/js/loggly.tracker-latest.min.js:1 Failed to load resource: the server responded with a status of 499 (Request has been forbidden by antivirus) SBPageExtension.js:3 SBBrowserInjectChrome SBPageExtension.js:2380 PAGEEXT FINISHED: browserInject=[object Object] stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-33510635-1&cid=1046869864.1542612184&jid=861674612&_gid=1425601501.1554077834&gjid=1712526148&_v=j73&z=1064021691:1 Failed to load resource: the server responded with a status of 499 ()

**Comment by paglias** [comment]
Can we ask them to try in an incognito window without extensions?

**Comment by cyxlan** [comment]
Ah, I found the issue; it was with a user style I wrote. Apparently trying to hide the footer also caused the pop-up to disappear, because the pop-up is contained in the footer class... It's not a big deal for me anyways, because I don't buy gems.

**Comment by paglias** [comment]
thanks for the followup @ravenlune ! I'm going to close this unless we get more reports as it's not really under our control and should be an edge case
