### ISSUE TITLE
claimed Group Plan task does not appear in personal task list until a sync

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11109]
As reported by Lord Kraken @mbianchi (071314b5-b684-43da-8e19-118e36ea16f6) and confirmed by me:

_"When I make a Group Task (in this case it was a To Do, but I think it applies to any kind of Task) and assign it to myself, and then click the "Tasks" button on the Nav bar, the Task I just created and assigned to myself does not show up in my list. I then Refresh my browser window with F5 and the task shows up. i am using Chrome on Windows 10."_

The task will also appear if you click the sync button but ideally it shouldn't be necessary to do either a sync or a refresh.

**Comment by paglias** [comment]
@SabreCat maybe something for #11107 ?

**Comment by Tressley** [comment]
Yeah, this is definitely on our radar. We reviewed Group Plans recently with the intention of highlighting the larger issues like this one. We prioritized some of the smaller fixes beforehand to help onboard @SabreCat into Group Plans code.
