### ISSUE TITLE
Booted from Party and Character's Face is Missing

### ISSUE THREAD

**Issue by julatkinson** [HabitRPG/habitica#1110]
This morning I took the survey posted by HabitRPG.

Shortly after completing the survey two things happened:
1. I was removed from my party.
2. My character's face disappeared.

So, yeah, not sure what to do about that.

![image](https://f.cloud.github.com/assets/4582185/592607/41c6e8f0-ca1f-11e2-8091-7a56bffdd043.png)

**Comment by lefnire** [comment]
Nothing to do with survey (they're not linked, separate websites). When you
go to party tab, what do you see? as far as face, that's a semi-known
problem i'm working on - go to avatar tab and click your head / hair / skin
again for the time being.

**Comment by julatkinson** [comment]
Makes sense. I think my sleepiness liked them. :)

When I sent to the party tab it said that I was not part of a party, and
had my ID code to send to a friend to join their party.

**Comment by lefnire** [comment]
Strange. What's your user id I'll investigate

**Comment by julatkinson** [comment]
(f0411936-4d65-4847-8e6f-59e87c15064d)granted, i rejoined the party, so i'm
not sure i can be a good test subject. :)

Julie O. Atkinson
804.513.3935

**Comment by lefnire** [comment]
Alas. I'll keep an eye out in the future then, sorry bout that!

**Comment by julatkinson** [comment]
No worries! If it happens again I'll let you know before I join the party
again. My bad!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
