### ISSUE TITLE
Visual issue: stats order is different between profile and item stats

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11115]
_EDIT: See the first comment for the desired fix._

> Kristof @KristofM (71d41add-5c1f-4f59-8354-ce6078a6abe2): "Hi, the order of the stats is different when you view the stats from a player vs the stats from equipment.
> 
> These are the order of the stats for a player:  
> STR - INT  
> CON - PER  
> 
> However, these are the order of the stats when you hover over a piece of equipment:  
> STR - INT  
> PER - CON  
> 
> This is rather confusing for a new player (like me)"

E.g.

![image](https://user-images.githubusercontent.com/8144640/56206541-8eb85b00-6044-11e9-8b59-53f6c416eef3.png)

vs.

![image](https://user-images.githubusercontent.com/8144640/56206577-a394ee80-6044-11e9-8d23-bbafa52f5800.png)

**Comment by Alys** [comment]
On the Android app, when you view a player's profile, you see both their own stats and their equipped gear's stats in the order **STR, INT, CON, PER**. That's the same order as the stats on the user's profile on the website so we'll call that one correct.

The contributor who works on this should change the on-hover pop-up for an equipment piece to match that order.

**Comment by kogelnikp** [comment]
@Alys Can I work on this issue?
It keeps confusing me too, so I'd be happy to have it fixed.

**Comment by Alys** [comment]
@kogelnikp Thanks! I've marked this as in progress for you.
