### ISSUE TITLE
Wacky Pets should not be feedable

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11119]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Currently, the API doesn't reject attempts to feed Veggie pets; it goes ahead and increases their food counter and can even transform them into mounts, causing them to vanish because Veggie Mounts don't (yet?) exist. We head this interaction off on the client side for Web, but other API consumers might still attempt this. The API should error out and not remove food, etc. in these cases.

**Comment by jerell-mendoza** [comment]
@SabreCat, could I take a look at this? I'll probably be asking more questions as I look into it

**Comment by paglias** [comment]
@jerellmendoodoo go ahead! Happy to answer any question you might have

**Comment by shanaqui** [comment]
@jerellmendoodoo Hi there! Are you still working on this? Let us know if you are! :)

**Comment by jerell-mendoza** [comment]
@shanaqui sorry, I'm not! Totally forgot about this one!

**Comment by shanaqui** [comment]
@jerellmendoodoo Thanks for confirming! I'll mark this as help wanted again. :)

**Comment by somersjw** [comment]
Hi could I look into this?

**Comment by Alys** [comment]
@somersjw please do, thanks! Post here if you have questions.
