### ISSUE TITLE
Hall of Heroes admin interface is setting numerical values as strings

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11122]
For mods and staff, the Hall of Heroes has an admin interface that lets you assign items to a user's account (screenshot below).

When you assign an item that has a numerical value (e.g., `5` for `items.pets.BearCub-Veggie`), the interface sets it into the user's account as a string rather than an integer. For example:

```
{
    "_id": "3a8....",
    "items": {
        "pets": {
            "BearCub-Veggie": "5"
        }
    },
}
```

I think this is a relatively recent bug. I'm pretty sure that the admin interface used to set integers correctly but I might be wrong about that.

This is a problem because when an integer value is set to a string, other bugs can happen (e.g., for a pet with a string value, feeding it one piece of food will turn it into a mount immediately).

I've marked this as high priority because setting pets to have a value of `5` is something that mods need to do often at the moment (due to the bug in the mobile app that allows Garden pets to be fed) and the more times a string value is set, the more accounts admins will need to find and clean up after the bug is fixed

![image](https://user-images.githubusercontent.com/1495809/56455591-83965f80-63a3-11e9-9c7c-0bbac22b1e74.png)

**Comment by paglias** [comment]
This is due to the PR to speed up the model perf since there's no more any automatic casting to the expected type and the form is sending strings instead of numbers/booleans/... I'll fix it after the weekend but in the meantime it would be better not to use it

**Comment by Alys** [comment]
I've marked this as in progress.

After the weekend, let us know if we should test forms in any other parts of the site.

**Comment by paglias** [comment]
Thanks but it should be limited to the hall of heroes since it's the only Apu route that allows to set arbitrary values for items

**Comment by paglias** [comment]
@Alys have you seen other issues with the hall of heroes not behaving correctly? For example setting a value for something else than a pet not being saved correctly?

**Comment by paglias** [comment]
Should be fixed in staging
