### ISSUE TITLE
Check-In incentive (loginIncentives) prize not given

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11121]
tam @tamtheotter (41f9f05a-fc5a-4ed2-9530-4d237637189c) reported:

_"I believe I'm missing an item for check-in, a saddle."_

shanaqui confirmed that was correct - they were at 53 check-ins and did not have any sign of every having owned a Saddle (i.e., `food.Saddle` did not exist at all in their account; if they'd been given a Saddle then used it, `food.Saddle` would exist with `0` as the value). A Saddle should have been given at 50 check-ins.

Amplitude shows that the 50th check-in cron was on April 13, 2019 9:34:37 pm UTC. There's nothing in Loggly for their account around that time.

Possibly the cron code that gives the `loginIncentives` prizes should have error checking around it to catch any failures and make another attempt?

**Comment by paglias** [comment]
Hmm I gave a look at the code but couldn't find anything wrong with it, did we see any reports of login incentives not working? 

> Possibly the cron code that gives the loginIncentives prizes should have error checking around it to catch any failures and make another attempt?

The save phase is the same used for the rest of cron so if there was an error while cron was running it would also affect login incentives

**Comment by shanaqui** [comment]
Aside from tamtheotter's report copied above, I haven't ever seen a report I was able to confirm before. There have been other reports of missing items, but it's difficult to confirm in most cases and it could get lost amidst the issues of misunderstanding when items are given. This one was unambiguous, though: the item was definitely not given to them at all.

(The user has been given a Saddle now, FYI.)

**Comment by Alys** [comment]
> The save phase is the same used for the rest of cron so if there was an error while cron was running it would also affect login incentives

Would you expect that kind of error to appear in Loggly? There was nothing for this instance.

"Check-in incentive" is the user-facing name for `loginIncentives`. I'm about to edit the title to add loginIncentives to it.

**Comment by paglias** [comment]
> Would you expect that kind of error to appear in Loggly? There was nothing for this instance.

Hmm if it was a VersionError we would have something in loggly but might have happened during a server outage

**Comment by SabreCat** [comment]
Sounds like we need more data here to make this actionable. Closing for now; we can reopen if we capture info from an account affected by another incidence.
