### ISSUE TITLE
Task editing modals do not scroll in response to dragging of checklist items

### ISSUE THREAD

**Issue by thebat137** [HabitRPG/habitica#11134]
@Alys asked me to create this issue.

[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: dea8a9e8-c084-438a-9a14-7fe96a73fd0a
  * Browser: Firefox (60.5.1esr) and Chrome (72.0.3626.121)
  * OS: Linux (Debian, kernel 4.19.0-3)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
I've noticed recently that, when I'm rearranging a long checklist on a task, I sometimes cannot drag a checklist item to the top or bottom of the screen and expect the task editing modal to scroll responsively. Instead, I have to drag the item as high (or low) on the list as is currently visible, drop it there, manually scroll the page, and then drag again. For the short checklists in my dailies, this isn't a big deal, but I have some month-long todos for which this becomes kind of painful. It happens in both Firefox and Chrome.

Since reporting this issue in the Report a Bug guild, I have discovered that it only happens if I try to drag the checklist item up first.  If I drag it down first, the problem does not occur.  The culprit seems to be the menu bar header, which is initially hidden when I enter the editing modal but unshades at the top of the screen when I try to drag the item upwards.  After this, the screen does not want to scroll.  However, if I drag the item downwards first and trigger a downwards scroll, then the menu bar does not seem to cause so much trouble, even if I reverse the drag direction, as long as I don't release the mouse button.

It seems to me that this could probably be solved by preventing the menu bar from unshading while in a task editing modal.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
No obvious ones.

**Comment by Alys** [comment]
I've marked this as suggestion-discussion for the staff to comment on the preferred fix.

Thanks @thebat137 !

**Comment by veeeeeee** [comment]
Preferred fix: screen should move with drag so you can access entire checklist with single drag motion.

**Comment by harumhl** [comment]
I'm open to take this

**Comment by Tressley** [comment]
Closing as this no longer seems to be an issue.
