### ISSUE TITLE
Missing potion.

### ISSUE THREAD

**Issue by Vividienne** [HabitRPG/habitica#1113]
Hello!

Just a second ago a red potion dropped, but it can't be found in my inventory.
Hope the missing potions/eggs will be fixed soon.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by cleave29** [comment]
This happened to me twice just recently in the past two days.  I think it actually said it was giving me a potion and then gave me an egg instead.
