### ISSUE TITLE
Inbox / private messages / PMs should be searchable by Username

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11140]
As reported by cTheDragons and confirmed by me: 

"Unable to search by @username in the Messages (Inbox) section. Only via the display name."

In my opinion, the ideal situation is that Inbox conversations should be searchable by both Usernames and Display Names.

I'll leave this as suggestion-discussion for a few days in case the staff want to comment and then mark it as help wanted.

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitica/pull/12044
