### ISSUE TITLE
Stat issues after using reset and dying

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11143]
Needs a more informative title, probably. Just trying to get this in here to start with!

> "I reset my character when I was at level 88 with all points allocated to INT, but now that I died a couple of times I find for no reason at all points allocated to STR and CON - it shouldn't even be possible to have new points because my allocated points are far higher than my level. I wanted points only to INT"

> The issue that I am reporting is the appearance of the points in CON and STR, I don't know when it happened because I wasn't looking at my stats as I needed many levels before receiving new ones.
> 
> Well, an other weird thing is that even dying various times I still have 88 points to INT, shouldn't I loose one allocated point every time I die? (4 deaths in the last week for example) Was I loosing allocated points that I shouldn't have? I don't even have automatic allocation active...
> 
> I can't track the sequence of events as I wasn't looking at my stats in the last month (more or less the time since reset), but something weird was going on.

> I found a possible culprit, if I activate automatic allocation, in this case task based, and I level up, I get a new point: I now have again a point in STR. Didn't check if the same happen with others.
> 
> It may be possible I had it active at one point too.
> 
> I don't know if I had maybe for a while a different kind of automatic allocation active to explain the CON points (I don't have tasks with CON attribute)

Reported by @ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b)

**Comment by majestic-owl448** [comment]
If there is any need of testing, like verifying if it happens with all automatic allocation options or things like that, I will re activate my test account

**Comment by majestic-owl448** [comment]
Even if it could still fall under this issue: https://github.com/HabitRPG/habitica/issues/6482

**Comment by SabreCat** [comment]
Does look very likely to be a duplicate, as that issue encompasses (and has examples of) many different ways to get bad stat allocations. Closing for now!
