### ISSUE TITLE
My Challenges is blank when filtering for Owned

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11145]
As reported by Ceran, Hamster Juggler (@Ceran, aabe567b-aa55-42c1-b612-b7699a7ba9b7):

"Addition to the problems on the "my challenge" page I posted a while ago: I now can't see all of my challenges. Some just won't show up there and I have to go to the guild they're posted in and access them from the guild challenge list there. When I try to filter by challenges owned, I get shown just very few challenges, most don't show up at all (even those not affected by the above named issue). I think the new "show more" button used to be at the bottom, but it's just not there now using the filter, so no way to actually show the other challenges."

I've confirmed this on my own account. I own several challenges but when I got to https://habitica.com/challenges/myChallenges and click the "Owned" filter checkbox, I see the "You don't have any Challenges" message.

**Comment by paglias** [comment]
@negue might be due to the changes to challenges pagination?

**Comment by Alys** [comment]
I'm reopening this because it's happening again. I own several challenges but when I got to https://habitica.com/challenges/myChallenges and click the "Owned" filter checkbox, I see the "You don't have any Challenges" message.
My owned challenges do appear when I untick the "Owned" filter checkbox.

I don't know if the exact behaviour described by ceran is still happening for some players.

**Comment by Alys** [comment]
My owned challenges do appear when I untick the "Owned" filter checkbox.

(I'm about to merge this comment into my previous one for neatness.)

**Comment by shanaqui** [comment]
This is happening to me as well.

Some of my owned challenges do appear in my challenges, when I filter by owned, but *only* if I am also a member of the challenge.  

I have a recording of my screen showing this if anyone needs it to investigate.

**Comment by negue** [comment]
my previous PR was redone with #11222, but with this the `Owned` filter stopped working again, seems that both changes are not "right" ^^ 

@SabreCat any idea on how to fix it for (hopefully) the last time? :D

**Comment by Alys** [comment]
Another report of this from @Transurfer (ffe1c057-537c-454d-873f-c590b162ff2c):

"This challenge https://habitica.com/challenges/e56d5140-7dce-40c1-9715-25eb187491f4 doesn't show up in the list when I click "OWNED" on my challenges page."

**Comment by kirsty-tortoise** [comment]
I think I could have a go at this - I think I have fixed the issue but should add tests to stop it happening again.

**Comment by paglias** [comment]
thanks @kirsty-tortoise ! Marking this as in progress

**Comment by kirsty-tortoise** [comment]
Hey, just wanted to check I've understood it correctly:
- the my challenge page gets data from the api via /api/v4/challenges/user?**member=true**
- we want that to return challenges that were either created by the user or that the user has joined

**Comment by SabreCat** [comment]
@kirsty-tortoise That's correct for the My Challenges page with no additional options checked. "Owned" should make it so you see only those you created!
