### ISSUE TITLE
task Notes don't disappear when deleted (client-side cache bug)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11152]
On the website, if you have a task with a note and you delete the note, the note still appears when you view the task until you reload the website.

It is however deleted from the task immediately (I've confirmed that by database searches) so this is just a website client-side caching problem.

If you change the text of the note, the change appears immediately so this bug seems to be just related to deleting the whole note.

Reported by cTheDragons and godless_toast, confirmed by me.

**Comment by Alys** [comment]
I've only started seeing reports of this today so this is probably a new bug caused by recent changes in Habitica's front-end code or in a vue library that our code uses.

**Comment by garayj** [comment]
Hi there! Is this still open? I just found this project and I really like it and I'd like to make a first time contribution. Is this something I can take on?

**Comment by Alys** [comment]
@garayj Sure, thank you! Post here if you have questions or run into trouble.

In case you haven't already seen this, the [Guidance for Blacksmiths](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths) wiki page and the pages it links to will give you some information about coding for Habitica. Good luck! :)
