### ISSUE TITLE
locked pinned Grand Gala seasonal equipment for your class has wrong date and wrongly mentions class

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11151]
EDIT: When this becomes help wanted again, note https://github.com/HabitRPG/habitica/issues/11151#issuecomment-626287070 and any comments below it. They are likely to be relevant to the solution.

When seasonal equipment for the class you are currently playing from the Spring 2019 Grand Gala is pinned to your Rewards column and you have never owned it, the on-hover text says **"Available until 31 October 2018"** (at least for the example item shown below; it's possible that other items show different text).

I have no idea where it's getting that date from; I can't find a reference to that date in the code in any context that should apply to those gear pieces.

Regardless, when the gear is no longer available, the message should say that instead of having any date. For example **"This item is no longer available."**

The on-hover text also says that it's available to a specific class, which is irrelevant when you are the right class - that message shouldn't appear.

Here's an example of the problem:
```
{
    "_id": "d904bd62-da08-416b-a816-ba797c9ee265",
    "profile": {
        "name": "Alys"
    },
    "flags": {
        "classSelected": true
    },
    "stats": {
        "class": "wizard"
    }
    "pinnedItems": [
        {
            "path": "gear.flat.weapon_special_spring2019Mage",
            "type": "marketGear"
        }
    ]
}
``` 
![image](https://user-images.githubusercontent.com/1495809/57189489-ba977400-6f52-11e9-884d-007bb473bea2.png)

_Note that the desired behaviour described above applies to only gear that you have never owned._
_If you have previously bought the item and lost it due to death, the equipment will appear in your `items.gear.owned` object with a `false` value, and then there should be no message indicating lack of availability due to the date or class. That situation is currently working and should not be changed._

**Comment by michelle-gong** [comment]
Hey Alys, 
I will give this a shot! : ) am I right to be looking at equipmentSection.vue or is there something related to the Grand Gala that I should be looking at?
Michelle

**Comment by Alys** [comment]
@michelle-gong Thank you! I've marked this as in progress for you.

Here's how I'd go about finding the right code to edit:

Once you have a local install set up, cd into the top-level directory of your local copy of the repo (the directory that contains `config.json.example`) and then pick some text from the feature that you're investigating. In this case, "Available until" is a good selection. You wouldn't want to use the whole string "Available until 31 October 2018" because with any body of code it's likely that specific data such as a date is inserted with a variable. 

To find where the string occurs, do `git grep "Available until"`
That will show you a lot of results but most of them are in the non-English language files. The ones in the `website/common/locales/en/` directory are the US-English ones. You'll find this:
`npc.json:189:  "limitedOffer": "Available until <%= date %>"`
(and also some other English strings that aren't relevant).

The key `limitedOffer` is what you can search for next with `git grep limitedOffer`. You'll see these results:
```
website/client/components/shops/buyModal.vue:350:        return this.$t('limitedOffer', {date: moment(seasonalShopConfig.dateRange.end).format('LL')});
website/client/components/shops/shopItem.vue:228:          this.$t('limitedOffer', {date: moment(seasonalShopConfig.dateRange.end).format('LL')});
```
The code in those files is probably related to this issue, or at least will give you a start for working out what needs to be changed.

Comment here if you have further questions!

**Comment by Alys** [comment]
For the current Grand Gala, the date is correct ("Available until 31 July 2019") but the lock message is still wrong ("available to a specific class").

@michelle-gong How are you going with this? Need any more advice? If real life has got in the way and you no longer have time for it, just let us know. :) We completely understand what that's like!

**Comment by michelle-gong** [comment]
@Alys Thanks Alys, I was working on this with one of my friends but I was having difficulty figuring out the issue without her : ( I'm doing my best to understand the codebase but I'm having difficulty figuring out the root of the issue.

**Comment by Alys** [comment]
I've changed this issue to suggestion-discussion for the developer staff to comment on my thoughts below about the `dateRange` value.

The wrong date problem described for equipment in this issue is also happening now for the Waffle quest (which shouldn't be appearing any more but that's a separate issue that I've mentioned to the staff):

![image](https://user-images.githubusercontent.com/1495809/81493375-37d29300-92e3-11ea-9f37-b28ca80d6fd6.png)

I think the wrong date has to be coming from the code below because I can't see anywhere else that the October 2019 date is stored in a way that could be relevant. The 2018 date mentioned in the top post was probably from before this code was changed to 2019.
https://github.com/HabitRPG/habitica/blob/be622e8b10ce7f9e59056c77ad01762320d85064/website/common/script/libs/shops-seasonal.config.js#L8

There's several places the `dateRange` value is used (below) but I'm not sure it's meant to be used any more since it hasn't been updated for the past two recent Grand Galas.
```
$ git grep dateRange
website/client/src/components/shops/buyModal.vue:489:      return this.$t('limitedOffer', { date: moment(seasonalShopConfig.dateRange.end).format('LL') });
website/client/src/components/shops/market/categoryRow.vue:64:      return this.$t('limitedOffer', { date: moment(seasonalShopConfig.dateRange.end).format('LL') });
website/client/src/components/shops/quests/buyQuestModal.vue:348:      return this.$t('limitedOffer', { date: moment(seasonalShopConfig.dateRange.end).format('LL') });
website/client/src/components/shops/quests/questInfo.vue:157:      return this.$t('limitedOffer', { date: moment(seasonalShopConfig.dateRange.end).format('LL') });
website/client/src/components/shops/shopItem.vue:317:        : this.$t('limitedOffer', { date: moment(seasonalShopConfig.dateRange.end).format('LL') });
website/common/script/libs/shops-seasonal.config.js:8:  dateRange: { start: '2019-09-24', end: '2019-10-31' },
```

**Comment by fmaximus** [comment]
The dates used to be right in `shops-seasonal.config.js`

https://github.com/HabitRPG/habitica/blob/5d202c761721597563b8c90aa989798c584d3a9c/website/common/script/libs/shops-seasonal.config.js#L8

commit 671c90a593a1fd51f22d8bddb777f05f50c79b22 seems to have reverted them to the state before the spring event.

https://github.com/HabitRPG/habitica/blob/671c90a593a1fd51f22d8bddb777f05f50c79b22/website/common/script/libs/shops-seasonal.config.js#L8

About the waffle quest, an attribute event was added.
The end date shown should take the end date of the event instead of the seasonal shop.
Besides that, `canBuy` is missing.

Proposal: have a default implementation of `canBuy`, if event is set.

    if (v.event) {
      defaults(v, {
      canBuy () {
        return moment().isBetween(v.event.start, v.event.end);
      },
    }

**Comment by SabreCat** [comment]
Some of the above has been implemented in https://github.com/HabitRPG/habitica/commit/6658abbcd99e55f2001f3ca05781b8aca58c796b

Agreed that we should be using correct/current/relevant time range information instead of years-old irrelevant ones.

**Comment by SabreCat** [comment]
More specifically, there are several things we can fix up, here:

- When an item is pinned but can't be bought due to its event having elapsed, remove it from `pinnedItems` automatically. Currently we do this with some db cleanup post-event, but that's a less than ideal solution.
- As a fallback, don't show the class-related lock message if it's locked due to a `canBuy()` failure; instead, show an alternative "This item is not available for purchase." message.
- Where possible, move Seasonal Shop configuration from code to environment variables.

**Comment by Alys** [comment]
Regarding this:
> When an item is pinned but can't be bought due to its event having elapsed, remove it from pinnedItems automatically. Currently we do this with some db cleanup post-event, but that's a less than ideal solution.
there was a brief discussion elsewhere about something related to it:

alys: "What if for anything that we want pinned to everyone's Reward column, we had a pinnedItems array in content and the code that displays pinned items for users read that as well as their own pinned items? We'd actually need five arrays/objects, one for each class and one for non-class things, but it would avoid the need for adding/removing items directly to each user."

matteo: "Don't we already have something similar with the official pinned items https://github.com/HabitRPG/habitica/blob/develop/website/common/script/libs/getOfficialPinnedItems.js ? ...  it's not been used recently and it does not support different classes (although adding support for it should not be difficult) but it seems to have been added exactly for this use case"

negue: "yeah thats why I added /website/common/script/content/officialPinnedItems.js back then"

So if we adjusted the official `officialPinnedItems` object to have five sub-arrays/objects and automatically displayed it in people's Rewards area, we could then prevent them from pinning the Grand Gala gear and we wouldn't need to remove their pins afterwards (just empty `officialPinnedItems` as part of the process of turning off the Gala).

**Comment by Alys** [comment]
Just to confirm (since it's a new Gala now) the issue reported [in this comment above](https://github.com/HabitRPG/habitica/issues/11151#issuecomment-626287070) is still happening for anyone that has the quest scroll pinned:

![image](https://user-images.githubusercontent.com/1495809/89013545-68145580-d357-11ea-9a4d-08845219ad43.png)

**Comment by SabreCat** [comment]
Is this still happening in the current Gala? We've done a number of updates to the display and behavior of time-locked items since last summer...

**Comment by Alys** [comment]
I don't recall reports of it this time so I'm closing this. We can reopen if it happens again.
