### ISSUE TITLE
Guild and Challenge categories bugs: duplication, inability to change

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11162]
As reported by @-R (3807fed9-ada8-41eb-9174-baa26246b57e):

**"on the website I noticed my private guild's assigned categories are repeated ? 4 categories instead of 2."**

**"The refresh [reloading the webpage] didn't change anything. Here's the URL: https://habitica.com/groups/guild/5189073f-56cd-4e2b-9cb6-817567371887 "**

I confirmed in the database that the guild had two categories assigned but each appeared twice in the `categories` array.

I asked "What happens if you edit the guild to try to change the categories? If simply editing and saving doesn't help, try unselecting both of the current categories and selecting another one (any other one will do) and save that, then edit again and put the categories back to what they should be. Does that help?"

@-R said:
**"Nothing changed when editing and saving. I clicked each category tag to manually uncheck it but the change wasn't implemented. I also tried wiping every category and saving a new one (hobbies), but it added hobbies to the category list on top of the duplicates, now I can't remove that either lol!
There's only meant to be 2 assigned categories: Time-Management and Getting Organised. It seems that new category selections can be added but saved category selections cannot be removed. When saving is attempted the category tags momentarily display `*string not found`. Perhaps the database isn't updating correctly because existing parameters aren't being located?"**

Here's the categories array after they tried those edits, still showing a duplicate:
```
    "categories": [
        {
            "_id": "5ccf6a4e8b3fbc0012f0e8ee",
            "slug": "getting_organized",
            "name": "getting_organized"
        },
        {
            "_id": "5ccf6a4e8b3fbc0012f0e8ed",
            "slug": "time_management",
            "name": "time_management"
        },
        {
            "_id": "5cd2f1c8ba5dc10011ff9c23",
            "slug": "hobbies_occupations",
            "name": "hobbies_occupations"
        },
        {
            "_id": "5cd2f1c8ba5dc10011ff9c22",
            "slug": "time_management",
            "name": "time_management"
        }
    ],
```

I've fixed the immeidate problem by deleting the duplicate and the hobbies category that was added just for testing. 

There's a second report that's probably related and I'll update this issue when I have more details about it:

Richard Russell   @Rick30024 (27294fb1-52ed-4b30-a565-3d250ca7febe):
**"Hi when i try to update the tags of my guild it will not save update and displays strings not found when its exits from edit window"**

**Comment by Alys** [comment]
Note how in the four categories array entries shown above, there's only two unique _id attributes.

**Comment by Alys** [comment]
actually, sorry, that's wrong, there are four unique _id attributes, they're just very similar.

**Comment by shanaqui** [comment]
This same issue appears to affect challenges as well, when trying to edit them.

**Comment by HerrMoriden** [comment]
is this still an issue ? would like to work on this

**Comment by paglias** [comment]
@HerrMoriden thanks for your interest with all these issues, but please let's only claim one and when it's fixed you can claim another one. Regarding what's still an issue, everything tagged with `help wanted` is something that can be worked on, so just let us know which one you prefer and I'll mark it as in progress for you

**Comment by CuriousMagpie** [comment]
This is still happening--

> Guild and Party categories are not updating when changed by 
> Guild/Party Admin. Issue occurs in Firefox 101 on Windows 10 (updated up
>  to June 2022)
> 
> Steps to replicate:
> 
> 1. Guild leader clicks Menu button next to Invite to Guild, selects Edit
>  Guild
> 2. Guild Edit popup appears, all categories are deselected.
> 3. Changes are saved.
> 
> Expected behavior: The Guild/Party categories are reduced to the 
> intended 3
> 
> Encountered behavior: Refreshing the page undoes all changes made. No 
> other users see the change in question. 
> 
> Please reach out to me with any questions. I can provide a short video 
> displaying the bug in action. 


UUID: da1cddd2-5cfb-4dbf-87a2-4d1fc97af973
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

**Comment by antonderegt** [comment]
Hey! Can I pick this up?

**Comment by CuriousMagpie** [comment]
@antonderegt Absolutely Thank you!
