### ISSUE TITLE
Set the time field

### ISSUE THREAD

**Issue by mbridgham** [HabitRPG/habitica#1116]
In the field for inputting the time you want to start the day the numbers aren't legible.  It looks like they are larger than the box for the field.

**Comment by lefnire** [comment]
yeah it's https://github.com/lefnire/habitrpg/blob/7fe86ac924ac18d69320f46f23944b7bcf116916/views/app/settings.html#L6tL9 . I still haven't wrapped my head around the new *-options option-group option-content class hierarchy stuff. @zakkain any pointers here top-of-the-dome?

**Comment by mbridgham** [comment]
Tyler,

I'm sorry but I don't understand this.   When I click on the link I get a page of data that I don't understand at all.

Also I went to sign on to the 3rd party mobile app for Android you recommended, thank you for that, but it asked for my id and  API token.  I don't know what my user ID is other than knowing it's a string of numbers.  And I don't know what an API token is.

Is there a simple way for me to create a username and password I can remember across devices.  I normally am pre-signed in on my laptop but when it goes down I only know how to sign in through the Facebook button.  I'd like better personal mental control around my access.  Thanks much.

Marc

**Comment by lefnire** [comment]
it was more a note to self and zak, for when we can get around to fixing
it. To get your user id and api token, click the settings tab, it's on the
right most pane.

**Comment by mbridgham** [comment]
Ah, thanks much!

Are you still looking for input for the Diabetes presentation?  I filled out the survey but I've had something further supporting, testimonial type thoughts I'm happy to share for you to use if helpful.

Marc

**Comment by StanLindsey** [comment]
@mbridgham - can you email me on stan [at] habitrpg.com regarding diabetes. 

Also, fixed with https://github.com/lefnire/habitrpg/commit/205bf24e02ab2486cf3356ae272b8a0a5cbd7d10
