### ISSUE TITLE
npm start Doesn't Start

### ISSUE THREAD

**Issue by rafucuk** [HabitRPG/habitica#11164]
Hi! I'm using Linux for Habitica. I do "npm install" and other things in https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux

But when i do "npm start" it doesn't starting.

Log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.8.0
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.94.1~prestart: habitica@4.94.1
6 info lifecycle habitica@4.94.1~start: habitica@4.94.1
7 verbose lifecycle habitica@4.94.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.94.1~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rauf/Masaüstü/habitica-develop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle habitica@4.94.1~start: CWD: /home/rauf/Masaüstü/habitica-develop
10 silly lifecycle habitica@4.94.1~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle habitica@4.94.1~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.94.1~start: Failed to exec start script
13 verbose stack Error: habitica@4.94.1 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid habitica@4.94.1
15 verbose cwd /home/rauf/Masaüstü/habitica-develop
16 verbose Linux 4.18.0-17-lowlatency
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.4
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.94.1 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the habitica@4.94.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Alys** [comment]
That says 
```
2 info using npm@5.8.0
3 info using node@v8.11.4
```
so it looks like you're using the wrong versions of npm and node. See "Install Node and NPM" in https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux for more details.

I'll close this issue for now since hopefully that will fix all the problems however if you run into any other trouble, post again to this issue and we'll reopen it and keep helping you!

**Comment by rafucuk** [comment]
Ahh again!

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.94.1~prestart: habitica@4.94.1
6 info lifecycle habitica@4.94.1~start: habitica@4.94.1
7 verbose lifecycle habitica@4.94.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.94.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rauf/Masaüstü/habitica-develop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle habitica@4.94.1~start: CWD: /home/rauf/Masaüstü/habitica-develop
10 silly lifecycle habitica@4.94.1~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle habitica@4.94.1~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.94.1~start: Failed to exec start script
13 verbose stack Error: habitica@4.94.1 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid habitica@4.94.1
15 verbose cwd /home/rauf/Masaüstü/habitica-develop
16 verbose Linux 4.18.0-17-lowlatency
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.94.1 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the habitica@4.94.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by paglias** [comment]
@RaufSSen the logs are not very clear, I would suggest to fully remove the `node_modules` folder and `package-lock.json` file and try to run `npm install` again looking for possible errors in the logs

**Comment by rafucuk** [comment]
I'm still waitin' help.

**Comment by paglias** [comment]
@RaufSSen I posted a possible solution in the previous comment, have you tried it?

**Comment by rafucuk** [comment]
yes i tried. Same error.

**Comment by rafucuk** [comment]
And what is proxy?

**Comment by paglias** [comment]
What do you mean by proxy?

**Comment by rafucuk** [comment]
When i try with `npm run client:dev` it saying proxy. Then it's opening server in `localhost:8080` but when i try to open account or insert a name it's givin' error.

**Comment by rafucuk** [comment]
@Alys help

**Comment by rafucuk** [comment]
I see anyone is helpin' me then im closin' this.
