### ISSUE TITLE
Login broken - changes case of what I typed

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#1117]
I've been using the beta site for a while. Today it was misbehaving, and I tried to login to the main site. No luck. I tried both forms of my login name - with and without its first character upper case, since frankly I can't remember which it is. One form gave me "no such player" [not the exact message]. The other form - kept being converted to the previous form. IIRC, when I clicked on the lower case selection, or tried to type it, it was auto-converted to upper case. (The browser gives me auto-completion choices once I start typing, hence the "clicked on".) 

Fortunately the beta site is back up, and still remembers me as logged in. For now ;-)

I'm using firefox 21.0, on Ubuntu 12.04 I have not updated it recently. I.e. I don't think the behaviour started with a browser "upgrade".

**Comment by lefnire** [comment]
do you have your [user id](https://github.com/lefnire/habitrpg/wiki/User-ID) handy?

**Comment by ArlieS** [comment]
Spontaneous remission occurred; I retried and found it let me in. I did not restart my browser, let alone reboot. 

4dc03dc4-4be9-44f4-9b50-c5a217f95ac2

**Comment by lefnire** [comment]
Yeah, your auth property is just fine - you in now?. If not I have your
uname / email handy if you need. you probably just caught the server on a
downtime

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
