### ISSUE TITLE
Accepting quest does not update participant numbers until refresh

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11173]
> Bug: Accepting a quest does not update the participating player count (e.g., 3/10) until refresh.

From Report a Bug. Not confirmed.

Not sure if we expect this to update live, but filing it as the best way to get the question on the radar.

**Comment by rogesson** [comment]
Hello everyone!

I can make this adjustment as a first contribution :)

**Comment by Alys** [comment]
@rogesson Great, thank you! Please go ahead and post here if you have questions!

**Comment by shanaqui** [comment]
@rogesson Hi there! Are you still working on this issue? If not, or if we don't hear back from you within a week, I'll mark it as help wanted again just to make sure it doesn't go stale. :)

**Comment by rogesson** [comment]
Hello @shanaqui,  how are you?

After some time without being able to continue, today i made a new commit in the PR that is open with the requested modifications.

I'm commenting here because I saw that there was no automatic notification.

Thanks and sorry for the delay!

**Comment by shanaqui** [comment]
Thanks for the update! :)
