### ISSUE TITLE
Character customisation during signup lacking options

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11171]
We've had a couple of remarks about this lately. It's not possible to remove the ponytail during setup (at least on web) for example:

![image](https://user-images.githubusercontent.com/8144640/57812996-99aafc00-7766-11e9-93c6-436bb9a9d75a.png)

Another user says:

> In character creation there is no way for me to avoid having a flower in my hair and long hair down the side. I can choose Color, Bangs, and Style. I think there is a bug in the Style section so it only gives me two similar options.

**Comment by SabreCat** [comment]
This'll be fixed with today's deploy. Also corrects the poor alignment of the "color, bangs, style" headings here.
