### ISSUE TITLE
Comment mouseover very picky for large comments

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1118]
(Using Chrome browser on Windows)

I put comments on most of my Habits, to document the conditions I've committed to for hitting the - or +. Most of them work fine, but for some, the area where mousing over the word bubble icon produces the comment popup is tiny: perhaps two or three pixels wide. I have to twitch my mouse very minutely to get it to appear. Moreover, when I do get it to show up, the arrow points off field, making it look awkward:

![screenclip](https://f.cloud.github.com/assets/4501321/595819/4dba812a-cb33-11e2-9400-d919cfdcc384.png)

It appears to be correlated to the size of the popup. For comments of only a few words, I have no trouble targeting, and the word bubble points appropriately. However, it is not related to position with respect to screen or browser window--there's plenty of space next to my Dailies column, for instance, but too long a popup bubble runs into the same trouble.

**Comment by kalmduck** [comment]
I think this is either the same problem (or a close relative to it) as https://github.com/lefnire/habitrpg/issues/399

**Comment by lefnire** [comment]
same indeed, closing as dupe
