### ISSUE TITLE
Conversations in Inbox often open at the beginning

### ISSUE THREAD

**Issue by majestic-owl448** [HabitRPG/habitica#11182]
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Google Chrome 74.0.3729.157 64bit
  * OS: Windows 10 Pro v. 1803

### Description
Below Report a Bug guild conversation
So, I can say it is not exactly every time, but for now it happens pretty often when I just got a new message. I had a notification of a new message, I went to open the conversation and found it scrolled up at the beginning of the conversation.
It seems it is happening when I open it a moment too early than it when it has finished loading
needs more infos, I am happy to make more trials 

> Alys
> @Alys•a day ago  (3rd Party)
> 
> @ieahleen Interesting. I can't replicate that so it's either already fixed in the 22 hours since you reported this or browser-specific or something else odd is going on. Can you please reload the website to ensure you have the latest fixes and if it's still happening, could you please log it in GitHub and say what operating system your computer is using and what browser you use? Mention in the issue that I asked you to log it. I'm suggesting that you log it because it's likely that the staff will have questions for you and GitHub will email you when they post to your issue.
> 
> IM @ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b): "Whenever I open a conversation in my inbox I need to manually scroll down to last message received, before the conversation was already scrolled down when I opened a conversation"

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
This happened to me once today: _"I had a notification of a new message, I went to open the conversation and found it scrolled up at the beginning of the conversation."_

I hadn't been paying close attention so I don't know this was relevant to my case: _"It seems it is happening when I open it a moment too early than it when it has finished loading"_
I'll watch for it next time.

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitica/issues/11220  might be another case of this.

**Comment by paglias** [comment]
Given the recent updates to the inbox UI, is this still happening or can be closed?

**Comment by Alys** [comment]
I have not seen reports of it or noticed it myself so I'll close it. We can reopen if it's still happening.
