### ISSUE TITLE
( General installation issue not an issue with the application directly ) :- is vagrent or docker compulsory to install ?

### ISSUE THREAD

**Issue by gautamz07** [HabitRPG/habitica#11194]
Hi , Iám using windows 8 and i just wanted to know if vagrant or docker is compulsory to install in order to run this application locally ? or are vagrant and docker optional .. ? 

Went through this link [HERE](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally) and it seems to be compulsory ..

**Comment by Alys** [comment]
No, it's not compulsory. Did you see the "Setting up Habitica Locally on Windows" link in the introduction to that page? The Windows instructions don't refer to Docker or Vagrant.

We use GitHub just for bug reports or problems with installations that need advanced help, so if you have any other questions, the Aspiring Blacksmiths guild is the best place to ask (there's a link to it in the installation instructions). The Guidance for Blacksmiths wiki page is worth reading too if you haven't already seen it (it's linked from there too).

**Comment by gautamz07** [comment]
@Alys , thanks i have installed habitica successfully, was just wondering if they were compulsory ( Docker or vagrent ) , and yes i refered to the windows installation guide , Will go through the blacksmiths page. 

Thank you for your help.
