### ISSUE TITLE
Dailies not resetting

### ISSUE THREAD

**Issue by virgiliu** [HabitRPG/habitica#112]
I set a daily yesterday at lunch and marked it as done. Today when I looked at the list it was still marked as done even though it's a new day.

Maybe the user should be able to set his timezone so that the dailies reset at midnight in the user's local time, not server time.

**Comment by sigboe** [comment]
It does not use timezones. There is some Javascript that asks your computer, Is it next day yet? If it is it should reset the daily task. 
It might have something to do with server downtime or something? IDK.

**Comment by virgiliu** [comment]
Nothing like that showed up for me.

**Comment by JamPol** [comment]
Same here. I didn't try from my computer though, accessed through my phone. Did you access through phone as well?

**Comment by MercuryChaos** [comment]
I'm having the same problem. I tried clearing my browser cache and it didn't help – all the dailies I checked yesterday are still greyed-out and checked, and un-checking them only causes me to lose experience.

**Comment by lefnire** [comment]
this should be fixed now, re-open otherwise

**Comment by lefnire** [comment]
(it was a change in a library's api, took some debugging)

**Comment by gbuell** [comment]
I'm not sure this is resolved, because the same thing's happened to me today. Dailies I checked off yesterday are still checked off today.
