### ISSUE TITLE
quest system messages sometimes have double backticks (rage attack, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11202]
As reported by @Chandramani_Adil (58de0b72-3af8-4f2a-b9a1-f7d196b29757), some quest system messages are incorrectly formatted because they have nested backticks:

![index](https://user-images.githubusercontent.com/1495809/58768912-04708a00-85e5-11e9-9e10-3d686bd04505.jpeg)

It happens when the messages already contain backticks in the translatable strings. The code that displays the messages always inserts its own backticks around the translatable strings. It was reported for a boss_rage message but other types of system messages are also affected. I've included details below.

Perhaps the easiest fix for this would be for the code that displays the messages to first check if there's at least one backtick already in the message and then not display it. ~`I'll leave this issue as suggestion-discussion for a few days for the staff to comment if they wish, and then if there's no objections I'll mark it as help wanted for that fix.`~

This is the code that inserts the backticks:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/server/libs/chat/group-chat.js#L36-L106

For example, for the exact instance shown in the screenshot above:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/server/libs/chat/group-chat.js#L50
(For those new to JavaScript, the outer backticks on that line are just for quoting the string in a way that allows variable interpolation; the inner backticks which are escaped by backslashes are the ones that are printed as part of the string.)

Some or all of the relevant strings are in `website/common/locales/en/questsContent.json` and this is the one shown in the screenshot:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/common/locales/en/questsContent.json#L399

This issue can't be fixed by removing the backticks from the translatable strings because for some examples, only part of the string is formatted with backticks:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/common/locales/en/questsContent.json#L436

In any case where the translatable string includes one or more backticks, the code that displays that string should not insert its own backticks.

In case it helps, this is the relevant data for the quest "system" message stored in the `chats` collection in the database:
```
{
    "_id": "1cb8587f-740e-46e4-ae8f-ef07cca1c05b",
    "text": "`Magical Axolotl uses AXOLOTL REGENERATION!`\n\n`A curtain of colorful bubbles obscures the monster for a moment, and when it clears, some of its wounds have vanished!`",
    "info": {
        "type": "boss_rage",
        "quest": "axolotl"
    },
    "timestamp": "2019-06-01T04:11:34.396Z",
    "uuid": "system",
},
```

**Comment by ofekmiz** [comment]
Hi, is this a new feature? in my party I only see messages like this:
"Player attacks Boss for 12.2 damage. Boss attacks party for 5.3 damage."

**Comment by Alys** [comment]
@ofekmiz The bug happens only when the translatable string already contains backticks. The example from your question and any others in your party chat that don't show the problem don't have backticks in their strings - the backticks are added by code when the messages are posted.

https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/common/locales/en/quests.json#L132

**Comment by whybin** [comment]
May I try my hand at this, given that the PR #11250 addressing this issue hasn't been revisited in almost a month? Thus far, that code seems to universally apply backticks to all messages excluding them, which might not be the desired behavior.

**Comment by Alys** [comment]
@whybin Thanks for asking about this! I think we should give @Scens a
little longer, since that pull request is nearly complete.

It's desired to have all system messages surrounded by backticks and
currently the `translateMessage` function should be used only by system
messages (they're the only ones that have an `info` field in the chat
message):
https://github.com/HabitRPG/habitica/blob/c80de385724d635cb199c1705818367663501036/website/server/models/group.js#L355-L358

However if you're seeing something that would make the backticks apply to
literally all messages, please let us know!

**Comment by whybin** [comment]
@Alys Apologies, I wasn't aware the intended behavior was for all system messages to receive backticks. I now understand the decisions made in the PR. Thanks for clarifying!
