### ISSUE TITLE
hair styles layout is unbalanced - free options mixed with purchasable sets

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11200]
This is not exactly a bug but a thing that affects usability and attractiveness of the website.

As metaphorical_snail (cb0db625-873b-4e58-a1e1-2c7d0d9ae939) reported:
"the free hair styles aren't at the top of the hair page. They're nestled among the gem options which makes them harder to see and awkward to select."

See the screenshot below. If the two free options were on the top row next to the icon for no hair style, then they'd be easy to access, and would look nice if they were centred. The three sets of purchasable styles would then be neatly lined up with each other under that.

![image](https://user-images.githubusercontent.com/1495809/58740084-ac554e80-8451-11e9-82d9-992d2b7b256f.png)

I'll leave this as suggestion/discussion for a few days to give the staff time to comment and then if there's no objections I'll mark it as help wanted.

**Comment by Chinmaygoyal** [comment]
Can I give this one a try?

**Comment by Alys** [comment]
@Chinmaygoyal I'm very sorry no one replied to you! Are you still interested in working on this? If so, post a brief reply and we'll mark it as in progress for you.

**Comment by tvaz** [comment]
If this one is still available, I'd like to take a crack at it for Hacktoberfest if that's OK!

**Comment by Alys** [comment]
@tvaz Thanks! Please go ahead! Comment here if you have any questions.

**Comment by adamfitzgibbon** [comment]
Looks like there hasn't been much action on this one for a while. I'll look for others, but let me know if you decided not to work it, @tvaz

**Comment by tvaz** [comment]
@adamfitzgibbon if you were looking to work this, go ahead!

**Comment by adamfitzgibbon** [comment]
Alright thanks! Of course if you were still wanting to work it I don't want to steal it from you, so just let me know if that's the case!
