### ISSUE TITLE
Avatars may not display on old posts

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11223]
From RaB:

> _citrusella, the serving elf @citrusella (2d6ef231-50b4-4a22-90e7-45eb97147a2c): "This might only be an intermittent bug that happens with old posts, but I noticed after looking in the Back Corner (though I don't think it's necessarily limited to that guild) that some messages had loaded without an avatar associated with them at all. (Like, in the source code, it looks identical to as if you opened, say, my message here (or anyone else that's not yours), and deleted the avatar avatar-left node (I think system messages have this sort of layout too?).) It wasn't consistent between reloads which people this applied to but it always applied to one person, at least (some very inactive, some very active, no seeming rhyme or reason that's *easy* to ascertain). It looks confusing without the avatar because the message is then left aligned and looks vaguely (at least to me because my browser frequently starts to have problems displaying images) like a post of mine that didn't load the avatar because there's some space to the message's right at that point (though technically not space for an avatar if one really pays attention to the gap).
> 
> So in short: A) (bug) It's possible for a user's message to not load anything remotely connected to an avatar with the post (but this might only happen under specific circumstances or only to old posts or something) and B) (confusing visual side-effect) the resulting avatarless card aligns all the way left.
> 
> I can try to get a picture if this description wasn't helpful, but my computer is being fussy right this moment."_

I found the same. Example screenshot -- my old posts show my current avatar, but these users' posts don't show any avatar and align with my posts. The users still exist.

![image](https://user-images.githubusercontent.com/8144640/59505358-213a7680-8e9d-11e9-9c96-9b42d846a143.png)

**Comment by majestic-owl448** [comment]
Just to contribute to the investigation... are there more recent posts of this users in the guild? If there aren't, maybe that could be a cause

**Comment by paglias** [comment]
So the way we load the avatar has changed in the past few months and we had a fallback for older posts but it might be failing. Another cause would be the user deleting their account

**Comment by SabreCat** [comment]
The users don't appear to have been deleted. Could be the fallback isn't working.

**Comment by veeeeeee** [comment]
Closing as this is increasingly irrelevant to the current product.
