### ISSUE TITLE
website footer covers task three-dots menu (z-index problem?)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11227]
As ieahleen reports in the Report a Bug guild:

"It is not possible to access the three-dots-menu of the tasks at the bottom of the screen, the menu appear under the footer:"
![image](https://user-images.githubusercontent.com/1495809/59557859-d731cc00-9027-11e9-8992-c935190d5909.png)

It might be because the z-index of the footer is too large.

You can replicate this with a task that has no note. (You don't see the bug with a task that has a note because the note will push the bottom of the task down far enough that the three-dots menu doesn't reach the site footer.)

----

_edit by Alys 2020-02-02:_

This was fixed in https://github.com/HabitRPG/habitica/pull/11230 but has started happening again as shown in the recent comment below. That PR might contain useful information for fixing the bug again.

The bug is slight different now than originally: 
When you move your mouse away from the drop-down menu it becomes fully visible. It's only hidden by the footer when your mouse is over the menu, so the problem might lie in styles that are only used for the on-hover state.

**Comment by freyacodes** [comment]
I think I've found a solution. It appears to both be caused by the z-index and the overflow.

Let me see about setting up a dev environment.

**Comment by Alys** [comment]
Thanks @Frederikam ! I've changed the label on this issue to in progress.

**Comment by shanaqui** [comment]
@jamesisaacm (d8617135-a8e8-491d-9fa1-0945203c47c0) reported:

> When opening the Edit / To Top / To Bottom / Delete menu on Dailies on the bottom of the screen, some of the menu is covered up by the Site Map at the bottom of the page. Hovering over where the menu would be causes the bit originally covered up to flash, appearing half of the time. Not extremely important, but it really bugs me.

I've confirmed the behaviour in Firefox.

![image](https://user-images.githubusercontent.com/8144640/73599015-e0c85f80-4536-11ea-8f35-f5be3b30acc5.png)

It does pop out and allow the buttons to be used if you wiggle the mouse and dance widdershins, but it's a bit of a pain.

I think this issue needs to be re-opened? Or should I create a new one for this?

**Comment by Alys** [comment]
I'm reopening this since it looks like exactly the same behaviour that was originally reported. 

A fix had been made in https://github.com/HabitRPG/habitica/pull/11230 which did work at the time, so I'm guessing it's been inadvertently reverted or overwritten with more recent changes. I've updated the top post to say that the code in that PR might help to resolve the issue again.

I'm marking this help wanted again too.

**Comment by freyacodes** [comment]
> it looks like exactly the same behaviour that was originally reported.

It is not exactly the same. Unlike with the initial issue, the clipping seems to depend on where the mouse is pointing.

**Comment by Alys** [comment]
@Frederikam Ah, thank you! I hadn't noticed that.

When you move your mouse away from the drop-down menu it becomes fully visible. It's only hidden by the footer when your mouse is over the menu, so the problem might lie in styles that are only used for the on-hover state.

I'm copying that to the top post too.

**Comment by actuday6418** [comment]
Could I give this a go?

**Comment by Alys** [comment]
@actuday6418 So sorry about the delay! Yes, please go ahead (although if you're no longer interested post again here and I'll set it back to help wanted).

**Comment by actuday6418** [comment]
I would love to take this up. Any pointers as to which direction to take? I'm new to Habitica's code base. Thank you!

**Comment by Alys** [comment]
@actuday6418 It's likely to be the same bug or a similar one as the one that was fixed last time, so the previous fix might give you some pointers. See above for the link to the merged pull request ("Fix task dropdown menu overflow") - that will show you the code changes that were done then.

If that doesn't help or if you have any other questions, post again here!

**Comment by actuday6418** [comment]
I made this PR after changing the footer's z-index from 17 to 10. That doesn't seem to have any adverse effects but still solves the problem. However, the PR made for issue  #11831 appears to be a change in the z-index of the three-dot menu itself. Would that then solve our problem too?

**Comment by joefessenden** [comment]
@actuday6418 I ended up not changing the z-index at all. Instead, I removed the "relative" css declaration from ".task". I did test with my code, though, and it looks like it resolves this issue, too, at first glance.
