### ISSUE TITLE
Avatar edit window layout mangled

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11221]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Something appears to have thrown off the layout of the edit avatar window:

![image](https://user-images.githubusercontent.com/4501321/59436263-e5c47d00-8db4-11e9-8ffe-a00b1d39a184.png)

* The z-index is wrong, landing the modal beneath the navigation bar.
* (Possibly) The modal is too high on the page.
* There is much more whitespace below the avatar than needed.

**Comment by SabreCat** [comment]
Tried sending up a fix, but my local dev environment isn't showing the issue, while production continues to do so.

Local:

![image](https://user-images.githubusercontent.com/4501321/59469067-6b6a1c00-8df9-11e9-9522-127cde809f06.png)

Prod:

![image](https://user-images.githubusercontent.com/4501321/59469108-82107300-8df9-11e9-9ea2-8a6cea798f15.png)

**Comment by SabreCat** [comment]
The trouble appears to be this class in `creatorIntro.vue`:

https://github.com/HabitRPG/habitica/blob/develop/website/client/components/creatorIntro.vue#L461-L463

However, if I remove it, my local instance ends up with this monstrosity:

![image](https://user-images.githubusercontent.com/4501321/59469293-1084f480-8dfa-11e9-998d-9a70469e8a43.png)

...so I'm reluctant to go ahead with that change. halp?

**Comment by mbernardes19** [comment]
![image](https://user-images.githubusercontent.com/26047592/60712829-3def2a80-9eee-11e9-9df3-10405cc768ba.png)

I've simply found the div in which the image is and changed the top property from -22px to 44px. I believe it's just a matter of positioning it like that.

**Comment by negue** [comment]
I think these issues were already fixed by the bigger redesign #11241
