### ISSUE TITLE
Documentation for the process of adding people to parties?

### ISSUE THREAD

**Issue by bluetailedgnat** [HabitRPG/habitica#1122]
I have an issue where I've added someone to my party, she tells me she's clicked Accept and can see me, and I can't see her, and I can't even tell if this is a bug because I don't know how it's supposed to work.

Can there be some documentation so that I can tell if this is a bug or not/figure out, specifically, what isn't working?

**Comment by StanLindsey** [comment]
Once they accept they immediately be in your party as long as there aren't any conflicts. (She isn't in a party before accepting yours? I'm not sure if thats a possible conflict.) 

If she has the option of leaving her party then can she try that and then you re-invite her?

Can you leave your UIDs here - @lefnire can possibly manually set your parties or maybe there is an obvious fault lerking there.

Thanks for the report!

**Comment by lefnire** [comment]
We may want to wait for the upcoming guilds push, as it fixes some party
bugs in the process - could solve issues here

**Comment by bluetailedgnat** [comment]
I eventually managed to solve the problem by having her leave and rejoin
the party and then refreshing my browser window (which didn't work the
first time, even with intervening server downtime). Somehow that worked.

Thanks, and sorry I can't be more helpful/specific in what happened.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
