### ISSUE TITLE
Npm start failling (Cannot find module 'babel-core') - Ubuntu19 in VM on Windows

### ISSUE THREAD

**Issue by rsamborski** [HabitRPG/habitica#11225]
### General Info
  * OS: Ubuntu 19 running in Virtualbox on Windows 10
  * Kernel: Linux 5.0.0-16-generic
  * node v10.15.2
  * npm  v6.9.0

I am running everything in Virtualbox on Ubuntu 19. What is specific to my install is that folder with Habitica files is located on Windows partition and shared to guest. Nevertheless due to known issues with such setup I have created node_modules folder on ext3 partition and made a symlink, so all npm stuff goes there. 

### Description

I have been following the instruction on page https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux, but keep getting following error after running `npm start`:

```
ubuntu@ubuntu19:~/projects/habitica$ sudo npm start

> habitica@4.100.0 start /media/sf_Projects/habitica
> gulp nodemon

Sat, 15 Jun 2019 08:23:12 GMT uncaughtException: Cannot find module 'babel-core'
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ubuntu/misc/habitica_node_modules/gulp-babel/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/home/ubuntu/misc/habitica_node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/misc/habitica_node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.100.0 start: `gulp nodemon`
npm ERR! Exit status 1
```

Multiple times I have removed node_modules folder, run npm cache clean --force, etc. Nothing seems to be helping. `npm install` goes well, but `npm start` throws the error.

#### Console Errors
Full log of my actions: https://gist.github.com/rsamborski/cef446ccdf82ca0a70e4537fa3775fb9

**Comment by garvitkhandelwal** [comment]
Have you tried installing `babel-core` as your dev dependency? 
Try `npm install --save-dev babel-core babel-preset-env`

**Comment by rsamborski** [comment]
@garvitkhandelwal I did now, but it didn't help:
```
ubuntu@ubuntu19:~/projects/habitica$ npm install --save-dev babel-core babel-preset-env
npm notice save babel-core is being moved from dependencies to devDependencies
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-lodash@2.7.0 requires a peer of eslint@>=2.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-mocha@4.12.1 requires a peer of eslint@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@2.0.6 requires a peer of webpack@^2.2.0 || ^3.0.0 || ^4.0.0-alpha || ^4.0.0-beta || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.11 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

+ babel-preset-env@1.7.0
+ babel-core@6.26.3
added 87 packages from 61 contributors, removed 50 packages, updated 1 package, moved 1 package and audited 45577 packages in 92.503s
found 39 vulnerabilities (15 low, 17 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
ubuntu@ubuntu19:~/projects/habitica$ npm start

> habitica@4.100.0 start /media/sf_Projects/habitica
> gulp nodemon

Sat, 15 Jun 2019 19:33:52 GMT uncaughtException: Cannot find module 'babel-core'
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ubuntu/misc/habitica_node_modules/gulp-babel/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/home/ubuntu/misc/habitica_node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/misc/habitica_node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.100.0 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the habitica@4.100.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-06-15T19_33_52_469Z-debug.log
```

I skipped `npm audit`, because it only shows some vulnerabilities and this is a dev environment.

Additionally I was playing around with `unsafe-perm` setting, but it seems to not have any impact:
```
ubuntu@ubuntu19:~/projects/habitica$ npm config ls | grep perm
unsafe-perm = false
ubuntu@ubuntu19:~/projects/habitica$ cat /home/ubuntu/.npm/_logs/2019-06-15T19_33_52_469Z-debug.log | grep perm
7 verbose lifecycle habitica@4.100.0~start: unsafe-perm in lifecycle true
```

**Comment by garvitkhandelwal** [comment]
I just checked that they have changed the command after version 6.
As for version 7, try installing it using the following command instead
`npm install --save-dev @babel/core @babel/preset-env`

**Comment by rsamborski** [comment]
Unfortunately the issue remains.

**Comment by paglias** [comment]
If you go into the node_modules folder is babel-core there? I think there are wider issues but the error you see is only about babel-core because it's the first package that gets loaded.

Can you try by deleting the node_modules folder, reinstalling with npm install and see how it goes? It would be useful to see the output of `npm install`

**Comment by rsamborski** [comment]
@paglias I tried removing node_modules folder several times with no luck :(
You can find `npm install` output here: https://gist.github.com/rsamborski/cb5e582ebf8b22c48a5cea587e52558c

I have also included `npm start` and `ls | grep babel`. 
I believe this is related to running Ubuntu in VM but I don't have another choice. Maybe someone is using similar configuration successfully?

**Comment by paglias** [comment]
@rsamborski unfortunately I really have no idea of what could be causing this :( The only thing I'd try is to reinstall everything from scratch following the Wiki instructions (we recently upgraded to node 12)

**Comment by rsamborski** [comment]
@paglias I found a solution to this issue here: https://github.com/npm/npm/issues/10013#issuecomment-189176273, https://github.com/yarnpkg/yarn/issues/6069#issuecomment-404198052

It seems that this doesn't work:
`lrwxrwx--- 1 root vboxsf       0 Aug 21 21:46 node_modules -> /home/ubuntu/misc/habitica_node_modules`

But this does:
`lrwxrwx--- 1 root vboxsf       0 Aug 21 21:46 node_modules -> /home/ubuntu/misc/habitica/node_modules`

So now `npm start` doesn't show any issues with missing modules of babel modules, but I am getting an issue related to bcrypt. 

Dump is available here: https://gist.github.com/rsamborski/ad12d776b0c07c603998698565773e8a

**Comment by paglias** [comment]
Looks like even bcrypt had issues being installed correctly. To be honest i'm not sure this is ever going to work on Virtualbox. We have several people working on Ubuntu with no issues and our CI pipeline runs several times on Ubuntu every day so it's possible it's a Virtualbox issue

**Comment by SabreCat** [comment]
Closing this for now. If we can reproduce this outside of a specifically VirtualBox environment, it'd be worth reopening!
