### ISSUE TITLE
Group Plan Dailies approval and/or singleCompletion causing cron to fail (quest progress and user damage not applied)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11231]
Kalani / @KalaniTheArtist (2e558a6e-5afa-485c-b7a6-b9ca8a3c56ca) reported:
_"I have an error message that says 'Cast to Number failed for value "NaN" at path "party.quest.progress.down", and I still show damage pending. I've also not taken personal damage for undone dailies. I saw this error message yesterday and today, so cron isn't reseting... whatever the problem is. Desktop version, on Chrome."_

The associated [error from Loggly](https://habitica.loggly.com/search#terms=2e558a6e-5afa-485c-b7a6-b9ca8a3c56ca&from=2019-06-14T00:00:00.000Z&until=2019-06-16T22:20:26.297Z&source_group=&event=8cf059a3-9058-11e9-802c-0234fe2ede76,1560704560564,137799973607594403) is below but the critical part is this ValidationError:
`User validation failed: party.quest.progress.down: Cast to Number failed for value "NaN" at path "party.quest.progress.down"`
`... at tasksByType.dailys.forEach.task (/usr/src/habitrpg/website/transpiled-babel/libs/cron.js:399:46)`

Kalani has one Daily with a streak of zero (Dailies with higher streaks are unlikely to be relevant for this bug since they won't cause `party.quest.progress.down` to be increased). The relevant parts of the Daily are below, copied from the database when I saw Kalani's report of the problem several hours after cron had run.
**Of particular note is that it's a Group Plan Daily with approval required and requested but not given, and it's also a `singleCompletion` Daily with one other person assigned to it.**
The history entries correspond to the timestamps of Kalani's partially-completed crons (taken from Amplitude).

I think it's possible that the Daily is causing the cron error, perhaps because/if it was completed but not approved at the time that cron ran and/or because of an interaction related to the `singleCompletion` feature.

Further information might be obtained by examining the crons and data of the other person assigned to this task, if you can get their permission to look at their data.

``` 
{
    "_id": "5db49450-a87e-4f01-98fc-f5494c567ae5",
    "repeat": ... [all repeat settings cause the Daily to be due every day] ...,
    "completed": false,
    "group": {
        "approval": {
            "required": true,
            "approved": false,
            "requested": true,
            "requestedDate": "2019-06-15T16:55:44.343Z"
        },
        "assignedUsers": [
            "[snip for privacy since this player hasn't reported an error]",
            "2e558a6e-5afa-485c-b7a6-b9ca8a3c56ca"
        ],
        "sharedCompletion": "singleCompletion",
        "id": "7720c71e-fe43-4bf0-8b52-10644df703eb",
        "taskId": "e645f98c-c363-4850-9f51-7c6c0ccefc40"
    },
    "streak": 0,
    "nextDue": [
        "Mon Jun 17 2019 00:00:00 GMT-0500",
        ... every day ...
        "Sat Jun 22 2019 00:00:00 GMT-0500"
    ],
    "history": [
        {
            "date": 1560562300890,	// 	UTC: 2019-06-15 01:31:40
            "value": 0
        },
        {
            "date": 1560617839827,	// 	UTC: 2019-06-15 16:57:19
            "value": 0
        },
        {
            "date": 1560704560434,	// 	UTC: 2019-06-16 17:02:40
            "value": 0
        }
    ],
    "type": "daily",
    "tags": [
        "7720c71e-fe43-4bf0-8b52-10644df703eb"
    ],
    "value": 0,
    "startDate": "2019-06-12T05:00:00.000Z",
    "createdAt": "2019-06-12T15:29:48.791Z",
    "updatedAt": "2019-06-16T17:02:40.502Z",
    "userId": "2e558a6e-5afa-485c-b7a6-b9ca8a3c56ca",
    "isDue": true
}
```

Loggly error:

```
{
"method":"POST",
"originalUrl":"/api/v4/cron",
"headers":{...},
"body":{},
"httpCode":400,
"isHandledError":true,
"fullError":{
	"errors":{
		"party.quest.progress.down":{
			"message":"Cast to Number failed for value \"NaN\" at path \"party.quest.progress.down\"","name":"CastError","stringValue":"\"NaN\"","kind":"Number","value":null,"path":"party.quest.progress.down",
			"reason":{"message":"Cast to number failed for value \"NaN\" at path \"party.quest.progress.down\"","name":"CastError","stringValue":"\"NaN\"","kind":"number","value":null,"path":"party.quest.progress.down"}
		}
	},"_message":"User validation failed","message":"User validation failed: party.quest.progress.down: Cast to Number failed for value \"NaN\" at path \"party.quest.progress.down\"","name":"ValidationError"
},
"timestamp":"2019-06-16T17:02:40.564Z",
"level":"warn",
"message":"ValidationError: User validation failed: party.quest.progress.down: Cast to Number failed for value \"NaN\" at path \"party.quest.progress.down\"\n
    at new ValidationError (/usr/src/habitrpg/node_modules/mongoose/lib/error/validation.js:30:11)\n
    at model.Document.invalidate (/usr/src/habitrpg/node_modules/mongoose/lib/document.js:2080:32)\n
    at model.$set (/usr/src/habitrpg/node_modules/mongoose/lib/document.js:1029:10)\n
    at Document.set [as down] (/usr/src/habitrpg/node_modules/mongoose/lib/helpers/document/compile.js:125:26)\n
    at tasksByType.dailys.forEach.task (/usr/src/habitrpg/website/transpiled-babel/libs/cron.js:399:46)\n
    at Array.forEach (<anonymous>)\n
    at cron (/usr/src/habitrpg/website/transpiled-babel/libs/cron.js:341:22)\n
    at cronAsync (/usr/src/habitrpg/website/transpiled-babel/middlewares/cron.js:96:35)\n
    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```

_EDIT: DONE: I've marked this as "notify helpers" so that I'll look at this issue again in detail when it's closed. I want to tell the leader of this group plan when this bug is fixed._

**Comment by Alys** [comment]
There might also be an interaction with this bug: https://github.com/HabitRPG/habitica/issues/10985 " Group Plan tasks need second completion after approval".
For example, perhaps the leader DOES approve the Daily before cron but the person who completed it doesn't realise that they have to mark the Daily complete a second time to work around that bug (or doesn't have time to do that if it's approved after they've gone to bed). When cron runs and sees the Daily incomplete, cron would try to modify `party.quest.progress.down`, although strictly speaking it shouldn't in that case.

**Comment by Alys** [comment]
Hmmmmm. Single completion isn't meant to be available for Dailies yet, is it? It's definitely turned on for that Daily though, assuming that's what `"sharedCompletion": "singleCompletion"` refers to. In commit 1135ab946e on 2019-04-29 ("fix(group-tasks): default single completion on client" in the commit comment), the tasks' model was changed from this:
`sharedCompletion: {$type: String, enum: _.values(SHARED_COMPLETION), default: SHARED_COMPLETION.default},`
to this:
`sharedCompletion: {$type: String, enum: _.values(SHARED_COMPLETION), default: SHARED_COMPLETION.single},`
and I'm wondering if that has caused the bug. Is that an appropriate default for To-Dos but not Dailies, perhaps?

**Comment by SabreCat** [comment]
Yeah, there's some contributor work going on to implement shared completion for Dailies, but it's not live. That said, it's _probably_ a red herring here, as `sharedCompletion` has nothing to do with `party.quest.progress.down`. The approval flow you were looking into upthread is a bit more likely a trouble area.

**Comment by Alys** [comment]
The leader of the Group Plan that Kalani is in has said "I see the problem. I usually log in on my Android Phone. Since I don't get notifications there and we're new to groups, I didn't see that I had notifications to approve Dailies. As a temporary fix, we're done with that Daily for now so I deleted it. For now, I'll not use the approval setting as I can't guarantee I'll be prompt in approving them."
