### ISSUE TITLE
purchasing quest scrolls / bundles should have confirmation popup

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11244]
Quest scroll purchases don't have a confirmation step.

When you buy other gem-purchasable items such as hatching potions, you see a confirmation dialog that tells you how many gems the total purchase will be and asks you to confirm:
![image](https://user-images.githubusercontent.com/1495809/60383487-c4ea7000-9ab4-11e9-9478-8e889eb7e68a.png)

The same thing should happen when you buy quest scrolls or quest scroll bundles.

**Comment by domtriola** [comment]
I would like to give this one a shot if I may?

**Comment by domtriola** [comment]
And one question: some quest items have a currency of Gold instead of Gems. Should those trigger a confirmation dialog as well?

**Comment by Alys** [comment]
@domtriola Thanks! Please go ahead.

For the gold-purchasable quests, my feeling is that having the same confirmation step is probably best for consistency, and because it's annoying to own quest scrolls that you don't want (unnecessary clutter).
It's not as important though since accidentally-spent Gold can be replenished using [Fix Character Values](http://habitica.fandom.com/wiki/Fix_Character_Values) (although of course not all players know that). If the staff say that gold purchases shouldn't have a confirmation step, believe them not me. :)
