### ISSUE TITLE
still level 1

### ISSUE THREAD

**Issue by titouwan** [HabitRPG/habitica#1124]
Hello!

I was level 2 and I gain acces to the sword and other stuff to buy.
But yesterday evening, I was back to level 1.
I can still buy rewards like armor or potion.

username is "titouwan"

**Comment by Shaners** [comment]
Go to Settings > Danger Zone: Restore and you'll be able to get back sword / gold / exp that you lost.

**Comment by titouwan** [comment]
thx a lot

**Comment by lefnire** [comment]
this is due to multiple computer access, or site unavailability because of mem leak - which are tickets of their own, so closing this
