### ISSUE TITLE
deleted challenge task should disappear immediately

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11245]
As @cTheDragons reports:

When deleting a task in a challenge in the web; click the three dots on task and choose delete; The tasks does not disappear although it has been deleted. You need to refresh the page to see the task has been deleted.

**Comment by kogelnikp** [comment]
@Alys I can take a look at this one.

**Comment by Alys** [comment]
@kogelnikp Thanks! I've marked it as in progress for you.
