### ISSUE TITLE
Challenges UI layout/formatting on My / Discover pages can be wrong; Username needed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11259]
The screenshots below show some examples of Challenges on the My Challenges and Discover Challenges pages where the formatting isn't quite right (e.g., categories overwriting the Guild name, inconsistent wrapping of the Created By line).

The layout issues might be related to some or all of these factors:
- creator name longer than average
- creator name longer than average AND the challenge is hosted in a guild (as opposed to being a "public challenge" with no guild name shown)
- size of gem prize 
- length of title
- other things?

Also the Created By line should probably contain the Username as well as or instead of the Display Name. Display Names can change often and it can be difficult to use them to recognise a player.
If it was only the Username, any issues with player name length would then probably disappear.

In addition to that, it might be worth considering changing the label "Created By" to something like "Owned By" or "Challenge Owner" or "Challenge Leader" for accuracy in all cases. It's not too uncommon for a challenge to be moved by an admin from the person who created it to another person who will then run the challenge, or for a challenge created by one person to be directly copied by another (I've seen this done with the creator's approval). In those cases "Created By" isn't accurate and it gives the credit for the imagination and hard work of thinking up the tasks to the wrong person. Using a different label would avoid that problem, while still making it clear who's currently responsible for the challenge.

I'm marking this as "on hold - needs design" in case @Tressley wants to make any design-related comments or point to an existing layout design that mightn't have been implemented as desired for all cases.

![1](https://user-images.githubusercontent.com/1495809/60875117-9589ef00-a27c-11e9-8679-e5b5a2cd7202.png)

![image](https://user-images.githubusercontent.com/1495809/60875188-b0f4fa00-a27c-11e9-893a-b4bf895b49d9.png)

![image](https://user-images.githubusercontent.com/1495809/60875242-c5d18d80-a27c-11e9-9993-2d9b33f46f9a.png)

Thanks to @ieahleen and @citrusella for reporting the layout issues.

**Comment by Tressley** [comment]
Going to loop @negue in as he was the last one to touch the Challenges styles.

**Comment by Alys** [comment]
See also https://github.com/HabitRPG/habitica/issues/11500 for the specific case of the Guild name being hidden by tags. It's been marked with the 'sprint' label for a fix to be done by a group of coders doing a November sprint, so while that issue is open, no one should try to fix the Guild name / label problem as part of this issue. 
If that other issue ends up being closed with a fix, I'll update this issue to remove mention of that specific problem.

**Comment by ShupingHe** [comment]
Can i take this once the design work settled?

**Comment by Alys** [comment]
@Stevens1995 It might be a while until the design is ready. Would you be interested in working on https://github.com/HabitRPG/habitica/issues/11500 right now? It's a similar problem. You'd be welcome to comment on that issue and start now if you wish!

**Comment by Alys** [comment]
When https://github.com/HabitRPG/habitica/pull/11620 ("fix challenge layout") is merged, we should check this issue to see if there are still any layout problems or if the problems described above have changed. I've marked that PR as "notify helpers" to remind me to follow up on this after it's merged.
EDIT: also when https://github.com/HabitRPG/habitica/issues/11500 is closed.

**Comment by Alys** [comment]
I'm closing this issue because the layout problems described here have been fixed in the PR linked above. If we notice any others we can open a new issue.
