### ISSUE TITLE
display `null` challenge prize as 0 gems

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11264]
As described at https://github.com/HabitRPG/habitica/issues/9745 it's possible for the gem prize for a challenge to be null which results in the prize box on the challenge having a blank space where the number of gems should be, as shown in the screenshot below.

As I mentioned in [one of my comments there](https://github.com/HabitRPG/habitica/issues/9745#issuecomment-508986367) a `null` prize doesn't seem to cause any problems apart from that display glitch, so this issue is to have **the website's front-end code modified so that when the prize is `null`, the number `0` is shown in the prize box**.

![screenshot_2017-12-26_19-56-52](https://user-images.githubusercontent.com/1495809/34363766-eb37fa24-ea76-11e7-8302-40a88e5bfea3.png)

_(https://github.com/HabitRPG/habitica/issues/9745 is being left open for a fix to the back-end code and a migration to correct all the affected challenges.)_

**Comment by kmacart** [comment]
I'll take the issue =)

**Comment by kmacart** [comment]
I've fixed it I think! Took me hours =|

**Comment by sanjayn2096** [comment]
Is this issue resolved? can I work on it?

**Comment by dl1683** [comment]
Is this open?

**Comment by Alys** [comment]
@kmacart has been looking into this so I'm marking it as in progress for them.

@kmacart Would you like to submit a pull request for the fix? So far it's just in a commit in your clone of the repo and it's easier for us to review and comment on it if there's a PR. :)

**Comment by akmaekki** [comment]
Hi, is this issue still open? I would like to work on it.

**Comment by paglias** [comment]
@akmaekki for now someone is still working on it but if we don't get an answer in a couple of weeks it'll be made available again

**Comment by akmaekki** [comment]
Ok, thank you for your answer. Just one more question. Is there another
possibility to contribute? Like reviewing pull requests, or something code
related?

**Comment by paglias** [comment]
@akmaekki reviewing pull requests is done by the staff usually but there are a lot of issues to work on if you want to ! Just pick any that doesn't have an `in progress` or `on hold` ticket and comment that you want to work on it

**Comment by evelynstender** [comment]
Hi! Is this still open? I'd like to work on this!

**Comment by paglias** [comment]
The server side change is done but missing the migration, the client side one is still missing, see https://github.com/HabitRPG/habitica/pull/11267#issuecomment-511350354
