### ISSUE TITLE
Notification settings page formatting is badly spaced

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11260]
Reported by ieahleen:

> User Icon -> Settings -> Notifications
> 
> The options to chose from are not easy to match with the corrisponding checkbox with just a glance, they are too near each other, the last few above everything: 
> 
> ![image](https://user-images.githubusercontent.com/8144640/61051552-31cd0680-a3e1-11e9-86fc-e6c2b9a330e1.png)

Confirmed on Windows 10/Google Chrome.

**Comment by Chinmaygoyal** [comment]
Can I go for it?

**Comment by paglias** [comment]
sure @Chinmaygoyal ! let us know if you have any issue

**Comment by martineizayaga** [comment]
Would it be ok if I took this?

**Comment by paglias** [comment]
@martineizayaga I'd say yes but let's first see if @Tressley has a design ready for it

**Comment by martineizayaga** [comment]
@paglias @Tressley any update on this? I'd love to start :)

**Comment by paglias** [comment]
@martineizayaga sorry about this, but after some internal talk we've decided to put this issue on hold while a bigger rethinking of the settings gets underway

**Comment by veeeeeee** [comment]
This has been fixed on prod for Notification settings.
