### ISSUE TITLE
no notification appears when gaining quest scrolls at levels 15, 30, 40, 60

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11266]
When you level up to levels 15, 30, 40, and 60, you do receive a quest scroll as expected (atom1, vice1, goldenknight1, and moonstone1) but you don't get any kind of notification that you received it. There used to be a modal; I'm not sure when it stopped happening.

I'm assuming it's a bug not a feature change since telling the players they've been given something for free is likely to be good for retention, but if the notification was deliberately removed, staff can close this of course. :)

I've marked it as "on hold - needs design" for a decision about how the notification should be shown (e.g.., modal, growl, notification in the menu down-down).

_Thanks to SheWhoKnits for reporting this._

When a decision has been made about what changes might or might not be needed for this issue, we should consider if anything needs to be done for https://github.com/HabitRPG/habitica/issues/11265 and either take it off hold or close it.

**Comment by Alys** [comment]
When a decision has been made about what changes might or might not be needed for this issue, we should consider if anything needs to be done for https://github.com/HabitRPG/habitica/issues/11265 and either take it off hold or close it.

**Comment by Tressley** [comment]
Designs are completed and in Zeplin. https://zpl.io/2p96pGr

_EDIT: Updated Zeplin link._

**Comment by benkelaar** [comment]
Can I pick this one up? I think I still need to be added to the Zeplin project, user benkelaar.

**Comment by Alys** [comment]
@benkelaar Thanks! I've marked this as in progress for you.

I believe the Zeplin access needs us to use your email address, but we can use the email address in your Habitica account if you wish - just let us know if that's the right one, no need to post it here.

Alternatively, you can give us a different email address if you wish, either here or by email to admin@habitica.com if you want to keep it private.

**Comment by benkelaar** [comment]
@Alys Indeed, that's the right one! Thanks!

**Comment by benkelaar** [comment]
@paglias I noticed your comment showing it won't show the levelUp modal on from the RYA modal. What's the RYA modal? Raise Your Attributes?

**Comment by SabreCat** [comment]
@benkelaar: That's "Record Yesterday's Activity"--the modal that lets you check off Dailies due on the previous day, before your start-of-day processing (the `cron` function) runs.

**Comment by benkelaar** [comment]
Ah, clear, that's the "yesterdaily" modal right?

**Comment by SabreCat** [comment]
Correct. "Yesterdaily" is the internal or casual dev term; "Record Yesterday's Activity" is the official name!

**Comment by benkelaar** [comment]
Ready for review
