### ISSUE TITLE
Level up modal (popup) doesn't always appear

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11265]
@shewhoknits (e1d43f13-4a7b-4188-8844-127b4f63c67c) reports:

**Sometimes I don't get the "Level up" popup although the notification bubble on the right side shows it. By now I'm pretty sure it happens on levels 15, 30, 40 and 60 when we get an unlockable quest.**
**If I'm right, it's just a minor bug, but I thought I'd tell here anyway.**

I haven't verified this myself but I'll do some tests in the next couple of days to see if I can confirm it. I'll also look through the code to check that it's not actually a deliberate feature, for example to prevent getting too many modals at once.

**Comment by Alys** [comment]
I've done several tests and I always saw level up modals except at levels 30, 40, and 60 (I did see a modal at level 15).

**Comment by Alys** [comment]
It looks like this is deliberate to prevent too many modals appearing when a quest scroll is given on level-up: 
This is the code that prevents the level-up modal appearing when `user._tmp.drop.type` has the value `Quest`:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/client/components/notifications.vue#L452-L457

and this is the code that sets `Quest` into `user._tmp.drop.type` when you reach a level that gives a quest scroll:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/fns/updateStats.js#L81-L109

However the quest scroll modal doesn't actually appear at those levels due to https://github.com/HabitRPG/habitica/issues/11266
I'm going to put this issue on hold until a decision has been made about https://github.com/HabitRPG/habitica/issues/11266 because if it's decided that there should NOT be a modal when a quest scroll is given, then we can remove the code that suppresses the level-up modal.

**Comment by paglias** [comment]
Looks like this is being fixed by #11389
