### ISSUE TITLE
'Support the Developers' reward not received

### ISSUE THREAD

**Issue by Etherfly** [HabitRPG/habitica#1126]
I registered on habitrpg.com and immediately purchased 20 gems to disable ads. It has been more than a week already, and neither the gems have come in, nor the ads have been disabled for me.
My user ID is 5fac22e8-3ee4-4a79-8d59-1635d242150a.

**Comment by lefnire** [comment]
ah, you did post to github after all! sorry doing some email catchup. you should be good now, thanks for the patience @Etherfly . re-open if still an issue
