### ISSUE TITLE
Group plan tasks are not sortable

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11268]
Tasks associated with a group plan do not seem to be sortable in your own personal task view (i.e. I am not referring to the group plan dashboard) even with all filters disabled. You can move them by clicking and dragging, but on sync they will pop back to where they started at the top of your list. This has been reported by someone using Firefox, and I just tested it now with Chrome. So far, I've only tested Dailies.

Both I and the person who reported it found that the button to send the task to top/bottom does work, though.

**Comment by Alys** [comment]
I've observed similar behaviour, although sometimes a reload is needed before the tasks jump back to the top. Might be related to https://github.com/HabitRPG/habitica/issues/11331

I've confirmed that tasksOrder bug (https://github.com/HabitRPG/habitica/issues/7645) is not responsible for the sorting problems I observe.

**Comment by Alys** [comment]
I've confirmed that tasksOrder bug (https://github.com/HabitRPG/habitica/issues/7645) is not responsible for the sorting problems I observe.

**Comment by Xaz16** [comment]
Hi folks!
I have strange feeling that when this PR will be merged this one will be resolved. 
https://github.com/HabitRPG/habitica/pull/11348

**Comment by Alys** [comment]
@Xaz16 Thanks for mentioning that! I'll put this on hold for now.
I'm also marking it as "notify helpers" so I'll see it when I do my regular sweep of that label and that will prompt me to test it again later. :)

EDIT 2019-10-23: it's fixed
