### ISSUE TITLE
Orb of Rebirth doesn't always adjust displayed stats (sync needed to see change)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11279]
@osberend (bc630499-2941-4c1b-85ed-41fed2e8959e) has reported the problem below with the Orb of Rebirth on the website. This conversation took place over a couple of weeks and involved osberend using the Orb twice.

osberend: **"Just now I used the Orb of Rebirth for the 30th time, at level 79. The pop-up then stated that this was my 29th rebirth and the highest level at which I had used it was 78. However, now, having refreshed afterward, my achievements page correctly reports that I have used it 30 times, with the highest being at level 78. So the actual updating is working correctly, but the pop-up has an apparent off-by-one error."**

alys: "I can't replicate it on the website (was this on the website for you?). I put a test account through three rebirths at increasing levels and both numbers in the pop-up modal were correct each time. I'm hoping what you experienced was a once-off glitch. The next time you rebirth, if you happen to remember this, can you take a screenshot of the achievement before rebirth, then a screenshot of the rebirth pop-up, then a screenshot of the achievement after rebirth? You can upload them to any image or file sharing site and paste the links here. Snag.gy is an easy place to upload by just pasting if you don't have a preferred place."

osberend: **"Yes the rebirth problem was on the website, specifically in Firefox (ESR? I can check, along with the exact version) on Debian. Possibly relevant: I leveled my final level with Burst of Flames XP, and did not complete any tasks between then and Orbing."**

alys: "Hmmm. I still can't replicate the problem even with leveling up from Burst of Flames and using the Orb immediately. I definitely want to hear if it happens to you again!"

osberend: **"I just orbed again, and the same thing happened.**

**"Level 80, with 'Began 30 New Adventures': 'Used an Orb of Rebirth to start over after attaining Level 79.' Last gain of XP that caused me to level up was from Burst of Flames (used on Desktop, not in an app). I am not sure whether I manually synced after leveling, but I definitely did some things that triggered auto-syncs (e.g., buying gems). I did not complete any further tasks or uses any further skills.**

**"I Orbed (on Desktop), and received the message (copy-and-pasted) 'You've begun a new adventure! This is Rebirth 30 for you, and the highest Level you've attained is 79. To stack this Achievement, begin your next new adventure when you've reached an even higher Level!'**

**"After clicking the 'Huzzah!' button, I continued to see myself described as a level 80 Mage. (Unfortunately, I did not think to click the Achievements link right at that moment, before manually syncing; perhaps I will remember to do this next time I orb, if this bug has not been figured out by then). I then clicked the manual sync button, and saw that I was now described as a level 1 Warrior. I then clicked on the Achievements link, and it correctly stated that I have achieved rebirth 31 times, with a highest level attained of 80."**

alys: "can you confirm that when you use the Orb, the sequence of events is precisely as I've listed below? If you can't remember exactly, that's okay, just let us know if anything in the list doesn't seem to match what you remember.
1. You click on the Orb of Rebirth in the Market (or in your Rewards column if you have it pinned).
2. You click on 'Buy Now'.
3. You click 'ok' on the confirmation pop up (the one that says 'Purchase for 6 Gems').
4. The website reloads automatically. This part is important! If you're not seeing a reload at exactly this point, please tell me!
5. When the website has finished reloading, the Achievement modal is shown to you.
6. You click the 'Huzzah!' button.
7. The modal disappears."

osberend: **"That sequence of events is correct. I can't 100% guarantee that there aren't any others that came in between (though I don't remember any), but all of those events did happen, and in that order. I also can't guarantee the nature of the reload, but it was definitely more than just a sync. (It might be informative to clear my cache and then reload the site after the modal pops up, but before clicking the 'Huzzah' button, and see if that affects what happens.)**

**"Also perhaps worth re-iterating: Despite there being that reload, my class and level continued to display as Mage 80 after clicking Huzzah, until I hit the manual sync button. There was not an automatic reload after clicking Huzzah, only the one prior to the modal popping up. I do not know whether these phenomena are normal or not; I mention them in case they aren't.**

**"At this point, (now that I am aware of it) the continued existence of this bug is a fairly modest inconvenience for me personally, but it was alarming when it first happened. And it seems unlikely that it is unique to my account."**

**Comment by shanaqui** [comment]
Update from osberend:

> osberend   @osberend (bc630499-2941-4c1b-85ed-41fed2e8959e) [android] 
> Update: I just orbed "prematurely" (at too low a level to stack the achievement) because I am starting a new job today. The Huzzah message displayed the (in this case correct) unchanged number of rebirths and max level achieved. So there is no bug in this case (unless your count my stats bars continuing to show me as a level 50 mage after I clicked "Huzzah," until I got the sync button; that did happen in this case as in others).
> 
> I mention this because it is evidence that the bug in other cases is, mechanically, a display of the old number of rebirths and max level achieved (instead of the updated values for each), not a display of the number of rebirths minus 1 and max level minus 1. The former was (in my opinion) far more likely than the latter anyway, but confirmation of such things can be useful, in my experience.
> 
> I will update again when I orb next, stacking the achievement, most likely somewhere between 1 and 2 weeks from now.

**Comment by Alys** [comment]
Another instance of this has been reported by @johnjsal (624e48a3-cbea-4bbe-ae44-ca9183f49626):

**"I rebirthed for my second time just now, but the pop-up dialog box said "This is Rebirth 1...". The achievement has stacked correctly, so it may just be an error with the dialog text."**

**Comment by veeeeeee** [comment]
Removing this from help wanted for now as this is likely to be impacted by upcoming reconsideration of how Orb of Rebirth should work relative to other resetting mechanics. See https://github.com/HabitRPG/habitica/issues/10918#issuecomment-689004163
