### ISSUE TITLE
Orb of Rebirth copy in profile indicates it is available for free even if it isn't

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11278]
![image](https://user-images.githubusercontent.com/8144640/61673352-0bfc0780-ace7-11e9-8c0a-639485efd519.png)

This text is the same even if the Orb is not currently available for free (due to the 45 day limitation). 

Reported by @Sananab (2d83aab3-7a37-43b0-9ad5-6572df95c2d4, partially confirmed by me (I didn't go as far as triggering Rebirth and then setting myself to 100 again).

**Comment by Alys** [comment]
I suggest we change that string to simply remove "now available for free in the Market" but I'm not marking it as help wanted yet in case the staff have preferred text or want to fix it themselves.

```
character.json:107:  "noMoreAllocate":
"Now that you've hit level 100, you won't gain any more Stat Points. You can continue leveling up, or start a new adventure at level 1 by using the <a href='http://habitica.fandom.com/wiki/Orb_of_Rebirth' target='_blank'>Orb of Rebirth</a>, now available for free in the Market.",
```
