### ISSUE TITLE
Habit minus streak being ludicrously negative

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11276]
@Rizz557 (d8fc75a7-6756-45bd-a12d-e0448316a31c) reported roughly a day before the time of this post that the counter on one of their Habits was incorrect - a huge negative number:

![image](https://user-images.githubusercontent.com/1495809/61574212-9b46c680-aaff-11e9-94af-db0ccc7140ba.png)

They've since reset the number. It was the Habit sorted to the top of the list, although I'm not sure that would make a difference.

I can't see anything in Loggly or the task's history that could explain it.

I'm logging this so that we have it on record but since it might be just a weird once-off glitch, it might not be worth investigating unless we see another report of it.

Task ID 7e20c204-e605-46f3-8f29-cd33f7a78fc8, not associated with a Challenge or Group Plan.

**Comment by Alys** [comment]
Task ID 7e20c204-e605-46f3-8f29-cd33f7a78fc8, not associated with a Challenge or Group Plan.

**Comment by SabreCat** [comment]
Closing for now, we'll see if it shows up again!
