### ISSUE TITLE
public guilds not always visible, sometimes requires refresh

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1127]
still haven't figured out what causes it. strange that `model.get('_publicGroups')` will show the guilds, so they're definitely fetched, and definitely before page render. Seems that section of the page (nested in the tab content) isn't reached for some reason

**Comment by switz** [comment]
without looking at the code: perhaps the templates are not live bound, so on render the content hasn't been fetched yet.

**Comment by lefnire** [comment]
Templates are live (double checked), fetch done serverside and render is a
nested callback after model.set('_publicGroups',publicGroups.get())... so
it should be rendered into the template server-side

**Comment by switz** [comment]
Wanna hangout and show me the issue?

**Comment by lefnire** [comment]
looks like this was the fix... https://github.com/lefnire/habitrpg/commit/7c829afb0957db870d9dc5d0c9987247a25210d2

**Comment by lefnire** [comment]
thanks for chiming in though duder!
