### ISSUE TITLE
Saddles should not be sellable using the API

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11280]
On the website, if you try to sell a Saddle, you're prevented from doing so and you see the message "Hey! This is a pretty useful item! Are you familiar with how to use a Saddle with your Pets?" (that's the locales string `foodSaddleSellWarningNote`). This was implemented because people were selling the Saddle by accident. It was based on the assumption that no one will ever want to sell a Saddle, which I think is still a correct assumption since Saddles are a very rare prize.

However the code to prevent selling it is only in the website's front end, which means you can still sell it using the API, and therefore using the mobile apps too (one person reported today that they sold a Saddle by accident on the app).

If the API prevents selling Saddles, then it won't be possible to do so on the apps. A user who tried to might see an ugly error message but I think that will be an improvement over accidentally losing a Saddle. The apps could be adjusted later as a lower priority to give better feedback when trying to sell.

~I'll leave this issue as suggestion-discussion for a few days in case the staff disagree but then if there's no objections I'll mark it as help wanted.~

This is the website code that prevents selling:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/client/components/shops/market/sellModal.vue#L24-L26

It uses the `sellWarningNote` parameter in the Saddle's `content` data, which should already be available through the API:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/content/index.js#L484-L492

The API route for selling is [/api/v3/user/sell/:type/:key](https://habitica.com/apidoc/#api-User-UserSell), which is defined here:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/server/controllers/api-v3/user.js#L1238
although this function is probably the best place to make this change:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/ops/sell.js#L15-L54

Note that a Saddle is defined as `food`, which is included in the `ACCEPTEDTYPES` constant (referred to in the above code and defined in the code below), so that's why it's currently sellable. We don't want to stop treating it as food because that would involve too many changes, some of them breaking changes.
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/ops/sell.js#L13

**Comment by gpalsingh** [comment]
Hi, I looked into the issue and would like to work on it.

Would a solution like this be acceptable?
```
if (key === 'Saddle') { 
  throw new NotAuthorized(i18n.t('itemNotSellable', req.language)); 
}
```
Since `Saddle` is the only item with a `sellWarningNote` it just checks the item name.
About the error message, should I add a special string for this case or reuse existing message? and which one in that case?

**Comment by Alys** [comment]
@gpalsingh Thanks for wanting to work on this! 

It would be best if the `if` statement in the API matched the one in the website's Vue code (that's the first code block above). That way if we ever change any related code, there's more chance that the same fix can be made in both places, and if we ever add another non-sellable item, the API will automatically prevent selling. Post here if you have questions.

I've marked this as in progress for you but let us know if you're not still interested in working on it. :)
