### ISSUE TITLE
404 not-found error page should point to Report a Bug guild

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11284]
As reported by @passocurto, the "Contact Us" link on the 404 error page https://habitica.com/static/not-found currently points to the Habitica Help guild (guild ID 5481ccf3-5d2d-48a9-a871-70a7380cee5a).

It should point to the Report a Bug guild (guild ID a29da26b-37de-4a71-b0c6-48e72a900dac).

_Note that you have to be logged in to Habitica to see the Contact Us link pointing to a guild. When you're not logged in, it points to the Contact Us page, which is the correct behaviour for that situation._

**Comment by lancewl** [comment]
Hi, I would like to try on this issue!!

**Comment by Alys** [comment]
@lancewl Thanks! I've marked it as in progress for you.

**Comment by lancewl** [comment]
>@lancewl Thanks! I've marked it as in progress for you.

@Alys Thanks! I think I just solve the issue with the pr, but I’m not 100% sure I did it in the right way.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adriancerejo** [comment]
Hey I know someone else already posted however could I try to fix this issue?
