### ISSUE TITLE
Antidotes to Avatar Transformation Items should be added to Rewards by API

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11289]
When you've been affected by one of the avatar [Transformation Items](https://habitica.fandom.com/wiki/Transformation_Items) (e.g., Spooky Sparkles), your Rewards column contains an antidote (e.g., Opaque Potion). Currently the antidote is inserted into your Rewards column by client-side code, so it's visible only on the website.

This should be changed so that the API inserts the antidote into a player's Rewards whenever they are affected by a Transformation Item. 
_(This will allow the antidote to appear in the mobile apps with little or no app-specific code being needed. Modifying the apps is not in scope for this issue)._

To find all the current website code for the antidote, use `git grep opaquePotion` (the other antidotes could also be searched for but their code will be in the same place as the Opaque Potion's code).

_(After the fix for this has gone live, we should check to see if the potion appears automatically on the mobile apps, and if not log issues to have that investigated.)_

**Comment by Xaz16** [comment]
Hi folks!
@Alys, can I take this one?

**Comment by Alys** [comment]
@Xaz16 Yes, thank you!

**Comment by Xaz16** [comment]
Ok, it is not so easy to understand how to make test data for that issue.
@Alys, may you help please?
How can I add transformation item for my local user? Or maybe it is better to understand how to start seasonal event on local machine...

**Comment by Xaz16** [comment]
It looks like I understand the magic @Alys. Sorry for disturbing :)

**Comment by Xaz16** [comment]
I made PR for this issue, but the solution is minimal as I can implement.
You can check it here https://github.com/HabitRPG/habitica/pull/11353
