### ISSUE TITLE
"Helped Habit Grow" Badge failed to appear after survey.

### ISSUE THREAD

**Issue by Elkian** [HabitRPG/habitica#1129]
Exactly what it says - despite filling and submitting the survey, no badge shows up.

User ID: 268b7375-3ede-4048-b687-c204a78580bd

**Comment by lefnire** [comment]
how about now

**Comment by Elkian** [comment]
Yeah, now it's fixed, thanks!

**Comment by traceyourshadows** [comment]
I've received no badge either. My user ID is 1ea4d0dc-6455-4f62-83ee-2a8b39c309bc.

EDIT: I received no gems, either.

**Comment by fawques** [comment]
Me neither. user-id: 20a7ce0f-5c50-4b01-bcec-36e9dab0d3b1

**Comment by BlackEdder** [comment]
For me neither the badge nor the gems appeared.
user-id: 62cf3b41-a297-4dd9-aa2d-2d1e051abbde

**Comment by freakizoid82** [comment]
Same here, no gems or the badge.
User-ID: d5d838a6-d4e7-4c32-8924-8c04a00d8f1b

**Comment by lefnire** [comment]
can y'all check now?

**Comment by fawques** [comment]
There it is, thanks! :)

**Comment by lefnire** [comment]
closing - the script just showed as having finished, so everyone should have their badges now. if anyone doesn't, post your uuid here and i'll apply manually

**Comment by freakizoid82** [comment]
Got it! Thank you!

**Comment by traceyourshadows** [comment]
I got it too! Thanks much.
