### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mclois** [HabitRPG/habitica#113]
I've discovered this app the day before yesterday, and I really like it, good job an great idea :).

Something has broken today. Six hours ago it was working (no offline problem, everything OK), but since a couple hours ago, all I get is a "Internal Server Error" message.

![habitrpg - Internal Server Error](https://f.cloud.github.com/assets/944362/78258/e633cf46-6176-11e2-875a-9b0b9a9df048.png)

**Comment by lefnire** [comment]
on it

**Comment by racuna** [comment]
if it helps, i just get this:

502 Bad Gateway
nginx/1.2.6

**Comment by lefnire** [comment]
That means server went down. i'm using [forever](https://github.com/nodejitsu/forever) to restart every time there's a crash, which is being caused by #80. Diagnosing

**Comment by lefnire** [comment]
actually, let's follow up on #84. sounds different, but same issue.
