### ISSUE TITLE
Uncaught TypeError: Cannot set property 'guilds' of undefined

### ISSUE THREAD

**Issue by motoyugota** [HabitRPG/habitica#1130]
Isn't working at all right now - beta or live site. Getting the above error message every time as well as getting the following at times too:

GET https://beta.habitrpg.com/socket.io/1/?clientId=e4db8497-3189-4435-9688-858658eff16e&t=1370311211116 502 (Bad Gateway)

**Comment by lefnire** [comment]
that should fix the issue, check again in about 5m and if still problem re-open
