### ISSUE TITLE
All titles/dates set to <username>

### ISSUE THREAD

**Issue by cybrex** [HabitRPG/habitica#1132]
All titles and due date values were set to my username.

I was using iOS 6.1.3 over a slow-ish 3G connection at the time. I've seen the titles get "stuck" with my username before, but I either just needed to wait a little longer and everything would populate with the correct text values or reload the page to fix everything.

After several minutes of waiting and a few reloads, I decided to give up until I got into work. When I logged into HabitRPG at work, all of my tasks, dailies, todos (including completed todos) and custom reward titles were set to my username (Argo). All of the metadata (difficulty, tags, days of the week, etc) was correct, with the exception of due dates. Due dates had also been set to "Argo".

I broke it good. kthxbai

Hit me up at brycew331atGmaildotCom if you need more deets.

**Comment by lefnire** [comment]
never seen this before :o only thing i can do is restore you to yesterday, or whichever day was working for you

**Comment by cybrex** [comment]
Yay! That means I did a good job... with the borking.

No worries. Stuff happens. I didn't have anything super-critical that I was
trying to keep track of. Although, if you could set me back to the most
recent backup before 7:00am this morning (-6:00 GMT/CDT), that'd be
super-nifty.

Keep up the great work!

## Regards,

Bruce

On Jun 4, 2013, at 12:48 PM, Tyler Renelle notifications@github.com wrote:

never seen this before :o only thing i can do is restore you to yesterday,
or whichever day was working for you

—
Reply to this email directly or view it on
GitHubhttps://github.com/lefnire/habitrpg/issues/1132#issuecomment-18926511
.

**Comment by lefnire** [comment]
ok, restored you. 

Come to think of it - I do remember seeing this about a year ago! possibly even back when habit was still on Rails. It was due to some "remember password" or "remember username" browser extension, can't remember what though

**Comment by cybrex** [comment]
Sweet! The only password manager that I ever use is 1Password. It has a browser extension... but not on iOS. Ring any bells?

**Comment by lefnire** [comment]
hmm... that might have been it, but if this triggered on your iPhone that
definitely wouldn't be the case. Restore look ok? Let's close this ticket
and keep an eye on it if so. sorry about that

**Comment by cybrex** [comment]
Like I said, no worries! And I'll let ya know about the restore shortly. Having trouble loading the site at the moment. I'll keep ya posted if it happens again.

**Comment by cybrex** [comment]
Restore looks good. I'll close this and let you know if something like this happens again.

**Comment by cybrex** [comment]
Ooops. The restore removed my "Helped Habit Grow" Achievement. -_-'  At your leisure...

**Comment by lefnire** [comment]
ah yes! done
