### ISSUE TITLE
Policy links on FAQ page don't work

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11326]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
From the Bug Guild:

@JosephK (221859e5-5d04-4753-9577-e0f4ca918b8c): "Hey - on the Habitica [FAQ page](https://habitica.com/static/faq), "Privacy Policy" and "Terms and Conditions" don't seem to have links. The other footer links work for me on the FAQ page, and those links work for me on other pages. (I'm using Chrome from a PC). Thanks!"

**Comment by SebastiaanNijland** [comment]
Seems to be an issue with the background being on top, I can take a look!
