### ISSUE TITLE
sorting Group Plan tasks in personal task list produces error "Not authorized to manage tasks"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11331]
After I have claimed tasks from a Group Plan, why I look at my personal task list and try to sort the tasks there, I see a red notification error message saying "Not authorized to manage tasks!" -- i.e., this message:

`groups.json:  "onlyGroupLeaderCanEditTasks": "Not authorized to manage tasks!"`

At the same time, the error below appears in the console.

```
Error: "Request failed with status code 401"                         vue.runtime.esm.js:1888
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:59
    VueJS 4
        ut
        st
        ot
        at
    j es6.promise.js:75
    j es6.promise.js:92
    l 
```

This might be related to https://github.com/HabitRPG/habitica/issues/11268

**Comment by Alys** [comment]
Sorry, submitted that accidentally, here's the full details:

After I have claimed tasks from a Group Plan, why I look at my personal task list and try to sort the tasks there, I see a red notification error message saying "Not authorized to manage tasks!"

At the same time, the error from the top post appears in the console.

**Comment by Alys** [comment]
This might be related to https://github.com/HabitRPG/habitica/issues/11268

**Comment by Xaz16** [comment]
Hi folks!
@Alys can I take this one?
I already created group on my local (thanks that I worked with stripe before) :)

**Comment by Xaz16** [comment]
Could you show steps for reproduce as well? Due to I can't reproduce issue by myself...

**Comment by Scens** [comment]
> Could you show steps for reproduce as well? Due to I can't reproduce issue by myself...

1. Claim some group tasks as a non-leader of a group 
2. Try to rearrange them at your personal tasks list.

**Comment by Xaz16** [comment]
Thank you @Scens.
How can I accept invite on non leader user, without working emails? I tried through MongoDB (modify leader field with another user token), and I have no result. I'm not so strong in Mongo. Can you provide some queries for me?

**Comment by Alys** [comment]
@Xaz16 Yes, it would be great if you could work on this, thanks! I've marked it as in progress for you. 
Emails shouldn't be necessary for invitations. When a player is invited to a guild (with or without a group plan), they'll see the invitation in their notification menu so they can accept it from there. Does that answer your question? Post again if it doesn't. :)

@Scens Thank you!!

**Comment by Xaz16** [comment]
Yeah, @Alys. It answers, thank you. For some reason I totally forgot about this method of applying invitation.

I reproduced that case and start working on it.
