### ISSUE TITLE
API route to export avatar as PNG file, shows invalid UUID

### ISSUE THREAD

**Issue by atlas-comstock** [HabitRPG/habitica#11333]
API is : https://habitica.com/apidoc/#api-DataExport-ExportUserAvatarPng

For example, `curl  "https://habitica.com/export/avatar-:106c172a-7799-49a5-b108-ebb23bae8a64.png"` shows:

`{"success":false,"error":"BadRequest","message":"Invalid request parameters.","errors":[{"message":"\"member\" must be a valid UUID.","param":"memberId","value":":106c172a-7799-49a5-b108-ebb23bae8a64"}]}`

However,  `106c172a-7799-49a5-b108-ebb23bae8a64` is my user id:
https://habitica.com/profile/106c172a-7799-49a5-b108-ebb23bae8a64

And it can be validate in python as a UUID:
```
$ python
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uuid
>>> uuid.UUID('106c172a-7799-49a5-b108-ebb23bae8a64')
UUID('106c172a-7799-49a5-b108-ebb23bae8a64')
```

**Comment by atlas-comstock** [comment]
Dig into the code, seems that it is validated by `express-validator`.
So it may cause by this?

**Comment by paglias** [comment]
@YongHaoWu `curl "https://habitica.com/export/avatar-:106c172a-7799-49a5-b108-ebb23bae8a64.png"  ` inclused `:` in front of the uuid, if you remove it the error doesn't appear anymore although the route is still broken due to #9489
