### ISSUE TITLE
Stats, Achievement menu options link to Profile modal; Edit Avatar option is sometimes wrong

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11337]
Clicking on User Icon > Stats or User Icon > Achievement opens the Profile modal. You then have to click on the Stats or Achievement subheading to get to the screen you want.
The correct behaviour is that those two menu options should link directly to the Stats or Achievement modal.

~The User Icon > Edit Avatar menu option works correctly most of the time (i.e., it takes you to the avatar editing modal with the Body section open). However if you use the User Icon > Backgrounds menu option and then any time later you go to User Icon > Edit Avatar, you're taken to the Backgrounds screen again (I'm pretty sure this is new, incorrect behaviour). You have to reload to make User Icon > Edit Avatar direct you to the Body screen automatically.~ <- This has been fixed

**Comment by Scens** [comment]
Hi!
I've just checked and Stat and Achievement menu options work good in the most recent develop version.

**Comment by Alys** [comment]
@Scens Thanks for finding that and for the PR! I've marked this as in progress for you.

**Comment by paglias** [comment]
I've edited the description to say that a part of the issue has been resolved

**Comment by ResamVi** [comment]
I have tinkered with it to see if I could pin down the error and I seem to have fixed it for me. Is help still wanted on this issue?

**Comment by Alys** [comment]
@ResamVi Sure, thanks! I've marked it as in progress for you.
