### ISSUE TITLE
can't close challenges - participants can't be searched or viewed in drop-down

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11339]
Multiple reports of this.

When you're trying to close a challenge from the "End Challenge" button, the "Select Member" drop-down list is empty and the name search field there doesn't accept input (clicking in it doesn't put a cursor there and typing doesn't cause letters to appear).

Similarly, the "View Progress Of" drop-down doesn't accept input.

I'm marking this high priority since it's very disruptive to challenge owners in general and at this time specifically there's a lot of end-of-month challenges that need to be closed.

**Any contributor is welcome to take this on but please only do that if you're able to submit a fix in a couple of days ideally. Also be aware that the staff might fix this themselves so post here to check before starting to work in it.**

**Comment by Alys** [comment]
Any contributor is welcome to take this on but please only do that if you're able to submit a fix in a couple of days ideally. Also be aware that the staff might fix this themselves so post here to check before starting to work in it.

**Comment by cheng-shiqi** [comment]
Can I take on this one? I've work out a solution in my local install and will submit the PR immediately.
