### ISSUE TITLE
Orb of Rebirth should reset Habit streaks

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11334]
Reported via RaB by Eliot the New Recruit [tmto]   @EliotThe (0d77107e-9128-4656-8c02-6e06331fa396):

> The streaks on a couple of my Habits, which reset monthly, did not reset to 0 when I rebirthed a couple days ago. I don't really mind, although I assume they were supposed to. The Habits are not part of a challenge---although, they were part of a challenge which I left and kept the tasks from.

I have not tested this personally.

**Comment by Alys** [comment]
Confirmed. Rebirth currently resets the streaks on a Daily but not on a Habit. This screenshot shows tasks immediately after Rebirth occurred:

![image](https://user-images.githubusercontent.com/1495809/64155910-19c0b300-ce77-11e9-81f2-168daab97fc1.png)

The desired behaviour is that the positive and negative streaks on Habits should be reset to zero by Rebirth, in the same way that streaks on Dailies are. All exceptions that apply to Dailies should apply to Habits (e.g., the streaks for Habits from challenges should not be reset).

**Comment by Xaz16** [comment]
Hi folks! 
Can I take this one @Alys ?

**Comment by Alys** [comment]
@Xaz16 Sure, thanks! Post here if you have questions. :)

**Comment by Xaz16** [comment]
@Alys thank you.
I created PR with fix for this issue https://github.com/HabitRPG/habitica/pull/11345
