### ISSUE TITLE
Gender change from male to female (short to long hair) on guild creation

### ISSUE THREAD

**Issue by Shaners** [HabitRPG/habitica#1134]
When I created a guild my avatar settings went from short hair to long hair. Easily fixed on the profile segment. One other person in tavern chat mentioned that it happened to them as well.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
