### ISSUE TITLE
Skills Layout is a bit off

### ISSUE THREAD

**Issue by SebastiaanNijland** [HabitRPG/habitica#11356]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 2f3f22af-3abf-4236-bf9e-67ff88051df9
  * Browser: not browser specific
  * OS: not os specifc

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
As you can see in this screenshot, the text of the skills is aligned to the bottom, while it would be nicer to have it aligned in the center:

<img width="835" alt="skills" src="https://user-images.githubusercontent.com/19267753/64678393-c30c3800-d479-11e9-9e02-84ac2c0c88da.png">

On certain screen sizes, there are also issues with the text and the mana cost symbol overflowing, that could be fixed by using some flexbox styles to align it in the center:

<img width="382" alt="Screenshot 2019-09-11 at 09 53 58" src="https://user-images.githubusercontent.com/19267753/64678548-17afb300-d47a-11e9-902e-d35097ffc73b.png">

**Comment by SebastiaanNijland** [comment]
Note that I'd like to work on this myself if that's okay :)

**Comment by Alys** [comment]
This is something @Tressley might like to comment on so I've marked it with the design on hold label.

**Comment by Tressley** [comment]
@SebastiaanNijland -- Thanks for wanting to pick this up. I've made some revisions to the design and added them to our Zeplin project here: https://zpl.io/aMjPv5m

Please let me know if you have any questions.

**Comment by SebastiaanNijland** [comment]
Nice design, it looks awesome! I will take a look at it, hopefully I will find some time for it this week or next week!

**Comment by SabreCat** [comment]
@SebastiaanNijland Are you still planning to work this one? Let us know if you won't have a chance--we've got a volunteer sprint coming up that'll be eager to pick up stray issues.

**Comment by SebastiaanNijland** [comment]
I fear I won't get around to this at the moment, so that's fine with me!

**Comment by jaimeparrajr** [comment]
Hi, can I help with this item?

**Comment by Alys** [comment]
@jaimeparrajr Thank you, yes! Please go ahead and post here if you have questions.

**Comment by jaimeparrajr** [comment]
Thank you.  How can I get access to the new design?

**Comment by Alys** [comment]
@jaimeparrajr  Post your email address here and tag `@ Tressley` or if you'd prefer to not make your email address public, send an email to admin@habitica.com and include your GitHub username and this issue's URL.

**Comment by Tressley** [comment]
Invite sent @jaimeparrajr!

**Comment by shanaqui** [comment]
@jaimeparrajr Hi there! Are you still interested in working on this one? Let us know!

**Comment by shanaqui** [comment]
@jaimeparrajr I've marked this as help wanted again for now, but if you do want to pick it up again, let us know!

**Comment by dabrowskif** [comment]
Hi, I would like to participate in the Habitica and I chose this for my first bugfix. I've already sent a mail - you can invite me to Zeplin project, so I can look at a new design that was made by Tressley.

**Comment by Alys** [comment]
@dabrowskif Fantastic, thanks! I've marked this as in progress for you. I've found your email and passed on your email address to Tressley and the other staff.  :)

**Comment by Tressley** [comment]
Invite sent! Here's the Zeplin artboard to reference: https://zpl.io/aMjPv5m

**Comment by shanaqui** [comment]
@dabrowskif Hi! Are you still interested in working on this issue? If not, or if we don't hear from you within seven days, I'll mark this issue as "help wanted" again just to make sure it doesn't go stale!

**Comment by dabrowskif** [comment]
> @dabrowskif Hi! Are you still interested in working on this issue? If not, or if we don't hear from you within seven days, I'll mark this issue as "help wanted" again just to make sure it doesn't go stale!

Yes, ive got stuck at one moment and currently i don't have time to solve it, i hope ill move forward next week.

**Comment by shanaqui** [comment]
No worries! :) I'll leave this as in progress for you.

**Comment by shanaqui** [comment]
@dabrowskif Just checking in again to make sure this issue doesn't go stale! Are you still planning to work on this? If not, or we don't hear from you within a week, I'll mark it as help wanted again.

**Comment by SabreCat** [comment]
@paglias and I poked at this a little in the context of @JalanshMunshi's recent PR, but it's still proving thorny..

**Comment by shanaqui** [comment]
@dabrowskif Since I didn't hear back, I'm marking this as help wanted again. You can let us know if you want to pick it back up later, of course!

**Comment by raghavchugh21** [comment]
I'll work on this issue!

**Comment by Alys** [comment]
@raghavchugh21 Thanks! I've marked it as in progress for you. Post here if you have questions!

**Comment by Tressley** [comment]
Hi @raghavchugh21 -- Please provide an email address to receive a Zeplin invite. Zeplin is how the platform we use for design hand-off to contributors.

**Comment by raghavchugh21** [comment]
Here's my email - 18ucs195@lnmiit.ac.in

**Comment by raghavchugh21** [comment]
Starting my work on the issue, kindly share the acceptance tests.

**Comment by paglias** [comment]
@raghavchugh21 what do you mean by acceptance tests?

**Comment by raghavchugh21** [comment]
@Tressley @paglias  Can you point out your requirements from this issue once more?

**Comment by paglias** [comment]
The requirements are to change the Skills Layout to match the design that you can find here on Zeplin https://app.zeplin.io/project/59c16a1433075573feaa48fb/screen/5dadbe46c02f1e83270ec082

**Comment by raghavchugh21** [comment]
@paglias Great. Working on this right away!

**Comment by Tressley** [comment]
@raghavchugh21 -- Please take a look at #10618 as it overlaps with this issue.

**Comment by raghavchugh21** [comment]
thanks for letting me know! I'll include the fixes for both issues in my PR.

**Comment by raghavchugh21** [comment]
Also, could you help me with where do I find the Skills Layout designs in Zeplin.

**Comment by paglias** [comment]
@raghavchugh21 they're here https://app.zeplin.io/project/59c16a1433075573feaa48fb/screen/5dadbe46c02f1e83270ec082

**Comment by VipulKhandelwal1999** [comment]
Hi @Tressley @paglias  I have worked on this issue. I am able to come up with a solution and fixed at my local setup.

--> Screenshots Of Issues Right Now:-

Desktop View:-

![2020-09-14 (63)](https://user-images.githubusercontent.com/44499187/93115520-9668ad00-f6d9-11ea-942b-216c7e93e60e.png)

Ipad View:-

![2020-09-14 (64)](https://user-images.githubusercontent.com/44499187/93117129-fb250700-f6db-11ea-8627-5ec8fe7077a9.png)


--> Screenshots After I Have Fixed These Issues:-

Desktop View:-

![2020-09-14 (65)](https://user-images.githubusercontent.com/44499187/93115947-3e7e7600-f6da-11ea-9abc-6869606fc7b8.png)

Ipad View:-

![2020-09-14 (68)](https://user-images.githubusercontent.com/44499187/93116140-7eddf400-f6da-11ea-9562-2cb77d370c3e.png)

The reason why i think that this layout is perfect as per your layout it is not possible for text earthquake in skill card to get fit into the skill card just beside its logo as you can see below. If you will minimize your window a little bit the text will get overlapped with the div containing diamond as you can see below.

![2020-09-14 (70)](https://user-images.githubusercontent.com/44499187/93116674-38d56000-f6db-11ea-9fa7-1e871b88a050.png)

Please tell me what do you think if it's perfect then i will work on it and will send PR ASAP.

**Comment by Tressley** [comment]
Hey @raghavchugh21 -- I think you may have been confused about the scope of this issue. The new design for the Skills bar is what needs to be implemented, while accounting for the display issue outlined #10618. That's the Zeplin link @paglias provided above.

**Comment by VipulKhandelwal1999** [comment]
Hi @Tressley I am not @raghavchugh21 .Please give me access of your designs so that i can implement them ASAP.
My email id is khandelwal.vipul1605@gmail.com

**Comment by Tressley** [comment]
Hi @VipulKhandelwal1999 -- Thank you for your interest! This issue is currently being handled by @raghavchugh21. If @raghavchugh21 is unable to continue working on this issue, it will be open for you to claim.

**Comment by VipulKhandelwal1999** [comment]
Ok @Tressley .Thanks for your response.

**Comment by raghavchugh21** [comment]
I would like to hand over this issue to @VipulKhandelwal1999

**Comment by VipulKhandelwal1999** [comment]
Thanks @raghavchugh21

**Comment by VipulKhandelwal1999** [comment]
Hi @Tressley Please assign this issue to me and please provide me the access of your designs as well. My email id is khandelwal.vipul1605@gmail.com

**Comment by VipulKhandelwal1999** [comment]
Hi @Tressley @paglias .Please assign this issue to me and please provide me the access of your designs as well. My email id is khandelwal.vipul1605@gmail.com

**Comment by VipulKhandelwal1999** [comment]
Hi @Tressley @paglias .Please assign this issue to me and please provide me the access of your designs as well so that i can work on it ASAP. My email id is khandelwal.vipul1605@gmail.com

**Comment by shanaqui** [comment]
@VipulKhandelwal1999 Hi! Did you get everything and get chance to get started on this? I'm just checking in to make sure the issue doesn't go stale -- if you're not working on it anymore or you don't reply within a week, I'll mark it as Help Wanted again. :)

**Comment by shanaqui** [comment]
@VipulKhandelwal1999 Hi! Did you get everything and get chance to get started on this? I'm just checking in to make sure the issue doesn't go stale -- if you're not working on it anymore or you don't reply within a week, I'll mark it as Help Wanted again. :)

**Comment by VipulKhandelwal1999** [comment]
@shanaqui Hi! I am working on it. I have completed most part. Now i am just refactoring the code to avoid redundancy, etc.

Zeplin's Design Of Skill Section:-
![2020-10-06 (5)](https://user-images.githubusercontent.com/44499187/95190100-69954a80-07ec-11eb-89bf-2f2a20114cda.png)

This is the output of my code same as the mentioned in zeplin's design.
![2020-10-06 (6)](https://user-images.githubusercontent.com/44499187/95189708-d5c37e80-07eb-11eb-8ae0-3025260bd09b.png)

Close Snapshot of skills section:-

![2020-10-06 (9)](https://user-images.githubusercontent.com/44499187/95190496-0821ab80-07ed-11eb-971b-3867c21dbdd5.png)

**Comment by shanaqui** [comment]
Thanks for checking in!

**Comment by VipulKhandelwal1999** [comment]
@paglias i will work on this again while keeping in mind all the things which you have mentioned in the previous PR.

**Comment by VipulKhandelwal1999** [comment]
@paglias i am working so hard on this. I just wanna know few things because i am new to open source. What must be the size of the drawer containing all the skills. So basically i just wanna know that whether i have to keep same dimensions mention on Zeplin or i can change little bit. 
And how can we fix eslint errors.
Please help me out....

**Comment by Tressley** [comment]
@VipulKhandelwal1999 -- Zeplin contains the approved design specifications for implementation. Your goal should be to have implementation be as close to the design as possible. If there are questions you have about the design or how to achieve certain design pieces, feel free to ask.

**Comment by VipulKhandelwal1999** [comment]
@Tressley Thank you very much. Now i will be able to send you PR ASAP.

**Comment by paglias** [comment]
@VipulKhandelwal1999 the only thing I'd not implement from the zeplin design is the exact with of the drawer as it should get calculated automatically based on the items inside it. Also it's very difficult to work without seeing the code so my suggestion is to push the PR even if you can't fix some issues and we can work on it from there. The eslint errors usually have a description with what's wrong, but in this case as well it's very difficult to understand what's wrong without seeing the code

**Comment by VipulKhandelwal1999** [comment]
@paglias Thank You very much. Now, I have all my doubt resolved. Now i can work efficiently. Hope i could meet your expectations
