### ISSUE TITLE
can't remove guild/party/group members; members appear in member list twice

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11355]
@SuperSaraA (dbf5390d-6a57-42ad-ae14-af8fd8e570ca) reports problems removing members from a guild:

"So as a newish guild leader I have been trying to delete the members who are years unactive. Recently I have noticed that they are not moving off of my member list after I click the "yes remove" button. I am working on the website version. ... 
One other person commented in the [Habitica Help] guild that they had the same problem and no idea why it was happening to them either and another user told us both that the web version is the only way to remove people from a guild so if it doesn't work it would be something to mention in this [Report a Bug] guild.
I also noticed that as I was trying to delete people, sometimes they were on the guild list twice and when I tried to delete them a red error box would show up saying "user not found" but they would still be on the list (sometimes twice) even after refreshing the window."

**Comment by SunSparc** [comment]
I have noticed a similar behavior in the iOS app for a party that I am in. Members that have long since departed will continue to show up, sometimes for quite a while. I cannot remember seeing this in the website version though. If I can get some time, I will see if I and duplicate it locally.

**Comment by Alys** [comment]
@SunSparc Thanks! Let us know if you can duplicate it and want to work on it.

**Comment by SunSparc** [comment]
I have been running a local copy of the site for the past week. Created a guild, added and removed members, come back different days and did that again. I have been using multiple different browsers as well. So far I have not been able to duplicate it. I will keep playing with it a while longer. Sounds like a possible caching/syncing issue between the different services.

**Comment by SabreCat** [comment]
I think we'd need a current example of the issue to be able to follow up on this in any way. Closing for now, but if it occurs again and we can grab the affected data to see what's going on, we can reopen.

**Comment by SunSparc** [comment]
@SabreCat agreed. After trying to replicate it myself I have realized that there is just not enough information. But having the issue here is good so that if anyone else experiences the issue they can add their experience and maybe over time we can gather enough to be able to recreate and track it down. Or it may just be fixed as a result of a seemingly unrelated fix.
