### ISSUE TITLE
punctuation in wrong place in RTL text (Arabic, maybe others)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11364]
@sora-01 (30647f40-eeb7-4d3a-a52a-40491b3eab84) reports:

"Hi! I'm from the Pirate Cove. When I posted Arabic messages in a chat, I noticed periods at the end of a paragraph were displayed on the right like English. It's not the correct position, because periods are usually on the left in Arabic. The same problem happened to exclamation marks. This display problem happens on website and I'm using Google Chrome.
I don't really understand Arabic. I found this problem by chance, so I'm letting you know just to be sure. Thanks!"

(sora-01 was pasting Arabic text written by an Arabic speaker for the Pirate Cove guild (a guild that helps other guilds find new leaders and become more active).)

@citrusella added:

"The guild @sora-01 posted to appears to be [Arab Folks](https://habitica.com/groups/guild/6dd4603a-d4d0-4d20-be5b-955bfbb857ad). It seems all LTR text posted in a message done in RTL text could end up in a wrong place syntactually, and periods and exclamations are being treated as LTR text, I guess? (Question marks appear to be a different glyph in Arabic and thus unaffected.) I tried playing around with copying some text from [Arabic Wikipedia's Main Page's talk page](https://ar.wikipedia.org/wiki/%D9%86%D9%82%D8%A7%D8%B4:%D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9) to my party and Habitica treated the strings fairly differently where LTR characters of any kind were involved."

@sora-01 said:

"I posted those messages in my private guild and [Arab Folks](https://habitica.com/groups/guild/6dd4603a-d4d0-4d20-be5b-955bfbb857ad) as @citrusella says. To avoid confusion, I deleted periods at the end of a paragraph in the Arabic Hail for posting Arab Folks.  I also modified [Hails In Other Languages](https://habitica.fandom.com/wiki/The_Keep:Pirate_Cove/Hails_In_Other_Languages).  I tried to recreate the message in my private guild just now: https://snipboard.io/hB8jtd.jpg https://snipboard.io/3RN6DW.jpg _[images copied below]_

"I found a conversation like this in [Arabic Language Learners](https://habitica.com/groups/guild/245a5948-951a-496b-b595-a2c8d5558ad9) (one year ago): 'I did set up the Windows Arabic keyboard on my computer, but at least on Habitica it messes up the punctuation. I'm hoping that it's just Habitica that does that.' 
'Yeah that's a common problem I run into all the time. tbh it doesn't get better and it's always frustrating'"

![hB8jtd](https://user-images.githubusercontent.com/1495809/65039098-d1d07e80-d994-11e9-8797-56771cb1e6be.png)
![3RN6DW](https://user-images.githubusercontent.com/1495809/65039097-d1d07e80-d994-11e9-93ce-a24823c65895.png)

**Comment by Alys** [comment]
I've posted to both those guilds to ask if anyone has any more information or suggestions.

**Comment by mario130** [comment]
@Alys I think I can solve this issue, I've made an Arabic site before and have some experience using Vue, but I'm new to contributing and I need help locating the file first, thanks.

**Comment by mario130** [comment]
But it has to do with text aligning and input direction so I think it will be a little complex to check for change direction at every input

**Comment by Alys** [comment]
@mario130 Thank you! I"m marking this as in progress for you.

I'm not certain myself where this should be fixed, but if you do the Unix command below it will show you all *.vue files that have `chat` (case-insensitive) in their names, so one of those may be either the correct place to modify or will give you pointers to other related files (e.g., files that contain its name).

`find . -type f -iname \*chat\*vue`

But post again here if you need more help finding the right place to start, or if you run into any other trouble or have any questions! See [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) and the wiki pages it links to if you haven't already found them.

**Comment by Alys** [comment]
Sorry, this is the command:

`find . -type f -iname \*chat\*vue`

**Comment by mario130** [comment]
I followed all the steps in the setup guide and everything was fine with no errors until I entered `npm run mongo:dev` which caused the error in the image.
![error](https://lh3.googleusercontent.com/DPBLdCG8cdEBDWpOXQJPelNdr3GZlQB8uuJDIo5JjlxSX7LuPC-v1fYTV6gVafn3zI9naajNoudF0Q=w1366-h632)
I didn't use MongoDB before so I don't know how to fix it or if there's already a fix.

**Comment by paglias** [comment]
@mario130 looks like there was some issues with the screenshot you posted, can you try again?

**Comment by mario130** [comment]
@paglias that's the output
```
> habitica@4.161.4 mongo:dev /home/mario/Desktop/habitica
> run-rs -v 4.2.8 -l ubuntu1804 --keep --dbpath mongodb-data --number 1 --quiet

Skipping purge
Running '/home/mario/Desktop/habitica/node_modules/run-rs/4.2.8/mongod' [ 27017 ]
Restarting replica set...
undefined
```

**Comment by paglias** [comment]
@mario130 can you try to delete the `mongodb-data` folder and try again?

**Comment by mario130** [comment]
still the same error

**Comment by paglias** [comment]
Looks like there might be an issue with `run-rs@0.7.0`, let's try with the previous version: `npm i run-rs@0.6.2`

**Comment by paglias** [comment]
@mario130 I've downgrade run-rs to 0.6.2 which is working (https://github.com/HabitRPG/habitica/commit/1d8880c04d8bdbcccdb92361e76c683907103cfa)

You'll have to re-install it with `npm i run-rs@0.6.2`

**Comment by mario130** [comment]
@paglias that worked thanks, will see what I can do from here

**Comment by mario130** [comment]
got another error when using `npm run client:dev`
here's the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.161.4~prestart: habitica@4.161.4
6 info lifecycle habitica@4.161.4~start: habitica@4.161.4
7 verbose lifecycle habitica@4.161.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.161.4~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/mario/Desktop/habitica/node_modules/.bin:/home/mario/.local/bin:/home/mario/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle habitica@4.161.4~start: CWD: /home/mario/Desktop/habitica
10 silly lifecycle habitica@4.161.4~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle habitica@4.161.4~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.161.4~start: Failed to exec start script
13 verbose stack Error: habitica@4.161.4 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid habitica@4.161.4
15 verbose cwd /home/mario/Desktop/habitica
16 verbose Linux 5.4.0-45-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.161.4 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the habitica@4.161.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
I'm just not familiar with the backend part of this project yet

**Comment by mario130** [comment]
@paglias  so now the project is running as it should 
but first I need to get gems to create a guild to start working
how can I get them?

**Comment by mario130** [comment]
@paglias  
It's done!
![image](https://i.imgur.com/ays4tLr.png)
I've made a pull request  #12655
btw that was my first contribution to open source ^^

**Comment by paglias** [comment]
thanks @mario130 , I'll review it in the next few days
