### ISSUE TITLE
Add a warning when leaving a guild

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#1136]
Hi
I created a guild, and use the "leave" button to leave the menu ... so basically, I just left my newly created guild without any warning. As I was the only member, the guild doesn't exist anymore (and I lost my gems in the process)

Please add a warning when leaving the guild, specially if you're the creator of it 

By the way, would it be possible to have my gems back ? Or my guild, as I would re-use my  gems to re-create it ?

**Comment by lefnire** [comment]
goodness! Sorry about that, fixed in https://github.com/lefnire/habitrpg/commit/6f1ac0c79e75ddbe00df7f06199144801fd873ae . You can't get your guild back, but i'll give you gems back - uuid?

**Comment by Aiseant** [comment]
Thanks for fixing, as I'm afraid this can happen to others people (even if I think leave is pretty clear for native speakers, I've to admit it was a dumb move from me) This brings another "issue" : I saw the gems are transferred to the "guild bank account", so what is planned if people want to dismembered (?) a guild, deliberately in their case, and there's still gems left on the guild account ? Just to know if all is lost, or what ?

**Comment by lefnire** [comment]
restored gems. Yeah, the gems still stay in the bank. The second-most
senior member becomes leader (able to allocate those gems to challenges),
unless the leader was the last one out, and until I create the "designate
new leader" feature. IMO that setup works pretty well, what do you mean by
"all is lost"?

**Comment by Aiseant** [comment]
Gems are back \o/ .o. \o/ Thanks ! 

The "all is lost" I was talking about is when the last person is out and the guild account is cloased (what happened to me, for instance) 

edit : oh oh ... wow ! you gimme back twice the cost of the guild :D I don't know if it was intended, but please correct it if it wasn't :)

**Comment by lefnire** [comment]
ah, that commit also makes it so last-person-out doesn't close a paid-for guild, only parties. Made sense to close the guild for free ones, but not for paid.

Also, just gave you a contrib badge - you've def. done your fair share of pixeling I'm going to give more people badges in a few weeks, and gear once the gear is in - but while I had your account open..

**Comment by Aiseant** [comment]
Ok, thanks ;) 

In fact, I'm glad I can help :)
