### ISSUE TITLE
Clicking on 'join' a guild brings you back to your habits page

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#1137]
When you click to 'join' a guild, you're brought back to your main page, with todo habits etc, and you have to scroll up (if you were down on the guild page).

Not really a bug, but annoying anyway.

**Comment by lefnire** [comment]
It's because joining a guild requires a refresh. All initial model
subscriptions (live connections to the database) are constructed on the
server before the page is sent to the browser. So when they join a guild,
we need to re-initialize that process. I'm working on finding a way around
it, but due to our current setup it's rather difficult

**Comment by Aiseant** [comment]
Yes, I was thinking something like that. I don't think this is very important right now, as I said, it's just annoying but it will become more and more painful for people when they'll try to join numerous guilds when we'll have a very long list

Is it possible at least to be at the top of the page when refreshed ? I really realized this 'glitch' because I have a pretty long list of habits and to do (so I can go very low on the page and I had to scroll up a lot) :)

**Comment by lefnire** [comment]
ah, that's a browser thing - remembering where you were on the page. I
think I'd rather work on coming up with a dynamic subscription solution, so
you don't have to refresh, rather than work on temporary stop-gaps for this
- unless I find it an impossible task

**Comment by Aiseant** [comment]
Seems sound to me

**Comment by paglias** [comment]
For the scroll on refresh, you could just scroll to the top after page load with `window.scrollTo(0,0)`.

About being brought back to the main page, even if you find a solution that doesn't require refreshing, what about using routes? So for example I can immediately reach a guild, the tavern without having to pass from the home page

**Comment by lefnire** [comment]
@paglias brilliant ideas. I'll check into those soon as I get the chance if you don't beat me to it.

**Comment by paglias** [comment]
I'm not very competent in Derby, I only gave it a quick look but I tjink that normal routes could be quite difficult to implement without giving many advantages. A quicker and simpler solution could be Transitional Routes http://derbyjs.com/#transitional_routes that don't require new routes. 

I'll try to set up something in the next few days

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
