### ISSUE TITLE
challenge creation/edit screen should not close except by buttons

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11394]
As reported by @caesg (e05cd0c8-038c-4606-82cf-744eea3568f6):
"If I click outside the foreground challenge box, while creating or editing the challenge, then the challenge box disappears and work up to that point is lost."

The desired behaviour is that the challenge creation / editing modal (screen) should close only if you click on the "x" button on the top right corner or the "Add Challenge Tasks" / "Update Challenge" button at the bottom of the form.

Clicking outside the modal should not close it.

_Currently, the modal can also be closed if you hit the Escape key on your keyboard. My personal opinion is that that should be prevented as well. It's convenient to use Esc if you've opened the screen by accident, but that won't happen often. It's definitely not convenient for all your work to be lost if you accidentally hit Esc while creating a challenge and I think that's the more important case to be considered. However I'm not sure what the intention is for whether Esc can be used for closing the modal, so if the staff post here to say that Esc should still close, listen to them not me._

--------------------

FYI, for challenge creators who want to avoid this bug until it's fixed, @caesg has suggested this workaround:

"For challenge creation: Type something brief/inconsequential in each * box item and save immediately.
For editing challenge: Create text in a separate word processor. Copy text and paste into challenge."

**Comment by leodalmacio** [comment]
Hi @Alys, I'm interested with this one, can I take it?

**Comment by paglias** [comment]
@leodalmacio sure! let us know if you have any question!

**Comment by leodalmacio** [comment]
Thank you @paglias! You bet that I'll really ask hahaha. Let me just familiarize myself with the code base.

Thanks again! ^_^

**Comment by leodalmacio** [comment]
Helloooooooooo @Alys @paglias, I just want to confirm something.

Do you want to prevent the modal from closing when the `ESC` button is pressend?

**Comment by Alys** [comment]
@leodalmacio Since there's been no complaints about that idea, I think yes, we should prevent the modal closing when `ESC` is pressed.
