### ISSUE TITLE
simultaneous quest invitation accept/reject/force-start are not all recorded correctly

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11398]
Miikethepriest (ee687a55-8b32-4e74-b935-2da33248a033) reported that they accepted a quest invitation but did not become a participant in the quest. Usually when this happens it's because the quest owner force-started the quest first, but in this case I've confirmed they really did accept the invitation in time and really were not recorded as a participant. 

From Amplitude data I found that another party member accepted the quest invitation about a quarter of a second after Miikethepriest. I'm assuming that the second acceptance prevented the first from being permanently stored in the database.

The party chat and Amplitude data showing this is below.

I'm marking this as minor priority since it's unlikely to happen often, and suggestion-discussion for a fix to be discussed.

```
quest owner sending invitations to the quest:
{
"client_event_time":"2019-09-26 21:04:03.645000"
"event_properties":{"owner":true,
"category":"behavior",
"questName":"dilatory_derby",
"response":"accept"},
}

Miikethepriest accepting the invitation:
{
"client_event_time":"2019-09-26 21:04:44.749000"
"event_properties":{"owner":false,
"category":"behavior",
"questName":"dilatory_derby",
"response":"accept"},
"user_id":"ee687a55-8b32-4e74-b935-2da33248a033",
}

another party member accepting the invitation in the same second:
{
"client_event_time":"2019-09-26 21:04:44.976000"
"event_properties":{"owner":false,
"category":"behavior",
"questName":"dilatory_derby",
"response":"accept"},
"user_id":"f836...",
}

quest owner force-starting the quest:
{
"client_event_time":"2019-09-27 10:25:59.690000"
"event_properties":{"owner":true,
"category":"behavior",
"questName":"dilatory_derby",
"response":"force-start"},
}

{
    "text": "`Your quest, The Dilatory Derby, has started.`",
    "info": {
        "type": "quest_start",
        "quest": "dilatory_derby"
    },
    "timestamp": "2019-09-27T10:25:59.283Z",
    "groupId": "3dc87ceb-35f0-4e69-b356-3f91a1078c4e",
    "_meta": {
        "participatingMembers": "[various party members including f836... but not including Miikethepriest]",
    },
}
```

**Comment by cvuorinen** [comment]
Maybe it could be solved by using `findByIdAndUpdate` and passing only the single members flag in the update instead of saving the whole group model.

**Comment by Alys** [comment]
There's an instance that might be another example of this but although slightly different. A quest accept/reject event and a force-start event happened at the same second, and (possibly as a result of that), the party's quest object wasn't updated correctly (the quest is active but the members array wasn't purged to remove the `false` and `null` entries).  I'm updating this issue's title to include this possibility too.

The person who did the reject at the same time as the force-start did have their reject status correctly saved (they are one of the `false` values in the members array), so I guess that update to the members array overwrote the update from the force-start event.

```
{
    "_id": "0aa5af39-f802-4a5e-88e7-3135724ef661",
    "quest": {
        "progress": {
            "collect": {},
            "hp": 32.709254797200984
        },
        "active": true,
        "members": {
            "[user id 1]": true,
            "[user id 2]": false,
            "[user id 3]": null,
            "[user id 4]": false,
            "[user id 5]": true,
            "[user id 6]": false,
            "[user id 7]": false
        },
        "extra": {},
        "key": "dustbunnies",
        "leader": "[leader's user id]"
    },
}
```



```
{"server_received_time":"2019-10-17 15:27:27.713000",
...
"partyID":"0aa5af39-f802-4a5e-88e7-3135724ef661",
...
"event_properties":{"owner":false,"category":"behavior","questName":"dustbunnies","response":"reject"},
...
}
```

```
{"server_received_time":"2019-10-17 15:27:27.724000",
...
"partyID":"0aa5af39-f802-4a5e-88e7-3135724ef661",
...
"event_properties":{"owner":false,"category":"behavior","questName":"dustbunnies","response":"force-start"},
...
}
```

**Comment by Alys** [comment]
The person who did the reject at the same time as the force-start did have their reject status correctly saved (they are one of the `false` values in the members array), so I guess that update to the members array overwrote the update from the force-start event.

**Comment by cvuorinen** [comment]
I could try to fix this with something similar to https://github.com/HabitRPG/habitica/pull/11502 (atomic update only to the correct value, without overriding any possible other updates since data was loaded). Or this could probably also be fixed with transactions on Mongo 4, but don't know what's the timeline for that.

**Comment by SabreCat** [comment]
I like @cvuorinen's idea of using atomic `findByIdAndUpdate` -- that's a good practice that will help avoid various similar issues wherever we can use it. And it'll work as a fix pending a bigger Mongo upgrade.

**Comment by cvuorinen** [comment]
Ok, I can take a stab at this issue.

**Comment by Alys** [comment]
@cvuorinen Thanks heaps! I've marked it as in progress for you.

**Comment by shanaqui** [comment]
Hi @cvuorinen, are you still interested in working on this? Please let us know! :)

**Comment by cvuorinen** [comment]
Yep, sorry for the delay. Been busy with other work, but I was going to look into it this week.

**Comment by shanaqui** [comment]
Awesome, thanks for checking in!
