### ISSUE TITLE
Background preview feature doesn't work

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11392]
As reported by Lorem Ipsum / @loremi (64d5d2fa-4ab1-4ff2-bc93-e46a18d44b25):

'Pop-up bug: In the background menu, when I click on a un-bought background to try it on, the preview pop-up shows up behind the pop-up with all the backgrounds showing. You then have to close the "all backgrounds" pop-up first, then the preview pop-up, then the "all backgrounds" pop-up again.'

I assume the intention is that the preview should open on top of the background modal, and then you should be able to close the preview to keep using the background modal.

**Comment by citrusella** [comment]
For what it's worth, this isn't happening on the delta site. Is there a difference between delta and production that would explain this?

I wonder, is it possible #11384 will fix this? It appears to be active on delta (where the background list is z-index 1040 and background preview modal is 1041) but isn't on production yet (where both modals are 1040 but the list modal is being overridden by 1045 with !important).

I'm brain foggy, so I'm mostly asking this based on it being z-index related and the difference between the two being a number removed in that PR, but figured it was worth an ask.

**Comment by Alys** [comment]
@citrusella Thanks so much! I must have been too tired to think about checking delta/staging. :scream: It would be z-index related and I think you're right that it's been fixed so I'm closing this. We can reopen it if needed later.
