### ISSUE TITLE
Can't delete dailies or habits

### ISSUE THREAD

**Issue by ibvee** [HabitRPG/habitica#1139]
I can't seem to delete dailies or habits. Todos work fine though. 

Output error: 
Uncaught TypeError: Property 'confirm' of object [object Object] is not a function     pCJFEDOk8qj_clhUOZeRjQ.js:20
e.del         pCJFEDOk8qj_clhUOZeRjQ.js:20
i.fn            pCJFEDOk8qj_clhUOZeRjQ.js:7
r               pCJFEDOk8qj_clhUOZeRjQ.js:8
r.trigger     pCJFEDOk8qj_clhUOZeRjQ.js:8
o              pCJFEDOk8qj_clhUOZeRjQ.js:8

User ID: 
808aa439-96bf-4af1-9f4e-a74757d1e57f

Windows 7 64bit
Chrome version 27.0.1453.94 m

**Comment by lefnire** [comment]
Is this still happening for you? I've tested your account locally and I
can't replicate

**Comment by ibvee** [comment]
Yes, this still happens. Could it have to do anything with cookies? Because I haven't deleted those yet.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
