### ISSUE TITLE
HTML entities & and < are not handled correctly

### ISSUE THREAD

**Issue by yaleman** [HabitRPG/habitica#114]
I made a Todo that was "Service K&N Filter" and it was displayed as "Service K&amp;N Filter"

Current ones I can reproduce (all task/item types)
- & translates to &amp;
- < is also translated to &lt; 
- > works ok, all others I can figure out too, such as the below (OSX keymaps rock):
  `¡™£¢∞§¶•ªºº–≠«‘“πøˆ¨¥†®´∑œåß∂ƒ©˙∆˚¬…æ÷≥≤µ˜∫√ç≈Ω~!@#$%^*()_+_|}{":?
- Doesn't seem to affect the ability to complete tasks

**Comment by racuna** [comment]
Tildes and accents in spanish works fine: á é í ó ú and ñ

regards from Chile

**Comment by JamPol** [comment]
I was just about to meantion this for Health & Safety paperwork. It is possible to complete the task though.

**Comment by yaleman** [comment]
Thanks, should have mentioned that (half asleep!) it doesn't affect completion - have updated the issue to note this.

**Comment by blueskymonster** [comment]
Something interesting:
"&" yields "&amp;"
"& " (note the space) yields "& "
" &" (note the space) yields " &amp;"

It turns out that as long as "&" is followed by a space, it renders correctly for some reason. Perhaps there is a constant or string in the code somewhere that mistakenly has a space in it?

**Comment by nt3rp** [comment]
I was poking around, and it all comes down to [this line](https://github.com/lefnire/habitrpg/blob/master/src/app/index.coffee#L166); it looks like it has something to do with how derbyJS does its escaping. From the Derby documentation:

> Because it understands the HTML context, Derby’s HTML escaping is much more minimal than that of most templating libraries. You may be surprised to see unescaped > and & characters. These only need to be escaped in certain contexts, and Derby only escapes them when needed.

I'm still new to this, but I'll see if I can figure something out.

**Comment by Pandoro** [comment]
Was this fixed with the pullrequest from @nt3rp  ?

**Comment by nt3rp** [comment]
It ought to have been. is it still present?

**Comment by Pandoro** [comment]
Okay :) Thank you, then we can close this one!
