### ISSUE TITLE
Hall of Heroes path update treats "true" as a string

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11402]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When using the Hall of Heroes admin features to award items to user accounts, the intended usage is to specify a path e.g. `items.gear.owned.head_armoire_shadowMastersHood` and a value like `true`. However, if you do so, the value is set as a string, leading to the path being set to the literal `"true"` which fails to make the item appear for the user.

**Comment by paglias** [comment]
Should be enough to update this function here https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/items/utils.js#L64 to support owned items

**Comment by Alys** [comment]
Is https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/items/utils.js#L70 a bug? Mounts shouldn't be a Number

**Comment by paglias** [comment]
Good catch @Alys ! https://github.com/HabitRPG/habitica/pull/11403 should fix both problems
