### ISSUE TITLE
Username styling incorrect on profile links

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11404]
Reported in RaB, confirmed by me:

> Aerilita   @Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) [web] 
> Minor bug.
> 
> So I opened a profile in a new link to send a message later, and when I tried to, the recepient's name was wrong colour. Happens on both Chrome and Firefox, when accessed from a direct link or via a new tab, not happening when the profile is opened by a click from the Habitica's page (although the URL changes too).

![image](https://user-images.githubusercontent.com/8144640/66235628-6bfc2a80-e6e8-11e9-9f80-32c35a905ba6.png)

**Comment by Markkop** [comment]
Hey! I've opened a PR with the fix and more details about the bug #11405
