### ISSUE TITLE
the memory problems just cost me a pet

### ISSUE THREAD

**Issue by mendingwall** [HabitRPG/habitica#1141]
to be fair? I usually have to re-check dailies multiple times a day when they get lost, and I usually take hitpoint losses because they uncheck themselves overnight. I have a lot of things on my lists, and sometimes just take the hit as a 'random attack' sort of chance thing instead of reinstating my HP every morning because-- to be honest-- resetting all my stats every single day kills the game aspect and turns it into just another list of things I have to remember. I rarely get that close to dying, even if the loss of EXP slows down my game progress a lot lately. 

I did the survey, just got my ten gems today, and got a gold hatching potion and a dragon egg and hatched my new pet. was very happy.

came back to find it gone, neither egg nor potion in my inventory, and my dailies shot back to twelve hours ago. I still had my gems, so I just rebought the potion and tried to rebuy the dragon... and couldn't. now I have two gold potions in my inventory mysteriously, and no ability to get another egg with this number of gems.

guys. I love this game. it's helped my life a lot. I understand this is still beta. but... guys. please.

**Comment by mendingwall** [comment]
... a dragon egg just appeared even though I still have two gold potions, and somehow, 2 gems.

either you guys are really quick on the draw and magically found me, or...

_BRAINSPLOSION_

**Comment by StanLindsey** [comment]
Sounds like you might of just hit the server during a restart or something. Just to confirm are you okay now? You've got your egg, potion & correct gems? If so close this ticket, if not leave your UID and let me know what is different. 

We are working on these issues!

**Comment by Shaners** [comment]
Out of curiosity do you have a tendency to leave Habit open in a browser window / tab for an extended period of time or use Habit on multiple computers?

**Comment by mendingwall** [comment]
Sorry for the delay!

Sometimes I leave it in a tab open, I don't use it on multiple computers or even browsers though.

By the end of the error wackiness, I wound up with my original egg/potion back and an extra gold potion somehow. If someone wants to take it off my account that's fine let me know, otherwise I'll write it off as a fluke-drop and close the ticket.
