### ISSUE TITLE
"npm start" gives errors

### ISSUE THREAD

**Issue by martineizayaga** [HabitRPG/habitica#11419]
Hello! I'm using Mac OS locally for Habitica. I ran "npm install" and got these errors:

Here's the gist with the errors: [https://gist.github.com/martineizayaga/196ca85312ee412f6c371e5e2106ff3a](https://gist.github.com/martineizayaga/196ca85312ee412f6c371e5e2106ff3a)

Here's the line where the errors start: [https://gist.github.com/martineizayaga/196ca85312ee412f6c371e5e2106ff3a#file-gistfile1-txt-L11666](https://gist.github.com/martineizayaga/196ca85312ee412f6c371e5e2106ff3a#file-gistfile1-txt-L11666)

I'm running Node JS 12.0.0, npm 6.9.0, and mongodb 3.4

**Comment by paglias** [comment]
Could you try running `npm install bcrypt@latest`? the issue seems to be with the installation of the `bcrypt` package.  On their GH page it says

> Note: OS X users using Xcode 4.3.1 or above may need to run the following command in their terminal prior to installing if errors occur regarding xcodebuild: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

**Comment by SabreCat** [comment]
Closing for now--if you're still having trouble, @martineizayaga, definitely comment again here or reach out to the Aspiring Blacksmiths Guild for help!
