### ISSUE TITLE
dropdown menus in Market have no default text

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11423]
As reported by citrusella:

"The dropdowns for sorting and grouping on the [Shops > Market] page only show the arrow. (As compared to, say, pet or equipment dropdowns showing the text and the arrow.)"

![image](https://user-images.githubusercontent.com/1495809/67139952-09cf2800-f299-11e9-96b3-7e5b24bb7314.png)

For an example of how it should work, see the Inventory > Items page where the "Sort By" menu has the default sort order displayed as soon as you load the page.

**Comment by Alys** [comment]
For an example of how it should work, see the Inventory > Items page where the "Sort By" menu has the default sort order displayed as soon as you load the page.

**Comment by saraheisa** [comment]
@Alys I'm interested to work on this one
Would you please assign it to me?

**Comment by paglias** [comment]
@prosarahgamal sure, go ahead! I'll mark it as in progress
