### ISSUE TITLE
Quests: Boss HP scaling / difficulty

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#11421]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Scaling Quest Boss HP is something that has been requested in the Trello board many times ([earliest comment](https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v2-collection-quest-and-boss-fight-enhancements#comment-52b1233f80dd3da24500e263) I found was from 2013), and this also comes up in various Guilds like Ask a Question & Tavern. 

The [latest comment](https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v2-collection-quest-and-boss-fight-enhancements#comment-5da8b7b199b6be4662a7a389) in Trello summarizes well the issues and frustration that large & powerful parties face, and suggests optional 10x to 100x multiplier to Boss HP. Others have suggested that the scaling would be [calculated by the amount of members](https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v2-collection-quest-and-boss-fight-enhancements#comment-5be0307eba55d3253b01af9a) participating in the Quest or also taking into account the [levels of the participating members](https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v2-collection-quest-and-boss-fight-enhancements#comment-598c15afc5116904c60f462e) according to some equation. And there is also [this comment](https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v2-collection-quest-and-boss-fight-enhancements#comment-598cbd706353b8298dd7665a) from 2017 where @lemoness says that a difficulty feature will be added after website redesign.

So I decided to create this issue to see if this is something that we could actually start working on, since it's obviously something that many users want and have wanted for many years. I tried to search for issues on this same topic but couldn't find any. Also I didn't see anyone saying in the Trello that this wouldn't be a good idea. I would be willing to work on this myself, but also totally fine if someone more experienced contributor wants to take this on.

So, first step would be to discus how the feature would work. My idea would be to add an optional feature for this, so that without doing anything special, things would work exactly the same as before. But when starting a new Quest there would be a toggle with a name something like "Adjust Boss difficulty" (and could have some accompanying description text that says it scales the Boss HP by participating members etc.). When the toggle is selected it could be only the "autoscaling" functionality or could also have user selectable multiplier (e.g. 10x, 20x, 30x...) if that's something we feel is useful. The autoscaling toggle could also be a Party specific setting that the Party leader can change and only need to set once, and then automatically gets applied to all quests.

I feel that the autoscaling feature would be ideal and would also accomodate for scaling the difficulty down (for low level parties or players doing quests solo). I haven't yet given the actual calculation that much thought, but I think it would work best if it would consider at least: the number of participating members and their current level, but maybe also their class and/or their STR stat. So for example a party with 10 level 20 healers would get same difficulty as a party with 3 level 20 warriors and same for party with 5 level 20 mages, or something along those lines. But the user selectable multiplier would of course add more freedom for the parties to choose what they want. One idea I also had was that the "Adjust Boss difficulty" would be a select box with different difficulty levels, such as Easy, Medium, Hard etc. Nice thing about the difficulty levels is that it's something many games also have, so it kinda ties back to the RPG nature of Habitica.

**Comment by SabreCat** [comment]
Hi @cvuorinen -- we don't use the main issues list for feature requests, so I'm closing this ticket. Thus far we've addressed quest difficulty by offering a wide variety of different quest content with difficulty being one of the differentiators, but this is something we could consider for a quest overhaul in the future!
