### ISSUE TITLE
Task approval requests not being cleared out of notifications

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11422]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

From the Report a Bug Guild:

>@Kantacoria (6b1f010f-28fc-48f2-a4df-eaabefec51a3): "I'm trying out the Group option, and I get notifications when a task needs approval. The problem is I can't make them go away once the task has been approved. This is only a problem on the computer interface, not the app."

It sounds like

a) Something's going awry in this code block: https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/tasks/groups.js#L354-L376
b) We should consider allowing users to dismiss approval requests without action

**Comment by paglias** [comment]
@SabreCat is this being handled in the Teams PR?
