### ISSUE TITLE
Challenge Join button is displayed for non-existent and inaccessible challenges

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11420]
@vamsijv [reports](https://github.com/HabitRPG/habitica/issues/10689#issuecomment-542887894) that when a challenge doesn't exist or isn't in a guild you're allowed to see (e.g., [this one](https://habitica.com/challenges/2350bb37-29f8-42dd-9a43-c3cc9e9d1939)), the challenge page still has the elements on it to let you Join the challenge.

_"... it's still offering people to join. Browser version [shows] message 'Challenge not found or you don't have access' upon clicking 'Join' button. It would be better if the page shows only this message on its load instead of regular UI elements for challenge."_
![finished challenge accessible - browser](https://user-images.githubusercontent.com/3140940/66958921-efbdfb80-f086-11e9-9d80-f6b1743d76be.PNG)

I'm marking this as suggestion-discussion for the staff to comment on whether a change is desired. FYI @Tressley

**Comment by vamsijv** [comment]
@Alys Please let me know when you have any update on whether this needs to be worked on. Thanks.

**Comment by Tressley** [comment]
@vamsijv -- We've discussed this and it'll need someone to take it on, if you're interested!

Our proposed solution is instead of loading the Challenge page, we should re-direct the user to the "Discover Challenges" page that displays the error message.

@Alys -- Did you have proposed messaging for the error or does the current copy still work?

**Comment by vamsijv** [comment]
@Tressley Thanks for the update. I would be happy to help here. 

If I understand correctly, we would like to _"Take user to 'Discover Challenges' page, whenever a challenge that's not accessible to current user is attempted to load. In addition to this, we show a message basically informing the user that requested challenge is not accessible and guide him/her to other available challenges"_

While I start working on this, please let me know the requirements(e.g message part) once finalized for this. Also I was wondering if there is any reference doc/requirement notes so I could know exactly  how the accessibility of challenge to a particular user(e.g. owner, participant and for different type of challenge - party, public etc.) is determined exactly. This would drive our new behavior.

cc @Alys

**Comment by Alys** [comment]
I think the current message is good:
https://github.com/HabitRPG/habitica/blob/1859f431338e16ca9fa2a4245bfe8dd068207315/website/common/locales/en/challenge.json#L86

@vamsijv If you search for the places where that message is used (`git grep challengeNotFound`), you'll find the code that controls how a user can access a challenge (since that message is displayed whenever a challenge should not be accessed by the user). We want to keep using the same access controls that we have now. That grep command will return a lot of hits but if you ignore the tests and the locales files, you'll see there's only three *.js files to look through. One example is the getChallenge() call so you can use that to find code that controls access: 
https://github.com/HabitRPG/habitica/blob/1859f431338e16ca9fa2a4245bfe8dd068207315/website/server/controllers/api-v3/challenges.js#L502

Note though that we don't want any API calls themselves to be modified because that would be a breaking change for the API (i.e., any code that currently uses the API to fetch a challenge's data would work in a different way than it does now). The new behaviour to resolve this issue should be added to just the website's client-side code.

**Comment by vamsijv** [comment]
@Alys I was able to make the necessary changes based on your inputs. Thank you!
I believe next steps are unit testing from my end. Is there any other QA cycle involved (or fix validation by some dedicated QA) before deploying to production? 
I know that there are some steps mentioned [here](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) for individual developers for testing any change that is needed for deployment. I will try to follow these unless you suggest something else for this fix to go live.

**Comment by Alys** [comment]
@vamsijv That wiki page you linked to should contain everything you need to do! 

If it turns out that it doesn't, let us know and we'll add to it.

**Comment by vamsijv** [comment]
The changes for this ticket are available in PR for review.
