### ISSUE TITLE
Experience graph doesn't appear

### ISSUE THREAD

**Issue by altsanz** [HabitRPG/habitica#1145]
I click on the experience bar and it does nothing, but next message appears in console:

You were about to set on a path including undefined: _tasks.charts.undefined Tfkd6Fz4QinKC3BcBp0jSQ.js:6
You were about to set on a path including undefined: _tasks.editing.undefined Tfkd6Fz4QinKC3BcBp0jSQ.js:6
Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by lefnire** [comment]
fixed https://github.com/lefnire/habitrpg/commit/c797ea59998cbbbf11244771e81e2138d61bc76c
