### ISSUE TITLE
"Hatchable" sort mode does not act as expected

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11458]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

I would have expected that sorting the Stable by "Hatchable" would bring all the pets that I can currently hatch to the top of the list. Instead, it groups by species, which makes it not much different from "Standard" when you can hatch a number of different animals of the same color:

![image](https://user-images.githubusercontent.com/4501321/67299466-55105300-f4b2-11e9-9319-63dd4d4fa64e.png)

**Comment by adamfitzgibbon** [comment]
I can take a look at this!

**Comment by Alys** [comment]
@adamfitzgibbon Thank you! I've marked it as in progress for you.
