### ISSUE TITLE
Calendar Pop-up Rarely Works

### ISSUE THREAD

**Issue by mutedgrey** [HabitRPG/habitica#1146]
I couldn't see anything like this in the few issues having to do with the calendar. I'm not sure if this is really a bug or if I'm just not using the calendar right? But the only time I seem to see it pop-up is when I've already entered a date and go back to change it, which is kind of silly, and even then I can rarely get the calender to show up. It might be related to how habitrpg is very laggy for me in general but I can't be sure.

It would also be helpful to have the calendar pop-up when entering due dates and regardless of whether I'm clicking on the "due date" text or in the field box. Right now I have so much difficulty getting the calendar to pop-up at all that I can't tell if it already works this way or not.

**Comment by aaronjbaptiste** [comment]
Which browser are you using? It works ok for me. If you click inside the Extra Notes field, and then back in the due date field, does it open then?

**Comment by mutedgrey** [comment]
Hi Aaron. I'm using Firefox 22.0 on the beta update channel, although I had the same issue on previous versions of Firefox. 

Trying it just now in every combination I can think of:
Create new todo -> Edit -> Click Due Date -> Calender does not pop-up
Create new todo -> Edit -> Click Extra Notes then Due Date -> Calender does not pop-up
Create new todo -> Edit -> Enter Due Date Manually -> Save & Close -> Edit same todo again -> Click Due Date -> Calender does not pop-up
Create new todo -> Edit -> Enter Due Date Manually -> Save & Close -> Edit same todo again -> Click inside Extra Notes first -> Click Due Date -> Calender does not pop-up
Edit older todo -> Click on Due Date -> Calender does pop-up
Edit older todo -> Click inside Extra Notes first -> Click Due Date -> Calender does pop-up

After refreshing the page:
Edit todo I had just created above -> Click on Due Date -> Calender does pop-up
Create new todo -> Edit -> Click Due Date -> Calender does not pop-up -> Begin writing the Due Date manually -> Calender decided to pop-up
Everything else works the same as above, i.e. other new todos wouldn't pop-up the calendar but older todos did.

Also, if I input the year as simply 13 (as in 06/14/13), the year on the calender pop-up defaults to 1913 instead of 2013. As my DeLorean time machine is broken, that's not terribly useful. If the Calendar actually worked and I was clicking to pick the due date, then this probably wouldn't be a big deal since I'd rarely be writing the due date in manually anyway.

It's a bummer if I'm the only one having these issues!

**Comment by Senth** [comment]
I too have the same problem and as you've noticed. The calendar does not pop up for newly created todo. I have to refresh the page to be able to get the pop-up working.

I'm using Chrome 28.0.1500.71_p209842

**Comment by AndreCaseyScott** [comment]
Due to #840 and the pending Angular Rewrite #841, there is nothing that can be done about this for now.  The only work around is to make sure that you refresh the page immediately before you attempt interacting with it (calendars included) and wait for the page to _fully_ load. The little spinning icon that denotes loading with stop once, and then spin up again to load the async stuff that should allow you to interact with the calendar.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
