### ISSUE TITLE
webhook label should be able to be set back to empty string

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11477]
_As reported by @rhitakorrr (cab16cfa-e951-4dc3-a468-1abadc1dd109)_:

"Updating a webhook with an empty string as a label does not clear the label. Example:"
```python
>>> response = fetch("https://habitica.com/api/v3/user/webhook", requests.post, { "url": "https://example.com", "label": "Example" })
>>> response.json()["data"]["label"]
'Example'
>>> webhook_id = response.json()["data"]["id"]
>>> modified_webhook = fetch(f"https://habitica.com/api/v3/user/webhook/{webhook_id}", requests.put, { "label": "" })
>>> modified_webhook.json()["data"]["label"]
'Example'
>>> modified_webhook_2 = fetch(f"https://habitica.com/api/v3/user/webhook/{webhook_id}", requests.put, { "label": " " })
>>> modified_webhook_2.json()["data"]["label"]
' '
```

"I found the issue in the source a while back (though I don't remember exactly where now), and if I recall correctly, a conditional was treating empty string as if no value was provided. This was due to the false-y nature of empty string in JavaScript. Changing the conditional to check for `== null` would probably fix this."

_Note that the default value for the label in a new webhook is an empty string (see the dump below for a new webhook created through the habitica.com website), so it should be permissable to set the label back to an empty string._
```
    "webhooks": [
        {
            "type": "taskActivity",
            "label": "",
            "enabled": true,
            "id": "f02900eb-f401-4e24-bc65-2d5b677601f3",
            "options": {
                "created": false,
                "updated": false,
                "deleted": false,
                "checklistScored": false,
                "scored": true
            },
            "url": "http://alsdkjf.cdl/",
            "createdAt": "2019-10-27T04:22:42.497Z",
            "updatedAt": "2019-10-27T04:22:42.497Z"
        }
    ]
```

**Comment by evelynstender** [comment]
Hey, can I work on this one?

**Comment by Alys** [comment]
@evelynstender Sure, thanks!

**Comment by evelynstender** [comment]
@Alys Cool! Opened a PR :)
