### ISSUE TITLE
No progress graph for experience

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#1148]
Hi there,

I can have graph for dailies and habits progression (by cliking on the icon with 4 bars, labelled "progress"), but I cannot have it for my global experience, on the header.

I remembered having it at least once, when I started to play, but I never checked since ... so I don't know for how long this didn't work for me.

**Comment by StanLindsey** [comment]
#1145 - closing for housekeeping

**Comment by lefnire** [comment]
fixed https://github.com/lefnire/habitrpg/commit/c797ea59998cbbbf11244771e81e2138d61bc76c
