### ISSUE TITLE
Error while running dev environment using docker 

### ISSUE THREAD

**Issue by aneesh4995** [HabitRPG/habitica#11498]
This is the error which I am getting when I try to run the app using docker and locally 
server_1  | [00:50:24] [nodemon] starting `node ./website/server/index.js`
server_1  | npm ERR! code ELIFECYCLE
server_1  | npm ERR! errno 1
server_1  | npm ERR! habitica@4.118.0 start: `gulp nodemon`
server_1  | npm ERR! Exit status 1
server_1  | npm ERR! 
server_1  | npm ERR! Failed at the habitica@4.118.0 start script.
server_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
server_1  | 
server_1  | npm ERR! A complete log of this run can be found in:
server_1  | npm ERR!     /root/.npm/_logs/2019-11-01T00_50_27_136Z-debug.log

**Comment by SabreCat** [comment]
Ah, looks like we updated the production Dockerfile for recent client changes but not the dev version. I can take a look at this!

**Comment by davis1410** [comment]
I appear to have had a related issue. It kept telling me that `vue-cli-service` wasn't installed, so it wasn't able to build the application. I made some modifications to the `Dockerfile-Dev` file and was able to get the development Docker working today. I'm more than happy to submit my fix in a pull request for review.

**Comment by aneesh4995** [comment]
That would be great. @davis1410

**Comment by SabreCat** [comment]
Absolutely @davis1410, please do!

**Comment by davis1410** [comment]
Got the pull request created, and it's ready for review.

**Comment by Alys** [comment]
Just to check something...

> Ah, looks like we updated the production Dockerfile for recent client changes but not the dev version. 

That doesn't still need to be done does it? For example, Dockerfile-Dev doesn't have `RUN npm set unsafe-perm true` or `EXPOSE 80 8080 36612` that were added to Dockerfile in https://github.com/HabitRPG/habitica/commit/2ab197745a5830e1940448252c23eb175aae442c

I'm not very familiar with Docker so I might be on totally the wrong track here. :)

**Comment by SabreCat** [comment]
@Alys Definitely not the `EXPOSE`. If folks run into trouble with file permissions we can add the other one, but so far as I know that's a quirk of our current production architecture rather than a universal thing.
