### ISSUE TITLE
website `title` tag "Gamify Your Life" is not translated

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11495]
As reported by @thatrobotdev (5222cb6c-3ae4-4ea9-a5d8-ce21ecc53b19):

"The <title> tag of Habitica is not localized":

![image](https://user-images.githubusercontent.com/1495809/67848515-8d69fe00-fb50-11e9-8236-8f200c2aacca.png)

I'm leaving this as suggestion-discussion so that the staff can comment on whether the "Gamify Your Life" part of the title should be translated and whether it's possible to do.

If translation is desired, an appropriate string already exists:
https://github.com/HabitRPG/habitica/blob/1859f431338e16ca9fa2a4245bfe8dd068207315/website/common/locales/en/front.json#L308

_(FYI for translators who aren't already aware, the "Habitica" part of the title should not be translated, for the reasons described at [Guidance for Linguists > Proper nouns and capitalization](https://habitica.fandom.com/wiki/Guidance_for_Linguists#Proper_nouns_and_capitalization).)_

**Comment by veeeeeee** [comment]
We are not looking to translate that title and tagline at this time, as there is limited benefit to doing so (and little to no harm from leaving it as is).
