### ISSUE TITLE
British or American Spelling of 'armor/armour'?

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#1149]
For the English translations, 'armor/armour' is spelled in two different ways. The British way of spelling it is armour, while the American way is armor. Lines 57-59 in the English translation:

`"_commentitemsarmour": "ARMOUR",
    "armour0Name" : "Cloth Armour",
    "armour1Name" : "Leather Armor" ,`

**Comment by Shaners** [comment]
funny enough both are correct for Canadian spelling

**Comment by StanLindsey** [comment]
I did all the translations basics. and I'm British. I think they should be Americanised really. I'll do that.

**Comment by PhilipHow** [comment]
+1 SlappyBag for relinquishing his British rights.

**Comment by wc8** [comment]
Since this is merged, I’m closing this.
