### ISSUE TITLE
Guild name hidden by tags on challenge page

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11500]
Maybe Steve Rogers @MaybeSteveRogers (767e5d92-0e13-4e30-acb1-d8bba62824fc): "(Long) guild name is hidden under tags on the challenge page - take a look:"

![image](https://user-images.githubusercontent.com/1495809/68064302-86680900-fd65-11e9-81a2-5960e2ac4d58.png)

Confirmed in Google Chrome.

**Comment by ShupingHe** [comment]
I'd like to work on this issue

**Comment by Alys** [comment]
@Stevens1995 great, thanks! Please go ahead.
