### ISSUE TITLE
Loading CSS chunk entry failed

### ISSUE THREAD

**Issue by lorenzleutgeb** [HabitRPG/habitica#11508]
Habitica does not load, so I cannot report this to the "Report a Bug"-guild.

### General Info
  * UUID: n/a (website does not load)
  * Browser: Firefox 70
  * OS: Fedora 31

### Description
The Habitica logo on a purple background flashes, but then disappears and I just get a white page. 

#### Console Errors

```
Error: "Loading CSS chunk entry failed.
(/static/css/entry.bca27fa2.css)"
    onerror Webpack
vue-router.esm.js:2079:16
    u vue-router.esm.js:2079
    h vue-router.esm.js:2124
    f vue-router.esm.js:1897
    zt vue-router.esm.js:1962
```
![Screenshot from 2019-11-04 14-18-15](https://user-images.githubusercontent.com/542154/68123753-1a74d480-ff0e-11e9-9dde-8c39eb020e42.png)

**Comment by paglias** [comment]
thanks for the report @lorenzleutgeb , I'm not able to replicate on Firefox and that CSS file is loading correctly for me. Could you try a different browser / private window or by clearing the cache?

**Comment by lorenzleutgeb** [comment]
OK. After you responded, I tried it with Firefox' "Private Window" feature, and also played around with extensions. It seems that your website does not load with [Privacy Badger](https://github.com/EFForg/privacybadger) enabled (in a certain configuration). For me, Privacy Badger would block requests to the domain "fonts.googleapis.com". Once I enabled requests to that domain, your website would load.

Of course, now this increases chances of Google tracking me, which I hate. So I should probably file an issue asking you to host all font files on your own domain.

**Comment by paglias** [comment]
@lorenzleutgeb I just installed Privacy Badger on Firefox 70 and Habitica loads fine for me. Are you using some particular setting? 

Anyway, it should be possible for Privacy Badger to block the loading of Google Fonts without breaking the rest of the website since it's loaded in a separate request. I would suggest to open an issue reporting the problem on Privacy Badger's own issue tracker

**Comment by lorenzleutgeb** [comment]
Here you can see my Privacy Badger configuration for your site, and how it looks:

![Screenshot from 2019-11-04 16-12-16](https://user-images.githubusercontent.com/542154/68131874-118bff00-ff1e-11e9-8094-4028416b337f.png)

![Screenshot from 2019-11-04 16-10-31](https://user-images.githubusercontent.com/542154/68131882-151f8600-ff1e-11e9-9a12-46f899a07e54.png)

I already filed reported this as an issue through the Privacy Badger extension itself.

**Comment by veeeeeee** [comment]
Closing as this specific issue is outside of our control. We'll look into hosting the fonts ourselves as a separate issue.
