### ISSUE TITLE
on-hover state of tiered display names in group chats should not include a colour change

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11503]
As reported by @citrusella (2d6ef231-50b4-4a22-90e7-45eb97147a2c):

"Mousing/hovering over the display name of anyone with a tier turns their name dark blue (like, darker blue than even the mod color)."

When you hover over the name of a player who doesn't have a tier, the colour does not change. 
That should be the correct behaviour for tiered players too <strike>but I'll leave this issue as suggestion-discussion for a few days then if there's no objections, I'll mark it as help wanted. FYI @Tressley</strike> 

By the way, when you hover over the name of any player, tiered or not, their name becomes underlined. I believe this is the correct behaviour for all players. I.e., the only on-hover effect should be an underline, not a colour change.

EDIT: See the comment below from Tressley for confirmation of the desired behaviour. In addition to changing the on-hover behaviour, the :focus and :active states should be changed too if needed, as he says.

**Comment by Tressley** [comment]
@Alys -- You're correct in that the color should not change and an underline should be applied for player names with and without a tier. This is also true for the `:focus` and `:active` states as well.

**Comment by adamfitzgibbon** [comment]
@Alys I can take a look at this one!

**Comment by Alys** [comment]
@adamfitzgibbon Thanks! I've marked this as in progress for you.
