### ISSUE TITLE
No reward after filling out survey

### ISSUE THREAD

**Issue by MasterGalvin** [HabitRPG/habitica#1151]
I filled out the survey for May but did not receive the badge-- apparently I'm not the only one.  Can you check into it?  Username is MasterGalvin.

Thanks!

**Comment by Shaners** [comment]
What is your User ID? Under settings it should be a long string of letters and numbers.

**Comment by lefnire** [comment]
It's anyone who didn't fill in the uuid question correctly according to the first question's instructions. i'm setting you up now, check back in 5 & re-open if still not there

**Comment by MasterGalvin** [comment]
72f9e803-84ef-4d5a-9081-914a2a31a173

**Comment by MasterGalvin** [comment]
By the way, I'd love to learn CoffeeScript, and I also would like to help HabitRPG.  Any quick links/pointers you could give me on a) getting started with CoffeeScript and b) getting started with the project?  I know there are resources out there on a), but just wondered what you thought were the best resources.  Thanks!

**Comment by lefnire** [comment]
Oh how we'd love you forever for joining our ranks! The first step is learning JavaScript. Second, [Derby](http://derbyjs.com/), the best tutorial is the homepage. Third, CoffeeScript - which sort of just "comes over time" if you already know JavaScript. You could take the tutorials, but I never did - it's not _that_ different from JavaScript, just a few syntax twists.

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/wiki/Running-Locally for setting up on your computer

**Comment by MasterGalvin** [comment]
ok, thanks! I'll try to ease into it soon.  I do know JavaScript, just wanted to get into CoffeeScript.
