### ISSUE TITLE
wrong @username selected from list when writing chat if list is stil updating itself

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11514]
@katzalina (c3282599-6e4d-48cf-b1ee-5d080120b925) reports:

"Not sure, if this is a new bug, but I think I've managed to hit it twice these last weeks:

"Posting in the Tavern, typing @ and choosing from the list, I seem to have managed to catch the moment before the list updated (just having posted an answer myself, this time) - the addressee seems to be taken from the position on the list, so that writing the post it was the correct one, the published post however was addressed to myself... (my name having moved to the top of the list)."

_I'm not sure if there's much we can do about this and it will hopefully not happen often but I wanted to log it here so that we're aware it can happen, and if we do get other reports we can add them here._

**Comment by veeeeeee** [comment]
We're having trouble reproducing this issue and have trouble understanding how this sequence of events would happen given that the post fills in as plain text. Closing it for the time being but feel free to reopen if other reports come up. A screen recording would be particularly helpful in diagnosis.
