### ISSUE TITLE
Username formatting breaks markdown for links in posts

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11520]
![image](https://user-images.githubusercontent.com/8144640/68435223-bde61380-01b2-11ea-9add-19ebab1ceb81.png)

> "Something I already suspected but just confirmed: Putting a mention in a link markdown breaks the link the person is trying to add (I've had to use a different "@" glyph in the first code demonstration to avoid triggering it expanding the actual mention's code there...)
> 
> Typing the following:
> 
> [＠citrusella really likes Habitica!](https://habitica.com)
> 
> produces
> 
> [@citrusella really likes Habitica!](https://habitica.com)
> 
> which the website likely sees in the following way:
> 
> [[@citrusella](/profile/2d6ef231-50b4-4a22-90e7-45eb97147a2c) really likes Habitica!](https://habitica.com)"

(Image included since obviously one can't demonstrate in the same way on github! In other words, including @username in markdown links breaks it because the @mention formatting takes precedence.

**Comment by KeiferE** [comment]
I don't mind taking a look at this one or is this already in progress in the referenced issue?

**Comment by Alys** [comment]
@KeiferE Thank you! Please go ahead and comment here if you have questions.

**Comment by KeiferE** [comment]
For desired functionality, do we want the whole link to redirect to desired weblink or the username when clicked on itself link to user with the rest of the sentence linking to desired link?

**Comment by Alys** [comment]
The whole link should redirect to the user-specified web link. I.e., the automatic linking for an @Username should be disabled whenever the @Username appears in a markdown link.

(That's the best approach because one of the common examples of this issue occurs when a player copies one of their posts to repost it with an edit. If the original post contains an @Username, you see this issue.)

**Comment by shanaqui** [comment]
@KeiferE Hi! Are you still interested in working on this issue? Please let us know. :)

**Comment by shanaqui** [comment]
I'll set this back to help wanted since there was no reply. :)

**Comment by benkelaar** [comment]
@shanaqui This one should also be fixed by the plugin we're writing here: https://github.com/HabitRPG/habitica-markdown/pull/87

**Comment by Alys** [comment]
@benkelaar Awesome, thanks for letting us know! I've marked it as in progress again.

**Comment by benkelaar** [comment]
After further investigation, this is actually on the backend part, not the frontend part, so this is not going to be fixed by the plugin (Which is ready for review).

However Nathan (@nathanzhu144) mentioned he would pick up this issue, so still in progress 👍

**Comment by shanaqui** [comment]
@nathanzhu144 Is that correct, and are you still working on this if so? If not, I'll set it back to help wanted in about seven days. :)

**Comment by shanaqui** [comment]
I'm setting this back to help wanted. :)

**Comment by benkelaar** [comment]
@shanaqui OK I'll pick it up then. I thought it might be quite hard, but I think I just now thought of a solution that leverages the work I already did for the code blocks. So should be doable.
