### ISSUE TITLE
party/group leader should remain on invitations tab after removing an invitation

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11523]
As reported by @MaybeSteveRogers:

"When viewing the guild member list on web, there's a tab that takes you to 'invitations'. Removing the invitation from any one user results in the modal "tabbing" back to the 'members' list. I'm not sure if it's intentional this way, but it *is* annoying when you're trying to clear all the invitations to have to spend time going back to the 'invitations' tab every single time."

The desired behaviour is that  you remain on the invitations tab after removing an invitation.

<strike>My guess would be that it's okay for this to be changed so that you remain on the invitations tab after removing an invitation, however I'll leave it as suggestion-discussion for a few days. If there's no disagreements from the staff, I'll then mark it as help wanted.</strike>

**Comment by alicemliu** [comment]
I'm interested in working on this one if that's okay!

**Comment by Alys** [comment]
@alicemliu Thank you! Please go ahead and post here if you have questions.

**Comment by alicemliu** [comment]
@Alys I've been able to fix the issue, test that it works manually, and have my changes pass automated tests, but I wanted to check on how I should go about writing unit tests for my changes. Which directory should tests for this kind of issue go in, and should each file contain tests for just one issue? Thanks in advance!

**Comment by Alys** [comment]
@alicemliu My personal opinion is that automated tests wouldn't be needed for this,  because this is a purely client-side problem, and because it doesn't make the invitation tab unusable so it's not a disaster if future code changes make the issue reappear.
However if any of the staff post here with an opposing reply, listen to them, not me. :)

In the meantime, you'd be welcome to submit a pull request without any new tests. You could write in the PR that you'd be willing to add tests.
