### ISSUE TITLE
I just got an empty "An item has droppped" message

### ISSUE THREAD

**Issue by marphod** [HabitRPG/habitica#1152]
As far as I can tell, my inventory is unchanged (lots of base potions, so I could have gotten a new one without noticing, but no new other potions or eggs).

**Comment by octern** [comment]
I just got this as well. Tried to take a screenshot, but hitting the modifier keys caused the message to close. I checked afterward and I believe that I did have a new item in my inventory. In case it matters, the new item is the same as the last drop I'd gotten, which was still at the end of my list (red hatching potion).

**Comment by Aiseant** [comment]
I encountered this one this morning too. Unfortunately, I've no idea if I really gain something or not (I'm not really up to date on my inventory content), but the dailie I checked that made this empty drop wasn't checked after the message closed. (and I gained nothing when I checked it again ... mew)

**Comment by wildcate** [comment]
I got one today as well, but I can't say whether I got a new egg or not (I am one of those with egg surplus and potion scarcity).

**Comment by heyimzsa** [comment]
This has only happened to me once a couple of weeks ago. 
—

**Comment by Aiseant** [comment]
I had one this morning as well, but this time the dailie stayed checked (and i'm pretty sure I did receive an egg)

**Comment by Catmagnet** [comment]
This has happened to my husband and me,  I'm one of those people with inadequate inventory control, so don't know if I got anything, but my husband has very few potions OR eggs, and he says he got nothing.

**Comment by mendingwall** [comment]
it's happened twice to me-- once yesterday, once this morning-- and it was the same type of potion both times (cotton candy blue)

**Comment by MllePandaRoux** [comment]
It happened to me two this week, I did receive a potion.

**Comment by octern** [comment]
Just happened to me again today. I wouldn't bother mentioning it except that some reports say that no new item was added, and I wanted to confirm that both times this has happened to me, I have gotten a new item from it.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
