### ISSUE TITLE
challenge participant count and list should update when joining / leaving

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11537]
When you join a challenge, the displayed number of participants does not increase immediately, and if you click on the Participants button/icon as soon as you've joined, you don't see yourself in the participant list.
Similarly, when you leave a challenge, the number and participant list are not updated immediately.
After joining / leaving, you need to reload the page to see the number and list change.

The ideal behaviour would be that as soon as you click the join or leave button, the number and list of participants should change immediately.

Note that this is just a client-side issue. When you join or leave a challenge, in the database the challenge's `memberCount` and your participant status are correctly updated, so server/API changes are not needed for this.

_Thanks to @DarkPassenger28 for reporting this._

**Comment by adamfitzgibbon** [comment]
@Alys I'll take a crack at this one

**Comment by Alys** [comment]
@adamfitzgibbon Thanks! Marked as in progress for you.
