### ISSUE TITLE
sorting in member/participant lists should use case folding for Parties, Guilds, Challenges 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11547]
As reported by @GeminiForce (bec264b9-5776-47fa-8cb6-672d33ea8fc2): 

"On the desktop, when I sort my party alphabetically by [Display Name], it will sort first alphabetically by names with the first letter capitalized and then by names with the first letter not capitalized. So that the names are listed like A, B, C, D, a, b, c, d."

The desired behaviour is that sorting should use [locale-sensitive case folding](https://www.w3.org/International/wiki/Case_folding).

The same should apply to sorting in the member lists for Guilds and in the participant lists for Challenges.

NB some Display Names start with emoji or other special characters. I don't have any particular expectations for how sorting would handle them so I think whatever position they happen to fall into will be fine - I don't think we need to have specific code to handle them.

**Comment by moniwang** [comment]
I'm interesting in working on this issue.

**Comment by Alys** [comment]
@moniwang Great, thank you! Comment here if you have questions.
