### ISSUE TITLE
Add Challenge Tasks button should be enabled after selecting new group

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11545]
As reported by @citrusella and confirmed by me:

"I inadvertently tried to create a challenge in a guild that has challenges limited to the guild leader. That brought an error and disabled the creation (add tasks) button, so I tried to switch it to a few other guilds and the button didn't reenable. It appears only a full reload reenables the button, even if you've set it after to a guild you should be able to put the challenge in.

The desired behaviour is that as soon as you select a different group from the "Add to" drop-down menu, the "Add Challenge Tasks" button should immediately be usable.

**Comment by alicemliu** [comment]
Interested in working on this issue!

**Comment by Alys** [comment]
@alicemliu Thank you! Please go ahead and post here if you have questions.
