### ISSUE TITLE
Selecting 'Su' repeat option in edit Daily disables (grays out) all days

### ISSUE THREAD

**Issue by Oshuma** [HabitRPG/habitica#1155]
Looks like this after clicking 'Su'

![screenshot_6_9_13_2_36_am](https://f.cloud.github.com/assets/2441/628599/f2077fbc-d0ce-11e2-9f1a-4e26584e82a2.png)

**Comment by MoofinSeeker** [comment]
That's because it's Sunday today. The Daily greys out on days that you haven't got selected. So because it's Sunday, it will grey out when you disable it, but on Monday the task will be active again (If Monday is an active day)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
