### ISSUE TITLE
Tutorial box covers up stats and the "next" button is hidden on phones.

### ISSUE THREAD

**Issue by MoofinSeeker** [HabitRPG/habitica#1156]
Apologies if this has already been pointed out. On my phone browser, I cannot see my current stats because of the tutorial box. I also can't get rid of the tutorial box because the header seems layered underneath the rest of the page. I have provided a screenshot below:

![image](https://f.cloud.github.com/assets/4653424/628803/79ee7be2-d0f7-11e2-9b1d-9acbbb321a75.jpg)

I am using an iPhone 4.

**Comment by deep-introspection** [comment]
:+1:

**Comment by simonwgill** [comment]
This is down to #undefined-sticky-wrapper having a defined height, .header-wrap having overflow:hidden, the div.popover with a fluid height and the buttons being at the bottom.

I don't know how to deal with coffeescript or .styl files yet, so I'll suggest these three options:
1. Move the Next and End Tour links into the .popover-title or to the start of .popover-content.
2. Give the div.popover in the header a max-height and overflow:scroll.
3. Make the popover a child of the page and absolutely position it in the right place using javascript.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
