### ISSUE TITLE
editing Challenge twice gives "string not found" categories and prevents saving

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11561]
If you edit a challenge and save it, and then immediately edit it again, the second edit has the following problems:
- the assigned categories stop being displayed at the bottom of the edit screen and instead you see "string * not found" (screenshot below)
- the "Update Challenge" button cannot be pressed meaning that your edits cannot be saved

I don't know if those two problems are related.

If you reload your browser in between the two edits, the problems don't occur.

The desired behaviour is that a second edit should work correctly without a reload being needed. The "string * not found" text should not appear.

This was reported by @BlueSky-9 (910410cb-71e0-47dd-a9b4-faa3fbe9c99c) who has seen it happen twice. I replicated it, although in one case I had to edit three times in a row before the problems happened.

![image](https://user-images.githubusercontent.com/1495809/69129159-928bee80-0af9-11ea-9235-815cd92117e1.png)

**Comment by nikonhub** [comment]
@Alys Hi.

I can fix this one.

**Comment by Alys** [comment]
@Nikosmonaut Thanks! Please go ahead and post here if you have questions.
