### ISSUE TITLE
Email edit form in Settings misbehaves after submission

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11565]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

On the Settings page, if you change your account's email address, the form fields vanish after you click Submit--and are replaced with the "Add email to account" fields. A sync or refresh corrects it, but it's causing some confusion for users. Folks think either that the email reg was _removed,_ or they try to fill out the newly appeared fields, resulting in errors due to the chosen email address already being in existence.

The page should update immediately to show the new email, or invalidate the user session and require a new login, not switch modes as if the email were no longer present.

**Comment by MeisterRed** [comment]
Hi, I would like to give this issue a try

**Comment by SabreCat** [comment]
Thanks @MeisterRed, go for it!

**Comment by MeisterRed** [comment]
Hey there, just wanted some clarification on how I should develop a solution (This is my first time interacting with vue so my knowledge is somewhat limited).

I reproduced the bug myself and noticed that any forms inside a div with "v-if="user.auth.local.email"" would immediately disappear as if the account no longer had an email just like you said. You also mentioned that the email for the account actually does update but the user doesn't see that until they leave the page or refresh. 

With that in mind, I was wondering if I should force the page to refresh after the user changes their email address. This will avoid the user being confused when the form disappears from the page.

**Comment by SabreCat** [comment]
@MeisterRed A forced refresh would be an acceptable solution!

**Comment by MeisterRed** [comment]
Alrighty, I'll have a pull request ready sometime today or tomorrow. Thank you so much for getting back to me very quickly
