### ISSUE TITLE
chat message purple dot highlighting intermittently doesn't work

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11593]
We've seen reports that the purple dot highlighting on a message containing your own Username isn't always visible. It doesn't seem to be related to any specific content of the message. The purple dot can initially not appear on a message and then later it does appear on that same message. A single reload / several reloads does not seem to be enough to fix the problem.

The rest of this post is the messages in which we were discussing this in the Report a Bug guild.

----

@katzalina (c3282599-6e4d-48cf-b1ee-5d080120b925):
> I'm not seeing a purple dot in the upper right corner of your previous message, but my name is highlighted and it lights up purple on ios. Reloading the page hasn't had an effect (citrusella's posts are marked, though).

All of the posts she mentioned contained `@katzalina` with the normal profile link.

I then made four different posts to see if I could isolate the problem:
> @katzalina Post 1
> 
> @katzalina Post 2
> ɐuᴉlɐzʇɐʞ @katzalina (c3282599-6e4d-48cf-b1ee-5d080120b925): "testing...."
> 
> @katzalina Post 3
> (testing @ALittleYellowSpider )
> 
> @katzalina Post 4
> (testing @ALittleYellowSpider )
> more text @katzalina This is the final one.

@katzalina said:
> @alys Purple dots on post 1, 3 and 4 not on post 2...

Several/many minutes later, katzalina said:
> @alys The incredibly funny thing is, that all posts have dots now, before the last post, I checked and rechecked (reloading each time) over a time of 2 maybe 3 hours and it remained the same...

@citrusella said:

> @alys If it helps you with the mention dot issue @katzalina brought up... I don't see a purple dot on the following posts (identified by their first few words here) still visible at present in this guild:
> > "LOL rabbitholds" (by you, 10 hours ago)
> > "Oh yeah, that's messed up" (by you, 11 hours ago)
> > "We do indeed have server logging" (by shanaqui, a day ago)
> > "I suspect @citrusella's post is correct" (by shanaqui, 6 days ago)
> > "Cron Safe Mode definitely does give you the Perfect Day buff" (by you, 9 days ago)
> > "Thanks! Confirmed and logged here" (by you, 10 days ago)
> > "To help me replicate and write up a good report" (by shanaqui, 12 days ago)
> > "As @citrusella surmised! I'm not sure if" (by shanaqui, 12 days ago)"
>
> I remember noticing it intermittently but I think it's a combination of me forgetting and me usually not noticing as to why I didn't say anything. I think most if not all of these did push a notification to my phone for the mention.

**Comment by citrusella** [comment]
This might be covered by the "A single reload / several reloads does not seem to be enough to fix the problem." bit but the messages I reported as missing the dot have stayed firmly in the "not having them" camp, reloads, restarts, and all.

**Comment by paglias** [comment]
I think given the refactoring of the highlight mechanism that was done this should be closed until we see more reports, what do you think @Alys ?
