### ISSUE TITLE
4 Pets Lost after Hatching

### ISSUE THREAD

**Issue by aliasBEE** [HabitRPG/habitica#1160]
Last night I used some potions on eggs in my inventory. 

2 Cacti
1 Bear
1 Flying Pig
1 Wolf (It's in my inventory in egg form, however)

I used a base potion on the Cacti, Wolf, Bear
Skeleton on the second Cacti
And I didn't do anything with the flying pig. 

After the page reloaded all of the pets I added were gone, and I was missing all the eggs (Except the wolf, which was either the first or second pet I hatched)  Unfortunately I don't have any pictures for you for before I hatched them. I wasn't expecting an issue.

I currently am using Chrome on a win7 machine, and I only have the web page open on one computer. I do tend to leave the site open throughout the day.

UserID 34e38288-0576-4b82-b2d2-90a2bf0484d3

I hope I am providing enough information. 
If I'm repeating a ticket that already exists my apologies. I did a search for lost pet and mostly came up with unrelated issues or closed tickets.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
