### ISSUE TITLE
incorrect error when sending private messages (PMs) to a player you have blocked

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11612]
When you have blocked a player from sending private messages to you, if they try to message you they see this error: 
"You can't send a message to this player because they have chosen to block messages."
That's the `notAuthorizedToSendMessageToThisUser` string in `website/common/locales/en/groups.json`
All of that is working correctly and doesn't need to be changed.

You are also not able to send PMs to the player you've blocked. That's also the desired behaviour, however in that situation you currently also see the `notAuthorizedToSendMessageToThisUser` error, which is not correct. The error that you should see should say something like:
"You can't send a message to this player because you have blocked them from sending messages to you."

_Thanks to EliotThe for finding and reporting this._

**Comment by tsukimi2** [comment]
Hi, can I try working on this issue?

**Comment by akmaekki** [comment]
I would like to work on this, cause I already have a similar issue.

**Comment by Alys** [comment]
@tsukimi2 I'm sorry for our late reply. Please go ahead! Comment here if you have questions.

@akmaekki I'm sorry, @tsukimi2 asked first. :) We should have marked this as in progress back then.

**Comment by Alys** [comment]
Just for the record, the same problem happens when sending a gem gift as @tsukimi2 [found here](https://github.com/HabitRPG/habitica/pull/11636#issuecomment-569502580) and is fixing (thanks!!)
