### ISSUE TITLE
NPCs should have NPC style on Display Name in chat, Hall, etc

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11617]
When [players who are also NPCs](https://habitica.fandom.com/wiki/Kickstarter#Non-Playing_Characters_.28NPCs.29) post to chat, their Display Names don't have the correct formatting for an NPC. You can see what the format should be by looking at Bailey's name in the "Staff and Moderators" list on the right-hand side of the [Tavern](https://habitica.com/groups/tavern). 

For an NPC who is also a contributor or moderator, the style should be the NPC style not the contributor/moderator style. 
An NPC who is not a contributor should of course have the NPC style not the default black name.

The fix to apply the NPC style should be applied in all the places where the contributor/moderator style is applied.

There's already some support in the code for this but it's not working (I haven't looked into why):
https://github.com/HabitRPG/habitica/blob/develop/website/client/src/mixins/styleHelper.js

~Note that currently I'm only assuming that we want a fix for this issue. Name styles used to work as I've described and I'm guessing that removing the NPC stye was accidental, since the NPC players paid a lot in the original kickstarter to be an NPC.~
~I'll leave this issue as suggestion-discussion for a few days so that staff can comment on it if they wish to. If it's intentional that the NPC style should no longer be used, then we should change the formatting on Bailey's name on the Tavern sidebar, and probably also remove any outdated code related to applying NPC styling (e.g., in the file I linked to above).~

~If there's no objections after a few days, I'll change this to help wanted.~
I'll also make a similar issue in the Android repo since the same problem exists there. EDIT: https://github.com/HabitRPG/habitica-android/issues/1254
Thanks to cTheDragons for reporting this for both platforms. We might need a similar issue for iOS too.

Any blacksmith who works on this after (if) it's marked as help wanted can make a test account on their local install be an NPC by adding this to it:

```
    "backer": {
        "npc": "NPC Title",
        "tier": 800,
        "tokensApplied": true,
    }
```
When you post a chat message with that account, you'll see the name is the default black -  it should have the NPC styling.

You can make the NPC also be a moderator by adding this to the account:
```
    "contributor": {
        "text": "Moderator Title",
        "admin": true,
        "level": 8,
    },
```
The name should still have the NPC styling after that change.

**Comment by tsukimi2** [comment]
@Alys Is it alright if I take a try at this issue?

**Comment by Alys** [comment]
@tsukimi2 Yes, thanks! Please go ahead.
