### ISSUE TITLE
"Click the paw print to hatch" appears even when the icon is not a paw print

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11613]
> @Cleminou (2153e659-6b03-4dbd-b0a3-281b4e29c537): "I'm not sure if this is the good place to mention it, but I just noticed that in the stable, when trying to hatch a pet for an already unlocked mount, the text 'Click the paw print to hatch' appears even if the icon is an hatching potion with an egg."

It's correct that this appears and might be a bit confusing.

**Comment by Alys** [comment]
I've marked this as suggestion-discussion for the staff to say what wording should be used for when the icon isn't a paw print.

**Comment by veeeeeee** [comment]
"Click to hatch!" is probably sufficient for now.

**Comment by oakypokey** [comment]
Hi, looking for a first contribution to an open source project to get into it-- can I help with this issue?

**Comment by Alys** [comment]
@oakypokey Yes, thank you! Comment here if you have questions or run into trouble.
