### ISSUE TITLE
Kickstarter 2019 achievement removed from account

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11616]
@a_diamond (eb5f51e6-cd0a-4590-b20c-5322bff97cc0) reported that they lost their 2019 Kickstarter achievement (`achievements.kickstarter2019`). They own 2019 Kickstarter equipment so they certainly should have the achievement and I've given it back to them.

From what they've said, it looks like they had been given it in the past but then lost it for unknown reasons. As described below, potential reasons seem to not include being given a contributor tier and not from an accidental change by me or another admin while fixing some other problem.

I'm marking this as needs investigation, and setting it to minor priority since it might have been a one-time glitch. If we see any other reports, we should add them here and then probably increase the priority.

---

Here's our posts about it from the Report a Bug guild:

@a_diamond: "I just got a contributor achievement, but somehow it seems that it lost my 2019 pin Kickstarter achievement."

@alys: "I've stepped through the contributor achievement award process on a test account that had the Kickstarter achievement and the achievement wasn't lost, so fortunately there isn't a code bug causing this for everyone! Can you tell me roughly when was the most recent time you saw the achievement in your account? Have Habitica's staff or moderators made any special fixes to your account for any reason since you last recall having the achievement or since the Kickstarter ended?"

@a_diamond: "Now that you mention it, I guess I haven't specifically looked for it since early October. I know for sure it was there when the other digital rewards went out, but I can't remember whether or not it was there more recently. As far as I know, there haven't been any other changes or fixes to my account between then and now."

**Comment by CuriousMagpie** [comment]
Closing because this seems to have been a one time glitch.
