### ISSUE TITLE
on-hover state of Tier 3 and Tier 5 display names in group chats should not include a colour change

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11633]
As reported by @EliotThe (0d77107e-9128-4656-8c02-6e06331fa396):

"On the website, when I mouse over Tier 3 and Tier 5 players' names in chat, they turn blue. It's the same blue that everyone's names turned during that sitewide bug a couple months back. ... It's only happening with tiers 3 and 5"

There was a similar bug last month: https://github.com/HabitRPG/habitica/issues/11503
but it was fixed. I don't know if this is related but the fix for that _might_ give pointers about how to fix this one.

**Comment by nikonhub** [comment]
Hello.

Sorry I didn't ask to work on this one. But I checked the issue and it seemed a very quick fix.

**Comment by Alys** [comment]
@Nikosmonaut no worries, thanks for posting to tell us and for the pr! I'm marking this as in progress.
