### ISSUE TITLE
Multiple joining in a Party

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1163]
Hello, 
I have invited a friend in a party. He clicked 4 times on the "Accept" button (yeah I know that's stupid :), and now he appears 4 times in the party. The page didn't had the time to refresh so he could click multiple times. 

![image](https://f.cloud.github.com/assets/4671953/638120/8db558b2-d2b4-11e2-850d-69f88ca70ede.png)

I guess that could be fixed easily 
1) if the Accept button shows once
2) if there is a verification in the members of a party so an id can't appear multiple times.

**Comment by MllePandaRoux** [comment]
NB : On his side, only him and me appear.

**Comment by lefnire** [comment]
actually a model.push/model.unshift duplicates bug, solved in racer 0.5 upgrade (in progress). The "join" action will test first if he's already in a party, which will show true after the first click, so i don't think his multi-click is what did it. 

In the mean time, chat in your party - it's a strange workaround i added for removing dupes in both chat and party-member entries

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
