### ISSUE TITLE
How can I delete messages in my guild?

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#1165]
A user accidentally (or maybe due to a glitch) posted the same exact message five times, this has cluttered my guild message history and I need a way to, as an admin, moderate the message log. Or in the meantime, can a site admin join my guild to delete the duplicated message?

**Comment by lefnire** [comment]
Very strang the workaround : say something in chat, it removes dupes. You
can the remove your own message

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
