### ISSUE TITLE
Webhook for quest invitation

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#11682]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API) 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Currently there is no webhook for quest invitation. Quest invitation also does not post any message to party chat (that could be detected with the `groupChatReceived` webhook). So currently the only way to programmatically handle quest invitations is to poll user data for the `RSVPNeeded` flag etc. 

There already seems to be a webhook type `questActivity` that is triggered on quest start and finish. So could we add one more trigger to that webhook for quest invitation? 

I think many people are using auto join scripts that are polling Habitica every hour (for example this one https://habitica.fandom.com/wiki/Google_Apps_Script#Auto_Accept_Quests), some parties even require all members to set it up. With this webhook we could achieve similar thing without any polling and thus reduce server load. Is there any specific reason this does not exist yet? Also wondering why quest invitation does not post any message to party chat?

I am willing to work on this myself if you think it would be useful.

**Comment by Alys** [comment]
@cvuorinen I've checked with Habitica's staff and they're happy for this to go ahead, so you're welcome to work on it - thank you! I've marked it as in progress for you, but if this has come in too late (e.g., if you've become involved in other work in the past week), tell us and we'll set it to help wanted.

**Comment by cvuorinen** [comment]
@Alys ok, I'll start looking into this.
