### ISSUE TITLE
equipment shows on avatar with Snowball transformation buff

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11684]
When you have the Snowball buff cast on you, your equipment shows. 
The correct behaviour is that your armor, back, body, eyewear, head, headAccessory, shield, and weapon items should not appear while the buff is in place.

This was observed on a Healer with `preferences.costume` set to true (screenshot below from @cvuorinen / @Squall_ / fa756acf-9127-4a3c-8dac-8ff627d30073) and on a Mage with  `preferences.costume` set to false (me, d904bd62-da08-416b-a816-ba797c9ee265).

When I tested briefly, the same bug did not occur for the other three avatar transformation buffs, but it wouldn't hurt to have a more thorough test done for those buffs too when a fix for this issue is being tested.

Note that the "Accent" items (flowers, earrings) SHOULD still appear on the avatar because that creates some cute effects (e.g., a flower makes a Shiny Seed avatar look like it's winking). 

![image](https://user-images.githubusercontent.com/1495809/71636148-10562480-2c78-11ea-8afe-67518bd3d5ac.png)

_Thanks to @cvuorinen for reporting this!_

**Comment by Alys** [comment]
So apparently this isn't a bug. The staff have just told me that class-specific equipment is meant to show up on Snowball avatars now. I'm closing this.

**Comment by SabreCat** [comment]
Working as intended, hehe. ⛄️ Now, in a similar fashion to the Shiny Seeds transformation that turns you into a differently colored flower based on your class, the Snowball transformation includes some class-specific decoration. You won't see your actual current equipment, just a class-specific iconic set.
