### ISSUE TITLE
cannot buy multiple gift subscriptions using Amazon

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11681]
If you try to buy more than one gift subscription using the Amazon payment method, the second, third, etc attempts fail.

Steps to reproduce:
1. Buy a one-month gift subscription for one player using the Amazon payment method. Observe that it succeeds.
2. Click on another player's profile, click the gift icon, select the one month subscription option.
3. Click the "amazon pay" button.
4. Observe that you see the error message in the screenshot below. 

Here's an error from Loggly from one of my attempts: https://habitica.loggly.com/search#terms=d904bd62-da08-416b-a816-ba797c9ee265&from=2019-12-01T00:00:00.000Z&until=2019-12-31T00:30:06.118Z&source_group=&event=9d415420-2b64-11ea-806a-12c72a2782d6,1577752172206,137970449723249696

```
{"billingAgreementId":"B01-9409592-7414448"},"httpCode":500,"isHandledError":false,
"fullError":{"type":"OrderReferenceCountExceeded",
"name":"OrderReferenceCountExceeded",
"body":{"ErrorResponse":{"$":{"xmlns":"http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01"},
"Error":{"Type":"Sender",
"Code":"OrderReferenceCountExceeded",
"Message":"The number of Order References that could be created on a DRAFT Billing Agreement has exceeded the maximum allowed limit of one Order Reference."},
"RequestId":"df7827aa-3d1c-4ade-b809-6e58523ff59f"}}}
```

Reloading the website does not help. 
Using Habitica's [clear browser data](https://habitica.com/static/clear-browser-data) button does not help.
The same error still occurs after both of those actions.

Using your browser's option to clear all data for all sites does fix the problem - you can then use Amazon Pay to buy the second susbcription. I have not done any more detailed tests to work out exactly which data it is that needed to be clear, but I'm guessing it's a Habitica cookie that relates to Amazon.

Using a different browser for the second subscription also works so it's definitely related to data stored in your browser.

![image](https://user-images.githubusercontent.com/1495809/71606273-3ff32700-2bbb-11ea-9de9-2bbbf71273e3.png)

_Thanks to @EliotThe (0d77107e-9128-4656-8c02-6e06331fa396) for reporting this!_

**Comment by ianrandmckenzie** [comment]
Hey @Alys — if no one picks up this issue after I finish #11827 I'd like to add this to my task queue. I'm on vacation next week and my chosen form of relaxation is to contribute to open source. My goal is to resolve 4 or more Habitica issues. Thanks!

**Comment by Alys** [comment]
@ianrandmckenzie Thanks! I've marked this as in progress for you.

**Comment by Alys** [comment]
@ianrandmckenzie Although there have been changes to Habitica's subscription code lately so it's possible this error no longer occurs. @negue @paglias @SabreCat Do you know if it's been fixed?

**Comment by paglias** [comment]
As far as I know this issue hasn't been fixed

**Comment by Alys** [comment]
@ianrandmckenzie Please go ahead if you're still interested and post here if you have questions or run into trouble!
Since it's been a few days though, if you've decided that you no longer have time to work on this one, that's fine, just let us know and we'll change it back to help wanted.

**Comment by ianrandmckenzie** [comment]
Hey @Alys, I think I'll have time on Friday to work on this. If you're willing to wait until then, I will let you know if I get around to it. My work can get spikes of needing my attention, though, so if you don't hear from me by Saturday feel free to add the help wanted tag back. 

Either way, I'll try to keep you updated with my availability.

**Comment by ianrandmckenzie** [comment]
I'm sorry, I wasn't able to keep up with my week. I won't be able to do this. I'll check back in a couple of weeks when (hopefully) things cool down. @Alys

**Comment by Alys** [comment]
@ianrandmckenzie No worries. :) Thanks very much for letting us know! I've labelled this as help wanted.

**Comment by fmaximus** [comment]
@Alys Before promising I can fix it, I would like to take a look into why it's reusing the same Billing Agreement.
Can you (create and) share an Amazon Sandbox account I can use on my local deployment.
