### ISSUE TITLE
inconsistent notification dismissal for Cards (greetings, birthday, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11688]
If two or more players each send you the same kind of card (e.g., if you have three Birthday cards), you have a notification for each of them (see the screenshot below). That's correct behaviour so far.

There's two ways that you can get to the cards and remove the notifications.

### First way:
1. You click on one notification. **That one notification immediately disappears**; the other notification(s) remain.
2. You're taken to Inventory > Items where you can see the cards.
3. You click on one card and read it.
4. You click the OK button on the card to close it. **A second notification disappears**.

I.e., if you were sent three cards, you've now read only one card but you have only one notification left. That's incorrect; you should have two notifications left.

### Second way:
1. You go directly to the Inventory > Items screen, without going through the notification menu. All notifications are still there (that's correct behaviour).
2. You click on one card and read it.
3. You click the OK button on the card to close it. **A notification disappears**. 

I.e., if you were sent three cards, you've now read one card and you have two notifications left. That's correct behaviour for this way.

Both ways are legitimate paths for the user to take so the dismissal of the notifications should work equally well for each method. The behaviour for the second way is currently correct. The behaviour for the first way is wrong because there are two notification dismissal events when there should be just one dismissal event.

I suggest that the best way to fix this is to prevent the card notifications dismissing themselves when you click on them. I'll leave this as suggestion-discussion for a few days then if there's no objections I'll mark it as help wanted for this fix.

Note that regardless of what changes are made for this issue, the card notifications SHOULD still be dismissed if you click the "x" button on the right-hand side or if you click the "Dismiss All" link.

![image](https://user-images.githubusercontent.com/1495809/71760644-81156f00-2f0c-11ea-8059-5673188553f8.png)

_Thanks to cTheDragons for reporting this._

**Comment by Kevin-DDR** [comment]
Would it be too early to ask permission to work on this? This seems like a pretty good first issue for aspiring Blacksmiths (such as myself)

**Comment by Alys** [comment]
@Kevin-DDR Sorry, I forgot to set labels on this! It's marked now as suggestion-discussion while we wait to see if anyone, especially Habitica's staff, have any objections to my proposed fix or any better ideas. If there's been no objections in a few days, it will be available to be worked on. We'll check with you then to see if you're still interested. Thanks for asking about it!

**Comment by Alys** [comment]
Ah, I see you've made a PR already. :)

**Comment by Kevin-DDR** [comment]
Sorry, I probably should have waited for a reply before working on it ^^'
