### ISSUE TITLE
Clear complete to-do : half of my current todo went into the complete list

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1169]
Hello, 
since I have a long complete to-do, I decided to clean it. It did erase the list, but it also cut the current to-do in half and put the lower half in the complete list. I had 15 todos, 7 still in my current todo and 8 in my complete todo. 

I'm trying to tick the complete to-do so my tasks can come back in the current one, but it doesn't work. It says it takes xp and gold, but it doesn't actually, and the task doesn't move. 

(then I refreshed the page and the old complete todo is back, and my current todo is normal. Pheww. )

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
