### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by mleon246** [HabitRPG/habitica#117]
I can't register because my name/emails are "taken".
When I try password recovery it says my email isn't registered.

could the Facebook login have anything to do with it?

i've recently been trying to remove my dependency from Facebook and would like to use HabitRpg without it.

**Comment by StanLindsey** [comment]
Are these issues still occurring? Can you re-register or does it say the user already exists? 

It might simply be bad timing as HabitRPG has had stability issues recently which are now 99% fixed and your user might need to be manually deleted.

**Comment by mleon246** [comment]
Its working for me now... thanks for checking on it.
