### ISSUE TITLE
purchases of Mystery Items equipment sets recorded twice/more in Amplitude

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11705]
When you buy a Mystery Item set using an Hourglass, the purchase is recorded in Amplitude once for each piece of gear in the set.

The desired behaviour is that there should be one Amplitude record for each Mystery Item set.

Here's an example:

Event Properties:
acquireMethod Hourglass
category behavior
itemKey back_mystery_202001
itemName Five Tails of Fable
itemType Subscriber Gear
Other:
Client Event Time Jan 9, 12:10:45 am UTC

Event Properties:
acquireMethod Hourglass
category behavior
itemKey head_mystery_202001
itemName Fabled Fox Ears
itemType Subscriber Gear
Other:
Client Event Time Jan 9, 12:10:45 am UTC

~I'm making this suggestion-discussion for the staff to comment on what data should be in the combined record. E.g., should it contain the itemKeys for all the items, or just the year-month for the set? Are the names of all the items needed, or just the name of the set?~

EDIT: See comment from veeeeeee below for more details

**Comment by Alys** [comment]
Here's an example:

Event Properties:
acquireMethod Hourglass
category behavior
itemKey back_mystery_202001
itemName Five Tails of Fable
itemType Subscriber Gear
Other:
Client Event Time Jan 9, 12:10:45 am UTC


Event Properties:
acquireMethod Hourglass
category behavior
itemKey head_mystery_202001
itemName Fabled Fox Ears
itemType Subscriber Gear
Other:
Client Event Time Jan 9, 12:10:45 am UTC

I'm making this suggestion-discussion for the staff to comment on what data should be in the combined record. E.g., should it contain the itemKeys for all the items, or just the year-month for the set? Are the names of all the items needed, or just the name of the set?

**Comment by Alys** [comment]
In case anyone's curious, here are the Mystery Sets that contain more than two items (this is not relevant for a fix for this issue, just something I was looking at when wondering how much this issue would affect statistics):
      2014-02 - 3
      2018-02 - 3
      2019-07 - 3
      3017-03 - 3
      3017-04 - 3
      3014-04 - 4
      3014-05 - 4

**Comment by veeeeeee** [comment]
Year-month of the set is all we really need for Amplitude purposes. Thanks!
