### ISSUE TITLE
default Backgrounds tab should be 2020

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11703]
_As reported by @loremi (64d5d2fa-4ab1-4ff2-bc93-e46a18d44b25):_

When clicking on the "Backgrounds" menu in the web version, it defaults to displaying the 2019 backgrounds instead of the 2020 ones.

**Comment by Kevin-DDR** [comment]
I'd love to work on this one if no other aspiring Blacksmith wants it !

**Comment by Alys** [comment]
@Kevin-DDR Thanks! Please go ahead! Post here if you have questions.
