### ISSUE TITLE
contributor tier color/icon should appear in guild/challenge member/participant list

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11736]
When you click on the "Member List" badge for a guild/party or the "Participants" list for a challenge, all player's names are grey, regardless of their contributor tier.

The desired behaviour is that each player's name should be formatted with the same colour and icon that appears on posts made by the player.

**Comment by Kevin-DDR** [comment]
I would like to try my hand at this If that's okay with everyone!

**Comment by paglias** [comment]
Sure @Kevin-DDR , go ahead!
