### ISSUE TITLE
Allocating 100 stat points to one stat causes text to overflow from the box

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11738]
![image](https://user-images.githubusercontent.com/8144640/72617748-91c4dc80-3931-11ea-9bfb-e07d5588d626.png)

> Not so much a bug as it is a formatting issue, but I just noticed when I reached level 100 (woo!) and put my 100th stat point into intelligence, that the "pts" text after the number 100 gets pushed out of the box and moved underneath it. I assume this is because the number has become three digits and the entire "100 pts" text doesn't fit in the box.

Reported by JohnJSal in Report a Bug.

**Comment by Alys** [comment]
I'm labelling this as "neds design" in case @Tressley wants to comment but if there's no objection in a week, I'll change it to help wanted for expanding the Stat Points boxes slightly to accommodate three-digit numbers and slightly longer "pts" labels that might exist in other languages.

**Comment by wScottSh** [comment]
If no one objects, I can tackle this one.

I'm going through the contributing docs right now. I'll post if I have any questions.

**Comment by Alys** [comment]
@wScottSh Thank you! Please go ahead!

**Comment by Tressley** [comment]
@wScottSh -- Thanks for taking this on! Here are some quick changes:
- Update the label from "pts" to "points"
- The boxes should be wide enough to have 24px of space between them. As you can see in Shanaqui's screenshot above, the Strength container isn't flush to the left margin of "Stat Points" heading.

**Comment by wScottSh** [comment]
Sure thing.

**Comment by wScottSh** [comment]
I've made it through the docs, but haven't yet set up my environment. I'll have time this weekend to do so. Just keeping you in the loop.

**Comment by shanaqui** [comment]
@wScottSh Hi! Are you still interested in working on this one? Please let us know if so!

**Comment by wScottSh** [comment]
@shanaqui Thanks for checking in, I apologize for not closing this loop earlier.

No, now is not the time for me to take this on. Family has been in the hospital and I haven't had the cycles dedicated to getting the environment working properly. Feel free to open it back up.

**Comment by shanaqui** [comment]
Thanks for updating! I'll mark it as help wanted.

**Comment by inftp** [comment]
Hi there,
Can I try this one?

**Comment by Alys** [comment]
@inftp Sure, thank you! Post here if you have questions or run into trouble.
