### ISSUE TITLE
member list should update when viewing different guilds

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11737]
If you visit a guild and click on its "Member List" badge, you see a list of the guild's members. If you then immediately visit a different guild and click on its badge, you see the SAME list - i.e., the list for the first guild. You have to reload the website to see the second guild's member list.

The desired behaviour is that a reload should not be necessary.

**Comment by tsukimi2** [comment]
@Alys Is it ok if I take a look at this issue?

**Comment by Alys** [comment]
@tsukimi2 Please do, thank you! Post here if you have questions.

**Comment by tsukimi2** [comment]
@Alys Hi, need some help in reproducing the bug.  I tried to reproduce the steps mentioned in the issue  but was not able to observe the bug.  Could you provide more detail about how to reproduce it? Thanks. The steps I tried is as follow:

Step 1:
Click on member list badge of guild Crimson Vow
![Screenshot from 2020-01-15 18-46-16](https://user-images.githubusercontent.com/3499949/72428382-84d8a980-37c8-11ea-8786-90ae14844ae5.png)

Step 2: (Member list of guild Crimson Vow)
![Screenshot from 2020-01-15 18-56-08](https://user-images.githubusercontent.com/3499949/72428587-fd3f6a80-37c8-11ea-9b53-2922c48ff0e9.png)

Step 3: 
Click on My Guilds, then click on the guild Log Horizon
![Screenshot from 2020-01-15 18-59-59](https://user-images.githubusercontent.com/3499949/72428721-3ed01580-37c9-11ea-96b1-410a0dc64eaa.png)

Step 4:
Then click on the member list badge
![Screenshot from 2020-01-15 19-00-41](https://user-images.githubusercontent.com/3499949/72428781-5909f380-37c9-11ea-808f-988b262fdb15.png)

Step 5:
![Screenshot from 2020-01-15 19-01-11](https://user-images.githubusercontent.com/3499949/72428815-6cb55a00-37c9-11ea-9660-1ab0e0709ed6.png)

**Comment by Alys** [comment]
That's exactly the steps I took to reproduce the issue. Looks like it's an intermittent bug. :( I'll try to make time on the weekend to do a bit more experimenting.

Firefox on Ubuntu in case that's relevant.

**Comment by Alys** [comment]
I can reproduce this bug every time with this process:

1. go to Tasks page
1. reload website (to clear out any cached guild membership data)
1. click on your notifications and click on the new message notification for one guild
1. observe that you're taken to that guild's page - ensure it has loaded fully before going further
1. click on the member list icon
1. make note of the first few members in the list
1. click on your notifications and click on the new message notification for a different guild
1. observe that you're taken to that guild's page - ensure it has loaded fully before going further
1. click on the member list icon
1. observe that you see the same members as for the previous guild
1. reload the page
1. click on the member list icon
1. observe that the list now shows the correct players
