### ISSUE TITLE
Bug when hatching multiple pets

### ISSUE THREAD

**Issue by weelillad** [HabitRPG/habitica#1174]
This bug appears when I have multiple eggs to hatch, and enough potions to hatch them all. Only the last hatched pet appears in the stable. A browser refresh restored all my eggs and potions, thankfully.
1. I had 2 eggs in my inventory, and >2 hatchiing potions.
2. I clicked on one of the eggs, selected the potion I wanted to use, and clicked Hatch.
3. The alert that I have a new pet appeared. I clicked to dismiss it.
4. I navigated to the Stable.
5. The pet that just hatched is present in the Stable.
6. On the inventory screen, the dropdown box to select a potion is still there, only this time it's prompting me to select a potion for my second egg. (I did not have to click on the second egg for the dropdown box to re-appear)
7. I selected the desired potion, and clicked Hatch.
8. The alert that I have a new pet appeared. I clicked to dismiss it.
9. I navigated to the Stable.
10. The pet that just hatched is present in the Stable. However, now the first hatched pet is missing. Both eggs and hatching potions used are no longer in my inventory.
11. I refreshed the browser, and found that my 2 eggs and 2 potions are back, while the new pets are gone from my stable. Effectively a rollback to step 1.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
