### ISSUE TITLE
incorrect avatar shown after sending private message (PM) in inbox

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11740]
_As reported by @cTheDragons with minor edits:_

On the website in the new messaging area when I send a message to a player, my avatar shows not as I am now but as I was before in my last message.

If I leave and go back the avatar is then correct as I sent the message.

Steps to Reproduce, 
+ Send a message to someone.
+ Exit the message screen change your Avatar's costume.
+ Send another message to the same person in the first step.

The avatar of you will be displayed the same as the last image not the image currently.

The expected behaviour is that as soon as you send the message, the avatar you see next to the message is your current avatar.

**Comment by youcandanch** [comment]
I'll take a stab at this.

**Comment by Alys** [comment]
@youcandanch Thanks! Please go ahead and post here if you have questions.

**Comment by shanaqui** [comment]
Hi @youcandanch! Are you still working on this one? Please let us know!

**Comment by Tressley** [comment]
This has been fixed in #11766. Private messages will now only display the user’s current avatar.
