### ISSUE TITLE
Disappearing pets

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1175]
Weird potion/egg issue tonight. This may well be a duplicate of any of the other disappearing egg/potion/pet issues, but I can't tell. 
1. Checked off one of my dailies, got a tiger egg 
2. Hatched the tiger egg with a cotton candy blue potion. Viewed the tiger in my stable.
3. Checked off another daily, got another tiger egg drop message.
4. Went back to my inventory. It was already on the "what potion do you want to pour on your tiger egg" prompt. 
5. Chose a skeleton potion. 
6. Went to my stable. The skeleton tiger was there, but the blue tiger was gone. The blue potion was not returned to my inventory. 
7. Reloaded the page. The two dailies were no longer checked off, there were zero tiger eggs in my inventory, and neither the blue nor the skeleton tiger was in my stable. Both the skeleton and the cotton candy blue potion were back in my inventory. 
8. Checked off the two dailies again. No more tiger eggs (though I did get a white potion). 
9. Reload the page. The two dailies are still checked off, white potion still in my inventory.

This is at least not the same as #1174, since I didn't get the eggs back.

**Comment by wc8** [comment]
Related to #988

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
