### ISSUE TITLE
challenge bugs when owner/leader deletes their account

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11768]
When a challenge owner deletes their Habitica account, any challenges they own have these problems:

1. In the "My Challenges" and "Discover Challenges" pages, the "Created By" field is blank. The first screenshot below shows an example of this problem in the "Test Challenge - don't join" challenge.
It should say "no owner" as decided [here](https://github.com/HabitRPG/habitica/issues/5979#issuecomment-151280530). A translatable string already exists for this and should be used instead of creating a new one:
`challenge.json:  "noChallengeOwner": "no owner",`

2. In the challenge's own page, the tasks are invisible. This is because when the challenge page is loading, there are errors when fetching data about the owner (you can see the errors in the javascript console), and (I assume) this prevents the page from displaying all of the challenge's other data.
The desired behaviour is that the challenge page should recognise that there's no owner and handle that gracefully instead of throwiing errors. The "Created By" field should say "no owner" and the tasks should appear as normal.
You can see this error displayed in the second and third screenshots below. The second screenshot is a test challenge that has me as the owner. The third screenshot is the same challenge after I have changed the owner to a User ID that is not in use (i.e., that mimics the case of the challenge owner deleting their account).
The test challenge is available here: https://habitica.com/challenges/f21ad727-3d0d-47c5-a5a3-e6311aa1e3e6

![image](https://user-images.githubusercontent.com/1495809/73132263-7f028400-4064-11ea-81f4-98531620b166.png)

![image](https://user-images.githubusercontent.com/1495809/73132251-5d090180-4064-11ea-8e77-458c3bc56140.png)

![image](https://user-images.githubusercontent.com/1495809/73132249-5a0e1100-4064-11ea-8d18-4a62c163605e.png)

**Comment by SpeedyLom** [comment]
I wouldn't mind giving this one a go, it looks like a good first issue.

I'm not at the PC at the moment; but from having a quick poke around earlier doing the following should fix it:
- Add a couple of `null` checks in `tasks.js` would allow the page to load
- Update `userLink.vue::displayName()` to return the `noChallengeOwner` string instead of `null`

**Comment by Alys** [comment]
@tthorpe88 Thanks! Please go ahead and comment here if you have questions.

If you'd like to be sure that the staff approve of your suggested approach, you might like to wait a couple of days to see if they add any comments here.

**Comment by SpeedyLom** [comment]
Cool, I don't mind waiting for confirmation/suggestions before starting since this is the first time working on the code 😁

**Comment by SpeedyLom** [comment]
Since there haven't been any updates to this I'll get started on it as soon as possible (probably the weekend).
