### ISSUE TITLE
About the HabitRPG survey in May

### ISSUE THREAD

**Issue by Weenyah** [HabitRPG/habitica#1177]
Hi there,

I found from Tumblr's habitrpg tag + the inn's helpful users that the survey rewards should had been already sent. I filled the survey and I'm quite sure my browser sent the information since refreshing the article just said I had already filled out the survey.
My user name is Weenyah, user ID 6e2c0df4-af45-4ff3-91b1-c3590a420b67, and Api Token is [redacted by @switz]. My avatar is currently on the level 20.
Thanks for your time, and sorry for the bother!

Cheers, Weenyah

**Comment by switz** [comment]
Please don't share your API token publicly! It allows anyone to manipulate your account.

**Comment by lefnire** [comment]
you should be sorted now
