### ISSUE TITLE
colour tier names in website header might need more contrast

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11799]
This is for only the staging site at the moment (i.e., this doesn't happen in production yet).

The normal contributor tier / NPC colours are now being applied to the player's name in the header. For some tiers, there's not a lot of contrast between the name and the header's purple background. For others, the contrast seems fine to my eyes but the colours don't always match well; I don't know if that's something worth considering.

I have not tested these for all the kinds of colour-blindness. That'll be important to test though because the contrast issues are more likely to be worse there.

I'm marking this as suggestion-discussion.

NPCs such as Bailey:
![image](https://user-images.githubusercontent.com/1495809/73592737-06f6fb00-4549-11ea-94c0-8380d4810235.png)

Staff members:
![image](https://user-images.githubusercontent.com/1495809/73592832-43772680-454a-11ea-94c1-d5657565a059.png)

Moderators:
![image](https://user-images.githubusercontent.com/1495809/73592848-6b668a00-454a-11ea-82c2-2df1b3a5ccf1.png)

Other tier levels as shown in the Display Names:
![image](https://user-images.githubusercontent.com/1495809/73592884-c7c9a980-454a-11ea-8acb-bcb414ffe992.png)

![image](https://user-images.githubusercontent.com/1495809/73592892-e16af100-454a-11ea-8a0c-035237fcf6a9.png)

![image](https://user-images.githubusercontent.com/1495809/73592899-f6478480-454a-11ea-87a7-c19f0ef72f3b.png)

![image](https://user-images.githubusercontent.com/1495809/73592905-0b241800-454b-11ea-8462-d682c6af3afa.png)

![image](https://user-images.githubusercontent.com/1495809/73592908-1d05bb00-454b-11ea-90ed-037a4c02c7f6.png)

![image](https://user-images.githubusercontent.com/1495809/73592914-2bec6d80-454b-11ea-964c-cf158093dd76.png)

![image](https://user-images.githubusercontent.com/1495809/73592918-3e66a700-454b-11ea-9161-f59ca0f443a8.png)

![image](https://user-images.githubusercontent.com/1495809/73592927-576f5800-454b-11ea-82cc-603abb3005d3.png)

Also currently on staging any backer from the original Kickstarter will have the black name in the header as for NPCs but that will be fixed as soon as https://github.com/HabitRPG/habitica/pull/11797 is merged.

**Comment by paglias** [comment]
@Tressley

**Comment by paglias** [comment]
Nevermind, my fault here, fixed in https://github.com/HabitRPG/habitica/commit/ad3b673fdac4b6f03b65bd8701c33bcb99a41af9

It was definitely a side effect of a PR that wasn't meant to change the header
