### ISSUE TITLE
some Premium and Wacky Hatching Potions have errors in _addlNotes data

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11794]
This bug can be seen when you use the API to fetch Habitica's `content` data with this command this:
```
curl -X GET 'https://habitica.com/api/v3/content?language=en'
```

For some items, such as the Royal Purple Hatching Potion, you'll see the error shown below in the `_addlNotes` (additional notes) data:

```
"premiumHatchingPotions": {
	"RoyalPurple": {
		"value":2,
		"text":"Royal Purple",
		"limited":true,
		"key":"RoyalPurple",
		"notes":"Pour this on an egg,
		 and it will hatch as a Royal Purple pet.",
		"_addlNotes":"Available for purchase until String 'dateEndundefined' not found..",
		"premium":true
	},
```

That error should not be there.

Below is some of the code related to this issue.

https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/common/locales/en/limited.json#L153

https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/common/script/content/hatching-potions.js#L268-L303

https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/common/script/libs/getItemInfo.js#L85-L97

This seems to be the offending code:
```
    _addlNotes: t('eventAvailability', {
      date: t(`dateEnd${pot._season}`),
    }),
```
```
	notes: `${item.notes(language)} ${item._addlNotes(language)}`,
```

`pot._season` is not always defined. When it doesn't have a value, `_addlNotes` shouldn't be populated.
When `_addlNotes` doesn't have a value, the `notes` attribute shouldn't be populated.

**Comment by MynahMarie** [comment]
Hi! I'm a new contributor but I'd like to have a try at solving this issue. Let me know if that's ok 😃

**Comment by Alys** [comment]
@MynahMarie Sure, thank you! Please go ahead and post here if you have any questions.
