### ISSUE TITLE
Lost focus when typing in guild chat causes browser "back" when using backspace.

### ISSUE THREAD

**Issue by zoebeagle** [HabitRPG/habitica#1179]
I was typing in guild chat (not party chat) this evening on three different occasions.  My fingers sometimes move faster than my brain, so I use the backspace key to correct mistakes (who doesn't, right?).

Anyway, I was typing in group chat and after typing a few words and pressing backspace a few times to clear my misspelled word, I suddenly am sent to the "New Tab" page in Chrome.  It was acting like the page was refreshing as I was typing in chat.  This last time, however, I made sure the page was completely loaded before I starting typing, and I still got booted out.  I verified this is what's happening because I can look at the "forward" history for my New Tab page and can see that HabitRPG is the only thing there.

I don't recall having this problem before but the guild chat is relatively new so it could be embedded in there.  I haven't this issue in party chat so far, only guild chat.

Info:
Windows 7 x64
Chrome Version 27.0.1453.110 m
User ID: e09e3b3c-a2ac-4a01-ab6e-739e83c79115

If I can provide any other useful info, please let me know!

**Comment by lefnire** [comment]
same problem indeed. see commit message of https://github.com/lefnire/habitrpg/commit/268157ca246280aace22dff949367691d7db96d6 if you're interested, I roughly know what's going on here but having trouble working around the private path restrictions

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
