### ISSUE TITLE
inconsistent user count on home page

### ISSUE THREAD

**Issue by mayajosyula** [HabitRPG/habitica#11790]
Mentioned this in the Bug Guild and was told by Alys to create an issue.

The user count on the Habitica home page is inconsistent - at the top it says 3 million, but at the bottom it says 2 million. 

Top of page:

<img width="888" alt="habiticahometop" src="https://user-images.githubusercontent.com/10248632/73329639-3e953880-4213-11ea-9333-2ea16cb126ef.PNG">

Bottom of page: 

<img width="876" alt="habiticahomebottom" src="https://user-images.githubusercontent.com/10248632/73329649-4654dd00-4213-11ea-813d-f924603b8daf.PNG">

Pretty sure this is because the relevant line hard-codes in "2,000,000" instead of using the `userCountInMillions` variable. 

https://github.com/HabitRPG/habitica/blob/02d6b77a0364e16013862abb3cde0d51ecf412d7/website/common/locales/en/front.json#L324

**Comment by Alys** [comment]
@agentx999 Thanks very much!  Your assessment is correct. Both locations should be using the "over x million" phrasing.

However the number should be changed from 3 to 4. (Our current user count is 4 671 530.)

To any contributor wanting to work on this, I've marked it as good first issue - it should be a good introduction for any new Blacksmith. Here are some pointers to relevant code.

https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/client/src/components/static/home.vue#L292
https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/common/locales/en/front.json#L324
https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/client/src/components/static/home.vue#L24
https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/client/src/components/static/home.vue#L827

**Comment by neepsnikeep** [comment]
I'm looking into this

**Comment by Alys** [comment]
@neepsnikeep Thanks! I've marked it as in progress for you. Post here if you have questions.

**Comment by zlotte** [comment]
Was it fixed or I can fix it ? :)

**Comment by actuday6418** [comment]
Can I work on this? I'm new and need somewhere to start

**Comment by Alys** [comment]
@zlotte @actuday6418 : this issue is in progress. You might like to look for issues marked with the "help wanted" label.

If you see any in progress issues where the most recent comment is a few months old and there's no linked pull request, you can ask on them, but this one was claimed just a week ago. :)

**Comment by neepsnikeep** [comment]
I'm pretty much done with it, but have problems testing it. My test environment seems to be very unstable, so even if I revert my changes it doesn't build... I'm working on it.

**Comment by Alys** [comment]
@neepsnikeep How are you going with that? If you're still having trouble with your local install, let us know what errors you're seeing and we might be able to help.

**Comment by neepsnikeep** [comment]
Okay I figured out rebasing, this is quite neat. I was about to create a pull request for work in progress, but seem to be denied to do that?

I'm updating Docker right now as coincidentally one is available now. It's whining that it needs more space even if it has plenty, but all the fixes and workarounds that worked for others don't do it for me. `docker system prune` seemed very promising, but no. The mongodb setup keeps failing. After it succeeded once, I can test my code by just resetting the client as I have the command for that now. So it shouldn't be that much trouble next time.

I have this week left to figure it out.


My code changes are:

website/client/src/components/static/home.vue:
`userCountInMillions: 4,`
`{{ $t('joinMany', {userCountInMillions}) }}`

website/common/locales/en/front.json:
`"joinMany": "Join over <%= userCountInMillions %> million people having fun while accomplishing their goals!",`

**Comment by neepsnikeep** [comment]
FINALLY!! Ok it's working. Following the steps for the pull request now.

As frustrating as it was setting everything up, it's more satisfying than I thought to test my changes. I guess it's worth it doing more in the future :)

**Comment by joefessenden** [comment]
Is there a mechanism in the code somewhere that can easily get a live user count so this doesn't have to be manually set as the number grows?

**Comment by neepsnikeep** [comment]
Well sure I guess you can connect to the database and get an up to date user count, but the performance issues are not worth it in my opinion. It's not like you need to update the million user count every day. The home page loads sluggish enough, a minor thing like an automatic user count isn't worth making it more slowly. A responsive front page is essential for getting new users.

**Comment by joefessenden** [comment]
@neepsnikeep Totally agree. That's what I meant by "easy." Wasn't sure if it was already in the dataset somewhere. I'm still wrapping my head around the paths through the code and the way data is handled in the application.
Aside: If there's a guide to this to help me get up to speed, I'd be happy to hear it.

**Comment by Alys** [comment]
@joefessenden There isn't anything in the code for getting a live user count. We update it maybe once a year roughly so any automatic counting method isn't needed, and as @neepsnikeep says, the performance hit wouldn't be desirable. As for a guide, see [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API), and the pages it links to. It has a lot of information and details about where to ask questions.

BTW, I've deleted some of the older comments from this issue about it being in progress and one brief comment from @neepsnikeep saying that there were problems with the local install (now fixed).

**Comment by joefessenden** [comment]
@Alys No argument here. 

Thanks for the info. I will look again there. I didn't see much about the actual structure of the app.
