### ISSUE TITLE
notification and User Icon menus have wrong colours

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11800]
This is for only the staging site at the moment (i.e., this doesn't happen in production yet).

The colours in the Notifications menu and User Icon menu are off, as shown in the screenshots. The other menus (Inventory, etc) are still okay.

I'm marking this as suggestion-discussion for now because the staff might be doing a fix for it themselves. If not, it can be changed to help wanted.

![image](https://user-images.githubusercontent.com/1495809/73593144-4b37ca80-454c-11ea-9c37-ba2d29171a90.png)

![image](https://user-images.githubusercontent.com/1495809/73593146-57bc2300-454c-11ea-9426-795453df5596.png)

**Comment by paglias** [comment]
Fixed https://github.com/HabitRPG/habitica/pull/11708#issuecomment-581032606
