### ISSUE TITLE
cron should remove duplicates from pushDevices array

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11805]
When a player uses one of the mobile apps, an object describing their device is added to the `pushDevices` array in their User document. For example:
```
    "pushDevices": [
        {
            "regId": "erWWzAqL9Bw:APA91bEkvxR_bo1232148734487103471983479817349287ieROEjvT1cx5",
            "type": "android",
            "createdAt": "2018-12-18T09:12:51.415Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
    ]
```

Sometimes the data is duplicated (or triplicated, quadruplicated,...), which means that the player will received duplicate push notifications.

When cron runs, it should examine the `pushDevices` array and remove any duplicates.

I suggest that the code for this should go just before or just after this code:
https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/server/libs/cron.js#L482-L488
That's code is cron removing incorrect entries from the user's `tasksOrder` object, so it's a similar kind of clean-up.
Although you might want to put the pushDevices cleanup code into a function in that file and call it from there.

Note that it's possible for the `pushDevices` array to contain entries for different devices (e.g., if the player runs Habitica on a phone and a tablet), and that's legitimate. The entries for other devices shouldn't be removed. The `regId` field determines which device the entry is for. So, the `pushDevices` array should contain only one object per regId.

As an example, the cron cleanup code would convert this:

```
    "pushDevices": [
        {
            "regId": "erWWzAqL9Bw:APA91bEkvxR_bo1232148734487103471983479817349287ieROEjvT1cx5",
            "type": "android",
            "createdAt": "2018-12-18T09:12:51.415Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
        {
            "regId": "erWWzAqL9Bw:APA91bEkvxR_bo1232148734487103471983479817349287ieROEjvT1cx5",
            "type": "android",
            "createdAt": "2018-12-18T09:12:51.415Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
        {
            "regId": "erWWzAqL9Bw:APA91bEkvxR_bo1232148734487103471983479817349287ieROEjvT1cx5",
            "type": "android",
            "createdAt": "2018-12-18T09:12:51.415Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
        {
            "regId": "fr_5B_ezlkE:APA91bF4Rq1RlTalkdsjfkaksjdflkasdflskajdflskjfj87GyD_9zKNIKB-hcybmte37kw",
            "type": "android",
            "createdAt": "2019-01-12T23:50:24.531Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
        {
            "regId": "fr_5B_ezlkE:APA91bF4Rq1RlTalkdsjfkaksjdflkasdflskajdflskjfj87GyD_9zKNIKB-hcybmte37kw",
            "type": "android",
            "createdAt": "2019-01-12T23:50:24.531Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
    ]
```
to this:
```
    "pushDevices": [
        {
            "regId": "erWWzAqL9Bw:APA91bEkvxR_bo1232148734487103471983479817349287ieROEjvT1cx5",
            "type": "android",
            "createdAt": "2018-12-18T09:12:51.415Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
        {
            "regId": "fr_5B_ezlkE:APA91bF4Rq1RlTalkdsjfkaksjdflkasdflskajdflskjfj87GyD_9zKNIKB-hcybmte37kw",
            "type": "android",
            "createdAt": "2019-01-12T23:50:24.531Z",
            "updatedAt": "2020-02-02T07:57:28.447Z"
        },
    ]
```

If you think you'd like to work on this and I haven't explained that clearly enough, post a question here. :)

**Comment by xrem** [comment]
@Alys could you verify please?

**Comment by Alys** [comment]
@xrem I've marked this as in progress for you. Thanks!
