### ISSUE TITLE
add lastUpdated value and query parameter to API v3 content route

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11803]
_This issue is for API v3 but if API v4 is given a `content` route before this issue is fixed, then the change described here should be done for both v3 and v4. This adds a new feature to the route and so it's not a breaking change for API v3._

---

When you use the [content](https://habitica.com/apidoc/#api-Content-ContentGet) route with the API v3 command below, the returned data is very large.  This increases mobile app loading times when the app is opened. This issue is to minimise the impact from that.

curl -X GET 'https://habitica.com/api/v3/content?language=en'

The `content` route should be changed so that the data returned includes a new `lastUpdated` field at the top level of the data. I.e., the response would then look like this:
```
{
	"success": true,
	"data": {
		"lastUpdated":"2020-02-01T21:15:07.363Z",
		"achievements":{"dilatoryQuest":... }
		...
	}
}
```

The `content` route should be given a new, optional query parameter called `lastUpdated`, with the value being a datestamp:
- If that parameter is not supplied, the `content` route must work exactly as it does now.
- If the parameter is supplied and is a valid datestamp, the `content` route must compare the parameter with the content's current `lastUpdated` date:
   - If the parameter's date is indentical to the content's date, then the `content` route returns nothing. _(Or should it return a value that indicates there's no new content?)_
   - If the parameter's date is different to the content's date (either older or newer), then the `content` route returns the full content data (exactly as if the parameter had not been supplied).
- If the parameter is supplied but the value cannot be recognised as a valid datestamp, the content route must act as if the parameter was not supplied. ~~_(An alternative option is for the route to throw an error and not return any data, but since the content is essential to the smooth running of the apps, any small bug in the app that made the date invalid would cause the app to be completely unusable, so I think it's best for date errors to be silently ignored.)_~~

I've marked this as suggestion-discussion for the staff to comment on it since what I've described might not match what they want. All the text in italics should especially be reviewed, and this shouldn't be marked as help wanted until the question in italics has been answered.

---

Once this issue is resolved, the mobile apps can be updated to cache the content data and send the cached date in each request for the data. If the app didn't have cached data, it would make the API call without using the date query parameter. Possibly the website could also be modified to store the content data in local storage. New issues can be created for these changes after this issue is closed.

**Comment by veeeeeee** [comment]
After review we are ok to move forward on this. We have edited OP to show final bullet point parenthetical as a strikethrough, as main statement is our preferred approach. 

Regarding "Or should it return a value that indicates there's no new content?" -- this can be decided at point of implementation.

**Comment by paglias** [comment]
> Regarding "Or should it return a value that indicates there's no new content?" -- this can be decided at point of implementation.

I think we should consider using the `ETag` header that is available with HTTP and meant for this type of use case instead of building something new. We just need to make sure it can be used easily from mobile apps @phillipthelen

**Comment by paglias** [comment]
With #12020 the content api can be passed an etag, that should prevent re-downloading the data if it's not changed (cc @phillipthelen )

**Comment by paglias** [comment]
Closing since the ETag offers the same functionality and is already available
