### ISSUE TITLE
move FAQ questions and answers from API v4 content route to dedicated route

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11801]
_Note for contributors: This issue relates to API version 4, which is used internally by the official website and mobile apps. All third-party tools must still use version 3. You're welcome to work on this issue after it's been marked as help wanted but be careful that your fix changes only [API v4](https://github.com/HabitRPG/habitica/tree/develop/website/server/controllers/api-v4). It must not change [API v3](https://github.com/HabitRPG/habitica/tree/develop/website/server/controllers/api-v3) because that would be a breaking change that would negatively affect third-party tools. Links to the [apidocs](https://habitica.com/apidoc/) are provided here for reference but those docs are for API v3 so they might not be accurate for v4._

---

When you use the [content](https://habitica.com/apidoc/#api-Content-ContentGet) route with the API v4 command below, the content includes FAQ data as well as other data:

`curl -X GET 'https://habitica.com/api/v4/content?language=en'`

Sample FAQ data:

```
"faq":{
	"questions": [
		{
			"question":"I'm confused. Where do I get an overview?",
			"ios":"First, you'll set up tasks...",
			"android":"First, you'll set up tasks...",
			"web":"First, you'll set up tasks..."
		},
		{
			"question":"How do I set up my tasks?",
			"ios":"Good Habits (the ones with a +) are...",
			"android":"Good Habits (the ones with a +) are...",
			"web":"* Good Habits (the ones with a :heavy_plus_sign:) are..."
		}
	],
	"stillNeedHelp": {
		"ios":"If you have a question that...",
		"web":"If you have a question that..."
	}
}
```

We want this FAQ content to be removed from the `content` route and added to a new `faq` route.

This must be done in SEPARATE stages:
1. **Create the new `faq` route.** This is the only action needed to resolve this issue.
2. LATER: Update the official mobile apps and website to use the `faq` route and wait long enough for most app users to upgrade the app.
2. LATER: Delete the faq data from the `content` route. We should be certain that the non-updated mobile apps won't crash when that's done. It's okay if the FAQ screen on non-updated apps doesn't work - the user can update to fix that.

So this issue is only for item 1 above. After item 1 is done, we'll log new issues for the other items.

The new `faq` route should take an optional query parameter that can have one of these values: `ios`, `android`, `web`:
- If the parameter is supplied, then only the questions and the matching answers should be returned, not all three answers for each question. See in the data above how there's different answers for different platforms).
- If the parameter is supplied and one of the items doesn't have a response for that platform, the `web` response must be returned. We'll assume `web` is always populated. See the `stillNeedHelp` item for an example of that.
- If the parameter is supplied and it's not one of the allowed values, an error should be thrown.
- If the parameter is not supplied, the full `faq` object should be returned.

----

_This is being done to slim down the `content` route to improve loading times, especially for the mobile apps. The new `faq` route can be loaded only if the user accesses the FAQ screen._

**Comment by Alys** [comment]
I've marked this as suggestion-discussion for the staff to comment on it since what I've described might  not match what they want. I'll change it to help wanted in a couple of weeks if there's been no objections.

**Comment by hamboomger** [comment]
@Alys Can you assign it to me?

**Comment by Alys** [comment]
@hamboomger Sure, thanks! I've marked it as in progress for you.

**Comment by hamboomger** [comment]
@Alys should the faq route be cached in the same way as content route does? Almost 30k characters (but it's not too large in comparison with 1.7 million characters in a content.js file).

**Comment by hamboomger** [comment]
@Alys let's suppose an answer without platform specified looks like this:
```
"questions": [
	{
		"question":"I'm confused. Where do I get an overview?",
		"ios":"First, you'll set up tasks...",
		"android":"First, you'll set up tasks...",
		"web":"First, you'll set up tasks..."
	},
	{
		"question":"How do I set up my tasks?",
		"ios":"Good Habits (the ones with a +) are...",
		"android":"Good Habits (the ones with a +) are...",
		"web":"* Good Habits (the ones with a :heavy_plus_sign:) are..."
	}
],
"stillNeedHelp": {
	"ios":"If you have a question that...",
	"web":"If you have a question that..."
}
```
Then if `?platform=ios` parameter specified, which approach is better, to answer like this:
```
"questions": [
	{
		"question":"I'm confused. Where do I get an overview?",
		"ios":"First, you'll set up tasks...",
	},
	{
		"question":"How do I set up my tasks?",
		"ios":"Good Habits (the ones with a +) are...",
	}
],
"stillNeedHelp": {
	"ios":"If you have a question that...",
}
```
Or like this:
```
"questions": [
	{
		"question":"I'm confused. Where do I get an overview?",
		"answer":"First, you'll set up tasks...",
	},
	{
		"question":"How do I set up my tasks?",
		"answer":"Good Habits (the ones with a +) are...",
	}
],
"stillNeedHelp": "If you have a question that..."
```
? 
I feel like the second one makes much more sense, but still it's better to ask first.

**Comment by Alys** [comment]
@hamboomger Thanks for asking! I think the first one might be better because it allows the website/apps to use the same code to parse the returned data, regardless of whether the platform parameter was specified.
However if the staff post here to say otherwise, listen to them not me. :)

For your earlier question:
> @Alys should the faq route be cached in the same way as content route does? Almost 30k characters (but it's not too large in comparison with 1.7 million characters in a content.js file).

I don't have an answer for that but the weekend is nearly over in the USA so the staff might have an answer for that soon.

**Comment by paglias** [comment]
Regarding the cache, yes for now let's use the same method, we might want to revisit it in future

**Comment by hamboomger** [comment]
@paglias have you considered using in-memory databases for these purposes? It's just seems to be a good use case for something like Redis.

**Comment by paglias** [comment]
@hamboomger yeah, it's in the big backlog of things to do :) But I prefer to do it all at once instead of introducing changes just for one case like here. Unfortunately these type of changes that impact the infrastructure need to be completed by the staff and we're a very small team

**Comment by hamboomger** [comment]
@paglias oh, ok, I dig it :)
I actually think now that there will be no benefit in caching /faq route in a file system, the same way as it was implemented in the /content route. Max size of faq response is ~32 Kb, and if platform specified it's only about 10 Kb(a /content response is ~2.1 Mb). What do you think?

**Comment by paglias** [comment]
So basically what we're trying to do is that the mobile apps load the `/content` API route at every startup and it's starting to be a bit heavy at ~2mb. So to begin with we want to remove from the content API stuff that is not needed every time the apps start

**Comment by hamboomger** [comment]
@paglias can somebody from your team check my pr please?

**Comment by paglias** [comment]
@hamboomger sorry but we’re a very small team and I’m the only one reviewing PRs, so it may take some time but we’ll eventually get to it

**Comment by shanaqui** [comment]
Hi @hamboomger! Are you still interested in working on this one?

**Comment by hamboomger** [comment]
@shanaqui Hi! Yes, I'm still interested in working on this issue

**Comment by shanaqui** [comment]
Alrighty, thanks for checking in!
