### ISSUE TITLE
Received 10 more gems?

### ISSUE THREAD

**Issue by gooddevil70** [HabitRPG/habitica#1181]
![capture](https://f.cloud.github.com/assets/4393964/654502/a107ede0-d4fc-11e2-86fe-7e32aea3c691.png)
I had 4 gems after making a guild and yesterday it turned into 14 gems. I have never connected a credit card with this site. I was wondering if it was a bug or not. Although I do like extra gems. :p

**Comment by Shaners** [comment]
Have you tried spending them? It could just be a display issue like before with resetting an account.

**Comment by gooddevil70** [comment]
Well when I refresh the page it still says 14 gems

**Comment by Shaners** [comment]
Just took a look at your github history, those 10 gems are probably a reward for filling out the survey #1170 

If so you can probably close this issue and #1170

**Comment by lefnire** [comment]
definitely the case.
