### ISSUE TITLE
Strange bug with dailies

### ISSUE THREAD

**Issue by Pacerparty** [HabitRPG/habitica#1182]
Today is Saturday.
I have on daily where all days are "off" except Wednesday which is "on".
I ticked on Wednesday so that it will also be "off" and immediately i lost hp and gold.
I hit the undo button and i lost more hp and gold. Every time i hit the undo button i was losing hp and gold.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
