### ISSUE TITLE
Brutal Smash and Burst of Flames skills should show a boss damage notification

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11828]
When you are in a boss quest and you complete a task, you see a "damage to boss" notification, like the one at the bottom of the screenshot below.

You should see the same notification when you do boss damage from using the Brutal Smash and Burst of Flames skills. Those skills used to give a notification but at some point they've stopped doing that.

![image](https://user-images.githubusercontent.com/1495809/73888908-3fd10000-48ba-11ea-8b5a-2ecf03613edd.png)
Ignore the grey box at the right of the screenshot, it's just an artifact of how I cropped the screenshot.

**Comment by fdmcneill2019** [comment]
Where is the code or files for this issue? I'm interested in trying to fix this one.

**Comment by fdmcneill2019** [comment]
Where is the code or files for this issue? I'm interested in trying to fix this one.

**Comment by Alys** [comment]
@fdmcneill2019 Thanks! I've marked this as in progress for you.

To find the relevant code locations, you can follow a process something like this:

`git grep -i "burst of flames"`  - that will show you all places where that text appears. A lot of the places will be in the locales files ("/en/" English text and texts for other languages) but you can either ignore them if you see other results that seem relevant.

For cases where the only results you see are the locales files, narrow it down to just the English ones like this:
`git grep "Burst of Flames" | grep "/en/"`
You can then pick an appropriate "key" from that and search to find where the key is used:
`git grep spellWizardFireballText`

Similarly to see where the current boss damage notification is coded:
`git grep "damage to boss"` (that's the string that appears in the notification in the screenshot above)

**Comment by fdmcneill2019** [comment]
@Alys I'm currently having some issues cloning the repository with Git so it may take me a few days to get started, but I'll definitely get to work on it when I can. Thanks.

**Comment by Alys** [comment]
@fdmcneill2019 Thanks for the update! Cloning is usually simple so if something's going wrong it'll be an unusual problem and you're welcome to ask for help with it if you wish. If you do want help, as a first step, use the process described in [Setting up Habitica Locally](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally) for your platform, and let us know which step fails and what errors or incorrect behaviour you see.

**Comment by fdmcneill2019** [comment]
@Alys Luckily I was able to clone it early this morning. Thanks for the link.

**Comment by fdmcneill2019** [comment]
@Alys I'm thinking the corresponding JavaScript files for each of the relevant JSON files responsible for damage notifications might be the origin of the problem. If I'm not mistaken, the JavaScript files are what makes calls to trigger the notifications. What are your thoughts?

**Comment by Alys** [comment]
@fdmcneill2019 Yes, the json files are just used for storing the translatable strings; all the backend/API code is in JavaScript files. There's some front-end website code in *.vue files as well as *.js files. However the json files are often a good place to start searching for code - you can look in them for the exact string that you see on the website to find the string's "key", then use "git grep " to search for they in the JavaScript and vue files.

**Comment by fdmcneill2019** [comment]
OK. And how would I test a feature to make sure it works after I make changes?

**Comment by Alys** [comment]
@fdmcneill2019 That "Setting Up..." page I linked to has links to other pages, including "Using your Local Install..." and that page has some tips about testing (the rest of it is good to read too).

**Comment by fdmcneill2019** [comment]
@Alys You might want to open this issue up for others to try. I've been having problems understanding the source code (I'm still relatively new to JS) so that I can track down the problem. There are a lot of modern JS concepts I'm still not familiar with like destructuring assignment and the use of 'this' in JS.

**Comment by Alys** [comment]
@fdmcneill2019 No worries, thanks very much for telling us!

**Comment by inftp** [comment]
Hi, I'd like to try my hand at this one

**Comment by Alys** [comment]
@inftp Thank you and sorry about our delay in replying! Please go ahead and post here if you have questions.

**Comment by inftp** [comment]
Hi @Alys , I'm having trouble replicating this on my fork of the develop branch with the latest changes from upstream as of the time of this message.

Steps followed:

1. I set my character's level to 11 to unlock both classes and abilities.
2. I started the dust bunnies quest
3. I cast Brutal Smash on a todo, there is a notification that Brutal Smash has been cast on the todo
4. I complete the todo, among other notifications there is a notification that I have dealt damage to the boss.

Am I missing something?

**Comment by Alys** [comment]
> 3. I cast Brutal Smash on a todo, there is a notification that Brutal Smash has been cast on the todo

That should have a second notification saying how much damage was done to the boss by the skill. The notification in step 4 is just for the task's damage to the boss.

**Comment by shanaqui** [comment]
@inftp Hi! Are you still interested in working on this one? Let me know! :)

**Comment by inftp** [comment]
Hi @shanaqui , my sincerest apologies, recent events have brought some new complications into my life (as they have to many others). I will take the chance to once again look at this ticket and #11991 before the end of the week. Thank you for your patience!

**Comment by shanaqui** [comment]
No worries! We'll check in again in a couple of weeks but for now I'll leave this with you.

**Comment by inftp** [comment]
Just to clarify: 

1. From what I was able to gather from the Habitica wiki, both Burst of Flames and Brutal Smash are "buffing" skills that cause a task to deal more damage to a boss, is this correct or have I misunderstood?
2. The expected behaviour is for two "x damage to boss" notifications to trigger sequentially (one after the other) when a "buffed" task is completed, rather than showing the combined (buffed) damage in a single notification?

**Comment by shanaqui** [comment]
Not quite! The skills do damage instantaneously. There should be a single
damage notification immediately after they are used, and no change when the
task is checked off.

**Comment by inftp** [comment]
So they both do an initial amount of boss damage *and* buff a task to deal more damage when it is completed? If not, what is the purpose of casting the spell on the task itself?

**Comment by shanaqui** [comment]
No. The point of casting them on a task is that the task value is used in
calculating the damage the skill can do.

Brutal Smash does also change the task value, so will change how much
damage the task does when it is checked off, but this is a permanent change
to the task itself and does not require an extra notification.

Which Wiki page were you referring to? It sounds like something might need
to be edited!

**Comment by inftp** [comment]
Hi team, I must apologise but I will no longer have the free time available to work on this ticket. For whomever picks it up, a `git bisect` ought to be able to reveal the commit that introduced the bug once the intended behaviour has been identified.

Best of luck

**Comment by Alys** [comment]
@inftp Thanks for letting us know! I'll set this back to help wanted.

For the next person to work on this:

The intended behaviour is as written above in the posts from me and from shanaqui. To summarise how the skills work on the website:
1. You click on the skill in your skill drawer at the bottom of the tasks page.
2. You click on any one of your own tasks (don't choose a task from a Challenge or Group Plan).
3. The skill immediately does damage to the boss (the damage is stored in your account and will be applied at your next [cron](http://habitica.wikia.com/wiki/Cron), in exactly the same was as boss damage from completing a task).
4. **As soon as the skill has been cast, you *should* see a notification saying how much damage has been done to the boss. Making this notification appear is what's needed to fix this issue.**

You could use `git bisect` as @inftp suggests to find at what point in the history the notification stopped being shown, but that's likely to take a fair bit of your time, and might not be successful since older versions of the website won't work with the current versions of config files and the node_modules directory.

It's likely to be faster to just add new code to display the notification. You can examine the code for completing tasks to see how task completion shows a boss damage notification and do something similar for the skills. See also the advice in my earlier posts here.

**Comment by fmaximus** [comment]
I think I found the issue. 
I'll do some tests, and if I'm right I'll create a PR
