### ISSUE TITLE
Users who do not have usernames show up only as @ in challenges

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11824]
In old challenges, there are sometimes participants who have never confirmed a username. These users appear in the "view progress" tool as "@", and also in the "End Challenge" username selection.

![image](https://user-images.githubusercontent.com/8144640/73743921-8fdb8580-4747-11ea-88d9-85b3d318a0e1.png)
![image](https://user-images.githubusercontent.com/8144640/73743935-9833c080-4747-11ea-84fa-900f68d33be9.png)

Example of a challenge with this issue: https://habitica.com/challenges/8aa90845-80ad-4c1b-ac93-e28d9c55c647

Reported by citrusella in Report a Bug.

**Comment by Alys** [comment]
My suggestion for how to fix this is that if the Username is not available, that list should show the Display Name. The "@" symbol should not be used for Display Names.

I've set labels on this.

**Comment by tuttiq** [comment]
Seems like this is the place that displays usernames on the `memberSearchDropdown` component:
https://github.com/HabitRPG/habitica/blob/aefd664db1ef46b24a6d9edc5ac55248e9082b0e/website/client/src/components/members/memberSearchDropdown.vue#L22

I'm just jumping to conclusions here (I'm getting to know this project now), but I'm guessing this could be solved with an `or` operator for username OR display name (whatever is not null/blank), or just replace completely with display names if that's the desired spec?

Feel free to ignore if I'm missing context on my suggestion!

**Comment by Alys** [comment]
@tuttiq We do want Usernames shown when they're available because they're the best way to identify players these days.

Your OR idea sounds good! If you'd like to try it, tell us and I'll mark this as in progress for you.

**Comment by tuttiq** [comment]
Sure, let me setup my local environment and I'll try to submit a PR for that :)

**Comment by Alys** [comment]
@tuttiq Awesome, thanks! Post here if you have questions or run into trouble.
