### ISSUE TITLE
After moving a task, the three-dots menu appears behind other tasks - z-index problem

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11831]
Reported by krezzkrazz:

> After I drag a habit, when I click on the three dots to edit it, the menu appears behind other items. I'm using Chrome version 79 on OS X 10.14.1.

I've reproduced the behaviour on Firefox in Windows. It occurs with all task-types, not just habits.

![image](https://user-images.githubusercontent.com/8144640/74015081-dae3db80-4987-11ea-9096-935297dfd18f.png)

This looks similar to #11457, but only occurs after dragging a task.

**Comment by Alys** [comment]
This is _probably_ a CSS z-index problem, although any contributor working on this should check that before proceeding on that assumption.

I've added labels for help wanted, etc.

**Comment by joefessenden** [comment]
I'm looking at this, and I don't think it's necessarily a z-index problem. If so, I should be able to adjust that value in the inspector in my browser. I'm still looking at it, but I'm not claiming it yet because I'm not sure I'll get much of anywhere. I'm still pretty new, an both of the beginners items seem claimed.

**Comment by joefessenden** [comment]
I committed a change for this to task.vue. I'm hoping I did it right. I'm very new to this. The .task element needed to have the position=relative removed so the z-index would be respected. I cannot find any negative effects from the change in the checking I did.

**Comment by Alys** [comment]
@joefessenden Thanks for taking this on! I've marked it as in progress for you. When you're ready, do a pull request and Habitica's staff will review it (it might not happen for a few days). If you'd like more details about the pull request process, [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) has a section about it.

**Comment by joefessenden** [comment]
@Alys Thanks. I checked in the code (I think). Can you let me know if I did that right (I just don't want this to be waiting for me - I know the code review will take some time)? I am a bit green at GitHub, and it doesn't seem to behave in quite the same way as my previous experience (SVN).

**Comment by Alys** [comment]
@joefessenden Hmm, I can't see a pull request from you so I think something might have gone wrong with that. Did you find the "Submitting your Change for Review in a Pull Request" section in [Using Your Local Install to Modify Habitica's Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API)? It looks like you're up to step 4, so if anything there doesn't make sense (in either the wiki page or the GitHub docs it links to), tell us and we'll adjust the instructions. If it still doesn't seem to work, tell us what you get up to in that process and what you notice that's wrong.

**Comment by joefessenden** [comment]
My challenge is that I'm trying to use the git interface in the IDE, so that's where I'm running into something not covered well by the docs. I posted a couple times in general in the Aspiring Blacksmiths Guild, but got no response. I did find where I made a pull request and a commit, but it only went to my clone, not to y'all. How do I address that?
https://github.com/joefessenden/habitica/commit/1c438744d775e25eaa1b1f5bafa5babd6db50152

**Comment by Alys** [comment]
Ah right. I saw your questions in the guild. I'd guess there were no answers because none of us have used that IDE for git commands. Your best option if you want to persist with doing it in the IDE might be to ask for help from the IDE's vendor. It can't be uncommon to need to do a PR from a fork to the original repo so they might be willing to update their documentation to include instructions for it.

**Comment by joefessenden** [comment]
@Alys I know this is pretty low on the priorities to be approved and actually merged into the code, but can you have a peek and confirm that I did the pull/commit right? I just want to be sure that I didn't mess that up, still, so it's just in limbo.

**Comment by Alys** [comment]
@joefessenden I haven't reviewed the code (the staff will do that) or tested it on a local install but the pull request itself and the commit have been done correctly! The PR is linked to this issue, which is good, and has the basic information needed.

**Comment by shanaqui** [comment]
Hi there! Are you still working on this one, @joefessenden? Let us know if so!

**Comment by joefessenden** [comment]
@shanaqui I wish I could do this in a timely manner, but I just took a new job, and I won't have time to sit down with this code for a little while, so please make it available again. If no one has grabbed it when I catch up, I'll swing back around.

**Comment by shanaqui** [comment]
I've marked this one as help wanted again too. :)

**Comment by anoopravella** [comment]
Hi, I'd like to pick this issue up.

**Comment by Alys** [comment]
@anoopravella Thank you! Please go ahead and post here if you have questions.

**Comment by shanaqui** [comment]
@anoopravella Are you still interested in looking into this issue? If not, I can mark it as help wanted again. :)

**Comment by shanaqui** [comment]
I've marked this as help wanted again!

**Comment by Alys** [comment]
I've marked this as in progress for @terminalstderr (https://github.com/HabitRPG/habitica/pull/11858#issuecomment-625000973)

**Comment by Alys** [comment]
I'm closing this because it should be fixed by the library update that @terminalstderr discovered.  https://github.com/HabitRPG/habitica/pull/11858#issuecomment-629042378 The new version of the library should be live in a few days.

@terminalstderr Thanks so much for that investigation! Nice work!
