### ISSUE TITLE
Bring back the Variable Change Panel

### ISSUE THREAD

**Issue by bowiz2** [HabitRPG/habitica#1183]
HabitRPG is awesome - except for when the memory leak issue doesn't allow me to log on, so I can't update my dailies, which causes my character to die and lose a sword I worked for months to get.

The panel was used earlier on when HabitRPG was unstable, so the code is already there. You could change items, levels, GP, and whatever. I feel that Habit's uptime is unstable enough so that it should be brought back.

Please bring it back. I truly can barely explain my frustration.

**Comment by lefnire** [comment]
It never went away. Options > Settings > Restore
