### ISSUE TITLE
No Ultimate Gear Achievement w/ Backer Armor

### ISSUE THREAD

**Issue by pheldurin** [HabitRPG/habitica#1185]
I currently have the max gear that I can buy, but I haven't received the Ultimate Gear achievement. I have the golden sword, shade helm, shade armor, and the tormented skull. User ID 75b93321-66b9-49bd-9076-052499c1d2bf

**Comment by lefnire** [comment]
woops, bug! fixed in https://github.com/lefnire/habitrpg/commit/7370331b8c7f22873c4187bd9e5f3450db6c4694 . I'll fix you up manually though for now, you should be good to go
