### ISSUE TITLE
clarify messages shown when a quest has already started

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11861]
The message below is used when four events occur:
"Your party is already on a quest. Try again when the current quest has ended."
https://github.com/HabitRPG/habitica/blob/e6ba1ccca72221a80e6e869bb2b87e0ad8faaafe/website/common/locales/en/quests.json#L104

Those events are when you try to:
1. issue an invitation for a new quest while your party is on a quest
2. force-start the current quest that has already started
3. accept the quest invitation for the quest that's already started
4. reject the quest invitation for the quest that's already started

The message is very appropriate for event 1 and that shouldn't be changed.

It's less appropriate for event 2. Better would be something like: **"That quest has already started."** (No need for "try again" because your intention was to start the current quest.)

The message is confusing for events 3 and 4. Better would be something like: **"That quest has already started."** Maybe it could also contain an encouraging and friendly message about waiting for your party's next quest.

The strings for the new messages should be placed next to `questAlreadyUnderway` to keep similar strings together.

You can find where each of those four events are coded by using `git grep questAlreadyUnderway` - that will show you the code that needs to be changed to use the new strings, and the tests that will need to be adjusted. All those changes should be simple so I'm marking this as "good first issue" so that a new contributor can try it.

**Comment by ianrandmckenzie** [comment]
I think I have a solution ready for this. I just need to read the guide on pull request protocols.

**Comment by ianrandmckenzie** [comment]
Looks like a couple of tests related to my changes failed. I'll look into it right now.

**Comment by ianrandmckenzie** [comment]
All passing now, ready for review.
