### ISSUE TITLE
most party members missing from header after viewing private messages / inbox / PMs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11869]
EDIT 2020-02-22:

As described in the next comment, the bug occurs when you reload the website while viewing the private messages page. To reproduce:

1. Go to the [private messages page](https://habitica.com/private-messages)
2. Reload using your browser's refresh button.
3. Use the top navigation menu to visit any other page (don't use the Help menu as some parts of it work differently).
4. Observe that all but one of your party mates do not appear. (Reloading on that page makes them reappear).

----

As reported by @geolojess (da27bf23-48f7-469d-9a32-58521f9c84a9) a few days ago:

**"(Web) looks like whenever I check my PMs, then leave that page and go to another one, all but one of my party members shown in my header disappear. Refreshing the page brings the rest back. Here's a screenshot."**

![image](https://user-images.githubusercontent.com/1495809/74599873-c1a00500-50d4-11ea-9aa6-df48b97a7c0c.png)

I've confirmed the party has five members, not two.

A little later she said: 
**"... I tried [again] and the bug didn't occur this time! Now I'm unsure if that's to be expected or if the PMs is not the cause. If it happens again I'll try your instructions again [for getting console messages] and report back."**

A couple of days later she reported it happened again and she sent us the errors below from the browser's console _[EDIT: I've deleted them since they turned out to not be related]._ There was also nothing in Loggly that could be relevant (e.g., no errors related to loading party member data).

~I'm marking this as needs investigation and minor priority since it's only been reported by one person. We can increase the priority if we see more reports.~

**Comment by Alys** [comment]
@geolojess has added:

**"I think I've figured something out with that party display/PMs bug! It seems to happen if I've been on the Messages page for a long period of time and then go to a different page!"**

I'll be doing some testing to see if I can reproduce that.

**Comment by shanaqui** [comment]
geolojess posted:

> figured out the (actual) cause of the "most party members missing from header after viewing private messages / inbox / PMs" bug! Refreshing while in the Messages page (I do this sometimes to bring in new messages), then switching to a different page, like the Tavern, will cause all but one of the party members to disappear. So causation is mostly me being impatient haha. Refreshing on a page other than Messages will bring back the rest of the party members.

This made it reproducible for me in Firefox on Windows.

**Comment by Alys** [comment]
I've edited the top post to summarise the issue, deleted a comment that's now redundant, labelled this as medium priority since it affects everyone, and marked it as help wanted.

**Comment by tsukimi2** [comment]
@Alys Alright if I take a look at this issue?

**Comment by Alys** [comment]
@tsukimi2 Sure! Thank you!
