### ISSUE TITLE
Unable to Edit - minor Bug on Opera & Firefox

### ISSUE THREAD

**Issue by lennellie** [HabitRPG/habitica#1187]
Hi... I'm quite a new user of only two days. However, I did notice that there are times where clicking on the edit button garners NO RESPONSE on arbitrary tasks, be it "habits" or "rewards" So for e.g. the first task is editable, and so's the third, but not the one sandwiched in between,... or perhaps on another time, it's the last task that I'm trying to edit. 

No box to edit comes out. I've searched the bug forum for "edit no response" but didn't get any results, so I hope I'm not creating a new thread for nothing. 

If you want, I can try it on internet explorer. I did try chrome, but it had flash issues, so I uninstalled it.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
