### ISSUE TITLE
"Collapse checklist" hovertext persists on mouseover and blocks checkboxes for checklist items

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11888]
> "This was mentioned in the Tavern and I'm seeing it too: in the tasklist on the web, if I hover over the Collapse Checklist button on a task, and then move my mouse down so it's on the label popup, the popup stays until I move my mouse off the popup. The popup covers the top couple checklist items so they can't be checked off (until you move the mouse all the way out of range to get rid of the popup).
> I know some popups are designed to stay onscreen if you mouse over them, which makes sense when the popup is designed to time out. The label popup doesn't time out, so I don't think it needs to be 'paused' with a mouseover."

Reproduced in Firefox on Windows.

**Comment by Artistic18** [comment]
Can I get a better description of the Issue please.

**Comment by Alys** [comment]
@Artistic18 I've stepped through the description and it works exactly that way for me. What part of it doesn't work for you or doesn't make sense to you?

**Comment by nikonhub** [comment]
Hello.

May i suggest to move the tooltip from bottom to top of the element ?

**Comment by cvuorinen** [comment]
I can take a look at moving the tooltip.
