### ISSUE TITLE
encouragement to buy gems

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1188]
I do not understand the concept of eggs, portions and pets - i do not think anyone will ever be attracted enough to buy gems. are you guys sure about this as a revenue model?

**Comment by lefnire** [comment]
we make ~$30/d on gem purchases. People use them on pets & guilds. In the future they'll also use them on the [mount system](https://trello.com/card/mounts/50e5d3684fe3a7266b0036d6/221), and rewards for [challenges](https://trello.com/card/challenges-individual-party-guild-public/50e5d3684fe3a7266b0036d6/58).

It's our survival revenue (enough to pay for servers, mongohq, etc). We're focusing on education and health organizations for our real revenue, but that's a big long road that takes tons of time and effort
