### ISSUE TITLE
Missing Achievements/Gems

### ISSUE THREAD

**Issue by Flargleblargle** [HabitRPG/habitica#1189]
I completed the servey about 2 weeks ago, and I still haven't recieved the 10 gems, or the achievement. Can someone reset the survey of something for me?
Cheers

**Comment by lefnire** [comment]
what's your id, i'll sort you out

**Comment by Flargleblargle** [comment]
My ID's: 5a159fb5-a5fc-4020-a79e-35f2d16dbdfd

Cheers very much for the help!

Date: Tue, 18 Jun 2013 12:54:52 -0700

**Comment by lefnire** [comment]
Great, you should be sorted.
