### ISSUE TITLE
Purchased items don't sync when buying them for the first time

### ISSUE THREAD

**Issue by alecbrick** [HabitRPG/habitica#11907]
[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 3c2b1d99-c6f0-4e6e-a67a-bd8e023cfc7e
  * Browser: Chrome 
  * OS: Windows

### Description
When buying food, potions, or eggs for the first time (i.e. having never had this item in your inventory before), the store doesn't sync correctly. In other words, the item in the store won't show an itemCount badge until you perform an action that causes the page to load (e.g. switching tabs in the store). The same goes for your current inventory at the bottom of the screen - it won't be updated unless you switch tabs in the inventory.

My current guess is that this is caused by the fact that when you've never had an item before, it doesn't show up in the JSON representation of your inventory; buying it adds it to the JSON object with a count of 1. For example:
```
{
  fish: 1
}
```
becomes
```
{
  fish: 1,
  chocolate: 1
}
```
 However, when you HAVE had that item, the item key remains in the JSON object. When you have none of that item, it's represented with a count of 0, and so buying the item increases the count to 1. For example:
```
{
  fish: 1,
  chocolate: 0
}
```
becomes
```
{
  fish: 1,
  chocolate: 1
}
```
I haven't confirmed that this is the source of the errors, but it feels very related.

#### Console Errors
None.

**Comment by Alys** [comment]
@alecbrick Thanks! I've marked this as help wanted but if you'd like to work on it post here and I'll make it in progress for you. No worries if you don't want to work on it of course. :)

**Comment by alecbrick** [comment]
I can work on this. I've got a working solution, but it's not the cleanest, and I'm wondering if there's a better way to handle it. I'll create a PR tomorrow.

**Comment by Alys** [comment]
@alecbrick Awesome, thank you! I've marked it as in progress for you.
