### ISSUE TITLE
sorting by name of party members in header should use case folding

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11914]
The party members that appear in the website's header can by sorted by name (click the "View Party" button and select "Sort by Name" from the drop-down then click "Apply Sort Options to Party Header"). When you do that, you see that sorting is done case-sensitively (A, B, C, a, b, c). 

The desired behaviour is that sorting by name should use [locale-sensitive case folding](https://www.w3.org/International/wiki/Case_folding).

Previously, this was also a problem in the modal that appears when you click "View Party" (this issue: https://github.com/HabitRPG/habitica/issues/11547). It was fixed for the modal in this PR:  https://github.com/HabitRPG/habitica/pull/11595, and you can probably do something similar for sorting in the header.

Note though that it's important that the `direction` option is still used when sorting by name (see https://github.com/HabitRPG/habitica/issues/11913 for more details about that).

![image](https://user-images.githubusercontent.com/1495809/75623361-fe9be980-5bf4-11ea-8f46-8a71d42731a2.png)

**Comment by nikonhub** [comment]
Hello.

I can fix this one.

**Comment by paglias** [comment]
thanks @Nikosmonaut , I'll mark this as in progress!
