### ISSUE TITLE
Double streak bonus at 42 days

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1191]
I just hit a 42-day streak on one of my dailies, and got a second streak achievement (and a point added to the number of streaks displayed on my profile). I thought the streak achievement was once per daily only. Is the second bonus an error, or was I just confused?

**Comment by Sean31** [comment]
I think it's designed to happen every 21 days, for any daily, even multiple times. It's still a 21-day streak, you see?

**Comment by octern** [comment]
I could see it going either way, so I thought I'd check. Anyway, anyone in a position to know that this is what was intended is welcome to close this issue without further comment.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
