### ISSUE TITLE
Party Sort Order Asc / Desc (Ascending / Descending) fails for "Sort by Name" in modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11913]
When you click the "View Party" button in the header, a modal opens and you see a drop-down with "Sort by" options and another drop-down for  "Asc" (Ascending) and "Desc" (Descending).

The Asc / Desc options don't make any difference when "Sort by Name" has been selected.

The expected behaviour is that if you select "Sort by Name" and then switch between Asc and Desc, the party members in the modal should reverse order.

Asc / Desc does work as required for the other "Sort by" options.

![image](https://user-images.githubusercontent.com/1495809/75623283-2c346300-5bf4-11ea-881c-56ae6611edc3.png)

**Comment by Alys** [comment]
This looks like the PR where this bug crept in: https://github.com/HabitRPG/habitica/pull/11595/files
The `direction` option should be used for sorting by name.

**Comment by Alys** [comment]
The same bug also happens for the guild and challenge member/participant lists, and it should be fixed for them too. The same piece of code will be used for all three types of member lists.

**Comment by nikonhub** [comment]
Hello.

I can fix this one too.

**Comment by paglias** [comment]
thanks @Nikosmonaut , I'll mark this as in progress!
