### ISSUE TITLE
the case of the disappearing tasks

### ISSUE THREAD

**Issue by permanentblur** [HabitRPG/habitica#1192]
my habits, dailies, todos, and rewards, save three, have disappeared! all my beautiful streaks! i've tried refreshing, switching the beta, etc, but nothing works. is this a bug, or did i misclick somewhere?

**Comment by lefnire** [comment]
you sure there's no active tags? click the "clear tags" x button just to be
sure

**Comment by permanentblur** [comment]
_foreheadsmack_ got it in one. thanks for your help!

**Comment by lefnire** [comment]
yeah, pretty common mistake - i need to somehow make it more obvious when nothing is appearing, maybe an empty message like "no tasks with those tags"
