### ISSUE TITLE
Disappearing hatching potions

### ISSUE THREAD

**Issue by ellernock** [HabitRPG/habitica#1193]
Today I've had three different hatching potions drop from tasks, and i can see them briefly in my inventory, but when I try to use them or leave my inventory, they disappear and the inventory says I don't have any hatching potions. Occasionally there's a small unloaded image box where the potion would be, but it usually goes away. It's really strange.

**Comment by wc8** [comment]
Possibly related to #988

**Comment by AndreCaseyScott** [comment]
And also #165??

Make sure you reload HabitRPGs tab before you check anything off. Decreases the likelihood of losing drops and other unpleasantness.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
