### ISSUE TITLE
Deleting a todo : todo went blank 

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1195]
Hello, I deleted 2 todos and I got this 

![buggy](https://f.cloud.github.com/assets/4671953/677302/117f4f54-d918-11e2-9564-5615fdc4d904.png)

It looks like I wasn't connected to the server anymore. (ticked and deleted todos went back when I refreshed the page)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
