### ISSUE TITLE
Page freezes after using the sort party header options

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11969]
> "The party sorting issue that I reported a couple of weeks ago (11913/11914) seems to have been fixed, but I think it may have introduced a new issue. When I sort my party header by name (either asc or desc), and then click the "View Party" button again, the website freezes until I get a "Page Unresponsive" error message, which I've never seen before, even when there are temporary server/sync issues. Here are the steps to replicate it:
> 
>     Click "View Party" button
>     Sort party by Name, either Asc or Desc
>     Apply sort order to the header
>     Exit the sorting modal
>     Click "View Party" button again_
> 
> Each time I've done it, the page freezes."

Reproduced in Firefox.

**Comment by paglias** [comment]
Confirmed, there's an infinite loop somewhere

**Comment by paglias** [comment]
Fixed in release, will go live with the next deployment
