### ISSUE TITLE
Streak Achievement error

### ISSUE THREAD

**Issue by Sean31** [HabitRPG/habitica#1198]
So I accidentally un-did one of my dailies by clicking it again, setting my streak back down from 22 to 21. Interestingly, this gave me another "Streaker" achievement. I did this again just to make sure (not to pad my achievements, I promise!) and it was reproduced. I now have 5 streak achievements when I should have 3. Anyway, thought you all should know. Nothing big or critical, but interesting.

**Comment by wc8** [comment]
Related to #1012 I think.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
