### ISSUE TITLE
wrong locked equipment message for gear from another class

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11988]
The Equipment section on Shops > Market gives the wrong message for basic equipment from another class. It says:

"This item is only available once you've purchased the previous items in sequence. Keep working your way up!" (that's the `tierLockedItem` string).

You should see that string only when you're in the same class as the equipment. When you're in a different class you should see this message:

"This item is only available to a specific class. At level 10 or above, you can change your class under the User icon > Settings > Character Build!" (`classLockedItem`)

The screenshot below show the bug. I lost the equipment shown when I was a Warrior. Now I am a Rogue and you can see it's displaying the wrong message.

![image](https://user-images.githubusercontent.com/1495809/76745703-0dbc9300-67c2-11ea-9920-8a5a52eed4ff.png)

This bug was reported by lex / @wlw_witch (87b9857a-48e8-48f8-8aae-fa52dd81f895) and confirmed by me.

**Comment by laurel-thomson** [comment]
I'd like to work on this issue!

**Comment by Alys** [comment]
@laurel-thomson Thank you! Please go ahead and comment here if you have questions or run into trouble.
