### ISSUE TITLE
Not that I'm not enjoying it, but my gold is back after buying a morningstar

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1199]
Hello, 
yesterday I bought a Morningstar 45 Gold. 
Today I'm reconnecting on HabitRPG, my Morningstar is still here but with 42 Gold back in my pocket. In fact, my actions from yesterday at the end of the day (1 AM in France) were not recorded, excepted the fact that I have a Morningstar. 

It's probably linked to some restart of the server, but I found that odd.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
