### ISSUE TITLE
Google Tasks Sync and Habit xp Values

### ISSUE THREAD

**Issue by Gr4ssh0pper** [HabitRPG/habitica#120]
I have been using Google Tasks for a great amount of time, it would be awesome to be able to sync the ToDo's with Google Tasks.

I feature that I find interesting would be customization of the value of experience received when completing a habit. Also, how much HP you lose for not completing it.Similar to how http://www.motivationrpg.com does it.

A basic question: If I have a Daily Task set and I don't complete it during that day, would I lose HP for that?

**Comment by BenMilford** [comment]
I really like the idea.

**Comment by racuna** [comment]
Good Idea, but i think an option to choose what list(s) of Gtaks i want to sync with HabitRPG is important, cause some lists in Gtask are just lists of things no necesary to do tasks like products in a shopping list, party guests or just ingredients of a recipe.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
Re: basic question: an uncompleted daily task set for that day does cost HP. 
For example, take out trash is set for every Thursday, if it is not done by Friday, HP will be lost.

**Comment by wc8** [comment]
Would Google Task Sync be the same as Google Calendar sync?
