### ISSUE TITLE
Problem with logging after an incorrect password attempt 

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1200]
Hello, 

after trying to logging with an incorrect password, if I click again on "Login/Register", the form stays 2 seconds and disappears. The problem also seems to happen after the "User not found" error.  

(NB : I'm trying to help by reporting as much bugs as possible. If you feel like I'm spamming, please tell me and I will stop :D)

**Comment by wc8** [comment]
Can you still login?

**Comment by MllePandaRoux** [comment]
Yes.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
