### ISSUE TITLE
Incorrect task display color for some fractional values

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12018]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

For some task values, the color displayed on the web client is inconsistent with the mobile apps and with the intended logic. In the below screenshots, the task "🐾 water topaz" has a `value` of `-0.9862061139856901`:

**Mobile (yellow, correct)**:
![image](https://user-images.githubusercontent.com/4501321/77789696-82e55f00-7031-11ea-9eff-90a5ea960449.png)

**Web (orange, incorrect)**:
![image (1)](https://user-images.githubusercontent.com/4501321/77789686-7f51d800-7031-11ea-96a5-0acd3c787d47.png)

The intended logic can be found here: https://github.com/HabitRPG/habitica/blob/develop/website/client/src/store/getters/tasks.js#L21-L34

```
  if (value < -20) {
    return 'worst';
  } if (value < -10) {
    return 'worse';
  } if (value < -1) {
    return 'bad';
  } if (value < 1) {
    return 'neutral';
  } if (value < 5) {
    return 'good';
  } if (value < 10) {
    return 'better';
  }
  return 'best';
```

I.e., a value below 1 but not beyond -1 should be returning the "neutral" yellow color, not the "bad" orange color. What's going on?

**Comment by SabreCat** [comment]
Having trouble reproducing this, but it might be browser-dependent? Changing labels as we gather more information.

**Comment by nathanzhu144** [comment]
I'm in the process of trying to work on this one!

**Comment by Alys** [comment]
@nathanzhu144 Thank you! I've added the "in progress" status label but I've kept "needs investigation" status label on it too since this one is odd. Note that it might be browser-dependent or intermittent in other ways so it might be hard to track down. :-/ Good luck! Post here if you have questions.

**Comment by nathanzhu144** [comment]
@SabreCat  Do you know what browser/OS you ran into this bug on?  Trying to reproduce the error.

**Comment by shanaqui** [comment]
The user who reported this issue was using Chrome. None of the team were able to reproduce this on the browsers they tried.

**Comment by shanaqui** [comment]
Hi @nathanzhu144, are you still interested in looking at this issue? If not, we'd love to hear about anything you found to help us decide on the status and what might have gone wrong!

**Comment by nathanzhu144** [comment]
@shanaqui I tried reproducing the error, and I was unable to really get much out of this one.  I don't know if we have sufficient conditions to reproduce the bug right now?

**Comment by shanaqui** [comment]
I think that's why it was marked as "needs investigation" and wasn't tagged as "help wanted". :) Good to know you didn't find anything!

**Comment by SabreCat** [comment]
Closing for now. Nobody's been able to reproduce it and it's distracting our helpful contributors! 😅
