### ISSUE TITLE
Habitica locally with Docker: 404 /api/v4/i18n/browser-script not found.

### ISSUE THREAD

**Issue by erikderzweite** [HabitRPG/habitica#12011]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Firefox
  * OS: Linux

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
I have set up Docker client and server according to the https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Docker

Server and client are running, but there is no text shown on the main page (and elsewhere). The problem seems to be in i18n with API v4 as the server reports:

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
habitica_server    | { method: 'GET',
habitica_server    |   originalUrl: '/api/v4/i18n/browser-script',
habitica_server    |   headers: 
habitica_server    |    { 'x-real-ip': '95.114.84.181',
habitica_server    |      'x-forwarded-server': 'ca243cb29066',
habitica_server    |      'x-forwarded-proto': 'https,http',
habitica_server    |      'x-forwarded-port': '443,80',
habitica_server    |      'x-forwarded-host': 'hab.boritsch.de',
habitica_server    |      'x-forwarded-for': '95.114.84.181,172.18.0.4',
habitica_server    |      te: 'trailers',
habitica_server    |      referer: 'https://habitica.mydomain.com/static/home',
habitica_server    |      'accept-language': 'de,en-US;q=0.7,en;q=0.3',
habitica_server    |      'accept-encoding': 'gzip, deflate, br',
habitica_server    |      accept: '*/*',
habitica_server    |      'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0',
habitica_server    |      host: 'habitica_server:3000',
habitica_server    |      connection: 'close' },
habitica_server    |   body: {},
habitica_server    |   httpCode: 404,
habitica_server    |   isHandledError: true }
habitica_server    | GET /api/v4/i18n/browser-script 404 3.880 ms - 59

Why exactly does the client try to get the v4 version of the browser script?

**Comment by paglias** [comment]
Hi @erikderzweite , v4 of the API is the one used internally by Habitica and not yet available as a public API. That being said the URL is correct and works fine on my local install. From the logs you posted it seems that you're using a custom domain, can you try if it works on `localhost`?

**Comment by erikderzweite** [comment]
This particular problem seems to stem from the typo in docker-compose.yml: i have forgot to remove docker Hub's habitica/habitica image from server thus resulting in old server with new client. I'd say, the client was trying to use api v4, but the server didn't knew anything about it.

**Comment by paglias** [comment]
That makes sense! let me know if you have any other issue
