### ISSUE TITLE
Intermittent server error

### ISSUE THREAD

**Issue by Tom-2** [HabitRPG/habitica#12017]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 9b188f09-8a3b-4d50-966d-53da212289d9
  * Browser: Chrome 80.0.3987.149(Official build) (64bit)
  * OS: Windows 10 Home 10.0.18363 build 18363

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Getting server error randomly. It started 3 hours ago. Sometimes I can score habits, but sometimes I can't. (red error message shows up in PC. server disconnection message when I use Android app.) Sometimes I can read messages in guilds, but sometimes messages don't show up.

Can't leave a message at "Report a Bug" guild. (I wrote the message and clicked "send" but nothing happens) So I came here.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Tom-2** [comment]
It's working well now. Closing :)

**Comment by paglias** [comment]
Hi @Tom-2 , unfortunately Habitica is being affected by an ongoing outage of Google Cloud (https://status.cloud.google.com/)

**Comment by Tom-2** [comment]
> Hi @Tom-2 , unfortunately Habitica is being affected by an ongoing outage of Google Cloud (https://status.cloud.google.com/)

Thank you for letting me know! I'll keep my eye on the server status.

**Comment by paglias** [comment]
It should have been resolved, we're not seeing any issue with our servers right now so I'm going to close the issue, will reopen it if needed
