### ISSUE TITLE
Checking off a completed daily via the API still gives rewards

### ISSUE THREAD

**Issue by ryjm** [HabitRPG/habitica#1202]
I actually kind of like this bug, since it means I can keep upvoting a daily if I think I deserve more exp for it (i.e if I spend more time on it) and then just reset the streak. 

To recreate, just send an "up" api call to a completed daily and it will increase your streak and give you rewards.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
