### ISSUE TITLE
I automatically have hundreds of coins without having done anything

### ISSUE THREAD

**Issue by ea247** [HabitRPG/habitica#1203]
I spend coins and then they come back to around 380 when I refresh the page. It totally destroys my motivation. :( 

My user ID is be032f09-bb90-4561-9881-11301aa1059b
My API token is [removed by @lefnire] if this helps at all.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
