### ISSUE TITLE
Coins award mechanism totally doesn't work. 

### ISSUE THREAD

**Issue by Muna526** [HabitRPG/habitica#1204]
I had about 10 coins in my pocket and spent 1,5 coins on a reward. However, after this 0 coins instead of 10-1,5 = 8,5 coins were left. 

When I did some dailies/habits I didn't get any coins. 

Even when I clicked on a reward, that has a price on it ,with 0 coins in my pocket, there was'n't any decrease of my HP. :(

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
