### ISSUE TITLE
Gems intermittently not decrementing properly

### ISSUE THREAD

**Issue by mindsandthings** [HabitRPG/habitica#1205]
My account showed 11 gems. I purchased a gold potion, it asked me if I want to buy it with 5 of my 11 gems, and after purchasing it showed my total gems as 6.  I bought a pig egg, it asked me if I want to buy it with 3 of my 11 gems, and after purchase, it showed my total gems as 8.  This same bug happened for all eggs: it asked me if I wanted to buy it with X of my 11 potions, and then after each purchase it showed my total gems as 11 minus however many gems the most recent purchase cost.  It also happened for base, gold, and red potions although I did not test the other potions.

I then logged out and logged back in.  It showed my gems as back at 11.  When I bought another egg (sorry, didn't record which one) while at 8 gems followed by a base potion, it correctly decremented my gems to 7. I then bought a red potion and it correctly decremented my gems to 4.  I logged back out and in again, and it still correctly shows it as at 4 gems.  I still have all the eggs and potions purchased both times.  

I think this may have happened in the past where I bought a single item and it decremented my gems correctly, but then they were back at 11 later. I did not check for whether it happened with multiple items, though.  

(Edited for parentheses and clarity)

**Comment by octern** [comment]
Just had a related issue: Purchased a tiger egg with 33 gems, dropped to 30. Reloaded the page, back up to 33 gems but still had the egg. I then tried purchasing a base potion and went down to 32, reloaded the page, and now (correctly) have 32 gems and a base potion. Not sure why it happened for one and not the other.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
