### ISSUE TITLE
Waffle / Confection quest scroll doesn't say that it's limited time only

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12066]
As reported by @Altariel (be317a32-c027-4032-bbd5-25ccb21eb912):

**"Not sure if I'm missing something, but the new Confectionary quest doesn't show that it's only available for a limited time anywhere that I can see."**

I'm marking this as suggestion-discussion for Habitica's staff to decide how/if this should be changed. Also marking it important priority since it's time sensitive.

**Comment by saraolson** [comment]
to make it clear the quest is seasonal, we should put the banner design we use on time-limited eggs/hatching potions on the quest purchase modal too

**Comment by SunSparc** [comment]
To be even more clear... 

This is an image of the "Waffling with the Fool: Disaster Breakfast!" quest, which provides the "Confection Hatching Potion":
<img width="828" alt="Habitica-Waffle-Confection-Quest" src="https://user-images.githubusercontent.com/1380473/78958673-0aa58180-7aa6-11ea-93a7-508986b0c3bc.png">

There is no banner or indicator in the text that this quest is time limited.

This is an image of the "Garden Potion", which is available for a limited time. There is text in the description that indicates it is time limited. There is no banner.
<img width="417" alt="Habitica-Time-Limited-Potion" src="https://user-images.githubusercontent.com/1380473/78958681-11cc8f80-7aa6-11ea-82a0-95b8d700a6b6.png">

This is an image of the "Spring Song" gear, which is available for a limited time. There is text in the description that indicates it is time limited. There is also a banner that indicates that it is time limited.
<img width="491" alt="Habitica-Time-Limited-Gear" src="https://user-images.githubusercontent.com/1380473/78958701-20b34200-7aa6-11ea-8b8b-5879f78b88ba.png">

**Would it be best to add both text and banner to the quest purchase dialog?**

**Comment by saraolson** [comment]
@SunSparc that colored banner is what we want to add to the quest dialogue. it's unintended that items like the garden potion don't have that banner visible right now, thanks for pointing that out!

**Comment by SunSparc** [comment]
I can take a look at this.

**Comment by Alys** [comment]
@SunSparc I'm sorry, the staff are working on this. It should have its status set to "in progress" so I've added that label.

**Comment by SunSparc** [comment]
@Alys, no worries. Thanks for letting me know. I am glad it is being worked on.

**Comment by Alys** [comment]
This has been fixed so I'm closing it. I think this was the commit that fixed it: https://github.com/HabitRPG/habitica/commit/168a3a6e89cdb53fed7ed5437d8f04a642dad7f5
