### ISSUE TITLE
Tagging one item tags it and the one beneath it

### ISSUE THREAD

**Issue by TahTheTrickster** [HabitRPG/habitica#1206]
I have three tags—Morning, Evening, and All Day—and have been trying to organize my habits and dailies with such. However, any one item I select to change the tags changes the tags for the one beneath it. Despite this, the item beneath it doesn't show up in the tag the first item is in, but I cannot change the tags for the lower item because it disables the tags for the upper item. And then it still does not show up in the tags I intended for the lower item to be in.

**Comment by jreatherford** [comment]
I am getting this issue as well

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
