### ISSUE TITLE
daily damage hit repeatedly today

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1207]
Today, sometime after my new day started (10 AM Pacific time), I took damage for my uncompleted dailies at least twice. @mindsandthings mentioned a similar problem -- she checked off all of her dailies yesterday, but still took a lot of damage when the day rolled over. Unfortunately neither of us was watching closely enough to know exactly when or under what circumstances it occurred.

**Comment by octern** [comment]
I just noticed that I lost streaks for a number of dailies that I checked off yesterday, so this might just be a garden-variety checks-not-recorded problem.

**Comment by lefnire** [comment]
0.5 framework upgrade coming very soon, should mitigate this issue
