### ISSUE TITLE
Lost Gold and XP : problem with Dailies ?

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1208]
Hello, 
I just logged in and lost Gold (99 Silver, then 2 Gold) and XP (twice). 

Everything else seems normal. I just didn't do one of my dailies yesterday (a dailie only available on Sunday) 

I guess it's an issue with the Dailies because 99 Silver and 2 Gold match the rewards of my 2 other Dailies.

**Comment by MllePandaRoux** [comment]
And now a Cactus Egg appears out of nowhere in my inventory o_O

**Comment by wc8** [comment]
Related to #759 possibly.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
