### ISSUE TITLE
Profile modal pops up incessantly if you press back button from PMs

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12096]
Reported by crThiago, reproduced by me in Firefox and Chrome:

> I found a bug, but I'm not sure it has been reported.
> 
> 1 - Open any user profile and click on PM. 2 - Now on the PM page click the back button on your browser. 3 - The modal of the user profile will always be opening.

The profile modal will go away and immediately come back over and over, if you click to dismiss it, but if you're really fast you can click on something else in the background and exit the inbox, and that seems to stop it.

**Comment by crThiago** [comment]
> O modal de perfil desaparecerá e voltará imediatamente e repetidamente, se você clicar para descartá-lo, mas se for realmente rápido, poderá clicar em outra coisa em segundo plano e sair da caixa de entrada, o que parece impedi-lo.

Even if you close the modal profile, it will continue to appear when you open any modal other than profile

**Comment by paglias** [comment]
Might be fixed by https://github.com/HabitRPG/habitica/pull/12010 but not sure

**Comment by paglias** [comment]
I think this has been fixed but reopen if it's not
