### ISSUE TITLE
habitrpg - avatar glitch

### ISSUE THREAD

**Issue by hulksmashley** [HabitRPG/habitica#1209]
My avatar has a glitch. The helm wasn't showing up and only a bald head is there. I tried having the head without the helm and it was the same and then I tried buying a new one (Red Helm) and it still remains the same. I use firefox as my browser and my user id is hulksmashley92.
![glitch](https://f.cloud.github.com/assets/4805048/697045/1578f4b6-dcf6-11e2-8208-9528a96ea5b1.png)

**Comment by lefnire** [comment]
try picking a hair style again (aka, male or female). I've seen this periodically but haven't had time to investigate, if part of your body disappears just pick it again from the customization options

**Comment by hulksmashley** [comment]
Thank you! I tried that and I now have hair but my helm still isn't showing up. I'm honestly just happy I have a normal looking avatar again though.

**Comment by lefnire** [comment]
hmm.. and "show helm" is checked? That's something I haven't seen before!
will revisit post 0.5 upgrade

**Comment by hulksmashley** [comment]
Here is a screencap of it with and without the helm checked. 
![habitrpg](https://f.cloud.github.com/assets/4805048/713563/c7475ede-ded2-11e2-8b24-874691b87e52.png)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
