### ISSUE TITLE
where do i find my api id and api token. this error is showing when my red progress bar is completed       Unable to log in to Habitica.  Check that you have the correct user-id and api-token in C:\Users\ASUS\AppData\Roaming\Anki2\addons21\1758045507\user_files\AnkiHabitica.conf.  These should not be your username and password.  Post at github.com/eshapard/AnkiHRPG if this issue persists.

### ISSUE THREAD

**Issue by whitewolf1012** [HabitRPG/habitica#12099]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by shanaqui** [comment]
On the web version, you can find your user ID and API key here: https://habitica.com/user/settings/api

If those are not working, it sounds like there might be an issue with the third-party tool you're trying to use. You'd need to post to github.com/eshapard/AnkiHRPG about that, rather than here. :)
