### ISSUE TITLE
How to setup production installation

### ISSUE THREAD

**Issue by Aeris1One** [HabitRPG/habitica#12093]
Hi,
I'm building a YunoHost package for Habitica, which will permit installing Habitica in a few clicks on a YunoHost server. This package have been many times requested by our community and is on the wishlist since a while !
But, to create this package, I need to know how to install Habitica in production mode and no in development because people who will install the package are, for the most, not developers and will need a stable environment.
Can you tell me how to install a production build of Habitica ?

**Comment by paglias** [comment]
Hi @Aeris1One ,

The production build of Habitica isn’t really different from the development one in terms of installation difficulty. The main difference is that setting NODE_ENV to production will enable a bunch of services like the payment providers but they will require you to setup your own accounts with them.

There’s also a lot of configuration specific to the Habitica.com website which isn’t easy to replicate so I would suggest to simply use the development build as running the software in production would be quite difficult without any advantages for low traffic instances
