### ISSUE TITLE
Dailies, habits and exp not being persisted

### ISSUE THREAD

**Issue by friscoMad** [HabitRPG/habitica#1210]
I first reached level 5 around wednesday last week since then every day when I log back I see how I am back to lv4 my exp was lost and my streaks are also at 0.
The funny thing is that I am almost dead due to this bug as I lose health every day and that is being stored perfectly.

I have searched but I am not sure if the bug has been reported or it is only server restoring previous backups when I am sleeping.
My id: c5d37533-1977-469f-a06f-2dca2ac12403
I use only firefox for W7 in 2 computers (home and office).

**Comment by lefnire** [comment]
due to #165 and general framework bugs, working on migration to Racer 0.5 and almost done (eta 1.5 weeks)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
