### ISSUE TITLE
Display descriptive error when tests can't be run due to absent database

### ISSUE THREAD

**Issue by benkelaar** [HabitRPG/habitica#12101]
### General Info
  * UUID: d71d2c57-a73d-4591-b64d-e688584a9092
  * Browser: Command line (zshell for me)
  * OS: Definitely macOS, but also in docker containers

### Description
When developing for habitica locally, running `npm run test:api:unit` without a mongo database running on localhost (default port) will timeout and give an undescriptive timeout error.

It's rather unintuitive that running the unit tests require a database to be up, so it can be hard to figure out that that is the way to fix this problem.

It does seem to specifically be the test:api:unit target that seems to have this problem, running `npm run test` works fine (Except that there's a test in test:common that seems to have a DST or time-zone problem or something (It keeps failing with day-off-by-one errors around midnight)).

In any case, throwing a descriptive error i.o. "Timeout exceeded" would really help new contributors get up to speed with how to run the tests.

#### ~Console~ Terminal Errors
```
[00:12:17] Starting 'test:api:unit'...


  1) "before all" hook
  2) "after all" hook

  0 passing (16s)
  2 failing

  1) "before all" hook:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) "after all" hook:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

```

**Comment by paglias** [comment]
We should try to avoid accessing the database in unit tests but that will require a bigger refactoring to be able to mock all database access. In the meantime a more descriptive error seems like a good idea

**Comment by fmaximus** [comment]
I see the issue also for `npm run test`.
I played with it a bit, and adding `test:prepare:mongo` helps to give a clear message.
PR on the way.
