### ISSUE TITLE
Broken sign in witj Apple from Safari

### ISSUE THREAD

**Issue by theTechGoose** [HabitRPG/habitica#12104]
Cant log into the guild website because  the bug prevents me from logging in.

 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/55964540/79639225-5ddb9c00-8158-11ea-9ab9-f00200740b49.png">

**Comment by paglias** [comment]
Hi @Rofer11607 , thanks for the report, do you know you Habitica username? If yes, could you post it here? Also did you previously sign up using the iOS app?

**Comment by theTechGoose** [comment]
I signed up with the IOS app but I am trying to log in with my macbook on safari using the sign in with apple option. When the form submits; the server responds with the JSON object above.

**Comment by paglias** [comment]
@Rofer11607 we've pushed a fix, could you try again?

**Comment by theTechGoose** [comment]
Now its saying "sign up not complete"

<img width="465" alt="image" src="https://user-images.githubusercontent.com/55964540/79640801-90d65d80-8161-11ea-8030-7882a56eff59.png">

**Comment by paglias** [comment]
cc @phillipthelen

**Comment by paglias** [comment]
It seems to be a problem specific to Safari, we'll try to push a new fix next week but in the meantime using a different browser should work

**Comment by paglias** [comment]
Safari on mac seems to have a particular behavior that doesn't work with our current code

**Comment by theTechGoose** [comment]
On a side note I've been teaching myself to code for the past year because I fell into a tech role within the company I work for; I'm pretty proficient with front end development and would be happy to assist with your project in exchange for the chance to work with other developers.

**Comment by paglias** [comment]
@Rofer11607 I pushed another fix, could you give it another try? I was able to login with Safari this time

**Comment by theTechGoose** [comment]
working now

**Comment by paglias** [comment]
great! thanks for testing and regarding the development work, we're always looking for help, [this](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths) is a good place to start
