### ISSUE TITLE
blue "Contributor Achievement" notification should remain on-screen until clicked

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12122]
When a player is given a contributor tier, the next time they sync on the website, a blue blue "Contributor Achievement" notification appears as shownn in the screenshot below. If they click on that notification, then a modal opens to that shows them more details about the contributor tier process.

That's all working as expected except that the blue notification disappears automatically after a few seconds. It should remain on-screen until they click on it or until they reload the website.

In case this is helpful to anyone working on this issue:
The screenshot below also shows a Streak Achievement notification. It has the same behaviour that the Contributor Achievement notification **should** have. I.e., when you get a streak achievement, its blue notififcation appears and stays there until you click on it (at whih time a modal appears).

I'm marking this as important priority because we've seen comments from several contributors saying that they hadn't realised that they'd been given a tier until they noticed that their Gem balance was higher than expected. Since contributor tiers are a reward for helping Habitica, it's important that contributors know when they've been given one. A blue notification that disappears by itself is too easy to miss.

![image](https://user-images.githubusercontent.com/1495809/80275968-864f3180-8728-11ea-9edd-a4d254c23b2f.png)

**Comment by PitiTheGrey** [comment]
I have an Idea about this. May I have a try, please.

**Comment by cvuorinen** [comment]
I can take a look at this. ~~Any pointers how to award a contributor tier on the local install to test it?~~ Found it.
