### ISSUE TITLE
Reset should unassign Stat Points (previously known as Attribute Points)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12123]
When you use [Reset Account](https://habitica.fandom.com/wiki/Settings#Reset_Account) (from User Icon > Settings > "Danger Zone" section), it correctly sets your Level to 1 but it does not reset your Stat Points. It should reset them as described below.

Ideally we'd fix this with the generic function described at https://github.com/HabitRPG/habitica/issues/6482 but that requires a large body of work and no one has taken it up yet. Doing a fix for Reset alone will be much simpler and will bring immediate benefits (e.g., for new players who were experimenting with Habitica and want a fresh start).

I'm marking this as "good first issue" although it's larger than we'd normally use that label for. The information below should help a new contributor though and you can comment here if you have any questions.

Stat Points are stored in a user's account like this:
```
{
    "stats": {
        "lvl": 14,
        "points": 2,
        "str": 3,
        "con": 3,
        "int": 3,
        "per": 3
    }
}
```

That's a user at level 14. They have 3 points allocated to each of the Stats (STRength, CONstitution, INTelligence, PERception), and they have 2 points unassigned.

After using Reset currently, the player's account will look like this, which is wrong:
```
{
    "stats": {
        "lvl": 1,
        "points": 2,
        "str": 3,
        "con": 3,
        "int": 3,
        "per": 3
    }
}
```

It **should** look like this:
```
{
    "stats": {
        "lvl": 1,
        "points": 1,
        "str": 0,
        "con": 0,
        "int": 0,
        "per": 0
    }
}
```

I.e., `stats.points` should the same as `stats.lvl` (1, the user's level) and the individual Stats should be set to 0.

This is where Reset sets the level to 1 so it would be a good place to reset the Stat Points:
https://github.com/HabitRPG/habitica/blob/d03e5e93b09f5a16598ed63b911c074d28c62368/website/common/script/ops/reset.js#L4-L9

We would want tests for this too. Below is the test for how Reset changes the level to 1. Tests for setting `stats.points` to 1 and the individual stats to 0 should be in the same file and can use similar code.

https://github.com/HabitRPG/habitica/blob/d03e5e93b09f5a16598ed63b911c074d28c62368/test/common/ops/reset.js#L47-L53

**Comment by PitiTheGrey** [comment]
I would like to give it a try, since I have been working with stats poitns on 3rd party tools a lot before. But I will have to set up my local Habitica install fist. May take a few days then.

**Comment by Alys** [comment]
@PitiTheGrey Great! I'll mark this as in progress for you and if you have any trouble with your local install, post to the Aspiring Blacksmiths guild and we'll help.

**Comment by FranzRome** [comment]
Whops! wrote in the wrong issue first.
Can i work on this?

**Comment by PitiTheGrey** [comment]
Couple of questions: 
1. Effects visually take effect after a page refresh only. Is that ok? 
2. I don't quite get how the test code works. How can I run that?

**Comment by Alys** [comment]
@D10master I'm sorry, @PitiTheGrey claimed it first. :) Thanks for wanting to help though!

@PitiTheGrey 
> Effects visually take effect after a page refresh only. Is that ok?

Hmmm. That's a good point. It's not ideal because it will be confusing to new players. The best fix is probably to make Reset reload the website after it's done everything else. The Orb of Rebirth does that (using code that I can't actually find at the moment).
If you want to make Reset do a reload as part of the fix for this issue, that would be great, but it's also fine if you don't. :) We can log a separate issue for it if needed.

> I don't quite get how the test code works. How can I run that?

Have a look at [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) on the wiki, in particular the section "Creating and Running Automated Tests" (much of the rest of that page will be useful too). If that doesn't answer all your questions, ask again here!

**Comment by citrusella** [comment]
@Alys Is this where rebirth reloads? Appears to be in the buy modal code. o.o (I looked up how to reload a page in Javascript and then searched for stuff like that in the files, so I'm about as confident as a kindergartener who just learned a big word for the first time. XP)

https://github.com/HabitRPG/habitica/blob/5ad30e815a2e8ef1178ea97836f51344b7392869/website/client/src/components/shops/buyModal.vue#L588-L590

(~~Aw, how do you make it do the magical fun code display? D:~~ Never mind! XD)

**Comment by PitiTheGrey** [comment]
I have issues with running: npm run test: 
On all sub-test errors appear:  
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v12.16.2
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [
6 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
6 verbose cli   'C:\\Users\\Marc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
6 verbose cli   'run',
6 verbose cli   'lint'
6 verbose cli ]
7 info using npm@6.0.1
8 info using node@v12.16.2
9 verbose run-script [ 'prelint', 'lint', 'postlint' ]
10 info lifecycle habitica@4.112.0~prelint: habitica@4.112.0
11 info lifecycle habitica@4.112.0~lint: habitica@4.112.0
12 verbose lifecycle habitica@4.112.0~lint: unsafe-perm in lifecycle true
13 verbose lifecycle habitica@4.112.0~lint: PATH: C:\Users\Marc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Marc\habitica\habitica\node_modules\.bin;C:\Users\Marc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Marc\habitica\habitica\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Users\Marc\AppData\Local\Programs\Git\cmd;C:\Users\Marc\AppData\Roaming\npm
14 verbose lifecycle habitica@4.112.0~lint: CWD: C:\Users\Marc\habitica\habitica
15 silly lifecycle habitica@4.112.0~lint: Args: [ '/d /s /c', 'eslint --ext .js,.vue .' ]
16 silly lifecycle habitica@4.112.0~lint: Returned: code: 1  signal: null
17 info lifecycle habitica@4.112.0~lint: Failed to exec lint script
18 verbose stack Error: habitica@4.112.0 lint: `eslint --ext .js,.vue .`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\Marc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:310:20)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\Marc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:310:20)
18 verbose stack     at maybeClose (internal/child_process.js:1021:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
19 verbose pkgid habitica@4.112.0
20 verbose cwd C:\Users\Marc\habitica\habitica
21 verbose Windows_NT 10.0.18363
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Marc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
23 verbose node v12.16.2
24 verbose npm  v6.0.1
25 error code ELIFECYCLE
26 error errno 1
27 error habitica@4.112.0 lint: `eslint --ext .js,.vue .`
27 error Exit status 1
28 error Failed at the habitica@4.112.0 lint script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

Anything I can do?

**Comment by PitiTheGrey** [comment]
Both reset.js files are updated. Shall I make a pull request? To Habitica's develop branch?

**Comment by PitiTheGrey** [comment]
https://github.com/HabitRPG/habitica/pull/12143

**Comment by Alys** [comment]
@PitiTheGrey Thanks for the PR! 

@citrusella You are correct! That was a good way to find it!
Thank you! When I make an issue for reset updating the page, I'll reference that code in case that's the solution chosen.

**Comment by PitiTheGrey** [comment]
The modal to atually post the reset is here:  
habitica/website/client/src/components/settings/resetModal.vue
Adding `windows.location.reload(true);` to line 45 
causes the page to reload after character reset. 

I hope there are no concerns about this.

Big thank you, @citrusella for your help!

Thankx, Piti!

**Comment by PitiTheGrey** [comment]
The reset does not change the class back to warrior. I am not sure if this is intended. Is it?

**Comment by citrusella** [comment]
I take it you deleted your comment because you found an answer, but just to confirm, the way I've always heard it is that it intentionally doesn't change your class to (opt-out) warrior if used after level 10.

**Comment by paglias** [comment]
This was fixed in https://github.com/HabitRPG/habitica/pull/12148
