### ISSUE TITLE
Duplicate guild members

### ISSUE THREAD

**Issue by Dexyne** [HabitRPG/habitica#1213]
I created a guild, but for some members - actually two, they have duplicate entries (same name and same userID).

One is in the guild with 2 entries and the second have 6 entries in the guild.
And each entries are in the guild members counter (on the public page).

I think this members try to enter in the guild with errors or no changes and try again, but not sure.

Note: The name of the guild is Laravel.

**Comment by NotChrisPlease** [comment]
When I first joined the developers guild I was listed twice.
I tried to leaving the guild and it removed one instance of me but I was still in the guild, I had to leave a second time to actually leave.

**Comment by hovancik** [comment]
I have such a members of guild too.

**Comment by lefnire** [comment]
I see what's going on, follow https://github.com/lefnire/habitrpg/issues/1286 for the deets. Will be fixing soon

**Comment by lefnire** [comment]
type something in chat, then refresh. it's a crappy hack that removes duplicates while we work on the rewrite

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
