### ISSUE TITLE
Suggestion: "push to top" for to-do list items

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#1214]
Since I have a very long to-do list, it would be really helpful for me to have a possibility to push an item to the very top of the list instead of dragging and dropping it - that would make re-ordering (as in picking out the most urgent things at the moment) much easier. Maybe a small arrow on the right side of the list items would be an option?

**Comment by wc8** [comment]
To vote head to this card on our Feature Request tracker: https://trello.com/c/DeJA1wan

**Comment by paglias** [comment]
Then i think we can close it if it's going to be tracker on trello.
