### ISSUE TITLE
/api/v3/user GET route is returning only 10 inbox messages - should return all

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12144]
_Note to contributors: I'm marking this as help wanted but before you start working on it it's important that you post here first and wait for a reply because it's possible that Habitica's staff will be fixing it themselves, which means if you've already starting on it your time would be wasted!_

Until recently, the [https://habitica.com/api/v3/inbox/messages](https://habitica.com/apidoc/#api-Inbox-GetInboxMessages) GET route was returning all inbox messages.

Currently it's returning only the most recent 10.

I think this problem started in just the past few days. I'm pretty sure that I used that route via a third-party tool on the weekend without noticing any problems, although if I was focusing on just recent messages it's possible the bug was happening then too.

**Comment by Alys** [comment]
I think this might be the commit that introduced the change: https://github.com/HabitRPG/habitica/commit/cbcc7cd47995744ad2f72b890f3e2d05a702c1f4
It has a "PM_PER_PAGE" variable set to 10, although I haven't checked if the functions that use that variable are used in API v3.

**Comment by Chuddington** [comment]
Hey everyone,

As the endpoint is a get method, would it be worth it to have the PM_PER_PAGE as a form of query string value, or as part of a header?  That way it can be configurable on the client side and a default of 10 can continue to be used in the backend until clients are updated to utilise said query string / header, without changing the current, unwanted behaviour until you're ready for it.  You can then have an option for it to also equal 'all' to go back to the initial functionality as well

**Comment by Alys** [comment]
I think the issue was that the PM_PER_PAGE limit was accidentally applied to version 3 of Habitica's API, instead of only to version 4. Version 4 is used solely by Habitica's official website and mobile apps, and it can be changed without notice to implement features that those official clients need. Version 3 of the API is used by third-party tools and its behaviour is not meant to change at all (or at least not without very good reason and ideally with sufficient notice so that developers of third-party tools have time to adjust their code in advance).

So the ideal fix for this issue would revert the behaviour of API v3 so that by default, all messages were shown.
In my opinion, it would be fine to have an optional query string for API v3 (that's good idea in fact) but if the query is not supplied, all messages must be fetched at once. It would probably be best for that default behaviour to remain in API v3 permanently to avoid a breaking change.

**Comment by Alys** [comment]
I've marked this as in progress since @negue is working on it
