### ISSUE TITLE
Play store/App store banner shown every time

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#12151]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Chrome/Safari/Firefox
  * OS: Android/iOS

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Now that the website is actually usable in mobile browsers (thanks to #12125), that smartbanner thing that promotes the native app on iOS and Android is a bit annoying since it's shown every time (and that small x to close it is even a little hard to hit by tapping). 

Would it be ok to add a longer time that it stays hidden? I mean I know there's the app and I have that too but sometimes I just want to use the website. 

There seems to be a feature to set custom ttl on the smartbanner.js package that's used to show that banner https://github.com/ain/smartbanner.js/blob/master/README.md#time-limited-close
So it shouldn't be any more work than adding one more smartbanner meta tag.

**Comment by paglias** [comment]
Sounds good to me, although the doc says:

> By default smartbanner would not reappear if closed

so it shouldn't actually reappear at all after you close it the first time?

**Comment by cvuorinen** [comment]
Well, it doesn't reappear during one browser session, since it seems to be using session cookie by default. So if you close the browser and open again, then it always reappears. In the readme at the top it says

> Close button that closes the banner and sets cookie to keep banner closed
> * for current session or for defined time

But anyway, since you think it's a good idea, I can make a PR.

Just one question. How long ttl should we set for the cookie? One month? One year? Something else?

**Comment by paglias** [comment]
One month seems reasonable. @Tressley do you have any preference?

**Comment by Tressley** [comment]
One month sounds good. We can always adjust if necessary. 👍
