### ISSUE TITLE
Lost 1 level + all money 

### ISSUE THREAD

**Issue by Tiszaid** [HabitRPG/habitica#1216]
Its been 2 months since I logged, 

I logged in expecting death, I lost 1 level. which was expected,

I completed old tasks i had finished, went back up to level 12, gained 20 coins to get a total of 43. Added a bunch of new tasks.

After i was happy with everything i Changed my URL to my gmail (without opening a new tab), then pressed command+back on the same tab to go back to habit RPG (on a new tab).. clicked on the tab only to have died again somehow, losing a level, going down to 11 again, then losing ALL my coins. 

i hope this makes sense. 

My account is the same as my github, Tiszaid.

What should i do? will i be reimbursed? 

Thank you

**Comment by lefnire** [comment]
I'm just about done with a framework upgrade to solve issues like this. In the mean time you can fix up your stats at Options > Settings > Restore

**Comment by Tiszaid** [comment]
You are filled with sweetness and kindness.

Thank you good sir.

**Comment by lefnire** [comment]
no YOU are! here are some gems.

**Comment by Tiszaid** [comment]
Thank you!!!!
