### ISSUE TITLE
Unresponsiveness when clicking on the + button

### ISSUE THREAD

**Issue by Chillchamp** [HabitRPG/habitica#1217]
Since the beginning of Habit-RPG I have the problem that after finishing a Task, no matter if Habit; Todo, or Daily the plus Button does not react. Sometimes I have to klick 10 or more times before my input is registered. Same comes for buying rewards.

**Comment by wc8** [comment]
Have you tried refreshing in between? 
Obviously, that is not a solution, but it might help reduce the number of clicks required.

**Comment by LotusEcho** [comment]
The same happens to me on Iceweasel 22.0 (Firefox) on Debian GNU/Linux. Oddly enough using the Android app to update things is much, much more responsive which is the inverse of what I've generally seen in websites versus apps.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
