### ISSUE TITLE
WatchOS?

### ISSUE THREAD

**Issue by josharmenta** [HabitRPG/habitica#12180]
Is anyone working on a watchOS integration? If not I can try to make a bit of time for one.

**Comment by Alys** [comment]
Drop in to the [Aspiring Comrades](https://habitica.com/groups/guild/2ff9822b-27f2-4774-98da-db349b57a38e) guild and ask there! :) That's where third-party developers hang out so if anyone's working on one, they're likely to be there. There's also information in the guild's description that's likely to help, and you can ask questions there if you run into any trouble! Thanks for offering!
