### ISSUE TITLE
Levelled up, all tasks deleted?

### ISSUE THREAD

**Issue by beenathemistry** [HabitRPG/habitica#1218]
Hi, I'm fairly new to Habit RPG. I levelled up a couple days ago and I noticed all my tasks got deleted on the website, but on the app they're still intact? I don't know if this is a bug or it's supposed to happen. I'm not sure if I should add them back again because I don't want to have duplicates on the app and I can't seem to delete tasks on the app version.

**Comment by lefnire** [comment]
Be sure you don't have any active filters

**Comment by beenathemistry** [comment]
OH that was it, I didn't know that woops. Thank you!

**Comment by lefnire** [comment]
np, will make it more obvious in the future
