### ISSUE TITLE
Searching party members via "View Party" in header fails ("unhandled promise rejection")

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12181]
From Report a Bug:

> _Jubineo @crThiago (12601b79-cf8e-44b7-94b9-2bafc97adc16): "hi guys, I found a bug, when I try search anything in group popup nothing happening.
> https://snipboard.io/THaWgo.jpg"_ 
> 
> 
> _Drandaerfin @healingjourneyman (c4d64716-9f93-4356-a436-0df52dbf44d5): "[@crThiago](/profile/12601b79-cf8e-44b7-94b9-2bafc97adc16) I can reproduce it, but only if I click on `View Party` in the header.
> When going to the Party page, and clicking on Member List, then filtering works."_

Confirmed in Chrome and Firefox; here's a dump of my console log:

> app.9c85943c.js:1 Unhandled promise rejection: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Full info: PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at https://habi…, type: "unhandledrejection", target: Window, …}
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Uncaught (in promise) TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at app.9c85943c.js:1
>     at u (chunk-vendors.8a5845dd.js:59)
>     at Generator._invoke (chunk-vendors.8a5845dd.js:59)
>     at Generator.S.forEach.t.<computed> [as next] (chunk-vendors.8a5845dd.js:59)
>     at r (chunk-vendors.8a5845dd.js:66)
>     at s (chunk-vendors.8a5845dd.js:66)
>     at chunk-vendors.8a5845dd.js:66
>     at new Promise (<anonymous>)
>     at chunk-vendors.8a5845dd.js:66
>     at a.searchMembers (app.9c85943c.js:1)
> (anonymous) @ app.9c85943c.js:1
> u @ chunk-vendors.8a5845dd.js:59
> (anonymous) @ chunk-vendors.8a5845dd.js:59
> S.forEach.t.<computed> @ chunk-vendors.8a5845dd.js:59
> r @ chunk-vendors.8a5845dd.js:66
> s @ chunk-vendors.8a5845dd.js:66
> (anonymous) @ chunk-vendors.8a5845dd.js:66
> (anonymous) @ chunk-vendors.8a5845dd.js:66
> searchMembers @ app.9c85943c.js:1
> searchTerm @ app.9c85943c.js:1
> nr.run @ chunk-vendors.8a5845dd.js:7
> Zn @ chunk-vendors.8a5845dd.js:7
> (anonymous) @ chunk-vendors.8a5845dd.js:7
> ue @ chunk-vendors.8a5845dd.js:7
> Promise.then (async)
> oe @ chunk-vendors.8a5845dd.js:7
> pe @ chunk-vendors.8a5845dd.js:7
> tr @ chunk-vendors.8a5845dd.js:7
> nr.update @ chunk-vendors.8a5845dd.js:7
> mt.notify @ chunk-vendors.8a5845dd.js:7
> set @ chunk-vendors.8a5845dd.js:7
> rr.set @ chunk-vendors.8a5845dd.js:7
> input @ app.9c85943c.js:1
> ne @ chunk-vendors.8a5845dd.js:7
> n @ chunk-vendors.8a5845dd.js:7
> Xi.o._wrapper @ chunk-vendors.8a5845dd.js:7
> app.9c85943c.js:1 Unhandled promise rejection: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Full info: PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at https://habi…, type: "unhandledrejection", target: Window, …}
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Uncaught (in promise) TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at app.9c85943c.js:1
>     at u (chunk-vendors.8a5845dd.js:59)
>     at Generator._invoke (chunk-vendors.8a5845dd.js:59)
>     at Generator.S.forEach.t.<computed> [as next] (chunk-vendors.8a5845dd.js:59)
>     at r (chunk-vendors.8a5845dd.js:66)
>     at s (chunk-vendors.8a5845dd.js:66)
>     at chunk-vendors.8a5845dd.js:66
>     at new Promise (<anonymous>)
>     at chunk-vendors.8a5845dd.js:66
>     at a.searchMembers (app.9c85943c.js:1)

To reproduce: click on "view party" in the header, type a couple of letters into the search bar.

**Comment by paglias** [comment]
I'll tackle this in #12179
