### ISSUE TITLE
Proxy error: Could not proxy request /api/v4/user/auth/local/register from liga.is:8080 to http://server:3000 (ENOTFOUND).

### ISSUE THREAD

**Issue by sergey-prosvirnin** [HabitRPG/habitica#12199]
Hi, I'm trying to build from running containers to run Habitica with the **docker-compose -f docker-compose.dev.yml up -d command**. I end up getting a broken frontend at ip_server:8080 and when I try to send a **Proxy error: Could not proxy request /api/v4/user/auth/local/register from liga.is:8080 to http://server:3000 (ENOTFOUND)**. In doing so, I have all three containers running.

```
      Name                     Command               State             Ports          
--------------------------------------------------------------------------------------
habitica_client_1   docker-entrypoint.sh npm r ...   Up       0.0.0.0:8080->8080/tcp  
habitica_mongo_1    docker-entrypoint.sh mongod      Up       0.0.0.0:27017->27017/tcp
habitica_server_1   docker-entrypoint.sh npm start   Exit 1                           
```

![image](https://user-images.githubusercontent.com/24830345/81730426-32697a00-9496-11ea-9849-a443f5119949.png)

**Comment by paglias** [comment]
Hi @sergey-prosvirnin the client should proxy requests to the server process which in your case seems to be configured to be at http://server:3000/, is that correct?

**Comment by sergey-prosvirnin** [comment]
Yes, as far as I can see in docker-compose.yml.

**Comment by paglias** [comment]
hmm could you try to change http://server:3000/ to http://localhost:3000/ and see if it works?

**Comment by sergey-prosvirnin** [comment]
How do you do that? Can you explain in detail?

**Comment by sergey-prosvirnin** [comment]
> hmm could you try to change http://server:3000/ to http://localhost:3000/ and see if it works?

How do you do that? Can you explain in detail?

**Comment by paglias** [comment]
We have a guide for using docker, https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Docker have you tried it?

**Comment by sergey-prosvirnin** [comment]
> We have a guide for using docker, https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Docker have you tried it?

Yeah, I've tried that guide. I was just running the docker-compose -f docker-compose.dev.yml up -d command from the habitica directory.

**Comment by paglias** [comment]
I see :( unfortunately I don't think anyone from the core team uses that method for running Habitica (pinging @SabreCat just in case), could you try posting in the Aspiring Blacksmiths guild to see if someone has had a similar issue and see how they fixed it? https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f

**Comment by fmaximus** [comment]
@sergey-prosvirnin Can you check the `habitica_server_1` container.
In the list you posted, it appears to be in state `Exit`,
so not running anymore.

**Comment by sergey-prosvirnin** [comment]
> @sergey-prosvirnin Can you check the `habitica_server_1` container.
> In the list you posted, it appears to be in state `Exit`,
> so not running anymore.

Thank you for pointing that out, I didn't notice right away. Now all the containers are up and the error is the same.

```
      Name                     Command               State            Ports          
-------------------------------------------------------------------------------------
habitica_client_1   docker-entrypoint.sh npm r ...   Up      0.0.0.0:8080->8080/tcp  
habitica_mongo_1    docker-entrypoint.sh mongod      Up      0.0.0.0:27017->27017/tcp
habitica_server_1   docker-entrypoint.sh npm start   Up      0.0.0.0:3000->3000/tcp
```

**Comment by sergey-prosvirnin** [comment]
> I see :( unfortunately I don't think anyone from the core team uses that method for running Habitica (pinging @SabreCat just in case), could you try posting in the Aspiring Blacksmiths guild to see if someone has had a similar issue and see how they fixed it? https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f

@paglias, it seems that the problem is in the server container, below the log from that container.

```
> habitica@4.141.2 start /usr/src/habitica
> gulp nodemon

[15:58:26] Using gulpfile /usr/src/habitica/gulpfile.js
[15:58:26] Starting 'nodemon'...
[15:58:26] Finished 'nodemon' after 238 ms
[15:58:26] [nodemon] 2.0.2
[15:58:26] [nodemon] to restart at any time, enter `rs`
[15:58:26] [nodemon] watching dir(s): *.*
[15:58:26] [nodemon] watching extensions: js,mjs,json
[15:58:26] [nodemon] starting `node ./website/server/index.js`
buffer.js:327
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:327:9)
    at Object.<anonymous> (/usr/src/habitica/website/server/libs/encryption.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module._compile (/usr/src/habitica/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.newLoader [as .js] (/usr/src/habitica/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/src/habitica/website/server/libs/email.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module._compile (/usr/src/habitica/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.newLoader [as .js] (/usr/src/habitica/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:977:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[15:58:30] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by fmaximus** [comment]
That seems like a missing property.
Did you copy `config.json.example` to `config.json`.
I suppose you'll have to do this, before running docker-compose up.

**Comment by sergey-prosvirnin** [comment]
I copied it again, but I'm getting an error.

```
Recreating habitica_mongo_1 ... done
Creating habitica_server_1  ... done
Creating habitica_client_1  ... 

ERROR: for habitica_client_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for client  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by sergey-prosvirnin** [comment]
> That seems like a missing property.
> Did you copy `config.json.example` to `config.json`.
> I suppose you'll have to do this, before running docker-compose up.

I copied it again, but I'm getting an error.

```
Recreating habitica_mongo_1 ... done
Creating habitica_server_1  ... done
Creating habitica_client_1  ... 

ERROR: for habitica_client_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for client  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by paglias** [comment]
That seems to be a docker compose  issue, https://github.com/docker/compose/issues/3927

**Comment by paglias** [comment]
I'm going to close the issue since it doesn't seem an error linked to Habitica itself but comment here if there are new updates
