### ISSUE TITLE
kinda death and lost of equipment after login from different PCs 

### ISSUE THREAD

**Issue by hovancik** [HabitRPG/habitica#1219]
So I have 2 laptops (both firefox - well one is Iceweasel 17 on Debian, other the latest Firefox on WIn7). 

I usually log in at Debian. Sometimes at Win. And no problem until today. 

In morning I checked in Debian, I was alive. Then I went to other dorm and later I logged from Win. It showed me that I am dead. I tried log-out, log-in but the same. I was still after dead. 

When I came back to the other dorm, and checked from debian, I wasn't dead, but lost my equipment (I upgraded my sword 3times or so).

On my Win I forget to clean cookies and so, but I did on Debian and it's still the same = my equipment is gone. After log in from Debian machine I haven't tried from Win machine yet. 

b45c33f6-4980-443e-9a29-62dc38018c0e

**Comment by wc8** [comment]
Did you use Settings > Danger Zone: Restore to correct it (or is that not working either)?
Were both browsers open at the same time? This might be related to #450.

**Comment by wc8** [comment]
P.S. [this](https://github.com/lefnire/habitrpg/issues/838#issuecomment-20295510) seems relevant.

**Comment by hovancik** [comment]
Ah, thanks, I used restore just now.

Browsers were not open at same time. It was a few hours difference.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
