### ISSUE TITLE
Automated testing (casper)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#122]
We need testing. [CasperJS](http://casperjs.org/). Mocha is great for server unit testing (and we absolutely need that too!), but what we need most is (1) client testing with casper, (2) load testing

**Comment by switz** [comment]
+1, attaching myself to this convo

**Comment by SEGEEK** [comment]
I am interested in helping out if I can.  I am a complete noob with CasperJS, but it seems similar enough to testacular that I am hoping I can be of use.

**Comment by lefnire** [comment]
@SEGEEK it's quite straight-forward. Check out https://github.com/lefnire/habitrpg/blob/master/test/browser.casper.coffee, if that looks like something you could get into read [Running Locally](https://github.com/lefnire/habitrpg/wiki/Running-Locally). You have to get the server running while you run the casper tests. Just test for the common criticals in the queue, like "are items being duplicated", "is any data being lost", etc

**Comment by lefnire** [comment]
Incidentally, if you can get a legitimate Testacular suite going for Habit, I'm more than willing to to switch over - it's just that I've played with many test frameworks and Casper is the only one that seemed to work with Derby (Derby does a lot of Dom magic)

**Comment by SEGEEK** [comment]
Sounds good, I will see what I can come up with.  I won't have time to do anything tonight but I should be able to get back at it tomorrow.

**Comment by lefnire** [comment]
So there are some basic tests now in `/test/casper/*.casper.coffee` - they're not all passing, and they need fixing up - but Casper has come a long way since the last time I tried to write client tests, and these files will provide a good starting point going forward. queueing in @SlappyBag and @toebu

**Comment by toebu** [comment]
Tried to get these tests working again. It seems to me that most of them are broken, but I'm not sure if I'm running them correctly and using the same version of casper (1.0.1) and phantom (1.8.1) as you are. It would be good to get them all working and I'll try to help. If you have a moment, I'd appreciate a quick how to on the wiki or so. That would also help to get other contributors to run the tests.

**Comment by lefnire** [comment]
They're definitely broken, I have a helluva time getting these things
working in general. Extremely important, but I've spent a good 6-7 days in
Habit just trying to get them working, only to toss in the towel. If you
can get them working, oh that would make the sailing so much smoother! I
don't have any cycles to write up a tutorial in the wiki, but if you want
to do a call / chat, email me

**Comment by lefnire** [comment]
currently in progress

**Comment by lefnire** [comment]
we'll be writing Karma tests as we go along in angular rewrite, & mocha tests against API
