### ISSUE TITLE
Added into new guilds without invitations

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#1220]
Yesterday I suddenly found myself a member of 3 more guilds, but I didn't get any kind of invite or confirmation request. They simply were there and I ran to change the password before recalling the invite feature in the guild's interface.

**Comment by nafoster** [comment]
Happened to me yesterday. I don't believe any of our accounts were hacked or cracked, but it may be related to the main system being updated.

**Comment by lefnire** [comment]
woa, what a strange bug! I'll revisit this right after the upgrade

**Comment by marphod** [comment]
I just found myself a member of 3 new guilds; 2 of which are for speakers of languages for which I don't.

Clicking on 'leave' didn't seem to do anything, either.  

(They are Fitocracy, Brasil, and 凡才の挑戦, For whatever that's worth.)

**Comment by SabreCat** [comment]
@marphod: Sometimes when this issue occurs, you get added multiple times to the guild. Take a look at the members list and see if there's a bunch of you listed. If so, leave that many times to get it to go away for real.

**Comment by lefnire** [comment]
I added a stupid janky workaround until we rewrite: chat in the guild's chatroom. Chat triggers sanitization on group properties, incl. member duplication. Then leave. 

It's ridiculous, i know :/

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
