### ISSUE TITLE
profile modal reopens inappropriately

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12200]
@shayyyyy (fd977ee7-5df7-4168-a116-e05ccc9c7b5c) reports:

**"Whenever I click out of something (Like completing a task or going between the party and task tabs) it shows a random person's profile."**

We've had this occurring in the past but we don't seem to have an open issue for it.

**Comment by paglias** [comment]
Can we ask them about console errors? Is it fixed by a reload?

**Comment by Alys** [comment]
I had asked them to email console log messages to us if it happened again but from what I've seen they haven't sent anything yet. I did suggest they reload if to stop it at least temporarily. That typically does stop this sort of problem.
