### ISSUE TITLE
Is it possible to make the group plan free?

### ISSUE THREAD

**Issue by sergey-prosvirnin** [HabitRPG/habitica#12201]
Hello, is it possible to make the group plan free? How do I turn off my credit card and Amazon Pay windows?

**Comment by paglias** [comment]
Hi @sergey-prosvirnin , this repo is used to host the code for Habitica.com where group plans are a paid features so we don't currently offer a way to disable the payments option and we're not likely to introduce the ability to here. But you can remove the code that requires the payments from your own copy of the code.
