### ISSUE TITLE
URLs containing non-English letters cannot be posted in markdown links

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12217]
If a URL contains non-English characters such as this Russian wiki page: https://habitica.fandom.com/ru/wiki/Снаряжение
then it can't be posted as a markdown URL in a chat message in Habitica. 

I.e., posting this to a guild will fail:
`[test](https://habitica.fandom.com/ru/wiki/Снаряжение)`

This shorter version with only one non-English letter fails too:
`[test](https://habitica.fandom.com/ru/wiki/н)`

This version with all English letters succeeds so the bug is defniitely triggered by non-English letters:
`[test](https://habitica.fandom.com/ru/wiki/C)`

The user sees "An unexpected error occurs" and this appears in the server logs:
```
message:TypeError: Cannot read property 'index' of null
    at /usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:132:15
    at Array.forEach (<anonymous>)
    at findTextBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:128:22)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:165:22)
```

The expected behaviour is that any valid URL should be able to be posted in a markdown link.

I'm marking this as high priority since it's preventing Habitica's wiki URLs being posted as markdown for a variety of non-English wikis (and I assume also some links from other web sites).

**Comment by Alys** [comment]
sorry, pressed enter too soon, more coming.

**Comment by Alys** [comment]
If a URL contains non-English characters such as this Russian wiki page: https://habitica.fandom.com/ru/wiki/Снаряжение
then it can't be posted as a markdown URL in a chat message in Habitica. 

I.e., posting this to a guild will fail:
`[test](https://habitica.fandom.com/ru/wiki/Снаряжение)`

This shorter version with only one non-English letter fails too:
`[test](https://habitica.fandom.com/ru/wiki/н)`

This version with all English letters succeeds so the bug is defniitely triggered by non-English letters:
`[test](https://habitica.fandom.com/ru/wiki/C)`

The user sees "An unexpected error occurs" and this appears in the server logs:
```
message:TypeError: Cannot read property 'index' of null
    at /usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:132:15
    at Array.forEach (<anonymous>)
    at findTextBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:128:22)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:165:22)
```

The expected behaviour is that any valid URL should be able to be posted in a markdown link.


I'm marking this as high priority since it's preventing Habitica's wiki URLs being posted as markdown for a variety of non-English wikis (and I assume also some links from other web sites).

**Comment by benkelaar** [comment]
@Alys Looks markdown-it doesn't show the link contents in the token contents if there are non-roman numerals in the link. Will see if there's already a bug-report on markdown-it for that.

**Comment by benkelaar** [comment]
Actually markdown-it seems to be doing the right thing, problem is (of course) the source-mapping code. The non-roman characters are url-escaped by markdown-it, so the link then no longer regex-matches the link in the source text. Makes sense. Will have a fix in about 5 minutes.

**Comment by Alys** [comment]
@benkelaar Thanks so much for jumping on this so quickly!
