### ISSUE TITLE
Party member avatar missing head

### ISSUE THREAD

**Issue by nafoster** [HabitRPG/habitica#1221]
![partymember-headless](https://f.cloud.github.com/assets/3391909/732139/14ae17b0-e27c-11e2-9f36-bbd37dd1cd64.png)

I have a 5 person party (including myself) and one of the members is missing his head. It also seems like he is missing his hands' skin color but the outlines are there. However, he cannot see this, only other party members can.

I asked him if he changed his helm or messed with any settings, but he hasn't responded to me.

**Comment by mendingwall** [comment]
thinking my bug might be related too? without and with the 'show helm' options:

![faceless](https://f.cloud.github.com/assets/4458182/756462/86f53226-e615-11e2-9156-8ff247ccf28f.png)

**Comment by nafoster** [comment]
Did you change your skin color recently?

**Comment by lefnire** [comment]
try re-selecting your skin in the meantime until I can take a look at this

**Comment by mendingwall** [comment]
I hadn't changed my skin color, reselecting did restore my avatar's face though. well, after a series of continuous script error popups. (cited as https://habitrpg.com/gen/bFAeiavSokqjjTCzN_zJaA.js:8)

**Comment by KatjeiDa** [comment]
I'm having a similar issue - my avatar suddenly lost all colour in its head, body and arms. When I go to my profile there are blanks under Hair and Skin Colour. Deselecting "show helm" makes my whole head disappear!

**Comment by lefnire** [comment]
For now just re-select your appearance prefs, this will be fixed in the rewrite

**Comment by KatjeiDa** [comment]
I can't reselect my appearance prefs - when I go to "Profile" ALL my appearance options either missing or blank

**Comment by paglias** [comment]
There is any javascript error? Open the console to see if there's any (ctrl+shift+j on chrome)

**Comment by KatjeiDa** [comment]
This is what I get when I click ctrl+shift+j:

Sync: Queue is empty app-7ca01d26.js:14
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by KatjeiDa** [comment]
For the record though I usually open HabitRPG in FireFox

**Comment by paglias** [comment]
@KatjeiDa did you saw this content in the console on the profile page or on the tasks page? if the latter, could you post what you see in the console when you are on the profile page?

**Comment by lefnire** [comment]
pushing fix to beta. Gonna do a quick test-run, then i'll push to prod. Her acct had some derby-wrought null preferences, and there's some funkyness in chat-message contributor analysis .
