### ISSUE TITLE
possible problem with quests: party quest data missing key and leader

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12222]
I've just found two parties that had active quests but the quests did not have an entry for `quest.key` or `quest.leader`

This was preventing a third-party tool from working correctly (two reports of that were how I found this issue) and would cause problems in Habitica too (e.g., not displaying the quest details in the party, not allowing the quest owner to force-start or cancel/abortt the quest).

I suspect it's a new problem because I haven't seen reports before today and I suspect it's more widespread than just two parties since it would be odd if there were two at once affected by a once-off glitch. It might be affecting all parties that start quests from now on, or it might be intermittent in some way.

I'm logging this here so it's obvious it's a **potential** known issue BUT I'm not currently certain that there's a code bug or what the circumstances are that could cause the issue to affect a party.

Anyone affected by it should post to the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild. Even though we don't yet know what causes this, we can repair individual parties' quests when they're reported to us.

**Comment by Alys** [comment]
One of the quest owners has said _"I believe I tried to abort/remove/complete it in the past"_ so that might be related. However when I tried to abort a quest it was correctly aborted.

**Comment by paglias** [comment]
Have we had new reports of this?

**Comment by Alys** [comment]
Not reports but I found other examples of it when I went searching through parties (without looking at private data such as party names or chat).

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitica/issues/12398 is one cause of this bug. There may or may not be others.

It may be worth assuming that https://github.com/HabitRPG/habitica/issues/12398 is the only cause and closing this until/if we find it still happening after https://github.com/HabitRPG/habitica/issues/12398 is fixed.

**Comment by Alys** [comment]
It may be worth assuming that https://github.com/HabitRPG/habitica/issues/12398 is the only cause and closing this until/if we find it still happening after https://github.com/HabitRPG/habitica/issues/12398 is fixed.

**Comment by SabreCat** [comment]
I'd say it's highly likely that #12398 is this issue, but with the cause clearly identified. Let's pursue a fix there, and if this one crops back up afterward, we can reopen it!
