### ISSUE TITLE
Stealth tooltip should state how many Dailies it will protect

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12220]
In the tooltip for Stealth, it should tell you how many Dailies will not cause damage if you cast the skill.

(This was a feature on the old site and was logged in https://github.com/HabitRPG/habitica/issues/9136 for a fix. Moving it to here to split up that issue.)

**Comment by alexandreabeh** [comment]
Hi! I'd like to work on this :) 

To confirm, it looks like according to https://habitica.fandom.com/wiki/Rogue#Stealth

that this should be the calculation
`
Number of dodged Dailies = 0.64 * (Total Number of Dailies [both due and not due]) * PER / (PER + 55)
`

Is that still accurate?

**Comment by Alys** [comment]
@alexandreabeh Thanks! I've marked it as in progress for you.

We try to keep the wiki pages accurate but they shouldn't necessarily be relied up when coding. It's best to get information directly from the source code. One of the easiest ways to do that is to use "git grep" to search for a keyword. For example:
`git grep -i stealth | grep -v "/locales/"`
(`-i` for case-insensitive searching; the normal grep at the end is to remove irrelevant hits from the text string files for English and other languages)
That will show you all the files that mention Stealth, and `website/common/script/content/spells.js` is the one that has the Stealth code in it, including the calculation.

Post here again if you need clarification of any of that or have more questions!

**Comment by alexandreabeh** [comment]
Thanks @Alys! Will do.

**Comment by alexandreabeh** [comment]
I've submitted https://github.com/HabitRPG/habitica/pull/12255 for initial review :)
