### ISSUE TITLE
new design for boss damage notifications from tasks and skills

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12221]
As stated by @Tressley at https://github.com/HabitRPG/habitica/issues/9136#issuecomment-575685571 :

"Here's a Zeplin artboard with how damage should be displayed: https://zpl.io/2p0d882
![image](https://user-images.githubusercontent.com/2686586/72626536-e871ec80-3918-11ea-98f2-5a6de8178183.png)
"

This design should be applied to the notification you see when you do damage to the boss by completing a task or by casting a skill (Burst of Flames, Brutal Smash).

To get an invitation to the Zeplin artboard to see the details of the design, please tell us your email address. If you don't want to post it here publicly, email admin@habitica.com and include the URL of this issue - however post here first to claim the issue so that someone else doesn't start on it!

**Comment by cvuorinen** [comment]
I can take this one.
Email: ~~redacted~~

**Comment by Alys** [comment]
@cvuorinen Awesome, thanks!

@Tressley or another staff member will send you the Zeplin invitation.

Post here if you have any questions!

**Comment by cvuorinen** [comment]
Ok, just to be clear, do you want the notification to look exactly like that on the image, or use same general styling that all other notifications use for font sizes, padding etc. and just use the text and icon like in the image? Because just setting the text and icon doesn't really look exactly like the image.

![Screenshot from 2020-05-25 23-18-11](https://user-images.githubusercontent.com/1764167/82841240-0c07fd80-9ede-11ea-8b63-ba8dc7923e5e.png)

**Comment by Tressley** [comment]
@cvuorinen -- Thanks for your quick work on this! I sent an invite to the email you provided above.

As for the current design, I'm sure you've seen that most of the existing snack notifications aren't following the proper margins and padding from the Zeplin artboard. This issue only calls for implementing the boss damage notification, so using the same general styling is okay for now.

However, if you don't mind a bit of scope increase, I wanted to do a quick re-visit on the snack designs to make them display better for the various cases (they're two years old now!) Would you be interested in updating the overall snack styling if I updated the designs this week and shared them here?

**Comment by cvuorinen** [comment]
@Tressley yes, I can update the styling too while am working on this anyway :+1:

**Comment by cvuorinen** [comment]
I made a PR already for just the icon & text change. I can make another PR later for the styling.

**Comment by cvuorinen** [comment]
@Tressley that PR now closed this issue, but I can still work on the styling when you are ready with the design. (Do we need a new issue for that, or it's ok to just discus it here?)

**Comment by Tressley** [comment]
Great, thanks for your work on this. Let's move the styling to a new issue. I can create that and ping you when it's ready. 👍

**Comment by cvuorinen** [comment]
@Tressley Hey. I guess that new issue for the notification styling never happened? I can still work on this if it's still something that needs done.

**Comment by Tressley** [comment]
@cvuorinen -- Ah, sorry, this was pushed onto our roadmap and is being handled internally while we work on some small UX improvements as well. Thanks for checking in though!
