### ISSUE TITLE
the same URL cannot be posted twice in a markdown link

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12223]
If you try to post the same URL twice in the same message (example below), it fails.
```
[here](http://habitica.wikia.com/wiki/The_Keep:Pirate_Cove/FAQ) 
[hier](http://habitica.wikia.com/wiki/The_Keep:Pirate_Cove/FAQ)
```

The error also occurs if there is text between the two links. Posting the same URL (with different text) is essential for multi-lingual posts.

The player sees "An unexpected error occurred" and the server logs show:
```
TypeError: Cannot read property 'index' of null
    at /usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:132:15
    at Array.forEach (<anonymous>)
    at findTextBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:128:22)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:165:22)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/chat.js:246:88)
```

The "Cannot read property 'index' of null" message also occurred in this issue: https://github.com/HabitRPG/habitica/issues/12217 which is now fixed but I've checked on our staging site and this new bug still occurs there.

The desired fix for this issue is to allow the same URL to be posted twice (or three or more times) but if possible it would also be good to have something that checks for whether the "Cannot read property 'index' of null" error would be thrown and if so, don't execute the code that would throw it. If that means that a more minor error occurs (e.g., formatting problems with the link), that might be acceptable, at least as a temporary workaround.

I'm marking this as high priority because the ability to post the same link with different text is very helpful for guilds where two or more languages are spoken. If the best solution for this would take some time but a smaller partial fix could be done quickly, it would be acceptable in my opinion for us to have the quick fix in place rapidly, with a second PR done later.

**Comment by paglias** [comment]
@benkelaar looks like `match` is null here https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/highlightMentions.js#L110-L120 in some cases?

**Comment by benkelaar** [comment]
> possible it would also be good to have something that checks for whether the "Cannot read property 'index' of null" error would be thrown and if so, don't execute the code that would throw it. If that means that a more minor error occurs (e.g., formatting problems with the link), that might be acceptable, at least as a temporary workaround.

I was thinking this would be a good idea last time but couldn't think of a proper way to test it. TDD gone wrong I guess :smile: 

Adding something like `if (!match || !match.index) return;` should prevent these errors from being critical. 

As for the bug it might be because some regex matches return a list of simple strings if there are multiple matches. In that case using matchAll and taking the first I think should fix it. However I'm not near a computer right now so can't check.

**Comment by benkelaar** [comment]
Found a PC, will implement both.

**Comment by benkelaar** [comment]
So the problem was not the match method, rather it was the fact that `.` in the first link would overeagerly match to include the second link. Now adjusted the unit test to actually test for the functional failure that would then happen.
