### ISSUE TITLE
Party member avatar missing head

### ISSUE THREAD

**Issue by nafoster** [HabitRPG/habitica#1222]
![partymember-headless](https://f.cloud.github.com/assets/3391909/732167/b7bec238-e27c-11e2-8921-904fc453d53d.png)

I have a 5 person party (including myself) and one of the members is missing his head. It also seems like he is missing his hands' skin color but the outlines are there. However, he cannot see this, only other party members can.

I asked him if he changed his helm or messed with any settings, but he hasn't responded to me.

**Comment by nafoster** [comment]
I'm sorry, I accidently submitted this issue twice. Feel free to delete this.

**Comment by claudevandort** [comment]
Maybe you're just dead :P

**Comment by lefnire** [comment]
There's a strange bug I'll be tackling sometime soon, where sometimes users
lose their avatar customizations, and instead of reverting to default it
removes that body item. They just need to re-click through customization
options.
