### ISSUE TITLE
avatar transformation buffs (Snowball, etc) can't be cast or removed on website

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12226]
On the website, you can't cast an [avatar transformation item](https://habitica.fandom.com/wiki/Transformation_Items) on yourself or on a party mate.

If the transformation is cast on you by someone using the mobile app, you can't remove it with the antidote.

It's expected that the effect will wear off when your next [cron](http://habitica.wikia.com/wiki/Cron) runs as normal, but if any player affected by this is finding it upsetting to be transformed, they can post to the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild to ask for an admin to remove the effect manually.

---

**Technical details:**

The transformation items still work on the mobile apps so this will be a website front-end bug rather than an API bug. The antidotes won't work on the mobile apps because they never have (unrelated to this issue).

Amongst the console errors are these:
```
Error: TypeError: "a.questProgress is not a function"
 r spells.js:80
 u runtime.js:45
 k runtime.js:271

Failed to log to loggly because of this exception:
TypeError: cyclic object value loggly.tracker.js:176:28
Failed log data: 
{...}
err: TypeError: "a.questProgress is not a function"
info: "v-on handler (Promise/async)"
sessionId: "a48168f3-1cc6-4e52-b0c1-cce0ba52b1ec"
vm: Object { _uid: 150, _isVue: true, "$options": {...}, ... }
```

The avatar transformation buffs are considered to be skills ("spells") in the code so any code related to the normal skills may be affecting the buffs. It's possible that the changes from the boss damage notification PR might be causing this issue. https://github.com/HabitRPG/habitica/pull/12173/files

**Comment by Alys** [comment]
On the website, you can't cast an [avatar transformation item](https://habitica.fandom.com/wiki/Transformation_Items) on yourself or on a party mate.

If the transformation is cast on you by someone using the mobile app, you can't remove it with the antidote.

It's expected that the effect will wear off when your next [cron](http://habitica.wikia.com/wiki/Cron) runs as normal, but if any player affected by this is finding it upsetting to be transformed, they can post to the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild to ask for an admin to remove the effect manually.

---

**Technical details:**

The transformation items still work on the mobile apps so this will be a website front-end bug rather than an API bug. The antidotes won't work on the mobile apps because they never have (unrelated to this issue).

Amongst the console errors are these:
```
Error: TypeError: "a.questProgress is not a function"
 r spells.js:80
 u runtime.js:45
 k runtime.js:271

Failed to log to loggly because of this exception:
TypeError: cyclic object value loggly.tracker.js:176:28
Failed log data: 
{...}
err: TypeError: "a.questProgress is not a function"
info: "v-on handler (Promise/async)"
sessionId: "a48168f3-1cc6-4e52-b0c1-cce0ba52b1ec"
vm: Object { _uid: 150, _isVue: true, "$options": {...}, ... }
```

The avatar transformation buffs are considered to be skills ("spells") in the code so any code related to the normal skills may be affecting the buffs. It's possible that the changes from the boss damage notification PR might be causing this issue. https://github.com/HabitRPG/habitica/pull/12173/files

**Comment by paglias** [comment]
Will make an hotfix

**Comment by Alys** [comment]
I wonder if it is because of this change from that PR, in the castEnd() function:
```
-      let beforeQuestProgress;
-      if (this.spell.target === 'party') beforeQuestProgress = this.questProgress();
+      const beforeQuestProgress = this.questProgress();
```

If I recall correctly, an earlier version of that PR had the `if` statement changed to `this.spell.target === 'task'`, which was the minimum needed to ensure the issue was fixed. That's likely to be necessary to prevent this new issue.

**Comment by Alys** [comment]
Also, this _might_ need to come back:
`-      if (!beforeQuestProgress) return null;`
because questProgress won't always be an integer and this might fail:
` if (questProgress > 0) {`

**Comment by paglias** [comment]
The issue seems to be that `questProgress ` is used only in that mixin but defined in a separate component so it's not available for avatar transformation items. I'll move it to the mixin. But in general this is a good example of why mixins are quite terrible and have been removed from React and I think are going to be deprecated in Vue 3

**Comment by paglias** [comment]
Should be fixed in https://github.com/HabitRPG/habitica/commit/032c95d5c84c3bfa76baca921f04ee394f2da195
