### ISSUE TITLE
Missing Daily Streaks

### ISSUE THREAD

**Issue by Flargleblargle** [HabitRPG/habitica#1223]
I tried to tick my dailies (all on 10 days) on another PC to usual, but when I did it deleted my streaks, and reset them to 0. Can someone please put my 3 dailies on 0 back up to 10 please? I definitely know I did them yesterday, so if that's possible that would be great. 
My ID: 5a159fb5-a5fc-4020-a79e-35f2d16dbdfd
Cheers!

**Comment by wc8** [comment]
You can: click Edit > Advanced Options for each daily.
I'm thinking the upgrade might help, if this is part of/related to the [handling multiple browsers on a single session bug](https://github.com/lefnire/habitrpg/issues/838#issuecomment-20295510)

**Comment by Flargleblargle** [comment]
Cheers for the help! All sorted now, thanks

Date: Tue, 2 Jul 2013 19:22:07 -0700

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
