### ISSUE TITLE
Achievements in profile modal overlap and are unreadable once you click "Show all"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12252]
![image](https://user-images.githubusercontent.com/8144640/83245863-3f29e580-a199-11ea-9f25-0186d7c574e1.png)

Reported on all browsers.

**Comment by paglias** [comment]
fixed in https://github.com/HabitRPG/habitica/commit/c9bf157c23775cb46d7994c048b80889f8c2fa33
