### ISSUE TITLE
tag screen too narrow for wide tags, especially as window size shrinks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12253]
_I'm marking this as suggestion-discussion for Habitica's staff to consider whether the Tags screen could be widened as described below, or whether another fix would be desirable._

When you click the "Tags" button to open the pop-up screen that displays your tags, the screen is rather narrow and tags that aren't very short will wrap. See the first screenshot below with my browser at full screen width.

The problem becomes more severe as the window width shrinks. See the second screenshot.

Since the new design of the Tags screen means that you can't use your tasks while you're looking at your tags, I'm wondering if it would be better if the tags screen took up more of the window space - you wouldn't lose any functionality from that and the Tags screen itself would be more usable.

_Thanks to Jubineo / @crThiago (12601b79-cf8e-44b7-94b9-2bafc97adc16) for reporting this._

**This screenshot was taken when my browser was at the full width of my screen:** 
![image](https://user-images.githubusercontent.com/1495809/83343316-04ac7e00-a33c-11ea-8820-fbdfea27962e.png)

**This screenshot was from my browser width was at a bit less than two-thirds of my screen (more than half the screen):**
![image](https://user-images.githubusercontent.com/1495809/83343336-4d643700-a33c-11ea-92d9-ebc1e752a6c6.png)

**Comment by Alys** [comment]
BTW @shanaqui has pointed out that if you make the browser window "too" small, the problem doesn't occur - the tags screen actually looks quite good then, and it takes up the full width of the window.

![image](https://user-images.githubusercontent.com/1495809/83349953-dfd7fb00-a37b-11ea-90b1-3ca0daace57d.png)

**Comment by Tressley** [comment]
Two changes I think we can make:
1. Move headings to above their respective tags so we don't have a column of white-space.
2. Set a min-width on the element to prevent it from looking like Alys' second screenshot.

I think we can go ahead and tag this as help wanted. 👍

**Comment by wwyl1234** [comment]
I think I can do this. It is just changing one of the vue files .

I think this file needs to be changed to incorporate the 2 changes from Tressley's comment:
 https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/tasks/tagsPopup.vue

**Comment by paglias** [comment]
thanks @wwyl1234 ! I'll mark the issue as in progress for you, let us know if you have any question

**Comment by wwyl1234** [comment]
The file that I mentioned before is not the issue seen here but the tag pop ups from adding tags to a task.

**Comment by wwyl1234** [comment]
I have a fix for this (haven't commit it yet). Let me know if there is a need to want the fix for this problem to be consistent to tag pop ups (see attached file).
![Screen Shot 2020-06-17 at 9 55 00 PM](https://user-images.githubusercontent.com/30581379/84968823-5b100f80-b0e5-11ea-8785-6a0512f6334a.png)

**Comment by paglias** [comment]
Hmm let see what @Tressley thinks

**Comment by Tressley** [comment]
This doesn't need to touch the tags component within the task modal, only the task board. We're actively working on improvements to the overall modal that address the tag component as well.

**Comment by wwyl1234** [comment]
https://github.com/HabitRPG/habitica/pull/12332

Okay, I made a pull request.
