### ISSUE TITLE
changing due date twice on a new To-Do does not update the view

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12254]
If you create a To-Do, then set a due date, the due date appears correctly. If you immediately change the due date, the new date does not appear (you still see the first one). When you sync, you see the second date, so this is merely a display problem, not a problem with the date being saved to the database. After you have synced, the problem no longer occurs.

Steps to reproduce:
1. Create a To-Do using the "Add a To-Do" box at the top of the To-Dos column.
1. Click the To-Do to open its edit screen.
1. Set a due date (any date will be fine for this, including one in the past).
1. Click the save button (either the top or bottom save button is fine - they work the same for all steps here).
1. Observe that the date you selected is accurately represented in the text at the bottom left of the task.
1. Click the To-Do to open its edit screen.
1. Change the due date (any date different from the first one).
1. Click the save button.
1. Observe that the date represented in the text at the bottom left of the task has NOT changed. It still indicates the original date you set, not the new one.
1. Click the sync button in the header. 
1. Observe that the second date you selected is now accurately represented in the text at the bottom left of the task.
1. Click the To-Do to open its edit screen.
1. Change the due date (any date different from the previous two dates).
1. Click the save button.
1. Observe that the third date (the one you just selected) is accurately represented.
1. Repeat the date edits if desired; observe that each new date is accurately represented immediately - no further syncs are needed.

_Thanks to Jubineo / crThiago (12601b79-cf8e-44b7-94b9-2bafc97adc16) for reporting this._

**Comment by Alys** [comment]
For anyone curious, the "help wanted" label on-again off-again dance you can see just up there was from me testing a problem with the webhook that posts issues to Aspiring Blacksmiths. I've reported it to the staff.

**Comment by bigsee** [comment]
@Alys never contributed to an open source project before but I wouldn't mind starting here if no-one else has taken this one and slower delivery isn't a problem?

**Comment by Alys** [comment]
@bigsee Hi! Thank you, please go ahead! We've seen only one report of this bug so it looks like it's not inconveniencing a lot of people, so slower delivery sounds okay for this. If you have any questions or run into trouble, post here and we'll help. :)

**Comment by bigsee** [comment]
@Alys great - thank you! :)

**Comment by bigsee** [comment]
@Alys I didn't add any unit tests and wasn't sure whether it was appropriate. Not sure whether that would be appropriate but happy to look into it if so.

**Comment by Alys** [comment]
@bigsee If [Habitica's staff](https://habitica.fandom.com/wiki/Staff) say anything different than I do here, listen to them not me. :) My feeling is tests wouldn't be needed because this is just a website front-end change. As a general guideline though, if the staff think that tests will be needed, they'll say so in a comment on your pull request. Thanks very much for asking about this! I appreciate your willingness to consider tests. :)

**Comment by paglias** [comment]
Regarding the tests, we don't require tests for client side changes as we don't have many but if you want to add one it would be great, ideally we'd like to increase the client side coverage

**Comment by shanaqui** [comment]
@bigsee Hi! Are you still working on this issue? If not, or if we don't hear from you within seven days, I'll mark this as help wanted again. :)

**Comment by bigsee** [comment]
Hi @shanaqui - apologies for the delay. Since submitting a PR and waiting for a review I got very busy with work. I do intend to finish this and will make some time this weekend. Please feel free to re-assign if this is more urgent than that though!

**Comment by shanaqui** [comment]
@bigsee If you're intending to keep going with it, that's fine! We just check in to make sure things don't go totally stale. :)

**Comment by bigsee** [comment]
@shanaqui thank you for checking in. :) just made an updated PR that hopefully solves this. and apologies again for the delay.
