### ISSUE TITLE
Game-Breaking Bug: Suspended Character

### ISSUE THREAD

**Issue by svetlashka** [HabitRPG/habitica#1226]
When I played a couple of months ago, there was a feature letting you suspend a character for things like travel and vacation (basically, you wouldn't lose health for not checking off dailies). When I returned from my trip, there was no longer a feature to un-suspend my character. I see "Zzzz" next to my character indicating suspension, my dailies no longer longer respond to the passage of time, etc. and as far I see, there is no longer any way to turn this off. Ideas? Suggestions? Fixes?

**Comment by wc8** [comment]
I think this is part of #997 and it'd be best to follow up there in that case,
 but, do you not see a Check Out of Inn or Rest in the Inn button under Tavern? 
If the latter, have you tried clicking and un-clicking that?

**Comment by svetlashka** [comment]
Ah yes, it's just a different way of handling the same function, but I didn't notice that it corresponded with the "suspend" mechanic. That seems to have worked for me. Thanks!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
