### ISSUE TITLE
Challenge tags are not converted to normal tags after a Challenge link is broken

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#12276]
When a Challenge ends (or is deleted) the associated tag should be converted to a normal tag and sorted properly in the tags dropdown. Currently, when a Challenge ends, the tag is still considered a Challenge tag and sorted incorrectly.

Cleanup of #7569. You can visit that ticket to see the full history of discussion on this issue.

**Comment by tsukimi2** [comment]
@Tressley May I help out with this issue?

**Comment by Alys** [comment]
@tsukimi2 Please do! I've marked this as in progress for you.

**Comment by tsukimi2** [comment]
@Alys Not directly related to this particular issue, but as I was testing out challenge tags when implementing the bug fix, I noticed that if a user joined a challenge with a task (let's say with task title ToDo1) and then leave the challenge afterward (but without deleting the associated tasks), and then later on decide to join the same challenge again, the task list will display the associated task in duplication.  (In this example, ToDo task list will have two ToDo1 tasks).  Just want to confirm is this the expected behaviour? Thanks.

**Comment by Tressley** [comment]
@tsukimi2 -- This is the expected behavior. Once a user leaves a Challenge and keeps the Challenge tasks, they are no longer associated with the Challenge. Should the user choose to re-join that Challenge, a duplicate Task has to be created to track their Challenge participation.

One thing to note while working on this is how tag filtering will be handled in your example. ToDo1 should only be filtered by the non-Challenge tag, while ToDo2 should be filtered by the Challenge tag, despite them having the same string.

**Comment by tsukimi2** [comment]
> @tsukimi2 -- This is the expected behavior. Once a user leaves a Challenge and keeps the Challenge tasks, they are no longer associated with the Challenge. Should the user choose to re-join that Challenge, a duplicate Task has to be created to track their Challenge participation.
> 
> One thing to note while working on this is how tag filtering will be handled in your example. ToDo1 should only be filtered by the non-Challenge tag, while ToDo2 should be filtered by the Challenge tag, despite them having the same string.

@Tressley Ic.  Thanks for the explanation.  ^_^

**Comment by shanaqui** [comment]
@tsukimi2 Hi! Are you still working on this issue? If not, or if we don't hear from you within a week, I'll mark this issue as help wanted again. :)

**Comment by tsukimi2** [comment]
@shanaqui Sorry, been busy lately.  Will work on this again during this weekend.  Thanks for the reminder.

**Comment by shanaqui** [comment]
Hi @tsukimi2! Just checking in again as usual to make sure the issue hasn't gone stale! :)
