### ISSUE TITLE
123 popup

### ISSUE THREAD

**Issue by xyviar** [HabitRPG/habitica#1229]
I keep getting this popup: http://i.imgur.com/82h9LEE.png

Happens every time I refresh or reopen the page.

**Comment by lefnire** [comment]
Ha, wtf that's so weird! There's no "123" confirm / alert in the code
anywhere, just did a grep to be sure. Let's revisit this after I push the
upgrade and see if your'e still experiencing it

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
