### ISSUE TITLE
Chrome extension won't install

### ISSUE THREAD

**Issue by BXQ** [HabitRPG/habitica#123]
Attempting to download the Chrome extension results in an error saying "Download was not a CRX". Attempting to manually install the downloaded file results in an error saying "Package is invalid: 'CRX_MAGIC_NUMBER_INVALID'"

**Comment by lefnire** [comment]
Yowzer! k, will check out once we stabilize the website. This should probly go here https://github.com/lefnire/habitrpg-chrome, but next time.

**Comment by hookang** [comment]
I didn't have any issues. @BXQ Are you still having issues installing the chrome extension?

**Comment by lefnire** [comment]
Someone mentioned needing to be in development mode, is that the issue?
Also, the chrome extension has its own github repo and issue queue, the
only reason I mention that is there's a developer there providing a lot of
help that will benefit from this info

**Comment by hookang** [comment]
Weird. I'm not in developer mode... or at least I'm not aware of that I am in developer mode.

**Comment by StanLindsey** [comment]
I've had no issues with non-developer mode. 

That said my GFs install had the small issue as @BXQ but after a number of re-tries it worked fine. I'll add it to my to-dos to check though.

**Comment by Cyberlyme** [comment]
HI there, I don't know if this will help or not but I was having the same issue, I have been trying over several days to install the program and getting the same error and have noticed today that I was not logged in to Chrome. I have done this and the Extension appears to have installed.

like I say not sure if this helps or not.

**Comment by lefnire** [comment]
the extension was updated recently, i forgot to post back here (the extension has it's own [issue queue](https://github.com/lefnire/habitrpg-chrome/issues)) - if anyone still has issues installing now, re-open this ticket
