### ISSUE TITLE
Can no longer create decimal reward values

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1230]
I like to do the odd ".5" or "2.5" gold reward, and have some of those in my list already. However, I can no longer create new rewards with this format. If I type a decimal point, the editing box goes red, and when I try to Save and Close, it reports "invalid value" in a text bubble with a red exclamation point.

My existing fractional-gold rewards still work fine.

**Comment by SabreCat** [comment]
Chrome browser only? Tried on Firefox this morning and it went through OK.

User ID 7f14ed62-5408-4e1b-be83-ada62d504931

**Comment by Gaelan** [comment]
I think that the text box is setup to only accept integers (using html5 validation). However, only some browsers (Chrome) support HTML5 validation, so only they actually stop you from submitting. I get the red border as well (on Safari), but it lets me save, so I think that the red border is separate from the HTML5 validation (but maybe a polyfill), and whatever is creating the border does not prevent saving.

**Comment by SabreCat** [comment]
I seem to recall from some help text (maybe part of the tutorial?) that decimal values were explicitly suggested, saying that fractional gold would come out as silver. So that field should probably be set to allow two decimal places, HTML5 or no.

**Comment by SabreCat** [comment]
Found where I remembered seeing advice about fractional gold. It's in the FAQ: http://community.habitrpg.com/faq-page#n84

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
