### ISSUE TITLE
Lost progress

### ISSUE THREAD

**Issue by Perlkonig** [HabitRPG/habitica#1231]
Two days in a row, now, I've suddenly lost progress. Yesterday morning I leveled, and then that evening I was back at my previous level. Most of the tasks I marked as completed rolled back, but some didn't. So I just kept going on and then I leveled again this morning. Well lo and behold, tonight I log on and the same thing happened. This time my HPs did some weird stuff, too. I usually use my desktop browser (Chrome), but I've also used my Android phone (default browser) and I tried a standalone Android client for a bit as well. Any ideas? I'm about to reroll and then just try again and hope.

UserID: 21bd123b-1642-4980-a27b-5f836359b656

**Comment by wc8** [comment]
**Restore**: Go to settings > Danger Zone: Restore and restore your character as appropriate.
I'd try to avoid having two browsers open or open for a long time in the meantime.

**Comment by Aubec** [comment]
I ran afoul of what seems to be a similar issue over the last two days.  Some of the dailies that I completed and some of the tasks that I entered didn't stick overnight, and I subsequently lost HPs for the dailies.

UserID: 228a0207-6355-471a-84cd-7de7bba7feee

**Comment by seajules** [comment]
I have to restore my character every single time I restart my browser, so I've taken to writing down my most current stats in a separate text file whenever I have to close programs or restart my computer.  It's very inconvenient.  I also constantly lose egg and potion drops this way.  Just today, I have lost two white potions and a zombie potion, all of which would have come in very handy.

**Comment by lefnire** [comment]
We're working on a complete rewrite of the site, in the meantime can you
see if these tricks help you?
http://habitrpg.tumblr.com/post/55792029689/bug-workarounds

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
