### ISSUE TITLE
Guild weird text

### ISSUE THREAD

**Issue by hovancik** [HabitRPG/habitica#1232]
I have guild called "BSD - Berkeley Software Distribution" 

If you visit it, you will probably see what is wrong: there is a bunch of weird text like; 

d one day it will hatch into a loyal pet.","type":"Egg","dialog":"You've found a Cactus Egg! Find a hatching potion to pour on this egg, and one day it will hatch into a loyal pet.","modifier":"CottonCandyBlue","str":"Cactus-CottonCandyBlue"},"eggs":[],"hatchingPotions":["Desert","Base","White","Base  

and so and so. 

Seems like it's instead of my pic as guild owner that is at the top. 

What I did recently (minute before I found out guild error ) was change of pet. Maybe that's the issue. Yesterday guild was looking as usual.

**Comment by lefnire** [comment]
woa mama. @hovancik what's your UUID?

**Comment by hovancik** [comment]
b45c33f6-4980-443e-9a29-62dc38018c0e

**Comment by lefnire** [comment]
ok, I fixed this. For some reason the group didn't get the `leader` field (being your UUID), and it wasn't falling back gracefully when no leader is present. I'm leaving open for now until I fix that

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
