### ISSUE TITLE
Webhook update route requiring "type" to be explicitly sent when changing options

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12336]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: cab16cfa-e951-4dc3-a468-1abadc1dd109

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

From the Report a Bug Guild:

>There is an bug with the "Edit a webhook" (PUT https://habitica.com/api/v3/user/webhook/:id) endpoint which prevents you from modifying the webhook's options field. The update request itself actually returns the properly updated webhook, but if you fetch the webhook again you'll see that the changes don't persist. I did discover a workaround for this: if you change the type of the webhook (e.g. from taskActivity to userActivity) and then change the type back and provide the new options you want, the options will actually be saved.

Looking at the `formatOptions` function called from the webhook model, the `options` field is discarded if an appropriate `type` isn't found:

https://github.com/HabitRPG/habitica/blob/release/website/server/models/webhook.js#L90-L131

I would have expected that to get pulled in when the target webhook is found here in the controller...

https://github.com/HabitRPG/habitica/blob/release/website/server/controllers/api-v3/webhook.js#L194

...but possibly that's not happening as expected?

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

Searching server logs for this user's webhook-related requests, there were some timeout, missing auth header, and connection refused errors, but nothing that clearly points to this issue.

**Comment by SabreCat** [comment]
I haven't personally reproduced this yet, so marking as Needs Investigation, though the user reporting the issue has volunteered to look into it.

**Comment by robwhitaker** [comment]
@SabreCat Fyi, I'm the one who reported it ([@rhitakorrr](https://habitica.com/profile/cab16cfa-e951-4dc3-a468-1abadc1dd109)). I'll hold off on looking into it until you give the go-ahead.

**Comment by SabreCat** [comment]
@robwhitaker Feel free--I was holding it open for you!
