### ISSUE TITLE
Can a red subtraction-only habit turn green/yellow again?

### ISSUE THREAD

**Issue by Gaelan** [HabitRPG/habitica#1233]
I've turned a subtraction-only habit red. Is it possible to make it green/yellow again? Maybe even collect coins/XP from it? I'm assuming that it automatically improves over time. Does it?

**Comment by lefnire** [comment]
yea, each day "onlies" go a tick back to their original yellow (0-value) state.

**Comment by Gaelan** [comment]
Thanks!
