### ISSUE TITLE
can't edit habits/tasks

### ISSUE THREAD

**Issue by satisnunc** [HabitRPG/habitica#1234]
Clicking on the edit button doesn't expand the tasks.

**Comment by wc8** [comment]
Have you tried refreshing your browser, clearing cache and/or made sure the page is fully loaded?

**Comment by janosgyerik** [comment]
This happens to me too, seemingly randomly. Typically it happens in one of the columns, while the others are fine. If I try clicking on different edit buttons in the column, some items may work, others may expand/collapse a completely different item within the same column. It's quite crazy. Reloading the page fixes it. 

I see this happening in Chrome browser, in Linux and Mac. 

I've seen this in at least in the Habits and the Rewards columns.

**Comment by janosgyerik** [comment]
Hm I just noticed something. Right now I had this problem in the Habits column, and the JavaScript console says: 

```
42fa1641-e88b-42d9-a892-cb3ba544144b's habits were corrupt. 
```

That id is me, of course. So it makes sense: my "corrupt habits" broke the UI :) Perhaps this can be handled gracefully by checking for errors and reloading habits if they are corrupt? Just wondering, haven't looked at the code yet...

**Comment by lefnire** [comment]
What's happening is Derby 0.3 has a bug where operations can be duplicated.
Eg, if you delete a task, the "delete" operations sends a bunch of times
and just clobbers your habits. Same with "add", and you get duplicates. So
I have some hack-job script to restore your old list, and evidently it
requires a refresh before the UI is usable.

This stuff should be fixed (and is one of the major fixes) in the upcoming
0.5 release. Stay tuned.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
