### ISSUE TITLE
Beginner wanting to contribute

### ISSUE THREAD

**Issue by rsivapr** [HabitRPG/habitica#1235]
I want to start contributing and learning node on the way. 

I cloned the `develop` branch and ran it successfully according to the instructions in the wiki. The problem I am facing is that I am not able to edit anything. I tried to edit the `habitrpg/locales/en/app.json`, but it does not reflect when I run it again. What am I looking at here?

Anybody feel patient enough to guide me here?

**Comment by svemir** [comment]
I dont think locales are setup in a way that would get used automatically even when you restart. If you just want to hack around, you could start with the files in habitrpg/views/app/ - for those you do not even need to restart node, just reload.

**Comment by lefnire** [comment]
If your'e working on translations, I believe you'll need to have the translations branch checked out. Follow the instructions https://trello.com/card/translations/50e5d3684fe3a7266b0036d6/12, there's an instructional youtube video there

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
