### ISSUE TITLE
Missing white hatch Potion

### ISSUE THREAD

**Issue by kirune-tora** [HabitRPG/habitica#1236]
Yesterday night I'd found a white hatching potion.
I checked it on my inventory
I tried to use it (clicking on it) and failed miserably.
Today I checked the inventory and the Potion is not there.
First there was some kind of missing icon empty space (white rectangle). Now it show the "You don't have any hatching potions yet." sentence.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
