### ISSUE TITLE
Alter API to allow Bulk Feeding 

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#12368]
Due to the API Limits to soon come into affect, bulk hatching and feeding pets will become very slow through the API. Tools like the [Bulk Pets Feed Tool](https://oldgods.net/habitica/cTheDragons/feed.html) will take a long time for users to complete triad bingo quickly as well as feed all their quests pets.

Please could we alter the  [/user/feed/](https://habitica.com/apidoc/#api-User-UserFeed) similar to [/user/sell](https://habitica.com/apidoc/#api-User-UserSell) to allow a query parameter of amount. If it is not specified it will assume amount of one.

**Comment by Alys** [comment]
Approval for this issue was given by paglias in the Aspiring Comrades guild so I'm marking it as Help Wanted.

For anyone who wants to work on this:
This is purely an API change. The bulk feed option doesn't need to be supported in the website or official mobile apps. They should continue working as normal - i.e., the query parameter added to [/user/feed/](https://habitica.com/apidoc/#api-User-UserFeed) must be optional, and when not specified it defaults to a value of 1 as cTheDragons says.

**Comment by PitiTheGrey** [comment]
Bulk feeding sounds like a good idea. Not sure if I can catch up with the 'medium level', but I'd like to give it a try.

**Comment by Alys** [comment]
@PitiTheGrey Thank you! I'm marking it as in progress for you. If you have any questions or run into any trouble, post here and we'll help!

**Comment by PitiTheGrey** [comment]
Do we want to make comrades' lives easier and check if the query-amount exceeds the necessary amount of feeds to make a pet become a mount, or will we leave them calculating this themselves?  
In case we want to help them: "how do I establish a new 'eror message': 'query amount too high.'"

**Comment by Alys** [comment]
Excellent question! Thank you for asking.

The easiest thing for both the end user and the Comrades may be for the API to not actually throw an error at all. Instead, it could let the user specify a number as high as they liked, then it would check if that number were more than needed and if so, it would use only as many foods as actually needed.

For example, I, as an end user see that I have a Base Wolf that's partly fed. I don't bother working out exactly how fed it is, I just tell the API to use 9 Meat foods, and then the API calculates that only 5 are needed so it uses only 5.

However wait for Habitica's staff to comment on this in case they don't like that idea. :)

If you do want to add a new error message string, you'd create it in one of the json files under /website/common/locales/en - you would use [pets.json](https://github.com/HabitRPG/habitica/blob/develop/website/common/locales/en/pets.json) for this case. You don't need to create a matching string for the other languages (see the README file in that directory for details). 

The message could be something like `You have specified too much Food. Only <%= maxAmount %> is needed.` where `maxAmount` is a variable that holds the amount of Food needed. You don't have to use that exact variable name or that exact wording. :)

For an example of how to use variables in translated strings, search through the code base for the `clickOnPetToFeed` string using `git grep clickOnPetToFeed`

**Comment by paglias** [comment]
Hmm if a number of food items to feed is passed I'd prefer it to throw an error, but I don't have a strong opinion. Maybe we could have a `feed all` where it feeds the necessary amounts of food until the user runs out or the pet becomes a mount?

**Comment by PitiTheGrey** [comment]
I made a pull-request for the bulk feed. It indeed works like Alys suggested. Does the code look too messy?  
I wouldn't mind if I was told to change it to `feed all` like paglias suggested.  
On the other hand `all` is equal to `?amount=23`.  
Please tell me what you think.  
Piti!

**Comment by paglias** [comment]
Fixed in #12384
