### ISSUE TITLE
API should prevent Chilling Frost and Stealth skills being cast when there is no point

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12361]
The Mage skill Chilling Frost will prevent the streaks from all your incomplete Dailies being set to zero when cron runs. This skill needs to be cast only once on each day. Casting it more than once on the same day has no additional benefit and just wastes Mana.
**The API should prevent Chilling Frost from being cast if it has already been cast that day.**
I.e., if the user has `stats.buffs.streaks` set to `true` and the user tries to cast `frost` again, the API should prevent the skill from having any effect and should return the string `spellWizardFrostAlreadyCast` as an error message.

The Rogue skill Stealth prevents incomplete Dailies from causing damage when cron runs. Only some Dailies are affected each time it's cast, so it is sometimes correct to cast it more than once each day, but after all your Dailies have been protected, the skill has no no additional benefit and just wastes Mana.
**The API should prevent Stealth from being cast again if all Dailies are already protected.**
I.e., if the user's value of `stats.buffs.stealth` is high enough and the user tries to cast `stealth` again, the API should prevent the skill from having any effect and should return the string `spellRogueStealthMaxedOut` as an error message.

See https://github.com/HabitRPG/habitica/pull/12255 for the website front-end change that was done recently to adjust the website's Stealth tooltip so that `spellRogueStealthMaxedOut` is shown in the tooltip when Stealth no longer needs to be cast. In particular, the code within the `skillNotes` function that you can see in the diffs for that pull request may be a useful reference when you're working on this issue.

--- 

_(NB: it would be ideal for the skill note that is returned by the API to tell you whether the skill still needed to be cast, but that's more difficult because the API's content route, which contains the skill note that the API returns, does not need authentication, and so it can't easily be adjusted to display customised information for each user. It's not essential for the note to be adjusted, so just preventing the skills being cast when there's no need for them should be enough to close this issue.)_

**Comment by paglias** [comment]
Looks good to me! I'll mark it as `help wanted`

**Comment by JalanshMunshi** [comment]
@Alys I am interested to work on this issue. Would you be so kind as to mark it as an in-progress issue for me? I will comment here in case I need some help.

**Comment by Alys** [comment]
@JalanshMunshi thank you! It's yours.

**Comment by JalanshMunshi** [comment]
@Alys 

I was able to figure out a fix for Chilling Frost. It would look like this - 

![Frost fix](https://user-images.githubusercontent.com/29619543/87857146-107eee80-c942-11ea-97fc-69510083504c.png)

I am sending a `BadRequest` here as this is something that the user did. I may be wrong. Please let me know.

I also need one more confirmation. Does
> I.e., if the user's value of stats.buffs.stealth is high enough

mean we should be comparing the stealth value with the total number of dailies present (due and not due).

That is, if `user.stats.buffs.stealth == user.tasksOrder.dailys.length`, we should return the error message (`BadRequest`) `spellRogueStealthMaxedOut`. Or we should just me considering only the not due dailies?

**Comment by Alys** [comment]
@JalanshMunshi That website error looks good to me! It's possible that Habitica's staff will ask for a different type of error than "BadRequest" to be used, but if so it should be a simple change. BadRequest seems fine to me though.  If you'd like to do a pull request when you're ready to to show us the code, the staff will comment there if they have a suggested change.

For your stealth question, it's a bit more complex than that because som of the user's Dailies may not be due, which means they won't need to be stealthed. Only due Dailies should be considered. Have a look at that PR I linked to as that may help, then ask again if you have more questions!

**Comment by veeeeeee** [comment]
Requesting a wording change for the error message: "You've cast this skill already. It won't have any additional effect." This language can be used for other skills if needed as well. If we discover that additional specificity is needed for user understanding, we can revisit.
