### ISSUE TITLE
Profile page out of alignment when translated versions of Habitica are used

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12381]
From Report a Bug:

> In languages that have longer names for equipment types the profile stats part is no more in neat rows and columns: https://snipboard.io/knP3oq.jpg

![image](https://user-images.githubusercontent.com/8144640/87038618-ead94300-c1e5-11ea-8ab9-e7d1b8e59c6a.png)

**Comment by Alys** [comment]
It also happens in English for head accessories:
![image](https://user-images.githubusercontent.com/1495809/87222175-0e061d00-c3b5-11ea-8578-bb8ea5fe186f.png)

I'm labelling this as needs design for a design decision to be made about how to best fix this. @Tressley 

----

It seems to be a fairly recent problem. The image below comes from an issue comment made on 2 June (https://github.com/HabitRPG/habitica/issues/11075#issuecomment-637490023) and the head accessory item wasn't misaligned then, although an alternative explanation is that this may be system-dependent.
![scr](https://user-images.githubusercontent.com/8144640/83516880-d1025d00-a4cf-11ea-8263-b088516caff7.png)
