### ISSUE TITLE
free experience etc.

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1238]
Hello,

When I leave the game on and my computer sleeps there is a glitch when I wake it back up. Even when I give it time to fully wake the most recent things I have accomplished have been reset in the list though I still have the experience and gold for them. When I go to mark them off on the list they give gold and experience a second time. Also when I choose a reward I loose experience but it does not show a popup with the amount as it would if I were loosing health. I don't know if that is part of the game or not but figured since I was writing anyway I would mention it just in case. Thanks! This is the best thing ever!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
