### ISSUE TITLE
CORS Origin errors when using third-party tools from two or more domains - API headers may need Vary: Origin

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12383]
_I'm labelling this suggestion-discussion for the staff to consider if `Origin` should be added to the `Vary` header (Mozilla docs referenced below)._

---

When a player is using third-party tools from two different domains in the same browser at about the same time, they'll see inappropriate CORS errors.

For example, Ceran (aabe567b-aa55-42c1-b612-b7699a7ba9b7) was using [a third-party tools on oldgods.net](https://oldgods.net/habitica/cTheDragons/challenge.html), then started using [a third-party tool at ieahleen.github.io](https://ieahleen.github.io/habitican-randomizer/) and saw this console message there:

"Access to fetch at 'https://habitica.com/api/v3/content?language=en' from origin 'https://ieahleen.github.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://oldgods.net' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
script.js:348 GET https://habitica.com/api/v3/content?language=en net::ERR_FAILED"

The same thing happened to me (d904bd62-da08-416b-a816-ba797c9ee265) but in reverse. I used the ieahleen.github.io tool successfully, then went to an oldgods.net tool and saw the CORS policy message saying that access from origin oldgods.net had been blocked because the header value was ieahleen.github.io.

The CORS errors tend to stop happening after one or a few reloads, and they don't always happen, but I've been able to reproduce it more than once. It seems to be because the browser is caching the the origin domain from site and using the cached domain on a different site, when both sites are sending requests to the same destination.

It seems to be a known problem for APIs other than Habitica. For example: https://community.esri.com/thread/238787-how-to-prevent-browser-from-caching-cors-domain (_"... Clearly some caching is happening in the browser, where it's sending the wrong (previous) domain out in the request so the external [destination] server is (correctly) rejecting it..."_). Unfortunately that's just a report of the problem without a solution. :)

---

I _think_ the problem may be fixed by adding `Origin` to the API's Vary header. I believe that may be what's being referred to in the text below, which is from https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin :
**"To allow any site to make CORS requests without using the * wildcard (for example, to enable credentials), your server must read the value of the request's Origin header and use that value to set Access-Control-Allow-Origin, and must also set a Vary: Origin header to indicate that some headers are being set dynamically depending on the origin."**

Habitica does set a non-wildcard origin sometimes as seen in https://github.com/HabitRPG/habitica/blob/develop/website/server/middlewares/cors.js and it sounds like the `Vary` header may help when the browser needs to send requests from third-party tools at two different origins.

I'm still pretty new to CORS headers so I'm not sure this will fix the problem, but regardless of that the Mozilla docs do seem to be saying that `Vary: Origin` is important in general. The examples at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS have `Vary: Accept-Encoding, Origin` in them, and I think the API is currently sending only `Vary: Accept-Encoding` from what I can see in the headers reported when I use third-party tools.

**Comment by paglias** [comment]
Definitely something to fix, but might be worth using a proper module like https://github.com/expressjs/cors

**Comment by Alys** [comment]
It just happened to me again and this time I was paying close attention so this was the situation:

1. At roughly 2020-07-13 14:20 UTC+10 I used a third-party tool at ieahleen.github.io (the [Habitica Randomizer](https://ieahleen.github.io/habitican-randomizer/)).
2. About an hour later (2020-07-13 15:18) I used a third-party tool at oldgods.net (the [Inbox Display & Export Tool](https://oldgods.net/habitica/cTheDragons/inbox.html)).
3. It failed to load my data and this message appeared in the console for the oldgods.net page: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://habitica.com/api/v3/content?language=en. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'https://ieahleen.github.io').`
4. I clicked the inbox tool's "fetch" button again pretty much straight away and this time it succeeded. A reload wasn't necessary. 

@paglias is it okay if I mark this as help wanted? 

If so, do you definitely want the fix to involve installing and configuring the module you linked to? Or do you want to leave it open for the contributor to decide how to fix it?

**Comment by paglias** [comment]
I haven't had time to look into the best solution yet

**Comment by Alys** [comment]
Oh sure, I'm sorry! I didn't mean to rush you.

**Comment by paglias** [comment]
I'd say to try to adapt our current code with a few extra things:

- Make sure the existing `Vary: Accept-Encoding ` is not removed but `Origin ` is appended to it
- Since we're here could we change the `cors` middleware from applying to all routes to just those under `/api/v3`? The middleware is currently applied here https://github.com/HabitRPG/habitica/blob/develop/website/server/middlewares/index.js#L63 and should be changed to only apply to the routes here https://github.com/HabitRPG/habitica/blob/develop/website/server/middlewares/appRoutes.js#L29

**Comment by Alys** [comment]
Today my only uses of Habitica have been through the habitica.com website and a third party tool at oldgods.net, however that tool has been failing with the message below in the console - note `0.0.0.0` is the "domain" that the API was expecting, which is odd (and I've certainly not been attempting to use that [meta-address](https://en.wikipedia.org/wiki/0.0.0.0)). I expect this would also be fixed by adding the Vary header but I'm reporting it just to document it and in case it turns out to be relevant. No reply is necessary unless you have questions or comments you want to make. :)

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://habitica.com/api/v3/content?language=en. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'http://0.0.0.0:8080').

**Comment by veeeeeee** [comment]
Ok with @paglias suggested pathway above. Removing suggestion-discussion label.

**Comment by thewilloftheshadow** [comment]
I'd like to take a stab at this one, if its still a problem

**Comment by Alys** [comment]
@thewilloftheshadow It's definitely still a problem! Thanks so much for taking it on. Post here if you have questions or find any problems.

**Comment by thewilloftheshadow** [comment]
Cool! Should I just host a copy of both the extensions and Habitica on my domain with the API routes changed, or is there an easier way to test that

**Comment by paglias** [comment]
@thewilloftheshadow CORS is only used when making requests from a website/browser extension so yeah to test it:

1) use both extensions
2) build two small websites that make request to habitica
3) make curl requests simulating a browser

but I think the suggestions made here https://github.com/HabitRPG/habitica/issues/12383#issuecomment-658196245 should fix the issue so you could try to apply them without testing anything

**Comment by thewilloftheshadow** [comment]
Is there a reason to dynamically set the CORS header? Why not just have it as `*`? I see things on the internet about how to dynamically set it but not why it's better to do that and Vary: Origin instead of wildcarding it

**Comment by paglias** [comment]
@thewilloftheshadow what do you mean by dynamically setting the header? The values here https://github.com/HabitRPG/habitica/blob/develop/website/server/middlewares/cors.js are pretty static

**Comment by thewilloftheshadow** [comment]
What I mean is `'Access-Control-Allow-Origin': req.header('origin') || '*',` versus `'Access-Control-Allow-Origin': '*',`

**Comment by paglias** [comment]
@thewilloftheshadow I don't remember exactly but it's probably because of this https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by shanaqui** [comment]
@thewilloftheshadow Are you still working on this issue? Can you check in within the next week to let us know? If not, or if we don't hear back, I'll mark this as help wanted again so the issue doesn't go totally stale. :)

**Comment by thewilloftheshadow** [comment]
Ahh I totally forgot about this issue! I can pick up work on it again in a couple of days, so yes, I am (:

**Comment by shanaqui** [comment]
No worries! Have at it. :)

**Comment by Alys** [comment]
@paglias I can't reproduce this bug now, and nor can @thewilloftheshadow / @beinginhisshadow according to the conversation in [Testing & Bug Squashing for Dragon Tools](https://habitica.com/groups/guild/d9a0ec1e-352b-4697-a5d5-fb45c98fb4a3). Do you know if something was changed to fix this?

**Comment by paglias** [comment]
I'm pretty sure we didn't change anything, maybe a dependency update? But i haven't seen anything related to this

**Comment by Alys** [comment]
This is still happening just not as often. I do not know why it doesn't happen as often. I saw it once earlier today when going from https://oldgods.net/habitica/habitrpg_user_data_display.html to https://ieahleen.github.io/habitican-randomizer/ but I couldn't make it happen a second time.

**Comment by Alys** [comment]
Another report of it from the

**Comment by Alys** [comment]
There was a report of this today in the [Habitican Randomizer (third party tool)](https://habitica.com/groups/guild/e4956785-9b42-470a-b1af-18d9c5e24769) guild so it's still happening:

> Access to fetch at 'https://habitica.com/api/v3/content?language=en' from origin 'https://ieahleen.github.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://oldgods.net' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by shanaqui** [comment]
Hi @thewilloftheshadow! Are you still working on this issue, or shall I change it to help wanted again to see if anyone wants to pitch in?

If I don't hear back in about a week, I'll do it anyway, but you can always pick it up again later if I do that and nobody else takes it over.

**Comment by thewilloftheshadow** [comment]
@shanaqui I'm still not able to reproduce this, you can open it up again

**Comment by shanaqui** [comment]
@thewilloftheshadow Thanks for letting us know! I've done that now.

**Comment by delightedCrow** [comment]
Having this issue lately too from our demo at [HabiticaMagicJS](https://delightedcrow.github.io/HabiticaMagic/docs/demo/demo.html) with the error message:

> Access to XMLHttpRequest at 'https://habitica.com/api/v3/content?language=en' from origin 'https://delightedcrow.github.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://oldgods.net' that is not equal to the supplied origin.
