### ISSUE TITLE
Which Node.js version for HabitRPG ?

### ISSUE THREAD

**Issue by HLFH** [HabitRPG/habitica#1239]
Which Node.js version for HabitRPG ? Please give me the precise version of Node.js supported by HabitRPG. Maybe HabitRPG could support Nodejs  0.11.3

**Comment by lefnire** [comment]
0.8.x for the main branches (master and develop), 0.10.x for
challenges-and-0.5 (the upgrade). Precise minor versions don't matter

**Comment by HLFH** [comment]
It f*cking works ! With challenges-and-0.5  branch and node v0.10.12. But temporarily. Just the homepage ! When I am at the login/register page, it just stops. 
With mongod, I have this message and an ERR_CONNECTION_RESET with Google Chrome :
Mon Jul  8 01:22:35 [initandlisten] connection accepted from 127.0.0.1:39250 #6 (6 connections now open)
Mon Jul  8 01:22:41 [conn3] end connection 127.0.0.1:39247 (5 connections now open)
Mon Jul  8 01:22:41 [conn4] end connection 127.0.0.1:39248 (5 connections now open)
Mon Jul  8 01:22:41 [conn6] end connection 127.0.0.1:39250 (5 connections now open)
Mon Jul  8 01:22:41 [conn5] end connection 127.0.0.1:39249 (5 connections now open)
Mon Jul  8 01:22:41 [conn1] end connection 127.0.0.1:39245 (5 connections now open)
Mon Jul  8 01:22:41 [conn2] end connection 127.0.0.1:39246 (5 connections now open)

Is it a mongodb error ? 

Maybe a redis error ? I have a warning :
WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
How can I solve it ? Thanks in advance,

I will try tonight.

**Comment by lefnire** [comment]
I haven't seen this before, which branch are  you working from?

**Comment by HLFH** [comment]
challenges-and-0.5 branch

**Comment by lefnire** [comment]
make sure you have redis installed & running. https://github.com/HabitRPG/derby-05-conigs for some example configuration files. I'll document this better once I get 0.5 launched, but for now consult the standard http://derbyjs.com/ docs for what's required

**Comment by HLFH** [comment]
so redis is installed & running. Mongod is running too. There is no more redis warning. I use a little now these configuration files : https://github.com/HabitRPG/derby-05-conigs. I have no more "end connection". But I still can't connect. I have just access to the homepage.

**Comment by lefnire** [comment]
You're not getting any server errors?

**Comment by HLFH** [comment]
No errors. Some news here after a downgrade to Node v0.8.xx and develop branch of HabitRPG : https://github.com/lefnire/habitrpg/issues/791#issuecomment-20919210

So, I now retry Node v0.10.xx and challenges-and-0.5 branch.
