### ISSUE TITLE
party leader should not be able to remove the owner of the party's quest

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12398]
_I'm marking this as suggestion-discussion for a few days for the staff to comment on whether my suggested fix is desired and then if there's no objections I'll mark it as help wanted._

Currently, it is possible for a Party leader to remove the Party member who is the owner of the Party's current Quest. This leaves the Party's `quest` object in an invalid state (see the sample data at the bottom of this post). As a side-effect of this, the former Quest owner is not able to use any third-party tools that read or display party data (because the data is invalid) and they probably see errors in Habitica's official clients too.

Another side effect is that the former Quest owner is no longer able to control the quest (e.g., they can't abort it) and that means they have lost the Quest scroll and cannot gain the Quest rewards. Since the Quest scroll may have cost Gems, this is a significant problem.

I believe the best fix is that the API's [/api/v3/groups/:groupId/removeMember/:memberId](https://habitica.com/apidoc/#api-Group-RemoveGroupMember) route must throw an error if the Party leader tries to remove the Quest owner. This should happen regardless of whether the Quest is in the invitation stage or is active.

The error message could say something like "You cannot remove this member because they are the owner of your Party's current Quest. If you abort the Quest first, you can then remove this member." 

I'll leave this as suggestion-discussion for a few days for the staff to comment on whether this is the desired fix and then if there's no objections I'll mark it as help wanted.

NB It would be possible for the `removeMember` route to be changed so that it automatically aborted the Quest before removing the former Quest owner, but I believe that would be less desirable. The Party leader may actually not want to remove the member once they realise the member is the Quest owner. 

---

As an example of the invalid data, below is a `quest` object after the Quest owner and sole Quest participant was removed from the Party. The Quest is active but there is no `quest.leader` or `quest.key` field.

```
    "quest": {
        "progress": {
            "collect": {},
            "hp": 100
        },
        "active": true,
        "members": {
            "0d0fd796-3271-43f0-b042-10bfd7ed3d97": true
        },
        "extra": {}
    },
```

**Comment by thewilloftheshadow** [comment]
Is there any update on this @Alys? It's still marked as suggestion-discussion but I'd like to take a look at this one

**Comment by Alys** [comment]
@thewilloftheshadow Thanks so much for asking about this! I think based on [this comment](https://github.com/HabitRPG/habitica/issues/12222#issuecomment-660063741) in a related issue, the fix for this one is approved to go ahead so I've marked it as in progress for you.

Post here if you have any questions about it or if you run into problems. Thanks!

**Comment by thewilloftheshadow** [comment]
Awesome! I'm doing the plan to make the `removeMember` route throw an error if you try to remove the quest owner, not change the `removeMember` route so it aborts the quest, as I believe that's what you wanted from your first post.

**Comment by Alys** [comment]
@thewilloftheshadow That's correct, thanks!

**Comment by paglias** [comment]
Reopening because it wasn't really closed
