### ISSUE TITLE
User Defined Shared Tasks

### ISSUE THREAD

**Issue by timothyCoxon** [HabitRPG/habitica#124]
Love the idea of this being a Gamer and also looking for the Ultimate todo list.
One feature I'd really love to see that I've yet to find on the GitHub.

User Defined Shared Tasks.
Basically this comes from crowd sourcing sites like Fiver. Give users the ability to pay other users to do tasks. 
Say I have a load of spare GP this feature would enable me to "Hire" other users to complete a particular task. 
Usage example: 
I have just completed my "Write a blog post task". I could then goto an ingame tavern or equivalent and make a posting for "Wanted 10 comments on X post for 3gp ea". People would then be able to do this task for me and I'd pay them the money. 
I guess it would be best to have it so I pay the money to the program and then when the tasks are complete I release the funds to the users that completed the task. 
For multiple tasks like this, once a user completes the task it's no longer available to that user. 
It would probably be best to have it so I get to pay the 10 best task completions.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
[Shared Rewards/Tasks/Habits](https://trello.com/c/5G7rcMpR)
