### ISSUE TITLE
"habitrpg" group should be deleted from the database

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12408]
If you use the api/v3/groups route to get a list of guilds for a user, then the returned list includes this one:
{"_id":"habitrpg","leader":"9","name":"HabitRPG","type":"guild","memberCount":0,"privacy":"public","description":null}

As stated by paglias at https://github.com/HabitRPG/habitica/issues/7431#issuecomment-339338704, that group should be deleted from the database.

This needs to be done by an admin so I'm marking this as suggestion-discussion until an admin has time to do it. It's low priority.
Technically, I could do it, but I'd rather not since any error in the deletion command would cause ... issues ... :)

sample command to fetch all guilds:
`curl -s -X GET -H "x-api-user: $HRPG_USER_USERID" -H "x-api-key: $HRPG_USER_APITOKEN" https://habitica.com/api/v3/groups"?type=publicGuilds&paginate=false"`

_This issue was created from https://github.com/HabitRPG/habitica/issues/7431_

**Comment by SabreCat** [comment]
done!
