### ISSUE TITLE
banned words (swear words, etc) should be allowed in guilds with a bannedWordsAllowed Group attribute

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12405]
EDIT 2020-08-17 : Stages 1 and 2 have been completed. **Stage 3 is now ready to be done.**

In https://github.com/HabitRPG/habitica/pull/9253, we prevented swear words being posted to most public guilds. Some guilds are exempt (e.g., because religious guilds need to be able to mention terms that otherwise would be considered banned religious oaths).

The guilds that don't have swear word blocking are listed in [website/server/libs/guildsAllowingBannedWords.js](https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/guildsAllowingBannedWords.js) and the code that applies blocking for everything except those guilds is shown below.
We want to stop keeping the list of guilds in a file. Instead, we want moderators and staff to be able to mark a guild as exempt from swear word blocking with a checkbox in the guild's edit modal.

https://github.com/HabitRPG/habitica/blob/fef9c74f9b9ab9b49ae4a8f9380faa7007fb5535/website/server/controllers/api-v3/chat.js#L173-L180

---

This will need to be done in three stages:

### THIS HAS BEEN DONE - Stage 1. Backend support for marking a guild as exempt

* Adjust the [Group schema](https://github.com/HabitRPG/habitica/blob/develop/website/server/models/group.js) to add an attribute called something like `bannedWordsAllowed`
* The attribute must be optional.
* It should be a boolean (if true, banned words can be posted; if false or not specified, then the normal swear word blocking happens).
* I think that should be everything needed for this step. No actual code that uses the new field needs to be added yet.
* The pull request for this should be merged and deployed to production before Stage 2 is done.

###  THIS HAS BEEN DONE - Stage 2. Mark guilds as being exempt.

Admins will do this step (probably Alys).

A simple mongodb update script will be run to set `bannedWordsAllowed` to true for all the guilds currently listed in `guildsAllowingBannedWords.js`. The contributor who works on this issue won't need to write the script.

### Stage 3. Frontend support and adjusting the swear word blocking code

* Adjust the guild creation/edit form to add a checkbox that only moderators and staff can see.
   * Mods and staff can be identified by `"contributor.admin": true` - see the `isAdmin()` function in [website/client/src/components/groups/group.vue](https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/groups/group.vue)
   * NB: mods and staff already have the ability to edit any public guild.
* Adjust the API so that when a guild is [created](https://habitica.com/apidoc/#api-Group-CreateGroup) or [updated](https://habitica.com/apidoc/#api-Group-UpdateGroup):
   * `bannedWordsAllowed` is set to true if the checkbox in the creation/edit form is ticked. That should happen ONLY if an admin is creating/editing the guild.
   * If an admin is creating/editing the guild and the `bannedWordsAllowed` parameter is not specified, then it should be set to false.
   * If a non-admin user is creating/editing the guild, then `bannedWordsAllowed` should not be changed.
* Adjust the [code that prevents banned words from being posted](https://github.com/HabitRPG/habitica/blob/fef9c74f9b9ab9b49ae4a8f9380faa7007fb5535/website/server/controllers/api-v3/chat.js#L173-L180) so that it uses the guild's value of `bannedWordsAllowed` instead of the `guildsAllowingBannedWords.js` file.
* If the guild doesn't have any value for `bannedWordsAllowed`, then behave as if the value is false.
* Delete the file containing the list of hard-coded guilds ([website/server/libs/guildsAllowingBannedWords.js](https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/guildsAllowingBannedWords.js)).

---

This is the new version of this old issue: https://github.com/HabitRPG/habitica/issues/8813 but everything you need should be in this new issue.

**Comment by veeeeeee** [comment]
Good to move ahead as described.

**Comment by Scottd125** [comment]
Hi all,

I'll be happy to pick this issue up. It looks like a good first issue to work on :)

**Comment by Alys** [comment]
@Scottd125 thanks! It's yours. Comment here if you have any questions or run into trouble.

**Comment by Scottd125** [comment]
Hey @Alys 

I've created the PR with the change and the api-v3-integration test suite seems to be failing at a specific test. The full test suite was ran locally on the new branch before creating a PR and they all passed successfully. I ran the failing test locally afterwards on the new branch and they appear to be passing without issues.

I'm not sure if this is a result of a problematic test or that I could be missing something in relation to the change I made. I'm a bit stumped so I'm all ears :D

**Comment by Alys** [comment]
@Scottd125 The tests sometimes fail for reasons unconnected with the code changes (e.g., timeouts). For your PR, the failing test is:

  1) POST /groups/:groupId/leave
       Leaving a group with extraMonths left plan when the group is a public guild
         calculates dateTerminated and sets extraMonths to zero after user leaves the group:
     An unexpected error occurred.

I doubt it's related to your change.
_(It doesn't even seem like a valid test if the description of that test is accurate, since a public guild can't have a group plan in it, but that's definitely not relevant to your PR.)_

I've started the tests running again and we'll see if that fixes it.

**Comment by paglias** [comment]
The tests are passing now

**Comment by paglias** [comment]
PR for point 1 has been merged

**Comment by Alys** [comment]
I've completed Stage 2. Stage 3 is now ready to be worked on. I've updated the top post to indicate that.

Thanks @Scottd125  and @paglias !

@Scottd125 If you'd like to work on Stage 3, post here briefly to say so. Don't feel obliged to though! It's up to you. :) If we don't hear from you either way in a couple of days, I'll mark this as help wanted.

**Comment by Scottd125** [comment]
I'll be happy to tackle Stage 3!

**Comment by Alys** [comment]
@Scottd125 Fantastic, thanks!

**Comment by Scottd125** [comment]
Hey all, just a quick question. 

In the last PR it was requested to add the bannedWordsAllowed field to a noSet property. 

As the third stage features the bannedWordsAllowed field to be set by an admin on the website via a form. Would it be fine to remove it from the noSet property or is it included there for other reasons that I may be missing?

**Comment by paglias** [comment]
@Scottd125 it was added to `noSet` because otherwise the leader of the group would be able to change its value, the idea is that in the updateGroup route there'll be a special check to see if the user making the update is an admin and in that case if `bannedWordsAllowed` is passed in the request body it should be used to update the value of the field

**Comment by Scottd125** [comment]
@paglias Thank you for the clarification, I ended up getting myself a bit confused but that makes a lot more sense now
