### ISSUE TITLE
quests that are level-locked for purchase should be usable at any level

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12417]
Currently, certain quest scrolls can only be bought or used after you have reached a certain level (the list of quests is below).

We want this to be changed so that **if you already own one of those quest scrolls, you can use it to start a quest regardless of what level you are**.

Existing features that should NOT be changed:
- quest scrolls that are given when you reach a certain level should still be given at that level
- quest scrolls that can be bought only after you have reached a certain level should still not be buyable before that level (that will prevent new players from buying a scroll that they are later given for free, which would be annoying)
- quest scrolls that are locked for buying or using before you have completed a previous quest in the same quest line should still be locked for buying and using.

See also https://github.com/HabitRPG/habitica/issues/9936#issuecomment-665149708 where this change was decided.

The affected quests are below, taken from the wiki's [Level](https://habitica.fandom.com/wiki/Level) page ("Unlocks" section):

* Level 15
   * The player receives a free Dish Disaster quest scroll.
   * The player is able to buy or use a SnackLess Monster quest scroll.2
   * The player is able to buy or use a Laundromancer quest scroll.2
* Level 30 	
   * The player receives a free Free Yourself of the Dragon's Influence quest scroll.
   * The player is able to buy or use a Find the Lair of the Wyrm quest scroll.2
   * The player is able to buy or use a Vice Awakens quest scroll.2
* Level 40 	
   * The player receives a free A Stern Talking-To quest scroll.
   * The player is able to buy or use a Gold Knight quest scroll.2
   * The player is able to buy or use a The Iron Knight quest scroll.2
* Level 60 	
   * The player receives a free The Moonstone Chain quest scroll.
   * The player is able to buy or use a Recidivate the Necromancer quest scroll.2
   * The player is able to buy or use a Recidivate Transformed quest scroll.2

**Comment by Alys** [comment]
The affected quests are below, taken from the wiki's [Level](https://habitica.fandom.com/wiki/Level) page ("Unlocks" section):

* Level 15
   * The player receives a free Dish Disaster quest scroll.
   * The player is able to buy or use a SnackLess Monster quest scroll.2
   * The player is able to buy or use a Laundromancer quest scroll.2
* Level 30 	
   * The player receives a free Free Yourself of the Dragon's Influence quest scroll.
   * The player is able to buy or use a Find the Lair of the Wyrm quest scroll.2
   * The player is able to buy or use a Vice Awakens quest scroll.2
* Level 40 	
   * The player receives a free A Stern Talking-To quest scroll.
   * The player is able to buy or use a Gold Knight quest scroll.2
   * The player is able to buy or use a The Iron Knight quest scroll.2
* Level 60 	
   * The player receives a free The Moonstone Chain quest scroll.
   * The player is able to buy or use a Recidivate the Necromancer quest scroll.2
   * The player is able to buy or use a Recidivate Transformed quest scroll.2 



See also https://github.com/HabitRPG/habitica/issues/9936#issuecomment-665149708 where this change was decided.

**Comment by Alys** [comment]
I've labelled this as notify helpers to remind us to tell the Socialites and Wiki Wizards about it when it's due to go live.

**Comment by hamboomger** [comment]
I could try to tackle that issue

**Comment by SabreCat** [comment]
Thanks @hamboomger, happy to see you give it a go! Hit us up here or in the Aspiring Blacksmiths guild with any questions that arise.

**Comment by shanaqui** [comment]
Hi @hamboomger, just checking in how you're doing on this! Still want to work on it? If not, or if we don't hear from you in a week, we'll mark it as help wanted again just to make sure it doesn't go stale. :)

**Comment by shanaqui** [comment]
@hamboomger I'm marking this as help wanted again, but just let us know if you'd like to pick it up again sometime in the future and nobody else has! :)

**Comment by hamboomger** [comment]
@SabreCat @shanaqui Sorry for such a long delay, I actually made a change back in August and tested it locally, but I had a lot of troubles running the automated tests because of some database-related errors. Then I had to put this aside because of some personal issues, which, at least I hope, got almost fully resolved. Which means I'm ready to take [butt] and kick names :)

**Comment by Alys** [comment]
@hamboomger I've marked this as in progress for you again. Let us know if you run into any trouble!

**Comment by Alys** [comment]
@hamboomger Regarding the tests not working locally: if it's not easy to get them to work, do a pull request anyway. You can view the output of the tests in the PR.
