### ISSUE TITLE
error not shown even after invalid email 

### ISSUE THREAD

**Issue by navnit0707** [HabitRPG/habitica#12419]
To Create problem:
visit this https://habitica.com/static/home
fill the form and in mail section write @g and move to password column you will se there is no error will apear and then fill all the option .
![Screenshot (429)](https://user-images.githubusercontent.com/40719341/88956579-3057d000-d2bb-11ea-9a64-0510aa42cba1.png)

As this should so error but not showing .
now change email to @g.g you will find a error appears .
so I want to fix that and make changes so that for @g also show error like this one 
![Screenshot (428)](https://user-images.githubusercontent.com/40719341/88956726-65fcb900-d2bb-11ea-8743-03ce8dede449.png)

 
LET ME KNOW IF THIS WILL HELP YOUR PROJECT I WANT TO CONTRIBUTE

**Comment by SabreCat** [comment]
Ah, looks like an issue with the regex used to validate the field. You're definitely welcome to submit a fix PR!

**Comment by navnit0707** [comment]
ok i will fix it

**Comment by paglias** [comment]
Hi @navnit0707 I'm sorry but we have a refactor of the auth components underway at #12141 that will also fix this issue

**Comment by navnit0707** [comment]
yeah, i checked the auth component respo  and this will help to fix this issue . Thanx for updates atleast i understood how all these works

**Comment by SabreCat** [comment]
Looks like this was closed before the fix to it was merged..?

**Comment by Helcostr** [comment]
I can tackle this regex.

**Comment by shanaqui** [comment]
Hi @Helcostr! How're things going with this? If you're not working on it anymore, I'll mark this as help wanted again so someone else can pick it up. :) If we don't hear back from you within a week, I'll do that anyway, just so the issue doesn't go stale.

**Comment by Helcostr** [comment]
You can mark as help wanted @shanaqui

**Comment by shanaqui** [comment]
@Helcostr Thanks, I've done that now!

**Comment by jasonmishi** [comment]
Hi, it is not the regex, this issue is that the validation is only run after 3 character have been entered in the email field. I can fix it to run as soon as any character is entered like it works for the username and password fields.
This issue is also present in the [https://habitica.com/register](https://habitica.com/register) page.
If it's okay with you I can work on resolving the issue by applying the fix described above in those 2 pages. @shanaqui

**Comment by Tressley** [comment]
Thanks for your interest @JasonCarvalho-tech. I've assigned this issue to you.
