### ISSUE TITLE
Streak counter for dailies is incorrect

### ISSUE THREAD

**Issue by wombatgal** [HabitRPG/habitica#1241]
Yesterday, I successfully completed all my Dailies and marked them as such. All of the Dailies show as having a streak, except for three of them. In addition, progress is not available for many of my Habits which I have marked as complete.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
