### ISSUE TITLE
Change page title based on the site section being viewed

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12421]
Currently the page title is `Habitica - Gamify You Life` no matter the section of the site you're visiting.

We already support dynamically changing the page title using the `title` property in the app store. See
- https://github.com/HabitRPG/habitica/blob/8003632041f0f62634be1f66b34bbd75ac3add1b/website/client/src/app.vue#L470-L472
- https://github.com/HabitRPG/habitica/blob/8003632041f0f62634be1f66b34bbd75ac3add1b/website/client/src/store/index.js#L54

For example,

- we could show the guild name when viewing a guild, same for challenges parties, ...
- we could show the section, for example Inventory, ...

It would help users using multiple Habitica tabs at the same time to distinguish between them and also to remember the Habitica page currently open while viewing a different site.

I'm labelling this as suggestion-discussion until the exact titles have been decided

**Comment by Tressley** [comment]
Suggested page title structure should be: `Section | Habitica`
`Tasks` | `Habitica`
`Items` | `Inventory` | `Habitica`
`Equipment` | `Inventory` | `Habitica`
`Stable` | `Inventory` | `Habitica`
`Market` | `Shops` | `Habitica`
`Quests` | `Shops` | `Habitica`
`Seasonal Shop` | `Shops` | `Habitica`
`Time Travelers` | `Shops` | `Habitica`
`Party Name` | `Party` | `Habitica`
`Guild Name` | `Guilds` | `Habitica`
`Challenge Name` | `Challenges` | `Habitica`
`Team Name` | `Teams` | `Habitica`

**Comment by jbusa22** [comment]
I'm a first-time contributor to this project and would like to take this on. Do you think this would be easy enough?

**Comment by jbusa22** [comment]
Ok I'm working on it now

**Comment by paglias** [comment]
thanks @jbusa22 ! I'm marking this as in progress for you, let me know if you have any question

**Comment by jbusa22** [comment]
I have a few questions about best practices for Habitica:
1. It seems like Vuex mutations aren't used so how would I even set the title state? Is it okay to directly edit the store.state.title?
2. Right now I am emitting to the root from the router on link change. I tried modifying the state directly from router but it doesn't update in the app. Is there a better way to do this?
3. Is it even necessary to edit the vue state? I could just use an emit and listen for it on app.vue and change the title from that listener.

**Comment by paglias** [comment]
Hi @jbusa22 ,

1. We don't use Vuex mutations because they are not compatible with some of our code, we usually change the state directly in store actions

2. Can you show an example of what you tried? I think a good option might be to use an in-component guard for each route component (https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards) that should make it possible to access all the needed info for the title to apply (for example having a before route update guard inside the group component will allow to react to changes in the guild / party being viewed and update the title with the group name)

3. It'd be better to change the state and let the route update the title as it will 1) make it easier to access the title elsewhere in the app 2) make testing easier as we can just test the state changes and not have to setup the app component to access the listener or watch for changes to `document.title`

**Comment by jbusa22** [comment]
Currently, I am editing the state directly from this.$store.state.title on mount for the pages mentioned by Tressely above. Now I will go add in the guard to update the group name on update. How do I create a Team on my local environment? I hit a paywall so not sure how to test it.

**Comment by paglias** [comment]
For group plan right now there isn't an easy way to test it, you can:

1. Edit the database directly and add a fake group plan to a guild
2. Signup for stripe (it's free) and add the test credentials you get from them in config.json (the stripe api key), then you'll be able to use one of the test cards they provide, see https://stripe.com/docs/testing

**Comment by jbusa22** [comment]
I'm thinking for the challenges and guild tabs we just say something like `Guilds | Habitica` and `Challenges | Habitica` until the user selects a specific guild or challenge. Does that make sense?

**Comment by paglias** [comment]
@jbusa22 I would use the name on the Menu, so. it would be `My Guilds`, `Discover Guilds`, `Tavern` or a specific Guild when you're viewing it. Does it make sense?

**Comment by jbusa22** [comment]
Yeah, that makes sense! I think I have everything ready to be tested other than the group plan. I attempted to use stripe and I think it worked but once the payment went through I got an error: Error: No such plan: 'group_monthly'. I can try to edit the db directly but haven't used mongo before. Do you have any tutorials I can read/watch to learn how to access/edit the db?

**Comment by paglias** [comment]
@jbusa22 hmm I think setting up the stripe plans might be too complex, for the database you can use the `mongo` shell (https://docs.mongodb.com/manual/mongo/) or use a GUI like Robo 3T https://robomongo.org/

But if it takes too long, no worries, just push the code and we'll give it a look

**Comment by jbusa22** [comment]
Ok I am able to view the db and the various test guilds and parties I created. Is there an easy way to change the fields of a guild / party to convert it into a group?

**Comment by paglias** [comment]
What are you using?

Il lun 28 set 2020, 18:31 jbusa22 <notifications@github.com> ha scritto:

**Comment by jbusa22** [comment]
The Robo 3T GUI, here's an example of a guild: 

`{
    "_id" : "2c784851-79a9-496d-9ed3-4daa50829748",
    "leaderOnly" : {
        "challenges" : false,
        "getGems" : false
    },
    "quest" : {
        "progress" : {
            "collect" : {}
        },
        "active" : false,
        "members" : {},
        "extra" : {}
    },
    "tasksOrder" : {
        "habits" : [],
        "dailys" : [],
        "todos" : [],
        "rewards" : []
    },
    "purchased" : {
        "plan" : {
            "consecutive" : {
                "count" : 0,
                "offset" : 0,
                "gemCapExtra" : 0,
                "trinkets" : 0
            },
            "quantity" : 1,
            "extraMonths" : 0,
            "gemsBought" : 0,
            "mysteryItems" : []
        }
    },
    "privacy" : "private",
    "chat" : [],
    "memberCount" : 1,
    "challengeCount" : 0,
    "balance" : 0,
    "type" : "guild",
    "name" : "sda",
    "managers" : {},
    "categories" : [],
    "leader" : "4072ccdf-45b9-4046-8d04-f463d707edb7",
    "__v" : 0
}`

**Comment by paglias** [comment]
If you right click on the document you can edit it,

<img width="725" alt="Schermata 2020-09-28 alle 19 40 24" src="https://user-images.githubusercontent.com/589911/94466929-7c8f9580-01c2-11eb-9c08-d0e08b716460.png">

What you want to do is change this part:

```
"purchased" : { "plan" : { "consecutive" : { "count" : 0, "offset" : 0, "gemCapExtra" : 0, "trinkets" : 0 },
```

with something like this:

```
    "purchased" : {
        "plan" : {
            "consecutive" : {
                "count" : 0,
                "offset" : 0,
                "gemCapExtra" : 0,
                "trinkets" : 0
            },
            "quantity" : 3,
            "extraMonths" : 0,
            "gemsBought" : 0,
            "mysteryItems" : [],
            "customerId" : "cus_123456789",
            "dateCreated" : ISODate("2020-09-11T17:49:59.589Z"),
            "dateTerminated" : null,
            "dateUpdated" : ISODate("2020-09-11T17:49:59.589Z"),
            "lastReminderDate" : null,
            "owner" : "YOUR USER ID HERE",
            "paymentMethod" : "Stripe",
            "planId" : "group_monthly",
            "subscriptionId" : "sub_123456789"
        }
    },
```

**Comment by jbusa22** [comment]
Awesome it works! Thanks I'll submit a PR now.
