### ISSUE TITLE
Hard to find indication of sent party invite

### ISSUE THREAD

**Issue by scantics** [HabitRPG/habitica#1243]
Paste someone's character ID into box, click 'Invite,' and the text just stays there or the page refreshes and it merely disappears. 

Correction: the invite sent indication pops up where I wasn't looking. Not a bug, Just a design consideration.

**Comment by lefnire** [comment]
Yeah, subtle light green hard to spot. Will fix later

**Comment by paglias** [comment]
Closing in favour of #1523
