### ISSUE TITLE
Updating avatar does not update your avatar in the "view party" section

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12442]
From Report a Bug: when you update your avatar's appearance, it does not update your avatar in the "View party" modal.

![image](https://user-images.githubusercontent.com/8144640/89651629-238b3b80-d8bc-11ea-92c5-e5cba4a798ad.png)

**Comment by Amberlisi** [comment]
Hi, anybody mind if I pick this one up to look into?

**Comment by Alys** [comment]
@Amberlisi please do, thank you! Post here if you have questions or run into trouble.

**Comment by shanaqui** [comment]
Hi @Amberlisi! Are you still working on this issue? If so just let me know -- if you'd like to drop it, or if you don't reply, I'll mark it as help wanted again in seven days. :)

**Comment by Amberlisi** [comment]
> Hi @Amberlisi! Are you still working on this issue? If so just let me know -- if you'd like to drop it, or if you don't reply, I'll mark it as help wanted again in seven days. :)

Hi @shanaqui, yes I'm still wanting to work on this one!

**Comment by shanaqui** [comment]
@Amberlisi Hey, just checking in again! No rush, just making sure things don't go totally stale. :)

**Comment by Amberlisi** [comment]
> @Amberlisi Hey, just checking in again! No rush, just making sure things don't go totally stale. :)

I'm still working on it! Not going stale 😊

**Comment by Amberlisi** [comment]
@shanaqui Hey, if someone else is able to pick this up and work on it they should. I am dealing with being laid off just recently and need to take some time to figure that situation out.

**Comment by lsophie** [comment]
Hi, is this issue free to being worked on? If so, I'd love to give it a go!

**Comment by shanaqui** [comment]
Thanks! I've added this back to the help wanted pool.

**Comment by Saiyara6133** [comment]
Hi, can I work on this issue?

**Comment by Saiyara6133** [comment]
@shanaqui Hi, is this issue still available to work on?

**Comment by paglias** [comment]
@Saiyara6133 I'm marking it as in progress for you!

**Comment by Saiyara6133** [comment]
I am having difficulty fixing this issue. I am okay if anyone else wants to tackle this issue!

**Comment by Alys** [comment]
@Saiyara6133 Thanks for letting us know! I've set it back to help wanted.

**Comment by Aerek** [comment]
Hi. I'd like to get more familiar with the code base and the Vue framework. This seemed like a good first issue for that. I didn't want to claim it yet, because I was more focused on learning how the code works than actually fixing it. I've found _a_ solution now though and I'd like to add it if it is still wanted.

Any guidance on how to properly make pull requests is welcome. This is my first time contributing to open source.

_~Life is good. Make it better.
Aerek_

**Comment by Alys** [comment]
@Aerek Thanks! I've marked this as in progress for you.

Have a look at [Using Your Local Install to Modify Habitica's Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) on our wiki. There's a lot of useful information in there including a section about submitting a change in a Pull Request.

**Comment by shanaqui** [comment]
Hi @Aerek! Just checking in whether you're still working on this one, or whether we should mark it as help wanted again. If we don't hear back within a week, we'll go ahead and put it back to help wanted, just so the issue doesn't go too stale! Thanks. :)
