### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by rafucuk** [HabitRPG/habitica#12441]
I tried to port forwarding with habitica but there is a problem.

### Description
I ran `npm run client:dev` with port 80 and forward port 80.
Worked perfect but everything is empty, then I realize:

I didn't port forward MongoDB and nodemon server. I forwarded both of them but still not working.

#### Console Errors
![haha123](https://user-images.githubusercontent.com/33981808/89643446-78c84c80-d8be-11ea-81f7-12cd7fc982ee.PNG)

**Comment by rafucuk** [comment]
I censored my IP for security.

**Comment by paglias** [comment]
Looking at the first line of your screenshot it looks like the server is reachable but returning a 500 error, so it looks like the port forwarding is working

**Comment by paglias** [comment]
Closing this issue as it's not directly related to the Habitica code, @RaufSSen if you still need help the [Aspiring Blacksmiths](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) guilds is probably the best place to get help
