### ISSUE TITLE
If you add a tag to a task you are creating, your dashboard gets filtered by that tag

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12447]
Expected behaviour is that adding tags does not affect what tags you're currently filtering by. However, at the moment, when you add a tag to a task during task creation, your dashboard becomes filtered by that tag.

To replicate:

- Start creating any type of new task, from the green + icon (not the quick-add at the top of each column)
- Add a tag 
- Save or cancel task creation
- Observe that your dashboard has become filtered by the tag

Editing a task and adding tags does not cause the same issue.

**Comment by paglias** [comment]
Is this still an issue? I wasn't able to replicate it

**Comment by shanaqui** [comment]
Yep. Still completely reproducible by the steps I gave above, happens every time for me on both delta and production, on all browsers I've tried. Still getting regular reports in RaB as well.

**Comment by shanaqui** [comment]
We figured out what was wrong with the steps to reproduce and I've added an edit above to make it a bit clearer, just in case anyone else needs to come back to this one! Thanks @paglias for figuring that out. :tada:
