### ISSUE TITLE
Losing group members

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#1244]
Removing one member from a group seems to be taking a second with them. Had six fellow members of The Albino Rooks a few days ago. Removed two people, and now I have only two others left.

My User ID: 7fa11a2a-f717-4a3b-bd3b-3798c3326edb

**Comment by lefnire** [comment]
this will be fixed in the upgrade. the issue is the "duplicate operation" bug of derby 0.3 - where any possible action (like removing a user) can send a duplicate of that action to the server

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
