### ISSUE TITLE
Experience is decreasing to negatives and health constantly changing 

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1245]
Every time I tick a daily or to do etc, my experience decreases. The experience bar is currently full but is showing -86. My health is constantly changing e.g. Going from full health to 20, then back up to 34.

**Comment by lefnire** [comment]
can you try this on upgrade.habitrpg.com and see if still the same issue? (note, upgrade isn't using production database, so your changes won't be permanent)

**Comment by ghost** [comment]
Seems to have fixed the issue, though my health has decreased dramatically because of it, and I'm also staying at the inn?

**Comment by lefnire** [comment]
It's from a snapshot of yore, so it may have been before you checked into the inn (and explains the decreased HP).

**Comment by ghost** [comment]
So to continue using habitrpg, do I have to use upgrade.habitrpg.com?

**Comment by lefnire** [comment]
no, don't use that yet - that database is going to be wiped. I'm working on pushing the updates live right now, should be done by today _crossing my fingers_

**Comment by ghost** [comment]
Ah ok, no worries! Thank you for your help :)

**Comment by ghost** [comment]
I'm still getting the same problem, no change at all. It means I can't use habitrpg to track my progress on anything.

**Comment by lefnire** [comment]
Let's just hold off for the rewrite then, we have a basic setup almost ready

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
