### ISSUE TITLE
Login and lastpass

### ISSUE THREAD

**Issue by ExtremeMultiman** [HabitRPG/habitica#1246]
Hi all, I use "Last Pass", and that software bothers me every time I login into HabitRPG telling that login module is unsure.

Can't say exactly why this happens, it doesn't happens with any other website or webapp.

Only thing I notice, it seems to me something strange happen, like multilogin or ajax/javascript refresh of the page on ready(when page full loaded).
I can notice this cause sometimes when I write something it get deleted at end of page load. Or tasks and dailies I write while loading don't get accepted.

**Comment by CoachHuff** [comment]
This related to the memory leak #165 ?
I started a character, played around, and when I tried to log back in, the system claimed it didn't recognize me login, but DID accept my password.  This seems to have been a one time error, however, maybe related to not logging out?

**Comment by wizonesolutions** [comment]
Can you post a screenshot @ExtremeMultiman? You might also want to take it up with LastPass directly first, and then tell us what they say.

**Comment by ExtremeMultiman** [comment]
I don't know if for memory leak, but I don't think so cause it happens asap I open the page. Even if I logout and login.
I'll try asking LastPass what "unsecure login module" means. Here it's the screenshot of the error, not very descriptive, and in italian cause I'm from italy.
![image](https://f.cloud.github.com/assets/840173/820503/578badf2-efc6-11e2-860a-ee70408bd76d.png)

**Comment by lefnire** [comment]
Is there a way to disable last pass for particular websites? I've heard of people experiencing more strange, and dangerous, bugs as a result of using lastpass on Habit

**Comment by ExtremeMultiman** [comment]
For disable you mean some way to block it on your site by you or by their own choice? If it's the first case I doubt it anyway since it's an extension. If you could do it popular websites would have disabled adblock for ages.

That told I'd like to keep using it, I have no  problem except for this popup (that I could disable) and I think the warning is related to the "302 Moved temporarily" response the browser get during access (even with lastpass disabled).

**Comment by lefnire** [comment]
More like how adblock allows you to blacklist / white list domains, was
wondering if there's a setting like that for last pass to exclude
particular websites. Will look into fixing this issue when I can

**Comment by ExtremeMultiman** [comment]
https://forums.lastpass.com/viewtopic.php?f=12&t=91895&p=302465#p302465. This is their reply.

**Comment by lefnire** [comment]
Thanks for the link, useful info provided by the dev there. I responded there for anyone interested

**Comment by paglias** [comment]
@lefnire in the meantime we could add a small notice advising people to manually write the password in case they are using a password manager and it doesn't work?

**Comment by lefnire** [comment]
yeah, maybe a `<small>If you have trouble with password managers, bla bla bla</small>` right under the pw field?

**Comment by paglias** [comment]
added in https://github.com/HabitRPG/habitrpg/commit/c9ff96af6cf086f49adf0f85ab311b2d9715e758

**Comment by paulstaab** [comment]
For me, if I just let firefox fill in the password, the POST request just contains my username. If I manually modify the password, e.g. add a character and delete it again, everything works fine.

**Comment by DanielHeath** [comment]
Lastpass user here.
I'd find it useful if we added a name="username" / name="password" attribute to the login inputs.
This would let me tell lastpass how to find the login inputs.

**Comment by DanielHeath** [comment]
Happy to take this one on myself if the change is considered a good one.

**Comment by lefnire** [comment]
@DanielHeath please do, that would be fantastic! Check out https://github.com/HabitRPG/habitrpg/blob/develop/views/static/front.jade#L24 , let me know if you need any help

**Comment by DanielHeath** [comment]
See https://github.com/HabitRPG/habitrpg/pull/2214

**Comment by lefnire** [comment]
@DanielHeath fixed, shall I close?

**Comment by DanielHeath** [comment]
Close it
