### ISSUE TITLE
Derby 0.5 Upgrade (Aborted)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1247]
I'm gonna track the progress here. There are some major concerns with architectural changes which could possibly mean we need to abort the mission, but if I can get those squared in the next few days we'll be solid. Let's post any issues we experience here, and I'll track the progress in this description (I'll edit it periodically). You can follow my brain-dump every-moment progress [here](https://workflowy.com/shared/4969f16c-c7a1-5667-6948-0416ef5234dc/) if that kinda thing floats your boat :)
## Upgrade Pros
- Duplicate operations fixed
- Memory leak (theoretically) fixed
- Multiple browsers access site at once
- Huge performance improvements
- Continual progress on the framework (master branches)
## Upgrade Cons
1. Missing Mongo projections requiring split of `users` collection into `usersPrivate`, `usersPublic`, `auths` ([details](https://groups.google.com/forum/#!topic/derbyjs/FvyIxuIZc-4))
2. ~~No batch sets, could very likely lead to database write constraints ([details](https://github.com/codeparty/racer/issues/93#issuecomment-18631190))~~ **Edit**: This didn't appear to be an issue after all, the database writes were sane.
3. Required Redis <-> Mongo replication consistency: 
   1. Possibility for corruption (details [here](https://groups.google.com/forum/#!topic/derbyjs/fwz8zdvAShQ) and [here](https://groups.google.com/forum/#!topic/derbyjs/n3cDlmXUcNs))
   2. Required Redis journal of all OT ops, memory overhead ([details](https://groups.google.com/forum/#!topic/derbyjs/C3Nja_UtQx8))
   3. Can't write db migrations (have to build a custom Racer migration tool) ([details](https://groups.google.com/forum/#!topic/derbyjs/C3Nja_UtQx8))
## Upgrade Failure Notes

Edit: We encountered fatal data synchronization errors between Redis & MongoDB [as outlined here](https://groups.google.com/forum/#!topic/derbyjs/n3cDlmXUcNs). Additionally, after a period of server uptime, the Redis journal of operation sequences became so large in memory that the website became completely unusable. ShareJS is looking to fix both these issues in the future, (1) by [gracefully handling sync errors](https://groups.google.com/d/msg/derbyjs/n3cDlmXUcNs/jO9JPyJ9uMMJ), (2) by not requiring all ops exist in the journal. However, we've already spent too much time down this rabbit hole and can't wait while these are added. We're going to be rewriting the website from scratch in Angular https://github.com/lefnire/habitrpg/issues/841

**Comment by palmate** [comment]
was testing the update and my to do list doesn't show up. if i toggle to my completed tasks, i can see those but i can't see any of my remaining tasks. i can also add new tasks to the to do list and they're visible so it's almost as if my old tasks were just erased. checking off a newly completed task also does not send it  to the list of completed tags. it's just remains on the list of remaining tasks with a check on it.

**Comment by lefnire** [comment]
@palmate just todos, none of the other lists? Ok, I'm gonna try a more recent snapshot in ~10m and ping back, let's see if that changes things

**Comment by palmate** [comment]
yeah, just the todos, haven't had issues with the other lists.

**Comment by lefnire** [comment]
can you try now?

**Comment by palmate** [comment]
the same issues with the todos are still there, but i can see my guild now. i was just getting ready to let you know i couldn't see them in my header or on my guild page but they're there now.

**Comment by lefnire** [comment]
what's your UUID per chance?

**Comment by palmate** [comment]
41c6fee0-610c-4f8f-b596-2e33d055b6b9 also just noticed that after refreshing the update, when i click on my avatar it doesn't do anything, i just remain on the task page and now i can't redeem rewards either.

**Comment by palmate** [comment]
noticing i can't delete tasks from any of the lists now, as well.

**Comment by lefnire** [comment]
are you getting any javascript errors? http://community.habitrpg.com/content/submitting-bugs

**Comment by palmate** [comment]
nope

**Comment by palmate** [comment]
refreshed the page again though, and was able to delete things and redeem awards.

**Comment by palmate** [comment]
clicking my avatar also takes me away from the task page again, so it may have just been an issue on my end. sorry about that.

**Comment by lefnire** [comment]
very strange.. testing your account, i can see todos and click things - ah, just saw your other comments. are your todos back then? 

edit: what browser are you using, can you try chrome?

**Comment by palmate** [comment]
yeah i'm on chrome, and when i'm on the regular habitrpg all my todos are there, no problem, it's just on the upgrade.habitrpg that was having the todos issues

**Comment by lefnire** [comment]
Ok, i'll look into this today. Thanks for reporting, @palmate! Could have been a doozie :o

**Comment by palmate** [comment]
no problem! hope it was helpful

**Comment by AndreCaseyScott** [comment]
On quickly assessing upgrade.habitrpg.com, seems waaaay more responsive. Even if I start checking things off before the page fully loads, it keeps track and updates them once it has. Very nice. The Zzzzz for resting in the Inn is a nice touch. Noticed there is a difference in width of User Created rewards and the Item rewards. Dunno if that was intentional, and after checking is the same as develop (super small difference, didn't notice until now)

Tags seem to be working on my account. All in all looks like a great improvement. Though if the API stays broken, that will be problematic with the Mobile App development. And from the topics you linked to, seems the corruption issue with redis is on it's way out. Just make lots of backups :P haha

**Comment by lefnire** [comment]
The API part will be a quick fix, that was more a "note to self" - I just didn't want to dive in too much until I was sure. Yeah, backups galore indeed! Glad things are working well then, thanks for checking it out @onduhray . Ps, we should G+ sometime and meet - you've been helping a lot!

**Comment by lefnire** [comment]
Upgrade aborted. We encountered fatal data synchronization errors between Redis & MongoDB [as outlined here](https://groups.google.com/forum/#!topic/derbyjs/n3cDlmXUcNs). Additionally, after a period of server uptime, the Redis journal of operation sequences became so large in memory that the website became completely unusable. ShareJS is looking to fix both these issues in the future, (1) by [gracefully handling sync errors](https://groups.google.com/d/msg/derbyjs/n3cDlmXUcNs/jO9JPyJ9uMMJ), (2) by not requiring all ops exist in the journal. However, we've already spent too much time down this rabbit hole and can't wait while these are added. We're going to be rewriting the website from scratch in Angular https://github.com/lefnire/habitrpg/issues/841

I'm writing a blog post right now, will put the link here when I'm done

**Comment by lefnire** [comment]
http://habitrpg.tumblr.com/post/55655159428/0-5-upgrade-aborted-angularjs-future

**Comment by ryjm** [comment]
Did you ever get a more detailed response from the Derby devs? I was able to recreate the "Trace: OP already submitted" error and I'm working with a new database. I have the same trace as https://gist.github.com/lefnire/6002531 except that the error is the "op already submitted error". I can't figure out how I recreated it though, and I'm not getting it anymore... so just for curiosity's sake, here are the redis calls when I got the error (happened soon after a server restart):

https://gist.github.com/ryjm/6019889#file-redis

So it looks like on a server restart we are comparing an op log in the redis database to the op log of a character, and getting that the `<seq>` field doesn't match. With a bigger database this would happen for each character, and so maybe the flood of the "op already submitted" errors (which could be a fixable bug) blocked the opData.v values from getting updated properly, causing the "invalid version" error. But I'm not sure if the cause of my error is the same as yours. 

Anyway, good luck with the switch!

**Comment by lefnire** [comment]
@ryjm I didn't respond. Because everything is logged and we have multiple MB/s flowing through, I was getting a large log file & couldn't find a good Grep for some useful output. I started to play with the debug code to just output pertinent snapshot data, but at some point I was just like "screw this." This isn't the final piece of the puzzle, this was just another Derby issue I've hit after ~80h of creating workarounds to 0.5 bugs and enigmatic architectural paradigms. Been spending more time in the last year pinpointing Derby / Racer bugs than coding, and watching the JS world moving on without me while I fight this uphill battle. They have incredibly talented developers, a brilliant product, and a very bright future - give them 6mo and they'll make a big splash - but Derby's just not ready yet, and I should have taken the hint long ago.

Sorry for rant :/ Anyway - that gist you have, could you post that info (probly just copy paste your response here) to the Google Group link? They'll definitely find that information useful, and would help them to know multiple users are experiencing the issue. Thanks for doing some digging, btw @ryjm

**Comment by ryjm** [comment]
Tyler Renelle notifications@github.com writes:

> @ryjm I didn't respond. Because everything is logged and we have
> multiple MB/s flowing through, I was getting a large log file &
> couldn't find a good Grep for some useful output. I started to play
> with the debug code to just output pertinent snapshot data, but at
> some point I was just like "screw this." This isn't the "final piece
> of the puzzle," this was just another Derby issue I've hit after ~80h
> of creating workarounds to 0.5 bugs and enigmatic architectural
> paradigms. Been spending more time in the last year pinpointing Derby
> / Racer bugs than coding, and watching the JS world moving on without
> me while I fight this uphill battle. They have incredibly talented
> developers, a brilliant product, and a very bright future - give them
> 6mo and they'll make a big splash - but Derby's just not ready yet,
> and I should have taken the hint long ago.

My head is still swimming from trying to figure out what the hell was
going on. Don't know how you've been doing it. 

> Sorry for rant :/ Anyway - that gist you have, could you post that
> info (probly just copy paste your response here) to the Google Group
> link? They'll definitely find that information useful, and would help
> them to know multiple users are experiencing the issue. Thanks for
> doing some digging, btw @ryjm

No problem, I'll post it to the list tonight.

**Comment by AndreCaseyScott** [comment]
@lefnire @litenull - Is there a repo on github you are using for the rewrite? Can't guarantee I will have time [or ability] to help much, but willing to see what I can do.

**Comment by AndreCaseyScott** [comment]
@lefnire and yeah! Totally down for a G+ meet. Scheduling might be tough, you're in Ireland, yes? Either way, I'm glad that the little I've contributed has been helpful ^_^

**Comment by litenull** [comment]
@onudhray Yes, https://github.com/lefnire/habitrpg/tree/angular_rewrite

**Comment by lefnire** [comment]
That's the one. I'm in Boston, EST

**Comment by AndreCaseyScott** [comment]
@litenull Nice, I'll check it out :)

@lefnire Haha, don't know where I got Ireland. 3 hours difference seems easier to work with than 8 :P

**Comment by lefnire** [comment]
Cool man, catch me on tylerrenelle gmail sometime
