### ISSUE TITLE
enhance "Get members for a challenge" API route to include tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12481]
Currently, the API route [Get members for a challenge (/api/v3/challenges/:challengeId/members)](https://habitica.com/apidoc/#api-Member-GetMembersForChallenge) returns:
- the participants in a challenge
- their public profile data if `includeAllPublicFields` is set to `true`

In addition to its current behaviour, we it to have a new optional Boolean parameter called something like `includeTasks`
If that parameter is set to true, then each participant's tasks from the challenge should be included in the returned data. 

This will make it much faster for third-party tools to retrieve all the data needed to allow a challenge owner to judge the challenge.

---

I've labelled this "medium level coding" because I _think_ it should be not too hard since you can look at how the `includeAllPublicFields` option was set up, and can look at the task routes for fetching task data, but it may be at the more difficult end of medium. If you take this up and run into trouble, feel free to ask for help!

**Comment by Alys** [comment]
I've labelled this "medium level coding" because I _think_ it should be not too hard since you can look at how the `includeAllPublicFields` option was set up, and can look at the task routes for fetching task data, but it may be at the more difficult end of medium. If you take this up and run into trouble, feel free to ask for help!

**Comment by mbroshi** [comment]
I'd like to give this one a try, although I'm brand new to this project, so I am stretching a bit. It looks simple enough to add a new Boolean field, and then it should just be a matter of figuring out how to run the correct query.

Am I correct that when `includeTasks` is set to `true`, the data sent back should include all tasks for each user for that challenge along with their completion statuses? Or are there some other tasks I should be sending back?

**Comment by Alys** [comment]
@mbroshi Thank you! I've marked it as in progress for you. You're very welcome to keep asking questions here when you need to.

The data sent back will include an object for each challenge participant. Each object should have all of the challenge's tasks for that participant. No other tasks need to be included. 
The completion status will already be in each task's data (along with all other details about the task) so you don't need to search for that specifically.
Post here again if any of that doesn't make sense. :)

**Comment by paglias** [comment]
@mbroshi the idea is that when `includeTasks` it should return the same data as the individual GET member route for a challenge member https://habitica.com/apidoc/#api-Member-GetChallengeMemberProgress, so an array of tasks for each member with the challenge tasks. You can also try to share the code between this route and the individual get member one

**Comment by mbroshi** [comment]
Thanks @paglias and @Alys for the pointers! My general plan is to create a `class MemberFinder` that has a `find` method that returns members based on the constructor options called. If I play my cards correctly, I will be able to call `find` on an appropriate instantiation of `MemberFinder` for GetMembersForChallenge, GetInvitesForGroup, GetMembersForGroup, and GetChallengeMemberProgress API calls. It will then just be a matter of setting an optional boolean parameter on `MemberFinder` to implement this feature.

**Comment by paglias** [comment]
@mbroshi we already have a method that tries to abstract the behavior behind all the members queries here https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/members.js#L279, we should probably expand it to include this new feature but also https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/members.js#L589 which is the same thing but for an individual member instead of multiple ones.

The current abstraction is a bit messy and can definitely be improved although we don't usually make a large use of object oriented programming and classes (instead prefer functional and modular programming) but if you want to create something similar to the webhook factory class used [here](https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/webhook.js#L77) that's fine.

**Comment by paglias** [comment]
Hi @mbroshi , I wanted to check the status of this, this issue being fixed is quite important for some 3rd party tools, could you please let us know if you still want to work on it? thanks

**Comment by mbroshi** [comment]
@paglias apologies but I haven't made sufficient headway on this issue. Please reassign it.

**Comment by hamboomger** [comment]
I love issues with (moderately) simple API changes, I'll give it a go if nobody is working on the issue at the moment.

**Comment by paglias** [comment]
@hamboomger that's great! I've marked this as in progress but let me know if you're having any issue with it

**Comment by hamboomger** [comment]
@paglias could you please explain how to pass authentication on a local habitica instance when making api requests? It seems like I should provide `x-api-user` and `x-api-key` in the request header params, should I get them from my `user` document in db?

Update: Nevermind, I figured it out

**Comment by paglias** [comment]
@hamboomger `x-api-user` and `x-api-key` should be passed as HTTP headers, you can get the values from an user document fields `user._id` and `user.apiToken`. There's an example on how to send them using CURL here https://habitica.fandom.com/wiki/Application_Programming_Interface
