### ISSUE TITLE
Stealth on-hover text confusing when all Dailies are completed / not due

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12487]
Stealth's on-hover text is misleading if you have not cast the Skill today and you don't have any remaining Dailies due. This is the current text:

https://github.com/HabitRPG/habitica/blob/d0bc0dbe498adbe036e01c261d8eed12a68c4dc2/website/common/locales/en/spells.json#L79

Possibly it should be changed to make it more generic so that it applies in either case. E.g., "There is no need for you to cast this Skill because all Dailies are not due or completed or already Stealthed." Or leave out the part from "because" onwards to make it brief. Or something else entirely. :)

_I'm marking this as suggestion-discussion for a decision to be made about what it should say._

---

Below is a two-part bug report from @Gumnos (43e2413a-f440-43c8-b96c-85b93024488c) displaying the confusion the current message can cause (slightly edited for brevity):

_"I'm not sure if this is a bug or not, but my rogue's 'Stealth' skill has been grayed out for several days (maybe more, I don't really use it, so I just happened to notice it a couple days ago and then notice again today that it was still grayed out). The message says that I've already used it, but I haven't used it in...ever? I'm level 68 so it's not a matter of having received/unlocked it yet. And I have more than the required 45 mana. Any ideas what's going on? Thanks!"_

_"Ah, I think I figured out what's going on. I'd completed all my dailies for the day so there's nothing for it to 'hide'. Unchecking one of my dailies to show it as uncompleted re-activates my option to use Stealth. So it makes sense to disable it if there's nothing left to be stealthy from, but the message is misleading, telling me that I've already used it, not that I have nothing left to be stealthy from."_

**Comment by citrusella** [comment]
Maybe something like "There are no more dailies for this skill to affect." ?

Trying to think of something brief that fits all cases... Specifically mentioning Stealth is probably bad because I think this is used for Chilling Frost too?

~~Part of me is thinking of taking this on, but I should wait until it's help wanted. XD~~

**Comment by SabreCat** [comment]
Super generic sentence that might work: "Using this skill at this time would have no effect."

but that might prompt people to wonder "why not?" ... hmm...

**Comment by Gumnos** [comment]
The advantage to being Gumnos both here and on Habitica is that I get tagged into these discussions here. 😉

I like @citrusella's phrasing best so far as it covers both the "you've already used it" case and the "you haven't used it, but if you did, it wouldn't do anything" case. Maybe something like "No uncompleted dailies for you to sneak past."?

**Comment by Alys** [comment]
What about "No remaining uncompleted Dailies for you to sneak past" to cover the case where there are uncompleted Dailies that have been stealthed. Does "remaining" indicate that appropriately?

I like the "sneak past" terminology!

I prefer all of the suggestions here over mine so mine can be withdrawn from consideration. :)

**Comment by citrusella** [comment]
The only thing I wonder is if "sneak past" fits for Chilling Frost as well (like, I genuinely wonder... mage-ing was never my strong suit, so I have no idea XD).

**Comment by Alys** [comment]
Oh heck! I forgot that same string was used for Chilling Frost as well as Stealth! Well done @citrusella !

So yes, we shouldn't use "sneak" or other words reminiscent of "stealth" in the string (although we could split this into different strings for each skill but that's probably more effort than is really needed at the moment). We could go for one of the generic options suggested so far and then change it later if there's still confusion?

---

BTW when a new comment is added to an issue, we get an email, but when a comment is edited, we don't. I think that's why I missed citrusella's first mention of Chilling Frost here - I think it was added as an edit? What I do if I want to add substantive changes to an existing comment is put the new text into a new comment so that an email is sent out, and then (optionally) neaten things up by either deleting the old comment or editing the old comment and deleting the new one. :)

**Comment by Gumnos** [comment]
I agree that "sneak" doesn't apply so well for Chilling Frost.

I originally considered the more generic "No uncompleted dailies for this to {affect,effect}" but would have had to think long and hard about whether it's "affect" or "effect" because I always struggle with this one in certain cases.

**Comment by citrusella** [comment]
It's affect. 😛 ("Effect" as a verb does have uses (i.e. "to effect change") but I'm pretty sure they don't apply here. "Effect" as a verb is more like "to implement" (as opposed to the noun meaning "result"); "affect" as a verb is "to influence or change" in this context. That is, the dailies are influenced to keep their streaks or not damage you, therefore "affect". ... </teacher voice>)

(Also, I did think about putting that extra edit in a second message because I was pretty sure edits still don't trigger emails, but I just... didn't? o.o)

**Comment by veeeeeee** [comment]
Let's try "Using this skill won't have any additional effect" to start. We can always adjust if additional confusion arises.

**Comment by citrusella** [comment]
...I feel the need to point out that in that phrasing, it's "effect". (Curse my teacher brain.)

**Comment by veeeeeee** [comment]
Hah, thanks! Corrected now.

**Comment by mike-the-monk** [comment]
has anyone claimed this? I see discussion about the phrasing to use, but it doesn't look like anyone has this issue officially assigned to them. If I'm correct, whoul I be able to claim it?

**Comment by citrusella** [comment]
I vaguely said I was thinking of taking it on in my first post, but when it actually went to help wanted status I decided I was gonna wait and only take it if no one claimed it for several days.

(Which is to say I want to clarify my earlier mention of taking this on wasn't a "true" claim, in case anyone else did notice I said that and was uncertain/considered that me claiming it earlier. XP)

**Comment by Alys** [comment]
@Mike-Antonacci I've marked this as in progress for you. Thank you! :)
