### ISSUE TITLE
filters on Challenge page for Habits, To-Dos, Rewards don't work (sort of works for Dailies)

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitica#12495]
From @Alys in #10771 

As described in detail below, most of the normal task filters (due, completed, etc), aren't of much use when looking at a Challenge's main page ([e.g., this page](https://habitica.com/challenges/14cf33bb-1e97-4a31-8f3d-49c0f9781d3a)). The fixes described below should be done.

This does NOT apply to the screens you see when you are looking at an individual member's Challenge progress - those screens should keep all the filter options because they help the Challenge owner assess the player's progress.

Below are the problems that exist for filters. The bolded options are my preferred suggestions for fixes. There's been no objections to them since I bolded them, so they're probably the best fixes to do.

- [ ] For Habits, the "Weak" and "Strong" filters don't work (they show all Habits just like the "All" filter does). <strike>They should either be modified so that they show appropriate Habits based on the progress from all Challenge participants or</strike> **the "All", "Weak", and "Strong" filters should be removed**.

- [ ] For To-Dos, the "Scheduled" filter doesn't work (it shows all To-Dos). I think this one is actually useful so **I suggest keeping the "All" and "Scheduled" filters and making the "Scheduled" one show only To-Dos that have a due date.**

- [ ] For To-Dos, <strike>I'm not sure if the "Completed" filter works. If it did work, you'd want it to show To-Dos that ALL Challenge participants had completed. If that's too difficult,</strike> **the "Completed" To-Dos filter should be removed from the page**.

- [ ] For Rewards, the "All", "Custom", and "Wishlist" filters all show the same thing (all custom rewards). Wishlist rewards don't exist for Challenges so **the filters should be removed for Rewards**.

- [ ] For Dailies, the filters are working correctly except that they filter Dailies into due and not due based on the time zone of the person who created the Challenge, not the person looking at it, so it can be misleading. <strike>I'm not sure if we should try to do something about this, or leave it as it is so that at least the Challenge owner can use it, or</strike> **remove the filters for Dailies**.

---

Anyone testing a proposed fix should check that:
- [ ] the fix works on a Challenge's main page (e.g., a page with a URL like this: https://habitica.com/challenges/14cf33bb-1e97-4a31-8f3d-49c0f9781d3a)
- [ ] the fix does NOT change the screen that shows an individual Challenge participant's progress (that screen should still have all the filters)
- [ ] the fix does NOT change the user tasks page (https://habitica.com/)

**Comment by veeeeeee** [comment]
@Alys Please correct the OP if details are missing or incorrect.

**Comment by kirsty-tortoise** [comment]
Can I have a go at this?

**Comment by Alys** [comment]
@kirsty-tortoise That would be great, thank you! I've marked it as in progress for you. Post here if you have questions or run into trouble.
