### ISSUE TITLE
Dailies will only refresh on computer, not on phone

### ISSUE THREAD

**Issue by Clockwater** [HabitRPG/habitica#1249]
Although I've set the timer for my dailies to refresh at 2 am, they don't refresh at all unless I get on the computer.  I work all day and have no access to the website and can only use my phone to use the app, so it's been a real sticking point for me.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
