### ISSUE TITLE
 Using a skill on a task should not allow the task to be completed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12498]
If you use a skill that needs to be cast on a specific task, when you click on the task to apply the skill, if you happen to click directly on the task's main checkbox, then task will be marked as completed.

The expected behaviour is that while you are casting a skill on a task, it should be impossible to mark the task as complete. I.e., the checkbox should not respond to a click in the way it normally does. The only thing that the click should do is apply the skill.

The same applies to the plus and minus buttons on a Habit. When you are casting a skill, if you click on those buttons, the only thing that should happen is that the skill should be cast. A normal Habit click should not be recorded.

**Comment by Alys** [comment]
The same applies to the plus and minus buttons on a Habit. When you are casting a skill, if you click on those buttons, the only thing that should happen is that the skill should be cast. A normal Habit click should not be recorded.

**Comment by paglias** [comment]
ah, there's code to prevent this from happening but it broke with bulk scoring, will handle it
