### ISSUE TITLE
Killed twice

### ISSUE THREAD

**Issue by scootshire** [HabitRPG/habitica#1250]
So not only do my tasks simply not go through a lot of the time, which resulted in me dying last night...this morning I logged in and was killed AGAIN from full health. Lost a sword and my armor. (Just the sword was bad enough. Why isn't it just losing a gear level instead of having to start over?)

Between all these and the fact that the site loads terribly slowly, I'm seriously just about ready to leave. I thought it was a great concept and it worked fine at first despite the occasional heavy load issues, and I spent money on it because it was a good tool and I wanted to support the site, but it's only gotten worse and worse. Really unhappy about this.

**Comment by BlackEdder** [comment]
The main developer is working on an important update that is close to going life. See here:
http://habitrpg.tumblr.com/post/54311977502/habit-update and https://github.com/lefnire/habitrpg/issues/1247

This update should solve (most) of these issues. So I'd suggest to hang in there for a bit longer :)

**Comment by scootshire** [comment]
Thanks, but that doesn't change the fact that a lot of the stuff I worked for was just completely wiped out. Makes me wonder if the frustration is even worth it. :/

**Comment by lefnire** [comment]
You can restore your stats and items via Options > Settings > Restore. The
bugs themselves should be fixed in the upcoming upgrade

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
