### ISSUE TITLE
Guild Membership Duplication

### ISSUE THREAD

**Issue by MayonnaiseJane** [HabitRPG/habitica#1251]
I'm running the IT Helpdesk Minions Guild...

I've got a member who appears on my roster about 30 times, and another one on there 3 times. As much as I love the fact that this gives me a bump up the list, and more visibility... it's a bug.

If while you're in there you're able to take "Helpdesk" out of the name to make us just the "IT Minions Guild" I'd appreciate it but it's not necessary.

<3

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
