### ISSUE TITLE
avatar modal partially hidden under top nav bar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12524]
asl / @x4ojM (2ab6ff6e-0e5b-4c58-b38f-842afc63c0e5) reported:

"When I try to edit my avatar the pop-up window that appears is partially hidden underneath the top nav-bar of the website. This started happening a few days ago. I thought this was maybe a problem with Chrome because I hadn't updated it lately, but I updated it just now and the problem is still occurring. When I open the "edit avatar" tool it looks like the following:"

![scr](https://i.imgur.com/7lRgeI7.jpg)

I can't reproduce this in Firefox on Ubuntu but I did notice the same thing happening with the backgrounds a couple of days ago, although it went away after a reload so I didn't report it, thinking it was a temporary glitch. For asl though it's clearly not something that goes away.

**Comment by paglias** [comment]
I can replicate it if I'm resting in the inn and the banner hides the top of the modal but not otherwise

**Comment by paglias** [comment]
I thought it could be the window's height but it's not, even if I shrink it I can't replicate

**Comment by ghost** [comment]
@paglias well done so far. Has the issue now been fixed?

**Comment by paglias** [comment]
Unfortunately I've not been able to replicate the issue

**Comment by ghost** [comment]
How can i help you?

**Comment by paglias** [comment]
@KarenEfereyan we received a bug report which I'm not able to replicate, if you are and want to make a fix PR, please go ahead and we'll be happy to accept the PR when it's ready

**Comment by ghost** [comment]
@paglias what does it mean to replicate?

**Comment by paglias** [comment]
it means being able to reproduce the issue on your own, in this case I can't reproduce the problem that was reported

**Comment by paglias** [comment]
Turns out the issue was due to bunch of css rules that were not being loaded consistently

**Comment by ghost** [comment]
Oh waow thanks for explaining that. So its important to be able to produce the error by myself
