### ISSUE TITLE
Challenge system bugs

### ISSUE THREAD

**Issue by nafoster** [HabitRPG/habitica#1254]
A few problems with the challenge system running on the latest version of Chrome on Windows. Also, if anybody else wants to put their bugs in this issue, feel free to add yours.
1. When adding a to-do item for a challenge, it does not show up on the subscriber's to-do list,
2. Though filter tags are generated, they do not recognize their associated item. Ex: I create a daily for the challenge, the filter tag is created, but when selected, it does not find the daily. It seems like we would have to manually add this tag to the daily, to-do, habit, etc
3. In a party or a guild, the challenges are does not list current challenges, only the coming soon text.

**Comment by lefnire** [comment]
awesome, i'll be on this right away

**Comment by nafoster** [comment]
I'm also going to add to the list the fact that the challenges area in the sidebar of a party or guild does not list any challenges. It still has the coming soon text. I'm not sure if that was intentional or not.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
