### ISSUE TITLE
Footer layout gets messed up in mobile view

### ISSUE THREAD

**Issue by VipulKhandelwal1999** [HabitRPG/habitica#12549]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: af292e10-b7c0-4a9b-866a-af13868920ba
  * Browser: Google Chrome
  * OS: Windows

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
![Footer Bug Mobile View](https://user-images.githubusercontent.com/44499187/92417664-ef3bc100-f180-11ea-85bc-a2018e4c8866.png)

Footer Layout becomes messy in mobile view and donate button touches upper paragraph. Privacy policy and terms and conditions gets messed up due to their alignment. This issue can be fixed by changing their alignment to center.  
Sir, please assign me this issue i will fix it asap.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by paglias** [comment]
Thanks @VipulKhandelwal1999 , unfortunately right now the Habitica layout is not optimized for mobile use. I'd say go ahead and fix it but let's wait for @Tressley , in case there are different plans

**Comment by Tressley** [comment]
No plans for a mobile footer at the moment. I agree centering the text would help. Let's go ahead and do that.

**Comment by paglias** [comment]
Marked as help wanted, @VipulKhandelwal1999 let me know if you want to tackle this!

**Comment by VipulKhandelwal1999** [comment]
I will work on this issue. Thanks for your response @paglias

**Comment by Alys** [comment]
@VipulKhandelwal1999  Thanks! I've marked it as in progress for you.

**Comment by shanaqui** [comment]
Hi @VipulKhandelwal1999, are you still working on this? No rush, we just try not to let issues go stale! If I don't hear back from you, or if you're not interested in working on this anymore, I'll mark it as help wanted again in a week's time. 👍

**Comment by VipulKhandelwal1999** [comment]
@shanaqui i have fixed footer but i will send you PR after my another PR gets reviewed. I have send another PR already which was for skill layout. As soon as your review on Skill layout gets completed,i will send you PR.

**Comment by VipulKhandelwal1999** [comment]
@shanaqui if you want the output image after fixing footer i can send it to you.

**Comment by shanaqui** [comment]
@VipulKhandelwal1999 No, I don't do reviewing of PRs anyway. But you don't need to wait -- you can start getting this one sorted out right away as well. No limit! :)

**Comment by Gav80794** [comment]
Hi! I'd like to contribute.

**Comment by VipulKhandelwal1999** [comment]
> @VipulKhandelwal1999 No, I don't do reviewing of PRs anyway. But you don't need to wait -- you can start getting this one sorted out right away as well. No limit! :)

Ok i will send you PR right away.

**Comment by shanaqui** [comment]
@Gav80794 Someone else is already working on this issue. :) You're welcome to browse the "help wanted" tag to see open issues!

**Comment by VipulKhandelwal1999** [comment]
@paglias Take a look at my PR.

**Comment by paglias** [comment]
@VipulKhandelwal1999 the pr is closed

**Comment by VipulKhandelwal1999** [comment]
@paglias I am sorry for that. It waz showing lint error. I will send it again after fixing those errors

**Comment by paglias** [comment]
@VipulKhandelwal1999 no worries, you can keep the PR open and just add more commits to it, btw you can have multiple PRs active at the same time by using different branches

**Comment by VipulKhandelwal1999** [comment]
@paglias  thanks for telling that because i was bit confused how to maintain both. That's why.

**Comment by shanaqui** [comment]
@VipulKhandelwal1999 Hi! Are you still planning to work on this issue? Can you please check in to let us know whether you're still working on this? If not, or if we don't hear from you within about a week, we'll set it back to Help Wanted so someone else can have a go. There's no rush, just checking it hasn't gone stale! :)

**Comment by VipulKhandelwal1999** [comment]
@shanaqui I have already completed this I will send you PR right away.

**Comment by shanaqui** [comment]
If you link the PR here, I will link the two so I can check on what's happening with it, and so it's easy for someone to close this when the fix is merged! :)

**Comment by VipulKhandelwal1999** [comment]
Ok @shanaqui Currently i am fixing the skill layout bug. I have fixed this footer bug but i have already done commits related to the skill section. So if I will send you PR, it will contain those commits as well. So either i will send after the skill bug PR is completed or anything you would suggest..

**Comment by VipulKhandelwal1999** [comment]
@paglias Please help me with that. Because you already know what i am talking about.

**Comment by paglias** [comment]
The best option would be to create a separate git branch for the new pr, apply the commits there and send it, but if that's to complex it's also fine to wait until the other pr is merged

**Comment by VipulKhandelwal1999** [comment]
@paglias As now you have merged PR which was related to skill layout. Now it's showing 
![image](https://user-images.githubusercontent.com/44499187/101278975-ea6cc480-37e4-11eb-8d73-5d360b7ab4d5.png)
Now what should i do work on this one. Should i make another branch and then work on it but it will also contain all the extra commits as you can see in the Screenshot.  Please tell me What should i do?

**Comment by paglias** [comment]
What you should do is:

- `git fetch upstream`
- `git checkout develop`
- `git reset --hard upstream/develop`
- `git push origin develop --force`

Now your develop branch will be up to date with the `develop` branch here

Then:

- `git checkout -b fix-12549 ` to create a new branch up to date with `develop` to work on this one
- make changes 
- commit
- `git push upstream fix-12549`
- create a pr using that branch

**Comment by VipulKhandelwal1999** [comment]
@paglias Thank you very much :)

**Comment by VipulKhandelwal1999** [comment]
Screenshot after fixing

Desktop View:-
![image](https://user-images.githubusercontent.com/44499187/101280176-a3cf9800-37ed-11eb-87bc-ac2f3fe42a23.png)

Mobile View:-
![image](https://user-images.githubusercontent.com/44499187/101280195-c2ce2a00-37ed-11eb-991f-e6269d0f2ab8.png)

**Comment by paglias** [comment]
In the desktop view it looks like there's no padding on the left side, I would suggest to use bootstrap's grid https://getbootstrap.com/docs/4.5/layout/grid/ and adapt it to the mobile view with the responsive classes

**Comment by VipulKhandelwal1999** [comment]
@paglias No it contains padding at the left and right. I have taken Screenshot of that only. 
The following are the full view:-

Desktop view:-
![image](https://user-images.githubusercontent.com/44499187/101285199-edc67700-3809-11eb-9b31-8c9e2f8e6644.png)

Mobile View:-
![image](https://user-images.githubusercontent.com/44499187/101285186-da1b1080-3809-11eb-8cc8-1aafa54f18c4.png)

**Comment by VipulKhandelwal1999** [comment]
@paglias I have replaced all my self-made classes with the bootstrap one. And after fixing the view is below:-

<b>Desktop View</b> 
![image](https://user-images.githubusercontent.com/44499187/101338592-2d8d6d00-38a3-11eb-8368-a6cdcafa268b.png)

<b>Mobile View</b>
![image](https://user-images.githubusercontent.com/44499187/101338706-56156700-38a3-11eb-977f-50795c6be807.png)

**Comment by VipulKhandelwal1999** [comment]
@paglias I think i have fixed this issue. Take a look whenever you are free.

**Comment by VipulKhandelwal1999** [comment]
@paglias Can you please take a look at the PR?
