### ISSUE TITLE
"Monthly - Day of  the Month" Dailies should consider time zone during edits

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12555]
I believe this bug only happens if your time zone is ahead of UTC (UTC+1, UTC+2, etc).

When you edit a Daily to change it to repeat on the same date each month, the player's time zone is not taken into consideration. Since the date due is taken from the Start Date and the Start Date is stored as a date in UTC, that means that the scheduled date is one day behind what it should be.

Note that this bug does not occur when you create a new Daily and set the monthly repeat options during the creation phase (more details about that below).

As a brief summary, I think the code to create a Daily has the correct method for setting `daysOfMonth` but the code to edit a Daily does not. _(I'm marking this as medium difficulty because it may be easily fixable by finding and comparing those two pieces of code. However I have not looked at the code myself recently so don't rely on this if it doesn't seem to help. :smiley:)_

Steps to reproduce the bug by editing an existing Daily:

1. Set your computer to be in a time zone that is ahead of UTC (mine is UTC+10 and that causes the bug to occur).
1. Create a Daily with the default settings (e.g., by using the "Add a Daily" text box at the top of the Dailies column.
1. Edit the Daily:
   * Ensure the Start Date is today (it should be by default)
   * Set the "Repeats" option to "Monthly"
   * Set "Repeat On" to "Day of the Month"
1. Save the Daily.
1. Observe that the Daily is NOT scheduled to be due, even though it should be.
1. View the data from the database, for example, see the data below which has had irrelevant fields removed:
 
```
{
    "_id": "3dedb8f6-03f2-407f-8cd3-08a0d2b46eea",
    "repeat": { "m": true, "t": true, "w": true, "th": true, "f": true, "s": true, "su": true },
    "frequency": "monthly",
    "everyX": 1,
    "nextDue": [
        "2020-10-08T14:00:00.000Z",
        "2020-11-08T14:00:00.000Z",
        ...
    ],
    "type": "daily",
    "text": "Wed 10am two-step",
    "startDate": "2020-09-08T14:00:00.000Z",  # This UTC date equates to 2020-09-09 in my time zone (UTC+10)
    "daysOfMonth": [
        8   # this is taken from the startDate and should be 9 for my time zone
    ],
    "weeksOfMonth": [],
    "createdAt": "2020-09-09T00:07:21.821Z",
    "updatedAt": "2020-09-09T00:07:59.176Z",
    "userId": "d904bd62-da08-416b-a816-ba797c9ee265",
    "isDue": false,
}
```
 

Steps to observe **correct** behaviour by creating a Daily with the monthly repeat option in a single step:

1. Set your computer to be in a time zone that is ahead of UTC (e.g., UTC+10).
1. Create a Daily by clicking the green diamond "+" button at the top right of the tasks area (just below the party member banner). Do NOT save the Daily immediately!
1. While still in the creation form, edit the Daily's settings:
   * Ensure the Start Date is today (it should be by default)
   * Set the "Repeats" option to "Monthly"
   * Set "Repeat On" to "Day of the Month"
1. Save the Daily.
1. Observe that the Daily IS correctly scheduled to be due today.
1. View the data from the database, for example, see the data below which has had irrelevant fields removed:
 
```
{
    "_id": "2fc939c6-f9a9-4678-9d8c-de464054d5a8",
    "repeat": { "m": true, "t": true, "w": true, "th": true, "f": true, "s": true, "su": true },
    "frequency": "monthly",
    "everyX": 1,
    "nextDue": [
        "2020-10-08T14:00:00.000Z",
        "2020-11-08T14:00:00.000Z",
        ...
    ],
    "type": "daily",
    "text": "wed 10am one-step",
    "startDate": "2020-09-08T14:00:00.000Z",  # This UTC date equates to 2020-09-09 in my time zone (UTC+10)
    "daysOfMonth": [
        9   # this is correct for my time zone
    ],
    "weeksOfMonth": [],
    "createdAt": "2020-09-09T00:08:28.166Z",
    "updatedAt": "2020-09-09T00:08:28.166Z",
    "userId": "d904bd62-da08-416b-a816-ba797c9ee265",
    "isDue": true,
}
```

**Comment by bakerty** [comment]
Hi, I'd like to work on this issue if that's okay

**Comment by Alys** [comment]
@bakerty Sorry about the delay in our reply! Please go ahead - thank you! Post here if you have questions or find problems,

**Comment by shanaqui** [comment]
Hi @bakerty! Are you still working on this issue? Can you check in within the next week to let us know? If not, or if we don't hear back, I'll mark this as help wanted again so the issue doesn't go totally stale. :)

**Comment by bakerty** [comment]
Hi @shanaqui, I'm still working on this. I got really busy with final exams for a while, but I should be able to contunue working on this now.
