### ISSUE TITLE
Editing config.json port gives error

### ISSUE THREAD

**Issue by rneha725** [HabitRPG/habitica#12556]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 9998b732-2688-45f6-a5f5-d31eef39e257
  * Browser: Chrome
  * OS: Mac OS 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
On changing the port in config.json, it gives error as the express server is required to be run on :3000 

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
Proxy error: Could not proxy request /api/v4/tasks/user from localhost:8080 to http://localhost:3000 (ECONNREFUSED).

**Comment by paglias** [comment]
@rneha725 the error you're seeing is because we also have the BASE_URL config var which includes the port and should be changed as well, see https://github.com/HabitRPG/habitica/blob/develop/config.json.example#L10. That is the url used by the client to send requests to the server

**Comment by paglias** [comment]
Let me know if it works @rneha725

**Comment by rneha725** [comment]
I think it will be good to have only one location to set the port. If it is not taken up in the past, I can take up this task.

**Comment by paglias** [comment]
Unfortunately that is not really possible as the PORT is always necessary but sometimes the BASE_URL doesn't include it, for example when running Habitica.com in production modo the BASE_URL doesn't include a port as it's used for redirects and we want to use `https://habitica.com` and not `https://habitica.com:XXX`
