### ISSUE TITLE
Description of each section vanishes when items are added

### ISSUE THREAD

**Issue by raghavchugh21** [HabitRPG/habitica#12583]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
UUID: af292e10-b7c0-4a9b-866a-af13868920ba
Browser: Google Chrome
OS: Windows

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
The components describing different sections vanish when more items are added in that list.
<img width="702" alt="Screenshot 2020-09-12 at 9 57 31 PM" src="https://user-images.githubusercontent.com/65908705/93096758-6530b280-f6c2-11ea-951d-8c3c6e975750.png">
<img width="706" alt="Screenshot 2020-09-12 at 9 58 03 PM" src="https://user-images.githubusercontent.com/65908705/93096724-5e09a480-f6c2-11ea-8531-b23d99105357.png">
#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by raghavchugh21** [comment]
This pattern does not look good, it projects non uniformity among different sections. This issue can be resolved by making the description a static and separate component itself.

**Comment by paglias** [comment]
@raghavchugh21 thanks for the report but this is the expected behavior as far as I know. I'm going to keep it open for a few days in case @Tressley wants to comment

**Comment by Tressley** [comment]
@raghavchugh21 -- This is the expected behavior. The task type descriptions are there to help new users differentiate between the task types. Once the user has added enough tasks of a certain type, the description disappears as we assume the user has a general understanding of the task types.
