### ISSUE TITLE
missing shop image for 2020-09 Marvelous Moth Mystery Item set

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12585]
As @Soown (d6b40670-91bc-46d1-b60d-dd4014ba7c43) reports:

**"When looking in the time travelers shop at the marvelous moth set, the icon for the set is not present and the box is in the incorrect direction."**

This is what I see when I have only two Mystery Sets unowned, the blank one being the new moth set: 
![image](https://user-images.githubusercontent.com/1495809/93175736-738ad700-f773-11ea-8d62-e03d2ba4f8cb.png)

_I'm labelling this as suggestion-discussion for the staff to look at briefly first because the issue may be that an image needs to be uploaded to the server._

**Comment by paglias** [comment]
this has been fixed with the last deployment, right @SabreCat ?
