### ISSUE TITLE
change dropdown menu to hardness line

### ISSUE THREAD

**Issue by zippomode** [HabitRPG/habitica#12587]

**Comment by zippomode** [comment]
current one
![image](https://user-images.githubusercontent.com/9381877/93190938-a2418700-f74c-11ea-864b-cd7fef3a7c38.png)
click - select - click
possible one
![image](https://user-images.githubusercontent.com/9381877/93191016-b71e1a80-f74c-11ea-8597-4eb89bae8f70.png)
zero clicks, just drug to correct hardness
(cant find how this element named)

**Comment by zippomode** [comment]
I think it's easy to do and a little better UX

**Comment by paglias** [comment]
Thanks for the report @zippomode but this component was redesigned just recently and I don't think we want to change how it works right now, I'm also not sure dragging is better from an UX perspective. Anyway let's hear from our designer @Tressley

**Comment by zippomode** [comment]
> better from an UX perspective

for understand this just repeat something 10-20 times
fewer clicks - less time waste - more time to donate

but let's hear designer, yes
also, ty for this service you both. it's great.

**Comment by Tressley** [comment]
@zippomode -- Thank you for the feedback, but as @paglias said, this control was recently updated and we don't have plans of changing it.

As for improved UX, you should take into account user learning. Dropdowns a fundamental web component and are used throughout Habitica's UI. They don't require a user to familiarize themselves with a new control.
