### ISSUE TITLE
Unable to purchase rewards with hit point penalty

### ISSUE THREAD

**Issue by bernerbits** [HabitRPG/habitica#1259]
Previously, when purchasing a reward that I could not afford (excluding equipment/potions), it would charge me the difference in hit points, potentially killing me in the process. As of a few days ago, I cannot purchase anything at all if I cannot afford it.

I'm not sure if this is a bug or a feature, but it is problematic for my workflow, as I've often taken a reward that I couldn't afford and had to pay for it in HP. Without this, there is no accountability for taking excess rewards.

This is happening to me on Mac OSX Chrome on both beta and the main site.

**Comment by SabreCat** [comment]
I'm also seeing this, on Windows Firefox.

No JS errors thrown that I can tell, though I might not be using the console correctly, eheh.

Notably, the Undo button appears as if you had purchased something...

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by SabreCat** [comment]
This is sort of still an issue--there's simply no popup at all if you click a Reward you're short on gold for. See #1403 .

**Comment by lefnire** [comment]
Ah! We took that out. You just can't purchase rewards with HP anymore. 

Actually, the reason was a technical difficulty when we were implementing mobile. I can't remember what the deal was, but Yan & I had some mismatch with the API vs how the Derby site handled this, and we tried to replicate this "purchase with HP" bit on API and tossed in the towel after a few hours. Figured - "eh, who's using that anyway".

If it's really something we want to bring back, we can put it on the docket again. Things may be different now we're not on Derby anymore

**Comment by SabreCat** [comment]
I like the idea, myself. I've used it only a couple of times, but I'd be sorry to see it go!

**Comment by Shaners** [comment]
Maybe this is a good thing for a community vote? Though I'm not sure what type of sicky Alex is for accepting blood as a currency...

**Comment by lefnire** [comment]
Do it Shane! [Do it do it!](https://www.evernote.com/shard/s17/sh/3fb63aa4-2ae5-41c9-b233-61add117b89e/d4ed5425e8b783a4ee138664ad23f2f9)

**Comment by Shaners** [comment]
Vote now! http://community.habitrpg.com/content/should-players-be-able-pay-rewards-hp-when-they-are-low-gold
Polls close in 2 weeks.

**Comment by wc8** [comment]
this just came up again in tavern:

> handlinger Whatever happened to the overdraft injury when trying to buy rewards you cannot afford? That system actually helped me a lot discipline-wise.

**Comment by wc8** [comment]
I believe the sample items tell users they’ll have an overdraft injury. 

Quoth Cake:

> But only buy if you have enough gold - you lose HP otherwise.”

So this is an issue from a user standpoint, at least. Either Cake needs to be corrected or the vote (Yes, players should be able to pay rewards hp when they are low gold) needs to be implemented.

**Comment by SabreCat** [comment]
Huh--I [thought I changed that](https://github.com/HabitRPG/habitrpg/blob/develop/locales/en/app.json). Maybe I didn't fix it in the right place?

**Comment by wc8** [comment]
My test character can’t take a hit; he’s notified “Not Enough Gold”.
I created the character recently, maybe yesterday. That’s where I got the sample reward quote.

**Comment by SabreCat** [comment]
Oho! I edited the wrong file! I have the derp again. @Xatres take note, the starting tasks are in [helpers.coffee](https://github.com/HabitRPG/habitrpg-shared/blob/master/script/helpers.coffee), not locales/EN. Thanks for pointing this out @wc8, I'll make a quick fix on habitrpg-shared to at least remove the misleading text. I would like to see the blood-price feature come back, too, but best not to misinform in the meantime.

**Comment by deilann** [comment]
Discussion on this has moved to Trello.

**Comment by SabreCat** [comment]
:(

**Comment by deilann** [comment]
I know. I want it too. :(

**Comment by wc8** [comment]
Should it be moved to Trello?
I see this as a ticket to fix/restore a feature that used to work, which is why I didn't close it before. My 2¢

P.S. plus the poll votes were in favor of restoring hp loss, and a number of posts in Tavern since have asked why it isn't working.

**Comment by deilann** [comment]
I totally thought this was already on Trello.

I'll reopen it and move the tags around.

**Comment by SabreCat** [comment]
Assigning myself, I think I can pull this off.

**Comment by crookedneighbor** [comment]
@SabreCat You still working on this? Or can I close it?

**Comment by SabreCat** [comment]
I'd like to get back to it--in fact I was thinking of tackling it this
weekend if I nab an hour somewhere.

**Comment by Alys** [comment]
Can this be mentioned in a Bailey as it goes live so no one who reads the Baileys dies by surprise? Unless you do something nifty like a confirmation menu to warn the user that they'll lose health if they proceed with the reward.

**Comment by SabreCat** [comment]
It did have a confirmation dialog when we had the feature previously, so
that should be doable!

**Comment by lemoness** [comment]
Definitely need a confirmation dialogue.

**Comment by Alys** [comment]
I'd really like this to not be implemented. The potential for new users to kill themselves accidentally is enormous and we don't need more questions and complaints about accidental death. 

I don't think it's unreasonable to expect users to not buy a reward until they've earned the gold for it or to adjust the reward cost to make it cheaper (although of course that can't be done for in-game rewards, but we already have a lot of complaints that all the gear is purchased too quickly and then there's nothing to spend gold on).

I don't think it's intuitive to have HP being "spent" to buy an item that's listed as having a gold cost.

So, I am closing this. Anyone who disagrees may open it, as long as you give a reason, along with a ten-page risk assessment. ;)

**Comment by crookedneighbor** [comment]
I fully support closing this issue.
