### ISSUE TITLE
opening then closing a modal causes whitespace next to scroll bar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12591]
When you open a modal then close it, the website gives itself extra whitespace on the right-hand side, just to the left of the browser's scroll bar.

Steps to reproduce and work-around to fix temporarily:
1. Visit the Tasks page (I've also noticed in on Inventory > Items but I don't know if it's all pages).
1. Observe that the right-hand side of the page does not have extra whitespace (first screenshot below).
1. Open a modal (e.g., click on your avatar to see your profile modal.
1. Close the modal.
1. **Observe that the right-hand side of the page now has extra whitespace (second screenshot below).** The expected behaviour is that the whitespace should not be there.
1. **Workaround: Reload the site using your browser's fresh button.**
1. Observe that the right-hand side of the page no longer has the extra whitespace.

My browser is Firefox on Ubuntu.

**Correct:**
![image](https://user-images.githubusercontent.com/1495809/93693334-d13b6c80-fb41-11ea-86d0-6a872dceebe7.png)

**Wrong:**
![image](https://user-images.githubusercontent.com/1495809/93693342-e3b5a600-fb41-11ea-8cb5-488225351824.png)

This issue was reported by @PixelStormArt (100fadc6-0b54-4329-8dc3-d96b5e482399) who indicates that it's recent, and that resizing the browser window doesn't help:

_"For the past couple of days, I've noticed a boundary issue on the website. The site seems to think my browser window is smaller than it is, resulting in a gap between the edge of the content and the scroll bar. This issue is occurring even when I resize the browser window. Here is a screenshot to clarify is my description is unclear. For reference, I am using Mozilla Firefox to access Habitica."_

It was also reported by @citrusella who points out it may be related to https://github.com/HabitRPG/habitica/issues/9559 and that many/all modals will cause the bug.

_"I noticed the same thing... last night sometime after checking off my dailies... in my case I don't know if it was [this bug somehow recurring in some way](https://github.com/HabitRPG/habitica/issues/9559) (i.e. if it's just exactly "that issue occurs with the level-up modal now for some reason) or some sort of fluke (or related to the speed the modal closed, since sometimes I click outside the level-up modal when checking off tasks in such a way that it disappears about as soon as it shows up). Or if it's unrelated to that and something else caused it..._

_"Update on my prior post: Every modal I could think of to test quickly (profiles, Bailey, report, gem buy, item buy, equipment, task edit, guild members) is causing the whitespace issue, so I'm gonna go out on a limb here and say every modal does it. It's less catastrophe-level than the issue I linked in my previous message because it only causes one scrollbar width whitespace that doesn't expand with further modals, so it's more "kind of annoying" than "can make the site unusable"."_

**Comment by paglias** [comment]
I can't replicate the issue, but looks like it's going to be solved by https://github.com/bootstrap-vue/bootstrap-vue/pull/5771

**Comment by paglias** [comment]
Fixes in #12603
