### ISSUE TITLE
Geo-location for the mobile Applications.

### ISSUE THREAD

**Issue by timothyCoxon** [HabitRPG/habitica#126]
Much like with the Chrome app for Lingering on Vice-Websites. 
If the mobile application could access geo-location you could make particular locations good or bad. 
e.g.
Spend time at the location of the Gym would gain you XP.
Spend time at the pub would loose you HP.
Spend time at work would gain you GP.

**Comment by racuna** [comment]
@timothyCoxon good idea, but if your todo is pick up a girl or be more social visiting a pub can be a gain in xp ;)

**Comment by racuna** [comment]
Another useful option for geolocation could be use weather information to have more points or badge for running in a very cold/warm/rainy day

**Comment by hookang** [comment]
Good Idea. Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
@racuna, @timothyCoxon, etc.: Vote for this idea [here](https://trello.com/c/ByJXycz4)

**Comment by tmas** [comment]
@racuna Linking locations to habits and todos could eliminate the conflict. Todos could have priority, so if you had to go somewhere for a todo it wouldn't count for the habit.
