### ISSUE TITLE
Account got reset

### ISSUE THREAD

**Issue by langejansen** [HabitRPG/habitica#1260]
all habits, coins etc. are gone after logging in with facebook.

user id: a0a74009-b650-44c4-b47c-256e99372578

**Comment by lefnire** [comment]
How long had you been registered? Take a look [at this](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found)

**Comment by langejansen** [comment]
Thanks,

fortunately only a few days(already hooked)

**Comment by lefnire** [comment]
shoot, indeed the account by that uuid appears to be the template user. do you remember the last time things were working well for you? I'll check in the backups

**Comment by langejansen** [comment]
Thanks for the offer, but most things are on my regular todolist. I can
restore it myself.

Most important was that the bug is known so you can make a nice product
good, great or even epic.

Kind regards,

Tim
Op 18 jul. 2013 22:10 schreef "Tyler Renelle" notifications@github.com
het volgende:

**Comment by lefnire** [comment]
Sorry about that :( yeah, thanks for reporting - definitely helps

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
