### ISSUE TITLE
Some guilds using unfilterable "organization" category where "getting organized" may be intended

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#12606]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

This was brought to light when the "organization" string was removed resulting in a missing string error (and subsequently re-added) (see [here](https://github.com/HabitRPG/habitica/issues/9957#issuecomment-695956033), but some guilds (for instance, [Life Hackers](https://habitica.com/groups/guild/694b15e1-19b0-4ea8-ac71-ce9f27031330) have "organization" as a category. This category seems fairly useless for searching/filtering since it's not (longer?) an available filter option, and since Organization is technically a separate category, guilds with that category don't show when "Getting Organized" is the chosen filter, either.

I wonder if it might be likely most or all guilds with "organization" as a category might be better under "Getting Organized" (getting_organized)? Should that be something that should be done in some way? (@paglias suggested I make a new issue for this.)

**Comment by paglias** [comment]
I've also noticed that some guilds have categories with empty names that result as `""` when viewed
