### ISSUE TITLE
Update Gifting Modal Design

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12607]
Need to implement the new Send Gift modals seen here: https://zpl.io/O0RPAqQ

**Comment by WolfTown0907** [comment]
@Tressley 
I am ready to work on this project. Can i have the location of the source file to work on?

**Comment by lynmuldrow** [comment]
@Tressley - New to contributing code here, but if more than one contributor is allowed I'd love to work on this as well.

**Comment by paglias** [comment]
@lynmuldrow unfortunately it's not possible to work in two on the same issue but we'll ping you in case this becomes available again

**Comment by Tressley** [comment]
Sure thing @WolfTown0907! Can you provide an email address to be invited to our Zeplin project? Zeplin is the application we use for hand-off between designers and developers.

**Comment by almondheng** [comment]
@Tressley Hi, it seems that this issue is not in progress. May I pick it up instead? Here's my email address: almondheng@gmail.com

**Comment by Tressley** [comment]
@WolfTown0907 -- Are you still interested in working on this issue? If so, please provide an email address to be invited to our Zeplin project.

@almondheng -- If @WolfTown0907 doesn't reply in a couple of days, I'll let you pick this one up. 👍

**Comment by dreysco** [comment]
@Tressley is this issue still open? If so I'd like to pick it up.

**Comment by yagopessoa** [comment]
Hi guys, is help still wanted for this one? If so, I'd be glad to pick it up. My e-mail is yagorp15@gmail.com if I can get access to the Zeplin design. Thanks :)

**Comment by hazwong** [comment]
Is this issue still open?

**Comment by CuriousMagpie** [comment]
@Tressley Is this modal--accessible from the bottom of the subscription page--also in this issue's scope? Once you type in the username or email address, it opens up the existing modal, which is the one which is reference here. 

![Screen Shot 2022-02-07 at 5 04 18 PM](https://user-images.githubusercontent.com/78037386/152880048-b992da04-0ae0-4809-b54c-f5a1b30c9e19.png)

And should the new modal default to subscription or gems based on what the user selects in the UI? ("Send Gems" versus "Gift a Subscription")

**Comment by Tressley** [comment]
@CuriousMagpie -- Yes, that modal should be included in the scope. The designs linked here are a bit older. I've gone ahead and archived those. Here are the updated versions that include that modal as well: https://zpl.io/O0RPAqQ

> And should the new modal default to subscription or gems based on what the user selects in the UI? ("Send Gems" versus "Gift a Subscription")

Yes, this is preferred and would be awesome. 😎
