### ISSUE TITLE
"Login" button on home page is cut off or hidden at some window sizes

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12611]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Firefox
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

At most window sizes, the "Login" button on the home page adjusts position to remain visible. However, there is a band of widths between 580 and 770 pixels (approximate) where the login button is cut off or completely out of view, without even a scroll bar available to find it.

![image](https://user-images.githubusercontent.com/4501321/94308529-480aa800-ff3c-11ea-9f03-fa1b32741fec.png)

**Comment by hypomania** [comment]
I am ready to work on this issue

**Comment by shamikakumar** [comment]
Hey @SabreCat I'd brought up that I'd like to work on this issue in the report a bug page, do assign this issue to me I'd like to tackle it

**Comment by SabreCat** [comment]
Hi @hypomania, in this case @shamikakumar did let us know their intent to tackle this before the issue was written up, sorry about that! If they relinquish the issue, we'll be sure to hit you up next.

@shamikakumar, you're good to go, with our thanks!
