### ISSUE TITLE
can't scroll to see all Quests in Party > Start a Quest modal on Safari

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12614]
As reported by @quiltsbylaurel (c8dcb8ce-eaae-47be-868e-4539998090f4):

**"When I tried to start a new quest for my party, I wasn't able to scroll down to see the bottom of my scrolls to get to the one I wanted."**

**"I'm using Safari 14.0 on Mac OS version 10.15.6"**

They added that it happens with scrolling by both keyboard arrow keys and mouse/trackpad, and they provided this screenshot:

![image](https://user-images.githubusercontent.com/1495809/94391763-c6b05100-0199-11eb-82a5-bdbd4454e3f5.png)

Here's what it should look like, taken from my Firefox on Ubuntu (note that I have a scroll bar in the left-hand pane that quiltsbylaurel's doesn't have):
![image](https://user-images.githubusercontent.com/1495809/94392073-97e6aa80-019a-11eb-9ab2-5bf509760a84.png)

**Comment by paglias** [comment]
The scroll bar doesn't appear because Safari hides it until you scroll, so it's there but it doesn't work for some reason, I've confirmed the issue. It seems that sometimes resizing the height of the window re-enables the scrolling, if you want to suggest it as a workaround for now. The css is correct so it's probably a Safari bug

**Comment by harumhl** [comment]
Out of curiosity, how do you reproduce this error? I tried it for a minute but I didn't get to this stage yet

**Comment by anishlukk123** [comment]
@saraolson   is this issue still relavant, and if it is can I work on it

**Comment by saraolson** [comment]
Taking a peek at this, the UI to handle this case was changed so, this is no longer an issue. Going to close this up
