### ISSUE TITLE
Streak Bonus Not Added

### ISSUE THREAD

**Issue by storian** [HabitRPG/habitica#1261]
The Streak Bonus box displays, but the streak is not added to the total gold/silver.  Before the last update, in the place of the streak bonus, 1 silver coin would be added.  Now the streak bonus is entirely left out.

**Comment by storian** [comment]
Maybe I'm misunderstood -- is the streak bonus already contained in the first box that appears?  That seems like that might be the case.  In that case, this request is for something a little clearer, like changing the message in the streak bonus box to "Includes [streak bonus]" or something like that.

**Comment by lefnire** [comment]
the streak bonus isn't included in the first box, it's included in the 3rd box (1st=exp, 2nd=gp, 3rd=streak bonus). If your'e not getting silver from the streak bonus, that's a bug. Will address when I have the time

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
