### ISSUE TITLE
Setting up Habitca Locally Windows 10

### ISSUE THREAD

**Issue by IAmAlexPuga** [HabitRPG/habitica#12629]
I get a huge list with the following errors when I try running npm install on windows 10 installation guide:
'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\observable\ErrorObservable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\_esm5\internal\operators\every.js'
.
.
.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\src\internal\operators\zipAll.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\src\operator\zipAll.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\src\operators\zipAll.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\_esm2015\LICENSE.txt'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Alex Puga\Desktop\habitica\website\client\node_modules\.staging\rxjs-0259747e\_esm5\LICENSE.txt'
npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex Puga\AppData\Roaming\npm-cache\_logs\2020-09-29T02_53_18_416Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.160.1 postinstall: `gulp build && cd website/client && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the habitica@4.160.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex Puga\AppData\Roaming\npm-cache\_logs\2020-09-29T02_53_18_504Z-debug.log

Alex Puga@DESKTOP-AL8L1F5 MINGW64 ~/Desktop/habitica (develop)

And the error log files are located here:

https://gist.github.com/IAmAlexPuga/3b08b4cd15fcd3b70c1378ebcf50b98f

Everything ran fine until npm install. Any help will be greatly appreciated! Thanks!

**Comment by paglias** [comment]
Hi @IAmAlexPuga I'm sorry about the troubles you're having but the best place to get support on these issues is the [Aspiring Blacksmiths](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) guild
