### ISSUE TITLE
Social Buttons

### ISSUE THREAD

**Issue by NasiDe** [HabitRPG/habitica#1262]
The social buttons at the bottom of the page (Twitter, etc.) all appear for a bit, but when the page finishes loading, they vanish and leave only github's button.

**Comment by lefnire** [comment]
yeah, page redraw issue. not sure how to solve this bit actually, will
postpone till post-angular migration & see if ti's still there

**Comment by NasiDe** [comment]
Huh, all right. That sounds like a good idea. I hope it works out and best of luck!

**Comment by philadams-zz** [comment]
Nice! When's the move to angular happening?

**Comment by lefnire** [comment]
Writing as we speak. Anywhere between 2-8weeks I should thino

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
