### ISSUE TITLE
Confection Flying Pig misaligned in Stable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12630]
_I've labelled this as suggestion-discussion for the staff to confirm if it is a bug and/or to comment on the fix (e.g., if it's best fixed by the staff)._

As reported by @blue-raindrop (8c51d487-4257-4e7c-9892-0dbceeed33d2):

"hello! I've noticed that the Confection Flying Pig in the Stable is appearing too much towards the bottom of its box for me. If I put it on my avatar, it appears in the same position as the others, but I'm not sure if it's a bug or if it's by design :sweat_smile: Here is a screenshot of how it appears for me. thanks!"

Two Wacky Pets Pigs:
![image](https://user-images.githubusercontent.com/1495809/94628092-76a0ce00-0302-11eb-9e02-710f4b6ea23d.png)

All Confection Pets:
![image](https://user-images.githubusercontent.com/1495809/94628120-891b0780-0302-11eb-945c-6d094c9d3362.png)

**Comment by Alys** [comment]
_I've labelled this as suggestion-discussion for the staff to confirm if it is a bug and/or to comment on the fix (e.g., if it's best fixed by the staff)._

**Comment by veeeeeee** [comment]
This isn't a bug so much as it is a side of effect of how we position sprites--the pets are off-center because of the way they're displayed in the avatar box.

**Comment by thewilloftheshadow** [comment]
It's not that they're not centered, it's that the `Confection Flying Pig` is different from all the rest if I'm reading it correctly @veeeeeee

**Comment by SabreCat** [comment]
Fixed in 7b6f639 for the specific case of the marshmallow fren. There's a bigger issue here with how we position pets within the avatar box vs. the Stable, though, as @veeeeeee mentions--I'll write up a separate ticket for that shortly!
