### ISSUE TITLE
Unnecessary padding in footer in mobile view.

### ISSUE THREAD

**Issue by Deeksha2501** [HabitRPG/habitica#12631]
**General Info**
Browser - Chrome

**Description**
The footer of the website has an unnecessary right and left padding of 6em and also the layout of bottom links is not proper.

![image](https://user-images.githubusercontent.com/47636651/94695567-af1cc800-0353-11eb-9f56-eecea1be70f9.png)

Can I work on this issue?

**Comment by paglias** [comment]
Hi @Deeksha2501 , thanks for the report but this seems to be the same issue (it's a different style but it's the same component) of #12549 that is already being worked on

**Comment by paglias** [comment]
@Deeksha2501 the links were already reported at https://github.com/HabitRPG/habitica/issues/12549 but if you want to fix the padding that's fine! I'll mark the issue as in progress for you

**Comment by Deeksha2501** [comment]
Okay, 
Thank you so much 
I'll work on this issue

**Comment by aandrewww** [comment]
Hey. What's the status of this issue? I'm ready to fix it :)

**Comment by paglias** [comment]
Hi @aandrewww , as you can see from the comment above yours someone is already working on this

**Comment by Vidhu007** [comment]
is the issue still open ?

**Comment by paglias** [comment]
@Vidhu007 the issue is still in progress, if it becomes available again it'll be marked as `help wanted`

**Comment by shanaqui** [comment]
@Deeksha2501 Hi! Are you still working on this issue? If not, or if we don't hear from you within about a week, I'll set this to Help Wanted again. But if you just need more time, that's fine -- just let us know you want to keep on with it!

**Comment by Deeksha2501** [comment]
I will send the PR if the bug is resolved otherwise I will let you know by tomorrow.

**Comment by shanaqui** [comment]
@Deeksha2501 If you can link me the PR we can get it and the issue linked so I can keep checking back. :)

**Comment by shanaqui** [comment]
@Deeksha2501 Hi! Are you still planning to work on this? If not, or if we don't hear back from you within a week, I'll put this back to help wanted so other people get a chance to dig in. :)

**Comment by Deeksha2501** [comment]
Sorry for the late response, I tried but wasn't able to solve the issue
You can assign it to someone else :)

**Comment by lilithi** [comment]
I would like to try fixing this issue

**Comment by Alys** [comment]
@lilithi Thank you! Please go ahead and post here if you have questions.
