### ISSUE TITLE
Issues While Local Run

### ISSUE THREAD

**Issue by VipulKhandelwal1999** [HabitRPG/habitica#12634]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: af292e10-b7c0-4a9b-866a-af13868920ba
  * Browser: Google Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Everything was running perfectly fine before your previously accepted commits. Now i am facing trouble while running the same locally. Please help me with that so that i can start work on some issues.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
![2020-10-01 (3)](https://user-images.githubusercontent.com/44499187/94774461-9821b880-03db-11eb-9a6b-e2c7b6560e80.png)

**Comment by paglias** [comment]
I would suggest to try the following:

1. Make sure you're using the latest node 12.x version
2. Make sure your repo is up to date
3. Try to delete the `node_modules` folders both at the root level and under `website/client` and then run `npm i` again

**Comment by VipulKhandelwal1999** [comment]
> I would suggest to try the following:
> 
> 1. Make sure you're using the latest node 12.x version
> 2. Make sure your repo is up to date
> 3. Try to delete the `node_modules` folders both at the root level and under `website/client` and then run `npm i` again

**Comment by VipulKhandelwal1999** [comment]
> I would suggest to try the following:
> 
> 1. Make sure you're using the latest node 12.x version
> 2. Make sure your repo is up to date
> 3. Try to delete the `node_modules` folders both at the root level and under `website/client` and then run `npm i` again

@paglias Sorry i have closed this by mistake.  I have reopened this.

**Comment by VipulKhandelwal1999** [comment]
@paglias my system has all the required configuration to run. 
My node version is v12.18.3
My npm version is v6.14.8
I have done what you said i.e., Try to delete the node_modules folders both at the root level and under website/client and then run npm i again but again the same error is appearing.

**Comment by paglias** [comment]
sorry about that @VipulKhandelwal1999 but it looks like a dependency is using all the available ram, you might want to report the issue at https://github.com/vuejs/eslint-plugin-vue but it's not really related to Habitica and we've not been able to reproduce it. 

I would ask in the Aspiring Blacksmiths guild for help
