### ISSUE TITLE
Item descriptions do not reliably appear on hover in rewards or market

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12649]
Report from RaB:

> 𝕄𝕚𝕟𝕦𝕚𝕒𝕝𝕨𝕖𝕟   @Minuialwen (928bb0c3-86a3-4ab9-a764-a7ae8ca11589) [web]
> I've just noticed that we no-longer get the pop up window when you mouse over an item in the shop, instead you now have to right click on an item to get the pop-up window describing it, but that isn't any good because the browser responds to a right click.

This seems to be the case for me as well, on a Windows computer, in both Chrome and Firefox.

**Comment by Alys** [comment]
I think this is likely to be the same bug as in https://github.com/HabitRPG/habitica/issues/12638 which has been fixed (and so wasn't appearing in the list of open bugs) but the fix isn't live yet. 

I'm closing this but if it's still happening after the next deployment to production, we can reopen it.
