### ISSUE TITLE
Collection Quest - Users can lose their "excess" collected items in multi-category collection quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12664]
When you cron while participating in a collection quest, it's possible for some of the items you've found to NOT be applied to the quest.
(This is a new version of the old bug where too many items of one type could be found: https://github.com/HabitRPG/habitica/issues/8248)

The example below uses mayhemMistiflying2 which is defined here:
https://github.com/HabitRPG/habitica/blob/efe7ea52bc0e3c27563eb2ebfe9ae5f082be20d4/website/common/script/content/quests.js#L2651-L2685

Before cron, the user has found 10 items as shown in the user's own quest object:
```
{
    "party": {
        "quest": {
            "progress": {
                "up": 0,
                "down": 0,
                "collectedItems": 10, // NOTE 10 PENDING ITEMS COLLECTED
                "collect": {}
            },
            "RSVPNeeded": false,
            "completed": null,
            "key": "mayhemMistiflying2"
        },
        "_id": "997bcc67-4764-4e99-813c-2e9330f58341"
    },
}
```

Before that user crons, the party has already found some items as shown in the party's quest data:
```
{
	"_id" : "997bcc67-4764-4e99-813c-2e9330f58341",
	"quest" : {
		"progress" : {
			"collect" : {
				"mistifly1" : 0,  // maximum is 25
				"mistifly2" : 14, // maximum is 15
				"mistifly3" : 9   // maximum is 10
			}
		},
		"active" : true,
		"key" : "mayhemMistiflying2",
		"leader" : "b917f6f9-4080-46c6-b25f-4febb9775941",
		"members" : {
			"b917f6f9-4080-46c6-b25f-4febb9775941" : true
		},
		"extra" : {
			
		}
	}
}
```

The user's cron then runs and it should apply their 10 found items to the quest (i.e., the total number of collected items of all types should increase by 10).

But here is the party's quest progress data after that user's cron has run:
```
{
    "_id": "997bcc67-4764-4e99-813c-2e9330f58341",
    "quest": {
        "progress": {
            "collect": {
                "mistifly1": 2,  // increased by 2
                "mistifly2": 15, // increased by 1
                "mistifly3": 10  // increased by 1
            }
        },
```

The total increase in found items was 4 instead of 10.

I believe the code responsible is in `function processCollectionQuest` in `website/server/models/group.js` 

First, this part of the code runs to identify all the collection items that haven't been fully found yet (that prevents the user finding more items for types that were already fully found **before** the user's cron ran): 
https://github.com/HabitRPG/habitica/blob/efe7ea52bc0e3c27563eb2ebfe9ae5f082be20d4/website/server/models/group.js#L1145-L1151

Then this code is run to determine which items the user should find:
https://github.com/HabitRPG/habitica/blob/efe7ea52bc0e3c27563eb2ebfe9ae5f082be20d4/website/server/models/group.js#L1153-L1163

It loops through that code the correct number of times (once for each pending item in the user's own quest data), and it tracks which types of items the user finds, so that the quest can't accumulate more than the maximum for each type (that seems to work correctly).
BUT after one particular type has been fully found **during** the player's cron, if the user finds another item of that type, that item is just abandoned - there's no attempt to reuse that item to apply it to a different type.

So in effect, the code DOES allow the user to find more than the maximum number for each type of collection item, it just doesn't record any numbers greater than the maximum.

The expected behaviour is that all of the user's pending found items will be applied to the quest
(unless of course the user has found enough items to end the quest without all of them being applied).

----

_Thanks to @cTheDragons for asking a question about the code that prompted me to find the bug._

**Comment by ghost** [comment]
Hello, I'd like to try working on this issue

**Comment by Alys** [comment]
@CodeBerrie Thank you! Please go ahead. Comment here if you have questions or run into trouble.

**Comment by shanaqui** [comment]
Hi @CodeBerrie! How's it going? Can you please check in to let us know whether you're still working on this? If not, or if we don't hear from you within about a week, we'll set it back to Help Wanted so someone else can have a go. There's no rush, just checking it hasn't gone stale! :)

**Comment by shanaqui** [comment]
I'm putting this issue back in the help wanted, since we didn't hear back! :)

**Comment by wolverdude** [comment]
This bug has bitten me several times by now. I'd like to go ahead and smash it. Please assign it to me.

**Comment by wolverdude** [comment]
This bug took 7 quest items from me just this morning... but I've taken it's very existence! PR #13401 is tested and ready to merge.
