### ISSUE TITLE
Waking up after sleeping in the inn - old dailies remain checked

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#1268]
I checked into the inn in the middle of the day, having already done all my morning dailies. This morning I checked out, and found that those dailies which had been completed at the time I'd checked out were still grey. It did figure out that it was a different weekday: dailies that should be due the day I checked in but not the day I checked out were grey, and dailies that should be due on checkout day, but not checkin day were not. 

Thinking about it, I'm not sure what correct behaviour would be. Habitrpg has no concept of time of day. So it can't tell that I checked out at a logically different time than I checked in. (I say logically, because by the looks of the tasks greyed out, I checked in at a point approx. 2 hours after breakfast, on a weekday - it's now a weekend, approx. the same time by the clock, but 3 hours earlier if the comparison is based on when I got out of bed ;-)) 

But this definitely violated the principle of least astonishment, for me at least.

**Comment by lefnire** [comment]
let's follow up convo here: https://trello.com/c/A2w2orSc/14-rest-in-tavern . This was built as intended, but there's convo saying that intention is not correct - chime in with your opinions there and we'll figure out something to replace the current method
