### ISSUE TITLE
Rewards costing 100+ don't look right

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1269]
Windows 7, Firefox, uid 7f14ed62-5408-4e1b-be83-ada62d504931. No JS errors.

If I create a reward costing a large amount of gold (100 or more), the gold coin icon drops to another line in an awkward fashion:

![rewards_layout](https://f.cloud.github.com/assets/4501321/832058/9880f1ba-f22c-11e2-84a1-a4a4938cf9b7.png)

Some ideas:
- Left-justify the cost+icon in the cell instead of centering.
- Allow the shaded cost cell to grow. The current size can be the default, then if somebody puts in a huge reward, steal space from the reward name to compensate.
- Size the custom rewards the same as the fixed rewards. The screenshot above shows the discrepancy in their widths. That'll allow a little more room overall.
- Super crazy edge cases (BILLIONS OF GOLD!) could do something like replace the displayed number with "10k+" and display the actual amount in a hover bubble.
- Or even better, give rewards a maximum price. 999 or 9999 would fit the classic console RPG feel! Whatever other solutions are applied, you'd only need to handle up to that number of digits plus 2 decimal places.

**Comment by SabreCat** [comment]
You can also run into this issue by putting in several decimal places, in a browser that allows it (#1230). Should cap that at 1-2 decimal places.

**Comment by nafoster** [comment]
Works fine on Chrome, Windows 7 64bit at 1366 x 768 resolution. Might not be a bad idea to left-justify the icon + cost text though.

![habitrewardglitch](https://f.cloud.github.com/assets/3391909/835666/7a1221e0-f2e0-11e2-90fe-9aaed7d146d2.jpg)

What is your screen resolution? Maybe it doesn't scale down well at certain resolutions.

**Comment by SabreCat** [comment]
Hmm!

I just took a look at it on my work computer (also Win7 64), and it's fine there on both Chrome and Firefox. It takes 4 digits to reproduce the issue. The main monitor at both home & work is 1920x1080, so the resolution doesn't appear to affect it. Maybe I have different versions of Firefox active?

A related matter I noticed, though: on Chrome, the input box for reward price is too small to see more than 2 digits.

**Comment by SabreCat** [comment]
Aha! I just figured it out. At home I have the page zoomed in by one tick on Ctrl+mousewheel. And I can reproduce the issue on both Chrome and Firefox now by setting zoom to 110%.

Definitely a low-priority thing in any case, but some handling for overflow (be it via huge numbers or zoom level) would be worthwhile.

**Comment by nafoster** [comment]
@SabreCat That's good we figured out the issue. However the input box size should be changed to fit inputs more than 2 digits. I'll take a look at it.

**Comment by lefnire** [comment]
this was fixed ,yeah?

**Comment by nafoster** [comment]
This fix has been implemented.

**Comment by lefnire** [comment]
seems ok for me on beta.habitrpg.com http://gyazo.com/48599954f870aee74266e8f6f62bbac0 , wanna give beta one more shot? (could have been a missed deploy after previous merge)

**Comment by nafoster** [comment]
Sorry, I didn't refresh the page before I posted the previous comment, but after checking the site, the fix has been implemented.

**Comment by lefnire** [comment]
Fantastic

**Comment by patena** [comment]
Is this supposed to be fixed? I'm still seeing it...

**Comment by SabreCat** [comment]
@patena, see #1993.
