### ISSUE TITLE
Heading level hierarchy is not accurately reflected by heading appearance (e.g., h5 larger than h3)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12704]
_The non-italics words below are taken direct from @citrusella's post in the Report a Bug guild. I've added [my own comments in italics and square brackets]._

---

Have been seeing how used to the new font changes I can get and noticing something that feels weird/confusing/possibly-buggy/unintended.

The h1, h2, h3, h4, h5, h6 hierarchy looks like this:

![image](https://user-images.githubusercontent.com/1495809/97129867-a8834400-178b-11eb-89c6-64753ccbb701.png)

_[Below is the markdown code that produced those headings, with blank lines removed to save space.]_
```
# 1
## 2
### 3
#### 4
##### 5
###### 6
```

Is it deliberate that some in the middle are smaller? h3 feels especially confusing--it's the same size (or very slightly smaller) and weight/color (or again, very slightly different) as regular text and nigh indistinguishable from it, which is throwing me off every time I look at my task list because I have "header tasks" for different sections of my task list and now they just... look like not-due tasks. (I'm not sure "header tasks" is a super common use case, but it is one highlighted on the wiki--I was using h3 because it was small enough to not wrap on the majority of the header tasks I'd made and large enough as to be visually distinguishable from standard text.)

For example, here's h3 vs regular text (there's some spacing difference if the lines wrap but that's about it--the color is a little more distinguishable here than it is on tasks, BTW):

![image](https://user-images.githubusercontent.com/1495809/97130135-4119c400-178c-11eb-844d-b71bd2a47ccf.png)

_[Below is the markdown code that produced those two lines.]_
```
### This is a third-level header, it's quite small, the size of regular text or so.

This is regular text. It is the size of regular text because it IS regular text.
```

I'm on the lookout for other things that look odd with the changes but I think most of the other things I go "weird, don't like that" with are just things I'm not used to yet.

---

_[I'm labelling this as needs design for a design-related decision. @Tressley ]_

**Comment by citrusella** [comment]
I feel a need to note that the third-level text and regular text look closer for me than that screenshot looks (that screenshot looks like the h3 is slightly larger?).

![The h3 and plaintext image in the post above, but with a screenshot from my computer](https://user-images.githubusercontent.com/14182450/97131993-fceedb00-171b-11eb-8b4b-b5758950a0f0.png)

**Comment by citrusella** [comment]
And just to be complete since I mentioned it looking even more indistinguishable on tasks... here's h3 versus normal text on tasks, where the text color is also closer:

![A task with nothing but h3 text in it, followed by the beginning of a task with regular text](https://user-images.githubusercontent.com/14182450/97132268-c2397280-171c-11eb-9a17-42c3349827ee.png)

(If it's not obvious: The first is h3 (###), the second is just text.)

**Comment by paglias** [comment]
Just a note that the headings styles are different between markdown (tasks, chat, ...) and normal non-markdown text. I think so far this issue has been around markdown headings

**Comment by citrusella** [comment]
I think the styling of some non-markdown headings changed too, but none of it has as confusing effects (visually, anyway) as far as I can tell.

**Comment by Tressley** [comment]
There were changes to headings that accidentally touched the task styles. @negue is currently working on fixing them.

I'd like to point out that Habitica's type scale didn't account for h5 and h6 as they're not used in our UI. That would be the reason the type scale seems out of sorts. However, we have been making updates which you can see outlined here:

![image](https://user-images.githubusercontent.com/2686586/97319523-5bfb3f80-1843-11eb-89a7-959d65ebfa9d.png)

**Comment by Alys** [comment]
@Tressley great, thanks! I've marked it as in progress since @negue is working on it
