### ISSUE TITLE
Systemd support / Start at boot

### ISSUE THREAD

**Issue by HLFH** [HabitRPG/habitica#1270]
Hi,

I'm running on a HackBerry with ArchLinux ARM. It would be cool if HabitRPG could start at boot. So HabitRPG need systemd support by one way or another.

Thanks in advance,

**Comment by HLFH** [comment]
So @lefnire when I'm running Systemd-only, Systemd with Forever, or just Crond & Forever with @reboot, I have this issue at startup : 

``` bash
info: socket.io started
Expressions in require() statements:
    require('./lang/' + key)
Expressions in require() statements:
    require('./lang/' + key)
Error: Couldn't load translations: en.app
    at i18n.localize.app.router (/var/www/habitrpg/node_modules/derby-i18n/lib/index.js:150:23)
    at Backend.init (/var/www/habitrpg/node_modules/derby-i18n/lib/backends/filesystem.js:15:13)
    at fs.js:117:20
    at Object.oncomplete (fs.js:297:15)
Message sent: 250 2.0.0 OK 1374827506 z2sm2947363wiv.11 - gsmtp
```

So the error is : **Error: Couldn't load translations: en.app**

But I don't have this issue when I do it manually at startup with a cd /var/www/habitrpg && node server.js

**Comment by HLFH** [comment]
Solved. http://stackoverflow.com/questions/13385029/automatically-start-forever-node-on-system-restart
I quote :

> Also, you may want to specify the 'current working directory' in app.js to ensure relative files are loaded correctly - 
> process.chdir('/your/path/to/your/app'); Node.js ref docs [here](http://nodejs.org/api/process.html#process_process_chdir_directory) –

On crontab -e, I added the WorkingDirectory :   

> @reboot source /root/.nvm/nvm.sh **&& cd /var/www/habitrpg** && /root/.nvm/v0.8.17/bin/forever start /var/www/habitrpg/server.js

**Comment by HLFH** [comment]
#reload current systemd daemons > systemctl --system daemon-reload

``` bash
vim /lib/systemd/system/mongodb.service
[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target

[Service]
User=root
ExecStart=/root/mongodb/bin/mongod --quiet --dbpath /var/lib/mongodb 

[Install]
WantedBy=multi-user.target
:wq!

systemctl enable mongodb

npm install -g forever
crontab -e 
Add :
@reboot source /root/.nvm/nvm.sh && cd /var/www/habitrpg && /root/.nvm/v0.8.17/bin/forever start /var/www/habitrpg/server.js
:wq!
reboot
```

Deploy NodeJS App with Systemd after : http://savanne.be/articles/deploying-node-js-with-systemd/

**Comment by lefnire** [comment]
Thanks for all the information @HLFH , I'm certain someone deploying their own server in the future will find this extremely valuable. Once you feel like you're up and running properly, let's consolidate all your instructions to a wiki page.

Sorry I haven't been much use to myself, to be honest we had a devop pro set us up on AWS originally, and I was in over my head on the chef config / setup. I mean to expose the config files in the future, but they're so tied up to some sensitive info currently that I can't just yet.
