### ISSUE TITLE
[Feature Request] Condensed checklists

### ISSUE THREAD

**Issue by tetrahedon7** [HabitRPG/habitica#12701]
The checklist items in the website used to be closer together but now they have more space in between, and so the to-do's and dailies also take up more vertical space.

How is was before:
![image](https://user-images.githubusercontent.com/69251025/97096725-d4200480-168d-11eb-83e6-1ff3f1a34681.png)

How it is now:
![image](https://user-images.githubusercontent.com/69251025/97096728-db471280-168d-11eb-98ac-af1c9d85230c.png)

There's that tiny extra space between the checklist items now, but for people like me who keep a lot of checklists in their to-do's and dailies, this results in making making those lists considerably longer, and also a bit more cluttered-looking, imo. Please add an option to keep checklists "condensed" or something. Thanks

**Comment by Alys** [comment]
As I mentioned in the Report a Bug guild, the best place for ideas like this option you're suggesting is through Help > Request a Feature. We use the Reports A Bug guild and this GitHub repo primarily for bug reports. :)
