### ISSUE TITLE
Gem count does not decrease properly

### ISSUE THREAD

**Issue by LotusEcho** [HabitRPG/habitica#1271]
I recently purchased 20 gems via donation and went to buy some pet items. I realized after buying a few things that the total number of gems that it was reporting at the inventory wasn't going down. Having gotten used to things not updating until a reload I finished buying my items. When I reloaded, after using two potions I bought, it first reported that I still had 16 gems and after another reload it changed to 20. I then counted what I bought and I should have -1 gems based on my calculations (or at least not have the last cotton candy pink potion and have 3 gems). 

Server: habitrpg.com
User: LotusEcho

So not only is it ignoring how many gems I actually have it's letting me USE them.

**Comment by lefnire** [comment]
verified, marking crit & will fix soon

**Comment by lefnire** [comment]
very strange one. I can't replicate on local, even with `NODE_ENV=production` - but definitely the case on prod. I'll have to revisit

**Comment by LotusEcho** [comment]
It hasn't happened for me on prod since then (now I'm down to zero again). I'm wondering if it has something to do with load perhaps? I wanted to dive into habitrpg so maybe I'll give it a look. I can probably simulate load by writing up some quick load test scripts or something (or by trying to run it on my RasPi).

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
