### ISSUE TITLE
Accessibility: use same focus style across entire website

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12714]
Lately we've been slowly fixing accessibility issues including focus styles for many elements across the website.

By default the focus styles depend on browser settings, for example the default focus style on Edge looks like this:

<img width="703" alt="Schermata 2020-10-26 alle 15 40 56" src="https://user-images.githubusercontent.com/589911/97186935-3702c000-17a2-11eb-9540-e2064d7baeb2.png">

We'd like to standardize this setting across the website like it's been done for some elements to be 1px outline/border of color `purple-400` using a global style:

<img width="482" alt="Schermata 2020-10-26 alle 15 40 16" src="https://user-images.githubusercontent.com/589911/97187026-4f72da80-17a2-11eb-8386-cb47581f1fd8.png">

On hold until @Tressley can confirm this is the desired behavior. I'm thinking some elements might need special treatment, for example on the header menu the purple outline might not be visible:

this is the default style on Edge

<img width="477" alt="Schermata 2020-10-26 alle 15 47 15" src="https://user-images.githubusercontent.com/589911/97187252-91038580-17a2-11eb-97b1-903d4a861880.png">

**Comment by Tressley** [comment]
This is the focus state that's used on buttons and the various other elements. Applying it globally hasn't been tested, but I think we could move forward with the decision and track the areas that may seem problematic.

**Comment by paglias** [comment]
I reviewed this a bit more and I think it's a bad idea actually, too many things that could go wrong
