### ISSUE TITLE
Guild member list currently allows searching by Display Name only

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12729]
As reported by @Nakonana (33bb14bd-814d-40cb-98a4-7b76a752761c):

"... when searching for a user via the guild member list, one can only search by Display Name and not by Username. I find searching by username much more practical because people change their display name frequently while they usually stick with their username once it's established :)"

There's two ways we could fix this:

1. ~Allow searching by Username only.~
2. **Allow searching by either Username or Display Name.**

I suggest option 2 (Username and Display Name) because that will make it much easier when searching for players who have a default hb-12345... Username. (Note though that challenges allow searching by Username only.)

~I'm marking this as suggestion-discussion but if there's no disagreement to that in a week, I'll mark it as help wanted for Option 2 (Username and Display Name).~
(If that's done, we could consider enabling Display Name searching for challenges too.).

**Comment by Nakonana** [comment]
I actually feel like the second option was a thing in the past and one could search by either, so maybe looking through past changes could help fixing this issue...?

**Comment by HerrMoriden** [comment]
is this still an issue ? would like to work on this

**Comment by Alys** [comment]
@HerrMoriden You have a couple of other issues assigned to you so we'll keep this one open for someone else to work on. When you've finished the other issues, post again here if you'd like to claim this one. Please see [this comment from Matteo](https://github.com/HabitRPG/habitica/issues/11162#issuecomment-727601277) about claiming just one issue at a time. :)

**Comment by jbusa22** [comment]
Can I work on this one?
