### ISSUE TITLE
HTML page Title tag for Guilds says "Group Plans"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12738]
When you are viewing a Guild that does not have a Group Plan, the title says "Group Plans".
It should say "Guilds".

The two examples below are public guilds that definitely don't have Group Plans in them.

![image](https://user-images.githubusercontent.com/1495809/97654801-75a0bf00-1aaf-11eb-94f0-6349bc2c84a3.png)
![image](https://user-images.githubusercontent.com/1495809/97654855-8ea97000-1aaf-11eb-84f5-5c0f02dc187d.png)

_Thanks to @citrusella for reporting this._

**Comment by Alys** [comment]
More confirmation from @thewilloftheshadow  / beinginhisshadow (2eb203f5-1b1e-4e5d-84a4-22f130a1090e): 

"it happened to me. I opened The Mystery Train guild from my notifications from this guild, and while I was in The Mystery Train, the title still said Report A Bug. It did not happen, however, when switching between guilds from the Discover Guilds or My Guilds page"

**Comment by Alys** [comment]
Ugh. Ignore that. Wrong issue.

**Comment by Alys** [comment]
@thewilloftheshadow / beinginhisshadow (2eb203f5-1b1e-4e5d-84a4-22f130a1090e) has posted technical details:

"... the Group Plans does show up for me. I went looking in the code, and saw that the section is in fact set to the wrong variable for line 504 in this file:

https://github.com/HabitRPG/habitica/blob/d678eb920f9b2c581475f1be4b9d1581ca64fa57/website/client/src/components/groups/group.vue#L500-L508

`this.$store.dispatch('common:setTitle', {section: this.$t('groupPlans'), subSection: this.group.name });`

"This was changed in PR https://github.com/HabitRPG/habitica/pull/12627 which was pulled to the server today"

**Comment by thewilloftheshadow** [comment]
I can take this on (:

**Comment by Alys** [comment]
@thewilloftheshadow Fantastic, thanks. :) It's yours.

**Comment by thewilloftheshadow** [comment]
Sorry about the delay, I'm having trouble setting up my local copy so I can test and make sure the change didn't affect anything else

**Comment by paglias** [comment]
Looks like normal guilds / parties and group plans use the same component (group.vue) so we'll have to add a check on whether you're viewing the group as a group plan or not (probably by looking at whether `group-plans` is in the url). Note that with https://github.com/HabitRPG/habitica/pull/12743 merged there are a couple more places to update in the component file, make sure to work on an up to date version of the `develop` branch.

@thewilloftheshadow let me know if you need any help

**Comment by thewilloftheshadow** [comment]
I think I got it all, but there is one space to check that I noted in the PR
