### ISSUE TITLE
HTML page Title tag for Guild contains the previous Guild's name

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12739]
When you go from one Guild directly to another, the page title does not update itself. 

Steps to reproduce:

1. Wait until you have a notification for new messages from any Guild. Do not dismiss the notification!
1. Go to Tasks and reload the website to clear any old data.
1. Go to Guilds > Discover Guilds.
1. Click any Guild.
1. Observe that the page title correctly displays the name of the Guild. (NB the title will say "Group Plans" instead of "Guilds" but that's logged separately: #12738).
1. Visit a different Guild by using the link in your notification about a new message. 
1. Observe that the previous Guild's name is still shown in the page title. See the screenshot below from Nakonana.

This was reported by @Nakonana (her post is below for posterity :smiley:) and by @citrusella (who says it may be intermittent) and reproduced by me a few times (with my Habitica-related extensions and styles disabled).

![image](https://user-images.githubusercontent.com/1495809/97655542-0af08300-1ab1-11eb-8fd4-22aef4574e81.png)

---

@Nakonana wrote:
_"Ahoy, Admirals! It appears, th' squirrels' ship be sailin' under th' pirates' flag recently. I be knowin' fer bein' a navigator on th' pirates' ship me sense o' orientation be all but great, yet I did not expect I would board th' wrong ship! Aarrrr! xDDD_

_Jokes aside: there seems t' be a small bug with th' new feature that names tabs in accordance t' one's current location in th' Habitican seas, but it looks like th' GPS system be a bit broken (or just slow, because 'tis not 2020 in Habitica yet, right? xD). As a result, th' tab name be displayin' th' previous location instead o' th' current location. Th' problem can be solved by reloadin' th' tab._

_Now, that certainly won't help with me sense o' orientation, aarrr!_

_(Win 10, Firefox 82.0.2, see screenshot above for possible Extensions interference)_

**Comment by Alys** [comment]
@thewilloftheshadow / beinginhisshadow (2eb203f5-1b1e-4e5d-84a4-22f130a1090e) has posted technical details:

"... the Group Plans does show up for me. I went looking in the code, and saw that the section is in fact set to the wrong variable for line 504 in this file:

https://github.com/HabitRPG/habitica/blob/d678eb920f9b2c581475f1be4b9d1581ca64fa57/website/client/src/components/groups/group.vue#L500-L508

`this.$store.dispatch('common:setTitle', {section: this.$t('groupPlans'), subSection: this.group.name });`

"This was changed in PR https://github.com/HabitRPG/habitica/pull/12627 which was pulled to the server today"

**Comment by citrusella** [comment]
I think that code was related to #12738 rather than this one? (Or maybe the change itself is related to both, but I think the report was for the other bug? :thinking:)

**Comment by thewilloftheshadow** [comment]
The part I added was about the Group Plans showing up instead of Guilds for the section, not the title changing, so that's why

**Comment by Alys** [comment]
Ugh. Ignore that update. Wrong issue.

**Comment by Alys** [comment]
More confirmation from @thewilloftheshadow / beinginhisshadow (2eb203f5-1b1e-4e5d-84a4-22f130a1090e):

"it happened to me. I opened The Mystery Train guild from my notifications from this guild, and while I was in The Mystery Train, the title still said Report A Bug. It did not happen, however, when switching between guilds from the Discover Guilds or My Guilds page"

_[EDIT: I've deleted a post from citrusella saying quite correctly that I'd added the wrong update to this issue. Thank you and let us never speak of this again. :smiley:]_

**Comment by thewilloftheshadow** [comment]
The part I added was about the Group Plans showing up instead of Guilds for the section, not the title changing, so that's why. I would be willing to take on fixing that, but I don't know enough about Vue to be able to fix the other

**Comment by jbusa22** [comment]
I can look into this given I worked on the title stuff

**Comment by Alys** [comment]
@jbusa22 Thank you! Marked as in progress. Thanks for the fast PR!
