### ISSUE TITLE
can't buy Gems using Stripe

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12731]
_@CathB (36976c15-5bcd-4197-965c-750d865abcd2) has posted to the Report a Bug guild to report being unable to use Stripe to buy Gems. The material below is collated from three posts there._

"I'm trying to buy gems, both by clicking on the gem icon and by going to my avatar>gift icon>gift gems. Tried both in Google Chrome and Mozilla Firefox. When I select "credit card" as way of payment, nothing happens. Almost nothing at least, as I see "waiting for q.stripe.com" and simalar (different prefixes before stripe), when I hover my mouse over the credit card button. (Yes, my internet is slow, as I've exceeded my monthly amount of data, which makes some websites terribly slow! The slow internet might be to blame.)"

"I've selected an amount of gems to buy. In Firefox, there was a spinning circle that did spin for a while. But then it stopped spinning and nothing happened. In Chrome, there's no spinning circle."

"I don't use any browser extentions which are directly related to Habitica.
I don't use any Stylish/Stylus/Greasemonkey/Tampermonkey themes or styles or scripts that are directly related to Habitica either.
I dont't use any browser extensions or scripts that are related to ad blocking or privacy or social media tracking. (At least I can't remember setting up any extensions!)

"I ckecked in an incognito window in Firefox now. I [clicked] on the gem icon and tried to purchase gems. There was a spinning circle, which spinned for a long time the first time. But nothing happened. Then I tried clicking the credit card button again, the spinning circle appeared for a few seconds. Then nothing happened. (The Amazon button doesn't show in incognito mode.)

"I've also tried buying gems by going to the gem icon in an incognito window in Chrome. Nothing happens when I click the credit card button. (The Amazon button is visible)."

**Comment by paglias** [comment]
Can't reproduce, I'd suggest to try with a different internet connection and make sure there are no ad blockers enabled

**Comment by paglias** [comment]
@Cathb is this still an issue?
