### ISSUE TITLE
HabitRPG will not log in on linux mint with google chrome!

### ISSUE THREAD

**Issue by pixelpax** [HabitRPG/habitica#1275]
No javascript errors; this is probably a backend problem. For the first time, I tried to log on using google-chrome (version 27.0.1453.110) on Linux Mint 15. I hit "play" on the index page, then I hit "login/register" and submit my login information. Instead of my user account, I am logged onto a user called anonymous, which contains all default parameters. From this user page, I can log myself out and repeat this process indefinitely. I have tested this four or five times with consistent results. I am able to successfully log into my account in chrome on Windows 7 and with firefox in Linux Mint 15. I also have been logging on with my phone using Magic Mickey's client. 

**After I wrote this (but before I submitted) I tried changing something on the "anonymous" user (added a habit). To my surprise after logging out and logging back it the site correctly navigated me to the correct user page. It has done so now three times. Weird problem, seems to be gone though...

**Comment by lefnire** [comment]
Interesting, could have caught the server on a down-swing. Paste your UUID in here, in case it happens again I'll have it handy to debug the issue

**Comment by pixelpax** [comment]
Sure, it's 730d2d0f-daf1-4b2c-b2ea-d1df45f2679b.
Sorry it wasn't included in the OP, I know the bug report instructions request it :/

**Comment by lefnire** [comment]
I'm gonna leave open for a tad, chime in if you experience it again in the future.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
