### ISSUE TITLE
@Username in private message does not behave as a link until after a reload

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12764]
As reported by @citrusella:

"If you type and send an @ mention in your PMs (for instance, to have a direct reference to someone's profile), then even if it's typed right, it has all the elements of a mention except... the link. The link happens, but you can only access it if you visit a different area of Habitica entirely (not just another PM) and then go back to the PM, at which point it's properly linked."

Confirmed.

Steps to reproduce:

1. Send a new PM to someone (to yourself if you wish). Include an @Username in it.
1. Observe that the Username looks like a link - e.g. the screenshot below.
1. Hover over the Username. Observe that it has incorrect behaviour:
   * your mouse cursor does NOT change to an arrow
   * the profile URL for the Username does not appear in your browser's status bar
   * the Username is not clickable
1. Reload the website OR go to a different page and then back to your private messages.
1. Hover over the Username. Observe that the Username now behaves correctly:
   * your mouse cursor change to an arrow
   * the profile URL for the Username appears in your browser's status bar
   * the Username is clickable and opens the user's profile page in a new tab

![image](https://user-images.githubusercontent.com/1495809/98354201-1d982880-206c-11eb-8cc4-615552d9b944.png)

**Comment by kevechen** [comment]
Hi, I'm pretty new to this project. I wasn't able to find a "good first issue" issue that hasn't been started already, so I was wondering if I can tackle this one! I was also able to reproduce this issue locally!

**Comment by Alys** [comment]
@kevechen Thank you! I've marked it as in progress for you. Post here if you have questions or run into problems.

**Comment by kevechen** [comment]
Hi, sorry it took so long, but I was able to print out the message to the console and it seems like an @Username message is being returned correctly with all the formatting (at least I think it is), so is the correct fix to manually reload the page ourselves?

**Comment by kevechen** [comment]
Ah, I investigated further and saw the text was not set after the response came back! I'll make a PR shortly!
