### ISSUE TITLE
RYA shows incorrect Dailies on two days after time zone change from Daylight Savings ending

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12765]
This bug occurs in the two days following rhe time zone change that happens when Daylight Savings ends, such as the USA's 1 November change from daylight savings time to normal time (e.g., New York changed from UTC-0400 to UTC-0500).

The bug applies to the "Check off any Dailies you did yesterday" screen (also known as "Record Yesterdays Dailies" or "RYA").
**The RYA screen does not show the correct Dailies if you have Dailies that are due on specific days of the week/month.**
(This bug does not apply to cron. Cron correctly identifies scheduled Dailies.)

To reproduce this bug, on a local install:
   1. Create the following Dailies, with Start Dates before 30 October 2020:
      * "Fri" - due on Fridays only
      * "Sat" - due on Saturdays only
      * "Sun" - due on Sundays only
      * "Mon" - due on Mondays only
   1. Set your PC to use the "America/New_York" time zone (UTC-4 / EDT before 1 November; UTC-5 / EST after 1 November)
   1. Set your PC's date to 10am Saturday, 31 October, 2020.
   1. Allow the RYA screen to appear. Observe that it contains the "Fri" Daily (this is correct).
   1. Set your PC's date to **10am Sunday, 1 November, 2020**.
   1. Allow the RYA screen to appear. **Observe that it contains the "Fri" Daily** (this is wrong; it should be the "Sat" Daily). See screenshot below.
   1. Set your PC's date to **10am Monday, 2 November, 2020**.
   1. Allow the RYA screen to appear. **Observe that it contains the "Sat" Daily** (this is wrong; it should be the "Sun" Daily).
   1. Set your PC's date to 10am Tuesday, 3 November, 2020.
   1. Allow the RYA screen to appear. Observe that it contains the "Mon" Daily (this is correct).

The bug is caused by this code:
https://github.com/HabitRPG/habitica/blob/8ac48406e91f39a475f41bd11bfe01dab98aebe3/website/client/src/components/notifications.vue#L730-L732

Most of the time that works well. For example, when the RYA screen appears on Saturday, 31 October, when your time zone is UTC-4 (EDT), the value of `yesterDay` is `Fri Oct 30 2020 00:00:00 GMT-0400`, which is the start of the previous day, and so the correct Dailies appear in RYA. I.e., that's correct.

However, when the RYA screen appears on Sunday, 1 November, 2020, when your time zone is UTC-5 (EST), the value of `yesterDay` is `Sat Oct 31 2020 00:00:00 GMT-0400`. I.e., because that date is before the time zone change, it's in the old time zone (UTC-4), and so the date is actually one hour earlier than it needs to be for displaying yesterday's Dailies. As a result, the Dailies for the day before yesterday are displayed (i.e., Friday's Dailies instead of Saturday's Dailies).

Similarly, when the RYA screen appears on Monday, 2 November, 2020, the value of `yesterDay` is `Sun Nov 01 2020 00:00:00 GMT-0400`. Again it's one hour earlier than it needs to be, so Dailies for Saturday are displayed instead of Dailies for Sunday.

When the RYA screen appears on Tuesday, 3 November, 2020, the value of `yesterDay` is `Mon Nov 02 2020 00:00:00 GMT-0500`, which is at exactly the start of the previous day and so RYA correctly shows the previous day's Dailies.

The screenshot below is what you see on Sunday, 1 November. Friday's Daily is displayed, when you should be seeing Saturday's Daily.
![Sunday-shows-Friday](https://user-images.githubusercontent.com/1495809/98464203-047aad80-220d-11eb-9f46-85ca397ab046.png)

**Comment by thewilloftheshadow** [comment]
Just curious, does this happen in reverse when Daylight Savings time begins? That date would be March 8, 2020, or March 14, 2021

**Comment by Saiyara6133** [comment]
Hi, I am looking to contribute to an open-source. Is this issue still available to work on?

**Comment by Alys** [comment]
@Saiyara6133 It is available, thank you! I've marked it as in progress for you. Post here if you have questions or run into trouble.

@thewilloftheshadow I wouldn't expect it to happen in the northern hemisphere in the Spring DST change because that would cause the value of the `yesterDay` variable to be one hour greater than required, which still puts it in the previous day and so the correct Dailies would be shown.
I expect that it will happen for the Autumn DST changes in the southern hemisphere so getting it fixed before then would be great if we can manage it. I believe that fixing it before March should cover all relevant countries.

**Comment by shanaqui** [comment]
@Saiyara6133 Hi there! Just checking in whether you're still interested in working on this issue. 

If we don't hear from you within a week, or you're not interested anymore, I'll mark this as help wanted again. :) No rush to complete a fix or anything, we're just making sure the issue doesn't go stale!

**Comment by Saiyara6133** [comment]
Hi, I am still working on it.

**Comment by Saiyara6133** [comment]
Hi, I submitted a pull request for this issue, will it be reviewed soon?
