### ISSUE TITLE
Issues on mobile version (e.g. with feeding pets, viewing notifications, viewing profiles)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12784]
Best described via screenshots!

![Screenshot_20201107-101443_DuckDuckGo](https://user-images.githubusercontent.com/8144640/98962740-d643e900-24fe-11eb-9c17-ae9b8360f4ac.jpg)
![Screenshot_20201107-101210_DuckDuckGo](https://user-images.githubusercontent.com/8144640/98962744-d7751600-24fe-11eb-833d-d7f050a4bfcd.jpg)
![Screenshot_20201107-101407_DuckDuckGo](https://user-images.githubusercontent.com/8144640/98962747-d80dac80-24fe-11eb-88f7-2664ffb589d4.jpg)

User: "these captures are taken with a Samsung galaxy A8. Same or very similar results in a Samsung galaxy S7." 

It appears to be via the DuckDuckGo browser, but the only one I couldn't reproduce in Chrome on a Google Pixel 3 was the Stables one.

**Comment by Taukir-Khatri7201** [comment]
You can try CSS media queries to fix this issue.

**Comment by Taukir-Khatri7201** [comment]
hope it will help you..... :)

**Comment by thewilloftheshadow** [comment]
Can reproduce on Chrome and Safari on an iPhone 7![image](https://user-images.githubusercontent.com/35580099/99155445-a2430200-267d-11eb-8603-a2d8d82d9490.png)![image](https://user-images.githubusercontent.com/35580099/99155448-a40cc580-267d-11eb-828b-995fea0d3fce.png)![image](https://user-images.githubusercontent.com/35580099/99155449-a66f1f80-267d-11eb-8d4f-bb9c7d1208ea.png)

**Comment by Nakonana** [comment]
Confirming all of the above for Sony Xperia Compact, no-name AddBlock browser and adding a few:

Like @thewilloftheshadow I'm not able to see my class in the task screen and when opening the skills section, the "+" button is floating in front of it
![class and plus button](https://trello-attachments.s3.amazonaws.com/5dfa77963d47893b8474869d/5e261bfa0c5bcf1647c15dbd/d634e1c228513fb8431e9fc991fa7bcc/Screenshot_20201118-092448.png)


There are no titles or descriptions visible for some guild challenges (but not for all) and the chat message buttons (e.g Liking, Deleting) are off (when holding the phone horizontally) :

![challenges](https://trello-attachments.s3.amazonaws.com/5dfa77963d47893b8474869d/5e261bfa0c5bcf1647c15dbd/75fc202c2a529a470487df619b409da9/Screenshot_20201116-194238.png)

**Comment by hazwong** [comment]
Could I work on this issue if no one is working on it? Thanks!

**Comment by paglias** [comment]
To be honest given the big amount of work that would be needed to completely fix the mobile experience I'm not sure it's worth starting. Let's hear from @Tressley

**Comment by Tressley** [comment]
I agree. This issue doesn't have a clear direction either in terms of completion. Many areas of the Habitica website are broken when viewed on a mobile browser. I don't think we need this in help wanted.

**Comment by CuriousMagpie** [comment]
Closing this issue for now. We recommend using the mobile apps whenever possible and if the team decides to clean up the mobile browser experience, we'll target specific pain points.
