### ISSUE TITLE
Shared style for small modals

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12781]
All the new small modals (level up, drop cap reached, payments success info, won challenge, ...) share some basic style elements:

- Title color and size
- Paddings
- In some cases the footer
- Same width

We should abstract the styles in a shared component or css class so they're not repeated every time.

Some examples:

<img width="384" alt="Schermata 2020-11-11 alle 16 00 13" src="https://user-images.githubusercontent.com/589911/98827555-4dae4580-2437-11eb-9f00-a6bded72140b.png">

<img width="366" alt="Schermata 2020-11-11 alle 16 00 52" src="https://user-images.githubusercontent.com/589911/98827556-4dae4580-2437-11eb-9837-76a1b8e7abae.png">

<img width="442" alt="Schermata 2020-11-11 alle 15 59 57" src="https://user-images.githubusercontent.com/589911/98827551-4c7d1880-2437-11eb-8e9a-e22c3a0417fb.png">

**Comment by kimiannalena** [comment]
I'd like to take a look at this and try to abstract a css class for these modals, if that's fine

**Comment by paglias** [comment]
Hi @kimiannalena , thanks for your interest, I'm marking the issue as in progress for you.

For now we'd like to focus on:

- the width of the modal
- the footer style
- the footer button
- the heading style
- the general positioning of elements and basic text styles

**Comment by shanaqui** [comment]
Hi @kimiannalena! Are you still working on this issue? Can you check in within the next week to let us know? If not, or if we don't hear back, I'll mark this as help wanted again so the issue doesn't go totally stale. :)

**Comment by kimiannalena** [comment]
Hey @shanaqui, unfortunately I will not be working on this Issue anymore. I attempted to fix this issue as part of a study project, but I've had major problems installing the project locally (I tried it on Windows 10 and Linux Kali in a virtual machine). I followed the instructions one by one, multiple times... in the end it mostly ended with an error of type ELIFECYCLE, that I am not able to fix.

**Comment by shanaqui** [comment]
Thanks for letting us know! If you do want to try again, you might be able to get support with the installation issue in the Aspiring Blacksmiths guild. I'll mark this issue as Help Wanted again, though.

**Comment by thewilloftheshadow** [comment]
Don't forget the needs reply label ;)

**Comment by benkelaar** [comment]
Hiya!  I was already thinking of doing this when implementing the new level-up modal.  Great idea to turn it into an issue.  I'd like to pick this up.

**Comment by paglias** [comment]
sure @benkelaar

**Comment by benkelaar** [comment]
@paglias I have a fairly decent solution now.  It's basically a "small-modal" component that has three slots.  One for content between the stars, one for the main body and an optional one for content with a grey background.

Title and button text can be passed in as properties.  It also fires a `buttonClicked` event when the button is clicked (Which the object cap reached popup uses to open learn more).

It seems to work well for these three modals, is there a list somewhere of which modals should all use this same layout or shall I just dig through the codebase and see which ones I can find?

@Tressley Also I noticed that while I horizontally mirrored the stars among the main image, in the other popups it's been rotated 180 degrees.  The difference of course is a vertical flip between left and right.  Visually which one do we prefer? Mirror or 180 degrees rotation? (Same question for the reward sparkles)

**Comment by Tressley** [comment]
@benkelaar -- Becoming a bigger fan the more I see you pop up around here. Another good catch! The sparkles should be mirrored, not rotated. Here's a quick screenshot:

![image](https://user-images.githubusercontent.com/2686586/104956939-24f87e00-599b-11eb-809e-ab015e5f9905.png)
