### ISSUE TITLE
Task on-click outline is only around title

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12796]
_As reported by @tripplehelix (874e648a-2df7-4312-a9e6-7217be462204):_

"When clicking on a task title to edit the task, only the title is outlined not the entire white portion. Not sure if this is on purpose.'

I'm labelling this as "on hold - needs design" for a design-related decision about any potential fix.

![image](https://user-images.githubusercontent.com/1495809/99892753-068c4400-2cc4-11eb-85d9-bc38ce029b3a.png)

**Comment by paglias** [comment]
I'm pretty sure this is on purpose but @Tressley can confirm

**Comment by Tressley** [comment]
This is technically correct in that the click area to edit a task is the task title and it's receiving the focus state.

**Comment by citrusella** [comment]
Should that area also get a focus state when casting a task-based skill? (Because it does.)

**Comment by Tressley** [comment]
@citrusella -- From a design perspective, yes, I don't think it should get the focus state since we're treating the task as the whole object when casting a skill. However, I think it's just a how it was implemented since clicking on the title is technically focusing it. Not sure this needs to be an issue. Just a small artifact.

**Comment by paglias** [comment]
I'm marking it as `help wanted` and `good first issue` since it looks like a perfect bug for a new contributor

**Comment by benkelaar** [comment]
I don't think this is a bug, but actually an accessibility feature.  When tabbing through tasks, this highlight shows the difference between whether the focus is on the title (Open edit tag on Enter), on the + or check button, or whether it is on the hamburger menu of that specific task.  I think that highlight has value and that just removing it is not the right call.

**Comment by Tressley** [comment]
Yeah, we defintely don't want to remove the outline by default as it is an accessibility feature. To Citrusella's point, there's a double-outline appearing when casting a skill on a task. For that instance I think the task title shouldn't have an outline since the skill is being cast on the entire task.

**Comment by SabbirAhmedAdor629** [comment]
Hi, I just got to know about open source and I want to work on this issue is it still Open. I am in my freshman year know little about HTML and CSS.

**Comment by Alys** [comment]
@SabbirAhmedAdor629 Thank you! I've marked this as in progress for you.

Habitica's website uses Vue.js so it won't be the same as the HTML and CSS that you're used to, so post here if you have any questions. If you'd like to read some introductory material about Vue, our wiki's [Guidance for Blacksmiths](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths) page has some links in the "Website Technology Stack" section.

**Comment by Alys** [comment]
@SabbirAhmedAdor629 I'm very sorry, I've just realised that someone else is already working on this, so I'm afraid it wasn't actually available for you to start work on. :(

Also, based on the most recent comments, I'm not sure if Habitica's staff actually want a fix done for this. It's possible that it was meant to have the "help wanted" label removed. Or is a fix desired but only for the case when the task is having a skill cast on it? I've changed it back to "on hold - needs design" while this is under consideration.

@codexdelta I see you've created a pull request for this. Thank you!
It's safest to comment on an issue first when you want to claim it and then wait for approval to proceed - that lets us know that we need to mark the issue as in progress, and has other benefits (see "Ways to Help" in [Guidance for Blacksmiths](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths) for more details). I've temporarily removed the "ready for review" label from your PR until we've sorted out what the desired fix is, but we'll look at your PR once this is clarified!

**Comment by SabreCat** [comment]
@SabbirAhmedAdor629's PR removed the task title focus outline entirely, even when tabbing, which I don't think is what we wanted based on e.g. https://github.com/HabitRPG/habitica/issues/12796#issuecomment-762359870. Is it accurate to say we only want to remove this focus highlight when using a skill on the task? Or should it not light up on any click, but we keep it for tabbing? @Tressley

**Comment by Tressley** [comment]
We only want to remove the outline on the task title when a skill is being cast. The outline should exist otherwise.

**Comment by CuriousMagpie** [comment]
I'll take this one!

**Comment by CuriousMagpie** [comment]
After some testing, I've discovered that the title outline only activates on skill use if you click on the title area. If you click on the option menu, that highlights. If you click below the title, only the complete task box highlights.

I'm not sure this is something that needs fixing--we would have to eliminate the focus outlines on a skill-click action and I don't know how that would affect overall accessibility for folks with screen readers or who tab through the fields.

@Tressley, do you have any thoughts on this?

**Comment by Tressley** [comment]
@CuriousMagpie -- I agree that I don't think this is a bug, or something that needs fixing. Ideally, the whole task would receive the outline when casting a skill, but the trade-off seems to be a loss of accessibility. Let's go ahead and close this for now.
