### ISSUE TITLE
View Party / Guild "sort by class" and "Asc" drop down visual inconsistencies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12795]
_@tripplehelix (874e648a-2df7-4312-a9e6-7217be462204) reports:_

"The 'View Party' overlay has a different drop down type to the rest of the Habitica website. This is causing inconsistencies with the overall colour theme."

It also applies to guilds and to the Asc/Desc dropdown in the same modal.

I'm labelling this as "on hold - needs design" for a design-related decision about any potential fix.
 
![image](https://user-images.githubusercontent.com/1495809/99892714-62a29880-2cc3-11eb-899f-00a1cd366cd5.png)

![image](https://user-images.githubusercontent.com/1495809/99892683-09d30000-2cc3-11eb-9f32-b9cbd9cd5d54.png)

**Comment by paglias** [comment]
cc @negue

**Comment by EmmaK2020** [comment]
ssssssss
