### ISSUE TITLE
Habit panel doesn't load shows "undefined"

### ISSUE THREAD

**Issue by DesignLemming** [HabitRPG/habitica#1279]
After log-in nothing loads in the habit panel, only shows "undefined." I also cannot get to the options page or anything else. The only things that work are logout and I can click on the crier and that page will load. Tried multiple refreshes and tested on mobile Chrome, IE and Firefox.  

Win 7
Chrome 28.0.1500.72 m
![habiterror](https://f.cloud.github.com/assets/3505471/849117/4682593c-f46e-11e2-80b1-f95d3bb641c4.png)

**Comment by lefnire** [comment]
[UUID](http://community.habitrpg.com/content/user-id)?

**Comment by DesignLemming** [comment]
I can't get to the options screen to load through the website. Just realized I had to use it for the Chrome App and was able to pull it from there: 50d86153-c227-4856-b09c-ebaff4a6418e.

**Comment by lefnire** [comment]
can you try clicking "clear filters" (circled x, right of the tags) and see
what happens? any javascript errors that you're seeing?

**Comment by DesignLemming** [comment]
Tried "clear filters," nothing happened. There is a screen shot of the Chrome console, showing 2 errors, hope this helps, these come up when I log-in.
![habiterror2](https://f.cloud.github.com/assets/3505471/851128/cff7b05a-f495-11e2-99a7-49845497b833.png)

**Comment by lefnire** [comment]
That is indeed a very useful screenshot, thank you. Can you try beta.habitrpg.com now?

**Comment by DesignLemming** [comment]
Error screen from beta site.
![habiterror3](https://f.cloud.github.com/assets/3505471/851342/5cc52fd2-f499-11e2-8ac1-6b547caa8965.png)

**Comment by lefnire** [comment]
Alright, elevating and working on it. This is a crit

**Comment by lefnire** [comment]
Pushing up another candidate fix: https://github.com/HabitRPG/habitrpg-shared/commit/dab72e5865b69009a6c3a82ddf2998813358fd5a . It looks like your items are larger than the maximum items in the system. Aka, there are 7 weapons; however, they're 0-indexed so the max is 6, but you have weapon 7 - which means it couldn't find info on that weapon. Likely numbers manually entered in the restore dialog, I put in some fail-safe for situations like that, so give this a shot.

Also, you may want to clear your completed todos section ("completed" tab at the bottom of the todos column), it will clear  up some CPU

**Comment by lefnire** [comment]
Better yet, I should instead do a safety check when the modal dialogue is saved and set the number accordingly. I'll keep this issue open until I implement that

**Comment by DesignLemming** [comment]
Looking back at this I did do a restore after a vacation before the resting in the tavern was implemented. I guess when I put in the 7 to restore my weapon it was showing the weapon 6, all was fine until that error.

Thanks for the fix.
