### ISSUE TITLE
missing margin on checkboxes at User Icon > Settings

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12794]
The checkboxes at User Icon > Settings ("Site" tab) have no margin between them and the text.

![image](https://user-images.githubusercontent.com/1495809/99870546-90ce9c80-2c1f-11eb-9abb-600d03425877.png)

I'm labelling this as "on hold - needs design" for a design-related decision about how much margin should be there.

_Thanks to @tripplehelix (874e648a-2df7-4312-a9e6-7217be462204) for reporting this._

**Comment by kimiannalena** [comment]
After testing what looks most natural, I would recommend 8px or 0.5em or rem, depending on which unit is preferred in the project. It will look like this:
![checkbox margin](https://user-images.githubusercontent.com/70015140/101982972-d529e700-3c77-11eb-9581-12c35ccaf1f3.jpg)
A bigger gap will visually detach the text from the checkbox, so I think this distance works just fine.
