### ISSUE TITLE
Little design flaw

### ISSUE THREAD

**Issue by Mapel** [HabitRPG/habitica#128]
As an old RPG-fan I love this concept, but I miss something: monsters or opponents.

This opponent should have health points and everytime you complete a ToDo or a daily, the monster gets a hit to the HP like an attack from you. If you miss dailies or do a bad habit you get a hit to your HP like an attack from the monster. After defeating the monster you get EP and some loot/gold. The monsters get tougher and the rewards bigger. If you fail to kill a monster you can fall back to the last with half hp or something.
Instead of getting green habits which doing less damage to your hp (that is actually bad because you do not want to let loose on a habit and get less penality; it is a wring signal) it should do more damage to your opponent. That would be a positiv reward for not letting loose on a habit. For red habits it should work just the other way round.

I can see many more feature to come with monsters. You could for example team up with others to defeat big bossmonsters. Other player could create monsters for a challenge or you create them randomized. You could implement attributes for a true rpg-game which determine your hp and your attackdamage and other stats. There could be different elements like fire, ice and this stuff.

There is plenty off room to develop this further.

**Comment by hookang** [comment]
Agreed. I was thinking each task/habit/dailies can be a monster you summon against yourself and you attack. Bosses are tasks you haven't done etc...

Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote: 
- [Boss Battles](https://trello.com/c/WP3dXij9)
- [Battle Creatures](https://trello.com/c/MnfgnOF0)
- [Ongoing Realtime Adventure](https://trello.com/c/edwHxp5G)
