### ISSUE TITLE
Can't Check Out of Tavern

### ISSUE THREAD

**Issue by Raibean** [HabitRPG/habitica#1281]
This is the third day in a row I've tried to check out of the inn. It will say I'm checked out, but at midnight, I'm checked in again and my dailies haven't reset.

I'm on Chrome, my username is Rhiannon WeasleyIsOur King, and I haven't noticed anything else weird happening.

**Comment by lefnire** [comment]
@Raibean can you try refreshing, checking out, then refreshing again to see if the change went through? See http://habitrpg.tumblr.com/post/55792029689/bug-workarounds (esp. No 1) for the details there.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
