### ISSUE TITLE
suggestion:chrome extension-buy a game website time with reward golds.

### ISSUE THREAD

**Issue by aileia** [HabitRPG/habitica#1282]
hey i want to want a script for a reward of mine, i set a reward for allowing 25 minutes of play time in a soecific facebook game for 4 golds, 

the script should allow only 25 minutes of time in that site, and it should be stackable so whenever i buy time, i could increment the the allowable time, but when i use the website, the allowable time should decrease., do you know any such script, all the web site blockers are all or nothing type or allowing the website for example only in the afternoons. it would be great if i could buy a reward like that

if it could be built in the chrome extension, it would be lovely.

**Comment by wc8** [comment]
@aileia I think [](https://trello.com/c/PQz88jll) is what you’re after. You may wish to vote for it if you have not already.

**Comment by SabreCat** [comment]
@wc8 Was there supposed to be a link to something?

**Comment by wc8** [comment]
Oh… this is it: https://trello.com/c/2iIxa9J5 (Reward Sites)
