### ISSUE TITLE
Posting in Wrong Guild's Chat

### ISSUE THREAD

**Issue by pheldurin** [HabitRPG/habitica#1283]
I'm in a lot of guilds (13), and twice when I went to post in the one guild's chat, nothing showed up, but then I saw it a couple days later posted in the another guild's chat. Also—I've noticed this several times, including twice today after posting a message—one guild's chat shows up under another guild also. Maybe this should be another ticket, but I think they're related. 

To test this, I posted a test message in Elijah's Habit, it didn't show up there, Classic Scholars showed Bailey Appreciation Guild chat (see attached pics), then after I refreshed HRPG, the test message showed up in Classic Scholars (screenshot doesn't show it, but Elijah's Habit is to the left of Classic Scholars in my guild UI). 

For another test, I posted a test message in Dubsteppin', which showed up fine, but when I posted a second test message, the chat from Elijah's Habit showed up in that guild, but only most recent four chat entries. since that's how many postings there had been in Dubsteppin'. Refreshing HRPG, both messages appeared in the correct guild. The problem seems to occur more when I'm posting in the first few guilds in the list, directly to the right of Public Guilds.

I'm using Chrome; user ID: 75b93321-66b9-49bd-9076-052499c1d2bf.
![right_guild_chat](https://f.cloud.github.com/assets/3946749/859727/bf20a460-f587-11e2-8b28-c9f5f01efb36.PNG)
![wrong_guild_chat](https://f.cloud.github.com/assets/3946749/859728/c4d270c8-f587-11e2-9caa-8f83e477ed29.PNG)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
