### ISSUE TITLE
Registration Textboxes Are Scrunched Up

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#1284]
When I try to register a new account, I see an impossible scrunched up set of textboxes.

I am using Windows 7 x64 with IE 10. My zoom level is 100%.

![screenshot](https://f.cloud.github.com/assets/1581929/860385/e6f644e6-f5a4-11e2-8341-acaeaf68cec5.png)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
