### ISSUE TITLE
Guild Turned Into Party?

### ISSUE THREAD

**Issue by cybrex** [HabitRPG/habitica#1285]
The Gaymers guild appears to have become a party. It is no longer listed under public guilds, and does not appear in my Guild memberships. Occurred sometime between 07/25/2013 and 9:00am CDT 07/26/2013.

Please Advise. More info available if needed.

**Comment by cybrex** [comment]
My user ID is 0fbddc3a-8fde-4fd8-9780-bff35a0f04bf if you wanna check things out for yourself. All of the info from the Gaymers guild (title/guild name/party name), members, and resources appear to have been simply copied to the Party section.

Having not been in a party previously, there's still a "leader message" (and I was/am the leader of the guild) - Not sure if that's a valid interface element of a party. There's also a bunch of people at the top of my screen, who I'm assuming are former Gaymers Guild members who are now my Party members.

Was using Firefox v22 on Windows 7 at the time that I noticed the issue.

**Comment by lefnire** [comment]
elevated to crit, will check into soon as i can

**Comment by lefnire** [comment]
that's really strange, the `type` property was unset. ( `{type:'guild'}` became `{type:''}` ). I fixed for now, investigating what happened

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
