### ISSUE TITLE
Shop on-hover popup should always disappear when moving mouse off item

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12884]
As reported by @johnjsal (624e48a3-cbea-4bbe-ae44-ca9183f49626):

**"when I go to Shops > Quests and click on a quest, the quest description pops up like normal, but when I close this pop-up, the smaller quest text window (the one that appears when you hover over a quest) remains locked on the screen. It won't disappear if you move the cursor around, but it will when you click elsewhere on the screen."**

The same applies to Shops > Market and Shops > Time Travellers and probably Shops > Seasonal Shop. The same fix should be applied to all of them (it may be shared code so it's possible that a fix in one place may fix all of them).

**Comment by JohnJSal** [comment]
I just want to add, in case it's helpful, that this issue also happens on the Tasks page when you click on a reward in the Rewards column (e.g. Subscriber Gems, a Background, etc.). Basically, it seems to occur with anything that has an on-hover pop-up.

**Comment by z0glen** [comment]
Hi there, I'd like to look into this!

**Comment by paglias** [comment]
@z0glen thanks! I've marked this as in progress for you
