### ISSUE TITLE
Dropdowns in members modal overflow in some languages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12891]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

In some languages, the label text for sorting the member list in Parties and Guilds doesn't fit the dropdown element:

![image](https://user-images.githubusercontent.com/4501321/102534322-2ff28280-406c-11eb-8924-506312a699ba.png)

**Comment by SachJay** [comment]
I dont mind working on this ticket, would be a good first ticket. Do we want the text to flow under (extending the box vertically) or do we want to cut it off like this: `This is a long sentenc...`?

**Comment by paglias** [comment]
I'd say we want to cut it off with ellipses at the end, the full text will show once the dropdown is open. Thanks @SachJay ! I'm marking it as in progress for you

**Comment by SachJay** [comment]
Apologies for the late reply but a bunch of things came up and I dont think I'll work on this soon. It won't be fair for me to hold on to this ticket so you can move it back to "help wanted". If by the time I am available again this ticket isn't completed, I can finish it.
@paglias

**Comment by Alys** [comment]
@SachJay Thanks very much for letting us know! I've set this back to help wanted.

**Comment by Helcostr** [comment]
I would like to work on this issue.

**Comment by Alys** [comment]
@Helcostr Thanks! It's yours. :)

**Comment by Helcostr** [comment]
I am explicitly stating my PR is ready to be reviewed (not sure if I should ping someone, or if I have to explicitly state in this issue that the PR is ready to be reviewed).
