### ISSUE TITLE
Social Sharing

### ISSUE THREAD

**Issue by timothyCoxon** [HabitRPG/habitica#129]
_Edited by wc8: Vote for this feature here: [Social Networks](https://trello.com/c/8TbkzhtR) 
    Note: This was split off from Groups/Parties, Sharing & Privacy options for clearer vote counting_
Liberally sprinkle social sharing throughout the application.
Enable people to share things like level-ups, badges and the like to social networks. 
Should improve the visibility of the application considerably.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.
