### ISSUE TITLE
Widget and Web not sync

### ISSUE THREAD

**Issue by MadeByBalaji** [HabitRPG/habitica#12903]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)
Widget is not synced with web unless the app is opened
[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
 

1. I closed  taskA on web
2. Open mobile screen and can also see the same taskA unclosed in mobile widget
3. Open and close habitica app without any changes
4. Now if I see the widget, the taskA is closed

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by paglias** [comment]
Hi @balaji303 , is the issue with the android or ios apps? If so it should be reported in their own github repositories https://github.com/HabitRPG/habitica-ios or https://github.com/HabitRPG/habitica-android
