### ISSUE TITLE
Skills you can't use at your current Level should not subtract Mana

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12904]
As reported by @citrusella :

"Casting a skill you don't have access to yet (i.e. a level 13 skill like Tools of the Trade when you're only level 12) deducts mana even as it tells you you need to be level [x] to cast it."_

The Mana is returned after a full sync has happened, but the expected behaviour is that it should never be deducted.

The screenshot below was taken immediately after I clicked on the level 13 skill.

![image](https://user-images.githubusercontent.com/1495809/103164570-eb7b9980-4858-11eb-824e-81649ae75d7a.png)

**Comment by saul-marquez** [comment]
I can try to fix this

**Comment by paglias** [comment]
thanks @saul-marquez ! I've marked it as in progress for you

**Comment by shanaqui** [comment]
Hi @saul-marquez! Are you still working on this? If not, or if we don't hear back from you within a week, I'll mark it as help wanted again so the issue doesn't go totally stale. :)

**Comment by saul-marquez** [comment]
I'm afraid life has gotten in the way. Go ahead and mark it. Apologies

**Comment by Helcostr** [comment]
I am taking a look at this, and have trouble replicating this issue.

Lvl 12 completely blocks my access, and I can't target a task.

Lvl 13 (de-leveled back to 12) shows a clickable interface, but a warning popup displays to let me know I can't use the skill.

**Comment by citrusella** [comment]
FWIW, the one(s) I've tried before aren't ones that target a task. They take the mana and also notify you that you can't use them immediately, but they do not give the mana back until you use the sync button. This is still happening because I just checked as a level 12 user trying to cast Tools of the Trade (a level 13 rogue skill).

I also made myself level 11 later in this test to try the level 12 skill (Backstab) as it's a targetable one, and it lets me go through all the motions to target and cast on a task but the cast isn't actually successful (as the level isn't met) and so the mana is refunded on a sync.

The error notification about the level always pops up, even though it still takes your mana (temporarily) anyway.

**Comment by Helcostr** [comment]
Ok, I will check Tools of the Trade lvl 12 rogue.

(Somehow I duplicated the issue using mage lvl 12 🤔 ).

**Comment by Helcostr** [comment]
I am now confident in my ability to fix this bug, and would like to work on the solution (familiarizing myself with the environment was daunting).

Although I am wondering if I should continue the plan of blocking the interaction on the client side (with client information), or I should have the mana (and similar) be subtracted after the server response...

**Comment by Alys** [comment]
@Helcostr Thanks for looking into this! I've marked it as in progress for you.

I believe the standard behaviour for skills is to show the deduction in mana immediately so that the player gets immediate feedback about their new mana total. I don't think we want to change that, so it's probably best to not change skills so that the mana is deducted after the server response. Blocking interaction client-side for skills you can't use is probably best.

@citrusella thanks for your help with the investigation!

---

_As an unrelated note for the record, I've deleted some of the older comments here that didn't have any information about the bug and the fix, to make the latest comments easier to find._

**Comment by Helcostr** [comment]
@Alys what about immediate deduction... then sync with player data on fail (just incase another client is doing simultaneous actions; I discovered this as I was using multiple tabs)? This way the mana is "refunded," and also the client stays synced with the server?

Ignoring more complex solutions, the simple "block on client side" is in the PR, but if u think I should go advance, I can make it WIP (dunno what the order of operation is for modifying the API w/o messing others up).

**Comment by Alys** [comment]
@Helcostr I think for this just blocking on the client side is fine. I've marked your PR as ready for review. Thanks!
