### ISSUE TITLE
Hourglass-purchasable Equipment should be unpinned when purchased

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12905]
As reported by @Nakonana and confirmed by me:

"When buying a pinned equipment set (Time Travellers) with an hourglass, the set is not automatically unpinned after purchase, even after refreshing the site."

The desired behaviour is that as soon as you've purchased a Mystery Item set with an Hourglass, if it was previously pinned to your Rewards column, it should immediately become unpinned.

The bug occurs regardless of whether you buy the item from Rewards or from the Time Travellers Shop.

_(The bug does not occur with Equipment that is purchasable with Gold or Gems, nor with Backgrounds purchasable with Hourglasses, nor with Quests purchased with Hourglasses - they're meant to stay pinned since you may wish to buy another later.)_

**Comment by samamill** [comment]
@Alys can I work on this?

**Comment by samamill** [comment]
https://github.com/HabitRPG/habitica/pull/12915

**Comment by Alys** [comment]
@samamill Thanks! I've marked this as in progress for you.

**Comment by beffymaroo** [comment]
@samamill Are you still working on this issue? Please let me know, and I can adjust labels if needed. Thank you!

**Comment by SabreCat** [comment]
The associated PR went unresponded-to for quite some time, so I'm opening this back up!

**Comment by abigley** [comment]
Hi, I'd like to work on this!

**Comment by CuriousMagpie** [comment]
Sure thing, @abigley! I'll assign it to you momentarily.
