### ISSUE TITLE
Sending password reset email is failing for some users

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12902]
This should be marked as "needs investigation", because I haven't been able to reproduce it, but it's happened a few times and it should be recorded and tracked until we can rule out a problem on our side.

Here is one example. Jules_1981 requested a password reset link several times via web and nothing happened. They emailed us for help on Dec 20, 2020, 11:35 AM, so the errors would be some time before that, in case that helps us find the details in Loggly.

I put their email in the form myself and it worked.

**Comment by paglias** [comment]
I can't find anything related to this on loggly
