### ISSUE TITLE
Strange potion/egg distribution

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1290]
Hi,

I'm not sure if it's a bug or done in purpose, but:
- I get a lot of base/white/desert potions
- I get a lot of pandas/fox eggs

This doesn't seem right.. I have 10 base potions left, for only one egg left to hatch (base lion).

Here is a screenshot:

![screenshot](http://i.imgur.com/nrBwHAm.png)

My user id: 84497c76-4028-4dd5-8403-69b4f5b12575

**Comment by gkatsev** [comment]
I've been getting a bunch of white potions with base and desert close behind.

**Comment by SabreCat** [comment]
I have the overall impression that the rarity of potions goes from left to right. Base potions are typically the most common and Golden the hardest to come by. Not sure if any variation in egg frequency is intended or not, though.

**Comment by gkatsev** [comment]
That does make sense. Though, seems to be very heavily skewed towards white/base.

**Comment by AndreCaseyScott** [comment]
As with all RPG that have item drops, there are some that are "common" that you get a boatload of, and the "rare" ones that only drop once in a blue moon. 

There has been some talk about adjusting the ratio, or selling unneeded potions or eggs for gold. #1048 in particular.

**Comment by gkatsev** [comment]
I just noticed the gem values for the eggs and potions. The eggs all have the same gem values while the eggs have different values.
For me, personally, I've received a lot more white potions than base potions even though the distribution implied by the gem values would suggest that base should be available a lot more.
Might be good to explicitly mention that there is a distribution for the drops, though, now that @onduhray mentioned it, it should've been obvious from the start :grinning:

**Comment by wlinna** [comment]
I already have all white and base pets and I still get new base and white hatching potions.

Pets are strangely distributed too. I only have 2 cacti and flying pigs yet I have all the dragons.

**Comment by AndreCaseyScott** [comment]
@dnyarri This is to be expected. What you get is decided using a random number generator, and there is no cap on how many of any one type of potion or egg you receive. This is not expected to change, and is consistent with all major RPG games to date (think of WoW). Even though you have no need for that particular drop, you will get it anyway since the drops are based on chance, not needs.

That said, feel free to peruse and chime in on this issue [https://github.com/lefnire/habitrpg/issues/1290#issuecomment-22198795] if you want. :)

**Comment by AdrienLemaire** [comment]
Sorry for creating this issue, it was a bit obvious... Maybe it would help for other people having issues with probabilities if some help text was available in an icon next to the inventory :P

Anyways, closing the issue

**Comment by AndreCaseyScott** [comment]
No worries. It's good to bring these things up. Obviously something needs to be done to make this clearer to folk. Not everyone comes from an RPG background :P

Maybe an entry in the FAQ/Wiki about distribution? Change the onboarding text when drops are activated? A little (?) Icon with a brief description that links to the FAQ?
