### ISSUE TITLE
I want My Profile Pic

### ISSUE THREAD

**Issue by MadeByBalaji** [HabitRPG/habitica#12919]
### Questions
I want my Habitica Profile Picture to be exported so I can use them.
I tried to open the image in a new tab but it doesn't work.
Please suggest a way other than ScreenShot

**Comment by thewilloftheshadow** [comment]
There used to be a way to do this, but it is currently broken and disabled (see #9489)

Also, in the future, there is a guild in Habitica for questions which you can find at [this link](https://habitica.com/groups/guild/5481ccf3-5d2d-48a9-a871-70a7380cee5a), and another for bugs that you can find at [this link](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac)

**Comment by MadeByBalaji** [comment]
Thanks @thewilloftheshadow  Sure I will look into it
