### ISSUE TITLE
The "Forum" link should be removed from the Tavern "Helpful Links"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12916]
The forum page (http://habitica.fandom.com/wiki/Special:Forum) no longer exists, and should be removed from the list of "Helpful Links":

![image](https://user-images.githubusercontent.com/8144640/103441961-aafd9080-4c49-11eb-8ab0-88c347357c44.png)

**Comment by shailenpatel1** [comment]
Can I work on this?

**Comment by paglias** [comment]
@shailenpatel1 looks like there's already an open Pr
