### ISSUE TITLE
/api/v3/cron POST route sets auth.timestamps.loggedin even when cron doesn't run

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12914]
~~This is suggestion-discussion for us to consider the code implications and whether we want to fix this.~~

If you have already cronned since your CDS time today and you run the `/api/v3/cron` POST route (e.g., with the command below), then the value for `auth.timestamps.loggedin` is updated (as is `lastCron` but that's no as much of an issue). The cron route doesn't make any other changes (which is as expected and as desired).

The `loggedin` value normally indicates the most recent time that a true cron ran, so the value is misleading when it's set by that route at a time when cron doesn't actually run.

@cTheDragons reported this and pointed out that it can lead to incorrect stats being reported by third-party tools. E.g., any tasks that were completed after today's real cron but before the new `loggedin` time may be displayed as if they were completed before a real cron.

sample command:
`curl -X POST -H "x-api-user: 12345678-3d8a-4a10-bfe0-123456789abc" -H "x-api-key: 12345678-3d8a-4a10-bfe0-123456789abc"  https://habitica.com/api/v3/cron`

**Comment by paglias** [comment]
The value for `loggedin` is updated because the user is updated to set the `lastCron` value used to avoid multiple crons at the same time. I don't think that it's a real issue to be honest and I also don't think we say anywhere that `loggedin` has the time of the last cron (which is saved in `user.lastCron`) but let's leave it open to see if anyone has a different opinion

**Comment by Alys** [comment]
`lastCron` is used to prevent multiple crons, but `loggedin` isn't used for that. It's just used on for display purposes in the website. I've copied below all the locations it's referenced.

It used to be set only at the end of cron and we still have comments in the code stating that it's the time of the most recent cron.

From what I can see, the code could be safely adjusted so that `loggedin` isn't changed unless cron actually runs.
 
 ```
 $ git grep loggedin

client/src/components/groups/membersModal.vue:427:          value: 'auth.timestamps.loggedin',

client/src/components/userMenu/profile.vue:792:      return moment(this.user.auth.timestamps.loggedin)

server/controllers/api-v3/members.js:92: *        "loggedin": "2017-03-05T12:30:54.545Z",

server/middlewares/cron.js:28:      'auth.timestamps.loggedin': now,

server/middlewares/cron.js:140:    // Set _cronSignature, lastCron and auth.timestamps.loggedin to signal end of cron

server/models/user/methods.js:438:        // NB: We don't change this.auth.timestamps.loggedin so that will still record
server/models/user/methods.js:439:        // the time that the previous cron actually ran.

server/models/user/schema.js:65:      loggedin: { $type: Date, default: Date.now },
```

**Comment by SabreCat** [comment]
Looking through, I agree with @Alys here--otherwise we have two fields recording the same data, making them overall less useful. We should only update `loggedin` the first time on a day the user crons.

**Comment by DarknessCatt** [comment]
Hello, may I work on this issue?
It would be my first issue for Habitica, but it doesn't seem too complicated. (And I was seeking seeking issues related to the API).

If I understood it correctly, we just want to avoid ```/api/v3/cron``` from updating ```loggedin``` date, right? Any tips on which files I would have to look at?

**Comment by SabreCat** [comment]
@DarknessCatt More that `loggedin` should only be updated at the end of the cron process, so that if there's some issue and the cron is aborted, we don't record that date as if it had. `/server/middlewares/cron.js` is what you'll want, I believe--it may be as simple as moving the `loggedin` update from line 28 down to the database update following line 140.

**Comment by SabreCat** [comment]
Anyway, yes, I'll set the ticket to in-progress so you can have a look!
