### ISSUE TITLE
Faulty Script

### ISSUE THREAD

**Issue by ubia61** [HabitRPG/habitica#1291]
Hey,

I don't know if this has been addressed yet. I'm running the latest version of Firefox on a Windows 7 machine. When I open the page I get the following error:

https://habitrpg.com/gen/SXyp22UIH2VwKO-5IDtXOw.js:4

Sometimes the tasks won't update. Sometimes Firefox freezes. Perhaps it's something on my end as well.

Thanks!

**Comment by lefnire** [comment]
Likely not something on your end, I'll revisit this after the site rewrite as that should change a lot of things

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
