### ISSUE TITLE
date on New Stuff by Bailey news posts varies based on time zone / locale

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12920]
@SnowCrasher and @beinginhisshadow and @citrusella all reported that the "2021 IS HERE!" / January Mystery Items Bailey was dated 31 December 2020.  @citrusella's time zone is UTC-5 and her screenshot is the first one below.

@SnowCrasher's post about this was in the Wizards of the Wiki guild since it was related to how the news is to be displayed on the wiki:
_"I'm confused. Today's news says 12/31/2020 but it was posted today, and the wiki is edited for today as well. Which is it?"_

When I look at the Bailey I see it dated 01/01/2021. My timezone is UTC+10 and my screenshot is the second one below.

_I'm marking this as suggestion-discussion for Habitica's staff to consider if / how this should be fixed._

![image](https://user-images.githubusercontent.com/1495809/103455306-b0390900-4d37-11eb-8d92-280fb97a9fe0.png)

![image](https://user-images.githubusercontent.com/1495809/103455313-bd55f800-4d37-11eb-9ec7-0bbefbc551a5.png)

**Comment by thewilloftheshadow** [comment]
Noting my (@beinginhisshadow) own time zone is UTC-6, and I have my language set to Pirate English (but I don't think that that language affects it)

**Comment by shailenpatel1** [comment]
Can I work on this?

**Comment by paglias** [comment]
@shailenpatel1 unfortunately only issues marked as `help wanted` are available to be worked on

**Comment by Alys** [comment]
Just posting to confirm that this is still happening. From the [Wizards of the Wiki](https://habitica.com/groups/guild/9a163b28-ebcf-4e52-87de-5c040ed0f8f8) guild:

@johnjsal:

> I just received the Bailey update today (1/26) but it's dated for 1/25. Just wanted to check if maybe I missed it yesterday, or if the date is wrong? Which date should be used when updating the [Whats New](https://habitica.fandom.com/wiki/Whats_New_2021) page? (Someone else can add the update if you'd like, I'm just asking to be sure.)

@jjgame83:

> the News is dated 26 for me.

**Comment by veeeeeee** [comment]
Staff proposes removing Date from the first part of title line, but adding additional line below the Title stating that Bailey news was posted at X time in Eastern United States time. 

Example: screenshot example should display as 
`2021 is Here! New Mystery Items and Official Habitica Challenges`
`Posted on Jan 1, 2021 8PM EST`

**Comment by SpeedyLom** [comment]
Can I work on this please?

**Comment by Alys** [comment]
@SpeedyLom Yes, thank you! Post here if you have questions.

**Comment by SpeedyLom** [comment]
I'm not going to be able to work on this for now due to personal circumstances, sorry about that.

**Comment by Alys** [comment]
@SpeedyLom No worries at all, we understand! Thanks so much for letting us know! I'm marking this as help wanted again. :)

**Comment by Helcostr** [comment]
I would like to work on this issue.

Is the request to remove the date stamp from the title?

**Comment by Alys** [comment]
Actually, I'm sorry, but I'm going to put this back on hold. It's a tolerable bug to put up with and we have a backlog of PRs to review. :( Thank you for offering though @Helcostr !

---

I've deleted some older comments that weren't specifically about the bug and the desired fix.

**Comment by Lyqst** [comment]
> Staff proposes removing Date from the first part of title line, but adding additional line below the Title stating that Bailey news was posted at X time in Eastern United States time.
> 
> Example: screenshot example should display as `2021 is Here! New Mystery Items and Official Habitica Challenges` `Posted on Jan 1, 2021 8PM EST`

Hi, I could implement this change.

**Comment by Alys** [comment]
@Lyqst Thanks! I've marked it as in progress for you. Post here if you have questions!

**Comment by Lyqst** [comment]
Hey, how can I get my local install to show the latest Bailey update (or a mock-up)? Right now, when I open the modal, it opens like this:

![image](https://user-images.githubusercontent.com/78376862/138762131-911b637f-268e-40be-a68f-850b80cad39e.png)

In the meantime, how does this look?

![image](https://user-images.githubusercontent.com/78376862/138761892-8b18ac5d-6312-493f-9739-b89481899dba.png)

**Comment by citrusella** [comment]
Technically there's an API command to create a new post: https://habitica.com/apidoc/#api-News

...But as I've never done it, I don't know what being *allowed* to post it entails (i.e. getting the local install account in question to have the NewsPoster permission, for instance).

**Comment by Lyqst** [comment]
Thanks @citrusella !

> I don't know what being allowed to post it entails 

I managed to give myself permission by manually modifying my test user in the database (as far as I'm aware, there's no API endpoint for this):

![image](https://user-images.githubusercontent.com/78376862/139933902-5502ad60-7f53-4c2d-85c3-34e7fa47cbf4.png)

Anyway, here's what I did:

![image](https://user-images.githubusercontent.com/78376862/139936314-ba79b2fa-6b3d-45cf-8d11-82a063759fbe.png)

The date and time is converted to EST, formatted using the user's preferred date format, and passed as two separate variables to localization:

```javascript
const publishDate = moment(post.publishDate)
        .utcOffset(-300)
        .format(this.user.preferences.dateFormat.toUpperCase());
const publishTime = moment(post.publishDate).utcOffset(-300).format('LT');
return this.$t('newStuffPostedOn', { publishDate, publishTime });
```
```json
"newStuffPostedOn": "Posted on <%= publishDate %>, <%= publishTime %> EST",
```

**Comment by citrusella** [comment]
> Staff proposes removing Date from the first part of title line, but adding additional line below the Title stating that Bailey news was posted at X time in Eastern United States time.

Oh darn even though this is an issue someone else is working on at this very moment, I wanna ask a clarifying question for this point because this doesn't specify daylight or standard time, does that mean it should always be EST (as it is in the code Lyqst is working on to my understanding)? Or does it matter when Eastern is in daylight time (especially as *all* of Eastern observes it AFAIK, hrmmmm)? (And then, does it matter that many people tend to use EST as "the time offset I'm at right now" (i.e. EST = EDT even if that means UTC -4 which is not what EST actually is) vs using it to mean "standard time" (i.e. EST ≠ EDT because they are different things, and it always means UTC -5)?)

(File this under "things on my mind because time is literally going to change back at the end of this week" XD)

**Comment by Lyqst** [comment]
@citrusella yeah, that's a good point. Actually, that wouldn't be too difficult to solve using [moment's timezone add-on](https://momentjs.com/timezone/).

From their front page:
```javascript
var jun = moment("2014-06-01T12:00:00Z");
var dec = moment("2014-12-01T12:00:00Z");

jun.tz('America/New_York').format('ha z');     // 8am EDT
dec.tz('America/New_York').format('ha z');     // 7am EST
```

**Comment by SabreCat** [comment]
@Lyqst Looking like good work! I agree that `.tz` could be a viable solution for the last comment. Could you go ahead and open a PR with your work so we can continue the review there?

**Comment by Lyqst** [comment]
Apologies for the huge delay on this @SabreCat , life has been a little chaotic lately. I just created the PR!
