### ISSUE TITLE
Died while staying in inn

### ISSUE THREAD

**Issue by jesscrees** [HabitRPG/habitica#1292]
Using Chrome Browser. User ID: d7fe6e42-053b-447d-b980-832f0cb16092

I clicked to rest in the inn while I was spending a couple of days away. Came back to find I'd died and lost a bunch of stuff. Please return my character to its previous status.

**Comment by lefnire** [comment]
Unfortunately the lost stuff would be due to No 1 of http://habitrpg.tumblr.com/post/55792029689/bug-workarounds , and isn't anywhere to be restored from. Follow No 4 to get your stats back to snuff, and if you lost eggs / potions I can give you gems to buy them back

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
