### ISSUE TITLE
Add 'questOwner' to the return data of a questActivity webhook (mainly questStarted)

### ISSUE THREAD

**Issue by PitiTheGrey** [HabitRPG/habitica#12931]
As a party leader I run a google sheet  to log questActivity via webhooks. (A google apps script web app deals as the webhook server and prints data output to a spredsheet).  
 
The data returned by the questActivity webhook contains information about type(eg 'questStarted'), group (id, name of party), quest (key: name of quest), webhook-type ('questActivity') and user (_id of the party leader).   

I belive there are quite some party leaders, who log questActiviy manually at this point of time. There could be automation to help them, but questOwner (UUID of party-member who invited the party for a quest) needs to be added to the webhooks return data. (Preferably to the group object?)
  
A GET request to https://habitica.com/api/v3/groups/party dispays the UUID of the member who started the quest under data/quest/leader. I would like to implement that data into the webhook response.

I already found out, that simply adding code to  
HabitRPG/website/server/modals/group.js is not sufficitent to do the job. 

9226cae6-d852-45da-a51b-ec2c9cb759e6

**Comment by Pyromonk** [comment]
I agree with @PitiTheGrey, there needs to be a transparent way to identify the person who initialised the quest, both via API and the site's UI.

**Comment by paglias** [comment]
I'm marking this as `suggestion-discussion` for the team to give it a look. But in the meantime as @PitiTheGrey mentioned you can make a call to `GET https://habitica.com/api/v3/groups/party` to see the details of the quest, so there's a way to get this info from the API

**Comment by PitiTheGrey** [comment]
There is some progress: I managed to edit HabitRPG/website/server/lib/webhook.js and added `questOwner: group.quest.leader` to the `quest` statement in line 184 giving me this result:  
`{"type":"questStarted","group":{"id":"1e53098d-642a-4042-8df5-5005cafb7903","name":"Tests Party"},"quest":{"key":"mayhemMistiflying1","questOwner":"9b2c3036-4f20-4f8b-aff3-f5ddaf8bc027"},"webhookType":"questActivity","user":{"_id":"ddfd634c-efbb-4315-bf4f-360cc671a778"}}`  
The ...webhook.js seems to contain the necessary information in the variable `group`. 
  
It seems more difficult to get the questLeaders proper name, since I belive that needs to await a promise resolve of the user data of the quest leader.

**Comment by paglias** [comment]
Yes for the leader name you'll have to make a query for the user profile or use a `populate` call that's already used elsewhere

**Comment by PitiTheGrey** [comment]
In my last comment I suggested putting the "questOwner" into `quest`-category of the JSON-response. Since the info about the questOwner comes from the `goup`-variable, I want to ask if it was better to put the questOwner into the `group`-section of the response. 
Secondly I want to ask if it better to stick to the naming that is already used and call display it this way:  
`{"type:":"questStarted","group":"{"id":"...","name":"Tests Party","leader":"uuid"...`
(using `leader` instead of `questOwner`).

**Comment by paglias** [comment]
I'd go for the `quest section`, note though that issues marked as `suggestion discussion` will have to be discussed internally by the team so they might have a different opinion on how to solve this one

**Comment by Pyromonk** [comment]
Not sure if I should create a separate issue for that, but 'questInvited' seems to not fire when you are the person inviting others, which is a big problem as well... But might be a problem with my code, I'll double-check.

**Comment by PitiTheGrey** [comment]
Would it help to make a pull request with my suggestion? So the staff can see more clearly what I would like to do?

**Comment by cvuorinen** [comment]
FYI @Pyromonk I made a separate issue for the `questInvited` webhook #13043

**Comment by Alys** [comment]
@PitiTheGrey If you'd still like to do a PR to show what you'd like to do, I think that would help!

I'm sure you already realise this but just in case it's not clear: Because this issue is suggestion-discussion, there's no guarantee that a fix ends up being desired for it, and your PR may not be accepted.
 
 However I think it's a great idea for showing what you'd like to do!

**Comment by PitiTheGrey** [comment]
Thank you, Alys! Above and beyond as always!  
https://github.com/HabitRPG/habitica/pull/13045

**Comment by PitiTheGrey** [comment]
Please excuse me. I am just curious if there is any progress here.

**Comment by PitiTheGrey** [comment]
Merged
