### ISSUE TITLE
Found item with no item present

### ISSUE THREAD

**Issue by trolderik** [HabitRPG/habitica#1295]
I have experienced two times where I get at pop-up, telling me I have found an item, but no item is presented, and no new things have been added to my inventory as well. 

Best Regards

**Comment by trolderik** [comment]
I understand that you will like additional details, I use a Firefox browser and will try to stay tuned if you got further questions :)

**Comment by trolderik** [comment]
And a user ID as well. 4351ea4b-6560-4ed5-8f23-98f32cc48a77

**Comment by lefnire** [comment]
dupe of https://github.com/lefnire/habitrpg/issues/1152, let's follow up there
