### ISSUE TITLE
"Create Challenge" button should not appear in groups where you can't create one 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12966]
When a Guild or Party has a ticked checkbox for "Only the Leader can create Challenges", currently all players see the "Create Challenge" button on it.

The desired behaviour is that only the leader sees that button.

I'm proposing this change because currently if a player clicks the button, they can get all the way through entering the challenge title, summary, and description without any warning that they are wasting their time. It's only when they click the "Add Challenge Tasks" button that they're told they can't create a challenge in that guild. If they've typed a lot of detail, that would be very disheartening.

~~I'm marking this as suggestion-discussion for the staff to decide if the proposed change is appropriate but if there's no objections in a couple of weeks I'll mark this as help wanted.~~

**Comment by veeeeeee** [comment]
Confirmed this is the correct approach, thank you @Alys!

**Comment by SpeedyLom** [comment]
Would I be able to work on this?

**Comment by Alys** [comment]
@SpeedyLom Yes, thank you! I've marked it as in progress for you.
