### ISSUE TITLE
"Show More" buttons appear in Stable even when there is nothing more to show

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12972]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The Stable includes "Show More" buttons meant to expand sections where some content is hidden. However, the buttons don't appear and hide intelligently--they show up, and you can click them to no effect, when there isn't anything more behind the fold.

From @atunpktfmweinawyqj (14e2b50b-c28c-4dac-977b-c664244f3543):

> Open Stable
> In left menu press selector "Hide Missing"
> Even if you don't have content in blocks, you will see "Show More" button."

**Comment by danikyl** [comment]
Hi guys,

I'd like to handle this one

**Comment by VGabriel45** [comment]
Can i handle this issue ?

**Comment by zerkshaban** [comment]
Can I handle this?

**Comment by Alys** [comment]
@danikyl I'm sorry we didn't reply sooner! Are you still interested in working on this?
If so, I'll assign it to you. If you're no longer interested, I'll pass it on to @VGabriel45

**Comment by Alys** [comment]
@VGabriel45 I've marked this as in progress for you. Post here if you have questions or run into trouble.

**Comment by shanaqui** [comment]
Hi @VGabriel45! Are you still working on this one? Just checking in to make sure issues don't go too stale! If we don't hear back within a week or you're not working on it anymore, I'll mark it as help wanted again. :)

**Comment by VGabriel45** [comment]
Hi, sorry I did not manage to make it work and forgot to tell you guys one week ago...

**Comment by shanaqui** [comment]
@VGabriel45 No worries, I've marked this issue as help wanted again. Thanks for having a go at it!

**Comment by Helcostr** [comment]
I can work on this.

**Comment by unmannaged** [comment]
Hi @Helcostr - How are you getting on with this issue?  

I've had a look at the problem and know what needs to be changed but haven't got a clue with the syntax.  If you want to put our heads together, then just give me a shout.

**Comment by Helcostr** [comment]
Sure, I haven't actually worked on the issue since I wasn't green lit. What code section are u looking at @mannkid?

**Comment by vanathi-g** [comment]
I'd like to work on this issue. I think I've figured out how to fix it!

**Comment by Alys** [comment]
@vanathi-g Thank you! Please go ahead!

**Comment by beffymaroo** [comment]
@vanathi-g Are you still working on this issue? Please let me know, and I can adjust labels if needed. Thank you!

**Comment by vanathi-g** [comment]
Hey @beffymaroo , sorry I was caught up with some other work! I'm still working on this issue though. I just have one clarification:
According to the description of the issue, the show more button should be hidden when there is no content at all in the block. However, should it also be hidden when there is no "more" content to show i.e. all the content fits in one/two rows without need for a "show more" button?

**Comment by beffymaroo** [comment]
@vanathi-g Thanks for replying! Your question may be a question for @Tressley (?)

**Comment by Tressley** [comment]
@vanathi-g -- Yeah, I think that's a great suggestion!

**Comment by SabreCat** [comment]
@vanathi-g Been a while since we've heard from you on this one--are you still planning to wrap this up? Let us know how you're doing!

**Comment by vanathi-g** [comment]
Hey @SabreCat ! Really sorry for the delay but I'm still working on it. May I have another week to work on it? I think I've almost figured it out.

**Comment by CuriousMagpie** [comment]
@vanathi-g Sure thing! Thanks for letting us know that you're still working on this!
