### ISSUE TITLE
Graph Data Is Not Displaying

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#130]
The graph data is not displaying only on the habits though and only on one of them.

**Comment by mfcovington** [comment]
Of the habits that have data available, only 5 of 12 will display the little graph. For the others, the habit text adjusts slightly (up or down) when I click the graph button, but nothing else happens.

**Comment by horusofoz** [comment]
@Neohuman @mfcovington
@lefnire advised [here](https://github.com/lefnire/habitrpg/issues/210#issuecomment-12703957);

> "...you have to have 2 items of progress (2 days passed, 2 +-
> clicks, and note: +only and -only don't get progress)..."

Can you confirm this explains your issue?

**Comment by ghost** [comment]
No I already checked that thanks

**Comment by horusofoz** [comment]
@Neohuman Can you confirm if the affected habits are "+" or "-" only?

**Comment by ghost** [comment]
It does indeed

**Comment by mfcovington** [comment]
For me, the only ones that are not working are the habits with both `+`/`-`, whereas `+`-only habits show the graph as expected (I don't have any `-`-only habits that have been clicked, yet). I changed habits from one to the other and they still kept the behavior from before the change (i.e., changing didn't fix the problem).

**Comment by horusofoz** [comment]
@Nehuman Appears your issue is by design. Progress was not originally implemented for "+" or "- " only habits. This is being considered for implementation [here](https://trello.com/c/YSXfecBt). Add your vote to help highlight the importance of the request.

**Comment by ghost** [comment]
Okay

**Comment by horusofoz** [comment]
@Neohuman I'm going to keep this open for a bit until we can get to the bottom of @mfcovington's issue.

@mfcovington The behaviour your experiencing is very unusual from my understanding of how things are supposed to work. Let's flesh it out a bit more.
- For the habits not displaying, are these more than 2 days old and you've recorded more than 2 instances of progress (e.g. + or - twice or more)?
- Lets try to recreate this. Is it possible to create a new habit with both "+" and "-" in it and give it some progress clicks over a couple days then on the 3rd/4th day check if the graph is showing?

**Comment by StanLindsey** [comment]
From above reference thread;
The progress chart is showing a day repeatedly, for all the Habits. See above:

![progress](https://f.cloud.github.com/assets/1236297/106600/d5b812ac-6a00-11e2-8a40-598fbc02fb4e.png)

**Comment by ghost** [comment]
They are the same demon

**Comment by mfcovington** [comment]
Previously, I wrote:

> For me, the only ones that are not working are the habits with both `+/-`, whereas `+`-only habits show the graph as expected (I don't have any `-`-only habits that have been clicked, yet). I changed habits from one to the other and they still kept the behavior from before the change (i.e., changing didn't fix the problem).

I hadn't had a chance to do any troubleshooting the last few day. As of today, however, I see the graphs properly for `+/-` habits and no longer see graphs for `+`-only habits. So, now behaving as intended?

**Comment by ghost** [comment]
Yes I believe so

**Comment by StanLindsey** [comment]
I'm not sure I can pinpoint a time where +/- habits didn't work. I do know that you have to click them twice for the graph to work. (I think its twice, lefnire posted somewhere that it needs a couple of points of data before the graph is created and displayed)

**Comment by horusofoz** [comment]
At this point do we have @NeoHuman's and @mfcovington's issues resolved?

**Comment by ghost** [comment]
Yes
