### ISSUE TITLE
Undo button does not undo getting a hatching potion

### ISSUE THREAD

**Issue by tonificante** [HabitRPG/habitica#1300]
I just got some exp points and automatically I got a message on the screen, but I clicked accidentally and then it dissapeared. Then I clicked on the "Undo" button at the top left, and then clicked again in the activity to get again the exp points and the message, and then I could read it. It was, I got a hatching potion.

But then, when I went through the menus till the inventory, I found I have 2 potions. I suppose, this is due to the undo functionality.

It is not urgent, but I just wanted to notice you about that. Thanks for the website, it is very helpful and nice.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Note that undo button is still not ported
