### ISSUE TITLE
Editing Tags

### ISSUE THREAD

**Issue by rtkleong10** [HabitRPG/habitica#1301]
When I try to edit a currently existing tag, I can only type one letter and then I have to click it again. However, this does not happen for new tags, it only happens when editing existing tags.

Browser: Chrome
User ID: 921407e7-20a5-49c9-802f-a63e4efd86e5

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
