### ISSUE TITLE
apidocs contain non-working Sample Request forms

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13012]
~~This issue is suggestion-discussion for staff to comment on which option(s) they'd like to see done. If there's no objections in a week, I'll mark it as help wanted for option 1, or if that's not possible option 2, with my idea being that the contributor who works on it would do the researched needed to work out if option 1 can be done.~~

**EDIT 2021-03-14: Option 2 has been done by @SpeedyLom.  I've set this back to suggestion-discussion. In future, we can look at doing one of the other options if the apidocs package is modified to make it easy to turn off the Sample Request forms or to make it easy to add API authentication fields.** 
 
EDIT 2021-02-07: I've marked this as "help wanted" for for option 1 to be done, or if that's not possible then option 2. The contributor who works on this would do the researched needed to work out if option 1 can be done. Please post a comment here if anyone has any questions about this issue!

---

Habitica's [apidocs](https://habitica.com/apidoc/) now have "Send a Sample Request" form under each route (example screenshot below). Almost all of them don't work because they don't contain fields for the User ID and API Token (and possibly for other reasons, such as other missing fields).
This means they're just unnecessary clutter, will be confusing and frustrating to any Comrades or Blacksmiths who try to use them, and will probably result in questions and bug reports that we'll need to handle.

This issue seems to have arisen due to an intentional change in the https://github.com/apidoc/apidoc/ library. With a quick search, I can't find anything in our own PRs that looks related. It's a great change for that library but our own docs aren't set up to take advantage of it.

There's multiple ways we could fix this:
1. Disable the sample forms, e.g., if the apidoc library gives an easy option for that. This is my favourite approach, at least initially to get a quick fix done to get rid of the non-working forms.
1. If option 1 can't be done quickly, then add a large obvious note to the top of the apidoc page to say that the form won't work. This is my second-favourite option at least initially. It may help to prevent some confusion/frustration/questions.
1. Find some way to add User ID and API Token fields to the top of the apidocs page so that they'll apply to all the forms on the page. E.g., the apidoc library may have a feature to easily enable this.
1. Add the User ID and API Token fields to all of the routes (except the very few that don't need them), so that each sample form works. This is my least favourite approach because it's extra clutter in the docs themselves - option 3 would be better if possible as a long-term solution.
1. Anything else?

Note that options 3 and 4 would also ideally require that we carefully check all the api documentation to ensure that all relevant fields are listed, and listed correctly. This is one of the reasons why I'm suggesting that option 1 be done now as a quick fix. Option 3 or 4 could then be done later.

_This issue is suggestion-discussion for staff to comment on which option(s) they'd like to see done. If there's no objections in a week, I'll mark it as help wanted for option 1, or if that's not possible option 2, with my idea being that the contributor who works on it would do the researched needed to work out if option 1 can be done._

I'll link this issue to the [Aspiring Comrades](https://habitica.com/groups/guild/2ff9822b-27f2-4774-98da-db349b57a38e) and [Aspiring Blacksmiths](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) guilds so that the current members know to not bother trying the forms, and I'll add a note to the wiki docs. 

Thanks to citrusella for noticing and reporting this! I've copied her post below.

![image](https://user-images.githubusercontent.com/1495809/106346191-efd81e00-6300-11eb-9c01-59326be7fa15.png)

---

@citrusella wrote:

"A bit of a weird one, but: the [API doc](https://habitica.com/apidoc) now has sample request forms underneath most of the doc options... but it looks like most of them don't actually work (namely the like 99% that require authentication... though weirdly one I thought requires it actually DOES work...), in the sense that they will return a NotAuthorized error.

"It seems as if the sample request forms came about via an update to the dependency that produces the API doc rather than something specifically done to get them to show up. I don't know enough about API requests *or* the way those forms work to know if there's any way to send an authentication header through them at present (or to allow them to send an authentication header themselves)... or if those were previously available in terms of what the thing that generates the doc offers but were somehow suppressed or something... or what. But I figured I'd bring it up because right now for most of them it's kind of a useless form taking up space beneath each entry?"

**Comment by Alys** [comment]
When this is fixed, we should remove references to the issue from these two wiki pages:
https://habitica.fandom.com/wiki/Application_Programming_Interface - two references
https://habitica.fandom.com/wiki/Webhooks - one reference

I'm labelling this as "notify helpers" to remind me.

EDIT: done

**Comment by SabreCat** [comment]
I'd set the proposed solution 3 as preferable to 2, but I agree with this plan!

**Comment by SpeedyLom** [comment]
Hey everyone, I'd be willing to look into this 🙂.

**Comment by Alys** [comment]
@SpeedyLom Thanks! Please go ahead and post here if you have questions.

**Comment by SpeedyLom** [comment]
The simplest option (_option 1_?) I can see would be to revert to `"apidoc": "^0.25.0"` based on:
- [#915](https://github.com/apidoc/apidoc/pull/915) being included in [apidoc 0.26.0](https://github.com/apidoc/apidoc/releases/tag/0.26.0)
- [@apiSampleRequest off not working](https://github.com/apidoc/apidoc/issues/947)

With the `sampleURL` not being provided by default, it won't include the samples in the generation of the docs.

**Comment by Alys** [comment]
@SpeedyLom Thanks for finding that information!

Unfortunately I think we can't really go back to an older release. There's no guarantee that they'll fix the bug in the upcoming releases but they may fix more critical bugs or security vulnerabilities if any become apparent, and if so, we'd want to upgrade to get those fixes.

So we need some workaround that lets us keep using their most recent release. If there's no other easy way to achieve option 1, and no easy way to do option 3, then it may just have to be option 2.

How do you feel about all that?

**Comment by SpeedyLom** [comment]
On further inspection, it looks like this is being addressed in [#930](https://github.com/apidoc/apidoc/pull/930). 

I can look into other options in the meantime if that is still required.

**Comment by Alys** [comment]
@SpeedyLom I guess if there's a chance they'll fix the bug reasonably soon, then there's not too much point in us doing a complex workaround. Probably option 2 is the best approach. If you'd like to add a message as described in that option, please do!

**Comment by Alys** [comment]
I've merged the fix that implements Option 2.

I've set this back to suggestion-discussion and we'll revisit it later. I've added this note to the top post:

**EDIT 2021-03-14: Option 2 has been done by @SpeedyLom.  I've set this back to suggestion-discussion. In future, we can look at doing one of the other options if the apidocs package is modified to make it easy to turn off the Sample Request forms or to make it easy to add API authentication fields.**

@SpeedyLom Thanks for the investigation and fix!

**Comment by citrusella** [comment]
It looks, from the apidoc thing's documentation, that header parameters could be included... but I think (with my rather basic but hopefully not incorrect understanding?) that'd be a number 4 scenario that would need to be added to each one? I may be misunderstanding, though: https://apidocjs.com/#param-api-header

**Comment by SpeedyLom** [comment]
Yes, that was my understanding as well. If the forms were going to be supported then the API definitions could be updated with header information individually.

I was unable to find a way to add the header information globally, which was a shame.

**Comment by olignyf** [comment]
I started having the sample request forms appearing in my apidoc output, now there is a "Send a Sample Request" at the bottom of each endpoint and `@apiSampleRequest off` doesn't seem to work. Also there seems to be no way to print apidoc version: `apidoc -v` would be nice or the `apidoc --help` to be printing the version number?
Currently I need to use this to check the globally installed apidoc version
```
$ npm list -g | grep apidoc
+-- apidoc@0.28.1
| +-- apidoc-core@0.15.0
```
What is the solution or apidoc version to revert to?

**Comment by Alys** [comment]
@olignyf Just to check, did you mean to post this to the Habitica repository (this repo), or to the apidocs repo? I'll respond to your post as if you mean to post it here to Habitica's repo, but bear in mind that the apidocs code comes from a library maintained by someone else. :)

> Also there seems to be no way to print apidoc version: apidoc -v would be nice or the apidoc --help to be printing the version number?

That would be something to submit to the maintainers of the apidoc library.

> I started having the sample request forms appearing in my apidoc output ... What is the solution or apidoc version to revert to?

If you meant to post here, I'm guessing you're referring to your local install of Habitica? I can't tell you which apidoc version you'd need to revert to because it's been a while since this issue was logged and I don't remember when the library was updated. The only solutions I can suggest are the ones written in the top post. Note that if you wanted to revert or write a solution purely for your own benefit, that would be fine of course (e.g., if you use a local install for local management of your tasks), but if you wanted to submit a pull request to help Habitica's code deal with the apidocs issue, post here first to describe what you have in mind and Habitica's staff will let you know if that sounds suitable (see also our wiki's [Using Your Local Install to Modify Habitica's Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API) page if you haven't already seen it, and the other pages it links to).

**Comment by funandgame** [comment]
> @olignyf Just to check, did you mean to post this to the Habitica repository (this repo), or to the apidocs repo?

Sorry wrong repo. Will repost at correct place.

**Comment by citrusella** [comment]
In theory, this was fixed in #13507 (I say "in theory" because it's not yet on the main website so that I could say it's certainly doing what it says and working and all, though it was tested and approved so I assume it works).

AFAICT the coding that PR did was the "option 1 fix".

**Comment by Alys** [comment]
@citrusella Good point, thank you!

I'll leave this open for now since the change isn't live yet - and especially since you reported a bug related to this in a test site! - but I've set this page to reappear in my browser in a week and then I'll close it if it's all sorted out.

**Comment by Alys** [comment]
The sample forms have now been removed from https://habitica.com/apidoc/ so I'm closing this (fixed with https://github.com/HabitRPG/habitica/pull/13507).
