### ISSUE TITLE
Restore Streak can re-award the Streaker achievement

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1302]
Windows 7, Chrome and Firefox.
- Score a Dailies streak in the usual fashion.
- Before you complete that Daily again, suffer some mishap that causes the streak to be lost.
- Use Restore Streak to put the streak (of 21, 42, or the like) back in place. You stack the Streaker achievement!

Restore Streak should probably skip the check for achievements, since by its intended use you'll have already earned the relevant achievement.

**Comment by gkatsev** [comment]
I've had a related problem where selecting a daily granted the achievement but the actual daily wasn't synced properly to the server so the next time I loaded the site up, that daily wasn't select. Re-selecting that daily gave me another achievement.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by SabreCat** [comment]
At the moment, Streak achievements aren't getting awarded at all. Will need to keep an eye on this when that piece is fixed.

**Comment by lefnire** [comment]
This isn't a ticket  well fix. Now that we're stable, and soon as streak
notify is back, well remove restore streak anyway since it was a feature to
patch memleak issues
