### ISSUE TITLE
Mystery Items missing for February for some players

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13022]
We saw many reports in various guilds that some players with active subscriptions had not received the Mystery Items for February.
The reports made in the Report a Bug guild were all verified and found to be correct.

The reason for the missing items is not currently known so I'm labeling this as needs investigation.

---

SabreCat ran a script to give the Items to all subscribers who were missing them, so the immediate problem should be fixed for everyone. **Anyone who was missing the Items should reload the website using their browser's refresh button or sync on the mobile app and then go to the Inventory > Items screen to look in the Mystery gift box.**

**Comment by SabreCat** [comment]
I believe I have corrected this with some updates to the cron logic for awarding mystery items. Closing for now--let's reopen if we get any further reports!
