### ISSUE TITLE
After creating or cloning a challenge, clicking "create challenge" pre-fills all fields with info from that challenge

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#13046]
Reproduced:

- Clone a challenge and save it, or create a new one and save it
- Click in a guild to create a new challenge
- Expected: empty form, what happens: form prefilled with details from previously created challenge
- If you refresh and do it again, it no longer prefills and you get the expected blank form

I *didn't* get this reproduced when I tried to create a new challenge from the main challenges page, but I'm still testing.

**Comment by benkelaar** [comment]
Apologies for not claiming etc.  Was just looking in to it and fix seemed quickly doable.  Seems to work well for me locally.

**Comment by Alys** [comment]
@benkelaar No worries, thanks for letting us know and for the PR! I've marked this as in progress.
