### ISSUE TITLE
over-purchase warning for Gryphon eggs should ignore RoyalPurple pet and mount

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13042]
In the Market, when you start to buy more Eggs than you need for a particular breed of Pet / Mount, you see this warning:

"This purchase would exceed the number of items you need to hatch all possible [pet_name] Egg pets. Are you sure?"
(locales string `purchasePetItemConfirm`)

That works correctly for most Egg types, but not for Gryphon Eggs. If you own the Royal Purple Special Gryphon Pet and/or Mount (which aren't hatchable), and you do need one or two Gryphon Eggs to complete your collection of hatchable Gryphons, you see that warning message when you try to buy the Eggs.

If you remove the Royal Purple Gryphons from your account, the warning message behaves correctly.

It looks like the code that works out whether you already have enough Pets/Mounts/Eggs for a particular breed is counting the Special Pets and Mounts for Gryphons. It should not be.

**Comment by majestic-owl448** [comment]
there is probably a new check to add, like it was added to avoid counting the Ghost Jack-O-Lanter for Ghost Magic hatching potions
```
        const ownedPets = reduce(this.user.items.pets, (sum, petValue, petKey) => {
          if (petKey.includes(this.item.key) && petValue > 0
            && !petKey.includes('JackOLantern') // Jack-O-Lantern has "Ghost" version
          ) return sum + 1;
          return sum;
        }, 0);
```

the idea that comes to mind is to just exclude the purple gryphons from this counting, or anything royal purple as those can be obtained through check-ins and not bought

can I try?

**Comment by Alys** [comment]
@ieahleen Please do, thank you! Post here if you have questions.

**Comment by majestic-owl448** [comment]
@Alys do you know if there is any plan to ever make royal purple potions purchasable? if there is not I can exclude royal purple pets and mounts, and it will still work in case of the release of any other royal purple pets and mounts. If there is the chance that royal purple potions may be sold I will target the fix to just royal purple gryphons.

**Comment by Alys** [comment]
@ieahleen I'm not aware of any plans to make Royal Purple potions purchasable. I like your idea to exclude all Royal Purple pets and mounts! I think it's worth doing that fix, thank you!


---

(This is not exactly related, but in case anyone is curious: If you have accidentally sold any of your Royal Purple potions, you can post to the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) to ask that they be given back to you. Even though that's not a bug, that guild is a good place to post because only an admin can give you back the potions.)
