### ISSUE TITLE
Site accesses every profile picture on startup

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1304]
Windows 7, Chrome and Firefox.

I see a plethora of warnings like these in the JavaScript console whenever I log in:

![screenclip](https://f.cloud.github.com/assets/4501321/905907/3f28c66c-fc5c-11e2-88c0-676228cf3a66.png)

This seems unnecessary/a bad idea...
- It slows down loading of the site.
- It could provide a route in for a DOS or malware attack.
- The likelihood of the user actually needing to view most of these images is very low.

Suggestion: Don't try to fetch these images until needed, i.e., when you actually pull up somebody's profile to look at it.

**Comment by AndreCaseyScott** [comment]
Thanks for pointing this out! This a known issue, and is part of the reason Habit takes so long to load before you can click anything meaningful (see https://github.com/lefnire/habitrpg/issues/840#issuecomment-20908741). Realistically, this will be a part of the angular rewrite to be released soon, or fixed shortly thereafter.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
