### ISSUE TITLE
'questInvited' webhook not sent when the user is the one who invites the quest

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#13043]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: fa756acf-9127-4a3c-8dac-8ff627d30073

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
The motivation for `questInvited` webhook #11682 was originally mainly more efficient auto-accept quests scripts, and for that purpose it's fine that it's not sent when user themself is the one who invites, as then they are automatically accepted. But people are actually using this webhook for other things also (myself included), e.g. posting notifications about the new quest to other chat services such as Discord or Telegram (see recent discussion in [Aspiring Comrades](https://habitica.com/groups/guild/2ff9822b-27f2-4774-98da-db349b57a38e) for example). So it would actually make sense to send this webhook even to the user who invites, so that it works for these kind of use cases.

I am the one who originally added this webhook in #11707 and I'm willing to make this change.

**Comment by cvuorinen** [comment]
I guess I could just make a PR for this, shouldn't be that big anyway...

**Comment by PitiTheGrey** [comment]
I would like to support cvuorinen's idea. Sending the webhook response to the person who invites to the quest would be useful for me, too.

**Comment by Pyromonk** [comment]
So this has been implemented, by the looks of it?
`code: 400; result: {"success":false,"error":"BadRequest","message":"You already accepted the quest invitation."}`

**Comment by cvuorinen** [comment]
Yes it has. PR was merged a month ago.

**Comment by Pyromonk** [comment]
> 
> 
> Yes it has. PR was merged a month ago.

Thank you, it appears I have been overlooking the error messages in my tool's logs all this time, my bad.
Would you happen to know if the data sent by a quest webhook contains information on the quest leader (the person who initiated the quest) now as well?

**Comment by cvuorinen** [comment]
@Pyromonk Seems it's not merged yet, but you can track the Issue #12931 or PR #13277
