### ISSUE TITLE
Audio demo button causes sound effects to be played at wrong times in Edge, Chrome, maybe other browsers

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13070]
As reported by @MrGaberson (eb9b83b8-749b-4536-95af-1641a6cf4967):

"... with the webapp version
Whenever I update any task: Be it dailies, habits, or to do, the sound effect plays whenever I update a task's or checklist item's name with every click and every letter I type on my keyboard"

"i tried refreshing. from what I experience when booting up the web app, it's been fairly silent for the first few moments before the sound effect bug happens."

"Update: It's silent until I tried pressing the SFX demo button in the settings"

"https://1drv.ms/v/s!AhB0AzACtjoTh1mRVseunoM3oxuB?e=ILQEKS
Here's a link of me trying to recreate the bug again with additional stuff I've noticed. Also correction in the vid: I mentioned I used Chrome, but it's clearly Microsoft Edge"

**Comment by Alys** [comment]
We've had a report of this from someone using Chrome:

Lavra / @reconcile (6b6411eb-34a2-4f56-b22f-10d2274c5a47) wrote:

"For some reason, whenever I press any keyboard buttons anywhere in habitica, I get the sound effect playing. That means every letter I'm typing in this message, every time I alt+tab out of any screen on the habitica website, I'm getting the [check-in sound?]. This just started a few days ago I believe. Hard-refreshing the page did not work, but resetting chrome seems to have paused the problem."

**Comment by shanaqui** [comment]
> @flockofteeth (ce7bf333-2fa0-4610-bef3-5bcd244a4a98): "Hi there! After I've ticked off tasks on my main tasks pages and the sounds have played for them, I'm finding that those sounds play then repeatedly when I type anything into the webpage, both entering the text for a new task and its even happened on a group, literally every keystroke it's like CLING CLANG DING CLING. I have discovered that refreshing the page fixes it so its not a massive issue but its a weird one and it can get a bit annoying, and it keeps happening! I'm on firefox."

**Comment by mars-schmutz** [comment]
Is this still a problem? I was trying to replicate it but I wasn't having any luck. I tried Chrome and Firefox, but I haven't been able to try on Edge yet.

**Comment by anishlukk123** [comment]
@SabreCat  is this issue still relavant? if it is  I would like to work  on it

**Comment by Tressley** [comment]
Closing as this doesn't seem to be an issue that can be easily replicated. If we see reports on this again, we'll create a new issue.
