### ISSUE TITLE
Change of difficulty names to represent a monster instead

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1308]
This could be something like
Mob (normal)
Elite (medium)
Boss (hard)

Thus it feels more like you're killing things when you complete your task :)

The name suggestions might not be the best, I'm sure the community can come up with some better names :)

EDIT: I meant difficulty and not priority.

**Comment by AndreCaseyScott** [comment]
This is an interesting idea. I personally name all my Habits and Dailies with RPG style names, thus it would be fitting for the difficulty to be more RPG-like. 'Boss' specifically might be problematic, as there are pending features which would make certain tasks a 'Boss' battle and would reward you extra for completion. 

Two (silly) things that popped into my head: 1) make the text customizable by the user, so they can use whatever term they want for the difficulty, if they don't like the default. and 2) after a difficulty is set, have an icon or something next to the item to visually indicate the difficulty. Im imagining little pixel goblins and demons, but could be something more subtle. 

hmmm....

**Comment by Senth** [comment]
I like both your ideas, especially the icons, never thought of that :)
You could keep both names actually.
[icon] Goblin (normal)
[icon] Cyclops (medium)
[icon] Dragon (hard)
then as you say display the icon beside the item :)

**Comment by SabreCat** [comment]
I think there are plans for monster encounters at some point, which this could get muddy with. I could totally see renaming the difficulties to something more RPG-evocative, though! Ideas:

Common / Heroic / Epic
Worthy / Perilous / Deadly
Tricky / Vexing / Arcane

I don't want the base difficulty to sound too puny, since we want people to use it most of the time. "Easy" and "Medium" are a little problematic on that count already, I feel.

**Comment by lefnire** [comment]
Check out https://trello.com/c/4C8w1z5h/17-priority-multiplier . This difficulty thing has been discussed at great length, as well as a few polls voted on. @wc8 drove that original convo, you may wanna jump in there with your $.02 - but I'm pretty much taking the backseat on this conversation

**Comment by wc8** [comment]
@SabreCat Difficulty values: **easy x0.5, normal x1, hard x2** won the poll 
Thus, brush teeth can be 1/2 as hard as a normal task, and 1/4 value of a hard task. 
These differ from Priority values: x1 (normal), x1.5, x2

Overall I like the idea. 
To make it clearer: on mouseover show _easy_, _normal_, _hard_, respectively.

**Comment by DraguMaki** [comment]
Hey, how about Easy - wooden/bronze sword, Medium - Silver sword, Hard - Gold sword?

PS: Hello. :P

**Comment by ivyxaur** [comment]
We could also go to D&D tiers

Easy - Hero
Medium - Paragon
Hard - Epic

(Also yeah mouseover of Easy Medium Hard / including it in the tutorial would help!)

**Comment by deilann** [comment]
This is being discussed on Trello, as Tyler pointed out.
