### ISSUE TITLE
(Meta) bonus exp & gold

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1309]
The idea is to spur the player completing even more tasks, or in a certain order, or by some other means.

**Two examples**
1. If the player completed all tasks in a day/week/month (i.e. didn't get hit) s/he would get bonus exp and gold for accomplishing this.
2. Complete boss tasks first. The reason for this is that you should start your day by doing the hardest task at hand as this increases productivity. Paraphrase from the book "Eat that frog" by Brian Tracy. This does not mean the player needs to complete all tasks that day, but as long as all the hard tasks were finished before any medium; where all medium tasks needs to be finished before any normal.

**Possible Problems**
1. Habits can't really be a part of the bonus. Is this a problem or not?
2. Some hard tasks cannot be done early in the day. For example if I have a daily task of running in the morning (should this be a daily task or habit? I think the two are more less the same in meaning). In the beginning this might be a hard task, but after 3 months this might be easy. Because this task should be done in the morning it will probably always finish first, i.e. the player can never get the bonus. A solution might be to have an option 'time specific' on daily tasks, these will not be used when checking if the tasks were completed in the correct order.

**Comment by wc8** [comment]
> If the player completed all tasks in a day/week/month (i.e. didn't get hit) s/he would get bonus exp and gold for accomplishing this.

See [Perfect Day Bonus](https://trello.com/c/an2xJ1lX)

> Complete boss tasks first. The reason for this is that you should start your day by doing the hardest task at hand as this increases productivity. Paraphrase from the book "Eat that frog" by Brian Tracy. This does not mean the player needs to complete all tasks that day, but as long as all the hard tasks were finished before any medium; where all medium tasks needs to be finished before any normal.
> Some hard tasks cannot be done early in the day. For example if I have a daily task of running in the morning (should this be a daily task or habit? I think the two are more less the same in meaning). In the beginning this might be a hard task, but after 3 months this might be easy. Because this task should be done in the morning it will probably always finish first, i.e. the player can never get the bonus. A solution might be to have an option 'time specific' on daily tasks, these will not be used when checking if the tasks were completed in the correct order.

See [Ate Frog Bonus](https://trello.com/c/yJlBTla3) based on this ticket. Vote for it. (Or let us know there in the comments if the description missed something.)
