### ISSUE TITLE
[Feature Request] Daily Roll-Over.

### ISSUE THREAD

**Issue by timothyCoxon** [HabitRPG/habitica#131]
Yet another feature request ;)
Daily Roll-Over: Basically a setting that would mean that if you didn't do a daily task on that day it would Roll-Over to the next day and potentially let you do that task twice.
For example. I am freelance and for one client I have a max number of hours per month. So I divide that total up and it leaves me with 2hrs per day everyday except for Sunday. Some days I will not do any work and the next day do 4hrs to make up for it.

**Comment by theogeer** [comment]
I think this would make more sense as a habit than a task. 

Maybe the feature is really to add counter and time-frame limiter on a habit. So you create a habit for your client that says 

Work on Client X for 1 hour;
Limit: 50;
Period: Month;
PeriodType: Boxed; (Boxed means you get 50 for each calendar month. Rolling could mean you get 50 in the last 30 days)

**Comment by timothyCoxon** [comment]
Good point. I guess with a set limit like that you could get a load done earlier. So do 3-4 days worth of work on one day then take the next few days off.
Although you could make it so that when you check off the daily task it would generate a new empty check box, then when the day moves to the next you just remove the first checked off check box from the list.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Would [Expected Habit Frequency](https://trello.com/c/cwQvDQI9) address this?
Or perhaps [Completion Quotas](https://trello.com/c/E5CVJlW6)?
