### ISSUE TITLE
Various help actions for completing tasks

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1310]
Just a vague idea, but I will still share it :)

The idea is probably more suited in a family, or a business.

**Ask for help**
If your stuck on a task, or don't want to do it you could ask a friend for help. This could give you some exp, but not gold. It will probably cost you gold instead.

**Delegate task**
Some of the less productive tasks you have might be worth delegating. This allows you to be more productive. This works best if the person you delegate it to also has an account, you could then send it to that person, where s/he needs to accept it. While the other person get full exp and gold for the task, you could get 10% of the value too. Hopefully this will incentive people to delegate tasks as they too benefit from it.

Another incentive might be to get some exp (but no gold) when just delegating the task. It is easier for the brain to make connections that delegating task = exp = good.

If the other person doesn't use HRPG, you could get 10% of the task directly. I had an idea of keeping the task in a seperate delegated tasks and then you could complete it manually. I'm a bit torn if that's good or bad. Good: You can directly see the tasks you delegated and ask if the have been done. Bad: The task is not out of your head, meaning you still have to think about it.

**Comment by AndreCaseyScott** [comment]
This feels a bit off base from what HabitRPG is intended for. The way I see it, HabitRPG is not a Task Management system (where delegation can be handy) but a habit builder/life hacking app. It is intended for **you** to do the task for your own good. Having friends encourage you is useful, but just offloading the task defeats the purpose of HabitRPG, IMHO.

**Comment by Senth** [comment]
Yes, now that I think of it, it is. Better to skip this feature :)
