### ISSUE TITLE
Rewards for leveling

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1311]
In addition to regular rewards, one could be able to set leveling rewards.

**Why not use the same reward system?**
For example the regular reward system might work good for smaller stuff, such as cake or game of thrones. But what if you have a bigger reward, such as travel to X which costs 10000 gold. I see three options here.
1. The player saves 90%-100% of the gold to the big reward. I'd argue the smaller rewards is important too. You should try to have fun often, not just once every year.
2. The player uses 100% of their gold on smaller rewards. The big reward seems way too far away to bother getting it.
3. The player saves 10-50% of the gold to the bigger rewards. This seems like a good option, but how do we actually get player to do this and not the other ways?
   In addition, a big reward is not scheduled. So you could have several big rewards, then you don't know which one you want to choose from...

**Level reward system**
Allows you to set rewards for either each level, or some specific levels like 10,20,30...
This gives the player a clear reward to focus on. S/he can easily see the progress towards that goal as it never goes backwards (unless you die).

**Comment by SabreCat** [comment]
I've been thinking about these things too--I threw a couple of 500-gold rewards onto my list a few weeks ago, and I'm no closer to getting them now than I was then, thanks to spending on lesser rewards! It would be interesting to have a way to pay in toward a large reward: I build up 50 coins, decide to bank it toward the 500-gold reward; now it's a 450-gold reward and I have no coins.

You can do this by hand with a little work, and I may very well do that myself, but a convenient UI for it would be sweet.

**Comment by wc8** [comment]
Have you seen: [Gold Pots for Saving](https://trello.com/c/s7qi0EMU)? 
I'll note the idea there for a percent-based division of gold. EDIT: percentage is a mentioned option.
