### ISSUE TITLE
Sudden "rollback" on first load of day, with large XP and gold loss

### ISSUE THREAD

**Issue by CountPacula** [HabitRPG/habitica#1313]
User ID: d29d5a61-a642-411c-86fb-f00a49516b44
Browser: Chrome Version 28.0.1500.71 m, running on Win7 Pro x64

I logged in for the first time today a few minutes ago, and instead of the usual single report of HP loss from undone dailies, I was greeted with a sudden flood of reports, each noting a -loss- of both XP and gold. The amounts in each report were about the same as the gains I normally get with my dailies, as if the credit I had previously received was now suddenly being rescinded. I'm not certain, but I think the total loss was about ~150 XP and a couple dozen GP in all.

This is actually the second time this has happened to me - a near-identical incident occurred a couple weeks ago, nearly killing me. :(

**Comment by CountPacula** [comment]
Just happened to me again this morning, this time with my XP dropping from 54 down to -negative- 83.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
