### ISSUE TITLE
Disappearing Habits/Dailies and HP Loss

### ISSUE THREAD

**Issue by b4silio** [HabitRPG/habitica#1315]
I've seen a number of similar issues but since they've all been closed a number of months ago I guess I'll open one again.

I lost a large portion of my habits/dailies/todos randomly when I put my char in the Inn. (happened one week ago). At least the dailies seem to still exist to some extent (but not being displayed) because I'm loosing HP every day despite completing all my currently re-written dailies. It has been this way for the past week or so, so I guess it's not a simple "offline - reload" problem.

I can rewrite my habits and dailies (i've re-done them mostly) but i would rather not have my character die out. Can I do something from my end to erase for sure all tasks and start over filling them in without losing my character? (and my pets!!)

Thanks!

**Comment by lefnire** [comment]
Do you have any active filters?

**Comment by b4silio** [comment]
OMG yes

I apologize for my stupidity….

Thanks!

**Comment by lefnire** [comment]
np, it's a common issue. on my agenda to make things more obvious
