### ISSUE TITLE
Estimated time -> another multiplier on tasks

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1316]
Before I begin talking about a solution I'll give you some examples of my problems.

I generally want to create tasks for everything I do, be it habits, dailies, or todo. But I often find them very unbalanced. For example if I use Anki I get almost 1 gold for each task card I complete, roughly this is 20 gold in 10 minutes. Other times it's the other way around I have a 10h programming task that I get 2 gold for. I think you can see the problem.

I have two possible solutions for this
1. You can let an app through the API decide on the amount of exp and gold. This would allow anki to set the value to 1-5 silver which is more appropriate and 1 exp at max. Depending on how you have implemented the system it can be hard to implement. Let's say to give a player exp or gold you have to have a task for it. But there is always a way to change that or to create a hack (a ghost habit).
2. You introduce a 3rd option in addition to priority/difficulty (and maybe even urgency). And that is the estimated length of the task. This ways I can by myself set Anki with a time to 1 minute, whereas I can set my large programming tasks to 10h or 2h or something else. This will also allow you to have ultimate control over how much experience and gold the player get, thus it's easier to balance because only you have to balance it and not everyone that makes an app. In addition you will be able to create todo-tasks inside the webapp.

If you don't want the player to be able to set a free amount of time for the task you could quite easily group tasks into these categories
1-5 minutes
5-15 minutes
15-30 minutes
30-60 minutes
1-2 hours
2-5 hours
5-10 hours
10h+
The simplest way to implement would be to let the player add freely (in hours, e.g. 0.5 for 30 minutes; or add hours 10 minutes more coding but more clutter). Then just use the amount of hours as a multiplier. For example 15 minutes = 0.25h = 0.25x multiplier, or 2h = 2x multiplier.

EDIT: Forgot to mention, but it could be a good idea to maybe hide these settings from default users and either introduce them later inside the game, or that the user can force to see all settings directly.

This will allow not-so-advanced users to not feel overwhelmed by the options and will allow perfectionists like me customize the settings :)

**Comment by wc8** [comment]
Have you seen: [Timed Tasks/Alarms](https://trello.com/c/FwSlQrR5)? 
I added a link to this ticket. 
Current plan for Priority and Difficulty multipliers is here: https://trello.com/c/4C8w1z5h
As noted there, Urgency might be handled by Due Date and/or Start Date.
