### ISSUE TITLE
Skill ("spell") to buff the party (Rogue)

### ISSUE THREAD

**Issue by gocoelho** [HabitRPG/habitica#13166]
### General Info
  * UUID: 68209916-0a5b-487c-a4e8-46583244b472
  * Browser: Microsoft Edge
  * OS: Windows 10

### Description
I'm in a party and when I use a spell to buff the party, Habitica don't show the message, like it happens when another member used a spell :(
both case, I (gocoelho) use this:
![image](https://user-images.githubusercontent.com/7503127/114323845-7da06880-9afd-11eb-8ca6-f93a129e7bb0.png)

And the message wasn't there (Only when Mione use Spell):
![image](https://user-images.githubusercontent.com/7503127/114323782-3fa34480-9afd-11eb-809b-adc24de8d563.png)

**Comment by Nakonana** [comment]
"Furtividade" (or: "Stealth") is not a party buff skill and thus does not appear in the party chat to my knowledge. It is applied to your own tasks and prevents the party from taking damage if you don't complete your tasks. 

If you want to buff your party, try the skill next to Furtividade, the one for 25 Mana ("Tools of Trade"), and check if a message in the party chat appears or not. Tools of Trade should increase the PERception stats of your party :) 

These links could help: https://habitica.fandom.com/pt-br/wiki/Gatuno#Furtividade and https://habitica.fandom.com/pt-br/wiki/Gatuno#Ferramentas_do_Of.C3.ADcio

**Comment by Alys** [comment]
@gocoelho If you find anything else that you think is a bug, please post to the Report a Bug guild (from the Help menu on the website or from the Guilds section of the website or app). As the new issue template here says:
> Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.

So it's usually easier for you to post to the guild and easier for us too. :)

@Nakonana Thank you!
