### ISSUE TITLE
Changes not saved, caused death

### ISSUE THREAD

**Issue by jreatherford** [HabitRPG/habitica#1317]
Hello.

I recently was near death and when I updated yesterday, I checked off all my dailies and deleted one (it was no longer applicable).

When I logged in today, I was dead and that dailie was back.  My changes from yesterday had not stuck.

I was running chrome and my id is (ba9fc2d8-5bde-491d-b27a-0d7d9f9cd0a2)

Is there any way to roll back my account?  I really don't want to lose my gold.

Thanks for any help.  Love the site.

-James

**Comment by AndreCaseyScott** [comment]
Issue caused by Derby backbend. See #840 and #841 for more info.

Under your account settings there is a red Restore button. You can use that to reset your gold, exp, armor, etc that was lost to the bug. 

Keep on trucking :P

**Comment by jreatherford** [comment]
Awesome.  Thank you very much.
