### ISSUE TITLE
Red Sword Experience Gain Bug

### ISSUE THREAD

**Issue by daplho** [HabitRPG/habitica#1319]
Hello Developers,

The red sword is showing a 12% increase in experience gain in its tooltip. I believe that should be 15% as weapons have progressed in 3% increments so far. Not sure if this is just a tooltip bug or if it actually affects experience gain as well.

Cheers,

Niko

**Comment by SabreCat** [comment]
Did you only just purchase the Blue Sword? See issue #1020.

**Comment by daplho** [comment]
Thank you SabreCat.
