### ISSUE TITLE
Print Option

### ISSUE THREAD

**Issue by FaeriMagic** [HabitRPG/habitica#132]
I think a print option would be really useful for users who cannot access the mobile version. True, there's the print option built into the browser, but everything might not fit into one page (the ideal amount). And there may be certain things that you'd want to exclude.

Maybe perhaps a simplified version of HabitRPG where users can check off what they want to print? :/

My thinking is like this: If a user couldn't access it the mobile version, they can print it out, go to school/work where they can discreetly check off accomplished goals, go home and then input it in hRPG.

**Comment by wc8** [comment]
Possible Temporary Workaround: Take a screenshot and print it. 
Depending on how small you can handle the font size vs. how many tasks you have, you could zoom out to make sure the image shows all tasks.

**Comment by hookang** [comment]
Interesting idea - Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Print options included here: https://trello.com/c/29qEE1DF

**Comment by rajlego** [comment]
Was this ever implemented? If it has been, I don't see a way to do so
