### ISSUE TITLE
Lost Username

### ISSUE THREAD

**Issue by BrianTheMayor** [HabitRPG/habitica#1320]
HabitRPG seems to have ceased recognizing my username for the log in process. I was still able to reset my password, and my username was included in the email I received. However, the log in function does not recognize my username.

**Comment by kevinalai** [comment]
My username has also stopped being recognized at the main site and the beta site as of this evening.

**Comment by lefnire** [comment]
Is this still the case for both of you? Sometimes when the site is rebooting due to the memleak #165, people get the "uname doesn't exists" bit

**Comment by lefnire** [comment]
if it's still the case, could you provide me with your user ids if you have them handy? (long string of letters)

**Comment by kevinalai** [comment]
This issue has still persisted. Moreover, it says my email is not registered.

Unfortunately, I don't have my user id. My username was kal2000, and I was in the same party as a user with this ID: a3154932-d543-44c1-8659-d0343bc49b3e

However, on my friend's screen (same party), it just shows me as "Anonymous" and Level 1, with no head also.

**Comment by lefnire** [comment]
are you Alex Chen? That user id provided is registered as facebook authentication, so if that's you try logging in with the facebook button. If i's not you, check out https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found and see if you can provide me with a specific task i can search you by.

**Comment by kevinalai** [comment]
I'm not Alex Chen--that's someone else who is in my party (wasn't sure if you could find me based on party). I'll send you an email.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
