### ISSUE TITLE
Please add a setting to disable notifications/popups from Bailey

### ISSUE THREAD

**Issue by vexx32** [HabitRPG/habitica#13220]
I get that Bailey notifications exists for a reason, but there being no way to ignore / mute / disable the literally constant updates from Bailey is a huge deterrent to even using Habitica on my computer. 

There's always so much to read through, it's like a short story every single day that I have to click through in order to just check off my tasks. It mightn't sound like a lot, but some days it's the difference between me actually updating my tasks / Todo / dailies and giving up to focus my limited energy elsewhere.

Frankly, I don't really care about 99.999% of the Bailey notifications, I don't really care about the events or anything for the most part. I certainly don't need _daily_ reminders about the same things ad nauseum. I don't have the energy to process all of that information over and over. 

It's much less irritating in the android app, where the notif is there if you want it, but not an obnoxious popup that I have to click through every single day.

Please make it stop.

**Comment by SabreCat** [comment]
As this isn't a bug, strictly speaking--and bug reports go through the Guild in any case--I'm closing this ticket for now. This would be good to send to the team via the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link) instead!
