### ISSUE TITLE
Time-limited quests show the timer in the inventory as well

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#13224]
As Fox_town reported in Report a Bug:

"The seasonal quests (e.g. Waffling with the Fool) have an expiration timer on the hover-over, in the inventory. (It's the same hover-over as when the quest is in the shop.) This is misleading and has unduly led some players to think the scroll will vanish from their inventory if they do not use it by tomorrow. Especially as these are gem purchases, I think we should remove that alarm from the purchased version of the scrolls."

Remeday adds:

"In addition to what Foxtown said, the Find the Cub and Trapper Santa quest scrolls are showing in my inventory the same way, though they're not currently available in the Market at all. That seems even more confusing, since there's not even a "Oh, that just means available for purchase" explanation."

**Comment by veeeeeee** [comment]
Confirmed there should be an exception to hide the expiration timer when quest is in inventory.

**Comment by lizapritchard** [comment]
Can I tackle this one?

**Comment by Alys** [comment]
@lizapritchard I'll actually leave this one still marked as help wanted for now, while you work on the other couple of issues you have. Since this one is "good first issue" it would be great for someone completely new to Habitica's code. However if no one else has taken this one by the time you've finished the others, post here again if you're still interested in this one. :)

**Comment by Walker80529** [comment]
can me do?

**Comment by Alys** [comment]
@Walker80529 Since you're new to Habitica's code, see how you go with the "Orb of Rebirth should unpin Antidotes" issue and once you have a Pull Request submitted for that, if this issue is still available and you're still interested in it, post again here.

**Comment by prii-yanka** [comment]
I'm new to Habitica's code and would love to try and tackle this issue

**Comment by Alys** [comment]
@Priyanka72 Thanks! Please go ahead and post here if you have questions.

**Comment by shanaqui** [comment]
@Priyanka72 Hi there! Are you still working on this one? If not, or if you don't reply within a week, we're going to mark this as "help wanted" again to make sure people know it's available to work on. Thanks!

**Comment by Walker80529** [comment]
Oh, sorry. Yeah, I stopped. I’m moving to Utah right now, so maybe choose someone else.

-George Busby

**Comment by shanaqui** [comment]
@Walker80529 That's alright, @Priyanka72 is the person assigned to work on this at the moment. :)

**Comment by Lyqst** [comment]
Hi, I would like to work on this as my first issue

**Comment by SabreCat** [comment]
@Lyqst OK, go ahead! Speak up here or in the Aspiring Blacksmiths Guild if you need help with anything.
