### ISSUE TITLE
Purcharsed item not showing after unequip/equip

### ISSUE THREAD

**Issue by pierrepicaud** [HabitRPG/habitica#13248]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: @dlieu
  * Browser:
  * OS: Android

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Nakonana** [comment]
Any chance that you have the costume option enabled...? Avatars have two different outfits, one for battle and one for looks. You can equip items to both things at the same time but only one of them will be visible. You equipped your items to the battle option, but if you activate costumes you can't see your battle equipment.

See here: https://habitica.fandom.com/wiki/Equipment#Costumes

**Comment by shanaqui** [comment]
Nakonana's explanation is most likely correct, so I'm closing this issue. If you're having further problems, @pierrepicaud, please report in the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild so we can troubleshoot there. :)
