### ISSUE TITLE
wrong challenges shown for guild when accessing through notifications

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13256]
_As reported by @citrusella:_

"If I visit a guild and then visit other guilds through notifications (or any method that does not involve a reload or visiting a non-guild page, i.e. using the back button to go to a guild you were previously at), the guild keeps the same challenges in the sidebar even as all the other aspects of the guild update to the new guild. 

"I didn't see any errors in the console or anything (or at least not related ones--i.e. I saw some errors for, like, broken emoji and stuff, and a lot of successful loading)."

Anyone who works on this issue should make sure that the fix also applies to parties.

**Comment by Alys** [comment]
Anyone who works on this issue should make sure that the fix also applies to parties.

**Comment by lizapritchard** [comment]
Can I work on this one?

**Comment by Alys** [comment]
@lizapritchard Thank you, please go ahead! Post here if you have questions. Out of the three issues you've asked to work on, this one is the most important.

**Comment by Alys** [comment]
I'm reopening this because the bug is still happening or has started happening again. I've checked the current code and the fix in the linked PR is still in place, so it looks like a different method of fixing it will be needed now.

**Comment by antonderegt** [comment]
Hi there, could I have a go at this one?

**Comment by antonderegt** [comment]
Or should this issue be closed? I saw someone else already submitted a PR in issue #13891

**Comment by CuriousMagpie** [comment]
Good catch, I've linked that issue here as well. Once the PR is reviewed and put into production, this issue will be closed as well.
