### ISSUE TITLE
@mentions dropdown should not stay visible after selecting from it

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13254]
As reported by @citrusella and replicated by me (Ubuntu Firefox):

> a bug [I saw] while adding SabreCat's name to the middle of the post I posted prior to this:
> 
> The newly added/fixed ability (https://github.com/HabitRPG/habitica/pull/13180 by helcostr and benkelaar) to go back into the middle of the text and get an autocomplete if you add a mention there is great!
> But if you hit enter on that mention to select from the dropdown (which properly adds the relevant name and a space), it stays visible until the next time you hit space (or enter, or backspace) *after* that.
> 
> It also becomes uninteract-able by keyboard (i.e. using the arrow keys doesn't select a dropdown option but instead moves you around the text box like it would if you were just typing (and the dropdown follows your cursor around), enter also doesn't select an option but adds a new line like it would if you were typing (and dismisses the dropdown)), and further letter typing doesn't cause the dropdown to autocomplete again or anything. But you can still click names that are visible and they will be added, just without an @ in front, as follows: @citrusella citrusella citrusella citrusella citrusella citrusella  (This text typed *before* the preceding mentions.) Clicking does not cause the dropdown to disappear; all those extra citrusellas are from me clicking the dropdown multiple times. XD
> 
> It also seems to not happen if there's a space at the end of the text in the text box, which I discovered while I was trying to enter examples for reporting. :P

**Comment by Helcostr** [comment]
That's interesting... I thought it disabled the the dropdown on an enter select :O

Welp, time to fix my mistake.

(seems to be an issue with just FF, this is so weird)

(oh yeah, i'm dumb and somehow didn't reset the autocomplete menu since I use a different method... suprised this didnt show up in chrome for some reason).
