### ISSUE TITLE
Server side update health/uncheck dailies

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1325]
I would propose updating health/uncheck dailies as a hourly cron-job for the server. Why?

I'm not sure how you handle multiple days when a player doesn't log in. For example the player doesn't log in for 4 days, the client needs to have all the logic and update it. Reduce health, etc.

Before this would actually be fine, as there only was one client and the client would handle all processing power, not the server. But now you are working on an Android client, and people might actually implement other unofficial clients which then won't be able to handle the logic, meaning if they want them to function correctly they have to first login to the web client every day.

Pros
- If you change update functionality, implement new features requiring updates you only need to change it in one place. This means less code, less bugs.
- Inofficial clients works correctly and doesn't need to either implement this functionality (which would break the client once new features/changes are made) or where the player needs to login to the web-client first.
  
  Cons
  - You need to move the code to the server. As you already have the update functionality this shouldn't be too hard.
  - Server might be bogged every hour when updating health/uncheck dailies. The server probably has multiple cores, thus only utilizing one core doesn't slow down the server as much as would 10 000 client requests probably would do? (not sure).
  
  I.e this approach will be more work now, much less work later.

**Comment by wizonesolutions** [comment]
@Senth AFAIK this is already in the works, just being debugged, and that actually the server is already where cron is run. It's just that it only happens in the web client.

See https://github.com/HabitRPG/habitrpg-shared

**Comment by lefnire** [comment]
This is complete

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
