### ISSUE TITLE
Use word boundaries when parsing @mentions on server

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13250]
### Description

Currently, if a user neglects to put a space between two @-mentions of users, the server will still evaluate both of those @-prefixed strings and send mention notifications to both users if they're valid. While this sounds intuitive, it is inconsistent with established UI conventions in this space, and may result in unintended notifications being sent when a user types an email address.

The web client correctly interprets mashed-together @'s as incorrect syntax for mentioning and does not highlight the later instances in the string. We should update the server logic to use the same evaluation, requiring a word boundary before the @ before treating something as a mention.

Thanks to @Helcostr for spotting this trouble!

**Comment by patriciatiffany** [comment]
Hi @SabreCat! Could I take this on? It'll be my first issue and my first time contributing here.

**Comment by SabreCat** [comment]
@patriciatiffany Sure, take a look with our thanks! Definitely ask here or in the Aspiring Blacksmiths Guild on Habitica if you need any help getting going.

**Comment by patriciatiffany** [comment]
@SabreCat Just got set up, and looking around now! Is src/components/chat/chatMessages.vue the right place to go?

**Comment by SabreCat** [comment]
@patriciatiffany This is for the server side, so `website/server/libs/highlightMentions.js` should be the spot. I think it's just a simple edit to the regex on line 7!

**Comment by patriciatiffany** [comment]
@SabreCat Thanks! The tweak I see would involve a lookbehind in the regex... but it seems like that's not supported by all (older?) browsers. Is there another edit you had in mind?

**Comment by Alys** [comment]
@patriciatiffany If this code is only going to be run server-side, which I think is the case, then a lack of browser support won't matter.

I believe the code that evaluates @-mentions and sends notifications is part of Habitica's API / server code, and doesn't run directly in the website.

**Comment by SabreCat** [comment]
@patriciatiffany: I agree with @Alys's assessment--the backend code doesn't care about specific browsers!

**Comment by patriciatiffany** [comment]
Hi! I think someone must have already fixed this before I came along. The regex `const mentionRegex = /\B@[-\w]+/g;` already looks for a word boundary, and it seems to work when I test it locally.

If it's the same user that's mentioned twice in a row, though, both will still be highlighted. That seems like okay behaviour?

**Comment by himanshu-0611** [comment]
Hey, I am a newbie here, can anyone tell me how this issue is solved?

**Comment by Helcostr** [comment]
@patriciatiffany did you test removing the word boundary and seeing if both instances of the user will be highlighted?

**Comment by beffymaroo** [comment]
Possible related report? 

        Please describe the issue you encountered:
When I was trying to @ my party members in our party chat, it didn’t work. Referring few people at the same time is OK. But for 14 people all together doesn’t work. I also leave a space between each members’ usernames.
        User ID: 2b47e470-3434-44f0-9fb3-9fc648abc60f
        Level: 71
        Class: wizard
        Dailies Paused: false
        Uses Costume: true
        Custom Day Start: 6
        Timezone Offset: -60

**Comment by SabreCat** [comment]
I just gave this a try, and I believe you're right, @patriciatiffany, the mentions feature already requires a word boundary there. @Helcostr was mistaken, perhaps!

I'll follow up with @beffymaroo about the last comment separately.
