### ISSUE TITLE
Accessibility Concerns

### ISSUE THREAD

**Issue by AndreCaseyScott** [HabitRPG/habitica#1328]
_NOTE: this cannot be assessed until after the rewrite._

I've been thinking a lot about some of the accessibility issues HabitRPG has at the moment. Specifically how we can make the experience better for not only people with disabilities, but everyone as a whole. With HabitRPG positioning itself for use with Health Orgs and Enterprise in the future, best to start talking about these things. 

I noticed some brief talk about accessibility of the interface over in #585, but figured a dedicated thread to this would be better.
## Inventory

After discussion in #1224 about having the hover bubble be the main way of labeling inventory items, and testing #1274 (hint: it's a pain), I'm inclined to return labels to their rightful place.
- Reasons:
  - the eggs themselves are not descriptive enough by themselves
  - hover action is unreliable
  - If vision or mobility was an issue, having to hover over each item would be frustrating

This would require fixing #1227 so they would display correctly, at least for new items and users. But would increase the overall user experience, being able to scan the inventory (or read descriptions) before moving mouse. Consider what it would be like if you had movement issues (arthritis or carpal tunnel). 

It would also reduce the ambiguity of what is what in habit. I use the example that if my mom tried to use the Inventory as it is, she would be totally lost and frustrated.
## Item Descriptions

As mentioned in #1327, the hover action is too precise on some items, resulting in being frustrated or unable to click or read the info. This is probably an issue with other parts of the site as well. 

I haven't done an audit as to offending items, but wanted to get it down so it can be looked at. 
## What you can do

If you find anything about the User Interface frustrating to use, or is/could be an issue for people with disabilities, discuss it below. Or you can open a ticket and reference this one. 

This can't be given a good look until after the rewrite is launched.

**Comment by SabreCat** [comment]
I am a fan of the inventory without captions, but this is a compelling argument for bringing them back.

**Comment by wc8** [comment]
[Costumes comment … wrong browser tab open]

**Comment by wc8** [comment]
Mouseover of item notes (the speech bubble icon) is at times impossible to use. This is possibly affected by browser window width. Another user first drew my attention to it.

**Comment by SabreCat** [comment]
@wc8: Yeah, that problem has been around for ages: #399. @lefnire had hoped it would be cleared up with the jump to Angular, but it's the same old. Something awry in the way the popovers position themselves...

**Comment by wc8** [comment]
Would it mess up drag-and-drop to have notes appear on hovering over the main task text instead of the comment bubble? I had this idea when I noticed that Re-Roll gets two mouse-overs, one for the comment bubble and a simple redundant, yellow label, “Re-Roll"

**Comment by SabreCat** [comment]
@wc8 Ooh, that's a great idea, especially if the fix to comment bubble hover continues to be elusive.

**Comment by wc8** [comment]
Added a [Trello card](https://trello.com/c/x7Zm7UCY) for hover notes.

**Comment by deilann** [comment]
This is definitely being discussed on Trello.
