### ISSUE TITLE
aborted Quest should appear in Quest Inventory without manual sync

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13289]
As reported by @citrusella and confirmed by me:

> If you abort a quest, you won't be able to see it in your inventory (including via the "start a quest" form on the party page) until you manually sync or you reload (or presumably if you do something that causes a full sync to happen).
> For a brief moment I actually thought I lost the quest in question after aborting (which would have been a much worse bug if true), but it was just a visual thing.

The desired behaviour is that as soon as you abort a quest, you should be able to see it in your Inventory or restart it from the Party page without needing to sync manually.

**Comment by lizapritchard** [comment]
Can I work on this?

**Comment by Alys** [comment]
@lizapritchard Thanks! I've marked this one as in progress for you. It's significantly less important than the "wrong challenges shown for guild when accessing through notifications" issue, in case that helps you decide how to allocate your time. Post here if you have any questions or run into any issues.

**Comment by shanaqui** [comment]
@lizapritchard Hi there! Are you still working on this one? If not, or if you don't reply within a week, we're going to mark this as "help wanted" again to make sure people know it's available to work on. Thanks!

**Comment by ShiqiRao** [comment]
I think the problem is that the member's data is not refreshed while the inventory page is loading.Maybe forcing data to load will work.
