### ISSUE TITLE
I got two eggs, hatched them, they disappeared

### ISSUE THREAD

**Issue by 4G0N** [HabitRPG/habitica#1329]
I completed two of my daily quests, getting a dragon egg and a flying pig egg, went to my inventory, poured a base potion on each of them (in that order), went to the stable, and I don't have a dragon! I do have a flying pig, though. Is there any way to get that dragon back? 

Upon checking it again, my flying pig turned back into an egg. I used a base potion on it again and now it's back in my stable. Still no dragon nor dragon egg, though!

**Comment by lefnire** [comment]
Give me your uuid, I can give you some tokens to buy back. Unfortunately
can't fix it his bug till we rewrite (see #165)

**Comment by 4G0N** [comment]
My user ID is bgaesop. Thank you for the assistance!

**Comment by SabreCat** [comment]
@bgaesop: Not the user ID you log in with, the funky UUID from the Settings page. This FAQ shows you where to find it: http://community.habitrpg.com/faq-page#n416

**Comment by 4G0N** [comment]
Ah, gotcha. Here you go:

6fb1e4cc-c14a-4bbb-8d62-60469503c0f8

On Thu, Aug 22, 2013 at 12:04 PM, Sabe Jones notifications@github.comwrote:

> @bgaesop https://github.com/bgaesop: Not the user ID you log in with,
> the funky UUID from the Settings page. This FAQ shows you where to find it:
> http://community.habitrpg.com/faq-page#n416
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1329#issuecomment-23064050
> .

## 

-Thomas Eliot

**Comment by lefnire** [comment]
added tokens to account

**Comment by 4G0N** [comment]
Thank you

**Comment by lefnire** [comment]
this should be fixed now
