### ISSUE TITLE
Orb of Rebirth should unpin Antidotes (Sand, etc) for Transformation Item buffs (Seafoam, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13306]
_I'm marking this as "good first issue" and also "minor" priority, so experienced Blacksmiths should leave this issue for a new coder. :)_

If you have had an avatar [Transformation Buff](https://habitica.fandom.com/wiki/Transformation_Items) cast on you, and you then use the Orb of Rebirth, the transformation effect is removed at the same time as the other Buffs (that's the correct behaviour). However Rebirth does not un-pin the antidote to the transformation Buff. 

For example, if you had Seafoam cast on you, the Sand antidote would be automatically pinned in your Rewards section, and then after Rebirth it would still be pinned there.

The expected behaviour is that using Rebirth un-pins any antidotes that are no longer needed.

Below is the code for how cron handles removing all the Buffs and then unpinning the antidotes. Rebirth should do something similar.

https://github.com/HabitRPG/habitica/blob/bc730a0d59676aabaa8bbd55fb198995b7c8ba3a/website/server/libs/cron.js#L508-L511

_Thanks to @clumsybrock (05c4dd65-e87c-448f-981c-5d882efcd60d) for reporting this._

**Comment by Walker80529** [comment]
Can I do this?

**Comment by Alys** [comment]
@Walker80529 Sure! Thank you! Please go ahead and post here if you have any questions or run into problems.

**Comment by Walker80529** [comment]
All we need to to is add the above code.

**Comment by dabrowskif** [comment]
I've already finished fixing my previous bug (having problems with git push origin, posted on aspiring blacksmith guild, waiting for help and response) and can take on this one if it's not finished yet.

**Comment by Walker80529** [comment]
That’s fine. I don’t really understand how to fix this.

-George Busby

**Comment by himanshu-0611** [comment]
I don't intend to take this issue, I am a newbie, can anyone please explain to me in simple words what this issue is?
