### ISSUE TITLE
UI elements taking on system dark mode colours

### ISSUE THREAD

**Issue by J-Sanderson** [HabitRPG/habitica#13312]
Created on request from Alys.

### General Info
  * UUID: cbeeb477-d5db-4efd-8f0b-68201870482b
  * Browser: Firefox 57.0
  * OS: Linux Mint 18.3

### Description
Certain UI elements take on dark mode colours when dark mode is set in the system settings. It does seem to be based on system settings as changing Firefox to light mode makes no difference.

It is worst on inputs, as the content is near impossible to see:

http://lilaclynx.net/img/darkmodeinput.png
![image](https://user-images.githubusercontent.com/1495809/120788988-59e52600-c574-11eb-9299-be3b86fe28e6.png)

~It also effects elements such as notifications, tooltips, etc, but I am not sure if this is intended behaviour anyway and it doesn't break accessibility like the inputs:~

~http://lilaclynx.net/img/darkmodetooltip.png~
~http://lilaclynx.net/img/darkmodenotification.png~
~http://lilaclynx.net/img/darkmodedrawer.png~

There may be more elements affected, these are just the ones I found. I'd be happy to volunteer to fix the problem for you.

#### Console Errors
None

**Comment by Alys** [comment]
@J-Sanderson Thanks!

As mentioned in the Report a Bug guild, it's only the input field that's affected. The other screenshots show the standard appearance. I've inserted the input field screenshot as an inline image and I've put strikethrough around the section that isn't affected by dark mode.

Can you please also add a screenshot showing the system setting for dark mode?

**Comment by J-Sanderson** [comment]
My apologies, it looked so close to my dark mode theme that I assumed they were affected.

Here are my system settings:

http://lilaclynx.net/img/darkmodesettings.png
_[screenshot inserted inline below]_

It looks to be the Controls setting that causes the issue - if I switch to a lighter theme it goes away.

I also noticed that the item sell dialogue input has the correct white background, so I suspect there's a missing class or similar in the affected buy.


![image](https://user-images.githubusercontent.com/1495809/120788915-3e7a1b00-c574-11eb-85ff-60edc593d944.png)

**Comment by Alys** [comment]
@J-Sanderson Thanks!

I've labelled this as "needs design" for a design-related decision to be made about if/how to fix this. Just to highlight this: J-Sanderson has offered to work on a fix.

@J-Sanderson If you have any thoughts about how you'd go about fixing it, please post here, but please be aware that Habitica's staff may make their own decision about a fix so you may not want to spend too long on planning a fix if you don't already have one in mind. :)

**Comment by J-Sanderson** [comment]
I think it's just a case of missing classes. Comparing the buy input to the sell input (which as I noted has a white background), I noticed it has a class of form-input that specifies the background colour. This class is missing from the buy input so I'd just add it in and maybe check for any other inputs similarly affected while I was at it.

**Comment by Tressley** [comment]
@J-Sanderson -- Nice sleuthing! That seems like a good start. Are you still interested in working on this issue?

**Comment by J-Sanderson** [comment]
Yes, I'm happy to pick it up.

**Comment by J-Sanderson** [comment]
Chasing up, are you waiting on me to work on this or am I waiting on you to give me the okay?

**Comment by Alys** [comment]
@J-Sanderson I'm not staff and I'm not involved in the visual design aspects of the site, so I can't be sure about this, but I think it's likely that it's okay for you to go ahead. However if you want to be certain that your time isn't wasted, you may want to wait for @Tressley to comment.

**Comment by Tressley** [comment]
Ah, I can see how that wasn't clear. Yes, please go ahead. 😄
