### ISSUE TITLE
Countdown is wrong for limited-time items that are no longer purchasable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13318]
Related to https://github.com/HabitRPG/habitica/issues/9933 :

If an expired limited-time item is pinned or otherwise still visible, the countdown makes it look as if it's still available.

![screenshot](https://user-images.githubusercontent.com/1495809/120784437-6f0b8600-c56f-11eb-9569-8c3a6a0f6b42.png)

_suggestion-discussion for the staff to comment on how they want this fixed, since once https://github.com/HabitRPG/habitica/issues/9933 is fixed, the incorrect countdown would presumably no longer be a problem_

**Comment by SabreCat** [comment]
I think this is fixed in a89c7d2. @Alys let me know if it's still acting up!
