### ISSUE TITLE
arrow keys for purchasing items are not clickable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13313]
When trying to purchase items, the arrow buttons that let you change the amount to buy don't respond to clicks (i.e., the arrows shown in the screenshot below). Similarly for the arrow keys when selling items. Firefox on Ubuntu. 

This was also reported by @Sara-lily (80fd8da4-45bf-4105-8ff0-3434cef1b311):

> The hit box when trying to increase the number of things to purchase by using the arrow keys is essentially non-existent on Firefox (not sure if it's an issue in other browsers). It acts like an input over top of both buttons making them impossible to click (and is rather annoying when I just want to buy two gems and have to replace text in the field instead of just click the up arrow).

![image](https://user-images.githubusercontent.com/1495809/120635533-eda0ee80-c4af-11eb-9c2a-d93f6fcedf57.png)

**Comment by ShiqiRao** [comment]
It seems like a bug of old version firefox.When I tried to reproduce it with the latest version firefox, arrow keys still can work.
After while,I changed firefox to 88.0.1 version,  and then the bug was reproduced.

**Comment by mornir** [comment]
yes, I also couldn't reproduce the bug in the latest version of Firefox on Windows 10. Does the bug only occurs in Firefox on Ubuntu? (In that case, I would say the bug comes from the OS/Firefox and not from habitica, and would close the issue)

**Comment by ShiqiRao** [comment]
> yes, I also couldn't reproduce the bug in the latest version of Firefox on Windows 10. Does the bug only occurs in Firefox on Ubuntu? (In that case, I would say the bug comes from the OS/Firefox and not from habitica, and would close the issue)

In order to verify whether it is related to the OS, I tried it with the latest version on Ubuntu.Still the same.

**Comment by Alys** [comment]
The bug no longer happens for me either so I'm closing this issue.

@mornir @nockyQ Thanks for your testing!
