### ISSUE TITLE
Class icon is in middle of avatar in Profile screens and Edit Avatar screen, and might be wrong in header

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13316]
When you look at a profile screen or the edit avatar screen, the class icon is around the middle of the avatar.

Marking this "needs design" for a decision on where it's meant to be.

![image](https://user-images.githubusercontent.com/1495809/120886485-975bb900-c631-11eb-8cd0-1136adaad755.png)

![image](https://user-images.githubusercontent.com/1495809/120886915-a5123e00-c633-11eb-91ab-057ce9854943.png)

**Comment by Alys** [comment]
Also on the Edit Avatar screen. I've updated the top post with a screenshot of that.

**Comment by Alys** [comment]
An addition from @PixelStormArt (100fadc6-0b54-4329-8dc3-d96b5e482399):

> I have an extra report to add to the class icons not displaying correctly. In addition to seeing the icon over an avatar on profile and edit avatar pages, my class icon is also displaying differently in the party header bar. The icon and circle are much smaller than before - screenshot [below]. I'm not sure if this is an intentional design change or related to the already reported bug, but I thought it would still be worth mentioning just in case.

![image](https://user-images.githubusercontent.com/1495809/120943458-5c14d380-c772-11eb-9814-b6efe5ca4920.png)

**Comment by habitrpguser** [comment]
I just wish to confirm that I am also seeing that bug.

**Comment by Tressley** [comment]
This looks to be an issue with a recent PR. I think the fix is just adding `px` to the `--badge-size: 32;` line.

**Comment by FarisPalayi** [comment]
Hey, can I work on this?

**Comment by Alys** [comment]
@FarisPalayi Yes, thank you! Post here if you have questions.

**Comment by FarisPalayi** [comment]
Okay👍

**Comment by FarisPalayi** [comment]
So, this is the desired class icon's position, right?
<img width="148" alt="Screenshot 2021-06-09 154603" src="https://user-images.githubusercontent.com/78663072/121337587-54a02680-c93a-11eb-8fb6-3f468d9af1d4.png">

**Comment by FarisPalayi** [comment]
And this is how the header icon should be, right?
<img width="361" alt="Screenshot 2021-06-09 155244" src="https://user-images.githubusercontent.com/78663072/121338076-cbd5ba80-c93a-11eb-93f8-e8c1c7d807b4.png">

**Comment by Tressley** [comment]
Both of those are correct. 👍🏻

**Comment by FarisPalayi** [comment]
Hey guys, I solved the issue, but I can't start the development server.
When I type `npm run client:dev `, I'm getting this error: 
```
'vue-cli-service' is not recognized as an internal or external command
```
Do I need to have Vue CLI installed?

**Comment by FarisPalayi** [comment]
installed Vue CLI, but still getting the error. 
Full error 👇
```
C:\Users\ACER\Personal\Programming\Write Code\Contributions\habitica>npm run client:dev

> habitica@4.196.0 client:dev C:\Users\ACER\Personal\Programming\Write Code\Contributions\habitica
> cd website/client && npm run serve


> habitica-client@1.0.0 serve C:\Users\ACER\Personal\Programming\Write Code\Contributions\habitica\website\client
> vue-cli-service serve

'vue-cli-service' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica-client@1.0.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the habitica-client@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2021-06-10T08_39_32_293Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.196.0 client:dev: `cd website/client && npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the habitica@4.196.0 client:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2021-06-10T08_39_32_329Z-debug.log

```

I did everything correctly like the 'setting up habitica locally' article.
Don't know why this is happening.

**Comment by FarisPalayi** [comment]
Solved the problem. There were some npm packages missing. Typed `npm install` again. Server is running now.😀

**Comment by FarisPalayi** [comment]
Hi guys, 
It's been almost a week since my PR, do I have to notify the maintainers to get a review?

**Comment by Tressley** [comment]
Thanks for getting this together quickly!

Habitica is a small team, and we all wear many hats, so we’ll get code
review on this as soon as we can.

**Comment by FarisPalayi** [comment]
@Tressley Thanks for the quick reply 😊. 
This is one of my first contributions, so I was just confused if there is anything that I'd missed or something that I should be doing that I didn't do, that's all.
