### ISSUE TITLE
New day started too early

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1331]
hello,

First time I get this issue. My custom start of day is 7:00 (24h clock), but I just came back home at 9:45pm and it seems that the new day already started (maybe cards got reset at 7pm ?

Dailies cards for Wednesday are open though. Seems like it reset my cards (but not the gold & xp), and I lost the streak number on the cards I didn't checked yet for today.

User id: 84497c76-4028-4dd5-8403-69b4f5b12575

Hopefully you can figure out what happened :)

**Comment by lefnire** [comment]
will hit this asap. we added cron to the API, and having difficulty telling timezones with the api / server. likely chrome extension or pomodoro or such triggered this, but essential I fix asap

**Comment by mnorthenscold** [comment]
I got this issue the last two nights. The new day had started by around 10PM my time (US Central), and the dailies had reset. I had the custom start of day set to 2:00, then changed it to 3:00 the next day, but it didn't help.
Perhaps it is a timezone problem. Thanks.

User ID: b338ddab-3a6c-4ecd-be7a-2846a1a25b5a

**Comment by lefnire** [comment]
Yep, definitely a timezone prob. Your 10pm is my server's 12am, so that's a full-on confirmation. Tomorrow I'll fix this issue first thing in the morning.

**Comment by AnonyMoses** [comment]
Chiming to say I am also suffering from this issue, the custom start to my day has no rule over the error that is going on.

**Comment by apLundell** [comment]
I'm also experiencing issues with day-start time.

my day start time is 7:00am, (EST) but when I check things in late at night, the check-ins seem to get carried over to the next day!

The weird thing is that I don't lose my streak bonuses, or get a HP penalty.  I think it's "Counting" for both days. (I don't think I get double XP, though. )

**Comment by SHMAUS-Carter** [comment]
I just had a new day start early as well. (-6 gmt/cst)

**Comment by lefnire** [comment]
sorry guys, everything's so disorganized since I have 3 repos going on. Let's consolidate the issue over here https://github.com/HabitRPG/habitrpg-mobile/issues/73
