### ISSUE TITLE
Quest modals say "New Item" where they should say what the item is

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13326]
When a Quest modal shows you the rewards for a quest, any reward that is not Gold or Experience is listed as "New Item", meaning that you have no way to tell what the item is if you don't recognise the image (that's especially undesirable for Pet Quests since some of the Eggs have names that are noticeably different than the Quest / Boss name, and so you can't guess what they'll be called, and so, for example, you can't use the rewards list to decide whether you want to spend gems on that particular quest or not).

This bug occurs in the Quest modal that you see in all locations
   * Shops > Quests
   * Inventory > Items
   * Party > Select Quest
   * when a Quest finishes
   * etc
There'll most likely be a single piece of shared code that you can update to fix this in all places at once.

The names of the items can be found in the `text` attribute in the `drop.items` data for each quest. For example in the lower half of this snippet:
https://github.com/HabitRPG/habitica/blob/07b9cc533ba79aa9bc7598d9d142eef442eca134/website/common/script/content/quests.js#L473-L497

![image](https://user-images.githubusercontent.com/1495809/121152926-f8c99500-c888-11eb-8170-6d9c3ed00e70.png)

![image](https://user-images.githubusercontent.com/1495809/121153034-126adc80-c889-11eb-98d3-3d70ed274a1d.png)

---

_Thanks to  @EricadawnK and @Acorn_Sprout for reporting this._

**Comment by Tressley** [comment]
These items are just missing their associated tooltips. Should be able to carry it over from The Market.

**Comment by negue** [comment]
so `New Item` stays, but add the other tooltips ?

**Comment by Tressley** [comment]
Yes. New item stays because we don't have a ton of space to display longer
names. They'll just re-use the tooltip from The Market.

**Comment by Alys** [comment]
Is it possible to make space for the item titles to be displayed? The items are the most important information about the quest since they're the primary reason for choosing which quest to buy or do. It used to be one click and scroll down to see what items you'd get, now it's a click and scroll down and a mouse move for the hover (repeated when there's more than one item type), so it's less usable for players, and less accessible for people with mouse movement difficulties or who use screen readers.

**Comment by Tressley** [comment]
I’d prefer if we just focus on fixing the sprites for now. The quest reward
items are using the same layout as items seen in inventory and market.
These are familiar, not any less usable or accessible, and actually give
the user more information that wasn’t originally available in the previous
design (next quest info, item info).

Additionally, these simpler updates do a much better job of conveying the
information in a clear manner and no longer run into the display issues of
the previous design.
