### ISSUE TITLE
Difficulty dropdown spacing and alignment issues

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#13329]
The Create and Edit Task modal difficulty dropdown has styling issues. Menu items are no longer vertically centered and the star icons aren't far enough to the right.

![image](https://user-images.githubusercontent.com/2686586/121536470-143fb780-c9d1-11eb-940d-b01d9ca96566.png)

**Comment by godwin-morwin** [comment]
Hi @Tressley ,
i do like to solve this issue

**Comment by Tressley** [comment]
@Godwindaniel10 -- Great! It's all yours. 👍🏻

**Comment by godwin-morwin** [comment]
hi, 

I have been getting this error in my terminal while running the ( npm run mongo:dev ) command, and I have been trying to fix it for weeks by trying different possible ways i can, but still not getting through.

![err](https://user-images.githubusercontent.com/54848535/122253484-1d92bd80-cec4-11eb-9332-a19e4124d33d.JPG)

**Comment by Harinivas2003** [comment]
Hi @Tressley , I think I can solve this issue.

**Comment by citrusella** [comment]
I'm not Tressley (or even an admin here on Github or anything) but I think Godwindaniel10 still has it claimed (and hasn't un-claimed it at present?).

**Comment by Tressley** [comment]
@Harinivas2003 -- Godwindaniel10 is currently working on this issue. Should it become available again in the future, you're more than welcome to take it on.

@Godwindaniel10 -- Tagging in our developers @SabreCat @negue to see if they can help you with the issue you're encountering.

**Comment by godwin-morwin** [comment]
@Tressley alright, thanks, will be looking forward to the solution. meself is still trying out more solutions

**Comment by negue** [comment]
I'm not that experienced with the `run-rs` way. When #12335 was added - this linked issue in `run-rs` also mentions `ECONNRESET` https://github.com/vkarpov15/run-rs/issues/45

In that issue it is mentioned to not use `--keep` on the first execution, could you try to run this in your terminal:

`run-rs -v 4.2.8 -l ubuntu1804 --dbpath mongodb-data --number 1 --quiet`

It is the same command as `mongo:dev` except for the `--keep` part  - hopefully this works

**Comment by shanaqui** [comment]
@Godwindaniel10 Hi there! Are you still working on this one? If not, or if you don't reply within a week, we're going to mark this as "help wanted" again to make sure people know it's available to work on. Thanks!

**Comment by godwin-morwin** [comment]
> @Godwindaniel10 Hi there! Are you still working on this one? If not, or if you don't reply within a week, we're going to mark this as "help wanted" again to make sure people know it's available to work on. Thanks!

Hi @shanaqui , I am so so sorry for the delay in working on this issue. I should have responded. and I am currently overwhelmed at the moment and I don't want the issue to wait again, so it will be best if someone else works on this issue.

**Comment by shanaqui** [comment]
@Godwindaniel10 No problem, I'll mark the issue as "help wanted" again!

**Comment by sahilcode17** [comment]
hi @Tressley i would like to contribute to this issue @shanaqui  would love if you could help on how can I get started on this

**Comment by beffymaroo** [comment]
@sahilcode17 Are you still interested in working on this issue? Please let us know if so. If not, I will mark it as Help Wanted again. Thank you!

**Comment by SabreCat** [comment]
Opening this back up to contributors-- @sahilcode17, if you still want to tackle this, let us know!

**Comment by sahilcode17** [comment]
@SabreCat  yes but would love if can get help on how can i get started

**Comment by twjasa** [comment]
Hello 👋 , 

Can I take this? I think I can resolve it pretty fast

**Comment by jbryson3** [comment]
I can take a crack at this, if its not already in progress

**Comment by citrusella** [comment]
I'm not someone who can give a definitive answer as I'm not, like, staff or something, but I think [Guidance for Blacksmiths](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths) advises to look at the most recent comment to see if someone's asked to work on it recently and then if you do ask, to wait on admin okay before starting work? (Largely to make sure you don't waste your time, if an admin's answer were to be "no", I guess?)

(Again, I'm kind of just regurgitating the guidance page here, and partially because there *was* someone who asked to work on it, in the comment immediately preceding yours. 🤔)

**Comment by jbryson3** [comment]
Thanks @citrusella, I totally missed the last reply to this before I started work. It was only when I was opening up the PR that I saw that someone had requested to work. I figured I'd open up the PR anyway because I had something. 

I'll be more mindful on this project in the future, and will definitely understand if the PR gets closed and the ticket assigned to the previous person!

**Comment by SabreCat** [comment]
Yeah, apologies for the delay there! We're implementing some new practices with regards to maintaining these GitHub queues, so turnaround times should start to improve. In any case, we'll give a look at your PR soon!
