### ISSUE TITLE
cloned challenges should keep tasks in the same order as the original

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13328]
As noted at https://github.com/HabitRPG/habitica/issues/1703#issuecomment-856953339 (comment copied below) when you clone a challenge, the tasks sometimes do not keep the same order they were in in the original challenge.

 I reproduced this using https://habitica.com/challenges/79fabb8c-f99a-459f-bdb7-ed810f25661b - the first clone had the tasks in the correct order, but the clone of that clone had the Habits mixed up.
 
 As you can see from the report below, other kinds of tasks can have the same issue.
 
 If anyone would like their own copy of the https://habitica.com/challenges/79fabb8c-f99a-459f-bdb7-ed810f25661b challenge so that you don't have to recreate it manually, post your User ID (not Username) here and I'll use my moderator abilities to clone it and make you the owner of the clone.
 
 ---
 
Original report from https://github.com/HabitRPG/habitica/issues/1703#issuecomment-856953339 by  @habitrpguser :

This bug still happens! I don't know if challenge tasks change order if a challenge is cloned once (I couldn't reproduce that), but they definitely do if a challenge is cloned and then that clone is cloned again. Please see examples:

https://habitica.com/challenges/79fabb8c-f99a-459f-bdb7-ed810f25661b

https://habitica.com/challenges/7f96108c-c086-4ae1-9fa4-7b2006bbb965

https://habitica.com/challenges/6cec332e-8ddc-46f7-afe6-f2a9cb212311

**Comment by Lyqst** [comment]
Hey, I can take a look into this if that's ok!

**Comment by Alys** [comment]
@Lyqst Thank you! Please go ahead and post here if you have questions.

**Comment by Lyqst** [comment]
I think I've fixed the issue. The problem was that when  querying for the tasks to be added to the new challenge, it would just search by the challenge id, which I don't think would necessarily return the tasks in the expected order:
```javascript
const challengeTasks = await Tasks.Task.find({
  'challenge.id': challengeToClone._id,
  userId: { $exists: false }, 
}).exec();
```

I've changed this to instead iterate over the tasksOrder arrays in the challenge, so we get the tasks in the expected order:
```javascript
const challengeTaskIds = [
  ...challengeToClone.tasksOrder.habits,
  ...challengeToClone.tasksOrder.dailys,
  ...challengeToClone.tasksOrder.todos,
  ...challengeToClone.tasksOrder.rewards
];

const challengeTasks = await Promise.all(challengeTaskIds.map(async taskId => {
  const task = Tasks.Task.findById(taskId).exec();
  return task;
}));

challengeTasks.reverse(); // last task should be added first and vice-versa, since new tasks are prepended
```
I've tested this and it looks to be working, but please let me know what you think before I create the PR.

**Comment by Alys** [comment]
@Lyqst This seems like a good idea to me (although if any of the staff post here to say otherwise, listen to them not me). It sounds like you have it working in your local install - which is great! - so I think it's appropriate for you to do a PR and that will let us review the code to see what we think. Thank you for working on this!
