### ISSUE TITLE
Buying a custom reward sets its cost to 0 and doesn't remove gold

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1333]
Windows 7, Chrome browser, user ID 7f14ed62-5408-4e1b-be83-ada62d504931, on both Beta and main sites.

As of this evening, when I attempt to purchase one of my custom rewards, my gold doesn't decrease--instead, the cost of the reward drops to 0! No JS errors are logged.

The Undo bubble conveniently resets it to what it was, but right now I'd have to manually edit my gold to dock myself anything...

**Comment by lefnire** [comment]
fixed https://github.com/HabitRPG/habitrpg-shared/commit/fc3d863feb43a7b745bcf3cd12f27a3a08bf51e7

**Comment by lefnire** [comment]
btw sabe, i know you're starting to dabble in JS. don't let that commit scare you - the very last file (coffeescript) is compiled into vanilla javascript (all the complex shit) so that mobile can use it

**Comment by SabreCat** [comment]
You mean the 7000-line change? Hah, interesting. I did research how
CoffeeScript works, and install the CS-to-JS command line compiler, when I
was trying to figure out how to randomize the Anonymous user's appearance.
I have a basic understanding of that and Lodash, now... bit by bit I'll
learn about the pieces that go into a Habit install!
