### ISSUE TITLE
GPL V3 use

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#13331]
Hey everyone, don't know if this is the proper channel for communication, but I have some doubts about the GPL V3 license regarding habitica and browserquest. I am building a study web application where you take notes, make flashcards from those notes, and review them. I would like to implement a gamification system to make things more fun and found BrowserQuest wich then led me to Habitica which uses the same assets. I saw it and thought it was pretty cool, however I don't necessarily want to have all my code in the GPL V3 licenses. So I was wondering what my options are and the solutions I think seem feasible are:
1. Build a gamification system based on habitica separate from the rest of the components (I was thinking of having a different page where you can check the characters progress however, I would also like to have "pop-ups" saying good job, among other things
2. Don't even look at the source code from habitica and simply try to implement a different gamificiation system based on the BrowserQuests assets completely from scratch (wondering what are the limitations of it being considered a derivative work here)
3. See if it is possible to negociate another license

I would like to ask if any of these options seem valid, and what suggestions you might have to solve this issue

Thank you for your time and attention, have a nice weekend

**Comment by SethFalco** [comment]
Generic [IANAL](https://en.wikipedia.org/wiki/IANAL) disclaimer.

> Don't even look at the source code from habitica and simply try to implement a different gamificiation system based on the BrowserQuests assets completely from scratch

Copyright does not prevent you from reverse engineering software functions. It will not be considered derivative work in most cases unless you take snippets of code or content from the site directly.

> See if it is possible to negociate another license

That probably isn't going to work. All contributors retain copyright of their contributions. You'd need to get permission from every contributor on the project, or at least every contributor that has touched the relevant code.

**Comment by SabreCat** [comment]
Closing this ticket as it's not an issue requiring a fix in the repository--please email admin@habitica.com with your concerns and we'll get you the information you need!
