### ISSUE TITLE
Site won't load in any browser. (My PC language is english).

### ISSUE THREAD

**Issue by fassina2** [HabitRPG/habitica#13345]
This is what is displayed when I log into habitica, tried on chrome, edge, vivaldi, firefox etc..
> ��Yms��+�����  ps�N�^�7�L2Izi��Ę"��O��{@�O���t{A �}v��],�{���w��/߿��Ӧ}��4:c_�ܸ�D�������T'jqZ]O�6q���r���_%�fk��l�"��nrD޾^:�r�B�ٸ�b߸�m?Lg��;�����%�"n�fjL���iݒbj�ֽ�4%nT&J�7f�ԇ�~7D�4�{���+�n��f;5}w���#Ճs��/E���v�����}3"��F��L�483���+ô�Zh�p倰�.ݡV��֮��ݑ�֍ۻ��7�M}T���@+���!�]Cׁ��������m�7)���}x�^�d|㯛�s��X��������Si�� /m���f7����߿���]E>-��3��x����qW����ܳ�]���+�ǩ��V}�z���ބ����> �@�)�8��*������o�U�6��H���X���8�W���~��MӽD����_ڞ���G���i�L;� � R6ݍ).��)E�UH>g�ɌWә���j͕b��O����[�[Ă�����7`L-P�v�kc��C�A�vẺ����uǕM�d��as^e'����O��ij���,� �6�U�\���ǓGfی��j�Z������/����E�Y׍ξ�Y���&�4�9ny|c�s���ӡu�ڹ�ւ�2�u�vS�n�Ϳݸ\p���������;ƴ6{?!�D5{��g��u�t����Nr���%!8��n��E�z�l�t) �� ���c��0?�_�����yaTE�ʉW�c��j�iItʶu��Bg5��{���j�w[���x·c��΍�i>5pf0{׺a�ٍn� B�S�t��������W�F�5�I]e�q-f� �Á��9��,�3g�����>g��C�1a���e����,�!{�t{0�{*��̵��P|,/Lar9/��g�S�̿?%.��+7��Bs[��Bߛ�%tE_Ф�e�U%���'٩�V#Q��ιl����H�s1/Ί��ږ�:��љ��LK �,ͨyƽS�0�9Nݼ @DgF:�� S�4���8�g)WR�y<;�D���O/��N�Ak����Yr7�(��Ϳ���%7�±8��͈LS�s�,�g6���J���γƥ��N�gbX�*�\�9��kSWzNDϛK��(��c�GZKa�@��C�mS2�̜�gK��Y�6�37#4�x�ܬb���Y]�R>K�~C1�h�������F���|�]3q���PsR���V��̖?6�������k#%ӥ�ٜ��X1��Y5�d��\�j���u%�����>�s߳��)�>8}���$���>��{���Ͳ��W/m���\x;Q� �t�îq� 76�m��\�7m7���}}M�s��Կ�ؽ��Ϛ��/Y�E�M#��5�:ԷXS,��RP"t����8�W�P���EB�/ v�h3��q�'P!d"<{ܳ�8����_�)�[�.aR��+��&� 2X��eτꥺ��R��X#�*�%�A�� ��'���D�c����<A�A ~������/����.�%(��`��D����I��JR7��c� ��d�s0ޅ\�A�!7Я��� �(�����ԃO���wT�LӣϠ~K�a�b��9�� 0�����2O���&�����>؞\_*(d楅'�@:��_�=�d�Ta;� ��W�候׉��}=3oz���oũ�}�pū,��|�a� ���ǚ�!���zP�} ��*$�羒�=����[�C�uIC ��|~]Dx�F�{�r�-���L�y�M���u]/R�891��p�_ܮ�F4��j������HۯV�!�x�Nt����� �W���MӅfd�CWy]���6鞧 U]Z�5Z|r׫>.��eه��L"=6�4�W����f�

It works on my phone. PC language is in english. Any clues on how to fix it ?
![Habitica bug](https://user-images.githubusercontent.com/36776815/122689633-906ca300-d1fa-11eb-9978-8cf244b8a2d2.png)

**Comment by Nakonana** [comment]
May be related: #13160

**Comment by Inseut** [comment]
It's been like this since yesterday for here and my partner, we're in Brazil. I posted about this on Twitter and another Brazilian person reported the same issue.
I tried opening Habitica in Tor, where it simulated a German connection, and it worked. Maybe it's region-specific?

**Comment by fassina2** [comment]
> It's been like this since yesterday for here and my partner, we're in Brazil. I posted about this on Twitter and another Brazilian person reported the same issue.
> I tried opening Habitica in Tor, where it simulated a German connection, and it worked. Maybe it's region-specific?

Could be region related yes, I'm also in Brazil.

**Comment by NamelessGO** [comment]
Yo same, i thought it was because of ProtonVPN, nice to see that ppl are having the same problem

**Comment by shanaqui** [comment]
This should be all fixed now (and has been for several days); it happens sometimes after deploys. Is anyone still seeing a problem?
