### ISSUE TITLE
Not Enough GP Popup Mesage While Trying to Buy Armor (Error)

### ISSUE THREAD

**Issue by MetaphoricalSheep** [HabitRPG/habitica#1334]
Hi, I've been trying to buy the red armor types since yesterday. At first nothing would happen when clicking on any armor type; today I get a message stating that I do not have enough GP. I have 96 gold and the most expensive armor of this tier costs 90 gold. 
- Refreshing the page (f5 and ctrl+f5) does not help
- Completing more tasks to get the gold to change does not work
- I'm using Chrome, did not try to reproduce this bug on another browser
- User Id: 31f430f3-2783-4b5f-81a7-8d848078eea7
- Only the "usual" JS errors are occuring, nothing strange when I'm clicking on the armor

**Comment by schulmanwriter** [comment]
I'm getting the same issue. Yesterday would click and nothing happen. Today it's not enough GP when I clearly have enough.

**Comment by lefnire** [comment]
duplicate: https://github.com/lefnire/habitrpg/issues/1330

**Comment by lefnire** [comment]
@Ambulans 

> Completing more tasks to get the gold to change does not work

are you now not getting GP from completing tasks?

**Comment by MetaphoricalSheep** [comment]
Sorry that was a bit ambiguous, what I meant was that even after getting more gold it still did not change the message. I was able to buy the red helmet an hour or so ago, but instead I got the golden one. I reported this on the other thread.
