### ISSUE TITLE
The check-ins modal has an extra string which seems superfluous

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#13343]
User report:

> probably not technically a bug (?) but it seems like [the check-in-reward announcement](https://i.imgur.com/cQCfwte.png) doesn't need both those lines? might be another weird thing with the british language habitica. unless of course they mean different things and i'm missing something."_

I confirmed this in the default language setting.

**Comment by shanaqui** [comment]
citrusella added additional thoughts:

> Not a fix so much as an add-on (for further reference for others), but I can say with certainty the check-in counter issue is not language specific (the relevant lines are [here in the Github file for the modal, for anyone looking](https://github.com/HabitRPG/habitica/blob/51e8aa341dc2d46aa102b3d9014b22584aa8a756/website/client/src/components/achievements/login-incentives.vue#L72-L91). After some discombobulation involving both the main Github and a fork (I was trying to figure out how far back both lines were used and it seemed like they were both in use all the way back), this is what I found, and my best guess at the possible reason there's two, whether or not that's still "needed". Looking back, one was phrased more like a sentence when the lines were initially added (as of the merge of the pull request) and a change to improve their grammar for single-day situations made them more similar... but even the prior structure would have been duplicating information but the text lines would have just looked more different... (For reference: [original commit that added the lines](https://github.com/HabitRPG/habitica/commit/25b0ff38c42ef0b36e4f6bf9bb6667a387cc70c2#diff-417eed3e9a7fa4a28d433695b84e4610499078b24bb98fc4b368092a037cc7f1), [commit that changed the structure for those two strings in the English file back in 2017 (would have propagated more gradually out to various non-USEnglish language strings)](https://github.com/HabitRPG/habitica/commit/44f23a76751f1fcf5860db9f0ab7ec7dfa8d3a28#diff-417eed3e9a7fa4a28d433695b84e4610499078b24bb98fc4b368092a037cc7f1)) Though I can't find evidence of it in the actually committed code, the modal popup originally only used `nextRewardUnlocksIn` (the line that says "next prize" instead of "next reward") judging by screenshots (in [this pull request](https://github.com/HabitRPG/habitica/pull/8230), [this specific comment shows an image with that structure](https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262420258)). It looks like the *very* earliest reason for the other line (`countLeft`) was for it to say "x left" in big letters on the modal ([reference for the string saying that](https://github.com/HabitRPG/habitica/pull/8230/commits/eb57f902c9accd2a990493df28a2357720a81538#diff-417eed3e9a7fa4a28d433695b84e4610499078b24bb98fc4b368092a037cc7f1)). So countLeft was originally part of the "art"/graphical representation at the top of the modal and the other was a sort of expanded prose version of the same information as part of the text. (The pull request at some point suggests countLeft be removed alongside another change.) It's like the string was kept but its functionality was removed... but then the string resurfaced on the modal again somehow...

**Comment by SabreCat** [comment]
Agreed, we only need to display that information once! The fix should remove the upper copy of the line ("Check-ins until next reward"), keeping the lower one. Then check if the removed string is used anywhere else--if it is, let's update those other places to use the same wording. And either way, remove the superfluous string from the locale files.

**Comment by CuriousMagpie** [comment]
I'll take this one on!
