### ISSUE TITLE
Task edit dropdown menus for Tags and Difficulty don't close themselves, causing overlap

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13344]
_Below is a report from @fufuj (86f37f0c-ebaf-4ee8-bf9f-00a5aa485501). I've marked this as in progress for them to work on a fix._

On Firefox and Internet Explorer (prolly on other browsers aswell), when you:
    + Click to edit a habit
    + Click on a Tags to expand dropdown list of available Tags,
    + Then, without closing Tags dropdown list, click on Difficulty to expand dropdown list of available Difficulties
    + Tags dropdown list doesn't close, therefore it looks bad when those lists overlaps each other

Also, i can try to fix it, so as soon as you post it on GitHub issues, i will apply to fix it.

Looks like this:

![image](https://user-images.githubusercontent.com/1495809/122635163-a3fa0a00-d125-11eb-9852-e4490217a220.png)

**Comment by dabrowskif** [comment]
Hi, as i wrote in Habitica, i will try to take care of it if possible. :)

**Comment by dabrowskif** [comment]
I've finished fixing this bug, but can't "git push origin name-of-branch" this. Wrote on habitica's aspiring blacksmith guild.
