### ISSUE TITLE
Warning for overbuying Magic Potions popping up unnecessarily - possibly related to Glass + StainedGlass hatching potions

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#13358]
_EDIT 2021-07-07 by Alys: see https://github.com/HabitRPG/habitica/issues/13358#issuecomment-875369365 for a guess at where the bug may be_

A user reported that they're seeing the warning about not being able to use all the Magic Potions they are trying to buy, but it's not correct.

They had previously bought and used 9, and had fed those pets to become mounts. They needed 9 more potions to rehatch the pets, but received the warning when trying to buy 9. The user in question is 941180d8-bff4-45c2-b997-c04394d9fa28, and I confirmed what they said from their account (i.e. they're not mistaken about how many potions they need, or anything like that).

Other users have been reporting that they saw the warning inappropriately as well.

**Comment by shanaqui** [comment]
A user who had no potions at all got the warning on Glass Potions when trying to buy 18.

**Comment by Alys** [comment]
@aethelflaeda (042b3a26-fa61-47f4-b0c4-c43a22f08688) reported:

> Whenever I try to buy glass potions I receive a message saying that whatever I buy will exceed the number of potions I need to hatch all the pets - which is odd, because I have no potions except basic ones (i.e. the normal drops) in my inventory and I have only hatched three glass pets.

**Comment by Alys** [comment]
I haven't spend any time testing this but I'm guessing that this bug occurs specifically for `Glass` hatching potions if the player already has some `StainedGlass` Pets / Mounts (and _possibly_ also if they have some unused StainedGlass hatching potions).

If my guess is correct, it may be from the line of code below, which might trigger on  pet keys containing `StainedGlass` when it should be just triggering on pet keys containing `Glass` but NOT `StainedGlass`:
https://github.com/HabitRPG/habitica/blob/e8fd66f522fcdb2aef9d634885047c4d8606fe11/website/client/src/components/shops/buyModal.vue#L540

Again, I have not tested this, it's just a guess based on a quick look at the code. Any coder who wants to take up this issue should verify this with testing before starting to fix based on my idea. :)

Any fix should ideally NOT be specifically related to Glass and StainedGlass hatching potions. There could be other potions in future that exhibit the same problem, so a generic fix should be created (e.g., something using word boundaries in the key).

**Comment by majestic-owl448** [comment]
the easiest could be to use this for potions for potions
```diff
-if (petKey.includes(this.item.key) && petValue > 0
+if (petKey.includes('-' + this.item.key) && petValue > 0
``` 
and this for eggs
```diff
-if (petKey.includes(this.item.key) && petValue > 0
+if (petKey.includes(this.item.key + '-') && petValue > 0
```

or a regex that consider both like (it's to test if it works, it's just an idea for now)
```
petKey.match(new Regex('(-|^)' + this.item.key + '(-|$)'))
```

**Comment by Alys** [comment]
I've labelled this as important priority because it's stopping players from buying the potions because they don't realise that they can just click through the warning.

**Comment by majestic-owl448** [comment]
I can try to see if the regex works and in that case submit a PR with that

**Comment by majestic-owl448** [comment]
I went through with the testing, it seems it works with a Regex like I was thinking, it is set up already in case there will be eggs with similar names like it happened with `Glass` and `StainedGlass` but maybe it's overkill
https://github.com/ieahleen/habitica/tree/fix-overpurchase-warning-stainedglass-potions

I just need authorization to open a PR

**Comment by Alys** [comment]
@ieahleen Thank you! Please go ahead. :)
