### ISSUE TITLE
Daily colors not changing once dark red

### ISSUE THREAD

**Issue by mmarkey3** [HabitRPG/habitica#1336]
I had two of my dailies change to dark red over some time, and have done them every day since then.  No matter what, they won't move to orange, yellow, etc.  Seems like if you're good about doing a daily for 14 days straight, it should get back up towards yellow at least, no matter how long it was red.  The other tasks change just fine, but I also never let them get that bad.

Since there is a restore streak function now, I'll get around it for now by deleting and re-creating the task.

Edit: I see now that I'm hovering somewhere around -25 points, but...it wasn't the expected behavior.  I feel like the red-ness should cap somewhere....  Same with blue-ness, since if you do a task every day for months and then let it go for a long time, it should still be red when you come back.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by mmarkey3** [comment]
This probably belongs on the Trello boards as an issue of balance rather than a "bug" anyway. :3 Thanks for the rewrite, the new app works great!  I'll wait until progress is visible again to bring this up again, though, since that's sort of necessary to the underlying issue.
