### ISSUE TITLE
Backgrounds modal: When "Hide locked backgrounds" is on, year tabs are still there despite all backgrounds being on one page.

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#13373]
### Description
When selecting "Hide locked backgrounds" on the Backgrounds modal, all unlocked backgrounds are shown on one page - and this is definitely a feature, please leave that as it is! But the year tabs (2021 - 2014) are still there and can be selected as if the backgrounds were grouped by year. This is misleading and makes no sense. (The tab selection does not change anything, all tabs show the same complete collection of all unlocked backgrounds of all years, plus the free ones and the steampunk ones if they are unlocked.)

I'd suggest not showing the tabs when "Hide locked backgrounds" is switched on, or making them unclickable and changing the tab labeling, or otherwise making the design and text consistent with the fact that these are all unlocked backgrounds from all years (and the free ones and the steampunk ones if one has them) on one page. Also, while this is being changed, it would also be nice to give users a hint that this feature exists, by not just labeling the toggle "Hide locked backgrounds", but "Hide locked backgrounds and show all unlocked backgrounds on one page", or just "Show unlocked backgrounds on one page", or similar. (Otherwise one can just discover this very useful "side effect" by accident.)

In my opinion, this is a very low-priority bug with no need to fix it any time soon. But now it is documented here and can be linked to from the wiki and from "Ask a Question"/"Report a Bug" answering posts. And if there is ever a time when Habitica programmers got nothing more urgent to do or a new programmer wants to fix a small thing, this is on the list.

I created this issue with permission from @shanaqui after first discussing it in the Report a Bug guild.

### Screenshot Link (Temporary)
This screenshot is on snipboard.io and may therefore be deleted automatically after a while (if I understand correctly how snipboard.io works). But it can easily be recreated.

[https://snipboard.io/NxL37C.jpg](https://snipboard.io/NxL37C.jpg)

### General Info
  * UUID: 1aff9116-34b0-438c-9877-06038bdce161
  * Browser: Chrome, Firefox
  * OS: Windows

**Comment by fmachado091** [comment]
Hey, everybody, it's my first time around here. Can I work on this issue? Thanks!

**Comment by SabreCat** [comment]
I'm not sure that showing all the backgrounds in that state is intended, but it is rather convenient, here! So I'd agree, we can hide the unusable year navigation tabs in this scenario.

**Comment by majestic-owl448** [comment]
Can I work on this?

**Comment by SabreCat** [comment]
@ieahleen Sure! Marking as in progress.

**Comment by majestic-owl448** [comment]
I have not yet had the chance to start but I still intend to work on this

**Comment by CuriousMagpie** [comment]
@ieahleen Are you still working on this?

**Comment by majestic-owl448** [comment]
Yes, I had some family emergencies and health issues that distracted me - if it's urgent I can leave my claim for someone else

**Comment by CuriousMagpie** [comment]
Nope, no worries, @ieahleen! Thanks!

**Comment by majestic-owl448** [comment]
I'm sorry. I will not be able to continue working on this.

**Comment by CuriousMagpie** [comment]
Not a problem, thanks for letting us know.

**Comment by wllyng** [comment]
Hi would me and a partner be able to pick up this task? If so what would be a good place to start?

**Comment by CuriousMagpie** [comment]
Hi @wllyng, if you'd like to take this on, you're welcome to do so! A good place to learn about our tech stack is on [the Guidance for Blacksmiths page](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths) on the wiki and general questions can be posed in the [Aspiring Blacksmiths Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) in-game. Thanks for your help!

**Comment by wllyng** [comment]
Hi,
We found a fix for the bug but we were wondering if there exists UI tests in the test suite. In testing for the change should we just have mocha test for the absence of the year tabs by looking to see if the submenu class exists on the website?

**Comment by CuriousMagpie** [comment]
We normally test UI changes in the browser by using a local development server. Here are instructions for [setting up Habitica locally](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally).

**Comment by wllyng** [comment]
In that case would that mean that we wouldn't need to create automated tests for UI changes? We have tried testing the UI changes manually and it seemingly works!
