### ISSUE TITLE
Facial Hair modal: Locked facial hair set is shown as if it includes only the beards, not the mustaches.

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#13374]
### Description
According to the wiki (and my memories), if one buys the facial hair set, one gets all the facial hair (including mustaches). But on the modal, when locked, only the beards (not the mustaches) have a darker grey background. So it looks as if the set would only include them and as if one would not also get the mustaches when buying the set.

I think the locked set should optically include all the options on the tab, meaning, they should all have the darker grey background.

When asking about this bug in the "Report a Bug" guild, @shanaqui thought it possible that "there might be a design reason for this" (and tried to ask @SabreCat who could not be reached at that moment though), but could not confirm or exclude that possibility.

My own completely uninformed guess is that it might have something to do with beards and mustaches being combinable, i.e., there are two independent layers, one for the beard and one for the mustache, and this may somehow have contributed to them not being colored as one set. (But nonetheless I think it is a bug.)

In my opinion, this bug has low or medium priority, and there is probably no hurry to fix it. But now it is documented here and can be linked to from the wiki and from "Ask a Question"/"Report a Bug" answering posts, and can be found and fixed when there is nothing more urgent to do.

I created this issue with permission from @shanaqui after first discussing it in the Report a Bug guild.

### Screenshot Link (Temporary)
This screenshot is on snipboard.io and may therefore be deleted automatically after a while (if I understand correctly how snipboard.io works). But it can easily be recreated.

[https://snipboard.io/E20Lfz.jpg](https://snipboard.io/E20Lfz.jpg)

### General Info
  * UUID: 1aff9116-34b0-438c-9877-06038bdce161 (but the screenshot is from a secondary account, 6d49978e-d277-4dd8-a2a1-e1b8e5ae8c08 )
  * Browser: Chrome, Firefox
  * OS: Windows

**Comment by habitrpguser** [comment]
I think these are the code parts where one can see that buying the facial hair set buys beards as well as mustaches:

https://github.com/HabitRPG/habitica/blob/51e8aa341dc2d46aa102b3d9014b22584aa8a756/test/common/ops/unlock.js#L14

https://github.com/HabitRPG/habitica/blob/51e8aa341dc2d46aa102b3d9014b22584aa8a756/test/common/ops/unlock.js#L227-L243

**Comment by SabreCat** [comment]
Looking at the screenshot, I wonder if this was intended to be an alternate row highlighting to distinguish the separate layers you described. But I agree that in the situation where both rows are locked and available for purchase, it leaves the UI looking ambiguous. @Tressley what do you think the solution is, here?

**Comment by Tressley** [comment]
I am not sure there's an immediate solution. We do have plans for the customization shop so we can loop this in during those discussions. 👍🏻

**Comment by saraolson** [comment]
closing this as it's no longer relevant with the release of the customization shop
