### ISSUE TITLE
Set streak to 0 if it has no integer value 

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica#13372]
If someone edits their streak on web and saved the task with an empty field, that task will disappear on mobile. If they go back and type a 0 into the field, then the task appears normally again. We'd like to change the API so all platforms will always save the field as 0 if its empty to make sure this is fixed across all platforms for good.

original issue was posted to mobile, but we decided to make it an API change. Can reference that issue here: https://github.com/HabitRPG/habitica-android/issues/1569

**Comment by Alys** [comment]
The fix should apply to these routes:
+ [Create a new task belonging to the user](https://habitica.com/apidoc/#api-Task-CreateUserTasks)
+ [Create a new task belonging to a challenge](https://habitica.com/apidoc/#api-Task-CreateChallengeTasks)
+ [Update a task](https://habitica.com/apidoc/#api-Task-UpdateTask)

I suggest not applying it to [Create a new task belonging to a group](https://habitica.com/apidoc/#api-Task-CreateGroupTasks) as the Group Plans code is under redevlopment by the staff so the chance of conflicts is high.

The fix should ensure that if the user enters no value for the streak or enters a value that is not an integer, then the value entered by the user should be ignored and the Task schema's default value should apply (which is 0).

The fix should include tests for this behaviour for each route.

Note that it's possible that some of this already exists, so check the code first before you start writing new code. :)

**Comment by joeyzero** [comment]
I would like to tackle this.

**Comment by joeyzero** [comment]
Friendly reminder: I'd still love to work on this one.

**Comment by Alys** [comment]
@joeyzero Thank you! I've marked this as in progress for you.

**Comment by melvio** [comment]
Will this preserve negative integers? I like using negative integers such as `-1` to make my streaks a bit harder.

**Comment by saraolson** [comment]
@melvio im not 100% sure, but i think negative numbers may still work as they are an integer? on mobile, you've never been able to enter a negative number, but it can display one in task settings if you set a negative on web. i tested setting a habit to -5 on web then tapping the + on mobile, and it correctly updated to -4. 

@Alys do you know for sure if this solution would block negative values or not?

**Comment by Alys** [comment]
I haven't seen @joeyzero 's solution so I can't answer that yet. Once a PR is submitted, we'll be able to tell.

**Comment by melvio** [comment]
@saraolson That's exactly how I've been using it on the web :smile: .

**Comment by melvio** [comment]
Thanks @Alys :+1: . How is it going so far @joeyzero ?

**Comment by Lyqst** [comment]
I will take a look at this since there's no news if that's ok

**Comment by Alys** [comment]
@joeyzero How are you going with this? If you're no longer able to work on it due to other commitments, that's totally fine - just let us know!

@Lyqst We'll wait a couple of days and then if there's no reply, it'll be free for you to start on, thanks!

**Comment by Alys** [comment]
@Lyqst You're free to go ahead with this. Thank you!

**Comment by Lyqst** [comment]
Ok so I've added this line to the updateTask api code which does the trick:

```javascript
if (task.streak == undefined) task.streak = 0;
```

There's no need to change anything in the create api routes, since if no streak is sent the default 0 is used (also, there's no option to enter the streak when creating a daily task, neither web or mobile)
![image](https://user-images.githubusercontent.com/78376862/135166397-3a2fa265-5b66-446c-99ce-9b4df1ce4d4d.png)

On a related note, when testing I found that you can also enter and save a floating point value for the streak, which to me at least doesn't make much sense, and can also easily be dealt with just after the fix above with:
```javascript
task.streak = Math.trunc(task.streak);
```
I can add that to the PR if that's OK with everyone.

**Comment by SabreCat** [comment]
@Lyqst Apologies for the delay! I agree with your solution, we should definitely truncate any decimal values on this field. (Probably `===` for the undefined check, though)

**Comment by Lyqst** [comment]
Ah yes, I'll change that and create the PR.
