### ISSUE TITLE
Town Crier Bailey News (newStuff) API

### ISSUE THREAD

**Issue by wizonesolutions** [HabitRPG/habitica#1338]
`GET /api/v1/bailey`

So everyone can spread the good news...when it happens.

Need I say more? :D
##

**Comment by lefnire** [comment]
ah yes!

**Comment by Alys** [comment]
Comment from lefnire in https://github.com/HabitRPG/habitrpg/issues/3442#issuecomment-42719005 : "the news is currently straight html. Our goal is to move it to the database (kinda CMS, so our mods can edit it too) and expose that via a route, but it's pretty low prio so unless a contrib tackles it, it won't be any time soon"

**Comment by negue** [comment]
I think this could be done in two steps.
1. All Bailey Data is loaded of a static json file, once this works as expected...
2. create an api route to generate this specific json
3. a) create an interface to fill it OR b) directly in mongodb

For 1.

The current structure is like this?

Message Header

[multiple:]
- Part Title
- Part Content
- Part Picture

Am I missing something?

**Comment by Alys** [comment]
See also https://github.com/HabitRPG/habitrpg/commit/0b9c5271bb6d58c9b6c5035edebfa472c17f93e5#commitcomment-7525311 describing plans to move the Bailey New Stuff into the database, which would then make an API route easy to create.

**Comment by negue** [comment]
Oh nice, I guess I kinda missed that mail...

Thanks!

Btw, do we really need the "news" from day 1?

**Comment by lefnire** [comment]
I think for posterity we'll want to keep the old news entries. So after this feature is built, we'll probably need to do a data-entry sweep. @negue I hadn't thought of putting news in a static json file, that might be easier. We could have mods who want to edit the news simply submit PRs through Github's "edit file" web interface. It's a _tad_ technical (they have to fork, edit, PR) - but they never need to download / setup locally - kinda how translations are currently being handled.

Anyway, I see merit in both those options (CMS/db-entry vs static JSON)

**Comment by Alys** [comment]
In the Tavern, Lyranessie and janey_p were expressing interest in the Bailey News being translatable, which would add complications but seems like a good idea.

**Comment by deilann** [comment]
Iirc those translations go on.the wiki. Maybe it should be made more clear

**Comment by Alys** [comment]
Duh, of course they do. I remember that page now. :)  It needs some updates though: [Whats new](http://habitrpg.wikia.com/wiki/Whats_new). I'll mention it in the Tavern now and I expect some wiki editors will jump on it.

I do think that the Bailey news pop-up has a standard message pointing to that page, however we probably want to first improve the processes of keeping it updated and translated.

**Comment by negue** [comment]
So Bailey API with multilang support? or will the translated versions still inside the wiki?

We could also put a link inside the popup which has the target to the wiki page?

**Comment by paglias** [comment]
I think the interface label here is not needed. This is an API change. Also the priority should be medium considered that typos get a minor we want something more for this

**Comment by lemoness** [comment]
This ticket is very outdated, so I'm closing it for now! It can always be reopened if needed.
