### ISSUE TITLE
API token is invisible

### ISSUE THREAD

**Issue by Vsevo1od** [HabitRPG/habitica#1339]
It looks like this since I've registred. And there are no API Token in QR-code either
i.snag.gy/1sdRj.jpg

**Comment by lefnire** [comment]
bug. what's your uuid, i'll add one for you

**Comment by Vsevo1od** [comment]
Thank you!

7ce0f07e-96e5-466d-88e2-bd6a2939c613

**Comment by lefnire** [comment]
added for you
