### ISSUE TITLE
can't use Avatar Transformation Buffs (e.g., Seafoam) on all party members for parties over 30

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13394]
If your party has more than 30 members (e.g., due to a bug or because it was created before the party member limit), then you can use avatar transformation buffs such as Seafoam on only 30 of the members. There's two aspects to the bug:
- When you go to Inventory > Items and click on the avatar transformation item, you see the "Select a Party Member" modal and it contains only 30 members. There is no "Load More" button at the bottom for you to see the other party member(s).
- When you enter a player's name in the search form of that modal, it will show you that player if they happen to be one of the 30 in the list. It won't show you the player if they are not in the list of 30. This means you can't cast the buff on anyone who doesn't appear in the list.

This bug also happens in the Android app (we have an emailed report from User ID: 1f472d64-139c-4d34-832e-6b92e448c609).

**Comment by Alys** [comment]
This bug also happens in the Android app (we have an emailed report from User ID: 1f472d64-139c-4d34-832e-6b92e448c609).

**Comment by dabrowskif** [comment]
Hi, i can try to fix this.
[EDIT .1] Also, how do you want it to be done? Should i add Load More button to load all remaining members that have not been shown or maybe load all members instantly?
[EDIT .2] Also, i have found out that Party size can actually be 31. 30 members + 1 Party Leader. So when trying to cast transformation buff like Seafoam, even in newly created party with theoretically correct number of members, this bug appears.
I have just created 31 accounts, all in the same party (added manually in the website, not through database edit), and one account is missing from "Select a Party Member" modal, due to possibility of casting this spell on yourself.

**Comment by Alys** [comment]
@dabrowskif Thanks for volunteering for this! I've marked it as in progress for you. Regarding your questions, firstly I've copied them below so that they get emailed out to everyone who is following this issue (edits to comments don't send emails). I've added my answers under each one.

> [EDIT .1] Also, how do you want it to be done? Should i add Load More button to load all remaining members that have not been shown or maybe load all members instantly?

Use the Load More button for this. Groups (guilds and parties) never load all members instantly because for large groups that would create too much load on the database / website.


> [EDIT .2] Also, i have found out that Party size can actually be 31. 30 members + 1 Party Leader. So when trying to cast transformation buff like Seafoam, even in newly created party with theoretically correct number of members, this bug appears.

Huh. Interesting! The 30-member limit is meant to include the party leader. Thanks for mentioning that!


>  I have just created 31 accounts, all in the same party (added manually in the website, not through database edit), and one account is missing from "Select a Party Member" modal, due to possibility of casting this spell on yourself.

Casting the Buff on yourself should work the same way as casting it on any other party member.

**Comment by beffymaroo** [comment]
@dabrowskif Are you still working on this issue? Please let me know, and I can adjust labels if needed. Thank you!

**Comment by dabrowskif** [comment]
@beffymaroo Hi, i'm about to finish it. I need couple more days.

**Comment by beffymaroo** [comment]
@dabrowskif Thank you for replying, and no worries on needing a little more time, we appreciate your help!
