### ISSUE TITLE
Incorrect npm version installed during local setup of habitica on linux

### ISSUE THREAD

**Issue by shanewidanagama** [HabitRPG/habitica#13395]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 3243d86d-fe52-4ffc-80d5-17f495165e4c
  * Browser: Chrome
  * OS: ChromeOS but I'm installing the local copy of habitica in the Linux container inside ChromeOS which is Debian GNU/Linux 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

I'm trying to install habitica locally on linux. I successfully installed the correct version of nodejs but despite following the instructions to install npm 6, "npm --version" says the version is 7.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

Here is the github gist of all the commands I've used: https://gist.github.com/shanewidanagama/a35fbecd8eb923a171e47911a7a5a1b1.

**Comment by Alys** [comment]
Based on the details that I've copied from your gist to below, it looks like you have a couple of node versions installed, and that npm 6 was installed, so I'd guess that the only problem is that one of the node versions is causing npm 7 to take precedence. You might want to use nvm to manage multiple node/npm versions.

Note that for Habitica, it's best to use only the node and npm versions listed in the "Setting up Habitica Locally..." pages on the wiki. For Linux, please see the "Install Node and NPM" section in [Setting up Habitica Locally on Linux](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux). That section tells you the correct versions and gives you a link to nvm. Once you have the correct node version installed, the npm 6 vs 7 problem might disappear - if not, nvm should help.

Can you go through that section in detail and then if you still have trouble, post again here?

```
shane@penguin:~$ node --version
v15.14.0
shane@penguin:~$ nodejs --version
v12.22.2
shane@penguin:~$ npm --version
7.7.6
shane@penguin:~$ sudo npm install -g npm@6
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.13
updated 1 package in 17.93s
shane@penguin:~$ npm --version
7.7.6
```

**Comment by melvio** [comment]
What helped me is to use `nvm use 14.0` instead of `nvm use 14`:
```bash
# use 14 gives me an npm that is too new: 
$ nvm use 14
Now using node v14.16.0 (npm v7.20.1)

# use 14.0 does give me npm 6 
$ nvm use 14.0
Now using node v14.0.0 (npm v6.14.4)
```
I'm on ubuntu 20.04 though, so your mileage may vary.

**Comment by SabreCat** [comment]
Based on what I've seen here so far, this is unlikely to be an issue with Habitica code. We can reopen if it proves to be otherwise!
