### ISSUE TITLE
Different types of characters

### ISSUE THREAD

**Issue by ebressert** [HabitRPG/habitica#134]
Would it be possible to have different characters to select from, e.g., a mage, warrior, etc? Additionally, it would be great if different subjects of the goals could add to different experiences like strength, magic, intellect, and dexterity. For example, if you have exercising as one of your daily tasks your strength experience goes up.

**Comment by lefnire** [comment]
see #74

**Comment by ebressert** [comment]
Nice to see that it is already in the works! Sorry for the double issues report.

**Comment by lefnire** [comment]
np!
