### ISSUE TITLE
Mobile App Custom Day Start

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#1340]
To my knowledge, it appears that the custom day start does not work on the mobile app. My day should have reset at 3am. I went on the site around 1:50am and everything was still the same as it had been, all day. But then I accessed the mobile app, which showed everything reset as if it was a new day: my dailies had reset and I'd lost health from the dailies I hadn't checked off earlier. I refreshed the actual site after that and it reflected the mobile app, moving on to the next day too early.

**Comment by lefnire** [comment]
let's log mobile bugs against https://github.com/HabitRPG/habitrpg-mobile/issues

yeah, this one is https://github.com/HabitRPG/habitrpg-mobile/issues/48 - pretty big issue, I'm gonna solve it today. On the up-side, this fix should solve any timezone issues once and for all - and API consumers (3rd party apps) can finally start using cron!
