### ISSUE TITLE
Bug: Search guild should clear when you’re rap on guild

### ISSUE THREAD

**Issue by skywinder** [HabitRPG/habitica#13430]
iOS;

Im searching guild. Then start to browsing guild,challenges etc and search bar didn't disappear. But its already irrelevant to screen ![image](https://user-images.githubusercontent.com/3356474/128620809-5a3ad737-fb77-4984-9612-1283a8d1a02e.jpeg)

![image](https://user-images.githubusercontent.com/3356474/128620814-a4cc1a37-de6a-4fd3-a12e-a48a298b243d.png)

**Comment by Alys** [comment]
Can you please report this to the mobile team through the app's menu at About > Report a Bug?  That will send debugging information to them.
