### ISSUE TITLE
Tags Wont Delete In App

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica#13458]
sjaarestad13@gmail.com

Device: samsung SM-J337P
Android Version: 28
AppVersion: Version 3.3.2 (3041)
User ID: dbf5390d-6a57-42ad-ae14-af8fd8e570ca
Level: 44
Class: wizard
Is in Inn: true
Uses Costume: true
Custom Day Start: 4
Timezone Offset: 420

Tags will not delete in app, despite reloading content and uninstallling/reinstalling app.

**Comment by Alys** [comment]
Can you please report that to the mobile team through the app's menu at About > Report a Bug?  That will send debugging information to them.
