### ISSUE TITLE
I cannot see any text no matter what I do.

### ISSUE THREAD

**Issue by wondrousweeb** [HabitRPG/habitica#13457]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: Opera GX
  * OS: Windows 11

### Description
Here are some screenshots of the issue:
![image](https://user-images.githubusercontent.com/70597482/130211080-2b638908-8afb-4e04-a81e-d14dd8e27c1a.png)
![image](https://user-images.githubusercontent.com/70597482/130211089-4b60c3e1-d659-4e78-a33b-cc722801fe50.png)
![image](https://user-images.githubusercontent.com/70597482/130211093-259c54f3-cba7-49a0-8d78-c36d92111615.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by majestic-owl448** [comment]
have you tried in a different browser? in incognito mode?

**Comment by wondrousweeb** [comment]
Hey, sorry for not replying early, I got busy with exams
And, it seems to have been fixed now. Earlier, I did try it using incognito mode, and it worked that way too. So I tried to delete cookies and cache files but that didn’t work either. However, it’s fixed now. Thanks a lot :D

**Comment by Alys** [comment]
@wondrousweeb Thanks for letting us know it fixed itself! If you have any further problems, please post to the Report a Bug guild, which you can reach from the Help menu on the website (there's a reminder about that in the template that you see when you click "New issue" here). We use GitHub issues only for problems that need code fixes. The issue you had was probably just that your browser hadn't correctly downloaded all the website's files.

@ieahleen Thank you!
