### ISSUE TITLE
Missing checklist information in API-docs

### ISSUE THREAD

**Issue by melvio** [HabitRPG/habitica#13450]
### background
This issue is in response to the suggestion of @Alys in the Comrade guild chat.

### Description
*Summary:* Checklist information is missing in the habitica [API-docs](https://habitica.com/apidoc/)

#### 1. CreateUserTasks endpoint
The API-docs for <https://habitica.com/apidoc/#api-Task-CreateUserTasks> are missing the `checklist` body parameter.
The wiki does give a good example here [source](https://habitica.fandom.com/wiki/Application_Programming_Interface):
```bash
$ curl -X POST \
    # ...
    -d '{
    "checklist": [
            { "text": "1st checklist item", "completed": false },
            { "text": "2nd checklist item", "completed": false }
        ],
```

![apidocs](https://user-images.githubusercontent.com/31448155/129471651-c88036a3-02a5-4ae5-9aa2-71d989f51191.png)

#### 2. AddChecklistItem and UpdateChecklistItem endpoint
As I was writing this down, I noticed that other endpoints are also missing information that is implicitly mentioned in the wiki.
For example, <https://habitica.com/apidoc/#api-Task-AddChecklistItem> does not make mention of `<completed>` body parameter. It is also unclear if the <https://habitica.com/apidoc/#api-Task-UpdateChecklistItem> supports the `<completed>` body.

**Comment by melvio** [comment]
@Alys I can contribute to this myself :wink:. I'm not a frontender, and I haven't used Vue.js before, so it will require time and effort on my part. However, every blacksmith gotta start somewhere right:sweat_smile:? @Alys do you want me to pick this up?

**Comment by Alys** [comment]
@melvio Thank you, yes, please go ahead!

**Comment by melvio** [comment]
Awesome @Alys. I've arranged that I can work on this ticket this weekend. Should I assign it to myself, or do you do that? (I'm not sure what the normal procedure is).

**Comment by Alys** [comment]
@melvio See [Using Your Local Install to Modify Habitica's Website and API](http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) for the full process (it has a fair bit of useful information) but in brief once an admin has said you can work on an issue and has set its label to "status: issue: in progress", then you can start. Admins have GitHub's "member" badge.

**Comment by melvio** [comment]
Thanks @Alys. I managed to run habitica. Which was a breeze with the tips listed over here <https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Docker>. I basically only had to fork the project, run `cp config.json{.example,}` and run `docker-compose -f docker-compose.dev.yml up -d` and I was good to go. 

The output looks as I want it to be on <localhost:3000/apidoc>. 

For example: 
![apidocs-update1](https://user-images.githubusercontent.com/31448155/131213203-e8ac8b77-5d68-4bcd-ab88-9c78b7ebcaeb.png)


And:
![apidocs-update](https://user-images.githubusercontent.com/31448155/131212624-81b7ad6a-49ca-4411-bfd0-4d1b55964fd7.png)

However, the commit I was working from was already getting a few days old. 
I've checked it out Wednesday the 18th of August (10 days ago) (commit: `ca185f019839555d9c9dfa67c5a283e83b53b838`).
However, I didn't work on it till this morning, so I've updated the code to be up to date with `develop` (commit: `5b346690a9cde8a09afaa3ec9770da46e918e8e6`).

Unfortunately, now the docker container `habitica-server` dies consistently after starting after a few seconds.

I think that `docker-compose logs server` gives us the error:
```
Attaching to habitica_server_1
server_1  | 
server_1  | > habitica@4.203.1 start /usr/src/habitica
server_1  | > gulp nodemon
server_1  | 
server_1  | [09:05:19] Using gulpfile /usr/src/habitica/gulpfile.js
server_1  | [09:05:19] Starting 'nodemon'...
server_1  | [09:05:19] Finished 'nodemon' after 56 ms
server_1  | [09:05:19] [nodemon] 2.0.4
server_1  | [09:05:19] [nodemon] to restart at any time, enter `rs`
server_1  | [09:05:19] [nodemon] watching path(s): *.*
server_1  | [09:05:19] [nodemon] watching extensions: js,mjs,json
server_1  | [09:05:19] [nodemon] starting `node ./website/server/index.js`
server_1  | 2021-08-28T09:05:28.591Z - info Express server listening on port 3000
server_1  | 2021-08-28T09:05:28.613Z - info Connected with Mongoose.
server_1  | npm ERR! code ELIFECYCLE
server_1  | npm ERR! errno 1
server_1  | npm ERR! habitica@4.203.1 start: `gulp nodemon`
server_1  | npm ERR! Exit status 1
server_1  | npm ERR! 
server_1  | npm ERR! Failed at the habitica@4.203.1 start script.
server_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
server_1  | 
server_1  | npm ERR! A complete log of this run can be found in:
server_1  | npm ERR!     /root/.npm/_logs/2021-08-28T09_05_37_346Z-debug.log
```
@Alys Do you know what happened in the past few days that could cause `npm/nodemon/gulp` to fail inside the `habitica-server` container? 
Getting habitica to run 10 days ago was really surprisingly easy so it might have to do with version bumps performed by the @dependabot ?

Note: I've also attached the results of the client (`docker-compose logs --no-color client > docker_client_logs.txt`) but I see no errors there. 
[docker_client_logs.txt](https://github.com/HabitRPG/habitica/files/7070466/docker_client_logs.txt)

**Comment by SabreCat** [comment]
@melvio I thought it only affected production environments, but there does appear to be an issue with a recent Dependabot upgrade to `storybook`. Can you try building with the latest commit from `develop` or `release` instead of the 4.203.1 tag?

**Comment by melvio** [comment]
Hey @SabreCat Great to meet you :smiley:. I am building with the most recent `develop` version (`5b346690a9cde8a09afaa3ec9770da46e918e8e6`). 
It has the commit message `fix(storybook): temporarily disable story` and it gives me the error listed above. 

To be sure, I also asked `docker-compose` to clean up thoroughly:
```bash
docker-compose --file docker-compose.dev.yml up --force-recreate --always-recreate-deps --remove-orphans --detach
```

Unfortunately, the response is the same:
```
$ docker logs habitica_server_1 

> habitica@4.203.1 start /usr/src/habitica
> gulp nodemon

[06:29:39] Using gulpfile /usr/src/habitica/gulpfile.js
[06:29:39] Starting 'nodemon'...
[06:29:40] Finished 'nodemon' after 47 ms
[06:29:40] [nodemon] 2.0.4
[06:29:40] [nodemon] to restart at any time, enter `rs`
[06:29:40] [nodemon] watching path(s): *.*
[06:29:40] [nodemon] watching extensions: js,mjs,json
[06:29:40] [nodemon] starting `node ./website/server/index.js`
2021-08-29T06:29:45.815Z - info Express server listening on port 3000
2021-08-29T06:29:45.836Z - info Connected with Mongoose.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.203.1 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitica@4.203.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I do notice the `npm ERR` message stating the `habitica@4.203.1 start script` part.      
Besides checking out the most recent commit with git, do I also need to modify the `package.json`'s `"version":4.203.1"` " to run a more recent version?

PS: I also tried `release` but the errors are identical.

**Comment by melvio** [comment]
I tagged the most recent version of habitica on my `melvio/habitica` repo with `4.203.2`.   
I incremented the package.json version string to `"version": "4.203.2",`. (just locally, I did not push)

I ran docker-compose with the `--build` flag this time:
```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --force-recreate --build
```

Unfortunately, the error message remains the same:
```
> habitica@4.203.2 start /usr/src/habitica
> gulp nodemon

[07:10:21] Using gulpfile /usr/src/habitica/gulpfile.js
[07:10:21] Starting 'nodemon'...
[07:10:21] Finished 'nodemon' after 53 ms
[07:10:21] [nodemon] 2.0.4
[07:10:21] [nodemon] to restart at any time, enter `rs`
[07:10:21] [nodemon] watching path(s): *.*
[07:10:21] [nodemon] watching extensions: js,mjs,json
[07:10:21] [nodemon] starting `node ./website/server/index.js`
2021-08-29T07:10:27.222Z - info Express server listening on port 3000
2021-08-29T07:10:27.255Z - info Connected with Mongoose.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.203.2 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitica@4.203.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

@SabreCat Is this what you meant with
> building with the latest commit

 
Or am I misunderstanding you?
Thank you for your help @SabreCat  :smiley:

**Comment by SabreCat** [comment]
Nope, that's exactly what I wanted to check--that it was using the commit with `storybook` disabled. Hrm. Is there any way to get a more verbose error output? And/or do you have a known good commit you can reset to and step forward from, to identify when the issue started?

**Comment by melvio** [comment]
I would have to check tonight after work. (I'm in the GMT+2 timezone). 
`npm` is reporting that the `gulp nodemon` is failing, so I assume a verbosity flag can be set somewhere here :slightly_smiling_face: .
And if that doesn't work, I can bisect which commit introduced this issue. But I cannot promise that will be done this working week, I'll try, but this probably something that will happen next weekend :innocent: .

**Comment by SabreCat** [comment]
You can try merging #13465 which cleans up some build issues, see if that helps! It'll be on `develop` soon.

**Comment by melvio** [comment]
Perfect timing @SabreCat :smiley: I just tried `gulp -LLLL nodemon` instead of `gulp nodemon` to get some extra information:
```
  --log-level, -L         Set the loglevel. -L for least verbose and -LLLL for
                          most verbose. -LLL is default.                 [count]
```
But I got the same output; So you're just in time with your advice. I'll try it right now.

**Comment by melvio** [comment]
Unfortunately, still no luck. I ran:
```
git pull upstream fix/storybook_install
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --force-recreate --build
```
But I still have the same issue. The `habitica-server` container dies after a few seconds with the same logs.

**Comment by melvio** [comment]
Okay.. don't ask me why. But It works now. 

I ran:
```
$ nvm use
Now using node v14.0.0 (npm v6.14.4)

$ docker-compose -f docker-compose.dev.yml up -d --force-recreate --build
```
The `nvm use` should not matter because I'm running docker containers. 
I also pushed the changes from `fix/storybook_install` to my own repo (instead of just pulling).
However, I really don't see how the above should have made an impact, but I'm  not complaining :smile:
