### ISSUE TITLE
HTML application-wide broken.

### ISSUE THREAD

**Issue by rliebig** [HabitRPG/habitica#1347]
Hello,

unfortunately, the /static/front-site doesn't have a `<html>` tag at all and doesn't opens the `<body>`-Tag, but closes it. 

The active pages are more interesting. The body tag isn't present at all, as the html tag. However the head-tag is closed, but two times.

**Comment by lefnire** [comment]
Hmm, I can't replicate ([screenshot](https://www.evernote.com/shard/s17/sh/7209b414-f18f-4a8b-84e6-995be18745d7/6cb3b230b9c9008f895a2309a9e215dd)). Where you seeing this? Is it causing render issues for you?

**Comment by rliebig** [comment]
Beware, Firebug shows the current representation of the Site(See [documentation](http://getfirebug.com/html), "Firebug's HTML tab shows you what the HTML looks like _right now_."). Under Firefox you can use CRTL-U to see the actual HTML, sent by the server. Browser have become very good at parsing invalid HTML, but I can't see a reason why one should deliver it.

Fortunately, I isn't causing any render/usage issues to me(, yet ;) ).

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
