### ISSUE TITLE
Letting the player balance the game

### ISSUE THREAD

**Issue by Senth** [HabitRPG/habitica#1349]
**The story**
Every user plays habitRPG differently, some have many habits, dailies and todos, others only have larger sets of habit goals. For example I have 9 active dailies, 6 habits and usually complete over 10 todos every day since I also use it for my work as I'm self-employed. Other users might only have 2-3 really important dailies, 1-2 habits and really important todos. I've test both approaches and I like dividing them into lots of smaller tasks.

**The problem**
I think I get way too much gold and experience and it feels like cheating, although I rarely have enough money to buy items as I have balanced by own rewards as 1h of freetime costs 10g or 4g on the weekend. While those that only have very few tasks might get very little exp and gold, and even drops. The essential problem is that the users aren't balanced and thus it's easier or harder for some to get items and level and could feel unfair or like cheating.

**The solutions**
1. Let the user set an exp/gold/item drop rate. E.g. I'd probably set mine to 60-75%, while others would set it to 150%. Yes I know this would allow you to cheat, but you already can cheat if you want and the only one you cheat is yourself. This is relatively easy to implement if you have the exp/gold/item drop calculation in one place. The player would be allowed to set this in the settings.
2. Automatically calculate the rate depending on how many habits (including upvotes), dailies, and todos the player usually have/complete during a day and take the mean over a week. A bit harder to implement, and requires more computation, but you will still be in control over the system.
3. Combination of 1 and 2.

**Open questions**
What about health, would the amount of damage also be reduced? Probably, but I don't mind for it to be harder. Health loss could be a profile difficulty setting linked to the death mechanic feature https://trello.com/c/k2MWBcxl/204-death-mechanic

**Comment by DanielTheBard** [comment]
I agree with the feeling that I'm cheating by having a lot of stuff (I'm pretty sure I have around 25+ dailies). However, I don't agree that this is the way to go about solving it.

**Comment by wc8** [comment]
You can weigh in 
here: http://community.habitrpg.com/content/should-game-difficulty-be-adjustable-or-normalized-httpgoogl2tzve
here: http://community.habitrpg.com/content/habitrpg-too-easy
or here: #325 Difficulty Normalization

**Comment by wc8** [comment]
I added links to this discussion on [Death Mechanic](https://trello.com/c/k2MWBcxl), and am closing for housekeeping.
