### ISSUE TITLE
[Feature Request] User Specific Timezones

### ISSUE THREAD

**Issue by timothyCoxon** [HabitRPG/habitica#135]
Okay so it's 8:42am on the 20th Jan for me and my dailies are still greyed out. 
I guess Habitrpg servers are based somewhere in America but I am in the UK so run GMT. 
It would be nice if each user could set their own timezone.

**Comment by timothyCoxon** [comment]
Hmm Think this maybe the same as #121

**Comment by GoldFroggy** [comment]
I'd like to second this - I'm in Australia, which means that at 4pm each day the app thinks it's midnight the day before and pounds me for not completing dailies.

**Comment by lefnire** [comment]
let's follow up on #30
