### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by cybrpimp** [HabitRPG/habitica#13510]
We have recently installed using Docker on the guide.

![image](https://user-images.githubusercontent.com/61793417/133672162-24137371-b781-4fad-9f38-30bbad9d4428.png)

[//]: # (Bugs in the mobile apps can also be reported there.)

**Comment by NicolasCARPi** [comment]
What makes you think this is an issue with the software and not the free space on your disks. What is the output of `df -h` ?

**Comment by cybrpimp** [comment]
@NicolasCARPi We had plenty of space on the system drives.  It turns out that Docker has some type of cache that fills up and needed to be cleaned.
