### ISSUE TITLE
Link in Re-Roll modal doesn't go anywhere informative

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1351]
Silly of me not to notice this while I was working on the modal (I copy-pasted the link from the previous content), but the link mentioning the incentive value of red tasks just redirects to the Habit repo here on GitHub.

I'd fix this myself, but I don't know where that page actually is! There doesn't seem to be a corresponding FAQ entry on the topic.

**Comment by lefnire** [comment]
Goodness I'm a mess, yeah I don't know where the original page is either. We can just nix that link methinks

**Comment by SabreCat** [comment]
Will do!

**Comment by SabreCat** [comment]
This got taken care of at some point during the rewrite. Closing!
