### ISSUE TITLE
Day Didn't Progress. Dailies Didn't Reset

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#1353]
I can't tell if this is on purpose, temporarily, or a bug. But my health and dailies didn't adjust for today. All the dailies I checked off yesterday are still checked off. Nothing reset. I'm not resting in the inn so I'm not sure what happened.

**Comment by lefnire** [comment]
let's follow up on https://github.com/HabitRPG/habitrpg-mobile/issues/73 . Can you post your UUID there?
