### ISSUE TITLE
Selection highlight in avatar editor carries over between tabs

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13543]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Chrome 94.0.4606.61
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When selecting a skin on one tab of the avatar editor window, then changing tabs to the hair colors, the corresponding colored hair has an incorrect selection highlight (in addition to the hair color the user actually has selected):

https://user-images.githubusercontent.com/4501321/136256665-ff190857-ee20-4c73-b1a8-7210919bcc6f.mp4

Only the actually equipped style should have the border in this scenario.

**Comment by SandraBiros** [comment]
Hello can I work on this issue ? Please assign me.

**Comment by kartiks26** [comment]
heyy if this issue is not resolved yet then please assign to me i can work on this. @SabreCat

**Comment by SabreCat** [comment]
@SandraBiros, you're welcome to have a look! Reach out to us here or in the Aspiring Blacksmiths Guild with any questions you have!

**Comment by SabreCat** [comment]
@kartiks26 Sandra stepped in first, but if they can't get it figured out we'll tag you in!

**Comment by twjasa** [comment]
Hello you all, 

Can I take this? If @SandraBiros or @kartiks26 dont mind :)

**Comment by kartiks26** [comment]
@twjasa  i am not assigned

**Comment by SabreCat** [comment]
We haven't heard from @SandraBiros in a while; @kartiks26, if you're still interested, feel free to look into it!

**Comment by CuriousMagpie** [comment]
@kartiks26 Are you still working on this?

**Comment by kartiks26** [comment]
> 

nope

**Comment by vanathi-g** [comment]
Hey, may I work on this issue if no one else is currently working on it? @CuriousMagpie

**Comment by CuriousMagpie** [comment]
Go for it, @vanathi-g!
