### ISSUE TITLE
Issues with Habits and To-Do's

### ISSUE THREAD

**Issue by nerdmagnet** [HabitRPG/habitica#1354]
Close to every other time I log into my account and go to do something, anything, with my habits (it doesn't seem to be happening to the other three columns yet), weird things happen. My bottom-most habit, when I click on "progress", it won't open, but it will open if I click the "progress" button on the habit above it. I can only view the chart for the bottom-most one, not the one I click on when that happens. Sometimes it won't let me click on things at all in habits, and when that happens, I'm kicked off the game.

With To-do's, more times than not I have to submit things a few times for them to register, and other times I'll click submit and half of what I wrote will disappear.

**Comment by DanielTheBard** [comment]
Just tried it on mine. Not seeing that habit problem. I can open up the progress for all my habits. Your second problem is most likely just due to the frequent connection problems the site has. No way to get around it other than to refresh after you do stuff to make sure it saved.

**Comment by SabreCat** [comment]
I think the progress bar issue has to do with it too, or at least is hooked into the same ongoing Derby headaches. I usually find that if a given icon isn't responding, a refresh clears it up.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
