### ISSUE TITLE
Died (although I bought and used a potion)

### ISSUE THREAD

**Issue by Texasmama** [HabitRPG/habitica#1355]
I'm very frustrated - I deliberately went in earlier yesterday and bought (and used) a potion so I would not die....and somehow - I log in this morning to see I died...in spite of all that.

About ready to give up on this game - so sick of it being down a lot - and now to have this happen when I deliberately tried to avoid it (after dying before) - just really sucks.

**Comment by octern** [comment]
Possibly similar issue today: Had 2 HP. Realized I'd engaged in a bad habit but decided to let myself buy a potion before taking the hit. Used the potion, saw my HP go up, then hit the minus, lost 2 HP and immediately died. I believe it was on a fresh reload but I'm not sure (and also not sure whether that would matter).

**Comment by octern** [comment]
BTW, you can use the "restore" option under Settings to manually get back your level and gold.

**Comment by Shaners** [comment]
Sorry to hear that Texasmama. We're working to resolve these types of issues but we aren't quite there yet. Feel free to restore your lost progress as octern has pointed out. Settings > Danger Zone: Restore.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
