### ISSUE TITLE
Invalid certs.

### ISSUE THREAD

**Issue by WoahdangJr142** [HabitRPG/habitica#13560]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: Inaccessible
  * Browser: Opera GX
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Invalid cert
![image](https://user-images.githubusercontent.com/68622581/137650104-f3394f12-e9db-4752-9f2b-ad393163b854.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by WoahdangJr142** [comment]
I can't get into the site at all.

**Comment by WoahdangJr142** [comment]
Also when I try to run a script it tells me invalid certs, so I'm assuming it's not just me.

**Comment by Tranquilitea** [comment]
Having the same trouble, on Windows 10, but with Firefox.

Additionally, when I use the Android app, (in this instance to +1 a habit) it fails to update, and there's a brief pop-up saying "Server connection lost".

Hope this helps. :)

**Comment by WoahdangJr142** [comment]
Yeah, on my phone it also says invalid certs

**Comment by bauerbach** [comment]
I can't access the site either! Please fix this ASAP; I NEED Habitica back!

**Comment by cygnoir** [comment]
This is happening to me as well, running macOS Big Sur (11.6). Here's a screenshot from Safari. 

<img width="701" alt="Screen Shot 2021-10-17 at 17 52 01" src="https://user-images.githubusercontent.com/1072244/137652156-fe69aecd-01d1-4757-86a3-a03ff2b2f851.png">

**Comment by ozw-sei** [comment]
This is happening same issue, Windows 11 Google Chrome.

**Comment by blankoon** [comment]
Same here

**Comment by danndylan** [comment]
I think its up and running again. In Windows 10 Google Chrome at least

**Comment by ClementTsang** [comment]
Seems to be resolved on my end as well, for both my browser (Linux, Firefox) and for actions on the Android app.

**Comment by blankoon** [comment]
Yeah, it's resolved on my end, too. 
The problem seems to be resolved because the certificate be set up.

![스크린샷 2021-10-18 오전 10 35 38](https://user-images.githubusercontent.com/28880021/137656156-fd206f28-291b-47f2-89e5-86d5e4bd4936.png)
