### ISSUE TITLE
Insane memory use when loading habit in chrome

### ISSUE THREAD

**Issue by Fitzwibble** [HabitRPG/habitica#1356]
I'm seeing a +1.5 GB spike in my active system memory when I have habit and beta.habit open in chrome. I tested it briefly in Firefox and I don't appear to be seeing the same spike. I'm on a mac running os 10.6 if it's pertinent.

The task I'm seeing at the top of my activity monitor when the spike happens is "google chrome renderer" if it helps

**Comment by lefnire** [comment]
That'll be fixed in the rewrite (http://habitrpg.tumblr.com/post/59104876969/website-issues-what-were-doing) Naught that we can do right now, unfortunately

**Comment by gwillen** [comment]
This is still somewhat bad post-rewrite. I'd be curious to hear what @Fitzwibble is seeing, but for me Habit is using anywhere from half a gig to a whole gig of ram regularly, which is more than all my other tabs put together. Every morning if I've left it open overnight, the garbage collection stall while it remembers itself takes many minutes.

**Comment by lefnire** [comment]
make sure to always clear your completed todos (bottom tab of todos column). beyond that, follow https://github.com/lefnire/habitrpg/issues?labels=performance&milestone=&page=1&state=open for our progress

**Comment by gwillen** [comment]
It would be nice if it were possible to keep todo history without keeping it all in RAM forever.

Failing that, it would be nice if there were a warning somewhere that you have to clear them to save RAM.

I'll go try that.

**Comment by paglias** [comment]
Partly are the todos but memory usage is going up anyway (I easily reach 400-500 mb opening the options page and checking some dailies, with 0 todos).

Surely always keeping the tab open is not helping in the long term but the app itself is very complex, browser garbage collection (removing objects not used from the RAM) is probably not perfect, too.

I would suggest closing the tab after some time
