### ISSUE TITLE
De-decimalize Health and Experience

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1358]
One complaint I occasionally hear about Habit is that it feels too technical--like users must frequently interact with the code-like guts of the app. The main offenders here are UUIDs/API Tokens and the current necessity of frequent interaction with Restore features, but overall it might behoove us to keep an eye out for opportunities to prettify things that look like glimpses of the back end.

A simple change that might help here would be to remove decimal places from Health and Experience. Most RPGs don't use decimal places, and decimals tend to give things a technical/scientific feel. We could preserve the current algorithms almost unchanged if we round to what's now the first decimal place, and multiply all these figures by 10. So a level 1 character would have 500 health, need 1500 XP to level up, lose 20 HP for indulging a bad habit, and gain some 75 XP for completing a typical task.

Decimals are OK for gold. People are used to dollars and cents, and the mapping of decimal gold to Silver is pretty cool.

**Comment by octern** [comment]
I agree with the premise here, but I'd prefer to keep the current order of magnitude for HP / XP / gold and just have quantities be a little coarse-grained. Right now, the numbers are roughly appropriate to the 8- or 16-bit console RPGs that HabitRPG is meant to evoke. Multiply everything by 10 and you get numbers that look like more modern, score-inflated games.

**Comment by SabreCat** [comment]
I could see that, but I feel like we'd lose quite a bit if we just dropped the fractions outright. It's kinda nice to see the difference, when hitting a Habit multiple times, that diminishing returns (or worsening punishments) are taking effect click by click. Under a decimal-floored scheme, you'd only see breakpoints after quite a few taps.

500 health, and XP in the low to middling thousands, feels very _Chrono Trigger_ or _Final Fantasy IV_ to me*. Granted, it's more expressive of a character in the midgame of one of those than somebody just starting out. But that's not so bad, given that Health currently doesn't increase over time, and the XP expansion is more modest than in one of those games.

*http://strategywiki.org/wiki/Chrono_Trigger/Experience
http://strategywiki.org/wiki/Chrono_Trigger/Stat_Gains/Crono
http://strategywiki.org/wiki/Final_Fantasy_IV/Characters#Cecil

**Comment by octern** [comment]
Now that I think about it, I agree with you. 500 HP still seems high to me, but it's better than the current situation where HP effects are shown with one decimal place, and HP actually has multiple decimal places, but the displayed value is rounded to a whole number. And representing XP in a manner similar to any classic game is going to be a lost cause, since the nature of HRPG calls for a slow linear progression in XP-per-level, whereas most games have the requirements increase much more dramatically.

**Comment by wc8** [comment]
https://trello.com/c/W46gHos0
