### ISSUE TITLE
[Feature Request] Google Login

### ISSUE THREAD

**Issue by timothyCoxon** [HabitRPG/habitica#136]
Any chance of a "login via google" feature?

**Comment by lefnire** [comment]
hey @timothyCoxon, that'll come once this is tackled: https://github.com/lefnire/derby-auth/issues/16 (which is also my project, so hopefully i'll find some time!)

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by larsrc** [comment]
For the record, lefnire is no longer working on derby-auth, so this feature cannot expect to come out of that. It should be done on its own.

**Comment by deilann** [comment]
The site is also no longer using derby, so it's unrelated.

However, I know that Google Auth is not going to be implemented until the recurring issues with Facebook Auth are sorted out.

**Comment by larsrc** [comment]
That's a shame - implementing Google Auth would make it possible to sync with Google Tasks, making it easier to move from any of a number of task management systems to HabitRPG.

**Comment by deilann** [comment]
And it would also greatly increase the workload on the staff, as there are
many problems with Facebook auth that require Tyler's intervention
regularly.
