### ISSUE TITLE
Helm not showing on character

### ISSUE THREAD

**Issue by mattbob** [HabitRPG/habitica#1360]
I purchased the first helm and a while ago but a few days ago it disappeared from my character. The settings still said Helm was at 1. I now bought the 2nd helm and the settings show Helm is at 2 but it still doesn't appear on my character image.

**Comment by Shaners** [comment]
Is it possible that you changed this option?
![showhelm](https://f.cloud.github.com/assets/2374703/1018752/5625623c-0c31-11e3-937c-30c0db5bc6c7.png)
Maybe try clicking and unclicking that.

**Comment by mattbob** [comment]
Well I feel stupid. Thanks! Not sure when I would have clicked that but that was my problem.

**Comment by Shaners** [comment]
@mattbob well very possible that you didn't click it. I know in the past some player settings got fuddled with when certain things happened like creating a guild changed your gender. Or could have accidentally hit a key without realizing it.
