### ISSUE TITLE
Dailies Not Resetting

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#1361]
I checked off my dailies three days ago, and they're still showing as grey and checked, I haven't been able to enter my daily activities for the last three days.  Thank you for all the work you do on HabitRPG!

User ID: 572fdfa8-bac7-423f-9bd1-90eb8e04cb72
Browser: Safari 5.0.6

**Comment by lefnire** [comment]
Investigated your account - looks like you're resting in the inn, go to Options > Tavern and click the button to check out. It won't take effect till the next day ([see "why" discussion here](https://trello.com/c/A2w2orSc/14-rest-in-tavern)).
