### ISSUE TITLE
Language is not correct on habitica webpage

### ISSUE THREAD

**Issue by FirstLoveLife** [HabitRPG/habitica#13629]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: ef3f1e96-dcbd-4036-a8cd-3d5cb10b4edd
  * Browser: Microsoft edge/chrome
  * OS: windows/linux

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Recently, I found my habitica webpage's language switch to Japanese somehow(it used to be English), and I cannot switch to English or Chinese anymore even though I set it in my setting.

**Comment by wyatt400** [comment]
I'm having the same issue. However, it changed from English to Spanish and even if I go into the settings to change it back to English or British English, it does not work and stays Spanish.

**Comment by wyatt400** [comment]
Interesting, I just reloaded and it changed to Chinese?

**Comment by Carifyn** [comment]
Same issue here, using Google Chrome. (Mobile app is working fine)
I'm using German language and it partially switched to French. Changing to English works, when I switch back to German, all French parts are showing as English instead of German. Reloading the site makes it show in French again (while still being set to German). xD
![habiticalang](https://user-images.githubusercontent.com/94597775/142371360-222b5bd8-726d-4533-89a3-526789fe6aa6.png)

**Comment by petrof21** [comment]
Same here, noticed this couple of days ago, and it happens every day.
But sometime during the day it returns to my default English language.

**Comment by ramonacat** [comment]
I believe this is happening because there's some cache between Habitica's servers and the end users which caches the `/api/v4/i18n/browser-script` endpoint, which should not be cached on public caches, because it depends on the user's session.

@SabreCat sorry for the direct ping, but I saw you're working on this, I am a software developer, I believe I understand the bug and I'm happy to help :)

**Comment by FirstLoveLife** [comment]
My grifriend also suffer similar issue, she cannot switch to other languages after switch from Chinese to English.

**Comment by SabreCat** [comment]
@Agares 
> I believe this is happening because there's some cache between Habitica's servers and the end users which caches the `/api/v4/i18n/browser-script` endpoint, which should not be cached on public caches, because it depends on the user's session.
> 
> @SabreCat sorry for the direct ping, but I saw you're working on this, I am a software developer, I believe I understand the bug and I'm happy to help :)

Hmm, could be! Based on my and @phillipthelen's investigations, my theory is that the `browser-script` is only actively fetched from the API in the base `index.html`, and that's not reliably happening after Vue has finished setting up and loading the user--but that doesn't quite explain why people are getting _arbitrary_ languages assigned to them. Maybe a cache is involved!

**Comment by ramonacat** [comment]
A cache is definitely, involved, the response has an `Age` header, and a `Via: 1.1 google`. I guess a quick solution would be to do `Cache-Control: private`, or `Cache-Control: no-store` (though that'd increase the number of requests to the backend quite significantly). I see `max-age=0` is set in current Cache-Control, but not sure if that was the original header from the server, or is it the cache messing with it (and max-age=0 means the server SHOULD revalidate immediately, but still might not if it decides to do so for whatever reason)

**Comment by SabreCat** [comment]
@Agares Would it be possible for you to submit a PR with the suggested change? I'm guessing this tweak would be in `website/server/controllers/v3/i18n.js`?

**Comment by ramonacat** [comment]
Sure, can do in an hour or so :)

**Comment by ramonacat** [comment]
The PR is ready for your review :)
https://github.com/HabitRPG/habitica/pull/13631

**Comment by wyatt400** [comment]
The PR was closed because it doesn't fix the problem.

Someone could try to code up a new pull request that will hopefully fix the problem.

**Comment by FirstLoveLife** [comment]
I found my language setting works correctly now :)

**Comment by FirstLoveLife** [comment]
This issue should have been fixed

**Comment by FirstLoveLife** [comment]
This issue appears again @SabreCat @Agares

**Comment by benzinn94** [comment]
Yep. It's switching between French and Dutch for me.

**Comment by ramonacat** [comment]
@SabreCat I think with the new release, a revert for my commit (https://github.com/HabitRPG/habitica/commit/90a14ee871f5a8ada79365f7e95bdd85bc67424e) got (re)deployed.

**Comment by melvio** [comment]
I've seen Russian, French, German, and Portuguese on Chrome.

**Comment by SabreCat** [comment]
yup, a fix is on the way up now.
