### ISSUE TITLE
No potion option in rewards in iPhone app

### ISSUE THREAD

**Issue by Aubec** [HabitRPG/habitica#1362]
No potion appears in the rewards section of the iPhone app.

P.S., I checked into the inn while you have been working on fixes and a) I'm psyched to be able to get back on board using the iPhone app, also b) in fishing around online and in the app store, the framework of what you've put together is effective and unique.  Keep up the hard work, it is much appreciated and you are building something that is exactly what I've been looking for for a long time and that will help a lot of people.  You are great, thank you.

**Comment by lefnire** [comment]
dupe here: https://github.com/HabitRPG/habitrpg-mobile/issues/79 . let's take mobile issues to that issue queue

Thanks for the kind words @Aubec :) Much needed in these times of distressed users. I've got a "fix the website" sprint ahead of me, I hope to revive Habit from it's rough current state
