### ISSUE TITLE
Armor avatar layer appears behind bangs

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13624]
### Description
@citrusella reports: The armor avatar layer appears behind bangs. Normally this is more or less to no effect but it means the headgear portion of the rogue set for 2021 Autumn shows up behind the bangs, since the actual headgear is goo and the "headgear" is built into the armor.

### General Info
  * UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c

**Comment by CuriousMagpie** [comment]
I'll look into this one!

**Comment by CuriousMagpie** [comment]
![Screen Shot 2021-11-15 at 2 22 58 PM](https://user-images.githubusercontent.com/78037386/141841478-f94896eb-751a-46cd-a266-587d39198b84.png)

Yup, those are bangs on the top of the goo. Probably has something to do with the order in which avatar elements are rendered, am looking into.

**Comment by CuriousMagpie** [comment]
Looking into this a bit more, this is working as intended. The goo is supposed to be semi-transparent, and if you look closely, you can see the rest of my avatar's hair as well. I also noticed that different parts of the bangs peek out of different pieces of headgear. Closing this now!

**Comment by citrusella** [comment]
No, the goo is headgear.

The *armor* in the same set includes a fake "headgear" and *that* appears behind the bangs because armor (not headgear) appears behind bangs. Let me get a picture myself?

**Comment by citrusella** [comment]
Armor in question:

![Screenshot 2021-11-16 at 01-17-50 Equipment Inventory Habitica](https://user-images.githubusercontent.com/14182450/141931910-923d7c39-7f5d-4391-8658-31f017cc3393.png)

Appearing behind bangs:

![Screenshot 2021-11-16 at 01-17-40 Equipment Inventory Habitica](https://user-images.githubusercontent.com/14182450/141931953-89281253-b36b-451d-9c8b-3f5179ef175e.png)

With bangs removed, just to show the fake headgear portion:

![Screenshot 2021-11-16 at 01-20-13 Equipment Inventory Habitica](https://user-images.githubusercontent.com/14182450/141932123-b5c235c5-c47b-4358-9e34-7fb6dd9207e7.png)

So this is still happening and the workaround of removing bangs in an instance like this feels awkward?

Like... the armor layer and the bang layer are almost never in the same place to interact with each other (so this is minor, yeah)... but when they do, this happens, which feels like a bug or at least not intended.

**Comment by CuriousMagpie** [comment]
Oh, _weird_. I see what you mean, yeah. It probably has something to do with the way the avatar is rendered and the order of the layers, but I'm not sure we want to necessarily change how that works because one piece of equipment looking strange. @SabreCat, what are your thoughts here?

**Comment by SabreCat** [comment]
Right, this is very much not something that we'd change the layering for. Should the armor's attached headgear be moved to the actual headgear component of the set? @beffymaroo

**Comment by SabreCat** [comment]
Per @beffymaroo, this set is an intentionally unusual design, so it does have some quirks to work around. We'll leave this as is!

**Comment by citrusella** [comment]
This isn't some sort of request to revisit this or anything, but it felt like noting somewhere semi-permanent that multiple people in the past few days have mentioned experiencing this (and wondering why it was like that) with the ghost sheet armor added to the armoire this month too.

(In my opinion it's kind of fun with that one, though, like you taped hair to the outside of the sheet. XD But just felt like adding that note here just in case it's worth making known.)

**Comment by CuriousMagpie** [comment]
We knew about it, but thanks for posting here, too @citrusella. Like last year, this was an intentional design choice. 😄
