### ISSUE TITLE
Invisible dailies

### ISSUE THREAD

**Issue by Aubec** [HabitRPG/habitica#1363]
I have been losing health when all my dailies have been completed, I just figured it was a memory-leak issue.  However, when I downloaded the iphone app, I see that my daily list includes the example tasks you start with when you first create an account.  In the app I was able to delete them.  I'm deducing from this that the starting dailies were sitting there invisibly not getting completed by me all this time.

**Comment by lefnire** [comment]
Ahh, I presume your theory is absolutely correct. We're gonna do some proper data cleanup with the migration

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
