### ISSUE TITLE
String error on Equipment screen

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13634]
Off-Hand Item text is not rendering on the Equipment screen.

Probably introduced by PR #9210.

![Screen Shot 2021-11-19 at 9 10 36 AM](https://user-images.githubusercontent.com/78037386/142674780-b669015c-7618-4efd-97b8-da267596af91.png)

Edited to add: I can't seem to replicate this on my end. Everything looks fine.

Here's the section of code where the string is used on the Equipment page:
https://github.com/HabitRPG/habitica/blob/7aecec9cf4ac4d00e3fb661892d3ba601290ac2a/website/client/src/components/inventory/equipment/index.vue#L360

And the string in the locale/en/gear.json folder:
https://github.com/HabitRPG/habitica/blob/7aecec9cf4ac4d00e3fb661892d3ba601290ac2a/website/common/locales/en/gear.json#L1960

**Comment by SabreCat** [comment]
The string is undefined in most of our language files, only penciled in for English, French, and Chinese... but it _should_ fall back to English where it's missing, not throw an error. I wonder if this is somehow oddly related to #13630? Maybe it's cleared up now that's been addressed?

**Comment by CuriousMagpie** [comment]
Another report from a user, this time on the Broken Task modal:
![broken-challenge-modal](https://user-images.githubusercontent.com/78037386/143285124-b5935b6e-e08a-446b-8961-0e8aedce647b.png)

However, I cannot replicate the issue on my local development server:
![Screen Shot 2021-11-24 at 12 15 06 PM](https://user-images.githubusercontent.com/78037386/143285211-72d6f345-1ce1-4808-ba1b-b6cd2a83be41.png)

UUID: a09e63bc-ca88-4fc5-b6ce-af7ed36eab9c

**Comment by citrusella** [comment]
I had something *like* this happen inconsistently to a few strings in the help menu while trying to force the language issue through repeated reloading (just to see what it looked like) while my language was set to (US) English and the website continued to appear in what looked like English (as I never experienced the language issue).

Dunno if related but felt like mentioning.

**Comment by CuriousMagpie** [comment]
I feel like it's got to be tied to the language/cache issues somehow. The two reported problems were were both strings updated in #9210, so it's possible that the cache wasn't grabbing those updates as well. I'd also updated a couple strings in the help menu as well.

**Comment by citrusella** [comment]
Ooh, my problem was also in a string that was probably updated, I just noticed--I don't remember for sure what the other one was, but one string reported as having a problem was requestAF.

**Comment by CuriousMagpie** [comment]
That string was changed to "requestFeature."

**Comment by CuriousMagpie** [comment]
I haven't seen anything more about this, so I'm going to go ahead and close on the assumption that the cache updates were the root cause.
