### ISSUE TITLE
Language Issues

### ISSUE THREAD

**Issue by 0H21** [HabitRPG/habitica#13630]
First of all, I apologize because I can't report a bug since I can't understand anything. Second, I can't also send my API because once again I can't understand anything. I just logged in on my account when my language became Chinese. I blindly tapped to where I could find the settings, of course google gave a lot of help, but the language setting is already on "English".

When I tried to click this "Settings -> Site" hyperlink from another language settings issues. It gave me the option to translate the whole page using Google Translate. But let's be real, at times we have to clear the tab or reload the page and when I did that it just went back to how it was. It's quite frustrating. I prefer using my Habitica on pc rather than on mobile. So please send help! TT

[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID:
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
![Habitica_LanguageError_1](https://user-images.githubusercontent.com/94634239/142462461-11de7a30-4cc6-4ac2-a0e3-9e314b16ebaa.png)

**Comment by saraolson** [comment]
We have an open issue for this already, please see https://github.com/HabitRPG/habitica/issues/13629

**Comment by 0H21** [comment]
Thank you ^^
