### ISSUE TITLE
Habitica won't load on PC, tested 2 different browsers.

### ISSUE THREAD

**Issue by fassina2** [HabitRPG/habitica#13632]
Habitica won't load, yesterday it loaded but the tasks were invisible so I had to use the phone app.

Today the site won't load it stays in the purple background with the white logo forever. 

Tested 2 different browsers, chrome and vivaldi. Also tested on my phone browsers, vivaldi and chrome. Same thing all of them giving infinite load screens.

I'm in Brazil, using windows 10, phone is an android, mobile app is working normally.

**Comment by CuriousMagpie** [comment]
@fassina2, are you still having this issue?

**Comment by CuriousMagpie** [comment]
Closing this issue.
