### ISSUE TITLE
"Bird Buddies Quest Bundle" has been existd for months

### ISSUE THREAD

**Issue by FirstLoveLife** [HabitRPG/habitica#13633]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: ef3f1e96-dcbd-4036-a8cd-3d5cb10b4edd
  * Browser: edge/chrome
  * OS: linux/windows

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
"Bird Buddies Quest Bundle" has been existing for months and never ends. btw, I cannot buy this bundle too. I believe this is a bug. 
#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by FirstLoveLife** [comment]
![image](https://user-images.githubusercontent.com/37442588/142519997-98b50fc9-9d5f-4626-bf1d-c945abe2769c.png)

**Comment by CuriousMagpie** [comment]
Thanks for raising this, @FirstLoveLife!

**Comment by FirstLoveLife** [comment]
@CuriousMagpie Hi, thanks! but 5 hours past, the bundle still doesn't change on page

**Comment by CuriousMagpie** [comment]
It hasn't been deployed to production yet--should roll out tomorrow!
