### ISSUE TITLE
Dates get cut off in experience graph

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1364]
Windows 7, Chrome browser.

If you've been playing a while, the dates on the X axis of the experience graph get truncated (with "..."), making it pretty unreadable:

![screenclip](https://f.cloud.github.com/assets/4501321/1021830/aabfd2a6-0d34-11e3-907f-91c3c3d7e5db.png)

You have to hover over each date to be able to read it via tooltip.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Note that graphs still need to be ported

**Comment by SabreCat** [comment]
Can't currently check this because progress graphs aren't yet re-implemented. Will need to take a look when they are.

**Comment by paglias** [comment]
Oh, I closed it since tyler is going to use a different library for this, anyway, just remember to close when the graphs are here

**Comment by paglias** [comment]
Is this still happening?

**Comment by SabreCat** [comment]
Doesn't look like it. Thanks for the reminder!
