### ISSUE TITLE
Habitica website will not load in Firefox due to MIME type mismatch

### ISSUE THREAD

**Issue by haslers** [HabitRPG/habitica#13652]
I tried with and without cookies, same result. See attached screenshot. 
<img width="927" alt="Screen Shot 2021-11-24 at 08 04 13" src="https://user-images.githubusercontent.com/19686340/143191010-7e8410e5-599e-401c-a6fd-61eb3d2b0cb2.png">

**Comment by SabreCat** [comment]
I've made a change to server config that should hopefully address this. Closing for now, please reopen if there's new reports!
