### ISSUE TITLE
Cant login on android app

### ISSUE THREAD

**Issue by paulovitorbal** [HabitRPG/habitica#1365]
I fill the username and password and it shows me a message: "please enter your ID and Token in settings" but  i'm stucked in login screen.

If I hit the back physical button of my phone I can access the id and token screen, but I don't have an API token.

**Comment by lefnire** [comment]
what's your user id?

**Comment by paulovitorbal** [comment]
kinnison

**Comment by lefnire** [comment]
Fixed for you, this will be fixed as of the rewrite since Mongoose handles defaults for missing values. ETA post coming soon

**Comment by paulovitorbal** [comment]
Thank you, It worked like a charm.
