### ISSUE TITLE
Unable to Send Party Invites 

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica#13665]
>User ID: 81a0beb6-7a40-4156-81b4-85033ca5d5fc
 > Level: 74
 > Class: rogue
 > Dailies Paused: false
 > Uses Costume: true
 > Custom Day Start: 0
 > Timezone Offset: 480
 > Not Subscribed
 >Please describe the issue you encountered: 
 >"Not letting me invite new people to my party. Getting the message “UserID: already in a party” when I’m inviting brand new people who just signed up for Habitica and are definitely NOT in a party already. These are my friends who I asked to sign up and they aren’t in any other party yet" 
![unnamed](https://user-images.githubusercontent.com/89276822/144474809-b45d151a-1224-419f-aa11-5277f886a094.png)

**Comment by CuriousMagpie** [comment]
I just looked user 9dfb935c-fe91-46bc-8518-9962834c8220 up in the database and can confirm that they are in no parties or guilds and have no outstanding invitations.

**Comment by Alys** [comment]
According to Amplitude, user 9dfb935c-fe91-46bc-8518-9962834c822 joined a party on Nov 19, 11:27:07 pm UTC, about an hour after creating their account. They also have quest progress messages for 2021-11-24, 2021-11-30, 2021-12-01, 2021-12-02, and 2021-12-03, so they were in a party _probably_ continuously from at least 2021-11-24 to now.

**Comment by Alys** [comment]
I think this is a case of the person who reported the issue assuming that the invitee wasn't in a party when they actually were.

**Comment by CuriousMagpie** [comment]
Okay, I'll go ahead and close this. The user did reply to email saying that the issue was resolved and all the folks were now in their party.

**Comment by CuriousMagpie** [comment]
Reopening this because we received another email from the user indicating that it's a persistent problem, so it does require investigation.

**Comment by Alys** [comment]
Copying in some parts of their latest email:

> it happens every time I try to invite a new person
> But somehow they are able to still join my party if they take the initiative to join, I just can’t invite them. 

It's not possible for someone to join a party without an invitation, so the invitations must be working. It may be worth talking them through the process to see where the confusion lies. I'll have a go at that, and also get them to try inviting a test account of mine that I know is not in a party.
