### ISSUE TITLE
App crash, giving "free" money and xp by completing habits

### ISSUE THREAD

**Issue by Sulfirh** [HabitRPG/habitica#1366]
Hi there.

So first, I use Chrome, and the mobile app, the android official one.
User ID: 0e471dc1-ecb0-4388-a891-b873a237d2cf

This problem seems to come from the app. In fact, for two or three days, the app doesn' t launch, and I've got this message: "Application Error - The connection to the server was unsuccessful. (file:///android_asset/www/index.html).

The funny thing is that each (most of the?) time I try to launch the app, got this message, and go back to Chrome, most Habits became completed (turning dark blue) and I win something like 300xp and 30gold.

That's quite awesome ($_$) buuuut not really deserved.

Voilà, I hope this can help a little.

**Comment by Sulfirh** [comment]
Well, I tried to reinstall the app and... tadaah, it works !
I don't really know what was the origin of the problem, but it seems to be something directly from my phone.

Cresus time is over, time to deserve the gold.

**Comment by lefnire** [comment]
looks like https://github.com/HabitRPG/habitrpg-mobile/issues/116 , let's follow up there. strange issue indeed!
