### ISSUE TITLE
Task Scored webhook not firing when task causes a level up

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13680]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: 35c3fb6f-fb98-4bc3-b57a-ac01137d0847

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

> I've written a number of scripts for Habitica, and I just realized (through reading my log files) that the "scored" webhook doesn't get triggered if I score a task that causes me to level up!

Needs confirmation, but it could be we're sending the "level up" webhook in this scenario but not the concurrent task score!

**Comment by tilleym23** [comment]
Is this still an issue? First time contributor here so I'm not super familiar with the project's code, but just from my initial looking through I don't see anything out of place in regards to sending the webhook on task scoring. The taskScoredWebhook is sent on each individual scoring of a task. Inside of that function, ignoring errors from outdated sessions, the only possible early returns prior to sending the webhook are from requiring group approval of the task to be scored.

If this issue still needs investigation I can try to recreate it.

**Comment by CuriousMagpie** [comment]
@Woozical If you'd like to investigate this, that would be great!

**Comment by tilleym23** [comment]
So through manual user testing I have not yet been able to confirm this issue. Every task scored on my local install successfully sends a webhook which is then successfully received by a local Flask server. I'm noticing in the request body of the task score webhook that level up information is included when the task triggers a level up (highlighted in red in attached image). Also that there doesn't seem to be a level up webhook being fired off that could take precedence. So far I've tested level ups on tasks of every type (habit/daily/todo) at every difficulty, as well as a level up from a guild challenge. 
![hooks](https://user-images.githubusercontent.com/80441515/153511106-54a076c0-0df0-4793-9956-b41f78481ff9.png)

**Comment by CuriousMagpie** [comment]
@SabreCat Is this still an issue, since @Woozical tested it and wasn't able to replicate the issue?
