### ISSUE TITLE
Missing translations not correctly defaulting to US English

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13681]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When a translated string, or even string token, doesn't yet exist for the user's selected language, we should display the US English string instead, which we create when building out new content. However, recently it seems as if this fallback has stopped working:

![Screen Shot 2021-12-08 at 10 57 02 AM](https://user-images.githubusercontent.com/4501321/145247381-fc358aed-e2eb-4102-a1cc-5210e16957d0.png)

Given translations are volunteer-supplied and we can't rely on them being complete, especially right at release of new content, this is a substantial problem for non-US-English language users.

**Comment by CraigInches** [comment]
I wasnt able to replicate the issue with a fresh local  install. Can you provide the exact language and background - (I cant see a winter canyon backgroud is it seasonal?)

**Comment by CuriousMagpie** [comment]
@CraigInches I checked in multiple languages--Spanish, French, British English, Danish, Swedish--and the string wasn't being translated. I was checking in production (which is the release branch). The Winter Canyon background is one of the three new backgrounds this month. The only one which had defaulted to American English text was the Frozen Polar Waters background.

**Comment by CraigInches** [comment]
I see the issue, its not the translations falling through.. they dont exist even in default english, will do a PR here to resolve the en, and then head over to the translations repo to fix up the alternatives.

**Comment by CuriousMagpie** [comment]
Oh my goodness, I see it now, too. Too much staring at the code on my part—thanks for catching this, @CraigInches!
