### ISSUE TITLE
account vanished

### ISSUE THREAD

**Issue by toktobis** [HabitRPG/habitica#1369]
After not logging in for a couple of days my account seems to have completely vanished. it says my username doesn't exist, and my email account doesn't work either. I'm a little upset about this, as the site was actually seeming to make a difference in me getting my crap done. But I don't want to start over again and lose everything again.

**Comment by Sulfirh** [comment]
Are you sure you used the exact same username?
It won't work if you use "toktobis" instead of "Toktobis", for example.

**Comment by lefnire** [comment]
@toktobis how long have you been registered? Do you recall your uname, email, or (preferably) UUID you used to register?

**Comment by toktobis** [comment]
my username was Essi and my email was toktobis@yahoo.com (I think) I've been registered for about two weeks and I joined an artist guild and had several pets.

**Comment by lefnire** [comment]
Hmm, something is indeed amiss. Your account still exists under `_id:"9c9a58d3-d9b5-465e-82a1-d5690fa2cae3"`, but without auth properties.

Easy fix, register a new account, give me the new UUID, i'll put that auth property into your old account and delete the new account.

But to address the issue - anything change recently in usage? Are you using the API at all (chrome extension, mobile app, etc)?

**Comment by toktobis** [comment]
Ah, thank you! No there's been no change in usage, I just didn't log in for a few days. I can't think of anything different I did at all.

**Comment by toktobis** [comment]
made a new account under toktobis, here's the UUID 7c7335c9-0cc9-4cc4-bef8-a4c327ecb0a3

**Comment by lefnire** [comment]
alright, give that a shot - logout & back in

**Comment by toktobis** [comment]
Still not working, and it won't let me log in under the new one, either. trying to send a new password doesn't work as well.

**Comment by lefnire** [comment]
hmm... it's showing right in the database:

``` shell
> db.users.find({_id:"9c9a58d3-d9b5-465e-82a1-d5690fa2cae3"},{auth:1})
{ "_id" : "9c9a58d3-d9b5-465e-82a1-d5690fa2cae3", "auth" : { "local" : { "username" : "toktobis", "email" : "toktobis@yahoo.com"}
```

(note the _id being the original account). Can you try again? Capitalization counts. You may have caught the server on a down-swing, it tells users they're not in the database if the site is having connection issues. Try beta.habitrpg.com

**Comment by toktobis** [comment]
now it refuses my password. Is there any way you can reset it from your end? the Lost Password thing gets me no emails. Part of me wants to just give up, but I know this site is still in beta and there's gonna be bugs and things, so I want to keep going with it, it's worth the effort.

**Comment by lefnire** [comment]
@toktobis I know this is centuries later, sorry about that. We rewrote the site from scratch (which is why the radio silence) and released last night. Any chance of giving the reset-password another go? Per chance you using 1Pass, I hear that causes issues with HabitRPG

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
