### ISSUE TITLE
[Feature Request]: Zones with zone-specific dailies & habits for vacation, travelers, and more

### ISSUE THREAD

**Issue by colindmurray** [HabitRPG/habitica#13699]
Last year I had a great time with Habitica... until I went on a month-long vacation. I checked into the tavern but opening the app was pointless. All my normal dailies and habits were mostly irrelevant (tidy my room, brush my dog's teeth, ect. ok... sure). When I came back I was so knocked out of the habit I never picked it back up.

My proposal is Zones. Your default homeland zone is everything the app offers now. If you split time living in different areas, or have a big vacation planned and want to make a specific list of dailies and habits (and even todos re-flavored as local quests that encourage you to go out and complete a specific task at least once while you're away, e.g. visit colosseum, yodel from a summit in the alps, spot a leopard on the safari, ect.) that are tailored to your travels, create a new zone and customize it before your trip.

For my purposes I might have created a simple set of dailies while on vacation I knew I could maintain, and set my character to venture off into that zone when my trip started. If this feature existed I would have kept opening the app each day on my vacation and most likely maintained my habit when I returned.

I always struggle to restore my habits after any temporal disruption, and unfortunately this app has little to help with that. A feature like this could be simple, intuitive, and help enrich a vacation with little quests and small, fun dailies push you to get the most out of your time off.

P.S. I like the idea of implementing some kind of UI skins that could be themed to your zones. Tropical beaches, or alpine mountains, or old rustic cities, ect.

**Comment by SabreCat** [comment]
Hi @colindmurray, we don't use GitHub for feature requests. Send feedback using the form on the site, if you'd like to send your idea along!
