### ISSUE TITLE
Weapon for "killing" unproductive tasks

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#137]
Like you can buy some weapon, you could buy sword that is better of "killing" your critical tasks.

For example if I have Daily task that i constantly not doing (1h of training). With this new sword I could gain more exp for completing it (but not affected green or yellow tasks).
So this would be better motivation to do these tasks.

Just from top of my head and adapt as you like.

**Comment by hookang** [comment]
Unique Weapons with unique modifiers. Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Do current armor/weapon options address this?
