### ISSUE TITLE
Due date issue

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1370]
Hi,

As reported in [trello](https://trello.com/c/vtJv2DyY/77-google-calendar-due-dates) a few weeks ago, I'm facing a real problem with cards becoming red before the due date and killing me.

It should really not start aging before the due date, only after the due date. I have to use another software at the moment to handle such tasks, a bit annoying :)

Thanks !

**Comment by lefnire** [comment]
TODOs don't hurt you. Are you sure it's not some Dailies? What's your UUID, you might have some stray dailies due to Derby crapola.

**Comment by AdrienLemaire** [comment]
My id is 84497c76-4028-4dd5-8403-69b4f5b12575

I might be wrong, as I though I was losing points because the todo cards became red :) If that's the case, sorry for raising a non-existent bug. Might be a good idea to add a ? icon next to the Todos title, which some explanations such as this :)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by paglias** [comment]
Note that the due date feature hasn't be ported, yet!
