### ISSUE TITLE
More prominent link to mobile apps

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1372]
I noticed that on the site I couldn't find a link to the mobile apps. Unless I had not followed the blog I wouldn't have known about them.

**Comment by lefnire** [comment]
Will put them on the new landing pages of the rewrite. we'll be launching pretty soon, and want to sort of raise ourselves out of the ashes, with all the new fangled stuff all at once.

**Comment by paglias** [comment]
Fantastic!
