### ISSUE TITLE
Account reset button pop-up text needs revision

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13731]
### Description
User reports: "I just reset my account (using the option in the Danger Zone). The warning text says "You will lose all your equipment but you will be able to buy it all back, including all limited edition equipment or subscriber Mystery Items that you already own." However, the subscriber Mystery Items are still in my inventory. (So are the Daily Check-In items ... and the birthday hats/robes for some reason?)"

This text needs to be revised to indicate that subscriber Mystery Items, free commemorative items, and all achievements will be retained, as this is working as intended.

The [wiki page](https://habitica.fandom.com/wiki/Reset_Account) has already been revised to reflect this.

**Comment by alekpentchev** [comment]
Hi there :) 
If it'd be fine for you, I'd like to tackle this issue. It'd be a good start for me when it comes to contributing to your repository :) 
From what I understood the goal of this task is to change the pop-up text of the account reset button to reflect the same approach as the wiki page, right?

**Comment by CuriousMagpie** [comment]
@alekpentchev Welcome! Please go ahead and take this one on. The test should say something like: "Start over, removing all levels, gold, gear, history and tasks. Subscriber Mystery Items, free commemorative items, and achievements will be retained." And be sure to check out the [Aspiring Blacksmiths Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) in the app!
