### ISSUE TITLE
Negative habits don't display 0 correctly

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13749]
### General Info
  * UUID: 7c94e21b-8ff2-44a7-a5f1-cfdef807a5f5
  * Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
  * OS: Windows

### Description
From user: 

> I have a negative habit defined, with no positive equivalent defined. I have not touched it for about a month, and it is showing "-0" instead of just zero. I understand that this probably has a minus because it is a bad habit but "-0" just looks weird/confusing because zero is not positive or negative, it is just zero.

![streak-counter-negative](https://user-images.githubusercontent.com/78037386/149574419-9b7f1fc2-f441-42f9-bb8d-ed6a42ecc56e.png)

I checked the user's value for this habit in the database and it is currently 0.

A fix for this would remove the minus symbol from the streak if the value is equal to 0.

**Comment by ouroboran** [comment]
@CuriousMagpie Can I work on this issue?

**Comment by dehanz13** [comment]
Hi @CuriousMagpie , I would love to tackle this issue if it's still open

**Comment by SkitzAvernal** [comment]
Hi @CuriousMagpie, if it's open I would like to work on this

**Comment by iswarmondal** [comment]
**Hey @CuriousMagpie, it looks like the same issue is also happening with the positive habits also. Take a look at this**
![image](https://user-images.githubusercontent.com/73457704/149762358-802239b4-be1d-4cde-942a-b849bc75c47c.png)
If you (or anyone) are not working on this issue then I would like to work on this issue

**Comment by CuriousMagpie** [comment]
Hey folks! We assign issues in the order people ask for them, so if @ouroboran is still interested, they can work on it.

@iswarmondal - the display there actually makes sense, as it's showing that the habit has been clicked 0 times positively and 0 times negatively. This is a display issue that affects habits that have only a positive or a negative option.

**Comment by ouroboran** [comment]
Hi @CuriousMagpie, Thanks. I will work on this issue. So, after fixing, the view should look like below. Please correct if I'm wrong.

![image](https://user-images.githubusercontent.com/97726608/149951646-5a4b1b71-134f-4547-9ff4-126e293d3e61.png)

**Comment by KrSkander** [comment]
Hello @CuriousMagpie, I'm sorry I've made an extra attempt at this issue ! As I'm new to contributing I didn't even notice that issues get assigned per priority until now ! I hope this isn't much of a problem.
Thanks in Advance

**Comment by CuriousMagpie** [comment]
@KrSkander Absolutely no problem! Welcome to open source and Habitica! If you haven't already checked it out, there's an [Aspiring Blacksmiths Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) that can be really helpful for new contributors. You can see issues that need to be worked on by using the "help wanted" tag.

**Comment by dnow2000** [comment]
has this issue been resolved?

**Comment by CuriousMagpie** [comment]
@dnow2000 There's an open PR for this under review right now.
