### ISSUE TITLE
Language Not Changing or Reverting Back

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica#13750]
>Email | j.nakken@outlook.com
>UUID | 120d4af3-15d4-4fb3-bea6-3c07ca06fdc8
>User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
>Level | 93
>Class | rogue
>Dailies Paused | false
>Costume | false
>Custom Day Start | 0
>Timezone Offset | 300
>Subscription | basic_12mo
>Payment Platform | Stripe
>Customer ID | cus_JozC7TAekAMTuJ
>Consecutive Months | 6
>Offset Months | 33
>Mystic Hourglasses | 9
>Describe: "I have attempted to change my language several times for QuartzFox's "Language Bug" challenge, but the only thing that changes is the party skill cast notifications. My most recent attempt, I accidentally left my language set on Pirate English, and when I logged back in a few hours later everything had finally changed to Pirate. Then I logged out and logged into an alt. account. That one displayed in Pirate as well, though set to English. Logged back into my main account and changed my language back to English. Several hours later I'm still in Pirate English."

**Comment by CuriousMagpie** [comment]
@creaturebytes I see that you've already sent an email to the admin team for assistance, so I'm closing this issue.
