### ISSUE TITLE
Password reset email not delivered after many attempts.

### ISSUE THREAD

**Issue by sarahkatenoel** [HabitRPG/habitica#1375]
I really enjoy this game, but forgot my password so tried to reset it. However the password reset email has never come. I checked my spam folder, added the HabitRPG email to my contacts, waited a few days in case I caught HabitRPG at a glitchy day, still nothing.
My username is sarahkatenoel and my email is sarahkatenoel@yahoo.com I don't know my user ID number. My character hadn't progressed very far, so I can create a new account if I really need to, but I'd really prefer to be able to use the same username, or at least the same email address. Thank you for your time.

 I'm not very good at navigating this website, if I accidentally post this to an incorrect section I apologize.

**Comment by lefnire** [comment]
@SlappyBag could this be because of admin@habitrpg.com recent email changes? reset-password uses that account

**Comment by lefnire** [comment]
Can you try again, same email? We were having an email settings issue

**Comment by sarahkatenoel** [comment]
Whatever you did fixed it. Thank you very much!

**Comment by lefnire** [comment]
Awesome, sorry about that!
