### ISSUE TITLE
Problem with registration (community forum)

### ISSUE THREAD

**Issue by Jajoto** [HabitRPG/habitica#1376]
Hello!

I'm Jajo from Poland. I have a problem with registration to the community forum. I registered yesterday and after registration there was an announcement that something went wrong and I should contact with the administrator. There was also announcement "You will receive e-mail" or something like that but it hadn't been delivered to my mailbox. My username is Jajo and my e-mail is vena777@wp.pl . Now if I try to log in it says:

"Sorry, unrecognized username or password."

but if I try to register again it says:

"The name Jajo is already taken.
The e-mail address vena777@wp.pl is already registered."

Well, I know that there are taken because I registered before but I don't know what is wrong. Maybe it's because of this e-mail which hadn't been delivered?

Help me, please.

Jajo

**Comment by lefnire** [comment]
Hey there, I just set your password to [removed] - could you give that a shot,
and change it?

**Comment by Jajoto** [comment]
Thank you so much! I changed password. It works :)
