### ISSUE TITLE
Justin's "Let's Go" button visual bug

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13772]
### General Info
  * UUID: ccd674f1-a67e-4de4-a66d-1267006b075b
  * Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
  * OS: MacOS

### Description
from user:

> I noticed that the "let's go!" button on the intro messages from Justin behave a little different than all other buttons. When you hover over the button, the text color changes (disappears). Not sure if this is intentional or not. 

![justin-lets-go](https://user-images.githubusercontent.com/78037386/150169496-eeb68000-0282-45be-87ac-3d49e171919f.png)

Fix would correct the hover text color to match the rest of the buttons on Justin's intro.

**Comment by jaredmez** [comment]
Can I take this issue?

**Comment by CuriousMagpie** [comment]
@jaredmez You sure can! 😄

**Comment by CuriousMagpie** [comment]
Hi @jaredmez! Are you still working on this? Have any questions coming up that we can help with?

**Comment by vanessasickles** [comment]
@CuriousMagpie I would love to take this issue if @jaredmez is still busy!

**Comment by jaredmez** [comment]
@CuriousMagpie You cant take it!

**Comment by CuriousMagpie** [comment]
I’m afraid I’m a bit confused? If you’re still working on this @jaredmez, that’s great. We try to check in with folks every so often, that is all.

**Comment by W1-PopelierE** [comment]
@CuriousMagpie it appears this issue is still open and has not been fixed in `develop` yet. Would you like me to pick this up?

**Comment by CuriousMagpie** [comment]
@W1-PopelierE This issue is assigned to @jaredmez. Is there something else you'd be interested in working on?

**Comment by W1-PopelierE** [comment]
@CuriousMagpie yeah I noticed this was assigned to @jaredmez but since this is still not fixed I thought perhaps I can take over this issue. I'm looking for any great "first issues" to get to know the code.

**Comment by SabreCat** [comment]
Haven't seen anything from @jaredmez in a while, and @vanessasickles has some other issues assigned, so if you still want this @W1-PopelierE, go for it!

**Comment by W1-PopelierE** [comment]
@SabreCat PR submitted.
