### ISSUE TITLE
Class Change Text Line For Equipment Store Misleading 

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica#13775]
>Device: samsung SM-F926B
>Android Version: 30
>AppVersion: Version 3.4.2 (3133)
>User ID: 0cfa3d66-8392-444f-872f-d027d87512bd
>Level: 3
>Class: warrior
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0
>Timezone Offset: -480
>Details:
>" Equipment store tells players that class can be changed in settings. This information is incorrect for players less than level 10"

**Comment by CuriousMagpie** [comment]
The fix for this should make it clear that class can be changed in settings for characters > level 10.

**Comment by shagen9285** [comment]
Hey! Do you mind if I try and fix this issue?

**Comment by CuriousMagpie** [comment]
@shagen9285 Go for it! Thanks!

**Comment by CuriousMagpie** [comment]
@shagen9285 Hello! Are you still working on this issue?

**Comment by shagen9285** [comment]
I think it has been fixed already. Unless I'm missing it somewhere, but when I go to the shop before level ten and try to buy something not in my class, it tells me I need to be level ten before I can change class.

**Comment by CuriousMagpie** [comment]
Huh, you're right. The text seems pretty clear to me as well--I'm going to go ahead and close this. Feel free to request another issue!
