### ISSUE TITLE
Account loses progress on refresh

### ISSUE THREAD

**Issue by lsaul** [HabitRPG/habitica#1378]
I added a couple of to-dos and crossed some things off the list to get a feel for the app. I earned a bit of experience and coins. One of my completed todos didn't reward me with any coins so I refreshed the page. I lost all of the todos, experience, and rewards that I just set up. 

This looks promising, but hopefully these bugs will get worked out.

**Comment by lefnire** [comment]
This is due to #165. The workarounds [are listed here](http://habitrpg.tumblr.com/post/55792029689/bug-workarounds) for the time-being, and the solution is the [rewrite we're working on](http://habitrpg.tumblr.com/post/59104876969/website-issues-what-were-doing) which should be released soon
