### ISSUE TITLE
blank eggs

### ISSUE THREAD

**Issue by Erreinion** [HabitRPG/habitica#1379]
I have 2 eggs in my inventory without graphics but a small border, and the 'pour a potion' text reads: "Which hatching potion will you pour on your egg?" when it usually states the type of egg that is selected.

![image](https://f.cloud.github.com/assets/2197557/1060879/8320c100-11bd-11e3-92d4-54f6da7556cf.png)

**Comment by SabreCat** [comment]
Duplicate of #1367 .
