### ISSUE TITLE
Seasonal items from nonstandard gear slots inappropriately locked for re-purchase

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13798]
### Description
Via @citrusella:

> I just noticed in the market/my rewards column that several seasonal accessories for my current class that *should* be available for re-buying are locked with this message: "This item is only available once you've purchased the previous items in sequence. Keep working your way up!" ...For one, that *particular* message shouldn't apply to seasonal gear. For two, there *are no* previous items in sequence for those slots (I think head accessories *and* body accessories). I tried to figure out if maybe it was sort of defaulting to that message but locked for some other reason and I couldn't figure out any other problem, though it's possible I was sniffing in the wrong places. The equipment at issue is: - Green Kitty Ears (spring) - Yellow Dog Ears (spring) - Purple Bunny Ears (spring) - Purple Mouse Ears (spring) - Dark Visage (fall) - Sailor's Neckerchief (summer) (For context as to why I have so many items "lost" if you happen to go looking in my account: I politely asked Alys some months ago to wipe my equipment list legacy-rebirth-style. I don't think that could be the problem here, though, as I'm pretty sure when I pinned those items they were able to be purchased.) Happy New Year!

This is unlikely to affect many users, ~~as these items aren't normally set to `false` under routine app usage~~. But in the event that they are in that state, they should indeed be Gold-purchasable while the user is the appropriate class, not blocked as if behind a non-existent gear progression!

**Comment by megansearles** [comment]
Hi, can I take this issue?

**Comment by citrusella** [comment]
> these items aren't normally set to `false` under routine app usage

Just a question since the phrasing of this threw me off when I read it and I don't know if I'm understanding what you meant--since death sets lost items to `false` does that mean nonstandard slots can't get lost to death? Or am I misunderstanding and you just mean it's statistically unlikely under a routine `false`-setting feature like death, since there are so many items that could theoretically be lost to death and most are not nonstandard slot equipment?

**Comment by CuriousMagpie** [comment]
@megansearles Sure thing--welcome to Habitica! You might want to check out the [Aspiring Blacksmith's Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) as well!

**Comment by SabreCat** [comment]
> > these items aren't normally set to `false` under routine app usage
> 
> Just a question since the phrasing of this threw me off when I read it and I don't know if I'm understanding what you meant--since death sets lost items to `false` does that mean nonstandard slots can't get lost to death? 

Oh, you're quite right, I thought these were excluded from breakage during the `revive` op, but it looks like any `special` gear with a `value` greater than 0 should be eligible to break. I've struck out that phrase from the issue ticket.

**Comment by megansearles** [comment]
Hi! I made a pull request, but one of the tests failed and I'm not sure why. It passed on my local machine. I also don't see how the failed test relates to my change. Any advice would be appreciated!
