### ISSUE TITLE
Habits disappeared

### ISSUE THREAD

**Issue by JesperDramsch** [HabitRPG/habitica#138]
I use chrome and windows 7 and just now, more than 50% of my habits disappeared. This kind of data loss is kind of annoying...

**Comment by sergiobc** [comment]
Confirm, just happened to me also

**Comment by JesperDramsch** [comment]
Now some dailies disappeared on onMouseOver.

2013/1/21 sergiobc notifications@github.com

**Comment by wc8** [comment]
On browser refresh/reload, habits sometimes disappear

**Comment by wc8** [comment]
I think this is related to https://github.com/lefnire/habitrpg/issues/118

**Comment by lefnire** [comment]
Well, it's most likely #80 causing #84. In a nutshell, the server crashes, comes back up - you were connected before it crashes, and it's not properly reconnecting after it came back up. I'm sad to hear it's still happening for you guys - I'm seeing the server go down substantially less often, but I'm still diagnosing this one.

As far as @Jesper1337's onMouseOver bit, I'll check that out. Very strange.

**Comment by sergiobc** [comment]
I don't think it is #84 because my items that disappeared were created days ago. So items existing on the server have been deleted, not "changes made between the time the server came down, and the time the user refreshes the page are completely lost" as says #84

**Comment by ctuirmt00** [comment]
My To-Dos disappeared...  I wrote so many things down on them too.  I kept refreshing to see if they would come back but I think I lost them forever.

Not all of them are gone though, just a random bunch as far as I can tell.
