### ISSUE TITLE
Sync tasks with dav protocol

### ISSUE THREAD

**Issue by parisni** [HabitRPG/habitica#13820]
if habitica can provide a task dav endpoint then the tasks would be shared among tasks tools and that would be great

**Comment by CuriousMagpie** [comment]
Hi there! We don't take feature requests via GitHub. Instead, we ask that you submit a [Request A Feature](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link) form. Thanks!
