### ISSUE TITLE
Adding a task to todos just refreshes the page

### ISSUE THREAD

**Issue by JohnsonDH** [HabitRPG/habitica#1382]
Hi,

I've noticed this with not only the todos. When I try to add a task to one of the lists, it refreshes the first time or two, but manages to add into the list the third or fourth time.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
