### ISSUE TITLE
Run migration to give gems for broken eggs, then delete them

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1386]

**Comment by Habitfan** [comment]
Tyler this is Senica from Habit.

I am not a programmer but just a few idea's.

If pets are not porting over well...... maybe you could give everyone the same value of gems which would equal the same number of pets they acquired and they could use those gems to recreate there stable. Maybe this is simpler solution for you.

Second idea. Start everyone over with pets. I know this will not be popular with some, but it may be the cost of a less bug free site. You could give some badge out to the people with over a certain number of pets to appease them and start anew. 

You could even roll out the more advanced pet system in the plans without the legacy issues. 

You have worked hard at this. The pet system has always been a cool wild card part of Habit maybe scrapping it for a new system may be the best use of your resources. Any complaints about the injustice of pets can be directed to Bailey and me. :)

**Comment by lefnire** [comment]
naw, we won't scrap all pets. Only recent adds to users' pet list are corrupt, they were saved as a string "[object Object]" instead of and actual object. Either your first solution (giving everyone 3gems for every "[object Object]") or just wiping all the empties is the best bet. No need to scrap all pets alltogether

**Comment by paglias** [comment]
On mobile it shows items.eggs as [object Object] but show them correctly on habitrpg.herokuapp.com

**Comment by lefnire** [comment]
@paglias strange, that was fixed at https://github.com/lefnire/habitrpg/commit/687da68d520af74d742330c221acd3ea48e4ded5#L0R130 . Is mobile running of a pulled instance of the rewrite? If it's still running off beta, that' the problem (since it still has the bug). Reason I'm pushing so hard on rewrite is so we can replace beta asap to fix that bug

**Comment by paglias** [comment]
Yes beta, thanks!

**Comment by paglias** [comment]
I thought that also the published mobile app was running off beta

2013/9/3 Matteo Pagliazzi matteopagliazzi@gmail.com

> Yes beta, thanks!

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
it does indeed, so some people are racking up `[object Object]` pets. Once we publish rewrite to beta (which will fix this issue for mobile), we'll run a migration to nix the corrupt eggs

**Comment by lefnire** [comment]
I'm now running a migration to grant 3 gems for every broken egg, and the original bug is fixed
