### ISSUE TITLE
Weird --- EGG and potion did nothing but both disapeared

### ISSUE THREAD

**Issue by nosht82** [HabitRPG/habitica#1387]
I had a --- under eggs in my inventory with no picture when I clicked on it, it acted like a normal egg.  I used a Desert potion on it and both diapered.  It said the pet would be in my stable but no new pets were there.

Also it says I have 4 / 90 Pets Found, but I only have 3.

My user id is
9a1e176f-a6e1-4da3-90e7-d04d0c60977e

**Comment by paglias** [comment]
It's #1367
