### ISSUE TITLE
500:TypeError message on herokuapp site

### ISSUE THREAD

**Issue by LordGrowl** [HabitRPG/habitica#1388]
An error message in red font within a pink box has appeared below the header.  If I hide the header, the error message remains at the top of the page.  It doesn't cover anything up, i.e. the rest of the webpage is pushed down to accommodate for the pink box.

Here's a copy paste of the full error message:

> 500: TypeError: Object.keys called on non-object at Function.keys (native) at init (/app/node_modules/mongoose/lib/document.js:267:21) at EmbeddedDocument.Document.init (/app/node_modules/mongoose/lib/document.js:247:3) at DocumentArray.cast (/app/node_modules/mongoose/lib/schema/documentarray.js:135:27) at /app/node_modules/mongoose/lib/document.js:289:29 at model.Document.$__try (/app/node_modules/mongoose/lib/document.js:758:8) at init (/app/node_modules/mongoose/lib/document.js:288:16) at init (/app/node_modules/mongoose/lib/document.js:282:7) at model.Document.init (/app/node_modules/mongoose/lib/document.js:247:3) at completeOne (/app/node_modules/mongoose/lib/query.js:1821:10) at /app/node_modules/mongoose/lib/query.js:1789:11 at /app/node_modules/mongoose/lib/utils.js:414:16 at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:953:5 at Cursor.nextObject (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:678:5) at commandHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:658:14) at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1670:9 at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41) at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18 at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20) at EventEmitter.emit (events.js:95:17) at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13) at EventEmitter.emit (events.js:98:17) at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:301:18) at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:736:14) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:526:21)(see Chrome console for more details).

**Comment by lefnire** [comment]
on it, thanks

**Comment by lefnire** [comment]
note-to-self. once we're off Derby, revert the above commit and run a db migration to remove all `"[object Object]"` corrupt eggs from database (leaving open till then)

**Comment by lefnire** [comment]
migration run, this should be fixed
