### ISSUE TITLE
Guild navigation using notifications does not update challenges to current guild

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13891]
### General Info
  * UUID: b0fbabc9-32be-49c7-8b3e-f05578f61388
  * Browser/OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

### Description
Navigating to a different guild page using Notifications does not update the guild's challenges. i.e. It is still showing the challenges from the previous guild. Steps to reproduce. 1. Go to a guild page. 2. From the notification, click on a notification that will bring you to a different guild. 3. Check the challenges section, it will still be showing the previous guild's challenges.

**Comment by dsychin** [comment]
Here's a screen recording reproducing the issue.

![habitica_reproduce2](https://user-images.githubusercontent.com/19268668/158495028-37f4c08f-895e-43d8-99f6-53283b9bce74.gif)

**Comment by Alys** [comment]
This has been happening for several months. We had it reported at https://github.com/HabitRPG/habitica/issues/13256 which was closed with a PR, but I'm not sure the bug ever went away.

**Comment by johnl2102** [comment]
Hi, I and a colleague of mine are interested in working on this issue. What would be the best way to get started?

**Comment by CuriousMagpie** [comment]
Hi @johnl2102 I noticed that you asked to work on another issue as well. We only assign one issue at a time, which one would you prefer?

**Comment by CuriousMagpie** [comment]
Another user reporting this issue:

> on Web version when moving from one guild to another through notification, it wont update the Challenges at the description to the new ones on the page (will keep showing old ones). happen on chrome and explorer.

**Comment by CuriousMagpie** [comment]
User provided a screenshot of the console:
![console log](https://user-images.githubusercontent.com/78037386/182205368-1a4a3f49-e0df-4640-ac30-192c63f9d0fe.png)

**Comment by theneelshah** [comment]
@CuriousMagpie Can I pick this up? I've never done a contribution before and am excited for my first contribution. I managed to repro this issue locally..

**Comment by theneelshah** [comment]
Have created a pr: https://github.com/HabitRPG/habitica/pull/14169
