### ISSUE TITLE
Heroku - money, exp, gems, pets, armour, shield disappeared

### ISSUE THREAD

**Issue by Jajoto** [HabitRPG/habitica#1391]
Hello!

I lost money (72 coins), experience (???) and 4 gems at heroku site. I also don't have any pets (I got 27) - just blank site. I don't have an armour and a shield which were at the same level as sword. Help me please. 

(I'm not good at english, it isn't my native language so please don't use slang, colloquial words)

My nick at heroku: Jajo
My user ID: f6d401ca-7e94-4961-b9b3-b85c8c8b5d66

edit: Now I realised that I lost also colours (now all yellow). I marked "cleaning" as green and now I have 9 exp and 1 coin... Wow... :(

**Comment by lefnire** [comment]
can you [click sync](https://www.evernote.com/shard/s17/sh/ade42209-e820-4603-8615-46a95d2aa7c1/e9b4d7b737615e8374a16a1aee15f5e0) and see what happens real quick?

**Comment by Jajoto** [comment]
Nothing happens
I clicked many times, it doesn't work

**Comment by Jajoto** [comment]
LordGrowl wrote in the Tavern: "Hmm... interesting. Since that sudden update, I have lost 2 levels, my armour, my shield and all my gold."

**Comment by lefnire** [comment]
ok, i'm looking into it. i have a backup from earlier today we can roll people back to as necessary.

**Comment by lefnire** [comment]
@Jajoto Can you log out and back in on the herokuapp, i restored your info. Anyone else who was effected, please provide your uuid here and i'll restore you. I'm terribly sorry for this one

**Comment by LordGrowl** [comment]
Hey, Lefnire, many thanks for the quick fix.

User ID: 1e18512a-0130-4651-962a-e089300f0b4d

**Comment by lefnire** [comment]
ok - log out & back in, you should be good. Everyone gets gems for this

**Comment by Jajoto** [comment]
Thank you very much :)

**Comment by LordGrowl** [comment]
I'm in an interesting situation. The bug happened just before midnight, it is now 00:40pm. It seems that I was restored back a state before midnight and now I can't get the end-of-day cycle (the cron thingy). My dailies are now marked as completed. Ah well, worst comes to worst, it'll sort itself out in 24 hours times anyway.

Many thanks for the quick response, lefnire. =]

**Comment by lefnire** [comment]
Hm, let's see if I can figure out.. that a shot (if no cigar, also try Menu > Sync)

**Comment by LordGrowl** [comment]
No worries, I think I've just sorted it out. I'm just switching between beta. and herokuapp back and forth while playing around with my computer's time.  Always a work around for things like this, even if it is a rather messy and unsophisticated one.  =]

Edit: Actually, just re-read your post. That was probably your magic that fixed the problem after all.  Many thanks again!

**Comment by jasdonle** [comment]
Hello! I tried herokuapp this morning, and in the afternoon switched back to beta and vanilla. Now my character is level one and I've lost all my gear.

**Comment by jasdonle** [comment]
UserID is jasonadam and my name is Pseudonaut. Thank you!

**Comment by lefnire** [comment]
@LordGrowl Alas, no cigar then? I tried setting your `user.lastCron` property to 5h ago, hit me up if you want me to try another route (sounds like you're on a track).

@jasdonle i can restore you to sometime earlier today if you want, provide me with your UUID and i'll restore you & add tokens

**Comment by LordGrowl** [comment]
@lefnire Everything's fine now - whether it was my messing around or your code wizardry (probably the latter), all is good now in the land of Habitia (why to mystical lands all end in -ia or -ica?) =]

**Comment by lefnire** [comment]
Habitacia? 

@jasdonle log out and back in, you should be good. Gave you gems for the trouble. I think this is everyone, at least all the names I saw for users experiencing the bug. Closing now, thanks guys!

**Comment by LordGrowl** [comment]
"Habitacia" could work. You know, after doing the whole party and class system thing, you could probably ask someone to draw a sort of world map for Habitacia. What old school RPG doesn't have a world map? =]

**Comment by lefnire** [comment]
I jest! I think I like your Habitica best :) A map indeed! Can't wait to have challenges in place so I can commission that

**Comment by Jajoto** [comment]
Well, I didn't get extra gems for the trouble. I received only four that I lost because of this bug.

**Comment by jasdonle** [comment]
Everything is back to normal, but I didn't receive any gems either. 

f26a568b-55d9-4d31-b933-56f603be1590

**Comment by lefnire** [comment]
shoot - ok, everyone double check now, ran it again

**Comment by jasdonle** [comment]
Everything is good. Gems are there. Thanks! And congrats on launching the new site!

**Comment by LordGrowl** [comment]
Whoa!  Many thanks for the gems, lefnire. Although I wasn't wanting them - I'm more than delighted by your ridiculously quick response - but the gesture is hugely appreciated. Thanks very much.  =]

(I didn't notice them until now because I usually turn off the header; I just turned it on now to see how my party members were doing and "OMG!")

**Comment by Willz7** [comment]
Two days ago I had some errors on my header showing random numbers and then yesterday, it added a random numbers into my dailies. I lost 4 gems. My UDID is d1f393d4-1d9b-4b04-be50-47f9f3db0abd

**Comment by lefnire** [comment]
@Willz7 sorry this is so late. What's your account look like now, i could restore you but it would set you back 5 days. Want me to just send you some gems instead?
