### ISSUE TITLE
MS Edge - Choose Class Modal Broken

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13929]
### General Info
  * UUID: 61dc80c3-8522-482e-a7af-04554c531570
  * Browser: MS Edge
  * OS: Windows 10

### Description
The modal at level 10 for choosing a class is broken in the Microsoft Edge browser. User Settings > Choose Class also has this error as does purchasing a class change with gems. The user was able to select a class via User Settings > Choose Class in Firefox with no problem.

![ms-edge-choose-class-error](https://user-images.githubusercontent.com/78037386/162779374-c9e6f3ee-b7f4-4b2c-bb51-b2639690b3c8.png)

**Comment by citrusella** [comment]
I was curious about what could be causing this (partially because it reminded me of a weirdly similar issue happening universally regarding the avatars on the modal wearing seasonal gear IIRC) but couldn't reproduce it on (gem) class change.

**Comment by W1-PopelierE** [comment]
I'd love to dive into this tomorrow. I am new to Habitica but not new to Vue. Sounds like something I have done before for work.

**Comment by CuriousMagpie** [comment]
That would be wonderful @W1-PopelierE! I'll go ahead and assign this to you.

**Comment by W1-PopelierE** [comment]
@CuriousMagpie I am using the `develop` branch and this is working as it should. 
The only comment could be that the image is not aligned in the center of the purple border. But besides that visual "bug" I am unable to reproduce this.

![Screenshot 2022-04-14 at 16 58 03](https://user-images.githubusercontent.com/17490821/163417693-05f93a0d-1bb8-4ee3-9cbe-8b3512084fa1.png)

**Comment by CuriousMagpie** [comment]
Thanks, @W1-PopelierE. The non-centering behavior is due to the gear that the avatars are wearing and how they're placed in the avatar display with backgrounds, etc., so that's working as intended. I'm going to go ahead and close this unless we get future reports.
