### ISSUE TITLE
Add Tour back in

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1396]
Add Ian's NPC in there

**Comment by paglias** [comment]
Bootstrap Tour v0.5.1 which gets installed in habitrpg is not compatible with bootstrap 2.x.x but only with 3.0.0

We should use v0.5.0 and also talk about, in the long term, leaving bootstrap 2.3.2 since it's not going to be supported anymore

**Comment by paglias** [comment]
Fixed in https://github.com/lefnire/habitrpg/commit/6ce3488e6710e7b23d8209b50e687acc60b7cda8 and https://github.com/lefnire/habitrpg/commit/8d8734d1578a9337b4c74607fa29f72a6f30e184 since the bootstrap resoluton is not necessary anymore

**Comment by lefnire** [comment]
added

**Comment by paglias** [comment]
I have a problem with that: it showed both on my phone & pc, shouldn't it be shown only once? And then most important: I could see only the first two steps of the tour then it ended

**Comment by paglias** [comment]
Tried locally from the develop branch and it's working (I would add a tour step about the "options" page which isn't exactly easy to find unless you know)

**Comment by paglias** [comment]
What is happening is taht it's showing only steps for items you have, since I have only dailies but no custom rewards, todo or habits it only show two steps: the first one and another about dailies

**Comment by lefnire** [comment]
Ah, the css selectors are hitting the `li`s then, not the `ul`. Not too big a deal right now, since 99% of people will be seeing tour on initial account only. I think the issue with when it's visible is this: it checks `user.flags.showTour !== false` (maybe I should set to `=== true` instead, and update the newUser habitrpg-shared helper). Since you have an account stored in localStorage, it starts the tour before it fetches the user and knows that the flag is false. hmmm.. think think think....

**Comment by paglias** [comment]
We should add a tag `priority - minor - minor -minor` for this type of bugs :)

**Comment by paglias** [comment]
Fixed that the tour was shown twice (we should use User.log to set also the local model..) Closing since I don't think we're going to fix that when you have no habits/dailys then the tour isn't shown because other selectors aren't as good as the actual ones to show the user around and the tour should be needed only the first time.
