### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1398]

**Comment by lefnire** [comment]
The code is there now: ceae8bf and 466c727, but we have an issue that we're not really dealing with session state, & facebook login requires a full redirect. See "Facebook authentication" issue outlined in http://stackoverflow.com/a/16781555/362790 . So the net result is it goes to server, redirects to front-page with auth params in the url, `$location` parses that & runs auth. Fuggly. And we'll want to support some facebook API auth route for mobile devices too, so we gotta fix this

**Comment by lefnire** [comment]
gonna put this one till post-launch, we have all the things we need for now albiet ugly.

**Comment by paglias** [comment]
This is done
