### ISSUE TITLE
[Feature Request] suggestion

### ISSUE THREAD

**Issue by stadt-kind** [HabitRPG/habitica#140]
hi there, 
first of all thanks for your hard work i really like the rpg approach because im hooked to games like these since i first played secet of mana on my snes when i was a kid. i started using the game and i sucked me right in, even though it got some bugs and some things that might be added, so i put together a lil list with some things i thought you might add to the game.

-quests
the user can create quest (projects) wich contain multiple smaler tasks wich need to be done to finish the quest. each of the small tasks gives a small reward (gold,xp etc) finishing the whole quest gives a bigger reward depending on a deadline wich can be set by the user( finishing a quest earlier gives more while not forfilling the deadline will reslult in a smaller reward) this encourages the user to set a realistic deadline and helps estimating the amount of time needed for the next quests.

-alterego/pet
it would be nice if habit had some sort of private vs work balance system. i.e. an alterego or a pet wich is right next to your avatar . by clicking on it, you will be able to switch to your work related tasks wich also have their own habits dailies todos (quests). the goal is to have a balance between the two, wich shows you if you work too much/less on your job private tasks.if the system gets out of balance it hurts your avatar and costs hp. (maybe balance should be set by the user ->60% private 40% or as the user pleases)

-death
when a user dies his avatar gets stuck in some sort of twilight zone (similar to the rpg ultima online ) in wich he is stuck until he manages to resurrect. to resurrect the user is forced to complete a number of the oldest tasks in his to do list. (so if u fuck up you will be forced to finish some uf the stuff youve been struggling to do for a longer time)

-random challenges
the system creates random challenges like little sidequests wich can be accepted or denied by the user (i.e finish 5 todos today or finish daily workout before 11am...) if you accept the quest you will be force to finish to the given deadline.  the harder the sidequest the bigger the reward

-guilds
user created guilds to group with other users with a shared goal (i.e. weightloss, stopsmoking learnig a language) guild members can create guildquests wich can be completed by the members. there could also be a rankingsystem within the guild.

-sleep button
adding a button with wich the user can end a day manually ( i often work past 12 pm so when i return home und wanna check of my tasks it already started a new day.) if the buttisnt pressed at a certain time i.e. 5am the game automatically ends the day by itself.

sorry for the long post but i really like your game and hope i can somehow help with input or however to make this even more amazing.
keep up the good work and let me know if there is something a can contribute to the project.

**Comment by mgatten** [comment]
I really like most of those ideas.

In particular, the Quest idea is awesome. I just started using the system yesterday after discovering it on Kickstarter. I enterered a whole bunch of To-Dos, many of which could be grouped into three major projects. Basically, I made the major milestones my To-Dos. Getting one of those groups done is a major accomplishment. Getting all but one of them done is as good at failing at them all, though. The system doesn't see it that way, though. It would be phenomenal to be able to group them into quests, with the final task ("Complete Project") as a boss monster. 

I also really like the Limbo idea. In order to be resurrected you must complete your oldest To-Do. Brilliant!

**Comment by wc8** [comment]
RE: quests & random challenges
I think some of this is under consideration: see complex todos (https://github.com/lefnire/habitrpg/issues/67), Party or Guild challenges--_campaigns_? mentioned in comments on (https://github.com/lefnire/habitrpg/issues/65), random challenges (https://github.com/lefnire/habitrpg/issues/70), battles, boss battles (https://github.com/lefnire/habitrpg/issues/66), habit roulette (https://github.com/lefnire/habitrpg/issues/69)

RE: alterego/pet
hm... see https://github.com/lefnire/habitrpg/issues/48 re: tags and categories. 
I'd rather have this be locations/buildings. Maybe this could affect the health of your town...
I do like the idea of an alterego/pet, generally though

RE: death
Maybe a do very old task(s) OR use Tokens, see also: business model (https://github.com/lefnire/habitrpg/issues/25)
I wouldn't want the ONLY method to revive being based on oldest To-Do. What if it's something I'm waiting on someone else for but can't take off my task list? Uh-oh!

RE: guilds
At first I thought this was another version of parties, but the groups-with-similar-goals is an interesting idea.

**Comment by hookang** [comment]
Added a bunch... Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
-quests [Checklists](https://trello.com/c/PJ1iJ413), not to be confused with [quests](https://trello.com/c/VPPjVRlF)
-alterego/pet: as far as separating work from home, see [Tags, Categories](https://trello.com/c/q7v02jAw), for the HabitRPG pet feature see [Pets](https://trello.com/c/SVteKuNu)
-death: see Phoenix Quest on [Death Mechanic](https://trello.com/c/k2MWBcxl)
-random challenges [Random Challenge](https://trello.com/c/EPxvwrrh) 
-guilds [Shared Interest Groups](https://trello.com/c/CuEnnOpe)
-sleep button: see [Record Yesterday's Activity](https://trello.com/c/CaAm7APS)

**Comment by wc8** [comment]
Update: - alterego: [Alterego Roles](https://trello.com/c/W0XdPYwT)
