### ISSUE TITLE
Start from a login or refresh with nothing in a task list. Add one or more tasks. They don't appear in list until a new refresh.

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1401]
@SabreCat is this still the case? closing 'cause i think it's fixed, if still issue re-open

**Comment by SabreCat** [comment]
This one's still happening. Just replicated it with Todos on my main character.

**Comment by lefnire** [comment]
oh man... heroku or beta/prod?

**Comment by SabreCat** [comment]
Heroku only.

**Comment by lefnire** [comment]
5f2405a
