### ISSUE TITLE
Quest rewards tool tip cut off on quest modal

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#14017]
[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: c7834c97-7063-4070-a4c0-25e6a297929e
  * Browser: Chrome/101.0.4951.67
  * OS: Windows NT 10.0; Win64; x64

### Description
When hovering over the right-most reward in the quest modal, the tool tip is cut off. The tool tip should display fully.

![2022-05-25_user_screencapture](https://user-images.githubusercontent.com/78037386/170735521-3b009331-0f2d-42d6-a828-6dd3700c2748.png)

From the user:
> This only happens in the party view, not when you look at it in the Shop.  And it only seems to have started in the last week or so.

Investigation is needed to determine _why_ the tool tip is being cut off. Simply repositioning it on the modal is not a sufficient fix.

**Comment by darkarchana** [comment]
I didn't find the problem on the latest develop branch on chrome and firefox. Someone need to check on this, clarify, and close the issue if no problem found.
![habitica-quest-tooltip](https://user-images.githubusercontent.com/41007883/171991417-082fab95-bdb7-4e20-919e-78c4bf631375.png)

**Comment by CuriousMagpie** [comment]
I'm unable to duplicate on either Firefox or Chrome. Am closing, but will re-open if we get additional user reports of the issue.
