### ISSUE TITLE
Not receiving password changed successfully toast

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica#14032]
When going to Settings to change your password, you can type in your old password + new password, click save, and nothing seems to happen except a load bar. The fields stay filled in with what you typed. If you then click save again, it says 'Wrong Password' because the first save actually did change your password.

It should show a green "Your password has been changed" toast in the top corner, and the text fields should clear out.

**Comment by darkarchana** [comment]
I have 2 ideas to solve this and want to have a go. May I work on this? If I may which are more preferable from this 2 solutions?

1)  
- on [https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/settings/site.vue](url)
add on changeUser method:
```
if(attribute === 'password') {
          this.passwordUpdates = {};
          this.$store.dispatch('snackbars:add', {
            title: 'Habitica',
            text: "Your password has been changed",
            type: 'success',
            timeout: true,
          });
```

Or

2. 

- on [https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/settings/site.vue](url)
add on changeUser method:
```
if(attribute === 'password') {
          this.passwordUpdates = {};
}
```
- on [https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/auth.js](url)
add response  data for api.updatePassword, currently only blank data response with http status 200
or
add notification on the response for api.updatePassword:
```
    res.locals.user.notifications.push({
      type: "UPDATE_PASSWORD",
      data: {
        text: "Your password has been changed",
      },
      seen: false,
    });
```
- on [https://github.com/HabitRPG/habitica/blob/develop/website/client/src/app.vue](url)
add dispatch notification on axios interceptors when success response

**Comment by CuriousMagpie** [comment]
@darkarchana I'll go ahead and assign this to you. As for which fix is preferable, I'll leave that to @SabreCat to weigh in on!

**Comment by darkarchana** [comment]
@CuriousMagpie, I already did PR #14054,
I used the first solution, since I think it leaves less footprints and I think there are not many success response that need to be showed currently. So when in the future the API has more success response, the notification dispatch can be moved to the axios interceptors.

**Comment by CuriousMagpie** [comment]
Completed with PR #14054
