### ISSUE TITLE
NS_BINDING_ABORT error when using master key to kennel 

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#14030]
> A new bug report from @Kittyluvr42
> 
> The master key to the kennels fails on firefox. The page reloads but the stable doesn't change. Looking at the network debugger it looks like it's throwing an NS_BINDING_ABORT error, maybe a security issue with how that's sending?
> 
> Email 	[liony3@gmail.com](mailto:liony3@gmail.com)
> UUID 	55fb9c7b-6832-4c34-8b1f-ba6ecab6c6ad
> User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
> Level 	128
> Class 	wizard
> Dailies Paused 	false
> Costume 	true
> Custom Day Start 	0
> Timezone Offset 	420

could potentially be linked to this issue: https://github.com/HabitRPG/habitica/issues/13883

**Comment by SabreCat** [comment]
Almost certainly duplicate of #13883. Closing for now.
