### ISSUE TITLE
Profile Modal displays poorly at smaller screen sizes

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#14070]
### Description
From a user:
>I’ve noticed some problems with the UI of `div id=”modal-body”` where text goes on top of the avatar and Profile, Stats and Achievements tabs doesn’t fit well in the modal. I’m using Full-HD screen and filling half of the screen with a browser window.
<img width="480" alt="image001" src="https://user-images.githubusercontent.com/78037386/174159847-a58dc41f-5dcc-4151-83fe-a04f197b5713.png">

There are also significant issues with the display of the stats page:
<img width="480" src="https://user-images.githubusercontent.com/78037386/174162714-64d49d8c-6b06-4553-8341-cc559e9ff11d.png">

The fix more than likely does not involve changing the styling on the `modal-body` ID, as that's used throughout the site, but in how the components `website/client/src/components/userMenu/profileStats.vue` and `website/client/src/components/memberDetails.vue` (and `website/client/src/components/avatar.vue` within `memberDetails.vue`) are rendered at various screen sizes within `website/client/src/components/userMenu/profile.vue`. 

The navigation bar should also be updated to degrade more gracefully, with all three options on a single line.

**Comment by scootyboots** [comment]
Could I take a crack at this? I've got a fix working locally at least for the top header of the profile modal. 

Also is this a duplicate with https://github.com/HabitRPG/habitica/issues/13944 ?

**Comment by CuriousMagpie** [comment]
...yes, it does appear to be a duplicate (sigh). When you write the PR, reference both issues!

(can you do me a favor and go comment in #13944 ? GH is being annoying and not letting me assign you to it!)
