### ISSUE TITLE
Suggestion : Information only displayed for members of the guild

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#1408]
Hi,

I'm well aware that you have a lot on your plate right now, and this is not critical at all :)

This is just two suggestion, as I realized today that I was missing those features : 
- I would like to add informations on the guild page, but it's not something that should be seen on the description on the guild list (absolutely no interest and way too long)
- It would be great if we could organize the order of guilds in the guild tab (I want mine to be the first choice, or at least second after "public guild")

Thanks

Keep on the good work,

Regards,
Aiseant

**Comment by wc8** [comment]
Added to [Sort Guilds](https://trello.com/c/ZHGWjX4o)
I also added [Guild Details](https://trello.com/c/qP1J204Z) but, I have a temporary or possibly better suggestion:
Guild pages in the community site forums, and add link to Guild page on forums.
