### ISSUE TITLE
API Input Not Leveling Up

### ISSUE THREAD

**Issue by StanLindsey** [HabitRPG/habitica#141]
I don't think the input from the API will push a character into leveling up. I had 54/40 EXP which only leveled me up once I had manually completed an item on the site. 

Problem seems to be that the check for leveling up isn't done until a manually entered task, may be better to do it on page load and/or API input also?

**Comment by StanLindsey** [comment]
Reopened as this is actually a separate issue from #236.

**Comment by horusofoz** [comment]
@SlappyBag Is this still an issue?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
