### ISSUE TITLE
Gems for the trouble and problem with logging in

### ISSUE THREAD

**Issue by Jajoto** [HabitRPG/habitica#1410]
Hello!

I didn't get extra gems for the trouble. I got only four that I lost because of this bug (bug from yesterday = disapearing of exp, money, armour, shield and gems). I would like to get extra gems too. :)

My ID: f6d401ca-7e94-4961-b9b3-b85c8c8b5d66
Username: Jajo

edit:
Oh nice... I logged out and now I'm trying to log in but when I click at the button "Login/Register" nothing happens...
And I got message at the screen "Not authenticated, can't sync, go to settings first.". I click at login and nothing happens. There should be chart with login and password but it doesn't appear.

edit2: Now it works. It fix itselfs. ;)

**Comment by lefnire** [comment]
Ran tokens script again, you should be set now.

You should probably use the main site for now. herokuapp's in alpha testing right now, meant for people willing to get their avatars dirty until we've ironed out the bugs. 

Login modal issue logged here https://github.com/lefnire/habitrpg/issues/1412 , closing so we can follow up there.

**Comment by Jajoto** [comment]
Thank you for gems :) 
I use the main site. It's very slow but don't have so many bugs.
