### ISSUE TITLE
Login not rembembered

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1411]
If i leave the website (habitrpg.hherokuapp.com) for some time (don't know exactly after how many times exactly this happen, it may be when the session end) the next time I visit the site i get redirected to the static front page (I typed only habitrpg.herkouapp.com) but i'm already logged in because if I type in the address bar the website url then it opens the app.

**Comment by litenull** [comment]
Thats the session. We should increase the expiry time.

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/commit/e5bafe7f0bb5ca9727d422365b22938ad5c20359
