### ISSUE TITLE
Login modal faded

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1412]
Sometime, not always, on the static front page the login/sign up modal is opened by default but with the class 'fade'.

It doesn't happen always and no console error is logged.

The "Play" button is not clickable because the modal is there but with `opacity: 0`.

It should have `display: none`.

![schermata del 2013-09-03 12 55 49](https://f.cloud.github.com/assets/589911/1072128/9ecd8a6e-1488-11e3-8dd7-bbb0a7b74ae8.png)

**Comment by litenull** [comment]
Its faded by default. Please add console errors (as you can see there are 14) next time.

**Comment by paglias** [comment]
it's faded but should have display: none, now it's only opacity: 0 and it
covers the habitrpg logo or when you scroll the play button making it not
clickable.

Errors are not about css but cross origin frames not allowed:

Blocked a frame with origin "http://player.vimeo.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". Protocols, domains, and
ports must match.
Blocked a frame with origin "http://habitrpg.herokuapp.com" from accessing
a frame with origin "http://player.vimeo.com". Protocols, domains, and
ports must match.
2Blocked a frame with origin "http://player.vimeo.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". Protocols, domains, and
ports must match.
Blocked a frame with origin "http://ct1.addthis.com" from accessing a frame
with origin "http://habitrpg.herokuapp.com". Protocols, domains, and ports
must match.
Blocked a frame with origin "http://platform.twitter.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". Protocols, domains, and
ports must match.
Blocked a frame with origin "https://accounts.google.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". The frame requesting
access has a protocol of "https", the frame being accessed has a protocol
of "http". Protocols must match.
Blocked a frame with origin "http://static.ak.facebook.com" from accessing
a frame with origin "http://habitrpg.herokuapp.com". Protocols, domains,
and ports must match.
Blocked a frame with origin "https://s-static.ak.facebook.com" from
accessing a frame with origin "http://habitrpg.herokuapp.com". The frame
requesting access has a protocol of "https", the frame being accessed has a
protocol of "http". Protocols must match.
Blocked a frame with origin "https://apis.google.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". The frame requesting
access has a protocol of "https", the frame being accessed has a protocol
of "http". Protocols must match.
Blocked a frame with origin "https://www.facebook.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". The frame requesting
access has a protocol of "https", the frame being accessed has a protocol
of "http". Protocols must match.
L'URL inserito non è consentito dalla configurazione dell'applicazione.:
Uno o più degli URL inseriti non sono consentiti dalle impostazioni
dell'applicazione. L'URL deve corrispondere a quello del Sito Web o della
pagina principale dell'applicazione e il dominio deve essere un
sottodominio di uno dei domini dell'applicazione.
ping:1https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habitrpg.herokuapp.com&origin=1&redirect_uri=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D26%23cb%3Df19a5a29dc%26domain%3Dhabitrpg.herokuapp.com%26origin%3Dhttp%253A%252F%252Fhabitrpg.herokuapp.com%252Ffb2c914b%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey
Blocked a frame with origin "https://www.facebook.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". The frame requesting
access has a protocol of "https", the frame being accessed has a protocol
of "http". Protocols must match.
Blocked a frame with origin "http://platform.twitter.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". Protocols, domains, and
ports must match.
Blocked a frame with origin "https://platform.twitter.com" from accessing a
frame with origin "http://habitrpg.herokuapp.com". The frame requesting
access has a protocol of "https", the frame being accessed has a protocol
of "http". Protocols must match.

2013/9/3 litenull notifications@github.com

> Its faded by default. Please add console errors (as you can see there are
> 14) next time.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1412#issuecomment-23708548
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by litenull** [comment]
There are no js errors ? I thought there were. hmmm
I've experienced this yesterday, but with errors that were blocking the logic.

**Comment by litenull** [comment]
Yep, I've consistently reproduced this. If you scroll middle page, the modal is there and is over the button. login-modal should be set to display:none in css. It gets set to display:none when you close the modal. Good call Matteo!

**Comment by lefnire** [comment]
fixed
