### ISSUE TITLE
Rewrite error message.

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#1416]
Over on Heroku, this wall of text popped up of a sudden:

503: <!DOCTYPE html> <html> <head> <style type="text/css"> html, body, iframe { margin: 0; padding: 0; height: 100%; } iframe { display: block; width: 100%; border: none; } </style> <title>Application Error</title></head> </head> <body> <iframe src="//s3.amazonaws.com/heroku_pages/error.html"> <p>Application Error</p> </iframe> </body> </html>

**Comment by paglias** [comment]
Could you provide some more information? If there isn't a longer error message visible please open the console ( [How to open the JavaScript console in different browsers?](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers) ) and report any error you can find there.

Thanks!

**Comment by lefnire** [comment]
This one was interesting. Right after @Eiron reported this I checked the heroku logs and the server had disconnected from mongohq, couldn't re-establish connection. No errors leading to the disconnect. I was seeing the error message too as a result - restarting the app fixed the issue. I'll keep an eye on this one

**Comment by lefnire** [comment]
havne't seen this since, we should be good
