### ISSUE TITLE
URL redirect from login page not working properly

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#14176]
Reported by @citrusella via email:

### General Info
- **UUID:** 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- **User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

### Description
> If the register URL has a redirectTo in the query, after signing up this redirects to *exactly* what the query says and doesn’t append it to [habitica.com](http://habitica.com/) first. For instance, I duplicated a tab of Aspiring Comrades into a container tab so I could make a new account to test something, and after moving from the sign-in page to the register one the URL was https://habitica.com/register?redirectTo=%2Fgroups%2Fguild%2F2ff9822b-27f2-4774-98da-db349b57a38e which after entering information and registering, tried to send me to https://groups/guild/2ff9822b-27f2-4774-98da-db349b57a38e which of course didn’t work. I don’t know if this is specific to the register screen specifically but it’s where I encountered this.

#### Comments
We recently put in a [redirect vulnerability fix](https://github.com/HabitRPG/habitica/commit/d76d5f2cf19899305470ee43e6409f6840b4ed5a) of which this is an unfortunate side effect; the fix for this will likely require a significant knowledge of regex. 

Here is the portion of the code from `website/client/src/components/auth/registerLoginReset.vue` where the fix will _probably_ need to happen, line 758 & following:

```
sanitizeRedirect (redirect) {
   if (!redirect) return '/';
   let sanitizedString = DOMPurify.sanitize(redirect).replace(/\\|\/\/|\./g, '');
   sanitizedString = `/${sanitizedString}`;
   return sanitizedString;
},
```

**Comment by antonderegt** [comment]
Please excuse me for not asking for the okay to work on this issue. The fix was so small I just went ahead and pushed a PR.

I hope you don't mind 😄.

Let me know what you think!

**Comment by CuriousMagpie** [comment]
No worries! If it was an easy fix, all the better! :)
