### ISSUE TITLE
Challenge Category list is copy/pasted 4 times in the client code

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#14175]
The list to define the different challenge categories is copy and pasted in 4 different locations. Instead of having this long list in the code 4 times, it should be moved to the common code and added to the content definitions there.

It could also be useful to return it with the `/content` api call

[Github search to find all occurrences of the list](https://github.com/HabitRPG/habitica/search?q=%7B+++++++++++label%3A+%27time_management%27%2C+++++++++++key%3A+%27time_management%27%2C+++++++++%7D)

**Comment by Tundrian** [comment]
Is anyone currently working on this issue? If not I'd love to contribute to this. Please let me know if there's anything I need to be aware of before diving in.

**Comment by CuriousMagpie** [comment]
@Tundrian I don't know anything in particular that you need to know--this is essentially a refactor to streamline the codebase a tiny bit. 😄

**Comment by anishcode19** [comment]
Hi, I'm interested in contributing to this issue. This would be my first open-source contribution. Can it be assigned to me?
