### ISSUE TITLE
Error: Forbidden on habitica.com

### ISSUE THREAD

**Issue by MmKargar** [HabitRPG/habitica#14198]
I get `Error: Forbidden` on habitica.com.
![image](https://user-images.githubusercontent.com/11253027/187449821-cc2f2cd9-afbc-43de-b477-e3c64d3abd47.png)

**Comment by CuriousMagpie** [comment]
This has been corrected in #14182 and should be in production shortly. In the meantime, you will just need to retype the website address into your address bar on the browser.
