### ISSUE TITLE
[Feature Request] Repeated dailies with times per week instead of specified days

### ISSUE THREAD

**Issue by mgatten** [HabitRPG/habitica#142]
Some tasks need to be done a minimum number of times per week, but the days they are done on don't matter.

A good example is going to the gym. I want to make sure I go to the gym at least four times a week, but the specific days I go don't matter. Another example would be housecleaning - I want to vacuum the floor at least three times a week, but I don't care when I do it. 

It would be nice to be able to create a daily task where, instead of selecting which days I must do it, I specify how many times I must do it in a week or in a month. A small experience reward would be awarded each time I do it, with a bonus at the end of the week or month if I've met the minimum number of times for that period. (There could also be a bonus for doing it more than the minimum number of times or for finishing early by getting to the minimum number of completion a day or two early.)

**Comment by racuna** [comment]
I agree with that. Maybe is not the correct way to handle, but works for me until @lefnire implements something like you describe. I wrote on my habits box a task like this: "(+) (-) weekly - call parents"

**Comment by wc8** [comment]
This would be great.
Taking it a step further, add minimum times per custom period.
Examples: 
- Drink 8 glasses of water daily
- Take medicine every 8 hours
- Take medical statistics every 6 [waking] hours
- Exercise 30 minutes 4 times per week
- Read (at least) 1 hour 4 times per week
- Brush & Floss twice a day

**Comment by benmanley** [comment]
+1

Would be great to group them into a Quest (#140) with a Boss Battle (#66) at the end.

**Comment by hookang** [comment]
Good ideas. Added to Master list of Features #169. Issue closed for organization.

**Comment by racuna** [comment]
I can't see this in the Master List.

I think of a counter of days for each daily task (by default 1) but anyone can change it (to 7 if weekly, 30 if monthly). So when I check the task the day counter turns to 0 again. If the day counter is greater than the number you lose HP.

Maybe can be hours so the default would be 24 in that case.

**Comment by wc8** [comment]
[Completion Quotas](https://trello.com/c/E5CVJlW6)

**Comment by igorsantos07** [comment]
Cool! Ten years later and this is the first result I get when looking for this simple feature most generic habit trackers have.
Ten years and you still can't configure "eat salad at least 5 times a week" 👌🏻

**Comment by harumhl** [comment]
I submitted a Google form to submit the request and emailed them that I'd like to work on it. Let's see if it gets approved. (I didn't see it as an existing Issue)

**Comment by igorsantos07** [comment]
Yeah, it looks like they're moving out from publicly viewable roadmaps into private ones - the Trello board links I see around here got made private, and the feature request moved to a Google Forms as well. Not a great way to run open source or communicate with users, but... I guess they had their reasons :man_shrugging: 

Edit: this was also requests on #258, a couple of days after the original report here.
