### ISSUE TITLE
add `quantity` body parameter to apidocs for "Purchase Gem or Gem-purchasable item"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#14217]
In the API, the `https://habitica.com/api/v3/user/purchase/:type/:key` route allows you to specify the amount of items you wish to buy (e.g., more than one Hatching Potion at once, or more than one gold-purchasable Gem at once). You do that by supplying a body parameter called `quantity`, with the value being an integer indicating the amount of the item to buy.

This issue is to get the `quantity` option added to the apidoc page in this section: [Purchase Gem or Gem-purchasable item](https://habitica.com/apidoc/#api-User-UserPurchase)

It should be added in a similar way to what's been done for the [Purchase Hourglass-purchasable item](https://habitica.com/apidoc/#api-User-UserPurchaseHourglass) route.

I'm labelling this as "good first issue". You can find the correct file to modify by doing `git grep "Purchase Gem or Gem-purchasable item"` in your local install.

**Comment by Alys** [comment]
I've added the "notify helpers" label to remind me to remove the tip about using `quantity` from [Application Programming Interface > Errors in the API Documentation](https://habitica.fandom.com/wiki/Application_Programming_Interface#Errors_in_the_API_Documentation) on the wiki.

**Comment by ATommasi** [comment]
I can take care of this
