### ISSUE TITLE
force ssl redirect

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1422]
localstorage & cookie get mis-matched if you go between http & https. When you're on the tasks page as anon, there's no way to logout and you have to go in and clear localStorage. We need to force ssl, and also do something about them if they have localStorage or cookie but yet aren't properly authenticated

**Comment by paglias** [comment]
@lefnire 

> and also do something about them if they have localStorage or cookie but yet aren't properly authenticated

do you mean about security? we could encrypt everything and store the key in the user object in the db

**Comment by lefnire** [comment]
no, what's happening is this. If they have localStorage, but not a cookie authenticating them, it gives them strange errors. the obvious example is switching between http & https - different cookie domains, so one will log you in and the other will give you 401 errors. The other example I can think of is if the cookie expires, but your localStorage is still there. Still not sure what would happen in that case.
