### ISSUE TITLE
FAQ Code Refactor

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#14246]
The FAQ code needs to be refactored to take into account differing numbers of questions between platforms, retired questions, and reordered questions.

Files affected (these may not be the only ones):
- `website/client/src/components/static/faq.vue`
- `website/common/script/content/faq.js`
- `website/common/locales/en/faq.json`
- `test/content/faq.js`

**Comment by SabreCat** [comment]
Specific things to overhaul:

* `faq.js` in `common/script/content` supposes that all platforms will have the same number of questions and that we will never remove a question from the list. So...
  * Change the structure of `common/script/content/faq.js` to something like `{ platformA: [ 1, 2, 4, 8 ], platformB: [ 2, 3. 4. 5 ] }` or similar
  * ...somehow keep the actual response in the content API the same? But if a breaking change is unavoidable, coordinate with mobile so the apps can parse the server data correctly
* `faq.vue` doesn't actually use the content API or even the relevant common script, it just maps a hardcoded list of headings to string tokens by index. So...
  * Add headings to the FAQ API
  * Make `faq.vue` call the API, or at least pull data about available FAQ questions from `common/script/content`

**Comment by adamfitzgibbon** [comment]
I can help with this! It seems like there are three separate action items here though. so I'm going to start with the hardcoded lists in `faq.js` first and have subsequent PRs for the API changes

**Comment by CuriousMagpie** [comment]
Hi there! I'm working on this--we usually only have one contributor working on an issue at a time. Is there anything else that strikes your fancy?

**Comment by adamfitzgibbon** [comment]
Oh sorry, didn't know if you were active on it or not. I'll look at the other issues thanks

**Comment by veeeeeee** [comment]
Changing our approach to this problem.
