### ISSUE TITLE
Things to put in Bailey notif before we go live

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1426]
- mention of veteran wolf
- put old.habit back in when we get it running

**Comment by lefnire** [comment]
feel free to add to list @lemoness

**Comment by lemoness** [comment]
Between those and mobile app, I actually think you're pretty well-covered... maybe mention the Meet The Staff and Meet the NPCs series happening on Tumblr?

**Comment by lefnire** [comment]
√
