### ISSUE TITLE
The Progress button doesn't work sometimes

### ISSUE THREAD

**Issue by Zequez** [HabitRPG/habitica#143]
It throws "Uncaught TypeError: Cannot read property 'date' of null" on the console. Tested on Chrome and on Firefox.

It's just on some tasks, can't figure out what's special about them.

**Comment by horusofoz** [comment]
@Zequez Can you confirm if this is still happening? I've been testing on both Chrome and Firefox and have not been able to reproduce the error.

**Comment by Zequez** [comment]
Still happening, although I think I was able to reproduce the error.

It only happen on "Habits", and it only happen if you create an habit and you immediately change it to positive-only or negative-only, and then you click to fulfill the habit. After you do this doesn't matter if you change it back to "dual", the progression graphic doesn't appear UNLESS you reload the page, but remember, only if you change it back to dual.

Here is another aspect, if you have a dual habit, and you fulfill it, you can click the progression graphic without trouble. But then, if you change it to positive-only or negative-only, AND you fulfill it then, when you click on the progression graphic, and you see it, BUT, you only see the times you fulfilled it with the dual-spec, and you get "Uncaught TypeError: Cannot read property 'date' of undefined" on the console.

My guess, the date is not being saved for positive-only or negative-only. Or something about that.

**Comment by horusofoz** [comment]
Thank you for the additional detail. Makes determining your issue much Much easier.

Though I never received your error message, I previously encountered the issue where I could not see progress on newer Habits under #210. 

Tyler's explanation from that ticket 

> "It's true, you have to have 2 items of progress (2 days passed, 2 +- clicks, and note: +only and -only don't get progress) - but it sounds like it's still an issue beyond that for people?"

Also it was advised that +only and -only progress is planned.

You error message is in the console so I suspect it is the expected behaviour/known issue which is planned to be addressed under https://trello.com/card/habit-shading/50e5d3684fe3a7266b0036d6/67. I recommend you vote for that card to increase it's visibility to the devs.

@lefnire Can you confirm the above behaviour is the known issue?

**Comment by PiNotEqual3** [comment]
I have the same problem.

I belief the error accrues at https://github.com/lefnire/habitrpg/blob/master/src/app/index.coffee#L239

Looks like an empty object got into the history. Here are the IDs of the object:

```
data-toggle-id="9468b6e0-0a28-4b2b-93a2-ebce76bf8a13-chart"
data-hide-id="9468b6e0-0a28-4b2b-93a2-ebce76bf8a13-edit"
data-history-path="_user.tasks.9468b6e0-0a28-4b2b-93a2-ebce76bf8a13.history"
```

Hope that helps.

**Comment by horusofoz** [comment]
@SlappyBag @lefnire Dev triage? e.g. "Critical", "Important" or "Later".

**Comment by horusofoz** [comment]
@ZequeZ & @PiNotEqual3 Is this still happening for with of you?

**Comment by PiNotEqual3** [comment]
For my old task it still does not work.
For new tasks I can not reproduce the bug.
@ZequeZ can you reproduce the bug?

**Comment by horusofoz** [comment]
@PiNotEqual3 The bug has been fixed. unfortunately we cannot make it work retroactively on those previous habits.

Your options are to recreate or continue with them as they are.

**Comment by PiNotEqual3** [comment]
Cool, thanks a lot for fixing it!
Nice project with nice people here :)
