### ISSUE TITLE
Next Hourglass showing incorrect month estimate

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica#14319]
User bought a 12 month sub Oct 2021, it renewed Oct 2022 and we're saying they will get their next hourglass in october. that should be november.

9f7155e8-dbb6-4795-a522-b861b125daec 

<img width="438" alt="Screen Shot 2022-10-28 at 1 17 01 PM" src="https://user-images.githubusercontent.com/12453119/198697255-66b27ba5-0f6c-434c-ad31-ea84d05aa86d.png">

**Comment by melvio** [comment]
I have a similar issue, which also shows a wrong subscription end date. I bought a yearly subscription on 16 Sept. 2022, but it already shows 10 Feb 2023 as the date for the last subscription benefit. 
![image](https://user-images.githubusercontent.com/31448155/215497287-87114819-bade-477c-b6df-70cb7f5ba99f.png)

**Comment by saraolson** [comment]
@melvio i believe that's actually in US date format, so oct 2nd 2023. you can reach out to admin@habitica.com with your username and they can look into it to be sure tho!
