### ISSUE TITLE
Purchased thunderstrom potion to use on my dragon egg and dragon is greyed out

### ISSUE THREAD

**Issue by mjfighter** [HabitRPG/habitica#14369]
<img width="99" alt="image" src="https://user-images.githubusercontent.com/118700090/202938043-3fad23ed-80e5-41f8-94af-8c9e4cc1c5ed.png">

I attached a picture of it. Any ideas?

**Comment by mjfighter** [comment]
I just tried getting another mount with a normal potion and it worked. Is it just a bugged hatching potion?

**Comment by CuriousMagpie** [comment]
Do you have a dragon egg in inventory? 

In the future, please use "Report A Bug" form for these sorts of questions and concerns. Thanks!

**Comment by mjfighter** [comment]
Yea I have a decent amount of dragon eggs in my inventory! 
i just wasn't able to use the dragon after turning him into a mount

**Comment by mjfighter** [comment]
I also just bought a new thunderstorm potion and now I cant even feed the dragon
<img width="103" alt="image" src="https://user-images.githubusercontent.com/118700090/203610828-158007f3-8cfc-4b8a-9b07-d3a7f1a57f1b.png">
<img width="97" alt="image" src="https://user-images.githubusercontent.com/118700090/203610885-3f8df41d-28d8-47d3-bd69-8650f396ca9e.png">
He doesnt have a health bar

**Comment by CuriousMagpie** [comment]
You can't feed the dragon because you already raised it into a mount. You can only do that once. In order to rehatch the pet, you need both an egg and potion in your inventory.

I am closing this issue, as the application is working as intended. Please use the "Report a Bug" link located under the "Help" menu in the header with any future concerns. Thanks!

**Comment by mjfighter** [comment]
If you read the message it says i bought a NEW dragon after the last one DIDNT get turned into a mount after feeding it the appropriate amount of times.

**Comment by CuriousMagpie** [comment]
Your initial message was about not being able to use your dragon pet. The mounts are in a different portion of the interface. Pets are greyed out like that when you are missing either an egg or a hatching potion. 

Please follow the appropriate channels as outlined above if you wish to discuss this further. That will provide us with some more information to work with, like your user ID, operating system, etcetera. There's only so much we can do with a tiny screen capture such as the one you provided.
