### ISSUE TITLE
"Unticking" a yellow or red daily or ToDo removes you 10% less gold than it awards

### ISSUE THREAD

**Issue by Zequez** [HabitRPG/habitica#144]

**Comment by wc8** [comment]
What's the goal of this? Are you trying to repeat a daily?
My concern would be user confusion (checkbox in most apps just does done or not done, not half or 10% undone).

**Comment by lefnire** [comment]
It's just a rounding issue with the up down algorithms, we'll get all that squared away

**Comment by Zequez** [comment]
@wc8

> What's the goal of this? Are you trying to repeat a daily?
> My concern would be user confusion (checkbox in most apps just does done or not done, not half or 10% undone).

Maybe the user just ticked the daily by accident and he needs to untick it.

**Comment by wc8** [comment]
@ZequeZ Of course—I had been reading through so many feature requests, and hadn't noticed the issue myself, that I totally misread your post as a desired outcome. Sorry.

**Comment by horusofoz** [comment]
@lefnire Shouldn't this ticket be closed as a duplicate of #56 ?

**Comment by lefnire** [comment]
yesm. #56
