### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by anabeatrizzz** [HabitRPG/habitica#14413]
"an monstrous" should be "a monstrous".

https://github.com/HabitRPG/habitica/blob/51e8aa341dc2d46aa102b3d9014b22584aa8a756/website/common/locales/cs/questscontent.json#L316

**Comment by CuriousMagpie** [comment]
Thanks, @anabeatrizzz. We prefer to receive these kinds of reports via email, but I've updated my ongoing string fix branch with this.

**Comment by anabeatrizzz** [comment]
@CuriousMagpie oh, ok. Can I send a report to the email found at About > Report a Bug next time?

**Comment by CuriousMagpie** [comment]
Yep, ***@***.*** -- just put it to my attention (Natalie)
--
Natalie Luhrs
my pronouns are she/they
