### ISSUE TITLE
text overflow in donation button in italian

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#14420]
>The text inside the donation button goes overflow in italian, it can be fixed by assign the "text-overflow: hidden" property to the div that contains the text! Unfortunately I cant check your source code with my phone but I am sure there can be alternative solutions to solve this small visual bug!

![Screenshot_2022-12-22-23-39-24-939_com android chrome](https://user-images.githubusercontent.com/102926641/209391232-e2b3a4a3-1d64-4231-9472-6ad5d03be832.jpg)

**Comment by CuriousMagpie** [comment]
Will be fixed with #14414
