### ISSUE TITLE
move user.tasks object to array (or arrays)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1442]
once the derby site is completely dead (we still have a lot of work), let's either move `user.tasks` to:
1. `user.habits`, `user.dailys`, `user.rewards`, `user.todos`
2. `user.tasks` (array)

Derby wanted user.tasks to be an object, and maintained sorting via `habitIds`, `todoIds`, etc in order to utilize a construct it used called refLists. Since we transform the user to the API in arrays, let's change the Schema to use that by default. This will also give us the benefit of using Mongoose subdocs, making task-finding really easy on the server. That plus unique insertions, etc etc.

This one's for me.

**Comment by lefnire** [comment]
@MagicMicky - I switched to the arrays format, but you're currently using user.tasks. I'll temporarily put user.tasks back in until you can migrate to the arrays

**Comment by paglias** [comment]
Is this coming together with subdocs?

**Comment by lefnire** [comment]
Yeah, I'll b working on the .tasks => habits/dailys/etc subdocs this weekend, I'll get back to you ~Monday with the progress and I'll see if I can merge them from `challenges` to `develop`.

**Comment by lefnire** [comment]
Ok, this is mostly done and just needs to be thoroughly tested. It's on the `challenges` branch, the primary commit is https://github.com/HabitRPG/habitrpg/commit/93a1e2e3485e445e42cb3f2a3febb66de3b602ba (which also handles script templates and ads, see the commit message). It also depends on https://github.com/HabitRPG/habitrpg/commit/a9d335fb6bc31c871e7b14a85c43af0cdee418c0 . Unfortunately I couldn't cleanly separate the code enough functionally, but did my best just for organization. Anyway, the point is if you want to start testing it now, test the `challenges` branch - but we're not going to be able to cherry-pick commits, we'll just have to wait for `challenges` to be merged into `develop`
