### ISSUE TITLE
gifted subscription benefits not showing up when viewing subscription page

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#14432]
> User ID: 2c672825-b7ba-4cd6-816e-a6f353d4e616
> Details:
> My account is not indicating that I have a subscription on the website [...].

![Screenshot_20221225_223719_Chrome](https://user-images.githubusercontent.com/102926641/209582624-fc4e23db-19b1-497b-985c-b48730ed6707.jpg)

**Comment by pratikjpatil** [comment]
is this issue still open?

**Comment by saraolson** [comment]
we've made a lot of changes to our subscriptions since this, and haven't received any new reports for awhile. this is likely resolved.
