### ISSUE TITLE
Minor: Pet Count now incorrect

### ISSUE THREAD

**Issue by Mayjest** [HabitRPG/habitica#1445]
With the new Veteran Wolf pet (much appreciated) my pet count went up to 3/90. Technically there's now 91 total pets...

**Comment by Medaro** [comment]
New users can't get the veteran pets and the 'max' is hardcoded -- having 91/90 wouldn't break anything and could just be a bonus. The amount should reflect how many pets a normal user can achieve.

**Comment by SabreCat** [comment]
Except that somebody with a Veteran Wolf will now achieve the "Beast Master" achievement one pet early. Not the end of the world, but rather weaksauce.

**Comment by Mayjest** [comment]
As I said - minor. But regardless, the value shouldn't be hardcoded. It shouldn't be the number of pets a normal user can achieve - it should be the number of pets _this_ user can achieve. In my - and most other users right now - cases, that's 91, but a new user's is 90. 

I don't know the code - javascript/git/etc not being my thing - but it shouldn't be hard to a have a 'calcPetTotal' function. Take the number of normal pets available, plus any special pets if the user has them. The Beast Master achievement can reference the same function. There's going to be more special pets in the future so this is going to become necessary.

**Comment by paglias** [comment]
Since special pets actually can't be achieved I would remove them from the
pets count

2013/9/10 Mayjest notifications@github.com

> As I said - minor. But regardless, the value shouldn't be hardcoded. It
> shouldn't be the number of pets a normal user can achieve - it should be
> the number of pets _this_ user can achieve. In my - and most other users
> right now - cases, that's 91, but a new user's is 90.
> 
> I don't know the code - javascript/git/etc not being my thing - but it
> shouldn't be hard to a have a 'calcPetTotal' function. Take the number of
> normal pets available, plus any special pets if the user has them. The
> Beast Master achievement can reference the same function. There's going to
> be more special pets in the future so this is going to become necessary.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1445#issuecomment-24142125
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by katfang** [comment]
Not wholly sure where to leave this comment, but this seems at least somewhat related. When I unlocked the stable, the Veteran Wolf was already there. I don't actually have the pet, though...?

**Comment by lefnire** [comment]
> When I unlocked the stable, the Veteran Wolf was already there. I don't actually have the pet, though...

it's there but you don't have it? what do you mean?

**Comment by Shaners** [comment]
@katfang can you see the veteran wolf in your stable now? Can you click on it to use it as a pet?

**Comment by katfang** [comment]
@lefnire As far as I can tell, I never hatched a wolf. It was there as soon as I unlocked the stable. Is this supposed to be right? I did also have a wolf egg that disappeared (I never hatched it), but I think that the wolf egg was still there after I saw the Veteran Wolf. I mean that the egg disappeared afterwards. 

@katfang Yes, I see it in my stable, and I can click on it and use it.

**Comment by paglias** [comment]
If you signed up before the 4th of september it's normal that you have the veteran wolf, it's been given to anyone who signed up before that date

**Comment by paglias** [comment]
Fixed
