### ISSUE TITLE
Can't log in (incorrect password)

### ISSUE THREAD

**Issue by NotGus** [HabitRPG/habitica#1446]
So I can't remember my password and I was somehow logged out. But, I have my little number that I used to join a group. Can I use that to log back on? I really want to continue using habitrpg.

**Comment by lefnire** [comment]
on it now

**Comment by ianoff** [comment]
Related: I can log in to the derby version at old.habitrpg.com, no problem, but not the rewrite:

![image](https://f.cloud.github.com/assets/2190703/1096263/ae7ea4be-16fb-11e3-857a-074d317d08d5.png)

Exact same UN / pass, same case on username (lower). I use 1Password, if that helps; do you think the autofill of the password field is messing it up?

Edit: yeah, that was it: password managers like 1Password apparently mess up the login process on the Angular rewrite only. Weird.

**Comment by lefnire** [comment]
If you get a chance Meagan, can you peak at the code for the old / new mismatch? I gotta jump back to work, but will dive in again tonight.

In the mean time, I added PW-reset, and then after you're in PW-change (to put back to your normal PW):

![reset](https://www.evernote.com/shard/s17/sh/9659ebfe-946f-4eef-ae69-23c9f7086fab/354324322e9cfbf2c6948d8fdd3d1752/res/20608a35-0405-41ff-ba16-a04613dc31b1/skitch.png?resizeSmall&width=832)

![change](https://www.evernote.com/shard/s17/sh/59a7d1d5-25c5-4427-9a1b-0c987c224030/f0400dd4770c07f7f3a78f424f92264a/res/cc97a260-1916-4f11-883a-83994b15922e/skitch.png?resizeSmall&width=832)

**Comment by ianoff** [comment]
I got in, just had to do the PW by hand and not use 1Pass and it was fine.

here's a peek: 1Pass is trying to fill in both the login and registration (see the faded back box on the left) and there's a message in the console: `POST https://www.habitrpg.com/api/v1/user/auth/local 401 (Unauthorized)`

![screen shot 2013-09-06 at 9 13 23 am](https://f.cloud.github.com/assets/2190703/1096420/b94f7370-16fe-11e3-9f72-551f25483b18.jpg)

**Comment by lefnire** [comment]
there's definitely a 1pass ticket floating around, i'll need to find it and reference when i hit this next. The gist was 1pass was incompatible with how derby forms with `x-bind=submit..` handled things. Had a conversation over on 1pass forum (linked said ticket) about how to mitigate that once we're off Derby, so we'll just need to work those suggestions into our angular forms. In the mean time, let's have people blacklist habit for 1pass for now 

Edit: might just be we need to add `action='POST'` to all forms, even if they have an `ng-submit`

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/issues/1246 is the issue i was referencing. I just added an `action='POST'` to the form, can you see if that solved the issue?

i'm marking this ticket down in prio, after some to-and-fro in the issue queue, I realized many of the login issues weren't login issues at all, but API errors for derby-corrupted user data. This one in particular simply looks like the same issue as https://github.com/lefnire/habitrpg/issues/1246 , which black-listing Habit for LastPass or 1Pass is the temporary solution till we can get around to this

**Comment by paglias** [comment]
I think we can continue on #1246 since they seem exactly the same issue related to 1pass
