### ISSUE TITLE
Suddenly died twice in a row

### ISSUE THREAD

**Issue by wisteriacs** [HabitRPG/habitica#1447]
My first time going on the regular HabitRPG site this morning. And before it was due to reset. I set myself back up again using the dangerzone setting on old.habitrpg.com, but I wanted to let ya know.

**Comment by lefnire** [comment]
has this recurred at all? I have a hunch it was just a vestige of moving off old.habit, which is now officially dead

**Comment by wisteriacs** [comment]
It was when they were both existing , and I haven't seen it again. So probably no longer a worry. 

Brittany

**Comment by lefnire** [comment]
woo!
