### ISSUE TITLE
ToDos Hurt Health

### ISSUE THREAD

**Issue by cbleisch** [HabitRPG/habitica#145]
I am a big fan of this project and am already using it consistently. Thank you for all the effort and time you have already spent developing Habit RPG.

Currently I run into a problem daily where the items in my ToDo list are hurting my health. I wasn't sure at first, but after two days I noticed my health dropped by exactly the same number of items I had on my ToDo list each time. I don't think my Dailies are causing this error because each day I have been completing all tasks therein.

Thanks again for your work.

~Charles Bleisch

**Comment by lefnire** [comment]
keep an eye on it now. I made a _lot_ of changes recently (like 30m ago) and I believe this to be fixed with those changes. Re-open if not

**Comment by cbleisch** [comment]
I just checked and the items in my ToDo list still hurt my health.
