### ISSUE TITLE
I don't get eggs and potions

### ISSUE THREAD

**Issue by Jajoto** [HabitRPG/habitica#1454]
It's been a long time since I got eeg or potion. I don't know what's going on. Today I've clicked all the pluses and still haven't got nothing. It's about 2-3 weeks now.

User ID: f6d401ca-7e94-4961-b9b3-b85c8c8b5d66

**Comment by paglias** [comment]
Notifications are still missing from the new website but you still get
eggs/potions. Checked in the inventory?

**Comment by Jajoto** [comment]
In the inventory I have 13 potions and no eggs. I'm not sure if I had all of them.

**Comment by paglias** [comment]
They should drop as usual but wait for an answer from @lefnire who will
surely tell you something more

**Comment by Jajoto** [comment]
I've already checked so many dailies and habits that I've leveled up 2 times and I still have 13 potions. There is something wrong.

**Comment by lefnire** [comment]
I'll be getting to this as soon as I start porting drop notifications. sorry @Jajoto , thanks for having patience with us - this is a nights / weekends project for all of us

**Comment by Jajoto** [comment]
Today I have 14 potions (one more than yesterday) so I do get potions - it's just lack of notifications. :) 

Now I think I have the same problem as people in this topic: https://github.com/lefnire/habitrpg/issues/1048?source=cc I have a lot of potions but no eggs at all.

**Comment by lefnire** [comment]
that was mentioned in the bailey notif. Feature to be ported, let's follow up at https://github.com/lefnire/habitrpg/issues/1394
