### ISSUE TITLE
API doc page isn't mobile-friendly

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#14569]
user reports:

> The api documentation page https://habitica.com/apidoc/ isn't mobile friendly on my device.
> my screen width is 501px.
> ![Screenshot_20230401-234017](https://user-images.githubusercontent.com/102926641/230141668-2c19e856-8445-4a01-b914-55b308a76944.png)

**Comment by Isaius** [comment]
Hey. I think we need to assess what changes are necessary in order to enhance the overall experience on mobile but it wont be a light lift. At first I'd say that just hiding the sidebar menu would be a good start. I can work on that and maybe come up with some aspects that need update.

**Comment by CuriousMagpie** [comment]
If you want to take a stab at improving the experience at least a little bit on mobile, go for it. Thanks so much, @Isaius

**Comment by qudwl** [comment]
Is this currently being worked on?

**Comment by qudwl** [comment]
If it isn't being worked on, can I take a stab at it?

**Comment by Isaius** [comment]
Sure, go for it. I got a few things that have higher priority so I can't finish at the moment.

**Comment by BrunoViveiros** [comment]
@qudwl are you still working on this one? If not, could I take it?

**Comment by SabreCat** [comment]
We don't design that page, it's generated by [apiDoc](https://apidocjs.com/). So trouble with that layout is more a report for their repo than ours!
