### ISSUE TITLE
Group chat notif

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#1458]
The group chat notification either doesn't exist or isn't working on beta. How will we know when our lovely groups want to chat?

**Comment by lefnire** [comment]
TBP. Keep 'em coming, will give us centralized place to keep track

**Comment by AdrienLemaire** [comment]
bump on this issue. I haven't seen the notification icon in a very long time. Also, as far as I remember, it was only notifying new messages on the party. I suggest to fix and improve the feature by also notifying everytime our username is cited in the party, a group, or in the tavern.

**Comment by snicker** [comment]
I'm contemplating re-adding this feature now that highlighting is a
bit more reliable, I think it went missing a while back

**Comment by AdrienLemaire** [comment]
berzerker in action :)

**Comment by Gaelan** [comment]
Looks like this is done. Close?
