### ISSUE TITLE
500: Internal Server Error, Anonymous user

### ISSUE THREAD

**Issue by supermouse35** [HabitRPG/habitica#1460]
I haven't been able to log in for over 24 hours now. When go to either the main site or the beta site, I am somehow already logged in as "Anonymous," which is obviously not my username (my username is supermouse35, same as this one), and there is an error message that says, "500: Internal Server Error(see Chrome console for more details)." I then try to logout from the "Anonymous" account and try to login with my own account name and password. After I enter the information, I press the "Login" button and... nothing happens. Literally nothing. No error messages, no rejection of the info, just nothing. I have tried in two different browsers (Firefox and IE). I can't even log into the Android app using my phone. Please help? I don't want to lose my data, my character is at level 40 and I've got 56 pets. I've tried clearing my cache and deleting all of my cookies, but it hasn't helped. Thanks.

**Comment by supermouse35** [comment]
PS, I tried changing my password twice, didn't help.

**Comment by Shaners** [comment]
are you using one pass?

**Comment by supermouse35** [comment]
Well, I am using LastPass, if that's what you mean. But I noticed it wasn't working correctly so I deleted the info for Habit and tried entering my login info manually. No luck.

**Comment by lefnire** [comment]
@supermouse35 so you tried doing a reset password, got an email, plugged that new password in and it won't let oyu in?

**Comment by supermouse35** [comment]
Yes, that's correct.

**Comment by lefnire** [comment]
let's follow up on #1446

**Comment by lefnire** [comment]
I'm sorry, I was wrong - not the same issue, it looks like you were being effected by https://github.com/lefnire/habitrpg/issues/1472 . can you try logging in now?

**Comment by poopstick** [comment]
Working now if Firefox, but not in Chrome. Probably need to clear cache, but I've got too much ongoing right now to do that. Will try later.

**Comment by lefnire** [comment]
unfortunately we're using localStorage at present, so you'll need to actually hit the logout button top-right when you get around to it

**Comment by poopstick** [comment]
I can't get past the intro screen in Chrome, so no logout option available.

**Comment by supermouse35** [comment]
Oh yay, I'm back in! Thanks. :D

**Comment by lefnire** [comment]
@supermouse35 this is extremely good news, because judging by the server logs many people were being effected by this. Phew! I think that cleanup migration will have fixed many bugs.

Ok @poopstick this is gonna look a bit daunting. We're using localStorage to store user data, which is really cool because you can now run habit offline (like if your'e in the train) and it will sync up later (same codebase as our mobile app now). However, it kinda makes it hard to clear your session, and we're gonna have to do some special handling of situations like your'e in right now. In the meantime, go to habitrpg.com and then follow the instructions [in this screenshot](https://www.evernote.com/shard/s17/sh/eec8d98a-f9f0-4e83-920e-f5eb83d70384/f0be7cb3671608e7978e3f6a5f21e417) (doesn't matter if you're logged in or not)

**Comment by Laros** [comment]
I still get this error. I was loged in with via FB. even if I log out and back in I still get the error. Also tried with Chrome, Firefox and IE.

**Comment by paglias** [comment]
@Laros could you try following the steps in this screenshot? https://www.evernote.com/shard/s17/sh/eec8d98a-f9f0-4e83-920e-f5eb83d70384/f0be7cb3671608e7978e3f6a5f21e417

**Comment by paglias** [comment]
@Laros even when not logged in

**Comment by poopstick** [comment]
@lenfire I'm back. Sorry about the delay, but this now happens in Chrome on all my PCs. Even following the instructions in the screenshot provided don't help.

I get the message:

Missing :username or :password in request body, please provide both

**Comment by poopstick** [comment]
@lenfire Not sure if anything's been changed, but it seems to have started working again today. Will test on my main PC when I fly back to Japan later this week.

**Comment by deilann** [comment]
Working for me as well! Closing this for the moemnt.
