### ISSUE TITLE
Silver Rewards, eg. 0.5 GP error message (works anyway)

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1463]
reported by gwillen in Tavern chat:

> Ok, sorry for the delay, I tried setting a fractional-gold reward again. I see what happens: It turns the box red, and if I press enter I get a popup that says "Invalid Value". But by the time I've done that it's already saved the value anyway. So it _works_ but it says it doesn't.

I don't remember an invalid message, but the box did turn red.
It works, though, so marking this as minor.

**Comment by wc8** [comment]
ArtfulDodger in the Tavern reports that it is not functioning—i.e. cannot save Silver prices for Rewards in Webkit browsers but works fine in Mozilla.
Shaner reported,

> weird I can set it to .25 gold and click on it while the edit page is still open to lose .25 gold but I cannot save it so reverts to the original value

**Comment by SabreCat** [comment]
I reported this pre-rewrite in #1230 ... looks like it's still out there.

**Comment by paglias** [comment]
Fixed this and others similar validation errors
