### ISSUE TITLE
User selectable timezeone

### ISSUE THREAD

**Issue by AnonyMoses** [HabitRPG/habitica#147]
I am using Google Chrome and for whatever reason today (1/20/13 Sunday) my whole to dos went to Monday at least 2 or 3 hours early. I don't know what happened but there we go!

**Comment by cra** [comment]
One of the options to solve this might be a "narrow date" picker (like a switch between day-before-yesterday/yesterday/today). This would also help with forgetting.

**Comment by lefnire** [comment]
thinking out loud: easiest way would be to parse timezone from requester, but it [looks sketchy](http://stackoverflow.com/questions/7742378/nodejs-how-to-get-client-time-zone-info-from-its-serverrequest). Previously was running cron on client, but that causes [mongodb overload](#81). I'm working on some logic of setting timezone on first client load, then testing that on server next refresh

**Comment by yaleman** [comment]
Why not just make the timezone setting a part of the user's account and have an hourly/half hourly cron on the server that looks for user accounts with a timezone that should reset on that tick?

**Comment by lefnire** [comment]
i fixed it by offloading cron to the client. Yours sounds like a cool idea, I'll have to revisit is as a feature request down the pike (currently pretty booked up with [criticals](https://github.com/lefnire/habitrpg/issues?labels=critical&page=1&sort=updated&state=open))

**Comment by yaleman** [comment]
Thanks for the quick response - and definitely thank you for creating this
fun system :)

James

**Comment by Zequez** [comment]
Related to this, the user should be able to set when the day ends for him. I mean, for most people the day starts when they wake up, not at 00:00hs. So maybe we could give the user an option to set the start of the next day at, for example, 6am.

**Comment by hookang** [comment]
Good idea. Added to Master list of Features #169. Issue closed for organization.

**Comment by wc8** [comment]
See [Timezone & Day Start Options](https://trello.com/c/zFugXF6O)
