### ISSUE TITLE
Egg and potion disappear after "you already have that combo"

### ISSUE THREAD

**Issue by baimeeker** [HabitRPG/habitica#1476]
![image](https://f.cloud.github.com/assets/5406961/1103336/3a6ac6c8-18a1-11e3-82e2-77a5a7025307.jpg)

I tried getting a pet and I guess I already had it.  The tiger egg and desert potion nevertheless disappeared, leaving the message asking which potion I wanted to use in that egg on the screen, as you can see above. I selected a white potion, and my only other egg  (panda) and a white potion disappeared. That same message is still showing. 

Browser: chrome for iPad 
Username: baimeeker
No errors.

**Comment by baimeeker** [comment]
Just checked in Beta.  Everything looks fine there. 
![image](https://f.cloud.github.com/assets/5406961/1103342/38927b88-18a2-11e3-865e-e07a013b4ef4.jpg)

So looks like it's not affecting my user data

**Comment by lefnire** [comment]
pushing fix
