### ISSUE TITLE
checked out of Tavern Inn and dailies are still showing as grayed out and checked

### ISSUE THREAD

**Issue by jeromy-cannon** [HabitRPG/habitica#1478]
I checked into the Tavern on Friday (9/6/2013) evening after all of my dailies were complete as I was going to be unavailable on Saturday.  This Sunday (9/8/2013) morning I checked out of the Tavern and the grayed out dailies are not un-checking themselves.  

I have tried the following with no success:
with Chrome (version 29.0.1547.66) visit: http://habitrpg.com, http://beta.habitrpg.com, http:/old.habitrpg.com 
I tried adjust the custom day start from 4AM to a few minutes later than current time.  but after the time elapsed it still did not reset.
I tried using the 3 different Android Mobile apps.(MagicMicky, Paul Smith, and then the official one) and refreshing from there.

I also tried hitting http://habitrpg.com using Internet Explorer 10.

None of these things worked.

My account is under Rayel.

**Comment by lefnire** [comment]
This is just the way the tavern works. Follow the conversation on https://trello.com/c/A2w2orSc/14-rest-in-tavern for how it functions, and what our plans our for a different method (people aren't keen on the current method). tl;dr is you don't reset the day you check out, you reset the next day.

**Comment by jeromy-cannon** [comment]
thank you for the explanation.  I actually found the link you posted above and read it before opening this as an issue.  I guess the way you explained it just now, was easier to understand and I missed that information while reading the link you referred to.  Thank you again, I'll need to prepare better next time :)  I love the site!  I also love the new website, it is much faster and behaves better as well :)

**Comment by lefnire** [comment]
:) :) :)
