### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by Yughurt** [HabitRPG/habitica#148]
There's an issue with the daily checklist. At random times, the daily events reset and I lose half my health. Makes trying to use this difficult as half the reward for doing stuff is removed.

**Comment by lefnire** [comment]
how long has this been occurring? I recently rolled out a big fix to many of the these issues

**Comment by AnonyMoses** [comment]
It only happened today so far, have been using it for a few days now. I wanted to report it ASAP though. I was able to get everything marked up at around 11:50 last night, so it was surprising to see at 10:00 the next day had supposedly passed. It may be a one time thing though!

**Comment by lefnire** [comment]
Oh shoot, you know what it is - I moved cron to the server to bypass #80 (critical mongo load issue), but that means cron runs off my server's timezone EST instead of client. Ok, i gotta brew on a proper solution

**Comment by AnonyMoses** [comment]
Alright well I'm glad you got it figured out! Good luck and thanks for the
quick response!

**Comment by lefnire** [comment]
let's follow up on #147

**Comment by Yughurt** [comment]
Issue happened again. (nearly just died)
