### ISSUE TITLE
All party members appear as "Elite Friend"

### ISSUE THREAD

**Issue by LordGrowl** [HabitRPG/habitica#1480]
Hey all,

This is LordGrowl, user ID 1e18512a-0130-4651-962a-e089300f0b4d, reporting for duty.  Every single person appears to have gained the "Elite Friend" achievement when I view their profiles (i.e. click on their name in chat, party/guilds members list or on the avatars of my party members in the header).  Is this a glitch, or is this the achievement for signing up before the rewrite under a confusing name?

**Comment by Mihakuu** [comment]
Ah Lord Growl I just posted the same things about everyone have the same achievement list as my own. Check if it's the same thing. Same number of streaks etc

**Comment by Mihakuu** [comment]
#1479 is what I posted

**Comment by LordGrowl** [comment]
Yeah, this is a duplicate of #1479 alright.  Closing this one.
