### ISSUE TITLE
Community guidelines may want to make clearer the timeline and parameters for receiving a staff response to an email sent after an account consequence

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#14800]
Since you're already planning a community guidelines update anyway, I figured I'd voice this concern so that what happened to me perhaps could be avoided in the future. Two birds, one stone, you know?

I sent a civil (downright polite) email over a month ago asking to discuss the details of an account consequence (a ban) on my account, as both the mute and ban notifications as well as the community guidelines suggest doing, and I never received a response. I considered my email and the questions for staff in it quite reasonable, so it confused me that it went so long without a response, and I eventually just gave up.

I think the community guidelines *and* the ban snackbar notification should make *extremely* clear exactly what kinds of emails staff might actually respond to after a severe consequence (versus which kinds will never receive a response), as well as make *extremely* clear what the timeline will be for receiving an email reply. That way, the user won't be left hanging, trying to consider whether or not it's too soon to send a nudging "in case you missed it" type email, or perhaps trying to consider whether to send an initial email at all, if the guidelines make clear that staff will not respond to it.

Thanks for taking a look at my concern. Have a good day.

**Comment by SabreCat** [comment]
This user is now blocked from all repositories under the HabitRPG organization. Closing.
