### ISSUE TITLE
Using HTML5 Application Cache

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1481]
Since appending a md5 hash to all files under /public is quite complicate to do I think a good solution might be to use HTML5's [Application Cache](https://developer.mozilla.org/en-US/docs/HTML/Using_the_application_cache): it is a text file which contains a reference to all the files that should be cached by the browser.

It is meant to be used for offline apps but nothing block us from using it as a method to avoid always requesting static files to the server.

The important thing is to change the file (by adding a number, a date...) when some static file change (more or less at every push to the master branch).

This isn't _perfect_ since it will re-download every file when the manifest change but it's still better both for users & for the server then the current approach where no file is cached. And will be more valuable when the rewrite is completely done and we're not going to update the app every day.

It's supported in Internet Explorer 10, Firefox, Chrome, Safari and Opera.

I'll work on this tomorrow.

---

With a little more work **we can make the website working totally oflline :DD like the mobile app!**

What do you think?

**Comment by Shaners** [comment]
This sounds like a really good idea actually!

**Comment by paglias** [comment]
Yes but we can't use it :(

The problems are:

1-) It aways cache the page where the manifest is referenced (in our case http://habitrpg), we can't do this because the page is login protected. There's an hack which consists in using a small empty html frame referencing there the manifest and loading the small page in an iframe inside habitrpg.com so that resources are cached but not the page. But it's not really good.

2-) When the manifest is updated the browser recognize that only after having already loaded all the old resources from the cache so we may end having the old code on the browser and the new one on the server until the user refresh the page. This is not good and may cause serious problems. In theory an event is fired when the appcache manifest is updated but only after evryhting has been loaded so we will have to force the page refresh after it has already been loaded.
