### ISSUE TITLE
Herobox as an Angular Directive

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1483]
Create herobox (avatar.jade) as an Angular Directive "Rather than running include ./avatar everywhere and creating arbitrary controllers just to setup distinct scopes, Angular Directives is built for this sort of thing. May need to also do with other avatar info (modal dialogs, stats info, etc) and pets"
##

**Comment by Alys** [comment]
@crookedneighbor Do you have any opinion about this? It might have already been handled by the refactoring you've been doing.

**Comment by crookedneighbor** [comment]
It's not something I've already done, but I think it can be a good idea.

**Comment by lemoness** [comment]
@crookedneighbor Is this still relevant?

**Comment by crookedneighbor** [comment]
Since we're moving away from Angular, no.
