### ISSUE TITLE
Port Undo [$20]

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1484]
##

**Comment by wc8** [comment]
This came up in tavern (again?).

**Comment by lefnire** [comment]
ah, a bounty! fwiw, see https://github.com/HabitRPG/habitrpg-shared/pull/95

**Comment by librarianmage** [comment]
What happened here?

**Comment by Alys** [comment]
The website used to have an undo function and then it was removed when a large-scale code change was made. This issue was to recreate it. It's not suitable for working on at the moment because another large-scale change is underway.

**Comment by librarianmage** [comment]
Oh. Okay!

**Comment by lemoness** [comment]
Now that the API rewrite is done, we can discuss if this is still feasible or relevant.

Some people do request Undo buttons periodically, but if I recall correctly, there were issues getting it to work properly.

**Comment by crookedneighbor** [comment]
I have so many thoughts about this.

1) what actions are undoable? I assume anything that affects other players (skills, boss damage after cron, transferring gems, etc) would not be.
2) can you only undo the last action? Or can you choose from a list of recent actions? Can you undo an undo?

This would also nicely tie into a recent activity stream. I'm thinking something like:

``` js
[{
  createdAt: Date,
  type: 'scoreTask',
  text: 'You scored "task name here" for x gold and y exp',
  undoable: true,
  data: {
    task: {
      id: 'task-id',
      value: 'the change in value from the score',
    },
    stats: {
      gold: 'gold earned (or from action',
      exp: 'exp earned from action',
      mp: 'mp earned from action',
      hp: 'hp lost from action (negative habit)'
    },
    quest: {
       up: 'quest progress up',
       down: 'quest progress down',
       collect: 'items collected'
    }
  }, {
  createdAt: Date,
  type: 'buyEquipment',
  text: 'You bought a warrior shield',
  undoable: true,
  data: {
    stats: {
      gold: 'gold spent',
    },
    items: {
       warrior_shield_2: true
    }
  }
}, {
  createdAt: Date,
  type: 'castSkill',
  text: 'You cast "blessing" for the party',
  undoable: false
}, {
  createdAt: Date,
  type: 'partyMemberQuestDamage',
  text: 'boss attacked the party for x damage',
  undoable: false
}]
```

And then there'd be a "Recent Activity Feed" so you could see what

**Comment by lemoness** [comment]
We plan to tie this into a future feature involving a history log, so I am closing this discussion because it is fairly outdated. It can always be reopened in the future if needed.
