### ISSUE TITLE
Port Due Dates

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1485]

**Comment by ozziefallick** [comment]
Since this port is labeled with minor priority, I'd like to use it to cut my teeth on working on HabitRPG. I'll be learning Angular as I go along, so if there's nothing else left to port (or you decide that its priority is too low), feel free to take it from me.

**Comment by lefnire** [comment]
fantastic! give it a whirl, let me & @paglias know if you need any help getting up and running.

**Comment by ozziefallick** [comment]
Alright, experimenting now. So I'm clear, what's the expected behavior? I never used due dates in prod.

**Comment by lefnire** [comment]
Check out http://angular-ui.github.io/bootstrap/#/datepicker to get you started. We were previously using bootstrap-datepicker 3rd party module, but it didn't bode well with jquery-to-derby-model bindings. Nor will it for Angular, unless we write a custom directive (hence the above link to give us a boost). 

Expected behavior: click the "Date" field of a todo, get a calendar, select a date, updates `task.date`. That's all for now. Eventually we'll do stuff with that, but just with the learning curve of all this I think this will give you plenty to do. Later we'll want to fix the ical export, and then later-later add this whole [disease feature](https://trello.com/c/QmhxaBRE/93-missed-deadline-disease)

**Comment by JMTyler** [comment]
If it's unlikely that this is going to become available any time soon, maybe it would be a good idea to quickly toss in an alert similar to the one on progress graphs? i.e. "This feature is not yet ported from the original site."

I've tried to add due dates to my Todos a couple times (leisurely, no big deal), then finally came here to report it as a bug, but of course perused existing issues first and found this one.

I don't really know Angular, but I don't suppose adding an alert is terribly complex, so if I could get a succinct list of features that haven't been ported I might be willing to just hop in and sprinkle these alerts around myself.  I know it seems like a waste of time when there's so much that could _actually_ be ported, be these alerts would be really useful to newcomers and, as someone who doesn't actually know Angular, I'm not going to be any benefit to the port campaign anyway. :-)

**Comment by ozziefallick** [comment]
I think that would be wise. Since school just started for me and I had a lot of competing obligations, I haven't gotten to give Habit nearly the attention I've been wanting to, but that should hopefully be changing soon!

**Comment by ozziefallick** [comment]
@lefnire: Am I supposed to be using that Angular UI directive, or writing my own based on it?

**Comment by lefnire** [comment]
I'd say use the AngularUI directive. We're already using AngularUI for a
few other bits, so it'll be an easy drop-in

**Comment by ozziefallick** [comment]
Sounds good. What's the procedure for adding a module to the codebase?

**Comment by lefnire** [comment]
bower install {package} --save

**Comment by ozziefallick** [comment]
None of that `angular.module('myModule', ['ui.bootstrap']);` stuff? I noticed there didn't seem to be any in the rest of the codebase.

**Comment by Valence87** [comment]
Is there an eta on porting due dates? I miss them.

**Comment by ozziefallick** [comment]
Man, I really wish I could give you one. In my fork, you can enter due dates manually, but I haven't gotten the date picker to play nice yet, and all my attention has been on job interviews for the past four weeks. I'm hoping to get back to working on it later this week, but if it would be useful to have manual entry back in, I can put a tag there and submit a pull request.

**Comment by Valence87** [comment]
Having manual entry would be great, if that's not too much trouble to move over.

Good luck with the job interviews!

**Comment by ozziefallick** [comment]
Pull request submitted. Hope to be getting the actual date-picker in soon!

**Comment by ozziefallick** [comment]
Looks like this works now, no thanks to me. Any more to be done?

**Comment by lefnire** [comment]
@ozymandiasthegreat yeah, it has some weird z-index issues (falls below the rewards column) and we'd like to bring ICS export [back to life](https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv1.js#L20tL59). Either of those sound like something you could tackle?

**Comment by ozziefallick** [comment]
I'll take a crack at the ICS export, but if I end up being a deadbeat again feel free to toss it to someone else. I assume we want it in APIv2?

**Comment by lefnire** [comment]
Do eet. Yes, apiv2

**Comment by ozziefallick** [comment]
Didn't occur to me to put the issue in the pull request :)

**Comment by deilann** [comment]
Due dates exist... so I think this can be closed.
