### ISSUE TITLE
 add links to mobile apps on marketing pages

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1486]
esp. /static/front, with some pretty images and all that jazz

**Comment by Shaners** [comment]
Do you think we could use a landing page redesign? It's something I've been tooling with but won't push if we're committed to the current version.

**Comment by lefnire** [comment]
Oh, we could _absolutely_ use a different landing page. _I_ designed that, and we all know how design-savvy I am :)

**Comment by Shaners** [comment]
I am a fan of the current design! Tis not a knock at it but as we grow and look for investors I think it's a good idea to evaluate and experiment with our front gate!

**Comment by lefnire** [comment]
Oh I know you're not - _I'm_ knocking it :) Lotta people have said "it doesn't show enough", and especially now that you can't play around before signing up we'll need more screenshots & such
