### ISSUE TITLE
502 Bad Gateway Error - Unable to access website

### ISSUE THREAD

**Issue by catalincodes** [HabitRPG/habitica#14873]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: n/a
  * Browser: any
  * OS: any

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
"502 - Bad Gateway" error when trying to access server.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
![image](https://github.com/HabitRPG/habitica/assets/12548925/c99ca39e-e535-4fbc-aed7-1dda9ab1daee)

**Comment by ranchowei** [comment]
Me too!!!
I am a new fan of habitca.I really want to use it to form habits.
Yesterday,It's my first time to use it .But now...

**Comment by LemonPoems** [comment]
I've got the same issue (opened one too, didn't realize you've alr opened it lol).... I was an old fan but I deleted my account and I joined yesterday again, and now this... qwq

**Comment by vcoulter2015** [comment]
There's a wiki page for  https://habitica.fandom.com/wiki/Outage_Instructions for how this might be handled -- it was about 85 minutes ago that I noticed it was down (and it could easily have been 2 hours ago).

It's more likely to be a problem with whatever hosts Habitica.com than a problem in the codebase (I could be wrong).

Good night! I'm disappointed too, @ranchowei , but it'll work out. I've been on Habitica for about 4 months and this is the first time this has happened, and nobody else has mentioned to me that it happens often.

**Comment by aprilspace** [comment]
same problem for me, devs please fix it

**Comment by jmlingeman** [comment]
Did someone push to prod at 5pm on a Friday? :-)

**Comment by aprilspace** [comment]
go go send some mails :)

guess we should write to [admin@habitica.com](mailto:admin@habitica.com) about that problem
send email if you can I guess it can help a little
" Hello, habitica.com responds Error: Server Error Its down for 10h already Please fix it Thanks in advance. "
thats what I wrote

**Comment by magicalskye** [comment]
> There's a wiki page for https://habitica.fandom.com/wiki/Outage_Instructions for how this might be handled -- it was about 85 minutes ago that I noticed it was down (and it could easily have been 2 hours ago).

i ended up there too, but they link only a twitter account for news, which i cannot access because i don’t have a twitter and you cannot view anything unless you are logged in. it’s strange that there seems to be not even a status. subdomain or anything where you could check what’s going on

**Comment by aprilspace** [comment]
> > There's a wiki page for https://habitica.fandom.com/wiki/Outage_Instructions for how this might be handled -- it was about 85 minutes ago that I noticed it was down (and it could easily have been 2 hours ago).
> 
> i ended up there too, but they link only a twitter account for news, which i cannot access because i don’t have a twitter and you cannot view anything unless you are logged in. it’s strange that there seems to be not even a status. subdomain or anything where you could check what’s going on

just checked twitter nothing new today.

**Comment by catalincodes** [comment]
There is no feedback of any kind on their Twitter. I just checked and the latest information is from September 14th and not related to the ongoing outage :

![image](https://github.com/HabitRPG/habitica/assets/12548925/10014903-b90a-4020-87f9-855636ac2891)

**Comment by PVTejas** [comment]
I've been on the community habitica subreddit and a dev has mentioned that they are aware of the issue and working to bring the servers back online.

**Comment by saraolson** [comment]
yup our team has been working as fast as we can to solve the issue, thanks for your patience! i'll leave this issue open for anyone that stops by the github until we're back online.

**Comment by catalincodes** [comment]
> yup our team has been working as fast as we can to solve the issue, thanks for your patience! i'll leave this issue open for anyone that stops by the github until we're back online.

Thank you!

**Comment by saraolson** [comment]
aaaand we should be back up an running 🎉

**Comment by felixonmars** [comment]
> aaaand we should be back up an running 🎉

I am still getting the same error :O

**Comment by felixonmars** [comment]
Nevermind. It's working now! 🚀

**Comment by saraolson** [comment]
@felixonmars ty for the update! glad it's working for you as well now.

**Comment by catalincodes** [comment]
Seems to be working fine, yes! No errors! 

Plenty of console errors in prod, but that I do not think is new! 

Thank you @saraolson! 

I will go ahead and close the issue!

**Comment by LemonPoems** [comment]
Guys... the issue is back....

**Comment by joedragons** [comment]
No issues here.
PS: isup.me agrees there's an issue, so I guess might just affect new sessions for now? (jinx)

**Comment by LemonPoems** [comment]
> Guys... the issue is back....

Oop it's gone again, phew! Love you devs
