### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1487]
Check into
- https://github.com/lgsilver/angles #use-this-one
- https://github.com/rootux/angular-highcharts-directive
- https://github.com/angular-ui/ui-chart

**Comment by paglias** [comment]
Where do you plans to place them?

**Comment by lefnire** [comment]
I'll tackle this one actually, it's just a port from the old site. I'm gonna take a quick peak at these 3 options above, but likely use the original solution which was google graphs

**Comment by dfjkla** [comment]
Graphs are really useful in figuring out when you did a something task, and how often.

I have a few tasks which increment in value (Easy>Medium>Hard) at each step. For example, I have "eat fish" as a daily task to encourage me to eat more fish. First time of the week is Easy, second time is Medium, and third fish meal of the week is Hard.

While that is an easy task to keep tabs on, graphs would enable a bit more complex and long-term tiering up like that.

Another option would of course be to include such increasing tiers with specific time periods in-game :)

**Comment by Shaners** [comment]
@dfjkla something like a repeating checklist with weights for each item might work for that. Kind of like #529. Maybe add your thoughts here: https://trello.com/c/PJ1iJ413/65-checklists

**Comment by dfjkla** [comment]
Thanks Shaners, good catch - I added my comments there!

**Comment by lefnire** [comment]
i'll re open this if i decide to implement with one of the above libraries (likely angular-ui), but simply porting the old google charts code was easiest for now. There's also some strangeness where it's not picking up the containing div's width and it's spilling out, so I manually set it to 300px width (which won't look great on or small screens), so we'll want to fix that eventually - but in the mean time, this is fixed.
