### ISSUE TITLE
"502 Server Error" (on Chrome, Mac) and "Server Connection Lost" on app (Android).

### ISSUE THREAD

**Issue by LemonPoems** [HabitRPG/habitica#14874]
![Screenshot 2023-09-16 at 9 21 02 AM](https://github.com/HabitRPG/habitica/assets/145172924/d258c9f7-b171-43b0-bcd5-46ab2440d90b)
Above is what I see when accessing habitica.com on Chrome.

![Screenshot 2023-09-16 at 9 21 07 AM](https://github.com/HabitRPG/habitica/assets/145172924/a413cb01-b317-427e-9516-9e321459294e)
And is what I see in the tab area. (Also Chrome)

![android](https://github.com/HabitRPG/habitica/assets/145172924/08826089-fcb5-4f03-9503-8a3e18bb33a5)
This is what I see when opening the app on my phone or tablet (both Android).

I've tried to use a VPN (Chrome) and I've also turned off my wifi and used my data instead (Android phone), but the issue still remains... Also on https://isitdownorjust.me/habitica-com/, it's marked as down... Sorry to bother y'all, but may I know when the issue will be resolved because I've got some tasks due today that I need to check off :')) TYTY

**Comment by vcoulter2015** [comment]
This ~~is~~ duplicates https://github.com/HabitRPG/habitica/issues/14873 but screenshot is nice. I noticed about 75 minutes ago that habitica.com is down. @LemonPoems Thanks for reporting. I'm just a regular habitica user too.

**Comment by LemonPoems** [comment]
> This ~is~ duplicates #14873 but screenshot is nice. I noticed about 75 minutes ago that habitica.com is down. @LemonPoems Thanks for reporting. I'm just a regular habitica user too.

Hahah thanks, I also just noticed someone else posted about the same issue lol (sorry!)

**Comment by aprilspace** [comment]
same

**Comment by RealRTorres** [comment]
Oh okay, it's just down. I was wondering what happened. Good to know.

**Comment by aprilspace** [comment]
go go send some mails :)

guess we should write to admin@habitica.com about that problem
send email if you can I guess it can help a little 
" Hello, habitica.com responds Error: Server Error Its down for 10h already Please fix it Thanks in advance. " 
thats what I wrote

**Comment by RaianIE** [comment]
I have the same issue

**Comment by Dryad61** [comment]
Same problem; wrote to admin last night and no news yet

**Comment by AnkurAlpha** [comment]
Why is it down for so long ?

**Comment by PVTejas** [comment]
I've been on the community habitica subreddit and a dev has mentioned that they are aware of the issue and working to bring the servers back online.

**Comment by saraolson** [comment]
closing this issue as we already have one about this. our team is working as fast as we can to find a solution!
