### ISSUE TITLE
alert "You are about to leave Habitica.com" when click menu button

### ISSUE THREAD

**Issue by saibobo88** [HabitRPG/habitica#14876]
I installed habitica by docker, but every time i click the menu button. It alters warning:
"You are about to leave Habitica.com"
![image](https://github.com/HabitRPG/habitica/assets/145260812/4300d61d-1826-4b2b-a775-ac7869966979)
How can I fix this ?

**Comment by saibobo88** [comment]
i remove "externalLinkModal" lines, in app.vue . And it did not alert warning any more

**Comment by DuckManQuack** [comment]
Also having this issue with a self hosted version, could not locate "externalLinkModal" lines, in app.vue file.

**Comment by g-timmerman** [comment]
I solved it by editing the config.json in the root folder.
There's a TRUSTED_DOMAINS value in that file and I just expanded the collection with my own local address.

"TRUSTED_DOMAINS": "localhost,https://habitica.com,http://192.168.0.100",

After rebooting the system, it stopped nagging about external links.

**Comment by jamesking210** [comment]
I'm having the same issue and don't see the "externalLinkModal" lines, in app.vue
I'm using a Cloudflared Tunnel. (https://habitica.MYDOMAIN.com) an am hosting this using a proxmox helper script.
I have edited the TRUSTED_DOMAINS and tried every combination, including only my domain and/or the 219 address without ports.

"TRUSTED_DOMAINS": "localhost:3000,https://habitica.MYDOMAIN.com,https://habitica.com,http://192.168.1.219:3000",
"IGNORE_REDIRECT": "true", (I've tried false as well)
"BASE_URL": "https://habitica.MYDOMAIN.com",

**Comment by ryanbonus** [comment]
> I'm having the same issue and don't see the "externalLinkModal" lines, in app.vue I'm using a Cloudflared Tunnel. (https://habitica.MYDOMAIN.com) an am hosting this using a proxmox helper script. I have edited the TRUSTED_DOMAINS and tried every combination, including only my domain and/or the 219 address without ports.
> 
> "TRUSTED_DOMAINS": "localhost:3000,https://habitica.MYDOMAIN.com,https://habitica.com,http://192.168.1.219:3000", "IGNORE_REDIRECT": "true", (I've tried false as well) "BASE_URL": "https://habitica.MYDOMAIN.com",

I was having the exact same issue as @jamesking210 

the fix in my case was as follows:

1. add my domain to the TRUSTED_DOMAINS environment variable in config.json (this can be your base domain or including the subdomain, habitica just runs an include check to see if the content of the URL in your browser's address bar contains the domain as a substring)
2. stop the 3 habitica services running in my lxc container
`systemctl stop habitica-client.service`
`systemctl stop habitica.service`
`systemctl stop habitica-mongodb.service`


3. go through two of the same steps that the [community script](https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/habitica.sh) does to build habitica: 
`npm run client:build`
`gulp build:prod`

4. start the 3 habitica services back up
`systemctl start habitica-mongodb.service`
`systemctl start habitica.service`
`systemctl start habitica-client.service`



Adding this writeup to help you and anyone else encountering this issue :)
Happy hosting!
