### ISSUE TITLE
Ininity loading and errors

### ISSUE THREAD

**Issue by aprilspace** [HabitRPG/habitica#14875]
When I'm tryin to log in I got habitica like this (see an attached screenshot), and nothing changes after a time. Refreshing clearing cache makes no difference. Different web browser gives same results. Please fix.
![habitica](https://github.com/HabitRPG/habitica/assets/68641489/1c5fcf39-e210-468c-9a13-9c8bb5765652)

**Comment by ranchowei** [comment]
in three days ,it happened again and again !
maby we should establish our own server...

**Comment by aprilspace** [comment]
> in three days ,it happened again and again ! maby we should establish our own server...

I'm already did it, just need some time to migrate my tasks

**Comment by aprilspace** [comment]
oops

**Comment by aprilspace** [comment]
![image](https://github.com/HabitRPG/habitica/assets/68641489/8711aeb0-5c0a-4601-a4a3-729efd3bfdf8)
🤣
when you try to show an error, but the error falls into an error

**Comment by beffymaroo** [comment]
Hi, after a lot of hard work from the dev team this week reports indicate that the site and apps are stabilized. Please reach out via admin@habitica.com if you experience any further issues.
