### ISSUE TITLE
Port iCal

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1488]
not necessary before starting new features, since never was working really anyway, and few people attempted using it. But we'll need to add it in eventually

##

**Comment by Alys** [comment]
Partial implementation in https://github.com/HabitRPG/habitrpg/pull/2549 which has been closed due to age but could probably be used as a basis for a new fix.

**Comment by lemoness** [comment]
We are still interested in an iCal integration!

**Comment by librarianmage** [comment]
What exactly is requested?

**Comment by Alys** [comment]
I'm closing this because we have it in trello as a feature request. It's calendar synchronisation / integration.
