### ISSUE TITLE
Port Edit Groups

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1489]
- ~~title~~
- ~~description~~
- ~~logo~~
- ~~leader message~~
- ~~websites~~
- ~~group leader~~
- ~~ban members~~
- leader avatar saying leaderMessage
  - This is going to require avatar be converted to a directive, since we can't wrap each of these in a scope with `profile=group.leader`. We have to pass it as an attribute by-reference. This needs to happen eventually anyway for organization and performance

##

**Comment by lefnire** [comment]
working on now

**Comment by lefnire** [comment]
ok, no longer working on this now that I've completed the most important parts. I'm going to move on to other tickets, but the next important thing that needs to happen here (in case someone decides to jump in) is the "leader avatar saying leaderMessage" thing - which will require moving the `herobox` (avatar.jade) to a directive.

**Comment by paglias** [comment]
Group leader and websites are implemented, I've left the "leader avatar saying leaderMessage" thing
