### ISSUE TITLE
Server errors on https://habitica.com/party and when trying to submit a bug report via Help -> Report a Bug

### ISSUE THREAD

**Issue by wpdev8195** [HabitRPG/habitica#14890]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)
I was not able to contact site administrators from "Report a Bug" in the Habitica website's Help menu, because I got a server error when I attempted to.
![image](https://github.com/HabitRPG/habitica/assets/108739698/d308473d-320e-43eb-8493-44bc0fa11d9d)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: a1b3f37d-8481-4271-b05c-247219cecc97
  * Browser: Microsoft Edge Version 116.0.1938.62 (Official build) (64-bit)
  * OS: Windows 10 Pro

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When I access the page https://habitica.com/party
in Microsoft Edge on Windows 10 today 2023-09-18 around 2:45pm EET, I am getting the message "Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds."

This message appears in a red popup box on the ride side of the screen.
![268636174-7cb74479-ccff-4fc3-b751-756373f0bdc2](https://github.com/HabitRPG/habitica/assets/108739698/5f5fbc7f-d7a4-4d77-bbad-b53d1f627748)

After leaving this page to eg the Tasks page and returning to it, the message appears again. At least one time, multiple boxes appeared at once. Another time, only one box appeared.

**Comment by SabreCat** [comment]
We had a major outage on our server architecture on September 16 and we're still dealing with some of the fallout. This isn't a discrete app issue. Closing.
