### ISSUE TITLE
[Feature Request] Rememberthemilk Synchronization

### ISSUE THREAD

**Issue by lukashuebner** [HabitRPG/habitica#149]
Automatic Synchronization with RTM. Take priority and estimated duration into account when calculating rewards.

**Comment by racuna** [comment]
Or just sync current tasks, overdue, "this week" and "next week" only, at least until HabitRPG supports due date and repeat todo tasks by itself.

**Comment by hookang** [comment]
Tyler has a tons of plans on integrating with various APIs. Good idea. Added to Master list of Features #169. Issue closed for organization.
