### ISSUE TITLE
 "Show Bailey" option isn't available anymore

### ISSUE THREAD

**Issue by melvio** [HabitRPG/habitica#14917]
The "show bailey" option, to show the latest news, is gone:

![show bailey](https://github.com/HabitRPG/habitica/assets/31448155/14c899c3-01c6-404f-ac35-19b155d86512)

It used to be available at `https://habitica.com/user/settings/site`, but that link now gives a 404 not found.

**Comment by ASCE-D** [comment]
Hey Devs, I would like to contribute to this issue, can I work on this?

**Comment by CuriousMagpie** [comment]
You can see the most recent Bailey on the Notifications tab of the Settings page, under Website:
![Screenshot 2023-10-25 at 2 41 49 PM](https://github.com/HabitRPG/habitica/assets/78037386/201c4802-5160-464f-a7e8-62a4f7397078)
