### ISSUE TITLE
Bug Report: Request to Update Twitter Icon to X - HACKTOBERFEST

### ISSUE THREAD

**Issue by Akash02032002** [HabitRPG/habitica#14915]
# What happened?

## URL:-

https://habitica.com/static/home

## ScreenShot:-

![e](https://github.com/HabitRPG/habitica/assets/84145371/8ed75a93-2347-43be-84f1-33166ed1c809)

## The Twitter logo should be changed to X

![4](https://github.com/parallax/jsPDF/assets/84145371/4c8e6509-c011-4a79-a207-59db1b57eeb8)

## Scroll to the footer section and see Twitter old logo

https://github.com/Akash02032002
### " I am just starting with ( Hacktoberfest -23 ) open source contribution. I would love to take this issue as my first ever contribution.
# could you please assign this to me? "

**Comment by tquimbo** [comment]
Interested in working on this!

**Comment by ashgurl** [comment]
I can work on this

**Comment by asiarouse00** [comment]
would love to work on this as a first open-source contribution!

**Comment by PushpakChaudhari** [comment]
I am interested in resolving this issue. Please assign me

**Comment by SabreCat** [comment]
We won't be fixing this rn. Closing this ticket.
