### ISSUE TITLE
How to solve JavaScript heap out of memory?

### ISSUE THREAD

**Issue by rozerinyildiz** [HabitRPG/habitica#14936]
#### Electron Js - JavaScript heap out of memory
[//]: # (Include any JavaScript console errors here.)

I have an Electron JS project. I need to read a file. However, the file is bigger now and it has to be read. I get this error:

>  electron .

Hello World!

<--- Last few GCs --->

[9304:0000695000838000]    25883 ms: Scavenge 3943.4 (4085.4) -> 3941.0 (4087.9) MB, 14.24 / 0.01 ms  (average mu = 0.901, current mu = 0.878) allocation failure;
[9304:0000695000838000]    28273 ms: Mark-Compact 3945.8 (4087.9) -> 3942.9 (4093.1) MB, 2366.71 / 0.00 ms  (average mu = 0.677, current mu = 0.354) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: NewSpace::EnsureCurrentCapacity Allocation failed - JavaScript heap out of memory
 1: 00007FF79ACA0ED6 node::SetTracingController+81190
 2: 00007FF79ACA1163 node::OnFatalError+595
 3: 00007FF79DA982A3 v8::Function::NewInstance+835
 4: 00007FF79DA98233 v8::Function::NewInstance+723
 5: 00007FF79DB61517 v8::CppHeap::CollectGarbageInYoungGenerationForTesting+72871
 6: 00007FF79997FA3D v8::CppHeap::CollectStatistics+166125
 7: 00007FF79996C1CC v8::CppHeap::CollectStatistics+86140
 8: 00007FF79996A158 v8::CppHeap::CollectStatistics+77832
 9: 00007FF79C594E09 v8::MicrotasksScope::PerformCheckpoint+520841
10: 00007FF79C590948 v8::MicrotasksScope::PerformCheckpoint+503240
11: 00007FF79C5807AD v8::MicrotasksScope::PerformCheckpoint+437293
12: 00007FF79C788E58 v8::MicrotasksScope::PerformCheckpoint+2568920
13: 00007FF79CA8207A v8_inspector::String16::String16+2312474
14: 00007FF7E0048D64

How can i fix this problem?

**Comment by italojs** [comment]
for now you could use `--max-old-space-size=8192` when running the habitica server, the nodejs by default allow the use only 4GB
but could you explain better what you want to do? because if you need to read a big file you could use streams to do it

**Comment by SabreCat** [comment]
Habitica doesn't use Electron. If you're having trouble with Electron, that's an issue for a different repo!
