### ISSUE TITLE
User: port tasks, tags, history to subdocs

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1493]
We want to port all arrays of objects to nested schemas, and then setup server routes to handle them as nested resources (eg `POST/PUT/DELETE/GET` `/user/tags/:tid`). 

Tasks is going to be the hard one. It's essential because (1) we're casting from derby-style to api-consumer style all over the place, and we need to just remove that and keep the api-consumer style by making tasks a nested schema; (2) more importantly, we can't define the tasks schema without doing this. Presently it's just a `Schema.Types.Mixed`, and we lose out on validation, defaults, etc. But this is going to be an extremely complex overhaul, requiring changes to almost all user routes. Postponing, but note-to-self
##

**Comment by Alys** [comment]
Closing this now that API v3 has been released.
