### ISSUE TITLE
Mobile:  Android app doesn't work it shows "error:no tasks tags"

### ISSUE THREAD

**Issue by Neputin** [HabitRPG/habitica#1494]
The androrpg app worked fine for weeks and now it suddenly showed a bizarre error. I don't even have any tasks tags.

**Comment by paglias** [comment]
You're not talking about the official habitrpg app (
https://play.google.com/store/apps/details?id=com.ocdevel.habitrpg), right?

Which one are you talking about?

Anyway unless you're talking about the official app then you should
contatct the app developer.

2013/9/9 Neputin notifications@github.com

> The androrpg app worked fine for weeks and now it suddenly showed a
> bizarre error. I don't even have any tasks tags.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1494
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by Neputin** [comment]
I think I am talking about the official one. The one that has a tag feature that's available to premium users, which I don't use.

**Comment by paglias** [comment]
No that's not the official app, you can find the official one here
https://play.google.com/store/apps/details?id=com.ocdevel.habitrpg

**Comment by Neputin** [comment]
No wonder I had problems. But it says it's incompatible with my device.  Is there a way I can make it work on htc desire? I have it rooted.

**Comment by paglias** [comment]
Currently it supports only Android 3.0+, I'm sorry :(

2013/9/9 Neputin notifications@github.com

> No wonder I had problems. But it says it's incompatible with my device. Is
> there a way I can make it work on htc desire? I have it rooted.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1494#issuecomment-24063034
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by Neputin** [comment]
That's not a problem. I can root my device and install a 3.0+ rom.
