### ISSUE TITLE
Main, beta site don't load, old site doesn't "exist"

### ISSUE THREAD

**Issue by michaelmdf** [HabitRPG/habitica#1495]
Hello!

I haven't been able to load either the main or the beta site on Chrome or Safari for the past couple of days. It's been loading for 15 minutes now and still not ready :-(

The old site was working yesterday, but now Chrome says it "couldn't find it."

![screen shot 2013-09-09 at 9 04 31 am](https://f.cloud.github.com/assets/5418185/1106847/6b8ca64a-1950-11e3-8013-0d959f762e6a.png)

Thanks!

P.S.: HabitRPG has changed my life and I sincerely appreciate your work!

**Comment by lefnire** [comment]
We pulled the plug on old.habit. It was straight-up causing data corruption, that we were running around un-corrupting. I spent all last night prepping the new system with major missing features so we could kill Habit the Grey, and then finalizing it with a data sanitization migration script, putting the database in clean state (and widdling it down from 8GB to 1.5, so thing should load faster too).

As far as not being able to access the new sites, something awry must be going on in your account as it's working for the rest of us. Do you get any errors? Can you follow the instructions at the bottom of http://community.habitrpg.com/content/submitting-bugs to see if there are any console errors? What's your UUID?

**Comment by michaelmdf** [comment]
Oops, forgot to tell you my user ID: michaelmf

This seems to be the error message. I get three of those within the first couple of minutes of trying to load the page. After that it keeps trying to load the page. This morning I left it trying to load it for almost one hour. Chrome says it's not responding and asks if you'd like to kill it or wait, I kept telling it to wait. Sometimes it crashes also. Thanks!

GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1378742479153  app.js:3
send app.js:3
fb.extend.ajax app.js:3
fb.extend._evalUrl app.js:2
fb.fn.extend.domManip app.js:2
fb.fn.extend.append app.js:2
(anonymous function) app.js:6
(anonymous function) app.js:4
(anonymous function) app.js:4
(anonymous function) app.js:6
g.$eval app.js:5
g.$digest app.js:5
g.$apply app.js:5
f app.js:4
r app.js:4
v.onreadystatechange

**Comment by wc8** [comment]
I realize this is probably something you can't access, but just in case:
The User ID is _not_ your username or email address, it's your "UUID" that looks something like 2F1E4FC0-81FD-11DA-9156-00036A0F876A. You can access this on https://habitrpg.com by clicking Options > Settings.

Meanwhile, something I try sometimes: clearing browser cache.

**Comment by lefnire** [comment]
@michaelmdf , is this the same issue that you're experiencing over in https://github.com/lefnire/habitrpg/issues/1499 ? can we close this one and follow up there, or is it different?

**Comment by michaelmdf** [comment]
Yes, it's the same issue. Thanks!
