### ISSUE TITLE
check database if we can make usernames case-insensitive

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1497]
I made the big mistake of usernames bing case-sensitive back in the day. I need to run a script to see if there are any duplicates when lowercased, and if there _aren't_ we can move the app to case-insensitive. If the _are_, I'll make the login screen use email instead of username

**Comment by brightbold** [comment]
If possible, this would be nice because I've noticed the names are also case-sensitive in the Tavern. So when people mention me but fail to use my silly camel-case, it doesn't highlight the post.

**Comment by SonicWizard** [comment]
I think this is an important fix before you get too many duplicate usernames. Also, login logic (and registration and all other username checks) should ignore case.

**Comment by Alys** [comment]
This is being handled in https://github.com/HabitRPG/habitrpg/issues/5126
