### ISSUE TITLE
Habitica CalDav Sync?

### ISSUE THREAD

**Issue by diyoyo** [HabitRPG/habitica#14986]
Hi, 
not sure where to post this, but I was wondering if there was a way to sync the to-do list of habitica with my NextCloud calendar/Tasks (that rely on CalDav) ?
I would love to be able to have some kind of plugin in thunderbird or an integration in NextCloud.
If there is any old piece of code that no-one wants to update, I can even try to have a look at it and refresh it a little.
Thanks.

**Comment by SabreCat** [comment]
Feature request, closing as non issue
