### ISSUE TITLE
repeated habits in the habits column

### ISSUE THREAD

**Issue by djoolz** [HabitRPG/habitica#15]
I'm not a dev, sorry for not speaking the lingo. :) My habits are repeated dozens of times in the habit column.

**Comment by lefnire** [comment]
definitely a bug. as long as you refresh it should fix itself, because of [this code workaround](https://github.com/lefnire/habitrpg/blob/master/src/app/index.coffee#L60), but still diagnosing why it's happening

**Comment by lefnire** [comment]
follow on #17
