### ISSUE TITLE
Load todo from txt

### ISSUE THREAD

**Issue by Vndtta** [HabitRPG/habitica#150]
I've got my todo list in a txt, is there anyway to load it to HabitRPG?

Thanks

**Comment by lefnire** [comment]
Not yet, but we're thinking gof supporting todo.txt in the future

**Comment by Vndtta** [comment]
I can try to help making a script to translate from todo.txt to habitrpg, but I would need to know how do HabitRPG stores the information

**Comment by kwelch** [comment]
Would be nice to do from a csv as well. This would allow to add massive
amounts and have different attributes added as well.

On Mon, Jan 21, 2013 at 9:38 AM, Vndtta notifications@github.com wrote:

> I can try to help making a script to translate from todo.txt to habitrpg,
> but I would need to know how do HabitRPG stores the information
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/150#issuecomment-12502808.

## 

Kyle Welch
224-772-4854

**Comment by wc8** [comment]
I think my idea of parsed text is related, (https://github.com/lefnire/habitrpg/issues/151).
It has to do with input in the site, but it would relate to making sure text in a todo.txt file went into the right section (habit/daily/todo) with the right parameters (up/down or day of the week, etc).

**Comment by horusofoz** [comment]
@vndtta It would appear this is covered under [Trello Card 81](https://trello.com/c/29qEE1DF). Are you cool for us to close this ticket and discussion to continue there?

**Comment by Vndtta** [comment]
Sure

**Comment by horusofoz** [comment]
@SlappyBag Can you close this ticket please?
