### ISSUE TITLE
upgrade bootstrap (or see if it's compatible with our current css overrides)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1500]

**Comment by paglias** [comment]
3.0.0 changes a lot of classes but I've found a lot of tools that upgrade the code automatically, don't know if they are  trustable but we can give them a shot

**Comment by paglias** [comment]
The main problem I found with this is angular-ui-bootstrap which doesn't support bs3, yet. They have a branch on github but it's a WIP. Modals are not working (even though there are some workarounds), I'll see what about tooltips and popovers which would be difficultier to use without angular-ui-bootstrap.

**Comment by lefnire** [comment]
Cool. yeah, I think tooltips/popovers are the only thing we're benefiting from right now. It looked like modals are completely different since ui-bootsrap 0.5 (which we're on) and >=0.6, and when I was looking at its format it didn't seem like we'd be easily able to use the new setup. Might be worth removing ui-bootstrap modals if popovers/tooltips are available for the bs3 branch. I'll leave it all to your digression though, since you're closer to the situation

**Comment by paglias** [comment]
@lefniee Oh oh, I just discovered that angular ui has been upgraded for Bootstrap 3! (V0.10.0) 

I can start working on it tomorrow but it will take time and will creare a lot of conflicts with other code being committed.

We should take 1-2 weeks without new features only fixes, improvements, interface...

**Comment by paglias** [comment]
@lefnire

**Comment by paglias** [comment]
#2636
