### ISSUE TITLE
"Team" link takes to non-existing page

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1501]
The one in the footer under "Company"

**Comment by wc8** [comment]
Team info can be found here, but it needs updating: http://community.habitrpg.com/content/about

**Comment by paglias** [comment]
So we can remove the team link?

**Comment by lefnire** [comment]
Yeah, we can remove it. I added you to the about page btw (we need to update that some more sometime soon, I'll hit that once we start marketing

**Comment by paglias** [comment]
removed
