### ISSUE TITLE
remove angular-ui-bootstrap

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1502]
far too buggy, every time I hit a snag in bootstrap stuff with the rewrite, it's been due to ui-bootstrap. The major gain of ui-bootstrap is tooltips & popovers being linked after directive render, which we'd have to use a $timeout for otherwise. So we'll need to figure out how to handle tooltips / popovers, or simply use a custom-built version of ui-bootstrap just for those components.

Right now the things we'll need to remove are tabs, modals, and accordions

**Comment by paglias** [comment]
Bugs like #1630 could be related to angular-ui-bootstrap?

**Comment by lefnire** [comment]
I think #1630 was also happening before ui-bootstrap. people were reporting tooltip / popover flicker. Incidentally, tooltips / popovers are the #1 thing ui-bootstrap solves, since otherwise we'd have to re-initialize them every time an element is re-drawn (eg, via ng-if or ng-view). Sill trying to figure out what we're gonna do about that

**Comment by paglias** [comment]
@lefnire closing, do you still want to move away from angular-ui?

**Comment by lefnire** [comment]
no way, it's awesome after BS3 + angular-ui-bootstrap's official upgrade to version-match. Thanks for migrating us to BS3 btw, _huge_ help
