### ISSUE TITLE
Sorting options in party member list fail during use of transformation item

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#15038]
### Description
The dropdown menu with sorting options for the party member list doesn't work when the member list is summoned via the transformation item workflow.

Steps:
1. Purchase some transformation items (Spooky Sparkles, Snowballs, etc.)
2. Have a party with 2+ members
3. Use one of the transformation items, bringing up the party member list
4. Attempt to use the dropdown options to change the sort order

![image(1)](https://github.com/HabitRPG/habitica/assets/4501321/aa5c8485-8cdb-4e17-aa12-4c3ceaebfdb1)

**Comment by sar-mko** [comment]
Hi, I'd like to work on this!

**Comment by MohitBansal321** [comment]
@sar-mko  are you working on it?

**Comment by sar-mko** [comment]
@MohitBansal321 Hi, no I'm not! I was waiting before jumping into it. It looks like there's already a pr, otherwise go for it.

**Comment by hullypereira** [comment]
Hi guys, can someone merge this PR?

**Comment by MohitBansal321** [comment]
> Hi guys, can someone merge this PR?

Only the Project maintainer has access to merge the PR

**Comment by CuriousMagpie** [comment]
Looks like the PR has been merged, so I'm closing this.
