### ISSUE TITLE
Play button on static/front does nothing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1505]
Tried to log out and back in (wanted to use my test user for a bit) today, and now the "Play" button on static/front clicks in but has no effect.

This error appeared in the console:

[19:10:31.453] "Error: [$injector:unpr] http://errors.angularjs.org/1.2.0rc1/$injector/unpr?p0=MembersProvider%20%3C-%20Members%20%3C-%20User
d/<@https://habitrpg.com/build/static.js:5
sb/m.$injector<@https://habitrpg.com/build/static.js:5
c@https://habitrpg.com/build/static.js:5
sb/p.$injector<@https://habitrpg.com/build/static.js:5
c@https://habitrpg.com/build/static.js:5
d@https://habitrpg.com/build/static.js:5
sb/p.$injector<@https://habitrpg.com/build/static.js:5
c@https://habitrpg.com/build/static.js:5
d@https://habitrpg.com/build/static.js:5
sb/g/<.instantiate@https://habitrpg.com/build/static.js:5
@https://habitrpg.com/build/static.js:6
M/m/<@https://habitrpg.com/build/static.js:6
f@https://habitrpg.com/build/static.js:5
m@https://habitrpg.com/build/static.js:6
g@https://habitrpg.com/build/static.js:6
g@https://habitrpg.com/build/static.js:6
E/<@https://habitrpg.com/build/static.js:6
U/e/</<@https://habitrpg.com/build/static.js:5
g.prototype.$eval@https://habitrpg.com/build/static.js:7
g.prototype.$apply@https://habitrpg.com/build/static.js:7
U/e/<@https://habitrpg.com/build/static.js:5
d@https://habitrpg.com/build/static.js:5
U/e@https://habitrpg.com/build/static.js:5
U@https://habitrpg.com/build/static.js:5
T@https://habitrpg.com/build/static.js:5
@https://habitrpg.com/build/static.js:8
fb.Callbacks/l@https://habitrpg.com/build/static.js:2
fb.Callbacks/m.fireWith@https://habitrpg.com/build/static.js:2
.ready@https://habitrpg.com/build/static.js:1
nb@https://habitrpg.com/build/static.js:1
"

**Comment by SabreCat** [comment]
Futzed a bit more and got these errors as well:

[19:34:08.078] Error: Permission denied to access property 'toString'
[19:34:08.361] Use of attributes' specified attribute is deprecated. It always returns true. @ https://apis.google.com/js/plusone.js:23
[19:34:09.064] "Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

**Comment by lefnire** [comment]
Perfect, that's the kinda info i need. Fixing

**Comment by lefnire** [comment]
pushing fix. Not happy with the solution, I've gotten to adding way too many deps in the static routes. Problem is we're doing auth client-side in order to replicate the mobile setup (which we should), but things are getting pretty ugly and I'm not sure the best way to handle them

**Comment by timconnor** [comment]
I had this problem yesterday morning (Australian time) as well. In the afternoon it was working again. However now I have the same problem again.

**Comment by lefnire** [comment]
Fixed again. https://github.com/lefnire/habitrpg/commit/01ac814b170e01a3eaab8eb6b7eef10f6e194e9c - I just realized when I was testing production deploy on local, I wasn't running in NODE_ENV=production (though was running the production build steps). This will allow me to be more careful going forward
