### ISSUE TITLE
Login/Password/LastPass/Forgotten Password Issues

### ISSUE THREAD

**Issue by CopticWalad** [HabitRPG/habitica#1506]
I have used this website everyday since it was released and I've never been so frustrated to log in.  
I'm using Google Chrome Version 30.0.1599.28 beta-m
I was unable to login before and I think the biggest issue was due to LastPass Extension.  I use LastPass for everything but despite working everytime in the past would not log in, and then randomly at another point it made the username field like a password (so typing would show as asterisks) and HabitRPG didn't even recognize its entered credentials.  When I disabled it and then refixed my username to be Case Sensitive, I finally was able to login after 3 days of frustration.  
What was even more frustrating and strange was the "Forgot my password never sent me an email" after 3 attempts.  I then did a gmail search and found that I never even got an email from habitrpg, ever.  Very unusual because I do login usually with my email address but later did not find it in the settings to confirm.  
Overall though now that I'm logged in I am happy to see that clicking on the tasks for completion is a lot more reliable and I will continue to use this site as I love it's idea.  Just very tough to convince the mass population to use as they don't like to type in anything, perhaps that should be the first thing on their to-do list.

**Comment by lefnire** [comment]
Bumping this one up. Many people have experienced login issues in varying ways. Equal numbers on mobile & web, so it's not to do with the rewrite per se but the API route `POST /api/v1/user/auth/local`. Self-assigning this ticket

**Comment by lefnire** [comment]
we added the requisite `username` and `password` name form-fields to the login page, lastpass should be ok now
