### ISSUE TITLE
"Unresponsive script" warnings

### ISSUE THREAD

**Issue by AranelS** [HabitRPG/habitica#1508]
Ever since the new site, Firefox has been throwing "Unresponsive script" warnings left and right.  Before it happens the whole browser freezes for a few (agonizingly long and tedious) seconds.  I get at least one, guaranteed, before I can successfully click anything.  (Usually more than one, especially if I start clicking multiple habits.)   

Is this happening to lots of other people, or should I come back later (when I have more time) and post more specific info to pinpoint the problem?

**Comment by paglias** [comment]
It's not oonly you, closing in favour of #1499
