### ISSUE TITLE
[Feature] text parse eg. "+-" in add new habit = up & down habit

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#151]
Feature Request for input box (or boxes) that parse the text entry so data can be added/edited without a lot of clicks. 

For the habit box, adding a + and/or - would register as up and/or down for the task.
For the daily box, adding SU,M,T,W,TH, F,S would make the new task apply to the respective day(s)
For the rewards box, 15, 5 or 15g would be interpreted as gold coin

In the future, as features are added, they could be incorporated:
Edit: ! or 10! could add a task rank/priority (https://github.com/lefnire/habitrpg/issues/53) modifier/multiplier.
"today" would make the task due today, and further elements could be parsed like tomorrow, jan 12, every 3 days, etc.

If a single task entry box was incorporated, H or habit, D or daily, T or todo could move the entered task into the appropriate section.

**Comment by racuna** [comment]
Maybe habitRPG could parse this from Twitter but none of your followers will understand WTF are you twitting..

**Comment by hookang** [comment]
Added to Master list of Features #169. Issue closed for organization.

**Comment by wc8** [comment]
[Text Parsing](https://trello.com/c/vDYCrh16)
