### ISSUE TITLE
Need more feminine hair options!!!!!

### ISSUE THREAD

**Issue by meghanuh** [HabitRPG/habitica#15102]
I wish there were better feminine hair options without a pay wall. Feels really unfair that the guys can feel represented in this community without paying but we have to pay :(((((. Please add more options for feminine hair :(((

**Comment by msscsh** [comment]
It's a shame you feel this way. What types of hair did you miss most? Can you give some models?

**Comment by CuriousMagpie** [comment]
@meghanuh Please reach out to [admin@habitica.com](admin@habitica.com); we do not track feature requests here. We usually ask that you fill out feature requests on this [Google form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link), but my opinion is that this is worth discussion with the wider team.
