### ISSUE TITLE
BUG: No Checklists in To-Do's on Challenges

### ISSUE THREAD

**Issue by Oorha** [HabitRPG/habitica#15100]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID:
  * Browser: All
  * OS: All

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
If you create a To-Do within a Challenge, you are not able to Add Checklist items. You are able to do this in your regular interface. Functionality is missing or broken.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Oorha** [comment]
Current Behavior:
![Screenshot 2024-01-17 at 22 22 33](https://github.com/HabitRPG/habitica/assets/86652054/1db5158f-144f-4272-8c57-f4051a58f8b0)


Expected Behavior:
![Screenshot 2024-01-17 at 22 23 09](https://github.com/HabitRPG/habitica/assets/86652054/9ae3c88c-9620-44bf-8142-e5d66f5addb7)

**Comment by msscsh** [comment]
The behavior has been reproduced and actually occurs. Tested using Google Chrome in today's version

**Comment by msscsh** [comment]
We need to add the following code, or similar, to the modal design in the challenges view:
![image](https://github.com/HabitRPG/habitica/assets/51372744/6edcbbea-1235-4989-9b59-797e78635f94)


If possible, it would be interesting to reuse the component, so that changes at one point are reflected in the whole

**Comment by msscsh** [comment]
There is a condition called **checklistEnabled** that takes care of presenting the checklist and is in the **taskModal.vue** file.
There is a section in the code that makes it clear that checklists should not exist for challenges.

File: habitica/website/client/src/components/tasks/taskModal.vue.
![image](https://github.com/HabitRPG/habitica/assets/51372744/0dd421f4-4131-4f90-afda-a68225ebc047)

Considering the **!this.isOriginalChallengeTask** section of the **checklistEnabled()** function, I believe we are not talking about a bug, but perhaps an evolution.

I suggest closing the issue @Oorha

**Comment by Oorha** [comment]
@msscsh Thanks for looking into this. Though I personally feel that checklists should exist for Challenges and can think of no reason for them not to, I'm sure there's an bigger picture to the decision. Thanks again.
