### ISSUE TITLE
How to know which version I'm running locally?

### ISSUE THREAD

**Issue by diyoyo** [HabitRPG/habitica#15129]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID:
  * Browser:
  * OS:

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Hi, I'm using the dev version of Habitica locally, but I can't figure out whether it's time for me to update or not. I'm seeing many releases in the past few weeks, and yet, when I do `git fetch` + `git status` I get `Your branch is up to date with 'origin/develop'.`

On the Android app, I was able to read the app version, yet, on the browser, I can't figure out where to look...

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by olisteadman** [comment]
Hi @diyoyo, as per [contributing guidelines](https://github.com/HabitRPG/habitica/blob/ff0bb9d005fba2b5fa04bbb79db23b12e46b223b/.github/CONTRIBUTING.md) Habitica uses [this Google form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link) to track feature requests. Please post there rather than creating an issue.

**Comment by CuriousMagpie** [comment]
@diyoyo Your best bet here is to use the `release` branch instead of `develop`. Thanks!
