### ISSUE TITLE
Feature requirement: calendar view

### ISSUE THREAD

**Issue by nickjiunchetti** [HabitRPG/habitica#15180]
we should be able to have a calendar view, for example, paying a bill is monthly, not daily.
So we should be able to set it up in another column view, and don't let it linger in the daily, until it's due date.

Custom columns would also be good, I have long term objectives like `climb mount everest` and short term problems like `fix cellphone screen`, and it's really bad to organize if everything is in the same column. 
We could have at laest sections within the columns, like:

TODO:

prioritized:
tasks for this week

incoming in future:
music festival on day 03/12

objectives:
climb mount everest
learn to surf

**Comment by nickjiunchetti** [comment]
example from ms todo:

<img width="541" alt="image" src="https://github.com/HabitRPG/habitica/assets/47458202/f006c2eb-18b5-434f-8e7a-e52f57ec34a9">


you have  todos, inside lists, inside sections

I know we can have a todo with multiple steps, which is a list in someways, but then you won't get xp/gold from it, and I do have some infinite lists(like the mountains I want to climb)

but sections is what is lacking the most

**Comment by CuriousMagpie** [comment]
Hi there, please use the [Feature Request Form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link) for your request. Thanks!
