### ISSUE TITLE
Drops do not appear to correlate with streaks in dailies.

### ISSUE THREAD

**Issue by baimeeker** [HabitRPG/habitica#1518]
Previously, it was typical for 21+ day streaks to result in a drop a high percentage of the time and for those drops to include more rare items like gold or pink potions. These days, I rarely get a drop despite 4-5 21+ day streaks in dailies. When I do, it is usually a potion, and that potion is almost always white for some reason. 

Also my 21+ day streak achievements are not updating to show that I have more of them. 

I'm patient, and I know you are still making changes. I just didn't see this particular issue listed anywhere. 

Username: baimeeker

**Comment by paglias** [comment]
It's the same issue as in #1498 and/or #1048?

**Comment by baimeeker** [comment]
Yes, perhaps another aspect of the same problem in #1498 . My understanding is that that was about an egg not disappearing after being used, but streaks are mentioned.  This problem started after the rewrite, so I'm not sure how relevant #1048 is, other than getting potions rather than eggs.

**Comment by paglias** [comment]
Ok i'm going to close this, can you post you're problem as a comment in #1498 so that we follow there?
