### ISSUE TITLE
Docker compose fails to build at step 5

### ISSUE THREAD

**Issue by Warrennoa** [HabitRPG/habitica#15187]
[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * OS: Fedora/Docker Compose

### Description
[//]: Docker builds to step 5/7 RUN npm install, it errors out at postinstall with

44.06 > habitica@5.22.0 postinstall
44.06 > git config --global url."https://".insteadOf git:// && gulp build && cd website/client && npm install
44.06 
44.60 [18:24:25] No gulpfile found
44.61 npm ERR! code 1
44.61 npm ERR! path /usr/src/habitica
44.61 npm ERR! command failed
44.61 npm ERR! command sh -c git config --global url."https://".insteadOf git:// && gulp build && cd website/client && npm install
44.61 
44.61 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-22T18_23_41_670Z-debug-0.log

I've been trying to see if there is a recent change to gulp, node, npm etc that could  have caused this, but I have not found anything

**Comment by jecpr** [comment]
Why was this closed? Did you find a solution? 

My issue:
OS: Ubuntu Server

Description
[//](https://github.com/HabitRPG/habitica/issues/15187#): Docker builds to step 5/7 RUN npm install, it errors out at postinstall with

44.06 > habitica@5.22.0 postinstall
44.06 > git config --global url."https://".insteadOf git:// && gulp build && cd website/client && npm install
44.06
44.60 [18:24:25] No gulpfile found
44.61 npm ERR! code 1
44.61 npm ERR! path /usr/src/habitica
44.61 npm ERR! command failed
44.61 npm ERR! command sh -c git config --global url."https://".insteadOf git:// && gulp build && cd website/client && npm install
44.61
44.61 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-22T18_23_41_670Z-debug-0.log

I've been trying to see if there is a recent change to gulp, node, npm etc that could have caused this, but I have not found anything

**Comment by jecpr** [comment]
Anyone finding this later on - if you are having unfixable problems with the docker instructions then check the dockerfile in the repo. For some reason mine was set to node:20 - despite the documentation clearly requiring node:14. Anyway, changed it to 14 and it magically works.

**Comment by CuriousMagpie** [comment]
We are using Node 20 now. However, I'll check to see that the dockerfile in the repo has been updated!

**Comment by jecpr** [comment]
It doesn't build successfully when I use node 20. Now it's built, I'll try re-building with 20 and see if the outcome is any different.
Edit: Tried fresh build `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --force-recreate --build` and then `docker-compose -f docker-compose.dev.yml up -d --build` with node 20 and it failed. Log is below:
```
Step 1/7 : FROM node:20
 ---> a740756586cb
Step 2/7 : RUN npm install -g gulp-cli mocha
 ---> Using cache
 ---> 9d4e4f1aab7d
Step 3/7 : WORKDIR /usr/src/habitica
 ---> Using cache
 ---> f5d39ca9c6e8
Step 4/7 : COPY ["package.json", "package-lock.json", "./"]
 ---> Using cache
 ---> be1408354d35
Step 5/7 : RUN npm install
 ---> Running in f8cc4a1b4e43

<---snip--->
> habitica@5.24.2 postinstall
> git config --global url."https://".insteadOf git:// && gulp build && cd website/client && npm install

[19:52:44] No gulpfile found
npm ERR! code 1
npm ERR! path /usr/src/habitica
npm ERR! command failed
npm ERR! command sh -c git config --global url."https://".insteadOf git:// && gulp build && cd website/client && npm install

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-05-17T19_52_11_661Z-debug-0.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
ERROR: Service 'server' failed to build : Build failed
```

This is the log when changing "20" to "14" in 'Dockerfile-Dev'
```
Step 1/7 : FROM node:14
 ---> 1d12470fa662
Step 2/7 : RUN npm install -g gulp-cli mocha
 ---> Using cache
 ---> 2aa53437c20f
Step 3/7 : WORKDIR /usr/src/habitica
 ---> Using cache
 ---> e99d78457f67
Step 4/7 : COPY ["package.json", "package-lock.json", "./"]
 ---> Using cache
 ---> 5407a0a1ff9d
Step 5/7 : RUN npm install
 ---> Using cache
 ---> 961d3dd6da87
Step 6/7 : COPY . /usr/src/habitica
 ---> Using cache
 ---> 7fe841efd5c5
Step 7/7 : RUN npm run postinstall
 ---> Using cache
 ---> 0cbd550e569f
Successfully built 0cbd550e569f
Successfully tagged habitica_client:latest
```

**Comment by duplaja** [comment]
Ran into the same issue, switching to node 14 did the trick for now.

**Comment by CuriousMagpie** [comment]
@SabreCat Do you have any ideas why switching back to node 14 allows a successful Docker build while 20 does not?

**Comment by jecpr** [comment]
As additional context, I am also having all of the issues raised in:
https://github.com/HabitRPG/habitica/issues/14349

**Comment by DesBlock** [comment]
I'm currently having this issue on a fresh install. Can this issue be re-opened?
