### ISSUE TITLE
FAQ Browers Support Derby reference

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1519]
http://community.habitrpg.com/content/browser-support says use Chrome because IE not supported by Derby. Since we are Angular now should this be:

1) deleted?
2) rewritten (if Angular supports some browsers better than others)?

**Comment by lefnire** [comment]
Angular supports IE! I think it has _some_ compatibility issues (eg, IE<9 have some concerns - but not many). And our code will get more supportive of all browsers over time (we're currently not using shivs where we could be). I'd say we mostly support IE, but when in doubt use something besides. Btw, for those that don't know - IE is famously a very bad browser, and most web apps have to make converted effort to support _it_ specifically, while the other browsers generally act the same. At the risk of being that guy - people just simply shouldn't use IE in general.

You wanna have at the FAQ wc8? or do you want me to

**Comment by wc8** [comment]
I'll take a stab at it.

**Comment by wc8** [comment]
I gave it a quick rewrite, just so it'd be more up-to-date.

> While the rewrite of HabitRPG.com mostly supports Internet Explorer, there may be some compatibility issues, especially in older versions. For best results, use a different browser, such as Chrome. If you encounter any difficulties, let us know.
