### ISSUE TITLE
"Upping" habit sometimes returns Internal Server Error

### ISSUE THREAD

**Issue by jbfp** [HabitRPG/habitica#1520]
Sometimes when "upping" a habit, the API returns an odd 500 Internal Server Error:

```
{"err":{"message":"Cast to number failed for value \"NaN\" at path \"items.lastDrop.count\"","name":"CastError","type":"number","value":null,"path":"items.lastDrop.count"}}
```

**Comment by lefnire** [comment]
Ahhh! I've been looking for this bug for forever!! Finally someone found
it. Ok, could you give me your user id & the name of the task that triggers
this?

**Comment by jbfp** [comment]
UserID: 919f682b-a3ce-4fda-947c-32c559a14479
TaskID: e5daab0c-b28d-421c-9323-277dac2b8f75
Task name: "test" (this is just the text)

**Comment by lefnire** [comment]
Nailed it. This ticket makes me happy, I was getting only a portion of the CastError in emails and the logs were too flooded to find in history (getting proper logging is on my TODOs). Thanks @jbfp. This could have something to do with #1498 too...
