### ISSUE TITLE
Missing Shade Armor Graphic in Rewards

### ISSUE THREAD

**Issue by Shaners** [HabitRPG/habitica#1521]
Currently is showing the gold weapon:
![goldshadearmor](https://f.cloud.github.com/assets/2374703/1126435/48e45c16-1b24-11e3-9289-88bfc1427c0b.png)
Other shade items show the correct graphics on the player though:
![goldshadearmor002](https://f.cloud.github.com/assets/2374703/1126443/76adc268-1b24-11e3-8bee-a972dba5fdd4.png)

**Comment by paglias** [comment]
it may be a problem of wrong css positioning, can you say which image should appear? and what is the css class of the reward image: on chrome right click on the weapon image, select "inspect element" (or something similar to that) and report the code that appears highlighted

**Comment by paglias** [comment]
The image that should appear is the sword the avatar has in the image you posted? Also the avatar body is gold, it is right or should be the one near your's avatar helmet here https://habitrpg.com/bower_components/habitrpg-shared/img/sprites/shop_sprites.png?

**Comment by Shaners** [comment]
It is supposed to show this image: ![shade-armor](https://f.cloud.github.com/assets/2374703/1140409/617cabf4-1c9e-11e3-837f-b294c68ba19d.png) in the rewards column.
This is what chrome is throwing: `background-position: -1160px 0;}`
Which should be correct, no?

`<span ng-class="{&quot;shop_armor_6 shop-sprite item-img&quot;: true}" class="shop_armor_6 shop-sprite item-img"></span>`

All images on the character are correct, it's purely with the rewards image.

*Edit: Reset all my equip to the gold level stuff and saw that it is happening for all of the shade level equipment:
![shade-rewards](https://f.cloud.github.com/assets/2374703/1140498/2891fa04-1ca0-11e3-814d-a07bd3388a27.png)

**Comment by paglias** [comment]
yes it's correct but the shop_armor_6 is interpreted befor the background image rule so it is overriden by it. This is because in habitrpg-shared the order of css files is not defined, will fix it later

**Comment by paglias** [comment]
Should be fixed in https://github.com/HabitRPG/habitrpg-shared/commit/ae4f3a6481312f54859e289b2afc12d5bb14f635 but to be sure as soon as @lefnire pushs it to beta we should check if everything is ok

**Comment by lefnire** [comment]
check on prod in a bit. I may have pushed beta before your fix went in, and I don't know how to trigger re-bower-install on heroku without another commit

**Comment by paglias** [comment]
ok, I won't be able to check anything this evening, @Shaners can you give a look in a few hours?

**Comment by Shaners** [comment]
It's all good now! :sunglasses::thumbsup: 
![shade-reward-set](https://f.cloud.github.com/assets/2374703/1141604/a446a692-1cb7-11e3-8f5c-20dc9d346b81.png)
(on beta)
