### ISSUE TITLE
Item purchased at Seasonal Shop gone

### ISSUE THREAD

**Issue by Kalshone** [HabitRPG/habitica#15219]
Hello, I purchased the whole swan mage set. The gems were taken from my account but the swan dress item is not in my inventory and is gone from the shop :( 

My user id is 0d4aeac5-c45a-4314-a175-a10c568967da

**Comment by CuriousMagpie** [comment]
Hello! We don't provide user support via GitHub issues. Please send an email to [admin@habitica.com](mailto:admin@habitica.com). Thanks so much!
