### ISSUE TITLE
Re-organize habitrpg-shared branches

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1522]
1. move #master => #derby
2. move #rewrite => #master
3. update habitrpg #derby, #develop, #master package.json files

**Comment by lefnire** [comment]
back on master, derby's dead so whatevs on that branch. will kill rewrite after we've closed all the prs there

**Comment by Shaners** [comment]
RIP derby :bouquet:

**Comment by lefnire** [comment]
Just spent a ton of time looking for a coffin or veiled woman or something, and realized "what am I doing?"

**Comment by Shaners** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;:trollface:
:muscle::point_left:

**Comment by lefnire** [comment]
Giving @zakkain a run for his money!
