### ISSUE TITLE
Groups: add "who have you invited"

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1523]

**Comment by paglias** [comment]
i'm going to take this, do you think that making a global find on the users to see who are invited to a specific party/guild is too expensive in term of performances? Well it will depend a lot on how many users are out there mostly

**Comment by lefnire** [comment]
Yeah, I think that will be pretty expensive actually. Party would be easy: `User.findOne({'invitations.party.id':PARTY_ID})`. But because invitations.guilds is an array, you'd probably have to do a map-reduce. But in theory: `User.find({'invitations.guilds.$.id':GUILD_ID})`. We'd need to `ensureIndex` on those two fields as well.  Are you sure we need this feature? Nobody's asked for it before. But if you think it's fun / valuable, I'll help you out

**Comment by paglias** [comment]
Sincerely i found a bit annoying not seeing the users I invited because the
user doesn't know wheter they have been correctly invited or not but it's
certainly low priority, so I'll implement it maybe in the next future

2013/9/13 Tyler Renelle notifications@github.com

> Yeah, I think that will be pretty expensive actually. Party would be easy:
> User.findOne({'invitations.party.id':PARTY_ID}). But because
> invitations.guilds is an array, you'd probably have to do a map-reduce. But
> in theory: User.find({'invitations.guilds.$':GUILD_ID}). We'd need to
> ensureIndex on those two fields as well. Are you sure we need this
> feature? Nobody's asked for it before. But if you think it's fun /
> valuable, I'll help you out
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1523#issuecomment-24407080
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
fair enough. Yeah, let me know when you get started then if you need help with database stuff
