### ISSUE TITLE
Missing Achievement

### ISSUE THREAD

**Issue by nuzzlebutt** [HabitRPG/habitica#1524]
I recently bought the final Golden item and have zero items left to buy in my rewards section.  But I don't have the achievement for having the fully upgraded armor set.

**Comment by jbenzimra** [comment]
Same for me.
![screenshot 2013-09-12 at 10 02 18 am](https://f.cloud.github.com/assets/5383317/1129102/c67ce35c-1b81-11e3-9623-19ce0fad9f00.jpg)
![screenshot 2013-09-12 at 10 01 54 am 1](https://f.cloud.github.com/assets/5383317/1129103/c68f08ac-1b81-11e3-8610-307e18b34d0a.jpg)

**Comment by demhips** [comment]
Same here

**Comment by hammermybones** [comment]
Also missing this achievement. I noticed that Issue #1514 is marked as closed, but I am still with the original problem.

**Comment by lefnire** [comment]
@hammermybones #1514 was quite assuredly fixed, verified by a handful of users. Per chance you registered within the last few weeks and missed the veteran achievement?

**Comment by hammermybones** [comment]
Sorry, wasn't paying proper attention to issue #1514 and just saw the 'missing achievement.' To clarify, I am in fact missing the 'Ultimate Gear' achievement.

**Comment by paglias** [comment]
@hammermybones closing in favour of #1543
