### ISSUE TITLE
Contributing Guidelines Link Has Inaccurate Information

### ISSUE THREAD

**Issue by infinity-skies** [HabitRPG/habitica#15257]
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID:
  * Browser: -Github issue
  * OS: -Github issue

### Description - Github contributing guidelines linked [here](https://github.com/HabitRPG/habitica/issues/2760#issue-26998767) still references guilds as a primary means of support and troubleshooting, despite guilds having been discontinued nearly a year ago. Many references still link back to guilds, which returns a 404 error, especially on the wiki.  
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by anishlukk123** [comment]
@infinity-skies  can I work on this

**Comment by CuriousMagpie** [comment]
[Fandom.com](http://fandom.com/) wikis are made to be user/fan-created and maintained spaces, rather than spaces with heavy involvement from the creators of a property or game. We fully support and welcome players updating the wiki to help each other, while our team is working to update and improve the in-game FAQ.
