### ISSUE TITLE
Suggestion: Make it installable as a Chrome app.

### ISSUE THREAD

**Issue by ddd75a650fee04c0ce576c877521c6bd** [HabitRPG/habitica#15267]
It would make it quicker to access it from PC.
Like this:
![image](https://github.com/HabitRPG/habitica/assets/173018017/b0f6d5cf-39d5-47d8-8e24-36770b54ba57)

**Comment by CuriousMagpie** [comment]
We don't take suggestions via GitHub. Please fill out the [Request A Feature Form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform) instead. Thank you.
