### ISSUE TITLE
'report a bug' links on contact page and the footer do not work on chrome

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#15296]
to reproduce:

**contact page**
1. click 'help' at the top of the habitica homepage
2. click 'contact us' at the top
3. select 'report a bug'

**footer**
1. navigate to the habitica homepage
2. scroll down to the footer and select 'report a bug'

**Comment by CuriousMagpie** [comment]
I just tried to reproduce this in Chrome, Firefox, and Arc (Chromium browser) and was unable to do so. Do you have any more details on this?

**Comment by the-true-jazzgot** [comment]
Link in footer doesn't work for me either (in some cases, it's inconsistent) and there is neither href attribute nor component id on it when inspected with Chrome devtools:

![image](https://github.com/user-attachments/assets/de6eb2fb-1b34-41e9-921d-5e444a746260)

Found one consistent case tho:
**Steps to reproduce** 
1. go to https://habitica.com/static/faq
2. Scroll down to footer and click on 'Report a bug'

Microsoft Windows 10 Home 10.0.19045
Google Chrome Version 127.0.6533.120 (Official Build) (64-bit)

**Comment by CuriousMagpie** [comment]
Thanks for looking into this; I was able to duplicate the issue which may be confined to the static footer (the purple one). 

I logged out and checked both the login page and the FAQ (both use the same footer component) and when I clicked on "Report A Bug" I got a blank window. This may have something to do with not being logged in and while you can be logged in and looking at the FAQ, in both cases the same footer component is in play.

**Comment by Prathamesh0901** [comment]
Can I work on this issue?

**Comment by CuriousMagpie** [comment]
Hi @Prathamesh0901, we are still discussing how we want to handle this. Thanks!

**Comment by fullmoonemptysun** [comment]
I tried reproducing, but to no avail. The link works fine on Chrome

**Comment by CuriousMagpie** [comment]
As stated, it is only broken when you're logged out.

**Comment by Abhinab04** [comment]
can i work on this issue?

**Comment by CuriousMagpie** [comment]
@Abhinab04, we're still discussing how we want to handle this. Thanks!

**Comment by fullmoonemptysun** [comment]
> As stated, it is only broken when you're logged out.

I tried clicking both when logged in, and logged out. It seemingly only occurs on particular versions.

**Comment by CuriousMagpie** [comment]
We have determined that this is not a bug but a browser settings issue relating to the `mailto://` link. You can update your settings in Chrome under the Protocol Handlers section.

![Chrome Settings](https://github.com/user-attachments/assets/f563bb68-8e26-4609-a857-69eae0d46b07)
