### ISSUE TITLE
Chat Refresh: Fetch = Send

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1530]
If anything is in the message box when you hit the sync symbol button (Fetch Recent Messages), it will be sent out to the Tavern. 
Is this the intended result? It might be confusing to the users.

**Comment by lefnire** [comment]
not intended result. And could be the reason sync isn't working, will look into.

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/066364e3c9a38cc0d1be3da8772eb4930ef2cd68
