### ISSUE TITLE
Orb of Rebirth doesn't work in Firefox

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#15303]
A number of users reported in #13973 that they were unable to purchase the Orb of Rebirth using Firefox. We were able to determine that this issue was separate from `t.response undefined`. 

---
@CthonicSyzygies:
> I'm having this issue again today. Happens exactly as described by the above posters. I'm level 75. I'm trying to purchase it because it's the first day of the new year. When I click, it asks me for confirmation, I confirm, and it refreshes the page; I've tried 3 times, and the third time I noticed the "t response undefined" message in the Habitica notifications.

> The only thing I can think of is that I'm in a quest, but I don't think that would impact this.

> Firefox, I created my account in 2013, anything else you would need?

---
@un34s:
> This is happening to me today. I tried several times to purchase the orb. It seems to go through--the site refreshes, and everything is slowly reloaded, but I remain at level 101. I even tried leaving the quest I was in just in case that helped (it did not). Finally I tried it in Chromium (101.0.4951.15 (Developer Build)) rather than Firefox (109.0 build 20230109161414) and it worked. Chrome is an anti-privacy browser so it would be very nice if Firefox were fully supported.

---
@slach123:
> I also had this problem and tested many times on Firefox, fully refreshing the page, signing in and out, clearing cookies/cache and kept getting the t.response is undefined error. Tried in Microsoft Edge and worked first time. Please fix this so that Firefox users can have a complete experience. Like un34s commented Chromium is anti-privacy and I would hate for Habitica to force its user to use it.

---
@ctrueden:
> In line with other comments here: I also receive the error when attempting to rebirth in Firefox, whereas it works in Chrome.

---
@gwisp2:
> I attempted to examine this issue. While I couldn't replicate the 't.response undefined' error, I discovered that when clicking the 'buy' button, a POST request to /user/rebirth and a page reload occur simultaneously. When the page reloads, any ongoing requests get aborted. Therefore, if the rebirth request isn't sent quickly enough, it gets aborted.

**Comment by slach123** [comment]
Still getting this error even though it's been marked as completed. Same thing, t.response is undefined on firefox. Works on Duckduckgo browser no problem.
![image](https://github.com/user-attachments/assets/9ee117b1-27ca-42ed-afb7-185444428ef7)

**Comment by CuriousMagpie** [comment]
The t.response is undefined error is still open (#13973); it was not related to folks being unable to purchase Orb of Rebirth on Firefox, which has been fixed.
