### ISSUE TITLE
Can't log in using autofilled password

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1531]
If I log in to the site using my password as filled in by Firefox's saved passwords feature, this error appears:

![screenclip](https://f.cloud.github.com/assets/4501321/1135529/910776b2-1c15-11e3-8f62-144799967c9b.png)

If I backspace it out and retype it, I make it in just fine. I've confirmed that my saved password is correct by clipboard-copying it directly from the saved password list and pasting it in. It appears I have to perform some degree of manual entry into the field for it to accept the password correctly.

**Comment by Shaners** [comment]
Probably similar to the 1 password issue? #1506

**Comment by lefnire** [comment]
definitely the same issue, and I think i know what's going on at this point. Let's close this one and I'll explain my theory there

**Comment by lefnire** [comment]
actually, my theory is wrong. Ha. But anyway, same issue. I'll follow up with any progress
