### ISSUE TITLE
CastError: Cast to number failed for value "04:00" at path "preferences.dayStart"

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1532]
Hmm... how to handle this. So custom day start is supposed to be entered as an integer, but some people are entering it as "04:00" - which can't be int-casted. Since we're not setting the value on a dedicated API route (but instead doing `User.set('preferences.dayStart',...)` - we can't sanitize it server side. Maybe we just need to have a validator on that input field via angular

**Comment by BlackEdder** [comment]
How about turning it into a drop down list? That should solve the problem. The down side of course would be that the drop down list would get quite long.

**Comment by paglias** [comment]
what about sanitizing it in a mongoose pre save middleware http://mongoosejs.com/docs/middleware.html?

**Comment by paglias** [comment]
I tried to set a value like "04" on my local installation and angular converts it to 4 which should be correctly, sincerely I don't know how to set a value like "04" and "04:00" trigger an html5 validation error, maybe is something prior to the rewrite?

**Comment by lefnire** [comment]
ah! Presave, why didn't I think of that. Will do!
