### ISSUE TITLE
Not possible to disable Sign Up page - Docker

### ISSUE THREAD

**Issue by PeterTucker** [HabitRPG/habitica#15332]
How do we disable the option to sign up new users for self hosted? I see nothing in the config files, and this doesn't seem possible.

**Comment by CuriousMagpie** [comment]
We don't provide user support here on GitHub. Please address your question(s) to [admin@habitica.com](admin@habitica.com). Thanks!

**Comment by PeterTucker** [comment]
I tried emailing. Never got a reply.

**Comment by CuriousMagpie** [comment]
We try to answer all emails. Sometimes they do get lost in the process--we get a lot of email. Can you please resend?
