### ISSUE TITLE
I cant Reinvite my friend to my party 

### ISSUE THREAD

**Issue by HobTold** [HabitRPG/habitica#15331]
Unable to reinvate my friend who left the party and who wants to join in

![image_2024-09-30_161328143](https://github.com/user-attachments/assets/c13588d0-8c79-4422-ad6c-7b9199feed96)

![image_2024-09-30_161404815](https://github.com/user-attachments/assets/be2e9ecf-7843-4ac3-b118-0d9e75c2ac68)
My friend is not on the party currently

**Comment by CuriousMagpie** [comment]
Please do not create GitHub issues for user support requests. You can either email us directly at [admin@habitica.com](admin@habitica.com) or use the "Report a Bug" menu item in the Help Menu. Thanks.
