### ISSUE TITLE
Change Twitter Icon to X Icon

### ISSUE THREAD

**Issue by jenyyy4** [HabitRPG/habitica#15336]
### Issue: Change Twitter Icon to X Icon

**Description:**
With the recent rebranding of Twitter to "X," we need to update the Twitter icon on our website/portfolio to reflect the new logo. This change should be applied wherever the Twitter icon is currently displayed (e.g., social media links, footer, header, etc.).

**Example Code Update:**
```html
<!-- Old Twitter Icon -->
<a href="https://twitter.com/yourprofile" target="_blank">
  <img src="path/to/twitter-icon.svg" alt="Twitter">
</a>

<!-- New X Icon -->
<a href="https://x.com/yourprofile" target="_blank">
  <img src="path/to/x-icon.svg" alt="X">
</a>

**Comment by jenyyy4** [comment]
@phillipthelen i would like to work on this issue, please assign it to me.

**Comment by HtcYlmz** [comment]
I would like to work on this issue.

**Comment by CuriousMagpie** [comment]
Habitica's moving off of Twitter

**Comment by Shayan12456** [comment]
@CuriousMagpie Why my PR is not merged?
