### ISSUE TITLE
Difficulty Logging into Iphone app

### ISSUE THREAD

**Issue by tack00** [HabitRPG/habitica#1533]
Hey guys, I'm sorry if this is too minor an issue to be posting here, but I'm not sure where else to ask. I've recently downloaded the Habitrpg Iphone app, but for some reason I can't seem to login to my existing account. Would I need to make a new account to use the iphone app?

My user name is Tack00.

Thanks!

**Comment by lefnire** [comment]
what errors are you seeing?

**Comment by tack00** [comment]
Ah, sorry for the late response. Turns out I was just being dumb and forgot about the whole case sensitive thing. Thanks for the help anyway!
