### ISSUE TITLE
add Ebbinghaus repeat  to task

### ISSUE THREAD

**Issue by skyerGalaxy** [HabitRPG/habitica#15343]
could habitica add Ebbinghaus-like memory cycle function to task?

**Comment by CuriousMagpie** [comment]
Hi there! Please use the [Request a Feature](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link) form for these sort of requests. Thanks!
