### ISSUE TITLE
Provide a means for users to intentionally review tour

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1536]
At the moment, the startup tour is one-and-done based on browser and computer (I think; cookie maybe?). In order to view it again, you need to start a new account or log in from somewhere else (or clear cache?). As we work on making the tour more useful and informative--see issue #1513--it could be worth our while to provide a place on the Options page to restart the tour.

This could later become a jumping-off point for several different tutorials, like tours unlocked for new features or a library of cool inventive tips and poweruser tricks.

**Comment by paglias** [comment]
You can restart it from the settings page!

**Comment by SabreCat** [comment]
Oh! That must be brand new! Closing.
