### ISSUE TITLE
Checking Off Task

### ISSUE THREAD

**Issue by haedonk** [HabitRPG/habitica#15366]
### General Info
  * UUID: c17c2422-1a61-4ffc-8703-302217094e11
  * Browser: Chrome
  * OS: Windows 10

### Description
When a user clicks on the checkbox of any task to mark it as completed, it instantly disappears without any kind of prompt for confirmation or even providing an option to undo. Such actions will result in users accidentally marking tasks as complete and reduce user control/flexibility.

**Comment by MrJellyB** [comment]
Can I take this one?

**Comment by CuriousMagpie** [comment]
If a user wishes to uncheck a task, they can select "All" on the Task List and uncheck it there. The "All" view shows all tasks regardless of due date or completion status.
