### ISSUE TITLE
Removal of game items from shop is permanent

### ISSUE THREAD

**Issue by pipng13579** [HabitRPG/habitica#1537]
When I initially joined habit RPG, i thought that the items in the shop were examples, so i deleted all of them. Now i realised that the RPG hinges on buying these in-game items, but I have removed them and they are now permanently gone. Could we make these items un-deletable and restore these items to those who may have deleted it?

**Comment by paglias** [comment]
Which items are you talking about? The ones under the "Rewards" column can't be deleted unless you created them

**Comment by pipng13579** [comment]
![image](https://f.cloud.github.com/assets/4781051/1145146/58dd2020-1df5-11e3-8e12-c1592babaf8e.png)

Hmm, somehow I managed to remove them. I have tried ctrl+f5 to get a server copy of the page, but that did not help.

**Comment by paglias** [comment]
How did you managed to remove them? They are stored server side so you can't have removed them, did you edit the page html? the console shows any error (on chrome ctrl+shif+j)? have you tried from another pc?

**Comment by pipng13579** [comment]
I remember that all the items had a "delete" button and I just clicked on every one of them. Could it be that a new update removed this feature?

The console log says:
Sync: Queue is empty app-ea0e0b8d.js:14
Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=ht…26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey:1

**Comment by pipng13579** [comment]
This issue is not a local issue. I can replicate it in chrome on another computer as well. (And interestingly, the 'play' button does nothing on internet explorer for the static front page)

**Comment by pipng13579** [comment]
I got the rewards back now that I have levelled up! :) I'll close this since it seems to be a fluke that I managed to delete the rewards.
