### ISSUE TITLE
Wishlist: Daily tasks with no HP loss for failure

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#1539]
I keep finding there are task types which I'd like to receive XP for if I complete them, but only at most once per day, and with no HP loss if I fail.

For example, the first git commit of the day should generate XP, but usually if I'm hacking code, I'm making lots of commits, and they can threaten to overwhelm my HabitRPG experience. However I don't want to _lose_ HP if I don't commit, I'm probably off doing other things.

"But wait," I hear you cry! "Why don't you just stop pressing the button after the first time?"

Two reasons. Firstly, I'm poor at remembering if I've claimed my XP or not. But more importantly, my use of HabitRPG is becoming increasingly automated, with my exobrain picking up activity using the HabitRPG APIs to up/down tasks as appropriate. If HabitRPG has a native way of marking something as "claimed for the day", then I don't need to put extra smarts into my system, and it doesn't matter if I claim it from the phone, web, or cloud of bots.

One possible way of implementing this is as a tweak to how daily items work. A little ticky-box for "non-fatal" dailies would suffice, and code under the hood to not cause HP loss for non-fatal dailies.

<3 Paul

**Comment by wizonesolutions** [comment]
+1

**Comment by wc8** [comment]
I'm puzzled, you can do this already, can't you with Grey dailies? 
Disable all day of the week buttons, eg. S M T W T F S.

**Comment by wc8** [comment]
Closing this, since daily tasks with no HP loss is possible. Reopen/comment back if I missed something.

**Comment by pjf** [comment]
You can complete a task and get XP/GP if it's not due on that day? If so, that's perfect. :) Thank you very much! <3

**Comment by Shaners** [comment]
Yep you should be able to. A daily not assigned any days just loses the penality it otherwise would have inflicted if missed.
