### ISSUE TITLE
Missing 21-day streak achievement

### ISSUE THREAD

**Issue by djuretic** [HabitRPG/habitica#1540]
I reached a 21-day streak in one of my dailies, but the Achievements page shows "0 Streak Achievement(s)".

I tried to search the source code for that functionality, I only found this on `archive/derby_controllers/unlock.coffee`:

``` javascript
if (after % 21) is 0
    dontPersist =  model._dontPersist; model._dontPersist = false
    user.incr 'achievements.streak', 1, (-> model._dontPersist = dontPersist)
    $('#streak-achievement-modal').modal('show')
```

Is that feature ported to the AngularJS rewrite?

**Comment by lemoness** [comment]
Great, tracking this :)

**Comment by brightbold** [comment]
Two of my party members also achieved 21-day streaks post-Derby and did not get the achievement. There's definitely something funky here.

**Comment by lefnire** [comment]
yep, i'll fix this today. the achievement set was client-side in derby, rather than in habitrpg-shared - I just need to move it over

**Comment by lefnire** [comment]
have to push back till tomorrow, but made big progress

**Comment by ghost** [comment]
I am not getting streak achievements, either. Is this still a problem being worked on, or has this thread shifted to Ultimate Gear achievement?

**Comment by lefnire** [comment]
Not fixed yet, on my plate - laid some groundwork for the fix, but it's not
100%

**Comment by paglias** [comment]
Streak achievements are back! The commits are https://github.com/HabitRPG/habitrpg-shared/commit/9285a3e44b3f4d4ce33379c01c9872e6e6f2427e for habitrpg-shared and https://github.com/HabitRPG/habitrpg/commit/20f2d75bbf19bdb6ca3c6a519308a21ed6fe0e7c for the main site

**Comment by lefnire** [comment]
Awesome man! One thing - looks like it requires a refresh to go through (modal & badge don't show until after refresh, undo doesn't remove until after refresh - [video](https://dl.dropboxusercontent.com/u/3869142/streak_achievement.mp4)). I think the solution is to `user.markModified('achievements')` after setting the achievement. I haven't figured out what the deal is here, but sometimes certain attributes don't get flagged dirty after being modified, and so `user.__v++` never picks up (meaning that browsing session doesn't refresh the user)

**Comment by paglias** [comment]
@lefnire try now updating habitrpg-shared, I didn't run `grunt` so the browser wasn't getting the new code

**Comment by paglias** [comment]
the commit is https://github.com/HabitRPG/habitrpg-shared/commit/79e0d5cba2ff5567c8ca20a18b0b74fa8b9a2419

**Comment by lefnire** [comment]
sure enough, that did the trick! deploying

**Comment by lefnire** [comment]
Random thought, should we start removing the `paths[...]=...` stuff? We used to have that since it was required for Derby to be aware of what's been modified; however, Angular's digests & Mongoose's attr-setters take care of the situation and don't need to know which paths have been modified. On the one hand, none of our current projects use `paths` (now that we're off Derby), on the other hand _other_ projects might find it useful if they use habitrpg-shared. What do you think, keep / remove / whatever-it-doesn't-matter ?

**Comment by paglias** [comment]
I thought they were needed for mongoose... I would remove them, I mean I don't think that anyone uses habitrpg-shared and even if they did they should trust only the api, I think habitrpg-shared is made for the main site client & server and for the mobile app. As a developer I would not rely on it, but we can also keep them, it's the same

**Comment by lefnire** [comment]
Ha, you're the same as me. "Meh". But cool, I'll take a peak later to make sure nothing is using it, and if not I'll just delete them when I see them

**Comment by lemoness** [comment]
Quick question - is there a way for us to retroactively get streak
achievements? Because I got a bunch in the interim period, but they still
haven't showed up. Also, will above-21 streaks garner the achievement (aka
will I get it for clicking a Daily for the 30th time)??

**Comment by lefnire** [comment]
Unfortunately no. We'd have to write a database migration, and even at that I can't think of a possible way. We'd have to count all users' dailies' streaks mod 21, and add that many achievements - but there's no way to tell how many current achievements happened after the achievements weren't working vs how many of users' current were from before

**Comment by brightbold** [comment]
Wait, seriously? I've been telling people in the tavern their achievements will show up once it it was ported. I don't want people coming after me with pitchforks!

**Comment by lefnire** [comment]
I mean, I could just add achievements for all `task.streak % 21`, but people are going to end up with many more achievements than is accurate

**Comment by lefnire** [comment]
alternatively I could could set people's achievements manually if they shoot me a #

**Comment by brightbold** [comment]
Yeah, I was just writing the following comment when I saw your above comment in email:

How about a temporary honor system (like the reset streak) that lets us enter the total number we think we should have? Is that possible? I think people are going to be disappointed not to get that reinforcement. It's been a long time since anyone's had a streak achievement!

So whichever of those two solutions is less work for you seems good to me. If you put it on us, then people who care can up their numbers and people who don't won't create extra work for anyone.

**Comment by lefnire** [comment]
That's probably the easiest fix, I'll get started on that

**Comment by brightbold** [comment]
Thanks - that's awesome. You'll need to tell us the date that streak achievements stopped recording so we can do the math.

**Comment by lefnire** [comment]
July 9th, Angular rewrite go-live day

**Comment by lemoness** [comment]
Fantastic workaround, considering. I agree that people would have been very upset - I certainly would have!!

**Comment by lefnire** [comment]
pushing to beta. will push to production later once i can sift out some of the newer things (like hair)
