### ISSUE TITLE
Didn't receive Ultimate Gear achievement

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1543]
Hello,

I could buy today the last shield, and now have:

```
Golden Sword: 18% Exp gain
Golden Armor: 10% Defense
Golden Helm: 6% Defense
Golden Shield: 8% Defense
```

But the achievement isn't available. My user id is 84497c76-4028-4dd5-8403-69b4f5b12575

I'll check again tomorrow in case achievements are updated only once a day.

**EDIT:** No, still not received a day after

**Comment by brightbold** [comment]
Related to #1540 ?

**Comment by lefnire** [comment]
yep, i'll fix this today. the achievement set was client-side in derby, rather than in habitrpg-shared - I just need to move it over

**Comment by AdrienLemaire** [comment]
Ok thank you :-)

**Comment by lefnire** [comment]
have to push back till tomorrow, but made big progress

**Comment by paglias** [comment]
@lefnire the achievement in now correctly awarded in habitrpg-shared https://github.com/HabitRPG/habitrpg-shared/commit/d7416117f9211d08bb42eafbffc296917d0c21a9 and a notification is shown https://github.com/HabitRPG/habitrpg/commit/a5af52a275c267b75381c2a3100210d76e4f311a, do we need to run a migration to award it to some people who may have not it?

**Comment by paglias** [comment]
also @lefnire the beast master achievement should be awarded on habitrpg-shared too I suppose, but where?because pets hatching is all client side angular....

**Comment by lefnire** [comment]
May need to run migration, I'll revisit that if I start hearing complaints about missing achievement. They'll gain the achievement though if they die and then re-gain their armor, so it's not a fully missed bandwagon.

Yeah... beastmaster... what we could do is award it on client with the pet. It's not ideal, but currently only the website uses pets, so no other apps could trigger the award anyway (this will change eventually). Maybe we could do a `user.pre('save')` Mongoose middlware to check if `this.items.pets.length >= 90`? What do you think?

**Comment by rjalan63** [comment]
Hello,
I've bought all the available armor but haven't unlocked the ultimate gear achievement.
My user id: 9cd6a408-fe6f-4425-a1d7-db18a650e800
What am I missing?

**Comment by paglias** [comment]
@rjalan63 did you bought them now (or some days ago) or a lot of time has passed since you bought them?

**Comment by lefnire** [comment]
@rjalan63 I updated your profile manually for now. Tried reproducing the error on a new user, no cigar.. hmmm

**Comment by paglias** [comment]
@lefnire if you plan to write a migration to award beast master achievements it may be a good chance to also remove those undefined pets from users

**Comment by lefnire** [comment]
I believe all the undefined pets have been removed - have you seen them still?

**Comment by paglias** [comment]
My pets count says 35 but I only have 34, 2 of which are rare pets, so I
believe I have some undefined ones

**Comment by rjalan63** [comment]
@lefnire thanks for fixing it! I'll let you know...

**Comment by lefnire** [comment]
Oh, that was all pag!

**Comment by rjalan63** [comment]
@lefnire I can't seem to unlock any golden potions. I thought you could get those once you get all the armor. Or is it completely random? I'm up to 53 pets now.

**Comment by lefnire** [comment]
@rjalan63 golden pots are more rare than the rest. See [this wiki](http://habitrpg.wikia.com/wiki/FAQ#I.27m_Getting_More_Potions_Than_Eggs_.28or_Vice_Versa.29) which has distribution details
