### ISSUE TITLE
Make "Todos" into "To-Dos"

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1544]
Figured I would stick this in here because it's such an easy fix. In Spanish, "Todos" means "all", and I've gotten more than one confused person who knows Spanish and wants to know why there are three columns when they are supposed to put everything in the "all" column. 

Adding a hyphen and a capital D really can't be difficult, right?

**Comment by djuretic** [comment]
Another option is to use "ToDo" (without hyphen).

**Comment by lemoness** [comment]
Either works for me :)

**Comment by wc8** [comment]
Alternatively, **Tasks**
—or just call it _Onces_ :wink: and, as with Dailies, suggest function without the constraint of dictionary meanings. 
(P.S. I jest about _Onces_.)

**Comment by lefnire** [comment]
Not tasks. Tasks has been used historically as the general term for all the objects (todos, dailies, habits, rewards) and is also defined on the schema as such

**Comment by lemoness** [comment]
Okay then, To-Do or ToDo. I think the hyphen looks cleaner, personally.

**Comment by SabreCat** [comment]
"To-do" is the more standard English usage. It's a "To-do list", not a "Todo list".

**Comment by lemoness** [comment]
Exactly! :D

**Comment by snicker** [comment]
Looks like this one should be closed?
![image](https://f.cloud.github.com/assets/221540/1502254/00328938-4898-11e3-9357-006b045e4eb4.png)

**Comment by paglias** [comment]
Right @snicker , closed!
