### ISSUE TITLE
Tasks won't delete!

### ISSUE THREAD

**Issue by Moxana** [HabitRPG/habitica#1547]
I left my HabitRPG alone a long time in tavern rest mode and I'm finally coming back to use it and I need to delete a lot of outdated tasks (I rerolled so everything is neutral again) and I can't get any of them to delete! I hover over and get the little pointer hand but I can't click.

Is it something I'm doing wrong/don't have/don't have enabled?

**Comment by lefnire** [comment]
i'm gonna need some info to diagnose, [follow these instructions](http://community.habitrpg.com/content/submitting-bugs) and I'll look into tomorrow or the next

**Comment by lefnire** [comment]
still an issue?

**Comment by wc8** [comment]
yes on beta—correction, I just read the first post more carefully and that’s not exactly what I’m experiencing. I can click and get confirmation message, but on beta, it’s always as if I clicked cancel, nothing deletes. main site works just fine.

**Comment by deilann** [comment]
I'm closing this. If it's still an issue, please reopen.

@wc8 -- are you still experiencing this on beta, or no longer?
