### ISSUE TITLE
Dailies don't refresh daily

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#1548]
97cd6acc-7f56-4066-a0e7-31a1f6b1b2f0
Day start is 8 am, time zone +4

Some days dailies refresh just fine, some days they just stay checked. It isn't related to the unchecked days, I have Saturday and Sunday unchecked, and the last time bug happened was Tuesday. There was no checking in to tavern before that.

**Comment by hjalmberi** [comment]
It happened again, 8 more hours till they can refresh next time if you want to take a look

**Comment by paglias** [comment]
This should be the same as bug #1057
