### ISSUE TITLE
Chat refresh button doesn't seem to work

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#1549]
Whenever I click the refresh button in Tavern or Groups, it doesn't so anything. I can only see new messages when I refresh the whole page or when I post something myself. This could be something with my browser or my extensions, I'm not sure yet. Will do some experiments and let you know if I find any extension-chat-refresh dependencies.

Browser: Chrome
User ID: a5966c55-f839-49c8-8462-5400d2ee4166

**Comment by mczuchnowski** [comment]
Tried in Incognito mode (no extensions) with a party member, still works as described above.

**Comment by mczuchnowski** [comment]
Works the same with incognito mode (no extensions), after clicking the button a few times (Party chat) it even gave me the following error: 401: You don't have access to this group

Console:
Failed to load resource: the server responded with a status of 401 (Unauthorized) https://habitrpg.com/api/v1/groups/9d4f2a42-e34b-48a1-af2e-1c13e834fd02?

**Comment by lefnire** [comment]
great info, that'll give me a clue for when I jump in

**Comment by brightbold** [comment]
I can confirm this problem in Chrome.

**Comment by paglias** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/a56242d1a758ef11fcaa20b5ba2ab50f33a709d2
