### ISSUE TITLE
API calls (made using cURL and otherwise) redirecting to splash.html

### ISSUE THREAD

**Issue by snicker** [HabitRPG/habitica#155]
Whenever I make a call as described in the [API Docs](https://github.com/lefnire/habitrpg/wiki/API) using cURL (or any other method), I get HTTP 302 (Moved temporarily) and redirected to /splash.html. No changes are made to my account. The chrome extension seems to be working just fine, and the address in that code is identical to what I'm using.

Does it have anything to do with authentication or cookies? Headers?

**Comment by snicker** [comment]
Looks like it's a cookie issue, if I snag the value of my 'connect.sid' cookie from Chrome and pass that along with my cURL call, it is successful

**Comment by lefnire** [comment]
this is pretty important, i'm bumping it up.

**Comment by Andrew565** [comment]
I was looking at some of the code for this recently, I'll see if I can nail down the problem.

**Comment by lefnire** [comment]
i realized, you only get this issue if you're not logged into a habit session in the same chrome your'e using the extension. obviously should be fixed, but might be pretty rare

**Comment by snicker** [comment]
well, it also breaks any external API calls, ie, 3rd party apps

**Comment by lefnire** [comment]
Ahhh yes, good call

**Comment by lefnire** [comment]
this is fixed with latest [version of API], which requires `"Content-Type:application/json"` header.
