### ISSUE TITLE
Too big a group

### ISSUE THREAD

**Issue by trueskawka** [HabitRPG/habitica#1551]
Hey.

I can't see my group properly on my 11,6 inch netbook screen in Chrome. No horizontal scrollbar either. 

![habit_team](https://f.cloud.github.com/assets/3491502/1169375/dbd27d68-20b1-11e3-9757-adcb2680adf1.jpg)

**Comment by wc8** [comment]
Original plan was to limit party size. [P.S. I'm not sure the status of that.]

An alternative to scrollbars might be to scale each party member down, but that still will probably run into width limitations eventually.

**Comment by paglias** [comment]
@wc8 that is anyway going to be a problem with small screens and phones. We could add horizontal scrolling but it's so ugly

**Comment by paglias** [comment]
Ideas on that are well accepted

**Comment by wc8** [comment]
How about translucent arrows so you can arrow right or left for more, as appropriate?

**Comment by lefnire** [comment]
will check into bootstrap carousel

**Comment by paglias** [comment]
I've pushed https://github.com/lefnire/habitrpg/commit/332b4bd89949cc927077ff108b2f7fd6d57a40b9 which does the trick showing horizontal scrollbars when needed and will go un-noticed to most users.

@trueskawka can you check on beta.habitrpg.com if it's working fine for you?

**Comment by trueskawka** [comment]
I can't see a difference. We have 10 people in our team and I can see only 8.5.
![habit_team2](https://f.cloud.github.com/assets/3491502/1185820/f488186a-22cb-11e3-9539-ab21a67bee19.jpg)

**Comment by paglias** [comment]
Sorry @trueskawka, it may take a while to arrive on beta.habitrpg.com, don't know exactly how much. Anyway the result will be similar to this: 
![schermata del 2013-09-21 16 29 29](https://f.cloud.github.com/assets/589911/1185832/69e837fc-22cc-11e3-8647-812b669b84c7.png)

Notice the horizontal scrollbar

**Comment by lefnire** [comment]
I haven't yet set up continuous deployment on Heroku, I'll delay the
manually when I get home tonight (EST) and then look into setting up CI

**Comment by paglias** [comment]
Ok, @trueskawka should be in production but since there are some problems actually (http://blog.habitrpg.com/post/61931364067/woah-whats-with-the-site) you can try beta.habitrpg.com .

**Comment by trueskawka** [comment]
Maybe it's a Chrome +  Win7  thing, but it doesn't work...

![image](https://f.cloud.github.com/assets/3491502/1187597/221e12ae-2388-11e3-8202-dd86c6d19cba.png)

**Comment by lefnire** [comment]
I still haven't added CI, I'm working on that now. I _just now_ manually deployed to beta, so give beta a second go. It works on my Mac, but Macs hide scrollbars unless accessed which makes this work perfectly (visually) - I want see what this will look like on Windows, where scrollbars are always present.

Edit: Woops, didn't see @paglias 's screenshot. Ok, merging to master & deploying

**Comment by trueskawka** [comment]
It does the trick.

![image](https://f.cloud.github.com/assets/3491502/1187978/2f653d06-23ac-11e3-8529-e62310587baf.png)

**Comment by lefnire** [comment]
awesome!
