### ISSUE TITLE
"Onlies" (Habits with only a "+" or only a "-") don't reset if clicked more than once

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#1552]
As I understand it, Habits that are dubbed "Onlies" (because they have only a "+" or only a "-") are supposed to reset along with dailies because otherwise rewards would just diminish without going back up (and opposite for negative onlies). 

The bug I am experiencing is thus: when I have clicked one of these (Such as "Worked on HW') more than once a day, it doesn't reset at the day turnover. If I click on it only once during that day, it resets just fine.

**Comment by Nolori** [comment]
For me, it actually depends on how many times you clicked it. So, say you clicked it once, it resets the next day. If you click it more than once, it will reset in about two days. If you click it a bunch, (and it turns, say, blue) it will slowly go back up to green and yellow as the next couple of days pass if you don't click on them.

I'm not sure what the intended function is, but that's how it works for me. Is it not resetting for you at all?

**Comment by lefnire** [comment]
yeah, the algorithms has it slowly fall back to 0 over time. So if you click + once, the next day it theoretically should go back. If you smoked (-) 10 cigarettes in one day, it's not going to hit 0 again for a week or so

**Comment by lefnire** [comment]
actually, as i recall the math:
- scoring is 1pt modified (by weapon, lvl, and task color)
- regression is .2pt 

so even after 1 day for 1pt you probably won't 0-out, will take a little while. We had a math expert do all this, I don't even question it lol

**Comment by derekantrican** [comment]
Ok. Thank you for the clarification. Per this http://goo.gl/GWC4Te I got confused (I thought they were supposed to entirely reset every day). 

"and then to prevent them from becoming too useless or damaging we reset them back to 0 at the beginning of each day."
