### ISSUE TITLE
Next equipment in line doesn't appear until refresh

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1553]
Firefox on Windows 7, uuid 24593eff-c4cc-43e3-950b-51f291a3468b (my test dummy)

Similar to #1020 but worse: if you purchase a new piece of equipment, you get the notification that you've bought a thing, and it appears on your avatar, but the next item to purchase doesn't appear in the shop until you refresh the Tasks page.

Note that my valiant tester here has a wooden shield, but Wooden Shield still appears in the shop:

![screenclip](https://f.cloud.github.com/assets/4501321/1170158/c66a1228-20cb-11e3-92fa-34044254ce22.png)

**Comment by paglias** [comment]
Fixed, the watch expression wasn't working as expected (even tough it was called various times when the app was loaded)
