### ISSUE TITLE
API returning error 401

### ISSUE THREAD

**Issue by NotChrisPlease** [HabitRPG/habitica#1554]
I'm trying to call call the API from https://habitrpg.com/api/v1/user/task/taskname/up, but whenever I do I get HTTP Error 401 in response.

**Comment by paglias** [comment]
Are you sure you used the correct authentication headers? https://github.com/lefnire/habitrpg/wiki/API#full-api

**Comment by paglias** [comment]
I'm almost sure it's wrong authentication, leave a comment if it's something else or it's still happening

**Comment by NotChrisPlease** [comment]
I must be doing something wrong.
It works fine using curl but not with urllib2 in Python.
