### ISSUE TITLE
Popover with html code

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1556]
The group gems popover wasn't showing, now it works but angular-ui-bootstrap doesn't support using html code as popover content, so the result is this:

![schermata del 2013-09-19 19 06 10](https://f.cloud.github.com/assets/589911/1174798/ef81f4c8-214d-11e3-992d-e43b07a1c419.png)

There's an open pull request on angular-ui-bootstrap for this but even if it's merged it's not going to land in a version we can use until we switch to bootstrap 3 https://github.com/angular-ui/bootstrap/pull/641

**Comment by Shaners** [comment]
This may sound stupid... but maybe we can just remove the html for now?

**Comment by lefnire** [comment]
yeah, we can either remove the html or not use angular-ui for the popover. Either would be a pretty quick fix

**Comment by AndreCaseyScott** [comment]
Which branch does beta track? This still seems to be showing up in beta and was merged with develop... :/ 

Also any idea where I would be able to "fake" some gems on the dev install for testing?

**Comment by paglias** [comment]
For faking gems, I personally edited the db directly

**Comment by Shaners** [comment]
I did that as well on local.
