### ISSUE TITLE
Feature request: Unique URL

### ISSUE THREAD

**Issue by castor-troy** [HabitRPG/habitica#156]
How about providing a unique URL instead of logging in everytime. A unique url can help avoid the login screen again and again since I visit the site several times a day.

If security is an issue, you can give an option to the user, whether to allow unique URL...

**Comment by switz** [comment]
If you're using Facebook just visit habitrpg.com/auth/facebook 

You can't login a username/password through a a unique URL. I can't even begin to tell you the security issues with that.

**Comment by lefnire** [comment]
@castor-troy uuid-auth was actually the only way to play habit originally, similar to workflowy - I gotcha, I gotcha. Unfortunately, it is indeed a security vulnerability now that users have been entering a lot of data.
