### ISSUE TITLE
Bogus "Not enough GP" error

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1560]
Firefox on Windows 7, user ID 7f14ed62-5408-4e1b-be83-ada62d504931. Affects both beta.habit and main.

I currently have 1.96 GP, and can't purchase a Reward costing 1 GP:

![screenclip](https://f.cloud.github.com/assets/4501321/1178195/f1a06f42-21a1-11e3-9713-84164e330e1d.png)

**Comment by paglias** [comment]
I can't replicate this on my local install. does it happens for every reward?

**Comment by SabreCat** [comment]
I discovered this morning that it may have been a display issue with my gold total, rather than an error in the "Not enough GP" message. I accrued some 60 silver from a Daily, and I ended up with 1 gold and less than 50 silver in change--suggesting I'd in fact had less than 1 gold when I was trying to purchase that 1-gold reward.

**Comment by damascus1286** [comment]
I just encountered the same problem. I have 60 gold and 96 silver and it won't let me buy the red helm, marked as costing 60 gp.

**Comment by djuretic** [comment]
I think this pull request should be closed, the fix was already merged in habitrpg-shared.
