### ISSUE TITLE
log activities to view later

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1562]
Originally reported by @TheWebTech on HabitRPG/habitrpg-shared#19

---

> Sorry new to GitHub and this is more a request than an issue but I think it's help in debugging.
> 
> There should be a way for the user to see all actions they make. For example:
> 
> User(name) + "completed task:"+task. Name+"." 
> As well as
> User(name) + "purchased reward:"+reward.Name+" for "+cost+"gold."
> Sorry haven't read enough of the code to know your actual variable names.
> 
> This log would hold a list or matrix of the last 25 actions. Older actions get deleted. On mobile this would have it's own tab. Desktop it would be already in a div layer somewhere on the task/habit page.

---

> The graph feature is great, but what I'm thinking of is more along the lines of a general history.
> 
> It would show all actions in plain text separated by a line break.
> Here's a sample of what I'm thinking:
> 
> Thor purchased 2 hours of Netflix for 4 gold.
> Thor took 2 damage from ciggarette.
> Ding! Thor Gained a level!
> Thor completed take out the trash, earning 3 experience and 1 gold 2 silver
> Also having each thing time stamped or date stamped might be good too.
> 
> Later on as the parties and Guild features get developed, this log could serve even more purpose.
> 
> For example, if someone in your guild levels up:
> 
> Ding! Your Guild mate Roxtar91 is now level 23!
> 
> Your Party member PokeUrHauntUs has completed a task.
> 
> Your Party has just begun the _________ Quest.
##

**Comment by phortx** [comment]
+1 Would be really nice since I always forget if I've already clicked on a habit for something I've made some hours ago.

**Comment by wc8** [comment]
I wouldn't mind seeing these reports in my party, but that would have to be a per user option.

**Comment by paglias** [comment]
@wc8 yes, I think it should be private by default and opt-in for parties

**Comment by lemoness** [comment]
This is a feature request, so it should go on Trello instead.
