### ISSUE TITLE
front.jade ReferenceError habitrpgpixel.png

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#1565]
http://pastebin.com/1n8bUBEL  When I run develop, it all loads, but when I go to the localhost:3000, this is what I see.

It's looking for "/bower_components/habitrpg-shared/img/logo/habitrpg_pixel.png" which doesn't exist, but habitrpg_pixel.png does exist in "/public/logo/",  "/public/bower_components/habitrpg-shared/img/logo/",  and also "/node_modules/habitrpg-shared/img/logo/".

**Comment by fragmental** [comment]
Since I seem to be the only one having this problem, I assume I did something wrong?

**Comment by lefnire** [comment]
`npm install && bower install`?

**Comment by fragmental** [comment]
Same.  I'll try this again with a new clone tomorrow.

**Comment by paglias** [comment]
I can't replicate this but anyway there was an error in the code of `getBuildUrl`, fixed in https://github.com/lefnire/habitrpg/commit/4ded02e5dca7c69ecf4726a9f63c006e02c53885

**Comment by fragmental** [comment]
Fixed.  Thanks!  I've had this problem for about a week.
