### ISSUE TITLE
Security certificate (HTTPS) pops up as expired.

### ISSUE THREAD

**Issue by mrmowgli** [HabitRPG/habitica#1566]
Https connections are currently broken (They say untrusted connection) because both Firefox and Chrome say the certificate has expired.  Please renew ASAP! 

> You have asked Firefox to connect securely to habitrpg.com, but we can't confirm that your connection is secure.
> 
> Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified.
> What Should I Do?
> 
> If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue.
> 
> habitrpg.com uses an invalid security certificate. The certificate expired on 09/21/2013 04:59 PM. The current time is 09/21/2013 11:27 PM. (Error code: sec_error_expired_certificate)

Thanks

**Comment by fragmental** [comment]
The certificate has been renewed, but it doesn't show it.  I think it's a problem with the provider of the certificate.  It is safe to ignore the error and proceed to the site.  It should be fixed soon.

**Comment by corylowe** [comment]
Thanks.

**Comment by lefnire** [comment]
SSL cert fixed. Don't know what happened there, so I just deleted the cert & DNS entries, re-uploaded cert & re-created DNS entries. Fixed :/

**Comment by mikefinney** [comment]
Nice job all! :)
