### ISSUE TITLE
Full username appears in party and guild leader messages, rather than display name

### ISSUE THREAD

**Issue by LordGrowl** [HabitRPG/habitica#1571]
My name appears as "LordGrowlTheAwesome" in my party and guild leader messages, rather than my display name of "LordGrowl".

Party leader message:
![24-09-2013 14 55 35](https://f.cloud.github.com/assets/5367204/1200225/5c5bbc1a-2521-11e3-8a0b-4434be215f40.png)

Guild leader message:
![24-09-2013 14 55 45](https://f.cloud.github.com/assets/5367204/1200227/5e2509fc-2521-11e3-949d-4c829105170c.png)

**Comment by paglias** [comment]
Are you still able to replicate this? Always? because I was able but only once than it started working fine

**Comment by LordGrowl** [comment]
Yup:

![29-09-2013 16 11 27](https://f.cloud.github.com/assets/5367204/1233258/9e07989a-2919-11e3-909f-2767e3c2e866.png)

**Comment by paglias** [comment]
I really don't understand:
![schermata del 2013-09-29 17 14 57](https://f.cloud.github.com/assets/589911/1233271/facd4fd4-2919-11e3-8f85-7ae49508cc4d.png)

**Comment by LordGrowl** [comment]
Well I wouldn't post an easy one for you on here, would I?  >=P

Right, I'm using Mozilla Firefox 23.0.1 (latest version) with zero cache. Windows XP Professional SP3, if that helps.  I'll try Google Chrome when I get home from work and see what I get from that for you.

**Comment by paglias** [comment]
It was there then I edited some code to debug it and at some point disappeared, now with the old code the bug disappeared at least on my local install.

For anyone else trying to fix this: the code is ok and it's used correctly elsewhere in the app but sometimes the second argument to the `username` helper is passed as `undefined`

**Comment by deilann** [comment]
Is this still an issue? It doesn't seem to be happening to me.
