### ISSUE TITLE
Habit Task opens up to "Edit Mode" when Page is Opened/Refreshed

### ISSUE THREAD

**Issue by ArcticOokami** [HabitRPG/habitica#1573]
Whenever I get to the Task Page from a link, a certain task in my habits 'opens up' to the 'edit mode'.  Same thing happens if I refresh the page.  Going from 'Options' to 'Tasks' doesn't affect it, though.

I'm using Chrome and the same thing happens in Firefox.

**Comment by paglias** [comment]
This is still happening?
