### ISSUE TITLE
Disappearing lion

### ISSUE THREAD

**Issue by mclois** [HabitRPG/habitica#1576]
Two days ago I got a lion cub egg. All my hatching potions were base, white and dessert, and I already had those lions, so I bought a golden potion and hatched a golden lion. The next day I had no golden lion, and I had a skeleton hatching potion!

Had I seen the skeleton potion the day before I would not bought the golden one, so I am almost sure it was not there, but I cannot be 100% certain. The lion I am completely sure it was there two days ago, I even wore it for a few hours!

Also I think I remember seeing an 52/90 pet count, and know it is at 49/90 ¿¿??

User ID: c7ed829d-ef98-4138-9b34-e57dbe96cefd

**Comment by lefnire** [comment]
will look into this when i can, i'll add some gems to your account to buy back missing pets in the meantime

**Comment by mclois** [comment]
Thank you Tyler!

I am trying to remember to printscreen the stable every time I hatch an egg, so far it has not happened again :/

**Comment by paglias** [comment]
Could be the same (or at least the same source) of #1598, in case it happens again please post a comment there
