### ISSUE TITLE
Wobbly Stable on Hover

### ISSUE THREAD

**Issue by Shaners** [HabitRPG/habitica#1577]
This is kind of cool but I am guessing not an intentional effect?
![wobblystable](https://f.cloud.github.com/assets/2374703/1228915/c5f19bd4-27ad-11e3-9190-1586bf889430.gif)
Happening in chrome but not firefox.

When you hover over an item in the stable it changes how long that line is. Will go back to the original size after mouse exit.

**Comment by Shaners** [comment]
Actually this is really fun!

**Comment by lefnire** [comment]
noted. Ps, how do you make those gifs?

**Comment by Shaners** [comment]
Ideally with a screen capture to video program then video frames to layers in PS but had no admin rights at the time I made this so I just took a bunch of auto screen shots with hot keys while moving my mouse around.

**Comment by paglias** [comment]
yeah this is there since I rewrote the stable.... it's happening only with some pets, so it's probably the image

**Comment by paglias** [comment]
not it's not the image because it also happes hovering the missing-pet icon

**Comment by paglias** [comment]
Ok should be fixed in https://github.com/lefnire/habitrpg/commit/bb8bbe4e0f80003cf41ba4b96ac5817e81313947 (I referenced the wrong issue but it's ok).

**Comment by Shaners** [comment]
Confirmed, no more dancing pets. Maybe we could use some idle animations on hover after a few seconds to spice up this page.
