### ISSUE TITLE
Frozen blue daily

### ISSUE THREAD

**Issue by Ohrange** [HabitRPG/habitica#1578]
![h](https://f.cloud.github.com/assets/5556164/1229718/069ed568-27c0-11e3-9a0f-28f1f7bef5ec.png)
This is on my sister's account. She created the shower daily and within a few minutes it had turned blue and is unable to be completed, edited or deleted. As you can see, there is no tick box.

I'm not sure if it's related but she's also been receiving random huge bouts of points. These are disheartening and there's no easy way to keep track of how many were given so as to revert her account back to where it should be. She has some behavioural difficulties and Habit has been very motivational for her so far (so much less stress for the family) so I would hate it if these bonus points and levels broke the spell for her.

Is it possible for someone to have a look into her account and manually remove the stuck daily?

**Comment by kaenoku** [comment]
I have the same problem

**Comment by Ohrange** [comment]
Kaenoku, are you having the points issues too or just the stuck item?

**Comment by kaenoku** [comment]
Oh sorry, just the stuck item Probably shouldve specified.

**Comment by paglias** [comment]
@Ohrange @kaenoku thanks for the bug report! can you check wheter there are some javascript errors, on chrome you can check pressing CTRL+Shift+J and reporting back what you're seeing

**Comment by kaenoku** [comment]
Umm..I'm not really sure what I'm looking for? This was under the 'console' tab:

Uncaught TypeError: Cannot call method 'appendChild' of null graphics.js:17
AdSenseGraphics.drawSCurveWithCanvas graphics.js:17
(anonymous function) graphics.js:18
(anonymous function) graphics.js:18

Is that what you mean?

**Comment by paglias** [comment]
Yes it was that but sadly there's no clue of an error or something like that. Thanks anyway! Did this happened only with one daily or more?

**Comment by paglias** [comment]
@kaenoku what do happens when you try to delete it? Could you give another shot at the console after having tried to delete the daily? Thanks

**Comment by kaenoku** [comment]
It's just the one daily that's stuck. When i try to delete it, there's the regular popup thing that asks if I want to delete it or not. I click yes and the popup disappears, but the daily is still there.
This is what I get in the console after trying to delete:

TypeError: Cannot call method 'indexOf' of undefined
    at h.a.remove (https://beta.habitrpg.com/app-571bf273.js:15:15425)
    at https://beta.habitrpg.com/app-571bf273.js:5:9036
    at https://beta.habitrpg.com/app-571bf273.js:6:13714
    at h.$eval (https://beta.habitrpg.com/app-571bf273.js:5:16744)
    at h.$apply (https://beta.habitrpg.com/app-571bf273.js:5:16998)
    at HTMLAnchorElement.<anonymous> (https://beta.habitrpg.com/app-571bf273.js:6:13696)
    at HTMLAnchorElement.fb.event.dispatch (https://beta.habitrpg.com/app-571bf273.js:2:17916)
    at HTMLAnchorElement.r.handle (https://beta.habitrpg.com/app-571bf273.js:2:14686) app-571bf273.js:5
Sync: Queue is empty app-571bf273.js:15

**Comment by Ohrange** [comment]
I'm the same, with just the one daily that's stuck.

Here's my console before trying to delete:
Sync: Queue is empty app-571bf273.js:15
3
Uncaught TypeError: Cannot call method 'appendChild' of null graphics.js:17
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. 

And after:
Sync: Queue is empty app-571bf273.js:15
3
Uncaught TypeError: Cannot call method 'appendChild' of null graphics.js:17
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping:1
TypeError: Cannot call method 'indexOf' of undefined
    at h.a.remove (https://habitrpg.com/app-571bf273.js:15:15425)
    at https://habitrpg.com/app-571bf273.js:5:9036
    at https://habitrpg.com/app-571bf273.js:6:13714
    at h.$eval (https://habitrpg.com/app-571bf273.js:5:16744)
    at h.$apply (https://habitrpg.com/app-571bf273.js:5:16998)
    at HTMLAnchorElement.<anonymous> (https://habitrpg.com/app-571bf273.js:6:13696)
    at HTMLAnchorElement.fb.event.dispatch (https://habitrpg.com/app-571bf273.js:2:17916)
    at HTMLAnchorElement.r.handle (https://habitrpg.com/app-571bf273.js:2:14686) app-571bf273.js:5
Sync: Queue is empty app-571bf273.js:15

**Comment by paglias** [comment]
@kaenoku and @Ohrange thanks a lot!

Can you ask you another little help?

When you open the console there are on the top of the panel other tabs, you should switch to the "Resources" tab:

![schermata del 2013-09-30 16 09 29](https://f.cloud.github.com/assets/589911/1237579/c0d07678-29da-11e3-93e6-da48aaa0b6d6.png)

Then on the sidebar on the left expand the "Local Storage" list and select habitrpg.com:

![schermata del 2013-09-30 16 12 42](https://f.cloud.github.com/assets/589911/1237602/2100caac-29db-11e3-84d5-dc128656ee76.png)

It will show some items on the right, you should right-clik and delete all of them (they may be different from mine you can see in the screenshot above but it's ok).

Then don't do anything before having refreshed the page (it will asks you to login again) and tell me if after that the task still can't be deleted.

Thanks!

**Comment by paglias** [comment]
Sorry @kaenoku and @Ohrange a simple logout should be enough :)

**Comment by kaenoku** [comment]
Ok I tried it. Still stuck. :\

**Comment by Ohrange** [comment]
Yup, mine's still stuck after that too.

**Comment by veeeeeee** [comment]
Having a similar issue but with a To Do, not a Daily. Let me know if I should start a new ticket instead.
![duped and stuck to do](https://f.cloud.github.com/assets/5608909/1425092/53e1c346-402d-11e3-94c3-3e1830618dae.png)

**Comment by Ohrange** [comment]
New development... After letting the character die the daily turned into a 'habit'. Neither + or - button did anything when pressed but the item was able to be deleted and now seems to be gone.

![image](https://f.cloud.github.com/assets/5556164/1506296/f7537668-491b-11e3-8f9b-25bc0045a775.png)

**Comment by deilann** [comment]
Is this still being experienced? If this is still a problem, please reopen/comment.

**Comment by lefnire** [comment]
@deilann I don't think anything was done to fix this issue. I'm not sure we want to close tickets that are old, unless they predate some architectural overhaul (derby=>angular, apiv2, etc)

**Comment by kaenoku** [comment]
Hey just wanted to say that this problem is fixed for me. I'm not sure what happened but when I went to get rid of it again, it got deleted like normal.
