### ISSUE TITLE
Problem with Guild Gems mouse-over window

### ISSUE THREAD

**Issue by Nostos** [HabitRPG/habitica#1579]
Hello.

This is definitely not a big problem, but I'll write it anyway (it doesn't seem to be in the issues list).

There seems to be an error in the Group page. When you move the mouse over the "Guild gems" picture, a small window appears with the following text:

"Guild Bank
Gems which your Guild leader can use for prizes in the upcoming <*a target=_blank href="https://trello.com/card/challenges-individual-party-guild-public/50e5d3684fe3a7266b0036d6/58">Challenges</a> feature."

[I had to add an asterisk before the "A" tag because the Preview interpreted it in the correct way, whereas the small mouse-over window actually showed the HTML code]

Nostos

**Comment by paglias** [comment]
Thanks for reporting, I'm closing this because it's already reported as #1556
