### ISSUE TITLE
Daily streaks not giving achievement.

### ISSUE THREAD

**Issue by GuyDudeman** [HabitRPG/habitica#1581]
This may be due to the transition between websites (I started a day or two before the transition) but I have 1 daily with a 23 streak, 1 with a 22 streak, and 1 with a 21 streak, I think I did restore streak on the 21 day one, but the other two I got over a period of 21+ days. The achievement page still claims that I have 0 21-day streaks on Dailies.

**Comment by Shaners** [comment]
Same as #1540, can follow up there if you'd like.
