### ISSUE TITLE
Drops and the late game

### ISSUE THREAD

**Issue by jepler** [HabitRPG/habitica#1585]
I know that according to issue #1048, the drop system is considered to be working as designed, but I still feel that something needs to be done about egg and hatching potion drops for the late / "end" game.

I wrote my own Python simulator of the drop system at https://gist.github.com/jepler/6763003 which runs until the necessary 90 eggs and 90 potions were dropped to give a user the ability to hatch all the animals.  I came to the following conclusions based on 1000 runs-to-full-stable:
- 50% of the time, the number of drops needed was at least 979 (so even if you consistently get two drops a day, it's still 2.6+ years to have a 50/50 change to fill your stable)
- 5% of the time, in excess of 1600 drops were required, over 4 years playing at 2 drops per day(!)
- 50% of the time, the greatest number of excess (unhatchable) eggs of some type was at least 57
- 50% of the time, the greatest number of excess (unpourable) potions of some type was at least 101
- 50% of the time, the total number of unusable drops is at least 799
- 5% of the time, the total number of unusable drops exceeded 1500

Without something to do with currently unusable drops, the late-game user will have the experience of a bursting but useless inventory.

**Comment by wc8** [comment]
Closing, follow up on the Pets Suggestion thread.
