### ISSUE TITLE
iPhone App login using API token generates "We're Offline" error

### ISSUE THREAD

**Issue by CharlesLove** [HabitRPG/habitica#1586]
I'm not sure if this also happens with regular accounts, but I created my account using Facebook on the main site. When I try to login using the user id and api id, a "We're Offline" message appears at the top. I can not login, but if I shut down the app and re-run it a generic account is shown and I can access the default lists of things. Probably another bug.

Running iPhone 4, 7.0.2

**Comment by ghost** [comment]
I have the same problem. Can't get Habit to run on my iPhone at all. Always says offline.

**Comment by lefnire** [comment]
This will be something going wrong with the API then. Both of you, give me your UUIDs and I'll take a look at this the moment I can.

**Comment by CharlesLove** [comment]
Here you go: b1d3d145-fc41-4e0c-8d9f-5cc8a06aae5c

**Comment by ghost** [comment]
2af019ec-90ec-431f-8cc8-3e6bb81e01ff

On Sun, Oct 6, 2013 at 5:15 PM, CharlesLove notifications@github.comwrote:

> Here you go: b1d3d145-fc41-4e0c-8d9f-5cc8a06aae5c
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1586#issuecomment-25776954
> .

## 

Author of _Ashfall_ and _Ashen Winter_.
www.mikemullinauthor.com

**Comment by hannawolf** [comment]
I've got this problem as well...  UUID is:

1622652b-fd9d-4ad3-94a7-833bbffe984c

**Comment by paglias** [comment]
I tried on android and it works, does it happens only with facebook accounts?

**Comment by hannawolf** [comment]
I think it's a problem only with facebook accounts, but I have an iPhone, so I don't know if that contributes to the problem...  Has anyone gotten this issue resolved yet?  I'm still appless :-(

**Comment by ghost** [comment]
I ditched my iPhone (I hated it!) and bought an Android phone. Everything
works fine now.

On Sat, Oct 26, 2013 at 4:21 PM, hannawolf notifications@github.com wrote:

> I think it's a problem only with facebook accounts, but I have an iPhone,
> so I don't know if that contributes to the problem...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1586#issuecomment-27154852
> .

## 

Author of _Ashfall_ and _Ashen Winter_.
www.mikemullinauthor.com

**Comment by paglias** [comment]
It also happens on android phone, it seems, see HabitRPG/habitrpg-mobile#150

**Comment by paglias** [comment]
I tried with a facebook account and at least for me it worked

**Comment by deilann** [comment]
Are we still seeing this? If so, please reopen.
