### ISSUE TITLE
"Locked" Tasks

### ISSUE THREAD

**Issue by Gaelan** [HabitRPG/habitica#1587]
It would be nice to have a flag on tasks that disables checking (or clicking in the case of habits) it from the UI, and only allowing changes from the API. This might ruin the idea of a paid tier though.

**Comment by paglias** [comment]
Hi, can you explain this a little more? I can't understand the purpose

**Comment by Gaelan** [comment]
@paglias If I use the API to create a task based on a todo item from some other site, it would be useful to prevent checking it from the HabitRPG GUI and only allow checking it via the other site.

**Comment by paglias** [comment]
ok understood!

**Comment by wc8** [comment]
Vote here, [API-✓-only Locked Tasks](https://trello.com/c/XNlBV7Qa), especially @Gaelan
