### ISSUE TITLE
[Feature] "Time Attack Mode" for urgent Todos

### ISSUE THREAD

**Issue by benmanley** [HabitRPG/habitica#159]
There may be circumstances where you want to give yourself extra, short-term motivation to complete a Todo (e.g. an external deadline, or even just for fun).

One solution would be to put a Todo into "time attack mode" (limit break / power up / special move / magic or whatever).

In this mode, you specify a time limit within which to complete the Todo. There should be a maximum time limit (24hrs?) to emphasise the time pressure and so that it doesn't interfere too much with the existing rewards system.

If you complete the task within the time limit, you get an additional reward. If not, you are penalised.

A given amount of time must then elapse before you can reactivate time attack mode. This means that you must be selective as you can't apply it to every Todo and that, if you fail, you can't simply switch time attack mode straight back on.

[Ranking tasks (#105) and manually adding value/importance (#53) have been suggested already, but I think they go against the simplicity of the existing system whereby tasks gain value the longer they are left uncompleted.]

**Comment by wc8** [comment]
Someone else posted similar idea as [Russian] Roulette #69 
I prefer "Timed Attack"—terminology, at least.

**Comment by benmanley** [comment]
I suppose the biggest difference is that #69 suggests you are presented with a habit at random. My idea is that the user is in control of when and how to use a time attack and can use it strategically to give themselves an extra kick!

**Comment by wc8** [comment]
Oh, I overlooked/forgot the random element. I prefer the user control! The only time I'd want something random would be if I was at a loss where to start, but in general, I'd want to pick my battles. 

IMO, I think priority addresses a different issue and I see value in both options. 
- I like the Timed Attack for those times when, as you put it, one needs "an extra kick" or motivation to be efficient. 
- Priority addresses equal reward for tasks unequal in effort and/or value. If a list has five tasks that are worth more to you than the rest of the tasks in the same list (habit/daily/todo), you wouldn't necessarily want to make all five into a timed attack.

**Comment by hookang** [comment]
Good ideas. Added to Master list of Features #169. Issue closed for organization.

**Comment by wc8** [comment]
@benmanley Does [Scheduled Task Attack](https://trello.com/c/vPuLG1G0) fit your idea? If not, please reply back.

**Comment by benmanley** [comment]
@wc8 Thanks for checking back with me. I've been meaning to be more active on the boards, but have been tied up with other projects. Maybe I need to go into "Time Attack Mode" ;-)

I think this is a different idea to "Scheduled Task Attack".

The way I imagine it is that for any To-do, regardless of deadline, you can invoke Time Attack Mode. If you succeed, your reward is multiplied. If you fail, you are penalised in a similar way to a Daily. 

So, you could use it for a non-urgent, mundane task if you wanted, or even use it during a Scheduled Task Attack. The effect is simply to temporarily raise the stakes of whatever you're doing. Then, there is a cooling off period before you can use it again.

To me, it's a non-complex way of firing you up to complete a To-do without interfering with the natural prioritising that is at the core of HabitRPG.

**Comment by wc8** [comment]
Thanks for the explanation. In some ways, it seems similar to the [Heat Up Spell](https://trello.com/c/OsmmLDqw) suggestion:

> Increases the XP multiplier of any task by 0.05, consuming 5 Energy.
> If used on daily tasks, also increases the HP loss of undone tasks.

Your idea would apply to todos and add a time limit for completion (eg. 24 hrs), an HP penalty for failure, and a cooling off period. Is that right?

**Comment by benmanley** [comment]
Yeah. That sounds about right. 

Like you say, it does have some similarities with the Heat Up Spell idea. I'm imagining, though, that your Time Attack Bar would be available to you at all times, rather than being something you buy, "learn" or unlock. And the cooling off period would replace the need to "spend" energy.

The length of the cooling off period could relate inversely to the time limit for completion, or be fixed at a certain duration. So, a one hour time attack would have a higher multiplier for XP gain and HP loss and a longer cooling off period than, say, a 24 hour time attack. Or you might simply limit it to, say, one use in any 24 hour period.

[On a spell-related side note, maybe you could use spells/potions to temporarily shorten the cooling off period or super-charge your time attack multipliers.]

**Comment by wc8** [comment]
It's been added to Trello, follow the link to vote or comment: [Attack Task mode](https://trello.com/c/D2RQ1Poe)
