### ISSUE TITLE
Accidentally made a load of blank task via the API

### ISSUE THREAD

**Issue by Mr-Margaret-Scratcher** [HabitRPG/habitica#1594]
Was experimenting with the API via as3 and I've accidentally made a lload of blank task, which I can't edit or delete..

**Comment by djuretic** [comment]
Do you mean that you cannot delete them via the API, or you can't delete them from the website?

**Comment by paglias** [comment]
What do you mean by blank? We should avoid the possibility to create
such tasks if they do create problems

2013/10/6, djuretic notifications@github.com:

> Do you mean that you cannot delete them via the API, or you can't delete
> them from the website?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lefnire/habitrpg/issues/1594#issuecomment-25768711

## 

Matteo Pagliazzi - paglias.net

**Comment by philadams-zz** [comment]
I did similar things when trying to up/down a habit... if you send along basically any string as the task id (/:id/up for example), then it just assumes you're trying to create a new task. So I made several new tasks before realizing this was happening.

**Comment by paglias** [comment]
Mmm... yes that is the current behavior when making a POST to '/user/task/:id/:direction' and the task doesn't exist, but at it should let you delete/edit the tasks as normal. Is this (not being able to edit or delete) happening only to @Mr-Margaret-Scratcher or also to @philadams ? In case, could you post the uuid of the account you created tasks on?

**Comment by philadams-zz** [comment]
I was able to delete them via the web interface; I did not try to delete them via the API but have no reason to believe that wouldn't also work.

**Comment by deilann** [comment]
Please reopen/comment if this is still an issue. It seems it is intended behavior and they can be deleted?
