### ISSUE TITLE
Unresponsive Script

### ISSUE THREAD

**Issue by PSmitty1990** [HabitRPG/habitica#1596]
059c8b85-8b8f-4223-b5a7-d50e23b0df28

I am using Firefox, and I often use private browsing to use the site.

Sometimes when habitRPG is loading an action, usually after giving rewards for completing my goals ( +5 exp, etc), I get the following error message:

"A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: https://habitrpg.com/app-571bf273.js:14"

This has been happening multiple times per day.

**Comment by paglias** [comment]
Do you have a big number of items (habits, todos, dailys...)?
Il 06/ott/2013 20:43 "PSmitty1990" notifications@github.com ha scritto:

**Comment by PSmitty1990** [comment]
I have 12 Habits, 8 Dailies, and 31 Todo's. I am really behind on those.

On Sun, Oct 6, 2013 at 3:04 PM, Matteo Pagliazzi
notifications@github.comwrote:

> Do you have a big number of items (habits, todos, dailys...)?
> Il 06/ott/2013 20:43 "PSmitty1990" notifications@github.com ha scritto:
> 
> > 059c8b85-8b8f-4223-b5a7-d50e23b0df28
> > 
> > I am using Firefox, and I often use private browsing to use the site.
> > 
> > Sometimes when habitRPG is loading an action, usually after giving
> > rewards
> > for completing my goals ( +5 exp, etc), I get the following error
> > message:
> > 
> > "A script on this page may be busy, or it may have stopped responding.
> > You
> > can stop the script now, or you can continue to see if the script will
> > complete.
> > 
> > Script: https://habitrpg.com/app-571bf273.js:14"
> > 
> > This has been happening multiple times per day.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lefnire/habitrpg/issues/1596>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1596#issuecomment-25777875
> .

## 

Sincerely,

   Pierre Alexander Smith

**Comment by lefnire** [comment]
Check todos > completed (bottom tab), make sure it's cleared

**Comment by PSmitty1990** [comment]
Oh wow. There was a lot in there. Thank you!

On Sun, Oct 6, 2013 at 11:40 PM, Tyler Renelle notifications@github.comwrote:

> Check todos > completed (bottom tab), make sure it's cleared
> On Oct 6, 2013 11:22 PM, "PSmitty1990" notifications@github.com wrote:
> 
> > I have 12 Habits, 8 Dailies, and 31 Todo's. I am really behind on those.
> > 
> > On Sun, Oct 6, 2013 at 3:04 PM, Matteo Pagliazzi
> > notifications@github.comwrote:
> > 
> > > Do you have a big number of items (habits, todos, dailys...)?
> > > Il 06/ott/2013 20:43 "PSmitty1990" notifications@github.com ha
> > > scritto:
> > > 
> > > > 059c8b85-8b8f-4223-b5a7-d50e23b0df28
> > > > 
> > > > I am using Firefox, and I often use private browsing to use the
> > > > site.
> > > > 
> > > > Sometimes when habitRPG is loading an action, usually after giving
> > > > rewards
> > > > for completing my goals ( +5 exp, etc), I get the following error
> > > > message:
> > > > 
> > > > "A script on this page may be busy, or it may have stopped
> > > > responding.
> > > > You
> > > > can stop the script now, or you can continue to see if the script
> > > > will
> > > > complete.
> > > > 
> > > > Script: https://habitrpg.com/app-571bf273.js:14"
> > > > 
> > > > This has been happening multiple times per day.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/lefnire/habitrpg/issues/1596>
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lefnire/habitrpg/issues/1596#issuecomment-25777875>
> > > .
> > 
> > ## 
> > 
> > Sincerely,
> > 
> > Pierre Alexander Smith
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lefnire/habitrpg/issues/1596#issuecomment-25787158>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1596#issuecomment-25787668
> .

## 

Sincerely,

   Pierre Alexander Smith

**Comment by ghost** [comment]
Hi I just got the same script but this was on the guild page.
I use firefox as well.
I cleared the completed tasks and tried again but whenever I try to load guilds I would get this
Script: https://habitrpg.com/app-571bf273.js:5
I joined 4 guilds at the same time so I am assuming that is the issue. After clicking continue script three times I got through. 
I will quit a few guilds to avoid this issue but just a heads up.

**Comment by brightbold** [comment]
I can confirm this happens in Firefox but not Chrome or Safari. Good to know about clearing completed To Dos - I'll try that next time.

**Comment by paglias** [comment]
Closing this, pleas follow up at #1499
