### ISSUE TITLE
Egg/Potion Duplication

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1598]
I hatched a pink cotton candy wolf today. It said that it was successful, and both the egg and the potion disappeared. However, when I went to the Stable, I didn't see my pink wolf, so I refreshed the page. Sure enough, there was the wolf - but when I went back to my inventory, the pink potion and the wolf egg had reappeared. When I tried to hatch another pink wolf, it told me I already had that pet.

Probably an important bug to fix, or people will be able to game the pet system pretty quickly, which is bad for motivation :(

**Comment by Shaners** [comment]
I think the reappeared egg and potion will disappear but I am not 100% sure of that. Are they still there now?

**Comment by lemoness** [comment]
Nope, they're gone - but I think while they are there, you are still able to hatch pets with them.

**Comment by paglias** [comment]
That is quite strange I admit, It might be that Angular is taking a while to update every change but everything should be ok when refreshing, at least the website is using the old user copy stored in localstorage.

@lemoness yes, while they are there you are still able to hatch pets

**Comment by fragmental** [comment]
Same happened here.

**Comment by jayweiler** [comment]
Same happened to me. I was even able to buy another egg and hatch another pet with the same potion. Then the potion and 2nd egg disappeared but so far I still have the 1st egg and both pets.

Update: Navigating away from the page clears the inventory.

**Comment by deilann** [comment]
What's up with this?

**Comment by lemoness** [comment]
I believe this was related to loading times and server issues.

**Comment by deilann** [comment]
kk gonna close it
