### ISSUE TITLE
Feature Request:  Ability to see why you have lost HP (history of HP loss)

### ISSUE THREAD

**Issue by ctuirmt00** [HabitRPG/habitica#160]
Sometimes I lose HP and I am not sure what the reason is.  I mean, I know it's because I haven't done my tasks, but I'm not sure sometimes if it's from the browser extension or the tasks, etc.

It would be nice to see a little history.

**Comment by mgatten** [comment]
Amen! +1

**Comment by hookang** [comment]
Good idea. Added to Master list of Features #169. Issue closed for organization.

**Comment by wc8** [comment]
[Progress Views & Options](https://trello.com/c/h0pezwDR)
