### ISSUE TITLE
Lost account

### ISSUE THREAD

**Issue by Sassifrass** [HabitRPG/habitica#1602]
I took a break from using the site for a while, but when I tried to sign in with my old credentials, it said I didn't have an account.
I still have the Chrome Extension active with my old info.

Is there anyway to recover my old account?
UUID: cb62ac15-1faf-461d-9014-062a122ec8d2

**Comment by paglias** [comment]
Have you tried recovering your password or does it says that you're email is not registered?

**Comment by Sassifrass** [comment]
It told me my email wasn't registered.
I signed up for a new account with my email saunatina@gmail.com, but I
would like to recover the old account if possible.

S.

2013/10/14 Matteo Pagliazzi notifications@github.com

**Comment by lefnire** [comment]
The mail for the provided UUID was **s.sassifrass@gmail.com**, uname **Sassifras**. looks well and good in the database - wanna try that log instead?

**Comment by Sassifrass** [comment]
Thanks for responding.
All my email addresses are forwarded to my main address and I couldn't find
anything from Habit RPG in the search to know I used an alt.

Everything looks good.

S.

2013/10/14 Tyler Renelle notifications@github.com

**Comment by paglias** [comment]
Good! Closing this issue then
