### ISSUE TITLE
PUT request to complete a todo task does not yield XP/GP

### ISSUE THREAD

**Issue by philadams-zz** [HabitRPG/habitica#1603]
In the web interface, marking a todo as 'complete' gives you XP and GP. But via the API, this does not appear to happen (a PUT to user/task/:id). The todo is marked 'complete', it disappears from the web view, but no XP/GP are given.

This is in contrast to the habits up/down where you ARE awarded XP/GP for up and lose HP for down.

**Comment by paglias** [comment]
A PUT to user/task/:id shouldn't be used to mark a todo as complete but only to edit its title, note... instead there's POST /user/tasks/:id/:direction that should be used passifn the task id and in case of a todo direction: up to mark it complete and direction: down to mark it incomplete.

It's documented here https://github.com/HabitRPG/habitrpg/wiki/API

**Comment by philadams-zz** [comment]
Understood - thank you. This matches RESTful verbs; I just wasn't getting that the same action (e.g. POST :id/up) on different types of resources would do different things (mark as complete vs indicate 'up' as with a habit).
