### ISSUE TITLE
silver coins rewarded without any task completed

### ISSUE THREAD

**Issue by dyg321** [HabitRPG/habitica#1604]
I created a daily task, i marked it as completed, i rewarded 99 silver coins, but i realized that i did not complete the task so i unmarked it, then i lost 98 silver coins, after all i have 1 silver coin without any work.
i can repeat the process any times i want, and my silver coins will increase more and more.

i think this cannot be. am i wrong?  is it a bug or this is the way it should be?
thanks.

**Comment by wc8** [comment]
Looks like #286 and #423 persist. 
It's a bug, but a minor one (no major harm done, unless the user chooses to abuse it).
