### ISSUE TITLE
Did not lose HP overnight

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#1607]
Display name: Cindy  
UserID# 2b44124d-f9bc-49a9-bc97-26e5b3cd099c

Use Windows system 7 Professional on office computer, Andriod 4.1.1 on phone, and Windows Vista or Home on home computer. Using chrome on both computers. version Version 30.0.1599.69 m at office. Probably same one at home. The mobile app on the phone.

I didn't lose hp last night. I mentioned yesterday that I was advanced to a new level and I am still at 50 hp today. All three locations show same information. 

Yesterdays comment in Tavern: 
I am a level higher. I am almost certain I didn't do any jobs between the office and home. Earlier today I had 200 points left for next level when I checked off lumosity's daily at the office. I also bought a potion since I was at 33 health points and the likelihood of me actually doing a red tonight was about zilch. I now have 2/640 instead of 300 or 400/620. 20 hours ago
and Lumosity's daily was back to being unchecked. (on home computer. checked off at office)

Hope I did this correctly, if you need anything else let me know. 

![2013-10-09_1517_no_hp_loss](https://f.cloud.github.com/assets/5649804/1300797/c63be0fe-3117-11e3-8a88-2d50ab57d125.png)

I did have a couple yellow habits (probably 3-4). Maybe only 1 Daily that also was yellow.

**Comment by lefnire** [comment]
were the dailies still checked? is it the same issue as https://github.com/HabitRPG/habitrpg/issues/1057 ?

**Comment by clmmerrill** [comment]
No not same as #1057, all the checked things from night before were
unchecked and ready for the new day.

I only had a 3-4 couple yellow habits. Nothing red. Maybe 1 yellow daily. I
just thought I should have lost 1-5 hp like I do every night.  Just an
anamoly that surprised me and I wasn't sure if I was supposed to mention
it. It hasn't happened since.

On Wed, Oct 16, 2013 at 9:17 PM, Tyler Renelle notifications@github.comwrote:

> were the dailies still checked? is it the same issue as #1057https://github.com/HabitRPG/habitrpg/issues/1057?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1607#issuecomment-26472662
> .

## 

Cindy M Merrill
clmmerrill@gmail.com

**Comment by paglias** [comment]
will reopen If it happens again
