### ISSUE TITLE
The current state of Habit

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#161]
Hey guys, I hope you all know I'm not ignoring any of the feature requests. Skimming them presently and plan to give them proper love once the critical bugs and server stabilization is complete. I'm super pumped that everyone has so many feature ideas, this is fun! 

The notorious #80 has been mostly fixed. All data-loss has been due to the server crashing for one reason or another, and the socket.io connection not being properly re-esablished (see this [explaination](https://github.com/lefnire/habitrpg/issues/118#issuecomment-12500363) for more deets & a workaround). #80 was the primary culprit, now I'm diagnosing some other MongoDB fringe issues that still, from time-to-time, cause the timeout.

Ok, so now I'm working on 
- Casper testing #122 to help diagnose many of these issues. 
- Then I'll be preening the database, it's quite large (we had some gnarly traffic from Lifehacker, Reddit, Kotaku!) - and that might have something to do with the bundling timeout.
- Then test all the criticals
- Next, I want to get translations #62 underway so the translators can start doing that in the background.

Anyway, thanks for hanging in there everyone! I know it's been super frustrating with all these bugs, and you're all awesome for not being pissed

**Comment by hookang** [comment]
Translations added to Master list of Features #169.

**Comment by StanLindsey** [comment]
Simply having you posting, being open and explaining the issues is a fantastic turn of faith, everybody can obviously look at your profile to see your additions but coming on and explaining is great.

**Comment by lefnire** [comment]
Thanks @SlappyBag, that is absolutely good to hear!

**Comment by lefnire** [comment]
#165 (memory leak) is the new main critical issue crashing the server, now that #80 is fixed

**Comment by lefnire** [comment]
i'll start blogging here: http://habitrpg.tumblr.com/
