### ISSUE TITLE
Items lost when changing computers

### ISSUE THREAD

**Issue by MinatureCookie** [HabitRPG/habitica#1610]
Congratulations, level 4! Here's a bear cub egg.
Reopen browser on different PC
Congratulations, level 4! Here's a tiger egg.
Bye bye bear cub egg.

**Comment by Shaners** [comment]
Similar to #1561

**Comment by MinatureCookie** [comment]
Almost exactly the same, in fact. My changing of PCs may have been irrelevant, then. Sorry I didn't notice the other issue thread.
Closing as a duplicate of #1561
