### ISSUE TITLE
Can't seem to register

### ISSUE THREAD

**Issue by s-boardman** [HabitRPG/habitica#1613]
Hi,

I've been trying to register with username/email/password but the interface hangs and doesn't seem to act whenever I click on the "Register" button after inputting these details.

![regscreen](https://f.cloud.github.com/assets/3591844/1320739/9569d0d0-3374-11e3-94af-f368a733316a.PNG)

I can't get past this screen...

**Comment by paglias** [comment]
Hi @s-boardman !

The whole interface hangs after clicking the Register button or simply nothing happens?

Could you open the console (Ctrl+Shift+J on Chrome) and see if after clicking the button some error appears there?

Thanks!

**Comment by s-boardman** [comment]
Hi @paglias 

Well I tried again today and the screen flashes but doesn't move past the page with registration options. It doesn't obviously reload either.

There is a ping1 error, but that appears to be fairly benign?
"Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping:1"

Thanks :)

**Comment by paglias** [comment]
Yes that error is totally benign...

Which browser are you using?

**Comment by s-boardman** [comment]
I'm on chrome, latest version. Have disabled all the obvious extensions (ad
block, flash control).

It's very odd, seems to be exclusive to habit rpg :-(

**Comment by paglias** [comment]
@s-boardman have you managed to sign up, in the meanwhile I tried, using chrome, and couldn't reproduce this issue in any way. Could you try registering from the phone/another pc?

**Comment by s-boardman** [comment]
@paglias It seems to have fixed itself successfully! Thanks for the help. Now I can finally get started with it. :)
