### ISSUE TITLE
Lost Veteran Wolf pet

### ISSUE THREAD

**Issue by Otocinclus** [HabitRPG/habitica#1614]
What browser you're using: iPhone, Safari.
Your User ID: dfa5d988-992a-4dec-8183-c15c8adb041f
No errors occurred

I had the veteran wolf pet that was given out a while ago, and had him equipped. I changed him out for a fox maybe a few weeks ago and I don't know when it happened that he disappeared, but now he is gone. He does not show up under the "Rare" pet category in my Stable.

**Comment by lefnire** [comment]
how very strange, he's showing up in your database entry. Is this consistent across refreshes?

**Comment by lefnire** [comment]
oh, you said iPhone / Safari - is this the mobile app? I'm not sure if he's been added to the mobile app yet

**Comment by paglias** [comment]
@lefnire me too, I think the last commit you pushed to develop cause this, it may be my own https://github.com/lefnire/habitrpg/commit/bb8bbe4e0f80003cf41ba4b96ac5817e81313947

**Comment by paglias** [comment]
Fixed in https://github.com/lefnire/habitrpg/commit/c3086c61949dfd224ac5f0b727dc8e6d759d4348

**Comment by Otocinclus** [comment]
I use the iphone app on my phone, and I use safari on my computer.
It is consistent across refreshes that he is not there.
Is the fix that paglias is talking about an upcoming thing or should I be seeing him now?

**Comment by paglias** [comment]
@Otocinclus no it's fixed but still not on the website

**Comment by Otocinclus** [comment]
@paglias - Okay, cool :) Thanks for the really quick attention, wow!

**Comment by lefnire** [comment]
thanks @paglias!

**Comment by lefnire** [comment]
pushed, give that a shot

**Comment by Otocinclus** [comment]
There he is! Thank you @lefnire and @paglias !
