### ISSUE TITLE
[Feature] Combat log with the history of all your actions visible by user

### ISSUE THREAD

**Issue by Zequez** [HabitRPG/habitica#162]
It seems that the application already have a history on the database. So it would be nice if the user could see it on a log.

What do you think?

**Comment by wc8** [comment]
:+1: I like this idea, visible cues for habit accomplishment (maybe a progress bar issue?) would help accurate habit tracking (did I click that yet?) and also be motivational. 
That said, I think this is part of #6
Update: see also #55

**Comment by hookang** [comment]
Added to Master Feature Request List #169 and closed.

**Comment by Andrew565** [comment]
Here's a possible option for displaying these nicely: [TimelineJS](http://timeline.verite.co/).

**Comment by hookang** [comment]
Love the timeline. Hope it gets implemented

**Comment by wc8** [comment]
Trello: [Combat Log](https://trello.com/c/h0pezwDR)
