### ISSUE TITLE
2 accounts with same email?

### ISSUE THREAD

**Issue by EarnWings** [HabitRPG/habitica#1620]
I was booted from the software/site and when I attempted to log back in, the system did not recognize my username/password, so I submitted my email to reset it.

It sent me an email with a new password, and when I logged in, I am back a level 1 with old habits/dailies/etc. 

I was on level 15 or so and finally getting used to the "right way" to set things up, so I'm a little concerned.

Username I received back was ahartley, but I think my "good" account has a username of "earnwings"

I have the app on my iPhone, which has a User Id and an API token for the "good" account, if that would help figure out the issue.  I'd really like to get my "good" account back, if possible.

Thanks!

**Comment by paglias** [comment]
Could you report the user id you have on the iPhone app?

**Comment by lefnire** [comment]
When did you first register? You sure you didn't use Facebook login
originally? Do you have a very specific (capitalization included) task
title that was on our list? Like "Call Jared" or something

On Fri, Oct 18, 2013 at 12:25 PM, Matteo Pagliazzi <notifications@github.com

**Comment by EarnWings** [comment]
Yeah - wasn't sure if it was recommended to enter the userId on this forum:

UserId on iPhone: ea043a45-1916-43bb-83ba-32275

Tailwinds,
Andrew C. Hartley
Certificated Flight Instructor
http://www.smartflighttraining.com

**Comment by EarnWings** [comment]
I don't think I used the Facebook registration at all, thought I could be
wrong.

I just gave my iPhone UserId.

One of my Dailies is "Check Weather & NOTAMS" (ought to be pretty specific,
if that helps find the account)

Tailwinds,
Andrew C. Hartley
Certificated Flight Instructor
http://www.smartflighttraining.com

**Comment by lefnire** [comment]
You did indeed use Facebook, I found the account, the id is `ea043a45-1916-43bb-83ba-32275ba30c55` (one you gave us got truncated), but I was able to use your specific Daily - thanks for that one!

Yeah, just login with facebook on the website and you should be gold.

**Comment by EarnWings** [comment]
Okay - I'll give that a shot... thanks!

Tailwinds,
Andrew C. Hartley
Certificated Flight Instructor
http://www.smartflighttraining.com
