### ISSUE TITLE
Progress graphs look very different, sometimes mangled

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1623]
Some graphs among my Dailies look like straightforward line graphs, others like step graphs. (Has to do with the days they're active, I think.) That's less concerning than the fact that the date labels on the horizontal axis get mangled at times:

![screenclip](https://f.cloud.github.com/assets/4501321/1367488/17b70b1c-3932-11e3-867e-c4cb1a630a4a.png)

Firefox on Windows 7, user ID 7f14ed62-5408-4e1b-be83-ada62d504931 . No JS errors logged.

**Comment by lefnire** [comment]
I kinda slopped it together to get something working (since people were requesting). In case someone gets to this before me, another issue is that the graph has a manually-set width since it's not detecting the wrapping div's width for some reason

**Comment by paglias** [comment]
@lefnire we can set it to the column width with jquery, it won't adapt when window is resized but it's not a big deal.

The only thing is that it's really to small on some screens like my 1366x768 where the column width is 251px.

Actually it looks like this:

![selezione_005](https://f.cloud.github.com/assets/589911/1398952/99776fe2-3cad-11e3-81d5-b33409b3f8b6.png)

Adapting it to the column width:

![selezione_002](https://f.cloud.github.com/assets/589911/1398950/95fa81a6-3cad-11e3-9455-ac7d7888dfcf.png)

And in both cases it isn't easily readable, I believe it's going to be un.readable also on bigger screens when the history is longer

**Comment by lefnire** [comment]
I wonder why it was working in Derby version (it made the dates readable), we haven't modified the Google Charts code any in porting. Ah well. Is your first image without the jquery? That's not too bad actually, IMO, having he score  legend outside the task. Should we roll with that?

**Comment by paglias** [comment]
The score is outside the column because for some reason the graph doesn't start from the left but after or in the middle of the coloured vertical strip. Probably with some css hack I can make it showing the values on the y axis on the couloured strip like in my last screenshot.

Also some graphs have dates shown oblique, and they usually are wel readable while in some cases the dates are horizontal and they overlap each other..

**Comment by MaddieM4** [comment]
@lefnire I used to have this issue on some items back in the Derby days. Not so sure this is actually new.

**Comment by lefnire** [comment]
It's a something with google charts. Can't remember if it was a variable I passed in to fix the original issue, or if it was an `style="width:.."` bit. I'll take another pass at it soon, but if anyone wants to tinker with it before I get there, check out the [line charts](https://developers.google.com/chart/interactive/docs/gallery/linechart) api

**Comment by SyntaxPickax** [comment]
I've got some issues with the progress charts as well. I appear to missing data from tasks. For example:
![screen shot 2014-01-07 at 2 53 35 pm](https://f.cloud.github.com/assets/1245093/1864177/c9e49296-77ee-11e3-8bbe-1db2c72ab08c.png)
![screen shot 2014-01-07 at 2 53 28 pm](https://f.cloud.github.com/assets/1245093/1864178/c9e6fb76-77ee-11e3-8df8-fe957f5f57a7.png)
![screen shot 2014-01-07 at 2 53 19 pm](https://f.cloud.github.com/assets/1245093/1864179/d43c5314-77ee-11e3-875b-1a3da417dbd3.png)
That's quite a chronological jump between the first two data points.

**Comment by lefnire** [comment]
It might be merging all data points from the previous year, have a look at https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L83

**Comment by SyntaxPickax** [comment]
Ah, I see. Cool.

**Comment by deilann** [comment]
Gonna close this. We have better progress graph tickets and I no longer get the mangled stuff.

**Comment by SabreCat** [comment]
Date labels still overlap and are unreadable for me. Reopening.

**Comment by SabreCat** [comment]
@deilann If there's a better ticket, could you reference it here?

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2516

**Comment by SabreCat** [comment]
Cool, OK. Since that ticket is about a major overhaul, I'm gonna keep this open in case we can straighten out the malfunctions of the existing functionality in the meantime.

**Comment by rcichy** [comment]
Small change, but labels can be more readble.

Old:
![capture2](https://cloud.githubusercontent.com/assets/5044995/3280544/7f9812b4-f46a-11e3-9e77-613fa665abec.png)

Vertical - changed:
![capute](https://cloud.githubusercontent.com/assets/5044995/3280545/8bf84ed4-f46a-11e3-9f9f-387b088dc528.png)
