### ISSUE TITLE
Still having syncing issues

### ISSUE THREAD

**Issue by MattRenthing** [HabitRPG/habitica#1626]
This is related to this ticket that was closed when you guys made the new site: https://github.com/HabitRPG/habitrpg/issues/1368

Basically, I can log in with the same account name (MattRenthing) and PW (#notanoob) on both the iOS mobile ap and the website but the dailies do not sync and the User ID and API Tokens are different. Now, it should be said that the aps on my iPad and iPhone have the same User ID but not the website (despite using the same account name/pw as the mobiles). 

I'm currently using Firefox 24.0 as my browser.

**Comment by lefnire** [comment]
common situation is person used facebook to sign up on web, and then registered uname/password on mobile. If they don't have the same uuid, they're different accounts. Give me both uuids and I'll see if i can give you more info

**Comment by MattRenthing** [comment]
Web: d601f7b0-2866-470d-85b7-3eaf070bec28
iOS: dadc5f64-343b-4799-abed-051d15583779

**Comment by lefnire** [comment]
yep, as described above. You registered web with facebook, then mobile with uname/pw under `MattRenthing`. Unfortunately no way to merge accounts, so you'll have to choose just one
