### ISSUE TITLE
Chat sync button throws 401 error

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1627]
If I click the "Fetch Recent Messages" button in my party chat, a banner error "401: You don't have access to this group" appears.

This error was logged once, but I haven't been able to replicate it:

[11:03:01.613] "Error: [$rootScope:inprog] http://errors.angularjs.org/undefined/$rootScope/inprog?p0=%24apply
d/<@https://beta.habitrpg.com/app-b3021526.js:3
i@https://beta.habitrpg.com/app-b3021526.js:5
h.prototype.$apply@https://beta.habitrpg.com/app-b3021526.js:5
m@https://beta.habitrpg.com/app-b3021526.js:10
fb.event.special[a].handle@https://beta.habitrpg.com/app-b3021526.js:2
fb.event.dispatch@https://beta.habitrpg.com/app-b3021526.js:2
fb.event.add/r.handle@https://beta.habitrpg.com/app-b3021526.js:2
"

This, however, appears every time I get the 401:

[12:07:11.115] [object Arguments]

Firefox on Windows 7, beta.habit, user ID 7f14ed62-5408-4e1b-be83-ada62d504931

**Comment by paglias** [comment]
@lefnire getting a party is always going to return a 401 error, see https://github.com/HabitRPG/habitrpg/blob/master/src/controllers/groups.js#L105

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/3a45e721381e26ce32531d3a37b9db17e06f6a32

**Comment by lefnire** [comment]
god, @paglias you are on FIRE!
