### ISSUE TITLE
Drop sales are partially implemented on production, breaking egg hatching

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#1629]
So, it looks like part of the (cool! new!) drop-selling feature got unintentionally rolled out on production? On production, I see Alexander's message about how to hatch or sell drops. When I click on a tiger egg, I see a button "Sell tiger for 3GP." When I click on a potion to hatch it, I get a _second_ button underneath, saying (IIRC) "Sell for 3GP" (but not saying what I'm selling. So I didn't click it because I was nervous it would sell my egg instead of the  base and white potions I wanted to sell. 

Now, full disclosure, I failed to take a screenshot and now I can't reproduce because I used the one potion that formed a hatching combination. So now when I click on a potion, trying to remember exactly what the text was (I know it didn't include the potion or potion type, but did the GP change when I clicked on different potions or was it really the 3GP of the tiger egg all the time?) I get a message that I can't hatch that combination, even though I don't have an egg currently selected. (It's remembering the last one I clicked, according to the "Sell X for GP" button which stays visible even when I deselect all eggs.

This functionality all works great on beta, but I think some code got pushed to production that shouldn't have.

**Comment by lefnire** [comment]
Hmm, can't reproduce, and prod and beta are at the same commit SHA. The
deselection bit is just a visual issue where it's not yet obvious which egg
is selected, I'll be fixing that. I think I'll wait for someone else to
chime in to see if the blank sell button happens again, you do a hard
refresh?

**Comment by brightbold** [comment]
I did but unfortunately I sold all my potions (on beta) so can't attempt to reproduce until I get another potion. Maybe it was just a fluke of the page not having fully reloaded after the feature was committed?

**Comment by lefnire** [comment]
Hit me with uuid if you want gems to test more (or uuid of test account if
you want to)

**Comment by SabreCat** [comment]
I can confirm this is happening, on main Habit and not beta.habit. What's worse, you also no longer get popups of "you can't hatch that combination" - can you even hatch things at all on main right now?

**Comment by SabreCat** [comment]
Ah wait, a hard refresh does seem to fix it. Some sort of cache issue, perhaps.

**Comment by paglias** [comment]
Ok, everything should be ok with a cache refresh (f5 or ctrl+f5 when on habitrpg.com). If you notice that it continues to happen that cache isn't refreshed when new version are released please open a ticket since it may be a serious issue.
