### ISSUE TITLE
Selling potions provides streak bonus notification

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1631]
I checked off a daily for which I received an 87 silver streak bonus. Then I went to my inventory and sold a base potion. I got a "+1 GP" notification and a "+87 SP  streak bonus" notification. I tried twice more, and it continued happening. 

I don't seem to actually be getting the bonus silver; I'm just getting a notification that says I am.

**Comment by lefnire** [comment]
Ah, looks like User.user._tmp.streakBonus doesn't get discarded until
User.log({}) sync. That detailed description gives some good insight into
the situation, thanks Michael

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/cd97cc1e24b2351214e301bdae0822ec1f64c230

**Comment by lemoness** [comment]
Got this yesterday :(

**Comment by lemoness** [comment]
...and again just now! Not for eggs, just for potions.

**Comment by wc8** [comment]
restore also gives me a streak on both the old and new site. On the new site, I also randomly got it for joining a challenge (unless that was just Tyler’s idea of a joke, rewarding me for joining the wc8-should-really-join-this-challenge).

**Comment by Alys** [comment]
This no longer happens so I'm closing it.
