### ISSUE TITLE
Can't login with firefox password manager

### ISSUE THREAD

**Issue by paulstaab** [HabitRPG/habitica#1632]
My password for HabitRPG is saved in the Firefox password manager, so than when I enter my username in the login field, Firefox automatically fills in the password for me. However, the login afterwards does not work, giving me a prompt saying

```
Missing :username or :password in request body, please provide both
```

If I copy the password from the password manager to the clipboard and manually paste it in the corresponding field everything works.

This happens since the page was ported to Angular and on Firefox 24 (I think also on previous versions). Maybe this is related to #1246  ?

**Comment by lefnire** [comment]
Yeah, I think it's the same as that one - let's follow up there. I think it's something about using AJAX login forms
