### ISSUE TITLE
I bought 20 gems (with Paypal) and still see ads.

### ISSUE THREAD

**Issue by Quarkmus** [HabitRPG/habitica#1633]
I bought 20 gems (with Paypal) and still see ads.

**Comment by lefnire** [comment]
Sorry, this was a manual database migration issues I hit with a handful of
users. Shoot me your user ID and I'll disable

**Comment by lemoness** [comment]
Furthermore, some of my friends started complaining about the quality of the ads - including "Free Sex Games" and "Buy A Wife From Asia." Actually. They have screen shots.

Is that the kind of ad that Habit has (I hope not), or did settings get screwed up in the migration?

**Comment by lefnire** [comment]
No, that's just Adsense - I hate to put this out there.. but it creates ads from (a) what it reads on the page (aka people's tasks), (b) what it knows about the user's browsing history. Mine's all about Android, audiobooks, games, etc... lol _gulp_

And don't worry, it's not a privacy point of concern as far as Habit's concerned. 99% of sites with ads use adsense, it's just the default drop-in until you can find a specific ad provider relationship. It's the same mechanism that shows ads when you do a google search (adsense is made by google). People who are concerned re: privacy typically have an adblock extension.

**Comment by lefnire** [comment]
Anyway, @lemoness are your friends still seeing ads when they shouldn't? Shoot me their UUIDs if so and I'll disable. This should have been fixed per a reverse migration, I'll be bummed if it's still an issue for people

actually, if you want @lemoness i can give you perms to edit the adsense block - I would assume there's a way to disable tracking and instead give it some keywords to go off of (like "habits", "productivity", "games", etc) - but I can't seem to figure it out after playing around with it

**Comment by lemoness** [comment]
HAHAHHAHAHAHHAHAHAHAHAH I'M GIVING THEM SO MUCH FLACK FOR THIS

I'll check and see if they're still seeing them - their complaints were
around the time of the migration.

We'll talk to Vicky to see what she thinks. People are pretty used to
spammy ads, IMO.
