### ISSUE TITLE
Unlock skin set after buying a skin

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1634]
Hi,

Could you please update the code so if I want to buy a skin set in which I already bought a skin, the cost of the set is reduced by 2 gems ?

I bought a spooky skin a bit fast, then decided to donate 5$ for 20 gems, and now I wish I had bought the set instead.

Thanks for your support
Cordially
##

**Comment by lemoness** [comment]
This would actually be a useful feature, similar to the iTunes Complete-An-Album feature - especially if we are going to be doing more of these in the future. 

@lefnire is getting this kind of code in at all feasible before the Event ends? Or will it have to wait until future events?

In terms of pricing, @shaners is generally pretty good at that. Let's see - maybe 4 or 3 gems to "complete a set"?

**Comment by lefnire** [comment]
Yeah, we'll have to add that the "complete a set" feature in for the next event

**Comment by Shaners** [comment]
Hmmm
- Skin Price: 2
- Set Price: 5
- Rainbow Price (w/o set discount): 16
- Spooky Skin Price (w/o set discount): 12
- Rainbow Set Savings: 11
- Spooky Set Savings: 7

People that buy the whole set at first deserve full discount as an incentive. People that have bought a partial portion of the set should get less of a discount but still should be offered some discount to purchase the remainder.

1 purchase: Set price 5: Savings: 9 on rainbow, 7 on spooky
2 purchase: Set price 5: Savings: 7 on rainbow, 5 on spooky
3 purchase: Set price 5: Savings: 5 on rainbow, 3 on spooky
4 purchase: Set price 5: Savings: 3 on rainbow, 1 on spooky
5 purchase: Set price 5: Savings: 1 on rainbow, -1 on spooky _no longer worth it_
6 purchase: Set price 5: Savings: -1 on rainbow _no longer worth it_, -3 on spooky _really not worth it_

Maybe keep set price at 5 until they've purchased 33% of the set then reduce to 3 to complete the set above that. Could even change the set price to 2 after 66% of the set is purchased. I may throw these numbers into an excel table to see if any of this actually makes sense.

**Comment by lemoness** [comment]
I knew you could be counted on!!

**Comment by Shaners** [comment]
Here's a little excel doc to calculate things:
https://www.dropbox.com/s/v0lyxvz9givpsul/HAB-CalcDiscount.xlsx
(edit blue cells)

**Comment by lemoness** [comment]
The current way that we are handling purchasable items is pretty entrenched, so I don't think we need this ticket any more. If someone really disagrees, comment hear and I will reopen it.
