### ISSUE TITLE
"Options" should change into "Tasks" when clicking the avatar in the tasks window (and visa versa)

### ISSUE THREAD

**Issue by ShadowBB** [HabitRPG/habitica#1635]
When I click "Options" (In the "username" drop down menu) it changes to Tasks so the user can correctly switch back to the Tasks view-port.

However when I use the Avatar to go the the Options menu there is still the option to go to the options menu in the drop down menu.

Clicking this menu item will not change anything but this menu item itself (which if clicked again behaves like it should and doesn't seem to break anything which makes this a minor bug in my humble opinion)

I checked this in several browsers (internet explorer, firefox, opera) and several versions. The behavior is consistent in all browsers tested.

**Comment by paglias** [comment]
Thanks for the report! This has been fixed in https://github.com/HabitRPG/habitrpg/commit/0c7ba32c6b1ee377ac7a85fb33df2737c686467d, it should arrive on the site in the next few days!

**Comment by lefnire** [comment]
getting an error http://gyazo.com/758dce802158c517f0405888e9c0d9f8 , but it appears benign (everything still works, and this bug is indeed fixed)

**Comment by paglias** [comment]
it seems to appear only when opening the app with no hash attached to the url (habitrpg.com only), fixed in https://github.com/HabitRPG/habitrpg/commit/fe52731393470473a830ab04198280b01fca338a
