### ISSUE TITLE
Back after 1 month...

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1636]
Hi, 
I left HabitRPG a bit, leaving my character in the tavern. I just came back and my character died and lose all of her gear :( 

I know I can restore my character but I don't remember her characteristics, can you help me with that ? 
Thank you in advance

**Comment by Shaners** [comment]
Don't think we have the resources available (Tyler's time) to investigate where you were at before leaving but you certainly can restore yourself to the best of your abilities through Settings > Restore. Or could take this as an opportunity for a Habit rebirth and start from scratch again!
