### ISSUE TITLE
gray all the time/ frozen

### ISSUE THREAD

**Issue by atariisoda** [HabitRPG/habitica#1638]
hey got a question..so my dailies are all gray every day although I have some of them set to be performed every day, they are all frozen:( and I am not sleeping in the Tavern either. So I can't progress coz nothing changes.

**Comment by lefnire** [comment]
yowzer, what's your uuid?

**Comment by atariisoda** [comment]
it's Atarii..wait mate .. you just fixed it :D sweet looks like it works now :) darn it I was stuck for days.. and I can even see the progress chart thingy Thank you

**Comment by lefnire** [comment]
Hmm.. strange, I didn't do anything. Keep an eye on it, if it happens again
see if there are any javascript errors. It could have been cached old
scripts

**Comment by atariisoda** [comment]
Well of course it was premature happiness, it still is not working :( If I only knew what these javascript error magical words mean i would fix it.. well anyways HELP

**Comment by atariisoda** [comment]
I made a picture with opened console..it's a bit in Polish so I'll try to translate it says: The configuration of the app does not allow the use of this URL: at least one of the given Url address is prohibited. The address must match the site address or the domain must be a subdomain of the application domain... or something like that and it sound very abstract to me :)

![screen shot 2013-10-25 at 12 48 34](https://f.cloud.github.com/assets/5760588/1407125/ba79f4b0-3d63-11e3-8626-d4b0cec15e2d.png)

**Comment by paglias** [comment]
This bug seems to be the same of #1057 and #1640. I would say there's a sync problem with the server.

@atariisoda next time it happens could you try logging out and back in and report if the problem persists? Thanks

**Comment by paglias** [comment]
Also @atariisoda some people seem to experience this only if they open the site after midnight and they have a custom day start, it's your case?

**Comment by atariisoda** [comment]
I think it was the case I changed it to the original setting and it works now...although when I had it set at 24 it worked for a bit as well..hmm well I will keep it at the original setting then :)

**Comment by Habitfan** [comment]
Well looks like I'm reporting my first bug.  Yesterday, I was gone all day, so I came home approximately 12:30 AM local time and started to check off my dailies and proceed to get as many of my daily's done as I could. Particularly the ones with the longest streaks. 2:50 AM I finished what I was going to get to that day.  Logged in this morning and everything is gray that was checked off yesterday. The only items that are unchecked were the ones I did not get to yesterday. I have not lost any health points, and it appears all my streaks are intact. The streets did not reset from the items that were not finished last night.

So it appears that I virtually skipped yesterday and everything is carrying over to today. Any advice? Thank you! :-)Well looks like I'm reporting my first bug. Last night I was gone all day, so I came home approximately 12:30 AM local time and started to check off my dailies and proceed to get as many of my daily's done as I could. Particularly the ones with the longest streaks. 2:50 AM I finished what I was going to get to that day.  logged in this morning and everything is gray that was checked off yesterday. The only items that are unchecked were the ones I did not get to yesterday. I have not lost any health points, and it appears all my streaks are intact. The streets did not reset from the items that were not finished last night.

So it appears that I virtually skipped yesterday and everything is carrying over to today. Any advice? Thank you! :-)

**Comment by Habitfan** [comment]
all my dailies are still gray. could this be related to participating in the challenges?

**Comment by lefnire** [comment]
TMK some people have issues with custom day start. Delete that field and
see if you hit this issue still in coming days

**Comment by Habitfan** [comment]
Tyler just so you know this is Senica. Apparently the handle was taken already on github.

Thanks for the reply. A bonus pat on the back when you get your hug for the prompt reply.

When you say delete the field are you indicating I should go back to a midnight reset?

This feature has actually worked flawless for me. I'm hoping that everything's back to normal tomorrow. Fingers crossed.

**Comment by lefnire** [comment]
Ol' sen! Whhheeel why didn't you say so. Well if the feature has worked flawless for you, probably not what's happening here then. Another possibility is that some people experience start-of-the-week day issues if they don't live in the US (another bit we're working on). Where you from incidentally? Anyway, I'll be looking into this ticket soon. Also, [shoot me an email](mailto:tylerrenelle@gmail.com) sometime just so I can say hi :)

**Comment by deilann** [comment]
Closing this -- it's gotta be #1057
