### ISSUE TITLE
Party Leader Cannot Boot Inactive Members

### ISSUE THREAD

**Issue by SwizzleSticks** [HabitRPG/habitica#1639]
Hi all,

There are two inactive members in my party and I cannot boot them no matter how many times I click boot member. I have tried internet explore and chrome. I've disabled extensions, etc. I used chrome's "inspect element" and it looks like it should be asking me to confirm the boot after I click the icon, so it should be possible.

Thoughts?

Swizzlesticks

**Comment by lefnire** [comment]
Hasn't been ported yet. It not showing a "not ported" dialog? Was such an
underused feature I saved it for later. I can boot someone manually if you
want

**Comment by SwizzleSticks** [comment]
Hi Tyler,

It's not showing the "not ported" dialogue unfortunately. I'd appreciate it if you manually booted two members though. Should I just post them here? If so, I hope you don't mind if I edit my post after.

**Comment by lefnire** [comment]
You can email me at tyler@habitrpg.com if you're worried

**Comment by paglias** [comment]
I'll work on this, but until the other users refresh the page more or less nothing change, right? Also, I'm going to add it as an api route, it doesn't need to be accessible using batchUpdate/User.log, right?

**Comment by lefnire** [comment]
db query will be `db.groups.update({_id:GROUP_ID},{$pull:{members:MEMBER_ID}})`. Right, doens't need to be accessible by batch (mainly, only the things that mobile uses need that access). Since it's an API route, it will take effect once the viewing user refreshes, doesn't require the booted to refresh
