### ISSUE TITLE
[Brainstorm] [Later] Mode "Translation": Farmer role playing mode.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#164]
This would take further thought, but after seeing a lifehacker comment (http://lifehacker.com/5976476/?post=56309300), I wonder if translation feature could be used to "translate" terms into greenhouse/farmer/gardener mode to expand user base.

Icon at top becomes farmer/planter. Level up from apprentice to gardener, farmer, etc. roles.

30 Leather Armor > Greenhouse
20 Sword 2 > Fertilizer
25 Potion > Graft
 Re-Roll > Replace Plants

... etc.

**Comment by lefnire** [comment]
@wc8 email me sometime: tylerrenelle at gmail

**Comment by hookang** [comment]
Added to Master List of Features #169

**Comment by wc8** [comment]
[Themes & Genres](https://trello.com/c/IU05aEB6)
