### ISSUE TITLE
Dallies don't reset

### ISSUE THREAD

**Issue by Valiorin** [HabitRPG/habitica#1640]
So i completed all my dallies last night... And they stayed grey all day.  This isn't the first time this has happened.  I'm not sleeping in the tavern as far as I know, and they are all set for every day.

**Comment by lefnire** [comment]
Can you see if there are any javascript errors? (see http://community.habitrpg.com/content/submitting-bugs)

**Comment by Valiorin** [comment]
It seems to be working today and so I don't see any script errors at this time.  If it happens again I will post an update.  Thanks for the help!

**Comment by paglias** [comment]
@Valiorin it's the same bug as of #1638, I'm closing this in favour of the other.

Next time it happens, could you try logging out and back in and report if the problem persists on #1638? Thanks
