### ISSUE TITLE
Unchecking and re-checking a daily gives more gold and XP than just checking it off once

### ISSUE THREAD

**Issue by KristenEberts** [HabitRPG/habitica#1641]
If you check off a daily task, then un-check it (e.g. because it wasn't QUITE done when you first marked it complete), you should lose the exact amount of gold and XP you had gained by completing the daily, right? What actually happens is that you lose most, but not all, of what you'd gained. If you check off the daily a second time, you get more XP and gold than you did the first time you marked it 'done' that day.

In effect, this means that a user could un-check and re-check a daily over and over to gain unlimited gold and level-ups. Not that I did that...well, it was just to replicate the bug, I promise!

**Comment by paglias** [comment]
@AntiquatedMeme thanks for the report, it's a known bug, you can follow at #964
