### ISSUE TITLE
Tags deletion

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1643]
There was a problem when deleting tags that ended in api.deleteTag not being called (it is fixed in https://github.com/HabitRPG/habitrpg/commit/715e4e42a5d29b07be080320908b10da5f50b7b4 - the commit message is wrong). So tags on the server are updated correctly because `saveOrEdit` (https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/filtersCtrl.js#L8-L13) sends down `user.tags` but tags where never removed from tasks so for example I have the tag icon on a task without any task applied to it (if you check the object on the database the task will still have a reference to a tag, which has been deleted).

So the things are two:

1-) Can we run a migration to remove all non-existing tags?
2-) `api.deleteTag` should be added to batchUpdate so if you remove any tag while offline it will still be removed from the tasks when you sync with the server - I can do this

**Comment by paglias** [comment]
Also the ui (tasks' tags list) isn't updated until the server return the whole user object, this is probably a scope issue but I couldn't solve it

**Comment by paglias** [comment]
OK api.deleteTag has been added to batch update operations (https://github.com/HabitRPG/habitrpg/commit/1f8915f5de54357a236f1a4106b50ef84acdff07), it set user.wasModified until I find out why it doesn't update the ui...

**Comment by lefnire** [comment]
Look at a the server to see if User.save is actually saving the user to the database (which invokes `__v++`). Sometimes, for reasons I haven't yet figured out, some attributes aren't markedModified, so User.save() just passes through without hitting the database - in those cases I run `user.markModified('tags'), etc` manually.

If I don't get around to writing a migration in time, hit me with one (examples in /migrations) and I'll double-check it, backup & migrate

**Comment by paglias** [comment]
The server saves it correctly it's an angular problem that doesn't update the ui unless the server return the whole user object with the correct changes

**Comment by paglias** [comment]
Closing since pull request with migration has been sent, there's a comment in the api method for tags deletion about returning the whole user object because UI isn't updated otherwise, if someone will want to solve this
