### ISSUE TITLE
I have only "????????" instead Russian Lang sentences in name and description to task

### ISSUE THREAD

**Issue by fro0m** [HabitRPG/habitica#1645]
i created it by my Android tablet but after sync it has become ???????
it's very disappointed me cause i forget what i wrote there =((((

**Comment by fro0m** [comment]
wow suddenly i reminded that =))) but fix android app

**Comment by paglias** [comment]
Writing it in Latin alphabet causes the same problem or not? Also does it
happens also on the site or only on mobile: both creating it directly on
the site and creating it on the phone and seeing it on the site?

**Comment by paglias** [comment]
I tried with some cyrillic text taken from the web and it shows correctly.... 
![2013-10-24 21 08 53](https://f.cloud.github.com/assets/589911/1403356/3af687a6-3cf2-11e3-893c-7676df6d326a.png) also on the website. Let me know if I did anything wrong

**Comment by fro0m** [comment]
so, the task was created by android app. I have no thoughts what could cause that

**Comment by paglias** [comment]
so on the website it shows correctly if it's created there?

**Comment by deilann** [comment]
Language files are completely different now-- I can't figure out what's going on here. Is it still going to be an issue?

**Comment by paglias** [comment]
It was a matter of encoding not translations in this case if I recall
correctly, but we've not heard anymore of this. I think we can close
Il 10/feb/2014 13:51 "deilann" notifications@github.com ha scritto:
