### ISSUE TITLE
Daily stuck on 20 streak

### ISSUE THREAD

**Issue by satyreyes** [HabitRPG/habitica#1647]
I have a daily task that I've streaked for twenty days.  When I checked it off on the 21st day, the box ticked and the task went gray as usual, but I gained no XP or GP and the streak number did not increment.  On reloading the page, the daily was unchecked again.  This behavior has persisted over the last three days.

**Comment by paglias** [comment]
@satyreyes it should be fixed now, in the following days it should arrive on the site, I'll post a comment here so you can try it works. Sorry for the issue :(
