### ISSUE TITLE
Can't sell potions

### ISSUE THREAD

**Issue by startmyquest** [HabitRPG/habitica#1651]
An egg is automatically selected in the inventory page, with option to sell to Alex. However, when trying to click on any of the potions to sell, because the egg is already selected and it keeps saying "you already have that pet, hatch a different combo".

Does not seem to be a way to un-select the egg and only select the potions for selling.

UID d5f4c795-cce2-4434-a1a5-8df9aa059408

**Comment by paglias** [comment]
Clicking on the egg doesn't have any effect? Also could you try refreshing the cache (f5 or ctrl+f5)

**Comment by lefnire** [comment]
Clicking the same egg unselects it. It's not obvious now though which egg
is selected, need to highlight selection somehow

**Comment by Alys** [comment]
I'm closing this because the selected egg/potion is now being highlighted.
