### ISSUE TITLE
"Continue" after death does nothing

### ISSUE THREAD

**Issue by aleczor** [HabitRPG/habitica#1652]
My friend died and is stuck not able to do anything. The continue button does not work and he can't click anything. Username: Bazoomba

**Comment by paglias** [comment]
You should ask your friend to check if there's any error in the javascript console: ctrl+shift+j on chrome, ctrl+shift+k on firefox and report here what he sees

**Comment by aleczor** [comment]
Update: switching from chrome to firefox solved the problem.

**Comment by paglias** [comment]
@aleczor he could try deleting localstorage on chrome and log in again, it should work too.

Here there are the steps to delete localstorage on chrome:

https://www.evernote.com/shard/s17/sh/eec8d98a-f9f0-4e83-920e-f5eb83d70384/f0be7cb3671608e7978e3f6a5f21e417

**Comment by paglias** [comment]
same as #1693 probably which is now fixed and will arrive in a few days
