### ISSUE TITLE
Port member avatar modal opening from members list

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1656]
https://github.com/HabitRPG/habitrpg/blob/develop/views/options/groups/group.jade#L69

@lefnire this should be possible only for parties or also for guilds?

**Comment by lefnire** [comment]
Whichever's easier, I imagine the easiest will be _all_ groups. If that's harder, we can exclude from parties since they're accessible via the header

**Comment by paglias** [comment]
Ok, it was a matter of it being a feature for all groups or only for parties... but since it's also avalaible in the tavern it's obviously for all groups :)
