### ISSUE TITLE
"undefined" GP message

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1657]
It was after my daily rollover time, but the rollover hadn't happened (it was still showing dailies in the state they were for the previous day). I clicked on a daily that I hadn't completed the previous day. It seems to have handled all the logic correctly: 
- I got the XP and gold for the daily, including no streak bonus
- Right after that the rollover triggered and I lost HP for my uncompleted dailies
- The task I'd clicked was marked as complete for the new day with a streak of 1.

I got the usual XP and GP notifications for the task I'd completed. For rollover, I got the usual notification showing HP loss, but there was a second one showing "undefined" GP. 

So, this is a very minor bug -- appears to be an anomalous notification message under unusual circumstances, with no other effects.

**Comment by rcichy** [comment]
It happened to me in te middle of the normal day (no other bugs noticed).
Right after added todo (app synced I guess) party message icon appeared (we are in the middle of egg hunt, somebody find an egg) and gold notification "+ undefined".

**Comment by paglias** [comment]
If it will happen again, please leave a comment
