### ISSUE TITLE
When to use removeSelf

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1659]
@lefnire when getting a party members removeSelf is used to remove the current user from the results so that you don't have yourself in the header bar.

But this way you also don't get yourself listed among party members which is a different behavior than what is happening for guilds...

Would be ok to move removeSelf to the client side and only when displaying avatars in the header bar?

**Comment by lefnire** [comment]
Yeah, that's a good point... maybe it would be best handled client-side. Play around with it if you get the chance & see what you think

**Comment by paglias** [comment]
Done in https://github.com/HabitRPG/habitrpg/commit/fc10e9d6e6869f6f1d0553d4f9537f37cdc23c61
