### ISSUE TITLE
Todo made 20+ copies of itself, won't clear

### ISSUE THREAD

**Issue by Renna** [HabitRPG/habitica#166]
Basically what it says on the box. I added a todo item and it decided it needed to be 20+ todo items. I can edit, tick or untick them as I please, but they won't go away. I can't delete them either, the button just doesn't do anything. Changing one appears to change all of them most of the time, but not always. 

Everything else operates normally and I can still add new tasks and get points for them and all.  I guess it just decided that it was VERY VERY IMPORTANT that I tag B. 
Using SR Ironware/Chrome on Windows 8.

![Tag B](https://f.cloud.github.com/assets/3334169/85057/ae38ecfa-6439-11e2-8f54-20a350a8f6d9.png)

**Comment by wc8** [comment]
I wonder if this is related to #118 and server load issues. 
Try refresh, then make one change, then refresh, see what happens.
(Now and then, I select everything on page and copy to text file, in case I need to re-enter any data.)

**Comment by lefnire** [comment]
Well.. I mean, it _is_ tab B… jk, on it

**Comment by lefnire** [comment]
naw, it'll fix itself on cron (tomorrow morning) - but i'll add a fix for each refresh. still don't know what's causing this, but it's an oldie

**Comment by lefnire** [comment]
amirite @horusofoz? amirite amirite?

**Comment by horusofoz** [comment]
@lefnire Issue still present for me but have seen you fix it previously so looking forward to cron

**Comment by mgatten** [comment]
Hate to be a "me too", but "me too". Except I tried deleting one of them, and it deleted them all and replaced them with empty dailies with check boxes. Edited one of those, and they all refilled.

**Comment by wc8** [comment]
Try: Refresh. Delete one. Refresh. Delete Blanks. Refresh. 
That cleared it up for me the one time anything like it happened to me (only 2 in my case).

**Comment by Renna** [comment]
The refresh/change/refresh thing didn't clear it up last night, but they're all gone this morning. Thanks!

**Comment by lefnire** [comment]
this should be fixed not only on cron now
