### ISSUE TITLE
Hatching instructions on inventory seem like they need updating

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1660]
Seems like the easiest way to hatch an egg now is to click on the potion you want to use which will then green-highlight all eggs that can be hatched with that potion. I figured this out by playing around, but it would be nice to have it spelled out.

I'll update the wiki instructions http://habitrpg.wikia.com/wiki/Pets#How_to_Hatch_a_Pet if my understanding of the new process is correct.

This seems like something I could fix with my limited html & css if I could get a pointer to which file to edit (still a little lost on Github).

**Comment by lefnire** [comment]
sure! Shoot me a PR, or if you prefer (for simplicity) just hit me with the text to replace [these sections](https://www.evernote.com/shard/s17/sh/54d15213-7820-49c7-a705-dffc1e374ac4/ed1003adf675b331abd407d479519934). I mean, there's instructions there - but if it's still not obvious, then updating time
