### ISSUE TITLE
merge challenges > develop

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1662]
Ok, @paglias so I merged challenges to develop. Many things are broken, and I haven't fully architected the ui-router setup for groups, so groups.js is going to be in major flux right now, but I want to make sure we're not getting too far out of sync.

Some things:
- If you could, merge https://github.com/HabitRPG/habitrpg/commit/9eecb977ea0ab1a4c97e6cbac3c7da67b30027b9 into [20131028_task_subdocs_and_tags_cleanup.js](https://github.com/HabitRPG/habitrpg/blob/develop/migrations/20131028_task_subdocs_and_tags_cleanup.js), I'm going to run the full migration all at once since it takes about 30m. When you're done, delete the other two files and we can rename this one to something more sensical as necessary
- I did a full `git checkout src/controllers/groups.js --theirs` in the merge. This discarded your groups.js changes at https://github.com/HabitRPG/habitrpg/commit/fd952701dba6505599659c20c65a0059c5124242 , the file had big conflicts and I figured it would be best if you re-implemented the changes since you're closer to the situation. No other files were discarded, and I'm fairly confident I merged the other conflicts properly - but you may want to double check (conflict resolutions here https://github.com/HabitRPG/habitrpg/commit/4571cede37236443efb9dee9b8030125877a416d)

Some background on what I'm working on now so that you have a heads up on groups.js. I'm trying to implement a method of only requesting necessary fields from groups, groups.members, groups.challenges, etc. The reason is groups, with all its subdocs, are going to be too large to fetch all at once - so we've moved to angular-ui-router which allows us to incrementally fetch (lazy-load) routes at a time: 
- `/options` no fetch, just render
- `/options/groups` redirects to `/options/groups/tavern`, fetch full tavern (chat, challenges, etc)
- `/options/groups/guilds` fetch all guilds' `.name` and `._id`, but nothing else (for performance savings, since maybe they'll never click on particular guilds
- `/options/groups/:gid` fetch full group info, `group.members.names`, and `groups.challenges.name/description`
- `/options/groups/:gid/challenges/:cid` fetch full challenge info, including `challenge.user` subdocs for statistics
- etc, etc

Anyway, there's a lot going on - hit me on chat if you want to talk about anything

**Comment by lefnire** [comment]
Also, let me know what you think of this whole groups architecture. I'm still not sure if I'm doing it right, but trying to come up with a good nested resources setup for ui-router

**Comment by lefnire** [comment]
Ok, the backend is more stable now, and I've fully merged https://github.com/HabitRPG/habitrpg/commit/77fee06fdb2da8983a9ee849b406c078b06a51b5 , including your `invites` code. Double check to make sure everything is OK, but I'm more confident in this merge and I think we can carry forward pushing up new commits. I'm going to combine your migrations into a single migration, then i'll close this ticket

**Comment by paglias** [comment]
Everything is ok! Exception made for angular-route not being installed by bower, it's still needed also with angular-ui-router or we can simply remove it from the module definition in public/js/app.js. It's the reason why the server you set up show a bank page.

About this changes specifically:
- challenges are broken but I think it's normal and also there are a few things not really self-explanatory but that's not a big problem
- everything feels a lot faster in particular switching from tasks to options
- memory usage seems a little less than the current site but I should try with my account not the local ones I use for testing
- the only thing I don't like is the profile tab subtabs: profile, stats and avatar felt better before when they where under the same tab, now there's a lot of unused empty space which isn't really good

Great work @lefnire !

**Comment by paglias** [comment]
also stable & inventory are missing

**Comment by lefnire** [comment]
stable & inventory both under the [inventory tab](http://gyazo.com/60f6c3e2b4e28c37e8434bc252f41de8). the white screen / includes / grunt file issues fixed. I still need to do a bit of optimization on the tasks page (i think we're storing too much about members in MemberServices.populate() that we can cut back on). I also want to try some better `ng-if` on task edit panes & completed/remaining tabs, I think removing those listeners from the DOM will save some resources.

Profile > Avatar is actually clearing up room for upcoming (very soon!) [new customization options](https://www.evernote.com/shard/s17/sh/0b22bfe9-4892-4df3-a278-daea9d2ad385/4d8245d668836ba53b913cc227bfafdd). the only tab that will still have awkward amounts of whitespace is Profile > Profile, but IMO that's ok, not a lot of people will frequent that tab

**Comment by lefnire** [comment]
btw @paglias [this is the card](https://trello.com/c/YKXmHNjY/306-customization-redo) with the upcoming customizations that will populate those white spaces
