### ISSUE TITLE
Logging In Death.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1666]
It looks like habitrpg decided a new day dawned when I logged in on challenges/habitrpg, so I took a hit for every incomplete task… which killed me. 

I will have to see if it is only the first login or just logging in at all.

**Comment by paglias** [comment]
I think challenges.HabitRPG.com has an old version of the database
Il 30/ott/2013 21:16 "wc8" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
yep, it's an old snap (yesterday morn)

**Comment by lemoness** [comment]
That explains why I died too! My first-ever time ;p
