### ISSUE TITLE
Challenges - extra empty checkboxes

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1668]
When I go to the challenges page, under groups it lists "Purple Party" and "HabitRPG" but in between those two are some empty checkboxes with no text attached.

**Comment by lemoness** [comment]
And now that I see other people's screenshots, it looks like it's supposed to have entries for my groups! None of my groups showed up.

**Comment by lefnire** [comment]
pushing fix https://github.com/HabitRPG/habitrpg/commit/d2c50dc02fb76987b5ae9d62a7867d400d7e135f , live in 5
