### ISSUE TITLE
Health Restored then disappeared

### ISSUE THREAD

**Issue by jurries21** [HabitRPG/habitica#167]
My health had been down to about 22 or so yesterday when I leveled up, which restored me back to full health like normal. When I logged back on today though I was back down to 20 HP for some reason. Help?

**Comment by jurries21** [comment]
I should clarify that I had only missed two of my dailies, so I the 2 HP drop makes sense, but it dropping down from 50 to 20 doesn't.

**Comment by horusofoz** [comment]
@Jurries Can you confirm if you've had any recurrences of this issue?

**Comment by jurries21** [comment]
No, right now its fine. I leveled up again yesterday and so far my health has stayed fine. Thanks though...really loving this site so far! Its helping me keep on track more then a normal todo list ever has!

**Comment by horusofoz** [comment]
@jurries21 You're welcome :)

@SlappyBag Can you close this ticket please?

**Comment by StanLindsey** [comment]
@jurries21 - =D Glad it sorted itself out and we love that you're enjoying it so much =D

Thanks for the heads up @horusofoz
