### ISSUE TITLE
have to refresh to see new challenge

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1670]
I inputted the data for a sample challenge, then tried to create it, and got an error message saying "please select group". However, I am now unable to click any of the check boxes. 

I navigated away and back, but I still can't click any of the boxes. The participation buttons work fine, though

**Comment by lefnire** [comment]
how about now?

**Comment by lemoness** [comment]
It worked!! Had to refresh to see it in the list, though.

**Comment by lefnire** [comment]
fixed
