### ISSUE TITLE
Challenges - Unclear which challenge is mine

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1671]
I just joined a preexisting challenge. When I did so, it took me a while to realize that MY challenge tracker was the top bar. There should be my username or something, like with the others, or it should be highlighted - SOMETHING to make it obvious which one is yours! The fact that there is an empty challenges bar at the top makes it extra confusing. Maybe have the create-a-challenge separate from the displays in preexisting challenges?

**Comment by lefnire** [comment]
not quite following this one. Your'e talking about an indicator for challenges that you've created? Or challenges that you've joined (which should be given away by the Leave button). Should I create a filter bottom-left for "challenges I've created"?

**Comment by lemoness** [comment]
Sorry, I was in a rush - I meant that when I am looking at all of the
"progress reports" of users in a specific Challenge, I wasn't sure at first
which one was mine, especially because the "create a challenge" bar stayed
on top. It was visually confusing. Just having your name labeled would be
nice so that you can tell which of the thousand "Dailies" bars is the one
that applies to you.

Of course, a Challenges I've Created filter might be nice, too, if you want
to do mass-editing and prize set-up!

**Comment by lefnire** [comment]
Ah, got it. Yeah, definitely not obvious - will see what I can do. This will probably look better once we get @SabreCat's collapsible-participants suggestion in

**Comment by lefnire** [comment]
Ok, i added a collapsible on "how's everyone doing?" for now. The better solution will be v2's re-skinning the UI to look like @wc8's comps at https://trello.com/c/k0kSlT0Q/58-challenges-individual-party-guild-public , will cross that bridge when we get there
