### ISSUE TITLE
Daily added after I joined challenge does not show up in my list.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1674]
Rather than a fix, I suggest this could be a feature: add a option to “update” your list to reflect the new challenge/changes. 

That way, if the author decides to change the game midstream, you at least have some notice/control before your task list is changed.
![missing task](https://f.cloud.github.com/assets/3326182/1441897/2ccc0c30-41b3-11e3-94e3-8c8b0dc57bbd.png)

**Comment by lemoness** [comment]
Ditto with problem - also not showing up on Habits or To-Dos, although for me the missing tasks are just from the challenge I created. The ones that others created work just fine!!

**Comment by lefnire** [comment]
fixed in bbb4a91 . Adding "confirm adding new task" as a v2 trello checklist item
