### ISSUE TITLE
All challenge links are broken for party challenge I created

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1677]
Created a challenge for my test user party. Was able to join it with the originating user, but it says all the links are broken (note red-background bullhorn icons):

![screenclip](https://f.cloud.github.com/assets/4501321/1442408/c4976eba-41bd-11e3-8331-4d0a00e3951d.png)

**Comment by SabreCat** [comment]
Users:
24593eff-c4cc-43e3-950b-51f291a3468b (created challenge)
ca9f9f7f-8eb8-4b24-9579-a64cd4f83e05 (other party member, hasn't been able to sign up due to #1675 )

**Comment by SabreCat** [comment]
Can't seem to reproduce the issue, though. Second party Challenge I created didn't behave this way.

As further detail, my connection to my party member seemed to be disrupted along the way: their avatar went empty-headed and their name vanished from the party member list (though the UID was still there). Sync didn't seem to fix it, but logout/back in did. Haven't seen it since.

**Comment by bobbyroberts99** [comment]
I had the same problem yesterday, but today when I created another party challenge, the links haven't broken yet.

**Comment by lefnire** [comment]
fixed
