### ISSUE TITLE
Can tag challenges in normal tasks, other challenges

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1678]
Started creating a fresh challenge, and noticed that the other challenges I'm participating in were available as tags in the task editor:

![screenclip](https://f.cloud.github.com/assets/4501321/1442443/7913db80-41be-11e3-9183-d0dca44c2533.png)

Seeing this, I've realized I can tag my ordinary private user tasks with the challenges I'm in. Moreover, my own tasks report that they used to be part of a challenge! Not true...

![screenclip](https://f.cloud.github.com/assets/4501321/1442458/beab6654-41be-11e3-9146-462f29143307.png)

**Comment by SabreCat** [comment]
Poking around further, the challenge-tags appear to act just like normal tags. They don't actually add tasks to other challenges you don't own (which would be hilarious, but no).

Should challenge-generated tasks be available in the list like any other tag? I feel like there are interesting use-cases there, but overall it's just going to confuse people.

**Comment by SabreCat** [comment]
Ah: maybe you can't actually click these to effect when editing Challenge tasks. They throw an error:

## 

[19:24:58.935] "Error: ensureSafeObject(...) is undefined
_objectIndex/<.assign@http://challenges.habitrpg.com/bower_components/angular/angular.js:8541
@http://challenges.habitrpg.com/bower_components/angular/angular.js:14474
checkboxInputType/</<@http://challenges.habitrpg.com/bower_components/angular/angular.js:14055
Scope.prototype.$eval@http://challenges.habitrpg.com/bower_components/angular/angular.js:10034
Scope.prototype.$apply@http://challenges.habitrpg.com/bower_components/angular/angular.js:10131
checkboxInputType/<@http://challenges.habitrpg.com/bower_components/angular/angular.js:14054
x.event.dispatch@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
x.event.add/y.handle@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
"

**Comment by wc8** [comment]
> I feel like there are interesting use-cases there, but overall it's just going to confuse people.

I agree. Some part of me wants to explore the interesting use cases anyway, but, alas probably would generate too much confusion to be worth it.

**Comment by SabreCat** [comment]
The bug part of this is fixed; the rest of it working as intended. Closing.
