### ISSUE TITLE
Error when deleting a task from an in-progress challenge

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1679]
While building a challenge, if you try to delete a task, this JavaScript error is logged when you click the trashcan:
## 

[18:56:53.714] "Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.2.0-rc.2/$rootScope/inprog?p0=%24apply
minErr/<@http://challenges.habitrpg.com/bower_components/angular/angular.js:78
beginPhase@http://challenges.habitrpg.com/bower_components/angular/angular.js:10328
Scope.prototype.$apply@http://challenges.habitrpg.com/bower_components/angular/angular.js:10130
d@http://challenges.habitrpg.com/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:1
x.event.special[e].handle@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
x.event.dispatch@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
x.event.add/y.handle@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
"

Confirming that you do want to delete the task has no effect.

**Comment by SabreCat** [comment]
Oh... you CAN delete it. But only if you hit "Cancel" on the popup! xD

**Comment by lefnire** [comment]
cancel / confirm fixed, can't replicate the $apply bug. Will try again soon

**Comment by lefnire** [comment]
should be fixed in new setup, try again?

**Comment by wc8** [comment]
I used to not be able to delete tasks from a challenge, but I can now.
