### ISSUE TITLE
Tavern broken on Challenges server

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1680]
Not sure if this was intentionally not implemented yet in the Challenges branch, but I can't post to the Tavern with my test user on challenges.habit. This Javascript error occurs:
## 

[19:01:18.408] "Error: group is undefined
$scope.postChat@http://challenges.habitrpg.com/js/controllers/groupsCtrl.js:91
_functionCall/<@http://challenges.habitrpg.com/bower_components/angular/angular.js:8564
ngEventDirectives[directiveName]</</</<@http://challenges.habitrpg.com/bower_components/angular/angular.js:15511
Scope.prototype.$eval@http://challenges.habitrpg.com/bower_components/angular/angular.js:10034
Scope.prototype.$apply@http://challenges.habitrpg.com/bower_components/angular/angular.js:10131
ngEventDirectives[directiveName]</</<@http://challenges.habitrpg.com/bower_components/angular/angular.js:15510
x.event.dispatch@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
x.event.add/y.handle@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
"

**Comment by wc8** [comment]
I was able to post earlier, can’t now. Also, Tavern no longer appears as an option in Challenges and I am asked (forced) to choose a group when creating a new challenge.

**Comment by SabreCat** [comment]
Haha, you could challenge the Tavern before? That's awesome.

**Comment by paglias** [comment]
@wc8 I can challenge HabitRPG which I think it's the new tavern name

**Comment by lefnire** [comment]
Actually, HabitRPG was the old name and I was manually setting it to "Tavern" before sending down. I'm updating this in the upcoming migration to rename it officially to Tavern. What are thoughts and what the name should be? I'm thinking Public, Tavern, or HabitRPG. Leaning towards Tavern

**Comment by lefnire** [comment]
fixed

**Comment by SabreCat** [comment]
My vote is for Public, second choice HabitRPG. Tavern is cute but unclear.
