### ISSUE TITLE
Clicking second challenge title should open second challenge, not just close first challenge

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1682]
While browsing the list of available challenges, you can click the title of one to unfold it, seeing its tasks, users, and statistics. However, the only way to close it back up is to go somewhere else in the interface and come back, or unfold another challenge. It would be intuitive to have a second click squash the challenge back down to list form.

**Comment by paglias** [comment]
This doesn't work, challenge is correctly closed on click but if you want to open another one the first click simply closes the one opened and doesn't open the new one

**Comment by TheHollidayInn** [comment]
While looking into this ticket, I am seeing the correct behaviors.
1. When clicking the open challenge title, the challenge closes.
2. When opening one challenge, the clicking another, the previous challenge closes. 

Can someone verify that this is still an issue?

**Comment by SabreCat** [comment]
Aye, this looks to have gotten fixed at some point. There are scrolling issues still, but the second challenge does open. Closing.
