### ISSUE TITLE
Challenge edit buttons briefly appear on challenge I don't own

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1683]
If I expand a challenge available to me in the list, the Save/Delete/Cancel options appear while it's loading:

![screenclip](https://f.cloud.github.com/assets/4501321/1442671/6652223a-41c4-11e3-9cb8-0ed06814e6bf.png)

It's actually possible to mash the Delete button while it's visible, and get the prompt to confirm deletion. If you try to go through with it, you might get an alert-style error "401: cannot delete challenges API" (or something like that... didn't screenshot it in time), an [object arguments] entry in the JS console, and/or ACTUALLY DELETE A CHALLENGE YOU DON'T OWN. o.O

**Comment by paglias** [comment]
It may get deleted but only until you refresh I think since it's showing a 401, non authorized, error.

@lefnire ng-cloak may work here?

**Comment by lefnire** [comment]
it was a `resolve` issue (see fix ^). I'm going to revisit if we upgrade ui-router to #master, because I think they're $state.resolve doesn't work with ngResource
