### ISSUE TITLE
Challenge tasks of other users appears intercative

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1684]
## EDITED: Challenge tasks of other users appears as interactive

If you're looking at a challenge with some users' stats on display, the checkboxes and whatnot act as if they're interactive for you (the little checkmark appears on mouseover of a Daily, for instance). Following through produces this JS error:
## 

[19:40:45.272] "Error: user.stats is undefined
[5]</</obj.score@http://challenges.habitrpg.com/bower_components/habitrpg-shared/dist/habitrpg-shared.js:7566
_functionCall/<@http://challenges.habitrpg.com/bower_components/angular/angular.js:8564
ngEventDirectives[directiveName]</</</<@http://challenges.habitrpg.com/bower_components/angular/angular.js:15511
Scope.prototype.$eval@http://challenges.habitrpg.com/bower_components/angular/angular.js:10034
Scope.prototype.$apply@http://challenges.habitrpg.com/bower_components/angular/angular.js:10131
ngEventDirectives[directiveName]</</<@http://challenges.habitrpg.com/bower_components/angular/angular.js:15510
x.event.dispatch@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
x.event.add/y.handle@http://challenges.habitrpg.com/bower_components/jquery/jquery.min.js:5
"

**Comment by paglias** [comment]
Error not happenin anymore but tasks still appear interactives

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4880
