### ISSUE TITLE
Statistics shouldn't always load when browsing a challenge

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1686]
Given the large amount of page real estate each user's Statistics takes up, and the possibility that popular public Challenges could conceivably feature hundreds or thousands of users participating, showing everyone's stats to a user just popping open a Challenge to see its tasks seems like a bad idea. Here are some possibilities for improvement:
- Collapse the statistics behind a link. User must consciously choose to go look them up.
- Show the list of participants as links, and can click one to see their stats.
- Since stats don't need to be interactive, make them smaller, minimalistic. Much smaller headers, half-size boxes, whatever.

**Comment by paglias** [comment]
1 could still be a problem with public challenges that may have thousands of users.

I would go for 2+3

**Comment by wc8** [comment]
I agree, 2&3 seem good.

**Comment by lefnire** [comment]
we'll want to then color-code user names by their aggregate score so challenge leaders can still get that high-level "who needs help" view. Yeah, I agree with this ticket

**Comment by lefnire** [comment]
woops, how did i forget about this ticket so fast and create a duplicate: https://github.com/HabitRPG/habitrpg/issues/1716 . Anyway, some useful commit references there, so I'm gonna close this and follow there
