### ISSUE TITLE
[challenges] guild reloaded every time?

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1689]
When you open a guild, then open another tab and come back to the guild it is completely reloaded every time

**Comment by paglias** [comment]
Also while loading the guild the browser freeze, memory usage go up by about 200mb every time (and it's not cleared) and cpu to 100%. I tried with a public guild "The scholars" with around 1300 users.
![selezione_003](https://f.cloud.github.com/assets/589911/1446300/3ea3d5dc-4235-11e3-895b-eefa9fa96074.png)

**Comment by lefnire** [comment]
the reason I think it's taking so much memory is that we're unnecessarily using `Members.populate(group)` after each group is loaded, which _then_ loads members into memory so their avatars can be clicked. I think we should remove _all_ the Member-caching code. It's pretty rare people click one avatar twice, IMO we should instead load members every time they're clicked (maybe even with [ui-router named views](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views)).

It does, on the other hand, make sense to cache Groups - as you're suggesting. See how I'm doing it for tavern & guilds(name,descriptions) in GroupServices for example. I'm not quite sure this is the right approach, but it works for those cases.

**Comment by deilann** [comment]
Was this fixed? I think it has. I'm certainly not having this problem, and I believe members are loaded every time they're clicked now.

Reopen if I'm wrong.
