### ISSUE TITLE
angular 1.2.0 rc3 breaks our ngresource

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1691]
Just to let @lefnire know that angular 1.2.0-rc3 breaks habitrpg's ngresource http://docs.angularjs.org/error/$resource:badcfg?p0=object&p1=array

**Comment by lefnire** [comment]
I'll check into this, but I think it has to do with how we're now handling GET /groups. See comments on https://github.com/HabitRPG/habitrpg/commit/d2c50dc02fb76987b5ae9d62a7867d400d7e135f#diff-de5eb65c876ca1dbc6698250c15529c4R91

**Comment by paglias** [comment]
Mah, I'm getting this also on rc2 when I leave a guild, two request are made, one for leaving whihc returns an empty response and one to /groups which returns an array (why it is made?)

**Comment by paglias** [comment]
Should be ok now, so we can update if we want
