### ISSUE TITLE
Challenges: Overall reward stats are garbled

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1692]
I bought the reward for "2nd Challenge for Test party (created by Nattyaware1)" twice and when I look at the stats it came back with illegible text.

![name004_1](https://f.cloud.github.com/assets/4084120/1447344/aa00f6e2-4245-11e3-8aec-ef6e42393950.jpg)

**Comment by lefnire** [comment]
fixed
