### ISSUE TITLE
Death Modal won’t close.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1693]
I cannot revive my character. I left most of the tasks unchecked on the challenges site. This morning, clicking the “Continue” button does nothing. Refreshing the page does nothing.

**Comment by paglias** [comment]
Try clearing localstorage or heading to challenges.habitrpg.com/logout

**Comment by wc8** [comment]
Update: the path I was refreshing was …/options/groups/tavern 
When I changed to …/tasks I was able to revive character.

**Comment by paglias** [comment]
mmm.. Interesting, there were no errors? This happened also on the non-challenge site for someone maybe it's the same reason of you

**Comment by lefnire** [comment]
ah, revive is part of TasksCtrl - not globally accessible. I'm fixing now

**Comment by lefnire** [comment]
fixed
