### ISSUE TITLE
Daily Progress bar opens Habit's progress window. Closes it too.

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#1696]
Found in Chrome browser and got same results when I used Rockmelt browser. Clicked on Dailies progress bar and the habits progress window opens. Clicking second time closes the habits progress window.

![progess in challenge habit](https://f.cloud.github.com/assets/5649804/1448615/8bc9fdcc-4259-11e3-8f2e-365703bb9206.png)

**Comment by lefnire** [comment]
fixed
