### ISSUE TITLE
21-day streak achievements.

### ISSUE THREAD

**Issue by Nostos** [HabitRPG/habitica#1697]
Hello,

HabitRPG doesn't seem to recognize my 21-day streak achievements properly...
The streak counters show up correctly beside each Daily (some of them are around 35 as of now), but the Achievements section doesn't mention any of them: "Has performed 0 21-day streaks on Dailies".

I read a few posts regarding this problem, but most of them have already been corrected & closed (as far as I could discern), so I opened up a new one. I hope this doesn't break any forum rule.

D.

**Comment by Shaners** [comment]
Check out my response here: #1658

**Comment by bobbyroberts99** [comment]
Here's some more help on the wiki (shameless plug): http://habitrpg.wikia.com/wiki/Streaks

**Comment by Nostos** [comment]
Ok, sorry, I restored the streak counter by hand...Thanks for your reply.
