### ISSUE TITLE
Challenges 2nd testing pass

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1699]
My lovely testers @bobbyroberts99 @SabreCat @paglias @lemoness and anyone else: I'm about to wipe challenges.habit and do a second migration with new fixes. Hit me if you don't want me to do it yet (for whatever reason).

This new push has Gem Prizes, new layout (social > challenges), bull-horn tags, challenge short-codes, and a whole bunch of bug fixes. Also, since you'll be dealing with Prizes I added some debug buttons in the footer (they weren't wired up before). 

My plan is to release probably tomorrow, and I'll be tackling `minor` & `medium` -tagged issues after we launch. I'll hold off on launching until all `critical` and most `major`'s are closed. If you get the chance: close, re-open, or "still an issue" any tickets as necessary with the new launch. I'll shout out here once we're up

**Comment by lefnire** [comment]
feeling pretty good about this my friends! I just did a speed-run with my roomate to show him the ropes - there were definitely some bugs & kinks, but it's mostly there :) So I'm currently uploading the migrated database to challenges.habit, my network is dog-slow so it may take an hour or two, but it's testable with new accounts in the interim. Methinks I'll launch this puppy mid-day tomorrow.

**Comment by bobbyroberts99** [comment]
Just created a 2nd test challenge for a party on the 2nd pass. Everything worked as expected, didn't see any problems and you made all the suggested changes. I won the challenge, but then I created it and got to decide who won. Big surprise… Any mechanics planned for letting the game decide who wins?

I like it. Looks good. Nice job!

**Comment by SabreCat** [comment]
Very cool! Unfortunately I didn't see this until this morning and have some
social obligations tonight, so I won't be able to bash on it until tomorrow
at the earliest. But I'll write up anything I do spot!

**Comment by lefnire** [comment]
no worries, you were amazing in the last pass - thanks so much!

**Comment by lemoness** [comment]
Quick question - do we have the ability to issue a challenge to a single
person? Like, just a roommate, or just a significant other? Right now the
smallest I can find is "party".

**Comment by SabreCat** [comment]
You could create a private Guild with them, perhaps?

**Comment by lefnire** [comment]
Tis on the features [checklist](https://trello.com/c/k0kSlT0Q/58-challenges-individual-party-guild-public)
