### ISSUE TITLE
Experience bar and Leveling Up(after death)

### ISSUE THREAD

**Issue by ysiraichi** [HabitRPG/habitica#170]
So... I started to play, and died. So I simply restarted.

-> When I did so, my experience bar was "0/0". I thought "That is strange". So when I clicked the + button of "Habits"(in fact, it could be any button or any check), suddenly I leveled up! D=... and my experience bar was like "0/40".

-> I restarted and checked something on "Daily". Doing this, I leveled up to level 2(as I said before). Then, I unchecked that "check button". My experience bar simply showed "-1/40".

**Comment by racuna** [comment]
@YuKill maybe your nickname would be iDied. LOL.

Back to topic:
I wonder what happens if i died... all my tasks will be gone or just i restart from level 1 but with all my tasks there?

**Comment by ysiraichi** [comment]
Yeah... I get that a lot... It WAS funny though... lol

The tasks will remain... Besides, you start on level 2... thats the bug! D=

**Comment by wc8** [comment]
Did you re-roll or just die and complete one task?
Perhaps a better title would be "Leveling Up Too Fast After Death" to make it clear this is/appears to be an issue.
(I think death/tokens/reroll is in a bit of flux, which might be why the FAQ/wiki doesn't address it yet.)

**Comment by ysiraichi** [comment]
I didn't understand you question. However, the fact is that once you die, you can't restart at level 1. You will be level 2 no matter what! xD

**Comment by horusofoz** [comment]
Bug confirmed. To reproduce open a new account and spam the "- eat junk food" habit button.

Due to low likelihood.impact of bug I'm tagging to be attended "later".

**Comment by horusofoz** [comment]
Issue no longer occurs.
