### ISSUE TITLE
[challenges] User not loaded correctly using Facebook Login (CastError)

### ISSUE THREAD

**Issue by AndreCaseyScott** [HabitRPG/habitica#1702]
First off, is the challenges test server setup to login with facebook? If not, then this might be a useless report... 

When I go to challenges.habitrpg.com, a few things happen:
- When I click play, and login with Facebook. Nothing really happens. URL bar updates with token and junk, but stays on static/front
- When I refresh the page again, with the API tokens and things in the URL, it "logs me in" with issues
  - My character is not loaded in the primary spot (no skins, level 1, etc). I am listed as a party member
  - My current tasks are not loaded (default tasks when creating a new account)
  - My Party members are visible and clickable, except my character is also listed with party members, and is still clickable. (talk about out of body experience)
- I also get a red error box that lists a whole bunch of ThrowTypeErrors and stuff. Listed in console too (contents below)
- Console also lists a 500 error. `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` with URL of `http://challenges.habitrpg.com/api/v1/user/batch-update?data=1383285365891`

Console Data (looks like some debug object):

```
Arguments[1]
0: Object
config: Object
cached: false
data: Array[0]
headers: Object
method: "POST"
params: Object
_v: undefined
data: 1383285365891
__proto__: Object
transformRequest: Array[1]
transformResponse: Array[1]
url: "/api/v1/user/batch-update"
__proto__: Object
data: "CastError: Cast to number failed for value &quot;[object Object]&quot; at path &quot;streak&quot;↵    at SchemaNumber.cast (/app/node_modules/mongoose/lib/schema/number.js:172:9)↵    at /app/node_modules/mongoose/lib/document.js:289:29↵    at EmbeddedDocument.Document.$__try (/app/node_modules/mongoose/lib/document.js:758:8)↵    at init (/app/node_modules/mongoose/lib/document.js:288:16)↵    at EmbeddedDocument.Document.init (/app/node_modules/mongoose/lib/document.js:247:3)↵    at DocumentArray.cast (/app/node_modules/mongoose/lib/schema/documentarray.js:135:27)↵    at /app/node_modules/mongoose/lib/document.js:289:29↵    at model.Document.$__try (/app/node_modules/mongoose/lib/document.js:758:8)↵    at init (/app/node_modules/mongoose/lib/document.js:288:16)↵    at model.Document.init (/app/node_modules/mongoose/lib/document.js:247:3)↵    at completeOne (/app/node_modules/mongoose/lib/query.js:1831:10)↵    at /app/node_modules/mongoose/lib/query.js:1799:11↵    at /app/node_modules/mongoose/lib/utils.js:414:16↵    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:953:5↵    at Cursor.nextObject (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:678:5)↵    at commandHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:658:14)↵    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1670:9↵    at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)↵    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18↵    at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)↵    at null.&lt;anonymous&gt; (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)↵    at EventEmitter.emit (events.js:95:17)↵    at null.&lt;anonymous&gt; (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)↵    at EventEmitter.emit (events.js:98:17)↵    at Socket.&lt;anonymous&gt; (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:301:18)↵    at Socket.EventEmitter.emit (events.js:95:17)↵    at Socket.&lt;anonymous&gt; (_stream_readable.js:746:14)↵    at Socket.EventEmitter.emit (events.js:92:17)↵    at emitReadable_ (_stream_readable.js:408:10)↵    at emitReadable (_stream_readable.js:404:5)↵    at readableAddChunk (_stream_readable.js:165:9)↵    at Socket.Readable.push (_stream_readable.js:127:10)↵    at TCP.onread (net.js:526:21) (see Chrome console for more details)."
headers: function (name) {
status: 500
__proto__: Object
callee: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them]
get callee: function ThrowTypeError() { [native code] }
arguments: null
caller: null
length: 0
name: "ThrowTypeError"
prototype: ThrowTypeError
__proto__: function Empty() {}
<function scope>
set callee: function ThrowTypeError() { [native code] }
arguments: null
caller: null
length: 0
name: "ThrowTypeError"
prototype: ThrowTypeError
__proto__: function Empty() {}
<function scope>
caller: (...)
get caller: function ThrowTypeError() { [native code] }
arguments: null
caller: null
length: 0
name: "ThrowTypeError"
prototype: ThrowTypeError
__proto__: function Empty() {}
<function scope>
set caller: function ThrowTypeError() { [native code] }
arguments: null
caller: null
length: 0
name: "ThrowTypeError"
prototype: ThrowTypeError
__proto__: function Empty() {}
<function scope>
length: 1
__proto__: Object
```

What I see first after refresh
![screen shot 2013-10-31 at 11 13 23 pm](https://f.cloud.github.com/assets/3774345/1452086/1e4f2de4-42bd-11e3-98ce-45678968966e.png)

The API and USER ID boxes in settings are blank, though in the debug request below, are are present in the object.
![screen shot 2013-10-31 at 11 13 40 pm](https://f.cloud.github.com/assets/3774345/1452087/1e508306-42bd-11e3-8fef-b2210b881048.png)

Highlights CastError. USER ID and API key are present in the "headers" part of the object (not shown)
![screen shot 2013-10-31 at 11 14 21 pm](https://f.cloud.github.com/assets/3774345/1452088/1e509350-42bd-11e3-93af-38dea8df566f.png)

**Comment by lefnire** [comment]
I think it's just that my internet connection is shit, and I'm having trouble uploading the migrated database - so you're getting a half-bake. I'm working on setting up a `screen` session from community.habit to load the migrated db to challenges.habit. Oy vey.

**Comment by lefnire** [comment]
ok, @onduhray give that a shot. I did all migrations from my server (good to know that was way faster)

**Comment by AndreCaseyScott** [comment]
Whelp, I gave it another try and no go. 
- Logged out, and tried logging back in via Facebook.
- Cleared cache and tried again.

No avail. Same errors. :/

**Comment by lefnire** [comment]
what's uuid?

**Comment by AndreCaseyScott** [comment]
73fad769-a194-4655-aefe-08bc7cb3dc39

**Comment by lefnire** [comment]
Looks like somehow _some_ of your `tasks.*.streak` are objects (specifically `{}` empty object) rather than Numbers, and with the new TaskSchema defining a strict policy on attr types it's throwing a cast error. Hmm, I'm not sure how we ended up with objects instead of Numbers, we'll need to fix that. In the mean time I'll add to the migration to clean up corrupted streaks. I'm wondering though, @onduhray do you or @paglias know if there's a way to circumvent Mongoose's strict typecasting and fallback on the default value in the schema if the attr's value doesn't match the proper type?

I'll add to migration tomorrow morn, thanks @onduhray

**Comment by AndreCaseyScott** [comment]
I don't know of any way built in to Mongoose to allow for fallbacks. Not terribly familiar with the framework, but in my searching, it seems you can set the defaults for an empty value, but not on a CastError.

Two thoughts:
1. Is it possible that some of my streaks are left over from derby db entries? The only thing I could find that _might_ be the culprit was [this line in the tasksCtrl](https://github.com/HabitRPG/habitrpg/blob/931e8125b40795725eb98114c1b05c433fbf5e01/public/js/controllers/tasksCtrl.js#L67) that sets `task.streak` to the string "streak". Or at least I think thats what it's doing... agh I dunno now. Anyways, my 2cents on that. Other than that, can't really tell where streaks get set in the code.
2. It might be possible to do some trickery when you "catch" the errors. You could have a separate function that runs in the "catch" phase that would reset the streak, or whatever, to the default value, and then "try" to save it again. I have no idea even what pseudocode for that would look like, or what to do if THAT save fails.

Hope that helps. :/

**Comment by paglias** [comment]
I'm having some connection issue so I can't do much but I got this locally
some time ago but only once. I got it after I ported the steak achievement
but I don't think it's released to this.

**Comment by lefnire** [comment]
Writing migration now, [asked a question](https://groups.google.com/forum/#!topic/mongoose-orm/3RERMfc9M40) on Mongoose just in case

**Comment by lefnire** [comment]
ok, I made our migration more strict. Tested for your account locally and all's good. See you live soon!
