### ISSUE TITLE
Clicking Challenge ToDo not always successful & sometimes turns off tag

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1707]
Sometimes clicking a Tavern Challenge Todo is successful, sometimes it needs a second click. I also get the beach ball spinning a lot. Sometimes the challenge tag gets turned off and I have to reapply the tag. 

This all happened on the Get Ready for Thanksgiving challenge.

Speaking of filtering… Anyway to make the bullhorn mouseover say "[name of tag] Challenge" so it's easy to figure out which tag to apply?

**Comment by paglias** [comment]
Is this still happening?

**Comment by bobbyroberts99** [comment]
Not using the app anymore so I don't know.

**Comment by lemoness** [comment]
Closing this for now, but if anyone has the problem again, we can reopen it.
