### ISSUE TITLE
[Feature Request] Sync Status

### ISSUE THREAD

**Issue by coolandsmartrr** [HabitRPG/habitica#171]
Given that HabitRpg's connection is not yet always stable, I think it'll be helpful to have a "sync status" indicator for the time-being. This feature informs wether their data (e.g. todo, habits, completion status) have been synced with the servers or not. This way, users won't refresh or close the rpg only to find that their progress is gone the next time they visit.

**Comment by racuna** [comment]
+1 I use two computers (home and work) and sometimes that happens to me

**Comment by hookang** [comment]
I completely agree. I use 3-5 devices (work, personal, ipad) and this happens to me more than I like... This is more of a stability issue I think than a feature.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
I believe this has been incorporated as an _Offline - Reconnect_ message. If that's not it, please reply back.
