### ISSUE TITLE
write reverse migration for removed tasks.*.tags

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1712]
https://github.com/HabitRPG/habitrpg/commit/4ac0ef4ac2551f9d583680b5d89fb03299251a9f#commitcomment-4492793

**Comment by lefnire** [comment]
I'll start working tomorrow on a reverse migration for lost tags. I hope it's feasible.. but if I can't get it working, I'll alternatively start working on a multi-tagging feature. More soon

**Comment by lefnire** [comment]
made backup, ran reverse-migration. tags, streaks, dates, and zero'd-values should now be restored. @paglias can you verify that your tasks with the broken tags have been cleaned?

**Comment by paglias** [comment]
They are gone!

**Comment by bobbyroberts99** [comment]
Tasks are filtering by tags again on beta for me. Thanks. I'll post this news on the wiki.

**Comment by wisteriacs** [comment]
THANK YOU, THANK YOU, THANK YOU!!!!! Between this and the site being so smooth on mobile now, I can use tags on my walks!! (Which is my much preferred time to manage HabitRPG!) You've made me VERY happy today!

**Comment by lefnire** [comment]
Fantastic!
