### ISSUE TITLE
Clicking my avatar shows error: 404: Cannot GET /partials/options

### ISSUE THREAD

**Issue by w13** [HabitRPG/habitica#1713]
"404: Cannot GET /partials/options"
when I click my avatar picture.

The URL in my browser keeps alternating between https://habitrpg.com/#/tasks and https://habitrpg.com/#/options every time I click.

The errors keep piling up like this: http://i.imgur.com/hhVW9wY.png

I'm using Chrome on Windows 8.1. I left HabitRPG running in an open tab overnight, I'm not sure if that has anything to do with it (I think it does: it timed out my session). Just now, I refreshed the page, and I'm able to click my avatar without the error popping up.

**Comment by paglias** [comment]
You kept habitrpg open in the middle of a big update so when you clicked the avatar it searched for a page that didn't exist anymore :) Thanks for the report!
