### ISSUE TITLE
Tavern Talk (chat) returns no results

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1714]
Is it down?

![name001](https://f.cloud.github.com/assets/4084120/1458418/4cbdf4fc-436d-11e3-8e46-ab195564a4eb.jpg)

**Comment by lefnire** [comment]
fixed https://github.com/HabitRPG/habitrpg/commit/62b2d5780b9886fc2520e560af634eba32ae29a7
