### ISSUE TITLE
Add direct angular-ui-routing links to user menu

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1715]
3 clicks to Stable become 1. It's very convenient to be able to have direct browser bookmarks. This would be even better.

![name001](https://f.cloud.github.com/assets/4084120/1458537/372c9eb0-437f-11e3-96a6-ae5de9a0c8f0.jpg)

**Comment by lefnire** [comment]
Like, add all top-level options items? I guess we could do superfish-style
flyouts
