### ISSUE TITLE
[Suggestion] Bonus / Penalty for consecutive habit performance

### ISSUE THREAD

**Issue by danj3ris** [HabitRPG/habitica#172]
If I complete a daily for a full 5 or 7 days straight, I want something to show for it. This can be a one time experience or coin boost or maybe even gaining back one health. Maybe my avatar receives a status effect like "haste", making all experience gain for a 24 hour period double. 

On the flipside, if I perform a bad habit multiple times a day or multiple days in a row, I dare say I WANT a penalty. Loss of coins, large health loss. Perhaps my avatar receives "poison" status and all negative habits or not performing a daily for a 24 hour span will hurt more.

**Comment by wc8** [comment]
https://github.com/lefnire/habitrpg/issues/59 suggests awards (titles/notifications) for consecutive completion/failure. Daily failure already causes a penalty. Methinks it makes sense for repeated performance of negative habits to result in a penalty.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote for [Streaks: Consecutive Bonuses](https://trello.com/c/wTiRWiB2)
