### ISSUE TITLE
Bailey should appear automatically?

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1720]
A new announcement has been posted to bailey but I had to enable it manually from the setting page, otherwise I wouldn't have noticed it.

**Comment by octern** [comment]
Had you ever manually disabled Bailey form the settings page? I think she's supposed to be on by default.

**Comment by lefnire** [comment]
Naw, I only recently ran the script to bring her back. The settings button brings her back, she's disabled by default
