### ISSUE TITLE
Check if user alraedy owns skin/set before deducting gems

### ISSUE THREAD

**Issue by Catmagnet** [HabitRPG/habitica#1721]
I clicked to unlock all the rainbow skins, clicked on the box that asked if I wanted to spend 5 gems, and the blue line went across the top.  Then I got an error message.  At that point, no gems had been taken from my stash, and the skins were not unlocked.  So I clicked on it again, thinking it had just had a problem and maybe it would work a second time.  It did work . . . but took 10 gems; I suppose, 5 for each time I clicked.

Is there any way for me to get my 5 gems back?

Thanks.

**Comment by lemoness** [comment]
Whoops, sorry about that! @lefnire or one of the other devs should be able to gift you some gems if they have your UUID.

**Comment by lefnire** [comment]
Yeah, @Catmagnet I just restored 5G on your account, double check that's ok. I'm gonna rename this ticket for my own reference. I double checked to see if anything was going wrong - all's ok, it's just we don't do any double checking that the user already owns something on the backend, so a slow internet connection and this issue might happen again for unknowing users.

**Comment by Catmagnet** [comment]
Thank you so much! My computer _is_ quite slow (and it's Windows X P) so
that might be part of the problem on my end.

**Comment by wizonesolutions** [comment]
Did this one already get fixed elsewhere?

**Comment by lefnire** [comment]
Yeah, should be covered [here](https://github.com/HabitRPG/habitrpg-shared/blob/91724277438a9a2b83e36f2106f5c688bbe0bac7/script/index.coffee#L722tL726)
