### ISSUE TITLE
Other people's pet counts show zero

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1723]
When I click on a party member's avatar, it brings up their stats. Both my party members are shown as having zero pets even though they even have a pet visible with their avatars, and I know they have many more. My own pet count in my profile is correct.

**Comment by djuretic** [comment]
+1 I have exactly the same problem. Also if a click on any person on the tavern, their pet count is zero.

**Comment by lefnire** [comment]
fixed

**Comment by djuretic** [comment]
It's happening again.

**Comment by lefnire** [comment]
fixed again
