### ISSUE TITLE
Show high-level progress of participants (color-coded names? total score?)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1728]
With challenge participant lists getting way longer than I thought they'd be (already!), it's not useful to click into each member individually to determine who's in the lead. Couple things we could do: (a) sort by total score, (b) show total score next to participants' names, (b) color-code their names similar to task colors. I'm thinking (a) has to happen regardless, in order that the leader can easily choose a winner, and that we can limit the returned query (which we'll have to do when participant lists are > 25 or so) while still retaining a useful list - say top 25 in the lead out of 1k participants.

Ok, this is easier said than done. We can't just load all users on the server routes, aggregate their scores, and sort in code - that's going to be way too much load on the server & database. We'll probably have to add an attribute to either the Challenge or User model, tying each participant to their score, and updated every time a user clicks a task

##

**Comment by lefnire** [comment]
After some investigation, we can achieve this via Mongo's `mapReduce` or `aggregate`. We could even load / show participant stats inline in the challenge view, without having to go the extra step of clicking to load a participant. Here's my thoughts: Use aggregate or mapReduce to:
1. Add a `.sumScore` value to members, which is `sum(task.*.value)`
2. `{sort:{sumScore:1}}`, so we have winners at the top
3. `{limit: 25}`, since any more than that isn't going to be useful information (eventually we can add infinite-scroll lazy-loading)

TMK mapReduce can be less-than-ideal performance wise, so ideally we'll be able to cache the query for 1hour or so, since the reports don't need to be _that_ fresh.

**Comment by wc8** [comment]
Hm… I was going to go on Trello and suggest coloring the participants names based on performance, which would be _b-colors_ (should that be c?).

On reading this, I’d like a—sort by progress _and_ b—task-like colors. I think both would make the challenge more interesting & competitive for the participants. Helping the challenge master pick a winner is an added bonus.

**Comment by lefnire** [comment]
Will do. Got my commit above, which is a mostly-working WIP - will revisit in the near future

**Comment by lemoness** [comment]
Better Challenge participant data is definitely still needed.

**Comment by librarianmage** [comment]
What would determine the score? Some challenges are based on streaks, some on doing something (and then being done), etc. Also, could the tasks be 'weighted' such that some tasks contribute more towards the score?

**Comment by khipkin** [comment]
Maybe we could implement a "scoring schema" enum (or something similar).  The challenge owner would choose an option when the challenge is created, and then progress could be displayed depending on which option was selected.  This may also allow for challenge winners to be chosen automatically for some scoring schemas.

**Comment by lemoness** [comment]
We will be revisiting better ways for scoring and awarding Challenges in a future feature that is being planned, so I am closing this ticket for now. It can always be reopened if necessary.
