### ISSUE TITLE
challenge tasks getting scored multiple times

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1729]
can see in http://gyazo.com/e17dce00d9a408685e8ba50afdcbd095, challenges has only been around one day but this daily has >10 completions (blue, big graph). Seems score is getting multi-counted somehow

**Comment by paglias** [comment]
one score for each user in the challenge that scored the task?

**Comment by lefnire** [comment]
that should just be applied to Challenge.task. So each person has their own, and then the all aggregate on challenge.tasks - but these scores I'm seeing are on the individuals' tasks

**Comment by lefnire** [comment]
fixed, it was copying over `task.value` & `task.history` on `challenge.join()`, so new subscribers were getting the overall group's progress on their task
