### ISSUE TITLE
study checklist

### ISSUE THREAD

**Issue by wjordan213** [HabitRPG/habitica#173]
I am a college student and it would be very cool if there was a way to track things involving my studying such as a set of academic goals I can check off the same way I would check off the todos. Also, maybe a custom list feature would be very helpful as well where if I wanted a list to check off involving fitness, work, academic goals etc. that i wanted to be separate from the other lists, i could just make it.

**Comment by wc8** [comment]
I think tags and categories are on the roadmap. 
By separate, are you thinking of a filtered view of a category (study/fitness/work) or an extra column or something that would be completely separate?
The complex todo feature #49 might be another way of separating these out.

**Comment by lefnire** [comment]
yep, tags is the solution : #48

**Comment by wc8** [comment]
Trello: [Checklists](https://trello.com/c/PJ1iJ413) and [Tags, Categories](https://trello.com/c/q7v02jAw)
