### ISSUE TITLE
Deleted Tasks reappear after Sync

### ISSUE THREAD

**Issue by Vorakesh** [HabitRPG/habitica#1730]
The "Example Tasks" reappear after I hit the Sync button or just re-login.

In the Android App my tasks appear after a couple of seconds on their own.

The can be edited (eating Junk Food is now a positive habit ;)) but not deleted

**Comment by Verax2** [comment]
Same results here.  Example tasks return after re-login or refresh.

If I delete my own stuff it stays gone, but not the original example tasks.

**Comment by lefnire** [comment]
this is a critical one, i'm gonna work on this asap. There's a mismatch going on between `task._id` and `task.id` (something to look out for @paglias )

**Comment by lefnire** [comment]
dupe of #1741, fixed
