### ISSUE TITLE
Dailies resetting their counters as if I haven't checked them when I have

### ISSUE THREAD

**Issue by RosemonkeyCT** [HabitRPG/habitica#1732]
This has happened several times now, but today's has reset 3 dailies to 1 when they were all between 40 and 50 streaking. Last time it was just one.

I'm using Firefox, my user ID is the same as this one - RosemonkeyCT.

In general, the website is still very slow and glitchy for me. I often have to reload the page and check that things have been ticked off properly. It doesn't always go through. And sometimes it resets itself as if I haven't and I lose progress. I'm not bothered about the health loss. It's more the money loss when streaks drop.

**Comment by lefnire** [comment]
how long has the slowness / unreliability been going on for you do you think?

**Comment by abdou1884** [comment]
Hi,
My Dailies counter resetted to 1 too. I was one a streak of 4 for three dailies, and I checked them out. They were part of the challenges tasks, so I can't restore the counter too. I'm using Chrome and my username is Abdou1884, as this one. Can I get any help with that?

**Comment by lefnire** [comment]
@abdou1884 I'm pushing ability to restore streak on challenge tasks, 5m should be live. @SabreCat @wc8 what do y'all think about this, should I keep it in the game? Streak doesn't do anything on challenges (yet) so it won't really affect anything.

**Comment by SabreCat** [comment]
I would vote for it being a temporary inclusion until this issue is resolved. With your own Dailies, the only person you're hurting by cheating is yourself. With a challenge Daily, the challenge leader might be using streak count to help decide the prize winner, so hacked streak values could really sour the situation.

**Comment by RosemonkeyCT** [comment]
Sorry, I've been a bit slow on keeping up with this one =/ since the beginning, my computer is a tiny bit slow in general, but the two websites it absolutely cannot cope with (and this will make you laugh) are HabitRPG and Google, particularly the image search - that just fries everything! The daily resorted itself and those have been fine since though, not sure if that was you or just luck but yay for that! And I know this is a totally different uissue, but it became a huge issue two days ago when I needed to go away. On my screen resolution (1024x768 I think is is? Not quite 800) I can't check into the Inn. It's behind something else.

I know there isn't much to HabitRPG on the surface, but whatever it does underneath just massacre's my computer. It sulks when I try to click dailies too fast (if I don't wait at least 10 seconds that's too fast), sulks when I try to go to a new page, and refuses when I try to type messages without freezing every 10-20 words for 5 minutes before carrying on. I do know the issue is more my computer, honestly it is. I call it a glorified calculator with pretty colours. But it can handle Hotmail, Facebook, deviantArt, GitHub, Twitter, the Wikia, Wordpress and other blog sites, Pinterest, and anything else I've really come across a tiny bit easier than it can handle Habit.

As for the streak counter, maybe make it a choice of the challenge setter? If it's a relaxed challenge, give the challenge setter the option to leave it open. But, if they are using the streak as something to judge a winner, give them the choice to close that edit option off to anyone who accepts it? Is that something you can do?

**Comment by abdou1884** [comment]
@lefnire thank you a lot. and I agree with @SabreCat.
@RosemonkeyCT I had same problem with entering the Inn. I restored chrome's window, and the button was visible and clickable. I use an extension called "the great suspender" to minimize chrome's and the many tabs draining my PC's performance, give it a try.

**Comment by paglias** [comment]
I think the streak counter is not an issue anymore, as for the performances #1499
