### ISSUE TITLE
Loss of HP and streaks at time other than day reset

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#1733]
I had a strange thing happen this morning, not sure what it's related to so I'll give as much detail as I can.
I leveled up last night so had 50 HP. I was actually still up after the day reset, and did a couple of dailies for Sunday before I went to bed. I didn't notice what my HP were at that time, but everything seemed normal.
This morning I opened two tabs (in Chrome, not sure that would matter) and went to https://beta.habitrpg.com/#/tasks on one, https://beta.habitrpg.com/#/options/groups/tavern on the other. Once they both loaded, I noticed that the options page said I had 40 HP, which is about what I expected based on the dailies I didn't get done yesterday. The tasks page said I had 7 HP. The experience points and the level were the same on both. But on the tasks page, I noticed that all except two of my dailies had lost their streaks - so very likely the 7 HP came from assuming I didn't do any dailies except those two. The two streaks that were kept were high ones but otherwise apparently random. Those two dailies I did in the early morning hours were not checked off either. (EDIT - No, I just realized they're not random. The two streaks that were kept ARE the dailies I checked off in the early morning hours. Also I just noticed that streaks were kept on dailies that were disabled yesterday, so it's just affecting the ones that were available to check off yesterday.)
Next I clicked on my avatar on the options page to see if going to the tasks from there would change my HP. I got to the tasks page and still had 40 HP and my dailies from yesterday had streaks still. The two dailies from early morning were checked off.
Next I opened a new tab and went to https://habitrpg.com/#/tasks to see if it was just something with the beta site. This page said I had 7 HP with most streaks gone.
Finally I refreshed the page that said I had 40 HP, and when it refreshed, I had 7 HP and everything else was the same as the other two tasks pages.

User ID is 0b670754-57f5-4704-854f-9a9c92107b9b if that helps. I have one Challenge daily that I added yesterday, everything else is the same as usual, and this hasn't happened to me before.

**Comment by hattieshoe** [comment]
I just had another thought. Could daylight savings time (we turned the clocks back last night) have somehow caused my account to effectively have an extra day where I started with 40 HP and only checked off those two things, getting hit by all the other uncompleted dailies? The clock change isn't supposed to happen till 2 AM and my settings give 0 as the reset time, but still, could that explain some of what happened?  (My Saturday-only dailies that I completed yesterday lost their streaks, so if there was an "extra day" it must have been another Saturday.)

**Comment by hattieshoe** [comment]
Just noticed my streaks are back - I'm pretty sure they didn't show up yesterday (Sunday) but today the things I did Sunday seem to be accounted for, along with (as far as I can tell) the previous streaks. If someone reset this for me, thank you - if not, I figured I should report it in case it's part of the bug.

**Comment by lefnire** [comment]
was a reset, see https://github.com/HabitRPG/habitrpg/issues/1712 . All fixed!
