### ISSUE TITLE
Custom rewards cost 0 GP

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1734]
Most but not all of my custom rewards (~20 out of 30) have been set to a cost of 0 GP. Clicking on them causes habitrpg's progress indicator to spin for several seconds, but does not deduct any GP and does not produce a status message.

**Comment by octern** [comment]
The problem has spontaneously resolved. The correct prices are showing again.

**Comment by lefnire** [comment]
yeah sorry about that, fixed at https://github.com/HabitRPG/habitrpg/issues/1712 and forgot about this ticket
