### ISSUE TITLE
Hatching potion captions on inventory not wrapping

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1736]
Cotton candy overlaps

![name004](https://f.cloud.github.com/assets/4084120/1461666/00043bf8-44c1-11e3-8c74-a3584410e0a1.jpg)

**Comment by bobbyroberts99** [comment]
Is this the same as #1028? (Looked but didn't find until after I submitted.)

**Comment by nathyong** [comment]
It appears to be an issue with the layout code using the internal name (which has no spaces) instead of the screen name. Since the name has no spaces it doesn't wrap longer potion names. So no, it doesn't look related to #1028..

**Comment by paglias** [comment]
@nathyong yes, the inventory page uses a different text from the original potion name (it uses potion.name instead of potion.text)...

**Comment by bobbyroberts99** [comment]
No longer a problem because of stacking.
