### ISSUE TITLE
Tab Crashing in Google Chrome

### ISSUE THREAD

**Issue by deertheory** [HabitRPG/habitica#1737]
If I check off more than one item, and occasionally when I only check off one item, HabitRPG becomes so overwhelmed that Chrome prompts me with the "HabitRPG has ceased loading" dialogue and asks if I want to force close it. I generally select Wait, and then it seems to be a 75/25 toss-up of whether or not HabitRPG prefers to simply crash or if it loads after some minutes.

In addition, generally after checking off an item, the page is so stuck on loading that it won't scroll down or respond to mouse hovering anywhere until after the task is done registering that it has been checked off.

**Comment by lefnire** [comment]
what's your UUID?

**Comment by lefnire** [comment]
let's follow on #1499
