### ISSUE TITLE
Task Creation Freezes Tab

### ISSUE THREAD

**Issue by deertheory** [HabitRPG/habitica#1739]
Using Google Chrome, creating a task occasionally causes the entire site to freeze and become unresponsive. Unlike in an earlier issue posted this does not consistently prompt Chrome's interrogative whether to force close the tab.

**Comment by negue** [comment]
@deertheory This Freeze still exists?

**Comment by deertheory** [comment]
I haven't used habitrpg in a while due to travelling a lot this last season and not having an app for it. I'll get back to it now that I'm back and see if it still exists. 

-----Original Message-----

**Comment by paglias** [comment]
I think it's #1499
