### ISSUE TITLE
urgency and importance

### ISSUE THREAD

**Issue by wjordan213** [HabitRPG/habitica#174]
_Edited by wc8: See [Importance, Priority, Duration/Difficulty, Deadlines](https://trello.com/c/4C8w1z5h)_
there should be a way of classifying what is urgent and what is important in this game. perhaps the option of assigning deadlines or decreasing the amount of experienced gained as something gets closer to its deadline would serve as a good motivator. If past a certain deadline, health would be lost

**Comment by wc8** [comment]
I thought I'd seen due date for todos mentioned elsewhere besides #45 but I'm not seeing it now. 
Priority has been discussed elsewhere, see #53 for algorithm factors. 
I lean towards a simple (important or not important) as a modifier working with the current algorithm might be possible way of marking priority/importance.
I lean towards deadlines/due dates addressing urgency. If urgent, has a date (and urgency weighted by the closeness of the due date).
Another area to consider would be integration with sites (or apps?) that incorporate the Eisenhower or Urgent/Important Matrix.

**Comment by hookang** [comment]
I would say priorities for tasks is probably a good start.

Added to Master Feature List #169. Closed for Organization.

**Comment by horusofoz** [comment]
I thought I already posted this but can't find the suggestion so please forgive if this is a duplicate posting.

I think an easy way of implementing priority/importance that would be forward compatible with minimal engineering is to add a multiplier based on priority to the existing equations used to calculate HP loss, XP/GP rewards and shading.

For example a three tiered priority system (my preferred system) would have the current algorithms unchanged for priority three tasks. Priority two tasks would have a 1.5 multiplier applied to HP loss, XP/GP rewards and shading. Priority One tasks would have a 2x multiplier applied.

All new tasks would be priority three by default and the user can increase priority if desired.

This method is easy to use and see the effect it has.

Additionally it would be able to be implemented parallel to the Due Date feature requested elsewhere and perceived as clashing with priority/importance setting.

**Comment by wc8** [comment]
@horusofoz you may be referring to your comment here #94, but I think your latest comments help clarify what you meant. I like the multiplier for priority and dates as a way of tracking urgency.

**Comment by horusofoz** [comment]
@wc8 You're right on both counts. Thanks.
