### ISSUE TITLE
Chat Duplication issue

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1740]
I've been seeing the occasional repeated message in guilds and the tavern the past few days, but couldn't be sure it wasn't just user error - until it happened with one of my messages. Has this old bug come back?

**Comment by lefnire** [comment]
Well, it won't be the same bug as last time. The last one was a Racer
internals issue that was duplicating database entries on the server. My
hunch is this one isn't preventing ENTER from being hit twice or something

**Comment by lemoness** [comment]
Ahhh that actually sounds really plausible! For me at least it was when I
hit enter by accident to start a new paragraph. That should be pretty
simple to test. Let me try it out.

Yep, that's definitely it!! I tested first with two enters - resulted in
two duplicate tavern messages - and then four enters - resulted in four
duplicate tavern messages. Great hunch, Tyler!!

**Comment by lefnire** [comment]
added a temp fix, can you give that another go?

**Comment by paglias** [comment]
@lefnire I was getting a 500 error at least on parties, I pushed a client side fix, it shoudl work fine
