### ISSUE TITLE
ngResource PUT/POST/DELETE send whole model to the server

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1742]
This could be quite a bottleneck for performances.

Every PUT/POST/DELETE http call made by angular $resource sends to the server the whole model.

For example deleting a chat message sends to the server the whole group model.

**Comment by lefnire** [comment]
yeah, I think we should separate chat out to it's own nested resource https://github.com/HabitRPG/habitrpg/issues/1665

**Comment by paglias** [comment]
Restangular seems quite interesting and supports nested resources. Anyway it's not only a chat problem but of every ngresource. It means that leaving a guild, for example, sends the whole group to the server.

**Comment by paglias** [comment]
@lefnire I didn't do anything for challenges like I did for groups (using class methods) because the only two methods are $join and $leave, they require a little of works so will do them later but anyway they don't send anything big to the server (usually).

The big problem with challenges regarding performances is another and it's the number of requests made:

### Leaving a challenge

2 request before leaving:
- querying groups
- querying challenges

1 after
- querying challenges

![selezione_012](https://f.cloud.github.com/assets/589911/1502606/1c426d00-489d-11e3-858d-70124ecd0f72.png)

The two before leaving the challenge i can't understand where they come from, querying challenges after having leaved it is necessary https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/challengesCtrl.js#L193?

### Deleting a challenge

Also here challenges are queried after the challenge is deleted, https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/challengesCtrl.js#L99

### Creating a challenge

After the challenge is created and returned from the server, challenges are queried https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/challengesCtrl.js#L74 and then the single challenge is re-queried https://github.com/HabitRPG/habitrpg/blob/develop/public/js/app.js#L112

Unless we can remove a lot of these, especially queries we could use caching here...
