### ISSUE TITLE
Challenge tasks don't update at all

### ISSUE THREAD

**Issue by elprohabro** [HabitRPG/habitica#1743]
Challenge's dailies and to-dos don't update on main page and remain the same even after multiple editing in Challenges section. Refreshing and logging in/out doesn't help.

Edited version is well saved in Challenges section. But old version remains the same on main page.

**Comment by lefnire** [comment]
I have a fix ready https://github.com/HabitRPG/habitrpg/commit/7161ddf70ebe9f054390d3cd4e70ef5963c8e9b2. Waiting for NPM to come back https://twitter.com/npmjs before I can push

**Comment by lefnire** [comment]
fix pushed
