### ISSUE TITLE
jquery.cookie is used?

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1744]
Or we can remove it?

**Comment by lefnire** [comment]
I believe we're using it. IIRC we needed _some_ sort of session, just to bypass the splash page, since the website is 100% using the API. See `middleware.js:splash()`, it was kinda a hurried approach, so if you can think of an alternative doooo eeeet

**Comment by paglias** [comment]
Ok, I checked and it's not used. there aren't cookies just session set server-side so it's safe to remove it

**Comment by lefnire** [comment]
@paglias looks like bootstrap-tour requires jquery.cookie, even if it doesn't use it (we're using localStorage tmk). http://gyazo.com/b402fcebf03a9e590f2e8b5e4ee63b19 . Can you add back in?

**Comment by paglias** [comment]
Yes, i noticed that. I added it back some time ago, don't remember the
commit but it's in public/manifest.json

**Comment by lefnire** [comment]
Ah, I'm stupid - npm & bower. _face palm_
