### ISSUE TITLE
Very strange and important bug :(

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1746]
Hello, 
this morning I reloaded my page, but I had an error 500. I tried multiple times and it still didn't work, so I decided to log out then log in. 

I log out, click on "Play" button, enter my username and password, click "Connect"... Nothing happens. The button doesn't respond. I close the login prompt, the page finally loads and I got this : 

![bugg](https://f.cloud.github.com/assets/4671953/1465523/918d011c-4562-11e3-9742-49be3930a939.PNG)

My character is MllePandaRoux, instead of being displayed on the left, I'm displayed with my own party... My todos are not here, my settings are not here, but my party and my guilds are. 

I tried to log out and log in again, but I have the same problem ("Connect" button doesn't react, same strange display)

**Comment by MllePandaRoux** [comment]
Same problem as #1745 but I didn't see his post.

**Comment by paglias** [comment]
Follow on #1745
