### ISSUE TITLE
main interface columns don't grow to fit ads

### ISSUE THREAD

**Issue by BruceWilliams** [HabitRPG/habitica#1747]
When I view the front page of the habitrpg site, I see four columns: habits, dailies, todos, and rewards. The ads on the bottom of the columns stick out the right side of the columns and overlaps the adjacent column (see attached picture). I expect the columns to be wide enough to fit the ads; and for my current browser width, I'd expect this to force a reflow to the stacked two-column view. (I see the two-column view if I narrow my browser window a bit, so I know the UI is able to do this.)
![habitbug](https://f.cloud.github.com/assets/389656/1466398/8d866622-4570-11e3-9f82-e5fe3d2e0fbb.png)

**Comment by Shaners** [comment]
those ads...

**Comment by litenull** [comment]
Hahahahaha

**Comment by deilann** [comment]
If this is still an issue folks are having, please reopen/comment.
