### ISSUE TITLE
Dailies Disappeared?

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1749]
I deleted a couple of obsolete dailies this morning (leftover from house-sitting this weekend)... and then realized that about a fourth of my normal dailies had disappeared, too!  They were all in totally different spots from the house-sitting dailies that I deleted - the house-sitting dailies were right on top, and the other dailies were scattered through the list - so I don't think I accidentally deleted them. Even my dark-red-duel challenge daily, which was at the BOTTOM, is gone. Is anyone else having this problem?

**Comment by lemoness** [comment]
OH thank god, they didn't disappear - when tags came back, the tags on some of my dailies disappeared, so they didn't show up in any of my tag lists. I can just manually re-add their tags. PHEW!!!!! What a huge relief.

**Comment by lemoness** [comment]
You can probably close this unless anyone else complains about tags disappearing on dailies. Sorry for the moment of terror!

**Comment by lefnire** [comment]
ye ol' http://community.habitrpg.com/content/im-missing-some-or-all-my-tasks

**Comment by lemoness** [comment]
I know!!!!!! How embarrassing that I fell for it. It's because usually all
my tasks are tagged to the nines. Ironically, it was when they DIDN'T show
up in my tags that I panicked!!!
