### ISSUE TITLE
[Suggestion] Day total for each habit, reward

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#175]
For each habit, reward (or any future item types that could be clicked multiple times) show a total # of clicks for the day, perhaps where the current edit, delete and progress bar buttons are. 

This would help with [accuracy](https://github.com/lefnire/habitrpg/issues/6#issuecomment-11802731) and also serve for encouragement (4 sessions of study/work done) or a deterrent (been having a lot of cake lately). 

The lack of a tick mark or grey/green/red shading seems to suggest no progress with a given habit. 

This request is for the individual items, unlike, but related to the request for a full log of habits (#6 and #55), a feature I would also appreciate.

**Comment by hookang** [comment]
You can kind of see this with the graph, but sure it could use some improvements. 

Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
[Habit/Reward Totals](https://trello.com/c/uaIl9x5r) added to Trello.
