### ISSUE TITLE
Challenge To-Dos Not Accurate Depiction

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1751]
I went to go check out my competitor's progress in the Pixel challenge by clicking on their name - and was horrified to discover that they'd done every single To-Do except for the hue-shifting one!! I ran around in a panic, frantically trying to rearrange my schedule ("I'll pull an all-nighter fixing jaggies!") - until I clicked on my name, and saw that my display was identical and claimed that I, too, had completed nearly everything when in fact I had completed almost nothing. Sure enough, when I clicked on Shane's name, I saw the same thing.

The to-dos in my task list on the main page are accurate, but the progress report ones are not. This makes it difficult for me to decide exactly how much sleep I should trade for pixel art.

**Comment by Shaners** [comment]
Yea for some reason it is just showing the last to do (so at the top) I added to the challenge for everyone when you click on them. I've tried rearranging those to dos since they were in the wrong order but it doesn't seem to stick. Going to try rearranging and changing the tag by 1 character and see what happens.

**Comment by SabreCat** [comment]
Not sure if this is the same thing I'm seeing--only the first task of each type shows up when peeking in at a participant's status. I created a Pomodoro challenge today, which looks like this (not sorted the way I wanted it to be, but that's another known issue):

![screenclip](https://f.cloud.github.com/assets/4501321/1488887/e6030b66-475a-11e3-9c58-98317434a8a2.png)

However, if I click any participant's button, I only see the top Habit and the top Daily:

![screenclip](https://f.cloud.github.com/assets/4501321/1488898/012223a0-475b-11e3-954a-309516c01d7a.png)

...is that the same thing? If not, I'll create a separate ticket.

**Comment by Shaners** [comment]
Yea I believe it's the same thing.

**Comment by lemoness** [comment]
Looks just like it to me.

**Comment by lefnire** [comment]
Ah, looks like `$elemMatch` will only return the first matched array subdocument. I'm gonna have to use aggregation to get multiple array elements matching "in this challenge" criterion. [Offending code](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/challenges.js#L70...L72), [issue background](http://stackoverflow.com/questions/19696282/make-elemmatch-projection-return-all-objects-that-match-criteria). Don't worry, it's a benign bug - once we fix this query, things will show properly.

**Comment by lefnire** [comment]
I pushed the fix. It has poor performance (filtering at application-level), and needs revisiting - but we'll cross that bridge later. TMK this ticket mentions two issues: (1) tasks getting copied from aggregate progress (#1729), (2) participant modals not showing all tasks. # 1 was fixed a while back, I'm closing this ticket as a fix for # 2. Re-open if I'm missing anything
