### ISSUE TITLE
iOS w/o Inn, issues with dying?

### ISSUE THREAD

**Issue by Laydeneko** [HabitRPG/habitica#1754]
I forgot to 'check-in' at the inn before I left for vacation on Friday.  Saturday morning (Friday night?), I tried logging into the Inn, but there wasn't an option for this when I was using the app, and I never did get the website to load.  

Later Saturday, when I broke down to spend my gold and get a potion, I had the message that I was dead.  After I bought the potion.  Now the app keeps flashing that I am dead, but it shows I do have HP, and it is going down as I'm not completing tasks.

**Comment by DanielTheBard** [comment]
Yep, there's no check in tavern option yet for the iOS app. Bit of a problem. Not sure about the flashing dead part though.

**Comment by deilann** [comment]
This is a planned feature on the Trello card-- let's take it there.

**Comment by lefnire** [comment]
This is actually in the app now, settings tab
