### ISSUE TITLE
Can't enter party

### ISSUE THREAD

**Issue by edmilsonrobson** [HabitRPG/habitica#1756]
Chrome 30.0.1, userID: "ryanmts".

I just can't enter my friends party. I click on "accept" and it seems fine, but when I leave the page and come back, the "You're invited to <party name>,  Accept/Reject" screen appears once again.

Awesome site, btw :)

**Comment by paglias** [comment]
After you click "accept" the party is shown? Also could you check that
the request has been completed (there's a blue loading bar at the top
when a request is being made) and also if there's any error in the
console (ctrl+shit+j to open in on chrome)?

2013/11/5, Edmilson Rocha notifications@github.com:

> Chrome 30.0.1, userID: "ryanmts".
> 
> I just can't enter my friends party. I click on "accept" and it seems fine,
> but when I leave the page and come back, the "You're invited to <party
> name>,  Accept/Reject" screen appears once again.
> 
> Awesome site, btw :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/1756

## 

Matteo Pagliazzi - paglias.net

**Comment by edmilsonrobson** [comment]
After a few minutes or so the page "remembered" my choice and my party appeared at the top of the main page. Weird... :S 

But thanks :)
