### ISSUE TITLE
Can't see days active for Challenge dailies

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1758]
When previewing a Challenge, or once I've signed up for it, the Dailies don't include information on what days they're active. I created a Pomodoro challenge today, which has its stuff active on weekdays by default, but all I see on the subscribed task is this:

![screenclip](https://f.cloud.github.com/assets/4501321/1488907/60d75bee-475b-11e3-84d6-5b2795d6cdbe.png)

**Comment by Everyst** [comment]
I think this is so that participants can't change the days. You can change them from the mobile app, however (which I believe is a bug so I reported it).
They could be made visible but not editable maybe?

**Comment by SabreCat** [comment]
Agreed: visible but not editable is the way to go.

**Comment by paglias** [comment]
Fixed, @Everyst I'll push a similar fix for mobile now
