### ISSUE TITLE
registration failed

### ISSUE THREAD

**Issue by ibvee** [HabitRPG/habitica#176]
Registered on the website. Started to make my own screen. After a while the connection was lost. Tried to log out and log in again. Was greeted with a "username not known" and an "invalid login" message. 

Tried this twice. Same thing.

**Comment by mleon246** [comment]
Ive got a similar issue... see #117

**Comment by StanLindsey** [comment]
Are both of these issues still occurring? Can you re-register or does it say the user already exists?

**Comment by ibvee** [comment]
I managed to register now :) However with a different email address, as the
other address 'already existed'.

**Comment by lefnire** [comment]
ibvee - sorry about that man, if you email me your username or email
address you used originally i can try to restore your account,or if you
prefer delete it

**Comment by ibvee** [comment]
You can delete it, it's working fine now with the other mail adres :)

Love what you're doing!

Is there a way I can send you my email adres without putting it here in the
public?

**Comment by lefnire** [comment]
Yep - tylerrenelle at gmail

**Comment by horusofoz** [comment]
Issue resolved as both users now able to register accounts.
