### ISSUE TITLE
Mobile app challenge dailies can have their active days changed

### ISSUE THREAD

**Issue by Everyst** [HabitRPG/habitica#1760]
On the website you can't change what days your dailies gotten from challenges are active. But you can change them from the mobile app (running on Android), which sets them for the website too. It's neat to be able to change them but probably not intended behaviour.

**Comment by paglias** [comment]
fixed in https://github.com/HabitRPG/habitrpg-mobile/commit/82fc5dd0791c212829d0a861e2ba2d6cf808cfe4, may take a while to land on google play and the app store (1 week more for ios usually)

**Comment by lefnire** [comment]
awesome thanks @paglias! I'll cut a release after we get contrib gear in there too, should be today
