### ISSUE TITLE
Party Chat Error 500 (and party accept invitation)

### ISSUE THREAD

**Issue by filkaris** [HabitRPG/habitica#1764]
User ID: f210735b-1bea-48ab-a7a3-d3e690a8dde7

Google Chrome Version 27.0.1453.110
and the same error occurs in 
Mozilla Firefox 25.0 (for ubuntu)

I get this error when I try to "Send Chat" in the party.
![screenshot](https://f.cloud.github.com/assets/1624978/1500780/ddf9649e-487f-11e3-85ff-34dfb1bde25c.png)

The Console shows this:
![screenshot-1](https://f.cloud.github.com/assets/1624978/1500792/28e2513c-4880-11e3-8737-27379b609769.png)

A friend of mine got THE SAME error when trying to invite someone to the party.
The invitation got sent though, inspite the error.
Now, the person who was invited tries to accept, and gets the SAME error...
(I dont know what their consoles show, only the red window is the same)

What's going on?

Edit: I should also mention that this has been going on for 3-4 days now.
Before that everything was working properly

**Comment by filkaris** [comment]
I installed HabitRPG locally and I can't reproduce the error with sample users and chat texts. 
(obviously I don't have access to the original database)
I am a programmer and I can help debug this. What more can I do??

**Comment by paglias** [comment]
If you can reproduce this on HabitRPG.com then before sending a chat
message open the developers tools in chrome and switch to the network tab.
Then try to send the message, a new entry under the network tab should
appear in red, click on it and see what does the response contains

**Comment by filkaris** [comment]
{
 "err":{
           "message": "Cast to number failed for value \"[object Object]\" at path \"_v\"",
           "name":"CastError",
           "type":"number",
           "value":{},
           "path":"_v"
       }
}

**Comment by paglias** [comment]
@phil230 thanks very much! @lefnire is this the same as the other cast errors?

**Comment by filkaris** [comment]
You're welcome!
Here is the correct message (with git markdown)

```
  {
    "err":{
      "message":"Cast to number failed for value \"[object Object]\" at path \"_v\"",
      "name":"CastError",
      "type":"number",
      "value":{},
      "path":"_v"
    }
  }
```

**Comment by lefnire** [comment]
woa! why is Group._v trying to get set as an object? I just ran a cleanup migration, see if it's fixed and we'll need to investigate why _v isn't a number here. 

@paglias random note: I forgot we have `Group._v`, we could probably use that for a cleaner chat sync method

**Comment by paglias** [comment]
@lefnire couldn't it be user._v since it's modified when accepting a party invite or sending a chat message?

**Comment by lefnire** [comment]
Ah that makes sense... but does it modify when sending a chat message? I ran the script on both users and groups in any case, but I'll keep that in mind - looking at User._v

**Comment by paglias** [comment]
yes, it modifies user.party.lastMessageSeen

**Comment by filkaris** [comment]
Guys the error is gone!

I can post normally in the party chat, and my friend has successfully joined the party!
Thanks a lot! :D

Out of curiosity, what was the problem? (I want to contribute in the future, so I want to understand the code better  :) )

**Comment by filkaris** [comment]
Never mind, I saw the commits!

@snicker you are the best!

**Comment by snicker** [comment]
Thank you for the nice words @phil230, but I do not think it was my fault that the problem is fixed, as much as I would like it to be ;) I added some features for nickname autocompletion

**Comment by filkaris** [comment]
Hmm... You fixed _chatMessage by turning it into message.content and I thought that was it. But now I realize this is only on develop branch... When I go to HabitRPG.com (is this exactly like the master branch?) I see that _chatMessage is still there. 

How come it's fixed now?? 
@lefnire did you do something?

**Comment by paglias** [comment]
A migration has been run on the database to remove all the NaN values from
user._v and group._v and that were causing an error since the value for _v
must be a number.

**Comment by filkaris** [comment]
I see... awesome! It makes sense that it was a database thing :) Thanks
@paglias
You guys can close the issue now since it's solved.

On Wed, Nov 13, 2013 at 5:13 PM, Matteo Pagliazzi
notifications@github.comwrote:

> A migration has been run on the database to remove all the NaN values from
> user._v and group._v and that were causing an error since the value for _v
> must be a number.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1764#issuecomment-28402153
> .

## 

Filippos Karailanidis

**Comment by lefnire** [comment]
Thinking back, maybe I didn't run this migration in the past after all.. could be this recent migration puts is to good, because I've checked everywhere I could think of for `user._v` & `group._v` sets, and everything looks fine. We'll close, and keep a close eye out for a recurrence.
