### ISSUE TITLE
Beast Master Achievement

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1766]
After reaching 90/90 Pets the Beast Master achievement is not unlocked.

**Comment by lefnire** [comment]
Oh my god! Your'e the first!! Ok, I'll look into this. We should celebrate you in tavern though :) Gimme your UUID for now so I can manually set your achievement while looking into the issue

**Comment by ghost** [comment]
I don't think I deserve the achievement, I was cheating to see if the achievement worked.

**Comment by paglias** [comment]
@Deterous it's still to be implemented, see https://github.com/HabitRPG/habitrpg/issues/1543

**Comment by lefnire** [comment]
@Deterous scoundrel! JK, glad you tested it :)

**Comment by ghost** [comment]
With the trigger new day button, it took ~600 virtual days to get all 90 pets.

**Comment by Shaners** [comment]
haha

**Comment by lefnire** [comment]
Yeesh, I'd better remove that button. Only other time someone mentioned using it was on accident

**Comment by ghost** [comment]
The achievement has appeared on my profile, so it appears to be fixed.

**Comment by joelmaxuel** [comment]
User ID:d6e1290f-5ec3-42d9-b73b-6a51b4824a93, just reached 90/90, yet no achievement awaited.  Although I did purchase an egg and three hatching potions to get to 90/90, not sure if that makes a difference. @lefnire
