### ISSUE TITLE
Dailies randomly not resetting with new day

### ISSUE THREAD

**Issue by UffishThought** [HabitRPG/habitica#1767]
Sometimes (like today) when I log in in the morning, all the dailies I checked off the day before are still greyed out. They should reset at 2am, but occasionally (maybe once every week or two)  they don't. Any idea why not?

**Comment by paglias** [comment]
Did you checked them after midnight maybe?

**Comment by UffishThought** [comment]
Some of them, sure. But not all of them. And I should have until 2am to check them, anyway.

**Comment by paglias** [comment]
ok follow on #1057
