### ISSUE TITLE
Add gems to local database without paying

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1769]
I'd like to be able to use gems on my local copy and and be able to take screen shots for the wiki. Is there a way to do this?

**Comment by lefnire** [comment]
you'll have to enter a MongoDB query:
`db.users.update({_id:YOUR_ID},{$set:{balance:10000}})`

**Comment by paglias** [comment]
@lefnire the addTenGems route isn't executed... https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/api.js#L40, it isn't registered as a route because unless tou export in the shell `NODE_ENV` manually it is undefined, we could use `app.get('env')` but `app` isn't accessible from the router actually. Would it be ok use `nconf` to get the environmento from `config.json`?

**Comment by bobbyroberts99** [comment]
Sorry that I gotta ask so many questions, but where do I type db.users.update….? I checked out mongo docs, but I don't see it.

**Comment by lefnire** [comment]
@paglias yeah, nconf is legit to use there. @bobbyroberts99 you'll want to use [mongoshell](http://docs.mongodb.org/v2.2/mongo/). You on mac or windows?

**Comment by paglias** [comment]
@bobbyroberts99 from the terminal you should be able to access the mongodb shell typing `mongo` then you should select the database where habitrpg is hosted, in my case it's `habitrpg`, using `use dbName` then you should be able to type `db.users.update....`.

**Comment by paglias** [comment]
@bobbyroberts99 now if you update your local copy to the latest commit you can use the button in the footer to add 10 gems with a click

**Comment by bobbyroberts99** [comment]
I synced develop and reloaded and still get a 404.

For mongo, I get this

![name001](https://f.cloud.github.com/assets/4084120/1507244/bc038a86-496f-11e3-89a9-5b40b512d7c6.jpg)

How do I fix those warnings?

**Comment by lefnire** [comment]
Gotta put UUID in quotes. ({_id:"23b…"

**Comment by bobbyroberts99** [comment]
Still have 0 gems. Does it have anything to do with the soft limits warning?

![name002](https://f.cloud.github.com/assets/4084120/1507288/c76f592e-4972-11e3-991d-e4f6e835c33c.jpg)

**Comment by lefnire** [comment]
instead of:

``` shell
$ mongo
> use dbname
```

you want `dbname` to be actually `habitrpg`. Here's a shortcut entry anyway:

``` shell
$ mongo habitrpg
```

**Comment by bobbyroberts99** [comment]
Thanks Tyler, that worked. I'm rich!

Now to the next problem…

I'm playing with habitrpg/views/shared/modals/new-stuff.jade but the copy I have (after syncing develop) doesn't have the most current text that's on the website. 
Here's how I set up my local copy:
1. Forked Habitrpg/habitrpg (Develop branch)
2. Clicked the Clone in Desktop button on GitHub

I've done this a couple of times. Removed the clone and deleted the files and repeated the process. 3rd time is not a charm.

Now if I switch to Master and then Clone in Desktop, I DO get the current files. Can I use these files and just push back to a different branch (develop, for instance, or one that I create for wikia changes)?

The README says to clone develop. What am I doing wrong?

I really appreciate your being so patient. I know you're busy and I'm just a wannabe dev. It's nice of you. Please take all the time you need. When I finally get it figured out (almost there I think), I'm going to start trying to add links to icons and modals that go to specific wikia pages.

**Comment by lefnire** [comment]
You may want to go through a basic Git tutorial. [This one](https://help.github.com/articles/fork-a-repo) has some basics on forking/pulling etc; what you want to do if there are changes remote is `git pull` (or there should be a button in your UI for pulling). 

Master is pretty far behind right now, all this sprinting and we haven't stabilized lately, so I'm running both herokus off develop. So no, you're not gonna wanna push from master. Do some tutorialing around on Git to see if you can get the latest develop pulled

**Comment by bobbyroberts99** [comment]
Tyler, I think I'm all set. I basically deleted everything, reforked and cloned dev (not with the command line though).

I then did npm install again (which I think is all I really needed to do).

Anyway, the file that wasn't current now matches what's live on beta, so I think I'm good to go.

I had done the tutorial that you sent and Try Git on Code School. Nick Gordon I ain't, but I'm learning, slowly. Thanks again for your help.

**Comment by lefnire** [comment]
@bobbyroberts99 great, you're doing fantastic :)
