### ISSUE TITLE
[Suggestion] Advanced Scheduling for Todos

### ISSUE THREAD

**Issue by jacobwolfe** [HabitRPG/habitica#177]
I just started classes today and I realized that a lot of my courses have an assignment schedule with due dates. I would be convenient if I could schedule Todos to appear at a specified time away from it's deadline (perhaps a Google Calender event sync?). It would be a lot more motivating if you saw that your hero is loosing a lot of hp because you are close to the deadline on that paper you haven't finished yet. Keep up the good work!

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
See [Urgency: Dates & Deadlines](https://trello.com/c/i6kXvNY2) and [Google Calendar](https://trello.com/c/vtJv2DyY) and/or [Google Tasks](https://trello.com/c/l7UsVY8E)
