### ISSUE TITLE
Double gems!

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1771]
When contributor rewards went live, I got 40 Gems, far more than the 14 expected for tier 7. So I used the admin console to reduce my Gems total to 14. This morning, when I logged in, I had 28 Gems. Somehow they got doubled...?

UID 7f14ed62-5408-4e1b-be83-ada62d504931 on beta.habit.

I'll keep an eye out, see if my 28 becomes a 56 next cron... xD

**Comment by lefnire** [comment]
I just gave you a boat load because you're Sabe. You fixed them, then I actually ran a migration to give all the current contribs gems according to their level. Because you manually set yours before that migration, it didn't take that into account. Nobody else (maybe save Lemon & Paglias) were effected

**Comment by SabreCat** [comment]
Oh, hilarious. Thank you, then! OK, I'll reset my Gems to the 40 you wanted me to have!

**Comment by lefnire** [comment]
alas, can't reset gems in admin anymore. will add back in, in the future - for now, upping a contrib level manually handles gems. I can set in DB for you if you want :)

**Comment by SabreCat** [comment]
Ack, yeah, I just discovered that. Please do, if that's your intent!

**Comment by paglias** [comment]
Not doubled but gone from 64 to 80

**Comment by paglias** [comment]
Oh, didn't see the comments following @SabreCat 's one

**Comment by bobbyroberts99** [comment]
I should have 33 but now have 39. Stats say I'm a "Friend" but I can't tell if 1 or 2. Seems like if I'm Level 2 that I should just have received 2 (for a total of 35).

**Comment by breadstrings** [comment]
When I achieved contributor level 1, I got two gems, when it should have been just the title (2 gems come at contrib level 2). Bug?

**Comment by breadstrings** [comment]
I just noticed that I have the same problem as Bobby. Not that I'm complaining. ;) But it seems wrong to have 2 extra unearned gems.

**Comment by lefnire** [comment]
The algo gives 2 gems for every level. Let's just update the wikia / website sidebar wording
