### ISSUE TITLE
Saving an edit to an active Challenge turns user buttons into dashes

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1772]
If you own a challenge, have some participants, Edit the challenge, and Save, the "How's Everyone Doing?" area collapses the users' buttons into little dashes without names:

![screenclip](https://f.cloud.github.com/assets/4501321/1507095/ea6841b6-4963-11e3-8e0d-d9efec45dd3d.png)

Win7 - beta.habit - Firefox - No JS errors.

**Comment by lefnire** [comment]
Ah, it's just ngResource not returning the full populated challenge object on update. Refresh will fix, will look into soonish

**Comment by deilann** [comment]
Is this still a problem?

**Comment by SabreCat** [comment]
@deilann: Looks like under Bootstrap 3, the people straight-up vanish, rather than turning into dashes.

**Comment by crookedneighbor** [comment]
Looks like this is fixed now. Tested in Firefox. Re-open if still occuring.
