### ISSUE TITLE
"Close" is not a good name for button to end Challenge

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1773]
When you Edit a challenge you own, you see three buttons: Save, Cancel, and Close. 

![screenclip](https://f.cloud.github.com/assets/4501321/1507103/821326f2-4964-11e3-81e3-a994e23218b9.png)

I was perplexed by these at first, because "Cancel" and "Close" mean very similar things, by UI convention. I wondered why we had two buttons to do the same thing, and worried that Close wasn't clear whether it would save changes or not. So I tried clicking Close, and discovered it meant "end the challenge!" I'd suggest these changes to make the function more apparent:
- Change the button title to "End Challenge", "Conclude", or "Conclude Challenge"
- Rather than put it as a button during an Edit, have this button be adjacent to Edit when you open up the Challenge to view. Perhaps shade it red to show its importance and finality.

**Comment by lefnire** [comment]
fixed

**Comment by lefnire** [comment]
(woops, didn't tag properly in commit msg: https://github.com/HabitRPG/habitrpg/commit/8c83bc6ad2fc167a558d120e47f6917655e0f525)
