### ISSUE TITLE
Difficulties are available to assign to Rewards

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1776]
Difficulties are a multiplier on task value, for how hard a Habit, Daily, or To-Do is. They have no effect (or obvious meaning) for Rewards... but you can still edit them:

![screenclip](https://f.cloud.github.com/assets/4501321/1507298/a7b47d02-4973-11e3-8117-97c257b42e44.png)

**Comment by DanielTheBard** [comment]
Yup, seeing that as well.

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/e711258ced7e946a15b7305be0aaa0d7d9e4a0df
