### ISSUE TITLE
Pets overhaul (mounts prep)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1779]
@paglias & @Shaners, heads up on a big overhaul coming to Pets: https://github.com/habitrpg/habitrpg/compare/ddd45d76d4c169e91defd8c81a01ec58ba4a0c62...085919c000d87ef48165b5461d94e21e14b35bf6 . The important piece is the [UserSchema.items refactoring](https://github.com/HabitRPG/habitrpg/commit/60421a85cccd0250609be42ef8a21eb436df635d) (the rest of the code simply supports this change, so you can ignore it for now). The takeaway is we're migrating item attrs from arrays to objects. (note, the diff urls may change as I `force push`, I'll update on the ticket if I do).

The biggest reason for the refactor is that Mounts is coming, and we need to keep track of pet "Growth Points" - so it's no longer sufficient to store pets as an array of strings, instead we store them as key=>value like `{"BearCub-Desert":15}`. The number is Growth Points, 0 means "does not own". Changing eggs & hatchingPotions to work consistent with this allowed me to get [stacking](https://trello.com/c/IDWPwF7d/310-stacking-inventory) for free ([screenshot](http://gyazo.com/dce00137ae63325509ec7cd951f9551e)). Turns out this overhaul was a big improvement on clean code, sensical organization / storage format (especially for item-lookup), and even performance. There were a lot of cases we had commented "why isn't this updating in the UI?" which the overhaul fixed, and I was able to remove quite a few workarounds. I think this format will make our lives much simpler for managing pet stuff.

The only thing I'm not quite sure on is custom pet / mount names. We could feasibly store pets as:

``` javascrript
items.pets: {
  // Current: 'Dragon-Red': Number
  'Dragon-Red': { owned: Boolean,  points: Number, name: String }
}
```

But I think this introduces a lotta cruft & extra logic (in HTML & controllers) for a seldom-requested feature. Should we add that in now and deal with the annoyance, or should we cross that bridge when the time comes?

Also, this overhaul will require a (possibly heavy) update to mobile, so I think I'll wait till  either mounts feature is complete, or at least we're totally solid on the new architecture, before cutting mobile (then waiting for iOS to land first), then rolling to develop

**Comment by Shaners** [comment]
Hmmm I feel like we need to map this out, it may make the solutions more obvious. I can give it a go but I'm not too familiar with mongo so I'll have to learn a bit to map the physical data model.

To do:
- Identify entities
- Define business rules (relationships)
- Define cardinality 
- Magic Box View (conceptual model)
- Logical Data Model (ERD)
- Physical Data Model

**Comment by lefnire** [comment]
Oh, you mean for the possible "naming pets" component. Yes, good call

**Comment by paglias** [comment]
@lefnire just one thing, does this mean every user will store all avalaible pets as `petName: 0` until they own it?

**Comment by lefnire** [comment]
@paglias Not at the moment. I didn't add a `{'default':0}` property, so right now it stores as: `eggs: {Dragon: 3, Cactus: 1}` (only storing what's owned) and if I hatch my cactus egg, it stores as `eggs: {Dragon: 3, Cactus: 0}`. Angular views treat `null` & `0` both as falsey, so it works out well.

So this format is more lean - only storing what we need to store. If we decide we should have all keys accounted for, and store 0 by default, we can add `{type: Number, 'default':0}` to the items. The `user.items` attrs currently following this scheme are: eggs, hatchingPotions, pets, mounts, food
