### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by SteveSmith3** [HabitRPG/habitica#178]
When Iog in the page it says game over. I hit ok and then says "unable to reconnect - reload" If I reload it says game over again and then asks me to reload. It does this forever.

**Comment by hookang** [comment]
It might be a stability thing @stevesmith3 try again. If you're still having this problem let us know. Here.

**Comment by handcuff** [comment]
I have a problem with that too. I keep on dying and i have to reconnect every time.

**Comment by Zequez** [comment]
Well, I don't die, but I still can't connect. Tried from home and work computer, so I don't think it's my end.

**Comment by castor-troy** [comment]
I like the site very much, but this is very frustrating. I am so much addicted that I am checking it every hour to see if it works.

**Comment by Paragonid** [comment]
I have this "Unable to reconnect – Reload" issue now. So can't save any changes.
Browser Troubleshooting Info http://pastebin.com/bfwKiGUj

**Comment by lefnire** [comment]
I'm looking into it this. Very strange, loads for me, server resources at a minimum (obviously not doubting with so many chiming in, just thinking out loud).

**Comment by Zequez** [comment]
Maybe it's unrelated, but in the console you can see "fatalErr Unauthorized", and it points to some part of the Socket.io code. It's all packed so I can't backtrace very well.

Edit:

One GET request to: `https://habitrpg.com/socket.io/1/xhr-polling/AAAAAAAA?clientId=XXXXXXXX&t=1358954784006` returns `5:::{"name":"fatalErr","args":["Unauthorized"]}`. The status code is 200 OK.

Then there are 2 subsequent POST request to the same URL (different time), both with response `1` and status code 200 OK.

**Comment by Paragonid** [comment]
here is console output http://pastebin.com/zNLafHER

**Comment by lefnire** [comment]
Awesome! That will help, can you try deleting your cookies and re-logging
in?

**Comment by lefnire** [comment]
You can use [web developer](https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm?hl=en-US) extension for that if you're on chrome

**Comment by jspivack** [comment]
I was having this issue very frequently (every minute at least) and just cleared my cookies and re-logged in. Can confirm that it looks to be running much smoother now. I'm not getting the "Unable to connect" error anymore at least

**Comment by lefnire** [comment]
confirmed then, it's an auth issue. For one reason or another sessions got booted, but it's not logging users out fully. diagnosing

**Comment by Paragonid** [comment]
Sorry, pastebin seems to be down O_o
here's console output just from the beginning without any cookies http://sprunge.us/GJga

**Comment by lefnire** [comment]
I'm gonna restart the server real quick

**Comment by lefnire** [comment]
is this still happening for anyone if they clear their cookies? what about after that server restart? i'm looking at detecting busted session & clearing cookies if so

**Comment by jspivack** [comment]
Had to clear cookies again after the server restart, but it's working well now

**Comment by Paragonid** [comment]
Sorry, still can't hold connection
upd.: console output, cookies cleared http://pastebin.com/GLAzdbK2

**Comment by SteveSmith3** [comment]
This bug shows up for me in Ubuntu on firefox and chrome, also in Windows 7 on firefox (dual boot machine).

Just cleared out all history in Firefox in Windows. I get the "Unable to reconnect – Reload" message without logging in.

Console shows "fatalErr Unauthorized" for https://habitrpg.com/gen/SiXUaOe5_PoGndpQAw65XA.js line 3.

Is that some kind of generated JavaScript? I suppose I could send you the script file itself if its somehow unique to me.

**Comment by lefnire** [comment]
it's derby-generated min/concat javascript. I tried deleting `public/gen/*` and restarting server, looks like that's not helping. I'm looking into upgrading socket.io right now

**Comment by jspivack** [comment]
It's showing up again for me too

**Comment by lefnire** [comment]
got it! 9924edcd959fe75c4411bb151f73285054d499de - strange bug, I think it has to do [with this](https://github.com/codeparty/racer/issues/57)

**Comment by ghost** [comment]
It is back.
