### ISSUE TITLE
Could use select/clear all in Challenges navigation

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1781]
If you're a member of several groups, it takes several clicks to filter down the Challenges list to just one group you're interested in (say, your party, or the Tavern). It'd be handy to have a select/deselect all button or checkbox so you can get the full list / clear the list and select one, in just a couple of moves.

**Comment by lefnire** [comment]
fixed

**Comment by SabreCat** [comment]
:+1:
