### ISSUE TITLE
Angular 1.2.0 stable is broken

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1786]
@lefnire just a reminder that angular 1.2.0 is broken.

They "decided" that all properties starting with a `_` are to be considered private so they can't be used inside the templates.

It brokes a lot of thing and I don't feel we can change this easily.

The error is this http://docs.angularjs.org/error/$parse:isecprv?p0=_id and I really hope they'll revert the commit (https://github.com/angular/angular.js/commit/3d6a89e8888b14ae5cb5640464e12b7811853c7e) because it's completely preventig us to upgrade.

**Comment by lefnire** [comment]
Ohhh shoot.. Derby made that decision in 0.5 as well, yeah we're using `._` in many places. Good to know, thanks for the heads up - I'll start thinking about this

**Comment by lefnire** [comment]
You know what - I was thinking, "well we can remove all our private fields from the app and come up with something cleaner" - and then remembered we have User._v. We're gonna have to wait this one out and follow that convo.

**Comment by paglias** [comment]
Hopefully this pull request will be merged in 1.2.1 https://github.com/angular/angular.js/pull/4859/

**Comment by paglias** [comment]
Reverted in 1.2.1 :+1: http://blog.angularjs.org/2013/11/angularjs-121-underscore-empathy.html

**Comment by lefnire** [comment]
Wooo!
