### ISSUE TITLE
Daily day selection backwards after Inn stay

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#1787]
I just got out of the inn and noticed many of my dailies were set to the opposite days. I noticed because there is one I do only on Sunday was grayed out on Sunday but not all the other days. It was not the only one that is backwards. 
1. My Sunday Daily had M-Sat selected instead of just Sunday.
2. The daily I have turned off on Sunday and 'on' rest of days was opposite than should be.
3. There were 2-3 others but I have fixed them and do not remember which ones they were.
4. I do know all of the every day dailies were fine; and, 
5. The ones I have selected weekdays only were fine.

Sorry do not have a picture. Everything else on my account seems fine except those 4-5 Dailies that were different. Sorry again for not keeping track.

**Comment by Alys** [comment]
I'm closing this because I believe it was fixed quite some time ago. I haven't noticed it happening to me. It can be reopened if I am wrong.
