### ISSUE TITLE
Halloween skins have been removed from Avatar Settings

### ISSUE THREAD

**Issue by AndreCaseyScott** [HabitRPG/habitica#1792]
Bought the Halloween skins and was under the impression that they would only be available to buy for a short time, but would stay with your character to use when you wish. Mine have since disappeared, with only the Rainbow and normal skins remaining. 

Were the Halloween skins supposed to be removed? Will they appear next year around halloween? Or is my account bugging out...

**Comment by dbueller** [comment]
Mine are also gone.  I was under the impression that they would stay but you could only buy them for a short time.

**Comment by DanielTheBard** [comment]
This is also happening to me. To my knowledge, they should still be there. Most likely a bug.

**Comment by Starfog** [comment]
I'd really not have purchased them if I knew they'd disappear, so I really hope it's a bug ... I bought gems because of them and purchased the full set. It'd be pretty annoying if you can only use them in halloween.

**Comment by lefnire** [comment]
Yep, bug. Sorry guys! Midnight haze. Pushing fix now
