### ISSUE TITLE
Not so much a bug ... just a spelling error.

### ISSUE THREAD

**Issue by suitcase76** [HabitRPG/habitica#1793]
Hey on the Chrome Extension settings page, the save to cloud option reads:

'Settigs save to the cloud?'

...rather than 'settings'

Really enjoying Habit RPG, keep up the good work!

**Comment by suitcase76** [comment]
Also in the Host Watcher section both codeacademy and khanacademy read:

codeacadamy.com
khanacadamy.org

Which I think means they wont work as productive site options. 

I realise these can be changed by the user however. Just a heads up!

**Comment by ahstro** [comment]
I couldn't find the "codeacadamy" or "Settigs" spelling errors, infact, I found the phrases where they were used and they were spelled correctly. I did however find the khanacadamy spelling errors and corrected them.
Here's the pull request: https://github.com/HabitRPG/habitrpg-chrome/pull/79

**Comment by wc8** [comment]
This should really go in the chrome extension repository, I think.
