### ISSUE TITLE
It would undo a day's worth of completed tasks

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#18]
This happened to me two or three times where I would go on the site and it would revert my account to the state it was hours ago (undo purchases and undo task/habits/daily completions. This is really annoying since you have to remember what you did.

**Comment by lefnire** [comment]
That's a terrible bug. I updated to the latest Derby core, which might help - give this recent push a shot and tell me if it makes any difference.

**Comment by nexusventuri** [comment]
I had the same problem twice yesterday. Today I added a task and an habit, got some xp for getting a habit done, refreshed the page to discover that the actions weren't saved

**Comment by lefnire** [comment]
Here's my theory:

I think what was happening here is that the app was hitting some major issues which were crashing the server (see the [last couple days'](https://github.com/lefnire/habitrpg/issues?labels=&milestone=&page=1&state=closed) worth fo closed tickets). You both had accessed the app, gotten the downloaded & running-offline version of the app, and then the server crashed. When [Racer](https://github.com/codeparty/racer) tried to sync data back to the server, the server was either down, or had been restarted with fresh sockets & sessions, disconnected from your own socket/session.

Aka, I don't think there's any specific bug causing you to lose data, I think it's that there were other more general bugs crashing the server and disconnecting your data-syncing. Try for the next couple days, if you don't hit this issue again my theory should be correct. If not, please do reopen. I'm going to keep my eyes peeled for this issue besides.

**Comment by loldude101** [comment]
Therefore I should avoid "completing" tasks without first making sure the the site is running offline? This might be the issue since I ran into this problem when I had habitrpg "pinned" (Pin Tab) on my Chrome browser, the site might have gone offline during that time and when I "completed" a task it might have not registered it.

**Comment by lefnire** [comment]
Well, now that the other major bugs should be ironed out, you shouldn't have to go to that extent. If you lose any data in the next few days, bug still exists and re-open this ticket.

**Comment by dobry** [comment]
I had the same problem yesterday and today. After using the app for a while and refreshing I had a state from few hours before. I never got any warnings that the app has no connection and is unable to synchronize with server.
