### ISSUE TITLE
Mobile Notifications

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#180]
For the Mobile version, you could add an option to add a timed notification for certain Habits, Dailies, and Todos. And for todos maybe a deadline or something and you would get warned 10 days, 5 days, 3 days, 2 days, 1 day, and hours before the deadline. This would help me a lot because a lot of my things on HabitRPG are meant to be done at a certain time.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote here for [timed notifications](https://trello.com/c/uC0MX8kg), see also [Dates & Deadlines](https://trello.com/c/i6kXvNY2) and [Disease for Missed Deadlines](https://trello.com/c/QmhxaBRE).
