### ISSUE TITLE
'Play' Button doesn't work on WP 7.8

### ISSUE THREAD

**Issue by samjross** [HabitRPG/habitica#1800]
I have a Windows Phone running version 7.8, and when I'm at habitrpg.com/static/front the big blue 'play' button doesn't do anything.

**Comment by benmanley** [comment]
@deilann I'm having the same problem on Safari on iPad mini (iOS 7.0.6) and iPhone 3GS (iOS 6.1.6). Is this happening to all mobile devices?!

**Comment by deilann** [comment]
@benmanley No. This specific issue likely be an IE compatibility issue. Your issue is likely either related to the issue I have, where my Nook can't render the site, or an iOS issue.

**Comment by benmanley** [comment]
@deilann OK. I guess I should open a separate issue then. Is there a ticket already for the Nook problem?

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2571 is where I'm tracking my
Nook issue. If I had to take a gander, I'd guess it's a javascript problem,
but it's hard to tell because checking for errors is hard on mobile.

**Comment by paglias** [comment]
Still happening?

**Comment by Alys** [comment]
The front page has been changed greatly since this was logged, so I'm closing this.
