### ISSUE TITLE
"Boot Member" hover label gets cut off (and icon doesn't use space well to start with)

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1807]
In Win7 Firefox on beta.habit, one of my Guilds' member lists looks like this:

![screenclip](https://f.cloud.github.com/assets/4501321/1537491/3db33ac2-4cc7-11e3-9cdf-d812cf5b8ba1.png)

Note that the "Boot Member" tooltip gets chopped off at the left (3oot member?). It also strikes me as odd that the boot button takes an entire line, making for a lot of extra white space.

Suggestion: Move the "boot" button so the tooltip comes up in its entirety. At my first suppose, I'd move it to be right-aligned on the same text row as the member's name; if there's worry about mouse targeting in that setup, maybe change the tooltip to dynamically say "Boot {{membername}}"?

Would need to test how it looks with really long user names, but I think that'd otherwise be ideal.

**Comment by paglias** [comment]
The icon position has been changed, if it still appens I'll reopen
