### ISSUE TITLE
Add field for personal notes on Challenge-acquired task

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1808]
It makes sense that a Challenge participant shouldn't be able to edit the fields defined by the tasks they signed up to. However, it would make sense and be useful to give the user the ability to add their own, separate comments to the task. As a use case example, in a polyphasic sleep challenge I just started, there's a Daily for "Core Sleep" that tasks the participant with hitting their target sleep/wake times--but any given participant could define those target times according to their schedule needs. At present, that information would need to be recorded or remembered outside of the task, but a separate user-editable field would be perfect.

**Comment by wc8** [comment]
This is closely related to [Challenges: Participant-Customizations (e.g. Aliases, Tags)](https://trello.com/c/XFXRoelM) so I added it to the description and checklist. 

What I’m doing for the water challenge is changing the tag name: e.g. Hydrate became 24.oz, but that only works if there’s only one short note to be made.
