### ISSUE TITLE
Add "Created" or "Owner" option to Challenge list filters

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1809]
The "Participating" / "Not Participating" options for filtering the Challenge list are quite useful, as are the group filters (especially with #1781 accomplished, yay!). One filter I found myself wanting but lacking, though, was a filter to show only the Challenges I created or am responsible for.

It doesn't fit well as an additional option on the other filter lists... it'd probably work something like the Participating filter, "Owned" / "Not Owned" / "Either"?

**Comment by deilann** [comment]
Oh god, I'd like this.

**Comment by TheHollidayInn** [comment]
Great idea! Pull request submitted: https://github.com/HabitRPG/habitrpg/pull/4842 .
