### ISSUE TITLE
[Sugestions & Questions] Icons & Avatars

### ISSUE THREAD

**Issue by superlikelikes** [HabitRPG/habitica#181]
Icons. Shop Owners. Uploading. Sharing. 

Icons for habits, rewards, option to publish.

Other users can browse anything someone chooses to publish.
There is an option to add a public entry to your own routine.

Pick a Habit!!!
Coins awarded to the publisher for every time it gets added to someone elses habits.

Searchable.

Icons fit in any 100 x 100 frame.
[currently 36 x 60]
Publishable.

Include a pixel editor. Import and edit any Icon.
Personalization.

Social. Sharable. Rewarding. Fun. Connect.
Creative. Artsy.

I see potential with this.
I see something wonderful. 

So many ideas!

:)

**Comment by hookang** [comment]
Love the ideas. Like what Steam and Valve are doing.

Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
I added a note on [Trello 9](https://trello.com/c/pxics3ZM), but I am not sure I completely understand the idea.
Related to #107

**Comment by superlikelikes** [comment]
I'll work on making a little mock up later today to better illustrate my idea.

My basic idea here is having the ability to upload our own pictures to use as icons for our profiles, habits, daily, to do, rewards... in addition to what you already have (name, description, plus/minus) . I'm a visual person. Video games are very visual (obviously)... 

<-- what is the size of my icon here in this forum? 48 x 48? That's a perfect size (to me).

To take it one step further (for example), Let's say I upload a heart icon, and make up a task to go along with it that says something like "spend 5 minutes loving everything"... after i log it into my own routine / habit, I would then have the ability to submit my icon, the task or both together to a public domain where other people can see, search for, save my icon, task or both to their own routine. 

When that happens I would get some points for that. 

This to me this is really cool because not only can I tailor it to how I am in a visual sense, I can peek at other people's habits in the public domain and find really good ones to add into my own routine. Once people get the word out that you can upload your own icons, i expect to see a lot of really cool pixel art and icon art around here and that makes everything more fun. Do you start to see what I see yet?

Let me make a mock up by editing a screen shot over what you currently have to help give a visual...
Any questions I'm just happy to be discussing it, even though it would be truly awesome if we could pull this off.
Thanks :)

**Comment by superlikelikes** [comment]
![habit rpg mockup copy](https://f.cloud.github.com/assets/3335116/100180/a0ac12bc-67f2-11e2-877a-55ee98a0a567.jpg)

I'm going to take a break for a while, but I played around with the idea... 
Imagine you can hover over certain things to get the option to upload or add/change an image, 
Imagine that as you click on a task and it opens up (like it does now) the option to submit to public would be in there...
Imagine clicking certain things takes you to another screen....

Let me know what you think - thanks for checkin it out :)

**Comment by ghost** [comment]
Hmm interesting concept but then the point of the current graphics would be
null and void.

**Comment by superlikelikes** [comment]
I believe that sticking to just the current graphics limits everyone.

There is absolutely nothing wrong with keeping the original graphics.
I encourage it. Everyone new who signs up would obviously start out with them. 

PS - with it being user created... there would be no legal issues. No one is going to sue me if i use mario as an icon on a messageboard, facebook, twitter, etc... so why would it be any different here?

**Comment by wc8** [comment]
[As far as the avatar:] There's a current plan beyond the currently visible graphics. If I understand right, the plan is for the "avatar" to change with levels, skills, etc. see #74 and #107. User chosen graphics for the avatar would conflict with that, wouldn't they?

P.S. Nice to see possibilities with the header, though. On the other hand, I wonder how the width would work in the mobile app. 
P.P.S. #97 also relevant
P.P.P.S See also the chest for items discussed here: #209

**Comment by lefnire** [comment]
Yeah, for the reason pointed out by @wc8 we can't implement this strategy
because it will conflict with the current avatar customizations plans,
which is a big part of the game experience, and also part of the business
model. Users improve their avatar visual appearance as they play. We can
talk about task icons though, what does everyone think of this?

**Comment by wc8** [comment]
I very much like the task icons.
P.S. That would be an area where custom user icons & sharing could be useful, as it is hard to find appropriate icons sometimes.

**Comment by superlikelikes** [comment]
I do understand what your current plan is. I respect it. 
I just wanted to give you an alternative to consider. 

From what I've read, it seems to me it might be a lot of work on the programmer's end:
Implementing all the customizations available for a 16 bit character and having them co-inside with your level, the equipment you buy, and so on could be a time consuming process to create, troubleshoot and to get it running smoothly. 

I could be way wrong, I am a graphic designer, not a programmer.

However, being able to choose your own avatar from your own favorite video game, (be it uploaded yourself, or chosen from other user's uploads) along with equipment being icons instead of adding it on to the graphics of the character may also take a bit of coding and trouble shooting...  but after it is set up... it might save you future effort with this. I don't know. 

I personally don't care about the avatar as it is or what equipment is really on him/her.
I don't mean to offend, at all. You've done some tremendous work here so far. Thank you for making this.
Just keep in mind you are going to have a bunch of users who look exactly the same if you do it this way and the level of individuality a user can have with it will fall short in that respect. 

Thank you very much for considering my ideas.

**Comment by lefnire** [comment]
oh, of course you didn't offend! hope i didn't sound smack-down. We'll keep this convo going, something to consider. Ps, Marle :+1: I'm glad to see many of the Habit users are Chrono fans :)

**Comment by lefnire** [comment]
also, depending on y'all opinions - we may want to put items, equipment, and stats into a Bootstrap Modal to save interface clutter, a backpack icon which brings up Equipment (like this [WoW screen](http://spicytunas.com/wp-content/uploads/2009/03/equipment-manager-1.jpg)). You can similarly click an Allie's avatar and bring up their equipment/stats.

**Comment by lefnire** [comment]
more i think on it, a custom avatar in the traditional sense (your recommendation) would be nice in _some_ location of the app. Hmm..

**Comment by superlikelikes** [comment]
Thanks! You want to buy a mousepad? JK

Seriously, this is what I would like to do for you:

I'm going to clean up that screenshot just a tad and then I'll upload on my deviantart, from there toss it i'll over to tumblr to help promote your project (fully disclosing this isn't an official screen shot, it is only my fan made concept by me).

I don't have a huge enormous following of game nerds online, but do I have a quite a nice handful of fans I would love to introduce this concept too. I plan to get this done (its on my Habits "to do"!) on Sunday. :)

**Comment by wc8** [comment]
By the way, I think it would be great if there were more variations in the avatar. There have been a few comments (here and on other sites) about disappointment at the lack of choice for complexion and gender. Boy/girl #107 will probably help, I wonder if medium and darker tones as well as a green would give a little variation without creating too much complication for the designers?

**Comment by lefnire** [comment]
Could use CSS3 Hue filter as a stop-gap.

**Comment by wc8** [comment]
Users can vote here for [Task icon feature](https://trello.com/c/FCVdjdUd). I added a version of the above image focusing on the icons for tasks to help explain the feature. (I trust that's ok.)

**Comment by wc8** [comment]
[Custom **Profile Picture**](https://trello.com/c/lrIqemFX)—to be different from user's in-game icon/avatar
Any other features to glean from this thread to be added to Trello?

See also [Market for Shared Items](https://trello.com/c/9Leb2poC)
