### ISSUE TITLE
Choose default for Challenge group drop-down if only one group filter is selected

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1810]
A cool shortcut we could include in the UI for creating a new Challenge: if you have only one group selected in the filter at the left when you click Create Challenge, have that group default into the dropdown menu selection. Nice and intuitive, and supports some odd but probably not uncommon workflows ("What's my Guild got... oh, hey, we don't have a challenge about X yet, I'll whip one up.").

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4871

Note that on the Challenges page, a guild will appear only if there is already at least one challenge in that guild. Hence the workflow described above can't be used for the first challenge for a guild.
