### ISSUE TITLE
Changing name of a task in the Challenges-tab does not change it at task-page

### ISSUE THREAD

**Issue by kalakom** [HabitRPG/habitica#1812]
I am the creator of a challenge and edited the name of a daily after creating the challenge. The new name shows up when at the challenge-tab, but it does not change the name on the main task-page.

**Comment by lefnire** [comment]
even after a refresh or a sync-user?

**Comment by kalakom** [comment]
Both don't change it.

**Comment by Aiseant** [comment]
Apparently, any modifiations on a challenge after its creation won't apply to people who already joined it (I tried to change the days some dailies are due, and it didn't change in my dailie list)

**Comment by lefnire** [comment]
bumping priority, it's coded to sync to users, but apparently not working

**Comment by lefnire** [comment]
this is fixed now
