### ISSUE TITLE
translations merge conflicts 

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1813]
### The problem

So I merged as many translations as I could simple or no conflicts. There are still some PRs left which conflict and will have to be manually handled. Unfortunately, because many of the PRs were augmentations to an existing translation, they conflicted with each other and caused conflicts which I couldn't sensibly resolve as I don't speak the languages. In most cases I did a `git checkout {FILE} --theirs` if "theirs" was newer than "ours". There are also some commits which clobbered translations, https://github.com/HabitRPG/habitrpg/commit/c82e0651d13231b7e917284850e74e6807e82f61 was a pretty heavy one (I can identify that it clobbered `bg` in particular). 
### The solution

There was no really clean way to go about this, unfortunately. I spent the better part of today running `rebase --abort` & `reset --hard HEAD` to bail merges - trying to come up with a clean solution. Alas, we may have to go through each app.json's git history (Webstorm is really good at this) one by one and make sure each file didn't get clobbered in its history. If they were, we can do a `git revert SHA` or simply copy/paste the good code over the new stuff.

The issue was that everything sat in PR-land too long, compounding merge conflicts, which was my own fault since I didn't get them in sooner-than-later. To prevent this going forward, I'll merge to `develop`, delete `translations`, and try to merge often.

**Comment by lefnire** [comment]
- bg (c82e065)
- pt (2aa9c0e)

**Comment by lefnire** [comment]
I think that covers em, I got pt taken care of, bg we'll need to handle manually. Let's keep an eye out for fr, that one had a lot of toe-stepping.

**Comment by lefnire** [comment]
(Deleted `translations` branch, @paglias, so we can work off develop now)

**Comment by lefnire** [comment]
these two PRs were closed automatically because `translations` was deleted. However, it looks like they're pretty out of sync with translations/develop and would have caused conflict. Revisit int he future if they don't respond:
- https://github.com/HabitRPG/habitrpg/pull/965
- https://github.com/HabitRPG/habitrpg/pull/1574

**Comment by nafoster** [comment]
Just confirming: you want us work off and pull request the develop branch if we want to add more translations? That is probably best so you can keep everything more organized.

**Comment by paglias** [comment]
@nafoster yes, the `translations` branch has been deleted so all the work is being done directly on `develop`

**Comment by nafoster** [comment]
Excellent; that makes things much cleaner. Thank you for confirming that.
