### ISSUE TITLE
Zombies, Run! Integration 

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#182]
_Edited by wc8: Vote for this feature here: [Zombies, Run!](https://trello.com/c/veANdaTT)_
I noticed that you are planning to integrate some apps to work with HabitRPG but you didn't list Zombies, Run! (Probably because you haven't heard of it). Well let me just give you a brief explanation on what it is:

Zombies, Run! is an iPhone and iPod Touch fitness/game that basically encourages you to go jogging/running by giving you a story to listen to, letting you listen to your own music, makes you run faster with the occasional zombie chase, and letting you level up your city with items that you pick up while running. I'm not the best at describing thing so here is the website for more information. https://www.zombiesrungame.com/

Some ideas i had are:
- Setting days of the week to run and if you skip a day than you lose HP
- Tracking how long you run for and it would take the average time of the last 10 runs and if you run longer than your average you would gan more EXP and if you run less than your average you gain less EXP

People can comment more ideas below

I think that these two app work go perfectly together because they are both apps that improve your life by implementing gaming mechanics.

And lastly, if you don't decide to integrate HabitRPG with Zombies, Run!, than at least now you know about Zombies, Run! which judging by the videos i've seen of you, i think that you're the type of guy that would love this app if you wanted to exercise by jogging every day.

**Comment by hookang** [comment]
Cool Idea... Added to Master Feature List #169. Closed for Organization.
