### ISSUE TITLE
Item counter doesn't refresh

### ISSUE THREAD

**Issue by Nostos** [HabitRPG/habitica#1821]
Hello,

I noticed that the item counter in the Inventory doesn't refresh properly. 
This evening I found 2 panda eggs, which were added to a single fox egg I found a few days ago; however, even after pouring 2 hatching potions on them, thereby losing 2 item both in the Eggs and in the Hatching Potions categories, the two counters didn't change. 
This pic should make it clearer: http://i44.tinypic.com/2cpyzix.png
Not a big deal, but I thought you might want to take a look at it anyway. If you open the Inventory again, everything goes back to normal, it's just that the refresh doesn't work if you stay in the page.

Bye,

Nostos

**Comment by Nostos** [comment]
Ok, I wanted to lower the priority of this issue, but I could not find how I was supposed to do that...Sorry, it's not like I'm proud of my issues, it's just that I didn't know where to downgrade them.

Nostos

**Comment by SabreCat** [comment]
No worries--dev folks will assign priorities as needed when they look over your issue. GitHub's issue reporting paradigm doesn't require the author of the ticket to assign tags etc.

If you're interested in tagging and prioritizing issues, get involved with contributing to the project, and you might gain the ability to do those things!

**Comment by lefnire** [comment]
fixed
