### ISSUE TITLE
egg drop led to false achievement, inventory/stable problem

### ISSUE THREAD

**Issue by lsprague** [HabitRPG/habitica#1826]
I just checked off one of my dailies and got a Wolf Egg as a drop -- and then got a message that I'd gotten the Beastmaster achievement immediately afterward. I only had ~30 pets previously and did not go hatch the wolf before the achievement popped.

Then when I went to my inventory, my list of eggs and potions have been blanked out: there are dashes that get an active-cursor hand hovered over, but clicking them doesn't do anything (there's one under eggs and several under potions, so I tried to see if I could get the egg hatching to happen despite the images being invisible).

Looked in my stable next - it now shows I have "/90 pets found" and all the pet slots are back to blank pawprints. The pet I had equipped previously is no longer on my character.

User ID: b38f52be-395c-44d1-88ab-2d4b350cb307

**Comment by lefnire** [comment]
#1818
