### ISSUE TITLE
Creating party doesn't refresh with my new party view

### ISSUE THREAD

**Issue by kakariki** [HabitRPG/habitica#1828]
I attempted to create a party from the Party tab. It looked successful, but after leaving the page and returning to the Party tab, it asked me to create a new Party again. I tried this multiple times.

After a few attempts I created a new Party, and then invited my friend to it hoping it would stay once there were two of us in it. My friend received the invite and was able to respond to it. I still couldn't return to my party after this.

About an hour or so later, I was finally able to access my party by clicking on the Party, but my friend wasn't in it. Attempting to reinvite them gave me a "Error 400: User already in a party." error. My friend cannot see the party they are currently a member of.

**Comment by paglias** [comment]
I believe two party have been created, you're being shown the second one and your friend has been invited in the first one...

@lefnire we doesn't actually check for user already in a party when creating one https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L180

**Comment by nafoster** [comment]
This happened to me too. I left the second party I was being shown and it automatically placed me in the first one with my friend.

**Comment by kakariki** [comment]
I just attempted to leave the party to see if it reconciled the issue of there being 2 parties, and when returning to the Party tab, it still lists me as being in the party I just left. My friend still cannot see the group they are apparently a member of.

**Comment by lefnire** [comment]
Looks like you created 4 parties (found in database). Basically, you're going to need to leave 3 times. For now, any time the page reloads and the party isn't legit, leave. It will be random which party shows up (you may get the "good" on after the 1st leave), but you'll need to leave the 3 bad parties.

@paglias you're right! I was wondering how so many users ended up creating multiple parties, that's exactly the reason why. I'll work on a fix right now

**Comment by lefnire** [comment]
fixed the above check. but it's strange that @kakariki didn't see the party immediately after creating (i do on my end, `$scope.group = newGroup` kicks in just fine). We'll want to investigate further

**Comment by lefnire** [comment]
@kakariki what I mean was you ne- actually, never mind I'll just do some database operation. Check now

**Comment by kakariki** [comment]
@lefnire All fixed now, thanks :)
