### ISSUE TITLE
Sort Challenges in reverse created-date order

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1829]
At present, the lists of Challenges displayed in groups (Tavern most notably) show up in the order they were created. This means it takes conscious effort, scrolling down to the bottom of the list, to spot if there are any new Challenges available. Having them sort in reverse order, so the newest Challenges appear at the top, would increase the chance of users seeing new challenges in the ordinary course of using group chat.

We could go further and come up with a "new challenge!" notification to blow in somewhere, but this would be an easy first move.

**Comment by lefnire** [comment]
fixed. Also added group & creator in chal header

**Comment by SabreCat** [comment]
Ah! That's pretty cool (if a little busy-looking, with the group and creator info on there). I was actually talking about this list, though, sorry:

![screenclip](https://f.cloud.github.com/assets/4501321/1555730/0a571a3c-4e7e-11e3-83f4-c66329764354.png)

"displayed in groups" meaning, the list of Challenges that you can view from within a Group's page. Clear as mud?

**Comment by lefnire** [comment]
Fixed challenge box (pushing)

**Comment by SabreCat** [comment]
:heart: Love it. Thanks!
