### ISSUE TITLE
Pets Not Appearing Next to Avatar

### ISSUE THREAD

**Issue by Frau-Eva** [HabitRPG/habitica#1833]
I've had no problems loading my pets next to my avatar before, but now none of them will load. I'll click it and the blue loading bar will appear and it'll generally act like it's doing something, and then nothing. I've tried loading all of my pets, and it never works.

ID: ef25f3fb-dd40-4ba8-b75a-7b45ce4ea2fb

**Comment by lefnire** [comment]
is this still an issue for you? I'm showing your user is just fine in the database, and you have BearCub-CottonCandyPink equipped. My hunch is #1818 (you just needed a hard refresh). Re-open if still an issue.
