### ISSUE TITLE
Bug report warning looks terrible on non-widescreen

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1839]
If I've got Habit up on my old 4:3 monitor, the warning about bug reporting via proper channels instead of just complaining in chat gets chopped up in unpleasant fashion:

![screenclip](https://f.cloud.github.com/assets/4501321/1556381/fb4ffe28-4ecd-11e3-8867-8a7c2f6437b5.png)

The styling here would be more palatable if it made one big bubble containing the whole width of both lines when a break occurs.

**Comment by nafoster** [comment]
What is your monitor resolution? I might be able to tackle this since responsive design is my thing :P

**Comment by SabreCat** [comment]
1280x1024, using Firefox at normal zoom (as far as I can tell, anyway... the browser's not very forthcoming with that setting).

**Comment by nafoster** [comment]
Is it just happening using Firefox?

**Comment by SabreCat** [comment]
Lessee, I've been avoiding Chrome lately since it's slower and crashier than Firefox... oh, interesting! Chrome treats it this way, flying under the button instead of wrapping:

![screenclip](https://f.cloud.github.com/assets/4501321/1556491/d50a1418-4ed4-11e3-812d-48004b0ccdbb.png)

**Comment by nafoster** [comment]
Interesting. I will definitely take a look at this.

**Comment by SabreCat** [comment]
Appears to have been incidentally resolved by pull #1908. Closing!
