### ISSUE TITLE
HP is at 0 and the char is not dead

### ISSUE THREAD

**Issue by Mirosan** [HabitRPG/habitica#1848]
I'm using Google Chrome version 31.0.1650.57 m.
My UserID is bf2dc54a-0905-42af-bbfb-5f66439ef70b.

As I mentioned in the title my char has 0 hp and is still alive. He keeps getting more XP as I'm doing more tasks but he doesn't "die".

I'm would check for some JavaScript errors but I don't know where to start.

Cheers

**Comment by paglias** [comment]
Probably you have HP between 0 and 1 but they get rounded down so you see them as 0

**Comment by paglias** [comment]
#596
