### ISSUE TITLE
Resources appear in guilds page

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1849]
Resources (websites) appear in the guild description.

For instance (example from my own guild),

> A guild for all anime, manga and visual novel fans, and the wider otaku subculture outside Japan! \* http://www.animenewsnetwork.com/ \* http://hummingbird.me/ \* http://myanimelist.net/ \* http://anidb.net/

It would be much nicer if the resources did not follow the guild description, like before.

**Comment by lefnire** [comment]
Deliberate. We removed the websites feature from groups and users, since
you can achieve the same functionality with markdown in your description,
and it was adding extra maintenence. migrated the old websites into the
description fields and deleted the feafure
