### ISSUE TITLE
Do you have a blog?

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#185]
I know this isn't directly related to the game, but do you have a blog so people can subscribe to it using RSS reader, so we don't have to constantly check Github for updates.

If you don't, then i think it would be a good idea to help users receive news about HabitRPG (and maybe anything else you might work) easily. It could be a Google blog, or connected to the HabitRPG website, it doesn't have to be all fancy, just something that will let you tell people news in a simple and easy way.

**Comment by hookang** [comment]
I've been asking @lefnire to set this up. I'll talk to him again to see what we can do about it. He's been busy trying to get the app stable - so no worries.

**Comment by Nelmalih0** [comment]
Thank you, i would really appreciate it, you have no idea how much easier it would be for me (and i assume many other people) if he had a blog. :)

**Comment by StanLindsey** [comment]
This is a good idea, as I stated in another thread lefnire being so open about development is fantastic but as you say its currently only on github which isn't really immediately accessible or user-friendly for most users.

As @hookang says though the priority is getting it all stable at the moment. =D

That said, there is a reddit at http://www.reddit.com/r/habitrpg/ which lefnire set up so that should be frequented as its more user friendly.

**Comment by wc8** [comment]
Possible workaround meanwhile: Watch Thread #161 The Current State of Habit
Notifications received in the inbox every time @lefnire comments there.

**Comment by lefnire** [comment]
Hey guys - I'll start blogging here: http://habitrpg.tumblr.com/ . I
created it but never used it, I'll make sure to get the word out on that
URL. (I'll set it up as blog.habitrpg.com when i get the chance). People
can guest-post it and I can approve, so feel free to send anything you
think pertinent my way.

**Comment by hookang** [comment]
Can you add a link to the bottom of habitrpg.com between about and FAQ as blog?

**Comment by Nelmalih0** [comment]
I was thinking the same thing, it would make it easy to find for everyone that uses it

**Comment by lefnire** [comment]
committed, will deploy with next push
