### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1850]
It seems all memory-leak related cards ( eg Issue #1356) have been closed, but I can still experience issues.

![cpu_habitrpg](https://f.cloud.github.com/assets/260983/1560111/c1b9deaa-4ff8-11e3-8860-f81d5ca587ef.png)

When I let habitrpg open for too long (sometimes not so long actually), chromium will use 100% of my cpu, trying to load the habitrpg page, and will ask me to kill it.

**Comment by lefnire** [comment]
are you syncing chat often? I think either @snicker or @paglias mentioned trying to implement long-poll on chat, but it causing a mem-leak. I wonder if that's the leak your'e hitting, or if there's also something else

**Comment by AdrienLemaire** [comment]
I do sync chat often ^^

Then, I'll refresh the page instead of clicking the sync button from now on, until it gets fixed. Thanks :)

**Comment by paglias** [comment]
Surely chat syncing is leaking several tens of memory at every sync for the
tavern at least. Probably it's not the only problem with memory but the
only one I could verify

**Comment by paglias** [comment]
Not happening anymore with chat
