### ISSUE TITLE
titles style

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1855]
Very minor issue: the black div wrapping the titles for a user doesn't scale correctly with the text:

![titles](https://f.cloud.github.com/assets/260983/1570111/277bbf20-50e3-11e3-9737-0a20c3a28551.png)

**Comment by snicker** [comment]
Seems to apply to people with ridiculous titles. Edge case. Suggest do not fix.

Just kidding ;)  I got you:
![image](https://f.cloud.github.com/assets/221540/1572955/45125356-5128-11e3-98ec-2e574b18cbe4.png)

**Comment by snicker** [comment]
Merged into develop.

**Comment by AdrienLemaire** [comment]
@snicker thanks buddy !
