### ISSUE TITLE
Heavy armors look armless with no weapon/shield equipped

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1858]
This was something of a problem already if you happened not to buy a Shield or lost it due to death, while purchasing bigger and better armor, but is accentuated now that we can hide weapons and shields. The Plate Armor and Red Armor, at least (worse on Plate due to less color distinction between shoulder and arm), have a shoulder pad + arm design that makes the sprite look armless, or perhaps winged, without equipment in the character's hand. Maybe we can show a bit more skin on the heavy armors, so it's clear that's part of the sprite's hand instead of their shoulder/body? Pixelists probably have better ideas than I, heh.

**Comment by SabreCat** [comment]
Screenshots later. They're kind of a pain to do on my tablet :P

**Comment by lefnire** [comment]
bump @Fandekasp Yeah, there was discussion on https://github.com/HabitRPG/habitrpg/pull/1815 . @Pandoro mentioned (and I second) concern that the pixel art isn't designed modularly, such that they can be turned on-and-off. Particularly, helms often drop low below the face, and we cut the armor from the helm along a pixel line so they can snap into place properly on a sprite guide when creating the sprite sheets. This is particularly bad for backer & contributor gear. 

Fixing this issue would require redesigning much of the pixel art, as well as making their placement on spritesheets difficult. I thought "heck, let's push the change and see if it irks people". Figured, if they got a funky disable combo, then it's on them to just enable stuff back until it's not funky. However, if we get more complaints we may have to just revert the changeset. Nobody's ever requested the feature (TMK), so I'd rather revert than go down a track of pixel-art redesign

**Comment by AdrienLemaire** [comment]
sure, I understand

**Comment by SabreCat** [comment]
I wouldn't advocate rolling back the "hide thing" options. When it looks sucky, it's one click to put it back the way it was. And as I mentioned, this isn't a new problem--if you don't buy a Shield, you start looking like you're missing your left arm circa Plate Armor.

**Comment by Pandoro** [comment]
I'm going a bit out of my comfort zone as to what I promise of me doing.
But I want to get involved more again and I am a BIG fan of this
modification. I already am afraid of the contributer set, as it looks like
you can ONLY wear it with the helmet, which I always tend to hide.

If we can do a hangout on where I can find the stuff in the repos and what
the current state of the pixelart is, I think that I will be able to give
redrawing stuff a shot. At the same time I can rewrite my guide on a wiki
page. I would be really interested in making the stuff more modular to
actually make gear look good in different combinations!

**Comment by AdrienLemaire** [comment]
@Pandoro cool ! I was going to add your tutorial in the wiki in the following days, but now that you said you would, I'll let you the honor :) You'll want to add it [here](http://habitrpg.wikia.com/wiki/Tips#Pixel_Art)

**Comment by lefnire** [comment]
@Pandoro let's catch up soon (saturday's G+?), I can show you the files and
the complications. For now, let's hold off on this until the class system
is built (is in progress) since I'm knee-deep in sprites and they're in
high flux.

**Comment by Alys** [comment]
Is this still an issue? Should it be moved/copied to the art trello? @SabreCat @lemoness

**Comment by lemoness** [comment]
It doesn't bother me personally - Sabe?

**Comment by SabreCat** [comment]
Yeah, I had pretty much forgotten this was a thing I submitted. xD There are so many options out there now, if you want a hands-free look, you have many possible armors to choose from.
