### ISSUE TITLE
Just made a Chrome Shortcut!

### ISSUE THREAD

**Issue by coolandsmartrr** [HabitRPG/habitica#186]
Not a big deal, but if you want a convenient shortcut, here's something you can use!

![screencap](https://raw.github.com/coolandsmartrr/habitRPGChrome/master/screencap.png)
Download: https://github.com/coolandsmartrr/habitRPGChrome

**Comment by hookang** [comment]
Nice job dude.

**Comment by superlikelikes** [comment]
mines on my desktop. i just dragged it over and renamed it to STATUS and made the icon into a nintendo
![nintendo status](https://f.cloud.github.com/assets/3335116/92110/b2bf0c66-65bd-11e2-9bdd-8f6f766bffeb.jpg)

**Comment by horusofoz** [comment]
@lefnire Close?

**Comment by lefnire** [comment]
ah yes. Cool business guys, makes me feel good :D
