### ISSUE TITLE
tags design messed up

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1860]
Hi,

After taking on some challenges, the number of tags is increased dramatically. And on short windows, it looks really bad:

![tags](https://f.cloud.github.com/assets/260983/1579477/7a8c699e-519c-11e3-95ad-17e6d5a39bcf.png)

I suggest to have them in one scrollable horizontal line, same as for the party members

**Comment by snicker** [comment]
From this:

![image](https://f.cloud.github.com/assets/221540/1607829/36610cc6-54a7-11e3-8d87-94fe4bb66242.png)

to this:
![image](https://f.cloud.github.com/assets/221540/1607831/5e977ad6-54a7-11e3-891e-4c8d46604c7b.png)

**_?**_

**Comment by AdrienLemaire** [comment]
hmm, the scrollbar looks quite big, you think you can restyle it ? Otherwise, maybe it should be a vertical scrollbard

**Comment by snicker** [comment]
@Fandekasp we could re-style the scrollbar. The horizontal approach seems to be the most appropriate. another vertical scrollbar might be odd. Let's see how it fares?

**Comment by snicker** [comment]
Also, it will only show if you have more tags than screen realestate

**Comment by snicker** [comment]
horizontal scroll added here: https://github.com/HabitRPG/habitrpg/commit/38225896f4b48a71e68901430f0a8d1b0d54ee97

leaving this open for comment

**Comment by AdrienLemaire** [comment]
Let's see how it fares :)

**Comment by lefnire** [comment]
+1 for horizontal. Similar setup to Party horizontal overflow. You two are **titans**

**Comment by lefnire** [comment]
deployed

**Comment by snicker** [comment]
MAKE ME PURPLE, CLOWN

**Comment by AdrienLemaire** [comment]
Better solution would be to have arrows on the left and right of the tags, and clicking on the arrows would scroll the tags.

**Comment by lefnire** [comment]
@snicker @Fandekasp Ah! Why do I always forget about contrib levels. You're both purple now, and you motherfuckin deserve it. Thank you so much for all your help! Don't disappear now that you're max, we love you and need you!!! :)

**Comment by AdrienLemaire** [comment]
hahaha cool, thanks @lefnire

**Comment by snicker** [comment]
@Fandekasp I'm still getting used to the "angular way" of doing things. I could have whipped that up with JQuery in a couple seconds, but the angular way says "make a directive and tag the root element with it, create a template, and angular will do it for you". Time consuming, but easier (?) to maintain
