### ISSUE TITLE
No longer getting potions (items still arrays, not objects)

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#1862]
Hello, whenever I get a potion drop, I never see it in the inventory anymore.  Instead I see an increase in eggs.  It's happened three times so far.

**Comment by cleave29** [comment]
And again tonight.  I got a cotton candy and skeleton potion and neither of them showed up.  It also gave me an egg after it had given me the potions which breaks the two-drop-per-day limit.

**Comment by lefnire** [comment]
Did some pretty thorough local testing, can't replicate. UUID?

**Comment by cleave29** [comment]
a4be2ca2-67e9-4355-bd27-be3c22fc554f

**Comment by lefnire** [comment]
blahh.. `user.items.hatchingPotions` was an array, not an object. Fixed. Vestige of users who didn't refresh between when I deployed the new pet system (couple weeks back) and when the next found a drop. Next time around, I really need to have a "please refresh" notification system in place, preventing actions unless the client is updated. I'm gonna dive in to see how many users are still affected. 

Gave you some gems to buy back any lost potions, let me know if you need more

**Comment by cleave29** [comment]
Wow, thanks, Tyler!  :)
Matt
