### ISSUE TITLE
Chat highlights now dependent on @ sign

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1864]
Prior to recent changes to chat highlighting, any mention of a person's name would highlight them in chat. Now, it appears that only explicit @ mentions get highlighted. Was this intentional? With username "SabreCat":

![screenclip](https://f.cloud.github.com/assets/4501321/1581753/34f17cbc-51dd-11e3-9026-86adee0f118f.png)

**Comment by paglias** [comment]
I think it's intentional and probably needed for performances, otherwise every letter typed would result in search for matching usernames

**Comment by snicker** [comment]
Actually, this should be working, I'll investigate

**Comment by paglias** [comment]
@snicker in the readme https://github.com/scarletsky/Angular-At-Directive, in the third snippet of code a flag attribute is mentioned, 

Also this is the code https://github.com/scarletsky/Angular-At-Directive/blob/master/src/at.js#L119

**Comment by paglias** [comment]
My personal opinion, anyway, is that we should have it dependent on @ sign for both performances but also because I don't want to have a list of username appearing for every letter I type

**Comment by snicker** [comment]
this pattern:
`(\s|@|^){1}"+username+"([^\w]|$){1}`
should be working and tests fine, but isn't passing with the space for some reason. Eliminated the previous character test as it's being tested anyway and is probably a faster executing expression as well

**Comment by snicker** [comment]
@paglias the '@' sign must be typed in order to make the list pop up, but it was not previously required for highlighting, I didn't intend to break that functionality

**Comment by paglias** [comment]
Yeah sorry, I think we were talking about mentions when typing, anyway since user lists in the chat box appears only after the @ sign we should make chat message highlighting consistent with it I think

**Comment by SabreCat** [comment]
I'm in agreement with @snicker - assuming no noticeable performance hit, I'd rather see highlights for mentions even without @ flags. Not everybody knows about or uses the autocomplete, like in the example here.

I could be convinced otherwise, though--it would end once and for all the accidental highlighting that happens to folks with short and/or pedestrian user names. :P

**Comment by snicker** [comment]
The most recent highlighting fix should have taken care of the issues
with folks with short usernames. I pity the fool that chooses "A" for
their username though, they're just asking for trouble
