### ISSUE TITLE
Profile without blurb shows "undefined" in popup view

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1865]
If a user doesn't fill out their profile blurb, and you click their name in chat or their avatar in party, you see an "undefined" in the upper left corner:

![screenclip](https://f.cloud.github.com/assets/4501321/1581775/b40b3786-51dd-11e3-9b4c-f99baef65c7c.png)

That should probably say "No profile blurb." or just hide the data element entirely.

**Comment by paglias** [comment]
Strange, I can't replicate this and in case the blurb it's undefined it shouldn't show up: https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/modals/members.jade#L11

**Comment by paglias** [comment]
In the screenshot above, what is that symbol next to undefined?

**Comment by SabreCat** [comment]
It's on beta.habit at least. I can supply a test user and password if you want.

The symbol is just an asterisk, I think. It shows up for people who have blurbs, too.

**Comment by lefnire** [comment]
It's from the migration that merged websites into the blurb, and removed websites. I moved them to the blurb in markdown format (asterisk list). I believe this happens then for users who had added a website and deleted it from their profile, leaving the field as `undefined` in mongo. Then the migration copied the value in as literal text. Ah well, minor

**Comment by Alys** [comment]
Fixed in a change that has been lost in the mists of ancient time.
