### ISSUE TITLE
Strange matches in chat mentions

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1866]
I get some strange matched when mentioning people on github:

![selezione_005](https://f.cloud.github.com/assets/589911/1582672/8ade6378-51f2-11e3-9ed0-d98c2735db8e.png)
![selezione_004](https://f.cloud.github.com/assets/589911/1582673/8ae2251c-51f2-11e3-9d6d-66f181be03c8.png)
![selezione_003](https://f.cloud.github.com/assets/589911/1582674/8ae4f33c-51f2-11e3-9b2b-fbf623d62a28.png)

**Comment by paglias** [comment]
Breadstrings, zak Dwyer and Nick gordon when typign `wc` for example

**Comment by snicker** [comment]
I've noticed this as well, I think it may have to do with the list being unsorted. I may chase it down this weekend.

**Comment by SabreCat** [comment]
Seems to me this got much worse all of a sudden. I can type out someone's entire name using @ and still not have them show up in the autocomplete.

**Comment by joyheron** [comment]
I'm going to look into this.

**Comment by joyheron** [comment]
I implemented a solution that filters the users shown based on prefix matching. That is what I find most intuitive, but I am open to feedback.
![chat2](https://cloud.githubusercontent.com/assets/1502724/7333053/2de3334e-eb5f-11e4-97ee-12a571e32ea8.png)

**Comment by crookedneighbor** [comment]
Closed by #5085
