### ISSUE TITLE
I cant see my character

### ISSUE THREAD

**Issue by Derukee** [HabitRPG/habitica#1867]
i dont know why but 3 days ago when i log in i only see the tags and the task , help plis D:

**Comment by paglias** [comment]
Could you open the javascript console (ctrl+shift+j on chrome) and report what you see there?

**Comment by snicker** [comment]
Do you have "Hide Header" clicked in settings?
![image](https://f.cloud.github.com/assets/221540/1582744/b863ffaa-51f3-11e3-9a29-d3ff8eb24bf6.png)

**Comment by Derukee** [comment]
yes i clicked that button, my bad thanks guys
