### ISSUE TITLE
Green line visible in Contrib Gear announcement when mouse is hovered over

### ISSUE THREAD

**Issue by MaddieM4** [HabitRPG/habitica#1869]
http://imgur.com/lvYPiCZ

When you hover your mouse over the advertised equipment, the outfit drops down a bit, as intended. However, this reveals a thin green line at the top, that probably shouldn't be there. It's possible this line also exists for the main avatar at the top-left, and it's just hidden by the name caption, but who knows?

**Comment by lefnire** [comment]
A piece of the upcoming mounts system peaking through. Pets will have progress bars indicating their growth before they become mounts. This is tucked away enough, and mounts is so close around the corner, I'm just gonna leave it as is

**Comment by MaddieM4** [comment]
Cool! Looking forward to the new feature!
