### ISSUE TITLE
Every time I reload i lose HP

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#187]
I try to check some tasks but the "offline - reload" appears. When I reload the tasks are unchecked and I lose HP. 

Very weird, Im gona die without make any wrong!!

**Comment by racuna** [comment]
Im sign in again, and my HP down from 32 to 14 :/

(I accidentally closed this issue, and i dont know how)

**Comment by wc8** [comment]
What time is it happening? Is it just once a day (may timezone factor) or every time you sign in?

**Comment by lefnire** [comment]
right, if it's in the morning and it's dailies, that's the name of the game

**Comment by racuna** [comment]
I understand that, but was in the middle of the day every time I press F5 i
lose 4.4 hp

## 

oɔıɟíuƃɐɯ sǝ ɐunɔɐɹ ןǝ

**Comment by lefnire** [comment]
Shoot, can you email me your uuid?

**Comment by racuna** [comment]
sure

**Comment by racuna** [comment]
Yesterday I was testing all day and works fine, maybe was a collateral effect of another bug. Today is working fine too, except for the ocassional "offline - refresh" but i think you know that.

**Comment by lefnire** [comment]
ok cool. keep a finger on this pulse and email me your uuid if it happens again.

**Comment by horusofoz** [comment]
@racuna Any recurrences?

**Comment by horusofoz** [comment]
No notification of recurrences after 9 days. Closing ticket.

**Comment by teampayoff** [comment]
i've repro'ed this, too. refresh on a new day causes me to lose HP.
