### ISSUE TITLE
Rename top level Inventory tab to Pets?

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1870]
In writing documentation on the wiki, we're currently working on how to organize it all. At this point, the wiki is more or less organized around the tabs in Options--one article per tab. Pets seems to be the centrally binding focus of eggs and potions, but there's nothing really about pets in the game. This would make the game and the wiki match up. Thoughts?

**Comment by lefnire** [comment]
we could do that for now, since there's no other inventory besides pest. In the future we plan to add collectible armor, glyphs, quest scrolls, etc - so either we change now and change back later, or we hold off anyway

**Comment by bobbyroberts99** [comment]
Hold off would be my vote. I'm just trying to make the game and the wiki more or less parallel so it's transparent what to search for on the wiki. I think this goes away once there are more in-games links. We'll work around it for now.

Will it still be inventory/inventory? How about Gear/inventory (or something different which is maybe a little confusing).

Would it be possible to combine stable and inventory for pets? Show me the 90 pet grid. I see the pet if it's hatched, I see an egg if it's hatchable (with a click to hatch it) or I see the pet. Just thinking…

**Comment by lefnire** [comment]
inventory/gear sounds good to me. Because while gear/inventory makes sense, gear/pets doesn't - but inventory/gear + inventory/pets :+1: 

As for the the combined view, could you do me a mockup? Having trouble visualizing

**Comment by MaddieM4** [comment]
Not OP, but I knew exactly what he was talking about, so I made the mockup myself.

http://i.imgur.com/G0wBRlF.png

**Comment by SabreCat** [comment]
Perhaps you could keep the "Stable" designation (I mean, just look at the Matt NPC!), but change the first tab to "Shop"?

**Comment by lefnire** [comment]
Might be worth a gander as part of classes roll-out. Gear inventory right now is next to pet inventory ([screenshot](http://gyazo.com/bf353e173862f681196b30117eb1b5f0)). It's "consistent", but it doesn't make much sense since you can't sell / buy gear, and gear is gold-purchased, not gem. (well... with upcoming accessories & scrolls & all that, hmm...)

**Comment by bobbyroberts99** [comment]
@campadrenalin that's exactly what i meant. Thanks for the mockup.
