### ISSUE TITLE
Got a potion for clicking on the challenges page

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#1874]
I was chatting in the tavern and wanted to refer to one of the challenges, so I command-clicked to open it in a new tab (Chrome Mac). When I switched to the tab with challenges open, I had a message that I had a skeleton potion. I'd been in the tavern for a while so it's not like I'd just checked off a task and this was the slightly delayed result. Weird.

**Comment by deilann** [comment]
Don't think I've seen this repeated. Gonna close it for now; if it surfaces again, let's investigate further. I'm guessing it was the cache updating, opening a new tab (being in the Tavern doesn't update anything).
