### ISSUE TITLE
Can't log in to locally running Habit

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1875]
Bit of contributor frustration, here. Wanted to test out some .jade edits I made, but can no longer make it past the static/front screen with the big PLAY button.

Windows 7, node.js 0.10.22, Mongo... dunno how to tell.

Mongo's running, gets connections OK.
grunt run:dev goes off without errors.

However, when I make any attempt to navigate or log in, I'm redirected to http://localhost:3000/static/front#/tasks and stay at the main splash page. The Grunt terminal shows a 401: 

![screenclip](https://f.cloud.github.com/assets/4501321/1597577/4d4f905e-5314-11e3-96d2-79ab2bb9bb40.png)

Any idea what's broken?

**Comment by AdrienLemaire** [comment]
oh, did you try to do some stuff like symlinking the habitrpg-shared directory ?

I'm pretty sure that if you reclone habitrpg in another location, and reinstall it (npm install), it will work. Need to figure out what broke your first repo.

**Comment by SabreCat** [comment]
I have a habitrpg-shared clone, but haven't done anything to link it up with habitrpg main. I'll try a redo, then. You suggest recloning in a different location--is there any reason I can't wipe the directory I've got? (Is there a git command to do that cleanly?)

**Comment by AdrienLemaire** [comment]
hmm you can try `git clean -df .` or something like that :)

**Comment by lefnire** [comment]
Try deleting localstorage:
https://www.evernote.com/shard/s17/sh/e71b95ac-04dc-45f5-8002-5f811f21d7a8/792c378c33e43d1f8f5cc0477dea8d9d

**Comment by SabreCat** [comment]
Ooh? That does sound plausible, some sort of mangled cache thing. But how do I get at what you show in the screenshot?

**Comment by lefnire** [comment]
Top right settings button in Chrome > Tools > Developer Tools

**Comment by SabreCat** [comment]
Any idea where that is in Firefox? I can jump over to Chrome, but I tend to use FF most of the time.

tch... I tried starting over before @lefnire chimed in, anyway, and now grunt run fails to compile Stylus. fml?

![screenclip](https://f.cloud.github.com/assets/4501321/1597795/d236c472-5319-11e3-8377-e32ec82caffa.png)

**Comment by SabreCat** [comment]
Needed to npm update (iCal breaks, but who cares) and bower update... now I'm back to where I was on static/front. Will try Chrome.

**Comment by SabreCat** [comment]
Hah! Okay! Made it. Now, to restore the edits I made and see if they take. Thanks both of you, I'll get the hang of this eventually!

**Comment by SabreCat** [comment]
The fruits of my labor and your assistance: #1876

**Comment by AdrienLemaire** [comment]
Troubleshooting added to wiki: http://habitrpg.wikia.com/wiki/Installation_troubleshooting#Cannot_login
