### ISSUE TITLE
HabitRPG Blog Bottom div layer covers navigation menu

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#1878]
This is a screen shot of the http://blog.habitrpg.com/ask page. As you can see, the bottom images cover the bottom of the navigation menu, making it impossible to see the search box or click on the lower menu buttons.

![image](https://f.cloud.github.com/assets/5908271/1600630/c0fd1cae-5375-11e3-84dd-8996bf3af710.png)

**Comment by negue** [comment]
Since there is no repo for the blog :tongue: 

This could fix it:

Add this to the #main Style in style.css:
`min-height: 700px;`

And then this Issue can be closed.

**Comment by Alys** [comment]
@lefnire : This might need to be fixed by you or another member of the inner circle. :)

**Comment by lefnire** [comment]
@lemoness do you have access to edit / append-to CSS on the blog?

**Comment by lemoness** [comment]
@lefnire I think I do! Will give this a try in a bit and ask questions here.

**Comment by lemoness** [comment]
Okay, I have access to the html on the page. A search for "main" brought up the following:

![screen shot 2014-09-05 at 3 22 48 pm](https://cloud.githubusercontent.com/assets/3494081/4172600/5146f606-354b-11e4-8094-1eacb5ed49e7.png)

Is this what you mean, or is there somewhere else I should edit?

Sorry about the dumb questions that will invariably ensue from this process - right now my coding experience is limited to super-basic HTML and uploading images to Spritesmith, but I'm determined to learn how to do things myself, so this is good for me.

**Comment by lefnire** [comment]
That's the HTML editor. There should be a CSS editor somewhere too, but I can't find it. It _definitely_ should be there, since there's this in the HTML:

``` html
<style type="text/css">
  {CustomCSS}
</style>
```

that `CustomCSS` should come from somewhere, but I don't know where. Anyway, I added it in at the end like this, which is fine for now:

``` html
<style type="text/css">
  {CustomCSS}
  #main {min-height: 700px;}
</style>
```

**Comment by lefnire** [comment]
Oh, I found it. I added it in, so this can be closed. It's at Customize > Edit Theme > Advanced Options (all the way at the bottom) > Add Custom CSS

**Comment by lemoness** [comment]
Thanks @lefnire! Sorry I didn't find it.
