### ISSUE TITLE
Glitched daily slowly killing me

### ISSUE THREAD

**Issue by nafoster** [HabitRPG/habitica#1879]
![untitled-1](https://f.cloud.github.com/assets/3391909/1600690/29871fe4-5377-11e3-9e3a-73f09c70290a.jpg)

Not sure how that blank -/+ habit got into my daily section, but I can't delete it and it is slowly killing me.

User ID: f90f3c99-8e91-433d-8db2-7377c6c8f709

**Comment by lefnire** [comment]
Running migration to fix this for you, shoudl be complete in next hour or so and you can delete the task. Fixed in https://github.com/HabitRPG/habitrpg/commit/c2b8a6274901c4189dca5d50b67e4f7404d08537 , hopefully this shouldn't happen again

**Comment by lefnire** [comment]
yowzer. commit on develop, cherry-pick to master, `rebase -i` to classes, and I've got 3 different SHAs (hence the 3 mentions above). Sorry everyone if this mucks up merges down the pike, I'll keep an eye out

**Comment by nafoster** [comment]
Everything seems fine now. I'll let you know if it happens again.
