### ISSUE TITLE
Not leveling up any more

### ISSUE THREAD

**Issue by GrandBastard** [HabitRPG/habitica#188]
My avatar got stuck at Level 2 close to level 3.
Thing is I have gone over to level 3 a couple of times and it goes back to level 2 with 5 points away form level 3.
I don't know if related but it says "Unable to reconnect - reload" at the top.

Thanks

**Comment by horusofoz** [comment]
@GrandBastard "Unable to reconnect - reload" is your likely cause. Can you close the tab, revisit the page, login and try again to confirm it is now working?

**Comment by GrandBastard** [comment]
It seems to be working now, however I had tried reloading new tabs at the time.
Thanks for the great work

**Comment by horusofoz** [comment]
@SlappyBag Can you close this ticket please?

**Comment by StanLindsey** [comment]
Aha. Thanks @horusofoz =D
