### ISSUE TITLE
You're Dead!  But not really...

### ISSUE THREAD

**Issue by kalliburr** [HabitRPG/habitica#1881]
When I use HabitRPG on my iPad, every time I check off something I've done on my Dailies list, a screen flashes for just a second telling me that I'm dead, even though I'm not, and then just continues on to the regular page with the item I checked off as being completed.  It's a little weird.  Nothing major, but I don't think it should be doing that.

**Comment by snicker** [comment]
I've also noticed this... I think it's related to iOS not respecting the display:none attribute and http://docs.angularjs.org/api/ng.directive:ngCloak

**Comment by ianoff** [comment]
Is this for the mobile app? Or is this happening on Habit web version, while on the iPad, as well? It is a known issue on mobile.

**Comment by kalliburr** [comment]
It's the mobile app, yeah.  I wasn't sure if it was known or not.  It does it on my iPad, though, and not my iPhone.

**Comment by ianoff** [comment]
See https://github.com/HabitRPG/habitrpg-mobile/issues/151 Mobile app issues should be reported at habitrpg/habitrpg-mobile if possible
