### ISSUE TITLE
Inventory Broken

### ISSUE THREAD

**Issue by m0xf4240** [HabitRPG/habitica#1882]
My inventory has been completely broken for a few days now. Instead of clickable icons I have this 
![bug](https://f.cloud.github.com/assets/3958169/1603939/36f8be9e-53b3-11e3-9612-a0804701ccb4.png)
and when I get alerts for new drops they don't show up in the text list. I'm having the same problem in chromium and firefox.

**Comment by paglias** [comment]
New drops not getting in the list until a refresh was my fault but now it's fixed, but the [objectObject] thing is quite strange, instead of potion/egg name it seems like you have the whole item....

**Comment by lefnire** [comment]
@xenakaaii UUID? and how long has this been happening, or is it just within the last hour or so?

**Comment by m0xf4240** [comment]
@lefnire It's been like that for the past week. UUID is 15615480-15a0-4efe-894c-f104afa3df3d

**Comment by m0xf4240** [comment]
Also the items in the list aren't clickable, it's just text. Here's some more information if it helps: 
![screenshot from 2013-11-22 16 17 21](https://f.cloud.github.com/assets/3958169/1604332/8d75bf9e-53bb-11e3-9755-6481421bb7a7.png)

**Comment by lefnire** [comment]
same issue as #1862 turns out, I'm gonna fix and get back to you

**Comment by lefnire** [comment]
Ran migration for you - do a hard refresh, added gems for the troubles. Let's follow on #1862 for future users
