### ISSUE TITLE
[Feature] Ability to choose difficulty for a task from 1-5. Different difficulty should give different rewards

### ISSUE THREAD

**Issue by Zequez** [HabitRPG/habitica#189]
Tasks are not equally difficult. There is an great difference between "study for 1 hour" than "wash your teeth after lunch". And so should be the rewards each task give.

We could calculate the reward of tasks using 2 variables: time estimated the task is going to take, and actual difficulty of the task.

Also, with the party system we could moderate our tasks by averaging. So let's say I set one tasks to difficulty 5, but a friend of mine thinks is a bit far fetched, so he set it's to 3. So it averages at 4.

**Comment by wc8** [comment]
See https://trello.com/c/4C8w1z5h and #53

**Comment by horusofoz** [comment]
@lefnire Duplicate of #53?

**Comment by lefnire** [comment]
yesm
