### ISSUE TITLE
NPCs are not getting the right styles on their usernames in chat

### ISSUE THREAD

**Issue by snicker** [HabitRPG/habitica#1893]
Poor Bailey:
![image](https://f.cloud.github.com/assets/221540/1606034/f9bf6e6e-540d-11e3-8fb5-4ca12becab16.png)

**Comment by snicker** [comment]
This is related to bindonce, the bo-class directive does not work when the same tag has double curly brace markup. Issue is documented here:
https://github.com/Pasvaz/bindonce/issues/35

In the meantime, I've rolled back to using ng-class. We should keep an eye on this in case bindonce is fixed, it would be the "high performance" way to do it.

**Comment by snicker** [comment]
Fixed here:
https://github.com/HabitRPG/habitrpg/commit/2a7adf7285a4f3d441603c233e417b0aef0e0e44#diff-ddc63968914312231b143b93f4131c57R12

**Comment by snicker** [comment]
We need a "revisit periodically" tag for the issue tracker. I didn't want to close this because I think it's not resolved in the way it should be. But it's all the fault of bindonce...

**Comment by snicker** [comment]
@lefnire: "revisit periodically" tag pls <3

**Comment by AdrienLemaire** [comment]
oh ok. I thought you mistakenly reopened it :) sorry about that

**Comment by paglias** [comment]
@snicker I think you can edit tags, anyway, I've added it :)

**Comment by lefnire** [comment]
ah, interesting - sort of an "acceptability tests" tag

**Comment by snicker** [comment]
@paglias I'm not sure I have permissions to edit tags, but thank you!

**Comment by snicker** [comment]
Looks like I'm doing this all wrong:
http://www.thinkingincrowd.me/blog/2013/01/30/string-interpolation-should-not-be-used-with-class-directive-in-angularjs/
Thanks @paglias for finding that, I can fix this properly and use bindonce now.

**Comment by snicker** [comment]
Fixed and bindonce compliant in https://github.com/HabitRPG/habitrpg/commit/a4fb0b42ad64334bad5fbddf459c520406d13b85
