### ISSUE TITLE
develop broken

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1895]
Error raised : http://sprunge.us/cgRO, by commit 4bedefbc57a1a38509b1d801de8b6aa78ae40d84

Can be fixed by doing:

```
$ git revert 4bedefbc57a1a38509b1d801de8b6aa78ae40d84
```

@paglias I also notice some dirty commits like 967801eb1fedba86ed5db1c1913edc8d25ade911.  Please check the [wikia tips](http://habitrpg.wikia.com/wiki/Guidance_for_Contributors#7._Issues) on how to avoid that :)

**Comment by paglias** [comment]
Try updating habitrpg-shared, it's been added in the past days so you may
have an old version of it

**Comment by AdrienLemaire** [comment]
good catch... Now I feel stupid ^^ Thanks @paglias

**Comment by paglias** [comment]
@Fandekasp I'll try to avoid that "Merge" commits, even though they are not causing any problem I understand it's not the best way to do it :)

**Comment by snicker** [comment]
good fix for this is running `npm install --force`
