### ISSUE TITLE
package.json references nonexistent version of iCalendar

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1897]
Running npm install throws a "version not found" error for iCalendar:

```
13576 error Error: version not found: 0.6.4 : icalendar/0.6.4
```

Looks like current version is 0.6.5. I'd correct it myself, but it looks like the package.json points to @lefnire's fork? Didn't want to dabble in matters beyond my ken.

**Comment by lefnire** [comment]
Is this still happening for you? I can't repro

**Comment by SabreCat** [comment]
Still happens as of this morning, ran an `npm update` and got this:
![screenclip](https://f.cloud.github.com/assets/4501321/1700333/20f66dee-600b-11e3-9d06-af2005e6e93b.png)

**Comment by SabreCat** [comment]
...but that's with a Develop-based branch checked out. I'll let you know later if it happens with Classes too.

**Comment by paglias** [comment]
I can confirm that too, it seems that it tries to get the package from npm registry even though it is specified to use @lefnire 's from github

**Comment by SabreCat** [comment]
Argh, now my local copy's blown up not able to find uglify.js. **stomp, stomp, mutter**

(unrelated I know, just had to grumble)

**Comment by negue** [comment]
NPM INSTALL / UPDATE works here without an error.

@SabreCat @paglias  Do you both still have this error?

Maybe old / buggy node version?

**Comment by paglias** [comment]
Fixed for me
Il 24/ago/2014 12:40 "negue" notifications@github.com ha scritto:
