### ISSUE TITLE
Stats page still counts rare pets in Pets Found

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1898]
If you have some rare pets, the Stable correctly shows the number of non-rare pets found out of 90 for "Pets Found", but the Stats page still includes them in its total.

I tried fixing it, but my Angular-fu failed; I couldn't figure out how to reference the petCount variable from outside the Stable page's scope. I could put a Band-Aid on it by appending an "including rare pets" parenthetical, but that seems like weak sauce, heh.

**Comment by paglias** [comment]
@SabreCat yeah I'm sorry, I moved the code to the rootScope so that it can be used outside of the Stable
