### ISSUE TITLE
Tasks that pop up every "n" days

### ISSUE THREAD

**Issue by funvill** [HabitRPG/habitica#19]
_Update by wc8: Vote here: [Repeat every "n" days](https://trello.com/c/XuVokK2V)_
I want to scheduled tasks that happen every 6 weeks (any arbitrary time) that pop up in to my to-do list. 

For example 
On Aug 1st every year, "clean the gutters" 
Once a month "check visa bill" 
Once a week "Go shopping for food"
ect..

**Comment by passy** [comment]
+1

**Comment by lefnire** [comment]
Definitely on the agenda. A bit later than sooner, some essentials to complete first, but planned.

**Comment by passy** [comment]
Fantastic! :cake:

**Comment by horusofoz** [comment]
+1
Weekly or monthly tasks that appear in same task list or a timed tasks list would be great

**Comment by FunnySunshine** [comment]
Good idea!

I would also like an option to add a weekly task, but not necesarily for a specific day.

**Comment by Nelmalih0** [comment]
+1

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Update by wc8: Vote here: [Repeat every "n" days](https://trello.com/c/XuVokK2V)
Related #208
