### ISSUE TITLE
App suggestions

### ISSUE THREAD

**Issue by jendie** [HabitRPG/habitica#190]
_Edited by wc8: Vote for this feature here: [Noom](https://trello.com/c/I8xXMWmo), [AnyDo](https://trello.com/c/wA4iObYh)_
Hi,

Just wanted to suggest support for Noom (fitness tracker) and AnyDo (task manager).

Thanks!

Jennifer

**Comment by ApexNights** [comment]
_Edited by wc8: Vote for this feature here: [Clear](https://trello.com/c/PAFPwZ6Q)_
I'd like Clear to be supported, i use it cooonstantly.

**Comment by StanLindsey** [comment]
Closed, check the discussions in Trello and remember to vote for your favourite!
https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6
