### ISSUE TITLE
Concern about Gifs in Chat

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1902]
Hm - question for you guys. Should we be having gifs in the chat? Will that be potentially problematic for people with epilepsy and/or people who have sensitivity to that sort of thing? On gif-heavy sites like Tumblr, it's easy to tag for that sort of thing, but we have no Tumblr Savior equivalent.

 On one hand, we have some very mild animation in the contributor and backer armor... but with gifs, we are running the risk of a user happily posting something funny or cute that happens to be problematic, and then a user who has come to the tavern to ask a question experiencing pain or a seizure because of it. It's not like people are expecting gifs in this format :/ 

I think this might be an issue particularly because we are in many way a health-site.

Thoughts?

**Comment by SabreCat** [comment]
There's also the risk of an uncouth user throwing something not-so-PG in there. Any admin would delete it right quick, but there's reason for the saying "what has been seen, cannot be unseen."

**Comment by snicker** [comment]
I believe we can restrict which markdown tags are active... should we disable images and titles and horizontal rules?

**Comment by lefnire** [comment]
awww... I was rather liking the images, **and** the gifs. Gives the chat room a lot of character and fun, it was one of the things that made chat at previous jobs I'd worked a lot more frequented

**Comment by snicker** [comment]
I'd say put it to a vote. I am fond of it as well.. and beta has the style code that makes the images and scrolling nice and unobtrusive

**Comment by lefnire** [comment]
bam http://community.habitrpg.com/content/images-gifs-chat

**Comment by lemoness** [comment]
Images are fine - as for the NSFW, that's what mods are for. But I worry
that gifs will pose an actual health risk to some of our users :( Can we
keep images, but nix gifs? Or hide gifs until clicked?

**Comment by SabreCat** [comment]
Do we have 24/7 mod coverage in Tavern at this point?

**Comment by snicker** [comment]
@lemoness I think that's a fair request.. I'll have to look at how other places are doing it. I think with gifs you have to grab and cache the first frame and load the real image on click :/ it's rather onerous of a process. I'll research.

**Comment by deilann** [comment]
@lemoness Part of the guidelines work? As someone who used to deal with seizures, I can tell you that the flashing gifs that are likely to cause seizures are few and far between (and it's hard to say what will trigger non-epileptics, as it might be dark vs. light rather than the flash rate.)

**Comment by lemoness** [comment]
Heh, good to know!
