### ISSUE TITLE
Barring markdown, chat scrollbar should kick in on integer number of lines

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1903]
Firefox on Windows 7, beta.habit...

If you post a four-line message to chat, you get a scrollbar for your message with just a sliver of movement space, cutting off only the dangly bits of the letters on the lowermost line:

![screenclip](https://f.cloud.github.com/assets/4501321/1607738/f1e6f246-549b-11e3-9283-57cd7f44bd05.png)

The scrollbar should only appear if there's something meaningfully hidden; this only makes things look unsightly. Give it a few more pixels of breathing room before deciding to use one.

Polyphasic sleep tip brought to you by the "Naps of Power" guild. You're welcome!

**Comment by snicker** [comment]
Will change from 75px to 80px. Can't base it on the number of lines, per se.

**Comment by snicker** [comment]
fixed in https://github.com/HabitRPG/habitrpg/commit/2604d8e21e6ef4e361f121e018961131923984cc
