### ISSUE TITLE
Resource added

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#1906]
Suggestion to add markdown cheat sheet link in the resource panel of tavern. or something similar.

**Comment by lefnire** [comment]
There's a jade file for "click this for markdown tips" (used in profile & group edit), in case someone gets to this before I hit the code

**Comment by SabreCat** [comment]
On it.

**Comment by clmmerrill** [comment]
This is all I have so far. I probably would only ever use the blank line so I couldn't think of any more besides the basics.

Markup Cheat Sheet

line break or paragraph break= shift + enter enter
headlines must be on own line to work = pound sign before and after 
once is #h1# , two times is ##h2## and, three times ###h3###
quoting is the > sign
one astrick or underscore _will make italics_
two of either **will make strong**

**Comment by SabreCat** [comment]
@clmmerrill The cheat sheet link will now go to http://habitrpg.wikia.com/wiki/Markdown_Cheat_Sheet , so if you have more information to add, you can put it right in the wiki!
