### ISSUE TITLE
OAuth2Strategy error when trying to run locally

### ISSUE THREAD

**Issue by Cecron** [HabitRPG/habitica#191]
I get the following error when accessing the page http://192.168.1.50:3000:

Error: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/mac/habitrpg/node_modules/passport-facebook/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66:32)
    at new Strategy (/home/mac/habitrpg/node_modules/passport-facebook/lib/passport-facebook/strategy.js:49:18)
    at /home/mac/habitrpg/node_modules/derby-auth/index.js:128:26

Looking around in the derby-auth http://github.com/switz/derby-auth/ files, I could not understand enough to find any solutions...

I followed the steps outlined in http://github.com/lefnire/habitrpg/wiki/Running-Locally using 
NODE_DB_URI=mongodb://localhost/habitrpg
BASE_URL=http://192.168.1.50

**Comment by lefnire** [comment]
You might also need FACEBOOK_KEY and FACEBOOK_SECRET env vars. You can probably set those to gibberish, if that's the case check back here and I'll update the code or wiki

**Comment by Cecron** [comment]
Nope, same error when I set those two keys.

(Yiee where you fast answering this one...)

**Comment by lefnire** [comment]
try commenting out using facebook strategy ([these lines](https://github.com/lefnire/habitrpg/blob/master/src/server/index.coffee#L39-43)) just to get it working for now

**Comment by Cecron** [comment]
Still not running, I get this now:

Expressions in require() statements:
    require('./lang/' + key)
TypeError: undefined is not a function
    at /home/mac/habitrpg/node_modules/derby-auth/index.js:128:26
    at eval (eval at createIterator (/home/mac/habitrpg/node_modules/lodash/lodash.js:683:19))

**Comment by arscan** [comment]
I had this same problem.  Just assigning random strings to clientID and clientSecret in the lines that Tyler highlighted in the comment above did the trick for me.

**Comment by lefnire** [comment]
shoot, try running `BASE_URL="localhost:3000" FACEBOOK_KEY=abc FACEBOOK_SECRET=abc node server.js`

**Comment by Cecron** [comment]
Thanks! This one worked  
BASE_URL="localhost:3000" FACEBOOK_KEY=abc FACEBOOK_SECRET=abc NODE_DB_URI=mongodb://localhost/habitrpg node server.js
