### ISSUE TITLE
Clicking link in tavern does not open new tab anymore

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#1910]
I only use beta.habitrpg, but just checked habitrpg and same thing is happening there. 
Until yesterday when I clicked on a link in a chat box, the link would open in a new tab. 
Yesterday and today the link opens in the same window. Not a complaint just something different. I just know now to left click to open in new tab.

**Comment by SabreCat** [comment]
That's happening here too (Win7 Firefox). I do think this is worth fixing: default behavior should be new tab for links that take you outside the habitrpg.com domain.

**Comment by paglias** [comment]
Partially fixed in https://github.com/HabitRPG/habitrpg/commit/fa2fb8e3fbdb4420be1081f3a314585df00512e7, it won't work with links autodetected (but only with this syntax `[linkName](http://link.com)`), @snicker if you would like to give a look at it I added a comment in the commit

**Comment by snicker** [comment]
fixed in https://github.com/HabitRPG/habitrpg/commit/f4323ddc24e5f329a46af3a3a135f78abc671da0
