### ISSUE TITLE
Remove sensitive informations from data export

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1914]
Actually user data exported in JSON/XML contains the hashed password and the salt which shouldn't be avalaible I think.

They are removed from api.getUser for example.

@snicker

**Comment by snicker** [comment]
I thought that may be a concern... but that data is only available to the
authenticated user so should it really matter that much?

**Comment by snicker** [comment]
removed in https://github.com/HabitRPG/habitrpg/commit/878bfc7f46282dc69aa02a82d3e87862dc032967
