### ISSUE TITLE
Cannot Delete Challenge And I Left All Challenges

### ISSUE THREAD

**Issue by mikefinney** [HabitRPG/habitica#1915]
I left all challenges I had. I see "Stand up with the alarm" challenge still. I tried refreshing browser. Still there. Can't delete it.

Using Latest Chrome browser: Version 31.0.1650.57

finneycanhelp aka mikefinney ; if you need my facebook client ID, please let me know.

Javascript error in console (unrelated?):

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. 

https://www.facebook.com/connect/ping?client_id=.... I removed the rest because I was concerned about sharing something I should not publish (security concern).

**Comment by lefnire** [comment]
Possibly connected to https://github.com/HabitRPG/habitrpg/issues/1883 , will investigate soon

**Comment by Joy2b** [comment]
I've also had issues with the inability to delete three dailies that were created by challenges.   The delete button does not appear.

My user ID is: 8fee75a0-1156-4880-9ae2-a911d300faf8
Browsers: Firefox 24 and Chrome 32.0.1700.107 
Dailies: Conquer Castle Clutter 15m+, Write down something good that happened to you, resist the urge
Screenshot: 
![dailieswithoutdeleteicon](https://f.cloud.github.com/assets/6333449/2130558/64ab055c-9294-11e3-8b16-f682d5a8122b.JPG)

What else can I do to help?

**Comment by deilann** [comment]
Let's follow this at https://github.com/HabitRPG/habitrpg/issues/2763
