### ISSUE TITLE
Momentarily incorrect guild tabs after leaving a guild

### ISSUE THREAD

**Issue by SyntaxPickax** [HabitRPG/habitica#1916]
Here's how to reproduce the bug:
1. Join some guilds.
![screen shot 2013-11-25 at 5 05 29 pm](https://f.cloud.github.com/assets/1245093/1618571/132bd538-5637-11e3-8bc3-2b3be696517b.png)
2. Then join a guild with more members than at least one of your other guilds. This guild will be appended to the row of tabs.
![screen shot 2013-11-25 at 5 05 39 pm](https://f.cloud.github.com/assets/1245093/1618574/1d7a2058-5637-11e3-889e-1463d25d9dd2.png)
3. Refresh the page.  The tabs are reordered by decreasing member count.
![screen shot 2013-11-25 at 5 06 00 pm](https://f.cloud.github.com/assets/1245093/1618580/359656a2-5637-11e3-8940-45cf5eb0c670.png)
4. Leave a guild with a higher member count (e.g., the one just added). The tabs will be updated to appear as though the user left the wrong guild.
![screen shot 2013-11-25 at 5 09 21 pm](https://f.cloud.github.com/assets/1245093/1618591/7b62c7e2-5637-11e3-8d44-d1e2b4efdfc0.png)
5. Refresh the page. The tabs are correct again.
![screen shot 2013-11-25 at 5 10 44 pm](https://f.cloud.github.com/assets/1245093/1618598/97754d42-5637-11e3-9ab3-4f09e90a101a.png)

(Using Google Chrome. No JS errors in the console).

**Comment by snicker** [comment]
@Fandekasp is this related to https://github.com/HabitRPG/habitrpg/pull/1904?

**Comment by paglias** [comment]
@SyntaxPickax this happens only with guilds with more members than the others?

**Comment by paglias** [comment]
I've been able to replicate this, but only sometimes: it seems that guilds are not always correctly removed, sometimes they appear after leaving them if you refresh but any action on them gives a 401 because the server correctly removed you from the guild. It shouldn't happen because the guild list isn't saved on localstorage & the server doesn't have any sort of caching.

**Comment by SyntaxPickax** [comment]
@paglias That's actually a bit tricky for me to test, since I'm the creator of the Climbers Guild, which is tied for lowest member count (3) and I don't want to leave it. Ha! 

Of course, if I don't refresh the page (i.e., omit step 3) and just immediately leave the guild while it sits at the end of the row of tabs, then there's no buggy behavior.  But that of course doesn't really model what users might do, which is join a guild and only days/weeks/months later leave it.

**Comment by AdrienLemaire** [comment]
@snicker I think it's unrelated. #1904 is related to **partyMinusSelf**, which is only used for the party, not for guilds

**Comment by Swotfabs** [comment]
I had a similar issue.
I joined guilds starting at the bottom of the page (lowest member count first) and the guild I had joined last was appended to the guild list.
Then I left a guild, and the wrong guild was removed from the list.
Refreshing the page both re-ordered the guilds I was in and made the correct guilds appear.

**Comment by JesperDramsch** [comment]
Just had the same problem. I left some guilds "from the middle" of my list and somehow the list got mixed up. First I was wondering if I clicked the wrong guild to leave.

**Comment by theplushfrog** [comment]
I've had a similar issue repeatedly today, often with guilds (which I'm no longer a member of) not going away even after refreshing.  I've noticed a few guilds (which I am a member of) aren't showing.

I went back to check, but I'm definitely listed as a member of the guilds I'm supposed to be in and not as one in guilds I'm not supposed to be in, but it still shows them incorrectly even after refreshing.

**Comment by Otocinclus** [comment]
I think I had the same problem, but with added complications of it causing me to unjoin a guild I had just created, and having to figure out a way to rejoin it when it still thought I was a member but didn't show it in my guild list.

**Comment by deilann** [comment]
Are you sure you weren't still a member? That's the thing with this bug--
it won't show in your guild list, but you're still a member.

**Comment by Otocinclus** [comment]
It said I was still a member on the guild's own page, but not having access to it on my guild list or guild tabs, and thus only being able to get to it through chat alert, is - I think - the bigger problem. But I definitely think that the guild page did the "momentary" incorrect tab thing at the time. I think that's why you referred me here in the first place from my original issue, https://github.com/HabitRPG/habitrpg/issues/3063.

**Comment by deilann** [comment]
Yeah. So you were still a member-- it was just displaying incorrectly.
(Sorry, there's a huge difference on the backend between "I wasn't a
member" and "The guild wasn't displaying")

**Comment by Otocinclus** [comment]
Well, it kindof happened again just now. I went to my guild tab and saw a guild I had already left back on my tabs, so I went to unjoin it... Now it's still there, but my private guild is gone again. I think it might be getting rid of the most recently joined guilds? That would explain why it keeps being that one that disappears? So I guess, backend-wise, I'm still a member of my guild, just unable to access it through normal means.

**Comment by deilann** [comment]
Try refreshing (hard refresh) on the guilds page.

**Comment by Otocinclus** [comment]
Okay, now it has my old guild back (YAY!), and the one I just left is gone. I'm not going to join or unjoin any other guilds for a while now, and take note if/when the ones I've left come back... would that help?

**Comment by deilann** [comment]
They shouldn't, and leaving guilds shouldn't be a problem.

The hard refresh makes sure that what the page is showing you is what's on
the server, not what's in your local cache. So it's just a display issue.

If you encounter this again, just do a hard refresh and you should be all
good.

**Comment by wc8** [comment]
Maybe add text to confirmation dialog suggesting the user restart his browser afterward?

**Comment by deilann** [comment]
That would be good for this exact moment, but it would be nice for the
problem to be fixed at the root...

**Comment by Alys** [comment]
Leaving a guild now triggers a page refresh which fixes this.
