### ISSUE TITLE
API Problem Delete and Get Task by ID

### ISSUE THREAD

**Issue by kitsully** [HabitRPG/habitica#1917]
I'm running the python equivalent of this request.

``` bash
curl -X DELETE --compressed -H "Content-Type:application/json" \
   -H 'x-api-user: user-id' \
   -H 'x-api-key: api-key' \
   https://habitrpg.com/api/user/task/6ea60933-2307-48c8-b68f-c9a4a2a3421b
```

Obviously in my code the user id and api key are filled in. I just didn't want to write them here. If you need them let me know.

Whenever I try to run it I get a 404 error. When I run the curl command I get "Cannot DELETE /api/user/task/6ea60933-2307-48c8-b68f-c9a4a2a3421b." I also get a similar error when I try a PUT request. A POST request to create a new task works fine. Anyone have any idea why this might be?

**Comment by lefnire** [comment]
What's your UUID? I wanna check if that task actually exists with that id
(6ea6...)

**Comment by kitsully** [comment]
86fc6c84-6a31-434a-9934-26db5d58ee4a

I have tried this with multiple tasks. I even used POST to create a new task and then copied and pasted the task id directly from the response.

**Comment by kitsully** [comment]
So I'm guessing by the labels this issue has this isn't a problem localized to me?

**Comment by lefnire** [comment]
Yours is the only report, but I marked it up so once we close the `critical`s we can move on to the `important`s

**Comment by jbutz** [comment]
@kitsully I found the issue. Your url needs some modification. Instead of `https://habitrpg.com/api/user/task/6ea60933-2307-48c8-b68f-c9a4a2a3421b` it needs to be `https://habitrpg.com/api/v2/user/tasks/6ea60933-2307-48c8-b68f-c9a4a2a3421b`

I added the `/v2/` part and changed `task` to `tasks`
