### ISSUE TITLE
Donation trouble

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1919]
Hi,

I'm new here, but I already fell in love with this website :) Amazing idea and a great job!

This morning, when I reached level 2, I donated 5$ (PayPal) but I didn't receive anything (no gems, and ads still there).
I found in an other issue that sometimes a manual intervention is necesarry.
So here my User ID: de9c8079-aa01-441f-9fce-8d7305b9dc80

Thanks for your help!

**Comment by lefnire** [comment]
hmm.. strange, the IPN might just be waiting in the queue for some reason (sometimes paypal can take a day or two). Anyway, I added gems & removed ads for ya
