### ISSUE TITLE
Switch positions of gold/silver

### ISSUE THREAD

**Issue by geebru** [HabitRPG/habitica#192]
Bug: Vertical position of gold/silver

Up until 5 minutes ago I was under the impression that gold led to silver coins. I think having gold before the silver icon is confusing. Can we switch the two? (Silver LEADS to gold LEADS to future currency)

**Comment by StanLindsey** [comment]
EDIT: I was completely wrong =P

**Comment by wc8** [comment]
See #51

**Comment by lefnire** [comment]
No, Gold and Silver are both in-game currency. It's just like dollars and
change. "Tokens" are real-money currency. You currently don't see tokens
anywhere unless you click "reroll"

**Comment by geebru** [comment]
So as a moment of regrouping and figuring this out - do 100 gold make a silver or are silver separate? I'm getting this mindset from EVERY RPG / MMO on the market (copper leads to silver leads to gold leads to etc.).

**Comment by lefnire** [comment]
It might currently be 10 silver make 1 gold, if so that was a mistake. I'll
change that when I get the chance.

**Comment by geebru** [comment]
So silver does go into gold - in that case I stand by my request to swap the position of the two :)

**Comment by lefnire** [comment]
i dunno, wow does it the same way: [backback screenshot](http://images2.wikia.nocookie.net/__cb20091228031804/wowwiki/images/b/b1/Backpack.png)

**Comment by geebru** [comment]
I must be rusty on my WoW knowledge (I played that forever and could have sworn it was the other way around). If I'm alone in my opinion we'll leave it at that - I might be the lone soul that gets confused easily.

**Comment by lefnire** [comment]
Naw, we'll keep it open and wait for a few +1s. If not we'll close

**Comment by wc8** [comment]
It is sometimes vertical in habitrpg, only it doesn't line up smoothly (#37).
- Gold
- Silver

**Comment by StanLindsey** [comment]
I guess its based on the idea that £1.50, $1.50, Gold 1, Silver 50. 

Also I was completely wrong. Oops. I wondered why my silvers kept changing so much.

The confusion may still be an issue, though now major; I've never seen silvers referenced anywhere but have seen quarters/tokens.

**Comment by lefnire** [comment]
That vertical alignment is definitely a design bug.

**Comment by horusofoz** [comment]
@blackpandemic As it appears most people are settled on the current placemen (no +1's) are you cool to close this ticket?

**Comment by geebru** [comment]
Of course - if I'm the only confused one, let me wallow in my own confusion :)

**Comment by lefnire** [comment]
vote this card if we want copper added: https://trello.com/card/add-copper-to-gp-system/50e5d3684fe3a7266b0036d6/225
