### ISSUE TITLE
drops occur on first two Daily tick-offs every day (not random)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#1921]
For the past several days, the only time I have received drops of eggs or potions has been first thing in the morning when I've ticked off my first two Dailies. I realise that randomness does sometimes create "patterns" that seem meaningful, but this has been so consistent that it does seem to be a bug - it's always my first two Dailies that produce drops, and never anything else. I'm using Chrome 31.0.1650.57 on Mac OS 10.6.8 and my user ID is d904bd62-da08-416b-a816-ba797c9ee265. My custom day start is set to 0. My time zone is GMT+10.

**Comment by paglias** [comment]
Dailies with a +10 streak have a 100% chance of creating a drop. Is this
your case?

**Comment by Alys** [comment]
Yes, that's the case. That explains what I've been seeing. Thank you. 

But isn't there now a maximum of two drops per day? I think I read that somewhere in another github issue. If I'm wrong, ignore the rest of this post! :)  This means that drops are no longer random as soon as you get two long streaks going. I'm concerned about this because random rewards are an excellent motivational tool [1] - much more so than predictable rewards. I used to feel excitement every time I ticked off a task, wondering if I'd get a drop, and I'd push myself to do more tasks to increase the chance of a drop. It's sort of nice to get two drops first thing in the day, but it makes the drops routine rather than random, and makes the rest of the day less rewarding. HabitRPG is a bit less fun now, and that makes it a bit less effective.

I had thought that the random drops were one of HabitRPG's cleverest features, because they used behavioural psychology to increase motivation, so I'd like to suggest that this policy be rethought. However I'm aware that I know nothing at all of the thoughts that have already gone into it, so there might well be good reasons for it that I'm not considering! Was it discussed anywhere that I'd be able see the discussion so I could learn about the reasons it was done? 

[1] http://www.jasonshen.com/2013/using-variable-rewards-to-drive-behavior-change/   and other links from a google search for "random rewards"

**Comment by snicker** [comment]
I'm in complete agreement with @Alys, we should never have a 100% drop chance for anything

**Comment by paglias** [comment]
@Alys yes there is a 2 drops/day limit.

@snicker @Alys this has been discussed somewhere else (not in a specific issue, though) I agree with you and would like to have a different behavior also because habits and todos are now surely less rewarding than dailies not having the streak bonus

**Comment by snicker** [comment]
@lefnire is there a location for this discussion? I'm not suggesting that the streak no longer affect drop chance, but maximum probability should maybe be no more than 75% chance, with the maximum of all factors combined (task age/value, streak, etc)

**Comment by Alys** [comment]
Thanks @paglias and @snicker! 

As a workaround, I've decided to delete and recreate my dailies when they get to a streak of +10. The random drops are more important to me than the streak achievements.

Is it also worth reconsidering the 2 drops/day limit? Perhaps after the second drop, the chance of future drops is merely reduced (perhaps reduced a LOT if you want to strictly limit the rate at which people can accumulate pets)? Late in the day, it would be nice to know that there is still a small chance of a random reward.

**Comment by paglias** [comment]
Ok, I found the thread where this problem first came out, it's #1625 but I opened #1922 so that we can discuss it there
