### ISSUE TITLE
Setup CI to deploy develop to beta on passing commits

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1924]
(self-assigned). Need to setup continuous deployment, so that `beta` will automatically update with `develop` commits (as long as the tests pass). Couple snags I'm hitting:
- The real tests are in habitrpg-shared, not habitrpg... so "passing tests" difficult to determine
- Travis has CI [integration with Heroku](http://about.travis-ci.org/docs/user/deployment/heroku/), but it requires putting your heroku API key into your .travis.yml file, which seems like a security issue. I need to investigate
- If ^ is a no-go, I'll investigate deploying from Drone.io or Codeship.io

**Comment by snicker** [comment]
should probably write some tests for the site when we implement features

**Comment by AdrienLemaire** [comment]
Yes, need to document the process on how to write tests for habitrpg, and CI should deploy only if tests pass and code coverage > 80% (or if new code contains tests)

**Comment by lefnire** [comment]
Ok, maybe I'll hold of on CI then until we have some tests in place. When we get them, want me to add y'all's emails to the deployment status?

**Comment by AdrienLemaire** [comment]
sure

**Comment by lefnire** [comment]
In the mean time, I'll see if there's a way I can give y'all access to push to heroku/beta without needing some of the other permissions (like editing/viewing env vars, what with stripe/paypal/gmail credentials & all). I just hate being you coding gurus' bottleneck.

**Comment by AdrienLemaire** [comment]
If you use a tool like jenkins or buildbot, we should be able to access a waterfall interface, login, and have perms to force a build, without needing to see the code.

**Comment by lefnire** [comment]
Looking like we have some pretty solid tests in place nowadays, thanks to @djuretic @colegleason and the like. Might be worth revisiting this so bug-pushing @colegleason, @paglias, and @SabreCat don't have to wait on me to get their changes live. The way I see this going down is we start using master again. Beta tracks develop, production tracks master. For the most part, they'll be identical - but every once in a while we'll want something only on develop (like Cole's cluster test). 

Ok, so by [the docs](http://docs.travis-ci.com/user/deployment/heroku/) it looks like we have to put the encrypted deployment API key in the travis.yml file. Does anyone think this would be a security issue if public?

**Comment by colegleason** [comment]
I think if it is encrypted it should be fine, but maybe I misunderstand.

On Fri, Jan 24, 2014 at 7:35 PM, Tyler Renelle notifications@github.comwrote:

> Looking like we have some pretty solid tests in place nowadays, thanks to
> @djuretic https://github.com/djuretic @colegleasonhttps://github.com/colegleasonand the like. Might be worth revisiting this so bug-pushing
> @colegleason https://github.com/colegleason, @pagliashttps://github.com/paglias,
> and @SabreCat https://github.com/SabreCat don't have to wait on me to
> get their changes live. The way I see this going down is we start using
> master again. Beta tracks develop, production tracks master. For the most
> part, they'll be identical - but every once in a while we'll want something
> only on develop (like Cole's cluster test).
> 
> Ok, so by the docs http://docs.travis-ci.com/user/deployment/heroku/ it
> looks like we have to put the encrypted deployment API key in the
> travis.yml file. Does anyone think this would be a security issue if public?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1924#issuecomment-33277488
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
I thought so too, just want to verify with you. Encryption has always been a topic I don't understand well

**Comment by colegleason** [comment]
Ah, this is cool: http://docs.travis-ci.com/user/encryption-keys/

So they take the environment variables like HEROKU_KEY=bfasjdfaisuhf and
encrypt all of that using our project's public key. Then when they parse
the YAML, they decrypt the secure variable using the private key and
release that environment variable to the program.

Assuming we trust Travis's implementation, it looks fine to me.

On Fri, Jan 24, 2014 at 7:40 PM, Tyler Renelle notifications@github.comwrote:

> I thought so too, just want to verify with you. Encryption has always been
> a topic I don't understand well
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1924#issuecomment-33277658
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by djuretic** [comment]
I agree, Travis' encryption method looks ok.

**Comment by lefnire** [comment]
So we're cool to have our _encrypted_ Heroku API key publicly visible in .travis.yml then? Cool beans, i'll get started

**Comment by Alys** [comment]
Beta is now used for specific non-`develop` branches so we no longer want this.
