### ISSUE TITLE
Ads still there

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1927]
Hello,

Yesterday I opened an issue (https://github.com/HabitRPG/habitrpg/issues/1919) because my donation had not been taken into account.
After lefnire's intervention I got the Gems (and now I know a PayPal donation can take few days), thanks for that, but ads are still displayed.

I'm sure it's not expected, could you check my account again please?
User ID: de9c8079-aa01-441f-9fce-8d7305b9dc80

Thanks.

**Comment by lefnire** [comment]
Let's try to keep things centralized if possible (re-opening old tickets if not solved & such). Can you try again? Double checked the account and the flag is set properly, I think we may just need a hard refresh on your account

**Comment by ghost** [comment]
Sorry for not re-opening my old tickets.
It's ok now, ads disappeared after log out.

Thanks again and have a nice day.
