### ISSUE TITLE
Issue/Suggestion: Losing an item and maybe death should be less harsh

### ISSUE THREAD

**Issue by etryn** [HabitRPG/habitica#1928]
Hi,

Not sure if this constitutes a real issue or not, but I died a week or two ago and am still suffering the consequences. Since "losing a random piece of armor" actually means losing all items in that armor slot tree (is this how it should be?), I actually lost several pieces of armor. I was just thinking about how this is a permanent set back (I will always be behind several hundred gold compared to others at my level). Considering that you also lose all your gold and a level, I think death may be too harsh.

From reading back on older issues, I saw that death has already been made less harsh than it originally was. I know if I wanted to play safer, I could simply delete the dailies that I struggle to do each day. However, I think being punished for failing to do those dailies is an integral part of the game and I do /want/ to be punished, so players shouldn't be encouraged to delete their dailies. Currently, though, there is essentially no punishment for performing poorly (losing HP is pretty much inconsequential except that it brings you closer to death), and then once you die you suffer pretty extreme consequences. As had been said in previous comments, it's somewhat demotivational.

My thinking was that it might better if you randomly lost either one item OR a level OR all your gold. Or, at the very least, maybe losing one item should really mean losing one item, and I should have lost only my red armor instead of my red armor and my plate armor and my mail armor and my leather armor. I understand that death shouldn't be too light or we won't be motivated by trying not to die, but if you accidentally forget to purchase a potion or miscalculate how much HP you will lose that night and the result is a very serious setback in the game, then I think death is too harsh.

Also, is there any way to "punish" players more lightly for general poor performance even when you don't die? What if a random pet from your stable might run away occasionally because you've been a poor owner? That could be cute and not too severe of a consequence, but still one you would want to avoid. Currently, death is really the only punishment and there is nothing milder than death.

Sorry for the wordy post, but I'd love to hear others' thoughts on this! Thank you!

**Comment by wc8** [comment]
See ongoing discussion on [Death Mechanic](https://trello.com/c/k2MWBcxl) and [Death Warning](https://trello.com/c/NpknHuDm). Can you share your ideas there?

P.S. link to this discussion added to Death Mechanic card.
