### ISSUE TITLE
Templates and Habit Organization

### ISSUE THREAD

**Issue by KellarW** [HabitRPG/habitica#193]
I just started using this after seeing it on kickstarter.  I think it's a great idea to use game theory to help people change (or continue) their habits.

I had three thoughts on the structure.  One is that it would be nice to be able to have different habit sets.  So, if you wanted to have a set of fitness habits it could be in a different grouping than self improvement habits.

The other thought is to be able to set up different templates and have the templates sharable or available at a group level.  So dieting friends can see your dieting habits, but not your TV watching habits.

This would also open the door for promoting popular or useful templates.  Perhaps a nutrionist might set up a list of food choices. With food categories as habit sets.  

The last thought I had is to be able to hide/show the plus and minus buttons.  A task could be positive or negative, but seeing the button makes it harder to want to track a negative actions and easier to want to track a positive action.

The plus and minus button could be hidden, so a person can log what they ate, and the results would follow.

-Kellar

**Comment by wc8** [comment]
Habit Sets sounds like #48 Tags & Categories, see also [Trello 43 Tags and Categories](https://trello.com/c/q7v02jAw).
Privacy Options for tags and categories added to: [Trello 9](https://trello.com/c/pxics3ZM)
I'm not sure if this is what you mean, but it is not a plus-and-minus button: it is a plus button and/or a minus button.
In cases where an item has a plus and a minus button, the habit has a direct opposite: 
Take Stairs/Elevator. + represents stairs, - represents elevator.
You either took the stairs or you took the elevator. The habit was either positive or negative.

**Comment by KellarW** [comment]
For the +/- buttons, the idea I had is that you when you set a habit to be either positive or negative, you could also set the habit to not show the button. This way you could have one habit for "Drank Soda", and another for "Drank Water". You would not know if the habit was a positive or a negative habit unless you looked at edit section. 

-Kellar 

----- Original Message -----

**Comment by horusofoz** [comment]
For the +/- buttons request, either option can be toggled under edit task as per below:
![Image 2](https://f.cloud.github.com/assets/3202339/100903/090c9424-6886-11e2-9f47-148caff1d746.png)

For templates, would this [idea](https://trello.com/c/dwIeOjZQ) encompass your proposal?

With the above in mind, would you be cool closing this ticket?

**Comment by wc8** [comment]
@KellarW is the idea to kind of trick yourself into not knowing the consequence of what you're clicking?

Thus, "Water" would replace the + button and "Soda" would replace the minus button. 
So, I click "I drank Water" I can't see a + button, so I don't know I'm getting rewarded. 
I click "I drank Soda", I can't see I'm getting an HP loss?

**Comment by KellarW** [comment]
Yes, that's what I meant. 

----- Reply message -----

**Comment by wc8** [comment]
Vote here for [Named Habit Buttons](https://trello.com/c/2Ky5TOlh)

**Comment by wc8** [comment]
Since the [idea (Library of Crowd Sourced Tasks)](https://trello.com/c/dwIeOjZQ) @horusofoz mentioned does relate to templates, I'm closing this. @KellarW, you can still comment here if we've missed something.
