### ISSUE TITLE
Hatched Pets missing

### ISSUE THREAD

**Issue by JesperDramsch** [HabitRPG/habitica#1931]
A couple of days ago I was pretty happy to have hit the 40 pets mark (and above). A little later however, I was down to 38 pets.

**Comment by paglias** [comment]
Is the pet count correct now? I mean it says 38, can you count manually how many do you have?

There was a bug that caused people having more pets counted than they really had.

**Comment by JesperDramsch** [comment]
The count is right now. That's disappointing. Thanks :+1:
