### ISSUE TITLE
Challenge To-Do list

### ISSUE THREAD

**Issue by DubBub** [HabitRPG/habitica#1932]
Hello,

My sister and I created a challenge a few weeks ago (private party) and we had a to-do mission; to get a ball. The main point was we got it within a week of putting it up, and we both struck it off our respective MAIN habit page, (She being the host of the party btw), and it was gone from BOTH the MAIN habit page and CHALLENGE page. However, just a few days ago, the to-do pop back up again, this time only in the CHALLENGE page.The main page remains clear, and i know it's a relatively small problem, but it is pretty annoying striking to-dos off the list only to see them back in there, and we don't really want to take advantage of that and click it again just to get free xp + coins. Also we like to keep the To-Do list clean ;)

**Comment by wc8** [comment]
Possible temporary fix: write down your stats, check-off the task and then use Settings > Restore to undo the extra xp+coins. If you get a drop, sell the item before you do Restore. 
Then consider _Clear Completed_ for your todos.

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/1950
