### ISSUE TITLE
Days not resetting despite being set to 0:00. Also, can't change time for reset.

### ISSUE THREAD

**Issue by gorillagnomes** [HabitRPG/habitica#1933]
Every day I have logged in, and every day the tasks from the prior day are still checked off.

I've tried to change the time for reset, but it keeps going back to 0:00 and none of my dailies have been cleared to be checked again the next day. Help!

**Comment by lefnire** [comment]
every day you've logged in, it's _never_ reset for you? Hmm... what's your UUID? Re: `0:00`, be sure to enter a whole number between 0 and 24. Eg `2`, not `2:00`

**Comment by amici-ursi** [comment]
My dailies didn't reset last night either, lefnire. UUID is "psdtwk". I have a custom day start of 4, if that matters.

**Comment by gorillagnomes** [comment]
UUID is gorillagnomes. I used numbers only to change the reset time, but I didn't try that until yesterday. Before that, I hadn't messed with the time settings. It's not reset since I started 3 days ago.

**Comment by paglias** [comment]
@psdtwk there was a bug yesterday resetting everyone's custom day start, it should be working now

**Comment by gorillagnomes** [comment]
Oops. That wasn't my UUID. Here it is: db63d489-e349-41f4-8c19-48a27d34a418

**Comment by amici-ursi** [comment]
UUID 94ddad44-d10a-4417-b9a9-75d6f89584e1
Thanks @paglias I'm trying a temporary day start of 14 (about an hour from now) to force a reset of my dailies.

**Comment by lefnire** [comment]
@psdtwk that's gonna be for tomorrow, so it won't work. If you and @gorillagnomes want, I can set your `user.lastCron` (aka, "last login") to yesterday and see if that triggers a new day for you?

**Comment by gorillagnomes** [comment]
@lefnire  that would be awesome!

**Comment by lefnire** [comment]
ok, both give that a try

**Comment by gorillagnomes** [comment]
@lefnire  No dice, muchacho. Still the same

**Comment by lefnire** [comment]
I think y'all might be hitting https://github.com/HabitRPG/habitrpg/issues/1057 then. I think you hit the 0:00 bug https://github.com/HabitRPG/habitrpg/issues/1929 first (which was fixed), but are now _also_ running into #1057 (which is not yet fixed). Can you give that ticket a gander, and if you think it's the same issue close this one and follow that one?

**Comment by gorillagnomes** [comment]
@lefnire  - yes, that's the same problem for me

**Comment by lefnire** [comment]
kk, let's follow there

**Comment by amici-ursi** [comment]
@lefnire my dailies _did_ reset when 14 came around eight minutes ago. I'm adjusting the day start back to where I had it before. Thanks for your help, all.
