### ISSUE TITLE
"Reset" and "Restore" are confusing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1934]
Per @wc8, users have complained in Tavern that "Reset" and "Restore" are too easily confused. They're in close UI proximity, with similar yet _very importantly_ different functions, and extremely similar names. I myself have found myself accidentally saying "Reset" when I meant "Restore" in conversations about features.

Compounding the issue is the fact that the Reset popover runs off the screen:

![screenclip](https://f.cloud.github.com/assets/4501321/1633634/7e0a8402-578c-11e3-95f0-fec6cb3d4158.png)
(I accidentally my whole account)

Suggestions:
- Rename one or the other or all buttons. Possibilities: "Reset Account," "Delete Account," and "Correct Character Stats".
- Give the "Restore" (or whatever name) button a milder color, since it's a less severe action than Reset or Delete.
- Include icons on the buttons. Maybe an exclamation mark on Reset, a refresh button style swirly arrow on Restore, and a big dark X on Delete.
- Move Restore out of the Danger Zone to the Misc header.
- Improve the popover text on the buttons. "Start over, removing all levels, gold, gear, history, and tasks." / "Manually change values like Health, Level, and Gold, to correct mistakes or work around bugs." / "Cancel your HabitRPG account. You will need to create a new account to log in with this username and/or email address."

**Comment by lefnire** [comment]
I'm all for all of those options. Might not be able to get to this till a bit later, in case you wanna PR me first. In the mean time, you're whole account was reset? Do you want me to restore from yesterday?

**Comment by SabreCat** [comment]
Oh, no, haha. That was a joke. I was referencing the "I accidentally the whole (fill-in-the-blank)" Internet meme, with respect to the wording produced by the chopped-off popover bubble.

**Comment by SabreCat** [comment]
As for the PR, I'm good for it. I would kinda like to see my extant PR get merged before I get too deep into further tweaks, but I'll take a look at it after I work on that items.coffee task you gave me. Assigning myself.

**Comment by lefnire** [comment]
Haha! See, I got the meme but I thought you _accidentally_ missed the word ("he totally did that meme on accident"). So meta!

**Comment by SabreCat** [comment]
Reviewing my list, I _might_ end up needing help getting the icons on there. I'll speak up if I can't figure it out.

Relevant feature question: does (currently-named) Reset wipe out your pets? Or can only a Delete do that?

**Comment by lefnire** [comment]
Just lists, items, stats. [The code](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L320tL341).

**Comment by SabreCat** [comment]
Got it. For a moment I thought, "why not pets?", but then realized that pets might have been bought with real money, and take-backsies on that would be not so cool.

**Comment by nafoster** [comment]
If you're looking to add icons and since we're using Bootstrap, try using Font Awesome (http://fontawesome.io/). Completely customizeable SVG icons and works very well with Bootstrap, since it was made for it!

**Comment by lefnire** [comment]
FWIW, we haven't added fontawesome to the repo yet, but we plan to. if you decide to give it a try and find adding it to the repo a challenge, ping me

**Comment by wc8** [comment]
I assume delete account warns user and wipes pets? In that case (delete) I think everything should go, since user is basically saying, forget you ever knew me.

**Comment by SabreCat** [comment]
@wc8: That's my understanding, yeah. I think it drops that user from the database.

**Comment by lefnire** [comment]
Yep, user is deleted from the database entirely.

**Comment by SabreCat** [comment]
Hey @lefnire, @nafoster, I am in fact having trouble adding Fontawesome to the repo. It's supposed to go in a "component.json" per the documentation, but I'm not finding that anywhere. Do I need to add [Component itself](https://github.com/component/component) first?

**Comment by paglias** [comment]
@SabreCat propably the documentation references the old name of bower.json which was component.json, so i think you can try using bower.json

But, personally, I don't like we're adding a new library to habitrog every week, last week it was +50kb for emojis now we want to add FontAwesome which is 18kb of minified css + the fonts (40kb only for the eot format, hoping other file types are not going to be loaded). 

It's not only a matter of size but also that we're not going to use it for the whole site but only for a bunch of icons. Can't this be avoided?

**Comment by SabreCat** [comment]
Hmm, I tried bower.json, but it didn't recognize FontAwesome, at least according to the suggested syntax. I could try pointing it directly at the Git URL instead of using the repo name by itself, maybe... I'll keep toying. @lefnire would have to speak to the strategic concern.

**Comment by snicker** [comment]
@paglias I understand your concern with emoji, we could do the work serverside so we don't have to push the huge js array to the client...
