### ISSUE TITLE
certain emoji images are not loading

### ISSUE THREAD

**Issue by snicker** [HabitRPG/habitica#1935]
It appears that a few Emoji images are not loading, star, heart, a few others.

This is happening because the Gemoji library that is being used for images has symbolic links in the repository:
https://github.com/github/gemoji/tree/master/images/emoji/unicode

and bower does not install the symbolic links. What we get are missing items.

I'll propose manually downloading the images and building them into habitrpg-shared. 

Opinions @lefnire ?

**Comment by snicker** [comment]
so @lefnire, are we cool with the solution of merging all the images into habitrpg-shared? If so, merge the PR (I can't) and I'll update the code to point to the new image location

**Comment by AdrienLemaire** [comment]
LGTM

**Comment by lefnire** [comment]
Merged, added you as habitrpg-shared admin (sorry I forgot to)
