### ISSUE TITLE
Party Members' Pet Count is Wrong

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1936]
When I click on my party members to see how many pets they have, every single one of them is listed as having 90, even though I know for a fact that this isn't true. (One of my friends refuses to hatch any pet at all, only selling them).

**Comment by lefnire** [comment]
@snicker bindonce concerns?

**Comment by snicker** [comment]
@lefnire nope, don't think that's from something I did. It's showing the number of pets that the logged-in user has, not the number of pets of the targeted user. Seems to be an issue with any profile pop up

**Comment by snicker** [comment]
It is something I fixed though

**Comment by lefnire** [comment]
> don't think that's from something I did
> It is something I fixed though

I love it! You're the man!
