### ISSUE TITLE
Justin is invisible in honor of Turkey Day

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1937]
When the Turkey Day announcement came out, I eagerly rushed to look at each of the NPCs' outfits. But alas, Justin has simply opted out of the holiday, leaving only his disembodied voice to guide newcomers!

![screenclip](https://f.cloud.github.com/assets/4501321/1636446/b6d3fad8-57ce-11e3-9f94-ab6a077c3461.png)

Firefox on Win7, beta.habit. Tried a couple of force-refreshes, no good. I don't see any relevant errors in the console.

**Comment by lefnire** [comment]
fixed
