### ISSUE TITLE
Turkey increases pet count but not max

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1939]
I have 70 regular pets plus the veteran wolf. Previously, my pet total was 70/90. Today the turkey showed up, and my pet total is now 71/90. Either the turkey should not be counted, or it should increase both the count and the max.

**Comment by SabreCat** [comment]
Ah, good catch. We had this trouble with the Veteran Wolf before, too, but straightened it out eventually.

**Comment by paglias** [comment]
yes yes, we have to manually update the list of special pets every time one of them is added... we'll probably wait for https://github.com/HabitRPG/habitrpg-shared/pull/45 to be merged and will also fix this.

**Comment by snicker** [comment]
https://github.com/HabitRPG/habitrpg-shared/pull/45 merged, this will be fixed when it goes live
