### ISSUE TITLE
Feature: Fitocracy Integration

### ISSUE THREAD

**Issue by jsamurai** [HabitRPG/habitica#194]
_Edited by wc8: Vote for this feature here: [Fitocracy](https://trello.com/c/WqllBvgX)_
Could be a good idea considering HabitRPG and Fitocracy are both video game based.

**Comment by wc8** [comment]
Indexed on Trello [Fitocracy](https://trello.com/c/WqllBvgX)

**Comment by horusofoz** [comment]
@lefnire Shouldn't this be closed as with the other integration requests noted in #169: Master List of Features Requests and on Trello?
