### ISSUE TITLE
Turkey pet is invisible

### ISSUE THREAD

**Issue by OmerN** [HabitRPG/habitica#1940]
When enter the stable there is a space between the veteran wolf and the "Gold footprint".
There is a tooltip when hovering the mouse over the blank space "Turkey"
It's selectable. when selected the avatar seems to be without pet.

![hrpg_turkey](https://f.cloud.github.com/assets/6056164/1637667/62920b80-57f2-11e3-8356-def972a9b911.png)

**Comment by lefnire** [comment]
Hard refresh

**Comment by OmerN** [comment]
Fixed,(so called). turkey visible after refresh
