### ISSUE TITLE
Can't Log in Chrome

### ISSUE THREAD

**Issue by bennypowers** [HabitRPG/habitica#1941]
I can't log in using Chrome 30.0.1599.101 Mac 10.8.5:
at habitrpg.com/static/front, the PLAY button brings me to http://habitrpg.com/static/front#tasks (instead of habitrpg.com/#tasks)

Works in Safari, FF on same computer. Works on chrome android

**Comment by SabreCat** [comment]
Huh, this sounds like the behavior I hit with #1875 ... but I actually solved that by switching _to_ Chrome. Can you try clearing your local user data as described in the screenshot on that issue?

**Comment by bennypowers** [comment]
Yerp, that fixed it!

Thank you very very much!

Benny Powers
Licensed Israel Tour Guide

In Israel 054-482-5726
In Canada 705-300-0072
In the USA 601-255-3532

bennypowers.com
