### ISSUE TITLE
free exp, money from dailies

### ISSUE THREAD

**Issue by yashkochar** [HabitRPG/habitica#1942]
If you (accidentally) complete a daily task and the click it again so that it is unfinished, your experience and money is reduced. However you still retain the bonus experience and money gained from streak bonus. There is no rollback for the bonus.

![bug](https://f.cloud.github.com/assets/1310989/1638987/41278c8e-5817-11e3-8f31-79e43ee7c644.png)

**Comment by paglias** [comment]
follow at #964
