### ISSUE TITLE
"Pets Found" of Party members are the same as mine

### ISSUE THREAD

**Issue by filkaris** [HabitRPG/habitica#1943]
All the party members display that they have 15 pets, same as me, even the guys that are lvl 1 and lvl 2. 

So I know for a fact it's inaccurate.

It also did the same yesterday, when I had 13 pets.

**Comment by SabreCat** [comment]
Duplicate of #1936. Been fixed in the code, but might not have deployed to the site yet.

**Comment by filkaris** [comment]
You're right! Sorry for not searching :innocent:
