### ISSUE TITLE
[Feature] Skills

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#195]
_Edited by wc8: Vote for this feature here: [Skill Item Type](https://trello.com/c/UTWW66Uu)_

First of all i just want to note that this is not 100% my idea. the original idea is from an iPhone app called Level Me Up HD!, but i did tweak, take out, and add some things to it, besides the app hasn't updated in over 2 years so i think its ok, and i tried to make it work as perfectly with HabitRPG.

Now for the features
Skills will be on a different page (so the page wont get to crowded)
Skills are not connected to habits
Skills are another option like Habits, Dailies, Todos, and Rewards

Every Hour on the skill gains exp depending on how often you practice your skill
(The experience on the skill is not linked to the experience on your character)

Skills level up also like rpg
- Time: 0:15, 1:00, 2:20, 3:55, 5:35, 7:40 etc.
- Variable: 4, 10, 19, 33, 57, 82

just an example, i'm sure you can make an algorithm for it

Gain extra Exp. from gaining a level in the skill, as a bonus
ex: lvl 2 = .2 exp/gold, lvl 3 = .3 exp/gold, lvl 21 = 2.1 exp/gold

Compete with friend on skills
This could work perfectly with your guilds idea, it would make it easier to compete with your friends

Integrate with other apps (Self-explanatory)

Undo button (for obvious reason)
For if you accidentally add time or variables and you want to take them out

If you don't practice a skill in a week or so, your experience in that skill will slowly start to decrease
I added this because in my personal experience, when i haven't play a certain song on guitar in a very long time, i notice that i'm not as good as i used to be, if you stop doing something for long enough you will slowly forget it

An option that you would lose HP if you don't practice in more than a week (which you will be able to turn this option on of off if you want)

I've added pics below, i tried to do it on paint but it took to long so i just started drawing the rest, I know my drawing isn't the best but at least you can tell whats going on, and my writing is pretty neat and easy to read
![SkillsRPG](https://f.cloud.github.com/assets/3344983/91260/ce353974-6596-11e2-9c80-8d7e4bc03dea.jpg)
![IMG_1433](https://f.cloud.github.com/assets/3344983/91335/1a5f89ae-659b-11e2-851c-08b1369c028d.JPG)

You can download the free version of Level Me Up in the app store for a more hands on understanding of what i'm trying to explain.

If you do decide to add this then i understand it is a big update, but I think it will be very useful. This would be very helpful because some of my habits are Guitar, Piano, and Producing which would work so much better as a skill

And lastly, if you have any questions about it, please ask before you close the thread just so it's understandable :)

**Comment by mleon246** [comment]
I get it but Guitarist skill as an abstract concept compared to something like running.
If I want to level up Running then we could measure by time or distance. (EX: under 1 mile is lvl 1 and mile 1-2 is lvl 2)

Regardless having the ability to create skills and add math to it would advance the project!

**Comment by wc8** [comment]
I'm making an index of requests on Trello (where users should be able to vote for ). 
This is similar to elements of #39, is that right? 
Expanding on it by adding durations (something that has come up before).

**Comment by Nelmalih0** [comment]
mlean246: You could use it for running, i thought about that, i just used guitar because i play guitar, but running works perfectly
wc8: If i'm correct, #39 is about progress about a task/habit until you reach a goal
Skills are about getting better at skills you have or want to have, HabitRPG could help encourage you to get better at skills
If you download the Level Me Up app that i mentioned before, you could have a better understanding on what skills are, that's where i got the idea

**Comment by wc8** [comment]
@Nelmalih0 I think the thread, if not the first post, (see second post), is about progress in a group of related tasks in tags & a final goal (boss battle). I'll try to look into Level Me Up. 
Update: I glanced at the app. I don't have an iphone. It really seems related. I'm sorry if I'm not appreciating the difference. I don't mean your post isn't different at all.

**Comment by Nelmalih0** [comment]
one of us clearly doesn't understand the others point lol :P

**Comment by wc8** [comment]
Right, I don't get it yet, that's why I'm asking.
Let's see, is your request: 
_Awards for achieving a certain number of completions of a single habit?_
For example: if a habit is: 1h play piano, clicking it 100 times gives you: "Congratulations You've completed 100 hours of Piano?"

(By the way, I know a piano teacher who likes to say, _People say Practice Makes Perfect. Practice Makes PERMANENT_)

**Comment by Nelmalih0** [comment]
Not exactly, you would start the timer and practice piano, then when you are done you press stop and it records the time as experience for that skill, and after a certain amount of time, you gain a level
the other field is if you played piano for 15 minutes but didn't start the timer, you can add your time manualy
the idea is based of of the Level Me Up app, heres a video of it http://www.youtube.com/watch?v=rECjoxfsJZo
the piano is just an example, obviously if you were gonna add piano you would do time instead of variable, but the number is just another option for anyone that had a use for it

**Comment by geebru** [comment]
I feel like this is quickly slippery sloping into creating an overly complex app. The simplicity here is what's key. Time tracking (which is what you're proposing) isn't really a to-do list kind of thing.

Seeing that basic analytics are already in place, adding a "ceiling" and a "floor" where you want to improve would be the best way (to me) to get "skills" in without adding overly complex time keeping. If you fall below 'x' you receive a (fairly) major HP reduction, but get to 'y' and you get a sweet XP boost.

**Comment by wc8** [comment]
I see the difference now.
Part of the reason why I thought (think?) they are related is that there can be a number of different kinds of practice or habits that build a skill. So you might have hours of guitar practice and of music theory study involved in becoming a good musician. (I saw writer on the site and as a writer, I know many different "habits" go into improving that skill!)
This is interesting to me, because I currently use elements of the pomodoro/timeboxing method for helping me move forward with big projects and routine tasks. [Note: At the end of the buzzer I mark the 20m of X task complete]
One possible method of implementing this would fall under integration.
Another part of this (if I'm not mistaken) falls under awards (#59).

**Comment by Nelmalih0** [comment]
blackpandemic: i don't want to complex the app, skills is just another option like Habits,Dailies, Todos, and Rewards.
the time tracking only applies to skills, not habits or anything else, its there because, according to scientist, it takes 10,000 hours of practicing a skill to master it
there is no penalty for not practicing a skill except for losing experience on that skill (not on your person)
but you gave me a good idea, there is an option that you would lose HP if you don't practice in more than a week (which you will be able to turn this option on of off if you want)

wc8: I think you are confused a little, habits and skills are not linked (I edited the main article to add that fact)
skills have their own exp and levels, but you are rewarded for practicing your skills
and i don't completely understand what you mean by #59 and integration

**Comment by geebru** [comment]
I see your point - I still think it should be user-controlled to do your time, not an app addition. Practice 1 Hour is your task - it's a discipline thing to me to do that for an hour, hence my idea for a ceiling/floor as opposed to actual, granular time tracking.

:+1: For a "neglect" versus "stay with it" mechanic for skills / dailies / habits, etc. which I can see being skills as well.

**Comment by Nelmalih0** [comment]
You can do it 6 separate times for 10 minutes , then you would get your exp. it all adds up
and if you look at the picture (that i so poorly drew) you can add time manually

sorry that i'm really bad at explaining things, it would be a lot easier if i was talking to you in person :P

**Comment by mleon246** [comment]
The best explanation i can give is:
It's a habit to run every day and you get rewarded for it.

It's a skill to improve your distance/time where the improvement is the reward.

This can be done without using an Exp Formula by allowing the player do manually level up and keep checking off that the habit has been done.

If it where me I would combine them into habits you do and then have the menu "would you like to improve this skill"
![Level](https://f.cloud.github.com/assets/2007282/91895/238ba5fe-65b3-11e2-93d4-2b59fcfec287.png)

This is what I see as a middle ground between the two.

**Comment by hookang** [comment]
Epic Idea.

**Comment by wc8** [comment]
Trello [Skills](https://trello.com/c/UTWW66Uu)

**Comment by Nelmalih0** [comment]
mleaon246: I see what you're saying, but i intended it to be separate form Habits
hookang: thanks, i thought it would fit very well, i just wanna know what @lefnire thinks
wc8: awesome, i just voted for it :P

**Comment by wc8** [comment]
I added a very temporary description. I hope later to improve it. I think there's potential in the idea and it'd be neat to see it tailored and enhanced for HabitRPG. Integration with a pomodoro/timer app or website could possibly even allow for a timer element without overwhelming the habitrpg interface.
One thing: I showed habitrpg to another user and they found habits/daily/todo, even with the explanation on the site confusing. So there could be an issue with adding another term, but maybe with a good explanation.

**Comment by Nelmalih0** [comment]
Most things you have use it to understand it
A friend of mine that is in the army told me "You can read 100 books about guns, but until you actually hold one, you will never know how to use it."

**Comment by mleon246** [comment]
It makes sense to separate them out except that it would require additional work from the coder perspective and the user who whats to get in habit of ____ as well as trying to improve the skill itself would have to go through extra menus creating confusion to new users/low tech users that require simplicity.

The combination would be treated as an optional add-on to any habit instead of a section to itself.

User Example:
My grandfather who plays games would use it but gets confused when there are too many main menu options.

**Comment by lefnire** [comment]
One big goal of Habit is to introduce complex features over time by
"unlocking", like the item store was. That way it's plain and simple to get
into, then gets more involved over time. I'm not too worried about to a lot
of interface additions as long as users graduate into them, and they can be
toggled in some cases

**Comment by Nelmalih0** [comment]
I understand that it would take a lot of work for the coder but i'm not expecting it to come out right away, it will take time
And it sounds complicated here because there are a lot of rules, but that's to the person making the app, but the user will only see the user interface, which i tried to make as simple as possible
Its like a song, a writer could spend days writing and composing the song (writing the code), then he has to get it produced and record it 50 times until he gets it right (bugs), but you only hear 3 minutes of what could have taken weeks to make (our wonderful HabitRPG app)

And what @lefnire said, he could introduce it over time so the user understands everything in front of them, then he will unlock the new skills feature and it won't be overwelming

**Comment by horusofoz** [comment]
I have drafted a proposal of how Skills could be implemented which is available to view at https://docs.google.com/document/d/1jF6ll7GdHNSttF723aJYf5K33MBZusIBylotUjsF60U/pub.

It is a simple system that allows users to tag tasks with a skill and HabitRPG does the work of calculating the skills' development. It would eliminate the set up and complexity required in some of the suggestions above such as real time tracking. 

Progress would be measured the same way as Habits/Dailys are already with the addition of mapping the tasks to skills.

This method should be easy for users to pick up and minimise work re-engineering when introducing new features. An example is the request for priority/level of importance. This example would only require a multiplier added to the skill points added.

**Comment by wc8** [comment]
So skills (example above: learning to play guitar, real life skill), would be merged with D&D skills/classes [doc](https://docs.google.com/document/d/1jF6ll7GdHNSttF723aJYf5K33MBZusIBylotUjsF60U/pub)?
Would that affect the original request to level up in a particular real life skill by logging time practicing?

**Comment by horusofoz** [comment]
@wc8 Yes it would affect the original request as it is a proposal for an alternate implementation of skills/attributes.

User's would associate the real life skill they are practising with one of the attributes. In the case of "play guitar" I would associate this with dexterity. When they practice guitar they get progress towards a dexterity skill point.

Though this may seem limited compared to being able to generate your own skill set and level them up, I think it is a much more manageable solution to code, support and that can be integrated with other proposed features such as classes, guilds, achievements, public challenges, etc.

**Comment by wc8** [comment]
@Nelmalih0 By integration I was referring to the feature request for integrating other apps into HabitRPG, effectively _integrating_ that app's or site's features into HabitRPG. So for example, the pomodoro integration feature would bring timed tasks to HabitRPG.

**Habit** "a settled or regular tendency or practice" A good habit would improve something in your life, whether it is health, skills, etc. That is why I say there are many "habits" that can improve one's writing skills.  Practicing the guitar is, in real world terms, a good habit, which improves your guitar skill. 

It did help though, for you to clarify your idea was for a new item type. I can understand wanting a new item type, but could much/all of your idea be achieved with out it?

Perhaps a few more features, most already requested, would achieve it through existing item types?

For instance:
- XP gains based on length of practice via [timed tasks](https://trello.com/c/FwSlQrR5) / [pomodoro integration](https://trello.com/c/iZlDf9J6)
- (The experience on the skill is not linked to the experience on your character) _and_ Skills level up also like rpg: 
  [Habit Goals](https://trello.com/c/Cld8EjME) request plus variation: several levels/stages, not just one final goal. XP boost on each level. + [Stat Modifiers], Skills/Classes (eg. dexterity)
- If you don't practice a skill in a week or so, your experience in that skill will slowly start to decrease: _decrease level in Habit Goals maybe?_
- Compete with friend on skills: [Party System](https://trello.com/c/GPc3MvYv), [Guilds/Groups](https://trello.com/c/OY9PDkmn), 
- Integrate with other apps (Self-explanatory)... request any apps/sites you want for Integration list on Trello
- Undo button: See [Undo Button](https://trello.com/c/RQIp0Yl5)
- An option that you would lose HP if you don't practice in more than a week (which you will be able to turn this option on of off if you want): make these features available as daily habits with [every n days](https://trello.com/c/XuVokK2V) feature or regular habits
- [Profile Page]() showing levels of achievement at practicing/improving that skill

What'd I miss, beyond the idea of a separate list of skill-improving habits/tasks?

**Comment by wc8** [comment]
@horusofoz I know at least one voter (see earlier comment in this thread) was voting for the new item feature [here](https://trello.com/c/UTWW66Uu) and I'm afraid others might be voting for #74 RPG type Classes which request hadn't made it to the trello board yet. 

Sorry. I was afraid of misstating the request and thought it would be best to just link back here, but that seems to introduced confusion, since **skill** is also an RPG term. I've updated that card title for clarity.

Is it ok if we make a new card for your alternative / RPG skills/classes and put a link & notice in the current trello card so voters can adjust their votes if needed?

P.S. [Trello Card 110](https://trello.com/c/L1H6LiZ3) might represent #74

**Comment by horusofoz** [comment]
@wc8 Sounds good to me.

**Comment by horusofoz** [comment]
@wc8 My apologies for muddying the waters. 

I suggest we split the ideas into different cards and remove the link to the skills proposal in non-relevant cards to ensure accurate voting. 

Alternatively remove the card and create new ones for each idea to ensure accurate voting (may be more work than it's worth).

**Comment by wc8** [comment]
@horusofoz I'm getting a little backlogged on some things on my end; would you mind creating a new card for your idea? Or, if your proposal fits Trello card 110 (Character Stats / Attributes), just add the doc link there. Then one of us can add a link on the Skill-Item trello card to the RPG-style Skills/Classes card with an announcement (comment &/or checklist item) for voters.

**Comment by horusofoz** [comment]
@wc8 I would say this is covered by 110. Added the link and deleted it from the previous card where I think it wasn't creating confusion.

**Comment by horusofoz** [comment]
Discussion moved to [Trello Card 110](https://trello.com/c/L1H6LiZ3).
