### ISSUE TITLE
To-Do List items keep re-appearing after i check them off (but gives me xp & gold)

### ISSUE THREAD

**Issue by professorsugoi** [HabitRPG/habitica#1950]
When I check off some to-do list items on my phone, they immediately reappear.
The same happens in the browser version when I refresh the page.

It lets me keep the rewards even though they re-appear each time. They also re-appear if I delete them instead.

**Comment by eiron** [comment]
I have noted this behaviour also. The same bug seems to refund you on upgrades, but allows you to keep the kit.

**Comment by jreatherford** [comment]
Similar problem here.  Every-time I open the page, things have been rearranged.

**Comment by jreatherford** [comment]
Hey, I got it to work for me.  I _think_ it may have something to do with the mobile version syncing up with the webpage version.  If you use the app, make sure it is not running in the background of your device (turn the device off if you have too) then put everything in the correct order on the page.  Refresh the page and see if it works.  If so, try the app now.

At least, that's what worked for me.

**Comment by deilann** [comment]
Let's move all these here: https://github.com/HabitRPG/habitrpg/issues/2505
https://github.com/HabitRPG/habitrpg/issues/2306
https://github.com/HabitRPG/habitrpg/issues/2726

**Comment by kribbit** [comment]
hope i'm commenting in the right place here :x i'm having this issue as well! only with one of my to-do tasks, though. i'll consistently check it off my list, get XP and gold from it, and then at some random point during the day i'll see that the XP and gold have been taken back, and the task is there again. i even tried deleting the task -- a pop-up asked if i was sure i wanted to delete, i clicked yes, the page synced, and the task is there again! it's been reappearing for about a week now
