### ISSUE TITLE
Markdown adds extra horizontal lines in ordered lists

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1951]
Made my first Markdown ordered list in guild chat, and discovered that it throws in a HR after every line item:
![screenclip](https://f.cloud.github.com/assets/4501321/1650453/7974ba52-5a8e-11e3-835a-345487bcadb9.png)
It strikes me as unnecessary and unsightly, especially since it stretches the scrollbar to bursting after just a few line items. Can we alter this behavior so it does a raw list without dividers?

**Comment by snicker** [comment]
Is it a style issue? Or is markdown actually inserting `hr` elements after every `li`?

**Comment by SabreCat** [comment]
Looks like a style issue. This is what the Inspect Element output looks like:

```
<markdown class="ng-pristine ng-valid" target="_blank" ng-model="message.text">

    <p> … </p>
    <ol>
        <li> … </li>
        <li> … </li>
        <li> … </li>
        <li> … </li>
        <li> … </li>
        <li> … </li>
    </ol>

</markdown>
```

**Comment by JesperDramsch** [comment]
It's inherited from the .tavern-chat li and party-chat li.

```
border-bottom: 1px solid #ddd
```

**Comment by SabreCat** [comment]
Hmm, I see. Do we want that there across the board? What would it affect if we took it out?

**Comment by snicker** [comment]
You don't have to, you can just do an overriding style. Take a look at https://github.com/HabitRPG/habitrpg/blob/develop/public/css/game-pane.styl#L62-L69 for an example of overriding styles in just the markdown tag. That is where you would do it

**Comment by SabreCat** [comment]
Cool! Override styles crossed my mind, but I didn't know where the markdown-specific stuff lived. Thanks for the tip!

**Comment by lefnire** [comment]
Snicker :+1:
