### ISSUE TITLE
Link to Introduction Video in beginner's tutorial is broken

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#1953]
Copied from Tavern:
The tutorial video linked on site is dead, but I see the one on the wiki is working - I'll check that out maybe it'll answer my questions :) ~ Recon

**Comment by katerberg** [comment]
Is this still a valid issue? I see the video working properly on the main site. 

Sorry if this is considered dead. I know it's 2 months old; I'm just trying to find something easy to work on for my first commit.

**Comment by colegleason** [comment]
Unless there is some other video than the one I see, this is no longer valid.
