### ISSUE TITLE
Challenge Tasks not Updated

### ISSUE THREAD

**Issue by JesperDramsch** [HabitRPG/habitica#1954]
I created a challenge and then updated the names to be more gamified. People who joined later, got the new names, yet for me the names remain unchanged but unchangeable since they're challenge tasks.
Shouldn't these be globally updated?

**Comment by breadstrings** [comment]
Also, if you change the challenge daily status from inactive all days to active, it doesn't change the status of those who have already joined the challenge. The only option is to delete the daily and restart again, which can be undesirable.

**Comment by lefnire** [comment]
they should be updating, bug. bumping prio

**Comment by lorian** [comment]
Sadly, this also means that the cute new emoji can't be added to challenges in progress :(

**Comment by lefnire** [comment]
pushing fix. 

@djuretic I was able to use some API mocha tests to solve this one, we may want to connect sometime soon on when to use what types of tests where, so I don't step on your toes. unit-tests=habitrpg-shared obviously, but then API-tests vs e2e tests should we come up with some sort of guidelines? Or just use whatever works under diff circumstances?

**Comment by djuretic** [comment]
@lefnire We now have 3 types of tests in habitrpg:
- Karma unit tests. No database, mocked HTTP requests.
- API tests against Node server and Mongo, using HTTP requests directly.
- E2e tests against Node server and Mongo, via browser interaction (Protractor/Selenium).

I think we need all three of them.
In the e2e tests with Protractor there is not direct way to send a POST request (you only can trigger JS events, like "click", as a regular user using a browser would do). So it makes sense to have API tests apart.

**Comment by lefnire** [comment]
Perfect, makes sense! Thanks @djuretic
