### ISSUE TITLE
Challenges drawing from guild AND personal coffers?

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#1955]
I am pretty sure I had 24 gems. Then I made a new challenge in my guild and am down to 23 gems. The guild is also down a gem. I am not sure if this has happened before and I just have not noticed it. If so, I would be down three gems in all.

**Comment by lefnire** [comment]
Yes. If you created the guild (5gems is it?), then those gems get added to the guild bank, and get dipped into first (if the challenge creator is the guild leader) before dipping into user's gems

**Comment by eiron** [comment]
Yes. There were those four gems and with three gems offered for challenges
we are down to one. But I seem also to be down on personal gems too.

**Comment by eiron** [comment]
Okay. I set up another challenge and attached a gem's reward to it. The guild bank is down one gem (to zero), but I am also down one gem (to 22). For four gems attached to challenges I have now spent eight gems (as it has taken from both guild and myself each time).

So, this is still a genuine bug.

**Comment by lefnire** [comment]
k, upped your gems, re-opened ticket. Tell me guild name (uuid if possible... do we expose that anywhere?) and I'll up it's gems, in case you want to experiment between now and when I can tackle this ticket. In can anyone's feeling adventurous, [here's the code](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/challenges.js#L105tL149) handling this stuff:

**Comment by SyntaxPickax** [comment]
Ignore that first commit -- it had a typo.  The pull request should be good to go.
