### ISSUE TITLE
Pets Found value is blank on first visit to profile stats page

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1959]
Firefox on Win7, beta.habit, no JS errors.

When I first open my Stats and Achievements page, my Pets Found number is blank:

![screenclip](https://f.cloud.github.com/assets/4501321/1670197/2164955a-5c8f-11e3-8ad1-e1d1528f4a54.png)

I can see other people's pet counts in their profile popups just fine. And in fact, if I pop up my _own_ profile from e.g. a chat message, the Pets Found value appears fine... and if I then return to Stats and Achievements without refreshing, it fills in there too!

**Comment by filkaris** [comment]
Weird, why did noone pay attention to this? Happened to me as well.

This started occuring after 62aeb7087a01a251262b8185117a5b51ffa1eced.
Especially, the line:

```
strong Pets Found
-  | : {{petCount}}
+  | : {{profile.petCount}}
```

If you switch it back to "petCount", your pet count appears normally. The bad news is that issue #1936 also comes back.

I guess we can find a solution somewhere in the middle...
