### ISSUE TITLE
Plus and Minus Habits

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#196]
_Edited by wc8: Vote for this feature here: [Habit Shading](https://trello.com/c/YSXfecBt)_
Habits that are made to only have plus should turn red if it's never clicked
and vice versa
Habits that are made to only have minus should turn green if it's never clicked

**Comment by wc8** [comment]
Hm... I've thought something like this myself. It seems to fit in with the daily shading. It's another way of seeing progress/areas to work on. 
Perhaps, for plus or minus habits, the shading could turn green if frequently (+) and red if frequently (-)

**Comment by wc8** [comment]
@Nelmalih0 Please let me know if the description on Trello accurately expresses the idea.

**Comment by Nelmalih0** [comment]
I mean habits that i set to only have the minus, if I don't press it it should turn green to say that i have been good by not doing it
and vice versa
this rule wouldn't apply if the habit has both plus and minus

**Comment by Nelmalih0** [comment]
sorry, i misunderstood, you got it right :+1:

**Comment by horusofoz** [comment]
@nelmalih0 With a [Trello Card](https://trello.com/c/YSXfecBt) up for this suggestion, are you cool with this ticket being closed?
