### ISSUE TITLE
"community.habitrpg.com" website doesn't work

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#1961]
I found these links not working, I think the whole site has some problems.
These are accessible from the footer of the main Habitrpg.com page.

http://community.habitrpg.com/forum
http://community.habitrpg.com/extensions

![error](https://f.cloud.github.com/assets/6122017/2083591/19a28a36-8e06-11e3-8987-439a086b9475.png)

**Comment by paglias** [comment]
@Omnomnobot these links are working at least now. can you try again?

which problems are you encountering with the site?

**Comment by lefnire** [comment]
Yeah, it's just our Drupal forum (@Omnomnobot meant community.habit, not the main site). It has this error from time to time, I'll fix eventually (or we'll get off Drupal eventually)

**Comment by deilann** [comment]
Site is no longer used.

**Comment by fragmental** [comment]
community.habitrpg.com should probably redirect somewhere.

**Comment by fragmental** [comment]
an announcement would probably be good too
