### ISSUE TITLE
Mobile app creates disorder in some tasks (habit, dailies)

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#1962]
I tried using the mobile app, both Android and iOS. I added some tasks yesterday evening, and now in the website some tasks have changed name, now they have the name of other tasks. This happened only to habits and dailies. I think I made something unusual with the iOS application, strange behaviour though.
(sorry for my English, I hope you understand)

**Comment by lefnire** [comment]
can you verify if this is still happening, with the push from a few days back?

**Comment by deilann** [comment]
This hasn't been reverified in 2 months. Closing.

**Comment by Atomk** [comment]
Sorry, I totally forgot to write about this. After some trouble with the app I almost stopped using it, but I think the problem is solved because it happened only one time to me.

**Comment by deilann** [comment]
Thanks @Omnomnobot ! I'm going to guess the push fixed whatever was going on.
