### ISSUE TITLE
Markdown doesn't support images inside links

### ISSUE THREAD

**Issue by SyntaxPickax** [HabitRPG/habitica#1963]
Markdown supports images inside links, but HabitRPG's group chat lacks this support. For example, here are three ways that markdown supports images inside of links:

```
[![Now that's a no-hands rest with a view][2]][1]
[1]: http://vimeo.com/31878065
[2]: http://www.dpmclimbing.com/sites/default/files/uploads/images/upside%20down%20on%20salathe.jpg

[![Now that's a no-hands rest with a view](http://www.dpmclimbing.com/sites/default/files/uploads/images/upside%20down%20on%20salathe.jpg)](http://vimeo.com/31878065)

[<img src="http://www.dpmclimbing.com/sites/default/files/uploads/images/upside%20down%20on%20salathe.jpg" alt="Now that's a no-hands rest with a view" />](http://vimeo.com/31878065)
```

Github's support for markdown includes this, so here's what we should see (photo links to video):
[![Now that's a no-hands rest with a view](http://www.dpmclimbing.com/sites/default/files/uploads/images/upside%20down%20on%20salathe.jpg)](http://vimeo.com/31878065)

[![Now that's a no-hands rest with a view](http://www.dpmclimbing.com/sites/default/files/uploads/images/upside%20down%20on%20salathe.jpg)](http://vimeo.com/31878065)

[<img src="http://www.dpmclimbing.com/sites/default/files/uploads/images/upside%20down%20on%20salathe.jpg" alt="Now that's a no-hands rest with a view" />](http://vimeo.com/31878065)

However, HabitRPG does a little formatting for the user. Images are resized to fit limits, and the image is wrapped in a link to the original full-size image. Any original link that contained the image is lost.  In the first two markdown examples above, this results in a thumbnail that links to the larger image.  In the last example, however, the img tag is not evaluated and is just treated as raw text inside of the link:
![screen shot 2013-12-06 at 12 02 20 pm](https://f.cloud.github.com/assets/1245093/1695415/9174ac12-5eb1-11e3-80d5-0d1e84d46f13.png)
Funnily enough, on this last example, I kind of think HabitRPG gets it right (the user should stick to markdown and not include html tags) and Markdown gets it wrong, but, hey, go figure.

I can think of a variety of alternatives here, but here's one: perhaps clicking (or hovering?) on the thumbnail could bring up a popover of a larger (or original sized) image, and clicking on that opens a new browser tab to follow any links that wrapped the image.
##

**Comment by crookedneighbor** [comment]
Issue moved to [HabitRPG/habitica-markdown #4](https://github.com/HabitRPG/habitica-markdown/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
