### ISSUE TITLE
Shade Dragon Mount never appeared

### ISSUE THREAD

**Issue by QuestingOrc** [HabitRPG/habitica#1966]
Hey folks!

I just bought a saddle (now I have 13 of 18 gems left) to grow my shade dragon pet into a Mount, but unfortunately it did not appear; just an image with a different background as the unachieved pets with a little wider in format appeared. As I refreshed the page, no mount was seen on my avatar or in the stable. 
Worse, my shade dragon pet disappeared completely out of my stable as if I would have never hatched it before.

I logged out and logged in again, no difference.

Can anyone help?

I would really like to have my shade dragon pet back, as well as either my 5 gems or the Mount.

Kind regards
QuestingOrc

**Comment by lefnire** [comment]
Have you checked the Mounts tab? ![1](https://www.evernote.com/shard/s17/sh/d1e08321-13f3-4fd6-8c53-8226257116bb/92905a49f46e215882902a6578c0ba8e/res/681f83d8-46b6-40b1-94c1-938d4088bf85/skitch.png?resizeSmall&width=832)

**Comment by QuestingOrc** [comment]
Oh stupid derpism. Did not see the tab, forget what I said.

I'm too stupid to be worthy of this mount.
Many thanks, quickest help ever.

**Comment by lefnire** [comment]
Oh god, lol, you're not stupid! It's a new addition and we're all used to the old system :)
