### ISSUE TITLE
Pet Stat Loss

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1968]
Hey! So, I understand the logic of your pet "disappearing" when it becomes a mount - but the fact that growing a mount made my "pets found" number drop and took away my beast master achievement is pretty sad. Maybe have it so that the number does not go down, and the achievement does not disappear. As for the pet vanishing.... what if it was replaced with a greyed-out version of the sprite? So you saw that you had collected it, but that you didn't have it any more. Would that be hard to implement?

**Comment by lefnire** [comment]
Definitely need to fix #1, that was an unexpected side effect (which makes sense given the framework). Not so sure on #2, why not just paw and they re-earn (the usual workflow)?

**Comment by lemoness** [comment]
I guess it's the "unlocking" knowledge - even though I no longer have that pet (and could hatch a new one), it would signify that I had unlocked it in the past. I envision that you could hatch a new one if you wanted, but your total pet number would be unaffected.
