### ISSUE TITLE
Dailies Not Being Displayed?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#197]
![habitrpg](https://f.cloud.github.com/assets/3363224/92481/2a2d9210-65d5-11e2-952d-7752376f45a8.jpg)

Normally, I have a decently sized list of daily quests, such as "Drink a glass of water", "Draw Something", etc etc. It was displaying all Daily quests earlier today. I added the dog-walking daily today, and checked it off today. For some reason, when I checked the site, it was like this. I didn't delete the dailies I had. 
I can add new dailies fine, but I'd like to keep the ones I had as some of them were different colors and had progress, more or less.

**Comment by lefnire** [comment]
the dailies weren't added today? In other words, you've had multiple sessions / days with the dailies intact?

**Comment by ghost** [comment]
Yeah. The dailies have been up every day like normal. They were fine earlier today, too. They did a vanishing act on me a few hours ago, though. I tried logging out and logging back in, checking on my phone instead of my laptop, etc etc, to no avail.
I've been using HabitRPG for about a week with no problems whatsoever up until this. c: Thanks for the quick response!

**Comment by lefnire** [comment]
could you email me your uuid? (top right, under settings) I want to do some investigation - I can also restore your account to a previous version if you want, though it sounds like you just added them back in?

**Comment by ghost** [comment]
No, I haven't added them back in yet. I was waiting until at least tomorrow because I assumed since the Dailies reset the next day there'd be a possibility they could show up again. How much of a previous version? I'd like to stay at level 3 with my super awesome armor and such. XD

**Comment by lefnire** [comment]
one from this morning and one from about an hour ago

**Comment by ghost** [comment]
Can I get the morning one please? :D I can just add the dog walking daily again.

**Comment by wc8** [comment]
This may be irrelevant, or too late, but I have sometimes found that if the page seems bizarre (missing columns) or strangely empty on refresh a second refresh _immediately following the first, without changes_ fixes it.

**Comment by ghost** [comment]
o.O _Shrug_ Doesn't work for me, but good to know in case something comes up. Thanks!

**Comment by lefnire** [comment]
This will take me a bit, bear with me

**Comment by ghost** [comment]
Of course, thanks for working on it! :)

**Comment by lefnire** [comment]
ok, give it a shot now

**Comment by ghost** [comment]
Yay! :D All is well, thanks!

**Comment by lefnire** [comment]
well I discovered something while i was in there. @wc8 get ready for people with "old tasks have come back" - it turns out not _all_ tasks got lost in space all the time, evidently the [model refLists](http://derbyjs.com/#references) sometimes got improperly saved while the tasks themselves remained intact. basically there's your list of tasks, then there's a _separate_ list of task ids which you can sort (kinda weird, but required by Derby). So a lot of people will have recreated new tasks while the old tasks were not deleted, but "de-referenced".

**Comment by lefnire** [comment]
which accounts for some people "losing HP to todos on cron" - it could be they just had zombie (rogue) dailies

**Comment by wc8** [comment]
@lefnire I will try to help if possible but dealing with frozen pipes and flooding here.

**Comment by lefnire** [comment]
no worries, i think people saw the ticket. we should be good. wow, good luck with frozen pipes and flooding!?? :o

**Comment by wc8** [comment]
Mini flooding—only have to replace maybe 1/3 of the floor in our little house.
