### ISSUE TITLE
Translations are not working

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#1970]
I changed the language in the settings of HabitRPG but there's only a small amount of strings really translated ("new daily", "new todo", "new habit"), I still see mostly English. I tried with Italian and Spanish. I'm sure the Italian translation is complete.
Should we consider it a problem to fix or it's somewhat you already know?

**Comment by paglias** [comment]
Translations are there but they are not used.... Some strings are probably
not needed anymore and some might have to be added. @lefnire since we're
not using them I would like to move everything into habitrpg-shared so the
strings there can be translated too and mobile can use them too

**Comment by AdrienLemaire** [comment]
+1 for moving translations to habitrpg-shared

**Comment by lefnire** [comment]
I'm for it! Before we do, let me merge classes into habitrpg#develop, and we'll start using habitrpg-shared#classes as primary. Master will be on feature-freeze until classes release (hotfixes only). More soon

**Comment by AdrienLemaire** [comment]
@lefnire I recommend you create a **develop** branch in `habitrpg-shared` to respect the git flow.

**Comment by lefnire** [comment]
@Fandekasp good idea, will do

**Comment by lefnire** [comment]
Kk:
- `master` = `develop` circa 12/8@6:30p, hotfixes now to go master, both beta & production track master. 
- `develop` (both web & shared) = really dirty / broken classes stuff. Merged to consolidate effort. Any new features go here. @djuretic don't mind the failing tests - I'm going to update them once we have [passive stats](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system) implemented

@paglias @SabreCat @snicker

**Comment by SabreCat** [comment]
So classes development goes into /classes? Or /develop?

**Comment by lefnire** [comment]
develop (sorry for the flip-floppy confusion). I'm gonna remove the `classes` branches once I have Adrienne's stuff merged, but let's do everything on develop branch now.

Reasons for this move
- get devs using the new items.coffee structure (it's so overhauled, want to reduce future conflicts)
- get art contribs using spritesmith
- reduce merge-conflicts that will be created by view translations `env.t()`
- get more hands in the classes cookie jar

**Comment by paglias** [comment]
Ok, will work on this tomorrow:

Since habitrpg-shared is both client & server I'm not going to `require` translations, at the beginning I'll:
- move all the translations to habitrpg-shared
- keep using the current method to load the translations on the site, just changing the file location
- add a `setUpTranslations` method on habitrpg-shared that accepts a locale (the content of a locales/*.json file) which will be called after they have been loaded allowing us to use `t.stringName` also on habitrpg-shared.
- for mobile we'l probably have to load the file separately hoping that it doesn't hurt performances

Is that ok? Better solutions are welcomed

**Comment by lefnire** [comment]
@paglias if you haven't started, don't jump into translations yet. I'm doing a big overhaul of habitrpg-shared to support https://github.com/HabitRPG/habitrpg/issues/1977. Will ping you when I'm done (FYI @Fandekasp @snicker @SabreCat)

**Comment by snicker** [comment]
Good stuff. I always thought that was a bit of a bad smell ;)

**Comment by paglias** [comment]
@lefnire was planning to do it on the weekend, if you need any help on api v2 methods let me know

**Comment by lefnire** [comment]
I'll ping you ~tomorrow, will likely need your help testing / debugging. It's gonna be a pretty cool unified approach, more soon
