### ISSUE TITLE
Hatch using potion and egg but no new pet was found

### ISSUE THREAD

**Issue by sabrinastarfire** [HabitRPG/habitica#1972]
it used up the potion and the egg but there was no new pet at the stable.

**Comment by deilann** [comment]
Hey, sorry this is so late, but is there any way you could give us more info? Has this happened again? I'm closing this ticket for now, but please reopen it when you respond.

**Comment by sabrinastarfire** [comment]
Just that. i used a potion and hatched an egg. it said, do u want to hatch this egg? i clicked yes. couldnt find the pet anywhere. Sry, it was a while ago.
Thank you so much. i thought no one saw it :)

On Tuesday, February 11, 2014 5:02 PM, deilann notifications@github.com wrote:

Hey, sorry this is so late, but is there any way you could give us more info? Has this happened again? I'm closing this ticket for now, but please reopen it when you respond.

**Comment by NessyNoinex** [comment]
This has just happened to me, I don't see my pink cotton cactus.

**Comment by Alys** [comment]
Usually when you hatch a pet and the pet doesn't appear straight away, all that's required is that you reload the Pets page (occasionally clearing your browser's cache might also be needed and/or logging out and logging back in). The other reason this can happen is if a sync error occurs, in which case the egg and potion usually reappear in your inventory after a short delay (details at [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) - see section 4.4).

@sabrinastarfire and @NessyNoinex , I realised you logged these problems a long time ago (I'm sorry about the delay!). Do you still have any problems with hatching pets?

**Comment by Alys** [comment]
Closing this issue because it's very old now but it can be reopened if you still need help - just comment here.
