### ISSUE TITLE
Pixel art decisions

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1973]
(posting here because more of the users ref'd are here. not a bug, I'll close after)

We find ourselves in an interesting situation! With our recent surge of pixelists, all the gatekeepers (and the community) have largely varying opinions on the contributions (they are, after all, visual - tis inevitable). 

@Pandoro & I like @fuzzytrees' grey chucks & @crystalphoenix's hook; while @DanielTheBard & @SabreCat prefer the samurai sword & no chucks. I'm in love with @Fandekasp's rock monster, @lemoness isn't a fan. On the other hand, I tore into poor @Fandekasp on his shirts - @lemoness IS a fan (with some tweaks).

Ok, so it's clear that much of it comes down to preference. I think the best workflow for now then is: Pixelists call the shots (@Pandoro & @lemoness). This **is** the current workflow, I just want to call it out again as a reminder. We should also weigh _proven_ artists' opinions more heavily: @fuzzytrees, @aiseant, @baconsaur, etc. This means we can safely treat my, et al, opinions with a grain of salt. 

Not really an issue yet, but I could possibly see it becoming one if contributors hear lotsa conflicting constructive feedback but no canonical voice - could feel like they're getting the gauntlet, and we don't want that (@crystalphoenix's, @RosemonkeyCT, @coyotino, @Fandekasp - hang in there friends, we love your work!). If anyone thinks there might be a better way to handle this, start mulling. I mused about polls, but that might be simply too many, and too... cold? Is that the word I'm looking for?

**Comment by crystalphoenix** [comment]
that sounds good to me :)

hopefully as time passes and the Guidance for Pixelest wiki page gets more detailed, there would be enough there as a style/art guide to keep most submissions somewhat consistent.

when i think of user submitted art, there are two places that come to mind. both have an art guide established, and the head/official artist(s) gives the final word on whether it's accepted. the pieces are sometimes tweaked as things bounce back and forth between the the two parties, but i think it's an important step in making sure that the art doesn't stray too wildly in style.  luckily pixel art is used here, so there's only so much straying that can be done within the 3x3 px units and canvas size constraints.

**Comment by AdrienLemaire** [comment]
I'm fine with @lemoness dictating what is good or not. Votes could be done by a limited group of persons, but they must be professional designers, we don't want ignorants to vote in something they don't really understand (for example me !)

**Comment by SabreCat** [comment]
For the record, I love the hook swords and think the nunchucks should be available ASAP as a Costume item. But I will happily write up the content and mechanics for whatever the final decision is!

**Comment by lemoness** [comment]
Sounds good, guys! Alex had some ideas for streamlining this  process, too,
and I think that it's something sorely needed. Maybe we should make a
Trello card for ideas. Alex?

**Comment by Pandoro** [comment]
Sorry it took so long. Here is the [trello card](https://trello.com/c/8okdnZJy/350-pixel-art-rating-system). I wrote down what was discussed elsewhere. Feel free to make additions and suggestions!
