### ISSUE TITLE
No Obvious Way to Rest in Inn, and FAQ is incorrect

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#1974]
According to the FAQ:

"Resting in the Inn freezes your entire account, so that you can enjoy your sunshine or chicken soup in peace. There's a minimum stay of 24 hours, but after that you can check out any time you like! The Inn is located in the Tavern. To access it, click on your picture, and then click on on the "Tavern" tab. There's a green button to the left that says "Rest in the Inn." Click it, and you're home free!"

Actually, there's no green button to be found, once I got to the inn via the new 2 stage process, and I'm failing to find any other way to rest in the Inn. It looks like the latest visual upgrade disappeared this feature.

**Comment by lefnire** [comment]
You're not seeing this?

![1](https://www.evernote.com/shard/s17/sh/a8c393d6-ff0a-4fed-9017-86e5ce543986/d4dfebbec1d9f5f1decfa8fcdda8eb55/res/5f16bc78-4185-40cf-85f6-b8106cad55f1/skitch.png?resizeSmall&width=832)

**Comment by ArlieS** [comment]
firefox 25.0.1 on Ubuntu 12.10 with fluxbox.

Can't see the (presumed) picture in your comment above - I'm getting an access denied from evernote. 

I believe - but can't check right now - that I see the same thing with firefox ?? + ubuntu 12.04 + unity

**Comment by ArlieS** [comment]
Hopefully the following is a picture of my screen.

![screenshot from 2013-12-09 17 05 28](https://f.cloud.github.com/assets/4530463/1710668/35d3c0f4-6137-11e3-904c-d1e072977581.png)

**Comment by lefnire** [comment]
Ah, the button is covered because of screen zoom. Either zoom out or resize
the screen even smaller, that page size is the in-between blind spot. It's
a bug somewhere else in the queue (on phone, will find later)

**Comment by ArlieS** [comment]
Aha! Thanks. Shrinking it did the trick.

**Comment by bobbyroberts99** [comment]
I added language to the wiki about this--[here](http://habitrpg.wikia.com/wiki/FAQ#I'm_going_on_vacation,_how_can_I_disable_my_Dailies?) and [here](http://habitrpg.wikia.com/wiki/Tavern#Resting_at_The_Inn)

**Comment by wc8** [comment]
I think this is #1350.
