### ISSUE TITLE
Town Crier showing up late

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#1975]
I've had this a few times already - some new feature gets introduced, and the town crier shows up late (a day or several days after the feature is available).
Same happened today - I found the food option available (yay!) but noone to tell me about it. 

Extra bug: I do not see the food pictures - just the little blue number telling me how many I had or the gemstones below the market food telling the cost. Mouse-over functions, though, and feeding the food also worked.

**Comment by lefnire** [comment]
Have you done a hard refresh since mounts release?

**Comment by wildcate** [comment]
I did a reload with cache bypass, still no town crier. Might be a firefox bug though, it sometimes seems to use the cache even if explicitly told not to.
Food pics have turned up, meanwhile.

**Comment by deilann** [comment]
If this is still a problem, feel free to re-open!
