### ISSUE TITLE
Schema Upgrades v Old Clients (APIv2)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1977]
(Devs can ignore, this is a note-to-self ticket)

A four-part ticket around the issue Schema upgrades can cause problems with older-version clients (older mobile app, user hasn't refreshed browser, 3rd-party apps, etc). All parts need completion before releasing classes.

The issue is that much of our client code is depending on the (wide-open) `PUT /user` paths (via `User.user.set()` to run calculations client side, then manually set variables on the user. This is terrible API design - instead, they should be sending up REST POSTs for particular operations (hatch-pet, equip-gear, etc) and we should lock down as many PUT user paths as possible. Once that's done, we can make updates to the API without fearing if out-dated browsing sessions can corrupt data. This bit us in the ass with mounts, and we'll need to fix it before launching classes
## [√] Force Refresh

See https://trello.com/c/zo3URB1c/334-forced-refresh

Completed by @paglias: c30934bc96af42f900e5a887364d804738940ec8 , 9b459e37f368dd64e7c0e33b8417b7a2a2b83c88
## [99%] Move Everything to API (APIv2)

Move as much as we possibly can from the client to the server. Instead of running algorithms directly in our Controller code and running `User.set()` at the end of the calculations, we should:
- move _all_ algos / helpers to habitrpg-shared
- pass user through those habitrpg-shared functions, so that the client is updated immediately (performance)
- build out our API to support _all_ ops without requiring `User.set()`. Eg, add `POST /user/equip`, `POST /user/choose-pet`, etc
- Send up the op after running it client-side

This will allow us to avoid having to force a new client release (mobile release, browser refresh) when we make substantial changes to the API, which previously can cause data-corruption since `User.set()` can clobber proper schema
### Still to port:
- [ ] `user.invitations` (group accept/reject)
## [√] Harden `PUT /user`

Make sure only leaf paths can be set via `POST /user` (see 4323443)
## ~~[ ] Ensure Schema Structure~~
- If validation error, send "refresh or upgrade"
- use `pre('save')` ? 

See [StackOverflow](http://stackoverflow.com/questions/20497750/how-to-ensure-mongoose-schema-structure) & [Google Groups](https://groups.google.com/forum/#!topic/mongoose-orm/jz2ImEPdfVg). Turns out this can't (cleanly/easily) be done, and we should depend on a hardened API (above) instead. See conversation [here](https://groups.google.com/d/msg/mongoose-orm/jz2ImEPdfVg/Zo4Q7DJNP9cJ), and (deleted) response [here](https://gist.github.com/lefnire/9d583c6a1018c9819eb3)
##

**Comment by lefnire** [comment]
@paglias @Fandekasp @snicker @SabreCat 

Here's [some documentation](https://github.com/HabitRPG/habitrpg-shared/commit/aac5cc6d395700bf58160f6db0911563557f825b) on the new system, it really can use a lot of work (outlined in the comments) - but it's a pretty decent functional WIP.

https://github.com/HabitRPG/habitrpg/commit/d4e0ae85a0b4e3c56d40c68fecc0a59bb552de49 and https://github.com/HabitRPG/habitrpg-shared/commit/ab5bd6d5af9b7a9be695c7ebbfddd755da074949 show this system in action. Those commits port the `feed` operation to `user.ops`, and now the code is called both on the server and the client, and all that `User.set()` code (dangerous for upgrades) is removed. You'll notice, I don't have to define `api.feed` on the server (if no special server-handling is required), `api.feed` is added and called automatically (just copying in `user.ops.feed`), and `user.save()` is run at the end. Pretty slick, eh? Weird, but slick.

So some notes, `User.set` (convenience for `user.ops.update`) will probably still be necessary for `.preferences`, `.flags`, and some other simple paths. Also, `user.ops` is only for operations that need to be called on both server & client. I'll keep updating that big comment block as I go along, and let me know if y'all think there are better ways to handling all this

**Comment by lefnire** [comment]
Simpler sample https://github.com/HabitRPG/habitrpg-shared/commit/a5bf3440c807806fca196dcef600ed825d3e1bb4 & https://github.com/HabitRPG/habitrpg/commit/dc63eff41d847f3d421c47f79e04f57e74da24b3

**Comment by lefnire** [comment]
Last things that need porting to APIv2 is invitations-stuff (reject, accept). Lo-prio for now

**Comment by snicker** [comment]
I guess you've already committed to the breaking change approach, but is there an option for leaving a v1 API endpoint open for backward compatibility? Apologies if I'm not up to speed enough on what's been changed and if that's not feasible. Just noticed that the CLI tool isn't playing nicely anymore

**Comment by lefnire** [comment]
v1 should still support very basic operations: addTask, updateTask, deleteTask, score. See [supported v1 ops here](https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv1.js#L149tL162). Unfortunately, the **big** one we had to remove was `PUT /user`. The reason is apps based on the apiv1 were expecting a certain UserSchema, which is lo longer supported. If you read the "Ensure Schema Structure" section in this card's description, you'll see there's no easy way to harden against those incoming updates save just nixing the route. Unfortunate. 

In the mean time, [here's APIv2](https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv2.js#L33tL131). It should be readable-enough for 3rd-party-ists to get started, but I'll add real documentation this week. Incidentally, which routes are giving you beef?

**Comment by snicker** [comment]
Not so much routes, but the data structure returned from `up` and
`down` seems to have changed. I am using some hacky absolute array
index reference in that AutoIT app, so that's smelly anyway. I haven't
fully looked into it, I'll check later

**Comment by lefnire** [comment]
Kk. If you prefer a quickfix, let me know what you're receiving and what you expect instead, I'll see what I can do with v1

**Comment by snicker** [comment]
Sure, it's no big deal, I could probably whip it in myself ;)
