### ISSUE TITLE
2nd time: Paid for the package (20 Gems, no ads, donation) and recieved nothing… :(

### ISSUE THREAD

**Issue by guryushika** [HabitRPG/habitica#1978]
Hi, I'm guryushika (it's my nickname on habitrpg) after discovering HabitRPG I went straight to the donation page because I love it so much it's everything I wanted, also it's affordable and nice to support neat ideas.
I gave my 5$ but unfortunatly recieved nothing in return…no Gems, still have the ads.
The paypal transaction is 8J627525V86731334
Please fix it, thanks

**Comment by lefnire** [comment]
shoot, what's your uuid?

**Comment by guryushika** [comment]
here is my uuid 6216a267-4391-4c71-926e-c4b512a019f4

**Comment by lefnire** [comment]
I set the necessary bits for your user in the database, double-check those
went through. Will investigate what could have gone wrong soon as I can.
Sorry for the issues!

**Comment by guryushika** [comment]
24 Gems, no ads and the 5$ on your paypal, we are all set :+1: 
Thank you very much, keep up the good work, your product is just awesome!!!!!!!!!!

**Comment by guryushika** [comment]
Hello again there,
Well I paid again to get more Gems (yes I'm addicted and it's nice my addiction is useful héhé :smile_cat: )
Anyway the Gems didn't add up to my Gems counter :(
The paypal transaction is 0F813779HW177735F and my uuid is still 6216a267-4391-4c71-926e-c4b512a019f4
Hope you can fix it and understand what's wrong.

**Comment by SabreCat** [comment]
Thanks for your patience with this @guryushika!

**Comment by lefnire** [comment]
@guryushika updated you in the database, extra gems for the wait and trouble. sorry friend :(

Paypal is giving us mixed results for internationals. @SabreCat, think I should disable it until we figure out what's going on? It's pretty rare, but when it happens it's pretty important. Downside is paypal is 90% of our payment throughput, and I wouldn't even know where to start diagnosing the issue since it's off our servers

**Comment by SabreCat** [comment]
Argh, that is a hell of a call to make. I hate to ask, but do we have any line of support from the PayPal side?

**Comment by lefnire** [comment]
Naw don't worry on judgement call, more a "thoughts?". I'll see about sending them a support ticket. Will try to sift through their support base too.

**Comment by guryushika** [comment]
Thank you for the gift guys :+1: , and best of luck to get through with the Mammut named paypal…

**Comment by guryushika** [comment]
Ok well, I had 81 Gems, you gave me 80 Gems and I had 1 Gem remaining. I spent no Gem yet because of so many options I was thinking where to put it…but then I wanted to buy something but my Gems are almost all gone…I'm back to 1 Gem…this is indeed a weird bug!

**Comment by lefnire** [comment]
give that a shot. Looks like #2105 hit ya
