### ISSUE TITLE
Missing tasks came back

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#198]
Many of you will notice missing tasks return. Turns out not _all_ tasks got lost during many of these server rough-patches, evidently the [model refLists](http://derbyjs.com/#references) sometimes got improperly saved while the tasks themselves remained intact. Basically there's your task-lists, then there's a _separate_ list of task _ids_ which is used for filtering/sorting (kinda weird, but it's how Derby does it). It's the id-lists that was having issues, so I've applied a fix 54df0c16ffb898a30e090547ef601b1cf4bb6f7a to check for "zombie" tasks and put this back into their id lists. 

Blessing for new comers, a lot less data-loss as a result - curse for the long time users. there will be some trash-can clicking.

**Comment by switz** [comment]
Nice, this is cool - I'll have to checkout the code.  

Always wondered if derby was missing a few ids in my refLists.

**Comment by lefnire** [comment]
you're not gonna like it: [code](https://github.com/lefnire/habitrpg/blob/54df0c16ffb898a30e090547ef601b1cf4bb6f7a/src/app/index.coffee#L59-77) - I'm not embarrassed of the code, because WTF is derby doing man?? unless i find out later it was me all along..
