### ISSUE TITLE
Feeding the displayed pet makes it disappear

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#1980]
Experienced on beta. The pet can be chosen again, though.

**Comment by lefnire** [comment]
Can't replicate. You sure you didn't feed the pet past the tipping point? Aka, is your pet now a mount? (check the mounts tab)

**Comment by Eusebius** [comment]
No, I have no mount. I'll try to replicate next time I drop some food.

**Comment by Eusebius** [comment]
Could not reproduce. Sorry.
