### ISSUE TITLE
Dragging tasks makes their direct surrounding transparent rectangle size increase (Firefox CSS)

### ISSUE THREAD

**Issue by Anodescu** [HabitRPG/habitica#1983]
On the beta, you can easily see it by holding left click on a task and performing small circles such that no other task moves to make room for the dragged task. The surrounding transparent rectangle of the dragged task will keep increasing in size as the task is dragged and until left click is released. I did not spot any error in the JavaScript console.

Using Firefox 26.0
User ID : 9094b1ee-be36-4ba9-ac5b-3279a28280e9
##

**Comment by Alys** [comment]
Still happens:
![screen shot 2014-09-19 at 4 57 15 pm](https://cloud.githubusercontent.com/assets/1495809/4331805/7c4080be-3fca-11e4-8960-b34dd7aa7b7a.png)

**Comment by negue** [comment]
Only on firefox?

**Comment by Alys** [comment]
Not on Chrome nor Safari. Don't know, don't care about IE. ;)

negue, I'm wondering if it's similar to the problem you fixed two or three weeks ago, where in the header, when you hovered over the level, there'd be a too-large outline around the on-hover tooltip. It looks sort of like that.

**Comment by negue** [comment]
Could be that problem yes, but I tend to think this is because of the "drag&drop" (reorder) code which sets a "bad" css and expands this border more & more

**Comment by negue** [comment]
Hm, I tried it myself and the border only expands about 10px each side, If I hover over the "check"box while dragging the task, and then goes back to normal, but I don't get the fullwidth like in the screenshot.

FF 32.0.2 , Win8.1

**Comment by lemoness** [comment]
I am no longer having this issue. If anyone else is, feel free to comment and I'll reopen!
