### ISSUE TITLE
Rare pet FAQ outdated

### ISSUE THREAD

**Issue by GeorgeGabechava** [HabitRPG/habitica#1985]
The FAQ for:

"What is the rare pet/Veteran Wolf?" [http://community.habitrpg.com/content/what-rare-petveteran-wolf , http://community.habitrpg.com/faq-page#n499 ]

Is outdated because there has been new rare pets (atleast one that I know of: turkey). It currently says:

"Currently, there is only one rare pet - the Veteran Wolf. This pet was awarded in Fall 2013 to the users who had survived the old, bug-filled version of HabitRPG before the site's switch to the new, smooth-running Angular framework.

There will likely be other rare pets in the future!"

Can update to something like:

"Rare pets are awarded on special occasions or through ways that a regular pet cannot be obtained by. An example of a rare pet is the Veteran Wolf. This pet was awarded in Fall 2013 to the users who had survived the old, bug-filled version of HabitRPG before the site's switch to the new, smooth-running Angular framework."

I plan to be able to help the project in terms of coding later on this month to join in on the true githubing :P.

**Comment by lefnire** [comment]
I'm gonna delete the wiki from community.habit, it's been fully ported to habitrpg.wikia.com (@bobbyroberts99 is that correct?). The updated pets section can be [found here](http://habitrpg.wikia.com/wiki/Pets)

**Comment by bobbyroberts99** [comment]
If you mean [this site](http://community.habitrpg.com/section/tutorialswiki) then yes it has been ported. The [community page FAQ](http://community.habitrpg.com/faq-page) has mostly been ported. I'm double checking and will let you know when it's done.

**Comment by bobbyroberts99** [comment]
OK, the [wiki FAQ](http://habitrpg.wikia.com/wiki/FAQ) now more or less matches the [community pages FAQ](http://community.habitrpg.com/faq-page). @GeorgeGabechava, I incorporated your suggestion [here](http://habitrpg.wikia.com/wiki/FAQ#What_are_rare_pets.3F)

@lefnire, delete away.

**Comment by GeorgeGabechava** [comment]
Glad I could help! Even though the issue was trivial, it was my first post on GitHub and I'm happy to see my actions making a difference the project. As I said earlier I plan to take up coding later this month to help that way. 

Happy habiteering :)

**Comment by bobbyroberts99** [comment]
@lefnire, commit 182a34e changes footer link to wiki faq and is in my pull request on develop.

**Comment by lefnire** [comment]
√
