### ISSUE TITLE
Screen locks on two simultaneous popups

### ISSUE THREAD

**Issue by woodgirl90** [HabitRPG/habitica#1987]
When a 21 day streak coincides with a iten drop it greys the screen and only one of the popups shows. After dismissing one of the popups the screen stays greyed but doesn't show the other popup. While screen is greyed the normal screen is unable to be interacted with.
![habitrpg glitch](https://f.cloud.github.com/assets/6186810/1749191/069cd20a-64ff-11e3-8472-67b502f00670.jpg)

**Comment by negue** [comment]
Is this currenty still working like that? If not I think this can be closed

**Comment by lemoness** [comment]
I don't think so, so I'm closing this. If anyone still has this problem, we can reopen it.
