### ISSUE TITLE
Classes Beta Site - Error 503

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#1989]
Trying to log into the Classes Beta site http://habitrpg-classes.herokuapp.com/ gives me a 503 error and it will not allow me to proceed.  

Browser: Safari Version 5.0.6

**Comment by lefnire** [comment]
Having trouble connecting to the database, I wonder if it's because there
are no indices (shouldn't be a problem though with no data). Gonna do a
full migration & try again in an hour or two

**Comment by lefnire** [comment]
I cloned the old database in, but the migration script is taking a very long time. Could take an hour or two. In the mean time, create a new account to test. I'll ping back here when existing accounts have been migrated

**Comment by wc8** [comment]
still get error when trying to register new account. Does it need to be a new email address for new account?

**Comment by JennaMalkin** [comment]
Yes, it will say 'that email address is already taken' (or words to that effect) if you try to re-register with the email you used for the main site.

**Comment by wc8** [comment]
I'm just getting 503 error, maybe I need to restart browser

**Comment by lefnire** [comment]
yeah, something's funky. I think it's the cheap Azure mongo db I've cloned into. the backend shouldn't be much more impacted, and everything runs smoothly on local. I'll take another stab tomorrow

**Comment by JennaMalkin** [comment]
The 503 error seems to be resolved. :)

**Comment by lefnire** [comment]
Shoot, some people are still getting it. Let's try this;

``` diff
-mongoose.connect(nconf.get('NODE_DB_URI'), function(err) {
+mongoose.connect(nconf.get('NODE_DB_URI'), {auto_reconnect:true}, function(err) {
```

503 means the service is unavailable. Unfortunately it's not gonna tell us the real error, or which service (very likely Mongo) - it's a a _previous error_ that knocked the service offline, and _that_ one's important. But for some reason it's staying offline for other users (which it doesn't do if encountering an error on production). Let's experiment with `auto_reconnect` flag

**Comment by lefnire** [comment]
bumping to crit, this is still going on periodically. The most important bug to kick for launch

**Comment by lefnire** [comment]
Ok, we're on a new Heroku instance, and a new Mongo instance. If this happens again, it means it's my code. Keep an eye out folks (@wc8 @breadstrings @JennaMalkin)

**Comment by lefnire** [comment]
you know this was our heroku instance after all? It's running smoothly on prod!
