### ISSUE TITLE
Classes forces me to repurchase Crystal Blade

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1992]
All the other contrib gear was in my inventory except the blade

**Comment by lefnire** [comment]
fixed above, re-open if it happens again the next time I do a migration (should be today sometime. I'll try to remember to buy a crystal sword myself before doing it)

**Comment by lefnire** [comment]
(verified on local, √)

**Comment by bobbyroberts99** [comment]
Version 2 of classes had my crystal blade in inventory.
