### ISSUE TITLE
Rewards that cost more than 100 gold (3 digits) don't display on one line

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1993]
![name002](https://f.cloud.github.com/assets/4084120/1757497/bbe014ce-6680-11e3-971f-ff5c8d27a951.png)

**Comment by breadstrings** [comment]
I'll add to this, and say there's also a bit of offsetting with the coin images.

![screen shot 2013-12-17 at 9 36 17 am](https://f.cloud.github.com/assets/5908271/1760228/31bc2b54-66ab-11e3-8158-601fcfe3fba9.png)

**Comment by SabreCat** [comment]
The return of #1269!

**Comment by breadstrings** [comment]
Difference being that Bobby's one is affected by the actual in-game reward rather than a custom one. ;)

**Comment by quin-jay** [comment]
Could we globally widen the cost box width for all rewards? This seems like a problem that's just going to keep happening for items greater than 4 or 5 digits, but I think given that some in-game rewards are 3 digits it should at least be fixed for those.

As an aside, I'm using Chrome 32.0.1700.107 for OSX Mavericks, and I can reproduce this effect for every zoom level above 80% (which is, personally, too small to keep as my default view).

**Comment by SabreCat** [comment]
If the cost box grew to fit rather than being a fixed size, we'd be set. Assuming the rest of the stuff would drop to another line if you put in 100,000,000,000, or max cost were set to e.g. 9999.

**Comment by quin-jay** [comment]
@SabreCat, to clarify -- do you mean the cost box for _just_ the higher-priced rewards? Or would all of the boxes grow to match as well? I think it would look odd if just one box was wider. Wouldn't be the end of the world, but it's not exactly solving the "one of these costs is not like the other" problem either.

**Comment by SabreCat** [comment]
@lynnyliz: I think I'd only want the too-big boxes to stretch; no need to cramp the titles of your more modestly costed rewards. Even with the inconsistency, it'd be a far sight better than having the coin icon fly around to odd places.

**Comment by quin-jay** [comment]
Good point. Right now it just looks all sorts of gross, so a single wider box would be much better by comparison.
