### ISSUE TITLE
Various classes issues

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#1994]
Not sure if this is due to the different server, but there's a definite lag (of 7hrs and counting) in the chat which doesn't update on refresh.

**Comment by breadstrings** [comment]
Didn't want to clog the issue feed with my other concerns, which I'm not sure were actual bugs or issues, so I'll list them here:
- ~~Ticking items off in habit-classes doesn't tick them off in main habit site~~
- ~~It is unclear whether actions taken in the habit-classes is supposed to transfer over to main habit site~~
- ~~Purchasing items with gold in habit-classes _does_ remove gold from the main habit site~~
- [x] No option to unlock sets of hair (as in clothes and skin colours)
- [x] Mana is above maximum on entry into class system (I got 26/10 mana)
- [x] Joining and then leaving a challenge (in addition to removing tasks) produces a 503 error.  (however it does allow you to leave challenge and keep the tasks)
- ~~adding/removing tasks in habit-classes does not sync across to main habit site~~

**Comment by lefnire** [comment]
nothing is synced between the classes server and the main server. It's a database snapshot, and will be wiped periodically. I preened your list down

@lemoness how do we want to handle "unlock set". Should we do one unlock for all hair+beards+mustaches? One unlock for all hair, one for beards+mustaches?

**Comment by LittleRabbitBeta** [comment]
Hair will not change color on avatar w/ "no" bangs (upon initial entry); I didn't get any further.

**Comment by lefnire** [comment]
@LittleRabbitBeta as in "my hair won't change color when I'm bald"? ...

**Comment by lemoness** [comment]
Facial hair unlock and hairstyle unlock should be separate, I think. For
example, I wouldn't want a beard, but I would want pigtails, and
vice-versa. 2 gems each and 5 gems set, like the Halloween skins?

**Comment by lefnire** [comment]
Deal

**Comment by breadstrings** [comment]
- [x] As wc8 mentioned in tavern, can't add tasks when creating challenges.
- [ ] ~~If you create a challenge, and no one joins, and then you delete it without closing the challenge, the challenge remains without any leader to choose the winner. The challenge should automatically close or cancel once the creator leaves challenge, or have a pop-up preventing creator from leaving challenge until they reassign who their next in charge is, or close the challenge.~~ 
  - **Moved to https://github.com/HabitRPG/habitrpg/issues/1998 , unrelated to classes**
- [ ] Inviting someone to a private guild doesn't have "pending" or some indication that they have been invited but are awaiting acceptance (not sure if this is a feature or not, but I think it'd be good to have)
  - **Is this new to the heroku-classes? Or is this an issue with main site too? If so, let's create a new ticket for it**
- [x] tiger cub images don't load (occurred after I hatched a skeleton lion and went to the stable. I refreshed twice and they still didn't load)
- [x] Dismissing or saying "cool" to Bailey doesn't remove her from the header bar. (she's kind of stuck there despite refreshing)
- [ ] ~~Justin's image doesn't show up in the tour (empty space is present only)~~
  - **Can't replicate. Try a hard-refresh**
- [ ] There's a constant 504 error when using the site for a duration of time forcing me to refresh the page (occurs after various actions, none of which are similar)
  - **Do you mean 503? If so, that's my most vexing bug right now**: #1989
  - I'm almost certain it was a 504 error. Wish I had a screenshot of it. It happened three times, but I haven't received it since the classes went live.  ~ Breads
- [ ] ~~Casting "pick pocket" skill on a daily automatically gives you gold before it is ticked off. Ticking off the enchanted task gives you the normal amount of gold you'd get without enchantment.~~ 
  - **This is by design. Chime in on [Trello](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system) (ping @DanielTheBard or SabreCat) if you think this should be otherwise**
- [ ] ~~After closing death notice, the habit/rewards area went blank, party members disappeared. Refresh restored these but removed the debug area (this might have been a coincidence with a feature update or something).~~
  - **Can't replicate**
- [x] Purchasing new t-shirts for sprite after gaining ultimate gear achievement, makes all class-gear disappear from inventory and sprite.
  - **I believe I've fixed this, try again in 10m if you could**
- [ ] Costume items are not grouped by type as they are in the armoury. 
- [ ] Manually editing mana to full makes things go weird. See following images:

Before refresh:

![screen shot 2013-12-17 at 9 43 29 am](https://f.cloud.github.com/assets/5908271/1760291/5a3a89b2-66ac-11e3-8015-8adfdf30f065.png)

After refresh:

![screen shot 2013-12-17 at 9 44 10 am](https://f.cloud.github.com/assets/5908271/1760292/5fd03980-66ac-11e3-8a48-84b136c851b2.png)
- [ ] Using costume under mage class and wearing with a different staff from the one equipped. Refreshing replaces the staff with a rogue's base weapon? (rogue was the first class I chose but I didn't buy any weapons from that class before changing class to mage)

### Tour placement issues

> These issues are caused by using [bootstrap affix](http://getbootstrap.com/2.3.2/javascript.html#affix), instead of Zakkain's old header positioning code. Need to move back to original. - Tyler
- [x] In the tour, when you reach the rewards part, two "rewards" speech boxes appear like so:
  ![image](https://f.cloud.github.com/assets/5908271/1759167/9a9d9a10-669a-11e3-8ba8-f5cb6980edc7.png)
- [x] In the tour, "hovering over comments" speech bubble is nowhere near a task like on the main site. Instead, the arrow points to the "Habit" title. Scrolling down the page, makes the bubble disappear _over_ the header so it looks like it's floating off the page and out of sight (perhaps make it scroll under the header?)

**Comment by lefnire** [comment]
@breadstrings updated your listing with some of my own comments (hope you don't mind, kinda intrusive of me but helps with organization)

**Comment by breadstrings** [comment]
I'm also updating the list with extra issues I find so you can see them all in one place. Do you want me to check mark them or leave them as bullet points?

**Comment by breadstrings** [comment]
I'm unable to test the purchase of shirts since I've already bought them. Might have to wait until the system resets.

**Comment by lefnire** [comment]
What's your uuid, i'll unset purchased

**Comment by breadstrings** [comment]
3b675c0e-d7a6-440c-8687-bc67cd0bf4e9

**Comment by breadstrings** [comment]
Yup, no problems after purchasing shirts. :)

**Comment by LittleRabbitBeta** [comment]
@lefnire LOL, feeling silly. So bald isn't the wrap around 1" band of hair eh :-)

**Comment by breadstrings** [comment]
Unsure whether this is a bug:
My item store shows crystal gear even though I haven't achieved the top tier armour yet. Is that meant to happen?

**Comment by lefnire** [comment]
Yep, "special" gear is no longer tiered. You can buy it at any point, as long as you've earned the ability to buy it

**Comment by Senth** [comment]
I also get a bug when resetting the MP counter. I tried to reset to 55MP but I got full instead. When I checked the MP-field value inside "fix character values" again there was no value there at all, just plain empty.

Now I can use inifinet amount of MP and whenever I use a spell I gain maximum MP.

The first time I cast chilling frost I lost around 66% of my experience for the current level.

**Comment by nafoster** [comment]
Might as well put my class issue in here.

Looking through my party member's stats & equipment shows my stuff though she's a Rogue and I'm a Wizard.

**Comment by lefnire** [comment]
Ah yes, party stats aren't working at all presently. On my high-prio todo list

**Comment by breadstrings** [comment]
I'm still getting a 504 error. The latest occurred when I was attempting to post a message in one of the guilds.

**Comment by deilann** [comment]
Pretty sure this is all fixed.
