### ISSUE TITLE
XP and MP amounts earned are greater than level amount in classes

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1996]
![name001](https://f.cloud.github.com/assets/4084120/1757425/e3aede14-667f-11e3-9e98-056a7202bfd6.png)

**Comment by lefnire** [comment]
MP fixed in https://github.com/HabitRPG/habitrpg/commit/5f689960b614dd5a9063c5e9a6af678495cbe687 (pushing now). Re: Exp - is that how it started for you character? Or is he not leveling as you + things?

**Comment by bobbyroberts99** [comment]
That's how it started. Seems to be working fine now.

**Comment by wc8** [comment]
Closing because I think this is fixed.

**Comment by marcelosizer** [comment]
I got the issue when using Burst of Flames on a daily but when I checked another daily I leveled up with the correct amount of EXP.

![habit error3](https://f.cloud.github.com/assets/6205335/1768524/d98d9238-6763-11e3-9419-3a6e7e338b44.png)
