### ISSUE TITLE
Error 500 cannot call method cast… when applying Burst of Flames

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1997]
Long error on trying to apply Burst of Flames to a to-do (as Wizard).

**Comment by wc8** [comment]
P.S. P.S. task checks off, not sure if any special abilities are applied. I’m losing mana, but I can’t stop the game from trying to apply Burst of Flames…so I’m around -120 mana deficiency. Note, if I click on Burst of Flames again, I’m informed “not enough mana” but I keep losing it if I click tasks.

**Comment by wc8** [comment]
Update: this is resolved now.

**Comment by lefnire** [comment]
I'm pushing a big spells update, check back in 5m for improvements (re-balancing, bug fixes, etc). Also pushing a Justin tour after you select your class
