### ISSUE TITLE
sole challenge or party participant can leave an orphan challenge or party

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1998]
@breadstrings says: 

> If you create a challenge, and no one joins, and then you delete it without closing the challenge, the challenge remains without any leader to choose the winner. The challenge should automatically close or cancel once the creator leaves challenge, or have a pop-up preventing creator from leaving challenge until they reassign who their next in charge is, or close the challenge

**Comment by paglias** [comment]
This is also true for groups, when the only member leaves it, it should be deleted

**Comment by breadstrings** [comment]
Empty challenges have an additional usage of being templates now. If this get's fixed, we'd need to implement a template function to replace this use of empty challenges as there is a whole guild dedicated to using challenges as templates for those just starting out or wanting to revamp some tasks.

**Comment by Alys** [comment]
I'm closing this since allowing empty challenges to remain is easier than implementing a template function. 

Deleting empty parties is discussed in https://github.com/HabitRPG/habitrpg/issues/5136#issuecomment-98561702
