### ISSUE TITLE
Unique URL isn't working

### ISSUE THREAD

**Issue by hsribei** [HabitRPG/habitica#2]
The field comes out empty:
https://skitch.com/obvio171/exups/habitrpg

I'm on Chrome 21.0.1180.82 + Mac OS X Lion.

**Comment by lefnire** [comment]
nooo! my exact browser + OS no less. [Usually works](http://www.evernote.com/shard/s17/sh/ad8ff50e-b62a-42e5-8f4a-1358d21e1aea/5bad2efbe748cf6854f53262546f1003), for some reason that particular field has been giving me so much beef (as the [comment surrounding it indicates](https://github.com/lefnire/habitrpg/blob/master/src/app/index.coffee#L66)). Diagnosing.

**Comment by lefnire** [comment]
@obvio171, hit me up if you see anything obvious

**Comment by hsribei** [comment]
No worries. Congrats on a great project! If you need help testing anything just let me know :)

**Comment by lefnire** [comment]
Can't replicate on local (which is expected, I was getting that issue intermittently for alternating browsers before I finally "fixed" it). I think I'll setup a Sauce Labs account + Phantom or Casper testing for this. Stay tuned.

**Comment by lefnire** [comment]
Well, never could fix it - but hell, I implemented Auth anyway - give it another shot & register with FB

**Comment by hsribei** [comment]
Awesome, it works! Thanks! :)

Em sábado, 15 de setembro de 2012, Tyler Renelle escreveu:

> Well, never could fix it - but hell, I implemented Auth anyway - give it
> another shot & register with FB
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/2#issuecomment-8591235.

## 

Sent from my phone.
