### ISSUE TITLE
Reset wont hide the store items again

### ISSUE THREAD

**Issue by acadavid** [HabitRPG/habitica#20]
It's not really a big deal but i was testing the app and i got to the point where i had the items from the store (sword, etc). I reset the account to start for real, and the items were still there.

**Comment by lefnire** [comment]
I hope you don't mind if I just leave that. My goal was to expose features incrementally so as not to overwhelm the user at first, and to do this via "unlocking" features. (Groups will be unlocked in the same way, once it's developed). So once you've been exposed to the feature, no point in hiding it even on reset IMO

**Comment by acadavid** [comment]
Oh ok, that makes sense! I just thought it was a bug. Loving the app btw!
