### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by netcriptus** [HabitRPG/habitica#200]
Hey, this HabitRPG is awesome!

One quick idea, how about changing "Todos" to "Quests"? Just to make it more "game-ish".

**Comment by StanLindsey** [comment]
I think its a great idea but the name may be"quests" reserved for future features. e.g. "Quests" are challenges that your friends/party send you or randomly generated ones you can opt in to. 

Check out the Trello for possible features that the word "quest" may be used for;
https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6

**Comment by lefnire** [comment]
Yeah, reserved for future feature. Let's keep the stuff that people are
familiar with standard, because RPG metaphors will come in other areas

**Comment by wc8** [comment]
Perhaps todo could be made a tad more gamified without losing real world meaning: _Actions!_ or _Act!_ but I agree that the basics need to be clear & familiar especially for new users.

**Comment by killroy42** [comment]
How about letting us change the list titles a-la Trello? I think I would feel more heoric and motivated to go on a quest to clear my desk, for example...

Also, perhaps we could up-vote features with kickstarter donations :D :D :D

**Comment by netcriptus** [comment]
Here's how I thought of that: last week my sister asked me to take the car to a carwash. Well, that sounded like a quest to me.

It didn't feel very game-like to put a quest on a "Todo" list.

**Comment by lefnire** [comment]
that sounds like a job for [this feature](https://trello.com/card/cross-profile-challenges-quests/50e5d3684fe3a7266b0036d6/58), but I'll add "manually renaming columns" to the feature list

**Comment by lefnire** [comment]
[Custom Column Names](https://trello.com/card/custom-column-names/50e5d3684fe3a7266b0036d6/113)

**Comment by netcriptus** [comment]
Not really. My sister is a lawyer, she thinks all this RPG is a waste of time, so I think it defines her as a NPC XD

**Comment by killroy42** [comment]
Woohoo!

Also, Tim Ferriss has done some research showing that value pledges, such as a group putting cash into a pot towards a fitness goal work really well. How about a party each putting gold into a pot and the top habit improvers get it? Stuff like that...

**Comment by lefnire** [comment]
Create a new ticket in github for each feature idea, if it doesn't already
exist on Trello, Habit has some awesome community managers that sort all
that stuff out periodically, convert them to Trello cards, and users can
vote on the cards, etc. We're gonna be tackling features top to bottom by
vote
