### ISSUE TITLE
Unable to Select a Class *or* do anything else

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2000]
I stuck looking at a popup that says "class system unlocked!" and requests that I select a class. One of them appears to be selected - it's coloured, with text describing it in the box below the 4 image boxes. Clicking "select" has no effect. 

While in this state, I can't record tasks as accomplished, let alone get myself into the Inn. I hope we still have a way to undo any bogus deaths resulting from this. 

I'm on https://habitrpg.com/ - not the beta site, which is confusing me. I thought classes were only available on the beta, and nothing I saw this morning suggested they'd be going live tonight. 

Using firefox 25.0.1 on Ubuntu 12.04.

![Uploading Screenshot from 2013-09-18 20:24:56.png . . .]()

**Comment by lefnire** [comment]
Are you seeing any javascript errors? Try a hard-refresh, and select again

**Comment by ArlieS** [comment]
what's a hard refresh? reload the page, or something more drastic?

reload caused me to take damage (huh?) and got me back to a state with nothing selected on the popup.

Selecting only the class I wanted - not looking at all the descriptions - got me success. I think.

**Comment by lefnire** [comment]
Actually click a refresh button, or the refresh shortcut key. Don't just
hit enter with the url in the bar

**Comment by ArlieS** [comment]
apologies for confusion - updated comment above, as things changed. And lost the screen shots. Bottom line, browser's reload got me back to the popup with nothing selected. Selecting only one thing - not checking them one by one - and then clicking select - worked. 

I think it wants me to allocate stats now.
