### ISSUE TITLE
All my armor disappeared :( 

### ISSUE THREAD

**Issue by BanktownUSA** [HabitRPG/habitica#2002]
Okay two parts. I couldn't log onto habit yesterday and was unable to check off my tasks. Because I was low on HP I died. Usually this only downgrades one item a level. And it didn't change until after I said I wanted to be a rouge instead of a warrior all my armor disappeared and put me back at base zero. If I'd known changing freaking classes would make me start back at zero i definitely wouldn't have changed. I'm not sure what is going on, but since the restore button is now gone. I can't manually fix it.

**Comment by lefnire** [comment]
Once you select your class, the tutorial popovers explain that your gear has not disappeared, they have been placed in your inventory and you've been equipped with your apprentice class gear. Simply go to inventory and re-equip

**Comment by BanktownUSA** [comment]
My Tutorial is frozen and won't disappear or advance.
