### ISSUE TITLE
Unable to change gear in costume mode

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#2003]
This is my new class, all of my warrior gear is available but nothing from my new (healer) class. Special gear is available

**Comment by lefnire** [comment]
So, to make sure I'm understanding properly.. All your warrior gear is available in your inventory, but no healer gear is available for purchase in your item store (/#/tasks page)?

**Comment by Mihakuu** [comment]
I went ahead and got all the healer gear from the store, but going into inventory it doesn't show anything for my healer gear at all. It's like I didn't get it or maybe a missing piece that would display another list like the warrior one?
![gear](https://f.cloud.github.com/assets/3769301/1761823/322daabc-66de-11e3-943a-f84629951a6c.PNG)

**Comment by lefnire** [comment]
949cd97 , pushing
