### ISSUE TITLE
Unable to Accept or Reject Party Invitation

### ISSUE THREAD

**Issue by Krolahzul** [HabitRPG/habitica#2004]
UserID: 217b0064-7259-474a-8402-1fa45b0ebbf7

On my party screen, I see the words "You are invited to" and then it just goes blank. 

When I hit accept, it gives me a 404 error with this console code:
POST https://habitrpg.com/api/v2/groups/join? 404 (Not Found) 

When I hit reject, this pops up instead:
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.

**Comment by lefnire** [comment]
hmm, your account in the database seems fine.. can you try a hard refresh (manually click the refresh button, don't just hit enter in the url bar) and see if it fixes?
