### ISSUE TITLE
9.29 GP for a new (yellow) to-do?

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2005]
I just completed a brand-new todo item and received 9 XP and 9.29 GP! I created several more and confirmed that I'm getting 9.29 each time. I just classed to Rogue and have not allocated any stat points yet. I know rogues are supposed to get more gold, but this seems high enough that I wanted to check whether it's really right. 

I also note that if I uncheck the todo, I only lose 8 XP and 7.82 GP.

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2001 . Chime in there with your level as well.
