### ISSUE TITLE
Stats disappeared after the class change

### ISSUE THREAD

**Issue by EvilTosha** [HabitRPG/habitica#2009]
I changed my class from rogue to rogue and discovered that I don't have any stats to allocate (and all allocated stats are 0). Then I changed to wizard, and the situation was exactly the same. I'm level 12.
![habitrpg your life the role playing game](https://f.cloud.github.com/assets/712705/1765511/ff3547a6-6736-11e3-9ba1-cb3530bbf0be.png)

**Comment by lefnire** [comment]
By intent, "change class" is also a reroll (@sabrecat @danielthebard see I'm tellin' you guys, we should call it reroll - someone else asked "how do reroll my stats"?). I'll add a help (?) to explain such

**Comment by lefnire** [comment]
(incidentally, it _is_ in the confirm dialog) ![1](http://gyazo.com/7d4d7fd13f1d3bccdd1ad58214d38c8c.png)

**Comment by Pandoro** [comment]
I actually was also wondering where reroll was.

**Comment by EvilTosha** [comment]
It says "you'll get them all back to re-allocate", but it doesn't give them to me.

**Comment by sleepykit** [comment]
I'm with EvilTosha. You don't get the points back to reallocate. So they're gone now?

**Comment by lefnire** [comment]
oi! I missed the bug entirely. Got it, thanks guys - pushing fix now. Give me your UUIDs for your gems back, and do another re-roll in 5m

**Comment by sleepykit** [comment]
4b378ace-e802-4349-a2c2-7bdc07fff75a

**Comment by EvilTosha** [comment]
aecd54bd-6832-4d47-a82c-8aea1e1092b6

**Comment by lefnire** [comment]
Gem'd you both, re-roll away
