### ISSUE TITLE
HeyOffline Support - Let Users Know They're Offline

### ISSUE THREAD

**Issue by Andrew565** [HabitRPG/habitica#201]
Slappybag: Added to Trello: https://trello.com/c/lUlKuIHK

http://oskarkrawczyk.github.com/heyoffline.js/

Good little tool for letting people know they've gone offline and their changes won't get synced.

**Comment by StanLindsey** [comment]
Added to Trello: https://trello.com/c/lUlKuIHK

**Comment by horusofoz** [comment]
@SlappyBag With this now added to Trello, should we close the ticket as appears to be the process with other feature requests that graduate to Trello?

**Comment by StanLindsey** [comment]
Yeah, its a bit of a grey area as sometimes discussions are very much alive here on Github so I keep them open. But as I caught this one early the discussion can move on Trello. =D Thanks.
