### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by no1yudkno** [HabitRPG/habitica#2011]
I downloaded the app and registred last week and lve it so far. today i logged out of the app and was not able to sign back in because of a server connection issue. Then I went to login on the actual website to check it out, which i have never done before. I enetered my info and it says it does not recognize my username. When i have it re send the password to my email it sends me the exact username i entered, i have even cut and pasted it. this is very frustrating I am hoping to get some answers here. Thanks.

**Comment by lefnire** [comment]
do you have your UUID handy?

**Comment by lefnire** [comment]
also, #2014 might be similar

**Comment by no1yudkno** [comment]
im not sure what that is if its my username its no1 yud kno

**Comment by no1yudkno** [comment]
bump

**Comment by lefnire** [comment]
do you have your UUID handy? `no1 yud kno` is not in the database

**Comment by no1yudkno** [comment]
im not sure what the uuid is sorry

**Comment by no1yudkno** [comment]
this is one of the emails i recieved 
HabitRPG admin@habitrpg.com
10:28 am (1 day ago)

to me 
Password for no1 yud kno has been reset to bf5788cf97. Log in at https://habitrpg.com

**Comment by lefnire** [comment]
oh, looks like you have a space at the end of your user username - try adding that

**Comment by lefnire** [comment]
See UserID section of http://habitrpg.wikia.com/wiki/API

**Comment by no1yudkno** [comment]
i just tried it with a space at the end and it still pops up saying username not found

**Comment by lefnire** [comment]
Try now, I removed the space from the end in the database

**Comment by no1yudkno** [comment]
thank you sir you are the best

**Comment by lefnire** [comment]
np, sorry for the srangeness!
