### ISSUE TITLE
API v1 is no longer supported

### ISSUE THREAD

**Issue by afs2015** [HabitRPG/habitica#2014]
I downloaded HabitRPG for my iPhone 4s but when I tried to login I got this error. "API v1 is no longer supported. please use API v2 instead (https://github.com/HabitRPG/habitrpg/blob/develop/API.md)"

**Comment by lefnire** [comment]
Oh shoot... what was the action that caused this? Registration? Login? Clicking a task? Or simply loading the app and not doing anything?

**Comment by afs2015** [comment]
The action that caused this was clicking the green Login button, a popup box titled index.html provided the error message. If I can provide you any other useful information that can help please ask.

**Comment by lefnire** [comment]
Fixed in a661c18 , can you try again now?

**Comment by afs2015** [comment]
I was able to login fine now. Thanks!
