### ISSUE TITLE
Grammar: Affect vs. Effect

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2016]
Similar to #1104.
Quoth SirGoodSir:

> Oh can't wait to learn more about the class system. But this was painful:
> "These are your class's stats, they effect the game-play."
> Not effect. Affect.

**Comment by lefnire** [comment]
*rolls eyes*. Here I am hunting the cause of `{ code: 500, data: { err: { [MongoError: LEFT_SUBFIELD only supports Object: preferences.hair not: 2] name: 'MongoError', err: 'LEFT_SUBFIELD only supports Object: preferences.hair not: 2', code: 10145, n: 0, connectionId: 251218, ok: 1 } } }`, and people are griping about grammar. alright, fix comin' up.

**Comment by wc8** [comment]
@lefnire that’s why I marked it minor… I expected it to sit for a while. You need Github integration… an automatic **+** habit for every pull request you submit…maybe even an option on submission to choose _that was_ **_hard**_ and you score extra.

**Comment by lefnire** [comment]
There was a project with such support somewhere... I need to hunt it down again, I'd not be a n00b anymore!

**Comment by SabreCat** [comment]
@lefnire If you want, you can keep your attention on the thorny stuff and assign niblets like this to people like me, @Xatres, etc.!

**Comment by lefnire** [comment]
sounds good!

**Comment by wc8** [comment]
@SabreCat and @lefnire How about I make a label for these? e.g. “wording” 
That way, @lefnire can ignore them and @SabreCat and @Xatres can filter for them.
P.S. going to start this, can delete label if any issues.

**Comment by lefnire** [comment]
Sounds good to me

**Comment by SabreCat** [comment]
Cool. Will be useful for any enterprising content-editor/light coder, not just me and @Xatres!
