### ISSUE TITLE
Class changing

### ISSUE THREAD

**Issue by Arcklo** [HabitRPG/habitica#2017]
When prompted to choose a class, i looked it up in the wiki and saw the cooldown-based changing system. Since i was undecided between wizard and rogue, i went with rogue temporarily in the assumption i could freely change my mind later.
  I now find it is not yet implemented and currently requires gems. I humbly request a free change and suggest you guys at least mention in the wiki(and perhaps elsewhere) that it's not in yet.

**Comment by lefnire** [comment]
changed Wiki, shoot me your UUID and i'll give 3g

**Comment by wc8** [comment]
@Arcklo which page were you looking at? The wiki Class page has said, "At present, it costs a flat 3 gems to change a class. In the future, we'll add a "cooldown" mechanism.”" for a while now. I want to make sure there’s no other page or section that needs updating.

**Comment by Arcklo** [comment]
@wc8 I looked at the page today, 17:08. This was the page then: http://habitrpg.wikia.com/wiki/Class_System?oldid=8487

@lefnire Thank you <3 It's 6bb9d67a-675a-4391-bf0f-381f2749b764

**Comment by wc8** [comment]
@Arcklo thanks, so the wiki should definitely be fixed, then. Good. So when @lefnire gets a chance to give the gems we can close this.

**Comment by lefnire** [comment]
@Arcklo updated you.

**Comment by wc8** [comment]
@lefnire would it be possible to add a confirmation button if users choose anything other than warrior? Suggested text on select: 
_Are you sure? Changing classes in the future will cost 3 gems._

**Comment by lefnire** [comment]
Will take some extra work, i'll need to add an extra `user.flags.___`. Doable, I'll put it on my list

**Comment by wc8** [comment]
Here’s a further idea: 
1) update Class System Unlocked dialog to:  "You can now _change your class_”
2) To warrior add description, _Your current class_.

Hopefully, that way users will understand they still have the option to keep going with their current class.

Also, having given it some more thought, I’d add _Are you sure? Changing classes in the future will cost 3 gems._ to all selections.

**Comment by lefnire** [comment]
I'm also thinking of adding another yellow button next to "Select" which says "Opt Out", which automatically sets your class to warrior, 'auto allocate', and hides stats. Then adding a settings button "enable class system"

**Comment by wc8** [comment]
@lefnire sounds good.
I wonder if users are getting struck with classes more rapidly than they would otherwise and finding it overwhelming? In other words, if Level 5 introduces classes and gear options, Level 6 introduces MP and 1 spell, and Level 7 another spell, but users are Level 14 they’re getting hit with a lot of information at once. If so, it’ll be less difficult for newer players.

**Comment by lefnire** [comment]
Is the suggestion to unlock it later then? (had trouble following)

**Comment by wc8** [comment]
Those commits are also relevant to #1991 but I don’t know how to link them directly.
I’m working on updating the wiki with productivity uses for class features like mana and spells, so hopefully users will feel less overwhelmed by it.

**Comment by SabreCat** [comment]
@lefnire If I'm reading @wc8 right, it's that we have a huge userbase of players who are already well beyond the point of unlocking classes. So rather than getting class select, a few points, their first spell; then another spell; etc. they immediately have dozens of points to allocate and a whole raft of new options due to the rollout.

**Comment by wc8** [comment]
@SabreCat yes. 
My thinking stems from the wiki saying Level 5 unlocks classes, Level 6 unlocks your first spell. 
Any idea if the wiki is correct? (I’ll try to check it at some point with my test character if I can.)

**Comment by lefnire** [comment]
Correct - that's the current way of it

**Comment by wc8** [comment]
By the way, I wasn’t thinking of having users opt out of Mana & Spells…It’s done now, but maybe we should have a discussion somewhere about reintroducing it gradually. I think it would be good in general if Justin-the-Guide explains it as an optional productivity tool.
P.S. Later…
