### ISSUE TITLE
Healer Symbol

### ISSUE THREAD

**Issue by Aubec** [HabitRPG/habitica#2019]
This isn't a bug, so I apologize if I am making a comment in the wrong place.  I'm excited about the new class system.  It's great to see depth being added to the Habit experience.  In looking over the things I target for myself, many of them are social and the healer would seem to be a good fit.  However, I don't happen to be a Christian and I notice the fellow has a cross on his shield.  I believe there are options for item appearance where I won't need to use it, but I thought I would put a vote in for the use of symbols that don't tie to any particular religion.  

Thanks much, sorry to be a bother.

**Comment by lefnire** [comment]
We were thinking more along the lines of Redcross, the **+** being the universal [medic sign](https://www.google.com/search?site=&tbm=isch&source=hp&biw=1440&bih=735&q=medic&oq=medic&gs_l=img.3..0l10.300.733.0.769.5.5.0.0.0.0.193.553.1j3.4.0....0...1ac.1.32.img..2.3.360._096yM1hmWM#q=medic+sign&tbm=isch). You'll probably want to take this up with the pixelists on this [Trello card](https://trello.com/c/tRRgqhgP/218-class-gear-pixel-art)

**Comment by lefnire** [comment]
@RosemonkeyCT looping you in

**Comment by SabreCat** [comment]
I had a similar reaction when working on the gear descriptions. I wouldn't at all mind de-religionizing things if we do change the pixel art: a few names and descriptions could use similar tweakage ("crosier" and "Hospitaler" are pretty Roman Catholic things, f'r instance).

**Comment by RosemonkeyCT** [comment]
Hi... yeah, I tried to make sure it was more "central cross" for universal medic sign rather than the christian connotations of paladins and crucifixes. It's definitely not intended with the religious link. I can have a go at a redesign if people are unhappy with it though.

**Comment by wc8** [comment]
@RosemonkeyCT and coders, how about an alternative rather than a replacement? 
So for example, a choice of white shield or the existing red-on-white.

@SabreCat I’d pick fantasy-ish labels over real-life political/organization labels regardless of whether the option changes—extra points for alluding to the original medical intent.

**Comment by RosemonkeyCT** [comment]
Even with fantasy I couldn't think of another symbol commonly associated with healers, but I don't want to make anyone offended =(

**Comment by wc8** [comment]
@RosemonkeyCT the overall effect of the combined gear looks more like a **royal healer** than anything else—and very unique and cute. 
Also, the original post doesn’t mention being offended, just preferring another option.

**Comment by Aubec** [comment]
Hi All, I enjoy all of the Habit art, and agree that the healer is both unique and cute.  So, please don't be sad! Generally speaking, in a multicultural community, I like the idea of avoiding symbols from any particular religion.  Now, Habit lets you change your avatar's appearance without losing stat bonuses from your best gear.  So, I think this is a pretty minor issue.  I'm looking at it now and the horizontal bar is definitely on the upper side of the cross.  Could you lop off the bottom tip of the vertical bar so that the length of each bar of the cross was identical and it looked like a plus sign?

Again, I don't see this as a big deal, I just thought I would mention it.  Also, thanks for all your hard work on the Habit art, it's really great and I'm a big fan.

**Comment by RosemonkeyCT** [comment]
Thanks guys, I'm glad you like my work and I've not upset anyone.

Is this better:

![shield set](https://f.cloud.github.com/assets/5843898/1781336/263be07e-6892-11e3-95c2-f5063a756df7.png)

**Comment by Aubec** [comment]
You've captured what I was envisioning exactly.  I love it and I think it's perfect for the class.

**Comment by RosemonkeyCT** [comment]
I struggled with it the first time around, but I like how these have turned out... @lefnire is this something which could/ should/ needs to be changed?

**Comment by lefnire** [comment]
Great! I'll swap those in the moment I can, thanks @RosemonkeyCT

**Comment by RosemonkeyCT** [comment]
You're welcome =)

**Comment by SabreCat** [comment]
I'll put it on my list to change up some of the equipment names, then, too.

**Comment by wc8** [comment]
Should this be reopened until it is done? Or just follow up with Trello card?

**Comment by SabreCat** [comment]
@wc8, you can reopen and assign to me if you want to track it better. I'm going to work on the renames tonight, should be done by tomorrow at the latest.

**Comment by SabreCat** [comment]
Addressed textual issues at https://github.com/HabitRPG/habitrpg-shared/pull/58

**Comment by SabreCat** [comment]
Make that https://github.com/HabitRPG/habitrpg-shared/pull/59, d'oh.

**Comment by SabreCat** [comment]
Art and text have been updated. @Aubec @RosemonkeyCT @wc8, please comment and re-open if there are any lingering concerns!
