### ISSUE TITLE
Time-based tasks

### ISSUE THREAD

**Issue by w13** [HabitRPG/habitica#202]
Trello: https://trello.com/c/FwSlQrR5

I have one task called "1 hour uninterrupted studying". (I accidentally clicked it twice just now.)

So, what I suggest is that I can optionally set how long a certain task lasts ("1 hour", "30 minutes", etc.) - and that way I will never be able to accidentally double-click... and I won't need to time myself separately. HabitRPG can do it for me. It can say, "Current task: 1 hour uninterrupted study. [12 minutes to go] " - it is a lot like how it takes a few seconds to mine an ore in RPGs.

**Comment by StanLindsey** [comment]
I use a timer for a number of tasks in real life so this could be a good feature later on down the line. When the phone/webapp etc are all integrated properly you could start a task on your PC and have the alarm go off on your phone or in your browser. Would be great for taking breaks or similar. 

I've added this to Trello so give it a vote if you think its an important feature to work on!
https://trello.com/c/FwSlQrR5

**Comment by lefnire** [comment]
check out my comment on that card, i'm currently doing that

**Comment by horusofoz** [comment]
Suggestion and discussion moved to [Trello](https://trello.com/c/FwSlQrR5).
