### ISSUE TITLE
Gold disapears on refresh

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2021]
If I refresh my main page there seems to be a chance I will randomly loose gold.
the one time I noticed it fist about 36g--I thought maybe it unregistered a todo that I had just completed multiples of, so didn't pay much mind. This latest time, however, was in the morning and I lost 9 gold & some silver.
I have both the Android app and the webbrowser in use. The Android app was not open, there was only the one window open in the browser (Firefox 26.0, the latest update)

In addition, after the update, any time I click something that's not a habit/todo/task/purchase it causes the entire browser to stall and go non-responsive for a time. It did this previously, but not nearly as consistently.

**Comment by wc8** [comment]
In the morning sounds like you lost health for incomplete dailies. Is that a possibility? Is it possible one of the browsers was simply updating to match activity in the other?
If not, while you wait for help from developers, there’s a fix button in Settings that will let you correct your gold amounts.

**Comment by ghost** [comment]
Yes, I had, but that refresh had already appeared. This was later (at least 15minutes to an hour, I have no concept of time), and a separate, refreshed and it just flashed up on its on, there was no health or XP hit with it.

In addition, the other time I noted it, where I lost about 36 gold, happened at night, but well before my day reset time

**Comment by BlackEdder** [comment]
I notice that backstab was not holding for me, i.e. if I did a backstab, some time later I would lose the could again and gain the mana back. Could that be what's happening to you?

**Comment by ghost** [comment]
I just checked off a task and LOST gold instead of gaining it (despite the little pop ups telling me that I gained gold). No spells in use.

Edit: Hmm, it may not have been the checking of the task that did it. I know I was one piece of gold away from being able to buy something, checked off a task and then noticed I was down about 7 GP but the gold may have disappeared in between me last looking and the checking off of the task.

Edit: And half an hour later my gold is mysteriously back. I'm pretty sure I haven't checked off enough tasks to earn it back. Curious.

**Comment by lefnire** [comment]
This sounds like https://github.com/HabitRPG/habitrpg/issues/2157 . You need mobile apps versions 0.0.15. iOS is still pending review (they take forever...). Check that ticket, if it sounds like the same issue close this, if not hit me up

**Comment by ghost** [comment]
I don't have an iphone, I'm using the android app. Does it have the same problem? (though this would also occur on days I didn't use the app)
However, it doesn't seem to have been happening recently, so something has changed.

**Comment by lefnire** [comment]
As long as you're on 0.0.15, you should be sorted. Android & iPhone apps mirror eachother exactly (a huge benefit of using PhoneGap + AngularJS), so they experience the same issues. The reason iPhone users are experiencing more, is because iOS takes about 2weeks to approve an app submission, while Android users get updates immediately (as long as they're set to auto-update). Ugh, Apple... 

Anyway, it sounds like the 0.0.15 app upgrade (which was around the time of this ticket) has solved the issue for you

**Comment by ghost** [comment]
Awesome! thanks :)
