### ISSUE TITLE
I can cast "Pickpocket" on "Burst of Speed"

### ISSUE THREAD

**Issue by stachurskip** [HabitRPG/habitica#2022]
Step to reproduce:
1. Choose Rogue as character class
2. Left-click on "Pickpocket" spell (with enough mana)
3. Think few second to find task to boost.
4. Can't find anything to boost so give up by left-clicking on "Burst of Speed" spell.

My many has gone and I don't have boost :(
I haven't try it with other spells.

**Comment by wc8** [comment]
Don’t fix this—it’s too cute. Ahem, seriously now: I’m not sure but there’s just a chance that Mana/Magic points can be fixed under Settings > Fix Character Values. If not, @lefnire or @SabreCat should we add Mana Points correction there?

**Comment by lefnire** [comment]
It's there

**Comment by deilann** [comment]
I think it makes sense to move this to #2647 -- includes being able to cast spells on rewards & completed To-Dos.
