### ISSUE TITLE
Pickpocket double bonus

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2023]
Level 45 rogue, cast pickpocket and clicked a dark red to-do. I got the usual reward and XP, plus two additional notifications of 1.86GP each (so, four in total: XP, main GP, 1.86 bonus, 1.86 bonus). Then I clicked a daily, and shortly after that I got an additional notification of -1.86 GP.

**Comment by deilann** [comment]
I'm gonna bet this is related to #2554
