### ISSUE TITLE
Notifications are very easy to miss

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2024]
The small-print, translucent notifications that pop up in the upper-right hand corner of the screen are very easy for me to miss. They don't draw my eye at all, and sometimes they disappear so quickly that even if I'm looking for them I don't catch what they said. It's a particularly noticeable problem when I'm not expecting them, because they'll be sending an error message and I won't notice it (this happened recently when I was trying to hatch a pet I already own). Various solutions might be to make them more opaque, to make the background contrast more strongly with the main window background, or to have an option to change the location where they pop up.

**Comment by ghost** [comment]
maybe they should stay more, like 5 secs insetad of 1 or 2?

**Comment by octern** [comment]
That would help in some cases, but not with the ones that I don't notice in the first place (it's the act of popping up that causes notifications to catch my eye, so if I didn't see it right away then keeping it around won't help).

**Comment by wc8** [comment]
I’ll try to look up the link for this (or add it if it’s not in Trello) later, but I think there’s a request to add a notification button where you can look up old notifications.

**Comment by brightbold** [comment]
I think this is a bigger problem now that drop notifications have moved there too. I didn't think I'd gotten any food drops today, only a couple of eggs, but when I just checked my inventory I had 5! Clearly I missed the notification of the majority of my drops, even though I knew the notifications had moved and was making an effort to remember to look for them in the corner. 

I think for motivational purposes you really need to see the drop when it happens. Keeping it around longer would definitely help some (when you get multiple notifications on one click, for instance, if you level up, there's not time to read all the notices) but as @octern says, we probably need a way to make them a little more attention-grabbing

**Comment by SabreCat** [comment]
Yeah, we wanted to get some feedback on that. I love not having the intrusive modal, personally, but agree that the notification can be too subtle. I tried to have the picture of the dropped item show up, which I think would be pretty eye-catching, but couldn't get the code to work...

Another thing could be to bolden up the color of drop alerts. At present they're the default text notification style, which is kind of a desaturated yellow/orange thing that looks inconsequential.

**Comment by SabreCat** [comment]
Relevant: Some great suggestions from "E" [here on the community forum](http://community.habitrpg.com/content/suggestion-food-mouseoverdrop-notification-text)!

**Comment by crystalphoenix** [comment]
i was wondering... is it possible for there to be a notification history page? there's so much going on in that corner now that it's difficult to catch it all before it disappears. 

if it's combined with a time stamp and a source, such a page could also be a partial fix to http://community.habitrpg.com/content/indicate-date-time-habit-was-last-completed
i'm trying to think of how such a thing would look on the site and i was thinking of a slide out column on the right side of the screen (could be the same on mobile apps when that comes around) that can be pulled out with some sort of arrow on the top right of the header. perhaps under our username?

**Comment by wc8** [comment]
@crystalphoenix how about https://trello.com/c/684Dv1py

**Comment by wc8** [comment]
@SabreCat what if you increase length of time on screen?
As far as E’s suggestions,I like them. I’ll convert it to a card for voting.

**Comment by wc8** [comment]
https://trello.com/c/207q72VI E’s notifications—although I think it’s minor enough you could go with a pull request, @SabreCat. So far I’ve only heard voices in favor.

**Comment by crystalphoenix** [comment]
ah! thank you @wc8 ^_^ i'll shift my thoughts there :)

**Comment by SabreCat** [comment]
@wc8: OK, I'll see about implementing E's text and extending the visible time for notifications. Might need to unassign myself after that if there's deeper redesign to be done.

**Comment by paglias** [comment]
The time is longer now, as for keeping an history let's use #3297
