### ISSUE TITLE
Can't use Staff as a costume when using Sword+Shield

### ISSUE THREAD

**Issue by marcelosizer** [HabitRPG/habitica#2025]
I just got my mage class and I decided to keep using my previous gear and wear the mage equipments as costumes but I'm wearing sword+shield and when I put a staff as a costume I get this error:
![staff2handed](https://f.cloud.github.com/assets/6205335/1768667/0f0fbf06-6766-11e3-822d-4dbc66eff1ed.png)
And when I reload the page my weapon gets set back to the previous one I was using, be it a 1-handed weapon or no weapon if that was the prior.

It only affects the costumes, the gear is ok.

**Comment by SabreCat** [comment]
Yeah, I noticed this too. So my mage is packing sword and shield again, heh...

**Comment by lefnire** [comment]
I'm not sure I follow, unless I simply can't replicate:

![1](https://www.evernote.com/shard/s17/sh/4232d3ae-6d16-43ca-82a7-91a231e7a9ed/e474416bf8c1b09a8930d5bfe8205a43/res/08500823-d234-41aa-915c-085f70498fc9/skitch.png?resizeSmall&width=832)

FWIW, staves will un-equip your shield (since they're two-handed), and shields will un-equip your staves. Both costumes, and equipment

**Comment by SabreCat** [comment]
Evernote access denied on link.

What I'm trying to do:
Sword and shield equipped as Gear.
Wizard staff equipped as Costume.

Even though Gear and Costume should be entirely separate, I am disallowed from Costume-equipping a staff while Gear-equipping a shield.

**Comment by lefnire** [comment]
Oh, I see it. Ok, on it (god, why does my Skitch intermittently deny
access..)

**Comment by lefnire** [comment]
probably TMI, but bug was my new APIv2 shared ops framework - if an error is 200, that means "success, but give them a message" (eg, "weapon is two handed). If no code is provided, it's assumed to be 400, not 200. 400 is a real error, don't send op to the server. so I just have to change `cb(message,req)` to `cb({code:200,message:message},req)`

**Comment by marcelosizer** [comment]
Just checked and under the new Equipment tab it seems to be working ok!

**Comment by SabreCat** [comment]
:+1:
