### ISSUE TITLE
Skill using more mana than displayed.

### ISSUE THREAD

**Issue by AtgeirManagarm** [HabitRPG/habitica#2026]
I tried out "Pickpocket" on a light red "to do" task which shows it should cost 10MP. I had 29MP to start with and after using the ability I was down to 9MP. 

There were several notifications in the top right showing the gold increases but I didn't see any that said I'd used extra MP, they do move pretty quickly though.

I use Chrome version 31.0.1650.59 m and my user ID is 85af968b-6cd1-4333-9738-38fcbb0658f8

**Comment by SabreCat** [comment]
Duplicate of #2012. Follow up there!
