### ISSUE TITLE
Critical hits need their own alert callout

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2029]
For a little while after the Classes rollout, I was baffled at why sometimes I was getting upwards of 6 gold for a single click, and other times I got only 2 or so. My hunch at this point (after the recent PER rebalancing) is that critical hits are happening sometimes? Do we display an alert "Critical hit!" or similar to let the user know what just happened?

Some cool animations would be awesome, but at least we need an alert, heh.

**Comment by lefnire** [comment]
yep

**Comment by SabreCat** [comment]
Er... "yep" we have an alert already, or "yep" we need one?

**Comment by lefnire** [comment]
yep we definitely need one. was on my workflowy, but better in GH - thanks!
