### ISSUE TITLE
Can't re-buff same party member - Invalid target

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2030]
I cast a STR buff the other day on my Party Leader.  My buff appeared to expire within 16 hours or less, which I was a bit disappointed with, as my party is international, so there's no telling if anyone actually reaped the benefit or not.  

I decided to cheat, and reset my mana to its max.  

I then tried to buff my party leader again with the same STR buff, but I got a yellow message 'Invalid target'.  

I then successfully buffed another party member B.  I then decided to try out my second buff ability - a DEF buff, and I could not buff party member B with my DEF buff, I got 'invalid target'.  

I had to buff party member C to get both buffs to take.  

This appears to make buffing work only once on each party member - could this please be checked into and fixed?  Is it because I reset my mana, or is it an inherent bug?

**Comment by lefnire** [comment]
A few things:
- There are no individual member targeting spells (huh! we have the framework for that, I wonder what happened to such spells? @SabreCat @DanielTheBard). Per chance you were actually casting a debuff/attack spell on your friend? 
- So, an unfortunate technicality is that buffs only last until _each user's next cron_. This means it's not 24h _per se_ - it's from when you cast it, till their next roll-over. I'll start thinking on a fix for this, but it's probably gonna be this way for a long while.
- I'm pushing some casting fixes presently, can you try some casts again in 5-10m? (remembering to hard-refresh your page beforehand)

**Comment by lefnire** [comment]
yes, I think the first point is indeed an issue. What happens is it doesn't fulfill the casting until you get a success from the server. So your green **+** icon still shows up while the server is chugging, you try to cast it on someone (invalid target, since it's a party spell), server then comes back later and says "all good!" - and you think something funky happened in between. I just need to remove the green icon the moment it's cast

**Comment by SabreCat** [comment]
Hum, spells are all DTB. I barely read the abilities, was too busy with gear :cat::sweat_drops:
