### ISSUE TITLE
Should be Mage, not Wizard

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2031]
Per Trello discussions, we'd settled on "Mage" for the name of the magicky class. But the label in the Stats page says Wizard (and in all lowercase to boot):

![screenclip](https://f.cloud.github.com/assets/4501321/1770253/986be93e-6787-11e3-9b77-4e8aa2db792b.png)

**Comment by lefnire** [comment]
wizard is the key for everything in items & database. I didn't realize that
mage had been the consensus after all, this is going to require a migration
and site downtime

**Comment by SabreCat** [comment]
Whoops! Well, we can leave it if it's going to be a big pain, but that was indeed the consensus :cat::sweat_drops:

**Comment by lefnire** [comment]
Well, let's keep it open and then next time we do a version site downtime migration we'll slip this one in

**Comment by wc8** [comment]
How many votes are needed to change to consensus? (I like wizard. :smiley: )

**Comment by Johangsl** [comment]
probably mage works better for the future, for if there is a day we have second tier classes  

like

1st class - Mage

2nd class - Wizard or Spellsword

something like that...

**Comment by wizonesolutions** [comment]
...Spellsword?

**Comment by Johangsl** [comment]
Well its an advance class, a mix of warrior with mage...you could think of
any other tier 2 class...red mage...i don't know lol

**Comment by lefnire** [comment]
Actually Sabe, don't mind me. We can leave is wizard as keys in code and
database, and use Mage for html display. Dirty, but whtaver

**Comment by SabreCat** [comment]
@lefnire: We've already got that with "Fortify" which is in code as "reroll", all my fault xD

**Comment by lefnire** [comment]
Eh whatever, as long as people see the "clean" version. Kk, I'll start
renaming as Mage

**Comment by Johangsl** [comment]
Tyler if you like wizard better, Leave it :)

**Comment by lefnire** [comment]
Incidentally i like Mage better, I just missed the concensus. Will fix
