### ISSUE TITLE
I have a Shade Helm I didn't pay for

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2034]
When classes rolled out, I got a Shade Helm even though (a) I didn't contribute to the Kickstarter, and (b) I'd never purchased it from the Rewards shop. Maybe something funky happened with the fact that I had the contributor Crystal Helm at deploy time?

![screenclip](https://f.cloud.github.com/assets/4501321/1770365/f77e5ea8-678b-11e3-89fb-c6e1f60a7769.png)

I'd suggest deleting these items from folks who shouldn't have them (pretty easy to determine, yeah?).

**Comment by lefnire** [comment]
Yep, I need to run a migration to remove these. I know exactly what went
wrong, and exactly the fix (it shouldn't be too hard)

**Comment by lefnire** [comment]
ran migration. @SabreCat can you check you're good? @mihakuu you still have your backer stuff?

**Comment by SabreCat** [comment]
Poof! Shade be gone. Thanks!

**Comment by nafoster** [comment]
I also still have Shade gear though I'm not a backer.

ID: f90f3c99-8e91-433d-8db2-7377c6c8f709

**Comment by lefnire** [comment]
@nafoster hmm... do a refresh, checked your account and the gear shows gone in the db

**Comment by SabreCat** [comment]
Yeah, it took a hard-refresh for me.

**Comment by Mihakuu** [comment]
It looks like I still have everything I had before

**Comment by nafoster** [comment]
@lefnire All set on my end. Had to hard-refresh as well.

**Comment by lefnire** [comment]
Grand! √
