### ISSUE TITLE
Need headers on the Equipment panes

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2035]
The Equipment tab under Inventory is a fantastic improvement! However, it's a little disorienting to look at, since the only indication of what's different between the left and right sides is the "Use Costume" checkbox:

![screenclip](https://f.cloud.github.com/assets/4501321/1770377/2fefdbb8-678c-11e3-94f7-06d5f1bb5320.png)

Let's put in "Gear" and "Costume" headers, an h-level higher than "Base" "Special" etc. We could even include ? bubbles for each, explaining what they represent--in the Costume case, moving the ? bubble up from the checkbox to the header.

**Comment by wc8** [comment]
Definitely it’s not clear. While :question: bubbles are a good idea, can we make the headings clearer to begin with? 
Brainstorming here: _Pick Your Battle Gear_ and _Pick Your Character’s Costume_
:question: bubbles then explain further.

**Comment by SabreCat** [comment]
@wc8: I like it!

**Comment by wc8** [comment]
I added an entry-level code label to this, @SabreCat, feel free to remove it if it’s harder than I think. (I’m not a coder so I’m guessing) or should we get @lefnire approval first? I’m figuring he’d be reviewing the pull request.

**Comment by SabreCat** [comment]
Entry-level code is legit. Pull request review is already part of the system (new arrivals can't push their code directly into "official" branches), so nothing to worry about there. Tag away!

**Comment by SabreCat** [comment]
Oh, and I'm bashful and tend to get my pull requests reviewed even though I do have the power to push them right in, so no fear from my side :P

**Comment by lefnire** [comment]
Bashful is good when merging, and bold is good with PRs. I'll merge, then
fix what needs fixing. Y'all are doing it correctly :-)

**Comment by SabreCat** [comment]
We've got "Battle Gear" and "Costume" now with explanatory text. While there's improvements to be made (e.g. #2158), this issue itself is taken care of.
