### ISSUE TITLE
"Drops" is an odd name for the Market

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2036]
With the reshuffling of the Inventory tab for class gear, we now have a sort of miscellany tab called "Drops". This makes sense for the left-hand side--all your collected items that can fall off of tasks when you click them--but doesn't well capture the inclusion of the Market on the right.

I think it's fine for now (an improvement over Inventory-Inventory, hah), but long-term I'd like to see a retooling of this...
- Make the Drops tab the Shop or Market. Make this all about buying and selling things--remove pet-hatching workflow from that screen.
- Move pet hatching to the Pets tab. Someone (alas, I don't recall who) suggested this: when you have a legal combination of egg and potion to hatch a pet on the grid, change the ? pawprint icon to the icon of the egg. Click it, you get a prompt "Hatch this [species] egg with your [relevant hatching potion]?" Say OK, and pow, pet is born and dropped into the grid.

**Comment by SabreCat** [comment]
If we implemented the hatching delay idea, you could have eggs-in-progress get a little crack that grows as hatching time gets closer!

**Comment by breadstrings** [comment]
Will we get the animation you've been working on? I like the cracked animation. :+1: from me. :)

**Comment by wc8** [comment]
I like all of this… especially with the hatching delay and cracked animation. :+1: 
I think the Pets tab is the Stable. It makes sense to have your hatch-able eggs in the warmth of a stable.
Should this go in Trello or stay here?

**Comment by SabreCat** [comment]
@wc8: I tend to have trouble making the distinction of what belongs in Trello and what belongs in GitHub. I have trouble finding the right card for a suggestion even when I feel Trello is a better fit. And Trello comments have an unsettling history of being overlooked, lost, or forgotten. So I tend to err on the side of sending suggestions to GitHub, which fills me with a lot greater confidence that my ideas will be looked at.

tl,dr: I leave it up to you: close and move to Trello if that's where it belongs. I will probably continue sending tickets like this to GitHub until somebody explicitly asks me to stop.

**Comment by SabreCat** [comment]
Re Stable: Hmm, I feel more like Mounts live in a Stable than pets. What's a good name for a place full of baby animals? Petting zoo? (joking.) If we implement hatching delays, it could be the Hatchery ^.^

**Comment by wc8** [comment]
@SabreCat a lot of your suggestions tend to be addressing potential user issues, for example, clarity. 
The key reason for moving to Trello is so feature requests don’t bury user issues. So I think you’re fine posting them here, and I’ll move them to Trello if it seems appropriate. 
I like Hatchery. :hatching_chick: 
BTW, would this be something that you can tackle?

**Comment by lefnire** [comment]
Just remember that quest scrolls will go here too, since they're gem
purchaseable. Same concern re: fortify. Basically, the left most tab is the
"can find or buy" tab

**Comment by SabreCat** [comment]
@wc8: It's a little beyond my current skills, but I can try to train myself up to it. I'm going to be pushing my coder comfort zone a lot in the next week or so, we'll see how far I get!

@lefnire: Good point. Will you be able to sell quest scrolls? I feel like we're going to want a Quests or Quest Journal type tab somewhere, so would it be out of the question to launch your quests from a different place than where you buy the scroll?

**Comment by wc8** [comment]
@SabreCat how about **_Discoveries**_?
You might discover the object in your Habitica journey or at the Market.

**Comment by lefnire** [comment]
Yes, can sell quest scrolls - because you may find a quest the party's already completed, and they're gunning for the next one

**Comment by breadstrings** [comment]
I like SabreCat's idea of the Stable for pets and mounts.

How about we make Equipment and Stable main headings beside the inventory. And under inventory we have what we have now for "drops".

**Comment by deilann** [comment]
These pages have been renamed, so I'm gonna close it.
