### ISSUE TITLE
Lost items

### ISSUE THREAD

**Issue by Asbra** [HabitRPG/habitica#2037]
Lost a Scimitar and a Black Leather Hood. It is what I bought last night (~12 hours ago)
The Scimitar is still showing on my characters paperdoll, but not in Inventory.

My username is Recons

**Comment by lefnire** [comment]
actually, looking at https://github.com/HabitRPG/habitrpg/issues/2025 this should be the same issue. the message is set as "Bought ___", and that was still flagged as a 400 automatically, meaning it never went through to the server. This should be fixed now via https://github.com/HabitRPG/habitrpg-shared/commit/c2a27370a129dcf592e56549369c7ae81ace644f (you'll have to buy back the gear though, go to Settings > Fix Character Values, get some gold, buy back)

**Comment by Asbra** [comment]
Thank you for your reply
