### ISSUE TITLE
Early Contributor Armor

### ISSUE THREAD

**Issue by fuzzytrees** [HabitRPG/habitica#2039]
I have the contributor armor + helmet available to buy even though I haven't bought all the normal levels of armor and helmets (in either my old warrior class or my new mage class). Dunno if this is a deliberate change or an error, but I just wanted to make sure you were aware. I think I started seeing the contributor armor at some point after the class release, not at the same time as the class release.

See: 
![armor_error](https://f.cloud.github.com/assets/4355305/1770751/0c948e52-679b-11e3-887e-f928a3b8bff7.png)

**Comment by SabreCat** [comment]
This is a deliberate change. Backer and contributor gear is now purchasable on a separate track from your class's equipment progression. (The "Armory" features of the revised Inventory made this possible!)

**Comment by fuzzytrees** [comment]
Ok, cool.
