### ISSUE TITLE
Uncheking dailies with no money.

### ISSUE THREAD

**Issue by drBradley** [HabitRPG/habitica#2046]
So, today i just start thinking about what happens if i have no gold and uncheked a daily task that i accidentialy hit. To my suprise it is actually possible. In normal situation dailies are taking back expierience and gold, but when you have not even a penny, it simply won't leave you with debt - just clear your money to 0. 
In result it is possible to checked all the dailies, get yourself an item, and then unchecked all the dailies without a need to return the purchased item.

It is not so important, but i think it should be fixed.

**Comment by wc8** [comment]
Is this related to #964 and similar issues?

**Comment by drBradley** [comment]
Yes, they all are related.

**Comment by wc8** [comment]
OK, let’s follow up on #964 then.
