### ISSUE TITLE
Lost my Cotton Candy Blue wolf

### ISSUE THREAD

**Issue by scooterlou** [HabitRPG/habitica#2047]
Yesterday I ended up with a wolf egg as a drop, and a cotton candy blue potion as well, so I decided to make myself a cotton candy blue wolf!  He was adorable, sticking his tongue out and looking all cute. Imagine my dismay when I logged in this morning and he was gone!  I still had my other two pets (a desert wolf and a shadow bear), but the blue wolf seems to have disappeared completely.  (And I was getting attached to the little guy!)  Is it possible to bring him back?

User ID:  30d61a8d-19aa-4833-8676-83508f4b6350
Browser: Chrome Version 31.0.1650.63 m

**Comment by lefnire** [comment]
added gems so you can buy back potion & egg. re-open if happens again
