### ISSUE TITLE
Streak Bonus appears not to be added?

### ISSUE THREAD

**Issue by storian** [HabitRPG/habitica#2048]
Hi, I posted about this same issue prior to the major upgrade.. it appears to still be around.

When I check off a Daily, I see an alert for accomplishing the task, and also an alert for the streak bonus.  From what I can tell the streak bonus is not being added to the gold/silver.  When I last posted this, I asked if the streak bonus was implicitly part of the amount in the main "accomplished" amount; while I was informed that the streak bonus is actually separate, I thought I'd just mention it again; maybe the system thinks it's included or something.

**Comment by PaulRosenfield** [comment]
I have also noticed this behavior. Running Habitrpg in Chrome.

**Comment by lefnire** [comment]
Can you test something. Click a daily with streak, note your before GP +
streak bonus. Refresh the page, see if the correct GP is in your account.
Aka, is the bug only in the browser but it goes through properly on the
server? Or is it both

**Comment by storian** [comment]
Interesting.  Lefnire, I ran the test.  Main bonus was 2g 1s, streak bonus was 18s.  Both pre- and post-refresh, the amount added to my g/s was 2g _2s_ -- not 1s.  So it is adding the main bonus, and 1s.  But THEN, after the refresh, I saw an alert box for -17 -- I didn't actually see the "s", but clearly that must have been it, as the amount I received for the task was 17 less than the alerts showed.  Most curious.

**Comment by storian** [comment]
FYI I am also running in Chrome.

**Comment by PaulRosenfield** [comment]
I had 40g 90s, then checked a task and gained 2g 33s for the task itself plus a 19s streak bonus. Both before and after refresh, the new total was 43g 23s, which includes the normal gain but excludes the streak bonus.

**Comment by Evxie** [comment]
I also have this problem.

**Comment by SabreCat** [comment]
Confirmed here too with a quick test.

Started with 15 gold 63 silver.
Checked off a Daily that awarded this alert:

![screenclip](https://f.cloud.github.com/assets/4501321/1814569/6cf846fe-6ef7-11e3-98ca-c02057d7f54a.png)

Expected output would be 17 Gold 43 Silver. But in fact I ended up with 17 Gold 37 Silver--the normal Gold award, no streak bonus added in.

**Comment by SabreCat** [comment]
I sometimes get this in the console, maybe related?

TypeError: Cannot read property 'streakBonus' of undefined
    at Object.fn (http://localhost:3000/js/controllers/notificationCtrl.js:25:33)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:11762:29)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:12013:24)
    at HTMLAnchorElement.<anonymous> (http://localhost:3000/bower_components/angular/angular.js:17823:21)
    at HTMLAnchorElement.jQuery.event.dispatch (http://localhost:3000/bower_components/jquery/jquery.js:4676:9)
    at HTMLAnchorElement.elemData.handle (http://localhost:3000/bower_components/jquery/jquery.js:4360:28) angular.js:9384

**Comment by SabreCat** [comment]
@lefnire Given the current Winter event, with lots of limited-time-only Gold purchasables and Fix Values for Gold disabled, we might wanna bump the priority on this.

**Comment by SabreCat** [comment]
Oh! After a pass through with some debug breakpoints, I see what's going on. The streak bonus is added correctly, but the notification makes it look like it isn't.

In my screenshot above, the "+1 gold 74 silver" _includes_ the streak bonus. The "+6 silver Streak Bonus!" makes it look like I should be getting 6 silver more on top of that, but in fact that's already been factored in.

I think the easiest way to deal with this is to have the GP alert notification subtract off the streak bonus, so we keep the present look and feel while making everything add up correctly (except maybe for rounding errors). I'll give that a try and push a fix if it looks like it's acting right.

**Comment by storian** [comment]
When I originally noticed this a long time ago, I asked if that was
happening, and lefnire seemed to think the streak wasn't included in the
top notification.  But debugs break points clearly trump memory. :)

In case anyone is interested in my opinion:

I agree with the approach of removing the streak amount from that notice.

I would also suggest that rounding errors be eliminated if possible by
rounding up always.  I have noticed more than once that the amount received
was off by 1s; I assume that's a rounding error.  I realize that my
suggestion is probably far easier recommended than done, but that's my
recommendation.

**Comment by SabreCat** [comment]
@storian That's actually a fair suggestion re: the rounding errors. Can you write it up on its own ticket?

**Comment by storian** [comment]
Sure thing.

**Comment by storian** [comment]
@SabreCat: done.
