### ISSUE TITLE
Bad skill behaviour

### ISSUE THREAD

**Issue by Johangsl** [HabitRPG/habitica#2050]
As I Rogue I used pickpocket on a task, by clicking on it, but not on the checkbox, the skill gave me money but the task did not complete this way. Is this an expected behaviour or is it supposed to only  cast a skill on a daily and complete it?

I was able to complete it afterwards.

**Comment by wc8** [comment]
I believe it is currently the expected behavior. You’re pickpocketing the task. ;-)

**Comment by SabreCat** [comment]
There was some discussion about having the bonus only kick in if you complete the task (which is weird RPG-wise but makes a lot of sense for motivation), but I'm not sure where that's at right now.
