### ISSUE TITLE
Mobile header character

### ISSUE THREAD

**Issue by smartao** [HabitRPG/habitica#2051]
After the upgrade I noticed that the character falls along with the screen, I found cool interesting, but then I realized that there are two drawbacks.
1 - Who plays on a small screen have to spend more time to get rolling on the specific task.
2 - The character always shows it's bad when you go to use the HabitRPG at work, my boss will not find it an interesting, even explaining all the benefits...

You could create a checkbox in options for each user can choose this, imagine that there are many people who liked the new feature and others like me who find any disadvantages.

Tks

**Comment by lefnire** [comment]
Checkboxes already there, go to Options > Settings

**Comment by smartao** [comment]
Thank you! sorry have not seen this before.

**Comment by lefnire** [comment]
np! (sorry for terse response, was on mobile)
