### ISSUE TITLE
@ completion shouldn't grab spellcasting notifications

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2052]
With the recent addition of party chat notifications for abilities used, party members' names get added to the chat with angle brackets. This is great to clarify that it's a notification and the player didn't actually type that in! Unfortunately, it then shows up in "At" autocompletion:

![screenclip](https://f.cloud.github.com/assets/4501321/1779438/dc95badc-6849-11e3-87df-2b80f29906b7.png)

We should filter out these casting tags from the list.

**Comment by lefnire** [comment]
Don't worry, I have a system in place for that. Twill be fixed in a few days

**Comment by lefnire** [comment]
fix coming with the bosses feature
