### ISSUE TITLE
Guide: Level Up Points, Attribute Points, Statistic Points?

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2053]
http://habitrpg.wikia.com/wiki/Point

> When a HabitRPG player gains a level, she receives a point which she can allocate toward one of the four statistics that help define her character within the game, after unlocking the class system at level 5.

What’s the official name for this point? We’re trying to establish it for the documentation. Already there are several kinds of points: experience, health, gold, mana. This fifth one needs a name to help avoid user confusion.

**Comment by lefnire** [comment]
Sabe DTB wc8, y'all pick

**Comment by JennaMalkin** [comment]
I'd prefer to call the stats 'Attributes' and the points 'Attribute Points' (AP).  I think this would help people who aren't as familiar with RPGs remember what they are.

**Comment by SabreCat** [comment]
@JennaMalkin: I agree with those suggestions. I've been gently pushing back against the use of "stats" for these, because we have a whole other level of "statistics" in this game (a user's history of task scoring and so forth)!

**Comment by wc8** [comment]
It’s official then. @JennaMalkin go with 

> the stats 'Attributes' and the points 'Attribute Points' (AP)

**Comment by wc8** [comment]
@SabreCat should we add attribute to the notification then?

> When a HabitRPG player gains a level, she receives an attribute point which she can allocate toward one of the four statistics that help define her character within the game, after unlocking the class system at level 5.

**Comment by JennaMalkin** [comment]
Maybe we should wait until they've been changed in-game - at the moment, Justin's tour still says 'stats' and 'points'.

**Comment by SabreCat** [comment]
I'd say it's pretty safe to update the wiki with that term, because it's innately descriptive. The site can catch up to the documentation on this one.

**Comment by wc8** [comment]
We can also add deprecated term entries to the glossary.

**Comment by DanielTheBard** [comment]
It's been decided, but I like attributes, as well aha.

**Comment by wc8** [comment]
Seems like this is done, so closing—reopen if I missed something.
