### ISSUE TITLE
XP reward calculations broken

### ISSUE THREAD

**Issue by TheOfficePicnic** [HabitRPG/habitica#2054]
A change was made today which resulted in me only receiving about 2 XP for dailies that used to give me 5.5 XP just yesterday (even after the class change addition).

I saw Tyler made a post about some tuning/balance adjustments, but I suspect there may have been an overcorrection or bug included in that code release. I doubt it was intentional to have any class, let alone an XP-centric level 30 Wizard class (me), only receiving 2 XP for tasks.

Username is: TheOfficePicnic

**Comment by ghost** [comment]
Yup, me too. Dailies, Tasks (orange task netted 3XP), Habits. Almost all are 2XP. I'm a rogue lvl 37.

Username is: Anysia

**Comment by wc8** [comment]
It might help developers to know your INT levels as rogue @Anysia  and wizard @TheOfficePicnic. 
Are either of you using auto-allocate?

I’m getting 3 XP per task as a level 26 Wizard with 12 INT. 
I ran a reroll, and an ordinary habit gains me 4 XP with 26 INT.

**Comment by wc8** [comment]
Another thought is that maybe XP leveling has been slowed down in order to compensate for Mana options? 
Oddly, I like the slower leveling—so long as I survival doesn’t prove too difficult.

**Comment by DSollick** [comment]
Level 4 checking in here, getting a whopping 1 XP per task when I was getting 7-8.  A bit of a hard hit starting out since it's not even a possibility for me to allocate stats.

**Comment by TheOfficePicnic** [comment]
@wc8 My wizard has 34.5 INT, and I am not using auto-allocate. It may be useful to know that all of my habits/dailies/to-dos are set to "easy," as that has always been the default. Additionally, I get a lot more gold per task than I used to, while simultaneously getting a lot less XP. That seems a little more in line with the intent of the rouge class, no?

**Comment by ghost** [comment]
I had auto-allocate checked and, not realizing that didn't affect the 36 pts I already had, had 0 for everything except PER. Then I allocated everything evenly (so 9,9,10,9). As far as I can tell it made absolutely no difference. I don't think I'm getting a lot more gold than I used to but I never paid attention to that so I can't say for sure.

**Comment by TheOfficePicnic** [comment]
@wc8 The difficulty curve of the game is ultimately a decision for the devs, but I do think striking the right balance between risk and reward as you try to level your character is absolutely crucial to this game's longevity. To paraphrase what I said in the tavern:

There is perhaps no more crucial balance issue for this game than the relationship between XP gained and XP needed to level up. It appears as if the former has been nerfed, and the latter has remained the same. I would argue that the balance was nearly perfect before, and if the mage/wizard class is meant to excel in XP gain through INT, then their numbers should be boosted (with trade-offs in other areas) above the previous norm while the other classes remain as they were before. 

The current balance will lead to a lot of discouragement; particularly among mid to high level players whose XP requirements per level are quite large in relation to their per-task rewards. For example, I have to complete 330 tasks at 2XP each to reach level 31. Three hundred and thirty. At a rate of roughly 10 tasks per day (what I seem to be averaging right now) it will take me a full month to reach the next level. And then another month for the next level, with some extra added on top each time. 

We're talking about a rate of progression that could mean literally taking a player five years or more to reach level 100. If you die and level down? There goes a month or more of your effort.

That's just not a system that's going to keep people hooked. And ultimately, this game should be about making the act of improving yourself addictive.

Just my two cents, in case this new balance is an intended system rather than an error.

**Comment by shockbros** [comment]
This happened to me yesterday. I was level 4, and in the morning, I completed a red daily and it gave me about 7-8 exp as expected, leaving me 8 exp away from level 5. Doing a habit, and completing a yellow daily by the afternoon, however, only gave me 1 exp each. I thought it was an error due to using one of the mobile apps so I tried to do it on the web to see if that changed anything but even creating a new daily to 'fix' the exp I was missing, that still only gave me 1 exp and so far I've only been getting 1-2 exp when I was getting much more before.

**Comment by wc8** [comment]
@TheOfficePicnic and I thought my 570 level up was going to be hard with 30+ dailies… 
@shockbros an upgrade hit the system that was supposed to address the excessive gold issue, but may have had unintended consequences for XP.

**Comment by Evxie** [comment]
I'm a level 35 Wizard with a total (allocated/gear/level) of 59. I get 3exp for yellow tasks and 2 for green/blue ones (on easy). I used to get something like 6 exp for the bluest of blue tasks and 10 for yellow ones (on easy). And I need 800 exp to get to the next level. That is ridicolous...

**Comment by lefnire** [comment]
Let's follow up on [Trello](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system), since that's currently where all the numbers conversation is happening
