### ISSUE TITLE
Experience gain reduced shortly after

### ISSUE THREAD

**Issue by twilker** [HabitRPG/habitica#2056]
For at least the past two days I have experienced that when ever I score XP through dailies, shortly afterward my XP gain is reduced to zero. Two examples what I meant:
1. Yesterday I checked several dailies at once. I gained all the XP for it. But only seconds afterward I got the message "-35 XP". I do not know exactly how much I gained but it was not much more.
2. Today I checked one daily to test it. I gained exactly 2 XP and one second later it was reduced by one XP.
It seems that with my account it is reproducable. My ID is 44f53eef-29a9-4a39-af09-818227ae6317.

**Comment by jeremyfourna** [comment]
Hello, I got the same problem. Before the change in Wizards I gained 12XP per task and after it was 8 so OK but yesterday and today I only gain 2XP per task !!!

**Comment by twilker** [comment]
That is not my problem. My problem is that I get the correct amount of XP but it is reduced afterward.

**Comment by wc8** [comment]
@dexterneo your issue is #2054

**Comment by Aubec** [comment]
Looks like the XP is much higher now.  I'm getting 40 xp for new tasks (75.5 Int).

**Comment by twilker** [comment]
I have not seen this effect for the last two days, maybe it was solved with #2054.
