### ISSUE TITLE
Mana dopped to -9 (negative 9)

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2057]
Here's how the whole thing went down:

I'm a rogue. Today my mana recharged to 21. I decided to use the pickpocketing spell twice. First, I clicked the spell and then clicked a To-do, but I did not click the completion tick instantly - I first cast the spell on the To-do's general area, and after that I clicked the tick to complete it. Mana dropped to 11, I got two GP drops - one from spell, one from completing the task.

Here's the weird part: I used the spell again, this time on a daily and this time I cast the spell directly on the tick area to cast the spell and complete the daily in one click (still wasn't sure which method was proper). This gave me a lot of GP and for some reason drained my mana to -9. Now the mana bar looks odd - it's all blue (as if it's full) and has a negative number on it.

**Comment by Pandoro** [comment]
This is an interesting observation! So there is a difference between casting on something and casting it while completing it. This might also explain why there are problems around this? @lefnire Good hunch for debugging maybe?

**Comment by Evxie** [comment]
I've used both the spells I have (as a Wizard) on dailies. Every single time it's used double the mana and given me negative exp.

**Comment by wc8** [comment]
This looks related to #2012

**Comment by lefnire** [comment]
#2012 indeed, let's follow there
