### ISSUE TITLE
Deleting Habits/Dailies/To-Dos appears to delete two at a time

### ISSUE THREAD

**Issue by tstowe** [HabitRPG/habitica#2058]
Whenever I delete a task from any category, it will also appear to delete the next task underneath of it.  When I refresh, the additional task that was deleted returns, but it's still confusing to see 2 tasks disappear.  Using google chrome, my user ID is 060c8699-9deb-4f0e-9480-636fa21bcb00

**Comment by etatuev** [comment]
I have this one, too. My user id -- e47cd8f1-51dd-4679-91b7-94cbc56eedcd.
Chrome 31.0.1650.63
