### ISSUE TITLE
Recently created character appearing with sword on party avatar

### ISSUE THREAD

**Issue by guifes** [HabitRPG/habitica#2059]
My friend and I started playing today, but his avatar, although not having a sword equipped has a sword in his hands in the party avatar display in my home screen.

**Comment by lefnire** [comment]
If you're judging what he has equipped by his gear listing in the modal dialog, that gear listing is incorrect - see https://github.com/HabitRPG/habitrpg/issues/2010 . If he actually told you he's wearing something other than the sword, he might be [using a costume](https://trello.com/c/iY6A7nlX/336-costumes-armory-v2)

**Comment by guifes** [comment]
I was indeed judging by the gear listing in the modal dialog! Sorry for that!

**Comment by lefnire** [comment]
Yeah, hot issue we'll fix soon. Let's follow over there

**Comment by guifes** [comment]
There's something I did not say. My character did not start with a sword by default, like my friends did.
