### ISSUE TITLE
[Suggestion] A little fix on the balloon with text and notes?

### ISSUE THREAD

**Issue by murilomgh** [HabitRPG/habitica#206]
First, thanks for this great project!

When you hover over the details of a Habit, the baloon with text and notes appears at the right side of the icon. For Rewards, it appears on the left.
An idea is set the balloon to appear in the left for all the tasks. Please see the images below (when I'm using a narrow browser window):

![Habits_hover](https://f.cloud.github.com/assets/1236297/96136/fae2cdf0-6691-11e2-8c5c-0da241f05871.png)
![Rewards_hover](https://f.cloud.github.com/assets/1236297/96137/000d4666-6692-11e2-856c-02ffb9a3d07b.png)

Sorry for spelling errors...

**Comment by horusofoz** [comment]
@lefnire Has this suggestion been implemented? All my note balloons appear on the left.

**Comment by StanLindsey** [comment]
Yeah Tyler merged code a while back. Thanks for spotting this is open!
