### ISSUE TITLE
got a drop from checking the automatic stat allocation box

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2060]
I have a bunch of unallocated stat points. I checked "automatic allocation" to see what would happen. Nothing appeared to change, so I unchecked it. Then I checked it again, and got a desert hatching potion! (to be precise, I got a desert hatching potion drop message. I have so many of the things that I can't tell whether one was actually added).

**Comment by ghost** [comment]
Hmm. I tried this and got a message that I lost 6 HP .. on refresh it doesn't appeared to have actually affected my HP.

**Comment by lefnire** [comment]
The way habit works is it will update anything form the server for every client action you perform. If the API updated your user (mobile app, chrome extension, or even using Habit in another browser), it will notify _this_ browser of any updates when you perform your next action, no matter what that action is.
