### ISSUE TITLE
'Intimidating Gaze' auto-message to party doesn't feel friendly!

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2061]
![picture 146](https://f.cloud.github.com/assets/5298344/1787051/1788eadc-68ff-11e3-9d3a-87ac36070fae.png)

I cast my defense buff on my party to help them stay healthy, but when I looked at the automessage in my guild, because of the name of the spell, it feels like I'm staring at my party - 'J'accuse!' - rather than we are staring down our foes as comrades-in-arms.  Could this be reworked in green, or renamed, or something?  (And perhaps save red for debuff spells cast by bosses?)

**Comment by SabreCat** [comment]
Earthquake has the same problem, it sounds like I'm rocking the ground under my allies' feet. It could be as simple as saying "for the party" instead of "on the party" for these sorts of thing.
