### ISSUE TITLE
Issue using HabitRPG website w/ Android app

### ISSUE THREAD

**Issue by Ohaeri** [HabitRPG/habitica#2062]
Same issue as https://github.com/HabitRPG/habitrpg/issues/635 (which is closed and I don't think I can reopen?)

So you don't have to go back and read, I installed the Android HabitRPG app today. Came home, completed my tasks, and made it to level six. Only, shortly thereafter I got kicked back to level five.

I'm going to uninstall the android app since I'm not keen on it anyway, but I thought I should let you know that this is still an issue, at least from what I've experienced . . . 

Running Chrome 31.0.1650.63 m
Running HabitRPG for Android v. 0.0.13

I will let you know if uninstalling the Android app does not fix my problem. (EDIT: It does indeed seem to be fixed.)

No errors or warnings are being thrown by the console on the HabitRPG website.

**Comment by lefnire** [comment]
This sounds like https://github.com/HabitRPG/habitrpg/issues/2157 . You need mobile apps versions 0.0.15. iOS is still pending review (they take forever...). Check that ticket, if it sounds like the same issue close this, if not hit me up
