### ISSUE TITLE
Earthquake not buffing properly

### ISSUE THREAD

**Issue by Lilymorningstar** [HabitRPG/habitica#2064]
Hi,

I attempted to use Earthquake this morning, hit the skill, saw my MP drop appropriately, went to my skill sheet to check the buff, and... no buff listed.  Checked my party members - no buffs.  Refreshed - still no buff.  Verified through completing a common task that it still yielded the same XP as it normally did.  Bummer!  Thanks for looking!

**Comment by JennaMalkin** [comment]
Have you tried waiting ~15 minutes or so?  That was the length of time it took my buff to show up today.

**Comment by SabreCat** [comment]
I didn't have any luck casting Earthquake either.

**Comment by lefnire** [comment]
pushing fix. I can't replicate on a buff-less character, so the issue I think was that some buffs (inc. earthquake) weren't stacking, they were replacing.

Couple other notes: You wont' see the party "___ cast ___" message until chat refresh, you can't yet view party attributes accurately (i'm going to temporarily disable that form modals until I can fix it), and I _believe_ you won't see if a party member is buffed until refresh... maybe...

**Comment by Lilymorningstar** [comment]
@JennaMalkin Yes, it was well over 8 hours since I was able to report in here due to a jam-packed day, and still no buff from Earthquake.

Thanks for verifying you also had trouble, @SabreCat!  It's good to know I wasn't going insane ;)

Also, thank you @lefnire for pushing for fix - truly appreciated!

**Comment by SabreCat** [comment]
Just tried it again this morning. Waste of MP! The buff icon shows on my avatar until refresh, then nothing.

In a local copy of `src\models\user.js` (from when I branched for my Attributes work) it looked like the `buffs` attribute had `def` listed instead of `int`, but I'm not seeing that in the current branch, nor can I tell when it was fixed. @lefnire, is that change live? Does it need a migration to straighten out?

**Comment by ghost** [comment]
Earthquake not buffing (in Firefox; OS Windows 8; API UUID: 88357773-a371-41f5-9ee2-5c4def77a810). All others spells work. MP resets when I reload the page. When I cast Earthquake, I receive the following error:
"Error Cast to number failed for value "NaN" at path "_v"" (see Chrome console for more details).

The associated JavaScript error:
Object { data: Object, status: 500, headers: Vc/<(), config: Object, statusText: "Internal Server Error" } app-99623818.js:22
window.habitrpg</</<.responseError() app-99623818.js:22
Kd/d/k.promise.then/l() app-99623818.js:6
Kd/d/k.promise.then/l() app-99623818.js:6
Kd/d/k.promise.then/l() app-99623818.js:6
Kd/g/<.then/<() app-99623818.js:6
Md/this.$get</i.prototype.$eval() app-99623818.js:7
Md/this.$get</i.prototype.$digest() app-99623818.js:7
Md/this.$get</i.prototype.$apply() app-99623818.js:7
o() app-99623818.js:6
x() app-99623818.js:6
_c/</s.onreadystatechange() app-99623818.js:6

**Comment by lemoness** [comment]
So, that's actually a new bug that we've been encountering: https://github.com/HabitRPG/habitrpg/issues/4067 You can follow that thread for the details as we work on it. Sorry for the frustration!
