### ISSUE TITLE
Tons of gold

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#2065]
This is a weird complaint, but I'm getting tons of gold for stuff that would normally have given me under 1G.  I thought it was because I was a Rogue so I switched to Cleric and lowered my perception by a lot.  I still got 8G for a red task, whereas it used to be 2.5 or so.  
![image](https://f.cloud.github.com/assets/3587570/1788946/1cec01a8-6945-11e3-8ce4-8100765e2d4f.png)

**Comment by cleave29** [comment]
Oh, and my new stats are about 16 each.  (65 total if that helps.)

**Comment by SabreCat** [comment]
Is it every click, or only sometimes? See #2029.

**Comment by cleave29** [comment]
Hmm, I'm pretty sure it's every click.  I don't feel like I'm critting every time.  Lemme experiment with that.

**Comment by Eusebius** [comment]
I'm a bit surprised with that too. Before last update, I was always below 100G, and struggling not to die every two day. Now suddenly, I'm over 300G just by waking up in the morning, and casting "pickpocket" can earn me several hundreds with a single task... I have absolutely no risk of dying anymore, the balance of the game has drastically changed (maybe we just need to adapt to this change and rethink the cost of our rewards, though).

**Comment by cleave29** [comment]
Yep, I just clicked a blue (4-day streak) and got about three gold.  It's every click.
![image](https://f.cloud.github.com/assets/3587570/1795583/2d4ec5c0-6a22-11e3-8cbd-66abf7a88e06.png)

**Comment by lefnire** [comment]
Let's follow up on [Trello](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system), since that's currently where all the numbers conversation is happening
