### ISSUE TITLE
Opted-Out Gear Still Gives STR?

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2066]
The 'opted-out' gear still says it has STR, etc. - does an opted-out Plate Helmet, which used to reduce HP loss by x%, still reduce HP loss, or will it only increase STR?

**Comment by JennaMalkin** [comment]
![picture 147](https://f.cloud.github.com/assets/5298344/1790444/3b1a6cc4-6976-11e3-8994-e9dbbed2b3cc.png)
![picture 148](https://f.cloud.github.com/assets/5298344/1790452/78e1cbba-6976-11e3-856b-d18f8a3a250c.png)
![picture 149](https://f.cloud.github.com/assets/5298344/1790498/90116966-6977-11e3-98b8-633643b29007.png)

**Comment by SabreCat** [comment]
It still increases STR, which is task fade and critical hits. I wonder how common this sentiment is...

**Comment by JennaMalkin** [comment]
Colin Bowen @Malkin I really think HabitRPG has 'progressed' beyond what a non-RPG-expert can understand. You seem to have cut out a large slice of potential users. IMO, a HabitRPG-Lite version using the old code would be good for n00bs, with the option to transfer the user data to the 'Pro' (current) version should they wish. Twice the servers, and twice the support though? I appreciate it might not be an option.  

LordGrowl @Colin Bowen, I would actually agree with what you said. On the other hand, I see plenty of potential for them to improve the layout of the site to make the class system more foolproof so that even non-RPG players can pick things up quickly and easily. Stretching the progression out would be a good start (e.g. level 5 to unlock classes, level 6 to unlock spells, level 7 to unlock costumes, etc.). If everything's spoon fed gradually (level by level), new users won't get the sudden dump and overload of information the happens with the current system where everything unlocks at level 5. :crown::smiling_imp:

**Comment by JennaMalkin** [comment]
How many people have opted-out of the class system?  I've been finding my strength ridiculously boosted, but I'll have to wait until some of my habits warm up before I can test the new numbers properly. I still have a lot of reds, but they're only to-dos, so there's no point smashing them with my mighty STR, as once they're done, they're done.

**Comment by Alys** [comment]
I'm closing this. I think we're pretty much used to the new STR, CON, etc system now.
