### ISSUE TITLE
Limited usefulness of high MP

### ISSUE THREAD

**Issue by ParisiT** [HabitRPG/habitica#2069]
Most spells/abilities cost anywhere from 10-40 MP. Since MP only regens daily, and at a rate of 10 MP for everyone, this limits the usefulness of having a stat that boosts MP, as intelligence does now. This, in turn, makes things which boost Intelligence less-useful than similar items going to other classes.

It seems it would be better to detach MP from INT and just give characters a hard number, as has been done for HP, and to have Int do something else, or to make the regeneration of MP be tied to INT, or both. This would keep INT in line with the usefulness of other stats. Alternatively, if there were other ways to regen MP, either through an item or by leveling or some other mechanic, it would be more useful.

Currently, the only way to regen MP is a spell that Wizards get, but Wizards are the class that gets the most INT-boosting items, so they don't reap the full benefits of this.

Case in point: I have over 70 MP now, without any INT-related gear. It is unlikely that I will ever _need_ 70 MP, or that I would wait until I had it, seeing as there's no real reason for me to hold off on spellcasting. So I'm better off giving my Wizard a Gold Sword, Shield, and Armor to increase my Str and Con, than buying a Staff and Robes which help my INT, since half of the bonus it gives me will never come up.

**Comment by sleepykit** [comment]
I think the whole MP thing would benefit from refills at level ups (just like with health) and Mana potions (just like we have health potions). _shrug_ That's been bugging me ever since Mana first showed up.

**Comment by lefnire** [comment]
These are good ideas all around. Don't worry, things aren't set in stone,
we're still figuring stats/numbers/MP-handling out, so I'll start looking
at these bits

**Comment by SabreCat** [comment]
I had this in mind too. My suggestion would be to have the daily replenishment be a percentage of total MP (somewhere in the 10-20% range?) rather than a flat value.

**Comment by Draayder** [comment]
Maybe have level ups give either a percentage or somewhat large flat amount of mana on top of the amount per day?

**Comment by lefnire** [comment]
let's follow this convo on [Trello](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system). MP regen has been implemented (INT bonus on cron, full-regen on level-up); but most of the dialog is happening on Trello, so chime in there if you're not digging that strategy / wanna see the math

**Comment by lefnire** [comment]
Update (again, follow Trello for the latest) - 10mp on cron, 1 To-Do regens 1MP (no INT-based regen). Trying to give our incentive-less To-Dos incentive.
