### ISSUE TITLE
[Feature] Customizable equips and skills

### ISSUE THREAD

**Issue by Yughurt** [HabitRPG/habitica#207]
Just read the skills suggestion and thought of additional customization that wouldn't apply to just skills.

In addition to adding different aspects of life: Work, family, health + exercise. (Easier management) by attaching different aspects with different equipment or skills; doing certain activities give different bonuses not restricted to GP. Make some things exclusive. eg: Completing daily exercise routine gives rise to a reward that only completing that daily exercise can unlock. Doing Work could reduce the "cost" of recreational activities (encourages work before play).

For equipment have name extentions and for skills, titles. I'll show examples of this put together.

Cool examples: Running -> lvl 1-4 -> boots become (after you buy the base eg. leather boots) boots of speed. lvl 5-7 -> boots of haste. Events such as marathons give qualities such as magical or "Hermes's" steel treads of lightning wind.

For skills: Avatar name + title. Lefnire - master worksman or something to that effect.

**Comment by StanLindsey** [comment]
So the idea is sort of along the lines of "charming" your weapons/equipment depending on what you do?

You could possibly sell these items on a marketplace once you have levelled them up as well? Thoughts?

**Comment by Pandoro** [comment]
I like the idea a lot, the problem I see here is how to realize it? How would you really know which task falls in which "class" of tasks? If it is user defined, you can simply put whatever task into your running boots, and achieve your awesome boots by brushing your teeth. Now I know this game builds on not cheating on yourself, but if you for example only make three different routes your boots can take, say, running, defence and miner boots (as in more exp, less damage and more gold) but I have no habits or dailies which fit into these categories, than I will soon feel left out and I would just assign something to them. 

So maybe the idea could be generalized to something less specific to certain tasks? This would also take away to need for possible machine learning algorithms which decide the difference between "run three km today" and "run three experiments today". 

Considering I guess you don't really get boni from the titles, there it wouldn't really matter if I fit into a certain category or not. But still it would be the question how to give which title to whom. Unless there are some generic dailies you can adopt from a list, or there are some generic titles which are obtained by your general behaviour in the game, I think it can be very hard to put someone into a category. Especially when people start writing in their own language.

**Comment by Yughurt** [comment]
I was thinking that you would be able to organize dailies based on different aspects of life. Health/Exercise(armour/boots), Work(sword), as opposed to actually different tasks. The running was more of an example of something within this aspect. There would still be some issues I agree... You'd have to make custom tasks (time based: distance based, etc) rather than algorithm setting... just maybe something

**Comment by wc8** [comment]
I had thought about suggesting a flexible association/relationship between habits/tasks/skill-building and rewards with similar tags. It might be complicated though. 
P.S. Does this relate to #59 insofar as it involves titles?

**Comment by horusofoz** [comment]
Hey @Yughurt.

Are you able to elaborate on your idea so we can transfer it to [Trello](https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6)?

Alternatively, would you prefer us to close the ticket as request withdrawn?

**Comment by Yughurt** [comment]
Sorry, I've been overseas but I will elaborate. (I found a solution)

So the idea is to have different sort of rewards that are not gold related. As I've suggested having categorized todo's you can spend "favours from the god of health" or work, etc, which gives levels of blessings to your choice of armour or whatever you want. You'd need to have customizable amount of rewards to be attached. Alternatively you could make it a luck based thing. The gods look well on you and decide to bless your helmet... etc.

**Comment by horusofoz** [comment]
@Yughurt We won't be able to introduce your feature request at this time. However you may be interested in the [Real-Skill as Item Type](https://trello.com/c/UTWW66Uu) request currently on Trello.

**Comment by Pandoro** [comment]
I feel a bit like the idea with the gods would diverge a little from the general current playing style. :x Furthermore it will be a pain in the ass to draw all the fancy versions of all the items if that was intended.

However, I do like the idea of customizable items. It might be a great monetization. You could buy an enchant and add it to your item. Think of something like a "+1% exp" rune. But I don't think this works with the current system where you loose your stuff when you die and where you buy a new weapon every few days and the old one disappears. @Yughurt what do you think of this interpretation of your idea? 
@horusofoz @wc8 what do you think about this?
@lefnire @SlappyBag How do you feel about this monetization idea? I think it should be doable regarding coding effort once the token store is in place, but it would of course mean quite some changes to the item system.

**Comment by horusofoz** [comment]
With the current system I don't think it would work. Maybe in 6-12 months
it may be worth revisiting.

But again as it stands I don't think it passes a basic cost (coding,
maintaining, story building, supporting) vs benefit (cool factor, story
depth, monetary gain) analysis.

_Horusofoz_
*
*
"Live to learn. Learn to live." J.W.S.
