### ISSUE TITLE
Casting Earthquake did not increase my xp

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2070]
Before casting Earthquake, got 26xp from a habit; after casting Earthquake, next click of habit was 22xp. If it's only supposed to raise party members' xp and not casters', that needs to be clearer in the tooltip (and would be very unfortunate). According to the simulation, it looked like it was supposed to increase int, but my stats still show int from buffs as 0.

**Comment by lefnire** [comment]
Definitely a bug then, you should be getting an int buff. Will look into

**Comment by lefnire** [comment]
This should be fixed now, keep an eye out and if it happens again re-open

**Comment by wc8** [comment]
#2064 related
