### ISSUE TITLE
Need HP/Gold/XP style alert for MP

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2072]
We could cut back on a few questions about MP behavior, and give us some nice groundwork for mana potions or the like, if changes to Mana got an alert bubble similar to changes in Health, Experience, and Gold. Cast a spell, you see a "-35 Mana" alert along with the confirmation of what you just used. Tick over to a new day, you get a "+10 Mana" alert. Map the color to the blue of the mana bar.

**Comment by DanielTheBard** [comment]
Definitely. And it should note when you get +1 MP from doing a todo. (New implementation)

**Comment by SabreCat** [comment]
I think I've learned enough about Growl notifications from working on #2092 that I can tackle this. Assigning myself. I'll get to play with colors!
