### ISSUE TITLE
Spells prevent dailies from being checked

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#2074]
I hope it's not a dupe. When using a spell with a daily (I tried "backstab" and "pickpocket"), the daily does not get checked, so I can/must validate it again (without a spell).

**Comment by SabreCat** [comment]
This is due to the temporary fix on #2012. You can no longer click the checkbox simultaneously with the spell. Use the spell on the task by clicking the spell and then the task body (i.e., its name), then check off the Daily or To-Do normally.

**Comment by Eusebius** [comment]
OK, thanks.
