### ISSUE TITLE
Option to hide completed Dailys

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#208]
_Edited by wc8: [Vote for this here](https://trello.com/c/q7uM2Ymq)_
For users with many Dailys, it would be convenient to have an easily switched option to hide completed Dailys. 

Completed Dailys could be moved onto a Completed list similar to completed Todos.

The option would be located under Username>Settings>Hide Completed Dailys.

**Comment by StanLindsey** [comment]
Trello: https://trello.com/c/q7uM2Ymq

**Comment by horusofoz** [comment]
An option to hide dailys that are not set to repeat on that day would also be beneficial as keeps the user focussed on what needs to be done that day.

**Comment by wc8** [comment]
I definitely like hidden completed dailies. 
I would appreciate the _option_ setting for hiding repeated dailies, as there may be instances when something is not due but I can do it today.
I like the grey, but I wonder if they could be made even less obtrusive, without totally hiding them, by using a (slightly) smaller font, less padding in the box?

**Comment by wc8** [comment]
See also [Option: Hide Until Due](https://trello.com/c/G14jkPYd)
