### ISSUE TITLE
Current MP Went Over Max MP

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#2082]
Didn't happen to me, but user @Eipois reported in the tavern that their MP went up to 45/44. However, they couldn't use an ability that cost 45 MP.

**Comment by djuretic** [comment]
That reminds me of #1560 (in that case it the problem was with GP), maybe it's a rounding math problem.

**Comment by SabreCat** [comment]
It'd help to know what tripped this. Did it happen when they scored +1 MP off a To-Do? When a party member cast Ethereal Surge? When they leveled up? When they raised or lowered their INT score?

**Comment by DanielTheBard** [comment]
@SabreCat - I wish I knew aha. They just told me that and said something about not being good at English I think so they didn't want to open up an issue ticket.

**Comment by djuretic** [comment]
There are two issues here:
- How can the current MP exceed the Max MP?
- The "real" current MP is less than the current MP shown. Otherwise the user could have used the ability that cost 45 MP.

For the latter, I think that in the case of user Eipois: 44.5 <= current MP < 45
The code used to show the current MP (`number: 0` in https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/header.jade#L31) rounds the number to the nearest integer.

**Comment by SabreCat** [comment]
Hmm, it rounds, but how would we get a non-integer MP in the first place? Isn't it always raised and lowered by whole numbers?

...maybe in the formula for how much you get out of INT?

**Comment by djuretic** [comment]
The formula for max MP is (taken from https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L1195):

```
computed.maxMP = computed.int*2 + 30
```

So, to have a non-integer max MP you need to have a non-integer INT (except when the computed INT ends with .5), with buffs and gear bonus applied.

**Comment by deilann** [comment]
Did they have a Perfect Day yesterday? The Perfect Day buff for INT can leave you with more MP on a day than your actual regular amount. Then, when you lose the buff, you have more MP than your maximum.

**Comment by djuretic** [comment]
I think the site didn't have the Perfect Day feature then.

**Comment by deilann** [comment]
Yeah, sorry, I thought I was commenting on this ticket: https://github.com/HabitRPG/habitrpg/issues/2737

**Comment by Alys** [comment]
Can this be closed? I think the current behaviour regarding MP > max is appropriate. There are legitimate reasons to have more than max MP (e.g., you've just deequipped INT gear) and there are already some things in place that reduce MP to max (cron and ticking off a To-Do). See also the discussion here about why MP > max isn't all bad: https://github.com/HabitRPG/habitrpg/pull/3662

**Comment by lemoness** [comment]
I agree! Closing now; let me know if it should be reopened.
