### ISSUE TITLE
Weapons and armor disappearing after purchase

### ISSUE THREAD

**Issue by cinemafreak** [HabitRPG/habitica#2085]
Armor and/or weapons disappear and my previous armor and/or weapon return after purchasing the new. It's happened a bunch with my rogue. I don't mind having to rebuy things but the gold isn't coming back into my coffers.

**Comment by lefnire** [comment]
what's your UUID?

**Comment by cinemafreak** [comment]
9814cdf5-7be0-4d39-bd18-71b8d31620ed

Any help would be appreciated.

Thank you

Podcasting's Rich Sigfrit
Host/Producer
Requiem of the Outcast and Mister Adventure
Award Winning Podcast
http://www.outcastmultimedia.com
As seen in Podcasting for Dummies
6 time Dragon*Con Parsec Award Finalist

**Comment by mud-fighter** [comment]
I had the same problem, bought black leather armor and never received it, took my gold as well.  

UUID is 10e54769-cb4a-460a-a081-d69762fdece0

Thank you much.

**Comment by cinemafreak** [comment]
Aaaaaaaand this is the fourth time I've lost my  Penumbral Armor and/or my Penumbral Hood without my gold being returned.

**Comment by lefnire** [comment]
Will look into this soon as I can, I'm crazy swamped. I checked out your accounts, and the structure looks solid so I'm not sure what could be going wrong. If it happens again, keep an eye out for javascript errors in Chrome Console, or any alerts in the top right. In the mean time, use Options > Settings > Restore Character Values to give yourself the gold to buy back your items

**Comment by cinemafreak** [comment]
I'd really prefer to not Restore Character Values if it's at all possible.  No worries on being swamped, I know the feeling.  I just wanted to raise the red flag since it's happened again.  I'm going to wait to buy any gear until after the IOS push (since I use both the online version and the IOS app).

**Comment by cinemafreak** [comment]
I've lost about 400 gold buying things and loosing them.  It would seem it's only purchases down via the IOS app.

**Comment by jreatherford** [comment]
I have had the same problem with the Scimitar in the android app

**Comment by lefnire** [comment]
@cinemafreak has this issue always been with iOS then? You haven't experienced it with the website? If so, see https://github.com/HabitRPG/habitrpg/issues/2157 (additional info at https://github.com/HabitRPG/habitrpg/issues/2127#issuecomment-31227455)

@jreatherford which android mobile version are you? 0.0.15?

**Comment by lefnire** [comment]
I'm gonna close this as it sounds very much like the issue was using an older version of the mobile apps. Android 0.0.15 is out, and iOS 0.0.15 is currently being processed (god thy take forever...). If anyone experienced this issue _using the website_ primarily (or using 0.0.15 of the mobile apps), hit me up and I'll re-open

**Comment by cinemafreak** [comment]
Thank you, guys.  Yes, it does seem like it's because of the IOS.
