### ISSUE TITLE
APIv2 Updates

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2087]
- [x] path to return all item keys
- [x] return new task on POST & PUT
- [ ] path to upgrade class gear without passing item key (/user/inventory/upgrade or such)
- [x] /user/tasks/:id/:direction return user._tmp (drops & streakbonus info)

> It seems that when you switched to APIv2, you changed the API results of POST /user/tasks and PUT /user/tasks.
> They used to return a task object, containing the id of the object, and every other information about this tasks. It was very useful and allowed me to have the task id as soon as the task was submitted to the server. Now we just have a simple 'OK' saying that the task was uploaded.
> Now, to have the id of the task, I have to do a GET /user/tasks, and retrieve all the other tasks (which I don't care about since they haven't changed).
> Could it be possible to have the result of POST (and PUT) /user/tasks return the task id or the task object?

**Comment by MagicMicky** [comment]
Return new task on creation and edition

POST user/tasks/:id/:direction is working, just wondering if it sends info about drops? 

Sorry to be brief, sent from mobile.

**Comment by lefnire** [comment]
cool, updated the description. Thanks

**Comment by MagicMicky** [comment]
Well this was fast for the item keys. Thanks! Will try it out as soon as I get back from Christmas!

I think there is no need for the 3rd one (path to upgrade gears without item keys) since we can have item keys easily now.

And I guess you can close #2080 now.

I really need to start learning about js and Angular to help a little more...

**Comment by lefnire** [comment]
naw, don't bother with Angular - it's the API (Node.js & Express.js) which could use your help as our primary 3rd-partyist. I'll close the other one and copy the text in the description here (sorry, I totally missed that one!)

**Comment by lefnire** [comment]
@MagicMicky checkout these commits:
- https://github.com/HabitRPG/habitrpg/commit/827d04e4dcc376c0fd7bc0f2e3922d40b9d306cb
- https://github.com/HabitRPG/habitrpg-shared/commit/dfd2a17ef906603dfcdbeec86ead974e2d508c42 (ignore dist/habitrpg-shared.js, it's a compiled version of the coffee file)

You probably wouldn't have been able to add those in, I had to re-rig the framework to return response-objects if called from habitrpg-shared instead of [user.js](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js). Now that that's in place, if you look at [something like this](https://github.com/HabitRPG/habitrpg-shared/commit/dfd2a17ef906603dfcdbeec86ead974e2d508c42#diff-747ea83b7876b59304b3577730cc1b35R651), `cb` (callback) returns the response object as the second parameter. In many cases, I'm plucking only the attributes that would have been affected by the API route. If you want something different, feel free to edit the response object and submit a pull request. Don't be afraid to change response objects, since our web & mobile app aren't using API responses at all, but the batch-api framework instead.

**Comment by lefnire** [comment]
Also, this is pushed to beta.habitrpg.com. Play around and make sure everything seems OK, tell me if you have troubles

**Comment by MagicMicky** [comment]
Well, that's awesome! I will take a look at it tomorrow, but thanks a million! :)

**Comment by lefnire** [comment]
@MagicMicky do you need that "path to upgrade class gear without passing item key (/user/inventory/upgrade or such)" checklist item after all? Or we cool to close this?

**Comment by MagicMicky** [comment]
No, with the /content route, I can easily guess what item should be bought.
I think you can close this.
Thanks a lot!

**Comment by lefnire** [comment]
√
