### ISSUE TITLE
Snowball at 1x zoom

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2088]
The snowball sprite is at 1x zoom! It should be at 3x zoom. Did you check the most recent sprite uploaded to the Trello?

**Comment by lefnire** [comment]
doesn't fit 40x40 for item-store & inventory. Nearest-neighbor scale down looked poor. Can you make one a <40x40?

**Comment by lemoness** [comment]
?? I made the snowball itself 39 by 39... do you mean, with the blank
outline? I've trimmed the .png so there's no transparent border; emailing
it to you now. Sorry! I figured you would just crop off the transparent
excess to fit.
