### ISSUE TITLE
Cannot delete a habit created by challenge that no longer exists

### ISSUE THREAD

**Issue by ndandanda** [HabitRPG/habitica#2089]
Explanation: some time ago I joined a challenge that created a "productivity" habit. This challenge no longer exists (so I cannot leave it) but when I try to delete this habit it disappeares for some time and then reappeares. I tried to delete it from Crhome and Safari browsers and Android app, with no success. Emptying cash didn't help either.

Browser: Chrome Version 31.0.1650.63

Java console: 
Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.
Received message of type object from chrome-extension://pioclpoplcdbaefihamjohnefbikjilc, expected a string all.js:56
Received message of type object from chrome-extension://pioclpoplcdbaefihamjohnefbikjilc, expected a string all.js:56

Thank you in advance.

**Comment by lefnire** [comment]
@ndandanda I see you closed the ticket. Was it resolved for you, or was the ticket-close an accident?

**Comment by ndandanda** [comment]
I found out that the habit was automatically generated by chrome extension. Sorry for taking your time.
