### ISSUE TITLE
Digital item to increase gold intake

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#209]
_Note by wc8: Vote for [Gold-Boost Item here](https://trello.com/c/yX3PAtJZ)._
I think a digital item to increase gold intake would be a great addition.

Something like a ring, gloves or boots of luck. 

They would add a +3% multiplier similar to armour or weapons do for HP and XP currently.

**Comment by Nelmalih0** [comment]
I think Exp Gain is linked to Gold gain so the weapon would increase gold intake too

**Comment by horusofoz** [comment]
@lefnire Can you confirm the above?

**Comment by lefnire** [comment]
they are indeed linked. If we add such stats modifiers (i like the idea) we'll need to break the link, which shouldn't be too hard.

**Comment by horusofoz** [comment]
Adding another line of digital items would be beneficial. Though in keeping with the current line up will need to be visible on avatar. Not that much space left so possibly boot or amulet?

**Comment by lefnire** [comment]
line == column?

**Comment by lefnire** [comment]
easy to put rewards column in tabs, similar to "Todos" remaining / complete

**Comment by horusofoz** [comment]
Sorry I haven't worded that well.

I meant as in a line of rings or a line of boots.

Using the same terminology there is currently a line of armour (leather, chain, plate, etc).

**Comment by Pandoro** [comment]
Considering I have been working on some of the pixel art, I think it is "fairly" easy to split up the helmets and the body armor. Boots and rings are something I regard as next to impossible with the current resolution of the characters. Funny enough though, 1 Pixel is currently represented by 3x3 pixels. There are a lot of possibilities, but this would also mean a LOT of work in my opinion and it would change the overall look of the game.

I would rather think about the pets and mounts which are to follow if the Kickstarter project works out. These can serve as additional "lines" of items and as I said maybe the splitting of the armor would give another option. Additionally I could think of some "treasure chest" where you could maybe "display" two collectible items which could give additional stats. There you could for example put amulets, rings, runes or whatever you would deem a worthy item.

**Comment by lefnire** [comment]
i agree with the chest idea. or a backpack or something - bring up a Bootstrap Modal showing your equipped items, but you can only view the sort of "macro" equipment on your avatar.

**Comment by wc8** [comment]
Note by wc8: [Chest for Reward Items](https://trello.com/c/2brf9FNW)

**Comment by horusofoz** [comment]
Graduated to [Trello](https://trello.com/c/2brf9FNW).
