### ISSUE TITLE
Paid the supporter thingy - still have ads, didnt get gems

### ISSUE THREAD

**Issue by FraktalInverTer** [HabitRPG/habitica#2090]
While I do love contributing to a worthwhile project just because it is awesome, the ads are really annoying. Could you look into why I didn't get my rewards after paying?

Oh.. my uuid is: e53390fa-0f01-49de-8989-3b91c8fb1278

**Comment by lefnire** [comment]
Give that a shot. We're having trouble with international paypal for some reason, but it's really inconsistent. Extra gems for the trouble and the wait.
