### ISSUE TITLE
Earthquake still not working

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2091]
I cast Earthquake this morning, lost 35 mp, received a notification that I'd cast Earthquake on my party, and nothing showed up in buffs, and xp didn't change. I waited about 45 minutes, but nothing changed. I have no other buffs on me.

(Unfortunately only people with commit access can re-open github issues, so I'm creating a new one, sorry!)

**Comment by wc8** [comment]
Tip: if you comment in the original ticket, we’ll see it and we can reopen it.
Is the original #2064 ?

**Comment by lorian** [comment]
Nope, it is #2070 although the problem is the same.

**Comment by SabreCat** [comment]
Looks like a duplicate indeed. Closing this one, the original is reopened so we can follow there.
