### ISSUE TITLE
Non-Modal Drop Notifications

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2092]
Give drop notifications in the format of XP, GP, with an image of the drop so they do not interrupt workflow. 
- related to Trello https://trello.com/c/684Dv1py/320-quiet-notifications-bell
- would also help with 2nd request from #939

**Comment by lefnire** [comment]
I'm for it. oh, sabrecat assigned himself! _wipes sweat_

**Comment by SabreCat** [comment]
This is probably a rabbit-hole of a question, but this came up in the context of customization, turning different alerts off. Does this need to be configurable? I'm hoping not, I think it'll be fine if everybody gets the initial modal explaining drops and then the rest just appear as alerts, but wanted to be clear re: the request...

**Comment by wc8** [comment]
@SabreCat I’d say no, don’t make this configurable. Initial modal explaining drops, the rest as alerts. So long as they don’t blink by too fast, I doubt anyone would have an issue with this.

**Comment by SabreCat** [comment]
@lefnire, gonna pass this to you for now for whenever you get the chance to investigate adding drop icons. I'm still working on some misc drop improvements and can do e.g. coming up with a notification style for drops, but I think the hardest piece here is the icons, and that's proven beyond my grasp so far.

**Comment by SabreCat** [comment]
I guess I'll write up a separate ticket for the icons, then?

**Comment by deilann** [comment]
That would be awesome. I closed this because the spirit of the ticket has been completed.
