### ISSUE TITLE
My character did not start with a sword by default. But my friend's did.

### ISSUE THREAD

**Issue by guifes** [HabitRPG/habitica#2095]
My two friends playing with me started their characters with a sword, mine didn't.

**Comment by lefnire** [comment]
UUID?

**Comment by guifes** [comment]
cb4e4581-c305-42c4-a25b-41f7f2db0987

**Comment by lefnire** [comment]
Interesting.. I'll look into why it didn't equip automatically for you, but in the meantime you can equip it from your inventory https://habitrpg.com/#/options/inventory/equipment

**Comment by guifes** [comment]
Now that you've mentioned it, I realised that my inventory tab in options is not even appearing. But I could manage to access it going directly to the URL.

**Comment by lefnire** [comment]
Oh snap, sorry inventory unlocks with pets at lvl 3. Yeah of can access by
URL before then if you know it

**Comment by guifes** [comment]
Since I got your attention, I did not create an issue for this yet, but in the web I can't see the default rewards (Leather armor, sword, etc). But I can see them in my Android app.

**Comment by lefnire** [comment]
Lvl 2. just level up a few and check back at 5 if you're still having
issues

**Comment by guifes** [comment]
I'm already lvl 3 and I still can't see where to open my inventory. I can only open it via direct URL https://habitrpg.com/#/options/inventory/equipment

**Comment by lefnire** [comment]
Level 4. You've got one more level before inventory unlocks (with the pets & drops system). Here's the order of unlocks:

2: Item store (under your rewards)
3: Party (just a notification, it's always available)
4: Pets, Mounts, Drops, Inventory Tab
10: Classes
50: Rebirth
