### ISSUE TITLE
Spell list has disappeared.

### ISSUE THREAD

**Issue by Shmitz** [HabitRPG/habitica#2096]
I am a level 10 rogue. My spell list disappeared after refreshing my browser sometime on the day I leveled to 10. This was the same day I saw the message that class unlocks were getting pushed from level 5 to level 10. I was a rogue previously, and it still says I'm a rogue. It is still offering me rogue equipment to purchase.

My user ID is e8a9aabd-b14c-45d7-92c3-4bfe2c583669

I use Chrome. I see this error in the console: 
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1

**Comment by lefnire** [comment]
classes unlocks at 10 now, not 5. spells unlock then at 11,12,13,14. Had some major backlash for unlocking classes so early (users getting confused/overwhelmed). One more level, friend!

**Comment by doctorcurly** [comment]
Thank you.
