### ISSUE TITLE
Difference Between Rewards Earned on App and on Website

### ISSUE THREAD

**Issue by kalliburr** [HabitRPG/habitica#2097]
So there is a HUGE discrepancy between the gold I earn on my iPad app vs. the gold earned on the website.  I have attached two images, both were captured today while selecting the same habit.

The first one was taken from the app.

![img_0084](https://f.cloud.github.com/assets/6013399/1804287/5e94f044-6c45-11e3-9e41-2808ade80564.PNG)

This second one was from the website.

![screen shot 2013-12-23 at 6 38 38 pm](https://f.cloud.github.com/assets/6013399/1804289/99289580-6c45-11e3-9376-e95d34e0bfa6.png)

Same habit, different gold and XP.  But then when I log onto the website, it diverts back to the gold that I had as if I hadn't logged the activity on the app, and when I go back to the app again, it changes so that it agrees with the website.  So I earn 40 gold on the app, buy a hat, go to the website, and it says no I didn't, then I go back to the app and says yeah, no you didn't.  =_=

**Comment by lefnire** [comment]
see this update: https://www.facebook.com/Habitrpg/posts/551153928302320 . Unfortunately we can't push an iOS update to till 12/28; luckily, the server saves the correct math, but you'll need to refresh periodically & keep that in mind for the next week. Kinda a bummer :( I'll keep this ticket open until we can push

**Comment by kalliburr** [comment]
Cool.  :3  It's not a huge problem, it's just confusing. xD
