### ISSUE TITLE
Show progress/weight bars for task-based auto-allocation

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2098]
When the present (task attribute-based) auto-allocation feature is on, the only way to tell what you're leaning toward is to keep track of your present attribute point assignments and see which one changes when you level up. It would be useful, and a cool motivation enhancer, if you could see some indication of your attributes' relative weight during the course of a level. Say, little percentage bars with the attributes showing that my CON is currently in the lead, with PER close behind, and STR a distant third, or whatever. That way I can plan my real-world tasks to try to level up the point I want!
##

**Comment by SabreCat** [comment]
This doesn't actually make much sense for the current implementation of auto-allocate. But I'll take a look at this toward the end of my [auto-allocation overhaul](https://github.com/HabitRPG/habitrpg-shared/tree/sabe/attributes).

**Comment by SabreCat** [comment]
Gonna reopen this one, I still intend to take a stab at it eventually. Would make transparent what's going on with task-based auto-allocate, whereas right now it's a sort of black box that goes pop! surprise! when you level up. :P

**Comment by DrTall** [comment]
I agree this would be cool!

**Comment by lemoness** [comment]
@SabreCat Do you still want this open? It's pretty old.

**Comment by SabreCat** [comment]
Not super important. I've long since stopped using task-based auto-allocate, myself; it's a system that could use some overhauling if it's to be of value to more than a niche population of users.
