### ISSUE TITLE
Unable to login via Chrome on Android

### ISSUE THREAD

**Issue by toekneebullard** [HabitRPG/habitica#21]
As soon as I type in my username and switch to the password field, I get a "disconnected" message alongside my username. 

![2012-12-31 10 18 59](https://f.cloud.github.com/assets/1326712/36665/014b028a-535e-11e2-9861-759d5325ef45.png)

The "Login" button appears to be grayed out because of this.

If I close out the login pop up, the top of the page says "Offline - Reconnect". If I click "Reconnect" it switches to just "Offline" and then back to "Offline - Reconnect"

I've tried closing the tab, and the browser and retrying, but I get the same result each time. 

I just tried rebooting but now it appears you're having web troubles. Just say "Cannot GET /"

**Comment by lefnire** [comment]
I think I solved it, was a mongohq corrupted session issue. try now

**Comment by toekneebullard** [comment]
Now I get this:

Template Error
TypeError: Cannot read property 'history' of undefined
    at EventEmitter.Component
(/app/node_modules/derby/lib/component.js:79:30)
    at createComponent (/app/node_modules/derby/lib/View.js:680:19)
    at partialBlock (/app/node_modules/derby/lib/View.js:847:16)
    at /app/node_modules/derby/lib/View.js:631:48
    at render (/app/node_modules/derby/lib/View.js:199:12)
    at Object.get (/app/node_modules/derby/lib/View.js:263:30)
    at Object.View._render
(/app/node_modules/derby/lib/View.server.js:310:23)
    at View.render (/app/node_modules/derby/lib/View.server.js:278:10)
    at View._init (/app/node_modules/derby/lib/View.server.js:291:5)
    at Object.View._load._load
(/app/node_modules/derby/lib/View.server.js:85:7)

**Comment by lefnire** [comment]
Gah! Was running smoothly up until yesterday/today, sorry about this @toekneebullard, bear with me. [Background](https://github.com/codeparty/derby/issues/187#issuecomment-11540349) on the issue

**Comment by toekneebullard** [comment]
If it makes you feel any better, I'm really excited to use it!

**Comment by lefnire** [comment]
It _indeed_ makes me feel better :)

**Comment by lefnire** [comment]
k how 'bout... now!

**Comment by toekneebullard** [comment]
Fantastic!

Tony Bullard
tonybullard.com | @toekneebullard

**Comment by lefnire** [comment]
_phew_ ok, I'm gonna leave this open for a while. I'm pretty sure I pegged it, but just in case.

**Comment by lefnire** [comment]
I'm closing this, it was simply a matter of the app was crashing generally. there are some other issues in this queue which may trigger the same issue, but i'll track them independently.
