### ISSUE TITLE
Progress Not Showing For New Habits

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#210]
I noticed new habits that have only Up or Down don't have a progress window. Progress is only showing for older habits.

**Comment by StanLindsey** [comment]
I just checked this also, though there may be a reason behind it: e.g. it doesn't display a progress window until you've completed it x amount of times. @lefnire will have to chime in on this one.

**Comment by lefnire** [comment]
It's true, you have to have 2 items of progress (2 days passed, 2 +-
clicks, and note: +only and -only don't get progress) - but it sounds like
it's still an issue beyond that for people?

**Comment by StanLindsey** [comment]
The issue is there wasn't any feedback to when it would be displayed. Maybe have the view there by default but replace it with; "You need to have 2 items of progress before this is tracked" and some more detailed little blurb underneath. Doesn't seem to be a huge issue though.

**Comment by horusofoz** [comment]
Is it possible to develop a +only or -only progress option? 

This I assume will require an inaction indicator and side effect. 

My thoughts would be if a user doesn't + a +only habit in a day then it counts as the equivalent of a - and they lose HP and record negative progress.

For a -only habit if the user does not - it in a day it counts as a + and they gain XP/GP and record positive progress.

If it's your thinking that this functionality may not be desirable for most users than have it as an opt-in function under Edit Task>Enable Inaction Consequences.

**Comment by StanLindsey** [comment]
Well what you are talking about there though are dailys. If a user doesn't check off a daily it takes off HP.

One of the examples of Habits is the "Take the stairs", this gives a positive or negative reaction to a real-life choice. If a user never encountered this choice then the habit shouldn't have any affect.

**Comment by lefnire** [comment]
Jeff, +only and -only progress is planned:
https://trello.com/card/habit-shading/50e5d3684fe3a7266b0036d6/67

**Comment by horusofoz** [comment]
@SlappyBag I see what you're saying but I think there is a large grey area.

For example, "Reduce Alcohol Intake". I have this habit as a -only as I don't drink every day (doesn't qualify as a daily) yet it would be inconvenient to + it everyday I don't drink. Also I would need to remember everyday if I had already +'d it. Additionally if I were away for a couple days then during that period no positive progress would be recorded.

Another example from my own Habit list is "Help Others". This isn't a daily task but rather a positive habit I have set as +only. Sometimes I'll feel my actions qualify for multiple +'s in a day. Sometimes there'll be consecutive days where I don't + it as there has been no action on my behalf to warrant it. It would be good if I notice this habit losing it's blue colour to prompt me to look for opportunities to be helpful to others.

@lefnire Your comment popped up just as I was about to click "Comment" but I'll post anyway for posterity. Thanks :)
