### ISSUE TITLE
Buying max Wizard/Mage gear doesn't earn Ultimate Gear achievement

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2100]
Noticed this while testing my Rebirth branch, but I suspect it's the same on main. If you buy up all the Wizard equipment, you don't earn the Ultimate Gear achievement. I suspect this is because Ultimate Gear checks for maxed-out shield, and the Wizard doesn't get shields!

**Comment by lefnire** [comment]
Oi! Good catch!

**Comment by SabreCat** [comment]
Should be easy to fix, just check if the Weapon is two-handed, and only require the shield if not. (Rather than check if class is Wizard, which would require re-fixing if we add Rangers or something later with the same problem)

**Comment by lefnire** [comment]
Definitely. 2m job, will do when back at a comp

**Comment by storian** [comment]
Does the Ultimate Gear achievement only happen once, and not happen again if you change your class?  I have that achievement from before classes were implemented, and I've bought all gear for the Rogue but did not receive it again.  Is that how it's supposed to work?

**Comment by SabreCat** [comment]
@storian: That's right. It could be a cool enhancement to have separate achievements for each of the classes, but at the moment, you get the Achievement once for the first class you max out, and it's done.

**Comment by storian** [comment]
Ok cool.

**Comment by SabreCat** [comment]
@lefnire Nvm, I'm on it. Trawling the queue for little things I can address, y'see :smile_cat:
