### ISSUE TITLE
Quest scrolls

### ISSUE THREAD

**Issue by Jajoto** [HabitRPG/habitica#2104]
I aborted quest scrolls and I thought I would keep it in inventary. I want it back. :(

ID: f6d401ca-7e94-4961-b9b3-b85c8c8b5d66
API: [edit: removed by @lefnire, security risk]

**Comment by lefnire** [comment]
I'll give you yours back, but I'm not sure if we're going to have "abort quest" restore people's scrolls. Quests are meant to trigger productivity sprints, and if people can abort close to the end of a failing quest, it takes away their incentive to get their act together during the quest

**Comment by lefnire** [comment]
added back
