### ISSUE TITLE
"No user found" and continuous refresh

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2105]
When I go to habitrpg, I get a dialog box saying "no user found" and after pressing OK, the page reloads. After reloading, the same thing happens again. I've tried this on a browser on which I'm logged in, and it does show me my tasks &c before the dialog pops up. I also tried it on a browser on which I'm not logged in, and the same thing happens when it loads the HabitRPG title screen. There's nothing I can do to get past it. 

In the browsers where I'm logged in, it also shows a habitRPG notification in the upper right reading "Error 401: No user found".

**Comment by DanielTheBard** [comment]
This was happening to me, too, on the beta site. Swapped to the normal site with no problem. But the last 19 hours of chat have been deleted. Got back on beta now though no problem.

**Comment by octern** [comment]
Okay, it persisted through the first 5 reloads in multiple browsers. Then it reloaded a version of my page from about 4 days ago, and then it updated back to the current version, and the problem resolved. I'll leave this open in case it's happening to others.

**Comment by lorian** [comment]
Just happened to me as well, with the 401s and popup box and endless reloads; Firefox eventually crashed while I was attempting to reply to this issue, and now it is not doing it any more (cross fingers).

FWIW, I'm on the standard site, not the beta one.

Edit: As Lrdwhyt says, my dailies were reset and were from yesterday (I change the text of some of them every night), before I had checked anything off. Can't tell if my xp or gold is also rerolled back.

**Comment by ylysyym** [comment]
Yep, had this problem. I logged out and tried to log back in, but it would not let me. So I reset the password, logged in, and found that my progress had been set back.

**Comment by DanielTheBard** [comment]
@lefnire has realized and is looking into it. He set the site back to a version from this morning I think to fix it.

**Comment by lefnire** [comment]
Holy snap! There was a database outage. Doubtful it has anything to do with bosses, but no clue what happened, I'll see if there are MongoHQ logs. I did a roll-back to this morning. Let me know if anyone needs any missing gems or such in the mean time, more soon

**Comment by lefnire** [comment]
Hey all, I can't find any leads... I fear for the worst - I think I ran a development database script against production accidentally :( :( I've given everyone who's logged in today 2gems for the troubles, and I've emailed anyone who's actually purchased gems to give me their UUIDs. I'm so sorry everyone! That's a dev's worst nightmare, we're always so meticulous when running our db scripts for this very reason... 

Anyway, db restored, problem fixed... :(

**Comment by lefnire** [comment]
If anyone still needs apology gems, [shoot me a message](mailto:tyler@habitrpg.com)

**Comment by lefnire** [comment]
and also if people need stats restored, go to Options > Settings > Restore Character Values. If you need Streaks restores, edit a task > Advanced > Restore Streak. If you have tons of streaks and that would be too daunting, [email me](mailto:tyler@habitrpg.com) and I'll revert your streaks from 12/24

**Comment by wisteriacs** [comment]
Myself and a party member died today and yesterday when we really shouldn't have. Not sure if it's part of this or not. We can mostly reset, but two days feels like a pattern that ought be reported. Plus my friend is finding it de-motivating and I want him on board for our first quest!! ;-)

**Comment by lefnire** [comment]
Hm, the db outage hasn't recurred... is this possibly due tot he same issue (ie, he hasn't logged in since right before the outage 3 days ago, and only just logged in now)?

**Comment by wisteriacs** [comment]
That would explain yesterday (for him, not me, since we both died two days in a row and only he was I the inn yesterday), but not today for either of us. I haven't talked to the other party members about it yet.

**Comment by lefnire** [comment]
@wisteriacs has this recurred at all?

**Comment by wisteriacs** [comment]
Thanks for checking! My friend has been fine. I died today but with class calculations changing I don't know if I had it coming or not. I used mana to try to hide from my dailies today, but I don't know how much that does... Basically, I'm not sure. I would be more helpful if I were better with my dailies. ;-)
