### ISSUE TITLE
No User Found

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2106]
This morning, https://habitrpg.com/#/tasks is hysterically alternating between a pop-up that says "No user Found", in white, in the upper center of the window; a pair of pop-ups where I normally get notified about xp, gold, etc, in pink, saying "Error 401: No user found"; and notifications about scripts running too long. It's also hogging most of the cpu cycles given to the browser, except when waiting for me to click "OK" on the white pop-up. 

I'm using firefox 25.0.1 on Ubuntu 12.04. 

When I went to bed, the site was behaving sanely. This morning I used my browser's refresh button to get it to recognize the new day, which it seems to have done (I'm back to full mana points), and then marked my first daily as complete. I don't recall for certain whether the first message about the scripts happened before or after I marked the daily complete. The other stuff was after. This is my normal morning routine - i.e. this set of actions normally works fine. 

Firefox and its hangerons seems to be leaking memory again - a perennial problem on my system - and it's back up to 9190M virt, with resident set size of 5.5 g. (70.8% of mem) It's also reporting 101% cpu - all this according to top. IIRC, 101% means it's using all of _one_ cpu on my MP desktop, not all the cpu in the system. 

I'd really like to know which of my browser associated apps leaks memory - and whether it's habitrpg ;-) - no idea whether that's related to the current problem - doubt it, since I've seen this before without the habit misbehaviour. Reporting it anyway, as relevant data - but frankly the memory usage isn't yet at the point where I normally kill and restart firefox ;-) (The cpu on the other hand, is way higher than normal.)

Going to submit this, kill firefox, and then report any interesting developments on restart.

**Comment by lefnire** [comment]
See https://github.com/HabitRPG/habitrpg/issues/2105#issuecomment-31203606 for the User Not Found issue, see https://github.com/HabitRPG/habitrpg/issues/1499 for the performance stuff

**Comment by ArlieS** [comment]
It seems sane now, though I haven't clicked anything yet. I've lost 7 HP, 112 XP, and 21 GP; I take it this is roll back + day starting with many of yesterday's dailies at the rollback state. Not concerned about the losses - it won't kill my character. Just reporting for clarity. Thank you for being alert and on this on a holiday morning; I really wasn't expecting you to once again respond before I'd finished data gathering.

**Comment by ArlieS** [comment]
yep, it's sane. I successfully reported my first daily of the day

**Comment by lefnire** [comment]
Oh, not at all! I'm in panic mode with that stray-script, I've ruined Christmas :(  Anyway, thanks for the report and your understanding

**Comment by skreebat** [comment]
Hey, I've just joined the community today, and everything was working fine until I checked one of my To-Do boxes. My page started to immediately tell me "user not found" and refreshing continuously. It just keeps looping on that. I assume it has to do with the same issue?

**Comment by lefnire** [comment]
@skreebat i'm pushing the constant-refresh fix fix right now. To get out of it for the time being, you'll have to hit `esc` to prevent reload, then click Logout from the user dropdown. You'll have to create your account again :(

**Comment by skreebat** [comment]
@lefnire Ah, alright! That's okay. Thank you. :)
