### ISSUE TITLE
Error 401: No user found

### ISSUE THREAD

**Issue by dariattic** [HabitRPG/habitica#2108]
I've made a new account just this afternoon, but now I'm unable to use it. An Error 401: No user found keeps popping up.

My User ID is ad1dc74c-5a85-4ee8-bb03-39fb8227851a
My API is 3c93f5e4-6589-44d2-b80f-11a4bf3a51e5

If it helps, I'm using Firefox, only I'm not sure what part of the source code on the page tells about the error.

**Comment by lefnire** [comment]
see https://github.com/HabitRPG/habitrpg/issues/2106#issuecomment-31204520
