### ISSUE TITLE
I died

### ISSUE THREAD

**Issue by Habitfan** [HabitRPG/habitica#2109]
I just Died and lost a boatload of gold. This one was a bug. I lost over 10k in Gold! I am not looking for anything i did not earn but any help would be appreciated!

It's Christmas so I don't expect anything to be done today I just wanted you to be aware. 

Thanks Seneca.

**Comment by lefnire** [comment]
alas friend seneca, it's https://github.com/HabitRPG/habitrpg/issues/2105 . Read up on that bit, you'll have to restore (Settings > Restore). [Let me know](mailto:tyler@habitrpg.com) if you're missing apology gems
