### ISSUE TITLE
Spells hidden

### ISSUE THREAD

**Issue by boehsermoe** [HabitRPG/habitica#2110]
I can no more cast spells since some days, all my spells are hidden...

**Comment by SabreCat** [comment]
Are you 10th level, or higher? You shouldn't have all spells unlocked until level 14.

**Comment by boehsermoe** [comment]
I'm level 10 and last Weeks i had 4 Spells, but now they are disappeared.

**Comment by SabreCat** [comment]
Yup. The progression has changed. Classes now unlock at level 10, and you get a spell each level thereafter.

**Comment by boehsermoe** [comment]
Ah ok, thanks!
