### ISSUE TITLE
Dailies resetting early

### ISSUE THREAD

**Issue by xAlec** [HabitRPG/habitica#2116]
My dailies are set to reset at 3:00 am, but have done so early. As a result, I've lost a bunch of health.

Browser: Safari 7.0.1

**Comment by lefnire** [comment]
follow on https://github.com/HabitRPG/habitrpg/issues/1057

**Comment by lefnire** [comment]
Woops, resetting too early - haven't seen that before, re-opening

**Comment by SinEstelle** [comment]
I had the same thing.  I saw a message in the tavern chat by someone saying there was a database hiccup and it had to be rolled back a day.  

But I hadn't had a chance to put them all back in, and have now lost a lot of health, and lots of streaks too.  :/

**Comment by paglias** [comment]
Had the same thing but only once (two days ago if I recall correctly)

**Comment by lefnire** [comment]
Oh, I think the issue isn't early reset then, I think the issue is #2105
