### ISSUE TITLE
Ctrl-F5 I lose tasks and sorted lists

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#212]
I lost a few tasks earlier today.  Not sure why.  The ads were missing off my page at that time so perhaps I lost communication and didn't see the notice at the top of the page.

Also, when I hit ctrl-F5 to refresh the page (to see if my changes "took") I lose the sort order of my To-Do items, and the other lists were randomly (seemingly) sorted as well.

Excited about the game.  Looking forward to helping out.

edit: Honestly, I wouldn't mind a "save" button to commit changes and updates I've made.
edit2: happens even with just "F5"

**Comment by racuna** [comment]
+1 Save button (or sync status message too)

**Comment by wc8** [comment]
Note: Browser refresh or reload (F5, CMD/CTRL+R) will "save" changes so long as the user was not offline when the changes are made. If you see the Offline-Reconnect message at the top of the page, reload before making changes. Then use reload to save changes.
#171 [Update: #171 related to +save button / sync status message, not @abednego's issue]

**Comment by abednego** [comment]
Thanks, wc8.  The order is still lost when I refresh.

**Comment by wc8** [comment]
Which browser are you using?
If you have any other browsers, does the problem happen there, too?

**Comment by abednego** [comment]
Using chrome.  I think this may have been due to my misunderstanding of how the system works and updates.  As you mentioned, if the offline message is at the top, any changes will be lost.

It appears to be working correctly now that I understand.  I'll keep watching this and trying IE as well to see if the behavior is duplicated.

**Comment by lefnire** [comment]
To be clear, when all is fixed that won't be how it's supposed to work -
it's supposed to properly reestablish connection and always sync data. It's
just the workaround people have found with my presently buggy-ass app ;-)

**Comment by horusofoz** [comment]
@abednego I recommend against using IE. The framework used for HabitRPG (Derby) has limited support for Internet Explorer and does not plan to resolve until IE10.

**Comment by Pandoro** [comment]
The bug I noticed today is somewhat related to this I think. I did not loose tasks, but the order gets messed up all the time and I am no longer able to properly sort the list. Sometimes while sorting the task is placed on the right place where I dropped it, but sometimes it pops up somewhere else and also messes up the order of one or two extra tasks in the list. 

I'm using Firefox 17.0.1 on Ubuntu 10.04.

**Comment by horusofoz** [comment]
Is anyone still experiencing this issue? I was under Chrome/Win7 but haven't had recurrences.

**Comment by wc8** [comment]
I am occasionally experiencing issue of task order reverting, but I don't think I am losing tasks, or having issues with drag and drop. 

I use Mac Mtn. Lion Chrome. I had been using Fluid but lately it seems that browser has a higher likelihood of receiving high-server load warnings from habitrpg.com.

**Comment by horusofoz** [comment]
I find my Todos get rearranged. I don't take note enough to see how often but I have noticed this for some days now.

**Comment by StanLindsey** [comment]
#318 - closing for housekeeping.
