### ISSUE TITLE
My character died twice yesterday!

### ISSUE THREAD

**Issue by Tinus427** [HabitRPG/habitica#2120]
... just as I was checking tasks. I was a little low on HP the day before, so it didn't surprised me much the first time (though I thought I could made it to the next level without damage). But how could it happen a second time on the same day?

Thank you!

**Comment by SabreCat** [comment]
There was a database blooper that caused some rollback of data--this probably hit as a result of that. Please reopen if you see this again. See #2105 for additional info.
