### ISSUE TITLE
Huge loss of health for no reason

### ISSUE THREAD

**Issue by Walthanar** [HabitRPG/habitica#2121]
I was at 50/50 health and 7 mana yesterday before date change, with one red task not completed, that usually hits for 7-8 damage. Today I found 18/50 HP and 71/72 mana, I cast all the healing I can and that's no problem, though I think it's a bug of some sort. I also started the xmas quest, maybe it's part of the problem?

**Comment by SabreCat** [comment]
There was a database blooper that caused some rollback of data--this probably hit as a result of that. Please reopen if you see this again.

**Comment by lefnire** [comment]
@Walthanar see https://github.com/HabitRPG/habitrpg/issues/2105 for some deets
