### ISSUE TITLE
#2090 revisited - Paid the supporter thingy - still have ads, didnt get gems

### ISSUE THREAD

**Issue by FraktalInverTer** [HabitRPG/habitica#2122]
Bug 2090 was fixed, then when I logged in today all gems were gone and ads are back again. Did you do some server restore?

Please help again.

**Comment by SabreCat** [comment]
There was a database error within the last 48 hours that forced a rollback. Can you provide the User ID from your Settings > API page? That'll let us get your ads and Gems fixed.

**Comment by FraktalInverTer** [comment]
Hi my uuid is: e53390fa-0f01-49de-8989-3b91c8fb1278
I had 40 gems on my account, I got some extra from Tyler Renelle as compensation after the first trouble with the account.

**Comment by SabreCat** [comment]
Should be back to 40 Gems with ads off. Do a refresh, check it out, and let us know if there's further trouble!
