### ISSUE TITLE
Donation effects suddenly reverted

### ISSUE THREAD

**Issue by jacobb84** [HabitRPG/habitica#2125]
Hi there, 2 days ago I donated 5 dollars to buy 20 gems and disable the ads. I bought one skin set for 5 gems that day as well. Today when I logged in though, all the ads are back, and my purchases and gems are missing. 

My user id there is also RatNeurons and the PayPal transaction was #7A073854X5049091V

Let me know if there's any other info I can provide to help track this down. Thanks!

**Comment by SabreCat** [comment]
There was a database error within the last 48 hours that forced a rollback. Can you provide the User ID from your Settings > API page? That'll let us get your ads and Gems fixed.

**Comment by jacobb84** [comment]
Awesome, thanks. Here's my id:

0250e37a-82fd-4563-a5e5-3f3d1c07a426

**Comment by SabreCat** [comment]
You should now have your 20 gems back and ads hidden. Reopen if that's not the case!
