### ISSUE TITLE
Daily Resets for Inventory, HP, EXP, etc.

### ISSUE THREAD

**Issue by Django53** [HabitRPG/habitica#2127]
Hello all,

Ever since the HabitRPG update that introduced classes I have been having bug problems both on mobile (Android) and on the computer. For example, yesterday I leveled up, allocated a point, bought a new weapon, made a few new pets, fed pets, completed tasks, To-Do's, etc. and today all of that has reset. My new weapon is gone, my pets are gone, my completed To-Do's are back, I leveled down, etc. 

This has not been a one time occurrence but happens about every other day since the class update. I have tried using only mobile, only the computer and a combination and no matter what I do the bug keeps happening. At this point HabitRPG is completely unusable. 

Is this happening for other people as well or does anyone know of a fix? Any help would be greatly appreciated, thanks!

**Comment by lefnire** [comment]
Yesterday saw a big database hiccup #2105. The fact that it's happening every day _is_ unusual. What's your UUID? Also, do you know if you have 0.0.14 or 0.0.15 of the mobile apps installed? The previous versions of the apps have outdated math

**Comment by Django53** [comment]
Thanks for the fast reply! Is UUID my User ID? That would be 640f7208-30c4-4f3d-8dd8-40ba5034f69a. If that's not what you are looking for let me know where I can find it. My mobile version says 0.0.13. But I just checked for an update an now have 0.0.15.

Could my outdated mobile version have been causing problems even if I was only using the full website the last few days?

Thanks again for the help.

**Comment by lefnire** [comment]
I think that's what it was then. What happened was the outdated mobile app had bigger numbers all around, so users were leveling up faster, getting more gold, etc.The server (website) was saving the correct numbers, so what would theoretically happen is you'd be lvl10 with 1000 GP on mobile, then open the website and you're 3 with 20gp. (the numbers were really really bogus with the initial launch). 

What's flagging me is that you were getting pets that weren't sticking. Pets don't show up on mobile, and the website is the "canonical" version - so if you got a pet and it disappeared, something's up. Now, if the pet issue is something you noticed within the last 48h, then that's an issue of #2105. 

So... my _hunch_ is, now that you're on 0.0.15, and now the db hiccup is sorted, everything will be good going forward. I'm gonna close this after taking a peak at your database record to make sure everything's ok, re-open if it happens again

**Comment by lefnire** [comment]
yeah, everything looks good on the database side, so just keep an eye out

**Comment by Django53** [comment]
Thanks for the help. I'll let you know if I encounter any more problems.
