### ISSUE TITLE
Can't Start Quest

### ISSUE THREAD

**Issue by ParisiT** [HabitRPG/habitica#2128]
The button that would allow me to start a Quest for my party (specifically, the 'Trapper Santa' Quest) isn't showing up. I've checked with each of the members of my party, and none of them have started a Quest, so that's not the issue, and I can't find any other reason why members of the party or the party as a whole would be ineligible.

If it helps, my party's group ID is 0b521f95-cdf2-4efe-af56-ab5583f6ff09 and the quest is the 'Trapper Santa' Quest.

**Comment by lefnire** [comment]
Looking at the database, invites haven't yet been sent out for the quest. This may actually be due to #2105 - double check to see if the scroll is still in your inventory, you'll probably have to init the quest again

**Comment by ParisiT** [comment]
Well, the problem seems to be that I can't find a way _to_ init the quest. There is no apparent mechanism to do so.

**Comment by ParisiT** [comment]
The scroll is still in my inventory. Watching. Waiting. Taunting me with it's questyness.

**Comment by lefnire** [comment]
So when you click the quest scroll in your inventory, you should get a
modal dialog where you can click "Invite Members". After that, you go to
Options > Social > Party and you'll see who's accepted / rejected pending.
You can either wait for everyone to accept/reject (then quest auto-starts),
or you can click "Begin" at the bottom of that user list, and the quest
starts.

Which of these steps isn't working for you?

**Comment by ParisiT** [comment]
The first one. The dialogue box that comes up has no "Invite Members" button.

**Comment by ParisiT** [comment]
Okay, it shows up when I am on a PC. It seems that if you open it up on a touch-screen device (such as an Ipad) the button to Invite Members doesn't show up.

**Comment by lefnire** [comment]
Ohhh.... does it look hidden by other html elements? Or is it actually invisible. I'll play with it some when I get the chance

**Comment by ParisiT** [comment]
It's just not there at all. So the latter, as far as I can tell.

**Comment by deilann** [comment]
@ParisiT I'm going to guess the modal is cut off, due to the screen size, not invisible or hidden by other HTML elements.
