### ISSUE TITLE
Include tags in sticky header

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2129]
EDITED

I've been finding lately that I'd really like certain things to stick to the header that currently don't. On Tasks, it'd be fantastic to have my filters available as I scroll down through the lists:

![screenclip](https://f.cloud.github.com/assets/4501321/1811491/068007c2-6e57-11e3-8abf-1301cc842475.png)
## What's below is not relevant anymore with the new interface:

And on Options, I find myself needing to scroll all the way back up to navigate, and it'd be super sweet if I could make it to the bottom and just click what I need when I'm down there:

![screenclip](https://f.cloud.github.com/assets/4501321/1811493/3a5b7036-6e57-11e3-8560-2dfdeb988dff.png)

Having the Gems stick there too would be a bonus, because it's easier to make decisions about unlock purchases and so forth if I can easily see what my current balance is.
##

**Comment by lefnire** [comment]
Check out [rootCtrl.js](https://github.com/HabitRPG/habitrpg/blob/aa3767afd98c0fe0523d35439d2ad20c9b6ccd61/public/js/controllers/rootCtrl.js#L10tL14) if you're interested

**Comment by Aurornis** [comment]
It'd also be nice if the tabs under the main tabs were a drop-down instead.  It's irritating to have to load the tavern when I just want to go directly to my party, or having to go to the market first when I just want to change or feed a pet.

**Comment by paglias** [comment]
Edited to reflect that everything this is implemented execp tags

**Comment by lemoness** [comment]
We're thinking of doing a more thorough re-evaluation of site design in the future, and we can re-examine this at that time. In the meantime, I'm closing this ticket. Feel free to comment if anyone still feels strongly about this!
