### ISSUE TITLE
Interface Suggestions

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#213]
I have put in a lot of tasks and to-do's such that I have to scroll down to look at them all.  It would be nice if my little dude at the top of the page would be "frozen" in place on the screen so I could still see him and his experience/health when I scroll down.

Perhaps some of the lists could be grouped together so the total list size could be minimized.  Maybe like tasks under a larger project.  For example, I'm putting together several desks, tables, and chairs for my kids in the basement.  I could have a group "Basement Finish" and have subtasks under that list.  I don't need to see them all in the main list all the time, but when I'm home from work and I'm trying to remember the tasks I have to do, "Basement Finish" would be the only thing I'd need to see.

I suppose, also, there could be job-related tasks and home-related tasks.  Be nice to sub-categorize those so when I'm at work I'd collapse the home-tasks so I don't see them during the day.

**Comment by wc8** [comment]
Related:
Header Always Visible: #100 
Tags or Categories #48

**Comment by StanLindsey** [comment]
You're not the first to suggest these @Abednego =D

Vote for these issues on Trello at:
https://trello.com/c/mrbELa6J
https://trello.com/c/q7v02jAw

I'm going to close this issue for the sake of Housekeeping, but know we appreciate all feedback - even if its repeats as that just means the suggestion is important!
