### ISSUE TITLE
Spell tooltips don't show up on 75% zoom

### ISSUE THREAD

**Issue by krakzr** [HabitRPG/habitica#2132]
So I run Habit as a desktop app (through Chrome), and I generally have it as a half screen window and at 75% zoom. When I do that, the tooltips for spells (and sometimes rewards) get buggy.

I made a video to show it happening: http://www.youtube.com/watch?v=6xCmeIk1h_A

This may be a Chrome issue but I figure it can't hurt to let people know.
Also this is my first bug report so if this is in the wrong place or I need to tag it or something, let me know.

**Comment by SabreCat** [comment]
Old issue #399. I actually have a pull request out to fix it (#2083) but @lefnire needs to check it over before implementing it.
