### ISSUE TITLE
Can't log in to my account!

### ISSUE THREAD

**Issue by piratemonkey06** [HabitRPG/habitica#2133]
So I joined up yesterday, and I was going to log in just before and tick off my dailies, but the site says my account can't be found when I try to log in via PC, and that my account doesn't exist when I try to log in via mobile. Please help! I was really looking forward to using this app regularly :(  I was actually getting stuff done. I was lucky enough to have my habitrpg dashboard open in a tab from yesterday, here's a few screenshots from there:
The error message I'm getting (PC)
![image](https://f.cloud.github.com/assets/6264704/1812502/fe984f84-6e7d-11e3-9870-c91e638b8b54.png)
My dashboard (can't tick off any of my dailies as they're greyed out from the day before)
![image](https://f.cloud.github.com/assets/6264704/1812505/13a57672-6e7e-11e3-8749-03d96eabe8ff.png)
I have tried logging into beta.habitRPG instead; I still get the 'does not exist' message.
My username is screaming-in-lowercase.
Thanks!

**Comment by lefnire** [comment]
An unfortunate case of #2105, read up there and message me for some apology gems
