### ISSUE TITLE
friend can't log in?

### ISSUE THREAD

**Issue by plateny** [HabitRPG/habitica#2134]
So my friend had this error about a week ago where the page looked like this:
![untitled](https://f.cloud.github.com/assets/6267668/1812833/36b7536a-6e92-11e3-9dae-20d2d347a034.png)
And now she can't seem to log in, she just sees a big blue play button that does nothing when she clicks it, and there's no log in or sign up link on the habitrpg page.
Her habitrpg name is poobread, user ID is e0f53064-fc86-4ec1-a0e6-7ef75dc39224. She's already tried clearing cache and hard refreshing etc, I'm not sure what the problem is.

**Comment by lefnire** [comment]
Strange, I've looked at her record and everything looks fine.. Even tried
loading it up in my browser with success. Could you have her try a
different browser to see if that fixes it? If so, we'll need to have her
clear actually her localStorage, not her cache. Also see if there are any
JavaScript errors in Chrome Console. Will wait to hear back

**Comment by plateny** [comment]
Alright I'll get her to try a different browser and maybe clear her localStorage, will let you know once she does!

**Comment by plateny** [comment]
Okay she tried on every browser but she can't login, her email isn't being recognized. Also we're not sure how to clear localStorage, I know almost nothing about javascript.

**Comment by SabreCat** [comment]
@plateny: Email... you need to log in using your username rather than your email address, could that be the problem?

**Comment by plateny** [comment]
Ah actually she was trying to login from the blog instead of the actual site. However the problem with the actual site persists where when she clicks the play button, nothing happens, so she can't login still. Could this be an issue with localStorage and such? I'm not sure how to clear that though, what are the steps for that? Thanks for helping.

**Comment by lefnire** [comment]
have her try https://habitrpg.com/logout

**Comment by deilann** [comment]
If this is still an issue, please reopen with more info.
