### ISSUE TITLE
send UUID in server error logs

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2135]
(self task) send UUID along with uncaughtExceptions, so I can better diagnose issues. Also, server isn't currently emailing error 500s that are caught in process. Instead of `res.json(500,{err:err})`, we should be running `next(err)` and catching all errors at top-level express error handler, so we can email error to admin, and _then_ `res.json` error down to client.

Creating this ticket just to track some info. Possible express domains-based error handlers:
- [domain-middleware](https://github.com/fengmk2/domain-middleware): Using, seems to work well. Says it requires cluster in order to terminate processes, but from my testing it never actually terminates single processes, so we should be good.
- [connect-domain](https://github.com/baryshev/connect-domain): The most populate solution, but I simply couldn't get it working
- [node-domain-middleware](https://github.com/brianc/node-domain-middleware)

**Comment by lefnire** [comment]
Remaining task is to replace all instances of `return res.json(500,{err:err})` with `return next(err);`. I'll do that incrementally as I see them

**Comment by lefnire** [comment]
@paglias @litenull [this](https://github.com/fengmk2/domain-middleware) is a cool module, I think y'all will like it

**Comment by paglias** [comment]
Will definitively be very useful, hope it doesn't fill your inbox :)

**Comment by lefnire** [comment]
It most certainly does! All these errors I wasn't aware of, time for a
fixing spree

**Comment by paglias** [comment]
:+1: I'll try to catch up with everything happened in these weeks tomorrow!

**Comment by litenull** [comment]
Yeah this is really nice. Especially for HabitRPG! :))
kidding!
