### ISSUE TITLE
Option to "try on" gem restricted options for avatar?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2136]
Hi! I am thinking of buying some gems to support this great project and maybe customize my avatar a bit. I'm trying to make the avatar look like myself so I need some extra hair options.

However, it's very hard to get the idea of what my avatar may look like with the special clothing/hair/skins/etc. that I have to buy with gems. I'd like to be able to see how the different hair options actually look on my avatar before buying. Would be especially great for weird combos, like the winter hair sets plus the ponytails..have no idea how that is going to look.

Do you think a "try before you buy" could be added? I think it would give me and others incentives to purchase gems.
##

**Comment by lefnire** [comment]
I like the idea. I won't add it soon, since I've got a lot of of criticals on my plate, but note-to-future-self:

`mousenter` on customize-options, something like:

``` javascript
$rootScope._pref = User.user.preferences[pref];
User.user.preferences[pref] = newPref;
```

`mouseout`:

``` javascript
User.user.preferences[pref] = $rootScope._pref;
```

Don't use `User.set()` since it will send to the server, just use `User.user.xxx=yyy` since that's a non-permanent in-browser set.

**Comment by deilann** [comment]
i like

modals

so maybe

we could do a modal

with your avatar

and the option to buy (item) (set) (cancel)

**Comment by lemoness** [comment]
This is still something that would be useful!

**Comment by paglias** [comment]
We're going to implement this separately, not on the website directly
