### ISSUE TITLE
XP maximum exceeded

### ISSUE THREAD

**Issue by Nostos** [HabitRPG/habitica#2137]
Greetings.

I just received quite a lot of xp by casting "Burst of Flames" on one of my Dailies, which led me beyond the maximum insted of simply increasing my level. This was corrected automatically by doing another Daily, but my character panel temporarily showed this problem. Not a big deal, but I thought you might want to look into it.

Here is a picture of my panel before the last Daily: http://oi39.tinypic.com/f3c2tj.jpg.

As usual I tried to look for this problem on the forum, but could not find it among the issues, so I hope I'm not posting a duplicate...

Nostos

**Comment by colegleason** [comment]
Let's continue this on #2598, if you don't mind.
