### ISSUE TITLE
Popup on settings page

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2139]
Every time I open the settings page, a window pops up, saying that my password is succesfully changed (the same that pops up when I do click on submit). It doesn't pop up if I refresh the page, but it does when I navigate to it from another page.

**Comment by colegleason** [comment]
@lefnire Any thoughts on this? I'm digging around in the changePassword code, and there seems to be no reason it could be called other than on the form's submit function.

https://github.com/HabitRPG/habitrpg/blob/928f7cfdd7ebb3f746ccf238249c297e3f44b7ce/public/js/controllers/settingsCtrl.js#L68

https://github.com/HabitRPG/habitrpg/blob/3b3b0e6915fab78a12c3754ce2c061647b00212c/views/options/settings.jade#L56

**Comment by paglias** [comment]
will reopen If it happens again
