### ISSUE TITLE
Original Logon information

### ISSUE THREAD

**Issue by Cyberlyme** [HabitRPG/habitica#214]
Hi there, 

Apologies for this but I've been using Habitrpg for a few days now and loving it. Having just installed the chrome extension I was looking for my username to add to it. I couldn't remember exactly what I had used to set up the account and I couldn't see it anywhere so I logged out to try and log back in again.

Everything I tried to use gave me the username not registered error, having set up a new account I've noticed that the username comes up over the settings bar and this was blank originally.

Have I lost my original account? I would rather not start again but will do if need be.

**Comment by lefnire** [comment]
@Cyberlyme [email me](https://github.com/lefnire/habitrpg#email) your email address or username you used to sign up with, I'll look into it - you might have been victim to the recent instabilities :( (which are improving dramatically)

**Comment by Pandoro** [comment]
Has this been resolved?

**Comment by Cyberlyme** [comment]
Hi Pandoro, I spoke to Lefnire directly via email - I had lost the account so yes, it was resolved.

**Comment by Pandoro** [comment]
Okay, then I am closing this one :) Good you were able to figure it out :D
