### ISSUE TITLE
Time Travel in Chat

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2141]
So I'm in the social-tavern window, chatting - and the message I just typed immediately shows as "3 minutes ago". Sometimes the error factor is larger. I don't recall for sure if it's ever been negative, but I _think_ it has. Looks like you are using 2 different clock sources - perhaps the server _and_ my local clock. 

No biggie; just rather weird.

**Comment by paglias** [comment]
Could you check your clock is ok?

**Comment by ArlieS** [comment]
It's a bit off - it's claiming 15:19 right now, with my cell phone claiming 15:16.

**Comment by paglias** [comment]
Then it's definitively that, the time since is calculated based on the time difference from when the message was sent (on the server) and the hour on the client,

**Comment by ArlieS** [comment]
I disagree that this is not a (minor) bug. Printing the server time that messages occurred (converted to local time zone) would be clearer. Also, there seems to be a tendency for pages which _don't_ auto-refresh to express themselves in terms of "x minutes ago". Habitrpg doesn't _quite_ have this problem - the chat screens _don't_ auto-refresh, and the timers on messages already displayed _do_ auto-refresh (bizarre combo) - but it helps make them look as if they _do_ autorefresh, which is unhelpful.

**Comment by Aurornis** [comment]
I'm with Arlie.  Many a time in my party chat I've made a fool of myself posting about something, only to see that it was already covered by other posters hours ago, but as I didn't f5 first, I didn't see them.

**Comment by paglias** [comment]
I think you're talking about two different things:

@ArlieS -> the way the timestamp for messages in chat is shown
@Aurornis -> would like to have  the chat auto refreshing (anyway no need to f5, there's a sync button next to the Send button) and which is discussed in #1503 

Anyway I've reopened the ticket if you want to continue the discussion

**Comment by Aurornis** [comment]
Arlie said "the chat screens don't auto-refresh, and the timers on messages already displayed do auto-refresh (bizarre combo) - but it helps make them look as if they do autorefresh, which is unhelpful." which is what I was responding to, but I'll head on over to 1503 to air my grievances about the refresh button not working. :)

**Comment by paglias** [comment]
The refresh button isn't working? Any error alert is shown?

2013/12/28, Aurornis notifications@github.com:

> Arlie said "the chat screens don't auto-refresh, and the timers on messages
> already displayed do auto-refresh (bizarre combo) - but it helps make them
> look as if they do autorefresh, which is unhelpful." which is what I was
> responding to, but I'll head on over to 1503 to air my grievances about the
> refresh button not working. :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2141#issuecomment-31301560

## 

Matteo Pagliazzi - paglias.net

**Comment by Aurornis** [comment]
Nope.  No indicator it wasn't working.  I had cast three spells to attack trapper santa, and was expecting that at midnight my time it would've shown my damage like it did for a party member in an earlier time zone, but nothing showed after I hit refresh so I posted a theory that maybe santa damage was only tallied once when the earliest persons cron goes off (ended up not being the case).  Once that post was posted and the screen refreshed to reflect that, underneath my post, time stamped at the same time, was my dam...ag... oh.  ok, so maybe it does work and that was 'cause it doesn't tally my damage till I'm active...

...carry on! >_>

**Comment by paglias** [comment]
Ok, there's a sync button next to chat send button and that refreshes only the chat.

Then there's a sync button under the top right menu (in the header) and refreshed the user, for parties currently you have to reload the page to have a new version...

**Comment by paglias** [comment]
About last comment, sync chat button should update the whole gruop not only the chat itself

**Comment by Aurornis** [comment]
Just tried it and using the sync from the dropdown while in Party mode updates my stats, but not the chat feed.  Hitting the sync one by the chat feed refreshes the chat... so in the case of the party window, f5 is still faster, but the buttons work.
