### ISSUE TITLE
Boss status update shows negative damage

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2142]
Boss damage for our party is showing up as negative. Here are the status announcements:

```
<AxialGentleman> attacks <Trapper Santa> for 7.0 damage, <Trapper Santa> attacks party for -0.9 damage.  - 44 minutes ago
<mindsandthings> attacks <Trapper Santa> for 1.2 damage, <Trapper Santa> attacks party for 0.0 damage.  - 21 hours ago
<AxialGentleman> attacks <Trapper Santa> for 6.9 damage, <Trapper Santa> attacks party for -0.6 damage.  - a day ago
```

Since the numbers are so low, I can't tell whether it's actually calculating that the boss is doing negative damage, or whether the text just shows damage as a negative. If the latter, I think that's a confusing double-negative -- it should be either "attacks party for 0.9 damage" or "attacks party for -0.9 HP".

**Comment by lefnire** [comment]
Just visual/confusing. Pushed fix, will deploy with next batch of updates
