### ISSUE TITLE
Skills/Quest cause Experience (XP) to go over maximum without leveling up (Burst of Flames, Backstab)

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2143]
I Burst of Flames'd a daily and got around 70xp, which was added to my current xp total, taking me to 1182/1130. It seems the level-up check isn't being calculated for spells? I checked off a brand-new to-do, and was then leveled up and left at 67/1160.

_edit by admin:_

**Comment by lefnire** [comment]
Ah, spells don't trigger `user.fns.updateStats(newStats)`. will fix when I'm done with crits

**Comment by ArlieS** [comment]
Same scene, different spell. I look so cute at 2360/1850.

**Comment by deilann** [comment]
Fix proposed here: https://github.com/HabitRPG/habitrpg-shared/pull/136

**Comment by Alys** [comment]
In https://github.com/HabitRPG/habitrpg-shared/issues/329, freakinhippie suggests this fix:
**When casting the spell "spellWizardFireball", the reward of XP is applied directly by setting "user.stats.exp = ..." rather than using the API and calling User.set(...). The result is that when/if this spell is cast just prior to leveling up, the XP counter exceeds the limit and there is no level-up.**

**Comment by sadanyagci** [comment]
I experienced this bug while using Burst of Flames. I'm now level 16 with 435 / 360 experience points. What can I do about it?

**Comment by deilann** [comment]
The first post in this issue has a very large, bolded section on "What to do"

**Comment by sadanyagci** [comment]
Ah, ok. I somehow completely missed that.

**Comment by scheidm** [comment]
did this one just fall through the cracks? experiencing this issue as well, just noticed the fix posted october 2014. Did anyone try that and find problems with it?

**Comment by deilann** [comment]
@scheidm A fix was suggested, but a PR was never made.

I personally like the way it is right now, even though it's a bit unintuitive. Being a productivity site, it makes sense that you can only level up through a task.

Of course, that's probably also just my Stockholm Syndrome talking, and considering the number of bug reports submitted about it, we should probably fix it at some point. However, all bugs considered, it's rather low priority.

**Comment by lemoness** [comment]
I would definitely like to get this one fixed, as it's the source of a lot
of questions and sometimes bug reports.

**Comment by Alys** [comment]
FIXED!!!! Fixed fixed fixed fixed fixed!

https://github.com/HabitRPG/habitrpg/pull/4919

**Comment by lemoness** [comment]
Yeeeehaw!!!!!
