### ISSUE TITLE
Mounts make it hard to see weapons

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2144]
Most notably any dragon combined with many of the staves, but it happens to a lesser extent with many combinations, because avatars are right-handed, and mount heads are to the right. Possible solution: let player swap their avatar to be left-handed (or swap the mount to face right).

**Comment by SabreCat** [comment]
The dragon's head falls at a rather unfortunate spot for the avatar's face, too, covering up the rider's right eye:

![screenclip](https://f.cloud.github.com/assets/4501321/1817819/db7a0f04-6fc9-11e3-8c09-db935d523a2b.png)

**Comment by crystalphoenix** [comment]
ah, didn't realize i made a duplicate ^^;

in any case, how are the mounts aligned within the avatar? the sprites arn't a part of spritesmith so i'm not sure.
are they also by the upper left corner?

**Comment by lefnire** [comment]
They're not currently part of spritesmith, it was the last thing I had on my todo-list for converting to spritesmith

**Comment by Alys** [comment]
Closing because this is probably best handled as a request in the art trello board, and the spritesmith information is outdated.
