### ISSUE TITLE
Died While Resting

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2146]
I put myself in the inn, saw that I was resting, came back, and it said I died! :(

**Comment by SabreCat** [comment]
When did you check in to the inn? If it was around the 24th-25th, you probably ran afoul of the database rollback we had to do around that time: #2105

**Comment by deilann** [comment]
Yeah, someone in the Tavern mentioned it to me. It was definitely during
that period of time. :)

**Comment by SabreCat** [comment]
OK, I'll close this ticket then. Use "Fix Character Values" in Settings to put yourself back together, and contact admin@habitrpg.com if you lost any Gems (or Gem-purchasable stuff like drops).
