### ISSUE TITLE
Can't join quest

### ISSUE THREAD

**Issue by m0xf4240** [HabitRPG/habitica#2149]
My party started the Trapper Santa quest, and there doesn't seem to be a way for me to join or accept. I'm not listed under the Participants section, and I have a button to Abort the quest for my whole party, but no way to Accept.

**Comment by lefnire** [comment]
For now you gotta wait for them to finish, then you can start a new one with them. I'm working on allowing late-joiners, new party members, etc- but that'll be a couple weeks out

**Comment by m0xf4240** [comment]
cool. thanks.

**Comment by Otocinclus** [comment]
I'm in the same boat as xenakaaii :( Except I started the quest in a party by myself and quit to join a different party and have a better chance to finish it... soooo now I can't do it at all? Or could we restart it with someone else's scroll? Are there any workarounds?

**Comment by lefnire** [comment]
The quest-leader can abort the quest, which will return the scroll to their inventory. They can then re-invite everyone and start over. IMO, just wait for them to finish and do it again next round
