### ISSUE TITLE
Burst of Flames is OP on bosses

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2150]
On Thursday, I did 27 dailies and 21 to-dos, and cast burst of flames once, for a total of 116.8 damage to the boss.
Yesterday, I did 28 dailies and 24 to-dos, and cast burst of flames three times, for a total of 346.8 damage to the boss.

I don't think this is as intended! Note that I was casting BoF on blue dailies with streaks in the 30-42 range. 

Personally, I'd like to see the damage on blue dailies and yellow to-do's raised, and BoF solidly nerfed. I'd rather be motivated to task the boss to death, not blast it there.

**Comment by lefnire** [comment]
I probably won't have time to fix this any time soon, hopefully someone else will be able to [look at the numbers](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L222tL225). It's very likely the `crit()` function crits too high.

**Comment by lefnire** [comment]
see [this commit](https://github.com/HabitRPG/habitrpg-shared/commit/bb5fe9c6e57e06ea3eb73c051893320a354448fb#diff-652dbbf3d459e90a3de1a122c063bb6bR225), temporary measure. Need something better

**Comment by lorian** [comment]
If I'm reading that correctly, then boss damage should be about a 10th of the xp value gained from BoF, in which case my BoF on a 51-streak daily would do about 15 damage to a boss. That's about the same level of damage as people my level seem to get for the whole day (10-20 seems to be a common range). On the other hand, that means it would take 200 mana to one-shot the boss, which would be basically my entire mana bar. That feels kind of reasonable.

**Comment by lorian** [comment]
Ok, so with my usual amount of dailies and to-dos, and two casts of BoF, I did 44.5 damage to the boss, which seems like a much more reasonable number. Temporary measure seems fine to me.
