### ISSUE TITLE
Mysterious "2 more members" on party members list

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2151]
This is a follow-up to #2147 (booting now works). After removing 2 members from the party, I now have a party list that has: my name (as a blue button), names of ALL other members (as clickable links and option to boot them) and a mysterious, grey button (unclickable, looks like my own name, but is grey) saying "2 more members". List of invites is just underneath this thing. Any ideas? Some kind of relic from the times the party was larger?

**Comment by lefnire** [comment]
it just has a cap on member lists, because some guilds were in the thousands and it was causing browser crash. We have a task for ourselves to click that button to load 50 more incrementally,  but it's pretty low-prio given the other things on our plate
