### ISSUE TITLE
Party Challenges No Longer Visible In Party Chat

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2152]
I now have a new 'Quest Invitation: Trapper Santa' on the sidebar of my party chat, but I am no longer able to see the party challenge I made in the party chat (despite being the owner of the challenge, and not closing it.) I can still see it if I go to the Challenges tab.

**Comment by lefnire** [comment]
refresh or a "sync chat" fix it?

**Comment by JennaMalkin** [comment]
Yes, that fixed it! :)
