### ISSUE TITLE
Flip Mounts?

### ISSUE THREAD

**Issue by crystalphoenix** [HabitRPG/habitica#2154]
with the current avatar composition, there's a lot going on to the left of the character. that is currently where the pets, the mount's head, and the main weapon are placed. by comparison, the right side of the character tends to have a shield, or at most one of the late rogue weapons. i think flipping the direction of the mount would balance out the avatar composition. it would also help with actually seeing the main weapon since mounts like the dragon and wolf seem to block a lot of that off. 

alternatively, i think i remember someone suggesting that there be "dismount" version of the mounts where the character can stand beside their steed instead of riding it. it might still be a good idea to flip the mount in this case anyways because of the space the main weapons tend to take.

**Comment by SabreCat** [comment]
That'd be sweet! This is a suggestion for fixing #2144, let's proceed with further conversation there.
