### ISSUE TITLE
Stealth is the only spell that doesn't stack (Bug? Feature needing documentation?)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#2156]
While looking through the spell definitions in content.coffee, I noticed that the Stealth spell has its buff defined with "=" like this:
    user.stats.buffs.stealth = Math.ceil(user._statsComputed.per \* .03)
whereas every other spell has its buff defined with "+=" like this:
    member.stats.buffs.per += Math.ceil(user._statsComputed.per \* .03)
I.e., you can cast all spells multiple times each day for a larger effect, except for Stealth - if you cast that more than once, then every casting except the final one is wasted.

Is that intended? If so, it's probably worth mentioning it in the spell description. I know that would add bloat to the description, but I think it's important to mention to prevent people wasting their MP. Perhaps you could add flavour by phrasing it something like "Cast this spell only once per day otherwise your extra magic usage will attract attention, cancelling out your stealthiness!". Or something. :)

(P.S. I LOVE habitrpg!)

**Comment by Alys** [comment]
After poking around further, I found this change, with a note implying that Stealth is overpowered:
    https://github.com/HabitRPG/habitrpg-shared/commit/7c39f8c4e37c7acb8231e40b92ac8e348c3cfe1a
So perhaps "=" was intentional, as "+=" would just be too powerful. But I'm still thinking it should be indicated in the spell description, and even more so in a comment in the code to prevent other code newbies from asking the same question. :)

**Comment by lefnire** [comment]
Actually, I don't see a problem with stacking stealth. It's a pretty costly spell, so if if they have the MP they deserve the stack (IMO). Will fix

**Comment by Alys** [comment]
Yay! Thank you! :)
