### ISSUE TITLE
iPhone app seems to use different math than website for HP loss, XP gain, possibly more

### ISSUE THREAD

**Issue by TheOfficePicnic** [HabitRPG/habitica#2157]
I checked off a Daily just now using the (updated) iPhone app and got 20 XP. That seemed higher than it should be, so I opened the website, and a notification appeared in the top right saying I had gained 10 XP. 

Similarly, my wife was using the iPhone app all day today, and she checked a negative habit, which took 20 HP away (and subsequently caused her to die unexpectedly). I restored her account to its pre-death state using the settings options on the website, because there is no reason she should have lost 20 HP for a single negative habit.

Both of these oddities are making us reluctant to use the iPhone app for now, so I wanted to raise the issue and see whether there is indeed a difference in the calculations being used for the two portals.

My UUID: aaa08944-1e22-41ae-8b60-e52a4521142d

**Comment by lefnire** [comment]
upgrade the app, 0.0.15 should be live now (with updated math)

**Comment by TheOfficePicnic** [comment]
Ahh, I didn't realize there was already a fix launching. I'll update to 0.0.15 when I see it in the app update list, but it hasn't appeared for me yet.

**Comment by lefnire** [comment]
Are you on 0.0.14 currently? Looks indeed that 0.0.14 is the only available one in the store, though I got the "0.0.15 launched" email, let me see what's going on

**Comment by TheOfficePicnic** [comment]
Yes, I'm on 0.0.14 currently. I upgraded to that on Dec. 26.

**Comment by lefnire** [comment]
Hmm, something got lost in the pipes then. I just re-submitted 0.0.15, keep an eye out in coming days

**Comment by cinemafreak** [comment]
I can't figure out what version of the IOS app I have, but I don't recall seeing an update since before Christmas.

**Comment by lefnire** [comment]
Don't know what happened as I have the 0.0.15 "ready for sale" email. Checked the app-store to verify (due to this ticket), still on 0.0.14 :o . Anyway, I resubmitted 5days ago and I got another "ready for sale" email late last night, finally [looks to have stuck](https://itunes.apple.com/us/app/habitrpg/id689569235?mt=8) so do an update now and you should be good

**Comment by cinemafreak** [comment]
I got it!  Thank you so much for the help.  I do just wish I could get my 400 gold back though.

**Comment by lefnire** [comment]
Options > Settings > Restore Character Values > enter 400 GP

**Comment by cinemafreak** [comment]
Ah, I hadn't seen that feature.  Thank you very much.
