### ISSUE TITLE
Function suggestion: Require party members to be out of the Inn to receive quest rewards.

### ISSUE THREAD

**Issue by TheOfficePicnic** [HabitRPG/habitica#2159]
My party just defeated the Trapper Santa quest. One of my party members accepted the quest, but was in the Inn the entire time we were "fighting" Trapper Santa. I don't believe he was able to do any damage to TS while in the Inn (he says he checked off some To-Dos while in the Inn, and I didn't see any system message in chat that he did any damage), but I also don't think he lost any HP overnight while the rest of the party did.

Essentially, he was able to risk nothing and still receive the full benefit of the quest reward. That doesn't really seem to be in line with the spirit of the quest feature, so I wanted to bring it up as a discussion point as the quest system is built out.

**Comment by lefnire** [comment]
Follow on https://trello.com/c/VPPjVRlF/212-quests-bosses . This, and many others, are some Quests to-dos on the list.
