### ISSUE TITLE
List of Habits I've completed today

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#216]
So there's Habits I can click on.  One of the defaults, "1h Productive Work" I like, so I left it.  I even have a stopwatch to tell me when I get to one hour, heh.  Problem is, I can't tell if I clicked it or when I clicked it.  I may have clicked it before lunch, but given how forgetful I am I don't know if I did nor not.  So I clicked it again.  Might be cheating myself.

Us ADD folks need to know what we've already clicked on, and what time we clicked on it, for Habits.

Thanks!

**Comment by StanLindsey** [comment]
Good idea, a little display that shows how many times you've upped/downed today on the task would be good.
I've added this to Trello, thanks for the suggestion!
https://trello.com/c/h0pezwDR
