### ISSUE TITLE
Can't reassign Guild leader

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2160]
Because the list of Guild members is dramatically truncated, I don't have the ability to assign Guild leadership to the person I'd like to. Any chance this can be done from the database side in the meantime?

Group ID: 0379d34a-754c-4ff4-9020-5762cecb1d67
Leader-to-be: 3a168da9-f7af-409e-8c6e-2826e16fbf82

**Comment by lefnire** [comment]
√

**Comment by lefnire** [comment]
er, still a feature to solve

**Comment by SabreCat** [comment]
Ah, I could've sworn that issue was already documented somewhere else, but if not, cool 'nuff!

**Comment by paglias** [comment]
related with #1806

**Comment by lemoness** [comment]
Still having this issue, unfortunately.

**Comment by lemoness** [comment]
EDIT: And the fix hasn't been merged yet, so of course it is still happening! Ignore this.

**Comment by Alys** [comment]
I'm closing this since it's covered by https://github.com/HabitRPG/habitrpg/issues/1806 "Need way to expand/search guild members list - can't assign new leader or boot member when member isn't listed"
