### ISSUE TITLE
Incorrect HP Loss from Quest Boss

### ISSUE THREAD

**Issue by ArcaneOre** [HabitRPG/habitica#2161]
The new quests are interesting - but I've noticed that what damage the boss takes doesn't match the HP you get from your Dailies, and varies wildly from day to day even when you've done the same things and your dailies are all in the same color zone. 

For instance - yesterday I was in a different level - today I'm 400 points through the level between dailies and To-Do's, and the boss has never taken more than 27.7HP loss in a day and so far a total of 65 points loss over 3 days - obviously nowhere near matching the 400 or so points I've gained over the past few days. So wtf? It's kind of annoying since I pushed myself to complete tasks so I could complete the quest before it's gone!

**Comment by lefnire** [comment]
The boss doesn't take the same amount of damage as the Exp you gain, he takes the `task.value` difference (called `delta`) you've dealt to a Daily / Todo. Exp is roughly 10-15x that. `delta` is usually between 1-5 (increased by `task.value` aka redness, `user.stats.str`, `task.priority`, etc). 

You're gonna want to [find a group](http://community.habitrpg.com/forums/lfg) to fight the boss. Social accountability is the [primary purpose of bosses](http://blog.habitrpg.com/post/71529752833/keep-new-years-resolutions-fight-bosses). We killed ours in ~2 days with a skeleton crew of ~7. If you still think the math is wrong, take a peek at [the code](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L695TL698) and tell us if you spot anything off

**Comment by ArcaneOre** [comment]
Unfortunately - while I like your site as it keeps me on tasks, I know nothing about coding, only what information is shown on the task - which doesn't mention the difference between EXP gain and Attack on the Boss. It is discouraging and frustrating to know that even though it mentions that a single person can take on a boss if they so desire - that you are forced to partner with 6 other people to actually be able to complete such a thing. 

I appreciate the site you've created. Good info to know that it's not possible for one person to take on and participate in boss fights. Would have been nice to know earlier if you're not a coder.
