### ISSUE TITLE
API doesn't return max mana

### ISSUE THREAD

**Issue by russtaylor** [HabitRPG/habitica#2163]
API calls don't return the user's maximum mana, which makes it impossible to display an accurate bar showing the user's mana level.

**Comment by lefnire** [comment]
Which routes would you like it on? Easy to add. Incidentally, what'cha building?

**Comment by russtaylor** [comment]
I'm not sure about other routes, but I'd at least like it on the GET user route. I'm not currently sure if it'd be useful elsewhere, as I'm not super familiar with the rest of the routes yet.

I'm working on revamping the Chrome plugin, as its bugginess has been getting on my nerves a bit! I'm hoping to get it to a much more stable & user-friendly state.
