### ISSUE TITLE
Issues with markdown in task titles

### ISSUE THREAD

**Issue by progenitus** [HabitRPG/habitica#2165]
When writing a task title that begins with a number followed by a period (like "40.") or with a # it now triggers markdown formatting where it didn't before. This causes all numbers to show up as 1. in front of the title, and titles beginning with # are now huge. Having markdown in task titles caused me a lot of confusion before my brother explained why it was happening. Hope this helps. Have a nice day!

I'm using firefox 20.0 and my user ID is 704f08da-b19a-4880-8507-126554601651

**Comment by lefnire** [comment]
You can escape numbers with \ , eg `#before` => `\#after`. I think # -prefaced task titles might be pretty rare, but what's your recommendation for handling this? remove # from the supported markdown tags? That's doable. We don't want to remove markdown altogether, since I think people are getting some benefit from it (primarily from Emoji, and for myself from links)

**Comment by progenitus** [comment]
Escaping with the \ doesnt't work. I can still see the \ in the task title.
It makes sense not to worry about the # though, and I see the value of
markdown especially with links. Thank you for your quick reply.

2013/12/29 Tyler Renelle notifications@github.com

> You can escape numbers with \ , eg #before => #after. I think #
> -prefaced task titles might be pretty rare, but what's your recommendation
> for handling this? remove # from the supported markdown tags? That's
> doable. We don't want to remove markdown altogether, since I think people
> are getting some benefit from it (primarily from Emoji, and for myself from
> links)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2165#issuecomment-31321269
> .

## 

Mvh. I. T. Hammar
www.ithammar.com - www.facebook.com/ithammarkunst -
www.facebook.com/gallerikunstgress

**Comment by wc8** [comment]
@progenitus another option would be to use code markdown. You’d get `code` formatting but at least not the `\` or the incorrect number.
@lefnire should we just note this in the wiki and close this ticket?

**Comment by lefnire** [comment]
The code markdown gives it a [pretty good style](http://gyazo.com/15b1bb6dd133ee672402ffdd7ee4c3a2) too. Yeah, a wiki should be sufficient

**Comment by lefnire** [comment]
incidentally the backslash is [working for me](http://gyazo.com/039c40fbfce9c14f398b2b0fdfe33c71)
