### ISSUE TITLE
count of "Mounts Tamed" includes rare mount (gives inconsistent count / total)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#2169]
On the Mounts page, if you have a rare mount (e.g., from the Trapper Santa quest), then it is included in the count of mounts tamed. For example, I have two normal mounts (created by converting pets) and one rare mount, and the page says I have "3 / 90 Mounts Tamed". It should be either "3 / 91", or "2 / 90" which would be consistent with how "Pets Found" is reported.

This is about as low priority as it's possible to get. :)

**Comment by deilann** [comment]
I believe lorian has fixed this.
