### ISSUE TITLE
Progress Suggestion

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#217]
could there also be a progress graph saying how much experience you got per day, in addition to score, because when I first started HabitRPG i set rewards prices pretty fairly, but after a while of using HabitRPG i've added a lot more things to it and now i can get 4 of my rewards every day, so could there be an additional history graph that shows my daily Exp/Gold intake

**Comment by StanLindsey** [comment]
I've moved this item over to Trello as we already have a card on the subject of progres views: https://trello.com/c/h0pezwDR

Thanks for your suggestion and for using HabitRPG =D
