### ISSUE TITLE
Tags think they are other tags

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2170]
I can't even figure out what the pattern is, but some of my tags think they are other tags. For instance, my first tag is convinced it is my 5th tag, to the point of renaming itself after my 5th tag. Also, attempting to delete the 5th tag instead deleted the first tag. Now deleting any tag instead deletes the first tag in the list.

This started happening after I deleted all my tags, including my active challenge tags.

Edit: Aha, I think the weirdness had to do with using ":" in the tag name! I deleted all of them, they all came back (with duplicates), and I renamed everything to not have ":" in the name, and now they appear stable.

**Comment by SabreCat** [comment]
Whoa! Nice find!

**Comment by lefnire** [comment]
is it https://github.com/HabitRPG/habitrpg/issues/940 ?

**Comment by lorian** [comment]
I don't know; I didn't try selecting any of them during the weirdness, and now I can't recreate the behavior :(

**Comment by deilann** [comment]
I had this exact issue at one point in time and it was also related to the colon.

**Comment by Alys** [comment]
Does anyone know if this still happens?

**Comment by paglias** [comment]
I think we can close unless it happens again
