### ISSUE TITLE
Tags from finished challenges don't clear out

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2171]
This isn't something that's too horrendously annoying, but I've been noticing that the tag filters from challenge-related tasks that have been completed and removed still hang around, and I have no way to remove them. Specifically, in the screenshot, I dropped out of the 'Music' challenge over two weeks ago and the 'Christmas' one was completed around that time.

UID: cca60406-1b8f-496e-af77-cd19df77c895

![screen shot 2013-12-29 at 4 47 34 pm](https://f.cloud.github.com/assets/6208739/1820136/ea999fcc-70d2-11e3-8359-b82270f3f640.png)

**Comment by SabreCat** [comment]
No way to remove them? You can't click the pencil icon at the left there, and X them off? I'm pretty sure I did that with at least one of my completed Challenges.

**Comment by casicastiel** [comment]
Oh, that's what that thing is! Christ, I'm an idiot.

**Comment by SabreCat** [comment]
Not at all! Could be a clue we need to make that feature more obvious.

**Comment by casicastiel** [comment]
I suppose I was under the impression that the tag filters would automatically reflect the tags I had added to tasks, and that once the last task with a particular tag was deleted that the filter would be removed.
