### ISSUE TITLE
Trapper Santa vanished

### ISSUE THREAD

**Issue by storian** [HabitRPG/habitica#2178]
I was signed up for Trapper Santa and it seems to have vanished from my profile.

**Comment by storian** [comment]
And now it's back.  Sorry for the noise.

**Comment by lefnire** [comment]
what's your UUID? you might belong to multiple parties (bug)

**Comment by storian** [comment]
I'm only in one party, by myself, which I created in order to quest.  But
my uuid is 062e4a2a-9176-4b11-8d07-f6950c1b429e.

**Comment by lefnire** [comment]
one party indeed.

Another thing that could have happened, when you create your party initially, you'll need to do a refresh before starting the quest. It's benign, you'll still have your scroll & such, and I'm working on fixing this.

Re-open this if you experience again
