### ISSUE TITLE
Bogus "Class Equip Bonus"

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2181]
(aka "oops I broke it")

My character is showing all sorts of Class Equip Bonuses that don't add up:

![screenclip](https://f.cloud.github.com/assets/4501321/1822198/fba74b7e-7155-11e3-8eeb-2f6085e39e26.png)

Beats me what's happening here, the math is pretty trivial. I'll take a closer look later, but thought I'd send this in case a keener eye spots the goof first.

**Comment by SabreCat** [comment]
Oh, it looks like it's missing the allocated stat points. I'll add a fix for that to #2177.

**Comment by lefnire** [comment]
Was just about to send you an email "you've proven yourself, don't be afraid to hotfix / small-change directly do `develop`"

**Comment by SabreCat** [comment]
Oh, I will be afraid. But point taken, I'll work myself up to it!
