### ISSUE TITLE
Double-clicking in task edit fields closes the task

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2184]
If I double-click a word in my task title or notes (a common shortcut to highlight an entire word for deleting or replacing), the task collapses. While this might train me to better stick to my keyboard for efficiency's sake, it doesn't seem intentional.

**Comment by lefnire** [comment]
intentional, see https://github.com/HabitRPG/habitrpg/commit/e3458194533b0efcd857c73f11724fc64fbde01d . Was brought up on the checklists branch since dropping into edit to click off checklists will be common. We'll want to add keyboard shortcuts a la Trello eventually

**Comment by SabreCat** [comment]
:-1: Dislike! Is there any chance of having the double-click work elsewhere on the task, but not in active text fields? :\

**Comment by lefnire** [comment]
[A poll!](http://community.habitrpg.com/content/double-click-task-toggle-edit-mode-see-betahabitrpgcom)

**Comment by lefnire** [comment]
Sorry man, I'm dumb :/

**Comment by SabreCat** [comment]
Hah, fantastic! Sorry about the confusion, I should've taken a screenshot to clarify what field I meant!
