### ISSUE TITLE
Calendar falls underneath rewards

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#2187]
When you pop up the calendar in Chrome Mac, the right edge falls underneath the .task <li>s in the Rewards column, even with my browser window full width (on MBP 15" Retina). I can see that the z-index of the calendar is already set to 1000, but since this only affects it in the context of its container, I think what we need to do is ensure that the To Dos container has a higher z-index than the Rewards container. (I played with this briefly but there's some complexity in the interplay of z-index values for various elements, so it needs more time than I have right now. I suppose I should meet my end-of-year client deadlines before I fix Habit, sigh.)

**Comment by zoebeagle** [comment]
I accidentally just wasted a bunch of mana trying to "Close" the calendar.  Maybe it would beneficial (even without the display issue) to verify the user actually wants to cast a spell/use a skill?

**Comment by quin-jay** [comment]
This was fixed with #2810, so perhaps this thread can be closed now?

**Comment by deilann** [comment]
Yay I like closing things!
