### ISSUE TITLE
Deleting removes wrong To-Do item

### ISSUE THREAD

**Issue by trueskawka** [HabitRPG/habitica#2189]
Hi.

I wanted to delete some of my old To-Do's, but instead of the one I clicked it deleted a completely different one. When I tried again, it deleted the item next to the one deleted before.

Cheers.

**Comment by lefnire** [comment]
Is this mobile only?

**Comment by deilann** [comment]
Your commit said that it fixes this ticket, which is why I closed it.

**Comment by lefnire** [comment]
Oh, roit. (sorry, on mobile..my recent comments are probably weird and
uninformed)
