### ISSUE TITLE
Long checklist items are truncated

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2190]
Tried to translate one of my routine-style Dailies into a checklist, and ended up with this:

![screenclip](https://f.cloud.github.com/assets/4501321/1823413/94e55d9c-717b-11e3-8083-4b8cfe9695ef.png)

The field should stretch to available space and wrap when it runs out, not chop off the text.

Related to #2183.

**Comment by lorian** [comment]
Related bug: when you're entering a long checklist item, sometimes it doesn't scroll back to the beginning of the line when you hit enter, turning "Determine point system for valuing tiles" into "mine point system for valuing tiles" until you manually scroll back to the start of the line.

**Comment by ghost** [comment]
Observation: I noticed today using iOS Chrome that if I changed the orientation of the iPad and then changed it back that the truncated checklists now wrapped properly. Don't know if that helps troubleshoot or not but thought I'd add it anyway.

**Comment by DexOfTheWild** [comment]
Changing the element from input to textarea could easily solve this.

**Comment by deilann** [comment]
It wraps for me now? If it's not wrapping for others, please reopen.

**Comment by SabreCat** [comment]
The box doesn't wrap while editing, but once you finish entry it looks OK.
