### ISSUE TITLE
Checklist items and tags aren't aligned to left edge

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2192]
Firefox does the following for checklist items and tag list:
![checklistscreenshot2](https://f.cloud.github.com/assets/2963633/1824565/f9277ca8-719a-11e3-9957-6d6c71ef1a81.jpg)

![checklistscreenshot](https://f.cloud.github.com/assets/2963633/1824558/cd8416b0-719a-11e3-9244-8baf07e13415.jpg)

It's done it since I started using Habit in May, through all intervening Firefox versions to 25.0, and did it under both Windows and Ubuntu. Frankly, I thought it was intended behavior!

**Comment by SabreCat** [comment]
Weird! I'm on Win7 Firefox here, and have never seen that behavior. Do you have a browser theme or script you're using? Those checkboxes look different than I'm used to.

**Comment by lefnire** [comment]
@lorian how good are you with Firebug / Chrome Console? Since we can't replicate on our machines, I'm wondering if I could throw some in-browser code ideas for you to try out?

**Comment by lorian** [comment]
@SabreCat I have lots of weird extensions running, but no scripts on the habit page. Only general browser appearance change I have are Personas, which afaik don't change anything other than pretty colors.

@lefnire Haven't used Firebug before, but I can get it, and if you throw me code bits, I can poke them and see what happens.

**Comment by lorian** [comment]
AHA! It's because I have the habit window zoomed out (or whatever ctrl +/- does to the text). I'm maybe 4 ctrl- clicks in from what I think is the default, comparing to what I get in chrome (god, the default text is HUGE). The alignment is correct for most of the zoom, but gets the neat staircase effect after some number of zoom outs.

Here's a screen shot at one zoom tier before the one with the staircasing:
![checklistscreenshot3](https://f.cloud.github.com/assets/2963633/1824727/e991d2b2-719e-11e3-8e12-b931347f000d.jpg)

(zoom doesn't cause the same problem in Chrome, fwiw)
