### ISSUE TITLE
Checklists: Click X/Y badge to unfold checklist

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2198]
I see we've got a user preference now for inline checklists. But honestly, I don't like it either way--I want to see inline checklists for individual tasks when I want them, not always all or always none. And I don't necessarily need all the editing functions at that same time, so I'd rather not open up the task for editing.

What about adding an `ng-click` event on the `span.badge` that flips out/closes the inline checklist? Maybe that'd work? (I only got that far, conceptually, before my Angular-fu ran out, haha)

**Comment by wc8** [comment]
:+1: expand/collapse—ideally, _remember the way I left it_. 
If hrpg can’t remember the way I left it, then, on refresh, default applies (e.g. inline).

**Comment by SabreCat** [comment]
We'd need to add a data element to tasks to set and save their checklist collapse state, methinks. Maybe not a bad idea!

**Comment by lefnire** [comment]
how's this: https://github.com/HabitRPG/habitrpg/commit/77c67775062b7be37ccc1e1bad3316d11f5be764 (check beta in 5m)

**Comment by SabreCat** [comment]
@lefnire: Hmm, not what I had in mind. I meant clicking the progress badge, to change whether or not the checklist displays _outside_ of edit mode:

![screenclip](https://f.cloud.github.com/assets/4501321/1828584/1900d34e-725e-11e3-8768-f1f2da67ff39.png)

So with this task not in edit mode right now, I'd click "0/2" to put away the checklist, and click it again to bring it back to the state you see above.

**Comment by SabreCat** [comment]
This works, but it's a hella lot of clicks to accomplish compared to what I had in mind, and doesn't offer much advantage over just opening the edit mode when I want to check things off.

**Comment by lefnire** [comment]
√ beta

**Comment by SabreCat** [comment]
OMG so very yes. :heart: With little "push me" cursor and everything. Thanks man, closing!
