### ISSUE TITLE
Logged as another user

### ISSUE THREAD

**Issue by strasznyobibok** [HabitRPG/habitica#22]
After creating second account for my girlfriend (on the same computer), I've noticed some strange behaviour. She can log in with her credentials, but the username displayed is "[Edit: removed to protect user]" (it is not her username). We tried to create another account and the bug repeated.

**Comment by lefnire** [comment]
Oh wow. So every time you try to create a new account it logs you in as that user? Are you using Facebook reg, or uname/pw? This is pretty dire, I'm making this top priority right now.

**Comment by strasznyobibok** [comment]
My own account works just fine (diplays my username), but everytime when my girlfriend logs in with her account (at this time she has two accounts, both have the same bug), there is "[Edit: username removed for privacy]" displayed. We don't use Facebook, just a normal register uname/pw.

-- EDIT
Oh, I've almost forgot. Both accounts started with only 30hp.

**Comment by lefnire** [comment]
@strasznyobibok, could you [email me](mailto:tylerrenelle@gmail.com) her usename that I might diagnose? FYI, the module I'll be working on to fix this is [derby-auth](https://github.com/lefnire/derby-auth)
