### ISSUE TITLE
Can't Login After Password Reset

### ISSUE THREAD

**Issue by J-Mind** [HabitRPG/habitica#2200]
I reset my password and when I now try to login it says: "Incorrect Password". I tried to reset my password twice more but the same problem reoccurred.

**Comment by lefnire** [comment]
Hmm, can't replicate on the site. So, you're doing:

Play > Forgot Password > Email New Password > (attempt login copy new password received from email) 

And it's telling you incorrect password? What's your UUID / email / whatever-you-have-handy

**Comment by J-Mind** [comment]
Thanks for replying. Yeah, that's essentially what's happening.  My email is: james.g.hofman@gmail.com

**Comment by lefnire** [comment]
@J-Mind can you try logging in with facebook? For some reason change-password is showing for facebook-registered users, so I have a hunch you're facebook-registered and was getting that dialog even though it doens't do anything for you

**Comment by J-Mind** [comment]
Ahh, I'm able to log in with Facebook. I used the same email for both a Facebook and a non-Facebook account, but I wasn't actively using the Facebook one. So it's caused some type of confusion? If I deleted my Facebook linked HabitRPG account would the password reset problem still occur for my non-Facebook account?

**Comment by lefnire** [comment]
@J-Mind were you able to get this sorted? I was looking through the error logs, and _many many_ users logged in through facebook were attempting password resets. I hid the field for facebook registrants, so and the errors stopped coming in. 

Are you able to get into your accoutn?

**Comment by deilann** [comment]
J-Mind please reopen this if you need further assistance.

**Comment by llagerlof** [comment]
I am trying to retrieve my password too. Reset password is not sending me any email (the alert window tell me the email was sent). And I not have facebook.

**Comment by lefnire** [comment]
@llagerlof can you give it another shot? This is a recently common issue, but it's very intermittent (works sometimes, not other times). I'll be diagnosing shortly

**Comment by lefnire** [comment]
actually, let's follow on #3306
