### ISSUE TITLE
Cannot Remove Absurd Hats

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2204]
Either this is a bug or the best prank ever.

You cannot remove the absurd hat once purchasing it, as it auto-equips.

Because it is its own category (special), you cannot equip less than one item per category, and there are no other special items, you cannot unequip the Absurd Hat.

I am using Chrome, 31.0.1650.63 m, Windows 7, and am primarily on the beta build.

**Comment by lefnire** [comment]
can't replicate, I'm able to de-equip. To un-equip completely, top-row (Base) - empty head icon. Are you wearing a costume?

**Comment by deilann** [comment]
Nah, I just didn't think to dequip helm. I'm not awake enough. Don't mind me.

**Comment by lefnire** [comment]
You'll be less awake tomorrow ;)

**Comment by SabreCat** [comment]
Related: #2208
