### ISSUE TITLE
Missing Ultimate Gear achievement

### ISSUE THREAD

**Issue by chadschultz** [HabitRPG/habitica#2206]
I've been on HabitRPG for some months. I had the best gear available, then when classes became available, quickly upgraded to the best Mage gear (I had a lot of gold laying around).

I looked at my achievements today and noticed that I never was awarded the Ultimate Gear achievement.

After looking at #1543 and #2100 , my guess is that buying the gear didn't trigger the achievement due to #2100 , and then checks were never ran after the fact to award the achievement to those that didn't get it, but should have?

My user ID is e7c9f489-4995-4448-b585-937712834bd8
I have the Royal Magus Robe, Royal Magus Hat and Golden staff equipped.

**Comment by lefnire** [comment]
give that a whirl

**Comment by chadschultz** [comment]
Set, thanks! Hopefully nobody else has this issue.

**Comment by lefnire** [comment]
There might be, but it's somewhat a self-healing bug because if they lose a piece and re-find, it will re-calculate. Or if they switch classes and max the gear, etc. But I'll manually set for any users who need

**Comment by Ephiarsis** [comment]
Same problem for me. Bought golden sword, golden armor, golden shield and golden helmet, but the achievement for ultimate gear wasn't triggered.

Maybe it's because I'm wearing the "Golden Wings" as well? (February surprise package)
Another thing is that I can't take these wings off.

My user ID is 9ef8acb6-4278-48e4-b479-ea3031329e85

**Comment by deilann** [comment]
From what I know about how the achievement works, the golden wings shouldn't do anything. To remove them, you need to go to the top and click "No Back Accessory"

**Comment by Ephiarsis** [comment]
Doesn't change the fact that I didn't receive the perk.
Maybe because I was resting in the inn?

**Comment by deilann** [comment]
Sorry -- not trying to discredit your ticket. Trying to rule things out and let you know how to remove the wings.

**Comment by Ephiarsis** [comment]
Sorry on my side as well. That sounded much more sassy than it was intended. :)
Good to know with the wings anyway, thanks.

**Comment by deilann** [comment]
It took me forever to figure out how to remove helms, so I don't blame you for not figuring it out on your own!

**Comment by lefnire** [comment]
Topic of un-equipping: mounts & pets are: click the mount/pet you currently have out puts it away. Should we equipment to that for consistency? Or would it be confusing?

**Comment by deilann** [comment]
@lefnire I was considering that, but what I'd prefer is to have the inventory arranged by slot, rather than class, but while I can seem to sort items based on klass, I can't seem to sort by gear type?

**Comment by lefnire** [comment]
Check out habitrpg-shared/script/index.coffee#api.updateStore

**Comment by deilann** [comment]
Oh, awesome, thnx.

**Comment by Ephiarsis** [comment]
Well - don't wanna be pushing, but would it be possible to set it for me manually? @lefnire 
It may seem ridiculous, but I worked hard to get there and since the whole game is about levelling and achievements, reaching a certain goal and not receiving the desired reward is like getting a pair of socks on christmas. :)
Thanks in advance.
9ef8acb6-4278-48e4-b479-ea3031329e85

**Comment by bolthy** [comment]
I'm encountering the same problem with the Ultimate Gear achievement. I'd appreciate any help I can get. cefeb701-3ed2-4ea9-bee5-563ddb8c40e0

**Comment by pipcorona** [comment]
I'm encountering the same. I have all the gear purchased for rogue and did not get the achievement.
0487ef5f-b2db-4e4c-be6a-d403f7eceec9
Thanks!

**Comment by lefnire** [comment]
actually, let's follow on https://github.com/HabitRPG/habitrpg/issues/2232#issuecomment-36678855 since there's some architecture being discussed there
