### ISSUE TITLE
Markdown doesn't actually work in Admin tab

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2207]
The Admin function for rewarding contributors claims "Markdown formatting allowed", but when you look at the list of contrib reasons, it doesn't appear to be parsing them as such:

![screenclip](https://f.cloud.github.com/assets/4501321/1828434/1634f596-7259-11e3-951a-aafdee029ad6.png)

**Comment by lefnire** [comment]
Yeah, it's not applying markdown. I was holding out until it would be useful. My big idea was adding a "Hall" tab, which would have subtabs "Hall of Heroes" and "Hall of Patrons". Heroes would list contribs, patrons would list KS backers. 

Heroes == current Admin tab, but we'd make it prettier, list (in functional markdown) what each has contributed. Remove the admin tab, and instead add admin functions to the Heroes page (forms, buttons, and admin-specific table columns) only visible to admins.

thoughts?

**Comment by SabreCat** [comment]
Ooh! That sounds cool! People will love it, their names will be up in lights even if they're not Tavern regulars.

**Comment by djuretic** [comment]
I guess this should be closed, Markdown works there.

**Comment by lefnire** [comment]
truth
