### ISSUE TITLE
Rearrange sorting of gear items in Battle Gear / Costume

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2208]
Usability issue, pointed out by Ryan in the Tavern. I'd tripped over it before myself, but hadn't thought to write it up until he talked about it.

In most gear-equipping workflows, you're primarily interested in what slot to equip, and secondarily interested in what class the piece belongs to. At the moment, the sort is all class-based, so if you want to see what all hats you have available to select from (as in the recent case when the Party Hat was handed out), you have to look all over the page. It would make more sense to organize by slot, then have a small icon or the item's popover inform you what class the item belongs to.

**Comment by deilann** [comment]
+1

I would be willing to go through and do the pixel edits to categorize the items. I feel that there should be a visual icon as well as information in the popover, simply because sometimes the hover text is touchy for me.

**Comment by deilann** [comment]
With the addition of the Winter Gear, this has again raised issues for me. In order to find what helm I should put on, I have to look all over the place to see which have the best stats. It's just not a logical setup.

**Comment by Alys** [comment]
Being handled in  [Reorganized Equipment Page and/or Equipment Sorting - Issue #5033](https://github.com/HabitRPG/habitrpg/issues/5033) and [Added ability to group equipment by TheHollidayInn - Pull Request #5046](https://github.com/HabitRPG/habitrpg/pull/5046)
