### ISSUE TITLE
Tasks not displaying correctly, unable to check off Dailies

### ISSUE THREAD

**Issue by sablewing** [HabitRPG/habitica#2211]
When I checked on my account today there were some additional entries showing up, with numbers for the task title and a note that a 3rd party API had placed the task into the list. My tasks for Dailies are already checked and I have tried the Sync command several times. I have also logged out and back in and I still get the same display.

 I've attached a screen shot that shows what I see in my browser. I have also attached a screenshot showing the message that appears when I hover over the new tasks that appeared. I am using Firefox, version 26.0. My user id is c255cb1c-ac84-4a73-95e8-d496c2bf9aeb. I only use HabitRPG in one location, on a desktop at my home.

Here are errors showing up in the JavaScript Firebug  Warnings console. If it would help to get additional information from the Firebug console, I can provide that too.

For the short term I have set the Resting at Inn option so I don't lose my current streaks on tasks.

15:4:7.730 CSI/tbsd_
15:4:7.734 CSI/_tbnd
Unexpected value xMidYmid meet parsing preserveAspectRatio attribute.

...["\\/b-u]/g,"@").replace(/"[^"\\n\r]_"|true|false|null|-?\d+(?:.\d_)?(?:[eE]...

cb=gapi.loaded_0 (line 37)
Unexpected value xMidYmid meet parsing preserveAspectRatio attribute.

![habitrpg_task_display](https://f.cloud.github.com/assets/6295095/1828940/6d87e0fe-726f-11e3-9f87-75f5c4349b4d.jpg)

![habitrpg_task_api_msg](https://f.cloud.github.com/assets/6295095/1828955/4deb9db6-7270-11e3-82ad-ce697aa77f65.jpg)

**Comment by paglias** [comment]
Is this still happening?
