### ISSUE TITLE
Positive mana on undoing a todo

### ISSUE THREAD

**Issue by ShwetaNarayan** [HabitRPG/habitica#2212]
I accidentally clicked a todo item and gained positive gold/xp and one mana point. Then went to the "completed" tab and clicked to undo it - and while I got the negative gold & xp, I gained another mana point instead of losing it. 

I tested this twice more and it seems to happen every time.

**Comment by negue** [comment]
Tested it right now, seems to work again^^.

I'm closing this, if this still happens for you, we'll reopen it. :)
