### ISSUE TITLE
Skills won't show up

### ISSUE THREAD

**Issue by philldevil** [HabitRPG/habitica#2215]
when I reached lvl 8 the skills stopped showing up on my tasks page. The place where they should be ins simply empty. I wonder why?
![bug bugado](https://f.cloud.github.com/assets/6297884/1829795/6f10e6a6-72ff-11e3-9adf-779763299641.png)

**Comment by SabreCat** [comment]
You won't see abilities until Level 11. #2096 #2102 #2103 #2110...
