### ISSUE TITLE
No Documentation for APIv2

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#2217]
While APIv1 already is marked as deprecated, there is no documentation for APIv2. Is somebody already working on this? (or is there possibly already some documentation, and it's just somewhere else than the old one).

If nobody is working on this, I could write some documentation, as I work through the api trying to understand how to work with it ;)

**Comment by lefnire** [comment]
I'll do this today. Sorry, after https://github.com/HabitRPG/habitrpg/issues/2135 I've been side-tracked with all the newly-found critical errors for the last couple weeks, but I think things have settled down and I can take time for this

**Comment by lefnire** [comment]
### General Progress:
- [x] [Find a generator](https://groups.google.com/forum/#!topic/nodejs/nlqR3XmJMUA)
  - Chose [swagger](https://github.com/wordnik/swagger-node-express), it's very cool. It setups up a route at /static/api with a visual & interactive API guide.
- [x] Finish [documentation](https://github.com/HabitRPG/habitrpg/blob/api-docs/src/apidoc.coffee)
  - Live progress at https://beta.habitrpg.com/static/api
- [x] Migrate [old documentation](https://github.com/HabitRPG/habitrpg/wiki) into [swagger page](https://github.com/HabitRPG/habitrpg/blob/develop/views/static/api.jade)

### Swagger Implementation To-Do
- [x] Embed swagger doc markup directly in routes, so they're not managed separately. [Read more](https://github.com/wordnik/swagger-node-express#mapping-swagger-to-subpaths)
  - This will consolidate a lot of code, and allow us to remove custom query/params validation, instead defining them in each route's swagger spec
- [x] Setup the interactive feature so users can test the API from swagger
- [ ] Convert mongoose models to swagger models, expose schemas in swagger-ui

**Comment by lefnire** [comment]
Ok, this is mostly done https://beta.habitrpg.com/static/api . Still some stuff to do (see progress above), but the brunt of it is complete.

@magicmicky you may be interested too

**Comment by MagicMicky** [comment]
Well, that's awesome! Thanks :)

**Comment by colegleason** [comment]
So when I was working with the API, I noticed the 'Try it Out!' feature doesn't work for many of the API docs because the requests aren't set up correctly (GET /challenges/{cid}). Can we add specific examples to the Swagger docs so that these work properly?

**Comment by lefnire** [comment]
So is the issue that you don't have a `cid` to work with? Or is it that the route demo isn't setup properly? If (b), we should go through and cleanup swagger with correct params, better documentation, and added Schemas. (I just threw together a v1 swagger fast since our apiv2 needed some baseline documentation, I'd ditched apiv1 leaving current 3rd-parties high-n-dry).

So on my list
- Better the documentation. More verbose descriptions, etc.
- Make sure all the params information is accurate. I believe much of it might not be.
- Convert Mongoose Schemas to Swagger Schemas (maybe 1-2h job), which will automatically show documentation for routes that take `req.body` (eg, POST/PUT /user/tasks), as well as document what the expected return format is for GET routes.

This isn't super high on my list, just brain-dumping for posterity

**Comment by colegleason** [comment]
No, I have a `{cid}` to work with. I just mean that the route demos don't
work.

On Tue, Jan 7, 2014 at 7:01 PM, Tyler Renelle notifications@github.comwrote:

> So is the issue that you don't have a cid to work with? Or is it that the
> route demo isn't setup properly? If (b), we should go through and cleanup
> swagger with correct params, better documentation, and added Schemas. (I
> just threw together a v1 swagger fast since our apiv2 needed some baseline
> documentation, I'd ditched apiv1 leaving current 3rd-parties high-n-dry).
> 
> So on my list
> - Better the documentation. More verbose descriptions, etc.
> - Make sure all the params information is accurate. I believe much of
>   it might not be.
> - Convert Mongoose Schemas to Swagger Schemas (maybe 1-2h job), which
>   will automatically show documentation for routes that take req.body(eg, POST/PUT /user/tasks), as well as document what the expected return
>   format is for GET routes.
> 
> This isn't super high on my list, just brain-dumping for posterity
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2217#issuecomment-31796722
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
pushed fix for that case to beta

**Comment by negue** [comment]
Just curious. IMHO Swagger has currently enough documentation for about the API.

Since there isn't any " old documentation" to migrate, this Issue can be closed. 

Or is there still anything to do / migrate?

**Comment by lefnire** [comment]
@negue that was actually tackled by someone in a PR, forgot to update it here! Also, I doubt anyone will ever get to "Convert mongoose models to swagger models, expose schemas in swagger-ui", and it's really not that important. So yeah, let's just close this
