### ISSUE TITLE
No Cron

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2218]
Have not been able to force cron this morning. Thought there was an issue regarding this already, but tags were empty and could not find one in five pages.

Wot happened:

I had a silent migraine last night and so had to suddenly end my day. Utilized the inn in case the migraine lasted longer than my day/would last longer than a day. (Which it did.)

Past my custom cron time (6am) removed self from inn. Dailies were left as I left them before going into the inn, aka the ones I'd checked off yesterday were still checked off.

Not knowing what else to do (I couldn't handle the damage from all the hits, especially soloing Trapper Santa), I reset my cron time for the next hour and checked off the rest of my dailies.

Cron time hit (9am, iirc) and no reset. Refreshed, no cron. Hard refresh, no cron. Cleared cache and restarted browswer. No cron. Changed cron time again (tried 10am and 11am); still have not had success in restarting my day.

Google Chrome   31.0.1650.63 (Official Build 238485) m
OS  Windows 7
JavaScript  V8 3.21.18.13

**Comment by casicastiel** [comment]
Similar thing happened to one of my party members. They had been in the inn on/before New Year's Eve, if I remember correctly, and haven't had a cron since. 
Here's the relevant party chat log - 
![screen shot 2014-01-01 at 5 03 23 pm](https://f.cloud.github.com/assets/6208739/1830259/9e14b690-7330-11e3-9ca5-762d2b84ebeb.png)

**Comment by lefnire** [comment]
See https://github.com/HabitRPG/habitrpg/issues/1057 . customDayStart has many issues, and we're thinking of doing away with it (or adding a "use at your own risk"). The solution is to set your CDS to 0, and unfortunately you'll have to wait another cron cycle. See linke for more info
