### ISSUE TITLE
deselecting daily doesn't remove enough money

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#2221]
I noticed, that I got 1gold 2silver for completing a daily and then got 1gold 1 silver removed when deselecting it again. This could be reproduced for all of my dailies Shouldn't it remove the same amount of money, I got for completing the task?

**Comment by deilann** [comment]
Check out #2503

**Comment by deilann** [comment]
Sorry: https://github.com/HabitRPG/habitrpg/issues/964
