### ISSUE TITLE
unticking a todo with a checklist removes much less XP and GP than it should

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#2222]
I had a todo with two checklist items. I ticked off both of the checklist items then ticked the todo. I received these rewards:
    28 XP
    7.32 GP
    3 MP

I then unticked the todo (but left the two checklist items ticked). These rewards were subtracted:
    13 XP
    3.42 GP
    3 MP

I then ticked the todo again, and received similar rewards to the first ticking:
    27 XP
    7.2 GP
    3 MP

Summary: For MP, unticking a todo with a checklist behaves as you'd expect - you loose all the MP you'd gained. But for XP and GP, unticking behaves as if the todo does not have a checklist - you loose only an amount that you'd expect from a non-checklisted todo.

This is reproducable. I tested MANY times and am now MUCH rich! :) (But I'm about to set my values back to what they should be.)  For todos with more checklist items, the effect is proportionally larger (you gain rewards for every checklist item, but always loose only a single todo's worth of rewards).

**Comment by wc8** [comment]
This is probably related to #2221 and there’s another ticket for this, I believe. Unchecking doesn’t remove exactly what was added, having multiple to-do items probably compounds it.

**Comment by Alys** [comment]
I'm not sure they are related. #2221 seems more like a rounding error, with the amount added being very close to the amount removed (1.2 GP versus 1.1 GP). With checklisted items, the difference is much greater (7.3 GP versus 3.4 GP for two checklist items; proportionally more for larger checklists). It's more like unticking ignores the fact that the item includes a checklist. If I get a chance this evening, I'll try to look through the code.

**Comment by Alys** [comment]
Ha!! Found it! I think. :) 

In develop/script/index.coffee at line 746, we have this:
          if task.checklist?.length > 0
           ....
            if direction is 'up' and task.type is 'todo'
              nextDelta *= task.checklist.length

BUT, direction will be 'down' if a todo task is being unticked, according to this code from HabitRPG/habitrpg/blob/.../public/js/controllers/tasksCtrl.js :
    /**
     \* This is calculated post-change, so task.completed=true if they just checked it
     */
    $scope.changeCheck = function(task) {
      if (task.completed) {
        $scope.score(task, "up");
      } else {
        $scope.score(task, "down");
      }
    };

So we need "nextDelta *= task.checklist.length" to be executed regardless of the direction - if my understanding is correct.

I have submitted a patch for this, but I HAVE NOT TESTED IT because I don't yet have habitrpg installed locally. I've referenced this issue in my pull request, so someone who knows what they are doing can check up on me. :)  Pull request: https://github.com/HabitRPG/habitrpg-shared/pull/73

**Comment by lefnire** [comment]
Alas, the issue is that the math used to determine the amount of points going up vs points going down won't give you the same results after modifying the task.value. Coming up with math for defending against that situation is gonna be a task and a half

**Comment by Alys** [comment]
lefnire commented on the GitHub pull request: "What this will do is, a user will gain points from checking a todo no matter if they're checking or unchecking. Alas"

Forgive me for arguing - especially if I'm still wrong! - but I don't think this will cause the user to gain points if they are unchecking. The index.coffee script already contains this code (line 738):
          nextDelta = Math.pow(0.9747, currVal) \* (if direction is 'down' then -1 else 1)
which is already being executed for any todo that's either ticked or unticked. Note the direction +/- 'if' clause which ensure that points are subtracted if the user is unchecking.

The trouble at the moment is that if the todo contains a checklist, there is further code that multiplies nextDelta by the checklist length:
          nextDelta *= task.checklist.length
This is currently only being executed when you complete a todo (direction is 'up'). If we also execute it when you untick a todo (direction is 'down') then nextDelta will still be negative and so points will still be subtracted.

"the math used to determine the amount of points going up vs points going down won't give you the same results after modifying the task.value" - Yes, but the difference seems to be small when there is no checklist (e.g., issue #2221 - 1.2 GP versus 1.1 GP). When there is a checklist, the multiplying factor of every checklist item makes the difference much larger (7.3 GP versus 3.4 GP for only two checklist items). Including the task.checklist.length multipler for unticking todos will reduce the difference to a much smaller amount.

**Comment by Alys** [comment]
> the math used to determine the amount of points going up vs points going
> down won't give you the same results after modifying the task.value. Coming
> up with math for defending against that situation is gonna be a task and a
> half

That's clearly still a problem (although less than it was before for
checklisted tasks). What if, whenever a todo (and a daily?) was ticked off,
the exact XP, GP, and MP deltas were recorded in an attribute of the task -
a new attribute called "deltaApplied" or something (which would have child
attributes for each of XP, GP, MP). Then if the task was later unticked,
you could use the deltaApplied values to remove exactly the same points
that had previously been added. Your maths for determining addition of XP,
GP, MP could then become as complex as desired, but with unticking always
being absolutely trivial.

You could even record drops in deltaApplied, and subtract the drops if the
user hadn't already used them (although I would weep tears of bitter
despair if I lost a new Golden potion through unticking an
incorrectly-completed task).

If you did this for dailies, you'd obviously have to clear out deltaApplied
on cron.

What do you think? Would you like me to have a go at implementing this? I'm
part way through setting up HabitRPG locally so (hopefully) I'd be able to
test my changes. If you like some of what I've described but not all of it,
tell me which bits are good and which bits suck. :)

Alys
proud owner of awesome new Crystal gear :)

**Comment by deilann** [comment]
...sorry, wrong ticket.

**Comment by Alys** [comment]
This was fixed as described in my Jan 5 comment with https://github.com/HabitRPG/habitrpg-shared/pull/73
