### ISSUE TITLE
Class Change Not Working?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2223]
Hi there, I'm having some problems with the class change...
I used to be a Wizard, and then I decided that I wanted to be a Warrior, right? So I go and buy some Gems, then click the Class Change button. They say that there was a 3 day cool-down period for it, so I waited a long while just to make sure that I wasn't just being impatient. I never got any confirmation on whether or not it changed, but it doesn't seem to have at all...

The Gems I spent on the change is gone, I still can only buy Wizard stuff, and I haven't gotten back my points for re-allocation. Is there a way that either I or someone from the staff can manually change my class?

**Comment by SabreCat** [comment]
The cooldown hasn't been implemented yet, it's an immediate switch. When you activate the change, you should see the "Select Your Class" popup immediately. What's your user ID from Settings > API? We can give you back your Gems, then you can give it another try and maybe use the JavaScript console to see if you're throwing an error somewhere.

**Comment by ghost** [comment]
Thank you for getting back to me! ^^
My ID is "6a498313-355a-43d7-ba6b-855a652bae8c"

**Comment by SabreCat** [comment]
OK, your Gems should be refunded. Refresh the page, give it another try, and if it doesn't give you the class switch right away, check the [console](https://developers.google.com/chrome-developer-tools/docs/console#opening_the_console) to see if anything blew up.

**Comment by ghost** [comment]
My Gems are back to 20, so I'm happy about that, however I still don't have a class change, and when I click on my name in chat, it says "Wizard - Coming Back Soon!" Oh, and I tried to see what was wrong with the console, but I'm not entirely sure if I did it right. Here's a screenshot of what happened:

http://25.media.tumblr.com/d82bfcd07e3a82821c07e1db68efe6dd/tumblr_myt6vpfPbK1seeicoo1_1280.png

**Comment by lefnire** [comment]
Click the class change buttons now with your restored gems, you gotta
trigger it again manually

**Comment by ghost** [comment]
Oh man, I'm sorry! This is a big thing, and I can't see how I neglected to mention it, but I don't have a Class Change button anymore! Here's a screenshot of my Stats page:
http://31.media.tumblr.com/4d43086dce3c71ca6de2b46bc75489f4/tumblr_myuk4vhIuN1seeicoo1_1280.png

**Comment by lefnire** [comment]
Oh I see. Classes unlock at lvl 10 these days. I see what went wrong, you
were part of the lvl5 classes early batch. We changed classes unlock to 10,
so when you clicked "change class" before 10, it knocked you back to normal
user status, out of classes early-adopter status. You may just need to wait
till lvl 10. Does everything function as expected otherwise?

**Comment by ghost** [comment]
OOOHHHH!!
Woah, I'm really sorry for making such a hullabaloo about this, I had no idea that it unlocked at Lv. 10 now. xD
Yeah, everything else works as normal, thanks so much for all your help! ^^

**Comment by lefnire** [comment]
Cool beans!
