### ISSUE TITLE
Tomatoes 15min break not properly recognized, taking HP after 5mins

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2227]
When using the plugin for Tomatoes, after 4 pomodoros you should take a 15min break, which is indicated by the 15min timer. After 5mins, which is the duration of a small break, you start getting more and more HPs taken away from you, even though there are 10mins left in the break.

**Comment by lefnire** [comment]
Report that over on https://github.com/habitrpg/habitrpg-chrome
