### ISSUE TITLE
Rogue Ultimate Equipment Achievement

### ISSUE THREAD

**Issue by clarence1** [HabitRPG/habitica#2229]
This is my user ID: 5001734a-5948-4319-aab8-914d3d0a2dd6

I have already obtained the Umbral Armor and Helmet and both Hook Swords and there is no further equipment for me to buy but I still have not unlocked the achievement yet.

**Comment by djuretic** [comment]
Related to #2232

**Comment by lefnire** [comment]
let's close and follow up there. i'll manually set you @clarence1 for now
