### ISSUE TITLE
Daniel, tell us your inn is not proof against attacking bosses.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2231]
If we start a quest, we’ve committed to it. Resting in the inn shields us from Neglected Dailies, however it does not—and I say, should not—protect us from _Boss damage_. 
We need Daniel to explain that, so our resting innHabitants don’t wonder why they’re taking a hit.

**Comment by lefnire** [comment]
I was thinking DTB the whole time... "what is she _talking_ about"? Nope, got it.

**Comment by wc8** [comment]
je je… :grin:  I generally try to make myself type out Justin the Guide and Daniel the Tavern Keeper, but I failed here. 

I  keep wondering what NPC’s are thinking as they read about the complaints people have against their counterparts:

> Justin is confusing…
> Clicking …doesn’t dismiss Bailey 
> Justin is invisible...
> I'm not sure what type of sicky Alex is for accepting blood as a currency...
> Put Justin in popovers...

Popovers…![popovers](http://upload.wikimedia.org/wikipedia/commons/1/15/Popovers_2.jpg).

So far, Ian appears to have escaped this abuse.

**Comment by lefnire** [comment]
You had me at "put justin in popovers"... *wipes tear*

**Comment by wc8** [comment]
I’m upping this to important because users are going to be approaching the end of the chance to finish Trapper and buy the Cubs Quest. If they misunderstand and think that the Inn will protect them, they could all die at the last minute without time to restart, see #2387 

Current text says:

> Daniel
> Welcome to the Tavern! Stay a while and meet the locals. If you need to rest (going on vacation? sudden illness?), I'll set you up at the inn - Dailies won't hurt you while you're resting.

On Resting, message says:

> Whilst resting, your dailies are saved and aren't affected by day turn-over. Whether you check out tomorrow or in a week's time, you'll continue in the same state as when you checked in.

Proposal, also trying to help #1350 by keeping bubble text short:
- [ ] **Daniel**: Welcome to the Tavern! Stay a while and meet the locals. If you need to rest from your dailies for vacation or illness, I can set you up in the Inn.
- [ ] **Resting Message**: While resting, your dailies will not be cleared with a new day. Whether you check out tomorrow, or in a week’s time, you’ll continue in the same state as when you checked in. Dailies themselves will not do damage if you miss them, but if you are in a Quest, Bosses can cause damage for missed dailies.

**Comment by DanielTheBard** [comment]
@lefnire - I just saw this issue and thought "I need to tell you what now? D: "

**Comment by wc8** [comment]
@DanielTheBard I just realized recently (or remembered, I may have known and forgotten) that Daniel the Tavern-keeper and Daniel the Bard are not one and the same.

**Comment by Aiseant** [comment]
I just made a pull request for this, my very first one !!!

**Comment by deilann** [comment]
This has been fixed.
