### ISSUE TITLE
Ultimate Gear stat not functioning properly? [$15 awarded]

### ISSUE THREAD

**Issue by Reesachan** [HabitRPG/habitica#2232]
#### Note to devs: This is our current intention for the badge: https://github.com/HabitRPG/habitrpg/issues/2881

---

I'm a rogue, and I've gotten outfitted with an Umbral Hood, Umbral Armor, and Hook Swords. The Rewards tab is no longer offering to sell me any more gear for my character aside from Health Potions, so I think that means that I should have achieved the Ultimate Gear stat, but that's not showing up for me. If someone could confirm or deny that for me, that'd be great.
##

**Comment by colegleason** [comment]
Trying to investigate this on a test user. I was able to get the achievement. However, the if statement for the achievement is a little complex, so maybe I'm not hitting the right condition.

```
if item.klass in ['warrior','wizard','healer','rogue'] and user.fns.getItem('weapon').last and    
  user.fns.getItem('armor').last and user.fns.getItem('head').last and (user.fns.getItem('shield').last or    
  user.fns.getItem('weapon').twoHanded)                                                                                                                                     
    user.achievements.ultimateGear = true  
```

**Comment by colegleason** [comment]
Wait, hold on. @Reesachan, were you _wearing_ all that gear when you bought the last item? I think the bug is that `user.fns.getItem` only returns the currently equipped item, so the if condition above would fail if one of those items wasn't `last`.

**Comment by Reesachan** [comment]
No, I wasn't. I've switched over to doing so for the time being, and I'll leave it on until the issue is resolved to see whether that makes a difference. So far, simply putting it on doesn't seem to have triggered the achievement. Do you think buying up the last of the winter gear would do it?

Thank you for helping me resolve this!

**Comment by colegleason** [comment]
@Reesachan, I don't think you will be able to get it right now. I'm trying to fix that.

**Comment by CiderSalt** [comment]
I'm having the same problem--rogue with no achievement though I upgraded to ultimate gear. I also wasn't wearing all my rogue armor at the time. My user ID is f7163b41-30a7-4b12-98d5-b244671fa0c4. Thanks for any help!

**Comment by Reesachan** [comment]
Thank you for working so hard on this problem. What do those of us who maxed out the gear without having been awarded that status need to do in order to activate that bit of code?

**Comment by colegleason** [comment]
Unfortunately I made the code only activate when you buy an item from the
final tier, so you will be unable to get the achievement (unless you switch
classes). We will award it manually.

@lefnire,would you like to run a migration? Or I could just write a script
that runs this function for all users that don't have the achievement.

On Fri, Jan 24, 2014 at 6:04 AM, Reesachan notifications@github.com wrote:

> Thank you for working so hard on this problem. What do those of us who
> maxed out the gear without having been awarded that status need to do in
> order to activate that bit of code?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2232#issuecomment-33217616
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by astroslav** [comment]
Are we still writing here about this problem? Same thing happened to me, however I WAS wearing all my armor when I bought the final piece so I'm not sure what happened.

UUID: 939751e2-d0c7-4d04-a9af-466a7967e421

**Comment by colegleason** [comment]
Yeah, a new bug was introduced recently. Sorry!

**Comment by astroslav** [comment]
Alrighty. Good to know I'm not the only one haha.

**Comment by mychan24** [comment]
Ah, same thing happened to me. I'll just wait for it to be resolved. 
(UID: 786f7ded-c00d-47c2-a1d4-37296d24926b)

**Comment by Ephiarsis** [comment]
Yeah, same for me.

**Comment by AlderQueen** [comment]
I got the last items yesterday with no achievement as well. UID 9fd7cfe1-fb0a-400c-b9f7-4fba502e4b5c

**Comment by NicoleEli** [comment]
Also having this issue (rogue class, wearing all top-level gear at the time of purchase, UID d289d42a-1028-4a26-b246-5924755575ff ).

**Comment by evelisaue** [comment]
Also same issue few days ago (rogue class, wearing all top-level gear at the time of purchase, UID f6159baa-422d-4711-ba27-25012cfbec96)

**Comment by ThisOtterBeGood** [comment]
Same here (warrior class):
a28797fb-2c12-4c04-aab8-4f7919c98e5a

**Comment by lefnire** [comment]
Hmmm... we may need to remove the Ultimate Gear Achievement. It was one of the first badges in the game, when there was only one gear set and no special gear. Since then the gear system has evolved so much that this badge has become something of a maintenance nightmare. How bad will it be for people if we remove this badge altogether? (cc @colegleason @SabreCat @deilann)

**Comment by colegleason** [comment]
I was actually thinking about that. Or transform it into something else. In
WoW achievements aren't "Acquire the last item in the set" but more like
"Collect the following 5 items." So either remove it or make it extremely
explicit in what items you need.

On Tue, Mar 4, 2014 at 9:39 AM, Tyler Renelle notifications@github.comwrote:

> Hmmm... we may need to remove the Ultimate Gear Achievement. It was one of
> the first badges in the game, when there was only one gear set and no
> special gear. Since then the gear system has evolved so much that this
> badge has become something of a maintenance nightmare. How bad will it be
> for people if we remove this badge altogether? (cc @colegleasonhttps://github.com/colegleason
> @SabreCat https://github.com/SabreCat @deilannhttps://github.com/deilann
> )
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2232#issuecomment-36637187
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by SabreCat** [comment]
The thought I had (I assigned one of these tickets to myself, somewhere) was to make it a layered achievement, the way Quests and Challenges are.

**Ultimate Gear**
Completed the following equipment sets:
- Crystal
- Rogue
- Warrior
- (insert special multi-equipment-quest themed set here)

**Comment by lefnire** [comment]
@SabreCat that works too! I'm up for either yours or @colegleason's idea (or both). Decided then, let's get off the current Ultimate Gear setup and move to something else. I hope to tackle this in coming weeks, but if someone beats me to it..

**Comment by bolthy** [comment]
Commenting here as instructed. I'm having same issue. cefeb701-3ed2-4ea9-bee5-563ddb8c40e0

**Comment by bifrostblonde** [comment]
commenting as instructed: af7286e5-e18d-4808-b170-137d2d8c9733 (mage)

**Comment by MagBag** [comment]
My original comment was in a thread that has been closed and merged with this one.  I still have the same issue, but didn't provide my user info previously.  Here it is if you need it: 99e9a8f7-57c5-49a7-870d-f4ff46f2439b (rogue)

**Comment by colegleason** [comment]
@lefnire @SabreCat We can do both of those. I just think code-wise it is more proper to explicitly list the item keys that are required. Makes the computation much easier and harder to break the achievement if we modify the item system like adding another item slot.

As the Pythonistas like to say: Explicit is always better than implicit.

**Comment by deilann** [comment]
I agree with @colegleason, not only because it's cleaner code with less
legacy, but because it also makes it clearer what the achievement is.

**Comment by soryanne** [comment]
Also having this issue, commenting as instructed, IUD 2489d48e-70a3-45e6-ad45-1e1edca36d8e (rogue). Thanks!

**Comment by jenncgf** [comment]
If you are still awarding this achievement, I had the same problem. I bought the last piece of eq the day before yesterday and had all the top tier stuff auto-equipped, and the achievement never awarded for me. My IUD is 1041c10f-362c-4528-9190-9630080f0f28 and I'm a healer. Thanks!

**Comment by Melanogaster** [comment]
I've got a rogue with the same problem. 289806ce-817a-4dd1-81d5-a9553bc04c5b
(Thanks for any help you can give!)

**Comment by evelisaue** [comment]
Also roque with ID f6159baa-422d-4711-ba27-25012cfbec96

**Comment by espritfollet** [comment]
I'm a mage with this problem. 7daa8315-2082-4958-ae08-deeb7bb746e1
More gear, in general, would be preferable ;)

**Comment by amyhowse** [comment]
Rogue with the same problem.  d1fbb91c-421f-4027-b654-b9ef2cd9fe22

**Comment by CharPU95** [comment]
Also a mage with this problem. User ID bcaccd30-8440-47e0-baad-7d9c2a228910

**Comment by LyndisSacae** [comment]
If the achievement's not getting thrown out, I'm also a mage with this problem. 84d81ec4-3587-4d24-92bb-9aec53497363

**Comment by hammstheman** [comment]
Hi, mage also having the problem c290a7cb-364b-49f1-a425-cb5ac6cb1af0

**Comment by elaseela** [comment]
Rogue with the problem.  957b4bbf-1a7d-4398-9a4f-91b4b891133e

**Comment by fleurrochard** [comment]
Yeah, I have a rogue with that problem as well. f8677abb-1936-44c4-bba8-c181dfc83e9d

**Comment by lefnire** [comment]
Hey everyone, let's not list IDs here anymore. We're going to changing the way this system works, and it will be "self-healing" when people equip their next piece (after we deploy a fix) - so we don't need IDs anymore

**Comment by jenncgf** [comment]
Thank you! That sounds great! Will we be able to equip anything from our existing inventory when the fix is made, and will you be posting it here when the fix happens?  

Much appreciated!  :)

**Comment by lefnire** [comment]
Theoretically anything, according to the fix I have in my mind. But we'll see when crunch time comes

**Comment by sputnikvi** [comment]
Glad to see it's getting fixed! I'm having the same problem.

**Comment by Thoth19** [comment]
I just bought the last hook sword. I had the rogue gear equipped, but I had a costume with a winterwonderland piece. 1392204a-d08e-4958-94bb-c35ea0920d2b
Thank you very much.

**Comment by frostykatmonstur** [comment]
Another Rogue experiencing this problem. User ID is e240ef42-f243-4e56-954b-16e5136b0687
Thanks much!

**Comment by AlpineLotus** [comment]
Also Rogue, having same issue.
User ID:
9d627dbb-2d9b-41a4-8734-f6c863720b70
Thanks.

**Comment by deilann** [comment]
Hey guys-- can I repeat that @lefnire stated it is no longer necessary to
post UUIDs in this thread? The fix he is planning to implement will be
self-healing.

**Comment by ghost** [comment]
Have the same problem too, with my Rogue. Any ETA for the fix?

**Comment by Wine-Guy** [comment]
Yet another Rogue with the issue
b16695dc-2dae-4144-919d-3e84086e624f

**Comment by quin-jay** [comment]
I noticed on my profile page that this hasn't quite been resolved yet. I'm not sure if you guys have been chipping away at this behind the scenes, but I thought I'd throw my idea out there just in case: What if the code's if statement was like `if {list every rogue item} OR  {list every warrior item} OR {etc....`? It would be _super duper bulky_ but you couldn't get more explicit than that. If this was set up as `if user owns = true` then it would probably fix it for everybody who already has the top gear, right? ~~if you couldn't tell, my "code" examples are completely made up and I have no idea what language it's even supposed to be in~~

I know @SabreCat's idea included top-tier of other equipment, but my understanding was that Ultimate Gear was originally just for the classes, is that correct?

**Comment by kipjib** [comment]
Am I safe to assume that if I purchase my last piece of ultimate gear now it won't glitch?
I am a warrior class.

**Comment by Alys** [comment]
@kipjib   No, please see the message at the top of this page. No one gets the achievement. When this bug is fixed, it will state here that it's fixed.

When you buy your final piece of gear you'll get the notification that you have ultimate gear but you won't see the achievement on your stats page. When the achievement is fixed, then it will appear.

**Comment by kipjib** [comment]
Oh okay I wasn't sure based on the age of the post. My apologies and thank you for the clarification.

**Comment by lemoness** [comment]
Since from reading this it looks like the conclusion was that we were going to remove the old Ultimate Gear badge and then replace it with the new Ultimate Gear Badges, which are handled in https://github.com/HabitRPG/habitrpg/issues/2881, should I close this ticket? I can update the name and description of the other one.

**Comment by Alys** [comment]
@SabreCat Bounty!
