### ISSUE TITLE
Unable to join a party fight

### ISSUE THREAD

**Issue by JPSmee** [HabitRPG/habitica#2233]
My party is currently engaged in a fight against 'Trapper Santa' - but I am unable to join in. One member of my party initiated the fight, and the only option that I have is to abort the fight. When I complete dailies, it does no damage to the boss.

**Comment by lefnire** [comment]
Just gotta wait for them to finish, and join the next round. In a
decent-sized party, quests go quite fast. You have until Jan 31st (plenty
of time), and each player who signed up before 12/25 got 1 scroll for free,
so someone in your party will have a spare to start again

**Comment by JPSmee** [comment]
Shouldn't the other party members have been given the option to join in? I ask, as nobody in the party was given the option to join in.

And to clarify, the only person who is currently able to participate in the fight is the person who used their scroll.

**Comment by lefnire** [comment]
When the quest scroll is activated, everyone in the party _at that moment_ is given an invite. The quest leader waits until everyone (or enough) people have joined, and then manually clicks "Begin Quest". At that point, it's locked, the battle begins, and nobody can join or leave until until (a) the questers win, (b) loose, (c) abort

**Comment by JPSmee** [comment]
Ahh, that makes sense. Now to beat my party member (I'm the party leader, lol). Many thanks!!!
