### ISSUE TITLE
Changing equipment gives weird blank notifications

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2235]
user cca60406-1b8f-496e-af77-cd19df77c895, mac chrome
![screen shot 2014-01-01 at 4 58 58 pm](https://f.cloud.github.com/assets/6208739/1833561/426cf5cc-73cc-11e3-8613-e2d947584407.png)

**Comment by djuretic** [comment]
Happens to me too! Chrome on Ubuntu

**Comment by SabreCat** [comment]
Duplicate of #2073.
