### ISSUE TITLE
Using the Reset feature pops up a modal about Streaker achievement

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2236]
I used the reset feature to remove some experience I accidentally gave myself. After saving the changes, a modal dialog popped up to tell my how I received the "Streaker" achievement. Sorry, I should have took a screenshot.

Since I've only been using this for a day, I'm pretty sure I don't have that achievement.

**Comment by speg** [comment]
Can you reproduce it?  I just reset my new account and didn't get it.

**Comment by colegleason** [comment]
Er, sorry. I think I meant 'Fix Character Values', not Reset. I will try to
reproduce.

On Mon, Jan 6, 2014 at 3:32 PM, Steve notifications@github.com wrote:

> Can you reproduce it? I just reset my new account and didn't get it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2236#issuecomment-31689321
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
Yeah, it brings up the modal (confirmed) but doesn't actually reward you a streak achievement. I think the watcher might just be triggering on change, and it's `undefined` before but `0` after

**Comment by speg** [comment]
Yup, that did it.
