### ISSUE TITLE
Suggestion: Logging Habits for the previous day (skip back 1d)

### ISSUE THREAD

**Issue by spaboleo** [HabitRPG/habitica#224]
Hey Tyler,

I really love this webapp and so far it helps me to stick to habits. It's fun. :+1: 

The only thing that drives me crazy is that it kind of forces me to end my day around midnight, which doesn't necessarily meet my schedule. 
I've got some habits that I want to form that are supposed to happen right before I go to bed. Logging them beforehand just to meet the midnight-deadline is not a solution. This would contradict the methodology of crossing off things that you actually did, without excuses or cheating (crossing off things you never accomplished).

It shouldn't be a problem to just log that habit for the next day then, but this somehow rips apart the chunkiness a day has. It doesn't seem to be one block of todos and habits anymore.

At the same time I don't want HabitRPG to get to complex. Allowing the user to jump back to the last day and being able to make edits would be nice.

Maybe this option should only be granted only once a day. There is really no purpose for constant jumping back and forth. As the previous day already elapsed one should no what was done and which habits were sticked to. So one time editing should be enough.

I know there are more important things to tackle, like the critical bugs, but maybe for the future :)

Thank you for your work!
It's awesome!

**Comment by StanLindsey** [comment]
Hi spaboleo, thanks a bunch for your input. You're not the first to suggest this feature so it must be important, check out the card on Trello: https://trello.com/c/CaAm7APS

Trello is where you can vote for the features most important to you. We're glad you're enjoying HabitRPG =D
