### ISSUE TITLE
Dailies

### ISSUE THREAD

**Issue by delphina** [HabitRPG/habitica#2240]
The dailies I checked yesterday are still checked today, and all dailies have lost their streaks and I lost 5HP, as if I had not completed any of them.  I checked my settings and nothing has changed about my custom day start, so I'm a little baffled.

Username: Delphina

**Comment by wc8** [comment]
For debugging purposes:
- were you resting in the inn recently?
- do you have a custom day start?

For immediate relief, you might try recording the values (e.g. level, XP, GP) you should have, unchecking your dailies manually and using Fix Character Values in Settings.

**Comment by delphina** [comment]
- I have not rested at the inn at all.
- I do not have a custom day start.

**Comment by padmi** [comment]
I have the same problem! I also was not in the inn and do not have a custom day start.
Username: padmini

**Comment by deilann** [comment]
Follow this at: https://github.com/HabitRPG/habitrpg/issues/1057

We're not sure CDS has anything to do with it anymore.
