### ISSUE TITLE
Unlocked Rebirth, Stuff Vanishes

### ISSUE THREAD

**Issue by stormyhearted** [HabitRPG/habitica#2241]
I feel bad, I just posted an issue two hours ago, and here I am again.

I upped one of my habits and got a notification that I'd unlocked Rebirth, so I went into the options to see where it was. The Beast Master achievement I'd unlocked in the past two hours disappeared, along with the six pets I'd finished- but the gems I used to buy them weren't restored. My UID is 103c0def-d25f-424f-a4c1-ab7ca7655710.

**Comment by wc8** [comment]
Hi, did you unlock the stable yet? My understanding is, the pets should be there when you unlock that feature. You just won’t see them until you unlock it.

**Comment by stormyhearted** [comment]
I didn't use the rebirth option, I just got the note that I'd unlocked it. My level and gear are all the same, and I still have access to the rest of my pets and mounts.

**Comment by stormyhearted** [comment]
I should note I just went looking, and can't even _find_ the Rebirth option.

**Comment by wc8** [comment]
Some tavern reports of missing pets / pets needing to be re-fed, too.

**Comment by lefnire** [comment]
@stormyhearted are you using beta? wonder if the tavernists are too. Fixed a bug here https://github.com/HabitRPG/habitrpg-shared/commit/8523f686723d0c730c16aa2c3f63b4f102d29249 , but it would only have affected beta. I'll give you gems for buy back in the mean time

**Comment by stormyhearted** [comment]
I am using beta, yes.

**Comment by lefnire** [comment]
K, we should be good then - fix pushed, buy-back gems granted. Sorry boot that

**Comment by SabreCat** [comment]
And for clarification, @stormyhearted, the Orb of Rebirth can be bought in the Market, where the Snowball and Fortify Potion are! (The unlock modal mentions that, but it's way subtle... sorry about that!)

**Comment by stormyhearted** [comment]
I think the bug fix must have affected that too, as it's not in the market for me. Not that I'm worried about it, I don't plan to use it anytime soon.
