### ISSUE TITLE
Picture offset mismatch

### ISSUE THREAD

**Issue by JasonGross** [HabitRPG/habitica#2242]
When I recently navigated to the pets page, I saw

![screenshot 2014-01-02 19 08 05](https://f.cloud.github.com/assets/396076/1836672/6debc7ca-740b-11e3-91e9-5ba586839cd9.png)

Reloading the page fixed it.  I suspect the problem is that I had old javascript code running to get the pictures, and the server had updated the images.

**Comment by lefnire** [comment]
refresh

**Comment by JasonGross** [comment]
As I said, reloading the page fixed the issue.  I reported the issue in case the developers wanted to add some code to version-check the images before loading them, and automatically reload the page if the versions don't match or something.
