### ISSUE TITLE
Unresponsive Script Pop-up on Tasks page.

### ISSUE THREAD

**Issue by Calae** [HabitRPG/habitica#2246]
Whenever I log in to HabitRPG, or any time after when I return to https://habitrpg.com/#/tasks, my browser freezes for a moment (It says "Not Responding" in the title bar and I have the Windows 7 loading circle pop up; I cannot do anything with my browser during this time), and then I inevitably get at least two Unresponsive Script popups like the ones shown here:

![habit rpg error 2](https://f.cloud.github.com/assets/3935538/1839986/3f4fd216-7489-11e3-9482-1978d0b58016.png)
![habitrpg error](https://f.cloud.github.com/assets/3935538/1839987/3f518af2-7489-11e3-8ceb-0bb1533cf894.png)

The numbers at the end where it says Script always seem to change, I've noticed the numbers 1-6 on different occasions but there could be others.

**Comment by djuretic** [comment]
If you use another browser, do you experience the same problem?

**Comment by lefnire** [comment]
See https://github.com/HabitRPG/habitrpg/issues/1499 . The most common solution is to clear your completed To-Dos. If you can't even get in to do that, I'm posting workaround on that other ticket.

Also, per @djuretic  - use chrome, it's faster than other browsers :)

**Comment by lefnire** [comment]
sorry, [workaround here](https://github.com/HabitRPG/habitrpg/issues/1499#issuecomment-28160349)
