### ISSUE TITLE
Non-questers' missed dailies hurt party?

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2249]
Not all of my party has joined the Trapper Santa quest, so non-questers are protected from losing HP, but according to the tavern, their missed dailies are damaging the questing members of the party.  

If this is so, could you please make it so that party members who reject or are still pending on a quest when the quest starts don't have their missed dailies count towards boss damage to questers?

**Comment by SyntaxPickax** [comment]
I've tried, and I can't reproduce this locally. If I set up a party of two, and one of them starts without the other, the non-quester does not affect the quester.

Sir Codes-A-Lot is a good little quester with no unfinished dailies. Sir Tests-A-Lot is a non-questing slacker who doesn't call his mom or brush his teeth and has ignored his party member's quest invitation.
![screen shot 2014-01-09 at 9 35 18 am](https://f.cloud.github.com/assets/1245093/1880150/7de1b6b4-7954-11e3-80b8-4b2c16dc5dd4.png)
The next day:
![screen shot 2014-01-09 at 9 37 36 am](https://f.cloud.github.com/assets/1245093/1880172/d2358402-7954-11e3-985a-6bbf44d500fa.png)

**Comment by colegleason** [comment]
@JennaMalkin: Do you know if the quester rejected the quest, or was it started without him/her?

**Comment by SyntaxPickax** [comment]
@colegleason For what it's worth, locally everything still works in a party of 3 with one quester, one who rejects the quest, and one who wants to be asked later.

**Comment by lefnire** [comment]
@SyntaxPickax I started setting up some integration tests for quest scenarios for such edgecases [here](https://github.com/HabitRPG/habitrpg/blob/develop/test/api.mocha.coffee#L232), dunno if that will help you with testing around or if you have your own processes down. `mocha test/api.mocha.coffee`

**Comment by SyntaxPickax** [comment]
Excellent, thanks. It might be a while before I'm able to dig into things
again, but when I do the tests will be useful.

**Comment by JennaMalkin** [comment]
The active non-quester Rejected the quest, but we also have two people who were Pending.

**Comment by lefnire** [comment]
looks like something else is at play. I've written some tests to ensure this isn't happening, and sure enough non-questers are _not_ hurt by bosses (as intended). It could be that the non-questers are using a 3rd-party app. Chrome extension, mobile app, etc - and they're getting notifications of damage they've taken off-site
