### ISSUE TITLE
Internet Explorer 9 Compatibility Trouble

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#225]
While trying to create a testing account in IE9 on Win7, I found I was unable to open the Login/Register dialog. Pressing the button gave no response. Clearing cache, closing/re-opening IE has not fixed it.

Can anyone confirm this behaviour?

Browser: Internet Explorer 9.0.8x
Operating System: Windows 7 Ultimate 64-bit (fully patched)

**Comment by lefnire** [comment]
yeah, this is gonna be a tough one. Derby has [experimental IE support](https://groups.google.com/forum/?fromgroups=#!topic/derbyjs/3r4PJZpbzgQ), let's come back to this one later - I may have to put up one of those "use a new browser" modals

**Comment by SaraDGore** [comment]
I had the same problem with IE 8 on Windows 7 Enterprise.

**Comment by lefnire** [comment]
sorry guys, IE simply does not work with Derby. It cannot be used. Gotta use anything else my friends.

**Comment by lefnire** [comment]
this will be fixed when we move to angular
