### ISSUE TITLE
Deleting a challenge does not delete the challenge tag

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#2250]
When I deleted the old, finished challanges, the challanges' tags were still in the tag bar. The tags were automatically created when I joined the challenges, not by me.

**Comment by SabreCat** [comment]
Since you could have added that tag to other tasks in the meantime, we don't automatically delete it. (In fact I'm still using the tags from some expired challenges, myself!) You can use the pencil icon to edit your tags and get rid of it if you don't want it anymore.

**Comment by Atomk** [comment]
@SabreCat Ah, now I understand. In this case it would be nice if, when deleting the challenge, the site asks if you want to keep its tag or not. (however I see there are more important things to care about at the moment :smile:)
