### ISSUE TITLE
Can't type in Tavern, Party or Guild Chat

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2251]
When I click inside the tavern, party, or guild chat, it won't let me click and type.  My mouse cursor changes to a 'you're about to type bar (with a hat and base)', but when I click, nothing happens, I can't type in chat.  Nor can I copy-paste from chat or my User ID.

Browser:  Safari 5.0.6
User ID: 572fdfa8-bac7-423f-9bd1-90eb8e04cb72

**Comment by lefnire** [comment]
Can any one else replicate? I can't (incl with safari)

**Comment by JennaMalkin** [comment]
Using the 'chat refresh button' (multiple times) did nothing.

**Comment by JennaMalkin** [comment]
Seems to be a case of massive lag - closing my browser and restarting it seemed to fix it.
