### ISSUE TITLE
"Party System" alert/notification is behind the main page but above header

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2254]
If I scroll to the top of the page I can dismiss it. If I scroll down, however, I cannot since half of it is below the index page as seen below:

![screen shot 2014-01-03 at 11 22 05 pm](https://f.cloud.github.com/assets/232327/1844126/6c6c8f2e-7500-11e3-8c05-98ec50f039bd.png)

This was on the Challenges list page I think, but it may have also occurred elsewhere. Looks like a z-index problem, perhaps?

**Comment by paglias** [comment]
The interface up there has changed, if it still happens will reopen
