### ISSUE TITLE
No gold from completed quest?

### ISSUE THREAD

**Issue by stormyhearted** [HabitRPG/habitica#2257]
I'm in a solo party and I completed the Trapper Quest when I logged in this morning; I have my quest mount but no extra gold? Am I missing something in the party page? (My UID: 103c0def-d25f-424f-a4c1-ab7ca7655710) Thanks!

**Comment by ghost** [comment]
I have the same problem, completed the quest this morning.  I received the polar bear mount and experience but no gold.

**Comment by deilann** [comment]
Y'all can fix this yourself: fix character values under settings.

I'm going to guess, considering the timing, it was related to the 503s.
