### ISSUE TITLE
Ultimate Gear Achievement

### ISSUE THREAD

**Issue by LuisCoder** [HabitRPG/habitica#2259]
I got all armor and weapon upgrades for the warrior class about 2 days ago. For some reason i didn't get the Ultimate Gear Achievement.

**Comment by MagBag** [comment]
Same here -- I completed all armor and weapon upgrades for the Rogue class yesterday.  I thought the achievement might be applied after the new day reset, but no.  Still no Ultimate Gear Achievement.

**Comment by lefnire** [comment]
@colegleason any thoughts on this per recent(ish) ult-gear achievement code?

**Comment by LauraMSE** [comment]
I have this issue as well. Rogue class here.

**Comment by colegleason** [comment]
@lefnire It should trigger when you purchase any of the last items. I wonder if something changed recently with the way I wrote it and the addition of the back slot.

**Comment by colegleason** [comment]
Yeah, I just used `content.gearTypes`, and no one has a back armor piece that is `last`.
https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L13

**Comment by lefnire** [comment]
@colegleason would this be the fix? https://github.com/HabitRPG/habitrpg-shared/commit/27da784cf6e6d3ece8827037cb7a370e8462fd78

**Comment by lemoness** [comment]
Also reminder here that we have all the art for badges to give each class a separate achievement!

**Comment by colegleason** [comment]
@lefnire it would be. You could also filter out `back` from `content.gearTypes` in `user.fns.ultimateGear`.

Sorry for not fixing it myself.

**Comment by lefnire** [comment]
Perfect thanks! No worries, thanks for finding

**Comment by frostykatmonstur** [comment]
I'm also having this problem. I purchased all of the gear for the rogue class about a week ago and never got the achievement. Username is frostykatmonstur

**Comment by AlderQueen** [comment]
Same issue with rogue class, purchased a few days ago. UID 9fd7cfe1-fb0a-400c-b9f7-4fba502e4b5c

**Comment by bifrostblonde** [comment]
Same issue with mage class, purchased probably 4 days ago.

**Comment by lefnire** [comment]
let's follow on https://github.com/HabitRPG/habitrpg/issues/2232
