### ISSUE TITLE
'Error 400: User with id ---- not found.'

### ISSUE THREAD

**Issue by wolvenhalo** [HabitRPG/habitica#2260]
Both I and a friend have been met with this message when trying to invite to a party, both with me hosting a party and her. I've searched through here for a bit but couldn't find anything helpful.

My user id: efb56443-0c20-4ac5-9b42-​c9a5cf34edf0

**Comment by lefnire** [comment]
Looks like you closed it, I'm assuming (a) accidentally, (b) you realized you were entering the profile name instead of the UUID ?

**Comment by wolvenhalo** [comment]
I closed it because we've only had accounts for a few hours now, and
guessed that it might take a bit for them to register as existing. If it
still doesn't work in the next couple of days, then I'll reopen the issue -
we were using the UUID so it wasn't that.

**Comment by lefnire** [comment]
Gotcha gotcha

**Comment by wolvenhalo** [comment]
It's been a few days now and we're still having this issue, any help?

**Comment by monsterthing** [comment]
I am still having the same problem as well and we have had our accounts for over a week

**Comment by lefnire** [comment]
Promise to get to this as soon as we can, we have tons of other crits in the queue - hang tight

**Comment by BeeTee** [comment]
Friend made a guild and he receives the "Error User with id X not found" error while trying to invite me.

Also receives the error while trying to invite me to a party.

the error he gets:
https://habitrpg.com/api/v2/groups/dbbf24b1-d46e-44b2-8830-5cfa92eb510e/invite?uuid=BeeT 400 (Bad Request)

**Comment by deilann** [comment]
Is it actually your user id or is your friend using your display name?

**Comment by Netharia** [comment]
Any updates on this?

**Comment by deilann** [comment]
@Netharia The error @BeeTee got shows that they were trying to use "BeeT" instead of the user's UserID. As you are new to this thread, I want to make sure that you are using a user ID, which is a random alphanumeric string, not display name, which would be more of a... well, name.

@wolvenhalo's issue is more peculiar and specific. Are you the friend referenced? If not, any and all info you can share about what's happening would be extremely helpful.

**Comment by Netharia** [comment]
Apologies for not providing specifics. I am experiencing the alphanumeric userID not found error when being invited to a party, correct. I embarassingly don't have my friend's username (we both found the project this week, late July), but I do have the Group ID of her party, as well as my own userID of course. Would those be helpful?

**Comment by deilann** [comment]
Ah, there be the problem!

You can't actually join a party via the Group ID. You'll need to find a way
to give her your UUID and have her invite you.

Or is she experiencing the error trying to invite you?

**Comment by Netharia** [comment]
That is exactly the problem, she cannot find my UserID when attempting to invite me. We've checked to make sure it was entered correctly, to no avail. I only mentioned having the GroupID in case being able to look at the account and/or party in the backend might help.

**Comment by deilann** [comment]
Ah yes, so she is inviting you. You said you were experiencing the problem,
so I was confused.

Yes, that info would be lovely. If she could also post the error message
she's getting in its entirety here, that would be lovely as well.

**Comment by Netharia** [comment]
Group ID: 3f50b495-d505-4bd5-a47b-57a2263aab60
my UUID: e671755a-4500-4f52-8458-03850c4c316f  (account/character name is Nessari)

She's gone to bed for the night, I'll see if she can send me the whole error text before she goes to work tomorrow; all I know is "hmm. not found" and "error, still".

**Comment by deilann** [comment]
If it's possible, could she post here? It just gets rid of the possibility
of losing something in communication, and then she'll get updates with the
ticket.

**Comment by Netharia** [comment]
I'll relay the message. Wouldn't surprise me in the slightest if she already had a github account (not that it's difficult to get or anything :p ).

**Comment by deilann** [comment]
Thanks!

**Comment by paglias** [comment]
I suppose this is fixed
