### ISSUE TITLE
Duplication and re-categorization of tasks

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2261]
Hello, I logged on just now (9:05 @ 1/5/13) and I found my dashboard to be strangely modified.

All of my dailies, to-dos, and rewards were duplicated (ie. there would be two "Watch 1 episode of anime" rewards with the exact same properties) except for one daily and a different one of my dailies was re-categorized to the habit list. I was able to delete the duplications successfully and unfortunately I forgot to take a screenshot before I deleted, whoops.

The daily that moved was checked off and grayed out and cannot be deleted or moved back to its daily home. I just created the account today. I did modify xp/gold values as i was moving data across accounts but otherwise nothing else should be there. 

Using Chrome Version 32.0.1700.41 m Aura, UID: 6c15366c-2458-4bb1-ad44-3f00a1c55c94 and i'm not too sure how to determine if an error is relevent so i posted the console dialog below for my page...
![habitrpg_bug_figydaflygon](https://f.cloud.github.com/assets/6326230/1848081/868705e0-7679-11e3-93eb-06269cf658df.png)

Let me know if there's any more info I should provide. I'll check to see if my daily went back to its spot after the daily reset (cron?) but I'd like to know how to delete it otherwise.

Thank you and wonderful job guys!

**Comment by lefnire** [comment]
Closed on accident or purpose?

**Comment by ghost** [comment]
Oh no no, i'm not familiar with Github and i didn't realize this bug was already opened. I couldn't find the delete button

I'm sorry I'm not really sure what to do. Should I re-open this or...?
