### ISSUE TITLE
Problems using Habit RPG on tablet

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2262]
I am using a windows surface RT tablet running windows 8. When running the website (using internet explorer browser, as required by tablet), anytime I try to scroll down, the entire screen just goes blank. Everything returns as soon as I scroll up to the top of the page. But scroll down even a minute amount and everything disappears again. This is a problem as I now can't access the tasks at the bottom of my to-do lists. 
This happens using both landscape and portrait orientation.

**Comment by lefnire** [comment]
@mbehr think https://github.com/HabitRPG/habitrpg/pull/2258 will fix this? (gonna merge soon btw, just wanna give it a test)

EDIT: Oh wait, totally misread the PR. Ignore me

**Comment by deilann** [comment]
Is this still occurring? Please reopen the issue ticket if it is.

**Comment by lefnire** [comment]
We've upgraded a lot recently which may have fixed. If not, could you list any Javascript errors from console?

**Comment by deilann** [comment]
@lefnire I think this might also be an IE support thing.
