### ISSUE TITLE
After Rebirth, avatar not showing gear properly

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#2263]
Small issue:  I bought an Orb of Rebirth and my avatar changed to have no gear except the training sword, just as it should (although I do still show the mount and pet I was equipped with when I bought the Orb, which surprised me). But then I got to level 2 and bought a shield, and it does not appear with my avatar. It does show up in my stats. I also bought the 0-gold party hat and it does not appear either. I am wondering if this has something to do with the fact that I was using "costume" before the rebirth. As I said, a small issue but I figured I'd mention it in case it's not what was intended. User ID is 0b670754-57f5-4704-854f-9a9c92107b9b.

**Comment by hattieshoe** [comment]
Okay, I got to level 4 and got my inventory tab, and sure enough, when I went in there the "use costume" option was already checked and had me costumed with no gear except the training sword. The equipped gear was correct and when I changed my costume it worked fine. So it appears the issue is simply that if you do a rebirth while using a costume, you lose the costume components but stay fixed with the costume option till it unlocks again. (And same with mount and pet, they stay fixed till unlocked again.) So.... not really a bug unless you want it to show up the same way as someone starting for the first time, and even so, it's just till level 4. Hope that clarifies things at least. :-)

**Comment by lefnire** [comment]
methinks @SabreCat has since fixed this

**Comment by SabreCat** [comment]
Yup, fixed over [here on habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared/pull/78). Sorry about that @hattieshoe, I ran into the issue too!

**Comment by SabreCat** [comment]
Also [this fix](https://github.com/HabitRPG/habitrpg-shared/pull/75) addresses the pet and mount piece, by deequipping your current Pet and Mount upon Rebirth.
