### ISSUE TITLE
Mana incorrectly displayed

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#2266]
Hi there,

I noticed a small glitch in the display 

![sans titre](https://f.cloud.github.com/assets/4418868/1849612/8c05e182-76b8-11e3-8883-a1690db71807.PNG)

I have 121/87 mana points ?

**Comment by Aiseant** [comment]
update : 
- when I used mana yesterday, it went down to 101/87
- this morning, I have 87/91, with a correct display

**Comment by deilann** [comment]
There are ~ways you can get too much mana. #2737
