### ISSUE TITLE
Not Losing health for Incomplete Dailies

### ISSUE THREAD

**Issue by azurehorror** [HabitRPG/habitica#2268]
I have about 5 or so dailies I have on my account, and I haven't logged on for about 3 days. I know I'm not resting in the tavern, and I did not lose any health for missing these dailies. Is something wrong? I also did not lose my streak.
I did, however, regenerate mana over this period of time.

**Comment by wc8** [comment]
@azurehorror the 5 dailies are not grey?
developers, is this an intentional implementation of auto-freeze on inactivity?

**Comment by deilann** [comment]
Cron only triggers after you log on. So if you logged off before cron (everything checked) and then log on again three days later, it triggers cron, reseting everything. But cron was never triggered while nothing was checked off.
