### ISSUE TITLE
Bizarre Changes to HP etc. In My Morning

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2270]
Last night at 0:25 (i.e. after midnight, but before my custom day start) I recorded all my stats and went to bed. 

This morning at 8:05 I refreshed my browser window. I then 
- _gained_ one HP
- _lost_ 15 XP
- gained at least _12_ MP (I went from down 12 to full)
- _lost_ 3 GP and 21 silver

I don't know for sure, but I believe I clicked some + habits after midnight, but no dailies and no - habits or ToDos. (All I have recorded is a list of everything clicked between 22:59 and 0:25, along with the resulting change to XP and GP.)

As of when I went to bed I had no dailies unchecked.

**Comment by snicker** [comment]
Are you using multiple clients or computers to interact with HabitRPG? The notifications calculate a delta between server and your last log in _from that client_, so if you make changes on mobile or another client, you may see strange values.

**Comment by ArlieS** [comment]
Nope, only 1 computer involved this time, and only 1 browser. 

Also, it's not just the notification that was odd. These are real changes to the values. I've been keeping a log of what I check off, and resulting values - partly to see trends, and partly to facilitate exact bug reports if something goes wrong.

**Comment by wc8** [comment]
I wonder if Settings > Export > CSV would help, at least as a log of clicks?

**Comment by colegleason** [comment]
Yeah, any logs you might have would be great.

**Comment by snicker** [comment]
A JSON export may hold even more possible data for us.

On Jan 9, 2014, at 17:42, wc8 notifications@github.com wrote:

I wonder if Settings > Export > CSV would help, at least as a log of clicks?

—
Reply to this email directly or view it on
GitHubhttps://github.com/HabitRPG/habitrpg/issues/2270#issuecomment-31996047
.

**Comment by deilann** [comment]
@ArlieS please reopen this ticket if you can supply us with any more datas.

I'm going to guess the things you clicked after midnight were not saved to the server, so when you refreshed, they went back.
