### ISSUE TITLE
Disappearing Gold

### ISSUE THREAD

**Issue by jamiederpson** [HabitRPG/habitica#2273]
I had 10 gold and 50 silver, and then I deleted a custom reward (I didn't spend it, just hit the trash button) and all of a sudden had 0 gold and 46 silver. 
I'm very confused as to where it all went, as I hadn't missed any dailies or hit any - habits, or anything of that sort.

**Comment by colegleason** [comment]
I'm having problems reproducing this issue. Has it happened again?

**Comment by jamiederpson** [comment]
No, it only happened the one time.

**Comment by colegleason** [comment]
Do you remember the amount of the reward? Perhaps the one click somehow
triggered both the reward and the delete.

On Tue, Jan 7, 2014 at 10:03 PM, jamiederpson notifications@github.comwrote:

> No, it only happened the one time.
> 
> > On Jan 7, 2014, at 9:52 PM, Cole Gleason notifications@github.com
> > wrote:
> > 
> > I'm having problems reproducing this issue. Has it happened again?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2273#issuecomment-31804245
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by jamiederpson** [comment]
I don't remember, but it's not a big deal, it wasn't a ton of gold or anything.

**Comment by colegleason** [comment]
Oh, @lefnire may be able to reimburse you. I was just wondering if the
amount of gold lost was equal to the reward cost.

On Tue, Jan 7, 2014 at 10:14 PM, jamiederpson notifications@github.comwrote:

> I don't remember, but it's not a big deal, it wasn't a ton of gold or
> anything.
> 
> > On Jan 7, 2014, at 10:05 PM, Cole Gleason notifications@github.com
> > wrote:
> > 
> > Do you remember the amount of the reward? Perhaps the one click somehow
> > triggered both the reward and the delete.
> > 
> > On Tue, Jan 7, 2014 at 10:03 PM, jamiederpson notifications@github.comwrote:
> > 
> > > No, it only happened the one time.
> > > 
> > > > On Jan 7, 2014, at 9:52 PM, Cole Gleason notifications@github.com
> > > > wrote:
> > > > 
> > > > I'm having problems reproducing this issue. Has it happened again?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/HabitRPG/habitrpg/issues/2273#issuecomment-31804245>
> > > .
> > 
> > ## 
> > 
> > ## Cole Gleason
> > 
> > Student, University of Illinois at Urbana-Champaign
> > Email: cg@colegleason.com
> > Website: colegleason.com
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2273#issuecomment-31804632
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by deilann** [comment]
@jamiederpson Just so you know, you can now fix gold in fix character values.
