### ISSUE TITLE
Inventory tab should (maybe) appear at the same level you can buy gear

### ISSUE THREAD

**Issue by erratio** [HabitRPG/habitica#2274]
My newbie friend reports that at level 2 he can buy basic gear but has no access to the Inventory tab to take it off - he's stuck wearing whatever he buys.

**Comment by lefnire** [comment]
You unlock the item store under rewards column at level 2. You don't see the inventory tab until you've unlocked drops (aka, pets & potions) until lvl 4. So you can't swap gear until later.
