### ISSUE TITLE
tags after the third are created tied to the third

### ISSUE THREAD

**Issue by moskupols** [HabitRPG/habitica#2276]
When I create a new tag and there are already at least three of them, it becomes tied to the third one, i.e. it is applied to all the tasks the third tag is applied to, and every change is automatically applied to both tags. When I click on one of the tags after the second, all of them become selected:
![2014-01-07 03 46 52](https://f.cloud.github.com/assets/6238404/1855365/07569646-772d-11e3-8c1a-e0f30144a0e3.png)
Also sometimes when I finish editing tags, name of one of the tags is changed to name of the third or vice versa.

UPD: It seems that refreshing the page solves the problem quite well.

**Comment by agentzel** [comment]
I'm having the same problem, though it happens regardless of the number of tags I have (even with just 2, tagging one tags the other).  I also sometimes have the issue of the tags changing to be the same.

**Comment by colegleason** [comment]
I think this the same as #940. I looked into it a bit, and I think it has something to do with the way the list is updated after a tag is created. Since a refresh fixes it, it's fine when it fetches the tag list all over again. Maybe we should examine what happens after a call to `User.user.ops.addTag`.

**Comment by colegleason** [comment]
Pretty sure it is because new tags aren't given IDs:

```
console.log(user.tags);
[Object, Object, Object, Object]
 0: Object
 1: Object
 2: Object
   $$hashKey: "09T"
   id: "5b62e67a-0237-456f-bbca-e2a81e247891"
   name: "evening"
   __proto__: Object
 3: Object
   $$hashKey: "0HG"
   name: "newtag"
   __proto__: Object
 length: 4
 __proto__: Array[0]
```

**Comment by lefnire** [comment]
sure 'nuff! Thanks @colegleason , pushing fix

**Comment by lefnire** [comment]
@colegleason I stole your thunder there, gave you contrib.lvl++ since you did the grunt work :)

**Comment by colegleason** [comment]
D'aw, thanks, I was messing around with how to fix it but I didn't know we had that client side UUID call.
