### ISSUE TITLE
I got hurt but I don't know why...

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#228]
I'm sure this has been mentioned before, and if so, please forgive me.

I logged on this morning after breakfast and I took some damage.  But I don't know why.  It would be nice to know why, so I can make sure I don't take damage tomorrow for the same reason.

Thank you!  I'm totally stoked about this game.  :)

**Comment by StanLindsey** [comment]
We're looking into displaying a "history" of your user so that we're can find out if this is an actual bug or just an unknown. 

Have a look at the card on Trello https://trello.com/c/h0pezwDR
