### ISSUE TITLE
Useless scrollbars in the tavern

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#2284]
Hi !
Recently, scrollbars appeared everywhere in the tavern. I don't know if there was an update, or if it's just me realizing it, but anyway... there's way too much of it : more than half of them don't add anything, it just scroll half a millimeter for ... well, nothing. 

Basically, any chat longer than one line has a scrollbar (in my display of the tavern, maybe it's different for other people)

Sorry to point this out, it's absolutely not a priority to solve, but kinda annoying. :)

**Comment by snicker** [comment]
Could you post a screenshot? I think I know what you're referring to, but the scrollbars should only appear when the text is longer than the container. This was to prevent long posts from taking up a ton of real estate.

**Comment by Aiseant** [comment]
There you go :
![sans titre](https://f.cloud.github.com/assets/4418868/1860013/e68c3b5c-77ac-11e3-83d0-09bce178e81d.PNG)

I do agree that scrollbars are usefull. But this is ridiculously useless : see here, the same chatroom with all the scrollbars down : 
![sans titre](https://f.cloud.github.com/assets/4418868/1860023/0f6762c2-77ad-11e3-874e-30bfce5c53b8.PNG)

And there are other people commenting on this subject in the tavern
If it was possible to change the length of the message where you start to have a scrollbar ...

**Comment by Aiseant** [comment]
Sorry for that ><

**Comment by casicastiel** [comment]
I'm getting it too. Even for messages one line long. (Chrome on Mac)
![screen shot 2014-01-07 at 10 33 55 am](https://f.cloud.github.com/assets/6208739/1860277/34dc7ff2-77b1-11e3-88e5-14d84672c096.png)

**Comment by snicker** [comment]
Seems related to the new "+1" feature styling.. if there is a +1, the scrollbars are gone... @lefnire @SabreCat ?

**Comment by Aiseant** [comment]
Yes indeed ! I just +1'd a message in the tavern, and the scrollbar left.

**Comment by clmmerrill** [comment]
I have the vertical scroll bars when not needed also but I have a new horizontal scroll bar. Should I keep the issue here or move to be new issue? Adding picture to show.
![2014-01-07_horizontal_scroll](https://f.cloud.github.com/assets/5649804/1861714/5c99dd22-77c6-11e3-98d8-2092e6b0e49a.png)

**Comment by lefnire** [comment]
will push later
