### ISSUE TITLE
Sudden health loss and task duplication

### ISSUE THREAD

**Issue by RoseOnAPiano** [HabitRPG/habitica#2285]
When I opened up HabitRPG, I lost 50 health, gained 281 XP, gained 11 MP, lost 4 gold and 85 silver, and then lost the rest of the gold because I died. I thought this was weird because I had just hit level 13 the night before and was at full health when I went to bed.

Also the two new tasks I added to my dailies last night were doubled.

I'm not sure if this is useful information but I'm also experiencing the bug from issue #1915, where I can't delete a challenge that doesn't exist.

I know for sure I didn't have two RPG tabs open at the same time, but I probably had two computers logged in to HabitRPG at the same time. I haven't used the second computer to access the RPG in a few days though.

I'm using Chrome Version 31.0.1650.63, my username is RoseOnAPiano, and here's the screencap I grabbed as I opened HabitRPG:
![habit](https://f.cloud.github.com/assets/6337646/1857703/50acded6-777d-11e3-93e2-5780687e17cd.jpg)

I used the fix character values feature to bump myself back to level 13, so not much damage was done. Thanks for your hard work! :)

**Comment by deilann** [comment]
gonna guess this was related to #2601
