### ISSUE TITLE
To-do : string not found

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#2286]
Hi, me again, for a small glitch :)

It seems there's a string missing in one ballon help (no idea how to translate the french word >< sorry). 

See below :

![sans titre](https://f.cloud.github.com/assets/4418868/1858194/83b9778a-7787-11e3-8b03-ebca194b9d5c.PNG)

It appears when you hover the icon to save and close the edited todo ('cancel' and 'delete' work fine, the one in between is missing)

**Comment by speg** [comment]
Related to 255acd79d22f9d5cf1677875665fb17f88866bb1?  I am seeing this in other places too.

**Comment by Aiseant** [comment]
I'm sorry 'cause I don't know the language this code is in, so I cannot really debug it. However, I cannot detect any discrepancies between the syntax in the lines concerning the 'save' and the other like 'cancel' and 'delete'

If I'm correct, it's around
a(ng-hide='!task._editing', ng-click='editTask(task);saveTask(task)', tooltip=env.t('save'))

The only difference is that ng-click calls two functions where there's only one for delete and cancel. Maybe something is wrong here (in the way the functions are merged to make one attribute) and prevent the tooltip to be correctly called ? 

Once again, i don't know this .jade thing, it's purely observatory and maybe totally out of subject here. Sorry if it's the case

**Comment by lefnire** [comment]
pinging @Sinza-

**Comment by marcelosizer** [comment]
@lefnire I believe I forgot to add `save` to main.json but the weird thing is that it's showing to me. Added now but my previous commit is still showing on the new PR [habitrpg-shared #80](https://github.com/HabitRPG/habitrpg-shared/pull/80).

@Aiseant are you seeing it over save only?

@speg where else are you seeing it?

**Comment by speg** [comment]
@Sinza- 
![screen shot 2014-01-07 at 7 14 37 pm](https://f.cloud.github.com/assets/698301/1864707/7eba0790-77fa-11e3-8ccb-63fb99016a33.png)

**Comment by lefnire** [comment]
It's showing in english. So looks like if someone's browser's language picks up, and that locale is is selected from the server, it's not falling back on english strings for defaults when the locale doesn't have the string

**Comment by marcelosizer** [comment]
@speg Can you refresh your page to see if it works? Can you check your language on the Settings tab to see if it's set to English or something else? Thanks!

@lefnire I really missed `save` but both `addChecklist` and `checklist` are on main.json file. I had my habit in Portuguese and after the locales folder got moved to habitrpg-shared it changed to English and it's the only language displaying on Settings. Also, @paglias said that it was supposed to work that way, fetching the default strings on the english folder and I tried looking in `middleware.js` but it's beyond my scope. Is it possible that @speg's `tasks.jade` file was updated but `habitrpg-shared/locales/en/main.json` wasn't? They weren't merged at the same time and @Aiseant has only the **string not found** issue with `save` which was really missing and you can see the **Add checklist** button on his picture.

**Comment by Aiseant** [comment]
My 2 cents : I only saw this with the "save", but maybe I missed it somewhere else, I'm not sure. My hrpg is in english in the computer from which I took screenshot (I cannot choose another language anyway).

**Comment by marcelosizer** [comment]
@Aiseant if you see on @speg's picture he got **string not found** where you got **Add Checklists**. I'm waiting for his answer to see if it worked out.

**Comment by speg** [comment]
@Sinza- reloading the page does not resolve the issue.  My language is set to English (the only choice.)  Perhaps I am missing the translations file somehow?

**Comment by marcelosizer** [comment]
Weird. Need to wait for @lefnire or @paglias.

@speg are you on the habitrpg.com website or is it a local install? Try holding the shift key while refreshing.

**Comment by speg** [comment]
Local install, HEAD at 039bdabb495b6e1365b93c49e162323511c4cba1.  At work now, but can help debug more tonight.

**Comment by marcelosizer** [comment]
@speg I believe it's the outdated main.json file then. The latest version is [here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/main.json).

This issue has probably been fixed by this PR [habitrpg-shared #81](https://github.com/HabitRPG/habitrpg-shared/pull/81)

**Comment by paglias** [comment]
@speg local install? check that dependencies are updated, `npm install`, if still doesn't work delete the `node_modules` folder and run that command again.

@Sinza- I'm merging that commit and closing this issue, it should arrive on the site as soon as a new version is pushed, thanks!

**Comment by lefnire** [comment]
pushing now. y'all check back in 5-10m

**Comment by speg** [comment]
Removed `node_modules` are reinstalled.  All good now.
