### ISSUE TITLE
"Pickpocket" on a dark red TODO gets me *less* gold and no XP

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#2289]
If I use "pickpocket" on a dark red TODO, I get less gold (around 5 gold instead of 7-8 without pickpocket), I get no XP, and apparently no drop but it's difficult to say whether this one is deterministic.
I was able to measure that because pickpocketing a TODO, like a daily, does not validate it.

So in a nutshell, using "pickpocket" means spending your mana to shoot yourself in the foot...

**Comment by casicastiel** [comment]
Pickpocket is supposed to be used on low-value Dailies, I think; I use it on my blue >80-day streak once in a while and get 80-90 gold from it. I don't know how it's calculated on Todo's.

**Comment by lefnire** [comment]
Yep, target blues. The spell description actually says "You gain an increased gold bonus on the task, higher yet the 'fatter' (bluer) your task."

**Comment by Eusebius** [comment]
Sorry, but the design is really poor here, I believe the users should not be tricked into spending their mana to lose money... It should be at least neutral, or at the very least advertised. It is said that the blue ones will get you more money, it is not said that the red ones will make you lose some!
