### ISSUE TITLE
For large reward prices, the coin icon is off the reward bar.

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2292]
![screen shot 2014-01-07 at 12 16 59 pm](https://f.cloud.github.com/assets/232327/1861824/169ebc6e-77c8-11e3-82e2-92fa02d15d1b.png)

I believe this only happens at certain zoom levels (110%). Not sure if we should cover those, but the site looks like it is meant to be responsive to different screen sizes and zoom levels.

Browser: Chrome 31.0.1650.63
OS: OSX Mavericks

**Comment by sleepykit** [comment]
Same as https://github.com/HabitRPG/habitrpg/issues/498 and https://github.com/HabitRPG/habitrpg/issues/1993, I think.

**Comment by colegleason** [comment]
Yup, same as #1993.

On Tue, Jan 7, 2014 at 8:34 PM, Anna Nelson notifications@github.comwrote:

> Same as #498 https://github.com/HabitRPG/habitrpg/issues/498 and #1993https://github.com/HabitRPG/habitrpg/issues/1993,
> I think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2292#issuecomment-31801030
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com
