### ISSUE TITLE
Rogue Ski-sassin weapons mismatched

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2293]
This may be because of the right-hand/left-hand difference with other classes, but at the moment the right-hand Ski-sassin weapon is 90 gold, 8 STR bonus, and the left-hand one is 70 gold, 9 CON bonus. Is it intentional?

**Comment by colegleason** [comment]
I just spent like 20 minutes trying to reproduce this, but it seems @lefnire already got it in habitrpg/habitrpg-shared@221574bcb24371aef0e0fbf6a2608aef3a914e0b. Not sure itf it's been pushed yet though.

**Comment by lefnire** [comment]
yeah, this one's fixed
