### ISSUE TITLE
People with mounts and w/o pets are positioned too low

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2297]
When someone is riding a mount and at the same time does not have a smaller pet next to their sprite, the whole character with the mount is too low, so the level number partially covers the mount's legs. I believe such characters should be positioned the same way people with mounts and pets are positioned - in the middle, not at the bottom of the bar.

**Comment by deilann** [comment]
This seems correct to me?

**Comment by mczuchnowski** [comment]
It's corrected now.

**Comment by deilann** [comment]
Thanks! Closing a TON of tickets, and sometimes I get them wrong.

**Comment by lefnire** [comment]
All hail @sabrecat on this one

**Comment by SabreCat** [comment]
Haha, yeah. I intend to expand the mount sprite area, if I can, to make use of some of that space to correct positioning issues...
