### ISSUE TITLE
How did my pet become unselected?

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2299]
I was going along normally, fully equipped rogue, with veteran wolf, with a costume setup involving the "absurd" hat

I did all of the following over the course of a day or so:
- bought winter rogue gear
- hatched approx. 4 pets
- fed a pre-existing pet enough food to make it into a mount (all at once)
- hatched a new copy of the pet that had been promoted
- discovered my avatar seemed to be flying/hovering with possibly foreshortened feet, and definitely without my pet wolf
- selected the pet in the appropriate screen, whereupon it returned to normal
- noticed I was wearing the new (lower stat) winter gear, but not displaying it, and fixed all that too.

The (trivial) "bug" is that I never selected a new pet or knowingly unselected the pet I had. It's also not the one promoted to mount - it's not even one that can be promoted.

I suspect the auto-wearing of my new purchase counts as "works as designed", though not so desirable for someone with max gear, buying a semi-costume piece. 

I'm including the rest of the story in case I'm wrong about when my pet became unselected. Probably it's a side effect of promoting some other pet to mount. Possibly a side effect of simply feeding some other pet.

**Comment by zoebeagle** [comment]
I think what happens is that, when you feed a pet, it becomes active.  Even though you didn't specifically select it, it became active. After it grew into a mount, the 'pet' version disappeared from your inventory, which is how the pet got 'unselected'.  (This is all just an educated guess, but I think it's accurate.)

**Comment by wc8** [comment]
@ArlieS a pet you can't feed, like a turkey?

**Comment by ArlieS** [comment]
@wc8 Yep, the pet I started with was one of the special ones that can't become a mount.

**Comment by deilann** [comment]
Closing this. If it's reoccurred, please let us know.
