### ISSUE TITLE
Suggestion for Repeating Tasks

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#230]
I think there's a lot of possibilities for the Repeating tasks.  Options such as a task that would repeat every two days rather than just certain days of the week, or tasks that would appear once a month.  I'd suggest taking a look at the options that Outlook (the email program) gives for Reoccurring tasks and duplicate, if possible, most of what they have there.

For example, I'd like to enter a task that I should go running every other day.  Can't do that.

Thanks.

**Comment by wc8** [comment]
See #19

**Comment by StanLindsey** [comment]
More task management is planned. Thanks for the suggestion though. 
Make sure to vote on the card on Trello if its important to you:
https://trello.com/card/repeat-every-n-days/50e5d3684fe3a7266b0036d6/108

Issue closed for housekeeping
