### ISSUE TITLE
joining challenge makes party look empty

### ISSUE THREAD

**Issue by Akiaya** [HabitRPG/habitica#2303]
**Logging out and logging back in should fix this, for the moment.**

Yesterday I sent my code to the party leader, they took me in and when I checked today, I was able to read everything in the party section, I was in the party. But when I clicked Challanges, checked a party challange, and then went back to party section, there was no party whatsoever. Create a Party thing was back. I messaged party leader, they said I was already in the party and it probably was a bug. So...

**Comment by Akiaya** [comment]
It seems like my problems resolved when I logged out and logged in back in.

**Comment by lefnire** [comment]
Did you join the challenge? Probably a bug that a party fetch was returning `res.send(200)` instead of the full party object, and `ngResource` was replacing the in-browser party with `{}`. Benign, refresh should fix, but will look into when we can

**Comment by Akiaya** [comment]
Yep, I joined the challange. Also, challenge was my party's.

**Comment by lefnire** [comment]
@deilann should we re-open this and rename "joining challenge makes party look empty" or something? or is this tracked elsewhere?

**Comment by deilann** [comment]
I could have sworn it was somewhere else, but now I can't find it. I'm going to reopen it, rename it, and give info on loging in and logging out.

**Comment by Alys** [comment]
Recent changes to how you view and join challenges have fixed this issue.
