### ISSUE TITLE
Can't leave

### ISSUE THREAD

**Issue by marska** [HabitRPG/habitica#2304]
I can't leave party.

Browser: Chrome, IE9
User: b78e81ff-ff23-4541-bf15-c4f1898a5acb

Steps to reproduce:
1. Create party.
2. Change party owner.
3. Try leave.

**Comment by lefnire** [comment]
Parties have an issue that you have to refresh after creating them before you can do anything substantial with them (like changing party owner). Had this party existed for a while before you performed that operation, or was this all in one go?

**Comment by zoebeagle** [comment]
I'm also having a problem leaving my current party.  I am not the leader of the party, but when I click the "Leave" button, nothing appears to happen.  I've refreshed after clicking it and even logged all the way out and back in, and I'm still in it.  Help :)

**Comment by lefnire** [comment]
Verified. @colegleason looks like something with the leave-group-leave-challenges code. Seems to work fine when leaving Guilds, but but the button doesn't respond when trying to leave a party

**Comment by colegleason** [comment]
Yup, that's my bad. Fixing now.

On Wed, Jan 8, 2014 at 2:33 PM, Tyler Renelle notifications@github.comwrote:

> Verified. @colegleason https://github.com/colegleason looks like
> something with the leave-group-leave-challenges code. Seems to work fine
> when leaving Guilds, but but the button doesn't respond when trying to
> leave a party
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2304#issuecomment-31874971
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
pushing fix now (thanks @colegleason!). Y'all who can't leave, try again after ~10m

**Comment by lefnire** [comment]
ah... heroku buildpack push issues, may take a while. I'll ping back when we're good

**Comment by lefnire** [comment]
ok, √

**Comment by marska** [comment]
thx :+1:

**Comment by zoebeagle** [comment]
Works now, thank you very much! :)
