### ISSUE TITLE
Party buff not working

### ISSUE THREAD

**Issue by sabrinastarfire** [HabitRPG/habitica#2305]
I casted tools of the trade for the party and im the only one with the buff sign.
My teammates have cast earthquake n tools of the trade for the party but they are the only ones with buff sign. My character does not show any buff.

**Comment by SyntaxPickax** [comment]
Does refreshing the browser change anything?

**Comment by Aubec** [comment]
I'm encountering a similar issue.  I buffed our party (protective aura) this morning and now I see that one of our party members no longer has the buff (but the others do).  What should the duration of the buff be?  My first thought was that it had worn off him but not the others.for some reason.

**Comment by sabrinastarfire** [comment]
No, refreshing does not change anything

**Comment by wildcate** [comment]
Similar thing here - the rogue who cast the tools of the trade spell has a buff, my character shows no buffs even though I did refresh the browser.

**Comment by deilann** [comment]
@sabrinastarfire Did you sign on after they cast the spell?

Cron removes any and all buffs.

**Comment by brightbold** [comment]
I am seeing the same thing. Yesterday I cast Earthquake in the morning so my party members would get a full day of the buff before it expired at their midnight cron, but I was the only one who showed the buff. I tried the same thing again today and one member has the buff but not the other. Both days I cast it before either of them had logged in - should I be doing it afterwards? (And if that's the problem, how come one got it today but not the other?)

**Comment by deilann** [comment]
@brightbold Logging in causes cron. So if one of them logged in after their cron time (as I do) and therefore triggered cron, but one of them didn't log in until later, triggering cron, one will get it and the other won't.

**Comment by deilann** [comment]
So basically, if they had already triggered their day's cron, it won't trigger when they log on.

**Comment by brightbold** [comment]
That makes sense, thanks. I was thinking it was server-based, but I guess that doesn't make sense since in your settings it's your local time. And I didn't think either of them had logged in this morning, which is why I asked that question, but I suppose one of them must have.

**Comment by sabrinastarfire** [comment]
yeah, i did. and it still didnt work after refreshing

On Wednesday, February 12, 2014 9:48 AM, Kelley Curry notifications@github.com wrote:

That makes sense, thanks. I was thinking it was server-based, but I guess that doesn't make sense since in your settings it's your local time. And I didn't think either of them had logged in this morning, which is why I asked that question, but I suppose one of them must have.

**Comment by deilann** [comment]
@sabrinastarfire If you signed on _after_ they cast the spell that's the problem. See #2523
