### ISSUE TITLE
To-do Keep Reappearing

### ISSUE THREAD

**Issue by Rickyb1194** [HabitRPG/habitica#2306]
I have a to-do that keeps coming back up.  I check it off, get the exp, gold for it and refresh my browser and it shows up again.

**Comment by lefnire** [comment]
what's your UUID, and the text of the item that keeps re-appaering?

**Comment by Rickyb1194** [comment]
User ID

40161c07-07c3-43b3-a0f7-b29e57e1f085

The task is ‘Family worship’

**Comment by deilann** [comment]
Let's move it to the referenced issue.
