### ISSUE TITLE
Rounding Errors in Reward Alerts

### ISSUE THREAD

**Issue by storian** [HabitRPG/habitica#2309]
In another discussion wrt correct display of reward alerts (linked below), error from rounding in "money" rewards was mentioned.

There I suggested that such errors be eliminated by always rounding up.  Really my main idea is to eliminate errors from the reward alerts.  My guess is this is best accomplished by making rounding consistent, which I imagine would mean to round everything in the same direction at generation, which should mean that later no rounding will occur, hence no errors.  And I suggested rounding up because I imagine most HabitRPG users would rather have more reward than less. :)  But I have nothing to recommend choosing "rounding up" as a solution other than that.

SabreCat asked me to post a ticket on this, so here it is.

See: https://github.com/HabitRPG/habitrpg/issues/2048

**Comment by Alys** [comment]
Tentatively closing because I think this doesn't happen any more....
