### ISSUE TITLE
Bought a sword, but how can I tell I bought the sword?

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#231]
I _think_ the sword is a bit bigger.  I was wondering if it would be a good idea to implement something where, if you hover over your avatar/character it would display a list of all the doo-dads he's wearing or has equipped?  Also, once I've purchased the sword, it should disappear from my list.  It didn't, initially.  But I logged out and logged back in and now there's an axe in the list so it looks like this feature/ability is there.  Perhaps my screen didn't update as it should have?

-abe

**Comment by StanLindsey** [comment]
Check #233 

The sword does change it is just that the second swords graphic is only slightly larger than the first. 

I'm going to close this issue has there is a discussion already at #233
