### ISSUE TITLE
Problem with registration (community forum)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2315]
Hello I have the exact same issue with regarding to registering to the community forum as this one: https://github.com/HabitRPG/habitrpg/issues/1376

When I registered they didn't send any email and told me to contact the administrator if error persists.

My username is GlassJewel

**Comment by wc8** [comment]
@GlassJewel I changed pass to "removed" try signing on to change it.
Report back here if that didn't work.

**Comment by ghost** [comment]
It worked! Thank you!
