### ISSUE TITLE
Registration issue for community forum

### ISSUE THREAD

**Issue by Dr3amrunn3r** [HabitRPG/habitica#2317]
hi guys! Jake here,and I went to sign up for the habit rpg community forum,but after i signed up it gave me two messages,one saying "Email with further instructions sent!" but then there's another error that says "email unable to be sent contact administrator if the issue persists" Because of this issue when i sign in it won't let me sign in because it says that my password or username is invalid.I'm certain that i'm correctly entering my password,so i'm pretty sure this has to do with the unsent email. 

if it's any help, my habit rpg community forum username is Dr3amrunn3r

**Comment by wc8** [comment]
Site's down I'll try again in a while.

**Comment by wc8** [comment]
I'm going to try steps from #1376, hang on.

**Comment by wc8** [comment]
change pass to "removed" sign on and change it or comment back here if that doesn't work @Dr3amrunn3r

**Comment by Dr3amrunn3r** [comment]
well,it appears that changing the password worked after  signed in with removed

**Comment by Dr3amrunn3r** [comment]
so thank you alot!
