### ISSUE TITLE
"Save" checkmark no longer working

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2318]
In Firefox, when any to-do etc is in edit mode, the checkmark in the upper right corner says "string not found" when moused over, and can no longer be clicked on. The other three buttons (cancel, delete, and progress) appear to work normally and have normal mouseover text.

**Comment by octern** [comment]
This happened to me yesterday, but the problem went away after a refresh.

**Comment by lorian** [comment]
And so it has for me!
