### ISSUE TITLE
Task repeat button setting

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#232]
I'm not sure I understand, even with the color of the task itself, whether or not a task is set to be due on a particular day or not.

Is a task due when the day button looks pressed in, or out?

For example, when would these tasks be due?  All the weekdays, or just weekends?

![Capture](https://f.cloud.github.com/assets/3382838/100635/a1649f56-683f-11e2-976f-4b2277ef86f6.PNG)

Sorry for the dumb question.  Thank you for your help!

**Comment by rixx** [comment]
The way it is now, the task is due every weekday.

Tasks are active when the button of the respective day is pressed.

(It took me some time to get it, too.)

**Comment by StanLindsey** [comment]
I fumbled on this also. I think a slight tweak of the design may solve this. I'm going to keep this issue open as its a very minor bug/design flaw.

**Comment by Pandoro** [comment]
Can we close this? With the new colors I think this is fixed right?
