### ISSUE TITLE
REST Headers combined into one?

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#2320]
I'm working on a habitRPG client in the Unity game engine, and I have to use a separate library, because habitRPG's native classes do a relatively poor job of handing REST apis.

Is it possible to combine the api key and user id headers into one header inside of the habitrpg server?  I think I would be able to do post and get requests with the native WWW class, if I only needed one header.

**Comment by snicker** [comment]
What language is this in? C#? I don't understand how anyone would approach this without having two separate headers, or how there is an HTTP library that doesn't allow you to send requests with more than one additional header.

**Comment by fragmental** [comment]
It's not really an HTTP library.  It's a "WWW class", and it sucks.

**Comment by colegleason** [comment]
Looking here:
http://docs.unity3d.com/Documentation/ScriptReference/WWW-ctor.html

It takes a Hashable object, so just fill the Hashable with as many headers
as you like.

On Thu, Jan 9, 2014 at 7:49 PM, Stewart Martin notifications@github.comwrote:

> It's not really an HTTP library. It's a "WWW class", and it sucks.
> 
> On Thu, Jan 9, 2014 at 6:32 PM, snicker notifications@github.com wrote:
> 
> > What language is this in? C#? I don't understand how anyone would
> > approach
> > this without having two separate headers, or how there is an HTTP
> > library
> > that doesn't allow you to send requests with more than one additional
> > header.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2320#issuecomment-31992521>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2320#issuecomment-31996344
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by fragmental** [comment]
DOES IT REALLY?! Lol.  I guess I should have read the class description
again.  When I first read it, I didn't know what a hashtable was :/
