### ISSUE TITLE
Disappearing quest

### ISSUE THREAD

**Issue by Hodizzle** [HabitRPG/habitica#2321]
BOught gems, bought the new quest scroll, started the quest yesterday (bear cub). Today, the quest is gone, scroll is not there, no prizes have been gained (therefore, I know it wasn't magically completed) and gems are still missing.

**Comment by lefnire** [comment]
UUID? Might be hitting the bug where user is in two parties at once

**Comment by deilann** [comment]
@Hodizzle please reopen this with your UUID when you have a chance. :)
