### ISSUE TITLE
Checklist to-dos giving extra reward multiplier (n+1 instead of n)

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2324]
The help text for checklist to-dos says that a 4-item checklist will be worth 4x the normal reward. But in the few cases I've tested, an n-item checklist gives me (n+1)x the reward. Is that because the main task checkbox is being counted along with the checklist boxes? Is it intentional?

**Comment by lefnire** [comment]
possibly not intentional, [here's the code](https://github.com/HabitRPG/habitrpg-shared/blob/a89ef25e230ca88d2928bb90ee04bf8bb781b93b/script/index.coffee#L750tL757) - it's just `points * checklist.length` in the end

**Comment by SyntaxPickax** [comment]
I can't reproduce this. Checking off a normal to-do gives me 1 GP 27 SP (aka 1.27 GP), and as expected, I get
1.27
2.54
3.81
5.08
6.35
7.62
8.89
10.16
11.43
12.7
for checking off a to-do with 1 through 10 checklist items, respectively. (Actually, I get 1.27, 2.53, 3.80 etc, due to rounding, but that's not something to worry about.) XP also goes up as expected.

**Comment by colegleason** [comment]
Trying to reproduce on local:
- Todo with no checklist: 1.93 GP, 6 XP
- Todo with one checklist item: 1.93 GP, 6 XP
- Todo with two checklist items: 3.88 GP, 13 XP
- Todo with three checklist items: 5.82 GP, 19 XP
- Todo with four checklist items: 7.79 GP, 26 XP

Those seem about right to me. What numbers are you getting?

**Comment by octern** [comment]
I'm doing this on the website, not on local. The values below show that the behavior I reported is no longer occurring for XP or gold (or maybe I was wrong about it in the first place), but it is occurring for mana:

Single to-do (no checklist)
12 XP
1.64 GP
1.1 mana

To-do with 1-item checklist
12 XP
1.64 GP
2.2 mana

To-do with 2-item checklist
24 XP
3.29 GP 
3.3 mana

To-do with 3-item checklist
36 XP
4.95 GP
4.4 mana

**Comment by colegleason** [comment]
Well, I do see at least one bug here: You get the checklist multiplier
regardless of whether or not the checklist item was checked.

On Thu, Jan 9, 2014 at 12:31 PM, Michael Cohn notifications@github.comwrote:

> I'm doing this on the website, not on local. The values below show that
> the behavior I reported is no longer occurring for XP or gold (or maybe I
> was wrong about it in the first place), but it is occurring for mana:
> 
> Single to-do (no checklist)
> 12 XP
> 1.64 GP
> 1.1 mana
> 
> To-do with 1-item checklist
> 12 XP
> 1.64 GP
> 2.2 mana
> 
> To-do with 2-item checklist
> 24 XP
> 3.29 GP
> 3.3 mana
> 
> To-do with 3-item checklist
> 36 XP
> 4.95 GP
> 4.4 mana
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2324#issuecomment-31961807
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by octern** [comment]
I assumed that was an intentional shortcut. Are there circumstances where someone would check off the main to-do when they hadn't completed all the checklist items?

**Comment by lefnire** [comment]
Yeah, @octern states what I meant with it. Sort of "Check. Check. yadayada yeah yeah, this whole thing's done". I'm open to alternative though

**Comment by colegleason** [comment]
I dunno. At the very least it's confusing since dailies don't work like that.

Here's the bug for MP: https://github.com/HabitRPG/habitrpg-shared/blob/a89ef25e230ca88d2928bb90ee04bf8bb781b93b/script/index.coffee#L847

It should be `(task.checklist?.length or 1)` not `1 + (task.checklist?.length or 0)`

**Comment by colegleason** [comment]
@lefnire, Is the calculation for `user.stats.mp` done on both client and server? Server is now correct (locally), but the browser gets out of sync since it keeps adding too much MP. A refresh works fine.

**Comment by lefnire** [comment]
Well, the `score` function (and anything in habitrpg-shared#user.ops / user.fns) is run the exact same on server & client. Browserify converts that code to client JS, node requires that code for server processing. So that's really strange... hmmm.... *think think think*...

Well anyway, your [comment above](https://github.com/HabitRPG/habitrpg/issues/2324#issuecomment-31963234) finds the MP inconsistency, :+1:

**Comment by colegleason** [comment]
Now it works! I must not have regenerated the JS or something

**Comment by colegleason** [comment]
@lefnire, Why do we commit changes to `dist/`? Aren't those generated files?

**Comment by lefnire** [comment]
@colegleason Oh, I should mention - when you edit habitrpg-shared/script/*, run `grunt browserify` to regen the client code. `grunt` straight up will run the whole compile suite, which includes generating a new spritesheet (which we most often don't want.. I need to remove that from `grunt`'s default...). So yeah, if you'r seeing discrepancies, `grunt browserify`

**Comment by lefnire** [comment]
They're generated from `grunt`. We could add their grunt phases to server startup, but we also use the `dist/` directory for generating our mobile app (which is 80% habitrp-shared, 20% it's own code). We could add a grunt step for mobile in addition to web, and mobile will package it's own dist from habitrpg-shared compile..

Well anyway, we haven't really looked into it I guess, never came up before. Open to change

**Comment by colegleason** [comment]
So do you want commits to include the browserified javascript in `dist/*` or do we let people generate that on checkout?

**Comment by colegleason** [comment]
Ok, cool.

**Comment by lefnire** [comment]
Include, for now. When not included, I notice and run grunt before pushing, so it's no big deal. But convention has been to include, we can start looking into a on-server-start / on-mobile-package solution and stop committing the code
