### ISSUE TITLE
Clarify what “Submissions” are.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2326]
From Tavern:

> I did click the link that says "Friend (1-2)" and that is when I got the "When your first submission is deployed, you will receive the HabitRPG Contributor's badge. Your name in Tavern chat will proudly display that you are a contributor. As a bounty for your work, you will also receive 2 Gems." I am trying to understand what a "submission" is and how you "deploy" it. Look on the left to see what I am talking about.

Note that the links above all reference contributing, and new users, who are most likely to need the legend, are less likely to guess that contributions = submissions and submissions refer to code, pixel art or documentation/user support.

**Comment by SparkNorkx** [comment]
I think the description is clear enough for a normal a English or 2nd language speaker. The user's first sentencing was poor while he/she first asked me about it and I couldn't understand the person at first. So I simply want to point out that the user's English skill might be poor.

Here's the person's sentencing from Tavern.

![screenshot1](https://f.cloud.github.com/assets/6336720/1881229/0b5c33d4-7964-11e3-916c-1878dc6825a6.png)
