### ISSUE TITLE
Day reset itself at wrong time

### ISSUE THREAD

**Issue by Impignorate** [HabitRPG/habitica#2328]
Hi! I'm new to HabitRPG, and I recently changed my custom start time to 6AM because I tend to stay up rather late doing work. I just checked my account to tick off a few dailies, and found that I'd lost twelve health points. My dailies appear to have reset themselves at either 6PM or 7PM, which is incredibly annoying because I'm trying to do a challenge that requires a high streak count. My timezone is GMT/00, so I doubt my timezone is the case in this matter. Any advice? I don't want to lose any more health, ah!

**Comment by colegleason** [comment]
@lefnire Have you pushed the changes yet? Is this caused by them?

**Comment by colegleason** [comment]
@Impignorate, to the best of your knowledge, can you tell me the last few times you logged on within the last 24 hours or so?

**Comment by lefnire** [comment]
changes indeed pushed live

**Comment by colegleason** [comment]
@Impignorate To fix your issue, you can manually adjust your streak count by editing the task. You can also restore any lost health, etc via the 'Fix Character Values' on the Settings page.

**Comment by lefnire** [comment]
Sorry, was on the road. Let me know if you think I should roll-back the
current release

**Comment by colegleason** [comment]
Not sure yet. Trying to debug, etc.

On Thu, Jan 9, 2014 at 2:21 PM, Tyler Renelle notifications@github.comwrote:

> Sorry, was on the road. Let me know if you think I should roll-back the
> current release
> 
> On Thu, Jan 9, 2014 at 1:15 PM, Cole Gleason notifications@github.comwrote:
> 
> > @Impignorate https://github.com/Impignorate To fix your issue, you
> > can
> > manually adjust your streak count by editing the task. You can also
> > restore
> > any lost health, etc via the 'Fix Character Values' on the Settings
> > page.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2328#issuecomment-31971290>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2328#issuecomment-31971896
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by Otavainen** [comment]
I have the same problem, though I can't say exactly when the reset occurred, other than within the past 9 hours when I was offline. No major losses - just wanted to report the issues because in the Tavern chat Cole asked to do so.

**Comment by colegleason** [comment]
@Otavainen when is your Custom Day Start?

**Comment by Otavainen** [comment]
@colegleason At 3 am (EET) = in ~2 hours.

**Comment by colegleason** [comment]
@Otavainen Ok, just so I have it down: you last logged on at around 14:00 EET and then most recently around 1:00 EET and it reset?

**Comment by Otavainen** [comment]
Most recent was around 23:40, otherwise correct.

Please let me know if you need anything else! I'm happy to give you as much data as I can. For tonight, I'll log off in ~15 mins though, it's getting so late here :).

**Comment by colegleason** [comment]
Thanks! I'll look into it. Could you post your UUID and let me know if your
dailys don't reset correctly tomorrow?

**Comment by Otavainen** [comment]
UUID is the same as Settings > API > User ID, right? If so, that's 46db85df-e36c-4dfe-88bc-eb6ba93afbc8.

I'll report back tmw. Thanks for reacting so quickly - you guys are amazing!

**Comment by Impignorate** [comment]
@colegleason Hi! Apologies for the late response! I have my Habit tab open at all times, so I've only technically logged in once today when I switched on my laptop (which was about seven hours before the reset happened). I've since reset my values and streak count, which was a bit of a hassle but manageable enough. I've decided to keep my custom start time at six rather than restore it to midnight, just to see if it resets properly.

**Comment by Impignorate** [comment]
@colegleason If you need any extra information, let me know! Thanks for your help!

**Comment by Otavainen** [comment]
@colegleason The issue looks fixed: dailies have reset normally, no HP loss. Anything else you need?

I'll keep an eye on this for a while and let you know in this ticket should there be any more problems. Thank you!

**Comment by deilann** [comment]
Reset my cron to 1000. Was 2300. Cron went off at 2300 anyway. e7b5d1e2-3b6e-4192-b867-8bafdb03eeec

I used to have no problems with changing my cron. Now, it seems like I can't change it at all (either changing it triggers cron, killing me, or it doesn't change, leaving me with another cron coming up shortly that will kill me.)
