### ISSUE TITLE
Have HabitRPG Veteran badge but no wolf after leveling up to 4?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2329]
I'm kind of excited about pets but only just leveled up to 4 to unlock them. I do have the Turkey pet from Thanksgiving (even though I couldn't use it at the time, which was great) but I was reading that veteran users got a "veteran wolf" pet, and I don't see it anywhere. Shouldn't I still have the pet even though I wasn't level 4 at the time it was given out?

**Comment by lefnire** [comment]
UUID?

**Comment by ghost** [comment]
3c735bf8-8e39-4fb6-ae02-092b910fe89a

**Comment by deilann** [comment]
I also have the badge, but no wolf: e7b5d1e2-3b6e-4192-b867-8bafdb03eeec I assumed that it was a "you have to buy this for free in the store on this exact day thing," but if I was supposed to get it, I would like it.

**Comment by wc8** [comment]
If you were using HabitRPG before the cut-off date (spring or summer of this year?), you qualify for the badge and the wolf.

**Comment by lefnire** [comment]
I'll run a migration of Monday, out for the weekend

**Comment by Iloenchen** [comment]
I've got the badge and am missing the wolf, too. My user ID is a3d80579-f18f-4b2b-a170-ce1064f755fd

**Comment by n-luca** [comment]
Same here. User ID 3b44fdf0-196f-4786-a2e1-9ffa56803d58

**Comment by SeanStiny** [comment]
I also don't have the wolf but I have the badge.

User ID: 776d604e-b3d4-4b61-8c7a-6928ef24e40a

**Comment by lefnire** [comment]
Ran the following, y'all should be all set now

``` javascript
db.users.update({'achievements.veteran':true},{$set:{'items.pets.Wolf-Veteran':5}},{multi:1});
```
