### ISSUE TITLE
Typo in the Trapper Santa defeat screen

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#2330]
It says "squeels" when the correct spelling would be "squeals".
![mzgjbob](https://f.cloud.github.com/assets/6363204/1882017/c1d7ecb0-796f-11e3-8024-9199a09a6b86.png)

**Comment by speg** [comment]
fixed typo in PR https://github.com/HabitRPG/habitrpg-shared/pull/88
