### ISSUE TITLE
Negative unallocated attribute points after reset

### ISSUE THREAD

**Issue by boberthepker** [HabitRPG/habitica#2332]
I made it up to level 20-something, but couldn't stay alive more than 2 days. I did a reset and have worked my way back up to level 5, but I just realized that I have -14 attribute points. It can't be corrected via "Fix Character Values". Is there any way to correct this?

![image](https://f.cloud.github.com/assets/5184730/1882403/8566bf9e-7975-11e3-9240-0db7f99fc923.png)

**Comment by lefnire** [comment]
Keep "auto allocated" turned off, and level up once - should work. We'll
fix when we get a moment

**Comment by boberthepker** [comment]
@lefnire Thanks for the recommendation, but I've leveled up 4 times and it's still negative. Thanks in advance for the perm-fix.

**Comment by strasznyobibok** [comment]
The same error on my account: I had -14 points to distribute after reset. Now, after leveling up, I have -7. It's a progress, I admit, but a very slow progress, I'm afraid.

**Comment by deilann** [comment]
Curious -- did you level up 7 times or just once?

**Comment by Alys** [comment]
A similar issue was reported in https://github.com/HabitRPG/habitrpg/issues/2496 with other details so I'll close this one. Anyone who wants to follow the progress of this bug fix can subscribe to notifications in the other issue (button in right-hand column).
