### ISSUE TITLE
Cannot recieve email from community site

### ISSUE THREAD

**Issue by neuroillogic** [HabitRPG/habitica#2333]
So I cannot create an account or talk to anybody, I got an error that said it could not send email, but when I tried to register again it said the email was taken. I tried to change my password and I got the same error saying it could not send email. Help please? I would love to join a party.

**Comment by wc8** [comment]
What's your username on the forums?

**Comment by neuroillogic** [comment]
neuroillogic

**Comment by gem322** [comment]
I am having the same problem, my username is gem322.

**Comment by lefnire** [comment]
*groan* can we start using something else yet? Does the wikia support forums?

**Comment by wc8** [comment]
@lefnire yes

**Comment by wc8** [comment]
In fact, there's this: http://habitrpg.wikia.com/wiki/Board:LFG_Board

**Comment by lefnire** [comment]
ooo ooo let's do it! let's move LFG over, we'll keep the community site up but link nothing to it

**Comment by wc8** [comment]
Related http://habitrpg.wikia.com/wiki/Special:Forum#

Main feature missing I can think of might be equivalent poll options, but we could figure something out. There is a voting page option somewhere.

**Comment by wc8** [comment]
I added entry level coding for
- [x] point links to wiki Special Forum

BTW, I had just finished resetting:
- [x] neuroillogic to 'removed' (so @neuroillogic should be able to go there, login and reset password)

**Comment by neuroillogic** [comment]
Thank you for the help, though I am still getting the same error message, I will try and post to the wikia and see if I can find anyone there. I hope it picks up!

**Comment by lefnire** [comment]
closing this, migrating full-swing to Wikia (added a notice on the comm site, and changed the website links). Time to ditch that rickety site
