### ISSUE TITLE
Problem registering for community forum

### ISSUE THREAD

**Issue by lanthanides** [HabitRPG/habitica#2337]
Hi all! 

I've been trying to create an account to post on the community forum. However, every time I submit the form I receive a red box stating that the email wasn't sent, followed by a green box saying that the email was sent. So far I haven't received any emails. 

I've tried registering under four different email addresses and usernames, and have even tried creating an account using my phone's browser, but neither have worked so far. Attempting to re-register under a previous email address or username doesn't work, either, as I get a "this name is already taken" or "email address ___ is already registered" statement.

I'd really appreciate some help on resolving this issue. My most recent username is "actinides.". Thanks in advance!

**Comment by wc8** [comment]
#2333 related

**Comment by lefnire** [comment]
Hey @lanthanides, we're gonna try moving all LFG to http://habitrpg.wikia.com/wiki/Board:LFG_Board . The community site has historically be a bit of a mess, so post on the wiki for LFG and we'll start moving people your way

**Comment by lanthanides** [comment]
@lefnire Sounds good, thanks for the heads-up.

**Comment by lefnire** [comment]
Closing this, will update the LFG links and I added a block to direct people
