### ISSUE TITLE
Trouble With The Forum

### ISSUE THREAD

**Issue by Caytlynn** [HabitRPG/habitica#2338]
I attempted to sign up for the forums and join a party today, but my email didn't go through properly. I got the error message accompanied by the confirmed message, like several other users on this help site. There is a specific party I'd like to apply for, so moving to the wiki forum might not be an option, unfortunately. 

The username I used was Caytlynn. If I need to post my email as well I can but I'd prefer it not be up on a public forum like this if it doesn't have to be. Please help whenever able, I recognize that this issue has to be solved on an individual basis :)

**Comment by wc8** [comment]
Hi, we're moving LFG (Looking for Group) posts here: http://habitrpg.wikia.com/wiki/Board:LFG_Board

This is part of #2333

I'll be closing this, since the using the new board is the solution, but if you have any trouble, comment back. I think you might not even need to sign up for wikia to post there. (Although it would record your IP address, not sure if you want that.)

**Comment by vimaleshking** [comment]
Hey there, fellow Habiticans! Guess what? I've been on this Habitica adventure for about a year now. 🎉 I even leveled up to a whopping 110 before hitting the reset button and now winding up at level 57. Life's taking me to the college realm, so I have decided to give away my Habitica account. 📚🎒
Here's the loot you'll get:
-A posse of normal pets, a bunch of magical potions, and more quest pets than you can shake a stick at. 🐾🔮
-Loads of pet food(174), got some cake, 145 eggs (that's a lot of omelettes), and 161 magical potion stash that would impress even the most seasoned alchemist. 🍳🍼
-Wardrobe? Oh, I've got a collection of costumes that would make any fantasy character jealous. Full warrior and mage sets, some bought with gems like a true VIP. 🧙‍♂️🎭
-I wield the title of "Warrior," and let me tell you, my single smash can hit for an impressive 40.01 damage. That's some heavy hitting right there! 💥
-As if that's not enough, I've got a hoard of 8,456 gold coins piled up like a dragon's treasure trove. 💰🐉
-As a bonus you get 1 gem which you can use in seasonal shop, to buy some costume 
If all this treasure's got you intrigued, slide into my DMs Instagram @billy_ray_x_ (yep, that's right, I said it) and I'll toss you my profile so you can take a peek. Adventure awaits, my friends! 🌟🗺️
