### ISSUE TITLE
Confirm message before delete

### ISSUE THREAD

**Issue by PiNotEqual3** [HabitRPG/habitica#234]
If you miss click delete on task, habits, ... it gets deleted without delay and there is no way to undo this. For good reasons this is a stand behavior in any application. Would be nice to have this here too. Otherwise you might lose an important habit and its history.

This would fix it:

```
onclick="return confirm('Want to delete?');"
```

**Comment by lefnire** [comment]
if your task has any history items, or is below a certain value threshold - it asks you. basically you can only quick-delete your task if you only recently created it. I can change that if that's what people want.

**Comment by horusofoz** [comment]
I think a confirm deletion dialogue regardless of history would probably be preferred by new users. It may get annoying when deleting the example tasks but better that than accidentally deleting new tasks which I know I have done multiple times.

**Comment by PiNotEqual3** [comment]
Ah sorry, I did not see that. Sounds good! I would leave it as it is.

**Comment by horusofoz** [comment]
As original requester has withdrawn request, I figure close this ticket. My thinking is "nice to have" rather than need. Close her up @lefnire.
