### ISSUE TITLE
Linebreaks no longer working in the chat

### ISSUE THREAD

**Issue by Snellopy** [HabitRPG/habitica#2341]
Something so minor I almost didn't report it, but if everyone thinks that way, then you'll never know it needs fixing.

Shift+Enter isn't making a new line in chat in guild, tavern or party, and a completely blank like for a new paragraph has never worked. 

I'd tag this with priority minor, but I don't know how to do that sorry.

**Comment by hattieshoe** [comment]
I also noticed this not working today (I know it was working 2 or 3 days ago), and I would also appreciate the possibility for a blank line in between paragraphs if it's possible.

**Comment by wc8** [comment]
hm... shift+enter twice gets a new line for me same as before.

**Comment by hattieshoe** [comment]
Yeah, it works now for me too. Maybe it was a temporary glitch? Snellopy, is it working for you now?

**Comment by Snellopy** [comment]
Nope, still not working for me. I thought it was at first because I was trying to do a lot of linebreaks and bolding as well (I've an acrostic for the pilgrimage) but when I tried a little simple one like yours WC8, it still just got smooshed together

**Comment by wc8** [comment]
what I have to do is:

> first line [SHIFT+ENTER]
> [SHIFT+ENTER]
> second line 

It also works to copy:

> test
> 
> test
> 
> test
> 
> @Snellopy 

Results in Tavern. 
What happens if you copy and paste that quote as it is?

**Comment by snicker** [comment]
two blank lines for a linebreak is standard markdown.
