### ISSUE TITLE
Streaks gone, HP down

### ISSUE THREAD

**Issue by planetaryalien** [HabitRPG/habitica#2342]
So a weird thing just happened with my HP and streaks as well as my habits. 

I'm up late today because of work, so I tried to move the reset time for my day,so I could get my dailies done while my day is still ongoing. The day reset regardless of the extra two hours I'd tried to tack on, so HP went down as expected, although earlier than I wanted my day to end, also earlier than my usual time for reset and later than the default reset. 
It seemed a rather arbitrary moment to reset really, but I kind of brushed it off because it's still experimental, and I didn't really mind anyway. 

I decided to carry on as I would normally, checked off the last dailies, but when I clicked one of my habits, suddenly another 28 or so HP went down and everything seemed to reset itself again.
Now all my streaks are gone, even the dailies I had clicked in the last 5 minutes to finish up my day, had reset themselves again. Again at a seemingly arbitrary time (not the time I'd set it for either, not any of the times that would make any sense).
All my stats are severely out of whack now as well -- habits and dailies that were in the green/blue are back to yellow and one that was yellow is now in the green...

Is this just because of the experimental time-setting and I messed with it at the wrong time?

Not sure it it's needed but user ID is: 568445a8-ce63-430a-88d1-b8950f91cf0b

**Comment by colegleason** [comment]
Yeah, cron seems to be a bit out of whack right now, _especially_ if you move your custom day start time. We are looking into it.

Sorry! You should be able to restore your health from the settings page and restore streaks on any dailies.

**Comment by deilann** [comment]
Yes, let's follow this at one of the other tickets.
