### ISSUE TITLE
Checklists on Challenge To-Dos?

### ISSUE THREAD

**Issue by ld89** [HabitRPG/habitica#2343]
I didn't see a way to enable them, but they would be mightily helpful. Is that feature not a thing or am i experiencing a bug?

**Comment by wc8** [comment]
Users can add them, creator can't.

**Comment by ld89** [comment]
Oh, yikes. I have a list of roughly 25 To-Dos that I wanted to put four checkboxes each on. (Or I'd have to make about 100 To-dos, which, also yikes.) I would really hate to have to ask anyone who joined to manually do the checklists themselves D: Are there any plans to make it so that challenge creators can do them and save everyone else the trouble?

**Comment by wc8** [comment]
#2205 I think this is a related discussion. 
It's not final—I don't think.

**Comment by ld89** [comment]
Ah, okay - thanks so much!! I'm not familiar with the etiquette here. Should I comment on that thread and leave my vote or something? I just think it'd be a lot easier to have uniform checklists if the challenge creators could do them, and save the challenge-ees, so to speak, a lot of trouble.

**Comment by deilann** [comment]
I'd comment there, as it saves clutter. /belated
