### ISSUE TITLE
Quests not feasible to solo?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2345]
Hi, I decided to try out the Trapper Santa quest for fun, but I can't get any of my friends to join me in playing HabitRPG so I went solo. Sadly it seems with my current setup (using mostly habits, a few dailies and rarely to-dos) I'm doing very little damage - I did 0.8 damage and I think I can only expect to do a little bit more on a perfect day. The boss's health is 200, so I think it's very unlikely I'd be anywhere near killing him even if I did things perfectly every day.

It's sad because this could be a big motivator for me, but as far as I can understand, it doesn't seem to scale. I'm just not comfortable joining a random party and would like to solo quests, but I don't see this happening with the current setup. Conversely, if I joined a huge party, it seems like I could reap all the benefits by barely even scraping by.

Are you considering scaling the damage to make things more fair?

**Comment by wc8** [comment]
Hi, quests are designed as a party-motivation feature.
That said, you can—depending on your the level, attributes and tasks—beat the Trapper Santa. The achievement's been reported several times in the Tavern. 

You need, from what I remember of Tavern reports, to make sure you don't neglect dailies, do every single one you possibly can. This way, you'll keep alive. Also, record as many dailies as you feel comfortable **committing to**. More dailies, more damage. Also, I hear to-dos help. So if you've got any tasks you're doing, make sure to record them.

If you reach level 10 and have an option for allocating points, certain attributes will help. I think STRength is one of them, but I'm not sure. 

I do like the idea of having a few solo or beginner quests, and the plan—as I understand it—is to have different quests aimed at different kinds of productivity/habit-building situations. So having difficulty with one does not mean you'll have difficulty with another.

Not every quest will have a time limit. From what I understand, the following quest, Find the Cub is easier. You have until Jan 31st to buy it, but I think you can complete it whenever.

**Comment by wc8** [comment]
@lefnire, Monday can you confirm whether or not:
- users can continue the polar bear quest after Jan 31st if it's been purchased by then?
- quests are returned to the scroll chest on Abort if a user needs to restart it?

**Comment by lefnire** [comment]
- users _can_ continue quests / save them for later. We're just removing the scrolls from the market
- Scrolls are returned to inventory when aborted

STR is indeed that stat you want to focus on. Warriors & mages are the best classes for bosses. Cast "burst of flames" and "brutal smash" on your bluest task when you have MP. Do all dailies, and as many To-Dos as  you can. Focus on Reds, or tasks with checklists.

**Comment by ghost** [comment]
So can someone clarify the time limit for me? Is the scroll only available to get within that limit? I was thinking I actually only had until the end of the month to complete it, and then the quest/scroll/everything would be unavailable. But now that I've started the quest and I'm plunking along at 2 damage to the boss can I just keep it open for months and months until I die or win? And if I were to die, is the quest gone or can I try again?

**Comment by colegleason** [comment]
@Stacia, You just need to buy the quest before the end of the month. You
can then complete it whenever. If you abort the quest, the scroll goes back
into your inventory and you can try again. I'm actually not sure what
happens when you die though.

On Fri, Jan 10, 2014 at 2:22 PM, Stacia notifications@github.com wrote:

> So can someone clarify the time limit for me? Is the scroll only available
> to get within that limit? I was thinking I actually only had until the end
> of the month to complete it, and then the quest/scroll/everything would be
> unavailable. But now that I've started the quest and I'm plunking along at
> 2 damage to the boss can I just keep it open for months and months until I
> die or win? And if I were to die, is the quest gone or can I try again?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2345#issuecomment-32062303
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by Fannish** [comment]
In a related note, I have over 25 dailies, and have finished 3 checklist heavy tasks, and have a STR of 87. 

Yet in 3 days of completing all tasks and using my brutal smash at least 2-3 times a day, I've only done1 point of damage. 
I am solo, and due to chronic depression, I've set all my tasks to hard, to try and make sure I actually go out and DO them.

Wondering if it is because I am solo, because my tasks are set to hard, or another bug that is causing this.

Editing to add: Will open a new bug if people think it's unrelated to the Solo aspect.

**Comment by lefnire** [comment]
@Fannish that's definitely a bug. 25dailys, high str, etc - you should be dealing ~30dmg to the boss each morning. I'll look into this in the near future, got some stuff keeping me busy for a bit

**Comment by Fannish** [comment]
@lefnire Did you need my party ID?
(and counted it up, I actually have 42 dailies. >.> I may have over itemized)

**Comment by lefnire** [comment]
UUID & Party ID please, yeah. Even so, 1 daily is 1pt avg. So you should be doing at least 42dmg. Smash is a heavy hit, checklists add dmg, redness add dmg, etc

**Comment by Fannish** [comment]
@lefnire Party ID : a77e686e-b215-429b-9a05-b3c282e7ed87  And it suddenly did 160 damage all at once- perhaps it was just being slow to tally everything? 
Annnd I finally found it- UUID : a62df112-0ba4-4833-864f-24f0163e7ee2

Seems like 160 would be the last two days damage for all dailies and to do tasks I did...

**Comment by tildelowengrimm** [comment]
For what it's worth, I found it a challenge to solo Trapper Santa, but not an impossible one. I do 3-6 habits, have somewhere from 12-20 dailies, and do 1-5 old to-dos every day.
