### ISSUE TITLE
Link issue on HRPG Blog Site

### ISSUE THREAD

**Issue by zoebeagle** [HabitRPG/habitica#2347]
I'm not sure if this is the right place or not, but I noticed on the blog (http://blog.habitrpg.com/), the Android App links to the Spanish page: https://play.google.com/store/apps/details?id=com.ocdevel.habitrpg&hl=es

Instead of the English page:
https://play.google.com/store/apps/details?id=com.ocdevel.habitrpg&hl=en

Not sure if this is how it's supposed to be, but if it is, please close this and ignore me.

Thanks :)

**Comment by lefnire** [comment]
hmm, I changed it but it's not kicking.. I wonder if Tumblr has some cache they bust periodically, I'll check again later to see if the link fixes

**Comment by colegleason** [comment]
Seems to be the English page now.

**Comment by lemoness** [comment]
Almost certainly my fault - all my google pages are in Spanish. Whoops! Good catch!
