### ISSUE TITLE
[Suggestion] Sorting to-do's by due date

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#235]
The colors are helpful, to be sure.  I'm sure this has been suggested before.  I appreciate you guys' patience with my suggestions.

It would be nice if the lists were able to be sorted by date, I guess most specifically the to-do list, to show what's needed to be done today, as opposed to tomorrow or next week.

Thanks.

**Comment by StanLindsey** [comment]
This sort of functionality is being discussed over on Trello, have a look at the card and vote for it at:
https://trello.com/c/i6kXvNY2

Thanks for the suggestions, don't worry about us having to be patient, its fantastic to see the community arising around HabitRPG.

Closed for housekeeping.

**Comment by abednego** [comment]
You don't know how much I want this application/program (what do we call it?) to work for me.  I've been a serial procrastinator my entire life and I've tried every trick in the book, as far as I can tell.  Lump ADD in there as well and I forget the very thing I was supposed to remember not 5 seconds ago.  I've been to seminars, read books, set up Outlook reminders, etc. etc. ad nauseum.  I really want to help, because in the end this will help ME.  ;)

**Comment by StanLindsey** [comment]
Ahaha. Fantastic, personally HabitRPG has helped me a hell of a lot more than my usual method (before this it was just a to-do list on a notepad on my disk) and its great to see that others are getting use out of it. Give all your praise to @lefnire

**Comment by lefnire** [comment]
Woooo!

**Comment by damian-m-g** [comment]
Hi, I wonder what's the format used to write correctly the "Due date". I've not found any information around, perhaps you could make a "tooltip" arise showing that information when the user puts the mouse over it.
