### ISSUE TITLE
When registering, I received an error (confirmed by second test)

### ISSUE THREAD

**Issue by xtraorange** [HabitRPG/habitica#2355]
When using the registration form, I filled out the information and clicked register.  I received the following error message:
"Something went wrong, please refresh your browser or upgrade the mobile app"
Upon clicking OK, the browser refreshed and everything continued fine.

I repeated registration a second time to confirm that this is a regular issue, not a fluke.

I'm on a Mac, 10.7.5, using Chrome 31.0.1650.63.

**Comment by lefnire** [comment]
Shoot, can't replicate. I'll check back again here later, or if someone else can replicate

**Comment by xtraorange** [comment]
To be clear: I just confirmed again, same procedure, same error.

**Comment by SabreCat** [comment]
I can see this running locally too, Chrome on Win7. Nothing spits to the JS console, alas.

**Comment by negue** [comment]
@SabreCat @xtraorange is this still happening?

**Comment by SabreCat** [comment]
I haven't seen this during my recent testing. Can probably be closed until if/when it crops up again.
