### ISSUE TITLE
Critical Hit on unchecking a daily

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2356]
Which, of course, caused me to lose twice the xp and gold that I had gained from clicking it. Not exactly what I was hoping for from my strength stat!

**Comment by Nurylon** [comment]
I get this relativeily often, and it's especially irritating because my mouse double clicks very often--so then I have to go and click a random habit + to make up for the loss, which feels sloppy.

**Comment by marcelosizer** [comment]
I've just got a negative critical hit by unchecking a to-do.
