### ISSUE TITLE
dailies are refreshed twice and lose hp twice

### ISSUE THREAD

**Issue by sabrinastarfire** [HabitRPG/habitica#2357]
once at 11pm 
and the other one when i woke up this morning
my daily reset is at 2pm
as i havent checked off my dailies for both times, i lost abt 12 hp altogether.

**Comment by colegleason** [comment]
@sabrinastarfire Please add you UUID as we may use it later for debugging.

Do you know how to reset your HP? Settings -> Fix Character Values.

Sorry about this! We're working on it!

On Fri, Jan 10, 2014 at 9:43 PM, sabrinastarfire
notifications@github.comwrote:

> once at 11pm
> and the other one when i woke up this morning
> my daily reset is at 2pm
> as i havent checked off my dailies for both times, i lost abt 12 hp
> altogether.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2357
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by sabrinastarfire** [comment]
80d34f3c-8231-4133-9406-391bdf4449a3
Thank you

**Comment by octern** [comment]
Not sure if this is the same thing that happened to me, but I do seem to have taken more damage than I should. I had 20 HP and died at rollover. I missed 3 dailies, all of them blue, which in my experience do less than 1 damage apiece. I'm also taking part in the trapper santa quest (I'm actually on my second run -- one party member sat it out the first time we completed it, then he used his scroll to start the quest and it asked me to join again). According to the log, Santa did 0 damage at my companion's rollover and 9.6 damage at mine. So unless the damage calculations have changed drastically, this shouldn't have been able to kill me. (though it seems like the damage calculations may have changed, if santa hit me for that much).

**Comment by octern** [comment]
Disregard that, turns out my problem was syncing-related (I checked dailies several hours before rollover, but they weren't counted until after rollover).

**Comment by colegleason** [comment]
That's an odd sync problem. Was this on the website?

On Sat, Jan 11, 2014 at 2:01 PM, Michael Cohn notifications@github.comwrote:

> Disregard that, turns out my problem was syncing-related (I checked
> dailies several hours before rollover, but they weren't counted until after
> rollover).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2357#issuecomment-32105441
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by octern** [comment]
@colegleason are you asking me? Yes, it was on the website. I wrote up a description in #2369.

**Comment by Alys** [comment]
Our cron code has been changed a few times since this was logged so I'm going to close this but we can reopen it if it's still an issue.
