### ISSUE TITLE
Logging in Brings Up A Different Account

### ISSUE THREAD

**Issue by mikicis** [HabitRPG/habitica#2358]
**If when you log on via another computer with your credentials and see a level 1 character, rather than your account, please do the following:**

Check the User ID (you can find this under Settings > API) and see if it matches your other account.
If it does not, delete the level 1 account.

This should solve your problem.

*_Original ticket: *_

I can access my profile in Google Chrome, but whenever i try to sign in on other computer using my username, i get signed to an account with level 1 and with another user id, api token and with basic tasks.

**Comment by colegleason** [comment]
Have you ever used Facebook to login?

**Comment by mikicis** [comment]
Not in the combination with this account. The username is miki.cis
I should have user id 092c3624-d6e5-46b7-90a9-380b932c44d1
but when i log in on other computer with my username, the user id shown is
7968f727-782d-4885-bc51-214b970d11de
It's driving me little bit mad, because i can't access my tasks from
another pc or from mobile...

2014/1/11 Cole Gleason notifications@github.com

> Have you ever used Facebook to login?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2358#issuecomment-32092168
> .

## 

_M.V. Císaøovský_

_http://www.dotekomanie.cz http://www.dotekomanie.cz_
_http://cisarovsky.blogspot.cz http://cisarovsky.blogspot.cz_

**Comment by colegleason** [comment]
Oh dear. This is a problem. There are two users with that username. I think they are both your account as they were created around the same time.

@lefnire We don't force uniqueness on usernames, do we? Is the password salt on these two users somehow the same?

**Comment by colegleason** [comment]
Wow, please just ignore everything I said in the last comment, as all of it is wrong.

**Comment by mikicis** [comment]
I think the passwords are same... I've encountered this problem when i tried to sign-in to
the android app. Can you delete the account with UUID
7968f727-782d-4885-bc51-214b970d11de ?

**Comment by deilann** [comment]
@lefnire Can you handle this one?

**Comment by mikicis** [comment]
@deilann I handled it myself, i went to settings of the account i didn't want and deleted it myself ;)

**Comment by deilann** [comment]
Wowwwww, I can't believe I didn't even think of that. Good job @mikicis !

**Comment by lefnire** [comment]
Awesome! I didn't think of that either, let's start recommending it.

**Comment by mikicis** [comment]
I was just hoping it wouldn't delete both accounts :D

2014-02-12 19:15 GMT+01:00 Tyler Renelle notifications@github.com:

> Awesome! I didn't think of that either, let's start recommending it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2358#issuecomment-34897989
> .

## 

_M.V. Císaøovský_

_http://www.dotekomanie.cz http://www.dotekomanie.cz_

**Comment by lefnire** [comment]
and... it didn't, right?

**Comment by mikicis** [comment]
It didn't :) I just had to be careful and check twice wich UUID i was
deleting.

2014-02-12 19:18 GMT+01:00 Tyler Renelle notifications@github.com:

> and... it didn't, right?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2358#issuecomment-34898276
> .

## 

_M.V. Císaøovský_

_http://www.dotekomanie.cz http://www.dotekomanie.cz_

**Comment by deilann** [comment]
@lefnire I'm gonna edit this ticket with the DIY solution, a more clear title, and make it a hub.

**Comment by Alys** [comment]
FIXED! Duplicate accounts can no longer be created (excluding duplicates created deliberately (sort of) using different-case email addresses which we're fixing in https://github.com/HabitRPG/habitrpg/issues/5126).
