### ISSUE TITLE
Development docs

### ISSUE THREAD

**Issue by Melevir** [HabitRPG/habitica#2361]
It seems that there is not enough docs for smooth start for contributors. This is what I miss much:

1 Localization docs. This is what readme says:

```
All the old files in /locales has been moved to /locales_old.
```

There is no `/locales` or `/locales_old` at dev branch! I'll be glad to help translating the project, but no one tells me where to start. Please, add more docs about localization process.

2 Tests. Here is quote from `test/README.md`:

```
We need to clean up this directory. The *real* tests are in spec/ mock/ e2e/ and api.mocha.coffee.
```

There is `/test/spec/` and `/test/e2e/`, but no `/test/mock/`. There is no docs that says how to run tests (is `/test/run_test.sh` outdated? It fails for me). More docs on testing would be awesome.

Maybe this issues should be obvious for js developers, but anyway, there should be docs about that, isn't it?

**Comment by Alys** [comment]
We now have information about tests in [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths#Tests), and there's a lot of information about translations in [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists), with pointers to that from readme files in the locales directories.
