### ISSUE TITLE
Mobile app - Store displaying for level 1 character

### ISSUE THREAD

**Issue by tomvaughan77** [HabitRPG/habitica#2362]
The item store unlocks at level 2 on the web page, however my level 1 character has it displayed under the rewards tab on the mobile app.

**Comment by deilann** [comment]
@lefnire Is this current?

**Comment by lefnire** [comment]
Yes still an issue, but minor

**Comment by negue** [comment]
@tomvaughan77 @lefnire Does this issue still exist?

**Comment by lemoness** [comment]
We want to make the store visible for all players at the opening
eventually, so I think this can be closed.

**Comment by Alys** [comment]
store is now visible on website for level 1 players (after ticking off first task)
