### ISSUE TITLE
Setting up account with Community Site

### ISSUE THREAD

**Issue by Rhoadey** [HabitRPG/habitica#2365]
I gave my email and a password to sign up, and it simultaneously said that I was signed up and that an email couldn't be sent to my email account. When I tried registering again, it said I couldn't use my chosen username (because it already existed with the account I just created prior), but still no emails have arrived regarding an account. Is the issue on my end? Is a Gmail account a problem?

**Comment by lefnire** [comment]
We're no longer supporting the community site, everything's been migrated to the Wikia. We'll be removing any links to it over time, and _possibly_ take it down eventually (it's got a lot of content.. so maybe we'll just de-SEO the heck out of it instead). Head to http://habitrpg.wikia.com/wiki/Special:Forum
