### ISSUE TITLE
Dailies won't update

### ISSUE THREAD

**Issue by Rhoadey** [HabitRPG/habitica#2366]
I was in the inn for a couple days, but now my dailies won't update. They're still showing as "done" from a couple days ago.

**Comment by colegleason** [comment]
Please provide:
- Your UUID
- Your Custom Day Start Time
- Your Timezone

Just to make sure, have you tried refreshing the page?

Sorry about this!

**Comment by lefnire** [comment]
Actually, what happens with the inn is the day you check out is acts as the day you checked in. It's kinda "time freeze", so you won't roll till the next morning. See https://www.evernote.com/shard/s17/sh/a90261df-9704-4ef3-9baf-a033cd03ee22/42ff6b368d413a16efd97a2aea6471f0

**Comment by Rhoadey** [comment]
No worries! I tried refreshing. 

UUID: 2d323ffd-29f3-409d-b811-dcac8f93362b
Day start time is at midnight (or 0:00)
Timezone: Pacific (US - California)

**Comment by Rhoadey** [comment]
Thanks Lenfire!

**Comment by lefnire** [comment]
It's something we're going to change, we're still figuring out how to handle checking in/out of inn (it's the way it is currently to prevent abusing check-in at night then checkout in the morning just to avoid HP loss). There are some links with conversation around the topic I don't have handy (in a rush), but I wanted to chime in to let @colegleason know it's not to do with cron code
