### ISSUE TITLE
Scrolling in Internet Explorer 11 causes the entire UI to vanish

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2367]
For example, scrolling down on the /tasks page or the /options/profile/avatar page in IE 11 causes the page to go blank. Tested on Windows 8.1. My user ID is solidus-flux. I don't see any JavaScript errors happening in the debugger when scrolling/screen-vanishing.

There is also a horizontal scroll bar. It's as if the canvas is tens of thousands of pixels wide. I don't know if this is related.

I know I might get laughed at for submitting an IE bug, but I'm hoping this gets fixed because this is the only decent touch browser I can run on my Surface Pro 2, and I really love my SP2!

Interface:
![image](https://f.cloud.github.com/assets/1690206/1894689/3ddfa3a0-7af8-11e3-93a9-2809e0400450.png)

Interface after scrolling down one tick with the mouse wheel, or swiping a tiny bit with touch:
![image](https://f.cloud.github.com/assets/1690206/1894693/4ba13ce2-7af8-11e3-8e94-879d9e6abe98.png)

**Comment by brightbold** [comment]
Yes! I just noticed this on my Windows virtual machine. I thought it was something weird about the VM. In addition, if you set Document Mode to IE 8 or lower, the entire interface disappears whether you scroll or not. Makes it hard to  do cross-browser testing (but maybe we don't care about IE<9, which would be awesome actually.)

**Comment by ghost** [comment]
I think it's perfectly reasonable not to support IE < 9. I'd even be fine with IE 10 and up (Windows 7+ or Surface required). Windows users always at least have the option of using Chrome or FF. Surface users don't really have the option, as IE is the only real touch browser on Surface.

**Comment by lefnire** [comment]
dupes of #2271 #2262 , follow #2262

**Comment by ghost** [comment]
Oops, I searched and still missed it I guess.
