### ISSUE TITLE
Checklist dailies should not reset on days they are not due.

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2368]
I decided to try a new method of tracking cardio throughout the week. I made a Daily that was only due Sunday, with a checklist for doing cardio three times a week. I assumed that the checklist items would not reset until the Daily was active, but this morning I found that all of the checked items had reset.

I would like to suggest that checklisted items do not reset on days that the Daily is not due. I think checklists have a lot of potential for tasks that need to be done multiple times a week, but not on fixed days, such as fitness and cleaning.

**Comment by octern** [comment]
This is an ingenious idea for implementing a much-requested feature. Makes a lot of sense to me.

**Comment by wc8** [comment]
I generally like this, but what about maybe-daily tasks, where you might need to do something two days in a row or you might not need to do it at all?

**Comment by lemoness** [comment]
Hm. Can you give a hypothetical example? Those sound like they might need
separate features.

**Comment by wc8** [comment]
@lemoness the best example I can think of off the top of my head would be a checklist for variable housekeeping needs (e.g. laundry) that become due at an unpredictable rate but if due is a daily. There are, however workarounds I can think of for those. There are no good workarounds for weeklies, so I strongly favor this idea, the more I think about it.

Proposed tweak: checklisted items do not reset on days that the Daily is not due, **unless** it is never due, then it resets daily.

**Comment by lemoness** [comment]
Ah, I just put laundry as a To-Do when it becomes necessary! I think when
Due Dates are implemented fully, that will contribute to fixing that. BUT,
in the meantime, your solution sounds good!

**Comment by kuiperbelter** [comment]
I strongly favour this idea!

**Comment by deilann** [comment]
@wc8 Daily resets when checked would get you the best of both worlds.

**Comment by Alys** [comment]
This was done with the skills rebalancing: https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382 and https://github.com/HabitRPG/habitrpg/pull/4736
