### ISSUE TITLE
Party Chat Notifications

### ISSUE THREAD

**Issue by fuzzytrees** [HabitRPG/habitica#2371]
Before the site was re-worked, there was a little black speech-bubble that used to pop up whenever someone posted in your party's chat. It disapeared with the rework. I sort of expected it to come back, and it hasn't, and I find I've been missing lots of notes from my party. It takes away from the community-encouragement thing.

So, bring it back, please? Perhaps in a form that makes it more obvious what it is.

**Comment by fuzzytrees** [comment]
You could use this:

![party_chat](https://f.cloud.github.com/assets/4355305/1895442/f2c7c4b0-7b2e-11e3-8508-d74ea0569111.png)

**Comment by lefnire** [comment]
We know, it's just a difficult feature to bring back. In the queue for when we have time to hit chat enhancements

**Comment by shirtandtieler** [comment]
I don't know if it's bad etiquette to bump old posts (new to github) but I'm surprised this isn't a more highly suggested thing. I guess it's something that isn't very hard to remember but somehow my party members never seem to remember to check it :/

**Comment by deilann** [comment]
Don't worry -- it's a very highly suggested thing. Right now, though, site
stability is top priority.

**Comment by lefnire** [comment]
√

**Comment by shirtandtieler** [comment]
Holy crap, Tyler/Rest of Habit Team you're the best! Talk about quick response! (I realize this was a WIP before I bumped this topic haha)

**Comment by fuzzytrees** [comment]
Yaaaaaaaay!
