### ISSUE TITLE
Attributes readout in profile modal is a bit cramped

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2372]
Was looking at some party members' stats, curious about the meaty buffs @DanielTheBard was handing out, and noticed the attributes column gets rather squashed in the modal:

![screenclip](https://f.cloud.github.com/assets/4501321/1895604/3393b240-7b45-11e3-9c15-61cb374bff4c.png)

This is in part my own doing; I wasn't thinking of profile modals while working on adding more verbose and helpful details to the overall Stats page. Some possibilities for addressing it:
- Hide the help bubbles when you're not looking at your own attributes page.
- Make it a single-column layout, with achievements showing up after Attributes or vice-versa.
- Use more abbreviations when looking at someone else's profile (just "CON" instead of Constitution (CON), etc.).

**Comment by Alys** [comment]
To me, this looks to be fixed. Reopen if I'm wrong.
