### ISSUE TITLE
Dailies not Resetting

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2376]
It has been two days and some of my dailies that I did on Friday still have not reset.

**Comment by ghost** [comment]
I changed the Custom Start Day settings and then clicked on one of the Dailies that I have done today that hasn't been greyed out and it suddenly reset everything. But Iost health in the process, but I fixed it back to normal.

**Comment by ruinofeventide** [comment]
I am having a problem with the dailies not resetting after leaving the inn.  :(  Is there any way to get them to reset to do them today (as I still have chores to do today, but I can't seem to tick them off as they are ticked from a previous day).  I have tried doing the above (changing start day settings and clicking on one of the dailies) and it didn't work.

**Comment by colegleason** [comment]
@ultimagal You moved your CDS forward or backward?

@ruinofeventide Daily progress freezes when you check into the inn. They willl reset after your next daily roll over.

**Comment by ghost** [comment]
@colegleason I moved it one hour back from the current time.

**Comment by deilann** [comment]
Follow non-resetting dailies here now: https://github.com/HabitRPG/habitrpg/issues/1057
