### ISSUE TITLE
Change .completed color to opacity to support emoji?

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#2377]
I'm working on my first commit, but it wasn't as straightforward as I thought so I wanted to run it by people for discussion. Once we started adding emoji to tasks, it bugged me that they were still brightly colored even if the task was completed or disabled for the day. So I thought I'd reduce the opacity on the emoji accordingly.

However, it looks like Chrome and IE create `<span class="emoji">` but Firefox and Safari don't set the emoji off in any way.

So, are there any objections if instead I set the color of `.task-text` back to #333 whether completed or not, and then for `.completed` set both the emoji and the text to `opacity: .4`? (.4 gets the text pretty darn close to #999). Any disadvantages to this? It means older versions of IE will be using a filter. Do we care about older versions of IE? 

If people don't like this solution, then I can just set the opacity on the emoji span and Chrome and IE get this feature but Firefox and Safari don't, too bad for them.
##

**Comment by brightbold** [comment]
Also, it seems I can't assign an issue to myself so if someone wants to assign this to me, thanks.

**Comment by SabreCat** [comment]
Older versions of IE, definitely not. I'd be interested to see how it looks!

**Comment by brightbold** [comment]
OK here are some comparison screenshots of a few options.

0.39 opacity is actually a little closer to #999 so that's my recommendation (I tried 0.385 which might have matched #999 exactly, but turns out opacity is only supported to two decimal places.) So I like 0.39 (version 2) but 0.4 (version 1) is really close too if we like the simplicity of even tenths.

![emoji-opacity-comparison](https://f.cloud.github.com/assets/405068/1897790/9161ddbe-7bfb-11e3-9ae4-6143cf7262a0.png)

**Comment by colegleason** [comment]
V1 or V2 both look good to me!

**Comment by wc8** [comment]
Would it be possible to have done tasks and not due tasks different opacity? 
In other words, so actionable but not due tasks are all full or almost full opacity, but not due tasks are grey like completed tasks.

**Comment by brightbold** [comment]
@wc8 Not as it's currently coded. They both use the "completed" class on the outer list item, so at the `.task-text` level you can't tell whether the task is completed or disabled. Someone could change it so that a separate class was added for disabled/not-due tasks, but it's beyond the scope of what I'm able to do at this point (not getting into Angular and CoffeeScript right now! I've had enough unknown quantities this week with MongoDB, NodeJS, and Stylus that I need to stick to what I know for a little while so I can actually do some paid work!)

**Comment by lorian** [comment]
I'd like to just state that I would be sad if emoji changed opacity; I really like the fact that I can still recognize completed dailies by their emoji. If they turn grey like the rest of the daily, it's going to become even harder to navigate my enormous list of dailies.

**Comment by brightbold** [comment]
@lorian - They don't turn gray, they just fade some. (It's hard to tell from the screenshot above at its reduced size, but if you click it you can see it blown way up and get a better view of the reduced-opacity emoji.) I want the tasks I still need to complete to be the ones that stand out, so for me, it's very distracting to have my eye continually drawn to brightly colored emoji on an otherwise gray task - it ends up drawing my attention _more_ to completed tasks than incomplete ones, because the contrast between the emoji and the background is greater. By reducing the opacity of completed emoji, the whole task is less attention-grabbing, but personally I still find it easy to recognize the emoji and pick a completed task out of my list of 39 dailies.

**Comment by wc8** [comment]
I have the trouble of missing dailies that are do-able, but not due because they are too greyed-out, so I get where @lorian is coming from, which is why I asked if they could be done separately.

I'd rather **hide completed dailies** than opaque completed and incomplete dailies equally. If this affected only completed dailies, I'd have no reservations. 

@SabreCat / @colegleason any ideas?

**Comment by lorian** [comment]
Yes, hiding completed dailies would be so glorious. Although last I saw, the talk about hiding completed dailies was also talking about hiding not-due dailies as well (probably because of the same "completed" class @brightbold mentioned), which wouldn't really help with the relevant issue here.

**Comment by brightbold** [comment]
I would be on board with styling completed and inactive dailies differently, I would just need someone else to create the necessary "inactive"/"disabled" class. But I wouldn't want completed tasks hidden automatically unless there were a setting for it - I'm one of those people who likes to see all the stuff I did to feel awesome about my progress. (When I make paper checklists, sometimes I add things I've already completed, just so the list doesn't seem so overwhelming!) So I'd rather see it work like tags, where you could filter your list on active - not completed; active & inactive - not completed; or all tasks complete and incomplete.

But that's a little off topic. Regarding emoji styling, I feel like the style of the emoji should match the style of the task. Right now, the design is that inactive tasks are gray so as not to call attention to themselves. If this is the design direction, then I feel their emoji should similarly not draw attention. If we make a decision to change the design of inactive tasks so it doesn't match completed tasks, then the emoji style should in in accordance with that new design.

**Comment by SabreCat** [comment]
I'm pro-faded-emoji. v1 and v2 are indistinguishable to my eye (or maybe just on my monitor), so either of those works for me.

I'm having trouble picturing the idea behind styling inactive and done; I get what you're talking about, but I'm not sure how you'd visually go about distinguishing them. Anybody up to the task of mocking something up?

**Comment by brightbold** [comment]
I was thinking about it and I can't think think what it would look like either. I'm open to the idea, but I can't envision how to do it to make it different from completed tasks. Thoughts, anyone?

**Comment by wc8** [comment]
I was thinking something subtle: just don't grey out the text on the not-due, actionable tasks.
*Correction

**Comment by brightbold** [comment]
The only concern I have is that they're not always actionable. You and @lorian clearly have dailies that aren't mandatory but can still be done. I have maybe one of those but most of mine are more like "take out trash and recycling" or "move the car for street cleaning day" which are only relevant on certain days of the week and otherwise I don't really want to see them. 

What's the use case for disabled dailies that you might want to check off? If they're really "weeklies," where you need to do them each week but it doesn't matter which day, then I think we should focus on implementing that functionality instead. But there might be other reasons for having not-due, actionable dailies. The only one I have is professional development reading, which I require on weekdays but it's optional on weekends. 

I guess what I'm struggling with is how we come up with a design that works with the way everyone uses Habit. Right now, the design doesn't work well with the way you use the site. But what you're proposing is less desirable to me than the status quo, given how I use it. So maybe we need filters instead or in addition? Like:
[ ] Show all dailies
[ ] Hide completed dailies
[ ] Hide disabled dailies
[ ] Hide completed and disabled dailies

**Comment by wc8** [comment]
I have a mix: some only actionable specific day(s), some due specific day(s) but can be done on other days (like your professional reading), and 1-2 always grey (check if due, can't always do).

I'd love to be able to filter out the not-actionable tasks, too. (I've wanted the [_Skip Daily_](https://trello.com/c/CSQTy050) someone suggested, which :x:'s a task, and takes HP if was due.)

When someone suggested hiding all not-due, I suggested multiple filters, similar to your list, accessed like the To-Do filters. If your list were implemented, we'd be able to mark off a few Trello cards.

What if _completed_ were very faded and _not-due_ were somewhere in-between?

**Comment by brightbold** [comment]
How do people feel about going ahead with the faded emoji under the current circumstances of completed and disabled looking the same, and then continuing the discussion about making those two different. I could play with some mockups but as mentioned previously, I can't implement that change by myself because I'd need someone else to add the class (not yet ready to get into Angular & Coffee Script).

**Comment by lorian** [comment]
It seems reasonable enough. In all honestly, the non-faded emoji, no matter
how convenient it is, does look like a UI mistake.

Would it be possible/a good idea to just make completed/disabled tasks
slightly less faded, so they were easier to read?

**Comment by kangabell** [comment]
@brightbold Did you make a commit and not PR it? Maybe you should put in a PR so your changes can be merged?

**Comment by brightbold** [comment]
@kangabell I remember I worked on this but I don't know why I didn't do a PR - I think maybe I was waiting for consensus following @wc8's comments, but it seems like this should go ahead and happen. This weekend I'll take a look at where I left off, make sure it was done, and do a pull request.

**Comment by kangabell** [comment]
@brightbold cool sounds good

**Comment by librarianmage** [comment]
@Alys Is this still planned? If so, I could quickly submit a pull request.

**Comment by brightbold** [comment]
Ugh - clearly I haven't had time to follow up. @MathWhiz you should go for it if you have the time; I am totally under water with work right now. Hopefully you will find the experimentation I did in https://github.com/HabitRPG/habitrpg/issues/2377#issuecomment-32142300 helpful and you won't have to spend too much time on it to get it finished.
