### ISSUE TITLE
[Suggestion] XP/Gold bonus

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#238]
I was thinking that it might be nice to give an XP or Gold bonus if you complete all of your daily tasks.  The bonus would only apply if you have more than some minimum number of dailies.

**Comment by mgatten** [comment]
+1

**Comment by horusofoz** [comment]
This is currently under consideration a [Trello](https://trello.com/c/4uWICvDf). Voting for your idea there will help highlight the request to the devs. 

You will see in the description this is currently described as ""Streaks" - Complete all your dailies to start a st[r]eak". Add your voice.
