### ISSUE TITLE
Gem-Less Tavern Challenges

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2380]
I don't believe you've waived the gem requirement for tavern challenges? However, I've seen some as of late.

We've got "sleep better hours," "cycle monitoring with sensi-plan," "learn 250 SAT words," and "Weight Watchers Team" currently.
##

**Comment by wc8** [comment]
I believe there’s a gem requirement, but not a prize requirement—I could be mistaken though. 
Regardless, are you referring to prizes or actually being able to start a challenge without paying gems?

**Comment by lefnire** [comment]
the prize is the same amount of gems they put into creating the challenge, so if we're seeing 0-gem tavern chals, there is indeed a problem. Will look into later

**Comment by hattieshoe** [comment]
I noticed this too -- there's now another one, "Smile more," with no gems -- and I wondered how they're doing it, so I tried all kinds of things to create a challenge for the tavern with no gems (not selecting a prize amount, setting it to zero, setting it higher but changing it to zero, entering a negative number, selecting a guild and then changing it to the tavern, etc.) but couldn't get it to happen. May not be helpful, but I thought there could possibly be a clue in there somewhere so thought I'd mention it.

**Comment by deilann** [comment]
Yeah, I can't figure it out either. Cannot reproduce, but it's certainly happening.

**Comment by deilann** [comment]
Two more have shown up since I last checked. "walk you dog" and... something else.

**Comment by deilann** [comment]
Another one: "max out"

**Comment by deilann** [comment]
Okay, user Black Sheep2 has created two more. Are there any third party ways to create challenges? Could it be that's what bypassing this?

**Comment by wc8** [comment]
API?
https://habitrpg.com/static/api#!/challenges

**Comment by deilann** [comment]
Yeah, but I'm wondering if there are any specific third-party
programs/extensions/integrations that allow creation of challenges.

**Comment by deilann** [comment]
lightsaber sez:

> @!("Ryan") Oh… I didn't knew! I just entered a zero into the gem-field. That's all. I've got firefox 16.0.2 and ad-blocker on a mac.

**Comment by paglias** [comment]
In theory the api has a check for public challenges that should prevent this https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/challenges.js#L137 but probably it's not working

**Comment by deilann** [comment]
Lightsaber seems to be saying that the challenge wasn't created 3rd party
-- just by putting "zero" in the field in Firefox.

**Comment by deilann** [comment]
I'm just wondering what's special about when lightsaber did it and why it
doesn't work for everyone.

**Comment by paglias** [comment]
Yes but internally the same api method should be used
Il 29/mar/2014 23:01 "deilann" notifications@github.com ha scritto:

> Lightsaber seems to be saying that the challenge wasn't created 3rd party
> -- just by putting "zero" in the field in Firefox.
> 
> On Sat, Mar 29, 2014 at 8:05 AM, Matteo Pagliazzi

**Comment by deilann** [comment]
Ah, true. idek. Maybe it has something to do with the adblocker?

**Comment by lemoness** [comment]
Is this still an issue that's happening?

**Comment by paglias** [comment]
Still happening, I just created one with 0 gems prize

**Comment by Alys** [comment]
If you select "Tavern" AFTER you have entered 0 for the gems, the gem amount test does not occur. If you select "Tavern" BEFORE you enter the gem amount, it does occur. Tested on my local install only.

**Comment by TheHollidayInn** [comment]
I was working on another ticket and found this issue. I create a pull request which does the gem check during the $watch and on save phase. Does my pull request fix this issue as well: https://github.com/HabitRPG/habitrpg/pull/4836 ?

**Comment by deilann** [comment]
We're now getting a lot of challenges with no title. This is also still happening.

Challenges with no gems:

https://habitrpg.com/#/options/groups/challenges/d88a8386-261f-48e9-bef0-5222f2cbd0e8 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/3f4868cf-bd63-49e8-8f44-1161b1a5eec1 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/99065ef5-4fef-46f5-b87c-0e657ef35a7b - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/d5911161-8081-4d13-9934-a4d252c1fad6 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/a5c3cc6b-9bb5-4194-bc2e-ff066693c025 - I have no idea what this even means
https://habitrpg.com/#/options/groups/challenges/65cd8293-1f9e-43e7-b0fa-f49a5bf04371 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/00359d56-977d-48fe-9268-afa1b5b193c1 - has decent content, but a strange title. has 55 members. can probably be deleted... there are a lot of challenges with this kind of content.
https://habitrpg.com/#/options/groups/challenges/b4c9a381-812f-469d-be9d-8fb1012647e3 - I think this challenge was supposed to exist only for 40 days and has been around longer. Should probably be deleted.
https://habitrpg.com/#/options/groups/challenges/b9719168-a3d9-4149-9ad8-4e73b8f18e37 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/e154f5e1-a12d-482b-84a8-df5c514084eb - is okay I guess? the creator is a young (about two month account) that hasn't signed on in over a month, though.
https://habitrpg.com/#/options/groups/challenges/592b21b9-cdfb-43d6-a96b-b64afdfe3bd2 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/fa73b48d-d967-4ae4-a2b7-0a4df11771ac - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/364d902d-b843-4d40-ac67-381fd30d5525 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/c391677a-35c6-473b-b15a-81bc8ed55031 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/231b7a76-fe31-4709-bc4c-365354da8209 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/ca847465-6804-4770-a5f7-728af0e02781 - is a decent challenge, but we have tons of "be nice to people" challenges
https://habitrpg.com/#/options/groups/challenges/19ead677-ba7c-4e8c-a4da-1f3da4822cda - is a decent challenge, poorly set up, but should probably be deleted
https://habitrpg.com/#/options/groups/challenges/429a3087-5840-40ed-9546-076fa01583d2 - is actually a really nice challenge :(
https://habitrpg.com/#/options/groups/challenges/781c7c27-689f-466e-9141-55076163859f - has okay content, but many like it
https://habitrpg.com/#/options/groups/challenges/53f64ada-5806-4e30-b1d8-703eae5c4c65 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/b3f83fce-15ee-4c6e-b7ec-6372a60ff923 - is good, but we have a lot of these
https://habitrpg.com/#/options/groups/challenges/54eab07b-76e5-4cf7-a95b-eb73a6d73c1d - is well done? but again, seen a lot of these
https://habitrpg.com/#/options/groups/challenges/a4c09e74-ae02-4baa-9880-ab3a0527f6b6 - over done, should probably be deleted
https://habitrpg.com/#/options/groups/challenges/b98e050b-ad7a-4fa1-9023-4c0821346aed - over done, should probably be deleted
https://habitrpg.com/#/options/groups/challenges/0ab91c96-4974-4115-b2a1-d33a044c52dc - not sure what most of these tasks have to do with not yelling
https://habitrpg.com/#/options/groups/challenges/ead28a22-52ee-4896-8b8e-4d4fa3365253 - another no snooze challenge
https://habitrpg.com/#/options/groups/challenges/4537fe91-0293-4b3b-873f-211349aea0e8 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/7f910d1b-319b-4266-97b1-7af6f7e90827 -  a guitar challenge... should probably be deleted. better for a guild
https://habitrpg.com/#/options/groups/challenges/ad6925ec-482f-443d-8d9d-52946d3e9761 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/74dd400d-c51e-4d25-8d54-f85fdf092bf4 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/b0ea4010-6aad-4726-aa45-87e70354de19 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/577c114f-4eb0-4285-b6d8-b30d7afaff3b - dupe of above
https://habitrpg.com/#/options/groups/challenges/ea7f818a-4b9a-4384-baa3-07e5795d77d7 - better for a guild; should probably be deleted
https://habitrpg.com/#/options/groups/challenges/483cfe1c-9b3c-4c53-aa7c-84bcbe042d42 - should definitely be deleted; became useless mid feb
https://habitrpg.com/#/options/groups/challenges/d8b1462e-ce34-48df-addc-7280d34d6c14 - kind of nice but should probably be deleted
https://habitrpg.com/#/options/groups/challenges/de886093-ff2b-496c-bd84-b5cf5df81eaa - kind of interesting, but should probably be deleted
https://habitrpg.com/#/options/groups/challenges/2cc62c7f-126c-486e-a392-70b601263982 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/cef2c77f-d279-405b-bce5-99c79bc5ed3c - wonderful, but should probably be deleted
https://habitrpg.com/#/options/groups/challenges/6cd394f7-68f8-4597-b58b-11fb3d158585 - seen this before
https://habitrpg.com/#/options/groups/challenges/eb47a846-920b-4d2c-99ba-484b58591968 - nice, but whevs
https://habitrpg.com/#/options/groups/challenges/e4850c22-0b3c-4258-8992-dfd15843a332 - should probably be deleted
https://habitrpg.com/#/options/groups/challenges/726dd737-20e0-4084-99fc-2700af004740 - ........
https://habitrpg.com/#/options/groups/challenges/791e02a8-f1a6-4087-a41e-9e833af6980f - better in a guild
https://habitrpg.com/#/options/groups/challenges/1b8f7176-9ec4-4095-87f4-c1dc83ddcf29 - better in a guild
https://habitrpg.com/#/options/groups/challenges/795d14b1-224d-44c3-be3c-1912aceda3a4 - my face hurts
https://habitrpg.com/#/options/groups/challenges/e1438274-1804-4b6c-a106-c11e85fe2e91 - i'm starting to get tired listing all of these
https://habitrpg.com/#/options/groups/challenges/dc390a98-a580-4ca3-8c17-6bea2df96bb1 - this was a bad plan
https://habitrpg.com/#/options/groups/challenges/90ad5982-b8b6-4e98-aef2-d153d3199983 - i should learn to make better life choices
https://habitrpg.com/#/options/groups/challenges/d294a695-6694-481a-b956-cf0c86c21b88 - and watch what i'm doing

Personally, I think all of them should be deleted. Users can choose to keep the tasks if they desire.

**Comment by crookedneighbor** [comment]
@deilann What do you mean there is no title? Each one I clicked on did have a title. I must be misunderstanding something.

**Comment by deilann** [comment]
All of those are challenges with no gem prize, not challenges with no title. I cannot link to challenges with no title because there is no title to click on to generate a link.

**Comment by crookedneighbor** [comment]
Ahh, I see, you were listing two separate things.

**Comment by Alys** [comment]
@deilann I can clean up ones with no title through the database. I'll go through those others that you've listed and either remove them or discuss with Lemoness. Thank you very not much for the list. :)

**Comment by Alys** [comment]
Ignore my previous (now deleted comment). @deilann and I are chatting about ways of getting more info for those listed challenges for working out how best to deal with them.

I will clean up ones with no title through the database.

**Comment by deilann** [comment]
@crookedneighbor I was not very clear, but by the time I was done listing
all of them, I was too exhausted to look back and see if my sentences even
made logical.

**Comment by crookedneighbor** [comment]
List of challenges with no name:

https://habitrpg.com/#/options/groups/challenges/6cb2c5fc-67bc-4848-943a-844d28637094
https://habitrpg.com/#/options/groups/challenges/ea41af25-6f42-4037-b196-c5df79dfa9f2
https://habitrpg.com/#/options/groups/challenges/e606742c-b097-4f67-b246-10a73ef5f1f4
https://habitrpg.com/#/options/groups/challenges/a0eaddfa-adf4-4956-ad6d-c34481501ace
https://habitrpg.com/#/options/groups/challenges/2e65690c-c213-41af-94be-0ac5e569571d
https://habitrpg.com/#/options/groups/challenges/0344237a-370c-42fb-9ef7-c523b0218cd9
https://habitrpg.com/#/options/groups/challenges/e16224b4-0e19-4cda-b0f0-2592db2fe598
https://habitrpg.com/#/options/groups/challenges/9b06b819-27ce-4880-8226-4f1375e2f7db
https://habitrpg.com/#/options/groups/challenges/6ff9def8-5a91-49fd-9626-a6bb72fe5bd2
https://habitrpg.com/#/options/groups/challenges/072f5a53-94a9-4cc4-94a1-352f72d0b12e
https://habitrpg.com/#/options/groups/challenges/96acc917-4ad4-4d28-af08-baa4eca1dda7
https://habitrpg.com/#/options/groups/challenges/229bc374-5421-40a9-a712-b522edbca100
https://habitrpg.com/#/options/groups/challenges/56d7aff0-bb48-49f6-bebb-e3e31a44cc46
https://habitrpg.com/#/options/groups/challenges/924e86bc-6102-4d1c-a772-b73e0ac3064b
https://habitrpg.com/#/options/groups/challenges/c94460ae-e42c-4d34-a74e-8b685d2f7512
https://habitrpg.com/#/options/groups/challenges/c567a712-a39b-4765-a280-b7ceae2b9a8e
https://habitrpg.com/#/options/groups/challenges/02a85b3b-4901-4631-8354-e54a5a3c819c
https://habitrpg.com/#/options/groups/challenges/6bea6f1c-fc00-498a-91d6-29ff1c2a7640
https://habitrpg.com/#/options/groups/challenges/06eaf715-3d42-4db8-afd6-b65a0deaccce
https://habitrpg.com/#/options/groups/challenges/370497f1-0be0-4bfc-8e3a-752813bb87fb

**Comment by Alys** [comment]
@crookedneighbor I can identify those in the database easily with a search on title and I'll clean them up there as I find them.

**Comment by crookedneighbor** [comment]
Yep, that's what I did. Just posting for posterity. (And in case another mod wants to see)

**Comment by beffymaroo** [comment]
I found this thread very entertaining. Thank you all for your hard work, especially @deilann  ;)

**Comment by Alys** [comment]
The challenges with no name/title have been deleted except for one that was a challenge in a party with one person. I have given it a name (the challenge ID) so that it doesn't come up in future searches. The owner hasn't logged in for a while, so I won't bother telling them, unless anyone asks me to. Challenge ID c567a712-a39b-4765-a280-b7ceae2b9a8e

The deleted challenges all either:
- had no tasks, or 
- had pointless tasks AND few/no participants AND were months old (usually many months)

**Comment by Alys** [comment]
From the Tavern challenges that have no gems, I have deleted the ones below (I saved a copy of each). They were either more than a year old OR had no tasks.

I'll go through the others later, when I'm not using this as an excuse to procrastinate on things that are more urgent. :-/ 

2cc62c7f-126c-486e-a392-70b601263982
364d902d-b843-4d40-ac67-381fd30d5525
4537fe91-0293-4b3b-873f-211349aea0e8
483cfe1c-9b3c-4c53-aa7c-84bcbe042d42
592b21b9-cdfb-43d6-a96b-b64afdfe3bd2
74dd400d-c51e-4d25-8d54-f85fdf092bf4
99065ef5-4fef-46f5-b87c-0e657ef35a7b
ad6925ec-482f-443d-8d9d-52946d3e9761
b0ea4010-6aad-4726-aa45-87e70354de19

**Comment by Alys** [comment]
I've deleted more gem-less Tavern challenges (saved a copy of each). They were either rather pointless or very old.

d88a8386-261f-48e9-bef0-5222f2cbd0e8
e9a119b6-7cc0-46f1-bf86-9b1b125728b4
b4965a66-adda-4cdf-a906-f9e405edc200
77e187e5-d7f8-4d3d-b720-ecc2175ee9be
3f4868cf-bd63-49e8-8f44-1161b1a5eec1
d5911161-8081-4d13-9934-a4d252c1fad6
b9719168-a3d9-4149-9ad8-4e73b8f18e37
fa73b48d-d967-4ae4-a2b7-0a4df11771ac
c391677a-35c6-473b-b15a-81bc8ed55031
ea7f818a-4b9a-4384-baa3-07e5795d77d7
d8b1462e-ce34-48df-addc-7280d34d6c14
de886093-ff2b-496c-bd84-b5cf5df81eaa
cef2c77f-d279-405b-bce5-99c79bc5ed3c
6cd394f7-68f8-4597-b58b-11fb3d158585
eb47a846-920b-4d2c-99ba-484b58591968
e4850c22-0b3c-4258-8992-dfd15843a332
726dd737-20e0-4084-99fc-2700af004740
791e02a8-f1a6-4087-a41e-9e833af6980f
795d14b1-224d-44c3-be3c-1912aceda3a4
dc390a98-a580-4ca3-8c17-6bea2df96bb1
90ad5982-b8b6-4e98-aef2-d153d3199983
d294a695-6694-481a-b956-cf0c86c21b88
a4c09e74-ae02-4baa-9880-ab3a0527f6b6
b98e050b-ad7a-4fa1-9023-4c0821346aed

There's still 21 gem-less Tavern challenges, but they all seem to have some value and some are only a month old. I'll go through them in more detail later.

```
db.challenges.find({ 'prize':0, 'group':'habitrpg' }, {
    'id':1, 'name':1, 'prize':1, 'timestamp':1,
    'memberCount':1, 'group':1, 'leader':1, 'description':1,
    'habits.text':1, 'dailys.text':1, 'todos.text':1, 'rewards.text':1,
} ,{multi:true}).pretty()
```

**Comment by Alys** [comment]
There are no more gem-less Tavern challenges.
