### ISSUE TITLE
Can Feed Pets That You Already Have Mounts Of

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2381]
You can't hatch a pet that you already own, but you can feed pets that you already have a mount of. Is this intentional or an oversight?

**Comment by lemoness** [comment]
It's an oversight! We'll fix it soon, but right now the devs are swamped with some tough critical bugs. Thanks for filing the report!

**Comment by deilann** [comment]
Oh, I figured it was low priority. Just didn't know if there was a ticket
on it, or if devs were aware of it.

**Comment by lemoness** [comment]
Yup, if you can't find a ticket for an issue, it's always better to err on
the side of reporting it. If it's a duplicate, we can always close it.

**Comment by deilann** [comment]
I have a solution for this--

index.coffee line 553
`return cb?({code:401, message:"You already have that mount"}) if user.items.mounts[pet] and (userPets[pet] >= 50 or food.key is 'Saddle')`

should be:

`return cb?({code:401, message:"You already have that mount. Try feeding another pet."}) if user.items.mounts[pet])`

so that it disallows feeding of any pets that you have mounts of, even if it wouldn't cause evolve()

But I'm having a heckuva time testing locally for shared content.

**Comment by colegleason** [comment]
That looks correct. How can I help you test it?

On Sat, Jan 18, 2014 at 9:01 AM, deilann notifications@github.com wrote:

> I have a solution for this--
> 
> index.coffee line 553
> return cb?({code:401, message:"You already have that mount"}) if
> user.items.mounts[pet] and (userPets[pet] >= 50 or food.key is 'Saddle')
> 
> should be:
> 
> return cb?({code:401, message:"You already have that mount. Try feeding
> another pet."}) if user.items.mounts[pet])
> 
> so that it disallows feeding of any pets that you have mounts of, even if
> it wouldn't cause evolve()
> 
> But I'm having a heckuva time testing locally for shared content.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2381#issuecomment-32683789
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by deilann** [comment]
If you have a moment, I'm having trouble compiling shared for my local setup.
