### ISSUE TITLE
Missing Guild Gems

### ISSUE THREAD

**Issue by SiakelA** [HabitRPG/habitica#2382]
Hello, my party (The Silver Council) had 4 guild gems for challenges, and they have recently disappeared. We haven't had any challenges or anything, so where else could they have gone?

Thanks!

**Comment by lefnire** [comment]
Shoot! We'll look into when we can, in the mean time what's the ID of your guild ([under the Group Info section](https://www.evernote.com/shard/s17/sh/0f56e6b1-4408-48bd-9368-6760ac3d3763/5b570abc2deb1112e78f4cb37ed4b9eb)) I'll get you reimbursed

**Comment by deilann** [comment]
@SiakelA Please reopen this with the ID of your guild, so @lefnire can reimburse you. :)
