### ISSUE TITLE
Gems in challenge

### ISSUE THREAD

**Issue by thrappstead** [HabitRPG/habitica#2383]
I put a challenge together worth 5 gems, realised that the daily didn't add so I edited the challenge. The challenge wouldn't update on my account so I deleted the challenge to redo it, and the gems never went back to my account. I feel this is a big problem for habitRPG do to gems are the only thing paid for with real money.

**Comment by thrappstead** [comment]
My user ID is f90dc4e7-cce6-4b83-a138-936e0621e550

also I cant seem to erase the old challenge tag from my account now

**Comment by lefnire** [comment]
Reimbursed your gems. To delete challenge tag, click the edit pencil to the left of your tags and then click the trash-can next to the tag name
