### ISSUE TITLE
spontaneous combustion

### ISSUE THREAD

**Issue by liordon** [HabitRPG/habitica#2385]
a few minutes ago my poor innocent character had died unexpectedly. this should not have happened. I recently leveled up and had about full health, and my unchecked dailies were few and blue, so I see no way they could lower my health by about 40.
in the process of my unfortunate demise I lost that awesome ski outfit you made available for winter time, and I wound really like to have it back.
plus.. just so you know, in case this bug will\have come up again...

BTW, I think you guys are doing an awesome job with this project and I hope I could join you one day :+1:

**Comment by lefnire** [comment]
@colegleason unless you have objections, I'm gonna roll back the cron code. Seeing quite a few mishaps, what say we put that aside and start giving your system-cron setup some attention?

**Comment by colegleason** [comment]
Yeah, I agree. Not sure what's going on. My only hypothesis is that cron may be running twice or something.

Also, what's the status on logging in production? If we start instrumenting the cron code with logging data points, would that help with debugging issues like this? I see a lot of heroku data analysis addons, but I'm not sure what HabitRPG has already or can afford. I could also set up an external data collection service (Graphite instance on EC2) if that would help.

**Comment by lefnire** [comment]
No status on logging cron yet. I'm not quite sure if it would be very valuable, we'd be getting ~10k/day and it might be difficult to parse something useful IMO, unless you have something in mind?

**Comment by colegleason** [comment]
I just figured it would be nice when given a UUID to see why cron ran and why (or why it didn't run).

**Comment by lemoness** [comment]
Also, we should be able to restore the winter outfit, right? I don't think people should lose those when they die.

**Comment by wc8** [comment]
At least, not lose permanently, there should be an option to buy back, regardless.

**Comment by liordon** [comment]
that should be true to any limited edition equipment.
I would suggest buying back whatever is bought with gold and not losing
anything bought with diamonds.
(just saying)

**Comment by deilann** [comment]
Later discussion, implemented, original discussion, rollback fixed? Closing? If incorrect, please reopen.
