### ISSUE TITLE
I and all participants of my party died, even sleeping in the inn.

### ISSUE THREAD

**Issue by rainiermorilla** [HabitRPG/habitica#2387]
This weekend all participants of my party died, even sleeping in the inn. We are facing the Santa Trapper.

To help in tracing of the problem, I wrote the ID of all participants who complained of the problem and the ID of the party below.

party 5e48a15e-6448-4fcb-b996-90f59430c11f
Me c01a0b51-34e3-407c-8a7f-816139a32b27
Mauricio 2618fa63-f162-4575-9a89-08199e02ca45
Sinza b4597033-349c-4282-8aa3-1fa56047cf7f

Sorry for my english, it's not my native language. And thanks for the help.

Best Regards

**Comment by wc8** [comment]
Oh… oh… oh… It’s not a good idea to rest in the inn when facing the Trapper. Your _dailies_ themselves won’t hurt you, but the Trapper will if you don’t do your dailies. Do you have another scroll to start again? 

@lefnire you might need to know about this one.

This directly stems from #2231 I’m going to outline a specific text proposal there.

**Comment by rainiermorilla** [comment]
Thanks wc8!
