### ISSUE TITLE
Quest boss regenerating HP

### ISSUE THREAD

**Issue by inksplotched** [HabitRPG/habitica#2389]
Group ID: ba305520-ff3e-49c4-ac3c-39b8e0516d4d

Party had Trapper Santa down below 200 HP, then one morning it was back up to 300 HP for all quest participants. We have him down to ~200 HP again but by all accounts we should have already finished the quest.

**Comment by inksplotched** [comment]
Note: same party as @wecansexy below. Trapper Santa has dealt 9.8 HP damage to the party since regaining full health.

**Comment by Draayder** [comment]
Just had the same thing happen to my group, Trapper Santa went from 36 HP exactly to 74 HP, now down to 55 after I attacked. I've got no idea what caused it, group ID 2cdac76d-f56a-4dfb-a4fb-363fc6336d79

**Comment by samjross** [comment]
Gryphon regaining HP in my group

**Comment by deilann** [comment]
Let's follow this here: https://github.com/HabitRPG/habitrpg/issues/2657
