### ISSUE TITLE
Suggestion: Cumulative experience points

### ISSUE THREAD

**Issue by mgatten** [HabitRPG/habitica#239]
It would be really nice if the experience point total was cumulative instead of starting over at zero every level. That's the way most games work. 

Having zero experience points really isn't very motivating. It almost feels like taking a step backwards when you level up.

With a cumulative total I would be able to "see how far I've come". It would be a lot more satisfying.

**Comment by horusofoz** [comment]
Graduated to [Trello 112](https://trello.com/c/zwaxlchS). Submit your vote there to show support for your idea and highlight it to the devs.
