### ISSUE TITLE
Getting things done but doing 0 damage to boss is demoralizing

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2390]
Some of my party members have been very demoralized by consistently doing 0 damage to the boss. I realize that 8 dailies and a couple to-dos won't solo him, but I think they should at least be worth a point or two of damage. I feel like you should only do 0 if you don't do anything in Habit for the day, so you can at least feel like you're contributing something to the boss fight.

I suspect the consistent lack of damage is due to mainly doing dailies, which seem to do extremely little boss damage. I have 75 strength, and did 15 to-dos and 36 dailies yesterday, and did 19 whole points of boss damage. Even if everything did only 1 point of damage, I should be doing a heck of a lot more than 19 damage!

**Comment by deilann** [comment]
I think this has been fixed.

**Comment by colegleason** [comment]
This hasn't been fixed yet. My party member did 0 damage the other day. I believe it is a CastError that somehow results in `quest.progress.hp` being set to `NaN`.

**Comment by flora-bonita** [comment]
I am also having this problem with the Vice's Shadow Quest.  I have done all/most of my dailies for 3 days now without dealing damage.

**Comment by Alys** [comment]
I think this has been fixed.
