### ISSUE TITLE
Can't add new habbit 

### ISSUE THREAD

**Issue by Elisabethrose** [HabitRPG/habitica#2391]
I can't add any new Habbits, Dailies, or To do's. This is really annoying as habbitRPG has really helped me, but if I can't use it properly I'll most likely go back to not using it. Please help!!!!

**Comment by lefnire** [comment]
Are you typing into the box to the left of the + button before clicking the + button? The input field needs to have some text in it before you can add it as a task

**Comment by Elisabethrose** [comment]
Yes, I write in the box but when I press the + button, it doesn't so anything :( Thanks for replying so quickly ^_^

**Comment by AtomicSource** [comment]
I am also unable to enter any tasks (habits, dailies, or to-dos) on my Nexus 5 phone, running Android KitKat 4.4.2. I type a word or two in, and press the "Go" key (which replaces the normal enter key), and nothing happens. I tested with 3 different keyboards, same thing.
I don't have any issue entering new tasks on a HTC One X phone running Android 4.2.2, an iPhone 3GS (iOS 6.1.2) or in any browser.

**Comment by AtomicSource** [comment]
This issue has miraculously cleared up for me on my Nexus 5 phone, now. Maybe a reset solved it.

**Comment by Alys** [comment]
The site has undergone many changes since this was logged and I haven't seen recent reports of it, so I'm closing this.
