### ISSUE TITLE
android mobile app selects wrong thing when trying to check off to-dos

### ISSUE THREAD

**Issue by ribbondance** [HabitRPG/habitica#2392]
i downloaded the (official) habitrpg mobile app, and when i tried to check off one of my to-dos (it was on the bottom of the list) it chose the one above it. i tried this several times, and it always selected the one above it, no matter where i clicked. this happened on my sibling's phone as well, and has been happening for a few days (i just tested it, in fact) i use the android app, version... uh, the newest one. ((i dont know if this is the right place for this, sorry!))

**Comment by lefnire** [comment]
can't replicate on the latest 0.0.16 build (yesterday's release), when you upgrade can you try again and check back here?

**Comment by deilann** [comment]
Please reopen when you have a chance to share more, @ribbondance !

**Comment by lefnire** [comment]
I've seen this one pretty frequently filed, do we have a central open ticket for it?

**Comment by deilann** [comment]
Nah, let's make it this one then. I closed it because you couldn't replicate on the latest build and they never responded after that. But if people are still reporting it, it needs to be open.

**Comment by ribbondance** [comment]
sorry, the emails went into my spam folder somehow (aol is really weird...)

it is in fact still doing it on the most recent update.

i have an ipod touch (that runs ios 6) and i recreated the glitch there as well just now.

**Comment by negue** [comment]
@ribbondance Do you still have this bug ?

**Comment by negue** [comment]
Closing this for now, if this problems still happens, we'll reopen this issue.
