### ISSUE TITLE
Accomplishing dailies when not around wifi

### ISSUE THREAD

**Issue by bandwagonkitty** [HabitRPG/habitica#2394]
I don't always have access to the internet and I was wondering if there was a way to check off dailies after the day is through. I had a decent streak and then I went a night without internet and _poof_, bye-bye progress! 

Any ideas?

**Comment by octern** [comment]
Currently the solution is to set a custom day start other than midnight on the Settings screen. That gives you a chance to check off yesterday's dailies first thing the next morning. A more general / flexible solution is being discussed for the future. You can also get an app for Android or iOS devices that will let you log dailies from your phone.

**Comment by paglias** [comment]
We could also register the action date and if previous than day end time, execute it before cron (@lefnire @colegleason )

**Comment by bandwagonkitty** [comment]
I have an iPhone but I don't have 3G so I logged the dailies on my phone but they didn't count.

**Comment by bandwagonkitty** [comment]
I have an iPhone but I don't have 3G so I logged the dailies on my phone but they didn't count.

**Comment by bandwagonkitty** [comment]
I have an iPhone but I don't have 3G so I logged the dailies on my phone but they didn't count.

**Comment by octern** [comment]
@paglias I would love that. I've had the same problem as @bandwagonkitty several times, where I check something before rollover but for various reasons it's not counted until after.

**Comment by octern** [comment]
Also note that in situations like this, you can restore your streaks under "advanced options" for the affected daily.

**Comment by Alys** [comment]
We have plans to implement something like this and are developing requirements in trello, so I'm closing this.
