### ISSUE TITLE
Not a participant in boss battle, despite joining party

### ISSUE THREAD

**Issue by DanielHeath** [HabitRPG/habitica#2398]
User f5feea9c-3a32-445a-902a-75430e1c4b04 created a party (party ID: 93e41c1e-8278-4901-b048-6dcb4a300764), which I joined (userid fc72d2b8-5609-4e33-bea3-36944bba879c).

However, I didn't become a participant in the boss battle (and can't figure out why).

Could it be that I was too low level when I joined?

**Comment by deilann** [comment]
You don't join a boss battle if the quest has already been activated before you join the party. The only way you could join the boss fight is to cancel the quest, reactivate it, and then you accept the quest along with everyone else.

**Comment by lefnire** [comment]
@deilann has the right of it. See http://habitrpg.wikia.com/wiki/Quests#Starting_a_Quest
