### ISSUE TITLE
Accidently sold first egg

### ISSUE THREAD

**Issue by Anrisa** [HabitRPG/habitica#2401]
I didn't know what I was doing and now I don;t have my wolf egg anymore. Any way to get it back?

**Comment by wc8** [comment]
It’s sold for good, but all is not lost. Besides being able to buy gems and buy a wolf egg in the market, you have a fair chance of finding more eggs as you go along. I can’t guarantee, because they drop at random, but wolf eggs are reported to be among the most frequent.

**Comment by Anrisa** [comment]
Thank you :dancer:

**Comment by colegleason** [comment]
You have a 30% chance to find an egg when a drop occurs.
