### ISSUE TITLE
Badges Display String Not Found

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2411]
At least the Ultimate Gear Badge and the Original User badge are displaying "string not found"

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg-shared/commit/966151ebcce26f1bd94c684fa2cb02e82168661d , https://github.com/HabitRPG/habitrpg/commit/178086ef30af96fd629c222ecf888cba55e951af and https://github.com/HabitRPG/habitrpg/commit/2e12ffefc6a52042aaa6f1a47efe4fec9fe90f0e
