### ISSUE TITLE
Dedicated Log-In Page

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2413]
Is there a logistical reason there's no dedicated log-in page? Often, the pop-over log-in screen is twitchy on my tablet, an issue I've found to be non-problematic on other sites by accessing their log-in page proper. Lately, it's been even more of an issue, the pop-over page freezing on log-in attempt, giving me scroll control to the under layer then crashing my browser.

(It is crashing Chrome, Puffin, and Puffin Free. It was not crashing any of them yesterday. But even if it wasn't crashing them, an actual page that could be visited to log in, if so desired, could be nice.)
##

**Comment by Alys** [comment]
I would really like this. A dedicated login page with minimal JavaScript could be a useful workaround for the Safari bug where the "play" button doesn't always work, and it's likely to be more accessible. It would also allow password managers to work (I believe some don't at the moment).

It wouldn't have to replace the existing front page. It could just be a new, relatively plain page that we can direct users to when necessary (or have a small message on the normal login form that directs them to it if they're having problems).

@lemoness @AnitaYCheng What do you think?

**Comment by lemoness** [comment]
I'd be amenable to this!

**Comment by AnitaYCheng** [comment]
Sounds good to me!

**Comment by lemoness** [comment]
It will actually be useful to have a variety of registration pages, too, as
we go on - for example, one registration page for when you are clicking on
a link that invited you to a guild, etc.

**Comment by librarianmage** [comment]
@Alys Is this still planned?

**Comment by Alys** [comment]
@MathWhiz  I'd still really like to see this happen for the reasons listed above. It might also help with https://github.com/HabitRPG/habitrpg/issues/5428 if we don't fix that first.

**Comment by librarianmage** [comment]
@Alys I can try doing this!

**Comment by Alys** [comment]
@MathWhiz Great! Thank you!!

**Comment by librarianmage** [comment]
@Alys @lemoness would this replace the dialog box? How should users get to it?

**Comment by Alys** [comment]
It wouldn't replace the dialog box - the current method of logging in should remain as it is. Instead, you can create a new page https://habitica.com/static/login with a non-popup form in the page. For the basics of creating a new static page, have a look at how https://habitica.com/static/clear-browser-data is done.

**Comment by librarianmage** [comment]
@Alys how do I change the password for a user from the database (I forgot my password)

**Comment by Alys** [comment]
You could probably set up something to receive the email, but it's likely to be easier to use mongo, and even if you're not very familiar with mongo yet, this will be a good exercise. :)

Create a new user account with the password that you want to use. Export its data and look in the "auth" object (example below). Copy the values of "auth.local.hashed_password" and "auth.local.salt" to the old account. You'll then be able to log in to it with that password.

```
    "auth": {
        "local": {
            "email": "thing@thing.net",
            "hashed_password": "23198732985987ee7d89e10cb7a62a2849321777",
            "salt": "9887972b73",
            "username": "Bob",
            "lowerCaseUsername": "bob"
        },
        "timestamps": {
            "created": "2013-01-10T06:34:12.804Z",
            "loggedin": "2016-04-26T17:08:56.224Z"
        }
    },
```

**Comment by Alys** [comment]
Note that by "export its data" I mean use a mongo command to dump the user document. The in-game Data > Export feature won't show you the authentication information.

**Comment by lemoness** [comment]
We've made many changes to the website, and this should have been addressed. I'm closing this ticket, but if you feel that it should be reopened for any reason, please feel free to leave a comment!
