### ISSUE TITLE
PayPal Purchase Gems Info States it Removes Ads

### ISSUE THREAD

**Issue by KnittyGritty** [HabitRPG/habitica#2416]
Hi there,

I've just joined on the 13th, and paid the donation via paypal, however, there's still advertising coming up, and no gems arrived either...what went wrong there?

Thanks for looking into this...

**Comment by lefnire** [comment]
what's your UUID? Sorry for the issues, paypal IPN is quite finicky. We're looking into it, and recommending the credit-card payment (which uses Stripe) in the mean-time

**Comment by KnittyGritty** [comment]
...well, you got me there...where would I find my UUID?
 

Gesendet: Donnerstag, 16. Januar 2014 um 02:35 UhrVon: "Tyler Renelle" notifications@github.comAn: HabitRPG/habitrpg habitrpg@noreply.github.comCc: KnittyGritty e.boernard@web.deBetreff: Re: [habitrpg] "Donation" not registering... (#2416)

what's your UUID? Sorry for the issues, paypal IPN is quite finicky. We're looking into it, and recommending the credit-card payment (which uses Stripe) in the mean-time

**Comment by lefnire** [comment]
String of characters under `User Id` at https://habitrpg.com/#/options/settings/api

**Comment by KnittyGritty** [comment]
oh, thanks, found it...

 

here we go: 

 

9abb0c9f-1eaa-4cec-84c1-5676c6d7f97b

Gesendet: Samstag, 18. Januar 2014 um 06:58 UhrVon: "Tyler Renelle" notifications@github.comAn: HabitRPG/habitrpg habitrpg@noreply.github.comCc: KnittyGritty e.boernard@web.deBetreff: Re: [habitrpg] "Donation" not registering... (#2416)

String of characters under User Id at https://habitrpg.com/#/options/settings/api

**Comment by deilann** [comment]
@lefnire Did you get this one?

**Comment by laurentiu69** [comment]
ID: 819013f6-3bc0-4cbe-8127-6c23a2416041
I also make a donation, gems are in but ads are still there.

**Comment by deilann** [comment]
@laurghita Ads are now disabled through subscription, not through gems.

**Comment by laurentiu69** [comment]
Then must comunicate to OCDevel to change the text description:

Description                                                                  Unit price     Qty Amount
20 Gems, Disable Ads, Donation to the Developers    $5.00 USD   1   $5.00 USD
Charge will appear on your credit card statement as "PAYPAL *OCDEVEL"

**Comment by deilann** [comment]
Ohhhh yeah, that needs to definitely change. @lefnire I'm gonna tag this
one as well & disable laurghita's ads.

**Comment by deilann** [comment]
@laurghita Okay, your ads should be disabled now. Just let me know if they're not. Sorry about the improper description.

**Comment by laurentiu69** [comment]
Yes they are disabled now, but if it was not supposed to be disabled after donation then I dont mind to have them back (the ads). I just rise this because I was thinking is a bug or something.

**Comment by deilann** [comment]
It told you that your ads were going to be disabled, so I feel it's only
right you get what was advertised.

**Comment by laurentiu69** [comment]
Ok they are disabled, thank you.

**Comment by deilann** [comment]
Edited title to deal with @laurghita 's problem.
