### ISSUE TITLE
suggestion: put the charactor values buttons back!

### ISSUE THREAD

**Issue by wes1** [HabitRPG/habitica#2421]
yesterday my account had a large glich and deleted all my MPs, GPs, and experience. So I think it would be helpfull to put the buttons back. Thanks!

**Comment by deilann** [comment]
Go to settings. You'll see the "Fix Character Values" button. The only one that's not active at this moment is the gold, as the Winter Wonderland equipment is gold-purchaseable.

**Comment by wes1** [comment]
sorry didnt understand that :-)

**Comment by colegleason** [comment]
@wes1 Please look at this [Wiki page](http://habitrpg.wikia.com/wiki/Settings). You want 'Fix Character Values'.

**Comment by wes1** [comment]
ok ok ok so many people are pulling me out on this issue
