### ISSUE TITLE
error 401 when pressing Fetch Recent Messages button

### ISSUE THREAD

**Issue by Thyra-Sinisalo** [HabitRPG/habitica#2426]
Hi :)
I keep getting the error message 401: you don't have access to this group when I hit the Fetch Recent Messages button in my Party. I does not prevent me from posting there or accepting challenges, only the button seems to have a problem. I get the new messages when I refresh the website.
I have found this ticket on the issue that was closed and said it was fixed 3 months ago:
https://github.com/HabitRPG/habitrpg/issues/1627?source=cc

My ID: ef07dbbb-82f4-4eb6-873c-53bc421a53e7
Browser: Chrome
![image](https://f.cloud.github.com/assets/6417989/1928990/21973cfe-7e8f-11e3-93b3-cefabea0f450.png)

**Comment by deilann** [comment]
Are you still having this problem?

**Comment by deilann** [comment]
(If so, please reopen this ticket.)
