### ISSUE TITLE
Position on base wolf mount is not what it supposed to be

### ISSUE THREAD

**Issue by Akiaya** [HabitRPG/habitica#2428]
I recently gained a Bear mount from Trapper Santa quest and then i fed and turned my base wolf into a mount. But while my character is positioned correctly on bear mount, its a little bit off on wolf mount. Ill be showing below:
Bear: ![mount bear](https://f.cloud.github.com/assets/6347702/1930300/fb55d46e-7ea8-11e3-9a86-b7b5fa0487bd.png)
Wolf: ![mount wolf](https://f.cloud.github.com/assets/6347702/1930302/02940584-7ea9-11e3-9cff-8d412b8f7eb2.png)

I dont think it is supposed to be shown like this since my teammate, who has a base tiger mount seems to be riding it normally:
![mount tiger](https://f.cloud.github.com/assets/6347702/1930299/f86e2b84-7ea8-11e3-875c-d8654e832564.png)

I couldnt try on any other mounts since i dont still have any, but when i have, ill try to update this asap.

**Comment by lefnire** [comment]
Don't have the ticket handy, but mount-positioning is a known issue (some mounts, not all). Due to limitation in bounding box dimensions of avatar sprites, we're going to revisit after a sprite dimensions decision (could be some time)

**Comment by ghost** [comment]
Comparing my Gold Tiger and White Wolf, it seems like all wolves have this issue.

**Comment by SabreCat** [comment]
I'm actually working on this. If we can expand the size of the _mount_ sprite canvas, we might be able to accomplish some repositioning without major overhaul.

**Comment by lefnire** [comment]
In the mean time, since wolf is the only one with real issues (the others could use tweaks, but wolf is the really bad one) - we could just a have a `[class*=Mount-Wolf]` (or whatever it is) special case to add margin just for wolves

**Comment by Alys** [comment]
This has been fixed.
