### ISSUE TITLE
Dissapearing Ski- sassin Pole

### ISSUE THREAD

**Issue by Heyocto** [HabitRPG/habitica#2429]
I died a day or two ago and now every time a new day comes I have to re-buy the Ski- sassin Pole.

**Comment by colegleason** [comment]
@Heyocto can you do me a favor and refresh the page to see if the pole is still in your inventory? I wonder if the page only shows the pole in your equipment but the server doesn't recognize that you purchased it.

**Comment by deilann** [comment]
@Heyocto Please reopen this when you have more info for us!
