### ISSUE TITLE
HabitRPG not showing my party?

### ISSUE THREAD

**Issue by Tina-Lou** [HabitRPG/habitica#2430]
I'm fairly new to the game, so I apologize if this is known, or there's an easy workaround that I haven't figured out yet.  I'm playing as Tina Lou , I'm level 3, and just joined a party  (The Determined Ones.)   I posted in the chat there, and can still see challenges from them in my challenge tab. 

However, when I click my 'party' tab, it's telling me that I'm not in a party, but that I can create an empty one to do quests. 

Anyway I can fix/work around this? 

Thanks!

**Comment by lefnire** [comment]
Does a refresh help you? If not, can you post your UUID here?

**Comment by Tina-Lou** [comment]
I logged out and logged back in, seemed to fix it

Sent from Yahoo Mail on Android
