### ISSUE TITLE
Stealth preventing very little damage at very high perception

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2432]
I used Stealth with 12 dailies uncompleted, which (at my standard of 2.4 damage per undone daily) should have done about 29 damage to me. After using Stealth at 153 Perception, the next morning I took... 19 damage. As spending 45 mana at level 63 for the prevention of 10 damage hardly seems worthwhile, I have to assume something's not right.

**Comment by lorian** [comment]
Nevermind, I found the relevant code, and it appears that is working as intended:
user.stats.buffs.stealth += Math.ceil(user._statsComputed.per \* .03)
So at my level of perception, 45 mana allows me to dodge a random 5 dailies, which is about the 10 hp I saved. I wish I had known that before I cast the spell; 4 casts of pickpocket would have gotten me way more than one health potion!

**Comment by lefnire** [comment]
@lorian I have a To-Do to up the stealth buff based on %dailies-owned, and increase the number besides (given the MP cost). As I mentioned, I won't have time to dive into this for another couple months - but if you can suggest the math (or better, modify / run some simulations / PR) we'll get those in and boost your contrib lvl

**Comment by lorian** [comment]
I'll give it a try! I do so love math and simulations.

**Comment by lefnire** [comment]
Discussion [here](https://github.com/HabitRPG/habitrpg/issues/2408#issuecomment-32396208) for reference, let me know if you need help getting those up-n-running

**Comment by lorian** [comment]
The simulation passive_active_attrs.coffee has some issues with stealth; first, it gives a TypeError, "Cannot read property 'automaticAllocation' of undefined". When I commented out the offending call to user.ops.score, it ran, but it gives clearly wrong results for stealth: it shows the number of stealthed dailies being dependent on task value. I can't find anywhere in content.coffee where the stealth buff would be using task.value, and in fact, it's not even being passed to the stealth function. It's specific to stealth, as well; all of the other spells that should be constant (with respect to task.value) are, in fact, constant.

I'm afraid my limited javascript knowledge has failed me past this point.

**Comment by lefnire** [comment]
@lorian I recently fixed up passive_active_attrs script, can you give it another shot?

**Comment by lorian** [comment]
See pull request: https://github.com/HabitRPG/habitrpg-shared/pull/130

I balanced around 100 Per = 100%, but feel free to modify that as needed. My justification is that 100 Per is either a level 50 after a perfect day, with max points in Per, or a level 100 after an imperfect day, with half their stat points in Per, both of which feel like they "deserve" to stealth all dailies, but that's weak justification at best.

**Comment by lefnire** [comment]
:+1: thought it was, thanks @lorian! you're turning out to be the algos person! A much needed role.
