### ISSUE TITLE
BUG! only shows mounts head!

### ISSUE THREAD

**Issue by wes1** [HabitRPG/habitica#2436]
I don't know if anybody has this happening to them but when I go to the mounts page it only shows my mounts head!
![screen shot 2014-01-17 at 8 24 27 am](https://f.cloud.github.com/assets/6416566/1936178/3eef70de-7f05-11e3-9109-e8e65d1f0457.png)

**Comment by wes1** [comment]
if hs is just normal just close the issue! :-)

**Comment by lefnire** [comment]
this is normal behavior...
