### ISSUE TITLE
Vanishing / Missing gold

### ISSUE THREAD

**Issue by Novakza** [HabitRPG/habitica#2437]
It's possible that I had misclicked a reward (perhaps a backlog of purchases to catch mistakes like that would be useful), but I just had something in the region of 30 gold disappear shortly after completing an item on my to-do list. I wasn't keeping a close track, but I had roughly 55 before, then completed it, then took my attention elsewhere, and then found I had dropped to 29ish. Likely not an actual bug, more human error, but I figured I would submit it anyway just in case.

**Comment by deilann** [comment]
Let us know if you keep having this problem.
