### ISSUE TITLE
Top bar not loading

### ISSUE THREAD

**Issue by katerberg** [HabitRPG/habitica#2440]
When I log into HabitRPG, the top bar is just not there. I cannot see anything above the tags section as seen here:
![screenshot - 01162014 - 09 05 51 pm](https://f.cloud.github.com/assets/479643/1937438/4b7a62d6-7f24-11e3-8761-434085858a1b.png)

I'm using Firefox on Debian but have replicated this problem on Firefox on MacOS and in Chrome on Windows. I had another user log into their account on my computer and they did not see the issue and I was able to replicate the issue for me on their computer.

My userID is b38cb051-4eb8-4ba7-aef1-c37728debd7f

The only warnings are in widgets.js:
Unexpected value xMidYmid meet parsing preserveAspectRatio attribute.

**Comment by lefnire** [comment]
Sure you didn't [disable header](https://habitrpg.com/#/options/settings/settings)? [screenshot](https://www.evernote.com/shard/s17/sh/fc0aecd7-ce28-4817-a9f9-2e20282f6b29/f809d70887d33b3d17492b85590aaf2d)

**Comment by katerberg** [comment]
That was definitely the issue. Sorry for the confusion. I looked in the settings as well but was looking for top bar as that's what it's referred to on the wiki. Thanks!
