### ISSUE TITLE
checked in inn but still died after going away for a few days

### ISSUE THREAD

**Issue by sabrinastarfire** [HabitRPG/habitica#2444]
i checked in inn but still died after going away for a few days.

**Comment by colegleason** [comment]
Were you on the Trapper Santa Quest?

On Thu, Jan 16, 2014 at 11:12 PM, sabrinastarfire
notifications@github.comwrote:

> i checked in inn but still died after going away for a few days.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2444
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by deilann** [comment]
@sabrinastarfire Please reopen this if you have more info.

If you were in a quest, please remember that you still get damaged for your party members' missed dailies.

It's also possible that a 503 tripped you up, and you were never in the inn.
