### ISSUE TITLE
Donation issue

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2445]
Hi,

3 days ago I made a donation through PayPal but I didn't received any gem yet.
My User ID is: de9c8079-aa01-441f-9fce-8d7305b9dc80.

Thanks for support.

**Comment by wc8** [comment]
Hi, sorry for your troubles. Thanks for letting us know. 

Attn: @lefnire

**Comment by lefnire** [comment]
@JeanMichMuch ran a script for you, give that a shot

**Comment by ghost** [comment]
Thanks @lefnire, you fixed it.
Have a nice day.
