### ISSUE TITLE
Perfect day achievement : not awarded if you have grey dailies uncomplete

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#2446]
Hi there,

I removed a daily yesterday (without checking it before), and had my whole list completed at the end of the day. I didn't received any achievement for this "perfect day".

Is this intended ? (it would make sense, in a way)

If so, would checking the daily before removing it prevent this behaviour ?

Or maybe it's not related at all, and linked to something else ?

Regards

Aiseant

**Comment by lemoness** [comment]
Also didn't get my perfect day when I checked my last daily, but maybe it's calculated on cron. That would be my instinct, anyway.

**Comment by Aiseant** [comment]
Yes, I was my first thought. I waited my cron before posting this issue, it wasn't the problem.

**Comment by wc8** [comment]
Were any of your grey dailies unchecked? It believe it's a known issue that Perfect Day’s not yet accounting for not-due dailies.

**Comment by Aiseant** [comment]
Hooo, it must be that, I often have grey dailies. Thanks @wc8.

**Comment by lemoness** [comment]
Yikes, same thing happened to me! Must be my grey Dailies. Darn, I was so excited! Oh well, I'm sure it will be fixed soon.

**Comment by lefnire** [comment]
pushing @colegleason's fix, thanks cole!

**Comment by lemoness** [comment]
Thanks Cole!!
