### ISSUE TITLE
Lost most of day's checked items?

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2448]
Checked off a bunch of items, including all my dailies. Then, when I came back to HabitRPG to check the tavern quickly before bed, it announced a loss of MP and gold, and I saw that all of my tasks for the day except for those I checked first thing in the morning had reappeared/unchecked.

I rechecked them all. Will keep you posted, I guess.

**Comment by deilann** [comment]
I think this is another version of https://github.com/HabitRPG/habitrpg/issues/2554, Lemoness.

**Comment by lemoness** [comment]
It definitely was.
