### ISSUE TITLE
Reward based group quests

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#245]
The idea is for a group of people to invest gold into a pot, to be paid out to teh succesful completers. This is most likely to be based on habits or dailies, with a fixed run time and an accomplishment goal (avg habit increments per day, or top 3 daily completers).

This could be done via the group feature, or perhaps through NPCs. There could by NPCs for common global categories such as work, fitness, diet, live style. And similar to Lift you could join a quest and compete against other heroes. Prehaps yo ucan win gold or badges or hall of fame slots...

**Comment by horusofoz** [comment]
Migrated to [Trello Card 146](https://trello.com/c/A4NZOl7R).
