### ISSUE TITLE
Reset to lvl 5 with 30 EXP everyday

### ISSUE THREAD

**Issue by Yaneela** [HabitRPG/habitica#2452]
Hello there,

I've been experiencing a problem for about 3 days now where it sets me back to lvl 5 with about 30 EXP everyday. It seems to happen completly random all throughout the day.
My character seems to be stuck on this weeks tuesday too, the dailies haven't reset since then, and my To-Do-List keeps going back to what I had on tuesday (already checked things reappearing, new things dissappearing).
Additionally every day after the daily reset I am checked into the tavern, my pet gets unequipped randomly all the time, and I haven't had any drops these last few days.

Also on tuesday night, right before this started happening the site broke down completly for me. It just showed a long list of all the text fields for any possible event one after another with a bit of coding in between. 

Sorry if anything isn't understandable, English isn't my first language.

**Comment by colegleason** [comment]
Wow, this sounds like the most extreme cron-related bug I've heard of. Can
we get your UUID, please?

On Fri, Jan 17, 2014 at 7:29 AM, Yaneela notifications@github.com wrote:

> Hello there,
> 
> I've been experiencing a problem for about 3 days now where it sets me
> back to lvl 5 with about 30 EXP everyday. It seems to happen completly
> random all throughout the day.
> My character seems to be stuck on this weeks tuesday too, the dailies
> haven't reset since then, and my To-Do-List keeps going back to what I had
> on tuesday (already checked things reappearing, new things dissappearing).
> Additionally every day after the daily reset I am checked into the tavern,
> my pet gets unequipped randomly all the time, and I haven't had any drops
> these last few days.
> 
> Also on tuesday night, right before this started happening the site broke
> down completly for me. It just showed a long list of all the text fields
> for any possible event one after another with a bit of coding in between.
> 
> Sorry if anything isn't understandable, English isn't my first language.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2452
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by Yaneela** [comment]
I'd love to send you my UID right away but the earlier mentioned bug of just showing me bits of coding and pictures occured again so I can't look it up right now :/
I've been trying to load up a screenshot of it but GitHub won't let me (or else I'm to stupid)

I could upload it to my tumblr or deviantart though, if you think that'd help ...

**Comment by colegleason** [comment]
That would help a lot, just so we can see what is going on. Do you, by chance, have _a lot_ of to-dos?

**Comment by Yaneela** [comment]
Last time I checked I had something about 6 To-Dos

The Upload problem was apparently my browsers fault so here you go:
It goes on like that for a while longer ...

![habitrpg bug](https://f.cloud.github.com/assets/6429627/1942885/a352d084-7fa0-11e3-9a17-3cb7bf966627.png)

**Comment by colegleason** [comment]
Oh, I've seen this before! I think it means there is an error in the Jade
template.

If you are using Chrome, could you please right click on that page and
click "Inspect Element", then go to the tab called "Console" and copy and
paster any errors here for us?

On Fri, Jan 17, 2014 at 11:56 AM, Yaneela notifications@github.com wrote:

> Last time I checked I had something about 6 To-Dos
> 
> The Upload problem was apparently my browsers fault so here you go:
> It goes on like that for a while longer ...
> 
> [image: habitrpg bug]https://f.cloud.github.com/assets/6429627/1942885/a352d084-7fa0-11e3-9a17-3cb7bf966627.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2452#issuecomment-32629056
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by Yaneela** [comment]
I'm actually using firefox, there it says:
19:24:03.299 [object Exception] app-f70c919f.js:5

**Comment by colegleason** [comment]
I don't know firefox all that well. Is there any more info there (like an
arrow you can click?)

On Fri, Jan 17, 2014 at 12:38 PM, Yaneela notifications@github.com wrote:

> I'm actually using firefox, there it says:
> 19:24:03.299 [object Exception] app-f70c919f.js:5
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2452#issuecomment-32633154
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by Yaneela** [comment]
I can click on it and it sends me to this really long code line, should I copy it?

**Comment by colegleason** [comment]
If you could, please just paste it here: http://pastebin.com/ and copy the
link here.

On Fri, Jan 17, 2014 at 12:50 PM, Yaneela notifications@github.com wrote:

> I can click on it and it sends me to this really long code line, should I
> copy it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2452#issuecomment-32635300
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by Yaneela** [comment]
So I tried copying it, but apparently firefox doesn't want that (_sigh_ this is so exhausting, I don't know a thing about codes and the likes Q__Q) but I found this somewhere in the console:

Filename:  https://habitrpg.com/app-f70c919f.js
Message:  Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED)[nsIDOMStorage.setItem]
Name:  NS_ERROR_FILE_CORRUPTED
Result:  2152857611

I don't know if that helps at all but I really don't understand any of the interfaces it shows me so I can't really do more :/

**Comment by colegleason** [comment]
Hmm, this appears to be an issue with Firefox's localStorage. It seems it
has been corrupted somehow.

On Fri, Jan 17, 2014 at 1:03 PM, Yaneela notifications@github.com wrote:

> So I tried copying it, but apparently firefox doesn't want that (_sigh_this is so exhausting, I don't know a thing about codes and the likes Q__Q)
> but I found this somewhere in the console:
> 
> Filename: https://habitrpg.com/app-f70c919f.js
> Message: Component returned failure code: 0x8052000b
> (NS_ERROR_FILE_CORRUPTED)[nsIDOMStorage.setItem]
> Name: NS_ERROR_FILE_CORRUPTED
> Result: 2152857611
> 
> I don't know if that helps at all but I really don't understand any of the
> interfaces it shows me so I can't really do more :/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2452#issuecomment-32636478
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by Yaneela** [comment]
So I've deleted all cookies and the display bug seems to be gone for now, here's my User ID (finally):
04c8d6fb-d9a1-4888-9f91-30c1b91dbf49

**Comment by Alys** [comment]
@Yaneela I'm assuming this problem is no longer occurring, however if I'm wrong, please comment here and we'll reopen this!
