### ISSUE TITLE
Party Spells not working - Healer

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#2453]
I have been trying desperately to heal my party, but am getting a 500 error on each. The error text: "Error 500: request entity too large (see Chrome console for more details)."

**Comment by colegleason** [comment]
Oh dear. Just to help debug: how big is your party?

On Fri, Jan 17, 2014 at 7:35 AM, Eiron Page notifications@github.comwrote:

> I have been trying desperately to heal my party, but am getting a 500
> error on each. The error text: "Error 500: request entity too large (see
> Chrome console for more details)."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2453
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by eiron** [comment]
We are seven or eight. We are, however, likely to be cutting down a couple
members. Things do get unstable above six, as promised.

**Comment by lefnire** [comment]
This should be fixed as of https://github.com/HabitRPG/habitrpg/commit/e0646bb98d44b6874b5259107c9be5fa34c58933
