### ISSUE TITLE
Donated, gems not showing up

### ISSUE THREAD

**Issue by stupadbear** [HabitRPG/habitica#2454]
## Fixed

I've noticed that other people are having the same issue, so even if it's not been long since i wanted to just poke my head in and let you know.

I donated (Because you're amazing!), got a receipt and all but gems haven't shown up.

My ID is 4521379a-69cf-4d3b-aade-c073d32bd065 

My nickname is Stupidbear
##

**Comment by lefnire** [comment]
yeah, paypal IPN is slow and finicky (I added a note to the checkout screen to use card if available, which uses stripe - a much preferred vendor). I'm still looking into this, in the meantime i  ran the script for you - give that a whirl

**Comment by stupadbear** [comment]
Thank you very much! :)

**Comment by Eipois** [comment]
## Fixed

Hi! I have the same problem, 12.1. I donated 5 dollars, but nothing happened. At least on habitRPG, but other things look OK - I have confirmation email and so. 

User ID: 139b9647-c05a-41a3-bc80-4124d7555ec0
nick: Eipois
Paypal Transaction ID: 1BY73719XA059531B

Thanks a lot for help, I want to buy winter collection o:-) :)))

**Comment by lefnire** [comment]
@Eipois √

**Comment by ghost** [comment]
## Fixed

Same problem as above, donated nearly a day ago wia paypal, no gems appeared yet. I'm hoping to change my class soon-ish!

User ID: 2daca1ec-91e2-4066-b411-9b15ca498bea

**Comment by treskift** [comment]
## Fixed

I have the same problem, donated yesterday and got a receipt, but nothing has appeared yet.
Thank you lots if you can help! :)

User ID: f3f923a4-bdd8-46c3-a950-b93f8104b255
Paypal Transaction ID: 3E6988100M134872Y

**Comment by lefnire** [comment]
@Mureenahko @treskift √

**Comment by princeofbadassery** [comment]
## Fixed

Hello same problem here!
my User ID is bb3c8bfb-88fe-4f8a-8755-81cf343af91c
thanks a lot!

**Comment by stupadbear** [comment]
##Fixed

Hey! I donated again (Because you're awesome) and it was like four days ago. Used paypal because my wallet was too far away and I'm lazy (Maybe something for habits?). Could you run the script for me? Next time I'll just use a card, no problem :)

**Comment by ghost** [comment]
## Fixed

Same problem here. Donated via PayPal January 19. My user ID is db9321f2-8ca0-4a34-a204-5d96ee267ee7 
![paypal](https://f.cloud.github.com/assets/6595203/2087453/2ee33bbe-8e6c-11e3-9021-d15f4a1c197f.PNG)

**Comment by stupadbear** [comment]
## Fixed

I donated again and it's been about five days or so (estimated). 
Mind running the script again? ^^

My ID is 4521379a-69cf-4d3b-aade-c073d32bd065
My nickname is Stupidbear

**Comment by mr-flibble** [comment]
## Fixed

Same problem here, donated via PayPal  25 January 
ID: 87d5264f-6f0c-4318-acfb-67e856fb5292
PayPal Transaction ID: 3JR10591WV1276006

Thanks

**Comment by colegleason** [comment]
@lefnire, what's up with Paypal IPN? Do we just have something set up odd?

On Thu, Feb 6, 2014 at 3:07 PM, mr-flibble notifications@github.com wrote:

> Same problem here, donated via PayPal 25 January
> ID: 87d5264f-6f0c-4318-acfb-67e856fb5292
> PayPal Transaction ID: 3JR10591WV1276006
> 
> Thanks
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2454#issuecomment-34370787
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by lefnire** [comment]
My guess is it's hitting the same issues as the application errors people are experiencing. IPN sends a request to our server, responses with 200, locks up, nothing :( This 503 stuff is wreaking absolute wreckage upon habit

**Comment by lefnire** [comment]
@princeofbadassery @stupadbear can you list your paypal txn ids?

@Miisa @mr-flibble √

**Comment by stupadbear** [comment]
Transaction ID? 0WA37682RH150104A

**Comment by lefnire** [comment]
@stupadbear √ (sorry for the wait)

**Comment by princeofbadassery** [comment]
Transaction ID is 4SF731108M2659401

**Comment by lefnire** [comment]
@princeofbadassery √

**Comment by Winnihund** [comment]
## Fixed

also donated 5 dollar :( 12.02.2014
Transaction ID is 9LL20837H8537770H i think

habit id: af8c0d13-010c-4e89-8f1a-a747c28a34fb

**Comment by lefnire** [comment]
@Winnihund √

**Comment by melzipan** [comment]
Same issue just now :/

trans ID: 0TK18019AK5677108
habit ID: ff56048c-7b8b-484f-abe5-28798eb4e153

Thanks for your help

**Comment by deilann** [comment]
We haven't had this issue in a while... I just wanted to make sure that you
bought gems, melzipan, not subscribed. If you subscribed, you will have to
purchase your gems with gold.

**Comment by melzipan** [comment]
I'd bought gems, for sure! (I'd subscribed about two months ago however...)

**Comment by deilann** [comment]
Just wanted to make sure. :) I'll credit you in two shakes of a lamb's tail.

**Comment by deilann** [comment]
Alright, refresh, should be all good!

**Comment by melzipan** [comment]
Holy-- that was a fast reply! Thanks :dancer:

**Comment by deilann** [comment]
No problem. :) There's a reason I'm the magical glitter ninja lord.

**Comment by melzipan** [comment]
Hahaha no kidding, thanks again!

**Comment by thespaceferret** [comment]
Not sure if I should do this as a new issue, but I donated via credit card and it went through but the gems didn't show up (and then I tried two more times, so now I've donated $15 total, which is fine, but I'd like the gems). There was an error that flashed by too quickly for me to catch all of, but it said something about an error and Chrome. I have logged out and back in and it didn't help.

Userid is 56fe75d0-57a3-4d0e-a1ad-ff13b3919dac

**Comment by deilann** [comment]
Can you email admin@habitrpg.com? You may need to provide more sensitive
information, so it can be taken care of faster privately.

**Comment by lefnire** [comment]
@paglias the recent  code with emails broke something I'm getting a lot of
emails from people, I'm AFK right now you around to revert?

**Comment by lefnire** [comment]
This one is insanely critical. People are getting double-charged and not getting their purchases. I've pushed the likeliest revert, so we should be good - but mentioning just in case if anyone can think of any other recent code they've pushed that may be relevant

**Comment by deilann** [comment]
Please email admin@habitrpg.com about this, along with your transaction ID
number.

**Comment by deilann** [comment]
Please email admin@habitrpg.com about it. They'll need your transaction ID
as well.

**Comment by lemoness** [comment]
The site admin is very busy, so it may take several days to get a response,
but rest assured we will handle it as soon as we can! Sorry about the
hassle.

**Comment by paglias** [comment]
This should be fixed
