### ISSUE TITLE
Suddenly died, Rollover didn't happen, weirdness everywhere.

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2455]
I just died this morning, and I had completed all my dailies, and wasn't on the boss quest (I'm on the cub quest). Last night I had 26 hp (and 947 gold ; ;), and this morning I was told that I died.

All of my dailies still have streaks, and in fact the newest daily that I made yesterday is cloned: there are 4 copies of it, all with streaks (although one has one more streak than it should). How the HECK did I die (and how do I get my 947 gold back)?

Oh shit, I only just realized that most of my dailies aren't refreshed! The top 3 are, but the rest are all greyed out (although they all still have streaks). I have absolutely no idea what is going on, except I'm pretty sure it wasn't my fault. Worth noting: my habits are still the color they were last night, even though the single-click-a-day ones should have gone back to yellow.

Aaaaaand also a bunch of my to-dos are duplicated. HELP. I don't know how to fix this.

(For future reference, some of my streaks were also messed up -- but not all of them. Of the ones that were, many got reset to 4, for some reason.)

**Comment by wc8** [comment]
Hi, sorry, cleaning up the clones is something I suspect we'll need @lefnire to tackle.
He'll probably need your User ID.

**Comment by lorian** [comment]
User ID: 142e1f47-6fae-4927-a5c2-3ea8a42b71d1
Any idea what happened? It's like my account is currently stuck halfway between three copies of yesterday and today.

I have managed to clean up the clones; I kept hitting delete and reloading the page, and eventually they went away. Hopefully that's the last of it!

**Comment by lorian** [comment]
FYI, it sounds like my issue is some mishmash of issues  #2458 (unreset dailies) and #2456 (duplicated entries) . I'm now completely terrified of logging out.

**Comment by mariemariem** [comment]
hey, exactly this happened to me over night. i levelled up a few hours before midnight. over night my pixel guy suddenly died (I had full health points and in no way my unfinished dailies could have taken all 50 HP), one recently added task was duplicated and my dailies won't refresh (they appear grey and checked off the same as the day before).

any news, lorian?

my user ID: eef887b6-351c-4eeb-ad79-607102499226

**Comment by lorian** [comment]
My only "news" is that the dailies-not-all-refreshing party happened once again, but thankfully not the dying part! Useful tip for recovering: if you have a copy of the habit page open from the previous night (that you haven't refreshed), you can go into that page's "fix values" and it will have filled in your previous gold/hp/xp total; that's the only easy way to get your gold back. 

Otherwise, I recommend noting what your xp/gold values were the previous day (if you recall), and then unchecking all your dailies and fixing their streaks (their streaks will, at a minimum, be two lower than they should; I had a bunch of streaks that were wrong even beyond that, though). Then just make several "hard" habits, and start clicking the + until your gold is back to where it should be. If your xp isn't right after that, go into "fix values" and change it. And then cross your fingers!

It is a super annoying bug, and I wish someone would say they have an idea where it's coming from :/

**Comment by mariemariem** [comment]
thank you, those are some really helpful ideas!

**Comment by deilann** [comment]
Yeah, let's follow this at: https://github.com/HabitRPG/habitrpg/issues/2601
