### ISSUE TITLE
duplicating 'to do' and 'daily' tasks

### ISSUE THREAD

**Issue by snagerdra** [HabitRPG/habitica#2456]
having to delete duplicating items. some of them have duplicated themselves like 4 times. I just got this account yesterday so i wasn't sure if that was supposed to happen? doesn't make sense for it to.

then, when i completed a 'to do' item, sometimes it gave me gold and ex but stayed put and stayed yellow and other times it gave me damage. i tried to click items off my to do list several times so now my gold's all jacked up. :/

'habits' were also duplicating some yesterday, but that's stopped i think.

**Comment by wc8** [comment]
@lefnire this sounds to me like a corrupted item. 
Seems like we had a bug like this ages ago and defeated it. Now we're getting multiple reports here and on tavern about it.

**Comment by snagerdra** [comment]
I should say that by 'item' i mean the words you type in that are your tasks. I am so new, maybe there are actual items in this game thing.

**Comment by octern** [comment]
I've gotten repeat to-dos from time to time as well. Only doubles though, never quadruples. I didn't post about it because I could never replicate it or figure out exactly what was going on, but it's definitely not a thing of the past. I've also only observed this on to-dos, though that may be because I add to-dos much more frequently than other categories.

**Comment by lorian** [comment]
I got a large batch of triples and quadruples of all my recently-added dailies and to-dos this morning (along with other, more pressing problems). Never had it happen before.

**Comment by snagerdra** [comment]
it happened again this morning, but only for to-dos, rewards, habits and dailies that i added, yesterday. i'm also now getting that thing where the dailies you clicked off yesterday are staying greyed out. might have happened because I messed around with the weird 'this many hours a day' setting, not understanding what it was. I guess it lets you pretend you live on mars.

**Comment by colegleason** [comment]
Perhaps we should enforce unique task _ids per user. I imagine there is some case where it gets added twice somehow.

**Comment by octern** [comment]
Here's an interesting clue: 
![image](https://f.cloud.github.com/assets/1575692/1998396/bccb3f82-8532-11e3-8073-18319bd86100.png)

The duplicate to-dos are two different colors, indicating that they must have been added at substantially different times. I believe I typed this one in while I didn't have an internet connection, so maybe one copy reflects the time I added it and the other reflects the time it synched? 

... except that one of the copies is orange, whereas tasks that I added many hours prior to this one (and while I was on the internet) are still yellow. So it's not just that one copy of the task is older than the other, but one of them appears prematurely aged.

**Comment by lorian** [comment]
If the duplication happened on a different day than the creation, then that would explain why the original was older, and the copy was younger. Which at least points to them not being true clones.

**Comment by Earthstar** [comment]
Curious and curiouser ... When I delete a duplicate entry, the results aren't predictable. When I deleted one duplicate in my todo list, both entries disappeared. When I delete another duplicate, the bottom duplicate disappeared.
![habitrpg_duplicate_entries_bug](https://f.cloud.github.com/assets/2675982/2002713/c28bda58-8609-11e3-923a-4c7b90f5144d.png)
![habitrpg_duplicate_entries_bug_2](https://f.cloud.github.com/assets/2675982/2002714/c7753d84-8609-11e3-9c1a-de7d3a02be70.png)

**Comment by lorian** [comment]
Yeah, I had the worst time deleting dupes. Sometimes deleting one would delete both, sometimes it would delete the other, and sometimes it wouldn't delete anything. I had slightly better luck if I kept reloading the page after every attempted delete, but it's clear these aren't normal tasks.

**Comment by tiffogirl97** [comment]
hi, i have the same problem too. i refreshed my page, then many of my to-do tasks tripled, quadrupled, and some more. I also can't delete any of them and checking them off still gives me coins and xp but doesn't go away. reloading doesn't help
![screen shot 2015-03-18 at 9 42 06 pm](https://cloud.githubusercontent.com/assets/11549745/6724552/b087e292-cdb7-11e4-9857-7353b8c481d7.png)

**Comment by Alys** [comment]
@tiffogirl97 please try deleting them starting with the one closest to the **bottom** of the list. If that doesn't seem to work immediately, please view your completed To-Dos, untick any duplicates that might be there (so that all instances of that To-Do are now marked as not completed), and then go back to the active list and try deleting starting at the bottom again. I'm sorry this is so annoying! From what we've seen in the past, this should work.

If anyone else in this thread still has problems with duplicate tasks, can you try this too?

**Comment by tiffogirl97** [comment]
it worked! thanks!

**Comment by Alys** [comment]
We think duplicate tasks have been prevented by https://github.com/HabitRPG/habitrpg/pull/4845 (which was merged in https://github.com/HabitRPG/habitrpg/commit/ca72b9a9e1e86262fcab15c7d52ae902953dc7b8) so I'm closing this. It can be reopened if I'm wrong.
