### ISSUE TITLE
can't login via android app

### ISSUE THREAD

**Issue by kbonardi** [HabitRPG/habitica#2457]
Have tried using both username/password and user ID/API token but once both fields are filled, clicking either 'go' on keyboard or 'login' on screen does nothing.

**Comment by ChrisInCanada** [comment]
I have had this same problem through my ipod touch.  Just downloaded the app yesterday after creating an account through my computer and I am unable to click log in.  (I added my ID/API token, but when I click "log in", nothing happens.)

**Comment by deilann** [comment]
Have y'all made sure to click the checkmark saying to log in using UUID/API?

**Comment by ChrisInCanada** [comment]
Yes I have tried that.  If I didn't click that, it asks for username and
password...not UUID/API.

**Comment by deilann** [comment]
Just wanted to make sure because well, last time I had to log in, I forgot
:p

**Comment by ChrisInCanada** [comment]
I checked that box and then typed in the two fields, but then I am unable
to click anything.  The box is there to click log in, but I can't actually
click it.  Pressing it does absolutely nothing, so I don't know how to log
in.  Any advice?

**Comment by deilann** [comment]
I'm terrible with mobile, but when things haven't responded in the past,
rebooting my phone has helped.

**Comment by ChrisInCanada** [comment]
You were right!  Rebooted my phone and it worked!  Thanks.  :D. 

The images don't work now, but at least I can view my task list and dailies.  I'll try syncing with the website and maybe that will work.

Thanks again!

Chris

**Comment by deilann** [comment]
@kbonardi Did you try this?

**Comment by kbonardi** [comment]
Actually, I gave up and downloaded Habit AndroRPG instead.

**Comment by deilann** [comment]
I'm going to (tentatively) close this for now. Feel free to update with more info if you find out more.
