### ISSUE TITLE
Account Disappeared

### ISSUE THREAD

**Issue by putrocca** [HabitRPG/habitica#2458]
My account disappeared suddenly.  Username: putrocca

When I try to log in, it says there is no one registered with my username, and when I try to request a password reset it says it does not know my e-mail address.  I tried all my e-mail addresses and it returned that it didn't know any of them.

I found this old closed similar issue:
https://github.com/HabitRPG/habitrpg/issues/1369?source=cc 

It says the bug is gone but it seems to still be present.

I had been playing for four days.  I was using Google Chrome.  This may or may not be relevant, but I logged out because I noticed some of my Dailys had not reset from the day before and were still grayed out.  I hoped that logging out and logging back in again would fix that, but instead now I can't log in at all.

Is it possible to use the same fix that was used for tobokis before?  He created a new account and the admins somehow merged them?  Not sure I understand.

https://github.com/HabitRPG/habitrpg/issues/1369?source=cc

**Comment by putrocca** [comment]
Addendum: one additional fact: I was sent a Party invite shortly before the bug occurred.  I did not receive notificaiton of it, but the other players can still see my Party invite.

Group ID: 7e02501b-4e9e-4a23-90ab-94def9b98b9e

**Comment by lefnire** [comment]
Try logging in with Facebook, it's the most common mistake ("I promise I didn't use Fa- oh.") If not, I'll look into this soon

**Comment by putrocca** [comment]
Yep, that was it!  Wow, I barely remembered I even HAVE facebook.  I would suggest adding this to FAQ if it's common.  Thanks so much!
