### ISSUE TITLE
Challenges display improperly

### ISSUE THREAD

**Issue by prophecynine** [HabitRPG/habitica#2461]
When looking at challenges from the list (in a guild, for example), the interface seems to expect the user to click on the challenge title again to close it before clicking the next one. For example:

Challenge 1
Challenge 2
...
Challenge 50

Clicking challenge 1 opens the details. good so far. Now if the user clicks challenge 350, it does not open the details for challenge 50 as expected, but instead just closes the details for challenge 1. If there is a big list, this means that it scrolls up and whatever challenge the user was trying to look at is lost. Very frustrating. 
Instead, clicking the next title should close the previous details and open the details of the challenge clicked.

Thanks.

**Comment by deilann** [comment]
See #1682
