### ISSUE TITLE
Tutorial Video Outdated

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#2462]
This early tutorial video needs updating: http://vimeo.com/57654086

^ It talks about generic weapons as 'increasing experience gain', which isn't accurate any more.

**Comment by fragmental** [comment]
I can make videos, but I don't know all the details.

**Comment by colegleason** [comment]
Please take the discussion to [this Trello card](https://trello.com/c/hPftdlM2/406-tutorial-video-needs-updated) as I imagine more people will see it there.
