### ISSUE TITLE
Display error modal for NS_ERROR_FILE_CORRUPTED

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2463]
As mentioned in #2452, it's possible for some sort of browser-level storage error (cookies, local storage, etc). We should catch this error and instruct the user to clear their cookies (at least for HabitRPG).
##

**Comment by librarianmage** [comment]
@Alys @crookedneighbor does this still happen?

**Comment by Alys** [comment]
Frequently. 

https://github.com/HabitRPG/habitrpg/issues/4313 for local storage (logging out clears that).

**Comment by librarianmage** [comment]
Ok! I guess I've never seen it.

**Comment by lemoness** [comment]
Can this be closed now that we use the loading page?
