### ISSUE TITLE
Opening Tavern Tab Doesn't Refresh

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2466]
When you go into Guilds and click on their tab, it automatically refreshes the chat, so that you can see new messages. Is there a logistical reason clicking on the Tavern tab doesn't do the same?
##

**Comment by wc8** [comment]
I can't answer the question, but I can tell you this: if you add Tavern to your browser bookmark bar, I think it does refresh when you access the page that way.

**Comment by deilann** [comment]
Yes. If you open a new tab or do a force refresh or do anything but
navigate to the tavern tab through a funnel, it'll refresh. I'm just not
sure what triggers a Guild refresh upon opening the tab and why it's not
implemented for the Tavern, if there's a reason.

**Comment by PaulSainsbury** [comment]
I think I can fix this one.  I'll send a pull request shortly.

**Comment by paglias** [comment]
If I recall correctly guilds are not cached because they use a lot of memory so each time you open one it's fetched again from the server, while the tavern is cached.

**Comment by PaulSainsbury** [comment]
Yeah, that seems to be it.  I've basically made the controller for '/groups/tavern' update the cached copy before assigning it to the scope.  I'm kinda new to Angular, Node and Mongo so I'm not yet sure if I've broken some best practice or not though.

**Comment by paglias** [comment]
I think it's ok, you should just check one thing: when opening the tavern for the second, third... time can you check that the memory usage doesn't increase too much? Because last time we implemented an auto update for the tavern chat it had this problem, you can use the chrome task manager for that.

**Comment by PaulSainsbury** [comment]
Cool, I'll do that.  How well is the code covered by tests and how do I run them before I submit my pull request? (I'm running on Ubuntu)

**Comment by paglias** [comment]
Actually when you "sync" the chat we have a 100mb surge in memory, for some reason the old chat object is not garbage collected correctly.

About tests, if you installed habitrpg (npm install) and its global dependencies (npm install -g grunt mocha bower) then you can run tests using `npm test`. Anyway I don't think this is covered by tests (they are [here](https://github.com/HabitRPG/habitrpg/tree/develop/test)) and when you send a pull request it's automatically tested remotely using TravisCI

**Comment by PaulSainsbury** [comment]
Yeah, I have very little data in my chat and the sync was adding 2-3mb per sync. I'm trying to spot what could be referencing the "old" object still that might cause the browser to not garbage collect it... but likely that's going to mean I need a far better understanding of the Angular $scope usage. :(

**Comment by PaulSainsbury** [comment]
Looks like this is going to be well over my head to resolve since I'm quite new to all this.  I'll leave it for someone more capable to figure out how to make the combination of tools release memory between refreshes.

**Comment by lemoness** [comment]
Should we close this ticket since we are planning on changing the way chat works in the future?
