### ISSUE TITLE
Deleted To-do's hurt bosses

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2468]
I normally do around 10 damage to the boss daily. If some critical hits occur, this can be 13 or something. Yesterday I had to remove 2 or 3 to-do's, because they didn't apply anymore. They were red and orange, I think one had a checklist. Today, after logging in, I dealt 31 damage to Trapper Santa, which means these to-do's were treated as completed (although they do not show up in the Completed tab, so that's something; last time I did so much damage was when I completed a few red to-do's). Someone please try to reproduce this to confirm.

**Comment by mczuchnowski** [comment]
Again, I removed some to-do's (and really completed only one) and dealt 39 (!!!) damage to Santa today, where my dailies normally deal ~10 damage.

**Comment by deilann** [comment]
Cannot reproduce. On a test user, I activated Trapper Santa. Deleted a variety of red To-Dos, some with checklists, some without. Did not deal any damage to Trapper Santa.

**Comment by mczuchnowski** [comment]
Hmmm...this would mean that I do some extra large damage with some of my dailies for some reason...

**Comment by mczuchnowski** [comment]
OK, we can close this one. This was all most probably caused by Burst of Flames spell (I must have cast it exactly on those days when I removed my to-do's).
