### ISSUE TITLE
Brutal smash doesn't work

### ISSUE THREAD

**Issue by elprohabro** [HabitRPG/habitica#2469]
I tried it on To-dos, on Dailies and on Habits, and neither of them worked. Pls, help my to-dos become less red!

**Comment by elprohabro** [comment]
Shouldn't it be considered a bug?

**Comment by DanielTheBard** [comment]
It might be working but not noticeable. There's a similar problem with one of the healer's spells.

https://github.com/HabitRPG/habitrpg/issues/2081

**Comment by elprohabro** [comment]
Yep, I put my beta tester had and checked again. It works. Thanks!
