### ISSUE TITLE
Feature request (teaching)

### ISSUE THREAD

**Issue by psant000** [HabitRPG/habitica#247]
Hi
I love your program it is fantastic. I would love even more to be able to use it with my classes as a teacher.
I think having classes set up and ticking off habits like completing homework or showing up for class on time or many other things could really motivate students and improve their habits, particularly if they were competing with other students.
What do you think of this idea? Is something like this ever likely to be available
- Peter

**Comment by lefnire** [comment]
absolutely - actually a primary part of our business model we're pursuing, see # 2 of [the wiki](https://github.com/lefnire/habitrpg/wiki/Business-Model)

**Comment by horusofoz** [comment]
@psant000 With the information provided are you cool for us to close this ticket?

**Comment by Pandoro** [comment]
@psant000 I'll close this for now to keep the board clean. We haven't forgotten about the idea yet and this is most definitely one of the main things! Feel free to comment on here though if further questions arise.
