### ISSUE TITLE
Wrong report of item lost on death; two items lost on death

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2471]
When I died, I was told I lost my leather armor; however, what was actually missing (and what I could buy again) was the off-hand short sword, AND the hook sword. Which might be a consequence of the fact that I am a rogue, and leather armor would be a warrior item (in which case, good job making sure I don't have to class change to get my gear back! I would have been very unhappy about that).

**Comment by deilann** [comment]
I think this is related to the referenced tickets. Please follow there.
