### ISSUE TITLE
Make Help available

### ISSUE THREAD

**Issue by Sprachprofi** [HabitRPG/habitica#2472]
Right now it's a real pain to find the Tutorial and FAQ pages. Even after having found them before, I still manage to err in the navigation. I don't see how new users can find these pages at all.

Suggestion: Add a <?> button to the top right, at least for users < 10 levels. Alternatively add "Help" in the user dropdown after "Settings" and before "sync".

**Comment by PaulSainsbury** [comment]
I'll try add this (first time contributor)
