### ISSUE TITLE
Experience bar didn't update when I leveled up with a To-Do checklist

### ISSUE THREAD

**Issue by Twinkly** [HabitRPG/habitica#2473]
Experience bar didn't update (return to zero) when I leveled up with a To-Do checklist: I got the level, but experience bar remains in 220/250 (I was at level 8, and I'm not sure if the max 250 is for level 8 or 9.) I guess this is because I leveled up with a huge To-Do with 18-part checklist. I basically skipped a level :D

**Comment by colegleason** [comment]
The max seems to be 250 for level 9, so maybe it is possible you basically
skipped a whole level?

On Sat, Jan 18, 2014 at 11:25 AM, Twinkly notifications@github.com wrote:

> Experience bar didn't update (return to zero) when I leveled up with a
> To-Do checklist: I got the level, but experience bar remains in 220/250 (I
> was at level 8, and I'm not sure if the max 250 is for level 8 or 9.) I
> guess this is because I leveled up with a huge To-Do with 18-part
> checklist. I basically skipped a level :D
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2473
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by deilann** [comment]
If you have more info @Twinkly , please reopen!

But I think @colegleason is spot on.
