### ISSUE TITLE
Duplicate Challenges, then unremovable To-Dos

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2474]
I popped in to the Bailey Appreciation Guild, and determined in my expert judgment that they were not appreciating Bailey sufficiently. So I made some Challenges!

They went through OK, but one of them the Markdown didn't look right (#2475), so I went in and did a quick Edit. When I returned to the Guild, I discovered there were two copies of that Challenge active!

So I deleted one. Everything looked OK. But when I came back to my own task list, I still had the To-Do from both iterations of the challenge. No "broken Challenge" icon, nothing of the sort. D'oh! Even leaving the Challenge entirely had no effect.

There have been a lot of slowdowns, 503s, and 404s the last day or so; this might relate to one of them but I couldn't say which.

I'd appreciate a cleanup of my task list so I only have one of these Challenge To-Dos, thus the Support tag... User ID 7f14ed62-5408-4e1b-be83-ada62d504931

**Comment by SabreCat** [comment]
Oh wait--this might be a variation on #2456? Not sure.

**Comment by SabreCat** [comment]
Duplicate challenges probably resulted from all that site slowness. I still have a weird To-Do I can't get rid of, though.

**Comment by SabreCat** [comment]
Interestingly, that extraneous To-Do seems not to be affected by cron. I'm tempted to check it off just to see what happens.

**Comment by deilann** [comment]
What happened next?

**Comment by SabreCat** [comment]
@deilann: It's still sitting there. I could probably clean it up if I had db access, but I don't.

**Comment by lefnire** [comment]
@SabreCat i wanna get you & @colegleason database access soonish. Vicky says there's some form for non-disclosure of personal data I'll have to have y'all sign, I'm not sure what it is so I'll start poking around

**Comment by SabreCat** [comment]
Cleaned up, and the root cause is being tracked elsewhere. Closing.
