### ISSUE TITLE
Link Markdown in Challenges doesn't display parenthetical text

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2475]
If I do a []() Markdown in the description of a Challenge, a link is created, but it displays the bare URL, not the text I placed in parentheses.

If I remove the parentheses, the link isn't created at all; it stays plain text. Once I add the parentheses, even with nothing between them, the link text turns blue and becomes clickable.

**Comment by djuretic** [comment]
Can't reproduce it, what is the exact description you are putting into the challenge?

**Comment by SabreCat** [comment]
I am a dumb. I had the [] and the () backward, putting the intended visible text in the parentheses and the link in the brackets. XD Closing!

**Comment by colegleason** [comment]
I thought that might be the issue but for some reason I thought both ways
were valid in Markdown.
