### ISSUE TITLE
Add mana potions!

### ISSUE THREAD

**Issue by wes1** [HabitRPG/habitica#2477]
Just ran out of mana and would like to have more! can we make mana potions?

**Comment by wc8** [comment]
You'll get more the next day, and for every to-do you complete.

**Comment by SabreCat** [comment]
Mana potions purchasable with Gems could be a thing, but they'd have to be hella expensive if they were Gold-purchasable. Otherwise you could infinite loop Pickpocket for as much Gold as you'll ever need :P

**Comment by wes1** [comment]
hey i want to make a pixel art on gimp do you know how to make a pixel art?

**Comment by deilann** [comment]
@wes1 Pixel art board is over here: https://trello.com/c/u3dce871/1-instructions-for-pixel-artists
