### ISSUE TITLE
old Completed To-Dos are archived immediately (not after 3 days)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#2478]
When you view your completed todos, it says: "Completed To-Dos are automatically archived after 3 days." I take this to mean "3 days after you completed them" (which gives the player plenty of time to untick accidental completions and to analyse their done actions).

However, how it actually works seems to be that a completed todo will be archived immediately if the todo is more than 3 days old (i.e., it was created 3 days or more ago). When I complete a to-do that's been in my list for ages, it shows up in my "Completed" tab initially, but then when I reload the page (or wait a few minutes) it has already disappeared. That does not happen when I complete newer to-dos - they stay in the Completed tab for much longer. 

Note though that the old, completed to-do will still appear in the json dump of my tasks (created with the API), so this seems to be a bug in the website's user interface. The old, completed to-do only disappears from my json dump after I have manually cleared completed to-dos.

As a wild stab in the dark, it might be this code that's at fault (habitrpg src/controllers/user.js):

```
}else if(response.wasModified){
  // Preen 3-day past-completed To-Dos from Angular & mobile app
  response.todos = _.where(response.todos, function(t) {
    return !t.completed || (t.challenge && t.challenge.id) || moment(t.created).isAfter(moment().subtract('days',3));
  });
```

I suspect that fixing it would require adding a new attribute that records the date when a task was completed, and I'm reluctant to mess about with the code to that extent. :)

**Comment by colegleason** [comment]
Yeah, it looks like you are right. We'll need to add a completion date.

On Sat, Jan 18, 2014 at 11:22 PM, Alice Harris notifications@github.comwrote:

> When you view your completed todos, it says: "Completed To-Dos are
> automatically archived after 3 days." I take this to mean "3 days after you
> completed them" (which gives the player plenty of time to untick accidental
> completions and to analyse their done actions).
> 
> However, how it actually works seems to be that a completed todo will be
> archived immediately if the todo is more than 3 days old (i.e., it was
> created 3 days or more ago). When I complete a to-do that's been in my list
> for ages, it shows up in my "Completed" tab initially, but then when I
> reload the page (or wait a few minutes) it has already disappeared. That
> does not happen when I complete newer to-dos - they stay in the Completed
> tab for much longer.
> 
> Note though that the old, completed to-do will still appear in the json
> dump of my tasks (created with the API), so this seems to be a bug in the
> website's user interface. The old, completed to-do only disappears from my
> json dump after I have manually cleared completed to-dos.
> 
> As a wild stab in the dark, it might be this code that's at fault
> (habitrpg src/controllers/user.js):
> 
> }else if(response.wasModified){
>   // Preen 3-day past-completed To-Dos from Angular & mobile app
>   response.todos = _.where(response.todos, function(t) {
>     return !t.completed || (t.challenge && t.challenge.id) || moment(t.created).isAfter(moment().subtract('days',3));
>   });
> 
> I suspect that fixing it would require adding a new attribute that records
> the date when a task was completed, and I'm reluctant to mess about with
> the code to that extent. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2478
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by colegleason** [comment]
I feel like I remember looking at this code and thinking "Man, this feels wrong." but I was so tired it didn't even register.
