### ISSUE TITLE
Gaining points by spell casting does not cause to level

### ISSUE THREAD

**Issue by Jotempe** [HabitRPG/habitica#2480]
I have cast "Bust of Flames" of a task and got extra 50XP - this however did not result in leveling, the XP counter was showing 1043/1000. Only after cron rolled to the next day, level-up occured.

**Comment by deilann** [comment]
Check out: https://github.com/HabitRPG/habitrpg/issues/2598 and https://github.com/HabitRPG/habitrpg/issues/2143
