### ISSUE TITLE
Have checklists give multiple drop chances, not one big drop chance

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2484]
In most respects, checklists act as multipliers on their master task. They're collections of subtasks that get scored together. And in most respects this makes sense--you don't want a bunch of separate Gold, XP, and Mana notifications, you want them all totaled up and nabbed together. 

But drops, now, that's a different story. At the moment we put together all those multipliers, making a big checklist give a substantial chance for a single drop. But it'd be hilarious fun if instead _each checklist item yielded an independent chance for a drop_. Polish off a big project, long in the tooth and in the list, and a veritable shower of treasure could burst forth like candy from a struck piñata.

It would be _delicious._
##

**Comment by deilann** [comment]
That would be fantastic. Although, I think drop chances need to be looked at in general. Buffed, I seem to have over 50% chance of a drop! A single well-formed checklist could cover all my drops for the day.

**Comment by SabreCat** [comment]
A comprehensive drop overhaul is on my big projects list, which alas are very difficult to get done except during extended vacations :crying_cat_face:

**Comment by SabreCat** [comment]
Assigning self. Actually doing some work on the aforementioned drop overhaul, should be able to squeeze this in.

**Comment by crookedneighbor** [comment]
@SabreCat Reopen this if you're still working on ti.

**Comment by SabreCat** [comment]
Unassigning myself for now, but reopening. I still think this would be a good improvement to make, but coding it turned out not to be straightforward (mostly because of the way we notify on drops).

**Comment by Alys** [comment]
I've suggested this before and got a positive response but I can't recall
from whom. :)

We could give a drop chance when the user ticks off each checklist item,
then one more drop chance (as now) when they complete the To-Do. That
should be easier.

It also gives an immediate (sometimes) reward for each step in completing
the To-Do, which some users have said they'd like.

**Comment by deilann** [comment]
Sometimes, though, users want to delete checklist items before checking off
the To-Do, so they don't get credit for them.

Consider "Grocery Shopping" as a task. It's pretty easy to add your
shopping checklist in, check it off as you get things. But do you want
credit for buying bananas? Not necessarily. So you delete the checklist
items off, then claim the task.

I've sometimes done this just to make some steps clear (not grocery
shopping, but other tasks) and keeping track of things.

So the immediate reward? Not always a good idea.

On Sun, Jul 12, 2015 at 1:50 PM, Alys notifications@github.com wrote:

> I've suggested this before and got a positive response but I can't recall
> from whom. :)
> 
> We could give a drop chance when the user ticks off each checklist item,
> then one more drop chance (as now) when they complete the To-Do. That
> should be easier.
> 
> It also gives an immediate (sometimes) reward for each step in completing
> the To-Do, which some users have said they'd like.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/2484#issuecomment-120761300.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by SabreCat** [comment]
I'd be curious how common a use case that is. It's OK if a minor workaround is useful for an edge case (here, you'd have to delete the item straight up rather than check it off and then delete it, and that's only if you don't like the extra drops). In most checklist scenarios, I think a bit of instant gratification would be a big plus.

**Comment by crookedneighbor** [comment]
I agree with Sabe.

**Comment by Alys** [comment]
I'm assuming that if we add drops to checklist items, we'd do it only for To-Dos, not Dailies. This means that you could create a shopping list using a Grey Daily to avoid drops for checklist items. There's disadvantages to that workaround though (e.g., Grey Dailies are usually hidden; although we have an issue to make that optional per Daily), so I'm not strongly pushing the idea of a drop chance for each checklist item.

We have in the past discussed a clone task feature which could be used to copy a To-Do to a Daily, and vice versa. I'd like to see that implemented one day, and it might make this workaround better. That's probably far in the future though.

**Comment by crookedneighbor** [comment]
@Alys The [clone service](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/taskServices.js#L25-L30) is already written. Just needs some code to implement the button on the tasks page. 

I'm not sure how I feel about limiting checklist drops to todos. Feels weird to have it on one and not the other. 

Also, I feel like checklist drops should be a rarer occurrence than regular drops. Though, that might add too much extra complexity to the code.

**Comment by Alys** [comment]
For Dailies, I believe it's much more common than for To-Dos to use checklists for purposes other than marking off that you've done a small task. They're used for reducing or avoiding damage from Dailies that you can't do but shouldn't be punished for, and a drop for that use case would be inappropriate. We see that use suggested in the Tavern often. 

Dailies' checklists already don't add to the earnings you receive when you complete the Daily. Cron uses them to only reduce damage. I think there's already enough differences between checklists on To-Dos and Dailies to make one more difference negligible.

**Comment by SabreCat** [comment]
Closing this. I still think it's a fun idea, but we use Trello for misc feature requests and enhancements like this these days!
