### ISSUE TITLE
Logging in after a month

### ISSUE THREAD

**Issue by SecretCheri** [HabitRPG/habitica#2485]
I'm trying to log back in after about a month of vacation but it's ot letting me at all. When trying to recover my password as well it is saying it can't find a user under that email.

**Comment by lefnire** [comment]
See http://habitrpg.wikia.com/wiki/FAQ#Username_and_email_not_recognized

**Comment by deilann** [comment]
If you need more help @SecretCheri , please reopen this ticket.
