### ISSUE TITLE
Leveled up when I shouldn't have after HUGE xp gain

### ISSUE THREAD

**Issue by PaulRosenfield** [HabitRPG/habitica#2487]
I was a level 46 mage with intelligence of 115 at 117xp out of 1130 needed to reach level 47. I completed a crazy huge Todo with 11 checklist items, set to hard difficulty, which had been sitting on my Todo list for months. That gave me 571 experience, bringing my new total to 688.  Strangely, however, this caused me to level up. I have reloaded my page several times to make sure the problem is with the server and not with Chrome. Indeed, I am now level 47 with 688/1160xp. I even got a new stat point to allocate.

**Comment by colegleason** [comment]
I imagine it may have actually awarded you 1584 exp and the notification
was wrong since it doesn't take leveling into account.
