### ISSUE TITLE
Chat needs "ignore" feature

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2489]
First, I apologize for not putting this in Trello. I am unfamiliar with that tool and cannot find a way to add an item - or to search existing items.

Tavern chat currently includes a talkative individual with frequent name changes, whose "humorous" repartee doesn't work for me. I'd very much appreciate a way to avoid reading anything he posts; otherwise I'll probably just stop visiting the tavern.

In general, this was bound to come, as Habit became better known. We're lucky we don't (yet) have an infestation of outright griefers, advertising spambots, or similar. Let's get some tools in place to deal with them, at both an individual and a community level.
##

**Comment by deilann** [comment]
I agree. At the very least, being able to filter out someone's posts would be appreciated. (Especially if you could do what some systems do with downvoted comments-- show them if you click a link to expand them, but by default hide them). That way, if context got terrible without what was being said, it would be possible to go back and see what happened.

$user1 chatchatchat
$user2 chatchatchat
(3 messages have been filtered. show)
more chatting here

**Comment by crookedneighbor** [comment]
We have a blocking feature for private messages now. We could use that for filtering out messages by those individuals.

We could either automatically hide messages of users that are set to be blocked (with the option of showing it anyway) or include a setting for how the blocking mechanism works. IE, just block PMs or block PMs and hide public chat messages.

Thoughts?

**Comment by Alys** [comment]
@crookedneighbor My only thought is that it should not be possible to block or hide messages from moderators or staff.

**Comment by crookedneighbor** [comment]
Should the same go with blocking PMs? I don't think there's anything stopping people from blocking PMs from mods or staff.

**Comment by Alys** [comment]
Yes, I think it should not be possible to block PMs from mods or staff.

**Comment by lemoness** [comment]
Agreed on both counts.

**Comment by deilann** [comment]
+1

**Comment by crookedneighbor** [comment]
Users are no longer able to block mods and staff from the modal: https://github.com/HabitRPG/habitrpg/commit/403554ae3afc3c9741ba6f1a10cc751889c6c290

It's still possible to block mods via the api, I believe. Working on that now.

**Comment by crookedneighbor** [comment]
Hmmm... [somewhere in here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L652-L656) we need a way to determine if the uuid of the potentially blocked user belongs to an admin. Is there an easy way to do that?

Alternatively, we can just allow users to block admins via the api, but make sure that the codes for pms and public messages ignore the block if the user is an admin. 

Really, we should have the code do that anyway, in the case that someone blocks a mod before they become a mod, otherwise we'd have to run a migration every time someone gets promoted to mod to make sure no one had blocked them previously.

Thoughts?

**Comment by deilann** [comment]
I think the latter solution is more practical.

**Comment by paglias** [comment]
Closing in favor of #4218 that has a bounty on it
