### ISSUE TITLE
End Game

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#249]
![MirrorShield](https://f.cloud.github.com/assets/3267747/105735/fe9754d6-69c3-11e2-8874-bf05c12a4bb0.PNG)
After a certain level ie 100 you should get a pop up saying something to the effect of "congratulations you beat habitrpg" and the game just restarts from level one but you get a special item the second time round. Like in LOZ:MC after you beat the final boss you can get the mirror shield from the goron.

**Comment by StanLindsey** [comment]
Maybe the option to "prestige" a-la Call Of Duty. I can image in a couple years time people will be level 847392. 

Also would be interesting on your second "play-through" to compare stats; "You've leveled twice as fast this play-through" "You've completed "1hr Productive Work" 56 less times than this time last play-through"

**Comment by ghost** [comment]
@SlappyBag I was thinking of something like that actually

**Comment by horusofoz** [comment]
I personally do Not think there should be an end game. My understanding is the goal of HabitRPG is to motivate users to GTD in real life.

I know there is some motivation to winning a game but if someone reaches level 100, they should have improved their life to a degree where motivation is no longer a question.

If we wanted users to restart their progress at a certain level cap, we could possibly use a modified form of the "ancestor/descendant" concept originally proposed for death [here](https://github.com/lefnire/habitrpg/issues/223#issuecomment-12829853).

**Comment by Pandoro** [comment]
I personally like the idea of rewarding people with some nice treat once they reach certain levels, but I think this is very closely related to <a href=" https://trello.com/card/awards-badges/50e5d3684fe3a7266b0036d6/19">Trello card: Awards & Badges</a> 

However starting over is something I never liked. I never got how this ladder system in Diablo II was fun :-/ Why the hell would I want to start from scratch after I had my fancy stuff already.

**Comment by horusofoz** [comment]
@Neohuman Would an [award, badge](https://trello.com/c/4uWICvDf) or [rare item](https://trello.com/c/2brf9FNW) be sufficient reward for reaching certain milestones like level 100?

**Comment by ghost** [comment]
Not sure

**Comment by horusofoz** [comment]
Could you provide additional details as to how you would like your idea implemented and I'll raise it as a separate Trello card?

**Comment by ghost** [comment]
Hmm a special sword and shield would be nice actually. Like in LOZ that is
what I was thinking.

**Comment by Pandoro** [comment]
I would say that is included in rare items ;) If new items are made and implemented, a rare one, ONLY to be obtained at some high level would be easy to do. 

Going back to level 1 though... I still don't like that idea :X

**Comment by horusofoz** [comment]
I have added this as Milestone Awards under [Awards & Badges](https://trello.com/c/4uWICvDf). Please navigate there to add your vote and voice.
