### ISSUE TITLE
Long profile names in chat cause scrollbar

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2490]
![screen shot 2014-01-19 at 9 07 04 pm](https://f.cloud.github.com/assets/232327/1951466/1911265a-8180-11e3-9f6f-f7ee8cbb2927.png)

I think we should either make them wrap inside the box or just set a length limit.
##

**Comment by lefnire** [comment]
gosh, that guy....

**Comment by deilann** [comment]
I've been thinking for a while that setting a character limit would be good, even for ones that don't cause a scrollbar. When going through the names that come up after typing @, the longer names seem to cause a bit of lag and are just awkward.

**Comment by brightbold** [comment]
There's also a horizontal scrollbar (at least in Chrome/Mac) when the message fits perfectly on one line. I think it's the space for the +1 that causes it.
![tavern scrollbar](https://f.cloud.github.com/assets/405068/1967479/cb764360-82d5-11e3-866e-f527ec7fb4b7.png)
Maybe should that be a separate issue, if the solution is to cap name length. But we also might want to do `.tavern-chat li .scrollable-message, .party-chat li .scrollable-message { overflow-x: hidden; }` so you'd never get horizontal scrollbars. Not sure if there's a downside to that - it could hide the end of really long URLs posted by people who don't know how to use Markdown; it would hide the end of insanely long usernames; not sure what would happen with the trashcan if it's your own post.

**Comment by deilann** [comment]
If raw URLs generated hyperlinks upon posting, rather than pasting as text,
that would negate the URL problem. I know people have been asking for that
anyway.

**Comment by brightbold** [comment]
+1. URLs converting to hyperlinks automatically would be awesome for more than just reducing scrollbars!

**Comment by deilann** [comment]
wrt possibly blocking the trash can--

as the time stamp changes, the trash can would likely move and become
visible again

**Comment by librarianmage** [comment]
@Alys Do we still want to do this?

**Comment by Alys** [comment]
Seems like a good idea but not urgent (I haven't seen any other examples of this problem). At some point, we'll be making improvements to chat and profile names and this might be something to consider then, if not before. We'd want the length check to be both server side and client side, so doing this before API v3 might not be the best idea in case it impacts code that would be changed by the API upgrade.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Chat is handled different now, so this should no longer be an issue. If it happens again, we can open a new ticket.
