### ISSUE TITLE
Dailies not reseting for night owls

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#2497]
Hey I sometimes have days where my dailies don't reset and I've been having them more frequently lately.
I wonder if it's because some days I don't check in until after midnight even though my dailies reset is set at 4am.  
I'm going to try checking in before midnight just to get them reset and see if that helps.

**Comment by deilann** [comment]
Follow this here: https://github.com/HabitRPG/habitrpg/issues/1057
