### ISSUE TITLE
to-dos misfiring in app

### ISSUE THREAD

**Issue by prophecynine** [HabitRPG/habitica#2499]
I have the android app and I recently tried to check off some to-dos.
It consistently misread my taps and checked off the wrong ones. 
Not sure if the culprit was the app or my phone, but I suspect the app...

**Comment by negue** [comment]
What System Version do you have (it may helps to find a bug^^)

Do you still have this bug on your app?

Edit: Duplicate of #2392

**Comment by negue** [comment]
Closing this for now, if this problems still happens, we'll reopen this issue.
