### ISSUE TITLE
can't delete Todos

### ISSUE THREAD

**Issue by guyerson** [HabitRPG/habitica#250]
no problem with tasks or dailies though

**Comment by Pandoro** [comment]
My girlfriend created an account a few hours ago and experienced the same thing. 

(Account name Pandori)

**Comment by lefnire** [comment]
I think caused by move away from `_completedIds`, we'll need to integrate derby filters. See [this issue](https://github.com/lefnire/habitrpg/pull/226#discussion_r2810391).

**Comment by Nelmalih0** [comment]
This also happened to me a few seconds ago

**Comment by lefnire** [comment]
Fixed ([see notes](https://github.com/lefnire/habitrpg/pull/226#discussion_r2813953))

**Comment by lefnire** [comment]
it'll kick in on next server restart, a few hours or so
