### ISSUE TITLE
synced sudden death

### ISSUE THREAD

**Issue by kundragon** [HabitRPG/habitica#2501]
me and a party memeber both died this morning for no reason
i was just reaching lvl 6 yesterday and was in full health.

chrome v 32.0.1700.76 m
UID 8ce39acf-679b-4f88-b1c7-8e9f5b8ab55a

**Comment by ibvee** [comment]
Partner didn't die. But I did. Not so much red tasks, lvl 35, 45/50 health. 

Damage with refreshing this morning was -55 Which was not normal at all for the amount of open tasks...

808aa439-96bf-4af1-9f4e-a74757d1e57f

firefox 26.0

**Comment by deilann** [comment]
Important question: Are y'all doing Trapper Santa?

**Comment by ibvee** [comment]
I did, but finished it already. However, this did happen to me once while
doing trapper Santa also.

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544
