### ISSUE TITLE
Repeatedly clicking and unclicking dailies causes inconsistent xp allocation

### ISSUE THREAD

**Issue by alexhudici** [HabitRPG/habitica#2503]
If the user clicks a daily and unclicks it once, the XP and other resources get allocated and unallocated correctly. However if you do this a few times on the same daily an extra amount of XP gets allocated. 

Haven't looked @ the code but it is possible that the algorithm that allocates points based on streaks interprets the multiple 'completed' clicks as a streak even though you had unclicked it as well. So it allocates more XP the more you click and unclick it then click it again.

**Comment by paglias** [comment]
See #964
