### ISSUE TITLE
item not in inventory after purchase + took incorrect gold amount

### ISSUE THREAD

**Issue by chaoticawesome** [HabitRPG/habitica#2508]
Hello, 

I attempted to purchase the Oiled Leather armor (30 gold), and the game took 20 gold from me and did not give me the armor, even though it notified me that I had bought it. I was able to successfully purchase the Oiled Leather when I tried again, though I can't give myself back the 20 gold until the holiday event is over. 

Browser: Firefox 26.0
User ID: 79167200-f69d-4af3-bcac-6d166c21fd31

This is what my console comes up with:
![consolehabitrpg](https://f.cloud.github.com/assets/6465482/1969377/53b8b7c4-82f1-11e3-9b5d-b1f8557cb2a7.png)

Thanks in advance.

**Comment by chaoticawesome** [comment]
Hello again,

It just happened again, this time with the Scimitar (35 gold). It took 34 gold and did not give me the item despite saying so. It also spontaneously gave me 20 gold and some silver. I should note that both times this has happened I bought something directly after using my Rogue Pickpocket ability on a Habit. I hope this gets resolved quickly!

**Comment by deilann** [comment]
H'm, due to teh timing @chaoticawesome I'm thinking this was a 503 issue. If you're still having this problem, please reopen the ticket.
