### ISSUE TITLE
Redoing quest failed.

### ISSUE THREAD

**Issue by NinKenDo64** [HabitRPG/habitica#2509]
So my party already finished the first trapper Santa quest and recovered the polar bear mount. However the next quest didn't start (not sure if it was supposed t or not). Anyway, the other day I saw that we could redo the Trapper Santa quest, so I invited the party to do so.

One of the members in our party has become inactive, so after doing the invite, I booted him from the party while his acceptance of the quest was still "Pending", thinking this would start the quest, but it didn't. Now when I check the party screen, it shows that everybody has accepted the quest invite, but the quest never starts, and there's no button to force it to begin.
![untitled](https://f.cloud.github.com/assets/4001922/1970080/46002f86-8300-11e3-8aa1-cb520dd7bfc2.png)

**Comment by lefnire** [comment]
Did you send the invites? Only the quest leader can force-start (which is what you want in this case).

**Comment by NinKenDo64** [comment]
I assume I've sent them given it says they've been accepted. I also think I'm the quest leader, else how was I able to boot somebody?

**Comment by deilann** [comment]
@CapitalistKenCat Booting someone from the party means you're the _party leader_. Quest leader is the person who brought up the scroll. Were you the one who activated the scroll?

**Comment by NinKenDo64** [comment]
Thanks. I was definitely the one who bought the scroll. The problem's
resolved itself, which seems both good and bad, since now I can't figure
out what the problem was.

**Comment by deilann** [comment]
I think I know what the problem is:

When you booted the member, rather than force starting the quest, the quest is now waiting on the booted member, who can never answer, confusing the heck out of it, and making it sulk in the corner. So I'm going to leave this open, for further investigation (and quest therapy).
