### ISSUE TITLE
Sprites fuzzy on Mobile Safari for iOS7.0.4

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#2510]
**[edit by @lefnire]: This also happens on the _app_ now too, not just browsers. Needs to be fixed ASAP**

I've been using the mobile Safari version of HabitRPG since it has more features than the iPhone app. Today I updated my OS from 7.0 to 7.0.4 and when I went on the mobile site again the character, pet, and item icons were garbled as screenshotted. 
http://i.imgur.com/mV4MV8L.jpg main screen
http://i.imgur.com/8wpyP0o.jpg Matt Boch
http://i.imgur.com/My2dQAl.jpg pets (golden fox surrounded by undiscovered)
http://i.imgur.com/vhqNuHi.jpg eggs in inventory

Logging out and logging in again didn't help, neither did clearing history, cookies, and website data. The issue doesn't seem to be appearing in the app.

**Comment by ghost** [comment]
Yeah, I'm having the same problem tonight iOS Safari AND iOS Chrome.

**Comment by GrayDays** [comment]
Update: the garbled images have spread to the gold/silver and equipment icons since OP. http://i.imgur.com/LYimNrT.jpg Haven't bought any equipment or sold any items between posting earlier and taking this screenshot a minute ago, only checked off a couple of habits and dailies.

**Comment by ParisiT** [comment]
Same issue, so it's probably not just you.

**Comment by deilann** [comment]
That looks like it's reading the sprite sheet wrong, thinking it's larger than it is, so when it gets into position, it's in the wrong place and zoomed out.

**Comment by lefnire** [comment]
Does refreshing the page fix the issue?

**Comment by ghost** [comment]
No, refreshing does nothing. Neither does restarting the browser(s) or, in my case, the iPad.

**Comment by deilann** [comment]
Did a little more research-- this has been a problem in the past. iOS is
scaling the spritesheets, so they display wrong. The only fix people have
found in the past is to use single images for iPad users. Basically, iOS is
being stupid, not the site.

**Comment by ghost** [comment]
It worked fine until about the time the gryphon quest was added. Unlike the OP, nothing changed in my device (no updates--all automatic updates are turned off on my device) and it happens in Chrome as well. So something changed on the site recently. It has basically made the image heavy pages unusable on iOS since it is impossible to tell what you are clicking in the inventory, pets, market.

**Comment by deilann** [comment]
Gryphon quest would have changed the spritesheet/made it bigger, so that could be it.

**Comment by deilann** [comment]
Haven't heard about this in a bit. Is it still happening, folks?

**Comment by ParisiT** [comment]
Yep. Happens every time I log in with Safari on my Ipad

**Comment by GrayDays** [comment]
Same. In fact it's gotten worse as I equipped more gear and the new quests were released. http://i.imgur.com/jfuSIhG.jpg But, at least I'm a dragon!

**Comment by ghost** [comment]
Yes, it's still a mess. Can't see Bailey when she pops up (as Trapper Santa but it's on top of other garbled graphics so it's hard to see). Difficult to change equipment; tell what food, potions, and eggs are in inventory; hatch pets; feed mounts; change look of avatar, etc. Can't see anyone's avatar.

**Comment by lefnire** [comment]
Found two solutions: (1) [multiple spritesheets](https://github.com/Ensighten/grunt-spritesmith/issues/67#issuecomment-34786248), (2) [-webkit-background-size](http://stackoverflow.com/a/5222054/362790). I may not have time just yet to tackle, placing here for posterity

**Comment by GrayDays** [comment]
Upgraded to iOS7.0.6 overnight (with endless chagrin that my phone won't let me turn off automatic downloads, my regrets on that already) and I'm gonna assume it's that which has made things...weirder now? http://i.imgur.com/IlF9sDR.jpg http://i.imgur.com/Ki0XHFQ.jpg I don't know, I'm...pretty sure those emoji aren't supposed to be there? They don't seem like they should probably be there.

**Comment by GrayDays** [comment]
As of now the emoji issue I screenshotted earlier today seems to have resolved itself. Other graphics remain as they appear in earlier screenshots.

**Comment by ghost** [comment]
The random emoji are a different issue that show up on multiple platforms. Can't find the ticket right now but I know it's been mentioned on Github before.

**Comment by mutantant** [comment]
Same issue here, but on both Safari and Chrome on iOS 7.0.6. Since it affects both browsers I am assuming it is because of a core change to iOS itself since the 7.0.4 update.

**Comment by deilann** [comment]
Yes from what I know the issue is that ios is scaling the software.

**Comment by ghost** [comment]
The problem exists on 7.0.4.

**Comment by lefnire** [comment]
fixed, but can't push till later. Heroku + NPM issues now, and dead computer. ETA tonight

**Comment by ghost** [comment]
At the risk of sounding ungrateful, is the fix supposed to have fuzzy graphics?

**Comment by lefnire** [comment]
It's due to the css directive which prevents spritesheets from scaling. This is a temp fix, the real fix (somewhere above in the comments) is to use multiple small sheets, but this is a bigger project.

**Comment by ghost** [comment]
Ah, thank you. The fix is still a vast improvement over the garbled graphics, so thanks for that.

**Comment by lefnire** [comment]
Ok, this has been fixed and pushed to [beta](https://beta.habitrpg.com). Could some of you test around on mobile safari at that url to see if things are still blurry? This fix should also fix it for the mobile apps once those go live, including the non-existent images on older android devices

**Comment by GrayDays** [comment]
Everything looks good to me, no issues.

**Comment by lefnire** [comment]
Cool, I'm gonna do a bit of device testing tonight, push to prod and cut some new mobile releases.
