### ISSUE TITLE
Rebirth Causes You to Lose Limited Edition Gear

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#2511]
So, it's understandable that rebirth can force you to buy back your normal gear and even your contrib/backer gear. But by making you lose limited edition gear, you lose out a limited edition item forever (assuming you use rebirth after that item is available). 

I spent the time to hit lvl 60 and get all the new winter gear before finally using rebirth. Only to discover I needed to re-purchase all my limited edition winter gear once I hit lvl 2. Now of course, I could be wrong. Perhaps the winter gear is permanently unlocked for me now, since I bought it once? I hope this is the case, otherwise I think there should be a fix or it will devalue using Rebirth :/

**Comment by deilann** [comment]
Looking at the code, it suggests that you'll be able to repurchase it, just like someone who lost it via death, but I may be reading it wrong.

**Comment by SabreCat** [comment]
Yup, this was fixed already. We spotted it when we introduced the logic to re-buy gear pieces on death, and fixed it then.
