### ISSUE TITLE
503 Application Error on addTask op

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2514]
Just tried to add a task and got this error:
![screen shot 2014-01-22 at 1 33 28 am](https://f.cloud.github.com/assets/232327/1971756/cbc2f324-8337-11e3-925a-e8af244b3d03.png)

HTTP status error: 503

It was performed on a batchUpdate. That was the only op included. Curiously, the params and query for the op seemed to be undefined.

**Comment by colegleason** [comment]
Oh, it seems the entire app is down. JK.

**Comment by lefnire** [comment]
Yeah trying a repair, sorry shouldn't be too long. One sec
