### ISSUE TITLE
tried to invite a friend to a party i am in, got booted out of said party and then couldn't access habitrpg for 5 mins

### ISSUE THREAD

**Issue by Foxkitten** [HabitRPG/habitica#2515]
Hi, i've fixed this error by just waiting and refreshing lots but it's still something that happened so i thought i'd put it here

I just tried to invite a friend to a party i am in and it came up with an application error and asked me to try again after a few moments. I did this 3 more times, and then tried closing and opening my tab to see if that would help. 
When heading back through to my party i noticed that my fellow party members had disappeared from the top and also that i could choose to join someone's party again under the party tab - i.e. i'd been booted out of my party.

I thought maybe refreshing would help - maybe it'd forgotten something or loaded an old cache by mistake or somesuch.
Then all i got was a message saying application error, and no option to see my tasks or log in or anything. a white screen with Application Error.
One of my refreshes gleaned me an Error 503 message.

I looked around this bug reporting site for anyone with similar issues and read someones suggestion to log out and in again. I couldn't reach the page that lets me log out but i figured out that deleting my cookies and saved passwords on Chrome would do that for me. So i did that and tried to log back in, and after some fumbling about remembering my password and trying to get the Forgot Password thing to recognise my email address, i remembered my password and signed in.

Everything is back as it should be, except my friend doesn't have his invite. oh well i will try again.

Sorry this post is so long, i wanted to make sure i'd given you guys enough details incase it's of any help.

**Comment by Foxkitten** [comment]
This is completely not an important issue, i just wanted to make sure you guys know this happened as it was worrying. i thought my account had been deleted or something.

**Comment by deilann** [comment]
Yeah, this sounds like just the issue of the 503s. Let us know if it persists.
