### ISSUE TITLE
Improvements to Habit's history graphs

### ISSUE THREAD

**Issue by PaulRosenfield** [HabitRPG/habitica#2516]
Lemoness asked me to post about some of the problems with Habit's graphs (i.e. the 'history' of a user's experience or a particular daily) and about some possible ways to improve them. I am writing a textbook on data analysis, and I find the current versions difficult to impossible to read. Also, they contain so little information about a user's history that they aren't really worth reading.

I think graphs showing the user's history could be a really cool and motivating feature if done right. Graphs done right would not only be readable, they would tell a story about productive weeks, unproductive weeks, daunting tasks that were overcome or procrastinated on, quests completed, etc.

I was going to attatch my somewhat carefully put-together 6-page pdf, but it turns out that Github doesn't support pdf uploads. I will probably try to figure out how to create a dropbox link sometime tommorrow, but it is nearly 4:00 in the morning here, so I'm done for today. For now, I'm just e-mailing a copy to Lemoness.

Hopefully some of this stuff will be useful!
~Paul
##

**Comment by PaulRosenfield** [comment]
This should be the link to the pdf. https://www.dropbox.com/s/ion4ismamewscmp/Habit%20Graphs.pdf
Apologies for the rough figures and rough writing. It was 4am. But hey! I enjoyed it, and I hope you do too!

~Paul

**Comment by deilann** [comment]
Man, that is awesome. My only comment would be that one of your assumptions is incorrect: experience does not always go up. When a player dies, they lose a level and any experience they had beyond that level. But with a bar chart like that, you could have it dip below the x axis for death.

**Comment by colegleason** [comment]
I could probably code up some prototypes in D3js when I have time.

On Wed, Jan 22, 2014 at 12:17 PM, deilann notifications@github.com wrote:

> Man, that is awesome. My only comment would be that one of your
> assumptions is incorrect: experience does not always go up. When a player
> dies, they lose a level and any experience they had beyond that level. But
> with a bar chart like that, you could have it dip below the x axis for
> death.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2516#issuecomment-33050861
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by lemoness** [comment]
Paul, this is awesome except that the last page contains BLASPHEMY. Let the record stand that I have never been a Bieber fan ;p That post should have been about octopuses.

**Comment by lemoness** [comment]
But seriously - especially because history and detailed data will be part of premium accounts, this is important stuff.

**Comment by librarianmage** [comment]
Should this be put on hold?

**Comment by lemoness** [comment]
It should indeed!

**Comment by librarianmage** [comment]
Should this issue be closed, due to the current absence of value graphs?

**Comment by librarianmage** [comment]
If not, should it be marked as available and not on hold?

**Comment by Alys** [comment]
That PDF from @PaulRosenfield still has some great ideas in it so I think this issue should be kept open so we don't lose track of it. I'm leaving it on hold though because I think some significant changes to the method of displaying history are still being considered.

**Comment by Alys** [comment]
Labels updated to "status: on hold - needs design" at Lemoness's suggestion.

**Comment by ghost** [comment]
@Alys is anyone working on this, mind if i try prototyping something?

**Comment by Alys** [comment]
@laphiloctete That's a question for the staff rather than me, but to speed it along, would you like to describe what you have in mind?

**Comment by ghost** [comment]
This might be a bit of an ambitious first goal considering I don't know vue.js at all and I haven't even gotten set up locally yet :sweat_smile: but I would like to tackle the Habit History first... basically visualize the data here: https://oldgods.net/habitrpg/habitrpg_user_data_display.html

...Probably in the form of some sort of heatmap, not unlike githubs. I use this workout tracking app called "FitNotes" that has a very useful view. Here's a screenshot:

![screenshot_20180710-175925_fitnotes](https://user-images.githubusercontent.com/3860820/42545181-3c5b0296-846b-11e8-8fa8-6dce80a1d3ba.jpg)

With this view you are able to select any day and make amendments to that data.

I don't necessarily need to go with colored dots but something that signifies how many times each habit was done each day, I'm not sure what the appropriate design would be yet (especially considering mobile), I have over 30 habits myself...

But I would also like to build in the capability to edit my habit count for the previous day if possible. Sometimes I work late and don't sleep until after midnight, currently the app only gives you one opportunity to check off dailies (and only dailies not habits) after midnight.

**Comment by safareli** [comment]
It would be great if you restore this feature as well 
<img width="222" alt="Screen Shot 2020-03-11 at 11 27 36 AM" src="https://user-images.githubusercontent.com/1932383/76392818-c41c1480-638b-11ea-98e3-8a7dc4883a82.png">

**Comment by SabreCat** [comment]
We're moving this to an internal project board used for prioritizing feature requests. Closing to keep the HabitRPG/habitica issues list bug-focused!
