### ISSUE TITLE
Link to LFG board is to the wrong URL

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2517]
I imagine the LFG forum on Wikia has been renamed recently, as the link in the Tavern sidebar now points to a board title which doesn't exist: http://habitrpg.wikia.com/wiki/Board:Looking_for_a_Group_(LFG), rather than http://habitrpg.wikia.com/wiki/Board:The_Archery_(LFG).

**Comment by deilann** [comment]
Furthermore, it would make lives a lot easier if the link didn't end in ), as this makes it really hard to link via markdown in the tavern.

**Comment by ghost** [comment]
We should probably also set up a redirect for the old URL.

**Comment by deilann** [comment]
Agreed. I'd suggest creating a redirect for the old URL, then creating a redirect called just "The Archery," which would be what's linked to instead on the sidebar so that it's easier to Markdown.

**Comment by ghost** [comment]
Doesn't look like I have the ability to create pages in the Board section, otherwise I'd set these up myself.

**Comment by deilann** [comment]
Is it possible to create the page elsewhere then just use the redirect URL
to go there? While that wouldn't allow you to fix the redirect for the
current link, it would be a quick fix to having a markdownable link in the
sidebar for easy Tavern linking.

Also, just so you know, it confuses the hell out of me to see Ryan sending
me messages on Github.

**Comment by deilann** [comment]
kk, this link will work to get to the LFG board, without having a ) at the
end: http://habitrpg.wikia.com/wiki/The_Archery

**Comment by ghost** [comment]
Haha. Yeah, too many Ryans. Story of my life, right there.

Coolio. Glad you found that. Made the page, but then had to run off before I could report back here.

**Comment by ghost** [comment]
Created a pull request and awaiting acceptance.

**Comment by deilann** [comment]
@ryepdx Sorry, I just realized I direct commited this.
