### ISSUE TITLE
Two parallel parties exist; HabitRPG switches randomly between them

### ISSUE THREAD

**Issue by poopstick** [HabitRPG/habitica#2518]
Okay, way back when HabitRPG was still on the old system, I set up a party and added friend #1, who joined.

Then, after the transition to the new back end (when we all got our veteran wolves), I added two more friends. Friend #2 joined, friend #3 didn't.

I have never seen both friend #1 and #2 at the same time. I was mostly seeing friend #2 (friend #1 died a lot) through December. Then, about two days after activating the Trapper Santa quest, he disappeared and was replaced by friend #1 who hadn't played in at least a month and believed his character was dead. Going to the party page showed him in the party. Friend #3 was on the invitation list, and friend #2 was nowhere to be seen. Also, the trapper Santa quest had disappeared.

Then, a few days ago, friend #1 disappeared and friend #2 came back, along with the Trapper Santa quest. The quest hadn't registered any of my completed dailies or to-dos for the entire time that friend #2 was missing.

Then, about an hour ago, after a refresh, it switched again. Friend #2 is gone, and friend #1 is back. And the trapper Santa quest is missing again. It's like my character is shunting between two parallel universes.

Interestingly, friend #2 says he still sees me on his display.

**Comment by lefnire** [comment]
This happens periodically for old users. When you see the "wrong" party
next, leave it. Refresh and you'll see the right party. If you see another
wrong party, you may be in more than 2. keep leaving until the right party
shows up consistently on refresh. Tell your mates to do the same

**Comment by poopstick** [comment]
Super! That worked. Never would have thought of that. Glad to have escaped
the mirror universe before my own goatee'd self showed up and murdered me.
