### ISSUE TITLE
Random subset of dailies not refreshing on cron

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2519]
This has happened to me twice over the last week; it's not ALL my dailies, however, it's an extremely random subset. (Not, for instance, the last dailies I checked off before going to bed). My reset time is 6am, but until just recently, I've never had problems with it, and I check off everything before midnight. The streaks for said dailies were also, sometimes, borked.

Also, I'm not sure if this is related, but I got a big chunk of xp (about 200) upon rollover today, which might be the xp for the dailies that got checked.

**Comment by deilann** [comment]
This is still a known iteration of #2494
