### ISSUE TITLE
Streak reset even though I didn't skip it

### ISSUE THREAD

**Issue by ohtree** [HabitRPG/habitica#2524]
I had a task (which is a challenge so I can't go and fix the streak) which had thirty or forty days on it and even though I did not miss clicking it, the streak reset. Can I get this fixed? And what caused it? I do have a custom day start, could that be the cause?

**Comment by ghost** [comment]
This happened to me too, after a 25 day streak.  I also have a custom day start, but I've had it for a while and it hasn't changed.

**Comment by deilann** [comment]
Gonna guess this is related to #2601
