### ISSUE TITLE
I don't have the Veteran Wolf

### ISSUE THREAD

**Issue by 101Leafy** [HabitRPG/habitica#2527]
I'm an Original User, so I have the Veteran Badge. However, I don't have the Veteran Wolf. Why?

**Comment by deilann** [comment]
Mentioned here: https://github.com/HabitRPG/habitrpg/issues/2329 Not sure if the push ever happened, though, as I still don't have mine.

**Comment by SeanStiny** [comment]
I also still don't have mine.

User ID: 776d604e-b3d4-4b61-8c7a-6928ef24e40a

**Comment by lefnire** [comment]
dupe of #2329 follow there. I'll push the migration sometime this week
