### ISSUE TITLE
Social Media Connection

### ISSUE THREAD

**Issue by ivyxaur** [HabitRPG/habitica#2530]
(I'm sorry I'm pretty new to this whole thing I hope I'm doing this right and that this hasn't been suggested before!)

Alright, I'll be the first to say that I hate how games will sometimes do everything in their power to make you tell your friends exactly how much you're having fun. However,  HabitRPG is something I'd love to have the option of reporting my progress on! If you gave the option of sharing on facebook in a way that wasn't BLATANT IN YOUR WAY OBVIOUS ADVERTISING, I think it'd be well-received. 

For example, if I finally clean my room after marking it as a hard task and letting it harden into that rich red color, finally doing it makes me want to screenshot it on my completed and caption it "YESS". If I make a 30-day streak of no-smoking, and I want to show everybody that's been by my side through that struggle, I'd post that to facebook to show off my hard work

Alternatively, even sharing your habitrpg stats might be a cool thing. It could post an image consisting of your avatar with your first name, level, # of completed tasks, etc. It'd make a great summary of productivity!

With the posts thing, perhaps there could be a button on your completed to-dos that shares, there could be a button in dailies and habits under "progress" in dailies that shares, 

All in all, I think passive social media could make a big breakthrough in this amazing new thing you guys have made, and if done right it wouldn't annoy users very much but the ones that use the sites could bring a larger fan following to it!
##

**Comment by deilann** [comment]
Note: I am not an admin on the site, or anyone of importance. However, I _am_ going to meet up with the folks of importance tomorrow and talk about social media and SEO. So I am so glad to hear your thoughts on this.

I do find it annoying when things constantly ask me if I want to share with X social media site (Freerice, I'm looking at you. "You just answered five questions right in a row? Would you like to share that on Facebook?)

In my head, I'm struggling to figure out exactly what the logistics would be. Right now, there aren't notifs for most of the things you'd want to share, like super awesome streaks, or finished To-Dos. Maybe opening Dailies with Twitter/Facebook integration set would have a button that allows you to "share your streak"? To-Dos could be togged to share upon completing.

It would definitely be interesting to combine https://github.com/HabitRPG/habitrpg/issues/2516 and this, with the stats generation. There's talk of having a stats page for hRPG in total-- maybe a dedicated stats page for charts and stuff for users as well, then you could share a chart. (Dropdowns to select a chart for a specific Daily/Habit?, so they don't all show at once?)

Do you feel like if the buttons were there, but it never popped up at you, asking you to share, that it would be unobtrusive enough? Would occasional popups prompting you to share be annoying? Frex, every 5/10 levels, share that you leveled up, every 21-day streak, share the streak, every badge, share the badge.

**Comment by deilann** [comment]
Hokai, so this has been talked about, and it is definitely a thing that is wanted, not just by you, but by hRPG. The only issue is in implementing it. But it will happen!

Further thoughts: Sharing gives a small gold bonus. Not only would this increase the number of shares, which is good for the site, but sharing increases accountability, which is crucial for forming habits. Drawbacks: people could spam sharing for gold. Solution: Gold bonus is only given upon "suggested" shares, such as 21 day streaks, high-value To-Dos, reaching certain levels.

Would definitely love to see some community feedback on what level of prompting would be appreciated, what they'd find spammy, and what they think about gaining gold from sharing (especially if gold is only gained upon suggested shares, as this would help form what should generate prompts).

**Comment by ivyxaur** [comment]
I feel like having the button there and pointing it out a little out would be enough to get people that want to use it to use it without irritating people who don't. Also, you can add an option of hiding all social notifications, which would help those who hate sharing in general out a lot!

As far as a gold reward, what you said works, but also you could add in a "drop" system with gold on sharing to keep people from going overboard. So the logic would be "Well, you might get something, and you could get this same benefit by doing other tasks, but hey if you wanna share you can share just be aware that your friends and followers might hate you a little bit if you spam". If you have control over the probability of drops, you could code it to be more likely to drop things the longer the streak or the harder the activity.

Regarding where to place the share button, this is my advice
Habits/Dailies: Under the Progress menu (or stat board if that becomes a thing)
To-Dos: Under Completed, next to the completed to-do
Rewards: Pop-up when you earn the reward

In fact, with the option to block pop-ups up, you can perhaps have corner notifications of "You have a 21-day streak! Would you like to share this on (Facebook/Twitter/Tumblr/whatever we can do)?"

As for how to make it work, I know that a lot of sites have a "share on facebook" button which basically takes a generated photo and posts it to the person's timeline (for example, "I got Darth Vader! (_picture of Darth Vader_) Which Star Wars character are you?")

We could take this to the pixel art board and have somebody create an image of some sort to represent what kind of task and then generate text on it to say different things for different tasks. For example:

Habits: (some image along the lines of mastering a skill, like a book or a checkmark or something) "[Player] is keeping up the habit of [Habit](on HabitRPG.com)!"

Dailies: (some image along the lines of mastering a skill as well, either the same or different than the one for habits) "[Player] has a [X]-day streak of [Daily](on HabitRPG.com)!"

To-Dos: (some image along the lines of slaying a beast or finishing a quest) "[Player] completed [To-Do] on their To-Do List (on HabitRPG.com)!

Rewards: (some image of a jewel or something else desirable) "[Player] just earned [Reward](on HabitRPG.com)!"

Level-Ups: (player avatar maybe for this one?) "[Player] is now Level [Level](on HabitRPG.com)!"

Again, I'm just offering suggestions, but it'd be awesome to see this all come into a reality! As a pixel artist myself I might even be able to contribute a bit! :)

**Comment by rachelkelly** [comment]
Adding my support to this idea, love this.  How thoughtful!

**Comment by Gaelan** [comment]
@deilann I feel that if there is a gold bonus, clicking on the 'share' link then not going through with it on the social network site should be sufficient. Reasoning:
1. Most people will go through with it anyway
2. It allows non-social-networkers like me (or people who don't want to spam their feeds) to gain the small gold bonus anyway
3. Gold should be productivity-only, supporting HRPG should be gems

**Comment by paglias** [comment]
I really think this would be a fantastic way of marketing HabitRPG, the first idea that comes to my mind is adding a small "Share" text link at the end of notifications which would open a modal allowing to share what you just achieved.

@lemoness @lefnire

**Comment by lefnire** [comment]
_Absolutely_ this would be a huge marketing win for us. @lemoness this might be a good one to bump in prio in the monthly feature internal trello bit?

**Comment by lemoness** [comment]
Yes!!!!! Will add to Trello when I am at my computer

**Comment by crookedneighbor** [comment]
@lemoness Is this still desired? (I assume so) Want to add it to our trello?

**Comment by lemoness** [comment]
It's already on there :)

**Comment by paglias** [comment]
This is possible when levelling up and in a bunch of other situations. Shall we close it?
