### ISSUE TITLE
Angular syntax in html attributes is sanitized by Jade

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#2531]
I just discovered that this piece of code:

![selezione_018](https://f.cloud.github.com/assets/589911/1986017/af2529de-8446-11e3-85c5-fd2c38f2f6b4.png)

It is rendered:

![selezione_016](https://f.cloud.github.com/assets/589911/1986020/b565f044-8446-11e3-897e-e9f24739c551.png)

It is a quite serious bug, it makes all the ng-if, popover, ng-class... unuseful if they have any "html" code (like `&, <, >, "...`)

It is due by the fact that Jade automatically escape HTML code for security reasons. See http://jade-lang.com/reference/#bufferedcode

We must change all the `=` to `!=` and also write this somewhere so it doesn't happen in the future.

If we could disable this "feature" at all it would be even better. 

@lefnire @colegleason

**Comment by colegleason** [comment]
Well, shit.

On Thu, Jan 23, 2014 at 10:09 AM, Matteo Pagliazzi <notifications@github.com

> wrote:
> 
> I just discovered that taking this piece of code:
> 
> [image: selezione_018]https://f.cloud.github.com/assets/589911/1986017/af2529de-8446-11e3-85c5-fd2c38f2f6b4.png
> 
> It is rendered:
> 
> [image: selezione_016]https://f.cloud.github.com/assets/589911/1986020/b565f044-8446-11e3-897e-e9f24739c551.png
> 
> It is a quite serious bug, it makes all the ng-if, popover, ng-class...
> unuseful if they have any "html" code (like &, <, >, "...)
> 
> It is due by the fact that Jade automatically escape HTML code for
> security reasons. See http://jade-lang.com/reference/#bufferedcode
> 
> We must change all the = to != and also write this somewhere so it
> doesn't happen in the future.
> 
> If we could disable this "feature" at all it would be even better.
> 
> @lefnire https://github.com/lefnire @colegleasonhttps://github.com/colegleason
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2531
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by paglias** [comment]
No option to disable it, we'll have to do it. What about a global search &
replace with a code editor? It's not necessary everywhere but it won't hurt

2014/1/23 Cole Gleason notifications@github.com

> Well, shit.
> 
> On Thu, Jan 23, 2014 at 10:09 AM, Matteo Pagliazzi <
> notifications@github.com
> 
> > wrote:
> > 
> > I just discovered that taking this piece of code:
> > 
> > [image: selezione_018]<
> > https://f.cloud.github.com/assets/589911/1986017/af2529de-8446-11e3-85c5-fd2c38f2f6b4.png>
> > 
> > It is rendered:
> > 
> > [image: selezione_016]<
> > https://f.cloud.github.com/assets/589911/1986020/b565f044-8446-11e3-897e-e9f24739c551.png>
> > 
> > It is a quite serious bug, it makes all the ng-if, popover, ng-class...
> > unuseful if they have any "html" code (like &, <, >, "...)
> > 
> > It is due by the fact that Jade automatically escape HTML code for
> > security reasons. See http://jade-lang.com/reference/#bufferedcode
> > 
> > We must change all the = to != and also write this somewhere so it
> > doesn't happen in the future.
> > 
> > If we could disable this "feature" at all it would be even better.
> > 
> > @lefnire https://github.com/lefnire @colegleason<
> > https://github.com/colegleason>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2531>
> > .
> 
> ## 
> 
> ## Cole Gleason
> 
> Student, University of Illinois at Urbana-Champaign
> Email: cg@colegleason.com
> Website: colegleason.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2531#issuecomment-33141831
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
This is probably the reason for #2492 : 
`data-custom="?uid={{user._id}}&amp;apiToken={{user.apiToken}}"`

What I don't understand is why angular doesn't throw any error

**Comment by paglias** [comment]
Maybe it's a false alarm. I mean it's sent escaped by the server but then it's correctly interpreted and if you check an element attributes with the chrome console they are not escaped... Strange
