### ISSUE TITLE
How to view exported data? (.CSV, .XML, .JSON files)

### ISSUE THREAD

**Issue by Arigator** [HabitRPG/habitica#2532]
As completed ToDos get archived now after 3 days and I still want to be able to view them in some way, I used the export function in the "Settings" - "Data Export" sub menu. 

I think it would be important to put up a tutorial or just a short description on how to view these files the best way, as I don't think this is basic knowledge for HabitRPG users (I, for one, have no idea. First I tried to open it with LibreOffice's Calc and then I googled "CSV viewer" "XML to PDF" etc. for hours). 

As an alternative, could there be a "Export list as PDF" option?

P.S.: I used GitHubs search function before writing this issue and I found some threads about the export function, e.g. #1831
They cover the topic of WHICH file formats to offer, but they do not cover the topic of WHAT to do with these downloaded files.
##

**Comment by zoebeagle** [comment]
You should be able to open XML in pretty much any browser, but the data might not be very useful for you.  CSV you should be able to load into Excel or another spreadsheet program.  You might need to open the spreadsheet program first, then Open (or import) from there.

**Comment by Arigator** [comment]
Thanks for your reply! I tried to import it with the free Excel alternative "Libre Office Calc" so far. The import of the .CSV works, but this file only contains habits and dailies, no ToDos! The import of the .XML does not work at all. When I try to open the .JSON file in Calc, it gets opened in "Libre Office Writer" instead (the "Word" alternative) and yes, all the completed ToDos are there but it's not formatted and the ToDos get buried in code. I do not even wish for a table view, a simple list of the titles of the ToDos would be enough. So I probably could try to write a script which fetches only the lines which start with "text", e.g.:
"text": "28m Reading"
and outputs a new txt file, but I hope there's an easier and elegant solution.
Tomorrow I try to open it with Microsoft Excel on my father's computer but even if it opens it, I hope there's a freeware solution as well, because I am very pleased with Libre Office and do not want to buy a Microsoft Office license just for that.

**Comment by Arigator** [comment]
If I go to my overview page and mark all the text in the "To-Dos" row with my left mouse button and copy the selection to a document file, than I get a nice list with bullet points. Great, if I just would have tried that before my completed tasks were archived.

So I tried to get the important lines out of the .JSON file by using grep. I noticed that all the lines which contained the titles of my habits, dailies and to-dos start with "text". I use Linux, but I am not a programmer so I only could create a very simple line of code so far:

```
grep "text" /home/my-username/userdata.json >> completed_todos_list.txt
```

The output txt file also contains my habits and dailies, but I can simply erase them.
The good thing is that it also contains the checklists with indented paragraphs (I am no native English speaker so I hope I use the right term here) underneath the To-Dos.

**Comment by marcelosizer** [comment]
Or you can grep again to keep only the to-dos.

``` bash
grep "text" /home/my-username/userdata.json | grep "to-do" - >> completed_todos_list.txt
```

**Comment by Arigator** [comment]
Hi @Sinza- , thanks for your advice! I just tried your suggestion, but it did not work, the output is a 0 byte txt file (I also used my real user name instead of "my-username"). As I understand it, grep searches for lines of text which contain the word that was put in quotes and the output is the whole text which this line contains. There are lines at the end of every To-Do paragraph which contain "type": "todo", but they are not in the same line as "text", it looks like this:

```
{
      "date": "",
      "text": "compare price offers for bass guitar",

[...]

      "type": "todo"
    },
```

So I suspect that | grep "todo" eliminates every hit from the results that was fetched before by grep "text".

But Sinza, do you have an idea how one could replace every "text": in the output file with a bullet point?
So that instead of this:

```
      "text": "reinstall Linux on SSD hard drive",
          "text": "install firefox addons, point thunderbird to email profile folder, etc.",
          "text": "put shared NTFS music partition in fstab for auto-mount at system startup",
          "text": "etc.",
      "text": "compare price offers for bass guitar",
      "text": "put 32 GB SD card in smartphone, install Cyanogenmod and move apps to SD card",
```

it looks like this:

```
      - reinstall Linux on SSD hard drive
          * install firefox addons, point thunderbird to email profile folder, etc.
          * put shared NTFS music partition in fstab for auto-mount at system startup
          * etc.
      - compare price offers for bass guitar
      - put 32 GB SD card in smartphone, install Cyanogenmod and move apps to SD card
```

That would be awesome! Thanks in advance if you (or anyone else) can help me out on this! (I know that this can be done in a text editor by using a "search + replace" function, but it would be nice if this could all be done with one command or one shell script.)

**Comment by marcelosizer** [comment]
Ah, yes, it won't work. You can use sed.

``` bash
grep "text" filename1 | sed s/\"text\"\:/-/ >> filename2
```

This will change all "text': to -, to change the checklists to \* you can try:

``` bash
grep "text" filename1 | sed s/\"text\"\:/*/ | sed s/^*/-/ >> filename2
```

The first sed will switch all **"text":** to \* and the second sed will switch, starting from the beginning, the characters \* to -. This will only switch the todos as the checklists have spaces before them.

I've just started learning sed yesterday and had no opportunity to use it. Tested it here and seems to work, let me know how it goes!

**Comment by meganstrickland** [comment]
Is it intended that the Habit History CSV does not include completed To-Dos? That seems counter-intuitive to me.

**Comment by lefnire** [comment]
@meganstrickland not intended, we probably just need to add that in. But for cleared completed to-dos, those are gone-zos

**Comment by Arigator** [comment]
@Sinza- Thank you a lot, this sed command works perfectly! Your second suggestion `| sed s/^*/-/` did not work for me. None of the "*" has been converted to "-". But it looks much nicer nevertheless! It's more important that the checklist lines are indented, anyways and this works nicely!

@meganstrickland I agree with you, to me it appears as if the CSV file basically contains just the data (habits, dailies) which we do not necessarily need to export, because they are the same every week, so the content of the file does not change much over time and because of the repetition it's also the data which everyone most easily remembers in case of data loss (unlike a long list of To-Dos, which I would hardly be able to reconstruct in case of data loss).

@lefnire first and foremost, thank you a lot for HabitRPG, it has been very helpful for me in the last few months already! I am not a native English speaker, so what does "gone-zos" mean? When I google it, the first hit is a definition by urban dictionary which is not what you mean here, I guess.

Also, a point of criticism: I think it was bad timing that one week before the introduction of the subscription system you started consolidating/archiving the list of completed To-Dos of people. The subscription feature "Retain full history entries" would have been the biggest incentive for me to subscribe with the monthly fee of 5$ when I still had the about 90 completed To-Dos in my profile overview. But after they had been erased from the profile and after I already invested several hours over the course of the last week in researching the best way to get back a clear list out of the exported XML/JSON file, I do not have that incentive anymore. 

But I supported HabitRPG a few weeks ago with a one-time payment of 5€ (for 20 gems), so I hope that I don't sound ungrateful.

**Comment by marcelosizer** [comment]
@Arigator yep, wasn't working again. This one I checked with the actual username.json file so it should work:

``` bash
grep "text" userdata.json | sed s/\"text\"\:/*/ | sed "s/^......\*/      -/" >> usernewdata.json
```

**Comment by lefnire** [comment]
@Arigator completed to-dos are archived for performance purposes, see https://github.com/HabitRPG/habitrpg/issues/976 . If your completed to-dos weren't archived, your browser would begin freezing upon loading your account. Your to-dos are still available in your account, accessible via csv/xml/json export, or via API access - just not in the web or mobile UI. This isn't what "retain full history entries" is about, that feature is with regards to your graphs (the up/down history of particular tasks).

**Comment by lefnire** [comment]
However, clicking "clear completed" button will also remove archived todos. This likely isn't desired behavior, well need to add a page for managing archives items before when addressing that concern

**Comment by kenfink** [comment]
As a flexible tool/workaround, I'd like to write a script in a Google Docs spreadsheet to grab the data from HabitRPG and post it into a spreadsheet daily after the chron job runs.  I've figured out how to pull the JSON, but I need help parsing it and pasting it into the spreadsheet.  Can someone help me with this?

EDIT: [It there now IS a dateCompleted stored for Tasks.] 

Plus once this is done, the script can be shared in GDocs for others to use their data flexibly as they like.

Can you help me?

**Comment by Alys** [comment]
The wiki's [Data Export](http://habitrpg.wikia.com/wiki/Data_Export) page contains information about the export formats and how to view and understand them.

I'll go through this GitHub issue to see if there's anything that can be added to the page so that we can keep everything in one place. I think the wiki is probably the best place for it because it's easier there to purge outdated material and keep everything organised.

If anyone finds anything on the wiki page confusing, please say so!

**Comment by Alys** [comment]
Content from this issue has been added to [Data Export](http://habitica.wikia.com/wiki/Data_Export) (thanks to Lexinatrix) so I'm closing this now.
