### ISSUE TITLE
Dailies are completely messed up

### ISSUE THREAD

**Issue by BlackSphinx** [HabitRPG/habitica#2534]
Last night when I went to bed, all of my daily tasks were checked off. The first three of them were on large streaks - 18 if I remember correctly, since I have managed to do them every day since I joined. The fourth should have been on a streak over 8. Today I get on and I take a 1.8 HP penalty, see that two of those 18 streaks have been reset to 2, see the fourth streak has also been reset to 2, and all of my dailies but one are ALREADY checked off which gave me a significant amount of gold for NO work on my part. When I refreshed the page again, all of the streaks that had been reset to 2 suddenly were reset to 1. I know for sure I had checked these off before I went to bed, which is before my chron reset. What happened?!

**Comment by taibhsearachd** [comment]
Something like this seems to have happened to me too. I'd actually done all my dailies yesterday, and went to bed with 48 HP. I woke up, and all my streaks are gone, and I got slapped down to 18 HP. This is really demoralizing. :\

**Comment by deilann** [comment]
Probably related to this: https://github.com/HabitRPG/habitrpg/issues/2554
