### ISSUE TITLE
Cannot Change Display name

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2539]
Going to change my display name, it shows default text "Full Name" rather than my current display name. Changing it to desired display name changes nothing. Other things change-- I can set my blurb without any issues.

Did a refresh. Did a hard refresh. Cannot get the new display name to change.

**Comment by Urse** [comment]
also had this issue.

**Comment by colegleason** [comment]
I actually experienced this on a local install but I have yet to investigate.

**Comment by deilann** [comment]
Stray paren?

`.control-group.option-large
      label.control-label=env.t('displayname')
      input.option-content(type='text', placeholder=env.t('fullName')), ng-model='editingProfile.name')`

That extra paren makes it so that it doesn't have anywhere to save the data.
