### ISSUE TITLE
Progress graph bug

### ISSUE THREAD

**Issue by murilomgh** [HabitRPG/habitica#254]
The progress chart is showing a day repeatedly, for all the Habits. See above:

![progress](https://f.cloud.github.com/assets/1236297/106600/d5b812ac-6a00-11e2-8a40-598fbc02fb4e.png)

**Comment by ghost** [comment]
@murilomgh that is the same as https://github.com/lefnire/habitrpg/issues/130

**Comment by StanLindsey** [comment]
Thanks for reporting this @murilomgh. I'd ask @horusofoz if this is the same issue as he has been involved in that other thread. Seems they may be different or may be linked, he shall decide =D

**Comment by horusofoz** [comment]
I think this is a separate issue from [#130](https://github.com/lefnire/habitrpg/issues/130). My understanding of the issues are:
130 = Graph not displaying
254 = Graph incorrectly displaying data as reported under [219](https://github.com/lefnire/habitrpg/issues/219)

While similar , at this stage I think we need to treat 130 and 254/219 as separate issues until we know more.

**Comment by horusofoz** [comment]
Issue being addressed under [GitHub #219](https://github.com/lefnire/habitrpg/issues/219).
