### ISSUE TITLE
Bring back click delay, but at a much shorter interval

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2541]
We briefly implemented a 10-second delay on + Habit clicks, to discourage cheating. This was an unpopular move among many users, since it's a common workflow to repeat a Habit or achieve several increments (laps, chapters, whatever), then tally them all up at once when you're back at the app. If you read 7 chapters for your "read a chapter of a book" Habit, what took a few seconds to log before took a full minute instead.

So we reverted that change. However! Some users found the click-delay useful, since it caught accidental double-clicks, especially common with a touch input. So why not implement a click cooldown, but with an interval to the tune of 0.5 seconds (maybe 1 second, probably not more than 2)? In fact, you could implement this for _all_ tasks, not just + Habits. That would help avoid accidental double-charges on Rewards, double damage on - Habits, and rollbacks of checked Dailies.
##

**Comment by deilann** [comment]
How did the code for this work? I suggested adding it as a feature. If it was put in settings and asked for a value, we could have users implement it as would work best for them. Some might have found the barrier of ten seconds good to discourage their own cheating. I persinally just want to prevent tablet double clicks, but if taken a step further it could be more than a double click blocker for those who want it.

**Comment by SabreCat** [comment]
@deilann: [This is the 10sec delay commit](https://github.com/HabitRPG/habitrpg/commit/ad4ca6655a3bdd870bb08173530372f81fdc9102) if'n you wanna study it!

**Comment by JadelynnOpal** [comment]
I'm on board with the idea of either adjustable time delays or optional time delays. Like, you could bring back the 10 second delay but just as a possible option in the Settings.

**Comment by octern** [comment]
I think configurable options are snazzy, but I also agree with sabrecat that a .5s delay would probably make almost everybody happy. You might want to implement some kind of button-down animation so it's clear when the cooldown is in effect.

**Comment by deilann** [comment]
I'd definitely need longer than .5s delay for a tablet.

**Comment by ghost** [comment]
Between the mouse overs that will not die and click delays, I'm having a hard time telling if my click has gone through on an iPad. If it's implemented I'd really like the option to turn delays off.

**Comment by wc8** [comment]
How about Settings option, enter your own delay in seconds or tenths of a second?

(For habit-spamming, I'd suggest a 50-habit-per-day cap for up-habits instead of a delay.)

**Comment by librarianmage** [comment]
@Alys is this still being discussed?

**Comment by Alys** [comment]
I haven't seen anything apart from what's here. We still don't care about "cheating" and wouldn't want to restrict the use Habit clicks (there could even be some legitimate uses for more than 50 a day), but avoiding accidental clicks would be nice.

**Comment by librarianmage** [comment]
Is this still an issue? I feel like waiting for the blue bar to load is a click delay in itself.

**Comment by SabreCat** [comment]
There's still nothing stopping the user from mashing a task again while the blue bar is cycling.

**Comment by lemoness** [comment]
I'm not sure we want this any more, though. Wouldn't it be better to just focus on our planned fixes for sync errors/batch actions?

**Comment by Alys** [comment]
Yes, THI's ideas for action queues, undoing, etc, would cover all this.
