### ISSUE TITLE
No images showing

### ISSUE THREAD

**Issue by agenthemlock** [HabitRPG/habitica#2543]
None of the images on HabitRPG-my avatar, the pets, eggs, anything-show up.  I am using my IPad, and this issue occurred a couple of days ago when I bought a couple of upgrades in equipment for my character, I think it was the Leather Helm and one other item.

**Comment by deilann** [comment]
Probably related to https://github.com/HabitRPG/habitrpg/issues/2510

**Comment by deilann** [comment]
Is this still happening @agenthemlock ? If so, please reopen the ticket.

**Comment by agenthemlock** [comment]
Hi,

Yes, it's still happening.  How do I reopen the ticket? Do I repost the issue?

**Comment by deilann** [comment]
I can reopen it. But in the future, there's a reopen button next to comment.

**Comment by agenthemlock** [comment]
Thank you!

**Comment by AlTest** [comment]
Hello,
Today I encountered the same kind of problem.
Every sprite – avatar, inventory, items in the Rewards space, pets, eggs, Perfect day achievement – is invisible. Everything else seems to be working fine.
I always get the same error message :  "Please reload, "Error Group not found or you don't have access." (see Chrome console for more details)." I keep reloading the page, yet nothing happens but the error message.
I don't understand what it means, nor I know what is the Chrome console – by the way, I'm on Firefox on a standard computer.
User ID : c4624ba7-c57e-49c7-a7c2-36a0110a5b5d

**Comment by AlTest** [comment]
(Gold & siver coins, gems and NPCs are also affected.)

**Comment by yarrow** [comment]
Same error message, but (aside from the message) things seem to be working fine for me.  (I just started a few days ago, so may have overlooked some misbehavior that would be obvious to those with more experience.)

The error message fades out after a few seconds, but reappears if I do in fact reload.  The behavior is the same in Firefox and Chrome, and the Chrome console doesn't seem to have more details.

**Comment by deilann** [comment]
The error message is related to something else.

**Comment by charoncherry** [comment]
I'm having this issue as well on Safari on iPad. No images for avatars, items, gold, etc.

**Comment by skymaiden** [comment]
This issue is still occurring, making the app horrible to use on an iPad 2 with iOS 6 (the game loses the fun aspect when you can't see any visuals). Possibly related to this bug? http://stackoverflow.com/questions/15061332/ios-background-sprite-not-displaying

**Comment by negue** [comment]
On Jul 31, 2014 the spritesheet was splitted to multiple files. So it may fixed this issue on iOS Safari.

Is this error still present on your iPads? @skymaiden @charoncherry @agenthemlock

**Comment by skymaiden** [comment]
My iPad was updated to iOS 7 this month, and after updating the app the sprites are now behaving. :+1:

**Comment by agenthemlock** [comment]
I didn't update my IPad to iOS7, but the sprites work now! Hurrah! :)

Thank you!
