### ISSUE TITLE
Dailies reset early

### ISSUE THREAD

**Issue by agenthemlock** [HabitRPG/habitica#2544]
My dailies reset an hour and a half earlier than it should have, and as a result I have lost a couple of streaks and HP.  I haven't ever touched the "Custom Day Start" option,  and it's been resetting at 12 midnight every night until now.

**Comment by agenthemlock** [comment]
Uh-oh...now that it is past midnight, my dailies reset AGAIN-and with none of my tasks checked off, I took a really heavy hit in HP.  What is happening? How can I fix this?

**Comment by AlexCharlton** [comment]
I've experienced something similar, with my dailies resetting around 6 hours before midnight. Unlike @agenthemlock, however, my dailies did not reset at midnight and remain checked.

I recently (as of Wednesday) checked out of the Inn, and dailies behaved well for that night.

User: 41c180e8-54c1-4de0-934c-ad1fde851dc3
Browser: Chrome on Linux

**Comment by Swotfabs** [comment]
My cron just ran at 5 PM rather than midnight.
My custom day start is at 0 (untouched).
Looking at my habit history (under Data Export under Settings) all of my dailies for today (01/25/2014) are recorded twice, once at 01-25-2014 06:17:00 and once at 01-25-2014 23:05:55.

I will look at what it does tomorrow morning.

**Comment by ylysyym** [comment]
I'm not sure if it's related, but twice now I've woken up in the morning and not had my day start. That is, all the dailies I checked the previous day are still checked. My streaks are intact, but it means I can't do my dailies for the day. My custom day start is at 5.

**Comment by deilann** [comment]
Let's move this here: https://github.com/HabitRPG/habitrpg/issues/2544
