### ISSUE TITLE
PayPal Issue

### ISSUE THREAD

**Issue by bingbangzoom** [HabitRPG/habitica#2546]
When trying to donate the $5 in return for gems, I clicked on the Paypal feature, which redirected me to an "about blank" page. The card option is working. I've refreshed the page but the Paypal option is still not working.

**Comment by deilann** [comment]
Check out this ticket: https://github.com/HabitRPG/habitrpg/issues/2492 A fix is in the works, but it's proving to be more difficult than anticipated.

**Comment by paglias** [comment]
Let's follow at #2492
