### ISSUE TITLE
When viewing the description of constitution a one follows the text

### ISSUE THREAD

**Issue by DeadlyAlbino** [HabitRPG/habitica#2548]
A simple typing error but one that gets on my nerves
![constitution](https://f.cloud.github.com/assets/6493403/1996592/c8a6156e-8516-11e3-81eb-ae9be47db844.PNG)

**Comment by deilann** [comment]
Whoops. Don't know how that got in there. I've tacked it to my pull request.

**Comment by DeadlyAlbino** [comment]
Thank you, keep up the good work
