### ISSUE TITLE
Unknown Habit added by a third-party service

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2558]
I just had a new habit show up. It has the title "a3cb20b3-c655-4a9d-ade1-609cdda07e88" (this is neither my UUID nor my API key) and the description includes the "This task was created by a third-party service..." text. I don't think I'm using any third-party services -- I was using the Chrome extension a long time ago, but it's been disabled for months. I use the Android client on occasion (the official one), but I didn't think that counted. 

Is it possible for a task like this to be created in error, or does it definitely indicate that somewhere, some application is using the API to interact with my account?

**Comment by lefnire** [comment]
No, it's an error, don't worry you don't have stray plug-ins. I know where
it fires falsely, I just haven't found what triggers it

**Comment by octern** [comment]
Thanks for the reassurance.

**Comment by lefnire** [comment]
Oh no, keep it open. Just giving FYI on the secondary question

**Comment by thereforebucket** [comment]
So, if we get a habit similar to this (same message, different code), should we delete it?

**Comment by lefnire** [comment]
Yes

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/1402
