### ISSUE TITLE
[Suggestion] Upgrade/downgrade from habit to daily

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#256]
After playing with my habits/dailies for a bit, I find myself realizing that somethings I thought should be worked on as a habit and done multiple times per day really should be a daily item.  Obviously it could be deleted and reentered, but I like having the graphs/history and would like the item moved from one category to another.

**Comment by racuna** [comment]
A "drag and drop" feature between columns would be great

**Comment by StanLindsey** [comment]
The drag and drop feature is fantastic and I am surprised hasn't been mentioned before. I've added a card on Trello:
https://trello.com/c/nytaY3gn

Make sure to press "v" on the card to vote.
Closing for house keeping, thanks @sabin144 & @racuna
