### ISSUE TITLE
Dailies Won't Reset

### ISSUE THREAD

**Issue by TheCarpinator** [HabitRPG/habitica#2561]
This is the second time I've checked off my dailies after midnight, but before my daily reset time (4am), only to find them checked off still. I've tried clicking "sync" and putting my reset time back to midnight, but the dailies aren't resetting.

**Comment by octern** [comment]
Did you also take damage and lose streaks as if the dailies had been done on the new day, instead of the day you checked them off?

**Comment by lefnire** [comment]
Follow on #1057
