### ISSUE TITLE
Boss damage display is misleading at best

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2563]
This morning when I look at the display it appears that my fiery gryphon has 76 HP left. I remember that it started at 300 HP, and can see that I've done 25.2, 26.1, and 22.7 damage to it, totalling 74. 

A committee of folks on tavern chat, with their own anomalies, figured out the problem. The number (76) shows % of health remaining; the bosses total HP are unavailable. (300-74)/300 = 75 2/3 %.

Any UI that requires a committee to decode is broken by definition. And there's no way that a heart symbol followed by 76 gives any suggestion that it's anything other than a number of HP. (Given the placement and value, I'd taken it as the amount of damage done, with a significant rounding error.) 

For what it's worth, I believe this is new breakage - I must have seen the 300 HP sometime in the days since I started the quest. 

Will attempt to attach a screen shot.

**Comment by ArlieS** [comment]
![screenshot from 2014-01-25 11 19 43](https://f.cloud.github.com/assets/4530463/2002429/1a899c00-85f5-11e3-967c-d4db7f8f4461.png)

**Comment by colegleason** [comment]
Oh, I may have broke this yesterday. Sorry! Let me fix it real quick.

On Sat, Jan 25, 2014 at 1:16 PM, ArlieS notifications@github.com wrote:

> [image: screenshot from 2014-01-25 11 19 43]https://f.cloud.github.com/assets/4530463/2002429/1a899c00-85f5-11e3-967c-d4db7f8f4461.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2563#issuecomment-33297229
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by colegleason** [comment]
I meant to round the remaining HP up instead of to the nearest integer since it is confusing when a boss has 0.2 HP and it just says 0/300. I got distracted and accidentally replaced it with percent.

**Comment by ArlieS** [comment]
Thanks. That was impressively fast.

**Comment by colegleason** [comment]
It's easy when you know what to look for ;-)

On Sat, Jan 25, 2014 at 1:54 PM, ArlieS notifications@github.com wrote:

> Thanks. That was impressively fast.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2563#issuecomment-33298309
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com
