### ISSUE TITLE
Original user achievement has HTML tags in it

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2564]
![screen shot 2014-01-25 at 1 52 40 pm](https://f.cloud.github.com/assets/232327/2002517/5671c166-85fa-11e3-9463-a94edee25878.png)

**Comment by octern** [comment]
Also spotted in the Fiery Gryphon challenge description:

`your friends by completing your dailies! <strong>All damage to and from a boss is tallied on cron (your day roll-over).</strong>`

Maybe a more general issue?

**Comment by marcelosizer** [comment]
These are different errors. The `<strong>` tag had a syntax error in a .jade file and I'll upload once I'm done with main.json splitting. The `<em>` tag is on the main.json file and @paglias implemented string interpolation so there may be something missing there but we'll have to wait for him.

**Comment by paglias** [comment]
@colegleason 's one is due to the use of `=` instead of `!=` in a jade file, I'll fix it 

@Sinza- , @octern 's one is due to translations or it's something different?

**Comment by marcelosizer** [comment]
@paglias exactly the same, a `=` instead of a `!=` in /views/options/social/group.jade. They were the same after all.
