### ISSUE TITLE
Sell item dialog done broke

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2567]
The text in Alexander's sell item dialog is garbled:

![temp](https://f.cloud.github.com/assets/1575692/2002577/d6238484-8600-11e3-8249-4ebef6ea7c77.png)

The lack of spaces and the extra close paren show up for any potion, egg, or food you try to sell.

**Comment by marcelosizer** [comment]
Yes, I saw that. I'm currently splitting main.json file and once it's done that will be fixed.

**Comment by deilann** [comment]
Can this be closed?

**Comment by marcelosizer** [comment]
Fixed by #2591.
