### ISSUE TITLE
Multiple "sell item" buttons appearing

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2568]
This is what I see when I click on a wolf egg, and then a pink cotton candy:

![image](https://f.cloud.github.com/assets/1575692/2002580/230493b0-8601-11e3-9eb9-9cbce7bbbfdd.png)

Clicking either button causes me to sell a wolf egg. 

The same thing happens if I click a potion and a food. Clicking a potion and an egg doesn't cause this because it brings up the hatch dialog instead. 

This report is about the double buttons; I opened a separate issue for the garbled button text.

**Comment by lefnire** [comment]
Oof. A vestige of translations @Sinza- @paglias ?

**Comment by marcelosizer** [comment]
The text error is, I'm working on splitting main.json and I'll fix that. But I can't seem to replicate that image as whenever I click on an egg and a potion at the same time it just tries to hatch it. I've even tried Wolf and Cotton Candy Pink as in the picture on my local install, as I currently don't have a Cotton Candy Pink on the website, but I don't get double buttons. 

Have you tried refreshing the page @octern ?

**Comment by octern** [comment]
@Sinza- The cottoncandypink referenced in the image is the food, not the potion.

**Comment by marcelosizer** [comment]
Ah, sorry about that. Let me see.

**Comment by marcelosizer** [comment]
@lefnire probably wasn't an issue with translations. Fixed with PR #2576.
