### ISSUE TITLE
Everything became untagged, but tag icon still present

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2569]
I tagged a bunch of items this morning, and the filter worked correctly. However, just now, the filter showed no items for the tag; I checked, and although all my previously-tagged items still have the "tag" icon, they have no tags checked.

**Comment by deilann** [comment]
I'd go ahead and check out some of the other issues tagged "tags."

This one, in particular: https://github.com/HabitRPG/habitrpg/issues/2370

But there are a few other ones that I've seen (I think they're closed at this point) that are similar. I'm pretty sure what's happening is that it's not syncing properly, so while it seems like they're tagged, they're not actually. So once things update, they're not actually tagged.

One way to test this is to do a hard refresh after tagging something. If it stays tagged, you're good.

**Comment by lorian** [comment]
Well, clearly something's syncing properly, because my now-untagged items all have the "tag" indicator, despite having no checked tags. Also, as I was choosing the "save and close" option, that indicates a definite sync bug.

**Comment by deilann** [comment]
Yeah, it's similar to the issue of checking off dailies only to come back
later and see that they weren't checked off. It's interesting that it
recognizes that tags happened.

Were you using any special characters in the tags, or were they all
alphanumeric?

**Comment by lorian** [comment]
My tags had emoji, which could be related. Ironically, I was attempting to tag things to get around the "things randomly rearrange themselves" bug; as it currently stands, I'm at a loss for how to avoid drowning in my sea of to-dos.

Edit: I just tried to re-create the bug using the same tag, and the to-do remains tagged after reload.

**Comment by deilann** [comment]
Ohhhh, I'm going to guess it's the emoji because they contain colons, which
have been reported to cause HUGE issues in tags. (I used them to do tag
subcategories and terrible things happened. TERRIBLE. I will not speak of
it.)

I'd try tagging without emoji/special characters, and see if that helps you
paddle to shore.

**Comment by lorian** [comment]
Ah, I shall try tagging the boring way and see if that works, thanks! (now I wonder if my much-earlier tag problems were due to having @ in the names...)

**Comment by deilann** [comment]
I would not be surprised. Possibly there should be a warning until it's
entirely figured out. Especially as the wiki actually _suggests_ using
emoji as tags. "Use tags with special characters at your own risk. It has
been known to cause issues." Kind of like Manual Day Start.
