### ISSUE TITLE
Following People

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#257]
Just like twitter, my friend just asked for this feature. English women FTW!

**Comment by horusofoz** [comment]
I think this sounds very interesting. I think it would have to be alloed rather than open access like Twitter. Still an new feed for user activity I think would be awesome.

**Comment by ghost** [comment]
I think people would enjoy this, add to the social aspect of habitrpg.

**Comment by horusofoz** [comment]
Discussion moved to [Sharing, Privacy Options](https://trello.com/c/pxics3ZM).
