### ISSUE TITLE
Aborting Trapper Santa Warns You'll Lose Scroll

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2573]
Thought this had been changed, but not entirely sure. Member in the Tavern states that trying to abort Trapper Santa, they're warned they will lose the scroll.

If this has been changed, then the text needs to be changed to reflect it.

**Comment by wc8** [comment]
I get the same warning with the cub scroll.

**Comment by lefnire** [comment]
Warning is outdated, you get scroll back

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/pull/2703 Fixes
