### ISSUE TITLE
Syncing account fails leading to two different account statuses

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2575]
Sorry if this is a duplicate, but anything that I can find close to this is either months old and closed or references Facebook logins which I've never used.

I usually have HabitRPG open in Safari on my desktop (Mac OS X 10.8.5) and in iOS  (7.0.4) Safari. The sync button in iOS doesn't work because it triggers a party member's stats instead but I thought reloading the page would accomplish the same thing but it doesn't seem to. Tonight I noticed that things I have checked off on the desktop are not checked off on my iPad and vice versa no matter how many times I refresh (or sync on the desktop).

My account on the desktop shows 28/50 health, 1131/1520 XP and 44/198 MP and 53 pets (which I can only hatch on the desktop).
My account on the iPad shows 40/50 health, 993 XP, and 44/198 MP and 45 pets (I hatched a bunch this afternoon).

Both my User Id and my Api Token are the same on the desktop and on the iOS browser.

Am I using the site wrong somehow or is this a bug?

**Comment by deilann** [comment]
Are you refreshing or doing a hard refresh?

**Comment by ghost** [comment]
How do you do a hard refresh in iOS Safari? If you mean clearing the website data, I did that just now and it seems to have worked but that's impractical to do every single time there's a switch between the desktop and the tablet all day long (which I guess makes the sync button not working on the iPad a bigger issue).

**Comment by deilann** [comment]
It's necessary. There's no real way around it.

Your iPad is caching info, and you need to get rid of it in order to see
the differences. I'm not sure how to do it in iOS Safari, but there should
be a way to refresh without using the cache. I'd have to look it up.

**Comment by ghost** [comment]
That's not true. Normally a simple refresh does work. In fact after clearing the website data it started working again. But this problem keeps recurring every few days so I'm not sure why it stops working at some point and requires the website data to be cleared.

**Comment by deilann** [comment]
It depends on what's in your cache and what's being pulled. If you're using
the same account on multiple devices, the truth is, you're going to need to
clear your cache upon update from time to time.

From what I've read, either shift refresh or option refresh will reload the
page without the cache.

**Comment by ghost** [comment]
Those are instructions for the desktop. iOS doesn't have an option key (and as far as I know there is no way to hit 'shift' and the refresh icon at the same time in iOS anyway). Is the sync button supposed to do a hard refresh in iOS? Because that is not working with a party member sitting underneath the menu.

**Comment by deilann** [comment]
Doing some more reading, it looks like refreshing twice in a row may clear
the cache. (Sorry, I assumed you were using a keyboard with your iPad.) I'm
not 100% sure on how sync works with the browser, so I can't help there.
But I can tell you that Safari's cache will need to be cleared if it's got
old data in it that it's using to make your pages load faster and it
doesn't know new data has been created on another device. I have this issue
when I use two laptops.

**Comment by ghost** [comment]
Well there's a work around so I guess this is closed.
