### ISSUE TITLE
Clicking on Gems Brings Up Useless Window

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#2577]
So since we decided to add the subscription plan, we got rid of the ability to just purchase gems right? (Was it intentional? I kind of hope not) Two problems:
1. The subscription is hidden away in the menus. This doesn't seem intuitive. I clicked on gems assuming to find it there. 
2. Clicking on gems pulls up this useless window that scrolls weirdly when you hover over it.

![screen shot 2014-01-26 at 2 56 03 am](https://f.cloud.github.com/assets/4434731/2003561/b1d19a34-8660-11e3-8398-f374162bb5a4.png)

**Comment by deilann** [comment]
I'm getting the perfectly normal popup. No subscription stuff, just the normal popup.

**Comment by deilann** [comment]
Oh, you must be talking about on the beta site. I assume if it's on the beta site, it's still being worked.

**Comment by DanielTheBard** [comment]
Yeah, should have clarified. I just always use the beta so I never really think about it.

**Comment by deilann** [comment]
I'd imagine that that part of the page is under works so that it contains subscription stuff. I'm pretty sure Tyler said that gems will be purchasable a la cart as well, so I think that bit just needs to be redone to show all options.

**Comment by lefnire** [comment]
Actually, thanks for catching this. Both of ya - working on it now, basic (g2G) based sub is avail on beta, I'll work on fixing this, then deploy to prod.

**Comment by deilann** [comment]
Can this be closed?

**Comment by DanielTheBard** [comment]
Yeah, @lefnire this can be closed, I think.

**Comment by deilann** [comment]
You can close it. It's your ticket. :P
