### ISSUE TITLE
"Weekly" Habits [Suggestion]

### ISSUE THREAD

**Issue by JustinThomason** [HabitRPG/habitica#258]
I've only just started using HabitRPG, but so far I love the idea of it. 

Personally I would like to see a second type of Habit - something that could be set up to be done X number of times per week. This would be a little different than mapping daily habits to individual days since they would be more nebulous.

For instance, in my life I am trying to get better about taking my lunch to work rather than buying lunch out so often. I'd love to have a habit for "Take Lunch 3 times a week" but I don't necessarily need to set up "Take Lunch" on Monday, Wednesday and Friday. 

Maybe incremental habits that build in rewards as you defeat them but that don't hurt you until the end of a predetermined time. However if you don't defeat them all before the timeframe they hurt you more for each that are undone (possibly even with an exponential element to the damage). This could potentially make the concept work for any sort of timeframe - weekly, monthly, even annually.

**Comment by StanLindsey** [comment]
Hey @JustinThomason - thanks a lot for your suggestion; you are not the first to come up with such a great idea.

Check out this Trello card and vote for it by pressing "v" on your keyboard!
https://trello.com/c/XuVokK2V

I'm going to close this for housekeeping =D
