### ISSUE TITLE
Party members who joined a quest aren't showing correctly.

### ISSUE THREAD

**Issue by TehPudding** [HabitRPG/habitica#2580]
Hello, two days ago I invited my party for the Trapper Santa quest. I checked a couple hours later and it said both members had accepted my invite, but when I started it, only one of them was in it. Is there something that could have gone wrong?

**Comment by kittyo9** [comment]
I'm the party member that was excluded from the event.  I never received an invitation to accept the quest as far as I know.  I am also the original founder of the party, and all three members of the party (myself included) were members prior to beginning the quest.

**Comment by deilann** [comment]
I'm gonna guess this was a 503 issue, where it partially saved (so it displayed that @kittyo9 accepted) but not fully (so @kittyo9 didn't get to participate). Just so you know, if this happens again, you can rebort & reinvite.  You don't actually lose the scroll (I think I've fixed the warning on that? Don't know if it's live.)

As I'm guessing this is 503 related, I'm closing it for now. But please reopen it if you have reoccurring issues.
