### ISSUE TITLE
Ambiguous phrasing in 'Buy Gems' description text on subscription info tab

### ISSUE THREAD

**Issue by marphod** [HabitRPG/habitica#2581]
The text lists a monthly "25G" conversion limit.  I assume that means a maximum of 25 Gems, but the usual reading of "25 G' would refer to gold (and converting 25 gold doesn't make much sense)..

**Comment by sleepykit** [comment]
Yeah, I kind of puzzled over that one, too. Maybe change it to "25 Gems" explicitly.

**Comment by deilann** [comment]
@lefnire Thoughts?

**Comment by lefnire** [comment]
I'm gonna do a big sweep on ui re gems and subs soon, I'll keep this in my pocket

**Comment by deilann** [comment]
thx :)
