### ISSUE TITLE
Lots of Errors

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2586]
Getting lots of errors, specifically when trying to visit the guilds tab (503s), the tavern (503s and a 404), and when dealing with checking off tasks (503s and an error that's rendering in html:

```
<!DOCTYPE html>
    <html>
    <head>
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by Alys** [comment]
Over the past 24 hours (very roughly), I also have been seeing a few 503's and one or two of the HTML errors, from the tavern, ticking off tasks, reloading the tasks page, and adding rewards. Chrome on MacOS, not that that's likely to be relevant.

EDIT: There's also occasionally an issue where an emoji displays as only blank space.

**Comment by deilann** [comment]
Still getting the html error, from time to time.

**Comment by lorian** [comment]
After several of both the 503's and the html errors, I actually got the entire task page replaced with an "Application Error" for several minutes earlier today; when it finally came back, I had lost my most recent action.

**Comment by colegleason** [comment]
Please follow #2554
