### ISSUE TITLE
Got kicked out of party, trapper santa quest disappeared.

### ISSUE THREAD

**Issue by EricLyHealth** [HabitRPG/habitica#2587]
Got kicked out of party, trapper santa quest disappeared. What can I do? Seems to coincide with all of the errors people are getting today.

**Comment by marcelosizer** [comment]
That's the expected behavior. If you leave a party or get kicked from it you will be booted from the quest as well. Did you start the quest?

**Comment by colegleason** [comment]
I don't think it was an intended kick.

On Tue, Feb 4, 2014 at 4:18 AM, Marcelo Sizer notifications@github.comwrote:

> That's the expected behavior. If you leave a party or get kicked from it
> you will be booted from the quest as well. Did you start the quest?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2587#issuecomment-34046227
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by deilann** [comment]
Hey @EricLyHealth can you confirm what happened for us?

**Comment by EricLyHealth** [comment]
Okay so it magically fixed itself 12 hrs later, as in the very next day I was somehow back in the party doing the quest again. 

FYI: I was not intentionally kicked out nor did I leave the party.

**Comment by EricLyHealth** [comment]
I'll be closing this since it seems to just happen once in a while but it fixes itself if I just wait it out.

**Comment by deilann** [comment]
It's likely not that you're not in a party -- it's likely that the party
page isn't fully loading. The "Create a Party" page loads first and then it
fetches your party on top of it. Sometimes, it can take a bit for that to
be fetched. Try refreshing next time.
