### ISSUE TITLE
Lost two leves, all of inventory

### ISSUE THREAD

**Issue by JackalopeApocalypse** [HabitRPG/habitica#2588]
Heyyo!

So, I just went up a level (4! Hurray! Woo!) bought a Yeti-Tamer shield and found a Wolf egg. Things were good.

I just reloaded the page to discover a message saying I had died (the damage taken from dailies I didn't complete did not add up to the 50 HP I had inexplicably lost), gone down two levels and lost everything in my inventory. Things are very sad. Please help.

**Comment by lefnire** [comment]
follow progress on https://github.com/HabitRPG/habitrpg/issues/2601 , part of an overall milestone for recent instability. restore lost progress in the mean time at Options > Setting > Restore Character Values
