### ISSUE TITLE
Can't add user to party although he isn't part of one

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2589]
Hi,

adding the user 4224e25f-0f6d-4485-83a7-535bb84f0f64 to group 42acc4d2-e74c-4695-b582-544814834bdd doesn't seem to work. I get an "Error 400: User already in a party.", although the user assures me that he isn't part of one. Inviting other users to the party worked though.

Could you please help resolving this?

**Comment by deilann** [comment]
@rckn Are you still having this issue?

He may be in a party by himself, in which case he needs to leave that party.

If he's definitely not in any type of party at all, please let me know.

**Comment by Alys** [comment]
closed from lack of response
