### ISSUE TITLE
Categories Idea

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#259]
Now i know there are a lot of suggestions for Categories and Tags but I just want to pitch an idea about how I would do it

Basically, I want to make the the columns customizable
You would be able to add new columns and delete columns
Each column would have an edit button (like habits do)
- You can rename the column
- You can chose the type of column, (Habit, Daily, Todo, Rewards, [and skills if you decide to implement my skills idea])
  The ability to drag and drop between different columns

Obviously if you have more than 4 columns you will need a scroll bar to go side to side
You could make the mouse wheel scroll side to side for easy navigation like in windows 8

any suggestions people, if something sounds good ill edit it into this post

**Comment by StanLindsey** [comment]
Hi @Nelmalih0 - Check out this suggestion on Trello which covers a lot of what you suggest. I've added this thread through to that card as you bring up some interesting points yourself. 
https://trello.com/c/q7v02jAw

Thanks for the suggestions though, we love the fact that people are enjoying HabitRPG enough to come on here with suggestion ideas. 

I'm going to close this issue though for housekeeping, keep up the conversation over on Trello.
