### ISSUE TITLE
Incorrect character display

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#2590]
Hi everyone,

Something is wrong in the display of my character :

![images](https://f.cloud.github.com/assets/4418868/2007057/54dc92cc-8730-11e3-9673-b2a1b3141f06.jpeg)

You can see the upper part of a pet (I think it's the contrib pet). Even if I choose a pet, it still appears :
![images](https://f.cloud.github.com/assets/4418868/2007076/e5eb4f88-8730-11e3-8632-0d70ac5c4a73.jpeg)

On a mount :
![images](https://f.cloud.github.com/assets/4418868/2007070/b7f6159a-8730-11e3-9783-186ff7b6c84b.jpeg)

**Comment by colegleason** [comment]
Please follow at #2594, as these seem to be similar.
