### ISSUE TITLE
LICENSE contains conflicting terms

### ISSUE THREAD

**Issue by pafcu** [HabitRPG/habitica#2596]
The LICENCE file states that code is under the GPL v3. However, it also states that you are not allowed to run the code for commercial purposes:

> You can deploy the code on your own servers; however, you cannot use your own deployed instances for commercial purposes.

However, this conflicts with GPL v3. From the GNU GPL FAQ (https://www.gnu.org/licenses/gpl-faq.html#NoMilitary):

> I'd like to license my code under the GPL, but I'd also like to make it clear that it can't be used for military and/or commercial uses. Can I do this?
> No, because those two goals contradict each other. The GNU GPL is designed specifically to prevent the addition of further restrictions. GPLv3 allows a very limited set of them, in section 7, but any other added restriction can be removed by the user.

Thus, according to the GPL, a user is free to remove the restriction on commercial use, which makes it unnecessary to have the restriction there in the first place, as it merely serves to confuse users about their rights under the GPL.

**Comment by lefnire** [comment]
@pafcu totally forgot about that clause. I added that way back before I understood OS (and "don't mess with the license"), the above commit removes the clause and simply references GPL v3 by URL (as done here https://github.com/browserquest/BrowserQuest/blob/master/LICENSE) 

It should be noted, the assets designed for Habit have been copyright-assigned by the permission of the artists under CC-BY-NC-SA, so if someone wants to use Habit for commercial use they'll still need to redesign the assets, or request permission from Habit. 

@lemoness, any corrections you'd make?
