### ISSUE TITLE
Backstab not leveling up

### ISSUE THREAD

**Issue by rtdeacha** [HabitRPG/habitica#2598]
Hi I used backstab on two of my dailies, after receiving XP for both, my XP bar is full and the total XP earned is calculated properly, but I'm not leveling up till I perform another task.

![image](https://f.cloud.github.com/assets/5741041/2011408/8587dd74-877a-11e3-9cce-adb263a0867b.png)

I know is no biggie, just wanted to give you a heads up...

![image](https://f.cloud.github.com/assets/5741041/2011541/126a7ef8-877c-11e3-864b-245f7fcb0cdd.png)

Regards
Rick

**Comment by marcelosizer** [comment]
Related to #2143 #2137 and #1996.

**Comment by rtdeacha** [comment]
Thanks for linking this to other issues Sinza.

I wasn't able to find any issue regarding the backstab, but it seems that it happens with other spells as well. 

Regards
Rick

**Comment by deilann** [comment]
Let's just follow this at https://github.com/HabitRPG/habitrpg/issues/2143
