### ISSUE TITLE
Overlapping buffs not always working

### ISSUE THREAD

**Issue by pipcorona** [HabitRPG/habitica#2599]
I cast Tools of the Trade on my party of three including me. I had a perfect day the day before so my buffs to all attributes were 8. After casting tools of the trade my perception went up to 10. One of my party members who did not have a perfect day got the buff of 2 to perception. My other party member who did have a perfect day had a buff of 5 to all attributes and after casting TotT did not receive the buff of 2 to perception. Might there be an issue with buffs from party members not overlapping properly with other buffs?

**Comment by colegleason** [comment]
I think this problem may have to do with the way perfect day is calculated in cron? Not sure.

**Comment by Alys** [comment]
Closing because skills have been modified since this was logged.
