### ISSUE TITLE
non 24-hour days

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#26]
HabitRPG looks interesting and I was going to try it out, but then I realized that its tied to the 24 hour day cycle. I have a sleep disorder where my days last longer, about 25 hours, and thus my "day", in relation to Earth's, slowly travels around the clock such that I'm sometimes awake at night and sleeping during the day.

Of course, I'm an exception, but it would be nice to have an app like HabitRPG which was not tied to real time per se, but was more like turn-based. Do you have any comments in this regard, either concrete or conceptual

**Comment by lefnire** [comment]
Hmm, that might be kinda difficult. Are there any other apps you use which accomodate for this? Or, can you configure your system clock to work on a 25-hour day? I'm wondering if there's something on your system I can piggy-back on in JavaScript for such a feature. Habit doesn't currently say "if it's been 24 hours, run cron" - instead it says "if the last time cron was run was before today, run cron" - so if there's a operating system time configuration that's exposed to your browser, it should work automatically.

**Comment by Core-Xii** [comment]
No, I don't use any apps tied to the 24-hour cycle and I'm aware of no system or configuration that accommodates otherwise. My system, calendar, etc. run on the default cycle, but there's nothing that triggers specifically "daily" or expects me to conform to 24 hours.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
@Core-Xii would a manual day start, such as one idea on [Record Yesterday's Activity](https://trello.com/c/CaAm7APS) address this?

**Comment by Core-Xii** [comment]
I can't access the Trello link.

Manual day start should address it, as long as no part expects a day to last 24 hours at maximum, and the whole doesn't rely on the calendar (like, care which day it is, other than as an incrementing count).
