### ISSUE TITLE
MP awarded for stats allocation (again)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2602]
I just changed classes and allocated my attribute points. To my surprise I gained 1 MP for every point allocated! (I got the popup notifications and the points were added to my mana since it doubled from allocating points). This was a bug that was previously resolved but it seems to have reappeared (I'm assuming this is not intended behaviour).

**Comment by colegleason** [comment]
Offending line: https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L718

**Comment by colegleason** [comment]
What is intended behavior here? Give 1 MP per point allocated but take away 1 MP when you unallocate (change classes)?

**Comment by colegleason** [comment]
Maybe we can just set `stats.mp` to `user._statsComputed.maxMP` here?
https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L699

**Comment by ghost** [comment]
¾ fixed: INT points allocation still generates MP.

**Comment by marcelosizer** [comment]
I believe this is intended as when you add 1 INT you get 1 max MP, so it gives you that point.

**Comment by deilann** [comment]
I wouldn't want to lose a bunch of MP when I changed classes. Chances are, all the allocated point MP was a long time ago over a long period... It seems ridiculous to drain my MP, especially if I'm switching to a non-INT class.

**Comment by colegleason** [comment]
@deilann But should you have more MP than the max?

**Comment by deilann** [comment]
More MP than max? No. Have logic so that if you have more MP than max, it gives you full MP. But the logic of "remove 1 MP whenever an INT point is deallocated"? Not cool with that.

**Comment by Alys** [comment]
I think the way MP is handled now is working well, even though you can have MP > max and keep adding to it by assigning points to INT. The MP that you had before you started assigning points is likely to have been earned legitimately, and there are valid reasons for having MP > max (e.g., you've just changed class away from Mage your high-INT gear has been deequipped). I don't think that earned MP should be removed, even when you're adding to it by increasing INT points.

MP > max will disappear as soon as you tick off a To-Do or go through cron, so there's already some processes in place to prevent MP > max lasting for too long. I don't think we need more.

See also the discussion here about excess MP: https://github.com/HabitRPG/habitrpg/pull/3662

**Comment by ghost** [comment]
I'm still unclear as to why allocating INT points generates MP which was my original issue. Maybe that was explained and I missed it but this seems to have gone off in an unrelated tangent.

**Comment by Alys** [comment]
That's just one of the features related to Mana and INT. It's documented in the wiki's [Mana Points](http://habitrpg.wikia.com/wiki/Mana_Points) page.

**Comment by Alys** [comment]
I'd like to suggest that this be closed. The original report describes expected and intended behaviour (you're supposed to get mana when you increase INT), and there are already processes in place to deal with MP > max, and I don't think we should be removing MP that players have earned or obtained from previous attribute point assignments.

Happy to hear dissenting viewpoints though!

**Comment by ghost** [comment]
Correction: The original report was for MP being awarded for ALL points, not just INT, which has been fixed. I still find the remaining behaviour odd (I don't see why you should get MP for allocating INT), but if that is intended then close it.
