### ISSUE TITLE
too many XP points awarded upon refreshing page

### ISSUE THREAD

**Issue by cferreira08** [HabitRPG/habitica#2603]
Hi, I think there's been some type of mistake with my account leveling up. I had just finished checking off items on my to-dos and habits and was at around 690/800 at level 35. Then, I realized that my computer was in off-line mode (my laptop's connected to ethernet) and refreshed the page. Suddenly, I had leveled up to level 36. I checked my completed tasks, and only one was doubled (as in one of my completed tasks had been duplicated and both were marked as complete). I unchecked one of the doubled tasks and deleted it.

Um, not really sure what else to do. Just wanted to figure out what went wrong, if possible, how to correct the issue, and if not, how to prevent "fake" leveling up from happening in the future. I assume it was connected to refreshing the page after plugging in the ethernet, but I have refreshed Habit before without this happening.

Thanks,
Carla

**Comment by cferreira08** [comment]
An update: in addition to the one to-do that was doubled, there was also a habit (which was green) that was doubled.

**Comment by cferreira08** [comment]
This has again happened today. I was refreshing the page to see the amount of mana points I would have since it was past midnight and then, I leveled up. Again, there have been several times where refreshing does not make this occur.

**Comment by crabbadon** [comment]
I had a similar issue with 'fake' XP. Last night I had used healing brightness multiple times to soften a really bad day on the to-dos, which may be relevant; when I synced after turning my computer back on from hibernation I was awarded about 250XP and 100 gold.

**Comment by deilann** [comment]
Issue with the Drag'on quest triggering completed early. Check Tavern for
more info.

**Comment by lefnire** [comment]
#3712
