### ISSUE TITLE
cannot log in to iOS app

### ISSUE THREAD

**Issue by meganstrickland** [HabitRPG/habitica#2604]
Posting for Imamadmad, copied from Wikia Q&A forum page http://habitrpg.wikia.com/wiki/Thread:5846

OK, so I've found a bug in the iOS app version of this thing which I have only just downloaded after having a friend recommend it to me a few hours ago. However, I can't find any email address to send a bug report to, and I don't have a Github account to lodge the bug report there, so I'm just going to outline my problem here in the hopes somebody will either see my message and will be able to fix the problem or will be able to send me to a place where I can seek help.

So basically, I've just downloaded the iOS app for the first time, and it opens up on the login screen, just as one would expect. Now, I already signed up for an account on my computer before trying to download the app, so I went to press the username field in the login form. As one would expect, the keyboard popped up to let me type in my username. As one wouldn't expect, the "Login with Facebook or API Token" box flies to the top part of the screen above the username field, and brings the bottom of the page with it, obscuring the login form with white blankness. I tried typing in my username anyway, in case the username field was still active under the blankness, but when I clicked away so the keyboard disappeared, the form was still completely blank. I tried repeating this process a few times with both the username and password boxes, every time with the same result. I've even tried closing the app and reopening it after doing the double home button click thing to make sure it was completely closed. I'm using an iPhone 4 with iOS 7. Can anyone else replicate this problem, and/or have a solution, and/or could point me to a place where I could find one? I can produce screenshots if needed.

**Comment by colleenrose** [comment]
I'm having the same problem trying to use the iOS app.

**Comment by philbetts** [comment]
I'm also having the same problem with my iPhone 4 and iOs7.

**Comment by Sprachprofi** [comment]
Also having the same problem. My boyfriend is an iPhone developer and says it's related to screen size: the iPhone 5 is taller, so there it's possible to still see the textfields despite that weird grey box.

Temporary workaround: tap on the user name field. Use the > button at the top of the on-screen keyboard in order to jump to the next textfield. The cursor is now in the password field and the grey box is gone. Use the < button in order to jump back to the user name field and TADA you can enter something.

Still annoying as hell and I haven't been able to actually log because I created an account through Facebook and the Facebook login is way too complicated. Kicking myself now that I didn't use the regular registration...

**Comment by translunar** [comment]
I'm having a very similar problem. However, I've actually managed to input my API token and UUID and such. Unfortunately, the Login button does not work.

I can push Sign-up, but not Login. Neither button gives any kind of feedback that it's been pressed, but Sign-up does take me to a sign-up screen.

I gather these are all parts of the same bug.

**Comment by deilann** [comment]
Have you tried rebooting your phone? That has worked for some people in the
past.

(Also, I highly suggest visiting the website on your phone, and
copy/pasting your API token and UUID rather than manually typing them.)

**Comment by deilann** [comment]
@Sprachprofi As a facebook account, you should still have a UUID/API token -- that's what you have to log in with anyway. (Username/password doesn't actually work currently.)

**Comment by translunar** [comment]
Ahh, yes. As soon as I rebooted, it accepted the API token and UUID I had entered previously. Odd, because I didn't even have to enter it this time. Thanks!

**Comment by Alys** [comment]
I'm closing this because the login system has changed since it was reported and many of the comments above are now irrelevant. If anyone is still having trouble logging in on the iOS mobile app, comment on https://github.com/HabitRPG/habitrpg/issues/5561
