### ISSUE TITLE
Can't damage Trapper Santa

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2607]
Despite completing Dailies and To-dos, https://habitrpg.com/#/options/groups/party doesn't show any changes (either in the boss HP bar or the chat log).
My User ID is dfba70b0-4b31-443f-928f-3bae5a200376

Any help would be greatly appreciated, as I'd love to get started on the follow-up quest before it disappears!  Thanks!

**Comment by deilann** [comment]
Just wanted to let you know that you can purchase Find the Cub before you finish Trapper Santa.

How many days has this been going on?

**Comment by Caspid** [comment]
Does the chat log reflect my actions as well?  If so, I don't believe I've ever damaged him (two weeks), despite being part of the quest.

**Comment by deilann** [comment]
The chat log should update shortly after cron every day, saying how much
damage you dealt.

**Comment by Caspid** [comment]
Ah, that must've been the problem then.
I see "All damage to and from a boss is tallied on cron (your day roll-over)" now.
Sorry for the trouble, and thanks for your help.

**Comment by Caspid** [comment]
Hm, so cron has definitely past, and I completed Dailies and To-Dos yesterday, but Trapper Santa still shows the same amount of HP and my actions aren't recorded in the chat log.

**Comment by Caspid** [comment]
Today, I don't see updates from me or my party members.
(he was at 205 HP yesterday, and is still at 205 again today; no damage is recorded in the chat log from last night.)

**Comment by marcelosizer** [comment]
Have you tried refreshing the page?

**Comment by Caspid** [comment]
Yeah, I have. 
As soon as my party member logged in though, it said we completed the quest.
I guess this is resolved.
