### ISSUE TITLE
Copyright information is not easily found

### ISSUE THREAD

**Issue by pafcu** [HabitRPG/habitica#2609]
I didn't manage to find any copyright information (i.e. who has the copyright) to the source code or the art. It would probably make sense to have it at least in the LICENSE file. This is especially problematic for the artwork since it requires attribution, yet it's difficult to figure out who to attribute.

**Comment by lefnire** [comment]
There are [two assets copyright holders]((https://github.com/HabitRPG/habitrpg/blob/develop/LICENSE):
- [BrowserQuest](https://github.com/mozilla/BrowserQuest) for any assets created for the BQ project
- HabitRPG for assets created for this project. Assets added to our project beyond BQ have been copyright-assigned to HabitRPG by the permission of their creators. That means we are the entity you're seeking. For attribution, you'll want to attribute BQ & HabitRPG. For commercial use of art assets, please contact us [here](mailto:admin@habitrpg.com)
