### ISSUE TITLE
[suggestion] Clickable links in descriptions

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#261]
A thing I just noticed while pasting a link into a description, it cannot be clicked. I guess this would be really nice to have :) Iḿ for example using this for papers I have to read at a later point. It would be even nicer if I could upload the file, but a link would be helpful already! Maybe at some point there could be something like google drive, dropbox, box.net etc integration so we can easily add files without taking your server space.

**Comment by wc8** [comment]
Yes. You're referring to the notes area, correct?

**Comment by Pandoro** [comment]
Exactly. It came very spontaneously, I didn't check if such a suggestion has been made already. In that case, please delete/close this post and ignore it :x

**Comment by wc8** [comment]
I didn't find it on Trello yet, so I added it: [Links in Notes](https://trello.com/c/0oQBQW6W).

**Comment by StanLindsey** [comment]
Closed as on Trello - thanks for the suggestion =D
