### ISSUE TITLE
Quest progress not applied to quest (damage not registering for one/multiple party members)

### ISSUE THREAD

**Issue by poopstick** [HabitRPG/habitica#2613]
Okay, so for the last five days, my dailies and to-dos haven't been affecting this quest. They're not appearing on the chat list any more (last one is from 5 days ago), and Trapper Santa's health is stuck at 9, which is very frustrating.

I thought it might have to do with me having set a custom cron time, so I reset it to 0:00.

Then, I thought it might have had something to do with having HabitRPG open on two PCs with different time zones (I'm travelling right now), but I killed the HabitRPG window on the second PC two days ago and have seen no change.

Would really like some help before this quest expires.

Thanks in advance!
##

**Comment by deilann** [comment]
Don't worry -- the quest isn't going to expire. You just won't be able to purchase the scroll any more.

You might want to post your UUID so better investigation can happen.

**Comment by poopstick** [comment]
Good idea.

Group ID: a0204c4e-38c9-4f54-bcbf-f8a80cee3a4e

User ID: 290d7cc7-9824-4f83-8bed-e8b6766fab24

Thanks!

**Comment by deilann** [comment]
Did this ever resolve itself? Are you still in Santa limbo?

**Comment by poopstick** [comment]
Indeed. Santa's still got 9 hitpoints left. No damage has been inflicted in 19 days. Tasks seem to be rolling over and buffs are appearing in the chat area, but no further interaction with Trapper Santa.

**Comment by deilann** [comment]
I'm wondering if you didn't kill Santa, but a 503 screwed it up. I really hate to say this, but your best bet is probably aborting the quest, and restarting it. (Don't worry, you won't actually lose the scroll. Not sure if my fix about that warning is live yet.)

**Comment by poopstick** [comment]
Tried that just now. I did lose the scroll, it seems. Unless I'm just looking in the wrong place? Social -> party and inventory.

**Comment by deilann** [comment]
You really shouldn't have lost the scroll. Go to your inventory (Market)
and refresh. If it's still not there, let me know.

**Comment by poopstick** [comment]
Still not there after a refresh. Only seeing the Dragon's Influence one.

**Comment by deilann** [comment]
Kk; I'm definitely guessing that you did actually "complete" the quest
then, just not actually saved to the server in that case. So it's basically
thinking "but you beat that quest. you can't have the scroll back!"

@lefnire can we get @poopstick another Trapper Santa scroll? Or run a
script saying the quest was beaten?

**Comment by poopstick** [comment]
So, Trapper Santa came back, and my other party member must have clicked it. If he aborts, is it possible for both of us to join it again?

**Comment by deilann** [comment]
@ironrhino12 That's definitely #2657 

@poopstick It should be, yes.

**Comment by poopstick** [comment]
@deilann Hm. Other party member aborted and started the griffin quest because it was the only one that showed up. Any chance of getting the trapper Santa quest back so we can complete it?

**Comment by deilann** [comment]
I can't grant scrolls that are no longer purchasable, unfortunately. @lefnire?

**Comment by lefnire** [comment]
@poopstick i just gave you trapper & cub scrolls, see if that's good

**Comment by poopstick** [comment]
I see them. Thank you very much!

**Comment by lemoness** [comment]
Quick check - if you are in the inn, does your damage not go through because you don't have cron? I just failed to deal any damage to a boss - didn't even show up - but my teammate is also in the inn and he DID deal damage.

**Comment by deilann** [comment]
Yeah, afaik, if you don't have cron, you shouldn't deal damage. Are you
sure he didn't go into the inn after cron?

**Comment by lemoness** [comment]
He must've :/ Darn, I saw him deal damage and thought, "Oh cool, I will
too!" Thanks for the clarification.

**Comment by ironrhino12** [comment]
the #2657 I've thought I've been having is definitely a #2613. my Party continues to do damage, and when I log on (first thing in the am) I can see it, but then it resets to the "multiverse" that is my bug... and I am stuck in that purgatory for the rest of the day. Also it seems to be reoccurring ever 15 days or so.
We are currently fighting the dragon's shade, but i see trapper santa.

UID: 5ab3ee1e-a9fc-4d76-95e1-7f02ee8068af
Party ID: af41792d-582b-4053-8dfe-aa2548138bcc

**Comment by Alys** [comment]
Habitica's code has recently undergone large changes, which means that the code that caused these bugs probably does not exist any more. I'm closing this, but if you notice the same problem happening again, please open a new issue.
