### ISSUE TITLE
Lost all my progress and lists after changing password

### ISSUE THREAD

**Issue by AndrewSchwarz** [HabitRPG/habitica#2614]
I tried logging in using Firefox on a Mac this morning and I got a "invalid password" message. I am pretty sure I was not putting the wrong password though. I clicked on "Forgot Password" and a new one got sent to my email account. When I logged in with that new one I found out I had lost all my progress and my to-do, dailies, habits and rewards lists where at default like when you open your account for the first time. 
This is not dire since I was a level 1 character with just 18 gold and 107 exp., but it worries me that this might happen again when I am more leveled up and actually be a serious problem. 
I can still see my "old" stats and lists in the iphone app, though. 
I don't know what else I can say to have this be a helpful bug report. I'm using firefox 26.0 for Mac, and Google Chrome indistinctly.

**Comment by wc8** [comment]
Is it possibly a browser issue, since you say you can see them in the phone? Have you tried refreshing your browser and/or closing and reopening it?
If you can see it in your phone, it sounds like the data is not really lost, it's just a display issue.

**Comment by AndrewSchwarz** [comment]
I logged out and in with my phone and the old data has definitively disappeared. Now I can only see the new default one. Also if i log in with other browsers/computers my old data still doesn't show up. Just the default one.

**Comment by lefnire** [comment]
Double check you're not registered with Facebook
http://habitrpg.wikia.com/wiki/FAQ#Username_and_email_not_recognized

**Comment by AndrewSchwarz** [comment]
Double-checked. I don't use Facebook. I registered through email.

**Comment by lefnire** [comment]
Can you provide me with a very specific (caps included) task name I can search your user by? If sensitive, send to tyler@habitrpg.com

**Comment by AndrewSchwarz** [comment]
Not particularly sensitive, but I replied to the email address. :)

**Comment by lefnire** [comment]
Very interesting! You ended up with two accounts with the same credentials
for some reason! Do this for me. Log in and check your UUID. One of these
is bad, and one is good:

c8aaebad-26d9-447e-9a7b-27f169b53d68
8aff44dd-fd93-474d-af1b-00ec2c8b7a63

When you log in, give me the UUID and tell me which you see - your normal
account, or your blank character

**Comment by AndrewSchwarz** [comment]
If I sign in using any browser or computer I get my old BLANK account, with number
8aff44dd-fd93-474d-af1b-00ec2c8b7a63

However if I type http://habitrpg.com in my firefox browser on my computer it automatically grants me access to my normal account, the one I am currently using. WIth number
c8aaebad-26d9-447e-9a7b-27f169b53d68. 

This last one is the one I have been using lately. 
This is so weird! haha

**Comment by lefnire** [comment]
Ok great, give that a shot - you should only see the correct account now

**Comment by AndrewSchwarz** [comment]
Yeap! Now I only see the correct account. Thanks!

**Comment by lefnire** [comment]
@AndrewSchwarz √

**Comment by TwoKillerMockingbirds** [comment]
Hello! I have run across the same problem on my account. I had previously only accessed y account via my tablet's browser. I had needed to rest my password, so I did so. I used the new password to log into the browser on my computer. I found my account had been completely reset. Considering it an issue with using the new browser, I promptly logged out and returned to my tablet. It would not allow me to reset the password within the still-accurate browser tab I had open, so I logged out and logged back in using the reset code. Low and behold, that account appeared to be reset as well.

I registered by email, not by facebook, and I can send you a specific task if you need.

The user ID for the blank account is:d42b898e-c2b5-41ed-9f2f-9c34927bfe8f

**Comment by deilann** [comment]
Delete the duplicate account and you should be fine.

**Comment by TwoKillerMockingbirds** [comment]
Alright- I use the option under site settings, correct?

And, when I delete the duplicate account, will the password I received in the reset email log me into the proper account?

-----Original Message-----

**Comment by deilann** [comment]
Yes. I cannot assure you of the second though as there is a chance
something else is going on, but there's a good chance it will work.

**Comment by TwoKillerMockingbirds** [comment]
Thank you! For any looking at this thread at a later point:

I deleted the duplicate account, and attempted to log back in using the previous reset password. This password did not work.

I requested another reset password, which logged me into the proper account.

Thanks very much!

-----Original Message-----
