### ISSUE TITLE
Link to about page broken

### ISSUE THREAD

**Issue by Sjlver** [HabitRPG/habitica#2615]
At the bottom of https://habitrpg.com/, there is a link to "About" in the "Company" list, pointing to https://habitrpg.com/static/about . That page gives an access denied error.

**Comment by deilann** [comment]
The landing page and static pages are under major revamp. That page is going to be a completely different page and going to be linked to from elsewhere.

**Comment by quin-jay** [comment]
This looks to be fixed now! Close?

**Comment by deilann** [comment]
Yes! That page exists now. Thank you for pointing it out @lynnyliz !

**Comment by quin-jay** [comment]
I may not be able to contribute much with code, but trawling old tickets is something I can definitely do! (and apologies if I ever end up spamming your inbox with a bunch at a time, @deilann!)

**Comment by deilann** [comment]
Oh, don't worry about it. I recently closed ~200 tickets in two spurts.
Inbox flood!
