### ISSUE TITLE
The white dragon has red eyes

### ISSUE THREAD

**Issue by adacable** [HabitRPG/habitica#2617]
They should be [blue](http://yugioh.wikia.com/wiki/Blue-Eyes_White_Dragon) . 

I'd add a commit to fix this, but the sprites seem to be closed source?

**Comment by lefnire** [comment]
Not closed source, see habitrpg/habitrpg-shared (separate repo)

**Comment by deilann** [comment]
I understand wanting to have Blue Eyes, but all of the white pets have red eyes because they're albino. Maybe wander over to Trello to discuss it?

**Comment by Natanji** [comment]
HabitRPG has nothing to do with Yu-Gi-Oh! so can someone please close this as invalid?

**Comment by DanielTheBard** [comment]
I'll admit. I laughed in disbelief. This should be closed, though. Since there's no real reason to change the color away from the albino theme.

**Comment by lefnire** [comment]
sorry @drcable, hope didn't seem like a bully-barrage! kinda felt bad

**Comment by adacable** [comment]
On 30/01/2014 23:38, Tyler Renelle wrote:

> sorry @drcable, hope didn't seem like a bully-barrage! kinda felt
> bad
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/HabitRPG/habitrpg/issues/2617#issuecomment-33747462
> 
> NP. Was at least 50% humerous to start with :)

## 

---

T. Walpole, Maker
drcable.org @drcabl3 drcabl3.tumblr.com
