### ISSUE TITLE
Automatically lint JSON

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2618]
It would be nice to automatically lint JSON files on commit for translations and such. This would ensure it's correct and there aren't duplicate keys, etc.

@paglias @Sinza

**Comment by paglias** [comment]
Definitively! Do you know any node library for doing that? I use [JSONLint](http://jsonlint.com/) but it's only on the web.

We could just require() all the files inside a try-catch and see if they are loaded correctly
