### ISSUE TITLE
Gear disappearing from inventory

### ISSUE THREAD

**Issue by Bokononist** [HabitRPG/habitica#2619]
I recently got to level 10 (YEAHH!) and was able to purchase my first Rogue Winter piece a few days back (The ski-ssasin Parka). I've been playing/leveling regularly, so I haven't died  since then. Today I logged in, after buying another piece of the ski-ssasin set and I went to equip it. I then noticed the parka wasn't in my inventory. I went and checked my stats...it was showing as equipped so I assumed it was just an update bug. I equipped the warrior chest piece to see if that would fix it... and now the Parka is completely gone, no stats for it and not in my inventory.

**Comment by deilann** [comment]
I can't help you with this, but can you post your UUID, so the folks who can, can investigate?

**Comment by deilann** [comment]
This is probably related to: https://github.com/HabitRPG/habitrpg/issues/2554
