### ISSUE TITLE
Crystal Blade contrib sword has sprite glitch

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#2620]
When the Crystal Blade contributor sword is used, you can see part of another item of equipment at the bottom of the image. http://i.imgur.com/m1r3Upm.png shows the avatar with and without the sword.

This is very low priority of course.

**Comment by deilann** [comment]
There's actually something wrong. This is happening all over. Need to lump these all together.

**Comment by Alys** [comment]
Would it help if someone tested every piece of equipment and reported on all the ones that are wrong? If so, I can do almost all of that. I have all the purchasable specials and maximum normal gear in all classes (and I'd check that before testing to make sure).

**Comment by deilann** [comment]
I think it's less the pieces of equipment, and more how the spritesheet is
spaced and the sprites are rendering, but @lefnire would have to speak to
that.

**Comment by lefnire** [comment]
No, it's a grunt spritesmith setting that needs to be updated, all or most
sprites are affected. There's already a ticket for this, but I'm on mobile
and can't look up

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2594

**Comment by colegleason** [comment]
Please follow this at #2594
