### ISSUE TITLE
Cannot Make Bailey Go Away

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2621]
GUYS BAILEY IS STALKING ME.

I went to "Show Bailey" because I wanted to look over the old announcements. But now there's no way to dismiss her. So now Bailey is watching me. All the time. And I'm super uncomfortable with this.

**Comment by paglias** [comment]
Dismiss this alert doesn't work?

**Comment by deilann** [comment]
There is no Dismiss this Alert.

On Tue, Jan 28, 2014 at 12:39 PM, Matteo Pagliazzi <notifications@github.com

**Comment by deilann** [comment]
![screenshot from 2014-01-28 12 41 43](https://f.cloud.github.com/assets/6274734/2023541/2b372eb8-885d-11e3-9061-700e80666081.png)

As you can see from the screen shot, I need to make lemon bars.

...and restart my computer. And clean out my inbox.

**Comment by paglias** [comment]
It seems hidden, scrolling to the bottom of the modal doesn't show it? It seems the screen is too short

**Comment by deilann** [comment]
Oh, I know what it is. I'm having bad vision tiems and my screen is zoomed in order to make the text legible.

I should be able to zoom out to dismiss it, but there are a lot of modals that need to resize based on screen zoom that don't (break the site on lower resolutions such as tablets).
