### ISSUE TITLE
add additional tags for changelog generation (interface)

### ISSUE THREAD

**Issue by snicker** [HabitRPG/habitica#2622]
As we are presently conforming to AngularJS guidelines for commit messages, there are a few that are lacking for this particular application.

interface: for user interface changes
translation: for localization

comment to add more

**Comment by snicker** [comment]
Well, I'll suggest "localization" as a tag for localization tasks such as translations... that @snicker guy is an idiot sometimes

**Comment by colegleason** [comment]
i18n ;-)

jk, thats confusing

On Tue, Jan 28, 2014 at 3:43 PM, snicker notifications@github.com wrote:

> Well, I'll suggest "localization" as a tag for localization tasks such as
> translations... that @snicker https://github.com/snicker guy is an
> idiot sometimes
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2622#issuecomment-33529984
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
l10n or i18n are pretty common know, not a bad fit IMO. But I'm down for
any, paglias and sinza have been the primary contribs there so whichever
they think.
