### ISSUE TITLE
Enable Intra-Party Gift-Giving

### ISSUE THREAD

**Issue by PaulRosenfield** [HabitRPG/habitica#2623]
Two of my party members just died after a botched boss battle, and one of them was really close to being able to buy his complete winter armor set. He was really disappointed, and I thought to myself, "I have PLENTY of gold to spare! Why don't I just give him some of mine?"

Then I realized that I couldn't because Habit hasn't implemented a feature like that. Here are what I consider to be the pro's and cons of such a feature:

POSSIBLE BENEFITS:
1.) If you are in a party, your gold is always useful, even if you already have everything you want.

2.) It helps cement relationships in the real world by enabling virtual generosity.

3.) It can help to soften the disappointment of dying without actually removing any of the penalties. (I would like to have been able to do this for my friend.)

4.) two or more teammates could work together to advance a joint goal, for example, buy all of the winter gear, survive a boss battle by buying each other healing potions when no one in the party is a healer, or exchange potions and eggs to help them get the beastmaster achievement. This opens up a whole new, collaborative dimension to gameplay, which could be powerfully motivating.

POSSIBLE DISADVANTAGES:
1.) At the moment, gold, items, and experience all represent something achieved by the player. Gold given as a gift would not. This could lessen the connection between hard work and pay-off.

2.) Could create weird social pressure to give gifts if asked or accept gifts if offered.

3.) It might open the door for the kind of hacking seen in other online games (where someone hacks into someone else's account, and then uses the trading option to transfer all of a person's stuff into their own account). Honestly, I don't think this would be a serious problem on Habit.

QUESTIONS:
1.) What should be tradable? Only gold? Or also rewards and drops like eggs, potions, and purchasables?

2.) Should there be limits on how much trading can be done? I tend to think so. Maybe you could put a limit on the number of gold and or items in a single gift and then charge one gem to the gift giver and the gift receiver for each gift. I tend to think this would lessen the disadvantages, and increase the benefit of having a premium account (if that enables you to convert gold into gems). Plus, this approach would create a 5th benefit for Habit: another source of revenue!

Thoughts?
~Paul

**Comment by JennaMalkin** [comment]
There's a trello card about something similar here: https://trello.com/c/eOylUgB0 - don't forget to vote and comment on it!

**Comment by DanielTheBard** [comment]
Personally, I'm opposed to a trading system. Giving others gold or items isn't helping them out. It's removing incentive for them to work harder at bettering themselves.

**Comment by lemoness** [comment]
Actually, a more relevant card is this one: https://trello.com/c/BLIOj4Ty/206-send-gifts - that Potion one's not as relevant, now that Healers are around.

The feature has been debated and bandied around for a while. I have a hunch that spells may be the key to this - some people have been proposing the idea to use gold to buy spell scrolls, which they could then cast on a party member. I can imagine one like "double gold gain" - your gold gives that person a huge advantage, but they still have to work to achieve it!! 

Chime in on the card :)

**Comment by colegleason** [comment]
I'm going to close this issue while we have a discussion on that Trello card.

**Comment by EHLOVader** [comment]
I noticed that the trello card was in the Accepted list. 
Does that usually mean action should start over here? or would that bring this issue ticket back to life?

Since then all conversation on Trello's side has been about how everyone would like to see this feature.
