### ISSUE TITLE
Quest Buying Glitch

### ISSUE THREAD

**Issue by MarsEnyalios** [HabitRPG/habitica#2624]
I managed to try and buy a quest just as my computer glitched out, giving me two of the same quests and taking 8 gems. I only wanted one of the quests D: Ryan told me to come over here and post with my UUID, so here I am, requesting that one of my quests be taken away and four of my gems refunded. 

Here is my User ID (is that the same as my UUID? I hope so): 

ed9d1f2b-6d29-4892-801c-06d1a191b860

**Comment by lefnire** [comment]
refunded gems. I'm leaving quest scrolls alone, that's a pita to deduct

**Comment by MarsEnyalios** [comment]
Thank you!
