### ISSUE TITLE
Are dailies supposed to stay gray while resting at the inn?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2625]
I started resting at the inn a week ago since I got sick and was having trouble completing my dailies. I still was able to complete them some days though, so I checked them off when I could..

However, for the past few days, my dailies have been stuck gray and haven't been resetting. I'm wondering if that's because I am resting at the inn, or a bug?

In addition, my quest, santa trapper, was put on hold, even if I complete a todo. I'm guessing that's the expected behavior, but just thought I'd check.

**Comment by DanielTheBard** [comment]
It's because you're at the inn. Dailies don't reset while you're checked in. So if you mark off dailies while you're in the inn, they will stay grey until you check out and then let the day end.

**Comment by ghost** [comment]
Why are you able to check them off at all, then? That's sort of confusing.

**Comment by DanielTheBard** [comment]
Cause maybe you did them while you were sick/on vacation? But it won't reset until you check out, preventing you from abusing the safety of the inn. (Hard to remember, but I think at one time it used to reset and just not deal damage to you. Which people could abuse. I don't think it's that hard to understand as is though.)

http://habitrpg.wikia.com/wiki/Tavern

**Comment by ghost** [comment]
I disagree, it's not entirely clear that they're not resetting because I'm in the inn, and it seems odd that you can do it once at all. Also, I've been having enough issues with the custom reset time having bugs that it's easier for me to assume that it is a reset bug, without explicitly marking it as such.

I'd suggest maybe a slight UI change, instead of graying them out, something slightly different to remind you you're at the inn?

**Comment by DanielTheBard** [comment]
But there is something to remind you that you're in the inn. "Zzz" s appear next to your character at the top of the screen. This symbolizes that you're resting in the inn. Party members will also have those if they are resting in the inn.

**Comment by ghost** [comment]
Yes, but it's not clear what the proper behavior regarding dailies at the inn is, especially since you're allowed to do them once, and then they gray out until you check out. Although you may find this behavior obvious, it wasn't obvious to me, and is confounded further by the custom rollover bug.

**Comment by 9fruits** [comment]
I had this too, couldn't do the dailies that I had done when I was sick the next day, because they weren't reset when I checked out. I understand that it happens, but it shouldn't be that way.

**Comment by colegleason** [comment]
So I don't think we plan to change the reset functionality here, but maybe a UI change is in order. We could, maybe, pop up a modal when you load the page while you are in the inn? Or put up a "action not allowed" cursor when you try to check them off?

**Comment by ghost** [comment]
What about something as simple as just graying out the whole dailies column?

**Comment by lefnire** [comment]
FYI, there's a lot of "Inn v2" convo on Trello. Nobody likes the current Inn functionality, it's just the simplest and we plan to fix it later. Do a search on "Inn" on the Trello board to join the convos, let's close this ticket to avoid disjoint convos

**Comment by 9fruits** [comment]
For me the ideal solution would be for everything to be grayed same as the way things are when it's not the day to do them. Then you could still check them off so you could still get a reward for doing them regardless of whatever you're staying in the inn for, and they'd be reset the next day, without the penalty of missing them.
