### ISSUE TITLE
Beta Site is Down

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#2626]
Just tried to get on and it's down :( I'll check the main site, too.

Edit: Main site is fine. Just beta is down.

![screen shot 2014-01-28 at 7 16 47 pm](https://f.cloud.github.com/assets/4434731/2025380/b42d5630-887a-11e3-9188-10ac7baf0ac3.png)

**Comment by lefnire** [comment]
Fixed, npm coffee-script version issue
