### ISSUE TITLE
Rewards error

### ISSUE THREAD

**Issue by makethisreal** [HabitRPG/habitica#2628]
Hi,

I'm new to the site and recently set up some custom rewards. Unfortunately on trying to edit a BIG reward to have a higher coin cost I accidentally "purchased" said reward. Since this isn't something I'm actually going to have any time in the near future, this was a waste of coins for me. I was wondering if there's some sort of undo feature that I missed somewhere?

I checked the FAQ and open tickets, but couldn't find any answer to this issue.

Thank you.

**Comment by deilann** [comment]
Mmm, undo is on its way, but doesn't exist right now.

Thoughts: https://github.com/HabitRPG/habitrpg/issues/2502

Would like to disable the ability to click on things whilst editing them.

**Comment by deilann** [comment]
Just so you know, you can now fix gold again in Fix Character Values under settings. Let's follow this at #2502 now.
