### ISSUE TITLE
[question] About the values of the habits and coins

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#263]
I dont know where to ask this, but there i go:

Reading the Algorithms page I cant found two things (or maybe I just not understand it):
- How is the conversion between XP and Gold or Silver? I other words, how many money I get for every task i complete?
- How many HP I lose for every "minus" I hit in Habits?. I think, a negative habit must be more "toxic" if is more frequent: e.g. smoke is less negative once a week than once or twice a day. But I don't know how was implemented in the organic algorithm of habitRPG.

**Comment by lefnire** [comment]
Check out [scoring.coffe L42](https://github.com/lefnire/habitrpg/blob/b9c9586696ee7f766219e8c0e80a937ff0324ecd/src/app/scoring.coffee#L42). A "task delta" is calculated (modified by level, armor, and weapon), and applied to HP or Exp + GP. I was considering switching to [Roar Engine](http://www.roarengine.com/) as a black-box algorithm engine.

**Comment by racuna** [comment]
Great, thanks :D

## 

oɔıɟíuƃɐɯ sǝ ɐunɔɐɹ ןǝ

**Comment by lefnire** [comment]
Oh, also https://github.com/lefnire/habitrpg/wiki/Algorithms

**Comment by horusofoz** [comment]
@racuna With the info provided are you cool with closing this ticket?

**Comment by racuna** [comment]
Yeah, thanks.

## 

oɔıɟíuƃɐɯ sǝ ɐunɔɐɹ ןǝ
