### ISSUE TITLE
Feature: Send bug report button

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2632]
We should add a button to the header menu that sends a bug report which consists of: the browser, os, user id, the last N number of batchUpdate operations that were processed, etc. May help with debugging without taking up all the memory and bandwidth of logging.

**Comment by crookedneighbor** [comment]
We now have a button that gives instructions for how to submit a bug report, not exactly this, but so far it doesn't seem like anyone wants to tackle this specifically so I'm closing it.
