### ISSUE TITLE
Use a CDN for static files

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#2634]
We shouldn't server static files through Heroku, it only adds more load on the server. 

I think something like Amazon S3 won't be very expensive, almost free for the storage, we may have some costs for the bandwidth but since we cache most of the files it won't be much. http://aws.amazon.com/s3/pricing/

@lefnire @colegleason 
##

**Comment by paglias** [comment]
Or even better a complete CDN like Cloudfront Or [CloudFlare](https://www.cloudflare.com/features-cdn) (I'm not very expert with these services)

**Comment by colegleason** [comment]
I can set it up if you like. We just need to get an invalidation and
caching strategy down.

**Comment by colegleason** [comment]
Alright, so the problem is this: what files are static and how do we handle invalidation when we push an update?

It looks like files for production are hashed like `app-d1e14df9.js`. If that is the case, we just need to make sure that the HTML references the new hash and we don't have to worry about invalidation. Is the HTML updated as part of the build or does the Node server map `app.js -> app-d1e14df9.js`?

Can we make the HTML static as well? It's my understanding that we serve the jade file to the browser where it is rendered. If that is the case, then the jade stuff isn't templates server side and can be made static.

**Comment by lefnire** [comment]
So just a couple thoughts. We previously tried the CDN thing, it made local dev somewhat difficult. It also made it an issue for users who were hosting locally instead of using Habit proper (security, performance, etc). Turned out there were more of those than we'd thought. So we'll want to make sure that `NODE_ENV=development` uses the local files, probably?

Anyway, not dogging the idea - totally up for it, just dumping some thoughts.

**Comment by paglias** [comment]
The cache is setup here : https://github.com/HabitRPG/habitrpg/blob/develop/src/middleware.js#L36-L90 (I know, it's messy)

Mainly it maps all the files inside /build which are be renamed with an md5 hash of the content appended at the end to their original name:

`build/app.js -> build/app-1regd5fst.js` 

and there's a function that calling it with the original file name supplied it prints the hashed one.

The files not cached are mainly images (execpetion made for the spritesheet) because we would have to change the urls in the css files, everything else is or can be cached.

---

About Jade files, I was thinking abouth that too, actually there's some data passed from the server to the view during compilation:  https://github.com/HabitRPG/habitrpg/blob/develop/src/middleware.js#L173-L200

But we can do that with client side code or compiling with grunt, but since translations are injected at compilation time we would have to compile a different html version for every language which isn't as bad as it seems.

---

@lefnire sure! I was thinking about a grunt task run before or during heroku deployment that upload the files from local maching to s3 or whatever, otherwise it will serve local files.

Cloudflare seems to be totally automatic, like a proxy in front of the site (but the version with ssl support costs 20$/mo)

**Comment by colegleason** [comment]
Oh yeah, totally. We should only use the CDN for prod.

On Wed, Jan 29, 2014 at 2:38 PM, Tyler Renelle notifications@github.comwrote:

> So just a couple thoughts. We previously tried the CDN thing, it made
> local dev somewhat difficult. It also made it an issue for users who were
> hosting locally instead of using Habit proper (security, performance, etc).
> Turned out there were more of those than we'd thought. So we'll want to
> make sure that NODE_ENV=development uses the local files, probably?
> 
> Anyway, not dogging the idea - totally up for it, just dumping some
> thoughts.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2634#issuecomment-33627970
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by paglias** [comment]
When I finish Bootstrap3 I'll refactor caching then we can tackle this, the more I think about it Cloudflare seems really cool, it requires no changes on the server side and if we use it correctly it may save a lot of resources on heroku. The only problem with HTML caching is that we can't cache the index or other static pages because there's no way to bust their cache but compiling Jade to static HTML is on my to do list

**Comment by colegleason** [comment]
@paglias: We can bust their cache (it's called purging). They have a web interface for it or there is an API call [here](http://www.cloudflare.com/docs/client-api.html#s4.5).

**Comment by colegleason** [comment]
@paglias And actually, you may have to correct me on this, is the reason we have to bust our HTML files because the reference to `app-HASH.js` would change? Otherwise I don't really think it would be common for us to bust them.

I'm wondering if there is a scheme where we just set a semi-short TTL on the HTML pages (24-48 hours).

**Comment by paglias** [comment]
The problem with html files is how to bust them.

Express itself sends the ETag header with every request and if it didn't change even if not cached it will respond with a 304 without sending any content.

But while for other files we can easily change their name telling the browser to load a new, uncached file, we can't do this with html files, we can't rename `static/about` to `static/about/45ghfs676wq` to bust it and as far as I know there isn't another way to do that on a browser.

There's appcache but it has been built for offline apps and would load the new file version only the second time it is accessed, the first one you get the cached.

**Comment by colegleason** [comment]
I guess what I am asking is why do we care if HTML is busted or not? Those
should only be for static pages that don't change often and people will most likely only view once.

On Thu, Jan 30, 2014 at 11:49 AM, Matteo Pagliazzi <notifications@github.com

> wrote:
> 
> The problem with html files is how to bust them.
> 
> Express itself sends the ETag header with every request and if it didn't
> change even if not cached it will respond with a 304 without sending any
> content.
> 
> But while for other files we can easily change their name telling the
> browser to load a new, uncached file, we can't do this with html files, we
> can't rename static/about to static/about/45ghfs676wq to bust it and as
> far as I know there isn't another way to do that on a browser.
> 
> There's appcache but it has been built for offline apps and would load the
> new file version only the second time it is accessed, the first one you get
> the cached.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2634#issuecomment-33713141
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by paglias** [comment]
Ok, so what do we do with those, we don't cache them at all (what I think is the best solution) or set an early expiration date hoping no one has problems?

If we use a CDN and compile jade files I believe they will load very fast, no one pretends an immediately loaded website

**Comment by colegleason** [comment]
What is the output of compiled jade files? Can those have hahsed names?

On Thu, Jan 30, 2014 at 11:55 AM, Matteo Pagliazzi <notifications@github.com

> wrote:
> 
> Ok, so what do we do with those, we don't cache them at all (what I think
> is the best solution) or set an early expiration date hoping no one has
> problems?
> 
> If we use a CDN and compile jade files I believe they will load very fast,
> no one pretends an immediately loaded website
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2634#issuecomment-33713851
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by paglias** [comment]
Yes they can have hashed names but the browser when it receives a file with an expiration date, requests a new file only when it finds another one (name changed) and we can't change the urls of the static pages every time.

**Comment by colegleason** [comment]
Right. I agree we can't change the URLs, but I don't understand why we need to bust the static files. It's not going to affect me if /static/about/ is out of sync on my local browser from the codebase.

**Comment by paglias** [comment]
What about this scenario: I open the front and plans pages this evening, but I don't signup. The expiration data is set in 48hrs, tomorrow evening I visit the page again and in the meantime the plans has changed or a new feature has been added. I don't see the changes.

I understand this is not something that is going to be common but I don't think that saving a bunch of requests that will return a 304 (200ms each?) is so important. I don't know if you say that in english, but here in italy we have an expression that says that the game isn't worth the candle. I think it's one of those cases.

**Comment by colegleason** [comment]
Okay, that makes sense. That would be confusing to the user. There is a solution where we set the browser to not cache and still cache on Cloudflare.

But yeah, you're right. It's probably not worth it. I just figured it might reduce CPU usage on the Node servers.

**Comment by paglias** [comment]
I don't know if that is possible, I'll signup for cloudflare and see what options they have. It would be perfect to have it linked with heroku, every time a new app version is pushed Cloudflare check for updates, otherwise it serve cached files.

**Comment by colegleason** [comment]
Should be possible, mentioned in this blog post:
http://blog.cloudflare.com/edge-cache-expire-ttl-easiest-way-to-override

You can set different TTL for browser and for edge.

On Thu, Jan 30, 2014 at 12:32 PM, Matteo Pagliazzi <notifications@github.com

> wrote:
> 
> I don't know if that is possible, I'll signup for cloudflare and see what
> options they have. It would be perfect to have it linked with heroku, every
> time a new app version is pushed Cloudflare check for updates, otherwise it
> serve cached files.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2634#issuecomment-33717736
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by colegleason** [comment]
![screen shot 2014-01-30 at 9 14 24 pm](https://f.cloud.github.com/assets/232327/2047625/e2e13486-8a25-11e3-9f3f-4cfd07604ba3.png)
![screen shot 2014-01-30 at 9 15 44 pm](https://f.cloud.github.com/assets/232327/2047633/00f52d10-8a26-11e3-9773-2c257ab8a21c.png)

A large portion of the requests we serve are static assets

**Comment by paglias** [comment]
Why it doesn't show complete urls and only `.png`?

Anyway spritesmith image is cached, bootstrap icons aren't because we would need to change the reference to them in bootstrap css, emoticons in the tavern are not cached and each image is separated, it's not a big sprite

**Comment by YokoZar** [comment]
I just wanted to bump this bug and ask if this is still roughly the state of the world.  Is substantial server resources still spent on static content?

**Comment by Alys** [comment]
Do we need to do anything more for this?

**Comment by paglias** [comment]
Yeah, something to keep in mind for the rewrite

**Comment by paglias** [comment]
We're going to do this with the redesign
