### ISSUE TITLE
Metrics for performances

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#2635]
Do we have metrics for the server & client performances?

If we don't it may be useful to collect them, [New Relic](https://addons.heroku.com/newrelic) seems to have a free plan & heroku integration.

**Comment by colegleason** [comment]
New Relic is pretty nice. Not sure if we qualify for the "Stark" plan though. Perhaps "Wayne" is sufficient.

**Comment by lefnire** [comment]
I've been meaning to give New Relic a shot, I'll check into this when I get a moment

**Comment by lefnire** [comment]
Google Analytics will give you some client-side stuff, but for details you gotta use Chrome's dev tools, the following tabs: Profiles, Audits, AngularJS(Batarang). 

We've now deployed New Relic. This is _very_ useful, and has helped us pin-point lotsa bottlenecks. I'm gonna put this in the milestone to show progress on backend perf.

@colegleason Farris at NR pointed out to me the [tracing location](https://rpm.newrelic.com/accounts/565514/applications/3386694/transactions#id=547252277&app_trace_id=3091679693&tab-detail_3091679693=trace_details). Monitoring > Web Transactions > `post /user/batch-update` > App server transaction traces ([screenshot](https://www.evernote.com/shard/s17/sh/aaaac6a8-0dd5-40e3-bdd1-dd759bd58cd1/7201e0b79e44e9ade05188a574d9f107)) > Trace Details

Unfortunately it still doesn't break down the "Application Code" ([screenshot](https://www.evernote.com/shard/s17/sh/a5448e5d-abe0-4ce6-ab61-d93ff21f4e1e/fd8aa523978a85384fb3fd33896531c5)), so I'm following up. But hey, looks like we made some huge progress on the mongo side! Woot!
