### ISSUE TITLE
Chrome Extension notification typo

### ISSUE THREAD

**Issue by gbuell** [HabitRPG/habitica#264]
There's a typo in this notification, it should be spelled "lingering": 
![screenclip_013013_093427_AM](https://f.cloud.github.com/assets/3417856/111349/9269db3c-6af2-11e2-97ff-edefccd9968f.jpg)

**Comment by StanLindsey** [comment]
Good man ;) I'll fix that now. =D

Although this should be posted in [lefnire/habitrpg-chrome](https://github.com/lefnire/habitrpg-chrome/)
