### ISSUE TITLE
Item Disappearing when Equipping/Buying a Shield

### ISSUE THREAD

**Issue by conorg95** [HabitRPG/habitica#2641]
I had bought a Yeti-Tamer Spear a few days ago, had it equipped, then today I bought a Wooden Shield.  This obviously unequipped my Spear and reequipped my Sword, but when I went to find my Spear in my Inventory, it was gone, and available for sale again at the Rewards Store.

**Comment by deilann** [comment]
H'm. This actually shouldn't have unequipped your spear. (The spear isn't two handed.)

I'm going to guess https://github.com/HabitRPG/habitrpg/issues/2718

Did you ever check to see if the spear was in your equipment tab?

**Comment by conorg95** [comment]
Yes I did, and it wasn't there.
I seem to have had the same issue as the one you linked to very recently, except instead of the battleaxe, it's a left-handed Scimitar.  It is on my avatar, and the bonus is applied, but it is still for sale in the store.
Have you come across a way to fix this yet?

**Comment by deilann** [comment]
No, but you can give yourself the gold via fix character values, and repurchase it, which fixes the problem, but not the source. Let's follow this at #2718.
