### ISSUE TITLE
I didn't get the gems I paid for.

### ISSUE THREAD

**Issue by Jefferlope** [HabitRPG/habitica#2643]
On Monday (January 27th), I tried to buy 20 gems. I was charged $5 to my PayPal, but I still haven't received the gems. I contacted @HabitRPG via Twitter and was told to make a post here.

I was hoping to receive the gems before the gems before the Winter events end, but it's looking like that might not happen.

Thank you,

-Jefferlope

**Comment by lefnire** [comment]
Shoot me your UUID

**Comment by Jefferlope** [comment]
My User ID: 5ae2e173-21b6-4d55-9409-cd921e307f0e

**Comment by lefnire** [comment]
give that a shot
