### ISSUE TITLE
Site not displaying in Safari

### ISSUE THREAD

**Issue by jwodder** [HabitRPG/habitica#2644]
Since 2014 January 24, trying to view the HabitRPG site (habitrpg.com, www.habitrpg.com, and beta.habitrpg.com) in Safari 5.0.6 on Mac OS X 10.5.8 just displays a blank page (albeit with the proper window title), even though "View Source" shows what I assume is the full & complete code for the site.  Clearing my cookies and then refreshing causes the /static/front page to display correctly, but clicking "Play" then returns me to the blank page.  Clearing my cache changes nothing.

**Comment by deilann** [comment]
Check out this ticket: https://github.com/HabitRPG/habitrpg/issues/2571

**Comment by lefnire** [comment]
let's follow there
