### ISSUE TITLE
Add API-throttling

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2645]
We'll want to prevent the number of requests/second that a single client can send. This will prevent (1) malicious cheating, (2) DDoS, (3) accidental haywire scripts when developing 3rd-party apps (as noted by @fragmental

**Comment by fragmental** [comment]
Whoops.  Where'd that infinite loop come from?  I could have sworn I closed
that.

**Comment by wc8** [comment]
Could #2654 be related?

**Comment by lefnire** [comment]
@wc8 nay, see https://github.com/HabitRPG/habitrpg/issues/2642#issuecomment-33658836 for that one

**Comment by lefnire** [comment]
@wc8 oh I see what you're saying.. well, I'm not sure if we can easily solve that with API-throttling. I'm pushing a commit that says "limit 120 req/min". Aka 2req/sec, but spread out for the following reason. Many page loads request multiple routes at once. Eg, `GET /` gets the user, then the party. Many creation actions will perform back-to-back ops too (create, load, re-sync, etc). So if we tried to limit ops directly after another (say 1req/10milliseconds), we might hit issues with some other parts of the app.

Anyway, it's not a bad idea - I'm gonna look into it soon, because I didn't realize that potential issue until implementing the api-throttle. It could solve the actions-duplications, malicious clients (cheaters, DDoS), and accidental double-clicks.
