### ISSUE TITLE
Should not be able to cast spell on rewards

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2647]
This is Burst of Flames on a reward:
![screen shot 2014-01-29 at 9 51 58 pm](https://f.cloud.github.com/assets/232327/2037107/f70b440c-8961-11e3-8dbb-72d9b96a45d6.png)

**Comment by deilann** [comment]
Casting pickpocket on a completed to do gets me 1 xp and gp.

**Comment by negue** [comment]
can someone point me to the "casting" code of the frontend? I think this could be easily fixed IF the casting code just uses css queries to highlight the target task

**Comment by paglias** [comment]
here https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/tasks/task.jade#L1
see the ng-click and ng-class on the first line, they shouldn't be
there when displaying rewards

2014-10-12 1:37 GMT+02:00, negue notifications@github.com:

> can someone point me to the "casting" code of the frontend? I think this
> could be easily fixed IF the casting code just uses css queries to highlight
> the target task
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2647#issuecomment-58768371

## 

Matteo Pagliazzi - paglias.net

**Comment by negue** [comment]
Fixed with 67b341760eb0926ff890fd944d6ae1aec29e4ccc
