### ISSUE TITLE
Daily Bad Habits

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#265]
Im not sure what to call it, but i had an idea.

A habit that is a negative habit, that if you press it it loses HP (like usually) but if you don't press it all day then you gain Exp/Gold

Sort of like the opposite of a daily except you can press it multiple times in a day

**Comment by wc8** [comment]
Methinks this could be a simple enhancement of the current habits system: _GP/XP for not clicking a negative habit all day_

It makes sense to me. Here's how I think it could work:
- small bonus (GP/XP) for each bad habit not clicked at all during the day
- further small bonus (GP/XP) or 1 HP gained if HP is low, for not clicking any bad habits that day.

_Update:_ Would that fit what you're looking for?

**Comment by Pandoro** [comment]
I'm not sure if this is very beneficial, you can easily simulate this yourself by keeping a + and a - button. If you are doing the bad things, you punish yourself, if you do the good thing you reward yourself. Based on how red or green the task is, you get better or less good rewards.

By implementing another new rule for the habits, I think it might just get overly complicated. But this is just my feeling. I don't think of it as a bad idea, I'm just not sure if it is really worth spending time on.

**Comment by StanLindsey** [comment]
One of the examples of Habits are "take the stairs" which you plus up if you take the stairs and minus down if you opt for a lift. If that choice isn't given to you that day then no affect should happen.

**Comment by Nelmalih0** [comment]
But there are some habits that I set up that i click negative if i do it, and i click positive if i manage to avoid it all day, but the problem is that i sometimes forget to click the positive button

**Comment by Pandoro** [comment]
So what speaks against clicking it the next day for the previous one? If it is a habit which is so integrated into your system, you might not even have to track it with habitrpg? I don want to interfere in how you play, I just think that this is a niche feature which I think might not be interesting to many people and many cases.

**Comment by StanLindsey** [comment]
Set is as Daily then? They automatically deduct points if not ticked and you'll visually know if you've ticked them before logging off. 

(I'm not dismissing your suggestion at all, I just feel that it may be a tad specific, if others want similar functionality then by all means it can be incorporated)

**Comment by horusofoz** [comment]
I think this is covered under [Habit Shading](https://trello.com/c/YSXfecBt)?

**Comment by wc8** [comment]
Good idea: Habit Shading would give an acknowledgement of what was not pressed, and then the user could click the green button to reward himself. Daily would be a temporary workaround as it also introduces a risk: if the task doesn't get clicked by mistake, the user takes an HP loss. 

I'm just wondering, is this difficult to code or is there an issue with excessive XP accumulating? 
If it is introduced: the user who simply forgot to click negative would be rewarded. Maybe there is an advantage to using Habit Shading to let the user know when it's appropriate to reward himself. That way he has a chance to think, oops, I forgot about that time I took the elevator...

**Comment by horusofoz** [comment]
Discussion moved to [Habit Shading](https://trello.com/c/YSXfecBt).
