### ISSUE TITLE
Boss fight damage calculation triggering at times other than cron

### ISSUE THREAD

**Issue by chris-the-bruce** [HabitRPG/habitica#2651]
My girlfriend and I formed our first party and decided to try out the "Trapper Santa" scroll as our first quest.

We have found that the damage calculation for the fight occurs at times other than cron for both of us, and at different times for each of us.

We are pretty sure that's not meant to happen since the quest text includes: "All damage to and from a boss is tallied on cron (your day roll-over)."

And also since we're being punished for not doing dailies that we haven't done yet because it's not the end of the day yet.

My character nearly died from this today, and my girlfriend's character did die today (she has loads of dailies), losing a level and about 300 gold. (She's been working really hard, and she's really upset.)

Here's all the information that I can think of that might be relevant:

We are using different PCs in the same house.

We are both using Chrome as our browser.

We have not modified our cron time on the settings.

We are in the Australian eastern time zone, currently on daylight savings time (AEDT).

In the chat history for our party it shows the damage calculations occurring at about 7am AEDT (8pm UTC/GMT) for me and 1pm AEDT (2am UTC/GMT) (I can't be more accurate due to the time rounding up to hours), which makes me wonder if it is related to the times that we accepted the quest, but I remember us accepting the quest in the evening our time, only a few minutes apart. I could be wrong about that though.

I have manually set my HP back up to full, and my girlfriend has gone to the Inn to hopefully prevent this happening again until the quest is finished.

Our user IDs are:

Me - 52b2ddc8-9da5-484b-844d-0f0d63380c1b
My girlfriend - d645a792-baab-478b-a5e7-0f97c978bfc4

Here's a screenshot of my Social/Party page:

![image](https://f.cloud.github.com/assets/6541394/2037344/c0c560cc-896a-11e3-9fad-8acbd5ccbc03.png)

Are you able to investigate and fix this, and let me know please?

We were thinking of subscribing because we've had loads of fun with HabitRPG, and we've found it has helped us an enormous amount with our productivity, but we might hold off until there's a solution for this problem before we do.

Thanks for all your work on putting HabitRPG together, it's mostly awesome!

Kind regards,
Chris

**Comment by colegleason** [comment]
Chris,

Cron currently occurs when you login and it is past your cron time. We are
working on making it run at your actual cron time in settings, but we are
still a little ways away from having that complete.

From the log it looks like you are only experiencing one roll-over per day,
which is good. It just isn't at the time you expected, it is sometime
_after_ your cron time.

On Wed, Jan 29, 2014 at 11:05 PM, chris-the-bruce
notifications@github.comwrote:

> My girlfriend and I formed our first party and decided to try out the
> "Trapper Santa" scroll as our first quest.
> 
> We have found that the damage calculation for the fight occurs at times
> other than cron for both of us, and at different times for each of us.
> 
> We are pretty sure that's not meant to happen since the quest text
> includes: "All damage to and from a boss is tallied on cron (your day
> roll-over)."
> 
> And also since we're being punished for not doing dailies that we haven't
> done yet because it's not the end of the day yet.
> 
> My character nearly died from this today, and my girlfriend's character
> did die today (she has loads of dailies), losing a level and about 300
> gold. (She's been working really hard, and she's really upset.)
> 
> Here's all the information that I can think of that might be relevant:
> 
> We are using different PCs in the same house.
> 
> We are both using Chrome as our browser.
> 
> We have not modified our cron time on the settings.
> 
> We are in the Australian eastern time zone, currently on daylight savings
> time (AEDT).
> 
> In the chat history for our party it shows the damage calculations
> occurring at about 7am AEDT (8pm UTC/GMT) for me and 1pm AEDT (2am UTC/GMT)
> (I can't be more accurate due to the time rounding up to hours), which
> makes me wonder if it is related to the times that we accepted the quest,
> but I remember us accepting the quest in the evening our time, only a few
> minutes apart. I could be wrong about that though.
> 
> I have manually set my HP back up to full, and my girlfriend has gone to
> the Inn to hopefully prevent this happening again until the quest is
> finished.
> 
> Our user IDs are:
> 
> Me - 52b2ddc8-9da5-484b-844d-0f0d63380c1b
> My girlfriend - d645a792-baab-478b-a5e7-0f97c978bfc4
> 
> Here's a screenshot of my Social/Party page:
> 
> [image: image]https://f.cloud.github.com/assets/6541394/2037344/c0c560cc-896a-11e3-9fad-8acbd5ccbc03.png
> 
> Are you able to investigate and fix this, and let me know please?
> 
> We were thinking of subscribing because we've had loads of fun with
> HabitRPG, and we've found it has helped us an enormous amount with our
> productivity, but we might hold off until there's a solution for this
> problem before we do.
> 
> Thanks for all your work on putting HabitRPG together, it's mostly awesome!
> 
> Kind regards,
> Chris
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2651
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by chris-the-bruce** [comment]
Hi Cole,

Thanks for the quick reply!

In that case I'll have a go at setting our cron times to the evening and make sure it runs while we're logged in and aware of it.

I'm sure you'll let everyone know once you've got cron running at the time in the settings (that seems like a big one).

Thanks again.

Cheers,
Chris

**Comment by colegleason** [comment]
I actually wouldn't recommend that. Setting you cron time to something other than 0 can (but not always) introduce other bugs (which is why we are revamping the cron system).

Here's an example of how it works now:

Let your day start be 12 AM (midnight) and the current time is 7 AM. You last logged in at 10 PM the day before.

In the ideal system, cron ran at midnight and everything was calculated before you logged on. In the current system, we notice that cron _should have ran_ at midnight and run it right before we load the UI. However it really runs at 7AM and that shows up in chat as such (like you said above).

This was actually a fine approach (other than a few bugs) originally because _to you it appeared as if cron ran whenever it was supposed to_. Unfortunately, the addition of quests complicates things since cron doesn't just affect you now, it affects your party members too. Thus it looks like cron was ran at the wrong time in the chat (because it was).

This does introduce a gameplay problem because it makes it hard to guess when to heal. If it worked like you expect in the ideal system, you would just have to heal before your party members' cron time. In the current system you have to guess when they will actually login.

Anyways, we are working on a fix which you can follow at #2344. I hope that clears some things up so you can continue your quest!

**Comment by chris-the-bruce** [comment]
Hi Cole,

Thanks for another fast response, and thanks for all the details. That makes things much clearer for me, and will let us keep questing. :)

I had a look at #2344 and the branching conversations from there.

It's really interesting to be able to watch as you encounter emergent problems and figure out how to fix them, and it seems like you're all having fun with it, which is great.

Keep up the great work...

Cheers,
Chris
