### ISSUE TITLE
Allow user to configure date format

### ISSUE THREAD

**Issue by pafcu** [HabitRPG/habitica#2653]
HabitRPG uses the MM/DD/YYYY format which is not at all obvious for a lot of people. In other countries the format is given as DD/MM/YYYY, DD.MM.YYYY or even YYYY-MM-DD (which is also used in ISO standards).
According to https://en.wikipedia.org/wiki/Date_format_by_country the currently used format is very uncommon world-wide (Basically USA, Candada, Philippines and Saudi Arabia).
Users should be able to specify which format they want to use (with maybe the default value determined by geolocation?)

**Comment by wc8** [comment]
There's a request for YYYY-MM-DD in Trello, under dates (maybe it needs more visibility). If, for simplicity reasons we end up using just one format, I'm guessing _year, month, date_ is probably the clearest for most users. 
P.S. that might not solve the problem though, as the date display on the to-do does not show the year.

**Comment by patena** [comment]
I'd also like a customizable or at least less uncommon date format.

**Comment by lefnire** [comment]
As per wc8, well fix with iso. Current format is improper. Customizable is
too difficult technically

**Comment by paglias** [comment]
We can use moment.js for that, it has contry specific formats for dates (see also #2652)

**Comment by ghost** [comment]
Any update on this issue?

**Comment by crookedneighbor** [comment]
I saw [this PR](https://github.com/HabitRPG/habitrpg/pull/4422) was posted a little while ago. Havne't had a chance to check it out though. Will do so this week.

**Comment by paglias** [comment]
@mxp with the next deployment you'll have a new option in the settings allowing you to choose the preferred date format.

For future enhancement we could detect this on signup like we do with the language but for now is enough

**Comment by paglias** [comment]
Oh I see this asked for YYYY-MM-DD not dd-mm-yyyy

**Comment by crookedneighbor** [comment]
@paglias I think it suggested YYYY-MM-DD as a universal, everyone can agree on this format. Allowing the user to choose between two more common formats is a good compromise I think. And it shouldn't be hard to add in YYY-MM-DD as an option, right?

**Comment by paglias** [comment]
@crookedneighbor indeed! added

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg/pull/4422
