### ISSUE TITLE
503 error after random action, appeared twice

### ISSUE THREAD

**Issue by ibvee** [HabitRPG/habitica#2655]
First I received this message:

<!DOCTYPE html>
    <html>
    <head>
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

It was just the plain HTML code. 

After that a screen appeared in a very odd sice, way to small for the message, in the upper right corner saying something like: Error 503, check log if you're administrator.

User ID:
808aa439-96bf-4af1-9f4e-a74757d1e57f

browser is Firefox

**Comment by ehungerford** [comment]
Having the same issue in Chrome Version 32.0.1700.102 m

**Comment by deilann** [comment]
Follow this here, guys: https://github.com/HabitRPG/habitrpg/issues/2554
