### ISSUE TITLE
Died without taking damage, lost armor belonging to another class.

### ISSUE THREAD

**Issue by GuyDudeman** [HabitRPG/habitica#2656]
Hello, I signed in on my laptop this morning and got a message saying that I had died. Last night I got a perfect day, and should have lost no health this morning. I was a rogue, but switched class to Wizard, it says I lost a rogue item, but also I can now buy the royal mage helm again, which I had before. Looking at my daily streaks, it looks like all of the dailies I completed on my desktop didn't transfer to when I loaded the site on my laptop today, I'm not concerned about the level or the items, but I am concerned that the quest I'm on might fail because I died.

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544
