### ISSUE TITLE
Died twice today

### ISSUE THREAD

**Issue by princessbee728** [HabitRPG/habitica#2658]
So, I will admit, I forgot to check in my tasks yesterday - and when I logged in this morning on my desktop (win8, chrome), I died.  I kind of expected that.  So I marked down my tasks as I did them, and went on my merry way.

Fast forward to now, I'm on my laptop (ubuntu, firefox) and I log in again... and I die. Again.  Lost all the XP I'd earned this morning, and my money, and lost my epic fancy Archmage Hat, too.  

It shouldn't do that, right? Heh.

**Comment by colegleason** [comment]
@lefnire, a bunch of these reports have been coming in lately and it really
sounds like cron is running twice somehow, which sounds like a different
error than #1057.

@princessbee728 What is you custom day start set to?

On Thu, Jan 30, 2014 at 12:36 PM, princessbee728
notifications@github.comwrote:

> So, I will admit, I forgot to check in my tasks yesterday - and when I
> logged in this morning on my desktop (win8, chrome), I died. I kind of
> expected that. So I marked down my tasks as I did them, and went on my
> merry way.
> 
> Fast forward to now, I'm on my laptop (ubuntu, firefox) and I log in
> again... and I die. Again. Lost all the XP I'd earned this morning, and my
> money, and lost my epic fancy wizard hat, too.
> 
> It shouldn't do that, right? Heh.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2658
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by princessbee728** [comment]
@colegleason - I've left it at the default, decided not to mess with it because it's buggy.

**Comment by colegleason** [comment]
Cool, that backs up my theory that this may be a different bug.

**Comment by princessbee728** [comment]
Yeah, it seems like cron ran twice, because all the tasks I'd checked were unchecked.

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544
