### ISSUE TITLE
Too much damage from Gryphon and tasks not reset

### ISSUE THREAD

**Issue by melarish** [HabitRPG/habitica#2660]
I don't know what happened but I lost 50HP (and hence 50 gold :( ) overnight! I calculated damage from our party log and it was only 25. I had all my dailies done but today it showed most of them grey and two unchecked, meaning it did not do a reset for me. My custom reset is at midnight (default).

**Comment by lefnire** [comment]
Follow "too much damage" part on Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544  , "dailies not resetting" on #1057
