### ISSUE TITLE
Emoji and Markdown don't work in checklists

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2662]

**Comment by negue** [comment]
@lefnire @Alys Should there be Emojis in Checklists? And also Markdown? Since Markdown "inserts" the emoji's right?

**Comment by Alys** [comment]
I would LOOOOOOOVE to have markdown in checklists. Emoji would be cool too. I was under the impression they were implemented separately, but that's really just a wild assumption.

@lefnire, is there any reason to not have markdown in checklists?

**Comment by lefnire** [comment]
@Alys no reason, I'd be down for it too!

**Comment by negue** [comment]
I would take a try for this, unless you want to do it.

**Comment by Alys** [comment]
@negue Please do!

**Comment by negue** [comment]
Well that was quite easy, thanks to the markdown directive :D

**Comment by negue** [comment]
Can be closed now^^
