### ISSUE TITLE
Many glitches, a death and a lost yeti-tamer robe

### ISSUE THREAD

**Issue by Pecanne** [HabitRPG/habitica#2663]
Hi! Today I died after having all my HP the day before and most of my dailies finished (therefore I really shouldn't have died). I had bought the yeti-tamer robes (twice now cause it disappeared once before) yesterday and was planning to save up for my yeti-tamer spear (also purchased before then unexplainably back in my Rewards section). 
I have the latest iOS app and it was there that I saw that I had died. 
Today some of my dailies are still checked off as they were yesterday. 
D: Help? 
I've seen some similar issues on lost items but not also dying.
Here's my UUID: e8c2b52f-04a0-4719-ba9f-a2bd29f28a1a

I forgot to mention the glitches, there's an error message that happens over a few tasks especially when I check a few dailies down in a row.
This is the glitch I get on Chrome: 
<!DOCTYPE html>
    <html>
    <head>
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

**Comment by aurakami** [comment]
A lot of people seem to be having this problem, it looks like. As a suggestion for the site as a whole, I think special event items should not be able to be taken by "Death", it just is extremely unfair especially since they are a "one time" event.

You can see my partner's issue here, it's similar to yours: https://github.com/HabitRPG/habitrpg/issues/2630

**Comment by SabreCat** [comment]
@aurakami: Any limited edition item lost to death or Rebirth can always be bought back, even after the event is over.

**Comment by lefnire** [comment]
You can buy them back after death. As long as you bought it once during the special event, it's re-buyable permanently. Re: application error, follow https://github.com/HabitRPG/habitrpg/issues/2554
