### ISSUE TITLE
Unable to access private guild

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#2664]
I am unable to access the private "Contributors" guild to which I have been invited.

It is shown among my guilds but when I try to open its tab I get a 401.

I think it's because of these lines https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L126-L131 and consequently of this https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L21

Limiting the members to 15 if the user isn't in those 15 it will look like he isn't authorized to access the group.

**Comment by veeeeeee** [comment]
I've been having the same problem with the same guild. Right now it's showing me a chat notification in the guild but won't let me load the guild.

If it's helpful at all, @SabreCat tried to re-invite me to the guild but the system informed him I was already a member of that guild. 
![screenshot 2014-02-17 11 17 31](https://f.cloud.github.com/assets/5608909/2188630/218f71b6-9809-11e3-96ec-22577f9782ee.png)

**Comment by deilann** [comment]
Can someone invite me? I'm supposed to be a member and it would be
interesting to see if a new member has the same problem:
e7b5d1e2-3b6e-4192-b867-8bafdb03eeec

**Comment by veeeeeee** [comment]
Just tried and got "Please reload, "Error Group not found" (see Chrome console for more details)."

**Comment by paglias** [comment]
The limit to 15 members for GET actions was set to improve performances but I suppose we can remove it for private guilds at least if @lefnire is ok

**Comment by deilann** [comment]
Not sure if that'll fix it -- Bailey was having trouble accessing a guild
of 3 members.

**Comment by paglias** [comment]
@lefnire can we remove the `limit: 15` here https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L21 or it would kill performances?

Another option might be to split the getGroup database query in two pieces and getting all the members in case the guild is provate. Or even get the guild and do another find query to check if the user is a ong the members using the `$in` operator.

But I would go with removing the limit if it doesn't kill the server.

**Comment by lefnire** [comment]
@paglias what about [this as a fix](https://gist.github.com/lefnire/9bece67a27afc13fe67b)? If so, note-to-self: add a compound index to support this before launching

**Comment by paglias** [comment]
@lefnire I like that!
