### ISSUE TITLE
random death

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2665]
While trying to increase a task, HabitRPG became unresponsive, then informed me I had died.
It also duplicated my custom rewards.

Lately, I've been getting an application error (something about failing to load an Amazon page, I believe); I'll post it when it happens again.

UID dfba70b0-4b31-443f-928f-3bae5a200376

**Comment by lefnire** [comment]
got [quite a few dupes](https://github.com/HabitRPG/habitrpg/search?q=random+death&ref=cmdform&type=Issues) in the queue, let's follow up on those
