### ISSUE TITLE
Great difficulty sorting habits/dailies.

### ISSUE THREAD

**Issue by ThunderGyra** [HabitRPG/habitica#2667]
I'm having a very difficult and frustrating time trying to sort my dailies, habits, etc. because every time I try to move on, say, below another, all of a sudden it's at the bottom of the list, and three other dailies are in bizarre places, even though I didn't touch them. 

I figured it might be my extensions, but even after turning everything off, it's still happening. I'd like to know if this issue is just me.

**Comment by colegleason** [comment]
I believe it is a known issue with todos, but I actually wasn't aware it
was happening with dailies.

Can you post you UUID? I'm going to cross check it with some erros we have
been seeing.

@lefnire, versionerrors?

On Thu, Jan 30, 2014 at 8:44 PM, ThunderGyra notifications@github.comwrote:

> I'm having a very difficult and frustrating time trying to sort my
> dailies, habits, etc. because every time I try to move on, say, below
> another, all of a sudden it's at the bottom of the list, and three other
> dailies are in bizarre places, even though I didn't touch them.
> 
> I figured it might be my extensions, but even after turning everything
> off, it's still happening. I'd like to know if this issue is just me.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2667
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by lefnire** [comment]
@colegleason saw one 37m ago & 42m ago. Sound about the time @ThunderGyra? Yeah, as cole said - there's a known reason this would be happening for To-Dos specifically, but not for habits/dailies (the known issue wouldn't apply).. definitely those two types then that's effected?

**Comment by lorian** [comment]
I've had my dailies reorder themselves spontaneously at least once over the last few days (although it happens a lot more with to-dos).

**Comment by ThunderGyra** [comment]
@lefnire Sorry for the slow reply. That sounds roughly around the time. 

@colegleason Sorry if I sound like a dunce, but what is a UUID, and how do I find it?

**Comment by colegleason** [comment]
@ThunderGyra Sorry, it isn't that obvious ;-)

Go to Settings -> API and copy the numbers from there under UUID.

@lefnire The UUIDs are a bit of a leaky abstraction. Have you given any thought to somehow changing those on the display side?

**Comment by ThunderGyra** [comment]
@colegleason Thanks. Here: 6a98f6a4-0f42-439d-8d5e-db95dd579eff

**Comment by quin-jay** [comment]
@SabreCat recently opened issue #2860 to talk about API, UUID, and other terminology, in case anyone wants to continue discussion about that

**Comment by androidadvocate** [comment]
I am having the exact same problem. I did a search on github and discovered these three are the exact same issue:

https://github.com/HabitRPG/habitrpg/issues/3025
https://github.com/HabitRPG/habitrpg/issues/2667
https://github.com/HabitRPG/habitrpg/issues/3250

And MAY be related to: https://github.com/HabitRPG/habitrpg/issues/2606

These two issues should be consolidated into one so we know which one to donate a bounty to.

**Comment by Alys** [comment]
@androidadvocate : Those are not all the same issue. Some deal with sorting to-dos, others deal with sorting habits and dailies - while they might seem similar, they have different technical challenges. See the response I have made to your first comment elsewhere: https://github.com/HabitRPG/habitrpg/issues/3250#issuecomment-52825302

**Comment by antichris-zz** [comment]
I'm having this problem with dailies. Moving a daily causes the dailies to reorder seemingly randomly (the daily I was trying to move doesn't go where I put it; other dailies move around).

I'm using Chrome for Windows (version 41.0.2272.118 m, Windows 7 Enterprise). 

UUID: dfb616a4-9dbf-4ba0-b937-46e558f864d2

**Comment by Alys** [comment]
@antichris Are you using the normal website (habitrpg.com) or the beta website (beta.habitrpg.com)?

**Comment by antichris-zz** [comment]
@Alys The beta website.

**Comment by Alys** [comment]
Please try the normal website. The beta site can't be guaranteed to be reliable or to have normal behaviour since we use it for testing various code changes.

**Comment by antichris-zz** [comment]
@Alys I just tried logging out of the beta site and in to the normal site, and reordering dailies seems to work as expected on the normal site.

**Comment by deilann** [comment]
Also, if you're ever using beta and are reporting a bug, please let us know
that you're using beta. It's great to know when there are bugs on beta --
that can keep them from going to prod. But if we don't know you're on beta,
it doesn't help!

**Comment by antichris-zz** [comment]
@deilann Sorry! TBH I switched to beta ages ago when I was having trouble logging in, and forgot I was still using it. I'll mention it next time.

**Comment by Alys** [comment]
Closing because Habit/Daily sorting problems don't seem to occur now.
