### ISSUE TITLE
something definitely up with my drops

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2668]
I started getting only food as drops a while back. I ignored this and thought that I must have been one of those outliers that gets only one type of drop, and that I would get new drops soon. However, when I went to look at yet another food drop that I gained, it showed me that I had 10 food items (when I clearly only had just that one food drop), and there was no image for all 10. When I attempted to click on the drops, there was no reaction. I believe there was a thread here about a duplicates glitch for drops some time back (though I can't seem to find it) and I think that I'm experiencing the same bug.
My UUID is 80094f6c-bb4c-4bf8-862b-3b8c9028d40a and I am using the most recent version of Chrome (32.0.1700.102).

**Comment by lefnire** [comment]
Can you try a hard refresh? We added a bunch more food, and gave everyone
10 cakes as a habit bday gift

**Comment by ghost** [comment]
That worked! Thank you!
