### ISSUE TITLE
Don't show feeding bar for ineligible pets

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2669]
Once you've created a Mount of a certain species+color combination, attempting to feed another pet of that same species+color combination results in an error. But the little progress bar beneath the pet suggests that you _should_ feed them! It would make sense to remove the gauge if it's not possible to fill it up.

**Comment by deilann** [comment]
Here you go: https://github.com/HabitRPG/habitrpg/pull/2714
