### ISSUE TITLE
Easter Eggs

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#267]
I think there should be planned easter eggs anyone else think so? I think Adventure Time's Jake inspirational words appear ever time your buttons begin to go red.

**Comment by horusofoz** [comment]
Raised as [Trello 134](https://trello.com/card/easter-eggs/50e5d3684fe3a7266b0036d6/134)

**Comment by StanLindsey** [comment]
Easter eggs don't really get planned and made public. Thats sort of the point of easter eggs?

**Comment by horusofoz** [comment]
@SlappyBag Agreed. It's a nice idea but long down the track IMO.

**Comment by Pandoro** [comment]
Personally I think this is a nice idea and not hard to realize. Any item slot could easily get an easter egg item on events such as christmas etc. For example we could randomly get christmas gifts from tasks etc. Right now it seems far down the track, but once special rewards and badges are implemented, adding such things will probably follow naturally. So I wouldn't plan them right now as something we HAVE to think about, but they will be a nice touch once features are implemented that can benefit from this idea :)

**Comment by ghost** [comment]
Maybe then we should just close this. Honestly I wasn't entirely sure how to bring this up any other way.
