### ISSUE TITLE
Error when clicking "Sticky header" option

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2671]
In my Win7 Firefox, when I click the checkbox to toggle the "Sticky header" option, I get the "Something went wrong, please refresh" popup. Sometimes it also throws either a 400 or 404 alert, I haven't been able to reproduce that bit consistently. Console shows this:

[object XPCWrappedNative_NoHelper] app-54146eb0.js:5

**Comment by negue** [comment]
@SabreCat Error still there?
