### ISSUE TITLE
schedule db.repairDatabase() or set up a replicaset for slave-master syncing without downtime

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2672]
Due to our history-tracking (`user.history`, `user.tasks.*.history`), and history-_preening_, our database grows very rapidly, and that data isn't reclaimed on preen (due to how Mongo functions). The way to reclaim disk-space in mongo is `db.repairDatabase()`. You can see [from this screenshot](https://www.evernote.com/shard/s17/sh/4e077e53-3e19-4095-852b-137dc5539131/d9a2032318ddf3582bc874e66bd3077d) that reclaimed diskspace is substantial: almost half of the db size is defragable. Db size == db performance, so it's somewhat important (not crucial just yet, but may get there).

After some hunting around, there's no such thing as "auto defrag" or such in mongo, on a per-document basis or anything. The only solution is `db.repairDatabase()`. (`compact` doesn't reclaim disk space). Unfortunately, it's a blocking operation - meaning the site goes offline for ~5-10m. There are some complex methods using replica sets where you take one offline for repair, swap & repeat - we may go that route in the future.

Anyway, looks like our best bet is to schedule a `db.repairDatabase()` cron task, maybe every Sat @~4am ([habit's lowest lull](https://f.cloud.github.com/assets/195202/2048597/b1b1faea-8a4c-11e3-8380-096c24e2cd65.png)). Not a rush, just jotting down for posterity
##

**Comment by wizonesolutions** [comment]
I imagine something like this already happened?

**Comment by lefnire** [comment]
Alas, nay

**Comment by crookedneighbor** [comment]
Is this still a good idea? @Alys @gisikw @paglias?

**Comment by paglias** [comment]
Maybe if we're going to have some offline minutes, we can run this but I don't have enough information whether this is going to give a boost to performances or not. Also in the docs it says:

> It also recreates all indexes in the database.

Which given our indexes may take a while, more than 5-10 minutes for sure

**Comment by Alys** [comment]
We could run it on a local copy of the database, but would we be able to
simulate production use well enough to tell whether it boosts performance
sufficiently?

**Comment by paglias** [comment]
I'm not sure, also according to the docs (http://docs.mongodb.org/manual/reference/command/repairDatabase/ - they are for 3.x, the version can be changed in the top left) it only frees space, there's no mention of performance gains. 

The only thing could be cost, but our plan still have enough free space to keep 4x the data we currently store.

Maybe we should ask the guys at MongoLab but I wouldn't say it's high priority

**Comment by gisikw** [comment]
I suspect that setting up a replicaset should effectively fix this without requiring downtime. First, set up a slave to pull in from the master, then elect the new slave to master, then wipe the old master and resync against the new "pristine" master. All the while, we'll have an active DB for the app to operate against.

**Comment by paglias** [comment]
Fixed with the new database since it rewrote all the data
