### ISSUE TITLE
Hide completed dailies

### ISSUE THREAD

**Issue by tstolpestad** [HabitRPG/habitica#2674]
Hi, just got back into using HabitRPG and enjoying it a lot, but now that my computer screen is smaller I'd run into my later dailies being lost in the grey that is the ones I complete early in the day. 

Would it be possible to have an option for hiding dailies you have completed so your list only shows the one you have left todo?

**Comment by JennaMalkin** [comment]
There's a Trello card about this here: https://trello.com/c/q7uM2Ymq - don't forget to vote and comment!
