### ISSUE TITLE
Awarded Beastmaster prematurely due to gryphons

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#2676]
I know the plan is to remove gryphons from the beastmaster requirement, but we seem to be in a weird hybrid phase where the pets page shows x/100 but you still receive the achievement when you hit 90. I have 88 of the original 90 pets, but when I hatched my second gryphon (reaching 90/100), I got the Beastmaster achievement. :( 

Seems to me we should set the achievement threshhold temporarily to 100, until we've excluded the gyphons, and then run some kind of script to correctly identify all the people who hit 90 while it was broken and award them the achievement. It was really a bummer to get it when I didn't deserve it yet. I've been looking forward to this for a looong time.

**Comment by lemoness** [comment]
So, I'm sure you know by now, but the gryphons are actually separate from Beastmaster, and indeed will be on their own page at some point. The devs just have a lot to do!

**Comment by brightbold** [comment]
Right, I am aware of that (and even mentioned it above!) and I do recognize this is not the highest priority item - there's a lot of cool stuff going on now, as well as some more urgent things like the application error. 

I was just thinking that until we get the gryphons sorted, we should change the Beastmaster requirement to 100 (since gryphons appear to be included) so that you won't get an incorrect Beastmaster for 88 pets + 2 gryphons. (I'm assuming that changing the threshold number is quite easy, as opposed to making the change to remove the gryphons from the equation which is more time-consuming). My assumption had been that as long as the page said x/100, you would need to reach 100 pets to get Beastmaster, even though I knew that was not the long-term plan. So it was jarring to get the achievement at 90 (when I was really only at 88. And then bizarrely, I got it _again_ today when I hit 89. If I get it a third time when I hit 90 that will be a very happy bug.) 

So not a big deal, it just didn't work they way I was expecting. It seems like you won't get it until 100, or until the gryphons get pulled out onto their own page, whichever comes first. So just weird to get it for a random combination of gen 1 & gen 2 pets totaling 90.

**Comment by lemoness** [comment]
With Rare pets, this bug has actually been around for a long time - I've
been awarded Beastmaster probably 10 times. So it isn't just the gryphons
that screws it up, it's the polar bear, the hydra, the veteran wolf, the
cerberus... It's actually indicative of a larger issue that will probably
have to be fixed when the pets get sorted out.

**Comment by brightbold** [comment]
Huh. I thought those were fixed when they removed the special pets from the count. Because if they weren't, I should have gotten Beastmaster earlier, since I have the polar bear, veteran wolf, and turkey. But the second gryphon is the first one to trigger it. But, not a big deal, especially now that it looks like I'll continue to get the award each time. I was mainly sad that I wasn't going to get my big TA DA moment when I hit 90 because I'd already had it. But it looks like I'll just get a lot of ta da moments, which is OK. I know which one is the real one.

**Comment by lemoness** [comment]
They may indeed have been fixed! If so, maybe the Gryphons should
temporarily be removed from the pet count and put under the rare pet tabs
for now? I'm not a programmer, so I don't know what would be the easiest
solution. It may be that we just leave it as-is until we make a new Quest
Pets page.

**Comment by brightbold** [comment]
Yeah, a temporary solution would be nice if it's easy to do, if it's hard then it's not worth it, and we can wait on the Big Pet Overhaul.
