### ISSUE TITLE
DAILIES not completely resetting (yes, I reloaded page and tried Sync)

### ISSUE THREAD

**Issue by FLJIM560** [HabitRPG/habitica#2678]
In the last 3 days, I've been having an issue with not all my DAILIES re-setting overnight. I also cannot sync when I switch computers, (I start the day on a desktop and switch to laptop) I cannot get my laptop to sync with the site. Reloading the page has no effect and, in my experience, the SYNC button never works. Some but not all completed tasks from earlier in the day appear as unchecked. The first couple of days, I just re-checked the completed tasks. Last night, when I saw that the laptop wouldn't sync, I just closed the site without re-checking the already completed DAILIES. 

This morning I'm dead, even though I did most of my DAILIES and had 45-50 Health. Even though my character died, about 1/3 of my completed DAILIES from yesterday remained checked this morning. 

Since these problems started I've been seeing "503" errors a few times a day if that helps. I'm accessing the site on both computers using Chrome 31.0.1650.63 m.

FYI, when I died, I didn't lose my Mana or my Level but I lost 3000+ Gold. The "Fix Character Values" option in Settings does not give the option of restoring Gold, even though that option appears in the description.  PLEASE GIMME MY GOLD BACK!!! :(

Display Name: Jim560 (changed from FLJim560; not sure which is UserID)

**Comment by deilann** [comment]
UserID is going to be a string of numbers and letters, found under settings > API

**Comment by FLJIM560** [comment]
@ deilann
Thank you. I should have known that. Sorry all.

Here it is...
2419a180-11e2-4266-8466-93160c1daf6a

**Comment by deilann** [comment]
No problem! It's not super intuitive. Don't worry about it.

**Comment by meganstrickland** [comment]
Related to [Dailies still checked from yesterday #1057](https://github.com/HabitRPG/habitrpg/issues/1057)?

**Comment by kathatfield** [comment]
I'm having the same problems, complete with the 503 for the past couple days now. I assumed it was an issue on my end but restarting and syncing everything has yielded no results and now I see other people are having the same issue. My one day of the week only dailies are popping up to be ticked off so the system knows it's a new day but the dailies aren't resetting. I died, lost a level, and something around 50 gold. Tried on my cellphone and also not resetting. Using Firefox and as a last ditch effort turned off all add-ons but no cigar for that either. Please help!

UserID: e4584811-041d-493a-9db2-adf01a8aaddb

**Comment by deilann** [comment]
Yeah, guys, this is definitely related to https://github.com/HabitRPG/habitrpg/issues/1057, if you could follow it there.

You can now use fix character values to re-add your gold, now that Winter Wonderland is over.
