### ISSUE TITLE
Absurd Party Robes not showing in Rewards column - L6

### ISSUE THREAD

**Issue by thiefofcamorr** [HabitRPG/habitica#2683]
'Absurd Part Robes' aren't appearing for me in the rewards column, or anywhere else on the site. I'm L6 and have refreshed and looked everywhere. I'm on a mac running Snow Leopard using Chrome. Hopefully the screen shots I've taken will assist. What am I doing wrong? :) 

![tumblr_n0aajz9wnq1qzzgeuo2_500](https://f.cloud.github.com/assets/6558868/2056629/54e67a36-8ae5-11e3-9e51-a50237656a8d.png)
![tumblr_n0aajz9wnq1qzzgeuo1_250](https://f.cloud.github.com/assets/6558868/2056630/54eb7efa-8ae5-11e3-8a2e-492bff989ec0.png)
![screen shot 2014-02-01 at 11 33 52 am](https://f.cloud.github.com/assets/6558868/2056631/54ef316c-8ae5-11e3-94a7-617f434ef910.png)

**Comment by lemoness** [comment]
A bunch of people have been complaining about this in the tavern, too.

**Comment by thiefofcamorr** [comment]
Guessing it's too late for this to be fixed, which is a shame :( I would have liked those robes!

**Comment by lemoness** [comment]
No, I want to find a way to get you these robes somehow, because it was not
your fault that you did not receive them. We might have to do a manual fix,
though. Any programmers want to jump up and help? I know it's low-prio, but
would it be difficult to get thiefofcamorr their robes?

**Comment by colegleason** [comment]
@lemoness If they logged in during the birthday party they have an achievement. We could just give anyone with that achievement the robes. cc @lefnire

**Comment by colegleason** [comment]
Something to note is that Yeti-Tamer's spear is also not in your rewards. Looks like something went a bit haywire with all limited time items (assuming this was before the end of the event).

**Comment by lemoness** [comment]
Yes, I was first contacted about this during midday January 31st.

**Comment by admk55** [comment]
This happened to me as well. =(

-69a95718-88a0-4a85-acdd-9770ae81ea1e

**Comment by thiefofcamorr** [comment]
Oh, yes, hrm. I thought I had bought that spear then wondered a bit later where it had gone. I'm now down with a pretty awful cold so my thought process is a bit laughable :D Thanks for pointing that out, colegleason!

**Comment by colegleason** [comment]
@thiefofcamorr what is your time zone and about what time (local) did you
take these screenshots?

**Comment by thiefofcamorr** [comment]
Ooh, now there's a good question. I'm timezone UTC/GMT +9:30 hours, and these screenshots were taken Saturday 1st February 6.30am for the first two when I started looking into it, then probably about midday Saturday for the third screenshot of the inventory, just before posting here.

**Comment by colegleason** [comment]
Yeah, I think the code currently uses local time zone. We probably should
change it to server time. Not sure.

@lefnire thoughts on timezones overall? Should we try to operate in user
time?

**Comment by thiefofcamorr** [comment]
Is there any update regarding this?

**Comment by lefnire** [comment]
Shouldn't be a TZ issue, as the item visibility is client-based (using a moment.js compare). I'll just grant whoever is missing stuff an item, list your UUID and what item you want

**Comment by colegleason** [comment]
But Tyler, is item visibility set by date for the event? By the time he
logged on it was already Feb. 1st in his time zone.

**Comment by admk55** [comment]
## Fixed

69a95718-88a0-4a85-acdd-9770ae81ea1e

Absurd party robes, please! 

Thank You!

**Comment by thiefofcamorr** [comment]
## Fixed

I'm e890aac7-e282-4c03-a46f-15f71725ac64

Could I please have Absurd party robes, and the Yeti-Tamer's spear that's suddenly not in my items either. If they could be granted that would be excellent :)

For information's sake, yes, I was online and using HabitRPG when the item should have been visible. Everyone else was talking about getting theirs, and I couldn't see it anywhere, nor could a handful of others posting in the tavern.

**Comment by lefnire** [comment]
@admk55 @thiefofcamorr √ . Fix gold at [Settings](https://habitrpg.com/#/options/settings/settings) > Fix Character Values. 

@colegleason will revisit your discussion later, I'm in stupid mode right now

**Comment by admk55** [comment]
Thank you!

**Comment by thiefofcamorr** [comment]
Hoorah, thank you kindly :)

**Comment by quin-jay** [comment]
This issue looks potentially closable?
