### ISSUE TITLE
Migration for Beastmaster Mounts fix

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2684]
A fix was recently implemented for evolving pets into Mounts: once you level up a pet into a Mount, a faded ghostly image of the pet remains in the Pets grid. You can't equip it, but it still holds the slot to show you did hatch a pet of that type. The count of pets found on that page also includes these "younger self snapshots".

However, this wasn't done retroactively. I, for instance, have a Base Fox mount, but the Base Fox slot on the Pets tab still shows the mystery pawprint. Since one can safely assume that having a Mount of a species+color combination means the user at one point had a Pet of that species+color combination, can we run a migration to fill in faded pets on the grid where users have Mounts and no pet?

**Comment by deilann** [comment]
Theoretically, yeah, I just don't know how to write that, so I didn't. :P

**Comment by colegleason** [comment]
I think that will end up being an annoying migration since it can't be run with an `update`. Could still do it in the mongo console or with a small script I suppose.

**Comment by ghost** [comment]
Just wanted to note that I have this issue too...

**Comment by deilann** [comment]
@cinnamingirl -- the fix wasn't retroactive. No one had it applied
retroactively.

**Comment by ghost** [comment]
Oh, yeah, I am aware, was just chiming in so that it wasn't just SabreCat having the issue.

**Comment by deilann** [comment]
But... it's not an issue. It's something we're aware of didn't happen for
anyone?

**Comment by ghost** [comment]
Never mind then, new here and was trying to be helpful, so thanks for being welcoming and forget I mentioned it.

**Comment by deilann** [comment]
No, you're fine, I just wanted to make sure you understood what was going
on? Everyone who hatched a mount before the Beastmaster fix has this
"issue." It wasn't a retroactive fix. So we know SabreCat has plenty of
company (he's also staff).

**Comment by Alys** [comment]
I'm pretty sure this doesn't happen any more.

**Comment by Alys** [comment]
If it does, let me know and I'll do the database migration.
