### ISSUE TITLE
weird day: dailies not reset, perfect day not awarded, no drops, strangeness in Trapper Santa quest

### ISSUE THREAD

**Issue by meganstrickland** [HabitRPG/habitica#2686]
After a long stretch with no problems, I was bitten by the [Dailies still checked from yesterday](https://github.com/HabitRPG/habitrpg/issues/1057) bug. I had checked all my dailies yesterday, and today all but one of my dailies was still checked and I did not get credit for the perfect day. 

Furthermore, my streaks were mostly gone. I did very little damage in my Trapper Santa quest, and my party received rather a lot of damage—almost as if the daily that reset was the only one that "counted."

Today (though I could be wrong because I wasn't keeping track at first), I'm pretty sure that I found zero drops, which gave me a sad. (I was really enjoying the unlimited drops of my recently purchased subscription. Drops are very motivating for me.)

I reset my custom day start to 0, and my day just ticked over as expected. Dailies have reset correctly and everything seemed fine... but I checked my Party tab and it says I did over 48 points of damage to Trapper Santa. I've never been able to get even half that much in one day before. I'm not exactly complaining about that part, but it seems like things have just gone wonky with my account and I have no idea what is happening. Halp?

UID: 73e5125c-2c87-4004-8ccd-972aeac4f17a

**Comment by meganstrickland** [comment]
Edited title to be more descriptive.

**Comment by lorian** [comment]
The streaks and damage issues are probably related to the dailies not unchecking issue; when I had that problem, I also did almost nothing to Trapper Santa (3 damage. 3 damage!) and lost a lot of streaks (because the game thought they were undone the previous day, I presume). I don't recall the uberdamaging next day, though, and I wasn't keeping track of drops at all at that time.

**Comment by meganstrickland** [comment]
Thanks, @lorian!

I've reset my CDS to 0 and things seem to be back on track. I guess I'll just keep an eye on the primary "dailies not resetting" issue thread and keep my CDS at 0 until there's news on that front.

**Comment by lorian** [comment]
Yeah, I've had to do the same with my CDS. Cross fingers, nothing weird has happened since!
