### ISSUE TITLE
Rogue Pickpocket

### ISSUE THREAD

**Issue by minicucumbers** [HabitRPG/habitica#2687]
I used pickpocket and it gave me a 25g bonus after the base 1g, on a blue task.
I refresh the page and it takes away 25g. 

Try again just to see, it takes away the 1g base after refresh instead of 25g bonus. 

ONE more time, and it took away 25g bonus again after refresh. 

(By the way, I didn't cheat my habits testing this :D) These were all bright blue tasks. I'm kind of bummed because now I'm pretty much out of mana and without 51 gold and some silver. Hmph. Here's my ID : 02b262de-d554-4d67-b501-9aacda518d93 I'm using google chrome.

**Comment by minicucumbers** [comment]
Also it took away exp bonus / base / bonus, in that order.. going with the gold removal.

**Comment by deilann** [comment]
It's related to this: https://github.com/HabitRPG/habitrpg/issues/2554

**Comment by deilann** [comment]
Also @colegleason -- this is what I'm talking about. Mana doesn't come back, but the rewards of spells do get taken away.

**Comment by elaseela** [comment]
I am sorry to reopen this, but I am fairly new to HabitRPG and I am having this problem as well.  I have learned that Pickpocket has no use other than wasting mana.  It removes gold, and sometimes exp.  Can this bug be fixed soon?

**Comment by Sciurus68k** [comment]
It looks like this bug still exists. After reloading the page the extra gold and experience is removed. Is it possible to reopen it or should I create a new Issue for this?

**Comment by deilann** [comment]
Are you clicking the button of a habit with it or the body? You need to
click the body. This is a known bug and has its own ticket, but I'm on
mobile and can't look it up.

**Comment by Sciurus68k** [comment]
Thank you for the fast response. I have tested it right now and it is working as expected when I click on the body instead of the button.
