### ISSUE TITLE
Dailies from yesterday that completed in evening still checked - and did not get credit yesterday

### ISSUE THREAD

**Issue by KatieSt27** [HabitRPG/habitica#2688]
Good Morning,

When I woke up this morning, I logged in to Habit RPG to figure out what to do first.  I noticed, to my dismay, that:
1.  I lost 20 hitpoints overnight and 
2.  suddenly the dailies I stayed up late to do are already checked for today (I should have had a 'perfect day' yesterday).  

It looks like I got credit for dailies that I did last night, today instead.  I finished the rest of my dailies around 23:40 EST last night.  I have not changed the custom start time (it is still 0).  I was using my iPhone browser (not app).

I also think I got a chunk of EXP I didn't earn this morning when this happened - as if I got EXP for yesterday's dailies in addition to getting exp from them today - but did not get credit for a perfect day and received hit points.

I'm less worried about losing health or exp, and just wishing i could get my 'perfect day' bonus and credit for my perfect day.  Oh, and have those dailies un-checked so I am motivated to actually do the dishes today.  :)

My user code is: aa87a105-5770-40a0-aa8d-cdf74973b912

Thanks!

ps - thanks so much for this program - I am really enjoying HabitRPG and find it extremely motivating (hence finishing my unhappy dailies like 'cleaning,' 'dishes,' and (worse) 'cat litter' at 11:40pm.  :)   I only started earlier this week, but am already recruiting my friends.

**Comment by KatieSt27** [comment]
Update - I used the "Fix Character Values" section to fix almost everything.  The only thing that would be nice to fix it to have my perfect day achievement there as well.  (the perfect day bonus would be nice of course).

Thanks again for the great game!  Seriously...what else could get me to do the dishes at 11:25 at night, after getting home from work at 10:30pm?  :)

**Comment by adalina** [comment]
I just had a similar problem. I haven't changed my custom cron time or anything. I reloaded Habitrpg after midnight, expecting to get a perfect day, but instead lost 11.9 hp and I believe I gained exp and gold too (but I was a bit too confused at the hp loss to notice). This is not the first time this has happened.

**Comment by adalina** [comment]
Oops, forgot the id: f327bfcc-6cbb-4277-b0d2-1a2e2788e3cf

**Comment by deilann** [comment]
This should be followed here: https://github.com/HabitRPG/habitrpg/issues/2601
