### ISSUE TITLE
(Now resolved?) Error when ending challenge, now in limbo with daily still active

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#2692]
I ended a challenge just now (Conquer Your Castle Clutter) and chose a winner, but got a 503 error (or possibly it was the other kind of error that keeps happening the last few days, not sure what that one is called). I tried again to choose a winner but got the same error. Then I refreshed the page, and my challenge had disappeared from the challenges list. I refreshed my tasks page and looked at the daily associated with this challenge, and it does **not** have a red box signaling that the challenge is over.

I've left a message for Roberta (the winner) in the tavern asking whether the challenge prizes have shown up, but I'm guessing maybe not, since no winner is listed with the daily. I can work around that, if I hear back from Roberta. (Create new challenge with same name, Roberta joins, declare Roberta the winner. I'd have to put up 4 more gems since the ones from the original challenge disappeared, but that's not too big of a deal.)

A much bigger concern is that I can't delete the daily or even edit it to deselect days. There were 300+ participants in the challenge and if none of them can get rid of the daily, that's quite a problem. Any suggestions about that?

**Comment by hattieshoe** [comment]
Update: Now the red box is showing up and I have been able to delete the daily. So I guess it's not an issue, just a scare. It was probably 30 minutes before it got resolved, so I don't think I was just irrationally panicking! Maybe once the constant errors are cleared up, it won't happen to anyone else.

**Comment by deilann** [comment]
Thanks @hattieshoe !

**Comment by Joy2b** [comment]
Ah, this is one of the dailies I haven't been able to delete.  Thanks Hattieshoe for mentioning it, I was wondering when that challenge ended.

**Comment by hattieshoe** [comment]
Joy2b - Are you still not able to delete it and still don't have the red box that tells you who the winner was? Then there may be others who were in the challenge who have the same problem. @deilann - tagging you to make sure somebody sees that this may not be resolved after all.

**Comment by deilann** [comment]
Indeed, please let us know @Joy2b

**Comment by deilann** [comment]
However, actually, this is probably better followed at https://github.com/HabitRPG/habitrpg/issues/2763 or https://github.com/HabitRPG/habitrpg/issues/1915, where @Joy2b also commented, so this will remain closed
