### ISSUE TITLE
Vice quest scroll not being given out to high-level characters?

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2694]
I was under the impression, based on Trello comments, that everyone above a set level would receive a copy of the Vice scroll for free, and only have to purchase extra copies:

Lemoness: "What I am advocating is that any quests that provide stat-boosting equipment, like Vice, drop one time AUTOMATICALLY at a certain level. (Tyler, this is answering your question, I hope!) So the minimum level for Vice would no longer be just a stat - at level 50, congratulations! You get a Quest Scroll for Vice. It would also be available in the Market in case you wanted to do it again."

However, that does not seem to be what has happened; the Vice quests are only available through the market, same as the egg quests. Is that the final decision on the topic; all quests will be market-only?

**Comment by deilann** [comment]
Lorian, are you _above_ level 50? It may be that nothing was run to make sure characters who have already passed when the scroll would drop will get it.

**Comment by lemoness** [comment]
I also got no Quest scroll. I think that the people higher than 50 did indeed get overlooked.

**Comment by lemoness** [comment]
That is to say, it's in the item store - but it was supposed to drop automatically for people as well.

**Comment by lorian** [comment]
That was my thought, actually; I'm level 80, so well past any natural drop
points.

**Comment by DanielTheBard** [comment]
Was wondering about this. But since I rebirthed and I'm lvl 10, I wasn't really sure.

**Comment by lemoness** [comment]
Oaky, did you guys have Bailey pop up with the announcements? Because she didn't for me. I had to click "show bailey." And it looks like the level has been lowered to Level 30?

@lefnire?

**Comment by patena** [comment]
No Bailey for me!  No scroll either. I'm level 35, so if it was lowered to 30 I should have one, right?

**Comment by deilann** [comment]
Actually, that would be exactly the problem. XD Everyone above whatever the
requisite level wasn't given one.

**Comment by lorian** [comment]
Hmm, I had Bailey show up yesterday about the robes etc, but not today.

**Comment by deilann** [comment]
Yeah, clicking "Show Bailey" just gave me the message about Vice which did
not show up for me on its own.

**Comment by JennaMalkin** [comment]
Is this ongoing into the future?  (if I reach level 30 in a month's time, will I get a free quest scroll?)

**Comment by deilann** [comment]
The issue is that people beyond thirty (who don't trigger the drop) didn't
get their scroll. There should be no issue if you hit thirty in a month's
time or tomorrow or in a minute.

**Comment by lemoness** [comment]
Ah, what about the Bailey Announcement, though?

**Comment by lefnire** [comment]
ran script, pushing code now

**Comment by colegleason** [comment]
Thanks!

On Sat, Feb 1, 2014 at 6:25 PM, Tyler Renelle notifications@github.comwrote:

> ran script
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2694#issuecomment-33888004
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by lefnire** [comment]
@colegleason so I tested this on beta, there was server lag and I got 4 vice drops; two notifications. Reset, tried again, 1 drop. So server lag definitely causes action duplication. I'm still not sure if it's duplicate http requests, or the ops being duplicated in one http call on the server. My hunch was multiple http calls, because the notification showed twice, and `user._tmp.drop=...` is assignment, so it would have overridden and only shown one. But then again, `$scope.$watch('user._tmp.drop')` will pick up browserify'd `user.fns.updateStats`, so that might defeat the theory.

Anyway, just more thinking-out-loud

**Comment by colegleason** [comment]
Could the `user.fns.updateStats` have set `user._tmp.drop` on the browser, then cleared it in the `$watch`? Then the HTTP response could have come back form the server which set `user._tmp.drop` again?

I dunno. It's all very confusing.
