### ISSUE TITLE
Filter for not-tagged?

### ISSUE THREAD

**Issue by kenfink** [HabitRPG/habitica#2695]
Is there a way to filter for entries that are not-tagged?  For example, I have an "active" tag, and need a way to see a list of entries that do not have that tag.

If not, could this be added to the feature request list?  It could be implemented by making the tags a three-way toggle - off, on, not.  
Untagged would be easily handled this way, but making all tag filters "nots."  More elegant would be an "untagged" tag.
##

**Comment by patena** [comment]
This would be awesome - both for "not tagged at all" entries, and "not tagged with X" ones.

**Comment by lorian** [comment]
Yes, this would be fabulous, for both. I would LOVE to be able to see the inverse of a tag, as well as all the poor, unloved, untagged tasks.

**Comment by kenfink** [comment]
Ironically, I can't figure out how to tag this thread with a "tags" tag, so it gets seen in the right place.  This seems like a potentially simple mod with few implications for UI design, which would add a ton of functionality.  Not sure how I can help, but I'd love to.

**Comment by deilann** [comment]
@kenfink You can't tag it! But I can.

**Comment by wc8** [comment]
:+1: for a three way tag filter: 
- _white/clear_ (OR/doesn't matter), background (as current)
- _blue_ (AND/has tag), solid background (as current)
- _red_ (NOT/does not have tag), UPDATE: or red with transparent slashes like Trello colorblind mode labels
- and an untagged filter. 

For active/inactive my current _workaround_ is to use two tags `:unlock:` = _active_ and `:lock:`= _on hold/inactive/deferred/someday/maybe_. Every once in a while I review the lists via mouseover of the tag icon to make sure that my tags have either :unlock: or :lock: tags.

**Comment by deilann** [comment]
Please do not use colors to designate anything more on the site. It's bad
enough as it is.

**Comment by wc8** [comment]
Hm... how about red with the transparent diagonals /// through it, similar to Trello's colorblind mode?
(Nix on the grey—I meant white, clear, the current method).

**Comment by deilann** [comment]
I can't speak for people with trouble with red (I'm blue-deficient) but if
the grey is gotten rid of, blue isn't as much an issue. Grey and blue can
often seem the same for me. Granted, I have issues distinguishing between
the light blue habits and the grey habits (it's completely
indistinguishable for me on mobile) so I could only imagine it would be
nearly impossible to see on mobile. I'd imagine red would desaturate for
someone with a red deficiency similarly, too.

/// on red would help protans, but it would still leave folks like me
without a paddle. If the blue was marked, that would also be good.

**Comment by wc8** [comment]
Alternative visual proposal
1. Include items with Tag = **Blue Highlight** (current)
2. Exclude items with Tag = **Red Outline with a slash** similar to :no_entry_sign: 
3. no filter = blue text-on-white (current)

@kenfink [Unofficial Tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html#) includes a tool to list untagged tasks

**Comment by deilann** [comment]
I _think_ that would work for most color deficient folks. The blue
highlight isn't important to me (I was kind of aware that it's blue, but
couldn't tell you it was blue without going and looking and making sure)
but if I've got a visual cue of "highlighted" and "highlighted with slash,"
I'll be able to tell them apart. I'd imagine that red deficient folks will
be fine as well, as they'll be able to go "welp, it's got slashes and
therefore is excluded"

**Comment by breadstrings** [comment]
~~As an aside but relevant to this topic suggestion, can we have an "OR" or "NOT" function on tags? Currently, if you select more than one tag it acts as an "AND" function. I'd love to select multiple tags at once, so I don't have to see certain tags that aren't relevant to my day. For example, I'd like to only see my "school" or "home" tags at the same time (with tasks that aren't tagged with both tags!), but not see "wiki" tags on weekdays.~~

~~Did that make sense, or did I just confuse everyone?~~

Nevermind, I just read wc8's post above. XD

@wc8 - what about having just the words "AND", "NOT", "OR" on a dropdown menu (or could make it a toggle icon) for each tag? That way we don't have to worry about colours. And then putting that as an advanced feature on the HabitRPG settings page (so as not to confuse our newbies)?

**Comment by lemoness** [comment]
That's actually been requested before on the main Trello. We'd have to find
a clear way to do it, though.

**Comment by Memry** [comment]
It should be a fairly simple item.  The code that select by tag should have a simple not selector capability.

**Comment by Alys** [comment]
I've linked this issue to the tags feature request card (https://trello.com/c/HzlNeTQB/274-tags-v-2-tag-ideas-enhancements ) so I'm closing this. We'll assess these ideas at the same time as the other suggestions on that card.

**Comment by texastoland** [comment]
I'm interested in implementing this?
