### ISSUE TITLE
Opted out of classes

### ISSUE THREAD

**Issue by SpocketWrench** [HabitRPG/habitica#2696]
When I hit level 10 two days ago and got the "classes unlocked" prompt, I didn't have time to go decide which class I wanted. The phrasing in the pop-up made it seem like if I opted out, I could go back and choose my class later, so that's what I did. Later, I couldn't find anything on my profile about my class, and when I went to the wiki it said I can only change my class with gems (and that there would be a future change to the feature.) 

Is it possible for me to opt back in to classes somehow? I would really like to be a rogue.

**Comment by marcelosizer** [comment]
Go to settings > settings
![optin](https://f.cloud.github.com/assets/6205335/2058746/3f0701fc-8b82-11e3-9c52-a6744cf31665.png)

And then click on **Enable class systems**, the last option here.

![optin1](https://f.cloud.github.com/assets/6205335/2058749/4eaac06c-8b82-11e3-9236-f26a077ab085.png)
^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
