### ISSUE TITLE
unexpectedly died in the morning of my day!

### ISSUE THREAD

**Issue by EmmaLK** [HabitRPG/habitica#2697]
HI
user name Emma_K
User ID: 0d9bc3ef-4d1d-4ce6-a38b-549220315be1
i was in the morning of my day (8am here in Australia) and was pottering around in habitrpg, my life was a little low due to bad habits, but i have done all of my dailies everyday for 3 weeks now - i have never gone to bed without completing them all.  in the middle of doing something a notice came up telling me i had died.  i lost over 300 gold, all of my experience, my streak and my weapon. i want them back please.  i have been working really hard, and i want all the hard work to show - this is important.  
 i have not messed with the time in the game - i understand that this feature is buggy so have stayed away from it.  i was just doing what i do everyday - completing my dailies.  
please fix this.

**Comment by benjjk** [comment]
Hello

User ID: e4a6340b-909e-43d2-9768-5df8358a51b5

My username is benjjk, husband of Emma_K and in the same party. I've had a similar experience this morning. I died unexpectedly, despite having completed all dailies yesterday. 

However this morning many of my dailies have somehow already been marked as completed. Last night (about 11:00pm local time) I entered a new daily and two new habits, and it seems they have both duplicated.

I did have over 600 gold that I was looking forward to cashing in this week! Any help will be appreciated!

Thanks

**Comment by deilann** [comment]
Fear not, folks. If you go to your [Settings Page](https://habitrpg.com/#/options/settings/settings) and click "Fix Character Values" you can renter all the gold and XP you lost. You can manually reset any streaks under advanced options in your dailies. Obviously, this needs to be looked into, but at least you can fix your account. :)

(You can't fix back your weapon, but if it's the same class as you, you can give yourself the extra gold needed to purchase it.)

**Comment by EmmaLK** [comment]
Thank you for this! 
You're marvelous! 
Good luck with fixing everything! 

Sent from Samsung Mobile

-------- Original message --------

**Comment by deilann** [comment]
Also, this can be followed here: https://github.com/HabitRPG/habitrpg/issues/2116
