### ISSUE TITLE
deleteable accounts

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#27]
_Edited by wc8: Vote for this feature here: [Delete Account Option](https://trello.com/c/ezd4YkAS)_
I don't see any delete account button. I would appreciate it very much if my account was deleted. I love the idea. I just don't want my e-mail stuck on something I can't take off.

**Comment by loldude101** [comment]
I also want this. I have accounts with hundreds of duplicates on them (due to the recent bug) and I want to have the ability to delete them so I can register again using the previously used username (main one, I use it for all accounts).

**Comment by horusofoz** [comment]
Not planning on deleting any time soon but a must have feature especially for the privacy minded

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.
