### ISSUE TITLE
Leftover Cake

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2700]
Cake is still dropping randomly for people.

**Comment by patena** [comment]
Yeah, I got some early this morning. (I didn't actually see it drop, but it was there in my inventory, probably due to rollover bug weirdness.)

**Comment by lefnire** [comment]
People have 2 of some? Or they use it and it's back or something? Could be
people are unlocking the inventory and discovering late

**Comment by patena** [comment]
I used all but one of mine yesterday (I did have a full set, I think) and got several more today - I definitely had doubles, I remember them. And my friend says she actually saw one drop.

(It seems to have used up my normal daily drop quota for today, though, if that matters.)

**Comment by deilann** [comment]
I definitely got a strawberry cake dropped this morning. I didn't get any cake drops on the 31st due to bad cron timing, so it was pleasant. (I did still get my inventory cake, though.)

**Comment by lemoness** [comment]
Nope, I've actually been seeing them drop along with the normal food.

**Comment by lefnire** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/commit/1b36425099b7578bc9c2c7ec4e276439186f5d5d , will go with next push
