### ISSUE TITLE
Lost January mage robe

### ISSUE THREAD

**Issue by patena** [HabitRPG/habitica#2702]
I am pretty sure I bought the entire limited Mage set last night, and now the robe is missing from my inventory!  I also had a ton of cron bugs (lost a level, some health, a lot of xp, a lot of my dailies were still checked the next day and I had to reset a few streaks; I have a 6am custom day start), so I'm guessing it might be part of that.

I am 99% sure that I bought it: I remember calculating that I had enough money for the whole set yesterday, and I have a screenshot from 6 min after midnight showing that I only have 16 gold left (that was before the bugs set in), so I did spend it. I even closed the Mage tab that I had been keeping open to remind myself about the apparel. 

Is there any chance of someone checking what happened or giving it back to me? :(

**Comment by deilann** [comment]
I can't fix this, but I can say that your UUID will be needed if someone can get around to fixing it! So if you could post that here, it would be greatly appreciated.

**Comment by patena** [comment]
Good point, thanks! 28493c5d-00bb-4bc0-a471-9c4b40c9e642.

**Comment by bntracy** [comment]
I am losing equipment as well :( I bought the Yeti-Tamer Robe on January 31. A day or two later, it was gone from my equipment, but back in the store. So I purchased it again, and I started checking every morning to make sure my gear was what I thought it should be. (As a side note, I've been dying a lot, and I noticed the equipment the pop-up says I lose and the equipment I actually lose are often different.) This morning, things looked fine. A few minutes ago, I noticed the Yeti-Tamer Robe back in the store, along with the Absurd Party Robes. Now, I can buy back the party robes, but that yeti-tamer gear's expensive!

User ID: b308b2ae-5448-415b-850b-96ba3272c71f

**Comment by patena** [comment]
That's different from my case - my robe isn't back in the store at all. :(

**Comment by Felinar** [comment]
I bought a camouflage hood and it disappeared.  Took my gold, too!  D:

User ID:  9cd6aa49-0cc8-4f6a-8719-8feb2f91dcd7

**Comment by Alys** [comment]
@patena : I have given you your missing Candy Cane Robe. I am sorry about the delay! Check your inventory and you should see it there. You might need to reload first using your browser's refresh button. I'm closing this job now, but if it doesn't show up, comment here and I"ll reopen it and fix the problem!

@bntracy : Your situation was a bit different. One of the side-effects of [death](http://habitrpg.wikia.com/wiki/Death_Mechanics) is that you lose a piece of equipment as part of HabitRPG's mechanism for trying to motivate you to do the daily tasks that you have set for yourself. You can always buy back equipment that you lose through death, even if it is no longer available to new players. You would need to change to the correct class if the equipment is for a class that you are no longer playing.

@Felinar : I see that you were able to regain the hood.

**Comment by patena** [comment]
@Alys Great, thanks!
