### ISSUE TITLE
I made a sword.

### ISSUE THREAD

**Issue by infinidulge** [HabitRPG/habitica#2704]
This was just one sword I made as pixel art. This is my first attempt. If you want, I can create multiple types in the future and just submit it all together, instead of individual items. Thanks!

Infinidulge;
e34e7804-579f-4bf2-81b8-c8ae2c396675
![sword](https://f.cloud.github.com/assets/6565486/2059628/b26602a2-8bc2-11e3-8dfc-ca9e85eb3718.png)

**Comment by lemoness** [comment]
Hey Infinidulge! 

So, the Pixel art Trello is almost ready - I'm hoping to have it done Sunday or Monday. We'll have some better guidelines there. The sword and colors are very nice, but it doesn't actually fit our specifications, in that it will not fit with the avatars. But! I think it's a very cool concept, so when the Trello board is open, I'd encourage you to go check it out and make a new one that fits the specifications!
