### ISSUE TITLE
habits no longer trending back to yellow?

### ISSUE THREAD

**Issue by meganstrickland** [HabitRPG/habitica#2706]
I have many +only habits which usually get clicked once a day at most. In the past, they have generally "reset" to yellow after a day (or maybe two or three if I clicked it more than once and they need to fade from blue to green to yellow), but it seems that they are no longer resetting. Am I imagining things? Is this just me? Is it intended behavior?

**Comment by lorian** [comment]
For what it's worth, I definitely had several habits that I had clicked on once yesterday, return to yellow. So if it's broken, it's not for everyone.

**Comment by meganstrickland** [comment]
Thank you again, @lorian! My habits seem to be trending back to yellow again, so perhaps it was related to all my other weirdness #2686 and/or the dailies not resetting issue #1057.
