### ISSUE TITLE
Users Under 30 Can Buy Vice

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2707]
Hey!

So, it's come to our attention in the Tavern that users who are under Level 30 have been excitedly buying all three Vice quests for gems, and then discovering that they can't use them. Obviously, this is problematic, because 1) they can't use them, and 2) they'll be getting the quests for free at 30 anyway, so it's a waste of their gems. Of course, they can buy to replay, but not everyone will choose to do that.

So, I think that users under level 30 should not have the Quests in their stores, or they should all be locked.

**Comment by lemoness** [comment]
Forgot to tag @lefnire @colegleason and @paglias.

**Comment by deilann** [comment]
[This](https://github.com/HabitRPG/habitrpg-shared/pull/126) warns users about it, at the very least. I tried to set canBuy based on level, but my local repo has been broken since doing a pull earlier today, so I can't test it.

**Comment by colegleason** [comment]
@deilann We both added fixes. Awkward.

They won't see your warning with my addition.

**Comment by deilann** [comment]
Yeah, I closed mine.

**Comment by colegleason** [comment]
Cool, I hope you don't mind. Would you rather have a warning instead of locking it? I fear people won't read all the text before buying.

Maybe for dropped quests we should only display it in the store if you have already completed it.

**Comment by deilann** [comment]
I'm torn both ways. I too fear that people won't read all the text before
buying. I'm also afraid that someone might not realize they got a free
version of the quest upon hitting level 30 without some statement of it.

I was going to implement a "can't buy" and a warning, but my local is
seriously messed up since updating it today. Don't know what is up.

I do like the idea of not setting canBuy:false, but letting them know it's
a thing that exists.

**Comment by lemoness** [comment]
I think that making it so that users cannot buy the quest will be the
safest bet. In theory, when you hit level 30 a giant pop-up will tell you
that you unlocked the Vice Quest, like with Unlocking the drop system,
Classes, etc. @colegleason is that not the case?

**Comment by colegleason** [comment]
@lemoness I'm not sure you get a popup. It might just be a drop like an egg or a hatching potion.

**Comment by lemoness** [comment]
Oh -  no, that is WAY too easy to miss. It should definitely be a pop-up.
Frequently drops load so slowly that I don't even see them, or I'm not
looking, or I'm clicking lots of things at once.... pop-up is definitely
the way to go.
