### ISSUE TITLE
Boss Damage Incorrect?

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2709]
Vice's Shade has a STR of 1.5

I took 13.3 damage this cron.

The party took 5.7 damage.

This does not add up in a logical way. It appears my dailies did me MORE damage than Vice's Shade.

**Comment by colegleason** [comment]
I'll have to do more research, but I think constitution is not taken into account for boss damage as it is for missed dailies.

https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L814

**Comment by deilann** [comment]
Either way, the boss should be dealing _more_ damage than my dailies, not
less.

**Comment by deilann** [comment]
Took 9.3 total damage today. Boss dealt the party 3.9 damage. This really seems off. Boss is once again dealing less damage than my dailies on their own.

**Comment by colegleason** [comment]
Can you screenshot or otherwise record your stats yo help with debugging
the math?

**Comment by deilann** [comment]
Yeah. However, I think I might have found the issue:

`hpMod = delta * conBonus * task.priority * 2 # constant 2 multiplier for better results`

Is that 2 being used for bosses as well?

**Comment by deilann** [comment]
Stats:

Constitution (CON): 23  

```
Level: 23 
```

Intelligence (INT): 100.5   

```
Level: 23 
Equipment: 24 
Class Equip Bonus: 7.5 
Allocated: 46 
```

Perception (PER): 40.5  

```
Level: 23 
Equipment: 14 
Class Equip Bonus: 3.5 
```

Strength (STR): 23  

```
Level: 23 
```

**Comment by colegleason** [comment]
No, it doesn't seem like that variable (hpmod) is returned. I think boss
just uses delta.

**Comment by deilann** [comment]
That would perfectly explain it. My dailies hit me for 5.4. Half of that is 2.7. 1.5 of that is 4, close to that 3.9.

**Comment by deilann** [comment]
It works out perfectly for the first day, too. Dailies are doubled, boss damage isn't.

**Comment by colegleason** [comment]
Yeah, quest progress only uses delta:

```
delta = user.ops.score({params:{id:task.id, direction:'down'},
```

query:{times:scheduleMisses, cron:true}});

```
        user.party.quest.progress.down += delta if type is 'daily'
```

The question is, should this be changed?

**Comment by deilann** [comment]
I think it doesn't make sense for bosses to deal less damage than your dailies do normally. And I believe that wasn't the intention. But idk, I think people might get upset if bosses start dealing more damage.

**Comment by DanielTheBard** [comment]
@deilann - Boss battles might start becoming way harder. Hmm. While, I personally may prefer that... Idk. That means there's some days that my party absolutely should have got me killed on a boss battle.

**Comment by deilann** [comment]
@DanielTheBard That's kind of exactly my point... I feel like boss battles have no impact right now if missing five of my dailies does three damage!

**Comment by SabreCat** [comment]
What would happen if we upped the boss damage, but allowed CON to play a part? It seems weird that boss attacks cut straight through your defense, no matter how tanky you are.

**Comment by deilann** [comment]
I think the issue with CON taking a part is that everyone's CON in a party
is going to be different. So the "dealt the party X damage" would have to
be pre-CON, if that were implemented.

**Comment by SabreCat** [comment]
@DanielTheBard: The whole point of bosses is that if you screw up, you get your party members killed. Better make sure you've partied up with people who don't enjoy that sort of thing... ;)

**Comment by SabreCat** [comment]
@deilann: Aye, that's what I was thinking.

**Comment by crookedneighbor** [comment]
Since this is stale, I'm closing this, but if anyone wants to work on this, please re-open it.
