### ISSUE TITLE
I am not doing any boss damage

### ISSUE THREAD

**Issue by MichelleSvenson** [HabitRPG/habitica#2710]
I recently joined a new party (2 days ago) and they were half-way into defeating the trapper santa. I have been completing dailies and to-dos but I am not doing any damage. I am not sure if this is a bug, or if I am just unallowed to join a boss fight half way through?

**Comment by deilann** [comment]
You are unallowed to join a boss fight half way through. If you join a party during a boss fight and want to join in, they have to abort and restart the quest. This doesn't lose them the scroll, but it does lose all their progress.
