### ISSUE TITLE
Tasks automatically being checked off

### ISSUE THREAD

**Issue by ChewieKittie** [HabitRPG/habitica#2712]
When I open the game for the last two days, about half of my daily tasks have already been checked off as though I completed them.  It also keeps resetting the streak counters on those tasks.  And for two of the tasks it changed the days of the week for which I wanted them done.

**Comment by lorian** [comment]
Dailies not resetting is unfortunately a known issue that's been around for a while; see issue #1057 for a discussion of it. Were you using custom day start, or does your day still start at midnight?

**Comment by ChewieKittie** [comment]
My day starts at midnight.  And it isn't so much they aren't resetting....it is that they are auto checking off.  Because some of them that are checked off are ones that are due only on specific days.  Like a Friday only.  And when I open Friday....it is checked off like I did it.  Is that not resetting?  Idk?  It confuses me.  :/

Date: Mon, 3 Feb 2014 08:52:59 -0800

**Comment by lorian** [comment]
Huh, so dailies you DIDN'T do the day before, are checked off when you reload the next day? Ok, that's definitely a bug I haven't heard of before.

**Comment by ChewieKittie** [comment]
It happens sporadically.  And it randomly changes the days of the week I want to do dailies on.  eg.  A task I have set for Sundays only will suddenly be due on Mondays.  Or a task I have set for Mondays only will be set for Fridays and also checked as though I've done it when I open the game on a Friday.
It did it to me Friday, Saturday and Sunday but everything was fine this morning.  

Date: Mon, 3 Feb 2014 14:01:14 -0800

**Comment by squirrel7** [comment]
I had a similar issue this morning - never happened to me before. I have four dailies that were checked off this morning that should not have been - I guess they didn't reset over night. These were four that I had checked off yesterday, but everything else checked off yesterday was unchecked as usual. I do not have a custom day start set or anything. If I need to put this in a different thread, please let me know...

**Comment by stormyhearted** [comment]
I'm also having this issue- today and yesterday, though it's happened sporadically in the past. I do use a custom day start.

**Comment by MrSmearkase** [comment]
I can also confirm this issue. I completed all of my dailies yesterday, but when I woke up, about half had been reset, and half had not. I do use a custom day start at 6 am. As another user said, I am also seeing my streaks reset when they should not.

**Comment by deilann** [comment]
We're not positive about CDS having anything to do with this entirely. So if this could be moved to https://github.com/HabitRPG/habitrpg/issues/1057 that would be awesome.
