### ISSUE TITLE
Tags disappeared upon dying

### ISSUE THREAD

**Issue by heatherjmitchell** [HabitRPG/habitica#2719]
Hi,
Last night I put in a bunch of new tags. I tested them to make sure they worked. Today I died, and my tags weren't there anymore. I asked about this in the Tavern, and someone said to report it here. I've since put my tags back today. Looks like a bug to be fixed, though, and not user error. 
Here is my User ID:  9e0ce54a-c111-45a8-b20e-6934cb79f596

**Comment by deilann** [comment]
Probably related to this: https://github.com/HabitRPG/habitrpg/issues/2370 not death. Follow there.
