### ISSUE TITLE
Spontaneous Character Restart

### ISSUE THREAD

**Issue by tedar2006** [HabitRPG/habitica#272]
So, I logged in today to update my character and it turned out that my level 6 character with a morning star is now a level 1 with a simple sword. This would be ok, however all of my habits, dailies, and to-do have also restarted to default. I thought, perhaps, it was a program-wide wipe, however, my friends have still retained their progress. My second thought was that I had died, except that the last time that I had logged in (yesterday) I had 48/50 hp. Is there any explanation for the spontaneous wipe?

**Comment by TrevorJin** [comment]
I had it happen to me as well.

**Comment by horusofoz** [comment]
Can you advise if this is still happening and your timezone please?

**Comment by tedar2006** [comment]
Just checked again and turns out all my stuff is back! That was a little scary. I am on PST [California, USA]

**Comment by horusofoz** [comment]
@tedar2006 Similar thing happened to me. Appears to be bugs related to timezones.

@ph201 Can you confirm you're restored?

**Comment by Pandoro** [comment]
Great! This is very good new I guess! Hopefully this is working for everyone. Thank you for the quick work @lefnire , do you have any idea what could have really caused this thing to happen?

**Comment by lefnire** [comment]
not the same issue as #268?

**Comment by TrevorJin** [comment]
I am restored.

**Comment by Pandoro** [comment]
This seems to have been fixed by @lefnire. Closed until further cases occur.
