### ISSUE TITLE
perfect day on saturday, woke up "dead" on sunday

### ISSUE THREAD

**Issue by kiss-the-fiddler** [HabitRPG/habitica#2720]
Hi.  I had a perfect day on Saturday, 2/1/14.  Completed and ticked off all my dailies.  Logged on Sunday to a "you died" notice and didn't receive any "perfect day" buffs.  Frustrating because I worked so hard.  And I lost my helmet which is now unavailable to buy again.  Grrr . . . 
User ID  57710bfb-f220-49c8-a37e-9b8aa7a01589

**Comment by lefnire** [comment]
let's follow on https://github.com/HabitRPG/habitrpg/issues/2675
