### ISSUE TITLE
Habit name starts with +, boxes obscure markdown

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2721]
If the name of a habit starts with a +, the name displays as input, without the initial +.

**Comment by sigod** [comment]
Wow! Just find out that markdown works in habit's names.

Actually, + (plus) is displaying like a little circle and it hidden by +/- signs:
![screenshot 2014-02-11 02 42 06](https://f.cloud.github.com/assets/1175750/2132278/197e5ee4-92ad-11e3-8a98-4f7fb4207087.png)

**Comment by deilann** [comment]
Ah, right, didn't even think of the markdown implications. Lemme change the title.

**Comment by negue** [comment]
Workaround would be using a backslash: `\+`

all + / - signs are being interpreted as list item, so it is being transformed to this little circle.

**Comment by crookedneighbor** [comment]
I assume you don't actually want to mess with the markdown being created, so is this the desired look?

![screen shot 2014-12-05 at 5 07 04 pm](https://cloud.githubusercontent.com/assets/2916945/5324537/2dcb3c4e-7ca1-11e4-8fa2-77d93d41d56e.png)

**Comment by negue** [comment]
I think the desired look would be this

![2014-12-06_00-14-44](https://cloud.githubusercontent.com/assets/842273/5324612/fd076542-7cdc-11e4-8214-61fb609eef78.png)

**Comment by crookedneighbor** [comment]
Well, the question is do we want the markdown for the list to not be parsed in task titles (this affects all kinds of tasks, including rewards)?

@deilann's change of title suggested that it should be rendered as markdown, but not be obscured by the buttons.
