### ISSUE TITLE
No spells available

### ISSUE THREAD

**Issue by siozosdr** [HabitRPG/habitica#2722]
I have picked the wizard class and about a month ago i could no longer see my spells. I am level 10 now and i still have no spells available to cast.
Please help!

**Comment by wc8** [comment]
Spells are released one per level through 11, 12, 13, 14, as I recall.
See http://habitrpg.wikia.com/wiki/Skills

**Comment by Cecron** [comment]
So what can I do at level 10 when I get Mana?
This wording confuses me "Mana unlocks at level 10 and allows players to use skills"
(I'm assuming OP's spell == skill)
http://habitrpg.wikia.com/wiki/Mana

**Comment by deilann** [comment]
At level 11 you will unlock your first skill. There are four.
