### ISSUE TITLE
Username not found

### ISSUE THREAD

**Issue by LyneaLennox** [HabitRPG/habitica#2723]
I have tried to login, and the username says it isn't found. I get a new password sent to me, and using that and the username in the email, I have tried countless times, and each time it doesn't work.

**Comment by deilann** [comment]
@lefnire Any thoughts on this?

**Comment by lefnire** [comment]
@LyneaLennox take a peek at http://habitrpg.wikia.com/wiki/FAQ#Username_and_email_not_recognized first

**Comment by deilann** [comment]
If you still need help, please reopen this ticket. :)
