### ISSUE TITLE
login with username and password api not documented on swagger; improvements needed for third-party logins using uuid and token (temporary tokens? oath? etc?)

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#2724]
Trying to figure it out.  I found the modal, but that doesn't help me much.  https://github.com/HabitRPG/habitrpg/blob/develop/views/static/login-modal.jade
##

**Comment by fragmental** [comment]
Heck yeah.  Figured it out.   The number "200" never looked so sweet.  I used https://github.com/HabitRPG/habitrpg-mobile/blob/7c7e70fa4ab1d4f19726d2d01a306192b51ad931/app/scripts/controllers/authCtrl.js to help me figure it out.  Don't know if I'll ever get rid of this migraine though.  Was that some kind of a competency test?

**Comment by colegleason** [comment]
I really think we should restrict username/password auth to the web client. Sharing that info with third parties is not ideal.

**Comment by fragmental** [comment]
How is an user id and and api token better than username and password?  If
I had to guess, I would say that a username and password are easier to
guess than a uid and api token?

**Comment by fragmental** [comment]
Anyway, I defer to your expertise on the matter.  However, if you consider
me a third party, that ship has sailed, because I already have it working.

Still not exactly sure what to do about facebook auth yet.  Probably just
simulate the way the mobile app(used to?) works, and switch the uid/token
mode for facebook auth.  But now I'm getting off topic.

**Comment by paglias** [comment]
We have two options here, I believe, considering that we should definitively change how it works now:
1. Remove CORS for the `/api/v2/user/auth/local` route and others related to it so that we can still use them for mobile apps but not from thirdy party websites. Which I believe is how other apps do when it comes to mobile apps. But it still enables web servers, desktop to access the route without problems. And use OAuth for 3rd party apps (but how can we enforce the non browser-based ones to use it and not the traditional route which should be `private`)
2. Use OAuth for everything execpt that for the main site

**Comment by paglias** [comment]
About api tokens and uuid I think how they works actually they are not much safe than username/password. They would be safier if, logging in with username/password or with a strategy similar to OAuth returned only a temporary api token which must be used for all the requests, with an expiration date, a refresh token to get a new api token and the possibility for users to see authorized apps and in case to invalidate their access

**Comment by deilann** [comment]
Using UUID/API reduces the possibility of phishing for passwords, damaging the security of people who use the same username and password for multiple sites. So if I could get someone's Habit username and password, I could go say, see if they had a Wells Fargo account with the same details.

**Comment by lefnire** [comment]
We gotta remember thought that our mobile app is using the uname/pw routes, so whatever direction we take we'll want to make sure our app is still supported

**Comment by colegleason** [comment]
Another idea with UUID/API token is that maybe logging in with an API token
would limit what you could do. Additionally, maybe there could be a concept
of revoking an API token.

I like Oauth better though.

On Tue, Feb 4, 2014 at 12:05 AM, Tyler Renelle notifications@github.comwrote:

> We gotta remember thought that our mobile app is using the uname/pw
> routes, so whatever direction we take we'll want to make sure our app is
> still supported
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2724#issuecomment-34033379
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by deilann** [comment]
Perhaps something similar to EVE Online's API system? You generate a code,
give it rights, and decide if it expires? Then, if so desired, you can
delete it.

**Comment by fragmental** [comment]
Entering uid and api key on a mobile app can be a big pain.  I know how to
copy and paste on my android and that makes it easier, but not everyone
knows how to do that.

**Comment by fragmental** [comment]
@deilann good point about the phishing, though.

**Comment by tmas** [comment]
I like the idea of having a web UI to show what third party apps have access to the account. The secure way to do that would be to provide a unique API key to each application to identify it properly. The easy way to implement that would be to have the UI generate keys and assign certain perms to them, but it'd be much more user friendly if the application could ask for permission based on the username and the user could then accept or reject the request in the web interface.

**Comment by Alys** [comment]
We should probably go through this to pull out anything that's still relevant (e.g., swagger is not) and then log it in a new issue or on Trello.

**Comment by paglias** [comment]
I think it's okay to keep this here in Github. We absolutely want to use OAuth for 3rd parties

**Comment by Alys** [comment]
Oauth is already in progress by staff. We don't want login name and password in the API because it's a security risk. Hence I'm closing this issue.
