### ISSUE TITLE
Leveling up removes party buffs

### ISSUE THREAD

**Issue by marcelosizer** [HabitRPG/habitica#2727]
I've just leveled up and the party buffs that I had are gone. The rest of the party still have them. Yesterday wasn't a perfect day so I don't know if the perfect day would also be removed.

**Comment by deilann** [comment]
Levelling up did not remove my buffs today, also no perfect day.

**Comment by colegleason** [comment]
Both of you, what allocation scheme are you using for stats on level?

On Mon, Feb 3, 2014 at 11:52 PM, deilann notifications@github.com wrote:

> Levelling up did not remove my buffs today, also no perfect day.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2727#issuecomment-34032909
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by deilann** [comment]
No auto-allocation.

**Comment by marcelosizer** [comment]
No auto allocation either.

**Comment by marcelosizer** [comment]
@colegleason leveled up again and this time I kept the buffs. Weird.

**Comment by deilann** [comment]
Also leveled up again today, and kept buffs. Guessing that it was just a
one-time thing for you, Sinza.

**Comment by marcelosizer** [comment]
You're on a roll! =p
Yep, probably.

**Comment by marcelosizer** [comment]
@colegleason shall I close this issue?
