### ISSUE TITLE
Boss regen to Full Health

### ISSUE THREAD

**Issue by MicioDelCheshire** [HabitRPG/habitica#2728]
I was fighting Trapper Santa with my party. It was at 36 hp (/300 total). Suddenly, out of any cron, he went to max health (300/300).
We have no ideas about what could be the cause. For my part, I accepted some guilds challenges.

**Comment by Dale86** [comment]
I'm in his party and can confirm. For my part I accepted challenges too. Boss wasn't full hp: in attachment a screen with a lot of the damages we did in the last 2 days.
![trappersanta](https://f.cloud.github.com/assets/6578691/2069638/1af0096e-8d15-11e3-8de4-641030d8d6d7.jpg)

**Comment by deilann** [comment]
Related to https://github.com/HabitRPG/habitrpg/issues/2657 ?

**Comment by colegleason** [comment]
Yeah, looks to be the same. Please follow there.
