### ISSUE TITLE
Double death (possibly triple death)

### ISSUE THREAD

**Issue by katfang** [HabitRPG/habitica#2730]
Hello,

The short summary of the bug (I believe that) I'd like to report is that I deleveled twice in one "death." I'll include the longer explanation because a lot of different issues seemed to have hit me at once and are all related to death. The closest other bug I can find to this is #2630, which has a similar stew of problems and also says some things have been double counted due to internet slowness, but because my [first] death can be explained, I decided to start a new issue.

Last night, when I fell asleep, I was level 20. This morning, I logged on with just 4HP after my dailies and the Trapper Santa calculated damage on me. Just now, I refreshed the page and found that I had died, lost an item, and subsequently am now level 19 (due to a friend, Trapper Santa dealt me another 7 damage). Only then I refreshed again, and found I was at level 18. I later found out that I had another HabitRPG window open, so maybe death hit me twice because both happened to be syncing or something. After 3 more refreshes (with 1 window open), I seem to be stably at level 18.

There is, as far as I can tell, nothing that justifies two deaths, but it is also not random.

---

So that's the short of it. The extended version of my sadness is that I seem to have actually lost 3 levels, from 21 to 18. As I mentioned, I was 4HP after my daily damage / Trapper Santa was calculated. I quickly finished a bunch of tasks, and hit 21 with a _huge_ sigh of relief. Around the same time (I'm pretty sure this was not at the time I leveled to 21, but shortly afterwards), the #2554 issue came up for me (but I ignored it).

A few hours later, I get back online to check off another box, and I receive the death report that brings me down to 19. It said I lost my candy cane robes, and my candy cane robes were back on my rewards list (and thanks to #2663, because otherwise I definitely would have freaked out).

I later find another HabitRPG window open that says I am at 18. Hoping that the situation would resolve itself in my favor, I closed the window that said I was now at 18, and refreshed the window that said I was at 19, the one in which I received the death report. Well, I'm still at 18, but my candy cane robes are back. My hat, however, is gone. Actually, both my latest hats (candy cane and cornuthaum) have disappeared. Seems I've been hit by #2471 as well.

Here's the explanation of what I think happened to all the levels.

1) Level 21 might not have actually registered on the server. This would cause the 21 to 20 "death."
2) Prior to my level up to 21, I was at 4HP. The Trapper Santa dealt 7.2 damage due to a friend. As far as I know, this was _after_ I leveled to 21, but checking the time at which that damage was posted, it might have happened before. In any case, this might have caused the 20 to 19 death.
3) I later found out I had another instance of HabitRPG open. This might have caused the 19 to 18 death.

With only one HabitRPG open, I refresh, and I am stably at 18 with 50 HP with 0 XP. 

What I think should be true is either that I should be Level 19 with an item gone and non-zero XP if the 7.2 damage hit before I got the XP to level to 21 from 20. Or I should be Level 21 with my candy cane hat with 7.2 HP chunked out of me. It would also be awesome if I could get back to level 19 [or 21 with my hat back], but in any case, I hope I've shed some more light on some of the issues surrounding death.

**Comment by deilann** [comment]
Not 100% sure what's going on here, but I wanted to let you know that you can go to Settings and use "fix character values" to get your levels back and add the gold needed to repurchase your hat.

**Comment by mentalisttraceur** [comment]
Just saw you reference my bug. I wanted to you know that I am pretty sure I also lost two levels when I died instead of one, seemingly in connection to having the 'you died' screen load on two windows with HabitRPG open, but I decided that just on the off chance that I was misremembering what level I was at, to omit that part.

**Comment by katfang** [comment]
@deilann Thanks. I remembered there was some sort of feature that allowed restoration, but I couldn't find it. I definitely just overlooked that.

**Comment by lefnire** [comment]
let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544
