### ISSUE TITLE
Dailies not reseting

### ISSUE THREAD

**Issue by raphaelhata** [HabitRPG/habitica#2731]
Since I started the game my dailies are scheduled to reset at 06:00 AM. Since this morning I have not been able to reset them. I tried to set different times but it didn't work. Currently, I am leaving on the standard time so if it works. 

SUGGESTION: wouldn't be easier if the dailies were reseted manually? Just some idea, I have no knowledge of programming so I don't really know if this would be easier.

**Comment by deilann** [comment]
Check out this issue here: https://github.com/HabitRPG/habitrpg/issues/1057

There's talk about manual day reset and I really, really want it. There are just a few quirks that need to be figured out on top of everything else.
