### ISSUE TITLE
Tasks not staying ordered

### ISSUE THREAD

**Issue by caveman1337** [HabitRPG/habitica#2732]
Every time I try to rearrange my tasks, the next time I go on, they reset themselves. Even worse, the ordering is absolutely horrible. I've tried syncing afterwards, but that just sets them all back to unordered. I'm having the same issue in two different browsers too. (Firefox 26 and Chrome 32) My biggest issue is that some of my stuff that I want at top (has due date within a few days) keeps getting either pushed to the bottom or scattered somewhere in the middle. It would help more if we had an option to sort tasks by due date, too.

**Comment by deilann** [comment]
You can follow this here: https://github.com/HabitRPG/habitrpg/issues/2606
