### ISSUE TITLE
Create a hotkey and click action to insert an item mid-checklist

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2733]
I've found that as my checklists mature, I sometimes want to insert a checklist item somewhere other than the end of the list. (Very often they're sequential actions, so order is important at least for ease of use.) But at present, I have to either delete all the checklist items after the point where I want to insert one and rewrite them, or edit over each of them. Slow and clunky!

Suggestions:
- If the user has the cursor at the front of the checklist item and presses Enter, have it push that item and ensuing items down a row, adding a new blank checklist item.
- Add a divot that appears when the user mouses over the area to the left of and in between checklist items. Like so (though it wouldn't need to be so huge; enlarged for emphasis and because Paint):

![image](https://f.cloud.github.com/assets/4501321/2072579/94853ea4-8d40-11e3-80ab-75fdd2590de0.png)

When the user clicks that, insert a new checklist item at the selected location.

**Comment by SabreCat** [comment]
Oh, and though I chose poorly for the screenshot, that should only appear when the task is in edit mode.

**Comment by deilann** [comment]
Or the ability to rearrange checklists. I'd prefer that.

**Comment by SabreCat** [comment]
Good point! Drag-drop would render this moot.

**Comment by gjoyner** [comment]
Hey everyone! I decided to start tackling this as my first major contribution (after learning AngularJS and all). What I'm thinking is a drag & drop re-arrange like with tasks, the "cursor in front, and if you press enter, push things down and create a new entry" thing that was reference in the first bullet point above. I'm also thinking about when a user presses Enter when the cursor is in the middle of a list item to have it push the latter half beyond the cursor into a new list item below the original, so a person can divide an item.

This is all I have in mind for it now, but hoping to really tackle this in the coming weeks. :)

**Comment by lefnire** [comment]
For those interested in hotkeys, be to use http://angular-ui.github.io/ui-utils/ Keypress (a util we're already using in some instances).

**Comment by crookedneighbor** [comment]
The spirit of this issue is fixed (being able to re-arrange checklists), but not the specifics. @SabreCat you comfortable with calling this closed, or do you want to leave it open?

**Comment by SabreCat** [comment]
I'm satisfied with the present UI!
