### ISSUE TITLE
Editing my name withdrew me from me party.

### ISSUE THREAD

**Issue by 7eagle14** [HabitRPG/habitica#2734]
I edited my changed my screen name and it seems to have rebooted my ID and withdrawn me from my party.

**Comment by 7eagle14** [comment]
Except... whenever I open the Social tab it lists me as having no party. Then it seems to update, as if it doesn't immediately recall that I was someone else, and lists me as belonging to a party. The chat shows that my previous name made a comment, but that any comments made now are listed as my new name.  The chat also offers the @name of my previous name along with my new name.  It's like the system can't understand that my name changed and thinks that I'm a completely different person.

**Comment by deilann** [comment]
That's all completely normal. Doing things like clicking on your old name and stuff in chats will still bring up your proper info. The "no party" thing is just the window loading slowly.
