### ISSUE TITLE
Dailies Failed To Reset 2 Days in a Row

### ISSUE THREAD

**Issue by nataliezook** [HabitRPG/habitica#2735]
Title says it all. I signed in for the first time today six or so hours ago and saw my dailies hadn't reset. I thought I was forgetting having signed in even earlier and didn't think anything of it 'til midnight rolled around and again, my dailies have not reset. (Obviously my main problem here is not going to bed on time, but I suppose y'all can't help me with that. ;) )

**Comment by nataliezook** [comment]
Update: This is very similar to #1057 , except I do not and never have had a custom day start time. Today I made new tasks duplicating my old "stuck" ones and restored streaks so I get my streak bonuses, but if I have to do that everyone day it will get old very fast.

**Comment by lefnire** [comment]
Same as #1057. turns out CDS is unrelated after all, let's follow there

**Comment by colegleason** [comment]
Tyler, are we sure CDS is unrelated? I still believe there is another CDS
bug that is not related to the duplication of actions.

On Tue, Feb 4, 2014 at 10:13 PM, Tyler Renelle notifications@github.comwrote:

> Same as #1057 https://github.com/HabitRPG/habitrpg/issues/1057. turns
> out CDS is unrelated after all, let's follow there
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2735#issuecomment-34136244
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com
