### ISSUE TITLE
No damage to boss from BoF cast before quest started

### ISSUE THREAD

**Issue by marcelosizer** [HabitRPG/habitica#2736]
I cast around 10 BoFs yesterday and I had a quest invitation. After that the quest started and today I did only 6 damage to the  boss which I believe to be from dailies. Is this the expected behavior or the boss should have received the BoF damage?

**Comment by SabreCat** [comment]
Damage to bosses only accrues while the quest is active. This does lead to some odd behavior sometimes (if you start the quest late in the day, you frequently get party members dealing 0 damage to the boss even with perfect days), but it's expected, at the moment.

**Comment by marcelosizer** [comment]
Ok. Just to add some info here:
![nodamageboss1](https://f.cloud.github.com/assets/6205335/2076233/f14936ec-8d9d-11e3-96ec-e92e343307ce.png)
![nodamageboss](https://f.cloud.github.com/assets/6205335/2076232/f0d386f4-8d9d-11e3-9cab-3fe157c8bda0.png)
My damage (10 BoFs) vs the damage of the user who started the quest (15 BoFs). I believe he used his spells before he started the quest, but sent him a message to confirm it anyway.

**Comment by SabreCat** [comment]
Sheesh, BoF is OP xD

**Comment by marcelosizer** [comment]
No it's not! =p

**Comment by marcelosizer** [comment]
Actually he used his BoFs after starting the quest, so the problem is when using it before starting the quest. Is it supposed to do damage or not?

@SabreCat I was thinking here and last post I was joking but it doesn't seem that BoF is overpowered at all. I'm full int and I have around 300 MP without buffs. I get around 25 MP/day and to get 150 MP (which is what he used to do 310 damage) I would need around a week. That means that it would take around 2 weeks to get full MP and after two weeks I would deal around 600 damage to the boss which is a little over 40 damage/day. It would take me over a month to kill Vice on my own. It doesn't seem overpowered.

**Comment by DanielTheBard** [comment]
@Sinza- It wouldn't make much sense if you cast a spell before you started a quest, and then it did damage to the boss. You don't shoot a gun at the wall and then when a guy comes in the room expect it to have hurt him :P

As for overpowered... idk. It leads to some bad implications. If a group of wizards just saved up mp, they could start a quest, all use their BoF and just one shot our current biggest boss. Defeating the point of a boss, I think. I really think we need to reduce the power of BoF and BS. 

310 dmg - (maybe) 10 for dailies  / 15 BoF  = 20 dmg / BoF

If a 10 mp is doing like double the dmg you do by actually doing tasks? That's messed up. And mage's earn MORE mp per day?! So they can cast at 2 BoF a day, 5 every 2 days. That is completellyyyy overpowered. It also makes non-warrior/mages classes feel more useless. Rogue's have their own OP problems. And I as the healer feel generally useless other than some minor healing powers, that generally aren't necessary since the other classes are so much more powerful.

**Comment by marcelosizer** [comment]
@DanielTheBard yes, it makes no sense but dailies and to-dos completed before the start of the quest deal damage but that's a different issue. I'm gonna close this PR. Where is the BoF discussion going on?

On the BoF issue though I still think it's not OP but I'm always a Mage so my opinion can be biased. But each class should have abilities that add to the party. I don't know about you, but people die a lot, so a healer can be really useful.
- Healers shall keep everyone alive.
- Rogues are supposed to be good at collection quests and gathering items, which other classes aren't.
- Fighters are supposed to deal higher damage to bosses without the use of MP.
- Mages are supposed to deal high damage to bosses with magic skills.

5 BoFs/2 days is not really too much as when you're low level you can't cast that much and when you're high level that's hardly enough to level. I tend to use once or twice a week half of my MP to kill a boss, but now it's starting to get really hard! I'm near level 50 and it's becoming hard to level up and I can either buy potions (I'm a relatively new player so I don't have much gold) or use BoFs to get to full HP. Considering my highest daily which give me around 75 XP I would need 16 BoFs which is more then half my MP and there are days (specially with quests) that I lose half my HP.

You gave an example of a party full of mages, of course they would 1-hit kill the biggest boss, but they shall also be 1-hit killed by the biggest boss! They are supposed to use magic and not get hit as if they get hit they receive high damage. I have a very high int and mid per but I have no con or str, so I get a lot of damage even though I deal a lot of damage with magic skills (not much on to-dos or dailies).

Now, imagine a party of full INT healers. They wouldn't have as much mana as mages but they would receive way less damage. Let's say the party has 7 healers, if each one of them use one healing spell/day they would never die! And with high MP they would be able to use spells more often then 1/week.

I'm enjoying the game as it is, increasing difficulty gradually as I get used my chores and feel ready to add more. And the fact that you make your own game also makes me feel that it's not OP. I'm trying to balance my difficulty in order that it doesn't get too hard that would discourage me but doesn't get too easy that would not inspire me, so I take the BoFs into account. As far as bosses are concerned I would need around a month and a half to kill Vice on my own and I could die, so on a party of 6 full int mages it would take something like a week. That's an extreme example so on an average party it shall take around 2-3 weeks to kill it.
