### ISSUE TITLE
Mana over maximum allowed

### ISSUE THREAD

**Issue by PaulSainsbury** [HabitRPG/habitica#2737]
I'm not sure how it came about, but today, after completing a few dailies and tasks, my mana bar shows 65/58. 
![image](https://f.cloud.github.com/assets/326852/2075379/ea1c7328-8d8b-11e3-86b0-302ebb5067c6.png)

**Comment by deilann** [comment]
Check this out: https://github.com/HabitRPG/habitrpg/issues/2082

Question I asked on that ticket stands: did you have a perfect day yesterday?
