### ISSUE TITLE
Wrong image when upgrade a pet to mount.

### ISSUE THREAD

**Issue by MicioDelCheshire** [HabitRPG/habitica#2738]
A few days ago I fed my cotton pink dragon pet the last pink food to let him become a mount. I received correctly the mount and I lost the pet. Good.
But instead of the previous paw silhouette with the question mark, in the pet tab I can see the outline stroke of the dragon-which-was..
![pet bug](https://f.cloud.github.com/assets/3024012/2075546/3a567c32-8d8f-11e3-9172-33bda75ee321.jpg)

**Comment by marcelosizer** [comment]
That was a recent update to let you know which pets you have already upgraded to mounts.
