### ISSUE TITLE
Re-hatching evolved pets counts toward Beastmaster

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2739]
Today I got the Beastmaster achievement even though my Inventory > Pets page only shows 88/100.

It appears that not only do [Gryphons erroneously count toward the 90](https://github.com/HabitRPG/habitrpg/issues/2676) (I have 6 of them), but re-hatching a pet that was already leveled up into a mount also increments the counter. The hatching that put me over to earning the achievement was a Base Tiger, which I already have the mount form of.

So to reproduce:
- Note the Pets count on the Stats & Achievements page, and the Inventory > Pets page.
- Transform a pet into a mount.
- Check how the counts have changed.
- Hatch that pet species+color again.
- Check the pet counts one more time.

It may not be entirely consistent, or perhaps the behavior has changed and I hit it at different times. I know I've re-hatched at least three pets I have the Mounts for, but my count is off by 2, not 3.

Solution: don't decrease the "pets found" count when you level up a pet, but don't increase it when you re-hatch that combination either.

**Comment by SabreCat** [comment]
Oh! The mis-awarded achievement appears to only happen on the browser end. I checked off a task and got the notification that Rebirth was unlocked. Then I refreshed the page, and went to the Market: no Orb. I went back to Stats & Achievements: no Beastmaster either!

My "Pets Found" on Stats & Achievements still reads 90, though.

**Comment by deilann** [comment]
Not duplicating this. Just rehatched a White Wolf and my counter stayed at 47. However, my counter is two off.

**Comment by deilann** [comment]
Also hatch has nothing to do with petCount... so I'm not sure how rehatching pets would increase the count.

**Comment by DanielTheBard** [comment]
Same problem. I have 88/100 pets. 6 gryphons. Got the message for the achievement at around 87 or 88 pets. But no actual achievement on my page.

**Comment by deilann** [comment]
How many special pets do y'all have?

Cause:

```
    $rootScope.$watch('user.items.pets', function(after, before) {
      if (User.user.achievements && User.user.achievements.beastMaster) return;
      if (before >= 90) {
        User.set({'achievements.beastMaster': true});
        $('#beastmaster-achievement-modal').modal('show'); // FIXME
      }
    });
```

**Comment by deilann** [comment]
Sorry, edited in the correct code, there. No coffee = no awake.

**Comment by SabreCat** [comment]
I've got four rare pets. Which still doesn't add up...

**Comment by deilann** [comment]
Yeah. But I can't see how my Beastmaster fix would skew that count any more
than feeding a pet would. Honestly, @colegleason and I were talking about
this -- Beastmaster isn't logically written. Would be better to go off of
countPets. When that hits ninety, boom! And Cole says he's gonna be able to
do a gen1 count, so we could use that.

**Comment by SabreCat** [comment]
OK, something else must've been going on, since I just re-hatched a Red Dragon today and didn't see any of my numbers budge. The Stats & Achievements page still shows 2 more pets found than the Pets grid itself, but the issue as described here appears not to be the case. Closing.
