### ISSUE TITLE
Suggestion: Organize To-Dos by Due Date

### ISSUE THREAD

**Issue by lor1000** [HabitRPG/habitica#2740]
I make use of the due dates for school, however when I add new to-dos, the ones I've made get pushed downwards. Oftentimes, I have assignments that aren't due for a few weeks and so they'll get pushed down the list as I add more. By the time the due date rolls around, I'll have forgotten about it or don't notice it since it's far enough down on my list that I have to scroll to see it and I don't always remember to do so.

It would be helpful if the To-Do list could put things in order by due date, and those without due dates go under the ones that do?

I've also made the observation that there is no penalty if you don't complete something by your due date, which basically lets me keep procrastinating until the last minute since I'm sort of prone to cheating a bit on things like that.

**Comment by deilann** [comment]
There is a Trello card on this! I highly suggest checking over there for these kinds of things.
