### ISSUE TITLE
Application 503 and character death

### ISSUE THREAD

**Issue by mmarkey3** [HabitRPG/habitica#2741]
Posting for my friend, aghstnashell, because he doesn't have a Github account.

"Application 503 Error resets all dailies and any other changes for the day. Occationally dailies do not reset on cron but dailies that are set for the next day open up. Signed in for the first time today and got the same application 503 error, refreshed and got a you died message when I had 40 health the night before. Lost 498.xx Gold but level did not drop to 61 from 62 after death I was still at lvl 62."

The death definitely should not have happened, since the rest of us were in the middle of a quest, and only lost around 12 HP each at cron.  This has been a problem for some time but didn't result in death until now.

**Comment by lefnire** [comment]
let's follow on #2601
