### ISSUE TITLE
Optimize slow queries

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2743]
This is complete, just filing against our milestone to show the progress.

We had a lot of Mongo queries which were >300ms due to improper use of compound indexes. There were a few issues, all related to the order of the compound index. Read more on the topic [here](http://docs.mongodb.org/manual/core/index-compound/) and [here](http://docs.mongodb.org/manual/tutorial/sort-results-with-indexes/)
- Sort fields need to be in the compound index. Eg, `db.challenges.ensureIndex({group:1})` wasn't sufficient since we were running `Challenge.find(..).sort({timestamp:-1,official:-1})`. The solution is `db.challenges.ensureIndex({group:1,timestamp:-1,official:-1})` 
- The order of the compound index is important. `db.ensureIndex({__v:1,_id:1})` was our previous, which is slower than `db.ensureIndex({_id:1,__v:1})`. Why? `{__v:1,_id:1}` will first find all users whose `__v=...`. There could many. In this case, there might not be - but in other collections, this first index field was causing major slowness. You want the first field to represent the unique, or most-unique, of the fields in the compound index
- and a bunch more, maybe i'll update this later.

**Comment by colegleason** [comment]
Possibly a dumb question, but how does the order of the keys in an object
matter? I thought objects represented unordered collections.

On Tue, Feb 4, 2014 at 12:25 PM, Tyler Renelle notifications@github.comwrote:

> Closed #2743 https://github.com/HabitRPG/habitrpg/issues/2743.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2743
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by lefnire** [comment]
Turns out Mongo doesn't use the javascript object as javascript-proper, it parses it out left-to-right when reading the `ensureIndex()` command.

**Comment by lefnire** [comment]
When you issue a query, the order doesn't matter. It finds the index that fuzzy-matches. However, the order you specify in `ensureIndex` is super important, and needs to be left-to-right sort of "order of uniqueness". Lots of details [here](http://docs.mongodb.org/manual/core/index-compound/) and [here](http://docs.mongodb.org/manual/tutorial/sort-results-with-indexes/), but that's the gist

**Comment by colegleason** [comment]
Alright. That's just odd to me.

On Tue, Feb 4, 2014 at 12:58 PM, Tyler Renelle notifications@github.comwrote:

> When you issue a query, the order doesn't matter. It finds the index that
> fuzzy-matches. However, the order you specify in ensureIndex is super
> important, and needs to be left-to-right sort of "order of uniqueness".
> Lots of details here http://docs.mongodb.org/manual/core/index-compound/and
> here http://docs.mongodb.org/manual/tutorial/sort-results-with-indexes/,
> but that's the gist
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2743#issuecomment-34093866
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
I'm trying to find where I saw that described. SO IIRC. TMK it's _only_ when running the `db.collection.ensureIndex` command, everything else acts as expected. I could be way off too, just something I saw floating aboot
