### ISSUE TITLE
Automaticly died, gold and experience lost.

### ISSUE THREAD

**Issue by Aroswing** [HabitRPG/habitica#2745]
So, I went to add something to my to-do list on my phone. During the sync process, I got a message saying that I had died. I had more than 90% of my health remaining the night before and all my dailies were done. I also had about 133 gold that disappeared, and I lost a level. All this was verified when I checked on the computer. What happened?

**Comment by mmarkey3** [comment]
Related? #2741

**Comment by Aroswing** [comment]
I think so

**Comment by lefnire** [comment]
let's follow on #2601
