### ISSUE TITLE
Party

### ISSUE THREAD

**Issue by Silkone** [HabitRPG/habitica#2746]
I was invited to a party,
I accepted it, and then when i went back to check it i had the invite again. 
Now when i've gone back to check it, I am no longer in a party?

**Comment by deilann** [comment]
Make sure to wait for the screen to entirely load. It loads a default "no party page" and then fetches the party page on top of it. Sometimes that fetch can take a while. If it still doesn't load, try refreshing and wait again.

**Comment by deilann** [comment]
If this is still an issue, please let us know. I've put in a PR to let people know the party may just be taking a while to load.
