### ISSUE TITLE
Problem with the HabitRPG android app

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2747]
I'm having an issue with the HabitRPG app on my phone running on Android. I don't know if it's only a problem with me or if it really is a bug.

All the checklists on the app work great, except for the to-dos checklist. Whenever I try to check a task and touch the screen, the screen suddenly jumps and I end up checking the task above the one I completed. Unchecking in the "completed" tab goes completely fine, and checking of the dailies as well, it's just a problem with the to-dos.

I don't know if anyone else has been bothered by this as well, but it's hard for me to cross tasks of my to-do list this way.

**Comment by negue** [comment]
Could you pls check again if the problem still exists?

**Comment by lemoness** [comment]
Due to lack of response, I'm closing this ticket. Let me know if you're still having this problem and we can reopen it.

**Comment by ghost** [comment]
Oops, forgot to respond. The problem seems to have been solved. I'm no longer having trouble with the app anymore.
