### ISSUE TITLE
Experience loss, money loss, level loss, item loss

### ISSUE THREAD

**Issue by Eskerne** [HabitRPG/habitica#2748]
So, I tend to do all my To-dos at the end of the day and I keep track of them throughout the day (to stop myself from picking up my phone which will distract me). Well, twice today, I added all the to-dos I did. Gained two levels (to level 42) and then when I came on at a different part of the day, I lost everything. I don't have the new armour that I bought. I don't have the items and pets that I found. It resets to what it was last night before I entered everything. 

I didn't think anything of it when the game asked me to re-buy one of my mage weapons, and I spent a second 160 gold on it. However, it takes time to re-add all the tasks and I'm not sure if my drops are resetting either. Which means that I've lost what I gained, but don't have a chance to regain items.

Edit: Because I accidentally hit submit... Browser: Firefox (also the iphone app). 
User ID: 1e939519-9a51-4bf0-b566-4928b63fb4e8

There was a javascript error that came up earlier today, but I didn't think anything of it at the time. And it popped up as I was gaining items. I noticed item loss on another ticket.

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544
