### ISSUE TITLE
Ads overlap the header

### ISSUE THREAD

**Issue by gbuell** [HabitRPG/habitica#275]
When I scroll down, the ads land on top of the header, which I assume is not the intended behavior. Here is a screenshot: 
![ScreenClip](https://f.cloud.github.com/assets/3417856/115422/845dd976-6bce-11e2-8597-6af6b24b1071.png)

**Comment by StanLindsey** [comment]
Apparently the Google Adwords TOS restricts the ads from being underneath any elements. @lefnire - they may need to be moved to a different location...

**Comment by lefnire** [comment]
lol, seriously? what a TOS.. kk

**Comment by gbuell** [comment]
What a gross restriction. I guess you need to prevent them from scrolling that high.

**Comment by StanLindsey** [comment]
Note; Thats from reading forum posts from as close to a year ago - not reading the actual TOS. People were very adamant though. I think it is so you can't trick users into clicking on the ads.

Options for us are different placement, different ads altogether (game ads? Eurogamer.net have an advert API I think that they use on a couple other sites, plus at least they aim towards our demographic) or something else.

**Comment by lefnire** [comment]
you're talking below items vertically, or z-index?

**Comment by StanLindsey** [comment]
z-index I think - your post is the first mention of "below" in this thread though so I may be misunderstanding your question.

I did try to change the z-index of the various advert tags(albeit in Google Chromes dev tools) but they either disappeared completely or had no effect.

**Comment by horusofoz** [comment]
Same thing happening for me on Chrome for Android (ICS).

**Comment by Pandoro** [comment]
As ads are out, I will close this one.

Please correct me if I am wrong :x
