### ISSUE TITLE
Since moving to Wikia, where is the developers' forum?

### ISSUE THREAD

**Issue by jr24207** [HabitRPG/habitica#2750]
Asked this in the Wikia users' forum, got no response: http://habitrpg.wikia.com/wiki/Thread:5079

**Comment by lefnire** [comment]
The devs don't much frequent the Wikia. What Qs do you have?

**Comment by jr24207** [comment]
Was trying to figure out how to create a new habit through the API.

Is there currently no forum for developers of third party addons? 

I tried to create an account for the dev forum at the pre-Wikia forum site, but it was having issues.

**Comment by lefnire** [comment]
Pre wiki forum site is dead, it's just up for archive purposes. Most the devs are chatting away on Github, but I suppose that's funky 'cause it has to be related to a ticket / commit. You should start the revolution :)

**Comment by deilann** [comment]
You can also head on over to the Aspiring Legends guild -- it's kind of
slow/dead, but you could also start a revolution there.

**Comment by jr24207** [comment]
I don't think I'm up to being a mod for it at the moment.

Lefnire, what about creating an /r/hrpgdevs subreddit and linking it from the /r/habitrpg sidebar?

**Comment by deilann** [comment]
You wouldn't have to be a mod @jr24207 -- the guild already exists.

**Comment by deilann** [comment]
Closing this; it doesn't need to be open for discussion to continue.
