### ISSUE TITLE
It's possible to create user-undeletable habits through the API.

### ISSUE THREAD

**Issue by jr24207** [HabitRPG/habitica#2751]
While trying to figure out how to create a new habit through the API, I inadvertently created a user-undeletable habit. It had different buttons and no "delete" button.

HRPG sent response code 200 "ok" when the habit was created.

The habit was still deletable through the API. 

I've since figured out how to make new habits, but thought the community might want to know.

![capture2](https://f.cloud.github.com/assets/3826195/2084208/65088386-8e1a-11e3-919b-42506633709e.PNG)

{
  "type": "habit",
  "history": {},
  "up": true,
  "down": true,
  "id": "id",
  "created": 1389719154807,
  "text": "blah",
  "notes": "notes",
  "tags": "tag",
  "value": 1,
  "priority": 1,
  "challenge": {
       "id": "id",
       "broken": "",
       "winner": ""
       }
}
##

**Comment by colegleason** [comment]
This is "undeletable" because it is a challenge tasks. We should probably
reject the creation of task associated with a challenge where the challenge
doesn't exist of the task isn't part of the challenge.

On Tue, Feb 4, 2014 at 10:19 PM, jr24207 notifications@github.com wrote:

> While trying to figure out how to create a new habit through the API, I
> inadvertently created a user-undeletable habit. It had different buttons
> and no "delete" button.
> 
> HRPG sent response code 200 "ok".
> 
> The habit was still deletable through the API.
> 
> I've since figured out how to make new habits, but thought the community
> might want to know.
> 
> [image: capture2]https://f.cloud.github.com/assets/3826195/2084208/65088386-8e1a-11e3-919b-42506633709e.PNG
> 
> {
> "type": "habit",
> "history": {},
> "up": true,
> "down": true,
> "id": "id",
> "created": 1389719154807,
> "text": "blah",
> "notes": "notes",
> "tags": "tag",
> "value": 1,
> "priority": 1,
> "challenge": {
> "id": "id",
> "broken": "",
> "winner": ""
> }
> }
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2751
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by jr24207** [comment]
Looks like a logic bug you guys ought to straighten out.

**Comment by librarianmage** [comment]
@Alys is this still a problem?

**Comment by paglias** [comment]
Fixed in v3
