### ISSUE TITLE
503 errors leading to death

### ISSUE THREAD

**Issue by Derpums** [HabitRPG/habitica#2752]
The past few days I've completed all of my dailies and yet I've been getting 503 errors multiple times in one day and just recently died with having everything complete on full HP during the cron.

**Comment by lefnire** [comment]
Let's follow on https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-34134544

**Comment by lefnire** [comment]
guys.... https://github.com/HabitRPG/habitrpg/search?q=death&type=Issues , why does nobody search :(
