### ISSUE TITLE
Dailies are still red, even after checking them!

### ISSUE THREAD

**Issue by rsp88** [HabitRPG/habitica#2754]
I had a few dailies that I'd fallen behind on, but when I did accomplish and check them, they were still red the next day! I've already died once, losing a Yeti-Tamer robe that took no small amount of time to earn!

I've deleted the red tasks and replaced them with identical ones - I just couldn't take any more!

**Comment by marcelosizer** [comment]
The color of the tasks depend on their score. If your score was too low that the daily became red, it would take some time for it to become yellow again. You can check your score on the progress icon (the second from right to left):

![progress](https://f.cloud.github.com/assets/6205335/2087942/3ae61744-8e74-11e3-94f8-63b5596d7c15.png)

If you can't keep up with the tasks and you're dying to often you can use a Fortify potion (under Inventory > Market) to restore all tasks to yellow (and keep your history) or just remove and create new ones as you did.

![fortify](https://f.cloud.github.com/assets/6205335/2087989/f9eaefca-8e74-11e3-955f-95cd6a786da8.png)
