### ISSUE TITLE
One user isn't in our party, but we can't invite him!

### ISSUE THREAD

**Issue by Mclary** [HabitRPG/habitica#2755]
One day a player (Nate Jagger) disappeared from party members list (http://prntscr.com/2pghyr), but if we try to invite him, site is telling, that he is already in the party (http://prntscr.com/2pgi82). So, what's going on?

**Comment by deilann** [comment]
Does his screen show him in a party? If so, have him leave that party and then invite him.

**Comment by crookedneighbor** [comment]
@Mclary did this get resolved?

If not, can you send us your user id, as well as the user id of the person who is not in the party?

**Comment by berriganator** [comment]
@crookedneighbor I'm having this problem as well. My friend (cfcc6f43-719f-4b33-9eea-66e6e1749dee) accidentally left or disappeared from our party (487d2206-03c9-4474-9b67-04e225ca93c8). On my social page, the party only lists me. But when I try to invite my friend, it says she's already in the party. Would love your help. Thanks.

**Comment by deilann** [comment]
That actually sounds like tbr duplicate party issue. When you see yourself
alone in a party, leave that party. Log out and log back I'm and see if
that fixes things.

**Comment by berriganator** [comment]
@deilann I'm not sure what you mean. Do you mean that my friend should leave the party, log out and log back in? I tried logging out and back in, but that didn't solve it. I don't want to leave the party because we are in the middle of a Quest.

**Comment by deilann** [comment]
Do you see the quest in this party by yourself? If so you are in the
correct party. (Do make sure to refresh though to make sure that it's not
just a cached quest.) If your friend cannot see the quest, they are tied up
in a duplicate party and should leave it. At the very least, this will
allow you to invite them back to your party.

There is an issue sometimes, especially with older accounts, where the
account gets stuck in two parties at once. Obviously this causes Issues.

**Comment by berriganator** [comment]
@deilann Yes, I am in the party and the quest and all is fine for me. I do not see my friend in the party or in the quest. I will ask if she can see the quest & the party. I don't think she can. She told me she thought she accidentally left the party, and I no longer see her in the quest or in the party. She is a very new user (within the last month or so), and I am a pretty new user as well (within the last few months).

**Comment by deilann** [comment]
She may have also accidentally left the party and then created a solo party
trying to get back in, which would cause this issue.

**Comment by berriganator** [comment]
@deilann I don't know what she did to fix it... She didn't tell me. But she did, and I was able to invite her back.

**Comment by deilann** [comment]
Alright! I'll close this then.
