### ISSUE TITLE
API function "member/{uid}" does not send toNextLevel (experience)

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#2758]
I was trying to make a Windows application that simply shows my stats, i've found two functions to do that:
1. user
2. member/{uid}

First case, I retrieved a 157kB file.
Second case, 2.58kB file.
I would use the second one but it lacks the toNextLevel field...
Not really a problem, just wondering why. Wouldn't it be faster?

**Comment by colegleason** [comment]
Generally, I think user is meant for your data and member is meant for fetching data of other people (since it doesn't contain their habits, etc). However, if you need toNextLevel we can consider adding it.

**Comment by Atomk** [comment]
@colegleason You're right, of course this is not really the main purpose... I just wonder how to know how much experience is needed by a generic user to level up, or why this variable has different names in two similar functions.

**Comment by colegleason** [comment]
Here is the knowledge you seek :wink: 

```
Math.round(((Math.pow(lvl, 2) * 0.25) + (10 * lvl) + 139.75) / 10) * 10
```

**Comment by Atomk** [comment]
That 139.75 is the key I suppose. I feel so ignorant about coding games now, ahah. As soon as I have some free time I'll try this, thanks a lot.
