### ISSUE TITLE
Not getting achievement or buff for Perfect Days, also some Dailies still checked off the next day

### ISSUE THREAD

**Issue by lapotatodolce** [HabitRPG/habitica#2759]
The dailies that are still checked off the next day seem to be giving me XP but not gold, so when I uncheck them I'm back to where I should be for XP but am out gold that I earned

**Comment by deilann** [comment]
Related to: https://github.com/HabitRPG/habitrpg/issues/1057

If you really believe you're out gold, you can always use "fix character values" under settings to give it to yourself.
