### ISSUE TITLE
Auto-Login kills health

### ISSUE THREAD

**Issue by jdgr** [HabitRPG/habitica#276]
Using Firefox on Windows 7, or Safari on my iPhone/iPad, or Chrome/Firefox on my Google Nexus 7, when the system auto-logs me in when I visit the site, my health drops significantly everytime. The last two times I've logged in (about 5 days apart :( ), I lost 38 HP each time. So now I am dead :(

I'm not sure if it's remembering when I "purchased" something I didn't have the gold for and I lost about 20 HP, but it seems to happen each time until I die. But if I close the page and try immediately, it doesn't do it. I think it only "remembers" if I don't log in for a day or so.

Jeremy

**Comment by StanLindsey** [comment]
Do you have any dailys set up? Any unticked dailys will hurt your character the next day. So if you've had 5 days off you've been hurt by them 5 times in a row...

**Comment by jdgr** [comment]
Then it's not an issue. I didn't understand how that worked because when I clicked off the daily's, the checkmark will usually just stay there and they don't refresh each day.

I'm assuming my "bug" was just I didn't know how it works compounded by another open issue (daily's not refreshing that I read about and experience).
