### ISSUE TITLE
Cannot buy Gems with Gold after subscribing 

### ISSUE THREAD

**Issue by stetreau** [HabitRPG/habitica#2761]
I have all of the other subscription perks (no ads, doubled drop cap, etc) but cannot buy Gems with Gold for some reason. My user id is 397a2a37-f587-4eb9-ba7a-5c156b62f6f0.

**Comment by lefnire** [comment]
Is it not showing up [here](https://habitrpg.com/#/options/inventory/drops)? ([screenshot](https://www.evernote.com/shard/s17/sh/97d770e7-8c95-49d6-b9ee-71daa3b06dce/767a443558e7dd5a7324cf3bd358ec20))

**Comment by stetreau** [comment]
Ah, now it is. I guess it just needed a while to update with my payment. Thanks!

**Comment by lefnire** [comment]
Gotta hard-refresh probably. Mayhapse I should automate that
