### ISSUE TITLE
Tour popover persists and cannot be ended

### ISSUE THREAD

**Issue by jkopczyn** [HabitRPG/habitica#2764]
![hangingpopovers](https://f.cloud.github.com/assets/1253351/2095220/c93870ea-8ede-11e3-9a2f-872ebf44138f.png)
This occurs in at least one place I can reliably reproduce, IIRC other times as well. After a class reset (with gem spend), if I change tabs manually before hitting the Next button on the popover, the new popover appears normally but the previous one does not go away. The buttons on the old popover no longer do anything. These popovers will not disappear without a page refresh.

This can happen multiple times; both popovers depicted are 'stuck', with the normal one proceeding to completion and disappearing.

**Comment by deilann** [comment]
I can attest to this. It's happened to me. Refresh is the only way I've
been able to get rid of it.

**Comment by lefnire** [comment]
when the tour takes you through multiple pages, you have to follow the tour. If you click to a different tab mid-tour, it breaks. Is this the issue you're experiencing, or is it different?

**Comment by jkopczyn** [comment]
Same. It happens even it'd you have not started the tour yet, as long as
the first screen has appeared.

**Comment by deilann** [comment]
@lefnire -- I don't think so.

If I change classes, a tour shows up, iirc, and I cannot close it. All I
can do is refresh the page.

**Comment by Alys** [comment]
Tour has been rewritten. Closing.
