### ISSUE TITLE
Hall of Heroes: auto add guild invite for level 7 contributors

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#2765]
This would tackle issues of level 7 contributors not getting invited by mistake. Currently the system adds gems automatically on level up, this would do the same for the [in-game contributor] guild invite. 
Attn: @lefnire, @SabreCat

**Comment by deilann** [comment]
This would require the system to know their G+ address and have Habit send out a G+ invite. I'm not sure that's really feasible.

**Comment by wc8** [comment]
@deilann nope, but possibly an example of the issue. If you're level 7 but haven't gotten your in-game guild invite… @lemoness ?

**Comment by deilann** [comment]
@lefnire pretty much put it as, "We don't really use the in-game version,"
more the G+. So I wasn't really that worried.

**Comment by wc8** [comment]
(_@lefnire_ doesn't use it much—it's used 2 or 3 times a day, maybe, so you aren't missing much.) That said, it'd make it easier, I think, to have it automated—one less  thing to remember.

**Comment by deilann** [comment]
Ahaha. Okay. Figuring out how to automate that would make the Secret Guild
possible too.

**Comment by lefnire** [comment]
Noted, putting on my queue. I'll start using it more once I add mentions / chat notifs feature

**Comment by crookedneighbor** [comment]
Closing this since moving from Google Hangouts to a private guild is desirable, but not being prioritized.
