### ISSUE TITLE
Gryphon counted towards Beastmaster Achievement

### ISSUE THREAD

**Issue by Otocinclus** [HabitRPG/habitica#2766]
Hi GitHub!
I'm one pet away from getting the Beastmaster Achievement (I need a cotton candy pink panda and am missing the potion) and today I hatched a gryphon... and got the achievement. Gryphons aren't supposed to count towards the achievement, so I'm making a report for you :)
Here's a pic of the Gryphon and the missing Pink Panda:
![screen shot 2014-02-06 at 9 35 06 am](https://f.cloud.github.com/assets/3780244/2100173/0dbc921c-8f45-11e3-8555-93d793792512.png)
Here's the achievement!
![screen shot 2014-02-06 at 9 36 11 am](https://f.cloud.github.com/assets/3780244/2100174/1006fd00-8f45-11e3-9b0f-5643de4c689a.png)
I play on Safari 7.0.1 on a mac and using the iPhone app.

Edit: Hatched a second Gryphon and got the "Achievement Earned" popup again. I guess this would be reproducible by having 89 pets and hatching a gryphon.

**Comment by deilann** [comment]
Known error, follow it here: https://github.com/HabitRPG/habitrpg/issues/2676
