### ISSUE TITLE
An error message when I removed a To-Do and then marked another "done"

### ISSUE THREAD

**Issue by Cassolotl** [HabitRPG/habitica#2767]
I was just on my tasks page; I deleted a To-Do, and then I marked another "done", and then a pop-up appeared that said:

```
The page at https://habitrpg.com says:

<!DOCTYPE html>
    <html>
    <head>
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

Then after I closed it a little square faded in and out in the top right corner but I didn't catch the error code. I then refreshed the page and everything looked as it should; the deleted task was still gone, and the completed task was in the "completed" section.

I don't know how to search for existing bugs like this, so I am just posting it here so that someone knows it happened.

Also HabitRPG is the best thing ever.

**Comment by deilann** [comment]
You can follow this here: https://github.com/HabitRPG/habitrpg/issues/2554

To search, there's a search box at the top of the screen.
