### ISSUE TITLE
Death in Boss Battle kills but does not remove character from the fight

### ISSUE THREAD

**Issue by jkopczyn** [HabitRPG/habitica#2769]
This has happened three times to me in the past week.

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg/issues/2673

**Comment by jkopczyn** [comment]
This has different results from that issue; death works as normal, but the battle-kick does not.

**Comment by colegleason** [comment]
I believe battle-kick is currently not implemented and the text is
incorrect.

On Thu, Feb 6, 2014 at 1:04 PM, jkopczyn notifications@github.com wrote:

> This has different results from that issue; death works as normal, but the
> battle-kick does not.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2769#issuecomment-34358025
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com
