### ISSUE TITLE
Achievement for Taking No Damage During A Boss Battle

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2771]
I'd love to see an achievement that your party gets for taking no damage during a boss battle. Extra incentive to be highly motivated, and also gives quests great replay value!

Zoebeagle created the badge - it's here. All permissioned-up and read to use!
![zero damage badge by zoebeagle](https://f.cloud.github.com/assets/3494081/2104175/c4a4a08c-8f77-11e3-838e-60a0a1fbd0db.png)
##

**Comment by Aiseant** [comment]
Awesome !!!

**Comment by Alys** [comment]
@lemoness I'm assuming this is still desired? It sounds like a nice idea.

**Comment by lemoness** [comment]
Yes, I think it would be fun! Low-priority, obviously, but fun.

**Comment by librarianmage** [comment]
@lemoness How do you think it would be determined?

**Comment by Alys** [comment]
Let's put this one on hold for now. We'd need to modify cron to record the
boss damage each day and changes like that are best done after version 3 of
the API has been released (in development now).

**Comment by librarianmage** [comment]
Ok!

**Comment by khipkin** [comment]
I think the [wait] label can be removed from this now.

**Comment by Alys** [comment]
@khipkin, good point, thank you!

**Comment by khipkin** [comment]
I would like to work on this!

**Comment by librarianmage** [comment]
How about a "Deal no damage during a boss battle"?

**Comment by khipkin** [comment]
I think new achievements should wait until the following things are resolved (issues closed & PRs merged into develop):
- [x] Issue #7946 _(Notifications no longer work.)_
- [x] PR #7904 _(Achievement list visual revamp & Achievements API)_
- [x] PR #6943 _(New achievement modal service & more achievement tests)_

**Comment by Alys** [comment]
Lemoness has asked that this be closed for now. While we might revisit this in future, it doesn't make sense to have it here in our list of bugs and active approved features.
