### ISSUE TITLE
User stats HP still rounds down

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2772]
More a note to self: user stats HP still rounds down, whilst HP in the header always rounds up. So they do not always match up.
##

**Comment by caveman1337** [comment]
I'd make the suggestion to just display the decimal, rather than dropping it for the display. If not, then I'd suggest rounding down, rather than up. It's better to think you have less HP and be wrong than to think you have more HP and be wrong.

**Comment by deilann** [comment]
No, the reason to round up is because otherwise you can display having 0 HP when you're still alive.

**Comment by caveman1337** [comment]
However, rounding down prevents you from thinking you have 4 HP left and dying to 3.1 damage. Granted, that is something people should be prepared for anyways, but it still gives a feeling of inconsistency. I feel displaying the tenths position would be the best option for users.

**Comment by deilann** [comment]
Currently, the HP is rounded up for the health bar, which was at request. I
just want to fix it so that stats HP matches your health bar. Not rounding
HP requires much more discussion and is such a big change, it would
probably merit a user poll.

**Comment by crookedneighbor** [comment]
@deilann did this get finished?

**Comment by CBXZero** [comment]
It looks like this has been resolved, proposing that his issue is closed based on the picture below (my health was 46.2 at the time of the screen cap).

![example](https://cloud.githubusercontent.com/assets/3888116/13036238/35f1fb8c-d327-11e5-80ee-846ed269a853.png)

**Comment by Alys** [comment]
Yes, both stats and header bar round up now - thanks @CBXZero!
