### ISSUE TITLE
Can't start quest

### ISSUE THREAD

**Issue by waddlefish** [HabitRPG/habitica#2774]
The party I'm in wants to start Trapper Santa, but we can't start it because it's already there, except no one started it– it just popped up on its own. There's no abort button, and when my team leader tried to start the quest anyway, it said that we were already in a quest. At cron, nothing happens– no attacks to the boss, no damages from the boss, nothing. It's like Trapper Santa just decided to come out of nowhere and sit there and stare at us lol. It's been going on for almost a week. If someone could look into this, I'd be grateful.

Thanks!

My ID: 6d99092e-ce45-40af-a9e4-e110920095c7
Group ID: 890b9d2f-7165-47af-a75e-30bd9400a0fe

**Comment by deilann** [comment]
Hey @lefnire @colegleason is it related to this:

```
id = shared.uuid()
user =
  stats: {class: 'warrior', buffs: {per:0,int:0,con:0,str:0}}
  party: quest: key:'evilsanta', progress: {up:0,down:0}
```

from https://github.com/HabitRPG/habitrpg-shared/blob/cbd3aeac70d6e99473dea42960f06d61d3774f43/tests/algos.mocha.coffee ?

**Comment by deilann** [comment]
I know that's a test, but what if some parties basically got told "You're doing TS"?

**Comment by lefnire** [comment]
Wait, if it's only in the test why would it be affecting anything in prod?

**Comment by deilann** [comment]
I'm wondering if something similar happened outside of test. Setting it so
that they have a quest, without actually activating it.

**Comment by deilann** [comment]
Sorry, my logic is not being explained. And I think that code is unrelated,
just what got me started thinking about it.

So the 503s sometimes saved parts of a function to the user, but not all of
them. (Like losing MP but not getting the spell rewards).

What if they got assigned the quest, but it didn't activate?

**Comment by lefnire** [comment]
Got it, yeah that's very plausible. Will take that into consideration when tackling this

**Comment by Alys** [comment]
I'm sure this doesn't still happen. We'd have heard reports of it. Closing.
