### ISSUE TITLE
Randomly dying

### ISSUE THREAD

**Issue by lizard87** [HabitRPG/habitica#2778]
Recently I've seen it happen to a friend a few times, and now it's happened to me.

Last night before going to sleep I had completed all my dailies and had around 30 health after having more health taken off than what the quest cost me in damage and repurchasing some health. This morning I woke up dead.

Chronological order:
-Found myself with 12 health yesterday morning
-Purchased extra health using gold
-Completed all my dailies throughout the day
-Had 30-ish health left about 9 hours ago
-Woke up, dead

**Comment by deilann** [comment]
Please follow here: https://github.com/HabitRPG/habitrpg/issues/2601
