### ISSUE TITLE
My dailies are not being recorded

### ISSUE THREAD

**Issue by mozuca** [HabitRPG/habitica#2779]
Well, my first time here, I didn't really find anything like what I'm experiencing in the forum.

Sometimes (at least every other day, lately), system does not record my checks on dailies, and this makes me take damage from the boss (quest), and, even more frustating, I lose my streak counts.

I believe that, maybe, this has been happening lately due to a system error, that frequently shows up on my screen, but not everyday (error 503). I even started to manually sync, on options, but it didn't work to help me from losing dailies. Maybe these are two disconnected issues, but somehow I thought they could be related.

What could this be?

Thanks,
Samantha

**Comment by colegleason** [comment]
Hey Samantha,

You're right, it is most likely those 503 errors. We're aware that they're a huge issue, and we are trying to find a way to fix them. Please see discussion at #2601.

Sorry for the issues! You can fix streak counts by editing the task. You can fix Health, gold, level, etc through Settings -> Fix Character Values.

**Comment by lefnire** [comment]
at least for now, post-error ops go through, so we should be seeing fewer "my actions didn't stick"

**Comment by colegleason** [comment]
Which change enabled post error ops to go through?

**Comment by colegleason** [comment]
Oh, jk. #2775
