### ISSUE TITLE
Daily Habits Cloned, Missing

### ISSUE THREAD

**Issue by jurries21** [HabitRPG/habitica#278]
So here's the deal: I have 9 items in my daily habit list. As of last night, 5 of them turned into copies of one of mine. If I check any of them off all of the copies check off too, and they all uncheck together as well. So not only is that screwed up but I don't have access too/can't see the five habits it overwrote. Help?

**Comment by lefnire** [comment]
yikes, even on a refresh? [email](mailto:tylerrenelle@gmail.com) me your uuid and i'll see If i can figure it out

**Comment by lefnire** [comment]
0a59d6e43d88cf6399d13e22ba19ff86fc27e9bb - i need to revisit that though for a specific edge-case (see comment there)
