### ISSUE TITLE
Dailies Not Recorded+ To-Do FUBAR

### ISSUE THREAD

**Issue by reachmouse** [HabitRPG/habitica#2780]
I've been seeing some errors a bit more lately in HabitRPG, and I wonder if that has anything to do with what I've seen this morning. When I woke up, rather than my Dailies being reset (after being completed, I might add), a number of them were still registering as 'recently completed'. But it wasn't consistent; it registered others as 'not done', breaking streaks that I was actually keeping up with and dealing boss damage. 

But it's the To-Do list that shows better that something's wrong, because it seems to be duplicating some of my To-Dos; I see them twice. 

Thanks for any help!

**Comment by zoebeagle** [comment]
Video of To-Do's acting strange (taken by me): http://screencast.com/t/MwLMShuamq

**Comment by colegleason** [comment]
This is probably a side effect of a #2601 related bug. Sorry for the inconvenience. We're working on it!
