### ISSUE TITLE
Also having trouble with Dailies 

### ISSUE THREAD

**Issue by elfflame** [HabitRPG/habitica#2781]
My dailies are not clearing, and I just basically lost two levels and "died" this morning trying to clear them. None of the things I mark as done the previous day clear, and I also noticed that several of my habits are duplicating.

I have noticed, at different times, error messages on the site, and wonder if the error is what's causing my issues, but I have no idea how to fix it.

I've been enjoying using this page, but if this continues, it's going to make the game worthless for me.

Any help here would be appreciated, thanks.

**Comment by colegleason** [comment]
Sorry for the trouble! We currently have two issues that reflect possible bugs that affect dailies. The primary one is #1057 and we also have theories at #2601. Please follow up there!

**Comment by elfflame** [comment]
Thank you. I did see the post after I posted here. I've got it sorted a little, at least. I hope you get it all figured out soon.
