### ISSUE TITLE
Resting in Inn - Dailies not greyed out, and also a weird chron bug

### ISSUE THREAD

**Issue by ACRPG** [HabitRPG/habitica#2782]
I started resting in the Inn yesterday afternoon, and it greyed my dailies out. I was ill but was able to do a few dailies, so I checked them off. 

This morning I checked in and I am still Resting (There are Zzz's next to my character, and option to "Check out of Inn" is available). BUT the dailies I did NOT do yesterday are colored! The ones I did do yesterday are greyed out and still checked, as if chron didn't roll over. 

I wanted to see what would happen, so I checked out of the Inn. I refreshed my page two times but still see that the dailies I did yesterday are greyed out and still checked. (I haven't done them yet today.)

**Comment by colegleason** [comment]
Hey there. This is actually (currently) intended behavior. Resting in the Inn essentially "freezes time" so cron doesn't run. This is to prevent abuse and letting you just enter the inn before the end of the day.

Discussion of changes to the Inn mechanics are ongoing [here](https://trello.com/c/0KfFF92z/347-inn-full-gp-no-hp-loss-no-xp-gain-xp-gives-level-up-attributes), so please voice your opinion if you have ideas for other ways it should work!

**Comment by ACRPG** [comment]
Thanks for your reply. Are your Dailies supposed to be colored while you are checked into the Inn? I thought they were supposed to be greyed out, and that being greyed out indicated that they would not cause damage.

**Comment by deilann** [comment]
No, they aren't greyed out. I stops cron from happening at all. So it
doesn't disable the dailies, turning them grey. They remain colored.
