### ISSUE TITLE
Suddenly dead after dailies didn't record

### ISSUE THREAD

**Issue by Draayder** [HabitRPG/habitica#2783]
I lost a little over 4200 treasure and my absurd party robes broke (I thought they weren't supposed to be breakable). I've fixed all my stats and got my robe back but man that was a shock to wake up to. UID 2c4a0ad2-edac-4847-bd10-9ff98ea23d14

**Comment by colegleason** [comment]
I'm glad you were able to fix stuff! Please follow the issue here at #2601 

Were your robes back in the shop?
