### ISSUE TITLE
/members/{uid} returns empty objects

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2784]
We return the following fields which I don't think should be publicly exposed or should just be removed:
- purchased
- invitations
- filters
- history
- preferences.dayStart, hideHeader, etc...
- items.food, mounts, pets, lastDrop, eggs, gear.owned, special

Most of these are just taking up bandwidth since we only use them to collapse into numbers like countPets, etc.

**Comment by lefnire** [comment]
are some of these empty objects? I think this might be because of `minimize: false`, it returns empty objects even where a projection pares down the model ([code](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L299))

**Comment by colegleason** [comment]
Yeah, some of these are empty (like history). We should remove them anyway just to stop confusion.

**Comment by Alys** [comment]
Is this still under consideration? I have no problems with removing the empty objects, but some of the other things are very useful for user support. dayStart and sleep are invaluable when helping with daily-reset issues, disableClasses is often useful when people forget they've disabled it, and some of the other preferences items can be useful too. The counts of specific types of drops and the lastDrop time help with troubleshooting drop issues and browser caching issues ('yes you DO have a golden potion, just refresh and you'll see it"). I don't see these things as needing to be hidden for privacy, and user support would become harder without them.

You could make a case for making them visible to only moderators, but non-moderator users help with support too - it's one of the ways they develop enough experience with support and with Habit's code/data structures to move up the contributor tiers.

**Comment by deilann** [comment]
So agreed. I can't see any reason those necessarily interfere with privacy,
and I am a huge habit privacy advocate.

**Comment by deilann** [comment]
Purchased however, filters... those aren't so good to be public maybe.
Purchased I'd like to be able to see for support, especially when users
cant find the gold for gems.

**Comment by Alys** [comment]
purchased, history, and invitations are always empty when I look at anyone's data through the "members" route so there's no privacy leakage there. They'd be useful for moderator support but I'd consider privacy more important.

Not sure about filters. Is it meant to be the current tags in use? filters is always empty even when I look at my own data through the user route.

**Comment by negue** [comment]
So we can close this?

**Comment by Alys** [comment]
I personally think that nothing needs to be changed for privacy reasons. The empty objects could be removed for neatness but I think that's low priority.

Others might disagree though, so perhaps leave it open for a few days for more opinions.

**Comment by colegleason** [comment]
Agreed with @Alys, sorry for not changing the title originally.
