### ISSUE TITLE
Get an error doing almost nothing

### ISSUE THREAD

**Issue by Klint-psk** [HabitRPG/habitica#2785]
It doesn't look like a serious issue. I was testing some hairstyles when these two messages popped out of nowhere
![captura de pantalla 2014-02-07 22 12 57](https://f.cloud.github.com/assets/6619777/2114451/80f2cd16-903d-11e3-8d97-eb5a62f68700.png)

The text was: "Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

I suppose that it's not important, but it was my first time getting an error.
It also happened on the Social Tab.
![captura de pantalla 2014-02-07 22 16 39](https://f.cloud.github.com/assets/6619777/2114468/b9a5deaa-903d-11e3-8aaf-ad280df98ba2.png)

**Comment by colegleason** [comment]
Thanks for the report. You can see the status of this bug here: #2601
