### ISSUE TITLE
In the Wikia for Mounts

### ISSUE THREAD

**Issue by 7eagle14** [HabitRPG/habitica#2786]
http://habitrpg.wikia.com/wiki/Mounts

The V2 Mounts are hidden for spoilers (which currently only contain Gryphon). However, directly beneath are the Special Mounts which show a picture of the base Gryphon. Perhaps a spoiler directly beneath something hidden is counterproductive...

**Comment by lefnire** [comment]
I'd take this up on the Wiki. Most of the devs aren't very involved in the Wikia, there's a discussions section at the bottom of that page, copy/paste this there and and one of the Wikia contribs will probably jump in

**Comment by deilann** [comment]
Can you take this to the talk page? The Github is for site code -- there's really nothing that can be done from here to change that.

**Comment by deilann** [comment]
Oh, hi @lefnire. Beat me by a few seconds, I see.

**Comment by lefnire** [comment]
A rarity! (I often wonder where you get your throughput/energy, @deilann...)

**Comment by deilann** [comment]
It comes and it goes! (And I have people to gripe at when I get frustrated.)

I'm hoping to close another 50 tickets today!
