### ISSUE TITLE
Translate, yeah, but where ?

### ISSUE THREAD

**Issue by ZanyMonk** [HabitRPG/habitica#2787]
Hi,
I can't find translation files/directory. Where is locales directory whose Lefnire's translation tutorial video talks about ?
Thank you in advance.

**Comment by ZanyMonk** [comment]
Found in habitrpg-shared, is it okay ?

**Comment by colegleason** [comment]
yup, it all got moved there recently. The video is out of date.

**Comment by ZanyMonk** [comment]
Okay. French translation will be pushed soon ; )

**Comment by marcelosizer** [comment]
@ZanyMonk it's on the [habitrpg-shared repository](https://github.com/HabitRPG/habitrpg-shared).
