### ISSUE TITLE
Improbable death- three dailies undone, on quest with 40 health

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2788]
This morning I came on to HabitRPG to find that I had died. Upon clicking through the notification, many of my dailies were still checked (but not all) and my to do list was duplicated. As I left it last night, I had 40 HP, and three dailies undone. Trapper Santa hit me for 16.2 damage, meaning that my undone dailies would have taken 23.8 HP?  Could you please have a look into this for me? I'd be very grateful!

Cheers.

My ID: 96ea9e6a-6e05-4766-b9af-de1fbd6d1d4f
My empty party ID: b7c6cff7-d88d-4d39-9e65-ce1741de75b4

**Comment by deilann** [comment]
You can follow this issue here: https://github.com/HabitRPG/habitrpg/issues/2601

Also, you can use "Fix Character Values" in Settings to give yourself back your XP & Gold (and the gold for any equipment lost)

Chances are, some of your dailies did not save to the server.
