### ISSUE TITLE
Wrong equipment item lost on death (server loses diff gear than client)

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2789]
Today I died at rollover. A dialog indicated that my robe had broken, and I could see that I had my hat but not my robe. I repurchased the robe. Later, after reloading again, I was wearing my robe but my hat was gone (not in inventory, repurchasable). My HP, XP, and gold were unchanged so it doesn't look like I died a second time.

UUID: 9b508a2e-1d1b-44ee-a437-266583e756e3

**Comment by lefnire** [comment]
I think the bug is that the client/server are handling differently which item was lost. Will investigate later

**Comment by Ulfethinn** [comment]
I've had similar problems wherein upon death I'm told that equipment 'x' is broken and instead 'y' and 'z' are. It has happened twice now, and every other time I've died it's been effectively the same with the exception of only one item being lost.

**Comment by brightbold** [comment]
Yep, confirmed. Two members of my party suffered quest-death today and this happened to both of us.

**Comment by octern** [comment]
So, should this be "two items lost on death" instead of "wrong item lost on death"? Or does the first item that was lost reappear when the second one breaks?

**Comment by brightbold** [comment]
It's definitely "wrong" not "two." My notification said I'd lost my gold armor, but later when I checked, the gold armor was there but the red helmet was gone. I didn't check my inventory right after the notification, so I don't know if it initially showed the gold armor missing or not.

**Comment by lefnire** [comment]
`predictableRandom` is probably just picking up some stat that exists on the client which doesn't yet exist on the server when it's run

**Comment by colegleason** [comment]
Ah yes, that makes sense. We should take a look at what we seed that with.
When you die, what is a good stat to use that will be the same on
client/server? Probably user.stats without HP, GP, or XP.

On Wed, Feb 12, 2014 at 11:22 AM, Tyler Renelle notifications@github.comwrote:

> predictableRandom is probably just picking up some stat that exists on
> the client which doesn't yet exist on the server when it's run
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2789#issuecomment-34892520
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by Ulfethinn** [comment]
not sure if this is worth mentioning, but I died, i lost the short sword both according to my inventory, the notification, and the store, and upon reloading the page the inventory and store changed to saying i was missing my ski-sassin pole

**Comment by Ulfethinn** [comment]
if that helps somehow

**Comment by TwasBrillig1** [comment]
I noticed the same thing as @Ulfethinn - I suspected it last time I died and took screenshots this time to confirm it.

Upon death, the notification said I lost my Morningstar, which was also missing from my inventory. Later (I don't think I actually did a hard refresh, but after a sync at the very least) the Morningstar was back in my inventory and one of the Rogue armour pieces was gone. (I'm Mage atm, so neither of them showed up in my rewards area anyway.) 

I can add inventory screenshots if they will help.

**Comment by AineMedias** [comment]
It seems mister Creeper here has the same thing.

Upon death, the notification stated that I lost my Golden Sword, but it was still there when I looked at my Inventory (It was still equipped!) Strangely enough, it was in the shop the first time I looked at my Tasks. Second time I looked at my Tasks though, my Chain Mail was in the shop. I noticed no duplicate Chain Mails after I bought that item, so I could say I lost my Chain Mail instead of my Golden Sword.

**Comment by AineMedias** [comment]
Confirmed! I lost my Chain Coif instead of Bunny Ears. It stated that I lost my Bunny Ears, but my Chain Coif was in the Shop. My Bunny Ears were not equipped until I did a to-do.

**Comment by Clariel** [comment]
Not sure if it's helpful to say, but this is still happening

**Comment by deilann** [comment]
Yeah, nothing's been done to alleviate it, so I would assume it's still
happening. But still good info to have.

**Comment by thepeopleseason** [comment]
Doing some investigating on my local server, and I found the following: 
- Purchase all of the armor, and a sword. 
- Force a death: Plate armor reported to be lost. Check inventory: Plate armor indeed gone. 
- Force another death: Red Armor lost. Check inventory: Red Armor indeed gone. 
- Force another death: Chain Mail lost. Check inventory: Chain Mail gone, Plate Armor back.
- Force another death. Chain Mail lost. Check Inventory: Plate Armor gone, Sword gone. Red Armor back.

**Comment by vnapolnova** [comment]
Happened to me today.
I had all class equipment bought out plus subscriber and spring items. And wearing a costume(not sure if thats helpful).
the popup told I had lost top level weapon(hook sword) and it wanished from the avatar.
When I clicked on marketplace instead the lowest level armor plate was missing.

**Comment by Alys** [comment]
Another instance of this was reported in July 2015: https://github.com/HabitRPG/habitrpg/issues/5659
