### ISSUE TITLE
Mulitple Blank, Un-deletable Habits 

### ISSUE THREAD

**Issue by Benjenzo** [HabitRPG/habitica#279]
New to this game, so when I was making "Habits" suddenly over 70 blank habits that I could not delete were there. Refreshing doesn't help.

**Comment by StanLindsey** [comment]
This is a known issue but thanks for bringing it up - we thought we had improved this. @lefnire will know more about the current state of this issue.

**Comment by lefnire** [comment]
And now?

**Comment by Benjenzo** [comment]
now its fine :) @lefnire  thanks! :D

**Comment by Pandoro** [comment]
Considering it is fixed, I'll close this. Let's hope we won't need to reopen it :)
