### ISSUE TITLE
Slightly invisible pet: feature?

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#2790]
This might be a new feature, but I just upgraded a pink bear to mount and now the pink bear pet looks kind of invisible.  Is this a new feature?  Love the improvements, btw, for example, unfeedable pets.

**Comment by deilann** [comment]
Yes, this notes that you have previously owned the pet, letting it count towards Beastmaster. :)

**Comment by cleave29** [comment]
Awesome.   Thank you.
