### ISSUE TITLE
Donated a week ago. Gems MIA

### ISSUE THREAD

**Issue by stupadbear** [HabitRPG/habitica#2792]
I donated again and it's been just about over a week since. Sent you a mail about it and mentioned it in a comment in my thread about last time it happened-

I know paypal is finicky for you and should've used my card, but alas, i was younger and stupider. Could you run the script for me?

My ID is 4521379a-69cf-4d3b-aade-c073d32bd065
My nickname is Stupidbear

Thanks and keep being amazing!

**Comment by deilann** [comment]
Taken care of according to https://github.com/HabitRPG/habitrpg/issues/2454
