### ISSUE TITLE
Make "weeks" button sticky in due date calendar

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2793]
When assigning a due date to a To-Do, there's a "weeks" button that shows a number along the left-hand side for each week of the currently displayed month. It defaults to being on. I don't have any use for those numbers, so I prefer the cleaner look where it's turned off. However, clicking that button doesn't persist to anywhere else--if I uncheck it on one task, then go to edit another task's due date, it's punched in again.

**Comment by Alys** [comment]
The weeks button no longer exists. Closing.
