### ISSUE TITLE
User HP - rounding inconsistency

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2794]
I'm at something between 29 and 30 HP right now, apparently. On the display at the top of my screen, it says 30, but when I look at my stats page or click on my name in chat it says 29. I don't know which is 'preferred' (I assume 29 is the result of rounding to the nearest integer, while 30 is rounded up), and it's a minor thing, but it would be nice to have the two numbers agree.

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/2772

**Comment by casicastiel** [comment]
Wait, I'm an idiot, someone already [posted this](https://github.com/HabitRPG/habitrpg/issues/2772). I guess my search didn't find it. Never mind.

**Comment by casicastiel** [comment]
Ha, you beat me.

**Comment by deilann** [comment]
At least you searched! :D Love to hear that.
