### ISSUE TITLE
Subscribed to HabitRPG with no money.

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#2797]
I went to subscribe to HabitRPG last month and I was looking for a way to pay by paypal. I couldn't find so I just closed the window and went to bed. I have been meaning to use a credit card and finally had time yesterday. When I went to subscribe, habitRPG subscribe page says I am already a subscriber.  
![subscribed when not](https://f.cloud.github.com/assets/5649804/2118257/fac795ea-90fb-11e3-9be7-f8c54792359c.png)

Do you want me to unsubscribe and try to subscribe again? Oh and can we pay with paypal?

**Comment by paglias** [comment]
You should be able to pag with PayPal but not on beta, for now.
Il 08/feb/2014 21:03 "clmmerrill" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
Uh oh, will look into. Thanks for the honesty!

**Comment by lefnire** [comment]
@clmmerrill what's your UUID? Wanna check that you didn't' actually subscribe via Stripe

**Comment by clmmerrill** [comment]
2b44124d-f9bc-49a9-bc97-26e5b3cd099c  I don't know what Stripe is. But, hey if I have money there, then let me know =)

**Comment by lefnire** [comment]
Ok, so you definitely have a legitimate & active credit-card monthly subscription, I looked you up in Stripe. Stripe is the credit-card processor we use, it's all handled off-site (not through HabitRPG) but _on the HabitRPG page_ - this way we get a seamless experience, but uber security without having to worry about haxors. Anyway, recommendation is to keep doin' what you're doin' if you're a happy subscriber, else click 'unsubscribe' and Stripe will remove your ccard from the records

**Comment by clmmerrill** [comment]
Does it say when it started? I will look up on my card statement. The first
time I clicked on the subscribe button was the first day. I don't think I
tried again until this month (february).

Cindy Merrill
clmmerrill@gmail.com

**Comment by lefnire** [comment]
Plan created Feb 9 (yesterday), but Stripe is always super ahead (don't know where their servers are) so makes sense if you first noticed this 2 days ago. Shows one payment made on that date, 2014/02/09 01:53:47
