### ISSUE TITLE
Golden dragon pet turned into mount with saddle, removed pet entirely instead of greying it out

### ISSUE THREAD

**Issue by Willetton** [HabitRPG/habitica#2798]
I used a saddle to turn a golden dragon into a mount, and instead of greying out the pet it was replaced with a pawprint, as if I never had the pet.

**Comment by colegleason** [comment]
Hmm, that's odd. Is it like that if you refresh?

**Comment by deilann** [comment]
I may not have changed the saddle mechanics. I'll look in a sec.

**Comment by Willetton** [comment]
It has been like this for a while, it was made into a mount a couple weeks ago.

**Comment by lefnire** [comment]
Oh, in that case - @deilann's fix is rather recent, the fix hasn't been applied retroactively. I'm not sure it's super critical, since it's just a visual thing

**Comment by deilann** [comment]
Oh, well, there's the answer. That was before my fix.

**Comment by deilann** [comment]
YOU DID IT AGAIN @lefnire

**Comment by lefnire** [comment]
Ha! I think I'll start keeping my answers to the highly technical stuff, or stuff that's waiting for a spell (meaning you're asleep ;)

**Comment by deilann** [comment]
Although -- it's not entirely visual, don't forget. A retroactive fix would
also make sure that people would be closer to Beastmaster if they have a
mount of a pet that they don't currently have the pet of. :P

I also may be slow on responses for a bit, as I'm about to go code in like,
10 quests.

**Comment by lefnire** [comment]
!!! Cool man! You know the process? It's very simple, but the only tut out there is a 30m overkill video

**Comment by deilann** [comment]
I'm about to learn the process. :P
