### ISSUE TITLE
Habits list repeat

### ISSUE THREAD

**Issue by rowanmikaio** [HabitRPG/habitica#280]
I added a new habit yesterday and today I had 338 copies of that new habit in my habits.  I tried refreshing/deleting a few times, and the third time (after logging out and back in) I deleted them instead of going away, the boxes all stayed but they're blank and gray, rather than the yellow color and having the text they had before.  Refreshing does not change this again.

Safari 5.1.7

**Comment by rowanmikaio** [comment]
And I fail at reading other stuff first, apparently.  That's what I get for reading the 'current' and 'critical' but not just the most recent stuff.

**Comment by W1ndW0lf** [comment]
I can confirm.  Got this bug today.  I tried deleting one of the duplicates and it deleted all of them including the original.

Additional: Empty multiple frames remain of the one I deleted.  My gold also shot up from 1 to 14.

Tried using both Chrome 24.0.1312.57 and Firefox 9

**Comment by spaboleo** [comment]
![habit_rpg](https://f.cloud.github.com/assets/3388603/117724/a2af51f0-6c52-11e2-9680-1766a3f9570e.png)
Got it to...1224 copies of one.

I delted one of them, as suggested above, but the "frames" of the items still remain :(
It's just the border no text and it's gray inlcuding the checkbox and the nonfunctioning delete and edit button.

**Comment by W1ndW0lf** [comment]
Seems to have gone for me.  All back to normal as of 10:00 GMT

**Comment by lefnire** [comment]
this should stop coming back to haunt us one we have model.update(), but
fixed for now

**Comment by spaboleo** [comment]
Thanks a lot! :) :+1:

**Comment by lefnire** [comment]
np, sorry about it guys
