### ISSUE TITLE
Chain Coif Missing A Pixel

### ISSUE THREAD

**Issue by Ryanman7** [HabitRPG/habitica#2802]
When viewing the Chain Coif helmet item in the reward shop, I can see that it is missing a single outlining Pixel on the inner part of the helmet on the right side.

**Comment by tmas** [comment]
I'm looking at the image, but I'm not seeing a missing pixel... Could you send a screenshot if this is still a problem?

**Comment by Ryanman7** [comment]
Yeah for sure
![missingpixel](https://f.cloud.github.com/assets/6628884/2143657/cb30755a-9375-11e3-89bc-ad4cf7ebbeb7.png)

**Comment by tmas** [comment]
In the develop branch, the corresponding pixel is also missing. Based on that, I think someone made a design choice and missed deleting the second pixel, then went back to delete it after realizing their mistake. Assuming this is correct, this should be resolved next time they pull in the latest changes from HabitRPG/habitrpg-shared.

**Comment by Ryanman7** [comment]
Okay thanks. Just thought i'd mention it in case it was unnoticed.
