### ISSUE TITLE
Give Warrior a "tanking" ability

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2804]
The Warrior's class abilities are quite bland, at the moment--three stat buffs and a task threat reduction/boss damage spell. None of these are unique, and in general they're less effective than you'd expect because (a) STR barely does anything, and (b) CON doesn't protect against bosses. Stealth, Chilling Frost, and healing are cool things that other classes can do that nobody else can: what's Warrior's thing?

Here's a suggestion: remove one of the bland stat-buff spells from Warrior, and give them a spell that targets a party member and allows the Warrior to take damage in their place. It could work like Stealth, in that every X points of CON you have lets you redirect one hit before the spell expires.

This would become really useful and popular once "death boots you from Quests" is implemented!

**Comment by deilann** [comment]
Would rather see a damage reduction spell-- basically rather than buffing CON, the spell would actually reduce everyone's damage by a percentage based on a stat.

**Comment by lorian** [comment]
I actually REALLY like SabreCat's idea; it would, imo, actually make warrior an appealing class to play for me, especially if STR was changed to boost crit chance as was discussed elsewhere.

While having a party buff that reduces damage for everyone could work, it lacks the interesting tactical choices of a taunt spell. Which party member do you use it on? How sure are they that they'd die? How sure are you that you can take the hit? These are exactly the fun types of choices that habit is missing, in its spells.

**Comment by quin-jay** [comment]
To me it seems more intuitive to have the Healer be a tank, as their primary attribute is CON. Right now both Healers and Warriors have a "buffs party's defense" spell -- What if we buffed that for Warriors (because right now it's only "moderate") because (outside of Habitica) warriors are good with tactics and thus come up with better defense plans, and swap out the Healer's spell to take advantage of their natural tankiness?

(also, FWIW, it looks like Rogues only have 1 party-buffing spell right now, so maybe there's room to shuffle things around with that in mind as well)

**Comment by Ripfrost** [comment]
I was hoping there’d be a discussion like this, mind if I try adding my two cents?
 I agree with lynnyliz CON and tanking in general should be a Healers area of expertise. Also I think the Warrior’s skillset and to a smaller degree the Healers skill “Searing Brightness” need to be changed to follow suit with the Rouge and Mage skillsets which are based interlay on their primary stat with their secondary providing helpful benefits without directly improving the skills, or working in a joint effort with the primary stat the way the healers two healing skills work.

Ex:
Rouges: Have high PER for skills and get extra gold and drops but compliment that with high STR and an enhanced critical hit rate (assuming that’s been added). 

Mages: Have high INT for skills and getting extra EXP but compliment that by adding even more boosts with their PER. 

For that reason I think Defensive Stance and Intimidating Gaze need to be altered to be STR orientated or better yet changed all together considering how both pale in comparison to Protective Aura.

Looking at all of the class skills together there seems to be a bit of a trend.

Damage move:             Brutal/ Burst/ Backstab/ Searing(kinda)
Primary skill boost:        Valor/ Earthquake/ Tools/ Aura
Insurance Tactic:          ????/Chilling/ Stealth/ Healing
Specialty:                       ???? /Ethereal/ Pickpocket/ Blessing

My suggestions are :
1.  Make Intimidating Gaze an “Insurance Tactic” for boss battles where it’ll temporarily lower the bosses attack multiplier based on the users STR.
2.  Make Defensive Stance the “Specialty” move scraping the CON boost and turning it into a parry attack with a higher MP cost. It would work similar to Sabre’s suggestion but would slightly reduce the damage you block based on CON and add a small counterattack against the boss based on STR into the mix.

**Comment by wc8** [comment]
@SabreCat's version would be really useful for a party member who had to rest in the inn for illness. On the other hand, having it help all party members to some degree (who might be taking damage for an ill person's incompleted tasks) also makes sense.

@Ripfrost + 1 for _Parry_ wording. If a small thrust/counter attack is included in the skill, it could possibly be called Parry-and-Thrust.

@lynnyliz I'm not sure why a Warrior protecting his party doesn't make as much sense, if not more, as a Healer doing so. Theme wise, the Warrior would address incoming damage (ward), and the Healer would address existing damage (heal).

**Comment by wc8** [comment]
P.S. I really like the idea of the Warrior _taking damage_ for his fellow party member. :+1: @SabreCat 
In that case, I would not make the mana cost higher, since, there's a loss of HP, right?

**Comment by Alys** [comment]
I'm closing this now that https://trello.com/c/TjZc6PnC/466-skills-v3-stat-rebalancing exists.
