### ISSUE TITLE
Duplicate credentials?

### ISSUE THREAD

**Issue by MaxHedrm** [HabitRPG/habitica#2806]
It looks like I have duplicate credentials. The same Username (MaxHedrm) and password, with 2 different API UIDs. Very odd. Do you think I can just delete the one I don't want?

So, the one I want to keep:
b7fd010e-bf83-47af-a2a1-70144c224b93  --  lvl 34

The one that can go away:
0e4dac74-75ad-4bb3-a588-d7e6987d65d0 -- lvl 1

I'm betting the duplicate came from when I set up the iOS app. :-/

**Comment by lefnire** [comment]
First one is a facebook auth, to access it you'll need to just use the facebook button (or on mobile, use the "use api & token" checkbox until we get that fixed). See http://habitrpg.wikia.com/wiki/FAQ#Switch_from_Facebook_authentication_to_Username_.2F_Password if that rubs you wrong

**Comment by MaxHedrm** [comment]
That's odd, since I don't recall ever setting up facebook auth. :-/ And I'm pretty sure I managed to log in to the Mobile without the Api UID. Very odd. Oh well.

So, yes, I suppose it does rub me wrong, but there's a workaround. Thanks for the info.
