### ISSUE TITLE
Failure to sync?

### ISSUE THREAD

**Issue by neosaiyanangel** [HabitRPG/habitica#2807]
I have two different computers, and I was splitting Habit RPG's use between them. My laptop ended up freezing my account on one day and didn't uncheck the tasks on the new day, but it did activate the ones set for specific days. I'd left the window open, figuring that I could sync whenever I needed. So I shut it down and went onto my other computer to try and do my habits. I found that my account actually hadn't updated for numerous days and that all the progress I'd made was gone, and I died from it thinking I didn't do my dailies.

**Comment by deilann** [comment]
If the sync isn't working for you, refresh the screen, preferably a "hard" refresh (without cache). This does a better job than the sync button.
