### ISSUE TITLE
Rewards with a negative price allow to win money

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#281]
When we define a rewards with a negative price (ex: cake, -1 gold) and we buy it, wa do win +1 gold.

Right, that is cheating (and quite doom for a game like this), but it might not be hard to fix.

**Comment by Pandoro** [comment]
This should have been fixed a while back. As well as some other bugs that have been coming up again regarding the duplicate items. @lefnire could it be the case that something went wrong while merging some branches lately? I have the feeling we went back to an older version of the game, causing this and other things to be broken again.

**Comment by lefnire** [comment]
No, dupes should be be fixed again. Always some edge case I haven't
accounted for in refLists. This particular thing, a pull request was
submitted for <0 values but which also effected other tasks' values going
below 0, and so was revoked (I don't know if he's still working on that).
We just added HTML5 min & type=number attrs as stopgap.

**Comment by abednego** [comment]
lol, I'm a big cheater now.  Well, the good news is I can buy a lot of episodes of Breaking Bad now.  (Got a late start, good show, added watching an episode as a reward...)

_giggle_

Tested it.  Created a reward with a value of -10 gold.  Added 10 gold to my account.

**Comment by Pandoro** [comment]
I'm closing this as it is the same issue as #47 Please post further comments in there.
