### ISSUE TITLE
To-Do due date calendar obscured by rewards with Weeks button active

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#2810]
I'm using Chrome version 32.0.1700.107 and OSX Mavericks, and I find it hard to add due dates to To-Do items with the Weeks button activated.

![screen shot 2014-02-10 at 11 39 29 am](https://f.cloud.github.com/assets/6640915/2127724/2c5ecfca-9272-11e3-8a40-1fb1651a3c88.png)

Granted, un-clicking Weeks makes it work just fine, but I've been dealing with this for a month without thinking to try that and this feels like a pretty simple fix. Is there some way to alter the code so that the calendar displays in front of all other page elements?

**Comment by lefnire** [comment]
Fixed on `develop` (which you can see at https://beta.habitrpg.com), and will be merged into master in coming days

**Comment by deilann** [comment]
Curious-- what does this look like on beta for you?

**Comment by deilann** [comment]
...thank you email, for not telling me about Tyler's responses. XD

**Comment by lefnire** [comment]
@deilann no worries. we're live now anyway, so all set

**Comment by quin-jay** [comment]
You guys work extremely quickly and I am super appreciative. I'm gonna poke around a bit and see if I can contribute anything in return, with my cursory knowledge of CSS
