### ISSUE TITLE
Missed Tasks

### ISSUE THREAD

**Issue by ruinofeventide** [HabitRPG/habitica#2811]
Hi,
I am wondering if there is any way to fix something on the HabitRPG or not.  I did my tasks yesterday, however, I wasn't able to put them into HabitRPG as completed (checked off) due to being so busy and falling asleep last night.  This morning I lost all my health, all my gold, and equipment, despite the fact I did my tasks and wasn't able to report it to the system.

Is there any way I can go back in and fix the tasks to show I did them yesterday where I won't lose all this?  Or am I just out of luck?

**Comment by colegleason** [comment]
Hey,

we don't currently have a way to edit the previous day's activity. You can
modify your stats though.

You can fix the streaks on your dailies by editing them. To restore level,
health, and gold go to Settings -> Fix Character Values. You can also give
yourself extra gold to buy back your old equipment.

On Mon, Feb 10, 2014 at 11:43 AM, ruinofeventide
notifications@github.comwrote:

> Hi,
> I am wondering if there is any way to fix something on the HabitRPG or
> not. I did my tasks yesterday, however, I wasn't able to put them into
> HabitRPG as completed (checked off) due to being so busy and falling asleep
> last night. This morning I lost all my health, all my gold, and equipment,
> despite the fact I did my tasks and wasn't able to report it to the system.
> 
> Is there any way I can go back in and fix the tasks to show I did them
> yesterday where I won't lose all this? Or am I just out of luck?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2811
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by ruinofeventide** [comment]
Thank you so much!  I was able to put everything back to normal.  :)  I greatly appreciate your help.
