### ISSUE TITLE
Username/level text small/misaligned

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2812]
Not a bug, per se, but an annoyance: the username text on group pages and the level numbers seem uncomfortably small, both compared to the gray boxes around them and to the other text on the page.

![screen shot 2014-02-10 at 4 55 23 pm](https://f.cloud.github.com/assets/6208739/2131282/51aa45b2-929e-11e3-944c-2210e0463c04.png)
![screen shot 2014-02-10 at 4 55 53 pm](https://f.cloud.github.com/assets/6208739/2131283/51b0f1f0-929e-11e3-9aec-29ade3f7a56c.png)

**Comment by deilann** [comment]
This is known; I brought it up here: https://github.com/HabitRPG/habitrpg/pull/2636
