### ISSUE TITLE
My baby gryphon grew into a mount... and flew away???

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#2814]
I fed my gryphon its last blue cotton candy food to grow it into a mount, but when I went to the mounts page, its not there. On the pets page I the blue gryphon is ghosted per Ryan's new code and the pet disappeared from my avatar (because I no longer have that pet), so both those are working properly. I can see the gryphon row on the mounts page, but it's empty. I've tried syncing and checked both beta and regular Habit, but my awesome gryphon mount is no where to be found. Where did it go?

**Comment by deilann** [comment]
guessing this has something to do with #2801

**Comment by lefnire** [comment]
fixed, see commit. @brightbold I added CCB-gryph to your mounts

**Comment by lefnire** [comment]
(nice catch @deilann )

**Comment by brightbold** [comment]
Thanks! That was fast.
