### ISSUE TITLE
Pets and mounts are weirdly spaced

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2815]
Pretty sure it's a problem with my pet/mount count/display change, but I can't find what's actually making it look like that. The only thing I changed about the standard pet display was the list of eggs it was using, and I changed even less with the mount display.

**Comment by deilann** [comment]
No, it's a BS3 thing, I think.

**Comment by lorian** [comment]
Oh phew! (well, I mean, still the same problem, but at least it's not something I did.)

**Comment by paglias** [comment]
Screenshot? This is also reported somewhere else @deilann ?

**Comment by deilann** [comment]
I can't give you a screenshot at the moment, but I mentioned it on the BS3
PR.

**Comment by lorian** [comment]
These are on Firefox; not sure if it's specific to browser.
![1_33_inventory](https://f.cloud.github.com/assets/2963633/2141495/ca721748-9359-11e3-8566-e87da6b8efef.jpg)
![1_32_inventory](https://f.cloud.github.com/assets/2963633/2141497/ccc7c768-9359-11e3-93d9-62f491fc4e6c.jpg)

**Comment by benmanley** [comment]
It's happening on Safari too. Safari is also jinking up pets that have been raised into mounts (see the pink cactus below).

I think it's some sort of inconsistency in rendering the `margin-top` value that has been applied to `.PixelPaw`. In Chrome, this value pushes the paw sprite into line. In Firefox and Safari, it pushes the whole row down without moving the paw sprite relative to the row. Not quite sure if there's a cross-browser fix. 

![screen shot 2014-02-11 at 21 17 11](https://f.cloud.github.com/assets/3317594/2142301/e0a50850-9362-11e3-8876-559086d86e14.png)

**Comment by benmanley** [comment]
I reckon I can fix it by absolutely positioning the paw sprite instead of using `margin:top`. But I'm not sure how to target pets that have been upgraded into mounts to fix the weird Safari behaviour.

@deilann Do you know what class is applied to pets that are now mounts?

**Comment by deilann** [comment]
No class is applied. Their value changes from 50 to -1

**Comment by benmanley** [comment]
Thanks @deilann. I see. 

Looks like there are styles being applied via `stable.jade` that would be better off in a stylus file if possible (but nothing that should effect positioning). If we can apply a class, we might be able to fix the Safari bug from there.  

I'll submit a PR to fix the paw sprite issue and raise a separate issue/PR for the jade file.

**Comment by benmanley** [comment]
@paglias @deilann I've set up HabitRPG locally. Is there an easy way to cheat items like food, potions and eggs, or add gems? I need to unlock a few pets and mounts for testing purposes. Thanks.

**Comment by deilann** [comment]
Debug buttons on the bottom!

**Comment by benmanley** [comment]
Ah. Thanks!
