### ISSUE TITLE
To-do checklist XP and gold are incorrect

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2816]
Related to #2629 - to-dos only give full XP and gold when all checklist items are ticked, although full mana is always awarded.  If a completed to-do with full checklist is unchecked, only the "container" to-do XP, gold and MP are reversed.
(Don't know if this is browser dependent; I'm seeing this on both Firefox and IE on Windows 7.)

**Comment by deilann** [comment]
That's currently intended, as people might have "extras" on the list that they do not complete. The MP thing is what #2629 is about. It shouldn't be browser dependant, and this would be an expected reversal, if no items were checked off upon reversing it. This conversation would be better suited on #2629
