### ISSUE TITLE
XP not leveling up

### ISSUE THREAD

**Issue by 0xRoM** [HabitRPG/habitica#2817]
Hi,
after defeating the gryphon, my XP now says 205/200
I presume it just adds it but doesn't check weather to do a level up or not.

![habbit_bug_01](https://f.cloud.github.com/assets/1678085/2136802/2dd80e3c-9319-11e3-974f-ef13cc2e8788.png)

**Comment by deilann** [comment]
This is a known issue. Completing a quest doesn't update states. Clicking any task will level you up; you won't lose any XP. See: https://github.com/HabitRPG/habitrpg/issues/2433
