### ISSUE TITLE
Unable to add new tag

### ISSUE THREAD

**Issue by yara-simargil** [HabitRPG/habitica#2818]
I've deleted all default tags (morning, evening..) and tried to add new one with no result - nothing happens when I press 'Add' button and there are no requests to server.
![2](https://f.cloud.github.com/assets/1819404/2136810/563a99a8-9319-11e3-8409-4cb1de2be181.png)

But there are errors on the page:
![1](https://f.cloud.github.com/assets/1819404/2136809/50d12d92-9319-11e3-9600-c21ff50a40de.png)

**Comment by deilann** [comment]
H'm. Those errors appear to be unrelated. They're analytics and ads.

**Comment by Gryffkin** [comment]
I am also unable to add a tag.  I'm using Chrome and Safari on OSX 10.8.5.

**Comment by LittleRabbitBeta** [comment]
I have not been able to add tags. I'm using Safari on OSX 10.7.5 and Chrome on some PC at work. neither works.

**Comment by SugarShin3** [comment]
When I hit the "Add" button for a new tag, it doesn't register. I realized this, so I tried out hitting my enter key. Sends it through fine that way. Obviously the "Add" button needs to get fixed, but for the meantime, that works. Running Firefox on Windows7.

**Comment by LittleRabbitBeta** [comment]
@SugarShin3 thanks for the workaround!
