### ISSUE TITLE
Can't buy back limited edition gear after dying

### ISSUE THREAD

**Issue by hanasaseru** [HabitRPG/habitica#2819]
My character died and I lost my limited edition winter gear yeti-tamer spear. However, the spear does not appear in my list of rewards to buy it back. It occurred to me that I've also changed class since buying it (warrior to rogue), so is it maybe just not available to me because I'm the wrong class? (If so, will it reappear next time I pick up the warrior class, or is it gone forever?)  My UI is 46c8d810-e0cf-4f8c-b78d-8d9a8eac0f77

**Comment by lefnire** [comment]
Yes, that is the case. You can only buy the gear of your class, and nonclass special gear. When you roll warr again you'll see it

**Comment by hanasaseru** [comment]
Thank you so much! Sorry to trouble you for what turned out to be nothing.
