### ISSUE TITLE
Tags overlay scroll bar for party members

### ISSUE THREAD

**Issue by mrabinovsky** [HabitRPG/habitica#2821]
Pic: http://snag.gy/TysgQ.jpg
Steps to reproduce:
1.Create a bunch of tags
2. join a multi-member party
3. Re-size window until a scroll bar appears to view all party members
4. try to scroll

What is expected: scroll bar scrolls to the right/left and you can see all the members
What is happening: You highlight the tag and can't access the scroll bar.

Browser: Mozilla Firefox 26
OS: Windows 8 Pro x64

**Comment by mrabinovsky** [comment]
I believe the reason is because the header's position is fixed and the filters position is relative. I would add a small padding to the top and that should fix it.

**Comment by Mihakuu** [comment]
I noticed this a while ago, you have to scroll down a bit to be able to grab a hold of that scroll bar

**Comment by negue** [comment]
Same as #3011 and I think can be closed now. @Alys  @lefnire  ?

**Comment by lemoness** [comment]
Closing this because it's a duplicate.
