### ISSUE TITLE
Tooltips get cut off

### ISSUE THREAD

**Issue by mrabinovsky** [HabitRPG/habitica#2822]
Pic: http://snag.gy/tvgrX.jpg
feel free to ignore firebug at the bottom I had it open from my previous bug.

Browser: Mozilla Firefox 26
OS: Windows 8 Pro x64

Steps to reproduce:
1. re-size your browser so that anything with a tool tip is close to the left
2. hover over icon to see tool tip

Expected result: Tool tip goes to the right, top, or bottom.
Actual result: Tool tip still goes to the left and gets cutoff by the end of the screen.

**Comment by lefnire** [comment]
unfortunately you can't designate dynamic tooltip/popover placement in bootstrap, so we just have to pick a side to display it on. If the current side is a bad location, hit us with a preferred side

**Comment by lefnire** [comment]
(top, bottom, left, right)

**Comment by mrabinovsky** [comment]
Hmm personally I think top would be the best option given the situation.

**Comment by bunnifluezl** [comment]
This also happens when hovering for the Difficulty tooltip in Habits. Pic: http://i.imgur.com/9LwM37a.png

I tried switching to a wider monitor and it didn't change anything. It's not a huge deal in this case because you can read the same tooltip if you hover over it in the Dailies or To-do sections, but I thought I'd mention it anyway!

**Comment by ghost** [comment]
> we just have to pick a side to display it on

Suggestions from https://github.com/HabitRPG/habitrpg/issues/3215 :
~~1a. Top bar Sync button needs tooltip to the left,~~ (out of question as top bar is having restyle now)
1b Items in the costume column need tooltip to the left.
1c Difficulty tooltip in Habits needs a tooltip to the right.
2. Free space between the in-game items and the right border of the screen might be made bigger to avoid horizontal scrolling.

**Comment by ghost** [comment]
I've just noticed, the problem may need a separate solution for mobile version. 

E.g. as it is now, the items on the market have tooltips being opened to the left, as the market is the right column of the page and everything works almost fine. However when you decrease the window width, the columns are combined in one row and toolips on the left get off the screen.
