### ISSUE TITLE
Shaft of the Dragon does not give stat bonus!

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2824]
Hey guys!  I just happily beat Vice, excitedly equipped my weapon, checked my stats.... and discovered that it isn't giving me any bonus. Refreshing hasn't helped.
EDIT: NOPEEEE it's working now!!! Awesome.

**Comment by lefnire** [comment]
What do you mean? I see 9+25 PER = 34, STR=25. Looks correct to me. Doesn't give class bonus if that's what you mean
