### ISSUE TITLE
unable to see party members or participate in quests

### ISSUE THREAD

**Issue by r00k5A58** [HabitRPG/habitica#2830]
My account has been pretty buggy since creation, but it hasn't bothered me too much. Recently my friends wanted to start quests, and even though I was the one who started the Trapper Santa quest for my party, I wasn't able to see or damage the quest at all. Additionally, I created the party, however I can't see anyone in it, even though they can see me.

user id: d3fba3a8-797c-42b2-8f6d-bec6f3cc5903

**Comment by r00k5A58** [comment]
Not sure what format these bug reports should be in or what pertinent information is needed, so if this issue requires any more information, please let me know.

**Comment by deilann** [comment]
How old is your account? It sounds you like you secretly have 2 parties.

**Comment by r00k5A58** [comment]
I can't find a date on the account or anything, but I've been using it for probably 4-5 months now? I'm really horrible with time recollection. It's possible that I'm in 2 parties, because we tried to make a party pretty early on, but I wasn't able to see anyone, and my wife never got the invitation. So I made another one, it seemed to work and I was able to see her every couple of logins and then I just never saw them again.

**Comment by deilann** [comment]
Okay, so, what I want you to do is leave the party where you can't see
anyone. If you do, by chance, see everyone, do not leave.

Tell me if that fixes it.

**Comment by r00k5A58** [comment]
When I did that last night, it didn't seem to do anything. No matter how many times I left my party it would still show me in that party. However now I can see my party. Perhaps I just needed to wait for the sync after leaving? Not sure.

Thanks for your help.

**Comment by deilann** [comment]
No problem!

In the future, if changes don't seem to stick, go ahead and refresh. Often
old cached info is being loaded.
