### ISSUE TITLE
Top bar darkness doesn't match theme

### ISSUE THREAD

**Issue by AsherVo** [HabitRPG/habitica#2831]
The new top bar is very useful, but it looks very out of place.

I suggest inverting the colors and going with a lighter theme.

boop @lefnire

**Comment by ghost** [comment]
I agree, it's a bit hard on the eyes..

**Comment by deilann** [comment]
I ALSO AGREE.

And I should have the option to make it sticky. (Separate from the header.)

**Comment by deilann** [comment]
Let's move this here: https://github.com/HabitRPG/habitrpg/issues/2835
