### ISSUE TITLE
List Monthly Item as Perk on Subscription Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2832]
The Subscription page needs to list the monthly item as a feature!

https://habitrpg.com/#/options/settings/subscription

I suggest "Unique Monthly Subscription Items" with the text "Each month, all subscribers will get a totally unique cosmetic item for their avatars!"

@lefnire @sabrecat @ any other programmers

**Comment by quin-jay** [comment]
Are you looking for just a text/HTML fix? (If so, adding that label will get even more eyes on it)

**Comment by SabreCat** [comment]
Yup, this is entry level textual stuff! Added the tag.

**Comment by deilann** [comment]
Dunno if it's public code, tho

**Comment by SabreCat** [comment]
Oh, right. Private code. Sigh.

**Comment by lefnire** [comment]
Should be public, private code is just backend

**Comment by SabreCat** [comment]
Ah! Phew. For some reason I couldn't find it before, but searching habitrpg-shared for "individual subscription" turned it up. Adding the tag back!
