### ISSUE TITLE
With UI Update, a habit turned into a daily?

### ISSUE THREAD

**Issue by Popitop** [HabitRPG/habitica#2833]
After the UI update, one of my habits, which I get high scores on repeatedly, changed from a positive-only habit to a checkbox. It's still in the Habit column.

**Comment by wc8** [comment]
@Popitop is this still an issue for you?

**Comment by negue** [comment]
Dupe of #2443 ?

(And I think this can be closed, since there is also no reply)

**Comment by Alys** [comment]
Yup, yup. It can always be reopened if Popitop replies.
