### ISSUE TITLE
loss of mana

### ISSUE THREAD

**Issue by biohazard44** [HabitRPG/habitica#2837]
This has happened a few times and I am unsure of the cause or the solution. My mana has been increasing as I level up so the max mana is in the 80's. I will have my mana maxed out and then it will seemingly randomly reset to having the max be 57 and my mana if full. Then usually a day later it will reset again so the maximum is in the 80's but it says I only have 57. I have not used anything that would have spent my mana.

**Comment by deilann** [comment]
I'm going to guess Perfect Day here. The buff will increase your INT, increasing your max mana. Then, when you lose the perfect day, it goes back down to what you're used to. Does that sound right?

**Comment by biohazard44** [comment]
So if i mis a perfect day my max mana will go down, and then it will return when I get another perfect day. But when it returns I go from having a full mana bar to essentially having a third of my mana gone.

**Comment by deilann** [comment]
Yes. Because your max mana went up, but you still only have 57 mana. You still have the same amount of mana.
