### ISSUE TITLE
Toolbar Icon Issues

### ISSUE THREAD

**Issue by MrSmearkase** [HabitRPG/habitica#2838]
Howdy, I am getting different icons than the intended ones in the toolbar. I am running Chromium on Ubuntu 13.10. I attached a screenshot at bottom. Initially, I thought I just really didn't like the icons, but then I logged in on mobile and discovered they were much nicer there ;)

https://www.dropbox.com/s/79xp9xjo8x5kgwc/Icon_Issues.png

**Comment by paglias** [comment]
I noticed that too but it happens also on other sites like Github, not always only sometimes and they show up correctly when you move the mouse over one of them...

**Comment by lefnire** [comment]
WTF... has it always been this way, or just when we moved to Bootstrap 3?

**Comment by ghost** [comment]
FWIW that happened to me briefly the other day as well on an iPad. And then righted itself.

**Comment by paglias** [comment]
Bootstrap 3 but I believe it's caused by the use of font icons. On other sites I saw it happening it always regarded font icons but not only Boostrap's ones.

**Comment by MrSmearkase** [comment]
Interesting. For me, this is very stable. The icons are always this way on Ubuntu, and they aren't changed by mouse hovering.

**Comment by colegleason** [comment]
I've had issues like this on Github and HabitRPG from time to time.
Something to do with the font file not loading correctly, perhaps?

On Thu, Feb 13, 2014 at 3:51 PM, MrSmearkase notifications@github.comwrote:

> Interesting. For me, this is very stable. The icons are always this way on
> Ubuntu, and they aren't changed by mouse hovering.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2838#issuecomment-35030499
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by MrSmearkase** [comment]
Ah... Welp, I figured it out on my end. I have Chromium set to use the Ubuntu font via this extension (https://chrome.google.com/webstore/detail/ubuntu-1010-unified-font/gmpnnplimbnbmdaigmnajmbdcinhpddj). I disabled that, and now everything is peachy keen.

**Comment by colegleason** [comment]
Hmm, I wonder if I have font extensions.

On Thu, Feb 13, 2014 at 3:57 PM, MrSmearkase notifications@github.comwrote:

> Ah... Welp, I figured it out on my end. I have Chromium set to use the
> Ubuntu font via this extension (
> https://chrome.google.com/webstore/detail/ubuntu-1010-unified-font/gmpnnplimbnbmdaigmnajmbdcinhpddj).
> I disabled that, and now everything is peachy keen.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2838#issuecomment-35031112
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by negue** [comment]
Since the Toolbar was redesigned, can this be closed?

**Comment by Alys** [comment]
Good call negue. The toolbar no longer uses those icons so this can't be an issue now.

@MrSmearkase, thanks for providing the initial screenshot (useful!) and for taking the time to explain your fix! Sorry we didn't say that six months ago. :)
