### ISSUE TITLE
Cannot Sign In through the App

### ISSUE THREAD

**Issue by leeleenat** [HabitRPG/habitica#2839]
Hi,

I believe this is the issue that the person who submitted the previous issue on not being able to "sign up" was referring to.

I'm having problems with the app. 

I can't type anything into the text boxes when I'm signing in.The field disappears, and I can't see what I'm typing in as well.

I can't copy and paste into the UUID and API fields, and typing them in manually doesn't really sounds like fun.

I couldn't sign up through the App, so I joined via my desktop.

I like the game so far on the web, but the app is basically useless to me because I can't even get past the sign-in page.  I couldn't sign up, and I couldn't sign in either.

**Comment by deilann** [comment]
@leeleenat Are you using Android or iOS?

Unfortunately, you do need to manually type in your UUID and API, but (can someone verify this?) you only need to do that once.

**Comment by negue** [comment]
@leeleenat  The problem still there? If not pls close this issue :)

**Comment by lemoness** [comment]
Closing due to lack of response - @leeleenat If you're still having trouble, let me know, and I'll reopen this.
