### ISSUE TITLE
[Suggestion] Mastered habits

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#284]
I would like to see habits/dailies being "mastered" if the success rate is very high or after a streak has been going for a certain amount of time.  These could be given their own area under the habit/daily area.  These mastered tasks could give a small amount of daily XP and gold and wouldn't require being checked every day.  Once a week (or manually), the player could be prompted if they want to revert/downgrade the task back to the normal area for more active tracking.

**Comment by Pandoro** [comment]
I do like the idea, considering I have come to the point where I was annoyed by clicking something over and over again as well. So I would also like to see this at some point in the future, but for now, I think @lefnire has a lot of different stuff he needs to take care of which I think might have a higher priority as they will add new features we cannot simulate by clicking ourselves.

**Comment by lefnire** [comment]
I like the idea

**Comment by horusofoz** [comment]
Excellent idea. Give the user an achievement badge per as well.

**Comment by StanLindsey** [comment]
Throw this baby on Trello!

**Comment by horusofoz** [comment]
Raised as [Trello #144](https://trello.com/c/1d1BqCM1).

Please vote for your idea to see it added.
