### ISSUE TITLE
Cannot order To-Do list properly

### ISSUE THREAD

**Issue by RainbowMagicMarker** [HabitRPG/habitica#2840]
When trying to sort my to-do list I have a fairly large checklist I want to keep at the bottom, however every time I try to sort my To-do's with deadlines by date and keep anything that doesn't have a deadline below those, however when I try to move one to it's new location, that one as well as the two it would have been neighbors with go down to the bottom of my list. They're in the right order but now they're beneath my big checklist. I cannot bring them back up above, they simply revert to the bottom when I release the mouse button, and they cannot be moved until I try to move something else and then those three go to the bottom instead.

Windows 7 on Firefox 24.0 and I have already tried clearing my completed to-dos, it did not fix this issue.

**Comment by deilann** [comment]
If you could still move this to https://github.com/HabitRPG/habitrpg/issues/2606 it would be appreciated.
