### ISSUE TITLE
Icons not displaying properly

### ISSUE THREAD

**Issue by Ulfethinn** [HabitRPG/habitica#2841]
![screenshot](https://f.cloud.github.com/assets/6634364/2167588/41404132-951d-11e3-928d-123de7b16cd8.png)

I just reloaded my page after closing some tabs and I saw what is in the screenshot. It seems like a weird jumbling of some of the pages I closed.

  This is my first time reporting an issue, so if I've made some mistake, let me know.

**Comment by Ulfethinn** [comment]
The icons were like this on all pages: tasks, other inventory screens, the profile page, etc. and it was randomizing with each reload.

**Comment by deilann** [comment]
Browser and OS?

**Comment by Ulfethinn** [comment]
Safari and Maverick, platform is a macbook pro

**Comment by deilann** [comment]
What happens if you use another browser?

**Comment by Ulfethinn** [comment]
The problem ended a few hours after I made the report. I didn't do much experimentation before it cut either. Should I consider this problem null?

**Comment by deilann** [comment]
No, it seems to be a non-mobile version of https://github.com/HabitRPG/habitrpg/issues/2510 which is really strange.

**Comment by deilann** [comment]
Except the images don't even seem to be from the spritesheet. H'm.

**Comment by Ulfethinn** [comment]
It happened shortly, but not immediately after updating to the new OS if that helps

**Comment by deilann** [comment]
That _does_. The iOS image problems happened immediately after an OS upgrade, too.
