### ISSUE TITLE
First valentine card is unreadable

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#2842]
Hi 

It seems that the first card you receive is not displayed in the inventory.
I received two, the first wasn't there but I could open and read the second one.

People in the tavern are saying it happened to them too.

Best regards

**Comment by ghost** [comment]
same thing here, got 1 card and it isn't in my inventory nor anywhere else

**Comment by deilann** [comment]
+1 here

**Comment by caveman1337** [comment]
Are you supposed to write a message in them? The 3 that I sent didn't really show anything other than that it sent something...

**Comment by deilann** [comment]
No, but a card should appear in the recipient's email that they can open
with a prewritten message.

**Comment by lefnire** [comment]
Verified, the first one doesn't stick and everything after does. I don't know why this is happening, I even wrote some unit tests (local) which pass, verifying first card is received. [Offending location](https://github.com/HabitRPG/habitrpg-shared/blob/28a744248c5035b62810731e320cc994530ed5bc/script/content.coffee#L481)

**Comment by deilann** [comment]
Coffeescript is weird.

...just saying.

**Comment by deilann** [comment]
It looks like because the value is null, it converts to [] but doesn't give the valentine. The second card goes through because the value is not null.

**Comment by lefnire** [comment]
If first value is null, it assigns to `[]` but wraps that in `().push(NEW_VAL)`, 2 birds in that step. I tried separating to two lines for kicks, and running the unit test (which I'll push up when I get a chance) and it didn't make a difference. It might be something mongoose-side

**Comment by quin-jay** [comment]
In the interest of de-cluttering the Issues list, does this still need to be open? It looks unresolved, but then again we can't send valentines anymore anyway.
