### ISSUE TITLE
Killed unjustly

### ISSUE THREAD

**Issue by MathewSuta** [HabitRPG/habitica#2843]
On Feb. 12 or 13 (sorry, unsure) I died. I know I shouldn't have, especially because I completed all my dailies and had at 8hp.

**Comment by deilann** [comment]
Are you in a quest? Have you seen "Application Error"? Did you lose any of your streaks?

You can restore your stats through "Fix Character Values" under Settings.

**Comment by Alys** [comment]
Closing because of lack of response
