### ISSUE TITLE
Subscription Gem Cap Bug

### ISSUE THREAD

**Issue by sleepykit** [HabitRPG/habitica#2844]
I did a search for this and don't see a relevant thread. :(

It looks like the 25 Gems cap is per day right now instead of per month as described in the subscription information. 

I tested by buying 25 gems yesterday (with gold) and then being able to buy more today. Yesterday, when I hit 25, it let me know that I was at the cap. Today, it didn't seem to care.

**Comment by weelillad** [comment]
I just encountered this too. I'm not yet sure if the limit resets per day: I last bought gems at the start of the month, not yesterday. The limit could have reset anytime in between. I'll try again tomorrow and report back.

**Comment by lefnire** [comment]
I'll look into this ASAP, super important - thanks for the honesty everyone!

**Comment by weelillad** [comment]
Well I could buy gems again today, even though I bought 25 two days ago. I would guess that the gem cap is resetting every day.

**Comment by lefnire** [comment]
confirmed and fixed (crossing fingers). try again tomorrow?

**Comment by deilann** [comment]
Will do! I guess this means I'll have to buy more gems...

**Comment by weelillad** [comment]
So I bought 25 gems 3 days ago, and 5 more yesterday. Today I could buy only 20 more, which might mean that the bug is fixed. I'll have to try again tomorrow, to be sure

**Comment by deilann** [comment]
I bought 4 gems yesterday, and was able to buy only 21. I as well will
double check tomorrow.

**Comment by weelillad** [comment]
Ok, can't buy gems today. I'm gonna keep trying for every day, and I'll report back if I manage to sneak in any buys before March.

**Comment by deilann** [comment]
Confirming the cap seems to be stable. I'm going to close this ticket, but if anyone notices being able to buy gems again, comment and it can be reopened.
