### ISSUE TITLE
Firefox scroll bar overlap bug

### ISSUE THREAD

**Issue by Earthstar** [HabitRPG/habitica#2845]
In Firefox, on the Party page, the gem indicator overlaps the scrollbar. This behaviour is not found in Chrome. 

<a href="http://imgur.com/QS7gCSn"><img src="http://i.imgur.com/QS7gCSn.png" title="Hosted by imgur.com" /></a>

My user id is 0b0a8159-91bc-4741-ad9d-c378b7d3b950.

**Comment by negue** [comment]
The Interfaces was rearranged "a long time" ago ^^.

I also tested it with IE and FF it is fixed.

@Earthstar if it is still not working for you, we'll reopen this Issue.
