### ISSUE TITLE
Backstab Bug

### ISSUE THREAD

**Issue by BrandonHabitRPG** [HabitRPG/habitica#2846]
When I use backstab, I get an error which includes: Error: No matching document found (See Chrome Console for more details.).  I have a little more gold than I used to, but I also lost my Umbral Armor ( I bought the Umbral Armor earlier today.).  Oh, I got the 15mp back too.
Repeated uses of backstab caused the same error.  I lost no other equipment.

**Comment by lefnire** [comment]
follow https://github.com/HabitRPG/habitrpg/issues/2301 . The solution is to interact slower (give 1-2s between clicking things) while we fix the error
