### ISSUE TITLE
A Way To Buy Food, Quests, etc. With Gold

### ISSUE THREAD

**Issue by BinJLG** [HabitRPG/habitica#2847]
I've only been playing HabitRPG for little over a month, and one of the first things I noticed was how there's no real way for free players to gain access to the items in the market. Not only does this give subscribing players a rather large advantage over their free counter-parts, but it also becomes inconvenient and frustrating when you gain the ability to do quests and are never dropped a scroll. Many people will probably just tell me to go join a party if I want to do quests, but I like and prefer the independence of solo gaming. That being said, I can't experience HabitRPG fully unless I start doing quests, and in order to get any scrolls at this point, I need gems. Seeing as how I am a broke college student, however, that's not going to happen any time soon. Therefore, I propose a way to buy goods in the Market with gold in a way that won't be too easy.

I suggest a simple running rate in the market between gems and gold. What I had in mind was something along the lines of 1 Gem = 100 Gold. This allows the simpler items such as food to be easily, but not TOO easily, obtainable, while also making the more valuable items (rarer hatching potions, quest scrolls, special items, etc.) a goal one can work towards while, again, still being obtainable. This also would not devalue the gems much, if at all, since it take a little while to save up that much gold.

Thoughts/questions/feedback?

**Comment by lefnire** [comment]
Alas, we're not going to be supporting this. It's a topic that's been discussed ad nauseam in [Trello](https://trello.com/b/EpoYEYod/habitrpg) (do a search in the search box, I don't have the cards handy). Nothing that affects stats in the game can't be earned through standard gameplay, gems are just a shortcut.

**Comment by deilann** [comment]
Also, fear not -- I'm working on gold purchasable quests.
