### ISSUE TITLE
quest wont complete

### ISSUE THREAD

**Issue by FrozenMime** [HabitRPG/habitica#2848]
I am in a one-person party and the christmas quest with the polarbear mount wont complete even though the boss's health is at 0.

**Comment by deilann** [comment]
How many days has it been at 0?

**Comment by FrozenMime** [comment]
2

On Fri, Feb 14, 2014 at 7:35 PM, deilann notifications@github.com wrote:

> How many days has it been at 0?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2848#issuecomment-35143881
> .

## 

Kind regards,

Paul Bendor
(214) 862-8774

**Comment by deilann** [comment]
And you have been dealing damage both of those days?

**Comment by FrozenMime** [comment]
Nvm, the quest completed. Apparently I needed to refresh the party page
specifically for the quest to complete.

On Mon, Feb 17, 2014 at 7:22 AM, deilann notifications@github.com wrote:

> And you have been dealing damage both of those days?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2848#issuecomment-35256096
> .

## 

Kind regards,

Paul Bendor
(214) 862-8774

**Comment by deilann** [comment]
I highly suggest whenever something seems "stuck" to refresh that page. It may have updated on the server, but the old info is still in your cache. Glad to hear it's resolved!
