### ISSUE TITLE
dailies dealing out huge amounts of damage

### ISSUE THREAD

**Issue by ld89** [HabitRPG/habitica#2849]
I only leave 1-3 dailies undone each day, but I am taking upwards of 20 damage daily and I keep dying. Are dailies supposed to deal out such massive damage?

**Comment by deilann** [comment]
Are they the same ones?

Every time you leave a daily unchecked, it gets redder-- the redder a
daily, the more damage it will deal. If you start doing the dailies, you
will get more points and they will slowly change back to yellow, then
green, then blue.

**Comment by ld89** [comment]
Yeah, that's it. Thanks so much! Guess I need to start practicing my Spanish...

**Comment by deilann** [comment]
Get to it! :P
