### ISSUE TITLE
Can't change the position of some To-Do items

### ISSUE THREAD

**Issue by notapooka** [HabitRPG/habitica#2855]
I am unable to change the list position of some items on my To-Dos list. It will appear as though the item has changed position, but the next time I load the page or open HabitRPG on another device, my To-Dos list shows that a different item than the one I intended to move has been moved. Most items, I can rearrange just fine, but some items always stay in the same position, no matter how many times I try to move them or on how many different systems.

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg/issues/2606
