### ISSUE TITLE
new tag can't be used until sync/reload

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#2856]
When I create a new tag, if I immediately assign it to a task, the tag itself and the "tag" that the task has have different IDs (i.e., the new tag is not actually assigned to the task).

If I create a new tag, then do a browser-reload or use Habit's new sync button, and THEN assign the tag to a task, everything works as expected (the tag itself and the tag that the task has have the same IDs).

I've replicated this issue in two accounts: 3e595299-3d8a-4a10-bfe0-88f555e4aa0c and     d904bd62-da08-416b-a816-ba797c9ee265

None of the new tags I tested with contained a colon, so https://github.com/HabitRPG/habitrpg/issues/2170 probably is not related.

**Comment by deilann** [comment]
Oh, awesome. Thanks for figuring out exactly what is up. That explains a
lot, and knowing that will be very useful for support.
