### ISSUE TITLE
Lost Gryphon

### ISSUE THREAD

**Issue by Sleepterrors** [HabitRPG/habitica#2858]
Cotton candy blue gryphon mount dissapeared from mount list, I was still riding it, but as i switched to other pet, I'm now unable to mount it again. The Gryphon mount was obtained with use of a saddle.  
Anyone know how to get it back?

**Comment by deilann** [comment]
@lefnire related to #2814 ? you had to run a script for that, iirc

**Comment by lefnire** [comment]
@Sleepterrors what's your UUID?
