### ISSUE TITLE
Toolbar gives access to inventory at level 1, reborn

### ISSUE THREAD

**Issue by ChristopheCalvez** [HabitRPG/habitica#2859]
The new toolbar gives me access to the inventory despite I'm level 1 (reborn), whereas I can't navigate to the Inventory tab (https://habitrpg.com/#/options/inventory) from the other tabs.
Does it happen to all level 1 ?
Should it be disabled from the toolbar, or a control added on the landing pages ?

**Comment by deilann** [comment]
I'll test this in a bit. Thanks. :)

**Comment by Alys** [comment]
Level 1 players now have access to equipment immediately. Closing.
