### ISSUE TITLE
Coin calculation when checking/unchecking daily tasks

### ISSUE THREAD

**Issue by mbnewsom** [HabitRPG/habitica#286]
If repeatedly checking and unchecking daily tasks, my coin count changes seemingly randomly.  I can artificially give myself coin this way.

**Comment by Pandoro** [comment]
I think this has been reported once before. But you can of course cheat anyways ;) So this will be fixed at some point. Probably by the  <a href="https://trello.com/card/undo-button/50e5d3684fe3a7266b0036d6/20 ">undo button</a>. This should make sure the same amount is subtracted as it was added. Until then however, you'll have to decide for yourself if you use it or not ;) And if it happens by accident, it will probably not make such a big difference :)

If this answers your question, we can maybe close this thread.

**Comment by horusofoz** [comment]
Hey @mbnewsom and welcome to the community.

Your issue was originally reported under [GitHub 47](https://github.com/lefnire/habitrpg/issues/47). 

Please refer to that ticket for updates and further discussion.
