### ISSUE TITLE
Make "API" page less techy

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2860]
"API", "User ID", and "API Token" are technical, view-into-the-guts type terms. Your average end-user will only have a vague notion of what "API" means, and thus won't know what to expect when clicking that item on the Settings menu. Moreover, once they get there, there's not a lot of guidance on what these different things are for: it says they're used for third-party applications, leaving out important information like the fact that the User ID is what you need for forming parties with other players.

Some thoughts, from half-formed ideas to full suggestions:
- The API page itself needs another name. I'm not quite sure what to call it, but not that.
- Call "User ID" the "Friend Code" or something. People are most frequently going to use it for inviting people to parties and Guilds--make it obvious that's what it's for. (You could keep "User ID" as a parenthetical for tech types or folks who've been around long enough to internalize the term.)
- Call "API Token" a "Security Code" and warn users to guard it like they would a password. (Again, we can keep the term "API Token" around, just not use it as the main word for the thing.)
- Flesh out the "third party applications" bit. We at least need to mention that it's used within Habit as well as outside.

**Comment by quin-jay** [comment]
I think I can make these changes, once I actually do the local setup for Habit. My ideas for terminology:
- API page > "**Account Numbers**" (con: may sound too scary?)
- User ID > "**Profile Number**" (so it doesn't sound like you're giving away your whole account, but also sounds a little more universal than just social/party uses)
- API Token > "**Security Code**" (great idea -- then again I don't actually know what it is either...) or perhaps "**Account Number**" (which sounds less like the back of a credit card and more like an actual bank account, perhaps?)
- I'll do some research on usage of these numbers to make sure I include a description that's as all-encompassing-yet-just-vague-enough as possible

**Comment by thepeopleseason** [comment]
For brevity's sake, API could just be "**Account**"

APIs generally call their tokens either tokens or keys, so "**Security Key**" would convey the right amount of keep-it-private-gravitas while also being appropriate enough for the technically-minded to understand its use. 

[The Wiki Page on API](http://habitrpg.wikia.com/wiki/API) has been fleshed out enough that we could likely link to it to further explain the use of IDs and Keys.

Also of note: habitrpg-mobile should be updated to account for the new field names should we implement this change.

**Comment by quin-jay** [comment]
Great point, thanks for that reminder

**Comment by snicker** [comment]
I disagree... these are pretty standard terms for anyone who wants to use an API. I think by doing this, you're going to make it more difficult for people who are actually looking for the API.

In my humble opinion, if you want to "hide the technical cruft" so-to-speak, the Right Way would be to have "Invite To Party" buttons on profiles, and an "Add Application" type interface for obtaining keys to add to third-party APIs. The API tab stays as is for the people who know what they're looking for, and we make easier alternatives for those who don't

**Comment by quin-jay** [comment]
What do you suggest for things like GitHub tickets where users need to find and post their UUIDs?

**Comment by deilann** [comment]
Generally we explain to them where to find it.

**Comment by quin-jay** [comment]
@deilann, to clarify, I was asking for a little more elaboration about @snicker's suggestion. It sounded like maybe the current API page would still exist but it would be easier to invite people to your party. I think that's a pretty good idea, but there are other cases where one would need their UUID, and I think we might as well rework things so that we no longer _need_ to be so explicit for every individual

**Comment by deilann** [comment]
I think "Unique User Code" works well

**Comment by quin-jay** [comment]
:+1: 

(I really wish there was a +1 button for GH comments)

**Comment by lefnire** [comment]
Chiming in here. I'm all for popovers, small/grey help text under existing text, etc. However, we're using some very standard terms throughout. One often finds an "API" tab in apps that have an API. It's literally an API Token, and that's a very standard term in web apps. User ID may be a bit funky, since people associate that with their login name - however, since it is the user account identifier (their login name is not), it's accurate.

So ticket may make things more readable for people who've never heard these terms before, but it's going to confuse people who've used any number of web apps before, and will also disrupt all the documentation out there (wikia & otherwise) pointing to these specific terms.

I'm actually quite _not_ in favor of this ticket. I'm open to debate, but my vote is a definite "no"

**Comment by thepeopleseason** [comment]
@lefnire: Based on @SabreCat's initial description, the primary objection to the terminology is the importance of the UUID and its location on such an esoteric page. I think solving this problem may be as simple as duplicating the UUID on a page less-technical users might regularly go to, say, perhaps the Profile options page. 

For some of @SabreCat's other issues, I could also see some crosslinking between the API options page and the wikia documentation, as well.

**Comment by quin-jay** [comment]
I think the UUID issue could be really easily fixed if the number was written on the Profile options page and/or on a view of your own profile as others see it, which currently you can only see by clicking your own name in chat. (Some of the UI changes suggested in [2835](https://github.com/HabitRPG/habitrpg/issues/2835) might be a way to implement that concept.) The most important thing is putting it in a place easily found by newbies, and making sure it's clear what that long string of characters _is_ by labeling it explicitly as **Unique user identifier number (UUID)**. This label should probably be replicated everywhere the UUID is found (except perhaps the API page, for tech-savvy users who already know what it is).

**Comment by lefnire** [comment]
I'm totally on board with these suggestions. Things should be much more
obvious and accessibly located. Cool beans, just wanna keep the standard
Web app terms (api, api token, etc) where we can

**Comment by quin-jay** [comment]
As someone who has no idea about API at all, I didn't quite realize that those were actually standardized terms. It makes total sense for those to stay put now. 

Unless someone else ~~who actually knows what they're doing~~ wants to take this, I'll see if I can work on it this weekend!

**Comment by SabreCat** [comment]
I think @lefnire's objections were already covered in the original issue ticket, but maybe I didn't phrase them clearly enough. To clarify, under my original suggestion you'd have...

**Friend Code** (UUID)
asoeud-3824328-gobbledygook

**Security Code** (API Token)
asdf-jkl-yomama-382423894

And though I didn't say it explicitly, the new name for the API page could do the same thing, be "Access Codes (API)" or whatever.

FWIW, this is the first Web app I've ever used that has exposed those kinds of techy things. Evernote, Facebook, Twitter, zendone, Workflowy, Toodledo, anything by Google... I've never had to manipulate tokens or get the numeric string undergirding my email address or user name. I'm sure I would if I were a developer looking to interface with these things, but not as an end user!

**Comment by deilann** [comment]
I'd stray away from using "Friend Code" because it would sound weird if we
asked for their Friend Code for tickets.

Security code, yes.
