### ISSUE TITLE
Item Purchased on iPhone App not appearing

### ISSUE THREAD

**Issue by KellenM** [HabitRPG/habitica#2861]
I purchased the Candy Cane Hat on my iPhone at some point, and I don't use the app very often anyway, so it didn't occur to me that this item actually never showed up in my inventory when I used HabitRPG on my PC. But then I used my phone again and I saw the hat on my character -- meaning it wasn't just in my inventory, but equipped, according to my phone. But then I checked my PC and it wasn't there at all. Maybe this is a bug in the phone app, or maybe the item itself is bugged, or maybe something else, I'm a bit stumped. I snagged a screenshot of my character with the hat before hitting Sync on the phone, which wiped out the item -- although it did apparently go back to the list of items I can purchase (I think this might be part of the problem, since I'm not sure that item should still be available for purchase).

**Comment by deilann** [comment]
I think this is https://github.com/HabitRPG/habitrpg/issues/2718, not related to mobile. Let's go there.

It's still for sale because while it didn't grant you the item, the system recognizes that it was purchased, which means it is always for sale for you when you do not own it.

**Comment by KellenM** [comment]
So the major question here is now whether there is any way for me to ever recover this item. I purchased it, but it's not longer available by any means. After purchasing it on mobile, it was not available in my inventory (or for purchase) on PC. Updates to the mobile app have removed it from my inventory, and it did not make its way back to the store.

**Comment by deilann** [comment]
What's your UUID? I can now grant you the item.

**Comment by KellenM** [comment]
d718e5a4-6873-4e94-8d66-768d666a273e

Thanks!

**Comment by deilann** [comment]
Refresh your inventory, and tell me if it's there! :)

**Comment by KellenM** [comment]
All set!  : )

Thanks again!

**Comment by deilann** [comment]
Yay!
