### ISSUE TITLE
Valentines Cost more than 10 GP

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2862]
They are currently costing me 10.13 GP

**Comment by quin-jay** [comment]
This could probably be closed as well.

**Comment by deilann** [comment]
It might be indicative of a larger problem.

**Comment by quin-jay** [comment]
Oh, good point. Actually I wonder if this is related-- for a while my rewards that cost less than 1 gold were undercharging me (what should've cost 20 silver only charged me 19, ditto a 40 charging 39). I didn't get to fiddle with it so I don't know whether it happened under certain conditions, and I haven't noticed it in the last day or so. 

Maybe it's resolved itself and maybe it has nothing to do with the valentine thing, but I just wanted to throw it out there just in case

**Comment by lefnire** [comment]
Could be reward purchasing takes a stat (PER, INT, etc) into count

**Comment by deilann** [comment]
That's what I'm thinking Tyler, but I feel like it wasn't affecting my
custom awards. When I purchase another one, I'll update with more info.

**Comment by deilann** [comment]
Just bought a health potion && a 100 GP custom reward to test this out; both cost the correct amounts.

**Comment by LyndisSacae** [comment]
I bought a gem recently that cost 20G 45S rather than the usual 20G, but that's the only time it's happened to me.

**Comment by SabreCat** [comment]
Could it be that some other sync in between clicks is causing the discrepancy? Like, there was actually a 45s adjustment that happened behind the scenes, then it added in to the Gem purchase notification because that was the next thing to happen?

**Comment by deilann** [comment]
Don't think so, Sabe. When I was doing this with Valentines, every
Valentine I bought was costing this much, not just the first one or a
couple.

**Comment by crookedneighbor** [comment]
I haven't seen this error, and since it's over a year old, I'm closing it.
