### ISSUE TITLE
Gold Sinks Part 1: Random Encounters [$85]

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2863]
[Trello Card](https://trello.com/c/0lxZ9Rlc/413-random-encounters)

These quests would be gold purchasable and provide XP (and possibly food drops) but no GP, as they are a gold sink. This takes quests out from behind the pay wall, making Habit's best accountability tool freely available.

Disclaimer: I am shamelessly posting this issue for bounties. I cannot prioritize this as much as I want to right now because it does not involve monies.
##

**Comment by Alys** [comment]
I'm closing this because the first quest line of gold-purchasable quests was created by @SabreCat in https://github.com/HabitRPG/habitrpg/commit/b9f79552  - Sabe, note the bounty here.

**Comment by SabreCat** [comment]
I don't feel comfortable claiming the bounty on this, given that "random encounters" was meant to be part of the project and hasn't yet been implemented. A single chain of Gold-purchasable quests doesn't make for a sustainable Gold sink.

**Comment by Alys** [comment]
No worries, but the exact specifications listed in this issue have been met so it might be worth updating the description.

**Comment by paglias** [comment]
What about this? If no one is going to claim the bounty @deilann should probably claim it back

**Comment by lemoness** [comment]
We need to do a lot more design work before we are ready for this, so I think it's too early for a GH ticket. The bounties can be reclaimed by the people who posted them!
