### ISSUE TITLE
Guild Error

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#2866]
I get a message upon trying to open up a private guild that says I do not have permission I access that guild and to reload. Does that mean I was kicked out or is that a glitch?

**Comment by deilann** [comment]
I imagine if the guild still exists in your tabs, then you are not kicked out, but don't quote me on it. Wait a few minutes, then reload the guilds page. If the guild tab still exists, wait for the page to completely load (blue bar goes away) then click on the guild.

Lemme know what happens. :3

**Comment by paglias** [comment]
I am from phone so I can't search it but some time ago I opened a issue for
this problem. It is caused by the fact that only 15 members for guild are
fetched from the server so if you're not in the first 15 members it looks
like you're not in the guild.

**Comment by deilann** [comment]
Looking like you're not in the guild and not being able to access it are
two different beasts, though.

**Comment by paglias** [comment]
I see the guild tab but I can't open it, it returns a 401. I'm pretty sure
it's the same issue.
Il 17/feb/2014 14:20 "deilann" notifications@github.com ha scritto:

> Looking like you're not in the guild and not being able to access it are
> two different beasts, though.
> 
> On Mon, Feb 17, 2014 at 5:19 AM, Matteo Pagliazzi

**Comment by Mihakuu** [comment]
Same. I clicked on the notification on the tool bar and I get the message of not having access to that guild and to refresh and check chrome console. It opens the guild but doesn't load anything like messages or members

**Comment by deilann** [comment]
Yeah, whenever a guild doesn't fully load, you get the template without the
actual guild stuff.

**Comment by Mihakuu** [comment]
Well it's as loaded as it wants to go. Tried on different devices. So it's a just wait till the server decides it's okay to go in thing? All my private guilds are like this.

**Comment by deilann** [comment]
Do all of your private guilds have > 15 members?

**Comment by Mihakuu** [comment]
One has 3, that one loaded when I refreshed a couple of times though. The others are larger but I don't know the number off top of my head, I've never needed to know before. Probably over 15

**Comment by deilann** [comment]
Okay, if one of them has less than 15, it's not the same bug. H'm.

**Comment by paglias** [comment]
The one not loading with less than 15 members then loaded, right? So it's probably a one time error

**Comment by deilann** [comment]
It took several refreshes, according to Bailey.

**Comment by Mihakuu** [comment]
I can't get into any private guides currently at all regardless of size

**Comment by deilann** [comment]
Got an invite; can't get in.

**Comment by lefnire** [comment]
I fixed the 15-limit thing (separate ticket), is this one fixed too as a result?

**Comment by deilann** [comment]
I can get into the private guild that was blocked.

**Comment by Mihakuu** [comment]
Same for me.
