### ISSUE TITLE
Add reCaptcha (or Captcha) (or anything similar) to Registration

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2867]
This issue is critical, but does NOT qualify for the Hammer.
#2865 makes a good point -- usernames can be farmed via the registration process as well as sign-in. By adding reCaptcha to registration, we will be able to better secure the system.

I also suggest adding a bot-test to "Email New Password" || change so that errors do not occur if no user is registered w/ address || simply output "If an account is registered to tyler@gmail.com (never will let myself forget that), you should receive your new password shortly."

**Comment by deilann** [comment]
@lefnire I'm tagging this critical because it's a big security flaw. I have edited to state that it does not, however, qualify for the hammer.

**Comment by 3onyc** [comment]
What would be the preferred way to get around the registration issue.

Throttling requests to the POST endpoint for registration would slow down but not prevent any acquisition of valid usernames, however it wouldn't impact UX either.

On the other hand reCAPTCHA would solve the acquisition issue entirely, but negatively impact UX.

Perhaps a combination of the 2, say after 5 requests to the registration endpoint in a minute you need to start entering a captcha?

**Comment by crookedneighbor** [comment]
@deilann What do you think of this: http://venturebeat.com/2014/12/03/google-boils-down-the-captcha-to-a-simple-checkbox-to-prove-youre-not-a-bot/

**Comment by deilann** [comment]
I feel like that article gives absolutely no real information.

**Comment by crookedneighbor** [comment]
Oh, sorry. I had looked at a few different articles in the same day a month or two ago on this topic. I grabbed the wrong link. Let me see if I can find the right one.

**Comment by deilann** [comment]
haha no worries

**Comment by crookedneighbor** [comment]
Here's the actual info from Google: http://googleonlinesecurity.blogspot.com/2014/12/are-you-robot-introducing-no-captcha.html

**Comment by deilann** [comment]
This I like!

**Comment by TheHollidayInn** [comment]
I can work on this, but an Admin probably needs to register: https://www.google.com/recaptcha/intro/index.html . Or, I can. Just let me know.

**Comment by 3onyc** [comment]
@TheHollidayInn You can add a variable in config.json for the Recaptcha credentials, that way you can use your own in dev, and HabitRPG theirs in prod.

**Comment by TheHollidayInn** [comment]
@3onyc Make sense! Thanks.

**Comment by crookedneighbor** [comment]
We were counseled against using a captcha of any kind, so I'm going to close this for now. 

@deilann If you're interested in the details, @veeeeeee is the one to talk to.
