### ISSUE TITLE
Some suggestions & bugs

### ISSUE THREAD

**Issue by rikikiangel** [HabitRPG/habitica#287]
I was disconnected yesterday and didn't notice and I added some dailies. After I refresh the page, there are blank dailies that I cannot delete, refreshing the page again doesn't help. I have to reset my account(I was just starting using and playing around so reseting is still ok but I have to be careful in the future).
The reconnect link is also not usable, I have to refresh the page to reconnect.
I'm using Opera also which may be the problem?

Subcategories would be nice. Like I have a todo project that need to be broken down to subtasks.

Also, it would be nice to have a dream like category. Things that I've thought of but no plans to do yet or I'm not going to do in a short while like going vacation to a place. This category is different from todo because it is just some thoughts that I want to gather but not planning to use in habitrpg yet. Like an inactive todo.

Separators would be nice also. So it looks more pleasing when I have a lot of habits or dailies.

**Comment by wc8** [comment]
Something similar happened to me on Wednesday night. @lefnire can usually help, sometimes he'll need your UUID,  username, and/or email. I was restored by the following morning. (You can email the UUID to him directly.) 

For a semi-backup on my end I select all (CMD+a / CTRL+a) and copy the page to text/rtf file. I made doing that a daily. That way, if something happens, at the least, I can re-enter my items. 

As far as your suggestions:
See the #243 for an idea for handling "dream" tasks. 
What do you have in mind for separators?
On Trello, there is a feature request for [checklists](https://trello.com/c/PJ1iJ413), a single level of subtasks, would that address what you mean by subcategories/subtasks?

**Comment by rikikiangel** [comment]
Thanks for the help.
For separators, I'm thinking of a simple horizontal separator that I can drag and drop to position. I want to separate some of the dailies, habits. They are not really related but they have something in common sometimes(not sure how to say).

Yes, something like checklists. Like I'm doing my school 3D project, I need to do a lot of things to finish it: eg. write proposal, sketch, do diagram, write report, model A item(house), model B item(dog), model C item(flowers) etc(there can be a lot of models). If don't want a lot of nesting, maybe model A-C can be separated by separators(separators in subcategories).

**Comment by rikikiangel** [comment]
I have another idea that the social people may like. I tried to search around here or trello if there is similar idea mentioned but I did not find it. 

EDIT: I have put it in a card in trello that I think can apply this.

U share ur public page with friends(private task are hidden from public page). Ur friends can add rewards for completing a specific task or add rewards that can be bought for certain coins. After the user complete/bought the reward, an email will be sent to the friend notifying him/her so he/she can fulfill the reward.

**Comment by Pandoro** [comment]
I like this idea indeed, however the question is how to determine a good
value for the reward. Other people might now know what your average GP
income a day is and thus might make the rewards too cheap or too expensive
for you to make.

**Comment by rikikiangel** [comment]
The reward per task don't have this problem, just the coins one. Most people might be lazy to think of rewards so give some pre-made selections to choose and some introduction that includes an average coins that User has earned last week at the public page like this:
You can give User motivation by giving him personal rewards! Choose from pre-made rewards or think of a new one. User earns an average 20.5 coins per day last week. You can customize the pre-made value if you think it is too cheap or expensive.
5 coins - a hug
5 coins - message shoulders
5 coins - bring me a drink
10 coins - shopping together

 User can delete/add more pre-made rewards to the list.

**Comment by Pandoro** [comment]
I think the pre-made rewards aren't really necessary, However I really like the idea of having an average GP earn/day for each user. This way anyone can easily calculate how long she or he wants the other player to work for the reward. 

Also sorry about not seeing the reward per task suggestion, I think this is a great idea! 

I updated the [trello card](https://trello.com/card/reward-task-habit-sharing/50e5d3684fe3a7266b0036d6/76)
