### ISSUE TITLE
Can't get Chat function to work on iPad after donation

### ISSUE THREAD

**Issue by ACinJC** [HabitRPG/habitica#2871]
Hi, 
I made a $5 donation on Habitrpg.com for gems, but really thinking that would make the chat function on the iPad app activate.
It doesn't appear to be working. What did I do wrong? 

Thanks!

**Comment by deilann** [comment]
As discussed in the Tavern, I believe it needs to be a subscription now. Is that correct, @lefnire?

I am tagging this with the sub tag so you can visit it in your sweep.

**Comment by ACinJC** [comment]
Reposting over here what I accidentally put in the Tavern. 
I understand now that this is supposed to be for subscription accounts. 
I think the language in the app is misleading on this point. Ryan 2.0.7 agreed. 

So, reposting now: 
Well, here's my thought on what I would like, in order of preference:
1) I really wanted the chat function. Is there any way, in consideration of my confusion, you can jury rig it to work for me anyway? 
2) Unfortunately, I don't have the money for the monthly subscription. If option 1 isn't possible, could I get at least a partial refund? 
Sorry I got confused.

**Comment by deilann** [comment]
Can we also get your UUID?

**Comment by deilann** [comment]
Or wait, I can grab it myself, from the Tavern. It's `403d2928-63f2-4b0d-8b63-aca88a79686d`

**Comment by ACinJC** [comment]
Following up...
I would still really like the chat function, if there's any way that's possible.
If it isn't, however, don't worry about a refund. I'm discovering enough that I can do with the gems (thinking of starting my own guild, for example) that I'll get $5 worth of value from it all.
Any in-game swag or somesuch that you can toss my way that might make up for it would still be appreciated.
Thanks.

**Comment by lefnire** [comment]
@ACinJC [email me](mailto:tyler@habitrpg.com), I'll get you sorted. I'm pushing a mobile release now with updated wording (and a chat box bug fix)
