### ISSUE TITLE
Username box on avatar misaligned

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2872]
When you click on someone's name to view their stats, the username hover thingy on their avatar shows up a good deal to the right of it.

![screen shot 2014-02-17 at 12 40 30 pm](https://f.cloud.github.com/assets/6208739/2187749/a0c245b2-97fa-11e3-9fdd-73d3cbf4ac59.png)

**Comment by deilann** [comment]
Confirmed!

**Comment by quin-jay** [comment]
Just to help isolate the problem because I know some web style codes vary browser to browser: I am _not_ seeing this issue in the latest version of Chrome on Mavericks. I'll try a couple other places if I get the chance, though

**Comment by paglias** [comment]
It's the `.modal-body figure` padding set to 15px, fixed
