### ISSUE TITLE
Purchased 20 gems but still haven't received them.

### ISSUE THREAD

**Issue by RainbowSocks** [HabitRPG/habitica#2876]
Hi,

I subscribed/purchased 20 gems on 7th February, but unfortunately I still haven't received them. The charge shows up on my Paypal, so the payment definitely went through. I'd be really grateful if you could fix this!

My user ID is:
3df35b85-e381-40bc-9d51-47c5ebde0d5e

Many thanks in advance! :)

**Comment by deilann** [comment]
Sorry RainbowSocks -- if you see #2384 PayPal has issues with Habit. In the future, if you can use a card, it will go through much easier. I've added the gems to your account. If you could post your the transaction ID for posterity, though, it would be appreciated.

**Comment by RainbowSocks** [comment]
The gems just showed up, thank you so much! :)

(Also meant to say in my original post that I didn't actually subscribe- I thought buying the gems also meant a subscription, oops.)

Transaction ID from Paypal:
Unique Transaction ID9HF37905V5093394C

**Comment by deilann** [comment]
Thanks!

Do you have any ideas on how things could have been worded so it clarifies
that purchasing gems is different than buying a subscription? In other
words, what confused you?

**Comment by RainbowSocks** [comment]
It's actually my fault, I didn't read the wording properly as I was in a bit of a hurry to go out and I wanted to buy gems there and then (I knew I'd forget to do it later- next time I'll put it on my To Do-s! :P). I assumed it was similar to some other websites (DeviantArt, for example) and that I'd get a month's subscription for a one-off $5 payment, as opposed to a longer one if I made monthly payments. I really only wanted the gems for the time being, though, so it wasn't a problem! :)

**Comment by deilann** [comment]
Thank you so much for taking the time to give me feedback! :)
