### ISSUE TITLE
Windows Phone 8, interface bugs

### ISSUE THREAD

**Issue by veilrap** [HabitRPG/habitica#2878]
It's nearly impossible to see more than the first two elements in a particular category (i.e. Habits, Dailies, etc.)

Drag and drop also does not work via the web interface.

**Comment by deilann** [comment]
Curious: what phone browser are you using? If it's IE, that might be the problem right there.

**Comment by veilrap** [comment]
On windows phone, like iOS, there's not much choice in browsers.

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2879

lets merge these
