### ISSUE TITLE
Drag/Drop issue

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#288]
I have a somewhat long todo list that doesn't fit on the page.  When I drag a todo from the bottom to the top I have to drag it up above the static header.  It isn't a big deal, but it isn't how you would expect it to behave.  Forgive my lack of html XP, but could we make it act more like a frame would act so that when we drag it up it starts scrolling as soon as the cursor gets to the header?  Not sure, but I think that should fix the ad problem in #275 as well?

Edit: I think I mean to say, we can just use a table with 2 cells.  Again, I don't do much html, so there might be a better way to do this.

**Comment by Pandoro** [comment]
I have experienced the same thing myself. As far as I know @lefnire is away for the weekend, so let's see what he thinks about this.

**Comment by horusofoz** [comment]
@lefnire Triage difficulty. Assign.

**Comment by horusofoz** [comment]
@Sabin144 Is this still and issue for you?

**Comment by dbueller** [comment]
Less of an issue since the graph data of habits were reset, but it would
still be a nice feature to have.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Anyway sorting has still to be ported so i't currently not working, it will probably come back in the near future
