### ISSUE TITLE
Mage's Gear Bonuses Underpowered Compared to Other Classes

### ISSUE THREAD

**Issue by MrMakara** [HabitRPG/habitica#2880]
The Mage's Ultimate Gear only gives 18 Perception points and 30 Intelligence points, while all other Ultimate Gears give 20 points to the secondary skill and 30 to primary. Not sure if this was overlooked or simply made to be this way but it seemed odd.

Royal Magus Robe: 12 INT
Royal Magus Hat: 9 PER
Golden Staff: 18 INT + 9 PER
![ugm1](https://f.cloud.github.com/assets/6519619/2191222/b10dfc2c-9840-11e3-8a7a-41c927f1049a.PNG)
![ugm2](https://f.cloud.github.com/assets/6519619/2191224/b483e31c-9840-11e3-97cb-c188c075702d.PNG)
![ugm3](https://f.cloud.github.com/assets/6519619/2191228/b6258c66-9840-11e3-8368-a47cfc4e8e6b.PNG)

**Comment by SabreCat** [comment]
Looks like an oversight. Should be easy enough to add +1 PER to each of the hat and staff.
