### ISSUE TITLE
Class-Specific Ultimate Gear Badges

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#2881]
Thanks to our awesome @zoebeagle, we now have three new badges so that Rogue, Mage, Warrior, and Healer can all have separate Ultimate Gear achievements! Hooray!

The badges are attached to this card. The contributor level has been given.

https://trello.com/c/xfXldYs1/11-badges

**Comment by SabreCat** [comment]
Got some ideas how to do this. I'd like to give out an Ultimate Gear badge for buying the full set of Crystal or Ebon gear, too.

Assigning myself for now, though if somebody else takes a shine, they're welcome to it.

**Comment by lemoness** [comment]
Awesome!!
