### ISSUE TITLE
Party page not loading after syncing chat

### ISSUE THREAD

**Issue by Irrlich** [HabitRPG/habitica#2883]
A new issue popped up recently.

When I try syncing the party chat the page says that I am not in a party (even though I can see the members in the bar on top. The following error message is displayed.

Please reload, "Error You don't have access to this group" (see Chrome console for more details).

If I reload the entire page the error is gone and things go back to normal. 

![habitrpg](https://f.cloud.github.com/assets/6713843/2193472/bdbe7aa4-987d-11e3-8ece-a199651096a6.png)

**Comment by deilann** [comment]
This is related to #2866 , I'm pretty sure.

**Comment by lefnire** [comment]
how about now, fixed?

**Comment by Irrlich** [comment]
It is!

Thank you very much!
