### ISSUE TITLE
To-Dos and Dailies aren't detracting the right amount after being Unchecked

### ISSUE THREAD

**Issue by MrMakara** [HabitRPG/habitica#2884]
Whenever I accidentally check a Daily or To-Do and then uncheck them, I am not being detracted the right amount of Gold and XP that I originally got from the To-Do/Daily. This is usually giving me a net amount of Gold and is making a Gold and XP farm. Also got a critical hit for unchecking To-Do.

On this note, when unchecking To-Do or Daily that caused me to level up, go into negative XP instead of levelling down.

**Comment by deilann** [comment]
PR for criticals, not yet merged: https://github.com/HabitRPG/habitrpg/issues/2356

See ticket: https://github.com/HabitRPG/habitrpg/issues/964

The answer here is not to cheat. There's no point in farming, when you can set character values. It's not that big of a deal, and especially won't be when Undo is implemented. But if you could follow those tickets, it would be appreciated.
