### ISSUE TITLE
near-constant invites to particular guild

### ISSUE THREAD

**Issue by inksplotched** [HabitRPG/habitica#2886]
for ages i've been getting invites to the guild "the scholars". any time i reject the invite, a new one shows up immediately. i ignored it for a while but now it's present in my notifications bar (which i like!) and i'd like it to go away for good. i don't know any way of blocking the invite or getting it to stop.

user id 46c6a593-38ef-4996-923b-fa925929f1fa

**Comment by inksplotched** [comment]
er! soon after writing this i accepted the invite and then left the guild - that seems to have worked for now, but idk you still might want to look into this in case it happens to someone else?

**Comment by deilann** [comment]
Yeah, keep this ticket open. I think that solution will work, but the
decline isn't permanently getting rid of the invite. So to get rid of it,
you have to accept it.

**Comment by LB7979** [comment]
I have the same glitch with invites, clicking the Reject button doesn't work... Joining then leaving is the only way to dismiss an invite.
