### ISSUE TITLE
Negative Gems

### ISSUE THREAD

**Issue by Aaern-the-Blunt** [HabitRPG/habitica#2889]
I had one gem. Everytime I create a new challenge with a guild, my gems go down one by one, and now I have -1 Gems (even though the gems should have been taken from the guild, which they were).

**Comment by deilann** [comment]
I assume you lost 4 gems this way, as that's how many go in the guild bank? What's your UUID?

**Comment by TheHollidayInn** [comment]
I tried to replicate this error, but I get an error message when having 0 gems.
![screen shot 2015-03-14 at 5 39 31 pm](https://cloud.githubusercontent.com/assets/1253400/6653898/2c082796-ca71-11e4-8982-e9a1f489e60d.png)

**Comment by Alys** [comment]
Thanks @TheHollidayInn 

@Aaern-the-Blunt This was a while ago now, but if you still want the gems back, comment here with your UUID (Settings -> API -> User ID). I'm closing this since it's so old, but if you comment we'll see your reply and keep on helping you.
