### ISSUE TITLE
Daily Items not changing colors

### ISSUE THREAD

**Issue by abednego** [HabitRPG/habitica#289]
Not sure if the lack of activity on my daily items is counting against me, but I have several that are set for every work day, but they remain gray like I've completed them.  Perhaps I misunderstand how they work.

**Comment by wc8** [comment]
Today (Saturday), a task set for M,T,W,T,F, but not S,S, (as pictured in #232) would appear grey. Today and tomorrow (Sunday) it will not count against you (no HP loss) if you do not complete the task, but you will be rewarded if you complete it. 

If your tasks set to be due on weekdays (M,T,W,T,F) remains grey, for example, **on Friday** even when the checkbox is unchecked, that behavior is not expected.

**Comment by abednego** [comment]
I'll re-review on Monday and report back.  Thanks wc8.

**Comment by horusofoz** [comment]
@abednego How did things go mate?

**Comment by Pandoro** [comment]
As there was no answer back, I will close this for now, feel free to post here again and we can revisit it if it has occurred again!
