### ISSUE TITLE
Cost Popup Displays Incorrect Amount

### ISSUE THREAD

**Issue by UsuallyPassive** [HabitRPG/habitica#2890]
Try buying a reward that costs 0.1gp. It will lower your gp by 0.1 (10sp), but on the popup on the top right, it'll say -9sp.
I expect this bug occurs because of a rounding error somewhere.

**Comment by negue** [comment]
@UsuallyPassive popup display issue still there?

**Comment by lemoness** [comment]
Just tested this and it worked fine for me, so I'm going to go ahead and close this. If anyone still has double, let me know and we'll reopen it.
