### ISSUE TITLE
Triggering a sync without refreshing page shows Bailey but wrong message

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2891]
This has happened a couple times: I'll be out all day, come home, check off some more Dailies on the Habit tab I've had open for 84 years, and voilà! Bailey appears. I click on her, and — the Valentine's Day message shows up. 
(Refreshing the page, going to Show Bailey, and then opening the message fixes it.) 
I don't know if this is actually an issue, or just a "E, refresh the stupid page every once in a while" thing, but thought I'd mention it.

**Comment by lefnire** [comment]
Yeah, you have to refresh. Her messages are backed into the HTML, they're not coming from the database. Therefore you need a refresh to pull down the new HTML.

**Comment by casicastiel** [comment]
That's what I suspected. Thanks for the confirmation :)

**Comment by lefnire** [comment]
Though it is on the agenda at some point in the (probably distant) future to make Bailey notifs a database thing, so that admins can update the content without requiring a PR. I'll keep this closed for now, and add to the company's internal Trello
