### ISSUE TITLE
Dividers still exist where Valentines used to be

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#2892]
It looks like, as they were meant to, the valentine card item disappeared from the shop, but there's still extra space where it had been.

![screen shot 2014-02-18 at 9 53 20 pm](https://f.cloud.github.com/assets/6640915/2203001/1c805be6-9911-11e3-8caf-2ac922d5e43f.png)

This will probably be a very easy fix, I'm just not quite sure where it lives in the code.

**Comment by lefnire** [comment]
Fix will go out with next deployment

**Comment by quin-jay** [comment]
Ooh, shiny :) thanks!
