### ISSUE TITLE
Damage to Gryphon is decreased every day

### ISSUE THREAD

**Issue by Goldenwyrm** [HabitRPG/habitica#2896]
I searched and I don't find anything about it. I think it isn't a right behavior. If it carries on, it will not let me finish the quest due to zero damage.

I always complete 4 of my 5 dailies.
None ToDo was done during this period.
I'm alone in the party.
The first (or second) day of the quest I used _Stealth_ that let me have a _perfect day_ even if the last daily was not done.

![damage_decreases](https://f.cloud.github.com/assets/5647357/2205026/3a5068c8-9948-11e3-9edc-3e8475922848.jpg)

User ID: 487745da-7a5d-49c5-a548-5a1bb257a4b4
Group ID: 66523149-910c-4084-9cb5-251e6114f1a5

**Comment by deilann** [comment]
This is expected behavior. Whenever you complete a task, the amount of damage it delivers is reduced (it gets bluer). So that way, you have incentive to do things that you don't normally or you've been putting off. There is a cap to task value; so your damage will never zero out.
