### ISSUE TITLE
Quest scroll lost after quitting solo party

### ISSUE THREAD

**Issue by GuanyangLuo** [HabitRPG/habitica#2899]
I was doing Trapper Santa solo, then I found that I needed help. I left my solo party (instead of aborting the quest), then the scroll was gone.
##

**Comment by deilann** [comment]
That party is now sadly in limbo, doing trapper santa with no quest members for eternity.

The only way to get a quest scroll back after a quest has started is to abort the quest.

**Comment by GuanyangLuo** [comment]
Is there any way to prevent quest-starters from losing scroll if they quit the party (solo or group)?

**Comment by deilann** [comment]
I think that wouldn't be a bad thing to code in.

**Comment by Alys** [comment]
Fixed. You now see a message, "You cannot leave your party when you have started a quest. Abort the quest first."
