### ISSUE TITLE
Progress sharing

### ISSUE THREAD

**Issue by morgante** [HabitRPG/habitica#29]
So, I've seen "groups" on the roadmap, but am most interested in seeing the ability to share your progress/daily completion with friends. What work has been done on this thus far? (I'd be happy to contribute code for it, just want to make sure I'm not repeating work you've already done.)

My particular use case is a friend who will be monitoring my progress, so the easiest thing would be for him to be able to log in and see **my** account dashboard.

**Comment by lefnire** [comment]
Haven't thought of that bit at all actually, have at it! See [getting involved](https://github.com/lefnire/habitrpg/wiki/Get-Involved)

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
The account dashboard sounds like another name for the [Profile Page](https://trello.com/c/9LNJafFM) request. 
If I'm misunderstanding, please let me know. 

> Account Dashboard/Profile Page, with user control over: 
> what to share:
> - achievements
> - tasks completed
> - rewards taken, 
> - etc. 
>   with whom to share the page: 
> - Facebook friends
> - My Party
> - General Public

**Comment by wc8** [comment]
Also, this specific request can be voted for [here](https://trello.com/c/5DddPN9J)
