### ISSUE TITLE
Polish translation error(s?)

### ISSUE THREAD

**Issue by heyheyitsrey** [HabitRPG/habitica#2900]
(1) http://cl.ly/image/191m1W243O3M
As in the picture: the "Subscribed" button should be "Subskrybowano". Extra y snuck in.

(2) http://cl.ly/image/3x0P2w2r0T2a
"User" should be translated to "Użytkownik". 

(3) http://cl.ly/image/1k1S3Z2S0E2S
Attributes aren't translated, but their descriptions are.
In addition, attribute abbreviations appear in their English variety (CON/INT/PER/STR) in that section, and in their Polish ones (KON/INT/PER/SIŁ) in the "character development" one where you allocate points.

(4) http://cl.ly/image/1R1m3S360F06
Quest titles are not translated

(5) http://cl.ly/image/2S0b2E1L2u0l
Armor names aren't translated

(6) http://cl.ly/image/1O24090y1R0F
Guild/party chat notifications aren't translated upon mouse-over

(7) Class names not translated

(8) "To-dos" should not have the hyphen to make sense in PL ("Do zrobienia" instead of "Do-zrobienia" - both are understandable, hyphenated would never be used).

That's just what I noticed after a quick browse-through after changing browser settings to PL. If wanted or needed, I can manually verify translation strings (it's part of my day job anyway) or ones tagged by the app/team you're using as uncertain.

Extra info:
Language - Polish
Browser - Chrome
Region settings - Poland

**Comment by paglias** [comment]
@rodzajowo some things are yet not avalaible to translations (quests, armor, pets...)

Class names in some cases are not avalaible also, I know it's a bit confusing, sorry.

"User", I forgot about it, I'll add it.

The notifications are to be translated.

For error in translations and strings that aren't yet translated you can go here https://www.transifex.com/projects/p/habitrpg/, it's the place where translations are managed, you can translate strings and comment on translated ones if you think there's an error.

Thanks!
