### ISSUE TITLE
Extra line in toolbar

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#2901]
Yesterday I had something like the following sequence of events. I didn't get a screenie. 

1) refresh browser
2) discover toolbar had extra line with only the "collapse toolbar" arrow in it.
3) click on one of my notification icons
4) arrive in that chat with a normal toolbar.
5) go back to the main screen and the toolbar was fine.

This morning, after refreshing the browser (to trigger cron) I have a 3 line toolbar - 2 lines appear to be legitimate (I have lots of notifications), but "collapse toolbar" has a line of its own again. 

I got a screenshot this time.

![screenshot from 2014-02-19 08 11 27](https://f.cloud.github.com/assets/4530463/2208518/d00f9e0a-9980-11e3-8c6a-e6b865046719.png)

This time when I clicked on my first notification icon, it merely reduced to 2 lines, possibly legitimately.

![screenshot from 2014-02-19 08 19 44](https://f.cloud.github.com/assets/4530463/2208533/f9e66dd0-9980-11e3-8fbe-94fd00ff2a8f.png)

When I clicked another notification, the screen became normal:

![screenshot from 2014-02-19 08 21 47](https://f.cloud.github.com/assets/4530463/2208568/47882d76-9981-11e3-86f4-684694f801db.png)

Firefox 27.0 on Ubuntu 12.04.4 LTS.

Not a big issue, but weird and ugly.

**Comment by lefnire** [comment]
Yuck. Any css gurus in our midst? I tried a while to make `overflow-x: scroll` work, but couldn't - some decently complex bootstrappage going on.

**Comment by negue** [comment]
Can be closed, header was renewed.
