### ISSUE TITLE
Can't access "challenges" page

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#2903]
I tried changing tab, refreshing the page, everything I think. I believe a screenshot could explain the situation better than me. (I'm using Firefox)

![2014-02-19 18_19_59-greenshot](https://f.cloud.github.com/assets/6122017/2209317/6f854fb2-998a-11e3-8179-e09cfb9234df.png)

**Comment by lefnire** [comment]
Works for me, can anyone else replicate? UUID @Omnomnobot

**Comment by Atomk** [comment]
My UUID is --> d8fc8d8b-a10f-416a-b089-587db2af9e4d

**Comment by Anna-Davis** [comment]
I am having the same problem as @Omnomnobot

**Comment by Aiseant** [comment]
It happens also to me sometimes (on firefox, too).

**Comment by mrgoodwrong** [comment]
Same here. It's been happening for a couple of days, so there's no way to access challeges. (firefox, chrome)

**Comment by Atomk** [comment]
@lefnire I tried via API, it returns an error 500, so I think it's not something related to browser or users in general.. But I'm not the developer here. :)
We're in your hands.

**Comment by cjapplepies** [comment]
I've had the same thing happening to me since yesterday, on firefox, safari, and chrome, as well as four different computers.

**Comment by lefnire** [comment]
pushing fix now, check back in 5 min and re-open if still an issue. See https://github.com/HabitRPG/habitrpg/commit/4f426b9d24be4b3b31be1bb3fb4a7ad531875b01 , log2viz was showing we were maxing out RAM. My theory is we were loading too much on the challenges page. We could still do for optimizations, using ngInfiniteScroll & adding paging (`{limit:25}`) to challenges.list, but this should get us pretty far here

**Comment by Atomk** [comment]
Oh, now it works! Huge thanks! Maybe you guys can implement something like in the Hall, a page that shows only last created challenges and dynamically adds more as you scroll down - so if someone wants to check only new challenges, there's no need to send the whole challenge object.

**Comment by lefnire** [comment]
@Omnomnobot yes:

> We could still do for optimizations, using ngInfiniteScroll & adding paging ({limit:25}) to challenges.list, but this should get us pretty far here

**Comment by Atomk** [comment]
@lefnire Oh, I think I understood a bit different thing. Let's go back to study English!
