### ISSUE TITLE
Header won't stay unstickied

### ISSUE THREAD

**Issue by nataliezook** [HabitRPG/habitica#2904]
When I uncheck the "sticky header" box, I always get a "server currently unreachable" error despite the fact the automatic refresh immediately starts and completes. After the refresh, the "sticky header" box is suddenly checked again, but the header is not sticky. But if I manually refresh the page or close HabitRPG and then open it again, the header is no longer sticky and I have to go uncheck the sticky header box again. I have no idea what's going on.

**Comment by deilann** [comment]
"Server Currently Unreachable" means it's not saving it to your settings on the server. So on the client side, it will be unsticky, but the moment you refresh, pulling info from the server, it won't remember to be unsticky.

**Comment by nataliezook** [comment]
Ah, interesting! That makes sense. Any reason this and only this isn't reaching the server? I'm have no other repeated issues like this anywhere else in the game. I've tried unstickying the header for several days now.

My user ID:
ec6e08f5-f39d-47f8-95e1-7909cd18965e

**Comment by deilann** [comment]
You might not be noticing the errors-- when you try to click a habit and it
doesn't register or do anything, but you wait for the site to finish
loading, that's the same thing.

I've been having the same problem; so you're not alone. Sometimes, even
when it says the server can't be reached (It says it every time), it sticks
anyway. So refresh after trying (do it a maybe three or four times) and see
if you can get it to fix itself.

**Comment by ChrisInCanada** [comment]
I have the same issue as UnconsciousPlots.  When I uncheck the box for "Sticky Header", I get the "Server Currently Unreachable" error.  I've tried refreshing many times and coming back to retry it.  Also tried on several different computers and different browsers, to no avail.  Any idea how to fix this?

**Comment by nataliezook** [comment]
And despite trying every few days, I've yet to get the header unstickied. I'm guessing there's something up with this particular feature. All the other options under Misc. work just fine.

**Comment by deilann** [comment]
Yeah-- I get the error, but sometimes it works for me, and sometimes it
doesn't. Not sure.

**Comment by paglias** [comment]
Fixed, it was reloading the page before the server could receive the update. It should land on the site in a few days

**Comment by deilann** [comment]
Interesting! I wonder why it was working for me on occasion, then.
Matteo Pagliazzi notifications@github.com wrote:

> Fixed, it was reloading the page before the server could receive the update. It should land on the site in a few days
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2904#issuecomment-36889000

Fixed, it was reloading the page before the server could receive the update. It should land on the site in a few days

**Comment by paglias** [comment]
@deilann it used a 0ms timeout to reload the page. It takes some time to execute the timeout so it isn't really 0ms, if in the meantime the request to the server was reached then it worked, otherwise no. It was a "who is executed before" race

**Comment by deilann** [comment]
Ah hah! Thanks for the explanation.
Matteo Pagliazzi notifications@github.com wrote:

> @deilann it used a 0ms timeout to reload the page. It takes some time to execute the timeout so it isn't really 0ms, if in the meantime the request to the server was reached then it worked, otherwise no. It was a "who is executed before" race
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2904#issuecomment-36889983

@deilann it used a 0ms timeout to reload the page. It takes some time to execute the timeout so it isn't really 0ms, if in the meantime the request to the server was reached then it worked, otherwise no. It was a "who is executed before" race
