### ISSUE TITLE
Gold and Items Lost when Leveled Up

### ISSUE THREAD

**Issue by InsanityxthexGit** [HabitRPG/habitica#2905]
When I level up, I lose 10 gold coins. I have also just lost two quest scrolls.

**Comment by deilann** [comment]
Were the two quest scrolls you lost the same type?

**Comment by InsanityxthexGit** [comment]
Yes

**Comment by deilann** [comment]
Were you doing the same quest right about when it happened?

**Comment by InsanityxthexGit** [comment]
No.

**Comment by deilann** [comment]
Which quest were they?

**Comment by InsanityxthexGit** [comment]
Free Yourself of the Dragon's Influence
I still had one scroll left, so I invited my party to join after the other two disappeared.

**Comment by deilann** [comment]
You should only have gotten one copy of that scroll. Some people accidentally appeared to get multiple copies, and it was fixed.

**Comment by InsanityxthexGit** [comment]
Okay, thank you very much.

**Comment by deilann** [comment]
Do you always lose 10 GP whenever you level up, or did it seem to happen just the last time you leveled up?

**Comment by InsanityxthexGit** [comment]
I noticed it happen the last two times I leveled up.

**Comment by deilann** [comment]
How recently was that? The reason I ask, is leveling up causes a sync. So if you clicked a task and it didn't save to server side, just the client side, due to a 503, leveling up would cause a sync, letting telling you that you lost GP, even though the truth is, you never actually gained it on the server side. You wouldn't see the lost XP because when you level up, you don't see XP.

**Comment by InsanityxthexGit** [comment]
I last leveled up three or four days ago, about the time I made the glitch report. I don't know when the time I leveled up before that was.

**Comment by deilann** [comment]
If you notice you're about to level up, can you do me a favor and do a hard refresh of the page? By loading the page without cache, it'll also take away anything that didn't save to the server. That way, we can tell if it's leveling up that's causing it, or if it's what I suspect. (You can also just refresh once in a while and see what happens, whether or not you're about to level up.)

The best way to avoid this happening, is to click slower. If you send too many requests to the server too fast, some of them fail.

**Comment by InsanityxthexGit** [comment]
Okay, thank you.

**Comment by deilann** [comment]
No problem -- I'm going to go ahead and leave this open. Let us know how things go. :)
