### ISSUE TITLE
Can't leave party

### ISSUE THREAD

**Issue by paulovitorbal** [HabitRPG/habitica#2907]
I created a party, the party has only one member (me, kinnison). When I try to leave it says "successful" but when I refresh the page I'm still on that party.

Party id: c9d983aa-3802-46c1-bb42-1155fb929f22
User id: c6c8c77a-9608-4dcb-9f13-c8046e665d4f

**Comment by Atomk** [comment]
#2936

**Comment by Alys** [comment]
Looks like a once-off bug. Closing.
