### ISSUE TITLE
Died and can't repurchase broken item!

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2908]
Forgot to check off a few dailies, died overnight, and my Ski-sassin Helm broke with no option to reinstate or repurchase it.

UID dfba70b0-4b31-443f-928f-3bae5a200376

**Comment by deilann** [comment]
Caspid, are you still a rogue? You have to be a rogue to purchase that. Also, are you positive it is the item that broke? Apparently some of the time the message on what broke is wrong.

**Comment by Caspid** [comment]
Yes, I'm still a Rogue, but it seems you're right - it was something else that broke, despite the message.  That's a relief.  Thanks!
