### ISSUE TITLE
Lack of feedback when updating habits

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#291]
I never know if my click on a habit has been registered.
Especially if I don't know if I'm connected to the server or not. Perhaps some sign my click has registered, slowly fading could be added as feedback.

**Comment by wc8** [comment]
[Click Feedback](https://trello.com/c/zn8uTNzB) added to Trello.
As a stopgap, watch the right side of the header for +GP/XP or -HP notification. 
You may be interested in the request for [Habit Shading](https://trello.com/c/YSXfecBt) also.

**Comment by killroy42** [comment]
What seems to happen is that when I am scroleld down to the task I'm modifying, the xp Up message appears off-screen.

**Comment by StanLindsey** [comment]
@killroy42 - Thats my fault I missed making that piece of code static. I'll get on that. Cheers!

**Comment by killroy42** [comment]
I thought I was going nuts when everybody told me just to look at top ;)

**Comment by StanLindsey** [comment]
I'm just re-opening this as a reminder for me to sort it out. =D

**Comment by horusofoz** [comment]
@SlappyBag Would assigning the Trello card to yourself keep you reminded?

**Comment by StanLindsey** [comment]
Well I'm not implementing the features on the cards you posted its got more to do with the constant header, which I'm already assigned to.

Even better I'll put it on my HabitRPG. ;)
