### ISSUE TITLE
Invalid indentation, you can use tabs or spaces but not both

### ISSUE THREAD

**Issue by goodniceweb** [HabitRPG/habitica#2913]
{"err":"/app/views/options/index.jade:4\n    2| //html(ng-app=\"habitrpg\", ng-controller=\"RootCtrl\", ng-class={env.getBuildUrl(\"favicon.ico\")}?v=3')\n\nInvalid indentation, you can use tabs or spaces but not both"}

I saw this message when change language from Russian to English.

**Comment by deilann** [comment]
Sounds like Russian has a jade syntax error.
