### ISSUE TITLE
Login/Lost Password Issues & No Facebook

### ISSUE THREAD

**Issue by coffee1983** [HabitRPG/habitica#2915]
There's a long, boring story that prefaces this issue, but I'm not going to relay it here. Suffice to say I was forcibly logged out from the site sometime today, and when I tried to log back in, I would get a password error. It had been a while since I started and I wasn't entirely sure what password I used, so I thought I would just reset it and have done with it. Unfortunately, the reset password wasn't accepted either.

An actual dozen attempts later, and still no luck. By then, my daily deadline had passed, so I figured I would just bite the bullet and make a new account. That worked fine until I wondered if this was going to be a persistent issue. I logged out to test the theory and wasn't surprised to find I get the exact same error. This time, I KNOW the password was right.

Now, not only can I not log into my OLD account, I can't even log into my NEW account. This is extremely frustrating. I had several weeks of work saved on the old one, and quite a few dalies that are now piling up.

Suggesting logging in with Facebook does not help. I don't like Facebook; I don't use Facebook. I haven't even logged into Facebook in over six years, and the email I used to do that with is long since lost. The emails I used to create my accounts were not connected to that site.

Computer details: Firefox browser, running Windows XP. I cannot provide user IDs as I no longer have access to my accounts, but can provide email accounts for both.

Assistance would be appreciated; thank you.

**Comment by lefnire** [comment]
[send me](mailto:tyler@habitrpg.com) the emails for both accts

**Comment by lefnire** [comment]
Following up via email
