### ISSUE TITLE
Growth bar not increasing

### ISSUE THREAD

**Issue by katasha838** [HabitRPG/habitica#2916]
Hello! I have fed my pets a number of food items but have seen no increase in  the growth bar that's underneath it. In fact, the growth bar is present but empty. Is that the case for everyone when you began feeding it food? Or am I the only one with that issue???

Thanks in advance for your help and feedback! =)

**Comment by ThisOtterBeGood** [comment]
Hi katasha,
are you aware of the food preferences?

See http://habitrpg.wikia.com/wiki/Food

Regards

**Comment by katasha838** [comment]
Hi ThisOtterBeGood,

Yeah, I've fed them nothing bit their preferred food, but nothing comes up on my growth bar =/

**Comment by deilann** [comment]
Don't worry -- that sounds like the progress bar isn't rendering. They
should still be getting the points!

**Comment by lefnire** [comment]
@katasha838 which browser you using? Can you try Chrome?

**Comment by katasha838** [comment]
Thanks guys!!! I just got on a comp that uses Chrome, you were right! =) The growth bar is progressing but it just wasn't showing with my browser at home!

**Comment by deilann** [comment]
What browser were you using?

**Comment by katasha838** [comment]
I have internet explorer at home

**Comment by deilann** [comment]
What version? See: #2879

**Comment by katasha838** [comment]
Thanks for the deilann! Useful! However I have no idea what version of IE I'm using.

**Comment by deilann** [comment]
If you check "About" you should be able to see what version you're using.
Probably under "Help"
