### ISSUE TITLE
Yellow tier name for subscribers.

### ISSUE THREAD

**Issue by laurentiu69** [HabitRPG/habitica#2918]
I think subscribers need/deserve also a special rectangle tier around theirs name on tavern chat. Maybe keep the gray rectangle for them and a non-colors/white rectangle for normal users. Or a yellow tier resembling money/gold.

**Comment by deilann** [comment]
I support a badge, but marking subscribers in chat just sounds like a terrible idea all around and I've had many people express how unhappy they'd be if this happened.

**Comment by meganstrickland** [comment]
I understand wanting to give a shout out to those who support HRPG financially, but I concur with @deilann that a badge would be a better way. I don't like the idea of being able to buy greater visibility in the community.

**Comment by negue** [comment]
Leave discussion open or close this?

**Comment by Alys** [comment]
If we leave this open and decide to make a marker, I think it should be opt-in. Some might not want the fact that they're a subscriber being public, since it's related to their finances.

**Comment by crookedneighbor** [comment]
I agree with @Alys.

**Comment by lemoness** [comment]
I think something like a badge would be better than a name tag color - much
more subtle, and I'd like to keep name tags indicative of contributor
status, which is earned, not bought, and tag markers indicative of
staff/mods.

**Comment by crookedneighbor** [comment]
I'd prefer to just not have a subscriber badge at all.

**Comment by lemoness** [comment]
I'm down to close it if nobody is passionate about it.

**Comment by crookedneighbor** [comment]
Since no one has spoken up with a passionate argument for having it, I'm going to close this.

If someone is inspired to argue the point later, just re-open it.
