### ISSUE TITLE
Everytime I do something or reload an error message appears to reload

### ISSUE THREAD

**Issue by tvkiki** [HabitRPG/habitica#2919]
I just created my account, and made some tasks for myself and then next day when I wanted to refresh this error message appeared: Please reload, "Error group not found, or you don't have access." See Chrome console for more details.
I tried to login and logout, reset my account, deleted it and made a new one but it still appears anything i do. 
I use Firefox on windows 7 if that helps with anything. 
I would really appreciate the help, i can't check my daily tasks anymore, they remain checked for every day.
![vglap02](https://f.cloud.github.com/assets/6748947/2230914/6c1b400e-9b09-11e3-8610-3fd64369f2fb.jpg)

**Comment by MagBag** [comment]
I also have this message appearing for the last day or two, every time I open HabitRPG in any web browser -- Firefox, Chrome, Comodo Dragon, on both of my computers (Windows Vista, Windows 7).  The error message does not seem to affect my ability to do anything, however, and goes away on its own without me clicking anything.  I still have full access and I am able to check off my habits/tasks as usual.

**Comment by pippitree** [comment]
I also have this message, again showing in every browser, but not impeding me on doing anything. Just appears and then fades away every time I reload a page!

**Comment by lefnire** [comment]
yowzer, sorry - side effect from my fix to challenges scalability issues yesterday, pushing fix now

**Comment by Jasmedra** [comment]
I've been getting this "Please Reload" error message similar to the one shown at the top in the first comment a few times now today, and I suspect it's all the times when I should've gotten a drop =( Is there a way to fix this?
![habitbug2](https://f.cloud.github.com/assets/6947140/2417358/85cfeddc-ab1d-11e3-8858-8db386b21e7f.png)

**Comment by deilann** [comment]
@Jasmedra We're having server issues-- that's the error you get when you try to do some things (load chats, check off tasks, etc.) and it can't reach the server. See #3065
