### ISSUE TITLE
Suggestion- Option to customize Gained XP/HP/Gold

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#292]
Please make it so that Habits/Dailys/Tasks can be customized to their reward! So that if one habit is completed, it can be customized to give something like...5 gold, 2xp, and 1 HP...or something like that. Customizable HP, XP, and Gold for each Habit/Daily/Task

As far as I imagine, it would be nice if it was something like an On/Off option for customization or default.

Reason for this is because I would like to gauge my rewards to how many or what kind (Habits/Dailys/Tasks) of tasks are sufficient for a specific reward. I don't like to add things as negative points from habits but rather as spent gold for rewards.

**Comment by horusofoz** [comment]
@derekantican Welcome to the community.

Would a Priority system such as that suggested [here](https://trello.com/c/4C8w1z5h) be adequate.

It would meet the underlying functionality you are looking for (increased reward/penalty for specific tasks), tie in with other requested features (start/due date, on hold) and is a more manageable system (dev, support, user XP).

If so please let me know here and vote for the request on the linked card.

**Comment by Pandoro** [comment]
I would also say that the priority system should be the way to realize this. One key part of habitrpg is the fact that it learns how good you are at completing things. If you are able to set the rewards yourself, you are totally loosing this and thus loosing the general gameplay mechanism. I wouldn't add hp rewards to tasks, as this would break the incentive of dying.

**Comment by derekantrican** [comment]
@horusofoz Thanks for the reference! As far as I can tell, that would suffice right there.

@Pandoro I didn't think of adding +HP, but maybe -HP. For instance, if you have one habit that you're REALLY trying to stop (e.g. smoking) you could make it so that it takes off something like 5 HP when you click the "-" on the Habit.
