### ISSUE TITLE
No Cotton Candy Pink Potions?

### ISSUE THREAD

**Issue by storian** [HabitRPG/habitica#2920]
Okay, this is FAR from urgent.. but are cotton candy pink potions supposed to be the rarest of potions?  I was about to say "I have not gotten any in months", but I JUST noticed that I have One.  So, in several months I have gotten 1 pink potion.  Meanwhile I seem to get all the other ones regularly, including gold, which I always assumed was supposed to be the rarest (because it's gold).  So, as far as this "bug" goes, I seem to be getting one pink potion every few months (3? 4?).  This is not a real problem for  me, I can be patient, but since the frequency of pink potions seems so much less than that of all the other potions, I thought I'd mention it.

**Comment by deilann** [comment]
For me, it's skeleton potions. Cotton Candy Pink are rare for a lot of people (they're not the rarest, but they are rare). The RNG is just toying with you.
