### ISSUE TITLE
Getting hit for damage twice by the Free Yourself of the Dragon's Influence Quest boss.

### ISSUE THREAD

**Issue by Drekimond** [HabitRPG/habitica#2921]
I'm doing the Free Yourself of the Dragon's Influence quest and am having the issue of getting hit for damage twice in one day. The first hit will be at my cron time, then second is about an hour after that. I'm not dealing damage twice to the boss, just taking damage. This has been happening since about 2/17/14 (as far as I've noticed). I am not savvy with code or anything so Sorry if this is a double post.

**Comment by deilann** [comment]
What does your party chat look like?

**Comment by deilann** [comment]
If you're seeing it twice in your party chat, this is this: https://github.com/HabitRPG/habitrpg/issues/2805

If it's different, please feel free to reopen.

**Comment by Drekimond** [comment]
I guess it worked itself out. I'm not getting hit twice right now.

**Comment by deilann** [comment]
I've had the "double hits" happen a couple of times myself-- they seem
happen during times the server is stressed.

**Comment by Drekimond** [comment]
If it happens again I'll add it to the number you gave me. Thanks for the
help though. I'm not a techy person.

**Comment by deilann** [comment]
It's not a problem! I hope we can get this sorted out soon-- it's super
demotivating to take what accounts to boss crits!
