### ISSUE TITLE
Scrolling party members in main page not working

### ISSUE THREAD

**Issue by felipecv** [HabitRPG/habitica#2922]
When trying to scoll (vertically) to see the party members, the scroll is not working in both Chrome and Firefox.

My User ID: ed901b9c-6fb4-4e5e-b2a3-69c626ac2abc
![asdasd](https://f.cloud.github.com/assets/6749811/2232075/3698008a-9b17-11e3-97f2-4509390d495e.png)

**Comment by paglias** [comment]
The scrolling is horizontal for pary members, not vertical.
