### ISSUE TITLE
Colored border to indicate task difficulty

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2923]
I think I've seen a similar request floating around in Trello / Github, but I can't find it now. I have code on my localhost which adds a border (well, an inset) to tasks based on their difficulty. [Looks like this](https://www.evernote.com/shard/s17/sh/1b5f647c-5213-4830-8703-2968d01e94dc/04376d38abf8bfeb2da2b11882c254a1). I actually use "difficulty" to indicate "priority", personally. I let the auto-adjust system determine what's really "difficult" in life. This could help me see at a glance what I should be focusing on these days.

Anyway, wanna bounce if off y'all before pushing. If there's push-back / preferred alternative methods, I won't push the code

**Comment by paglias** [comment]
The colors are different from the ones of the task state? If I have a red and difficult task it will use the same colors? In case I think they should be distinguishable

**Comment by deilann** [comment]
I'd test them for colorblindness as well -- I can see all of those color
differences, but red-green folks might have issues.

On Fri, Feb 21, 2014 at 10:42 AM, Matteo Pagliazzi <notifications@github.com

**Comment by lefnire** [comment]
Good points from both of you, in that case maybe a "1.5x" "2x" badge
instead?

**Comment by deilann** [comment]
Where would it go?

**Comment by lefnire** [comment]
Along with everything else I suppose, but then again - we're starting to be
pretty damned cluttered in there... hmm... any ideas?

**Comment by deilann** [comment]
What if the shape of the checkbox changed?

**Comment by paglias** [comment]
Maybe an icon in the title?
Il 21/feb/2014 20:32 "Tyler Renelle" notifications@github.com ha scritto:

> Along with everything else I suppose, but then again - we're starting to be
> pretty damned cluttered in there... hmm... any ideas?
>

**Comment by lefnire** [comment]
Icon probably best, I'll play with that soon
