### ISSUE TITLE
Notifications out of the screen

### ISSUE THREAD

**Issue by federeghe** [HabitRPG/habitica#2924]
If there are too notifications they disappears at the end of the page, and there is no way to show them (scrollbar is not working).
Maybe when end of the page reached, deleting the first notification at top and shifting all others up can solve this.

(notifications in screenshot are intentionally exaggerated)
![screenshot - 02212014 - 09 04 35 pm](https://f.cloud.github.com/assets/979007/2234211/0c055be2-9b35-11e3-9d1e-7a2e8b26df5e.png)

**Comment by deilann** [comment]
So, I don't think there's a way to fix this whilst still using Bootstrap Growl? Then again, I'm still annoyed at #2441 (I still impulsively try to close notifs and end up on the tasks page) so I'm wondering if there are any alternatives.

**Comment by federeghe** [comment]
Bootstrap Growl it seems not very active project...

Maybe http://sciactive.com/pnotify/ ?

**Comment by deilann** [comment]
Oooooh, I like that.

**Comment by lefnire** [comment]
Ooo pretty, & so many options! PR us if your'e feeling adventurous, bootstrap growl was simply the only option at the time (1yr ago)

**Comment by snicker** [comment]
pnotify definitely looks awesome.

**Comment by crookedneighbor** [comment]
Closed with #3237
