### ISSUE TITLE
Alerts don't handle Markdown - maybe partially skip it?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2927]
When I cast a spell (Burst of Flames) on the task that has emoji in the title, an alert on the right shows the link to the image. E.g. `You cast Burst of Flames on ! [Trash] (http://i39.tinypic.com/5aessm.png "Trash Out").`

Can it be filtered to show only `You cast Burst of Flames on [Trash]` - no exclamation mark and no url with alt-text. BTW the name of emoji is needed in the message because some challenges have tasks with the only emoji as a title (and no text).

**Comment by deilann** [comment]
That's not actually emoji -- that's Markdown. I think it would be better to see if alerts can render Markdown.

**Comment by ghost** [comment]
Thank you for remark. I changed the title accordingly.

**Comment by negue** [comment]
Tried it, what I got was `Text :smiley:`, so I think this was fixed some time ago, I'll close this for now, it is still an issue, we'll reopen this.

**Comment by deilann** [comment]
@negue I'm not sure what you mean? This is about markdown, not emoji. (And that's still not properly parsing emoji?)

**Comment by negue** [comment]
Oh, sorry my bad. Seems that I understood it the wrong way :/

**Comment by deilann** [comment]
Is okay. :) Issues are _not_ hard to reopen.

**Comment by Alys** [comment]
Reported again in https://github.com/HabitRPG/habitrpg/issues/5310 so I'm closing this one.
