### ISSUE TITLE
'Stealth' awards Perfect Day

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2929]
I missed several Dailies yesterday due to illness, and had enough mana to cast Stealth for myself to protect my party members from the damage. However, this morning I woke up to a hefty buff of 25 on all my stats (I'm level 49), which I assume means that the game assumed since I took no damage that I'd had a Perfect Day. 

Is there a way around this? I don't want to be rewarded for my own incompetence. :p

**Comment by ghost** [comment]
Resting in the Inn seem to do so too.

**Comment by casicastiel** [comment]
I should also mention that I had been in the inn to protect myself from the cron before that one, if that affects things. Got sick > did about half a day's worth of things > checked into Inn that afternoon > did a few more things the next day > checked out of Inn > still had several things unchecked > cast Stealth > received Perfect Day.

**Comment by casicastiel** [comment]
This just happened again - used Stealth to protect myself from 5 undone dailies, received Perfect Day this morning. The Inn was not possibly related this time.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2565
