### ISSUE TITLE
Has there been any change to the API? "..target machine actively refused..."

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#2931]
I'm getting this error in my client, "System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it."﻿  I'm trying to determine if whether this is a bug in the library, or caused by a change to habitrpg.

**Comment by lefnire** [comment]
Is the error code 429? We implemented api limit for runaway scripts and
haxors. Should be 2 requests / sec

**Comment by fragmental** [comment]
Nevermind.  I thought it was set to beta, but it was set to local.  My mistake. :/

**Comment by fragmental** [comment]
I was laying in bed this morning and I thought "You know...I bet that's set to local..." Sure enough, it was.
