### ISSUE TITLE
Syncing chat from within group should clear that group's notifs

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2933]
I had one of my guild's chats up when I left the computer for a while. I came back and clicked the global sync, and saw a chat notification show up for the guild. So I clicked the "Fetch Recent Messages" button and saw the new chat lines... but the notification didn't clear until I left the guild screen and came back. The fetch button should clear the notif bubble for the group in question.

**Comment by deilann** [comment]
Refreshing the page should as well, and currently does not.

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4958
