### ISSUE TITLE
Profile Images Pull Incorrectly

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2934]
![screenshot from 2014-02-22 22 35 34](https://f.cloud.github.com/assets/6274734/2239787/fb954990-9c54-11e3-9095-b7da21671977.png)

I'd say this is related to images not showing on iOS, but this is only in the profile screen and there are some other issues, like the shirts suddenly being larger.

**Comment by tstark221b** [comment]
all fixed on my end.
