### ISSUE TITLE
'Food and Saddles' section in market contains only food

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2937]
The Saddle is still located down with the special items; the section header is incorrect.

**Comment by SabreCat** [comment]
Whoops! I changed that string so it made more sense in the other two places it shows up (i.e., once you've actually purchased a Saddle). Would it make sense to move the Saddle in the Market out of the Special list into the Food and Saddles group, then?

**Comment by quin-jay** [comment]
I think that would make sense, @SabreCat. That would also create a breakdown between pet-related and character-related items, which feels a lot more intuitive

**Comment by casicastiel** [comment]
Another, even more minor thing: because of the alphabetic sorting, I assume, the saddle appears in the middle of the food (before the strawberry), not at either the front or back where it would seem more logical.

**Comment by deilann** [comment]
I think that's part of the reason the saddle was in special. I preferred it
there.
