### ISSUE TITLE
Improper # of stat points; can't repurchase broken items.

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#2939]
I had an improper # of stat points.  I tried to fix it by dying and re-leveling, but that seems to have made it worse.  Also, it resulted in some items from another class breaking permanently (unable to be repurchased).

It currently shows that I have 17 attribute points at level 23.

UID dfba70b0-4b31-443f-928f-3bae5a200376

improper stats:
![habitrpg _ your life the role playing game - nightly 2014-02-23 10 03 17](https://f.cloud.github.com/assets/2336773/2240912/e0a0f91c-9cb4-11e3-81b6-255848207488.png)

**Comment by Caspid** [comment]
The stat points seems to have been fixed, either with cron and/or another level-up.  I'm still unable to regain the Warrior items as a Rogue though.

**Comment by SabreCat** [comment]
Items from another class need to be purchased as that class. They'll be available for purchase whenever you're a Warrior again, even if they were limited-edition pieces.

**Comment by Caspid** [comment]
It seems somewhat strange to require the user to pay cash in order to regain something he once owned, doesn't it?  Is there a bug about removing this requirement?

**Comment by Caspid** [comment]
Also, there seems to be a bug: changing levels via Fix Values doesn't allocate the proper number of stat points.
STR: Had x stat points available, where x was my current level (24).  Set level to 9, level up, then set level back to 24; # of stat points remains at 10.

Perhaps it's recalculated at cron.

**Comment by deilann** [comment]
Yes, there's at ticket about repurchasing cross class equipment... I don't
have time to look it up right now, but it should be pretty easy to find. (I
think it's also my ticket.)

**Comment by Alys** [comment]
Death no longer breaks other-class gear.

For the attribute bug, see "Changing level with Fix Character Values doesn't adjust Attribute points" https://github.com/HabitRPG/habitrpg/issues/2041
