### ISSUE TITLE
Winged Messenger Set

### ISSUE THREAD

**Issue by clairepg** [HabitRPG/habitica#2940]
I somehow dident receive my Set .Heres my user ID : a874f9eb-35bf-48fa-9e1c-c3ef7ada34ed

**Comment by deilann** [comment]
Did you open your boxes?

**Comment by lefnire** [comment]
Assuming @Golluemchen is from Twiter, then yes. I haven't seen any other complaints as such, @Golluemchen may have hit a down-swing of the server. Goll, in the database it shows no subscription (or any other transactions). I'm also not showing that UUID for any users in the Stripe database. Goll, make sure you [subscribe](https://habitrpg.com/#/options/settings/subscription) - we're not talking about registration
