### ISSUE TITLE
Mystery Items - recoverable after death?

### ISSUE THREAD

**Issue by TwasBrillig1** [HabitRPG/habitica#2941]
Hi, it's currently not clear whether it's possible for the mystery subscriber items to be lost upon death, or how someone would get them back if that happens (unlike limited-edition items, they weren't in the "rewards" column to begin with). 

Is there something in place to handle this possibility? Thanks!!

**Comment by lefnire** [comment]
As long as the false/true/undefined handling works out (as it should be for all equipment in the game, nothing should ever be permanently losable _ever_) then we're good. In the case of class equipment, you can only buy back the gear of the your current class - which is a common point of confusion. Aka, if you can't buy back lost warrior event gear, you just need to switch to warrior and you can. If any of this is not working as expected, re-open and I'll (1) fix, (2) give you back your lost gear
