### ISSUE TITLE
Message notifications appear even if the message is mine

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#2942]
Not really a problem, just annoying.

**Comment by brightbold** [comment]
Yeah, I noticed that too. Got all excited that someone had replied to my message, but no, I was just being notified that I had said something.

**Comment by Alys** [comment]
I can't replicate this. I opened a guild in one tab, with my task list open in another. I posted to the guild. I synced the other tab. I didn't get a notification. I think we've fixed this so I'm closing it. It can be reopened if anyone notices it happening again.
