### ISSUE TITLE
All icons are invisible

### ISSUE THREAD

**Issue by Benga007** [HabitRPG/habitica#2943]
For the past two or three days, all icons have been invisible- my avatar and those of my party, pets, mounts, Matt Boch, all items in the market, gold and silver icons, equipment, etc. Logging in/out doesn't change anything.

![habitrpg no icon bug](https://f.cloud.github.com/assets/6767434/2242623/ce4e94fe-9d09-11e3-9582-ac95adfc158d.png)

Bug appears in Firefox (Windows) but not in Chrome.

**Comment by paglias** [comment]
Try clearing the cache

2014-02-24 5:18 GMT+01:00 Benga007 notifications@github.com:

> For the past two or three days, all icons have been invisible- my avatar
> and those of my party, pets, mounts, Matt Boch, all items in the market,
> gold and silver icons, equipment, etc. Logging in/out doesn't change
> anything.
> 
> [image: habitrpg no icon bug]https://f.cloud.github.com/assets/6767434/2242623/ce4e94fe-9d09-11e3-9582-ac95adfc158d.png
> 
> Bug appears in Firefox (Windows) but not in Chrome.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2943
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by Benga007** [comment]
Clearing the cache fixed it- thanks!
