### ISSUE TITLE
Subscription paid, not active for a full day

### ISSUE THREAD

**Issue by nottnottloop** [HabitRPG/habitica#2946]
Firstly, if this is the wrong place to put this here, I apologize.

After paying by card, I've checked that the payment went through. That was around an entire day ago. There are still no signs I'm on a subscribed account on the main site now.

I have no idea whether it's habit's fault or not, or whether the payment is going through some complex verification process or something. Forgive me if it's supposed to take this long, but I just want to make sure so that I don't waste any subscription time, or possibly miss the February item. My habit account is "NottNott". Thanks :3

**Comment by deilann** [comment]
Can you email tyler@habitrpg.com? He'll need your UUID, not your account name. You can find this under Settings > API

**Comment by lefnire** [comment]
@NawtNawt I'm not showing a payment made for that UUID in our credit-card processor (Stripe) database, meaning it didn't go through. Check your bank to be sure, but you'll likely need to try subscription again

**Comment by nottnottloop** [comment]
Okay, this seems sorted now.

I got a text from Barclays just asking me to confirm if a payment to habit was intended or if it was fraudulent. It stated if you confirmed it was intended no other action would be needed. That wasn't the case it seems.

I've paid again and it ~~should~~ is fine. Thanks :>

**Comment by lefnire** [comment]
Oh Woa! I wonder if we got flagged somehow. One or two others have had a
similar no-transaction experience, I'll contact Stripe soon.  Sorry about
that
