### ISSUE TITLE
Multiple Device Synchronization

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2953]
I died on my phone while offline after levelling up on my desktop while online.  I then proceeded to lose the sword I had bought on my desktop, but not the battleaxe or the morningstar I did NOT lose any levels, and I did lose all my money, but after I had already spent most of it on my desktop.

TL:DR Syncronization of death events on multiple devices that may or may not be connected to the internet
##

**Comment by Ulfethinn** [comment]
similarly, I've died and refreshed the page on my computer to see the results and then logged in on the app and died a second time upon refreshing, suffering the penalty again along with #2789
