### ISSUE TITLE
Is cyrillic font different?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2956]
If I understand right, HabitRPG relies on Lato font family, but as far as I know Lato doesn't have a cyrillic symbol set. Then what cyrillic font is used now? It doesn't match a bit (you can have a look in the guild https://habitrpg.com/#/options/groups/guilds/92900a1d-2d0f-4e19-81c3-e2f2362a4660 )

~~Rotobo~~ Roboto is usually suggested to use alongside with Lato  for latin-cyrillic pages. Can we give it a try and find the best match?
##

**Comment by paglias** [comment]
Probably it uses `sans-serif` which is declared as a fallback for Lato in
the css.

Rotobo is also on Google Fonts?

2014-02-26 19:35 GMT+01:00 Sphinx notifications@github.com:

> If I understand right, HabitRPG relies on Lato font family, but as far as
> I know Lato doesn't have a cyrillic symbol set. What font is used now? It
> doesn't match a bit (you can have a look in the guild
> https://habitrpg.com/#/options/groups/guilds/92900a1d-2d0f-4e19-81c3-e2f2362a4660
> Rotobo is usually suggested to use alongside with Lato for latin-cyrillic
> pages. Can we give it a try and find the best match?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2956
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by ghost** [comment]
@paglias http://www.google.com/fonts/specimen/Roboto
http://www.google.com/fonts#UsePlace:use/Collection:Roboto
It is licensed under apache license 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

P.S. sorry, I misspelled it under the influence of Japanese Rotobo organisation.

P.P.S.Examples of pairings by google:
http://www.google.com/fonts/specimen/Lato#pairings
Droid Sans and Source Sance Pro look good, but I'm not sure if they support cyrillic

**Comment by ghost** [comment]
As far as I understand, the author of the Lato font family has created much more sets of symbols and made everything necessary to get Cyrillic, Greek and maybe other symbol sets on Google code:

> > Martin 2014-08-22 at 07:59
> > Dear Łukasz ... Would you please add Cyril­lic sim­bols to Google Fonts Lato? It’s such a pain to use workarounds!%))
> 
> Łukasz 2014-09-03 at 10:56
> I did.
> [Source](http://www.latofonts.com/lato-free-fonts/)

However only Latin and Extended Latin are available at the moment on [Google Fonts](https://www.google.com/fonts#UsePlace:use/Collection:Lato).

I've found some notes from web devs who managed to get the code from Google and apply it for the symbol sets of Lato family not available from Google Fonts. E.g. [code example with some discussion in Russian](http://ru.stackoverflow.com/questions/357338/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%BE%D1%80%D0%BE%D0%BD%D0%BD%D0%B5%D0%B3%D0%BE-%D0%B2%D0%B5%D0%B1-%D1%88%D1%80%D0%B8%D1%84%D1%82%D0%B0)

Do you think anything of this sort can be implemented? - as I'm not sure the Google Fonts service will have other than Latin symbols set for Lato...

**Comment by ghost** [comment]
OK, after some googling, I guess it will be best to wait for https://github.com/google/fonts/issues/6 to be implemented. May I keep the issue open in the meantime?

**Comment by Alys** [comment]
Closing since this is now being handled in https://github.com/HabitRPG/habitrpg/issues/6710. We'll reopen this if it turns out we have to wait longer before Cyrillic symbols can be supported.
