### ISSUE TITLE
Quest items not adding up?

### ISSUE THREAD

**Issue by Mokona271** [HabitRPG/habitica#2958]
Seemingly either the display of the quest drops or the quest reward counter on the right are not working propperly: 
http://prntscr.com/2w5ihh
(Screenshot)

**Comment by deilann** [comment]
Have you refreshed the screen? Pulling new party messages doesn't update
the quest info. (That should probably be changed.)

**Comment by Mokona271** [comment]
Nah, rebooting, cache/cookies etc. doesn't help:

http://prntscr.com/2wc5i5

**Comment by crookedneighbor** [comment]
@Mokona271 I know this is almost a year old at this point. Looks like it was only counting your contributions to the quest? (9 + 16 = 25) 

I assume by this time whatever bug was happening has been resolved, so I'm closing this issue. If it is not resolved, or someone else has the same issue, let me know and I'll re-open it.
