### ISSUE TITLE
null gold reward

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2959]
I accidentally clicked a reward (I always think the purchase button is the edit cost...) and wasted 10 gold. So I had an idea, what if I created a dummy reward worth -10 to get that back. 
The system allowed me to create the reward but the gold amount was blank. Curiously (I am a programmer by trade), I clicked it, and my gold was all removed. A popup appeared saying -4 gold -56 silver (which was my balance at the time). And now my balance is as 0 and 0.

**Comment by deilann** [comment]
That is curious! Just so you know, if you accidentally lost gold, you can
go into "fix character values" in settings and restore your gp

**Comment by deilann** [comment]
I actually do know the answer to that!

There's a page on the wiki for third party stuff:
http://habitrpg.wikia.com/wiki/App_and_Extension_Integrations

You can also announce it in the Tavern.

**Comment by wc8** [comment]
@Omni239 the issue (how to correct gold values) seems to be addressed (Settings > Fix Character Values), so I'm closing this. If there's still an existing issue, just explain in another comment and we can reopen it.
