### ISSUE TITLE
Mobile with dock clicking [bug]

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#296]
I was trying to use habit on my (Android) tablet (using chrome) with it docked to its keyboard.  It didn't seem to like accepting mouse clicks.  I would click on a daily and the checkbox would appear/disappear, but it wouldn't update XP/Gold.  Also, I tried to add a task unsuccessfully.  I could input the text, but I couldn't add either using the mouse or pressing enter from the keyboard.  I will try to replicate this later.

**Comment by horusofoz** [comment]
@sabin144 How did your testing go?

**Comment by dbueller** [comment]
Can't get it to do it again. Maybe I was just disconnected. You can close
for now.

**Comment by horusofoz** [comment]
@Sabin144 Thanks for the super quick response :)

Closed as per user's advice above.
