### ISSUE TITLE
Rogue only gets drops in the first tasks

### ISSUE THREAD

**Issue by Johangsl** [HabitRPG/habitica#2960]
For some reason I only get drops on the first tasks I complete. Afterwards I don't get more drops no matter what.

**Comment by casicastiel** [comment]
This is normal — there's a cap of 5 drops per day, so users with high Perception (especially Rogues) tend to get all their drops all at the beginning of the day.

**Comment by SabreCat** [comment]
I'm hoping [this pull request](https://github.com/HabitRPG/habitrpg-shared/pull/155) will help spread things out over the course of the day.

**Comment by SabreCat** [comment]
Closing via merge of [the aforementioned PR](https://github.com/HabitRPG/habitrpg-shared/pull/155). See how your drops feel for a while once this hits production, and let us know how it feels!
