### ISSUE TITLE
Mage without Ultimate Gear Achievement

### ISSUE THREAD

**Issue by xiauyu** [HabitRPG/habitica#2961]
Hi there!

I currently have the max equipment for the mage class (Golden Staff, Royal Magus Robe, Royal Magus Hat) however, have not got my Ultimate Gear Achievement badge.

Could someone please take a look at my account? Username: xiauyu (User ID: 60677639-93b7-4cb8-8804-d91e637fda47)

Thanks and regards,
Xiauyu

**Comment by casicastiel** [comment]
See #2259. It's not just you :)

**Comment by xiauyu** [comment]
Thanks! I'll keep an eye out on that one and see how it goes. :)

**Comment by SabreCat** [comment]
Closing as a duplicate.
