### ISSUE TITLE
In Firefox, Guild page join button pushed off screen

### ISSUE THREAD

**Issue by Earthstar** [HabitRPG/habitica#2962]
In Firefox, the Guild page join button is pushed off the screen by the search box, so you have to horizontal scroll to click the join button. This behaviour is not present in Chrome.

<a href="http://imgur.com/OuVNgkl"><img src="http://i.imgur.com/OuVNgkl.png" title="Hosted by imgur.com"/></a>

**Comment by surrogatekey** [comment]
quick CSS fix in case helpful:
.table-striped.ng-scope {width:75%;}

**Comment by negue** [comment]
Now all Guilds are listed under the Search Input.

I'll close the issue.
