### ISSUE TITLE
iOS Sprites Broken

### ISSUE THREAD

**Issue by pipcorona** [HabitRPG/habitica#2964]
With the newest update to the ios app, the sprites are not showing correctly. They are displaying multiple parts of the spritesmith file for each picture.

I've also noticed this when using the website on mobile browsers (chrome and safari on iPads and iPhones)

**Comment by lefnire** [comment]
closing in favor of https://github.com/HabitRPG/habitrpg/issues/2510 . That ticket pointed out that this happens on mobile safari and other browsers as of ios7.0.4. The _app_ issue is new, and so this will need to get fixed asap
