### ISSUE TITLE
Rebirth oddities with missing mystery items

### ISSUE THREAD

**Issue by thepeopleseason** [HabitRPG/habitica#2967]
Following Rebirth, my avatar had the Golden Wings auto-equipped (see avatar in screenshot).

After achieving level 4, however, all mystery items, including the Golden Wings, do not appear in my equipment list.

![post-rebirth mystery items](https://f.cloud.github.com/assets/267868/2284132/fc740a12-9fc5-11e3-9423-1b525d3f3219.png)

**Comment by Minette3714** [comment]
Having the same issue.

**Comment by lorian** [comment]
Same here; rebirth removed all my subscriber items.

**Comment by thepeopleseason** [comment]
Likely related to #2999

**Comment by deilann** [comment]
Yes, it's the same issue. Let's follow it there.
