### ISSUE TITLE
Invite user to party error with Chrome?

### ISSUE THREAD

**Issue by hollabaq** [HabitRPG/habitica#2968]
I use habitrpg on Chrome, just tried to invite another user to join my party, and received this error message:
"  Please reload, "Error User with id "JennyBear13" not found" (see Chrome console for more details)."
Tried inviting same user through a different browser (Firefox) and received the exact same error regarding Chrome... is there an advanced setting I might have missed in Chrome that is causing the issue?

**Comment by lefnire** [comment]
Use their user ID, not their profile name. It's a long string of characters
