### ISSUE TITLE
Suggestion for SMS app

### ISSUE THREAD

**Issue by Damien-Orange** [HabitRPG/habitica#297]
Even people without smartphones should be able to use this without having to go online. Why not make an app like the Google calendar app? Send a + or a - along with the name of the todo/daily/habit you've completed, and it'll register in your profile. I don't know the exact mechanics, but I don't think it should be too difficult to pull off.

**Comment by Pandoro** [comment]
I have no real idea about it, but personally I think it sounds pretty hard to set up. But as far as I remember the apps will have an offline mode which should also fix this :) Well... that is if you have an Android or iPhone :x

**Comment by Damien-Orange** [comment]
Well, yes, but that is the problem-- I don't have an Android or iPhone, and I know I'm not the only one.

**Comment by Pandoro** [comment]
Hmmmm, well this one is up to @lefnire He is the main developer and he
would have to set this up. I think this requires totally different
techniques, so honestly I have no idea if it is realistic. The main
question would probably be if the server that currently runs habitrpg is
capable handling such a thing. Considering the apps are a part of the
Kickstarter though, I think they will come first :x

**Comment by ghost** [comment]
@chokfull post a sketch

**Comment by lefnire** [comment]
SMS is absolutely doable. Definitely not trivial, so we'll have to postpone this. Alternatively, once some of the integrations are provided against apps that currently implement SMS (evernote? wunderlist?) you could use that for your Todos / Dailies.

**Comment by switz** [comment]
I'd be interested in implementing this, @lefnire. Twilio ftw

**Comment by horusofoz** [comment]
@lefnire Is this going forward? If so you'll need to triage the difficult and assign.

**Comment by lefnire** [comment]
will be a whole project, something for the future

**Comment by horusofoz** [comment]
Moved to [Trello 297](https://trello.com/c/HdTdr6IC). For all interested parties please navigate to the provided link, vote on the card and add your voice to the discussion there.
