### ISSUE TITLE
Subscriber items not appearing

### ISSUE THREAD

**Issue by dfjkla** [HabitRPG/habitica#2970]
I just subscribed, but haven't received my Feb subscriber reward. Mystery Item in my inventory has "0" next to it, and when I click on it popup says it is empty.

Reloading the page doesn't help. Do I have to wait for cron? Firefox on Linux Mint.

UID 87a47e8c-5d1f-4910-a030-3f36c70ef816

UPDATE: cron didn't fix things, still no reward.

**Comment by silverthemoon** [comment]
I have the same problem. I subscribed several hours ago, and have yet to receive my subscriber reward. I have tried refreshing the page to no avail. A friend who subscribed earlier today said she got a message in her toolbar about her items, and I've yet to see any message either. 

I'm running Firefox on Mac OS 10.6.

UID b148038b-f297-42d8-8416-43f0f980524b

**Comment by brimmely** [comment]
I'm having the exact same issue. I just subscribed about two hours ago. Not sure if it takes time to appear, but I did receive a "success!" message after I input my payment information, and I'm listed as a subscriber on my profile. The mystery item box is empty, though.

Running Chrome on Win 7.

UID: 9a77344b-168a-4f53-807a-2813f84e9574

**Comment by paglias** [comment]
The mistery items are avalaible only to users who are subscribed on the
23th of each month, I think. So if you subscribed after the 23 you'll
receive the items for march only
Il 28/feb/2014 08:29 "brimmely" notifications@github.com ha scritto:

**Comment by deilann** [comment]
Matteo, I don't think that's true? The point of releasing them on the 23rd
rather than the last day of the month was to encourage people who wanted
the items to subscribe.

**Comment by dfjkla** [comment]
@paglias I doubt that's correct, since Lemoness requested me to raise this ticket in the Tavern.

**Comment by paglias** [comment]
@dfjkla @deilann ok, let's ask @lefnire

**Comment by brimmely** [comment]
@paglias HabitRPG's tumblr was updated this morning saying today was the last day to subscribe and receive the set.

**Comment by lefnire** [comment]
Are ads disabled, the subscribe button checked, or other such subscription
indicators present for those on this thread? I want to make sure it wasn't
an issue of "the credit card didn't go through and you're not actually
subscribed". I'm not at a computer for a while, but as long as subscription
was successful, I can verify the txn timestamp later and fix people
manually, so fear not re: time-sensitivity.

**Comment by brimmely** [comment]
@lefnire At least for me, all those things are present. Also the white button at the top that says "subscribed".

**Comment by silverthemoon** [comment]
@lefnire Yes, all of those things are present for me as well.

**Comment by TwilliK** [comment]
I've also encountered this issue, running Opera on Win 7.

UID: 13cf7733-780a-427f-a46f-62761f284846

**Comment by poetiscariot** [comment]
Likewise, same issue. I searched before posting my (duplicate) ticket, but I just looked for things tagged "subscription."

UID 8dabf913-a480-40af-a84c-29170afada21

**Comment by dfjkla** [comment]
Don't know about ads, running adblock. Subscribed-button is present.

**Comment by lefnire** [comment]
Gonna hit this today, anyone on this thread who hasn't already, post your UUID

**Comment by agentzel** [comment]
Same issue.

UID: 618debcb-a446-478f-8666-18f2b35669bc

**Comment by lefnire** [comment]
This one was weird. For some reason, some users (35 of them) who subscribed had their subscription-creation date set to 2/28. I'd say it's a timezone issue, but some people reported this 2-3 days ago, so that's out. I'd think it's a universal bug, but this only covers 35 of 350 subscriptions during that time frame. I'll investigate before our next subscription item rollout, but in the meantime I just ran [this script](https://github.com/HabitRPG/habitrpg/commit/acc32473a44972d88d804e57fbe1e0a8fd796c53) to give anyone who sub'd before 2/29 their items. report back if any issues

**Comment by deilann** [comment]
Does it recognize 2/29 as a date?

**Comment by lefnire** [comment]
It recognizes `new Date('2014-02-29')`, which is what's used in the script

**Comment by deilann** [comment]
Haha, that's hilarious. You created a new day.

**Comment by dfjkla** [comment]
Fixed, thank you!

**Comment by Ulfethinn** [comment]
I don't know if this is a mistake in logic on my part, but I subscribed around the end of february as well to get the item and it still says i'm subscribed, the mystery box is present, but green, I have all the marks of being subscribed, and I can purchase gems with gold, and yet the mystery box is empty. is this the way it is supposed to be and I am simply experiencing a massive brainderp or is it similar to this threads' problem?

**Comment by lefnire** [comment]
@Ulfethinn uuid?

**Comment by ghost** [comment]
Hi. Having a similar problem as well. Subbed March 1st, and haven't gotten the new March Limited-Edition item. Yes, there is a white "Subscribed" button next to Bailey.

UID: 2d585642-630f-4fce-8822-325c669b41ec

**Comment by lefnire** [comment]
@HabitRPG-MC march item doesn't get revealed until March 25th ([Bailey](https://www.evernote.com/shard/s17/sh/635db74f-1f3f-4693-b533-966c4f3ef6b1/30a114c700b51d07c250a40370538b64))

**Comment by Ulfethinn** [comment]
UID: 53a3d048-ebd7-4dd5-8602-02089f4496b5

but my mistake was thinking that although the twenty fifth is the day upon which all would know what the mystery gift is, that subscribers would be receiving their items on the first day or, thereabouts, of each month. This is to say that the terminology used led me to believe that the unveiling was just showing off to non subscribers a teaser to get their subscriptions where it is actually just the release of the mystery item on the whole.

**Comment by lefnire** [comment]
@Ulfethinn I'm not sure I understand. I'm looking at your account and you actually own the mystery items (check your gear inventory). Your subscription was 2/23, so you should(did) get your mystery items.

**Comment by ghost** [comment]
@lefnire Oh, I must have misunderstood something. The "The awesome people who subscribe to HabitRPG will now receive the limited-edition March mystery item!" part made me believe that we were getting it immediately. Thanks for the answer.

**Comment by deilann** [comment]
@ghost Glad to hear it's cleared up. If everyone who subbed got to see it before it was unveiled, it wouldn't be a mystery very long, even to the non-sub users. ;)

Closing this ticket, as it should all be handled by now.

**Comment by thirdpolice** [comment]
Just subscribed for the first time to get octopus mystery items. Mystery item appeared, but with a "0" next to it. Says "Empty" when I click it. Refreshing page and restarting firefox do not work.

User ID is 1c6567b4-9226-47e7-b52f-e00aefa8b11e

**Comment by deilann** [comment]
Try clearing your cache.

There's a small chance that if you JUST subscribed, it was a touch too
late, but then Tyler should be able to help you out. But to do so, he'll
need your User ID.

**Comment by thirdpolice** [comment]
Cleared my cache, refreshed the page, no change. But I do see a new update message appeared just now, so perhaps it's now July on the servers?

User ID was edited into my post above.

**Comment by deilann** [comment]
Yeah. Might have just missed the cut-off. But @lefnire should be able to
hook you up. Might take a bit, but you should be good.

**Comment by lefnire** [comment]
@thirdpolice try now

**Comment by thirdpolice** [comment]
They're there now. Thank you for your help, both of you!
