### ISSUE TITLE
Subscriber item disappeared after dying

### ISSUE THREAD

**Issue by dandyfloss** [HabitRPG/habitica#2971]
I died today and encountered bug [#2789](https://github.com/HabitRPG/habitrpg/issues/2789); said the item I lost was an Apprentice Staff, but what actually disappeared was one of the subscriber items (robe, can't remember exact name as it's not in my inventory any more). I understand that this is not supposed to happen?

UUID: d981b508-55cd-4aea-9c71-8b92bfc6cdfb

**Comment by lefnire** [comment]
#2999
