### ISSUE TITLE
My dailies are red everyday

### ISSUE THREAD

**Issue by Metahari** [HabitRPG/habitica#2972]
My dailies are red everyday, including the ones that have 40+ day streaks.  I was informed that they aren't supposed to be red everyday after I missed a couple and it killed my party against vice, (partially a caching issue, I thought I had things checked) but still. I do these dailies pretty much daily and they are always red and I guess that means mucho damage. 

Can someone check it out for me? user id - 828284c9-a29d-4220-806d-c29e5a3612c2

**Comment by zoebeagle** [comment]
Have you tried deleting them, re-adding them, and restoring the streak counter?  Does it turn red the next day?

**Comment by Metahari** [comment]
Ok, I deleted and re-added them and restored the streak counter. They are currently green, I'll keep an eye on them I guess. I can see how this bug may be difficult to track down.

**Comment by negue** [comment]
@Metahari does this bug still exists? If not pls close the Issue :)

**Comment by lemoness** [comment]
Due to lack of response, I'm going to go ahead and close this issue. If you're still having this problem, let me know and I'll reopen it!
