### ISSUE TITLE
Minor issue: Costume option missing?

### ISSUE THREAD

**Issue by ricecakies** [HabitRPG/habitica#2974]
I subscribed today and opened my mystery gifts at the same time (they're fantastic, btw). I tried them on my avatar with some left-handed weapons as a costume (class: rogue) but when I tried to take the weapon off, there wasn't an option for "No weapons (left hand)" anymore.  I guess it was replaced by the "No back accessory" icon? The current "No weapons" option only takes off the right-hand weapons, not all. Is it just me?

Browser: Firefox 27.0.1
UID: d9011b96-f6c8-46c0-b7dd-7bd94139b3ff

**Comment by deilann** [comment]
You want "No off-hand equipment" -- for other classes, it's a shield, so
it's not going to say that it's a weapon.

**Comment by ricecakies** [comment]
Maybe my internet was laggy those few days. I tried clicking that as well and the weapon didn't disappear but it's working fine now. Thanks for the info!
