### ISSUE TITLE
Challenge Todo and daily not deletable

### ISSUE THREAD

**Issue by TheWebTech** [HabitRPG/habitica#2975]
I had a challenge which it appears it must have ended but the daily and todo for it are still there and there is no way to delete them.

**Comment by deilann** [comment]
This is a known issue; I can't search for it right now, but the current
workaround is that if you check off one of the tasks, it will recognize the
challenge has ended and you can delete them.

**Comment by hattieshoe** [comment]
Yes, check off one of the tasks, then refresh the page. You should then see the "broken challenge link" (a red square on the task) which you can click and then choose to delete the tasks. Let us know if this works.

**Comment by negue** [comment]
I can delete todos / daily of old challenges.

This can be closed?

**Comment by Alys** [comment]
Yes, hattieshoe's workaround is the standard way of fixing it. It will hopefully be fixed properly at some future time. I think https://github.com/HabitRPG/habitrpg/issues/2763 is relevant.
