### ISSUE TITLE
iphone update glitch - icons/images

### ISSUE THREAD

**Issue by rhonnnnie** [HabitRPG/habitica#2976]
the most recent update for the iphone app has caused the icons and images to... malfunction?
not sure how to describe it, here's what it's looking like for me -
![photo 1](https://f.cloud.github.com/assets/6814794/2293044/79957b94-a065-11e3-9047-51bc931985b6.PNG)
![photo 2](https://f.cloud.github.com/assets/6814794/2293046/7cd9ecb8-a065-11e3-8435-3d4c8bc3ea7c.PNG)

(id is 76416b9e-307f-43ad-8a1a-cce5225eebe1)

**Comment by lefnire** [comment]
#2510
