### ISSUE TITLE
Subscription didn't give the mystery item

### ISSUE THREAD

**Issue by poetiscariot** [HabitRPG/habitica#2977]
I subscribed to HabitRPG during the day on Feb 28, which, as far as I understand, should have gotten me the wings mystery-item set, but it never showed up in my inventory.  I thought it might come in at cron, but no.

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2970

**Comment by apollonaut** [comment]
I'm subscribed currently, and have received the Forest Walker Armor but not the headgear.

**Comment by lefnire** [comment]
@apollonaut uuid?

**Comment by apollonaut** [comment]
a78c6580-dfa8-4680-8a0c-2b2e1014784a

**Comment by lefnire** [comment]
@apollonaut it's still in your mystery box :) you have to click it for each item
