### ISSUE TITLE
broken page, nothing visable but snowmen

### ISSUE THREAD

**Issue by shayleenhulbert** [HabitRPG/habitica#2978]
![habit rpg](https://f.cloud.github.com/assets/6823695/2301172/08659234-a12c-11e3-8916-136b7bafaa41.jpg)

When i signed into habitrpg yesterday this page is all i can see. I can't sign out because none of the buttons work; as cute as the snowmen are i would really love for them to go away so i don't die. Whats happening?

**Comment by deilann** [comment]
@lefnire This is the exact view I get on my nook.

@shayleenhulbert Is your Javascript current and happy? Also, if you try another browser, what happens? (That is Chrome, right?)

**Comment by shayleenhulbert** [comment]
Its a new tower with the latest java scripts and flash installed, and i am using chrome yes. When i try to open it with explorer i can't even log in cause the 'play' button doesn't work. 
My account is fine on other computers, just not this one.

**Comment by deilann** [comment]
Are you sure Javascript is enabled and installed correctly?

**Comment by lefnire** [comment]
there will likely be a javascript error, can you open up chrome console & check?

**Comment by negue** [comment]
I'll close it for now.

If this happens again and we get some javascript console output, then we'll reopen it.
