### ISSUE TITLE
Restart server when down

### ISSUE THREAD

**Issue by Drakas** [HabitRPG/habitica#298]
Strange problem here... The server is under heavy load or is experiencing issues.

**Comment by Drakas** [comment]
Now appears works fine o.O

**Comment by ghost** [comment]
This is an old bug

**Comment by Drakas** [comment]
@Neohuman and why occurs?

**Comment by lefnire** [comment]
It happens periodically when the server crashes too many times as a result
of db optimization issues / memory leak. I have to manually restart
sometimes until we get those fixed.

**Comment by StanLindsey** [comment]
Is it not possible to do timed restarts or spread the power of re-starts incase you're not around? (Not that you're sleeping at the moment.)

**Comment by lefnire** [comment]
looking into it

**Comment by Drakas** [comment]
@lefnire But this issues are contains inside the habit's code or it's a bug of the sql or webserver? Becouse the server shoul not crashes even with a optimization issues / memory leak.

**Comment by lefnire** [comment]
#165 #80 #237

**Comment by Drakas** [comment]
Again.. mmm what about to write a script for auto-restart the server? is it possibile?

**Comment by lefnire** [comment]
I just added an hourly cron restart, that seems to be helping
