### ISSUE TITLE
Hedgehog Quest

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2980]
As it currently stands, it says that it drops gryphon eggs rather than the hedgehog eggs. I'm disinclined to actually do that quest until that's fixed, please. xD <3

**Comment by deilann** [comment]
Dupe of https://github.com/HabitRPG/habitrpg/issues/2979

**Comment by deilann** [comment]
As stated in #2979, I checked the code && the quest certainly gives hedgehog eggs-- it just has a text of Gryphon eggs. This will be fixed ASAP (I'm hoping to let an aspiring coder do it), but you are safe to use your scroll.
