### ISSUE TITLE
suggesting change to announcement dialog box

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#2982]
When viewing habit on mobile web, if you read the assignments then you must scroll through every announcement we've had before you can dismiss the alert. Right now there us almost a years worth of announcements. 

Possibly could be solved with moving the dismiss button to the very top or right under the newest entry. 

I was unsure where to post this but it's not the mobile app itself that you can view announcements on, it's mobile web.

**Comment by lefnire** [comment]
A few things we'll want to do:
- Make announcements a database thing, so we can use a mongo query with a `{limit:10}`. 
- Add a "read more" link which takes to a static page listing everything
- Collapse everything past the main announcement by default (click to expand, or some such)

Database method also allows @lemoness to update messages. this could be a ways out, but on my bucketlist

**Comment by Alys** [comment]
fixed
