### ISSUE TITLE
No Drops Today

### ISSUE THREAD

**Issue by wendellmartin** [HabitRPG/habitica#2983]
I'm a mage (Wendellian), and used almost all my skill points on perception.  Today I have completed about 15-20 tasks, but without a single drop.  Could someone check that the drop system is working correctly?  It's possible I've just had bad luck.  Really bad luck.  I did several of the task completions from the iPhone app, but usually drops are waiting for me when I log into the web app.

Thanks!

**Comment by SabreCat** [comment]
The drops formula changed dramatically, so Perception doesn't push you up to 50%+ drop chance/click so easily anymore. That said, the reduction in drops was a lot harsher than intended, so I pushed [this commit](https://github.com/HabitRPG/habitrpg-shared/commit/734d5585800870f50e91423f11b7a9310be570c2) to ratchet the base chances up. Give it a day or two for that change to hit the site, and let me know how it feels after that. The new scheme, while it had a bad first day, is a lot easier to fine-tune than what we had before.

**Comment by wendellmartin** [comment]
Stings because I'm newer to the site, and am the only one in my party without a full-grown pet or a saddle, even though I am the same level. Hope joining late doesn't put me at a disadvantage for too long. Glad you are tweaking it--still no drops today. I'll let you know if it still feels harsh after a few days.

**Comment by SabreCat** [comment]
Should be rolling out later today, way it looks. Might have swung back too far the other way, but we'll see :P

**Comment by lefnire** [comment]
live for the last ~3h FWIW

**Comment by SabreCat** [comment]
I seem to be getting a drop rate of about 1 in 3 for fresh tasks, for my modestly boosted dude. Feels about right to me; how's it feel on your end @wendellmartin?

**Comment by wendellmartin** [comment]
Much better...don't know if it's too generous or not...but I already got 2 drops with 4 tasks.  I'll need to spend some more time to assess fully.  Definitely more in my favor.  :)
