### ISSUE TITLE
Mobile App Color Issues

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2988]
So, I've started using the mobile app recently, and there's a MAJOR problem. One of the blues looks the exact same color as the grey. This means that I have to distinguish between a daily that has been done and a light blue (?) daily is based on whether or not the text has been greyed out. This is VERY difficult, and means that I cannot reliably use the mobile app.

**Comment by wc8** [comment]
Is this a [mobile](https://github.com/HabitRPG/habitrpg-mobile/issues?state=open) issue or a site issue? Are colors controlled on site or on mobile app?

**Comment by deilann** [comment]
@wc8 It's a mobile issue, but it feels like 99% of mobile issues are tracked in this repo, rather than mobile.

**Comment by Alys** [comment]
I'm closing this since the old apps are being deprecated and we should open a new issue if the problem still occurs in the new app.
