### ISSUE TITLE
Progress bar not showing for habits with only one option

### ISSUE THREAD

**Issue by foriamstu** [HabitRPG/habitica#299]
The progress bar doesn't show when clicking the option. Here are the conditions that reproduce the issue (as far as I can tell):
- Chrome 24.0.1312.56 m
- Only items on the Habits list
- Items with either a plus or a minus option (but not both)
- The issue persists after a hard refresh (Ctrl+F5)

Here's the error and stack trace that Chrome reports:

> Uncaught TypeError: Cannot read property 'date' of null v-IHAELY_6VItMe2RUVtiQ.js:19
> n.toggleChart (line 19)
> i.fn (line 6)
> r (line 8)
> r.trigger (line 7)
> o (line 8)

Let me know if you need any more information.

**Comment by Pandoro** [comment]
This has also been discussed in #130. I think this might have been a design
choice. All you would see is a line going up or down. But I also sometimes
would have liked to see the shape of this curve.

These items also don't get a green / red shade when often clicked. This has
also been discussed somewhere.

What does everyone else think about this? Or is there actually a ticket for
this already that I couldn't find ?

**Comment by foriamstu** [comment]
Design choices usually don't generate JavaScript errors, in my experience at least.

**Comment by Pandoro** [comment]
True true, :)  But in my experience ;) As long as the code keeps running,
everything is fine ;)

But well, just kidding, kind of, this should be looked at, at some point.

**Comment by foriamstu** [comment]
I agree, it isn't the end of the world.

**Comment by lefnire** [comment]
Yeah, that's a bug - sounds like a public/gen/\* generation issue, but those
errors you provided will prove handy - thanks. I'll revisit this when I
have the time

**Comment by Flimm** [comment]
Is the progress on + or - only habits recorded? In other words, once this issue gets fixed, will I see historical data, or do I need to start tracking these habits on my own?

**Comment by horusofoz** [comment]
Please refer to [Shading Onlies](https://trello.com/c/YSXfecBt) for further discussion on this subject.
