### ISSUE TITLE
Lost gold and no sync

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2991]
Hi there, since I upgraded to the recent iPod form of HabitRPG my dailies won't sync and update each day. I've also lost ~1000g that I'd managed to collect... Any ideas?

**Comment by deilann** [comment]
H'm. Is this only happening on the iPod? And are you sure the app is accessing the internet?

If you've lost gold, you can restore it via Settings > Site > Fix Character Values on the web app.

**Comment by ghost** [comment]
It happened when the new version (not the newest version) of the iOS app came out. The web stopped syncing completely and stayed that way for five days, leaving me unable to defeat the dragon and so forth. The app was accessing the internet. I'm yet to try the latest version of the app, but will let you know.

**Comment by deilann** [comment]
Thanks! Hopefully things will work better. I'll be entirely honest -- I have no idea why this would happen.

**Comment by ghost** [comment]
No problem. I do have my day starting at 11am, but it was fine before that new version. I managed to get it working again when I deleted the app - that seemed to help.

**Comment by deilann** [comment]
I wonder if it installed incorrectly or downloaded wrong or something. :(
If you ended up dying because of this or anything, remember that if you go
to Settings > Site (on the website) you can use "Fix Character Values" to
patch yourself up.

**Comment by ghost** [comment]
Thanks - I've updated the app and logged back in - we'll see what happens.

In other news, I completed the Gryphon quest the other day, but didn't get my eggs...?

**Comment by deilann** [comment]
Are you sure you didn't get the eggs? And were one of the people questing, not just someone in your party? Refresh in the Market, just to make sure.

**Comment by ghost** [comment]
I do apologise - they have arrived now :)

On 15 March 2014 08:04, deilann notifications@github.com wrote:

> Are you sure you didn't get the eggs? And were one of the people questing,
> not just someone in your party? Refresh in the Market, just to make sure.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2991#issuecomment-37720115
> .

## 

David Ault
www.davidault.co.uk
Twitter: @astrotour2010

**Comment by deilann** [comment]
It's not a problem @amadan80 -- in the future, whenever something seems to be missing, it's a good idea to refresh. A lot of stuff gets stored in your local cache, which means you might need to tell your browser to look for new info through a refresh in order to see it.
