### ISSUE TITLE
Ultemate gear acheivment is not registering

### ISSUE THREAD

**Issue by Verlanda** [HabitRPG/habitica#2993]
Hey,
I have reached the ultimate level of gear for my rogue character but it has been 2 days and the achievement still hasn't been "unlocked".
Thank you,
Verlanda

**Comment by deilann** [comment]
Hey Verlanda -- in the future, can you do a search for your problem before posting a ticket? There's a search bar up at the top that will allow you to do so.

Follow this bug at #2206
