### ISSUE TITLE
Shade Wolf/Shade Tiger Cub look swapped

### ISSUE THREAD

**Issue by nmynarcik** [HabitRPG/habitica#2994]
I guess this is based on my opinion, however...

**Preview:**
![Shade Wolf and Tiger Cub](http://new.tinygrab.com/8fdce8520e1536269015d50e0a32a9240b4e582be7.png)

Looks as though the shade wolf and shade tiger cub have reversed assets. Tiger cub looks more like a wolf, than the current.

**Comment by deilann** [comment]
Have you seen the entire set? The wolves all look like the wolves and the
tiger cubs all look like the tiger cubs.
