### ISSUE TITLE
Party Leader spent Gems but didn't receive quest scroll

### ISSUE THREAD

**Issue by clusterpainter** [HabitRPG/habitica#2996]
Hi. Our party leader purchased a scroll for our party. The gems were deducted from her account but the scroll never showed up. Can this be fixed? Her username is Biowolf.
Thanks,
Painter

**Comment by clusterpainter** [comment]
I have no idea how accounts work on here, but to clarify, she spent the 4 gems to buy a gryphon quest (the second for the party) and when that didn't work, spent 4 more gems to do the hedgehog instead. We had no issues starting the hedgehog quest.

**Comment by deilann** [comment]
1) How many scrolls does it say she has?

2) What is her UUID? I can't go off of display names, as they are not unique.

**Comment by clusterpainter** [comment]
Her UUID is: 5f68baed-a803-4c4b-9ffc-394e5d0865eb
She says it says -2 in the number count for the Gryphon quest. We in the midst of the hedgehog quest now.

**Comment by deilann** [comment]
This is definitely this then: https://github.com/HabitRPG/habitrpg/issues/2592

Refunding gems to the party leader.

**Comment by clusterpainter** [comment]
So, she got the gems back and used them to try to buy a second gryphon scroll and the same thing happened. Is it possible to fix it so she gets the scroll rather than getting the gems back?

**Comment by deilann** [comment]
I can't grant scrolls. The issue is that she has negative scrolls-- so even adding a scroll wouldn't fix the problem. It needs to be set to 1. I'm going to give her 8 gems. If the count was -2, that should fix it by now.
