### ISSUE TITLE
Subscribed to get February items

### ISSUE THREAD

**Issue by Zorelya** [HabitRPG/habitica#2997]
I subscribed specifically to get the February item set, but due to an unfortunate misunderstanding (and, ironically, my being completely swamped with tasks), I subscribed yesterday thinking that I could still get them.
Would it be possible for me to pay for the month of February in order to get them, or do something else?  I'd be willing to do basically anything >.<

My userid is ce88d3cb-b725-47d6-86a8-34bbac0d0751

**Comment by lefnire** [comment]
Shoot me [an email](mailto:tyler@habitrpg.com) and I'll get you sorted
