### ISSUE TITLE
One un-finsihed Daily killed me (Again!)

### ISSUE THREAD

**Issue by WickedFabala** [HabitRPG/habitica#2998]
Went to bed last night with more than half my HP and wake up this morning to see that my one Daily that I didn't do has killed me!? And this has happened before, but only that time I had just leveled up, went to bed and was dead by morning, losing 2 levels in the process?! How can 1 Daily kill me (especially from 50/50 HP)?

**Comment by praest76** [comment]
This has been happening to me for a week or so. Unless I'm at full health missing one daily out of the ten or so I have will leave me dead when I wake. It never used to be like this. I'm loathe to strip all my to-dos and dalies out and start again but unless this is clarified as a bug I don't see what else to do.

**Comment by deilann** [comment]
Either of you:

Is that daily red? If you don't do a daily regularly, it will damage you more and more as you don't do it.

If you're having trouble staying alive because of this, I highly suggest making it a habit, not a daily.

**Comment by Metahari** [comment]
My whole list of dailies is red every day, even the ones with 45day streaks...

**Comment by praest76** [comment]
Same here. They are permanently red even if I do them daily.

On 7 March 2014 23:59, Stacie notifications@github.com wrote:

> My whole list of dailies is red every day, even the ones with 45day
> streaks...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2998#issuecomment-37081030
> .

## 

Peter
http://about.me/praest76

**Comment by deilann** [comment]
In that case, this is #2972. Let's follow there.

**Comment by WickedFabala** [comment]
Um Not Closed? Why close it because someone hijacked it?
No mine are not permanently red (even with a streak). First time was killed by a green Daily and second time killed by a light red.

**Comment by deilann** [comment]
@WickedFabala Because tickets can always be reopened and you were being unresponsive.

Are you in a party that is questing?

**Comment by WickedFabala** [comment]
I never answered because I still don't know how to fix the problem, and I was hoping someone else would have the answer. :/ 
and no I'm not in a party.

**Comment by deilann** [comment]
@WickedFabala It is impossible for me to give you support or for anyone to give you answers if you don't answer the questions we give you! I can't just magically know what's going on -- I need you to tell me.

What "difficulty" are the Dailies set on?

**Comment by WickedFabala** [comment]
Both were medium

**Comment by deilann** [comment]
Are you positive that all of your dailies were checked and saved to the server? Have you lost any streaks on dailies you know  you did and checked off?

**Comment by WickedFabala** [comment]
I assume they were saved to the server, and I haven't noticed any streak loses.

**Comment by SabreCat** [comment]
@deilann, chill, dude. This sounds like a pretty distressing issue, no need to shout down the person who's struggling with it.

@WickedFabala and @praest76: Couple of questions for you. What browsers are you using? If you're on Chrome, there's a way to dump out user data that could be handy for troubleshooting; if it's something else, @lefnire might need to dig into the database, in which case we'll have need of your user ID from the Settings > API page. Also, does anything behave differently if you delete the Daily and rebuild it?

**Comment by deilann** [comment]
@SabreCat My intention was never to shout down the person who's struggling with it-- I honestly thought the issue was resolved (well, was another issue).

**Comment by WickedFabala** [comment]
I use Firefox (it is up to date). I've never deleted a daily and remade it, but I'll try that. Don't know if I'll see a difference soon though, the deadly daily thing has only happened to me twice (in less than 3 months).

**Comment by SabreCat** [comment]
@WickedFabala: Oof, that'll make it hard to replicate. (If it happened every time, it'd be a huge pain, but at least it'd be easier to find to fix!) Let us know here if it happens again, see if there's any pattern to it.

**Comment by praest76** [comment]
I use Firefox. As per #2972 I removed my allies and readded them and the issue seems to have gone. All dailies asserted returning to green after being ticked.

**Comment by Marcows89** [comment]
Happened also here.
Died from uncompleted dailies (expected), woke up with half hp (not expected), completed all dailies except for one orange one (-9 ones) and woke up dead again.

Funny fact? The orange daily that (I guess) killed me, was "completed" when I woke up.

Already had some sync issue but to die almost 3 times in 2 days, even when completing dailies, and see equipment and gold being wiped out it's really distressing.

**Comment by deilann** [comment]
That sounds like your dailies aren't saving to the server -- make sure to
click slower (clicking quickly is likely to cause errors) and wait for the
blue bar to finish across the screen before clicking something else.

You can restore gold and XP by going to Site > Settings > Fix Character
Values. Make sure to give yourself enough gold to repurchase any lost
equipment. If you're no longer a warrior, you won't be able to immediately
repurchase your carrot sword, but you will be able to repurchase it once
you roll that class again. (Also, there is a bug where it may not actually
be your carrot sword you lost. Sometimes it says the wrong item and the
right one isn't lost until you refresh.)

I highly suggest refreshing before bed, to make sure everything was
actually ticked off. Alys' User Data Display tool is also pretty awesome --
https://oldgods.net/habitrpg/habitrpg_user_data_display.html It will not
only tell you if any dailies are incomplete, but how much damage they
should do you for.

**Comment by Marcows89** [comment]
Thanks for the rapid answer. It seems you were right and the sword were still in place.
Btw I'll follow your suggestion and start using the tool you posted up there.

I'll let you know if this happen again even by following your suggestions.

**Comment by deilann** [comment]
Thanks! I love Alys' tool -- it really keeps me motivated, showing things
like quest progress

**Comment by Alys** [comment]
These bug reports are all old now and can probably all be attributed to sync errors. I'm closing this but if anyone here is still having the same problem, tell us.
