### ISSUE TITLE
Missing mystery item after death

### ISSUE THREAD

**Issue by Reginau** [HabitRPG/habitica#2999]
I died a few times, and then I noticed that two of my February mystery items were gone from my equipment and not available in my item shop either. 
![screen shot 2014-03-04 at 12 24 17 pm](https://f.cloud.github.com/assets/6853799/2324544/7502addc-a3ca-11e3-8ccb-4538369a0fbc.png)

UID: a12bca74-34da-4432-8125-06dc4734f5a2

Thanks!

**Comment by lefnire** [comment]
Interesting. Will take a peek eventually, but note-to-devs - the values are properly being set to `false` in `user.items.gear.owned`. It's likely the `canBuy` in content.coffee for mystery items aren't being handled properly

**Comment by thepeopleseason** [comment]
To the best of my knowledge, I don't think the mystery items are in the current `develop` branch's  content.coffee. 

With Revival, the line here:

https://github.com/HabitRPG/habitrpg-shared/blob/505b473d427a74de5963b52cbe3281b294fcc8ad/script/index.coffee#L388

`lostItem = user.fns.randomVal _.reduce(user.items.gear.owned, ((m,v,k)->m[''+k]=''+k if v;m), {})`

Seems like it needs filtering of user.items.gear.owned. Perhaps:

`lostItem = user.fns.randomVal _.reduce(_.map(user.items.gear.owned, (m)->m if m.canBuy=true),
((m,v,k)->m[''+k]=''+k if v;m), {})`

When it comes to Rebirth, the offending line here: 

https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L460

Looks like it should be:

`_.each gear.owned, (v, k) -> if (gear.owned[k] and gear.owned[k].canBuy==true) then gear.owned[k] = false; true`

(but my coffeescript skills are not really there).

**Comment by Jenkinel** [comment]
Oh! I have this same problem: I died once after a party member missed all his dailies while we were questing (dunno if that's relevant, but I've read that quest deaths are a little buggy still). I received notification that my "robe" had broken. The robe was fine, so I shrugged it off. Now I notice my "messenger wings" are missing, and seeing as they weren't items purchased in the same way as the winter gear, there seems to be no option for getting them back. Would love to retrieve them somehow even if I have to spend gold on it - they were my favourite item!

**Comment by deilann** [comment]
Quest deaths aren't buggy; the boot mechanics just aren't coded yet. They
are exactly like any other death. So likely unrelated.

**Comment by kb-code** [comment]
I have had the same experience... teamie accidentally killed everyone in quest, and it said my "chain mail" broke.  Didn't even know what that was so I just figured I'd buy it back like any regular equipment, but instead my subscribers white messenger robe is gone with no option to replace... how do I go about getting it back?  Happy to buy it with gold if there's a place to go get it... 

update: so when i last logged in, I had option to buy training sword, so that was the equipment that I must have lost before.  However, my robe is still gone...

UID: cf1ba132-f177-4865-a6b6-d16bcb89e5c0
