### ISSUE TITLE
Timezones and completion times

### ISSUE THREAD

**Issue by empish** [HabitRPG/habitica#30]
I'm just starting to use habitrpg.  I do have doubts about the system's machine-learning [1], but I'm willing to give it a whirl.  ;)

However, I just went to enter my daily accomplishments and realized that the program thinks it's tomorrow.  Clearly you and I are on a different timezones :)  While my days aren't 25 hours long [2], the timeframe when I will input my end of day activities will likely vary by several hours, so having the correct timezone is kinda important.  

Of course, it may be simpler and more useful to have an editable date/time associated with a given task.  That way, when I come home after midnight of my timezone, I can still mark the previous day's activities as having been completed the previous day.  

[1] https://github.com/lefnire/habitrpg/wiki/FAQ - How do I customize a task's value?
[2] https://github.com/lefnire/habitrpg/issues/26 ; actually peoples' biological clocks can be https://en.wikipedia.org/wiki/Free-running_sleep , but our world typically isn't

**Comment by lefnire** [comment]
The machine-learning bit is pretty simple at present, and will get more complex the more this project takes off . So don't lose faith just yet. 

A user's "cron" is [run on the client](https://github.com/lefnire/habitrpg/blob/b1cbadb2d1834a720228ab7f73f3a148a10ee576/src/app/scoring.coffee#L211), so it should run on your own computer's timezone. On page-load, in the browser, Habit tests a flag "is it tomorrow yet?" and if so, runs cron. If cron happens not sometime after midnight of _your_ timezone, it's a bug I need to fix. 

You say Habit thinks it's tomorrow on your computer? What happens, exactly, is cron being run prematurely?

**Comment by empish** [comment]
I have two daily tasks that weren't supposed to be active until today.  They were both greyed out yesterday morning, but then yellow yesterday evening. 

I don't know if it would cause cron to run prematurely, but I do use multiple firefox profiles (http://lifehacker.com/231646/geek-to-live--manage-multiple-firefox-profiles).

RE: "On page-load, in the browser, Habit tests a flag "is it tomorrow yet?" and if so, runs cron."  How does this deal with travel through different timezones?

**Comment by lefnire** [comment]
It should just work, AFAIK. I'll have to play with it / do some research,
but `new Date()` in JavaScript TMK just picks up system's configured
timezone, and system clocks typically update when they have internet
connection in new timezone. Again, I'll play around / research that bit and
get back to you on it.

**Comment by empish** [comment]
The more this bounces around in the back of my brain, the morehaving a way to edit the date/time stamps seems to make sense.  The automated method _should_ work most of the time, but when there are computer or network issues or when someone doesn't have access to a networked computer, an edit option would solve the problem.

**Comment by mfcovington** [comment]
I'm on the west coast and when I checked at 10:40PM, it was already 'tomorrow' (sort of).
- All my dailies had reset (and were green if I had checked them, so they were definitely registering as having completed since it was my first day)
- However, I ++'d a hobby and looked at the progress chart... it only had the real today's date, not tomorrow's.

Edit: Happy to report that when it really became 'tomorrow' (as of 12:10 AM), nothing reset. I was concerned that back-to-back resets of dailies would nearly kill me. Also, after ++'ing a hobby, the progress chart shows, rightly so, that it is now 'tomorrow'. So, this might be a clue... Is the time on the progress chart generated differently than the time that dictates when dailies are reset?

**Comment by mfcovington** [comment]
So, I've been using habitrpg for a few days now and it seems to reset the day twice a day for me. I'm on the West coast and the dailies get reset ~ 10PM local time and then they get reset again when I login in the morning. Is this possible or do you think it is just an issue with the server? As a result, I've had to add a habit that I just click a bunch to get me to the next level so I'm not dead.

**Comment by lefnire** [comment]
We should be good on this now, cron has been offloaded to the client. It'll take a full cron cycle to kick in for people - you have logged in one day, and the next day the cron issue should be fixed from then on out. If anyone experiences this timezone issue occurring more than once from here on out, hit me up. (@mfcovington - I think you should calibrated now)

**Comment by mfcovington** [comment]
@lefnire Sounds great. I'll keep you posted.
