### ISSUE TITLE
ToDo Tasks Due By

### ISSUE THREAD

**Issue by tommy1019** [HabitRPG/habitica#300]
Make an option for a task to be "due" by and give more points the further away from the due date its done, and damage the player for each day its not done

**Comment by Pandoro** [comment]
This, and many possible other applications of this idea has been discussed in this issue #204 

If this is similar to what you are thinking, please vote for that trello card. Otherwise  post something here, than we'll discuss further :)

**Comment by horusofoz** [comment]
Welcome to the community @tommy1019

Your idea is a great one and has been raised on our [Trello Board](https://trello.com/c/i6kXvNY2). Vote for your idea to see it added :)
