### ISSUE TITLE
Hedgehogs Face Wrong Way

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3000]
All the hedgehog sprites need to be flipped!

**Comment by lemoness** [comment]
*Hedgehog PETS. I presume the mounts are correct.

**Comment by pipcorona** [comment]
While they are being flipped, could they be updated to actually match the template for all the other pets? The dimensions of the hedgehogs (67x74 pixels) are not the same as the other pets (81x99 pixels) which is probably what led to the issue I thought I had read about before with them not being positioned properly.

**Comment by lemoness** [comment]
Whoever tackles this issue - let me know if you want me to repost the
hedgehogs to be correctly oriented with the proper dimensions.
