### ISSUE TITLE
Taking hits for not completing dailies when I have, believe its a chron issue.

### ISSUE THREAD

**Issue by callumbaillie** [HabitRPG/habitica#3003]
I'm getting hit for not completing dailies when I know I completed them all. I'm noticing that in the party tab I'm getting damaged by the gryphon at around 6 am local time. I think whats happened was I put it a custom day start time, then realized there were issues with it and changed it back. Now I'm not sure whats happening with the chron, but my guess is that its calculating the damage at 6 not at midnight. If my dailies are resetting at midnight, then perhaps that's why I'm taking damage, because they're no longer checked when it calculates the damage?
I'm guessing, really, but either way, somethings wrong and I'm getting penalized even when I've actually had a perfect day, which is frustrating. It doesn't matter so much now because I'm only a level 3, but later, I think its going to start really bothering me.

**Comment by deilann** [comment]
Cron currently runs when you log in after your day start-- so that's when you'll take the damage and when it will check whether or not things are checked off.

**Comment by callumbaillie** [comment]
Yeah, it seems to be working OK now. Perhaps for some reason my dailies weren't checked. I've started double checking at the end of the day to be sure that if I close the browser then come back that the dailies are definitely all grayed out.

**Comment by deilann** [comment]
When double checking, it's a good idea to refresh, just to make sure it all
saved to the server.

**Comment by callumbaillie** [comment]
Yes thank you. I'll be doing that from now on.
