### ISSUE TITLE
Backstab causing negative mana

### ISSUE THREAD

**Issue by sirsavary** [HabitRPG/habitica#3005]
I used backstab a few times in a row (4 to be exact) and ended up with -13~ (rounded up to -14) mana. On top of this, my level up did not occur even though I had more than enough experience.

Screenshot of the mana and xp bars: http://gyazo.com/18b6327718d57d2a232c2de385a65184

I did a search for other tickets https://github.com/HabitRPG/habitrpg/issues/2012 which appeared to be caused by using backstab on the task checkbox. I did not use backstab on the checkbox. This may be related to the weird damage calculations I have been encountering over at https://github.com/HabitRPG/habitrpg/issues/2957.

**Comment by deilann** [comment]
Sounds to me like you got hit with a double server request, so it processed twice. Level up doesn't happen currently with skills, but once you do anything else that changes your stats, it'll occur and you don't lose any XP. See: #2143 

What happened here is you clicked too fast. Slow down your clicks, and this should not happen again.
