### ISSUE TITLE
Got more than 10 drops in a day

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#3006]
Today I've gotten 14 drops so far; did something remove the drop cap? Is this deliberate?

**Comment by deilann** [comment]
High PER now nudges up your drop cap, a la SabreCat's redoing of the system.

**Comment by lorian** [comment]
So, the thing that worries me here is I'm level 9.

**Comment by lefnire** [comment]
And double that if you're a subscriber

**Comment by deilann** [comment]
Oh, and rebirths bump it up, too, I believe.

**Comment by lorian** [comment]
Wow, that must be some bump then! Ok, mystery solved.

**Comment by lefnire** [comment]
Plus triple if your name is "lorian". Regex IIRC
