### ISSUE TITLE
Graphs have disappeared on some of my habits

### ISSUE THREAD

**Issue by tog22** [HabitRPG/habitica#3008]
This affects some but not all of my habits. The graph shows up but with no line.

I'm user tog2014 and am happy to share my account details if this'll help debug this. Not a big deal but thought this might affect others!

**Comment by deilann** [comment]
The graphs are mostly useless as it is, unfortunately. There's a revamp in the works #2516

**Comment by crookedneighbor** [comment]
Since this is very old, I'm closing it.

@tog22 If you're still having issues, please re-open it.

**Comment by tog22** [comment]
Yeh, not having issues any more

**Comment by crookedneighbor** [comment]
Awesome, thanks for reporting back!
