### ISSUE TITLE
Rearranging Getting Messed up

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#301]
For some reason, my arrangements of tasks and such are getting messed up. I'm not sure when it happens (e.g. login, refresh of page, etc) but it's just that when I go to mark something as completed, it's in a different spot than I put it.

**Comment by Pandoro** [comment]
I have also experienced this a while back. I can definitely say that it occurred on my work pc, FF17 Ubuntu 10.04, but not at my home pc (with a different FF I think and Ubuntu 12.04). 

Issue #212  might also be related to this.

**Comment by StanLindsey** [comment]
#318
