### ISSUE TITLE
Mystery item wings can't be removed

### ISSUE THREAD

**Issue by brimmely** [HabitRPG/habitica#3013]
Hi, I tried on the wings to see what they'd look like and now I can't take them off. 

Running Chrome on Win 7.

UID: 9a77344b-168a-4f53-807a-2813f84e9574

**Comment by TwasBrillig1** [comment]
(I'm not a dev; sorry if I'm not supposed to be replying here!) @brimmely, if you look along the row of "base" slots on your equipment page, there's a light grey square for the back item (beside the headgear slot). You can click that to remove the item that's currently on your back slot.

**Comment by paglias** [comment]
@TwasBrillig1 of course you can reply here and in fact it's very appreciated. Thanks!
