### ISSUE TITLE
Avatar being displayed oddly.

### ISSUE THREAD

**Issue by Pol-S** [HabitRPG/habitica#3015]
Currently my avatar in the Habit RPG app on my Iphone 5 looks very odd. My avatar seems to be a lot of random parts and even my equipment gold shop is rendering oddly.

http://imgur.com/euqKxGi
http://imgur.com/AJtSCAh

What's more I've check on the main website and can see that my avatar looks normal compared to what I see on my phone. I've tried deleting and downloading the app again, but the results look the same. Has anyone else encountered this issue? Anyone know a way around it?

Username: Pol S

**Comment by deilann** [comment]
This is a known issue: #2973 is the correct ticket, I believe.
