### ISSUE TITLE
Can  you help me get my stuff back?

### ISSUE THREAD

**Issue by FixiePixie** [HabitRPG/habitica#3016]
Someone stole my laptop, and to protect my privacy (because I was logged in all the time), I deleted my old account. I'm an early user who had a veteran wolf, and I had bought some gems back when doing so would disable ads. I'm wondering if there is any way I get those things back for my new account?

**Comment by deilann** [comment]
Can you email tyler@habitrpg.com about this?

**Comment by lefnire** [comment]
handling offline
