### ISSUE TITLE
Site on Mobile doesn't update

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#302]
I use a Nexus 7 tablet to access the site when I'm not at my computer and it doesn't seem to update with the changes when I update tasks on my computer. For instance, if I mark a task as completed, spend gold, etc, it won't change on my tablet. I've tried refreshing the page, closing the page and revisiting the link...but it doesn't show it as updated. Is there something I could be doing wrong?

**Comment by Pandoro** [comment]
For me it worked pretty okay on my nexus 7 if I recall right, it did however completely fail on my Galaxy R smartphone. I somehow get the feeling the site in general isn't working so great on mobile devices yet :( 

You could try different browsers on your tablet. I think I used chrome, but maybe it works better in Dolphin or Firefox?

**Comment by StanLindsey** [comment]
Works fine on IE-Mobile for me, surprisingly. I need access to more phones to test it on other browsers.

**Comment by derekantrican** [comment]
Now it seems to be working better, but I would agree that the site probably
doesn't perform as well on mobile for some reason. Can't wait for that app!

**Comment by dbueller** [comment]
I can't reproduce #296 either.

**Comment by horusofoz** [comment]
Issue appears to be resolved. Suspect cause was broken DB connections. If recurs please feel free to re-open ticket or raise a new one referencing this for background.
