### ISSUE TITLE
Extensions Page Broken

### ISSUE THREAD

**Issue by HalfAdd3r** [HabitRPG/habitica#3022]
# Short Summary

The link from the main page for extensions gives a Drupal error page.  
http://community.habitrpg.com/extensions
# Error

PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111) in lock_may_be_available() (line 167 of /home/lefnire/Sites/habitrpg-community/includes/lock.inc).

Via Chrome

**Comment by deilann** [comment]
Yes, the community site no longer exists. That link will soon point elsewhere. I guess I should remove it for the time being or replace it with a wiki link @lefnire?
