### ISSUE TITLE
Habitrpg Synced and I lost all gold + level

### ISSUE THREAD

**Issue by chippythemad** [HabitRPG/habitica#3023]
Hey guys

I opened Habitrpg on Firefox (updated to 27) on my phone (Nexus 5, stock, android 4.2.2) via a bookmark on my homescreen and it opened to level 9 even though I had leveled up to level 10 an hour or so ago (on my laptop, Firefox 27, Windows 7). I seemed to have retained all my equipment and stats. I don't think any of the new dailies i entered were affected either.

This happened earlier today as well but I didn't think much of it. (In that instance I had lost a piece of equipment and skills.) But now that it's happening again it can get pretty demoralizing. (Especially when you're a rogue lol. I love my gold.)

**Comment by chippythemad** [comment]
Something else I noticed. My avatar shows me having short swords but in my rewards it shows a dagger for sale for zero gold. I bought it and the game equipped it to my avatar and skipped to showing scimitars for sale again. (I had never purchased any so that's fine.) I just went back to the equipment menu and found the short sword and re-equipped it.

**Comment by deilann** [comment]
That means your dagger is what broke, and you have to repurchase it in
order to buy the next tier. You're lucky that what broke costs no gold. :)

**Comment by Alys** [comment]
Closing because this is from March 2014.

FYI there is information about sync errors at http://habitrpg.wikia.com/wiki/Sync_Errors
