### ISSUE TITLE
Problem with setting up HabitRPG Locally

### ISSUE THREAD

**Issue by filkaris** [HabitRPG/habitica#3026]
Hello guys!

I didn't know where to ask this, so I post it here.

I used to have Habit working locally 3-4 months ago, and everything was great.
Now, I can't seem to make it work. I even tried a fresh checkout from github, and still nothing.

There are some warnings when I do "npm install", 

![screen](https://f.cloud.github.com/assets/1624978/2357088/5bed94da-a5f8-11e3-875c-b56717d7db22.png)

and when I run it, I get this:

![screen2](https://f.cloud.github.com/assets/1624978/2357093/6355db10-a5f8-11e3-8029-76462431164d.png)

Any ideas?
Thanks!

**Comment by deilann** [comment]
You've got a problem with the file listed. Have you edited that file?

When you say you've tried a fresh "checkout," do you mean you've done a
recent upstream pull?

The npm warnings, afaik, should not be a problem.

**Comment by filkaris** [comment]
Thanks for the quick reply :)

Yes, I actually cloned it all over again. 
Still "pull upstream develop", says Already-up-to-date.

No editing whatsoever...

**Comment by snicker** [comment]
Some additional configuration settings were added to `config.json.example`, if you haven't updated your `config.json` you could be experiencing this error. You'll also need to run any DB migrations or wipe out your DB and start fresh if you haven't pulled in several months.

**Comment by filkaris** [comment]
Turns out I forgot to create the config.json file!
I also erased the database to create a new one, and everything works as a charm :)

@snicker and @deilann thanks a lot!
