### ISSUE TITLE
Thoughts on Drop Caps

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3027]
cc @SabreCat who asked for this, also @thepeopleseason

SabreCat mentioned that the drop caps got pretty ridiculous with high PER for subbed users-- and I think they should stay that way, if not made infinite.

Like thepeopleseason mentioned in the past, if users know they have a chance of getting a drop, they are far more likely to do a task. I, for one, am very unconcerned with users abusing this, for the following reasons:

1) As @lemoness has pointed out, gen1 pets are not a heavily utilized monetization feature, as users want to feel like they've earned their pets. Having unlimited drops as a subscriber should not cut into revenue.

2) As the users are subscribing, they are far less likely to game the system. If Habit is working well enough for them to spend $5/month, they know they are only cheating themselves.

3) By the time drop rates become frequent enough that they would be getting excess drops, chances are the user is either very close to Beastmaster or already has it. This means that they're either looking for very specific eggs/potions or food. Because of this, the drive to get drops is even more pronounced-- you got another base hatching potion, but need a CC Blue? Well, maybe if you clean the kitchen, the RNG will favor you more.

I also think that a better way to handle the drop rates is to reduce your drop chance every time you receive a drop. This would help handle the issue of lower level users receiving almost no drops, and fix the issue of higher level users still receiving copious amounts of drops. PER could still up the drop rate overall. I'd also suggest having subscribing up the drop rate in this instance, so the user can take advantage of higher/infinite drop caps.

**Comment by thepeopleseason** [comment]
Agreed on all counts, but tracking per-day drops for a given user seems like computational/data structure overhead which may not be worth it. One alternative could be a computation based on level. 

Edit: Ah, ignore the previous--looks like this is _already_ tracked. 

I mentioned this to @SabreCat in the Tavern: I'll have to study the new drop algorithm in more detail, but given high PER levels are completely achievable without a subscription, I'd rather a subscription grant infinite drops. 

For those coming into the conversation, [here's my initial thoughts on the drop cap](http://habitrpg.wikia.com/wiki/User_blog:Thepeopleseason/Why_there_should_be_no_Drop_Cap), complete with links to an article about the neuroscience behind it.

**Comment by lemoness** [comment]
Exactly how much does PER raise the drop cap, now?

**Comment by thepeopleseason** [comment]
It's (current PER value) divided by 25. @SabreCat changed it after the drops overhaul because it was initially divided by 10.

**Comment by crookedneighbor** [comment]
Changes have been made to the system. Closing this for now.
