### ISSUE TITLE
CSV Export data contains tasks no longer on task list

### ISSUE THREAD

**Issue by LittleRabbitBeta** [HabitRPG/habitica#3028]
I exported my data this morning and noticed that there are tasks on there that I deleted from my task lists a long time ago. Sample:
"10,000 steps","e74b1177-5b40-493c-8ed9-574dfc712be9","daily","03-07-2014 13:12:21","21.24378203984096"
It appears the system is still counting them.

971073fb-154f-40b1-a288-6ef89f1640ae

**Comment by LittleRabbitBeta** [comment]
Upon closer inspection I see I didn't delete the task. But is was greyed out for a long time AND is only "active" on certain days however it appears it is being counted on a daily basis.

**Comment by deilann** [comment]
Yes -- it's showing its task value every day, which shouldn't change if
it's greyed out (and not checked), but still exists.
