### ISSUE TITLE
Message alerts from a party that I don't belong to anymore?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3031]
User ID: 64f83041-2071-4979-914c-19d5a65e7c7f

I was removed from my old party by the leader, but there is still a new message alert in my toolbar that won't go away from the previous group... how can I get that removed so that the alert function works for messages in my new party?

When I click on the message alert, I get the following error message:

Please reload, "Error Group not found or you don't have access." (see Chrome console for more details).

**Comment by deilann** [comment]
Urf--  not entirely sure there's a way atm besides asking your old party
leader if you can be invited back and then leave after getting rid of the
notif on the honor system.

I think this definitely speaks to the need for a "dismiss all alerts"
function && the ability to remove alerts by a refresh in the appropriate
page.

**Comment by lefnire** [comment]
@im2dmnq2bstr84u (how do you remember that uname?) is the party you _were_ in "Vencarlo ISN'T Blackjack!", or is that the current party?

**Comment by deilann** [comment]
@lefnire I'm going to guess because it reads out to "I'm too damn q to be
straight for you."

**Comment by ghost** [comment]
The party that I currently belong to is called "Vencarlo ISN'T Blackjack!" and is a bit of an in-joke. The other party was called "Creidieki's Totally Awesome Self-Care and Productivity Party for Rad People" which I was booted from by the party leader. As for my s/n, it's "I am too damn cute to be straight for you" when read out, yes.

**Comment by Alys** [comment]
This is no longer a problem because each notification has a cross next to it for cancelling the notification without visiting the party or guild.
