### ISSUE TITLE
Repeat by day on Dailies not working for me

### ISSUE THREAD

**Issue by bobolous** [HabitRPG/habitica#3032]
On a Daily, under the Repeat heading, I can click the day buttons and they become a little brighter, but when I click a second day that I want it repeated the previously-selected day turns off again and I'm left with only one day selected. I have tried holding shift, control, etc, but I cannot select multiple days.

Furthermore when I save the item the single day I have selected (as that's all I'm able to do) simply disappears.

I'm therefore unable to specify that work-related Dailies should only occur on weekdays. (Or, indeed, I'm unable to specify that any Daily should recur on any given day or days!)

This was previously listed as Issue #937 which is closed. But it is still a problem for me. I'm on Chrome (up to date: Version 33.0.1750.146 m)

I get not java script errors when making Repeat selections or when saving Dailies with a Repeat day selected.

I have tried syncing and refreshing etc.

**Comment by bobolous** [comment]
I am an idiot. The Daily I was using was an imported Challenge Daily and I therefore couldn't change the days. (This wasn't very obvious but it's understandable now!)

**Comment by deilann** [comment]
Don't feel bad -- I've done the same thing.

**Comment by bobolous** [comment]
Maybe there should be a more obvious "lock" on items imported by Challenges.

**Comment by deilann** [comment]
I wouldn't argue with that. I'd also like to open up more options for
challenge creators allowing specific things editable.
