### ISSUE TITLE
Boss not taking damage

### ISSUE THREAD

**Issue by hametsunosaturn** [HabitRPG/habitica#3033]
My friend and I are in a party fighting The Fiery Gryphon quest, I swung for  53 damage and brought him down to 8 HP, which should have been low enough for my friend to kill him when she logged in that day. But all day long she logged in, logged out and back in again, refreshed, did anything she could, and it never registered her damage. So we decided to wait until today, but kind of held off on our big To Dos til we started our next quest so that we didn't waist like, 50 damage points on a boss with 8 hit points. So I just checked off all my dailies, and also cast Valorous Presence on my whole party. As you can see, I did 53 damage the first day. Today, it only swung for 7.6 -- it looks a bit suspicious when it keeps /just barely/ not killing the boss and also not taking any extra damage from the other party member who, until now, was able to hit he boss. Is there some weird glitch not letting us end this quest?

Also, before I started the quest, I had 5 scrolls, then once I started the quest, I only had 3. Why would it take 2 scrolls to play one time? I've since used my gems to purchase another one, but will it continue to do that?

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg/issues/2613

**Comment by hametsunosaturn** [comment]
So, I understand that the first part of my question was similar to the other issue, but what about the second part? Where it cost two scrolls to start my quest.

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2592
