### ISSUE TITLE
Checklists impossible in Chrome on Nexus 4

### ISSUE THREAD

**Issue by Cassolotl** [HabitRPG/habitica#3042]
![screenshot_2014-03-09-23-21-28](https://f.cloud.github.com/assets/6607512/2369643/2691211c-a7e2-11e3-8951-b475985e621a.png)

I hope it's clear from this screenshot. If I use Chrome on my Nexus 4 I can't press enter/carriage return, because that key isn't available. There's no "add checklist item" button so a checklist entered in-browser can't be more than one item long.

**Comment by paglias** [comment]
Try pressing Go (bottom right corner) it works on my Galaxy Nexus on
Android 4.2
Il 10/mar/2014 00:28 "Lottiotta" notifications@github.com ha scritto:

**Comment by Cassolotl** [comment]
Interesting. I just tried it. It's a bodge and it takes forever, but it's possible. I press "Go", it saves and closes with an empty checklist item at the end. I click the pencil to edit, repeat the process, and eventually have all the checklist items. But I have to save and re-edit after each one.

Thanks. :)

**Comment by paglias** [comment]
@Lottiotta It works on my Galaxy Nexus.. which should be slower than your Nexus 4.

Consider that HabitRPG website is very heavy and it's "normal" that it struggle on mobile.

If you try to add another checklist item after the first one in the empty checklist item that appears, it doesn't work?

**Comment by Cassolotl** [comment]
That's so weird! Today pressing "Go" works as it should, without closing the edit interface thing. _shrug_ Sorry to bother you!
