### ISSUE TITLE
Pet hatching bug/overlook?

### ISSUE THREAD

**Issue by onlikeespe** [HabitRPG/habitica#3043]
I noticed in the inventory interface for hatching eggs, where eggs that are compatible will show up with green highlighted backgrounds, that it gives you the option to hatch a pet of an animal you have already made a mount out of -- even though it will not let you hatch a pet of an animal you already own. I'm wondering if this is a bug, or possibly an overlook by the developers? Is this intentional? If so, this leads me to my next question:

Another small problem I had was that I also wasn't aware that they were supposed to 'grey out' at first - my first mount, a base wolf, just vanished and I thought when it turned into a mount, the pet was gone, because it had turned back into the pawprint with the question mark. I figured I would have to hatch another one to get the Beast Master achievement, because it suddenly no longer counted, but when the rest of my pets matured and just greyed out (still counting out of the 99), I got confused. There's a very unsightly question mark paw that I would like to get rid of, but I worry about hatching another base wolf. Will this break my game if it reaches maturation? I've already got 51/99, I don't want to have to restart now.

Thank you for your time and effort!
-on.like.espe

**Comment by deilann** [comment]
1) Yes, it's intentional. Once you evolve a pet into a mount, you can no longer equip it as a pet, so it must be rehatched if you'd like to equip it.

2) The Beastmaster fix that I coded was not retroactive. That fix is the one that helps the game remember what pets you've found, but evolved. Hatching another base wolf won't be a problem.

**Comment by onlikeespe** [comment]
thank you!
