### ISSUE TITLE
Critical hit rolled back

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3048]
Today I scored a critical hit, got the notification and the extra Experience and Gold... and then immediately thereafter got a notification of lost XP and Gold. I didn't react in time to screenshot it to be sure, but it seemed like I lost the crit bonus and kept the base value.

I noticed that I also got a chat notif from my party during the sync from that click, and it turned out someone had cast Valorous Presence. Does the `_.reduce` of `user.stats` include buffs? In that case, it could be a `predictableRandom` issue: the server had my updated stats, which didn't roll a crit; the client had my pre-buff stats, which did. Server wins of course, so I got faked out.
##

**Comment by caveman1337** [comment]
Possibly unrelated problem, but I've noticed critical hits can also apply when unchecking dailies (which cause you to lose extra HP and gold).

**Comment by SabreCat** [comment]
Aye: #2356 (though I thought that one was fixed, hmm!).

**Comment by paglias** [comment]
Critical hits are handled on the server now
