### ISSUE TITLE
Time zone issues?

### ISSUE THREAD

**Issue by cogsmac** [HabitRPG/habitica#305]
I didn't have the option to set my time zone. Not a huge deal, but it would be cool if my daily tasks could re-set at a certain time based on my preferences.

**Comment by Pandoro** [comment]
It should reset at 0:00 am your local time, but I also would like to set it to something like 1 or 2am.

This has been suggested before though #30

You can vote for it on [Trello card 15: Timezone & Day Start options](https://trello.com/card/timezone-day-start-options/50e5d3684fe3a7266b0036d6/15)
