### ISSUE TITLE
Checked off habits, didn't get the corresponding gold + exp

### ISSUE THREAD

**Issue by KikoSantos** [HabitRPG/habitica#3050]
I checked off a few dailies in my list (one of which I used "Backstab" on) but I didn't get the corresponding gold or exp reward from it. I only noticed it because I had enough exp to level up, but didn't. How do I fix this issue?

**Comment by zoebeagle** [comment]
This might be related to #3048.

**Comment by Alys** [comment]
I'm closing this since it's old and recent site changes have probably fixed the problem, but @KikoSantos tell us if this still happens and we will reopen it and investigate.
