### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by opus72** [HabitRPG/habitica#3052]
This is all I've been seeing when I open HabitRPG for the past two days; I am unable to select anything. Mostly I'm just wondering if other people have experienced this issue.

I've been using HabitRPG on one computer only, with Firefox.

![what](https://f.cloud.github.com/assets/6923467/2391068/6152fc90-a962-11e3-8bb3-db94e8facd31.jpg)

**Comment by lefnire** [comment]
What [javascript errors](https://developers.google.com/chrome-developer-tools/docs/console#opening_the_console) are you seeing?

**Comment by wc8** [comment]
@opus72 I think Firefox > Tools menu > Web Developer > Browser Console or Web Console will open a similar tool to Chrome's for displaying errors.
