### ISSUE TITLE
When feeding/saddling, ineligible pets should not get the green bubble

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3054]
Pets for whom you already have the corresponding Mount don't display the progress bar for feeding, but once you select a food or Saddle, they still light up with a big green highlight as if they're a legal target. The green target-indicator style shouldn't get applied to pets that will give you an error if you click them.

**Comment by rcichy** [comment]
I added a pull request for this issue - https://github.com/HabitRPG/habitrpg/pull/3507

**Comment by SabreCat** [comment]
Nice! It might be worth adding a special case for the egg pets, though, to further reduce the "Egg mount" bug confusion--they shouldn't get highlights either.

**Comment by deilann** [comment]
@SabreCat Possibly that should be bundled in with logic removing them from
the mounts page?

**Comment by SabreCat** [comment]
@deilann: Depends on how the logic's set up. It might be easier to fix the highlight as a partial measure, or it might be easier to address both at once.

**Comment by deilann** [comment]
I'm thinking if both are addressed at once, it would make it easier to
handle the issue in the future and a lot cleaner. So if we have more pets
without mounts, we don't have to compensate for them, too.

Giving pets a hasMount might work best. So if hasMount and check if user
has the mount.
