### ISSUE TITLE
Fix iOS Avatar

### ISSUE THREAD

**Issue by stsmuniz** [HabitRPG/habitica#3055]
Dear HabitRPG iOS app developers.

You need to review the avatar on HabitRPG app, because it's showing anything but the user's avatar.

Below are some screenshots of the app. It shows a series of sprites instead of my avatar.

![img_0940](https://f.cloud.github.com/assets/2389863/2393172/26b3fa9e-a98a-11e3-926d-ce0e39384432.PNG)
![img_0939](https://f.cloud.github.com/assets/2389863/2393173/26b50ff6-a98a-11e3-827f-dd1cc032f636.PNG)
![img_0938](https://f.cloud.github.com/assets/2389863/2393174/26bb2b34-a98a-11e3-9dcd-88ca9fc96f54.PNG)

Thanks in advance for receiving it and I wish it's resolved soon.

**Comment by wc8** [comment]
This seems to be a variant of #3030

**Comment by stsmuniz** [comment]
@wc8 is right. Closing for duplicated with #3030
