### ISSUE TITLE
Inexplicable death mid-day while using mobile app

### ISSUE THREAD

**Issue by Reesachan** [HabitRPG/habitica#3056]
My ID is 4c076644-3805-45e4-98e5-686f43d3d541

An hour ago, I was at 49 out of 50 health. I was somewhere between a third and halfway through level 59, I've had a perfect day, and I had a bit over 1500 gold. I have no clue which piece of equipment I had at that point and no longer have. 

Fifteen minutes ago, I opened up the mobile app to enter an item on my to do list and immediately afterward it informed me that I'd died. I'm in the middle of a quest, so I went and checked my party to see whether someone there had been incredibly lax and if that had caused my death, but there's no new activity there.

I didn't find anything else in the current list of issues that sounded quite like this - all of them seemed to start a new day dead, for instance, rather than a random reset mid-day - so I thought it better to open a new thread.

**Comment by Ratcoon2** [comment]
To better assist with this one, can you also provide the following to help others with isolating this bug:

OS and Mobile App used:  Was it the official App for iOS/Android or one of them other 3rd party ones (could be a API issue)
Based on the information you provided it sounds like there issue may be related to the to do item, as you stated you marked an item complete and noticed the death.  Do you recall the settings for that to do item and if any status indicators listed at the time of death (-2000 health for example)

[Not currently a coder, just trying to help narrow down where the issue may have occurred]

**Comment by Reesachan** [comment]
Thanks for helping me come up with good information to add!

I have an Android phone, and I believe I'm using the official app.

I was adding a new item to the to do list, not marking something
complete, and I didn't do anything special to it, I just typed in the
task and hit enter.

**Comment by deilann** [comment]
I'm going to guess adding the new item triggered a sync, and for some
reason, the server thought to kill you. I think this is the same issue --
was this the first time you'd used the app that day?

**Comment by Reesachan** [comment]
No, I'd been using it off and on all day. I believe I'd been using the
computer to access the site an hour earlier, though, and that this was
the first time using the app since then if that makes a difference.

**Comment by deilann** [comment]
That certainly does make it unique. I was thinking if it was the first time
you'd used it since cron, it might not have recognized you'd checked off
your dailies and then reapplied cron, killing you. But that seems not to be
the case here, if you'd used the app on and off all day.

Just want to make sure you know you can go to Site > Settings > Fix
Character Values (on the web app) to restore your gold (and gold for lost
equipment) and XP.

**Comment by Reesachan** [comment]
Okay, correction, I have a third party client - the one by MagicMickey,

Side note: When I went looking for the HabitRPG app through the Google
Play store, it was impossible to tell which one was the official one,
and even now the only way I was able to figure it out was to find a
link through the HabitRPG blog to take me there. It might not be a bad
idea to throw a note up on the app page saying that that one's the
official one.

**Comment by Reesachan** [comment]
Also, the official one is apparently incompatible with my Motorola
XT557 in case that makes a difference regarding what's going on.

**Comment by deilann** [comment]
@lefnire I agree with @Reesachan -- marking the "official" app is probably a good idea, so people can tell the difference.

It's really hard for us to troubleshoot third party issues (none of the devs here worked on that code) -- is there any way you could bring up the issue with the developer of the app and report back to us/keep in touch so we can know what's going on?

**Comment by Reesachan** [comment]
I'm looking into that as we speak :-)

**Comment by deilann** [comment]
Awesome-- thanks. I'm going to keep this open, even though I'm pretty sure it's a third-party problem. But it might give us some insight into other things.

**Comment by MagicMicky** [comment]
Hi there ! I'm the developer of the third party application!

I was currently investigating the issue (thanks @Reesachan for your mail), and was looking into what I was doing and what were the problem.

My application hasn't been modified for quite a long time, and may not be up to date with the latest API changes. My guess would be that I might have had the death popup shown where the user wasn't dead, and the user clicking "revive" lead to an API call on /user/revive. I would believe that there is some protection around /user/revive where I can't revive a user that isn't dead. Is there such security?

About which app is the "official" one, I'm really sorry. My application has been out there for a long time (even before you guys had finished yours), and I don't know why I never put an unofficial tag there. I will do so immediately. :)

Edit : Could it be linked to #2601 ? @Reesachan did you see some kind of error just before dying? Anything like a red bar on the top saying an error happened?

**Comment by planetaryalien** [comment]
I thought I might tag my bug onto this one because it's very similar. With or without a mobile app (magicmickey's) me and my party (two others in it) keep dying at random. We take critical health hits out of nowhere. There are no neglected tasks for any of us, no damage taken form boss (we are on quest though) and we keep losing a level, all the acquired gold and sometimes piece of equipments. So actual complete deaths but completely uncalled for. We are not taking that much damage in boss fights, and as said, we keep up with our dailies/tasks and shouldn't be getting more than a few HP down.

Anyone has any idea what is causing this, it's happened a few times now and is a bit discouraging.

User ID: 568445a8-ce63-430a-88d1-b8950f91cf0b

**Comment by planetaryalien** [comment]
For clarity's sake: I occasionally use the mobile app but haven't with the last death occurred. Party members both don't use a mobile app at all.

**Comment by deilann** [comment]
planetaryalien, are you losing any of your streaks when this happens? Also,
is this happening during the middle of the day, or when you log in after
cron?

**Comment by planetaryalien** [comment]
Nope, don't lost any streaks...
First death was upon first sign in of a new day, but this latest one was in the middle of the day when I'd already been on to check off tasks earlier in the day.

**Comment by deilann** [comment]
Can you do me a favor and refresh the party page, just to make sure the
boss isn't dealing you damage? I believe you, but I know I've misread the
party page due to not refreshing.

**Comment by planetaryalien** [comment]
Oh god. You're right. Massive refresh fail, it only popped up after I deleted my cookies and refreshed. So sorry for taking up your time! ;__;

**Comment by deilann** [comment]
Don't worry about it. :) I'm glad we all found out what it was.

**Comment by MagicMicky** [comment]
Hi there. I'm commenting around here, because I found something interesting.

It seems that I'm able to call the `/user/revive` API, even if the user isn't dead. The expected implementation would be either a message saying you can't, or at least not doing anything. Right now it seems to reset user's gold, set his life to 50 and removing an item from his inventory.
Is this the wanted implementation ?
cc @lefnire & others.

Cheers,

**Comment by lefnire** [comment]
Not desired implementation, good catch

**Comment by MagicMicky** [comment]
I'm not sure, but I guess it could be the origin of issues like this. Do you want me to open a new issue about it?

**Comment by lefnire** [comment]
Sure, that would be good!

**Comment by Alys** [comment]
I'm closing this because planetaryalien's issue was solved, MagicMicky logged a new issue for the revive problem, and we don't have any responses for the questions MagicMicky asked of Reesachan. @Reesachan, we can open this if it's still happening for you.
