### ISSUE TITLE
Dailies doesn't work

### ISSUE THREAD

**Issue by Dinanachka** [HabitRPG/habitica#3057]
Hi
Repeat Dailies every day doesn't work 

I looked 
https://github.com/HabitRPG/habitrpg/issues/937
https://github.com/HabitRPG/habitrpg/issues/3032

I dont understand. Please could you show a screen with the correct settings
Thks

**Comment by Dinanachka** [comment]
Help me please

**Comment by deilann** [comment]
I honestly don't understand what you need help with.

Can you provide more information about what you need? What you're doing? What's not working? What the expected result is?

Dailies repeat every day by default. You can deselect days on your own created tasks (not challenges) so that they aren't required that day.

**Comment by Dinanachka** [comment]
![2014-03-14 00-27-13](https://f.cloud.github.com/assets/6927800/2415032/a9b5b68c-aaf0-11e3-80ba-07489d6b6de5.png)

These gray stripes I see every day in Dailies. But before, they are updated after a night, so that I could celebrate it

**Comment by deilann** [comment]
Are you saying that your dailies are always grey?

If they're grey, it means that you've either checked them off, or they're
disabled for that day. Are they grey regardless of whether or not they're
checked off? If so, that means they're disabled. Open the daily up and turn
on the days you'd like the daily to repeat. They're turned off on the days
they show up grey.

If they're always checked off and grey, that means your cron isn't
happening, which is another bug. Search "Dailies not resetting" to find the
ticket (in email at the moment, don't have it handy).
