### ISSUE TITLE
All right, so this might be a bit of a silly suggestion, but: pink hair?

### ISSUE THREAD

**Issue by ld89** [HabitRPG/habitica#3058]
I was pretty disappointed to see there was no pink mixed in with the rainbow colors! ...I don't suppose there's any future plans for it? That's something I'd definitely buy gems for.

**Comment by LB7979** [comment]
Pink hair would be a great option, I'm backing this!

**Comment by deilann** [comment]
I highly suggest heading over to the [Pixel Trello](https://trello.com/b/vwuE9fbO/habitrpg-pixel-art) with this suggestion. That's where all the art is done. Most of the people who hang out here are coders, and so wouldn't be able to help you. ;)
