### ISSUE TITLE
Cant Log in

### ISSUE THREAD

**Issue by Mangageek94** [HabitRPG/habitica#3059]
Went to go Log in through FB and there wasn't an option for it. Forced me to create a new account. My old User ID was 
3b8be8a4-5952-4416-8f74-f1170fe170af
And my new User ID is
30c9bbf9-17c5-4ce6-8b52-645613cb9800

=/ Really bummed I couldn't log back in through FB.

**Comment by zoebeagle** [comment]
Did you get any errors or anything?

**Comment by Mangageek94** [comment]
No. Besides the User ID not found/password incorrect for entering my ID.

**Comment by deilann** [comment]
...oh, you're talking mobile app, not the site?

**Comment by Mangageek94** [comment]
No. Site. Went to log in through the site this morning, wouldnt let me.

**Comment by Mangageek94** [comment]
Tried mobile, same results

**Comment by deilann** [comment]
Wait, are you trying to log into the site itself with your User ID? Or are
you using your user name?

**Comment by deilann** [comment]
If you want to log in with your FB-based account, you need to click the FB
"Login/Register" button above the login form. Have you tried that?

**Comment by Mangageek94** [comment]
Im saying the FB-based account button was not there. Therefore I could not log in that way. Trying with user name, ID, eveything I could think to try on my end.

**Comment by deilann** [comment]
Is FB blocked on this computer? The FB button is displaying for me.

You said you're on Chrome, yeah? Can you open up the console and tell me if
there are any errors?

**Comment by Mangageek94** [comment]
Aha! My Ad blocker was blocking the button as an add. Disabled it and it popped up. :) I am on Chrome. Was using Ad Blocker Plus.

**Comment by deilann** [comment]
Glad to know we've got that cleared up! :)
