### ISSUE TITLE
Numbered tasks

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#306]
Some task have different value depending of a certain number: take stairs 2 floor (my work) is not the same than 14 floors (my apartment). So, add an option to have a number as a complement to the organic value would be nice.

Some examples where Numbered tasks (needs a better name):
- N kms running
- N minutes walking
- N pushups
- N situps

The rule of XP gained can be based on the media for each task, so if one day i walk for 60 minutes, and tomorrow i walk 30, im just gained 0.5*XP

**Comment by wc8** [comment]
Considering the examples given, is this a suggestion for an enhancement of habits and/or daily tasks?
(For example, something similar to https://github.com/lefnire/habitrpg/issues/142#issuecomment-12519651) 
Or for a new kind of task as the #195 skill-item proposal is?

**Comment by racuna** [comment]
None of those. Is not about how many times I do something nor learning some skill.

I'm thinking in the effort to walk upstairs 2 floors is not the same than walk upstairs 14 floors. So, based in a formula maybe would be nice earn more points for the additional effort.

Im thinking in two ways to think in this kind of tasks:

I create a new numbered daily task: N pushups
- Based on max.
  If everyday i do 10 pushups, and someday i can do 30, that is my new max. So, next time i have to do 30 to earn the total points. If, I do 10 again (or less than 30), I have to gain a fraction of the total points. 
- Based on media. (less harder than max)
  if i do 10 pushups for 5 days. My media is 10 pushups. But if the 6th day i do 30 pushups, my new media is 13. So, if i want to gain the total points on 7th day, I need to do at least 13 pushups.

**Comment by Pandoro** [comment]
I get your idea, but I think there is also more pressing stuff at hand right now. :x 
For similar behaviour, I simply click the plus button more often on a habit if I really want this. You could keep track of your goal in the note field. Of course this is not the same, but at least you can achieve this suggestion like that and I guess at some point this sounds pretty realistic.

**Comment by horusofoz** [comment]
@Racuna I keep "Bonus Productivity" and "Bonus Exercise" habits available to provide the productivty you're looking for. Whenever I exceed my prescribed reps or do a job not on my list, I give myself a + on the relevant habit.

This helps you keep everything neat. Only problem is it will make you want to do Bones work every day to get it green/blue :)

Would this workaround suffice?

**Comment by Pandoro** [comment]
I certainly don't want to forget about this one though. It's just that the
trello board is piling up so much stuff. If we keep adding everything, I
think it soon looses it's value and we will start to make a trello board
for the selected ideas from the trello board, which were selected on here
:x

If there are more people interested though, we can add it I guess.

**Comment by StanLindsey** [comment]
We need to start consolidating the trello cards together, e.g. one which has all the organising/tagiging/numbered things. One for data display that has everything pertaining to graphs etc.

**Comment by wc8** [comment]
The difficulty is voting. Perhaps there would be a way of grouping cards together by topic instead of by vote, since you can still see the number of votes? Or perhaps a few more lists? 
If something's not ready to be voted on but relates to a card already on trello, it could work to list it as a checklist item. Later it can be converted to a card.

**Comment by horusofoz** [comment]
How about we preen Trello a bit? If a card has received no votes after a month or whatever specified time we archive it. If someone else requests the feature we restore the car, direct the user to it and give them the opportunity to vote for it. Won't make a big dent but will reduce to active requests and probably a good practice going forward.

**Comment by horusofoz** [comment]
Closing ticket as no response from user after 17 days.
