### ISSUE TITLE
phantomjs install fails on Ubuntu 13.10

### ISSUE THREAD

**Issue by iartarisi** [HabitRPG/habitica#3060]
Doing 'npm install' from the README instructions fails with this error on Ubuntu:

```
> phantomjs@1.9.7-1 install /home/mapleoin/habitrpg/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! phantomjs@1.9.7-1 install: `node install.js`
npm ERR! `sh "-c" "node install.js"` failed with 127
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-1 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
```

Installing the `nodejs-legacy` package fixes it. It might be useful to mention this in the README. I almost abandoned it.

**Comment by thepeopleseason** [comment]
Did you install npm via chris lea's repo or from bare ubuntu? 

`apt-get update`
`apt-get install python-software-properties`
`apt-add-repository ppa:chris-lea/node.js`
`apt-get update`
`apt-get install nodejs`

You can also bypass installing npm if you use the Vagrant VM. Check VAGRANT.md for more details.

**Comment by negue** [comment]
@mapleoin, npm install still not working for you?

**Comment by iartarisi** [comment]
@negue Haven't tried this since then and I don't feel like installing nodejs now. This was caused by the `node` command being hardcoded in the install. The binary is called `nodejs` on Ubuntu/Debian (but there is a `nodejs-legacy` which provides a symlink). So if that's fixed now in the install scripts, it should work.

**Comment by Alys** [comment]
If you do try again in future and have problems, look at the vagrant.sh file in the root directory of the habitrpg repository, even if you don't want to use the Vagrant VM. That's what the VM uses to set up the environment, and it uses Ubuntu so the same apt-get install commands should help your system.

We'll close this now but you're welcome to re-open it if you ever need more assistance, or post questions in the Aspiring Coders guild.
