### ISSUE TITLE
npm install fails because of bad peerDependency requirements in karma-requirejs

### ISSUE THREAD

**Issue by iartarisi** [HabitRPG/habitica#3061]
I get this at the end of `npm install`. I don't know what to do about it.

```
> habitrpg@0.0.0-152 postinstall /home/mapleoin/habitrpg
> ./node_modules/bower/bin/bower install -f

npm ERR! peerinvalid The package karma-requirejs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma@0.10.10 wants karma-requirejs@~0.2.0

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/mapleoin/habitrpg
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.2.18
npm ERR! code EPEERINVALID
```

**Comment by JoeBot0101** [comment]
in your project.json, find the reference to karma-requirejs and update it to this:
"karma-requirejs": "~0.2.0",

then re-run 'npm install'

**Comment by iartarisi** [comment]
Thanks! That worked. For future reference, the file is `package.json`, not `project.json`.

**Comment by JoeBot0101** [comment]
haha, oops, sorry about that.

**Comment by lefnire** [comment]
btw this is fixed (per above commit). I was hitting it too, even after fix - you have to `rm -rf node_modules/karma-requirejs && npm install` if you have old version downloaded.

**Comment by adrianenriquez** [comment]
Thanks @mapleoin !

**Comment by SabreCat** [comment]
Oh! Yay! I was having trouble with this the other night. Maybe now I can get local Habit running on my new computer at last...
