### ISSUE TITLE
Accidentally left my own guild

### ISSUE THREAD

**Issue by Otocinclus** [HabitRPG/habitica#3063]
I was trying to leave a different guild and it seemed that the screen blinked and it didn't work, so I tried again... turns out it refreshed with my own guild and trying again made it so I unjoined a guild I literally JUST made (and the guild I originally was trying to leave, which was adjacent to mine in my guild toolbar). 
The guild was private and so new that I had JUST invited one friend to join a minute ago (who hadn't accepted yet) and I didn't even take note of the guild number. How can I get back in, and should it be a little more difficult to leave a guild you've made and paid 4 gems for, like a different popup that says "You are the guild founder, are you sure you want to leave?"
For now, seeing if invited friend can still join and reinvite me, but I'm pretty cheesed at myself. I didn't know I had to be careful about that, but from now on I will be. :( whoops.

**Comment by Otocinclus** [comment]
Update: Friend managed to join but cannot reinvite me because I am still a member, even though I do not see the guild in my guild lineup. She posted a chat note and I was able to follow the chat alert to the group, see I was still a member, edit the guild, set myself as leader, etc, but when I left the guild page and tried to find it in the guild's tab, it is still not there and now I can't go back unless she posts another chat response. Let me know what other information you might need to sort this one out, we can try to replicate or something. Going to try and use the guild's code, when I can see it again, to invite myself? Or I'll post it here so I can be manually reset as a member.

**Comment by Otocinclus** [comment]
Workaround: using the chat alert shortcut into the guild, edited the guild leadership to friend, who used it to boot me and then reinvite me. Now the guild is working properly again (although another guild I left is now also showing up on my guild list.) So that's how that can get worked out. 
For reference, the group ID of the private group I was trying to get back into is: c5bb08eb-f3b1-4a47-95de-9a5f2efa79fc

**Comment by deilann** [comment]
Any thoughts on if this could be related? https://github.com/HabitRPG/habitrpg/issues/1916

**Comment by Alys** [comment]
Sounds like a once-off problem and I don't recall any other reports so I'm closing this.
