### ISSUE TITLE
Has Habitica Fallen?

### ISSUE THREAD

**Issue by Gaelan** [HabitRPG/habitica#3065]
Habit looks down.
![screen shot 2014-03-13 at 6 58 27 am](https://f.cloud.github.com/assets/4495750/2409939/97d6ca52-aab7-11e3-913b-5524292130c8.png)

**Comment by Gaelan** [comment]
It's being quite flaky: once I managed to load the page, but when I checked a daily it showed an error.

**Comment by deilann** [comment]
Give it a few minutes. Looks like the server's unhappy.

**Comment by deilann** [comment]
(I'm impatient myself-- I have things I can check off!!! But waiting's the best course at the moment.)

**Comment by Gaelan** [comment]
OK.

**Comment by deilann** [comment]
Site's occasionally fully loading for me and I've had success checking off checklists, but not full tasks. If this lasts a significant period and @lefnire hasn't shown up to save the day, I'll call him.

**Comment by paglias** [comment]
I'll check on New Relic when I get home (30m). In the meantime it isn't a
heroku problem, at least it's not reported on their status page. What about
beta?
Il 13/mar/2014 15:15 "deilann" notifications@github.com ha scritto:

**Comment by deilann** [comment]
@paglias I'm having trouble loading beta as well. Site is acting very much the same as when we were having scads of 503s all over the place.

**Comment by deilann** [comment]
My last two checked off tasks have stuck, but the site is still taking longer than usual to load.

**Comment by casicastiel** [comment]
I got one 503 in the middle of reading the Tavern backlog a few minutes ago, but otherwise the main site's been working perfectly fine for me. The habit, checklist item and dailies I've checked off in the past 30 minutes have all stuck.

**Comment by deilann** [comment]
Site's back to fully functional for me as well. Load times are normal.

**Comment by paglias** [comment]
Ok it looks like there's been a downtime of about 45 minutes lasted up to 45 minutes ago. But now everything is ok.

**Comment by deilann** [comment]
Is that a typo (now vs not) or is not everything okay?

**Comment by paglias** [comment]
A typo... edited

**Comment by deilann** [comment]
Glad to hear it! The typoed version certainly seemed ominous!

**Comment by lefnire** [comment]
Yeah, NewRelic has been showing _quite_ the downtime spells throughout the night and this morning. There weren't any errors out of the ordinary during that time. My only guess is memory-maxing due to a surge of traffic. We did seem to have more users than usual this morning (there was another lifehacker thing), but nothing nuts.  

Here's my proposed (deployed) solution. Bring max cores back to 1 (https://github.com/HabitRPG/habitrpg/commit/3f5221755c21ea7dfbc0278218560463300eacc1). Used to be we allowed all cores to engage (4 on heroku), which was maxing memory because each cluster instance spins a new server on the same box per core, ~400mb/server. So we scaled it down to 2, which avg'd 800mb / 1GB-allowed. Commit above goes back to 1 core, which is now avg-ing 450mb. The downside? We can only use one core, which:
1. Gives us lower throughput (RPM)
2. _May_ cause funkyness when an instance crashes and needs to restart via domain-middleware. This is the biggy. I'm gonna keep a keen eye out today, if anything starts acting up and ping back here and I'll jump on it soon as I can.

**Comment by deilann** [comment]
I'd lean towards traffic as well-- we've got over 300 people on the site at
the moment. Honestly not sure this can be blamed on lifehacker; I think the
site is just getting a touch too popular. ;)

**Comment by lefnire** [comment]
And by blaming, I mean all the love I can muster towards that wonderful site! Traffic-surges, a good problem to have. 

Grr... still present. I have no idea what's happening... we're not maxing memory, we're not seeing server errors. Our RPM has increased from ~600 to ~800, but that doesn't say DDoS to me - and according to newrelic, we're crunching it ok. We're getting "Request timeout" every few seconds. `at=error code=H12 desc="Request timeout" method=POST path=/api/v2/user/batch-update?_v=23&data=1394730718138&siteVersion=1 host=habitrpg.com request_id=f98eb67b-ee28-42f4-a39b-0070883808ad fwd="..." dyno=web.2 connect=14ms service=30000ms status=503 bytes=0`. Continuing to dig...

**Comment by paglias** [comment]
@lefnire the database is up? also we're getting it only with batch-update, all the api, or even with the entire site?

**Comment by paglias** [comment]
entire site -> static pages without database calls

**Comment by lefnire** [comment]
@paglias database is up. It's intermittent, most requests go through fine but maybe 20% hit this ([screenshot](https://www.evernote.com/shard/s17/sh/568cc529-8fed-4c63-897e-c5685201ec08/b9448816812efc066c909067c08fe627)). It's for everything - i'm seeing it for assets and more, though batch-update is the most common

Well... we seem to be ok now. I reverted the 1-core commit, it has merit and the domain-middleware restart bit checked out fine, but it appears we need that extra core so as not to lock up the processes (possibly the cause of the timeouts?). I'll experiment with this some and return to this in the future. In the mean time, the downtimes do indeed seem to be correlated with RPM - as in we were getting many more requests over a chunk of time. Not more web users (per analytics), so it could be API usage. I thought of DDoS and/or awry API scripts; however, the RPM wasn't exorbitant, and we have API over-use protection. Next time this happens I'll just up our Dynos and see if that helps

**Comment by ghost** [comment]
I'm still getting the issue.

**Comment by casicastiel** [comment]
Same here, as of now.

**Comment by busterroni** [comment]
Same.

**Comment by SabreCat** [comment]
habitrpg.com throws the screenshotted application error from the top post. Attempting beta gives me an untrusted connection warning about the HTTPS, which is not normal...

"beta.habitrpg.com uses an invalid security certificate. The certificate expired on 3/13/2014 6:59 PM. The current time is 3/13/2014 7:10 PM. (Error code: sec_error_expired_certificate)"

Might be benign?

**Comment by martenson** [comment]
This is still happening. Site either loads incompletely (picture) for me or I got the error above. 
![screenshot 2014-03-13 22 09 55](https://f.cloud.github.com/assets/1814954/2417368/cb6a6386-ab1d-11e3-8fc0-868773c0cb12.png)

**Comment by Mihakuu** [comment]
Yesterday iPhone mobile web was completely unusable for me. Nothing loaded or quickly errored out. But I didn't see this problem with loving in on the actual site

**Comment by Mihakuu** [comment]
Logging*

**Comment by lefnire** [comment]
One thing I'm gonna look into when I'm back: it seems restarting the server fixes it for a time. Could it be a newer version of Node 10.x broke domains, such that it's not restarting instances on crash? Will check soon

**Comment by thepeopleseason** [comment]
Looks like Habitica is under siege again. https://status.heroku.com/ shows no known issues with the service in general.
