### ISSUE TITLE
Repeated pop-ups about chrome

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3066]
yesterday and today, I'd frequently click a task, and get a pop-up that basically said the app. wasn't working, with reference to chrome or the chrome console. It disappears pretty fast, and I've failed to get a screenshot. 

I am running firefox on Ubuntu, not chrome. 

Yesterday, when I then hit reload, it would claim to be deducting xp etc. Sometimes it would do this in spite of not having unchecked whatever daily I was trying to check off when the pop-up occurred; sometimes I couldn't see any sign of rollback/lost update, just claimed xp loss. 

Today I get an "application error" (attached) when I try to reload. When I tried again (as suggested) after writing this bug report, the screen loaded normally. 

Did you folks fix something that wasn't previously broken? Or is this too much success leading to overloaded servers?

![screenshot from 2014-03-13 08 53 44](https://f.cloud.github.com/assets/4530463/2411482/dda44522-aac7-11e3-8dd4-8b5f3fd70a1f.png)

**Comment by deilann** [comment]
See #3065 -- might need to reopen that one, as I'm starting to get errors again.
