### ISSUE TITLE
Tomato.es Linkage

### ISSUE THREAD

**Issue by LordVinnietheFinisher** [HabitRPG/habitica#3068]
After downloading the HabitRPG extension to track web browsing I noticed that the first recorded tomatoes worked fine but once I received a long break for completing my forth tomato, I was continuing to lose health because I was "overbreaking" even though my timer still had time.

**Comment by LordVinnietheFinisher** [comment]
In fact I ended up dying in the process :(

**Comment by deilann** [comment]
I... am not positive the HabitRPG Chrome Extension is still supported. Is that the one you're talking about?

**Comment by LordVinnietheFinisher** [comment]
Well it works to a certain degree.  It syncs with the 25 min blocks of time
but once it goes to the longer break I get penalized.  The extension has
work fine with checking sites but I just wanted the longer break to be
recognized.

**Comment by LordVinnietheFinisher** [comment]
Yea its the chrome extension.

**Comment by deilann** [comment]
Sorry -- "not supported" doesn't mean "doesn't work."

Not supported means that it is no longer being updated and tested-- so it
might work or it might not or it might do unpredictable things. Looking at
the GH Repo, Tyler hasn't changed it in 4 months. Tomatoes was updated
within the last month.

@lefnire Is the Chrome extension still being worked on? I see no sign of it
being abandoned in the GH readme, but I could have sworn I've heard that.

**Comment by crookedneighbor** [comment]
The HabitRPG chrome extension is no longer maintained. Closing this issue.
