### ISSUE TITLE
Minor bug: In challenges area, Join button has a yellow background

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#3069]
In the challenges area, the yellow background for the text works fine, however the 'Join' button also has a yellow background, which I don't think is intended and looks a bit awkward. Using Chrome version 33.0.1750.149.
![screen shot 2014-03-13 at 7 10 47 pm](https://f.cloud.github.com/assets/3424032/2416434/196d6592-ab05-11e3-97ec-80f1a576f43e.png)

**Comment by tomwalker** [comment]
Simple fix that would remove the yellow
