### ISSUE TITLE
default task due days

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#307]
are disabled visually, but still dock points on cron

**Comment by Pandoro** [comment]
As a little further info, this can be fixed, by actually enabling them once visually and then turning them off again, if you want to turn them off. Or just deleting them and recreating them of course ;)

**Comment by horusofoz** [comment]
@lefnire Triage difficulty. Assign.

**Comment by horusofoz** [comment]
@lefnire Is this still an issue?

**Comment by lefnire** [comment]
fixed :)
