### ISSUE TITLE
completed tasks back in to-dos, level + xp reset to what it was earlier today

### ISSUE THREAD

**Issue by clockadile** [HabitRPG/habitica#3073]
I completed a few things at once, and checked off some habits and tasks. One was a two part check listed task set to medium (hanging pictures), though I changed it to hard right before completing it.

Upon checking it I got a bonus crit and levelled up to lvl 11. I completed a few more small tasks, getting a bear egg for one of them. I bought a new shield then a little later I added one more to do, and checked it off.

I checked back in later this evening while at a friend's house (still on my laptop, not the app) and the picture hanging task was back on my to-do list, I'd lost my level, and my shield. I still have the bear cub egg. Did not regain the gold. The second to-do has not re-appeared.

**Comment by deilann** [comment]
See #3065 

So, the server issues mean that you check off a task, but it doesn't save to the server. So if you refresh/switch computers, it'll revert all changes that didn't save.

I'm going to guess the second to-do actually got saved to the server, as well as the bear egg.

**Comment by clockadile** [comment]
Thank you very much! I'll just check things off again and continue on then.

**Comment by deilann** [comment]
np :)
