### ISSUE TITLE
Experience overload

### ISSUE THREAD

**Issue by DimTwin** [HabitRPG/habitica#3074]
This is not an ocasional bug. I encounter it regulary.
When I use the Backstab skill, the exp from it adds to my current exp. Thats ok. But when I reach the amount of exp needet to lvl up, the lvl up just doesn't happen and the exp keeps adding up. 
Here, take a look:
![1](https://f.cloud.github.com/assets/6949144/2419030/ad324d66-ab54-11e3-8a52-e75fd97f2d5d.png)

As you can see, I have 1402 exp out of 1200 need to lvl up.
Its not so bad though. It gets easily fixed by doing regular habits/dailies/to-dos.

Here is what happens when I do a habit right after the exp overload caused by the Backstab:
![2](https://f.cloud.github.com/assets/6949144/2419043/17c148b2-ab55-11e3-81f6-097cd1f40cb8.png)

My ID: 91ab86a8-6fb0-4be4-8eeb-7f6b96aef698

**Comment by deilann** [comment]
This is known: https://github.com/HabitRPG/habitrpg/issues/2143

Skills don't tell the server to level up. Like you've experienced, doing a habit/daily/to-do will fix it. You don't lose any XP; fear not.
