### ISSUE TITLE
Scroll buying is a bit glitchy

### ISSUE THREAD

**Issue by LoicBrassart** [HabitRPG/habitica#3075]
Hello,
I trid this evening to buy a Hedgehog Quest Scroll, but just lost 4 gems in the process.
I currently have 1 Scroll in my inventory screen, and it matches reality (Vice scroll, saved for later use). So it doesn't seem like it would be #2592.
I didn't try to buy another one, because maybe this case could help you solve the glitch.

I'd like to solve this asap please. Be it by getting my gems back or by getting a Hedgehog Quest Scroll, I don't mind...
My ID is : 917eae07-7ccc-4b2c-88d2-5a904366997e

... As a side note, I love this app, please keep up the good work ;-)

**Comment by deilann** [comment]
I think it is most likely #2592 -- but when you bought the scroll you "fixed" the number of scrolls you have. I'll refund you 4 gems in a second.

**Comment by LoicBrassart** [comment]
Thank you for your reply !
