### ISSUE TITLE
EDIT: Inventory not missing

### ISSUE THREAD

**Issue by rachelsstorm** [HabitRPG/habitica#3078]
I can't find a way to delete this, so: please ignore/close. I'm embarrassingly mistaken about the issue I originally posted.

**Comment by deilann** [comment]
Oh, in the future @rachelsstorm instead of editing can you post again? I've been puzzling about this in my inbox and edits don't get emailed to me-- only ticket updates. Glad to hear the issue is resolved. You can't delete, but you can close issues. The close button is at the bottom.
