### ISSUE TITLE
Option to "Automatically start each day at the Inn"

### ISSUE THREAD

**Issue by digital-carver** [HabitRPG/habitica#3080]
I do not have a fixed schedule or a consistent ability to connect to the Internet, which means that oftentimes I'm unable to check off the dailies even if I've completed the tasks themselves. If this happens often enough, it's definitely going to (and has started to) affect the appeal of the RPG idea itself to me. 

My idea is that the avatar starts every day at the Inn, protected from the dailies, until I check out to enable to dailies. Obviously this wouldn't be everyone's cup of tea, so it would only be an option and by default disabled. But once enabled, it can be the "do I have Internet access today" check for those of us who need one.

**Comment by deilann** [comment]
I think what you actually want is manual cron, not automatically starting out in the inn. Checking out of the inn isn't going to run cron until your CDS again, which may or may not be at the time you need.

_I_ would kill for manual cron, not because of internet, but because I don't keep a 24-hour schedule.

**Comment by caveman1337** [comment]
I'm going to also vouch for this. Ability to get a chance to go on HabitRPG every day is often very unpredictable and the modified cron time is still buggy. A default inn option would really help out.

**Comment by crookedneighbor** [comment]
We've rewritten the inn code to allow dailies to reset (from checked to unchecked) while resting in the inn. This should allow you to avoid damage from the inn, but still be able to use your dailies.

**Comment by digital-carver** [comment]
Just to be clear, this seems to be a very different thing from what the issue originally asks for. 

The feature requested was that at the beginning of any day, the user is put in the Inn automatically. Other than this, the game elements would remain exactly the same, and the user would be able to participate in all aspects of it, including taking damage and dying. The only thing prevented would be the useless deaths that happen just because the user could not login at all on a given day. 

The recent change mentioned seems to be to allow playing a crippled version of the game while continuously having to remain within the Inn. If one wants to use this feature to solve the originally stated problem, one will have to remain forever in the Inn, taking no damage ever, just to make sure an unexpected offline day doesn't kill your character. So, basically, you'll have to lose the chief distinction between a 'Daily' and a 'Habit': penalties in terms of damage. Everything becomes a 'Habit', which kills most of the 'game' appeal to me.

**Comment by Alys** [comment]
We are currently planning a feature very similar to what you describe.
