### ISSUE TITLE
got over 20 gold when opening account

### ISSUE THREAD

**Issue by Joshyar** [HabitRPG/habitica#3081]

**Comment by deilann** [comment]
Hey @Joshyar can we get a bit more information? I don't know what you mean by "opening" account-- do you mean signing up? Logging in? Refreshing the page?

Do you use the mobile app? Official or third party? Do you only use the web app?

**Comment by Joshyar** [comment]
It was when I logged in. When I pulled up my account, it said I got 21 gold. It was on the official site and I was using a desktop. 

On Sunday, March 16, 2014 5:46 AM, deilann notifications@github.com wrote:

Hey @Joshyar can we get a bit more information? I don't know what you mean by "opening" account-- do you mean signing up? Logging in? Refreshing the page?
Do you use the mobile app? Official or third party? Do you only use the web app?

**Comment by deilann** [comment]
That just means that was gold you'd accrued between log ins that hadn't hit local. When I switch computers, it happens all the time. No need to worry!
