### ISSUE TITLE
Wish we could have a live chat within parties

### ISSUE THREAD

**Issue by reesarose** [HabitRPG/habitica#3084]

**Comment by deilann** [comment]
Hey, reesarose-- if you want to make feature suggestions, please go to [Trello](https://trello.com/b/EpoYEYod/habitrpg). This is mostly where we handle bugs, or very code-specific issues.

**Comment by DanielTheBard** [comment]
But, you can. There's a chat in the party screen. It's live. Just like every other chat on the site. You can refresh it if it isn't updating.
