### ISSUE TITLE
Over XP'd + Change of a daily name results in death

### ISSUE THREAD

**Issue by ReZuu** [HabitRPG/habitica#3088]
Well I had a multiple of bugs at once I think.

I managed to over XP as a mage via the "Burst of Flames" spell. 
I had something like 480/360 XP. 
And then I went to change a name of one of my dailies which then ended up killing me after pressing save making me loose all the XP and Gold I had.

**Comment by deilann** [comment]
The over XP thing is known-- skills like Backstab and Burst of Flames don't cause a stats sync. See #2143 

Now, as for changing the names of one of your dailies killing you-- are you in a boss fight and/or was it close to your cron time? Saving that updates the server, which means it's going to see if you're owed any damage. I will venture to guess it is not changing the name that killed you, but something else.

**Comment by ReZuu** [comment]
My party is on a quest, but on the social page it says "ReZu attacks Vice's Shade for 35.5 damage, Vice's Shade attacks party for 0.0 damage. - 9 hours ago". And I had updated the habitRPG for todays cycle already between this incident and that boss attack.

**Comment by deilann** [comment]
Can you refresh the party page for me? Just a double check.

**Comment by ReZuu** [comment]
I just updated the party page and between my refresh and death there had been 12.8 dmg dealt to the party, which I think would have been enough to kill me since my HP was low since the over XP didnt make me level up =/

**Comment by deilann** [comment]
That's what I thought had happened.

Next time, if your XP goes over, clicking any task will level you up. You can use Fix Character Values (In Settings > Site) to give yourself back your gold and XP.

**Comment by ReZuu** [comment]
Thank you for the assistance =)

**Comment by deilann** [comment]
np n__n
