### ISSUE TITLE
Lost HP after levelling up

### ISSUE THREAD

**Issue by FunnySunshine** [HabitRPG/habitica#309]
At the beginning of the day, I had maybe a health of 11/50. However, I levelled up during the day, so my health bar got filled again.

However, now, I went back on the website later in the day and I have again 11/50 of health. We're still the same day and I haven't done any bad habit, so I shouldn't have lost all that health. I haven't noticed if I'm at the same level, but my experience bar is at 1/100, as it should be, and all the tasks I've done are still checked. Therefore, it only seems to be a problem with my health bar.

Thanks for your help!

**Comment by Pandoro** [comment]
Have you tried to log out and in again, or refresh the site? 

I must say I noticed something similar on the test server this morning though. Please report back when you have any news on this problem :x

**Comment by lefnire** [comment]
Check this out again tomorrow morning, my latest push may have fixed this

**Comment by FunnySunshine** [comment]
I tried to log out and log in as well as refreshing, but it hasn't done anything.

I'll see tomorrow morning.

**Comment by loldude101** [comment]
I have the same problem but mines worse. Remember, my "It's going berserk" claims, well it went away for it bit but lately (past week) it's has been horrible. I log and I randomly die, try to check marks "Daily"s the it goes berserk (doesn't get me exp, or reduces hp, it just goes CRAZY). Also, today while it was doing it's own thing it all the sudden deleted all my "Habits".

**Comment by lefnire** [comment]
@loldude email me your uuid, i'll investigate. Try a refresh on deleted
habits

**Comment by horusofoz** [comment]
Resolved through previous fixes
