### ISSUE TITLE
Duplicate quest scroll

### ISSUE THREAD

**Issue by leupagus** [HabitRPG/habitica#3090]
I purchased The Fiery Gryphon quest scroll (and am currently almost done with it!) and the quest itself has been fine. However, when I had to abort the quest the first time, I noticed that it resulted in me having TWO quest scrolls for the same Fiery Gryphon quest. I didn't purchase it twice; I think something about the fact that I had to abort made it duplicate somehow. I'm happy to do the quest twice if needs be, but it seemed like an odd bug that might pop up for other people (although I've looked at this board and no one else seems to have had this problem).

By the way - thanks for doing this. This site has, as cheesy as it sounds, really changed my life. I'm so grateful to you guys.

**Comment by deilann** [comment]
Curious-- what happens if you sync and refresh?

**Comment by leupagus** [comment]
It stays put - that's one of the first things I tried (after trying to sell
the quest scroll) and I just tried it again. No dice.

**Comment by deilann** [comment]
Congrats! You have an extra quest scroll. Doing the Gryphon quest
repeatedly gets you more eggs, so you have just lucked out!

I'll try to reproduce this in a bit.

**Comment by leupagus** [comment]
Haha - fair enough! Next time I'll do the Gryphon quest with some friends
and share the wealth.

**Comment by phillipthelen** [comment]
@leupagus Do you, by any chance, remember if the quest was already active? or were people still responding to the invite?
