### ISSUE TITLE
Random Drop Solution for Quests?

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3091]
What if a random drop from a quest was actually an item-- it showed up in your inventory as "Random Drop" and upon clicking it, you could "open" it to get your random item?

This would allow quests to do random drops, without reworking the entire system.

**Comment by caveman1337** [comment]
This actually sounds like a pretty great idea. Would you suggest the item be determined when you receive the drop, or when you open the item? I'm guessing the latter. This would probably make compatibility with the phone app a lot simpler too.

**Comment by deilann** [comment]
@caveman1337 Sorry I wasn't entirely clear-- what I'm talking about here is a system in which we have no way of giving random drops from quests. This isn't a proposed solution to daily drops.

**Comment by caveman1337** [comment]
Makes sense. It sounds like it would kill a few birds with one stone, though. And yeah, having random drops from quests would be pretty neat.

**Comment by deilann** [comment]
Well, no, in my mind, regular random drops from tasks would drop the same.

**Comment by caveman1337** [comment]
Fair enough. Would you suggest different "Random Items" with different drop tables for each quest? 
I was suggesting doing normal drops like that just for consistency, but it does have the downside of having to open something every time you get a drop. I think I agree with you on keeping normal drops how they are.

**Comment by deilann** [comment]
The only random drops I need to deal with at the moment are food, so I was
imagining a random food item.

**Comment by SabreCat** [comment]
So to be clear, this is a suggestion for a way to have quests include in their list of rewards, "Random item"? If so, can you update the title of this ticket and maybe the initial post? At first glance it's not at all clear what drops you're talking about and what problem this is a proposed solution for.

**Comment by deilann** [comment]
I will. My brain isn't exactly working.

**Comment by crookedneighbor** [comment]
If this is still desired, it should be added to Trello.
