### ISSUE TITLE
Progress text overlapping

### ISSUE THREAD

**Issue by atpunk** [HabitRPG/habitica#3092]
When viewing the progress of any section, the dates are unreadable if there is a high number of progress.  
![hrpg_progress](https://f.cloud.github.com/assets/6874950/2444741/8f6e68d8-ae5f-11e3-8bbf-17359953cef6.PNG)

**Comment by busterroni** [comment]
Same with me, using Chrome (I don't know what version, I'm on my phone
right now, sorry).

**Comment by deilann** [comment]
This is a known issue, and we're actually working on improving graphs in general: https://github.com/HabitRPG/habitrpg/issues/2516
