### ISSUE TITLE
Tags permanently hid dailies.

### ISSUE THREAD

**Issue by JennJohnson** [HabitRPG/habitica#3094]
On Sunday, I tagged a bunch of habits, dailies, and to-do's "weekend," only to have anything (habits, dailies, to-do's, and custom rewards) not labelled "weekend" disappear, even when I toggled the tag on and off. I thought they were simply gone forever, so I deleted the "weekend" tag. Yesterday I did all the remaining dailies, but I still took 18 damage overnight last night, which makes me think my lost tasks are simply hidden.

I'm using chrome, my user id is a211b503-cdd7-4711-a4af-dc2f8f9a433c, and there were no JavaScript errors.

**Comment by deilann** [comment]
What happens if you click the (X) at the end of all the tags?

**Comment by JennJohnson** [comment]
And they're back. Thank you.

**Comment by deilann** [comment]
I think the issue here is that toggling a tag on/off doesn't seem to actually turn the tag off -- only the (X) does.
