### ISSUE TITLE
Vice's HP bar on beta site has an extra box

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3095]
![screen shot 2014-03-18 at 10 59 03 am](https://f.cloud.github.com/assets/6208739/2449136/0da6cda0-aeae-11e3-9ab2-3066b2be4aad.png)

Is this related to the new header? (Which is awesome, by the way.)

**Comment by deilann** [comment]
Mah hedgebeast is doing the same thing.

**Comment by AineMedias** [comment]
I have exactly the same thing!

**Comment by annesoares** [comment]
My trapper santa also has it now.

**Comment by paglias** [comment]
@casicastiel @deilann @BuggyCreeper @annesoares can any of you make a screenshot of the correct behavior or describe it better? Because, not doing any quest I don't understand what's wrong Thanks

**Comment by annesoares** [comment]
@paglias It's just the blue box around the Boss's life that @casicastiel put. It shows like this:
![image](https://f.cloud.github.com/assets/5385803/2491577/70e42358-b1f2-11e3-811b-8b9afc63202c.png)

**Comment by paglias** [comment]
Thanks. Yes it's due to the toolbar redesign, which changed also some styles in the header bars for health, exp... I think cc @benmanley

**Comment by AineMedias** [comment]
@paglias I can't place a screenshot of it, don't know how to do that. Extra description: Blue box like an extended glitchy bar like @annesoares but with Vice, the Shadow Wyrm. I'm currently doing a quest.

**Comment by annesoares** [comment]
@BuggyCreeper yeah, I believe all bosses look like that now... if you notice, your health and XP bars at the new toolbar have a different blue tone than the avatar and the party. I think all the header bars have it now ^-^
If you want to post a screenshot, you can just use print screen + "ctrl+v" at the comment. GitHub auto-uploads the image for you ;)

**Comment by benmanley** [comment]
Oops. That PR should fix it.

**Comment by deilann** [comment]
lgtm, and I'm gonna close this, but let someone with more css knowledge press the green button

**Comment by AineMedias** [comment]
My issue has been fixed!

**Comment by deilann** [comment]
Yup! @benmanley came to the rescue!

**Comment by benmanley** [comment]
Any time. Although it was partly my fault in the first place!
