### ISSUE TITLE
No Experience Being Gained After Rebirth. No Gold Either.

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3096]
This morning, having reached level 100, I bought a rebirth orb. I've since checked off 3 dailies. I still have 0/150 XP and 0/0 GP. The latest daily, at least, produced no pop up about experience or money gained. 

Screenshot attached (taken after checking off 2 dailies). 

Note that the 2 tasks I checked off do have check marks. 

I had a perfect day buff and a "tools of the trade" spell in effect when I used the orb. 

![screenshot from 2014-03-18 07 54 27](https://f.cloud.github.com/assets/4530463/2449152/499ef120-aeae-11e3-9806-53a001109ccf.png)

**Comment by deilann** [comment]
Can you log out, log back in for me, and tell me if those dailies are still
checked off?

**Comment by ArlieS** [comment]
They weren't still checked after logging off and on. And now I know there's a logout button ;-)

**Comment by ArlieS** [comment]
And when I checked one of them after relogging I got 14 xp and 2:10 GP. Much better!

**Comment by deilann** [comment]
You tried turning it off and then on again. ;)

**Comment by ArlieS** [comment]
Logged out, logged in, and then clicked a daily. Which happened to be one I'd clicked pre-logout. Didn't  do an extra click after that to uncheck it.

**Comment by deilann** [comment]
Yeah, I think for some reason when you were clicking the dailies before, it
wasn't actually triggering anything-- so it didn't give you XP, GP... or
save to to the server.

**Comment by ArlieS** [comment]
Oh the joys of multiple places to lose information. 

Sometimes I think kernel programming is _easier_ than web programming. No black boxes in the kernel, except firmware and hardware.

**Comment by deilann** [comment]
Actually, knowing that it didn't save to the server is sometimes nice, like in this situation. :P
