### ISSUE TITLE
Every field to submit says the same thing and runs super slow

### ISSUE THREAD

**Issue by sciurae** [HabitRPG/habitica#3097]
I was both playing with adding tags and turned the option to "Open new tasks in edit mode" on. The option is not staying checked, but new tasks do open in edit mode. 

Every field shows either the word "on" now, or a link I pasted in one of my tasks earlier. If I expand a task to edit, it completely deletes old text and changes everything over to "on" or the link. 

When I try to edit the contents of something, it takes a very long time.

I've tried deleting cookies, I've checked my lastpass settings, and nothing had an effect.

Uname: squirrell

![screen shot 2014-03-18 at 4 38 48 pm](https://f.cloud.github.com/assets/3819536/2455037/8d0cc2fa-aef6-11e3-9b37-ba23ab7f103d.png)

**Comment by deilann** [comment]
The very long time thing most likely has to do with the fact that the
server has been grouchy lately. Requests are taking longer.

Whenever you make a change, it's a good idea to wait for the blue bar at
the top to completely finish. That means that the request actually went
through (if not, you should get an error).

As for the on thing, I've got no idea what's up with that. You've deleted
cookies, but have you cleared your cache?

**Comment by sciurae** [comment]
I cleared cache, and just for fun cleared my form fills in chrome as well. No effect. 
The slowness only seems to occur when I'm attempting to edit the fields that have the "on" inside them - other requests aren't entirely speedy but I also wouldn't call outside of "normal" for habitrpg

(It is super frustrating, I keep wanting to edit things and it takes sooo looong)

**Comment by deilann** [comment]
Does it replicate in another browser?

Also, if you could check and see if there are any js errors showing up in
your console, that would be superawesomehelpful. Do you know how to do that?

**Comment by sciurae** [comment]
I'll check another browser. I do not know how to check errors in my console.

**Comment by sciurae** [comment]
Must be a chrome thing - it isn't happening in  safari.

**Comment by deilann** [comment]
I know you said you cleared your form fills, but that sounds to me like it's some sort of auto-fill going on. What happens if you disable lastpass?

**Comment by sciurae** [comment]
Hmm, that worked. Weird. 

You're super helpful! Thank you so much! Now I gotta figure out why lastpass was frakking up.

**Comment by deilann** [comment]
o7 Glad to help.
