### ISSUE TITLE
Boss Healing back to full twice

### ISSUE THREAD

**Issue by trebro** [HabitRPG/habitica#3099]
Hi there,

Our party is on the Free Yourself from the Dragon's influence quest, and the Dragon has healed itself back to full--TWICE. 

Kinda hard to ever win if it can do that. :(

I check on the tavern, they said it wasn't programmed into the game, so to let you know this happened.

Thanks for any help you can give.

**Comment by deilann** [comment]
You can follow this issue here: https://github.com/HabitRPG/habitrpg/issues/2657
