### ISSUE TITLE
A million points of damage

### ISSUE THREAD

**Issue by DimTwin** [HabitRPG/habitica#3101]
My ID: 91ab86a8-6fb0-4be4-8eeb-7f6b96aef698
Group ID: 15f5b304-8426-49e6-82e0-444455a74628

Here's the issue: While doing the Fiery Gryphon quest one of our party members got hit by the boss for a million points of damage. 
Screenshot:
![1](https://f.cloud.github.com/assets/6949144/2457769/5b2335dc-af3f-11e3-8da2-dbc46c8f177c.jpg)

It was at about 5pm GMT+3
I will provide more info on the background story when/if I can.

**Comment by DimTwin** [comment]
oops sorry)) looks like it was a joke)

**Comment by lefnire** [comment]
_snicker_

**Comment by DimTwin** [comment]
(^_^)
