### ISSUE TITLE
After buying things with gems, they don't appear but I get charged.

### ISSUE THREAD

**Issue by jhardy735** [HabitRPG/habitica#3102]
Hi, I am a subscribed user and as such turn my gold to gems at the market. Recently I have bought potions that never appear but I get the gems taken as if they should have. Just today, I had been saving my last last 4 gems to buy a hedgebeast quest and when I did, it took the gems but left me with no quest. Now I'm in a position where I can't get more gems until next month and am left questless. Kind Regards

**Comment by deilann** [comment]
Potion buying is a new one. What's your UUID?

@lefnire Can you investigate this one? I know of no reason that potions would not appear, unlike quest scrolls.

**Comment by jhardy735** [comment]
Hi, thanks for getting back to me. My UUID is 4056b772-4aa0-49ce-b05a-652fce7b1ae2
Let me know if you need anything else :)

**Comment by deilann** [comment]
I've refunded you 4 gems for the moment, just so you can try and rebuy the
quest. Let me know what happens!

**Comment by jhardy735** [comment]
Wow thanks! I think you've given me 16 though! Thank you. I bought the deer and hedgehog quests and both worked. Great 'game' btw its made me beautifully productive. Jennifer

**Comment by deilann** [comment]
...you're right. I did. Whoops. Brain not turned on. It's your lucky day!

**Comment by Alys** [comment]
This sounds like a syncing problem which we're aware of from other issues, and it's an old report so I'm closing this.
