### ISSUE TITLE
Boss fight in Scroll quest

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3103]
Hi! My party of four started and today completed the first scroll quest, but boy, was the defeat of the boss hard. We are seriously confused about how the points and damage to the boss is ccounted. It said that the damage should be dealt after completing our dailies and to-do's, but sometimes there were no points whatsoever. For example, I completed my to-do's worth a lot of points but no damage was dealt to the boss. There was absolutely no record of it in the party. And today I have apparently dealt damage of 2.8 to the boss just by simply logging in and when I completed my dailies I didn't get any other more points again......
And I would like to ask how the points are calculated? Because when I completed my dailies I got over 30XP, but the damage dealt to the boss was 3.9.....
We are all really confused so thank you for any info :)

**Comment by deilann** [comment]
Missa, the damage is calculated upon cron, so you're not going to see it until you log in after your CDS. XP and damage are not entirely related. The answer to how it's calculate is kind of complicated. You can either dig into our source code or check out the Wiki. That's really the best way to answer questions like these. [Here's the Wiki page on bosses.](http://habitrpg.wikia.com/wiki/Boss)

**Comment by ghost** [comment]
Ok, thank you :-)
