### ISSUE TITLE
Bought a quest scroll and it's not there!

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3104]
Pretty sure this is a common problem but my quest scroll number was at -1 and when I bought one it went up to 0, took my gems but didn't give me a scroll.
My userID is 7c3304d1-3fe8-4a7a-b905-7d2862445b79 if I could get a gem refund please?

**Comment by deilann** [comment]
Gotcha! :)

**Comment by ghost** [comment]
Thanks!

**Comment by deilann** [comment]
Glad to help! :)
