### ISSUE TITLE
Clicking on a Challenge Auto Scrolls Down, Lose Place on Page

### ISSUE THREAD

**Issue by ivychen** [HabitRPG/habitica#3107]
Using Firefox. Clicking on some challenges opens a detailed panel on Habits/Dailies/ToDos/Etc, but clicking others forces the page to scroll down.
The Firefox NET console returns the following (when clicking on ones that force-scroll down):
GET https://www.google-analytics.com/collect

Console returns the following when clicking on a challenge works:
GET https://www.google-analytics.com/collect
GET https://habitrpg.com/api/v2/challenges/6bcefca8-4d26-4d22-9f11-46f45a64dbc0

**Comment by deilann** [comment]
This is related to this: https://github.com/HabitRPG/habitrpg/issues/1682
