### ISSUE TITLE
Tasks go blank after resizing browser

### ISSUE THREAD

**Issue by bunnifluezl** [HabitRPG/habitica#3108]
I had my browser (Firefox 27.0.1) in full screen and resized it for a moment while in HabitRPG. This caused the four panels on the main task page to form a grid (instead of lying side-by-side) and three of the eight tasks in my To-Do panel went blank. I went back to full screen and they didn't come back; refreshing, logging out and in, and resizing the browser didn't fix them.

When I click edit on any of the blank tasks, all the settings for those tasks have been reset as well. When I have them open like that the task title area seems to be shortened, so that the little checkbox beside it is half cut off. Pic: http://i.imgur.com/6UtdIxW.png I don't know if that detail is helpful but I thought I'd be thorough.

Another thing I noticed - I had ordered the to-do list by due date, but after this incident they reverted back to (I believe) the order in which I'd entered them.

I can find no common factor among the items that disappeared.

**Comment by kangabell** [comment]
I've seen To-Do titles disappear too but not sure how. 
Note: I think the reason why the task title area is cut off is because it gets shortened when there is no title present. You can see this happen if you edit a task that does have a title and remove the title while in edit mode.

**Comment by crookedneighbor** [comment]
@bunnifluezl Is this still occurring for you? I tested it in Firefox and didn't get any weirdness.

**Comment by bunnifluezl** [comment]
Nope! Everything seems to be working now. :) Thank you for asking!
