### ISSUE TITLE
Quests don't show victory text

### ISSUE THREAD

**Issue by Waldere** [HabitRPG/habitica#3109]
I recently asked about this in the Tavern, and it seems I'm not the only one having this problem: quests no longer give victory/confirmation screens when a party completes them.

Sure, there's an update in the party chat log: "You defeated X! Questing party members receive the rewards of victory." However, I remember way back when we did Trapper Santa and Find the Cub we received popup notifications showing the prizes we'd won accompanied by a bit of flavor text to complete the story line of the quest. It doesn't sound like anyone has received these popups since the other quests have been implemented.

At first I thought that feature had just been dropped, but based on the Tavern responses, some Trello cards, and a few articles on the wiki containing boss text I've never seen, it seems like the content is there, but no one is seeing it.

I'm afraid I can't be of any help identifying what the problem might be, but I hope that's enough to go on!

**Comment by Alys** [comment]
fixed a couple/few weeks ago
