### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Lyrael** [HabitRPG/habitica#311]
It would be awesome if the habit column could have up/down buttons to sort via most often clicked to least often and vice versa. It would mean I wouldn't have to scroll down the page hunting for things all the time. I know I can sort things one by one but it's not really advisable with the server as unstable as it is; I've lost habits this way too many times to want to touch it anymore, but a quick sort option would be awesome. (and also allow for some visible progress on habits that only have a plus or minus, not both)

**Comment by horusofoz** [comment]
Hi @Lyrael and welcome to the community.

Your idea Is a great one. It is currently on our [Trello Board](https://trello.com/c/OvDWr1Ra) for voting and further discussion.

Please navigate to the link provided and add your voice :)
