### ISSUE TITLE
Could not start solo quest

### ISSUE THREAD

**Issue by bogeyman** [HabitRPG/habitica#3110]
Yesterday I created a solo party, bought my first quest role (Hedgehog), and tried to start the quest. It said, it will start, when all party member accept the quest. So I went to the party page, but found just an abort button. I did not press anything, because I thought it was automagiclly accepted ;)

But today the quest window on the party page is gone. Also the scroll/gems are gone.

Group ID: df7d5122-e1c6-4351-823a-2c87705315fc
User ID: 82f5e274-7386-4e94-be66-ffa5c5e0b36c

PS: Using current Chrome on Windows 7

**Comment by deilann** [comment]
What happens if you refresh the party page?

**Comment by bogeyman** [comment]
Argh, ok, everything is now in place. Thanks a lot!

**Comment by deilann** [comment]
No problem! For some reason, you often have to refresh the party page to
get new info.
