### ISSUE TITLE
Beast Master Achievement keeps appearing on hatching gen2 pets

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#3111]
Now that I have the beast master badge I keep getting the pop up saying that Congratulations I've got the beast master badge! when I hatch the new pets such as the gryphon or hedgehog. This does not happen when rehatching grown pets.

**Comment by deilann** [comment]
Here you go Bailey: https://github.com/HabitRPG/habitrpg/issues/2990
