### ISSUE TITLE
Clearing To do list does not remove challenge todos from list

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#3112]
I tried to clear my completed to do list recently. Regular To dos that I created are removed but my challenge to dos remain. Is it suppose to stay there? I fear it will just continue growing and take over my habit

**Comment by wc8** [comment]
Is the challenge ongoing?

**Comment by Mihakuu** [comment]
Both on going and closed

**Comment by deilann** [comment]
Ongoing challenge To-Dos will remain until the challenge is closed. If the challenge has ended, you can remove them like any other challenge item.

**Comment by hametsunosaturn** [comment]
This is the closest bug I can find to my problem. I've been clearing regular (non-challenge) to dos and they keep coming back. I had one I checked off then just randomly reappeared for no reason. I checked it off again, refreshed the page, and it was still there (as was the XP and gold I gained for checking it off). It took too tries to delete it before it finally went away.

**Comment by deilann** [comment]
@hametsunosaturn That sounds more like you're trying to clear them while
we're having server issues.

**Comment by hametsunosaturn** [comment]
Maybe. But other things I've checked off at the same time do go away. I checked off several things on Wednesday, one came back the next day. So I checked it off again on Thursday and it came back again, several times, until the second time I deleted it (once I realized I was getting extra XP). Then today, another item I checked off on Tuesday or Wednesday popped back up again and I deleted it. But I've checked off way more To Dos than that between Wednesday and now and all of those have stayed gone.

I don't mind deleting them, just thought you guys might want to know that it's happened a few times.

**Comment by deilann** [comment]
Yes, that can happen. The server issues are intermittent. You may also be
clicking too fast, which can cause your requests to not make it all the way
to the server. And you shouldn't delete them if that happens-- if it
doesn't stay gone, you didn't get the XP/GP from it, even if it looked like
you did when you checked it off the first time.

**Comment by hametsunosaturn** [comment]
Well, all the extra XP I got actually stuck around. So I felt bad because even after refreshing it appearing again, I still had more XP from the task than I should have gotten.

**Comment by deilann** [comment]
Are you positive that the XP stuck around? It might not be entirely obvious
that it didn't.

**Comment by hametsunosaturn** [comment]
Well, I am capable of remembering a number over a short period of time and tested it a few times in a row. So yes. But if you're certain it was server issues and I'm wrong, then we can leave it be and I'll just keep checking things off that come back and stop bugging you.

**Comment by deilann** [comment]
Sorry-- what I'm talking about here _isn't_ a short period in time. The
reason I need to make absolutely sure if the XP is sticking around, and not
being taken away later, when you sync with the server is because that's a
unique bug. It's not that I'm sure that you're wrong; it's that this has
never been reported and it's always been what I'm talking about. So I need
to make absolutely sure that's what's going on, if that makes sense?

**Comment by hametsunosaturn** [comment]
Then if it happens again I'll check how much XP I have at night and then see if it decreased at all after chron and report back.

**Comment by deilann** [comment]
Awesome! Thank you so much.

Until then, I highly suggest clicking slower (wait until the blue bar
across the top finishes before clicking something new), and periodically
doing a hard refresh, just to see if anything pops back.

**Comment by hametsunosaturn** [comment]
I already do wait for the blue bar to load and all the notifications to pop up before clicking anything else off. That's why I didn't think it was anything to do with checking things off too quickly.

**Comment by deilann** [comment]
:thumbsup:

Checking things off too quickly can get the same response as the server
having issues. But we've been having server issues separate from the
clicking fast lately. There's a ticket on that if you want to look called
"Has Habitica Fallen?" (On email not GH at the moment; can't search for
it.) Sometimes it can be difficult to tell if the server's not actually
responding during these periods, and sometimes it's blatantly obvious, with
errors popping up everywhere and pages not loading.

**Comment by Lael-** [comment]
https://github.com/HabitRPG/habitrpg/issues/3803   I've posted a new issue here that is somewhat similar - although it is the same group of 6 to dos that reappear each time.

**Comment by deilann** [comment]
This ticket should actually be closed, as it's expected and desired behavior. If challenge To-Dos cleared when you cleared completed, there would be no way for people to see if you've completed the tasks.

Your bug @Lael- is a different one entirely.
