### ISSUE TITLE
Chat Mentions Not Highlighted

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3114]
So, I've managed to create the opposite of E's problem with chat highlighting. With the username `!("Ryan 2.2.5")` absolutely nothing highlights for me.

**Comment by casicastiel** [comment]
Congratumalations.

**Comment by deilann** [comment]
It's pretty awesome. I like breaking things.

**Comment by negue** [comment]
Closing this, because the logged user, will be highlighted (with an underline) in the chat.
