### ISSUE TITLE
Purchased Quest Scroll does not appear in inventory

### ISSUE THREAD

**Issue by KatieSt27** [HabitRPG/habitica#3116]
I just purchased The Fiery Gryphon quest scroll for 4 gems (my last 4 gems).  However - it did not appear in my inventory but the gems are gone.   I've done similar purchases 6 or 7 times over the past 2 months with no issues.

 Any way to get the scroll or the gems back?

Thanks!

User ID

aa87a105-5770-40a0-aa8d-cdf74973b912

**Comment by deilann** [comment]
Gems on their way back ASAP! I'm pretty sure this is related to the negative quest scrolls bug. Sorry it took me so long to respond. :)

**Comment by KatieSt27** [comment]
Thank you!!!  I appreciate the help!

**Comment by deilann** [comment]
np :)
