### ISSUE TITLE
Trouble with "sort" API function

### ISSUE THREAD

**Issue by black-orchid** [HabitRPG/habitica#3118]
I apologize if this is a dumb question, as I am new at this!  I am trying to use sort, and no matter what I do, I seem to get an HTTP 400 (Bad Request) response.  Here is the url I am using:

https://www.habitrpg.com/api/v2/user/tasks/fb3137d4-dc39-4403-a638-fd16ecbe9788/sort?from=0&to=1

I am properly putting API credentials in the header (I have been successful with other commands).  The task I am trying to move is currently first in my To-Do list, hence "from 0 to 1."  Could the bad request be because there is no content in the body of the request?  Is there request content I'm supposed to include?

**Comment by lefnire** [comment]
Very strange, the path looks correct. Does the 400 show any sort of error [in the response](https://www.evernote.com/shard/s17/sh/f39bfb99-d319-489a-9c6e-7a141339aa6f/e65851956fd530f2e8a74f384e98442a)?

**Comment by black-orchid** [comment]
Sorry, I was working with .Net's Web package and maybe it wasn't giving me the whole story.  Using curl, here's the exact command I'm running (minus authentication data), and the response:

curl -X POST -H "x-api-user: APIUSER" -H "x-api-key: APIKEY" "https://habitrpg.com/api/v2/user/tasks/24eb0a59-a77b-4e51-a71e-d636d1c52963/sort?from=1&to=0"

{"err":"direction must be 'up' or 'down'"}

**Comment by lefnire** [comment]
fixed, will push tomorrow

**Comment by black-orchid** [comment]
Thanks for the quick fix!
