### ISSUE TITLE
Empty Place-holder for last item

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#312]
![HabitRPG Gamify Your Life](https://f.cloud.github.com/assets/3267747/129973/4beff690-6ff8-11e2-9864-b4b6b82408e7.png)
After getting the gold sword the gold coin appears next to an empty box. This is me testing btw.

Edit: Changed title from "Image Gone" to "Empty Place-holder for last item" for easier finding in future when addessed.

**Comment by horusofoz** [comment]
@lefnire Has NeoHuman bought out the weapon range?

**Comment by lefnire** [comment]
yeah, last items bug. will fix later, minor

**Comment by Pandoro** [comment]
If I recall it right, this was fixed during one of the last bigger pushes right? Can we close this? 

Edit: I just checked this on the test server, which was up to my surprise ^^; And this is gone now, so I'm closing this one for now.
