### ISSUE TITLE
Local copy of habitrpg throws error on npm start

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#3120]
Been a while since I've been around habitrpg, but now I'm trying to actually learn the MEAN stack and want to get my local copy of habitrpg running again. No rush on this, but if anyone can give me a hint, that would be great.

Here's what I've done to update from the root directory of the project:
 `git fetch upstream`
`npm cache clean`
`bower cache clean`
`npm update -g npm`
`npm update -g bower`
`npm update -g grunt-cli`
`npm install -g npm-install-missing`
[npm-install-missing](https://www.npmjs.org/package/npm-install-missing)

`````` npm-install-missing```
Returns "nothing missing, Wazooh"

```mongod```

```npm start```

Everything seems fine until it starts throwing many of these errors:

```module.js:340
    throw err;
    ^
Error: Cannot find module '/Users/bobbyroberts/habitrpg/node_modules/habitrpg-shared/locales/en/app.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadTranslations (/Users/bobbyroberts/habitrpg/src/middleware.js:115:15)
    at Object.<anonymous> (/Users/bobbyroberts/habitrpg/src/middleware.js:123:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/Users/bobbyroberts/habitrpg/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bobbyroberts/habitrpg/src/server.js:30:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
[Fri Mar 21 2014 15:00:16 GMT-0700 (PDT)] [master:2056] worker:4621 disconnect! new worker:4628 fork```

After 15 minutes and no completion, I give up and control z.

Any ideas? Thanks.




``````

**Comment by deilann** [comment]
Have you pulled the latest habitrpg-shared stuff? It looks like you're
missing the new language files.

**Comment by paglias** [comment]
npm install?
Il 21/mar/2014 23:09 "Bob Steffes" notifications@github.com ha scritto:

**Comment by bobbyroberts99** [comment]
Here are the [results of npm install](https://www.evernote.com/shard/s207/sh/b3cea387-d2b3-47f3-b60c-6684cbbaa7a0/b4ca27e2f83251ac9242e9d64a29c293) and [npm start](https://www.evernote.com/shard/s207/sh/e89ecca6-742b-441a-93d7-faec84296bdd/6511de28b976cd942c47079ec696e68a).

I have habitrpg-shared cloned but can't fetch or set the upstream? Do I need to or should npm install load the shared stuff? 

Thanks for such quick response @deilann and @paglias.

EDIT: See below for most current versions.

**Comment by deilann** [comment]
I've found that if I have a setup that uses shared, if shared is out of
date, it causes issues because it is replacing files that habitrpg uses.

Are you making sure to set the upstream in the habitrpg-shared repo, rather
than in the habitrpg repo? You could also just `git pull
https://github.com/HabitRPG/habitrpg-shared.git`

**Comment by bobbyroberts99** [comment]
@deilann, yeah I was working from the shared repo. Here's what I get:

**Status**
`BobMac:habitrpg-shared bobbyroberts$ git status`
`# On branch develop
nothing to commit, working directory clean`

**Fetch upstream**
`BobMac:habitrpg-shared bobbyroberts$ git fetch upstream`
`fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository. 
Please make sure you have the correct access rights
and the repository exists.`

**Set upstream**
`BobMac:habitrpg-shared bobbyroberts$ git branch -u upstream/develop`
`error: the requested upstream branch 'upstream/develop' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.`

**Pull upstream**
`BobMac:habitrpg-shared bobbyroberts$ git pull upstream develop`
`fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`

Is Develop the right branch?

**Comment by deilann** [comment]
Did you ever `git remote add upstream
https://github.com/HabitRPG/habitrpg-shared.git`?

**Comment by bobbyroberts99** [comment]
@deilann, that's what I was looking for. Seems like habitrpg-shared is up-to-date now but npm update is throwing errors when i run it from habitrpg repo. Now what do you think is the next step?

BobMac:habitrpg-shared bobbyroberts$ git remote add upstream https://github.com/HabitRPG/habitrpg-shared.git
BobMac:habitrpg-shared bobbyroberts$ git fetch upstream
remote: Counting objects: 4423, done.
remote: Compressing objects: 100% (2105/2105), done.
remote: Total 4423 (delta 2795), reused 3657 (delta 2221)
Receiving objects: 100% (4423/4423), 17.82 MiB | 509.00 KiB/s, done.
Resolving deltas: 100% (2795/2795), done.
From https://github.com/HabitRPG/habitrpg-shared
- [new branch]      bosses     -> upstream/bosses
- [new branch]      challenges -> upstream/challenges
- [new branch]      challenges-0.5 -> upstream/challenges-0.5
- [new branch]      checklists -> upstream/checklists
- [new branch]      contrib    -> upstream/contrib
- [new branch]      cron-script -> upstream/cron-script
- [new branch]      develop    -> upstream/develop
- [new branch]      difficulty -> upstream/difficulty
- [new branch]      ghost-stag -> upstream/ghost-stag
- [new branch]      master     -> upstream/master
- [new branch]      math-balancing -> upstream/math-balancing
- [new branch]      mevanoff/bug -> upstream/mevanoff/bug
- [new branch]      mounts     -> upstream/mounts
- [new branch]      ops-overhaul -> upstream/ops-overhaul
- [new branch]      paglias/translate -> upstream/paglias/translate
- [new branch]      sabe/drops -> upstream/sabe/drops
- [new branch]      undo       -> upstream/undo
- [new branch]      winter     -> upstream/winter

**Comment by deilann** [comment]
What errors is it throwing?

**Comment by bobbyroberts99** [comment]
Aside from the [highlighted errors](https://www.evernote.com/shard/s207/sh/2dcff217-8815-4434-83b0-83340b9dc56d/572c6ea992580d2b00b13dd7a1760973), npm update came back mostly clean (I didn't include the whole thing, just from where the 1st warning occurred).

It seems like my version of nodejs (0.10.25) is not what it wants (0.8.?). Should I look at uninstalling and reinstalling the older version?

Here are the errors for [npm install](https://www.evernote.com/shard/s207/sh/3d3691a5-9f8b-431e-8559-5b798cf35ad0/00f40d8651fee80898d75d9487f949f0).

And for [npm start](https://www.evernote.com/shard/s207/sh/c9484ef8-fb03-49da-91ee-3816ed37dc51/fa0c243f8aff6fcdbf7043712cfb9686).

**Comment by deilann** [comment]
Nah, the warns are fine. Actually looks like node needs an update, not a
downgrade. What OS are you using?

**Comment by bobbyroberts99** [comment]
OS X 10.9.2

**Comment by bobbyroberts99** [comment]
I did an npm install for habitrpg-shared and got errors and then did this update. Was that right to do? I never did this before and had the local copy running successfully. Seems like the problem is with spritesmith?

[Errors for npm update on habitrpg-shared](https://www.evernote.com/shard/s207/sh/09894742-30c2-401d-bd43-0bf56fc3046c/2dbd689d298a63b2054a0428e56a562b). 

running node:  0.10.26
running npm:   1.4.3

I have n installed so it's easy to switch versions of nodejs if that's what necessary. Any ideas?

**Comment by tjwds** [comment]
OS X and habitrpg really do not get along whatsoever.  Try any one of these things:
- Clear your trash… this may be difficult if node is holding on to one of the files, so familiarize yourself with the "rm" command.
- …then run sudo npm cache clear
- Make sure bower was installed properly—installing npm on OS X has to be run as sudo, but bower throws an error if it's run as sudo (???!!!!!??!?!!???!) so go ahead and run "bower install" for good measure
- And, if all else fails, delete everything and start from scratch using [this guide])(http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally). 

Hope this helps, because it's pretty frustrating for me as well to have to spend several minutes troubleshooting every time I want to run a local copy for testing.

**Comment by bobbyroberts99** [comment]
Thanks for the reply. I've done all you suggested. Starting from scratch 
will be my third time doing so. I give up.

joe woods wrote:

**Comment by tjwds** [comment]
Don't give up! I've contributed like five times in the past two weeks and have only gotten a local copy to work around twice.  I know it's frustrating, but these tools weren't written with OS X in mind; there are a lot of variables at play.  And it'd be great if there were multiple people working on the problem so that we'll get it fixed permanently that much sooner.  :-)

**Comment by thepeopleseason** [comment]
Just a note that you could try the vagrant virtual machine to see if it eliminates OS X-specific errors.

**Comment by Alys** [comment]
I'm closing this since it's a few months old now and the site's code has progressed enough that any issues @bobbyroberts99 was having have hopefully been resolved. 

I second @thepeopleseason's recommendation for his awesome vagrant VM. I use that on OS X and it saves a LOT of work.

@bobbyroberts99, if you'd like to come back and try again, there's more of us around now with enough experience to probably be of help to you.

**Comment by tjwds** [comment]
The OS X worker-disconnect-fork error [seems to be a port listening problem](https://github.com/HabitRPG/habitrpg/issues/4138#issuecomment-59086085), but now I'm having issues with it no matter which port I try.  All in all, pretty frustrating.

**Comment by Alys** [comment]
@tjwds It's probably best to start a new issue, with output from your own install. The information listed above is likely to be wildly out of date and investigating based on it could lead us down a completely wrong path.
