### ISSUE TITLE
Is this what the new toolbar is supposed to look like?

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3123]
People are posting compliments, but I can't see my avatar, or much of its stats.
![screenshot from 2014-03-21 22 33 46](https://f.cloud.github.com/assets/4530463/2489981/ea71beac-b183-11e3-9cff-3442ca17ceca.png)

**Comment by deilann** [comment]
Click some of your notifs and it should fix itself.

**Comment by lefnire** [comment]
@benmanley is looking into collapsing chat notifs in the future. Might be
better to wait for that than a temp fix methinks, since I'd imagine that
many notifs might be somewhat rare?

**Comment by MaxHedrm** [comment]
This isn't entirely related, but I thought I'd throw it out here, since it's about the new menu. :) 

I'm a bit mixed on the new menu. Putting all the non-Task (User, Social, Inv...) sections in a drop down just makes it harder to get to with no real value added. It also seems a bit tall, in these days of wide screen laptops, vertical real-estate is much more valuable than it once was.

I do like moving the Gems & money up there though. And locking it in place is a huge improvement. Of course that only exaggerates the thickness. :)

Also, I'm curious, Arlie, how many guilds & such are you in? Yikes!

**Comment by AranelS** [comment]
I am not at ALL mixed about this new menu.  It takes up even more of my valuable screen real-estate, it has a ton of extra (unnecessary) space around the words, and it is set to a FIXED HEIGHT.  

I can now see three dailies without scrolling.  On the tavern page, I can only see as far as the notice about reporting bugs.  The menu adds basically nothing for me.  It just gets in the way.

**Comment by AranelS** [comment]
I uploaded a screenshot so you could see what this does on a small widescreen laptop.  (I have a 14" screen. Its optimal resolution is 1366x768.)
![ss](https://f.cloud.github.com/assets/4458101/2491253/aae919e2-b1e2-11e3-9178-a795e28fc1f1.png)

**Comment by MaxHedrm** [comment]
Your post just made me notice, didn't the black menu have a collapsable thing? or was that just the avatar bar below it that's collapsable?

**Comment by lefnire** [comment]
FWIW, the conversation leading to these changes is here https://github.com/HabitRPG/habitrpg/issues/2835. There's still some stuff to be done - this release isn't he finished product, but a piece of it. Catch up on that convo, and do continue to post requests here (eg, _collapse toolbar_ feature).

**Comment by MaxHedrm** [comment]
Great, thanks! I was hunting for a spot for feedback, but gave up too soon. ;)

**Comment by MaxHedrm** [comment]
It looks like benmanley directed stuff specific to the new toolbar here: https://github.com/HabitRPG/habitrpg/pull/3076

**Comment by ArlieS** [comment]
@MaxHedrm Only 27 guilds ;-)

**Comment by ghost** [comment]
I use an iPad (so, small screen) and it helps to set the avatars/party section so that it's not sticky so that you get screen real estate back as you scroll.

**Comment by wc8** [comment]
Shall we close this in favor of #3155 ?
