### ISSUE TITLE
Problems with switching classes

### ISSUE THREAD

**Issue by BanktownUSA** [HabitRPG/habitica#3124]
I changed my class to Healer for the spring event and whilst I then had new items to buy they were the warrior ones. There are also no special attacks available to me (idk if Warrior's are suppose to have them, but I didn't pick Warrior in the first place). Now I can't change my class or even edit my allocation points. That whole section in the profile area is missing.

**Comment by Alys** [comment]
This might not help with your issue, but just in case it does... Have a look at these instructions for [enabling the class system](http://habitrpg.wikia.com/wiki/Class_System#Enabling_the_Class_System). Do they fix your problem?

**Comment by BanktownUSA** [comment]
That fixed it! Thanks.
