### ISSUE TITLE
Spring event gear descriptions don't show stats

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3126]
Although it costs the same as normal armor, the spring gear is described as if it were costumes in the store. However, when you go into the profile of someone who's wearing it as gear, it shows stats.

![screen shot 2014-03-22 at 8 53 46 pm](https://f.cloud.github.com/assets/6208739/2492358/b2fdc176-b225-11e3-854f-cad4410101cf.png)

I've seen a few people confused about this in the Tavern today.

**Comment by lefnire** [comment]
They have stats. The descriptions need updating.

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg-shared/pull/183 Fix'd
