### ISSUE TITLE
all tasks deleted!!

### ISSUE THREAD

**Issue by squishygoat** [HabitRPG/habitica#3127]
Somewhere in between buying the spring event armor and hatching new eggs, all of my tasks/dailies/etc. got deleted.  I did not reset my account - I still have gold and inventory.  Anyway someone can help?

I added a test daily "hi" just to see if that was actually the case and it wasn't my screen/browser/ad blocker/etc.  Help!  :(
!

[image](https://f.cloud.github.com/assets/5897657/2492765/f754899a-b252-11e3-898d-ab5652f0ad31.png)

**Comment by lefnire** [comment]
Clear your tags

**Comment by squishygoat** [comment]
haha what a mess I am.  thanks!  :)
