### ISSUE TITLE
Can't add friends to party

### ISSUE THREAD

**Issue by Sashi-Mee** [HabitRPG/habitica#3128]
Hi there !

I love HabitRPG but I can't get to the social part of it as when I try to add some friends to my party. Everytime I get an error.

Can this be fixed rarther quickly so my friend's interest does not die ( and so they can help me not dying too ! ;) ) !

Thanks!

I admire the work you've achieved so far !
Keep up and good luck !

If i can do anything to help, please let me know !
Cheers

---

Here's the console output :

POST https://habitrpg.com/api/v2/groups/477c4389-c4a4-47d5-bbc9-b7d809ec2799/invite?uuid=Marcouchka 400 (Bad Request) app-812c96da.js:5
(anonymous function) app-812c96da.js:5
r app-812c96da.js:5
j app-812c96da.js:5
k app-812c96da.js:6
(anonymous function) app-812c96da.js:6
i.$eval app-812c96da.js:6
i.$digest app-812c96da.js:6
i.$apply app-812c96da.js:6
(anonymous function) app-812c96da.js:7
o.event.dispatch app-812c96da.js:2
r.handle app-812c96da.js:2
Object {data: Object, status: 400, headers: function, config: Object}
 app-812c96da.js:22
d app-812c96da.js:22
l app-812c96da.js:6
(anonymous function) app-812c96da.js:6
i.$eval app-812c96da.js:6
i.$digest app-812c96da.js:6
i.$apply app-812c96da.js:6
n app-812c96da.js:5
y app-812c96da.js:5
t.onreadystatechange app-812c96da.js:5

**Comment by deilann** [comment]
Are you trying to add them with their display name or their UUID, which is
a random alphanumeric string they can find in Settings > API?

**Comment by Sashi-Mee** [comment]
Thanks for the quick reply !

I tried both (but the copy-paste i did is from the display name).
I can't get their UUID at the moment for a retry (i shoulda copied them on a spare file but I didn't. 
If you're u, you may give me an UUID so i can try to add it to help you troubleshoot ?

**Comment by deilann** [comment]
Trying my UUID would not work-- I'm in a party, so you'd get an error.

**Comment by Sashi-Mee** [comment]
My friends are sleeping. (we're in France) I'll shall get back at you when i get an UUID to tryout.

**Comment by deilann** [comment]
o7 I'll likely still be awake. ;)

**Comment by Sashi-Mee** [comment]
great then ! :) in the meantime, does the info i got you can help ? (console ?)

**Comment by deilann** [comment]
That spits out a bad request because you were trying to invite with the
user name "Marcouchka" rather than the UUID.

**Comment by negue** [comment]
I'll close this, since it is not an error of the API, which is working as intented.
