### ISSUE TITLE
Can't delete todo

### ISSUE THREAD

**Issue by ian-kelling** [HabitRPG/habitica#3129]
Just created new account. Click delete button on the prepopulated todo, nothing happened. Created new todo. Click delete. Nothing happened.

**Comment by deilann** [comment]
What OS and browser are you running? Can you open your console and tell me if you're getting any js errors? If you log out and log back in, does anything change?

**Comment by ian-kelling** [comment]
iceweasel 28.0-1~bpo70+1 amd64, debian wheezy. logged out and logged in and it worked. I initially created my account on mobile, then noticed it didn't seem fully formed so I switched to my desktop and noticed the problem there. Didn't get to check for js errors before it got fixed by relogging, and there were none then.

**Comment by ian-kelling** [comment]
On mobile, I used the app by OCDEVEL, on android.

**Comment by deilann** [comment]
I'm going to guess the page didn't fully load or something was up-- I've seen this creep up a couple of times, but logging in and out (or refreshing) tends to fix it. Sometimes it'll be that clicking a task doesn't do anything.

The OCDEVEL app is the official one. It doesn't have as much functionality as the site, though; you are correct. Habit was initially a web app; the mobile app was added later.
