### ISSUE TITLE
Being able to put the game on pause

### ISSUE THREAD

**Issue by nodefourtytwo** [HabitRPG/habitica#313]
If I go on holidays and I can't access internet, I'll lose HP points everyday without being able to do anything. It would be great if we could put the game on pause for some days.

**Comment by Pandoro** [comment]
As suggested in several other places, you can disable all your dailies for each day, and thus not loose any hp. But some sort of pause feature can also be found on [trello card 14: Rest in Tavern/Vacation button](https://trello.com/card/rest-in-tavern-vacation-button/50e5d3684fe3a7266b0036d6/14)
