### ISSUE TITLE
Negative Mana

### ISSUE THREAD

**Issue by CSlatman** [HabitRPG/habitica#3130]
For some reason I'm now at -10 mana. I don't know what happened. I searched through the other issues, but I don't think I clicked pickpocket twice.

Right now I can't gain or lose mana, but the mana bar appears full. Even after attempting to die, to fix the issue, it didn't work. I still can't gain or lose mana.

**Comment by deilann** [comment]
You probably ended up getting a double request, not clicking twice. Go to "Fix Character Values" in Settings > Site and you should be able to restore it.

We're looking into ways to keep the number of double requests from happening, but that should fix your problem.
