### ISSUE TITLE
Dailies Randomly Resetting Streaks

### ISSUE THREAD

**Issue by nataliezook** [HabitRPG/habitica#3132]
Two days ago several dailies of mine had their streaks reset. I figured it was a random glitch that had to do with the big Spring updates. I've not noticed it happen since, but when a party member reported the same thing, I figured a bug report wouldn't be out of line. Will report back if it happens again.

My ID:
ec6e08f5-f39d-47f8-95e1-7909cd18965e

**Comment by deilann** [comment]
I think it's less likely that their streaks were randomly reset and more likely that you checking them off didn't save to the server, so they were thought to be undone. This is more common than usual lately, due to some server issues.

**Comment by nataliezook** [comment]
That makes sense, especially since I'd only logged in twice the day before instead of my usual three times (in other words, that evening I wouldn't have caught any dailies that didn't take.) Thank you.

**Comment by deilann** [comment]
No problem. :)
