### ISSUE TITLE
You have achieved Beastmaster - again and again

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3133]
So, I have a complete collection of non-quest pets, along with a few quest pets. Today I hatched a hedgehog (quest) pet, and was told I'd achieved beastmaster. I believe this is a regular occurrence, for both quest and non-quest pets. (I.e. when I feed a non-quest pet up to mount, then replace it, I "achieve beastmaster" again.)

Low priority but silly. 
![screenshot from 2014-03-23 21 48 35](https://f.cloud.github.com/assets/4530463/2496073/a151608c-b30f-11e3-933c-a60ecd39aca0.png)

**Comment by ArlieS** [comment]
Update after 3 hedgehogs each told me I'd achieved beastmaster, I promoted and replaced a fox - no pop-up for that one. So I guess I'm wrong about non-quest pets. Perhaps that's been fixed since last time I'd accumulated enough food? Or perhaps I'm misremembering, but don't believe so.

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/2990
