### ISSUE TITLE
Empty party for questing

### ISSUE THREAD

**Issue by Tkaname** [HabitRPG/habitica#3134]
Ok, I've been trying to figure out how to start questing... I created an empty party MONTHS ago, and the thing in my inventory keeps telling me to create an empty party for solo quests. I am in an empty party, why in the world is it not recognizing this? I can't do anything! Also, are the world events quests supposed to be free the first time around, then buy the scroll from the market? because I haven't gotten the scrolls for anything ever.

**Comment by deilann** [comment]
The notice in the Market is static-- regardless of party status. The only
free quest at the moment is Vice, which drops at level 30. The deer quest
was released during the spring event, but it is not a world event quest --
it's another pet quest and will never expire.

**Comment by Tkaname** [comment]
so will the deer quest ever be dropped to me then?

**Comment by deilann** [comment]
No, it's a regular pet quest. It must be purchased with gems.

**Comment by Tkaname** [comment]
darn, thanks. I didn't know if i was missing something or not.

**Comment by deilann** [comment]
If you can't purchase gems for some reason or another and want to do pet
quests, you might want to check out the section on the wiki for finding a
party. Only one person in the party has to buy the scroll, and everyone
gets the eggs.
