### ISSUE TITLE
Different Health in bar vs stats page

### ISSUE THREAD

**Issue by Coi-l** [HabitRPG/habitica#3135]
Right now I have 44 / 50 as health in my health bar but 43 / 50 on the stats page. 
Page is freshly reloaded.

Should I venture a guess I would say different rounding techniques are being used in the  two cases but that is just a guess without knowing the code base.

Cheers

**Comment by deilann** [comment]
It's true. And actually, I have a solution for this I just haven't pushed it yet. There's a ticket assigned to me somewhere for this...

**Comment by deilann** [comment]
Here it is: https://github.com/HabitRPG/habitrpg/issues/2772

**Comment by Coi-l** [comment]
Sorry about the double post. Didn't find anything when I searched. 

Good to know it's on the way. :-) 

Cheers
