### ISSUE TITLE
Leveled up, max mp decreased!?

### ISSUE THREAD

**Issue by Greygreene** [HabitRPG/habitica#3136]
I recently leveled up from 11 to 12, and I expected my max mp would increase. Instead, it changed from 50 to 41! As a rogue I was really hoping to make use of pickpocket to get the whole kitty cat suit-- I need all the mp I can get! And I certainly don't want to keep losing max mp as I level... help!

My id is 19d9f752-de61-450b-9073-022e77bc2f7c

**Comment by casicastiel** [comment]
Your MP potential is based on your INT points, so that means that something else happened to decrease your INT, at a similar time to when you leveled up. Did you have a Perfect Day buff, or a party member's Earthquake buff that could have just worn off?

**Comment by casicastiel** [comment]
(Also: Backstab is way better for gold at the moment than Pickpocket. ;)

**Comment by Greygreene** [comment]
Not that I know of! I thought everyone started out with 50 MP!

**Comment by deilann** [comment]
nope! 40, actually

**Comment by Greygreene** [comment]
Dang. I guess i coulda had a perfect day buff at some point that wore off. Thanks!

**Comment by deilann** [comment]
np!
