### ISSUE TITLE
Cannot change jobs or set stats

### ISSUE THREAD

**Issue by SuicidalChaos** [HabitRPG/habitica#3137]
I used some gems to change jobs to get all of the Spring gear sets. I then had 11 gems left. I went to change jobs again, but backed out of the menu by hitting Opt Out and it still charged me 3 gems for it. I am now down to 8 gems. On top of this I no longer have the option to change jobs or set the stats on my character. The normal options on my stats page for this is completely missing.
![habitrpg_glitch](https://f.cloud.github.com/assets/7049518/2502181/6f2465fe-b374-11e3-8c4f-8e7ba19a4b0d.jpg)

**Comment by deilann** [comment]
I believe there's a place in settings where you can re-enable classes...

**Comment by SuicidalChaos** [comment]
That worked. Thanks for the help!

**Comment by deilann** [comment]
np! Glad you got it fixed. :)
