### ISSUE TITLE
"Invite" button on Party page - functionality could be clearer

### ISSUE THREAD

**Issue by LB7979** [HabitRPG/habitica#3138]
RIght now there can be confusion to the user regarding what the "Invite" button on the left side of your Party page is for.
It is for inviting others to join your Party, but it is easy to think that it is for inviting others to a Quest.
To make its functionality more clear, maybe something could be displayed near the button along the lines of:
"This is for inviting others to join your Party. To invite others to join a Quest, use a Scroll from your Inventory that can be found under Market."

**Comment by LB7979** [comment]
Sorry about the stuff between [ ] in the title, I wanted to attach a label but it didn't work (first time I've posted on GitHub...)
Can someone tell me how to attach labels to post titles?

**Comment by deilann** [comment]
Not sure if you can attach labels... but I can!

**Comment by larouxn** [comment]
How about a tooltip on rollover for the invite button? I have attached an example.
![rollover](https://f.cloud.github.com/assets/1557529/2512981/f1623002-b42b-11e3-8c11-81e3539a5cfa.png)

**Comment by LB7979** [comment]
Yes that would be perfect!

**Comment by deilann** [comment]
I think I'd also add something about using the UUID, not the display name.

I'm gonna assign this to myself and add it to my to-do list.

**Comment by Alys** [comment]
The invite process is being redesigned by Lemoness and she'll create trello cards/issues for her changes, so I'm closing this.

Pinging lemoness in case there's anything here to be considered.
