### ISSUE TITLE
Tasks not contributing to the boss fight

### ISSUE THREAD

**Issue by RankkaApina** [HabitRPG/habitica#3140]
I'm quite new to habitrpg and we just started a quest with my party. My problem is that even though I've completed several tasks today, I only got credit for the first one against the boss. I'm wondering if it has something to do with the fact that I changed my profile name, but at least changing it back didn't help. Please help! I want to be useful to my party!

**Comment by deilann** [comment]
You will only see your boss damage after cron (your day rollover). All of your tasks will be rolled into one. If after cron, you still don't see the damage, refresh. Often, the party chat doesn't auto-update.
