### ISSUE TITLE
Gear Disappeared

### ISSUE THREAD

**Issue by GirlGalvanized** [HabitRPG/habitica#3143]
Gear disappeared.  I didn't die, but when I woke up my gear was all gone and I was back to base clothes.  I bought bunny ears after that and those disappeared too now.

**Comment by GirlGalvanized** [comment]
My tasks are fine.  It's the gear for my avatar that disappeared.

**Comment by lefnire** [comment]
Woops, sorry about that! Did the GP go through? (are you short GP now?) If not, like the actions never got through to the server for one reason or another. In the mean time, head to Options > Settings > Site > Fix Character Values and set your GP up for re-purchase

**Comment by GirlGalvanized** [comment]
It's fixed now!  Thank you very much.

**Comment by deilann** [comment]
Glad to hear it @GirlGalvanized !
