### ISSUE TITLE
Sync button in Toolbar doesn't seem to sync Bailey

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3145]
Here's a sequence of events:
- been logged on all day
- clicked on a to do to record completion.
- the Bailey head appeared in the tool bar to announce that there was news
- clicked on it; the news looked familiar.
- clicked the sync button at the right side of the tool bar
- clicked the Bailey head; the news still looked familiar
- used the browser's refresh function
- and now I see news dated 3/25/14 

I'm not surprised to see Bailey appearing with old news; I've need to do an explicit refresh for rather a while - otherwise the head appears when there's new news, but the news I see is stale.  I just hoped that the sync  button would handle this case.

**Comment by lefnire** [comment]
Alas, when there's a bailey you have to refresh. She comes with new css, images, javascript item definitions, etc - those have to be reloaded by the browser
