### ISSUE TITLE
Empty inventory.

### ISSUE THREAD

**Issue by DimTwin** [HabitRPG/habitica#3146]
Today when I i checked my inventory to have a look at my new mystery items i found that its almost empty.
Here's the screenshot:
![1](https://f.cloud.github.com/assets/6949144/2509365/f7760760-b3f0-11e3-8b4a-285331e65a79.jpg)

Yesterday it was completely ok. And even now i have all my equipment on me. It just doesn't show in inventory. I reloaded and refreshed the page several times but it didnt help. The pets and mounts windows are unaffected.

My ID: 91ab86a8-6fb0-4be4-8eeb-7f6b96aef698

**Comment by DimTwin** [comment]
Hm. I cleared cache and it helped.

**Comment by lefnire** [comment]
Likely just needed a hard refresh. We'll need to add a header bar indicating users need to refresh when we push new stuff,  it's causing a lot of confusion

**Comment by paglias** [comment]
@lefnire we have a method to say to the browser that it needs to refresh

**Comment by DimTwin** [comment]
@paglias Good to know that)) 

By the way it refreshed just fine on my other PC.

**Comment by lefnire** [comment]
@paglias ah yes! I'll look into using that. I was reserved since IIRC it will tell mobile clients to upgrade the app (it's a heavy-handed solution, I think we built it for major API updates where a client snap is incompatible with the server). Will look into

**Comment by paglias** [comment]
Yes it was built for api updates. Anyway we can use it for whatever we
want. Even if in this case I suppose it was due to the browser not
invalidating the cache correctly
Il 25/mar/2014 20:06 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by Alys** [comment]
I'm closing this since it's old, was fixed with a cache clear, and we now have an automatic refresh every six hours.
