### ISSUE TITLE
Notifications obscure header.

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#3149]
and, AFAIK, there's no way to hide or disable them.
![bad notifications!](http://i.imgur.com/QpVTb6j.png)

although I did find this amusing:
![get off my bod, Bailey!](http://i.imgur.com/J2SboxB.png)

**Comment by deilann** [comment]
Ben Manley's going to make it so that if you have this many notifs, you don't see all of them. It's a known issue. The solution is to click a few of them.

**Comment by Caspid** [comment]
An option to mute guilds or disable notifications altogether would be nice — I don't particularly want _any_ notifications.

**Comment by deilann** [comment]
That is in the plans/works! You'll be able to decide what guilds (if any)
you want notifs for.

**Comment by negue** [comment]
Can be closed? The Header was renewed.
