### ISSUE TITLE
Progress graph doesn't show  for daily's

### ISSUE THREAD

**Issue by aaronjbaptiste** [HabitRPG/habitica#315]
After pressing the progress icon I get: "Data column(s) for axis #0 cannot be of type string"

Shows up fine on Habbits

Chrome: 24.0.1312.57 m

**Comment by wc8** [comment]
Is this a newly created task?

**Comment by wc8** [comment]
@lefnire I can replicate this on the tester site, though not on my main account. (That is why I am wondering if it only affects tasks that are fairly recent.)

**Comment by aaronjbaptiste** [comment]
Nope, everything under Daily, including those that were created 2 or 3 days ago. (I only signed up 3 days ago so that's as old as they get).

I was having this problem yesterday as well, so I don't think it was caused by the recent deployment.

Screenshot:
![progress graph error](https://f.cloud.github.com/assets/3449340/133662/92dbe142-70af-11e2-82d6-30d5b1e46af8.PNG)

**Comment by justinvanwilgen** [comment]
I got this issue today as well on a daily that I created about 3 days ago, but haven't done yet.

**Comment by StanLindsey** [comment]
Yeah I am getting this too, it seems like an easy fix as the graph just wants an integer and not a string and therefore we most likely need to feed in some default values of 0,0. @lefnire will know where this is in the code =P

**Comment by ianjohnsa** [comment]
Just want to report that I have also encountered this issue. Affects all of my dailies, regardless of age. BTW do habits still have the same chart button option? Because the button isn't showing up at all on my habits. Also, I noticed the graph button for my 'to do's' disappears after I click it and the graph pops up. There is no way to hide the graph, unless I refresh the entire page.

**Comment by StanLindsey** [comment]
Is it happening on ones which you have given 3 inputs to? If so then my thought above is incorrect. 

I noticed that graph issue also. I plan on looking into them both.

**Comment by lefnire** [comment]
there's some funky history snapshots being stored, which is confusing google. Definitely a bug, it's on my list.

**Comment by ianjohnsa** [comment]
Don't quite know what you mean by 'given 3 inputs to'. Do you mean that I have completed 3 times? If so, then no. I'm pretty new and don't think I've completed any of my dailies 3 times (all less than that I believe).

By the way, congratulations on getting funded on Kickstarter. You have a great app with enormous potential. And open source of course rocks. You all should be proud to be working on it.

**Comment by lefnire** [comment]
:) :) :) :)

**Comment by ianjohnsa** [comment]
As one more piece of information. The graph (progress icon) does show up for my habits which have + and - buttons. But not on the ones which only have one or the other. I don't know if this is a bug or by design for some reason, but thought that piece of information might help you all hone in on the issue if it is a bug.

**Comment by busterroni** [comment]
I can also confirm this.
![Screen Shot 2013-02-20 at 6 25 14 PM](https://f.cloud.github.com/assets/3424032/178346/fee7e38a-7bb4-11e2-84d2-75f973bc4796.png)
FireFox v. 11.0

**Comment by lefnire** [comment]
You get points for farting? :) :)  Naw, this is a definite confirmed bug - and happening for most people at this point. I elevated to important (we have critical for the more debilitating bits)

**Comment by busterroni** [comment]
Farting is healthy :)

**Comment by Daij-Djan** [comment]
Im experiencing it too

**Comment by wc8** [comment]
This seems, in my case, restricted to certain tasks. I'm not sure the common denominator, yet, but it might have to do with several days of not having completed them.

**Comment by ErPanfi** [comment]
Can confirm this
![Screenshot](https://f.cloud.github.com/assets/3525691/236283/b587d6ea-87e0-11e2-8910-86d327b2ab41.PNG)
These dailies has been created together, so it's not a daily-age related issue...
Also, the screen shows a bug in X-Scaling routine of the plot (many X entries for the same day)

**Comment by lefnire** [comment]
Fixed: https://github.com/lefnire/habitrpg/pull/616/files - deploying soon

**Comment by fawques** [comment]
I had this issue with one of my dailies. After this fix, the one that was having the issue (bottom one) has started showing the graph, but it's plain
and the one that was working fine has plummeted with no reason (top one)
![Captura de pantalla de 2013-03-11 23:56:27](https://f.cloud.github.com/assets/1254383/246408/b6d74dca-8a9f-11e2-8078-dad777771e2a.png)

**Comment by Linskeyd** [comment]
I know this is closed but I just got this message to pop up when I hit the set of bars on the far right of my experience bar.
![screen shot 2014-07-19 at 11 27 09 pm](https://cloud.githubusercontent.com/assets/5875538/3636389/c4145f06-0fbd-11e4-8728-323a496ffdb7.png)

**Comment by deilann** [comment]
@Linskeyd check out this ticket: https://github.com/HabitRPG/habitrpg/issues/3691
