### ISSUE TITLE
Daily CRON

### ISSUE THREAD

**Issue by ceresandraste** [HabitRPG/habitica#3151]
My cron did not roll over and I am unable to check off my dailies for today. Username ceres_andraste.

**Comment by lefnire** [comment]
#1057

**Comment by ceresandraste** [comment]
Sadly I am not finding that thread at all useful, I checked my start time and I interacted and refreshed the screen.

**Comment by deilann** [comment]
@ceresandraste That is the master issue ticket for this bug.
