### ISSUE TITLE
Menu arrow should face right and upon click face down

### ISSUE THREAD

**Issue by larouxn** [HabitRPG/habitica#3152]
Just a small improvement that I can write up and submit in a pull request.

It just doesn't make logical UX sense for the arrow to face down and upon the menu appearing below, it swing to facing up. I guess it is supposed to represent the action of clicking to make menu come down then up, but I believe it makes more sense to face right then down.

Mockup:
![right](https://f.cloud.github.com/assets/1557529/2528593/168e1914-b511-11e3-9e8f-2428827aa1a5.png)
![down](https://f.cloud.github.com/assets/1557529/2528594/17c6d118-b511-11e3-8e1b-71f018b006d9.png)

Opinions?

**Comment by deilann** [comment]
You're right, but can you post this here: https://github.com/HabitRPG/habitrpg/pull/3076 so Ben Manley will see it?

**Comment by larouxn** [comment]
Sure thing. Thanks.
