### ISSUE TITLE
Yeti Hat gone :,(

### ISSUE THREAD

**Issue by HumanPlus** [HabitRPG/habitica#3153]
I died, and my yeti hat is gone, and is no longer available for me to re-purchase.  

I was under the impression that you couldn't permanently lose limited edition items.

**Comment by lefnire** [comment]
Are you a warrior still? You can only re-purchase the gear of your class, so when you roll warrior again it will be available

**Comment by fayehinto** [comment]
Does this apply to the Shaft of the Dragon as well? It being warrior specific purchase. Two of my teammates lost it and are unable to repurchase it.

**Comment by deilann** [comment]
What level are they? I'm wondering if it's level specific because I can't
repurchase it yet, after a rebirth.

**Comment by disreputabledog** [comment]
I'm also wondering about Shaft of the Dragon. I'm a Mage and it's not showing up in my store after losing it on death a few days ago; do I just need to swap to Warrior?

**Comment by deilann** [comment]
One should be able to repurchase Shaft of the Dragon now.
