### ISSUE TITLE
Can view the discussions for a guild I haven't joined.

### ISSUE THREAD

**Issue by JennaMalkin** [HabitRPG/habitica#3156]
I followed a link that @lemoness left on the HabitRPG Pixel Art board to the Pixels in Progress guild on HabitRPG ( https://habitrpg.com/#/options/groups/guilds/a141a5b9-0d69-46cd-93e6-2b76f18bcc54 ) and even though I have not joined the guild, I can see the discussions there.

This feels slightly wrong to me, like I can eavesdrop on the guild.  Should this be changed so that I get a 'join this guild' page instead?

I have not tested posting in the guild.

**Comment by deilann** [comment]
I personally don't find it a problem because you cannot access private
guilds you are not a member of, just public ones.

**Comment by JennaMalkin** [comment]
But what's the point of joining a guild if you can eavesdrop?

**Comment by deilann** [comment]
Notifications. Ease of access. Challenges.

It's not really eavesdropping, considering I could join the guild for two
seconds, read the convo, then leave.

**Comment by Alys** [comment]
Viewing a guild in this manner is a very common thing now. We often put guild URLs in the Tavern, for example. It is definitely considered a feature now.
