### ISSUE TITLE
Damage not being dealt to The Spirit of Spring boss

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3157]
The damage my party has been doing to the boss of this quest has not been showing up as it should be. Refreshing the page added HP back on to the boss.

Group ID: c6943add-d0d3-4da6-b3b6-84c82e40ab95

**Comment by deilann** [comment]
If refreshing the page added HP back onto the boss, I think you've got #2728

**Comment by deilann** [comment]
Er, sorry: https://github.com/HabitRPG/habitrpg/issues/2657
