### ISSUE TITLE
Question: Town Crier Forest Walker Announcement

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3158]
@lemoness or @lefnire Is "February" correct in the following announcement? 
(Emphasis added, but otherwise the following is copy, paste.)

> March Mystery Item Set
> 
> The **March** Mystery Item Set has been revealed for all subscribers... The Forest Walker Set! All people who are subscribed this **February** will receive two items: Forest Walker Armor and Forest Walker Antlers!

**Comment by deilann** [comment]
There's already a fix merged to handle the typo. :)

**Comment by lemoness** [comment]
Yep, that's what I get for trying to work while traveling. Sorry, guys!

**Comment by deilann** [comment]
Oh man, if this is the extent of that, no wonder you're always amazing. :)

**Comment by lemoness** [comment]
<3
