### ISSUE TITLE
Party System bugs

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#316]
They should all be their own tickets, but I figure we'll start the flood in one location so I can direct offsite requests here.
- Something happened causing a 500 query/sec spike in Mongo, killing the connection. Still diagnosing
- One user experienced the popup disappear immediately

**Comment by danj3ris** [comment]
I got one for you. Hitting "reset" after the party feature has been unlocked, does not remove the party feature. Hence I can now form a party as a level 1 character. The store is also still available after a reset.

I cheated my way to level 3 in order to unlock the functionality. Which leads me to a suggestion concerning cheating, which I am about to submit.
![Resetbug](https://f.cloud.github.com/assets/3335082/134460/83231b36-70db-11e2-8103-77cf50e54a0b.jpg)

**Comment by lefnire** [comment]
I don't think I'll change that, incidentally. The point of unlocking things is to expose users to complexities over time, so that they're not overwhelmed at first, but also have new goodies keeping them on their toes. Once _features_ are available, don't want to remove those.

**Comment by danj3ris** [comment]
Well, I find myself agreeing with you! I'm posting my suggestion as a separate "bug / feature suggestion".

**Comment by danj3ris** [comment]
Clicking on the "Add" button in the "Habits" box opens up the box that clicking on one's username opens. I cannot add a new habit.

**Comment by wc8** [comment]
@danj3ris your issue sounds like #330 
I can't confirm it on my end, but that may well be because I'm not a member of a party.

**Comment by ancientcampus** [comment]
Level one players invited to a party will see a green "1", but have no way of seeing, confirming, denying the invitation, or even knowing what the heck it the green 1 means. :)
Once the player reaches level three, they can suddenly see the party option and accept.

**Comment by ancientcampus** [comment]
This was with the same characters as my above comment, but as it's a different issue I'm posting it separately:

The level one player received an invitation, then spammed the green arrow until he became level three, at which point he accepted the party invitation. He could not see who the invite was from, or the party name. When he clicked "accept", the party name appeared for a brief moment before successfully putting him back in the main screen, in the new party.

**Comment by ancientcampus** [comment]
"No close button to the party screen"

Not a bug, but a UI issue:
When looking at the party screen, while already party, there is a red "Leave" button, but no close button. Clicking on the background will close the party window, but users may interpret the only button ("leave") as the way to close the party manager window.

**Comment by lefnire** [comment]
the "can't add a habit" bug is here: #330, pretty critical

**Comment by Flightone2** [comment]
Hi, when the "Party system" went online I created a party then I sent my girlfriend a invitation to it. She was able to accept and this put both our xp and hp on her page (not sure if that's how its suppose to work). But anyway,  I never got a message back and my page has not changed. I still am solo. Is this a bug or am i doing the party system thing wrong?

**Comment by lefnire** [comment]
indeed a bug. Even after a refresh on your end? You shouldn't see exp/hp of each, you should see only your own exp / hp and your friend's avatar. Checking it out.

**Comment by Flightone2** [comment]
I only see my avatar hp and xp (like its always been). I refreshed, its been about a day. I made a party then put her id in, sent her a request and the party system is showing on her screen but mine never changed. 

Do i have to do something else on my end? or does she have to send me a request like i sent her one?

**Comment by lefnire** [comment]
No, it's all pretty automatic. [email me](mailto:tylerrenelle@gmail.com)
your uuid, email, or username - I'll see what I can discover.

**Comment by lemoness** [comment]
When it says ID, is that the string of numbers and letters? I feel like it would be much easier to just enter the username of my friends.

Also, is there a way to see their pages?

**Comment by lefnire** [comment]
The User id is the first string of characters on the user settings dialog.
I'm going to add this to the "party" dialog to make it more obvious. I'll
think on a way to do username too, but some people signup with facebook

**Comment by lefnire** [comment]
ok, #330 is fixed, we have close button, the "create party" dialog shows your user id so people dont accidentally give each other their user names (we'll add support for the latter later). Soon i'll set it up so you can join a party even if it's not unlocked (the "1" in the corner but nothing i can do issue)

**Comment by lefnire** [comment]
[Unlock party system if user invited to a party despite level](https://github.com/lefnire/habitrpg/issues/533) (fixed). The rest are in specific issues #320 #426 or have been fixed
