### ISSUE TITLE
Can't feed pets after choosing "prevent page from generating further dialogue"

### ISSUE THREAD

**Issue by SoonerDVM** [HabitRPG/habitica#3160]
Don't know if this is a bug, but it's a problem that I don't know how to fix. 

I was on the pets screen and when the dialogue box popped up to confirm, I clicked the checkbox about not generating further dialogue.

Since then, I can't feed any pets and I don't know how to undo it. 

---

_edit by admin:_

**Comment by paglias** [comment]
Which browser are you using?
Il 27/mar/2014 15:59 "SoonerDVM" notifications@github.com ha scritto:

**Comment by SoonerDVM** [comment]
Firefox 28.0

**Comment by paglias** [comment]
Refreshing the page worked for me
Il 27/mar/2014 16:21 "SoonerDVM" notifications@github.com ha scritto:

**Comment by SoonerDVM** [comment]
Ok, that seems to have fixed it. Thanks. 

I just need to remember that refreshing fixes almost anything on Habitrpg.

**Comment by paglias** [comment]
Well at least this one isn't a HabitRPG problem :)

**Comment by deilann** [comment]
Yeah, that's a browser setting -- and there's nothing Habit can do about it
being an option. If Firefox detects lots of dialogs are happening, it'll
ask you if you want the page to stop making them.

**Comment by Rorikins** [comment]
I'm having the same issue but it won't resolve with a reload/refresh browser. I'm using Chrome.

**Comment by Alys** [comment]
close all browser windows and reopen them.

**Comment by Rorikins** [comment]
That worked! Thank you!!
