### ISSUE TITLE
Almost no drops for Subscribed Rogue

### ISSUE THREAD

**Issue by zero719** [HabitRPG/habitica#3162]
So, I heard on the Tavern that the Drops code was recently changed a bit. I don't know much about it, but around that time my drops started changing dramatically. Now, I used to get an obscene amount of drops, and I'm glad that was balanced out. But on a day where I might average 10ish Dailies and a few Habits, I'm getting maybe one or Two Drops over the entire course of the day. Some days I get no drops. 

I'm Subscribed and I'm a Rogue with Per over 50. Shouldn't I be getting way more frequent drops?

**Comment by deilann** [comment]
Subscriptions up your drop _cap_, but don't up your drop _rate_. That sounds about right to me-- about a 15% chance, which will go up as your PER goes up. But @SabreCat's the one to ask here.

**Comment by zero719** [comment]
Yeah, I know it ups the cap, but I just wanted to be clear about the fact that I haven't even gotten close to reaching my cap in weeks, when I was relatively used to hitting it daily. Not that I think drops should be that abundant necessarily. But again, going a whole day without a drop when I do all of my dailies doesn't seem right.

The problem also started when I began using two different mobile HabitRPG clients. I'm not sure if that has anything to do with anything, but I've noticed mobile clients don't provide drops. 

Also, for reference, I have 71 Per on days when I get Perfect Day Buffs (which is most days).

**Comment by deilann** [comment]
The mobile clients _do_ provide drops-- just not drop notifications. So you
may be getting drops, but not noticing.

Drop rates are also related to the _color_ of your tasks. Blue tasks are
less likely to give drops unless they have long streaks. Streaker
achievements will up your overall drop rate.

**Comment by zero719** [comment]
Ah. That's all good to know. I didn't know about the colour affecting drops. Maybe it actually is an issue relating to the colour and my streaks. It still seems like I'm getting significantly less drops in general, but I guess I'll close this up until I can confirm with certainty that it's an issue and not just a misunderstanding on my part. 

Thanks for the help!

**Comment by deilann** [comment]
It's likely that since the changes you _are_ getting less drops in general,
but because of the way the algorithms were changed, but not due to a bug.
One thing you could try is purchasing a fortify potion (it'll reset all
your tasks back to yellow, 0 streaks). Also, if you're using mobile, which
still doesn't show drops, check how many items you have at the end of the
day, and compare. You may be getting things you didn't know about. :)
