### ISSUE TITLE
First char is > in task textbox results in enlarged task entry

### ISSUE THREAD

**Issue by sleepyspider1** [HabitRPG/habitica#3163]
If the first character in a daily/todo/habit is the ">" character, it becomes enlarged.

**Comment by sleepyspider1** [comment]
Create the task first, then edit it.

**Comment by deilann** [comment]
That's because task titles support markdown.

**Comment by deilann** [comment]
Sorry if that was gruff. You'll get the same thing with starting a task title with # or + or \* -- lines in Markdown that start with those characters have special formatting. So it's either no markdown or some things get weird.
