### ISSUE TITLE
Quest Damage Resetting Periodically

### ISSUE THREAD

**Issue by MANDRO1D** [HabitRPG/habitica#3165]
On four separate boss quests, after a few of our party members have dealt damage to the boss, the boss suddenly restores itself to 100% health. It's usually after 3-5 party members have registered damage. 

This has happened to our party in the Hedgehog, Gryphon and Spring boss quests. Is this a known issue?
![bossdamagereset](https://cloud.githubusercontent.com/assets/6981840/2546037/b7da2570-b628-11e3-8659-7458ba4b2dd9.png)

**Comment by deilann** [comment]
It is! And we have _no_ idea why it's happening. Chime in here #2657
