### ISSUE TITLE
Spacing around "Archery" lost in tranlated pages #i18n

### ISSUE THREAD

**Issue by oleg-sh** [HabitRPG/habitica#3167]
![snapshot44](https://cloud.githubusercontent.com/assets/1823612/2550613/cc70dd9c-b684-11e3-963a-1ca00e9d435e.png)
Whitespace is lost in Russian, German, Spanish, French and probably other locales.

Page URL: http://i18n.habitrpg.com/#/options/groups/party

**Comment by paglias** [comment]
thanks, let's keep them in a single place #3168 

By the way it looks like all the items are not showing up translated... it's only me @oleg-sh ?

**Comment by oleg-sh** [comment]
@paglias yep, same here

**Comment by oleg-sh** [comment]
@paglias just to clarify — this issue is not specific to http://i18n.habitrpg.com, it appears on the production site too.

**Comment by paglias** [comment]
@oleg-sh fixed now, to see the default tasks you'll have to create a new account
