### ISSUE TITLE
facebook login doesn't work if not already logged in

### ISSUE THREAD

**Issue by ShabbyX** [HabitRPG/habitica#317]
Usually with other websites when you log in using facebook, but you aren't already logged in facebook, you will be taken to a facebook login page.

With habitRPG however, the page goes blank without any messages. If I open facebook on another page, log in and then go back to the blank page and refresh, I correctly log in and would be redirected back to the habitRPG.

I'm on Ubuntu (both 12.04 and 12.10) with the latest firefox.

If you can't recreate the problem, let me know so I can try to get more information.

**Comment by lefnire** [comment]
oi, upping to critical. I tried to emulate, was able to log in but it took a helluva time. Diagnosing, thanks.

**Comment by ShabbyX** [comment]
A day after I submitted this issue, it seems to be ok since then. Don't know if it's luck or you did something ;)

Anyway, I, at least, don't have this issue any more.

**Comment by lefnire** [comment]
I think I solved it, re-open if an issue again
