### ISSUE TITLE
Superfluous, repeated deaths in party

### ISSUE THREAD

**Issue by Raibean** [HabitRPG/habitica#3170]
My party is on the "Vice Awakens" quest, and this is the fourth time I have died during this quest. (We all know that you are not actually taken out of quests when you die... even though you're supposed to be.) Another member in my party has died three times, but I don't know about anyone else in the party. It seems like it's over-adding of party damage or something, because I haven't acquired enough damage to have died this many times - just once, total. It's very frustrating.

Browser- Chrome
User ID - 0b66bb30-8328-4e27-b2c6-7d293c57d52f
Java Error - I don't believe I've gotten any errors, or at least I haven't been notified of any.

**Comment by deilann** [comment]
Not doubting you, just want to make sure:

Are you remembering that you don't just take damage from Vice, but you also take your normal daily damage?

**Comment by Raibean** [comment]
I'm not forgetting that I'm damaged by my party's damage, but are you also implying that I get double my own damage?

**Comment by deilann** [comment]
Not quite double.

So, you get hit for your own dailies like usual. Then, Vice does about 1.5 times as much damage to you and your party. (CON isn't involved in the Vice damage, so it's not _exactly_ 1.5 times, but close.)

**Comment by Raibean** [comment]
But what I'm asking is if you get hit with your own damage PLUS the 1.5 your own damage?

**Comment by deilann** [comment]
Yes. Like I said -- you get hit with your normal damage, like usual. Then Vice does 1.5x damage to you and your party.

**Comment by Raibean** [comment]
Well that definitely makes it more difficult, but I'll look back at my damage to see if that's still enough.

**Comment by deilann** [comment]
Thanks. :) Let me know in a new comment. (If you edit, it won't hit my
inbox.)

**Comment by Raibean** [comment]
Okay, I think the 2.5 of my own damage is doing it. I want to reset my tasks, but I can't find that option. I know it used to be with the health potion, but it isn't there anymore. Has it been moved?

**Comment by deilann** [comment]
The fortify potion? It's in the market now.

**Comment by Raibean** [comment]
So they cut out a useful (free? I think it was free) option and now make you pay cash for it? (And adding more features to it, I guess.) That's a bit upsetting, considering my situation.

**Comment by deilann** [comment]
I'm not sure why you feel the need to reset all your task values and
streaks to zero because of this? I'm not sure how it's related.

**Comment by deilann** [comment]
(I also personally can't remember fortify being free, but I might be wrong?)

**Comment by Raibean** [comment]
My understanding is that if I reset, I'll receive less damage from red tasks. (Maybe it wasn't free? But at least it was gold.)

**Comment by deilann** [comment]
Yes... but really the best thing to do is to do those red tasks instead. If
you're having trouble doing a task that badly, it might be best for it not
to be a daily and be a habit instead. The solution should really not be to
reset all of your tasks... I think that's part of the reason the Fortify
potion costs. It's kind of contrary to the idea of the game?

**Comment by Raibean** [comment]
But if it's a Habit, I won't know if I've done it that day. It's unfortunate, but honestly the Habits section only works to help me break bad habits, and not through loss of life, but through refraining from doing something for the day and gaining experience/gold/drops because of it. Losing health points just doesn't motivate me, and until this particular quest, I've had no problems with it.

**Comment by Raibean** [comment]
I definitely think quests should explain that they add to your usual daily damage instead of replacing it, to avoid future confusion, at least.

**Comment by deilann** [comment]
I find that meta-tasks help with that. (I'm also working on Habit counters
at the moment, but bigger stuff has come up.)

If you don't want to gain extra XP from it, you can put it as a checklist
item in a related (or unrelated daily) to say whether or not you've clicked
it. Checklist items in dailies don't actually increase their value, like
To-Dos.

**Comment by deilann** [comment]
I can look into that. I've only had it come up a couple of times, so I'm
not sure how many people are confused. I'm thinking info about quests
should be part of the party tutorial bit. The tuts need a lot of work, and
are sadly not high priority at the moment.

**Comment by Raibean** [comment]
Sorry, I don't understand any of the Habit jargon. The XP bit... is not relevant to me? That's the opposite of what I said?? There have been a lot of updates, and the alerts are great, but maybe not enough for everyone. (Which is also unfortunate, because making it more accessible means more work. Who wants to make optional tutorials for every new thing you can do on the site? No one.) The site used to be a lot simpler and I can't understand what anyone is saying anymore. I think a lot of the updates are great and very useful, but the language around it is evolving and I just ????

Well it could be a phrase in that paragraph that explains every quest, the one that's tacked at the bottom. Just add the words "in addition to your usual damage".

**Comment by deilann** [comment]
Sorry -- meta means self-referential. So you'd create a self-referential
task. A task on Habit about using Habit. This task would be to click the
Habit you've set up to replace the daily. But I imagine you don't want to
gain XP from doing it because that defeats the purpose if you didn't do it.
So if you make it a checklist item in another daily, you won't get a bonus
from it, but you'll have a place to record that you've clicked the Habit
that day.

I think tacking it onto the quest at the bottom would be good, but it
should be added to the tutorials in the beginning as well. At level 5, I
think, there's a "hey look parties!" tutorial bit and it needs revamping.

I'll add the tacking on bit to my ever growing list of Habit fixes. ;)

**Comment by Raibean** [comment]
Wait, so you're suggesting I pimp my habit by putting a habit in my habit in my habit???

**Comment by deilann** [comment]
Yo dawg.

**Comment by Raibean** [comment]
Okay, well that's something to consider. Thanks for working with me!

**Comment by deilann** [comment]
No problem! :)

**Comment by lefnire** [comment]
Two bits:
1. Fortify has never been free (actually the original monetization item, was the only one sold for a year)
2. Double damage is not intended, whoops! This is probably the fix, but I don't have time to test it just now, in case someone wants to investigate:

``` diff
diff --git a/src/models/group.js b/src/models/group.js
index 697de31..d2a3670 100644
--- a/src/models/group.js
+++ b/src/models/group.js
@@ -226,7 +226,7 @@ GroupSchema.statics.bossQuest = function(user, progress, cb) {
     // Everyone takes damage
     var series = [
       function(cb2){
-        mongoose.models.User.update({_id:{$in: _.keys(group.quest.members)}}, {$inc:{'stats.hp':down, _v:1}}, {multi:true}, cb2);
+        mongoose.models.User.update({_id:{$in: _.keys(group.quest.members, $nin:[user._id])}}, {$inc:{'stats.hp':down, _v:1}}, {multi:true}, cb2);
       }
     ]
```

**Comment by deilann** [comment]
Oh, double damage is _not_ intended? I always assumed that you were
supposed to take your own damage like normal.

**Comment by lefnire** [comment]
@deilann well hey, leaving it in is easier if y'all prefer it that way. Makes more sense, now I think about it - a pleasant accident?

**Comment by deilann** [comment]
Thoughts:

Bosses currently deal half of the damage they're supposed to. Static 2
multiplier got left off.

So, if we get rid of the personal damage, a lot of bosses are going to be
dealing far less damage than your dailies would naturally. Sure, it's to
the entire party, but it feels like bosses should deal more damage than
your dailies, imo.

So, if we do get rid of personal damage, I think we need to get that 2
multiplier in there.

**Comment by Raibean** [comment]
Wow all of that and there is an actual glitch?

**Comment by deilann** [comment]
It's not a glitch per se. It just wasn't what was intended, but has been how the game worked and was left that way.

**Comment by deilann** [comment]
Like, it's not a glitch that bosses deal half their STR in damage, rather than full STR in damage... it was a mistake that's just now used that way.

**Comment by Raibean** [comment]
Okay but that's what a glitch is, a minor problem.

**Comment by lefnire** [comment]
We'll leave it in for now then. Sounds like people have expected it to work this way for the most part.

**Comment by deilann** [comment]
@Raibean See, but you're viewing it as a problem. I'm not viewing it that
way. The way it was implemented was not intended, but is intuitive and
logical to me. A glitch is something that does not work the way you expect
it to.

@lefnire sounds good!

**Comment by Raibean** [comment]
Well, it's the thing that killed me and took away my nearly 2k gold... I feel a bit justified in calling it a problem lol but that's because I have a personal stake in it, so I'm biased. As for glitch, the mirriam-webster dictionary defines it differently, but I'm sure it means something more specific in tech circles, just like many jargon that shares common language and professional language.

**Comment by deilann** [comment]
No, what killed you was not doing your dailies. ;)

All bosses work that way and have always worked that way since the quest
system was implemented. The best way not to die whilst questing is and
always has been... do your dailies.

**Comment by deilann** [comment]
I made you a present Raiban. :)

https://github.com/HabitRPG/habitrpg-shared/commit/5db43ecd668bfcc6fd9f2e8fd088f97f9bed414a

Hopefully no one will be confused in the future. Wording look good to you?

**Comment by Raibean** [comment]
Perfect, thank you!
