### ISSUE TITLE
Tasks deleted

### ISSUE THREAD

**Issue by Pattonandy** [HabitRPG/habitica#3171]
Yesterday I added a task and all of my other tasks and rewards disappeared. Is there a way to restore them? Habit username: Pattonandy. User Id: 90a75d41-fe0c-4b9a-b86e-f92091599592.

**Comment by meganstrickland** [comment]
It sounds like you might have a tag selected. Could you try clicking the ( x ) at the end of your tag list?

**Comment by lefnire** [comment]
indeed. Checked out the UUID, all's there. See https://github.com/HabitRPG/habitrpg/issues/3047
