### ISSUE TITLE
Unlocking language on Avatar page is unclear

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#3175]
The current wording of "2gems/locked" is unclear, and makes it sound somehow like the whole category is locked and you have to pay to unlock it. From the Tavern:

@balamuc:

> Why does it say 2gems/locked under Head, Body and Skin in the Avatar tab? It looks like it's related to the basic types, but those were already unlocked. 

@BrightBold:

> I agree with @balamuc that that is confusing. I only figured out last week what it was supposed to mean. Maybe something wordier like "Dark gray = locked. Unlock items for 2 gems/ea or 5 gems/set" (where "dark gray" and "gems" could be replaced with images).

I'm not hung up on that particular wording; we just need something that makes it clear that we're referring to the cost of unlocking locked items, as opposed to it sounding like we're saying all the items are locked.

**Comment by deilann** [comment]
`assigns`

**Comment by denis-sokolov** [comment]
Proposed fix in #3184.
