### ISSUE TITLE
Return task info with up/down scoring api

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3177]
@fragmental requests returning task with up/down scoring. Particularly he needs `task.value`

``` diff
diff --git a/src/controllers/user.js b/src/controllers/user.js
index 91329c4..9cec1c8 100644
--- a/src/controllers/user.js
+++ b/src/controllers/user.js
@@ -96,6 +96,7 @@ api.score = function(req, res, next) {
     // TODO this should be return {_v,task,stats,_tmp}, instead of merging everything togther at top-level response
     // However, this is the most commonly used API route, and changing it will mess with all 3rd party consumers. Bad idea :(
     res.json(200, _.extend({
+      task: task,
       delta: delta,
       _tmp: user._tmp
     }, saved.toJSON().stats));
```

downside: more bandwidth, particularly with `task.history`. Thoughts anyone?
##

**Comment by fragmental** [comment]
The reason for this is setting the task color, since task color is determined by task.value.  Without local math, the only way to determine a color change from upping and downing a task is make a call for stats every time a task is upped or downed.

**Comment by negue** [comment]
The only math that is needed is this: `newTaskValue = oldTaskValue + delta`.
