### ISSUE TITLE
Challenges UI closes opened challenge when another is clicked

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3178]
Browser: Firefox 28.0, Windows 7

Steps to reproduce:
0. Go to the challenges page.
1. Click the title of a closed (folded? hidden? whatever the word is) challenge (A).
2. Click the title of another closed challenge (B).

Expected:
Challenge A stays opened, and challenge B becomes opened.

Actual:
Challenge A becomes closed, and challenge B is not opened.

**Comment by deilann** [comment]
See https://github.com/HabitRPG/habitrpg/issues/1682
