### ISSUE TITLE
Death

### ISSUE THREAD

**Issue by vidasoy** [HabitRPG/habitica#3179]
Hi,

I recently died and lost all of the normal things associated with death. My random item lost was the Cornuthaum hat. However, once I bought it again at 25g, I automatically lost my Golden Staff as well. I should have only lost one item upon death, so is this a bug?

Thanks,
vidasoy

**Comment by deilann** [comment]
I'm thinking you got hit with https://github.com/HabitRPG/habitrpg/issues/2789

So, you repurchased the item your local side thought you lost, but upon doing so, you synced with the server and it recognized that you actually lost your Golden Staff.

You may or may not have gotten refunded the 25 GP in this instance. Either way, you have the options of using Settings > Site > Fix Character Values to give you the GP to fix this. :)
