### ISSUE TITLE
Subscription benefits should last through billing cycle, even when canceled

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3180]
We've had a number of users subscribe, then immediately unsubscribe. The thought being they take their credit card off recurring payments, but still get a single billing-cycle's worth of benefits. Not yet implemented, self-assigning.

Temp semi-solution: users should open heir mystery box before canceling, they will keep their mystery gear.

**Comment by deilann** [comment]
:thumbsup:

**Comment by deilann** [comment]
When implementing this, maybe keep in mind selling block subs in the future?

**Comment by lefnire** [comment]
Added note about cancelled subscriber perks at https://github.com/HabitRPG/habitrpg/commit/301bebe1bdcc4600c61a05ce47115f6ac4cc386c, so people aren't snagged by this in the near future.

**Comment by bonesarelazy** [comment]
I did not get a note about removing the automatic pp charge equaling canceling the subscription. I also wasn't made aware in advance that the charge was recurring. I can't have a recurring charge on my pp account, so I removed it immediately, loosing all benefits of subscribing, and I'm not thrilled. Can this be reversed, or at least refunded so that I can resubscribe?

**Comment by ghost** [comment]
Would have been nice to see this before I cancelled, as I thought it'd just stop recurring payments... I did not get a note about it either,as @bonesarelazy mentioned, and considering this is day four into a renewal, I'm feeling rather bummed. Ideally I'd like it reinstated for the remainder. Upon trying to re-start the subscription, it wanted me to insert my information again. ><

**Comment by lefnire** [comment]
b0eb12b is important. Now when users unsubscribe, they get the remaining month of perks. I'm gonna go through emails of users who felt slighted there and give them a free month, since now I can do so with a flag on the user object (couldn't before). If I'm missing anyone, [ping me](mailto:tyler@habitrpg.com) and I'll sort ya.

**Comment by bonesarelazy** [comment]
Thanks!

**Comment by deilann** [comment]
Will this allow the sale of block subscriptions?

**Comment by lefnire** [comment]
Yes. 'twill be a medium-difficulty feature dev, but this paves the way

**Comment by deilann** [comment]
:D Yay!
