### ISSUE TITLE
Lost a Level, Equipment Reappeared 

### ISSUE THREAD

**Issue by Serendipital** [HabitRPG/habitica#3181]
My username on HabitRPG is Serendipital. Recently, I lost a level due to some missed dailies. My Plate Armor was taken, and the notification alerted me of this. The next time I logged on, the plate armor was back on my avatar. This happened once before with my Yeti Spear, but I figured that it only came back because it was a limited edition item. It's not a game-breaker, but I think it's important to have - it really encourages you to do your dailies.

**Comment by deilann** [comment]
Chances are, you lost a different item than was displayed. See https://github.com/HabitRPG/habitrpg/issues/2789
