### ISSUE TITLE
Cannot end challenge (or edit)

### ISSUE THREAD

**Issue by Kite12** [HabitRPG/habitica#3182]
As "Kite" I created the challenge "Making your bed keeps your room clean" I am trying to end it, picking a winner and clicking confirm. It loads for a bit and then comes up with this. 
![untitled](https://cloud.githubusercontent.com/assets/7111649/2563716/6f5fc734-b888-11e3-8e63-4422c55166c4.jpg)
The message: "Please reload, "Error Request entity too large" (see Chrome console for more details)."
I then tried to edit the challenge to let people know that I can't end it and it came up with the same error message without saving the changes.

I tied to search the forum to see if anybody had already lodged this glitch but could not find one, I apologise if I just did not search well enough.

**Comment by deilann** [comment]
Yeah, this is a known bug. Next time, try searching the Github repo instead
(you can search issue tickets as well as the code). A lot of the known bugs
are on the forums, but many of them aren't. If I have a moment, I'll go
find you the right ticket. :)

**Comment by Kite12** [comment]
Would you like me to delete this then? Can I physically delete it?

**Comment by deilann** [comment]
No, no. You can't actually delete issue tickets anyway. You can close them,
but I want to make sure you find the right ticket, as it has some tips on
how to deal with the issue.

**Comment by Kite12** [comment]
Thanks.

**Comment by deilann** [comment]
No problem! If you find it before me, though, kudos. ;) I got a bit more do
to before I can issue search.

**Comment by denis-sokolov** [comment]
I think you're talking about #1471.

**Comment by deilann** [comment]
More specifically https://github.com/HabitRPG/habitrpg/issues/2877

Thank you @denis-sokolov !
