### ISSUE TITLE
Blank notifacation.

### ISSUE THREAD

**Issue by DimTwin** [HabitRPG/habitica#3183]
My ID: 91ab86a8-6fb0-4be4-8eeb-7f6b96aef698

Every time I use the health potion I get this blank notification. Nothing critical, the potion works just fine. But it's a kinda annoying.
![1](https://cloud.githubusercontent.com/assets/6949144/2564433/27869d80-b8a0-11e3-9396-1c0ec2683bf6.png)

**Comment by federeghe** [comment]
Confirmed, me too.

**Comment by phillipthelen** [comment]
this also seems resolved, according to the PR

**Comment by paglias** [comment]
Mmm the PR here "hide" the problem, the blank notification is always generated just not shown
