### ISSUE TITLE
Cannot permanently join party

### ISSUE THREAD

**Issue by scrauder** [HabitRPG/habitica#3188]
When invited to a party, I click accept, and am shown the party screen. But when I click to another tab and then click back I have to click accept again. After about three times, the buttons are no longer offered and it says I am not currently in a party. This has now happened twice in two different parties.

**Comment by scrauder** [comment]
Addendum: Once someone commented in the chat in the party I was brought into the party and now have party members showing at the top of the screen. The problem seems to have fixed itself.

**Comment by deilann** [comment]
That's likely either the site or your internet being slow.

Okay, here's what happens:

You never left the party.

The thing that loads default is the "You're not in a party page." Then the
party page renders on top of it. So if it gets interrupted or you don't
wait long enough or the moon doesn't align correctly, it'll look like
you're not in a party when you are. Just refresh the page and try again. It
should show up like normal.
