### ISSUE TITLE
Just rebirthed, can still access market/equipment/pets/ect through task bar

### ISSUE THREAD

**Issue by cecilyperez** [HabitRPG/habitica#3189]
Here's a screenshot:

![screen shot 2014-04-01 at 12 25 21 am](https://cloud.githubusercontent.com/assets/3329995/2575570/d7877a14-b955-11e3-9c81-69c7ab501dfc.png)

As you can see, while the option is not available in the usual nested tabs, I can still get to one of the screens through the task bar and then go through them like normal. I can select mounts and pets, and repurchased equipment looks equipped on the page though obviously I can't see it on my avatar right now...

**Comment by cecilyperez** [comment]
Also, I still have all my (considerable amount of easily converted into lots of gold) drops, don't know if that's intended or not though?

**Comment by deilann** [comment]
The toolbar thing isn't just a thing about rebirthed users-- it's actually
showing up for level 1 new users as well.

The drops are intended. There's no way for habit to tell if you paid gems
for them or not.
