### ISSUE TITLE
[Feature] [maybe way down the track] Other role-playing premises.

### ISSUE THREAD

**Issue by Yughurt** [HabitRPG/habitica#319]
For some, the whole 8 bit character getting gold and equips isn't the premise that everyone would like. As such you could slowly create new premises.

Eg. Town: You're a villager in a town working for a far away king looking to make your way to the top of the social hierarchy. By doing many different tasks which "help the towns people" which leads to your popularity and lets you get promotions. This is a different sort of level progression which you have more attachment to. If you neglect your job, you will be demoted. etc.

Lord/King mode: You have to look after your lands (tasks). Can get attacked by different unchecked "kingdoms" (must complete this recently neglected task or your city can get taken over and you have to work to get it back, etc)

Knights, warriors (Jedi? :D): Obvious different sort of progression.

Yes it would be difficult, but perhaps even a scenario creation mode where you create elements and put it together yourself and share with others? but perhaps also a way to monetise the system without it impeding? Sell scenarios? Anyway maybe you're not into that but I would definitely pay to get a cool setting.

**Comment by wc8** [comment]
Similar to or enhancement of #164 a request for a greenhouse or farming "scenario"/genre?

**Comment by Yughurt** [comment]
Sort of except not a direct translation. Have the progression a different way. Getting levels may not be a great motivator for some. I'd prefer personally to work towards something more tangible like a position in society.

**Comment by horusofoz** [comment]
Please direct discussion to [Trello Card 101](https://trello.com/c/EKxy5lYI).
