### ISSUE TITLE
To-Dos rearrange themselves upon refresh

### ISSUE THREAD

**Issue by noidexe** [HabitRPG/habitica#3192]
UID: 5fb3f867-844c-40d0-be2c-6a6ecd3ca899

I sort some to-dos in the list, always getting `POST https://habitrpg.com/api/v2/user/batch-update [HTTP/1.1 200 OK 359ms]` in the console. However, when I refresh the site the to-dos are in a different order. This doesn't happen with dailies or habits.

**Comment by deilann** [comment]
check out: https://github.com/HabitRPG/habitrpg/issues/2606

Clear you completed to dos and it should all be good.
