### ISSUE TITLE
Clean checkout of environment is broken.

### ISSUE THREAD

**Issue by edgarjcfn** [HabitRPG/habitica#3193]
By following the instructions on the README.md, it's not possible to properly setup a dev environment. 
### Steps to Reproduce

1- Clone a clean checkout of HabitRPG
2- Follow the instructions on README.md
3- Run HabitRPG locally
4- Visit `localhost:3000` and click "Play"
### Expected behaviour

After seeing the static front page, the user should be able to click "Play" and be redirected to the Login Dialog or ultimately be redirected to `localhost:3000/#/tasks`
### Actual behaviour
- The user is instead redirected to `localhost:3000/static/front#/tasks`
- There's also an ouputted error in the Console:
  `Failed to load resource: the server responded with a status of 401 (Unauthorized) http://localhost:3000/api/v2/user/batch-update?_v=0&data=1396386985089&siteVersion=1`
### Additional information
- Executing `node src/seed.js` is outputing what seems to be debug information. It finishes with the message `info: Done initializing database` but after that, the habitrpg database only has one collection called "groups"
- Trying to download the Vagrant Box is giving a 404. It appears the Vagrant box is not hosted on Dropbox anymore.

**Comment by thepeopleseason** [comment]
Can you confirm that the url of the Vagrant box is in the Vagrantfile?  "http://dl.dropboxusercontent.com/u/4309797/devel/habitrpg/habitrpg.box"

**Comment by raymondcascella** [comment]
Hey, edgarjcfn, this is Mundo from IRC. I think I figured it out! =-D 

The database is ready, but completely empty. You just have to register a brand new user. The instructions don't exactly say that, and in my opinion, they really, really should. 

It's confusing when you see that the database is being seeded. The expectation is that I'd get some sort of base system, with some users and what not. Then the instructions also talk about just going to settings and getting your user ID, which you cannot do because a users doesn't even exist yet. It mentions "test user" but that's all, it never mentions that you are the one who creates the user!

**Comment by deilann** [comment]
Yes, you are going to have to register users. :)

**Comment by raymondcascella** [comment]
I am simultaneously shamed and thrilled at the simplicity of the answer. But hey, she's purring like a kitten now. Time to dive in. =-D

**Comment by edgarjcfn** [comment]
Hey guys, as described in the issue, I cannot register a player because clicking the "Play" button doesn't show me the login/register dialog. 

Did you have a similar issue? How did you register a player?

**Comment by edgarjcfn** [comment]
Also, the URL of the Vagrant Box is wrong in Vagrant.md (it says "package.box" instead of "habitrpg.box"). I'll try to run with the correct box later today.

**Comment by deilann** [comment]
So, if clicking the button doesn't show you the login/register dialog, it
seems to think you're already logged in. (If you're logged in, that
redirect is what happens on the main site.)

**Comment by thepeopleseason** [comment]
@edgarjcfn Regarding the vagrant box, make sure you've pulled and rebased from upstream, because there's an updated Vagrantfile, and VAGRANT.md has updated instructions.

**Comment by edgarjcfn** [comment]
Ok, apparently the weird behaviour was caused because I had successfully created a user in a previous version of HabitRPG and after pulling again from upstream, my cookies were still saved with an older format (probably that's why it was calling `/user/batch-update`.

So, in short, clearing the cookies solved it for me :)

Thanks for the help! :+1:
