### ISSUE TITLE
Backstab allows over XP

### ISSUE THREAD

**Issue by justdiver** [HabitRPG/habitica#3194]
Using backstab on a task can allow you to gain more than the XP required to level.  For example, if I have 999/1000 for a level, and backstab grants me 100, it will show 1099/1000 and not grant the level until another task (not backstab) is performed.

**Comment by deilann** [comment]
Yes, this is known. In the future, please search. We've had an extraordinary number of these tickets. The master ticket doesn't mention backstab, but if you look at closed tickets about this, it refers to that master ticket. Which is... #2143
