### ISSUE TITLE
March Mystery Item

### ISSUE THREAD

**Issue by clockworkkitten** [HabitRPG/habitica#3195]
### Fixed

I subscribed on the 31st in order to nab the Forest Walker set, and while the mystery box appeared in my inventory, it was empty. I tried multiple resets, refreshes, etc, to no avail. Did I subscribe too late or was this simply a glitch?

85fc0b29-b027-4ea4-9a2a-76d043a7d02c

**Comment by deilann** [comment]
Just a heads up @clockworkkitten! @lefnire is the one who would handle this, but he's on vacation this week. However, I'm positive he'll sort it out!

**Comment by clockworkkitten** [comment]
@deilann Alright, thank you!

**Comment by deilann** [comment]
### Fixed

User on referenced ticket is UUID a0bf8cea-bd9e-4c9d-bba4-97673e190c57

**Comment by lefnire** [comment]
@clockworkkitten @eternalearth888 check your boxes now, should be √

**Comment by wc8** [comment]
Should we close this, or leave it open for debugging?

**Comment by eternalearth888** [comment]
I think we should leave it open until we see what happens with the April
mystery items.

**Comment by Alys** [comment]
Fixed, no further reports.
