### ISSUE TITLE
Quest: Vice Awakens; Cannot join

### ISSUE THREAD

**Issue by bennau** [HabitRPG/habitica#3196]
For some reason I cannot join the Vice Awakens Quest. I'm in a party and have been invited, but am not able to deal damage to the boss. However I can see the status of the quest and the damage dealt by other party members. It is not possible for other party members to invite me again. Suggestions anyone?

**Comment by deilann** [comment]
Did you join the party after the quest has started? How many days has this been going on?

**Comment by bennau** [comment]
No, I was already member of the party for a long time then. It goes on for 8 days now.

**Comment by deilann** [comment]
It sounds like the quest was started before you accepted. Once a quest has started, you can't add new people to it. The only way you could join in is if they don't force start the quest before you have a chance to join.

The good news is that you don't have to complete Vice Awakens to do the subsequent quests. Just make sure that your friends don't force start the next quests without you!

**Comment by bennau** [comment]
okay. many thanks for your answer :)

**Comment by deilann** [comment]
Not a problem!
