### ISSUE TITLE
Subscribed and did not recieve gift

### ISSUE THREAD

**Issue by eternalearth888** [HabitRPG/habitica#3197]
To whom this may concern:
I subscribed before the end of March so I could get the Forest Walker Set but I never received the set, even when I clicked the present in the market. The present simply said 0.

Now that April has started, I went to the market to grab the present but it won't let me click on it. Is this a bug/is there any way I can get the Forest Walker Set and get the April Gift box?

**Comment by deilann** [comment]
Can you move this over here? https://github.com/HabitRPG/habitrpg/issues/3195

Like that thread states, Tyler will take care of it, but he's on vacashun. Also, you'll need to give him your UUID, which you'll be able to find in Settings > API

**Comment by eternalearth888** [comment]
Hello,

My UUID is : a0bf8cea-bd9e-4c9d-bba4-97673e190c57

I will wait. I just wanted to bring the issue up because I didn't recognize
it already had and so when it is taken care of I can get my mystery gifts.

Thank you very much for your patience.

Maria

**Comment by deilann** [comment]
Hey @eternalearth888 I'm trying to make a master ticket for these. :) I've added your UUID to the ticket I referenced, but you won't get notifs that it's updated unless you go subscribe to that ticket or post in it.

**Comment by eternalearth888** [comment]
Thank you for letting me know. I will subscribe soon.
