### ISSUE TITLE
Invite / Notification keeps re-appearing even though already Rejected

### ISSUE THREAD

**Issue by LB7979** [HabitRPG/habitica#3199]
Even though I clicked on 'Reject' for an Invite to  a Guild, the Notification Icon for this Invite keeps re-appearing when I refresh the page or sync. Even if I Reject the invite again, the invite keeps re-appearing. Logging out and back in did not work either.

**Comment by deilann** [comment]
I think there's another ticket for this (will look it up in a bit) but the solution at the moment is to join the guild then immediately leave it.

**Comment by LB7979** [comment]
Thank you, and that worked!
Not intuitive though, that the Reject button doesn't function, so I hope someone can look over this...

**Comment by deilann** [comment]
Yeah.... I think there's another ticket. If you find it first, awesome, but
if not, I'll find it and let you know.

**Comment by deilann** [comment]
Oh you found it. Way to go. XD
