### ISSUE TITLE
Text wrapping issue in Titles and Descriptions

### ISSUE THREAD

**Issue by jonathanbron** [HabitRPG/habitica#32]
I am noticing that text is being wrapped within item titles and descriptions - normally this would not be a problem, but it is wrapping individual characters as opposed to entire words. Screenshots attached.
![image](https://f.cloud.github.com/assets/3172327/39320/5f6ee438-5522-11e2-80cb-30687d5912f0.png)
![image](https://f.cloud.github.com/assets/3172327/39324/b2cd0c90-5522-11e2-8a5c-545ae12e9206.png)

**Comment by lefnire** [comment]
Yeah, it didn't used to be that way - used to break on word. An update to [Bootstrap popovers](http://twitter.github.com/bootstrap/javascript.html#popovers) later caused this. I'll investigate again, it's probably just a configuration paramater

**Comment by horusofoz** [comment]
@lefnire Did this turn out to be a parameter setting or something more serious?

**Comment by lefnire** [comment]
paramater setting, i merged @teekirol's pull request and this should be fixed with the next deploy

**Comment by horusofoz** [comment]
Resolved.
