### ISSUE TITLE
valid username says "username not registered"; party bug

### ISSUE THREAD

**Issue by godheadcomplex** [HabitRPG/habitica#320]
When I type in my username to log in, it says "username not registered"; it does, however, let me successfully log in regardless. Was I supposed to get some sort of confirmation email? I've been checking for the past hour now.

I tried to set up a party with friends but got caught in the middle of a server overload. When the site returned to normal, I couldn't access the menu I had been using to set up a party any more (the pop up that comes from clicking on the username doesn't happen any more - clicking on the name does nothing).

I've been using Chrome, but I tried to access these features on Firefox too just now, to no avail.

**Comment by lefnire** [comment]
woo, those are some solid bugs!
- username bug - looking into. there's no confirmation email, yet to be built in [derby-auth](https://github.com/lefnire/derby-auth)
- the server overload is my most pertinent bug right now. for some reason, mongo goes haywire sometimes with 500 reads/s causing a connection timeout from the server. Same amount of visitors, I think it's a model subscription not terminated properly or something.
- party issue - you're level 3+ ? Hmm.. looking into

**Comment by Pandoro** [comment]
Any news on this front :x ?

**Comment by lefnire** [comment]
@godheadcomplex, can you not get in still? Confirmation email: https://github.com/lefnire/derby-auth/issues/21

**Comment by lefnire** [comment]
Ok, most of these should be fixed now. If not re-open
