### ISSUE TITLE
API: Low-priority "sort" issues.

### ISSUE THREAD

**Issue by black-orchid** [HabitRPG/habitica#3200]
It's me again - the only person using the sort API. ;-)  

This is so silly I feel embarrassed to post it, but I guess it's technically a bug.  If I run this:

curl -X POST -H "x-api-user: USER" -H "x-api-key: KEY" "https://habitrpg.com/api/v2/user/tasks/f4285a70-4dce-4c5b-a099-c640b165c27d/sort?from=x&to=0"

and x is greater than the number of tasks I have, it appears an empty task will be inserted at index 0.

Additionally, if x is a valid index but not the index of the indicated task, whatever task was at index x will be moved to index 0.  This may be the intended behavior - I'm not sure.  For my purposes, it would be more useful for the indicated task to be moved from whatever its current index is to the index indicated by "to," as discovering the current index is more labor-intensive; but my preferences really shouldn't figure centrally.
##

**Comment by paglias** [comment]
@black-orchid thanks a lot! keep this issues coming they are really useful!

I'll fix it in the following days

**Comment by black-orchid** [comment]
@paglias, do you know if there's a way to assign tags to a new task upon creation?  I tried the "post" syntax a couple different ways and couldn't come up with it. Thanks!

**Comment by crookedneighbor** [comment]
@paglias Did this ever get fixed? Or was this v1 of the api?

**Comment by paglias** [comment]
Fixed in v3
