### ISSUE TITLE
Stats are not applied

### ISSUE THREAD

**Issue by DMcGeeX** [HabitRPG/habitica#3202]
Hi. I am DMcGeeX and I was having problems with my stats not being applied. I am a lvl 33 rogue. Every time I check off my tasks I get about 1 gold and 16 exp. I tried resetting my class to see if that would fix the problem, but it did not. If someone could me I would be appreciative.

**Comment by deilann** [comment]
What is your PER and what happens if you check off a freshly made To-Do?

**Comment by DMcGeeX** [comment]
My PER is 25 and I got 1 gold 50 silver and 9 exp For checking off a freshly made To-DO. I am a warrior I still need to change back.

**Comment by deilann** [comment]
Okay, it doesn't seem like your stats aren't being applied... but that your
dailies are all the same value. As you do them, they get slightly less
valuable.

**Comment by Alys** [comment]
I believe this has been resolved by deilann's explanation. Closing.
