### ISSUE TITLE
Translating HabitRPG

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3203]
Hi! I have been using HabitRPG for quite some time and I love it! I love it so much I have infected almost all my friends with it :) Even some of my students would like to use it! But they are often put off by the site being only in English. Would you guys be interested in translating it? I could provide translation to Czech and maybe German and I am sure that some users would try to translate into their languages as well!

**Comment by paglias** [comment]
hi @Miisa  !

Currentluy HabitRPG is avalaible in sevaral languages and while some parts are still not translated (some parts of the static pages and more or less all the items avalaible through the game) we're in the process of making the whole site avalaible for translation.

The languages currently avalaible are these:

![selezione_050](https://cloud.githubusercontent.com/assets/589911/2605112/49bbf974-bb41-11e3-83b9-9024823212d5.png)

If your system language is one of those it should be automatically used on the site (if it isn't let me know)

Translations are managed on Transifex https://www.transifex.com/projects/p/habitrpg/, if you want to contribute it would be really appreciated. For more info see this Trello card https://trello.com/c/SvTsLdRF/12-translations

If you have any more question I'll be happy to help you :)
