### ISSUE TITLE
Can't Add New Tasks

### ISSUE THREAD

**Issue by randomhobo** [HabitRPG/habitica#3204]
I haven't been able to add anything new to my Habits, Dailies, To-Dos, or rewards for weeks now.

**Comment by casicastiel** [comment]
How so? Are you adding the tasks but they don't stay, or can you not add them in the first place? When you type in the 'New Daily' (Habit, To-do, etc) field and click +, what happens?

**Comment by negue** [comment]
@randomhobo Do you still can't add anything?

Can you provide any javascript console output?
