### ISSUE TITLE
Tasks didn't refresh but I still received damage

### ISSUE THREAD

**Issue by kyoki** [HabitRPG/habitica#3206]
I have a custom rollover time of 6AM, and because of this (I assume), sometimes my task list doesn't refresh. Not really a big deal. For some reason, though, when my tasks didn't rollover yesterday, my party and I still took a bunch of damage for tasks that had been checked off the day before. This is mostly an issue because it ended up killing everyone in the party :(

**Comment by crookedneighbor** [comment]
Sorry we never responded to this. This sounds like sync error. If you're still having issues, there's advice how to deal with it in this issue: https://github.com/HabitRPG/habitrpg/issues/4313
