### ISSUE TITLE
Got stuck in death loop

### ISSUE THREAD

**Issue by Cjdudebro** [HabitRPG/habitica#3208]
Unsure if this bug was caused by habit or the app I use (habit Android). I became stuck in a death loop when I leveled up, and have lost 4 levels as a result. There is no apparent reason for the first death as I had hp and hadn't received any quest damage for a number of days. I closed the app when I realised that it was continually murdering my poor character

**Comment by negue** [comment]
If this is still happening could you post your UserID?

**Comment by Alys** [comment]
Closing but we can reopen if it's still happening.
