### ISSUE TITLE
march item not recieved

### ISSUE THREAD

**Issue by sodawizard** [HabitRPG/habitica#3211]
Hello,

I subscribed to HabitRPG around 9pm PDT on March 31st, and my mystery gift box did not contain the item. I contacted Mihakuu on twitter and was told to make a ticket here. My UUID is "sodawizard"

Thank you!

**Comment by deilann** [comment]
UUID is an alphanumeric string, not your display name. You can find it in
the API section.

Also, I'm gonna guess that Habit is in Eastern time -- so it was no longer
March 31st there. But I bet @lefnire will still take care of this. :)

**Comment by lefnire** [comment]
@sodawizard all set
