### ISSUE TITLE
February Item still not recieved

### ISSUE THREAD

**Issue by LadyDreamgirl** [HabitRPG/habitica#3212]
I subscribed the very last day of February, and I've just checked the credit card records to confirm that a payment was made on Feb 28th, but I still haven't received the February subscription item. I had seen other reports of a similar problem so I thought my issue would be resolved when theirs were dealt with, but since the February item hasn't shown up yet but the March one has, I wanted to see if there is anything that can be done about it.

**Comment by Mihakuu** [comment]
We need your UUID 
Options>Settings>API 
cut and paste that User ID into this ticket

**Comment by deilann** [comment]
NO -- NOT the API Token. Do not share your API Token publicly.

But please do paste the UUID.

**Comment by Mihakuu** [comment]
Ah I'm sorry I got distracted and looked at the wrong thing. TT~TT I shouldn't  try to help

**Comment by deilann** [comment]
No, helping is good. <3

**Comment by LadyDreamgirl** [comment]
Ok, so my user id is: 7c93e9b8-8c55-4d24-8d63-8bcf1e161b1d
Sorry it took me so long to get it posted. Hope this helps resolve things.

**Comment by Alys** [comment]
@LadyDreamgirl, I'm so sorry, we never fixed this up for you! I've given you the items now. Check your inventory and you should see them there. You might need to reload first using your browser's refresh button. If you're not sure what they should look like, you can see the in the wiki's [Mystery Item](http://habitrpg.wikia.com/wiki/Mystery_Item) page - it's the Winged Messenger Set. 

I'm closing this job now, but if they don't show up, DEFINITELY comment here and I"ll reopen it and fix the problem!
