### ISSUE TITLE
Random, unexplainable deaths

### ISSUE THREAD

**Issue by phedg1** [HabitRPG/habitica#3213]
Hello HabitRPG. This is my first series of bug encounters whilst playing HabitRPG and I would dearly like them fixed. What has been happening, and 3 times total now, is my character has been experiencing random and unexplainable deaths. Each time this has acoured it has been during the very first habit clicks of the day. I have been on the Dragon quest, part 3 and I have only been clicking positive habits only. My character has gone from 40-50 health down to being dead instantly. I have checked in the party chat to see if anyone forgot to do any dailies and it's only ever small amounts of damage, 5 across the whole party max. 

Weirdly enough, this glitch has been occuring during the one same quest and I still have not been kicked out of the quest and my daily streaks are still intact (so it wasn't daily damage I have been taking, clearly). The most recent time this happened, yesterday morning, I died twice within a couple of seconds. I clicked a positive habit about 3 times and died twice.

As well as asking for this bug to please be fixed, is there any way I can get the 5 levels I have lost back as well as the gold and items? I have been playing rather competitively with my friends in my party and I am just way out of their league now that I've been taken back about 3 levels, lost about another 2 levels worth of experience and lots and lots of gold.

**Comment by deilann** [comment]
Yes, there is a way you can get your stuff back! Go to Settings > Site >
Fix Character Values.

Also, dying does not currently do anything to quests.
