### ISSUE TITLE
To-Do Treated Like a Daily

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3214]
Searched around a bit for this, but wasn't sure exactly what to call it, so hopefully this isn't a duplicate....

I noticed that a To-Do that I thought I had clicked kept showing up again. Today, I clicked it to complete it.... and it turned green. I clicked it again, and it turned yellow and subtracted the gold/XP it had granted me. I clicked it repeatedly, and it swapped between green and yellow like that. Eventually, I deleted it.
![screen shot 2014-04-05 at 8 33 22 pm](https://cloud.githubusercontent.com/assets/3494081/2624445/7da209ce-bd3d-11e3-99ee-7740ad4bd6ce.png)

**Comment by larouxn** [comment]
Is this the first time this has happened? Do you have any idea of how to reproduce it?

**Comment by lemoness** [comment]
It is the first time it has happened (a very recently added To-Do) - so
certainly not a high priority issue - and thus far, I have not been able to
reproduce it :/ We can leave the issue open in case anyone else starts
seeing this, but unless that happens, I don't think it needs extensive
investigation.

**Comment by larouxn** [comment]
Gotcha. Sounds like a plan.
