### ISSUE TITLE
Interface bug: tooltips go off the screen (Costume / Sync / etc)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3215]
Popup notification for the top bar sync button get out of screen to the right for interface languages which have more than 10 symbols in the equivalent word for sync.
http://oi58.tinypic.com/2mhv2o5.jpg

**Comment by deilann** [comment]
I'm not sure what can really be done about that. It's known that (it's not
just an issue of the languages -- some English tooltips get cut off) some
of the tooltips go off the screen, but what is the best direction to put
them in? How can we make them more responsive?

(The answer is definitely not going to come from me. :P)

**Comment by ghost** [comment]
@deilann 
Now I see that the problem is really bigger.
See the costume column:
http://i61.tinypic.com/2n9geq0.jpg
notifications for the far right items can not be read.
The possible workaround may be to make notification popup to the right or to the left depending on what part of the screen they should be. Manually, just as it's implemented in the market section.
http://i61.tinypic.com/o5dc9h.jpg
BTW the tooltip for the most right item shouldn't be narrowed in such a way if its not the screen border, but just a column.

**Comment by deilann** [comment]
Yeah. I'm not sure how front end stuff like that works, though. We'd have
to get one of the CSS folks in here.

**Comment by ghost** [comment]
I've just noticed that tooltip to the right creates horizontal scrolling bar.
http://oi59.tinypic.com/5vvupz.jpg
1. Page as is. 2. Mouseover on item. 3. Scroll to the right reveals the tooltip. 4. (Immediately after 3) "Mouse focus" lost, tooltip and scrolling bar disappear => 1.
I'm not sure It was really meant to be like that.

**Comment by deilann** [comment]
Yeah, I'm pretty sure there's a master ticket about this, btw.

**Comment by ghost** [comment]
I haven't found that one before, sorry. So this issue can really be merged with:
https://github.com/HabitRPG/habitrpg/issues/2822

> we just have to pick a side to display it on

Suggestions:
1a. Top bar Sync button needs tooltip to the left,
1b as well as items in costume column.
1c Difficulty tooltip in Habits needs a tooltip to the right.
2. Free space between the in-game items and the right border of the screen might be made bigger to avoid horizontal scrolling.

**Comment by deilann** [comment]
Yeah, let's take it there. :thumbsup:
