### ISSUE TITLE
Pet Feed Bar doesn't show up in IE

### ISSUE THREAD

**Issue by valrus** [HabitRPG/habitica#3218]
See image. I just hatched a tiger and it doesn't have a food meter in my stable.

![image](https://cloud.githubusercontent.com/assets/343665/2627569/0c78263c-be0c-11e3-9cf3-26ee1f9da28f.jpg)

**Comment by deilann** [comment]
Do you have a tiger mount?

**Comment by valrus** [comment]
Nope. I don't have any mounts.

**Comment by deilann** [comment]
Interesting. That's how it shows if you own the mount of a pet. What's your UUID?

**Comment by valrus** [comment]
42b8a8bb-80bb-4547-a9a1-36a5e4a8c9b4

**Comment by deilann** [comment]
Awesome. If someone has database access, and could look into if something
wonky's going on, that would be awesome. However, @valrus, I'm going to
give you a gem. I'd like you to purchase a meat with it and try to feed it
to your glitch!Tiger. Lemme know what happens. :)

**Comment by valrus** [comment]
Thanks a lot, @deilann. Now I have negative three gems. :)
![image](https://cloud.githubusercontent.com/assets/343665/2639583/b463e342-becd-11e3-8e00-6a62be8a4b30.jpg)

I didn't buy any meat, or anything else. When I logged in today the above screenshot was what I saw.

**Comment by deilann** [comment]
Whoops. That would be because I accidentally gave you -3 gems instead of 1.
:P How's that?

**Comment by valrus** [comment]
Soooooo I went to go buy the meat and give it to the tiger, and magically it had a meter again! Before I even _gave_ it the meat!

Then I turned my tablet back to portrait mode, and it no longer had a meter. Then I turned it back to landscape mode, and it had a meter again. Perhaps this will be of some use to you in getting a repro? :)

**Comment by deilann** [comment]
Huh! Interesting. And it's just the tiger?

**Comment by valrus** [comment]
Yep, definitely just the tiger.

**Comment by nihongineer** [comment]
Wonder if my problem is related.  I have a wolf and a fox, both have bars technically but after feeding them three times it has no green progress at all.  Could it be the same problem or maybe a new issue?

ID: dfb3571b-fe0b-4e70-817f-b21f30993298

**Comment by deilann** [comment]
Are you using Internet Explorer?

**Comment by nihongineer** [comment]
Yes, I used FireFox first but switched to IE recently.

Edit: Logged off IE and back in on FireFox, the feed bars are updated there no problem.  Just doesn't show when I'm in IE.

**Comment by deilann** [comment]
IE doesn't play well with Habit. The most obvious bug is that on IE, the
progress bars for pets will never display any progress. The good news is,
that progress is saving to the server. Just not displaying.

**Comment by nihongineer** [comment]
Awesome news, I'll put a check in my "happy camper" box and be on my way then.

**Comment by crookedneighbor** [comment]
(Hopefully) closed with https://github.com/HabitRPG/habitrpg/pull/5614
