### ISSUE TITLE
Sudden death happened twice

### ISSUE THREAD

**Issue by pocketwise** [HabitRPG/habitica#3219]
At level 10 I encountered sudden death twice when I refresh the webpage. My health was full or near full, but when I refresh the page within 24 hrs I received the death notice and lost the level.

**Comment by Alys** [comment]
@pocketwise I'm so sorry we never got back to you about this! Unfortunately we can't tell what went wrong, but if anything like this happens again, please tell us and we'll try to work out what caused it.
