### ISSUE TITLE
500-1K Mongo queries/second bug

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#322]
Sometimes (still haven't figured out what triggers it) Mongo goes haywire. All reads, no writes, but about 500-1K /second, causing connection loss and the "forever loading" issue. I _think_ it's on server restart (which happens on cron every 2hrs to kill memory leaks, now that session reconnection works), but I'll need to do some load testing locally. I also _think_ it has something to do with the multiple subscriptions that are setup. There are 3 subscriptions to racer queries: `model.query('users').withId(id)`, `model.query('parties').withId(id)`, `model.query('users').party(ids)`. They are all 3 of them re-upped from time to time (based on party actions, such as leaving, inviting, etc). All this subscription-handling may be causing craziness.

**Comment by HarmonRook** [comment]
This sounds like what has been happening to me all day. It loads, and after a second or two re-loads, and keeps doing it indefinitely. I don't have time to click on anything (I tried scrolling down to click on "Bugs" at the bottom of the page, but it kept reloading before I had a chance, and I had to find the link on the Kickstarter page instead). It's been doing it for about the last six hours, I'd say?

**Comment by lefnire** [comment]
Wow! 6 hours, right when I launched parties. Are you in a party?

**Comment by HarmonRook** [comment]
No - I hit level 3 yesterday, and today when I marked my first box, it said "You've unlocked the party system!" then reloaded itself. And ever since then, it just reloads itself over and over. Just now I managed to check a box before it reloaded, and I got the same "You've unlocked the party system" notification and it just keeps reloading. I haven't had a chance to form a party.

**Comment by lefnire** [comment]
Gnarly. [Email me](mailto:tylerrenelle@gmail.com) your uuid, I wanna check something. or email / username you signed up with

**Comment by lefnire** [comment]
So after a conversation with @HarmonRook, turns out hers was an IE issue. Maybe we should put a notification for IE users to use Chrome instead. For the record, Derby just doesn't work in IE - though they're planning on fixing that. 

This database issue definitely triggered on restart, I've confirmed that. It usually lasts about 5-10 minutes, which sucks. If any coders are following this thread, I'm pretty sure it has something to do with the `model.subscribe`s that are setup (see original description above)

**Comment by wc8** [comment]
@lefnire sounds like a good addition to the FAQ under best browsers. I would include the note about Derby working on compatibility with IE.

**Comment by lefnire** [comment]
Added, thanks

**Comment by lefnire** [comment]
@switz the mongo wig-out ticket

**Comment by lefnire** [comment]
Definitely only on restart, and only when the memory is already maxed out. Hopefully now that #165 is (I think) fixed, this should go away. I'll keep an eye on both over coming days

**Comment by switz** [comment]
Hm, that's interesting. Let me know what you find.

**Comment by lefnire** [comment]
Didn't fix it :( Restarts sill cause crazy-ness. Like everyone's trying to
re-establish their model subscriptions but nobody can

**Comment by switz** [comment]
That sounds about right. We'll have to figure out some way to slowly allow people to reconnect. Maybe on server restart, we should send a notification to the client saying, "If nothing has been updated, just refresh the page" – it might stop Racer from trying to sync with all of the clients.

**Comment by lefnire** [comment]
I'm going to keep an eye on SLaks/racer, he seems to be really on top of this stuff. https://github.com/SLaks/racer/commit/fdbbff8f9291cb635c28ddc8306e5c346c766626 fro example looks like it might be in this realm.

**Comment by lefnire** [comment]
This doesn't seem so much a problem anymore, #413 hits us instead

**Comment by safarijacksa** [comment]
Hey Tyler and co,

Is this still an issue? If so can you not set a minimum wait time before the server accepts a refresh request? So if it gets stuck in the loop where it tries to refresh every second or less then it is forced to wait 5 seconds if the same IP/user tries again to repeatedly access a 10 second wait is implemented and so on.

If you can do this then you should be able to 
a) Improve the stability of the server
b) Slow down the rate of failure to investigate what exactly is going on,

**Comment by lefnire** [comment]
seems fixed presently, will revisit
