### ISSUE TITLE
April Mystery Item 'Empty'

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#3220]
I've seen this has been a little bit of an issue for some new members (like myself), but the mystery item for April is in my inventory but it is 'empty', and the little number on the side is 0, despite me not having gotten anything from it.

My User ID:  d62e990b-d300-46cf-9dc5-bc99d122ac36

**Comment by deilann** [comment]
April Mystery Item will not be revealed until closer to the end of the month, just like the March item. :)
