### ISSUE TITLE
April Mystery Item 'Empty'

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#3222]
I've seen that this has been somewhat of an issue for new members, but while I have received the little box that should contain the mystery item, it keeps telling me that it is empty, despite the April mystery item not appearing (not in my inventory either) 

User ID: d62e990b-d300-46cf-9dc5-bc99d122ac36

**Comment by deilann** [comment]
The April mystery item will be revealed towards the end of the month, just like March.
