### ISSUE TITLE
Health, Experience, Mana bar: display precise amounts on mouseover

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3223]
Display a more precise amount, e.g. "Health 0.3" when  you mouseover a given statistics bar in the header.

**Comment by negue** [comment]
@wc8 @deilann Could you make an example of what should be added where? I kinda don't understand where this precise Health 0.3 should be visible, 

We already have `X / 50` HP, am I missing something?

**Comment by crookedneighbor** [comment]
@negue You can have part of a health point, so like 43.7/50, but the bar only shows the floored version, so 43/50. I think @wc8 wants a tooltip when you hover over the health bar to show you the exact amount of health you have.

**Comment by jdpopkin** [comment]
I took a shot at it in [this pull request](https://github.com/HabitRPG/habitrpg/pull/4476).

**Comment by Alys** [comment]
closed by https://github.com/HabitRPG/habitrpg/pull/4476
