### ISSUE TITLE
Streak Notifications Can Get Annoying

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3225]
Unplanned rebirth annoyance - lots of synchronized streaks. I used a rebirth orb 21 days ago, and most of my dailies are giving me streak notifications this morning. It's getting a bit old, particularly in the early morning when I check off a lot of dailies more or less at the same time. I'd like to be able to turn streak notifications off, or at least not need to click them to make them go away.

**Comment by deilann** [comment]
It's extremely annoying, especially as it slows down habit like whoa.

I vote turning the notifs into growls.

**Comment by casicastiel** [comment]
Seconded - after the first notification informing you of the badge, the rest are just irritating. The drop notifications don't take up the whole screen anymore; neither should these.

**Comment by deilann** [comment]
Maybe if user < 1 streak achievements modal else growl?

**Comment by phillipthelen** [comment]
This issue is also fixed with the pull request, referenced here.

**Comment by paglias** [comment]
@vIiRuS thanks, closing, for your own pull requests if you add in the commit message something like `fix #3225` it will also close the issue automatically. [More info](https://help.github.com/articles/closing-issues-via-commit-messages)

**Comment by phillipthelen** [comment]
@paglias i know. But I'm currently just going through all the issues, looking for some "low hanging fruit" and also noticed some already resolved issues, that are still open. And to make that "open issue" number less daunting, I thought I'd help out and notify about them. If it's annoying/there's a better way to notify, i can also do that.

**Comment by paglias** [comment]
@vIiRuS no no absolutely, it's really helpful. I just thought that it could be a useful info even though most of these PRs are not by you
