### ISSUE TITLE
Guild Members list ordering menu incorrectly labeled as "Party"

### ISSUE THREAD

**Issue by kbmartin** [HabitRPG/habitica#3227]
On the Guilds page, when I am in my Guild, in the Members box it says "Party members list ordering" and then has a dropdown menu where one of the choices is "Sort by Party date joined"

in both of those cases "Party" should be changed to "Guild."  We are bunch of noobs in our private guild and it's generating confusion about the difference between a guild and a party. 

My UUid is: 6f246e20-f6a3-4026-b8fd-e345b7ade91c
and the group ID is: c025515c-72b7-4250-b07a-7547e5329264

Thanks
kbm

**Comment by Alys** [comment]
This was fixed by removing the "Party members list ordering" section since it was not applicable to gvilds (it affects only the party member avatars in the header).
