### ISSUE TITLE
Boss damage doesn't add up

### ISSUE THREAD

**Issue by valrus** [HabitRPG/habitica#3229]
Based on the second of the two attached screenshots, the stag should have 1002 health left. As the first shot shows, it has more.
![image](https://cloud.githubusercontent.com/assets/343665/2639659/fca19670-becf-11e3-81d7-7efdf5ca1fdc.jpg)
![image](https://cloud.githubusercontent.com/assets/343665/2639660/011a26f4-bed0-11e3-9b46-35b01fcfa28f.jpg)

**Comment by valrus** [comment]
Note - I did try refreshing. It didn't change anything. At least one of my party members sees the same thing.

**Comment by deilann** [comment]
I'm guessing this is a variant on boss regenerating health issue; just it
happened early on and no one noticed it. It looks like it happened after
the first two attacks.

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/2657
