### ISSUE TITLE
died on new To-Dos

### ISSUE THREAD

**Issue by hovancik** [HabitRPG/habitica#3232]
so I created new todo: 
"-5 wakeuptime ;[]"

and it made me die upon creation.

I checked party and it's not because of that. my health was also not the issue.

**Comment by deilann** [comment]
Can you refresh party? Usually, the damage from party members isn't shown
until a refresh. Creating a new task will sync you with the server, so any
damage that's due will be applied.

**Comment by hovancik** [comment]
damage from party for last 24 hours was around 10. my health was around 50

**Comment by deilann** [comment]
Yes, I get that. I just want to know if refreshing shows damage you didn't
see before.

**Comment by hovancik** [comment]
Ah, that's what I mean, after refresh I counted damage from party and it was not issue

**Comment by Alys** [comment]
@hovancik I'm so sorry we never got back to you about this! Unfortunately we can't tell what went wrong, but if anything like this happens again, please tell us and we'll try to work out what caused it.
