### ISSUE TITLE
"Remove task" button is gone for tasks created by challenge

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3233]
Recycle bin button is gone for tasks created by a challenge.
Is that on purpose?
Of course there are ways to delete a task by leaving a challenge (you can choose not to keep all tasks, but anyways the tasks becomes removable as the recycle button appears) or when the challenge ends (from the task edit menu). Still it was more convenient to have a way to delete a task (and being asked if you want to leave the corresponding challenge) without additional moves.

**Comment by ghost** [comment]
Another user Hellika (685c9479-7b05-440b-8de4-d4f2850da6c7) reports she is completely unable to delete a daily after the challenge has ended:
http://screencast.com/t/71KcXCgyQm

**Comment by deilann** [comment]
That's an actual bug, generated from challenges with high number of members. The workaround at the moment is to click one of the tasks associated with the challenge. It will then update and know that the challenge is ended, so it can be deleted.

The recycle bin being gone for tasks created by challenges is in purpose. When the challenge ends, if the bug in question doesn't show, the megaphone will break and clicking on it will ask if you want to keep or discard tasks.

**Comment by ghost** [comment]
Thank you! The workaround is reported to work as you said. No need for this issue then if there is a master ticket.

**Comment by caveman1337** [comment]
I currently have the same problem, however clicking the megaphone, editing the item, etc. doesn't seem to trigger any dialogue. The challenge is completely missing from the challenges page (I'm pretty sure it ended), but I still can't delete the items. It doesn't seem to realize that the challenge is gone...

**Comment by deilann** [comment]
The workaround isn't to edit the item, but to actually check it off or
click one of the buttons on it.
