### ISSUE TITLE
Egg quest scroll not active

### ISSUE THREAD

**Issue by speakwithbread** [HabitRPG/habitica#3234]
Hi, I received the quest scroll that's supposedly for the Great Egg Hunt, but I get nothing when I click on it, so I can't activate it.  I'm already in a party, so that shouldn't be the problem.  Am I the only one with this bug?

**Comment by deilann** [comment]
Refresh. See if that helps.

**Comment by speakwithbread** [comment]
Huh.  Refreshing within the window didn't work, but refreshing the tab did.
 Sorry for not trying that earlier.  >.<  Thank you!

**Comment by deilann** [comment]
No problem! Your refreshing probably was a soft refresh, so it was still
loading the problematic cached data.
