### ISSUE TITLE
Daily completed twice

### ISSUE THREAD

**Issue by devenv** [HabitRPG/habitica#3235]
Completed a daily from the mobile app (unofficial), then forgot that I did and completed it again on the site.
I couldn't check it 100% but I'm pretty sure I got the experience and golds twice.
At least I saw the "growl" notifications twice and the streak was incremented +2.

On the same note it would be nice if the site would be updated without refreshing the page, which is one possible solution, but it's more of a feature request...

**Comment by deilann** [comment]
There is absolutely nothing we can do about the unofficial app. You're
going to have to take that up with MagicMickey.

The site can be updated without refreshing the page --- there's a sync
button on the toolbar just for that purpose.

**Comment by devenv** [comment]
The problem is not in the app, it just uses the API.
The problem is that there is a way to complete a daily twice...
For example if you open the site in different tabs and complete the same daily in each tab.

**Comment by deilann** [comment]
The app uses an outdated version of the API and has not been updated since
then. Because of that, odd functionality sometimes exists with it. Yes, the
ability to check a daily twice exists outside of the app, but it is not
uncommon for folks to ask us to troubleshoot third party problems, so I
always lay that out ASAP.

If you are using multiple devices, make sure to sync before checking off
tasks. You don't have to refresh to update the page, like I said. Just
click the sync button.

**Comment by devenv** [comment]
Thanks, I understood the workaround :)

Can't it be fixed by adding a condition at habitrpg-shared/dist/habitrpg-shared.js:12819
if (task.type != 'daily' || ((direction == 'up') != (task.completed))

Of course need to return some feedback to the user if there is no generic error or something...

P.S. I think there should be an open issue on refactoring that file :/

**Comment by deilann** [comment]
Yeah, I think that would be good. Want to submit a PR? Possibly a growl of
"Task already completed... do you use Habit on another device?" or
something if it's tried.

**Comment by paglias** [comment]
@devenv @deilann if you refresh the page it continues to show additional gold and experience?

**Comment by devenv** [comment]
I need to setup the env first, I'll see if there are no issues with this solution later...
BTW. Is there an issue with polling the server for changes once in a minute? Like pressing that refresh button automatically? Is it a server load issue?

**Comment by devenv** [comment]
@paglias Yes, it stays (and when you click uncomplete it reduces the values only once), I didn't see any place where this scenario is handled anyway so I doubt it suppose to work...

**Comment by paglias** [comment]
@devenv mmm... ok 

It works like this, when a request is sent to the server it is sent with a `_v` property, which is updated every time the user's object changes. So if you send a request with a _v lower than the one store on the server it means an operation has been done somewhere else and so the whole user is sent back to the server (but the operations are still executed so yes it may happen that a daily is checked twice) https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/auth.js#L27 and https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L442

**Comment by devenv** [comment]
@paglias Well, as far as I understood from poking around in the source the problem is that the logic happens actually on the client side and the result is sent to the server only after that. And the server is KISSed, saving what it gets into mongo...
The right solution would be to move the heavy logic to the server side, where it belongs :)
But feasible solutions:
1. refresh BEFORE the action, which means double requests, which sucks and doesn't really solve the problem actually.
2. don't allow actions if user model is dirty, with a refresh and some nice growl.
Second option suppose to be a quick one :)
Is there an issue with this approach?

BTW, I saw that that needs-to-be-refactored js file was a generated coffeescript, sorry :)
The coffeescript though needs-to-be-refactored too :)

**Comment by paglias** [comment]
@devenv if I remember correctly operations are duplicated: they are executed on the client to give immediate feedback to the user and sent to the server (as {op: 'sortTasks', params: {blabla}` where they are executed again and saved to the database

**Comment by devenv** [comment]
Hmmm... Both use the shared lib? When I added the condition I still managed to complete a daily twice from different tabs... May be I missed something, I'll try again...

**Comment by paglias** [comment]
yes it's the same code on browser and server

**Comment by wc8** [comment]
Maybe this is a feature ;-) so we could, technically, take advantage of the api to complete a task twice (or miss it twice)?

**Comment by devenv** [comment]
OK, just checked, after adding the condition it still allows you to complete a daily from different tabs.
Is the model refreshed before doing the logic on the server side?

**Comment by paglias** [comment]
@devenv even after you refresh? The model is fetched at each request from the database, no caching

**Comment by deilann** [comment]
The issue, Matteo, is that if I have Habit open in two tabs, don't realize
it, and I see a daily I thought I forgot to check off, I'm unlikely to
refresh. You shouldn't be able to check off a daily twice in one day and
have it count twice -- whether or not you refresh. It should recognize that
it's completed.

**Comment by paglias** [comment]
@deilann yes of course but since we don't have a reliable method for pushing updates to the client I wanted to understand if it was a syncing problem or a bug that persisted on the server

**Comment by deilann** [comment]
It is not.

**Comment by crookedneighbor** [comment]
The server should (now?) sort this out.
