### ISSUE TITLE
Nonstandard visuals not displayed on android mobile app

### ISSUE THREAD

**Issue by ca-mcknight** [HabitRPG/habitica#3236]
All of the no-standard items/colors/options do not show up on the android mobile app.
It appears the assets have not been added to the mobile app repository. 
Special Pets seem to show up just fine, such as the griffin or the hedgehog. 
Desktop:
![avatar](https://cloud.githubusercontent.com/assets/6657781/2656454/4fd364e0-bff2-11e3-9550-3fa2c364335e.png)
Mobile:
![2014-04-09 14 14 26](https://cloud.githubusercontent.com/assets/6657781/2656472/6a9dd80a-bff2-11e3-8619-36000e9426d3.png)

**Comment by deilann** [comment]
I think @lefnire needs to do something with habitrpg-shared to move it over
to mobile stuff, but I don't know what that is. He's on vacation atm, and
I'm sure will get to it ASAP.

**Comment by negue** [comment]
@ca-mcknight Does this still happens?

**Comment by crookedneighbor** [comment]
I believe this happened with the new backgrounds recently too.

**Comment by SabreCat** [comment]
I've noticed the Time Travelers gear isn't in Android mobile yet.

**Comment by lemoness** [comment]
iOS either - what happens is that the most recent art only appears in the
mobile app when we release a new update.

**Comment by ExperimentMonty** [comment]
The stat bonus from these items don't show up either, so I have had times where it shows me as having more than the maximum MP on android.

**Comment by Alys** [comment]
We're fixing this in the new apps by having images stored externally.
