### ISSUE TITLE
Don't show unlock price for items already group-unlocked

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3239]
In the avatar customization screen, there are various customization options available for Gem purchase. You can buy them individually for 2 Gems, or in themed groups for 5. The latter is so much better a bargain that I've never bought customizations individually... but the little price tag saying "2 Gems/locked" is still there. It's a little confusing and a lot superfluous. Can we hide these if the corresponding avatar set is completely bought?

**Comment by crookedneighbor** [comment]
Closed with #3186
