### ISSUE TITLE
Plain Eggs have empty positions in Mounts page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3240]
Even though the Plain Eggs are not meant to be fed into mounts, there are places for them set aside on the Mounts page.

**Comment by stemvork** [comment]
**Quoting Alys from the Tavern:** _"In my personal (irrelevant) opinion, we should fix this bug by making Megan create some egg mounts. :) We'd look awesome riding eggs! And think of the possibilities for next April Fools Day: we could all turn into hens, sitting on our egg mounts. :)"_

+1

**Comment by neverasuspect** [comment]
I want to ride in an egg, please. I vote for mounts as well.
