### ISSUE TITLE
Toolbar unlocks access too early...

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3241]
As mentioned elsewhere, #3076 needs to take into consideration which places are locked for a player. For example, level 1 players would not have access to equipment, level 2 players would not have access to Market (?) I think, etc.

**Comment by deilann** [comment]
Items in general; the whole market subsection, doesn't unlock until 4.

**Comment by Alys** [comment]
I'm closing this because the current site design allows for new players to see all features immediately, and the help text explains when the features will be usable.
