### ISSUE TITLE
Started quest, became invincible?

### ISSUE THREAD

**Issue by scheidm** [HabitRPG/habitica#3242]
Greetings,

A few days ago, I started the trapper santa quest. I had a good day, and expected to take only minor damage. I promptly forgot about the website due to pressing RL issues and expected to log back in dead. INSTEAD, I have taken 0 damage, neither from dailies nor from the boss. 

Even more strange, the boss has taken a small amount of damage since the last time I log in. Hard refreshing the page did not change anything nor did the sync button. If it helps my userid follows:
cd74cac2-86f3-4aa4-956e-9362e1bb628e

**Comment by deilann** [comment]
Are you in the inn? (Have to ask, sorry. :P)

**Comment by scheidm** [comment]
I had meant to mention that, I've used the inn but had signed out of it a few days prior to this issue.

**Comment by Alys** [comment]
@scheidm I'm sorry we never got back to you to help you with this! I can see from your account that you're not in a quest now, but if the same problem happens in future, please tell us and we'll try to be more prompt. :(
