### ISSUE TITLE
Not able to go on the website

### ISSUE THREAD

**Issue by Melyk** [HabitRPG/habitica#3245]
I tried many times in a row to access the website, and there's that error code that pop up: An error occurred during a connection to habitrpg.com.
Peer's Certificate has been revoked.
 (Error code: sec_error_revoked_certificate)

What is wrong with the website!?

**Comment by caveman1337** [comment]
It seems the whole server is down. You can't even get a ping from it

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg/issues/3230
