### ISSUE TITLE
Invalid certificate on beta

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#3246]
I'm seeing an invalid TLS certificate on beta.habitrpg.com, with an error of type "sec_error_unknown_issuer" on Firefox (on Konqueror: "The root certificate authority's certificate is not trusted for this purpose").
Has the certificate recently changed, and can anyone reproduce?

**Comment by lefnire** [comment]
Let my try fiddling with the way the `*.crt` files are concatenated. Can you give that a try?

**Comment by Eusebius** [comment]
No alert anymore. Fine for me, thanks!
