### ISSUE TITLE
Dailies not resetting

### ISSUE THREAD

**Issue by wendolen** [HabitRPG/habitica#3248]
For two days now, my finished dailies have not reset after cron. Perhaps coincidentally, I have been staying at the inn during this time, but the description of the inn doesn't seem to indicate that this is part of staying there. (I'm using the inn because I have some dailies that I'm inconsistent about finishing and my party is engaged in a quest.)

**Comment by deilann** [comment]
Not coincidentally at all. Being in the inn freezes your dailies. They will
never reset whilst you are resting.

**Comment by wc8** [comment]
The description could probably be clearer...or maybe just link to the wiki article on Resting in the Inn.

**Comment by kitsully** [comment]
@wendolen @wc8 What would you guys suggest that it be? I can change the popover while on my quest to learn Angular and Node.js.

**Comment by wc8** [comment]
How's this?

> Welcome to the Tavern! Stay a while and meet the locals. If you need to rest (vacation? illness?), I'll set you up at the [inn](http://habitrpg.wikia.com/wiki/Tavern). While checked-in, your dailies are frozen as-is (checked/unchecked) until the day after check-out. You will not suffer for missing them at the day's end. Beware, though: any boss you are battling can still inflict damage on you and your party!

**Comment by deilann** [comment]
Sounds like the boss will hurt you for your incomplete dailies

**Comment by kitsully** [comment]
I think that's fine thought because don't your party's dailies hurt you in a boss fight?

**Comment by deilann** [comment]
Yes, the issue is that it reads as if your own dailies will hurt you in a
boss fight, which is not true.

**Comment by kitsully** [comment]
How would you suggest it be clarified then?

**Comment by deilann** [comment]
I'll look at it later. If someone else wants to redraft before I can, they
are free to.

**Comment by thepeopleseason** [comment]
How this? 

> Welcome to the Tavern! Stay a while and meet the locals. If you need to rest (vacation? illness?), I'll set you up at the inn. While checked-in, your dailies are frozen as-is (checked/unchecked) until the day after check-out. You will not suffer for missing them at the day's end. 
> 
> Warning: If you are participating in a boss quest, the boss will damage you for any missed dailies from your party mates.

**Comment by deilann** [comment]
Would change "warning" to "Be warned" and cut the "however" (odd after the
warning) then possibly "for your party mates' missed dailies"

**Comment by wc8** [comment]
Are we sure that there's no _boss damage_ for your dailies? 
Last I checked, my impression was I suffered _boss damage_ but not regular damage. (I'm in a collection quest so I can't check now.)

**Comment by deilann** [comment]
I'm positive.

**Comment by casicastiel** [comment]
I can verify — I was in the inn last night as well as on a quest and took no boss damage from my own dailies. (Ofc, neither did I deal damage to the boss.)

**Comment by kitsully** [comment]
So is it okay that I go with what @thepeopleseason suggested then?

**Comment by deilann** [comment]
I was just going to direct commit this, Kristopher.

**Comment by kitsully** [comment]
Ah ... Okay go ahead.
