### ISSUE TITLE
Unchecking ToDo does not properly "undo" rewards

### ISSUE THREAD

**Issue by sctincman** [HabitRPG/habitica#3249]
Unchecking a ToDo does not remove the same amount of Xp/Gold and does not remove dropped items received from the original "check". Rechecking the ToDo nets more Xp/Gold than unchecking consistently.

The effect is more noticeable with old ToDos with long checklists--my rewards for those were typically over 3x as much as the amount lost from unchecking them.

This was originally invoked to downgrade the difficultly of a completed task as the amount of XP/gold was enormous.

No javascript errors in console.

**Comment by wc8** [comment]
See also #2221 which is about dailies being unchecked/deselected or possibly #2222.

**Comment by sctincman** [comment]
Ah ha, I must have missed that one, does seem to be a duplicate of #2222
