### ISSUE TITLE
To-Do I dragged to top keeps hopping back

### ISSUE THREAD

**Issue by cesarioviola** [HabitRPG/habitica#3250]
I'm working on a complex to-do with a lot of steps in the checklist that needs to get done today. I dragged it to the top of my to-dos list so that I could find it easily, but every hour or so it hops back to its original place in the list. I know the task will probably be finished by the time you get around to addressing the issue, but I don't want it to happen again in the future, so it seems worth mentioning.

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/2606

**Comment by cesarioviola** [comment]
If it's closed, why did it just happen again?
On Thursday, April 10, 2014 6:50 PM, deilann notifications@github.com wrote:

Closed #3250.

**Comment by deilann** [comment]
I closed your ticket because it's a dupe. See the ticket I linked.

**Comment by cesarioviola** [comment]
Ah, got it. 
On Thursday, April 10, 2014 7:58 PM, deilann notifications@github.com wrote:

I closed your ticket because it's a dupe. See the ticket I linked.

**Comment by androidadvocate** [comment]
I am having the exact same problem. I did a search on github and discovered these three are the exact same issue:

https://github.com/HabitRPG/habitrpg/issues/3025
https://github.com/HabitRPG/habitrpg/issues/2667
https://github.com/HabitRPG/habitrpg/issues/3250

And MAY be related to: https://github.com/HabitRPG/habitrpg/issues/2606

These two issues should be consolidated into one so we know which one to donate a bounty to.

**Comment by Alys** [comment]
This issue that you've commented on is 3250 (the third link from your list). It's already consolidated into 2606 (the issue that's linked to in the first response above). 3025 and 2667 are different problems - they are related to sorting habits and dailies, not to-dos. If you're having trouble with sorting to-dos, then use the 2606 link near this top of this issue.
