### ISSUE TITLE
Yet Another Cron/Dailies Still Checked Issue

### ISSUE THREAD

**Issue by kathatfield** [HabitRPG/habitica#3255]
So I reset the clock back to zero, checked of the in, logged in and out yesterday, etc and thought that resetting the clock and waiting till it past midnight was my best bet. Welp it didn't. I would put this one of the other tickets but nothing was wrong until the great heartbleed incident of 2014, so I strongly suspect they are related at least somewhat.

**Comment by deilann** [comment]
Heartbleed would have nothing to do this with. Please continue to follow this in the other ticket.
