### ISSUE TITLE
Quest of party member who was booted is not disappearing

### ISSUE THREAD

**Issue by spidey588** [HabitRPG/habitica#3257]
A party member had started the Egg Hunt quest by themselves, and since the rest of the party wanted to do the quest and that one party member wasn't ending the quest, I booted said member from our party. Now, three days later the quest hasn't disappeared and no one in the party can start it. Is there a way that I or an admin can delete the quest?

**Comment by deilann** [comment]
Can you post your UUID and your group ID? I can't do anything about this, but @lefnire might be able to.

The easiest way for you to fix it yourself would be to leave that party and have everyone else leave (grab all the member UUIDs as you do) then form a new party.

**Comment by spidey588** [comment]
Sorry, I was just about to edit it in: group: 69802ab6-043c-4fb6-a318-f8a2bf918701
User: 00a016ad-d2b2-4070-8853-431aff2fb3ef

**Comment by Calimie** [comment]
We have the same problem. A player began a quest by themselves and checked in the inn. They were booted a couple of days ago but the quest is still there.
Group ID: 623fedc6-2eb6-4426-bd76-90e9a413680f
User ID: 44e738fd-8fac-4bb7-b75c-bbe166297617

**Comment by thepeopleseason** [comment]
Some thoughts on where to look for this issue:

My party just started the Egg quest, and it's not auto-starting despite all of the members accepting it. 

http://imgur.com/Mtn45Yo

We previously had a member who removed himself from the party. Checking the API for our particular party yields the following entry in the dictionary, which is one too many: 

`"memberCount": 6,`

Also, the `quest` dictionary lists the UUID of the removed member of the party with the value 'null' (I'm guessing that's the accept/reject status). 

Somewhere in the quest or the groups code, we're referencing an outdated structure of party members.

**Comment by itsasooz** [comment]
Having the same quest issue: Member started a quest on their own, I booted the member, quest will not go away.
Group 618e9905-8e6c-4787-83b7-6a1273e20eaf
UID 312f9e64-7c17-40dc-b10c-3c03afc948a3

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4002
Any quests whose quest owner is no longer in the party can now be cancelled/aborted by other party members. More details at that link.

Also for @thepeopleseason's comment, the quest dictionary will no longer list the UUID of a removed member.
