### ISSUE TITLE
dailies resetting at odd times - and three times in two days

### ISSUE THREAD

**Issue by adalina** [HabitRPG/habitica#3258]
I just moved from GMT+1 to GMT and found that my dailies were switching over at 11pm instead of 12pm. My computer clock is set to the new timezone, and I can't find anywhere to tell Habit what my new timezone is. I refresh the page pretty frequently (by retyping habitrpg.com in the address bar - the refresh button itself doesn't seem to work) and have restarted my computer in the meantime. 
This would just be a bit annoying, but today I had cron twice - once at 8pm and once at midnight. I've never played with the custom cron time setting. What gives?
User ID: f327bfcc-6cbb-4277-b0d2-1a2e2788e3cf

**Comment by crookedneighbor** [comment]
@adalina  Sorry this happened to you. The site has gone through several code revisions since you opened this issue, so I'm going to close this issue. If you're still having trouble, please reopen it.
