### ISSUE TITLE
Include more info in guild invitation (feature request)

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#3259]
We were having a discussion in a private guild where someone who had been invited had at first rejected the invitation because they didn't know what the guild did. I realized I also had previously rejected a guild invitation on the assumption that the guild was just spamming large numbers of people with invites — it hadn't occurred to me until now that it might have been a personal invitation from someone who wanted me, specifically, to join their guild.

So, we thought it would be great if when you received a guild invite, it included the name of the person who invited you. Even better, if the inviter was offered a short textbox where they could optionally type a message. So the recipient would get something like this:

**Megan has invited you to join the guild My Cool Guild**
Megan's message: 
Hey BrightBold, I thought you'd like this guild because we talk a lot about hedgehogs and I know you like hedgehogs.
##

**Comment by crookedneighbor** [comment]
Very late to this, but I think this is a great idea.

**Comment by paglias** [comment]
Should be fixed
