### ISSUE TITLE
Opening HabitRPG in a small window break the interface

### ISSUE THREAD

**Issue by michalsrodek** [HabitRPG/habitica#3264]
How to reproduce:
1. Change the size of your browser window to e.g. 300x300px
2. Open HabitRPG
3. Maximize browser window
   ![1](https://cloud.githubusercontent.com/assets/292668/2688386/81a878ca-c29a-11e3-8ab9-6b87d2dcde43.png)

My browser: Chrome 34.0.1847.116 (linux)

**Comment by negue** [comment]
This still happens with Toolbar V3.0

The Content under the Header is somehow "moving" into the header, which results the same result as in the screenshot, except for the notification icons since theyre only inside the new notifications Button.

**Comment by negue** [comment]
Retested it now.

Seems to be fixed. 

Closing this issue. :)
