### ISSUE TITLE
Cast Blessing on Party and it doesn't heal any of my party members

### ISSUE THREAD

**Issue by ladyTorix** [HabitRPG/habitica#3265]
I cast blessing four times and then checked my party members HP, and they hadn't been healed, even though it said the spell had been cast on the party page.

**Comment by Alys** [comment]
Did you notice if only some of their Health had been restored? The Blessing skill won't restore the party to full health unless the person casting it has VERY high INTelligence and CONstitution. If you are a relatively low-level Healer, you might have restored only 1 or 2 HP to your party members. You can read about the exact effects of the skill here: http://habitrpg.wikia.com/wiki/Healer#Skills

If you're still not sure about what happened, add your INT and CON to this issue report, and I'll tell you how much healing your party would expect from that skill. This will let us work out if you experienced a bug or if the skill is just performing weakly for you.

**Comment by ladyTorix** [comment]
No, none of their health was restored, and I cast 4 times in a row.

My CON is 75.5 and my Intelligence is 59.5, which means it should have healed about 5 points per cast, right?

**Comment by ladyTorix** [comment]
On another note:  It did work for me just now, but I'm not sure why it didn't work yesterday.

**Comment by Alys** [comment]
About 5 points per cast, yes. 

Can you add your [User ID](https://habitrpg.com/#/options/settings/api) (not your Token) and [Group ID](https://habitrpg.com/#/options/groups/party)? The developers might need that.

**Comment by ladyTorix** [comment]
User ID:  c0fd8f13-6962-40dd-bb4a-d6d2f7a7b8b2
Group ID:  d910797d-f8f2-496c-ab9c-b0b3f1ef86b3

Thanks!

**Comment by Alys** [comment]
We never found anything that might have caused this behaviour and the skills have been rewritten now, so I'm closing this.
