### ISSUE TITLE
Missing string on Beta

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3266]
Cool new interface! But we're short a string resource for the caption of the notifications dropdown:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/2688567/e97e9678-c2ae-11e3-95c6-2eff50a0b071.png)

**Comment by ghost** [comment]
There is also a "clear" string - popup for the cross button on the screenshot above

**Comment by lefnire** [comment]
These all good now?

**Comment by ghost** [comment]
@lefnire It seems OK to me now. Thank you!
