### ISSUE TITLE
My level goes down

### ISSUE THREAD

**Issue by Pandagom** [HabitRPG/habitica#3267]
My level is 57 then I goes other page and I goes to habitRPG my level goes 45.

**Comment by Alys** [comment]
How long ago were you level 57? Were you level 57 just two or three days ago, or one or two weeks ago?

Between the time that you were level 57 and the time that you were level 45, did you not use HabitRPG for several days? Is it possible that you died many times between when you were level 57 and now? That could explain why you lost many levels.

Please add your [User ID](https://habitrpg.com/#/options/settings/api) (not API Token) to this bug report.

**Comment by Alys** [comment]
Closing because we can't do anything without further information. Even with more information, it's probably too late to investigate now since there'll no longer be any record of the problem in logs etc.
