### ISSUE TITLE
Login window layout: why is fb on top?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3268]
The login popup window shows (from the top):
fb banner, "OR" heading, login/register section, 1password note and finally password reminder section. (Screenshots are in Russian, but I hope they still show what I mean)
http://oi58.tinypic.com/oqb1gz.jpg

 Wouldn't it look more natural to have OR not on the top, but below the login/register section? http://oi61.tinypic.com/dhfih5.jpg
Is the current layout due to marketing reasons? In this case, I'm sure fb banner will still be visible pretty clear below the Enter button.

**Comment by deilann** [comment]
For some reason, it's pretty standard to have 3rd Party Authorization on
top or to the left -- so arguably first. I have no idea why this is
standard.
