### ISSUE TITLE
Logged in in different browser, got reset to lv 1

### ISSUE THREAD

**Issue by Chetamashii** [HabitRPG/habitica#3271]
I was logged in in Firefox with no problems, then logged in in Crome and died. Got reset to lv 1 with none of my habits, dailies etc. Sometimes this happens on my phone app, too, usually not a problem; when I check in Firefox it usually works. Not this time. I've logged in and out, in both Firefox and Chrome, but it seems to keep the idea that I just signed up. The app on my phone has me as lv 24 with my habits, dailies etc. intact.

User ID: Chrome and Firefox both say 165b0faa-d2b0-4ae9-98ef-060efa4c275f, but my phone app says the UUID is 6805d8ef-ea72-4c28-bdb8-d2efc213f1b5

Javascript errors according to Chrome:
Failed to load resource: the server responded with a status of 404 (Not Found) https://encrypted-tbn3.gstatic.com/favicon?q=tbn:ANd9GcQ9UebOcaeP5g9lmOuULMemm327JmUvBQtGLnocwdVzDVR_RRjrRBNX4bFOCLPvbkbSReDlQHELAw
Failed to load resource: the server responded with a status of 404 (Not Found) https://encrypted-tbn1.gstatic.com/favicon?q=tbn:ANd9GcTwf9-XdpKqsSk1_RbJ1rabnTlcarHf8nEgExSJu1eIL1BIpfTsm9NpOIbFsUgbFeYbMx8
Attr.specified is deprecated. Its value is always true.
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1397165098.html:1
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by deilann** [comment]
You have a duplicate account! Here's how to fix it:

When you see the secret level 1 account, delete it.

Should fix everything, iirc.

**Comment by Chetamashii** [comment]
Thanks, that did it!
