### ISSUE TITLE
ssl issue with api - unsupported hash algorithm

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#3273]
Started receiving [this error](http://pastebin.com/wqqmxpSq) today.  Not sure if it's related to the heartbleed changes, since it's probably been at least a week since I tested it last.

The hash it's saying it has a problem with is sha256RSA.

I don't know if it's some bug in software I'm using....or what...

**Comment by paglias** [comment]
@fragmental the ssl certificate has been replaced with a new one... maybe the old one is being cached?

**Comment by fragmental** [comment]
This is happening in my unity3d habitrpg client.  

 If the previous ssl cert used a different cert algorithm, then there may actually be a bug in the version of mono that unity uses that prevents sha256RSA from working.

**Comment by fragmental** [comment]
So, I think this is a bug from an earlier version of mono, that unity is using because they didn't like the license changes xamarin did to the newer versions of mono.  According to unity this is fixed in a newer version, and I just have to wait for it to come out.  http://fogbugz.unity3d.com/default.asp?602783_4ddsl9l014uuvquo  I'm guessing the pre-heartblead cert use a different hash algorithm, and that's why I didn't have the problem before.

**Comment by lefnire** [comment]
@fragmental it seems a lot of your issues stem from Mono, Unity, .NET (not supporting JSON, SSL, REST, etc) - and many of those on older versions to boot. Alas, not things we can or should support given the limited time our contribs have to focus on more prevalent issues. I'd say if you want these issues fixed, 'tis time to start rolling up your sleeves and jumping into habitrpg's codebase.

**Comment by fragmental** [comment]
I was trying to say this wasn't a habitRPG issue, but I was waiting until the fix from unity was released to actually close the issue. I should have just closed the issue.  I apologize if it caused any confusion.
