### ISSUE TITLE
Why did I die in the middle of a day?

### ISSUE THREAD

**Issue by hespa** [HabitRPG/habitica#3278]
Hi devs,

I'm in a party doing the Egg quest & hadn't been watching my health very well. When I logged on this morning (the second of four party members to log on), I had dropped to 1 health, so I immediately bought a health potion and my health bar showed 16 health. When I checked in this afternoon, after the oher two party members had logged on for the day (and the party had taken another 2-ish damage), it informed me I had died.

What happened? I could see this being related to damage being calculated at midnight (when I did not have enough health to take that much), but it was pretty disheartening to think I had saved myself in the nick of time, only to then be killed anyway. Is there a way to fix this so damage and health calculations line up?

**Comment by Alys** [comment]
The developers will need some additional information if they are able to investigate this, so please:
1. Post your [User ID](https://habitrpg.com/#/options/settings/api) (not your API Token), and your [Group ID](https://habitrpg.com/#/options/groups/party) (left-hand column, under the Quest box). 
2. Take a screenshot of your [party page](https://habitrpg.com/#/options/groups/party) showing the quest damage over the past 24 hours and add it here.
3. Tell us if you clicked on any negative habits in the time between buying the health potion and dying, and if so, about how many of them.

You can use [Fix Character Values](http://habitrpg.wikia.com/wiki/Settings#Misc) to restore your lost gold, XP, level, etc (you might need to estimate their original values).

One possibility is that when you bought the health potion, a syncing error prevented that action being transmitted to the HabitRPG servers (similar to the known issue [Gold/XP/Health/Mana Change for no Reason](http://habitrpg.wikia.com/wiki/Known_Bugs#Gold.2FXP.2FHealth.2FMana_Change_for_no_Reason): "... changes that are made in the browser are not synced to HabitRPG's server... When the browser and server next sync up, the server's information overwrites the browser. This causes the player's stats... to revert back to the state they were in before the syncing problem happened" [i.e., to the low-health state from before you bought the potion]

**Comment by Alys** [comment]
Closing because we can't do anything without extra information.
