### ISSUE TITLE
Daily graphs don't get new data [bug]

### ISSUE THREAD

**Issue by KeatonKafei** [HabitRPG/habitica#328]
Since the second of February, none of my graphs under the daily section seem to record my data anymore. I still get the exp etc.
They work just fine in the habits section, however.

![habitrpggraphs](https://f.cloud.github.com/assets/3501287/135516/585be166-7127-11e2-98a5-100e2f9849e0.jpg)

**Comment by kalmduck** [comment]
I'd like to comment that I have a similar problem with my dailies.  The only difference for me is that the graph data stops on 2/04 instead of 2/02.

**Comment by kamilpowalowski** [comment]
I have the same issue. And I can't display graph for habits (when I click progress button). JS console says: "Uncaught TypeError: Cannot read property 'date' of null"

**Comment by AnnFran** [comment]
Same issue (since Feb 5).

**Comment by horusofoz** [comment]
Is this still an issue for anyone as it's no longer affecting myself?

**Comment by kalmduck** [comment]
The issue with the Daily graphs appears to be resolved for me.  I still have the problem with some of my "onlies" in the habits, but if I delete them and make a new one, it works just fine.

**Comment by KeatonKafei** [comment]
Same here, looks like the redesign fixed whatever caused it. Hopefully it's working for everyone; I'm gonna close the issue.
