### ISSUE TITLE
Egg Hunt - Missing Eggs

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#3280]
My party started this quest, and since we have found 7 eggs, however the counter isn't working. Yesterday the counter was at 2 (but it should have been at 5) and today it is reading 0. 

Our Group ID: 2f75f0af-c169-42ab-a866-7d0b9ea2183f

![screenshot 2014-04-14 16 13 45](https://cloud.githubusercontent.com/assets/7197274/2696875/a92cdce4-c3e7-11e3-9593-80a7c872d551.png)
![screenshot 2014-04-14 16 14 04](https://cloud.githubusercontent.com/assets/7197274/2696876/a9332c70-c3e7-11e3-82a0-c2767d4bd28c.png)

**Comment by deilann** [comment]
@UncommonCriminal I'm pretty sure this is the collection quest version of #2657
