### ISSUE TITLE
Mage - Burst of flames doesn't fulfill chosen task

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3281]
Just tried my newly gotten spell "Burst of Fames" and tried it on a blue daily. Normally, this daily gives me about 6xp, w/ spell it gave me 50xp and I had to click on it again to fulfill it.

Judging by the description of "Burst of Flames" on the wiki the 50xp were also way too much.

**Comment by deilann** [comment]
50 XP seems fine for a daily that gives you 6 XP -- that sounds pretty blue.

Also, BoF isn't supposed to check off a task. It is independent of that. It is basically a reward for having a very blue daily.
