### ISSUE TITLE
Can't give gem prize for challenge "From Nailbiter to Nailfighter"

### ISSUE THREAD

**Issue by QuestingOrc** [HabitRPG/habitica#3282]
Hey there,

I tried to end the challenge "From Nailbiter to Nailfighter" giving away the price of 2 chrystals (I have 3 in my inventory) but the process can't be finished somehow.

There are currently 420 members in the challenge, maybe it's because of the numbers?
'entity is too large' 

Anyway, I really want to fulfill my promise and give the price, so please could anybody do something about it.

Thank you very much in advance.

Best regards
QuestingOrc

**Comment by AdrienLemaire** [comment]
:+1:, we need a way to edit the challenge prize at any time. I also tried to create [a challenge](https://habitrpg.com/#/options/groups/challenges/542df507-3f94-48d4-b930-71365e72ad8b) with all my gens (12), but somehow only 1 gem got assigned, and I cannot edit the prize anymore.

@lefnire can you quickly update the prize from 1 to 12 in mongo? And/Or evaluate whether this task can be completed by someone shortly?

Thanks!

**Comment by Alys** [comment]
_"but somehow only 1 gem got assigned"_ - that will probably be because of this: https://github.com/HabitRPG/habitrpg/issues/3862#issuecomment-51696097

EDIT: Actually it's more likely to be because of this: https://github.com/HabitRPG/habitrpg/issues/3998

**Comment by AdrienLemaire** [comment]
I see :) There's a lot of tasks in my challenge, and I reupdated all my private tasks with the challenge tag, removing the duplicate, so it would take me some time to delete/recreate. Hopefully an admin can help me with that ^^' Thanks for the fast answer @Alys

**Comment by Alys** [comment]
I'm closing this because the initial problem will be an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4132
and challenges can now be duplicated by cloning.
