### ISSUE TITLE
Paypal: "Cannot process request"

### ISSUE THREAD

**Issue by flauschekatze** [HabitRPG/habitica#3283]
I tried subscribing via Paypal; I get as far as entering my login information for Paypal, but instead of the payment going through, I get an error message informing me that Paypal can't process my request at this time (or something to that effect, the message is localised) and suggesting I choose a different option.

In case it's relevant, I am trying to subscribe from Germany.

**Comment by mhils** [comment]
Same issue over here. I'd love to subscribe, but PayPal doesn't process my order.
I am trying to subscribe from Germany as well.

**Comment by deilann** [comment]
@lefnire Any word yet, on forex subscriptions?

**Comment by mhils** [comment]
Don't get me wrong, but I'm somewhat astonished that such a critical payment bug doesn't get fixed ASAP.

**Comment by deilann** [comment]
Being a PayPal side issue, fixing it ASAP is a lot harder than you might
think.

**Comment by Alys** [comment]
I believe this is fixed now so I'm closing it. Reopen if I'm wrong.
