### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by stefanpenner** [HabitRPG/habitica#3284]
Reporting this on behalf of my wife (who doesn't have a GH account, but uses habit).

I am unsure if this is the correct place to report, if not let me know.
## Bug report:

The following data appears to have gone missing from her main page.
- tasks
- dailies
- to-dos disappeared 

She still has her:
- items
- quests
- levels/stuff.

**Comment by deilann** [comment]
Have her click the (x) at the end of the tags list.

**Comment by Alys** [comment]
Closing because I'm assuming from the lack of an update that this was fixed.  If not, the "x" button is now labelled "clear", and if that doesn't work, we can reopen.

**Comment by stefanpenner** [comment]
yes sorry apparently this was addressed shortly after posting this issue. (or so my wife informed me) I just forgot to close the issue
