### ISSUE TITLE
Text 'on' is entered in different places and checkboxes are all checked somepoint after the ad's load

### ISSUE THREAD

**Issue by TheLimey** [HabitRPG/habitica#3286]
I can't see this in the bug list, but it was hard to search for. 

I just signed up (after hearing you on Linux Outlaws), and am getting this weird issue when using Google Chrome Version 33.0.1750.146 on LINUX. It works fine using Firefox.

My username is TheLimey.

When I load the Tasks page it initially looks correct (the same as the Firefox screenshot), but after the adverts load various text is changed to 'on', also the checkboxes for any checklist items in tasks are ALL checked (I current have none actually checked), see the chrome screenshot.

The same issue with the 'on' text and checkboxes being checked occurs in the task editing bits as well.

Here is the JavaScript console output.

XHR finished loading: "https://habitrpg.com/api/v2/groups/party". app-a5d230cb.js:5
XHR finished loading: "https://habitrpg.com/api/v2/user/batch-update?_v=133&data=1397577218599&siteVersion=1". app-a5d230cb.js:5
XHR finished loading: "https://habitrpg.com/api/v2/groups/undefined/chat/seen". app-a5d230cb.js:5
event.returnValue is deprecated. Please use the standard event.preventDefault() instead. jquery.min.js:14
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1397165098.html:1
XHR finished loading: "https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.Z0T4ejFDQi8.O/m…sv=1/d=1/ed=1/am=AQ/rs=AItRSTMkT6pC-_gb2QICyfHFDXdNrMO2Zg/cb=gapi.loaded_0". fastbutton?usegapi=1&size=medium&hl=en-US&origin=https%3A%2F%2Fhabitrpg.com&url=https%3A%2F%2Fhabit…:27
XHR finished loading: "https://apis.google.com/_/scs/apps-static/_/js/k=oz.plusone.en_US.F1QgKL010…/rt=j/sv=1/d=1/ed=1/rs=AItRSTPn9mJEu-3Bnfr9JsHhg69z-fs2lw/cb=gapi.loaded_1". fastbutton?usegapi=1&size=medium&hl=en-US&origin=https%3A%2F%2Fhabitrpg.com&url=https%3A%2F%2Fhabit…:27
Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1
XHR finished loading: "https://fbstatic-a.akamaihd.net/rsrc.php/v2/yF/r/_cwLgt2Vdyt.js". like.php?action=like&app_id=172525162793917&channel=https%3A%2F%2Fs-static.ak.facebook.com%2Fconnec…:3

The line 'event.returnValue is deprecated' come up before the ad's start to load.
Then the next line doesn't come up until after the 'on' text appears and the check boxes all check.

![chrome-bad](https://cloud.githubusercontent.com/assets/7304320/2709409/f5875c9e-c4b5-11e3-9c57-247c35b9d76c.png)
![firefox-good](https://cloud.githubusercontent.com/assets/7304320/2709410/f58add6a-c4b5-11e3-9998-1afe5c6ada50.png)

**Comment by TheLimey** [comment]
Here's a screenshot of the 'Deck' task being edited. Initially it displays correctly, then after a couple of seconds or so, it changes to this.

![chrome-bad2](https://cloud.githubusercontent.com/assets/7304320/2709814/56849ad0-c4ba-11e3-9020-e26c173f3c1b.png)

**Comment by deilann** [comment]
Seen this before -- it's a lastpass thing, not Habit.

**Comment by TheLimey** [comment]
Hi,

thanks for the prompt response. I wondered if it was LastPass, but I don't
have the string 'on' saved anywhere for your site so figured it couldn't be.

Colin

**Comment by deilann** [comment]
iirc, neither did the other person

But disabling lastpass fixed it. It was very strange.

**Comment by Ripfrost** [comment]
I was about to ask about this as well. Altho I'm a bit confused, I've been playing habit for quite a while with LastPass and never had this issue before. Anyway thanks for the help Deilann.

**Comment by deilann** [comment]
Not sure what's up with lastpass and this -- for some strange reason, it
was also "on" iirc for the last user.

**Comment by TheLimey** [comment]
It just occurred to me that the "on" value would be the same as for the
checkboxes. It's like it's going through all the input fields (but not text
areas) setting the value to "on". I would guess it's trying to turn on a
specific check box and your field naming scheme is confusing it and causing
it to "turn on" all input fields.

Just a thought, hopefully it helps solve this.

Colin ☺

**Comment by deilann** [comment]
I'm gonna go ahead and close this -- it's a lastpass, not a Habit issue. Not really anything Habit can do about it.
