### ISSUE TITLE
Hatching Potions probability

### ISSUE THREAD

**Issue by kathcmills** [HabitRPG/habitica#3288]
So, okay. Hatching Potions have a rarity, and that's fine, but I don't think it's quite right. Because per the wiki & the code:

40% will be a Base, Desert, or White potion.
30% will be a Red, Shade, or Skeleton potion.
20% will be a Cotton Candy Blue, Cotton Candy Pink, or Zombie potion.
10% will be a Golden potion.

But then the Cotton Candies & Zombie potions are each individually rarer than the Golden potion because 20/3= 6.67, which is obviously less than 10. And actually, the Golden potions are effectively equally rare as the Red, Shade, & Skeleton potions. Which isn't quite the effect it's aiming for.

If the probabilities were 45/30/20/5, or 40/35/20/5, or 40/30/25/5, then that would fix the problem, but I'm not sure what would be preferable. Any thoughts?

& I _think_ I could figure out the code if I knew what the probabilities should be, but I don't know how to do Github. 

... And I sincerely hope this was the right place to put this.

**Comment by deilann** [comment]
I'm pretty sure Sabe fixed this. DIdn't you @SabreCat?

**Comment by deilann** [comment]
We've got

```
acceptableDrops =
          # Very Rare: 10% (of 30%)
            if rarity < .02 then ['Golden']
              # Rare: 20% (of 30%)
            else if rarity < .09 then ['Zombie', 'CottonCandyPink', 'CottonCandyBlue']
              # Uncommon: 30% (of 30%)
            else if rarity < .18 then ['Red', 'Shade', 'Skeleton']
              # Common: 40% (of 30%)
            else ['Base', 'White', 'Desert']
```

So we have .02 is 6.66% for Golden
.02 to .09 is 23.33% or 7.77% each for Zombie, CC Pink and CC Blue
.09 to .18 is 30% or 10% each for Red, Shade, and Skellie
.18 to .30 is 40% or 13.33% each for Base, White, and Desert.

Is correct.

**Comment by SabreCat** [comment]
Sounds like the wiki's out of date. The rarity line for Golden used to be "if rarity < .03 then ['Golden']", which did indeed make Golden potions more common than Zombie potions.

The code comments are off now, but the actual probabilities work.

**Comment by kathcmills** [comment]
Okay! In that case, I'm going to go edit the wiki!

**Comment by sean-maccath-moran** [comment]
Hmm... I think there _might_ still be a problem with the calculations on this -- and if there _isn't_, then I need to go play the lottery, because I'm _seriously_ beating the odds.

On my account, I've had around 270 items drops (between food, potions, and eggs), with about 80 of those being potions. Of those, _not one_ has been a Skeleton. Does this seem plausible, given this formula/distribution? I mean, sure, it's _possible_, but just seems particularly unlikely, you know?

On the other hand, people _do_ win the lottery... =o)

**Comment by deilann** [comment]
Over 10% of my potions are skeleton.
