### ISSUE TITLE
New notifications are super transparent

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3289]
I like 'em, but I can hardly see what they say anymore.

**Comment by deilann** [comment]
Huh. Can you give me a screenshot, E? They seem normal to me.

**Comment by casicastiel** [comment]
![screen shot 2014-04-15 at 9 40 53 pm](https://cloud.githubusercontent.com/assets/6208739/2715276/5361adea-c508-11e3-8bba-5b45e8c8cb06.png)

Ignore the clutter. :P (No Habiteers were killed in the making of this screenshot.)

**Comment by deilann** [comment]
I'd definitely turn up the opac just a smidge. Just realized that I've been
seeing them on top of an empty portion of the header for the most part,
which makes them super visible. But yeah, if they're overlaying something,
it's not such a good time.

But yessss. I love the new notifs too. So happy with them.

**Comment by thepeopleseason** [comment]
I'm on it.

**Comment by casicastiel** [comment]
Thank you!
