### ISSUE TITLE
Tokens gone?

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#329]
The silver coins are tokens, yes?

Before today, I had earned about 8. Suddenly they all disappeared! What's going on?

I still have all my gold.

**Comment by lefnire** [comment]
the item to the right of gold is silver. it's a fraction of gold. Tokens show if you click "reroll" - top right corner of that modal dialog. This will be more obvious in a future UI change, adding gold silver & copper, and putting tokens somewhere more visible in the interfact

**Comment by lefnire** [comment]
vote this card if we want copper added: https://trello.com/card/add-copper-to-gp-system/50e5d3684fe3a7266b0036d6/225
