### ISSUE TITLE
All data missing

### ISSUE THREAD

**Issue by diemarysues** [HabitRPG/habitica#3291]
When I opened my habit page, I was faced with this:

![untitled](https://cloud.githubusercontent.com/assets/7313138/2718536/0af3d888-c550-11e3-870f-eddbfe55913b.png)

The only links I can click are the Mobile/Company/Community ones at the bottom. I'm using Firefox v 28.0, and I tried to sign in on Chrome, to the same effect. I'm not sure where else to submit this report. Thanks in advance.

**Comment by deilann** [comment]
Can you open your console (on Chrome or Firefox) and tell me if you're
getting any javascript errors? This indeed looks like you are having
javascript problems.

**Comment by diemarysues** [comment]
under javascript is says

SyntaxError: syntax error

**Comment by diemarysues** [comment]
Under CCS I get this:

![untitled](https://cloud.githubusercontent.com/assets/7313138/2718760/fe0f67a0-c553-11e3-8ff5-ca72e994d20e.png)

**Comment by deilann** [comment]
Another user found that turning it off and on again (restarting) fixed the
problem. Have you tried that?

**Comment by diemarysues** [comment]
I had to restart twice, but it's working now. Thanks!

**Comment by deilann** [comment]
Awesome!

**Comment by lefnire** [comment]
This means browser  required a hard refresh / cache-clear
(ctrl/cmd+shift+f5). Restarting the computer may have some auto browser
cache invalidation mech, but you shouldn't need to go that far. I'll look
into express invalidation for habitrpg-shared.js cache

Closed #3291 https://github.com/HabitRPG/habitrpg/issues/3291.

—
Reply to this email directly or view it on
GitHubhttps://github.com/HabitRPG/habitrpg/issues/3291
.

**Comment by deilann** [comment]
Ach, I always forget that people don't automatically hard refresh when I
say refresh.
