### ISSUE TITLE
Bonuses Not Preserved by Time in Inn

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3294]
I'd assumed that checking into the Inn turned off cron completely. But as it happened, I checked in last week while under the influence of a "perfect day" bonus. This morning when I checked out, I'd lost my bonus, as I noticed immediately when I saw I had 176/148 mana points - having lost my int bonus. 

Not a biggie, since I've no idea what's intended - but given the way everything else works, somewhat surprising.

**Comment by deilann** [comment]
Not actually surprising -- so, in the inn, day turnover still happens. You'll still get +whatever MP. You'll still get your drop cap refreshed. Just nothing happens to your dailies.
