### ISSUE TITLE
Finished challenge can't be deleted from dailies

### ISSUE THREAD

**Issue by Weenyah** [HabitRPG/habitica#3295]
I'm sorry if this is a known issue or if there already was a ticket, I couldn't find one with a quick search.

I participated in a challenge called "Had a Lovely Meal Made by Me" at the beginning of 2014 and the challenge was supposed to end in February. Challenge can't be found in the challenges list anymore, but the daily, habit and done to-do's won't "break" and can't be deleted. I can't "leave the challenge" as it doesn't exist anymore. This is a daily I can't do every day and as such it makes it really hard for me to gain perfect days. I'd love to be able to get rid of it!

My user ID is 6e2c0df4-af45-4ff3-91b1-c3590a420b67 if it helps in any way.

**Comment by ghost** [comment]
You might want to give the following workaround a try: 
https://github.com/HabitRPG/habitrpg/issues/3233#issuecomment-39967924

**Comment by Weenyah** [comment]
I tried the workaround but it sadly didn't work with me :C daily and habit (I tried to edit and move both) are still listed as if they belonged into an active challenge.

**Comment by deilann** [comment]
Weenyah -- the workaround isn't to edit or move them, but to actually click
the habit or daily as if you did them.

**Comment by Weenyah** [comment]
@deilann but I've been doing this daily and habit since February? I must have clicked them at least 30 times past these two months. They won't break, they act like they were still part of an active challenge.

**Comment by deilann** [comment]
Yeah, sounds like the workaround isn't working for you then. :c That's
definitely the workaround.

**Comment by Weenyah** [comment]
@deilann oh no I'm sorry, I've been wasting both of your time :c it seems the challenge is still listed, I just couldn't find it because it's name was completely different than the actual tasks! Oh gosh I feel super stupid now, I've just been confused because the challenge was supposed to end months ago. I'm really sorry! Thank you a lot for your help. I hope you have a happy Easter (in case you're celebrating it)!

**Comment by deilann** [comment]
Don't worry about it. :) You're fine.
