### ISSUE TITLE
Died, can't re-purchase broken item.

### ISSUE THREAD

**Issue by mikesiegel** [HabitRPG/habitica#3299]
3 STR sword broke, switched back to training sword.  Now the 3 STR sword no longer appears in the shop.

**Comment by wc8** [comment]
If you haven't already, do try refreshing/reloading the page. Also, sometimes the simple act of checking off a task will reset the store.
Could it be the sword belongs to a different class? (If you haven't reached level 10, the answer is no.)

**Comment by mikesiegel** [comment]
I dont think that's it. It's been gone for a couple of weeks (log-ins, log outs, etc).  I thought it was a game mechanic but then realized that would make the game nearly impossible.

Interestingly after this happened my training sword broke, it showed in the store for 0 gp just fine.

**Comment by wc8** [comment]
hm... your [user ID](https://beta.habitrpg.com/#/options/settings/api) might be needed. 
I'm wondering what would show up if you were to use [Unofficial Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) and click Missing Items after fetching data.

**Comment by deilann** [comment]
When you say you cannot purchase the sword, are you saying there are no
weapons at all for sale?

**Comment by mikesiegel** [comment]
Nah, I see the Axe for sale, for example.  Nothing shows up in the Unofficial Data Display under Missing Items.

**Comment by deilann** [comment]
That means you own the sword. Have you unlocked inventory yet?

**Comment by mikesiegel** [comment]
Ah that's it, only level three. Never mind, sorry!
