### ISSUE TITLE
Checking off items broken in mobile safari

### ISSUE THREAD

**Issue by eshear** [HabitRPG/habitica#33]
When you attempt to check off a daily task in mobile safari on iOS, it doesn't work. The check mark doesn't appear and nothing happens.

**Comment by lefnire** [comment]
Hmm, I can't replicate. Someone else chime in if they're having this issue, I'll keep an eye out for it.

**Comment by edthefreak** [comment]
I also have problems running it on mobile safari. Nothing I click on seems to work. Try to edit tasks but the icons to edit and delete will just flicker. Haven't tried to check off a task or anything yet, been sticking to running it on my laptop because I just found it largely unusable on my iPad.

**Comment by horusofoz** [comment]
Can anyone advise if this is still happening?

I'm not aware of any work specifically aimed at resolving this bug but I believe there has been revisions to the code in that time that may have impacted.

**Comment by Bquilt** [comment]
Same as edthefreak on ipad

**Comment by horusofoz** [comment]
Can any users report if this is still happening? We have had significant changes to the code base which may have resolved this.

**Comment by Bquilt** [comment]
works for me now on iPad 2 using Safari and Chrome

**Comment by horusofoz** [comment]
@Bquilt Great to hear. Will close this for now. Can re-open if @eshear or @edthefreak advise it is still affecting them.
