### ISSUE TITLE
Toolbar menu button on mobile browser has no image/caption

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3301]
I can test only on android and I use opera, so it may need confirmation for other platforms, but as I have it, toolbar menu button has no caption or image, but a standard pic with question mark: instead http://i59.tinypic.com/2rg17rb.jpg

**Comment by thepeopleseason** [comment]
Confirmed on Chrome for Android:

http://i.imgur.com/TDXUuzr.png

**Comment by lefnire** [comment]
Could use ![glyphicon-align-justify](http://i.gyazo.com/b08a098cd8a4b9ec44ee05d88f9a75d0.png)

**Comment by negue** [comment]
I think this was fixed not long ago. It works on my Android.
