### ISSUE TITLE
Had Notification for Guild Lacking Messages

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3303]
This morning there was a new UI, and it appeared to me that notifications of guilds with messages had been removed entirely, so I went to a couple of places manually. One was my party, another was the Back Corner. 

Thanks to discussion in the Back Corner, I found that the icon to the right of the silver piece count was supposed to look like a chat bubble, and provide notifications. 

When I clicked on it, I got a nice list of places with messages - one of those was the Back Corner. I clicked the name, and found that the most recent messages had been left by me in my visit earlier this morning. I.e. I had already seen the messages which had appeared overnight, but the notification hadn't cleared.

On the other hand,  there was no notification for my party - and no messages since my visit either.

Bailey suggested "either you need to refresh the page or you didnt clear the notification from the menu somehow". 

Angrboda commented "that 'notification but no new messages' problem happens to me and at least one of my party members frequently. For me, sometimes I get a new message if I refresh. " So this issue may be a dup, and in any case is not new breakage - just something I noticed because of today's changes.

**Comment by deilann** [comment]
This happens in one of two cases -- it's not related to anything new. Notifs themselves hadn't changed.

1) you send a message and between the time you checked the messages and your message was sent, updating chat, someone else commented

2) someone sent a message and deleted it

**Comment by deilann** [comment]
I'm closing this because it's probably related to 1 or 2 and now when you fetch recent messages it clears the notification. If it continues to be a problem, we can reopen it.
