### ISSUE TITLE
Feature Idea: FreePlay Behavior Design / Rewards

### ISSUE THREAD

**Issue by xtagon** [HabitRPG/habitica#3305]
Hi,

Before I found HabitRPG, I have been toying with the idea of creating a similar project. In my research I discovered a company called [FreePlay](http://freeplay.co/). FreePlay connects marketers with developers, so that you can offer real-life rewards to enforce good behaviors. It may be worth looking into integrating with HabitRPG.

Just an idea.

**Comment by ramsaybr** [comment]
Hey Xtagon + HabitRPG,

Thanks for thinking of us! We're operating under the name Dopamine now (www.useDopamine.com) and we've been meaning to reach out to HabitRPG for a while to ask if they'd like to use the Behavior Design API.

We're focusing on building the best reinforcement and analytics system we can without brand involvement yet. I can see a really cool way for HabitRPG to use our API to optimally schedule in-game reinforcement to help people make long-term change faster and more effectively. I'd be happy to contribute to development as well if it would help.

Cheers, Rams

**Comment by crookedneighbor** [comment]
If this is still a desired integration, please post the info on our Trello board.
