### ISSUE TITLE
Not Receiving a Password reset email & No Support page for this sort of issue

### ISSUE THREAD

**Issue by CultD** [HabitRPG/habitica#3306]
Started an account a few days before the most recent update. Everything was great until till an issue unrelated to HabitRPG forced me to login again. Not being able to remember my password I requested a reset email but I haven't gotten one. 

I've requested a password reset email several times but I have yet to get an email. I, Also, can't reset my password for the phone that I have that I have tied to the account because there isn't a password reset option on the android app. 

I just wish there was a better place to put this because it doesn't seem like a Bug Issue, but there isn't really a support page that I could go to.

**Comment by deilann** [comment]
The android app doesn't actually use your password. It uses your API token, which currently cannot be reset by the user. So it would be a bit misleading if it had a password reset option.

So, from what I know (which might be horribly off base) it sounds like you are putting in the wrong email. Or you used the wrong email to set up your account. (Typo, whatnot.) What I'd do to resolve this, is email admin@habitrpg.com and see if things can be sorted out.

**Comment by paglias** [comment]
Also, are you sure you didn't sign up with Facebook?
Il 19/apr/2014 01:54 "deilann" notifications@github.com ha scritto:

**Comment by thepeopleseason** [comment]
If you have access to your UUID and API Token, you can now use them to login to the User Data Display tool here: https://oldgods.net/habitrpg/habitrpg_user_data_display.html

And see what email address you used to register.

**Comment by CultD** [comment]
@deilann I have check spelling again the email wasn't incorrect, but just for fun I requested a password reset again (no change to email field) and got the email so have fun trying to figure out what was wrong.

@paglias Ya i'm sure it wasn't through facebook.

@thepeopleseason This is helpful I'll keep it in mind if the problem crops up again.

**Comment by llagerlof** [comment]
I forgot my password too, and I am having the same problem.  I reset it in the password retrieval form, received the success alert, but no e-mail arrived in the gmail inboxes or even in the spam folder. I am lost.

**Comment by lefnire** [comment]
Hey all, I'm going to be looking into this soon as I can. In the mean time, try again every so often - I can verify that sometimes it doesn't work, but it's quite intermittent - starts working again randomly. More soon as I know

**Comment by lefnire** [comment]
Looks like Gmail imposes a daily quote for SMPT email-sending. The error we've been receiving is `error:  data=550 5.4.5 Daily sending quota exceeded. yv7sm82941142pac.33 - gsmtp, stage=data`. I haven't been seeing the error, because quota is exceeded before I can be emailed the error… catch 22.

Per [this](https://support.google.com/a/answer/166852?rd=1), I've tried upgrading our gmail account to a biz acct, and it seems from testing that helped. I'll keep an eye out. Anyone stuck, please try to reset your password again.
