### ISSUE TITLE
Typo in Web Site: Features

### ISSUE THREAD

**Issue by barrangatan** [HabitRPG/habitica#3307]
There's a typo on the Features page in your website: 
- It "gamifies" your life by turning all your tasks (habits, dailies, and to-dos) into little monsters you have to _conquor_.

Should be: 
It "gamifies" your life by turning all your tasks (habits, dailies, and to-dos) into little monsters you have to **conquer**.

**Comment by deilann** [comment]
This is known. It's fixed on a translation deploy that hasn't hit yet.
