### ISSUE TITLE
Post-Rebirth Cannot Purchase Shaft of the Dragon

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3308]
Prior to rebirth, I had defeated Vice and claimed my rewards. I know that users who have the Shaft of the Dragon break can repurchase it. However, I have not been able to repurchase the item since Rebirth.

At first, I thought that it was an issue of not being level 30+, but I hit level 30 and could not repurchase it. I am now level 50 (warrior) and it still does not show to repurchase.

Alys' third party tool shows it as broken -- so it's flagged at having been owned. Not sure what's up here.

**Comment by disreputabledog** [comment]
I apparently _can't_ repurchase Shaft of the Dragon after it broke. :frowning:
