### ISSUE TITLE
0 Health = No Death?

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3309]
I have exactly 0 HP according to Alys's third party tool. And yet, I am not dead. I'll look later, but I'm guessing that the check is if health is < 0. Is this intended, or should it be health <= 0?

**Comment by Atomk** [comment]
HP is a floating point value, maybe you have 0,4 life but the site shows life points as a integer-natural number.. I had the same issue on Habitrpg's main site, it is a bit confusing.

**Comment by deilann** [comment]
Third party tool pulls the float, not the rounded number. I had 0 HP.

**Comment by Atomk** [comment]
You mean this tool? --> https://github.com/Alys/tools-for-habitrpg
I didn't know it, in that case it should be the "death check", as you said.

**Comment by deilann** [comment]
Specifically the [User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html).

**Comment by deilann** [comment]
I'm guessing I possibly had _less_ than .05 HP...?

**Comment by Alys** [comment]
The User Data Display tool uses this code for displaying HP:
    var currentHealth = Math.round(user.stats.hp \* 10) / 10;
so anything a little above 0 would have been displayed as 0. I'll change my code so that if the rounded value is 0, then it will instead show you a more precise, non-zero result.

**Comment by deilann** [comment]
Yeah, I went and looked it up. And the Habit proper code. It is <=, not <,
so everything's good on all fronts.

But what weirds me out is so, Habit shows the number always rounded up in
HP bar now. But it still showed me at 0 HP.

Too bad I don't feel like trying to replicate. ;)
