### ISSUE TITLE
Death not adequately explained

### ISSUE THREAD

**Issue by ancientcampus** [HabitRPG/habitica#331]
I can find no place on the website where the consequences of character death are explained. I now know that it resets you to level one, sans items and gold - basically nearly permadeath. I only found that out while browsing the github discussions - hardly ideal for the average user with no interest in source code and bug reports. :)

**Comment by wc8** [comment]
In the meantime, check out #223 one of the comments gives an eyewitness report. ;-)
Update, I see you must have found that or one like it.

**Comment by wc8** [comment]
There's a hint on the video (you start-over like in video games), but it's probably a good thing for the FAQ.

@lefnire suggestion (rough draft) for the FAQ:
##What happens when I die?
As with digital games, you start-over from the beginning (Level 1), losing all gold and items.

**Comment by ghost** [comment]
@wc8 how about 
##Death
As with any good old school rpg when you die you start over from the beginning(level 1), losing all gold and items. Plus any quarters you put into the machine.

**Comment by wc8** [comment]
Better.

**Comment by ghost** [comment]
@wc8 best
##Death
As with any good old school rpg when you die you start over from the beginning(level 1), losing all gold and items. Plus any quarters you put into the machine and the hours of your life. Fear not upon death you are revived though and this time it doesn't affect your in game score.

**Comment by Pandoro** [comment]
So has this been posted somewhere? It will probably be changed at some point with the fierce discussions going on, but until that time, it might be a good idea indeed to explain the results of dying.

**Comment by horusofoz** [comment]
Devs have been advised of the need for the current state of death and efforts to find a better solution to be better explained. Monitor [#223](https://github.com/lefnire/habitrpg/issues/223) for now to see which way the topic goes.

**Comment by wc8** [comment]
@Pandoro it's not in the wiki yet. I agree current results of dying need to be explained, to be updated if/when changed.

**Comment by horusofoz** [comment]
@wc8 Maybe write an explanation in the forum? 

The FAQ section linked in the app footer currently goes to a page inaccessible for myself. I assume when the FAQ is completed it would include this info?

**Comment by wc8** [comment]
The FAQ is now [here](http://community.habitrpg.com/faq-page). The footer link must need updating.
I have now added a Q&A in the FAQ: [What happens when my character dies?](http://community.habitrpg.com/content/what-happens-when-my-character-dies).
It can be updated as any adjustments are made.
