### ISSUE TITLE
Filter multiple tags

### ISSUE THREAD

**Issue by SuPete** [HabitRPG/habitica#3311]
When selecting more than one tag in the filter at the top of the tasks page the filter only returns tasks that has all the selected tags attached to them. Shouldn't the list contain all the tasks that has one or more of the tags selected for filtering?

Ex.
If i select morning and evening the resulting page only contains tasks that actually have both tags attached to them.

Tested with Chrome

**Comment by deilann** [comment]
Currently that is expected behavior. It's an AND statement, not an OR statement.

The best place to discuss this is actually not Github (as it's expected behavior), but [this Trello card](https://trello.com/c/q7v02jAw/43-tags-categories).
