### ISSUE TITLE
"Burst of flames" spell doesn't mark a task as done

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3312]
The "Burst of flames" mage's spell used to give more experience when you cast it on a task and mark it as done. Now this spell gives you exp and gold, but the task is not marked as done, you have to do it "manually" afterwards with no spell. I don't think it's supposed to be like that as you can cast "Burst of flames" on a daily or a task many times, before you have mana for that.

**Comment by deilann** [comment]
This is expected (and desired) behavior. Spells are separate from completing tasks. You can cast a spell on incomplete tasks and can cast a spell multiple times on one task.

I can also assure you that in the time you have been on Habit, it has never been the case that you could check off a daily by casting a spell. This would actually trigger a double cast, back in the day, sometimes leaving you with negative mana. It's not that it gives more experience when you cast it on a task then mark it as done. Marking the task as done gives you experience and casting the spell gives you experience.

**Comment by ghost** [comment]
@deilann as I feel how your answers are getting personal I should say sorry if I have ever said or do something wrong or insulted you or anyone in any way. It wasn't intentional, really.

As far as this question is concerned, I just described it as I remember, and I can be wrong for sure. If the current behavior is desired, can I at least suggest disabling the spells for completed tasks?

**Comment by deilann** [comment]
Not personal at all? Don't feel insulted, nothing going on at all? I just happen to know that you signed up in January of this year, and the ability to check off and cast simultaneously was taken away long before that.

I'm not sure why if the behavior is as desired disabling spells for completed would be the right thing to do either. The idea is that you can cast the spells on whatever tasks you want. They're independent of doing the tasks. I'm not sure why you shouldn't be able to cast them on completed tasks?

**Comment by deilann** [comment]
(I also can't remember what the last Github ticket you posted is or when it was, so definitely not personal?)

**Comment by deilann** [comment]
(All that being said, you probably _should_ have searched for this first, as it's been posted many times and been responded to similarly. :P)

**Comment by ghost** [comment]
@deilann I really should have, sorry... The reason for 1. was that spells on habits seem to do the thing; as for 2. tasks are often described as monsters to fight with on hrpg static pages and in guides, so casting a spell on defeated enemy may sound a bit strange. But thanks for clearing everything up, I don't have any more questions.

**Comment by deilann** [comment]
@GitHubSphinx The :P there was to denote friendly teasing. I'm not actually upset that you didn't search. For future reference, I tend to be pretty blunt and not overly focused on tact. If I say something short and to the point, it's most likely that I'm being short and to the point... not that I'm upset.

As for your comment... I don't really view dailies as a defeated enemy... after all, they're just subdued for this turn. They'll try to hit you again tomorrow. You _can_ cast spells on completed to-dos... but it won't do much for you.

wrt spell strategy: BoF, you'd do better casting on a checked off daily. It's based on task value, and after you check off the daily, the task value goes up. So the spell will be worth more. Other spells, you might have more reason to cast them on non-checked off tasks that you don't think you'll get to-- particularly ones that reduce redness, and so would cut back on the amount of damage you'd take.
