### ISSUE TITLE
Quest Scroll Not Appearing

### ISSUE THREAD

**Issue by bingbangzoom** [HabitRPG/habitica#3313]
Hi. I'm on Chrome and recently bought 2 Stag Quests for my party but they do not show up in my inventory. My party recently completed the "Egg Hunt" Quest. Before completing this quest, I did have the Stag Quest Scrolls but now (after completing it) I do not. I refreshed HabitRPG various times. I completed a Stag Quest previously and it worked fine. The picture attached is what my Market page looks like. I'm sorry if this is a repeat and please direct elsewhere if it is.
![stag bug](https://cloud.githubusercontent.com/assets/6492597/2748648/3d9ad766-c7ce-11e3-9e4a-51dce384bef8.PNG)

**Comment by deilann** [comment]
Yeah, this be the negative scroll bug. What's your UUID? I'll refund you the gems and see if repurchasing the scrolls works.

As a heads up, so here's what's happening: for some reason, when you have stacks of scrolls, sometimes the systems decides to eat them into negative oblivion. It's usually best to buy only one scroll at a time.

**Comment by bingbangzoom** [comment]
Here's my User ID (hopefully that's what you asked for): bac90153-7cb5-46c3-94d1-c01a0287f588
Thank you so so much!

**Comment by deilann** [comment]
I refunded you your 8 gems. Can you buy a single Spirit of Spring scroll
and see if it shows up?

**Comment by bingbangzoom** [comment]
It is working now! Thank you so much. However, the number of quest scrolls still says 3 (including the two quest scrolls I bought but didn't work). I don't mind that though. You've helped so much!
![quest scroll](https://cloud.githubusercontent.com/assets/6492597/2749934/eb32790a-c838-11e3-991c-71def7ab0018.PNG)

**Comment by deilann** [comment]
Ahh, that means another scroll somewhere is probably in the negative
values...

**Comment by bingbangzoom** [comment]
Damn. I don't mind it though. As long as I can buy/offer quest scrolls, it's cool. Unless it's bad..

**Comment by deilann** [comment]
It means that a specific scroll may not show up if you purchase it. But
without going into the database (which I can't because I don't have
access), there's no way for me to figure out which one it is.

So, if you try to purchase a scroll in the future and have this problem,
just let me know, and I'll get you sorted. :)
