### ISSUE TITLE
boss disappeared (Dragon Vice)

### ISSUE THREAD

**Issue by emz83** [HabitRPG/habitica#3314]
I just signed in today after starting the dragon yesterday and it's not there anymore. The scroll is also not in my inv anymore.

**Comment by deilann** [comment]
Can you refresh your party page and tell me what happens?

**Comment by emz83** [comment]
Did so. Looks the same.

**Comment by deilann** [comment]
Can you do a hard refresh? (shift-ctrl-F5)

I'm assuming you're in a solo party?

**Comment by emz83** [comment]
Solo party yes. 

Ah, what's the command if you're using a mac?

**Comment by deilann** [comment]
Sub cmd for ctrl

Are you on an older account, btw? Back from during the Derby days?

**Comment by emz83** [comment]
You mean when it'd been crashing every hour? If so then yes.

**Comment by emz83** [comment]
shift cmd f5 does nothing

**Comment by deilann** [comment]
There's a good chance that you're actually secretly in two parties, in that
case. What I'm going to have you do is leave the party you're in. (If you
end up seeing Vice, don't leave, that's the correct party. But if you ever
don't see Vice, leave that party immediately.)

Here's the bad news: if this isn't the bug, welp, it's not going to fix the
problem. But the good-bad news, is that then I'll be able to give you 4
gems you can use to buy a new, unbugged Vice scroll.

**Comment by emz83** [comment]
oh! that fixed it! thanks.

**Comment by deilann** [comment]
YAY! I'm magic!
