### ISSUE TITLE
Notification Pop-Up Doesn't Go Away Without Clicking, Blocks Other Buttons

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3315]
I clicked on the new notification icon, determined there was nothing I cared to look at immediately - and now it's stuck there. Clicking on the main window doesn't get rid of it. Clicking on dailies seems to work in spite of the presence of the notification pop-up, but I think my attempt to click a reward failed, perhaps because it was partly buried under the notification pop up. At least, it didn't produce the transient pop-up deducting the price, or didn't do it right away. (Someone walked into my office and distracted me shortly thereafter.)  The &lt;esc&gt; key doesn't make the notification pop up go away either, not even if I click somewhere in the popup's title bar in an attempt to select it.

The notification pop-up finally went away when I selected one of the notifications. I haven't tried simply deleting one of them - assuming that's what the x to the right of the name does.

**Comment by denis-sokolov** [comment]
If I press on the new notification icon again, the notification area is closed then.

**Comment by Alys** [comment]
This is expected behaviour so I'm closing this. The popup stays open until you select a guild to visit or choose to close it, in line with how the menus work. I believe this behaviour is good for accessibility reasons.
