### ISSUE TITLE
Issue: Daily Task is moved to Habit section and now won't delete

### ISSUE THREAD

**Issue by avpan** [HabitRPG/habitica#3316]
As it says, a daily was moved to habit section and now I can't delete it. 

my user ID: 138f113c-497a-46f2-ba3c-e7c2de1641f4

**Comment by Alys** [comment]
@avpan : Is this problem still occurring? If so, you'll need to tell us the text of the daily/habit so that we can fix it. If there's private information in the text, tell us as much as you can so that it can be identified uniquely.

**Comment by Alys** [comment]
closing this because it's a duplicate of https://github.com/HabitRPG/habitrpg/issues/2334 and no response about whether it's still a problem

@avpan, if you still can't delete it, tell us and we can reopen this.
