### ISSUE TITLE
quest pets triggering beast master notification

### ISSUE THREAD

**Issue by rhonnnnie** [HabitRPG/habitica#3320]
Haven't seen this issue mentioned anywhere yet so making a new ticket :)
After I got the Beast Master achievement, every time I hatch a new quest pet the notification will pop up again?
Just a little thing, but after the Egg Quest or something with 10 eggs lined up it got a little irritating having to close it every time... 

Thanks :D
(UUID is 76416b9e-307f-43ad-8a1a-cce5225eebe1)

**Comment by thepeopleseason** [comment]
Duplicate of #2990
