### ISSUE TITLE
Hatched quest egg, potion & egg gone from Market but do not appear in Stable.

### ISSUE THREAD

**Issue by onehaslepers** [HabitRPG/habitica#3326]
Hatched a plain egg with Cotton Candy Pink potion.  Potion is gone, egg count is down one (was 7, is now 6), but there is no cotton candy pink egg in my stable.

Synced, no change.  Refreshed, no change.  Signed out & back in, no change.

I don't mind losing the potion (I know I'll get one as a drop eventually, or I can buy it), but losing the egg is aggravating because I can't just buy another egg -- I'll have to ask my party to do the whole quest again. 

What can I do?

**Comment by Alys** [comment]
Do a hard refresh now even if you've done one before (i.e., shift+ctrl+F5 or shift+cmd+F5). Is it appearing in the stable now? If not, please tell us your [User ID](https://habitrpg.com/#/options/settings/api) (not API Token), and add two screenshots to this bug report: one showing all of your current unhatched eggs and potions; and another showing the full row of Plain Egg pets (i.e., the ones you have hatched and the empty paw prints in that row). There might be something in those screenshots that gives the developers a hint about what's wrong.

**Comment by onehaslepers** [comment]
Hoorah!  Both the egg and the potion are back.  Thank you.
