### ISSUE TITLE
Little green blob appears in mouseover for class selection

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3327]
Alas, I don't have a screenshot of it, but when you use the Class Change feature and mouse over one of the class sample avatars, a little green box appears in the upper left. It appears that the bubble meant to show the profile name when hovering over yourself or a party member doesn't, under the recently revamped UI, know not to appear when there is no name to display.

**Comment by lefnire** [comment]
Confirmed. And it doesn't show you which class you have selected before clicking "Select"

**Comment by usernamenumber** [comment]
I've created a pull request that attempts to fix both of these problems. 

https://github.com/HabitRPG/habitrpg/pull/3360

**Comment by Alys** [comment]
I can't replicate this so it looks like it's being fixed. Closing, but reopen if I'm wrong.
