### ISSUE TITLE
Problems Running Locally

### ISSUE THREAD

**Issue by kitsully** [HabitRPG/habitica#3328]
Hey Guys,

I can't for the life of me get a local version of this running. I am a Software Engineer who uses this product and really want to contribute. After starting the vagrant box I do the following:

```
vagrant@habitrpg:/vagrant$ npm start            

> habitrpg@0.0.0-152 start /vagrant
> grunt run:dev

Running "stylus:build" (stylus) task
File build/app.css created.
File build/static.css created.

Running "concurrent:dev" (concurrent) task
Running "watch" task
Waiting...Running "nodemon:dev" (nodemon) task
22 Apr 02:53:19 - [nodemon] v0.7.10
22 Apr 02:53:19 - [nodemon] to restart at any time, enter `rs`
22 Apr 02:53:19 - [nodemon] watching: /vagrant
22 Apr 02:53:19 - [nodemon] starting `node ./src/server.js`
22 Apr 02:53:19 - [nodemon] reading ignore list
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
info: Express server listening on port 3000
info: Express server listening on port 3000
```

When I try going to localhost:3000 I get a no data received page. I'm not sure if I'm doing something wrong or if its something else. Any help would be appreciated. @thepeopleseason I'm told I'm supposed to tag you in this.

**Comment by paglias** [comment]
@kitsully when you try to open localhost:3000 something is logged in the terminal?

**Comment by thepeopleseason** [comment]
@kitsully Two things: 
1. Make sure when you `vagrant up` that you see the following lines: 
   
   ==> default: Forwarding ports...
       default: 3000 => 3000 (adapter 1)

If you don't, pay special attention to the lines scrolling by. You may already have something running on port 3000 of your host machine, and it can't forward the vagrant machine's port appropriately. It will find another port where you might need to go to http://localhost:3001/ (the actual port will be listed in the startup messages for the vagrant box). 
1.  I believe the final message that I receive before pulling up the site locally was `info: Connected to Mongoose` Try and wait a little bit longer after you get the "listening on port 3000" message, then try hitting the page with your browser.

**Comment by kitsully** [comment]
@paglias No nothing is logged in the terminal. And @thepeopleseason it looks like it is running on port 3004. I'm not entirely sure why as I don't have anything running currently on port 3000, but that isn't a big deal. I waited until `info: Connected to Mongoose` was displayed and then I hit the site at localhost:3004 and now I'm seeing this in my browser:

```
SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
Protocol mismatch.
```

**Comment by kitsully** [comment]
Never-mind it is working now, guess I just needed to be more patient. Thanks guys.

**Comment by thepeopleseason** [comment]
Glad it's working now! Good luck!
