### ISSUE TITLE
Cannot Move Grayed Out Things Up Or Down

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#333]
The title says it all. This is affecting to-dos and dailies.

**Comment by StanLindsey** [comment]
Are these greyed out items ones that have been checked off (like with dailies?) or similar to the previous error where if you deleted a task/habit it kept the "tab" but removed the text?

**Comment by ghost** [comment]
Checked off

**Comment by StanLindsey** [comment]
Cheers, added to bugslist. How did you manage to check off a habit though? (Or did you mean Dailies & to-dos?)

**Comment by ghost** [comment]
Fixed op.

**Comment by Pandoro** [comment]
Will close this as it is an old thread and lefnire will soon start to fix the whole drag and drop vs. select problem.
