### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by EricRFMA** [HabitRPG/habitica#3330]
After closing my browser (Safari 6.1.3, Mac OS 10.8.5) and restarting it, I can't log in to HabitRPG.  It tells me my username and/or password are invalid.

I tried the advice given about 1Password, and entered everything manually.  Then, I did a password reset (twice), tried entering the new password manually, and it gave me the same message (both times).

Can you advise?

Thanks!

-Eric

**Comment by deilann** [comment]
That means that you are entering the wrong password or username.

If you signed up via Facebook, you are going to have to use the Facebook
log-in.

If you didn't sign up via Facebook, your username is not the same thing as
your display name. It is the username you used to sign up for Habit. My
guess here is that you are not entering the correct username.

**Comment by EricRFMA** [comment]
My guess is that you are absolutely correct!

1Password was entering my e-mail address instead of username, so I incorrectly assumed that that was correct.  Once you pointed out the obvious, I noticed that the prompt in the empty username field said "Username" not "e-mail address".

Thanks for  your help!!

**Comment by deilann** [comment]
Yay! It's fixed. Glad to help.
