### ISSUE TITLE
Market: Quest scroll purchase fail

### ISSUE THREAD

**Issue by MunchmaKuchi** [HabitRPG/habitica#3336]
I bought a Spirit of Spring quest scroll, and my gems to pay for it disappeared, but the scroll hasn't appeared in my inventory.  

I'm using Chrome version 34.0.1847.116 on a MacBook Pro.

My user ID is bef51a84-6849-4ff8-95be-aa29329c144e

I think I've lost the relevant console info. All I have in the log is:

> Attr.specified is deprecated. Its value is always true.
> Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1397165098.html:1
> Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by deilann** [comment]
Two questions:

1) How many scrolls does it say you have in your inventory?
2) How many scrolls do you _actually_ own?

There's a bug where you end up with a negative number of a scroll -- I'm guessing that's what's happened here. I've refunded you four gems. If you have the same number of scrolls as it says you own, you should be able to repurchase the scroll and it should show up. (Purchasing the quest last time, in this case, would have turned a -1 into a 0.)

If the numbers aren't even, you may still be able to repurchase and it would be fine -- this means that on top of Spirit of Spring being -1, you also have another negative quantity of scrolls somewhere.

Either way, repurchase and let me know. :)

**Comment by MunchmaKuchi** [comment]
I haven't actually kept track of the number purchased vs owned in the past. Do you mean whether these two numbers reconcile on the Market page?
![screen shot 2014-04-23 at 8 04 04 am](https://cloud.githubusercontent.com/assets/3291093/2779098/b927c510-caf8-11e3-961d-49bbf9bb1dde.png)

I repurchased the scroll with no problems after taking that screenshot. Thank you! That was amazingly fast.

I will keep an eye on those numbers for future purchases. This has happened to me once before, but I was too lazy to document it. Thanks again :grin:

**Comment by deilann** [comment]
Indeed -- reconciling numbers. If you had a secret -1 quantity scroll in
there, you would see the 5 scrolls you had, but it would show "Quest
Scrolls (4)"
@lefnire -- I'm thinking of doing a quick fix just to reduce the amount of
support on this until the issue can be resolved: adding in an if statement
to purchases that checks and sees if the quantity is negative and if so
makes the quantity zero. It doesn't fix the problem of duplicated scroll
removal, but it will keep this issue from popping up so regularly.

**Comment by deilann** [comment]
Also, no problem. XD
