### ISSUE TITLE
Blank blue notification when use health portion

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3337]
Subject is on the top to the right. Tested on mobile browser http://i61.tinypic.com/331ezav.jpg

**Comment by deilann** [comment]
Can you do a search for me? Not at computer but i know there's a ticket on
the blank health potion notification

**Comment by thepeopleseason** [comment]
#3183

**Comment by thepeopleseason** [comment]
Closed as duplicate

**Comment by ghost** [comment]
Sorry about the duplicate. But that was about notifAcation :-P
