### ISSUE TITLE
Chat notifications should update the toolbar icon

### ISSUE THREAD

**Issue by SyntaxPickax** [HabitRPG/habitica#3338]
Years of behavioral conditioning by social media sites of have left me looking for some visual cue for pending chat notifications. It'd be great if the chat notifications icon updated to give some indication of the unread notifications. I'm thinking something like changing the speech bubble to red or showing a number, e.g., ![screen shot 2014-04-23 at 12 23 07 pm](https://cloud.githubusercontent.com/assets/1245093/2782246/3ef246a6-cb1d-11e3-98a5-12e86c3ff2af.png)

If I'm not mistaken, the chat icon used to have some visual cue before the recent UI update. It'd be nice to bring that back.

**Comment by deilann** [comment]
This is a planned feature that is on its  way ASAP. I'd share the ticket
with you, but on mobile. A quick search should find you the ticket.

**Comment by SyntaxPickax** [comment]
Oh, very good. Thanks. I'm looking forward to it.

**Comment by Cassolotl** [comment]
I would like to see the "real" issue page for this, but I can't find it for some reason?

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/3270

**Comment by Cassolotl** [comment]
Thank you! :)
