### ISSUE TITLE
Repeated penalties for missed dailies

### ISSUE THREAD

**Issue by weelillad** [HabitRPG/habitica#334]
This happened about 7 hours ago (12.30am local time) and just now. I was trying to access HabitRPG using Dolphin Browser on Android. After I logged in, the page loads my data, then deducts HP for missed dailies. Before I can do anything, the "Offline - Reconnect" message appears, and the page refreshes itself. After refreshing, the page then proceeded to deduct my HP again, the same amount as it did the first time. I tried closing the page and re-opening it, I also tried using the stock Android browser, and the results were the same. I lost >20 HP before I gave up. This morning I accessed the page using Chrome on my PC, and I lost another chunk of HP for missing my dailies. It seems to me like the page doesn't work well on mobile browsers.

**Comment by StanLindsey** [comment]
Thanks for the details @weelillad - I think we know the sort of ball park this error is stemming from and it is also causing a number of other bugs and issues but in this case is being extrapolated by bitty mobile connect.

Can you confirm if this was on Wi-Fi or standard signal? (4G, 3G, high/low signal if possible)

**Comment by weelillad** [comment]
Thanks for the quick reply! I was on Wi-fi when it happened. Other websites
load quickly, so my internet connection was working fine.

**Comment by StanLindsey** [comment]
Thanks for the info, it helps. That means we can't blame it on your phone connection though. =D

**Comment by horusofoz** [comment]
@weelillad Can you confirm this is still happening? If so can you create a new daily and advise if the issue still occurs there?

**Comment by weelillad** [comment]
Confirmed that it is working properly now. When I load the page using my
handphone browser, on Wifi, it still refreshes itself constantly, however
the daily penalty only happens once.

Weirdly, when I load the page using cellular data connection, with Wifi
off, the page does not keep refreshing itself. Not sure if this little
problem is worth creating a ticket for..

**Comment by Pandoro** [comment]
This has also been recorded in #495 where it happened only on a phone. I will close this thread in favor of the new one, as it only seems to happen on smartphones and it was reproduces by lefnire as well. Feel free to post there if you have any further issues, tips or hints :) 

And of course, thank you for bringing this up!
