### ISSUE TITLE
How to get login from 3rd party Android app

### ISSUE THREAD

**Issue by bytehala** [HabitRPG/habitica#3340]
Hi, I wanted to integrate HabitRPG into my app, but I can't find how to do this. The documentation here https://habitrpg.com/static/api assumes that I already have the api-user and api-key.

What I wanted to know is, how to get those values from a username/password login. How do I send the user/password over to the URL to get these?

Any resources I can read?

**Comment by deilann** [comment]
You don't as far as I know. Third party apps need to use User ID and API
token. Is there a reason this isn't feasible? I can think of a lot of
reasons to not integrate username pass for third party.

**Comment by bytehala** [comment]
Oh okay, no particular reason for it. I just thought it's better to do user/pass since it's the norm everywhere.
And I thought it's possible since the Habit AndroRPG app has the user/pass login.

No biggie, let's close this issue then.

**Comment by lefnire** [comment]
The route is `POST /api/v2/user/auth/local`. send body as `{username:"...", password:"..."}`, and the route returns UUID & API Token. Store those locally for future API calls. You can't auth calls with uname/pass, you require UUID & Token - but you can do above method to _retrieve_ uuid/token from uname/pw

**Comment by deilann** [comment]
Okay, so it's that you can't retrieve username/pass from UUID/API Token,
but you can do it the other way around?

I feel like last time the reverse question might have been asked.

**Comment by lefnire** [comment]
Correct, you can't get password from anything save "forgot password". It's
salted and hashed anyway, so it wouldn't do anyone good.
