### ISSUE TITLE
party boss not getting damage

### ISSUE THREAD

**Issue by emz83** [HabitRPG/habitica#3342]
so I previously had to exit party for my boss to reappear, but now its not getting damage despite several perfect days. do i need to exit the party again??

**Comment by emz83** [comment]
the boss is dragon vice part 1, if that helps

**Comment by emz83** [comment]
still not getting damage despite completing tasks/dailies

**Comment by uberniftacular** [comment]
I'm having the same issue. I started the Vice part 1 quest yesterday, had a perfect day and completed a lot of to-dos, but this morning the boss still shows that it's at full health.

**Comment by deilann** [comment]
Did you refresh the party page?

**Comment by uberniftacular** [comment]
Huh. Apparently I hadn't, because now it's showing up as having taken damage. (I guess I was assuming that because everything else had refreshed on its own, that the party page must have done so as well.)
Thanks.
