### ISSUE TITLE
Reloading page loses data

### ISSUE THREAD

**Issue by radicallyradish** [HabitRPG/habitica#3343]
This is only with Pets/drops, but whenever I reload the page after hatching an egg or feeding a pet, the changes aren't saved and the food goes back into my inventory as well as the unhatched eggs. Suggestions?

**Comment by deilann** [comment]
Sounds like you're hitting server errors. Reloading the page isn't losing
data -- the data never saved to the server, so you're getting the data that
actually exist.

Can you peruse this ticket for me, and tell me if it sounds familiar?:
https://github.com/HabitRPG/habitrpg/issues/3279

**Comment by radicallyradish** [comment]
Yeah, my problem sounds exactly like that. Unfortunately, I don't really have another computer handy to try it on, at least not today. I did, however, try it on Firefox and it worked, so maybe it's just chrome?

**Comment by deilann** [comment]
specifically something about your chrome - I (and most users) use chrome
and are fine. hmmm can you move to that thread?

**Comment by radicallyradish** [comment]
hmmm that is interesting. And of course!
