### ISSUE TITLE
Party member initiated quest & then left party

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3344]
One of our party members (as far as I can tell) initiated the egg quest for the second time and then quit the party (All of the remaining party members show Pending and usually the one who initiates it shows as Accepted). We have a Begin button but no Abort button. Is there a way to get rid of this quest invitation with the person who initiated it no longer around?

Our party ID is Group ID: 64991f5e-be81-4568-864b-0f2813964d12

**Comment by deilann** [comment]
I believe only the person who initiated the quest sees a "begin" button -- so you must have been the one to initiate it.

**Comment by deilann** [comment]
But no, there is no way to do that. The only real workaround is to form a new party. It can have the same name and everything, but everyone leaves, party leader creates a new party, then invites everyone back.

**Comment by ghost** [comment]
Then it's a glitch because I haven't been anywhere near the scrolls so there's no way I initiated this quest (not to mention that I was listed as 'Pending' when I logged in this morning which I wouldn't have been if I had initiated it). This is certainly a fine way to screw a party over when leaving it.

**Comment by deilann** [comment]
Yes, it is. :c

Maybe the begin button shows for party leaders? Not sure.

But yes, you have to leave the party and make a new one.

Does it at least make you feel better that this means they'll never be able
to recover their scroll? :P

**Comment by ghost** [comment]
I'm also not the party leader. It really shouldn't be possible to start a quest and then flounce. :/

**Comment by deilann** [comment]
Check this out: https://github.com/HabitRPG/habitrpg/issues/3345

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4002
Any quests whose quest owner is no longer in the party can now be cancelled/aborted by other party members. More details at that link.
