### ISSUE TITLE
If Quest Leader Leaves Party or Goes Inactive, Change Quest Leader

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3345]
So, a party gets stuck in limbo if the quest leader goes inactive or leaves a quest hanging.

I suggest that if the quest leader doesn't log in (look at last cron?) for X days or leaves the party, the quest leader be changed to the party leader.
##

**Comment by ghost** [comment]
I would further suggest that if a quest leader initiates a quest and leaves the party before it starts that the quest automatically abort.

**Comment by deilann** [comment]
Oooh, I like that.

At the same time, it could be pretty frustrating if you work on a boss for weeks and then the quest leader flounces. 'Course, if the quest leader wanted to save their scroll, they should abort pre-flounce anyway.

**Comment by ghost** [comment]
That's why I specified 'Before it starts'. If the party has accepted the quest then the Quest should continue (with maybe the Abort button going to the party leader by default if the quest leader bails).

**Comment by deilann** [comment]
Yeah, if the party leader becomes the quest leader, they'll be able to
abort.

**Comment by Alys** [comment]
Partial fix for some of what's discussed here: https://github.com/HabitRPG/habitrpg/pull/4002
Any quests whose quest owner is no longer in the party can now be cancelled/aborted by other party members. More details at that link.

**Comment by Alys** [comment]
I'm closing this because now that party leaders also have control over quests, it's less critical that the quest owner be active, and so this is more of a feature request than a bug report now.
