### ISSUE TITLE
Can't Wear WonderCon Battle Gear Collar

### ISSUE THREAD

**Issue by zincotroid** [HabitRPG/habitica#3346]
All the other Battle Gear from WonderCon seems fine, but everytime I put on a collar and sync or move to another page it's removed from my avatar.

**Comment by zincotroid** [comment]
Alys said I should add my user ID: 9047e584-f2b2-474b-ba5e-e9eb1f9c2770. 

It seems like the collar sticks when moving between different pages on the site, sometimes, but if I sync it's gone.

**Comment by deilann** [comment]
Have you tried recently? Have you done a hard refresh or logged in or out
recently?

**Comment by zincotroid** [comment]
Yes, try all the time. I just tried logging out and back in and equipping the collar and hard refreshing and it was gone. I tried equipping it as battle gear and as a costume. The one thing I did notice was that when I equip it I get no message. When I unequip it a blue message says "Ruby Collar equipped."

**Comment by deilann** [comment]
That's very strange.

What happens if you unequip it, it says it's equipped, and then you do a
hard refresh?

**Comment by zincotroid** [comment]
That didn't work. Good thinking though. I did notice that when I put it on and refresh when the page first comes up I still have the collar and then it vanishes. If I put it on and leave the site and come back it is gone immediately. If I equip it and don't sync, but just move between tasks and social and inventory, including sub pages, it stays on. If I sync, reload, or leave and come back it's gone.

**Comment by deilann** [comment]
So strange.

Is it just the ruby collar, or all collars?

**Comment by zincotroid** [comment]
All the collars and only the collars. The capes and masks I got with the same code work fine.

**Comment by deilann** [comment]
If you take off all your clothes, and just try on the collar, what happens?

...all your habit clothes. Disrobing in meat space will not likely have any
impact on this problem.

**Comment by lefnire** [comment]
It's likely not properly setup in the HTML, no need for unplugging the
computer and turning around 3 times :-) I'll check it out when I get a
moment

**Comment by deilann** [comment]
But saying "Bloody Mary" three times in the reflection of a CRT monitor
might help?

**Comment by lefnire** [comment]
> But saying "Bloody Mary" three times in the reflection of a CRT monitor
> might help?

GH needs a :like:

**Comment by zincotroid** [comment]
I tried taking all the other equipment off, putting the collar on refreshing, no good. 

One thing I did notice was that all on my equipment says it's equipping when I remove it.

**Comment by deilann** [comment]
That is not just you! It's doing that to me as well, actually.

**Comment by lefnire** [comment]
Fixed, will push tomorrow

**Comment by zincotroid** [comment]
Oh, awesome! Thanks very much!
