### ISSUE TITLE
Habits reordering is broken after AnkiHRPG added habits

### ISSUE THREAD

**Issue by Frazer** [HabitRPG/habitica#3347]
I use AnkiHRPG.

It added some habits, and when I tried to move them, the ordering gets reordered

It seems I can move my other tasks and the reordering works, but when moving the added tasks (IE Anki Deck Complete task) it moves to random spots

**Comment by csakai** [comment]
I don't know if my issue has been covered or if it is related to this issue, but I wanted to add that reordering of any to-dos does not actually work. It'll appear reordered, the page will refresh, and then it will be back to the old order.

**Comment by Frazer** [comment]
the To-Do's  are a different issue.

It has been covered in a different thread.  Someone has worked out how to fix it, but hasn't implemented it yet.

You can encourage them here:
https://github.com/HabitRPG/habitrpg/issues/2606

or pay someone to do it

**Comment by eshapard** [comment]
AnkiHRPG developer here,
That's strange. I haven't noticed any problem ordering the habits created by AnkiHRPG. I noticed this issue was nine months ago. Are you still having an issue with this?

**Comment by Frazer** [comment]
I dont use it any more.

but have you used any 3rd party apps to add habits?
ᐧ

**Comment by Alys** [comment]
I'm closing this since @Frazer doesn't use AnkiHRPG now and @csakai's To-Do issue is unrelated (and is covered by the issue linked to above). We can reopen this if it becomes apparent that the problem still exists.
