### ISSUE TITLE
April Mystery Items not added to inventory when I clicked the icon

### ISSUE THREAD

**Issue by notapooka** [HabitRPG/habitica#3348]
Today, my notifications said that I had two new Mystery Items, which I assumed were the Mystery Items for April. I went to my inventory, and indeed there was a little "2" next to the Mystery Item icon. I clicked the icon, and the "2" turned into a "1," but I didn't get a pop-up saying I'd received any item. I clicked it again, same thing, and now my Mystery Items box says it's empty. However, I do not have any new items in my inventory under Mystery.

**Comment by lefnire** [comment]
refresh & try again

**Comment by lefnire** [comment]
any time new item definitions +assets are added to the website, there's no way of getting them into the browser save a refresh. I hope to get a red bar up top "your browser needs a refresh" eventually, but in the short-term... that

**Comment by notapooka** [comment]
That did it. Thanks!
