### ISSUE TITLE
Invalid Login Issue

### ISSUE THREAD

**Issue by dapperfex** [HabitRPG/habitica#335]
Recently logged out of habit and when I tried to get back in it kept giving me invalid login errors. When I try to register a new account it says my username is taken, so the account still exists, I just can't access it. I really don't want to have to start over so help ASAP is needed.

**Comment by StanLindsey** [comment]
@lefnire is the only one who has direct access to the DB atm. He'll get you sorted soon hopefully. Don't threat! =D

**Comment by lefnire** [comment]
[email](mailto:tylerrenelle@gmail.com) me your username, email, or UUID

**Comment by dapperfex** [comment]
Thank you! Just sent it your way.

**Comment by Pandoro** [comment]
Has this been resolved? Or are there still issues?

**Comment by StanLindsey** [comment]
I'll close as they are in email contact.
