### ISSUE TITLE
Can't buy Rebirth Orb

### ISSUE THREAD

**Issue by kelmcdonald** [HabitRPG/habitica#3350]
I am at level 100. But the market won't let me buy the orb of rebirth. It says I don't have enough gems. I thought the Orb of rebirth was supposed to be free at level 100

**Comment by deilann** [comment]
I think the quick-fix I put through may still check and see if you have 8
gems, but doesn't take them.

The actually full fix is not yet complete -- this feature doesn't really
exist yet. I still need to test it. Once it's tested and clean, everything
should be good. Hopefully, within the next week.

**Comment by kelmcdonald** [comment]
Any progress with this? Kinda frustrating to not make progress

**Comment by deilann** [comment]
SabreCat may be able to test my code soon, but I still can't test it.

What's your UUID? I'll put 8 gems in your account then you tell me you've
rebirthed and I'll remove them.

**Comment by kelmcdonald** [comment]
e0a14806-b882-4621-bd04-9c37a72adb91

**Comment by deilann** [comment]
Huh. You have negative 680 gems. I wonder if that's related.

**Comment by kelmcdonald** [comment]
ok i'm reborn

**Comment by deilann** [comment]
Awesome! Sorry I haven't gotten it done yet. :c

**Comment by jobywalker** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg-shared/pull/262 -- the CoffeeScript interpreter does something not very intuitive in the boolean tests so the freeRebirth flag wouldn't be set.

**Comment by deilann** [comment]
Actually, this was fixed when I removed the level cap. The freeRebirth flag is unrelated to actually purchasing the orb. I just didn't close this ticket when I removed the level cap.
