### ISSUE TITLE
Quest restarted, boss magically healed.

### ISSUE THREAD

**Issue by neverasuspect** [HabitRPG/habitica#3352]
Started the gryphon quest with all party members, did 71.5 damage with the first 3 members that checked in. Sometime in the afternoon, the boss repaired all damage and was back to full strength when the 4th party member checked in to do 29.3 damage which lasted. 
User ID 0309ae9c-d809-4506-8a09-0b8848233171  was missing a second quest scroll after the "restart" and today not all members are incurring damage against the boss when they log in.

Group ID: 648d3867-a7b6-4521-9114-1b62cf5aedea
UserIDS: 0309ae9c-d809-4506-8a09-0b8848233171
30b5fa5a-d485-4ca6-9016-7ebb748adc24
32a32f06-4190-451f-af0d-6e34e9b8d6b7
![habitrpg](https://cloud.githubusercontent.com/assets/6492558/2800248/9b4c365c-cc6f-11e3-9836-fe6ce80706bb.jpg)

de98bdf3-4846-4e56-9325-ec488019a9dc

**Comment by deilann** [comment]
See https://github.com/HabitRPG/habitrpg/issues/2657 and https://github.com/HabitRPG/habitrpg/issues/2592 (the latter one may not seem related at first, but that is the consequence of the extra missing scroll from you, and this may actually be a HUGE key in understanding why that happens)

**Comment by neverasuspect** [comment]
Thank you, I've read them through. Can I please get the 4 gems refunded so I can repurchase and replace the missing scroll at least?

**Comment by deilann** [comment]
Right! Of course. Don't know why my brain skipped over doing that. :)

**Comment by deilann** [comment]
Done!
