### ISSUE TITLE
Quest finished, no rewards

### ISSUE THREAD

**Issue by Thymekitt** [HabitRPG/habitica#3354]
I finished the last stage of vice awakens and I didn't get any of the egg rewards that were expected.

**Comment by deilann** [comment]
Did you refresh the screen? Do a hard refresh (shift+ctrl/cmd+F5) on your
inventory screen.

**Comment by Thymekitt** [comment]
I finished it a couple of days ago, I figured it might have just been a temporary bug so I gave it a couple of days to refresh/fix itself before reporting it.

**Comment by deilann** [comment]
But you did get the Shaft of the Dragon?

**Comment by Thymekitt** [comment]
Yes, I got the shaft of the dragon.

**Comment by deilann** [comment]
That really makes no sense then. The reward mechanism for the two are not
separate. Can you log out and log back in for me?

**Comment by Thymekitt** [comment]
Okay, I'm an idiot, I thought it was a different type of egg as a reward, not dragon eggs. Please ignore me. I thought it was gryphon eggs, which makes no sense when you think about it.

**Comment by deilann** [comment]
Don't worry about it. I have a habit for responding to Github tickets, and desperately need to level up if I don't want to die tonight. ;)
