### ISSUE TITLE
Have a second currency for user-created rewards.

### ISSUE THREAD

**Issue by baudot** [HabitRPG/habitica#3355]
If the goal of HabitRPG is to promote good habits using positive and negative feedback, it's counter-productive to have the rewards the player sets for themselves spend out of the same currency pool as the in-game rewards that improve your character. 

A concrete example:
If I have to give up watching an episode of Game of Thrones to buy my character an Axe, that's creating negative feedback where there shouldn't be any.

Rather, you can double the strength of the positive feedback the player gets by giving them rewards in a second currency in parallel with the gold & silver drops for buying in-game rewards. This second currency, "Spirit" or "Mana" or whatever, can only be spent on the rewards the player sets for themselves, and those rewards can only be bought that way.

This way, if you're on a long slog to a major real-life goal, you can still treat yourself to in-game items. So you're still getting positive feedback along the way.

Example: If I set a goal for myself of 2,000 'Spirit' before I'm allowed to buy a motorcycle,  then my character still gets to spend their gold and silver on new swords and whatnot during the months it takes me to save up for my new set of wheels.

Also, by creating a currency that's only useful for buying player-created rewards, you're encouraging players to engage with that concept in the game. People tend to want to spend their wealth, not just let it grow. If they see that they're earning 'Spirit' at the same time as gold, they're encouraged to create rewards to spend it on.

**Comment by deilann** [comment]
Hey! Github is generally for bugs and coding issues. Feature requests go on [Trello](https://trello.com/b/EpoYEYod/habitrpg).

However, the way I work this is my rewards are priced to my economy -- which means If I'm still needing to buy equipment, that equipment is understood to be part of my "expenses" and therefore my rewards are priced lower until I no longer need to buy equipment.
