### ISSUE TITLE
Full API to get player stats, task names, stats & status.

### ISSUE THREAD

**Issue by elssar** [HabitRPG/habitica#336]
It would be nice if it were possible to get stats, like player health, GPs, xp, level, and task names, types, status from the API. Also, the ability to create or delete tasks and habits.

**Comment by lefnire** [comment]
there will be soon. is required for the phone app

**Comment by lefnire** [comment]
actually, i'm gonna keep this open and leave it in GH than Trello (it's a bit more code-y than feature request). I'm also going to prioritize it, because when this gets in more people will start helping out with the integration aspects, in tandem with our development efforts.

**Comment by lefnire** [comment]
This will happen within 1-2 weeks

**Comment by elssar** [comment]
:+1:  Cool, I have a Python command line app ready to implement stuff :)

**Comment by lefnire** [comment]
@switz this is the REST ticket. See my [comments above](https://github.com/lefnire/habitrpg/issues/336#issuecomment-13297103) on possible design, and we'll chat soon re: your design ideas

**Comment by switz** [comment]
Planning on tackling this tomorrow night. That is, if we can get the `validator` bug worked out – I'm still getting it.

**Comment by switz** [comment]
I started working on this tonight. I have a few routes and a small test suite built out. I won't send a PR until I add a few routes and create better test coverage.

Here's what I'm thinking for url design, let me know what you think. (Maybe we should call it v2)

Tasks are "Todos" as that's what Tyler has them called in the codebase. If you'd rather it be _todos_, please let me know.

## GET
- /api/v1/user - (get user status)
  - `user: uid`
  - `token: api token`
- /api/v1/user/tasks
  - `user: uid`
  - `token: api token`
  - `type: habit | daily | todo | reward` (optional)
- /api/v1/user/stats
  - `user: uid`
  - `token: api token`
- /api/v1/task/:id - (get todo, habit, reward, or daily)
  - `user: uid`
  - `token: api token`
- /api/v1/users/:id - (get user)

## POST
- /api/v1/task - (create new task)
  - `user: uid`
  - `token: api token`

## PUT
- /api/v1/user - (update user info)
  - `user: uid`
  - `token: api token`
- /api/v1/task/:id - (update task)
  - Note that type does not have to be passed in, it will be checked automatically, this is just to show that some functions may only be available for each particular type.
  - `type: todo` (optional)
    - Can pass in `done` parameter to accomplish (or unaccomplish) that task
  - `type: habit` (optional)
    - Can pass in `up` or `down` _functions_ to cause the action
  - `type: daily` (optional)
    - Can pass in `done` parameter to accomplish (or unaccomplish) that daily for today
  - `type: reward` (optional)
    - Can pass in `value` parameter to accompany that reward
  - `user: uid`
  - `token: api token`

## DELETE
- /api/v1/task/:id - (delete task)
  - `user: uid`
  - `token: api token`

I'm trying to find some express articles on sound API design (from a technical standpoint), but haven't come across many good ones. Obviously, this is all subject to change and rough look at what the API might be.

### EDIT: Fixed some errors in the API list.

**Comment by lefnire** [comment]
Incidentally, everything is a task in the codebase - rewards, dailies, todos, habits. This gives us flexibility in a lot of circumstances, I can explain if need. So we should probably consolidate `/api/v1/habit/:id` `/api/v1/task/:id` `/api/v1/daily/:id` all into => `/api/v1/task/:id`. As long as they pass in `{type:'habit'}` as distinguisher on task creation (POST). PUT, GET, DELETE won't need that distinction since you're working with it by id

**Comment by switz** [comment]
Makes my life easier :+1: Updated above.

**Comment by lefnire** [comment]
items should be simple enough, but pets are kinda patchy right now in the codebase - and we'll be revamping them soon anyway. We'll make that a second pass

**Comment by litenull** [comment]
This is gold. I will take this as guideline for the client mobile. cheerz

**Comment by switz** [comment]
Will the mobile app be powered via the API?

**Comment by lefnire** [comment]
yesm

**Comment by litenull** [comment]
come to irc :)

On Wed, Feb 20, 2013 at 7:19 PM, Daniel Saewitz notifications@github.comwrote:

> Will the mobile app be powered via the API?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/336#issuecomment-13847436.

## 

LP, Tomaž :)

**Comment by litenull** [comment]
meaning switz, but lefnire already replied

**Comment by elssar** [comment]
:+1:  Excellent! I'll get to work on the command line app next week, or maybe even this weekend

**Comment by wizonesolutions** [comment]
Ooh, command-line app! I was thinking of doing this too, so you definitely
have a tester waiting in the wings once you've got something. Tweet me;
same username.

**Comment by elssar** [comment]
@wizonesolutions you can test it out right now, well not right now as at the time of posting the api is acting up sending 504's, but I have a version that implements the current api - https://github.com/elssar/pyhabit - don't use the version on PyPI, it has a few bugs.

**Comment by magikid** [comment]
Very excited for this to be done.

**Comment by lefnire** [comment]
I'm also brainstorming separating out algorithms / logic into its own repo
(habitrpg-algorithms)

**Comment by lefnire** [comment]
So quick poll (I forgot to post this earlier). There are two approaches to the API.

@lefnire's approach: [nested resource routing](http://guides.rubyonrails.org/routing.html), popularized by rails, and standardized across most multi-user based APIs on the web (Twitter, Github, etc). See [Apigee](https://apigee.com/console/twitter) for examples. The routes look like `/users/:uid` `/users/:uid/tasks/:taskId`. For non-authenticated requests, you'd get a limited subset of fields (for example, your party members' stats & items). Authorizing a route would look like `/users/:uid?apiToken=:token`, `/users/:uid/tasks/:taskId?apiToken=:token`.
- Pros
  - Simple GET requests without special header rigging
  - Consistent approach to requesting non-authorized users as authorized users
  - Sensical path-mapping based on the hierarchical user document (if you know what the user object looks like, you know what to request)
- Cons
  - Less future-proof when we have real OAuth implemented (though we can build /v2/... for that)

@switz's approach: Simpler routes assuming a "home directory" format: `/user` `/tasks` (`:uid` and `:apiToken` passed in as headers). Non-authorized users will be requested as `/users/:uid`.
- Pros
  - Simple resource routing
  - Future-proof for when we implement OAuth
- Cons
  - Less consistent between authorized and non-authorized users

@switz, if I'm characterizing poorly feel free to edit my post liberally - I don't want to make mine sound better or biased. I'll also merge soon anyway and we can take care of this later (gotta run for a bit will be back later), but we'll want to get /v1 as rock solid as possible before pushing it.

**Comment by switz** [comment]
I think we could use a mishmash of the two. The thing I like about the headers is that it's consistent auth against all requests, whereas passing in `apiToken=token` is `req.params.token` on a GET and `req.body.token` on a POST.

**Comment by lefnire** [comment]
Ah, that's a good point. What about token in header & uuid in url?

**Comment by lefnire** [comment]
There a lot of benefits of using user id. (1) facebook users don't have a
username (for that matter, nor will any other oauth providers we integrate)
- it takes out the logic of having to generate usernames based on oauth
  integration. as the _id mongo property, it's blazing fast and easy to
  index.

**Comment by switz** [comment]
I say we move ahead with the current API. I'll build out the routes for your secondary API. We'll run both concurrently and see what people dig. I've done all the hard work, so adding routes + tests is insanely simple now.  

+1 to userid over username.

**Comment by lefnire** [comment]
let's do a G+ soon to get it finalized, it's highly important to get the API right the first time - even though we can add /v2 later, once people start writing apps we risk breaking compatibility

**Comment by lefnire** [comment]
Ok everyone, we've got the majority of /v1 API integrated into develop - everyone give @switz a round of applause! So start playing on your local machines on the `develop` branch, we'll be deploying this once enough people have kicked the tires and given it their blessing

**Comment by elssar** [comment]
Awesome work @switz , and @lefnire !

**Comment by lefnire** [comment]
done. Follow up here for specific REST routes to implement https://trello.com/card/rest-api/50e5d3684fe3a7266b0036d6/189
