### ISSUE TITLE
Password Change Message Can Be Erroneous

### ISSUE THREAD

**Issue by Scott-Earthtreader** [HabitRPG/habitica#3361]
When I most recently went to change my password, the message would tell me that my password had been successfully changed, and then afterward will display a less noticeable message at the top right of the page telling me that there's an error. I think that the message should be altered in some way, either to appear when next the page refreshes, or be programmed to display instead the error message if the password change has not been successful, as it currently reports whether it be the case or not.

**Comment by deilann** [comment]
That error is a general error that basically means the stuff you did
locally did not get saved to the server. I'm not sure how one would
specifically tailor it to password changes.

**Comment by crookedneighbor** [comment]
Closing this as it's pretty stale and I believe the error message was coincidental to the password change.
