### ISSUE TITLE
Editing Plus and Minus in Habit: Incorrect Offset

### ISSUE THREAD

**Issue by cevn** [HabitRPG/habitica#3364]
### Description

It's possible to click the button which toggles making a Habit a 'plus' or 'minus' habit without actually toggling the attribute. 
### Steps to reproduce
1. Go to tasks page
2. Select a habit
3. Click the 'edit' pencil
4. Toggle either plus or minus - but only within the left quarter of the plus or minus box. The box jiggles, but nothing is actually toggled. 

![screen shot 2014-04-27 at 11 56 00 pm](https://cloud.githubusercontent.com/assets/4663020/2813470/13735ece-ce89-11e3-8c77-3323ecf0b727.png)
### Environment

Browser: Google Chrome Version 34.0.1847.131
UserID: 5ddf47ab-72c5-45a4-a1ea-0ffe64a247b7
Relevant JS errors in console: None AFAIK

If there's anything wrong with the ticket please let me know!

**Comment by Alys** [comment]
@cevn I've very sorry we didn't respond to this when you logged it! We've recently made changes to the Habit buttons. Has that fixed the problem?

**Comment by cevn** [comment]
Yes, it's fixed now. Thanks for checking in
