### ISSUE TITLE
Egg Hunt dissappeared after changing to Ukrainian translation

### ISSUE THREAD

**Issue by silvirine** [HabitRPG/habitica#3365]
Hi guys,
Party dissappeared, and Egg Hunt was not showing both in inventory and in Party sections. This happend after trying to activate second quest while Egg Hunt wsan't finished.
Changing to English translation fixes the problem.

Please have a look on this.
Thanks

**Comment by deilann** [comment]
Party disappearing is usually the party not _loading_ -- the "not in a party page" loads first, then your party page renders on top of it. Can you do me a favor and switch back to Ukranian, go to your party page, and wait for the page to fully load? If the party page still doesn't load, go ahead and refresh a few times, seeing if it ever shows up.

**Comment by silvirine** [comment]
are you using beta.habitrpg.com or just the habitrpg.com to enter the site?
-  not beta, just habitrpg.com

Can you do me a favor and switch back to Ukranian, go to your party page, and wait for the page to fully load?
- CTRL + F5 fixes problem, and it appears only after trying to activate quest when you have active one already. Now found out tht it happens no matter what translation you have.

**Comment by deilann** [comment]
Sometimes it happens to me when my internet is just being slow, too. :)
