### ISSUE TITLE
Spirit of Spring stag boss is regaining power?!?

### ISSUE THREAD

**Issue by kb-code** [HabitRPG/habitica#3366]
my party is completing the spirit of spring quest again.  In past times, the boss lost damage daily until we defeated him, but this time, he's GAINING power!  adding our damage listed in the chat room, we should have done 378.3 damage, but it reads 1106/1200 (and earlier the score was well below 1000, it bumped up twice, seemingly unrelated in any way to the damage numbers we'd done).

Again, this didn't happen previously when we did this quest.  Did something in the code change since?  attaching chat room notices since we started quest below for reference, happy to give you more info as necessary...

(ps... refreshes do not change anything)

UID: cf1ba132-f177-4865-a6b6-d16bcb89e5c0
Group ID: ae0c1a47-876e-4bb5-a780-5717ae00035f

CHAT ROOM TRANSCRIPT - Unorthodox Swords of Marvelous Sundry

kb attacks Ghost Stag for 18.7 damage, Ghost Stag attacks party for 0.0 damage. -2 minutes ago+1 
 it must have gone back up, otherwise how did I do 222 damage last chron? Strange... -an hour ago+1 
kb 
 harlequix attacks Ghost Stag for 32.8 damage, Ghost Stag attacks party for 0.0 damage. -an hour ago+1 
 Weird. it looks to me like the health on the stag went back up. -5 hours ago+1 Longform 
 nishidake casts Tools of the Trade for the party. -7 hours ago+1 
 nishidake casts Tools of the Trade for the party. -7 hours ago+1 
 nishidake attacks Ghost Stag for 21.8 damage, Ghost Stag attacks party for 1.4 damage. -7 hours ago+1 
 @ckafi ...extremely gentle fistbump -8 hours ago+1 Ele 
 Healers damage ... like sneezing in the wind. -9 hours ago+1 ckafi 
 ckafi attacks Ghost Stag for 10.0 damage, Ghost Stag attacks party for 0.0 damage. -9 hours ago+1 
 Ele casts Blessing for the party. -9 hours ago+1 
 Ele casts Blessing for the party. -9 hours ago+1 
 Ele casts Protective Aura for the party. -9 hours ago+1 
 Ele attacks Ghost Stag for 10.9 damage, Ghost Stag attacks party for 5.2 damage. -9 hours ago+1 
 Longform casts Ethereal Surge for the party. -13 hours ago+1 
 kb attacks Ghost Stag for 222.1 damage, Ghost Stag attacks party for 1.4 damage. -18 hours ago+1 
 novemberalice attacks Ghost Stag for 8.3 damage, Ghost Stag attacks party for 0.0 damage. -19 hours ago+1 
 Ele casts Blessing for the party. -20 hours ago+1 
 Ele casts Blessing for the party. -20 hours ago+1 
 Ele casts Protective Aura for the party. -20 hours ago+1 
 Longform casts Earthquake for the party. -20 hours ago+1 
 Longform attacks Ghost Stag for 10.1 damage, Ghost Stag attacks party for 10.6 damage. -20 hours ago+1 
 Also - "woohoo, Beastmistress!" -20 hours ago+2 Ele 
 I agree with the others - no harm in you rejecting quests when you need to, and the more of us the merrier! -a day ago+2 Ele 
 harlequix casts Ethereal Surge for the party. -a day ago+1 
 harlequix casts Ethereal Surge for the party. -a day ago+1 
 harlequix casts Ethereal Surge for the party. -a day ago+1 
 aylatrigger attacks Ghost Stag for 11.0 damage, Ghost Stag attacks party for 0.0 damage. -a day ago+1 
 kb casts Ethereal Surge for the party. -a day ago+1 
 harlequix attacks Ghost Stag for 32.6 damage, Ghost Stag attacks party for 0.0 damage. -a day ago+1

**Comment by deilann** [comment]
Please make sure to search existing tickets. :)

See: https://github.com/HabitRPG/habitrpg/issues/2657

**Comment by kb-code** [comment]
Hi deilann,

Thanks for the reply..  I did check out that thread before posting and can
see why you would say it was related, but the behavior here is somewhat
different.  We had a one-time gain of points on a quest our party has
completed without issue before, and the points gain does not repeat at each
person's chron, and it did not reset the points entirely either.

however, from a coding perspective, I guess they are probably being caused
by the same digital gremlin, so I'll post this info there as well.  Thank
you for the work you guys & gals do behind the scenes here to keep HabitrPG
running!

I thought perhaps this woul

On Mon, Apr 28, 2014 at 5:27 AM, deilann notifications@github.com wrote:

> Closed #3366 https://github.com/HabitRPG/habitrpg/issues/3366.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/3366
> .

## 

"If you have a dream, don't resist or deny it - the whole point of dreaming
is getting to try it!"

**Comment by deilann** [comment]
Yup! Some people only have it happen once -- some people have it happen
repeatedly.
