### ISSUE TITLE
Lost equipment after April Mystery Item was received

### ISSUE THREAD

**Issue by novemberalice** [HabitRPG/habitica#3367]
User-ID: 9ae13a51-b3cd-4d1d-87c3-4f0f229bedce
Browser: Mozilla Firefox 28.0 for Mac

Location of Issue: Inventory

Description of Issue: After receiving and equipping the April Mystery Item (Moth Wings etc.), both these as well as a significant part of my equipment, which was a maxed out mages gear, disappeared (see screenshot one). Please not that this is not a graphics bug, as the equipment does not appear on my stats either (see screenshot two). I have not taken any action changing anything about my equipment except equipping the moth wings as costume.

![bildschirmfoto 2014-04-28 um 11 38 57](https://cloud.githubusercontent.com/assets/7427922/2815919/f083c1c2-cec1-11e3-868d-8529775b210b.png)
![bildschirmfoto 2014-04-28 um 11 39 26](https://cloud.githubusercontent.com/assets/7427922/2815925/f9295454-cec1-11e3-8b59-c87cb17725ce.png)

**Comment by deilann** [comment]
I'm confused by when you say it doesn't appear on your stats. Your stats
show maxed out mage gear? Can you explain further?

**Comment by novemberalice** [comment]
See second screenshot. It says No Head Accessory, which is in line with the fact that all my head accessories seem to have disappeared, even though I used to have them.

**Comment by deilann** [comment]
Were you wearing the head accessory as a costume or a piece of armor? If it was as a costume, it would not show in your equipment.

It looks here like everything's disappeared except armor and back accessories.

I know you think it's not a display issue, but your equipment is clearly showing you having equipped items that are not in your inventory. Can you do a hard refresh for me? (shift+ctrl/cmd+F5) Can you also tell me if anything you're "missing" is for sale?

**Comment by novemberalice** [comment]
Hard refresh seems to have fixed the issue. Thanks!

**Comment by deilann** [comment]
Awesome! :)
