### ISSUE TITLE
New Android app allows you to do dailies on days they aren't valid

### ISSUE THREAD

**Issue by AlMcKinlay** [HabitRPG/habitica#3368]
So, the new UI doesn't disable dailies when they aren't applicable. I have a few that should be available today (and aren't on desktop) but I can check them off on mobile.

Love the new UI btw.

**Comment by SabreCat** [comment]
You've always been able to check off Dailies on inactive days. They're grayed out, but can still be checked off for Gold, Experience, and Streaks. Can you clarify what changed that you find problematic?

Closing for now since as described, this is intended behavior.

**Comment by SabreCat** [comment]
Also, https://github.com/HabitRPG/habitrpg-mobile might be a better spot to report mobile app issues!

**Comment by AlMcKinlay** [comment]
1. Ok, well they aren't greyed out on the mobile app then. I hadn't ever tried to check them off on the desktop site, but it's just not clear what dailies are active as they look exactly the same now.
2. I didn't realise there was a specific one to the mobile app, I just followed the link from the bottom of the site, apologies.

**Comment by lefnire** [comment]
see https://github.com/HabitRPG/habitrpg-mobile/issues/193

**Comment by AlMcKinlay** [comment]
Cool, thanks. Will post mobile related ones in the right project from now.
