### ISSUE TITLE
Can't login with facebook

### ISSUE THREAD

**Issue by influnza** [HabitRPG/habitica#3370]
I believe there used to be one more button. I used the site in the morning and couple hours later I opened it again and was logged out and couldn't log in again.
If FB login is being removed, could you also transfer accounts to in-app login? Thank you
![image](https://cloud.githubusercontent.com/assets/7429636/2817872/46627ec8-cede-11e3-858c-254c66b5f97a.png)

**Comment by deilann** [comment]
Chances are, your ad-block has hidden the button. This has happened to
another user in the past.

**Comment by influnza** [comment]
Haha! Indeed. Thank you so much :)
