### ISSUE TITLE
Checking and unchecking items in checklist leaves a positive silver balance

### ISSUE THREAD

**Issue by Petemir** [HabitRPG/habitica#3371]
I have a todo item with 4 sub-items in a checklist. If I mark the "big" item as completed, I receive, e.g. 95 silver coins; If I go to the completed tab and then uncheck the "big" item, only 93 silver coins are deducted from my wallet. That way, I am left with a few coins that I didn't deserved, making it a way to generate infinite coins.

**Comment by deilann** [comment]
This is a known bug -- To-Dos don't remove as much as they should. However, there are lots of ways to generate infinite coins, such as spamming a dummy habit or going into Settings > Site > Fix Character Values and just give themselves tons of gold. I think it's best to trust users won't use gimmicks to inflate their gold.

https://github.com/HabitRPG/habitrpg/issues/964
