### ISSUE TITLE
Beastmaster achievement triggered early

### ISSUE THREAD

**Issue by grogert331** [HabitRPG/habitica#3372]
I've gotten the Beast Master achievement but I've not gotten one particular pet; the blue cotton candy panda. And I've been trying for weeks now but I've yet to get one blue cotton candy hatching potion! I've no idea what the issue is!

**Comment by deilann** [comment]
The modal triggered for me early too -- not quite sure what it is. However, I didn't get the badge in my achievements until I got all 90 pets proper. Can you check and see if you have the badge for me?

**Comment by grogert331** [comment]
I just checked for myself; I know it said I got the achievement multiple times but It doesn't show I got the medal

**Comment by deilann** [comment]
Yup. That's what happened to me.

Do you show 90/90 pets? For some reason, mine shows 91/90 pets now that
I've gotten Beastmaster. Soooomething in there is counting.

**Comment by grogert331** [comment]
It shows 90/90 pets and I think the achievement showed up multiple times for when I hatched my hedgehogs and some of my eggs from easter

**Comment by deilann** [comment]
Yeah, there's a known bug where you're going to get the announcement (even
after you get beastmaster proper) whenever you hatch a quest pet.

**Comment by grogert331** [comment]
Okay so that tells me about the Beast Master Achievement; but why haven't I gotten anything blue cotton candy related (the egg potion or the food) for the past few weeks?

**Comment by deilann** [comment]
The drops are RNG based and cotton candy potions are rare.

**Comment by grogert331** [comment]
Okay so I've just been unlucky so far

**Comment by deilann** [comment]
Yup! If I recall correctly, Megan's been waiting for cotton candy blues for
months.

**Comment by grogert331** [comment]
_sigh_ Well at least I'm a rogue! xD Thanks for the help!

**Comment by deilann** [comment]
No problem! Remember: every 25 points of PER, and your drop cap will go up
by one. Also, subscribing doubles it!

**Comment by Alys** [comment]
This was probably an example of #3904 which has been fixed.
