### ISSUE TITLE
I died, no clue why

### ISSUE THREAD

**Issue by tekHudson** [HabitRPG/habitica#3373]
I jsut died and lost hundreds of gold and a piece of 2013 holiday gear. I don't think I was that low on health. Please Help.

**Comment by meganstrickland** [comment]
This comes up a lot, so I just added it to the wiki FAQ page. Take a look and see if that answers your questions. :o)

http://habitrpg.wikia.com/wiki/FAQ#My_character_died_when_it_shouldn.27t_have.21_What_do_I_do.3F

**Comment by tekHudson** [comment]
@meganstrickland Thank you. I have restored what I suppose to be the lost gold (under estimated rather than over) and lowered my health to what I believe it was it. I'm not sure how my chest piece came back... if that was you, thanks. 

I would love to see a graph of stats(HP/MP/XP) similar to that of the habits with a clickable/rollover feature so you can see what caused the drop/increase in your stats(HP/MP/XP).
