### ISSUE TITLE
unknown habit showing up

### ISSUE THREAD

**Issue by CoffeBurn** [HabitRPG/habitica#3374]
Out of nowhere a new task appeared under my "Habits" column. The name of the task is "9e092010-b4a4-4909-a3fa-53e3c3641602" and the explanation for the task is "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task."
![screenshot 26](https://cloud.githubusercontent.com/assets/7436852/2826425/6b7aae92-cf6f-11e3-9133-38607822b714.png)

**Comment by ghost** [comment]
It's a known bug #2558 habitrpg.wikia.com/wiki/Known_Bugs
 You should be able to simply delete it.
