### ISSUE TITLE
Include a progress bar for the intro / tutorial

### ISSUE THREAD

**Issue by NewAlexandria** [HabitRPG/habitica#3375]
Following [S. Leslie's suggestion from Twitter](https://twitter.com/invis_insight/status/460460060796534784), @lemoness will hopefully find use in this suggestion.

The intro / onboarding process is long-ish, and it would be great if a status bar was added to overlay dialog.  Probably just in the upper-right, but maybe you will want to be design-y about something more inspired.  

A progress bar would also follow the theme of your gamified product.

**Comment by ghost** [comment]
As the tutorial is shown in tooltips, that change their position to indicate what they refer to, IMHO the progress bar won't look natural for them. The user should have no difficulties in noticing what changed when he/she clicked next and the next message jumped to some other place.

If the length of tutorials is really an issue, I would vote for simple note below the text to indicate the current and total number of messages: "4 of 8".

As far as the stylish solution is concerned, it may be a circle in any corner of the tooltip, that will come from gray to any color by sectors (like in donut pie chart) as you proceed further. The number of sectors should be dynamic and equal to the total number of messages in the tutorial. This will be different from the bar, as it should be eye-catching, and localized inside the message tooltip.

**Comment by lemoness** [comment]
I like the 4 of 8 idea - I've had a lot of people ask questions that were
just covered in the tutorial, leading me to suspect that they simply
skipped it. Maybe the number would help them know that it wasn't that long?

**Comment by NewAlexandria** [comment]
Thank you for verbalizing this @lemoness — I think that incomplete onboarding can results from this kind of non-communication (of progress / completeness).  The same rationale is why surveys show a progress bar.  With a progress 'signal' the user is unsure how much [more] of their time must be committed, which can lead them to chose _cessation_.

Also, I just had the consideration that tutorial stages may do best when aligned with particular sites of regular interactivity (this is what happens naturally already) — **_and**_ that the function in the app has an icon or clear/distinct graphic style that is highlighted or otherwise prominently reinforced in that stage of the onboarding.  This would aid memory consolidation.

**Comment by Alys** [comment]
Closing because we've changed the tutoial significantly since then.
