### ISSUE TITLE
Feedback on the redesign, colors, etc

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3376]
Whew I'm late to the bandwagon with this and I lost track of the thread where it was supposed to go. Anyway, here's my few cents on the redesign —
1. Dropdown menus currently stay open until you either click another menu button, reclick that one, or refresh the page. This is _very_ frustrating. Clicking an area outside the menu should close it.
2. I know several people have mentioned this before and it's probably already on the to-do list, but the notif button could use some work. Perhaps invert colors (dark-gray box, white speech bubble) when there are new messages (nonintrusive, but visibly different from no-messages); also imo add hover text [Notifications] and [Settings] for those two buttons like with [Sync], the symbols aren't 100% self-explanatory.
3. Not a big fan of the lighter font for gold/silver amounts. The silver especially is hard to read when my screen is dim. The fonts should be darker.
4. Actually on that note, color contrast overall isn't super great. Everything on the site is on a color spectrum from darkish grey to lightish grey to desaturated blue or green and it becomes somewhat of a nightmare to distinguish button outlines, columns, etc from each other. I know I already complained about the notif opacity which has been changed (thank you!) but I feel like the color scheme could be bolder. This is a game, after all. :p

**Comment by deilann** [comment]
I disagree with 1 -- this is primarily for accessibility and mobile. If
clicking outside closed it, it would reduce that usability.

2 is already in the works, pushed, but not deployed iirc

3 I agree, but my biggest problem is the gold

4 Yes, everything is blue, and pretty much the same blue. :c I'd really
like a darker blue/grey whichever it is, but not the black, which was too
disorienting.

**Comment by casicastiel** [comment]
1, 2 - good to know.
4 - every color on the site could stand to be a few shades darker to be honest; the black was too harsh, but as it stands everything's too similarly neutral for comfort.

**Comment by crookedneighbor** [comment]
The site site has gone through some cosmetic changes since this was opened. Feel free to reopen this issue if you have thoughts about the current design.
