### ISSUE TITLE
After rebirthing, headAccessory (ears, etc), "body" gear, "back" gear are not deequipped

### ISSUE THREAD

**Issue by ZachEd96** [HabitRPG/habitica#3377]
They aren't in my equipment, and they go away if I enable use costume. I was a level 33 rogue before rebirthing.

**Comment by deilann** [comment]
Oh, I bet I know what this is.

Head accessories aren't part of the rebirth dequip code.

**Comment by deilann** [comment]
(Because they didn't exist when rebirth was written.)

Nice catch!

**Comment by Alys** [comment]
I have uploaded a fix for this along with some changes to implement eyewear: https://github.com/Alys/habitrpg-shared/commit/004ef8809e67dab31af86be8dab98baf2fd28f14 in https://github.com/HabitRPG/habitrpg-shared/pull/291

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/pull/307 (not live yet, but works well in testing and this issue can be reopened later if needed)
