### ISSUE TITLE
Loggly

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#3378]
Just a reminder. We should probably implement something like Loggly (http://loggly.com). It has a generous free plan and integrates with New Relic (http://blog.newrelic.com/2014/04/15/logglys-new-relic-extension/).

The extension link is broken, this is the right one https://chrome.google.com/webstore/detail/new-relic-loggly-extensio/locgdocadipenhijhbfcfaegbfhgdbbi

**Comment by negue** [comment]
@paglias @lefnire Do we already have something like loggly implemented?

**Comment by lefnire** [comment]
not loggly, but newrelic records errors in the Errors tab we can make use of

**Comment by paglias** [comment]
@negue @lefnire what I miss from newrelic is the ability to log anything we want, like in the console. It would be really usefult to debug common problems

**Comment by lefnire** [comment]
@paglias feel free to add it, or let me know if you prefer me to do it

**Comment by paglias** [comment]
@lefnire great! signed up, will setup tomorrow. The lite plan only allows for one user, I'll send you my credentials

**Comment by paglias** [comment]
@lefnire @negue implemented now
