### ISSUE TITLE
Password reset isn't working

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3380]
Hi,

I tried to log in to my account on the website several times, and every time I ask for a password reset, I don't receive any email though there is a message that says otherwise.

However I am still logged in to the Android app.

Any thoughts?

**Comment by lefnire** [comment]
I'm gonna look into this, it happens intermittently for users - sometimes it works, others it doesn't... something on the email server likely

**Comment by ghost** [comment]
Hi lenfire, I tried again a few minutes ago and finally got an automatic email. I could change my password afterwards.
Thanks for your message!
