### ISSUE TITLE
Can't subscribe via PayPal internationally

### ISSUE THREAD

**Issue by BlackFerretC** [HabitRPG/habitica#3381]
Whenever I try to set up a subscription PayPal tells me "At this time, we are unable to process your request. Please return to HabitRPG and try another option." PayPal still works for me with everything else, including other subscriptions. This has been going on for three days.

_edit by admin:_
## What to do if this happens to you:

This is a common problem experienced by people in some non-USA countries. It's because PayPal does not handle repeating transactions in the same way for all countries. You do not need to comment here if you have this problem, because we know that it affects all players in those countries equally.

If you're unable to create a normal subscription for yourself, you can instead give yourself a gift subscription. Gift subscriptions are processed by PayPal as once-off payments and so do not suffer from the same limitations that PayPal imposes on recurring subscriptions.

To give yourself a gift subscription, find any post you have made in any guild, or Tavern, or party chat. Make a new post if necessary. Click on your name to access your own profile. At the bottom of your profile, you'll see a gift box. Click on that to access the form for giving yourself a gift subscription.

The gift subscription will not renew so you will need to recreate it when it expires, or before. If you recreate it before it expires, the new subscription period will be added on to the end of the current one and you will not lose your consecutive subscription benefits.
##

**Comment by deilann** [comment]
Are you using a non-USD currency?

**Comment by BlackFerretC** [comment]
Yes, but as far as I am aware, PayPal automatically converts it.

**Comment by deilann** [comment]
Yes, but I think @lefnire has to set it up to allow (possibly specific) non-USD currency. It's different on the vendor end than on the user end.

@lefnire This was brought up a bit ago, when Paypal recurring was first implemented -- any news/progress on figuring it out?

**Comment by ghost** [comment]
I encounter the same problem...
No chance to change the currency used by PayPal beforehand either

**Comment by deilann** [comment]
Any news @lefnire?

**Comment by habitrpguser** [comment]
I got exactly the same problem. currency is €. Paypal does NOT work for subscription (error message as described) but does work fine for directly buying gems. I'd really like to subscribe and I don't have a credit card, so could you please fix this?
The error message is in German and is:
"Wir können Ihre Anfrage zurzeit leider nicht verarbeiten. Kehren Sie zu HabitRPG zurück, und wählen Sie eine andere Option aus."
I googled this and it seems to be a common problem with other sites, too. Perhaps, since it works for buying gems and doesn't for subscribing, you can find the difference.

**Comment by habitrpguser** [comment]
... apparently, when trying to subscribe, the price is not shown in the paypal basket, whereas when trying to buy gems, it is. I've read the same thing about this bug for other websites.

**Comment by habitrpguser** [comment]
... this thread (though a little old) might be helpful since it quotes a reply from paypal on the matter:
https://www.paypal-community.com/t5/eBay-and-PayPal-Archive/At-this-time-we-are-unable-to-process-your-request-Please-return/td-p/313298

**Comment by habitrpguser** [comment]
... here's what stackoverflow has to say:
http://stackoverflow.com/questions/23805887/getting-message-we-are-unable-to-validate-your-information-during-paypal-trans

**Comment by habitrpguser** [comment]
here's two more that seem relevant:
http://stackoverflow.com/questions/18775951/paypal-sandbox-unable-to-process-request?rq=1
http://stackoverflow.com/questions/24258786/how-to-detect-the-paypal-cookies?rq=1

**Comment by habitrpguser** [comment]
I'm probably saying unqualified things here...
- I've been told it's a problem on Paypal's side and either can't be fixed by HabitRPG or is extremely difficult to fix.
- I don't know if this is a matter of cookies having to be deleted, or a matter of Paypal not trusting the subscriber, or not trusting Habitrpg, or both.
- I haven't tried yet if it helps if I, as the subscriber, try deleting cookies and using a different browser, and can't do so now (my Paypal account is empty, money's on its way) but will after the weekend. I'll write the results here.

But _if_ that doesn't work either, and if the bug can't be fixed by HabitRPG: Would it be a feasible workaround to give players the option to pay their subscription manually each month, so Paypal treats it like a one-time payment (like buying gems), and consequently, it works? Of course, it would be up to the players to pay in time, or the subscription would run out.

(I hope this isn't all nonsense... if it is, please forgive me. I don't know any better.)

**Comment by habitrpguser** [comment]
... _if_ that's an idea, it could also be in the form of "pay for x months in advance", maybe.

**Comment by lefnire** [comment]
@habitrpguser thanks for all the info. I'm gonna prioritize this in coming days, those resources will give me a leg up. I'll get back to y'all as soon as I have more info on the tech side.

**Comment by deilann** [comment]
Also, I know that @lefnire has been working towards block payments for
subscriptions and they're desired... as in "pay for x months in advance" :)

**Comment by habitrpguser** [comment]
@lefnire and @deilann , thank you for reacting so quickly and taking it seriously!
Money has arrived on my paypal account so I tried logging in with a "clear" browser - different browser with completely deleted cookies & other history. No change - subscribing doesn't work, buying gems does. The two paypal login pages those actions lead to are two completely different pages btw. (Different design and everything, the only thing they have in common is that they're both from paypal and that you have to enter your paypal login data in both.)
I'm rich in gems now! :-) (Not that I wouldn't know what to do with them...)

**Comment by lefnire** [comment]
I've prowled the internet for a solution to this. The links @habitrpguser gave me give solutions for the end-user to try (mainly just clear your cache/cookies). I couldn't find anything about setting a flag in code, or an option in PayPal's biz account's dashboard or anything. I scoped around my PayPal dashboard thoroughly, sure enough couldn't find anything. And sure enough, we only have 3 subscribing countries internationally.

It's gotta be a dashboard setting or a flag in code, but search as I may I can't find any leads. I've contacted PayPal's customer support, I'll report back when I hear more.

**Comment by lefnire** [comment]
Are people able to buy gems with PayPal just fine?

**Comment by lemoness** [comment]
I haven't heard complaints about that, so as far as I know, yes, at least
domestically. Can some international users chime in with confirmation?

**Comment by habitrpguser** [comment]
@lefnire @lemoness Buying gems works fine for me. (I'm from Germany.)

**Comment by lefnire** [comment]
Response:

> As customers pay through anywhere through PayPal, we have different filters that the transactions can go through. The transactions that are being denied to your customer are being denied by a risk filter. There is not a way to go around the risk filter but what you can do is use a different products then the standard PayPal Business account that you are using.
> 
> We have a product called PayPal Payments PRO that do not go through the same risk filters as the standard transactions do. If you would like to receive more information or if you are interested in signing up for PayPal Payments PRO, please contact our Sales department at ...

I'll investigate PRO

**Comment by lefnire** [comment]
Applied for PayPal Payments Pro. I called customer support and verified, to accept international recurring subscriptions one indeed must be on PRO. It's like Express/Standard's recurring payments feature is a trial! Hopefully this thread helps some other unlucky sap down the pike.

Anyway, turns out the code for Express/Standard recurring payments is different than for Pro's (according to lady on the phone), so I'm gonna have to gut that feature once I get approved - I don't think there are NPM modules that support PRO.

**Comment by deilann** [comment]
Is this going to break current subscriptions?

**Comment by lefnire** [comment]
That's a good question. I'll email them with that question when I hear back

**Comment by deilann** [comment]
Awesome. You might also want to G+ this info for those who don't follow the
repo.

**Comment by Shikogo** [comment]
Just noting that this issue still exists. I was looking forward to start subscribing today, but no such luck.

Any progress in fixing this?

**Comment by lefnire** [comment]
I've upgraded the paypal account. I need to go in an update the code, sounds like I'll be build a new module to support Paypal Pro (can't find support in NPM). Just been busy with crits and the memleak, I'll get back to y'all when I'm off that task

**Comment by lefnire** [comment]
I've tried a thing (not _the_ thing listed above, but 25a5bf92a6fe7fa5e59ae319e30ab568f8027005). Could someone give that a shot?

**Comment by Shikogo** [comment]
I'm still getting the same error when trying to subscribe.

**Comment by lefnire** [comment]
Damn. Worth a shot

**Comment by lemoness** [comment]
There should now be a workaround to this with the new subscription gifting system - try gifting a subscription to yourself! From feature description: "This block is purchased as a one-time transaction, so the sender isn't charged recurring. As an aside, international players who can't subscribe can use this as a workaround by gifting themselves a one-time subscription block (which should work, since it's not treated as a Paypal recurring plan, but a single purchase)."

**Comment by proxforge** [comment]
Bug is still there. Is there a workaround? I dont have a "gift"-option in the german-habitrpg interface. 

"Wir können Ihre Anfrage zurzeit leider nicht verarbeiten. Kehren Sie zu HabitRPG zurück, und wählen Sie eine andere Option aus."

**Comment by Alys** [comment]
@j0hnnycode The HabitRPG website should be identical for all languages, with the exception of the language strings themselves, so you should be able to access the gift option. Please see http://habitrpg.wikia.com/wiki/Subscription#Gift_Subscription for information about how to do this and then post again here if you need more help.

**Comment by proxforge** [comment]
Thanks! Maybe a hint for non USD-Users would be cool on the subscription page? Someone whos not searching for the bug will never do a payment, without this info.

**Comment by Alys** [comment]
@j0hnnycode That's a very good point! Thank you!

@lemoness would you like changes made to the subscription page to point people in the right direction for gifting subscriptions to themself? If so, what would you like it to say?

**Comment by lemoness** [comment]
Hmm. Maybe something like "Due to a Paypal error, some international users
may have difficulty subscribing, but you can always [gift yourself a
subscription]. We apologize for the inconvenience." I'm on the fence,
though.

**Comment by Alys** [comment]
Does this paypal error still occur?

**Comment by oktayacikalin** [comment]
I'm also getting "Wir können Ihre Anfrage zurzeit leider nicht verarbeiten. Kehren Sie zu HabitRPG zurück, und wählen Sie eine andere Option aus.".
Any news on this topic?

**edit by admin** google translate says "We can make your request at this time, unfortunately, not process. Return to habitrpg back and choose another option."

**Comment by crookedneighbor** [comment]
@oktayacikalin We'll need your user id to help you with this:

You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by oktayacikalin** [comment]
@crookedneighbor Sent you an email to [email address removed]. Thanks!

**Comment by Alys** [comment]
@oktayacikalin Please paste your User ID into a comment here. Blade might not be available to help you himself depending on his personal schedule, and pasting your User ID here allows any other admin to help. Putting your User ID here is not a security risk; mine for example is d904bd62-da08-416b-a816-ba797c9ee265 and that doesn't give anyone access to any private sections of my account.

**Comment by oktayacikalin** [comment]
@Alys Ok - here it is: 225d951f-145a-427a-82ce-095da32e1861

**Comment by Alys** [comment]
@oktayacikalin This seems to be the standard problem that many international users get -- i.e., PayPal doesn't let them create normal repeat subscriptions. However the workaround provided above by Lemoness on  Dec 5, 2014 (https://github.com/HabitRPG/habitrpg/issues/3381#issuecomment-65688043 ) will work for you -- you can use the gift subscription option to gift yourself with a subscription. Find your name in any chat message in Habitica, click to get to your profile, and use the gift box at the bottom. There's more information in the "Block Subscription" section on the wiki's Subscription page at http://habitica.wikia.com/wiki/Subscription -- see the "Gift Subscription" and "Non-USA PayPal Subscriptions" subsections.

**Comment by habitrpguser** [comment]
@oktayacikalin I just want to confirm everything @Alys said above. I've just gift-subscribed myself for a year for the second time. It works great. It does everything you'd hope for (and **great praise to the coders** for that!): If you gift yourself before the previous subscription runs out, the new one starts from the day the old one runs out, not from the day you made the gift subscription online - which means you get the full year. Also, the "consecutive months" count is continued and not restarted, so I have more than 12 consecutive months now and get the in-game benefits for that. I'm in Germany, and if I try to subscribe normally, I get the same PayPal error message as you get. As @Alys said: Everything that, from PayPal's perspective, looks like a recurring payment doesn't work and creates this error message. Everything that, from PayPal's perspective, looks like a one-time payment works fine.

**Comment by oktayacikalin** [comment]
@Alys @habitrpguser Thanks - had to find a way to actually find a page having that button :). I'm a noob here so it took some time but now it worked fine!

**Comment by Alys** [comment]
@oktayacikalin Thanks for the feedback! It sounds like the instructions on the wiki page I linked to weren't anywhere near clear enough! Would you like to edit that section of the page to put in instructions that would have helped you had they been there? Or would you like to post some suggestions here and we'll update the page?

**Comment by oktayacikalin** [comment]
@Alys I could open my stats view by going into social -> group and clicking on my name. Is there an easier way?
Sure - I could update the wiki page.

**Comment by Alys** [comment]
@oktayacikalin No, that's the recommended method from the wiki page. Sounds like it's okay, but feel free to clarify it if you think it needs it.

**Comment by oktayacikalin** [comment]
@Alys Perhaps we keep it as is. I don't want to blow the section up too much..

Or do other readers here think differently?

**Comment by TheHollidayInn** [comment]
I have confirm that this happens with a German test account but does not occur with a French and Russian test account. I think to have this issue solved we should make a list of affected countries (and continue to add) on the subscription page. We should then display the work around or suggest using a different payment method. Thoughts?

**Comment by lemoness** [comment]
Do you mean that this would display for all users? I'm concerned about
that, since it makes the subscription page much longer and makes the site
seem buggy. I'd prefer that we investigate a different solution.

**Comment by TheHollidayInn** [comment]
It would only show for users trying to checkout with Paypal. Braintree is an option to support some countries, but it doesn't support all either: https://www.braintreepayments.com/country-selection. Japan is missing for example. 

I'll look into Paypal Pro, but it is looking like users will have to use a provider that supports them for recurring.

**Comment by paglias** [comment]
Looks like Germany and China aren't supported but there could be an alternative

> Recurring payments cannot be created for buyers in Germany or China. In this case, you can use reference transactions as an alternate solution.

https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRecurringPayments/

**Comment by TheHollidayInn** [comment]
Yea, that docs you linked are in the old SOAP library. I think that is all moved to PaypalPro now.

**Comment by TheHollidayInn** [comment]
Have we had any reports of this still happening? Here is the supported list that should be working for: https://www.paypal.com/us/webapps/mpp/country-worldwide which includes Germany. This was linked from the REST API support which includes recurring billing. If we have a report, I'd like to see if we are not specifying a param for them.

**Comment by Alys** [comment]
I and the other mods don't recall seeing questions about this for a while so I'm closing this. We can reopen it if needed.
