### ISSUE TITLE
Cancel Subscription Button Missing

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3383]
On Chrome, the cancel subscription button is missing, both when clicking on gems and going to the Settings > Subscription page.

**Comment by deilann** [comment]
I'm magical.

**Comment by deilann** [comment]
Anyone who needs to cancel their subscription before this hits the site: please email admin@habitrpg.com with your User ID.

**Comment by lefnire** [comment]
Live, thanks @deilann

**Comment by deilann** [comment]
np :)
