### ISSUE TITLE
No avatar picture

### ISSUE THREAD

**Issue by afejesrichard** [HabitRPG/habitica#3384]
Hello!

I just started to use this site, like literally 5 minutes ago, and I can't see a single picture on the website. Not my avatar, neither my other party member's, and nor other avatars or pictures. I tried delete the cookies, log out and log in again, but nothing helped.

**Comment by deilann** [comment]
What browser are you using?

**Comment by afejesrichard** [comment]
Mozilla firefox, the latest version
(Also... a few minutes ago, it did work)

**Comment by deilann** [comment]
Can you do a hard refresh for me?

Shift+Ctrl(Cmd on macs)+F5

**Comment by afejesrichard** [comment]
I don't know why, but it did work. Sorry for the silly problem

**Comment by deilann** [comment]
It's okay. It wasn't your cookies that were the problem -- you needed to
clear your cache. :)

A hard refresh loads the page without cache.
