### ISSUE TITLE
I am still receiving benefits even though my credit card expired

### ISSUE THREAD

**Issue by Gaellan** [HabitRPG/habitica#3385]
My id is 97a2b542-8c85-4b69-a7d8-e0ac2b2946c0 I suscribed to HabitRPG a few months ago, I just realised this morning that the card I used has been expired for more than one month but I still have access to the benefits such as buying gems or receiving mistery items.
##

**Comment by deilann** [comment]
Can you check and see if payments have been going through on your new card?
Sometimes CC providers will temporarily allow recurring approved payments
on expired cards to go through as if it's on the new card.

Thank you for being honest!

@lefnire If it's not the case that the payments are going through, I guess
this would mean that failed Stripe payments do not properly trickle back to
Habit?

**Comment by Gaellan** [comment]
I only have access to bank statements from March 4th to now but nothing has been charged during that period of time, even though I believe I received the April mistery item (The butterfly set ?)

**Comment by jarrett** [comment]
> @lefnire If it's not the case that the payments are going through, I guess
this would mean that failed Stripe payments do not properly trickle back to
Habit?

I did a Stripe integration recently, so I'm familiar with the Stripe API. (I'm still getting to know the Habitica codebase, though.) I can look into this issue and post my findings here, if nothing else. I know this is a three-year-old issue, so I wanted to check in before going down the rabbit hole. Does this still need investigation?

**Comment by SabreCat** [comment]
I think this may be ready to close, actually, as we just recently implemented Stripe webhook handling for these things! @paglias can confirm.

**Comment by paglias** [comment]
Yep, it's fixed!
