### ISSUE TITLE
Disabling a Facebook account prevents from logging in

### ISSUE THREAD

**Issue by Glutexo** [HabitRPG/habitica#3386]
I registered to HabitRPG as a Facebook user and always used the Facebook login to access this app. Disabling of my Facebook account resulted in an unability to sign in to HabitRPG without re-enabling my Facebook account. It looks like a similar issue to #477, which has been solved by manually converting the account to the e-mail/password version.

As we can see, this is not just a matter of taste. If you lose your Facebook account, you lose your Habit as well. It’s not just about disabling your Facebook account, which is recoverable, but you can be e.g. banned from Facebook, which would result in losing the Habit account as well.

I think that a simple solution would be to be able to provide an e-mail address somewhere in the settings – then it would be possible to use the password recovery function. There should be no technical limitations for a single user to be able to sign in either by Facebook token or by e-mail/password, as many (if not almost all) applications do it so.

Just a note: The process described in the [FAQ](http://habitrpg.wikia.com/wiki/FAQ#Switch_from_Facebook_authentication_to_Username_.2F_Password) would work only if you have an access to a browser with an active HabitRPG session. If you don’t have access to your API settings, you can’t send an e-mail with your old UUID.

**Comment by lefnire** [comment]
If you need your old account UUID recovered, [send me](mailto:tyler@habitrpg.com) some very specific task text I can look you up by, like "Call Melody by Friday" or something

**Comment by Alys** [comment]
This has been fixed (options in Settings -> Site to add email etc).
