### ISSUE TITLE
Rebirth and limited edition items

### ISSUE THREAD

**Issue by LoicBrassart** [HabitRPG/habitica#3388]
I recently did a Rebirth, to test another class and to renew my H-Rrg experience.
Before I did, I read a lot on the wiki, and thought I could re-buy past "limited editions gears". Namely, my Ski-Sassin (Winter-Rogue) and my Sneak-Kitty (Spring-Rogue) outfits.
So I now find myself deprived of items I can't rebuy... I knew I'd lose every "useful" items (warrior stuff, rogue stuff). but had I knew I'd lose these items, but I wouldn't have rebirthed if I had knew I could lose these items.
Is this theawaited behaviour ? If so (I hope not ! So, I could rebuy those old comfy outfits !), could you please be more precise in the description of the Rebirth process ? 
(I'd be against it, because in my opinion you basically "punish" old players who were there from the beginning... But that's only my point of view)

Thanks for yout time and your hard work, and Long Life to Habitica !

**Comment by deilann** [comment]
You can repurchase them, just like you could if they were broken. But you
need to be a rogue in order to do so. Currently, you're a warrior.

**Comment by deilann** [comment]
Basically, you can only repurchase gear for your class. As a rogue, you will see the limited edition stuff appear again.
