### ISSUE TITLE
Feature Request:  Add a customizable "To Do in X Days"

### ISSUE THREAD

**Issue by ctuirmt00** [HabitRPG/habitica#339]
For example, if you had a bunch of things you wanted to accomplish TODAY instead of indefinitely.  And also, if you know something only needs to be done by 2 weeks from now, the ability to add that with no penalty?  I realize that the To-Do's have no penalty if you don't do them anyway, but some sort of calendar view or other type of option that's more in depth would be really cool!

Thanks!

**Comment by elssar** [comment]
Something like Daily, Weekly, Monthly tasks - and a custom option. Perform this in 10 days, or twice a week? Nice idea.

**Comment by wc8** [comment]
Are you thinking of something like [Scheduled Task Attack](https://trello.com/c/vPuLG1G0), at least in terms of assigning a date to something, or something more along the lines of [repeat in n days](https://trello.com/c/XuVokK2V)? Or perhaps just the ability to say 10 days from now and HabitRPG figures out when that is?

**Comment by killroy42** [comment]
Like a pay rent once a month, buy petrol every other week type stuff...

**Comment by StanLindsey** [comment]
This is currently the second most voted topic on [Trello](https://trello.com/c/XuVokK2V) so I'm going to close this for house keeping. 

=D

**Comment by wc8** [comment]
Another pertinent request: [Dates & Deadlines](https://trello.com/c/i6kXvNY2), especially the Start Date might speak to this request. 
@ctuirmt00 I just noticed your request for a calendar view. Would the ability to add dates to tasks be enough or do you have something further in mind?
