### ISSUE TITLE
spent Gems but didn't receive quest scroll

### ISSUE THREAD

**Issue by Yuubou** [HabitRPG/habitica#3390]
I tried posting on this thread but I don't think it worked b/c its closed:
 Party Leader spent Gems but didn't receive quest scroll #2996 

But basically, I had to buy 2 extra scrolls before my item inventory was credited with a scroll.  Here's a screen shot after I bought the first phantom scroll:
![scrolls](https://cloud.githubusercontent.com/assets/6673261/2851776/5d50ea16-d122-11e3-8213-debbe01a60ec.png)

Since I wasted 8 gems it would be great if you could recredit them to my account:
UUID: 7846c2cc-400d-4aff-b1ad-40ee3d68305c

Thank you!

**Comment by deilann** [comment]
If you read that, it was not closed because it was resolved, but because it was a dupe. This is the master ticket: https://github.com/HabitRPG/habitrpg/issues/2592

Refunding your gems.
