### ISSUE TITLE
Spent Gems, No Quest Scroll

### ISSUE THREAD

**Issue by Mixtercasual** [HabitRPG/habitica#3391]
I tried to buy the Firey Gryphon quest, but after spending 8 gems (the first four buying it, the second four mistakenly thinking I forgot to buy it), I still don't have the quest scroll. I would appreciate a refund, or, at the very least, to actually the scrolls I bought.

User name: Mixtercasual
User ID: 7ffc7c96-b7db-4f30-86fd-9c37eb251aea

**Comment by deilann** [comment]
Can you do me a favor and tell me how many scrolls you _actually_ own, like appear in your inventory, and how many scrolls total show up after the word quest scrolls in parentheses? I'm gonna refund you your gems. This is likely https://github.com/HabitRPG/habitrpg/issues/2592

**Comment by Mixtercasual** [comment]
Now it says 2 and I have 2 scrolls. Thanks.

**Comment by deilann** [comment]
Awesome! THat's how it should be.
