### ISSUE TITLE
Facebook login not working at all

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3393]
This issue started roughly 4 days ago, before which there was no problem whatsoever.  

When I visit the site, the Play button is extremely unresponsive.  Most times it doesn't respond to a click at all.  Occasionally I can get the login dialog to show.

I log in via Facebook.  However, when I click the login via Facebook button, it takes me to Facebook and I punch in my details (saved on this computer so I know they're correct), I get taken BACK to the homepage, with a bizarre, long URL which I assume includes my user ID (I'd paste this but I can't get the Play button to respond right now), but the Play button is there and not my tasks.  If I manually go to https://habitrpg.com/#/tasks, I am presented with a default task sheet where everything is labelled with what I assumed are their code names (again, I'm unable to copy examples right now).

I thought about creating a new account with Habit directly, but my username and email address are both tied up with the Facebook login, so I can't use them.

Some additional details. I'm using the website version, through Firefox 28.0, on a Windows 8.1 machine.  Anything else I can add to help, please let me know.

**Comment by deilann** [comment]
Sounds like bad cache times. Can you do a hard refresh for me?

Shift+Ctrl(cmd on macs)+F5

**Comment by ghost** [comment]
Sure, that doesn't seem to have had any effect.  Oh, I've also tried clearing out my cookies manually, to no avail.

**Comment by deilann** [comment]
Not cookies, cache.

Can you please clear your cache.

**Comment by paglias** [comment]
Could you try deleting localSotrage? I'm from mobile so I can't explain it
but a search on Google for "clean/delete localstorage" + browser name will
tell you how
Il 01/mag/2014 23:39 "arirish" notifications@github.com ha scritto:

**Comment by ghost** [comment]
Sorry for the confusion, deilann.  I did clear my cache when you asked.  I was just adding some additional info as an aside (namely, that I've ALSO tried clearing my cookies).

**Comment by deilann** [comment]
Sorry -- before I asked you to do a hard refresh, not to clear your cache,
so there was no way for me to know.

What browser are you using?

**Comment by ghost** [comment]
OH, hey, it looks like doing the hard refresh may have fixed it after all.  At least, it didn't seem to at first, but now it looks to be working.  I didn't do anything else in the meantime.  

Interestingly, none of my streaks have been lost, though my HP is very low.  I guess I'll keep an eye on it, but hopefully that's solved it.  Let me test if it holds over restarting Firefox.

EDIT: It seems to be fixed now.  I'm slightly annoyed that it was solved by something so simple, assuming it was the hard refresh, but glad it's fixed.  Surprising how much I've come to rely on the site for helping me stay on top of  things.  Thanks, deilann.

**Comment by deilann** [comment]
Awesome.

Yeah, what the hard refresh does is it loads the page without cache.

**Comment by negue** [comment]
As @arirish already wrote this issue was fixed, closing this.
