### ISSUE TITLE
Buying quests

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#3394]
I just bough 3 quests (Spirit of Spring, Hedgbeast and Gryphon) on top of 2 quests that I already had in my inventory (Egg Quests) But the Hedgebeast quest and Gryphon Quest have not appeared in my inventory, despite the gems for them 'leaving'. I was buying in bulk to resist the temptation of me spending gems on stuff like skin colours, purely for myself, as opposed to quests which everyone in my Party can enjoy.

UUID: d62e990b-d300-46cf-9dc5-bc99d122ac36

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/2592

I'll refund you the gems, but if you still have a negative quantity of hedgebeast or gryphon scrolls, they still won't show. Let me know if that's the case.

**Comment by k8sullyvan** [comment]
You work quick, Thanks! I've just bought them and the quests are there this time.

**Comment by deilann** [comment]
np! Glad to help
