### ISSUE TITLE
Item X is removed upon death, when checking back the next day X is still present but item Y is gone instead.

### ISSUE THREAD

**Issue by kahdri** [HabitRPG/habitica#3396]
I'm a new player and had my first death during a quest a few days ago. I received a pop-up message informing me my Egg Shield had been removed. I went to the equipment page and verified this; all other items were present and the Egg Shield was gone.

The next day, however, the shield was back on my avatar, and when I went to check my equipment the green clover armor had disappeared instead. It's frustrating as the armor cost 20 gold more and I was sadly not able to save up enough for another before the items were removed from the shop. I would have had enough to re-buy the shield.

**Comment by deilann** [comment]
This is https://github.com/HabitRPG/habitrpg/issues/2789

However, you don't have to repurchase limited edition armor before it is removed from the shop if you've purchased it before. Once you've purchased it, as long as you are the correct class when it is broken, you will be able to repurchase it forever.

**Comment by kahdri** [comment]
I did not have a class when I lost the armor. It was available for repurchase for a couple of days while I saved up, then all the green items were gone from the store and I saw red/yellow Fuzzy Puppy items instead. I bought the armor from that set. The green armor was nowhere to be seen and stil isn't. 

Another day or two later I got to level ten and chose healer.

**Comment by deilann** [comment]
Not quite true. Until you choose a class, you are de facto a warrior.
If/when you become a warrior again, those items will become available to
purchase again because you had bought them.

**Comment by kahdri** [comment]
I'm confused. If previously purchased gear is meant to always be available (depending on class), why wasn't the green armor available for purchase before I became a healer, when I was forced to buy the red/yellow armor instead?

**Comment by deilann** [comment]
The puppy armor is only available to healers, so you must be getting your
timelines mixed up. You wouldn't be able to see it at all if you hadn't
already chosen your class.

**Comment by kahdri** [comment]
I see. It has been a few days now so I may have chosen my class just before or the same day as I had saved up 90 gold for the armor again, I thought for sure it was the day after. As long as it will be available if I change back to warrior I'm happy. It was losing the chance to get it again forever that bothered me.

**Comment by deilann** [comment]
Yeah no you will definitely have it available to purchase whenever you go
warrior again. :)
