### ISSUE TITLE
Lines of chat scroll slightly even without scrollbars

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3398]
Chrome browser, main Habit site.

I find that when I'm using my scroll wheel to navigate through a chat (e.g. Tavern), that if I land my cursor wrong, an individual line of chat bobs up or down on a scroll wheel tick instead of scrolling the full list.

Hard to see, but chat line as it starts off in Tavern:
![screenclip](https://cloud.githubusercontent.com/assets/4501321/2862142/25f396b0-d1ed-11e3-9301-11265bee46bb.png)

Move mouse over text so that I get a text selection cursor, scrollwheel down:
![screenclip](https://cloud.githubusercontent.com/assets/4501321/2862148/400124fa-d1ed-11e3-825e-7d7405506773.png)

Note the slightly different alignment of text vs. the user's name.

**Comment by deilann** [comment]
It's not just single lined ones.

If I click on any chat message, then mouse wheel, they bob, regardless of length.

**Comment by SabreCat** [comment]
Updated! I must not have placed my cursor just right when trying to reproduce it on multiline messages.

**Comment by kangabell** [comment]
@SabreCat Are you still seeing this issue? I can't reproduce it. Using latest Chrome, v 39.0.2171.95, on OSX.

**Comment by SabreCat** [comment]
@kangabell: No, doesn't look like it. Closing!
