### ISSUE TITLE
Indicte how long ago habits have been clicked

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#340]
I can never be entirely sure if I have already updated a habit. I don't know if the system updated, as sometimse it looses an update if hte internet connection is flaky. I think I often double update a habit, or not at all. The graphs ususally don't work either. It would be good to have a clear indicator when a habit was last updated.

**Comment by wc8** [comment]
Would this [request](https://trello.com/c/uaIl9x5r) meet your needs or would you want to see an actual [time].

**Comment by wildcate** [comment]
I second the suggestion! For me, something like "a few minutes ago" and then "1 hour ago" .... to "x days ago" would be fine. I also forget whether (and when) I clicked stuff...

**Comment by wc8** [comment]
I added a note to the [request](https://trello.com/c/uaIl9x5r).
