### ISSUE TITLE
Scroll buying is a bit glitchy (second occurence)

### ISSUE THREAD

**Issue by LoicBrassart** [HabitRPG/habitica#3400]
I just bought two Scrolls (1x Spirit of Spring and 1x Fiery Gryphon), and my scroll count went from -2 to 0. I was deducted my gems but never got my scrolls.
Could someone please refund or provide the scrolls ?

**Comment by deilann** [comment]
This is https://github.com/HabitRPG/habitrpg/issues/2592

What's your UUID?

**Comment by LoicBrassart** [comment]
917eae07-7ccc-4b2c-88d2-5a904366997e

**Comment by deilann** [comment]
Refunded!

**Comment by LoicBrassart** [comment]
I tried to rebuy both scrolls, but only one got in my inventory (I miss a single Spirit of Spring).
Sorry to bother you, but could you get me the Scroll instead ? (I'd like to buy them before the end of the season...)

**Comment by deilann** [comment]
I cannot give you the scroll instead. I do not have that power. That means
you have a secret something else that's negative. However, I'll refund you
four more gems and you can purchase again.

That being said, the Spirit of Spring quest isn't going anywhere. It's a
forever quest.

**Comment by LoicBrassart** [comment]
Thank you for the refund and for the explanation.
(As a note : maybe it would be nice to have a visual signal to know what is temporary and what is not)

Thanks again, and please keep up the good work ;-)

**Comment by deilann** [comment]
Generally, things that are exclusive are marked as exclusive. So, just the
egg hunt was exclusive, and the Spring Fling equipment. Bailey will also
let you know if something's about to leave the market.
