### ISSUE TITLE
Lost 2 HP for no obvious reason

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3403]
Last night, AFAIK, I went to bed with all dailies checked off, and 50/50 hit points. I have no negative habits.

This morning I find myself with 48/50 HP - and a perfect day buff, so it's not a matter of my last daily not being recorded. 

Possibly relevant: the main site is down this morning, so I logged in to the beta site. 

Not a problem for me, but does look like a bug, so probably of interest for you.

**Comment by deilann** [comment]
Huh. That is interesting.

**Comment by deilann** [comment]
Oh, actually, I bet I know what this is.

I wonder if the last time you signed onto beta, you had 2 lost health and
beta's down, just not as visibly (not fetching data from servers). So the
two lost HP are actually not lost server-side -- you're just not getting
the server stuff.

**Comment by ArlieS** [comment]
I do appear as the right level, and I can even see that cron ran - with an extremely disappointing 4 eggs found on the April quest. So it's clearly getting _some_ data.

**Comment by deilann** [comment]
Cron running is good. But that also happens server side. The fact that you
can even see messages in your party chat means you're better off than me. :P

Once the application errors have quieted down, probably do a hard refresh
and see if the 2 HP are still missing. If it is, it's unrelated, if it
isn't, it's probably related.

It's good to see you back, by the way!

**Comment by ArlieS** [comment]
I've now got the main site to load - and I'm down 2 HP there too. So it's not a stale-beta-data issue. 

Also, and irrelevant to this bug,  the daily I clicked on the beta site is showing as clicked on the main site, i.e. things I did on one got transferred to the other.

**Comment by deilann** [comment]
That's supposed to happen. So, beta has some stuff that's not on prod, but
your tasks and stuff are the same between them. That way, you can decide to
use beta or not.

**Comment by ArlieS** [comment]
Yeah. Was trying to say Beta appeared to be behaving normally - no data loss because of the earlier outage. Sorry about being confusing. It appears to be a >1 caffeinated beverage morning for me ;-)

**Comment by deilann** [comment]
Yeah, when you were reporting beta working fine, both prod and beta weren't
working for me. :P So apparently you were just a lucky duck.

I need to go fine more caffeine as well.

**Comment by ArlieS** [comment]
In retrospect, I think I didn't have the perfect day buff yesterday, and misread something in my uncaffeinated state. Mystery solved - just an update that didn't take, and a normal "missed daily" penalty. Perhaps 2 "missed" dailies ;0) And now that I'm awake, I can even see which ones - the two with the improbably short streaks ;-)

**Comment by deilann** [comment]
ha!

(more words go here)

(wanders off for caffeine)
