### ISSUE TITLE
Week start in calendar

### ISSUE THREAD

**Issue by dinosw** [HabitRPG/habitica#3405]
Please fix the week start in calendar, when choosing due dates.
It show Sunday as the first day of the week, instead of Monday.
I know a few countries have Sunday as the first day of the week, but the far majority of the world, uses Monday as the start of the week.

**Comment by crookedneighbor** [comment]
@dinosw Thanks for your feedback on this. Sorry it took so long to respond (over a year, yikes!). If this is still desired, please [post about it on our trello board](https://trello.com/c/odmhIqyW/440-read-first-how-to-request-a-feature-table-of-contents)

**Comment by dinosw** [comment]
No matter what, that Yikes comment made my day ;-)

**Comment by ndossougbete** [comment]
This still seems to be an issue on the website, even after I switched my language to "British English". Is there a way to switch the first day of the week that I missed?
