### ISSUE TITLE
Did not get notice that subscription would be cancelled if recurring charge was removed

### ISSUE THREAD

**Issue by bonesarelazy** [HabitRPG/habitica#3406]
I did not get a note about removing the automatic paypal charge equaling canceling the subscription. I also wasn't made aware in advance that the charge was recurring. I don't want to have a recurring charge on my pp account, so I removed it immediately, loosing all benefits of subscribing, and I'm not thrilled. Can this be reversed, or at least refunded so that I can resubscribe? My subscription was only active for about an hour, so I didn't get to use it.

**Comment by deilann** [comment]
@lefnire can you handle this one?

@bonesarelazy The word subscription tends to imply a recurring charge -- think a magazine or newspaper subscription or an MMO subscription. I'm not trying in this to say "you should have known better", but this should help you in the future. If other sites offer a subscription, it will be a recurring charge unless it specifically states that you're purchasing a block period of time.

**Comment by lefnire** [comment]
Alas that Habit's in the clear. The details inform users that [it's a monthly subscription](https://www.evernote.com/shard/s17/sh/8129ec71-1825-4155-9cdb-c0c70b54f21b/58a2f26ec6add155cea0efe10fe7179d), and gives all fair warning of what will happen [when canceling one's subscription](http://i.gyazo.com/4983962216fcdbc0ab40dfb1e796e897.png). If users who have have canceled their subscription feel they've been wronged, [email me](mailto:tyler@habitrpg.com) and I can reimburse the last charge of a cancelled account, but unfortunately I can't setup a month of perks.

**Comment by deilann** [comment]
There being a notice, I'm gonna close this.

**Comment by bonesarelazy** [comment]
lefnire, I didn't cancel via habit, I just took the automatic recurring charge off of my pp account. That is why I didn't see the notice. I understand what a subscription is, however I've had subscriptions of varying lengths, and (wrongly) assumed that this was simply a month long subscription. If I cancel a magazine subscription, I wouldn't expect to have to send the magazine back. In this case, I thought that by paying for a single month, I would have access to the benefits for a single month.

**Comment by deilann** [comment]
As @lefnire said, if you want to handle that, please email him. Generally,
it's a bad idea to cancel recurring payments from the back end if you want
to see any warnings about what will happen in case of canceling.

**Comment by bonesarelazy** [comment]
I emailed lefnire right after responding here. I just wanted to make it clear that I hadn't seen the warning. I don't really do online subscriptions, so wasn't aware that I was doing it incorrectly.

**Comment by deilann** [comment]
It's okay. :) Yeah, in the future, usually the website has a "cancel
subscription" option -- think about doing it through paypal like asking
your bank to cancel your gym membership instead of going through the gym to
do it.  You want to be able to cancel it through your bank, in case the gym
does something that makes it hard to cancel, but you generally want to go
through the gym first. Make sense?

**Comment by bonesarelazy** [comment]
Yes, it does :)
