### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by SugarShin3** [HabitRPG/habitica#3407]
I was just trying to log in to my mother's account for her, as she said she was having issues. I started a new Firefox private window and pulled up the HabitRPG start screen. Clicked the PLAY button and typed in her usual info, and got a "Wrong Username/password" notice (see attached picture). Tried a couple more times, got the same notice. Then I requested a new password in case she had changed it without telling me, and got the new password from her email. Copypasted it, no luck. Typed it individually, no luck. Did a hard reset for the browser, no luck. No cache or cookies should be attributed to the browser because it's the private tab.

Any idea what this could be?
![error](https://cloud.githubusercontent.com/assets/6679022/2872106/e2441b00-d341-11e3-81eb-96885dcc0fc5.png)

**Comment by deilann** [comment]
Are you sure you're using her username, not her email?

**Comment by SugarShin3** [comment]
Yup! I set up the account for her myself, so I know what her login info was to begin with, which was why I was confused it said the password was wrong from the start.

**Comment by deilann** [comment]
I'm almost wondering if "she was having issues" is she deleted her account.

Can you post her username or UUID if you have it, so @lefnire can
investimigate?

**Comment by SugarShin3** [comment]
UUID is 008c3908-81ab-4dad-a488-5fc020f9a88c. She is still showing up in my party when I log in, and I'm not having issues logging in for myself.

Thanks muchly!

**Comment by lefnire** [comment]
Her username is **JocelynAvalon**. Case-sensitive. Have her try again with that, forgot password if still issues, and [email me](mailto:tyler@habitrpg.com) if _still_ issues.
