### ISSUE TITLE
Axe blocking face

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#341]
Not sure if this is the right place to report this, sorry... but I bought the ax for my character, and in the avatar it's blocking a third of her face. I checked on the kickstarter picture page and it looks like the ax is supposed to be held to the side, like the swords, so I figured I would mention it. Keep up the amazing work! You guys are great :)

**Comment by lefnire** [comment]
Got a whole new sprite system in the works, including tons of character
customizations (and fixed item positioning). ~1wk to deploy

**Comment by StanLindsey** [comment]
Going to close this for housekeeping. Thanks for bringing it up @lemoness
