### ISSUE TITLE
\u2630 ☰ "Trigram for Heaven" not supported on mobile devices

### ISSUE THREAD

**Issue by tjwds** [HabitRPG/habitica#3411]
Any way we could switch this over to a glyph?

**Comment by Alys** [comment]
Is this still an issue? One instance of `&#9776;` was been replaced by glyphicon-align-justify in https://github.com/HabitRPG/habitrpg/pull/4855 and I'm not sure the other instances are ever seen on mobile devices. They aren't in the Android app, nor in the website on an Android phone browser. However perhaps on an Android tablet browser, the full website menu system is used, which would mean that the other instances `&#9776;` would be seen. I have no idea about iOS devices.

See also the discussion of options in https://github.com/HabitRPG/habitrpg/pull/3412
and https://github.com/HabitRPG/habitrpg/pull/3427 "Menu line compromise built with css borders"

**Comment by Alys** [comment]
See also the discussion of options in https://github.com/HabitRPG/habitrpg/pull/3412

**Comment by Alys** [comment]
And see also https://github.com/HabitRPG/habitrpg/pull/3427 Menu line compromise built with css borders
