### ISSUE TITLE
Infinite loots with dailies.

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3413]
Hello,

I am new on GitHub, so I'm not sure how this works but here's what I found.

When a daily gives a loot, I can uncheck it (the system withdraths the gold and exp, but not the loot), then I can recheck the daily (more gold and exp, plus a loot), I uncheck it (minus gold, minus exp, keep the loot), check it again (more gold, exp and loot) etc. I did it 5 times, got 5 loots. Maybe I'm just super lucky, maybe there's a bug. I'm a rogue lvl 11 if this may be of any help.

**Comment by deilann** [comment]
Yes, there's no real way to stop this. But if people are going to cheat, they're going to cheat. It only hurts them. Doing it 5 times and getting 5 drops is lucky -- drop rates usually don't make it that easy, especially at level 11. But yeah, there's no real way to stop this, and I don't find it a big deal or a worry.
