### ISSUE TITLE
some issues with point allocation

### ISSUE THREAD

**Issue by Rominator425** [HabitRPG/habitica#3418]
hi guys I'm noticing a small issue with attribute points as I go up in level. when I went up in level from 24 to 25 it gave me my point as usual, however when I went from 25 to 26 it took the same point away and didn't give me my new point for level 26. no biggie. I died and dropped back to level 25 and it gave me 3 attribute points. I don't like to cheat so I only assigned one point (the point that I originally lost) I still have 2 more points (which is nice in case this happens again). just thought you guys might want a heads up on this. Thanks a bunch and keep rockin' the site your doing a fantastic job! Also, I was wondering....the habit-rpg website isn't working on my cell phone yet and the app is still kinda flaky do you guys know when you might be getting around to fixing it?

**Comment by deilann** [comment]
How many total attribute points do you have? Add them all up.

**Comment by Rominator425** [comment]
I'm level 25 but I only have a total of 23 attribute points. does that mean I get to add the two extra 2 points?

**Comment by deilann** [comment]
That means the 2 extra points aren't extras at all. :)

You're where you ought to be.
