### ISSUE TITLE
Add Front Page Wiki Link to Resources

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3419]
We have a lot of wiki links in the resources spot next to the Tavern, but I realized we don't have one for the Wiki itself -- which is a great resource. While yes, one could find the wiki by clicking on FAQ or LFG, I think the wiki really needs to be added as a link on its own so people know it exists, which isn't apparent from FAQ or LFG.

**Comment by tjwds** [comment]
There you go!  In my experience, "wiki" is the same in all languages, but I'm not so sure about Ukranian and Russian.

**Comment by deilann** [comment]
:thumbsup:
