### ISSUE TITLE
Mobile App Immediately Crashes

### ISSUE THREAD

**Issue by Panteleon** [HabitRPG/habitica#3422]
I apologize if this has been addressed, but I couldn't find anything similar via search above.

One small bit of ramble before I mention the bug: I love HabitRPG.  Lots of real changes for me, pleasure to use.  Thanks for your time, really!

Anyhow, emm... the mobile app kinda no longer works?  I have a Motorola Razr Maxx HD (yes, the phone's name is as obnoxious to me as I'm certain it is to you), and it crashes as soon as I try to scroll up or down through my Habits/Dailies (whatever is on the screen at any given time).  This really only starts after the advertisement at the top manages to load; before that, it's all spin-y wait symbol and some scrolling if I like.  But, again, the capacity to scroll without crashing the program ends as soon as that Advertisement loads.

For that matter... also, before the advertisement loads, none of the buttons work (should I try to press them before crashing out).

Lastly, and most importantly to me, thanks again for all your work, folks!

**Comment by deilann** [comment]
Check out this baby: https://github.com/HabitRPG/habitrpg-mobile/issues/200

:)
