### ISSUE TITLE
Vagrant box

### ISSUE THREAD

**Issue by jbutz** [HabitRPG/habitica#3424]
326b65a8e0f9fe4d6f4d7dbc19bfd383919d5a2d broke the ability to get the vagrant box

**Comment by thepeopleseason** [comment]
Are you running Vagrant 1.5+? The documentation indicates that that's now a minimum requirement for vagrant.

**Comment by jbutz** [comment]
I have vagrant 1.5.1. It says it can't find the `thepeopleseason/habitrpg` box.

**Comment by thepeopleseason** [comment]
Hmm... The box is showing as available here: 
https://vagrantcloud.com/thepeopleseason/habitrpg

Do you have connectivity issues to vagrantcloud.com? Can you post a full error message?

**Comment by jbutz** [comment]
It looks like this is only an issue if you already have a vagrant box from the old way. If you remove the `.vagrant` directory then it works.
