### ISSUE TITLE
[tasks] Reward from challenge cannot be removed

### ISSUE THREAD

**Issue by Aquea** [HabitRPG/habitica#3429]
I joined a Challenge which consisted of two tasks: a to-do and a reward. I did the to-do, and then bought the reward. The reward didn't disappear from my reward list. The Challenge doesn't display in my Challenges list or in the Tavern, so it prolly was closed/deleted? 
I am unable to edit the reward, because it has the "Challenge" status, and cannot delete it. Since there is no Challenge associated with it, I cannot leave it to check the "delete tasks" option.

_edit by admin:_
## What to do if you experience this issue:

Find any task (Habit, Daily, or To-Do) that is associated with the same challenge (if it's a To-Do that you've completed, you'll find it in the Completed To-Dos tab and you should untick it make it uncompleted). Then click on the task as if you were completing it. That should change the task's megaphone icon into a broken megaphone icon, which you can then click to delete all challenge tasks, including the reward. For more information or if this process doesn't work, see "Deleting a Challenge Task" in [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) for some other suggestions.

If the challenge **never** had any tasks but only rewards, comment below. Include your unique user ID  from [Settings -> API](https://habitrpg.com/#/options/settings/api) and tell us the reward's description.
##

**Comment by deilann** [comment]
This is a known issue, especially for challenges that are incredibly large.
The current workaround is to click the task. So go ahead and purchase the
reward again. You can refund yourself the gold in Settings > Site > Fix
Character Values if you so desire.

Clicking on it should make it register that it's broken, with the broken
megaphone. Click on that, and it should ask if you want to keep or delete
the tasks.

**Comment by Aquea** [comment]
I already bought the reward a couple of times, but it does nothing.

**Comment by deilann** [comment]
Maybe the workaround doesn't work with rewards.

Can you go to the completed To-Do (there's a tab on the bottom) and check
and uncheck the To-Do?

Do you remember what challenge it was, as well?

**Comment by Aquea** [comment]
The task was about taxes.
I went to the completed to-dos as you suggested and the to-do there had the broken challenge link, which solved the issue. The broken challenge link didn't appear for the reward, tho, so it might be useful to make sure it shows there too.

**Comment by deilann** [comment]
Oooh, that is interesting to know. You can't delete a broken challenge
reward without one of the tasks. That could actually be a really big
problem if someone say, decided to create a reward-only challenge. I'm not
sure why they'd do that, but they might.

**Comment by atalaya** [comment]
I have the same problem with the same "taxes" challenge. Wondering if there has been any resolution?

**Comment by Alys** [comment]
@atalaya What is your unique user ID? ([Settings -> API](https://habitrpg.com/#/options/settings/api))

**Comment by Alys** [comment]
@atalaya Actually, sorry, don't worry about the user ID; I misread this issue. There should be a completed To-Do that you can use to get rid of both the To-Do and the reward - look in your Completed To-Dos tab and follow the process described above. For extra information, see "Deleting a Challenge Task" in [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task).

**Comment by paglias** [comment]
This should be fixed
