### ISSUE TITLE
March and April Subscription Items Lost

### ISSUE THREAD

**Issue by danielckeaton** [HabitRPG/habitica#3431]
All right, I know it's a week into May, but I still hadn't opened my April subscriber mystery items yet... I was saving them to open after I was done with this semester of classes. But now I can't open them, because both those and my March items have vanished from my account. (I've been a subscriber since February 28th, and received both the March and April items correctly when they came out. They're just missing now. I never received the February items, but I don't know if that's relevant to my current problem...)

I did die last night. I've seen my character die a few times on HabitRPG since subscribing, though, and never had any issues with losing subscription items before. I also did lose one regular piece of equipment as well. But after that point, the little present notification icon wasn't in my top-right bar anymore, and the little box in the marketplace now shows "0" instead of "2," and displays the message "empty" when clicked. And no mystery items are in my inventory. I realize I probably should have opened and equipped those items earlier, but I would like them back, if that's possible.

My user ID: 2680e9b1-d37b-400e-84bd-7988b00e1f96

**Comment by lefnire** [comment]
I'll get you sorted sometime today, I'll ping you back

**Comment by lefnire** [comment]
all set
