### ISSUE TITLE
clean up swagger-ui

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3432]
Looks like the swagger-ui CSS isn't being setup properly anymore (https://habitrpg.com/static/api). Probably an update to the bower module or such. Super low prio

**Comment by lisbakke** [comment]
It'd be great to get it running again, it's an outstanding source of documentation. I have been relying on it lately.

**Comment by phillipthelen** [comment]
Fixed this in #3636 does somebody want to close this?
