### ISSUE TITLE
Time zone broke my streaks - what do?

### ISSUE THREAD

**Issue by MaddieM4** [HabitRPG/habitica#3433]
I recently went on a round-trip from my home on the west coast, to a business trip on the east coast. Going east was no problem, but I arrived on the west coast after midnight EST, and refreshed my browser before the time settings had been corrected.

Basically, this caused an erroneous day tickover, and now my precious streaks are dead. Is there anything I or the admins can do about this short term? What can we do to try to prevent or mitigate this in the future?

Username: RainflyX
Platform: Mac/Firefox

**Comment by deilann** [comment]
You can fix your streaks by opening up the daily to edit, going to advanced
options, and manually entering in the correct streaks.

The best thing you can do if you're traveling is to go in the inn whilst
traveling. Once you get into the correct time zone, check out.

**Comment by MaddieM4** [comment]
Thanks, that fixed it (sorry for the delay getting back about it).

I normally don't visit the inn while traveling out of a misguided "I CAN STILL DO THIS" attitude. I think the timezone wrinkle is gonna force my hand from now on, though.
