### ISSUE TITLE
Health Dropping

### ISSUE THREAD

**Issue by kwlosko** [HabitRPG/habitica#3434]
For some reason, every night, my health drops, even though I have all of my dailies completed. My inactive dailies - the ones I only do on one day - are turning red, as well, and I think that it's counting them, even though I only have the one day checked off for it to check them, and they haven't been turning gray. The drops are increasing drastically, and if I don't get this fixed I'll die within two days without having done anything.

**Comment by casicastiel** [comment]
Is it possible that your dailies are only turned _off_ for certain days of the week, not turned _on_ for certain days? If they aren't gray, that means they're active for the current day.

**Comment by deilann** [comment]
casicastiel is right -- if a daily is not supposed to be active, it should
be grey, so you shouldn't notice it turning redder.

**Comment by kwlosko** [comment]
Thank you! I guess that was pretty dense of me, huh? Should be fixed now!

**Comment by deilann** [comment]
Yay! If you want to restore any lost health, go to Settings > Site > Fix
Character Values to top yourself off.
