### ISSUE TITLE
Insert todos at bottom of list?

### ISSUE THREAD

**Issue by mockdeep** [HabitRPG/habitica#3436]
I type in my todos in the order that I think of them, which also often corresponds closely to the order that they need to be done in, so it's a little annoying that new tasks are added at the beginning of the list. I often type up my list somewhere else, then add them in reverse order in Habitrpg. Is there a way to have tasks inserted at the bottom of the list instead?

**Comment by tjwds** [comment]
The current system is set up the way it is to present a clear chronological order for the tasks that you have yet to do, the more red ones at the bottom.  For the time being, you can drag and drop them to order them in any way you like; you may have to clear your completed tasks before this ordering will save, however.

**Comment by mockdeep** [comment]
I guess I tend to think of my list as a queue, oldest at the top, newest at the bottom. I also like to add my schedule for the day to the To-Do section.

**Comment by deilann** [comment]
Challenges add To-Dos to the bottom, rather than the top. You could create
a dummy challenge for yourself, and add your To-Dos through that.
