### ISSUE TITLE
Healers can prevent death prior to partymates' cron runtimes.

### ISSUE THREAD

**Issue by thepeopleseason** [HabitRPG/habitica#3438]
Upon logging in this morning, I discovered one of my party mates had -5 HP. I quickly cast Blessing twice to pull him to 16 HP. I specifically asked him if he encountered death upon login, and he informed me later that he didn't. 

I know this is directly related to character state checks only happening on either cron or task update. 

Not sure if this necessarily needs fixing.

**Comment by deilann** [comment]
I personally see this as a feature, rather than a bug.

**Comment by thepeopleseason** [comment]
Haha. That works for me.

**Comment by deilann** [comment]
That was me personally! Not speaking as Habit. I don't know about anyone
else.

**Comment by thepeopleseason** [comment]
I figured, but this is essentially akin to #2433 (only regarding HP vs. XP) and #2673.

**Comment by lemoness** [comment]
Just wanted to agree that this has saved my party many times. I am a big fan of it!
