### ISSUE TITLE
Checklists no longer available on mobile

### ISSUE THREAD

**Issue by Drag0nsilver** [HabitRPG/habitica#3440]
Hi, folks!

Checklists are no longer available, either in the Android version or in the iOS version. Since I use checklists extensively, that means that these apps are no longer usable for me. Please restore this functionality to the mobile apps.

Sandra, the Silver Dragon
silver.dragon@mac.com

**Comment by lefnire** [comment]
Swipe left on the task, click the pencil icon. This was in the last announcement. Follow progress here https://github.com/HabitRPG/habitrpg-mobile/issues/199

**Comment by deilann** [comment]
You can get to the checklist by swiping to the left (or is it right?) then
clicking on the pencil icon.

**Comment by deilann** [comment]
Oh, hi @lefnire :P
