### ISSUE TITLE
Make News accessible through API

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#3442]
Hey,
currently the "newStuff" news are only available through the website/a modal there.
Would it be possible to have an API call, that returns news objects?

**Comment by lefnire** [comment]
the news is currently straight html. Our goal is to move it to the database (kinda CMS, so our mods can edit it too) and expose that via a route, but it's pretty low prio so unless a contrib tackles it, it won't be any time soon

**Comment by negue** [comment]
Is this a dupe of #1338?

**Comment by Alys** [comment]
Yup, good catch.
