### ISSUE TITLE
Monthly mystery items disappear if not "claimed"?

### ISSUE THREAD

**Issue by extrajordanary** [HabitRPG/habitica#3443]
Is the intended behavior of the monthly subscriber rewards such that if you didn't log in to hRPG before the end of the month to "claim" them that you can no longer get them? 

The present box is empty but I never got my wings and such from April.

UID: 7c389c86-74c3-419b-9cd7-94baafce2d49

**Comment by deilann** [comment]
I think it's expected, but not intended.

@lefnire should be able to help you. :)

**Comment by lefnire** [comment]
@extrajordanary give that a shot

**Comment by extrajordanary** [comment]
Hooray, all better! Thanks all!
