### ISSUE TITLE
Refactoring daysMissed

### ISSUE THREAD

**Issue by markusholdings** [HabitRPG/habitica#3444]
So I just finished my pertinent exams so I have more time to devote to the dailies bug.  As I've said before, the issue is that when the check for daysMissed is run, daysSince returns a 0 if 'lastCron' is the same day as 'now' even when now is past dayStart.  I'm worried though that just jumping in and fixing this might not solve everything.  I have lots of concerns with it's implementation.

So I'm going to work on refactoring the code and find what gets affected by the change.  @paglias mentioned that the daysMissed bug behaving the way it does should cause more widespread errors, but since this bug doesn't let cron happen during the critical start time, then any bugs that would also pop up don't have a chance to appear.  That said, fixing the immediate bug might be the same as opening up pandora's box.  In fact, I think that this might have been what happened to @colegleason 's solution since his solution is practically the same as mine, just another step back in the calculation process.

I'll probably be tracking my progress here rather than cluttering up anywhere else and if anyone has time, I'd really like it if they can check my work and see if its valid.

**Comment by paglias** [comment]
great! cc @lefnire

**Comment by lefnire** [comment]
@markusholdings Sorry I've been so far out of the loop on all this :( I'll try to catch up. In the mean time, be sure to run the test suite against your refactor as you go along. Particularly habitrpg-shared's tests, as they have a lot to do with cron.

**Comment by markusholdings** [comment]
@lefnire Its okay, so I have a few angles I'll be taking to tackle this.  I'll be working on three potential solutions at the same time.

Solution 1: Cole's Solution.  When this was implemented, we ran into several issues.  I'll dig around the tags to find where they were, then start writing tests for them.  It'll be the basis of my development, since his original solution and mine are very similar.

Solution 2: Changing daysSince.  This is the most immediate way to fix the bug.  However, in the comments, it says that daysSince is the absolute difference of days.  Which means that changing it might create bugs in places where it's assumed daysSince is assumed to return the absolute difference of days.  There's also a chance that Cole's solution might have triggered those bugs as well, but I haven't confirmed that yet.

Solution 3: Writing a new function gamedaysSince.  Basically, I'll take the code I put in my develop and move it into a new function meant to determine the subjective number of days relative to the user's dayStart.  However, this also could cause problems where places in the code assume daysSince is supposed to return the relative difference of days.  That will be a quick fix if that's the case though, because all I'll have to do is change daysSince to gamedaysSince in those locations.  The problem is finding them before its too late.

In essence, I'm faced with a catch 22, The objective is to minimize the damage before testing this locally.

**Comment by markusholdings** [comment]
Just ran Cole's Solution.  I ran into two issues with it:  The erroneous errors I mentioned in https://github.com/HabitRPG/habitrpg-shared/issues/199 appeared again, and one of my own tests failed for it.  Specifically, logging in twice during the critical time, even on the same day, caused cron to run.

I'll investigate further in a bit.

**Comment by markusholdings** [comment]
I think I found something incredibly interesting after looking at #2601.  That bug first seriously appeared after Cole's solution was implemented, right?  Which means that fixing the dailies but might end up aggregating that solution.  I came up with some thoughts on it, though.

One thought is the bug in his solution I found, if you log in during the critical time, then log in again, cron would run again, but unless someone had enough dailies that failing to complete all of them would kill them, it wouldn't account for that behavior.

The other one is much more complicated, and <b>much much much</b> stranger.  When I was first fixing the bug, I found that consecutive days logging in at the critical time, daysSince was counting one less than it rightly should have.  In other words, if you log in after midnight but before your cds one night, then do it again the next night, it would count as 0 days passed.  If you waited a night and did it two nights later, it would count 1 day passed.  There was no observable reason why it would do that, but I simply ignored it.

Here's the really weird part.  I placed some tests so I could fix it on my solution.  But when I implemented Cole's Solution, <b>it passed those tests no problem</b>.  Its strange because his solution and mine were practically the same (If yesterday < dayStart, account for that day), but handled differently (I added a day, he rolled the day back), Still, it wouldn't cause those issues.

And then there are the erroneous errors.  I'm beginning to think those erroneous errors arent so erroneous (lol).  If those tests are failing on the condition that no time has passed(Which would make sense), then that means somewhere, I don't know where, <b> Some ops are being duplicated, or even looped </b>.  This behavior only has a chance to occur if cron has a chance to run before dayStart,

So thats where I am right now.  I need to look through the code to find where it might be popping up, but my guess is that daysSince or startofDay is being called somewhere it shouldnt be.  I'll come back when I have something, but I might end up inadvertently finding the cause of #2601.

Edit: daysSince and startofDay arent causing it.  I just wrote a new function to use and the erroneous errors are still happening.  So somewhere in the code, if now is before dayStart, then something goes catastrophic.  But its only allowed to run after the daysMissed check.

**Comment by deilann** [comment]
Cole's solution was never on prod, afaik?

**Comment by markusholdings** [comment]
Really?  That would be a huge relief, actually.  I really don't want to have to chase that one down.

All right, I'll keep investigating.

**Comment by markusholdings** [comment]
All right, sorry I haven't been as active as I could be as of recently.  From what I can gather, most of the issues and bugs that arose do in fact come from the fact that Coles Solution forgot to account for logging in twice during the critical time.

@lefnire I think the solution is ready to be tested locally, just give me a little bit to get a more refined solution up and ready to go.

**Comment by deilann** [comment]
Again, markusholdings, Cole's solution has never been on the site, prod or
beta, and therefore could not be causing any of the problems.

**Comment by markusholdings** [comment]
@deilann According to #2328, it was pushed and tested <i>somewhere</i>, which is what gave me pause in testing it to begin with.

**Comment by deilann** [comment]
It was tested on cron.habitrpg.com, not on prod or beta.

**Comment by markusholdings** [comment]
I see, that makes sense.  Still, I found a bug in his proposed solution and I fixed it through my own tests at least.  I just wanted to look through some of the issues that popped up around the same time and re factor my solution, but if it was never on prod or beta, then the data I could collect would be limited :P 

I tried to combine mine and cole's approaches but the issue kept coming back, so I had to revert to an older working one of mine.

api.daysSince = (yesterday, options = {}) ->
  o = sanitizeOptions options
  ReturnValue = Math.abs api.startOfDay(_.defaults {now:yesterday}, o).diff(o.now, 'days')
  HourCheck = moment(yesterday).zone(o.timezoneOffset)
  if HourCheck.hour() < o.dayStart and o.now.hour() >= o.dayStart then ReturnValue++
  if HourCheck.hour() < o.dayStart and o.now.hour() < o.dayStart and HourCheck.diff(o.now,'d') != 0 then ReturnValue++
  return ReturnValue

This is the solution I want to test locally.  I fixed up my commits on my fork to move just this over, but my forked habitrpg-shared repo is kinda old.

**Comment by deilann** [comment]
Totes legit, just wanna make sure that you know any bugs that are coming
from prod or beta _never_ saw Cole's solution.

iirc, with Cole's solution cron _never_ happened!

**Comment by markusholdings** [comment]
Honestly I was a little confused about that so thanks for clearing that up!

**Comment by deilann** [comment]
np! I'm just so happy that you're working on this (waaaay out of my league)
and want you to have ALL the info you need!

**Comment by markusholdings** [comment]
Oh hey, sorry I've been gone for so long, things came up, but I'm back!

@lefnire yeah this is the solution I wanna test locally, but I'm having trouble doing it on my machine.  It should work okay though.  Any advice on how to proceed?

**Comment by Alys** [comment]
I'm closing this since it's old and the cron / daysMissed code has been changed a lot recently, but feel free to keep proposing changes if you wish!
