### ISSUE TITLE
API for character image?

### ISSUE THREAD

**Issue by lisbakke** [HabitRPG/habitica#3445]
Sorry to be posting this as an issue -- I couldn't find a better place to get this information.

I'm wondering if there is an API call to get an image of your character? I couldn't find an API call here https://habitrpg.com/static/api

Thanks.

**Comment by thepeopleseason** [comment]
Not at the moment. You can, potentially, cobble together the images from an individual user's output, but that would require the API Token of the given user. @deilann and I are pushing for expanded permissions options with API Tokens (including multiple tokens and manual expiration), and with that functionality, I think we could craft a read-only API result for the user objects which would eliminate any sensitive information. That would, however, require a lot of things to be developed.

**Comment by lisbakke** [comment]
Thanks for the quick response. How's the iOS mobile app doing it? Is it just one giant web view?

**Comment by thepeopleseason** [comment]
I think so, as far as I know.

**Comment by lefnire** [comment]
This is a goal of ours. Mobile uses much of the same code base as Web, so
that answers that. Alys has a 3rd party php script you can run on your own
server to render your character (like in a WordPress widget or such), I
want to convince her to bring that to the API native. Don't have the link
handy, check the wikia. But yeah, well add it eventually

**Comment by Alys** [comment]
This is the php script lefnire mentioned: https://pipcorona.github.io/HabitRPG-widget/
It's not mine though. :)

**Comment by lefnire** [comment]
Woops! :/

**Comment by lisbakke** [comment]
Thanks a lot for the help. I'll look into that script.
