### ISSUE TITLE
TypeError: Cannot set property 'translations' of undefined when runing npm start with vagrant installation

### ISSUE THREAD

**Issue by olssonr** [HabitRPG/habitica#3446]
I followed the instructions found here: http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Vagrant

When I first ran npm start (step 6) I got the known "failed to locate @import file" error and followed the troubleshooting guide and updated bower: http://habitrpg.wikia.com/wiki/Installation_troubleshooting

When I start npm this time I get:

/vagrant/src/i18n.js:89
shared.i18n.translations = translations;
                         ^
TypeError: Cannot set property 'translations' of undefined
    at Object.<anonymous> (/vagrant/src/i18n.js:89:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/vagrant/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/src/server.js:31:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

If I remove line 89 i i18n.js the application starts without error but I get some other error printed out in the browser when visiting the page.

Is this a new bug or am I doing something wrong when I am setting up habitrpg locally?

**Comment by Alys** [comment]
I've seen this reported elsewhere (in a private location so I can't link to it), and Tyler's suggestion was: "Make sure you have habitrpg-shared updated. If it's an npm link, then you'll want to go in there and git pull. If not, run npm update"

The OP then asked: "I’ve never properly understood where it gets habitrpg-shared from. I guess it’s using the github link in package.json? Since I have HabitRPG/habit-shared cloned to my computer, I’d like to use that so that I can work on both at once. Is that possible?﻿"

To which Tyler replied: "Like this: https://gist.github.com/lefnire/306df0bbf03e9c4f5129﻿"

Hope that helps. :)

**Comment by olssonr** [comment]
Thanks for the help :)

The link seems broken, or the gists was deleted.

I have the HabitRPG/habitrpg cloned, it has no sub modules as far as I can see. I ran npm update and it completed with an error

npm http GET https://registry.npmjs.org/amdefine

> canvas@1.1.3 install /vagrant/node_modules/habitrpg-shared/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/node_modules/habitrpg-shared/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/amdefine

When I ran npm start again I still got the translation TypeError

I also tried npm install and bower install and bower update, but with no luck.

**Comment by olssonr** [comment]
Alright, so I have made some further investigation and some progress. I tried clean the bower and npm caches without luck.

When looking in the habitrpg-shared folder in node_modules I can see that it does not have the latest code on github develop. When I look into the bower and npm log I now see that it checks out master and the sha for the commit is the same as latest on master.

I added #develop in package.json in the habitrpg-shared and did the same in the bower.json e.g. "habitrpg-shared": "git://github.com/HabitRPG/habitrpg-shared#develop",

Then I ran npm install again, and now it works! After logging in I noticed that the checklist in exercise (I created an account and logged in, exercise is on of the default dailies) looks funny: function (lang) {      if (vars == null) {        vars = lang;      }      return i18n.t(string, vars, lang);    }. I guess it should have said something else...

Anyway, I assume it is not supposed to work like this. Could this be a new bug or am I doing something wrong?

**Comment by olssonr** [comment]
Btw, do you think I should add this to the troubleshooting guide? http://habitrpg.wikia.com/wiki/Installation_troubleshooting

**Comment by deilann** [comment]
Feel free to add it to the troubleshooting guide! Wikis are easy to edit.

**Comment by olssonr** [comment]
Added instructions how to fix this problem under the trouble shooting wiki page: http://habitrpg.wikia.com/wiki/Installation_troubleshooting#Investigate_if_your_habitrpg-shared_was_taken_from_master_instead_of_develop

**Comment by olssonr** [comment]
I was just about to add a pull request, but noticed it was already fixed: https://github.com/HabitRPG/habitrpg/commit/f29eaab7190d07ab4c37da87644d430984b083b4
