### ISSUE TITLE
Separate kickstarter for improved server for free service.

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#345]
The current kickstarter is for additional development. How about another kicksterter, seperately, to finance sufficient server capacity to run the current free service more effectively for the current user base? I certainly would donate a second time to have the current service up and running reliably.

**Comment by lefnire** [comment]
that's part of this kickstarter. They don't allow things like that, so I had to come up with a discrete deliverable (the mobile app). The first place the funds will go is hiring a buddy who will help setup a testing harness and fix the major bugs.

**Comment by StanLindsey** [comment]
It is stated on the page that the first purpose of the Kickstarter is website bugfixing which is predominantly stability. (Which actually is actually mostly solved, its just that the recent fix broke other things, but these are much less serious)
![funds](https://f.cloud.github.com/assets/3317882/140775/5ba8d624-722d-11e2-9c34-322f58ed3ca8.jpg)

Don't worry, we aren't going to leave the website and simply run off with the phone app =P

Edit: Damn, @lefnire got there first.

**Comment by killroy42** [comment]
Hehe, I never expected that ;) But I like the app and use it. When it's down it slows me down. I'm more concerned about beefing up the server. If it's something simple to do, perhaps you can set up a donation link. I'm just concerned that if the kickstarter doesn't work out, the current online service might not be supportable by you.

**Comment by lefnire** [comment]
Not the server, its the memory leaks and bugs in the framework we're using. We'll get that Kickstarter :) That's the best place to donate, because if it tips we can use all that's currently in that pot to hire help. If not, we have to start over.

**Comment by killroy42** [comment]
I'm racing to catch up on my modern web tech... then I can help fix those things as well ;)

**Comment by lefnire** [comment]
You would be most welcomed my friend!
