### ISSUE TITLE
Purchased quest, no scroll

### ISSUE THREAD

**Issue by neverasuspect** [HabitRPG/habitica#3452]
Hi, I just bought the Hedgebeast quest. Gems are gone but the scroll hasn't shown up.
Any help would be appreciated!
User ID 0309ae9c-d809-4506-8a09-0b8848233171

**Comment by deilann** [comment]
The good news is just just wrote a fix that should keep this from happening! You probably managed to get a negative number of scrolls, so purchasing the scroll gave you a slightly less negative or zero number of scrolls.

I'm gonna refund you the four gems. Do go ahead and try to repurchase.

**Comment by neverasuspect** [comment]
Totally worked! Thanks so much ;D

**Comment by deilann** [comment]
Yay!
