### ISSUE TITLE
To-Do items don't stay in the order I put them.

### ISSUE THREAD

**Issue by MercuryChaos** [HabitRPG/habitica#3454]
I want to sort my to-do list by due date, but every time I refresh the page they're back in the order they were before. I don't see that there's any setting I have selected that would make them sort in a particular order automatically.

**Comment by deilann** [comment]
Check out this ticket: #2606 

Previously, clearing completed To-Dos would fix this, but it looks like a recent code change has mucked it up a bit. Hopefully the work-around will at least exist again soon!
