### ISSUE TITLE
User interface visuals not appearing correctly

### ISSUE THREAD

**Issue by mumblesauce** [HabitRPG/habitica#3455]
The app appears drastically different on my phone, using iOS 7.1, than the screenshot shown on the app store-- not a very pretty sight. There are few images, only rudimentary text and icons. Sometimes, the phone's time/battery/etc turns white and is unreadable. The swipe function is also quite difficult to activate.

I downloaded the app a few days ago. Is this a bug only on my phone, and if so, is it fixable?

Screenshots are below.

![photo](https://cloud.githubusercontent.com/assets/7561618/2949154/887abd42-da0b-11e3-91f7-36856f0ceeb9.PNG)

![image](https://cloud.githubusercontent.com/assets/7561618/2949047/f7d4de40-da09-11e3-98b6-4c456f02fdbd.png)

**Comment by lefnire** [comment]
I'm hearing a few things:
1. iOS StatusBar is obscured? (we'll work on a fix for that, it's a very common pitfall of hybrid apps, and Ionic is tackling it head-on)
2. The game's sprites are fuzzy. Follow progress there at https://github.com/HabitRPG/habitrpg-mobile/issues/201

Is there anything I'm missing?

**Comment by ckygel** [comment]
Hi, having another UI problem here (using iOS 8.2). When I am editing the tasks to set it to certain days (every Monday, Wednesday, Friday), I cannot set custom settings for Saturday and Sunday so I need to go on website and edit it there.

**Comment by Alys** [comment]
@ckylee : This sounds like a very different problem than the one @mumblesauce reported. Could you please log it as a separate issue? You can do that by [going to this page](https://github.com/HabitRPG/habitrpg-mobile/issues) and clicking on the green "New Issue" button.

**Comment by negue** [comment]
ping @huaruiwu

**Comment by crookedneighbor** [comment]
The old app is no longer supported. Please try out the new https://itunes.apple.com/us/app/habitica/id994882113?mt=8
