### ISSUE TITLE
Challenge Habits editable through API

### ISSUE THREAD

**Issue by malexmave** [HabitRPG/habitica#3457]
Hey,

I'm pretty new to HabitRPG, but I understand that habits / dailies that are part of a challenge are supposed to be un-editable. At least I can't change the days of the dailies using my webbrowser.

However, if I use the ChallengeRPG Android client (Habit AndroRPG), I can edit the active days for dailies, and it even shows up in the webUI, still as a part of the challenge, but with the changed days.

![screenshot from 2014-05-13 09 55 17](https://cloud.githubusercontent.com/assets/1688580/2954542/0639de26-da74-11e3-9b0c-1f9bda960080.png)

Is this supposed to work this way, or is this a bug?

Malexmave
##

**Comment by lefnire** [comment]
Not intended, thanks for the report!

**Comment by deilann** [comment]
This allows for editing on mobile as well.

**Comment by phillipthelen** [comment]
Is anybody currently working on this? Otherwise I'll take a look at it.

I suppose the only way to fix this, would to retrieve the challenge from the database and check if the user is the challenge author, when the task is tried to be edited. right?

**Comment by crookedneighbor** [comment]
@vIiRuS Challenges should only be edited through the [challenges routes](https://habitrpg.com/static/api#!/challenges/challenges_cid_POST) and there should already be checks there to see if the user is the creator of the challenge. 

In the [PUT call for tasks](https://habitrpg.com/static/api#!/user/user_tasks_id_PUT), we need to check if task is a challenge and prevent updating certain parameters. 

List of parameters that are okay to change (according to UI):
- notes
- daily streak counter
- Attributes (for stat allocation)
- tags
- checklists

**Comment by Alys** [comment]
@crookedneighbor @paglias This might be something to consider for API v3, if it's not already on the list.

**Comment by paglias** [comment]
it's on the list!

2015-11-15 11:45 GMT+01:00 Alys notifications@github.com:

> @crookedneighbor https://github.com/crookedneighbor @paglias
> https://github.com/paglias This might be something to consider for API
> v3, if it's not already on the list.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3457#issuecomment-156801258.

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
Fixed in v3
