### ISSUE TITLE
Coin image messed up when browser is made smaller

### ISSUE THREAD

**Issue by Chaoticjam** [HabitRPG/habitica#346]
Nothing big, just what i put in the title. The coin image moves to the next line like a word would but it makes it look silly.
![coins](https://f.cloud.github.com/assets/3515189/141203/1c38e75c-723e-11e2-9879-2ceefbcbf64e.jpg)

**Comment by lefnire** [comment]
Check it out [on the test server](http://habitrpg.herokuapp.com/) and tell me how it looks on your browser

**Comment by StanLindsey** [comment]
![gold](https://f.cloud.github.com/assets/3317882/141251/3dfef55e-7241-11e2-9438-57c2743f81f5.jpg)

Before & after some CSS tweaks. I'll put a request in in a moment. Can we use @media for bootstrap in index.styl?

**Comment by StanLindsey** [comment]
When with this in the end; Its not the best CSS but I couldn't see where the <table> tags were coming from  (I guess during injection into the html) otherwise I'd of had a different approach. It works from large to smallest pixel width. 

![goldolo](https://f.cloud.github.com/assets/3317882/141332/f5df6b56-7244-11e2-9688-90f49a7e4334.jpg)

**Comment by Chaoticjam** [comment]
Yeah mine looked like Slappybag's first image, better but running into the image. 
![coins2](https://f.cloud.github.com/assets/3515189/141375/942df024-7246-11e2-8507-c87edb8b09f2.jpg)
Also saw the 'remaining' button started to move into the title if that matters

**Comment by lefnire** [comment]
@SlappyBag rockin a female orc

**Comment by horusofoz** [comment]
This appears to be fixed. @switz Can you confirm your code resolved this?

**Comment by switz** [comment]
I didn't write any code. @SlappyBag did.

**Comment by horusofoz** [comment]
My bad. @SlappyBag Can you confirm this is resolved?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
