### ISSUE TITLE
Quest scroll purchased but not showing in my inventory

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#3460]
I purchased Spirit of Spring yesterday.  My account was debited 4 gems, but the scroll does not show in my inventory.  I gave it a day to show up and it has not.

**Comment by deilann** [comment]
This is a known bug and a fix is on the way. There's an open ticket for it,
but I'm on mobile so I can't find it. Can you search for it? Try scroll
glitch or scroll bug. Closed tickets will point you to the right ticket as
well. Post your user id in that ticket and I'll fix you up.

**Comment by Memry** [comment]
Found it.  Posting on there.  Thanks!
