### ISSUE TITLE
Problem while displaying Boss damages

### ISSUE THREAD

**Issue by Aiseant** [HabitRPG/habitica#3461]
Hello there,

My party and I recently started a Gryphon Quest again, and this is what we get at my cron :

aiseant attacks Fiery Gryphon for 14.1 damage, function (lang) { if (vars == null) { vars = lang; } return i18n.t(string, vars, lang); } attacks party for 1.5 damage

This doesn't happens with other members of the party, only me ...

Regards

Aiseant

**Comment by deilann** [comment]
Aiseant, are you on beta?

**Comment by lefnire** [comment]
Yeah, I'm still getting this on the develop branch @paglias 

```
Tyler Renelle attacks Rat King for 4.3 damage, function (lang) { if (vars == null) { vars = lang; } return i18n.t(string, vars, lang); } attacks party for 0.0 damage.
```

What's the easiest way to hunt these down?

**Comment by paglias** [comment]
@lefnire fixed, let me know if there are others
