### ISSUE TITLE
orphaned reward

### ISSUE THREAD

**Issue by inksplotched** [HabitRPG/habitica#3462]
I participated in a challenge re: doing your taxes earlier in the year. The challenge has ended and has (apparently) been deleted, but one of the rewards remains in the column to the far right. I would like to remove it but do not know how - I can't leave the challenge since it no longer exists.

User ID: 46c6a593-38ef-4996-923b-fa925929f1fa
![rewards](https://cloud.githubusercontent.com/assets/6390851/2972946/eb0b6c54-db78-11e3-9939-83fc4257a1dd.PNG)

**Comment by deilann** [comment]
Go to your completed To-do and remove it from that task.

**Comment by inksplotched** [comment]
I'm not sure what this means?

**Comment by deilann** [comment]
Go to your completed to dos. Find the to do for completing your taxes. The
bull horn should be broken. Click it. It will ask if you want to remove the
tasks.

If the bull horn is not broken, uncheck and recheck the to do. That should
have it register as broken.

**Comment by inksplotched** [comment]
unchecking it removed the completed to-do. the reward is still there and the bullhorn is not broken.

**Comment by deilann** [comment]
Unchecking it moved it back to incomplete. You'll have to go back to your
incomplete To-dos to re check it.

**Comment by inksplotched** [comment]
thank you

**Comment by deilann** [comment]
I wonder if I can close issues via email.

Close #3462

thank you

—
Reply to this email directly or view it on
GitHubhttps://github.com/HabitRPG/habitrpg/issues/3462#issuecomment-43096289
.

**Comment by paglias** [comment]
@deilann something yet to be added :)

**Comment by deilann** [comment]
Right after I log in on mobile:P

Thanks Matteo

**Comment by djstinkay** [comment]
FYI for anyone else who's been getting progressively more frustrated on this: It doesn't work in a browser (or at least in Chrome). In order to delete the task and the reward, I had to do it from my mobile app.

**Comment by Alys** [comment]
@djstinkay and others, see [Challenges : Deleting a Challenge Task](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) on the wiki for other things that you can try.
