### ISSUE TITLE
XP above Lv. 100 keeps reverting to 0

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3463]
I'm at Level 100, and have been for a while. When the Bailey update went through, I was pleased to see that my total XP returned to 0/3640. I checked off some tasks, and sure enough, I earned 30 XP!

And then five minutes later, it announced "-30 XP" and reverted me back to zero. My tasks remained checked.

I checked some more, and got myself to 75 XP... and five minutes later, it had reverted to 0 again, with all my tasks still checked. Have manually fixed my character value - will keep you posted.

@lefnire @deilann

**Comment by lefnire** [comment]
we had to revert the recent push due to some i18n+registration issues. likely not a bug, but you hit it during the rollback. try now
