### ISSUE TITLE
Dailies reseted without a reason

### ISSUE THREAD

**Issue by Aletraidi** [HabitRPG/habitica#3464]
![habitrpg_afterlvlup_exp_dailies](https://cloud.githubusercontent.com/assets/7584703/2976635/b83b03dc-dba2-11e3-9bc4-17cf77dfc3a9.png)
Hi,

today I was checking the dailies I had done and got the exp and all. Few moments later I refreshed the page (can't remember anymore if I visited party or market or anything) and the checked boxes were empty. I got to keep the experience points and apparently all the loot (fe. white hatching potion).
The problem is that now I have to either lose health from "missed" dailies or "cheat" myself some double exp. to prevent that since I already did all those things.
I can not describe it in more detail because it didn't give any error messages or stuff like that, the check boxes just disappeared.

~ Aidi

Edit: After I completed another daily  I leveled up but the dailies still claim not to be completed. Also the experience bar is full but says it has -3 exp. I have attached a screenshot of this. No error messages again.

**Comment by Alys** [comment]
@Aletraidi I'm so sorry we never replied to you to help you with this! It looks like it was a sync error, where some of the data wasn't sent from your browser to the server. If it happens again, you can use Settings -> Site -> [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to remove XP and GP, and you can, if you wish to, sell any drops you feel you shouldn't have gained.
