### ISSUE TITLE
Egg Hunt Quest Won't Complete

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3468]
I posted this as a comment in Issue #2507, but I couldn't tell if that issue was still open.  My party was doing the Egg Hunt quest, and it appears that the quest is complete, because we have all received the 10-egg reward.  However, the quest is still open in our Party window, and I cannot open a new quest because the game still thinks that the Egg Hunt quest is open.  I think that my eggs would have finished the quest, because the eggs that I found never showed up in the Party Chat window.  I asked for suggestions at the Tavern, and logging out and back in (using two different browsers) did not do the trick.  Is this a known bug?

**Comment by tjwds** [comment]
Do you know if all of your party members have logged on to get the "received rewards" prompt yet?

**Comment by ghost** [comment]
Two party members participating in the quest may not have logged on in the past two days.  Could that be causing the problem?

**Comment by tjwds** [comment]
Yep, that's the most likely cause.  Once all the party members clear the quest, you'll be able to prompt them for a new one.

**Comment by deilann** [comment]
Can you please post your User ID and your Group ID?

**Comment by deilann** [comment]
I've never needed party members to log on in order to trigger the end of
the quest. Even if that were the case, the correct amount of eggs should
show up.

Nadso, are you the quest leader?

**Comment by ghost** [comment]
I'm not the quest leader, but his eggs were recorded yesterday when we received the rewards.  
User ID: 8e41080c-c79b-4290-b52a-f2c6bbac6aae
Group ID: 8a45680e-ca27-4e08-94c4-b994534727e9

**Comment by deilann** [comment]
Can you ask the quest leader if he can try to abort the quest?

**Comment by ghost** [comment]
I've asked him, but he's out of town, so he may not be able to right away.  I'll post here once he does.

**Comment by ghost** [comment]
He aborted it.  It worked!  Thanks for your help.
