### ISSUE TITLE
Login in diferents devices makes me loss great amount of HP

### ISSUE THREAD

**Issue by oriberu** [HabitRPG/habitica#3469]
I usually play habit rpg on my deskpot computer, but also when at university i login in at my laptoc.
The problem is, when i login from one of them, and, at any moment, login with the other, the game "thinks" its a new day and hit me making me lose great amounts of HP when its still no the day.
It seems to be a regular thing since its not the first time that occured to me. Last time, today. I do all my dailys yersterday and do one this morning at home, when i was at uni, i login on my laptoc and hit me for more than 20hp. 
So, i dont know if its something im doing wrong, or just a "bug". 
Thanks for reading it.
Oriberu.

**Comment by tjwds** [comment]
Do the computers that you use have the same date and time?

**Comment by oriberu** [comment]
Yes both of them have the same date and by time i assume is hour and minutes so also same for both.

**Comment by Alys** [comment]
oriberu, do you click on a lot of negative habits? In particular, on the day recently when you logged in on your laptop and you lost more than 20hp, had you previously on your desktop computer hit the minus "-" button on habits often enough to lose about 20hp?

If so, the health loss on your laptop wasn't an additional loss, it was just your laptop syncing with HabitRPG's server and catching up to the latest updates. 

Tell us if I have not explained this clearly enough, and especially tell us if you do not click on negative habits that often!

**Comment by oriberu** [comment]
Not really, i dont hit minus so often. This time in particular i had full hp, didnt hit once on minus button on that day. 

When i use the laptop i see the game like the last time i see in my computer but after a few minutes it resets and hit me for all dailys that i dindt complete, Like the day change occurs in the moment i use the another device (laptop-computer or computer-laptop)

**Comment by crookedneighbor** [comment]
The site has gone through many revisions since this was opened, so I'm closing this. If you're still having issues, please reopen it.
