### ISSUE TITLE
Class Selection State Error

### ISSUE THREAD

**Issue by urandom2** [HabitRPG/habitica#3472]
After achieving level 10 on my mobile device{Android device running 4.2, accessed on Mozilla Fennec, not Android app}, I was prompted to select a class. After deciding that I wanted more information, I went and accessed the root habitrpg.com URL on my laptop{this time Mozilla Firefox}. This prompted me again to select a class. After some consideration, I chose Mage. Now ~24h later, I went and accessed the mobile client {Fennec again} and it prompted me to reselect a class. After trying to click on the background to get the notification to go away, I tried to select Mage again; unfortunately I selected Rogue and this change was made. Since I already made the binding choice to become a Mage I should not have been able to override this with an old cached version. This could also be used to circumvent the permanence of the class system, allowing for class changes at any point.

**Comment by crookedneighbor** [comment]
I don't believe this is an issue anymore. Sorry it took so long to respond.
