### ISSUE TITLE
Daily damage not showing up, then stacking?

### ISSUE THREAD

**Issue by Kiwoa** [HabitRPG/habitica#3473]
Recently, my entire party died during a boss battle because we all took 88.2 damage at once. When I looked at the cause, it seems like the damage from one of my party members didn't show up for four days, then on the fifth, a huge amount hit all at once. Is there any way to prevent that from happening? I could maybe handle healing the group for 88 damage over the course of five days, but all at once is impossible!

User ID: 4b4b4070-d55e-4415-aa24-c3e9f1469480
Group ID: e155e5e1-f8a2-47c9-af6d-82e162a2dd32

The damage (from pyrodynamo) in question:
![screen shot 2014-05-16 at 7 30 29 am](https://cloud.githubusercontent.com/assets/7602292/2996437/fd926cf2-dcee-11e3-9afd-09522c7d722f.png)

The last time pyrodynamo's damage showed up before the huge hit:
![screen shot 2014-05-16 at 7 31 28 am](https://cloud.githubusercontent.com/assets/7602292/2996440/071fa19a-dcef-11e3-8788-d0cef39b001d.png)

**Comment by deilann** [comment]
That's expected. If they didn't log in for five days (which would be why
their damage didn't show up), they missed five days worth of dailies, so
you got five days worth of damage.

The best way to prevent this is to have your party members log in every
day. If they are unable to do that, they should either not participate in
the quest or they should rest in the inn.

**Comment by Kiwoa** [comment]
Man, that's unfortunate. I wish it would just deal the damage every day, regardless of whether they've logged in or not. :/ It makes sense, though! Thank you for the explanation!

**Comment by deilann** [comment]
Cron would have to move server-side for that to happen, which is desired, but a _lot_ of work.

And no problem! I hope you get things sorted out with your party-mate.
