### ISSUE TITLE
Public Guilds Page Width is 125% in Firefox

### ISSUE THREAD

**Issue by oleg-sh** [HabitRPG/habitica#3475]
While in Chrome the list of public guilds is moved down (it probably wasn't intended too) in Firefox the page is wider than the screen so you have to scroll (horizontal scrollbar) to the right to see the Join button.
The horizontal scrollbar only appears if the browser window is wider than 1000px.

Here is the fix I suggest. Change this code: 

.table {
    width: 100%;
    margin-bottom: 20px;
}

to 

.table {
    width: 75%;
    margin-bottom: 20px;
}

That fixes it for both FF and Chrome.
Unfortunately, I couldn't find the code in habitrpg or habitrpg-shared repos with 'grep'. Where should I look for it?

**Comment by oleg-sh** [comment]
Firefox screen shot:
![guilds](https://cloud.githubusercontent.com/assets/1823612/3000663/b25bcf34-dd26-11e3-856c-fd25910b21ad.png)

Page URL:
https://habitrpg.com/#/options/groups/guilds/public

**Comment by oleg-sh** [comment]
Ok, I think I know where the code comes from... 
I can't figure out what .styl file should the override be placed in.

**Comment by rcichy** [comment]
Fixed. Screenshots here: https://github.com/yafinee/habitrpg/commit/59da439595adc59f94442550d1577262888d7e50#commitcomment-6768654
