### ISSUE TITLE
Missing scripts at build time

### ISSUE THREAD

**Issue by ssdg** [HabitRPG/habitica#3476]
I installed habitrpg on my own instance (debian server and firefox browser) and it worked (except for challenges.) until recently.

I pulled the most recent code from develop and got a 404 on infinite-scroll.min.js (sorry if the name is not exact, I can't reproduce it)

I removed all git ignored files (except for my config that I compared to the exemple) and built again. Now, I get this error at compile time:

```
Running "stylus:build" (stylus) task
>> Error: public/css/index.styl:6
>>     2| //@import "nib/vendor"
>>     3| 
>>     4| // Vendor Includes - include first so we can override
>>     5| // Import only styles that do not have urls to images! Include them directly in the page!
>>  >  6| @import "../bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css"
>>     7| @import "../bower_components/angular-loading-bar/build/loading-bar.css"
>>     8| @import "../bower_components/js-emoji/emoji.css"
>>     9| @import "../bower_components/select2/select2.css"
>> 
>> failed to locate @import file ../bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css
Warning: Stylus failed to compile. Use --force to continue.

Aborted due to warnings.
```

I hope I gave you enough information and that it will still be possible to host my own instance that easily.

PS: Thank you, habitRPG is great.

**Comment by paglias** [comment]
@ssdg try deleting /node_modules and /public/bower_components and running `npm install` once again

**Comment by ssdg** [comment]
Just tried this, 
rm -R ~/.npm/ ~/.node-gyp/ habitrpg/node_modules 
I do not have a bower_components directory in /public
I have the same message in grunt run:dev (might have been wrong about the message source in my original post)

**Comment by deilann** [comment]
DId you make sure to run run bower install?

**Comment by ssdg** [comment]
I ran npm install -g grunt-cli bower
but If I'm not sure it's the same command, the effects are the same when I run grunt run:dev

**Comment by deilann** [comment]
Because npm install has to be run sudo, but bower throws an error when run
sudo, you need to also run "bower install"

**Comment by ssdg** [comment]
Ok, now it works. thank you all for your help.

Is there a "silver bullet" way to pull the code and relaunch habitrpg?

I believe I can close this bug. Thank you again.
