### ISSUE TITLE
No "Contact Us" at Bottom of the Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3477]
At the bottom of the Main Page, there should be a "Contact Us" section that leads to a page that says something akin to the following, or which has links akin to the following.

CONTACT US

Report Account Problems: admin@habitrpg.com
Report a Bug: Github.
Report Community Issues: leslie@habitrpg.com [In the future I want to make a separate "community@habitrpg account that multiple people can monitor but it hasn't happened yet.]
General Questions about the Site: Newbies Guild
Business Inquiries: vicky@habitrpg.com
Merchandise Inquiries: store@habitrpg.com
Marketing/Social Media Inquiries: leslie@habitrpg.com

**Comment by ebiagogo** [comment]
I found a line in 'views/static/layout.jade' linking to a contact page which is currently commented out. I have the fix done locally with this line uncommented. This issue mentions only a link at the bottom of the page so I'm wondering if I should keep the layout link active or not. Also, are there any translations I need to include in the changes? Apologies if this is discussed in project documentation, I'll have a look around for related topics.

**Comment by lemoness** [comment]
It would be nice to have a "contact us", actually. Maybe directing to me or
to admin, or ideally to a page that gives a breakdown of different emails
for different situations (including directions to Trello and Github).
@lefnire @veeeeee Thoughts?

**Comment by ebiagogo** [comment]
Locally, I have the link at the bottom that leads to a new 'Contact Us' page that I created with content just as described in the original text for this issue (with all the details/links filled out). When working on the changes I noticed that there was a link to the contact page in layout.jade that was commented out. I was just wondering if I should uncomment it there too so it displays in the top set of menu items (along with Features, Videos, Blog and Group Plans). It was stubbed out like that so I figured someone wanted to have it there too. It doesn't look out of place there. I can just commit it like that and the decision can be made when reviewing my pull request. Apologies if I'm making this more difficult than it needs to be. I just don't want presume too much.

**Comment by lefnire** [comment]
Fixed by @ebiagogo

**Comment by beffymaroo** [comment]
Something to consider changing (?): The admin email address currently listed on the "Contact Us" page just says "admin@gmail.com."

(UUID: 9fe7183a-4b79-4c15-9629-a1aee3873390)

**Comment by ebiagogo** [comment]
Somewhat fortunately the actual mailto has the correct address (admin@habitrpg.com) and it's just the displayed text that is incorrect. I'll get this updated later this afternoon. Thanks...
