### ISSUE TITLE
User Profile Look-up From Hall

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3478]
I need a quick and easy way that I can look up a user's profile with their UUID, ideally in the Hall, so that I can verify claims of offensive content in profiles.This is pretty important. I shouldn't have to bother @lefnire with it.

**Comment by lefnire** [comment]
@lemoness click name -> profile, now at https://habitrpg.com/#/options/groups/hall/heroes

**Comment by lemoness** [comment]
But he's not a contributor, so his name isn't actually listed in the hall

**Comment by lefnire** [comment]
Enter an arbitrary UUID in the "Reward User" box, click the name. [Screenshot](https://www.evernote.com/shard/s17/sh/88900db9-d90b-40d0-adba-a0de7db47af9/0742635942776d8d399329e3688660fd)

**Comment by lemoness** [comment]
YOU ARE THE BEST
