### ISSUE TITLE
Drop Reward Announcements in Spanish

### ISSUE THREAD

**Issue by Cosicant** [HabitRPG/habitica#3479]
I play on google chrome, I have HabitRPG set to to English, but for some reason some of the drop notifications I get are in Spanish (the drop for pink cotton candy {food item} and tiger egg) while others are in English. I looked around my account and setting and everything seems to be in English, but the drops descriptions in Spanish if translation code is overlapping with the original code.

**Comment by paglias** [comment]
@Cosicant sorry for that, we're having some problems with translations

**Comment by konoyo** [comment]
Same here, just the item name was in Russian. http://i61.tinypic.com/sdmvk8.png

**Comment by Alys** [comment]
This was fixed.
