### ISSUE TITLE
Dynamic Cost Rewards

### ISSUE THREAD

**Issue by mattrozak** [HabitRPG/habitica#348]
Suggestion:  The user can set rewards to cost more or less during certain time periods.  Right now I make rewards for weekdays and duplicate the same rewards for weekends that are half-price.  For example, a "Watch a Movie" reward for me would cost 15 gold from Sunday Noon to Friday at 5PM, and cost 8 gold from Friday 5PM to Sunday Noon.  It would be nifty to have this done automatically once it's set.

**Comment by Pandoro** [comment]
I just made duplicates for this, but yes definitely something I would like
to see as well in the future :-)

**Comment by wc8** [comment]
I like that idea!

**Comment by StanLindsey** [comment]
[Trello 151](https://trello.com/card/dynamic-reward-cost/50e5d3684fe3a7266b0036d6/151)
