### ISSUE TITLE
Streak Bonus not subtracted when unchecking task

### ISSUE THREAD

**Issue by emilbayes** [HabitRPG/habitica#3480]
When unchecking a task the streak bonus is not subtracted. This means I can earn free sliver by continuously checking/unchecking a daily.

**Comment by deilann** [comment]
See: https://github.com/HabitRPG/habitrpg/issues/964

This isn't really a concern. There are much easier ways to get "free silver" than checking an unchecking dailies, such as Fix Character Values or infinitely clicking a + Habit.
