### ISSUE TITLE
Completed Quest and Did Not Get Pet

### ISSUE THREAD

**Issue by yuukai8** [HabitRPG/habitica#3490]
My user ID: 38101026-d3a1-4602-8038-45b507694bd2
Browser: Google Chrome

My party member and I completed the Egg Hunt Quest and she received the golden egg pet while I did not. Quest Pet's paw markers were revealed to me, but it does not show me having one!

**Comment by deilann** [comment]
You don't get the pets -- you get eggs that you can hatch into pets.
