### ISSUE TITLE
Mobile site: Emojis appearing randomly over status bars and tasks

### ISSUE THREAD

**Issue by LB7979** [HabitRPG/habitica#3491]
Mobile site on Safari on Ios 7.1.1 seems to display emojis that don't seem to belong there, over status bars and Tasks.
- HP bar has a woman's face emoji
- XP bar has a shirt and a football emoji
- Mana bar has an Iphone(?) emoji

Also, Mana bar is white while my Mana is 100% (39/39), so it should be all blue instead of white.
## Tasks also display emojis instead of the 'Edit' 'Delete' and 'Progress' icons - a question mark and that football again.

Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/2226697-mobile-site-emojis-appearing-randomly-over-status-bars-and-tasks?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by LB7979** [comment]
I'm also not sure about the icons in the upper row (under the browser address bar) here - the kissing couple seems to be for Notifications? And the fish for Settings? Is it meant to be like that or is that a display glitch too?

**Comment by deilann** [comment]
Definitely a display glitch.

Safari on iOS has not been Habit's friend in the past. Thanks for the
report!

**Comment by negue** [comment]
@LB7979 Is the Issue still present?

**Comment by lemoness** [comment]
Closing due to lack of response - let me know if you need me to open this again!
