### ISSUE TITLE
Tasks not displaying in Chrome

### ISSUE THREAD

**Issue by renduh** [HabitRPG/habitica#3492]
As of yesterday I can no longer view any of my habit lists in Google Chrome. Everything else on the site is viewable but all of my habits have gone missing. If I add a new habit, it shows up.

However, everything looks fine with habits displayed in Firefox. 

I also noticed that just before this error occurred, a horizontal scroll bar appeared on the site that scrolls just a pixel or two, not sure if these two are related. 

My user id is 56462f6a-4202-4ae8-a1a2-f58c3e69e49c

Thanks

**Comment by deilann** [comment]
If you go to your tags and press the "clear" button, what happens?

**Comment by renduh** [comment]
Well, don't I feel stupid. That has fixed it. Thank you very, very much :)

**Comment by deilann** [comment]
No problem! :) It happens to the best of us.
