### ISSUE TITLE
New user tutorial/default habits in Russian? (despite language setting being English & user is in Australia

### ISSUE THREAD

**Issue by aein** [HabitRPG/habitica#3495]
I just had my Australian friend join so she could join my party. She is reporting that she is seeing Russian? although her browser/computer is set to English as well as the HabitRPG setting is set to English as well. I attached screenshots.

![10320407_10152132933726347_2679286171154871621_n 1](https://cloud.githubusercontent.com/assets/5262885/3022571/0959964e-dfcb-11e3-8491-67538ebed546.jpg)
![10353652_10152132936211347_4396600038145257195_n](https://cloud.githubusercontent.com/assets/5262885/3022572/0ca63730-dfcb-11e3-96b7-7227de05f8b3.jpg)

**Comment by Alys** [comment]
There's a known issue with the translation software at the moment. I believe a fix has been created but it hasn't gone live yet. When it is fixed, she should start seeing English everywhere, although if she hasn't deleted the default tasks, they will probably still be in Russian. She will then be able to view the tour in English by going to [Settings -> Site](https://habitrpg.com/#/options/settings/settings) and clicking on the "Show Tour" button.

**Comment by aein** [comment]
Okay thank you Alys. :) I forwarded your message to her. :+1:

**Comment by Alys** [comment]
Actually... the language issue I was thinking of (https://github.com/HabitRPG/habitrpg/issues/3466 ) seems to have been fixed already (although I thought I'd seen people more recently saying they're still getting foreign-language drops).

@lefnire and @paglias : Can you look at this one please? Is it related or a separate issue?

**Comment by paglias** [comment]
Will look at it when I'm back at home, really strange as the tour is
browser based and we never had problems with it. Really sorry guys
Il 21/mag/2014 08:06 "Alice Harris" notifications@github.com ha scritto:

**Comment by aein** [comment]
I actually did get a foreign language drop around two days ago for the panda egg-- it came in Portuguese.

**Comment by deilann** [comment]
I've seen a couple of people talk about the starter tasks being in a
foreign language in the Tavern.
