### ISSUE TITLE
Latest updates require explicit bower install on vagrant machine

### ISSUE THREAD

**Issue by thepeopleseason** [HabitRPG/habitica#3497]
Update the provisioning script to do so and test.

**Comment by thepeopleseason** [comment]
Looks like this is an intermittent issue. I've updated the documentation on the wiki to account for the potential that bower does not install correctly.

**Comment by deilann** [comment]
I'm not sure about your vagrant machine, but on *nix, the issue has always
been that if you try to install bower with sudo, it's going to fail. If you
just run "bower install" it's fine.

**Comment by thepeopleseason** [comment]
Yeah, when I tried to add it to automatically bower install from the provisioning script, it complained about being run via sudo (which it's actually being run by root).

**Comment by deilann** [comment]
Is there a way to not run it root in the script? That would fix it.

**Comment by thepeopleseason** [comment]
Yes, I can sudo -u vagrant and run it. I'll have to experiment with it.
