### ISSUE TITLE
Tasks deleting themselves

### ISSUE THREAD

**Issue by miriahofthewind** [HabitRPG/habitica#3498]
My tasks are deleting themselves when I create a new tag. I turn the tags on and off one at a time and still get nothing. :(

**Comment by deilann** [comment]
Click the clear button, that clears all tags.

**Comment by Alys** [comment]
Also note that there's a bug with tags where a tag can't be used successfully as soon as it is created. Create the tags that you want, then reload the page, and then start applying the tags to your tasks.
