### ISSUE TITLE
Re-hatched a pet (that turned into a mount) and it is not showing up.

### ISSUE THREAD

**Issue by aein** [HabitRPG/habitica#3499]
I turned a skeleton tiger into a mount yesterday. I got a skeleton hatching potion to re-hatch a new skeleton tiger which I did today. The message said successful, but the skeleton tiger cub is still greyed out and unavailable.

**Comment by deilann** [comment]
Can you do me a hard refresh, or log in and out, and tell me if you have
your egg and potion back? I imagine it just didn't get saved to the server,
and you'll be able to rehatch.

**Comment by aein** [comment]
@deilann I did refresh after it happened because I thought it was just a bug, but nothing happened. I just logged in & out and the skeleton tiger cub is still greyed out/unavailable and the potion is still gone. :(

**Comment by deilann** [comment]
Sounds like the operation got interrupted in the middle some how.

Just the potion is gone? Not the egg?

**Comment by aein** [comment]
Sorry, the egg is gone as well. (I had 3 tiger eggs, now only 2.)

**Comment by deilann** [comment]
What's your User ID?

**Comment by aein** [comment]
8da80cb2-2e9a-4eee-a6cf-9aea48146fd6

**Comment by deilann** [comment]
Sent you six gems. Please use them to repurchase the potion and the egg.
Then try to rehatch the pet. Tell me how it goes. :)

**Comment by aein** [comment]
@deilann Thank you so much! It worked this time!
