### ISSUE TITLE
Could do with keeping the tour items

### ISSUE THREAD

**Issue by thebadger412** [HabitRPG/habitica#35]
Once I had finished the tour I had forgot what the habits did.. and I had already deleted the example ones.. so I had no idea how to find out what a habit was..

could do with maybe a little ? next to habits to hover over to bring up an explanation... or maybe a way to reset to the example life from the beginning..

Also when I see the buttons I think hmm what does this do so click it.. this automatically starts taking my hp off and then I would have to reset.. just think overall usability could be improved with some hover over docs..

Overall though this is a huge help to my project and I just wanted to say thanks for releasing it and your article on the frameworks

**Comment by lefnire** [comment]
good idea, I'll add that to my list. In the meantime for users with the same issue, workaround is to open up Chrome console and run the following javascript:

``` javascript
$.cookie('tour_current_step',null);
$.cookie('tour_end',null);
```

then refresh

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Added to Trello: [Help on Mouseover](https://trello.com/c/Mv1yqQbP)

**Comment by wc8** [comment]
[Restore Samples](https://trello.com/c/3q5fHAdQ) now has its own spot on our feature tracker, those interested can follow the link to vote for it.
