### ISSUE TITLE
Habit Sorting

### ISSUE THREAD

**Issue by dapperfex** [HabitRPG/habitica#350]
Incredibly minor complaint, but is there a way to fix how everytime I refresh habitRPG my habits will re-arrange themselves?

**Comment by lefnire** [comment]
not minor, it's critical (really irking a lot of users) #212. Followup there, I'm still trying to figure it out

**Comment by lefnire** [comment]
sorry, #318

**Comment by lefnire** [comment]
fixed 5ea0dfe713efabed95e4ea4dc51ddfa5fc02d674
