### ISSUE TITLE
Password reset email not received

### ISSUE THREAD

**Issue by parthppanchal** [HabitRPG/habitica#3500]
I've been trying `Forget Password` for 3 days & still haven't received any password related mail, even though the site says `New password sent`.
My email provider is Yahoo & I had registered from the Android app, if it helps.

**Comment by deilann** [comment]
If you registered from the Android app, did you actually register with an email/password?

**Comment by parthppanchal** [comment]
To register from the Android app, I provided following details:
- Username
- Email
- Password

**Comment by deilann** [comment]
Awesome! That must have been added in with the new release

In the past, what it's been is that not all of the emails were being sent
out. Try every day still for a bit.

There's also a small chance that you typo'd your email. If you check out
this tool https://oldgods.net/habitrpg/habitrpg_user_data_display.html it
can show you the email address you signed up with. Just cover all bases.

@lefnire Before the issue had to do with the number of emails being sent
out. Do you think this is still the issue?

**Comment by parthppanchal** [comment]
I rechecked my email id and it's correct. Moreover I tried to re-register with the same email id and the site said "Email already taken".

**Comment by deilann** [comment]
kk def sounds like the problem we were having before.

keep trying. i'm really sorry this is happening. :/

You're still logged on via phone, yeah?

**Comment by parthppanchal** [comment]
Unfortunately, no.

**Comment by lefnire** [comment]
Yahoo's rejecting your email address for some reason. I'm getting the following:

```
Delivery to the following recipient failed permanently:

     prth_pa*******@yahoo.com

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain yahoo.com by mta5.am0.yahoodns.net. [63.250.192.45].

The error that the other server returned was:
554 delivery error: dd This user doesn't have a yahoo.com account (prth_pa*******@yahoo.com) [-5] - mta1569.mail.gq1.yahoo.com
```

@parthppanchal , [email me](mailto:tyler@habitrpg.com) and I'll send you the new pass

**Comment by deilann** [comment]
Thanks for looking into it, Tyler!

So glad to hear it's not the same problem as before.

**Comment by parthppanchal** [comment]
@lefnire, mail sent.

**Comment by parthppanchal** [comment]
Thanks @lefnire and @deilann.
I'm really glad by such prompt support from HabitRPG team. Keep up the great work :smiley:
