### ISSUE TITLE
End Tour button misleading/ How to restart tour?

### ISSUE THREAD

**Issue by martinklepsch** [HabitRPG/habitica#3503]
Hey! Interesting project!

When I first signed up I accidentally hit "End Tour" in the little speechbubble because it was lower right (I assumed it'd be continue.) Maybe some coloring there would do the job.

After that happened I tried to restart the tour but couldn't find anything so I had do delete my account and sign up again to get the Tour popup again.

I could probably write a patch but I guess it's a small change anyways.
Let me know what you think!

**Comment by deilann** [comment]
If you go to Settings > Site, you'll see an option to restart the tour.

**Comment by negue** [comment]
Like @deilann wrote you can restart the tour.

I'll close this issue.
