### ISSUE TITLE
Quest rewards missing

### ISSUE THREAD

**Issue by dbTunder** [HabitRPG/habitica#3505]
I didn't receive the rewards after the Spring Spirit quest
Tried to refresh the browser, waited a couple days but nothing. my Party-mates did receive them.
I was in the party before starting the quest, like all the others.

I log on from Firefox mobile, other Firefox terminals on different machines and from the habitrpg android app

cheers

**Comment by deilann** [comment]
But were you actually a quest participant? If you go back, did you ever deal damage to the boss? Did you actually accept the quest?

Your party members could have started the quest without you, meaning you would not have gotten the rewards.

**Comment by dbTunder** [comment]
Of course I was participating in the quest. We started all together and I was the one who inflicted more damage. They received the rewards and I didn't.

**Comment by deilann** [comment]
It's not quite an "of course" situation. :) I've had many people comment that they didn't get the rewards and what actually happened is that the quest was force-started without them! Gotta rule that out first.

Can you post me the following:

A screen-shot of your inventory
A screen-shot of your party chat saying that the quest completed and showing some damage from everyone
Your User ID (you can find this in settings > API) but NOT your API Token (this is like a password, do not share it publicly)
How many times you've defeated the Ghost Stag in the past (if none, that's fine)
How many times your badges says you've defeated the Ghost Stag (if at all, screen shot preferable)

**Comment by dbTunder** [comment]
Hello
suddently today the eggs appeared, so guess that the problem is solved
itself!
Nevermind, thanks!

_dbT_
_---_
 www.tundersbay.com* <- my site: personal info, PC assistance, market, good
websites*

**Comment by deilann** [comment]
Likely, then, you needed to do a hard refresh, not just a refresh. Your cache wasn't allowing you to see the eggs.

Often, a hard refresh will fix a lot of Habit issues.
