### ISSUE TITLE
Time zone changed after traveling

### ISSUE THREAD

**Issue by Keevon** [HabitRPG/habitica#3506]
My dailies seem to be resetting in the early afternoon ever since I got back from a trip to Germany from Seattle. The time difference is approximately 9 hours and I believe the reset happened around 3pm so my assumption is that habitrpg set my timezone to the new location and never reset it when I returned. Is there any way to manually set it?

**Comment by deilann** [comment]
Habit goes off of the timezone of your device. So, as long as you put your
device back to your local time zone, it should function normally going
forward.

**Comment by Keevon** [comment]
I've been back for a few days and it still did the weird reset yesterday. Also it didn't seem to reset at midnight last night.

**Comment by deilann** [comment]
Has your device changed its time zone?

If we're talking a phone, have you restarted your phone since the time zone
was changed back?

**Comment by Keevon** [comment]
I'm using habitrpg on my laptop, and yes the time zone is correct. My phone is also correct but I haven't really been using habitrpg on it that often.

**Comment by deilann** [comment]
Can you log in and log out of Habit for me, and tell me if you still get
the strange time reset? I'm wondering if we're looking at something cached.

**Comment by Keevon** [comment]
Done. I have a suspicion - my account is logged in through Facebook. I realized that my facebook still appeared to be using the wrong timezone yesterday so maybe that's related. It seems to be correct today so I will keep an eye out.

**Comment by deilann** [comment]
Oooh, that is interesting. It may not be that Facebook is still using the
wrong time zone is the issue, but that for some reason anything that's
going off your computer clock is still using the wrong time zone for some
reason.

But yes, please do let us know, one way or another, what happens.

**Comment by Keevon** [comment]
I think it's fixed now. Either logging out helped or whatever was causing the wrong time zone to be used in my browser reset itself.

Thanks!

**Comment by deilann** [comment]
Glad to hear it!
