### ISSUE TITLE
Lost Everything

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#351]
I am on my mobile checked a daily and suddenly everything disappeared, except rewards.

**Comment by lefnire** [comment]
What happens on a refresh?

**Comment by ghost** [comment]
It still happens

**Comment by lefnire** [comment]
Shoot. Email me your uuid

**Comment by lefnire** [comment]
7f754517a4dea4ae4ba30a0d427b5241785b91ba fixed this (after follow up with Wes). Incidentally, I've found with Habit nobody every loses things, it's refLists (the sort-order objects) that get corrupted somehow, or overwritten on DOM reset. A precarious phenomenon, those refLists. In any case, users' tasks are still in their document, we just have to re-associate them with a refList under certain circumstances.

**Comment by lefnire** [comment]
(btw, thanks for catching that before shit hit the fan!)
