### ISSUE TITLE
Toggling header does not adjust other UI elements until refresh

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3510]
Firefox and Chrome browsers, Windows 7, main Habit site...

If I go into Settings > Site and change the "Show Header" setting, most of the UI does not adjust to match. If I'm turning off the header, this ends up with a swath of empty space to scroll through at the top of the page. If I turn _on_ the header, the effect is more dramatically wrong-looking:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3049148/71b5d8aa-e157-11e3-8c21-89e788a38727.png)

Hard refresh fixes it, but it'd be nice for it to sort itself out smoothly upon toggle.

**Comment by nicolasjones** [comment]
Hi! This is the first time i contribute with HabitRPG.
I was watching this issue and tried to solve it. What I did was the following:

1) When Show Header is checked, Sticky Header is enabled.
2) When Show Header is not checked, Sticky Header is disabled and not checked. I think there's no reason to enable it when you don't have a header to stick.
3) When show header is checked & sticky header is checked too, when you check Show Header browser will refresh and sticky header will go off.

Is there any way I could show you or submit this solution?

**Comment by SabreCat** [comment]
@nmjones: Yes! Create a fork of the habitrpg repository, add your changes as a commit to it, then submit a pull request. Check out [the guide on the Habit wiki](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths) if you need a walkthrough.

**Comment by lefnire** [comment]
fixed in https://github.com/HabitRPG/habitrpg/pull/3623
