### ISSUE TITLE
Died because browser had out-of-date HP values

### ISSUE THREAD

**Issue by FalseLobster** [HabitRPG/habitica#3512]
Hi,

I frequently use IE11 at work (which seems buggier than chrome, in general).  This tab usually stays open from day-to-day so I can keep my Habits/Dailies up-to-date from work.

One day I left work with just 1 HP left, but managed to level up after getting home.  Coming into work the next day, I engaged in a bad Habit.  I didn't reopen HabitRPG and just hit the '-' with the existing open tab and died, even though my character had full health on the server because I leveled up at home. 

As part of dying, I lost my piece of equipment and gold :( THEN my browser pulled in the latest from the server (the level up).

Sad day.

**Comment by deilann** [comment]
That's the order of operations.

I highly suggest syncing or refreshing any time you move from device to
device.

However, you can fix this yourself -- go to Fix Character Values in
Settings > Site and put your gold and XP back, with some extra gold for the
kit.

**Comment by deilann** [comment]
Github hid this bit:

However, you can fix this yourself -- go to Fix Character Values in
Settings > Site and put your gold and XP back, with some extra gold for the
kit.

I also want to point out that while this is expected behavior, it's not necessarily desired, so please do not close this ticket. I just wanna get you fixed up ASAP. :+1:

**Comment by FalseLobster** [comment]
Thanks for pointing out that part of the Settings!  I usually do sync as you suggested, but I was a little hasty this time.  Appreciate your work :)

**Comment by Alys** [comment]
This situation is avoided now by the six-hourly refresh so  I'm closing this.
