### ISSUE TITLE
Tooltip for EXP stat bar falls behind Health bar

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3514]
Like so:

![screen shot 2014-05-22 at 7 13 13 am](https://cloud.githubusercontent.com/assets/6208739/3052996/4e166b6c-e1a2-11e3-9eb0-419898831813.png)

Also it being cramped up by party members makes the Experience text illegible.

**Comment by negue** [comment]
Can be closed. The Health / EXP / Mana Bars has been redesigned.
