### ISSUE TITLE
Question: could site name show current page name, e.g. Tasks / Tavern?

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3517]
Currently all pages show as _HabitRPG | Your Life the Role Playing Game_ (or translation). I'd like to be able to set + habit or - reward based on Firefox window name via applescript and the API. Any chance we could have the site name follow the angular routing so we could get more precise names? 

I'd like to see:
- https://habitrpg.com/static/front as (current)
- habitrpg.com/tasks  as "HabitRPG | Tasks"
- habitrpg.com/…/tavern as "HabitRPG | Tavern"
- …party as "HabitRPG | Party"
  etc.
##

**Comment by thepeopleseason** [comment]
:+1:

**Comment by crookedneighbor** [comment]
I'm :+1: on this.

**Comment by teh-maxh** [comment]
The code for this should be easy; the tricky part would be i18n. Still, even that shouldn't be hugely difficult, just tedious. I'd be willing to work on it.

**Comment by Alys** [comment]
@teh-maxh Thank you!

Note that the translations will be handled in Transifex by different translators for each language, so it won't be too tedious for them, and not at all for you. :)

**Comment by nicolevonvon** [comment]
I'd like to try work on this since it hasn't been worked on for a while.

**Comment by crookedneighbor** [comment]
Go for it.

**Comment by gauthamchandra** [comment]
If i18n is needed, then this would mean we would have to list every major route in a json file in `common/locales/en` and pull this variable from a template.

This sounds tedious and if a new route or page is added, then new text would have to be added in the json.

Unit tests should at least be added then so that the tests would fail if it hit any route where it couldn't find a matching entry in the JSON file.

**Comment by Alys** [comment]
Perhaps as a first step, we should get it working in USA English. That would give immediate benefits for many players and could be completed relatively quickly. Translations could then be added later.

**Comment by gauthamchandra** [comment]
@Alys Fair enough. So enable this feature only for `uk` and `en` locales?

@nicolevonvon Tell me if you need any help with this. This looks fairly straightforward.

**Comment by nicolevonvon** [comment]
Hi, my free time has unfortunately been taken up with work priorities the past 2 weeks. Hoping to do this tomorrow though! 
@gauthamchandra if you have a suggestion on a way to do this which will make future translation easier but isn't quite as intensive then that would be welcome.

**Comment by nicolevonvon** [comment]
Hi all, work deadlines did not let up and I'm going away without internet for a while. I unfortunately won't be able to complete this. Sorry.

**Comment by Alys** [comment]
@nicolevonvon No problem - real life always should take precedence! Thank you for letting us know.

**Comment by pnrich** [comment]
I can take a look at this. Seems like a good introductory problem.
