### ISSUE TITLE
Missed the April subscriber gear despite being a subscriber for months

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#3519]
Hello! I'm not sure if this is a bug or not, but it's really inconvenient either way. Apparently the April subscriber gear was supposed to be the Twilight Butterfly set, but when I checked my Mystery Items this month, I only got the flame set. I assumed that if you didn't claim your Mystery Items one month, then next month you'd simply have 4 Mystery Items instead (2 from the first month, 2 from the second month). However, that doesn't appear to be the case, instead it seems the new month's Mystery Items overwrite the old ones. I'm pretty bummed about this, and I'm sure it's an easy fix. I did some searching and found that another person had the same problem, but it didn't seem like the issue was fixed for everybody, just that one person: https://github.com/HabitRPG/habitrpg/issues/3443

My User ID: 8a1db51b-01f8-4794-8f9b-a0da605b9bcb

**Comment by Sethycakes** [comment]
Bump

**Comment by Sethycakes** [comment]
Oops, that was an accident.

**Comment by deilann** [comment]
@lefnire is on vacation right now, and is the only one who can fix this. I
know it's frustrating, but if you could please be patient, it would be
appreciated.

**Comment by lefnire** [comment]
ran update, check now

**Comment by Sethycakes** [comment]
I got it! Thanks a bunch!
