### ISSUE TITLE
Login from ipad/website preventing login from android device

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3520]
Hello,

My user id is 86939c6c-fa8f-4e02-9f7d-b04b9f5494f9

On my ipad, I can long in via the website or app.
On my android phone, I cannot login via the website or app. It says either the username or password is incorrect.

I have also tried: resetting my password, signing in with my user id and API token, uninstalling and reinstalling apps.

When I registered it was on the ipad app.

Thanks!

**Comment by ghost** [comment]
I just had the idea to log out of my ipad first and then I could log in to my android. I'm sorry plz disregard

**Comment by thepeopleseason** [comment]
Hmm... looks like this isn't desired behavior, reopening. May be unrelated to the ipad/website login, but it bears investigation.

**Comment by ghost** [comment]
Hi, it actually stopped working again, even after logging out of the website and app on my ipad.

**Comment by Alys** [comment]
I'm closing this because I believe that whatever was causing the problem would no longer be happening. I haven't seen any other reports of being logged in on one device preventing logging in on another. This can be reopened if it's still happening.
