### ISSUE TITLE
Character column missing

### ISSUE THREAD

**Issue by alexandre-hirata** [HabitRPG/habitica#3522]
I am ahirata and somehow my character column, the one that I apply the points that I earn when I complete lvl 10 is missing... All my points were applied to str and I did not do this. Another issue that I am facing is that I am not seeing anything regarding my skill.

Thanks!

**Comment by deilann** [comment]
You won't see any skills until you hit level 11. They will be under the
rewards column.

There are only 2 ways your points could have been applied without you doing
it:

1) you have auto-allocation on
2) someone else did it for you (as in, someone accessed your account)

Do you have auto-allocation on?

**Comment by alexandre-hirata** [comment]
I am lvl 11... And there is no skill on the rewards column...

In Stats & Achievements, there is no column saying anything regarding the auto-allocation... Actually, I have 2 columns... One with my stats (str, con, etc, etc) and another one with:
Contributor
Has contributed to HabitRPG....

I see my friend's profile is different than me, including a char in same lvl that I am. Something is going wrong in my profile.

Thanks!

**Comment by deilann** [comment]
Can you get me a screen shot?

**Comment by alexandre-hirata** [comment]
![screenshot - 05232014 - 03 36 41 pm](https://cloud.githubusercontent.com/assets/4160186/3070443/4a8cb5b6-e2a9-11e3-966b-f3196e7a3424.png)

**Comment by alexandre-hirata** [comment]
![screenshot - 05232014 - 03 38 04 pm](https://cloud.githubusercontent.com/assets/4160186/3070449/6783012a-e2a9-11e3-96cc-3dfae7ad454d.png)

**Comment by deilann** [comment]
You need to enable classes. If you opt out of the class system, you won't get class benefits.

Go to Site > Settings > Enable Class System

Also, greyed out badges are badges you have not earned.

**Comment by alexandre-hirata** [comment]
Thanks! So, with it, the third column appeared! But I don't have the skill... Did I lose it?

**Comment by deilann** [comment]
Do a refresh of the tasks page.

**Comment by alexandre-hirata** [comment]
I did and a skill appeared! But I am not able to click on it... MP means mana, right? I have almost full mana...

**Comment by deilann** [comment]
What skill is it?

Some skills require you to click on the skill and then a task.

**Comment by alexandre-hirata** [comment]
Ah! Sorry... Indeed! It is brutal smash.. I choose a warrior... 

Thanks and I am sorry for the noob questions
