### ISSUE TITLE
Equip API call not working

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#3525]
Apparently the API call for equipping things is broken.
When calling it, it always returns a response with what gear, pets, mounts etc. you have. But it does not (un)equip anything. This seems to be the case for pets, mounts and gear. No matter what I entered, nothing got equipped.

steps to reproduce:
1. https://habitrpg.com/static/api#!/user/user_inventory_equip_type_key
2. choose either, pets, mount or gear
3. enter a key

Interestingly this seems to only affect the API endpoint. The website still works, as that uses the batch-update API call.

**Comment by kenfink** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  playwithscience@gmail.com
    Domain wondergy.com has exceeded the max emails per hour (1233/1000 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:48916 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
    by slmp-550-39.slc.westdc.net with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
    (Exim 4.82)
    (envelope-from noreply@github.com)
    id 1WoHXj-004EGM-SP
    for mail@wondergy.com; Sat, 24 May 2014 13:23:44 -0600
Date: Sat, 24 May 2014 12:23:40 -0700

**Comment by negue** [comment]
I'll close this issue, I use this API Call and it works^^
