### ISSUE TITLE
Add socket.io sync instead of manual refresh button?

### ISSUE THREAD

**Issue by fgolemo** [HabitRPG/habitica#3526]
Hey,

is there anything that is preventing us from implementing a socket.io automatic sync (instead of the manual sync buttons in the main window and party)? I mean would it put e.g. too much bandwidth on the server or something?
Don't get me wrong, I am totally aware that it would be a rather large rewrite. I'm not asking anybody to do it - I'd just like to try it out and wouldn't want it to be wasted effort.

For the sync I'd propose 
(a) the personal lists of habits, dailies, todos,..., including if they're checked and which attributes they have - I'd like to have this feature, because I always have HabitRPG open on different computers,
(b) your health, XP, mana and
(c) your party members' health bar.

Cheers,
Flo

P.S.: how do I label this issue? Don't want to bother everyone with dev suggestions.

**Comment by lefnire** [comment]
See https://github.com/HabitRPG/habitrpg/issues/1503

**Comment by negue** [comment]
Closing this, further discussion at #1503
