### ISSUE TITLE
Could not register new user with Firefox 29

### ISSUE THREAD

**Issue by jonathanderque** [HabitRPG/habitica#3529]
The register form seems broken with Firefox 29

How to reproduce:
- launch Firefox 29 and click on the "Play" button from the main page
- switch to the Register tab
- fill in the username, email and passwords
- clicking on the "Register" button does nothing

I'm using Firefox 29.0.1 on ArchLinux.

**Comment by deilann** [comment]
Do a hard refresh or clear your cache. Lemme know is that helps.

**Comment by jonathanderque** [comment]
I've cleared my cache, pressed Ctrl+F5 on the homepage, to no avail.

I managed to register using Chromium and then login from Firefox 29 works, but the register form is stiill not responding to clicking on the register button.

**Comment by deilann** [comment]
S'weird. I've registered test users on Ubuntu in Firefox 29 in the past
week.

**Comment by timelf123** [comment]
@jonathanderque can you bring up your console and see if any errors are thrown when you click the register button?

**Comment by jonathanderque** [comment]
Hi,
It looks like the rgister button is now working for me.
I'm still using the same version of firefox 29.0.1 so I'm not sure if something on the site has changed or if this is an issue on my end.

I guess this issue can be closed..

Thanks!

**Comment by SabreCat** [comment]
Cool. We can reopen if anybody stumbles across this again. Sorry for the temporary inconvenience!
