### ISSUE TITLE
Change Language Button on Front Page? [$5 awarded]

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3530]
Received a request from a user who didn't want to sign up for the service because from the front page they didn't know they could change the language. I know it automatically detects the country's language, but there are plenty of non-native speakers living in countries.  

How difficult would it be to add a language selection tool from the front page?
##

**Comment by deilann** [comment]
pinging @paglias

**Comment by paglias** [comment]
I can add it but where? I would go for the footer

2014-05-25 22:04 GMT+02:00, deilann notifications@github.com:

> pinging @paglias
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3530#issuecomment-44144082

## 

Matteo Pagliazzi - paglias.net

**Comment by deilann** [comment]
What about the toolbar at the top on the landing page, actually? Next to
the play button?

**Comment by paglias** [comment]
If we can find a non invasive way to show it.. it shouldn't be as
visible as the play button I think

2014-05-26 18:10 GMT+02:00, deilann notifications@github.com:

> What about the toolbar at the top on the landing page, actually? Next to
> the play button?
> 
> On Mon, May 26, 2014 at 7:55 AM, Matteo Pagliazzi
> notifications@github.comwrote:
> 
> > I can add it but where? I would go for the footer
> > 
> > 2014-05-25 22:04 GMT+02:00, deilann notifications@github.com:
> > 
> > > pinging @paglias
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/HabitRPG/habitrpg/issues/3530#issuecomment-44144082
> > 
> > ## 
> > 
> > Matteo Pagliazzi - paglias.net
> > 
> > —
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/HabitRPG/habitrpg/issues/3530#issuecomment-44195848
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3530#issuecomment-44201404

## 

Matteo Pagliazzi - paglias.net

**Comment by deilann** [comment]
I don't see why not. If it were just a menu of languages next to the play
button, that would strike me as completely normal.

**Comment by lemoness** [comment]
It seemed like the person who requested it was searching among the footer.
Maybe lower right corner?

**Comment by deilann** [comment]
I'm not sure why we're trying to hide it. It's a useful tool, and I think
Habit should more loudly advertise that it comes in multiple languages.
That's a feature, not something that needs to be hidden. It's not uncommon
for sites to put a language option in a conspicuous place on their landing
page.

**Comment by lemoness** [comment]
K! Then stick it up top :)

**Comment by paglias** [comment]
![selezione_070](https://cloud.githubusercontent.com/assets/589911/3085712/d8ec46ca-e518-11e3-95d8-838b91c89aa2.png)
Something like that?

**Comment by deilann** [comment]
Precisely.

**Comment by paglias** [comment]
Ok. I'll do it, I'm only not very sure with the alignment and the text (en
is very simple and I like it but probably the full name is needed). Also
usually this type of drop down is in the footer... Anyway, I'll do it
because it's not the first time it has been requested but really, if you
want a site in German I'm wondering why you don't have your pc/phone set to
German
Il 26/mag/2014 23:02 "deilann" notifications@github.com ha scritto:

> Precisely.
> 
> On Mon, May 26, 2014 at 2:01 PM, Matteo Pagliazzi

**Comment by deilann** [comment]
@paglias On a full site, yeah, I often see it in the footer, but usually
when it's a landing page, it's usually somewhere far more conspicuous in my
experience. Either way, I can't see any drawbacks from showing it
prominently. If you're concerned that users might not see it in the
prominent location and look for it in the footer, it could be in both
places.

**Comment by Alys** [comment]
Prominent would be VERY good. This insightful comment was posted to the Tavern today by Aira (4f7694ac-30f7-4549-86f6-a81dcbcc5363):

"Regarding the language, there is one fairly big problem I encountered when I first started up the site. It automatically detects your location and gives you the site in that language. I live in Prague, but I'm not Czech. It would be no problem, except the place to change the language is VERY hard to find if you don't understand all the menus. It should be right on the front page, at the top or bottom, or the site could even ask when you first start what language you want. In order to change it, I had to visit every page one by one, not understanding a word, until by chance I stumbled upon the correct drop-box. : /"

**Comment by deilann** [comment]
Actually, that's not how it works, I think.

I thought it grabbed the browser's default language.

**Comment by Alys** [comment]
Even the browser's default language could cause problems if you're using a friend's computer or a net cafe / library / university in a foreign country.

**Comment by deilann** [comment]
Agreed, but it should certainly NOT be going off location, as that's a
terrible idea and if it is, we should stop that.

**Comment by paglias** [comment]
@deilann @Alys  Sorry for the delay. It's not based on location. It's based on computer settings. When contacting HabitRPG the browser sends a list of accepted languages with a ranking where languages associated with a number closer to 1.0 are preferred http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4 . 

I don't know exactly how OS implement this but I strongly believe that it is based on the system settings of the computer not on the location.

It's possible, but I can't be sure without more info from the user, that the user's setting was to use a language not supported by HabitRPG so when she connected the browser may have sent a list like this:

"Language X not supported by Habit, Czech, ..." in which case habit would have chosen to use Czech being the first language unavalaible.

**Comment by paglias** [comment]
I made a quick check with my browser & system settings and it looks like the settings not the location are used.

**Comment by Alys** [comment]
@paglias : Note that I was never able to get more information from Aira about that comment. I asked if the browser was set to Czech, but Aira didn't reply. "Detects your location" might well have meant "detects your browser/PC setting".

Regardless, for this particular issue, I don't think it really matters how the site gets your language settings. There'll occasionally be users using a loaned PC in a foreign country, and the language settings, while correct for the PC, won't be correct for the user. A language drop-down on the front page would fix that. My only reason for pasting in Aira's comment was to give one additional reason to support a front-page language menu. I'm sorry if it came across as a bug report! :)

**Comment by paglias** [comment]
Don't worry :) I'll try to have it working in a few hours. It's just
that I have to read about 100 emails from two weeks out of home and
will leave again tomorrow for another few days so excuse me for any
delay!

2014-07-28 15:49 GMT+02:00, Alice Harris notifications@github.com:

> @paglias : Note that I was never able to get more information from Aira
> about that comment. I asked if the browser was set to Czech, but Aira didn't
> reply. "Detects your location" might well have meant "detects your
> browser/PC setting".
> 
> Regardless, for this particular issue, I don't think it really matters how
> the site gets your language settings. There'll occasionally be users using a
> loaned PC in a foreign country, and the language settings, while correct for
> the PC, won't be correct for the user. A language drop-down on the front
> page would fix that. My only reason for pasting in Aira's comment was to
> give one additional reason to support a front-page language menu. I'm sorry
> if it came across as a bug report! :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3530#issuecomment-50340061

## 

Matteo Pagliazzi - paglias.net

**Comment by deilann** [comment]
@paglias Looks like there's a bounty on it -- don't forget to go claim it. :)

**Comment by paglias** [comment]
@deilann @lemoness @Alys 
![selezione_009](https://cloud.githubusercontent.com/assets/589911/3791142/c819be8e-1b2a-11e4-964e-ad67b8418c58.png)

This is where I put it, feel free to suggest another design

@deilann the bounty can be redistribuited?

**Comment by deilann** [comment]
Yeah, when you claim the bounty it goes into your bountysource account and
you can do whatever you want with it.

**Comment by paglias** [comment]
@deilann great! if you have any suggestion for a ticket to assign the money, even an issue with an existing bounty, let me know

**Comment by deilann** [comment]
Haha, it's your $5. Put it where you best feel it should go. :)

**Comment by paglias** [comment]
@deilann I'll think about that :) what do you think of the position? You wanted it in more central place so feel free to move it or suggest another location

**Comment by Alys** [comment]
I think many people wouldn't notice it in the footer and wouldn't think to look there while under the stress of being faced with a page in an incomprehensible language. (Many people ask in the Tavern how to request features and there's a clear "Request Feature" link in the footer!)

Can it be placed in the middle of the page, next to or underneath the Play button? That's the only place I'd be certain people would see it. If that makes the page too ugly, then in the header perhaps?
