### ISSUE TITLE
Party losing huge amounts of HP during Spirit of Spring quest

### ISSUE THREAD

**Issue by urphoth** [HabitRPG/habitica#3532]
I'm doing the Spirit of Spring quest in a party with one other person. A few days after starting it, we started receiving huge HP damages for no apparent reason - lots more than could be explained by any account's dailies. The first time this happened, the other player was attacked for 64.4 (!) damage, and we both died.

It seems to be more of an issue with the other player than with me. Some of the time his damages are at a normal level, but on other days he loses tens of HP. I've talked to him about it and we can't figure out why.

**Comment by deilann** [comment]
The Spirit of Spring boss deals much more damage than dailies do on their
own -- on top of any normal damage a user would receive. Doing 64.4 damage
is entirely feasible. Have your party member check out Alys' tool:
https://oldgods.net/habitrpg/habitrpg_user_data_display.html It will show
how much damage the boss will deal per daily.

It may also be that your party member is checking off his dailies too
quickly, and causing errors that keep them from syncing to the server. It's
incredibly important to always wait for the blue bar to finish before
checking off something else. Alys' tool can also help there, as it draws
its information from the server, and so will show if dailies were not
actually checked off.

**Comment by urphoth** [comment]
Ah, I didn't know that different bosses could be more or less severe when dealing damage to a party. Thanks!

**Comment by deilann** [comment]
Yup! If you check out the Wiki, you can see their different strengths!
