### ISSUE TITLE
Wearing blue mouse ears after using Orb

### ISSUE THREAD

**Issue by rcichy** [HabitRPG/habitica#3533]
After using Orb I don't have mouse ears in equipment which is OK, but I'm still wearing them.

Steps to reproduce (probably - I will try to reproduce this on my local instance today):
1. Buy blue mouse ears
2. Use Orb
3. You are still wearing mouse ears.

![Screenshot](https://cloud.githubusercontent.com/assets/5044995/3079303/9e13a486-e495-11e3-9208-32860b5eb55d.PNG)

**Comment by deilann** [comment]
Yeah, it's a known oversight. Orb of Rebirth code was written before head
accessories were added, so it doesn't think to dequip them.

There's another ticket on this. I'll search for it in a second. If you find
it first, please link the ticket and close this one.

**Comment by rcichy** [comment]
https://github.com/HabitRPG/habitrpg/issues/3377

**Comment by deilann** [comment]
Awesome thnx
