### ISSUE TITLE
Rewards: Broken layout when the text is too long.

### ISSUE THREAD

**Issue by iuga** [HabitRPG/habitica#3534]
Basically that. I'm attaching a screenshot:
![screen shot 2014-05-26 at 10 32 14 am](https://cloud.githubusercontent.com/assets/1430179/3082893/ce942cda-e4da-11e3-8ddb-0b2fc7111738.png)

**Comment by iuga** [comment]
Any news?

**Comment by deilann** [comment]
This is not going to be super high priority, but thank you for bringing it
to our attention.

**Comment by rcichy** [comment]
Fixed rewards (which luga's screenshot shows) but also spells.

My screenshot below - on left old - on right fixed.
![capture](https://cloud.githubusercontent.com/assets/5044995/3278517/a790394c-f3c3-11e3-8329-a5928f04cdb6.png)

**Comment by lemoness** [comment]
@lefnire This is merged, so should I close this ticket?

**Comment by lefnire** [comment]
√
