### ISSUE TITLE
May Mystery Items

### ISSUE THREAD

**Issue by sefi-ne** [HabitRPG/habitica#3536]
I cannot obtain my May mystery items. Whenever I click on the mystery item box to retrieve my May mystery items, it turns up empty and but the notification still reads that I have yet to open the box. Please fix. I'd like my May items for subscribing.

**Comment by deilann** [comment]
Do a hard refresh or clear your cache to load the new code.

**Comment by Alys** [comment]
I'm assuming deilann's suggestion fixed the problem since there was no response after it, so I'm closing this job. It can be reopened if sefi-ne never received the May mystery items.
