### ISSUE TITLE
Character costume has unowned gear after rebirth

### ISSUE THREAD

**Issue by matthock** [HabitRPG/habitica#3537]
My costume currently has items that I owned prior to rebirth, but that I have not yet repurchased. As they are not on my gear list, I cannot remove them from my costume. The items in question are all Mystery Item type.

What I did that resulted in this state (some of these steps may be optional to trigger the condition, but I want to be thorough):
- Created a costume utilizing Mystery Item gear. 
- Deselect the costume and show my regular gear
- Rebirth
- Re-enable costume because I want to use the May mystery items, but find that I still have the April mystery items equipped in the costume from before the rebirth

**Comment by deilann** [comment]
See this ticket: https://github.com/HabitRPG/habitrpg/issues/3377

Once you own an item in the slot, you'll be able to equip/dequip them.
