### ISSUE TITLE
Dalies Did Not Reset

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3538]
Because of the long weekend, I set my account to Rest at the Inn. When I came back this morning, everything was okay, but my dailies were still all marked off from when I went to the inn on Thursday. I could unclick them, but then I lose my XP and coin from the previous day. I do not see a way to reset them.

**Comment by thepeopleseason** [comment]
This is a result of resting at the inn--it freezes the state to when you initially "rested." One thing you could do is record how much XP and gold you currently have, uncheck all your dailies, then go into the Settings and Fix Character Values to what you should have.

**Comment by thepeopleseason** [comment]
Closing ticket as duplicate. (See #2625)
