### ISSUE TITLE
[Suggestion] Support for BodBot workouts as daily task

### ISSUE THREAD

**Issue by FLAGSHiP87** [HabitRPG/habitica#354]
http://www.bodbot.com is new a tool to track you personal fitness (with is in already founded on fundable.com - http://www.fundable.com/bodbot). BodBod suggest a combination of exercises you could perform as your (daily) workout and tracks you progress. 

You could create a task "(daily) workout" in HabitRPG, that is linked with the workout from BodBot and marked as completed in both systems, once you completed the workout and marked it as such in either service.

**Comment by StanLindsey** [comment]
Thanks, sounds like a great site for integration, its been added to our list of APIs to consider on Trello. 

Make sure to vote for it [here](https://trello.com/card/bodbot/50e5d3684fe3a7266b0036d6/150)
