### ISSUE TITLE
Insta-Death Issues

### ISSUE THREAD

**Issue by Pandah** [HabitRPG/habitica#3541]
Earlier my little sister logged on and it logged 110.8 damage to our party. She said she had not logged in for two days, but it has never logged that much damage before for a missed day.  Is this normal? lol.  I'm not exactly sure how to tell what the issue is if it is not so please let me know if I need to provide any other information.

**Comment by thepeopleseason** [comment]
Her lack of login during two days accumulated two days' worth of missed dailies' damage to your party.
