### ISSUE TITLE
Deleted Users' Challenges Remain

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3543]
When a user deletes their account, any challenges they created remain and are undeletable.
##

**Comment by Alinorr** [comment]
Maybe this is the same problem I'm having. I have a challenge daily called Transfer $ for lost HP which I'd like to leave, but it no longer shows up in the Challenges area or in challenges I'm participating in.

Maybe this is how it's effective! I genuinely have to stick to it or it massacres my HP...

**Comment by Alys** [comment]
@Alinorr : See "Deleting a Challenge Task" in [Challenges](http://habitrpg.wikia.com/wiki/Challenges). Does that help?

**Comment by Alinorr** [comment]
@Alys Thank you! That's fixed it! I didn't have the broken link icon before but I have it now - thanks so much for the help!

**Comment by deilann** [comment]
Reopening. This ticket is about how when a user deletes their account,
their challenges still remain in limbo, which still happens.

**Comment by lemoness** [comment]
Ah, whoops! Misread the title as our typical duplicate.

**Comment by Verabird** [comment]
What happens to guilds or parties if the leader deletes their account?

**Comment by Alys** [comment]
@Verabird (only four months late), the next most senior member becomes leader (i.e., the first member who joined after the group was created).

**Comment by Alys** [comment]
Ideally we should change the owner of the challenge, probably to the owner of the associated group (Lemoness for the Tavern?), because other players might be using the challenge.

**Comment by crookedneighbor** [comment]
@Alys I think technically Lefnire is listed as the leader of the guild "habitrpg"

**Comment by Alys** [comment]
I'm closing this because we now have orphaned challenges listed as "no owner" and the [Elves](https://habitica.com/#/options/groups/guilds/a7d0a7c8-f1cf-4813-b841-75308003f611) search for them often and find new owners or close them.
