### ISSUE TITLE
Kickstarter supporters ($70+) didn't receive mount

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3544]
The [Kickstarter](https://www.kickstarter.com/projects/lefnire/habitrpg-mobile) rewards from $70 and up list a mount, but I believe that the mount wasn't received by some/most/all supporters, except possibly the highest level supporters. I didn't receive one (userid d904bd62-da08-416b-a816-ba797c9ee265), and the [kickstarter page on the wiki](http://habitrpg.wikia.com/wiki/Kickstarter) didn't include the mount until today (when it was mentioned sort of by accident in the Tavern).  I'm pretty sure this means that no/few Kickstarter backers received it otherwise someone would have added it to the wiki before now.

For other Kickstarter backers that are concerned about this, please be aware that Tyler / @lefnire  (HabitRPG's main developer) is currently on holidays and when he returns he might have critical bugs to deal with before he can investigate this issue. Please be patient and watch this issue ticket for updates.

**Comment by lefnire** [comment]
Woa!! If that's true, I'm _so_ sorry for all the 70+ backers out there. I was always wondering why I never saw people using that mount ("I thought it was cool..."). I'll run a script soon as I can, since mounts are boolean it's easily handled

**Comment by lefnire** [comment]
There were 99 $70+, 44 missing mounts. The only thing I can think of is I must have, in my newbish mongo days, written the script for $70 _specifically_ (not $70+). It should be fixed now, sorry sorry sorry :(

**Comment by lefnire** [comment]
Just to double check, any 70+ let me know if it's still not working

**Comment by Alys** [comment]
I has a new mount!!! :)  Thanks for fixing this lefnire. Don't feel too bad - you have had a few other things on your mind over the past year or two. :)
