### ISSUE TITLE
Cron runs a second time after switching time zones

### ISSUE THREAD

**Issue by mlei** [HabitRPG/habitica#3547]
Yesterday I came back from a trip, and my cron ran once in the former time zone and once in the new time zone.

As far as I can tell, this was what happened:
1) Logged in on first device (mobile) in Eastern Time
2) Cron ran at midnight Eastern Time
3) Logged in on second device (laptop) in Pacific Time around 11pm (2am Eastern Time)
4) Cron ran again at midnight Pacific Time

I don't think this should happen, but it's not clear how to solve it correctly. Maybe we need a check that makes sure cron doesn't run for at least 12 hours after its last run, regardless of time zone?

Moses

**Comment by Alys** [comment]
@mlei We're tracking this issue in https://github.com/HabitRPG/habitrpg/issues/3806 so I'll close this one that you've logged. If you'd like notifications about any future fixes, there's a subscribe button in the right-hand column on that page.

We're planning changes to cron that will make it possible to avoid damage from unexpected events like this. We're still finalising the details, but we are definitely going to be making improvements.
