### ISSUE TITLE
User can't be added to party

### ISSUE THREAD

**Issue by fwylion** [HabitRPG/habitica#3548]
I've been trying to add a new user to my party, but even though she isn't in a party herself, I keep getting "Error User already in a party." (see Chrome console for more details). Is there any way to fix this?

**Comment by deilann** [comment]
Are you absolutely sure she isn't in a party? Are you also absolutely sure you are entering the right UUID?

Often, users are in a "solo" party. If that's the case, they have to leave that before joining a new party.

**Comment by fwylion** [comment]
She says she's not in a party, and that it's her UUID. I've added others to the party without any issues.

**Comment by deilann** [comment]
She may be mistaken.

If I could get a screenshot of her party page, that would be awesome. Have
her go to the party page, and wait for it to load completely. If it still
says she's not in a party, have her refresh and wait for it to load
completely again.

**Comment by fwylion** [comment]
Never-mind; fixed!
