### ISSUE TITLE
HTML comment before <html> in homepage

### ISSUE THREAD

**Issue by ArloL** [HabitRPG/habitica#3549]
When you look at the source of https://habitrpg.com/static/front you can see that there is a comment right at the beginning of the HTML like this

```
<!--Trick needed to pass 'env' to ./layout-->
<!DOCTYPE html>
```

[A quick search reveals a few files containing this comment.](https://github.com/HabitRPG/habitrpg/search?q=Trick+needed+to+pass&ref=cmdform&type=Code). This comment will [force IE 6 through 9 into quirks mode](http://en.wikipedia.org/wiki/Quirks_mode#Triggering_different_rendering_modes). This may result in some weird rendering issues. The comments should be removed or moved further down.

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg/pull/3550#issuecomment-45378279
