### ISSUE TITLE
Undo Daily, Can't Undo Drop

### ISSUE THREAD

**Issue by Dotombori** [HabitRPG/habitica#3552]
This is similar to #3487 and #47, but I accidentally checked the wrong daily and got a drop. When I undid the daily, the drop (and one silver coin) was not undone. It doesn't seem to be a problem for the gold (as mentioned in #3487), but the drop seems to be a bigger issue, since at higher levels it could accidentally give some good loot.

**Comment by deilann** [comment]
At higher levels, you have the same exact drops.
