### ISSUE TITLE
TASK DIFFICULTY v2: Trivial Difficulty Setting; Priority Multiplier

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3556]
Some users have indicated a desire to place a bounty on Trello Card https://trello.com/c/4C8w1z5h/17-task-difficulty-settings-v2-priority-multiplier, so here is the corresponding Github ticket!

Priorities should be on the new task difficulty settings, including a "trivial" setting which is much easier than easy, as that is what the person placing the bounty has requested. 

From the card:
a three level Priority setting with values: x1, x1.5, x2
an additional three level Difficulty setting with values .5 easy, x1 normal, x2 hard, 
- also: a "trivial"setting" (.1)
##

**Comment by wisteriacs** [comment]
What I would specifically want to place a bounty on is a "Trivial" setting that is significantly less than "Easy"--  around .01 (or at least as low as 1/10 of whatever "Easy" is-- I'm suffering from reward inflation). I'm not sure how to alter that bounty, but that's something that I would easily put $35-$50 on. I don't personally care about the priority settings so much, but having a wider range of difficulty values would be really nice.

**Comment by lemoness** [comment]
@wisteriacs Okay; I'm editing this ticket so that the Difficulty settings are prioritized, including adding a "trivial" setting! Attention @SabreCat

**Comment by wisteriacs** [comment]
Thanks!

**Comment by SabreCat** [comment]
Ah, cool. Is there any distinction on what game effects "Priority" vs. "Difficulty" should have? My instinct is that Difficulty scales the reward, while Priority scales the punishment and how rapidly a task gets red.

**Comment by lemoness** [comment]
@sabrecat I believe that was indeed the premise! From what @deilann says on
the card:

"Brushing my teeth doesn't require a lot of effort, but _not_ brushing my
teeth has a lot of real world consequence. Logically then, brushing my
teeth should give little XP and GP, but not brushing my teeth should take a
lot of HP."

In that case, brushing your teeth would be Easy, but High Priority.

I think it would be interesting if high-Priority tasks all started as
orange or even light red!

**Comment by lemoness** [comment]
@wisteriacs Did you want to place a bounty?

**Comment by efim** [comment]
@lemoness @wisteriacs @SabreCat 
When I started on this there were no comments on this ticket. 
But now there are different parameters for priority and difficulty, and it is easy to break simmetry in their usage for reward/penalty calculation. 

To determine damage we could use priority only, and difficulty only to determine gold reward. Or to use lesser power in polynom for secondary property. (Like sqrt)

I will add fourth difficulty setting trivial shortly, but multiplier .01 seem too low - just how many exp are people going to get for it - 0? And 1 silver coin?

**Comment by lemoness** [comment]
@efim @lefnire
How much will Easy tasks give you if they've just been created?

Also, does this pull request include a measure to change the defaults of
people's new tasks to fit the system? Right now tasks default to Easy, and
we'll get lots of complaints that people's tasks aren't giving them enough
rewards unless all those tasks switch automatically to being tagged Normal.

Easy tasks should become Normal. Medium and Hard tasks should become Hard.

We could start everyone's Priority off at Medium.

**Comment by efim** [comment]
@lemoness I don't really understand what you are saying - right now default values for difficulty and priority is 1, and it is absolutely corresponds to priority being 1 by default before. 
Just as was requested in trello: 

> Polls indicated users would prefer:
> a three level Priority setting with values: x1, x1.5, x2
> an additional three level Difficulty setting with values .5 easy, x1 normal, x2 hard

If people prefer not to change their settings they will not notice anithing with current computations of rewards.

Added trivial difficulty setting; if you really want to break simmetry in calculations of monetary rewards and hp penalties for tasks based of priority and difficulty I believe that you would like to discuss it first, and last word would probably be by @lefnire, so I don't change them in this pull request.

**Comment by lemoness** [comment]
@efim That's fine, then! I wanted to make sure that the tasks would map
according to values (1 to 1) instead of titles (Easy to Easy). Since that's
the case, there's no issue there.

**Comment by wisteriacs** [comment]
Thanks! I placed it. I'm at a really high level, I know, but I'd love a 1 silver reward, honestly. For really silly things like "resist temptation to get distracted while getting ready for bed". I might hit it 20 times while getting ready for bed, but at least I got there without reaching for the other internet-distractions my phone offers. I've done it with the current "easy", but that leads to inflation really quickly. I study motivation and work with other ADDers, and $35 is worth it to me to experiment with the lower values. If/when it's implemented, I would love to hear if others find it useful for a little reminder/reward for staying on the path when distraction calls.

(I accidentally placed 2 bounties on this because they didn't empty my cart. So, if you want to say "thanks", one _could_ throw in an insane .01 for me to experiment with. Not needed, just putting it out there. 😃)

**Comment by efim** [comment]
@lemoness @Alys @lefnire 
I thought that it would be a demanded functionality.
What should be done for it to get merged? Maybe we're waiting for something first?
I personally would love to have separate difficulty/priority settings.

**Comment by LordVladneutral** [comment]
Something that is present on trello, pushed by me but not only me, is the idea that there should be a way to have a task with damages different from the reward it gives. There should be unrewarding tasks that hit hard and very rewarding tasks that hit less.

I'd like to put a bounty on that function, that is why I bring it up here, but should I do it on this issue ? It's the closest I could find ? Should I open something ? Should somebody else open something ?

**Comment by lemoness** [comment]
Thanks for commenting! We're open to that feature in the future, but we're actually going to need to do some internal discussions before we'd be ready to accept a bounty on something like this. I'm sorry for the disappointment. I'm going to close this issue to avoid further confusion.
