### ISSUE TITLE
OmniFocus Integration

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3557]
A user has indicated a desire to place a bounty on Trello Card https://trello.com/c/aDtc4RUz/441-omnifocus, so this is the corresponding ticket.

From the card:

"Request for Integration: OmniFocus! Flagged tasks only, or it would completely overwhelm HabitRPG."

**Comment by Gaelan** [comment]
No bounty, close?

**Comment by lemoness** [comment]
Closing this for now - we'll reopen if the user ever decides that they want to post a Bounty.

**Comment by matthewspear** [comment]
https://github.com/Matthewspear/OmniRPG - I've made this for my own use, it tallys completed tasks done over the past day and triggers a habit with them.

I've also add different levels of difficulty and context recognition to allow for different task to earn different rewards.

Hope this is useful to someone else too!

**Comment by Alys** [comment]
@Matthewspear That looks very exciting! We'll check it out!

Could you please send me a PM? There's something I want to discuss that I don't want to put in public for reasons that will become obvious. :)  You can go to the Tavern to find my name in the list of moderators.

**Comment by matthewspear** [comment]
Yeah sure! Matt
