### ISSUE TITLE
Pet Screen Speed Issues

### ISSUE THREAD

**Issue by nerdmagnet** [HabitRPG/habitica#3558]
I have an issue when I'm in the pets page. It doesn't seem to be happening any other page yet, but I've been keeping an eye out. Whenever I go to the page, everything becomes extremely slow. When I click on a food, I end up waiting 5 to 10 seconds before it registers that I've clicked on it, and another 5 to 10 seconds after I feed it to a pet. The only thing that isn't immediately slow is the scrolling speed when I first go to that tab. It gets sticky after I click something, however.

**Comment by SabreCat** [comment]
Possibly the same thing as #3486? What browser are you using?

**Comment by nerdmagnet** [comment]
I've tried Chrome, Firefox, and I even resorted to Internet Explorer to see if it was just Chrome. It's slow in the pet page on all three browsers.

**Comment by kipinae** [comment]
I'm experiencing the same issue, but only at home on both my desktop and laptop. At work the problem ceases to exist, so I'm guessing it's a network related issue?

This happens both on Chrome and Firefox.
I noticed the lag appears only after clicking something, as nerdmagnet said, OR if I happen to hover over something.
Can't remember when exactly this started happening, maybe within a month or so? I know it hasn't always been like this though.

**Comment by lefnire** [comment]
I'm now rendering pets & mounts on the server (https://github.com/HabitRPG/habitrpg/commit/cb7324ccdb267e41252686948576acb7aaf2c53a https://github.com/HabitRPG/habitrpg/commit/df1867ef4dd464fcae44f4a8147b7622f1056221). Since food is dynamic, it must be rendered on the client. https://github.com/HabitRPG/habitrpg/commit/8d49a4d0324b780f7ea3b15c5b93ba1ed3c4fc57 improves food's perf via Angular 1.3's bindonce feature. Could y'all try https://beta.habitrpg.com and see if there's a noticeable diff?

**Comment by deilann** [comment]
Noticeable difference: I cannot load any of the pages.

**Comment by kipinae** [comment]
On the beta site, the pets and mounts are now working as smoothly as ever. The market page still lagging.

**Comment by lefnire** [comment]
Pets and mounts were the only pages affected, so that supports my theory...
But used messages, Ryan you sure?

**Comment by lefnire** [comment]
*mixed

**Comment by deilann** [comment]
About 75% of the time, trying to load the page is either getting me a half
loaded page with 5 or 6 pop up application errors. 15% of the time it is
giving me the "Application Error" page. And about 10% of the time, the page
properly loads.

**Comment by deilann** [comment]
(For the record, prod is running perfectly fine for me.)

**Comment by lefnire** [comment]
I reverted mongoose version upgrade, let's try again on beta

**Comment by thepeopleseason** [comment]
On the beta, on the pets page. the pets are sorted alphabetically by pet type in the v1 section, then sorted by release date in the v2 section (as opposed to alphabetically by pet type on the main site). 

On the mounts page, the mounts are sorted alphabetically descending (Z-A) for the v1 mounts, then by release date for the v2 mounts (as opposed to v1 and v2 intermingling alphabetically ascending).

**Comment by kipinae** [comment]
Pets and mounts continue running smoothly on beta, market still laggy.

**Comment by lefnire** [comment]
@paglias this confirms the function watchers were the issue. I'll just go through as I find time and replace the function watchers with either (a) server-side renders using Jade, or (b) `{{:: foo.bar() }}` angular 1.3 bindonce directives (just add a `::` in the watcher and we're all set). In fact, it's dirt simple to just add that `::` where functions are being watched, so maybe that as a first iteration is the best for now

**Comment by Alys** [comment]
I believe this is fixed.
