### ISSUE TITLE
Hitting "Fetch recent messages" shows old quest participants table

### ISSUE THREAD

**Issue by rcichy** [HabitRPG/habitica#3564]
Sorry if this is something obvious but I don't understand how fetch r.msgs button works in 100%.
1. I was one of firsts "Rat King" quest participants.
2. Then couple of hours passed and I saw attacks by players that was not on participants table. So I hit sync then "fetch recent messages" but table didn't expand (in both cases).
3. So I hit ctrl+shift+R and table had updated but bizzare thing occured when I again hit "fetch recent messages" - I'm back with old short participants table.

This occuring even if I now log in in other browser.
This is not occuring if I hit sync button in step 3. Newer table stays.

This is how it works or is this a bug?

I capture a short .video in this swf file (cannot upload swf on github)
I hit ctrl+shift+R in the middle of video to see newer list of participants.
http://www.swfcabin.com/open/1401962944

**Comment by crookedneighbor** [comment]
Sorry this took so long for us to respond. The code for this has been updated since you opened the issue. Please reopen if you're still having issues.
