### ISSUE TITLE
Invitations to private guild don't work

### ISSUE THREAD

**Issue by Castiblanco** [HabitRPG/habitica#3567]
Well, I don't know if it is just a trouble of my guild, but I have created one Private Guild and It seems something is wrong, I sent the invitation to some user and she didn't receive any notification in order to be a member.

My Guild id is: 9f43bbe2-3af7-4af5-b008-9cc2ef681245

I was thinking in changing it to a Public Guild in order to let her find it but it seems not possible.

Thanks a lot, I don't want to spend my precious gems creating another one :)

**Comment by deilann** [comment]
Refresh the guild page. Does she show up as invited in the member's list?

**Comment by Castiblanco** [comment]
Yes, she shows up, but in her account nothing happened, I have removed and tried again plenty of times but nothing new. Thanks for the interest :+1:

**Comment by deilann** [comment]
She may need to refresh and click her notifs. If she's showing up, this is
most likely a problem on her side (how she's looking for the notif) and not
the guild invitation being broken.

**Comment by Castiblanco** [comment]
That was it, problem was that the notification never was showed but I was hide in the notification section.
