### ISSUE TITLE
Missing Equipment

### ISSUE THREAD

**Issue by clusterpainter** [HabitRPG/habitica#3568]
I used Pickpocket a bunch of times and bought the black leather hood. The hood is now missing from my inventory. I was not reimbursed the gold for the hood or the MP I used to earn that much gold.

**Comment by deilann** [comment]
Sounds to me like you probably clicked too much too fast. That can cause
server errors. Always wait for the blue bar to fully cross the screen
before taking another click.

You can refund yourself the gold via Fix Character values in Settings >
Site, and repurchase the hood.

**Comment by clusterpainter** [comment]
I did that, and then I just clicked on a daily and lost 19 gold and 30 silver. I really wonder why that just happened! That daily was the only thing I've clicked in a while.

**Comment by clusterpainter** [comment]
I can give myself the gold back, but I want to know if I lost it for a reason. It's important to only get the rewards I've earned and I wondered if the system may have accidentally over-rewarded me and was subtracting gold I shouldn't have had to begin with. I recently started using the chrome extension so perhaps that could be causing problems.

**Comment by deilann** [comment]
Yes, when you lose gold, it's because your local side (the side you see)
ended up getting more gold than what was saved to the server. So you click
on a daily and it goes "hey server, let's sync" and server goes "I have
less gold than you" and so you see that you've lost gold.
