### ISSUE TITLE
Can't parse JSON file when running vagrant (error on the npm install step)

### ISSUE THREAD

**Issue by ArjavS** [HabitRPG/habitica#3572]
@thepeopleseason 
I keep getting this error
Error: Cannot find module 'swagger-node-express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/src/server.js:27:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

and 

info: [Sun Jun 08 2014 00:59:59 GMT+0000 (UTC)] [master:7617] worker:7629 disconnect! new worker:7631 fork
info: [Sun Jun 08 2014 00:59:59 GMT+0000 (UTC)] [master:7617] worker:7623 disconnect! new worker:7632 fork

**Comment by thepeopleseason** [comment]
To clarify: 

You get the top error during npm install and you get the bottom error after you've already done the install and are running npm start?

**Comment by ArjavS** [comment]
no they both happen when i run npm install
the number in  [master:xxxx] worker:xxxx keep increasing (it started from 6800) and it keeps logging the JSON parsing error

**Comment by ArjavS** [comment]
when i run npm start or npm install i get this:
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  Welcome to your Vagrant-built virtual machine.
  Last login: Sun Jun  8 00:57:47 2014 from 10.0.2.2
  vagrant@habitrpg:/vagrant$ npm start

> habitrpg@0.0.0-152 start /vagrant
> grunt run:dev

Running "stylus:build" (stylus) task
File build/app.css created.
File build/static.css created.

Running "concurrent:dev" (concurrent) task
Running "nodemon:dev" (nodemon) task
Running "watch" task
Waiting...8 Jun 01:30:15 - [nodemon] v0.7.10
8 Jun 01:30:15 - [nodemon] to restart at any time, enter `rs`
8 Jun 01:30:15 - [nodemon] watching: /vagrant
8 Jun 01:30:15 - [nodemon] starting `node ./src/server.js`
8 Jun 01:30:15 - [nodemon] reading ignore list

module.js:340
    throw err;
    ^

module.js:340
    throw err;
    ^
Error: Cannot find module 'swagger-node-express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/src/server.js:27:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Error: Cannot find module 'swagger-node-express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/src/server.js:27:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
info: [Sun Jun 08 2014 01:30:42 GMT+0000 (UTC)] [master:7794] worker:7796 disconnect! new worker:7801 fork
info: [Sun Jun 08 2014 01:30:43 GMT+0000 (UTC)] [master:7794] worker:7797 disconnect! new worker:7807 fork

and it never stops

**Comment by thepeopleseason** [comment]
Have you attempted to run `bower install -f` after the initial install?

**Comment by ArjavS** [comment]
yeah i tried that and the install is successful but i still get the same issue when i run npm

**Comment by ArjavS** [comment]
idk if this helps, but this is an error i get a lot when running npm install
npm WARN package.json expect.js@0.2.0 No repository field.
npm WARN package.json icalendar@0.6.4 No repository field.
npm WARN package.json paypal-ipn@1.0.1 'repositories' (plural) Not supported. Please pick one as the 'repository' field

**Comment by thepeopleseason** [comment]
Those are warnings. You can disregard them for now. 

Things to try: 
1. `npm install` from the /vagrant directory. 
2. `sudo npm install` from the /vagrant directory.
3. `npm install git://github.com/lefnire/swagger-node-express#habitrpg`

**Comment by ArjavS** [comment]
i get the same thing whether i do sudo or not

vagrant@habitrpg:/vagrant$ sudo npm install
npm WARN package.json expect.js@0.2.0 No repository field.
npm WARN package.json icalendar@0.6.4 No repository field.
npm WARN package.json paypal-ipn@1.0.1 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm ERR! error rolling back Error: EPERM, unlink '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco'
npm ERR! error rolling back  swagger-node-express@2.0.0 { [Error: EPERM, unlink '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco' }
npm ERR! Error: EPERM, unlink '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco'
npm ERR!  { [Error: EPERM, unlink '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /vagrant/node_modules/swagger-node-express/node_modules/.bin/docco
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, unlink '/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco'
npm ERR! error rolling back Error: EPERM, unlink '/vagrant/node_modules/habitrpg-shared/node_modules/.bin/cake'
npm ERR! error rolling back  habitrpg-shared@0.0.0 { [Error: EPERM, unlink '/vagrant/node_modules/habitrpg-shared/node_modules/.bin/cake']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: '/vagrant/node_modules/habitrpg-shared/node_modules/.bin/cake' }
npm http GET https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/q
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0

**Comment by thepeopleseason** [comment]
What's the result of the command `ls -l /vagrant/node_modules/swagger-node-express/node_modules/.bin/docco` ?

**Comment by ArjavS** [comment]
lrwxr-xr-x 1 vagrant vagrant 18 Jun  7 16:16 /vagrant/node_modules/swagger-node-express/node_modules/.bin/docco -> ../docco/bin/docco

**Comment by ArjavS** [comment]
the "/vagrant/node_modules/swagger-node-express/node_modules/.bin/docco " and the "../docco/bin/docco" are in red

**Comment by thepeopleseason** [comment]
How about `ls -l /vagrant/node_modules/swagger-node-express/node_modules/docco/bin` ?

**Comment by ArjavS** [comment]
ls: cannot access /vagrant/node_modules/swagger-node-express/node_modules/docco/bin: No such file or directory

**Comment by thepeopleseason** [comment]
Try the following: 

`mkdir /vagrant/node_modules/swagger-node-express/node_modules/docco/bin; touch /vagrant/node_modules/swagger-node-express/node_modules/docco/bin/docco`

Then `npm install` again. 

Honestly, something seriously wonky happened with your Vagrant install during the provisioning step (Do you have enough space on your local disk?). You may be better off restarting the vagrant install by exiting the vm, then issuing:

`vagrant destroy` 
`vagrant up`

**Comment by ArjavS** [comment]
wait its saying i "cannot create directory `/vagrant/node_modules/swagger-node-express/node_modules/docco/bin': No such file or directory" when i run the mkdir

**Comment by thepeopleseason** [comment]
You can either try to create the entire hierarchy that leads up to docco/bin, or restart the vagrant install. I'd say go for the latter. Make sure to pay attention to any specific error messages that happen during provisioning (vagrant up), because something happened which led to your system being in a very unstable state.

**Comment by ArjavS** [comment]
i restarted the vagrant install and "==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
" is in red a few times and basically everything after "installing grunt/bower...." is in red. this happened last time as well. is this the problem?

**Comment by thepeopleseason** [comment]
No, that should be fine. Because there's a number of innocuous errors/warnings, you should take the entire output of the provisioning and add it to a pasting service like dpaste.com and link it here if you continue to have trouble.

**Comment by ArjavS** [comment]
I'm definitely getting a lot of errors during the install
Here is the link http://dpaste.com/3EKN3XF/

**Comment by thepeopleseason** [comment]
Are you sure you have enough space on your local disk for the entire installation? It would be taking up something like 2.5-3.5Gb.

**Comment by ArjavS** [comment]
hmmm thats weird. my habitrpg folder is taking up 300 MB
i have enough space on my local disk though

**Comment by thepeopleseason** [comment]
The habitrpg folder itself won't contain the virtualbox VM, which can be between 2.5-3.5 Gb. The behavior you're describing is that npm is having issues installing node software. The EPERM errors indicate that the folders its trying to create are failing somehow.

**Comment by thepeopleseason** [comment]
@ArjavS Any news on your environment?

**Comment by Alys** [comment]
@ArjavS : If you're still having problems, I recommend rebasing your local habitrpg git clone, destroying any Habit vagrant machines you might already have, and setting a new one up from scratch. There's been site changes which might make it work better. I'm closing this issue since it's been a while since it was updated, but if you're having problems after following that advice, you can comment here and reopen it.
