### ISSUE TITLE
strange pixel on gems icon

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3573]
![screenshot_2014-06-07-22-30-47](https://cloud.githubusercontent.com/assets/6208739/3210339/1c3fe544-eeb5-11e3-843b-98ce1455e484.png)
zoomed in for clarity, it shows up at normal zoom too tho
I'm on mobile Chrome, I don't remember noticing this before. could just be an oddity of how mobile displays the site?

**Comment by casicastiel** [comment]
It shows up on my computer too. Incongruous light pixel near the top left of the gem icon.

![screen shot 2014-06-09 at 8 54 56 am](https://cloud.githubusercontent.com/assets/6208739/3216645/770af862-efd5-11e3-9ec4-f06c16cbc274.png)

**Comment by deilann** [comment]
ty for the report E :)

**Comment by robeden** [comment]
Yay, it has annoyed someone else! I'm fixing this...

**Comment by robeden** [comment]
There is also one non-transparent pixel in the 11:00 position that I'll remove while I'm there. 
![screenshot_6_17_14__10_29_am](https://cloud.githubusercontent.com/assets/1891321/3302451/5881feee-f634-11e3-91e6-7ad184136e54.png)

**Comment by deilann** [comment]
@robeden If it's a problem with the art asset itself, upon fixing it, you will need to [give HabitRPG permissions](https://trello.com/c/eFz57Pqi/24-permissions) to use the art.

**Comment by deilann** [comment]
(Also thnx for working on this!)

**Comment by robeden** [comment]
Ah, thanks for the head's up regarding permission, @deilann. It is a problem with the asset.

**Comment by robeden** [comment]
Pull request submitted: https://github.com/HabitRPG/habitrpg-shared/pull/228

**Comment by deilann** [comment]
Awesome. @lemoness is travelling, but once I have the go-ahead from her,
:thumbsup:

**Comment by deilann** [comment]
Fixed in referenced PR! Thanks @robeden! What's your UUID?

**Comment by robeden** [comment]
9b561b3e-ef0b-4079-9718-c7e5095ff69c

**Comment by robeden** [comment]
Glad to help out! :-)

**Comment by deilann** [comment]
As this is a waffly area, I'll just ask you -- would you prefer the "Blacksmith" (for coding) or the "Artisan" (for art) user title?

**Comment by robeden** [comment]
I can do both, but blacksmith is probably best. Thanks!
