### ISSUE TITLE
class change button is missing

### ISSUE THREAD

**Issue by Eraxxx** [HabitRPG/habitica#3576]
Hello,

like mentioned in the title, my class change button is missing since a really long time. 
Right now I´m a lvl 56 warrior, but I want to change into a wizard. 

My ID is 97f3b0fd-d8f4-4125-a639-035cb232d2bb.

Thanks in advance for help :)

**Comment by deilann** [comment]
Can you post a screen shot?

**Comment by Eraxxx** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/7830292/3211400/3f79427a-ef15-11e3-8c81-ad36c78d4ec7.jpg)

**Comment by deilann** [comment]
You're not a warrior; you actually don't have classes enabled. Go to
Settings > Site and click the button to enable classes.

**Comment by Eraxxx** [comment]
yay, thanks for helping me.
