### ISSUE TITLE
User Dropdown not working

### ISSUE THREAD

**Issue by cgardner** [HabitRPG/habitica#358]
When I click the user button, the menu doesn't drop down like it should.

I looked in the debugger and noticed this message:
Uncaught TypeError: Cannot read property 'contentWindow' of null in show_ads.js:5

The same error shows up in show_ads_impl.js:41

**Comment by lefnire** [comment]
Those errors are ok, that's when the page is reloaded via character reset,
cron, revive, reroll, etc - and google ads doesn't like that. Are you
clicking the arrow to the right of your user name?

**Comment by cgardner** [comment]
I am.  I did a little more digging and it seems that there is a conflict with the chrome extension and some of the "fixes" I made.
