### ISSUE TITLE
Lost account

### ISSUE THREAD

**Issue by KateStrange** [HabitRPG/habitica#3581]
Help, I've lost my account! My android app has been for a while taking me to a level 1 character instead of my actual level 20 character. I thought this was a bug and stopped using the app until I noticed my user ID was different. I guessed that I accidentally created two accounts and tried to figure out what the different username and password was for my level 20 one, but in the process logged out with my level 20 and can't log in! My level 20 still appears on my party members' screens, and the username for both is Aldorel. I've tried all my email addresses for the password recovery but only one works and it's attached to the level 1 character. Logging in with FB creates a new account, so that's not where the other one is coming from.

I've got a lot of dailies so I'm worried I'll die if I can't log in for a few days.

I have my user ID and API copied down from the level 20, will that help?

**Comment by deilann** [comment]
When you next see the level one account, delete it.

**Comment by KateStrange** [comment]
That worked - I've got my real account back on my laptop AND android. Thank you so much!

**Comment by deilann** [comment]
Np :)
