### ISSUE TITLE
Checklist not working correctly

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#3583]
When I try to check some of my checklist tasks off the screen goes to a weird look. Sort of like the edit look. Two days ago it would give me experience and take away the exactly same experience away. This flashed on my screen at same time. I had to leave and forgot about taking pictures. I restarted when I got home and it worked fine yesterday and this morning. This evening it did it again. I took a picture. Not sure it will help though. The screen just looks different. Also the check isn't there when it goes back to normal look. 
It started working right again in a minute or two this time.

![cindy screenshot 2014-06-09 22 17 40](https://cloud.githubusercontent.com/assets/5649804/3225062/27e03a0a-f047-11e3-96fc-533b7f49c12b.png)

**Comment by clmmerrill** [comment]
Update. Doing it again. And I wasn't clicking fast. I remember to take pictures. Second pictures shows taking vitamin unchecked again. I have been refreshing the window and that seems to help. sometimes. 
![cindy 2014-06-11 23 05 47](https://cloud.githubusercontent.com/assets/5649804/3253709/34011c5c-f1df-11e3-91f7-7b3cf0276e0d.png)
![cindy 2 2014-06-11 23 07 44](https://cloud.githubusercontent.com/assets/5649804/3253708/33fc4c0e-f1df-11e3-9292-3ad0d567004d.png)

**Comment by SabreCat** [comment]
Some questions for clarification:
- What do you mean by "goes to a weird look"? I'm not noticing it in the screenshots.
- By any chance did the loading bar proceed really slowly, or any "application error" messages appear?
- What browser are you using, and is this the Beta site or the main Habit site?

**Comment by clmmerrill** [comment]
Chrome is browser.
The beta I can't even load anymore so stopped trying.
Yes the load bar is slow most of the time. I wait until it goes away.
The weird look... well the whole checklist area sort of changes to a white
background instead of the cream. The boxes turn blueish. I'm sorry can't
get a picture of it. It doesn't stay that way long. Just  couple of
seconds.
I do get the application error couple times a week. Usually on same say.

I've been using opera (windows 7 ) last few days.
Still get the check boxes not working.
Haven't seen any application errors yet.
It seems to load much faster than chrome.

I've tried rebooting computer which helps for a bit.
Closing chrome and reopening which helps most of the time for 1 to 2 checks
then doesn't work.
Cindy

I guess it could be server overload but I don't know what times EDT that
time frame is so can't go to a less busy time to test.

**Comment by clmmerrill** [comment]
Ok here are more pictures. I will try to load in order. but named them. I had to take picture with phone since print screen wouldn't show any of it.
This is a normal look
![clear look normal](https://cloud.githubusercontent.com/assets/5649804/3303383/d897ca82-f63e-11e3-95a7-96b7a90ab453.jpg)

It giveth and then taketh. (have to have humor or we could go crazy)
![clicking take vitamin](https://cloud.githubusercontent.com/assets/5649804/3303465/9fe16e40-f63f-11e3-849e-74ef0b31b91f.jpg)

sometimes likes like this (this is what I mean by "edit look"
![after checking looks like sometimes](https://cloud.githubusercontent.com/assets/5649804/3303388/e08f2e4c-f63e-11e3-8118-f76827f0f0a9.jpg)
or with a trash can in picture and the funny cursor shape

![after checking looks like sometimes 2](https://cloud.githubusercontent.com/assets/5649804/3303395/eb8f989a-f63e-11e3-98df-2a74eaa123e3.jpg)
Grainy looking too. Looks more grainy on my phone.
![grainy look after checking](https://cloud.githubusercontent.com/assets/5649804/3303409/1a7e8742-f63f-11e3-8ab2-faee112d1e53.jpg)

And they still aren't checked off. 

I am not sure if this is part of same problem. But most of time when I check off a habit this happens like I clicked twice.

![clicking eat a meal once](https://cloud.githubusercontent.com/assets/5649804/3303488/cb959f2a-f63f-11e3-940a-e5eb0c528494.jpg)

**Comment by SabreCat** [comment]
OK, the weird look is indeed edit mode. You can tell because the main checkbox isn't there anymore, a recent change that helps avoid certain goofs (like a mistake I used to make, changing a Reward's value and clicking to purchase it before the edit was actually saved).

Getting into edit mode by accident, the checkboxes not staying checked, and the double habit scoring make me wonder if maybe there is a common cause of Habit registering double clicks instead of single clicks. Double-clicking a task would put it in edit mode, double-clicking a checklist item would check it and then immediately uncheck it, and double-clicking a Habit would get the consecutive scoring like you see.

The _why_ of that, though, is harder to guess. I assume your pointing device isn't firing bogus double-clicks all over the place, right? xD It sounds like you're running into some severe performance problems, which could be part of it. Do you have a really huge list of tasks? Have you tried "Clear Completed" on the To-Dos list (if you want to keep your completed tasks around, you can export them first)?

**Comment by clmmerrill** [comment]
I did that last week. Took almost everything off and just added basics due to my busy schedule and not wanting to stay in inn or die. I tried to empty completed tasks and they are still there. I just opened habitrpg and looked again one hour later and they are the completes are still there.
I thought about the mouse. I slowed it down, just in case one of my kids sped it up for a game. Still does it. 
I tried tapping the mouse instead of clicking and it seems to work. Not sure what that means. But that is how I will go on. 
Thanks
Cindy

**Comment by Alys** [comment]
@clmmerrill I'm closing this because it looks like you found a workaround, and we haven't had any other reports of it so I think it was a local problem with your mouse, but if you're still having trouble, please do comment here again and we'll try to keep troubleshooting this.

**Comment by clmmerrill** [comment]
I am really glad I was only one having issues. Thanks for looking into it.
I haven't had any trouble lately.

Thanks again,
Cindy

On Sun, Jun 14, 2015 at 2:45 AM, Alys notifications@github.com wrote:

> @clmmerrill https://github.com/clmmerrill I'm closing this because it
> looks like you found a workaround, and we haven't had any other reports of
> it so I think it was a local problem with your mouse, but if you're still
> having trouble, please do comment here again and we'll try to keep
> troubleshooting this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3583#issuecomment-111790754.

## 

Cindy M Merrill
clmmerrill@gmail.com
