### ISSUE TITLE
Class Change did not refund stat points

### ISSUE THREAD

**Issue by Ristance** [HabitRPG/habitica#3587]
Just changed my class from Rogue to Wizard (2014/06/10), class changed okay, got the tour which I dismissed.  However my stat point allocations did not reset as in the past.  My stats are stuck like a rogue instead of being able to reallocate.  Hard refreshed site to ensure wasn't a caching issue.  No change.

**Comment by deilann** [comment]
Can you throw me up a screen shot?

**Comment by Ristance** [comment]
![image](https://cloud.githubusercontent.com/assets/6255590/3232611/ac10d316-f0b5-11e3-8386-64b275d01a8e.png)

**Comment by deilann** [comment]
Weird. What's your User ID?

**Comment by Ristance** [comment]
edf0bcf4-ef43-47a7-b305-e7f36f0a7357

**Comment by deilann** [comment]
I've refunded you the 3 gems; can you try again?

**Comment by Ristance** [comment]
That works, my points have been de-allocated.    Many thanks!
The last time I ended the tour immediately without going through it.  This time I clicked next through it.  Is there any triggers on the tour?

**Comment by deilann** [comment]
I don't think so. I never bother with the tour. :/ No idea why it didn't
work that time.
