### ISSUE TITLE
"Attributes" not displaying in "User"/"Stats"

### ISSUE THREAD

**Issue by Dranian** [HabitRPG/habitica#3590]
Hello,

The "Attributes" section of my character's "Stats" do not seem to be loading.

See here: https://www.dropbox.com/s/52yaye4whk5o33x/Screenshot%202014-06-10%2022.33.50.png.

What would folks recommend?

Thanks so much! :-D

Cheers,
Devin

**Comment by deilann** [comment]
This was fixed here: https://github.com/HabitRPG/habitrpg/pull/3584 but is not yet deployed.

**Comment by lefnire** [comment]
Will deploy no later than 6/14. Hopefully before then
