### ISSUE TITLE
Challenge MIA

### ISSUE THREAD

**Issue by kathatfield** [HabitRPG/habitica#3591]
I'm trying to leave the May Edition of the dungeon slayer challenge, but can't. It doesn't appear at all in the challenge lists, and I didn't get a notice of deletion like last time. Now I'm stuck with dailies and to-dos for a challenge I can't leave. I've cleared cache and cookies and tried chrome. None of it worked.

**Comment by thepeopleseason** [comment]
Try checking off the daily. When you do, you'll get a notification that the challenge has been deleted and give you the red challenge icon to click to remove the tasks.

**Comment by thepeopleseason** [comment]
@kathatfield Did that solve your issue?

**Comment by deilann** [comment]
If that didn't solve your issue, please re-open this ticket. That workaround is pretty solid.
