### ISSUE TITLE
Spelling Errors And Grammatical Issues

### ISSUE THREAD

**Issue by bouncyballboy** [HabitRPG/habitica#3593]
There are many spelling and grammar issues in the original text in quite a few strings. 

Not sure if this is the right place to post them. Or how to fix this type of error (because there are a lot and it's hard to keep track of which ones they are in order to post bug reports or them all, especially more than one in one ticket).

For example:
whyAdsContent1
original content: Habit is an open source project, and can use all the help it can get - consider this a donation to the contributors. You also get 20 Gems from the purchase, which you can use to buy special items.
it should say: Habit is an open source project and can use all the help it can get—consider this a donation to the contributors. You also get 20 Gems from the purchase, which you can use to buy special items.

**Comment by deilann** [comment]
Just post them all in this ticket, and I'll take care of them eventually.

**Comment by TheCodeSinger** [comment]
The word **perception** is misspelled as **percepition** in the tooltip for the basic rogue gear _Oiled Leather_ and _Leather Hood_.

**Comment by deilann** [comment]
Already got that one.

**Comment by TheCodeSinger** [comment]
Great!

**Comment by wuworkshop** [comment]
Isn't this issue very similar to https://github.com/HabitRPG/habitrpg/issues/2582?

**Comment by Alys** [comment]
#### Attention newbie programmers. Here's a summary of the requirements above:

We need someone to modify the text for "whyAdsContent1". Currently it says, _"Habit is an open source project, and can use all the help it can get - consider this a donation to the contributors. You also get 20 Gems from the purchase, which you can use to buy special items."_ The required fix is to remove the first comma and to make the dash wider.

**Comment by crookedneighbor** [comment]
I'd say use an [em dash](http://www.thepunctuationguide.com/em-dash.html) instead of a hyphen.

**Comment by Alys** [comment]
Ha. Never mind. That text string is no longer in use on the site. I'll do a search for other strings that can be deleted and get them all removed together.
