### ISSUE TITLE
All attributes missing from the Stats & Achievements page

### ISSUE THREAD

**Issue by fallerOfFalls** [HabitRPG/habitica#3596]
Does anyone else have this issue?

![habitrpg missing attributes](https://cloud.githubusercontent.com/assets/5463629/3256313/c2e467f8-f216-11e3-8e5c-bca4e49476ca.JPG)

**Comment by deilann** [comment]
Please search before opening new issues and look at closed tickets. This has been fixed, but the fix has not yet hit production.
