### ISSUE TITLE
Call to /user/revive doesn't check if the user is really dead.

### ISSUE THREAD

**Issue by MagicMicky** [HabitRPG/habitica#3599]
I think there's been an ommission when implementing the /user/revive API call as discussed in #3056.
The problem is that when you call /user/revive, you indeed reset the gold to 0, the health to 50 and remove an item, without checking if the user is really dead.
It could end up in bad implementation where you might call the /user/revive API without the user actually being dead.

My opinion would be that it should send back an error if the user isn't dead, or do as it does if the user is indeed dead.

Cheers,

**Comment by MagicMicky** [comment]
Did someone check if it was true ?

**Comment by paglias** [comment]
@MagicMicky you were right, fixing it, see https://github.com/HabitRPG/habitrpg-shared/blob/1e441d6fcd4fe5f512a2435d6f0929d5fdf5f4d2/script/index.coffee#L386

**Comment by paglias** [comment]
typo fixed in https://github.com/HabitRPG/habitrpg-shared/commit/e788872932640310427f468d2ec6afa19d08d842

**Comment by MagicMicky** [comment]
Thanks a lot ! :)
