### ISSUE TITLE
I'm dead, no token left

### ISSUE THREAD

**Issue by Gohan** [HabitRPG/habitica#36]
can't figure out the tokens, I make bad habits click so much time, it show me i have 2 token to reborn.

it is not clear the cost of once reborn, I reborn about 4 or 5 times then totally dead.

Forgot password feature we need it too.

**Comment by lefnire** [comment]
2 tokens to continue, you start with 8 - see [this screenshot](https://www.evernote.com/shard/s17/sh/57bcdab3-c69e-47de-b67c-2e528de6d649/35cefffe06b597b0bbe8498be7f9bca9). You have to buy new tokens when you run out, see [this discussion](https://github.com/lefnire/habitrpg/issues/25). Forgot password [is in progress](%28https://github.com/lefnire/derby-auth/issues/10%29).
