### ISSUE TITLE
Looking for Group option

### ISSUE THREAD

**Issue by rhettoric** [HabitRPG/habitica#360]
I'd love the possibility of creating a community among HabitRPGers.  I'm the only one in my Real Life social circle who really likes habit tracking, but I'd love to be in a party of like-minded individuals for encouragement/motivation.  Is there a message board where HRPGers can meet up and talk about the program and possibly join forces?

If not, maybe an option to make a basic info profile available to the public and note if you are looking for a party to join.

**Comment by lefnire** [comment]
There's the [Reddit group](reddit.com/r/habitrpg), but we're batting around a forum idea currently. Stay tuned

**Comment by rhettoric** [comment]
I didn't know about the subreddit, but I think a message board would be great.  Thanks for looking into this!

**Comment by wc8** [comment]
If you add a chat feature to HabitRPG like facebook and other online games have, you'll need a feature that occasionally mimics [The Ultimate Productivity Blog](http://productiveblog.tumblr.com/) interrupting the users with the message: "You should be working." ;-)

**Comment by StanLindsey** [comment]
Aha genius @wc8 =P 

Also, closing =D
