### ISSUE TITLE
Browser reports HabitRPG as continuously loading

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3603]
As well as the (presumed) load, I can no longer determine whether Habit actually got my updates - and I've taken damage twice in the past fortnight because it lost a few of the dailies I'd recorded done, even before this started, so not knowing whether my reload ever completed is important. 

I imagine it's intentional - I see this problem with many sites - I think it probably relates to some kind of instant update feature. Whatever the feature is, it needs to come without the problem - something I imagine to be impossible using most web dev libraries, judging by the results I wind up using ;-( 

Reporting it anyway in case it's fixable, since it's a big annoyance where I sit. I mostly just avoid sites with this feature.

**Comment by deilann** [comment]
No, I'd imagine this isn't intentional. It happened to me before with a
site update, and @lefnire found and fixed the issue. It's also not
happening to me currently, which leads me to assume it's not intentional.

Can you open your console and see what it's still loading?

**Comment by ArlieS** [comment]
It stopped happening spontaneously, somewhat to my relief. I'll see what I can record if/when it happens again.

**Comment by deilann** [comment]
Awesome, thanks.
