### ISSUE TITLE
sync, custom day start, dailies streak

### ISSUE THREAD

**Issue by paperskye** [HabitRPG/habitica#3604]
I'm not sure if others are experiencing the same issue, but starting yesterday (June 12), I was having problems with the mobile app for Android syncing to my account. I had stayed up late to make sure I finished my dailies (past midnight but my cron is set for 5am). Last night when going to bed, the mobile app correctly listed all daily tasks being done. This morning when I woke up, my party had damage from my "missed" dailies and I noticed that the tasks I had checked off right before going to sleep were checked off when I woke up. 
I know the custom day setting says there are some issues, but I have never experienced any problems before so I am thinking that the syncing issue may have been a factor as well.

Username is "paperskye" and I've got an S4 (SGH-M919) running Android 4.3 and Infamous 9.0 if that helps at all.

I am quite frustrated because I was almost up to my first 21 day streak and my party received 16 damage from the Ghost Stag. I was able to reset the tasks themselves, but I lost the buff and the full daily streak I had going as well as dealt quite a blow to my party.

---

Update:
Sync seems to be working alright today and I fixed my streaks for individual items back to what I estimate they were. I'm not sure if this happened before or after I changed that, but in my stats I have this:
Streak achievements - Has performed 3 21-day streaks on Dailies
17 Perfect Days - Completed all active Dailies on 17 days. With this achievement you get a +level/2 buff to all attributes for the next day.
So, now I have 3 21-streaks for dailies, even though I've only completed 17 perfect days (the 17 is correct).

**Comment by deilann** [comment]
Did you click off the last of your dailies pretty quickly? This like likely
unrelated to CDS.

If you click your tasks rather quickly, you're sending a lot of requests to
the server at once -- which can lead to them failing. Whenever you click,
wait a bit (on browser, specifically wait for the blue bar to finish). It's
always a good practice to refresh/sync before the end of the night, to make
sure everything "stuck."

Also, if you want to fix your streaks, you can open up the task to edit,
and replace them there.

**Comment by deilann** [comment]
Further note: I use [Alys' tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) to check and see if everything's all good. It will show you server-side is showing as incomplete. The tool works fine on mobile as well, so I highly suggest using it as a double-check.

**Comment by paperskye** [comment]
I have noticed that, I usually wait for the check to show before moving to the next one. I don't remember exactly how I did it last night, but the several that I checked off before bed (and my custom day rollover) were checked off this morning. 

I did fix the streaks on my daily tasks themselves, but I believe that doesn't fix the overall streak I had going for achievements. What is strange (I think this only happened within the past couple hours) is that I now have 3 21-day streaks in achievements, but only a total of 17 for my dailies streak.

**Comment by deilann** [comment]
I'm really unsure what you mean by "the overall streak I had going for
achievements" What do you mean a total of 17 for your dailies streak? The
21-day streak achievement is an achievement for getting a 21-day streak on
one specific daily, not for 21 perfect days.

I'm not sure _why_ your tasks didn't sync yesterday, but the result is the
same -- using Alys' tool to check and if anything is considered unchecked
server-side will fix the issue.

**Comment by deilann** [comment]
Ah hah, wait, sorry, I misread your post. Your mobile app was acting as if it was working on a different day. (Sorry, I'm really, really sick right now.)

The stuff about the streaker achievement is correct, though. You could very easily have streaker achievements and less than 21 perfect days. You get 1 streaker achievement for each task that reaches a 21 day streak (or a multiple there of). This actually seems to be a _mobile_ issue, not a site issue. Do you mind posting your issue ticket here: https://github.com/HabitRPG/habitrpg-mobile/issues?state=open

**Comment by deilann** [comment]
I think this is an issue of mobile not parsing CDS correctly. It was putting your tasks on tomorrow, when it should have been putting them on today. So when you went to trigger cron, it went "Welp, these tasks haven't been completed... but they've been completed today!"

**Comment by paperskye** [comment]
Thank you for that link! 
Ahh, I see about the streaks now. I misunderstood how they worked. 
I'll open a ticket there. Thanks for the help!

**Comment by deilann** [comment]
np! Until this is fixed/figured out, you might want to record post-midnight tasks via mobile browser, rather than the app.
