### ISSUE TITLE
Sum of attributes disappeared from Stats page

### ISSUE THREAD

**Issue by kazerniel** [HabitRPG/habitica#3606]
Hi,

Until recently the sum value of attributes adding up from distribution, level, equipment and buffs was shown on the Stats & Achievements page, but a couple days ago it disappeared and only the equipment-given points are shown now. Could you put the sums back? I used them to distribute my new attribute point at levelups.

(if relevant my browser is Firefox 29.0.1)

**Comment by deilann** [comment]
Please search before opening a new ticket and examine both open and closed
tickets. this is a known issue and has been fixed. The fix just has not hit
the site yet. According to Tyler it should be deployed sometime today.

**Comment by deilann** [comment]
Actually it's back now and all of the numbers are showing for me. Can you
show me a screenshot of what you think is missing?

**Comment by kazerniel** [comment]
Sorry, I searched before but for the wrong keywords D:

I just checked and it's showing them again for me too, thanks!

**Comment by deilann** [comment]
It's alright. :)
