### ISSUE TITLE
Clarify Backgrounds as Not Limited Edition

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3610]
I was thinking about direct committing this, but I first wanted to double check and make sure that the backgrounds are going to be sold continually.

Then, I wanted to verify wording choices.

I'd personally do something like "Set 01 - Released June 2014" or simply "Released June 2014"

Both of these should make it very clear that they aren't disappearing, but still remark on when they were released.

cc: @lefnire @lemoness

**Comment by lemoness** [comment]
I am in favor if this - and no, they will stick around! Maybe if we end up
with a hundred we will retire some, but that will be separately announced
and anyway, that is way in the future.

**Comment by deilann** [comment]
@lemoness Do you have a preference for wording?

**Comment by lemoness** [comment]
I like SET 1 as the title, and Released June 2014 as the description.
