### ISSUE TITLE
Header does not fill screen width

### ISSUE THREAD

**Issue by benplumley** [HabitRPG/habitica#3611]
The header (avatar, stat bars, party avatars) does not fill the width of the screen.

How it currently looks:

![](http://i.gyazo.com/781a9cf88de43a79d0ef4a62068d1006.png)

How it should look:

![](http://i.gyazo.com/0f439105e405910c63e40bfd1ea2b5ee.png)

I believe the file at fault is [habitrpg/views/shared/header/header.jade](https://github.com/HabitRPG/habitrpg/blob/9cd42524eccdfa4e6e3c6b7972d8088b2b33e6ad/views/shared/header/header.jade)

**Comment by paglias** [comment]
@benplumley this happens when you're in a party and the header is automatically set to a small size to make space for party members' avatars

**Comment by Gaelan** [comment]
I wonder if this would be fixable with flexbox. It might still need to scroll once a party gets big enough, and I don't know if flexbox supports that.

**Comment by benplumley** [comment]
Yes, I hadn't considered what would happen for large parties. However, large parties would also necessitate a scrollbar in the current system. The minimum size of 175px and stretch to fill screen could be implemented simultaneously, though, if min-width was used as a minimum rather than as an absolute.

**Comment by paglias** [comment]
I added a scrollbar for large parties a few months ago, it should be there
unless it's been overridden by some recent changes
Il 17/giu/2014 16:51 "benplumley" notifications@github.com ha scritto:

**Comment by Alys** [comment]
fixed
