### ISSUE TITLE
'ZZZ''s of Inn-Resting are invisible against some backgrounds

### ISSUE THREAD

**Issue by LB7979** [HabitRPG/habitica#3612]
It's very hard to make out to see who's resting in the Inn with the dark backgrounds. I.e. below: left Party member has the ZZZ's, but because they're black letters it's barely visible on the Forest background.

Suggestion: change the color of the ZZZ letters to one that can be seen on most backgrounds, like red ?

![screenshot 2014-06-15 at 18 03 38](https://cloud.githubusercontent.com/assets/4456266/3281373/79deb28c-f4a7-11e3-9b53-1986e88c63d1.png)

**Comment by benplumley** [comment]
IMO red (or other bright colours) would look tacky, but as there are so few backgrounds, just set the ZZZ colour depending on which background is being used. For light backgrounds, black text, for dark backgrounds, white text.

**Comment by LB7979** [comment]
Yes that'd be even better - black or white depending on background.

**Comment by wc8** [comment]
Or the shadow implemented in Tags. If the :zzz: has a thick shadow in a contrasting color/neutral, code for figuring out if a background is light or dark might not be needed.

**Comment by Alys** [comment]
fixed with recent change to add white shadow to ZZZ
