### ISSUE TITLE
Numeration in Title not working

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#3614]
If you create a task starting with a numeration it only shows "1. " instead of the entered number like "24. "

![Error](https://dl.dropboxusercontent.com/u/605545/Bug/habitrpg_numeration_title.PNG)

**Comment by deilann** [comment]
That's because of markdowns. Put a backslash in front of the task title.

**Comment by negue** [comment]
Then it looks like this:

![](https://dl.dropboxusercontent.com/u/605545/Bug/habitrpg_numeration_title_2.PNG)

**Comment by deilann** [comment]
Apparently it works for chat but not tasks. All I can tell you is that you
need to put something before number period, or use a different system like
drop the period or do No 24. It's an issue with markdown and kind of
unavoidable if we want to be able to format tasks.

**Comment by negue** [comment]
Okay closing as cant be fixed. I will use some other method then. :)

Thanks

**Comment by deilann** [comment]
(Or switch to LaTeX, but only I want and would benefit from that.)
On Jun 15, 2014 2:46 PM, "negue" notifications@github.com wrote:

Then it looks like this:

https://camo.githubusercontent.com/ef325d03130a76fd81f55a77e52eb5907d2f01c5/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3630353534352f4275672f68616269747270675f6e756d65726174696f6e5f7469746c655f322e504e47

**Comment by deilann** [comment]
Five #'s seem to do the trick! Override the coding with more coding. :P

**Comment by negue** [comment]
You are right with the #'s xD nice. Thanks ^^
