### ISSUE TITLE
Password reset not working - no account associated with any of my emails

### ISSUE THREAD

**Issue by PGeezy1991** [HabitRPG/habitica#3616]
Heya,
I have been using Habit RPG on my phone for a bit over a month, perhaps two. Today I signed out of my account and I can't remember my password. I have tried resetting it, but a dialogue box informs me that there is no account associated with any of my emails. This is despite the fact that I have reset my password once already. 

My account name is Pgeezy. 

Can anyone shed any light on this issue?

Cheers

**Comment by lefnire** [comment]
Hey there, looks like it's under _patrickgibb1@Gmail.com_ . Stupidly, our
auth system is case-sensitive (a FIXME in our queue) - so that capital G is
what's getting ya. I can change it if you want, but you can use that for
now to reset your pass.

**Comment by PGeezy1991** [comment]
Heya,

Thanks for your help. Although I can now use the reset password function, the temporary password I am issued is incorrect.. I have tried resetting the password several times and each time it hasn't worked. I have been using my email as it is above. 

Cheers

**Comment by deilann** [comment]
Are you trying to log in with your email or your username? You get your
password reset from your email, but you log in with your username

**Comment by justkristin** [comment]
I am having a similar problem. Only just today registered (not using facebook) and the password I set didn't work (using username JustKristin). Reset the password a number of times, but with no luck.

**Comment by deilann** [comment]
Just a reminder that everything (password, username, and email) are all
case sensitive.

One way you could make sure that you set up with the correct email (case
sensitivity-wise) is to try and register another account. (I'm assuming you
won't lose much if you just registered today.) Normally, that's not what
I'd suggest, but as your account is so new, this should get you help faster
than other troubleshooting might.

**Comment by lefnire** [comment]
just got back to @justkristin, looks like she found our "Duplicate Accounts bug" - which makes sense why the new password isn't working. Might be something worth adding to the wiki, "if you _received_ the forgot-password email, and you copy-pasted both username/email from the message _exactly as is_, and it's still not working - email admin@ since it could be a duplicate accounts issue"

**Comment by deilann** [comment]
Good to know! Thanks Tyler.

**Comment by Alys** [comment]
Duplicate accounts have been removed and prevented in https://github.com/HabitRPG/habitrpg/issues/5126 and we're working on removing case-sensitivity too (not for passwords of course).
