### ISSUE TITLE
To-dos going back to "remaining" when checked from the "completed" list

### ISSUE THREAD

**Issue by LeoBartenev** [HabitRPG/habitica#3617]
Hi everyone,

I wanted to do a second time a challenge including three "To-dos", but because I didn't wanted to quit then join back the challenge, I simply checked my to-dos from the completed list, and then the tasks came back to the "remaining" list.

Thank you for reading!

**Comment by deilann** [comment]
That's expected behavior. You are then unchecking them. Which removes the rewards, and puts the task back in your remaining list.

You could simply create new To-Dos.
