### ISSUE TITLE
Unofficial Android chat client

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#3619]
Hi folks! I've recently started developing apps for Android, and since I am an HabitRPG user I thought about creating a simple chat client for the site. I mean, the idea was to find a way to interact more with my party, but maybe it could be useful for other users (or for you if you're going to make a native Android app).
You can see a screenshot [here](https://dl.dropboxusercontent.com/u/105846917/habitchat.png).

As you can see the app's icon is a slightly modified version of official HabitRPG's icon, that's not involved in any licence thing right? Oh, another thing - I've noticed that in the official client the chat is a subscriber-only feature, I hope my app will not be seen as a way to "cheat" over that!

I opened the issue just to let you know about my little work. If all is ok I will add something in third-party-extensions page in the wiki when the app is ready.

**Comment by deilann** [comment]
From what I've heard:
1. Chat is going to cease being a premium feature, and mobile is going to
   move towards the same monetization structure as the site.
2. According to @veeeeeee, the image is CC-BY-SA, so you're good.

**Comment by veeeeeee** [comment]
Browserquest image license is here: https://github.com/mozilla/BrowserQuest/blob/master/LICENSE

**Comment by Atomk** [comment]
Understood! I'm really glad, I'll start thinking how to make it downlodable with all the license stuff done.
If anybody wants to stay updated, I've set up temporary repository for the project with some information.
I think I can close the issue, thanks a lot for the help!
