### ISSUE TITLE
Can't get the API to work

### ISSUE THREAD

**Issue by elssar** [HabitRPG/habitica#362]
I'm having problems getting the API to work. I get a 200, with the data as html. But when I check my stats on the website, nothing has changed. 

I'm using Python, and the requests library. My code is

```
req= post('https://habitapp.com/v1/users/<user-id>/tasks/<task-name>/up', data={'apiToken': <api-token>}, headers= {'user-agent': 'pyhabit', 'content-type': 'application/json'})
```

The response I get is -

```
>>> req.status_code
200
>>> req.headers
{'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'expires': 'Sun, 17 Feb 2013 13:07:37 GMT', 'vary': 'Accept-Encoding', 'server': 'nginx/1.2.6', 'last-modified': 'Sat, 09 Feb 2013 00:07:26 GMT', 'connection': 'keep-alive', 'etag': '"0-1360368446000"', 'cache-control': 'public, max-age=604800', 'date': 'Sun, 10 Feb 2013 13:07:37 GMT', 'x-powered-by': 'Express', 'content-type': 'text/html; charset=UTF-8'}
```

I thought it might be because task name, and task-id are different, so after a digging around, I found some habit-ids and tried using them in place of task name - didn't work either.

**Comment by lefnire** [comment]
oh wow. yeah, everything looks right - it's definitely taskId instead of taskName (but if the task id doesn't exist in the system, it will create a new task with that id). I'll check into this

**Comment by elssar** [comment]
Oops, I didn't convert my payload to json.
I thought requests would automatically do that. Was wrong. Now it works.

**Comment by switz** [comment]
Well this is still an issue. It shouldn't return 200 for a malformed request. Looking into this.

**Comment by lefnire** [comment]
had to enforce application/Json for api requests to bypass splash.html
