### ISSUE TITLE
Error 500 before I can log in- related to backgrounds

### ISSUE THREAD

**Issue by rcichy** [HabitRPG/habitica#3620]
I'm getting this error http://pastebin.com/Nj2v8H0d before I can log into local instance. I updated code to newest revision. It's some how related to backgrounds. Any ideas? Am I doing something wrong?

**Comment by paglias** [comment]
@yafinee try updating your habitrpg-shared version with `npm install`

**Comment by rcichy** [comment]
It works. Thank you.
