### ISSUE TITLE
/user/tags API is not RESTful

### ISSUE THREAD

**Issue by kusold** [HabitRPG/habitica#3621]
POST /user/tags should return the newly created Tag object, not the list of all the tags.

There should be two more routes:
GET /user/tags/:id to only get the tag for the id
GET /user/tags to get a list of all the tags. Currently the POST /user/tags is taking this responsibility

The GETs could be sneaked into the API without any issues, but the change for POST would be breaking and better suited for v3.
##

**Comment by lefnire** [comment]
TMK there's a few more bits that aren't restful. A v3 would be very useful. I'm going to be migrating user objects from tasks stored as arrays to stored as objects, and that will be on v3. I'll probably not document v3 until we get more stuff in there such as a restful API

**Comment by kusold** [comment]
I'll try and add the ones that I find. I only discovered the tag ones because I'm building out a [npm package](https://www.npmjs.org/package/habitrpg-api) for the API while also trying to tackle ToDoist syncing.

**Comment by me-and** [comment]
You can also do a GET `/user` to pick up a list of tags, which at least doesn't require POSTing if you want  the tag list without changing state anywhere.

**Comment by librarianmage** [comment]
Is this finished?

**Comment by Alys** [comment]
Closing this now that API v3 has been released.
