### ISSUE TITLE
XP bar overflow

### ISSUE THREAD

**Issue by DanielAW** [HabitRPG/habitica#3624]
I recently finished a **quest** and received the XP for it. I received enough XP for a level up, but I dont get the level up. Instead the XP bar got an overflow ;-) 

![lvl_up](https://cloud.githubusercontent.com/assets/2500905/3312497/d1bc9e42-f6d2-11e3-9dcf-5e37721a5ea6.png)

When I finished the next Daily I got the level up and the XP bar was 'normal' again.

**Comment by deilann** [comment]
Please search before opening new tickets. (Usually something not super specific. Frex, to find the proper ticket, I searched "quest xp" and immediately found the proper ticket.)

Here's the ticket: https://github.com/HabitRPG/habitrpg/issues/2433

**Comment by DanielAW** [comment]
Sorry, I searched not hard enought. Thanks for the tip
