### ISSUE TITLE
Tavern message question

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3627]
##### Can this be done?
- [ ] Daniel's Message changes if the user is Checked-In
- [x] link e.g. to Back Corner guild and Github.

If so, I'd like to change it so the following is displayed:

| Tavern Message | Inn Message |
| --- | --- |
| Welcome to the Tavern! Stay a while and meet the locals. Want to engage in a long discussion? There are bigger tables in the [Back Corner](https://habitrpg.com/#/options/groups/guilds/426c2c1a-eed0-4997-9b73-d30fc1397688). I can't follow bugs in my Tavern, it's best to take your specimens to the blacksmiths in the [Github Forge](https://github.com/HabitRPG/habitrpg/issues?labels=priority+-+important). If you need a vacation, or a place to rest during illness, I'll set you up in the Inn, which protects you from some danger. | How's your stay in the Inn? Your daily list is frozen, your checkmarks won't be processed and reset until the day after you check out. Be careful, if your party's in a Boss Battle, their misses will hurt you, and you won't hurt the boss. Ready to leave? |
| {Rest in the Inn button} | {Check out of the Inn button} |
- [ ] If not, I'd still use the Tavern message proposed and change the blue message afterward to:

> Staying in the inn freezes the checkmarks in your Dailies list. They won't be processed for points or cleared until tomorrow (the day after the day you check out). Beware: if you are in a Battle, the Boss will strike you for your fellow party members' mistakes!

**Comment by lemoness** [comment]
I like both of these new messages!

**Comment by lefnire** [comment]
I dig

**Comment by deilann** [comment]
It would be really cool if moderators had the power to change the messages
in the Tavern through the site, like guild leaders with guilds.

**Comment by lemoness** [comment]
I'd rather it didn't change frequently, actually. Better to be pretty
consistent. But this is a solid update.

**Comment by deilann** [comment]
@lemoness Not so it would change frequently, but so it could be modified
more rapidly, need be.

**Comment by deilann** [comment]
Although, now that I think about it, it wouldn't work with i18n.

**Comment by wc8** [comment]
I actually peered at some of the Tavern code, but couldn't quite find the right place to update this let alone where/how to set the variable. Is this entry level coding or should I remove that label?

**Comment by deilann** [comment]
It is entry level coding. The strings in the shared repo will need to be
changed and ones created specifically for the links.

**Comment by lefnire** [comment]
gimme one sec, I need to cherry-pick a commit before this. brb

**Comment by wc8** [comment]
@deilann thanks! I see that now. If it were just changing the strings, I'd probably be able to do this, but the strings for the links would require more study.

Don't worry, @lefnire I'm not doing anything, just learning a teeny bit.

**Comment by lefnire** [comment]
nm, my changes won't cause conflicts. Edit away!

**Comment by wc8** [comment]
OK, I'll take a stab at the basic message update. It'll still need links, at the least.

**Comment by deilann** [comment]
So, to make it easy to add the links in, you'll want a string for the
message up until the link, a string for the link, and then a string for the
message up until the next link, a string for that link, and then a string
for the rest of the message. :) If you look at some of the jade files with
links, you should get an idea of how to format it.

I think it's awesome that you're doing this.

**Comment by wc8** [comment]
I think I figured it out. Thanks for your help. I'm going to break this into 2 parts. Part 1 I think I might be able to do... 3 steps. Part 2 might be beyond me. 
- [x] part 1: update blue inn message and Tavern message with links
- [ ] part 2: figure out how to do an if statement so that daniel's text changes based on whether one's staying in the inn or not, rather than having an extra blue message below.

**Comment by deilann** [comment]
I think that would be a lot cleaner!

**Comment by wc8** [comment]
- [x] Tavern messages https://github.com/HabitRPG/habitrpg-shared/pull/232
- [ ] https://github.com/HabitRPG/habitrpg/commit/339dad216559fb50772c83bc30ffb00bb7e18d56 edit was supposed to be a pull request but appears to have updated directly? I think that will cause problems without pull 232 UPDATE: reverted for now.

**Comment by crookedneighbor** [comment]
@lemoness Can we get a decision on the final message for the checked in the inn version of Daniel's message and the not checked in version? 

I'm pretty sure I know how to do that, just need the text for the update.

**Comment by deilann** [comment]
@crookedneighbor Did you mean to post that in this very old ticket or the
newer one?

**Comment by crookedneighbor** [comment]
I meant to post in this one, though I see that they are related. Linking #5128 to this issue.

This one is about having the text change based on whether or not the user is currently resting in the inn. I'm going to close this one and add a comment to the new one you made.

**Comment by deilann** [comment]
The inn text does change whether or not you are resting in the inn.

**Comment by crookedneighbor** [comment]
The text in the button does. The text around the button does not.

**Comment by deilann** [comment]
I could have sworn it did. Huh.

**Comment by crookedneighbor** [comment]
If it does, it's too subtle a change for me to notice.

**Comment by deilann** [comment]
I just put it side by side. I could have sworn though, that we implemented
changing text at one point. I feel like I remember seeing it.
