### ISSUE TITLE
Food tray gets silly big

### ISSUE THREAD

**Issue by robeden** [HabitRPG/habitica#3628]
The food tray is currently configured to be 30% in the CSS. This generally works, but it means it keeps growing beyond what's necessary and makes you have to size the window really large in order to prevent it covering pets.

Here's a screenshot of how wide I have to make it in order not to cover items:
![screen shot 2014-06-19 at 3 57 40 pm](https://cloud.githubusercontent.com/assets/1891321/3333546/ccd76268-f7f4-11e3-880e-e093bda544f6.png)
(NOTE: These are scaled. View full size for the full effect.)

I propose we cap the max width to something reasonable (like "15em"), which is demonstrated in this screenshot:
![screen shot 2014-06-19 at 3 57 59 pm](https://cloud.githubusercontent.com/assets/1891321/3333559/f6c8e1c8-f7f4-11e3-81f0-8ddf0aabfef3.png)

That's a savings of about 150 pixels and makes the window size much nicer, IMO.

**Comment by deilann** [comment]
:thumbsup: I keep thinking about this, but never mention it.

**Comment by robeden** [comment]
I'll throw together a pull request shortly.

**Comment by deilann** [comment]
Hahaha yay! There's nothing better than when an issue is posted and someone says they can fix it. :)

**Comment by robeden** [comment]
Here ya go: https://github.com/HabitRPG/habitrpg/pull/3629

**Comment by deilann** [comment]
Okay, this is definitely way to _small_ now. I can only have one column of food.

**Comment by robeden** [comment]
Huh, that's odd. It was more than enough for two when I tested. Let me look at what units are used elsewhere and see if we have an em/pixel conversion difference.

I'll get you something tomorrow.

**Comment by veeeeeee** [comment]
Oh good, I'm not the only person with this problem.

**Comment by robeden** [comment]
@deilann & @veeeeeee : What OS and browser are you guys using? Looks like it's working fine on Mac under Chrome, Safari and Firefox. I'll test under Windows in a bit.

Side question: what's the typical deployment procedure? I sort of expected this to show up on the beta site (beta.habitrpg.com is a thing, right?) a bit before going live.

**Comment by paglias** [comment]
I get it like this, a bit too small but that's not a big problem for me. Previously it was perfect, starting just after the pets ended.

I'm on Chrome latest version on Ubuntu 14.04 ![selezione_074](https://cloud.githubusercontent.com/assets/589911/3349077/2af1fdc4-f951-11e3-994d-ba536a39b02b.png)

The deployment procedure isn't "fixed", big changes go through beta, smaller ones directly to prod.

**Comment by veeeeeee** [comment]
![screenshot 2014-06-21 10 44 49](https://cloud.githubusercontent.com/assets/5608909/3349560/ffc24a3a-f96b-11e3-9f1a-a6f97e4ecef7.png)
Chrome, Windows 7.

**Comment by deilann** [comment]
Also on Chrome, Windows 7. I could hop onto Ubuntu 12.04 and poke at it
with FF.

**Comment by paglias** [comment]
Just checked with FF and same as chrome (screenshot above)

2014-06-21 19:48 GMT+02:00 deilann notifications@github.com:

> Also on Chrome, Windows 7. I could hop onto Ubuntu 12.04 and poke at it
> with FF.
> 
> On Sat, Jun 21, 2014 at 10:47 AM, veeeeeee notifications@github.com
> wrote:
> 
> > [image: screenshot 2014-06-21 10 44 49]
> > <
> > https://cloud.githubusercontent.com/assets/5608909/3349560/ffc24a3a-f96b-11e3-9f1a-a6f97e4ecef7.png>
> > 
> > Chrome, Windows 7.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/3628#issuecomment-46760072.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3628#issuecomment-46760096.

## 

Matteo Pagliazzi - paglias.net

**Comment by robeden** [comment]
Ahhh... thanks. The screenshot helped. The issue is that there's room until a scrollbar is needed. I'd tried Safari, Chrome, Firefox on Mac, Windows, Linux and was starting to think I must be going crazy to not see the issue. :-)

**Comment by deilann** [comment]
Maybe then just make it a touch wider!

**Comment by robeden** [comment]
Yup, that'll be the solution. I just wanted to make sure I was seeing the original problem so I could properly test.

**Comment by robeden** [comment]
So far it looks like changing from 15em to 16em will be sufficient. If anyone wants to test, here are the steps for Chrome:

![chrome_test_steps](https://cloud.githubusercontent.com/assets/1891321/3349827/503b9f2e-f97c-11e3-9345-789b3c4729ea.png)

Testing in Firefox is basically the same.

I'll test the remaining platforms and submit a pull request shortly.

**Comment by deilann** [comment]
That fixes it for me!

**Comment by robeden** [comment]
Looks like it needs 17em. That pesky Windows. Ok, building PR...

**Comment by robeden** [comment]
Ok, there's the PR.

Sorry for the bad testing, all. I'll keep more food in my inventory from now on! :-)
