### ISSUE TITLE
Gems.

### ISSUE THREAD

**Issue by crimsonpanda** [HabitRPG/habitica#3630]
I bought some gems near the end of last month and when I got my bank statement it said that i had been charged twice. Is there anyway i can just get credited the 20 gems from the extra charge?

**Comment by deilann** [comment]
@crimsonpanda Can you email admin@habitrpg.com about this instead?

**Comment by deilann** [comment]
(Basically, Github isn't probably the best place, as you don't want to share your bank info publicly, and email will allow you take care of it privately.)
