### ISSUE TITLE
checkmarks on dailes do not refresh

### ISSUE THREAD

**Issue by sharan01** [HabitRPG/habitica#3631]
day before yesterday i checked some of dailes
and yesteday those check marks were still there
and today also
shouldn't check marks be  daily refreshed ?

**Comment by thepeopleseason** [comment]
They should be. Sometimes there's an intermittent issue and they don't get unchecked (usually when the user logs in after midnight but before a custom day start). In this case, the usual recommended action is to make a note of streak values, GP, and XP, then uncheck those dailies. Use "Fix Character Values in the settings screen to reset GP and XP to their correct levels, edit the streaks in the dailes, then re-check the dailies for today.

**Comment by thepeopleseason** [comment]
Closing as a duplicate (#1057)
