### ISSUE TITLE
Level 120 - Changed to Warrior, Disabled Spells and Gear

### ISSUE THREAD

**Issue by MANDRO1D** [HabitRPG/habitica#3632]
I'm a level 120 Mage and I used the reallocate option (3 Gems) to switch to Warrior so I could grab the new loot. 

Now, my character no longer has the ability to cast spells. I can't view the Gear tab within Inventory. The option to change classes within the User menu is no longer visible. It's as though the system is treating me as a level 1 user, although I'm level 120+. 

Please advise. Thanks!

**Comment by deilann** [comment]
Sounds like instead of switching to warrior, you actually opted out of classes. Go to Settings > Site and click "Enable Class System"

**Comment by MANDRO1D** [comment]
You're so right. Thank you immensely for the quick response. User error alert!

**Comment by deilann** [comment]
No problem! :)
