### ISSUE TITLE
Request: show date/time button was last pressed as a mouseover

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3634]
For habits and rewards, I sometimes forget if I already pressed the button. I sometimes use the export file to check, but that's not too helpful (FYI I do one habit twice a day). Would it be possible to have a mouseover or something that shows you when you last pressed the button?

**Comment by deilann** [comment]
Feature requests actually go on [Trello](trello.com/b/EpoYEYod/habitrpg). I know there's a request to show a counter already, and that's something I want to code, but need to have time.

**Comment by ghost** [comment]
ok thanks for that! :)
