### ISSUE TITLE
Rebirth causes undefined stats, can't get exp or gold from tasks

### ISSUE THREAD

**Issue by Earthstar** [HabitRPG/habitica#3637]
I just rebirthed by purchasing the Orb of Rebirth. Now, all my stats are "undefined" and I can't earn gold or exp from tasks.

![habitrpg bug undefined stats](https://cloud.githubusercontent.com/assets/2675982/3349564/36935324-f96c-11e3-892f-7cc2119226c3.png)

My uuid is 0b0a8159-91bc-4741-ad9d-c378b7d3b950

**Comment by deilann** [comment]
You look okay from here. All your attributes show 0, not undefined. Can you
do a hard refresh or clear your cache or log out and log back in again?

**Comment by Earthstar** [comment]
Okay, doing a hard refresh worked. Thanks! I was getting worried there.

**Comment by deilann** [comment]
No problem. :)
