### ISSUE TITLE
June Mystery Item missing

### ISSUE THREAD

**Issue by judgebunnie** [HabitRPG/habitica#3639]
So I've actually checked and I can't find anyone else who is having this issue.

So I've been subscribed for several months and I've gotten the mystery item every month so far except for the one that just was revealed today for June. I've checked and I am still subscribed.

Is there anyway this can be resolved?

**Comment by deilann** [comment]
June's mystery item hasn't been released yet, as far as I know.

**Comment by Alys** [comment]
The next Mystery Item release date is always documented here: http://habitrpg.wikia.com/wiki/Mystery_Item (as soon as a Bailey announcement lets us know when the date will be, which is usually several weeks before the date).
