### ISSUE TITLE
Extra "No Helm" equipment in Stats page

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3640]
Somehow, I'm both equipping "No Helm" and the Pirate Hat:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3350576/f6616270-f9be-11e3-9bed-b4e014595212.png)

I've tried a few other hats, and the "No Helm" still appears.

**Comment by Alys** [comment]
This is the culprit:

"back":{"base":{"0":{"text":"No Helm","notes":"No headgear.","value":0,"type":"b
ack","key":"back_base_0","klass":"base","index":"0","str":0,"int":0,"per":0,"con
":0}}

I.e., the "base" back accessory has been mis-labelled "No Helm" and "No headgear".

EDIT:
For consistency with "No Body Accessory", the name should probably be "No Back Accessory".

**Comment by Alys** [comment]
@SabreCat (or anyone else with awesome admin powers), I believe this can be closed. It looks fixed to me. :)

**Comment by SabreCat** [comment]
Ah, aye!
