### ISSUE TITLE
Winter Event equipment not granting Class Equip bonuses

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3641]
A while back, the special event gear was changed to grant the +50% bonus for equipping class-appropriate pieces. However, this does not appear to be happening for (at least) the off-hand Winter Event rogue weapon:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3350585/0b5619a4-f9c0-11e3-90f7-4fac20eab5ec.png)

Note from the screenshot that the cat suit and the pirate hat grant their +50% bonus to Perception, while Strength gets no benefit from the ski pole.

I don't have the Gold yet to test whether this affects other Rogue "shields" or Rogue main hand weapons (my main hand ski pole is broken, haha), event or otherwise. Will check back in once I've bought that Pirate Cutlass or whatever :P

**Comment by Alys** [comment]
I've just looked through the json "content" data and it will be a problem for all the "Limited Edition 2013 Winter Gear". Every item with "event":{"start":"2013-12-31","end":"2014-02-01"} is missing the specialClass attribute (e.g., "specialClass":"rogue"). 

For example, this item from a later event DOES have that attribute:
"springRogue":{"event":{"start":"2014-03-21","end":"2014-05-01"},"specialClass":"rogue","text":"Hook Claws","notes":"Great for scaling tall buildings, and also for shredding carpets. Adds 8 points to Strength. Limited Edition 2014 Spring Gear.","value":80,"str":8,"type":"weapon","key":"weapon_special_springRogue","klass":"special","index":"springRogue","int":0,"per":0,"con":0},

but this winter 2013 item does NOT:
"candycane":{"event":{"start":"2013-12-31","end":"2014-02-01"},"twoHanded":true,"text":"Candy Cane Staff","notes":"Limited Edition 2013 Winter Gear! A powerful mage's staff. Powerfully DELICIOUS, we mean! Two-handed weapon. Increases Intelligence by 15 and Strength by 7.","int":15,"per":7,"value":160,"type":"weapon","key":"weapon_special_candycane","klass":"special","index":"candycane","str":0,"con":0},

**Comment by SabreCat** [comment]
Thanks for the investigation! Updated issue title.

**Comment by deilann** [comment]
I'm gonna go fix this.
