### ISSUE TITLE
Extreme damage to bosses

### ISSUE THREAD

**Issue by Rakudajin** [HabitRPG/habitica#3642]
I deal too much damage to bosses. Kill them in one hit.

At first I noticed it, when finished a To-Do task with a huge check-list, which I was doing for 2 months. I thought completing such a huge task could be a reson for ~300HP damage.

But this time I definitely haven't accomplished something as big. So it's probably a bag...

![image](https://cloud.githubusercontent.com/assets/7362022/3352627/ecf27aba-fa51-11e3-84ec-7e8549538e49.png)

**Comment by deilann** [comment]
Not a bug. You're a mage. if you use Burst of Flames a lot, you'll deal a lot of boss damage.
