### ISSUE TITLE
Forces of evil took 20 health points from my character for nothing

### ISSUE THREAD

**Issue by Sapsality** [HabitRPG/habitica#3643]
Hey there, a very unpleasant thingy has just happened
I simply refreshed habbitrpg page and 20 h.p were gone to the wind. And I saw a notification that 20 h.p had been taken away.

Thing is I had'nt failed any dailies, it's not even evening in my town yet.

AND all my dailies became unmarked as if a new day had started.
It happened right after I installed habbitrpg app on my phone.
Date and time are set right there, I checked.

I already dealt with the problem by marking every daily done in case it happens again today (i only got 8 h.p left), but it would be really great if you fixed it somehow and told me what the problem was so I wouldn't freak out that it can happen again.

Please let me know why that happened so I can avoid having this problem again before u fix it. 
Have a nice day

P.S Nickname in habitrpg is Sapsality

**Comment by wc8** [comment]
If you're not questing with a party, it could be an odd sync issue. You can easily correct the problem with the Fix Character Values button in [Site Settings](https://habitrpg.com/#/options/settings/settings). 

I recommend at the end of the night, after your last action, pressing the sync button and waiting for the page fully to load, and/or refreshing habitrpg one last time. This way you'll see exactly what's registered for the night.

**Comment by Sapsality** [comment]
Thank you, kind sir
You literally saved my day out there :)
