### ISSUE TITLE
Can't wear eyepatch and cat ears at the same time?

### ISSUE THREAD

**Issue by diyadas** [HabitRPG/habitica#3645]
I can wear my cat ears and pirate hat the same time, but I can't wear the eyepatch and the cat ears together. I think the eyepatch and the cat ears might be in the same category (I'm wearing them as a costume), so that might be the cause - but in terms of positioning, I think both could be worn at the same time.

edit: Alys mentioned that they're both head accessories. I'd like to put this up as a suggestion, I guess.

**Comment by rcichy** [comment]
Yes, you cannot wear two head accessories at the same time.

**Comment by deilann** [comment]
Yes, the cat ears and the eye patch are both accessories. The pirate hat is
a helm.

**Comment by SabreCat** [comment]
I suppose we could create an eyewear slot?

**Comment by deilann** [comment]
As I'd like to eventually see glasses and sunglasses, that would be awesome.

**Comment by Alys** [comment]
It's been decided that eyepatches and the Unconventional Armour masks will be converted to a new type of gear, which will allow them to be worn at the same time as head accessories. It's not yet known when this will be done. I'll be doing it.

**Comment by Alys** [comment]
Pull Requests submitted:
https://github.com/HabitRPG/habitrpg/pull/3955
https://github.com/HabitRPG/habitrpg-shared/pull/291

**Comment by SabreCat** [comment]
And merged!
