### ISSUE TITLE
W3C Validation of front page

### ISSUE THREAD

**Issue by ArloL** [HabitRPG/habitica#3648]
When [validating the front page](http://validator.w3.org/check?uri=https%3A%2F%2Fhabitrpg.com%2Fstatic%2Ffront&charset=%28detect+automatically%29&doctype=Inline&group=0) there are a few issues that occur:
- [charset UTF-8 after the first 512 bytes](https://code.google.com/p/doctype-mirror/wiki/MetaCharsetAttribute)
- footer tag not closed
- px values in html attributes width/height
- some css hints for iframes
##

**Comment by librarianmage** [comment]
@Alys @lemoness @crookedneighbor I can try going through this

**Comment by paglias** [comment]
If someone wants to try to do this keep in mind that it's not super important unless it causes issues with rendering and that using a client side framework a lot of HTML code is not present in the source code but in template tags and thus not validated

**Comment by librarianmage** [comment]
nvm, then 😛

**Comment by librarianmage** [comment]
@paglias Should it also be put on hold for the website redesign?

**Comment by paglias** [comment]
@MathWhiz yeah, let's revisit this after/during the redesign

**Comment by lemoness** [comment]
We've redesigned the front page. Is this still a problem?

**Comment by librarianmage** [comment]
[It appears to be pretty good](
https://validator.w3.org/nu/?doc=https%3A%2F%2Fhabitica.com%2F), except for
one error.

**Comment by paglias** [comment]
I don't think this makes sense anymore as the HTML is just a few lines, the rest comes from Vue.js so it's not analyzed by the W3C validation
