### ISSUE TITLE
Link User Display Tool from HabitRPG

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3649]
I think we should link to Alys' tool from somewhere on HabitRPG proper. Perhaps in Settings? It's extremely useful, and I want more users to know that they can access it.

**Comment by rcichy** [comment]
Or maybe integrate/implement some functionalities of UDT in HRPG?

**Comment by wc8** [comment]
I suggest under Resources, @lemoness 
I think it would be a fairly simple matter of:
- [x] add to https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/groups.json
  `"dataTool": "Data Display Tool",`
- [x] add to https://github.com/HabitRPG/habitrpg/blob/develop/views/options/social/tavern.jade under \Resources table section with linebreaks:

`tr
              td
                a(target='_blank', href='https://oldgods.net/habitrpg/habitrpg_user_data_display.html')=env.t('dataTool')`

@yafinee I'd be glad if the functions were included.

**Comment by wc8** [comment]
OK. That might be it.

**Comment by SabreCat** [comment]
@yafinee: Long term, it'd be great to integrate some of those tools into the site; many of the features there are quick-and-dirty versions of things outstanding on Trello (e.g. the "you're going to die" warning). But a link will be handy in the meantime!

**Comment by deilann** [comment]
All done!
