### ISSUE TITLE
Real life rewards and in-game rewards compete for the same resources

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#3650]
With the current setup a person has to sacrifice in-game rewards for real world rewards and vice versa.  I'm sure that a lot of people find ways to cope with this, and make it work, but I think for most people it just cripples HabitRPG's effectiveness as a motivational/behavior modification tool.

For this reason, I think there should be a new currency that mirrors Gold.  Something like "Reward Points" (Rew Ps) or "Credits".  It could also, but not necessarily, be immune to death, as a motivation to continue using habitrpg even when you're dying frequently.

I know that github isn't the place for features, but I don't see this as a feature, I see it as a balancing issue.
#3355

**Comment by deilann** [comment]
As you stated, Github isn't the place for features. This is often discussed on Trello. You can look for it there.

**Comment by fragmental** [comment]
Again I say, I don't think it's a feature, I think it's a game balance issue.  A very serious one.

If it had a trello card, I would happily move discussion there, but otherwise it just gets lost in the noise of feature requests.

**Comment by deilann** [comment]
And there are some game balance issues that are discussed on Trello first,
not Github. The solution to "no one's hearing me" is not to post it to
Github instead.

There is a lot that would have to be planned in order to do this. It
wouldn't just be balancing or tweaking a skill. It is a new feature. And as
such, should not be discussed on Github, and instead on Trello.

**Comment by SabreCat** [comment]
Yeah, this is way too philosophical a question for a GitHub ticket. If you aren't fond of Trello, I'd suggest bringing it up on one of the social media sites/Guilds/forums.

**Comment by fragmental** [comment]
Is the "Comment Here with NEW Requests" the only place for discussion?  Is it the best place for discussion?

**Comment by SabreCat** [comment]
That's the place if there's not an existing card for your idea. Otherwise, there's G+, Facebook, Guilds, and wiki forums. We have no shortage of discussion spaces, but GitHub is not the right choice for this one.

**Comment by fragmental** [comment]
@deilann @SabreCat From a game design perspective, I still think it qualifies as a game balance issue.  But yes, you are absolutely correct;  from a programming perspective, it is a new feature, because it does not currently exist within the code.   I apologize for posting to the wrong place.

**Comment by deilann** [comment]
A good way to look at it is Github is where programming gets done. Trello
is where game design gets done.

**Comment by fragmental** [comment]
Thank you.
