### ISSUE TITLE
Email notifications if a party member proposes a quest?

### ISSUE THREAD

**Issue by Cassolotl** [HabitRPG/habitica#3654]
Hello!

There are some members of our party who like to join in on quests but rarely participate socially otherwise. So they like to quest, but they don't notice when a quest has been proposed because they're not regularly checking the Party tab.

I was just thinking it would be cool if one could check a box in the settings called "email me when someone in my party proposes a quest" - just to make sure we don't start without someone who wants to join in.

**Comment by deilann** [comment]
Email notifications are desired, but are currently out of HabitRPG's budget.

Also, feature requests tend to go on [Trello](trello.com/b/EpoYEYod/habitrpg), not on Github. I believe there is a card about email notifications.

Also, quests show up as a modal whilst you're browsing the site. So you don't have to go to the party tab to see that a quest has been initiated. Basically, if they are using the site, and logging in every day, they should see the quest.

**Comment by Cassolotl** [comment]
Useful! Thanks. :)

**Comment by deilann** [comment]
np! :)

A good guideline is that people who have not accepted the quest within 24 hours of it being initiated most likely didn't sign in that day. (And the last thing you want is to quest with someone who only signs in every few days... because the damage stacks each day and you'll get it in one big whallop!!!)

**Comment by JennaMalkin** [comment]
@Lottiotta - I've asked for a popup to appear on HabitRPG when a quest launches here: https://trello.com/c/VPPjVRlF

It'd help parties where there might be a delay between the person sending the quest and everyone accepting.
