### ISSUE TITLE
I am suddenly very rich.

### ISSUE THREAD

**Issue by Feulpelz** [HabitRPG/habitica#3655]
Trying to buy my self created rewards has ended up creating enormous piles of gold and experience. I should have had about 230 gold, I was trying to buy a reward for 125 gold, I know have 4.6 K.
My experience was about 50, but is now 4,560 XP. 
I didn't initially notice, but when I hover over rewards they are surrounded by a green box similar to when casting a skill on a task.
My user ID is Faulpelz. 3e2a1f32-c11e-4872-b2c9-e2dbbf3645e2
![habit_bug](https://cloud.githubusercontent.com/assets/7311298/3390972/33130e6a-fca5-11e3-9a12-de6c9593f368.png)

**Comment by Feulpelz** [comment]
Having logged out and in again, I am now poor once again. It was clearly just a dream.

**Comment by deilann** [comment]
If it happens again, let us know.
