### ISSUE TITLE
HabitRPG.com won't sync with mobile app

### ISSUE THREAD

**Issue by reederda** [HabitRPG/habitica#3656]
I've noticed that signing into the mobile app on an account gives a different user id and API code than when logging into the same account on the website.

**Comment by deilann** [comment]
That means you have two accounts with the same credentials. When you see
the undesired account, delete it. Should fix your problems. You can also
force mobile into the right account by logging in with your user id and API
token.

**Comment by reederda** [comment]
Ah, I see now. Issue solved. Thanks for the tip.
