### ISSUE TITLE
Disappearing Checklists

### ISSUE THREAD

**Issue by morallyambiguous** [HabitRPG/habitica#3657]
All of my habits, dailies, and all but four of my to-dos have disappeared from the website, they are still viewable on the iPhone app, but I can't pull them up on the website.

**Comment by deilann** [comment]
Click the "clear" button by the tags.

You probably have a tag enabled.

On Wed, Jun 25, 2014 at 11:05 PM, morallyambiguous <notifications@github.com

**Comment by Alys** [comment]
morallyambiguous, did that fix the problem? Let us know so that we can either investigate further or close this issue.

**Comment by morallyambiguous** [comment]
It did fix the problem but it keeps happening every time I pull up the site even though none of the tags are highlighted. I do just have to press clear, but still.

**Comment by Alys** [comment]
Clear your browser's cache. That should fix the issue.

**Comment by morallyambiguous** [comment]
Thanks it's fixed now!
