### ISSUE TITLE
Buying second pirate cutlass while 2 weapons equipped

### ISSUE THREAD

**Issue by unrelatedwaffle** [HabitRPG/habitica#3659]
I bought a second pirate cutlass for right hand while equipped with a rogue's basic knife and my first pirate cutlass in the left hand. My gold was deducted, but the cutlass and the knife changed hands, and I only have one cutlass in my inventory (as though it overwrote the first one).

**Comment by Alys** [comment]
I haven't been able to replicated this in a test account, so it looks like it's a local problem or a temporary glitch. Clear your browser's cache, log out of HabitRPG, log back in, and do a hard refresh on both the tasks page and the equipment page. Are you seeing both cutlasses? It's possible that one is on the equipment page and the other still in the rewards column of the task page.

**Comment by unrelatedwaffle** [comment]
Hi Alice,

I cleared my cache, logged out and back in, and refreshed both pages. I
still only have one cutlass in the equipment page and on my main page.

When I bought the second cutlass (right), it equipped only the right
cutlass, then put the left cutlass back in the Rewards section, but still
deducted the gold. I still see the left cutlass under rewards. Should I try
again with no weapons equipped once I get back up to 80 gold?

2014-06-27 15:55 GMT-05:00 Alice Harris notifications@github.com:

**Comment by Alys** [comment]
If the other cutlass is still available for purchase, then buy it again. That should fix the problem. It was most likely caused by a sync problem - your first cutlass purchase was done locally but probably not synced with the HabitRPG server. You can use Fix Character Values (Settings -> Site) to restore any gold you lost.

**Comment by unrelatedwaffle** [comment]
Thank you, it worked this time!

2014-06-27 18:20 GMT-05:00 Alice Harris notifications@github.com:
