### ISSUE TITLE
Progressing ToDo

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#366]
A pattern I've noticed is that ToDo itemsoften morph or split. For example My "dispose of car battery" item became "contact locil council". After a response from them it became "call waste company on ####### about battery", and so on. I expect it to morph e few more times before the original item is accomplished.

This seems to be a recurring pattern. A large, vague task becomes either several steps or a first step which morphs as new information becomes available. It's like steps in a quest. Perhaps the original task could become more valuable the more sub-steps I must take.

Also, I found it greatly motivating. "Clear area X" never gets done. But once I change it to "Clear only item Y from area X" I usually get motivated to start, and before you know it, I accomplished the original goal. This is the whole point of HabitRPG, to help me do things I wouldn't do without it!

**Comment by StanLindsey** [comment]
I think there is a lot of scope for grouping/categories/checklists and similar. Tagging will solve many issues I believe but like your recent post on Trello regarding working out groups these would all help with motivation and productivity. 

Checklists in-particular would be a great way of doing this. You could also get more experience from a task (not by a huge standard) by utilising checklists and breaking up tasks into smaller ones. That is a more productive method so we should reward it.

**Comment by ghost** [comment]
i think that bringing in a entire, more complete, todo-list system can get overcomplex, and that's technically and usability wise. Of course TODO's must and I believe they evolve with time. 

For now i'd suggest only a varying reward system for TODO's. You classify them as red, yellow or green according to urgency.

**Comment by StanLindsey** [comment]
I think checklists are something we need, but I agree with you @joecm that todo lists can get overly complex and one of the reasons I like HabitRPG are its simplicity.

**Comment by killroy42** [comment]
Perhaps individual items can be linked to external APIs. For example one ToDo item has a minature screenshot/icon of a trello card/board attached, so we know immmediately what it refers to, and have an easy link to where we need to complete the parts of the tqask, or mark our progress. So for example moving a card from list to list in trello gives us partial XP, while the final archive completes the ToDo. don't reinvent the wheel!

**Comment by wc8** [comment]
That's a good idea for trello integration.
The original idea for checklists was to keep it simple (one level deep) and then rely on integration with other apps like Workflowy, etc. for anything more complex. 
@joecm have you seen the [Priority Multiplier](https://trello.com/c/4C8w1z5h) request? It sounds similar to your urgency request, I think.

**Comment by wc8** [comment]
@killroy42 It seems either [checklists](https://trello.com/c/PJ1iJ413) or trello integration would meet what you're looking for in this suggestion. If not, please reply back.

**Comment by killroy42** [comment]
Perhaps, will have to see the implementation ;)
