### ISSUE TITLE
Guild page freezes tab

### ISSUE THREAD

**Issue by jweidmaier** [HabitRPG/habitica#3663]
Everytime I access the Guild tab, the browser tab freezes and I can't click on anything.

**Comment by lefnire** [comment]
Above commit uses bindonce on guilds listings, so we don't have watchers. Since the only time guild changes happen is when CRUD-ing guilds (a very rare operation), this is heavy handed and requires a reload to see changes. Meaning when you create a group, it does a hard redirect to the group page (not updating in real-time). IMO, this is totally fine since a lot of issues are triggered by not refreshing between group CRUD operations anyway (eg, create a party > join a quest > doesn't work). But since someone (@colegleason?) did a lot of leg work to make real-time group CRUD work, moving _away_ from hard redirects, I wanna check with devs first to make sure we're all :+1: - @SabreCat @deilann @colegleason @paglias

**Comment by jweidmaier** [comment]
I'm not sure what you mean.  I'm not in a guild and I'm not trying to create one.  All I know is when I go to "guilds" my browser tab stops working.  I can't refresh, I can't click on anything.  Nothing.  I have to close out and open HabitRPG.com again.

**Comment by lefnire** [comment]
Sorry @ohjeremy that was a message to the devs. This _would_ fix the issue for you, but first I want their OK on technical bits

**Comment by jweidmaier** [comment]
Ah okay.  Sorry for the misunderstanding and thanks for the quick reply!

**Comment by deilann** [comment]
I think since a lot of issues in general are solved by needing a refresh, that's a-okay.

I'm actually planning on going over "Refreshing, Habit, and You!" in the Newbies challenge I'm developing.

**Comment by paglias** [comment]
@lefnire I think it was me who tried to remove refreshes when joining/leaving/... guilds but sometimes it didn't update the UI correctly. For me it's totally ok.

**Comment by SabreCat** [comment]
Sounds legit to me. It'd be nice long-term to find some way of slimming the Guilds page down so we don't trip over this sort of thing so much, but in the meantime, a few extra refreshes are a small price to pay.

**Comment by deilann** [comment]
Having people category their guilds so they aren't ALL shown might help. It
would also help users find the guilds they're looking for.

**Comment by lefnire** [comment]
:+1: devs, thx. @ohjeremy could you try now?

**Comment by jweidmaier** [comment]
Same problem.  Everything freezes and I can't click on anything.  I have to
close the tab to even try and get back to the homepage.  I'm in Google
Chrome if that helps.

**Comment by lefnire** [comment]
Confusticate. (Chrome is the _best_ browser for Habit, so...). Well if someone gets the chance before me, we should implement [infiniteScroll](http://binarymuse.github.io/ngInfiniteScroll/demo_basic.html) (already a dependency) on guilds page. Not necessary to load via AJAX, we can just load it all and keep on hand, only rendering one page full at a time

**Comment by deilann** [comment]
Wonder if the new code had been loaded? Might be worth it to clear cache
before checking again?

**Comment by jweidmaier** [comment]
Just checked.  Cleared all browsing history and data.  Logged out and back
in, and still freezing.

**Comment by deilann** [comment]
kk you are the only one currently reporting this level of impairment, so:

What are your computer specs? What is the actual version of the browser you
are using?

Have you recently scanned for viruses and malware, with an up-to-date
database?

What happens if you try on another computer?

**Comment by lefnire** [comment]
I know why, I setup bindonce which removes watchers, improving
post-page-load performance. But with hundreds/thousands of guilds, they
still need to load once. So initial load is killing it. The solution is
infinite scroll, which only loads say 50 until you scroll down.

**Comment by jweidmaier** [comment]
Chrome is up to date.  Microscoft Security Essentials is up to date with
nothing detected.  Windows 7 - 64bit. Intel Core i3-2330M CPU @2.20GHz

**Comment by deilann** [comment]
thx -- just wanted to rule that out

but I think Tyler (who appears to be in mad scientist mode, which I love
watching) is on it. I think it's the initial load that's killing.

Hopefully reducing the number of guilds loaded at once will get you in
there!

**Comment by jweidmaier** [comment]
Yes, it freezes before any guild load.  When I tried it on my roommate's
much more intense desktop computer, it loaded just fine in Chrome.

On Tue, Jul 1, 2014 at 7:12 PM, Jeremy Weidmaier <jeremy.weidmaier@gmail.com

> wrote:
> 
> Chrome is up to date.  Microscoft Security Essentials is up to date with
> nothing detected.  Windows 7 - 64bit. Intel Core i3-2330M CPU @2.20GHz
> 
> On Tue, Jul 1, 2014 at 7:05 PM, Tyler Renelle notifications@github.com
> wrote:
> 
> > I know why, I setup bindonce which removes watchers, improving
> > post-page-load performance. But with hundreds/thousands of guilds, they
> > still need to load once. So initial load is killing it. The solution is
> > infinite scroll, which only loads say 50 until you scroll down.

**Comment by deilann** [comment]
I imagine you can load an actual guild just fine if this is the issue, like
follow this link:
https://habitrpg.com/#/options/groups/guilds/d7ff4130-7c2b-450c-8418-1eea35c255a5

**Comment by jweidmaier** [comment]
Yep, loaded just fine!  Thanks for all the help guys!  Ya'll are amazing
and this app is a life-saver.

**Comment by negue** [comment]
@ohjeremy Could you test it again? Any faster and no freezes?

**Comment by Alys** [comment]
Since this is old and there are no recent updates, I am assuming it is fixed, but if I am wrong, we can reopen this!
