### ISSUE TITLE
Subscription payment does not stop after cancellation

### ISSUE THREAD

**Issue by kiendang** [HabitRPG/habitica#3664]
Hi, I cancelled my subscription late April or early May (I don't remember exactly). The cancellation was successful and it clearly shows in the web page (the "Subscribe" button is available) However, after that, I was still charged at least 2 more times on June 11 and June 27. My user ID is 11759063-d8b0-432e-9c3a-32b6af27c6d0. I just want this to stop. No refund needed. Thanks for your support.

**Comment by deilann** [comment]
Ach! So sorry to hear that, @kiendang!

However, Github isn't the best place to handle this. (Mostly because it may involve personal information to get it sorted out.) Can you email admin@habitrpg.com, so it can be taken care of ASAP?
