### ISSUE TITLE
Boss Killing Party in One Hit

### ISSUE THREAD

**Issue by korybing** [HabitRPG/habitica#3665]
My party is fighting Vice, and for the second time now the dragon has killed the entire party in one hit. I'm pretty sure this isn't supposed to happen? I've attached a screenshot showing Vice attacking us for 900+ damage in one hit, whereas all the other hits have been hardly any damage. What is happening? I'm tired of losing all my experience and gold. : )

![screen shot 2014-06-30 at 12 00 11 pm](https://cloud.githubusercontent.com/assets/8029788/3434373/6521600e-0089-11e4-9733-9598895294ba.png)

**Comment by thepeopleseason** [comment]
Based on your interaction with your party-mate and the logs that you see, do you know if al has ever skipped multiple days of logging into HabitRPG?

Boss damage is calculated daily, but only inflicted when the user next interacts with the site after their day start (whether that's midnight or custom), so the potential is there that al may have skipped several days of HabitRPG, thus building up 900 points of damage.

**Comment by lefnire** [comment]
When I get a chance, I'll look at the database. Hunch is someone with nutso-reds, or hidden, or such

**Comment by lefnire** [comment]
@korybing could you shoot me al's UUID?

**Comment by korybing** [comment]
Al's UUID is 3776123f-13e4-471d-80fd-e2bd745b7153. I suppose it could be that he hasn't logged in in a long time and that's what's causing the problem, I haven't kept up with him in awhile. I had no idea that it would impact the party so much, though! This has only happened during our fight with Vice, none of the other bosses have caused this much damage. Thanks!

**Comment by lefnire** [comment]
Yeah, my _hunch_ is it was al. Numbers can get pretty ridiculous in Habit when you go outside normality (many incomplete reds, casting spells on reds/blues - etc); aka, our game is poorly balanced numbers-wise, so it could have just been a mega-missed batch of days.

However, seeing @Pandah experience the same issue at #3666 near the same time makes think that less likely. I'm gonna investigate the moment I can. We have a new boss feature which y'all will see tonight, but I did a pretty thorough review of [added code](https://github.com/HabitRPG/habitrpg/compare/7107f2d3235549caa312ad7c8b81f0d298cc3cd1...14c60192582ec0516231804bae6b77454d32be85) (plus running the tests) and I'm not seeing anything there that could have impacted this.

**Comment by lefnire** [comment]
Oh, and diff bosses have diff `str`, which multiplies the boss's damage. Vice3 ha 3, meaning 3x the normal dmg

**Comment by deilann** [comment]
@lefnire Actually Vice does 1.5x because boss damage forgets the static 2
multiplier.

**Comment by lefnire** [comment]
@deilann I've likely missed some back convos, but I don't follow? ([screenshot](https://www.evernote.com/shard/s17/sh/c4750461-df36-4652-8674-03bdf69589ac/348ec01857c911b02b4c624944657473))

**Comment by deilann** [comment]
@lefnire When task damage is dealt, it's multiplied by 2 for better
results. See line 852 of index.coffee

Boss damage never calculated that in.

**Comment by crookedneighbor** [comment]
This is a stale issue, so I'm closing it. If you're still having issues, please reopen it.
