### ISSUE TITLE
Bailey appears before her new message does

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3668]
I think I've figured out why I keep missing Bailey announcements.

The Bailey "Psst" pic appears upon sync, when a new Bailey announcement rolls out. But the _content_ of the announcement doesn't load until a hard refresh. So here's what happens...
1. New Bailey is deployed.
2. I click a task or something.
3. The "Psst" appears.
4. I click the "Psst". Huh! It's the same message I saw last time.
5. I click "Dismiss This Alert."
6. Later, a hard refresh occurs. (Maybe I restart my computer or something.)
7. The new announcement is available to me, but since I already dismissed Bailey, she doesn't show up to say so.

**Comment by deilann** [comment]
Yeah, this happens a lot. I keep having to tell users about it.

**Comment by lefnire** [comment]
Angular catches the "New Bailey" when clicking `sync` as a user model update. But the Bailey content is part of the HTML, and the HTML needs to be reloaded. What we _could_ do is make "New Stuff" a bindonce, so they only see it on refresh (the easiest solution, [diff](https://gist.github.com/lefnire/180cc9dd5cb5e2028649)) - but my fear is people won't refresh for _many_ days and miss many-days-worth of updates. Don't have the alternative solution, thoughts?

**Comment by deilann** [comment]
Tell people in the update to refresh if it's not a very recent date.

**Comment by lefnire** [comment]
Oo, I forgot - we could start using @paglias's `res.needRefresh` feature: https://github.com/HabitRPG/habitrpg/blob/develop/public/js/app.js#L228

**Comment by deilann** [comment]
:thumbsup:

**Comment by SabreCat** [comment]
Ohh! Yes!

**Comment by phillipthelen** [comment]
I actually started working on some code, that would replace the static html for news with content that is loaded via the api. (this way, news would be entered by admins on the website). But I'm not sure how long it will take me to finish this.

I guess that would be the best solution to the problem? 
The needRefreshing solution has the disadvantage, that it states that the last action has to be repeated, as it was not saved, although that's not correct. That would make users check off a habit twice, probably?

**Comment by paglias** [comment]
@vIiRuS the needsRefresh was implemented when a change to the API was made that was incompatible with the previous version. When enabled it blocks new requests to the server before they are processed, so they are not saved https://github.com/HabitRPG/habitrpg/blob/e5c002bcdb417d260a29afebbaaa22eb3ff6dbce/src/middleware.js#L81-L87

**Comment by phillipthelen** [comment]
@paglias that I understood. I was referring to this issue. As "there is new bailey news" doesn't mean that the api changed.

And i just realised, that the content of the news modal is also available via https://habitrpg.com/static/new-stuff
Should be rather easy to load the news from there and put it in the modal, right?

**Comment by paglias** [comment]
@vIiRuS ok, yeah the message is not a really appropriate one. 

Mmm yes we could load the modal content directly from there every time the modal is opened but we should also consider that the problem isn't only the news but also the new features avalaible on the site and the only way to get them is to refresh the page

**Comment by lefnire** [comment]
@vIiRuS I would _love_ for new-stuff to be loaded from the database, editable by admins. @lemoness always has to email me the messages, and I periodically screw  them up or forget to trigger the "new-stuff" flag. Plus, this would allow us to archive old news which can be requested as needed (right now users see everything since the dawn of habit). Anyway, low prio - but if you're thinking of tackling, :+1:

**Comment by phillipthelen** [comment]
That really doesn't sound like a great solution :D

There are two things, where I'm unsure about the implementation:
1. How long does it take to mark the new-stuff flag for every user? (aka: is it feasible to set that automatically after a blog post is created or would it be better to find a different solution? p.e. new-stuff could be replaced with the id for the last seen news and if that differs from the newest one, there is new stuff. That wouldn't require such a huge database upgrade each time.)
2. Should simply all admins be able to write news? or create some new group?

**Comment by lefnire** [comment]
1. Ideally, when an admin hits "Save" on the "Add Bailey Announcement" form, it would then trigger `db.users.update({},{$set:{'flags.newStuff':true}},{multi:true})` (https://github.com/HabitRPG/habitrpg/blob/develop/migrations/new_stuff.js). This takes ~5m to hit all users, but it's a backround op. But you're right, adding an id with the last seen message would be even better - kinda like how chat currently works.
2. I don't think we need to go so far as adding a new user role just yet. Really, @lemoness is the only person who writes Bailies (and myself, very seldom). Right now we have `admin` and `sudo` [roles](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L70) (admin==moderator, it's a legacy thing) - we'll allow it for `sudo` permission, which right now is only vicky, leslie, & I

**Comment by deilann** [comment]
I think there could be good reasons to allow moderators Bailey access. I
know there have been situations in which being able to write one would have
been _very_ useful. Although going through @lemoness would not be that
difficult.

**Comment by lemoness** [comment]
Since the Bailey announcements are frequently timed carefully to be spaced
out for event reasons, I'd rather that moderators with requests contact me
instead of adding them in themselves - but having them write their own
Baileys and send them to me is always helpful and is definitely encouraged!

**Comment by lefnire** [comment]
Incidentally, I was going to say @deilann would be the only other one besides. But at this point (maybe later, different) I think best Ryan contact Leslie with updates.

**Comment by deilann** [comment]
Haha, yeah, I was thinking it might be useful to be able to do them, but
not do them unless I had permission from @lemoness (because of timing
reasons, not overwhelming people, so on so forth) -- so actually having her
do the updates is not that much of a bigger barrier

**Comment by Alys** [comment]
I believe this has been fixed.
