### ISSUE TITLE
Drag'on of Dilatory bars not displaying correctly

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#3669]
![err3](https://cloud.githubusercontent.com/assets/6122017/3440248/16399d78-00f5-11e4-80d6-c34e805ec772.png)

I guess I'm not the only one. Off topic - I'm going to report a bunch of similar graphic problems, is it better if I create an issue for every "suggestion" or an unique issue with all the stuff?

**Comment by deilann** [comment]
Refresh. That was fixed a bit ago.

**Comment by deilann** [comment]
(Also, it's kind of easier to have separate tickets if they're not to be fixed with one solution, because otherwise the tickets can't be closed as the issues are fixed.)

**Comment by deilann** [comment]
For ref: https://github.com/HabitRPG/habitrpg/issues/3667

**Comment by Atomk** [comment]
Woah, didn't notice the other issue, you guys are amazing at fixing things!
I expected larger bars (5m could be 5999999 or 5000000, not really game-like), but at least it doesn't look ugly as before :)

**Comment by deilann** [comment]
Larger bars would involve... more CSS styles above and beyond. Front end stuff. Magic.

This gets it working for now. :)
