### ISSUE TITLE
Habit frequency option affecting habit color (indicating urgency)

### ISSUE THREAD

**Issue by sveinns** [HabitRPG/habitica#367]
There should be a box every habit where you can type in how often it should occur (ideally). E.g. two times per day or every x hours. I haven't thought this completely through, but I see my most important, high frequency habits go blue (indicating that I should do something else) while habits that should happen once a week stay yellow or go red.

I think this frequency should affect only the color of the habit, so that the xp reward isn't skewed. This could also possibly be an alternate view.

**Comment by elssar** [comment]
There is already an open issue similar to this --> #339

**Comment by StanLindsey** [comment]
This is currently the second most voted topic on [Trello](https://trello.com/c/XuVokK2V) so I'm going to close this for house keeping. Make sure to vote for it there to show that its important to you.

Thanks for the feedback and thanks @elssar for pointing out the other thread!

**Comment by sveinns** [comment]
Mind you, I was wishing this on habits, not on tasks! So the requests are different. Maybe @SlappyBag could consider this a separate request and reopen?

**Comment by wc8** [comment]
@sveinns Is [this](https://trello.com/c/YSXfecBt) what you were thinking of?

**Comment by wc8** [comment]
Ignore the last question. I think I get it now. 
You want to **assign a frequency to Habits not just to daily tasks.**

**Comment by sveinns** [comment]
That is exactly what I meant! :-D

**Comment by Pandoro** [comment]
@sveinns sorry for the long wait. See the [trello card](https://trello.com/card/expcted-habit-frequency/50e5d3684fe3a7266b0036d6/208) and vote for it there.

I will close this, please discuss further on trello where needed :)
