### ISSUE TITLE
[interface] Progress popup is hidden on XP bar

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#3671]
![2014-07-01 14_56_21-greenshot](https://cloud.githubusercontent.com/assets/6122017/3443211/7c6353a8-011f-11e4-85ab-a4569621508e.png)

The "Experience" popup hides the "Progress" popup.

**Comment by SabreCat** [comment]
In fact, it falls behind the background even when the Experience popup doesn't run into it:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3451376/94e227b2-0195-11e4-9121-a930a4d6e368.png)

**Comment by Atomk** [comment]
The design of the bars changed (in the beta server, at the moment) and there's no more Progress popup...

**Comment by Alys** [comment]
A design change has fixed this.
