### ISSUE TITLE
Party leader hasn't been invited to quest

### ISSUE THREAD

**Issue by thegrimsqueaker** [HabitRPG/habitica#3672]
Our party is trying to start the gryphon quest, but our party leader isn't seeing the invite. They were resting in the inn when I invited everyone, but even after checking out of the inn, they can't see the invite.

**Comment by deilann** [comment]
Have them log out and log in again. Even folks in the inn get invited.

**Comment by thegrimsqueaker** [comment]
That worked. Thanks!

**Comment by deilann** [comment]
np!
