### ISSUE TITLE
Progress graph useless after a fortfy potion

### ISSUE THREAD

**Issue by signaleleven** [HabitRPG/habitica#3673]
Hello,

A few month ago I left my account unused for some time, and my dailies plunged in the red.
I subsequently used the fortify potion to start playing again. In hindsight, I should have used the Orb of Rebirth.

The problem is that now the progress graph has a very deep "gorge" that ruins the scale, not letting me see the small day to day variations of my behavior (dancing around zero)

Is there a way to delete the history up to a certain point?
![progress](https://cloud.githubusercontent.com/assets/1616975/3453938/d4e44874-01ca-11e4-878e-805a4e41cca7.png)

**Comment by deilann** [comment]
Orb of Rebirth would do the same thing.

I'd simply suggest recreating the task, if you no longer want the old
history.

**Comment by signaleleven** [comment]
Mh. Wish I thought of that :-) 
I still believe a history edit would be better, because I would like to keep the last 3-4 months, but I consider the issue closed cause it could have been done before. :+1:

**Comment by deilann** [comment]
I agree -- a delete history would be a good feature. Maybe bring it up on
Trello?

**Comment by signaleleven** [comment]
Will do!

On Wed, Jul 2, 2014 at 11:34 AM, deilann notifications@github.com wrote:

> I agree -- a delete history would be a good feature. Maybe bring it up on
> Trello?
> 
> On Wed, Jul 2, 2014 at 2:31 AM, signaleleven notifications@github.com
> wrote:
> 
> > Closed #3673 https://github.com/HabitRPG/habitrpg/issues/3673.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/3673#event-137326729.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3673#issuecomment-47755481.

## 

Michael Sacchi
http://www.signal-eleven.com/
