### ISSUE TITLE
Sudden death!

### ISSUE THREAD

**Issue by deminard** [HabitRPG/habitica#3674]
Hi there!

User ID:
65a31f10-e34a-45d8-b714-bf1962789c90

Love the HabitRPG site, and was about four or five days into it - was updating on an android phone, (using a 3rd party app - Habit AndroRPG -  as the official app wouldn't install on my phone).

Suddenly I was notified that I was dead, having before had 40 of 50 hit points, and being well on my way to level 2, (about 2.05pm GMT, 02-07-2014).

Tried looking in the data export tab, but couldn't see anything in the spreadsheet that could have wiped me out so catastrophically. I only have about 3 dailies, so even if there had been a sync issue, this wouldn't have immediately swatted my character, would it?

Any possibility of getting my progress back would be greatly appreciated!

**Comment by deilann** [comment]
Sorry, if it's a third party app, we really can't do support.

However, if you'd like to get your progress back, on the web app, go to Settings > Site > Fix Character Values and put back your XP.
