### ISSUE TITLE
Habit Boss Damage, capped at 10 or 20 clicks per habit.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3675]
Would it be possible to allow Habits to do damage against bosses—capped, not the number of times you can click a habit, but the _boss damage per habit_? 

151 of 158 people answer [this poll](http://habitrpg.wikia.com/wiki/Thread:5738) don't expect to click their habits more than 20 times per day—at a maximum. 123 of 158 people don't expect to click them more than 10 times per day.

Alternatively [or in addition], if habits can reach a critical hit, then maybe just let critical hits always do some damage to bosses (more damage for warriors). This was suggested elsewhere.

**Comment by thepeopleseason** [comment]
:+1: to Critical hits.

**Comment by deilann** [comment]
I see no reason to cap it at all. People who cheat, cheat themselves.

But I know Tyler has already agreed that habits should deal boss damage.
It's just an issue of implementing it.

**Comment by wc8** [comment]
Then we can close this. The cap is an option if it would make calculating boss damage for quests or World Events easier—but I suppose one could simply estimate based on poll results.

**Comment by Alys** [comment]
I've seen comments in various places that when habits are changed to do boss damage, some rebalancing will be needed. Does anyone have any details about that? 

Making positive habits do boss damage would be VERY easy if it was implemented exactly as for to-dos and dailies, with no rebalancing.

It would also be easy if the rebalancing was something simple such as making a positive habit give only 50% of the boss damage compared to what a comparable to-do or daily would do.

Perhaps this is a good time to talk about it and make some specific plans? It would certainly be a popular thing to announce while Drag'on is plaguing Habitica. If no one has any strong feelings about this, I could just go ahead and code in what I think is good (probably the 50% idea), and then it could be hacked apart later after we've seen what sort of effect it has. But if you have better ideas, I certainly won't object to not doing this!

**Comment by Alys** [comment]
Alternatively, @wc8, once a decision has been made, I could help you make the change if you wish. It's pretty much entry level, unless we decide to do something very complex. This is the code that I'm thinking would be modified:

```
unless task.type is 'reward'
  if (user.preferences.automaticAllocation is true and user.preferences.allocationMode is 'taskbased' and !(task.type is 'todo' and direction is 'down')) then user.stats.training[task.attribute] += nextDelta
  # ===== STRENGTH =====
  # (Only for up-scoring, ignore up-onlies and rewards)
  # Note, we create a new val (adjustAmt) to add to task.value, since delta will be used in Exp & GP calculations - we don't want STR to bonus that
  if direction is 'up' and !(task.type is 'habit' and !task.down)
    user.party.quest.progress.up = user.party.quest.progress.up || 0;
    user.party.quest.progress.up += (nextDelta * (1 + (user._statsComputed.str / 200))) if task.type in ['daily','todo']
  task.value += nextDelta
delta += nextDelta
```

**Comment by Alys** [comment]
done but not capped
