### ISSUE TITLE
Equipment stuck/can't change equipment on avatar

### ISSUE THREAD

**Issue by micjiggly** [HabitRPG/habitica#3676]
This morning I purchased the Umbral Hood. However, it didn't appear on my avatar's head - he is still wearing the same hat as he was before the purchase. I can select the Hood and it says that it is equipped, but it doesn't show. In fact, all of my items are stuck on my avatar. This morning I also acquired my first mount. I subscribed two or three days ago.

**Comment by lefnire** [comment]
Make sure [Use Costume](https://www.evernote.com/shard/s17/sh/f6a86cb0-3194-44a2-9a17-463fb0f0aed8/e3e685936fbf7b64cda04a2ea7e940f3) is unchecked. Or if you want it checked, make sure you're equipping in the costume pane, not the Battle Gear pane

**Comment by micjiggly** [comment]
thanks! fixed. [facepalm]
