### ISSUE TITLE
A Daily transferred to Habits

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3677]
Hello,

I have this issue where a newly added daily that I checked suddenly transferred to my Habits when I logged back in. Here's what my tasks looks like as of the moment.

![screenshot 2](https://cloud.githubusercontent.com/assets/6478877/3465040/86885872-025c-11e4-9535-c8834c61b0a7.png)

I have a "checkable" habit instead of ones with "+" and/or "-". I know I could just delete it and retype the daily again in the Dailies section and get everything fixed but I still decided to report this issue in order for devs to know. This might be something of great concern in the near future.

If you want to know the full story, read on... Otherwise, you can skip reading the rest of the content.

Full Story:

I just woke up this morning and updated my tasks. I added a daily to login to HackerRank.com everyday so I could check about new challenges and contests. After adding the daily and logging in to HackerRank, I clicked on the daily and everything was fine. I mean, the daily was checked and there was no sign of a bug. This was when I was at home.

After a few minutes of preparation, I logged out of HabitRPG and went to my workplace. In my workplace, I have a computer where my HabitRPG is already logged in. I had always set my web browser (Google Chrome) to continue where I have left off. So, when I turned on the computer and opened Chrome, I already have HabitRPG opened. And, to my surprise, I already have a gray "checkable" habit as shown in the picture and the daily that I have set-up was gone in my Dailies. In other words, the daily (to login to HackerRank) that I set up earlier was transferred to the Habits section.

When I tried to click the "checkable" habit for the first time, it can't be checked but I gained GP and XP. Then, I logged out of HabitRPG hoping that it is a self-fixing bug. However, when I logged back in, it wasn't fixed. I tried to click the "checkable" habit again and it worked. The habit is now checked as you can see in the following picture:

![screenshot 3](https://cloud.githubusercontent.com/assets/6478877/3465357/cd408b48-0263-11e4-9e20-5deb51ea2929.png)

So I gained thrice the gold and experience from a single task.

**Comment by deilann** [comment]
Can you share this info here: https://github.com/HabitRPG/habitrpg/issues/2334

Thank you for the detailed report!

**Comment by ghost** [comment]
Yes, sure. I'm sorry for posting this. I didn't see that ticket. Thanks! :)

**Comment by deilann** [comment]
Don't be sorry. :)
