### ISSUE TITLE
Clicking names show the wrong character info

### ISSUE THREAD

**Issue by ThisIsBlank** [HabitRPG/habitica#3680]
After clicking a party member's avatar or somebody's name, it will show their character information, but if you click another character afterwards, it shows the first character's information instead of the new information. I hope that wasn't very confusing..
EDIT: After paying closer attention, it seems it's only the equipment that doesn't get updated.

**Comment by deilann** [comment]
Check out this ticket: https://github.com/HabitRPG/habitrpg/issues/2010
