### ISSUE TITLE
Orphaned Habit from Challenge

### ISSUE THREAD

**Issue by applejess** [HabitRPG/habitica#3681]
I have a Habit stuck in my list from a Challenge that no longer exists, and no way to delete it. The challenge doesn't appear in my list of challenges anymore, and is no longer listed in the Tavern, either, which is where I originally joined it. The habit is "finish another tome of compelling significance." I don't remember what the challenge was called, but something along those lines.

**Comment by deilann** [comment]
Click the habit (as in the actual button). It should register now that it's
broken. Then you can remove it by clicking the broken megaphone. This
happens with very large challenges.
