### ISSUE TITLE
Wrong Stats, Suspect Level Cap

### ISSUE THREAD

**Issue by m0xf4240** [HabitRPG/habitica#3682]
I noticed my individual stat benefits (Level, Equipment, Allocated, Buffs) don't add up to the displayed total. It appears the benefit from half my level is getting capped at 50 (possibly from the old level 100 cap), even though it's displaying as 53.5. Either the attribute total or the level-specific benefit should be changed to create agreement. 

Test 1: minimal gear
![habitrpg_lvlcap_bug_1](https://cloud.githubusercontent.com/assets/3958169/3484948/fd75cc70-03bb-11e4-975c-425c80839fb2.png)
Test 2: more gear
![habitrpg_lvlcap_bug_2](https://cloud.githubusercontent.com/assets/3958169/3484947/fd7588a0-03bb-11e4-9635-408d1295ee34.png)

**Comment by thepeopleseason** [comment]
Yep. Levels beyond 100 have a max level bonus of 50.

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg/pull/5626 (included in https://github.com/HabitRPG/habitrpg/pull/5642)
