### ISSUE TITLE
Dual Account Facebook Fail

### ISSUE THREAD

**Issue by gkiernozek** [HabitRPG/habitica#3685]
Hi, I tried to log in to my account by facebook(the same email on both options) and when i logged in i got fresh hero instead of mine, now i got two of them because hopefully on my android i got my kickass hero, what can i do to have just my high level hero and don't have problems logging in?

**Comment by deilann** [comment]
Next time you see the level 1 character, delete it.

**Comment by gkiernozek** [comment]
Great! that did it! :) thanks :) :+1:
