### ISSUE TITLE
Howdy, fellow habitian, Chrome extension's not working

### ISSUE THREAD

**Issue by Sapsality** [HabitRPG/habitica#3687]
Installed it yesterday and adjusted it for my needs.
The icon is still grey and when I reloaded chrome, a message appeared from habitrpg extension: "Warning! Your api/uuid keys are wrong, or the server is down".

I doublechecked it, everything is correct.
Help me, oh Great Support Master, you're my only hope.

UPD: forgot to mention. When i click on the extension icon, it updates the info about my character. Gold, experience, to-dos, it shows everything correctly.
It simply doesnt do anything else :)

**Comment by deilann** [comment]
Sounds like it's not a HabitRPG problem, but a chrome extension problem. Can you post your issue there: https://github.com/HabitRPG/habitrpg-chrome ?

**Comment by Sapsality** [comment]
Ok, T.Hanks
