### ISSUE TITLE
Organizing Tasks Doesn't Work

### ISSUE THREAD

**Issue by sthalor** [HabitRPG/habitica#3688]
Whenever I try to move my Habits or Dailies around, it only work's about 25% of the time. The other half, it moves the task somewhere completely random or just further down the list. I'd like to just have them in alphabetical order, or if possible organized by my preference. Right now, it's just a jumble of tasks and I find it a bit confusing to navigate.

**Comment by deilann** [comment]
Are you waiting until the blue bar finished completely before clicking
anything else? There is a known sorting issue with To-Dos, but whenever a
Habit or Daily sorting issue has been reported it has either been that
someone is moving things before the blue bar finishes (and therefore too
many actions for the server) or they are trying to sort whilst tags are on.

**Comment by sthalor** [comment]
Ah, waiting for the blue bar seems to be working. Thank you for the quick
response!
