### ISSUE TITLE
Loss of multiple levels on death

### ISSUE THREAD

**Issue by oneautisticturtle** [HabitRPG/habitica#3689]
Over the weekend I died and lost three levels instead of one level. At first it showed me having lost one level, and then after a refresh it showed me having lost 3, not having died again, just without the stuff or the levels.

**Comment by Alys** [comment]
@oneautisticturtle I'm very sorry we never responded to this. It would have been because we had no idea what might have caused that. I'm going to close this now, but if you've noticed it happening again recently, please tell us.
