### ISSUE TITLE
Kickstarter hits $25,000!

### ISSUE THREAD

**Issue by StanLindsey** [HabitRPG/habitica#369]
Well, we just jumped from $24,942 to to $25,052 so we are officially funded. 

We've got eight days left to reach our stretch goals in order to bring some of the most requested features to the forefront of development! As well as that we are still attempting to fulfill those top backing tiers. So there is no reason to let up with the social media marketing frenzy to allow development to go on even further! 

Thank you everybody who backed us and for the support you've all given. All those people contributing, tweeting, sharing, linking, giving suggestions and feedback; this wouldn't of been possible without you guys!

**Comment by Shaners** [comment]
Awesome!
