### ISSUE TITLE
Deleting tag that is assigned to a habit - does not remove tag icon

### ISSUE THREAD

**Issue by andyviar** [HabitRPG/habitica#3690]
If I have a habit with one checked tag, then I delete that tag via the tag management interface and save, the tag icon continues to appear next to my habit and there seems to be no way to remove the tag icon from that point on.

**Comment by Alys** [comment]
Duplicate: https://github.com/HabitRPG/habitrpg/issues/1611

I'm hoping to look into that soon. You can follow the progress at that link
