### ISSUE TITLE
Wiki should be updated or Balance need to be tweaked? (Mages)

### ISSUE THREAD

**Issue by emz83** [HabitRPG/habitica#3692]
So I don't know if it's by design or not, but currently Warriors are indicated as doing the most boss damage, but it seems like it's really Mages that does the most in practice.

Before I go messing with the wiki, I'd wanted to ask if this was on purpose, unless it was an unforeseen issue with Mage damage formula. If it's on purpose that Mages does the most damage then the wiki should reflect that... unless it's supposed to be hidden?

Please advise.

**Comment by thepeopleseason** [comment]
Ideally, this sort of question should go to the Talk page of Warrior or Mage on the wiki. Github issues are generally for software bugs. 

In answer to your question, however, I think the difference is in the spells/skills that mages and warriors can use. Once Burst of Flames has been rebalanced (currently proposed) the wiki statement may be more accurate.

**Comment by JennaMalkin** [comment]
You might also like to have a look at https://github.com/HabitRPG/habitrpg/issues/2464. Alys's User Data Display website gives hints about how to use your spells.  https://oldgods.net/habitrpg/habitrpg_user_data_display.html

**Comment by deilann** [comment]
Yeah, this should not be a Github ticket. Please use the Wiki talk pages or the Wiki Trello to talk about Wiki issues.

However, I think the statement is meant to talk about the most boss damage _before skills_. Which is totally true.
