### ISSUE TITLE
damage to World Boss is lost if party quest finished earlier in day

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3693]
(This issue assumes that I'm understanding Habit's code correctly, which I might not be. Apologies if I'm wrong.)

Based on src/models/group.js (finishQuest and cleanQuestProgress), I think that when a party quest finishes due to one player's cron, user.party.quest.progress.up is set to zero for all other party members. I.e., their quest progress is deleted before their own crons run. This was also noticed experimentally by taldin who has been watching his boss damage using the [DDT](https://oldgods.net/habitrpg/habitrpg_user_data_display.html).

This means that the boss damage built up by the player is not applied to a world boss when the player's own cron runs, if the player had been in a quest that finished earlier that day.

If the player had used several attack skills specifically to damage the world boss (which many players are doing), then the player will feel that the mana had been wasted. 

Assuming that is what's actually happening... I can see a few different ways that it could be fixed, although someone more familiar with the code could probably come up with better ones! Method 3 below is my favourite.

**Method 1:** When finishQuest/cleanQuestProgress runs, just before each player's user.party.quest.progress.up is set to zero, apply that progress to the world boss to do damage to it immediately. This has the disadvantage that it will still seem to the player that their progress has been lost, if they're using the API or the DDT to watch how user.party.quest.progress.up changes (i.e., this "bug" will keep on being reported occasionally even after it's been fixed).

**Method 2:** When finishQuest/cleanQuestProgress runs, just before each player's user.party.quest.progress.up is set to zero, copy that progress to a new value called something like user.party.WorldBoss.progress.up and then set user.party.quest.progress.up to zero. When the player's cron runs, use user.party.WorldBoss.progress.up as well as user.party.quest.progress.up to damage the world boss (this will not result in double damage because user.party.WorldBoss.progress.up will be zero until a party quest ends, and at that point user.party.quest.progress.up will become zero). This will allow the player to use the API to view user.party.WorldBoss.progress.up as well as user.party.quest.progress.up so the player will realise that their world boss damage has NOT been lost (i.e., it gets around the disadvantage of method 1). It will also require changes to Habit's code in fewer places than method 3, but despite that it feels to me like an ugly solution.

**Method 3:** In every place in Habit's code where user.party.quest.progress.up is incremented, also increment a new value, user.party.WorldBoss.progress.up (or whatever). When a party quest finishes, don't zero out user.party.WorldBoss.progress.up. When the player's cron runs, use user.party.WorldBoss.progress.up to attack the world boss (and then zero it); use user.party.quest.progress.up to attack the party boss (and then zero it) - i.e., damage to each type of boss is incremented separately and applied separately. This would require code changes in more locations than method 2, but I think it would produce code that was easier to understand, and it feels neat and symmetrical. It would also allow future changes in which the world boss and the party boss can be attacked in different ways, if that would ever be desirable.

I'd be happy to work on this (unless anyone else wants to!), but I'd defintely want to be given some direction about the sort of solution that would be most appropriate.

EDIT: See also **Method 4** in a later comment (it's my current favourite).
##

**Comment by thepeopleseason** [comment]
Are we already iterating through each party member when cleanQuestProgress runs? If so, method 1 seems the quickest way to solve the problem, otherwise I prefer method 3 because it's more orthogonal.

**Comment by Alys** [comment]
Method 1 would be the quickest initially, but at the risk of ongoing
questions from players about this issue, requiring repeated answers and
possibly repeated closing of redundant github issues, all which takes up
support time and is frustrating for those who have to keep dealing with it.
This bug (if it is a bug) became apparent when one player (taldin) noticed
the quest progress being zeroed out when the party quest ended. Method 1
WOULD fix the bug, BUT to the players it would still look exactly as if the
bug was still happening (because the quest progress would still be zeroed,
even though it had been applied to the world boss - there'd be no
indication that the world boss had been attacked by the player in the
middle of the day). If one player can notice this issue, then others will,
and we already have enough questions that are repeated frequently. :)

**Comment by crookedneighbor** [comment]
I vote for method 3.

**Comment by Alys** [comment]
**Method 4**:  Don't remove party members' quest progress when a boss quest finishes, if that party member has not cronned. The party member whose damage finished the quest should have their progress removed of course (that progress has already been assigned to the world boss). But does it really make sense to be removing progress that has not yet been applied to any boss? If the party starts a new quest in the same day, all non-cronned party members will already have made progress towards it, which I think is reasonable since they did earn that progress by completing their tasks. And this one change would also fix the problem of progress not being applied to the quest boss.

Collection quest progress should still be removed from all party members at the end of a collection quest, since you're collecting items specific to that quest, and immediately repeating a collection quest would be unlikely to happen.

**Comment by crookedneighbor** [comment]
I still think tracking it separately is the way to go (Method 3). 

Also, there's a checklist item on the [Trello card for Quests v2](https://trello.com/c/VPPjVRlF/212-quests-and-bosses-v-2-collection-quest-and-boss-fight-enhancements) about overkill that might be relevant.

> Overkill bonus: continues to tally damage even after the boss was defeated, for an extra bonus, until everyone has struck the boss.

Don't know if that's still in the plan for it or not, but that would affect whether or not users quest progress should apply to the next boss or not.

**Comment by Alys** [comment]
The overkill bonus is an interesting idea, but if that was implemented, I imagine the quest would stay active until all party members had cronned, which would result in their quest progress being applied to that boss (and to the world boss) and then removed by the existing cron code. I don't think method 4 would interfere with that.

I think a useful question now is: **Do we actually WANT to be deleting boss quest progress that has never been used against a boss?** That's regardless of whether there's a world boss or not. If we do want to keep deleting quest progress, then we'd use Method 3 to fix the world boss problem. If we decide that when a user has earned quest progress, it should not be wasted, then Method 4 fixes both problems. At the moment, I'm in favour of not wasting boss quest progress, but if no one else agrees, I'll drop the idea without sulking. :)

**Comment by crookedneighbor** [comment]
Does Method 4 account for the DDT showing accurate data for damage to the world boss? How is the person's quest progress that does get reset for delivering the killing blow to the party boss get applied to the world boss?

As for why I think that local quest progress should reset, my thinking is one of logic for how that damage is being applied. 

IE, I cast burst of flames to damage Trapper Santa. The next day, before I log in, Trapper Santa is defeated by another party member and the Laundromancer is started up. Logically, why would the spell I cast on Trapper Santa be applied to Laundromancer?

Now, according to that same logic, why would my spell attack both the world boss and the party quest boss at the same time? Wouldn't it target one or the other?

Just playing Devi's advocate here. I'm fine with whatever, I just think it odd that yesterday's actions should affect today's (new) boss. I get the reverse side of the argument though, I've gotten frustrated in the past for wasting MP on a quest. Especially when I played as a warrior and MP was hard to come by. I coordinated with another member of my party today so only one of us would use mp to kill the boss and the other could use MP on tomorrow's boss.

**Side Note - Have Skills damage boss in real time:**

If skills did damage the boss right away, that'd be an alternate solution to the problem, right?

These are my assumptions for why we don't do this already, correct them if I'm wrong:

The main reason for skills not damaging the boss in real time is to prevent people from starting and finishing multiple quests in a single day, right? And to prevent a boss from never damaging someone with unchecked dailies (IE, if I miss a few dailies, but blast away with BoF, upon cron, even if I kill the boss my party will still be damaged by my missed dailies), right?

We wouldn't be able to get around incomplete dailies not damaging the party, but we could arbitrarily limit quests to once per day.

Anyway, just a thought.

**Comment by Alys** [comment]
_Does Method 4 account for the DDT showing accurate data for damage to the world boss?_  Yes. The DDT reports only the current value of quest.progress.up from the user's data.

_How is the person's quest progress that does get reset for delivering the killing blow to the party boss get applied to the world boss?_ When a user completes Dailies or To-Dos or casts attack skills, their quest.progress.up total is increased. When they cron, that value is applied to the world boss and then to the quest boss, and is then set to zero. When a quest ends without them cronning, it is set to zero and is not applied to the world boss.

_As for why I think that local quest progress should reset ... Wouldn't it target one or the other?_  Yes, if you're thinking about attack skills from a game perspective ("I cast this skill on Trapper Santa") then it makes no sense to save the results of a skill and apply it to the next boss. But then, it also makes no sense to apply it to the world boss as well as to  the quest boss (as you say), or indeed to not apply it at all to the quest if someone else crons before you do. However if we think about it from a productivity motivation point of view, I think it does make sense to avoid wasting skills, so that people aren't demotivated.

_"I just think it odd that yesterday's actions should affect today's (new) boss"_ That's true and I do agree with it, but I think the motivational aspect of not wasting mana or completed tasks is more important. Probably... Although when you phrase it as "yesterday's actions affect today" it does make me question my own idea a bit. :)

Of course in many cases, using Method 4 wouldn't actually make a difference to anything except the world boss... If User A crons and kills the party boss, and then User B crons before a new quest can be started, cron would set that user's quest.progress.up to zero before it could be applied to any quest boss (but it would still be applied to the world boss). So intra-party coordination of mana use would still be important (which I think is a good thing from a social point of view). But maybe this inconsistency makes Method 4 undesirable.

_"If skills did damage the boss right away, that'd be an alternate solution to the problem, right?"_  True for attack skills, but it doesn't help Rogues and Healers who attack with tasks alone. In fact if we tried to fix this issue by making skills apply immediately, I think we'd be discriminating against those classes by giving Mages and Warriors even more advantages than they already have. If we're making skills damage the boss immediately, we should do the same for tasks, and that's a larger can of worms.

_The main reason for skills not damaging the boss in real time is to prevent people from starting and finishing multiple quests in a single day, right?_ I always assumed it was done for coding convenience. :) Does it matter if multiple quests are done in the same day? In a large party across several time zones, each quest might still provide Do-My-Dailies motivation to at least some of the users. And if people want to rush through quests to get more pets more quickly, I think that's fine. They're still doing tasks to earn mana to cast skills. Also, more gems spent. ;)

_we could arbitrarily limit quests to once per day_ If it's arbitrary, do we really want to do it? :) And how do we define "day" in a multi-zone party? And do we want another potential source of trouble when cron doesn't run properly? :)

So many options.... Is Method 3 best just because it's less controversial? Really, they're ALL my ideas so I shouldn't care which one is implemented. ;) I still think it hinges around "Do we want to delete boss quest progress that has never been used against a party boss?" but maybe that's a question for another day.

**Comment by Alys** [comment]
We didn't see any complaints about this in the most recent World Boss and it doesn't make a great deal of difference to the results and I personally no longer care about it :) so I'm closing this.

**Comment by Alys** [comment]
We were talking about this again today and have decided we will fix it with this simple fix: https://github.com/HabitRPG/habitica/issues/9698
