### ISSUE TITLE
Tags popup covers header

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3694]
![screen shot 2014-07-08 at 6 57 57 am](https://cloud.githubusercontent.com/assets/6208739/3508709/f91d5eba-068e-11e4-9599-9db15079c784.png)

With tags enabled:

![screen shot 2014-07-08 at 7 00 16 am](https://cloud.githubusercontent.com/assets/6208739/3508717/157e8aa2-068f-11e4-840f-33a885e3b260.png)

I'm using Chrome, if that matters.

**Comment by casicastiel** [comment]
It's gone after a refresh. Weird. Might've been because I was using one of Merfy's styles, then disabled it. Anyway, false alarm - sorry! :)

**Comment by SabreCat** [comment]
I've seen this happen too when I move the site to a monitor with a lower resolution. It seems that some elements don't always reposition properly when the available space changes--in your case, flip-flopping the style could have changed things around enough to confuse it.
