### ISSUE TITLE
veteran award and veteran wolf pet given to new user

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3695]
In the Newbies guild yesterday, a new user (yfD5^F 9098a561-f7b3-4810-824b-28e754df67b7; "member since 02/06/2014") reported that the veteran wolf had appeared in the user's account, and the user's profile shows the veteran award. A database glitch maybe?

![screen shot 2014-07-08 at 7 45 21 pm](https://cloud.githubusercontent.com/assets/1495809/3508972/cb3207ee-0693-11e4-9b94-643ef55f7f49.png)

I have a test account (3b7d59d1-9c79-4c96-a9ac-6e01664d4251) that was created on 2013-04-21 which also has the award and pet, but I can't recall if that's actually a valid date for it. A more recent test account (dca13bc9-eed-448f-99bf-ab770532f152) created on 2014-05-11 does not have the award or pet.

**Comment by deilann** [comment]
Wonder if this is related to the "everyone has the win a challenge" badge.

**Comment by lefnire** [comment]
Have we seen a pattern on this? (all newly created accounts, or accounts after a certain date)? This one still happening?

**Comment by Alys** [comment]
I've only heard of that one user being awarded it incorrectly, and they still have it. One of my recently-added test accounts does not have it.

I was intending to write a migration script to remove it from all users who shouldn't have it. I'd just need to know what approximate date was used to when it was legitimately applied to existing players.

**Comment by Alys** [comment]
We shouldn't fix this now. The user(s) who have the wolf would have become used to it being there and it would look like a bug or an unfair event if it was removed. Closing.
