### ISSUE TITLE
Challenge Gone, but dailies still there

### ISSUE THREAD

**Issue by JNFortin** [HabitRPG/habitica#3697]
I recently went to leave a challenge I'd joined (30 day character building challenge), and could not find it anywhere.
The challenges page said I wasn't participating in any, and the challege was not on the larger list. I can't delete the daily without leaving the challenge first, so I'm stuck with it. Is there a way to get rid of this daily if I can't leave the challenge?

**Comment by thepeopleseason** [comment]
Yep: http://habitrpg.wikia.com/wiki/FAQ#How_do_I_delete_a_Challenge_task.3F
