### ISSUE TITLE
My credit card was charged, but my subscription does not seem to be activated

### ISSUE THREAD

**Issue by efedak** [HabitRPG/habitica#3698]
I subscribed yesterday, and I see the charge on my credit card.  When I login, the subscribe button still shows, and ads still show up, I don't appear to be getting any subscriber benefits.. I have tried logging out and logging in with no luck.

Thanks,.

**Comment by lefnire** [comment]
What’s your UUID, which payment method did you use (Paypal or Credit Card),
when did you begin subscription & when cancel it?

**Comment by efedak** [comment]
Hello!

My UUID is c11a5294-2a2c-4d67-b5c5-04d48e108939 and I subscribed yesterday,
I don't think I cancelled, I sure didn't mean to!

THanks,

Erin

**Comment by lefnire** [comment]
Woops sorry, I misunderstood. Ok, confirmed the subscription isn't on the acct. I couldn't find any transaction history in Stripe (credit card processor) or Paypal, let's take this to email so I can ask you some private bits. [Shoot me an email](mailto:tyler@habitrpg.com) with (a) which you used (paypal or credit), (b) the email address you used in the transaction - I'll get you sorted
