### ISSUE TITLE
[API] "groups?type=guilds" returns Tavern object

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#3699]
As some of you know, I'm trying to develop an Android chat client for the site.
I found that I can retrieve the tavern chat with `groups/habitrpg/chat` and party chat (gives problems if the user do not have a party) with `groups/party/chat`, so I just need to know what guilds the user is subscribed to. I have a test account on i18n server, I'm not subscribed to any guild, but instead of retrieving `[]` the API responds with `[{"_id":"habitrpg","leader":"9","name":"HabitRPG","quest":{"progress":{}},"memberCount":4}]`.

**Comment by Atomk** [comment]
This doesn't make any sense to me, because `groups?type=tavern` gives the same result.

**Comment by thepeopleseason** [comment]
I just registered a test account on the i18n server and I can't reproduce this (see screenshot). One thing I do notice is that the code on i18n looks to be pretty far behind production, but that may just be cosmetic.

![groupstypeguilds](https://cloud.githubusercontent.com/assets/267868/3533986/b2b6ba92-07de-11e4-9249-9a63a2b4bd0d.png)

**Comment by paglias** [comment]
Ohh.. i18n is really far behind the production server. It was used
just as a testing site for the translations a few months ago. I should
take it down. Try on the production site or on a local install and see
if the problem persists

2014-07-10 5:03 GMT+02:00, James Hsiao notifications@github.com:

> I just registered a test account on the i18n server and I can't reproduce
> this (see screenshot). One thing I do notice is that the code on i18n looks
> to be pretty far behind production, but that may just be cosmetic.
> 
> ![groupstypeguilds](https://cloud.githubusercontent.com/assets/267868/3533986/b2b6ba92-07de-11e4-9249-9a63a2b4bd0d.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3699#issuecomment-48560547

## 

Matteo Pagliazzi - paglias.net

**Comment by Atomk** [comment]
Oh, I believed that the API stuff was not so different between Habit's servers. Later I'll try with another account to double-check this.

**Comment by Atomk** [comment]
Tried, you were right - testing on the main server gave no problems. Lesson learned, thanks a lot for the help!
