### ISSUE TITLE
Gold Placement

### ISSUE THREAD

**Issue by FaeriMagic** [HabitRPG/habitica#37]
Maybe place the gold and silver in the header, next to the health and EXP bar? 
If my browser (Google Chrome) isn't zoomed out to 75%, the images overlap a bit on the Rewards heading.
![goldscreenshot](https://f.cloud.github.com/assets/3200203/46579/db5f9b0a-5874-11e2-9ce0-3a2739e7ca2f.PNG)

(Oh, and another thing, could anyone explain to me how the Chrome extension is supposed to work? I input the time-eating sites I go to, save, then go to a site to see if my HP drops, and...it doesn't. Is it supposed to work after you linger on it for five minutes?
Oh, and I found HabitRPG through the Chrome extension, but couldn't figure out how to work it. Almost deleted it, until I realized it was an accessory for the site. (Thought it was an independent app...) You might want to mention that, if you can, for the stupid people like me. XD)

**Comment by horusofoz** [comment]
+1 support for the idea of moving money to the header with health and exp.

Additionally maybe arrange health,exp, money, avatar horizontally to save vertical screen real estate.

**Comment by lefnire** [comment]
@faerimagic did you input your user id into the chrome extension's settings page? ([screenshot](https://www.evernote.com/shard/s17/sh/d382c8e0-0438-46f1-932b-c32e229b11d5/318a97107e374b9605a1495349b23033)). If the instructions aren't clear enough as such, hit me up and i'll update them.

**Comment by lefnire** [comment]
definitely a zoom issue on the gold. i'll update the placement later.

**Comment by FaeriMagic** [comment]
Now that I read the details again on the Chrome Extension, the instructions actually seem a bit clear to me. (It might be because all the extensions I have downloaded thus far have been standalones...) For a suggestion, I would think "This extension is for the website HabitRPG" or something similar would really send a clear message for those who are skimming through the Chrome Web Store. A few paragraph breaks in the details page wouldn't hurt either.

As for the Chrome Extension itself, you meant the User ID from the settings page in HabitRPG, right? Well, yes, I did input it into the Options page, and clicked save, and that little HabitRPG popup just refuses to show up...

**Comment by lefnire** [comment]
confusticate and bebother. Time for some Chrome-extension-fixin'. Thanks for the copy recommendations, I'll fix that up when I get a chance.

**Comment by fonadius** [comment]
Hi,
not sure if it is that simple but in Chrome, FF and IE is sufficient to set width of the surrounding div to auto
&lt;div class="span6" style="width: auto;"&gt;&lt;h2&gt;Rewards&lt;/h2&gt;&lt;/div&gt;
(of course modify or add proper class)
Before:
![image](https://f.cloud.github.com/assets/2445514/148602/22c51cc6-7509-11e2-95e9-6f292c78dcc2.png)
After on smaller screen:
![image](https://f.cloud.github.com/assets/2445514/148599/00193aea-7509-11e2-80c7-78210546d83a.png)
After on larger screen:
![image](https://f.cloud.github.com/assets/2445514/148605/31edc2c0-7509-11e2-959e-045f21259192.png)

**Comment by horusofoz** [comment]
Resolved through the interface tweaks introduced by Zak.
