### ISSUE TITLE
Chrome Extension Ideas

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#370]
Is there any way that the chrome Extension could have more controls? By that I mean on certain days I can visit some sites and be productive but on others I can't. Plus can you make it so visiting a certain website is a plus in its own little habits. Instead of just browsing productivity?

**Comment by StanLindsey** [comment]
I've moved this to the chrome-extension repo

https://github.com/lefnire/habitrpg-chrome/issues/36
