### ISSUE TITLE
incomplete "Blacksmith" documentation - requesting review by experienced coders

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3700]
I've been trying to use my local install of HabitRPG (using vagrant) to do various types of code updates and I'm pretty sure that the documentation on the wiki isn't complete. For example, by following the documentation, I was not able to use browserify. I worked out that I had to cd into node_modules/habitrpg-shared/ then run "npm install" and then "grunt browserify", so that works for me now, but I'm wondering what else might be missing.

I was hoping someone very familiar with running a local install would be able to have a look at the documentation and see what should be added. If they'd prefer not to update the wiki themselves, they could write notes here and I could transfer them. These are the docs:

[Setting up HabitRPG locally](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally)

[Guidance for Blacksmiths](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths)

I realise that reviewing them might take some time, so I've been reluctant to ask about this, but it could make a big difference to how easy it is for new volunteers to produce good quality changes.

BTW, I have not updated the documentation with anything I've learned because I'm really not sure if what I'm doing is correct. For example, "cd node_modules/habitrpg-shared; npm install; grunt browserify" might not be the best way to get browserify working, or it might be best done after other steps are done first.

I also found that I had to run "sudo apt-get install graphicsmagick graphicsmagick-imagemagick-compat phantomjs" in /vagrant so I'm wondering if that should be added to the vagrant provisioning file, or at least to the docs.

**Comment by thepeopleseason** [comment]
I can add the graphicsmagick line to the provisioning file. That seems to me to be a new requirement.

**Comment by thepeopleseason** [comment]
I'm guessing the browserify requirement snafu is a result of the separation of habitrpg-shared and habitrpg repos. At the very least, it might be that browserify needs to be added to habitrpg's package.json (it's in habitrpg-shared's package.json), but my experience with node dependencies within other dependencies is limited at best.
