### ISSUE TITLE
Wrongly awarded beastmaster achievement

### ISSUE THREAD

**Issue by diyadas** [HabitRPG/habitica#3702]
I have 89 non-quest pets, but I am still missing a cotton candy blue cactus. I did hatch the seahorse egg today, so I am wondering if that was the cause (but I don't think it was meant to be counted for the beastmaster achievement?)

ETA: my user ID is 13018811-220f-4025-93a0-9ed6b6a21032 if this requires a manual fix.

**Comment by Alys** [comment]
Did you previously hatch a cotton candy blue cactus and then turn it into a mount?

**Comment by deilann** [comment]
Check your profile. For some reason, I got the modal at 89, but didn't
actually get the achievement until 90.

**Comment by diyadas** [comment]
Alys: No, I haven't ever hatched it.
deilann: You're right, it was just the medal, not the achievement. I've been at 89 pets for almost a week though, so I wonder what triggered it.

**Comment by deilann** [comment]
Every time you hatch a pet, it triggers a check to see if you got
Beastmaster, even though quest pets don't count.

**Comment by Alys** [comment]
This was probably an example of https://github.com/HabitRPG/habitrpg/issues/3904 which has been fixed.
