### ISSUE TITLE
2x Images for Icons

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3703]
Some of the more recent armor - the Summer Event Armor, the Rainbow Warrior Armor, and the June Subscriber Armor - did not have corresponding 2x icon art, and as a result the icons look very messy in the armory. I've resized them all, as well as the snowball, which also is improperly sized. 

Right now they retain their original proportions. If I need to adjust the canvas sizes, let me know. Also, if attaching them via Github is not as helpful as attaching them a different way, let me know as well.
![healer summeraccessory2x](https://cloud.githubusercontent.com/assets/3494081/3545187/b8e0e9f6-0874-11e4-8401-60c902a7724b.png)
![healer summercrown2x](https://cloud.githubusercontent.com/assets/3494081/3545189/b8e56dbe-0874-11e4-845a-9877424dbf7d.png)
![healer summershield2x](https://cloud.githubusercontent.com/assets/3494081/3545188/b8e4fa50-0874-11e4-95a1-7f5fbee3b457.png)
![healer summertail2x](https://cloud.githubusercontent.com/assets/3494081/3545192/b8e6f7f6-0874-11e4-981c-13dff7cd0f8d.png)
![healer summertailbroad2x](https://cloud.githubusercontent.com/assets/3494081/3545191/b8e6c79a-0874-11e4-90c8-45b3a51aaacd.png)
![healer summerwand2x](https://cloud.githubusercontent.com/assets/3494081/3545190/b8e649c8-0874-11e4-9752-fbdf21d6b6f6.png)
![june14 body broad2x](https://cloud.githubusercontent.com/assets/3494081/3545193/b8f7016e-0874-11e4-93b8-737317b6cd54.png)
![june14 bodyslim2x](https://cloud.githubusercontent.com/assets/3494081/3545195/b8f88ba6-0874-11e4-95e2-5ba40d8e7581.png)
![june14 helm2x](https://cloud.githubusercontent.com/assets/3494081/3545194/b8f7fe52-0874-11e4-9fa2-8f84aabbaa10.png)
![mage summer weapon2x](https://cloud.githubusercontent.com/assets/3494081/3545196/b8f8cdb4-0874-11e4-8636-37eba3caa50c.png)
![mage summercollar2x](https://cloud.githubusercontent.com/assets/3494081/3545197/b8f93ff6-0874-11e4-87e4-6e510db7046e.png)
![mage summerhelm2x](https://cloud.githubusercontent.com/assets/3494081/3545200/b90aca5a-0874-11e4-8fe8-e3f6fcc8cd37.png)
![mage summertailbroad2x](https://cloud.githubusercontent.com/assets/3494081/3545198/b90a6862-0874-11e4-99ef-a6e89a2887ac.png)
![mage summertailslim2x](https://cloud.githubusercontent.com/assets/3494081/3545199/b90a6ac4-0874-11e4-972a-e92b99621e18.png)
![rainbow warrior broad2x](https://cloud.githubusercontent.com/assets/3494081/3545202/b90d2020-0874-11e4-95d0-2a111f9b19b7.png)
![rainbow warrior helm2x](https://cloud.githubusercontent.com/assets/3494081/3545201/b90c686a-0874-11e4-9361-59144d235897.png)
![rainbow warrior slim2x](https://cloud.githubusercontent.com/assets/3494081/3545203/b91fab46-0874-11e4-84b0-2a941a2ee1ea.png)
![snowball2x](https://cloud.githubusercontent.com/assets/3494081/3545206/b920a0dc-0874-11e4-9f64-ad8813a51f68.png)
![summerrogue14accessory2x](https://cloud.githubusercontent.com/assets/3494081/3545204/b91fb136-0874-11e4-82f6-7fe571baf754.png)
![summerrogue14armor2x](https://cloud.githubusercontent.com/assets/3494081/3545205/b9204970-0874-11e4-8466-8b6b14f03d2c.png)
![summerrogue14armorslim2x](https://cloud.githubusercontent.com/assets/3494081/3545207/b92243c4-0874-11e4-83cb-70203212268d.png)
![summerrogue14hat2x](https://cloud.githubusercontent.com/assets/3494081/3545211/b93412fc-0874-11e4-9760-56832353e802.png)
![summerrogue14sword12x](https://cloud.githubusercontent.com/assets/3494081/3545209/b933c41e-0874-11e4-91d6-1152bf7faad2.png)
![summerrogue14sword22x](https://cloud.githubusercontent.com/assets/3494081/3545208/b933561e-0874-11e4-9664-4764b55668ca.png)
![summerwarrior14accessory2x](https://cloud.githubusercontent.com/assets/3494081/3545210/b934076c-0874-11e4-8d5e-f89da63bd719.png)
![summerwarrior14armorbroad2x](https://cloud.githubusercontent.com/assets/3494081/3545212/b9347b34-0874-11e4-93ae-6c23bf4f5905.png)
![summerwarrior14armorslim2x](https://cloud.githubusercontent.com/assets/3494081/3545214/b946ca3c-0874-11e4-8988-a2157a5e2394.png)
![summerwarrior14helm2x](https://cloud.githubusercontent.com/assets/3494081/3545213/b9465d54-0874-11e4-8521-e6c4489ad7df.png)
![summerwarrior14shield2x](https://cloud.githubusercontent.com/assets/3494081/3545215/b947a146-0874-11e4-9f90-96b622f3c109.png)
![summerwarrior14sword2x](https://cloud.githubusercontent.com/assets/3494081/3545216/b9495ca2-0874-11e4-9736-7744d0d8f819.png)

**Comment by deilann** [comment]
It looks like some of your attachments failed.

Also, do we have your permissions on file? ;)

**Comment by lemoness** [comment]
@deilann They're all showing for me - which ones aren't showing up? (It's all 4 summer event outfits, plus june armor, rainbow armor, and a snowball.)

Re: the snowball - I know it is already at 2x, but it sticks out in the spell list, so I was hoping that by cropping it, I could get it to fit more seamlessly. ...And then I attached the uncropped file. Here is the snowball I intended to attach: 
![snowball2x](https://cloud.githubusercontent.com/assets/3494081/3545350/c0f8fb3c-0875-11e4-9995-823c854a5482.png)

**Comment by deilann** [comment]
It's hard to say because they're just gaps. Do a hard refresh. They're probably in  your cache.

**Comment by lemoness** [comment]
I still see them all.... due to the canvas spacing, it does look like there are gaps where there are not. Try dragging on some of the gaps and see if they are just due to canvas size? As mentioned, I can certainly crop them if I need to.

**Comment by deilann** [comment]
Huh. The email version was showing broken images, so I assumed the gaps
were the borked images, but it seems fine.

YOU WIN.

**Comment by lemoness** [comment]
Maybe not. This may be an indication that @lefnire will show up and tell me
to crop them all ;p

**Comment by deilann** [comment]
IT'S AN OMEN

**Comment by lefnire** [comment]
@lemoness are these shop-sprites? (aka, equipment page) Alas... all shop sprites need to be 40x40. Ideally submitted as a pull-request with replaced art, I'll G+ tutorial you sometime on that - but in the mean-time this method works

**Comment by lemoness** [comment]
Equipment page and reward store. Will crop away, sigh. Figured it was
inevitable ;p

**Comment by lemoness** [comment]
Okay @lefnire, here you go! 
![cutlass1icons2x](https://cloud.githubusercontent.com/assets/3494081/3579883/d37b9e4c-0bca-11e4-8b51-17eb805a4516.png)
![cutlass2icons2x](https://cloud.githubusercontent.com/assets/3494081/3579884/d37e0560-0bca-11e4-9ca6-6fad42515e56.png)
![dashingbandanaicons2x](https://cloud.githubusercontent.com/assets/3494081/3579885/d37e7b9e-0bca-11e4-8668-e31173ee6f4e.png)
![dashingbroadicons2x](https://cloud.githubusercontent.com/assets/3494081/3579886/d38a0fea-0bca-11e4-9cda-9d3629ddc5ba.png)
![dashingeyepatchicons2x](https://cloud.githubusercontent.com/assets/3494081/3579890/d3998b00-0bca-11e4-95fa-d9e62c9f4969.png)
![dashingshieldicons2x](https://cloud.githubusercontent.com/assets/3494081/3579888/d38d065a-0bca-11e4-95b6-d3c68c032699.png)
![dashingslimicons2x](https://cloud.githubusercontent.com/assets/3494081/3579887/d38a2264-0bca-11e4-90f0-4e0c6b8d078d.png)
![dashingswordicons2x](https://cloud.githubusercontent.com/assets/3494081/3579889/d38f3880-0bca-11e4-8510-f57ecffb1bec.png)
![junebroadicons2x](https://cloud.githubusercontent.com/assets/3494081/3579893/d9083b18-0bca-11e4-824a-a86b071af4d2.png)
![junehelmicons2x](https://cloud.githubusercontent.com/assets/3494081/3579894/d90a0e7a-0bca-11e4-8bc2-4b9fd83d14d7.png)
![juneicons2x](https://cloud.githubusercontent.com/assets/3494081/3579895/d90b6edc-0bca-11e4-923b-02b7eaee7fae.png)
![mermagebroadicons2x](https://cloud.githubusercontent.com/assets/3494081/3579896/d90c9b40-0bca-11e4-9c2e-8d745b3142ec.png)
![mermagecapeicons2x](https://cloud.githubusercontent.com/assets/3494081/3579897/d90dac06-0bca-11e4-9f14-12a335e04074.png)
![mermagehelmicons2x](https://cloud.githubusercontent.com/assets/3494081/3579898/d90f614a-0bca-11e4-9328-25bd0f7d7457.png)
![mermageslimicons2x](https://cloud.githubusercontent.com/assets/3494081/3579899/d9166ddc-0bca-11e4-8a34-40dd2a76b3aa.png)
![mermageweaponicons2x](https://cloud.githubusercontent.com/assets/3494081/3579900/d918e404-0bca-11e4-9fe0-670351d5a40b.png)
![rainbowarmoricons2x](https://cloud.githubusercontent.com/assets/3494081/3579902/d91d5840-0bca-11e4-9d04-43c7a3c82553.png)
![rainbowhelmicons2x](https://cloud.githubusercontent.com/assets/3494081/3579901/d91c7efc-0bca-11e4-9b48-f98704b221e3.png)
![rainbowslimicons2x](https://cloud.githubusercontent.com/assets/3494081/3579903/d91eff56-0bca-11e4-8155-d61284d3c86e.png)
![roguebroadicons2x](https://cloud.githubusercontent.com/assets/3494081/3579904/d9273946-0bca-11e4-9c63-94c03fc252aa.png)
![rogueeyepatchicons2x](https://cloud.githubusercontent.com/assets/3494081/3579905/d92abf62-0bca-11e4-96fa-6e146362310b.png)
![roguehaticons2x](https://cloud.githubusercontent.com/assets/3494081/3579906/d92c21d6-0bca-11e4-9f19-f7869b73d6c4.png)
![rogueslimicons2x](https://cloud.githubusercontent.com/assets/3494081/3579907/d92c2276-0bca-11e4-9188-8793e51317e4.png)
![seahaelerwandicons2x](https://cloud.githubusercontent.com/assets/3494081/3579908/d92e8ea8-0bca-11e4-8412-4ef028f6ab57.png)
![seahealerbroadicons2x](https://cloud.githubusercontent.com/assets/3494081/3579909/d9367f6e-0bca-11e4-9149-67182e4c0c11.png)
![seahealercrownicons2x](https://cloud.githubusercontent.com/assets/3494081/3579910/d93bd09a-0bca-11e4-9030-a80275bd241a.png)
![seahealershieldicons2x](https://cloud.githubusercontent.com/assets/3494081/3579911/d94096b6-0bca-11e4-9153-bb223fd0a65b.png)
![seahelercrownicons2x](https://cloud.githubusercontent.com/assets/3494081/3579912/d9409e68-0bca-11e4-86dd-7ef5d20b5a73.png)
![sehealerslimicons2x](https://cloud.githubusercontent.com/assets/3494081/3579913/d941216c-0bca-11e4-9a2e-c25e9ebec664.png)
![snowballicons2x](https://cloud.githubusercontent.com/assets/3494081/3579914/d941623a-0bca-11e4-85a5-2b433a47b8c1.png)

**Comment by lemoness** [comment]
Submitted pull requests for all of them.
