### ISSUE TITLE
Level icon tooltips are lost in current herobox style

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3704]
With the new style for display of character levels, the tooltips on buffs and the Rebirth badge are hidden behind the herobox:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3547183/7444f7ce-0892-11e4-90f3-94048edc81c8.png)

I've seen this occur on both Chrome and Firefox.

**Comment by deilann** [comment]
I like your avatar. So whimsical!

**Comment by ellenhutchings** [comment]
If someone's going to fix this it should be considered with #938 and provide some information to new users about what buffs are, other than just "Buffed"

**Comment by lefnire** [comment]
Whoever tackles it, give `tooltip-append-to-body` a whirl (CTRL+F tooltip-append-to-body at http://angular-ui.github.io/bootstrap). Mobile now, so can't check

**Comment by deilann** [comment]
Disagree wrt giving more info there on "Buffed" -- not enough room in a
tool tip. More info on what buffs people have should be under stats. If
someone has multiple buffs, that would get unweildy fast, and wouldn't be
particularly useful without.

**Comment by deilann** [comment]
...totally thought that was a different ticket, about the explaining _what_
buffs a player has. Don't mind me.

**Comment by negue** [comment]
The problem doesn't exist anymore (tested on local version).  So this can be closed.
