### ISSUE TITLE
HUGE to-dos bug (well, huge for me)

### ISSUE THREAD

**Issue by Sapsality** [HabitRPG/habitica#3706]
Hi, dear support master

I place my to-dos in a very specific order and I've been experiencing a problem for like a week now 
When I move even 1 of my to-dos, they all get severely mixed up
Same thing happens when I refresh habitrpg page and sometimes when i click on resync button

Is there a way to fix it?
Sincerely yours, 
I_LOVE_MATT_DAMON_3000

**Comment by deilann** [comment]
I don't have time to search myself, but if you search the issues, there's a
ticket all about this. It includes more details on why, but the workaround
is to clear your completed to-dos before resorting.

**Comment by Sapsality** [comment]
KK, I'l look through the issues
Thanks :)
