### ISSUE TITLE
Can't click on mobile or log in on app

### ISSUE THREAD

**Issue by Visi78** [HabitRPG/habitica#3708]
My user id is Cassandra Case Carpenter
I cannot click on the play button on the mobile site, I click and nothing happens:
I've tried clearing my cookies, my cache, and a hard refresh.
Since I cannot open the mobile site, I've tried manually typing my API into the boxes when trying to use the app, clicking on the submit button gets no response.

**Comment by deilann** [comment]
It may be that your mobile browser is not modern enough to render the site.

**Comment by negue** [comment]
@Visi78 Browser Name? Version? Mobile OS? OS Version?

**Comment by negue** [comment]
Closing this for now, if this problems still happens, we'll reopen this issue.
