### ISSUE TITLE
Stale party quest can't be removed

### ISSUE THREAD

**Issue by sobachatina** [HabitRPG/habitica#3709]
We had a party member start a quest with the party.

Some lesser-active party members were taking a long time to respond to the quest. The party member who started the quest got frustrated and left the party.

Now we have the stale quest in our party and can't do anything about it. When party members try and accept the quest it doesn't ever mark them as having accepted.

The quest can't be cancelled, it can't be started. No other quests can be started because there is already the stale quest active.

How do I fix this without disbanding the party and forming a new one?

**Comment by lefnire** [comment]
Bit of a hack fix above. Someone will have to leave the party and rejoin. Leaving a group now fixes `group.leader` and `group.quest.leader`, if either is assigned to someone who's no longer a member.
