### ISSUE TITLE
Socket.io causes data loss

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#371]
I've added an issue in socket.io's issue tracker (https://github.com/LearnBoost/socket.io/issues/1157) that affects HabitRPG. When socket.io cannot connect to the server, what it does is it retries. However, it uses an unbounded exponential backoff. This means that the time between retries increases exponentially...and the time between them can perhaps get to be **hours** long, since it appears to be unbounded.

Thus, if I lose connection to the Internet for a few hours because I'm typing away in a word processor and adding a few to-do items as I think of them, the time between retries might have gotten to be several hours long. That means that if I reconnect to the Internet for **an hour or two**, _that might not be long enough for HabitRPG to bother retrying_.

Can you please inform the user of when they are disconnected from the Internet (that doesn't happen on Chrome currently) and, if an upper bound can't be set to something reasonable like a minute in socket.io, allow them to manually force a retry like Gmail does?

**Comment by Olathe** [comment]
I found out that the upper bound is configurable: https://github.com/LearnBoost/Socket.IO/wiki/Configuring-Socket.IO (text search for "reconnection limit defaults to Infinity")

**Comment by lefnire** [comment]
Oh! That's really good to know. So is there an option to pass in for maximum upper bound? I dont' know why the "offline" message isn't showing, it might be a static / z-index header issue @SlappyBag ? I'll look into this

**Comment by lefnire** [comment]
Ok, perfect, this is really handy. I'm not going to be available till tonight, but I'm setting this up priority - thanks for finding this @Olathe

**Comment by Olathe** [comment]
Thanks :)

**Comment by lefnire** [comment]
I know I said not till tonight, but I just pushed - it's quite important. It will kick in with the next server restart (in a few hours). Not sure how we can test this, except but not hearing data loss reports :) I set the cap to 5m, think that's good?

Knowing what I do about HabitRPG, its codebase, and its bug history - I don't think you realize how important a fix you just provided me @Olathe.

**Comment by ericwilmoth** [comment]
Hope it works! Keep up the good work!

**Comment by lefnire** [comment]
this also fixes "disconnected" message, was z-index indeed. I checked 'reconnection limit' on the client, looks intact. Hopefully this will fix us!
