### ISSUE TITLE
I screwed up creating a challenge. I ended it without awarding gems. Now I have zero gems

### ISSUE THREAD

**Issue by FLJIM560** [HabitRPG/habitica#3710]
I was trying to create a challenge to gift 4 gems to a party member. My wireless keyboard can betray me at times. I created a challenge with a 43 gem prize by mistake. I ended the challenge without choosing a winner, thinking the gems would go back into my account. The challenge is gone. Unfortunately, so are my 43 gems. Can I get them restored please.

Thanks,

Jim
2419a180-11e2-4266-8466-93160c1daf6a

**Comment by SabreCat** [comment]
I can straighten that out for you. You had exactly 43 Gems before running into this issue?

**Comment by FLJIM560** [comment]
Yes...43. Thanks for your help.

**Comment by SabreCat** [comment]
There you go! Reload the page and your Gems should reappear.

I believe the problem where ending a challenge without a winner doesn't refund Gems is documented elsewhere, so I'll close this for now.

**Comment by FLJIM560** [comment]
Thank you again. What is the proper way to end a challenge without awarding gems, award them to myself?

**Comment by deilann** [comment]
Indeed! Which is awkward because they you get a badge. However, if you edit
the name of the challenge, refresh, and then end it, you can at least make
it not so awkward in the profile ish kind of.
