### ISSUE TITLE
Level up too much

### ISSUE THREAD

**Issue by takoyu** [HabitRPG/habitica#3711]
I started out at Level 13 this morning. On average, I level up once a day, so I expect to be Level 14 by the end of today. However, when I checked off a few dailies (2-3), I somehow went up to Level 16. The dailies I checked off are either green or blue.

**Comment by deilann** [comment]
There was an error with the Drag'on, which caused it to trigger defeated,
which gave everyone 800 XP. You can use Fix Character Values to go down if
you want, or you can just accept it. :) It shouldn't repeat itself.

**Comment by takoyu** [comment]
Thank you, deilann! It's nice to be boosted up by 3 levels, but I'm going to tune it down. I'd rather earn my way there. :)

**Comment by deilann** [comment]
np! Glad to help.
