### ISSUE TITLE
Acquired gold from a negative habit

### ISSUE THREAD

**Issue by Moonie123** [HabitRPG/habitica#3713]
I refreshed my habitrpg tab about 5AM central time and clicked on the negative buttons for a few habits I'd been neglecting. In the corner where all the usual pop ups tell you what's happened, I noticed "Leveled up" even though I hadn't gained experience from the negative habits. My health went down a little, xp stayed the same and mana stayed the same.

I can't remember what level I was so I don't know if that level actually applied to my character. But then I looked up and saw that my gold went from 10 to 100 after clicking only three negative habits.

**Comment by deilann** [comment]
Issue with the Drag'on quest triggering completed early. Check Tavern for
more info.
