### ISSUE TITLE
Quest damage not updated after World Boss bug

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#3715]
Hey. I'm sure you guys have been overwhelmed with comments after the World Boss bug (http://habitrpg.wikia.com/wiki/FAQ#Where_Did_the_Drag.27on_Go.3F), but I just wanted to comment that damage values for boss quests haven't been updated since then. Since logging on after cron, I didn't note any damage to or from the boss on the quest a party member and I have been on. It's a two-member quest, so every bit of progress counts!

Thanks for your help. You guys have done a great job. Best of luck working out the bug!

**Comment by deilann** [comment]
Yes, we know about this complication. It has to do with what happens to
personal damage after a boss is defeated. Thank you. It's just
unfortunately something that happened whilst Tyler is in bed. But thank you
for the report!
