### ISSUE TITLE
Jumped levels, got 100 gold?

### ISSUE THREAD

**Issue by BobDole56** [HabitRPG/habitica#3717]
I signed in today, clicked a single light blue habit and jumped from level 6 to level 10 and jumped from just over 30 gold to 130 gold. Even with programming knowledge I have no idea what may have caused it but I know I can't decrease my level again, it'll just give me negative XP.

**Comment by FrancessFractal** [comment]
Yep, same thing happened to me.  Logged in today, and am lvl 7 instead of lvl 2, and gained two undeserved eggs, plus about 90-100 gold.

**Comment by DrewbyPls** [comment]
Exact same thing happened to me.  I jumped from level 4 to level 8 and from 24 to 124 gold.

**Comment by ghost** [comment]
I had the same issue. got over 800 experience and gained 5 levels

**Comment by SabreCat** [comment]
See #3712.
