### ISSUE TITLE
Got 900 exp after using sync

### ISSUE THREAD

**Issue by Littlenicky89** [HabitRPG/habitica#3719]
Hi, so I started using HabitRPG a few days ago, was level 2 yesterday when I finished for the day, logged in today and saw that the dailies didn't refresh so I hit the Sync button, after that I received 900 exp, I thought it's maybe a bug so I continued regularly and when I finished a daily suddenly I am level 7 with 102 gold..

Any chance to return it to the way it was before? Kinda confusing for me now being level 7, and I probably missed a few key stuff jumping from 2 to 7.

Thanks, amazing work by the way, really great tool to improve your life.

**Comment by lefnire** [comment]
See https://github.com/HabitRPG/habitrpg/issues/3712 . There's a world boss that's being battled, and it got defeated too early (thus the exp + gp)
