### ISSUE TITLE
Chrome App - Work days

### ISSUE THREAD

**Issue by alexarze** [HabitRPG/habitica#372]
I'm having trouble because I'm usually using HabitRPG for school and working out, but the web app is tracking me down on the weekends when I don't need it to. It would be AMAZING if you added a really simple fix that would let you choose "work days" where it was on, and "off days" where it was off :)

**Comment by lefnire** [comment]
do you mean the [chrome extension](https://github.com/lefnire/habitrpg-chrome/issues/31)?

**Comment by StanLindsey** [comment]
If you're talking about the [www.habitrpg.com](https://habitrpg.com/) interface you can edit any daily to only take affect on certain days.

else if you're talking about the [Chrome Extension](https://chrome.google.com/webstore/detail/habitrpg/pidkmpibnnnhneohdgjclfdjpijggmjj?hl=en) judging your web browsing then we've had a couple people requesting this, so its now my number 1 priority in terms of the web-app. I'll get a simple toggleable on/off out in the next day or so other work permitting.

Thanks for the input! 

I'm going to close this as it should be one of the above issues.  Follow up in [#31](https://github.com/lefnire/habitrpg-chrome/issues/31) for the web app issue.

**Comment by alexarze** [comment]
Yes! Sorry, the chrome extension. That's great! Thanks so much! Haha it sounds like a pretty easy fix, as long as I know how the extension works. I might open it up and mess around with it just to see how you have it set up. If you have it as a javascript looking at whether or not it is within the user-set time, then run the code, all you would have to do is add an if function right before that looking to see if it's on a user-allowed day. Then continue with the rest of the code.

**Comment by StanLindsey** [comment]
Check out the repo, I pretty much did exactly as you described for the next push. =D 

Thanks for the input all the same!
