### ISSUE TITLE
Changing level via fix character values does not adjust attribute points

### ISSUE THREAD

**Issue by itokro** [HabitRPG/habitica#3720]
After the Drag'on glitch last night, I went up a couple of levels. I've been into "fix character values" and taken my level back down to what it was before, but when I jumped levels, I also got attribute points. Since I'm on auto-allocation, these automatically went into my stats, so now I have higher stats than a character of my level ought to. Any way to undo this?

**Comment by nihongineer** [comment]
I just started so the auto-level cleared the tutorials for me.  Even after resetting the account to level 1 I already have the marketplace open and the wolf egg.  My progress bar also shows the 1k point jump in my history even after the reset.

**Comment by deilann** [comment]
@itokro Don 't worry about it -- it'll self heal as you level up.

@nihongineer If you go to settings > site, you can reshow tutorials. Don't worry so much about unlocking drops early, or whatnot. Consider it... a thank you for dealing with the glitch! Unfortunately, there's nothing that can be done about progress, either, but it's one day, and then the future should be golden.

**Comment by itokro** [comment]
Looks like this isn't self-healing for me: I just levelled up honestly (well, semi-honestly - backstab was involved) and gained an extra attribute point with the added level. So when I get back to the level that the Drag'on glitch took me to (when I next level up), I'll still have too-high stats for a character of that level.

**Comment by deilann** [comment]
A few points really shouldn't make that big of a difference. :) Consider
it... maybe a bonus for having to deal with it. What level are you right
now?

**Comment by itokro** [comment]
Level 20. Which works out to about 5 attribute points per stat (although mine aren't evenly divided) - so having an extra 2 in one stat does feel like a significant unmerited boost.

**Comment by deilann** [comment]
Yeah, I can see it at that point feeling super awkward.

Someone with database access might be able to fix it for you, but if not,
you can opt not to apply the points. I know a rebirth, if it's in your
future, will fix it, but that's so far out. :/

**Comment by deilann** [comment]
Oh man, I don't know why I didn't think of this earlier. @itokro -- send me your UUID and I'll set you up with a class change. If you don't want to change classes, you'll be able to just select the same class and it should de-allocate and fix the points. (Hopefully.)

**Comment by deilann** [comment]
Kk, I've upped you by 3 gems, if the class change fixes it, go ahead and close this ticket. :)

**Comment by itokro** [comment]
Thanks, @deilann - that does indeed fix things for me! I'm just wondering if this should be kept open as a more general issue of "should changing level via "fix character values" automatically adjust attribute point balance accordingly?" If so, I'll update the title to reflect this

**Comment by deilann** [comment]
Glad that worked out! :) Yeah, I think a title of "Changing level via Fix
Character Values does not properly adjust attribute points" would be better.

**Comment by itokro** [comment]
Done!

**Comment by Alys** [comment]
This had already been reported in https://github.com/HabitRPG/habitrpg/issues/2041 so I'll close this one. Anyone who wants to follow the progress of this bug fix can subscribe to notifications in the other issue (button in right-hand column).
