### ISSUE TITLE
No Loot for Drag'on

### ISSUE THREAD

**Issue by MatthiasMNG** [HabitRPG/habitica#3722]
I received a notification today that I have received some loot for the boss battle. However, I did not see the mount/pet in my stable nor did I gain the 90 gold that I was supposed to get.

**Comment by Alys** [comment]
Matthias, the notification was an error and no one was meant to get the mount, pet, or gold. See this [blog post](http://blog.habitrpg.com/post/91584540316/wow-whats-going-on) for details, and also this issue: https://github.com/HabitRPG/habitrpg/issues/3712
