### ISSUE TITLE
Lost new pet

### ISSUE THREAD

**Issue by lemna78** [HabitRPG/habitica#3726]
I recently found a cotton candy pink potion and hatched a cotton candy pink tiger.  However, when I checked my pets the cotton candy tiger was no longer there and the potion was gone as well.  I waited a little while for it to resolve itself (as it has before), but no luck.

**Comment by Alys** [comment]
Please try clearing your browser's cache and then reloading the Pets page and the Market page. Do either the pet or potion appear?

**Comment by lemna78** [comment]
No. I'm using Chrome, and I cleared my browsing history for the past 4
weeks.  The pet is still not there.

Thanks,
Robin

**Comment by deilann** [comment]
Robin, clearing your history doesn't clear your cache. The two are
different. :)

**Comment by lefnire** [comment]
Probly caught the server on a downswing (was in pretty bad shape during
dilatory madness past few days), what's uuid we'll give you gems to buy
back

**Comment by Alys** [comment]
lemna78 : has the pet or potion reappeared? If so, can you please close this issue? If not, then [clear your cache](https://support.google.com/chrome/answer/95582?hl=en) (be sure to select "Cached images and files" or "Empty the cache" or any other option containing "cache"), and reload and look again.

**Comment by deilann** [comment]
And if still not, please give us your UUID, so we can do something about it!

**Comment by lemna78** [comment]
The pet has not reappeared.

UUID is 062c28d3-4619-41d9-9938-fb02b9bd29ab

Thanks!

**Comment by lefnire** [comment]
@lemna78  updated you, check now

**Comment by lemna78** [comment]
Thank you! :)
