### ISSUE TITLE
Error purchasing Swashbuckler Bandana

### ISSUE THREAD

**Issue by uncleverone** [HabitRPG/habitica#3727]
Adds to inventory and subtracts gold, but appears not to sync with server. On refresh, purchase is gone, gold is at level prior to purchase.

After purchasing and then syncing, JS console shows:

```
Bought Swashbuckler Bandana
TypeError: Cannot read property 'streakBonus' of undefined
    at Object.fn (https://habitrpg.com/app-0fd192e9.js:22:29704)
    at i.$digest (https://habitrpg.com/app-0fd192e9.js:7:4825)
    at i.$apply (https://habitrpg.com/app-0fd192e9.js:7:6571)
    at HTMLAnchorElement.<anonymous> (https://habitrpg.com/app-0fd192e9.js:8:4264)
    at HTMLAnchorElement.n.event.dispatch (https://habitrpg.com/app-0fd192e9.js:2:6404)
    at HTMLAnchorElement.r.handle (https://habitrpg.com/app-0fd192e9.js:2:3179)
```

**Comment by Alys** [comment]
Please try this:
- log out of HabitRPG
- clear your browser's cache
- stop and restart your browser (i.e., close ALL browser windows)
- log back into HabitRPG
- reload the page
- buy the bandana again

**Comment by Alys** [comment]
Possibly related: https://github.com/HabitRPG/habitrpg/issues/3733 _"1 item [bandana] in the shop area below Rewards column cannot be bought, despite having enough coins?"_

**Comment by gitmee** [comment]
The same thing happened to me. I bought the Swashbuckler Bandana before I turned level 10 then changed my class. All seemed to be well, I had my hat for several hours after that. When I joined a guild, the hat disappeared from my avatar and inventory and I found that I have an additional 40 GP. I'm unable to repurchase since I've already selected my class. I hope I can get my item back, I saved GP specifically for that hat.

Edit: My User ID is `48e75f91-df09-4ac0-9fe4-bd4d7d6dcb91`

**Comment by deilann** [comment]
@gitmee -- I've tossed you 6 gems, so you can hop back to warrior and then
back to the class you'd like to actually be. Go ahead and swap back to
warrior (go to the stats page to do this) and try to repurchase the
bandana. Afterwards, both refresh and sync. If it sticks, then use the
remaining 3 gems to go back to your preferred class.

**Comment by gitmee** [comment]
@deilann Hi deliann, I reverted back to warrior and bought the Swashbuckler Bandana again, but each time I either reload the page or click the sync button, the bandana goes back into the store and I get my GP back again as if I never bought it. This happens every time I do this, both reload and sync with the same result.

**Comment by deilann** [comment]
Okay, that makes it sound to me like there's definitely an issue with
purchasing the item itself. @lefnire is going to have to handle this 'un.
Go ahead and switch back to your preferred class. :) If you need to switch
back again for some reason or another, I can always toss you some more gems.

**Comment by Alys** [comment]
Wild stab in the dark, but I don't suppose this is related to SabreCat's
recent change to the cost of the Bandana? Perhaps the production
site/database uses the old cost in one place and the new one in the other
and so the first stage of the purchasing works but the final stage does not?
https://github.com/HabitRPG/habitrpg-shared/commit/424cf1a5bf9b4bd02666a1bd3120303b531cabcd

BTW, gitmee and others with this problem, if you can't buy the bandana
before the cost on the production site goes up from 40 to 60 GP, you should
definitely use Fix Character Values to give yourself the extra 20 GP needed
to buy it.

**Comment by Alys** [comment]
This isn't easily reproducible. :(  Yesterday, using a test account (but on the production site), I bought all of the summer gear, and it's all still in my equipment list. UUID eeb9b8f0-ae33-4032-ae19-acaf50180e82

**Comment by nihongineer** [comment]
I think Alys is on to something with the price of the item changing.  I lost the bandana every time I synced until I had over 60 gold.  I then received two separate notifications, one for -40 gold and a second for -20 gold and the bandana stayed put.  So far no more changes after syncs.

**Comment by Alys** [comment]
Excellent work @nihongineer !!! I did not think for a moment to try that. I've confirmed it though: with 59 gold, I cannot permanently buy a bandana, with 60 gold, I can!

@uncleverone and @gitmee and anyone else with this problem: Use Fix Character Values (Settings -> Site) to give yourself at least 60 GP, then try to buy the headwear you've been unable to keep. Don't consider this to be "cheating" - you've earned the gold by having to deal with this bug!

@SabreCat : Even though the new 60 GP prices aren't showing up in the rewards column, it's looking like part of the 40->60 GP change might have gone live. Is it possible to revert that?

**Comment by deilann** [comment]
Shared info with Tavern!

**Comment by Alys** [comment]
Also confirmed in Tavern by LostInAForest (b92c0adf-1741-47b4-8710-163b906409ed):
"YAY! i payed 40 gold immediately upon purchase and it took the remaining 20 after i hit sync, and the hat's still there. i did only have 50-ish gold when trying earlier so that all makes sense then."

@nihongineer has definitely hit upon a good work-around.

**Comment by lefnire** [comment]
See https://github.com/HabitRPG/habitrpg-shared/commit/9f0e6607c5943bd921d1b6c33b7259de47389860 , we just needed to run `grunt` on habitrpg-shared. When server !== client, it's usually because grunt wasn't run

**Comment by deilann** [comment]
@lefnire It looks like the price for the helms being lower was purposeful
(according to @lemoness) because of added accessories, so the hope would
actually be to have the price go back to 40 GP, not go up to 60 GP.

**Comment by lefnire** [comment]
k, I'll leave it ya'll to set the correct cost values (I'm outa that convo loop) - I'm just making sure server matches client so people don't experience a bug

**Comment by deilann** [comment]
kk, sounds good. :)

**Comment by SabreCat** [comment]
Oof. Looks like I did more harm than good, here. Sorry, all!
