### ISSUE TITLE
Party Boss not taking damage

### ISSUE THREAD

**Issue by MKBGeorgi** [HabitRPG/habitica#3728]
Group ID: d2834408-ca72-4878-b38c-558ae5bbcc70

Chat window reports that Vice's Shade took 8.8 points of damage, Vice's shade HP bar is still full.  Started when Dread Dragon of Dilatory crash happened.

Thank you much, 
Melissa

**Comment by deilann** [comment]
The HP bar is still going to look full because it's such a small amount of
damage compared to the max HP.
