### ISSUE TITLE
Can't get off mount

### ISSUE THREAD

**Issue by Keleviel** [HabitRPG/habitica#3729]
I'm still riding my mantis shrimp mount, even though it was removed from my inventory. The problem is, now I can't get off! Getting another mount might do the trick, but I'm still new, and I don't have any. What do I do?

**Comment by deilann** [comment]
You'll have to get another mount, unfortunately. We have a couple of options:

1) You can wait until the Dread Drag'on is defeated (should be soon enough)

2) You can wait until you have another mount of your own (no idea when that will be!)

or 

3) If it's really bugging you, I can set you up with a saddle, if you give me your UUID. However, I know that might niggle you in the future, when you're finishing up a mount collection. Not feeling like you earned it.

You are the only one who can judge which is best!

**Comment by Keleviel** [comment]
Hrm. It is bugging me, but I don't want to fudge my collection in the future, once I start collecting. Would it be possible for you to give me a mount of whatever kind for an hour or so? Long enough for me to get off the mounts entirely, but then you take it back afterwards, so that I don't have a black spot in terms of mounts that I earned? If so, my uuid is f95c1075-a6d5-45b5-8a65-dd2464c2308d. If not, then I'll just wait until I get another one.

**Comment by deilann** [comment]
Unfortunately, not. All I can do is get you the gems for a saddle.

However, I will open an issue that I think we should have a "dequip all
pets/mounts/equipment" button, as that will fix many a problem. It probably
won't get coded in time to help you, but it may help others in the future!
:)

**Comment by deilann** [comment]
Here it is: https://github.com/HabitRPG/habitrpg/issues/3730

**Comment by lefnire** [comment]
I'll fix you @Keleviel , one sec

**Comment by deilann** [comment]
Tyler you are the best. The best at space. :)

**Comment by deilann** [comment]
I keep underpromising 'cause I don't want to speak for your abilities, and
then you overdeliver like whoa.

**Comment by lefnire** [comment]
@Keleviel all set. 

> The best at space. :)

@deilann I don't get it?

**Comment by deilann** [comment]
Sorry, it's a Portal 2 reference. You just keep being awesome, that's all.
Going the extra mile, to clean this up.

**Comment by lefnire** [comment]
Aw, thanks man!

**Comment by Keleviel** [comment]
Oh, hey, I'm no longer riding the mount. Thanks a lot!
