### ISSUE TITLE
Pets not being enabled for everyone at lvl 4

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#373]
```
db.users.count({ 'stats.lvl':{$gt:3}, 'flags.petsEnabled':{$exists:0}})
> 1165
```

Woa :o Temp fix is `db.users.update({ 'stats.lvl':{$gt:3}, 'flags.petsEnabled':{$exists:0}  },{ $set:{ 'flags.petsEnabled':true } })`, but need to figure out why it's not happening for some people

**Comment by lefnire** [comment]
i'm stupid, not everyone logged in since

**Comment by switz** [comment]
just wanted to let you know I had a nice laugh at this :smiley_cat:

**Comment by lefnire** [comment]
Hoh boy.
