### ISSUE TITLE
Egg hunt challenge ended prematurely with "NaN" of eggs found.

### ISSUE THREAD

**Issue by bjbishop** [HabitRPG/habitica#3732]
I just started up the egg hunt challenge again for my party about 5 days ago, so July 8th maybe?  I logged in to and found that my character, Dr. Telnet, found NaN plain eggs and our challenge was ended!  Here's the log from my party status screen.  Great concept and loving the site!  Keep up the great work!

All items found! Party has received their rewards.
-9 hours ago+1 
Dr. Telnet found NaN Plain Eggs.
-9 hours ago+1 
bassdaddy found 0 Plain Eggs.
-2 days ago+1 
Edoran found 0 Plain Eggs.
-2 days ago+1 
usammmy found 3 Plain Eggs.
-2 days ago+1 
rafael.moreira found 5 Plain Eggs.
-2 days ago+1 
Dr. Telnet found 3 Plain Eggs.
-2 days ago+1 
rafael.moreira found 0 Plain Eggs.
-3 days ago+1 
Edoran casts Earthquake for the party.
-4 days ago+1

**Comment by deilann** [comment]
Follow this issue here: https://github.com/HabitRPG/habitrpg/issues/3712  :)
