### ISSUE TITLE
1 item in the shop area below "Rewards" column cannot be bought, despite having enough coins?

### ISSUE THREAD

**Issue by LaurenGalleta** [HabitRPG/habitica#3733]
Newbie here, hi... so there is a bandana in the shop area below the "Rewards" column and every time I click on it, it says -40 coins and that I got the bandana - I can even see my character wearing it. However, when I click the sync button or refresh the page, it says +40 coins and I lose the bandana. I tried to purchase a different item and it worked just fine. The item I'm trying to buy is a "special edition" summer item, if that helps at all.

**Comment by deilann** [comment]
Check out this ticket that Alys referenced: https://github.com/HabitRPG/habitrpg/issues/3727 :)

**Comment by Alys** [comment]
@LaurenGalleta : There's a fix for this at https://github.com/HabitRPG/habitrpg/issues/3727#issuecomment-48976043 but in brief: Use Fix Character Values (Settings -> Site) to give yourself at least 60 GP, then you will be able to buy the headwear you've been unable to keep.
