### ISSUE TITLE
Not getting the 25 Gem max

### ISSUE THREAD

**Issue by clmmerrill** [HabitRPG/habitica#3734]
In June I got the message I was only allowed 25 gems per month which is fine. So, to buy more quests for party I waited until July. Then you all came out with background (really cool) so I spent 7 gems on that. Then I used 4 gems for newest quest. I don't think I did but maybe I bought another quest for 4 gems. But to see how many I have left I just tried to buy the rest. Habitrpg said I only had 6 left. I add really bad but I am sure that is not 25. 

I could only find gem count =25 in the json file.

Thanks
Cindy

**Comment by deilann** [comment]
Did you buy only one background, or the background set? Because the
background set was 15 gems.

**Comment by clmmerrill** [comment]
I bought the whole set. I didn't remember that it cost 15 gems. I looked
back on page and it said 7. Sorry for bothering you.  Definitely adds to 25
now.
Sorry again,
Cindy

**Comment by deilann** [comment]
No worries!

I think it may be unclear once the set has been purchased. I'll look into that. :)
