### ISSUE TITLE
"Strong" in a pop-up message instead of actual bolding

### ISSUE THREAD

**Issue by Mousekiro** [HabitRPG/habitica#3736]
When a glitch caused a quest to complete for me today -- the first I've ever had -- I noticed that the congratulations message had the text "(strong)Megan(/strong)" in it instead of the word "Megan" being bold, which I presume was intended. (It had proper triangle brackets, not parentheses, but when I type those here it _does_ auto-bold, oddly enough.)

I'm in Firefox 30.0, in case that affects anything.

**Comment by SNikon** [comment]
If using jquery then when $(element).text( 'a string' ) will disregard html tags while $(element).html( 'a string' ) will give you the correct effect.

**Comment by Alys** [comment]
Also reported here: https://github.com/HabitRPG/habitrpg/issues/4130 with a currently-available quest. We'll use that report to follow the progress of this bug.
