### ISSUE TITLE
World Boss Damage Cap Affecting Party Quests

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3737]
@lefnire I was capped at 900 damage against a boss today; not very happy about that -- I specifically did an "all out" before doing a Rebirth and now we're going to be stuck for weeks fighting this boss because of that. Thought you reverted the cap for parties?

**Comment by deilann** [comment]
(Sorry this was so grumpy @lefnire -- I'm not actually that grumpy anymore. I was just half asleep and upset. I still <3 you. And it's not going to be weeks. I was being hyperbolic.)

**Comment by deilann** [comment]
Thank you Tyler. <3 And again, sorry for my grouchiness. I should have
waited until the AM to post the ticket.

**Comment by lefnire** [comment]
sorry bout that. Having some localhost troubles, won't be able to test+deploy till tomo

**Comment by deilann** [comment]
Shouldn't be an issue 'cause I rebirthed, so if I'm doing 900 damage, it'll
be a miracle. :P But with the number of tasks I have, we should bring down
Octothulhu fast enough!
