### ISSUE TITLE
Sign in Problem

### ISSUE THREAD

**Issue by godingly** [HabitRPG/habitica#3738]
I use Chrome Portable on Windows 7, and sometimes when I try to sign in (https://habitrpg.com/static/front#/tasks) (click the play button) - it doesn't open the sign in page. Instead, the page seems to be loading, and then reopens the same page (https://habitrpg.com/static/front#/tasks). 
Is there another way to sign in?

**Comment by Alys** [comment]
The next time this happens, please [open the Chrome JavaScript console](https://developer.chrome.com/devtools/docs/console), then reload the page, then try to sign in again. Copy all messages from the console and paste them into this issue.

**Comment by godingly** [comment]
POST https://habitrpg.com/api/v2/user/batch-update?_v=339&data=1405344914177&siteVersion=1 401 (Unauthorized) static-48b4e494.js:9
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1404859412.html:1
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by lefnire** [comment]
Hmm, looks like you're unauthorized... maybe logged in on an old account. Open up Chrome Console again, and delete the localStorage entries for habitrpg ([screenshot](https://www.evernote.com/shard/s17/sh/e88225ed-51c4-42a7-b2a5-10acc18b4e9e/149a023940e6c3c9e8824d45c25b36b7))

Do you know your UUID?

**Comment by Alys** [comment]
@godingly : Is this problem still happening for you? If so, please paste your User Id into this issue as plain text. See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

**Comment by godingly** [comment]
No, I uninstalled chrome portable and re-installed it, and it was solved.
