### ISSUE TITLE
disappearing items

### ISSUE THREAD

**Issue by crimsonpanda** [HabitRPG/habitica#3739]
So i've bought the kelp wrapped hat twice now with out having died for it to be taken away and i've lost it again and dont want to pay another 40 gold for it since i've already paid double price for it.

**Comment by deilann** [comment]
Usually when an item disappears, you end up getting the gold back, although that might not be immediately apparent. If you're not getting the gold back, you can always use Fix Character Values (It's under Settings > Site) to refund yourself the gold.

However, I'm feeling that this is related to https://github.com/HabitRPG/habitrpg/issues/3727 -- maybe check out that ticket.

**Comment by Alys** [comment]
@crimsonpanda : There's a fix for this at https://github.com/HabitRPG/habitrpg/issues/3727#issuecomment-48976043 but in brief: Use Fix Character Values (Settings -> Site) to give yourself at least 60 GP, then you will be able to buy the headwear you've been unable to keep.
