### ISSUE TITLE
Coral crown (healer) doesn't stay in the equipment

### ISSUE THREAD

**Issue by Lysambre** [HabitRPG/habitica#3740]
For three days now, I've been continuously re-buying and re-equipping the coral crown (for healer). 
As soon as I close the page though, it leaves my equipment. The gold is re-funded, so it's not a loss, but I'm still unable to keep that piece of equipment.
I'm already wearing the seahealer tail.

Thank you :)

**Comment by deilann** [comment]
Sounds like the coral crown version of https://github.com/HabitRPG/habitrpg/issues/3727 ! Looks like it's hitting all of them, unfortunately. Let's follow there.

**Comment by Alys** [comment]
@Lysambre : There's a fix for this at https://github.com/HabitRPG/habitrpg/issues/3727#issuecomment-48976043 but in brief: Use Fix Character Values (Settings -> Site) to give yourself at least 60 GP, then you will be able to buy the headwear you've been unable to keep.

**Comment by Lysambre** [comment]
It worked :). Thank you very much for letting me know ^_^.
