### ISSUE TITLE
Collection Quest ended prematurely because of "found NaN Plain Eggs"

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#3741]
My Party was doing the easter quest (not sure what it's called. but the one, where you have to collect 100 plain eggs). And during the dilatory bug stuff there were messages with "XY found .". I guess this is expected, as all quests didn't work correctly during that.
But Today the quest was finished, and the last message states "XY found NaN Plain Eggs". We were only at about 30 Plain Eggs. So it should not be finished yet.

As the NaN thing may be related to the dilatory bug I'm not sure if it makes sense to investigate that. Probably makes more sense to find out, why NaN causes the quest to end and to handle that corner case.

![screenshot from 2014-07-14 21 40 45](https://cloud.githubusercontent.com/assets/298062/3576087/eb5e6968-0b8e-11e4-8cc0-225bf5081c10.png)

**Comment by deilann** [comment]
Yeah, actually, if you go to the end of the Dilatory ticket (https://github.com/HabitRPG/habitrpg/issues/3712) that's what's being covered. Follow it there. :)
