### ISSUE TITLE
Sync unbuys equipment

### ISSUE THREAD

**Issue by carsonbarlow** [HabitRPG/habitica#3743]
Every time I sync, I get +40 gold and lose my Swashbuckler Bandana.

I am logged in at home and at work, and this is happening on my work log in.

**Comment by Alys** [comment]
This has already been reported here: https://github.com/HabitRPG/habitrpg/issues/3727

**Comment by deilann** [comment]
Check out this ticket: https://github.com/HabitRPG/habitrpg/issues/3727

It's all of the helms it seems, for the summer event equipment.

**Comment by deilann** [comment]
Well, fine Alys. :P Beat me to the punch.

**Comment by carsonbarlow** [comment]
Thanks guys!  Keep up the good work.

**Comment by Alys** [comment]
@carsonbarlow : There's a fix for this at https://github.com/HabitRPG/habitrpg/issues/3727#issuecomment-48976043 but in brief: Use Fix Character Values (Settings -> Site) to give yourself at least 60 GP, then you will be able to buy the headwear you've been unable to keep.

**Comment by carsonbarlow** [comment]
Thanks Alice!
