### ISSUE TITLE
Unable to check out of the Inn

### ISSUE THREAD

**Issue by jithincn** [HabitRPG/habitica#3745]
Hey,

I have checked out of the inn 3 to 4 times in the past one week but everytime I come back it still asks me to check out again and also shows the ZZZ sign around my charecter. How can I check out?

**Comment by deilann** [comment]
Are you waiting for the blue bar to finish before you click something else?

Click the "Check out" button, wait, then refresh. Tell me if you're still
in the inn.

**Comment by jithincn** [comment]
Hey,

No idea how but its working now !! Thanks a lot :)

**Comment by deilann** [comment]
Probably just a server issue. Glad it's sorted out! :)

**Comment by vermilly** [comment]
I am also unable to check out of the inn, and I tried what you said above but I still can't get my dailies to uncheck the next day or make the zzz's go away :(

**Comment by crookedneighbor** [comment]
@vermilly Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

**Comment by vermilly** [comment]
7a2caff8-af0f-4103-b6bb-523599559aa4

**Comment by crookedneighbor** [comment]
I can confirm that @vermilly 's user is set to `sleep: true`. I don't see anything out of the ordinary though.

So you're in the tavern, you click the green check out button, you wait for the blue bar to disappear from the top (signifying that the sync is complete) and you refresh, but you're still in the inn?

Can you give me some details about your operating system and web browser? Would you mind trying it in Chrome? [Here's a download link for Google Chrome.](https://www.google.com/intl/en/chrome/browser/desktop/index.html)

When on the HabitRPG site while using Chrome, press `cmd + option + j`, that should bring up the console. Try checking out of the inn and take a screenshot of the console. Drag that screenshot onto the message box in Github on a computer (won't work to try and upload a screenshot on the mobile site or send one via email).

If all that fails to bring up anything and you have a mobile device (iOS or Android), you could download the mobile app, go to settings and check out of the inn there. I'd be curious to find out if that works for you.
