### ISSUE TITLE
Error viewing profiles in sequence - some information belongs to previously-viewed user, not currently-viewed user

### ISSUE THREAD

**Issue by itokro** [HabitRPG/habitica#3746]
I've noticed when looking at other people's profiles in the Tavern that the gear and badge information doesn't seem quite right. After fiddling around for a bit, it looks like the following things are happening:
1. If I view Person A's profile and then view Person B's profile, Person B's equipment list will actually show me Person A's equipment. However, if Person B has equipment in slots that Person A is not using (e.g. Person B has a head accessory and Person A does not), then I'll get the right information for Person B for those slots only. (Verified that this isn't just a case of "costume and equipped items differ" by testing with (a) myself as Person A or B, and (b) new users under level 10 who can't have non-warrior-class items as Person B)
2. Sometimes, Person B's badge list will show me Person A's badges, but sometimes it'll show me Person B's badges. I can't confirm what determines whether the badge information is right or not, but it seems as though in general, if Person B has "better" badges, they're more likely to be correctly reported. For example, if Person B is Bailey, I see the "TownCrierNPC" badge on viewing her profile. Meanwhile if Person A is Bailey and Person B is not Bailey, I still see the "TownCrierNPC" badge on viewing Person B's profile.

**Comment by deilann** [comment]
Yeah. There is a ticket for this one, but it's hard to search for because the bug is kind of hard to put succinctly. So don't feel bad that you had a hard time finding it! And the badge bit is new, I think. The gear was known. I'll look it up in a bit, and link you there. :)

**Comment by deilann** [comment]
Here it is: https://github.com/HabitRPG/habitrpg/issues/2010

If you have any ideas of a better title for the ticket, so it's more searchable, do let me know!

**Comment by thepeopleseason** [comment]
"Stuck profile"?

**Comment by deilann** [comment]
@thepeopleseason That's a good one! I also just added "wrong profile info" and some other stuff. Feel free to tweak it!

**Comment by itokro** [comment]
Ah, I did see that issue but was thrown by the "party members" portion of the title - assumed for some reason that it was talking about a party-specific bug, e.g. something that only showed up while looking at people in your party header. May I replace "party members" with "public profile" to avoid future confusion of this nature?

**Comment by deilann** [comment]
You can't but I can! :) (Just quite literally you can't edit others'
tickets.)
