### ISSUE TITLE
Cannot login to iOS app with facebook UUID and API

### ISSUE THREAD

**Issue by trbedwards** [HabitRPG/habitica#3747]
I've copied and pasted my UUID and API from the habitRPG settings-->API.
I then press "submit" but nothing happens.

I can't login to the iOS app any other way. Please help!

**Comment by deilann** [comment]
I believe the iOS app has been updated to take username and password at
this point. Have you tried your username and password?

**Comment by trbedwards** [comment]
That’s the problem, I signed up using my Facebook account so I don’t have a conventional username and password.

**Comment by deilann** [comment]
Okay, before, what you had to do, was click a button that said you were
logging in with User ID/API Token. I haven't seen the new iOS app, so I'm
not sure. Is there a button to click to do that?

**Comment by trbedwards** [comment]
The button says "Use Facebook". I click on that and then it says "Until we add Facebook authentication, use your UUID and API Token to log in"

**Comment by deilann** [comment]
Okay, so are you clicking on that button, then putting in your UUID/API
Token in the field that pops up there, that says UUID/API Token, _not_
Username/Password?

**Comment by trbedwards** [comment]
Yep that's right

**Comment by trbedwards** [comment]
After that, clicking on "submit" does nothing

**Comment by deilann** [comment]
Just did it myself and it took a couple of clicks, but submit got me right
in. I think it took a couple of clicks because it needed to get out of the
keyboard.

It may be a pain, but perhaps try manually entering your UUID/API Token. It
may be that something in your clipboard is screwing things up.

**Comment by trbedwards** [comment]
I’ve tried both copy-pasting and manual. It still won’t work no matter how many times I press submit.
Thanks for the help though

**Comment by deilann** [comment]
There was a bit of a lag between pressing submit and it working, if that
helps. Maybe press it, wait a few seconds, and stare at it with hopes of
voodoo magic?

Another option is to get your account switched off of Facebook auth and
into an account with a username/password. @lefnire has to do that, and he's
kind of busy, so it can take a while, but it might be good for the long
haul. Email admin@habitrpg.com with a request for switching your account
over?

**Comment by lefnire** [comment]
@trbedwards what's your UUID? I wanna see if something on the acct is wonky

**Comment by trbedwards** [comment]
314cab7e-b396-499d-94ae-d06097023949

**Comment by lefnire** [comment]
Strange, I'm able to get on iOS with your uuid/api token - no errors. You may try uninstalling / re-installing?

**Comment by negue** [comment]
@trbedwards the Facebook Login was recently updated, could you try again?

**Comment by Alys** [comment]
I'm closing this since there's been no reply to negue's question for a while, but @trbedwards if you are still having problems, please tell us and we will reopen this.
