### ISSUE TITLE
Release Pets Feature [$75 awarded]

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3748]
As asked for, a bounty ticket.

Release pets would:
- [ ] make beastmaster stackable
- [ ] make all gen 1 pets undiscovered (no quest pets touched)
- [ ] be a gem purchasable item
- [ ] unlock upon first beastmaster
##

**Comment by SabreCat** [comment]
Yay!

**Comment by Alys** [comment]
I would also want to release all my gen 1 mounts, but would be happy if that was done with a different gem-purchasable item.

**Comment by deilann** [comment]
noted! That would definitely be a different item or I guess I could make it
the same item that triggers a modal with three functions: release gen 1
pets, release gen 1 mounts, and release gen 1 pets and mounts.

1 and 2 could be 4 gems and 3 be 6 gems.

**Comment by brightbold** [comment]
I want this big time. I'm going to hit level 100 and achieve Mount Master pretty close together, so it would be great to do Rebirth and Release Pets & Mounts simultaneously. For me, collecting gear and hatching pets are two of the most motivating parts of the game, so rebirth won't be as meaningful if I can't start fresh with pets too. (I've added to the bounty accordingly.)

**Comment by ghost** [comment]
If nobody's started addressing this yet, I think I'll start working on it next week.

**Comment by deilann** [comment]
This is my project and i already have the art and much of the code and
text. Please let me do it. I know it's been sitting a while, but it's kind
of one of my two babies, along with random encounters.

**Comment by ghost** [comment]
Yep, got it. Sorry, didn't realize

**Comment by deilann** [comment]
Someone with repo access, can you actually assign the ticket to me, to make
it clear I'm doing it? I'd do it myself but I'm stuck on mobile at the
moment due to my move.

**Comment by paglias** [comment]
@deilann assigned :)

**Comment by deilann** [comment]
No worries kumarei... it wasn't super obvious. :) And thanks Matteo!
Hopefully this will be able to be finished once I'm settled.

**Comment by deilann** [comment]
I have finished this. Just need to hop into a coffee shop. :)

**Comment by brightbold** [comment]
Sweet! I'm so excited! Thanks, Ryan.

**Comment by deilann** [comment]
PR submitted. :)

**Comment by taldin** [comment]
Question - when you release your pets, is it supposed to still say 'Pets Found: 90' on the Stats page?   I noticed that the application gives all of your pets a value of 0, so they don't show up in the Pets pages, but Pets Found counts the strings in the User object and doesn't check values.   But what I'm not sure of is if the fixes you made rely on that count being 90 for upgrading the Beastmaster count or not.

**Comment by deilann** [comment]
Stats page is using the wrong count. It relies on the count displayed in
the stable which is properly reset and only to decide whether or not to
show the key.
