### ISSUE TITLE
Thief Class Backstab Balance Issue

### ISSUE THREAD

**Issue by AHoopyFrood** [HabitRPG/habitica#3749]
Bug: Loading a large number of skills points into Perception (possibly Strength) and then casting Backstab on a blue task yields a huge amount of XP and Gold.
Attached is a picture of the output from this.
![thiefbug](https://cloud.githubusercontent.com/assets/8176698/3594974/978cfd2c-0cab-11e4-80e3-59c9f09e600c.png)

Here are my stats when the bug occurred:
![thiefbug2](https://cloud.githubusercontent.com/assets/8176698/3594990/00b2cd04-0cac-11e4-9ce5-17be13bb5ab5.png)

**Comment by Alys** [comment]
This isn't a bug so much as a skill that's just significantly more powerful than other methods of obtaining gold. It's already been reported in https://github.com/HabitRPG/habitrpg/issues/3029 and there are plans to modify Backstab to make it less powerful. However this is a lower priority than some of the bugs and other feature requests, so it probably won't be changed soon.

If you want to keep using Backstab, you could make a rule for yourself that you take one-tenth of the gold and XP given to you and remove the rest with Fix Character Values. You could also cast it on a less blue task to make it less powerful.

**Comment by Alys** [comment]
You can follow the progress of the fix in the issue I linked to.
