### ISSUE TITLE
Lost all my habits after I died

### ISSUE THREAD

**Issue by dariatrainor** [HabitRPG/habitica#375]
I lost all of my habits when I got resurrected. Not sure if it is a feature, but it is really unpleasant that I have to create habits anew.
1) Started site and it told me that I died.
2) Level returned to 1
3) It showed me popup message that I died again (bug?)
4) All my habits from the habits section are gone :(

**Comment by StanLindsey** [comment]
They shouldn't be gone, at least in my mind they shouldn't. I died recently and all my tasks stayed but this was before some other content pushes. 

I wish I could explain more but I'm knee deep in the wrong repo at the moment; @lefnire will be able to explain more. I have the hunch its linked to a number of recurring bugs. 

Sorry but also thanks for being a HabitRPG user!

**Comment by lefnire** [comment]
@Dash, does a refresh put you back to normal?

**Comment by lefnire** [comment]
There's a glitch where full DOM resets (happens on first load of the day,
reset, revive, etc) - sometimes loses refLists for that page load. I'm
working on it currently. But a refresh of your page should put you back to
normal

**Comment by lefnire** [comment]
Reopen if refresh didn't return you back to normal. I'm working on saner DOM reset in other tickets, closing this for housekeeping
