### ISSUE TITLE
Google API Bounty [$75]

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#3750]
I'm creating this bounty in the hope that other people who want the Google API integrated into HabitRPG, will add money to the bounty.  I can only afford $5 at this time, but may add more later, if I can afford to.

Why you want Google API.

Google API allows (possibly? logging in to habitrpg with your google account)
https://trello.com/c/Yqwr7NdQ/120-google-login  

Google Calendar integration -  Events on your Google Calendar can show up in HabitRPG and HabitRPG tasks can show on your Google Calendar.  Likewise, they will show up on all other applications that sync with Google Calendar, of which there are multitudes.
https://trello.com/c/vtJv2DyY/77-google-calendar-integration-due-dates

Google Task integration -  The same that is true for Calendar, only with Google Tasks, and the multitude of apps that integrate with it.
https://trello.com/c/l7UsVY8E/33-google-tasks

Why add money to this bounty?

Google API integration is a TON of work.  The higher this bounty becomes, the more likely a talented, ambitious programmer can afford to spend the time to code this feature.
##

**Comment by gauthamchandra** [comment]
These are a ton of changes to be classified as 1 issue or feature request. 

These should be broken down into individual issues and then tackled incrementally. 

I am also willing to tackle the major piece that would allow the user to login with their Google account. I will file a new issue for this specific piece and reference it here.

**Comment by paglias** [comment]
Google login is currently being worked on and should be released shortly

**Comment by fragmental** [comment]
I don't have control over who gets this bounty do I?  I don't know how this works. @gauthamchandra is right that this probably should have been split into individual issues.

**Comment by Alys** [comment]
Google login is done. The other items are features requests so they can be requested on Trello if still desired (Help > Request a Feature from the habitica.com website's menu).

@fragmental With this being closed, the money in bounty source should be returned to you automatically but please contact bountysource if there are any problems with that.

**Comment by fragmental** [comment]
This bounty still hasn't been returned, but someone has been trying to claim it.  I rejected their claim, and need to look into what needs to happen so the donations will get returned.

**Comment by fragmental** [comment]
This is what I've found:

What happens if an issue I've backed is closed without resolution?
If the issue was closed because it was a duplicate of another issue, we will transfer the bounty to the appropriate issue.

If the issue was closed as a "won't fix", or is deemed not in line with the project's goals, the bounty is refunded.

Can I receive a refund for a bounty I posted?
If you posted a bounty and decided you want a refund, or to reallocate the funds to another issue, you may contact us for support. Please note if that if you wish to take your refund out of the system, the withdrawal fee still applies(see Pricing page).

I may just have to email bountysource support.
