### ISSUE TITLE
No honey in the Reward list for Dread Drag'on

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3751]
The Reward list for the Dread Drag'on lists all food as a prize except for honey, which should also be a prize.

**Comment by deilann** [comment]
Honey is clearly missing because it's what I need most.

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg-shared/commit/b449387cc0a4244747f321312c08128dfbb3bf45
