### ISSUE TITLE
Can't renew subscribtion

### ISSUE THREAD

**Issue by kuvshiova** [HabitRPG/habitica#3755]
I subscribed on 25 may 2014 ago using PayPal. The first payment went through, but for next payments PayPal for some reason tried withdrawing money from the second card assigned to that account, which is not active at the moment. After I noticed that (on 06 jul 2014) I tried cancelling my subscription. The page now says "Subscription cancelled and will become inactive on 08/01/2014", and just beneath it - "Subscribed". I'm still getting mystery items and I can buy gems for gold. There's no "unsubscribe" button anymore.
I waited a while to see if that might resolve with time, but everything is still the same, although, in fact, there's been only one payment - in May.

Although I enjoy benefits of the subscribtion, I would like to actually pay for them, because you guys are awesome and deserve every cent of it =) Is there any way I can do that?
Thanks in advance!

**Comment by lefnire** [comment]
Give this person a raise! Very honest & kind of you :) Will look into

**Comment by deilann** [comment]
Actually, I think if a payment via PayPal fails, you'll end up with a
negative PayPal balance. (This happened to me once.)

So may have actually paid, 'cause PayPal is going to charge you.

**Comment by kuvshiova** [comment]
@deliann I don't think so. I've got an automatic letter from paypal saying "We've tried to process your automatic payment several times, and it is now past the original due date. You should contact HabitRPG to pay what you owe". 
I also checked operations history on my card - there's only one payment. And paypal "knows" that reccurring payments have been cancelled on 6.07 (there's a line confirming that in my paypal history). I don't think they will charge me two weeks later.

**Comment by deilann** [comment]
Okay. :) Just wanted to make sure, 'cause I know they just put me in
negative once, and I don't want you getting charged and losing your sub at
the same time!

**Comment by lefnire** [comment]
For now, as long as it doesn't keep attempting to charge you - wait till the cancelation completes on website (8/1 was it? should be ready) and re-subscribe (if you want). Let me know if you have any other hitches, or if I'm misunderstanding and this is more important than I think

**Comment by kuvshiova** [comment]
The cancellation was set on 08.01.2014 for some reason (I wasn't even registered on the site at that time). But I guess the problem resolved itself - a couple of days ago "Subscribe" button magically reappeared, so it seems that now I can subscribe again.  Let me check that...
Yep, It worked, I'm subscribed and everything seems ok now =)
