### ISSUE TITLE
Regularly Losing Last Update of the Day, in Spite of Reload

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#3757]
I'm a very frustrated mage. I have perfect days a lot - but can barely keep a perfect day streak going long enough to get my full inflated MP - not because I fail to check things off, but because the server loses my last update of the day. 

I reload the site (using the browser's reload) before going to bed, and verify that everything i checked off is still checked off, and my xp bar looks the same as it did pre-reload. Then in the morning when I reload the site again (to trigger cron), far too often I get the dreaded -1 or -2 HP, and -40 or so MP. 

At one time when this happened, I'd find myself with e.g. 290/222 MP, and could at least use the MP I was about to lose. Unfortunately you fixed that - while also apparently fixing the work around for the broken app which updates the local state even if it didn't successfully report to the server, then apparently never retries its reporting. Is there any reliable way to determine the current _server_ state, i.e. whether my updates were actually recorded? Or is this a new bug, and my updates _are_ being recorded at the server - and then later forgotten?

I have a custom day start of 2 AM, but quite commonly go to bed (and hence do my last access to the site) before midnight. 

As for frequency - 3 occurrences in the past 12 days, most recently this morning.

**Comment by deilann** [comment]
Do you ever check the Data Display Tool instead of reloading?

**Comment by ArlieS** [comment]
_clueless look_ Data Display Tool?  

Would that be https://oldgods.net/habitrpg/habitrpg_user_data_display.html ?

Looks like a nice summary of what isn't checked off. and no chance of missing an unchecked-off daily because of erratic scrolling. Ill try using it to verify that what I think I checked off, is. (Right now there are 4 missing - which is correct for what I've done so far today.)

I'll use that as a check for a week or two, see if reliable behaviour results, and report back.

**Comment by deilann** [comment]
Yup! that be it.

It uses the server's data, so there's also no chance of missing something
because your local side thinks it has it.

**Comment by ArlieS** [comment]
No unanticipated HP loss since I started checking on things with the Data Display Tool - but also no cases that I remember where the display tool warned me that something I believed I'd recorded hadn't made it to the server. 

I wonder if I was in fact losing HP to not seeing unchecked off items buried in my rather long list of "sometimes" dailies. (Scrolling can be iffy - I suspect it of scrolling by more than the screen length. Maybe because of the floating header. Or maybe because my browser was overloaded and flaking.)  Either that or the client's connection to the server has become much more reliable. Or I had a lucky 16 days, but that seems least likely.

**Comment by ArlieS** [comment]
Still no problems. Closing the issue.
