### ISSUE TITLE
Building the “Character Box” (and spriting quirks)

### ISSUE THREAD

**Issue by caycefischer** [HabitRPG/habitica#376]
@lefnire 

I'm thinking about building out a "char-box" component by extending the current `<avatar:` template. That way, a standard piece of UI can be used wherever we need to show the user's avatar, with no fuss—no different html for different parts of the site like we do now, etc. The char-box should have different configurations depending on the context, but this way it'll share design language & elements. Less custom code throughout the UI.

Anyway, all this to say—as I was starting to work on it when I realized something: positioning a user's avatar nicely inside a container is going to be next to impossible. Despite all our sprites being contained in a set 90px by 90px, depending on the user's equipment and pets their position within a box is different. 

![](https://f.cloud.github.com/assets/546495/146960/bfb2a0b8-749a-11e2-942a-84aae5769487.png)![](https://f.cloud.github.com/assets/546495/146963/ca92b112-749a-11e2-874f-c8e991312657.png)![](https://f.cloud.github.com/assets/546495/146961/c4818816-749a-11e2-8fef-b070d830025e.png)![](https://f.cloud.github.com/assets/546495/146962/c6ed70b0-749a-11e2-978f-72c1aae37c64.png)

As you can see, inside the same 90px box characters can look properly centered in frame, or very unbalanced. Now the way the sprite works, the character bodies don't sit in the dead center of the 90px, so that there's enough room for weapons and pets on the left—that's kind of unavoidable.

**My idea:**

Define certain conditions that will modify how the char-box is drawn with CSS. We're already kind of doing this with `minimal:true`. For example, if the `hasPet` condition is true, add a `.hasPet` class to the avatar to increase top padding on the charbox. Same principle for `longWeapon` and extra left padding. Whatever we end up needing, basically. Example:

![](https://f.cloud.github.com/assets/546495/146995/84e39a08-749c-11e2-9067-056d6fcdb690.png)![](https://f.cloud.github.com/assets/546495/146996/875eca00-749c-11e2-8487-ac5d47a6cedb.png)

At the end of the day, it remains to be seen how this'll play out. I'm going to start hacking on it and see what I can come up with for a cool character box we can use in the profile, the header and other areas. Just keeping you in the loop with my thinking. Any thoughts?

**Comment by lefnire** [comment]
Sounds good! If the whole thing becomes complex, we can always separate it out into avatar.html and import it with [template imports](http://derbyjs.com/#importing_templates). (In fact, our giant html file is a big mess, but I couldn't get template imports to work well when I tried first a long while back). 

But yeah, keep me in the loop, as well as @Pandoro - because the weapon v mount v pet in a 90-bound box has been something haunting us. Excited to see what you come up with.

**Comment by horusofoz** [comment]
Any updates team?

**Comment by caycefischer** [comment]
Nothing to push yet, I'll talk about it more at the meeting but I've been
hanging out the layout thread and whatnot.

On Sat, Mar 2, 2013 at 4:42 AM, horusofoz notifications@github.com wrote:

> Any updates team?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/376#issuecomment-14325677
> .

## 

_– Zachary Kain_

Designer, Creative Technologist
416-712-8895
zakkain@gmail.com
→ view my resume/profile http://zerply.com/zakkain/public

**Comment by horusofoz** [comment]
@zakkain With your tweaks is this ticket still needed?

**Comment by caycefischer** [comment]
I suppose not!
