### ISSUE TITLE
Pet doesnt have a green bar

### ISSUE THREAD

**Issue by Crimsyn** [HabitRPG/habitica#3761]
One of my pets doesnt have a green lvl up bar to take it to a mount

**Comment by deilann** [comment]
Do you already have a mount of this pet?

Can you show a screenshot of the issue?

**Comment by SabreCat** [comment]
Also, what browser are you using? I believe there's some known issues with Internet Explorer not showing the bars.

**Comment by deilann** [comment]
Yeah, but then all the pets wouldn't show a green bar.

Usually, this either means the user has the mount _or_ their resolution is
very small, and the base pets lose their bar.

**Comment by Mihakuu** [comment]
or the pet doesn't have a mount version like the eggs or special pets

**Comment by Crimsyn** [comment]
I use my phone. . I found if I flip my phone sideways the bar shows up. 

Sent from my personalized C Spire Wireless Galaxy S III

<div>-------- Original message --------</div><div>From: Sabe Jones notifications@github.com </div><div>Date:07/21/2014  6:56 PM  (GMT-06:00) </div><div>To: HabitRPG/habitrpg habitrpg@noreply.github.com </div><div>Cc: Crimsyn Draeken4@yahoo.com </div><div>Subject: Re: [habitrpg] Pet doesnt have a green bar (#3761) </div><div>
</div>Also, what browser are you using? I believe there's some known issues with Internet Explorer not showing the bars.

**Comment by Alys** [comment]
This has also been reported here: https://github.com/HabitRPG/habitrpg/issues/3218  "Then I turned my tablet back to portrait mode, and it no longer had a meter. Then I turned it back to landscape mode, and it had a meter again." @Crimsyn, you can follow the progress of any fixes at that URL. Use the Notifications button on the right hand side if you want emailed updates.
