### ISSUE TITLE
Dailies did not reset on a new day

### ISSUE THREAD

**Issue by septagram** [HabitRPG/habitica#3762]
My custom day start is set at 9 a.m., I didn't change it in the last couple of days, nor did I use the inn.

Usually I use Habit through the browser, or use mobile app occasionally through the day, but at least once open it in browser before the day ends. This time, I turned off my desktop, and ticked off the remaining dailies in the mobile app, about 5-7 hours before the day start. I have received XP and gold for them.

Today, after logging in with a desktop app, I saw all my yesterday dailies still ticked off. I have neither received any damage nor have dealt any. And Habit believes it's already Monday, since the dailies are enabled and disabled like they should be on Monday.

**Comment by deilann** [comment]
Looks like you've hit upon our meanest, oldest bug: https://github.com/HabitRPG/habitrpg/issues/1057
