### ISSUE TITLE
class-changer cannot rebuy old-class' gear.

### ISSUE THREAD

**Issue by liordon** [HabitRPG/habitica#3763]
My poor habitier just died. which happens, you know. it's okay. BUT!
I lost my ski-assasin pole (left hand) and (probably since I switched from rogue to mage since winter wonderland) I cannot buy it back from the store. can this be fixed? or can I at least get the pole back? ^^"

**Comment by deilann** [comment]
I'm really torn on this. If it's a legitimate death, I'd really say no
because otherwise it'll set a bad precedent, which will take up a lot of
admin time restoring lost. If you lose cross-class gear, you have to wait
until you're that class again to purchase it. If it were due to a bug
death, that would be different. You'll be able to grab it, though, next
time you roll rogue!

Now, I have questioned whether or not this should be the case (that you
_can_ lose cross-class gear) but the question was never fully resolved.

**Comment by liordon** [comment]
well, I guess this proves that you _can_ lose cross-class gear.

I'll tell you what, the death is sort of nobody's fault since it's the result of a party member having a very wierd computer which somehow toys with her cron timing (and causes here to deal the party 25-27 Dmg each night ><). So it's not a bug in the site, but I'd certainly hate to lose a limited edition item for that. I thought I could survive with "fix character values" but the last time her cron went crazy I was asleep, so... :/

**Comment by deilann** [comment]
Oh, it's not lost permanently! next time you roll rogue, you'll be able to
repurchase it.

**Comment by liordon** [comment]
that's said under the assumption that I'm one of those constantly-rotating-between-classes-to-get-all-the-stuff kind of guy instead of just-snatching-some-stuff-over-here-while-I'm-trying-to-figure-out-which-class-I-like kind of guy :P
being a rogue seemed kind of pointless eventually, since I'm not _that much_ of a hoarder, so I definitely wouldn't play it again just to get a ski pole.
I have given it some thought, and actually since it's just one of the ski poles it's not as important to me as that, but I would like to recommend restricting the loss of items to things that the player can purchase again without spending gems on class change or whatnot (I bet most veterans have the best warrior gear for example, and not all of us are class rotators). 
I know it's probably not habit's highest concern right now, but it's a sensible feature, isn't it? ^^"

**Comment by deilann** [comment]
Okay, I've gone ahead and returned it. However, I don't want to make a habit of this. If your party mate knows she's having issues with her computer, she should abstain from questing until she's figured out her problems.

**Comment by liordon** [comment]
thanks a lot @deilann ! I'll definitely tell her and note this to myself! :)

**Comment by deilann** [comment]
I've stated in the past that it shouldn't be lost because users spent gems doing so. But I don't want to set up a situation where it becomes my job to fix everyone's items because they aren't managing death until we decide, yanno?

**Comment by liordon** [comment]
of course, I never questioned your position! That's why I really appreciate your help and patience.
I hope this situation will not repeat itself  at all to save you and the other mods the trouble of dealing with it altogether :)
Thanks again!

**Comment by deilann** [comment]
np! try and stay death free ;)
