### ISSUE TITLE
See count of notifications on web site

### ISSUE THREAD

**Issue by jakerella** [HabitRPG/habitica#3765]
I would like to see a count of the "Notifications" in the top header. The speech bubble icon could be overlayed with a number of unread notifications channels - so if there are 5 new messages in Guild One and 2 new notifications in my party, I would see a "2" overlayed on the speech bubble.

FYI, I'll try to find where this is in the code and implement it (I have experience in both Angular and Node).

**Comment by SyntaxPickax** [comment]
See #3270 (and #3338).

**Comment by jakerella** [comment]
@SyntaxPickax Awesome, I searched and couldn't find it, but that's because #3270 doesn't seem to mention a count. I'll add a bit over there about that and leave this open for now. If that one gets merged then I might tack onto it.

**Comment by Alys** [comment]
This is under discussion in https://github.com/HabitRPG/habitrpg/issues/4365 and any fixes will be linked to that issue.
