### ISSUE TITLE
npm install error "Call to './util/has_cairo_freetype.sh' returned exit status 0"

### ISSUE THREAD

**Issue by benlind** [HabitRPG/habitica#3766]
Hey all. I'm trying to install HabitRPG locally in order to contribute to the project, but I am running into some problems. I'm on Mac OS 10.9.4. I have the repository forked and cloned to my hard drive fine, mongodb is set up, and node & npm are installed.

Here's the problem: when I run `npm install`, it goes through and installs most of the needed dependencies . . . until it gets to "node-gyp rebuild." Then it gives me errors:

```
> canvas@1.1.5 install /Users/benlind/Development/habitrpg/node_modules/habitrpg-shared/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/benlind/Development/habitrpg/node_modules/habitrpg-shared/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing gmsmith@0.4.2
npm WARN optional dep failed, continuing phantomjssmith@0.4.0
npm WARN optional dep failed, continuing canvassmith@0.2.1
npm WARN cannot run in wd habitrpg@0.0.0-152 ./node_modules/bower/bin/bower install -f (wd=/Users/benlind/Development/habitrpg)
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.6.2 wants karma@~0.10.0
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.4 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-ng-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-chai-plugins@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-mocha@0.1.6 wants karma@>=0.12.8

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/benlind/Development/habitrpg
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/benlind/Development/habitrpg/npm-debug.log
npm ERR! not ok code 0
```

Can someone give me a hand with these errors?

**Comment by SabreCat** [comment]
I've run into trouble with cairo a bunch of times, but I don't know the fix for Mac OS. I would try installing canvassmith or one of the other spritesmith options separately and see what happens.

**Comment by thepeopleseason** [comment]
Based on the output, the cairo issue is only for an optional dependency. while the latter issue (karma) is solved by #3769.

**Comment by benlind** [comment]
@thepeopleseason Thanks! That solved my karma peerdependency problems. Now when I run `sudo npm install` I believe it finishes the task, but I get these errors halfway through:

```
> canvas@1.1.5 install /Users/benlind/Development/habitrpg/node_modules/habitrpg-shared/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/benlind/Development/habitrpg/node_modules/habitrpg-shared/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.29","npm":"1.4.14"})
npm WARN optional dep failed, continuing canvassmith@0.2.1
npm WARN cannot run in wd habitrpg@0.0.0-152 ./node_modules/bower/bin/bower install -f (wd=/Users/benlind/Development/habitrpg)
```

I've searched extensively for that error, and the general advice seems to be that I should run `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` and then `PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig` so that pkg-config knows where to look for that xcb-shm.pc file. However, when I run those commands, I still get the same errors as above. It's as if pkg-config isn't really searching those directories for the file. If I run `echo $PKG_CONFIG_PATH`, I get `/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig`, so the variable is set correctly. Also, if I run `pkg-config --modversion xcb-shm`, I get `1.10` as a result, which would lead me to believe that pkg-config by itself _can_ find the xcb-shm.pc file, but for some reason npm install can't find it. Any ideas?

**Comment by thepeopleseason** [comment]
As I mentioned, this might not be something that's absolutely essential, as evidenced by the line: 

`npm WARN optional dep failed, continuing canvassmith@0.2.1`

Go ahead and continue with the setup instructions, and if you can npm start and connect to your local server, it might be something that you can ignore.

**Comment by benlind** [comment]
I see. I ignored it and continued, and HabitRPG's running now, thanks!

One more question: what information should I use to login to HabitRPG on my local machine? There is no users collection in mongodb, there are only counters, coupons, groups, and system.indexes collections. [This wiki page](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths#Use_the_shell) says to go to http://localhost:3000/#/options/settings and copy my user id from there, but that link just takes me to the HabitRPG home page, where I still need to login. Did I seed the database incorrectly?

**Comment by deilann** [comment]
You'll need to register a user.

**Comment by benlind** [comment]
Oh, duh, thanks. Works now. Let me make sure everything else is up and running before marking this as completed.
