### ISSUE TITLE
FAQ button on top bar

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3768]
I would really like an FAQ button on the top bar (possibly bolded) so that it is a little more obvious for confused users. Ideally, the button would lead to a searchable page on the site proper instead of the wiki, but in the meantime, linking to the FAQ on the wiki would be fine.  I think that having this button next to the Social/Inventory/etc buttons would help diminish confusion, although obviously there will still be people asking the same questions no matter what we do.

It would be nice to have a clear FAQ link from the mobile app as well - especially until we can get a better tutorial in.

**Comment by negue** [comment]
FAQ Button was added with #3988 , which soon goes live.

Only the mobile-app is left.
