### ISSUE TITLE
Add Level 11 Tutorial to Teach Skills

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3770]
At level 10, you get a "class" tutorial. However, I think that a level 11 tutorial would have great benefit.

Level 11 is when you get your first skill, so it would teach users how skills work, and some basics like "it's separate from doing the task," which is a concept that many users don't realize without it being pointed out.

If someone were to write and code a level 11 tutorial, it might be worth more than 1 contrib level, depending on your current tier -- one for writing the tutorial, one for coding it in. I'm putting this as priority medium because it comes up pretty regularly.

**Comment by lemoness** [comment]
Agreed that this is a v. important tutorial that we do not have.

**Comment by wysawyg** [comment]
I'm happy to take a look at this if no-one else already is though I'm a newbie to contributing and angularjs (though not coding in general) so it may take a bit of time!

**Comment by wysawyg** [comment]
Looking at implementation of this. The current tutorials appear to be inline in the javascript. I think it would make sense to extract these out into json which could allow for future tutorials to be defined by a non-dev with a dev coming in at the end to do the page links, item links and hooking the tutorial up to the necessary trigger.

**Comment by Alys** [comment]
@lemoness Is this still desired?

(FYI, to developers, the tutorials have been modified since the previous comment.)

**Comment by lemoness** [comment]
We'll be revamping this soon as part of all the tutorial changes, so in the meantime, we can close this issue.
