### ISSUE TITLE
Audio Assets Need Implementation

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#3772]
It's been months since I finished them, so I should double check the levels and such on them, but I've been sitting on completed sound effects for a long time now, but haven't had someone available to implement them. :(

Here are the assets in .mp3 and .ogg: https://drive.google.com/folderview?id=0B173ZqzAA0_RbVU4akJuYk5WSUU&usp=sharing

Anyone want to help tackle this with me? @Fandekasp was working on this previously with me but he's been incredibly busy and looks to continue to be really busy for quite a while. My best guess is that his work and perusing the trello card: https://trello.com/c/tljx8gKC/18-music-sound-effects , would be the best places to start on filling you in on how this has been going.

**Comment by lefnire** [comment]
Sorry this hasn't gotten any love friend :( It's still on my bucket list to help out, could still be a long while though

**Comment by negue** [comment]
This can be closed? Audio Assets have been added / merged on 16. August

**Comment by lemoness** [comment]
Agreed!
