### ISSUE TITLE
Accessibility Issue: emoji and text too small for vision-impaired users

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3774]
I've been meaning to post about this for a while:

The emoji are far too small for me to parse. While sometimes I'll zoom the page in order to make them readable, this really shouldn't be a requirement. (Especially as some aspects of Habit break when I use browser zoom.)

Other implementations of emoji I've seen make them larger, even though it disrupts the flow of text. This would be hugely appreciated. If I can't make out what they are, users with vision worse than me certainly cannot.

Whilst we're on the subject of Habit not zooming well... a good solution to that would be to have global font size settings... so I could make all of Habit's text bigger, without breaking the layout, losing the ability to close modals... I feel like that would be a relatively easy thing to code in, yeah? And a lot of good.

cc: @SabreCat ('cause I always love your opinions) @benmanley (because you know how front end works for reals) @lemoness ('cause I also love your opinions and you might have heard from users about this)

I know I could theoretically set up a style sheet, but I'm not so good at that, and this is a pretty big problem. If people argue with it as "priority - important" please do let me know.
##

**Comment by lemoness** [comment]
Agreed that making Habit more accessible in general should absolutely be a
priority, and I am definitely in favor of font size settings as well.
 Added both of these things to this Trello card here:
https://trello.com/c/pxTcbKuD/381-accessibility-settings. Moving it up to
the "Planning" section as well so that we can brainstorm more.

In the meantime, this Github ticket is a good place to discuss the
implementation of font size settings and larger emoji! (I wish there was a
way to enlarge them by clicking, as with images, but imagine that uniformly
larger emoji is much simpler, as they are part of markdown?)

**Comment by Alys** [comment]
This should in no way be considered a replacement for a permanent fix (and I agree with "priority - important"), but if anyone does want to set up a style sheet as a temporary workaround, this is what I use to make emoji larger:

```
/* MAKE EMOJI LARGER IN LIST OF TAGS ABOVE TASKS */
#main div.container-fluid.ng-scope li .emoji {
    font-size: 1.7em !important;
}
/* MAKE EMOJI LARGER IN LIST OF TAGS WITHIN EACH TASK */
label.checkbox span.emoji {
    font-size: 2em !important;
}
/* MAKE EMOJI LARGER IN TASK DESCRIPTIONS */
div.task-text span.emoji {
    font-size: 1.3em !important;
}
/* MAKE EMOJI EVEN LARGER IN TASK DESCRIPTIONS FOR DAILIES */
li.daily div.task-text span.emoji {
    font-size: 1.8em !important;
}
```

I also have these styles to make text SMALLER, but obviously the numbers can be adjusted:

```
/* MAKE TEXT SMALLER */
#wrap h2 {
    font-size: 1em !important;
}
#wrap div.task-text {
    font-size: 0.8em !important;
    margin-left: 0.7em !important;
}
label.checkbox {
    font-size: 1em !important;
}
```

From memory, the emoji size will vary with the font size, so some extra fiddling with the emoji size might be needed after changing the font size.

**Comment by deilann** [comment]
@Alys I have workarounds for task stuff -- my major issue is social. I mean, because I can't read emoji, I don't use them in tasks already. And I make sure my tasks are readable to me.

So do you have social stuff?

**Comment by Alys** [comment]
@deilann : Oh... yes... that's really _obvious_. :) I blame the cold I'm suffering from.

This will change emoji size everywhere. If that causes problems in some locations, tell me.

```
.emoji {
    font-size: 2.7em !important;
}
```

**Comment by deilann** [comment]
I've put together a [Large Print Habit](https://userstyles.org/styles/103704/large-print-habit) user style for the short term! Thank Alys for help with CSS!

**Comment by SabreCat** [comment]
It looks like most ground has been covered already, but I'm behind the thought, fwiw! Even for me as a (mostly) able-sighted person, emoji in chat are so small as to be indistinct.

**Comment by crookedneighbor** [comment]
I agree that the emoji are too small.

**Comment by crookedneighbor** [comment]
I've boosted the emoji up to 1.5em all around.
