### ISSUE TITLE
Remove AddThis | canvas fingerprinting

### ISSUE THREAD

**Issue by HLFH** [HabitRPG/habitica#3775]
Hi,

Could you remove AddThis of the ads systems used in HabitRPG?

We recently understood that AddThis is using this kind of technology: http://en.wikipedia.org/wiki/Canvas_fingerprinting

And I don't like this one. 

What do you think?

Thanks!!

**Comment by thepeopleseason** [comment]
Is there a substantive rationale beyond "I don't like this one" that you can provide? The wiki page on canvas fingerprinting doesn't list any controversies or potential security holes.

**Comment by HLFH** [comment]
I don't like to be tracked with this technology: http://www.theverge.com/2014/7/21/5924307/companies-have-a-tricky-new-way-to-track-your-movement-across-the-web

**Comment by negue** [comment]
@HLFH  you could something like https://www.ghostery.com

**Comment by Alys** [comment]
I'm closing this because there are many methods of preventing yourself being tracked, and they'll protect you on other sites too, so installing one of those methods is your best option if you don't want the Add This tracking.
