### ISSUE TITLE
User Issue

### ISSUE THREAD

**Issue by AshRoninRPG** [HabitRPG/habitica#3776]
![habitrpg - error1](https://cloud.githubusercontent.com/assets/8247210/3674787/8a10c6a0-1279-11e4-964b-4a2d34a244d5.PNG)

I refreshed my task page last night after midnight, and this is what it turned into. Only thing different is I had a few unfinished dailies. Things will highlight if I move the mouse over them, but aren't actually clickable.

Firefox
3e5cbf76-91c9-4e15-b32a-d8abe0ca85cf

**Comment by SabreCat** [comment]
Looks like the kind of thing that sometimes happens if you catch the site in the middle of an update. Is it still acting like that today? What happens if you refresh again?

**Comment by deilann** [comment]
Clearing the cache usually fixes it.

**Comment by AshRoninRPG** [comment]
Thank you! That fixed it. And thank you for the explanation. I'll know why and what to do next time.
