### ISSUE TITLE
performed a reset, item store and drops are unlocked at level 1

### ISSUE THREAD

**Issue by piscisvolans** [HabitRPG/habitica#3777]
I made an account and didn't start actually using it for a while, so I was dead when I eventually signed back in. Decided to perform a reset and start from scratch. After the reset, I was given a Wolf Egg and found that the item store and drop system were both unlocked--which I thought wasn't supposed to happen until levels 2 and 4? Is this a bug or some consequence of performing a reset?

I don't remember what my level was before the reset, but I can't imagine it would be higher than 1 because I never completed any tasks.

Chrome.
cc4637f9-53b6-4a91-b20a-8dfce006e848

**Comment by Alys** [comment]
I realise this is an old issue, but for the record: Reset is best used when you have a very new account and want to remove the effects of your initial experimentation. When you use it on a more established account, it can have undesirable effects, hence its placement in the "danger zone" on the settings page. The Orb of Rebirth is a better option.
