### ISSUE TITLE
Equipment list mixed for party members

### ISSUE THREAD

**Issue by chimmelb** [HabitRPG/habitica#3778]
I am a member of a 3 person party. 
![myparty](https://cloud.githubusercontent.com/assets/5881179/3682617/d9f6b9ce-12d1-11e4-8e57-1dc7e3351aea.png)

I click on the right party member and see this:
![rightpartymember](https://cloud.githubusercontent.com/assets/5881179/3682619/ea628ed2-12d1-11e4-9cd1-9716200eb045.png)

I click on the left party member and see this:
![leftpartymember](https://cloud.githubusercontent.com/assets/5881179/3682621/f617bf0e-12d1-11e4-9795-d9729d5b7785.png)

The right party member has the STR and pic of the Seafaring Slicer, but lists a training sword. The left party member has the STR and pic of the Training Sword, but lists a Seafaring Slicer. 

Boom. I just blew your mind.

Obviously this is a minor bug, but I noticed it and am reporting it. This was found on my Linux Mint 16 OS, using Google Chrome Version 35.0.1916.153.

**Comment by deilann** [comment]
This is known. There's another ticket on it, but I don't have time to look
for it right now.

**Comment by chimmelb** [comment]
Ah, I see. This can be marked Invalid or Duplicate.

**Comment by deilann** [comment]
We just close 'em. :)
