### ISSUE TITLE
"Data column(s) for axis #0 cannot be of type string" in Daily Progress

### ISSUE THREAD

**Issue by Envisign** [HabitRPG/habitica#378]
Tested in latest Opera and Chrome.

In the Daily column when the progress icon is clicked for any of the tasks, the error message "Data column(s) for axis #0 cannot be of type string" comes up instead of the expected graph.

**Comment by wc8** [comment]
See: https://github.com/lefnire/habitrpg/issues/315
I think this is that issue. Please follow up there, unless it is different.
