### ISSUE TITLE
Interface: Margin Quirks in Mobile and Website

### ISSUE THREAD

**Issue by pepperpanda** [HabitRPG/habitica#3782]
I have noticed some quirks while I have been using the browser (Chrome).

On Party Tab,there seems to be no margin between the borders and the content on the left and the right side. 

![party](https://cloud.githubusercontent.com/assets/4915522/3684949/8c50338a-1303-11e4-807e-b61ae375ab67.jpg)

Guild Search Box, there seems to be no margin below the Search Box.

![guild](https://cloud.githubusercontent.com/assets/4915522/3684953/902de6a0-1303-11e4-87d6-d75a9b78ac5e.jpg)

**Comment by deilann** [comment]
I can't actually see what you're referring to with the site.

Can you report the mobile issue in the mobile repo, if it hasn't already
been reported? If you don't know where it is, you can quickly find it by
clicking on the HabitRPG organization.

(Sorry, when I say I can't see it, I mean that literally. Describing it
might be helpful.)

**Comment by pepperpanda** [comment]
On the site I have them indicated with red boxes.

**Comment by deilann** [comment]
Yes. Not everyone is as visually gifted as you are.

**Comment by pepperpanda** [comment]
I'm sorry if my comment sounded arrogant. Updated my comment. Moved mobile issue to mobile repo.

**Comment by deilann** [comment]
It happens!

Speaking of happens, have you seen this happening on any other pages, or is it just the "No party" page?

**Comment by pepperpanda** [comment]
Only in the "No party" page.

**Comment by deilann** [comment]
Awesomesocks. I will look into this, but chances are will need the help of @Alys or @benmanley because markup languages are like Greek to me.

**Comment by pepperpanda** [comment]
Lol okay. But I think they just need to adjust something in the CSS side. I'd do it but I can't seem to get Vagrant up and running.

**Comment by deilann** [comment]
Yeah. I'm sure. I just sometimes like poking at CSS because it's strange and mysterious to me. They could probably solve it in 2 seconds flat.

**Comment by Alys** [comment]
pepperpanda! Trouble with Vagrant you say! I've been having trouble with it too, and have been modifying things to try to fix it, with some success, although I have no idea if it's just me that has these particular problems... Would you care to be a guinea pig for my new vagrant changes to see if it helps get you up and running too?

**Comment by deilann** [comment]
ALYS DON'T LOOK AT THE CODE YET I WANNA LOOK FIRST

**Comment by pepperpanda** [comment]
Sure! I'm a newbie at Vagrant though.

**Comment by deilann** [comment]
I think I see the issue here! This is the party page:

```
script(type='text/ng-template', id='partials/options.social.party.html')
  div(ng-if='group._id')
    include ./group
  div(ng-if='!group._id')
    div(ng-show='user.invitations.party.id')
      h2=env.t('invitedTo', {name: '{{user.invitations.party.name}}'})
      a.btn.btn-success(data-type='party', ng-click='join(user.invitations.party)')=env.t('accept')
      a.btn.btn-danger(ng-click='reject()')=env.t('reject')
    div(ng-hide='user.invitations.party.id')
      h2=env.t('createAParty')
      p
        =env.t('noPartyText')
      pre.prettyprint.
        {{user.id}}
      p
        =env.t('startLFG')
        |&nbsp;
        a(href="http://habitrpg.wikia.com/wiki/Board:The_Archery_-_LFG")=env.t('linkLFG')
        |&nbsp;
        =env.t('endLFG')
      include ./create-group
```

Now, actual groups start off with `.container-fluid` and a whole bunch of fancy formatting.

But the no party page doesn't.

**Comment by Alys** [comment]
@pepperpanda : Nifty! Note though that you can change your mind any time if being a guinea pig becomes too time consuming or stressful! Although I'm hoping it will be easy...

Depending on how enthusiastic/impatient or sensible you are, I can either give you some changes in the next half hour (and I THINK those changes might work), or you could wait maybe up to a day while I do another test first. The changes will be two just files, so they'll be easy enough to make. Which would you prefer?

**Comment by pepperpanda** [comment]
@deilann cool! You found it!

@Alys Any is fine. Was actually working on it the other day (whole day), I got woozy at the end of the day but still couldn't make it work.

**Comment by Alys** [comment]
Righty ho, files incoming within the next hour :)  :hamster:

**Comment by Alys** [comment]
@pepperpanda : I've uploaded some changes to my https://github.com/Alys/habitrpg/tree/vagrantChanges branch. Only two files were changed:
- https://github.com/Alys/habitrpg/blob/vagrantChanges/package.json
- https://github.com/Alys/habitrpg/blob/vagrantChanges/vagrant.sh

and you can see the changes here:
https://github.com/Alys/habitrpg/compare/vagrantChanges?expand=1

Note that the changes in package.json are quite hacky and I will be trying to put in proper version numbers, but for now the asterisks resolve some dependencies errors I was getting.

Anyway, this is all very unofficial and I still want to do a bit more of my own testing, but it might help you get vagrant working. I would be interested to know how you go! I recommend that you do "vagrant destroy" first to ensure a fresh start, and probably also make sure that your local habitrpg repo has the latest upstream updates (I typically just completely delete my local repo and create a new one from scratch) before you apply my file changes. 

I'm not sure what aspects of this you were referring to when you said you are a newbie, so you are most welcome to ask me any questions you like, and if there's anything I'm not sure about, I'll pass it on (I'm sort of newbieish to some of this too).

**Comment by pepperpanda** [comment]
@Alys ok! will try em! where should i tell you my response? i think we should move to another thread

**Comment by Alys** [comment]
That's probably very sensible! I think you should be able to comment here: https://github.com/Alys/habitrpg/issues/1

**Comment by crookedneighbor** [comment]
I don't think these are issues anymore. Closing.
