### ISSUE TITLE
Dropdown Menu For "User" and "Social" Cannot Close

### ISSUE THREAD

**Issue by GreenRaccoon23** [HabitRPG/habitica#3783]
![screenshot from 2014-07-24 10 49 41](https://cloud.githubusercontent.com/assets/6865750/3690778/d4f43abc-134b-11e4-9ac4-03b56f1f4f09.png)

When you click "User" or "Social" to bring down each of their dropdown menus, the menu will not close until you click one of the items in the list. For example, if you click "User," and then "Tasks," you will go to the Tasks page but the "User" dropdown menu will still be open.

So 1) this menu should close when going to a new page, and 2) it should also close when you click its parent button (e.g. the User menu should close when you click the User button)
##

**Comment by thepeopleseason** [comment]
Just a point of information: The menu closes when you click the menu icon.

**Comment by Alys** [comment]
The menu now closes when you go to a new page.
