### ISSUE TITLE
Paypal subscription - Application Error

### ISSUE THREAD

**Issue by jenmeister** [HabitRPG/habitica#3784]
Hi,

I subscribed via Paypal a couple of days ago. I received an application error, and my subscription is not being reflected in the web interface, but the payments are going through.

![Application Error Screen](https://cloud.githubusercontent.com/assets/8262620/3696883/eadf15e8-1398-11e4-88d7-9c0a52197235.png)

User ID: c81c30c7-df61-415d-bf1a-f6a8d1e76f0a
Subscription date: 23/07/2014 15:03 AEST
Browser: Firefox v26.0 on Ubuntu 13.04

Could this please be fixed so that my account reflects my subscription status?

Thanks,
Jen

**Comment by deilann** [comment]
Can you actually email admin@habitrpg.com with this info? I try to send payment stuff there in case any more private info is needed. You're also likely to get a faster response, so it's double win. :)

**Comment by jenmeister** [comment]
Thanks. I couldn't quickly find any email contact details on the site. I have sent through an email and updated the original report to be a more generic error report.

**Comment by deilann** [comment]
...yeah, Contact Us is missing. I remember seeing a ticket about that. That
really needs to be fixed. So thanks for that reminder!

**Comment by jenmeister** [comment]
This has been fixed for me :)
