### ISSUE TITLE
Dailies streak does not substract after unchecking

### ISSUE THREAD

**Issue by deivuh** [HabitRPG/habitica#3785]
If I check a daily task, the experience points and gold are given to me, and then removed when I uncheck it. But the streak count increments when checking it but does not decrement after unchecking it.

**Comment by deilann** [comment]
Can you post some before and after screen shots for me? Because I can't
replicate this.

**Comment by deivuh** [comment]
I believe it was my mistake, as I'm unable to replicate it now. Sorry for the trouble.
