### ISSUE TITLE
Avatar items showing as unlocked but clicking them results in "Purchase for x Gems?" confirm

### ISSUE THREAD

**Issue by DazDotOne** [HabitRPG/habitica#3786]
I have just reached level 10 and when clicking my avatar to view customisation options it appears that there are a lot of items that have become unlocked (they are not shaded with the dark grey background anymore).

However, when I click on some most of these items, I still get the purchase message described above.

![screenshot 2014-07-25 12 57 44](https://cloud.githubusercontent.com/assets/3983532/3701507/1c48cc82-13f3-11e4-95f2-46c5ee604056.png)

![screenshot 2014-07-25 12 58 11](https://cloud.githubusercontent.com/assets/3983532/3701510/21a3f544-13f3-11e4-957f-8af83c7cca85.png)

**Comment by deilann** [comment]
What item are you clicking in the screen shot?

**Comment by deilann** [comment]
Oh, and what's your UUID?

**Comment by DazDotOne** [comment]
How do I find my UUID? 

That happens when I click pretty much anything that's not got the dark grey background except the basic skins, shirts, bangs, flowers or single pony tails (base).

I also couldn't fit it on the screen shot but the facial hair is also showing as unlocked but not behaving so.

**Comment by deilann** [comment]
Okay, unless you've bought the facial hair, it shouldn't be unlocked. Just
to confirm: you haven't purchased any of the rainbow skins or hairs?

**Comment by DazDotOne** [comment]
No

**Comment by deilann** [comment]
Sorry, just realized I forgot to tell you where to find UUID

It's in Settings > API

What browser are you using?

**Comment by DazDotOne** [comment]
Chrome and my UID is fdd05629-d336-4d3e-8e35-9c3d6af725d2

**Comment by deilann** [comment]
Do you have any other browsers installed/can you install any other browsers
and see if it still shows up this way in another browser?

**Comment by DazDotOne** [comment]
Yeah it's the same in safari

**Comment by DazDotOne** [comment]
And Firefox too

**Comment by casicastiel** [comment]
This is happening for me as well (Chrome, Mac).

**Comment by casicastiel** [comment]
Also Chrome on Android. Interestingly, half of the Rainbow Skins set (green, blue, deep purple) show as unlocked whereas the others show locked correctly. The special shirts as well show up as locked. (If it matters, I've never purchased any avatar customizations.)

**Comment by lefnire** [comment]
This still happening? I'd made some updates recently here https://github.com/HabitRPG/habitrpg/commit/3605b517481de55b111295a8ade12ce330744fa8

**Comment by jenmeister** [comment]
I'm not sure if this is related to the same issue, but I am currently seeing an issue with "Hairstyle set 1" - screenshot attached. This persists after a cleared cache and reload.

User ID: c81c30c7-df61-415d-bf1a-f6a8d1e76f0a
Browser: Firefox 33.0 on Ubuntu 14.10

Even though I have unlocked it previously, and there are no "grey" boxes on the items (compared to beards for example), and I can already use all the hairstyles, it says "Unlock set - 5 gems".

And yes, clicking it will re-deduct 5 gems (I'm too curious for my own good - it would be awesome to have those returned if possible.)

![screenshot from 2014-11-28 22 28 24](https://cloud.githubusercontent.com/assets/8262620/5227469/d5d5080e-774f-11e4-9ac9-9ec16d2ae084.png)

**Comment by Alys** [comment]
@jenmeister I've given you back the 5 gems.

**Comment by Alys** [comment]
I'm closing this because the original problem has been fixed and the issue that @jenmeister had has been reported separately in https://github.com/HabitRPG/habitrpg/issues/4312
