### ISSUE TITLE
My habit is broken!!!!!

### ISSUE THREAD

**Issue by Cliojayne** [HabitRPG/habitica#3788]
My Habitrpg will not let me out of the inn, I'm not sure what's going on with it. I have tried multiple times on multiple devices and it's just not feeling it.

**Comment by Alys** [comment]
We'll need a bit more information before we can work out what's wrong. Please tell us:
1. Your User ID (UUID) - see [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find it
2. How you are trying to check out of the inn (i.e., where do you go and what do you click on).
3. Exactly what happens when you try to check out of the inn. Any error messages? Any change in what you see on the screen?
4. Which browser(s) are you using? If you're using Internet Explorer (very buggy), try Chrome instead.
5. What happens when you log out of HabitRPG, clear your browser's cache (note, the CACHE must be cleared, not just the browsing history), log back in, and try again?

**Comment by Alys** [comment]
@Cliojayne do you still need help with this (if so, we need the information from my previous comment) or is it working now and can we close the job?

**Comment by Cliojayne** [comment]
I do still need help with this I'm sorry, forgot I hadn't answered the email. I am including a picture of me API and uuid information. I am trying to get out of the inn the only way I know how, going to the tavern and clicking the leave the inn button. It does click normally and the boss pic/normal tavern stuff shows up like I had checked out, but my character is still in the inn. I am using Chrome or the mobile app version on my iPhone and either way it hasn't worked. As to your fourth question, I have tried clearing the cache and resetting my internet settings as much as possible. It makes me have to type things in the login haha but other than that no change. Habit is determine to have me resting in the inn for awhile. It has really made what was an extremely useful tool to me slightly useless bc I feel like I'm cheating checking stuff off when nothing will count against me.

**Comment by Alys** [comment]
Go to the Tavern page, and make sure it has COMPLETELY loaded - the thin blue bar at the very top of the page must have finished moving to the right and must have disappeared before you  do anything. Then, scroll down, click on the "Check Out of the Inn" button and again wait until the blue bar has finished moving and has disappeared. Reload the page. Your avatar should no longer have "Zzzz" on it.

If that does not work, give us your User Id. It was not included in your original post. DO **NOT** SEND US  A SCREENSHOT of the API page, for two reasons. Firstly, the page includes your API Token, which, as the page explains, is like a password and MUST be kept secret to protect your account. Secondly, to use your User ID, we need to paste it into a text field in an admin tool. We can't paste it from an image, and we don't want to type all 36 random characters. Please just copy the User ID (NOT the API Token) to your clipboard and paste it as text into a comment here.

**Comment by deilann** [comment]
Also, if possible... do this on a computer, not your mobile phone. It may
be an issue with your mobile browser. Do you not have access to a computer?

**Comment by Cliojayne** [comment]
I have access to a computer and generally habit on one (well really from three different ones) I just generally email from my phone. I will send the other info after trying the completely loading stuff here in just a bit.

**Comment by Cliojayne** [comment]
The completely loading apparently actually worked this time, so I guess we can close this :)
