### ISSUE TITLE
Boss damage does not occur at cron

### ISSUE THREAD

**Issue by juliemr** [HabitRPG/habitica#3790]
I'm in a party of two fighting Vice Awakens, and the Boss damage doesn't occur at Cron - it seems to occur when each individual player hits the site for the first time in a new day. I was sitting next to a party member when he logged on (9am) and I immediately got hit at that point. That's also when the message appeared in our party chat.

It's worth noting that we both have a custom day start of 01:00.

**Comment by thepeopleseason** [comment]
This is expected behavior. The custom day start is the latest a player can update their tasks. Cron runs on the next site interaction.

**Comment by juliemr** [comment]
Ah, thanks for clarifying - I see this now on http://habitrpg.wikia.com/wiki/Cron. It might be great to clarify this a bit in in-game documentation, since "cron" implies a set time to many of us.
