### ISSUE TITLE
Cannot choose a class

### ISSUE THREAD

**Issue by ceastman** [HabitRPG/habitica#3798]
Hi,

When I logged in today (over level 10), I was prompted to choose a class.  I was also given the option to not choose a class, which I did - I wasn't familiar with the classes.  I then went to the wiki to find out _how_ to change classes (having figured out what I wanted to be).  The instructions are as follows:
"Currently, you can change classes once for free when you unlock the class system at level 10. Thereafter, it costs three gems to change classes. To change classes, go to Profile → Stats and Achievements → Attributes and click the Change Classes button."

The attached screenshots are what I see when I get to the Stats and Achievements area.  There isn't a separate clickable area for Attributes, and there's no Change Classes button.  Please advise?

Thanks!

**Comment by ceastman** [comment]
Never mind; I found the Class System article (http://habitrpg.wikia.com/wiki/Class_System) which has different (and accurate!) instructions on how to enable classes.  Once one does that, it instantly pops up the "please choose a class" button.  Someone might want to edit the wiki to reflect this...

**Comment by deilann** [comment]
The information is accurate -- that's how you change classes. You needed
information on enabling classes. However, if you'd like to edit the wiki to
be more clear about your issue, you are free to do that. You don't even
need an account to edit.
