### ISSUE TITLE
Cleared Completed tasks show as empty tasks

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#38]
After completing a few tasks and then clearing completed tasks I returned to the remaining view and there are empty tasks in place of the completed tasks.

Completed view is empty.

Refreshing page has not removed the empty placeholder tasks but I am now missing some of my tasks. Logging out and back in to Habit RPG has not affected the issue. Nor closing and relaunching the browser.

See screenshots below for example. First screenshot shows the initial issue. Second screenshot shows the empty tasks and now missing tasks.

![Image 1](https://f.cloud.github.com/assets/3202339/47184/77bf0836-58bc-11e2-8111-c7a51146d457.png)

![Image 2](https://f.cloud.github.com/assets/3202339/47194/a9bef7c8-58bd-11e2-89d3-ba8ffd370d1b.png)

System Info:
Windows 7 Ultimate 64-bit (fully patched)
Google Chrome Version 23.0.1271.97 m

**Comment by lefnire** [comment]
oi, good times. On it.

**Comment by horusofoz** [comment]
I have identified the issue where the NON-completed tasks are missing from the second screenshot. 

It is because I never logged out off the application before refreshing the page. I am used to the auto-save features of other webapps. Will create a ticket for an auto-save or quick save button feature.

**Comment by horusofoz** [comment]
The above comment was made in error. Simply put the tasks that disappeared simply did disappear as per #43 . So that issue not caused by not logging out as @lefnire pointed in that ticket.

**Comment by lefnire** [comment]
try now

**Comment by lefnire** [comment]
how about now, with a refresh?

**Comment by horusofoz** [comment]
The empty tasks are gone. Well done :)

**Comment by lefnire** [comment]
holy phew! man, long story behind that one i wanna tell you sometime jeff, lol
