### ISSUE TITLE
Add tokens to FAQ

### ISSUE THREAD

**Issue by ancientcampus** [HabitRPG/habitica#380]
With the addition of mounts and the reinstatement of "tokens", the FAQ (and possibly the tutorial) will need to explain what they are.

Proposed addition to the FAQ:

What are tokens?
In the days of yore, arcade machines ran on tokens or quarters, and were known to gobble such nuggets with avaricious glee. Habit RPG has no wish to drain your pocket change, but those who use and appreciate it can support the project by turning real-world quarters into tokens, and using the tokens in turn to avert death, spruce up their character, and tame fearsome mounts to impress friend and foe alike!

(Feel free to edit/salvage bits as necessary. I'm not sure if tokens can still be used to avert death. I transfer all claim of ownership of those above words to Habit RPG, who can use any or all without need for credit or compensation. :P)

**Comment by lefnire** [comment]
added, thanks! (you're talking [GH wiki](/lefnire/habitrpg/wiki/FAQ) yeah?)
