### ISSUE TITLE
To-dos and dailies missing, but only in Safari

### ISSUE THREAD

**Issue by milehighfool** [HabitRPG/habitica#3804]
I've seen missing task bugs reported here before but I either (a) don't understand how they apply to my issue, or (b) my issue is new.

In this particular case, my list is complete in Chrome but most dailies and to-dos are missing when I access via Safari. Your advice?

**Comment by lefnire** [comment]
Hey there, make sure http://habitrpg.wikia.com/wiki/FAQ#I.27m_missing_some.2C_or_all.2C_of_my_tasks.21 isn't the case

**Comment by milehighfool** [comment]
Doesn't look like it. The weird thing is Chrome vs. Safari. I can't explain why it works it one and not the other.

**Comment by Alys** [comment]
@milehighfool : Even if it looks as if no tags are selected, please click the "Clear" button next to the tags. Does that fix it?

If it doesn't, on Safari, log out of HabitRPG, clear your browser's cache (not just your browsing history, the cache must be cleared), log back in, and click the tag "Clear" button again.

**Comment by milehighfool** [comment]
@Alys That did it. Thank you!
