### ISSUE TITLE
Cron runs erroneously when changing timezone

### ISSUE THREAD

**Issue by zofrex** [HabitRPG/habitica#3806]
Twice now when travelling I have been hurt because HabitRPG thinks the day has ticked over when it has not. In both cases I travelled west, changing my timezone by -8 one time and -5 the other. In both cases, I logged in to HabitRPG with my computer set to the new timezone and immediately saw a loss of health, even though it was before midnight in both my new timezone and in my previous timezone!

For example, right now I can see (by looking at the graphs) that HabitRPG thinks I have not done my dailies for the 29th. It's still the 29th in the timezone I was on this morning and in my new timezone.
##

**Comment by neoascetic** [comment]
+1 on this, please fix ASAP, we are dying there!

**Comment by paglias** [comment]
The latest changes by @Alys should have fixed this
