### ISSUE TITLE
Reset password don't work

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3809]
1. I enter my e-mail and password to login to system.
2. System shows notification that user login or password is invalid.
3. I select 'Forgot password', enter my e-mail and press send
4. I receive new password on my e-mail. I copy and paste it to login
5. System shows notification that user login or password is invalid (as in step 2)

**Comment by lefnire** [comment]
Do you have your UUID handy? If not, could you [email me](mailto:tyler@habitrpg.com) your email used?
