### ISSUE TITLE
Chrome Extension - Work Hours Bug

### ISSUE THREAD

**Issue by alexarze** [HabitRPG/habitica#381]
This bug is simple but actually throwing me off - it seems that the work hours are coded for a certain timezone, which appears to be an hour later than Central timezone. (USA, of course.) Just wondering if this is supposed to be happening.

My example is that it is 4:38 PM right now (according to my computer o.O) and I have my work hours set from 9 - 16. Shouldn't it be off right now? It turns off if I set it from 9 - 15, but 9 - 16 at 4:38 sets it on.

**Comment by StanLindsey** [comment]
I've moved this over to the Chrome Extension Repo at [#45](https://github.com/lefnire/habitrpg-chrome/issues/45)

**Comment by wc8** [comment]
Closing since it's listed in [habitrpg-chrome](https://github.com/lefnire/habitrpg-chrome/issues/)
