### ISSUE TITLE
Combined overall progress for challenge habits is wildly inaccurate

### ISSUE THREAD

**Issue by SyntaxPickax** [HabitRPG/habitica#3810]
The colors and graphs that supposedly represent the overall combined progress of participants must be incorrect for the habits in the challenge. The combined performance shows all blue habits with monotonically increasing progress graphs, while the individual challenge participants have almost entirely yellow habits with progress graphs that tell a much different story.

Overall progress:
![screen shot 2014-07-30 at 10 42 05 am](https://cloud.githubusercontent.com/assets/1245093/3753319/5643a9e4-1811-11e4-8ec8-a063e7005040.png)
![screen shot 2014-07-30 at 10 46 37 am](https://cloud.githubusercontent.com/assets/1245093/3753347/852f4ce0-1811-11e4-9800-7776725b7865.png)

Typical individual progress:
![screen shot 2014-07-30 at 10 42 30 am](https://cloud.githubusercontent.com/assets/1245093/3753324/5ceaedc0-1811-11e4-89c0-76cd7bba85c8.png)
![screen shot 2014-07-30 at 10 42 42 am](https://cloud.githubusercontent.com/assets/1245093/3753325/5fc42b7e-1811-11e4-8e4d-c30002c0de82.png)
##

**Comment by nimdahk** [comment]
The total graphs are not always monotonic - here's one from Read and Interact, a Scholars challenge:

![not monotonic](https://cloud.githubusercontent.com/assets/1014628/3803360/8b3bbd88-1c19-11e4-8deb-18d58acf0e8f.png)

**Comment by SyntaxPickax** [comment]
Ah, yes, you're quite right. Of course, they're still nowhere near accurate.

**Comment by deilann** [comment]
Actually, they are. They're just not doing what you are expecting them to
do.

They represent the combined value of all the Habit button pushes. The
reason they are all only going up is because the Habits are only positive.
Every time someone presses +, the value they add to their Habit adds to the
challenge.

Their Habits, however, drift back to zero every cron, halving their value,
so users don't end up with over-valued Habits that will never lose value.
(+/- Habits do not do this. They lose value by pressing the minus button.)

**Comment by SyntaxPickax** [comment]
Oh I see, although as @nimdahk points out, it doesn't quite explain why the graphs aren't truly monotonically increasing. Still, the overall progress habits (+ only) give a different picture from what I would consider "average". Also, I imagine they will almost always be blue, which makes the color kind of meaningless.  Is that really the desired behavior? It strikes me as much more intuitive to have the color and graphs match what individual users are seeing.

**Comment by deilann** [comment]
It does if that Habit is a +/- Habit. :)

I agree that it's not intuitive. The best solution might be to divide the
task value by the number of participants actually. I don't think they
should drift back to zero along with the users' tasks.

**Comment by Alys** [comment]
The task progress graphs have been removed in the website redesign and will be replaced in future with something better so I'm closing this issue. We can still refer back to it when needed.
