### ISSUE TITLE
Change class

### ISSUE THREAD

**Issue by laylavalentine** [HabitRPG/habitica#3813]
I bought the gems to change class .. I went into the screen, but inadvertently got out. Gems are dropped, but I can not change the class anymore. how can I do?

**Comment by deilann** [comment]
You still should be able to. Go to settings > site and click enable classes

**Comment by laylavalentine** [comment]
yes, it was off .. thanks :)

**Comment by deilann** [comment]
Awesome! I'm on mobile so i can't do it. Can you close this ticket? It's
next to the comment button.

**Comment by laylavalentine** [comment]
ok
