### ISSUE TITLE
Images Do Not Appear

### ISSUE THREAD

**Issue by WizardOfStaz** [HabitRPG/habitica#3817]
On Mozilla Firefox none of the habitrpg sprites will load. Items, avatar options, pets, gold, silver, the tavern, and the world boss are all blank. Page does not give me any errors or say it is still loading. Pretty much a game-ruiner for me.

**Comment by deilann** [comment]
Have you tried clearing your cache (not history) and reloading?

**Comment by WizardOfStaz** [comment]
That fixed it! Thank you.

**Comment by deilann** [comment]
No problem! I'm on mobile so can't close this ticket. Do you mind doing it
for me? The button is right next to the post comment button.
