### ISSUE TITLE
No Button to add Checklist on Android App

### ISSUE THREAD

**Issue by uvires1** [HabitRPG/habitica#3819]
There is no button to add a checklist to my dailys in the android app. I'm using a Asus Transformer pad 701 with Android 4.3

**Comment by Alys** [comment]
Is it possible that you are not using the latest version of the app? Go to your Google Play app and see if an upgrade is available. If not, please check again tomorrow. I've noticed with other apps that Play doesn't always let me upgrade immediately.

**Comment by paglias** [comment]
It should have arrived with the latest update
Il 01/ago/2014 01:52 "uvires1" notifications@github.com ha scritto:

**Comment by uvires1** [comment]
OK, I've waited a few days now, and still no button. I also checked for any updates anf there are none. Is no one else talking about this issue? I really dont think it is my device.

**Comment by lefnire** [comment]
The app now shows a version number, go to "About" (sidebar) and check the version at the bottom of the page. If it's not visible, then you're on too old a version. If it's < 0.0.31 (I believe it was), then it's too old a version. If it's 0.0.34, then crap - let's diagnose

**Comment by uvires1** [comment]
I have 0.0.34, so it looks like an issue.

**Comment by lefnire** [comment]
Damn. Thanks for checking, we'll look into it!

**Comment by deilann** [comment]
Just want to make sure you're looking in the right place. You need to go to
view/edit on a daily or to do (not a habit) and then click the pencil to
view the edit screen. (For the record, this is me simply ruling out
possibilities not calling you stupid. I always forget that the view screen
comes up first. Not super intuitive for me.)

**Comment by uvires1** [comment]
I got it now, thanks! I've used the pencil on the habit screen, don't know if I was just missing it on the daily or what. Thank again.
