### ISSUE TITLE
Feature Request: more pet options

### ISSUE THREAD

**Issue by ericwilmoth** [HabitRPG/habitica#382]
If one does not identify with available pets, but has ideas for new pets, what should we do?

**Comment by lefnire** [comment]
Create one! Well actually, I'm speaking out of turn.. @Pandoro @Shaners?
Were working on a community assets marketplace model, but in the meantime
those two might have input.

**Comment by Pandoro** [comment]
What would you be able to identify yourself with? There are certainly more
options, but creating them isn't exactly quick ;) I have still some other
pixel art on my plate, but if you give us some inspiration what you would
like, then we can look into it at some point.

Also I'm not sure how busy @Shaners is, maybe he will find the time sooner
than I do.

**Comment by ericwilmoth** [comment]
I'm an illustrator, so I know what you're talking about, time-wise. Not to mention, you have bigger fish to fry at the moment. 

One idea that leaps immediately to mind--[an atomic] rooster! Other animal ideas: a bee, a hare....those three do it for me. Actually, is there going to be an option to have more than one familiar?

Thanks!

**Comment by Pandoro** [comment]
Well we will probably stick with a normal rooster ;) 

Right now the focus is to get the Kickstarter backer items done. But as soon as I find the time, I will try to get some of this in there :)

While we are speaking of it, would you like a realistic as possible style? Or rather some kind of the comic/fun style? @ericwilmoth ? And everyone else out there!

**Comment by ericwilmoth** [comment]
I'm all about the comics! Fun it up! 
Though, I'd request leaning towards the bad-ass, rather than going too cute. 
Thanks!

**Comment by ericwilmoth** [comment]
Hey, wondering...as a temporary/flexible option...would there be a way to add a text-pet placeholder of some kind? either entering a description of a pet by oneself...until such a time that it can be incorporated fully? Not sure if i'm painting a clear picture...does this make sense? Basically one could select a 'blank' pet...type in description...like 'Pegasus' or something...and it would simply have a generic pet avatar, kinda like a generic facebook avatar...and it would work like any of the other pets...just with no graphic? and, if someone wanted to create their own graphic they could do that, too?

**Comment by Pandoro** [comment]
Well if you keep the same kind of style we have right now, feel free to give it a shot. If it is nice we can at some point maybe integrate it as a pet. I don't really see the point of a generic avatar though. You would still have to buy that for a set of tokens and then I think you are better of not buying one at all since apart from the looks they do not give any other benefit. 

Or you can post what you really want in the #107 thread. Maybe that will make it faster. Sadly I haven't gotten around to giving the pets you suggested a shot. :(

**Comment by ericwilmoth** [comment]
Ah--I just assumed the pets would add some benefit and level up along side of us...but if they're just jewelry for the characters then I guess it doesn't matter.

**Comment by Pandoro** [comment]
As of right now they are, but stay tuned regarding this topic :) There
might be some new things coming up when it comes to levelling up stuff. And
yes I can understand what you mean now. I will keep this in mind when
discussing such things! Thank you for the input.

**Comment by ericwilmoth** [comment]
My pleasure!

**Comment by wc8** [comment]
Would [Eggs](https://trello.com/c/dxD6mJOO) be a good place to post pet suggestions?

**Comment by lefnire** [comment]
closing this ticket, lots of new pets in the pipeline at https://github.com/lefnire/habitrpg/issues/942
