### ISSUE TITLE
"Close" button is nearly useless with sticky header

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3820]
If you have the "Sticky header" preference enabled, then click the "Close" button for the top menu ribbon, the menu items disappear but no space is actually reclaimed. While this does mildly reduce visual distraction, it doesn't accomplish much as far as reclaiming screen real estate (the way it does with Sticky header disabled).

The Close button should either float down into the party header space, or close the entire header including the party header.

**Comment by crookedneighbor** [comment]
@SabreCat Does anyone use the close/menu button? I kind of hate it.

**Comment by lemoness** [comment]
I am in favor of removing it.
