### ISSUE TITLE
Tags don't get out of the way of party scrollbar

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3821]
When the user's party is large enough to require a horizontal scrollbar, tags overlap the scrollbar in unsightly fashion:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3773522/78b7ed32-1910-11e4-93e9-bc24bb1c6537.png)

I've noticed this on Chrome and Firefox both.

**Comment by Alys** [comment]
Duplicate. :) https://github.com/HabitRPG/habitrpg/issues/2821

SabreCat, I've copied the labels you assigned to the earlier issue.

**Comment by SabreCat** [comment]
Exactly 1000 issues too late xD
