### ISSUE TITLE
Gold gem conversion cap reset problem

### ISSUE THREAD

**Issue by ozkansari** [HabitRPG/habitica#3822]
I've subscribed to Habitrpg on June 26. Gold gem conversion cap should have been reset on July 26. My subscription continues but it keeps saying that the capacity is reached, when I try to buy gems.

My user id is : ea41d6fe-a9d8-4f55-b34c-8054b623eb01

Message is:
_"You've reached the Gold=>Gem conversion cap (25) for this month. We have this to prevent abuse / farming, please wait until the beginning of next month."_

Thanks.

**Comment by deilann** [comment]
The cap always resets at the beginning of the month, like the message says,
not the date of your subscription. You will need to wait until the first.

**Comment by ozkansari** [comment]
Thanks. Sorry, I misunderstood that but this doesn't change anything. 
Today is the 1st of August. I didn't buy any gem today and I haven't bought any for a long time.
A new month starts and gem conversion cap resets, right? But it's not the case for me.

**Comment by deilann** [comment]
It's only been the first of August for a short time. If towards the end of
the day in the US it's still not working, clear your cache and try again.

**Comment by ozkansari** [comment]
Yes. I could have finally bought gems on the 2nd of August (GMT+3). Thanks.

**Comment by deilann** [comment]
Yeah, sorry -- the change takes a bit to permeate through folks and we're
here on the other side of the pond. ;) You get August before us.
