### ISSUE TITLE
In-game rewards not showing up in reward store.

### ISSUE THREAD

**Issue by MercuryChaos** [HabitRPG/habitica#3823]
I just saw the announcement today that some kind of special reward items were taken out of the reward store yesterday. I've been using HabitRPG all month when this event was going on and I never saw these items displayed in the reward store - just my custom rewards and spells. 

EDIT: I use HabitRPG in Chrome (Mac and PC.) My character is at level 80.

**Comment by deilann** [comment]
What's your user id?

**Comment by MercuryChaos** [comment]
ba9920a5-b079-4db8-ad25-f47bb81d2f5f

**Comment by deilann** [comment]
I looked and you purchased quite a bit of it, including the Rainbow Armor
and Helm, and the Summer Healer items, so you most certainly saw it.

**Comment by MercuryChaos** [comment]
Derp. You're right.
