### ISSUE TITLE
Gem costs could use some padding between quantity and icon

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3828]
In the Market, the costs for various items have no spacing after the numeral, causing them to run into the gem icon:

![screenclip](https://cloud.githubusercontent.com/assets/4501321/3787051/b07a7598-19f9-11e4-88e8-76a90f2dab6c.png)

Even a couple of pixels' gap would make this look nicer!

**Comment by jobywalker** [comment]
Just adding padding will cause issues with the current CSS design, but a couple minor layout changes will make it work.

**Comment by crookedneighbor** [comment]
@jobywalker If you'll rebase this PR, I'll take a look at it. This has been an issue that's been bugging my front-end dev brain.
