### ISSUE TITLE
iPhone app: No display (v 0.0.31, August 1st)

### ISSUE THREAD

**Issue by sebi21** [HabitRPG/habitica#3829]
Hi there!

The newest update shows a crashed display on iPod touch (see picture).
Can you help?

I need the app! ;-)

Thanks,
sebi21
![2014-08-02 06 43 54](https://cloud.githubusercontent.com/assets/8335574/3787132/e9ee5382-1a01-11e4-880a-9e889d4647ec.png)

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg-mobile/issues/246

@sebi21 : You can follow the progress of the fix from that URL. Use the Notifications button in the right-hand column if you'd like email updates.
