### ISSUE TITLE
Feature request: Questgiver

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#383]
If anybody is like me they are often indecisive about what to do next (especially if they have a to-do list with hundreds of items in it). A questgiver who would suggest tasks to take on, picked randomly but weighted so as to take into account dailies and urgency, would be a godsend.

For the coin-hoarder, they might also suggest spending a few on a reward from time to time.

**Comment by StanLindsey** [comment]
Considering we've now sold the "Quest Giver" backer reward on [Kickstarter](http://www.kickstarter.com/projects/lefnire/habitrpg-mobile) this will happen. Tyler & I have had some chats about its implementation and its pretty much exactly as you suggest. Great minds think alike ey! 

Going to close this for housekeeping but rest assured this is on its way, though after a bunch of other more important features first. Thanks for being involved!
