### ISSUE TITLE
I don't even know. Aliens?   [Images displaying incorrectly]

### ISSUE THREAD

**Issue by WizardOfStaz** [HabitRPG/habitica#3830]
This problem is gone now because I refreshed the page, but it's so strange I had to post it. 
![habitwtf](https://cloud.githubusercontent.com/assets/8324026/3787261/3735c968-1a0c-11e4-9b13-34f51fe1607a.png)

How does that even happen!?

**Comment by Alys** [comment]
### It's just a temporary local browser error from images being loaded incorrectly. Whenever you see any odd glitches like that on HabitRPG (or any website really), reload using your browser's refresh/reload button. If that doesn't work, clear your browser's cache (not browsing history, but actual cache) and reload again.

**Comment by lefnire** [comment]
rofl! love the title

**Comment by deilann** [comment]
The background kind of looks like aliens, too.
