### ISSUE TITLE
Iphone app useless after update?

### ISSUE THREAD

**Issue by SugarNinja** [HabitRPG/habitica#3831]
An update was just pushed to my iphone and it has pretty much rendered the app useless. I can no longer switch between Dailies, Habits, To Do without completely shutting down the app and re-entering. I can't tap some of the items because they are hidden under my phone's signal strength/time bar. I use the app pretty regularly, since I'm not always at my computer, so it's instantly frustrating. I'm hoping it's just a glitch and there will be another update today to fix it? Or revert back to the old one till this is fixed? 
![photo](https://cloud.githubusercontent.com/assets/8338550/3788421/78d78bb4-1a65-11e4-9d2e-2dc92f2d149b.PNG)

**Comment by paglias** [comment]
@SugarNinja see https://github.com/HabitRPG/habitrpg-mobile/issues/246
