### ISSUE TITLE
Make sleeping in the inn more obvious

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#3833]
Just an idea I had. When a user is in the inn, additionally to displaying the zZZ above their head, the avatar eyes could be closed.
before creating the new images for all skins, I wanted to make sure that other people find the idea interesting enough to get merged.
The overhead is pretty low (only one additional line in the avatar template). There just has to be a sleeping version of each skin.

If you like the idea, I'll make a pull request with it.

![habitrpg-sleeping](https://cloud.githubusercontent.com/assets/298062/3789267/2530f982-1a97-11e4-9566-d8379a05245d.png)

**Comment by deilann** [comment]
This could fix the issue of the ZZZ not showing up well against all backgrounds. I approve heartily.

**Comment by phillipthelen** [comment]
as @deilann pointed out, the ZZZ currently also is not very visible on some backgrounds. I added a white border around it for testing. Imho this makes it a lot easier to see, without changing too much.

![zzzbg](https://cloud.githubusercontent.com/assets/298062/3789415/9f5bd7f4-1aa1-11e4-96e9-d2630668ec93.png) ![zzzplain](https://cloud.githubusercontent.com/assets/298062/3789416/9f602a84-1aa1-11e4-9371-c3567a8ba72a.png)

**Comment by deilann** [comment]
paging the thinktank: @benmanley @lemoness @Alys @lefnire @SabreCat and heck, I know I'm missing people and let's throw in @huaruiwu for good measure and... pretty much anyone anyone wants to tag.

**Comment by benmanley** [comment]
@vIiRuS I like it!

**Comment by Alys** [comment]
Pretty!! Obvious without being blatant.

**Comment by lemoness** [comment]
I think it looks super cute. A+ from over here! Just a note, though - don't forget to include all the limited edition skin colors.

**Comment by huaruiw** [comment]
Absolutely!

**Comment by phillipthelen** [comment]
If all the limited editions skins are in the same folder as the other ones, i have them covered. (It seems that way, from the files that are in there)

**Comment by SabreCat** [comment]
Cool! :+1:

**Comment by phillipthelen** [comment]
Fixed with #3837
