### ISSUE TITLE
Desert Wolf displayed improperly after hatching

### ISSUE THREAD

**Issue by JenniferNeff** [HabitRPG/habitica#3835]
Immediately after hatching my Desert Wolf, he displayed as a chunk of Octothulu, as in the attached image, both in the pets menu and when beside my character. Some minutes later, a refresh using the browser's refresh button fixed his graphics. Other navigation within HabitRPG itself didn't fix it before that. The only other hatched pet I have is a Skeleton Cactus; I also hatched that today and it didn't suffer any errors.

I'm c5183dfa-c741-43ce-935e-c6d89b41a030, using Chrome Version 36.0.1985.125 m. Unfortunately, I cleared the error log in an ill-conceived attempt to isolate the relevant message and didn't get any that might have pertained to this.

![wolf octothulu bug](https://cloud.githubusercontent.com/assets/8341199/3789851/06a99eaa-1aca-11e4-8d56-a80b7e8f7a50.png)

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/3830 for an explanation and fix. In brief, whenever you see anything odd, just try reloading. That fixes many glitches.
