### ISSUE TITLE
Autoequip only better items

### ISSUE THREAD

**Issue by JanChec** [HabitRPG/habitica#3838]
It's very annoying that when I die and rebuy an item my char is automatically using it. Most of times it is worse thing than my best. Every such time I have to go and correct it manually. That's the worst aspect of my Habitrpg experience.

**Comment by Alys** [comment]
This has been reported in https://github.com/HabitRPG/habitrpg/issues/2711 and as you'll see from that discussion there are reasons to have it working the way it does now as well as reasons to change it. Chime in on that discussion if you wish, and follow it for news about changes. There's a Notifications section in the right-hand column that will let you get email notifications for that issue if you would like them.
