### ISSUE TITLE
Change of destroyed item after death

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3839]
After login I got the message that I had died and that my Stephen Weber's Shaft of the Dragon was destroyed. The shaft was also on the list of items I could buy.
I went to the market and sold 66 eggs for 198 gold. Then I went back to the task page and clicked on the + of one of my habits. After that I had enough money for the shaft but instead of the shaft there was now a scimitar in the list with its normal price.
I had the shaft equiped before I died but not afterwards.

**Comment by Alys** [comment]
This is https://github.com/HabitRPG/habitrpg/issues/2789

Please use that issue to follow the progress of a fix.
