### ISSUE TITLE
Todos Progress Button Disappears

### ISSUE THREAD

**Issue by kalmduck** [HabitRPG/habitica#384]
Using Chrome Version 24.0.1312.57.
Clicking the 'Progress' button under the Todos correctly displays the progress graph, but then the button disappears.  In order to hide the graph again, I must reload the page.

**Comment by wc8** [comment]
Hm... I don't have a Todo progress button. Todos are a one-time thing. Are you referring to dailys or habits?

**Comment by lefnire** [comment]
It's a solitary button, below all the todos (below the tabs). This is a
confirmed bug.

**Comment by wc8** [comment]
I'm listing this as minor since there is a workaround for now: reloading.

**Comment by horusofoz** [comment]
@kalmduck Is this still an issue?

**Comment by kalmduck** [comment]
Looks like this is fixed, now.
