### ISSUE TITLE
Dailies not reset after leaving inn

### ISSUE THREAD

**Issue by mereprototype** [HabitRPG/habitica#3840]
I had to spend some time in the inn recently and last night, once I left, all of my Dailies were in the same status of checked/not checked as when I entered. I assumed this would change when my day rolled over at 11AM but that hasn't happened -- it's still in the shape it was when I went to bed around 4AM. Is this a glitch between the inn and my day start time or is it a smaller error that can be quickly tweaked and fixed?

**Comment by Alys** [comment]
_"once I left, all of my Dailies were in the same status of checked/not checked as when I entered."_  That's the intended behaviour. For further info about that, see the message on the Tavern page around the "Check into Inn" button, or the wiki's [Tavern](http://habitrpg.wikia.com/wiki/Tavern) page.

_"I assumed this would change when my day rolled over at 11AM"_  That's a known issue that happens occasionally. See "Dailies Remain Checked after Cron" on the [Known Bugs](http://habitrpg.wikia.com/wiki/Known_Bugs#Dailies_Remain_Checked_after_Cron) page for a workaround. Follow https://github.com/HabitRPG/habitrpg/issues/1057 for news on a fix.
