### ISSUE TITLE
Abandoned solo party

### ISSUE THREAD

**Issue by n-luca** [HabitRPG/habitica#3844]
Hi! I used the Egg Hunt quest Scroll a few days ago and started a solo party. I left said party before finishing the quest.Is there some way to get the scroll back please?

**Comment by deilann** [comment]
UUID please?

**Comment by n-luca** [comment]
3b44fdf0-196f-4786-a2e1-9ffa56803d58

**Comment by deilann** [comment]
Gonna fix you up in a sec. :) In the future, you can avoid this by aborting
the quest before you leave the party.

**Comment by deilann** [comment]
You are all set. :)

**Comment by n-luca** [comment]
Thank you :)
