### ISSUE TITLE
Quest scroll disappears from inventory after quiting an empty party

### ISSUE THREAD

**Issue by QvCHh4p8l9gl** [HabitRPG/habitica#3845]
I have that issue, I was soloing a quest and quit the party withouy aborting it first. I assume the quest simply stayed in the empty party. I don't have the scroll now.

The scroll name was Trapper Santa. 
9098a561-f7b3-4810-824b-28e754df67b7

**Comment by Alys** [comment]
I've given you back the quest scroll. You will have to reload to see it.

**Comment by QvCHh4p8l9gl** [comment]
Thank you!
