### ISSUE TITLE
After I casted a spell the game doesn't check if I have leveled up.

### ISSUE THREAD

**Issue by ludat** [HabitRPG/habitica#3850]
The bug is really simple. I'm a wizard and after I cast "Burst of Flames" on a task I gain some XP but the game doesn't check if I have leveled up as a result and I get 348/330 XP.
![Here's a pic](https://cloud.githubusercontent.com/assets/4952044/3838600/b53087d4-1e05-11e4-84f5-771172b073eb.png)
[And the pic on imgur](http://i.imgur.com/hmRKeU4) just in case github hates my image
This is really easy to fix (not the code). I just have to do something else like completing a Daily or a ToDo or updating a Habit and then the server checks if I have leveled up and applies the proper changes.

When I force the server to update I think it counts the overflowed XP

I have the weekend free so **_MAYBE**_ I'll dedicate some time to it.

**Comment by Alys** [comment]
This has been reported before: https://github.com/HabitRPG/habitrpg/issues/2143

If you'd like to spend time helping us fix it, that would be fantastic, just note the proposed fix in that thread.
