### ISSUE TITLE
Facebook login via Android device

### ISSUE THREAD

**Issue by chankeypathak** [HabitRPG/habitica#3851]
I'm unable to login to HabitRPG using the userid and token taken from https://habitrpg.com/#/options/settings/api. When I tap the "Submit" button nothing happens. 

Device: i9082
Android version: 4.4.3

**Comment by lefnire** [comment]
We've seen this from time to time - could you try uninstalling/reinstalling
and trying again?

**Comment by deilann** [comment]
Also sometimes rebooting your phone after install seems to help.

**Comment by negue** [comment]
@chankeypathak Could you retest it? The Facebook Login was updated recently.
