### ISSUE TITLE
Can't create challenges in locally set up HabitRPG

### ISSUE THREAD

**Issue by efim** [HabitRPG/habitica#3852]
After filling up all fields and clicking 'Save' there are two pop-ups - first 'Challenge created' and second 'Please reload, "Error Unsupported projection option: $elemMatch"'
http://pastebin.com/smy2U9v8# - console content.

Tasks from challenges appear in 'Tasks' section, but challenges are not displayed on Social/Challenges screen.

**Comment by Alys** [comment]
I can't replicate this on my local install. It all works as expected. Is it still happening for you? Does it happen even on a new branch that's identical to upstream/develop? Does it still happen if you delete all groups content from the database and create a new party/guild and then create the challenge in that?

If it is still happening, tell us the exact parameters you're using for the challenge.

**Comment by paglias** [comment]
have you executed the seed.js file?

2014-09-11 10:20 GMT+02:00, Alice Harris notifications@github.com:

> I can't replicate this on my local install. It all works as expected. Is it
> still happening for you? Does it happen even on a new branch that's
> identical to upstream/develop? Does it still happen if you delete all groups
> content from the database and create a new party/guild and then create the
> challenge in that?
> 
> If it is still happening, tell us the exact parameters you're using for the
> challenge.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3852#issuecomment-55233808

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
seed.js is presently not required, due to https://github.com/HabitRPG/habitrpg/blob/develop/src/models/group.js#L322 (we can either remove the file, or keep it around in case of future seed updates). I think the problem here is mongodb version (`Error Unsupported projection option: $elemMatch`). @efim what's your `mongo --version` ?

**Comment by negue** [comment]
So we can close this?

**Comment by paglias** [comment]
I think so, it was the same error I got when I didn't upgrade to 2.6 from 2.4

**Comment by melissamcewen** [comment]
I'm having this issue as well. Version says MongoDB shell version: 2.0.4
it's a pretty clean Vagrant instance. What's the recommended way to update?

**Comment by Alys** [comment]
When I looked into it last, it turned out to be simplest to uninstall mongodb and reinstall version 2.6.

**Comment by melissamcewen** [comment]
Thanks @Alys , following these instructions worked
http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/
would it be possible to update the Vagrant configuration so it automatically has the right one?

**Comment by Alys** [comment]
@thepeopleseason _"would it be possible to update the Vagrant configuration so it automatically has the right one?"_   Is that something you'd like to work on, or should I?

**Comment by melissamcewen** [comment]
I could try it...what is the name of the file that tells Vagrant what packages to install? Or would I put the command in vagrant.sh?

**Comment by Alys** [comment]
Thank you! It would go in vagrant.sh - you'll find in there the default ubuntu command for installing mongodb so that's what you'd need to replace. However first wait a day or so to see if thepeopleseason replies because he set up the Vagrant configuration.

**Comment by thepeopleseason** [comment]
Hey, sorry. I've been in the midst of baby and work. @melissamcewen, if you want to go ahead and update the script, feel free!

**Comment by Alys** [comment]
Reopening because we still need to update the Vagrant configuration so it automatically installs the correct version of mongod. The production site currently uses mongod 2.6.4

**Comment by melissamcewen** [comment]
I have this ready, I can test it this afternoon and initiate a pull request

**Comment by melissamcewen** [comment]
BTW in the future if we want to switch to Chef Provisioning I'd be interested in helping and/or spearheading. I don't know Chef but I've worked with some Vagrant instances that use it and would love to learn it. http://docs.vagrantup.com/v2/provisioning/chef_solo.html

**Comment by Alys** [comment]
I looks like this is all fixed now, so I'm closing again. Comment here if I'm wrong.

@melissamcewen If you're still interested in switching to Chef Provisioning, you're welcome to open a  new issue for us all to discuss it in.
