### ISSUE TITLE
Drop notifications not popping up

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3853]
Recently, I've been having pet items appear in my Market without an accompanying drop notification. Over the last three clicks, for instance, I got drops every time, but only received a notification on one (a Skeleton Potion from a Daily); the other two (Blue Cotton Candy and Milk from two + Habit hits) dropped silently.

**Comment by lemoness** [comment]
We've been getting a lot of reports of this recently and assumed it was because people were using the mobile app. Guess not?

**Comment by SabreCat** [comment]
Nope. I thought that at first, but I reproduced it using only the Web site. Emptied out my food, clicked a couple tasks, came back and poof, more food.

**Comment by paglias** [comment]
It might be my fix to drops with partial translations? I tested it and seemed to work... I can't revert it now so if someone of you wants to do it it should be one of my last conmits

**Comment by iamcrumpet** [comment]
I've had this problem today. The only thing I did differently yesterday was updating the HabitRPG app, but I haven't used it or opened it. I haven't used the app in over two weeks. I exclusively use the website on my desktop computer, and this problem started this morning. I go into my inventory and there's food there, but the notification never popped up with the XP and gold information.

**Comment by SabreCat** [comment]
Turns out this is a duplicate of #3787. Continue there!
