### ISSUE TITLE
PUT "/user/tasks/{id}" gives infinite loading

### ISSUE THREAD

**Issue by 71** [HabitRPG/habitica#3861]
I'm currently developping an HabitRPG app for Windows Phone, so I use the API. The thing is, I can't update anything anymore. Even when I use the [Swagger API](https://habitrpg.com/static/api#!/user/user_tasks_GET), I have this image: 
![swagger ui - torch](https://cloud.githubusercontent.com/assets/7189784/3866135/4abd08ea-1fc3-11e4-9a76-4df721dc9f74.png)[For those who use the Swagger API, this image is like a loading, it disappears quickly, and the results are then loaded]
I have used the API for a few weeks now, and I was able to update any task without any trouble. But now, I can't update anything. 
It's been here for three days now, I think.

**Comment by lefnire** [comment]
that image didn't come through. Are you seeing any error in the response code? I can't replicate on my end, it's [responding just fine](http://gyazo.com/8ee6442e008ec468a7dff619d1125d7e)

**Comment by 71** [comment]
It's working again since yesterday, or the day before yesterday. Weird. Thank you!
