### ISSUE TITLE
Tag names starting with # are displayed bigger

### ISSUE THREAD

**Issue by loial1** [HabitRPG/habitica#3864]
When you name a tag #something, the tag something appears bigger than the other tags in the list on the tasks page. Is that normal? I am reporting it, it is probably not the expected behaviour. 

![bug](https://cloud.githubusercontent.com/assets/8407714/3869078/4f4e57f2-207b-11e4-808c-2d95f88f7289.png)

loial.

**Comment by Alys** [comment]
This is expected behaviour because HabitRPG allows you to use markdown to format your tasks and tags. The # is the markdown symbol for larger text. You can learn more about markdown on this wiki page: [Markdown Cheat Sheet](http://habitrpg.wikia.com/wiki/Markdown_Cheat_Sheet)

**Comment by loial1** [comment]
Thank you for your quick answer, and thank you for the link. I checked the Tags section to see if this was normal, I should have thought about looking at the Markdown Cheat Sheet. Anyway, it's good to know.

**Comment by Alys** [comment]
Ha! Yes, the Tags page doesn't mention markdown at all, does it? That's an oversight! I'll fix it right now. Thank you for mentioning that!!

**Comment by loial1** [comment]
No problem, I am happy to contribute a tiny little bit! Have a good day.
