### ISSUE TITLE
Massive health loss for no reason

### ISSUE THREAD

**Issue by michael21115** [HabitRPG/habitica#3867]
So I'm not in a quest but I've been losing health at random points throughout the day for about two weeks now, even when all of my dailies were completed. I entered the Inn just because I kept losing all of my health and dying within a day, and now that I'm in the Inn I'm still losing all my health and dying. There doesn't seem to be any rhyme or reason to when I lose my health either, it's not on cron (which I have set to 2AM). Whatever it is, it seems to take off about 12 HP every couple of hours, so if I leave it alone throughout the day I end up going from fifty HP to zero.

**Comment by Alys** [comment]
Please paste your User Id into this issue as plain text (not a screenshot). See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

**Comment by deilann** [comment]
Also do you have any third party extensions or use the chrome extension?

**Comment by michael21115** [comment]
User ID: 195d11fc-5b5d-4e7b-9caa-7ceb4e9351cd

**Comment by Alys** [comment]
@michael21115 : Could you please consider @deilann's question too? It's actually the most common explanation for the behaviour you are experiencing.

Please check your browser's extensions list to see if there are any extensions that mention HabitRPG (if so, they are probablly subtracting health from you when you visit websites that are configured as "bad" in those extensions).

Also consider if you are using any other third-party tools or custom-built scripts that use HabitRPG's API.

**Comment by michael21115** [comment]
Oop, I missed that one. You're right though, upon closer inspection it does seem to have been the chrome extension, it must have turned on in the background at some point without me realizing I still had it even. Now that I've removed it the site is functioning normally and I haven't lost any more health.

**Comment by Alys** [comment]
Thanks for letting us know! I'm glad it's fixed for you. :)
