### ISSUE TITLE
develop branches reverted to May 12 for habitrpg and habitrpg-shared

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3868]
When I look at the develop branches in both habitrpg and habitrpg-shared, it looks like they've been reverted to an old state. The latest commit date is May 12 and a lot of recent content is missing from content.coffee.txt in habitrpg-shared (no backgrounds are there now, for example).

**Comment by deilann** [comment]
Yup dealing with the same issue here.

**Comment by deilann** [comment]
no, I think this is totally my fault. I think I zonked and forced a push to upstream instead of origin.

**Comment by Alys** [comment]
We'll sort it out. Nothing is ever lost in git. :)

**Comment by Alys** [comment]
If there's any git experts online now, advice about a quick fix would be welcome. Otherwise we'll keep bumbling through until we have this sorted.

I could push my own local version of develop which is quite recent, but I'm concerned about making the situation work. However if I haven't found a better idea very soon, I'll do it.

**Comment by Alys** [comment]
We think we have both develop branches back to how they should be.

Ryan did this for habitrpg:
    `git push --force upstream b19649c:develop`
and I did this for habitrpg-shared:
    `git push upstream 431b1da:develop`
Those IDs were the most recent ones listed from `git reflog show remotes/upstream/develop`

**Comment by lefnire** [comment]
My local branches show the same results, I think all's well
