### ISSUE TITLE
Dailies task should reset daily.

### ISSUE THREAD

**Issue by kulalking** [HabitRPG/habitica#3869]
it was working fine some time back, i guess new build has this issue

**Comment by Alys** [comment]
Can you give us more information about the problem? I'm not sure what you mean. What actuallly is happening or not happening? For how long has the incorrect behaviour been occurring?

Also please paste your User Id into this issue as plain text (not a screenshot). See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

**Comment by kulalking** [comment]
user id : 27b01fab-ad6e-4a19-9134-70fbce3b38c4
My daily task is gray(marked as done task) always, i am expecting that to be yellow(not completed) daily so that i can work on them. and build the habbit...

**Comment by Alys** [comment]
@kulalking : You are "resting in the inn". That's why your dailies aren't resetting. See the wiki's [Tavern](http://habitrpg.wikia.com/wiki/Tavern) page for an explanation and for how to check out of the inn.

**Comment by lefnire** [comment]
And if you're not in the inn, see #1057 (also, make sure you're not currently using beta.habitrpg.com)
