### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3871]
Some how on my RPG game my health does not go down even when i'm not doing my dailies, also the colors of the dailies does not change either.
![captura de pantalla de 2014-08-11 17 59 17](https://cloud.githubusercontent.com/assets/3812582/3884177/4a984070-21ab-11e4-811e-272b64cf9a88.png)

**Comment by deilann** [comment]
You have disabled all the days on which that daily is due, hence it being
grey. Edit it and turn on the days you'd like it to be due.

**Comment by ghost** [comment]
First Thank You and Second, allow me to apologise for this stupid mistake.

**Comment by Alys** [comment]
No worries, it happens. :) Thanks for your reply!
