### ISSUE TITLE
My tasks no open on Chrome

### ISSUE THREAD

**Issue by barbaradduarte** [HabitRPG/habitica#3873]
Hey guys, 
I've been using HabitRPG for almost a year, but, in the last week, when I open my account I can't see my tasks (when using Chrome). When I open in Internet Explorer I can see the tasks but I can't see the pet status bar. About everything else, the site is ok in both browsers.

**Comment by thepeopleseason** [comment]
Can you check if you have any tags selected (in Chrome)?

**Comment by barbaradduarte** [comment]
I checked this, and I haven't

**Comment by Alys** [comment]
@barbaradduarte Click the Clear button to the left of your tags, even if it looks like all tags are already clear. That will probably make your tasks reappear.

Internet Explorer has many bugs and non-standard features so it's best to not use it for HabitRPG. However you could check under Settings -> Site to see if the header checkboxes are ticked or not. Toggling them might fix the IE header problem.

**Comment by barbaradduarte** [comment]
Worked, thanks !
