### ISSUE TITLE
Phone app isn't syncing

### ISSUE THREAD

**Issue by BunnyManders** [HabitRPG/habitica#3874]
I checked off some dailies on the phone app, using the wireless connection at my house, but when I checked the website my tasks had been listed as incomplete. I tried again with 4G, it still didn't go through. I also noticed that tasks I knew I had completed on my to do list were still showing up on the phone app as incomplete.

**Comment by crookedneighbor** [comment]
I've had to manually sync (pull down from the top) whenever I use the phone app.

**Comment by dedalus71** [comment]
Continued and recurring problems with syncing to and from iphone app.  No obvious confirmation that a manual sync has taken place and no obvious method of manually syncing. (pull down to refresh/sync is native to many apps, but without confirmation is pretty useless).
WIthout a reliable method of syncing between phone and web this app becomes virtually useless for anyone wishing to use it as a serious method of managing actions and recurring tasks.

**Comment by lefnire** [comment]
manually syncing is the solution for most people. @dedalus71 you may have some special issue going on, do you have your [UUID](http://habitrpg.wikia.com/wiki/API_Options) handy?

**Comment by crookedneighbor** [comment]
As this issue is quite stale, I'm closing it. Reopen if you still need help.
