### ISSUE TITLE
Quest scroll disappeared from inventory after quitting empty party?

### ISSUE THREAD

**Issue by sirtonyx** [HabitRPG/habitica#3875]
I have an issue. today the scroll "Attack of the Mundane Questline, Pt. 1: Dish Disaster!" dropped to everyone over lever 15. I had just finished a solo quest so I decided to check it out with my solo quest party. when I saw that it required finishing habits, I decided to do it later since my mana is at max and better used casting spells, so I left the party thinking I'd be able to quest later. to my horror I discovered I no longer had the scroll in my inventory. now it looks like I should have aborted the quest instead of leaving it, but I didn't know I had to do that or even how to do it. I assume the quest now simply stayed in the empty party and so I don't have the scroll anymore. can someone please restore the scroll to my invetory? my user id is 15c2425f-84da-4b49-8ca0-6a6e9ad0a09d

**Comment by Alys** [comment]
I'm about to do this for you. In a couple of minutes, reload your Inventory page and you should see it there. You might need to shift-reload or clear cache. Comment here if you still can't see it and I'll reopen this issue.

**Comment by sirtonyx** [comment]
Thank you Alys, I see it again now, thank you so much!
