### ISSUE TITLE
Stuck in 'pending' as party readies for Vice scroll #3

### ISSUE THREAD

**Issue by IstraLouise** [HabitRPG/habitica#3877]
Didn't receive an option to accept Vice quest #3   The rest of my party is ready to go and i don't know how to trigger it to give me the option of accepting the quest.   I've been all over the site and nothing happens.  The other two times a popup came up filling the screen with a big 'Accept' button and I didn't have to do anything.

**Comment by Alys** [comment]
Go to your party page and reload it using your browser's refresh button. If that doesn't work, log out, log back in, go to your party page and reload again.

Tell us whether that works for you or not.

**Comment by IstraLouise** [comment]
A member of my party had the idea of clearing the cache of cookies and files. I did that and then I got an invite to the quest and was able to accept.  I think I'd already tried refreshing the page. I know I'd tried hitting the sync button and traveling between pages in my account.

Yay, though! Problem solved! And thank you for your time and timely reply!

Theresa (IstraLouise)
