### ISSUE TITLE
Shuffle tasks on refresh

### ISSUE THREAD

**Issue by scalegraze** [HabitRPG/habitica#3878]
I am finding that when I am on my work's network, I can reorganize my tasks based on my own preferences and when I refresh, the tasks then shuffle back to where they were.
I saw that there was an old thread on a similar issue, but it closed long ago.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2606

There's a workaround described here: http://habitrpg.wikia.com/wiki/Thread:15177
In brief, delete your completed to-dos and then you should find that sorting works
