### ISSUE TITLE
Started a Quest and now my party doesn't seem to exist?!

### ISSUE THREAD

**Issue by L1st3r** [HabitRPG/habitica#3879]
Text when I enter the party section:
You are either not in a party or your party is taking a while to load. You can either create one and invite friends, or if you want to join an existing party, have them enter

I don't remember what the scroll/quest was, but it's now gone, and I also am not IN the quest either!

**Comment by lefnire** [comment]
try reloading the page a few times. It could be you belong to multiple parties (a bug), and you need to leave the "wrong" one. If reloading the page sometimes gives you a different party, that's the indicator - click "leave party" when the wrong/blank one shows up. If that doesn't do the trick, tell us your UUID & I'll investigate

**Comment by L1st3r** [comment]
I def didn't join a 2nd party. There is no "leave party" option. I refreshed the page multiple times to no avail. There's a GUID on the party page, is the the UUID you're looking for?

**Comment by lefnire** [comment]
Nay, UUID here http://habitrpg.wikia.com/wiki/API_Options

**Comment by L1st3r** [comment]
I feel weird putting my UUID here, I'll email it to you!

**Comment by L1st3r** [comment]
I think you fixed it. Thank you!

**Comment by lefnire** [comment]
Hmm, I haven't had a change to look into so wasn't anything on my end. No log-out/log-in or different computer or anything? (aka, making sure you don't have 2 accounts). Re-open if re-experience, and I'll still look into when I can

**Comment by L1st3r** [comment]
lefnire, it just happened again! What info do you need from me?

**Comment by Alys** [comment]
@L1st3r Please log out of HabitRPG, clear your browser's cache (it must be the cache that you clear; not just browsing history, for example), log back in, and then reload the party page and wait 30 seconds.

If that doesn't help, please paste your UUID into this job. lefnire probably hasn't kept the email you sent the last time this happened.

Note that making your UUID public is completely safe (mine is d904bd62-da08-416b-a816-ba797c9ee265). It doesn't give anyone access to your account; it's just like a username. If you ever post to a guild or the Tavern, any HabitRPG player can see your UUID in your profile. Having the UUID in this issue makes it easier for multiple developers/admins to assist you if needed.

**Comment by L1st3r** [comment]
Logging out and then back in again fixed the problem. I'll remember to do that in the future if this happens again. Thank you!
