### ISSUE TITLE
Active quest disappears on second day and reappears on third day

### ISSUE THREAD

**Issue by meiloslyther** [HabitRPG/habitica#3881]
I started the dishwasher quest yesterday and after cron this morning it's disappeared without a trace. I've seen one other issue like this (closed) but no solution. I know I'm not in more than one party because I never joined one before and so had to create one to start my quest in the first place.

**Comment by Alys** [comment]
Did the quest scroll reappear in your inventory?

If it did not, tell us your Unique User ID (Settings -> API).

**Comment by meiloslyther** [comment]
The next day it mysteriously reappeared in my party as active, and even showed the items I'd acquired the day it was gone. It has done this with each subsequent quest (disappearing the second day and reappearing the next). But otherwise there seems to be nothing wrong.

**Comment by crookedneighbor** [comment]
Closing this as a temporary issue. If you're still having trouble, reopen it.
