### ISSUE TITLE
mage no fun

### ISSUE THREAD

**Issue by tbelaire** [HabitRPG/habitica#3883]
I feel like the game got really pointless once I hit level 11 and became a mage, and could just turn MP into EXP to level up and heal myself.

Before, if I was doing poorly, I'd have to be very careful, and make sure to not miss any dailies, but now I can just plow through to finish off a level, and it is a lot less fun.  Does this ability to just plow through levels stop at some level?

**Comment by thepeopleseason** [comment]
You'll still have the ability to plow through levels throughout the game, which is only an advantage if your primary intent in playing is to level up. If, however, you want to improve your habits or keep track of tasks, you might want to change the way you play the game. One option is to only use spells if you can pay gold for them. I'd recommend hitting up [the wiki forums](http://habitrpg.wikia.com/wiki/The_Keep:The_Mage%27s_Tower) for advice to help make your experience more productive and fun.
