### ISSUE TITLE
Negative exp makes the EXP bar look full

### ISSUE THREAD

**Issue by Pichu0102** [HabitRPG/habitica#3886]
As a bit of extra incentive to not die at level 1 which is a slap on the wrist, I decided to drop my exp into the negatives if I die at level 1 manually. The game doesn't seem to understand this correctly. Expected behavior was an empty EXP bar until out of negative EXP.

![screenshot 1290](https://cloud.githubusercontent.com/assets/4944941/3951972/58b9784a-26dd-11e4-914a-0fc9851c2755.png)

**Comment by sbreiler** [comment]
It could be fixed by editing the percent-function in
habitrpg-shared / script / index.coffee (Line: 202)

``` javascript
roundFn(x/y*100)
```

to

``` javascript
Math.max(0,roundFn(x/y*100))
```

(If this behavior should be applied to all situations - or maybe put it as default which can be overwritten with optional argument)

**Comment by Alys** [comment]
That seems to me like a very neat fix for this and all similar potential issues, although I'm very much not the person who would have the final say. :) 

As far as I can tell, that percent function is used in only views/options/social/boss.jade and views/shared/header/header.jade (a few places in each) and I can't see any reason why this change would break anything. @breiste Do you have a local install of HabitRPG? If so, I think it's worth giving this a try, although note that I personally can't guarantee that the fix would be accepted. 

For easy reference to the code: https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L202

**Comment by sbreiler** [comment]
I don't have a local installation. I'm totaly new to the habitrpg source (also github), but i'm pretty shure this fix would work (the function seems to be for UI only). Someone with insight to the code should revise it and could submit it.

**Comment by Alys** [comment]
No worries. I'll see if any of our relatively new programmers would like to try this, and if not I'll do it myself.

If you're interested in getting into programming for HabitRPG, there's some information at [Guidance for Blacksmiths](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths) and you can join the "Aspiring Coders" and/or "Aspiring Legends: HabitRPG Helpers" guilds.

**Comment by sbreiler** [comment]
I will check where the percent-function is used. Afterwards i can do a local test (i got a local copy working).

**Comment by sbreiler** [comment]
Shared.percent is used in the following files:
https://github.com/HabitRPG/habitrpg/blob/develop/views/options/social/boss.jade#L38
https://github.com/HabitRPG/habitrpg/blob/develop/views/options/social/boss.jade#L46
https://github.com/HabitRPG/habitrpg/blob/develop/views/options/social/boss.jade#L52
and
https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/header.jade#L13
https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/header.jade#L19

**Comment by sbreiler** [comment]
Tested it succesfull localy, see: https://github.com/HabitRPG/habitrpg-shared/pull/315

**Comment by Alys** [comment]
Fixed by https://github.com/HabitRPG/habitrpg-shared/pull/315  (fix will be on the live site in a few days).
