### ISSUE TITLE
Missing 4 or 5 old quest scrolls

### ISSUE THREAD

**Issue by AshtonSanders** [HabitRPG/habitica#3888]
Hi,

I started using HabitRPG right after the kickstarter release, but I took a break for a while. When I came back a couple months ago, I had 4 or 5 quest scrolls. I didn't really know what they did, so I ignored them. I'm in a party now, and we started doing quests. But it looks like all my old quest scrolls are gone. It's been a few weeks since I've seen them. =/ Maybe I wasn't supposed to have them?

I'm Ashton, and my UID is d979691a-3a0c-4410-92d1-b629726f61bf

Thank you for any help you can provide!
Ashton

**Comment by crookedneighbor** [comment]
@AshtonSanders Sorry it took so long for anyone to respond to you. 

The site has undergone a few revisions since the kickstarter release. @lemoness @veeeeeee @Alys Any idea what these quests would have been?

**Comment by Alys** [comment]
@AshtonSanders Your account shows that at one time you had these five quest scrolls and you do not have them now, however you do have achievements for all of these quests (meaning you have done them, either from your scrolls or someone else's):
- Trapper Santa
- Attack of the Mundane, Part 1: Dish Disaster!
- Egg Hunt
- The Golden Knight, Part 1: A Stern Talking-To"
- Vice, Part 3: Vice Awakens

None of those were from the Kickstarter days. I think Trapper Santa was given to everyone as the first quest ever, so I can give you a new copy of that if you want to do it again.

There have in the past been display issues that caused the number of scrolls owned to look like it was larger than it actually was.

Do you have any idea which scrolls you are missing? Is it any of those listed?

**Comment by lemoness** [comment]
Trapper Santa and Egg Hunt were both awarded to people en masse due to events. It's odd that they do not have Vice Part 1, since that should have been awarded at Level 30.

**Comment by lemoness** [comment]
EDIT: Unless, of course, you were just listing the scrolls they no longer have, not all of the ones that they received.Ignore the last part of my comment.

**Comment by AshtonSanders** [comment]
Thanks for all the responses guys. I had totally forgotten about it, and I have a bunch of quests now, so no worries. Thanks for looking into it.
