### ISSUE TITLE
A chrome bug

### ISSUE THREAD

**Issue by Militoarg** [HabitRPG/habitica#3890]
{"err":"/app/views/shared/profiles/achievements.jade:65\n    63|     h5(ng-show='profile.achievements.perfect/-div(ng-if='profile.achievements.ultimateGear || user._id == profile._id')\n\nperfects is not defined"}

this is what the chrome tab returns. Help please.

**Comment by Alys** [comment]
Did you do all of the reloading and clearing of cache that I wrote about? https://github.com/HabitRPG/habitrpg/issues/2760#issuecomment-52588658

**Comment by Militoarg** [comment]
i try it already, still not working, check this message returned from chrome: 

{"err":"/app/views/shared/profiles/achievements.jade:65\n    63|     h5(ng-show='profile.achievements.perfect/-div(ng-if='profile.achievements.ultimateGear || user._id == profile._id')\n\nperfects is not defined"}

**Comment by Militoarg** [comment]
I have the same message on firefox browser.

**Comment by lefnire** [comment]
UUID?

**Comment by Militoarg** [comment]
44c105aa-928f-43f0-bc79-4b2681317413

**Comment by lefnire** [comment]
Checked out the account, can't replicate with that user. Make _double_ sure your cache is clear and all that jazz. That error means the server can't render a jade file to HTML, which means all users would be experiencing the same error.

**Comment by Militoarg** [comment]
re load chrome, deleted all cache files, still getting the same message: 

{"err":"/app/views/shared/profiles/achievements.jade:65\n    63|     h5(ng-show='profile.achievements.perfect/-div(ng-if='profile.achievements.ultimateGear || user._id == profile._id')\n\nperfects is not defined"}

**Comment by Alys** [comment]
Does the website work for you in any browser on your PC/laptop or mobile device What version of Chrome are you using? What operating system including version are you using?

Does the Android app or iPhone app work for you, if you have a device to test them on?

**Comment by Militoarg** [comment]
It does  not work on chrome, internet explorer or firefox, I tried to reset the pc and deleted all cache files, even in firefox (I installed it from 0) I got the same error. 

Nevertheless I can load it on the iphone client (but can't use skills there, there is no access/control of skills) help please.

**Comment by eugebib** [comment]
Hi! I get the same error in chrome and an 500 internal server error in explorer. I already cleared the cache.

**Comment by Militoarg** [comment]
{"err":"/app/views/shared/profiles/achievements.jade:65\n    63|     h5(ng-show='profile.achievements.perfect/-div(ng-if='profile.achievements.ultimateGear || user._id == profile._id')\n\nperfects is not defined"} 

not a clue whats going on. A friend of mine test it on his pc and my account works perfectly. I tried again to delete all browser data, and it is still not working :S

**Comment by Militoarg** [comment]
The main problem here is I can not play habit on my pc. nevertheless in iphone client I can't feed pets, neither use skills, May be someone could help me on this task. Thank you.

**Comment by lefnire** [comment]
@Militoarg sorry man, I've tried loading up your account in every browser, looking for javascript errors in console, investigating the jade files to see what could be triggering if maybe a server or client variable is off. Everything looks a-ok :/ Dunno what to do

**Comment by eugebib** [comment]
@Militoarg, are you from Argentina? I'm from there. Could that be related?

**Comment by Militoarg** [comment]
I have recently update java console on my pc (yesterday) may be that is the issue, I am from Argentina (I don't think so, My friend is from argentina, too, no problem with his client).

**Comment by paglias** [comment]
@Militoarg which language do you use on your PC? Does your friend use the same as you? @lefnire the only thing that comes to my mind is the addition of Latin american Spanish but I tested it changing my computer settings and it worked correctly..

**Comment by Militoarg** [comment]
latin america spanish, I will try changing it

**Comment by paglias** [comment]
Yeah... It is a problem with a string in Latin america Spanish used
there... Someone probably used an invalid variable... @lefnire I can't do
anything about that so you can edit the string in
habitrpg-shared/locales/es_419 (don't know exactly which one) or remove
Latin american Spanish at all: revert my commit about that in habitrpg repo
(not habitrpg-shared)
Il 19/ago/2014 20:25 "Militoarg" notifications@github.com ha scritto:

**Comment by lemoness** [comment]
We've just received a comment about this on Social Media from a user who said his first language wasn't English - it might be Latin American Spanish, but I'm not sure. I directed him here.

**Comment by Militoarg** [comment]
I finally could load it, it is that, @paglias, the language, in latin america it is not working my client, thank you for this. I had to change my first language to english to being able to load my account. 

Thank you to everyone :)

**Comment by lefnire** [comment]
@paglias pushing now

**Comment by negue** [comment]
@Militoarg does the website still not working with the American Spanish language setting?

**Comment by paglias** [comment]
It works now
Il 11/ott/2014 21:27 "negue" notifications@github.com ha scritto:

**Comment by negue** [comment]
Alright I'll close this issue then.
