### ISSUE TITLE
Language overwritten as Simplified Chinese in Hong Kong and Taiwan

### ISSUE THREAD

**Issue by copylion** [HabitRPG/habitica#3891]
Hi everyone, this morning I was shocked to see that the language in Habitrpg was switched from English to Simplified Chinese without any option to switch back to English. I believe this is because my machine's system setting is Traditional Chinese but habitrpg has only one Simplified Chinese translation. Not sure was there any discussion for keeping only one Chinese version before so I choose to raise the issue up here instead.

Simplified Chinese is used in: China, Singapore, Malaysia
Traditional Chinese is used in: Hong Kong, Taiwan, Macau

In Hong Kong we use both Traditional Chinese and English (as Hong Kong was a British colony for over 150 years), but NOT Simplified Chinese. In Taiwan most people use Traditional Chinese only.

Characters in these two versions varies a lot, for example:
Simplified Chinese:
如果你一个人玩HabitRPG，你会发现如果你开始和他人合作，竞赛，负有责任感的时候会非常不一样。任何自我改善的程序最有效的部分就是责任感，还有什么比游戏更适合激发你的竞争意识和责任感呢？
Traditional Chinese:
如果你一個人玩HabitRPG，你會發現如果你開始和他人合作，競賽，負有責任感的時候會非常不一樣。任何自我改善的程序最有效的部份就是責任感，還有甚麼比遊戲更適合激發你的競爭意識和責任感呢？

Please see also: Chinese - Wikipedia
http://simple.wikipedia.org/wiki/Chinese

More precisely, wordings in China/Hong Kong/Taiwan are different too like Spanish in Spain and Argentina are different, but I think it would be much faster to create a Traditional Chinese version base on the current Simplified Chinese translations for now, providing that we can have two sets of translations.

I have translated some mobile games from English to Traditional Chinese before and working on some other collaborative translation projects too (Facebook-Hong Kong, Steam-Traditional Chinese), so I am happy to help if needed.

**Comment by Alys** [comment]
[Settings -> Site](https://habitrpg.com/#/options/settings/settings) has a Language drop-down box, and there's also one on the login page in the footer.

**Comment by Alys** [comment]
Also, if you'd like to help translate the site, see [Guidance for Linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists) on the wiki. I'm sure your help would be appreciated!

@paglias : Is there a way to prevent Simplified Chinese being used if the PC is set to Traditional Chinese?

**Comment by copylion** [comment]
@Alys Found it, thanks! Will take a look and see if I can start a new set of translation there ;)

**Comment by paglias** [comment]
@copylion sorry about that, will correct it when I get a chance, should be
done for the first week of september
Il 19/ago/2014 08:20 "copylion" notifications@github.com ha scritto:
