### ISSUE TITLE
Quest image missing in party for "Attack of the Mundane Questline, Pt. 1: Dish Disaster!" quest

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#3892]
I was not sure if this was intentional or not, but I noted that the wiki had the Dish Disaster quest image posted but this image did not appear in the quest sidebar in my party. Will there be an image for the Dish Disaster mini quest? Or are images only for boss fights and not collection quests?

**Comment by Alys** [comment]
Looks like the code does put in an image for only boss quests, however I'm pretty sure something can be done about that. :)  Let me play around for a bit.

**Comment by Alys** [comment]
Yup, easy fix. But I'm going to ask in the [Aspiring Coders guild](https://habitrpg.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f) to see if there's any beginner contributors who would like to do this.

**Comment by breadstrings** [comment]
@Alys - awesome! I really like the collection quest images from what I've seen on the wiki, and you're very considerate to give the easy coding to beginners. :)

**Comment by lefnire** [comment]
Y'all talking about the collection item (bar of soap)? If so, :+1: @Alys. If you're talking the boss image isn't showing up (the dirty dishes), then I should probably look into this yes?

**Comment by lemoness** [comment]
@lefnire @Alys There's no bar of soap item - just a pile of floating dirty dishes, which we intended to use as the image.

**Comment by Alys** [comment]
@lefnire : The "boss" image is not showing up, but it's a simple fix. The code for boss quests and the code for collection quests is slightly different, and the latter does not have the tag that inserts the image.  If I can't find a beginner contributor to fix it in the next couple of days, I'll fix it myself.

**Comment by lefnire** [comment]
kk
