### ISSUE TITLE
Lost Vice Quest Scroll

### ISSUE THREAD

**Issue by Bujungo** [HabitRPG/habitica#3895]
I finished the first part of the Vice quest and attempted to start the second but instead of starting the second part the scroll just disappeared and I was not in the quest.

**Comment by Alys** [comment]
First log out of HabitRPG, clear your browser's cache (make sure it is the cache that you clear, not just your browsing history), then log back in. Reload the party page to see if you are on the quest. If you are not, reload the inventory page to see if the quest scroll has reappeared in your inventory.

If that does not fix the problem, paste your User Id into this issue as plain text and tell us what happened when you tried to start the second quest (e.g., you clicked on the scroll, then what did you see, then what did you click on next, then what happened after that, etc). See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

**Comment by Bujungo** [comment]
Still no scroll.

when it happened I clicked on the scroll, the normal popup showed up, and when I clicked Invite Party, the popup disappeared. I clicked over to the party tab, and was not in the quest. I tried this a few more times and then tried leaving my (empty) party and recreating one. Then when I went back to the inventory page the scroll was gone and I was not in the quest.

userid: a54bd323-229a-4e84-bb6d-92d18e663510

**Comment by Alys** [comment]
Your vice2 scroll is back in your inventory now. You might need to reload and/or clear cache to see it. If the same issue happens again, try the logout/clear/reload steps listed above after the first time you try to use the scroll. Don't leave the party because if the invite has worked (but just hasn't shown up yet), leaving will abandon the quest. I'm closing this since you have the scroll back, but feel free to comment if you need more help.

**Comment by Bujungo** [comment]
I have the scroll, but now my Attack of the Mundane Questline Pt2 scroll is gone. I followed the steps above and still only have the vice2 scroll.

**Comment by Alys** [comment]
That's because you're currently on that quest. You have used that scroll. It can be used only once.

**Comment by Bujungo** [comment]
Oops, I didn't realize I had started that quest. Thanks for your help!
