### ISSUE TITLE
Dailies

### ISSUE THREAD

**Issue by jvitorm** [HabitRPG/habitica#3899]
My dailies don't reset. I try sync and sleep in Inn, but my dailies still being marks. What I can do?

**Comment by paglias** [comment]
If you are in the Inn your dailies will never reset unless you exit from the inn and wait for midnight or your custom cron hour

**Comment by lefnire** [comment]
see #1057

**Comment by jvitorm** [comment]
Before Write this post,  My cron hour was program to 5:00H, when i tried check and refresh my dailies with something i did today, in 07:00H, it ain't had reset. So i read FAQ and try sync, and change my Cron hour to Midnight like i read in tutorial. Util this moment no back. Perhaps my dailies back to work normal after  00:00h of 22th august ? 

Sorry! I'm do not write english well

**Comment by ghost** [comment]
My dailies have also suddenly stopped resetting. I have my cron set for 10am, but it has been like that for at least a month, and everything has been going well. I haven't made any other changes. I have been using the app, but even logging in to my account and using Sync has not made a difference. They should have reset yesterday, so I have given it another day, and they are still not reset (although I guess I should wait another few hours to see if they reset after 10am today).

**Comment by Alys** [comment]
@jvitorm and @SiberAngel : You are either [Resting in the Inn](http://habitrpg.wikia.com/wiki/Tavern) which is meant to stop your dailies resetting or you are experiencing the bug that lefnire linked to and which is described on the wiki's [Known Bugs page]([Known Bugs]%28http://habitrpg.wikia.com/wiki/Known_Bugs#Dailies_Remain_Checked_after_Cron%29) in the section titled "Dailies Remain Checked after Cron". You'll find a workaround there.

When you log issues in GitHub, please always include your [User ID](https://habitrpg.com/#/options/settings/api). That lets us look at non-private data from your account and often helps us work out exactly what is wrong.

**Comment by jvitorm** [comment]
Well i will wait midnight to try again. And never Will use inn option any more.

**Comment by ghost** [comment]
Mine have reset today. I was definitely NOT in the Inn. Strange how it tweaked for a day only. Looks like my streaks were unaffected, hooray!

**Comment by jvitorm** [comment]
So is 05:00h and my dailies are the same of 2 days ago. I don't use inn and my cron hour, are set on 00:00h. What a can i do?

**Comment by Alys** [comment]
See my comment above - we need your User ID to help us work out what's wrong.

**Comment by jvitorm** [comment]
This my id Jvitorm

**Comment by Alys** [comment]
No, your User ID from the page I linked to above. This page: https://habitrpg.com/#/options/settings/api

**Comment by jvitorm** [comment]
33fbd749-0e39-4b31-90a1-81a8020ad636

**Comment by Alys** [comment]
Thank you. From that I can confirm that you are no longer resting in the inn, which is good since you want your dailies to reset. However your Custom Day Start is not 00:00, it's 23:00, although that shouldn't make much difference. You are probably suffering from the bug I described above. Go to the wiki's [Known Bugs](http://habitrpg.wikia.com/wiki/Known_Bugs) page and look for the section called  "Dailies Remain Checked after Cron". It describes a work-around that you can use. Note however that your dailies will probably fix themselves up within 24 hours.

**Comment by jvitorm** [comment]
Thanks. Now my dailies are reset.
