### ISSUE TITLE
Incremental/Progression Tasks

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#39]
_Edited by wc8: Vote for this feature here: [Trello](https://trello.com/c/Cld8EjME)_

Would it be possible to develop functionality for Incremental/Progression Tasks?

Hopefully you can come up with a better name for the concept but here is the idea.

Basically some tasks/goals are completed in increments. These could have small calculated rewards for progress made and a greater reward for completing the overall task/goal.

2 examples are;
- Saving up a specified amount of money.
- Lose a specified amount of weight.

You could receive a small reward proportionate to the progress made to the overall goal. For the money saving goal you could have an algorithm that calculate a "progress" reward for each sum you put away. For the weight loss goal you would enter in the amount of you want to lose then gain proportionate progress rewards for losing weight  or lose health for gaining weight. Additionally you would lose health for not entering any progress updates (positive or negative) for either of the goals within a certain time frame. With this last function there would need to be some in app notification to tell you why you lost the HP.

**Comment by lefnire** [comment]
I love it! I originally had a similar idea called "Goals" using Tags.
Anything with the same tag can be filtered, and percentages shown for tag
completion. The last item left in a tag is a Boss, and gives you way more
exp/gp.

I think I'll be mulling around combining my idea with everything you said.
It won't come for quite some time, there are critical issues to bang out
first, but definitely in the plan.

**Comment by Nelmalih0** [comment]
What if, instead of calling it goals, you called it Quests, to keep the RPG theme going

**Comment by horusofoz** [comment]
Quests sounds good though it's possible me made need some sort of prefix as I think there will probably be a few things termed quests when the RPG theme starts to get fleshed out. Post bug hunt.

**Comment by wc8** [comment]
Or use "buildings" or locations and level up the building/location as it progresses.
Landmark > Village > Town > City 
Hovel > Straw House > Wood H. > Brick H. > Manor > Castle
There could be bosses to overcome in each location.

P.S. There could still be special buildings, like "Tavern" #153 and perhaps a specially named shop for #181 
Maybe a Hospital that allows you to rest from all habits not tagged health.

**Comment by wc8** [comment]
[Trello 43 Tags and Categories](https://trello.com/c/q7v02jAw)

**Comment by horusofoz** [comment]
Request has been added to Trello. Closing ticket. If required can be re-opened down the track.
