### ISSUE TITLE
Missing capital letters

### ISSUE THREAD

**Issue by allinblack24** [HabitRPG/habitica#3902]
I have attached a screen shot. After a number of hours of play the capital letters disappeared. closing the browser and reopening the page does not fix the problem. Currently using Firefox.

![habit rpg bug](https://cloud.githubusercontent.com/assets/8517692/4003598/41c012d2-2978-11e4-8385-7397e0e130c9.JPG)

**Comment by Alys** [comment]
Might be related to https://github.com/HabitRPG/habitrpg/issues/3900 "Font rendered e's weirdly" (even though it's clearly different letters).

**Comment by negue** [comment]
Here on Windows 8.1, Firefox 31.0 this problem doesn't exist.

If you have a Windows Computer, check if you have cleartype active, if not please activate and check again.

**Comment by allinblack24** [comment]
All of last week this was a problem for my Firefox browser. I was using Chrome as a workaround. This week the text rendering is not a problem. I did not change any settings on my end. I am not sure what has changed between then and now.

Thank you for looking into it.

**Comment by Alys** [comment]
We believe this has been fixed so I'm closing this issue, however if anyone is still having problems, please say so here and I'll reopen it.
