### ISSUE TITLE
Erroneous Pet Count - Extra Pet

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3904]
My current pet count states 88/90; however, I still need 3 pets for completion (golden cactus, dragon, and tiger).  My userID is: fb8fca6f-ff99-43ea-bdbe-c1a22f82c0d6

Alys in the Tavern responded with the following comment:  

"You have an odd entry in your items.pets data (a pet called "5") which is probably what's causing the problem."

(any chance of a special unique pet for myself out of this?  I'm thinking an anthropomorphic number 5 ;P)

**Comment by ghost** [comment]
Now that I think about it, I remember noticing this some months back, when I had far fewer pets, so it's definitely not a new issue.  At the time, I assumed my Veteran Wolf rare pet was the extra pet, and that my total would end up being 91/90.

**Comment by Alys** [comment]
@lefnire : I think this needs direct database access to fix. Over to you to either delete items.pets.5 or create a rare pet image for it. ;)  But if you want to do this with a migration script, tell me and I'll write it, to save your time!

**Comment by ghost** [comment]
Rare pet image, eh? Like, a little sloth, or something? https://copy.com/DJANRObxP48ubUrp

**Comment by lefnire** [comment]
Ran `db.users.update({_id:'fb8fca6f-ff99-43ea-bdbe-c1a22f82c0d6'},{$unset:{'items.pets.5':1}})`, should be removed now. Alas, don't think we'll create a rare pet for this one

**Comment by ghost** [comment]
Alas indeed :D Well, thanks for fixing it!

**Comment by Alys** [comment]
@lefnire A bunch of other users have the same problem (an erroneous pet called "5" which makes the count of pets incorrect). I've run this command over a local test copy of the database to fix it for all users:
`db.users.update( {'items.pets.5':{$exists:true} }, { $unset: { 'items.pets.5': 1 } }, {'multi':true})`
Result:
`WriteResult({ "nMatched" : 46502, "nUpserted" : 0, "nModified" : 46502 })`

May I do the same on the production database?

**Comment by SabreCat** [comment]
Wow, 46.5k affected. I wonder where these came from!

**Comment by Alys** [comment]
I'm assuming old code or a temporarily-broken migration script. I'm not planning to hunt through the code to find out. What I am going to do (if lefnire lets me run that command) is after that wait a day, check for new "5" pets, then wait a week and check again, then a month and check again. If there's no new occurrences, I'll assume the code doesn't exist any more.

**Comment by Alys** [comment]
No extra "5" pets have appeared. I'm declaring this fixed for all players.
