### ISSUE TITLE
Connect authentication (tie Facebook to Local on one account)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3909]
This is embarrassing, we've had this conversation since day one (_so_ may times) - but I can't find any open tickets or Trello cards for the request. If anyone knows where it's at, fell free to dupe/close this (and let's make sure one is open).

Anyway, the request: allow a single account to have multiple authentication strategies. Aka, you can connect Facebook to your uname/pass-auth'd account, or add a uname/pass to your Facebook-auth'd account. Paves the way to adding Google auth, et al.
##

**Comment by paglias** [comment]
Now that we get emails from new FB signups we just have to check if the email is already there and merge the new info instead of creating a new user, I think

**Comment by lefnire** [comment]
True! Though we still may wanna add the other direction (plus UI to support this feature)

**Comment by paglias** [comment]
Okay! If anyone doesn't do it before, I'll implement the first part when I
come back. For the other direction: we should use popups probably to avoid
redirects hard to manage, give a look at a library called satellizer here
on github, seems perfect but it isn't passport js....)
Il 24/ago/2014 00:22 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by Alys** [comment]
Current situation is that if you sign up with Facebook, you can then add email, username, and password. You can't do the opposite.

I like paglias's idea of checking the email address of a new Facebook signup and merging it with an existing account, but I think it should be optional - the user is told that email address has an account and can choose whether to merge or create a new one. You might want to use both Facebook and email for different accounts, such as for home and work use (and you might not want to use your official work email address for your work account; I don't for mine).

**Comment by paglias** [comment]
One thing to consider is that many times when I login to a service after a long time I don't remember if I originally used email&pass or a social auth method and it's nice to be able to continue with the old account even when I chose the wrong auth method.

We can make it optional.

BUT we have to consider a thing: we don't validate email addresses so if I sign up with not-my-name@gmail.com and then someone login with a FB account linked to not-my-name@gmail.com (FB verifies email addresses) they'll be able to access someone's else account

**Comment by Alys** [comment]
Good point about accessing someone else's account. I see enough cases of people using the wrong email address that it does have a small risk of occuring. The privacy consequences are large so I suggest we don't do this until after we have email verification.

**Comment by librarianmage** [comment]
Doesn't this work now? I have a normal account that is can also be signed in with my Google account.

**Comment by paglias** [comment]
It only works one way

**Comment by Alys** [comment]
There is code for connecting accounts both ways. It's a bit buggy at the moment, especially for google login, but we have that recorded in bug reports elsewhere so I'm closing this.
