### ISSUE TITLE
suggestion - edit text on game rewards

### ISSUE THREAD

**Issue by Bquilt** [HabitRPG/habitica#391]
I'm not a gamer and am using habitrpg just for the convenience and tracking features.  So far it's great and once I can do a better job of assigning dates and different values to my todos it will be even better! 

Anyway, since I'm not a gamer, the enhancements and use of my $$ to buys swords and such are a bit meaningless to me.  I'd much rather spend my rewards on my stuff, but realize at some point I'll need the benefit of swords, helmets etc.  It would be nice if I could edit the text of the sword to say "Sword and cake" or something so that I get my sword and cake!  Not that I could change the value of the sword, just that I could get some more tangible awards (to me) also.

(ps - was thrilled to see the Kickstarter goal reached!)

**Comment by horusofoz** [comment]
HabitRPG will continue to utilise the built-in rewards in addition to custom. If possible we may review this again in the future. An alternative my be if you buy ALL the items they will no longer appear ;)
