### ISSUE TITLE
Anyone else getting this application error?

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#3910]
![screen shot 2014-08-23 at 11 19 47 pm](https://cloud.githubusercontent.com/assets/2916945/4022576/87457db8-2b46-11e4-94ba-aa1861090cd0.png)

**Comment by Artemisblack37** [comment]
I am

**Comment by pepperpanda** [comment]
I'm getting this one, instead of XP and Gold notifications, when I try to do tasks:

![error](https://cloud.githubusercontent.com/assets/4915522/4022679/869ccdf8-2b50-11e4-9f3a-9e4d626b8549.jpg)

But I guess they're the same.

**Comment by crookedneighbor** [comment]
Seems to be back up now.
