### ISSUE TITLE
Not gaining exp from tasks completed via API

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#3914]
When I update a task and mark it as completed via the API, I'm not getting any experience. Is this the expected outcome?

This occurs when I use the demo web interface for the API as well: https://habitrpg.com/static/api#!/user/user_tasks_id_PUT

**Comment by Alys** [comment]
I believe that API call is designed for editing tasks, and while you can edit the completion status, it's not exactly the same thing as marking the task completed.

What you want to use is POST /user/tasks/{id}/{direction} where {direction} is up for completing a task and down for uncompleting. If I recall correctly, it works on todos, dailies, habits, and rewards.

**Comment by crookedneighbor** [comment]
Ahh, I didn't realize that. I thought it was just for habits. That's awesome, thanks for clarifying!
