### ISSUE TITLE
Item Vanished

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3917]
**User ID:** 02b2728d-700f-4e74-a702-68dc06fb93f2

I died (bear with me), and it broke my rainbow warrior armor. Upon reloading the tasks page, I saw the rainbow warrior armor appear as a price 0 item under rewards. I clicked it, and the swashbuckler bandana promptly vanished from my costume. Checking my inventory, I saw that, indeed, my swashbuckler bandana had disappeared entirely. If this is a feature to prevent consequence-free deaths, then it should probably have an accompanying message to make that clear. If it is not a feature, then it should be investigated as a bug (and it would be nice if I could have that bandana back).

**Comment by Alys** [comment]
It's a bug and has already been reported here: https://github.com/HabitRPG/habitrpg/issues/2789

Any equipment lost on death can always be purchased again although if you're no longer in the correct class for that piece, you will need to change class to get it.
