### ISSUE TITLE
Minor button width problem

### ISSUE THREAD

**Issue by sbreiler** [HabitRPG/habitica#3918]
If you visit the frontpage at https://habitrpg.com/static/front using another language than english (in my case german) the Play-Button below the tagline is too small for the caption. **EDIT:** the problem only occurs in Deutsch :grin:

There is a style setting which puts a fixed width of 100px on this button:
https://github.com/HabitRPG/habitrpg/blob/develop/public/css/static.styl#L33

I don't think this is useful - at least a min-width would be better.

**Comment by negue** [comment]
+1, "min-width" instead of "width" is the solution

Screenshot:
![spielen_button_zukurz](https://cloud.githubusercontent.com/assets/842273/4035096/6a76775a-2c8b-11e4-8afb-e89035679d0f.PNG)

**Comment by Gaelan** [comment]
Close?
