### ISSUE TITLE
Task action icons getting unwieldy

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3921]
The one-click task actions are getting pretty outa-hand:

![screen](http://i.gyazo.com/dbb73884629278a6cc256c41c87c6a42.png)

That might be missing some too (challenge bullhorn?). We should start cutting back, does anyone have any recommendations? My own thoughts:
- remove checklist x/x count (pretty useless IMO)
- remove delete button, they can do that from edit screen
- maybe move the graphs button to inside the edit screen, as a tab or something?
##

**Comment by lemoness** [comment]
I actually like the checklist x/x count because I keep most of my
checklists collapsed.

Do we need the tag icon?

Would love to hear from @bnmnley.

**Comment by sbreiler** [comment]
I like to show as less interactive icons as possible, especially if they are repetitive all over the place. One way would be to hide all icons until you hover over the task (except the checklist and streak counter i guess).

**Comment by wysawyg** [comment]
There's also due dates which can take up a fair bit of space!

**Comment by Alys** [comment]
I like the checklist x/x count too, for the same reasons as lemoness. I use the tag icon very often to make sure the correct tags are used (especially for my "today" tag). I will use the new Push To Top icon CONSTANTLY so please leave that one there! :)

I suspect that for each icon, we'll find roughly the same number of players who can't live without it. :)

I like @breiste's idea of hiding the icons until you hover over the task.

**Comment by lemoness** [comment]
Hm, I worry that hover might be too hard for some users to find. What about
something to expand/collapse the icons, so people could choose whether or
not to have them displayed?

**Comment by lemoness** [comment]
Honestly, my biggest concern is that everyone know that these icons are
here - we're not the best with transparent features, frankly, so even if it
looks more streamlined, if we're hiding functions, we'll get more confused
users.

**Comment by lefnire** [comment]
not so certain. hover-to-show for action buttons is quite common on website (trello, pivotal tracker, asana, etc). I could get down with that - we'd want to decide which buttons are always visible, which are hover-to-show. 
- Definite hover-only candidates IMO: edit, trash, graph
- Possible hover: push-to-top, challenge-bullhorn
- Likely always-show: streak, checklist-counter, tag, comment-bubble, due date

thoughts?

**Comment by Alys** [comment]
How about:
- Always-show anything that helps to identify/classify the task: challenge-bullhorn, streak, checklist-counter, tag, comment-bubble, due date
- Hover-only anything that modifies/works on a specific task once you've found it: edit, trash, graph, push-to-top

@lemoness is right about confused users though. Maybe the always-show icons could end with "..." to indicate that there's more available? Although that's extra clutter too. If we did go with something to expand/collapse the icons, that could be it.

**Comment by lemoness** [comment]
Edit should be always-show, IMO. I think graph should be hover, if that's
what we're going for. Could we see some mock-ups, though?

**Comment by lefnire** [comment]
@Alys I like the `...` idea! @lemoness hover-:pencil2: is pretty common-place. Play around with a few sites (eg Trello) to see it in action. If it confuses users, it'd be because they're used to our old setup, IMO. Not that I'm against always-visible :pencil2:, just food-for-thought on common web UX

**Comment by lemoness** [comment]
Hm, okay, I'm outvoted! I do like the ... idea.

**Comment by sbreiler** [comment]
There is indeed one drawback i know of using this method: phones and tablets can't use hover items (is it required?). As lefnire says, it's quite common to use this and i think it fits this kind (playful) of website/app.

I've created a simple showcase video: http://youtu.be/lCIQLXTbLcM

_EDIT:_ I didn't understood the meaning of "..." you mentioned - therefore my showcase is useless

**Comment by Gaelan** [comment]
Just sent a PR for hover-to-show before seeing this post: #3923

**Comment by Gaelan** [comment]
I don't think users not finding hover buttons is a problem (at least on desktop) since they will need to hover to check a task off. :)

**Comment by sbreiler** [comment]
@Gaelan did you check that the task height doesn't jump on ~1100px window width while hovering over? I did a

```
position: absolute;
top: 0;
right: 0;
```

 on .task-meta-controls to prevent this.

**Comment by lemoness** [comment]
I like the loom of the hovering, but if we go through with this and it's
true that users accessing the site on mobile devices can't use hover, then
editing can't be hover-only, or it will break a basic functionality for
that group of users :/

**Comment by Alys** [comment]
The "..." icon could be a touch-point for unhiding the other icons (in addition to on-hover unhiding them).

**Comment by lefnire** [comment]
hmm.. mobile, yeah that'll pose an issue. They can still double-tap on tasks, but that's not intuitive. We could also do `ng-if="!env.IS_MOBILE"` (probably the simplest solution)

**Comment by veeeeeee** [comment]
On mobile, the Pinterest version of the hover is a long hold, which pops up your options.

ETA: Long hold, then swipe towards whatever icon you're aiming for.

**Comment by lemoness** [comment]
Is that for the Pinterest mobile app, or for users accessing the site on
mobile?

**Comment by AnitaYCheng** [comment]
Will return with more to say once i read through the thread carefully, but I would like to note that I did an impromptu user test with a friend of mine who saw my HabitRPG screen and signed up right then (I'm a UXer and she's a more experienced UXer) and she just plain ignored the block of tiny icons when she was on the task page the first time. And it was when the block was smaller! 

One interesting thing she did was that she clicked the "minus" button on the sample habit, when her intent was to delete it. My thinking is that the icons are too small, and yes, there are now waaay too many of them. Power users are perfectly fine with this, I'm sure, but I expect it to be a big problem when onboarding.

On mobile, Facebook options pop up when you do a long hold as well. On the Pocket app, there is a row of icon options when you swipe an article title left, when it is hover-only on desktop.

**Comment by veeeeeee** [comment]
@lemoness Pinterest mobile app.

**Comment by AnitaYCheng** [comment]
@lemoness, I'm not a power user myself, so I'm really interested in how a power user handles the task page. Want to do a user test sometime? :) @veeeeeee says we can do Korean BBQ!

**Comment by lemoness** [comment]
@anita Would love to! That would be pretty cool from my perspective. :)

I'm heading off to PAX first thing tomorrow, but I'll be back on 9/4 -
shoot me an email (leslie@habitrpg.com) and we'll talk logistics.

**Comment by ghost** [comment]
Please don't make it appear on hover. I use a tablet almost exclusively for HabitRPG and there are enough things that require multiple taps because of hover (feeding pets, for example, is tedious requiring a minimum of 4 taps for each piece of food fed). Also, the description bubbles for tasks are hover-only so they already pop up when you don't press a specific icon (and then refuse to go away, preventing me from being able to see or access the task covered by the bubble).

At least make it an option to keep the icons in the site settings.

**Comment by lefnire** [comment]
@Anysia et al, we can disable this behavior on mobile / tablet with `ng-if="!env.IS_MOBILE"`. This is just for desktop

**Comment by Alys** [comment]
In [Small alignment issue for task text - Issue #4694](https://github.com/HabitRPG/habitrpg/issues/4694#issuecomment-74579894), richcocoa suggests moving the icons to the bottom:

```
 ---------
|Text     |
|Text     |
|    * * *|
 ---------
```

**Comment by lemoness** [comment]
So, which icons will not be hidden until hover? I'd want streaks, edit and delete to stay always-visible.

**Comment by Alys** [comment]
### Suggested Show-Always versus Show-on-Hover/Submenu Lists

Any admins can edit these lists as desired.

Always shown:
- streaks
- tag icon
- checklist count
- due date
- challenge-bullhorn
- edit
- delete
- note?

Show on hover or in submenu:
- progress graph
- push to top
- push to bottom (doesn't exist yet, but could when we have space for it)

My thoughts are: Always-show anything that helps to identify/classify the task. Show-on-hover/submenu anything that modifies/works on a specific task once you've found it (with possible exceptions for the very common modification tools).

If we use richcocoa's idea of putting the icons under the text, it gives us a bit more room for always-show icons.

PR related to this: https://github.com/HabitRPG/habitrpg/pull/3923

**Comment by crookedneighbor** [comment]
That should say "Show on hover" not "Hide on hover", right?

**Comment by Alys** [comment]
@crookedneighbor I have no idea what you are talking about. `cough` :)

**Comment by crookedneighbor** [comment]
Seems to me like we have so many non-negotiables for always being shown, that it doesn't make sense to show 1-2 more on hover. 

Here's a mock up of what it would look like to put the icons on the bottom ~~left~~ right (not floating):

![screen shot 2015-02-16 at 4 28 57 pm](https://cloud.githubusercontent.com/assets/2916945/6220228/82bdd11c-b5f9-11e4-95e1-4a3e3522c5a0.png)

Biggest qualm is that it increases the height of every task to do it this way.

**Comment by Alys** [comment]
If we did have a hover/submenu thing, it would give us space for more icons in future (push to bottom, clone task).

I really like how that mock up looks, compared to the [clutter and wrapping on my tasks now](http://i.gyazo.com/ca1fb3f05039615ee298bdd33b9561db.png). The extra height would be worth it, for me.

**Comment by Alys** [comment]
@crookedneighbor I really like how that mock up looks, compared to the [clutter and wrapping on my tasks now](http://i.gyazo.com/ca1fb3f05039615ee298bdd33b9561db.png). The extra height would be worth it, for me.

**Comment by ghost** [comment]
What about we move the mini icons to the bottom right, keep them hidden, and slide them out on hover. So there won't be an increase in height for the tasks, and you get space for additions too. But there is the issue of discovering them, for both new users and those accustomed to the old layout.

**Comment by lemoness** [comment]
I really, really do not want all of the icons to be permanently hidden,
especially edit and delete. I think that will lead to significant user
confusion. Having streaks constantly displayed is also very motivating to a
lot of people.

Pinging @anitaycheng and @benmanley

**Comment by Alys** [comment]
Actually, yes, very good point about delete. We already get a lot of new users asking how to delete tasks. I've removed the question mark from that in my list above.

**Comment by deilann** [comment]
Streaks are so motivating for me that when I was primarily using the mobile
app (which does not display streaks) I had very little incentive to
regularly complete dailies.

**Comment by AnitaYCheng** [comment]
What I mostly got from this is, I should add "streaks" to the user survey! I actually don't look at them at all, personally - I check off things mostly not to lose health!

I really like @crookedneighbor's mockup of showing the icons on the bottom instead of squeezed on the top displacing the title. That's also more in line with what other apps do, such as Twitter and Pocket. Twitter on iPad's Safari browser is "tap to access tasks," (Pocket on iPad app is "swipe to access tasks" which is same thing pretty much) which makes sense since they want you to read down your feed. Pocket on desktop has "hover to show tasks" but things don't move around. It just makes things look cleaner. Twitter on desktop has all of the tasks visible on desktop all the time.

And people hover all the time on desktop, that I don't think we should worry about them "not finding" the tasks, if they were hover-only.

There is also a balance about first priority vs other priorities, which we could learn from Twitter. Of course Twitter wants you to engage with your feed (retweet, reply, favorite), but first you have to be able to read it. That's they hide tasks on smaller screens until you tap on the tweet you want to engage with. So in this case, I would be more in favor of hiding tasks (or at least not making it equal with the title) so each to-do is extremely readable.

**Comment by AnitaYCheng** [comment]
Actually, I'm wondering if there's a technical limitation for Twitter on mobile Safari, since the Twitter mobile apps (iPad and iPhone) have the tasks visible all the time. 

At any rate, we should determine what are the 3-5 things that users should be able to do immediately. And then stick them to the bottom of the to-dos. :smile: At least they wouldn't be so squeezed AND displace the title that way.

Due dates should stay on top, since it's not consistent across all tasks. It's more in line with "title" than an action task.

**Comment by sbreiler** [comment]
First of all, i like the icons below the text.

Maybe it's worth to think about splitting up the interactive "buttons" (edit, delete, ...) and the informational icons (streaks, checklist count, ...). Just a quick mockup how it could be done:

![mockup_task](https://cloud.githubusercontent.com/assets/5873569/6226486/f4d84830-b695-11e4-9e22-39bea94761a2.png)

**Comment by lemoness** [comment]
I kinda like that, actually!

**Comment by Alys** [comment]
I do too, although I think that probably the tag icon and definitely the challenge icon count as informational. How does this look when the task title is several words long? And with several tasks in a row when there aren't any checklists - does it make the page look too dark?

**Comment by moshner** [comment]
I would like to add that the icons are too small to comfortably tap. [44px](http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAA&url=http%3A%2F%2Fwww.smashingmagazine.com%2F2012%2F02%2F21%2Ffinger-friendly-design-ideal-mobile-touchscreen-target-sizes%2F&ei=qwj6VI2_OoaXNuG2hMAO&usg=AFQjCNFqq5q8XX8_VZ9qYWIQB9ngp6ncqg&sig2=g9AgY5QAdZO2gz5umOsZKw&bvm=bv.87611401,d.eXY) is the smallest I would go on a button. This is regardless of mobile or desktop. More and more people are getting touch interfaces on large screens. If you want your application to be usable across even those screens, it should be designed with touch as the primary interaction in all cases.

Some extra consideration needs to be given to the most important tasks and pieces of information. I saw in this thread that Trello was repeatedly mentioned. The biggest difference in Trello's interface is simplicity. They show a very small, select number of features as icons and require the user to tap for more. 

*_I recommend doing a user study to determine what the most needed icons are, focus on designing to make those usable on all devices and screen sizes, and THEN come up with a better way to access the other icons, etc.. *_

Some interface ideas, while I'm here:
Purely informational items like streaks could be designed into the interface more elegantly to reduce the visual clutter. E.g. There could be a large number in the background of the tasks to show the streak. The tags could be color coded like Trello. Challenge items could have a different colored border. 

![habittaskidea_3_6_2015 3_02_05 pm](https://cloud.githubusercontent.com/assets/3300206/6536320/3eaae65a-c412-11e4-9e5d-a61ea1725ce6.jpg)

Then when a user goes into edit or view a task we don't use enough of the available screen space. By keeping the task inside that little column we are limiting what we can do with these other screens. If we borrowed, again from Trello, the concept of a card opening as a modal we would have a LOT more space to work with on desktop and reduce scrolling as well.

**Comment by Alys** [comment]
@lemoness @AnitaYCheng Do you have any comments about @moshner's idea above?

**Comment by AnitaYCheng** [comment]
Sounds really good! An edit modal would allow much more room to work with, and emulate the native experience more as well, when the user is forced to go to another screen to edit. 

A lot of these considerations would require overhaul of the UI, so we'd need to determine what kind of priority this has.

**Comment by librarianmage** [comment]
@Alys was there any consensus on this?

**Comment by Alys** [comment]
No but let's talk about it after API v3 is released when we'll have more time. There's plans for a UI overhaul which will tie in to this.

**Comment by khipkin** [comment]
I really like the idea of splitting up the informational vs actionable icons.

**Comment by librarianmage** [comment]
@Alys should we still wait on this for the UI overhaul?

**Comment by Alys** [comment]
@MathWhiz Definitely, thank you!

There's some ideas here though that we might want to keep considering for the redesign so I'll copy this issue's URL to our internal docs.

**Comment by khipkin** [comment]
@Alys If this issue will be addressed in the redesign, why close it instead of leaving it open with a [wait] label?  Don't mean to be rude; I want to understand the workflow because it seems inconsistent with how this sort of situation has been handled in the past.

**Comment by librarianmage** [comment]
@khipkin I think @Alys closed this because it will be handled by the UI
update (she copied the issue link for reference), and isn't something that
needs to wait until after it.

**Comment by khipkin** [comment]
Ohh I see the distinction now.  That makes sense! Thanks, @MathWhiz!
