### ISSUE TITLE
"To and from are required" error

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3926]
If you drag-drop a task without changing its position in the list (something I often do by accident), a notification appears with the following text:

`"?to=__&from=__ are required"`

Sounds like it's passing in nulls to the list ordering function, which then gets confused as to what it's supposed to be doing with the task you dragged.

**Comment by SabreCat** [comment]
This also happens with tag reordering.

**Comment by lefnire** [comment]
Verified. [This](https://gist.github.com/lefnire/92c73abef1e341cb3615) should fix the issue, but it's not for some reason. Gotta break away for a bit if someone wants to take a peak at it for me?

**Comment by lefnire** [comment]
Hacky front-end fix https://gist.github.com/lefnire/52681718a5a63f5e91c5 (hacky because this doesn't solve it for other API consumers, so above method is preferred).

**Comment by DaggerPen** [comment]
I have also been getting this error when attempting to check off or edit tasks. I have to hammer an option repeatedly for it to work.

**Comment by Alys** [comment]
@DaggerPen : I suspect that you're getting it because when you do your tick/edit action, your mouse is actually jiggling the task a bit (so you're seeing what SabreCat describes above as "drag-drop a task without changing its position"). I've seen comments before about old or faulty mice causing glitches in HabitRPG.

**Comment by DaggerPen** [comment]
@Alys You're right, that was it. I mostly use my drawing tablet as a mouse, which tends to result in kind of shaky clicks - clicking with my touchpad resolved the issue. Thanks.

**Comment by lefnire** [comment]
Fixed in 4ba860e (will go out later). Turns out the new angular-ui-sortable directive lacks a to/from attr when sorting in place, so the server is acting just fine - it's the client that needs to prevent sending the op if `!from || !to`
