### ISSUE TITLE
August Mystery Item is mislabelled

### ISSUE THREAD

**Issue by hannsolo** [HabitRPG/habitica#3927]
The sun crown and sun robes are associated with each other's images.
![image](https://cloud.githubusercontent.com/assets/8177760/4045798/16f82a2c-2d2d-11e4-8f97-66bd650c8b92.png)

**Comment by rolandgridley** [comment]
Ah, beat me to it by two hours. I created an account for this one. I can confirm, if that counts for anything =)

![augusthabit](https://cloud.githubusercontent.com/assets/8558820/4047363/b6692802-2d39-11e4-99ce-55c6553c629a.jpg)

**Comment by Alys** [comment]
Already fixed but it might be couple of days before the fix appears on the live site. https://github.com/HabitRPG/habitrpg-shared/pull/286

**Comment by lefnire** [comment]
live
