### ISSUE TITLE
Android app a little forgetful of equipment

### ISSUE THREAD

**Issue by Pichu0102** [HabitRPG/habitica#3928]
Hello. For some reason, HabitRPG on Android is behaving strangely. It shows the wrong costume, and doesn't remember my combat gear exists, despite displaying it. My device is an HTC One m7, Verizon edition, and HabitRPG is v0.0.35, the latest on the Google Play store. 
Attaching screenshots in one moment. 

Edit: attached
![august 26 2014 at 0128pm](https://cloud.githubusercontent.com/assets/4944941/4048779/fee417ec-2d46-11e4-90d6-1f2dac1af75a.png)
![august 26 2014 at 0128pm 1](https://cloud.githubusercontent.com/assets/4944941/4048783/079857ea-2d47-11e4-8ee9-89c75c63632a.png)

**Comment by Alys** [comment]
@Pichu0102 What is your User ID and what costume are you meant to be wearing?

See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

**Comment by Pichu0102** [comment]
UID is 0d91f7d6-588d-4d54-822f-8bf8c4b2141c

And the outfit I was wearing was this:
![screenshot 1306](https://cloud.githubusercontent.com/assets/4944941/4051546/81f46f18-2d62-11e4-8ddc-129d00b03686.png)
![screenshot 1307](https://cloud.githubusercontent.com/assets/4944941/4051547/8201a0c0-2d62-11e4-9b24-50dc6825667c.png)

**Comment by Alys** [comment]
Okay, so the outfit is all correct except for the headgear which is a new item, released yesterday.

The mobile apps often lag behind the website a little. When new gear is released, it could be a few hours or a day or two before it appears on the apps, and in the meantime if you're wearing that gear it will look as if you aren't wearing anything.

At least part of the reason for the delay is that the app stores need to approve new app versions before they become available.

**Comment by Pichu0102** [comment]
Well, the app also is missing all my gear except the underwater suit in my inventory.

**Comment by Alys** [comment]
Please include screenshots that show that extra problem. At the moment all we can see is that your avatar isn't wearing the headgear.

**Comment by Pichu0102** [comment]
Ah, right. Here you go.

Edit: Github doesn't like image attachments from email. Here we go.
Edit 2: I have no idea why Github didn't inline them.

![august 26 2014 at 0551pm 1](https://cloud.githubusercontent.com/assets/4944941/4052404/494b92c8-2d6b-11e4-8e6a-18685a6a1e8e.png)
![august 26 2014 at 0551pm](https://cloud.githubusercontent.com/assets/4944941/4052403/4946fe8e-2d6b-11e4-9029-0d692e65930b.png)

**Comment by Alys** [comment]
GitHub probably didn't inline them because they're huge.

I've moved the issue to here: https://github.com/HabitRPG/habitrpg-mobile/issues/268
You can click on the Notifications button in the right-hand column to receive email updates (I strongly recommend you do this in case the mobile devs have questions for you).

**Comment by Alys** [comment]
@Pichu0102 : Could you please tell us if you are still unable to see most of your equipment on the mobile app? For a while there, I was having the same problem as you, but now I'm able to see all of my gear.
