### ISSUE TITLE
Have timed daily events

### ISSUE THREAD

**Issue by Wjdelt** [HabitRPG/habitica#393]
I'd like to see an option to set a time for a desired daily to occur (i.e. 5:30 pm "review mail"  ... 7:00 am empty cat litter.)  Habits, for me anyway, are better established if I know I have a specific time as well to do things.

**Comment by elssar** [comment]
You could name the task with the time, if you just need to have the time displayed, like so - 
- Review Mail 5pm
- Empty Cat litter 7am

**Comment by Wjdelt** [comment]
Thanks for your reply. I guess I'm thinking of the mobile app (when it's ready) to pop up a reminder at the designated time.  The mobile app will have more impact for me (& I imagine a lot of other people too) as I'm not always at my computer to make an entry or my entries would like to be put in right away (i.e. turned down snack at work).  I'm looking forward to see where this application goes.

**Comment by wc8** [comment]
Check out [Timed Notifications](https://trello.com/c/uC0MX8kg).

**Comment by Wjdelt** [comment]
Thank you for the link. Glad to know I'm not the only one who thought of that. Guess we'll just wait & see where the app takes us. ^_^
