### ISSUE TITLE
Gem to gold conversion not working with subscription purchase?

### ISSUE THREAD

**Issue by haemichoung** [HabitRPG/habitica#3931]
Hello!

I bought a subscription thinking I would be able to buy stuff with the gold I have but after two days, nothing seems to work. I tried buying something thinking my subscription will kick in but it is always preventing me from doing it, just like if my subscription didn't exist.

Is there a procedure regarding this? I know there was a cap per month and if that is the case, does it start at the beginning of a month?

**Comment by Alys** [comment]
What stuff are you trying to buy? When you are a subscriber, the only extra thing you can buy with gold is gems, from the Market -- see "Individual Subscription" in [Subscription](http://habitrpg.wikia.com/wiki/Subscription). You can then use gems to buy items that have a gem price listed on them. 

The gem cap resets at the beginning of the month so you should buy this month's allotment of gems in the next four days.

**Comment by haemichoung** [comment]
Hi! Thanks for your reply!
I thought that was it but when I click on the gem it says that the only
option to get gems is either paypal or my card but i scroll down and says I
have a subscription...
is that right? because it still prevents me from getting gems.

_Haemi Choung_
Cartoonist/ Funny Lady
www.haemichoung.com

**Comment by Alys** [comment]
Log out of HabitRPG, clear your browser's cache (make sure it's the cache that you clear, not your browsing history), log back in, reload the page, and if it still doesn't work, tell us your [User ID](https://habitrpg.com/#/options/settings/api).

**Comment by haemichoung** [comment]
hello!
I deleted my cache history and when i log in again, it still said i had to
get gems with either a credit card or paypal.
my user id should be haemichoung
but I log in via facebook
the facebook email is geekie@haemichoung.com

_Haemi Choung_
Cartoonist/ Funny Lady
www.haemichoung.com

**Comment by Alys** [comment]
Please tell us your User ID from the link in my message above. Your profile name won't help us because more than one person could chose the same profile name.

**Comment by haemichoung** [comment]
oh i see!
It's this: 65b7a063-0b73-4600-a67b-d163d7adad29

_Haemi Choung_
Cartoonist/ Funny Lady
www.haemichoung.com

**Comment by Alys** [comment]
Wait, I just noticed that you said this: "when I click on the gem it says that the only option to get gems is either paypal or my card but i scroll down and says I have a subscription". Is the only gem you're clicking on the one in the header?? If so, go to the market. See the "subscription" link in my first comment for information about how to buy gems.

**Comment by haemichoung** [comment]
OH MY GOSH! I found it! Haha!
Thank you so much for all your help!
You are a huge life saver! :)

_Haemi Choung_
Cartoonist/ Funny Lady
www.haemichoung.com
