### ISSUE TITLE
Increase Number of Gems for Contributors

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3933]
@Alys @lefnire 

We've been talking about the gem rewards for contributors, and we've come to the conclusion that 2 gems/tier isn't enough anymore. Back when we set those rewards, there was basically nothing to buy; nowadays, there are backgrounds, quest scrolls, saddles, quest eggs, limited edition items... 

So, we'd like to raise the amount of gems awarded every tier, to 3 gems/tier for the first three tiers, and 4 gems/tier for the next four. This would take the total number of gems that you can earn with standard contributions from 14 total (not even enough to buy a full background set) to 25, the same amount you can get in a month by subscribing.

People who have previously contributed will be automatically awarded the gem difference according to their level.

Note for @Alys that when this changes, we'll have to change the Community Guidelines.

**Comment by Alys** [comment]
I have already written a migration script for increasing the gems. I'll give it one final test then PR it and link it to here.

**Comment by lemoness** [comment]
++

**Comment by Alys** [comment]
Actually, it might be another couple of days. I should rewrite it as lefnire described here: https://github.com/HabitRPG/habitrpg/pull/3907#issuecomment-53522251

**Comment by Alys** [comment]
New PR: https://github.com/HabitRPG/habitrpg/pull/3957

**Comment by lemoness** [comment]
@lefnire let me know when you push this.

**Comment by negue** [comment]
The PR was merged, means we can close this one now?
