### ISSUE TITLE
No party notifcation

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica#3934]
Tried to invite a friend to our party, but she never received a notification in either her email (how she signed up) or any notification on her tasks screen. I had to tell her to check the "party" screen for it, which she hadn't thought to go to.

**Comment by Alys** [comment]
That's how it's meant to work. HabitRPG never sends emails to users for party invitations nor puts notifications on the tasks screens. You go to the party page for everything related to parties.

I'll adjust the text that appears on the party page when you are not in a party to make that more obvious.

**Comment by AnitaYCheng** [comment]
We're both UXers, and we were expecting at least a red speech bubble or...something. It doesn't have to be a modal window you have to close. We were thinking like Google Plus or Facebook, where you get a little red number on the alert icon.

She's totally new and hasn't gotten around to exploring all the pages. The "Party" page is not an obvious thing to check out unless you were feeling up for exploring. And I do think parties make HabitRPG a lot more fun, so trying to remind a newbie that parties exist would be good. :)

**Comment by Alys** [comment]
She would have received a notification like this on the header on any page on the site:
![screen shot 2014-08-27 at 11 38 08 am](https://cloud.githubusercontent.com/assets/1495809/4054207/dad9f6ac-2d8a-11e4-8276-423fb3dd6fcb.png)
The notification icon might have been different if she also had other kinds of notifications.

This pull request changes the text on the party page (when you are not in a party) to state that you can find party invitations on the party page: https://github.com/HabitRPG/habitrpg-shared/pull/289

Have you had a look at [HabitRPG's Trello board](https://trello.com/c/odmhIqyW/440-read-first-table-of-contents)? There's a card there for parties. It would be REALLY great if you could add some comments about how you think this could be improved. You can find the link to the board in the footer of any HabitRPG page ("Request Feature").
