### ISSUE TITLE
Confusing visual glitch

### ISSUE THREAD

**Issue by Finnicky** [HabitRPG/habitica#3935]
After trying to hatch some eggs on my mobile device, the main app loaded the pictures of the hatching potions wrong. The potions are not centered in the box, and appear to be the wrong color(if the potion is even visible at all). The zombie potion even has a picture of the hydra pet.
![image](https://cloud.githubusercontent.com/assets/8563212/4058781/bf7bbefe-2dda-11e4-8d90-160cfcf50a69.png)

When I checked my pets afterward, they were similarly glitched out. All the pets are colorshifted, and some have even been replaced with event and quest pets! When I roll-over or try to feed my pets, they still work as intended.
![image](https://cloud.githubusercontent.com/assets/8563212/4058790/d91b1b70-2dda-11e4-9a6f-c6fcc46311de.png)
I have never gotten the turkey pet. What do I need to do to get rid of the glitched visuals?

**Comment by Alys** [comment]
This happens sometimes when HabitRPG's image sprites are updated. It's a common temporary issue on sites that use sprite images (although the benefits of sprites outweigh the problems).

Any time you see anything a bit odd or unexpected in HabitRPG, just reload the page using your browser's refresh button. That almost always fixes it. Occasionally you might also need to clear your browser's cache and reload again (make sure it's the cache you clear rather the browsing history).
