### ISSUE TITLE
503 Errors, Application Errors, Screens not Refreshing Properly

### ISSUE THREAD

**Issue by wogsland** [HabitRPG/habitica#3938]
So these are popping up when I tried to reload HabitRPG:

![screen shot 2014-08-27 at 9 06 57 am](https://cloud.githubusercontent.com/assets/3073735/4060890/9fcf749c-2df3-11e4-92dc-4985dea97126.png)

I did an inspect element and looked at the console and I'm getting a 503 error. Same thing happens if I try to open it up in a new tab. I tried logging out and logging back in and I get a 503 error pop-up and cannot log in.

**Comment by Holseties** [comment]
I'm having this problem too! Also I find the site's been really slow this morning.
![untitled](https://cloud.githubusercontent.com/assets/8517672/4061105/8c8587b2-2df5-11e4-9070-1fe735f573f4.png)

And when I try to log in on Firefox.
![untitled2](https://cloud.githubusercontent.com/assets/8517672/4061378/7a740678-2df7-11e4-8d7a-babdf694b5a1.png)

**Comment by androidadvocate** [comment]
same issue as the one above this.

**Comment by k8sullyvan** [comment]
Yeah, me too :/ I tried on Chrome and Safari (where I get the 503 error) but no joy
![screenshot 2014-08-27 16 43 48](https://cloud.githubusercontent.com/assets/7197274/4062597/189561a4-2e01-11e4-8d23-fe152ec877e4.png)

**Comment by ifree** [comment]
me too

**Comment by negue** [comment]
Yes the server is down, and only your cached Frontend is working. I think the devs already know it, and they're working to find the error :)

Just wait and try again later.

**Comment by habitrpguser** [comment]
me too; comforts & good luck to the devs!

**Comment by valmikirao** [comment]
Having it too.  Help!  I need this site!

**Comment by MercuryChaos** [comment]
I'm having the same problem.

**Comment by ArlieS** [comment]
Ditto. 

Also https://oldgods.net/habitrpg/habitrpg_user_data_display.html repeatedly reports "There was an error obtaining your data."

And I had to hit reload on my browser 3 times this morning before cron appeared to have run.

It's also pretty clear clicks aren't always registering with the server, since the client reported I "lost" some xp at one point this morning. 

[Oh never mind, I just saw negue's comment. Clearly the server is still down 2 hours after zie commented.]

**Comment by veeeeeee** [comment]
Hi guys, we're aware of the issue and frantically working on it. Sorry for the stress and inconvenience! Will post here and on Twitter when we're back up.

**Comment by lefnire** [comment]
restarted server & upped dynos, we're back up now

**Comment by wogsland** [comment]
Hooray!

**Comment by pepperpanda** [comment]
I think I'm experiencing these errors again.

EDIT: Oh it's gone now.
