### ISSUE TITLE
Application Errors and Screens not Refreshing Properly + Party not Loading

### ISSUE THREAD

**Issue by Zelah-Meyer** [HabitRPG/habitica#3939]
Hi,  I subscribed this morning, so I'm not sure if the errors I'm experiencing are due to that or to other causes.  I checked the Facebook page and another couple of users had mentioned having issues today.

When I try to refresh my task page, I'm getting 'Application Error - Check Chrome Console' error messages popping up, and often the last thing I ticked doesn't register.  When I tried to refresh the tavern, it would take time then load with no chat.  Both problems are around about 50% of the time.  They will be buggy for a while, then work for a while, then buggy again.

I tried refreshing my task page in Chrome so that I could grab the console data & this is what it said:

Deprecation warning: moment.lang is deprecated. Use moment.locale instead. app-c180abc0.js:19
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). app-c180abc0.js:19
GET https://habitrpg.com/audio/off/Achievement_Unlocked.ogg 404 (Not Found) app-c180abc0.js:23
GET https://habitrpg.com/audio/off/Achievement_Unlocked.mp3 404 (Not Found) (index):1
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1409007440.html:1
Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1
GET https://habitrpg.com/api/v2/groups/party 503 (Service Unavailable) app-c180abc0.js:6
Object {data: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta …Error</p>↵      </iframe>↵    </body>↵    </html>", status: 503, headers: function, config: Object, statusText: "Service Unavailable"}
 app-c180abc0.js:22
POST https://habitrpg.com/api/v2/user/batch-update?_v=3879&data=1409150217614&siteVersion=1 503 (Service Unavailable) app-c180abc0.js:6
Object {data: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta …Error</p>↵      </iframe>↵    </body>↵    </html>", status: 503, headers: function, config: Object, statusText: "Service Unavailable"}
 app-c180abc0.js:22

Hope that helps to pinpoint the issue!  :)

**Comment by Verabird** [comment]
I'm getting these too

**Comment by MagBag** [comment]
Same here, in both of my user accounts.

**Comment by Holseties** [comment]
I have the same problem. There's a 503 error issue that's been brought up.

**Comment by metasean** [comment]
I received the same error, but was still able to successfully (at least they appear to have been successfully completed) mark a habit and a daily as complete, and I received appropriate coinage notifications.

**Comment by androidadvocate** [comment]
I have the same error. This is the message I get:
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

I can confirm tasks appear to be working.

**Comment by wysawyg** [comment]
It looks like the node js server might be down and just the angular js front end working so I wouldn't expect anything to persist. I did a refresh and tasks I ticked at lunch (via my work machine) are not shown as ticked on the screen now.

**Comment by ifree** [comment]
I got this error too, please fix it! thanks!

**Comment by metasean** [comment]
@wysawyg - That makes sense; thanks for the heads up!  Also, assuming "a" == "ain't", awesome username!

**Comment by habitrpguser** [comment]
me too

**Comment by MagBag** [comment]
A wee update with some specific issues:  I seem to be able to get my completed tasks to stick for the time being, but I get no tavern chat and I am no longer in a party, supposedly.  I have two accounts, and we are in a party together; neither are showing up as in a party at this time.

**Comment by JanChec** [comment]
+1. On Chrome it rejects most of changes (like adding/using points) with the error described above. On Firefox I can't get to login page at all, it redirects me to main page when I click "Zagraj" (pl for "Play").

**Comment by Bewildebeest** [comment]
Me too.  Or three.  Or twelve, or whatever.  Having all these issues.  Not having issues so much with tasks not sticking, but just now I tried to tick off one task, and instead two disappeared, and then I gained xp and gold and mana for one, but lost gold and xp and mana right after?  Neither was negative.

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/3938

The HabitRPG server is having trouble. The devs are aware of it and are working to fix it. You can follow the progress of the fix at https://github.com/HabitRPG/habitrpg/issues/3938. If you want email updates every time someone adds to the issue, you can click on the Notifications button on the right-hand column.
