### ISSUE TITLE
"Data column(s) for axis #0 cannot be of type string×"

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#394]
Hey this is only for the graphs for my dailies, but when I try to graph it, it says "Data column(s) for axis #0 cannot be of type string×" and shows no graph.
![image](https://f.cloud.github.com/assets/3587570/155785/372bb754-766e-11e2-9d2b-2c374a9d59e9.png)

**Comment by wc8** [comment]
I believe this is #315. Please follow up there.

**Comment by cleave29** [comment]
Thanks!
