### ISSUE TITLE
Due dates still highlight in red for completed To-Dos

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3940]
When it's the due date of a task or after, the due date appears in a red-highlighted style to draw the user's attention to it. However, this continues to be the case even if the task is completed. It'd be nice if the due date went back to its standard formatting when the task's done, for extra relief/satisfaction.

**Comment by wizonesolutions** [comment]
So should this issue be closed?

**Comment by Alys** [comment]
Confirmed fixed with a quick test.
