### ISSUE TITLE
Minor bug?

### ISSUE THREAD

**Issue by stormyhearted** [HabitRPG/habitica#3945]
Yesterday morning I started getting a weird pop-up when I click on a habit or task- it doesn't register my click but instead says "to=__ &from=__ are required" in a blue notification box. If I click the task a second time, it registers.

It's not really interfering with my use of Habit but I have no idea what it is. For reference, I'm using Chrome on Windows 7.

**Comment by Alys** [comment]
Your mouse is jiggling the task slightly, making HabitRPG think you are trying to move it to a new position, and that error occurs when a "move" is from one position back to the same position. This inadvertent jiggling sometimes happens with old or faulty mice, or with drawing pads used as mice.

A fix has been submitted for not showing that error for a "move" from one position to the same. It will be live in a few days.
