### ISSUE TITLE
Can't add attribute points after account reset

### ISSUE THREAD

**Issue by vivanesca** [HabitRPG/habitica#3947]
My attribute points show "-32" and neither automatic nor manual adding is to no avail.
![aa](https://cloud.githubusercontent.com/assets/6705130/4089390/5801d988-2f6b-11e4-8029-ec019fdd5ba2.jpg)
edit: I tried fixing it by changing stats like level and experience but it didn't work. Seems like they froze.

**Comment by Alys** [comment]
A similar issue was reported in https://github.com/HabitRPG/habitrpg/issues/2496 so I'll close this one. If you would like to follow the progress of this bug fix, you can subscribe to notifications in the other issue (button in right-hand column).
