### ISSUE TITLE
Item arrangement glitch

### ISSUE THREAD

**Issue by ericwilmoth** [HabitRPG/habitica#395]
Everything's been fine lately...but after rebooting my computer and relaunching a few minutes ago, all of my items have shifted around; i'd gone to some length to categorize them, and I know it was saving, because I did this a few days ago after we had that situation arise with habits being lost due to something you guys ended up fixing...so this is something new. 

In that previous bug someone commented that perhaps my last arrangement might yet be saved out there on your end, so I'm wondering if I can get it restored? also, some data I entered this morning got lost in this same glitch; I can live with that, but I really don't want to have to manually re-arrange things again if I don't have to. 

Thanks!

**Comment by ericwilmoth** [comment]
I just went ahead and reorganized everything; still, whatever happened might occur again, so hopefully it's something that can be sorted out for the future.

**Comment by ericwilmoth** [comment]
Ok...it happened again...and I've been refreshing the page after almost every entry; same basic pattern, too--it 'pseudo' randomly rearranges my items. What I mean is they appear to be rearranged to the same sequence they were rearranged earlier today...which is distinctly dissonant with the arrangement I've had them.

Please help!

**Comment by lefnire** [comment]
I'll have time next week to fix this bug. I recognize it, but have been
dealing with a lot of other stuff right now

**Comment by ericwilmoth** [comment]
Thanks! I know you guys are busy!

**Comment by ericwilmoth** [comment]
Just checking in to see if you've had a chance to look at this at all. Over the weekend I decided to give rearranging things another shot...but eventually it threw it all out of whack again, so I'm holding off using the system till you get a chance to sort it out--my ocd can't handle it.

Incidentally, congrats on the huge kickstarter finish! I am one of those who increased my donation at the end; wasn't much due to my finances, but i'm glad to see you guys blow your own goals out of the water with this--I think it's a marvelous tool that is going to do a lot of good for so many people!

**Comment by Pandoro** [comment]
I also thought this was fixed, but today it happened again. Somehow the
system seemed fairly robust. It just stopped dragging and dropping for me.
Eventually after several refreshes, it completely shuffled my list though.
After that I was able to order it correctly.

**Comment by lefnire** [comment]
let's follow this up on #318, it's still a bug (haven't tackled it yet - if it works until I close that ticket, it's a fluke)
