### ISSUE TITLE
Damage in party not loading

### ISSUE THREAD

**Issue by AmandaMock** [HabitRPG/habitica#3951]
I can see my party, and quest, I even see the damage other party members are doing and other elements in the feed. But my damage is not showing up in the feed or lowering the monsters health.

**Comment by Alys** [comment]
Click on the sync button on your party page. That's the button that looks like a circle made out of two arrows that's right next to the "send chat" button. It's important that you click THAT sync button, NOT the sync button in the top right corner of the page. The sync button next to "send chat" will cause new messages to appear in your party chat. Do you now see your quest progress?

If not, tell us your [Unique User ID](https://habitrpg.com/#/options/settings/api).

**Comment by AmandaMock** [comment]
I did, it's still not working. my UUI is
- 2d98182f-cd24-4048-aca8-f691708a1f14

**Comment by Alys** [comment]
According to your publicly-available data that the API provides, you're not part of a quest. Did you accept a quest invitation for the current quest? It's looking like the person who bought the quest scroll might have started the quest before you had a chance to accept the invitation. This would mean that you are not on the quest and will not be able to damage the quest boss or receive the quest rewards. You might want to talk to your party to find out who bought the quest scroll and whether they started the quest prematurely.

Another possibility is that you might have joined the party recently, after the quest had started. If so, you won't be part of the quest. (This is to ensure fairness. For example, it means that if a party works on a quest for weeks to earn the rewards, a new member who joins the day before the quest end doesn't share in rewards that they haven't earned.)

**Comment by AmandaMock** [comment]
This happened while things were going a little wonky with your systems.
1. No I have not joined the party recently
2. Yes I accepted the quest.

**Comment by Alys** [comment]
Which quest is it? How long has it been running for and roughly how much damage has been done to the boss? What is your party's Group ID? You can find that on the party page.

**Comment by AmandaMock** [comment]
Attack of the Mundane Questline, Pt. 3: The Laundromancer

About 2 days I believe?

And the only damage done has been by another party member total of 45.

Group ID: fbed4fb8-73c7-48e8-88c3-208713f02a3a

**Comment by Alys** [comment]
If it's been two days and there's only one other piece of damage, it's likely that others in your party have the same problem you do. This means that the quest would take much longer to complete than it should and that only some of the party will receive the reward. I recommend that the person who started the quest (bought the quest scroll) should abort the quest and restart it (the quest scroll will go back into their inventory, although they might need to refresh to see it). I think that's probably the best and fastest way to resolve this.

I realise this is inconvenient for everyone, and I'm sorry that the site glitches caused the problem. As compensation, if your party is willing to restart the quest, I'll give you a quest scroll for any other [currently-available quest](http://habitrpg.wikia.com/wiki/Quests#List_of_Quests_-_Types_and_Availability) of your choice (see the "List of Quests - Types and Availability" section on that page).

**Comment by AmandaMock** [comment]
Fair enough, I will notify my party members.

Can I take on the The Call of Octothulu
http://habitrpg.wikia.com/wiki/The_Call_of_Octothulu quest?

**Comment by Alys** [comment]
I've assigned you the quest scroll. If you refresh your inventory page you should see it. Tell me if you don't!

I'm going to close this since I'm confident that stopping and starting the quest will fix all the problems, but if you have any trouble at all or any questions, comment again here and we'll reopen this.
