### ISSUE TITLE
API: Chat Like returns full chatlog

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#3953]
Is this necessary?

I mean is it by design like that or just a bug?
##

**Comment by lefnire** [comment]
It's limited to 200, so it shouldn't be too much load. but if we can page it, all the better!

**Comment by deilann** [comment]
But why return the entire chat log when liking a message? Might make more
sense to return that message.

**Comment by paglias** [comment]
I think se might have done so in order to sync new messages upon every
action (send message, like...)
Il 30/ago/2014 00:38 "deilann" notifications@github.com ha scritto:

**Comment by paglias** [comment]
Anyway, Not saying this is the ideal solution
Il 30/ago/2014 00:39 "Matteo Pagliazzi" matteopagliazzi@gmail.com ha
scritto:

**Comment by crookedneighbor** [comment]
Definitely should not return all the message :disappointed:

**Comment by paglias** [comment]
Fixed in v3
