### ISSUE TITLE
Skeleton Panda Mount Head Shift

### ISSUE THREAD

**Issue by zincotroid** [HabitRPG/habitica#3954]
![image](https://cloud.githubusercontent.com/assets/7400973/4097281/b0ee9854-2fd1-11e4-97f9-ed887b46759a.png)

The skeleton panda mount's head looks like it's too far left, at least compared to the other panda mounts.

![image](https://cloud.githubusercontent.com/assets/7400973/4097299/1047acc8-2fd2-11e4-99c1-0859b8f4f753.png)

**Comment by ebiagogo** [comment]
I have this fixed locally and can commit it once I read the the Artisan guide to make sure I submit the change correctly.

**Comment by deilann** [comment]
You'll need to submit arts permissions if you haven't already, so habit has
the rights to use the altered image. I know it's just a shift, but it's
still a change. :) You can find the info for permissions on the pixel art
trello. If you don't know where that is or can't find it, let me know.

**Comment by ebiagogo** [comment]
Yup, I found it earlier and saw there's a bit to read through which is why it's going to take me a little bit longer to commit it. It'll probably take more time for me to read through it and finish the steps than it took me to shift the image. :) It's all good though, I understand the reason the policies are in place. Thanks much for the info.

**Comment by deilann** [comment]
Awesome. :)

**Comment by zincotroid** [comment]
Thanks guys, maybe some day I'll be able to make edits like this on my own. I just haven't sat down and figured out things like the Art Permissions, but I would like to contribute. I might start out trying my hand at writing a quest :)

**Comment by ebiagogo** [comment]
So I'm trying to test the change to the Skeleton panda mount on my local habitrpg and I keep getting an error when trying to recreate the spritesmith png files (grunt sprite under habitrpg-shared. The documentation seems to be sparse on building shared but I think I have things set up correctly. I keep getting the following error when it gets to the sprite:3 task:

...
Running "sprite:2" (sprite) task
Files "dist/spritesmith2.css", "dist/spritesmith2.png" created.

Running "sprite:3" (sprite) task
Fatal error: Unsupported interlace method.

I thought maybe  the new panda file was causing the error (even though I think the head is on the spritesmith5.png) so I reverted back to the most recent source and still get the error.

Thanks,

Michael

**Comment by ebiagogo** [comment]
It looks like the img/sprites/spritesmith/quests/quest_atom1.png is causing the "Unsupported interlace method" error. I'm not sure why. I opened it in gimp and just exported it again and recreated the sprites without an issue. I was then able to verify the new panda mount head locally.

I don't want to commit changes to the quest_atom1.png without confirmation that there's some issue with it. Also, does one commit the new dist directory and its contents after making a change to the sprites or is that directory generated as part of the build?

**Comment by ebiagogo** [comment]
submitted a pull request over on habitrpg-shared
