### ISSUE TITLE
Tasks That Can't Be Deleted

### ISSUE THREAD

**Issue by cm006j** [HabitRPG/habitica#3958]
I have some challenge tasks left over that I no longer want but there is no way to get rid of them. Even respawning didn't work! There's no delete option, there's no option to go back to the challenge and unjoin because it's already over. I really don't want these tasks anymore. What can I do?

**Comment by deilann** [comment]
If the megaphone for the challenge isn't "broken" yet, click one of the
challenge tasks like you did it then press sync. The megaphone should break
and you can then click the broken megaphone for the option to remove it.

**Comment by cm006j** [comment]
Oh! It did say "broken challenge link" but then once I hit the sync, it gave me the option to remove the tasks that I was looking for. Thank you!
