### ISSUE TITLE
Third Party Habits?

### ISSUE THREAD

**Issue by aedunn6** [HabitRPG/habitica#3959]
When I logged into Habit this morning, I had some strange habits that I did not add. The task description says it was added by a third-party service. I'm not sure if this is from something I don't remember signing up for, or a bug. But, I assume it's the latter. 
![odd habits](https://cloud.githubusercontent.com/assets/6609895/4103532/dd23e934-3165-11e4-900c-046b1a5e40ab.png)

**Comment by Alys** [comment]
See "Habit Added by a Third-Party Service" in [Known Bugs](http://habitrpg.wikia.com/wiki/Known_Bugs#Habit_Added_by_a_Third-Party_Service) or https://github.com/HabitRPG/habitrpg/issues/2558, They can be deleted.
