### ISSUE TITLE
Feature request: Spells

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#396]
Levelling up could open up new spells, which you can buy from a trainer or buy from the store. They would let you modify the task list in various ways, using up Energy:

Are you a task-smashing barbarian? You can learn the `Combine To-dos 1` spell which:

``` text
    Lets you combine 3 to-do list tasks, consuming 25 Energy.
    Finish all 3 tasks within 24 hours to get 25% more XP for them.
    Failing to finish the tasks within 24 hours simply uncombines them.
```

Are you a wizard at prioritizing? You can learn the `Heat Up 2` spell which:

``` text
    Increases the XP multiplier of any task by 0.05, consuming 5 Energy.
    If used on daily tasks, also increases the HP loss of undone tasks.
```

**Comment by caycefischer** [comment]
This is really cool! Spells as custom task combos/chaining

**Comment by ancientcampus** [comment]
At first I was skeptical, but this actually sounds pretty cool. It "Gamifys" HabitRPG a little more (which might not be everyone's cup of tea, but what I personally like), without having it drift away from a task/habit organizer.

"Heat Up" is also a great name - you could implement it by simply making a task more "Red".

**Comment by wc8** [comment]
Vote & suggest more: [Spells](https://trello.com/c/OsmmLDqw)

**Comment by lefnire** [comment]
we'll follow up on this feature in the Trello card
