### ISSUE TITLE
Subscription canceled prematurely

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3963]
My sub got paid on Aug 25 and after a couple days I unsubbed thinking I would have perks until Sep 25 but today I find myself without sub, is there a way to add those sub days to my account?

**Comment by deilann** [comment]
Please email admin@habitrpg.com and Tyler will be able to help. Payment
issues are better handled privately, as they may require more sensitive
data to resolve.

**Comment by ghost** [comment]
tried to mail but no answer

**Comment by deilann** [comment]
Lemme ping @lefnire to see what's up. Might not have got it.

**Comment by lefnire** [comment]
Answering via email
