### ISSUE TITLE
Can't repurchase Nameless Helm

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#3967]
Hello! I have a quick question. I've completed both the "Vice Awakens" and "Attack of the Mundane Questline, Pt. 3: The Laundromancer" quests, receiving Stephen Weber's Shaft of the Dragon and the Nameless Helm respectively. I recently used an Orb of Rebirth, and while the Shaft of the Dragon appears in my store, the Nameless Helm does not.

I haven't reached Level 10 yet, so if the Nameless Helm can only be accessed by certain classes/after Level 10, that might be the issue, but I've seen no indication that this should be the case. Does anyone know why this might be happening?

Thanks in advance!

**Comment by deilann** [comment]
@lefnire tends to fix these pretty fast :) it's easy to forget with new
items

**Comment by Alys** [comment]
I can see the problem. I'll submit a PR. Although you'll still have to wait for lefnire to push it live. :)  But it WILL be fixed. Thank you for reporting it!

**Comment by HSalgo** [comment]
Thank YOU guys!

**Comment by Alys** [comment]
@HSalgo : The [Pull Request](https://github.com/HabitRPG/habitrpg-shared/pull/297) will be merged by someone, and at some time after that, the change will be pushed to the live site. You won't see this bug being fixed until it is pushed to live, so it might be a few days, maybe even several days.

Excellent bug report by the way. Giving us something related that worked to compare the bug to was very helpful.

**Comment by HSalgo** [comment]
Sorry--still sort of new at this. Does this mean that the change is pending?

**Comment by lefnire** [comment]
Yes, will go out late tonight

**Comment by HSalgo** [comment]
Problem seems to be fixed. I appreciate your help! Thank you very much!
