### ISSUE TITLE
Quest does not begin once all members have accepted or rejected.

### ISSUE THREAD

**Issue by townimbecile** [HabitRPG/habitica#3968]
Expected behavior: "Once all members have either accepted or rejected, the quest begins."
Current behavior: We have 9 accepts, 1 reject, and 0 pending. The quest has not yet begun.

Our group id:
4b176c09-b969-4437-b744-ac43bc7c3721
##

**Comment by lefnire** [comment]
sounds like a bug indeed! in the mean time, you can manually begin the quest at the bottom of the quest dialog

**Comment by thepeopleseason** [comment]
@townimbecile Can you confirm that the party has had at least one member who was previously part of the party, but has since left or been removed? 

I believe this has something to do with a party's data structure keeping old members' UUIDs.

**Comment by townimbecile** [comment]
@lefnire I can't, because I didn't initiate the scroll. @thepeopleseason I believe that is what happened, but I'm not sure the exact timeline. In chat, no one seems to be taking responsibility for using the scroll.

**Comment by townimbecile** [comment]
@thepeopleseason Sorry, let me elaborate. Yes, I can confirm that people have left the party. That is definite. Additionally, it is possible, though difficult to verify, that someone left after using a quest scroll but before the party had accepted.

**Comment by Alys** [comment]
@townimbecile : For what it's worth, there might be a [change](https://github.com/HabitRPG/habitrpg/pull/3966) coming that will indicate which quest participant is the Quest Owner (bought the scroll and is able to start or abort the quest). It might be a few days before that change goes live, if it's accepted.

It's possible to use the [API](https://habitrpg.com/static/api) to find out who the quest owner is now, although the process is a little convoluted if you aren't familiar with APIs like this.

**Comment by townimbecile** [comment]
@Alys After casual reading, I see how to abort a quest, but I don't see any command for querying owner.

**Comment by Alys** [comment]
It's a multi-step process. :)

Under `groups`, use `GET /groups/{gid}` to get all data for your party. Near the top will be something like this:

```
 "leader": "d904bd62-da08-416b-a816-ba797c9ee265",
 "name": "YourPartyName",
 "type": "party",
 "quest": {
    "key": "vice1",
    "leader": "0abcdef-0798-4787-b1f6-91ec957c14ba",
    "members": {
      "d904bd62-da08-416b-a816-ba797c9ee265": true,
```

You want quest -> leader (0abcdef-0798-4787-b1f6-91ec957c14ba in that example). Don't use the party leader by mistake (that's the first ID in the example above).

Then under `members`, use `GET /members/{uid}`, BUT I have just remembered that you can't actually do that step through the API webpage, you need a custom-written script for it. If you paste the quest leader's ID into this issue, I'll find their name for you (I already have a script). Note that I won't be able to see any private data for the quest leader, so it's safe for you to do this.

**Comment by townimbecile** [comment]
@Alys I figured it out. Wonderful! Thanks. I can workaround for now.

**Comment by terry-webfox** [comment]
Used the API to get our party ID, then used that get the quest owner ID, then used that to cancel the quest (the user went offline, so got booted, and the quest wouldn't start and had no cancel option). I used the Postman extension for Chrome to do it with a GUI (quite a lot of copying and pasting, but that was ok).

**Comment by crookedneighbor** [comment]
Glad to hear it's worked out.

**Comment by terry-webfox** [comment]
@crookedneighbor I'd still consider this a bug worth fixing. The only reason I managed it is because I'm a software developer and figured out how to use the API! :-)

**Comment by crookedneighbor** [comment]
Good point. Just trigger happy to close issues I guess. :)

**Comment by paglias** [comment]
Should be fixed
