### ISSUE TITLE
Mana regeneration is only indirectly affected by productivity

### ISSUE THREAD

**Issue by Gaelan** [HabitRPG/habitica#3969]
Mana regeneration on cron is the (only?) aspect of HRPG where simply increasing an attribute advances you in the game. PER increases drops and gold, but only when you check off tasks. Same with INT and XP and STR and boss damage. I think that mana regeneration (at least for non-todo-heavy users like me) needs to be more directly affected by productivity, something like earning (previous cron mana regeneration)/(number of dailies) earned whenever a daily is checked.

**Comment by lemoness** [comment]
There was some discussion of making mana regeneration a sign-in incentive - only getting MP regeneration on days that you sign in. Not sure if that was ever implemented.

Trello might be a better place to have this discussion until we figure out an actionable plan. Maybe this card: https://trello.com/c/L1H6LiZ3/110-classes-v-2-character-stats-attributes-the-class-system-buffs

**Comment by chimericdream** [comment]
This should be addressed in #3029

**Comment by Alys** [comment]
@chimericdream It _is_ addressed in #3029. We'll be allowing mana to be gained from Habits and Dailies, and also lost from negative Habits and skipped Dailies, which ties it much more tightly to productivity. 

Also mana regeneration is now a sign-in incentive as described in the Trello card that lemoness linked to.

**Comment by chimericdream** [comment]
@Alys Sorry, that's what I meant. I was mainly going through old issues and trying to tag the ones related to #3029 to make it easier to close them after it gets merged. :smile:

**Comment by Alys** [comment]
Oh cool! A good initiative! :) Thank you.
