### ISSUE TITLE
Feature request: Achievement temperatures

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#397]
Achievement temperatures are like streaks but much, much less perfectionistic. For example, if you finish all your daily tasks one day, the reward for "Finished all daily tasks" heats up. If you fail, it cools down more than it would have heated up.

The reward is based logarithmically (or something like that) on how hot the achievement is. So, if you get all your daily tasks done almost every day for the past few years, you might get, for example, a considerable HP recovery every hour. If you fail to do all your daily tasks quite frequently, you wouldn't get very much HP recovery.

**Comment by horusofoz** [comment]
Your request has been moved to [Trello Card 200](https://trello.com/c/ejORegNg). Vote for your request on Trello to see it become a reality,
