### ISSUE TITLE
Notifications tied to browser

### ISSUE THREAD

**Issue by wysawyg** [HabitRPG/habitica#3971]
Not sure where to put this as it's not a bug, more a suggestion for discussion.

I love the notification stuff. I would love it more if it was tied to a cookie or something that tied it to a particular machine rather than my user profile. The reason for this is that I love having the sounds on at home but I also check HabitRPG at work where I don't really want the sounds going off.

I can keep turning it off and on but if other people feel the same way then it might be worth taking it out of user profile and into cookies.

**Comment by Alys** [comment]
Having preferences stored in cookies would be a relatively large change from our current system of storing all preferences in the user object. I haven't seen any other requests for this, and the notification sounds have a mute button now in the header, so I'm closing this. If it's still desired, it's best suggested at Help -> Request a Feature.
