### ISSUE TITLE
Wrong translation to Portuguese

### ISSUE THREAD

**Issue by tgl-dogg** [HabitRPG/habitica#3973]
In my profile/stats page there is a couple of badges that the player has/could have, etc. The colaborator badge has the following text (in Portuguese):

> Contribuiu ao HabitRPG (código, design, arte pixelada, **concelho** legal, documentos, etc).

The world **concelho** is intended to mean _advice_, but the correct spelling is **conselho**. Concelho means county/town hall.

**Comment by paglias** [comment]
@tgl-dogg thanks for the report! Translations are managed at Transifex https://www.transifex.com/projects/p/habitrpg/ where you can join the Portuguese team and leave a comment for that string
