### ISSUE TITLE
Facebook login button is missing

### ISSUE THREAD

**Issue by vibitect** [HabitRPG/habitica#3974]
It is actually "display:none"-d either purposefully or by accident. Please make it appear since Facebook users can't log in without manipulating the css by hand.
![screenshot from 2014-09-03 15 13 45](https://cloud.githubusercontent.com/assets/1253248/4134466/d5a36a96-336c-11e4-9a4b-41267c6a0412.png)

**Comment by Alys** [comment]
The backend code that implements that bit of HTML doesn't have display:none in it, and the facebook button appears in two of my browsers (and maybe more; I tested only two).

Do you have any extensions or similar that block facebook integration features on some/all websites? E.g., privacy/anti-spam extensions.

**Comment by vibitect** [comment]
Sorry my bad. I had a plugin in Chrome which hidden it for some reason.

**Comment by Kimoki** [comment]
I know this is an zombie thread, but I had the exact same problem. It was my ad blocker. I disabled it on Habitica (they deserve every penny of ad revenue they can get) and viola, my Facebook and Google login buttons showed up. The solution is still relevant today.

**Comment by Alys** [comment]
@Kimoki Great to know, thanks for posting that! Good news though - we don't have any ads. :) We used to many years ago (tiny Google text ads on the Tasks page) but you definitely won't see any now! Thanks for being willing to put up with them though. :)
