### ISSUE TITLE
Newly created Rewards with extra note leave the popup displayed after clicing Save & Close

### ISSUE THREAD

**Issue by vibitect** [HabitRPG/habitica#3977]
Example:

![extra_note](https://cloud.githubusercontent.com/assets/1253248/4135051/6531a074-3372-11e4-9f0c-b665a8df462b.png)

This happens in both Chrome and Firefox but only when using "Save & Close".
If the save icon is clicked in the top right corner it disappears immediately.
##

**Comment by gjoyner** [comment]
Looking into it and it seems to be for all tasks. Steps to reproduce that I've found:
1) Edit a task
2) Add a comment if needed.
3) If you added a comment, save the change, then reopen the task and make sure your cursor is the move cursor so it will force the comment to show.
4) Click Save & Close
5) The comment stays.

Going to look into this one and see if I can find out why. :)

**Comment by Alys** [comment]
Confirmed in Firefox (following the steps from gjoyner's comment).

**Comment by SabreCat** [comment]
Client display issue. Pending until after frontend redesign.

**Comment by lemoness** [comment]
This is no longer a problem in the new site because notes are displayed differently, so I'm closing this ticket.
