### ISSUE TITLE
If a menu button is clicked it does not disappear until another menu button or an option is clicked.

### ISSUE THREAD

**Issue by vibitect** [HabitRPG/habitica#3978]
Example:

![menu](https://cloud.githubusercontent.com/assets/1253248/4135355/2436be80-3375-11e4-8e0a-476ad92c9f8b.png)

If a menu button (surrounded with red or black squares) is clicked a menu appears and it does not disappear until I select an item from the menu or I click another menu button.

The menu persist even if I navigate to a different page.

Tested with:
- Chrome
- Firefox

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/3783

The menu closes when you click the menu icon.

I believe I read somewhere that this is deliberate behaviour intended for usability for users in certain situations. Mobile devices and/or users with poor mouse control maybe??? I can't find that ticket though.
