### ISSUE TITLE
Plain Egg sell cost incorrect

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#3979]
I just noticed under "Quest Eggs" on http://habitrpg.wikia.com/wiki/Eggs that Plain Eggs were supposed to be sold for 1 gold each. I just sold mine for 3 gold each. Don't know how much this will affect anyone, but I figured I'd point it out!

**Comment by Alys** [comment]
The wiki is wrong. Quest eggs sell for 3GP: https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L636

Thanks HSaigo, I'll adjust the wiki.
