### ISSUE TITLE
Suddenly died

### ISSUE THREAD

**Issue by Nostrocker** [HabitRPG/habitica#398]
Just died in the middle of the day, had around 40hp as of noon, logged back in around 4:00 to a death screen. Hadn't even used it in between!

**Comment by lefnire** [comment]
yowzer, I'll check into that. If you [email me](mailto:tylerrenelle@gmail.com) your username / user-id I can restore whatever you want me to in the mean time.

**Comment by lefnire** [comment]
also, any chance it could have been the chrome extension killing your for procrastination websites? do you have it installed?

**Comment by Nostrocker** [comment]
Hey, that was fast! User name is Nostrocker, ID
a872a846-5e4e-48a4-9512-e030d13e5b3c.

I have StayFocused installed but disabled, and I haven't had it enabled in
months so I don't think it would be that

**Comment by lefnire** [comment]
the [habitrpg extension](https://chrome.google.com/webstore/detail/habitrpg/pidkmpibnnnhneohdgjclfdjpijggmjj?hl=en-US) is what i mean. Cool, what do you want me to set you up with? armor:leather weapon:goldsword hp:50,etc?

**Comment by Nostrocker** [comment]
Oh, nah I don't have that extension yet. As for stuff, I think i was level
5 with leather armor, first level shield, blue sword. But you know, what's
a color? gold sounds better :) Thanks dude! By the way, congrats on
breaking your goal! I'm pretty stoked.

**Comment by lefnire** [comment]
Thanks a lot, I'm super super stoked! Ok, give that a shot

**Comment by Nostrocker** [comment]
I live! Thanks man. Hey while I've got you here, whats your art situation
like? I'm a huge fan of pixel art and have made a bit in the past, is there
anything you need made yet or is that all covered?

**Comment by lefnire** [comment]
chime in on #107, there's a few people bouncing stuff around. We've got kinda a "pixel art director", Pandoro - he'll be able to fill you in - but TMK we still need backer-only gear. Thanks for asking btw!
