### ISSUE TITLE
Daily Gold not working correctly

### ISSUE THREAD

**Issue by nyanbinaryneko** [HabitRPG/habitica#3981]
![screenshot 2014-09-03 22 47 46](https://cloud.githubusercontent.com/assets/3050609/4144343/fca1432c-33dd-11e4-97d5-2362387d69c4.png)
If I select, and unselect the daily, it takes away the correct amount of XP, but not the correct amount of Gold. This can be abused.

**Comment by SabreCat** [comment]
We've been tracking this on #964 (the title mentions To-Dos, but it's a problem across all undo'able tasks).
