### ISSUE TITLE
Everything in My Account Is Gone :(

### ISSUE THREAD

**Issue by jvallexm** [HabitRPG/habitica#3982]
I logged out of my account and when I logged back in I had to reset my password. Now all of my tasks, items, equipment, mounts, pets, and my subscription are no longer listed when I open up the website.

I can still access them on my iOS device, but how can I get them back onto my PC?

**Comment by deilann** [comment]
You have a duplicate account with your credentials. When you see the empty
account, delete it. This should fix your problems.
