### ISSUE TITLE
Pressing Enter key while editing preexisting tag immediately deletes it

### ISSUE THREAD

**Issue by freakinhippie** [HabitRPG/habitica#3983]
While editing an existing tag, I pressed the enter key thinking that would possibly save the changes. Instead it completely deletes the tag. I suspect this may be the result of the delete button having focus for the tag editing widget. Is this the intended behavour?

**Comment by lemoness** [comment]
Hitting "enter" to save is pretty intuitive - this might be expected
behavior, but it's worth a reevaluation.

**Comment by caseyhoward** [comment]
Yep, I just got bit by this.

**Comment by lurfdurf** [comment]
I've been bit by this many, MANY times. I suspect "Enter" is tied to the blank "Add Tag" function, which is why it reloads the tags, but I'm not sure why it also deletes the tag being edited. Very frustrating.

**Comment by gjoyner** [comment]
Hey everyone! I started looking at this and so far I can confirm that the Enter key is tied to the delete button of each, individual tag. I have no idea why Enter is tied to those delete buttons, but trying to dig further to figure it out. :)

**Comment by Alys** [comment]
fixed
