### ISSUE TITLE
Persistent To-Do item

### ISSUE THREAD

**Issue by squirrelfox** [HabitRPG/habitica#3985]
A week or two ago, I added a task to my to-do list. I completed it a few days later and checked it off. It disappeared normally. The next day, it was back in my to-do list. I thought I'd misremembered, and checked it off again, and it disappeared. 

However, it now reappears every time I sync. I have tried checking it off multiple times, but my Completed task list only shows one instance. At this point it is pretty far down in my list, but the color is still yellow, and the surrounding tasks are red, suggesting it's creating with a fresh date each time?

I did add a daily task with the same description a few days later when I realized I'd need to do this task regularly; I've since changed the name of the daily to something else to test if the two items were related, but the to-do keeps popping back up.

I am a subscriber, in case that affects how completed tasks behave; I usually use mobile Firefox or desktop Firefox (fully updated on one machine, still on 28 on another) and see this issue everywhere.

Any thoughts on how to get rid of this task?

![zombietask](https://cloud.githubusercontent.com/assets/8660487/4156443/6c36c32e-3474-11e4-80f0-adc1f743be2b.PNG)

**Comment by lemoness** [comment]
Might be related to https://github.com/HabitRPG/habitrpg/issues/2456? I had
a task duplicate and then keep reappearing yesterday.

**Comment by squirrelfox** [comment]
I wasn't sure how to flag those as possibly related, but they do sound close!The main difference I saw was that my water-the-foundation task never seems to end up with more than one copy active at a time, even if I perform multiple syncs. I also don't get any of the odd damage or insta-death that some users are seeing.

It's pretty reliable, so I'd be happy to run any tests that might help.

**Comment by Alys** [comment]
@squirrelfox : Can you add your [Unique User ID](https://habitrpg.com/#/options/settings/api) please?

If you're comfortable using the [API](https://habitrpg.com/static/api) (or learning how to), it would be interesting to see if that To-Do had the same "id" number as any other task on your lists. Our database admin could also check this but he tends to have a lot to do so it might not happen quickly. :)

**Comment by squirrelfox** [comment]
Sure--my UUID is 726be399-9295-4993-8c02-8c602e03ac4a . 
I tried out the API, and it looks like the To-Do's ID number is unique within my task list (it's de771e89-3eef-4347-aef9-0c473f1208e4 if that's useful at all). It has an original date created of 8/22, which sounds about right, but a value of -1 (full deal screenshotted below). 

![todo](https://cloud.githubusercontent.com/assets/8660487/4167630/c6d630e4-3514-11e4-8cca-90656a43148b.PNG)

**Comment by Alys** [comment]
@lefnire, is there anything you want to look at before we ask squirrelfox if the task is able to be deleted with the trashcan?

**Comment by Alys** [comment]
@squirrelfox what happens when you try to delete the task using the trashcan icon?

**Comment by squirrelfox** [comment]
Hi @Alys--I am really sorry, I missed this email. I deleted the task and it
did not return. This was also effective for a second zombie task that
popped up a while back. Thank you and apologies for the delayed response!
