### ISSUE TITLE
MongoDB: migrate to unique indexes

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3986]
Self-assigned. Many of our indexes aren't unique where they _should_ be. Eg, `auth.local.username`, `auth.local.email` (4.7k dupes on this field alone!), `auth.facebook.id`, etc. This will mitigate those dupe-db-ops issues where user has multiple accounts. Alas that one can't edit indexes, and there are dupes where indexes need uniqueness to boot, so this needs to be handled piecemeal:
- [ ] Backup database
- [ ] Identify which indexes need to be unique.
  - So far: `auth.facebook.id_1` `auth.local.email_1` `_id_1_apiToken_1` `auth.local.username_1_auth.local.hashed_password_1` `_id_1___v_1`
- [ ] For each index, [identify any dupes](http://blog.mongolab.com/2014/03/finding-duplicate-keys-with-the-mongodb-aggregation-framework/) - identify amongst those dupes which record is canonical and which can be deleted. Delete the non-canonical records
- [ ] Find a down-time and run these (very taxing) operations: `db.users.dropIndex(...)`, `db.users.ensureIndex({...},{unique:true, sparse:true})`
- [ ] How to handle errors for unique keys (`err.name === 'MongoError' && err.code === 11000`)

---

Notes: 
- `{background:true}` should be avoided [for performance reasons](http://stackoverflow.com/a/13769898/362790). 
- `{dropDupes:true}` [could be used](http://docs.mongodb.org/manual/tutorial/create-a-unique-index/) to skip steps, but I need to manually determine which record is canonical and which is "accidental".
- `{sparse:true}` [is required](http://docs.mongodb.org/manual/core/index-unique/) for values which may not exist (think local v facebook registration)
- Editing indexes notes: [1](https://groups.google.com/forum/#!topic/mongodb-user/Ie1dX0cKe1c), [2](http://stackoverflow.com/questions/13769603/can-i-modify-existing-index-in-mongodb-without-dropping-it)

---

Sample Queries

``` javascript
// Find duplicate emails, see http://blog.mongolab.com/2014/03/finding-duplicate-keys-with-the-mongodb-aggregation-framework/
db.users.aggregate([
  { $group: {
    _id: { "auth.local.email": "$auth.local.email" },
    uniqueIds: { $addToSet: "$_id" },
    count: { $sum: 1 }
  }},
  { $match: {
    count: { $gt: 1 }
  }}
])
```
##

**Comment by lefnire** [comment]
In fact, I'll bet this is 99% of the times when users say "Website & mobile apps don't sync". They logged in with uname/pw on mobile, it gave them their duplicate account - and they're managed separate. Just a theory. @Alys @deilann

**Comment by lemoness** [comment]
If that's true, fixing this would solve one of our major complaints. Fingers crossed.

**Comment by paglias** [comment]
:+1: :+1: :+1: :100:

**Comment by paglias** [comment]
@lefnire just one think I would add to the checklist "how to handle errors for unique keys" because when you try to insert an already used unique key it doesn't cause a mongoose validation error but a mongo error which unhandled cause a 500 status code I think

**Comment by paglias** [comment]
@lefnire I've added the error name and code returned for reference (don't know why the text is so big)

**Comment by paglias** [comment]
@lefnire I think this is worth implementing:

> When your application starts up, Mongoose automatically calls ensureIndex for each defined index in your schema. While nice for development, it is recommended this behavior be disabled in production since index creation can cause a significant performance impact. Disable the behavior by setting the autoIndex option of your schema to false.

See http://mongoosejs.com/docs/guide.html#indexes

**Comment by lefnire** [comment]
Exactly, I'd seen that a while back and that's why there aren't any indexes defined in the Mongoose schemas. For performance, they should be added manually via the mongo terminal (which is how I've been doing it). Unfortunately, that means people with localhost or even server deployments won't get those indexes. You and I do, since we download database snapshots (which include indexes). 

It _may_ be worth adding indexes to the schema `if (process.NODE_ENV == 'development')` or something, but meh - haven't seen anyone asking for it

**Comment by paglias** [comment]
Ohhh ok, I didn't noticed we don't have them in Mongoose, then no problem

2014-09-05 21:27 GMT+02:00, Tyler Renelle notifications@github.com:

> Exactly, I'd seen that a while back and that's why there aren't any indexes
> defined in the Mongoose schemas. For performance, they should be added
> manually via the mongo terminal (which is how I've been doing it).
> Unfortunately, that means people with localhost or even server deployments
> won't get those indexes. You and I do, since we download database snapshots
> (which include indexes).
> 
> It _may_ be worth adding indexes to the schema `if (process.NODE_ENV ==
> 'development')` or something, but meh - haven't seen anyone asking for it
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3986#issuecomment-54670246

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
@lefnire just found a user with 4 duplicate accounts all with the same email registered this october #4227

**Comment by lefnire** [comment]
@paglias yeah, it's a not-uncommon occurence - pretty serious issue

**Comment by Alys** [comment]
update from https://github.com/HabitRPG/habitrpg/issues/5126: usernames have an unique index
