### ISSUE TITLE
Snowflake Wand uses the wrong attribute in its tooltip

### ISSUE THREAD

**Issue by vibitect** [HabitRPG/habitica#3989]
When I was translating the texts of gear.json I've found a small problem:

> Limited Edition 2013 Winter Gear! This wand sparkles with unlimited healing power. Increases Strength by `<%= int %>`.

`<%= int %>` should be `<%= str %>`

**Comment by wysawyg** [comment]
Given it's a healing wand, it's probably the other way around: It should say 'Increases Intelligence by <%= int %>

**Comment by Alys** [comment]
Yes, the wand definitely increases INT, not STR. The text should be changed to say "Increases Intelligence". This is a good job for an entry-level contributor.

**Comment by vibitect** [comment]
I'll create a pull request for it during the weekend then! Can you assign the task to me? It seems I can't do it myself.

**Comment by itaisanders** [comment]
@adam-arold did you close this one?
don't wanna step in if you're already on it.

**Comment by vibitect** [comment]
Not yet sorry, but I will resolve it this week. I was preoccupied with the Hungarian translation.

**Comment by itaisanders** [comment]
sure, no problem. if you see you don't get to it and want me to step in, just say so.
