### ISSUE TITLE
Dailies with Checklists increment too many times while on a boss quest

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#3990]
Hey there. While on a boss quest, I notice that sometimes the daily streak counter increments more than it should for certain dailies. It happens only with dailies with checklist items. Today, for example, the majority of my dailies are at 4 and are green, but one with three checklist points is at 7 and is blue. I've seen this glitch a few times, and just figured it was a wacky error, but today was the first time I'd actually seen it happen and was able to trace it. A few other notes:

1) This glitch has only happened while on a Boss Quest.
2) I can't be sure, but I think this error is bypassed by having a perfect day. I think that the glitch only happens the day AFTER I do not have a perfect day. (i.e. at the end of a non-perfect day, at cron, going into a perfect day)
3) It looks like each of the checklist items is doing being counted separately, hence the jump from 4 to 7 with three checklist items, and the sudden change in task value from green to blue.

This really isn't a big deal; the streak counter is fixable. The change in task value isn't though, which is sort of weird, but that's okay.

**Comment by Alys** [comment]
Very interesting! Could you please look at your party page and tell me if any of the messages that describe how much damage you did/took to/from the boss are duplicated?

Also, could you paste in your [Unique User ID](https://habitrpg.com/#/options/settings/api)?

If you don't object, please tell us the text of the Daily that has the glitch. If it contains private information, is it possible to post just enough of the text that our database admin would be able to identify it, if he needs to?

**Comment by HSalgo** [comment]
Sorry for the delay; construction going on in my apartment.

There is no duplication of damage. I'm the only one on the quest right now. (My friends are in the tavern.)

UUID: 57a9ec4a-33d5-49f0-ba1c-291487983290

The task is called "Brush." I reset the steak value, but your admin should be able to see the difference in task value to verify that each of the checklist items was counted separately.

I've seen this happen with a different daily with two checklist items before I used the Orb of Rebirth, but I really didn't think much of it at the time. Those checklist items have been removed.

**Comment by Alys** [comment]
I can't replicate this on my local install (development mode lets us simulate new days rapidly). I'll try to replicate on my production site account, but that will take longer. :)

**Comment by HSalgo** [comment]
Yeah, it's sort of quirky. It's not a regular thing, so I think it might have something to do with recovering from a non-perfect day. I'm not entirely sure of the circumstances myself.

**Comment by HSalgo** [comment]
Will try to replicate the problem tomorrow--missed some dailies today. Will try to start a new quest tomorrow and hopefully get a perfect day to see what the following cron brings.

**Comment by HSalgo** [comment]
I created various tasks this time around, including one where I left the task checked/items checked, tasks checked/items unchecked, and tasks unchecked/items checked. Strangely enough, on this non-perfect day, only the daily with the task CHECKED and the items UNCHECKED incremented extra--it incremented by two instead of one. The task was checked, with two unchecked items, and today went from perfect -> non-perfect. You are free to investigate with my ID as required.

**Comment by Alys** [comment]
So it seems to be a bit random, but you are certain that sometimes when your day roll-over happens, some of your Dailies have their streak counters increased by more than one.

**Comment by HSalgo** [comment]
I am certain, yes. It only happens for dailies with checklist items, and it only appears after cron (not as I check them off during the day).

I believe it is more than just the streak counters--I think it is also that the items are being counted more than once. There are certain dailies that I always do together, and one checklist task was blue instead of green (like the others) when its daily streak counter jumped.

**Comment by HSalgo** [comment]
I wonder if it has anything to do with checking Checklist Items AFTER you check the task off?

**Comment by HSalgo** [comment]
Still can't figure it out. Any progress on your end?

**Comment by crookedneighbor** [comment]
None on our end. Are you still experiencing this bug? I'm assuming it's temporary so I'm closing this issue. Repopen if that's not the case.
