### ISSUE TITLE
Some daily and habits cant be removed

### ISSUE THREAD

**Issue by loboaureo** [HabitRPG/habitica#3992]
I've joined a challenge, after leave it, it let some dailies and habits that i cant remove

**Comment by Alys** [comment]
See "Leaving a Challenge" on the [Challenges](http://habitrpg.wikia.com/wiki/Challenges) wiki page. It describes how to fix this problem.

If for some reason that doesn't work, comment here to tell us what happened when you tried that process and what went wrong. We can then reopen this issue.
