### ISSUE TITLE
To Dos Randomly Rearranging Themselves

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3994]
I don't what is going on, but every time I refresh this evening my To Dos have randomly rearranged themselves. Stuff from the bottom of my list is at the top, stuff I have moved to the top is at the bottom. And then the next time I refresh everything rearranges itself again. It's very frustrating.

**Comment by Alys** [comment]
Duplicate: https://github.com/HabitRPG/habitrpg/issues/2606

See ["Rearranging To-Dos" in To-Do wiki page](http://habitrpg.wikia.com/wiki/To-Dos#Rearranging_To-Dos) or https://github.com/HabitRPG/habitrpg/issues/2606 for a workaround and to follow progress of this issue.

**Comment by ghost** [comment]
I'm aware of that issue actually. This is not To Dos not sticking where they are supposed to be when they are dragged. My completed To Dos are cleared. This is just random rearranging of blocks of To Dos whether I've moved anything or not.

**Comment by Alys** [comment]
Sorry about that Anysia.

Do you use the [User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) tool? If so, can you please show us a screenshot of the table from the "Task Statistics" section? There is nothing private in that section so your data won't be exposed. For example, your screenshot would look [something like this](http://gyazo.com/db794f73880212f6d7fc8d1c92260a69).

Please also tell us your [Unique User ID](https://habitrpg.com/#/options/settings/api).

**Comment by ghost** [comment]
No problem. If it's the same issue, then it's a new variation on it. I've had the other issue, but that's just things not sticking when you move them and ending up back where they were or somewhere in between as I understand it. This is entire blocks of tasks (>5) shifting from the bottom of my list to the top (it happened several times). They were all challenge tasks but I don't know if that's relevant or it's just what happened to be at the bottom of my list. Maybe overuse of 'push to top' is causing weirdness?

Anyhoodle.

My UUID is db190b28-8ce5-422e-8076-d43a62a7b204

The completed tasks that aren't cleared are challenge tasks. I don't use tag filters.

![screen shot 2014-09-07 at 13 21 22](https://cloud.githubusercontent.com/assets/6047755/4179408/214bd036-36c5-11e4-9104-8aca1493efc2.jpg)

**Comment by ghost** [comment]
For whatever reason, it seems to have stopped. Closing this unless it starts up again.
