### ISSUE TITLE
misleading Gold=>Gem conversion cap message

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#3996]
Currrently, when a subscriber buys 25 gems with gold in a month, they get this message:
"_You've reached the Gold=>Gem conversion cap (25) for this month. We have this to prevent abuse / farming, please wait until the beginning of next month._"

Could it please be changed to something like this?
"**_You've reached the Gold=>Gem conversion cap (25) for this month. We have this to prevent abuse / farming. The cap will reset within the first three days of next month.**_"

~~I've created PR https://github.com/HabitRPG/habitrpg-shared/pull/300 to add that text to locales/en/subscriber.json ("**buyGemsGoldCapReached**"), but if it can't use localisation for some reason, feel free to close that PR.~~
### Reason for change:

People in timezones ahead of the USA reach the beginning of the month several hours before the start of the process to reset the cap. I believe that process takes several more hours to run. Thus some people don't have the cap lifted until the 2nd or maybe 3rd of the month in their timezones.

There's always questions about this at the start of every month and early September had more than usual (including one overly-insistent user who took up a lot of our time and then didn't bother to say thank you after we'd helped them). Changing the message would prevent many of the questions, thus freeing up our time for other kinds of support work.

**Comment by paglias** [comment]
I van change it in a few hours, just two small notes:
- yes, we can't use localisation because the free plan on transifex is only for open source code so we don't translate text not avalaible.here
- instead of running each month a migration couldn't we add this to cron? When running cron if it's the last day of the month reset the cap

**Comment by Alys** [comment]
@lefnire or @paglias, would it be possible for the gem cap message to be changed before the end of the month? It would remove a support burden if the message more accurately indicated the timing of the cap reset. Suggested text:

**_You've reached the Gold=>Gem conversion cap (25) for this month. We have this to prevent abuse / farming. The cap will reset within the first three days of next month.**_

**Comment by paglias** [comment]
@Alys I've changed it in the private repo and mentioned @lefnire

**Comment by negue** [comment]
(Sorry I selected it) , Pls Ignore this. :smile:
