### ISSUE TITLE
Attribute values inexplicably decreased

### ISSUE THREAD

**Issue by jakeoakley** [HabitRPG/habitica#3997]
I recently noticed that some of my character attributes might have somehow decreased. I'm not entirely certain, but I could have sworn that my primary attribute (perception) was above 100, and now it's only at 89.5. I haven't died (as far as I know) or fixed/reset my character values recently, and I'm positive that I'm wearing the equipment that will give me the highest boost for that attribute.

A recent issue that may be relevant: This past weekend I went on a short trip where I didn't have access to internet on my laptop. I did bring my iPhone, however, and had access to the HabitRPG app. The trip started last Friday evening, at which point I only had two dailies left to check off. I completed and checked off these dailies later that evening. However, when I woke up the next morning, I found that those two dailies were already checked off for that day. I'm guessing that the issue was with a spotty data connection, but I have no way to be certain. Since I was worried that I would continue to have issues with dailies not registering, I decided to rest in the Inn until I got home this evening. I'm not particularly worried about this issue, but it might be helpful in figuring out what caused the drop in character attributes.

Browser: Chrome
User ID: 68b9555d-b9a5-4555-93fc-21b8e3a626d9

**Comment by Alys** [comment]
Do you normally have [Perfect Days](http://habitrpg.wikia.com/wiki/The_Perfect_Day) where you complete all your Dailies every day? If so, you're used to having the buff that comes from that. If a poor net connection prevented you ticking off your Dailies, then you lost the buff and your attributes dropped. They'll come back up when you have your next Perfect Day.

**Comment by lemoness** [comment]
Additionally, resting in the inn generally prevents you from getting a
perfect day, so that's a highly likely scenario. Let us know if this sounds
like the cause!

**Comment by jakeoakley** [comment]
That sounds like it's the issue. I was either unaware of or had forgotten about that buff. Thanks for your help!
