### ISSUE TITLE
Challenges: Assigning Location after Prize Defaults to 1 Gem

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3998]
I made a Challenge and put in the prize as 5 gems, then filled out the rest. When I clicked to save, it prompted me to choose a location for the Challenge, which I'd forgotten to do, so I clicked "Tavern" and saved again. The Challenge was created, but I was startled to find that the prize was only 1 gem. I deleted it and attempted the same process. When I set the location from the drop-down menu, the prize switched from 5 to 1. I suspect that it's defaulting the number of gems in Tavern Challenges to 1, the minimum, without checking if a number greater than 1 was already inputted. 

A minor issue, but thought I should log it, since having to remake the whole Challenge was a hassle!

---

_edit by admin, 28 May 2016:_

This still happens. If you initially select a guild/party and enter a gem prize of greater than 1 and then change the group to the Tavern, the gem prize is changed to 1.

The correct behaviour is that the prize should not be automatically changed to 1 if it is greater than 1.

If the prize is 0 and you chose the Tavern, then the prize should be changed to 1.
##

**Comment by Alys** [comment]
@lemoness, is it possible that [this is what was happening](https://github.com/HabitRPG/habitrpg/issues/3862#issuecomment-51696097)?

**Comment by lemoness** [comment]
Just checked it, and actually, I think that the issue reported there is
really the same issue as this, not related to scrolling.

First I typed in "13" for the gem prize, and scrolled up and down as I
always do. The gem prize did not change. Then I selected "Tavern" from the
drop-down menu with no other scrolling - and it instantly changed to "1."
Does the same thing happen when you try it?

**Comment by deilann** [comment]
I can confirm this has happened to me.

**Comment by Alys** [comment]
The scrolling issue definitely happens (I've observed it several times) but, yes, selecting Tavern does change the gem amount. The form seems to be designed to encourage the user to select the location of the challenge before anything else but the positioning of the drop-down makes it less likely users will do that. If it's moved to under the buttons, it will probably be used first more often. That's just a quick workaround though. A proper fix would prevent it changing the gem amount if the gem amount is >0 and would allow the gem amount test to happen even if the user selects Tavern after entering other details.

**Comment by deilann** [comment]
That was my thought exactly Alys.

**Comment by Alys** [comment]
This still happens. If you initially select a guild/party and enter a gem prize of greater than 1 and then change the group to the Tavern, the gem prize is changed to 1.

The correct behaviour is that the prize should not be automatically changed to 1 if it is greater than 1.

If the prize is 0 and you chose the Tavern, then the prize should be changed to 1.

**Comment by Ozzystrasza** [comment]
I'd like to try this fix, if it's ok.

**Comment by Alys** [comment]
@Ozzystrasza Yes, thanks!
