### ISSUE TITLE
Buy Gems from Rewards Column

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3999]
Suggested on Trello, and I thought it was a good idea - the ability for subscribers to buy gems directly from the rewards store, not just from the Market. Highly convenient when you're clicking off your tasks, and would also make that feature more obvious to users, which might lead to increased subscriptions.
##

**Comment by librarianmage** [comment]
@Alys Should this be left until after the client update?

**Comment by lemoness** [comment]
We're revamping the way the Rewards column works in the upcoming redesign, so I'm closing this.
