### ISSUE TITLE
Feature request: Weight graph.

### ISSUE THREAD

**Issue by Almao** [HabitRPG/habitica#400]
Hello,

I had an idea that I don't know if it will appeal so much people, but it would be useful for my fiancee and me and I guess some other users.

We weighs ourselves everyday (we both set it as a daily task) and I think it would be great if we could see our improvement.

Also I know some other people don't do it everyday, but maybe once a week so I guess we should be able to adjust it on some way and I guess it could be used not only for weight but maybe for other things.

Excuse my terrible english and thank you for your work.

**Comment by StanLindsey** [comment]
Honestly, thats a fantastic idea. Giving the ability to add input/stats into a task. Could be a time, a currency or a weight as you say. With the graph system we already have I think this will work perfectly. 

I've put it on [Trello](Think Stayfocusd for HabitRPG (http://habitrpg.com) and am closing this for housekeeping

**Comment by Pandoro** [comment]
I'm wondering if this could also be realized by having some integration of
some other service? Although It would be nice to have some generic graph
system which could track certain things. :)

**Comment by wc8** [comment]
@SlappyBag there seems to be an issue with the Trello link.

**Comment by elssar** [comment]
Great idea. And this could be done in such a way that other values can be tracked. A generic set unit, then every day set value interface would be awesome, and wouldn't require integration with any external service.

With this system you could track, not only weight, but things like daily spending, number of hours worked, studied, procrastinated..., number of __________ done and so on.

**Comment by Pandoro** [comment]
As this is on trello already, I will close this as SlappyBag wanted to do a while back ;)
