### ISSUE TITLE
When casting Burst of Flames on already checked Daily level up isn't triggered

### ISSUE THREAD

**Issue by cdrfun** [HabitRPG/habitica#4009]
OS: Windows 8.1
Browser: Chrome 37
UserID: a93f5665-4984-4fe6-b7bd-1d3bbf8acee1

No error in Developer Tools Console.

As you can see experience is above level-up threshold. After gaining experience through other sources the level-up takes places.

![image](https://cloud.githubusercontent.com/assets/146877/4201408/2a2c7688-381e-11e4-949e-873b52b71503.png)

**Comment by lemoness** [comment]
So this is actually a known behavior - it should be solved when you check
off any task. Let us know if it isn't!

**Comment by cdrfun** [comment]
Hi, yes when checking off a task the problem is solved. I'm sorry for creating a duplicate. I just wanted to link it here, If anybody else is having problems - but i can't find it?

**Comment by lemoness** [comment]
No worries! Sometimes it can be tough to search through the issue queue. I'm glad that the fix worked!
