### ISSUE TITLE
Feature Request : Fight someone for not doing a task

### ISSUE THREAD

**Issue by monsieurh** [HabitRPG/habitica#401]
Hey, I had a similar idea for a while but did not find time/motivation to code it. You're doing well so far !

Here is one feature I think could be fun/useful :

Mark people sharing a task with you, and then fight them for NOT doing it. 

An example is sharing "wash dishes" task with your brothers/sisters/wife/whoever-you-live-with and then fight their avatar for not doing it. The one who accomplished the task more often should have more chances to win to add some fair, though. I think habitRPG has strong enough bases to be a fair task-splitter in my family and we could have lot of fun in the process.

**Comment by wc8** [comment]
That sounds like a fun party feature to be used with [Item Sharing (includes tasks)](https://trello.com/c/5G7rcMpR) or even [Shared Task Lists](https://trello.com/c/OE6j2J8G).

How do you envision the battle working, computer wise?

**Comment by monsieurh** [comment]
Thanks for the links, but I'm completly lost with Trello, that's why I posted this here.

Computer wise I don't think it need any fancy graphic or animation. That's not the point of habitrpg.

Let's take an example of how it _could_ work: Alice, Bob and Eve share a common task (maybe through a party). Alice being tired tonight she doesn't wan't to do the task. She logs in, and use "challenge party" option on the given task. Bob and Eve would receive a notification (on next login or via mail?, it has to be discussed elsewhere) giving them the following choice: "Alice is challenging you for not doing <taskname>, do you accept her challenge and fight for the sake of lazyness?". 
Answers proposed "No fight, I'll do it" or "Let's fight"

**If the fight is taken**, the server will resolve it. If Alice wins  her challenge (over Bob & Eve), the task is considered done on her side, and any of Bob or Eve has to complete it. The resolving of the fight must take into account the frequency at which every player has already done the task (we already have this information, which is coloring the task itself in the interface). The more you did it (i.e. the greener), the better your chances to win. 

**If the fight is declined**, the player who resigned is in charge of the task. Eve doesn't want to fight, the task is considered done to Alice and Bob, but only Alice wins XP/Coins for it.

Alice is notified of each challenge as Bob and Eve make their choices. The experience points and coins earned for achieving the task are shared between the challenger and the player who makes the task.

That's just an example to illustrate my point. Ne need for a massive development here, but it could add lot of fun in my opinion.

Hope it clarifies my vison, may it be adapted in a better way.

**Comment by wc8** [comment]
Still a little fuzzy on the details, such as results of "resolving" the fight. 
Let's say, Alice challenges Bob and Eve to prove their diligence by taking out the trash.

First question, in the challenge accepted scenario: if Alice wins, do you really mean the task would be marked done for her (with XP gain, even though she didn't do it) or just that the task is simply grey (not due) for her today?

Second question, if the fight/challenge is declined: Eve has to do it, but she doesn't gain XP for doing it but Alice does? Or does Alice just gain XP and coin for winning the challenge, but Eve gains XP and gold if and when she completes it?

**Comment by wc8** [comment]
Maybe you're thinking the computer is vindicating Alice, saying she's been doing it a lot while Bob and Eve haven't been doing their fair share, so she gains XP and GP for winning the challenge?

I would suggest whoever actually does the task should gain appropriate XP and GP.
I would also suggest the winner who's gaining exemption from being required to do the task shouldn't actually have the task marked complete, just marked inactive or on hold (#243).

**Comment by ghost** [comment]
In all fairness alice and bob cannot even talk to each other...

**Comment by StanLindsey** [comment]
Why aren't they allowed to talk to eachother @Neohuman ? I'm not understanding your point.

**Comment by wc8** [comment]
Follow the link to vote for [Battle to Determine Task Assignment](https://trello.com/c/usjBm2AR). (Press "v" if the vote button is not visible.)

@monsieurh please let me know if the description there works for you or needs updating.
