### ISSUE TITLE
Cannot repurchase ALL of my old equipment

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#4013]
I used the Orb of Rebirth and I have been able to repurchase all my old equipment EXCEPT the egg shield.  I have the clover steel armor, helmet, and the carrot sword.  Please help.  I am considering how difficult it would be to make it for the costume contest.

**Comment by lemoness** [comment]
Strange - I just used Rebirth, and the Egg shield is showing up for me. Refresh, then double check to make sure it isn't in your rewards list or in your equipment. What's your UUID?

**Comment by Memry** [comment]
My user id is e495bd8b-f2f1-48e8-8f5f-9a52710999cf.  I saw the other thread
about repurchasing equipment and replied on there before I saw this
message.  (I subscribed to see the changes on this thread and somehow ended
up seeing every thread.  Oops!)

I used the orb a while back.  I'm currently at level 68 again.  I have
purchased all my equipment, except the egg shield.  I have refreshed and
cannot find it in either rewards list or in equipment.

**Comment by Alys** [comment]
The egg shield is a warrior item and you are currently a rogue, which is why you can't buy it. Clover-steel Armor is also warrior but I'm guessing you bought it before you changed to rogue at or after level 10. If you were ever to change back to warrior, you'd see the egg shield there.

**Comment by Memry** [comment]
THAT would explain it.  Thanks.  I must have had the chance to purchase it
before I reached class selection level way back when I started.  I'll
switch classes after the next equipment release, so I can get all the cool
new toys! :)  Thank you!

**Comment by Alys** [comment]
The publicly-available data that the API shows for your account (items, pets, etc) confirms that you will be able to repurchase the egg shield ("shield_special_springWarrior") if you were to change back to rogue. I.e., it's in your "owned" data with a value of "false" which is how previously purchased equipment is meant to be recorded. From what I can see, everything here is behaving as expected.

**Comment by Alys** [comment]
No worries, thanks for your reply. :)
