### ISSUE TITLE
Text error on Android

### ISSUE THREAD

**Issue by Equilibrist** [HabitRPG/habitica#4014]
When completing a multi-part task, once you check off the actual task and not the addendums, it says "A task were completed", instead of "A task was completed".

**Comment by Alys** [comment]
This happens on the unofficial Android app written by MagicMicky so it's best to contact the developer directly to ask about this. You can find contact details on the Google Play page for the app: https://play.google.com/store/apps/details?id=com.magicmicky.habitrpgmobileapp
