### ISSUE TITLE
New help menu messes with header on mobile browser

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#4015]
Chrome on an android tablet - it used to fit but now the help menu pushes the right side stuff down. 
![screenshot_2014-09-10-12-03-45](https://cloud.githubusercontent.com/assets/6208739/4220848/4bae2ad6-3904-11e4-9a6e-c12dde1afe6c.png)
##

**Comment by casicastiel** [comment]
I should clarify that this only happens in portrait orientation. Landscape is still fine IIRC.

**Comment by Alys** [comment]
There's code that causes the menu system to collapse to a single button when the screen is small enough. Now that the Help menu exists, it probably just needs to be changed to trigger at a different point.

**Comment by sbreiler** [comment]
Interestingly my old local installation w/o help menu item uses two lines too on small window (over 757px and below 947px). I should note bailey is visible. I can do a screenshot if needed.

**Comment by librarianmage** [comment]
Is this still a problem?

**Comment by crookedneighbor** [comment]
Even if it is, I'm closing this as a "won't fix" since we're starting to plan for some changes to the UI.
