### ISSUE TITLE
17,000+ Experience for One Task

### ISSUE THREAD

**Issue by sleepykit** [HabitRPG/habitica#4016]
First and foremost: I completed a task and received 17,000+ experience for completing a single task. The tasks's difficulty is "Medium". Suddenly, my level catapulted from 60 something to 329.

UID: 4b378ace-e802-4349-a2c2-7bdc07fff75a

Screenshot
![9-10-2014 12-12-15 pm](https://cloud.githubusercontent.com/assets/323871/4222830/e28a94be-3916-11e4-96a9-ef7625c4c591.png)

I checked the party I'm with, and it looks like another had a similar experience after casting Valerous Presence a whole bunch of times. 

Just FYI. It's not world ending.

**Comment by deilann** [comment]
Go to stats and tell me what it says your int is buffed by. The solution
(if the answer is a metric tonne) is to have your party members exercise
restraint when buffing.

**Comment by sleepykit** [comment]
You are correct on the metric ton: 

Strength Buff: 375518 

Thank you for pointing me in the right direction. :+1:

**Comment by deilann** [comment]
If you got a critical hit on the task that's exactly what would be expected
:)

**Comment by lemoness** [comment]
Out of curiosity, how many times did your party mate cast Valorous Presence?

**Comment by sleepykit** [comment]
I counted 132 times.

**Comment by lemoness** [comment]
.....Yeah, I think we can close this issue.

If you or your party mate would like to set your levels/stats back to what
they were before, you can use Settings > Site > Fix Character Values. For
the future, you can have a discussion with your friend about the famous
quote from Burns (paraphrased in English):
"The best-laid schemes of mice and men
Go oft awry,
And leave us nought but grief and pain,
For promised joy!"

**Comment by lemoness** [comment]
If anyone thinks that there is still a balance issue that we should address, let me know and I'll reopen it! :)
