### ISSUE TITLE
Feature Request: Change Password/Email settings

### ISSUE THREAD

**Issue by kalmduck** [HabitRPG/habitica#402]
Shortly after I set up my HabitRPG account, I forgot my password and had to reset it with the system password reset.  Now I'm stuck with a password that is difficult for me to remember and no apparent way to change it...

Additionally, would it be possible to add the ability to change my email address to allow me to sync to-dos with my google calendar that I actually use.

**Comment by wc8** [comment]
This would also be helpful for when users change their email address and no longer have access to that account. 
Vote here for [Password/Email Reset Options](https://trello.com/c/9nwlCiXs)

**Comment by horusofoz** [comment]
Closing ticket as user request has been moved to Trello for voting and discussion.

**Comment by logankoester** [comment]
:thumbsup:
