### ISSUE TITLE
Swagger UI member query missing parameter

### ISSUE THREAD

**Issue by townimbecile** [HabitRPG/habitica#4020]
On swagger UI, try to query a member by id. Oh wait, the interface only lets you send the GET without a parameter. Predictably, the server responds with an error.

**Comment by negue** [comment]
You could add this field easily, see:

https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv2.coffee#L352

**Comment by Alys** [comment]
Cannot replicate. Closing.
