### ISSUE TITLE
Scroll down produces strange pop motion

### ISSUE THREAD

**Issue by Aloriellelyn** [HabitRPG/habitica#4023]
Tested on Chrome (v37.0.2062.120) and Firefox (v31) on Windows 7

When I scroll down in either browser, the first moment of scrolling causes a sudden substantial scroll down instead of a smooth scroll down.

It appears to jump over the entire section where we can setup new To Dos or Dailies.

The motion makes for unpredictable mousing, is quite jarring visually, and feels glitchy as a result. Also, the slightest touch of the mouse wheel means one has no access to adding new To Dos. Without careful scrolling, I can easily jump right over the first entry in each of my lists.

First image: Not scrolled down
![habitrpg pop motion bug normal](https://cloud.githubusercontent.com/assets/8743442/4243727/d0929156-3a12-11e4-9d5a-cee5adc5c2d4.jpg)

Second image: Scrolled down a tiny hair. You can see that my scroll bar is nearly in the same location as the previous picture.
![habitrpg pop motion bug tiny scroll down](https://cloud.githubusercontent.com/assets/8743442/4243730/d748c254-3a12-11e4-92de-5d27dbfcdf79.jpg)

**Comment by Alys** [comment]
Now that you've mentioned it, I've realised I have that problem too. It seems to be related to this change: https://github.com/HabitRPG/habitrpg/commit/62361b6c3bc1bbd5d39fc0e71bcbad264870eae0
On my local install, when I remove that change, scrolling is smooth again.

@negue, would you like to look into this? It would be nice to keep your scrollbar fix if there's some way of stopping it from causing the jump. :)

**Comment by negue** [comment]
Oh my .... this is some strange bug, yes I'll look into this.

**Comment by negue** [comment]
Well, my height: auto fix won't work with that ... too bad.

I tried to change "in-browser" my css to:

``` css
.sticky-wrapper {
    height: 200px !important;
}
```

with that the scrolling seems to work.

@Alys could you test this locally? If not I'll test & push it after work.

**Comment by Alys** [comment]
It fixes both problems for me, although 205px looks a bit better (slight gap between tags and scrollbar)

**Comment by negue** [comment]
Okay so with 205px, the Party Scrollbar is fully useable?

(I don't have a party online xD, so I couldn't test that ^^)

**Comment by Alys** [comment]
Yup, it's good. I say commit.

**Comment by negue** [comment]
I think it should have been 215px, with 205px I can only use the top 3 px of the scrollbar inside Firefox / Windows.
