### ISSUE TITLE
API returns 500

### ISSUE THREAD

**Issue by kimifish** [HabitRPG/habitica#4025]
Hi. Need some python automation in adding tasks, but can't get with API.
Here's my code:

``` python
#!/usr/bin/python3
import sys
import urllib.request
import urllib.parse
import time

headers = { "x-api-key":    "00000000-0000-0000-0000-000000000000",
            "x-api-user":   "00000000-0000-0000-0000-000000000000",
            "Content-Type": "application/json"
            }

repeating_periods = [1, 14, 70]

task_name='Do the following: '
for next_arg in sys.argv[1:]:
    task_name += next_arg + " "

api_url = "https://habitrpg.com:443/api/v2/user/tasks"
methods = { "priority":     "1",
            "completed":    "false",
            "type":         "todo",
            "text":         task_name
            }                                               
for current_period in repeating_periods:
    methods["date"] = time.strftime('%m/%d/%Y',time.gmtime((time.time()+current_period*24*3600)))
    urldata = urllib.parse.urlencode(methods)
    #print(urldata)
    urldata = urldata.encode('utf-8')
    req = urllib.request.Request(api_url, urldata, headers=headers)
    RTM_response = urllib.request.urlopen(req)
    req_answer = RTM_response.read().decode('utf-8')
    print(req_answer)
```

This code always returns HTTP 500, dunno why.. 
Please help)

**Comment by negue** [comment]
I'm no python pro.

But from looking at this code I found 2 things.
1. Do you using a GET / POST HTTP-Call? Can't determine what urllib.request.Request does
2. If POST, you need to put the Task-Data as POST-Content in JSON and not as URL-Params

**Comment by me-and** [comment]
Yeah, this isn't a bug: the request body you're sending will look something like the below (URL encoded string):

```
priority=1&text=Task+text&completed=false&type=todo
```

It should, instead, look something like the below (JSON data):

```
{"priority": 1, "text": "Task text", "completed": false, "type": "todo"}
```

You can get this with the following code:

```
import json
task_name = 'Task text'
body = { "priority":     1,
         "completed":    False,
         "type":         "todo",
         "text":         task_name
         }
encoded_body = json.dumps(body)
print(encoded_body)
```

**Comment by me-and** [comment]
[Kinda advertising]

Alternatively, I'm creating a Python3 module for interfacing with the HabitRPG API myself. It's currently alpha quality*, but it's available at [me-and/HabitRPG](https://github.com/me-and/HabitRPG); you'll also need the `requests` module to use it. To do what your code is trying to do, you'd do something like the following:

```
import sys
import datetime
import habitrpg

API_USER = "00000000-0000-0000-0000-000000000000"
API_KEY = "00000000-0000-0000-0000-000000000000"

hrpg = habitrpg.HabitRPG()
user = habitrpg.User(hrpg, API_USER, API_KEY)

for period in 1, 14, 70:
    habitrpg.Todo.new(user,
                      title='Do the following: ' + ' '.join(sys.argv[1:]),
                      priority=1,
                      due_date=datetime.datetime.now() + datetime.timedelta(days=period))
```

\* By "alpha quality" I mean the interfaces exposed by the module are liable to change, and it's nowhere near as feature complete as I'm hoping it will be.

**Comment by negue** [comment]
Great now there is a Python API ! :).

I close this, because it is not an issue with the API.

**Comment by kimifish** [comment]
Thank you for help, me-and! And special thanks for the module
