### ISSUE TITLE
App Not Sycing

### ISSUE THREAD

**Issue by eglove** [HabitRPG/habitica#4027]
I've been having a really frustrating syncing issue with the android app. I've got a few dailies I do before bed and I'll check them off, wait until the little gear icon stops moving/goes away (I assume this means it's syncing?) But the next day I've always lost HP and sync points as if that never happened.

It's always my last two tasks at around 10-11pm. I know it's not a time issue because the other tasks don't reset and the last two aren't complete the next day.

Is there possibly:
1. A manual sync that actually confirms everything is good?
2. A way to go back and fix the incorrect missed dailies?

**Comment by lemoness** [comment]
Yikes, sorry about that! The good news: you can restore your stats by going
to the website and selecting Settings > Site > Fix Character Values; you
can also restore streaks under Task Edit.

On the iOS app, you can manually sync the app by holding down your thumb
and pulling down. Can an Android user confirm that this is how you sync on
Android?

**Comment by eglove** [comment]
Oh good, I fixed the values and yes, you can refresh by holding down and dragging down. Thank you! :+1:

**Comment by lemoness** [comment]
No problem! Glad that helped :)
