### ISSUE TITLE
Can only create one Habit, Daily, or To Do without restarting browser

### ISSUE THREAD

**Issue by NinjaOtt3r** [HabitRPG/habitica#403]
I can create one Habit, Daily, or To Do at a time (One of each). I have to quit and reopen the browser (in my case Safari) to add another one. Even just closing the page and reopening wont work.

**Comment by wc8** [comment]
What happens after you add the first habit? 
Did you try refreshing/reloading the page (CMD+R or CTRL+R or F5)?

**Comment by NinjaOtt3r** [comment]
After adding the first it is fine, it doesn't go away or anything I just can't add a second one. Tried refreshing, even closing window then going back to it, but can't add another habit until closing. Same for other two I can add one of each but then I have to quit If I want to add any more.

**Comment by horusofoz** [comment]
@NinjaOtt3r Can you provide your operating system (Windows, OSX, iOS) and Safari version? Also how are you connecting to the Internet?

**Comment by NinjaOtt3r** [comment]
OSX  Safari 6.0.2 (and if I understood that last part correctly) Wifi Sorry for taking so long to respond.

**Comment by NinjaOtt3r** [comment]
Been about a week since I've been on this issue post, but the problem seems to have escalated. I can now no longer add anything. Not habits, dailies or goals. Restarting the browser, or refreshing does nothing. Thanks for the responses. I also tried it on my iPod, can't add anything just get loading symbol across top.

**Comment by lefnire** [comment]
i upped to critical, will try to replicate. Is @NinjaOtt3r the only on experiencing?

**Comment by Pandoro** [comment]
For me the site has been remarkable stable today, I pretty much got around
without refreshing at all. About 4 days back it was pretty much the same
was as NinjaOtt3r described it earlier, but never as bad it now seems to be
:(

**Comment by horusofoz** [comment]
When accessing HabitRPG behind my work's locked down proxy I often have to
refresh. 2-3 times an hours but on a clean connection like at home Maybe
once 2-3 times a day after leaving the tab open all day. Haven't had to
close and restart the browser as yet. Chrome/Win7/WinXP

@NinjaOtt3r Do you have any addons installed in your browser?

**Comment by NinjaOtt3r** [comment]
I forgot to mention in my last comment that the second worse problem appeared shortly after my post about my OS. Maybe a week ago.

**Comment by NinjaOtt3r** [comment]
Sorry! Missed the "Do you have any addons installed in your browser?" Safari has "Extensions" I have the Duck Duck Go Extension.

**Comment by horusofoz** [comment]
@NinjaOtt3r Though it should not be related, can you disable the addon, log
out of Habit, clear your cache, close Safari, re-open, log back in and test?

**Comment by NinjaOtt3r** [comment]
Once again, sorry for the delay. Tried it, didn't work.

**Comment by rixx** [comment]
It's been some time - do you still experience this problem, @NinjaOtt3r?

**Comment by NinjaOtt3r** [comment]
I don't experience the problem any more. Not on my computer or my iPod. It started working with the change of the way to add them.

**Comment by rixx** [comment]
Might aswell close the issue, then. :)
