### ISSUE TITLE
Misspelling in german translation (morgenDs)

### ISSUE THREAD

**Issue by s-ol** [HabitRPG/habitica#4031]
The tag "in the morning" is spelled out as "morgends" but should be **"morgens"** on the german page.

**Comment by s-ol** [comment]
Fixed by https://github.com/HabitRPG/habitrpg-shared/pull/310

**Comment by Alys** [comment]
Thank you for the report about the problem. However, Translations are managed at Transifex and so your pull request unfortunately can't be accepted - if it was, your change would be overwritten the next time the translations were pulled in from Transifex. You can read more about the process at https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/README.md

@paglias : Should we copy that README file to each of the language subdirectories (except en)? I think it's more natural for translators to pay attention to files in their own language directory, and it's being missed often in its current location. Would this interfere with the Transifex process? It's a bit of a disadvantage to have the same file in multiple locations, but I think in this case it's warranted.

**Comment by s-ol** [comment]
Oh, I should've read that README passing through. My fault ^^

**Comment by Alys** [comment]
@S0lll0s It's a common mistake. :) I'm actually reopening this so that we don't forget to discuss copying the README file into each subdirectory, where it will be more obvious. You can probably ignore all updates to this now; you should be able to unsubscribe to them with a button on the right-hand side of the page, if you want to.

**Comment by Alys** [comment]
Closing now that I've done a PR for putting README's in all non-en locales directories
