### ISSUE TITLE
To Do List Organization

### ISSUE THREAD

**Issue by andieSCREAM** [HabitRPG/habitica#4032]
Whenever I try to reorganize my to do list the items on it randomly change order and the one item I tried to move doesn't move at all. Sometimes it does work, but only if I move the items short distances, no more than 2 or 3 lines up, never down. But even so, despite the fact that it does the saving motion (the blue bar on the top) it isn't saved upon refreshing.

I'm on google chrome and my user ID is e7becec1-61ec-49e3-8c23-98a9ef9dc24e

**Comment by Alys** [comment]
Duplicate: https://github.com/HabitRPG/habitrpg/issues/2606

See ["Rearranging To-Dos" in the To-Do wiki page](http://habitrpg.wikia.com/wiki/To-Dos#Rearranging_To-Dos) or https://github.com/HabitRPG/habitrpg/issues/2606 for a workaround and to follow progress of this issue.
