### ISSUE TITLE
to-do's wont go away

### ISSUE THREAD

**Issue by thrappstead** [HabitRPG/habitica#4036]
i complete my to-do's but they wont go away after i click them. so many bugs with this site, hope they can be fixed because its unusable at the moment for productivity

**Comment by deilann** [comment]
Please give more detailed information such as what you are doing exactly
when this happens along with screen shots.

**Comment by thrappstead** [comment]
I click the to-do cause I completed it and then like 5 seconds later it comes back like I never clicked it

Cpl Hrappstead, Trent
Medical technician, 17 Fd Amb
Trent.Hrappstead@gmail.com
(c) (204)297-2408

**Comment by deilann** [comment]
Please include screen shots. Do all To Dos do this or just some?

**Comment by thrappstead** [comment]
All as far as I know 

Cpl Hrappstead, Trent
Medical technician, 17 Fd Amb
Trent.Hrappstead@gmail.com
(c) (204)297-2408

Cpl Hrappstead, Trent
Medical technician, 17 Fd Amb
Trent.Hrappstead@gmail.com
(c) (204)297-2408

**Comment by deilann** [comment]
Again, can you please include screen shots? Do you always make sure to wait
for the blue bar to finish before taking any other action on the page?

**Comment by thrappstead** [comment]
it just shows it the same as normal but here is word doc with a screen shot

On Sun, Sep 14, 2014 at 2:45 PM, deilann notifications@github.com wrote:

> Again, can you please include screen shots? Do you always make sure to
> wait
> for the blue bar to finish before taking any other action on the page?
> On Sep 14, 2014 12:39 PM, "thrappstead" notifications@github.com wrote:
> 
> > All as far as I know
> > 
> > Cpl Hrappstead, Trent
> > Medical technician, 17 Fd Amb
> > Trent.Hrappstead@gmail.com
> > (c) (204)297-2408
> > 
> > Cpl Hrappstead, Trent
> > Medical technician, 17 Fd Amb
> > Trent.Hrappstead@gmail.com
> > (c) (204)297-2408
> > 
> > > On Sep 14, 2014, at 2:33 PM, deilann notifications@github.com
> > > wrote:
> > > 
> > > Please include screen shots. Do all To Dos do this or just some?
> > > On Sep 14, 2014 12:22 PM, "thrappstead" notifications@github.com
> > > wrote:
> > > 
> > > > I click the to-do cause I completed it and then like 5 seconds later
> > > > it
> > > > comes back like I never clicked it
> > > > 
> > > > Cpl Hrappstead, Trent
> > > > Medical technician, 17 Fd Amb
> > > > Trent.Hrappstead@gmail.com
> > > > (c) (204)297-2408
> > > > 
> > > > > On Sep 14, 2014, at 2:04 PM, deilann notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > Please give more detailed information such as what you are doing
> > > > > exactly
> > > > > when this happens along with screen shots.
> > > > > On Sep 14, 2014 11:57 AM, "thrappstead" notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > > i complete my to-do's but they wont go away after i click them.
> > > > > > so
> > > > > > many
> > > > > > bugs with this site, hope they can be fixed because its unusable
> > > > > > at
> > > > > > the
> > > > > > moment for productivity
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/HabitRPG/habitrpg/issues/4036.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/HabitRPG/habitrpg/issues/4036#issuecomment-55536252>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4036#issuecomment-55536829.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4036#issuecomment-55537006.

## 

Trent Hrappstead
Cpl Hrappstead
11 CF Health Svcs C Shilo, Medical Technician
1(204) 297-2408
Trent.Hrappstead@gmail.com

**Comment by deilann** [comment]
You can upload photos directly to github. I can't open a word document on
my phone. Also, can you please answer my last question?

**Comment by Alys** [comment]
@thrappstead, when you attach documents to a GitHub email reply, they don't appear on GitHub nor in the email that we receive. Can you please go to this GitHub ticket and drag the images into a new comment? Please do just the images, not a document.

When you tick off a To-Do, you'll see a thin blue bar appear at the top of the screen and travel from left to right, and then disappear. Wait until it has disappeared before you take any other action. I.e., tick off just one To-Do, wait for the bar to disappear, and then tick off another. Does that help? If you take too many actions too quickly, then you get sync errors and your actions aren't registered properly.

**Comment by Alys** [comment]
Please also tell us your User Id by pasting into this issue as plain text. See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

**Comment by thrappstead** [comment]
![image](https://cloud.githubusercontent.com/assets/6386084/4265515/bc41c350-3c53-11e4-81f8-9abdc0393f12.png)

I waited then clicked on another and the first came back

**Comment by thrappstead** [comment]
f90dc4e7-cce6-4b83-a138-936e0621e550

**Comment by Alys** [comment]
@lefnire Can you please look at the user data for f90dc4e7-cce6-4b83-a138-936e0621e550 to see if there's something wrong with it? Completed To-Dos keep being unticked (doesn't seem to be from sync errors) and there's a Reward in the Habits column.

**Comment by Alys** [comment]
Somewhat late - sorry @thrappstead - but I've removed the Reward from the Habits column and got rid of the duplicate tasks that were causing the completed To-Dos to reappear. I realise you haven't logged in to HabitRPG for a while, so you don't need to reply here if you don't want to. I'm closing this now, but if you still have problems, post here and we'll reopen it.
