### ISSUE TITLE
Task created by third party

### ISSUE THREAD

**Issue by mchlwgnr** [HabitRPG/habitica#4037]
A new habit just showed up, and when hovered over it it said it was created by a third party (screen shot included). Is this a bug? Is there a vulnerability?

![image](https://cloud.githubusercontent.com/assets/3712512/4266146/9483880a-3c74-11e4-89fc-00870ed33def.png)

Michael

**Comment by Gaelan** [comment]
It's a bug: #1402

**Comment by Alys** [comment]
It's a safe bug though. No harm has been done to your account. You can delete that Habit.

**Comment by mchlwgnr** [comment]
Thanks!
