### ISSUE TITLE
Duplicate attacks against quest boss

### ISSUE THREAD

**Issue by me-and** [HabitRPG/habitica#4038]
When my cron runs, I often (but not always) see two attacks against the quest boss my party is currently attacking.  For example:

> ```
> cygnoir casts Blessing for the party. -2 days ago+1 
> me_and attacks The Laundromancer for 8.8 damage, The Laundromancer attacks party for 4.0 damage. -2 days ago+1 
> me_and attacks The Laundromancer for 8.8 damage, The Laundromancer attacks party for 4.0 damage. -2 days ago+1 
> Haldamir casts Ethereal Surge for the party. -2 days ago+1 
> ```

This seems to have started about a week ago, after I checked out of the tavern. Of the past seven attacks, five have been doubled up, always with identical damage for both attacks.

It doesn't affect anyone else in my party, and other party members have confirmed they see the double attacks in the party log.

In case it's relevant, I have a custom day start of 06:00.

My user ID is `1186f4a9-a39c-4448-bc18-1c4e00e818bc` and the party group ID is `3e7f3670-d7a0-4685-a1c4-a987e964dbbf`.

**Comment by lemoness** [comment]
This has been happening to one of my party mates as well, actually, a few
times over the last battle. Devs, let me know what info you'd like about
his account.

**Comment by thepeopleseason** [comment]
This happened to me a few weeks ago, but when I used both beta.habitrpg.com and habitrpg.com in the morning and I believe both somehow ran cron.

**Comment by Alys** [comment]
The primary issue for this problem is https://github.com/HabitRPG/habitrpg/issues/2805 and I've made a note in it about this one.
