### ISSUE TITLE
Stats do not add correctly

### ISSUE THREAD

**Issue by townimbecile** [HabitRPG/habitica#4039]
I don't know whether this has to do with having a very high level. I think I see this on my lower level party members, too. Just take a look: my constitution, for example, should pretty clearly be 107.5.

Strength: 165  
Level: 57.5 
Equipment: 60 
Buffs: 50 

Intelligence: 253  
Level: 57.5 
Equipment: 37 
Allocated: 116 
Buffs: 50 

Constitution: 100  
Level: 57.5 
Buffs: 50 

Perception: 128 
Level: 57.5 
Equipment: 25 
Buffs: 53

**Comment by thepeopleseason** [comment]
I believe level bonuses should cap-out at 50. It's doing so in the calculation, but not in the display. See #3682

**Comment by townimbecile** [comment]
I thought about that. That explains my Int, Con, and Per. What about my Str?

**Comment by Alys** [comment]
fixed in #5626 (included in #5642)
