### ISSUE TITLE
Things give different amounts of XP

### ISSUE THREAD

**Issue by NinjaOtt3r** [HabitRPG/habitica#404]
I'm sorry for the lacking title. Checking a daily gives one level, but un checking takes away .9 (or so it was at first) but checking and unchecking more gives seemingly random values and the XP can go up just but checking and unchecking one.

**Comment by StanLindsey** [comment]
This is a known bug but is low on our priority list as anybody who would actually want to cheat would just use habits over unchecking/checking todos &dailys. Its alot more efficient to cheat that way =P

**Comment by horusofoz** [comment]
Closing as user advised this is a known issue which will be looked into in the future.
