### ISSUE TITLE
Friends suggest optional tasks

### ISSUE THREAD

**Issue by gabrielqmatos88** [HabitRPG/habitica#4041]
would be nice if friends could suggest tasks for us, and we could accept or decline.

**Comment by lemoness** [comment]
Have you explored the Challenges feature? You can do just that. For example, I recently created a private Challenge for my roommate that included all the things we wanted to make together. She accepted it, and now her To-Do list includes items like "make boba" and "pickle carrots."

For more information about Challenges, please read this page on the wiki :) http://habitrpg.wikia.com/wiki/Challenges

I hope this helps!
