### ISSUE TITLE
Quest owner kicked from quest every time it starts.

### ISSUE THREAD

**Issue by Imbecamiel** [HabitRPG/habitica#4042]
I've been buying and starting quests for my party for a while without any issues. A couple members are inactive over the summer, so as soon as the active ones accept I click "begin" and things roll along as expected.

I just bought the Hedgebeast quest, though, and now every time I click "begin" I get a message that the quest's owner has left the party. I'm not doing anything that I haven't been before, so I have no idea how this is happening or why I'm getting kicked from the quest. I really don't want to run a quest when I'm not even going to get to participate, though. :/

**Comment by Alys** [comment]
Do you also see that the participant list is empty? Try reloading the page. That should repopulate the list and remove the erroneous message. I think there's already a fix underway for this.

**Comment by Imbecamiel** [comment]
Hmm, yeah, I don't think there were other participants showing up either, but I did try reloading (because I thought it might be just a temporary glitch) and it didn't seem to help.

**Comment by Alys** [comment]
Reload again and wait for the page to load fully (might take five or so seconds at worst). Is the participant list fully populated now? Are you marked on it as the quest owner with an asterisk?

**Comment by bordersend** [comment]
This is happening in my party as well now. 

Someone starts a quest. It appears normal until anyone accepts it. We then start getting the following error: The quest owner has left the party and can no longer begin the quest. It is recommended that you cancel it now. The quest scroll will be returned to the quest owner.

The participant list is empty with a string of "Pending" statuses just hanging out.

The message goes away with a refresh and the participant list refills, though I'm waiting for everyone to accept to see if we can actually still start the quest.

**Comment by Alys** [comment]
It's just a temporary display problem. The quest will work correctly. Refreshing the page should fix the message.

**Comment by Imbecamiel** [comment]
I've just gotten everyone to re-accept and reloaded everything, and it does look like it's showing up right now. So, barring any problems that might show up once we start to do damage, it does look like just an issue with the way it displays, rather than something that'll keep the quest from running properly once it's started.

**Comment by aein** [comment]
This is happening to me as well.

"Someone starts a quest. It appears normal until anyone accepts it. We then start getting the following error: The quest owner has left the party and can no longer begin the quest. It is recommended that you cancel it now. The quest scroll will be returned to the quest owner."

We just had 4 quests canceled and restarted because of this lol. I told everyone not to cancel and to refresh so hopefully it won't keep happening.

**Comment by Alys** [comment]
A fix for this has just been merged (https://github.com/HabitRPG/habitrpg/pull/4010) and it will probably go live in the next few days. In the meantime, keep in mind that this is only a bug in the display of the quest, not in the quest itself, and reloading the page fixes it (except of course in the very rare cases where the quest owner really has been kicked out of the party by the quest leader).
