### ISSUE TITLE
Used Orb of Rebirth, can't complete tasks

### ISSUE THREAD

**Issue by thandle** [HabitRPG/habitica#4046]
I can create new tasks/dailies/habits.

When I click a habit, the color changes but no gold is given/health taken away. When I refresh/sync, the color returns to yellow.

When I click to complete a task, the task disappears but no gold is awarded. When I refresh/sync, the task returns uncompleted.

Items in checklists stay checked/unchecked through refreshes/syncs.

**Comment by Mixtercasual** [comment]
This same thing happened to me today. I'm level 1 and can't do anything now.

**Comment by Alys** [comment]
This was a recent change to Rebirth:
https://github.com/HabitRPG/habitrpg-shared/pull/307/files

I'm guessing this line might be causing the problem?
https://github.com/Alys/habitrpg-shared/blob/99e4f9b458e814b9e83411baaf295a18c6c8f99b/script/index.coffee#L498

I'm about to send a reversion for that. It will stop buffs being wiped on rebirth but that's less important.

**Comment by Alys** [comment]
@thandle and @Mixtercasual : Can you please paste in your Unique User ID (UUID), which you can find from [Settings -> API](https://habitrpg.com/#/options/settings/api)?

**Comment by thandle** [comment]
7eddf7e5-3f5a-4b36-8d0d-8a90f2d7cc2a

And it seems to be working now, thanks!

**Comment by Alys** [comment]
Wait, what?? :) I did nothing that could have helped that quickly. :)  Can you tell me please if you are aware of anything you did that might have made a difference? Perhaps logging out and back in? Or anything other than the normal actions of ticking off tasks?

**Comment by thandle** [comment]
I did log out and back in, but I did that a few times yesterday and that didn't fix it. This was my first time trying today, maybe the nightly rollover (resetting dailies and whatnot) reset some variable that orb of rebirth changed?

**Comment by Alys** [comment]
Ah cron (the nightly roll-over), yes, that could well have been it. Which, if true, is an enormous relief because it means no one will have to suffer through this for more than a day (unless they're Resting in the Inn). I'm sorry about that first day though! I realise how annoying it must have been to have none of your actions registering. :(

**Comment by thandle** [comment]
No worries! Thanks for all your help :)

**Comment by Mixtercasual** [comment]
7ffc7c96-b7db-4f30-86fd-9c37eb251aea is my ID.
I tried logging out and back in, but it's still not working. My first day hasn't ticked over yet, so that might be it?

**Comment by Alys** [comment]
@Mixtercasual , yes, when your first day roll-over happens, the problem will be fixed. Sorry about the delay.

**Comment by Alys** [comment]
A fix for this was pushed out a few days ago.
