### ISSUE TITLE
Won't reset dailies

### ISSUE THREAD

**Issue by kinoida** [HabitRPG/habitica#4047]
My "dailies" tasks stay checked although scheduled for each day of the week. 
(user ID 59e213c9-b4d8-41af-9b40-f890fbe92897 )

**Comment by Alys** [comment]
Thanks for including your UUID. That let me check your account and I can see that it's happening because you're Resting in the Inn. You can learn more about that, and how to check out of the Inn here: [Tavern](http://habitrpg.wikia.com/wiki/Tavern)
