### ISSUE TITLE
Tasks giving 0 rewards after rebirth

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#4048]
I accidentally used an Orb of Rebirth while my XP was over the limit for leveling up. (In other words, I had more than 1070/1060 XP at Level 47, for example.) Now that I've used the Orb of Rebirth, everything seems broken--I can check tasks off, and see that they're doing damage (e.g. with Habits), but I'm not receiving any XP or gold rewards. Do you happen to know what's going on? =/

Thanks a bunch! Sorry for breaking... well, everything.

**Comment by HSalgo** [comment]
As a note, I also tried to mess around with the Character Values, but altering those doesn't change the issue. I'm going to try logging out and logging back in.....

**Comment by HSalgo** [comment]
Nope. Didn't work. Oof, feel sort of silly for using the Orb without checking first.

**Comment by deilann** [comment]
That's not the issue. Check out

https://github.com/HabitRPG/habitrpg/issues/4046

One cron will fix it.

**Comment by HSalgo** [comment]
Yeah, I just checked--it seems as if all of my stats are currently listed as "undefined," which is probably one of the issues producing the lack of task rewards. The weird thing is that changing my level to a higher one (e.g. 2) doesn't unlock other  features--I was hoping that I could buy a sword to fix my stats, but it looks like I'll just have to wait for the next cron.

Thanks a bunch!

**Comment by lemoness** [comment]
Since this is a duplicate, I'm closing this - feel free to chime in on the other thread!
