### ISSUE TITLE
Suddenly died... again

### ISSUE THREAD

**Issue by Nostrocker** [HabitRPG/habitica#405]
Hey, had another random sudden death. I think I maaaayyy have found some kind of correlation though. Both times it happened at work, and both times it happened after I opened up firefox that was reopening old tabs where I had been logged in to habitrpg. Maybe there's some sort of time confusion if the page is saying I haven't been there for several days and applies all my undone dailies? I have no idea if that's logical, but it's the only correlation I can find. Although that may not make sense becuase I don't think I had enough dailies to kill me since the last time I was on firefox, unless I didn't refresh that page and it loaded the old one again. 

If I get my stuff back again that would be awesome! Nostrocker, a872a846-5e4e-48a4-9512-e030d13e5b3c. Leather and gold sword and whatever else you feel like throwing in there.

**Comment by DDzwiedziu** [comment]
Last week took some hits due to sickness, but leveled. Had about 46 HP yesterday.  Today I open hRPG, and I'm dead, everything lost. I even don't know what hit me.
Login "Dzwiedziu".

**Comment by Nostrocker** [comment]
I replicated the bug today, I'm assuming it's the time stamp of the saved page or something. 

I normally use chrome, but I logged in through firefox in the past. Firefox opens up tabs from last session when I run it, and one of those is habitRPG. Any time I open firefox now I instantly die... Pretty much what I said last time, but now I'm a little more confident having replicated it.

**Comment by Pandoro** [comment]
@lefnire This seems pretty bad. Any thoughts? Could it be firefox registers the multiple day changes since the time the tab was open and then it counts all of those -> Many things will not be checked -> death ?

**Comment by DDzwiedziu** [comment]
I confirm the time checking - the Firefox witch killed me wasn't opened for nine days.

**Comment by switz** [comment]
Just repro'd this bug. Working on it.

**Comment by lefnire** [comment]
Hey guys, I'm gonna fix you all up as soon as we get #427 and fixed

**Comment by lefnire** [comment]
Ok, #427 is fixed, and that should be what caused this issue. If anyone is still experiencing this, re-open. If anyone wants me to restore their accounts to any particular stats, [email me](mailto:tylerrenelle@gmail.com) your user id and what stats you want back (50 hp, 30 exp, lvl 3, gold sword, leather armor, etc)

**Comment by JacquelineChoo** [comment]
Hi there! I too suddenly died when I opened Firefox in Windows 7. I had tabs from my last session, but I don't know when I last opened firefox. I'm guessing it was at least 3 days ago. 

I will email you to request for an account restore. Thanks in advance Lefnire :)

**Comment by lefnire** [comment]
Hey @dirged , use https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#restoring-your-avatar-stats-items-accidental-death-etc to restore your account for now. Let's follow up on the particular bug at https://github.com/lefnire/habitrpg/issues/700
