### ISSUE TITLE
Wolf egg + desert potion = Turkey?

### ISSUE THREAD

**Issue by rabidredfox** [HabitRPG/habitica#4050]
When combining random drops of wolf egg and desert potion, the result is somehow a turkey.
![screenshot - 09162014 - 06 45 41 pm](https://cloud.githubusercontent.com/assets/8800262/4297450/7f0deecc-3e0c-11e4-8c41-9502bf549221.png)

The mouseover is pictured.

**Comment by deilann** [comment]
Refresh. The graphics get.scrambled when new content is added.

**Comment by rabidredfox** [comment]
After the first refresh everything changed to a very buggy looking screen where my avatar was something completely different.  Unfortunately didn't screenshot before I did a second refresh and everything was back to expected conditions.

Browser:  Iceweasel 24.8.0
User: loveless

**Comment by deilann** [comment]
No need to show us a second screenshot. This happens whenever the
spritesheet is changed. It's kind of inevitable.

**Comment by lemoness** [comment]
Everything is back to normal with refreshing, so I'm going to close this ticket :) Let us know if refreshing no longer works!
