### ISSUE TITLE
Guilds list is too wide in FF

### ISSUE THREAD

**Issue by Katzen-Gott** [HabitRPG/habitica#4051]
Hi. I use FF32 on KUbuntu and Mac.
And in both my Firefoxes, on https://habitrpg.com/#/options/groups/guilds/public guilds list (table class="table table-striped ng-scope") is gone beyound right window border. Seems that it should be placed below the search-box (div class="col-md-3 ng-scope"), but somehow it's placed to the right of the search-box.

**Comment by negue** [comment]
I'm already on it, to find a good solution :)

**Comment by Katzen-Gott** [comment]
Why not "clear:left" the table? I've just checked with stylish plugin and it actually works.

**Comment by negue** [comment]
Thx, good catch, yes with `clear:left;` it seems to work :) 

Now only some margin on the search inputbox is left and then this will fix it :)

I'll test other browser sizes, If this could break something else.

**Comment by negue** [comment]
On the next update, the guild list will look like this: 

I removed the col-md-3, because it doesn't sense If the Guild is beneath it.

![habitrpg_guild_list](https://cloud.githubusercontent.com/assets/842273/4324578/1186d76e-3f5c-11e4-82b6-14f0dc189178.PNG)
