### ISSUE TITLE
Burst of flames does not trigger level up when reaching experience needed for next level

### ISSUE THREAD

**Issue by betyplush** [HabitRPG/habitica#4052]
When using the wizard power burst of flames, you will gain experience, sometimes enough so that you would level up. However, the leveling up does not trigger when it should when using burst of flames; another experience-gaining task must be marked completed before the level up will trigger.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2143

You can subscribe to that issue if you would like to receive notifications every time it is updated.
