### ISSUE TITLE
Won challenges invisible in stats

### ISSUE THREAD

**Issue by DebsJS** [HabitRPG/habitica#4053]
My Stats page is not showing the challenges that I have won under "Was the winner in the following challenges". From some places when I have clicked my name there has been a single challenge shown, usually none. I have won a few, so not sure why there would be one or none. User ID: 09f81fc2-ddfd-4397-af24-15079a703e60

**Comment by Alys** [comment]
You say "From some places..." - can you tell us which places this happens in? Are there other places where the challenges do appear correctly?

When only one challenge is shown, is it always the same one? If so, which one?

**Comment by deilann** [comment]
@Alys I have not been able to see any challenges won by this user
(Wunderkind) in their profile modal. But I can see what I've won and other
users have won. And I know Wunderkind has won some challenges.

**Comment by Alys** [comment]
@vegangypsie Is this problem still occurring? I think we fixed it a while back but I'm not sure.

**Comment by DebsJS** [comment]
It is working correctly now.
