### ISSUE TITLE
improve code quality by auto style check

### ISSUE THREAD

**Issue by gasolin** [HabitRPG/habitica#4054]
We could integrate `grunt jscs` for style check, so every contributor could have consistent code style to submit the patch.

For those files that not ready for pass  style check yet, we could add the list into `.jscsrc.excludeFiles`

If all set, we could add travis test and pre-commit hook to catch the style errors later.
##

**Comment by gasolin** [comment]
PR in https://github.com/HabitRPG/habitrpg/pull/4055

**Comment by crookedneighbor** [comment]
I am for this, but I'd like to explore some other options for js linting.

**Comment by paglias** [comment]
Done for server code, client side code will be linted once we redesign the site
