### ISSUE TITLE
cron not occurring

### ISSUE THREAD

**Issue by RyanMeray** [HabitRPG/habitica#4059]
User ID is 15ef1187-d94e-44c1-8c4f-8d93936f3b9a

Account was using a custom cron time of 3AM EST. This morning, no rollover had occurred, dailies were still checked, and no progress was made in the quest.

Refreshed, force-refreshed, logged in and out, and added new to-dos, and even changed the cron time to noon in an attempt to get a rollover to occur. Nothing is triggering the cron.

**Comment by Alys** [comment]
See "Dailies Remain Checked after Cron" in [Known Bugs](http://habitrpg.wikia.com/wiki/Known_Bugs) for a workaround. It should fix itself up tomorrow.

If you want to keep your 3am custom day start and if all your Dailies are still ticked, I recommend changing the CDS back to 3am first, and then following the workaround at that link (just in case changing the CDS does trigger cron this time).

**Comment by RyanMeray** [comment]
I don't believe the cron has actually run at all, since last night didn't indicate any actions on my quest. Do you think at the next actual cron I'll get two days worth of actions on the quest?

I have changed the custom cron back to 3am and it didn't trigger yet.

**Comment by Alys** [comment]
Yes, when your Dailies remain unchecked, it's because cron didn't run. When your next cron does run (almost certainly tomorrow) all the progress you've made on your quest over the two days will be applied at once.

**Comment by Alys** [comment]
I'm closing this since it's a known problem. You can follow the issue in https://github.com/HabitRPG/habitrpg/issues/1057
