### ISSUE TITLE
Adding a real "unique" ID to task...

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#4064]
This will be a `workaround fix` for #4060.

But how?

$scope.obj is filled by ngResource. So I would have to add a custom ID  property to the TaskSchema? or go through all tasks and this id for each task?

But where should I do that?
- `api.getTasks` ?
- `api.getUser` ?
- both?
- what about `batchUpdate`?

I need some more Informations from the other devs :)
# 

The Real Problem is that WHY tasks are duplicated?! Is there already a ticket for this? So the discussion for the duplicated tasks won't fill this one :P
##

**Comment by negue** [comment]
It is possible to use a function inside "track by" to get an ID. So I won't need any mongodb / Schema changes. 

I'll test this after work.

**Comment by negue** [comment]
I think this is pointless.

Even If I could create a custom "unique" ID, reading the messages of #4060, it seems that somehow tasks are getting "cloned" so same name, same ID.

Does anyone have a good idea to fix this "duplicate ID"?

**Comment by paglias** [comment]
@negue sorry I forgot about this. Tasks are created with addTask in habitrpg-shared and the uuid is generated with this function. It might be it or something else. https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L164

**Comment by paglias** [comment]
We might have that from some old problem or the uuid function isn't so
random in which case, i would say in any case, we should move to something
like https://github.com/broofa/node-uuid/blob/master/uuid.js

2014-10-01 20:12 GMT+02:00 negue notifications@github.com:

> I think this is pointless.
> 
> Even If I could create a custom "unique" ID, reading the messages of #4060
> https://github.com/HabitRPG/habitrpg/issues/4060, it seems that somehow
> tasks are getting "cloned" so same name, same ID.
> 
> Does anyone have a good idea to fix this "duplicate ID"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4064#issuecomment-57509932.

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
I'm adding the critical tag because this is quite serious

**Comment by paglias** [comment]
@negue is this happening in your tasks (an id used twice)? If so can you give me your uuid? Switching to uuid.js I'm afraid will cause even more duplicates because of the old ids generated without it. Also @lefnire IDs should be unique to the user or to the whole app? We might even considering adding a unique index after we find duplicates and migrate them

**Comment by negue** [comment]
Never happened to me, while adding the "trackby" feature, just to the users of #4060

**Comment by Alys** [comment]
Was this fixed by https://github.com/HabitRPG/habitrpg/pull/4845 (which was merged in https://github.com/HabitRPG/habitrpg/commit/ca72b9a9e1e86262fcab15c7d52ae902953dc7b8)?
