### ISSUE TITLE
Application Errors/Plain Text Site

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4065]
@lefnire 

The site is throwing a lot of application errors, but not uniformly - sometimes it will load a plain text version of the site, and I just got a report that it's working fine for someone right now even though it seems to be down for many people.

@Alys @negue Any chance this could be related to something in the recent push, notably the fix for the disappearing tasks? Or is this just the same "Challenges crash the server" issue that we normally see? If it's the latter, I have access to heroku on my phone and could potentially reboot, but I'm leery.

**Comment by Alys** [comment]
I can't see any reason for the [disappearing tasks fix](https://github.com/HabitRPG/habitrpg/pull/4061/files) to be causing this. It was very simple and straightforward.

As best as I can tell from the closed issue list, that was the only change made with a pull request between the most recent two site deployments.

So if I'm right about both of those things, the errors are probably(?) from a challenge.

**Comment by lemoness** [comment]
Just bad timing, then. Okay. In a way, that's good, since it's a known
entity and easy to fix, but I can't reach @lefnire. Going to try to see how
to use heroku to restart the server if I still can't contact him - might
ask here for questions if I have to do so.

**Comment by lemoness** [comment]
@paglias - Searching through heroku, but can't see a way to reboot the
server - have you ever done this?

**Comment by lemoness** [comment]
I know @lefnire said there was an additional app to use, but I can't find
which one it would have been.

**Comment by lemoness** [comment]
@paglias Do you know if @lefnire uses Doppler for Heroku? Or what the name
is of the app that he does use?

**Comment by lemoness** [comment]
AHA - the app is named Nezumi. Getting it now; will give this a try and
pray that I don't make things worse.

**Comment by lemoness** [comment]
Followed the instructions Tyler had sent me, but it doesn't seem to be
working yet - I'll give it some time and then try again.

**Comment by negue** [comment]
The Error is a 503, which means the server itself is crashing. And since I don't get any other output on my end, I can't say for sure that it is my fault^^.

Anyway the fix @Alys "created" (for me), is only on the client-side (webbrowser), It has nothing todo with the crash. (I hope)

So you think the Heroku Server has bug? Or the started instance? (Im new to heroku, and such services...)

**Comment by lefnire** [comment]
Hey guys, sorry for the silence - I'm camping in the mountains right now and dropping in to cafes along the way any chance I can. I'm not sure what's causing all this, likely an npm package upgrade somewhere in our modules. Right I'm testing a deploy on [mongoose@439e486b87e584c5a1b5135fcc08212a25238d5f](https://github.com/LearnBoost/mongoose/commit/439e486b87e584c5a1b5135fcc08212a25238d5f), which is related to the error `500: Maximum call stack size exceeded` (the error I keep seeing on newrelic, which I think is the cause of all this). I'll keep you posted

**Comment by lemoness** [comment]
Poor Tyler :(

Brief background: I used Nezumi to restart the server twice, and it seems
to have helped a little bit, but people are still getting lots of
application errors (including me). I did manage to successfully create and
check off a task after the first one (used DDT to verify), but I haven't
been able to access chat at all. Keep us posted on how it goes.

**Comment by lefnire** [comment]
Ok, I've pushed. Anyone who has access to NewRelic (@Alys, I added you) should be able to see what's going on. [Server performance](https://rpm.newrelic.com/accounts/565514/applications/3386694) (shouldn't be exceeding 500ms response time - ideally 200ms, that's our usual avg); [errors](https://rpm.newrelic.com/accounts/565514/applications/3386694/traced_errors); etc. Anyone who has access to Heroku also has access to [log2viz](http://log2viz.herokuapp.com/app/habitrpg), which shows us if a lot of errors are being thrown (look for H*_, esp. H12). Not that this stuff helps much, it just tells us if crap's hitting the fan. However, the [errors tab](https://rpm.newrelic.com/accounts/565514/applications/3386694/traced_errors) on NR *does_ tell us a lot, particularly what's throwing stuff out of whack. Anyway, I'm showing us as stable now - I'll check back when I can and keep checking my email when I have access

**Comment by veeeeeee** [comment]
Thanks, @lefnire! Let us know when you're back from camping.

**Comment by lefnire** [comment]
backt tomo night

**Comment by lemoness** [comment]
Social media all updated. Thanks so much Tyler - enjoy your camping trip!

**Comment by paglias** [comment]
Sorry guys, it was night vere. The server is made so it's in fact multiple instances of it and each time one of it crashes a new one is created so restarting the whole server shouldn't help much. I have heroku access so I should be able to make deployments when necessary but without knowing @lefnire steps for this I want to bear back from him before doing anything. But we definitively need a way to rollback to a previous version in case of too many errors

**Comment by paglias** [comment]
See https://blog.heroku.com/archives/2013/7/25/releases-and-rollbacks
