### ISSUE TITLE
Cannot edit tags on existing tasks

### ISSUE THREAD

**Issue by CWFranklin** [HabitRPG/habitica#4066]
After adding a custom tag ("work"), I can no longer click on the checkboxes to add tags to existing tasks.
If I create a new task I can add tags after clicking edit, existing tasks will not allow it.

Screenshot to show existing and new "test" tasks.
http://puu.sh/bJXdM/0cdaeeb50d.png

**Comment by caseyhoward** [comment]
I can check tags either. All I am doing is trying to check a tag. I get the following error:

TypeError: Cannot set property 'e46eaedd-295a-4b9d-a2d0-fe4f8f03aa5b' of undefined
    at B.assign (https://habitrpg.com/app-99623818.js:6:26766)
    at $commitViewValue (https://habitrpg.com/app-99623818.js:7:28623)
    at $$debounceViewValueCommit (https://habitrpg.com/app-99623818.js:7:29062)
    at $setViewValue (https://habitrpg.com/app-99623818.js:7:28788)
    at https://habitrpg.com/app-99623818.js:7:26705
    at i.$eval (https://habitrpg.com/app-99623818.js:7:5174)
    at i.$apply (https://habitrpg.com/app-99623818.js:7:5461)
    at HTMLInputElement.Ze.g (https://habitrpg.com/app-99623818.js:7:26685)
    at HTMLInputElement.n.event.dispatch (https://habitrpg.com/app-99623818.js:2:6404)
    at HTMLInputElement.r.handle (https://habitrpg.com/app-99623818.js:2:3179)

**Comment by Alys** [comment]
Before about a day ago, when you created a new task (or reward), the task's object contained an empty 'tags' attribute. I.e., like this:

```
        {
            "text": "new task 1",
            "challenge": {},
            "attribute": "str",
            "priority": 1,
            "value": 100,
            "tags": {},
            .... etc....
        },
```

However now, when you create a new task/reward, there is no 'tags' attribute at all (not even an empty one). 

If you create a new task and assign tags to it **immediately**, that works. The tags are assigned correctly, and if you reload the page, they are still assigned, and you can assign new tags. Using the API, you can see that the new task is created without a tags attribute, but when you assign tags to it immediately, the tag attribute  is then created correctly.

However if you create a new task and then reload or sync **before** you try to assign tags, you can not assign tags to that task after the reload/sync. You get this error:
![screen shot 2014-09-23 at 11 50 00 am](https://cloud.githubusercontent.com/assets/1495809/4366682/f60b8a14-42c3-11e4-99e0-5de760e88403.png)

I would expect that any other action that causes a sync would also prevent you being able to add tags to relatively new tasks.

I suggest that we revert whatever change has prevented the tags attribute from being added to new tasks. At this stage, I am not sure what change that was.

**Comment by Alys** [comment]
### WORKAROUND for anyone experiencing this bug (which is probably everyone):

As soon as you have created a new task or reward, immediately add a tag to it, before taking any other action on the site. From that point onwards, you can edit and add tags on that task exactly as normal.

Alternatively, before you create the new task/reward, select at least one tag. I.e., filter your tasks by one or more tags. Then, when you create the new task/reward, it will already have those tag(s) in it, and from then onwards you can change tags on that task as normal, including removing the initial tags if you want to.

**Comment by Alys** [comment]
FYI, I'm not able to investigate this further today because of personal and work commitments.

**Comment by DrTall** [comment]
FYI I am affected by the same issue. This is my first day using HabitRPG and I thought I was going insane haha. :)

**Comment by lemoness** [comment]
Sorry you encountered this bug on your first day! You should definitely
stop by to chat in the Tavern and the Newbies Guild :) Enjoy the Fall
Festival!

**Comment by DrTall** [comment]
No worries, maybe it's for the best as it has stopped me from OCD'ing all over my task tags before I actually understand what layout would be best.

@Alys has actually already been chatting with me in the Tavern. Seems like you have a cool community going!

**Comment by DrTall** [comment]
Maybe this is unrelated, but I am also unable to delete tags.

Steps:
1. Choose "Edit" under tags.
2. Click the trash can next to a tag.
3. Click save.

Visually the tag has been successfully deleted, but refreshing the page causes the tag to re-appear. During step #2 the console logs:

TypeError: Cannot convert undefined or null to object
    at https://habitrpg.com/app-99623818.js:21:27924
    at nc (https://habitrpg.com/app-99623818.js:18:20127)
    at Function.Vc (https://habitrpg.com/app-99623818.js:18:24176)
    at a.ops.deleteTag (https://habitrpg.com/app-99623818.js:21:27877)
    at Object.m.ops.(anonymous function) [as deleteTag](https://habitrpg.com/app-99623818.js:22:28355)
    at https://habitrpg.com/app-99623818.js:6:27076
    at https://habitrpg.com/app-99623818.js:8:1406
    at i.$eval (https://habitrpg.com/app-99623818.js:7:5174)
    at i.$apply (https://habitrpg.com/app-99623818.js:7:5461)
    at HTMLButtonElement.<anonymous> (https://habitrpg.com/app-99623818.js:8:1388)

**Comment by lemoness** [comment]
The deleting tags bug is also noted here: https://github.com/HabitRPG/habitrpg/issues/4072

**Comment by DrTall** [comment]
Oops, sorry!

**Comment by lemoness** [comment]
No worries!! It's potentially relevant. Would you be able to copy your
error report into that thread as well? Thanks for reporting :)

**Comment by hgenru** [comment]
+, i'm experienced this problem. Also tags checkbox on Rewards tab work fine.

i'm using chrome 34.0.1847.132 on latest ubuntu linux.

This problem found only in habbits and daily tabs.

**Comment by stimulus2da** [comment]
I have this issue as well on Windows 7, Chrome Version 37.0.2062.124 m.
It happens in all areas for me. Habits, Dailies, To-Dos, and custom Rewards.
And yes, it also happens for tasks created with the android app.
@Alys your work-around has been working for me since I first noticed this bug a few days ago. I can't wait for a fix so I don't have to copy, delete, and re-add any task I add on the go with the app.
Cheers!

**Comment by lefnire** [comment]
This and the "can't delete tags" thing is due to `{type: Schema.Types.Mixed, 'default': {}}`, the `default:{}` not being respected ([code](https://github.com/HabitRPG/habitrpg/blob/efbf151c1136f39258eeac82576d5f22bed76d06/src/models/task.js#L21)). I don't know why, I see some talk of it [here](https://github.com/LearnBoost/mongoose/issues/1657) but that's closed as fixed. Maybe a Mongoose version upgrade, which was required for some subdocument updates issues. I hope we don't have any other locations of `'default': {}`, I'm looking into a fix without having to do `if (task.tags){...}` everywhere

**Comment by paglias** [comment]
Instead of default {} why not function(){return {}} so it's not inherited
everywhere?
Il 27/set/2014 03:34 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
change `'default': {}` to `'defaul': function(){return {}}`? What's the difference again?

**Comment by paglias** [comment]
I was thinking about inheritance, the same object being shared everywhere.
But probably not the case. But I don't think we need the default. Just
schema.type.mixed as type. Because having minimize:false as an option on
the model it should create the empty object anyway
Il 27/set/2014 21:38 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
Sure enough, `minimize:false` https://github.com/HabitRPG/habitrpg/commit/a6631f5d3681dc9424c9dc3cc2157b4c72250421 works to solve this for tasks. Not sure I like it, as it'll beef up user object responses. `default:{}` was working before the mongoose upgrade, so I'll keep eye on that issue, but thanks for the recommended solution in interim! Checking now to see if any other `default:{}` aren't being covered

**Comment by lefnire** [comment]
We should be good, other places that have `default:{}` already have `minimize:false` in place (`User` & `Group`). This'll do, thanks @paglias!

**Comment by lefnire** [comment]
Ope, that broke tests...

**Comment by rlquinn1980** [comment]
I found this bug today. I notice I have no problems adding and checking tags on those things which were already in some way tagged. A couple of my rewards, which I'd never previously added a tag to, won't let me check off new tags. 

The current layout for HabitRPG, while definitely appreciated, doesn't work with my current regimen. I really need tags to force some sense of organization here. :(

**Comment by deilann** [comment]
@rlquinn1980 Fear not! There should be a temp fix for this going live soon. You can see that @lefnire committed it, but it has not yet been deployed onto the site.

**Comment by paglias** [comment]
@lefnire why is the fix reverted? it's almost impossible to use tags

**Comment by lefnire** [comment]
It broke a bunch of challenges tests, I haven’t had time to investigate

**Comment by DrTall** [comment]
I am also excited for the fix, but my guess is that the memory leak is/was more important :)

**Comment by lefnire** [comment]
If someone can beat me to it, 

``` shell
$ git revert 0fa7277
$ NODE_ENV=test mocha test/api.mocha.coffee
```

**Comment by paglias** [comment]
@lefnire trying, $setDifference is a mongo 2.6 feature, because now I'm using 2.4 which should be the same and habit and it's not avalaible

**Comment by lefnire** [comment]
habit is 2.6, i upgraded yesterday

**Comment by paglias** [comment]
Cool! I get 5 failing tests, but only one of them seems related with this
commit (the others are per 2.6 or something else), investigating
Il 03/ott/2014 19:22 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by paglias** [comment]
@lefnire ok, I fixed a test due to moment not being required, as for this issue: one is due to https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/challenges.js#L144 not returning true anymore for any task and the second here https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/challenges.js#L293 with task.challenge always an empty object. Sincerely I'm not sure on how to fix these and if there's any bug in mongoose itself. I would leave it to you because I'm a bit lost. The branch with the fix for moment is here https://github.com/HabitRPG/habitrpg/commits/paglias/tags

**Comment by lefnire** [comment]
two down, two to go

**Comment by lefnire** [comment]
actually eff it, the remaining two tests are failing anyway

**Comment by DrTall** [comment]
Hooray! <3
