### ISSUE TITLE
Errors after casting a party skill

### ISSUE THREAD

**Issue by pepperpanda** [HabitRPG/habitica#4067]
When I cast Blessing I seem to be getting this error

![1](https://cloud.githubusercontent.com/assets/4915522/4365956/5c077d90-42b6-11e4-8ffa-942d5b0f8fde.jpg)

and then after I try to sync with the server the heal wouldn't be applied

![2](https://cloud.githubusercontent.com/assets/4915522/4365968/7852213a-42b6-11e4-9acc-98fedbed700e.jpg)

I've tried numerous times but the result is still the same.

**EDIT:** I have tried logging out, then clearing the cache and logging back in again.

**Comment by Alys** [comment]
Confirmed. I just switched to Healer and got the same thing when I cast Blessing and Protective Aura (party skills) but not when I cast the two non-party skills.  Chrome JavaScript Console report for one casting of Blessing:
![screen shot 2014-09-23 at 10 17 22 am](https://cloud.githubusercontent.com/assets/1495809/4366004/16ee5d2c-42b7-11e4-8f39-65b89cb7c5f5.png)

**Comment by ghost** [comment]
Same thing for casting a party spell as a Mage (Ethereal Surge, I think).

**Comment by Alys** [comment]
Also Rogue Tools of the Trade (party skill) but not two of the three non-party skills (didn't test Backstab because it's too powerful). Also both Warrior party skills but not either of the non-party skills.

It's definitely a bug for party skills only.

**Comment by Alys** [comment]
FYI, I am not able to investigate this because I have real-life commitments.

**Comment by Mihakuu** [comment]
I do not get the error message and it looks like I can cast the spell until refresh where the effect is reverted back. Was casting a blessing.

**Comment by veeeeeee** [comment]
Confirmed for Warrior--Can't cast Valorous Presence. Same error message.

**Comment by pepperpanda** [comment]
Just now, it's seems the skills behave normal. I can use Blessing as of now. Was it fixed?

**Comment by Alys** [comment]
fixed long ago
