### ISSUE TITLE
Last habit in Habits column is always blue-green

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica#4068]
Thought it was just me, but saw it on another new user's screen today. Even if we don't touch it (for weeks in my case), our last habit in the column is always blue-green.

**Comment by Alys** [comment]
Is it a Habit that has both plus and minus options enabled? If so, it will remain the same colour forever if you don't use it. It will be coincidence that you both have those at the bottom of the column.

**Comment by AnitaYCheng** [comment]
Ahh, interesting! Carry on then! :)

**Comment by Alys** [comment]
:) :)

I should have linked you to more details: http://habitrpg.wikia.com/wiki/Habits if you're not aware of that page.
