### ISSUE TITLE
app-99623818.js internal server error

### ISSUE THREAD

**Issue by nanooq** [HabitRPG/habitica#4069]
JavaScript Problem on Ubuntu 12.04, Firefox 32.0.2. NoScript Plugin deactivated, error still occurs.  Starting firefox console debugger, makes it crash. 

First, after log-in, I do not get redirected to tasks, but stay on the static frontpage. This is resolved by reloading. 

Secondly, I often get the warning, that a script is not responding: https://habitrpg.com/app-99623818.js:2. Debugging it makes FF crash. Stopping it or kepp executing it make no difference. It will reappear. This warning appears if scrolling or ticking off todos. 

Thirdly, trying to cast Tools of Trade with enough MP, the correct MP are substracted. Then a red bubble displays: "Please reload, "Error Cast to number failed for value "NaN" at path "_v"" (see Chrome console for more details)." and the 25 MP are added back. A reload changes nothing. Same problems (warning and red bubble) appear. This is a confirmation of https://github.com/HabitRPG/habitrpg/issues/4067

UUID: 2834621d-6f43-42d8-b42e-6f3d6c11f1ab

I then installed chromium-browser and started habitrpg to get you guys the logs. Chromium does not carsh and states:
Attr.nodeValue' is deprecated. Please use 'value' instead.
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1410989646.html:1
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
Failed to load resource: the server responded with a status of 503 (Service Unavailable) https://habitrpg.com/api/v2/user/batch-update?_v=9224&data=1411473409516&siteVersion=1
Objectconfig: Objectdata: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta name="viewport" content="width=device-width, initial-scale=1">↵      <style type="text/css">↵        html, body, iframe { margin: 0; padding: 0; height: 100%; }↵        iframe { display: block; width: 100%; border: none; }↵      </style>↵    <title>Application Error</title>↵    </head>↵    <body>↵      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">↵        <p>Application Error</p>↵      </iframe>↵    </body>↵    </html>"headers: function (c){if(!b)b=Uc(a);if(c){return b[e(c)]||null}return b}status: 503statusText: "Service Unavailable"**proto**: Object

This was after log in. Then with the casting of the tool of the trade

POST https://habitrpg.com/api/v2/user/class/cast/toolsOfTrade?targetType=party&targetId= 500 (Internal Server Error) app-99623818.js:6(anonymous function) app-99623818.js:6q app-99623818.js:6k app-99623818.js:6k app-99623818.js:6(anonymous function) app-99623818.js:6i.$eval app-99623818.js:7i.$digest app-99623818.js:7i.$apply app-99623818.js:7(anonymous function) app-99623818.js:8n.event.dispatch app-99623818.js:2r.handle app-99623818.js:2
Object {data: Object, status: 500, headers: function, config: Object, statusText: "Internal Server Error"} app-99623818.js:22responseError app-99623818.js:22l app-99623818.js:6l app-99623818.js:6l app-99623818.js:6(anonymous function) app-99623818.js:6i.$eval app-99623818.js:7i.$digest app-99623818.js:7i.$apply app-99623818.js:7o app-99623818.js:6x app-99623818.js:6s.onreadystatechange

**Comment by lemoness** [comment]
So, the problem with Tools of the Trade is unrelated - you can follow it here: https://github.com/HabitRPG/habitrpg/issues/4067

The other server issues have been plaguing us over the past two days. Leaving this ticket open for @lefnire and @paglias in case it contains helpful information for them.

**Comment by paglias** [comment]
I think we can close

**Comment by nanooq** [comment]
@paglias Could you please refer somewhere, where the server issue is being worked on? Thank you in advance.

**Comment by lefnire** [comment]
#4079
