### ISSUE TITLE
Healer spells fail

### ISSUE THREAD

**Issue by townimbecile** [HabitRPG/habitica#4071]
When I cast Blessing or Protective Aura, I get an error. The chrome console tells me:
    "Cast to number failed for value "NaN" at path "_v""
It have to do with my level being 140.

**Comment by lemoness** [comment]
Thanks for letting us know! This is actually a duplicate bug of https://github.com/HabitRPG/habitrpg/issues/4067 - you can follow that thread for details on what is happening. Thanks for bearing with us while we work to get this fixed!
