### ISSUE TITLE
Cannot permanently delete tags (or get a sort of them to stick)

### ISSUE THREAD

**Issue by edean** [HabitRPG/habitica#4072]
I am unable to delete or sort my tags in a way that will stick permanently. I'm careful to wait for the blue bar sync to occur after actions I take, I've tried reloading the page, I've tried logging out and back in, I've even tried deleting my completed to-do's in case that was somehow involved; basically, I've fiddled around to no end. Yet even though the sorts and deletes will appear settled for a while, without fail at some point the tags reappear, with all tags in the old order.

FYI, I joined two challenges for the first time a few days ago, and promptly decided to leave them. Two of the tags I'm trying to delete are from those challenges (note, the associated tasks went away just fine), but I'm also unable to delete normal tags at this point either.

The most closely related existing issues I found were [#4062](https://github.com/HabitRPG/habitrpg/issues/4062) and [#1611](https://github.com/HabitRPG/habitrpg/issues/1611), but I judged them to be distinct enough from my issue to warrant opening this new one.

User ID: 4cf2fa9f-fcc3-4d55-b3f4-2d3bfa8bd6a7
OS: Windows 8.1
Browser: Chrome Version 37.0.2062.120 m

**Comment by caseyhoward** [comment]
I experienced the same issue. I also added a challenge and removed it prior to experiencing this. I get the following error when I click the trash can icon next to a tag:

```
TypeError: Cannot convert undefined or null to object
at https://habitrpg.com/app-99623818.js:21:27924
at nc (https://habitrpg.com/app-99623818.js:18:20127)
at Function.Vc (https://habitrpg.com/app-99623818.js:18:24176)
at a.ops.deleteTag (https://habitrpg.com/app-99623818.js:21:27877)
at Object.m.ops.(anonymous function) [as deleteTag] (https://habitrpg.com/app-99623818.js:22:28355)
at https://habitrpg.com/app-99623818.js:6:27076
at https://habitrpg.com/app-99623818.js:8:1406
at i.$eval (https://habitrpg.com/app-99623818.js:7:5174)
at i.$apply (https://habitrpg.com/app-99623818.js:7:5461)
at HTMLButtonElement.<anonymous> (https://habitrpg.com/app-99623818.js:8:1388) 
```

**Comment by habitrpguser** [comment]
I'm having the same issue. I've also heard someone else talking about it in the tavern, I'm copying the post here because it's a good description:

"Apologies if this is documented somewhere, but I can't find it ... I am unable to delete or sort my tags in a way that will stick permanently. I'm careful to wait for the blue bar sync to occur after actions I take, I've tried reloading the page, I've tried logging out and back in, I've even tried deleting my completed to-do's in case that was somehow involved; basically, I've fiddled around to no end. Yet even though the sorts and deletes will appear settled for a while, without fail at some point the tags reappear, with all tags in the old order. I'd appreciate some sage advice; anyone? (FYI, two tags I'm trying to delete are from challenges I briefly joined then left [the tasks went away just fine], but others are normal tags.)"

**Comment by DrTall** [comment]
I am also affected, and I see the same stack trace:

TypeError: Cannot convert undefined or null to object
at https://habitrpg.com/app-99623818.js:21:27924
at nc (https://habitrpg.com/app-99623818.js:18:20127)
at Function.Vc (https://habitrpg.com/app-99623818.js:18:24176)
at a.ops.deleteTag (https://habitrpg.com/app-99623818.js:21:27877)
at Object.m.ops.(anonymous function) as deleteTag
at https://habitrpg.com/app-99623818.js:6:27076
at https://habitrpg.com/app-99623818.js:8:1406
at i.$eval (https://habitrpg.com/app-99623818.js:7:5174)
at i.$apply (https://habitrpg.com/app-99623818.js:7:5461)
at HTMLButtonElement. (https://habitrpg.com/app-99623818.js:8:1388)

**Comment by Alys** [comment]
## WORKAROUND

This excellent illustrated blog post by Taldin will show you how to use HabitRPG's API to delete tags: [Bug Workaround of the Day: Deleting Unwanted Tags](http://habitrpg.wikia.com/wiki/User_blog:Taldin/Bug_Workaround_of_the_Day:_Deleting_Unwanted_Tags)

There will be an official fix for this, probably within the next few days, and after that happens you'll be able to delete tags by the normal method, but if you'd like to delete them before then, Taldin's advice will help you.

**Comment by Alys** [comment]
See update here: https://github.com/HabitRPG/habitrpg/issues/4066#issuecomment-57038335

**Comment by Alys** [comment]
Fixed
