### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4073]
Not exactly an issue, but it was suggested I post this here.

https://chrome.google.com/webstore/detail/habitrpg/gibpkkgilfoeihbgnlafalhjfljbibnj

Handy extension to easily view and interact with you HabitRPG lists without having to go directly to the page every time. 

Current Features:
- View Health, Experience, and Gold
- View Habits, Dailies, and To Dos
- Complete tasks or mark up or down on habits
- Lists are as close to HabitRPG's interface as possible.

My username in HabitRPG and the developer name on the Chrome extension are both anijam.

**Comment by Alys** [comment]
I've been using this for a few days and I like it! It's a nice way of getting quick access to my tasks. It's especially useful for me because I have two accounts (home and work) and when I'm at work, I have the HabitRPG website open to my work account but the extension set for my home account.

This should definitely go on our wiki in the [Extensions](http://habitrpg.wikia.com/wiki/Category:Extensions) category. @crystaldarklight would you like to do that or would prefer that I or another wiki editor does it?

What's your HabitRPG unique User ID? You are probably owed a contributor tier for this. :)

**Comment by ghost** [comment]
Thank you. I just didn't know where to put this. I just wanted to share.
Put it on the wiki if you'd like; I'm still a bit of a beginner in all
this. If it's not put up on the wiki by the time I get home from work, I'll
do it myself.

I noticed that the current page for a Chrome Extension (the one that tracks
your pages) has a support page. I'm on bitbucket, as it offers free private
repositories, and I'd like to keep this one to myself until I'm done
messing with it for my portfolio. (I currently have only done internal work
for companies and really have nothing to show). When I am satisfied with
the extension, I will move it to github for anyone else to crack into.
https://bitbucket.org/anijam/habitrpg-chrome-extension/issues

My User ID is

e4448e6f-2152-42e5-8806-521d3b93afc2

**Comment by Alys** [comment]
lvl++ :)

**Comment by Alys** [comment]
By the way, is it possible to change the extension's name so that it's more descriptive? Perhaps something like "HabitRPG Display Items"? There's a few extensions now and a unique name will help people identify yours more easily.

Also are you considering adding rewards? I'd love that. :)

**Comment by ghost** [comment]
I was considering HabitRPG Interactive, as it's more than just a display.
The description is getting updated to better reflect this as well. (I'm not
in marketing)

I *am *considering adding rewards, but Reddit has requested an offline mode
first, and there's a glitch with showing how much gold is earned, even
though the total gold at the top seems to be correct. The amount is right,
but it's not splitting gold/silver.

**Comment by lefnire** [comment]
+1 on the name-change for clarification, as now there's two "HabitRPG"s in the extension store

**Comment by ghost** [comment]
New update should be on the store soon. Here's to hoping I didn't screw it
up :P

New:
Name is now HabitRPG Interactive
Offline Mode
Completed Items are now bumped down or to a new tab a la HabitRPG's
interface.
Fixed the money display bugs.

Maybe next:
Rewards Purchase
Show and interact with Checklist Items
Show Notes

**Comment by ghost** [comment]
Oh, and I've been informed that day specific items do not display proper. I'll look into that as well.
