### ISSUE TITLE
Can't add tags to task via edit function on mobile

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#4075]
Starting a couple days ago, I can't add tags to a task if it didn't already have any from either when it was created or from before this issue began. The box just won't check if I tap it. I'm running iOS 7.0.6.

**Comment by lemoness** [comment]
We're actually having a similar problem on the main website: https://github.com/HabitRPG/habitrpg/issues/4066

I'm willing to bet the two are related, and fixing the site will probably fix mobile. That being said, I'm leaving this ticket open until a dev confirms that it's a duplicate and can be closed.

**Comment by Alys** [comment]
yes, duplicate
