### ISSUE TITLE
page is completely white

### ISSUE THREAD

**Issue by patena** [HabitRPG/habitica#4077]
Sometime yesterday evening I reloaded habit and got an entirely white page. It's still entirely white today. Not sure what to do.

User ID 28493c5d-00bb-4bc0-a471-9c4b40c9e642, Firefox 32.0 on Xubuntu Linux.

**Comment by lemoness** [comment]
We've been having some server trouble - could you try refreshing, and then
another browser, and let us know if you're still having this problem?

Sorry about this!

**Comment by deilann** [comment]
You may also need to clear your cache

**Comment by patena** [comment]
Tried clearing my cache and reloading - still white.
Tried another browser (chromium) - it's not letting me log in, and it doesn't recognize my email when I try to do the "forgot password" thing! Could that also be related to your server trouble, or did something else happen to my account?

**Comment by lefnire** [comment]
@patena I was able to load your account without errors (+ no white screen). You had a typo in email field (**@gmail.cm), I fixed - can you try forgot-password again?

**Comment by patena** [comment]
@lefnire Oops, thanks for the email typo fix!
On chromium I reloaded the page and it logged me in fine, didn't even need to do do the forgot password thing. It just loads very slowly.
On firefox I reloaded a few more times - sometimes I get the white page and sometimes this (I tried attaching an image, hopefully it worked?)

**Comment by patena** [comment]
Image: http://weronika.smugmug.com/Random/stuff-Im-linkingsharing-on-LJ/i-w4mbS9q/0/S/Screenshot%20-%2009242014%20-%2011%3A31%3A27%20AM-S.png

**Comment by patena** [comment]
Still a completely white page in my main browser... :(

**Comment by paglias** [comment]
If you get the blank page on Chrome click CTRL+Shift+J to open the Console
and report any error you see there, on Firefox you can do the same with
Ctrl+Shift+K

2014-09-26 7:30 GMT+02:00 Weronika Patena notifications@github.com:

> Still a completely white page in my main browser... :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4077#issuecomment-56920944.

## 

Matteo Pagliazzi - paglias.net

**Comment by patena** [comment]
@paglias Here's what I get (on Firefox):
<source> element has no "src" attribute. Media resource load failed. habitrpg.com
All candidate resources failed to load. Media load paused. habitrpg.com
Error: [$injector:modulerr] Failed to instantiate module habitrpg due to:
Component returned failure code: 0x80520010 (NS_ERROR_FILE_NO_DEVICE_SPACE) [nsIDOMStorage.getItem]
http://errors.angularjs.org/1.3.0-beta.11/$injector/modulerr?p0=habitrpg&p1=Component%20returned%20failure%20code%3A%200x80520010%20(NS_ERROR_FILE_NO_DEVICE_SPACE)%20%5BnsIDOMStorage.getItem%5D

**Comment by deilann** [comment]
The fact that this is only one one browser makes me still think it's a
cache issue, despite the fact that you tried clearing your cache. Is there
any way you can try clearing your cache again? That error report looks like
a cache issue to me, too, from a quick glance.

**Comment by deilann** [comment]
(In order to clear your cache on Firefox, select "Everything" when you go
to Clear Recent History. Otherwise, you may not end up clearing your entire
cache.)

**Comment by lefnire** [comment]
Clear localstorage. Will follow up with screens

**Comment by lefnire** [comment]
https://www.evernote.com/shard/s17/sh/1dd195f3-5d51-4e7f-82e3-57304971cf60/143882fee4a9f822ff057e58b84bcefc

**Comment by patena** [comment]
@deilann Okay, just to make sure I'm doing this right - there appear to be two ways of clearing a cache in Firefox:
1) Edit->Preferences->Advanced->Network, click "Clear Now" in the "Cached Web Content" and "Offline Web Content" sections.
2) History -> Clear Recent History -> pick time range "Everything", check only the "Cache" box, click "Clear Now".
I did both these things and reloaded the tab, still white. Anything else I should do?

@lefnire That appears to be a screenshot for Chrome on a Mac, I'm using Firefox on Linux - I'm not sure how to get that to happen.

**Comment by lefnire** [comment]
http://stackoverflow.com/questions/6084099/how-to-view-delete-local-storage-in-firefox
 ?

**Comment by patena** [comment]
@lefnire Clearing local storage and reloading the tab didn't work, but restarting Firefox did (I'm not sure if I tried that before clearing local storage too). Things seem to be working fine. Thanks!
