### ISSUE TITLE
Died when I had full health

### ISSUE THREAD

**Issue by eternalearth888** [HabitRPG/habitica#4078]
To whom this may concern:
I was editing a task and giving it a checklist when suddenly it said -6.8HP when I was at a full 50HP and then it said I died. SO I lost a level AND it broke my Kelp Hat. :(

**Comment by Alys** [comment]
Are you in a party and is that party currently doing a boss quest? If so, a party member might have caused you more than 50 points of damage if they had a very large amount of Dailies left undone. Please go to your party page, click the sync button that is immediately next to the "send chat" button (it's important to use that sync button) and look through recent messages in party chat to see if there are reports of large damage.

**Comment by eternalearth888** [comment]
Yes, thank you for reminding me! Somehow we got 68.4 damage @_@ Oh well.
Thanks!

On Wed, Sep 24, 2014 at 3:35 PM, Alice Harris notifications@github.com
wrote:

> Are you in a party and is that party currently doing a boss quest? If so,
> a party member might have caused you more than 50 points of damage if they
> had a very large amount of Dailies left undone. Please go to your party
> page, click the sync button that is immediately next to the "send chat"
> button (it's important to use that sync button) and look through recent
> messages in party chat to see if there are reports of large damage.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4078#issuecomment-56742799.

## 

/**
 *
- Maria Deslis
- Colorado School of Mines
- Undergraduate
- Major: Computer Science
- VP of ACM-W CSM
  */
