### ISSUE TITLE
Several to-do lists (e.g. work and personal)

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#408]
I have a lot to do both at home and at work and would love to separate my personal life and job tasks in two lists.

**Comment by lefnire** [comment]
[Tags](https://trello.com/card/tags-categories/50e5d3684fe3a7266b0036d6/43) my friend, will be one of the first things built in the coming weeks.

**Comment by hjalmberi** [comment]
If there were a like button here, I'd press it!

**Comment by lefnire** [comment]
Click the Trello link, then press 'v'. "Vote" :)
