### ISSUE TITLE
Custom HabitRPG Protocol URL

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#4082]
We now get more and more 3rd Party Apps, some of them just using the normal "Copy UserID / ApiKey" method, some can use a QrCode Reader to get the connection Infos. 

But on some platforms there is no "simple" way to get a Qr-Code Reader, only If you wan't one yourself, which I don't want to xD.

Anyway my Idea was a link beside the Qr-Code, which would look like this:

`habitrpg://https/habitrpg.com?userId=1234123123123&apiKey=2312123123`

On each Platform an App can define that It would react to custom protocols, (alteast in windows & android), and then a user could login in the mobile website, click on that link and a 3rd Party App could easily react on this url to set its Account Settings..

What do you think^^

**Comment by paglias** [comment]
The best thing, from a lot of point of view would be to implement OAuth 2

**Comment by negue** [comment]
Yep, and every api consumer should register first, and each user could / should decide what data what go in which registered app.

But I don't have any knowledge of OAuth2 at all^^

So the custom protocol is a stupid idea?

**Comment by paglias** [comment]
No :) It was just a random thought. How would that work? A user is redirected to the mobile website/app of HabitRPG where upon login it would be redirected back to a custom protocol url containing api key & user id. Right?

**Comment by negue** [comment]
Yep, it would also work without redirecting from the 3rd Party app.
- Open / Login to mobile website or existing mobile app
- Go to API Page
- click on that Link
- any other app which has registered as a "handler" for protocol "habitrpg://" (managed by the platform itself) will be opened with this url data, if there are more than one handler the platform shows up a selection.
-  thats it, from here on the 3rd party apps handle the given data to i.E. set the account data

Also the browser addons (I count 2?, are there more?) could react on this URL, so the Users won't have to copy & paste the IDs

**Comment by paglias** [comment]
@negue Ok, there is one thing I don't like, this way any app/extension could listen for this protocol and steal the user api key. Let's say user want to authorize app A but maybe there is a malicious app B listening too that will get that info even if the user didn't want to give it its api key.

**Comment by negue** [comment]
Yes, but that would be only happen if the user click on it.

You are right that would be bad too :(
