### ISSUE TITLE
Tasks created via the Android app cannot be tagged

### ISSUE THREAD

**Issue by SpencerDub** [HabitRPG/habitica#4083]
# System Specs
## Smartphone:
- Samsung Galaxy S5
- Android 4.4.2
- HabitRPG 0.035
## Desktop:
- MacBook Pro, Early 2011, Mac OS X 10.9.4, with Firefox 31.0 and Safari 7.0.6
- HP Envy 15z-j100, Windows 8.1, Chrome and Firefox _(This is my home computer and I'm currently at work, so I can't give you version numbers on these at the moment.)_
# Issue summary:

Habits, Dailies, and To-Dos (in short, "tasks") created via the Android app cannot be tagged, either in Android or in the web client.
# Steps to reproduce:
1. Log in to the Android client.
2. Create a new task--whether it's a Habit, Daily, or To-Do doesn't matter. Give it a distinctive, easy-to-find name.
3. On a desktop browser, log in to HabitRPG.
4. Locate the task just created and click the "Edit" button in the top-right corner of the task.
5. Scroll down to its tags and click the checkbox next to a tag.
# Expected result:

The checkbox responds to the click by activating, displaying a checkmark, and adding the tag to the task.
# Actual result:

The checkbox does not activate. No checkmark is displayed and no tag is added.
# Console log:

This appears in the console when you click a tag checkbox on an app-created task:

```
https://habitrpg.com/app-b91ded6c.js

"Error: h is undefined

Bd.prototype.objectIndex/<.assign@https://habitrpg.com/app-b91ded6c.js:6:26755

df</this.$commitViewValue@https://habitrpg.com/app-b91ded6c.js:7:28623

df</this.$$debounceViewValueCommit@https://habitrpg.com/app-b91ded6c.js:7:29060

df</this.$setViewValue@https://habitrpg.com/app-b91ded6c.js:7:28786

Ze/g/<@https://habitrpg.com/app-b91ded6c.js:7:26703

Md/this.$get</i.prototype.$eval@https://habitrpg.com/app-b91ded6c.js:7:5163

Md/this.$get</i.prototype.$apply@https://habitrpg.com/app-b91ded6c.js:7:5449

Ze/g@https://habitrpg.com/app-b91ded6c.js:7:26683

n.event.dispatch@https://habitrpg.com/app-b91ded6c.js:2:6348

n.event.add/r.handle@https://habitrpg.com/app-b91ded6c.js:2:3121

"
```
# Other information:

If I create a task with the same name and description via the web client, I can tag it without problem.

As mentioned above, I've reproduced this issue on Safari and Firefox on Mac, and Chrome and Firefox on Windows.

UUID: 12fccfc6-5328-48a9-8c3c-fef4212b5c97

**Comment by Alys** [comment]
Please see [Cannot edit tags on existing tasks · Issue #4066](https://github.com/HabitRPG/habitrpg/issues/4066). It will be the same issue as this, so I'm going to close this one. You can follow the progress of a fix in 4006. Note the comment in that issue starting with "TEMPORARY WORKAROUND", although I'm not sure if tagging tasks **immediately** in the mobile app will behave the same way as tagging them immediately on the website.

**Comment by SpencerDub** [comment]
Ah, sorry about that. I missed it when searching. Thanks for pointing me to it.
