### ISSUE TITLE
Trying to see how others are doing in challenges results in an error

### ISSUE THREAD

**Issue by emguthrie** [HabitRPG/habitica#4085]
Every time I try to click someone's name to check on someone else's progress in a challenge (whether I am a part of said challenge or not), I get this error:

Please reload, "Error exception: invalid operator '$setDifference'" (see Chrome console for more details).

Neither the sync button, a refresh, or clearing my browser data have made any difference.

My UUID: e69f1761-ae26-42c1-9636-2c79154bf3e5
Browser: Google Chrome Version 37.0.2062.124 m
OS: Windows 7

Here's a screenshot that includes the issue and what shows in the console.

![challenge how s everyone doing bug](https://cloud.githubusercontent.com/assets/8921544/4413790/e7f75f2c-450a-11e4-9bfc-eadfc270584d.png)

**Comment by lefnire** [comment]
Committed in https://github.com/HabitRPG/habitrpg/commit/632726fe0273ad507138ae9c30a8a890659e8a0f , I need to upgrade our database server to 2.6. Assigning to self
