### ISSUE TITLE
Fall Festival gear unavailable.

### ISSUE THREAD

**Issue by MAZimbric** [HabitRPG/habitica#4088]
I'm unable to see or purchase Fall Festival gear in the rewards column using either the Android app (Galaxy G4) or Chrome on Mac OS 1.6. My user ID is ae88d017-f784-4d24-b327-eda814e798a1

**Comment by lemoness** [comment]
Hi Nepenthe! Never fear, this will be fixed the next time there is an update to the mobile app. We'll get to it soon! In the meantime, you can purchase it on the website, www.habitrpg.com. Thanks for reporting this!

**Comment by Alys** [comment]
On the app, it always takes a while for new items to appear: https://github.com/HabitRPG/habitrpg/issues/4086

From your publicly available API data, I can see that you own armor_special_fallMage, head_special_fallMage, weapon_special_fallMage. I.e., the Mage items shown here: http://habitrpg.wikia.com/wiki/Fall_Festival#Special_Class_Gear
Basically, you've already bought the Fall Festival items for your class. :)
