### ISSUE TITLE
Misspelling in Rooster Quest

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4089]
Pointed out by Vicky - the artist's name was misspelled, and none of us caught it. "extrajordinary" should be "extrajordanary."

**Comment by Alys** [comment]
I've posted in [Aspiring Coders](https://habitrpg.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f) that this would be an easy fix for a new programmer to do.

**Comment by mattstrick** [comment]
This looks to be fixed. I just forked the repo and the name change was already in there.

**Comment by me-and** [comment]
The only place in this codebase that name is mentioned is in `views/shared/new-stuff.jade`, where it was added in c32cd57c92b8845512a4e61fb5393458ed130084 and moved in f38db7b964a5f3a7dbbeeaa242ac2909183b2f61. In both cases, it was spelled correctly.

Possibly it's misspelled in the quest itself – quests don't appear to be in this repository (although I could just be missing them) – but I've no idea where the quest text is to fix it up. Certainly there's nowhere else that contains the string `xtraj` (searched case insensitive).

**Comment by veeeeeee** [comment]
I spotted it in the quest description. It's visible in the Market when you rollover for the popup.

**Comment by Alys** [comment]
A lot of site text is stored in the habitrpg-shared repository under https://github.com/HabitRPG/habitrpg-shared/tree/develop/locales/en. You can read about the various repositories in the "Coders (Web & Mobile)" section in [Contributing to HabitRPG](http://habitrpg.wikia.com/wiki/Contributing_to_HabitRPG#Coders_.28Web_.26_Mobile.29). See also [Guidance for Blacksmiths](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths) and [Setting up HabitRPG locally](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally).

**Comment by Algogator** [comment]
https://github.com/HabitRPG/habitrpg-shared/pull/330 did I do it right?

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg-shared/pull/330
