### ISSUE TITLE
Suggestion - fixed dps/xpps for chrome extension

### ISSUE THREAD

**Issue by noidexe** [HabitRPG/habitica#409]
Almost none of my productivity involves a browser, so I have no way to stop the productivity habit from turning red. I'm ok with the damage increasing with continous use of the vice site but not with five minutes of facebook here and there almost killing my character. 

So I think it should be possible to define either a fixed amount of damage or accumulative damage that slowly returns to base damage when you avoid vice websites.

Right now I end up buying a potion and clicking in the plus button a few times to return the damage level to something more reasonable.

**Comment by Pandoro** [comment]
I think this is a very valid point and I can understand your frustration. You can of course also use the productivity habit for other productive things in your life, but it might not be something you really want to track like this.

@SlappyBag Do you think you can make, or is it already supported, to use pure - or + habits for the productivity daily? Meaning that you will only track good OR bad sites and thus you will not get any bonus/damage increase from that habit?

**Comment by StanLindsey** [comment]
This is an API & main site issue really. All the extension does is tell the Habit to register an up or a down, exactly the same as if you had clicked on the plus or minus button yourself.

So there are two things I would would prefer: 
A. The possibility of Habits having a floor & ceiling so not as to get too dramatically screwed.
B. The ability to specifically send a up or down amount via the API.

We've already got a guy working on implementing a full API, so this will come. Until then the best I can suggest is either A. up the time interval between scores in the Chrome Extension settings or find some productive websites! Any website you want to be motivated to go on you should add to your productive list. 

=D

**Comment by Pandoro** [comment]
What I tried to say and seeing @SlappyBag 's post, believe might be possible, is that you remove the plus button of the productivity task. This is of course no real solution, but using pure negative or pure positive tasks means they would not change the damage you take / exp you get per click. So you would get a constant hp loss based on your browsing activity. 
The obvious drawback is that you cannot get a positive result of your browsing at all using this.

**Comment by horusofoz** [comment]
@noidexe Is this still an issue with the recent extension rewrite?

**Comment by noidexe** [comment]
I haven't tested it extensively but on my daily usage damage seems to be much more reasonable. As far as I'm concerned you can consider the issue resolved.

**Comment by horusofoz** [comment]
Thanks
