### ISSUE TITLE
Tags Automatically Highlighted Upon Reload (Clear Tags Not Permanent)

### ISSUE THREAD

**Issue by rlquinn1980** [HabitRPG/habitica#4094]
User ID: 1f5efdb9-9966-4b81-ba85-27e054345624

When first loading HabitRPG.com or after reloading the tasks page, tags are shown as highlighted. Selecting "Clear" for tags releases them, but once the page is reloaded, tags are highlighted again. 

There also appears to be a "ghost" tag left over from a former tag that was deleted while it was highlighted. After page load, clearing individual tags leaves all tasks and self-made rewards hidden. Only using the "Clear" option de-highlights this ghost tag.

**Comment by crookedneighbor** [comment]
@rlquinn1980 I'm just seeing this now and shocked that no one talked to you sooner. Is this still occurring? If so, what are the name of your current tags and what is the name of the ghost tag?

**Comment by rlquinn1980** [comment]
Someone else helped me fix it with a workaround later that day. Also, I
have not used HabitRPG in months.

**Comment by crookedneighbor** [comment]
@rlquinn1980 Sorry to hear that!

I'm going to close this issue, but do you have any idea what the issue was? Was it browser specific?

**Comment by rlquinn1980** [comment]
I tried to remember exactly what it was, but it's really been a while. I
know it wasn't browser specific, because the issue persisted in a different
browser and in the app on a separate device.
