### ISSUE TITLE
Unlocking Set of Supernatural Skins deducted 3 gems and unlocked one skin

### ISSUE THREAD

**Issue by Indubitably1** [HabitRPG/habitica#4098]
I just purchased 5 gems and used them to "Unlock Set" of Supernatural Skins by clicking "Purchase for 5 Gems." However after unlocking the set and then applying a skin, I went to the Equipment page whereupon I received an error that included 'server unreachable.' When I went back to the Avatar page, I had to reload in order to see the page, at which point only one of the skins was unlocked, however 3 of the 5 gems had been deducted. 

Is there a way to fix this or is it possible to have a refund so that I can redo the purchase, or am I simply out of luck?

User ID: 57aef3cc-7fe3-4d34-bbb2-26260c83d616

**Comment by paglias** [comment]
If you completely reload the page nothing changes?
Il 01/ott/2014 17:00 "Indubitably1" notifications@github.com ha scritto:

**Comment by Indubitably1** [comment]
Nothing changes, I've reloaded multiple times.

Also I am using OS X 10.8.4 on Firefox v.31.0

**Comment by paglias** [comment]
OK, the server is having some problems right now, I'll fix your
items/balance as soon as it's stable
Il 01/ott/2014 17:06 "Indubitably1" notifications@github.com ha scritto:

**Comment by Indubitably1** [comment]
Thanks so much, I really appreciate it!

**Comment by k8sullyvan** [comment]
I've just had a very similar problem, I bought the full set of hair styles and equipped one but now the system thinks that I only bought the one hairstyle and has deducted 2 Gems for the purchase (giving me back 3 of the 5 gems I spent on the whole set) 

UUID: d62e990b-d300-46cf-9dc5-bc99d122ac36

**Comment by paglias** [comment]
@UncommonCriminal strange.. I bought it and didn't have this problem myself so I don't think it's a bug.

I gave both of you the missing gems back, please let me know if it works now

**Comment by lemoness** [comment]
We'll be keeping an eye on this. Definitely let us know if you try to repurchase the set with your refunded gems and it does not work again.

**Comment by Indubitably1** [comment]
Thanks so much for your help guys. Unfortunately there is another related issue now.

Once I reloaded the page a couple of times to ensure it was loading correctly, I clicked "Unlock Set - 5 gems" on the Supernatural Skins and clicked "Purchase for 5 Gems." The skins then unlocked, and as I was clicking through them to try each on, a large red error spanning the right side of the page popped up, stating something like "page reload... chrome console...". As a result, 4 of the skins are now unlocked and the other 4 state that they require 2 gems each to purchase.

**Comment by lemoness** [comment]
This almost sounds like the server is crashing in the middle of buying the
gems and is only registering buying some of them - is that possible?

**Comment by paglias** [comment]
Can someone give him a few other gems to try? im not at a computer When you
get the error you should open the console and copy here what you can find
there, the console can be opened on chrome with Ctrl+alt+j
Il 01/ott/2014 21:15 "lemoness" notifications@github.com ha scritto:

**Comment by Indubitably1** [comment]
Sure, once I receive the gems I will try again and report back here if there is an error in the console.

**Comment by k8sullyvan** [comment]
I'm pretty sure that what happened to me was pretty much exactly what happened to Indubitably1 because I did the same thing of buying the set and then clicked on one of the skins (so then it registered that skin as purchased for 2 gems, but all the others were not purchased). However I dont seem to have that problem the second time when I was re-purchasing the hair set and purchasing the skin set for the first time.

Btw, when you sorted it out for me a purchased the set you left me with 2 more Gems than you should have done. Not that you have to take them back if you don't want to ;) but in the interest of honesty I thought I should let you know

**Comment by lemoness** [comment]
@Indubitably1 What's your UUID? I'll refund you so we can try again.

Also, reopening this issue until we decide what's happening.

**Comment by Indubitably1** [comment]
UUID: 57aef3cc-7fe3-4d34-bbb2-26260c83d616

**Comment by lemoness** [comment]
Okay, reload and try now.

**Comment by Indubitably1** [comment]
I purchased the set and everything seems to be working perfectly now, thank you!

BTW, for the purpose of full disclosure, I use a Firefox add-on called NoScript and to ensure that it wasn't interfering with the site I made sure to enable the only two sites that it was blocking before making the purchase: googleusercontent.com and google-analytics.com. It has never been a problem before when using HabitRPG but I wanted to share that info in case there is some connection.

**Comment by lefnire** [comment]
Guarantee this was memleak site downtime issues, no bug - just see [how bad it was](http://gyazo.com/213531a961de468e91be8d7e5c6c6b05) when @Indubitably1 would have made the purchase. Sorry for the inconvenience @Indubitably1! Thanks @lemoness & @paglias

**Comment by lemoness** [comment]
Glad everything is working! I'm going to leave this open for another day so
that if anyone else has problems, it will be easy for them to find, and
close it tomorrow if we don't hear anything else.

**Comment by lemoness** [comment]
Okay, that's a relief!

Sort of, anyway.
