### ISSUE TITLE
add todo by email/evernote

### ISSUE THREAD

**Issue by fro0m** [HabitRPG/habitica#41]
_Note by wc8: Vote for these requests here: [Google Calendar](https://trello.com/card/google-calendar/50e5d3684fe3a7266b0036d6/77), [Email Sync](https://trello.com/c/hxt5ApKM), [Zendone](https://trello.com/c/ExxNsQek), [Evernote](https://trello.com/c/9eJgSgSa)_
This need to make be able to sync with many GTD services

**Comment by lefnire** [comment]
On the roadmap, see [service integration](https://workflowy.com/shared/da537e4b-73fa-f8c7-64ed-3fb2526db98b/)

**Comment by fro0m** [comment]
well, where is the email integration??
Do you know the great GTD service Zendone?

**Comment by ghost** [comment]
Include syncing with Google calendar

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote for these requests here:
[Google Calendar](https://trello.com/card/google-calendar/50e5d3684fe3a7266b0036d6/77)
[Email Sync](https://trello.com/c/hxt5ApKM)
[Zendone](https://trello.com/c/ExxNsQek)
[Evernote](https://trello.com/c/9eJgSgSa)
