### ISSUE TITLE
I bought halloween hair set for 5 gem, it gave me 4/8 items and charged 8 gems

### ISSUE THREAD

**Issue by kb-code** [HabitRPG/habitica#4100]
i just bought the seasonal edition halloween hairstyles today (the day of their release).  I bought the whole set for 5 gems and was charged that, and they all displayed as available, I put on on my avatar and logged off.  Then I logged back on later in day and now only 4/8 items are enabled, and i have been charged 8 gems, which appears to be the price for each individually.  Have refreshed and synced with server, and items are still asking me to purchase for 2 gems even though I bought the whole set.

So in all, I need 4 more hairstyles enabled and 3 gems refunded...

There was a game server error during this time, but hopefully that didn't have anything to do with this...

**Comment by lemoness** [comment]
Unfortunately, the server error almost certainly had something to do with
this. We're so sorry! What's your UUID? I'll restore your gems so that you
can buy them again.

**Comment by kb-code** [comment]
ah yes, I did forget that part :)  thank you much for your assistance!  

As it stands now, I have 4 more skin styles showing as unbought... so either if you have ability to reset inventory items you can reset halloween skins set (I misspoke before saying hairstyles, it was the skins) and refund 8 gems so I can buy whole set again, else refund 11 gems and I can use them to individually purchase the missing 4 items for a total net cost of 5 gems for the set.  Really appreciate you looking into this, did fear it may have been a timing thing with the server... thanks again!

UID: cf1ba132-f177-4865-a6b6-d16bcb89e5c0

**Comment by paglias** [comment]
@kb-code refunded you 11 gems, sorry for the issue!
