### ISSUE TITLE
Skills Not Working

### ISSUE THREAD

**Issue by AApichu** [HabitRPG/habitica#4102]
Hi all, I recently started Habit, and just got to level 11 as a rogue. I should have unlocked the Pickpocket skill, as it says on the wiki, but I didn't. I tried reloading, then logging out and clearing my cache/history, to no avail. Can anyone help me with this? Thanks!

**Comment by deilann** [comment]
Where are you looking for it? Can you upload a screen shot?

**Comment by AApichu** [comment]
![image](https://cloud.githubusercontent.com/assets/9001653/4499994/3624659e-4a8a-11e4-9c53-b339ace25d27.jpg)

The bar doesn't show a plus sign, where I can cast the skill, and I had to pop up indicating I had unlocked the skill.

**Comment by deilann** [comment]
The spells are below the item store on the right by your rewards.

**Comment by AApichu** [comment]
Okay. I see it. It wasn't showing in my browser earlier. Thanks!
