### ISSUE TITLE
Switching classes -- skills did not change

### ISSUE THREAD

**Issue by KellenM** [HabitRPG/habitica#4105]
I switched classes from healer to rogue and it seems like my skills are still stuck as healer skills. (Another quirk: I couldn't dismiss the "tour" of the new class so I refreshed the page instead.)

**Comment by deilann** [comment]
Try logging out and logging back in.

**Comment by KellenM** [comment]
Hm, I should have probably tried that first. I tried logging out twice, the second time I cleared  cookies too, but even so, it's still mismatched.

**Comment by deilann** [comment]
Can you throw me up a screenshot and copy paste your uuid for me?

**Comment by KellenM** [comment]
Sure, although now that I'm refreshing, logging in and out, etc. it seems to have actually pushed the whole thing back instead of forward -- the class is now showing as healer again. This also explains the odd moment where, halfway through picking out which gear to put on my newly-converted rogue, I got an unexplained boost in mp. That must have triggered when the healer bonus to intelligence kicked in again.

I guess what I'm seeing here now is maybe more like the class conversion failed to stick. Is it possible to do two class changes within too short an interval of time?

UUID is d718e5a4-6873-4e94-8d66-768d666a273e. I'm not sure a screenshot would help at this point, but if so, what exactly should I snap a picture of?

**Comment by deilann** [comment]
Did you end up losing 3 gems or did those show back up? I was pretty sure
that's what happened... wanted to see your stats page to see what class you
were.

**Comment by KellenM** [comment]
Of course, this would happen at the end of my monthly "buy a bunch of gems and then spend them on all the new stuff that costs gems" spree, so I'm really not even sure what the right number of gems is. It doesn't really matter that much. Maybe it's a sign that I should be playing as a healer for a while.

On the bright side, it sounds like I just changed classes too quickly and things didn't synch up properly, which is better than some kind of real bug.

**Comment by deilann** [comment]
Thats what it sounds like to me. If I don't get to it first, someone
will.toss you 3 gems just in case you lost them. :)

**Comment by KellenM** [comment]
Cool, thanks. When I change classes in the future, I'll pay attention carefully in case anything else weird happens.

**Comment by deilann** [comment]
Gems sent :)
