### ISSUE TITLE
Inspecting a player shows the equipment of the previously inspected player

### ISSUE THREAD

**Issue by adamhollett** [HabitRPG/habitica#4107]
When I click to inspect a player, say, in the tavern, the Equipment listed for that player is actually the equipment of the last player that I inspected. This does not affect the first inspect that is performed in a session.

For example, I view the tavern and inspect **John**. John's equipment is displayed in the inspect window. I then inspect **Clara**. Clara's Equipment section lists John's equipment. If I then inspect John, John's Equipment section displays Clara's equipment.

**Comment by adamhollett** [comment]
This looks like it may be a duplicate of issue [2010](https://github.com/HabitRPG/habitrpg/issues/2010). Sorry.

**Comment by Alys** [comment]
Thanks @admhlt! I'm closing this.
