### ISSUE TITLE
Site was Down ~ Midnight Central Time

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4110]
At about midnight, the site went own, saying there way an application error. On the rare occasion I got signed in, I got a jumble of everything. This meant that I got enough damage to be killed and presumably damaged my party. I've gone to fix the character values, but it is a real pain.

I tried to access the site from a proxy in a later time zone, but couldn't log in.

It seems like there are some real problems there.

**Comment by yscali** [comment]
Site down on West Coast, too! I get "Application Error" when I try to log in on my pc. Tried my mobile app and the sync just keeps spinning and spinning....Help!

**Comment by lemoness** [comment]
Is it working for you guys now? Just checked and it seems to be functioning
for me. Very sorry about this! We've been having server troubles due to the
memory leaks, and they're close to being fixed, but not entirely.

**Comment by yscali** [comment]
Working this morning, although I did die and had to fix my character values. Thanks!

**Comment by ghost** [comment]
Yes, same thing as yscali.

I started working again for me at maybe 12:30 Central time. I did die and had to fix character values.

**Comment by lemoness** [comment]
@Nortya @yscali We are so sorry :( Glad that it's working again, and that you were able to fix character values. We're working very hard to eliminate the last of the memory leaks. Let us know if you have any more trouble!
