### ISSUE TITLE
Multiple Errors, Not Saving Progress

### ISSUE THREAD

**Issue by rlquinn1980** [HabitRPG/habitica#4111]
Beginning within the last few hours, my HabitRPG is no longer saving my progress. After completing tasks by checking them off, a reload of my tasks list reveals that these items are still listed as incomplete. On some loads, my party disappears from the interface. On others, they appear, but the glamour I put on some of them (the Spooky Sparkles for Halloween) does not appear to be in effect, though I used it earlier in the same day. Guild pages are also not completely loading. 
![screen shot 2014-10-04 at 4 06 15 pm](https://cloud.githubusercontent.com/assets/8965972/4514868/9c34f5c2-4b95-11e4-8d01-18f9ed05cb1b.png)

**Comment by lemoness** [comment]
Is it working for you now? We've been havin server troubles due to the
memory leaks. They're getting closed to fixed, but we're still not fully
there yet. We're very sorry about this!

**Comment by rlquinn1980** [comment]
Thanks for checking up on me!

I'm away from home, and now it seems to be working on the app and the site via the iPod version of Safari. I'll check again when I get to my home computer, but looks good so far.

Much appreciated!!
