### ISSUE TITLE
Shaft of the Dragon + Nameless Helm drop after quest repeat

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#4115]
Hey there. I don't mean to rock the boat, but this most recent rebirth I re-received the Shaft of the Dragon and the Nameless Helm upon re-completion of the Vice and Laundromancer quest arcs respectively. I don't know whether that's supposed to happen, or whether it is something with my account and not with others, but I figured I'd speak up and say something, despite the snazziness of getting free items.

I also want to confirm that you're supposed to re-receive the Vice Part 1 quest at Level 30 and the Laundromancer Part 1 quest at Level 15. Just making sure I'm not going crazy about that either.

Thanks again for the hard work!

**Comment by Alys** [comment]
This is all expected and desired behaviour. Rebirth is meant to put you into a state very similar to that of a new player. All (or at least almost all) the features that a new player experiences are going to be experienced again after rebirth.

**Comment by HSalgo** [comment]
Cool, just making sure, since the Wiki says that the items don't drop again upon re-completion. In past rebirths, the items never redropped--maybe this is a result from my last [now closed] inquiry from https://github.com/HabitRPG/habitrpg/issues/3967?

**Comment by deilann** [comment]
Mmm the items can't drop again upon re-completion if you own them. But
after rebirth you don't own them anymore.

**Comment by Alys** [comment]
Ah, good point about the wiki, we'll get that fixed up. What the wiki is trying to say is that you can't ever own two Nameless Helms at the same time.

The Rebirth code is under frequent improvement as people report problems with it, so it's not surprising that you're seeing slightly different (better, hopefully) behaviour this time around.
