### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by stimulus2da** [HabitRPG/habitica#4118]
On Chrome Version 37.0.2062.124 m, I cannot load HabitRPG at all. I get "Application Error An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details."

I tried clearing the cache and reloading the page to no avail, so I assume the server is having issues. Unless, of course, someone royally broke something ;-)

**Comment by cdepillabout** [comment]
I have been experiencing this issue for the past couple hours.  What's going on?  
Is this being caused by #4079 ?

(I get completely flustered when I can't log into HabbitRPG.  I don't know what to work on :-p )

**Comment by MagBag** [comment]
The same application error message is occurring for me on both Chrome Version 37.0.2062.124 m and Firefox 32.0.3 browsers.

**Comment by ndfelps** [comment]
Getting the same error in Chrome, Firefox, and IE. Tried a cache kill and mashing the refresh button in a panic. Another person in the building I'm in is also generating the same error in Chrome.

I, too, dunno what to work on now! Gonna sit around and look busy until further notice. D:

**Comment by negue** [comment]
Don't worry, the devs are on it. 

The last few days this Error comes and goes randomly :(

There is nothing we (and you) can do about it, just wait, while it get fixed^^ .. again.

**Comment by cdepillabout** [comment]
Looks like it is back up for me.  Thanks devs!

**Comment by stimulus2da** [comment]
Ditto, back up and running. Cheers!

**Comment by lefnire** [comment]
#4079

**Comment by cdepillabout** [comment]
This seems to be happening again.

**Comment by lemoness** [comment]
Alas, it will continue to happen periodically until
https://github.com/HabitRPG/habitrpg/issues/4079 is fixed, but we're
working on it with all we've got! You can subscribe to that thread to get
updates as they occur. We're sorry about all the hassle!
