### ISSUE TITLE
Boss Damage not Calculated for One Party Member

### ISSUE THREAD

**Issue by MagBag** [HabitRPG/habitica#4120]
I am in a party of two people, both party members being my own accounts under different names.  I log in using different browsers pretty much simultaneously, to view the results of the quest I am doing with myself.

After logging in today and refreshing my party information for both accounts for the day, I noticed that one party member is not showing as having done any damage to the boss I am fighting, while the other person in my party is.   There seems to be nothing else amiss between the two party members or the two accounts, but an update for damage to Vice is showing in the chat for only one party member, not the other -- this is true for both party members' pages, only the one shows as having done damage, while the other is simply not mentioned.  No damage is mentioned either to the boss or to the missing party member.  The party member in question had completed all dailies yesterday as well as several hefty to do's so there should have been damage.

The party member not showing as having done or received any damage is User ID 99e9a8f7-57c5-49a7-870d-f4ff46f2439b.

The party member showing as having done damage is User ID 6c537d6c-d184-4ca3-9964-c2b2d87002d1. (The party member is the quest owner)

Thanks for looking into this!

ETA:  This is the first time this has happened; prior to this I have been having no trouble with damage calculation between the two parties.  I have done numerous quests together with myself in this fashion and have not had any issues until today.

**Comment by Alys** [comment]
This happens occasionally and usually is only a temporary problem. It has been reported before at https://github.com/HabitRPG/habitrpg/issues/2613. You can subscribe to notifications for that issue if you want to follow the progress.
