### ISSUE TITLE
Experience graph missing [$10]

### ISSUE THREAD

**Issue by jdeut** [HabitRPG/habitica#4121]
Hi all,

i have just deployed `habitrpg` on my local machine. After i registered a testuser i gave him admin status and i played around with setting the various items which i accessed through `http://localhost/#/options/groups/hall/heroes`.

Unfortunately i can't figure out how to enable the experience graph. The bars at the top of the page still looks like this

![screenshot from 2014-10-07 17 12 06](https://cloud.githubusercontent.com/assets/1739296/4544595/9225301e-4e34-11e4-8b77-0e11ce6b5b3e.png)

in contrast to pictures like the following one

![screenshot from 2014-10-07 17 17 37](https://cloud.githubusercontent.com/assets/1739296/4544658/1cb3ca56-4e35-11e4-948c-c556f91db4e5.png)

where a little progress chart icon is placed at the right of the experience graph.

I would be very grateful for any hint how i can enable this feature since i know i respond better to visual feedback.

Best regards
##

**Comment by paglias** [comment]
@nichtleiter try checking out some tasks or waiting for the first cron to run, as you can see here it's enabled when history has some values in it https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/header.jade#L21
