### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by jklein** [HabitRPG/habitica#4123]
This error appears:

`npm WARN deprecated guid@0.0.12: Please use node-uuid instead. It is much better.`

I grepped the code and it looks like the guid npm module isn't actually used anywhere. Can we just remove this from `package.json`?

**Comment by paglias** [comment]
It's already removed in another pr that we're currently testing on
beta.habitrpg.com because it contains a lot of upgraded packages and we
want to be sure nothing breaks.

Thanks anyway
Il 07/ott/2014 20:17 "Jonathan Klein" notifications@github.com ha scritto:

**Comment by paglias** [comment]
#4097
