### ISSUE TITLE
Daily Not Showing Checklist

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4124]
So I created a new Daily with two items in the checklist (brush teeth twice a day: morning and night). However, these items are not displaying. The Brush Twice Daily is there, it says 0/2, but none of the checklist shows. My To-Dos still show a check list.

**Comment by deilann** [comment]
Click on the 0/2. It sounds like you collapsed it.

**Comment by ghost** [comment]
Thanks! Sorry about that! I had no idea they collapsed!
