### ISSUE TITLE
Regularly Losing Updates just before custom start time

### ISSUE THREAD

**Issue by lostgrail** [HabitRPG/habitica#4125]
This looks to be very similar to #3757 

I have a custom start time of 9am. Regularly, I will arrive at work between 7 and 8, and make sure I checked all my dailies from the day before. Then I will log off, let the day start, and go back to fill in anything I've accomplished for the morning.

This morning, I died again. I hadn't logged on at all yesterday afternoon, so my last update was at 8:2-something this morning, when I basically filled in all of my dailies. When I logged in just now, I had died. I'm ok with dying (it sucks) but today I lost one of my special edition items (Candy Cane Staff form Winter 2013) as part of that death, which is very frustrating. I was proud of that, even if I only used it as a piece of costume.

I have not checked the Data Display Tool, as suggested by #3757, as I only just came on here to look. I will watch that like a hawk from now on.

As an aside, is there anyway I can get my item back? Gold and XP I'll re-acquire, but that item is not available for purchase when I do get my gold back.
##

**Comment by lostgrail** [comment]
Ah, I see I can buy the staff back. So I feel a bit better about this whole death-experience. Still, it would be nice to not have died in the first place.

**Comment by lemoness** [comment]
In addition to that, you can also restore your stats using Settings > Site

> Fix Character Values! I hope that helps some.

**Comment by paglias** [comment]
Reopen if it occurs again
