### ISSUE TITLE
Purchased Gems Disappeared from Account

### ISSUE THREAD

**Issue by RedPhoenix1** [HabitRPG/habitica#4126]
I'm not sure if there is a way that someone can verify this or assist me, but I am hoping you can.

About 4 days ago I purchased 7 gems and today I noticed that they have disappeared. I did not spend them, as I am waiting to collect enough gems to purchase a set of backgrounds. There have been some errors lately when I try to use the account and often I have to reload the page multiple times in order to use the site, but I don't know if this is related. '

Please let me know how I can rectify this. Thanks!

**Comment by lemoness** [comment]
What's your UUID? Do you have a transaction receipt? We'll look into this
for you - sorry about the frustration!

**Comment by RedPhoenix1** [comment]
UUID: ffe20133-95fc-4a47-8b6e-859b2720e60d

Thank you, I appreciate your help! 

I am a subscriber and purchased the gems through the Market, so unless it is generated somewhere I am not aware of, I don't have a transaction receipt.

**Comment by lemoness** [comment]
Hm - buying from the Market? Did you notice if the gold you used to buy
them got refunded? That sounds like maybe the purchases didn't go through,
in which case you would have gotten the gold back.

**Comment by RedPhoenix1** [comment]
I know that the gems I purchased were in the account for at least two days past their purchase, and that I had used all the gold in my account to purchase them. A refund of 140 gold has not appeared, and the only gold I have now is what I have earned in the meantime.

**Comment by lemoness** [comment]
Refresh your page - you should have the seven gems back. Let us know if there's any more trouble!

**Comment by RedPhoenix1** [comment]
Thank you so much, I really appreciate your help!
