### ISSUE TITLE
Restarting the server kills query motifs

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#413]
When I restart the HabitRPG server, I get "Unauthorized: No access control declared for motif withId" for all the clients trying to reconnect. It's not just withId, but all the query motifs I declared & which have access control. I have to kill and start the node process 2-3 times for this to go away, then it's smooth sailing. See [this thread](https://groups.google.com/forum/?fromgroups=#!topic/derbyjs/WOuI1Ca-vzs) for some more background info. 

@switz looping you in just in case

**Comment by switz** [comment]
Still working fine locally. Will look into this more tomorrow.

**Comment by lefnire** [comment]
PS, hope it doesn't look like i'm nagging you on it - just shuffling / organizing things around, don't start anything until you're back from vacation ;)

**Comment by switz** [comment]
I watch the habitrpg repo so I get every post anyway ;)

**Comment by lefnire** [comment]
Gotcha biotch! https://github.com/lefnire/derby-auth/commit/08b0499c414ef7d4e00b0f23068220b8f3280c1f and https://github.com/lefnire/habitrpg/commit/be4c05ca4fe0fa102c3877738ffbaa2a29748b75 . But now we're back to #322 :( Oh well, it's a better critical bug lol.
