### ISSUE TITLE
HTML tags showing as text in Fiery Gryphon quest completion screen

### ISSUE THREAD

**Issue by chadschultz** [HabitRPG/habitica#4130]
Screenshot: 
![image](https://cloud.githubusercontent.com/assets/1164989/4579888/d8e5b7ce-4fd0-11e4-8a19-25a82ab5e4f6.png)

**Comment by Alys** [comment]
It's been reported before: https://github.com/HabitRPG/habitrpg/issues/3736  but I'm closing the old one and leaving this new one open for the nice screenshot.

**Comment by crookedneighbor** [comment]
@alys Is Habit using Angular UI to manage the pop-ups?

**Comment by crookedneighbor** [comment]
Never mind, I see @chadschultz found a solution.

**Comment by chadschultz** [comment]
My apologies. I want to improve what I did and then merge my code into HabitRPG proper. I'm new to Github and the HabitRPG codebase, so I'm fumbling through, and lost track halfway through.
However, I will note that what I did is not a fix so much as avoiding the issue altogether. I see in the translation files that HTML tags are used in multiple other ways; I don't know if they experience the same issue, but if so there is still an HTML rendering bug that needs to be addressed.

**Comment by crookedneighbor** [comment]
@chadschultz Okay, I will continue looking into a fix for it.

**Comment by crookedneighbor** [comment]
Found the answer:
https://docs.angularjs.org/api/ng/directive/ngBindHtml

**Comment by crookedneighbor** [comment]
@Alys @chadschultz 
this should do it, I think:
https://github.com/HabitRPG/habitrpg/pull/4162

**Comment by chadschultz** [comment]
Great, go for it!

If I get around to figuring out github and applying my changes, it will simply be making minor text changes (standardizing how PC names are displayed, for example) and would not be related to this bug. Thanks for making a real HTML processing fix, @crookedneighbor !
