### ISSUE TITLE
static/api page is down

### ISSUE THREAD

**Issue by pedercody** [HabitRPG/habitica#4131]
The api documentation page appears to be down at https://habitrpg.com/static/api.  Visiting the page with the link on the main page or through a Google search both return error messages. 
Instead of displaying a page, the browser displays:
<code> {"err":"/app/views/static/api.jade:1\n  > 1| doctype 5\n    2| html\n    3|   head\n    4|     title Swagger UI\n\n`doctype 5` is deprecated, you must now use `doctype html`"}</code>

 This has been the case for at least half a day now, but not much longer.  Similar url's like static/features and static/privacy don't have issues.  I've tried connecting with it repeatedly on Firefox 32.0.3, but I've also tried Chrome and a Dolphin browser over a 3g network, and they all return the same error.

**Comment by lefnire** [comment]
1fbf3a7

**Comment by paglias** [comment]
Sorry about this, it was my fault in a previous commit, it has been fixed by @lefnire but not yet online

**Comment by lefnire** [comment]
Live
