### ISSUE TITLE
Challenges endpoint is returning 500 - Runner error: Overflow sort stage buffered

### ISSUE THREAD

**Issue by trashhalo** [HabitRPG/habitica#4132]
Runner error: Overflow sort stage buffered data usage of 34177031 bytes exceeds internal limit of 33554432 bytes
##

**Comment by lefnire** [comment]
This is an important one. NewRelic shows the error periodically - I can't replicate on any of my accounts (and I haven't heard it reported by anyone yet before this) - so presumably it's for users subscribed to many challenges. 34 megabytes of challenge data is a crap-ton, considering it's stores as text, and the `.find()` op is [widdling down the data substantially](https://github.com/HabitRPG/habitrpg/blob/1fbf3a7eba58c7de14e282b848b0e74a9fd71ac9/src/controllers/challenges.js#L30tL40) (the match and projection should be slimming it down a lot). My _hunch_ is that [$elemMatch select](https://github.com/HabitRPG/habitrpg/blob/1fbf3a7eba58c7de14e282b848b0e74a9fd71ac9/src/controllers/challenges.js#L40), which is required for the subsequent populates - but maybe it's putting all user data into the query before running the sort? I'm gonna experiment with an aggregation framework alternative soon and get back to you

**Comment by trashhalo** [comment]
I'm a new account. It started happening after joining adhd guild which I can't seem to leave either (same error). If you need anything from me let me know!

**Comment by lefnire** [comment]
[UUID?](http://habitrpg.wikia.com/wiki/API_Options)

**Comment by trashhalo** [comment]
4d282319-1d04-464f-a9f1-a35182d4b1e0

**Comment by lefnire** [comment]
Thanks @trashhalo , may be a few days before I can peg this but that helps.

**Comment by lefnire** [comment]
and 'Fievel goes West' rocks

**Comment by trashhalo** [comment]
@lefnire :star: you just earned yourself another subscription!

Oh and problem is no longer occurring. Intermittent bugs are the worst.

**Comment by lefnire** [comment]
Ode to intermittent problems indeed, as I hadn't done anything to fix yet.
I've been investigating though, I'll keep you posted!

**Comment by yhimmel** [comment]
Hi,
Same issue here. 
"Please reload, "Error Runner error: Overflow sort stage buffered data usage of 37133511 bytes exceeds internal limit of 33554432 bytes" (see Chrome console for more details)."
Occuring when opening Challenges list  (I opened it earlier today but now it cannot be opened) and also I cannot leave guilds I joined.
**New account. Currently not subscripted to any challenges.**
User ID cf32be28-9e50-494e-8490-08124fbc042a
Windows XP; Noticed in Firefox and Chrome. (Tried refreshing, opening and re-booting the computer, didn't help)

**Comment by LeelooMina** [comment]
"Error Runner error: Overflow sort stage buffered data usage of 35801693 bytes exceeds internal limit of 33554432 bytes"

I also am getting this error. I'm a new user. I joined 4 guilds, just checking things out, before looking at the challenges tab and receiving the error. I cannot leave any guilds nor see any challenges. The guilds I joined were: "The Scholars" "Challenge... Accepted?" "The Health Nuts" and "ADHDers Guild". Please help?

**Comment by elenelsecchio** [comment]
Hi there.
Same issue, first time web-interface user. Had joined one challenge (Organ donors), visited Guilds, joined Challenge Accepted guild and Ghost Ship guild, wanted to leave Challenge Accepted guild and find organ donor challenge in Ghost Ship Guild, and that's when I started getting the message. Now it appears also when I try to view Challenges.
Noticed on Chrome (Windows Vista) and on Chrome app (Android 4.4)

**Comment by sschmidt01** [comment]
Same error, cannot leave group. Chrome/Firefox (Windows 64-Bit)

**Comment by litenull** [comment]
@lefnire Seems like new mongo bumped the limit a bit.
http://docs.mongodb.org/manual/reference/limits/#Sorted-Documents

Also, you can try experimenting with allowDiskUse, which saves data to temporary files.

**Comment by theglitchedhero** [comment]
Having the same error as most of these people. I have joined 3 guilds and tried to leave one that was inactive. I joined a challenge but it's not appeared. I get this error:

Error Runner error: Overflow sort stage buffered data usage of 33866251 bytes exceeds internal limit of 33554432 bytes" (see Chrome console for more details).

My user ID is: d7749f2f-cb09-4ede-94aa-75e315312c98
I'm using Windows 8.1 and using Chrome Version 39.0.2171.95 m

**Comment by Alys** [comment]
@theglitchedhero Your account shows that you have joined one challenge, but that challenge doesn't actually have any tasks in it, which is probably why it looks as if it hasn't shown up. Could you tell me though, does a tag for the challenge appear in your list of tags? 

If that error keeps happening for you when you try to take an action on the site, tell me what that action is and I'll see if I can fix the problem.

**Comment by theglitchedhero** [comment]
@Alys I got rid of the tag yesterday when I was trying to get rid of it. It was the meditation tag.

But it seems to be working today. I got a few unable to reach server errors, but now that I'm back home everything works.

**Comment by lefnire** [comment]
TMK, this error can occur for anyone, regardless of their own groups / user object. I _think_ it occurs for the first time someone loads up the challenges page, and then mongodb will cache the query for near-future queries. @litenull we're already on that version of mongo, alas - but I'll look into disk usage thingy.

**Comment by ladyvoldything** [comment]
I'm having the same error. I'm really new to HabitRPG, so I'm not really sure what I'm doing wrong. I tried joining my first guilds, and when I tried to look at their challenges, it keeps taking me to MY "challenges" tab, which is blank except for the green button and the angry red error message. 

It happens every time, no matter how many times I refresh, with every guild. I can't look at any of the challenges, I can't do anything with a guild at all. Help! What do I do?

**Comment by ladyvoldything** [comment]
It also is not letting me leave my party. Which is a problem, since it's a solo party and I want to join a real one. This is really screwing with my ability to be a part of the game.

**Comment by crookedneighbor** [comment]
I'm sorry you're having those issues. 

Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token). This should give us some info to figure out what's going on.

**Comment by ladyvoldything** [comment]
Sure. 
d0e22b31-10f3-4ec3-8c50-99ea3cc350f7

**Comment by crookedneighbor** [comment]
Hmmm... don't see anything particularly weird. Maybe another dev with direct access to the DB could look further.

In the meantime, let's take a look and see if Google Chrome can report any errors for us.

[Here's a download link for Google Chrome.](https://www.google.com/intl/en/chrome/browser/desktop/index.html)

When on the HabitRPG site while using Chrome, press `crtl + option + j (pc)` or `cmd + option + j (mac)`, that should bring up the console. From there, try to go to a challenge and then try to leave your solo party and record what is says in the console. Either copy and paste the text, or take a screenshot.

If you're having trouble, let me know!

**Comment by Alys** [comment]
These sort of problems tend to be temporary and purely in the browser, rather than due to any database issues - i.e., there'll be nothing wrong with ladyvoldything's account. The problems tend to fix themselves after a couple/few hours. We could adjust the database data manually, but it's a bit risky and not the ideal solution - definitely a last resort if there's still problems after a day or two that we can't resolve in other ways.

**Comment by crookedneighbor** [comment]
Good to know @Alys. Any idea what causes it in the first place?

@ladyvoldything can you update us in the next two days and see if you're still having trouble?

**Comment by Alys** [comment]
Just what lefnire wrote above in various comments. I've had no useful thoughts of my own. :)

**Comment by binarily** [comment]
One question: is request payload supposed to be this big? It seems that it's sending whole challenge object back to server.

**Comment by RavenEternal** [comment]
Signed up just to share this info: I had the same problem and what helped for me was clearing out all the junk in chrome. Like cookies, browserhistory etc. No probs anymore! :D

**Comment by lefnire** [comment]
If my theory is correct above, then the solution to this is simply: if you hit this issue, wait a minute and try again. Mongo will cache the query and on a second attempt will send the cached response. Caching the result may take a while, so doing a refresh _immediately_ after probably won't cut it - just wait a minute or two and refresh. Obviously not a perm solution, just a temp workaround

**Comment by binarily** [comment]
Unfortunately, it doesn't seem to work. 

Also, what surprises me is that everything else works, including challenges that surpass Fight Back Against Depression in terms of number of members. It's only this challenge that throws 500.

**Comment by kjdomanog** [comment]
Getting this issue as well, I got it from looking on challenges on Artist Guild(Group ID: dea7a124-9e69-4163-a708-d3e961a96159) 

this is my user id(0e676d8a-8c30-476f-9365-2efed35c3c68)

error:(Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33577261 bytes exceeds internal limit of 33554432 bytes" (see Chrome console for more details).)

**Comment by quetzalpie** [comment]
Getting this also when trying to view the challenges page (and when I try to submit a new challenge). User id: 5d204be3-6c6e-4cbd-bb5a-369690df79f7

Happening in multiple browsers (Safari and Firefox on a mac, have not tried Chrome).

Edit: appears to be working today, never mind!

**Comment by alestanis** [comment]
Same error here. I joined one challenge yesterday (CdT April). This started happening after I created a Party for myself this morning.

Group ID: 7a3b5255-901b-4a58-8c61-305bd75177cd
User ID: c5a8c2cc-5a4e-4526-abdc-a33b0fbbddc5

Console errors on Chrome:
GET https://habitrpg.com/api/v2/challenges 500 (Internal Server Error)

Mixed Content: The page at 'https://habitrpg.com/#/options/groups/challenges' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700'. This request has been blocked; the content must be served over HTTPS.

Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by alestanis** [comment]
Might be useful (the ensure_index thing):
http://stackoverflow.com/questions/27023622/overflow-sort-stage-buffered-data-usage-exceeds-internal-limit

**Comment by wrrrg** [comment]
Having the same bug across multiple browsers after joining a few challenges and Scholars guild.

**Comment by hmaida008** [comment]
i am having the same error .. i started my own group .. but now that i want to leave it and play with other people , this error keeps showing up

**Comment by mperez07** [comment]
Running into the same issue as above user loading the challenges page.

"Error Runner error: Overflow sort stage buffered data usage of 36673809 bytes exceeds internal limit of 33554432 bytes" 

User ID: 1ae80ebc-f6bf-4cbf-b601-79c456f51e57

It occurred after joining a couple of guilds (page was previously functioning fine) and without joining any challenges. Using Chrome. Console displays "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" (or similar internal server error issue) on every reload of the page. Reloading after several minutes or logging in/out does not resolve issue, nor does trying on Firefox rather than Chrome. Similar to other users above, I am also now unable to leave a guild without also generating the overflow error.

**Comment by Alys** [comment]
@mperez07 Which were those couple of guilds?

**Comment by mperez07** [comment]
Scholars, Life Hackers, The Health Nuts, Writers, Mentally ill,
Duolinguists of Habitica, all large guilds with lots of challenges. About
6-7 hours later, I tried again and had no issue. I was able to leave the
Scholar's guild and haven't run into the situation since.

**Comment by paglias** [comment]
Hopefully this is fixed in v3
