### ISSUE TITLE
Unlock Item Store at Level 1

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4134]
I've been talking to some new users and getting feedback from people, and I think that the Item Store should already be unlocked at Level 1 when you start the game. 

Some reasons:
1. There is no indication that there will ever be an item store, so new users think that they have to set all the Rewards themselves, which many find demotivating because they can't think of any.
2. Similarly, new users may feel that they have nothing concrete to strive towards because some people don't find custom rewards motivating.
3. New users frequently post in the Tavern that they don't know how to regain health - having the Item Store makes the health potion available from the start, which is useful for people especially when they're figuring out their initial balance.
4. We recently got a scathing Twitter review accusing us of being Pay-To-Win, because the only character customization items available to Level 1 players are the gem-purchasable ones under the Avatar Customization page, and there is no indication that you'll ever be able to buy character customization options with the gold you earn for doing your tasks.

I understand the idea behind unlocking things slowly to avoid confusion - it makes perfect sense with big features like Drops and the Class System - but the Item Store is very intuitive (click to buy!). Plus, it's one of our most motivating tools. I don't think that we should hide it away.

**Comment by Alys** [comment]
I like all your reasons. I agree.

**Comment by thepeopleseason** [comment]
:+1:

**Comment by deilann** [comment]
+1

**Comment by lemoness** [comment]
Is this a tough change, code-wise? Would it be a good candidate for an
aspiring coder, or is it deeply wrapped up in other things, requiring
substantial testing?

**Comment by lefnire** [comment]
We thinking it's unlocked from the start (never locked in the first place), or unlocked sometime during lvl 1? (say, after the first couple clicks or so)?

**Comment by lefnire** [comment]
Because if (B), then the change can be as simple as https://gist.github.com/lefnire/a0782fe7c24006aab9fd . If (A), then maybe more change is necessary (eg, re: Justin Guide, etc)

**Comment by Alys** [comment]
(B) immediately and then (A) later?

**Comment by lefnire** [comment]
SGTM

**Comment by deilann** [comment]
+1

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg-shared/commit/d843ff1ae460db697335a962f226fe74ad9d420e

**Comment by Alys** [comment]
There's something unnatural about fixing an issue 30 minutes after it was logged. :)

**Comment by deilann** [comment]
+1 to that, Alys

**Comment by lemoness** [comment]
Heh, seems good! You're a veritable speed demon ;p

Out of curiosity, how many clicks is it until it unlocks?

Ideally it will eventually be unlocked from the beginning, but I think if
it's after the first experimental click, that's a pretty good stopgap!!

**Comment by deilann** [comment]
How many clicks does it take to get to the center of a HabitRPG item store?
The world may never know.

**Comment by lemoness** [comment]
Hmm, if I had to guess, I would have to say...... +1.

;)

**Comment by lefnire** [comment]
~10 clicks? IIRC each click is worth 1 pt to start, so we can lower as
needed. I only hit it fast since I had the fix top of the dome

**Comment by lemoness** [comment]
Yeah, I'd say lower. Can't expect them to stick around for ten clicks.
First click?

**Comment by lefnire** [comment]
tested, turns out it's more like 2-3. That ok?

**Comment by lemoness** [comment]
Yeah, good for now!
