### ISSUE TITLE
Overcharged for a gem

### ISSUE THREAD

**Issue by me-and** [HabitRPG/habitica#4135]
I just bought a gem from the market, and was charged 20.09 gold for it. I can obviously fix the gold amount by using the Adjust Values form, but readily fixable or not, I don't think that's meant to happen.

**Comment by me-and** [comment]
Screenshot, just in case it's useful and now I'm on a PC and can post it (I'd already scrolled to the top of the page before noticing the oddity and thinking I should screecap it):

![screenshot_2014-10-10-08-40-24](https://cloud.githubusercontent.com/assets/1397507/4589954/56907efa-505a-11e4-8cca-14ac98422266.png)

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/4113. If you'd like to follow the progress of this issue, you can subscribe to notifications there.

At least one of the other people who experienced this noticed that they were charged the correct amount, and only the notification was wrong. Did you happen to notice how much your total gold dropped by when you bought the gem? I.e., did you notice if you lost 20.09 or exactly 20 gold? If you did notice the exact amount that was removed from your total gold, could you please add a comment to https://github.com/HabitRPG/habitrpg/issues/4113?
