### ISSUE TITLE
Task color shouldn't get red on dated tasks

### ISSUE THREAD

**Issue by hodrigohamalho** [HabitRPG/habitica#4147]
When creating a task informing a date target, the task shouldn't be marked on red until the date has beens reached.

![capturar](https://cloud.githubusercontent.com/assets/252998/4645193/d3c14364-5465-11e4-8d39-53c1e9af515a.PNG)
##

**Comment by negue** [comment]
All tasks got red because they loose "a value" over a time, which means they change the color.

See: http://habitrpg.wikia.com/wiki/Task_Value

If your task would be "too late" for the configured Date, then the Date itself "12/01" would be filled in red.

**Comment by hodrigohamalho** [comment]
I understand that, but the habit to schedule tasks in advance should be considered as a good habit.
For that reason I think the task should be color on red only after the date is reached.

**Comment by lemoness** [comment]
One of the points on this Trello card requests this as a new feature:
https://trello.com/c/i6kXvNY2/106-due-dates-urgency-due-start-expires-diseased-todos

Maybe this should be the ticket for it :)

**Comment by deilann** [comment]
Having them become red is rewarding you for scheduling the tasks earlier.
Red to dos don't hurt you and are worth more.

**Comment by lemoness** [comment]
Many people feel frustrated, however, by the high points that they then
get, which some feel are undeserved.

Maybe we could implement a start date as well as a due date?

**Comment by deilann** [comment]
I understand that. I've been all for a start date which would be optional,
but just blanket to dos with dates would cramp my style.

**Comment by lemoness** [comment]
Hm, okay - let's refocus this to be in favor of start dates, then. Should
we close this ticket, or rename it?

**Comment by deilann** [comment]
Unless someone wants to put a bounty, we don't usually do feature tickets.

**Comment by code-sculptor** [comment]
@deilann Feature??? **This is pure bug.** Would you - while creating to-dos feature - write it this way if it would cost you extra focus and few extra lines of code? I'm completely sure you wouldn't. It is simple overlook making application work not as expected and not consistent with behavior of already developed similar parts of application - and that's one of possible definitions of a **bug**.

**Comment by Alys** [comment]
As described above, we'll change this behaviour by implementing a start date for To-Dos. If a start date is set, the To-Do won't start getting red until that date has passed. This will satisfy both players who want to keep the current behaviour (they just don't set a start date), and those who want the behaviour to change. Because this new desired feature is described in https://trello.com/c/i6kXvNY2/106-due-dates-urgency-due-start-expires-diseased-todos, and because no one's put a bounty on this issue, I'm closing this issue now.
