### ISSUE TITLE
Not levelling up

### ISSUE THREAD

**Issue by philips999** [HabitRPG/habitica#4149]
Hello,

My character is not levelling up for some reason even though I have way more than enough experience. Please help!

eefad08c-4193-42dd-bea8-46b81837cccc

Thanks,
Phil

![habitrpg image](https://cloud.githubusercontent.com/assets/9252665/4646390/bee3b492-5472-11e4-95fb-925d7e3ba7d9.jpg)

**Comment by thepeopleseason** [comment]
Have you checked off any habits, dailies, or to-dos? Quest experience doesn't update character levels.

**Comment by philips999** [comment]
No, I hadn't done that. I did and I leveled up now. Thanks!

-sent from mobile-
