### ISSUE TITLE
Google calendar not importing events

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#415]
I've got due-dates implemented on the [develop branch](https://github.com/lefnire/habitrpg/blob/develop/src/server/serverRoutes.coffee#L7), which exports a `.ics` file. That file imports to Mac Calendar just fine, and the the _file_ even imports fine to Google Calendar. However, if you point GCal to the the `.ics` URL on the server (to create a synced calendar), it creates the calendar with no complaints - but doesn't import any of the tasks.

**Comment by busterroni** [comment]
I can confirm this bug, I don't use iCal but I wanted to see if the calender import option worked. I made an event in iCal called 'test' and clicked the little calender in the bottom right of 'Todos'. A page opened that said "No events found". I restarted Firefox just to make sure, and I had the same problem. I can test this on Google Chrome later but I'm on a computer that doesn't currently have Chrome installed.

**Comment by lefnire** [comment]
make sure you have at least one due date, i'm still trying to get to export an empty list properly

**Comment by busterroni** [comment]
lefnire, I'm not sure what you mean... On an unrelated topic to your post I just tested the iPhone's built-in calendar and used the Google Chrome iPhone application. I added an event to my calendar but I'm still getting the "No events found" error. I didn't really think it would work on the iPhone but it was worth testing.

**Comment by Pandoro** [comment]
I think you misunderstood the whole idea of this feature @busterroni. The
goal is not to make an item in your calendar and import it into habitrpg.
The idea is that you have todos with due dates set (in the edit menu of
each todo). Then you can export an iCal file from habitrpg, listing all
your todos with duedates. These can then be added into your regular
calendar. Not the other way around.

**Comment by lefnire** [comment]
(with the current caveat that the ical isn't syncing to GCal properly just yet, currently fixing that)

**Comment by busterroni** [comment]
Oh lol, I thought it went from iCal events -> HabitRPG where your iCal events are automatically added into HabitRPG  My bad. But I was just thinking that that feature would be pretty cool :P

**Comment by lefnire** [comment]
We'll work on that eventually, that'll require API integration /
synchronization - iCal export (and then one-way sync from Habit to GCal) is
very simple, MVP. Even though it's not working properly right now :s Hang
tight

**Comment by Bquilt** [comment]
Is it possible to export only todos that are remaining?  I just exported my todos w/dates to Google calendar and it includes all todos with dates.
Thanks for a great tool!

**Comment by wildcate** [comment]
Does the due date for tasks have any function yet apart from being able to export it to a calendar? The due date doesn't even show up when I mouse-over the task, so if I want to have the date visible in Habit, I have to add it to the notes and not the date fields.

I'd love to have an option that uses the due dates as a sort of "soft reminder" where a task will automatically hop to the top of the to-do list a given time before the task is due - such as 2 weeks before the due date. "Remind before" could be a setting in the game options for those who want this function, where you could choose a number of days between 0 (no reminding) and X.
Reminder popups and emails tend not to really work for me, but something coming up to the top of the list by itself? That would.

**Comment by lefnire** [comment]
reminders is important, I added that to the checklist at https://trello.com/card/urgency-dates-deadlines/50e5d3684fe3a7266b0036d6/106

**Comment by wildcate** [comment]
Yay, thanks!

**Comment by negue** [comment]
Can be closed and reopened, once ICS is re-implemented again?
