### ISSUE TITLE
Can't see Challenge Habits/Dailies/ToDos

### ISSUE THREAD

**Issue by chimeforest** [HabitRPG/habitica#4150]
_EDIT BY ADMIN:_

**Tasks in all challenges are currently not visible. A fix has been identified but it might be a few hours before it is applied to the website.**

**Every HabitRPG player will be experiencing this bug so you do not need to tell us if you are experiencing it too.**

_end of edit by admin. chimeforest's original comment is below_

---

72233058-41ed-4649-bfce-b8461455c089

I can not see any Habits, Dailies, or ToDos on the Challenge page. They used to show up, but not anymore. After I created a challenge I could no longer see them. It could be after I deleted the challenge, but I'm not sure.

They do now show up in:
-----Windows 8: Waterfox, Lightfox, Chrome, or Internet Explorer.
-----Android: Firefox

![habitrpg challenges bug](https://cloud.githubusercontent.com/assets/6296416/4651792/48f69236-549f-11e4-901e-d08a21bf17cc.png)

**Comment by Alys** [comment]
This is happening for many people / everyone.

**Comment by deilann** [comment]
We did have a change to challenges recently, yes? To export all data?

**Comment by Alys** [comment]
[Make export to csv button on challenges export all tasks (issue #2947) by Verabird - Pull Request #4028](https://github.com/HabitRPG/habitrpg/pull/4028) but it was merged 12 days ago so it probably went live before yesterday.

**Comment by Alys** [comment]
Using the API, I can see the tasks for various challenges, so this is just a display problem. It is not that all the tasks have been deleted.

**Comment by ephydriad** [comment]
Augh, I'm having this problem too - right after I'd just set up a challenge for my guild. Glad to see it's not just my machine, though... still hope it gets resolved soon :/

**Comment by Alys** [comment]
Looks like this commit is the problem:
https://github.com/HabitRPG/habitrpg/commit/c4a2e720fd1a7ae5bfe5fedcb99276123b9cb277 "Add ability to hide completed dailies."
:(

When I remove that commit from my local install, challenges display tasks; when I put the commit back, the tasks disappear again.

@lefnire, can you please revert that commit on the live site?

We will work on making that commit not interfer with challenges since comments in the Tavern show that it was already a very popular feature.

**Comment by lemoness** [comment]
Oh no :( People have been loving that feature so far. Here's hoping it get
fixed soon.

**Comment by Alys** [comment]
@lefnire Do not revert that commit. I have a fix now and I'll PR it asap. Note that it might not be the best possible fix, but it will get everything working I think.

**Comment by Alys** [comment]
leaving open until lefnire pushes the fix so that others can find it easily (hopefully prevents duplicates)

**Comment by lefnire** [comment]
Pushing now

**Comment by chimeforest** [comment]
Looks like everything is working again with the challenges. Thank you =)
