### ISSUE TITLE
Setback on loading

### ISSUE THREAD

**Issue by chaosreigning** [HabitRPG/habitica#4156]
So, whenever I sign in on anything other than the computer I originally signed up on, I get an immediate message that my character has died. Not only that, but my character's displayed as being level 4 instead of the appropriate level, and all my tasks, to-dos, dallies, equipment, pets, money, and inventory are gone! This is true regardless of whether I'm on a different computer or on the app on my iPhone. How do I fix this? Am I doing something wrong?

**Comment by deilann** [comment]
Sounds like you have two accounts with the same credentials. If you look at
the UUIDs of the accounts they are most likely different. Luckily, it's an
easy fix. When you see the wrong account, delete it, then log back in. Your
problem should be fixed.

**Comment by chaosreigning** [comment]
I... Have no idea how I ended up with two accounts. But that worked, so thanks very much!

**Comment by deilann** [comment]
No problem!
