### ISSUE TITLE
september's daily check challenge doesn't go away

### ISSUE THREAD

**Issue by ImkeStevens** [HabitRPG/habitica#4158]
I joined the challenge that helps with checking your dailies for september, but after it still hasn't gone away. I removed the tag and clicked everything, but it is still there.

**Comment by Alys** [comment]
See the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges) page and follow  the advice in the "Leaving a Challenge" section (assuming the challenge still exists). If that doesn't help, follow the advice in "Deleting a Challenge Task".

Tell us if that fixes the problem. If it doesn't, please describe each step you took and what happened at each step (especially what went wrong).

**Comment by ImkeStevens** [comment]
I was able to delete the last task. Thanks!
