### ISSUE TITLE
Quests, Party Tab Weird This AM, and Now Non-Functional

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#4160]
Sequence of events:
1. Refresh my browser to trigger cron
2. Am notified I finished my current quest.
3. Buy the new quest, click on it to start it,
4. Slow blue bar across the top of the screen, but presume it took.
5. Cast some "burst of flames" intended to affect this quest. Believe I also marked at least one daily accomplished. 
6. Decide to look at the party screen to see how many HP the new target has. 
7. Party screen does not appear to be up to date. This is a common occurence, generally fixed by a combo of reloading the messages (clicking the refresh button by the party message area) and clicking reload in the browser.
8. The reload failed. I didn't capture the sequence of errors. At some point I get told I am not in a party (or that it's not loading; this is a standard message). 
9. I hit browser reload again, possibly more than once.
10. Here's the current state. I did not click or hover on anything to produce the various unwanted menus/tool tips. 
    ![screenshot from 2014-10-17 08 24 59](https://cloud.githubusercontent.com/assets/4530463/4681207/25c4ce0e-5611-11e4-90bc-3952dc282400.png)

Nothing was clickable in the above mess, but with some creativity involving the browser's address bar I was able to get back to the main page (where one records tasks etc.) and that looks fine. 

The Habit RPG Official User Data Display at https://oldgods.net/habitrpg/habitrpg_user_data_display.html appears to agree that I am not in a quest, or perhaps that I am not in a party. I get no estimate of damage to party from the dailies I haven't yet done, and the quest progress selector gives me a blank area with only a title.

**Comment by deilann** [comment]
That's a cache issue. Just need to clear your cache.

**Comment by Alys** [comment]
@ArlieS Tell us if this problem is still happening for you and we'll reopen the issue and help you further.
