### ISSUE TITLE
Tag auto selecting

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#4163]
Each time I open habitrpg on mobile chrome the first tag of mine is always selected now.
I've tried unselecting the tag and reloading 
I've also tried deleting the first tag and it just selected the one that moved forward

**Comment by Alys** [comment]
@Mihakuu I'm sorry we never got back to you about this. I'm guessing it would have been a local browser problem, with mobile chrome having something weird in its local storage or cache. I'm closing this on the assumption that it's fixed itself by now, but definitely tell us if it's still happening.
