### ISSUE TITLE
Background doesn't appear

### ISSUE THREAD

**Issue by yhimmel** [HabitRPG/habitica#4165]
Hi,
I'm new around. I purchased 20 diamonds and used 7 to purchase a background ("Forest"), now the diamonds dropped to 13 but there's no background in my character's image! Help!
User:
cf32be28-9e50-494e-8490-08124fbc042a

Using Google Chrome/Windows XP.

**Comment by deilann** [comment]
Have you tried clicking a second time to equip it?

**Comment by paglias** [comment]
If you go to the backgrounds page and try to select the background you just
purchased does it appears in your profile image or does it ask you to buy
it once again?
Il 18/ott/2014 20:27 "yhimmel" notifications@github.com ha scritto:

**Comment by yhimmel** [comment]
OK, the wierdest thing just happened: I tried to do that, and now ny diamonds are back to 20 AND i have my background! 
Sorry if I misundertood this: was I supposed to click two times? (one to purchase, and one after my diamonds are removed?) If so, I suggest to tweak the GUI on this, becuase it's really not intuitive to have to click twice (I thought that clicking twice would cost extra gems).
Thanks for your help peoople! It's nice to see such a supportive developers team!
