### ISSUE TITLE
Dailies View Reverts to "All" Every Visit

### ISSUE THREAD

**Issue by impr** [HabitRPG/habitica#4168]
I'm a little surprised no one has already raised this issue (or I couldn't find where they had) so I'm not sure if it is just a glitch of my account or the way habitRPG runs for everyone.

Every time I open habitRPG, the view for Dailies defaults to "All". I open and close habitRPG often because my computer is old and can't handle having it open all the time, and I have a lot of Dailies (including some that are really weeklies), so this means scrolling down to the very bottom of the page to change views (to "Due") on a very regular basis.

It would be great if habitRPG could either:
a) remember what view you were using last time from one visit to the next, or
b) have a settings option where you set your permanent view preference.

**Comment by Alys** [comment]
There's two changes in the works that will help with this problem:
- [Added setting for making the due tab default on dailies by crookedneighbor - Pull Request #4157](https://github.com/HabitRPG/habitrpg/pull/4157) (does what you request in your point "b")
- [put Daily and To-Do tabs at top and bottom - fixes https://github.com/HabitRPG/habitrpg/issues/3827 by Alys - Pull Request #4166](https://github.com/HabitRPG/habitrpg/pull/4166)
