### ISSUE TITLE
No points docked for incomplete dailies/reverted health loss

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#417]
I did not complete some dailies last Friday, and when I logged in on Sunday, it docked health at first - but after changing two other dailies (removing the markers for Sat and Sun) and reloading, I was back to full health again. Plus some of the technically inactive dailies were not grayed out.

**Comment by Pandoro** [comment]
Sounds buggy indeed. Although I wonder how this could have happened. I doubt the active/inactive settings should nor can affect already taken damage. 

Maybe you can post some more details about it while it is still fresh? System, browser? Do I get it right you logged out on Friday and logged back in on Sunday?

**Comment by wildcate** [comment]
System is Win7, Firefox 18.02.
I didn't log out on Friday, just put the computer on standby/sleep mode and turned it on again on Sun (sorry for the misleading wording). It docked 3.4 hp (I think) which came back after reloading.

**Comment by toebu** [comment]
It's possible that the damage was never fully synced to the server. After you reloaded the page, were your other changes intact (the removing of the Sat/Sun markers)?

**Comment by cleave29** [comment]
I had something similar happen in that health got undeservedly refreshed.  I took an undeserved reward, for which I took 9.9 dmg.  Then I clicked a Habit and it gave me 20 gold and most of that health loss back!!!

**Comment by wildcate** [comment]
It's possible that the other changes reverted as well, but I did not really memorise that (I was so perplexed by my sudden health).

**Comment by toebu** [comment]
@cleave29 did you also reload the page before you got back your healh, or did you get it right when you clicked on the habit?

**Comment by cleave29** [comment]
@toebu  I got my health and 20g right when I clicked on my Habit.

**Comment by toebu** [comment]
Yep, I can confirm this. I could reproduce it on my local server.

**Comment by lefnire** [comment]
i think it's related to #427, i'm going to work on that and follow up here when that's fixed

**Comment by lefnire** [comment]
yep, definitely #427. let's follow there
