### ISSUE TITLE
Challenges: probably wrong behavior of accordion

### ISSUE THREAD

**Issue by holyspecter** [HabitRPG/habitica#4170]
As a user I expect challenges' list will behave like standard accordion. But if I have opened block and click on another challenge it doesn't open, only first block closes instead, so I need to click on it again.
Expected behavior: first block will be closed and clicked block will be open.

UserId: 31c68fa6-0028-427e-bf7d-715be49f3e68
Browser: Google Chrome
OS: Ubuntu 14.04

**Comment by Alys** [comment]
Duplicate: https://github.com/HabitRPG/habitrpg/issues/1682

Please follow that issue for progress on this problem. There's a "notifications" section in the right-hand side of the page if you would like email notifications.
