### ISSUE TITLE
Problem setting up dev env

### ISSUE THREAD

**Issue by tx-tim** [HabitRPG/habitica#4171]
I am trying to set up a development environment on a Mac running Mavericks.  I installed mongo and and specified the default dbpath, giving it full r/w/x permissions.  I know that's set up correctly because I can run mongod from the terminal without issue.

When i use npm start I get an error: 

```
/node_modules/mongoose/lib/schema.js:362
    throw new TypeError('Undefined type at `' + path +
          ^
TypeError: Undefined type at `paths.model`
```

The offending block of code is here

```
  // ------------  MongoDB Configuration ------------
  mongoose = require('mongoose');
  var mongooseOptions = !isProd ? {} : {
    replset: { socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 } },
    server: { socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 } }
  };
  var db = mongoose.connect(nconf.get('NODE_DB_URI'), mongooseOptions, function(err) {
    if (err) throw err;
    logging.info('Connected with Mongoose');
  });
  autoinc.init(db);
```

The logs actually point to the call to 

```
autoinc.init(db);
```

I suspect either a) my 'NODE_DB_URI' is not configured properly.  That variable is specified in the config file:

```
 "NODE_DB_URI":"mongodb://localhost/habitrpg",
```

or b) there's something up with the mongoose autoinc plugin.  

I went through all the issues in the troubleshooting guide to make sure it wasn't one of those.  And the installation guide mentioned to empty the trash (!?) if seeing a dreaded new worker error so I did that too.  Any ideas what I might do to get up and running?

**Comment by crookedneighbor** [comment]
@tx-tim Maybe a silly question, but you're running this through the Vagrant box per [these instructions](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally), right?

**Comment by tx-tim** [comment]
@crookedneighbor I was under the impression that vagrant one way to set up a dev env, but not the only way.  I chose to use tools I am more familiar with (grunt, node, etc) and began at the Unix/MacOs section at the document you linked to.

**Comment by crookedneighbor** [comment]
@tx-tim Good point. 

I just set it up via the Mac instructions and it's running fine.

How did you install mongo? Run `mongod --version`, what version do you have installed?

**Comment by crookedneighbor** [comment]
One note, I had to `sudo mongod` to get the database running correctly.

**Comment by paglias** [comment]
Try wiping out the node_modules folder and reinstalling everything with npm
install, it worked for me
Il 20/ott/2014 05:20 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by tx-tim** [comment]
@paglias That worked - thanks!

**Comment by crookedneighbor** [comment]
@paglias Good call ++

**Comment by paglias** [comment]
Yeah it's not the first time it has happened to me, this or other problems with npm not updating correctly
