### ISSUE TITLE
Duplicated date on due

### ISSUE THREAD

**Issue by rafaelhdr** [HabitRPG/habitica#4175]
I have duplicated option for my due date on To Do

User ID: c5ef4ae4-5e69-4b79-a1f6-13923bf8d3b9

Print screen (repeated due date 18/10)
![bug-habitrpg](https://cloud.githubusercontent.com/assets/1108973/4721234/54005468-5937-11e4-8f06-fd7bbe9841d7.png)

Browser: Chrome Version 38.0.2125.104 (64-bit)
OS: Ubuntu 14.04
Javascript errors:
- "Uncaught TypeError: Cannot read property 'appendChild' of null" - graphics.js:17
- "O URL informado não é permitido pela configuração do aplicativo.: Uma ou mais das URLs fornecidas não são permitidas nas configurações do aplicativo. A URL deve corresponder à URL do site ou URL do Canvas, ou o domínio deve ser um subdomínio de um dos domínios do aplicativo." - VM31048 ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-st…:1

**Comment by paglias** [comment]
@rafaelhdr thanks for the report- Does it fix itself if you reload the page and it happens for every todo or only for this one?

**Comment by rafaelhdr** [comment]
@paglias thanks for checking
It does not fix itself on reload the page (i tried F5, ctrl + F5 and also ctrl + R)
It happens for every todo (all created and all i am creating now)
It only happens in October 2014. I checked all months from October 2014 to December 2015.

**Comment by paglias** [comment]
@rafaelhdr strange... I'm probably not going to have time to investigate. If it happens only with October it's probably not going to be ever fixed. if it happens again I'll give it a look

**Comment by rafaelhdr** [comment]
Ok. It is really not a big problem :)
I just wanted to warn.

(and sorry for late answer. I completely forgot to check my github)

**Comment by Alys** [comment]
Let us know if this happens again in October and we'll reopen this.
