### ISSUE TITLE
Vagrant Up Connection Timed Out...

### ISSUE THREAD

**Issue by taldin** [HabitRPG/habitica#4176]
Hello hello, and attention @thepeopleseason.  
I'm trying to use "vagrant up" to get to the "vagrant ssh" step in the Installing HabitRPG Locally instructions.  However, I'm stuck because I have repeating "default: Warning: Connection timeout.  Retrying..."  which eventually runs out and drops out with an error*"you may want to increase the timeout."  Which I don't know how to do.   On the VirtualBox screen is a tiny little menu that some google fu says is an Ubuntu console that I can't get to, and sending a return through VBoxManage doesn't do anything much.    

I have ssh installed in my path via Git.    I can get it up and running using Mongo+Github, so it's not my installation.

Running vagrant ssh after vagrant up times out gives the error: 'ssh_exchange_identification: read: connection reset by peer."

-Taldin

**Comment by thepeopleseason** [comment]
@taldin Can you post the output of vagrant up?

**Comment by taldin** [comment]
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
C:\habitrpg [develop +0 ~2 -0]>
------------------ This is on my laptop, a Toshiba Portege' running Windows 7.

**Comment by thepeopleseason** [comment]
Hmm... it looks like the vagrant box hasn't booted at all. Can you try 'vagrant destroy <enter>' confirming all questions, then 'vagrant up' again and send the full output?

**Comment by taldin** [comment]
## Well, it's a little different now...

C:\habitrpg [develop +0 ~2 -0]> vagrant destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'shell' provisioner...
C:\habitrpg [develop +0 ~2 -0]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'thepeopleseason/habitrpg'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'thepeopleseason/habitrpg' is up to date...
==> default: Setting the name of the VM: habitrpg_default_1414000421645_70511
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 => 3000 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...

**Comment by taldin** [comment]
Same error when it finishes, though, after a bunch more of those:
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by taldin** [comment]
Tried a different machine (a Dell Optiplex 9020) and got past that part, but 'vagrant up'  still fails with these errors instead:

==> default: bower github-buttons#\*                    ETXTBSY ETXTBSY, unlink '
/vagrant/.bower-tmp/github-buttons-17333-VgU1qs/archive.tar.gz'
==> default:
==> default: Stack trace:
==> default: Error: ETXTBSY, unlink '/vagrant/.bower-tmp/github-buttons-17333-Vg
U1qs/archive.tar.gz'
==> default:
==> default: Console trace:
==> default: Trace
==> default:     at StandardRenderer.error (/usr/lib/node_modules/bower/lib/rend
erers/StandardRenderer.js:82:17)
==> default:     at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:11
0:22)
==> default:     at Logger.emit (events.js:95:17)
==> default:     at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-
logger/lib/Logger.js:29:39)
==> default:     at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
==> default:     at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:7
97:24)
==> default:     at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
==> default:     at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.j
s:1035:31)
==> default:     at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower
/node_modules/q/q.js:741:41)
==> default:     at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44
==> default:
==> default: System info:
==> default: Bower version: 1.3.12
==> default: Node version: 0.10.32
==> default: OS: Linux 3.2.0-23-generic x64
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by thepeopleseason** [comment]
Try adding the following line to the Vagrantfile: 

  config.vm.communicator = "winrm" 

Make sure that the indentation matches the rest of the file where you see the rest of the config.vm\* lines.

**Comment by taldin** [comment]
## Think that made it worse... it went right to the error message.

C:\htest\habitrpg [develop]> vagrant destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'shell' provisioner...
C:\htest\habitrpg [develop +0 ~1 -0]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'thepeopleseason/habitrpg'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'thepeopleseason/habitrpg' is up to date...
==> default: Setting the name of the VM: habitrpg_default_1414003693052_61390
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 => 3000 (adapter 1)
    default: 5985 => 55985 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by thepeopleseason** [comment]
What version of vagrant are you using? If it's less than 1.6, please upgrade vagrant.

**Comment by taldin** [comment]
Tis the current version.  Downloaded this morning for the work machine (the above error) and yesterday (the timeout errors I originally posted).

**Comment by thepeopleseason** [comment]
Also can you confirm that you have ssh installed for your environment?

**Comment by taldin** [comment]
ssh works with a command prompt inside Powershell (from Github).   (typing ssh gives me back the 'usage' from ssh).

**Comment by taldin** [comment]
Specifically, I'm using 1.6.5 Windows.

**Comment by thepeopleseason** [comment]
I suspect there's some interaction issue with your ssh and the vagrant box itself. Do you know which version of ssh you've installed?

**Comment by taldin** [comment]
Hmm.  Not sure --there's no -version argument that will easily tell me that. - I have whatever comes with Github for Windows 12.0.2.

**Comment by thepeopleseason** [comment]
Unfortunately, we're entering a grey area where I have no experience with the ssh client from Github for Windows, and I've never run the vagrant box on Windows. One thing that I would try: after waiting a while, run the following: 

ssh -v vagrant@localhost:2222

then paste the results here.

**Comment by taldin** [comment]
Answer:  
OpenSSH_6.6.1, OpenSSL 1.0.1i 6 Aug 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 1: Applying options for *
ssh.exe": Could not resolve hostname localhost:2222: no address associated with
name
C:\htest\habitrpg [develop +0 ~1 -0]>

**Comment by thepeopleseason** [comment]
Ungh. Hurm. Replace localhost with 127.0.0.1

**Comment by taldin** [comment]
C:\htest\habitrpg [develop +0 ~1 -0]> ssh -v vagrant@127.0.0.1:2222
OpenSSH_6.6.1, OpenSSL 1.0.1i 6 Aug 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 1: Applying options for *
debug1: Connecting to 127.0.0.1:2222 [127.0.0.1] port 22.
debug1: connect to address 127.0.0.1 port 22: Connection refused
ssh: connect to host 127.0.0.1:2222 port 22: Bad file number
...are the results.

**Comment by taldin** [comment]
Okay, some progress:  I finally managed to get into the shell, but now when I type 'npm start' I get:
![image](https://cloud.githubusercontent.com/assets/9312226/4745644/5f4d1c28-5a3d-11e4-9096-d4004483d705.png)

**Comment by Alys** [comment]
Try `cd /vagrant` and then repeat the npm start command. If that doesn't work, do this and send us the output:
`ls -l /vagrant`

It's a bit worrying that you weren't automatically put into the /vagrant directory, and I'm concerned that your prompt says "vagrant@precise64" instead of "vagrant@habitrpg".

**Comment by taldin** [comment]
I'm in the vagrant directory, but 'tis empty (mostly):
![image](https://cloud.githubusercontent.com/assets/9312226/4745906/3c6a7cd8-5a41-11e4-8b5f-b6e470b7f10e.png)

**Comment by Alys** [comment]
Sorry Taldin but it's essential to do exactly this: `ls -l /vagrant`  The slash there is important.

I'll drop an explanation into our wiki discussion a bit later today.

**Comment by taldin** [comment]
No worries.  When I do ls -l /vagrant, it says "No such file or directory."

**Comment by Alys** [comment]
I thought it might. :) Quit the ssh session with `exit` which should put you back in the C:\htest\habitrpg directory. From there do a `dir` command (or whatever Windows is using these days to get a directory listing) and show us the results. I suspect that you don't have all the files required to set up the vagrant box correctly.

**Comment by taldin** [comment]
I'm going to start from scratch; maybe some of the destroy commands nuked something I shouldn't have.  Stay tuned.

**Comment by taldin** [comment]
Watching the initial vagrant up logs... it's installing mongodb... git... npm...  node.js... grunt/bower.... and now HabitRPG.    Most of the text is green.   Some red text, mostly warnings about expecting one version but getting a higher one...but then it ends with a bunch of warning text as above.    However, I now have a /vagrant directory.... and here's what I have in the c:\htest\habitrpg.

```
Directory: C:\htest\habitrpg
```

Mode                LastWriteTime     Length Name

---

d----        10/22/2014   5:39 PM            .bower-cache
d----        10/22/2014   5:39 PM            .bower-registry
d----        10/22/2014   5:39 PM            .bower-tmp
d----        10/22/2014   5:24 PM            .vagrant
d----        10/22/2014   5:20 PM            archive
d----        10/22/2014   5:20 PM            database_reports
d----        10/22/2014   5:20 PM            migrations
d----        10/22/2014   5:39 PM            node_modules
d----        10/22/2014   5:20 PM            public
d----        10/22/2014   5:20 PM            src
d----        10/22/2014   5:20 PM            test
d----        10/22/2014   5:20 PM            views
-a---        10/22/2014   5:20 PM        164 .bowerrc
-a---        10/22/2014   5:20 PM        284 .gitignore
-a---        10/22/2014   5:20 PM        135 .jshintrc
-a---        10/22/2014   5:20 PM        186 .nodemonignore
-a---        10/22/2014   5:20 PM        219 .travis.yml
-a---        10/22/2014   5:20 PM       1697 bower.json
-a---        10/22/2014   5:20 PM      16283 CHANGELOG.md
-a---        10/22/2014   5:22 PM       1082 config.json
-a---        10/22/2014   5:20 PM       1077 config.json.example
-a---        10/22/2014   5:20 PM        608 CONTRIBUTING.md
-a---        10/22/2014   5:20 PM        844 Dockerfile
-a---        10/22/2014   5:20 PM       3312 DOCS-README.md
-a---        10/22/2014   5:20 PM       4512 EXTENDEDCHANGELOG.md
-a---        10/22/2014   5:20 PM       4837 Gruntfile.js
-a---        10/22/2014   5:20 PM       2769 karma.conf.js
-a---        10/22/2014   5:20 PM        501 LICENSE
-a---        10/22/2014   5:20 PM        688 newrelic.js
-a---        10/22/2014   5:41 PM       1061 npm-debug.log
-a---        10/22/2014   5:20 PM       3105 package.json
-a---        10/22/2014   5:20 PM         76 Procfile
-a---        10/22/2014   5:20 PM        707 protractor.conf.js
-a---        10/22/2014   5:20 PM       1470 README.md
-a---        10/22/2014   5:20 PM        591 VAGRANT.md
-a---        10/22/2014   5:20 PM       2197 vagrant.sh
-a---        10/22/2014   5:20 PM        521 Vagrantfile
-a---        10/22/2014   5:20 PM       2851 validate-commit-msg.js
-a---        10/22/2014   5:20 PM       2679 validate-commit-msg.spec.js

**Comment by taldin** [comment]
New output for 'npm start' is:
![image](https://cloud.githubusercontent.com/assets/9312226/4746712/be33f62a-5a4d-11e4-8ba0-62560b7e801d.png)

**Comment by Alys** [comment]
It's possible that bower didn't install correctly (because the error involves bower_components/. Do you still have all the output from the initial vagrant up command?

You could try running `bower install -f`

**Comment by taldin** [comment]
Okay.  Tried it from inside the vagrant shell, it did a bunch of stuff, tried npm start again, same issue.  Outside of vagrant ssh, it throws an error 'not recognized as the name of a cmdlet, function, script, or program. '

Hmmmm.... it looked like vagrant installed bower (it was green) but maybe not?

**Comment by Alys** [comment]
Can you show me the output of this? `ls -l /vagrant/public/bower_components/`

**Comment by taldin** [comment]
The plot thickens...
![image](https://cloud.githubusercontent.com/assets/9312226/4747274/b188d7ea-5a59-11e4-9ecd-0e0b67bdb62d.png)

**Comment by Alys** [comment]
Something has definitely gone wrong with the install process. My advice is below but it might seem horrific, and so you might wish to wait for thepeopleseason. He could well have much better advice, possibly including, "omg, no, ignore Alys, she's an idiot". :)

We could try to work out what went wrong, and fix it, but there might be more than one thing broken, and the fixes might put your system into a slightly (or greatly) non-standard state. If I was doing this, I would start again COMPLETELY from scratch. `exit` to leave the vagrant ssh session, then `vagrant destroy`, then open up the virtual machine manager to make sure there are NO virtual machines left (delete them all if there are), then completely delete C:\htest\habitrpg including all of the files you obtained from github (or, perhaps more sanely, rename the directory just in case you need it later, but be very careful to not use it by accident!). Then start again with the **_"Follow steps 1-3 in Fork & Clone HabitRPG (fork & clone, setup upstream branch, and rebase branch)"**_ instructions. But stop at the end of that step (i.e., do not do **_"Create a config file from the example one"**_). Before you go further, we'll check that some things did get cloned properly -- I'll think up a list of things I'd want to check soon, if you want to go down this path. :)

**Comment by taldin** [comment]
<grins>  Not at all horrifying.  Wouldn't do to put in bad instructions in the rewrite, and this is the kind of stuff I do for my day job.     I have a working copy on my laptop via the Git+Node+Mongo route, and the stuff I've been doing with Vagrant has been on my work machine since that got past the timeout problem.

**Comment by taldin** [comment]
Okay!  Set.

**Comment by Alys** [comment]
Right, so you've forked and cloned and setup upstream and rebased? (Not that the rebasing is actually necessary at that point.) Please show me a directory listing of your habitrpg directory (the one that contains vagrant.sh), and show me the contents of vagrant.sh and of config.json.

Also the content of the file called Vagrantfile

**Comment by taldin** [comment]
Directory:
...........................
    Directory: C:\htest\habitrpg

Mode                LastWriteTime     Length Name

---

d----        10/22/2014   9:14 PM            archive
d----        10/22/2014   9:14 PM            database_reports
d----        10/22/2014   9:14 PM            migrations
d----        10/22/2014   9:14 PM            public
d----        10/22/2014   9:14 PM            src
d----        10/22/2014   9:14 PM            test
d----        10/22/2014   9:14 PM            views
-a---        10/22/2014   9:14 PM        164 .bowerrc
-a---        10/22/2014   9:14 PM        284 .gitignore
-a---        10/22/2014   9:14 PM        135 .jshintrc
-a---        10/22/2014   9:14 PM        186 .nodemonignore
-a---        10/22/2014   9:14 PM        219 .travis.yml
-a---        10/22/2014   9:14 PM       1697 bower.json
-a---        10/22/2014   9:14 PM      16283 CHANGELOG.md
-a---        10/22/2014   9:14 PM       1077 config.json.example
-a---        10/22/2014   9:14 PM        608 CONTRIBUTING.md
-a---        10/22/2014   9:14 PM        844 Dockerfile
-a---        10/22/2014   9:14 PM       3312 DOCS-README.md
-a---        10/22/2014   9:14 PM       4512 EXTENDEDCHANGELOG.md
-a---        10/22/2014   9:14 PM       4837 Gruntfile.js
-a---        10/22/2014   9:14 PM       2769 karma.conf.js
-a---        10/22/2014   9:14 PM        501 LICENSE
-a---        10/22/2014   9:14 PM        688 newrelic.js
-a---        10/22/2014   9:14 PM       3105 package.json
-a---        10/22/2014   9:14 PM         76 Procfile
-a---        10/22/2014   9:14 PM        707 protractor.conf.js
-a---        10/22/2014   9:14 PM       1470 README.md
-a---        10/22/2014   9:14 PM        591 VAGRANT.md
-a---        10/22/2014   9:14 PM       2197 vagrant.sh
-a---        10/22/2014   9:14 PM        521 Vagrantfile
-a---        10/22/2014   9:14 PM       2851 validate-commit-msg.js
-a---        10/22/2014   9:14 PM       2679 validate-commit-msg.spec.js
............................................
vagrant.sh
#!/usr/bin/env bash
#
# HabitRPG provisioning script

# function for autostart
function autostart_habitrpg {
    update_config=$'Please update config.json with your values\nfor ADMIN_EMAIL, SMTP_USER, SMTP_PASS and SMTP_SERVICE,\nthen run "vagrant reload --provision"'

```
# check if config.json exists, then check if the defaults are still in place
if [ -e config.json ];
then
    if grep -Fq 'ADMIN_EMAIL": "you@yours.com' config.json;
    then
        echo "$update_config";
        exit;
    else
        npm start
    fi
else
    cp config.json.example config.json;
    echo "$update_config";
    exit;
fi
```

}

# Main provisioning
echo Setting up HabitRPG...
echo cd /vagrant >> /home/vagrant/.bashrc

# Prevent warnings: "dpkg-preconfigure: unable to re-open stdin ..."
export DEBIAN_FRONTEND=noninteractive

echo Updating repositories...
apt-get update -qq

echo Installing Unix build tools - needed for node-gyp to use make...
apt-get install -qq build-essential

echo Installing GraphicsMagick - provides gm and convert...
apt-get install -qq graphicsmagick

echo Installing phantomjs and dependency...
apt-get install -qq phantomjs libicu48

echo Installing requirements for grunt-spritesmith...
apt-get install -qq pkg-config libcairo2-dev libjpeg-dev

echo Installing Mongodb...
apt-get install -qq mongodb

echo Installing Git...
apt-get install -qq git

echo Installing npm...
apt-get install -qq python-software-properties
echo Adding repository node.js...
apt-add-repository -y ppa:chris-lea/node.js
echo Updating repositories...
apt-get update -qq
echo Installing node.js
apt-get install -qq nodejs

cd /vagrant

echo Installing grunt/bower...
npm install -g grunt-cli bower

echo Installing HabitRPG
npm install

echo Installing Bower packages
sudo -H -u vagrant bower --config.interactive=false install -f

## # echo Seeding Mongodb...
## node ./src/seed.js
## no longer required - see comments in src/seed.js

# Uncomment both lines to autostart the habitrpg server when provisioning
# echo Starting HabitRPG server...
# autostart_habitrpg

...........
config.json.example (since I haven't copied it to config.example yet)
{
    "PORT":3000,
    "IP":"0.0.0.0",
    "BASE_URL":"http://localhost",
    "FACEBOOK_KEY":"123456789012345",
    "FACEBOOK_SECRET":"aaaabbbbccccddddeeeeffff00001111",
    "NODE_DB_URI":"mongodb://localhost/habitrpg",
    "NODE_ENV":"development",
    "SESSION_SECRET":"YOUR SECRET HERE",
    "ADMIN_EMAIL": "you@yours.com",
    "SMTP_USER":"user@domain.com",
    "SMTP_PASS":"password",
    "SMTP_SERVICE":"Gmail",
    "SMTP_HOST":"smtp.gmail.com",
    "SMTP_PORT": 587,
    "SMTP_TLS": true,
    "STRIPE_API_KEY":"aaaabbbbccccddddeeeeffff00001111",
    "STRIPE_PUB_KEY":"22223333444455556666777788889999",
    "NEW_RELIC_LICENSE_KEY":"NEW_RELIC_LICENSE_KEY",
    "NEW_RELIC_APPLICATION_ID":"NEW_RELIC_APPLICATION_ID",
    "NEW_RELIC_API_KEY":"NEW_RELIC_API_KEY",
    "GA_ID": "GA_ID",
    "PAYPAL_USERNAME": "PAYPAL_USERNAME",
    "PAYPAL_PASSWORD": "PAYPAL_PASSWORD",
    "PAYPAL_SIGNATURE": "PAYPAL_SIGNATURE",
    "EMAIL_SERVER_URL": "http://example.com",
    "EMAIL_SERVER_AUTH_USER": "user",
    "EMAIL_SERVER_AUTH_PASSWORD": "password"
}
..........................
Vagrantfile
.......................
# -_\- mode: ruby -_-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "thepeopleseason/habitrpg"
  config.ssh.forward_agent = true

  config.vm.hostname = "habitrpg"
  config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
  config.vm.usable_port_range = (3000..3050)
  config.vm.provision :shell, :path => "vagrant.sh"
end

**Comment by Alys** [comment]
That all looks good! Copy the config.json example file, but don't bother editing any of it. The default settings should be fine for now.

Run `vagrant up` and if possible, capture the entire output to the clipboard or as screenshots. I don't know if Windows will let you scroll back far enough when it's all over, so you might want to take screenshots as it goes. Whatever you can manage. Being able to see the entire output could be very useful for troubleshooting later. However even seeing part of the output might help if you can't get it all.

If you end up with a huge number of screenshots, you can zip them up and email them to me, and then I can dump them on my website for others to view if needed.

Stop after `vagrant up` has finished.

**Comment by taldin** [comment]
All righty.  I'll get this done tomorrow morning - tis almost 1am here. :)

**Comment by taldin** [comment]
Sent to both you and thepeopleseason.

**Comment by thepeopleseason** [comment]
@taldin: When you say you sent to both Alys and me, I'm not seeing anything.

**Comment by taldin** [comment]
Sent it to the e-mail for your Github.  Should be from a 'mistwalker' address.

**Comment by Alys** [comment]
@thepeopleseason: For me, gmail threaded Taldin's direct email to us into
the emails I received from github, so you might find it in your trash with
the github emails.

**Comment by Alys** [comment]
@taldin I'm closing this since it's old, but I'm happy to reopen it if desired.
