### ISSUE TITLE
meteor rewrite?

### ISSUE THREAD

**Issue by dcsan** [HabitRPG/habitica#4184]
the setup around Derby is a bit of overhead, I wonder if the core team would consider a rewrite in meteor? then the setup and onboarding process for new devs would be a lot clearer.

I'm planning to create a simple gamification package for meteor which is purely API based, for other apps to use. probably not a Habit core team thing but in case other people are interested in the topic let me know.

**Comment by paglias** [comment]
Hi @dcsan!

The site has been rewrite from Derby more than a year ago. Now it's an Express app on the back end that exposes a REST API to a front end written in AngularJs

**Comment by dcsan** [comment]
ah, thanks for the info! i was reading some dev docs somewhere maybe on the wiki. Derby had a lot of promise as a next-gen reactive isomorphic framework, so very cool you guys were using it then, but meteor has really grown hugely since then with their big cash infusion... i far prefer that to the mess of callbacks with node/express and all of angular's boilerplate... but just personal opinion i guess.

**Comment by lefnire** [comment]
Meteor has a great future. I'm personally banking on firebase + angular.
Derby is. _cough_.. Ahem.. Anyway, we went express + angular to ensure a
solid API, since 3rd party is vital to our app.
