### ISSUE TITLE
User display showing previously selected user's equipment

### ISSUE THREAD

**Issue by emihalac** [HabitRPG/habitica#4187]
Hi,

This is happening to me in the Tavern chat:
1. Click on a username (to see that user's profile) of a user (let's call him/her 'user A')
2. Dismiss the 'user profile' window by clicking outside it
3. Click on another username to open up a different user profile (let's call him/her 'user B')

Expected result: user B profile window shows user B's profile, including their items
Actual result: user B profile window shows user B's profile, but making it look like they have the same equipment as user A.

Closing and re-opening user B's profile fixes this.

Additional info:
Personal User ID: 3a88151a-9681-40fe-89be-7b99628be7c0
OS: Ubuntu 14.04.1 LTS
Chrome version: 37.0.2062.120

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2010

You can follow that issue for updates about it (there's a "Notifications" section in the right-hand column if you'd like email notifications).
