### ISSUE TITLE
Can't Re-Order anything

### ISSUE THREAD

**Issue by MiriamELewis** [HabitRPG/habitica#419]
I can't seem to re-order the habits, dailies, ToDo's or rewards. Its been a bit buggy before but refreshing the page used to fix this. Every time I try it tries to highlight the text instead (Chrome) or just shows the hand symbol and jumps and stalls(Opera). Firefox seems to work fine.

Mac OS 10.6.8
Chrome 24.0
Opera 12.14

**Comment by wc8** [comment]
See #324
