### ISSUE TITLE
Accidentally Deleted Account/Lost Pets

### ISSUE THREAD

**Issue by freeman26** [HabitRPG/habitica#4193]
I got a message saying that my account had been deleted (while I was logged in), even though I hadn't clicked "Delete." I was able to make a new account, and used "Fix character values" to fix most of it, when it didn't fix, but I lost at least 33 pets, and I don't know how to get them back. Is it possible for me to Restore this, or for you to give me 33 eggs and 33 hatching potions in Drops, or something, so I can have my pets back?
Thanks!

7ffb2a83-1ff5-4884-bf26-c2d185e3009d
Firefox
Windows 8

**Comment by freeman26** [comment]
Oh, and this was probably a week ago.
Thanks! :smiley:

**Comment by lemoness** [comment]
How strange! Do you have the UUID and/or username of your old account?

**Comment by freeman26** [comment]
I am not sure what a UUID is, so I probably wouldn't have that. I used the same username for my new account as my old one, though.

Sorry, that probably doesn't really help. :/
If it would help, I can change my username to something else, and give you my original username. Let me know!
Thanks!

**Comment by lemoness** [comment]
Oh, sorry - a UUID is a user ID - the string of numbers and letters that
you can find under Settings > API.

@lefnire - Any way to find a delete account's information, or is it just
gone? Any idea why their account would have been deleted in the first place?

**Comment by paglias** [comment]
Could you providd the email you used in your prevuous account? Also how did
you notice your account was deleted? Did it told you that your email wasn't
registered?
Oh, sorry - a UUID is a user ID - the string of numbers and letters that
you can find under Settings > API.

@lefnire - Any way to find a delete account's information, or is it just
gone? Any idea why their account would have been deleted in the first
place?

**Comment by freeman26** [comment]
I used the same email address for my new account. Do you still need it, or is it no longer helpful?
A popup came (just like the ones that say to refresh the page, because the habitRPG site ran into an error, or whatever) that said something like "this account doesn't exist" or "no longer exists." This happened while I was logged into the account, and I really don't think I clicked the "Delete Account" button. 
I don't have the UUID- I never Exported any of that stuff.
To respond to @lefnire's comment, I used the same username and email address, but, again, I didn't Export anything. I did go on to the User stuff, earlier that day, and looked at the "Danger" or "Caution" section, but I never clicked, and I went back to my Tasks. I might have even marked a few, before I got the popup.

Thanks!

**Comment by Alys** [comment]
The confirmation process for deleting your account is complex enough that
you would have noticed and remembered it.

My guess for what went wrong is that someone else discovered your password,
logged in as you, and deleted your account. If you're still using the same
password on this account, change it just in case! Make sure it's a
sufficiently complex password that it can't be easily guessed or discovered
by brute-forcing in a short time, and not a password that you have used on
any other site.

**Comment by freeman26** [comment]
Good to know. I'll do that. Is there a way for you to give me the 33 eggs and 33 potions that I lost, in drops, or something? And, if not can I have a quest or two given (preferably one of the ones that give you Quest Pets)?

Thanks!

**Comment by lefnire** [comment]
@freeman26 when did you register and when did this happen? (or how long roughly had you been playing before this happened?) I'll look in the backups for, say the day before this happened, to see what I can find.

I've granted you some gems to buy back any missing bits in the meantime

**Comment by freeman26** [comment]
I registered around November 14-15. My username is/was francom. This happened nine days ago.
You don't need to worry about it. I can close this Issue, and just go with the Gems! Thank you all SO MUCH! You're all SO helpful. You're the BEST!
-freeman26

PS If I use the Gems once I already have them, will I get charged, even though I was given, not payed for them?
Thanks!
