### ISSUE TITLE
Incorrect label for Tier 8 (Mods)

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#4194]
I've noticed this was recently updated to a dark blue for the mods, but I've now acquired the label of "Heroic" when it should be "Guardian". I assume there was a mix-up with the coding or that it just hasn't rolled over properly yet, but I decided to make a ticket as it might cause some confusion later on. :)

**Comment by Alys** [comment]
It's been fixed already. Reload and it will be right.

**Comment by breadstrings** [comment]
Thanks Alys. :)
