### ISSUE TITLE
Error processing string

### ISSUE THREAD

**Issue by alowaniak** [HabitRPG/habitica#4196]
I'm getting "Error processing string." on the pop-up text for an item in the shop.
![image](https://cloud.githubusercontent.com/assets/2017509/4818471/edecfd9e-5ef3-11e4-8f99-da2e26e61c21.png)

Using Chrome Version 39.0.2171.36 beta-m, no javascript errors afaict.
But I'm kinda guessing the processing error is server-side.

**Comment by crookedneighbor** [comment]
This is a translation mistake in [Transifex](https://www.transifex.com/projects/p/habitrpg/).

The string for `locales/nl/gear.json` in [habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared) is:

```
Transplanteer deze helm op je hoofd! Hij is slechts in LICHT gebruikte staat. Voegt <% = str %> punten toe aan Kracht. Beperkte oplage herfs    tuitrusting 2014.
```

Notice the space after % and before = in `<% = str %>`. Should be `<%= str %>`.

**Comment by crookedneighbor** [comment]
@paglias This should be an easy fix in the Dutch section of the Transifex project. Here's the [link to view the string in question](https://www.transifex.com/projects/p/habitrpg/viewstrings/#nl/gearjson/31498531).

**Comment by paglias** [comment]
@crookedneighbor thanks, fixed and left a comment about that. Until a few weeks ago errors like this would have thrown an error killing the whole page, I changed it to showing an error string which is better because it means we don't have to check it's working every time but also made it difficult to find out.

Will go online with the next lang updates

**Comment by crookedneighbor** [comment]
Nice.

I just did a quick grep in habitrpg-shared and found the same problem in the gear.json for Spanish. [Here's the offending translation](https://www.transifex.com/projects/p/habitrpg/viewstrings/#es/gearjson/22835784?qt=%22%3C%25%20%3D%22).

**Comment by paglias** [comment]
@crookedneighbor corrected, thanks

**Comment by habitrpguser** [comment]
I just got the same "Error processing string, please report to" message while clicking a daily. (It was a grayed-out daily if that helps.)
