### ISSUE TITLE
Error drag and drop habits

### ISSUE THREAD

**Issue by chiarafes** [HabitRPG/habitica#4197]
Hi,
first of all ... thank you! HabitPRG is a very useful resource for my daily work. After that, I'm trying to organize my habits list, but boxes don't move properly and messed with each other.

It's just me? :)

Have a nice day!

**Comment by paglias** [comment]
@chiarafes thanks for the report? Could you provide a screenshot?

**Comment by chiarafes** [comment]
@paglias I shoud load a .mov, so you can see that the drag and drop is not working... and there is also an "intruder" task that I can not delete.
Where can I save you the files? Here I can upload just PNG GIF or JPG

**Comment by Carvagio** [comment]
I'm not sure if this is the same issue I've been having, but for the longest time I've found it impossible to re order my to-dos. I will drag and drop one somewhere, and the next time I load the page or even the next time the page updates (the blue bar travelling across the screen) the to-do will go back to where it had been. In addition, sometimes they will push themselves to the bottom as well.

**Comment by chiarafes** [comment]
YES! That's it! It happens to me too! :(

**Comment by lemoness** [comment]
@Carvagio - That's a slightly different thing, actually - have you tried
clearing your Completed To-Dos recently? That usually helps :)

**Comment by Carvagio** [comment]
@lemoness, That worked perfectly! I don't ever check my completed To-Dos, so I forgot I even could clear them. Thank you so much!

**Comment by chiarafes** [comment]
@lemoness I've cleared my To-Dos and now the drag-and-drop tool works! :)
But the intruder is stille there...
![intruder](https://cloud.githubusercontent.com/assets/6582625/4915052/1b9a1df8-64cb-11e4-82cd-d8d9f258fbd3.jpg)

**Comment by lemoness** [comment]
@Chiara Bosio - Is it still there after you've refreshed and cleared your
cache? Try that and let us know.

**Comment by chiarafes** [comment]
Mh mh... :(
Cache cleared, cmd+R. I also Logout but... nothing.

![schermata 2014-11-06 alle 12 07 27](https://cloud.githubusercontent.com/assets/6582625/4934775/22ce5f46-65a5-11e4-92e6-30bba65a8821.png)

**Comment by Alys** [comment]
@chiarafes What is your "User ID"? You can find it at [Settings -> API](https://habitrpg.com/#/options/settings/api)

**Comment by chiarafes** [comment]
Hi @Alys !
Here it is: fa7753ce-1c76-4e58-a471-6d51158a75e0

Thanks and have a nice day

**Comment by Alys** [comment]
@lefnire : Another account with a Reward appearing in the Habits column. The User ID is fa7753ce-1c76-4e58-a471-6d51158a75e0 and the Reward is called "anicure" (see screenshot three comments above this one).

ref: https://github.com/HabitRPG/habitrpg/issues/2334

@chiarafes : The Reward can be deleted only by our database admins who tend to be very busy. It might be several days before they're able to remove it. It will be gone eventually though!

**Comment by Alys** [comment]
@chiarafes I'm a database admin now so I've deleted the Reward that appeared in your Habits column. I'm sorry about the delay! Let us know if you have any other tasks that are causing problems.
