### ISSUE TITLE
Third party added a habit without my knowledge and consent.

### ISSUE THREAD

**Issue by LSaite** [HabitRPG/habitica#4198]
Seems to be connected with my account experiencing two "end of the day" health taking events. May have something to do with current quest. However the novel habits are recent compared to the other possibly related issue. Habit name is " 96f5ea41-190c-4f20-bd87-c3db7953e59a" and the comment attached is "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task." Is this a virus?

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/1402

It's known that HabitRPG itself creates these habits, not a third-party service, but I believe we're not completely sure why. The habit is harmless and no damage has been done to your account. You can delete it.

You can follow that issue for progress reports on the fix, if you wish (there's a Notifications section in the right-hand column).
