### ISSUE TITLE
Dailies won't reset

### ISSUE THREAD

**Issue by eteran23** [HabitRPG/habitica#42]
Today my dailies do not reset and I haven't lost any health for dailies I didn't do yesterday.

**Comment by eteran23** [comment]
The next day the system worked again as expected. So somehow it "forgot" to run the progress once.

**Comment by lefnire** [comment]
@eteran23 it worked ok today? it might have been fixed with a recent commit to derby. reopen if it happens again. I've seen it happen once before myself, so I'm going to keep an eye on it and try to write some test-coverage.
