### ISSUE TITLE
Retroactively Applying Stats

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#420]
I was super excited to see the class system stretch goal, and then I was thinking...

While it's easy to start adding the system on for the future, you don't want it to start all of the preexisting players off at zero.  Nor does it seem like everyone should have the same set numbers.

What if, when the class system is implemented, users get to choose "their play style" thus far, and then it divides up their preexisting experience and/or points based on that?

Example:

I do a lot of intelligence-type work, so I might choose Int- 50%, Dex - 35%% , Str - 15%. My friend is much more physically active, so she would choose Dex - 40%, Str - 40%, Int - 20%.

This would be a one-time thing, to help make the transition easier. 

No idea how hard it would be to implement, so feel free to use a completely different method! But something will have to be done to account for the difference.

**Comment by lefnire** [comment]
Good thinking, I'll look into your comment once we get classes underway.
We'll definitely not want to start everyone at 0

**Comment by Pandoro** [comment]
I added both a later and an important Label to this post. Important just so that we will not forget about it. If that messes with your Zen thing though, feel free to change it @lefnire ;) 

And yes, a very valid point. I think it makes sense as well, although it also really depends on how the class system will be implemented. If it is level based, then I really think this makes sense, if it is kind of not tied to the level, then everyone can just start at the same time without big trouble?

**Comment by lemoness** [comment]
Congrats on getting the stretch goal!!

I see in the link that it looks like you're adding 1 point per level... in that case, maybe a system where people can choose which skill they should have gotten for all their past levels? Like a basic grid? That seems much easier than percentages, especially since most people probably aren't TOO far up on the level charts :)

Also, since we're only giving people a bit at a time, maybe the default starting stat should be a higher number, like 10. (Nobody wants to be told that they have a zero intelligence.) Functionally it's exactly the same, but in practice it makes you feel a little cooler.

I am so excited for classes!

**Comment by wc8** [comment]
Added to checklist for [Stats](https://trello.com/c/L1H6LiZ3).

**Comment by lefnire** [comment]
closing, this will be implemented with classes
