### ISSUE TITLE
Decapitated mounts!

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#4209]
![screen shot 2014-11-01 at 4 31 42 pm](https://cloud.githubusercontent.com/assets/6208739/4873223/73fdcc46-6206-11e4-95a5-9181387a6f18.png)

I sure hope this isn't a feature.

**Comment by Alys** [comment]
<strike>It's a temporary display glitch in your browser. Whenever you see anything a bit odd in HabitRPG (or any website really), reload the page using your browser's refresh button. That will cause your browser to display the images correctly. For more information see https://github.com/HabitRPG/habitrpg/issues/3830</strike>

**Comment by casicastiel** [comment]
I did, though - it's showing up on both mobile and desktop Chrome, refreshing and all.

Sent from Yahoo Mail on Android

**Comment by Alys** [comment]
<strike>Clear your browser's cache and refresh again, or do a hard refresh (probably hold down shift while clicking refresh, although it might vary with different browsers).</strike>

**Comment by casicastiel** [comment]
Did both and restarted browser for good measure - still there. :/

Sent from Yahoo Mail on Android

**Comment by Alys** [comment]
Okay, reopening. @lefnire @paglias Is there a server-side cause for the display glitch this time? It's much more persistent than usual and seems to be specifically about mount head positions. Another user in the Tavern has reported it, with refresh also not working there, and I'm seeing it now too.

**Comment by breadstrings** [comment]
Also happened to me as well, after a hard refresh. I thought it was a new feature initially because the dragon mounts don't look too bad with the heads like that...and you can see your avatar too. :P

**Comment by averixus** [comment]
This is happening to me, too.
