### ISSUE TITLE
Feature Request: Rush / Tower mode

### ISSUE THREAD

**Issue by Risuji** [HabitRPG/habitica#421]
Basically an optional tower defence style mode.

1-6 random tasks are taken from your to-do list on random days. Each task is given a monster sprite, a speed based on their priority and power based on how old they are.  They charge your player (taking between 1-7 days) until either you've completed their task or they reach the top and start attacking your life points
They take knock-back for user completing dailies or good habits, and take buffs for bad habits.

**Comment by Pandoro** [comment]
Honestly I am a bit against it. As this would be a major change, it would again be an opt in feature. I think many people will not opt in for this, considering how many people use their todos also for things they need to do on the long run. For the select group of user that do use this though, there would probably be no real extra reward, considering that would be annoying for people who do not want to use it. So this would mean it is a pure motivational thing for a subset of the users. 

Right now I think this will be too much time for an implementation and the effort should be put into more general features that motivate all the user to get more stuff done. Let's keep this open to see what others think. You might however also be interested in #204.

**Comment by Risuji** [comment]
#204 does seem to me to be less work to the developers and to the same end of motivating the user to do a random task.
I'd enjoy the extra motivation and experience of a rush mode, but #204's disease tasks works equally as well in terms of raw purpose.

**Comment by Pandoro** [comment]
Hmmm what you say is true :p I must admit I never was a real big fan of that idea either ;) But of course the main user group should decide on what is going to be in the game. What makes that idea easier to implement is that we do not need to worry about monster sprites, and the overall system is somewhat simpler. You get a disease, or you don't, if you do, you get hp subtractions until you manage to cure yourself at some point. The system you describe is also based on speed, buffs and debuffs etc. And I think that people can relate a bit better to a disease than to a tower defence kind of scenario. But you are right deep down the ideas are very similar.

**Comment by Risuji** [comment]
Yeah, it was based more on the idea of "encroaching deadlines" - seeing your tasks crawling towards being overdue.
I would like to see some motivation towards doing a random task, but I think the quests system is also aimed at that kind of function.

**Comment by wc8** [comment]
@Risuji Since you brought up encroaching deadlines, have you seen this suggestion: [Scheduled Task Attack](https://trello.com/c/vPuLG1G0)?

**Comment by wc8** [comment]
Another idea possibly of interest: [Random Challenge](https://trello.com/c/EPxvwrrh), I've mentioned this idea there.
