### ISSUE TITLE
Unable to buy Fall Festival items on the last night.

### ISSUE THREAD

**Issue by crystalphoenix** [HabitRPG/habitica#4210]
I had changed class to Healer last night to get the last set of Fall Festival items I needed. But for some reason, the items didn't stick. I would buy them, and then suddenly be refunded the gold. I had tried hard refreshing the page, and even tried buying them through the Android app. Screenshot below shows what happened. 

Since Habit is the last thing I check into before sleep, I was too tired to come submit a bug report to figure it out... The time in the screenshot is in EST.

User ID: 52dc70a2-896e-4537-b306-4b449ba196e5
OS: Windows 7
Browser: Firefox 32.0.3

![screenshot 2014-10-31 23 40 25 blur](https://cloud.githubusercontent.com/assets/5247782/4873508/9afb9282-6216-11e4-9ed5-3c2c37dd9236.png)

**Comment by Alys** [comment]
I've given you the items. Reload your equipment page and let us know if they aren't there.

ref: https://github.com/HabitRPG/habitrpg-shared/issues/349
