### ISSUE TITLE
Change to standard time treated like a full day causing damage

### ISSUE THREAD

**Issue by coldwarjunkie** [HabitRPG/habitica#4211]
The moment my time zone switched from DST to ST, all my dailies refreshed as if a new day had begun. As I'd only clicked off two of them after midnight, I lost most of my streaks and sustained damage to my health. A quick glance at the tavern confirms many are having the same experience as well.

**Comment by immaculateconnection** [comment]
That just happened to me, too.  Ouch.  I was switching from Eastern (where it was 8pm) to Central (where it was 7pm).

**Comment by Alys** [comment]
We're tracking this issue in https://github.com/HabitRPG/habitrpg/issues/3806 so I'm closing this one.

We're also planning changes to cron that will make it possible to avoid damage from unexpected crons.
