### ISSUE TITLE
Avatar Mount Image Messed Up

### ISSUE THREAD

**Issue by mclarke12** [HabitRPG/habitica#4213]
![image](https://cloud.githubusercontent.com/assets/9513399/4875425/4e55c706-6296-11e4-945e-7beb31e1a36c.png)

Hi, Just a small thing, but as you can see in the above image, my avatar's mount has suddenly grown an extended neck. This is on Chrome desktop using a Windows 8 PC, and is not resolved by refreshing the page, or by de-equipping and re-equipping the mount. My user ID is 6f1b8618-90d0-42b4-a8b3-ac4f03271066

Many thanks
Michael

**Comment by negue** [comment]
Was Fixed 5 hours ago with #4212 :)
