### ISSUE TITLE
Mounts' Heads Misaligned (Production Only)

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4214]
On habitrpg.com:
![screen shot 2014-11-02 at 9 32 44 am](https://cloud.githubusercontent.com/assets/2916945/4875736/b2f1df74-62a5-11e4-85b8-b785566970bf.png)

I loaded up the develop branch and it looks fine:
![screen shot 2014-11-02 at 9 30 28 am](https://cloud.githubusercontent.com/assets/2916945/4875737/be7c5bc6-62a5-11e4-8dfd-45b3b379a4a0.png)

Digging into the inspector, it looks like someone gave the `.current-mount` and `.current-pet` class these attributes: `left:0; bottom:0`. If the attributes are removed from `.current-mount`, it looks fine.

**Comment by negue** [comment]
Yep :), already fixed with #4212

**Comment by crookedneighbor** [comment]
Awesome. Should have checked the closed PRs before posting.
