### ISSUE TITLE
Off site links - new tabs

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#4215]
Links that people post to pages outside of Habit are no longer being opened in a new tab, but rather in the same tab.
##

**Comment by lemoness** [comment]
Is this happening in the website, or the mobile app? If website, which
browser are you using?

**Comment by k8sullyvan** [comment]
It's on the website, when using chrome

**Comment by lemoness** [comment]
Hm, just tested on Safari - it still opens in a separate tab. Does Chrome
have any kind of setting determining whether or not its opened in the same
window?

**Comment by paglias** [comment]
Cannot replicate in the tavern with chrome
