### ISSUE TITLE
cron ran twice in 13 hours

### ISSUE THREAD

**Issue by magickmoons** [HabitRPG/habitica#4216]
This also affects my party members I assume. I logged in about 13 hours ago (just after midnight my time -- I use the default day start) and my cron tallied and dealt damage to our monster and the party. I just logged in again (with supposedly 12 hours left on my day) and hadn't checked anything off my lists. I clicked to join a new challenge, and suddenly lost 40+ hp, and dealt 21 damage to my party members!

**Comment by MelissaSmith12** [comment]
Roughly the same experience here. Last night I logged in at 11 PM local time, and cron had already run (I also use the default day start). Then this morning when I logged on at work, cron had run again (resetting day and dealing damage to monster and party) and ignored the Stealth I'd cast yesterday at about 9 PM local time, and killed me. 

_ded of extra cron_

user: 50b60b29-d15c-4724-a47e-613c897d72cb

**Comment by Enatee** [comment]
Same here. For some reason cron suddenly ran in 15.15 (+3 GMT). All my dailies have reset, I lost my Perfect Day buff and boss has attacked my party members. And this was very strange 'cause I use standart day reset time (00:00) and didn't use tavern in weeks.

ID: 950883ae-b0a0-4c4e-92bc-b1a1bda1747c

**Comment by Alys** [comment]
Another instance of cron running twice within the same day has been reported by @Piskvor at https://github.com/HabitRPG/habitrpg/issues/4189#issuecomment-72012704 (no time or timezone changes that might have caused it).
