### ISSUE TITLE
Ignore/block list [$45]

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4218]
Another user offered to put a bounty on it (and I expect others might like to as well) , so I'm making the card for it. Please advise if I've messed it up.

Request: An ignore/block feature. A way to say "I don't want to see this person's posts anywhere I go." Perhaps a toggle in a person's profile, or a :no_entry_sign: button next to the +1. 

Naturally this would also need a place to go and see your blocklist, so you could un-block someone in the future if desired.
## 

(Optional, appreciated if they're something efficient to code at the same time: "Hide this message" for blocking specific posts instead of people; ability to block a person in some places but not others [guild but not tavern, for example])

Semi-related Trello card: https://trello.com/c/gFieBjCB/376-messaging  (Mostly about a friends-list idea, but some comments on an ignore feature), 
##

**Comment by Gaelan** [comment]
I'd love to have this button for challenges as well. There's this certain challenge I really want to go away…

**Comment by ghost** [comment]
I am not into habit code and therefore am talking from my hindquarters, but the ignore feature _may_ work out in a way that ignoring a person also blocks their challenges.  (Not something I'd consider required for winning the bounty, though, since maybe I'm wrong and that'd be an entirely separate task.) 

If it's an offensive challenge, you might also flag a mod down; I believe they're working on expanding their ability to banhammer naughty challenges.

**Comment by librarianmage** [comment]
Hasn't this been done @Alys?

**Comment by crookedneighbor** [comment]
No. It has been implemented for the inbox, not for posts in guilds/party/tavern.

**Comment by librarianmage** [comment]
Oh.

**Comment by paglias** [comment]
Some useful discussion at https://github.com/HabitRPG/habitrpg/issues/2489

**Comment by lemoness** [comment]
We're still open to this in the future, but requests for this have hugely decreased since we've begun to moderate the community more heavily. I'm going to close it for now, but we can always reopen it if we decide that it's something we want to actively pursue.
