### ISSUE TITLE
Highlight rewards depending on gold amount

### ISSUE THREAD

**Issue by unchiujar** [HabitRPG/habitica#422]
Colour the rewards that cost less than the amount currently available in blue (or other colour or don't colour at all)  and the rest in red. This clearly communicates what is available for buying without penalty to health and also helps pick a reward in line with the amount of money one has.

**Comment by Pandoro** [comment]
I am not sure if it will be handled like this, but at some point in the future there will be a warning system before purchasing something you might get hp damage from. See this [Trello car](https://trello.com/card/confirmation-for-gold-spending/50e5d3684fe3a7266b0036d6/64)

Will that suffice for you, or is your suggestion more based on the fact that you want to see it before hand already? 

Edit: I just noticed that this alert is already there, at least on the test server it is available. So I am guessing you are going more for the color, not the notification?

**Comment by toebu** [comment]
Simply greying out the items that are too expensive might do the trick without introducing more visual clutter in form of colours. Surely a quick and useful change.

**Comment by lefnire** [comment]
actually yeah, +1 @toebu's suggestion

**Comment by unchiujar** [comment]
I was actually considering what  @toebu said when I posted the bug. The main point is to make immediately visible what is affordable and what's not but I went the red/green route since I thought it may be more suggestive.  

But yeah, +1 @toebu  :)

**Comment by wc8** [comment]
I updated the checklist item for shading the rewards that aren't affordable to "grey-out". 
[Show Progress Toward Rewards](https://trello.com/c/K7xOkD7a) request is a related request.

**Comment by wc8** [comment]
This request now has its own Trello card: [Shaded Rewards by Cost](https://trello.com/c/ZSIhV9cz). Vote if you're interested, especially @unchiujar.
