### ISSUE TITLE
Can´t login with facebook

### ISSUE THREAD

**Issue by chesterguara** [HabitRPG/habitica#4222]
In the past few days, I´m having trouble connecting to HabitRPG in my workplace. My account is linked to facebook, and everytime I try to connect, comes the message {"err":"This authorization code has been used."}, or most of the times, the message:

"Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

Worse yet, I´ve been able to connect at home so I tought it was a problem with my company internet connection, but as of today, I get the same message when I try to access it from home. What´s going on?

**Comment by lefnire** [comment]
#4221
