### ISSUE TITLE
How to update Fontello?

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4223]
@Alys question for ya: how should I add icons to our Fontello install? I presume you selected a handful of icons and downloaded a custom build. If that's the case, I imagine the best way would be to maintain a running list of all downloaded icons, so we can add to that build by re-selecting those icons, plus any we want to add, and re-download the build. (does that sound correct?)

PS, pinging here instead of email so other devs can see the sol'n

**Comment by Alys** [comment]
Yes, I used http://fontello.com/ to download some that I selected (the crown that we needed and a few others that looked useful). After selecting them, you click the red "Download webfont" button and then you get a zip file whose contents can be used to completely replace everything in https://github.com/HabitRPG/habitrpg/tree/develop/public/fontello

The first time anyone does this, do careful testing to ensure that my information here is accurate.

You can see the selected ones by viewing https://github.com/HabitRPG/habitrpg/blob/develop/public/fontello/demo.html in a way that actually makes it a webpage, not raw HTML (e.g., open your local install copy of the file in your browser). That file will be updated when you download a new set, so it should be a good way of tracking the ones we have selected. Here's what it looks like:

![screen shot 2014-11-07 at 7 42 21 am](https://cloud.githubusercontent.com/assets/1495809/4944461/1521c370-65fe-11e4-8adf-7f90022e5bac.png)

**Comment by lefnire** [comment]
Oh perfect, didn't see the demo.html file, thanks!
