### ISSUE TITLE
Missing tasks

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4224]
Hi, i just added a number of new tasks on the habitrpg app but when I came back, they were all missing.  I tried habitrpg on safari and chrome but it's still the same, missing the new tasks?  Worst thing is, I can't remember how many I added or what most of them were (they were mostly little chores I wanted to do).

So any help would be wonderful.

**Comment by lemoness** [comment]
Hi there! Sorry to hear that you're having trouble. That sounds to me like
you may accidentally have a tag enabled - can you try clearing your tags?
Let me know if that helped.

**Comment by ghost** [comment]
Hi, I tried clicking the clear button next to the tags.  It didn't really work...I did remember when I was making those tasks that words like "undefined Nan nan" came up underneath the title of the tasks and I just figured they were bugs of the new update to the ipad app.  

Anyway, I found a previous backup of the same list in my google drive so I'm just using that for now.  Other than that, I still love habitrpg.  Thanks for helping!
