### ISSUE TITLE
Character back to level 1; all habits gone

### ISSUE THREAD

**Issue by efthermc** [HabitRPG/habitica#4227]
I couldn't find this specific issue anywhere else. Sorry if it's out there and I didn't find it.

This is the third time this has happened. I check off all my dailies. I'm doing good on my habits. I want to make it clear that there was no reason for me to die. I'm not in a party or fighting a boss or anything like that. I log back in the next day, and my character died. I'm not only down one level, like it says I should be, I'm at level one. All my habits are gone. Animals gone. Potions gone. Everything is gone. It's like I just signed in and started. What's going on? I was level ten, and only because I fixed my character from the last time this happened. I would really like to use this site, but this is really frustrating. I can't trust the site to actually be the same the next day. Please help.

User ID: 9eec4efe-64af-4569-acc8-912eac5d00b7
Firefox 33.0.2
Mac OSX 10.7.5

**Comment by efthermc** [comment]
Btw, I refreshed several times yesterday, and everything seemed fine.

**Comment by efthermc** [comment]
I know I can fix my characters level, etc. The big issue is that I spent hours entering in my habits, sorting out dailies, and organizing my whole page nicely, only for all of that to be gone. I've found no reason why dying should erase all the work I put into entering habits.

**Comment by paglias** [comment]
It is possible that you have two account? One with Facebook and one with email? If you remember your UUID or username could you post the here? If you remember the email address and don't want to publish it here you can send it at matteopagliazzi@gmail.com

**Comment by efthermc** [comment]
I don't use Facebook. I know that sounds odd, but I lived in China for several years. It was always blocked, so I never use it anymore. I do have an iPad. I suspected the iPad and computer weren't playing well together the first time I died. So I stopped using Habitrpg on my ipad and deleted the app there.

**Comment by paglias** [comment]
OK, can you send me the email address you registered with at matteopagliazzi@gmail.com?

**Comment by paglias** [comment]
@efthermc that's strange...

There are 4 account registered with the email you sent me, all of which were create on October 10 this year at the same hour with a difference of just a few seconds.

One, with the UUID you posted above had its last login today, another one yesterday and the last two on the 21th and 7th of October.

If you remember for example the name of a task you created in the "real" account you had used today I can save it and delete the others, just send me an email as before with something I can use to identify your account's tasks (a daily, todo or habit...)

pinging @lefnire

**Comment by efthermc** [comment]
Wow. That is really strange. I remember when I registered in October, there were problems with signing up. The page didn't load properly, and I had to try several times to make an account. I guess those accounts were actually made. Is it usual for the site to allow multiple accounts to the same email/password? I've used the same userid/password combo every time I signed in. How about this: Just delete all the accounts except one. I'll login and fix that one. I think the multiple accounts were obviously causing this issue. Do you think that will work?

**Comment by paglias** [comment]
@efthermc yes, we're sorry about that, it usually check for duplicates before signing up but it might have been that for some reason the database wasn't properly checked.

About the solution: if you sign in and delete each account until you find the right one it should work. Then you can send me the right UUID and I'll delete any other that might not have been deleted because you found the right one before getting to it

**Comment by efthermc** [comment]
I want to make sure I understand before I try this. I sign in. If the account looks wrong, I delete the account. Then sign in again. Until I see the right account. Then I send you the UUID. Does that sound right?

**Comment by efthermc** [comment]
This one is the right one: 30036e57-f525-461b-9ac4-2525be9ffc66

**Comment by paglias** [comment]
@efthermc thanks! deleted the remaining two, you shouldn't encounter any problem anymore

**Comment by efthermc** [comment]
Thank you very much for solving this problem!
