### ISSUE TITLE
Vagrant build fails with ETXTBSY error at angular-ui-select

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4228]
Tried creating a HabitRPG Vagrant box per the instructions [here](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Vagrant), but `vagrant up` stalls while setting up `canvas`/`gmsmith`:

![image](https://cloud.githubusercontent.com/assets/4501321/4969310/3973c7b8-685c-11e4-8067-0855de8a8914.png)

So many difficulties in setting up local builds seem to stem from that branch of dependencies...

This happens on a Windows 7 host machine, if that matters.

**Comment by Alys** [comment]
For me, it always gives the "optional dep failed" message, which I ignore since it's optional, but I've never noticed it stalling there. If you go through the process a second time, does it still halt or hang at that point?

**Comment by SabreCat** [comment]
I can give it another try. Maybe I'll let it sit overnight and see if it ever completes...

**Comment by SabreCat** [comment]
Ah, shoot. It seems to have gotten past that step, but then quit out with this:
![image](https://cloud.githubusercontent.com/assets/4501321/4969703/953a4808-6869-11e4-80d0-e17659ad3f8c.png)

**Comment by Alys** [comment]
Try:

```
vagrant ssh
cd /vagrant   # might not be necessary but won't hurt
rm -rf  public/bower_components
bower cache clean
bower install -f
```

**Comment by SabreCat** [comment]
Throws the same error.

**Comment by lefnire** [comment]
permissions everywhere.

``` shell
cd ~
# blast bad permissioned folders
sudo rm -rf habitrpg habitrpg-shared .npm
# fix npm perms
sudo chown -R `whoami` /usr/lib/node_modules
# reclone both repositories
git clone https://github.com/HabitRPG/habitrpg.git
git clone https://github.com/HabitRPG/habitrpg-shared.git
```

**Comment by lefnire** [comment]
I think this is the sol'n, if not re-open
