### ISSUE TITLE
"Undo" does completely revert.

### ISSUE THREAD

**Issue by Raytray** [HabitRPG/habitica#423]
Checking and unchecking a daily does not negate it's reward. So click spamming the same daily produces surplus gold with no progress.

**Comment by Pandoro** [comment]
This has been reported several times already, see for example #286. We are aware of this issue, but it does not have a very high priority. You will be cheating by doing this and thus you will only be cheating yourself. Furthermore as @SlappyBag mentioned very nicely yesterday "If you are using this, you are a very bad cheater, as you can get gold in easier ways." ;) So considering this, it will be fixed at some point, but for now we will just give the player the "benefit of the doubt" when unchecking dailies. You will have to decide yourself if you want to use it and it will at least not hurt you if you check/uncheck by accident :) Right now there are more important bugs though :x 

Thank you for reporting this nevertheless!
