### ISSUE TITLE
Tag sorting does not work with a large number of tags

### ISSUE THREAD

**Issue by LeanderMcL** [HabitRPG/habitica#4232]
I have a large number of tags and am currently unable to sort them properly.

I have two major problems:

First: sometimes when I accidentally click near instead of right on a tag (trying to select/deselect), it will randomly "jump" to another place in the tag list. I can't seem to replicate this on purpose but it's happened repeatedly by accident.

Second: I have many tags (they take up 5 or so lines above my tasks) and when I pick up a tag it is almost impossible to drop it in the desired place. Because the tags move out of the way to make space for the tag, it's almost impossible to put my cursor in the place I need to, and in any case moving the cursor up/down doesn't seem to work reliably, and I can usually only put the tag on line 3, 4 or 5 (sometimes, but rarely, line 2).

I have tried this in both Firefox 32 and Chrome.

**Comment by TheHollidayInn** [comment]
I think this should be fixed by https://github.com/HabitRPG/habitrpg/pull/4991 .
