### ISSUE TITLE
Export Streak Data for Challenges

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4233]
Many Challenges are awarded based on streaks, so it would be nice to have streak data exported automatically with the other information.
##

**Comment by pollockjj** [comment]
When #4261 is resolved successfully, I'll be more than happy to start attacking this one.

**Comment by crookedneighbor** [comment]
@pollockjj #4261 has been merged. 

You mentioned being new to git, so here's something that might help you for the future. Instead of committing to your develop branch, checkout a new branch. That way, you can work on multiple issues at once!

This is my normal workflow:

``` bash
# Set up upstream branch (Only done once)
# If using HTTPS instead of SSH, use https://github.com/HabitRPG/habitrpg.git
git remote add upstream git@github.com:HabitRPG/habitrpg.git

# Update develop branch with new changes to develop
git fetch upstream develop
git rebase upstream/develop

# Create a new branch to work on the issue/feature
git checkout -b feature-or-issue-name-whatever-you-want-really
```

**Comment by pollockjj** [comment]
@crookedneighbor  - Thank you very much for the guidance during the previous ticket and for the advice on branching per ticket. 

I will integrate this into my workflow.

**Comment by Verabird** [comment]
@pollockjj Are you still working on this? If not I'm thinking of taking a crack at it.

**Comment by pollockjj** [comment]
Blade - I was going to take a crack at it now that I have some vacation
around Christmas, but I don't want to hold back the wheels of progress. Let
me know and I'll look for something else instead.

Happy Holidays!

## 

John Pollock
Burnsville, MN  55337
(612) 293-7792

**Comment by Verabird** [comment]
Go ahead pollockjj, you have first dibs

**Comment by crookedneighbor** [comment]
@Verabird and @pollockjj Either of you want to work on this still?

**Comment by Verabird** [comment]
I'm not currently working on it.

**Comment by crookedneighbor** [comment]
Since I haven't heard back from @pollockjj, I'd say this is free for anyone to work on.

**Comment by pollockjj** [comment]
My apologies.

I am obviously unable to devote the time to this that it needs at this time.

I relinquish all claim to the issue.

John

## 

John Pollock
Burnsville, MN  55337
(612) 293-7792

**Comment by librarianmage** [comment]
How would this be formatted, if some tasks that are exported aren't Dailies?

**Comment by Alys** [comment]
@MathWhiz I guess use a value of 0 or N/A for tasks that aren't Dailies.

Possibly the column header could be "streaks/counts" and then the column could include the + and - counts for Habits.
