### ISSUE TITLE
Must create new account on website before using mobile app

### ISSUE THREAD

**Issue by becomesaflame** [HabitRPG/habitica#4234]
I created a new account using Facebook login on the mobile app.  Then, I logged in to the website with the same Facebook login.  It created a new character, with none of the changes I'd made in the app.  I tried uninstalling the app and reinstalling it, and it solved the issue - the app synced up with the website.  

I'm posting this just to record the issue, and help people who have the same problem.

**Comment by lemoness** [comment]
@lefnire - I wonder if this is related to the duplicate accounts bug -
sounds similar.

**Comment by paglias** [comment]
Can't replicate
