### ISSUE TITLE
Feature Request: Integration with Mnemosyne (a flashcard program like Anki)

### ISSUE THREAD

**Issue by ancientcampus** [HabitRPG/habitica#424]
I use Mnemosyne, which is a flashcard program like Anki or Supermnemo. It's open source and supports add-ons, so I figure integration would be done by making a plug-in to send info to HabitRPG. I realize this is fairly low priority, and would be handled by one of the awesome volunteer code-monkeys. I can definitely say that getting a (+) habit for every card I hit (even with the inevitably tiny bonus it'd give), though, would really help motivate me. Heck, if I could see "+0.1 XP" every time I get a question right, that'd be friggin amazing.

I'm not sure if Anki supports plug-ins or not. If an Anki add-on gets developed, though, I'd cheerfully switch.

**Comment by lefnire** [comment]
Yeah, we'll have a full REST api within 1-2 weeks. Then we're hoping people will take care of those less popular integrations. I'm kinda hoping someone does on for Anki, that's my MO

**Comment by lefnire** [comment]
just for up/down voting, - or yeah, i suppose they can do that for Mnemosyne. Should be all set :) I was talking about the full REST api for user management, which is required for some more complex stuff

**Comment by lefnire** [comment]
oo! where where? I'd use the eff out of that

**Comment by antistic** [comment]
@Elexhad You could probably ask at https://groups.google.com/forum/?fromgroups=#!forum/mnemosyne-proj-users or https://groups.google.com/forum/?fromgroups=#!forum/mnemosyne-proj-devel . I'd love to see a mnemosyne plugin!

**Comment by lefnire** [comment]
I think that's good, upping a card if you go wrong. IMO the only time you should lose points is maybe a day gone without - but that might be hard, daily + habit conflict kinda

**Comment by lefnire** [comment]
Good call

**Comment by wc8** [comment]
Trello: [Anki](https://trello.com/c/7VPBaM1l)

**Comment by ooker777** [comment]
Edward Shapard has written a new addon. Please update its Trello and link to the [wiki page](http://habitrpg.wikia.com/wiki/Anki_Extension)

**Comment by Alys** [comment]
@ooker777 Can you paste in the URL to the Trello card?

If you'd like changes made to the wiki page, you're welcome to go ahead and make them. You don't need a wikia account.

**Comment by ooker777** [comment]
@Alys actually it's the link in the comment above mine: https://trello.com/c/7VPBaM1l/31-anki
The wiki has already edited, just need to link it from the Trello card.

**Comment by lemoness** [comment]
@ooker777 Thanks for letting us know! I've updated the Trello card.
