### ISSUE TITLE
Avatar Share Not Visible on Phones

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4240]
When you click on an avatar share link on your phone, it takes you to the static page and does not bring up the avatar popup. 
##

**Comment by paglias** [comment]
@lemoness can you give an example link?

**Comment by lefnire** [comment]
She means the "share" button isn't working properly on mobile website
(right?). Kinda expected that, since there's a few click handlers there and
tapping also brings up hover effects

**Comment by lemoness** [comment]
No, when I am browsing Twitter on my phone and try to click a link to see
someone's avatar, it doesn't work.

Here's a sample from a Tweet:

https://habitrpg.com/static/front/#?memberId=b8a84fcf-9ac7-40b0-bae3-53bf64df6d5f

I can view it on my computer but not on my phone.

**Comment by paglias** [comment]
@lemoness which phone? I couldn't replicate on Chrome on Android 4.4

Can you check wheter the part of the url after `#` is getting stripped from the phone's browser?

**Comment by lemoness** [comment]
iOS 7.1.1

**Comment by librarianmage** [comment]
This works for me on mobile (iOS 9.something, Chrome)

**Comment by Alys** [comment]
I'm closing this because it's something that will change in an upcoming website redesign (and possibly is indeed working now on mobile browsers).

**Comment by Alys** [comment]
@MathWhiz Thanks!!
