### ISSUE TITLE
Experience bug

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4243]
I just cast Burst of Flames on a task, got a boatload of experience, and then I didn't level up. Syncing and reloading didn't fix the problem, and only once I ticked off a task which gave me more experience (habit, to be specific), did it update and check for level up. This is clearly not expected behavior. :)

![screenshot_3](https://cloud.githubusercontent.com/assets/1434020/5058463/c8039ba4-6cbf-11e4-9ec2-2b8b62ac075d.png)

**Comment by Alys** [comment]
This has been reported here; https://github.com/HabitRPG/habitrpg/issues/2143 
You can follow that thread for progress on the fix for this bug (see the Notifications section in the right-hand menu if you want email notifications).

**Comment by bTackt** [comment]
Oops, sorry! Should have remembered to search first.
