### ISSUE TITLE
paypal.js "billingPlanID = plan.id" causes local installs to fail (quick-and-dirty "fix" provided; need proper fix)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4246]
**FYI for developers**

When I updated my local install to use the latest code from `develop` (and the latest paypal-ipn and paypal-rest-sdk packages from package.json), I found that npm start would produce this error:

```
$ cd /vagrant && npm start

> habitrpg@0.0.0-152 start /vagrant
> grunt run:dev

Running "stylus:build" (stylus) task
File build/app.css created.
File build/static.css created.

Running "concurrent:dev" (concurrent) task
Running "nodemon:dev" (nodemon) task
Running "watch" task
Waiting...
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./src/server.js`
info: Express server listening on port 3000
info: Connected with Mongoose
info: Express server listening on port 3000
info: Connected with Mongoose

/vagrant/src/controllers/payments/paypal.js:75
      billingPlanID = plan.id;
                          ^
TypeError: Cannot read property 'id' of null
    at exports.createBillingAgreement.billingAgreementAttributes.name (/vagrant/src/controllers/payments/paypal.js:75:27)
    at /vagrant/node_modules/async/lib/async.js:544:30
    at /vagrant/node_modules/paypal-rest-sdk/lib/api.js:72:13
    at /vagrant/node_modules/paypal-rest-sdk/lib/api.js:63:9
    at IncomingMessage.<anonymous> (/vagrant/node_modules/paypal-rest-sdk/lib/client.js:114:13)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
info: [Sun Nov 16 2014 06:04:41 GMT+0000 (UTC)] [master:4436] worker:4443 disconnect! new worker:4464 fork
```
## Quick-and-Dirty Fix

To get my install working straight away, I edited line 75 of [src/controllers/payments/paypal.js](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/payments/paypal.js#L75) to change it from this:

`billingPlanID = plan.id;`

to this:

```
if (plan) {
  billingPlanID = plan.id;
} else {
  billingPlanID = "none";
}
```

**If you do that on your own local install, make sure you do NOT submit it in any commits or pull requests you might make (i.e., don't do `git add src/controllers/payments/paypal.js` or `commit -a`).**

This fix is a nasty hack but it should let you keep on programming and testing, as long as the code you are working with does not have anything to do with paypal payments!
## Proper Fix

I suspect this error is happening because I don't have some settings needed for the paypal code to work properly, or don't have access to some private subscriber-related code, or I haven't installed a new software requirement, or my local install can't communicate with paypal, or something else. Summary: I have no idea. :)  If I find the time, I'll try to investigate further, unless anyone more clueful than I am gets to it before I do.

**Comment by paglias** [comment]
Mmm.. updated modules and config but doesn't fix. I would add a check for being in PRODUCTION but I don't want to disrupt @lefnire workflow if he need it in dev

**Comment by Alys** [comment]
Agreed about disruptions to lefnire's workflow! The workaround is very easy to do.

**Comment by lefnire** [comment]
Sorry about this y'all! The proper fix would be one of two things:
1. Rather than bail `if (node_env!='prod')`, bail if the credentials don't work (aka, `config.json` doesn't have real creds in there for testing). This because I do a lot of paypal stuff on develop (`PAYPAL:mode=sandbox`).
2. OR, I may need to move that billing plan setup setup out of `paypal.js` altogether, and into a migration script. I discussed in the PR, that step is a one-time setup and it's awkward where I put it (it's lame that setup isn't on Paypal's admin dashboard, rather than required to be in code - Stripe handles this the correct way). So I'll look into moving it to a migration script and doing `plan.id=nconf.get('PAYPAL:planID')` or something

In the meantime, 1 will be the easiest workaround

**Comment by lefnire** [comment]
sorry, @Alys's is sufficient for now ^

**Comment by lefnire** [comment]
moved to separate init file. previous setup was causing more major issues anyway

**Comment by taldin** [comment]
Is it safe to update our local installs now?

**Comment by lefnire** [comment]
Yesm

**Comment by taldin** [comment]
A'righty.  Thanks!

**Comment by paglias** [comment]
Yes, just tested
Il 16/nov/2014 20:40 "taldin" notifications@github.com ha scritto:

**Comment by Alys** [comment]
Thanks heaps @lefnire!

**Comment by lefnire** [comment]
Np!
