### ISSUE TITLE
Website graphic glitch happens on page refresh but only sometimes.

### ISSUE THREAD

**Issue by lordmatt** [HabitRPG/habitica#4257]
I have observed a graphical glitch that I am not entirely able to explain that happens sometimes when using Firefox. A (second) refresh fixes the problem so it is not earth shatteringly bad but the sprite graphic appears to load wrongly which makes things look a bit... odd.

![erm are you sure those are the right graphics](https://cloud.githubusercontent.com/assets/1843653/5102199/7c9ed028-6fbe-11e4-92be-b197e77c7424.png)

I do not recall seeing the error on first page load but as I tend to keep the HabitRPG tab open most of the time I do not see many first load instances. My assumption is that the main image file containing the graphics corrupts in some way but I have no way of testing this.

**Comment by Alys** [comment]
Please see the explanation and solution here: https://github.com/HabitRPG/habitrpg/issues/3830 (in brief, whenever you see something odd like this, reload the page).
