### ISSUE TITLE
Keep Parties After Having Gained It Once 

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#426]
I level up to quickly so I often have to reset to level 1. I love the party feature, anyway to keep that after you gained it once.

**Comment by lefnire** [comment]
Do you lose the party feature when you reset? I can't replicate

**Comment by ghost** [comment]
Yes

**Comment by tmas** [comment]
Maybe features like parties could depend on a separate variable that represents the maximum level that user has ever gotten to? This could keep it simple for new users but allow experienced users to reset to level 1 while keeping all of the features they had unlocked.

**Comment by StanLindsey** [comment]
I don't think @lefnire planned for it to reset. I'm fairly sure this is a bug not a suggestion. =P

**Comment by ghost** [comment]
@slappybag I think so too
@lefnire what do you think?

**Comment by lefnire** [comment]
Yeah, it's not supposed to reset. I'll look into this

**Comment by lefnire** [comment]
is anyone else experiencing this? I can't replicate
