### ISSUE TITLE
Differentiate Locked and Unlocked Backgrounds

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4261]
Right now it's pretty unclear which backgrounds you have bought, especially if you bought them individually instead of as a group (because then not even the purchasing instruction changes). It would be nice to have it highlighted in gray or have a similar visual marker that changed.

**Comment by pollockjj** [comment]
Alys in the Aspiring Legends guild chat mentioned that this type of functionality might have been implemented elsewhere and that this might be as simple as copying said method. Not sure where to start looking but if someone can point me in the right direction I can start digging in.

**Comment by Alys** [comment]
I was thinking of the User -> Avatar screen, where things have a grey
background before you buy them. :)

**Comment by pollockjj** [comment]
I see what you mean, Alys. Now I just need to dig in and look at how it works on the Avatar screen. Probably some changing of the color of a transparent background (just an assumption, as I am nowhere near being able to see the actual code properties that change there). I don't see any reason why we couldn't do a grey border like that on the background screens or even a corner diagonal banner overlay that says "purchased" or something like that (e.g. http://dragonartz.files.wordpress.com/2009/09/vector-corner-ribbons-cs-by-dragonart.jpg for an example of what I was thinking of.)

**Comment by lemoness** [comment]
I support any method that doesn't change the color of the art itself or
hide a large portion of it - so borders would be my top choice!!

**Comment by pollockjj** [comment]
Understood, lemoness. Thanks.

**Comment by pollockjj** [comment]
Ok, just reporting what I finding here as I don't know if I am on the right track or not:
1.  It looks like I was correct in that the image background color in spritesmith0.png (which contains both the **avatar-backgrounds** and some of the **avatar-customizations**) is transparent. This works well for the Avatar customizations and allows for any background color to exist underneath.
2.  The **avatar-backgrounds** are virtually seamless (as in one transparent pixel separating them from each other) meaning that a border can't be added in there without modifying _spritesmith0.png_ asset - which I don't know if that is an option or not - certainly not if it would require a re-jiggering of all the co-ordinates for every other sprite used from the file
3.  Based on a page source analysis, the **avatar-customization** button-icons have some conditional language (looks to be AngularJS) in there which include an if statement (e.g. "ng-if=!user.purchased.hair.color.XXX") in which it appears the scope of the element changes from "locked" to not having the locked property. I am assuming that means that somewhere the "locked" property changes the background color of the image being displayed.

So, where does that leave us:
1. Need to confirm that the same conditional would work for the background page (e.g. "ng-if=!user.purchased.background.starry_skies")
2. Need to understand if an overlay can be used, either to indicate it has not yet been purchased, or that it already has (see this example that doesn't agree with **lemoness**' guidance, nor the 8-bit theme, but just an example):
   
   ![Example](https://dl.dropboxusercontent.com/u/6814765/purchased.png)
3. If an overlay is deemed not thematically consistent, then a larger transparent border could be added to the images (and a color change like in the **avatar-customization** page, but once again would require a change to the _spritesmith0.png_ asset.)

Any thoughts or feedback are welcome. I will continue investigating the code side of things but as a newbie I just want to share where I was at thus far before I go too far down the wrong path.

**Comment by Alys** [comment]
A quick glance at the data makes me think that `user.purchased.background.starry_skies` is likely to work as you describe.

I think a border added around the background images is probably the best way to go, but it would be best to do it without modifying the png files. Can you use pure CSS to add the border? It would be a transparent border if purchased and a grey one otherwise.

Your code doesn't have to work in exactly the same way as existing code. What would be beneficial though is if the behaviour that the code implements looks the same to the user, so that they will already be familiar with the new interface changes.

**Comment by pollockjj** [comment]
A CSS border should work. I'll dig into it further and see where I need to implement the two changes (conditional, border).

Thanks for the feedback.

**Comment by pollockjj** [comment]
The plan is to put a gray border around non-purchased backgrounds, and a white border around purchased borders (transparent doesn't work as it extends the image around the boarder and picks up adjacent colored pixels from the _spritesmith0.png_ asset)

I've been able to mock this up by manually setting the .css in the page. 

It would look like this:
 ![](https://dl.dropboxusercontent.com/u/6814765/gray_border.PNG) 
with the far right being a "purchased" background.

**Comment by pollockjj** [comment]
I think I have a reasonable solution that includes a gray border for locked backgrounds and a white background for unlocked.

Adding a border to the image purely using .css does appear to scavenge the border-width from the edge pixels on the right and bottom image, so the style includes widening the image as well to account for this without having to mess with editing the style for the `spritesmith.png`.

A video of live code of my proposed solution on a local instance can be found [here](https://dl.dropboxusercontent.com/u/6814765/habitrpg_background.mp4)

Any feedback welcome. If the solution looks to be acceptable, I will begin figuring out how and where to commit the change to the dev branch.

**Comment by Alys** [comment]
@pollockjj  The appearance of the Backgrounds looks fine to me. I say go ahead with doing a pull request. If you'd like help with that, just ask. As a brief overview of how I'd do it:

```
git commit -a
# assumes that ALL changes in your local install should be committed and that all are related to this Background fix; if not, use "git add file1 file2" and "git commit"

git push origin name_of_your_local_branch
# name_of_your_local_branch might be "develop" or something else

go to https://github.com/YourUsername/habitrpg and you will see a Pull request button
```

That's all from memory, so it's possible I've forgotten something. Don't be reluctant to ask if it doesn't seem to be working.

**Comment by pollockjj** [comment]
Done. (At least, I think it is).

https://github.com/HabitRPG/habitrpg/pull/4299
