### ISSUE TITLE
Score of most of my habits has dropped precipitously

### ISSUE THREAD

**Issue by melissamcewen** [HabitRPG/habitica#4263]
Yesterday I noticed I wasn't doing any damage on the quest, so I looked at my tasks and they seem to be a bit messed up- the scores of them have dropped dramatically even though I've been doing them - here are just a few examples
![but I document all the time](https://cloud.githubusercontent.com/assets/1251094/5154647/220d195a-722d-11e4-9813-5e2a4e246000.png)

![habitrpg___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/1251094/5154649/39acca9c-722d-11e4-9cb4-d701e931f469.png)

The only thing I can think that changed lately is I removed the minus button from them because when I set them up I didn't know that was an option to remove.

**Comment by melissamcewen** [comment]
OK actually it turns out I am doing quest damage and it's super high - normally it's around 40 or so
![habitrpg___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/1251094/5154667/a3bde0f6-722d-11e4-8319-085234a7a6c3.png)

**Comment by lemoness** [comment]
Hi Melissa!

When you have a + only or - only Habit, they gradually drift back to a
yellow neutral state - I think that's probably what you're seeing :) Habits
don't actually count towards Boss damage yet, so they aren't connected to
that. Does that sound like what happened?

**Comment by melissamcewen** [comment]
Oh, thanks, that makes sense.
