### ISSUE TITLE
few emoji are broken

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#4265]
Just realized that the emoji :neckbeard: `:neckbeard:` doesn't render on HabitRPG. Might be others, something to look into.

**Comment by negue** [comment]
We use this emoji-library: https://github.com/snicker/js-emoji , and this library doesn't have a `:neckbeard:` Emoji

**Comment by AdrienLemaire** [comment]
I see. @snicker can you update your lib ? :) Thanks!

**Comment by snicker** [comment]
We can pull from the main repository now. The reason I had forked before was to support minification of the code, but my commit has since been implemented in master:
https://github.com/iamcal/js-emoji

Can someone handle updating the deps?

**Comment by snicker** [comment]
:+1:

**Comment by negue** [comment]
`:neckbeard:` also not exists in the master-repo

**Comment by lefnire** [comment]
ah..

**Comment by Jonta** [comment]
<code>:feet:</code> is also different from the [cheat sheet](http://emoji-cheat-sheet.com). It displays :feet: instead of :footprints: (the latter being <code>:footprints:</code> here on GitHub and on HabitRPG).

Not that the library is bad, but linking to one that isn't accurate is confusing. =)
