### ISSUE TITLE
Experience Points greater than amount needed to level up

### ISSUE THREAD

**Issue by tacmyers** [HabitRPG/habitica#4266]
Experience: 1,043 / 850---    Shouldn't this have leveled me up?  Refreshed-- still there.

User ID  cc406798-76d5-45a9-b750-c7eb657b58de

browser - Chrome  on Windows 8-- the web version
Shows same on Android-Kit Kat-

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2143

Tick off any task and you'll level up.
