### ISSUE TITLE
Level Gain Reversed After Casting Backstab

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4269]
Reported on Twitter: 

"Dangit habitrpg is doing that thing where it won't let me level up..." 
(I responded: "Is it where you have XP that says something like 112/100? If so, that's caused by a skill. Check off a task to level up!")
"I do that, and level up, but then there's an error and it goes back down to the previous level! This doesn't happen if I level up by just checking off tasks, though. It's only if I use a skill to level up. I get this error [see screenshots], and then things are okay until I reload the page, then the level goes back down. I'm a rogue! Usually it happens when I backstab a task. Tons of experience! But then pththth. Other tasks register. I usually fix it just by wailing on a habit until my level goes back up again to where it should be. Kinda forcing a level up."

I've attached their screenshots and am directing them to this Github thread so that they can answer any other questions. 
![b3pcrlxcqaaezat png-large](https://cloud.githubusercontent.com/assets/3494081/5175452/ea1d086a-73ef-11e4-8953-f79d11c07f25.png)
![b3pcrlyceaal78k png-large](https://cloud.githubusercontent.com/assets/3494081/5175453/ea36c070-73ef-11e4-802c-2137dc686dd6.png)

**Comment by Alys** [comment]
I'm closing this because we fixed the bug that prevents level-up from skills.
