### ISSUE TITLE
Blue sync bar missing

### ISSUE THREAD

**Issue by emguthrie** [HabitRPG/habitica#4270]
Since the most recent update that added PMs, I no longer see the blue sync bar that goes from left to right at the top of the page after pressing the sync button, indicating that syncing is in progress.

Quoth Alys, "_I'm not sure if that was intentional, but I think the bar was an important indicator for avoiding sync errors, so it's probably still meant to be there._"

**Comment by paglias** [comment]
@DrippyTheOrc @Alys it should be working now https://github.com/HabitRPG/habitrpg/commit/f5d0b7957306370f18c42c1b37c296a7d03423de

**Comment by paglias** [comment]
Let's close after it has been verified

**Comment by emguthrie** [comment]
It's been back for a day or two now. Thanks!
