### ISSUE TITLE
date picker not appearing

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4273]
When editing a task, the date picker no longer appears when you put the cursor in the date field.

Google Chrome v 38.0.2125.122 (MacOS 10.6)
Firefox 33.1 (MacOS 10.6)

Chrome's console doesn't show any messages that seem to be relevant.

**Comment by lefnire** [comment]
possible lead: we upgraded angular-ui-bootstrap from 1.11.0 => 1.12.0 (for compatibility with our angular 1.3.3 upgrade).  Maybe [datepicker](http://angular-ui.github.io/bootstrap/#/datepicker) is handled differently in 1.12.0

**Comment by bTackt** [comment]
This is happening for me as well.
