### ISSUE TITLE
Cannot tick or untick "use Costume"

### ISSUE THREAD

**Issue by LockeLamora** [HabitRPG/habitica#4274]
I have been using a costume as a rogue type character, switched to a warrior and bought the armour etc for that new character type

I wanted to see the new gear, but hitting "Use costume" won't untick the box or cause the costume to stop displaying on the avatar (Although it does sent off a batch-update POST - response is just a simple reply like {"_v":792})

**Comment by lefnire** [comment]
Confirmed. This one's strange, in other places we're using a ternary instead of `set('x': !x)`. I tried that here:

``` diff
diff --git a/views/options/inventory/inventory.jade b/views/options/inventory/inventory.jade
index 8303698..367f0be 100644
--- a/views/options/inventory/inventory.jade
+++ b/views/options/inventory/inventory.jade
@@ -11,7 +11,7 @@ script(type='text/ng-template', id='partials/options.inventory.equipment.html')
         h3.equipment-title.hint(popover-trigger='mouseenter', popover-placement='right', popover=env.t('costumeText'))=env.t('costume')
         .checkbox.equipment-title
           label
-            input(type="checkbox", ng-model="user.preferences.costume", ng-click='set({"preferences.costume":!user.preferences.costume})')
+            input(type="checkbox", ng-model="user.preferences.costume", ng-click='set({"preferences.costume":user.preferences.costume ? false : true})')
             |&nbsp;
             =env.t('useCostume')
         li.customize-menu(ng-if='user.preferences.costume')
```

but no cigar. Wonder why the others are working..

**Comment by DrTall** [comment]
FYI I am not able to tick it (mine is unticked but I cannot tick it).

**Comment by paglias** [comment]
@lefnire it seems the ng-model change is triggered before the ng-click, so the value is already changed and placing a ! in front of it returns it to the original value. It's fixed here https://github.com/HabitRPG/habitrpg/commit/43fa461a67ddea2125def4a0e517af081eab90ac but I wonder if something else is affected, feel free to revert

**Comment by paglias** [comment]
@lefnire in other places we use ng-change instead of click

**Comment by paglias** [comment]
fixed correctly with https://github.com/HabitRPG/habitrpg/commit/c0a3fc887a125341ebaea8085152a101cc5c895b
