### ISSUE TITLE
November Items not rewarded to valid subscriber

### ISSUE THREAD

**Issue by iamchapo** [HabitRPG/habitica#4275]
Not sure what else I can say to this issue. My box was empty! Very sad. Please help!

id: a95c615b-2484-4dd1-8219-9f313324c9da

**Comment by Alys** [comment]
Reload the Market page. Click on the Mystery box again, twice. Reload the Equipment page. Do they appear now?

**Comment by iamchapo** [comment]
They do! `scratches head in mystified wonder`

**Comment by Alys** [comment]
Good to hear. Any time anything a bit odd happens in HabitRPG, it's always worth trying a reload.

**Comment by iamchapo** [comment]
Thanks Alys. Fabulous responsiveness, glad I'm a subscriber!
