### ISSUE TITLE
Add Icons to Skills

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4276]
Some of the excellent artists on the pixel art board have created icons for all of the skills! They can be found attached to the Trello card linked below :) They just need to be implemented.

https://trello.com/c/uxl17rXM/10-icons-emoji

Let me know if you have any questions about them!
##

**Comment by SabreCat** [comment]
Nifty! I may take a crack at this...

**Comment by lemoness** [comment]
:D :D

**Comment by crookedneighbor** [comment]
Love this.

**Comment by lemoness** [comment]
Would this be a good task for an Aspiring Coder?

**Comment by crookedneighbor** [comment]
I don't think this is entry-level, maybe a step or two beyond that. Do you want this done soon?

**Comment by lemoness** [comment]
Nah, not high-prioirty - was just going through the art trello and found
them again.

**Comment by MathWhiz** [comment]
I can try working on this!

**Comment by librarianmage** [comment]
I can try working on this @Alys !

**Comment by Alys** [comment]
@MathWhiz Great! Thank you! Comment here if you run into trouble or want advice about anything.

**Comment by librarianmage** [comment]
Ok! Will do!

**Comment by librarianmage** [comment]
@Alys, where do you think I should put the images?

**Comment by Alys** [comment]
I guess like in the screenshot below for consistency, but if you come across anything that makes that seem like a bad idea (e.g., if the images are too large), tell us.

![screen shot 2016-03-06 at 12 58 06 pm](https://cloud.githubusercontent.com/assets/1495809/13552029/31f2d360-e39b-11e5-9620-9703c13c0030.png)

**Comment by librarianmage** [comment]
@Alys Thanks! Where in the folder structure should I put them?

**Comment by Alys** [comment]
I'm thinking either `common/img/sprites/spritesmith/misc/` where the Snowball, etc images are, or a new subdirectory under `common/img/sprites/spritesmith` specifically for the Skills images. The misc directory might get a bit large if we keep putting everything in there, and there'll be 16 skills images, so I think it's worth having them in their own directory.

However, hold off on this for a day to see if others disagree. Or if you prefer, go ahead with a new directory now, if you don't mind moving the images later if needed.

**Comment by librarianmage** [comment]
Ok! I will wait.

**Comment by lemoness** [comment]
Excited to see that someone is working on this! It will be nice to get this
art in the game.

**Comment by librarianmage** [comment]
@Alys @lemoness Can I rename the images to make them easier to use?

**Comment by Alys** [comment]
Yes, especially if it introduces consistency with other images in github and/or consistency between the image name and the skill name.

**Comment by librarianmage** [comment]
Ok!

**Comment by librarianmage** [comment]
@Alys Where do I find the keys for the Skills?

**Comment by librarianmage** [comment]
@Alys nevermind, I found them at https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content/spells.js

**Comment by mandyzhou** [comment]
@Alys Re: the screenshot, would it make more sense to put the images directly to the left of the skill names in the white shaded areas instead of the grey shaded areas? Judging by the way Rewards are currently displayed (see below for reference), the images in the grey shaded areas should be related to currency (e.g., GP or MP), while the images in the white shaded areas should show the items/skills themselves.

![untitled](https://cloud.githubusercontent.com/assets/279805/13996720/5ece5be4-f105-11e5-8d2e-db3caf5eb1a6.png)

**Comment by librarianmage** [comment]
@mandyzhou I think that is how I am currently planning on implementing this.

**Comment by Alys** [comment]
@mandyzhou Yes, good point.
