### ISSUE TITLE
Share Avatar options are intrusive

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4277]
The ability to share one's HabitRPG avatar is a clever addition! It's a good way to spread the word about the site and celebrate one's accomplishments. However, I'm finding that it's in my face a little too often.

![2014-11-25 14_56_31-clipboard](https://cloud.githubusercontent.com/assets/4501321/5191368/482d8934-74b3-11e4-8afd-6264a9d8cbf1.png)
<sub>All I want is to click my avatar to flip screens! _grrblmrgrysnarklecheeses_</sub>

Several times a session, I accidentally trip the mouseover, getting the share options dropdown, and need to waggle the mouse around a bit to get it to go away. Given that sharing one's avatar is not an everyday kind of action in most cases, this is more annoying than helpful.

Suggestions:
- Only present the dropdown on click of the "Share" button, not on mouseover.
- Move the Share feature someplace less prominent (maybe under the User menu?).
##

**Comment by lefnire** [comment]
Another possibility: explore some of the other share options, I find addthis a bit clunky (albeit functional, which is why I did it). One alternative I know of is [sharethis](http://www.sharethis.com/). Though definitely down with the "on click" suggestion, could someone poke around to see if there's such an option in [addthis](http://www.addthis.com/)?

**Comment by aedunn6** [comment]
Agree. I try to click on backgrounds, and the share menu pops up _through_ the dropdown!
![screen shot 2014-12-02 at 10 14 31 pm](https://cloud.githubusercontent.com/assets/6609895/5276213/892dbb48-7a71-11e4-8237-abb29cf30bbb.png)

**Comment by SabreCat** [comment]
In the meantime, users of browser extensions for blocking intrusive elements like this can nail it with a filter on the `atm-i` class of `div`.

**Comment by Alys** [comment]
Try installing this and then modify it for the Share icon instead of the
Level: http://habitrpg.wikia.com/wiki/Hide_Level_Numbers

**Comment by benmanley** [comment]
This is the code to disable hover, but I’m not sure where to put it: 

``` js
var addthis_config = {
    ui_click: true 
}
```

[addthis documentation](http://support.addthis.com/customer/portal/articles/381243-menu-offset-delay#hover)

Also, if the share button stays inside the herobox, I would prefer if it was in the bottom left corner as it currently obscures longer avatar names.

![share](https://cloud.githubusercontent.com/assets/3317594/5413064/e2c13658-820a-11e4-911c-01c9183328ca.png)

Any objections?

**Comment by crookedneighbor** [comment]
@benblank it goes [here](https://github.com/HabitRPG/habitrpg/blob/114cbe2760dd14fb6e078a79b3a6febe414b76fe/public/js/controllers/footerCtrl.js#L44-L49)

That's fine with me, and putting it at the bottom left also makes me less likely to trigger it accidentally.

**Comment by benmanley** [comment]
Thanks @crookedneighbor.

I’ve gone for it and committed a fix disabling hover (45d30ffef56cdec74849448195e9cca02af58d7d) and moving the share button to the bottom left (0943a229ec5cbb976e204ec7ec4641b138aea39b) . I've left this issue open as there’s still discussion to be had about whether the sharing button should be in the avatar box.

PS I’m @benmanley not benblank, just so we don’t pester him any more ;-)

**Comment by crookedneighbor** [comment]
Hah. Whoops. My fingers knew who you were, but my eyes and the keyboard apparently did not.

**Comment by crookedneighbor** [comment]
@benmanley Just rebased off your commits, and I noticed that now that it requires a click to activate, it's also activating the normal click action on the avatar to take the user to the profile page (or the tasks page if already on the profile page).

I don't think that's a big deal, but it was unexpected.

**Comment by benmanley** [comment]
Yeah. I noticed that. This was already the behaviour when you clicked. It needs sorting out somehow but I figured it was less irritating than the hover problem.

**Comment by crookedneighbor** [comment]
Oh, it's definitely much better.

**Comment by librarianmage** [comment]
@crookedneighbor Has this been disabled?

**Comment by SabreCat** [comment]
@MathWhiz It got moved to a much less obnoxious position and made to pop out only on click. I think this is solved!
