### ISSUE TITLE
can't click on food (e.g., fish) to feed pets

### ISSUE THREAD

**Issue by annabarnett** [HabitRPG/habitica#4278]
I have a fish in my inventory, but on the Pets page I can't click on it because the text balloon associated with it is placed incorrectly, such that it covers the fish. Mousing over the fish brings up the balloon and makes the fish impossible to click. (The balloon also flickers on and off unless I mouse in just the right spot.)

Account name: peachybetts

**Comment by Alys** [comment]
Confirmed on Chrome (recent version, on MacOS 10.6)

**Comment by JennaMalkin** [comment]
I have the same problem - is the fish in the right column of your food items? 

### Always feeding from the left seems to allay the hover problem.

_edited by admin to highlight the useful tip!_

**Comment by annabarnett** [comment]
Yes, I'm using Chrome and this happens in the right column. I don't want to feed from the left because the food on the left is not preferred by any of the pets I am feeding.

**Comment by annabarnett** [comment]
I just tried Safari and had the same problem.

**Comment by annabarnett** [comment]
Thanks for the fix. I decided to feed from the left after all, so I will have to wait to test this. 

I noticed that this popover issue is also happening with items in the two right-hand columns in the Market.

**Comment by lefnire** [comment]
good newbie dev task for anyone willing, see above commit for `popover-placement` (it may vary per item depending on it's location in the window)
