### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by safarijacksa** [HabitRPG/habitica#428]
Could we have maybe a small circle with a question mark in so that users can hover over it and get some help with regards to the different box's (to-do, daily, rewards etc).

**Comment by lefnire** [comment]
Added for you: [trello](https://trello.com/card/question-mark-with-help-information/50e5d3684fe3a7266b0036d6/168) - we'll need this

**Comment by StanLindsey** [comment]
Yeah we talked a little about this last night, thanks for reminding us! Closing for housekeeping.
