### ISSUE TITLE
Cannot GET

### ISSUE THREAD

**Issue by SoonerDVM** [HabitRPG/habitica#4283]
For the last couple days, I've been getting this message: Cannot GET /options/inventory/pets 

Not just for pets. I've gotten it for almost any tab I try to use. It makes things pretty much unusable. 

Today I gave up an opened it in a different browser. Seems to work ok there.
I normally use Firefox, which is where I'm seeing the problem. It's working (so far) in Chrome.

**Comment by paglias** [comment]
Can you try reloading the main page?
Il 26/nov/2014 16:49 "SoonerDVM" notifications@github.com ha scritto:

**Comment by SoonerDVM** [comment]
Doesn't help. 

Reload - no
Close the tab and open a new one - no
Close the browser and reopen - no
Reboot the entire computer - no

**Comment by paglias** [comment]
Mmm the problem is that links should have a # in front of them like
/#/options...

In the meantime if you add it manually it will work
Il 26/nov/2014 16:53 "SoonerDVM" notifications@github.com ha scritto:

**Comment by SoonerDVM** [comment]
What would I be adding the /#/ to? The URL?

**Comment by SoonerDVM** [comment]
Ok. Tried that. It works.

**Comment by SoonerDVM** [comment]
I was just watching the URL - it started out with the /#/ in the URL, then it changed and /#/ wasn't in it any longer.

**Comment by paglias** [comment]
That's really strange. Which version of chrome are you using? Also,do you
have any extension that may cause this?
Il 26/nov/2014 20:02 "SoonerDVM" notifications@github.com ha scritto:

**Comment by paglias** [comment]
Ok it seems that the href attribute points to a URL without the # but then clicking it opens the right one. I suppose if this is due to some upgrade of angular-ui-router. @lefnire?

**Comment by paglias** [comment]
It makes impossible to bookmark from a link or to open in another page

**Comment by SoonerDVM** [comment]
It's working fine on Chrome. The problem is occurring on Firefox. I'm using Firefox 33.1.

**Comment by paglias** [comment]
Ok, cannot replicate on Firefox but we've had some other report like this and the behavior for me it's like on chrome: the href point to the url without the hash which is then added on click.

**Comment by paglias** [comment]
Reported here https://github.com/angular-ui/ui-router/issues/1588

**Comment by paglias** [comment]
@lefnire we need to upgrade to angular-ui-router 0.2.12 or above to fix this but we're using a custom build of it right now https://github.com/HabitRPG/ui-router/commits/habitrpg 

It seems to be stick to 0.2.0 while the most current one is 0.2.13

**Comment by paglias** [comment]
@lefnire pushed an hotfix here https://github.com/HabitRPG/ui-router/commit/f1c08f1d11030297693c8b35a9727e3ade2ffe5d but we need to upgrade

**Comment by lefnire** [comment]
ohh, I think i did that because there was a certain commit where if you switch to a new tab, it would scroll weird (like, maintain scroll position rather that going to the top or something). I'm sure that's since been fixed, that was forever ago - we can probably upgrade

**Comment by paglias** [comment]
@lefnire that "we need to upgrade" was because there have been a lot of bug fixes since then but we can stick to the current version if we want :) I backported the fix so it should be ok now

**Comment by lefnire** [comment]
I say let's upgrade. it was a small issue back then, let's just do it

**Comment by lefnire** [comment]
I'm pushign https://github.com/HabitRPG/habitrpg/commit/1c70a5bad5f37bc0901b03fe78830e480a033020 to [beta](https://beta.habitrpg.com) now. The thing to keep an eye out for is navigating challenges. I remember now, it was something about clicking a challenge from the party page doesn't bring you to the scroll location of the challenge - something like that. But we can figure something else out for that, it's not super important - better to have the fixes angular-ui-router provides

**Comment by paglias** [comment]
@lefnire tried with a challenge from tavern it scrolls to the right position

**Comment by lefnire** [comment]
awesome. Yeah, i hate having custom forks - really makes me nervous. For anything custom in package/bower.json & anyone wants to move back to the original, ping me & I'll tell which specific issues I was trying to skirt / if we're good to move
