### ISSUE TITLE
[Visual] gold price for reward taking 2 lines with 3 digit numbers

### ISSUE THREAD

**Issue by snouz** [HabitRPG/habitica#4285]
I couldn't find any related thread. Here it is in task page

http://i.imgur.com/8ZGr6PT.png

**Comment by Alys** [comment]
Hi @snouz . It's been reported here: https://github.com/HabitRPG/habitrpg/issues/1993. If you'd like email notifications of updates, there's a "subscribe" button in the right-hand column.
