### ISSUE TITLE
Using Burst of Flames does not trigger level up.

### ISSUE THREAD

**Issue by Beanow** [HabitRPG/habitica#4289]
Using the Burst of Flame skill caused my XP to exceed my leveling requirement, but did not trigger the level up even after refreshing.
![Proof](http://ss.oscp.info/2014-11-27_16-51-16.png)

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2143
Please see that for a solution and to track progress of the fix for this.
