### ISSUE TITLE
Running locally results in hang when clicking play

### ISSUE THREAD

**Issue by tmas** [HabitRPG/habitica#429]
I thought I'd try and contribute to the codebase since I had some spare time on my hands, so I whipped up a quick Ubuntu Server install on proxmox to host a local instance of habit to muck around in. I followed all of the instructions under running locally, but somewhere along the lines something got messed up and I can't get past the splash screen. I get the full splash screen with the logo and everything, not the server overloaded one. Clicking play hangs for around 5 minutes and then fails with error 324 (the server closed the connection without sending any data). I'm not sure if this is an incompatibility with Ubuntu, a shortcoming in the install instructions, or just me being stupid.

**Comment by tmas** [comment]
I originally tried running habit without setting the facebook-related environment variables, but after creating a facebook application and filling in those values it still doesn't work.

**Comment by tmas** [comment]
Alright, I don't know how, but I'm making a bit of progress. I've gone from not loading at all to a quick flash of the site before a white screen and errors in the console. The error is as follows:
![error](https://f.cloud.github.com/assets/271652/169735/7e78ca74-7a34-11e2-93a8-3f4ea88a034c.png)

This repeats each time I try to load the page.

**Comment by lefnire** [comment]
I've never seen that error before, unfortunately - it looks like you have everything setup properly, otherwise it would complain specifically about env var -related issues.  It might be Racer's not checking out from git, on the #habitrpg branch properly. Let me come back to this in a bit

**Comment by lefnire** [comment]
Ah, i'm able to replicate. Diagnosing.

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/commit/daac7f424fce8f35a402cb2eafcc59a8d4a1df36 introduced the bug

**Comment by tmas** [comment]
Nice to see a critical bug that doesn't affect the main site :P

**Comment by lefnire** [comment]
_ahem_ don't, uh.. let's just say most our users are returning users (it's only effecting if no established sessions). 

Do a git pull & try again. If no cigar, take a look at the commit I pushed to get a gist of where the issue lies.

**Comment by tmas** [comment]
Well, the old issue is gone but a new one has taken its place.
![error](https://f.cloud.github.com/assets/271652/169921/e73c3026-7a40-11e2-8e04-fac9d2b73f5b.png)

**Comment by lefnire** [comment]
npm install

**Comment by tmas** [comment]
Ahh of course. Ran that and the old problem returned. I'll take a look at the code, but I don't actually know anything about derby as of yet so I don't think I'll be of much use.

**Comment by lefnire** [comment]
this shoul be fixed, re-open otherwise (git pull and all that)

**Comment by meredithcat** [comment]
I'm still getting the socket hang up error, even after pulling from master. Thoughts?

**Comment by tmas** [comment]
Socket hang up still happens for me as well, but everything seems to run normally.

**Comment by meredithcat** [comment]
Definitely not running normally for me. I'm getting a brief flash of the site, followed by a white screen.

**Comment by tmas** [comment]
Odd. I guess I'll reopen the issue then.
EDIT: Whoops, looks like I can't reopen this. Hopefully @lefnire sees it.

**Comment by meredithcat** [comment]
I tried a few things and somehow managed to break something else (yes, I'm a noob). I'll try again later this week when I have more time to work on it.

**Comment by tmas** [comment]
What OS are you running this on? I'll see if I can at least reproduce the issue. Are you getting any other errors in the console?

**Comment by meredithcat** [comment]
I'm running on Windows 8. I'm pretty sure my error looked identical to the one you posted (with "socket hang up" and "ECONNREFUSED").

**Comment by tmas** [comment]
Hmm, that's weird. I just installed on windows 8 today and it works fine for me. So the socket hang up was the only error you got?

**Comment by meredithcat** [comment]
Ok, now I am experiencing a new and (I think) completely unrelated error. I think I messed something up while trying to fix the previous one. Sorry if this is the wrong place to be posting it. It looks like I'm missing all of the files from the bootstrap, bootstrap-datepicker, and other folders in public/vendor. I can see them on GitHub, but even after resetting my repo they're still not there. Not really sure what happened or how to fix it, as it wasn't happening before.

![image](https://f.cloud.github.com/assets/351124/190675/7b713862-7f06-11e2-982e-f612cb28787c.png)

**Comment by tmas** [comment]
Wow, how convenient. I ran into this earlier, so I can actually tell you how to solve it. It looks like git doesn't checkout other repositories that have been added when running git clone --recursive under the windows command prompt, which leaves all the folders under public/vendor empty. The solution is to install the windows explorer extension and right click in the folder you want to clone the repo into, then select "Git Bash Here" and enter the command.

**Comment by tmas** [comment]
Hopefully the issue magically disappears after doing this, but if it doesn't give me a screenshot of all the errors you're getting and I'll see if I can work out what's causing them.

**Comment by meredithcat** [comment]
Yay, looks like it's fixed now. I'm still getting the socket hang up error, but I'm now getting an actual site rather than a blank page. However, there are still a few more issues:

(1) When running npm install, I get: 
![npm install](https://f.cloud.github.com/assets/351124/191237/e0ebbc54-7f2d-11e2-8e34-a276473d8cd7.png)

I tried installing the Windows SDK and am still getting the error. I'm not sure if it's important though.

(2) The site looks different than the live site - namely, the task boxes are vertically larger:
![running habitrpg locally](https://f.cloud.github.com/assets/351124/191254/5be9993a-7f2e-11e2-8bb4-d3fc6636ec49.png)

I'm getting so close! Have you encountered this before, or do you know of a fix?

**Comment by tmas** [comment]
I've never gotten the new error before, but i have gotten the tall boxes issues (#502). It seems to be windows-specific, and I haven't found a way to fix it. It probably has something to do with how git and windows handle newlines.

**Comment by meredithcat** [comment]
Thanks. I can only run on windows, so it would be nice to be able to fix the tall boxes issue. Other than that, it looks like I can run normally.

**Comment by tmas** [comment]
I'll try looking into it at some point, but I may not have time until this weekend.

**Comment by PhilipHow** [comment]
Uh, this may be a stupid question. How did you get it running on windows? I couldn't figure out how to specify the habitrpg environment variables.

**Comment by tmas** [comment]
In windows, go to Start > Control Panel > System and Security > System. Then click the Advanced system settings link in the left sidebar. From here, choose the Advanced tab and click Environment Variables. You can add each individual variable under user and habit will run correctly.

**Comment by lefnire** [comment]
copy `config.example.json` to `config.json` and edit all those variables (i'll add that to the wiki)

**Comment by toebu** [comment]
I didn't follow the discussion exactly, but I sometimes had the 'ECONNREFUSED' error when I had a connection.sid cookie set in the browser for a user that I deleted in the database. So make sure you also clear the cookies when you have this problem.

**Comment by lefnire** [comment]
I updated the [Wiki](https://github.com/lefnire/habitrpg/wiki/Running-Locally) with new instructions that should make things much easier. Try starting from scratch by dropping your mongo `habitrpg` database and running the new instructions.

The socket hangup issue is vexing me, I've never seen that before and don't know how to approach it. I dare say, running Derby on windows has a problematic history, I'd recommend using an Ubuntu virtual machine if you can. If I can think of anything, I'll chime in

**Comment by lefnire** [comment]
If anyone's experiencing `Emfile` error, check out http://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux

**Comment by lefnire** [comment]
Woo, getting it consistently on local myself. Now I feel y'all's pain :)

```
Error: EMFILE, too many open files '/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/lefnire'
    at Object.fs.readdirSync (fs.js:500:18)
    at files (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/derby/lib/files.js:528:6)
    at Object.watch (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/derby/lib/files.js:276:3)
    at addWatches (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/derby/lib/refresh.server.js:103:9)
    at Socket.<anonymous> (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/derby/lib/refresh.server.js:68:7)
    at Socket.EventEmitter.emit [as $emit] (events.js:96:17)
    at SocketNamespace.handlePacket (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/racer/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/racer/node_modules/socket.io/lib/manager.js:487:38)
    at XHRPolling.Transport.onMessage (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/racer/node_modules/socket.io/lib/transport.js:387:20)
    at XHRPolling.HTTPTransport.onData (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/racer/node_modules/socket.io/lib/transports/http.js:99:10)
    at IncomingMessage.HTTPTransport.handleRequest.req.on.buffer (/Users/lefnire/Dropbox/Sites/personal/habitrpg/modules/racer/node_modules/socket.io/lib/transports/http.js:69:12)
    at IncomingMessage.EventEmitter.emit (events.js:90:17)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socket.ondata (http.js:1703:22)
    at TCP.onread (net.js:403:27)

module.js:340
    throw err;
    ^
Error: Cannot find module 'derby-auth/node_modules/nodemailer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at sendEmail (/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/lefnire/server.js:39:26)
    at process.<anonymous> (/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/lefnire/server.js:63:5)
    at process.EventEmitter.emit (events.js:123:20)
```

**Comment by lefnire** [comment]
more info - it looks like it's the file-watching functionality trying to account for all the files in /public/vendor, which previously was just individual vendor js files, but now is entire submodule repositories. see https://gist.github.com/switz/b38674b3b5cff48fc237 for more info. Possible solutions:
- `ulimit` trick
- turn off file-watching
- slim down the repositories we're pulling into public/vendor

**Comment by wizonesolutions** [comment]
Easy workaround while we wait:

Run server.js with:

`{ ulimit -n 4096; node server.js; }`

Real-time was broken for me until I stopped the EMFILE stuff from happening.

**Comment by quimnuss** [comment]
Hi!
I'm trying to make it run locally as well. Everything loads fine but I'm unable to register a user, the register button is greyed out.
Any hints?
![Captura de pantalla 2013-04-28 a les 11 54 48 AM](https://f.cloud.github.com/assets/4179721/435566/c83cd39a-afe9-11e2-9504-4e31d0e43f2f.png)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
