### ISSUE TITLE
Cannot Send Private Message From Party Screen

### ISSUE THREAD

**Issue by emanaton** [HabitRPG/habitica#4290]
I can send messages from the message icons (i.e. next to people's messages) in the Tavern, but not in the Party. When I click on the send-message-icon next to Ceallaigh's name in the Party screen, I get an error message of "User not found" in the pop-up blue boxes, and the title of the message box reads "Private message to" (i.e. without her name included there). Typing a message and hitting Send results in another "User not found" pop-up _and_ one that claims "Message sent". When @Ceallaigh attempts to do the same to me, she gets the exact same result.

Of note, she is able to send me a private message by clicking on the send-message-icon next to my name in the Tavern, and I'm able to respond to that. Also, I was able to send a message to @Alys via the Tavern.

My (@emanaton) ID is: 0ac8f431-9915-4767-9857-56b9c9e911f7

The @Ceallaigh ID is: a76d68a7-8389-4e46-ade1-0491fcd237d0

Group ID: 1b2065bc-2cbf-4eb1-a87f-7a3d13df6b19

The OS in use is Kubuntu. The browsers this issue has been replicated on are:
- Chromium; Version 37.0.2062.120 Ubuntu 14.04 (281580) (64-bit)
- Firefox; 33.0 Mozilla Firefox for Ubuntu canonical - 1.0
  (Both browsers have minimal plugins)

**Comment by Alys** [comment]
@emanaton : I don't suppose this issue is relevant, is it? https://github.com/HabitRPG/habitrpg/issues/4292

Are you clicking on the envelope icon from one of the red system messages?

**Comment by emanaton** [comment]
@Alys: BOOM! You nailed it. I just made a test comment message to the group, and _that_ responds as expected. Excellent catch. I'm closing this ticket.
