### ISSUE TITLE
Subscription "Update Card" message is cut off. Convert Stripe Modal to have translatable strings.

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4296]
On the [Subscription page](https://habitrpg.com/#/options/settings/subscription), when you click on the
"Update Card" button, you see a screen that contains the message "Update the card to be charged for your subscription", but the latter portion of the message is cut off.

The code that inserts the message is here: https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/rootCtrl.js#L171

A quick-and-dirty fix would be to change the message to "Update the card to be charged." Is it sufficiently obvious that it's the card to be charged for your subscription? I think so. If I don't hear any complaints in the next couple of days, I'll advise people in Aspiring coders that changing the text is sufficient and that this is a good newbie job.

![screen shot 2014-11-29 at 6 18 54 pm](https://cloud.githubusercontent.com/assets/1495809/5233959/efef77d2-77f5-11e4-87b6-e50366aeced6.png)

**Comment by sbreiler** [comment]
I had a quick look at it. It seems Stripe uses its own modal windows which can't be altered that easy.

Totaly agree on shorten the Text. At the same time, could we internationalize the code?

```
description: window.env.t('newNamespaceForPayment?'),
```

Reference: https://github.com/HabitRPG/habitrpg/blob/develop/public/js/services/paymentServices.js#L54

**Comment by crookedneighbor** [comment]
:+1: I agree that it should be translatable.

**Comment by Alys** [comment]
Yes, it's always worth internationalising text.

**Comment by crookedneighbor** [comment]
@sbreiler Did you want to go ahead and do this? Or leave it for some one else?

**Comment by sbreiler** [comment]
Yes, i could do the changes if its not time-critical (it'll take me around two weeks due my workload). Are there guidelines for naming the translation-strings? Should i add a seperate file for the payment?

**Comment by crookedneighbor** [comment]
I believe there's already a [subscriber.json file in habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/subscriber.json), so I would use that. 

If the ticket is still open in two weeks, yes, please do it, but don't be surprised if someone gets to it before you do.

**Comment by sbreiler** [comment]
habitrpg-shared update (first to pull!): https://github.com/HabitRPG/habitrpg-shared/pull/408
habitrpg update: https://github.com/HabitRPG/habitrpg/pull/4404

**Comment by crookedneighbor** [comment]
:+1:
