### ISSUE TITLE
Sharing avatar via Tumblr, Facebook, Twitter sometimes produces generic link instead of profile link

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4297]
Sharing to Tumblr produces a link, but when you click through, it does not actually show the profile - just the static page. This was reported on Safari and I confirmed it on Firefox as well.
##

**Comment by crookedneighbor** [comment]
I've noticed that no matter what service I use, sometimes it works and sometimes it does not. Can't figure out a pattern yet.

**Comment by melissamcewen** [comment]
This happens to me as well for Twitter.

**Comment by lefnire** [comment]
Confirmed. My hunch was it's conflicting with the Addthis code in the footer, since that's the share link & text provided down there. Maybe Addthis can't be used twice in the same page or such. However, removing the footer code entirely doesn't fix the issue (at least not on local). Hmmm..

**Comment by lefnire** [comment]
bumping prio

**Comment by Alys** [comment]
See also https://github.com/HabitRPG/habitrpg/issues/4997 - a different issue that results in sharing links never working. We should fix that one before working on this "sometimes" bug.

**Comment by paglias** [comment]
is this still an issue?

**Comment by lemoness** [comment]
Yes, I believe it is, at least for Tumblr.

**Comment by librarianmage** [comment]
IIRC, the method of sharing avatars, etc, is changing, so should this be closed?
