### ISSUE TITLE
Feature request: Toggle for progress view

### ISSUE THREAD

**Issue by gxbag** [HabitRPG/habitica#4298]
Hi

Since I have many items in my Habits list I'd like to have a toggle to view the progress of all of them at once - a button to switch from progress view to normal view for all habits.
##

**Comment by crookedneighbor** [comment]
This could be a [setting here](https://habitrpg.com/#/options/settings/settings) that lets you toggle whether or not you want the progress button to toggle a single habit or all habits. 

The problem with the all habits option is that, for those with many habits, the particular one the user wants to look at might get buried lower on the screen as all of the habits expand at once, so there might need to be some scroll-to script in place as well to make sure the correct one is in view. 

So, the question is, is it worth it? Or will the scrolling cause more trouble than it helps?

**Comment by lemoness** [comment]
We're not currently planning to implement this feature request, but if we reconsider it in the future, we'll open a new ticket with the designs.
