### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lothlorienwoods** [HabitRPG/habitica#4300]
Every time I check off a task it says eternal server error please check chrome console for more details. It says this no matter what browser I use on the PC and IPad and on the app too. It will give me the rewards for the task but if I refresh it takes the rewards away. It has been like this since the  middle of the week. I have died 4 days in a row because of this. I check into the inn, but refresh and I am not checked in any more. This has become extremely frustrating.

**Comment by Alys** [comment]
We'll need to know your unique User ID - there's instructions for finding out what it is at https://github.com/HabitRPG/habitrpg/issues/2760

**Comment by lothlorienwoods** [comment]
e8195b11-320e-40fc-9431-085882ec5a1c

**Comment by paglias** [comment]
@lothlorienwoods also, after getting the error on the browser you should open the console and copy anything you see there.

If you use Google Chrome you can open it with CTRL+Shift+J

**Comment by lothlorienwoods** [comment]
I just think it is weird that other on other browsers it says check chrome
console.

**Comment by paglias** [comment]
@lothlorienwoods yes it's a deafult message because most devs use Google Chrome. Which browser do you use?

**Comment by lothlorienwoods** [comment]
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not
dots-per-physical-inch, so does not correspond to the actual 'dpi' of a
screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5),
(min-resolution: 144dpi)
ping:1 Given URL is not allowed by the Application configuration.: One or
more of the given URLs is not allowed by the App's settings.  It must match
the Website URL or Canvas URL, or the domain must be a subdomain of one of
the App's domains.
https://habitrpg.com/api/v2/user/batch-update?_v=16529&data=1417358428791&siteVersion=1
Failed to load resource: the server responded with a status of 500
(Internal Server Error)
app-1d500d68.js:27 Object
https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=medium&hl=e…_1417358394216&parent=https%3A%2F%2Fhabitrpg.com&pfname=&rpctoken=13971725
Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/plugins/like.php?action=like&app_id=17252516279391…=en_US&ref=.VHsr8kr5RnM.like&sdk=joey&send=false&show_faces=false&width=90
Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habi…7%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey
Failed to load resource: net::ERR_CACHE_MISS

On Sun, Nov 30, 2014 at 9:28 AM, Matteo Pagliazzi notifications@github.com
wrote:

> @lothlorienwoods https://github.com/lothlorienwoods yes it's a deafult
> message because most devs use Google Chrome. Which browser do you use?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4300#issuecomment-64986937.

## 

"I cant carry it for you but I can carry you"

**Comment by paglias** [comment]
Ok, next to "Failed to load resource: the server responded with a status of 500
(Internal Server Error)
app-1d500d68.js:27 Object
" there should be an arrow which when clicked expand the error giving
more informations, can you try?

2014-11-30 15:44 GMT+01:00, lothlorienwoods notifications@github.com:

> Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not
> dots-per-physical-inch, so does not correspond to the actual 'dpi' of a
> screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5),
> (min-resolution: 144dpi)
> ping:1 Given URL is not allowed by the Application configuration.: One or
> more of the given URLs is not allowed by the App's settings.  It must match
> the Website URL or Canvas URL, or the domain must be a subdomain of one of
> the App's domains.
> https://habitrpg.com/api/v2/user/batch-update?_v=16529&data=1417358428791&siteVersion=1
> Failed to load resource: the server responded with a status of 500
> (Internal Server Error)
> app-1d500d68.js:27 Object
> https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=medium&hl=e…_1417358394216&parent=https%3A%2F%2Fhabitrpg.com&pfname=&rpctoken=13971725
> Failed to load resource: net::ERR_CACHE_MISS
> https://www.facebook.com/plugins/like.php?action=like&app_id=17252516279391…=en_US&ref=.VHsr8kr5RnM.like&sdk=joey&send=false&show_faces=false&width=90
> Failed to load resource: net::ERR_CACHE_MISS
> https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habi…7%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey
> Failed to load resource: net::ERR_CACHE_MISS
> 
> On Sun, Nov 30, 2014 at 9:28 AM, Matteo Pagliazzi
> notifications@github.com
> wrote:
> 
> > @lothlorienwoods https://github.com/lothlorienwoods yes it's a deafult
> > message because most devs use Google Chrome. Which browser do you use?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4300#issuecomment-64986937.
> 
> ## 
> 
> "I cant carry it for you but I can carry you"
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4300#issuecomment-64987302

## 

Matteo Pagliazzi - paglias.net

**Comment by lothlorienwoods** [comment]
I will do it later I am not at my pc because I am am working
