### ISSUE TITLE
Streak data on most of my dailies reset, even though I checked them all.

### ISSUE THREAD

**Issue by mzieten** [HabitRPG/habitica#4301]
User ID 1dc83503-33a2-40c7-8631-9ab139685a26

Last night, I checked off all my dailies before heading to be around 1.  I have had my day start set at 2 am for quite some time, and have not had any issues before this.  I have only been logging in from my home computer this week, and have not used the app at all.

This morning, I refreshed, and didn't notice anything weird.  I was out for most of the day, and when I started checking off my dailies for today, I noticed my hit points had decreased significantly.  I'm not currently part of any quests, so this struck me as odd, and I went to look at my dailies, finding that my streaks on many of them had been reset.  It wasn't on all of them, just the longest-running.  

The only change I can see when I do a shift-refresh was that there were some design changes to the UI, but I don't know if that's related.  I know I can recover my streaks using the Streak Reset function on the individual dailies, but I don't really know how many days I had at this point.  So, I'm wondering if there is any way to recover that data, and wondering what happened so that I can prevent it from happening in the future.

**Comment by lemoness** [comment]
Yikes! That sounds like you experienced sync errors. You can read about them and how to avoid them here (scroll down to "How to Minimize Sync Errors"): http://habitrpg.wikia.com/wiki/Sync_Errors

A workaround to help restore your streaks is given here: http://habitrpg.wikia.com/wiki/Streaks#Restore_Streak_Counter

Sorry about this! Let us know if you have any other questions.
