### ISSUE TITLE
Getting damage even though dailies are all checked off

### ISSUE THREAD

**Issue by kisahawklin** [HabitRPG/habitica#4302]
I'm giving damage to my party even though I'm checking off all my dailies. I recently deleted one or two, there was a bug about not deleting properly before, apparently? (A party-mate found it, I can't find it myself.)

**Comment by Alys** [comment]
You are probably experiencing [sync errors](http://habitrpg.wikia.com/wiki/Sync_Errors), which can occur with task deletions, but it's more likely to be with ticking off Dailies. On that page, read at least "How to Minimise Sync Errors" and "Completing most/all Dailies but still losing health and streaks". It will explain what sync errors are and how to minimise their occurrence. If that doesn't start helping from tomorrow, let us know. Also definitely tell us if you have any questions about what's on that page!
