### ISSUE TITLE
Mystery Items Missing

### ISSUE THREAD

**Issue by ArchStanton112814** [HabitRPG/habitica#4304]
Hi-

My ID is:
54b59763-44f2-420e-85da-176a64ab5d79

I am subscribed, but the mystery item doesn't seem to be appearing.  I tried reloading the market page and clicking the box multiple times as was suggested in another post, but that didn't work for me.  Sorry to bug you!

**Comment by Alys** [comment]
pinging @lefnire. This is confirmed - there's no mystery items in the user's `owned` object.

@ArchStanton112814 We'll get this sorted out for you, even if it's not done by the time the Mystery Item becomes unavailable.

**Comment by ArchStanton112814** [comment]
Thanks!  You guys seem pretty awesome, I'm new here, but I'm feeling more productive already!  Keep up the good work!

**Comment by lefnire** [comment]
Oof, whopper! https://github.com/HabitRPG/habitrpg-shared/commit/703451d452330f15f47d16903da8b66b063ed202 . I'm gonna re-run the migration now, so anyone who missed will get their stufff

**Comment by ArchStanton112814** [comment]
I have everything now.  Thank you so much for the fast response!
