### ISSUE TITLE
Cannot purchase a tiger egg

### ISSUE THREAD

**Issue by tuffkiddo** [HabitRPG/habitica#4305]
I was trying to purchase a tiger egg with gems for the past few days, and every time I try to click on it, the dialogue box flashes. I can highlight it, but every time i click it I don't get the standard message "do you want to buy [x]?". I'm using the latest update of google chrome, and I tried this on internet explorer (rip) to no avail. my user id is 401d4a9a-d247-4ff3-baaf-bd885dc2db25 thank you for your help.

**Comment by crookedneighbor** [comment]
#4287 is addressing this issue.

**Comment by crookedneighbor** [comment]
@tuffkiddo In the meantime, resize your window so the tiger egg drops to the next row, that should allow you to purchase it.

**Comment by tuffkiddo** [comment]
It did help! Though when i had my window like this, while I could purchase what I needed, the lion, wolf, and dragon eggs were buggy as well http://i.gyazo.com/f4b9e2eda986f7b0db7ab22d3dfdd904.png

**Comment by crookedneighbor** [comment]
@tuffkiddo Thanks for the screenshot. It's a problem with how the popover interacts with the edge of the screen (hence why it's only affecting the eggs on the far right). 

We're working on it.

**Comment by Alys** [comment]
Fixed in "Market poptop fix" #4287 (link above).

The fix isn't live yet but should be in a day.
