### ISSUE TITLE
Popovers misplaced on right side of screen when element doesn't have room to display the full popover (notably on Market and Pets and rewards column screens)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4307]
This bug came from https://github.com/HabitRPG/habitrpg/pull/4287, which fixed a more severe bug.

On the Market page, most of the popovers are correctly placed, except for the two right-most columns, in which the popovers are positioned too far right and too far up. It's far worse for the quests than for the other items. The same thing happens with the food on the Pets page.

![screen shot 2014-12-01 at 6 09 59 pm](https://cloud.githubusercontent.com/assets/1495809/5242820/c4742c82-7986-11e4-93e5-5cacd8c99ac2.png)

![screen shot 2014-12-01 at 6 10 01 pm](https://cloud.githubusercontent.com/assets/1495809/5242822/c4802708-7986-11e4-875d-39df377a0a7d.png)

![screen shot 2014-12-01 at 6 10 03 pm](https://cloud.githubusercontent.com/assets/1495809/5242821/c47dbacc-7986-11e4-8c32-b629003bf10b.png)

![screen shot 2014-12-01 at 6 10 47 pm](https://cloud.githubusercontent.com/assets/1495809/5242823/c4815eb6-7986-11e4-8ae7-b8fbc8eec334.png)

**Pets page**:

![screen shot 2014-12-01 at 6 09 36 pm](https://cloud.githubusercontent.com/assets/1495809/5242824/c83373c8-7986-11e4-9064-edc6d08ae919.png)
##

**Comment by brightbold** [comment]
This bug is definitely a bigger deal on the quests. On my computer I can't read the full text of any of the quests in the right-most column, because the tops of the popovers (mmm... popovers!) all fall offscreen, even with the selected quest scroll all the way at the bottom of my viewport. 
![quest-popup](https://cloud.githubusercontent.com/assets/405068/5921041/eeecda36-a60e-11e4-8e56-597a978441c0.png)

**Comment by crookedneighbor** [comment]
This PR will help with this: https://github.com/HabitRPG/habitrpg/pull/4585

But it won't solve it completely:

## Good!

![screen shot 2015-01-28 at 2 22 46 pm](https://cloud.githubusercontent.com/assets/2916945/5946191/843886c2-a6f9-11e4-86b9-b6ae25511ca9.png)

## Still not perfect:

![screen shot 2015-01-28 at 2 22 52 pm](https://cloud.githubusercontent.com/assets/2916945/5946194/8a335b24-a6f9-11e4-9401-f46606b586db.png)

**Comment by crookedneighbor** [comment]
@brightbold the specific issue you pointed out will be fixed the next time a deploy to production is made (should be before the 30th).

**Comment by khipkin** [comment]
@Alys Is this still an issue?

**Comment by Alys** [comment]
It sounds fixed and if not, it's covered by this info about a website improvement project: https://github.com/HabitRPG/habitrpg/issues/7799#issuecomment-242433998

( @khipkin Thanks! I'll cover your other questions like this in several hours after I get back from some tourist time. :) )
