### ISSUE TITLE
Task tabs cut off long words

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4308]
The new tasks tabs cut off long words, or allow the words to stretch over the end of the tabs. For example, for Russian:

![c03c1641c690](https://cloud.githubusercontent.com/assets/1495809/5243117/aa15ae42-798b-11e4-8c7a-7c87e004132f.png)

Note that I'm definitely not suggesting a reversion to the previous design. This new design looks SO classy, and the previous one did very ugly wrapping of the tabs when the words were too long. But it would be nice if there were a way to improve the appearance for Russian and for any other languages that might have a similar problem (I'm not sure if there are any others).

For long labels that are made of a few small words, the behaviour is good:

![screen shot 2014-12-01 at 4 48 27 am](https://cloud.githubusercontent.com/assets/1495809/5243147/0733a8c2-798c-11e4-8f37-283426e715f0.png)

I'm wondering if the best fix for this is to hyphenate long words - does Russian use hyphenation to break up long words the way English does, and would that allow the hyphenated word to wrap in the same way that pairs of words wrap?

Alternatively, perhaps different, shorter words could be used for the labels. For Habits, we went with "weak" and "strong" simply because those were the shortest words we thought of. There are other options listed in https://github.com/HabitRPG/habitrpg/pull/4167 and the Russian translation could probably use any of those instead, or similar words, if they were shorter.

Attention:
- @benmanley if you have any thoughts about CSS changes
- any foreign-language speakers who've noticed this problem in their languages and have ideas about wording changes

**Comment by benmanley** [comment]
I’ve fixed by forcing long words to wrap using CSS. 

![filter-wrap](https://cloud.githubusercontent.com/assets/3317594/5246260/84591eb4-795e-11e4-80c0-e0dec781249e.png)

It solves the problem in terms of readability, but it’s not perfect. It will do fine if we also encourage translators to use shorter words if at all possible.
