### ISSUE TITLE
Split personalities

### ISSUE THREAD

**Issue by jcb03e** [HabitRPG/habitica#4309]
ID:
cea9dea2-ac1a-4ab6-a1b4-e077283b2849

Hi there, I use habitrpg on my PC at home and on my PC at work. My account is working normally at home. Recently though, my work one has messed up. It said that I died (which I wasn't even close to dying) and it had me at level 5, when I'm actually over level 20+. All my tasks and gear and pets are gone too. So is this some sort of sync issue?

I use Chrome on both computers. 

Thanks for your help!

-Julia

**Comment by lemoness** [comment]
Hi Julia!

Looks like you've accidentally got a duplicate account! The next time you
see the incorrect one, delete it (Settings > Site > Delete) and then sign
in again. Your correct account should be displayed!

Let us know if that works :)

**Comment by jcb03e** [comment]
So I deleted the wrong account, and now I can't log in at all! Did that
delete both versions? :(

**Comment by lemoness** [comment]
Uh oh - that's certainly not good. Pinging @lefnire and @alys, who have a
deeper knowledge of the tech side than I do.

**Comment by paglias** [comment]
@jcb03e it seems the account with the UUID posted in the issue has been deleted. do you have the UUID of the other one? 

Also, when you deleted it, we might have a backup

**Comment by jcb03e** [comment]
Ok, so my original account works at my home computer but not my work one.
Here's the id; thanks!

c1c391ac-00f9-49a1-9f72-80d11fd5dc23

**Comment by lefnire** [comment]
If the original account works anywhere, then you're still intact. When you
log in with the bad accounts do the deletion again, make sure you are
logged into the account

**Comment by jcb03e** [comment]
So since I log in with my email address, I'm not sure how to bring up the
correct account on my work computer. Is there any way to put in the correct
id before logging in?

**Comment by lefnire** [comment]
c1c391ac-00f9-49a1-9f72-80d11fd5dc23  is a facebook-registered account,
maybe you have one reg'd with FB and the other with uname/password?

**Comment by jcb03e** [comment]
Ohhhh! You're so smart, mystery solved. I deactivated my FB account for a
little while. So once I reactivate it should go back to normal. Hah.

Thanks for your help!
