### ISSUE TITLE
Feature Request: Pivotal Tracker integration

### ISSUE THREAD

**Issue by thewoolleyman** [HabitRPG/habitica#431]
Hi. Kickstarter backer here ;)

I like keeping my TODO list in Tracker, mainly because of the nice iOS app.

If the integration isn't too hard, I might take a shot at a pull request for it.  Any pointers to documentation or code which will show how to implement a TODO list integration are welcome.

Thanks,
-- Chad

**Comment by horusofoz** [comment]
This is currently up for voting on [Trello Card #29](https://trello.com/c/tpQBizSk). Add your vote to help make it a reality.
