### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by becomesaflame** [HabitRPG/habitica#4310]
http://www.isitdownrightnow.com/habitrpg.com.html

The server appears to be down.  Is maintenance happening on it, or is there some other issue?

**Comment by lefnire** [comment]
DNS down, follow https://twitter.com/dnsimple

**Comment by paglias** [comment]
Our domain registrar is currently experiencing a ddos attack. We'll be back
online when it's resolved. You can follow for updates on Twitter
Il 01/dic/2014 21:02 "Spark" notifications@github.com ha scritto:

**Comment by lemoness** [comment]
Okay, @lefnire has created a workaround! You can now use
https://habitrpg.herokuapp.com to access HabitRPG while DNSimple is out :)
IMPORTANT NOTE: use that for checking off tasks only - don’t buy gems or
subscribe, because it may not work correctly!

We’ll post here when DNSimple gets everything fixed normally.

**Comment by j-po** [comment]
I get a 404 when I try to log in on Heroku.

**Comment by deilann** [comment]
I was just redirected to the site proper. Try that Jonathan.

**Comment by lefnire** [comment]
Yes we can you be back online right now, I'll be monitoring DNS for the
next couple hours

**Comment by moeraccoon** [comment]
https://habitrpg.herokuapp.com/
Is not accessible where I live. Odd enough, when the website is up (habitrpg.com I mean) I still can't get to it, I had to use a proxy to open it, I live in Italy if that helps.
Going to sleep now, it'll probably be fine tomorrow if it's just a ddos.

**Comment by paglias** [comment]
@arkindal hi, you always use a proxy to access habitrpg.com from Italy? It shouldn't be necessary, I never had a problem with it

**Comment by moeraccoon** [comment]
@paglias Hi, no I think I explained myself badly. I had to use it only yesterday during the downtime. For some reason when the website wasn't down it was still not reachable from Europe (I asked a friend from Belgium if he could get to it and he couldn't). But now I can get there so I guess everything was fixed.

**Comment by becomesaflame** [comment]
DNSimple is back online as of 8:17 UTC.
