### ISSUE TITLE
Dec 1 blackout deleted daily progress (solved)

### ISSUE THREAD

**Issue by Sylvandyr** [HabitRPG/habitica#4314]
I finished and checked off all of my dailies earlier yesterday, and I was not aware of the access problem at all.  However, it seems that my client-side changes never made it to the server.

Because of this, I have lost my daily streaks and some health and experience (?).  I understand from the information posted about yesterday's blackout that I can fix my health and experience totals.  Fixing the health total is simple enough, but I do not know how much experience I lost (or was it gold? - it flashed too fast for me to see).  I also don't know how to check what my exact streak number for each daily was; I can see my SCORE, but I don't know what the corresponding streak number was, and I don't see any button to let me restore it.  (I also have no idea if I lost some of the points from my to-do list that I checked off yesterday, but I have no way to check for sure; the to-do tasks are all listed in my "completed" box, though, so I think that those, at least, probably worked.)

User ID: 8f57c755-8641-40c2-ac25-57237f560eda
Browser: Firefox 33.1
OS: Windows 8

I don't see any javascript errors in my browser console, but it's probably related to the server crash and me mistakenly thinking that I was communicating with the server when I really wasn't, anyway.

**Comment by Alys** [comment]
I've very sorry about the trouble this has put you to!

You can estimate what your Dailies' streaks were by going to the [HabitRPG User Data Display](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) tool and looking in the Dailies History section. It shows you a chart of the days when you did and did not tick off each Daily. If you count all the blue "V" marks back to the first red "x" mark, then that will be the streak, at least approximately. Click on the "show explanation" link to learn about the chart. You can also use the "Stats and Streaks Backup" section if you'd like to periodically save a record of your streaks (copy the information to a text file, for example).

If your To-Dos are still marked as completed, then it's very likely that you did keep the XP, GP, and MP earned from each of them.

**Comment by Sylvandyr** [comment]
Thank you so much, that fixed everything!

**Comment by lemoness** [comment]
Hi Sylvandyr!

We're very sorry about the hassle. Unfortunately, there is no easy way to
check the exact stats, but you can approximate many of them using the
information in the Data Display Tool (click "Data" in the top bar). You can
read about how to use it to restore streaks here:
http://habitrpg.wikia.com/wiki/Streaks#Restore_Streak_Counter

The experience and gold that you "lost" was actually from the tasks you
completed with didn't log as completed. You can fix the To-Dos and Habits
by simply checking them again. For the Dailies, when you check them off
today, pay attention to how much XP and GP they give you. That's
approximately how much XP/GP you should add!

I hope this helps. Sorry for the hassle!
