### ISSUE TITLE
Cron Runs Too Early

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4315]
We've been getting a lot of reports recently of cron running too early, even when the users say there is no time zone difference. I'm making this ticket to start collecting the reports. 

Before reporting this issue here, please check:
- if you have a Custom Day Start (found on the website under Settings > Site)
- if your device(s) have the correct time on them, since HabitRPG goes by your device's time zone.
##

**Comment by owenblacker** [comment]
I do have a custom day start (0300 local time) and I'm seeing this a lot, though temperamentally -- it occurred yesterday when I logged in around 0100ish, but I was fine just now at 0005.

It appears to be device independent, affecting me in the web app and on Android from time to time. If it helps, my UUID is 12c97e4a-5389-4e82-9c22-6a74562dd9f9

**Comment by owenblacker** [comment]
Fwiw, it's been fine for a good few days. But I died at 0035 last night as a result of not having marked off my dailies, despite supposedly having over 2 hours remaining… :(

**Comment by Alys** [comment]
@owenblacker Are you certain that you died because of your own Dailies and not from damage from the boss quest that you are on? Could you please go to your party page, click "Fetch recent messages" (that part is important) and see if there are any reports of damage from your party members that would account for your death?

**Comment by owenblacker** [comment]
@Alys Aha!

> Ramona Flowers attacks Vice's Shade for 8.3 damage, Vice's Shade attacks party for 37.7 damage.

That'd do it.

Sorry for the mistake!

**Comment by harrislapiroff** [comment]
I have a CDS set for 4, but I noticed my dailies all just reset, even though it's only midnight here in eastern time.

**Comment by Alys** [comment]
@harrislapiroff Did you change your CDS in the past 24 hours? Has the time or timezone on your PC/mobile been changed recently? Are you using two or more PCs or mobile devices that have different timezones or different times?

**Comment by harrislapiroff** [comment]
I changed it a few days ago. I have up to three devices using HabitRPG, but they are all on the same timezone and have not changed recently.

**Comment by harrislapiroff** [comment]
I checked this again tonight and it seems to be working fine now. Not sure what happened last time. Thanks for replying, though!

**Comment by Xiaonasa** [comment]
Currently both my fiance's and my accounts are doing this, and his was just made yesterday Added things last night at about 10:30 for both of us, and they counted towards today, definitely making it kinda hard to keep track. I usually put things in at that time. >< I noticed it also a day or two before on my account.

**Comment by jimbotherisenclown** [comment]
I just had the same problem. I do have a custom cron (6:00AM), but the damage occurred at 11:30PM, and I've had the custom cron for a couple weeks. Though I am in a boss battle, I don't have anyone else in my party to trigger the damage for me. It seemed the damage was triggered by checking the webpage in Chrome on my Android based tablet. The time on that tablet was 11:30, the same as my desktop. My User ID is 5b35f697-071e-49ae-8661-28e146e62e93 .

**Comment by Alys** [comment]
@jimbotherisenclown please check that the time zone on your tablet is identical to that on your desktop. If they are the same, please let us know what it is to help us correlate database timestamps with your report. If they're aren't the same, that would be what caused the early cron.

**Comment by jimbotherisenclown** [comment]
On both devices, the timezone is GMT -0700 (Mountain Time). The tablet's time is about a minute slower than the desktop, upon comparison.

**Comment by Alys** [comment]
Habitica's code has undergone large changes since this was last reported, which means that the code that caused these bugs probably does not exist any more. I'm closing this, but if you notice the same problem happening again, please open a new issue.
