### ISSUE TITLE
Error when opening the Challenges pane in Safari

### ISSUE THREAD

**Issue by JohanSpaedtke** [HabitRPG/habitica#4324]
When I tried to load 

https://habitrpg.com/#/options/groups/challenges

in Safari Version 8.0 (10600.1.25.1) on OSX Yosemite 10.10.1 I got the following error in a little red pop up ballon that slowly faded away

_Please reload, "Error Runner error: Overflow sort stage buffered data usage of 36466904 bytes exceeds internal limit of 33554432 bytes" (see Chrome console for more details)._

I got this a couple of times in a row and while I was getting the error I didn't see the list of created challenges but I saw the green **Create Challenge**-button. My party member didn't have the problem and then a couple of refreshes and approximately 5 min later the error was gone and now I'm seeing the list of challenges and everything seems to work.

I tried looking in the _Error Console_ and this is everything I found there

[Warning] Unexpected CSS token: : (app-c6da1c84.css, line 5, x3)
[Warning] Unexpected CSS token: : (app-c6da1c84.css, line 17, x6)
[Warning] Invalid CSS property declaration at: \* (tweet_button.2dbfc52aff624254c17d0ae518d60e15.en.html, line 1, x3)
[Log] Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. (ping, line 1)

**Comment by paglias** [comment]
@JohanSpaedtke sorry about this, you can follow at #4132
