### ISSUE TITLE
New Gift code issue on jade view

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4325]
@lefnire FYI, just rebased the merge you just made and am getting this: 

![screen shot 2014-12-03 at 5 44 31 pm](https://cloud.githubusercontent.com/assets/2916945/5291134/3809addc-7b14-11e4-9d2f-078995e02dba.png)

Feel free to close this if you're just in the middle of something to fix it.

**Comment by crookedneighbor** [comment]
Oh wait, I didn't rebase habitrpg-shared.

User error.

**Comment by lefnire** [comment]
You testing it, or just wanting to rebase? If testing, email me and I'll shoot you some config.json vars to play with, if not ignore me :)

**Comment by crookedneighbor** [comment]
@lefnire I tried testing it a little, but figured I was missing the necessary config.json vars to do so when it refused to let me gift some gems. 

If you want an extra pair of hands working on this, I'm happy to lend mine.

**Comment by Alys** [comment]
Blade, lefnire is fixing some bugs. I can pass some test info onto you. I'll do it as a message in G+. Incoming in a minute or two.

**Comment by crookedneighbor** [comment]
@Alys I'll look for it and any new commits by @lefnire.

**Comment by lefnire** [comment]
@Alys @crookedneighbor all's well now. the beta errors were due to `req.session.*` size causing heroku to error on "cookie max size exceeded". Just had to slim down what's stored in `req.session`. I'm gonna be pushing to prod in a bit here, wanna get in early so i can have some in front of computer in case users hit issues

**Comment by crookedneighbor** [comment]
@lefnire Awesome. The only problem I experienced was that I was getting "Amount must be within 0 and your current number of gems." randomly when I would input an amount. Couldn't figure out a pattern.

Just rebased and I'm still getting the notice.

![screen shot 2014-12-03 at 7 46 56 pm](https://cloud.githubusercontent.com/assets/2916945/5292271/3934381a-7b25-11e4-89cc-730e4fa6cff4.png)

**Comment by crookedneighbor** [comment]
Seems to be after a certain threshold, it'll go through. For instance, it didn't error at all if I put all the gems in.

**Comment by Alys** [comment]
Doesn't go through for 1 gem or 3 gems, does go through for 4 gems.
Something to do with the $1=4 gems conversion?

**Comment by lefnire** [comment]
Ah, got it - good breakdown! 1a84d01

**Comment by crookedneighbor** [comment]
Once again @Alys saves the day.
