### ISSUE TITLE
Opening Time Traveler page via click on Mystic Hourglass should scroll to top (also other pages, e.g., Pets, Mounts, etc)

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4326]
On my screen and browser, I need to scroll down a bit to see the special items including Mystic Hourglass in the Market. When I then click the Hourglass, it switches me over to the Time Travelers page, but scrolled down the same distance as I was on the Market page. If I go a bit far to start with, I don't see the Travelers at all when I first arrive.

It would be nice if jumping to the Time Travelers page scrolled it to the top so folks don't run into this awkward flow!

<sub>(wooooooooo time travelers)</sub>

UPDATE: See https://github.com/HabitRPG/habitrpg/issues/4326#issuecomment-214595238 for details about other pages this affects.
##

**Comment by crookedneighbor** [comment]
@SabreCat what parameters do you need to fulfill to see the hourglass?

I'm a subscriber and I'm looking in the market and I don't see it.

**Comment by SabreCat** [comment]
You get them for consecutive months of subscription--there's some info in the latest Bailey announcement!

**Comment by Alys** [comment]
If you use the special testing from earlier and gift a subscription for
multiple months, the recipient will see the hourglass

**Comment by crookedneighbor** [comment]
Oh of course, obviously.

**Comment by librarianmage** [comment]
@Alys Is this still needed (I am not a subscriber)?

**Comment by Alys** [comment]
It still happens, although it's not solely with the Time Travellers page. For example, go to the Pets page, scroll part way down, then use the Inventory > Mounts menu item, and you'll be taken to part way down the Mounts page. I imagine there's a way of fixing this that would work in all cases, although I have no idea what the fix would be. :) I'm about to update the title to indicate it's other pages too.

Although... for pets and mounts there's a certain convenience to being able to jump to approximately the same place on each of them (e.g., if you're wanting to equip the same breed for each), but that's probably not as important as having each page you visit starting at the top by default, as it would be on a normal website.

**Comment by librarianmage** [comment]
@Alys Possibly useful: http://www.w3schools.com/jsref/met_win_scrollto.asp

**Comment by librarianmage** [comment]
@Alys I can try this!

**Comment by Ozzystrasza** [comment]
Is this been worked on? If not, I'd like to try it, if it's ok.

**Comment by Ozzystrasza** [comment]
I added `window.scrollTo(0, 0);` to all the controller functions of all states in [app.js](https://github.com/HabitRPG/habitrpg/blob/develop/website/client/js/app.js), and it seems to be working. Tested in all pages, and also tested the page's normal functionalities and nothing seems to be broken.
Is this an acceptable solution?
