### ISSUE TITLE
No gem buying limit

### ISSUE THREAD

**Issue by Paluka7** [HabitRPG/habitica#4327]
With the new month and new feature for long-time subscribers, I decided to buy my monthly gems. I have this habit of just clicking until it says I can't get more, but today, it seemed not to stop. I've been subscribed for 4 months, so I should have a limit of 30 gems. I'm now at 105 gems total, and I'm 100% sure I didn't have 75 before my clicking started. Unfortunatly, I don't remember how much I had before starting...

User ID : ae623702-ded6-4b36-8b6f-1f77107ac8a6
Google Chrome, version 39.0.2171.71 m
Windows 7

**Comment by lefnire** [comment]
could you try now? see if it cuts you off yet?

**Comment by lefnire** [comment]
Do a hard refresh too beforehand

**Comment by Paluka7** [comment]
Cleared cache, did a hard refresh, but I'm still able to buy gems

**Comment by lefnire** [comment]
Fixed in https://github.com/HabitRPG/habitrpg-shared/commit/6ac6f4d476999737dad30c772bb5d2d4a462b6a5, pushing now

**Comment by lefnire** [comment]
try again in 10m, hit me if still issue
