### ISSUE TITLE
checkbox/plus/minus but no accompanying HP/exp/gold change

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#433]
From Twitter:

> Checkbox/plus/minus but no accompanying HP/exp/gold change. Refresh and checks are gone.

This might be a duplicate ticket (god, sorry guys I'm catching up on all this)

**Comment by toddgrotenhuis** [comment]
I see this happening:
GET https://habitrpg.com/img/BrowserQuest/habitrpg_mods/ 403 (Forbidden)

**Comment by lefnire** [comment]
@switz it's a problem after all! Thanks @toddgrotenhuis diagnosing

**Comment by Pandoro** [comment]
This feels related to #427 at least these problems started occurring for me at the same time.

**Comment by unchiujar** [comment]
It has been broken for me in the same way too since this morning (GMT+2) , sometimes it works only for the first click but not for the following ones.

**Comment by wildcate** [comment]
Same here.

**Comment by lefnire** [comment]
ok, let's follow this up on #427
