### ISSUE TITLE
Subscribe without money on PayPal

### ISSUE THREAD

**Issue by Darhaiyo** [HabitRPG/habitica#4331]
ID - ace00d73-a040-4f56-ba30-741e611578ca
Browser - Firefox 33.1.1
OS - Windows 7 Ultimate
Testers gonna test. I found bug with payment system. So I click on Benefits 1 month and choose Paypal as payment system. After confirmation I was redirected to the page of PayPal site, and then received a letter saying that I am a subscriber to HabitRPG and noticed of the creation of a permanent payment from Paypal. 
The problem is that neither PayPal or the credit card tied to Paypal not have 5 dollars. However, in the game store I noticed an opportunity to exchange gold for gems.
That is, in fact system mistakenly took payment from an empty purse and awarded me the status of the subscriber.
I don't want to cheat the game and the developers, so I would be grateful if this problem will solve.
Screenshoots:
http://awesomescreenshot.com/0953yydl43 - HabitRPG mail
http://awesomescreenshot.com/0983yydu97 - Paypal mail
http://awesomescreenshot.com/05b3yye32f - Marketplace
##

**Comment by lefnire** [comment]
Wooooweeeee! On. It. Thanks for the honesty!

**Comment by Darhaiyo** [comment]
You're welcome. Actually even my bank said "You've got no money for this, dude", but game still thinks that all paid.

**Comment by lefnire** [comment]
Ok, it looks like it actually created an account for you on PayPal. I was able to lookup your [recurring account](https://www.evernote.com/shard/s17/sh/c618a5a6-c32a-450d-ad07-cf229733cd51/47465eff537497bf1127e355bc126223) and it doesn't show any problems on it. I _think_ it didn't send an error to our servers because that flag down there saying "Add failed payments to next bill". Probably says "hey, he doesn't have money in the account - but we'll check again next month". I'll need to change that, but at least it's not as critical as I thought

**Comment by Darhaiyo** [comment]
When I try to unsubscribe - I've got this: http://awesomescreenshot.com/04c3yyni81

**Comment by lefnire** [comment]
Investigating

**Comment by Darhaiyo** [comment]
After deleting Recurring payment on Paypal - unsubscribe without problems.

**Comment by Darhaiyo** [comment]
After unsubscribing - still available purchase gems. And further purchases for these gems.
(Is there a chance to delete from my inventory gem-scrolls?)

**Comment by lefnire** [comment]
Un-subscribing will still give you subscription perks until the end of your
billing cycle (eg, 30 days after initiating a 30d plan).

**Comment by crookedneighbor** [comment]
@Darhaiyo Currently, no. There's talks of letting people sell excess scrolls for gold, but it's not decided yet.

**Comment by DrStrangepork** [comment]
Just a thought: I know my PayPal account is set to withdraw funds directly from my checking account if the PayPal balance is $0. Maybe this was succeeding because of a similar configuration to PayPal?

**Comment by TheHollidayInn** [comment]
When testing on Paypal with a balance of 0 I am directed to put in a credit card with the following message: `To complete this payment, add a debit or credit card to your PayPal account. Your card will not be charged unless the transaction amount exceeds your balance.`

Then, we also have IPN set up with the following: `if (['recurring_payment_profile_cancel', 'subscr_cancel'].indexOf(txn_type) === -1) return;`

So, I am assuming we have this case covered. Maybe it doesn't work immediately, but as soon as we receive the IPN notification we should have the subscription cancelled.

**Comment by khipkin** [comment]
@TheHollidayInn Sounds reasonable; maybe close this and re-open if necessary?
