### ISSUE TITLE
Trouble with new 12 month block subscription

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#4332]
Hey! I just saw the new 12 month block subscription option for HabitRPG. I cancelled my current subscription (which was set to pay tomorrow) and tried to pay for a 12 month subscription. For some reason, it's not working for me; after I log into my PayPal account and try to submit the payment, the confirmation page "can't be shown."

I'm a big fan of science, so I tried to make sure everything was working--I tested the $5 1 month subscription option again, thinking that it was paid on the 5th of every month. The subscription went through and paid, so I guess that one works. However, I'm wondering whether I could cancel that payment and find some way to do the $48 12 month subscription instead?
##

**Comment by lefnire** [comment]
UUID?

**Comment by HSalgo** [comment]
57a9ec4a-33d5-49f0-ba1c-291487983290

**Comment by HSalgo** [comment]
I guess it could theoretically be on my PayPal's end, but the $5 subscription went through just fine....

**Comment by HSalgo** [comment]
(I could also wait a few days if you think that would help.)

**Comment by HSalgo** [comment]
Oh! Sorry for the spam, but I forgot to say  I also tried the 12 month subscription with a credit card, and there was no confirmation. The payment didn't go through.

**Comment by lefnire** [comment]
So just to clarify:
1. You were already on 5m (PayPal)
2. Cancelled, tried 12m by (Card) - Failed
3. Re-sub'd on 5m (PayPal)

Sure enough, your account doesn't show `purchased.plan.consecutive.offset` which would equal `12` if you purchased a 12m block sub. Did Card give you an error (any red notifications top-right) or anything? I wonder if it was a mis-entered card # or the sort. (Not that I'm doubting, just debugging). I'm gonna test around some on local to see if I can replicate.

**Comment by HSalgo** [comment]
To clarify:
1. I was already on 1m subscription for 5m (Paypal).
2. Cancelled to try the 12m block subscription.
3. Tried 12m by PayPal repeatedly + failed.
4. Tried 12m by card once + failed.
5. Resubscribed on 1m subscription (Paypal) successfully.
6. Cancelled again to see if the 12m subscription worked.
7. Tried 12m by PayPal again + failed.

Pretty sure I didn't misenter the card #. I can try again, but that doesn't explain the failure with respect to PayPal. Has anyone else had this problem so far?

**Comment by lefnire** [comment]
Right, don't bother with re-enter card for now. Haven't heard this issue
yet, but it's only been up since last night - so you could be the first.
Investigating, thanks for the info

**Comment by HSalgo** [comment]
Bluh, just tried it with the card. It went through, but HabitRPG noted it only as a $5/month subscription. Let me check if I got charged. Sorry for the mess. D:

**Comment by HSalgo** [comment]
I think it worked with the $48 via card ("stripe"). I see the charge on my card statement.

It says, "Recurring $48 each 12 Month(s) (Stripe)," but it also says, "You have 0.94 months of subscription credit." instead of 12.94 (the 0.94 is probably left over from the $5 subscription test I did). The current "Consecutive Subscription" stats are correct.

If you want, I can cancel this later and try the PayPal thing to try to help sort out the problem with you. Not quite sure why everything's been exploding, but I appreciate your help.

**Comment by HSalgo** [comment]
A question that appeared in the tavern: how do gifts, or additional subscription fees, add onto the time that someone has already subscribed? I'm looking to go until February 2016 (it'd get me a last Mystic Hourglass, and would be a responsible time for me to look and see how I'm faring with HabitRPG), and I'm wondering if I could throw in a final $5 on top of everything else once this is all sorted out.

Until then, I'd be glad to serve as guinea pig! If you're willing to go through a bunch of refunds and retries with my card, that is.

**Comment by HSalgo** [comment]
Speaking of which, I don't know how it stacks, since I bought a $5 subscription through PayPal today and just did the $48 subscription via card. .... I'll just wait until you sort things out to figure how long my subscription extends until.

**Comment by HSalgo** [comment]
I think it stacked weirdly--a.k.a. the subscriptions overlapped rather than adding serially--because I was able to buy an extra 50 gems just now, which seems.... wrong. (I'd already previously hit the limit of 30 for the month of December.)

**Comment by Nafoi** [comment]
I might have the same problem: I had a monthly subscription and cancelled it to resubscribe the yearly one.
I had no problem subscribing to the monthly plan a month ago. Now doing it again with the yealy one always gives me the same problem: after the confirmation page on paypal it tells me it should redirect me to habitrpg to finalize the payment. It instead tries to connect to a localhost:3000 page and gives the unable to connect error page. I tried it on firefox and chrome with the same results. Hope this can help...

**Comment by HSalgo** [comment]
Yep! That's the error I was getting.

**Comment by lefnire** [comment]
ohhh oh oh, i know what's going on then. More soon

**Comment by lefnire** [comment]
Ok, pegged the paypal issue: https://github.com/paypal/PayPal-Python-SDK/issues/73#issuecomment-65706866 . The `return_url` & `cancel_url` were set to localhost:3000. It should be resolved now.

@HSalgo you've been a most patient and awesome guinea pig on this. I'm happy to refund anything necessary, [email me](mailto:tyler@habitrpg.com).

**Comment by lefnire** [comment]
Here's how the stacking works:
- Consecutive months: Months you've been sub'd up until now, _plus_ any block subs you purchase in advance. 
- If you cancel a sub, any time left over you have gets put into `dateTerminated` (when your subscription will become active)
- If you re-sub, whatever's in your `dateTerminated` will get added up and put into your `extraMonths` (time credit)

**Comment by HSalgo** [comment]
What happens if you:
1) gift a sub to someone who already has a subscription, or
2) are a doof like me and accidentally double sub?
Do the subscriptions take place concurrently or do they get added onto your "extraMonths" serially?

I ask because I think that I accidentally found a way to activate two subscriptions concurrently--I had a max of 30 gems that I bought on the 1st of this month, and after buying the block subscription, ended up with a cap of an extra 50 gems (instead of an extra 20 gems).

I'd like to clear this up with everyone else first and try to make sure no more problems crop up before I go complainin' about my own silliness. Thanks for your help!

**Comment by Nafoi** [comment]
I can confirm that the paypal subscription now works correctly.

**Comment by lefnire** [comment]
Aint complaining about any silliness here, you're a godsend for investigating this issue and being so willing to play with payments to explore issues! Not a lotta people would be willing to do that in my estimation ;) Thank you, thank you!
1. Give a sub to someone with a sub, it should add to their `extraMonths` (credit). Then, if they cancel in the future it will backport that credit to their `dateTerminated` field so their sub doesn't kick until that far in the future.
2. That indeed is very suspicious, I'll investigate it right now.

**Comment by HSalgo** [comment]
Feel free to examine the dates on my account (you have my UUID); it may make things easier. I was previously subscribed until 12/05/14. Today I resubscribed for 1m, and it got pushed back to 12/30/14. After some bumbling around (all the tests and reattempts and finally using a card instead of PayPal) it now says 1/02/15. I'm... not really sure what it's supposed to say at all.

**Comment by lefnire** [comment]
Oh, you know what happened? Your account shows `plan.consecutive.gemCapExtra=25` (good, the max) and `plan.gemsBought=50` (good, max). When you cancelled and re-sub'd, you cleared your `plan.gemsBought`. Which actually makes sense - if someone pays an additional $5/m (or whichever block), they should get the perk again since it's a full new payment. That make sense?

**Comment by lefnire** [comment]
Let's see...
1. Cancel adds whatever was left on your billing cycle (say, +30d) `12/30/14` √
2. Resub at adds 12m, `12/30/15` √
3. Cancel & resub at 1m (right so far?) Adds 30d.. should be `1/30/15`? Hmm... let me poke around some more

**Comment by HSalgo** [comment]
I think so! It's a little hard for me because I don't really want to look through the code (I'm much better at IDing bugs through trial and error than at actually looking through code to figure out why).

So to clarify: I have 0.94 months of "credit." This credit will be spent once I cancel my current 12 month subscription runs out? If so, then having cancelled and re-sub'd then, should the cutoff date be 13 months from today? (Can you confirm?)

Does that mean that if I were to cancel right now, and then pay another $5, I would have 13 months of "credit" plus the current month's subscription?

The only reason I'm worried is because of a doublecounting issue. If paying upfront now resets the gem purchase counter (thus buying 2x the gems this month), but it turns out that I STILL get to maintain subscription by using credit... I've actually gotten a free month's worth of gems by bypassing the gem limit. It's a little hard to explain. It makes sense in my head, but explaining it is going to be a little tough without variables and counters.

**Comment by HSalgo** [comment]
It's all sort of weird. I remember that upon my cancellation, it said that I started as a subscriber on 6/9/14. However, payment was happening on every 5th of the month, so my subscription technically only lasted until 12/05/14 (not sure if this was intentional or not). I cancelled a subscription yesterday (+1d credit), and resubscribed today. I think that kind of wonked everything up, which is why it says I 0.94 months of credit now, with an end date in 2015.

**Comment by HSalgo** [comment]
... I guess I could cancel again, since it looks like the credit card payment is going through, and we could see what date it gives me regarding when my subscription runs out. It'll also give me a chance to see what happens if I subscribe again for a month--if that also gets added onto the "Consecutive Months" or not.

Big fan of science, sorry.

**Comment by lefnire** [comment]
FWIW I'll drop your `user.purchased.plan` object here for when I can come back and take a peek

![screen shot 2014-12-04 at 3 18 09 pm](https://cloud.githubusercontent.com/assets/195202/5307307/27251366-7bc9-11e4-9519-8b6aa0c2ea22.png)

**Comment by HSalgo** [comment]
Okay. Cancelled again. It says that the subscription will expire on 01/02/2016. I'm not quite sure why it's not 01/09/2016 (I began on 05/09/2014)--are subscriptions set to be 30 days exactly? are they set to end at the last day of a selected month, and my 01/02/2016 is a glitch?

I can see why having some overhang into a following month would be a problem--having a subscription go from 12/04/14-01/04/15 will allow a person to purchase two months worth of gems for the price of one month of subscription. However, cutting it off at the end of the month means that someone who pays for one month's subscription from 12/20/14-12/31/14 only gets eleven days of a doubled drop cap.

I'm also still concerned about this wonkiness regarding the reset drop cap. If we have it confirmed that PayPal works and that you can refund me if anything suspiciously fishy happens, I'm going to go ahead and try to purchase an additional month now that I've unsubbed. If it resets my gem counter again, we might have a problem, despite the fact that I do love gems.

That problem being: if I can pay for a month subscription for the month of January 2016 (which will let me buy 50 gems in that month), but purchasing that subscription NOW resets my gem drop cap (because I've cancelled and re-sub'd) and lets me buy gems AGAIN for this month (the second time I've bought 50 gems for December 2014), then cancelling and re-sub'ing is allowing me to double-dip, if that makes sense.

**Comment by HSalgo** [comment]
Confirmed: PayPal works, though I only made a $5 payment. It was the $48 that was glitched, if I'm not mistaken.

Confirmed: extraMonths works properly--my credit now reads 12.94 months.

Confirmed: Upon cancelling this extra month subscription, the deadline is now 02/02/2016 instead of 01/02/2016.

Question: Still not sure why it's not 02/09/2016 (having started subscribing on the 9th of June) or 02/04/2016 (considering that I've done all of this purchasing today, on the 4th of December).

Confirmed: Gem purchases get reset. This allowed me to buy a third month's worth of gems in December. If I get to buy extra gems in the future too, then I've managed to bypass the gem limit again. This can likely be fixed by NOT allowing gem purchases to get reset if someone has cancelled a subscription within the past month.

PROBLEM: I refreshed, which caused everything to explode. It now says that my subscription will end on 01/02/2015 (instead of 02/02/2016). There is no line that says "Credit" anymore. The consecutive months reads 17; it should be 18 now that I had 5 months, and I've paid for another 14 now.

SORRY I am full of problems.

**Comment by lefnire** [comment]
K, I'll be investigating these today and tomorrow (sorry, a bit behind on things - will tackle soon as I can). In the meantime, rest assured i'll send any necessary refunds ([email me whenever](mailto:tyler@habitrpg.com)). Thanks for providing all this information, it's very valuable

**Comment by HSalgo** [comment]
Confirmed: I'm still a subscriber, as evidenced by the doubled item drop cap from the user display.

However: Apparently I have an extra 70 gems that I'm not convinced I'm supposed to have.

For now, keep the money, since the need for a refund isn't immediate, unless you guys want to be nice. As long as I end up with 14 months of credit at the end of the day (for a total of 18 months of consecutive activity), I'm happy to help.

Perhaps emailing me separately will be easier, since I'm sure everyone's getting spammed by my data. Additionally, I'm sort of curious as to what I'd need to do to be a more effective/helpful bug-finder for you guys.

**Comment by Alys** [comment]
For anything that's not a privacy or security issue for HSalgo, I'd quite like to see it kept here, if that's okay with everyone. Once it's all sorted, there'll probably be useful information here about odd little points (like the exact dates being used, which I already have a question about from another user).

**Comment by HSalgo** [comment]
Sure, I'm all for sharing, as long as I'm not boring/spamming anyone to death.

Yep, something is still up with my subscription, ever since I cancelled the most recent $5 one. It looks like all my credit just vanished. I'll wait for a day, but tomorrow I can try to re-subscribe yet AGAIN and see whether or not the credit comes back. In the meantime, maybe you guys can look and see how much credit HabitRPG says I have...?

**Comment by crookedneighbor** [comment]
FYI, I also cancelled my subscription today. When I tried to resubscribe for the 12 month plan using Stripe, I got a confirmation text message from Stripe, but failed to receive any confirmation from Habit. I looked at my subscriber settings, and it's set to expire at the end of this month (left over from my original subscription).

I'll wait a few days to make sure my card wasn't actually charged, and report back.

In case you need easy access to it, uuid: `75f270e8-c5db-4722-a5e6-a83f1b23f76b`

**Comment by HSalgo** [comment]
Cron happened. Credit's still missing. Perhaps you guys could take a gander and see the values in my UUID? (Or is there a place I could do it for you + report?)

**Comment by Alys** [comment]
@HSalgo There is a place you could do it (using the API), but it's probably best to let @lefnire look at it himself, so that you don't have to send your financial details across the net.

**Comment by crookedneighbor** [comment]
Just checked my bank account, still wasn't charged. I think it's safe to say it failed, just re-scubsribed via Stripe and it appears to be working now. Got the confirmation email from habit and a receipt email.

**Comment by HSalgo** [comment]
My cancelled subscription is still showing no credit. In the meantime, I'm still sitting on these gems which I think I've double-dipped to get by cancelling and resubscribing. (I see that you guys have added a little number next to the gems in the market.)

I could try to test it again and re-sub and see if the gem # still resets and/or if my credit is somehow hidden. Before I cancelled last though, it was off by one month, so perhaps looking directly at the code is best.

**Comment by SabreCat** [comment]
The number next to the Gems in the Market is the number still available for purchase with Gold this month.

**Comment by HSalgo** [comment]
Tried resubscribing to see if that would fix anything. The gem # reset, as expected. However, the consecutive subscription only shows 17 months--at this point it should be 20. Is the extra time capped at 12 months or something? (I have been subscribed for 5 months prior to this.)

**Comment by HSalgo** [comment]
Any updates? Otherwise, I will wait until January to see what's changed, and then I might contact you about that refund.

**Comment by LadyOrTheTiger** [comment]
I want to change my subscription to yearly. I can't cancel my monthly subscription.  I get this error message.  {"err":"Cannot read property 'current_period_end' of null"}   My user id is bd69ea39-5729-4a0f-a36d-849166c5934a  I tried to cancel on my Mac Air, no good.  Then I tried to cancel on my Windows XP PC and I still got the same error.

**Comment by Alys** [comment]
@LadyOrTheTiger I've made a change to your account that should fix that problem. Please try again and tell us here if you have more problems.

@HSalgo How are things going with you? Do you need anything fixed or a refund?

**Comment by LadyOrTheTiger** [comment]
Thank you Alys.  It is all fixed.  I was successfully able to change to a yearly subscription. You guys rock!

**Comment by audiolion** [comment]
can this be closed? what is the status on it, 2 years old!

**Comment by LadyOrTheTiger** [comment]
This was fixed 2 years ago.

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by Alys** [comment]
The individual people's specific problems were fixed but the bug might still remain; that's why this was left open. We see similar reports sometimes. However we do have a separate internal list of improvements we want to make to the subscription code, which includes a note about this issue.

**Comment by LadyOrTheTiger** [comment]
This was resolved two years ago. You asked me this last year too. I'm very
happy with my 12 month subscription. It still works great.
love,
Habitica fan
Melissa

**Comment by SabreCat** [comment]
@LadyOrTheTiger, per @Alys's comment above, we're holding the ticket open because we're not convinced the underlying problem has been resolved. I.e., it was fixed for you, but we think it could happen to someone else again. You might want to mute the thread using the unsubscribe link that comes with the email notifications!

**Comment by joe-salomon2** [comment]
@TheHollidayInn are you still working on it? If not, I'd like to take a crack if possible.

**Comment by FutureNathan** [comment]
Is this fixed? I bought my 12 month fine.

**Comment by SabreCat** [comment]
I'll close this for now, and we can reopen if we see further incidences!
