### ISSUE TITLE
quest completion screens don't show images

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4333]
I'm pretty sure that in the quest completion screens (below) there are meant to be images. I think they've been there in the past but have (recently?) disappeared. For collection quests (first screenshot below) I think there should also be text.

Investigating and fixing is probably a good task for a programmer with a small amount of site knowledge (or an enthusiastic new programmer).

![screen shot 2014-11-24 at 5 23 48 am](https://cloud.githubusercontent.com/assets/1495809/5305412/2e470db0-7c47-11e4-9180-41307facc3f3.png)
![screen shot 2014-11-24 at 5 23 11 am](https://cloud.githubusercontent.com/assets/1495809/5305411/2e447320-7c47-11e4-943c-b9d8c3637712.png)

**Comment by crookedneighbor** [comment]
@Alys Looking at the [strings for the moonstone quest](https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/questsContent.json#L81-L96), the only one that has completion text is part 3.

Here's the Trello card for [Moonstone Quest](https://trello.com/c/1iklq791/24-lv-60-equipment-quest).

@lemoness is it standard for multipart quests to only have completion text for the final part?

**Comment by lemoness** [comment]
Right now it hasn't been standardized, but there are definitely several
that do not. It's mostly up to the quest writers. Should I ask them to
include completion text after each quest even if it's in a linked quest
line?

**Comment by crookedneighbor** [comment]
@lemoness I don't think it's necessary. 

@thehindenburg just [submitted a pr](https://github.com/HabitRPG/habitrpg/pull/4375) for adding the images back in.
