### ISSUE TITLE
Missing Mystic Hourglass?

### ISSUE THREAD

**Issue by lanthanides** [HabitRPG/habitica#4334]
Hey everyone, the new content looks great!! 
I've been subscribed in February, March, and April, as well as July, August, and September. Since I subscribed for two 3-month consecutive periods, would I be eligible for the mystic hourglasses? I haven't received any yet. Here's proof of my subscriptions via a screenshot of my mystery items: http://awesomescreenshot.com/06d3yzrvb6

Thanks!

**Comment by lefnire** [comment]
[UUID](http://habitrpg.wikia.com/wiki/API_Options)?

**Comment by lemoness** [comment]
Ah, I think this is due to a confusion - the Mystic Hourglass was built so
that it only rewards current subscribers who are consecutive. Every time
you unsubscribe, it resets to zero, so you don't actually have any
consecutive months. Sorry about the confusion!

**Comment by lanthanides** [comment]
Ahh I see, now it makes sense...thanks for explaining :)
