### ISSUE TITLE
casting snowball on a person who's still a ghost doubles up image layers

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#4335]
So they become both a snowman and a ghost which looks abnormal:
![screen shot 2014-12-05 at 8 36 35 am](https://cloud.githubusercontent.com/assets/5908271/5307567/e3cd1870-7c59-11e4-9627-992f02bf80a4.png)

**Comment by negue** [comment]
Isn't this a feature? :P

We now have created a snow-ghost :P

Back to topic, what should be prioritized? Ghost-or-snow , or should we disable the ability to put one of these "states" if the other is already active?

**Comment by crookedneighbor** [comment]
I think if someone already has a changed state, it should either A) disable the ability to change it again or B) replace what is already there.

**Comment by breadstrings** [comment]
I assumed it would replace what was already there, which was why I did it in the first place. But for those who don't know that's what will happen, maybe a warning pop-up in that scenario that says "are you sure you want to cast a snowball on this person? Doing so would replace their current spell effects" or something like that.

**Comment by SabreCat** [comment]
A warning would be overkill, methinks. Just let me throw the snowball already ;P

**Comment by crookedneighbor** [comment]
@SabreCat :+1:

**Comment by Alys** [comment]
Is this really something that needs to be "fixed"? I love the appearance of
both cast together. If someone does it to a party member and doesn't like
it, they just have to wait a day until the buff wears off. And then try
again. If they really don't like that they've "wasted" one of their
snowballs/dusts, they can complain and we'll replace it. These things
really are for just a bit of fun, and it seems unnecessary to remove the
extra fun of being able to use both.

**Comment by breadstrings** [comment]
To me it looks like a bug as it wasn't the intention to have them both overlayed. How about an option to make it seem intentional? Ask the caster if they want to replace the current spell or add to it.

**Comment by crookedneighbor** [comment]
I agree with @breadstrings in that it looks like it's a mistake.

Not a big fan of opening up a dialog for the user to choose how it affects their victim. I think it should just replace what they currently are.

**Comment by Alys** [comment]
But being able to have both is desirable. The way it is now, you can have either ghost or snowman or ghost-snowman. It probably IS a mistake that both work together but it's cute and adds character to the game - it's a mistake that gives an extra, fun feature. I've done it myself deliberately a few times. Others probably have too. In the months in which we've been able to do both, this is the first bug report I've seen for it, but I have seen amused comments in the Tavern about how it's fun that you can do both.

**Comment by lemoness** [comment]
Just as a comment - in the future, we're highly likely to introduce more of
these for other events, since they're so popular. (In fact, one has already
been designed and will probably not merge as well, since it's for the
spring event and therefore brightly colored.) So at some point, we are
going to have to do something about stacking, or it will start looking like
a mess.

**Comment by crookedneighbor** [comment]
@lemoness Do you have a preference for how you want it to work?

**Comment by lemoness** [comment]
Sad as it is, I think the most recent cast should replace the older one -
as we add more of these, it will get more and more cluttered.

**Comment by crookedneighbor** [comment]
Is there a better way to do this than to write a function to clear visual buffs and add it above [this line](https://github.com/HabitRPG/habitrpg-shared/blob/6c8f9e39b63d4a4475458b7a010b137fcb3820b5/script/content.coffee#L656), and [this line](https://github.com/HabitRPG/habitrpg-shared/blob/6c8f9e39b63d4a4475458b7a010b137fcb3820b5/script/content.coffee#L678) and then just encorporate that into any new special item that gets added later?

**Comment by crookedneighbor** [comment]
I [worked this up](https://github.com/crookedneighbor/habitrpg-shared/blob/fix-item-spells/script/content.coffee#L648-L686).

Here is the important part:

``` coffeescript
special:
  clearVisualBuffs: (target) ->
     target.stats.buffs.snowball = false
     target.stats.buffs.spookDust = false
```

And then it gets called like this:

``` coffeescript
snowball:
  text: t('spellSpecialSnowballAuraText')
  mana: 0
  value: 1
  target: 'user'
  notes: t('spellSpecialSnowballAuraNotes')
  cast: (user, target) ->
  api.spells.special.clearVisualBuffs(target)
  target.stats.buffs.snowball = true
  target.achievements.snowball ?= 0
  target.achievements.snowball++
  user.items.special.snowball--
```

Can someone who is more familiar with the api and CoffeeScript confirm that is is a good way to do it and not super janky? It compiled and worked on my local install, but I'm not sure if this is the best way to format it. Should it be listed as a special spell? It kind of is?

**Comment by Alys** [comment]
This has been "fixed", sadly.
