### ISSUE TITLE
Canceling my subscription resulted in two cancellation emails

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4337]
When I cancelled my subscription (so I could resubscribe for a year instead), I got two duplicate emails about my cancellation. 

Haven't investigated how the mailing is done in the code base, but wanted to log it in case I didn't get to it tonight.
##

**Comment by lemoness** [comment]
Pinging @paglias

**Comment by paglias** [comment]
@lemoness it's always the same bug... Most, but not all people who unsubscribe receive 2 emails instead of one.

The line of code is https://github.com/HabitRPG/habitrpg/blob/d2e230db1fc66a98b02ea832d0c47647576f7ffb/src/controllers/payments/index.js#L96

@crookedneighbor  Did you subscribed with stripe or paypal?

**Comment by crookedneighbor** [comment]
I had originally subscribed with PayPal.

**Comment by paglias** [comment]
@crookedneighbor did you got redirected to the same url twice on habitrpg? 

@lefnire it's possible to test paymentes locally without real payment data?

**Comment by crookedneighbor** [comment]
@paglias I'm not sure If I got redirected twice.

I have the sandbox credentials for PayPal and Stripe, so I'll configure the email settings in `config.json` and remove `if(isProduction)` part of the line you highlighted to test it.

**Comment by paglias** [comment]
thanks!

2014-12-05 17:09 GMT+01:00, Blade Barringer notifications@github.com:

> @paglias I'm not sure If I got redirected twice.
> 
> I have the sandbox credentials for PayPal and Stripe, so I'll configure the
> email settings in `config.json` and remove `if(isProduction)` part of the
> line you highlighted to test it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4337#issuecomment-65811277

## 

Matteo Pagliazzi - paglias.net

**Comment by crookedneighbor** [comment]
I failed to test it.

Getting this error when I try to cancel (with no change to the branch):
![screen shot 2014-12-05 at 11 00 36 am](https://cloud.githubusercontent.com/assets/2916945/5319341/036daf78-7c6e-11e4-8862-f92afcfb6420.png)

Here's the url (API token redacted - though, shouldn't matter, it's a local account)

```
http://localhost:3000/paypal/subscribe/cancel?_id=b85c62a6-ec27-447a-aa09-d9d9d98cc8dd&apiToken=redacted
```

There's probably just an error in my `config.json`. I'll look into it later.

**Comment by lefnire** [comment]
@paglias yes it's possible, i'll send you credentials on slack soon

@crookedneighbor that's not a failed test. There really is a [paypal bug](http://stackoverflow.com/questions/25858816/paypal-billing-agreements-rest-api-how-to-start-immediately) that prevents subs from being activated immediately. They can only be activated minimum 5m after creation, and only within business hours. However, many users like to create a sub and immediately cancel, so they get the block of benefits without the fear of a future recurring payment. So we have [this](https://github.com/HabitRPG/habitrpg/blob/cb9083d9ba03854eabe4ff628f61ded809f7059d/src/controllers/payments/paypal.js#L163tL166) in place to tell them to hold off 5 minutes (or however long).

Anyway, if you wanna test without that in place:

``` diff
diff --git a/src/controllers/payments/paypal.js b/src/controllers/payments/paypal.js
index 9c7a1d4..5294907 100644
--- a/src/controllers/payments/paypal.js
+++ b/src/controllers/payments/paypal.js
@@ -160,9 +160,9 @@ exports.cancelSubscription = function(req, res, next){
       paypal.billingAgreement.get(user.purchased.plan.customerId, cb);
     },
     verify_cus: ['get_cus', function(cb, results){
-      var hasntBilledYet = results.get_cus.agreement_details.cycles_completed == "0";
-      if (hasntBilledYet)
-        return cb("The plan hasn't activated yet (due to a PayPal bug). It will begin "+results.get_cus.agreement_details.next_billing_date+", after which you can cancel to retain your full benefits");
+      //var hasntBilledYet = results.get_cus.agreement_details.cycles_completed == "0";
+      //if (hasntBilledYet)
+      //  return cb("The plan hasn't activated yet (due to a PayPal bug). It will begin "+results.get_cus.agreement_details.next_billing_date+", after which you can cancel to retain your full benefits");
       cb();
     }],
     del_cus: ['verify_cus', function(cb, results){
```

**Comment by crookedneighbor** [comment]
Awesome, thanks for pointing that out. I must still have something wrong with my smtp settings (using Google Apps with 2 factor authentication, so maybe it doesn't like my app specific password).

Will troubleshoot this week and try again.

**Comment by TheHollidayInn** [comment]
The code linked to the error is no longer used. We haven't had a report linked to this in a while, so I say we close and open a new issue if this reoccurs.

**Comment by Alys** [comment]
I agree. I've seen no recent reports of this and haven't noticed it in my own production site testing.
