### ISSUE TITLE
HabitRPG called Subscribe in Stripe Text Message

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4338]
Got this text message from Stripe:

![](https://d1x0mwiac2rqwt.cloudfront.net/baf204a0db036d1e704ac56ece896ebc/as/2014-12-04_11.00.36.png)

I assume the word 'Subscribe' should be 'HabitRPG'.

**Comment by crookedneighbor** [comment]
@lefnire I assume this would need to be adjusted via Habit's strip account?

**Comment by lefnire** [comment]
I don't think so, I looked through Stripe's dashboard and there's nothing
there that's causing this. Not too many fields to work with in to start,
and the Company Name field is "HabitRPG". I'd think it's maybe a wrong i18n
string being used for a certain field in code?

**Comment by crookedneighbor** [comment]
Any chance it's [this line](https://github.com/HabitRPG/habitrpg/blob/af7e68259dbd35de43410c03e263929b5a91b917/public/js/services/paymentServices.js#L33)

**Comment by lefnire** [comment]
ah, very likely! i say we change it and see how it goes

**Comment by crookedneighbor** [comment]
Yep. That was it. Just tested it with a Google voice number and a test card.
