### ISSUE TITLE
Stats shows more XP than needed for next level

### ISSUE THREAD

**Issue by Bathtor** [HabitRPG/habitica#4341]
User ID: 17685999-0a05-44d8-8a4f-6cf9c9fd8a3c
Browser: Google Chrome Version 39.0.2171.71 (64-bit)
OS: Mac OS X 10.10.1
Javascript Issues (doesn't seem to be anything important as far as I can tell, though):
 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
ping:1 Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=medium&hl=e…_1417777465209&parent=https%3A%2F%2Fhabitrpg.com&pfname=&rpctoken=14604191 Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habi…8%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/plugins/like.php?action=like&app_id=17252516279391…=en_US&ref=.VIGRNQ8eFAU.like&sdk=joey&send=false&show_faces=false&width=90 Failed to load resource: net::ERR_CACHE_MISS

For the actual problem see the marked area in the screenshot:
![screen shot 2014-12-05 at 12 05 07](https://cloud.githubusercontent.com/assets/596721/5314938/f4960072-7c77-11e4-9f9c-87b5fa9414f4.png)
Multiple reloads and syncs did not fix the issue.

**Comment by TwasBrillig1** [comment]
Hi @Bathtor - I'm not involved in the coding, but this issue is generally caused when a quest reward or a class skill grants the experience. It can be fixed by checking off any other task. This will make the app recognize that you have excess XP, and level you up properly. I hope this helps!

**Comment by crookedneighbor** [comment]
@TwasBrillig1 is correct. I'm going to close this for now, but if you complete a task and you still have not gained a level, report back and I will reopen this ticket.

**Comment by Bathtor** [comment]
Ok what you said worked.
But is there another issue that covers this problem?
I mean just because there's a workaround does not technically mean that it's not a bug, no?

**Comment by crookedneighbor** [comment]
@Alys @SabreCat I did a quick search through the issues, and couldn't find an open ticket describing this issue. Do you know of one?

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/issues/2143

**Comment by crookedneighbor** [comment]
Thanks @Alys. You rock. :rocket:

**Comment by crookedneighbor** [comment]
@Bathtor feel free to subscribe to the issue Alys linked to. It'll get sorted out eventually.

**Comment by Bathtor** [comment]
Done, thanks :)
