### ISSUE TITLE
Can't log in...Can't connect to server.

### ISSUE THREAD

**Issue by djmistak** [HabitRPG/habitica#4344]
Hi.

My user id is f07aca7f-4bad-4ad3-b1b0-1c0197c1f143

I haven't been able to log in for the last few days, and I thought that I needed to log out and log in. Once I did that, though, I was unable to log in (it says my username and password is incorrect). Then I when I went to have my password reset, it said my email address is wrong! I thought I used my normal email address, but I could have totally messed this up. Can anyone help?

**Comment by Alys** [comment]
Your data indicates that you used your Facebook account to register for HabitRPG. Please try the Facebook login option.  

If that works, and you like to now convert from Facebook authentication to username and password, there's instructions in the [FAQ](http://habitrpg.wikia.com/wiki/FAQ#Switch_from_Facebook_authentication_to_Username_and_Password) under "Switch from Facebook authentication to Username and Password".

Be sure to let us know if you need more help with any of this!

**Comment by djmistak** [comment]
Oh no! I don't have that facebook account anymore! I got rid of it when I read about how Facebook did experiments on emotions by manipulating a user's feed.

**Comment by djmistak** [comment]
What should I do now? Is there a way for you to switch it out? I'm still logged in on the app (although that says that it cannot connect with the server, too).

**Comment by Alys** [comment]
This can definitely be sorted out for you. Follow those instructions I linked you to. They'll work even though you can't log in to your old account. Thank goodness you have the UUID (user id) for it!! :)

**Comment by djmistak** [comment]
​The app was the lifesaver! Thanks so much! Hopefully the server connection
issues will have sorted themselves out, too.

Dan​

On Fri, Dec 5, 2014 at 10:23 AM, Alice Harris notifications@github.com
wrote:

> This can definitely be sorted out for you. Follow those instructions I
> linked you to. They'll work even though you can't log in to your old
> account. Thank goodness you have the UUID (user id) for it!! :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4344#issuecomment-65831904.

## 

Daniel J Mistak
