### ISSUE TITLE
Cannot buy gems with gold after being gifted subscription.

### ISSUE THREAD

**Issue by g2graman** [HabitRPG/habitica#4345]
User id:
9bc07270-4c5a-4410-8030-1d41e6e81aa1

Group ID: 4889c225-b5ed-41b1-92c2-bbc595521e62
Browser: Chrome
OS: Windows 8.1

After being gifted a 3 month subscription, I was not given the option to buy gems with gold in the market, though other features seemed to be unlocked.

**Comment by lemoness** [comment]
This bug has also been reported on Facebook:

"I got a one-month subscription-gift from a friend, but I can't buy gems in the market. Though the orb of rebirth appeared, but I'm not level 50 yet XD Bugged....."

Confirmation that other features have been unlocked but the Gems have not.

**Comment by Alys** [comment]
Hi @g2graman. This has been reported at https://github.com/HabitRPG/habitrpg/issues/4340 and we've already collected some information about the bug there, so I'm going to close this duplicate report. If you'd like to follow the progress of the fix, you can subscribe to email notifications in the right-hand column of that issue.
