### ISSUE TITLE
Challenge buttons and "leave challenge" menu appear faded

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4346]
On the [Challenges](https://habitrpg.com/#/options/groups/challenges) page, various buttons are faded (see screenshot), as is the menu that pops up when you leave the challenge. Happens in Chrome and Firefox. Multiple users have noticed it, including me.

Might be related to [Leave Challenge menu does not appear in Firefox - cannot leave challenges - Issue #4347](https://github.com/HabitRPG/habitrpg/issues/4347) or might not be.

![screen shot 2014-12-06 at 4 31 18 am](https://cloud.githubusercontent.com/assets/1495809/5320854/92e2db4a-7d01-11e4-9dfa-e44f97430d90.png)
![2u91mis](https://cloud.githubusercontent.com/assets/1495809/5320855/92e5d07a-7d01-11e4-95e4-e41f3d02c4b2.png)

**Comment by crookedneighbor** [comment]
The problem started happening after [this commit](https://github.com/HabitRPG/habitrpg/commit/7e9b92fcad3d2ad43da5395b34f580b8d961d648).

I think @lefnire created a new `.transparent` class for for the gifting modal, to make semi-transparent the inactive part of the modal, but a different `.transparent` class was already being used on the buttons in challenges to prevent the yellow background from appearing behind the buttons.

I think the button class should be adjusted from `.transparent` to `.bg-transparent`, that would make it more clear what it is doing. Making that change now. Chime in if you think there's a better tactic.

**Comment by lefnire** [comment]
ah woops, good catch blade - thanks!

**Comment by crookedneighbor** [comment]
@lefnire I'm just glad I looked through your commit a few days ago as that stuff was rolling out. For some reason the new transparent class stuck in my mind.
