### ISSUE TITLE
addthis Share menu does not appear when avatar has a mount

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4349]
When my avatar does not have a mount, I can hover over the share button and the menu will drop down as expected.

When my avatar has a mount, the share button appears but hovering will not cause the menu to drop down. Occasionally I can make the menu drop if I hover on the far right side of the share button.

This seems to be caused by the higher position of the avatar blocking the hover action of the share button.

Noticed in Chrome 38.0.2125.122 and Firefox 33.1 on Mac OS 10.6 in both my accounts (d904bd62-da08-416b-a816-ba797c9ee265 and 3e595299-3d8a-4a10-bfe0-88f555e4aa0c).

**Comment by crookedneighbor** [comment]
Just my two cents, but I'd like to move it out of the avatar box entirely. It gets in my way more than it's helpful.

#4277 happens to me all the time.
