### ISSUE TITLE
Websockets + Nginx

### ISSUE THREAD

**Issue by switz** [HabitRPG/habitica#435]
Thought there was a trello or github issue on this, but couldn't find it.

Anyway, good news! http://trac.nginx.org/nginx/changeset/5073/nginx

Edit: HN discussion [here](http://news.ycombinator.com/item?id=5240356)

**Comment by lefnire** [comment]
awesome, awesome!

**Comment by lefnire** [comment]
- http://nginx.com/news/nginx-websockets.html

**Comment by alanivey** [comment]
Nginx doesn't make it super clear with this- though it is "released," it's on the 1.3 development branch, which isn't stable. That said, I'm stoked to try it out and we should at least kick the tires on a test server somewhere to see how it does!

**Comment by horusofoz** [comment]
@switz Is this ticket ready to close?

**Comment by switz** [comment]
No, we're still using xhr-polling. Soon, hopefully!

**Comment by alanivey** [comment]
I think this can be closed now

**Comment by lefnire** [comment]
woo! @alanthing is the bomb
