### ISSUE TITLE
Website always crashes Firefox Developer Edition 35.0a2

### ISSUE THREAD

**Issue by ashaindlin** [HabitRPG/habitica#4350]
Not sure what's going on here, but the HabitRPG homepage always crashes Firefox Developer Edition on my laptop (I have an Acer C720 Chromebook running Gentoo Linux 3.17). After the page loads, I have about 5 seconds before my cursor becomes extremely sluggish or stops responding entirely and my 1-minute load average spikes to 5+ (this is on a dual-core machine). Then the entire Firefox process crashes, closing all open windows. I was able to reproduce this about 5 times, and I've never had it load without crashing.

In Chrome 39 it works okay. However, when I tried to record heap allocations during page load from Developer tools -> Profile, Chrome ran out of memory and killed the page. (The rest of my Chrome tabs were fine, unlike in Firefox where the entire browser crashed.) Only tried this once.

UUID: 83959d38-233d-44f8-b0a0-2a120f099c3c

**Comment by sbreiler** [comment]
Are you talking about the homepage or start page when coming back (tasks)? Are you still logged in? Did you try to log off (emtpy cache) and log in again?

**Comment by ashaindlin** [comment]
The tasks page, after logging in.

It seems fine after rebooting my computer for unrelated reasons (both in Firefox and in Chrome), so I'm going to close this, but if it comes up again I might poke at it and try to figure out what was going on.
