### ISSUE TITLE
Link for Tyler and Vicky's names

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4351]
Most NPC names contain a link to a site about the person, but Tyler and Vicky's names (in the "no hourglass" appearance of the Mysterious Time Travelers) do not. It would be nice to add links.

"Tyler" should link here: https://github.com/lefnire

"Vicky" should link here: http://blog.habitrpg.com/who

(This seems like it might be a simple task for an aspiring coder.)

**Comment by crookedneighbor** [comment]
That's a good idea, except that the title "Tyler and Vicky" is now a translatable string in [habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/subscriber.json#L66), which would make it harder for an aspiring coder to jump in.

Do you want me to just do it? Or leave it open for an aspiring coder to try their hand at it?

**Comment by crookedneighbor** [comment]
I'm going to post about it in the Aspiring Coders guild anyway. I think a quick newbie could get it.

Here are the relevant files that need changing:

https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/subscriber.json#L66
(See how `timeTravelersPopoverNoSub` handles putting in a link and model it after that)

https://github.com/HabitRPG/habitrpg/blob/develop/views/options/inventory/inventory.jade#L30
(Again, see how `timeTravelersPopoverNoSub` handles putting in a link just 2 lines below it and model it after that)

Here's how you can set up habitrpg to use your copy of habitrpg-shared.

``` bash
git clone both repos
cd HABITRPG-SHARED_LOCATION
npm link
cd HABITRPG_LOCATION
rm -rf node_modules/habitrpg-shared
npm link habitrpg-shared
```

Now your copy of habitrpg will use your copy of habitrpg-shared.

**Comment by andymantell** [comment]
Do let me know if I've done anything wrong, this is my first contribution!

**Comment by crookedneighbor** [comment]
@andymantell Just checked it out and it looks awesome! Merging it in.

**Comment by crookedneighbor** [comment]
@andymantell Can you post your [user id](75f270e8-c5db-4722-a5e6-a83f1b23f76b) in this issue?

@Alys or @paglias I think this is a good first contribution. Is it enough to tier?

**Comment by andymantell** [comment]
Here is my user ID:

8e01a835-91fe-4c81-823c-fe5ee34e8094

I'm trying to work through another ticket as well but still finding my way about so I'll see how that one goes... I may have bitten off more than I can chew for my second task. :-) I'm somewhat new to the whole stack, but AngularJS is something I really need to learn as I have had to turn down a couple of contracts due to not knowing it!

**Comment by crookedneighbor** [comment]
@andymantell If you're struggling with something, feel free to post about it on the ticket.

**Comment by andymantell** [comment]
@crookedneighbor Thanks very much, will do.

**Comment by Alys** [comment]
@andymantell : Tier++. Nice job. Thank you!
