### ISSUE TITLE
Allow choice of how time stamps are displayed

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4355]
From Susurrus in the tavern

> Any chance we could pick the date format for things like To Dos & the tooltip that shows on comments?
> The USA formatting throws me off.

Thought this was a good idea. Maybe just make it a [setting under language](https://habitrpg.com/#/options/settings/settings)?

**Comment by lemoness** [comment]
This has also been requested on trello for all date displays (such as due
dates).

**Comment by crookedneighbor** [comment]
@lemoness Do you have a link to that card. I'm doing a search through the cards for the word 'date', but I can't seem to find it.

**Comment by Verabird** [comment]
This seems like it will require adding a new user preference field to the database. I'm still figuring things out but I'm guessing that that's not something just anybody can do.

**Comment by Alys** [comment]
Actually, no, it's pretty easy to do that. You'd put a default setting in `preferences` in https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L260 and write code to change the setting when the user chooses an option, and then the database records automatically pick up the new field as necessary.

**Comment by Verabird** [comment]
Ah, thank you alys
