### ISSUE TITLE
Chrome Extension - Can't Level Up

### ISSUE THREAD

**Issue by alexarze** [HabitRPG/habitica#436]
Hey there again!

Here's another Chrome Extension bug:

I got to 81 out of 80 EXP from being productive online. Seems like a slight problem if you ask me ;) Not sure if you want to try and make it level up next time you reload or load the page or what, but that's just a slight thing I caught.

Just a suggestion: Javascript onLoad() function should do the trick to have it check you level and if exp_number > level_exp then set leftover_exp to exp_number - level_exp then levelUp() and set exp_number to leftover_exp and set leftover_exp to 0 :P 

If that made no sense, disregard. Otherwise, that'd be cool :D And the levelUp() function could be a cool little popup that says "CONGRATULATIONS! You were productive enough to level up."

**Comment by horusofoz** [comment]
This is being investigated under ticket [141](https://github.com/lefnire/habitrpg/issues/141).
