### ISSUE TITLE
can't access HabitRPG (was: "Something strange is happening")

### ISSUE THREAD

**Issue by djmistak** [HabitRPG/habitica#4360]
Hi. I haven't been able to access HabitRPG in over a week.

My user ID is 2c261603-07bf-47cb-afec-472432b1bc3a

Here is the history: since last week, the screen has said that it cannot access the server. I saw on twitter that some bug had been fixed, but I still couldn't access the server. I decided to log out and log back in. Since I created my account, I had left facebook. I had my old user id, which I migrated over to the user id above.

Now, the screen is basically all blank except for the health bars.

This is how I manage my tasks. I never thought I should doubt it, until now. I have a few things I need to handle, but I cannot remember what they are, and I don't have access to my list to add things to it. I need help very soon bc I'm sure there are balls I've dropped bc of this... thanks

**Comment by Alys** [comment]
Can you please try clearing your browser's cache? Note that it's important that it is the cache you clear (not just browsing history, or cookies, or other things - although it's okay if you clear them too), so if you're not completely sure how to clear the cache for the browser you're using, it might be best to google for instructions. Alternatively, you could try using HabitRPG in a browser that you've never used it in before (which won't have any cached pages). Let us know if that helps or not!

**Comment by djmistak** [comment]
I'm still trying to log in, so don't close this yet! I'll let you know when
it's a success... Thanks!

On Sun, Dec 7, 2014 at 4:40 PM, Alice Harris notifications@github.com
wrote:

> Can you please try clearing your browser's cache? Note that it's important
> that it is the cache you clear (not just browsing history, or cookies, or
> other things - although it's okay if you clear them too), so if you're not
> completely sure how to clear the cache for the browser you're using, it
> might be best to google for instructions. Alternatively, you could try
> using HabitRPG in a browser that you've never used it in before (which
> won't have any cached pages). Let us know if that helps or not!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4360#issuecomment-65963822.

## 

Daniel J Mistak

**Comment by djmistak** [comment]
So. Right now I'm waiting for a password to be resent... I clicked it yesterday to no avail. Twice. It's not in my spam.

**Comment by Alys** [comment]
Can you try another password reset today?

**Comment by djmistak** [comment]
I'm on the road. I'll be back tonight.

**Comment by djmistak** [comment]
Scratch that. I just did it from my phone.

**Comment by djmistak** [comment]
Fyi clicked the new password button and it and I'm still waiting (8hr now)

**Comment by crookedneighbor** [comment]
I was able to use the forget password just now with no problems.

@djmistak this might be a dumb question, but have you checked your spam folder?

Does a site admin want to look up @djmistak 's uuid on the site and check the email listed there?

**Comment by paglias** [comment]
@djmistak Could you send me your email address?  If you don't want to publish it here, send it at matteopagliazzi@gmail.com

**Comment by paglias** [comment]
@djmistak it seems that you had your account migrated from Facebook to Email/Pass and that UUID seems to be the old one so I need your email address to check what the problem is

**Comment by djmistak** [comment]
I have checked. So I'm not sure. Could part of it be because I just transferred from a Facebook account to a Facebook free account?

**Comment by djmistak** [comment]
My email is REDACTED
Thanks!

**Comment by paglias** [comment]
@djmistak the email is correct but for some reason is not getting sent

**Comment by paglias** [comment]
@djmistak maybe you got it now, could you verify?

**Comment by djmistak** [comment]
Nope. Very strange! No spam either.

**Comment by djmistak** [comment]
I thought I'd try to send it again...

**Comment by djmistak** [comment]
I don't care much about the security of my account. If I can make up a password and then someone send it to me or something, that'd be great.

**Comment by paglias** [comment]
@djmistak I'm going to make a change to the email sending system. If it still doesn't work after maybe we can "make up" your password. @lefnire 

I'll follow back with more info soon

**Comment by djmistak** [comment]
Thanks!

On Thu, Dec 11, 2014 at 7:35 AM, Matteo Pagliazzi notifications@github.com
wrote:

> @djmistak https://github.com/djmistak I'm going to make a change to the
> email sending system. If it still doesn't work after maybe we can "make up"
> your password. @lefnire https://github.com/lefnire
> 
> I'll follow back with more info soon
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4360#issuecomment-66636101.

## 

Daniel J Mistak

**Comment by paglias** [comment]
@djmistak you should have received an email now. It probably won't work but we've finally found the problem and working on it!

**Comment by paglias** [comment]
@djmistak in the meantime could you tell me if at least you got the email? it results as sent and received on our side

**Comment by djmistak** [comment]
It came! And you're right, they didn't work. Thanks for helping me through
this! I hope that my teammates are n't hating me right now...

On Thu, Dec 11, 2014 at 8:33 AM, Matteo Pagliazzi notifications@github.com
wrote:

> @djmistak https://github.com/djmistak in the meantime could you tell me
> if at least you got the email? it results as sent and received on our side
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4360#issuecomment-66646211.

## 

Daniel J Mistak

**Comment by paglias** [comment]
@djmistak it should be finally fixed and you should have received another email with a correct password

**Comment by djmistak** [comment]
Great it worked, and I can access it (the original problem). I've been a
subscriber forever, but I didn't get the mystic hourglass. Is this a
product of switching my profile from Facebook to a non-Facebook profile? If
so, is there a way to get the steam punk stuff and a mystic hourglass?

On Fri, Dec 12, 2014 at 1:20 AM, Matteo Pagliazzi notifications@github.com
wrote:

> @djmistak https://github.com/djmistak it should be finally fixed and
> you should have received another email with a correct password
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4360#issuecomment-66749089.

## 

Daniel J Mistak

**Comment by djmistak** [comment]
And thanks so much for everything!!

On Fri, Dec 12, 2014 at 7:12 AM, Daniel Mistak djmistak@gmail.com wrote:

> Great it worked, and I can access it (the original problem). I've been a
> subscriber forever, but I didn't get the mystic hourglass. Is this a
> product of switching my profile from Facebook to a non-Facebook profile? If
> so, is there a way to get the steam punk stuff and a mystic hourglass?
> 
> On Fri, Dec 12, 2014 at 1:20 AM, Matteo Pagliazzi <
> notifications@github.com> wrote:
> 
> > @djmistak https://github.com/djmistak it should be finally fixed and
> > you should have received another email with a correct password
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4360#issuecomment-66749089.
> 
> ## 
> 
> Daniel J Mistak

## 

Daniel J Mistak

**Comment by paglias** [comment]
@djmistak great and sorry for everything :)

as for the subscriber benefits I have to ask @lefnire

**Comment by lefnire** [comment]
@djmistak for some reason `purchased.plan.dateCreated` was `null` (I haven't seen that before..., sorry for all the trouble you've been having!) Check your subscription perks now, should be updated
