### ISSUE TITLE
Incorrect info on subscription email

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4363]
The confirmation emails for subscriptions states:

> Purchase gems with gold, up to 25 a month!

Which is true if you get the 1 month subscription, but not true if you purchase more.

@lemoness Do you have a suggestion for what it should say instead?

**Comment by lemoness** [comment]
Great point - I need to update this email to include info about the new
subscription plans. Will work on this today.

**Comment by paglias** [comment]
updated
