### ISSUE TITLE
Burst of Flames doesn't level character

### ISSUE THREAD

**Issue by Frimkron** [HabitRPG/habitica#4364]
The Burst of Flames spell awards XP for the habit that it's used on, but if this pushes the XP beyond the next-level amount, the character doesn't level and instead is left with more than their max XP.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2143
To follow the progress of this issue, you can choose to subscribe to email notifications (right-hand column).
