### ISSUE TITLE
Can't remove habit from Halloween costume challenge

### ISSUE THREAD

**Issue by darktendril** [HabitRPG/habitica#4366]
I cannot remove "Work on Costume" from my habit list.  It shows an unbroken challenge link, however I cannot see that the challenge even still exists, to try to leave it?  It does not show up under the list of my challenges that I am participating in, and I could not find it under "All Challenges" either.  I would like this habit removed from my list please, if possible.  My ID is bd34c114-0bbf-4939-a17f-fe6fff30b01e
Thanks

**Comment by Alys** [comment]
Please follow the advice in the section called "Deleting a Challenge Task" in the [Challenges](http://habitrpg.wikia.com/wiki/Challenges) page. If you get through all the suggestions there and it still can't be deleted, let us know.

**Comment by darktendril** [comment]
Hi, I had tried everything listed there for the desktop site, without success, but just read that I might be able to delete it using the mobile app, and that worked! Thanks!
