### ISSUE TITLE
Tooltip for chat titles wonky when user has more than 2 titles

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4367]
## Tooltip with a few titles

![screen shot 2014-12-09 at 6 08 06 am](https://cloud.githubusercontent.com/assets/2916945/5357269/3043ff02-7f6b-11e4-8be1-6878273cda4e.png)
## Tooltip with many titles

![screen shot 2014-12-09 at 6 08 19 am](https://cloud.githubusercontent.com/assets/2916945/5357273/381f2620-7f6b-11e4-8085-ef0b3efd48ef.png)

We could apply `white-space: normal` to `.chat-message .tooltip` and it would look like this:
![screen shot 2014-12-09 at 6 17 34 am](https://cloud.githubusercontent.com/assets/2916945/5357283/5df4aa5a-7f6b-11e4-9401-97bcec5da996.png)

**Comment by crookedneighbor** [comment]
@lemoness (and anyone with aesthetic sensibilities) How does that look to you?

**Comment by lemoness** [comment]
I like it - it won't affect the shorter titles though, right?

**Comment by crookedneighbor** [comment]
Unfortunately it would affect the smaller titles too. I've been thinking on it and I think I have a solution that will accomdate both. Will post it later today.

**Comment by crookedneighbor** [comment]
Made it apply the wrapping style if the title is longer than 30 characters. That should take care of it.
