### ISSUE TITLE
Hover over Guild Gems - and get "Guild Bank True" double popup

### ISSUE THREAD

**Issue by taryneast** [HabitRPG/habitica#4369]
**Steps to reproduce:**
1) in the browser (chromium)
2) go to guild page and click on "Bayesian conspiracy"
3) top(ish) right are the guild gems
4) hover over these and you get two popups overlaying one another

The bottom popup looks like the legit one, it has the title "Guild Bank" and a body that seem ssto be explaining what the gems are.
The one overlaying this is smaller and also with a title "Guild bank" and a body that simply says "true"

Here's a screenshot:

![habitrpg_guildgems_hoverbug](https://cloud.githubusercontent.com/assets/34846/5367511/71576e8a-8050-11e4-98d8-26ea9f65cbd2.png)

**What I expected:**
I suspect that the second overlay should not be there.

**Comment by crookedneighbor** [comment]
This has been fixed in the github repo, but it has not yet been deployed to production. Will be deployed soon, so hang in there :smile:

**Comment by taryneast** [comment]
yay - I'm happy with that :)
