### ISSUE TITLE
Sent me back down a level??

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#437]
Hey! I've been working hard all day on progress and managed to get to level five and knock a ton of stuff off of my to-do list, but then when I refreshed just now after the page was down, it's like I didn't sign on today at all! Back to a high level 4, all of the to-dos I completed are back, etc. :/

My user id is 7bde7864-ebc5-4ee2-a4b7-1070d464cdb0 - should I just re-click everything?

**Comment by lemoness** [comment]
Clicking isn't working for me, so hopefully you can restore it :(

**Comment by lefnire** [comment]
hey @lemoness i'm working through some hefty bugs, all on #427. I'll restore you as soon as i get those things fixed

**Comment by lemoness** [comment]
Don't worry - looks like you fixed the clicking bug, so I just reinputted the info and clicked a couple habits until I was all restored :) I'll let you know if there are any other problems, but things look okay for now.

**Comment by lefnire** [comment]
Cool, you rock lemoness. I'm going through my emails restoring people's
accounts, so you saved me some time - thanks!
