### ISSUE TITLE
Routing Errors?

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4371]
In `public/js/app.js`, the routing is listed this way:

```
$urlRouterProvider
    // Setup default selected tabs
    .when('/options', '/options/profile/avatar')
    .when('/options/profile', '/options/profile/avatar')
    .when('/options/groups', '/options/groups/tavern')
    .when('/options/groups/guilds', '/options/groups/guilds/public')
    .when('/options/groups/hall', '/options/groups/hall/heroes')
    .when('/options/inventory', '/options/inventory/drops')
    .when('/options/settings', '/options/settings/settings')

    // redirect states that don't match
    .otherwise("/tasks");
```

But clicking on the guilds link from the menu, or the guilds and hall links from the guilds sub menu take you to an empty version of those pages, rather than the routed versions above (guilds -> guilds/public, hall -> hall/heroes).

Why is that?

Looking at the menu buttons, it looks like the buttons for inventory is stated explicitly to go to drops. 

```
a(ui-sref='options.inventory.drops')
    span=env.t('inventory')
```

Should the ones for guilds and halls be set explicitely too?

```
li
    a(ui-sref='options.social.guilds.public')=env.t('guilds')
li
    a(ui-sref='options.social.challenges')=env.t('challenges')
li
    a(ui-sref='options.social.hall.heroes')=env.t('hall')
```

If so, this would be an easy one for a newbie to tackle. 
# 

What is the point of the routing in `app.js`? I tried removing all the `.when('foo", "bar")`s, restarted the local server, and it didn't seem to make a difference. Are those lines from an older version of the ui-router?

**Comment by paglias** [comment]
Those when are like redirects but seem to be broken since last update
Il 10/dic/2014 18:31 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by crookedneighbor** [comment]
Yeah, that's what I thought.

Would you like me to investigate and make the routing work (not entry level)? Or should we go with explicit links for now (entry level)?

**Comment by paglias** [comment]
@crookedneighbor whatever you want :) Of course fixing the when to make sure they work would be better but if you can't no problem

**Comment by crookedneighbor** [comment]
Cool. I'll assign myself to it and remove the entry coding label.

**Comment by crookedneighbor** [comment]
@paglias Solved it. 

The `options/groups` rule was somehow overriding the more specific `options/groups/hall` and `options/groups/guilds` rules. Just had to move the general groups link down under the other groups.

**Comment by crookedneighbor** [comment]
I was wrong, looks like it'll work as expected if you reload the page, but if you navigate via a link, it needs to be set to the specific page. Going to fix it now.
