### ISSUE TITLE
Experience and gold earned via backstab skill disappears when account is synced.

### ISSUE THREAD

**Issue by imminentimpact** [HabitRPG/habitica#4373]
Hello,

A few times now I've cast "Backstab" on a blue task and been rewarded with 120-150 gold and a good chunk of exp.   However, whenever I sync my account, the experience points and gold disappear.  Even if I purchase an armor or weapon item, they end up disappearing after I sync the account.  The page I'm usually on is the "Tasks" page.

User ID: 39724a17-f978-420d-9915-67503ffa3b64

Current browser:  Internet Explorer 11
PC OS: Windows 7 Professional 64-bit

**Comment by deilann** [comment]
When casting Backstab, make sure to cast it on the body of the task, not a
button.

**Comment by imminentimpact** [comment]
Hi Deilann,

Thank you for the help.  However, I'm casting it on the body of the task and it still occurs.

**Comment by deilann** [comment]
Can you try casting it in a supported browser, then? Like Firefox or Chrome?

**Comment by imminentimpact** [comment]
Hm...my apologies.  I just tried re-casting it, making sure that I casted on the body like you suggested...and it seems to be working just fine.

Must have been user error :-/ thank you for your help!
