### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4376]
Is there any reason we're not using an `.editorconfig` file in the repos?

It could help to standardize some things, like indentation. Obviously, it'll still depend on the contributors to have the associated plugin installed on whatever text editor they're using, but I think it would be good to have regardless.

Does anyone have a preference for indentation conventions for particular files? Looks like most of the site is 2 spaced.

http://editorconfig.org/
##

**Comment by ojintoad** [comment]
:+1: was surprised this wasn't included.

**Comment by tylerdmace** [comment]
+1 2-space (if we're still tallying votes)
