### ISSUE TITLE
Subscription info not displaying correctly

### ISSUE THREAD

**Issue by deathau** [HabitRPG/habitica#4377]
I mentioned this on Facebook but was directed here.
I cancelled my recurring monthly subscription and immediately purchased a recurring yearly subscription (via PayPal). That all seems to have gone through fine, however on my subscription page, it says I am on the monthly subscription.

These message is as below:

Subscribed

Recurring $5 each 1 Month(s) (Paypal)
 You have 0.00 months of subscription credit.
 Consecutive Subscription
Consecutive Months: 20
Gem Cap Extra: 25
Mystic Hourglasses: 4

It looks like the consecutive monthly info has updated, but the subscription hasn't. I'm hoping it's just a display issue, but I suppose either way it's a big that needs fixing.

Thanks guys.

My User id is: c36d2160-1566-48fb-9d57-ad411cae195e

**Comment by lefnire** [comment]
Ah, it is indeed just a display issue. I've verified in the database your
account is using basic_12mo (the correct subscription). So fear not, but
I'll look into the display issue when I get a moment. Just to be certain,
you tried a hard refresh?

**Comment by deathau** [comment]
I hadn't, but looking now it's fixed itself up to $48 for 12 months. So perhaps it was just a cache issue (or took a bit to update). Unless you fixed it already?
I'm any case, thanks for your quick response.
Just a quick one while I'm here though, perhaps the message should also indicate a date of renewal? Or some indication of how long is left in the current subscription period.

Thanks again guys.
