### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by Nebquerna** [HabitRPG/habitica#4379]
My ID: xxxxxxxx
I think that's right.

So my problem is quite simple. I cannot sign up. I'm using Win8, and I tried on Google Chrome and Firefox.
It let me sign in, but the only thing that appears is this http://image.noelshack.com/fichiers/2014/50/1418502882-2014-12-13-14h34-17.png

I tried to empty my cache/cookies
I tried to use another wifi
I tried to use a different computer
I tried to sign up wth my tablet (Asus, Android) with Firefw and Opera. The same thing everytime.

The only thing that is saving me is that I have the app on my tablet and it allows me to check my things, but I can't seem to accept quests. But well, it's not the problem.
Any advices?

**Comment by Alys** [comment]
There was no user with the ID that you gave, which might mean that you gave us your API Token instead. The API Token is like a password and so I have edited your comment to remove it. The HabitRPG admins all received your comment in an email, so we can still refer back to that code if we need it.

On the app, could you please go to Settings? There's a "UUID" field there, with a blue clipboard button next to it. Can you paste that UUID into this issue?

**Comment by crookedneighbor** [comment]
Looks to me like the Angular controllers are failing to load. 

Can you open the site in Chrome, right click anywhere on the page and choose inspect element and select the console tab? Take a screenshot and post it here.

**Comment by Nebquerna** [comment]
I am really sorry, for some reason I thought the API was the right one.
Anyway, UUID: 5c8a37ea-2125-4f1e-9132-f68c1679cbe5

And here is the screenshot of the code:
http://image.noelshack.com/fichiers/2014/50/1418575947-2014-12-14-10h51-53.png
http://image.noelshack.com/fichiers/2014/50/1418575947-2014-12-14-10h52-04.png

**Comment by negue** [comment]
You are on the "Elements" Tab, could you make screenshots of the "Console" tab? :)

**Comment by crookedneighbor** [comment]
Could you click on the console tab and take a screenshot of that window? Here's a screenshot showing where it is:
![console](https://cloud.githubusercontent.com/assets/2916945/5428253/8cc4a87a-8381-11e4-9780-836db780cbbe.png)

**Comment by crookedneighbor** [comment]
Oh man, ninja'd by @negue.

**Comment by negue** [comment]
Haha sry :D, yours is better with the edited screenshot

**Comment by Nebquerna** [comment]
Oh gosh, I am so oblivious today, I'm sorry!
http://image.noelshack.com/fichiers/2014/51/1418628253-2014-12-15-01h23-56.png
Here is the console thingy

**Comment by Alys** [comment]
That's okay Nebquerna. :)  It's just lovely that you're being so patient with our site bug!

@lefnire, @paglias, et al : The relevant part of the console log is likely to be this bit:
`TypeError: Cannot read property 'paymentMethod' of null`

The purchased object in Nebquerna's data looks like this (irrelevant data omitted for privacy):

```
    "purchased" : {
        ....
        "plan" : null,
        ....
    }
```

For comparison, my purchased object is like this:

```
    "purchased" : {
        ....
        "plan" : {
            ....
            "paymentMethod" : "Stripe",
            ....
        },
```

**Comment by paglias** [comment]
@Alys I think user.plan should be an empty object, not null. Maybe a problem with the last migration?

**Comment by Nebquerna** [comment]
It's actually kind of awesome. I have no idea what you're saying but I know it's code and it looks like magic from here, good luck!

**Comment by busterroni** [comment]
I get all issues emailed to me, so I still have their API key in my email,
and I'm sure many others do aswell. You might want to reset it.

**Comment by Nebquerna** [comment]
And how would I do that?

**Comment by Alys** [comment]
@Nebquerna It's something an admin would have to do for you. We'll make sure it gets done for you.

**Comment by Alys** [comment]
@Nebquerna Your API Token has been changed. It might be best if you log out of HabitRPG and log back in. You'll then be able to see the new token in the API screen.

**Comment by Alys** [comment]
@paglias An unsubscribed test account has this for the plan:

```
        "plan" : {
            "mysteryItems" : [ ],
            "gemsBought" : 0
        },
```

so I've set @Nebquerna's plan field to that. The test account does not have the problem that Nebquerna reported.

@Nebquerna can you please try the website again?

**Comment by Alys** [comment]
A database search for accounts that have `purchased.plan` existing but set to null finds another seven accounts. @lefnire, may I have your approval for me to adjust those accounts as described in my previous comment here?

**Comment by lefnire** [comment]
@Alys permission granted. Possible query (unless you have your own method):

``` javascript
db.users.update(
{'purchased.plan':null},
{$set:{'purchased.plan':{extraMonths:0, gemsBought:0, mysteryItems:[], consecutive:{count:0,offset:0,gemCapExtra:0,trinkets:0} }}},
{multi:1}
);
```

**Comment by Nebquerna** [comment]
My API token has been changed, but the website is still doing the same thing. Could it be a problem on my part?

**Comment by Alys** [comment]
The browser might be using your old user data from before the database fix
went through. Please try opening an incognito window in Chrome (File menu
-> New Incognito Window) and log in to HabitRPG there.

**Comment by Nebquerna** [comment]
And yes, this is working!
So is there anything I can do for the non incognito Chrome?

But anyway, this is actually really nice, to finally be able to connect on computer, thanks!

**Comment by paglias** [comment]
You should delete localStorage. Try to sign in and get to the non working
page. Open the chrome console and switch to the Resource tab. On the left
expand local storage for habjtrpg.com and click and delete everything
that's there (right click, then delete)
Il 16/dic/2014 07:10 "Nebquerna" notifications@github.com ha scritto:

**Comment by Nebquerna** [comment]
Guys, you fixed it!
It works normally again, I don't know if you realized but you've all been awesome, thanks again!

Now it doesn't bother me, since I'm not really using it, but you might want to know that on firefox, the URL seem to tell me that I'm on the task page, but I'm actually still on the home page
http://image.noelshack.com/fichiers/2014/51/1418711305-2014-12-16-00h26-58.png

**Comment by SabreCat** [comment]
That last isn't unusual. Pressing "Play" should clear it up fine.

**Comment by Nebquerna** [comment]
No what I meant is when I press play, the URL changes like I'm on the tasks page but I still am on the home page, not the tasks page.
