### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4380]
Something I assume is easily fixed:

In the "Find the Lair of the Wyrm" quest, Vice Part 2, the phrase "your party makes it's way to Mt. Habitica" should be corrected to "your party makes its way to Mt. Habitica". ;)

**Comment by crookedneighbor** [comment]
Opened up an issue [here in the habitrpg-shared repo](https://github.com/HabitRPG/habitrpg-shared/issues/392) where the file that needs to be changed is located.
