### ISSUE TITLE
{err:Cannot read property 'purchased' of null}

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4384]
A few users have reported an error when subscribing via Paypal: `"{err:Cannot read property 'purchased' of null}"`. The subscription is setup properly on Paypal (they're charged), but the error prevents the details from being saved to their account. I'm able to verify the txn and map the details fine, but this needs fix'n
##

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by SabreCat** [comment]
We do still get occasional reports of people attempting to subscribe, getting charged, but not receiving subscription benefits on the Habitica end. The specific error message doesn't sound familiar, though.

**Comment by TheHollidayInn** [comment]
I believe this happens when Paypal sends a cancel notice, our webhook doesn't work correctly, and then someone tries to cancel via our Paypal route, but it is already canceled on the Paypal side, so we get an error http response from the API.

**Comment by SabreCat** [comment]
@TheHollidayInn: That might happen (it certainly does with Stripe, which has no Webhook handling at all yet), but if so, that's a different issue--this issue as reported happens at time of subscription, not cancellation.

**Comment by TheHollidayInn** [comment]
We always assume success, so we need to code and write tests for the following: https://developer.paypal.com/docs/api/errors/

**Comment by TheHollidayInn** [comment]
We will use this PR: #8690 to determine if this problem still exists.

**Comment by joe-salomon2** [comment]
Hi, can I tackle this issue?

**Comment by TheHollidayInn** [comment]
We don't have a reliable way to reproduce this. It seems to be caused by corruption during the subscription process. I have a third-party logging set up to discover this. I would suggest a different issue for now.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by TheHollidayInn** [comment]
I haven't seen it on our log system. So, I'd say no.
