### ISSUE TITLE
Rare mounts gone

### ISSUE THREAD

**Issue by polishsputnik** [HabitRPG/habitica#4386]
In inventory my rare mounts are gone. I was riding one, and it's no longer with my avatar display. My user id is e79dad5d-f592-41d8-9185-3f7a1ed3c067

**Comment by Alys** [comment]
Your data shows that you still own the Mantis Shrimp mount. Did you own any others?

Please go to your [Mounts page](https://habitrpg.com/#/options/inventory/mounts), reload it, and look at the bottom. If the rare mount section still doesn't appear, do this - preferably in the Chrome browser:
- log out of HabitRPG
- clear your browser's cache (make sure it really is the cache you clear, not just the browsing history or other data)
- log back in
- reload the mounts page
- take a screenshot of the bottom portion of the mounts page showing the final line of quest mounts (even if that line just has pawprints), the space where the rare mounts should be, and the top of the page footer

**Comment by polishsputnik** [comment]
Logging out and in again fixed it.

Thanks very much!
Jenn.
