### ISSUE TITLE
Change Grand Gala Link

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4389]
Right now the Seasonal Shop's Grand Gala link points to the community page of the wiki, but since then, a Grand Gala page has been created here: http://habitrpg.wikia.com/wiki/Grand_Galas

Clicking on the link should open the Grand Gala page in a new tab.

**Comment by crookedneighbor** [comment]
@lemoness How urgent is this? 

If you want it done right away, I'll just go in and do it. If not, I'll post it in the Aspiring Coders guild.
