### ISSUE TITLE
Cannot see gold, hidden by 'Rewards' text

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#439]
In this screenshot, you can see the bug I'm talking about:
![Screen Shot 2013-02-19 at 4 26 42 PM](https://f.cloud.github.com/assets/3424032/174028/c619bce4-7af2-11e2-8d2d-3cb836ccc6ec.png)
The 2 is kind of hidden by the 'Rewards' text. I think you can fix this by moving the gold and silver coins and the numbers next to them more to the right. It may not look too bad with that screenshot but before that I could only see the 2 by highlighting it with my mouse.
If that link doesn't work copy and paste this into your browser:
http://i.imgur.com/M6djFWc.png

**Comment by tmas** [comment]
This is an issue with the way habit handles fluid width. I think each section should have a min-width as well as a max-width to force it to be large enough to hold its elements. The sections already stack themselves vertically when the screen gets to a certain width, but there is an area between full desktop mode and phone mode (vertical stacking) where this will occur.

UPDATE: looks like the correct min-width is around 315 px. I'd update it myself, but I can't test it until #429 is fixed. Here's some code that _should_ work if it's just copy/pasted into the css:

```
.span3 .well {
    min-width: 315px;
}
```

**Comment by horusofoz** [comment]
This is being addressed under #37
