### ISSUE TITLE
No habits, dailies or to dos

### ISSUE THREAD

**Issue by DaddyLudwig** [HabitRPG/habitica#4391]
Just now I noticed a glitch saying that I have no habits, dailies, or to dos. Cron did run so I don't know what's going on. Also it didn't make me go back to level 1.

fa197a4b-e065-4551-803a-c8a5b9970f9d

**Comment by crookedneighbor** [comment]
Is it possible that you have a tag enabled? In which case, click the clear button:

![clear](https://cloud.githubusercontent.com/assets/2916945/5508168/b7b9b72c-876f-11e4-8da1-ca48eebd7386.png)

**Comment by DaddyLudwig** [comment]
I don't have any enabled and it is only on a specific computer. All other computers show it up correctly.

**Comment by lefnire** [comment]
Try clicking the "clear" button anyway, just in case

**Comment by crookedneighbor** [comment]
@caters12 Any news on this?

**Comment by Alys** [comment]
I've just done a database search for this user's UUID with the search set to report only the ID numbers of the tasks and the dates they were created (no task text or any other personal details). It shows that there are several Habits, Dailies, and To-Dos, created from 17 December onwards. I'm guessing it was just a temporary tag display problem that stopped them appearing, as suggested above. I'm closing this, but @caters12 if you still can't see them, tell us and we'll reopen it.
