### ISSUE TITLE
Class Gear dialog screen appears three times after changing classes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4396]
After changing class, the "Class Gear" dialog appears three times. All three dialogs disappear at the same time when you click on the top-most "End tour" button.

Noticed by @deilann as well as by me (e7b5d1e2-3b6e-4192-b867-8bafdb03eeec and d904bd62-da08-416b-a816-ba797c9ee265).

![class gear](http://i.gyazo.com/444fa9a8da998908bc7a3d0725ff8608.png)

**Comment by deilann** [comment]
Only semi-related... but I think we need dolphin mounts.

**Comment by andyzinsser** [comment]
I'll take a stab at this one.

**Comment by andyzinsser** [comment]
Just submitted PR #4431
