### ISSUE TITLE
Emojis in tasks are flat in IE11 and the Windows version of Firefox (and black & white in Windows 7)

### ISSUE THREAD

**Issue by janey-p** [HabitRPG/habitica#4397]
Currently, the emojis included in tasks (habits, dailies and to-dos) are displayed in flat design, which makes them hard to see on colored backgrounds:
![flat emojis](https://cloud.githubusercontent.com/assets/10269892/5525217/b2392f9c-89e2-11e4-89e5-954ad9238742.PNG)

None of the suggested workarounds helped. (reload, logout/in, clear cache, restart browser)

Seen on FF 34.0.5 on Win 8.1
## 

_edit by admin:_
# WORKAROUND - what to do if your emoji are flat or black and white:

Use the [Chrome browser](https://www.google.com/chrome/browser/desktop/) if you can. Emoji are normal in that.

If you have two HabitRPG accounts and typically use Chrome for one and a different browser for the other, you can use Chrome for both by running one account in an incognito window (File -> New Incognito Window).

_end of edit by admin_

**Comment by kawunngg** [comment]
mine are also flat, but grey. also tried the solutions Alys suggested without effect. 

Firefox 34.0 on Win 7

**Comment by habitrpguser** [comment]
Mine are black & white. Both Firefox and Explorer. Win 7. Workarounds (reload, log out, clear cache, restart browser, restart computer, delete cookies & practically everything else for good measure) had no effect. I didn't try to reinstall the browser.
Just in case it might be a locality settings thing: I'm in Germany.

**Comment by MagBag** [comment]
My emojis in Chrome 39.0.2171.9m look normal -- not black and white, not flat.  However, in Firefox, they are black and white with little detail.  I tried all the workarounds to no effect.  I am using Windows 7 and my Firefox version is Firefox 34.05.  This problem also occurred in the FF version prior to 34.05, as it updated while I was restarting and clearing my cache, etc. in an attempt to get around the problem.

**Comment by crookedneighbor** [comment]
I've done some investigating. Here's how it looks in various browsers:

### Windows 7, Firefox:

![screen shot 2014-12-22 at 9 24 41 am](https://cloud.githubusercontent.com/assets/2916945/5526782/fcdc117a-89bc-11e4-9beb-15ebe2ff115b.png)

### Windows 7, IE11:

![screen shot 2014-12-22 at 9 31 09 am](https://cloud.githubusercontent.com/assets/2916945/5526818/58bbe592-89bd-11e4-9cdc-83c7232b42ac.png)

### Windows 7, Chrome:

![screen shot 2014-12-22 at 9 30 00 am](https://cloud.githubusercontent.com/assets/2916945/5526793/2286cb68-89bd-11e4-9ba2-81e2d50db8cd.png)

### Mac 10.10, Chrome:

![screen shot 2014-12-22 at 9 25 03 am](https://cloud.githubusercontent.com/assets/2916945/5526800/2c5b4696-89bd-11e4-9ff9-cf0b751bdd85.png)

My guess is that the jump from Windows 7 to 8 added the colors that @janey-p reported.

Here's what's displayed in Chrome:

``` html
<p>
    <span class="emoji emoji-sizer" style="background-image:url(bower_components/habitrpg-shared/img/emoji/unicode/1f44d.png)"></span>
</p>
```

Here's what's displayed in Firefox (W7):

``` html
<p>
    (hand symbol, probably from a unicode, my guess is this one: &#128077;)
</p>
```

It looks like what is happening is that the `:+1:` is being successfully converted to the emoji image, via bower_components, in Chrome and left as the unicode version in IE11 and Firefox, which means it's up to the OS to populate the icon with a built in font. Which would make sense why they are colored in 8, if 8 changed to a different, colored unicode font.

**Comment by crookedneighbor** [comment]
For reference, I believe [this is the js being used](https://github.com/iamcal/js-emoji) to convert the `:text:` to emoji.

**Comment by ghost** [comment]
For what it's worth -- the default (non-Chrome) browser on my phone (Android 4.3) displays the full-color "normal" icons. Everything else I have matches crookedneighbor's experience.

**Comment by lefnire** [comment]
FWIW, i've seen some activity on marked showing possible built-in support for emoji (maybe via a fork?) https://github.com/chjj/marked/pull/238 might be worth exploring

**Comment by janey-p** [comment]
Not sure how relevant the info is, but I just noticed that the DDT still shows the emojis correctly, just like the Emoji Cheat Sheet.

**Comment by Alys** [comment]
@janey-p The DDT uses a different library ([HenrikJoreteg/emoji-images](https://github.com/HenrikJoreteg/emoji-images)) but unfortunately it's not as simple as replacing one library with another. That library was chosen purely for ease of implementation, which is okay for a relatively low-traffic and simple tool, but for HabitRPG itself there's a lot of other considerations, such as short load times, consistency with software installation/update methods, caching, and probably a whole bunch of complex things that I don't even want to think about. :)  Which is not to say that there's anything wrong with that library, but it just might not be suitable for this particular usage.

**Comment by VikingRunner** [comment]
I don't know if this makes things more confusing or not, but I'm running IE 11 on Windows 7 Home, and while I'm currently getting flat black and white emoji there, up until about a week ago they were the regular, non-flat, colored version. I remember the emoji-cheat-sheet page I found being somewhat erratic: first I was able to see the emoji, then no images at all appeared for two days, then regular emoji again. But even when that page was showing no images, I still had standard emoji appearing in Habit. Up until, as I said, about a week ago when they switched to the black and white.

**Comment by Dewines** [comment]
FWIW, the emoji are their usual colourful selves in Firefox (v 23) running on Windows XP. I was  accessing Habit from the college where I work and thought, "Yay! They've fixed the emoji" but when I got home on my Windows 8.1 computer, they were sad and flat again.

**Comment by Alys** [comment]
It's possible that this issue has been fixed (or at least fixed for some people) by this commit made today: https://github.com/HabitRPG/habitrpg/commit/676562cfadd7b6721d054ccb18842933ec2f7e8c. Is anyone still seeing flat emoji or black-and-white emoji? Please reload the website before responding because that might make a difference!

**Comment by janey-p** [comment]
All's well on my end! :)

**Comment by kawunngg** [comment]
i also see colored emojis again! yay! (win 7, firefox)

**Comment by Dewines** [comment]
My first thought on logging in this morning was, "All the emojii are back!" The are in splendid colour again on my computer (Win 8.1 and viewed in Firefox).

**Comment by lemoness** [comment]
Confirmation from some users who've reached out on social media :)
