### ISSUE TITLE
Add colored border to active skill

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4399]
Originally from #4398 

After clicking on a skill (or spooky sparkles/snowball), it's not always apparent which skill you clicked on. Putting a border around the selected skill (maybe similar to the border that goes around the target task/user, but not green, since that signifies the target), would clarify this. I was thinking blue for the border, but am open to suggestions.

In addition to making it clearer all around, this will also help mobile users using the web app to tell when a skill has been activated and is awaiting a target (since the cursor is non-existent in mobile).

@lemoness and those with an eye for the aesthetics of the site, is this solution acceptable? If not, suggest alternatives and we'll change the title of the issue to reflect the one we go with.

**Comment by kangabell** [comment]
@crookedneighbor Currently when you hover over the MP area to select the skill, it changes from a blue to a yellow-ish color. I'd suggest that after selecting, that area remains yellow-ish.

**Comment by crookedneighbor** [comment]
@kangabell I think that's a good idea. Interested in doing it?

**Comment by kangabell** [comment]
@crookedneighbor sure! just getting started with running the app locally but will give it a shot.

**Comment by kangabell** [comment]
@crookedneighbor Seems like it might be a good idea to use angular to add a class to the item when it's active, but alas I don't really know angular. If someone could get that class in I could easily add the styling to it.

**Comment by crookedneighbor** [comment]
@kangabell Do you want to tag team it? You do the class and I'll do the angular stuff?

Or do you want to be coached through the Angular stuff? I'm up for either.

**Comment by kangabell** [comment]
@crookedneighbor Hey, yep. Here's the CSS: https://github.com/HabitRPG/habitrpg/pull/4486
