### ISSUE TITLE
Move Add new Habit/ToDo/Reward to top of lists

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#44]
I think it would be more efficient to move the add new list item field to the top of the list. This would be especially helpful for persons with lots of to dos to save them scrolling down whenever they want to add an item.

**Comment by wc8** [comment]
+1 maybe part of static header, so it always shows no matter where you are.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote here: [Add new at top/header](https://trello.com/card/add-new-tasks-at-top-header/50e5d3684fe3a7266b0036d6/126)
