### ISSUE TITLE
Reconnecting Bug

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#440]
I went away from the HabitRPG tab for like 10 minutes and it said on the top 'Offline - Reconnect'. Reconnect is a clickable link and I clicked on it, but it said the same thing (Offline - Reconnect). I did it a few times and it still said 'Offline - Reconnect'. Refreshing the page also didn't fix it - I had to close the tab and open a new one.

**Edit:** Duplicate of bug report #91; sorry :P I can't find a way to delete this post...

**Comment by lefnire** [comment]
There's a pretty nasty memory leak we're ever-battling #165. The node service has to restart periodically as a result, and it takes 1-2 minute to restart. During that time you'll get that message. Usually it will reconnect you when it's back online and sync the data back up, but your best bet during those times (until we fix that bug of course) is to just wait a bit, then refresh and keep chugging. Gonna close this ticket to keep followed up on #165
