### ISSUE TITLE
Wrong year in Winter gear descriptions (or continuity mistake?)

### ISSUE THREAD

**Issue by LordGrowl** [HabitRPG/habitica#4400]
The description in last year's winter gear says:

> Limited Edition 2013 Winter Gear

This year's winter gear says:

> Limited Edition 2015 Winter Gear

What happened to the winter of 2014?

(The problem exists in all the limited edition equipment for the rogue; I don't know about the equipment for the other classes.)

**Comment by crookedneighbor** [comment]
From @Alys in the tavern:

> @LordGrowl : It's deliberate. We're referring to the gear by a single year instead of 2014-2015, and the Winter season covers all of January but only a small amount of December, hence 2015 rather than 2014. 

@Alys and @paglias Should last year's strings be updated to 2014? Or just leave it alone?

**Comment by lefnire** [comment]
cc @sabrecat

**Comment by SabreCat** [comment]
I'm planning to update last year's strings.

**Comment by crookedneighbor** [comment]
Opened up an issue for entry level coders in habitrpg-shared:
https://github.com/HabitRPG/habitrpg-shared/issues/405

**Comment by lemoness** [comment]
For what it's worth, I like 2014-15 for clarity, but I may be overruled. It just feels weird to me to leave out one of the years.

**Comment by Alys** [comment]
Ah sorry, I thought it had been decided. 
I was editing the Winter Wonderland wiki page a couple of hours ago and was adjusting the years to use 2014 and 2015, instead of 2013-2014 and 2014-2015. It did feel odd to me then and I think there could be confusion. I'm now leaning towards keeping both years.

**Comment by lemoness** [comment]
Not at all your fault - I've been running around these past few days
because of Christmas and Chanukah, so it totally slipped under my radar until
I saw this ticket!

**Comment by crookedneighbor** [comment]
We got a pr to change the text from 2013 to 2014.
https://github.com/HabitRPG/habitrpg-shared/pull/406

Should I tell the contributor to change it to 2013-2014 and update the new gear to 2014-2015?

**Comment by SabreCat** [comment]
I prefer keeping it single years:
- It's more concise; item descriptions can get long!
- It lets all the Galas have a unified name convention
- You can refer to a given year's events as a group without ambiguity
- I like the forward-looking "model year" feel of starting the next year's
  Winter event in December, especially given the importance of New Year's to
  Habit

All that said, @lemoness has final word on the Galas, so I will object no
further if her preference remains!

**Comment by crookedneighbor** [comment]
I like @SabreCat's reasoning :+1:

**Comment by crookedneighbor** [comment]
Since we're discussing this here in stead of the shared repo, I'm re-opening the issue.

**Comment by LordGrowl** [comment]
Yay! My ticket is actually generating discussion. Always something good for the ego.

As for my own thoughts on the issue, I can't think of anyone who counts the seasons as: "Winter, Spring, Summer, Fall/Autumn". Most - at least in cultures in the Northern Hemisphere - would have been taught that they go in the order of "Spring, Summer, Fall/Autumn, Winter". After all, that's the reasoning behind why I thought there was a mistake in the first place, and the reason for my opening of this issue. At the moment, this looks very much like a case of trying to fix something that isn't broken.

The reasoning given by @SabreCat for the single year does make sense, though I'm split on the "New Year" point. After all the winter festivals I know of (Christmas, Hanukkah, Winter Solstice, etc.) all take place in December, i.e. before the turn of the new year. For me, it would be strange to have all these winter festivals taking place in 2014 and then having the winter gear to go with them described as being for 2015.

**Comment by crookedneighbor** [comment]
@lemoness do you have a decision for this? Do you want it `old_year-new_year`, `old_year`, `new_year` or something completely different?

We have two PRs pending using the `new_year` version.

**Comment by lemoness** [comment]
I don't know. Personally I like 2014-15 for the reasons listed and because
it has no ambiguity, but I can live with 2015 if that's being favored. It
just seems odd having the 2015 Winter Wonderland start in 2014.

Maybe we should do a poll?

**Comment by crookedneighbor** [comment]
I'd prefer it to be a single year. I don't care if it's 2014 or 2015, but I favor 2015.

**Comment by Alys** [comment]
I've seen text in the wiki that was confusing because a single year was mentioned for the Winter season. From a purely coding point of view, using just one year would make sense, but for all user-visible text I think we'll have less confusion and fewer questions if both years are mentioned (and if we do that it's probably best to also use both years in the code for consistency).

**Comment by lemoness** [comment]
Okay. I will let you guys decide what to do with the code, but I think I'm
going to go ahead and say that we should list both years. No preference
between 2014-2015 versus 2014-15.

**Comment by lemoness** [comment]
*list both years in places that the users will see it,such as wiki and
outfit descriptions.

**Comment by Alys** [comment]
Let's go with 2014-2015 in all user visible descriptions (e.g., in gear descriptions and on the wiki). That way if someone is searching for 2015, they'll still find it, whereas they wouldn't with just 2014-15.

Personally, I think that the code should also use both years for consistency and to avoid confusion, although we might want to introduce that guideline only from this point forward to avoid changing existing code.

**Comment by joshbDev** [comment]
I've submitted a Pull request to change the winter 2013 gear to winter 2013-2014 and winter 2015 gear to winter 2014-2015. it's this one: https://github.com/HabitRPG/habitrpg-shared/pull/427
