### ISSUE TITLE
Inconsistent text color in "you don't have any" Market messages

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4405]
Quick fix that should just require a one-line Jade tweak. The "you don't have any food or saddles" message in the Market is in black text, while all other similar messages there are in deemphasized gray text:

![2014-12-24 09_57_18-clipboard](https://cloud.githubusercontent.com/assets/4501321/5549636/46bb20e6-8b53-11e4-8e5e-b033fb86bab8.png)

The lower message should be in gray as well.

**Comment by ghost** [comment]
within the `<menu label="Food and Saddles (0)"...>...<p ng-show="foodCount < 1" class="muted">You don't have any food or saddles.</p>...</menu>`

**Comment by Alys** [comment]
@viejOMs That seems reasonable. Would you like to have a go at coding it on a local install and submitting a pull request? I believe the file to be edited is `views/options/inventory/inventory.jade` (note that it's Jade not raw HTML so the fix won't be exactly as you describe but the class you've found sounds like it'll be the right one). Feel free to ask questions if you get stuck at any point! And if you find out that you don't have time, that's fine. :) Just let us know and someone else can take this up.

**Comment by andyzinsser** [comment]
I'll take this one to use as my first contribution to this project. Should have a PR for you tonight.

**Comment by Alys** [comment]
@andyzinsser : I think viejOMs has already started looking into this. If they don't want to proceed with it, then we'd love to have your PR, but first please give them a couple of days to respond. If you'd like some other easy jobs to choose from, there's several marked with the [entry level tag](https://github.com/HabitRPG/habitrpg/labels/entry%20level%20coding%20%28text%20etc.%29).

**Comment by andyzinsser** [comment]
Apologies @Alys and @viejOMs, I jumped the gun and just submitted [PR #4423](https://github.com/HabitRPG/habitrpg/pull/4423).

I'll take a stab at some of the other issues later.

**Comment by crookedneighbor** [comment]
Whoops. I just merged it in. Didn't realize there were two people working on this.

**Comment by ghost** [comment]
oh, well, next time!
