### ISSUE TITLE
No levelup initiated

### ISSUE THREAD

**Issue by Pfeil** [HabitRPG/habitica#4409]
Long story short, I currently have 766/660 EXP.
I casted a few spells (burst of flames) to end a quest, which worked quiet well. Except that my level did not increase.

I started a new quest and casted burst of flames again, hoping that this would update my experience situation, but it did not. Also, reloading etc did not work. The error also appears on my mobile phone now, so it must be on the server.

user id:
    df576800-8a24-445c-97c2-457ef98ad66c

Browser: Firefox 34.0
OS: OSX Mavericks (up-to-date)

**Comment by SabreCat** [comment]
See #2143. Check off any task and you'll level up as usual.

**Comment by Pfeil** [comment]
Worked, thanks.
