### ISSUE TITLE
Broken Link on FAQ

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#441]
On the Frequently Asked Questions page, the question 'I'm going on vacation, how can I disable my Dailies?" has a broken link. It says 'See this screenshot' but it goes to a broken link on evernote.com. I think it can be fixed by just updating the link.

**Comment by wc8** [comment]
Thanks for reporting this. In the meantime:
To change which days a daily task is due, click the **Edit** (pencil icon) button. The **S**, **M**, **T**, **W**, **T**, **F**, **S** buttons represent days of the week. Clicking them will toggle between due (turquoise) or not due (grey).

**Comment by busterroni** [comment]
I knew that, I was just reading through the FAQ's when I was bored :P Thanks anyway :)

**Comment by Pandoro** [comment]
Once the community forum is up, we will make a bigger and fixed version of the FAQ and other things :) 

This should not be long, so hang in there for a bit :) 

Let us keep this open though in order not to forget it.

**Comment by rixx** [comment]
Was fixed and can be closed.

**Comment by lefnire** [comment]
ah yes, thanks @rixx
