### ISSUE TITLE
Protective Aura (protectAura) Skill Rebalancing (for `rebalancing-2014-12` feature branch)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4412]
As described in [Fix Overpowered Skills - Issue #3029](https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382), we are rebalancing many skills. This issue is specifically for Protective Aura (`protectAura`). [Current skill is defined here](https://github.com/HabitRPG/habitrpg-shared/blob/7fd4cebbdc531b6875fb0fbb687b89b66362ee67/script/content.coffee#L603).
#### Requirements:
- Keep scaling on CON only
- [x] Add diminishing returns ([diminishing returns function is defined here](https://github.com/HabitRPG/habitrpg-shared/blob/3de86f35cb244e5c3526a38d4b1c81274e9662ee/script/index.coffee#L101))
- [x] Make stronger
  - ~~Basic method (better methods welcome): change .15 to .3 in `member.stats.buffs.con += Math.ceil(user._statsComputed.con * .15)`~~
  - [x] Make stronger using diminishing returns parameters (https://github.com/HabitRPG/habitrpg-shared/pull/426)
  - [x] Maybe make stronger still by increasing the diminishing returns parameters
  - [ ] Maybe make stronger while making the effects of the skill random across a range of values, but with values in the middle of the range more common than the extremes (@Timoteo32 ?)
  - Important comments for Protective Aura start at  https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-65252020 and are all marked with **_{alys: PROTECTIVE AURA}**_ (they keep going down past some other discussions so make sure you see them all). However all future discussion about this skill should go into _this_ issue.
#### Notes:
- **Optimise for levels 1-100 only**. Levels after 100 will give no additional attribute points. So the highest Stat you could have is around 250 (level /2 + 100 attribute points + 50 perfect day bonus + 50 from the best gear)
- Do not allow the skill to give a negative buff.
- If appropriate, consider re-using the [calculateBonus](https://github.com/HabitRPG/habitrpg-shared/blob/4a7dcfc2bb5bf6b11ab5a896e052ae6ef615d3a9/script/content.coffee#L448) function instead of a custom function for this skill (search that file for examples of its use).
- Current skills and sample effects can be seen at:
  - [Skills Summary](http://habitrpg.wikia.com/wiki/Skills_Summary)
  - [Data Display tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) "Skills and Buffs" section
- Do pull requests to the `rebalancing-2014-12` feature branch, not to the `develop` branch (ask in the comments here if you're not sure how):
  - [HabitRPG/habitrpg at rebalancing-2014-12](https://github.com/HabitRPG/habitrpg/tree/rebalancing-2014-12)
  - [HabitRPG/habitrpg-shared at rebalancing-2014-12](https://github.com/HabitRPG/habitrpg-shared/tree/rebalancing-2014-12)

**Comment by Alys** [comment]
Verabird's changes in https://github.com/HabitRPG/habitrpg-shared/pull/426 caused the skill to be stronger, except for players who are buffed well over normal level 100 ranges (for them, the skill is much weaker, which is good):
Level 15 player with no buffs will have 4 CON added (previously 2).
Level 50 player with no buffs and all points to CON will have 28 CON added (previously 12).
Level 100 player with perfect day buff and all points to CON will have 50 CON added (previously 30).
Level 100 player with CON already buffed to 1000 CON will have 85 CON added (previously 180); if already buffed to 5000, will have 100 CON added (previously 780).

This seems good - certainly not too strong. In fact it could perhaps be made stronger still because CON has a small effect on damage taken. Comments from Healers welcome.

**Comment by Alys** [comment]
Verabird's latest changes in https://github.com/HabitRPG/habitrpg-shared/issues/433 caused the skill to be stronger still:
Level 15 player with no buffs will have 7 CON added.
Level 50 player with no buffs and all points to CON will have 55 CON added.
Level 100 player with perfect day buff and all points to CON will have 100 CON added.
Level 100 player with CON already buffed to 1000 CON will have 168 CON added; if already buffed to 5000, will have 193 CON added.

**Comment by Mihakuu** [comment]
I get that healers are support class and don't deal damage directly to a boss but is there a way to have this skill help with boss damage too? Since boss damage doesn't use con this skill does nothing for the party as a whole and makes the healer have to slide in all day to heal after crons

**Comment by crookedneighbor** [comment]
:+1: to that.

**Comment by crookedneighbor** [comment]
Actually, I misread @Mihakuu I'm in favor of protective aura actually reducing boss damage to the party, not causing damage to the boss.

**Comment by Alys** [comment]
Note that this should not be done (if it is done) by allowing CON to affect boss damage. Players with high CON could leave most of their Dailies undone, knowing they will be safe from too much damage, while low-CON players are killed. Any changes to boss damage should be applied equally to all participants. (Not saying CON is what you were suggesting; just noting this here.)

**Comment by Mihakuu** [comment]
@crookedneighbor that's what I meant. Sorry if what I said was confusing. I just wanted to point out the skill is mostly pointless unless you've a party that misses dailies left and right and you don't boss battle. As it stands there's no way to preemptively reduce boss damage so if someone misses checking in then the healer gets to take a hit, even killing themselves, to save the party before they log in.
It's okay. I was just seeing if were possible.

**Comment by deilann** [comment]
I think it is possible... make it a separate kind of buff specifically to
reduce boss damage by a certain percentage

**Comment by Alys** [comment]
ping @lemoness

**Comment by lemoness** [comment]
I would be in favor of that! It fits in with the Healer's logical role, and
right now, it's a class that mostly cleans up messes instead of preventing
them.

However, if this can't be done quickly, I would rather not delay the class
changes that we are rolling out. If we can get it in, that's awesome; if
not, let's not hold things up for that.

**Comment by crookedneighbor** [comment]
I agree. Con shouldn't be a factor when calculating boss damage.

**Comment by Alys** [comment]
I think doing it quickly is unlikely. Let's leave it out of this project, but it's a nice idea and perhaps we should brainstorming ideas for it.

**Comment by Alys** [comment]
@Mihakuu you might want to add to Trello your suggestion about having a different type of attribute that can reduce boss damage, fairly across all party members.

I'm closing this issue now since the primary purpose of it has been achieved.
