### ISSUE TITLE
Ethereal Surge ('mpheal') Skill Rebalancing (for 'rebalancing-2014-12' feature branch)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4414]
As described in [Fix Overpowered Skills - Issue #3029](https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382), we are rebalancing many skills. This issue is specifically for Ethereal Surge (`Ethereal Surge`). [Current skill is defined here](https://github.com/HabitRPG/habitrpg-shared/blob/7fd4cebbdc531b6875fb0fbb687b89b66362ee67/script/content.coffee#L466).
#### Requirements:
- [x] Add diminishing returns, configured to never give more than 29 MP ([diminishing returns function is defined here](https://github.com/HabitRPG/habitrpg-shared/blob/3de86f35cb244e5c3526a38d4b1c81274e9662ee/script/index.coffee#L101))
- [x] Remove the 25 MP cap
#### Notes:
- **Optimise for levels 1-100 only**. Levels after 100 will give no additional attribute points. So the highest Stat you could have is around 250 (level /2 + 100 attribute points + 50 perfect day bonus + 50 from the best gear)
- If appropriate, consider re-using the [calculateBonus](https://github.com/HabitRPG/habitrpg-shared/blob/4a7dcfc2bb5bf6b11ab5a896e052ae6ef615d3a9/script/content.coffee#L448) function instead of a custom function for this skill (search that file for examples of its use).
- Current skills and sample effects can be seen at:
  - [Skills Summary](http://habitrpg.wikia.com/wiki/Skills_Summary)
  - [Data Display tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) "Skills and Buffs" section
- Do pull requests to the `rebalancing-2014-12` feature branch, not to the `develop` branch (ask in the comments here if you're not sure how):
  - [HabitRPG/habitrpg at rebalancing-2014-12](https://github.com/HabitRPG/habitrpg/tree/rebalancing-2014-12)
  - [HabitRPG/habitrpg-shared at rebalancing-2014-12](https://github.com/HabitRPG/habitrpg-shared/tree/rebalancing-2014-12)

**Comment by Alys** [comment]
Skill now works roughly the same as it used to but uses standard diminishing returns instead of a hard cap.

**Comment by davidmanheim** [comment]
@Alys - I think there is still a critical flaw in the current implementation, relating to party size - especially for large parties (5+ players, but especially for 10+ or more). Specifically, if a party has 2 mages that have int greater than 150, they can get infinite mana; each spends 30 mp to give all 15+ more mp, which can be done around level 50 with perfect days. (Similarly, three mages with int 100+, with a bit more coordination.) This leads to instant kill of bosses, which seems very broken, and it can happen without really trying to break the game.

The easy fix here seems to be to have the total mana gained scale logarithmic-ly with party size: increasing the size of the party will reduce the per-member hp gain.

An example; if the skill currently gives X mana per person, change this to ln(party size+2) mana total. This makes the skill useful, but fixes this issue, largely.

Amounts:

| Party size | Mana Gained, Total | Mana Gained, ea. | Old mana gained, Total |
| --- | --- | --- | --- |
| 1 | 1.1x mana | 1.1x mana | x |
| 2 | 1.4x mana | 0.7x mana | 2x |
| 3 | 1.6x mana | 0.5x mana | 3x |
| 4 | 1.8x mana | 0.4x mana | 4x |
| 5 | 1.9x mana | 0.4x mana | 5x |
| 10 | 2.5x mana | 0.25x mana | 10x |
| 20 | 3.1x mana | 0.15x mana | 20x |

To make it clear, you can leave the current cap in place; the max for a single player party would be 27.5, and for a 5 player party, it would give each player ~10 mana, which is OK, but requires more than 3 mages (of 5) to break the system, or in a 10 player party, gives ~6 mana, which requires more than 5 mages working together to break it.

**Comment by Alys** [comment]
@davidmanheim I definitely understand what you're saying, and your proposal is clever, but I am reluctant to increase the code complexity to the extent required for this. Currently, all skill calculations are done using only the caster's own stats, which is simple and fast. For a skill to change based on party size, we'd need to extract party size from the database each time the skill was cast, and while that seems like an easy enough thing, I would really prefer that we didn't have the extra code and extra processing required for this. I am concerned about an increased possibility of bugs and unexpected behaviour.

One source of concern is that in the database, a party object can contain UUIDs for players who have abandoned the game (deleted accounts, or just players who never log in any more). This would unfairly reduce the mana given to the party. This isn't a rare situation and the code required to work around it would be still more complex.

It would also increase the difficulty of understanding the skill. We'd get more questions about how the skill works, and probably bug reports ("My stats haven't changed but suddenly I am giving my party mates less mana!"). I am very reluctant to make changes that make the system seem more complex, unless there is a very good reason for it. 

With the changes being made to other skills, having a lot of mana will stop being as serious as it is currently. It won't be possible to vastly boost stats (the worst problem we have related to skills) and even the Mage's attack skill will be weakened.

It will still be possible to kill a boss in one day, but I don't think that's a serious problem. For a party keen to collect all the quest pets, rapid boss death is an advantage. You can run a new quest every day (happier players, more gems spent). For parties that want quests to last longer, they can ask Mages and Warriors to not one-shot the bosses.

I am interested in hearing contrasting viewpoints to all of this, but at the moment I feel strongly that bringing party size into the calculations will create more problems than it solves.

**Comment by davidmanheim** [comment]
@Alys - That seems like a fair point. 

Despite that, I definitely think we need to do something to decrease this impact of the spell, if only by limiting the total mana gained by the spell per day (seems like a harder hack) or something similar. 
The idea of having this level of quick kills is difficult; I could create a party that single round killed a quest boss in the game every a single day, just by coordinating 2 mid level players, and never taking damage at cron due to missed dailies. That seems like a real problem with the mechanics - it makes the game with quests boring.

**Comment by Alys** [comment]
I think for that level of hack, if it makes the game boring, the best solution is to not do it. When you are talking about coordinating players to that extent, it is a problem that can be solved by deciding to stop coordinating. We are more concerned with hacks that affect players without their permission, such as buffs that increase their stats too much. If a party of two Mages wants to get through one, or even two, quests each day (possible with staggered crons), let them. 

Never taking damage from missed Dailies is a choice that the party can make, and they can make it in other ways too such as by using checklist items to prevent incomplete Dailies from doing any damage. That level of "cheating" is not something we usually try to control.

**Comment by davidmanheim** [comment]
@Alys We've done that, but I still feel it's worth optimizing the skill so it can be used better, without taking undue toll on the servers. (Our party banned using the skill already.)

**Comment by Alys** [comment]
Remember that many of the other skills have had their effects reduced by this project. This means that mana in general will have less effect than it used to. I would like to see how all the new skills play out together before making Ethereal Surge more complex. If it turns out (as I think it will) that the only remaining "abuse" is to instant kill bosses, then I really don't think it will need to be changed, since that's a desirable feature for some and an avoidable issue for others.
