### ISSUE TITLE
[Suggestion] Goals

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#442]
I'd like to suggest a 'Goals' section. It would be similar to 'Todos' but it wouldn't be something you do, it would be something you're pushing yourself to do. For example, a goal I would have is that I want to get a grade of a B or higher on my upcoming French quiz. If I _do_ get a grade of a B or higher I'd check if off. If not, I would X it off. This wouldn't be a Todo because it's not something that I have to do but something that I want to urge myself to do.

**Comment by lefnire** [comment]
vote on [this trello](https://trello.com/card/habit-goals/50e5d3684fe3a7266b0036d6/66) (type 'v')
