### ISSUE TITLE
Can't cancel monthly subscription to buy block subscription

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#4420]
I tried to cancel my monthly subscription (which I purchased with a gift card and think the gift card ran out) and I wanted to purchase the 12-month block subscription.  When I try to cancel, I only get a {"err":"Cannot read property 'current_period_end' of null"} message.  Please assist.

_edit by admin:_
## What to do if you experience this bug:

**Add a comment here. Include your Unique User ID from [Settings -> API](https://habitrpg.com/#/options/settings/api).**

**Comment by Alys** [comment]
Please tell us your unique user ID. You can see instructions for finding it here: https://github.com/HabitRPG/habitrpg/issues/2760 (if you need to find it again in future, Help -> Report a Bug will take you there).

**Comment by Memry** [comment]
My user ID is e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by Alys** [comment]
Can you tell us exactly what point in the process you get that message? It would probably help if you could describe step-by-step what you did (e.g., went to Settings -> Subscription, clicked on "Cancel Subscription" button, .... ) up until the point where the error occurred. Please also drag-and-drop a screenshot of the error into a comment here. Also tell us which browser you're using and which OS. 

Depending on what that shows, we might ask you to try this in Chrome with the Developer Console open, but we can talk you through that later if needed.

FYI to devs:

```
    "purchased": {
        "plan" : {
            "customerId" : "cus_xxxxxxx",
            "dateCreated" : ISODate("201x-xx-xxTxx:xx:xx.xxxZ"),
            "dateUpdated" : ISODate("2014-12-01T14:39:58.177Z"),
            "paymentMethod" : "Stripe",
            "planId" : "basic_earned",
            "consecutive" : {
                "trinkets" : x,
                "gemCapExtra" : x,
                "offset" : x,
                "count" : x
            },
            "mysteryItems" : [ ],
            "gemsBought" : x,
            "extraMonths" : x
        },
```

All the 'x' values appear normal.

The only place in the codebase where current_period_end appears is here: https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/payments/stripe.js#L74

**Comment by Memry** [comment]
OS: Windows 7
Browser: Chrome

I clicked on the gem icon.  In the popup box I selected "Cancel
Subscription".  A popup box asked me to confirm.  When I confirmed, the
error message came up.  I have attached the screenshot of the error message.

I tried the same thing going to Settings, Subscription, and selecting
"Cancel Subscription" from the screen.  Same result.

**Comment by crookedneighbor** [comment]
@Memry Github won't displsy images attached to an emsil. Would you mind visiting this issue in a web browser and re-uploading the screenshot?

**Comment by Memry** [comment]
[image: Inline image 1]

**Comment by Alys** [comment]
Memry, that image still hasn't worked. When you drag the image into a comment here, you can Preview before submitting to make sure it's appearing correctly.

**Comment by Memry** [comment]
It was appearing correctly in the email reply.  Is there somewhere else I'm
supposed to be?

**Comment by Alys** [comment]
Please visit this issue in a web browser and drag the image into a comment here. As @crookedneighbor explained, GitHub won't display images attached to an email (and an inline image in an email is still an attached image).

**Comment by Memry** [comment]
Here is where?  I'm getting all these notifications via email.

**Comment by Memry** [comment]
Ah! Here is here.  Now I've found you.  Sorry.  I was confused. Here you are.

![memry](https://cloud.githubusercontent.com/assets/1495809/5566079/8fc06652-8f63-11e4-9c81-b3a7c4ca96c8.jpg)

**Comment by crookedneighbor** [comment]
Just edited out the image, didn't realize that it'd display an API token. I assume that API token was for Memry's user, if it was not, and it was for stripe instead, I'm not sure why we're exposing an api token for stripe that a user can see in the url.

Once this is sorted out, we'll want to issue you a new API token.

**Comment by crookedneighbor** [comment]
ping @lefnire

**Comment by Alys** [comment]
@Memry, I've assigned a new API Token to you. If you were using your UUID and API Token in any third-party applications, you will need to get the new token from HabitRPG's Settings -> API screen.

Blade, it was Memry's token.

I've put the image back into Memry's comment.

Memry, in your Chrome browser, please reload whatever HabitRPG page you are on. Then open the JavaScript console by doing Control-Shift-J. Right-click or Ctrl-click anywhere in the Console and choose Clear Console from the context menu that appears. Then click on the Gem icon. In the popup box, select "Cancel Subscription", then confirm it. The JavaScript console will probably now display error messages. Copy the entire set of messages from it to your clipboard (you will probably need to scroll in the console while selecting to make sure you get all of the messages). Paste them into a comment here.

**Comment by Memry** [comment]
This is the image of what came up.  There was nothing in the console.  I
did edit the url to remove my token this time.  (I hadn't read it to
realize it included my token before, either.  Thanks for noticing and
changing it before).  Please note that I seem to be having some problems
with habit this morning.  It has been telling me "no user found" since late
last night (about 7 hours ago).  That would be right about the time you
changed the API token.  I do not believe I have been using my API token in
any third party applications.  I have not linked my habit with anything but
GitHub, and I'm not sure I've linked them.  So I don't know why I would
suddenly be having an issue.
[image: Inline image 1]T

OK, so I decided maybe I needed to log out and log back in.  I did, and
followed your instructions again.  And this is what happened. (Note: my no
user found error has gone away completely.  Habit is working normally again
(except for this issue).  I gave you an image because there are no messages
in the console.
Again I removed the token from the URL before taking the snapshot.
[image: Inline image 3]

**Comment by Memry** [comment]
Ooops, working in the wrong screen.  Adding the two images here.
First try:
![image](https://cloud.githubusercontent.com/assets/7385423/5568477/fc4ca590-8f10-11e4-8939-540264e1bc9f.png)
Second try:
![image](https://cloud.githubusercontent.com/assets/7385423/5568479/0d7c16ac-8f11-11e4-89ea-88bd2a9f1fb6.png)

**Comment by deilann** [comment]
You're attaching the images via email again, so none of us can see them.

**Comment by Memry** [comment]
Fixed the image already.  Sorry. The two screens are very similar in appearance, my email and github.  My bad.

**Comment by Memry** [comment]
Any new suggestions?  I would really like to get my annual subscription in while the sale is still on.

**Comment by Alys** [comment]
@lefnire any ideas? See my comment near the top for this user's data, which looked normal to me.

**Comment by lefnire** [comment]
I'll check into this tomorrow

**Comment by Memry** [comment]
Thanks.

**Comment by lefnire** [comment]
Ah, I've seen this before. Your subscription was canceled on Stripe's end due to multiple failed payments ([email me](mailto:tyler@habitrpg.com) for deets, so we can keep sensitive data to email). We'll need to code in a webhook of sorts to get notif'd on Stripe subscription cancellations. In the meantime, I'll go ahead and cancel the subscription on the HabitRPG side manually. You shouldn't have been billed since 5/5, let me know otherwise

**Comment by Memry** [comment]
Thank you.  It worked.

**Comment by ghost** [comment]
I am having the same issue with canceling my subscription.  I am clicking "Cancel Subscription" in the Settings menu, I get a pop-up confirmation, I click confirm, and then I get the same error message that Memry got.

![screen shot 2015-01-08 at 9 47 40 pm](https://cloud.githubusercontent.com/assets/10458692/5675292/41ea2466-9780-11e4-88fa-dee661bab9ac.png)

User ID: 20622df2-a733-4e7a-a106-1b3b576aa39d
OS: X Yosemite
Browser: Chrome

**Comment by crookedneighbor** [comment]
@annabsheff please [email lefnire](mailto:tyler@habitrpg.com) directly to work this out.

**Comment by ghost** [comment]
Thank you, @crookedneighbor.

**Comment by lefnire** [comment]
FYI devs, the `current_period_end` error means the account was canceled on Stripe's end (most commonly from the cases I've seen, due to too many failed charges); however, the cancellation never hit Habit's server, since we don't have webhooks setup to listen for such an event. In any case, feel free to keep sending them my way if it makes you too nervous to handle yourselves - but the fix'em query is:

`db.users.update({_id:UUID},{$set:{'purchased.plan.dateTerminated':new Date(MAYBE_A_WEEK_FROM_NOW)}})`

**Comment by Alys** [comment]
Oh cool, an easy fix! I'll update the instructions at the top of this issue to say they should just comment here.

**Comment by heteroerectus** [comment]
Same problem here, user ID is 835ca0fb-2466-4b5d-9096-91f07463f410

**Comment by Alys** [comment]
@heteroerectus Your recurring payments were cancelled by the credit card processing company we use (Stripe) two weeks ago because it had been unable to extract a payment from your card since April, and that's why you were unable to cancel it yourself. I've applied the cancellation to your HabitRPG account.

**Comment by equeslilia** [comment]
Same bug. My ID is c62b1e9e-4631-418b-b624-cc53e215954d

**Comment by Alys** [comment]
@equeslilia Same reason, same fix done.

**Comment by Snellopy** [comment]
G'day, my Vietnamese credit card expired in September, but due to the joys of bureaucracy coupled with incompetence on the bank's part, I've only just now received the replacement. I'm getting the same error message, my ID is 33991e0a-de55-4986-ac81-af78491a84de. Thanks for all your help, both here and on Habitica in general.

**Comment by Alys** [comment]
@Snellopy Fixed! You should be able to resubscribe now. Comment here if you can't. Thank you very much for your support!
