### ISSUE TITLE
No description for Ski-sassin Parka in Equipment and Seasonal Shop pages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4424]
[As discovered by @goldfndr](https://github.com/HabitRPG/habitrpg-shared/issues/415), the Ski-sassin Parka is on display in the Seasonal Shop (and on the normal Equipment page if you own that item) but it doesn't have the expected +15 PER description.

This would be a good task for a new programmer! Hint: armorSpecialSkiText in a script in the habitrpg-shared repository. Post here if you'd like to work on it, and don't be reluctant to ask for help if you have trouble compiling and testing on your local install.

![screen shot 2014-12-27 at 4 11 26 pm](https://cloud.githubusercontent.com/assets/1495809/5560599/2030040e-8de3-11e4-9ef1-d7cae5081dad.png)

**Comment by Sporax** [comment]
I'd like to work on it, I'm new to contributing and would love to give it a shot.

**Comment by Alys** [comment]
Fantastic, thank you!

You'll find some useful information in [Guidance for Blacksmiths](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths) and [Setting up HabitRPG locally](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally), and ask here for help if you need it!

**Comment by Sporax** [comment]
So I started the setup and I'm a little confused at step 3 of setting up HabitRPG locally: it says to update SMTP user and password and I'm not sure about what to put there.

**Comment by crookedneighbor** [comment]
@Sporax i think those instructions are a might bit misleading. Email only works when the environment is set to production, so you can safely ignore that step for now.

**Comment by crookedneighbor** [comment]
Actually, if I remember correctly, Vagrant might bark at you if you leave them as the default values. So if you're using Vagrant, just change the username and password values to anything but the default. If you have a gmail account, your smtp settings would look like this:

```
"ADMIN_EMAIL": "youremail@gmail.com",
"SMTP_USER":"youremail@gmail.com",
"SMTP_PASS":"your-gmail-password",
"SMTP_SERVICE":"Gmail",
"SMTP_HOST":"smtp.gmail.com",
"SMTP_PORT": 587,
"SMTP_TLS": true,
```

SMTP is a protocol for sending emails, but like I said, the system shouldn't have to make use of that if your config is set to work in development mode instead of production (which is the default).

**Comment by Sporax** [comment]
Ok thanks, I filled it up anyway with email details earlier. Just wanted to make sure about that. I have another question: I set up a local HabitRPG, but can't login as it says either the username or password is incorrect, even though my credentials are correct (I tried many times)

**Comment by crookedneighbor** [comment]
The database you're using in your local install is going to be different from the one used on the site, so you'll have to create a new user.

This will be useful, because you can manipulate and test things without affecting your real user.

**Comment by Sporax** [comment]
Alright, I fixed it in the local HabitRPG, the only change was for notes:armorSpecialSkiText to be changed to notes:armorSpecialSkiNotes for ski under the habitrpg-shared.js file; it gives a description to the armor now. What should I do next? Do I need to upload the file?

**Comment by Sporax** [comment]
![screen shot 2014-12-28 at 3 23 50 am](https://cloud.githubusercontent.com/assets/10322112/5562427/07b401d8-8e41-11e4-86a4-f8f413247bc1.png)

**Comment by Alys** [comment]
The habitrpg-shared.js file is actually a compiled file and shouldn't be edited manually (your changes would be overwritten when it was compiled on the server). If you grep through that repo for armorSpecialSkiText, you'll see the file that habitrpg-shared.js is compiled from.

For compiling, look through http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally and http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths for information about grunt.

Ask if you can't find what you need after a bit of hunting.

When changes are ready to be reviewed by others, you can push them to your own github repo and then do a pull request.

**Comment by Sporax** [comment]
I used grep on the repository and came up with a file public/bower_components/habitrpg-shared/script/content.coffee I assume this is the file that habitrpg-shared.js is compiled from. I don't have any apps that can edit this file format, is there something I'm doing wrong?

**Comment by crookedneighbor** [comment]
`.coffee` is for CoffeeScript. It should just be a text file, so it should open in most text editors. What text editors are you using?

**Comment by Alys** [comment]
The bower_components directory is also one that you shouldn't edit because those files are copied (or better, symlinked) from the habitrpg-shared repository. Do you have a local copy of that repo as well as the main habitrpg repo? It's important to have both. See the section "Work with habitrpg-shared" in http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths - it's usually worth going through all of that document and http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally to make sure you have everything covered. It's a bit tedious, but it does make everything run more smoothly.

**Comment by Sporax** [comment]
@crookedneighbor I have Text Wrangler and the default text editors that mac comes with.

**Comment by Sporax** [comment]
@Alys I do have a local copy of both the shared repo and the habitrpg repo. I also read all of Guidance for Blacksmiths and Setting up HabitRPG locally. I followed the instructions in Work with habitrpg-shared, but I'm confused about what it really does and what I'm supposed to edit to change the description of the parka without editing either the habitrpg-shared.js file or the bower_components directory. Could I get another hint, please?

**Comment by Alys** [comment]
No worries. :)  The habitrpg-shared repo should be in your local install under `habitrpg/node_modules/habitrpg-shared`,  where `habitrpg/` is the root directory for the main [habitrpg](https://github.com/HabitRPG/habitrp) repo. 

Under `habitrpg/node_modules/habitrpg-shared`, you'll see a `script` directory containing index.coffee and content.coffee. Both of those are important files and are the ones you should edit directly. `grunt` is used to compile them into `dist/habitrpg-shared.js` in that same repo (it also compiles other files). One of those coffee files is the file to edit for this particular issue (I can't recall which one, but a quick grep should tell you - ask again if it doesn't).

The files under bower_components should never be edited manually. They'll be automatically updated as needed as long as you followed the installation procedure in http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally (and it sounds like you have).

Any time you come across any file (for any project) that you need to edit but that doesn't open by default in any application, it's always worth initially assuming that it's a text file and using a plain-text editor for it. In some cases, that won't work and the file might look corrupted (e.g., if it's a binary file) but as long as you don't save the file in the text editor, you can't do any harm. But beware of text editors that save files without asking! 

Feel free to ask for clarification if any of this doesn't make sense!

**Comment by Sporax** [comment]
Thanks that cleared it up. I also realize that I hadn't previously forked the habitrpg-shared repo. 
I did the fix in `/habitrpg/node_modules/habitrpg-shared/script.coffee`, I also compiled it although when I went to localhost:3000 in chrome (as usual) the page doesn't load (it's just a white screen)

**Comment by Sporax** [comment]
There is a problem while compiling the local HabitRPG. When I use the command `npm start` then the console says `module.js:340 throw err`. Is there any way to reset the local HabitRPG? I tried by deleting the `habitrpg` folder and reinstalling using the instructions on the Blacksmith and setting up locally page, but keep coming up with the same problem. Can anyone help me here?

**Comment by crookedneighbor** [comment]
Can you post the full error?

**Comment by Sporax** [comment]
![screen shot 2014-12-28 at 10 03 21 pm](https://cloud.githubusercontent.com/assets/10322112/5564335/7ad956bc-8edd-11e4-8e25-fca4ed1376da.png)
This has repeated itself for the last few hours

**Comment by crookedneighbor** [comment]
Can you check your node_modules folder and make sure the pageres directory exists? If it does not, run `npm install` again. If it does, delete it and run `npm install`.

**Comment by Sporax** [comment]
I'm still getting an error: 
![screen shot 2014-12-29 at 2 40 46 pm](https://cloud.githubusercontent.com/assets/10322112/5567346/cec3bd40-8f68-11e4-92e4-1fa63859bd55.png)
Sorry about this, I seem to have blundered a simple task...

**Comment by Alys** [comment]
That's okay, sometimes local installs just go wildly wrong. :)

In my experience, it's usually faster and more reliable to delete everything and start again completely from scratch. I know that might seem overwhelming, but we could fix this current problem, and then find another one, and then another... Starting from scratch can avoid a lot of pain. 

So, what I recommend is, delete your habitrpg directory and everything under it. If you are using Vagrant, destroy the virtual machine and delete the folder that all its files are contained in. Then go to http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally and start from the top, proceeding carefully through each step. As soon as you find something you don't understand, or something that doesn't seem to work properly, stop and ask us for help here - that's important because proceeding past an error can lead to other problems later.

If you're using Windows, I do recommend following the Vagrant process rather than the native Windows process. I think it's likely to run more smoothly.

**Comment by Sporax** [comment]
I deleted and reinstalled using the Unix install instructions, but errors keep coming up when I run the `npm start` command: here is the full log
![screen shot 2014-12-29 at 10 37 04 pm](https://cloud.githubusercontent.com/assets/10322112/5570666/78dfe618-8fab-11e4-825f-e6ee06e9b86a.png)

**Comment by Alys** [comment]
I suspect that something has failed on this step: "11. Ensure that Mongo is running". Were there any error messages or warnings when you started it?

**Comment by crookedneighbor** [comment]
That is exactly the error I get when I forget to start the `mongod` process first in a separate window.

![screen shot 2014-12-29 at 11 37 12 am](https://cloud.githubusercontent.com/assets/2916945/5570937/0b515c1e-8f4f-11e4-94e0-0354acc5b6d5.png)

**Comment by Sporax** [comment]
I tried again with `mongod` in a separate window, but the errors are still there. Do you need to use                 `mongo habitrpg` and `show collections` in a separate window before using `mongod` as well? And does `mongod` have to be used in the `habitrpg/` directory?

**Comment by taldin** [comment]
Have you recompiled the habitrpg-shared directory since you made the change?   You're on Mac, looks like, so I don't know if that's the problem, but when I run into that on Windows, it means I forgot to run grunt on the habitrpg-shared module.

**Comment by Alys** [comment]
`mongo habitrpg` and `show collections` are just for use if you want to manipulate the database data or check that the database has been set up correctly. They're not necessary before you start HabitRPG for the first time (and in fact they probably won't work since I think the database wouldn't have been created yet). When you run `mongod` are there any errors?

Note that mongod is the database server so you need to leave it running all the time that you are using your HabitRPG local install. So, for example, you would run it in a terminal window of its own, and not kill it with control-C until your coding and testing session is finished.

**Comment by crookedneighbor** [comment]
Yeah, we need to make a distinction between `mongo` (no d) which is the shell interface for interacting with the database directly, and `mongod` that is the database server. It's possible you've started `mongo` in another window instead of `mongod`.

**Comment by Sporax** [comment]
There aren't any errors while running `mongod`, though when I run `npm start` then this happens at the same time as the errors:

> 2014-12-29T23:38:53.106+0530 [initandlisten] waiting for connections on port 27017
> 2014-12-29T23:39:51.716+0530 [initandlisten] connection accepted from 127.0.0.1:61251 #1 (1 connection now open)
> 2014-12-29T23:39:51.734+0530 [conn1] end connection 127.0.0.1:61251 (0 connections now open)
> 2014-12-29T23:39:53.160+0530 [clientcursormon] mem (MB) res:48 virt:2811
> 2014-12-29T23:39:53.160+0530 [clientcursormon]  mapped (incl journal view):320
> 2014-12-29T23:39:53.160+0530 [clientcursormon]  connections:0
> 2014-12-29T23:40:11.189+0530 [initandlisten] connection accepted from 127.0.0.1:61252 #2 (1 connection now open)
> 2014-12-29T23:40:11.205+0530 [conn2] end connection 127.0.0.1:61252 (0 connections now open)
> 2014-12-29T23:40:26.427+0530 [initandlisten] connection accepted from 127.0.0.1:61254 #3 (1 connection now open)
> 2014-12-29T23:40:26.442+0530 [conn3] end connection 127.0.0.1:61254 (0 connections now open)

I'm using `mongod` in a separate window, not confusing it with `mongo`. I had thought that you needed to use `mongo` in a separate window as well as `mongod`, but that's been clarified now.

**Comment by taldin** [comment]
Actually, wait, hang on.  If you're using Vagrant, have you been destroying old copies (vagrant halt)?   That can cause those error messages too.

**Comment by Sporax** [comment]
I have been destroying the old copies using virtialbox for what I started with vagrant, I didn't use a vagrant halt command.

**Comment by Alys** [comment]
Sporax, are you using the [Vagrant instructions](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Vagrant) or the [Unix instructions](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Unix) in Setting up HabitRPG locally? If you're using a Vagrant VM for HabitRPG development, you definitely should not be following the Unix instructions as well, and all of your commands such as `mongod` and `npm start` should be run from within the virtual machine, not in terminal sessions that use your Mac directly.

**Comment by taldin** [comment]
Yeah, one of the things I did/am doing with the rewrite is splitting those up. :3

**Comment by Sporax** [comment]
I initially installed using the Vagrant and Unix instructions, and the local compilation worked using Vagrant. Now I installed using the Unix instructions. Should I be using Vagrant to set it up instead?

**Comment by Alys** [comment]
You definitely need to chose just one set of instructions - either Vagrant or Unix, not both. They are different processes, just as Windows is different from Unix.

Unless you are experienced with installing and configuring software on your Mac using command-line tools, it's probably best that you use the Vagrant instructions only. In theory, following the Vagrant instructions carefully should leave you with a fully working installation, with no tweaking needed. In practice, it doesn't always work that way. :)

So, assuming you want to use Vagrant, start from scratch again. Destroy and completely delete any existing virtual machines you might already have. Delete the habitrpg repository from your Mac. Then go to http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Vagrant (i.e., "Instructions by Operating System" -> "Vagrant") and follow the steps from the top. As soon as you find something you don't understand, or something that doesn't seem to work properly, stop and ask us for help here - that's important because proceeding past an error can lead to other problems later.

**Comment by Sporax** [comment]
I finally got it! I installed on a separate computer running Ubuntu using the Unix install, and had the same problem with the `mongod` command. Apparently other people had the same problem and used `sudo killall -15 mongod` to end the process, and that made it work.

**Comment by Sporax** [comment]
I fixed the line in the `/habitrpg/node_modules/habitrpg-shared/content.coffee` by changing `notes: t('armorSpecialSkiText'` to `notes: t('armorSpecialSkiNotes'`, but on the local HabitRPG there is no change to the ski-sassin parka description. Is there something else I have to edit for that?

**Comment by deilann** [comment]
Did you run `grunt` in the shared repo to compile it?

**Comment by Sporax** [comment]
Do you mean `grunt run:dev`?

**Comment by deilann** [comment]
No, I mean use your command line in the habitrpg-shared directory and run
`grunt` to compile the changes to shared so they will be used.

**Comment by Sporax** [comment]
When I run `grunt` in the shared repo (I assume you mean `/habitrpg/node_modules/habitrpg-shared/`) then it says 'aborted due to warnings` because some local npm modules were not found.

**Comment by deilann** [comment]
Did you install npm in the shared repo?

**Comment by Sporax** [comment]
Was I supposed to install it separately? I'll run `npm install` then.

**Comment by Sporax** [comment]
Thanks, that fixed it. Now to upload it, I just use `git push` and then send a pull request, right? Do I need to do this for the `/habitrpg` repo or the shared repo?

**Comment by deilann** [comment]
yes, shared repo

**Comment by Sporax** [comment]
It says that there's nothing to compare, am I creating a request in the wrong branch (its in develop)?

**Comment by deilann** [comment]
Did you first add and commit the file you changed?

**Comment by crookedneighbor** [comment]
@Sporax I don't see any of your commits in your [develop branch for habitrpg-shared](https://github.com/Sporax/habitrpg-shared/commits/develop). I couldn't find a different branch with a name similar to the issue you were working on, so I assume you're working on the develop branch.

Did you commit the changes and then push (while in the shared repo, not the main repo)? If so, what is your branch's name?

**Comment by Sporax** [comment]
Guys I'm new here... How exactly are you supposed to add and commit a file? All I did was use `git push` in my shared repo, and then tried to create a pull request

**Comment by crookedneighbor** [comment]
@Sporax No worries!

The way git works is it keeps track of changes to files, so to add a file you've changed to be tracked you do: `git add path/to/file` for each file, and then `git commit -m "message about the changes I made"`.

Alternatively, you can do `git commit -am "message about the changes"` which adds all the files git with changes that git is currently looking at and lets you make a commit right away.

**Comment by crookedneighbor** [comment]
The only files with changes that git won't add using `git commit -am` are new files that git hasn't been instructed to track yet. For instance, let's say you made a new javascript file called `new.js`. Before git can track the change, that would need to be added with `git add new.js`, but after that, if you make a change to it, running `git commit -am "message"` would include it.

**Comment by deilann** [comment]
You can see what files have been changed with `git status -s`

**Comment by crookedneighbor** [comment]
@Sporax If that still doesn't make sense, please say something. Git can be confusing when you're just starting to use it.

After you've committed the file, you can then `git push` to send it to your repo. From there, you should be able to make a pull request and see the changes.

**Comment by Sporax** [comment]
I have one question: do I only add the file I directly edited or all the files it changed as well when it was compiled?

**Comment by crookedneighbor** [comment]
@Sporax Also, this might help you out: https://try.github.io/levels/1/challenges/1

It's an online interactive teaching tool for Git/Github.

**Comment by crookedneighbor** [comment]
@Sporax That is a great question. For now, all the files. 

You may run into merge conflicts with the habitrpg-shared.js file. Do not worry about them, submit your PR anyway, and I will sort them out.

We're working on having the compile process take place on the server, so in the future, git will automatically ignore the compiled files, and you can just submit the changes you actually made, but until that happens, commit all of them.

**Comment by crookedneighbor** [comment]
@Sporax Actually, if you haven't already done it, just add the one you changed. I'll compile it for you.

**Comment by Sporax** [comment]
I'm confused about another thing, I used a `grep` to find all the changes that were made during compilation since `armorSpecialSkiText` would have changed to `armorSpecialSkiNotes`. The files `content.coffee` and `habitrpg-shared.js` were changed under two directories: `habitrpg/public/bower_components/habitrpg-shared` and `habitrpg/node_modules/habitrpg-shared`. I used `git add` on the files in the node modules directory (which I directly edited) and when I used `git status -s` in the other directory, no files came up. Do I need to add the two files under the bower components anyway?

**Comment by Alys** [comment]
No, never add or commit or push any files under bower_components.

**Comment by Sporax** [comment]
Ok thanks. <a href="https://github.com/HabitRPG/habitrpg-shared/pull/421">I created the pull request</a>

**Comment by crookedneighbor** [comment]
@Sporax One of the steps you did was remove the existing `public/bower_components/habitrpg-shared` directory and instead created a link to `node_modules/habitrpg-shared`, which itself was a link to your local copy of habitrpg-shared. So adding the file in `node_modules/habitrpg-shared` did in fact add it in bower_components, because they were all referencing the same file.

I know that can be confusing, but does that make sense?

**Comment by Sporax** [comment]
Yeah that makes sense

**Comment by crookedneighbor** [comment]
Closed via https://github.com/HabitRPG/habitrpg-shared/pull/421

**Comment by Sporax** [comment]
Thanks for all the help guys, I really enjoyed working with you all!
