### ISSUE TITLE
Private Message (PM / DM) textbox is too small

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4425]
For private messages, I'm finding the text box to be smaller than convenient for typing more than a sentence. I think it could be made at least four or five times longer - unless anyone can think of a reason not to?

This would probably be a good job for a relatively new programmer since it should be a simple change.

**Comment by deilann** [comment]
Is longer the issue? Maybe it should be made fatter, too.

**Comment by crookedneighbor** [comment]
All it really needs is a rows attribute on the textarea element. I like 5 rows:

![screen](https://cloud.githubusercontent.com/assets/2916945/5561672/a1607a40-8dac-11e4-9ef1-1d0360599088.png)

**Comment by crookedneighbor** [comment]
Also, most browsers, including Chrome, allow you to resize the text area:

![screenresize](https://cloud.githubusercontent.com/assets/2916945/5561676/dd340b04-8dac-11e4-81d6-a241d14f4a24.png)

So I think adding `rows="5"` is a good default, and if people needs to expand it they can.

**Comment by lefnire** [comment]
And if we need it wider, simply use `size:'lg'` in modal-opening options (see https://github.com/HabitRPG/habitrpg/blob/develop/public/js/controllers/rootCtrl.js#L122)

**Comment by crookedneighbor** [comment]
Personally, I think it's a good width. I agree that the height is too small.

**Comment by melissamcewen** [comment]
Oops I just committed something for this, but it looks like it's in the same pull request as the other thing I was working on
https://github.com/HabitRPG/habitrpg/pull/4437
is there a way to prevent this? Should I be creating new branches?

**Comment by Alys** [comment]
Almost everybody makes that mistake in the beginning, including me. :)

Yes, it's a very good idea to create a new branch locally for every separate change you do, and then when you push to your repo on github, you push to a branch of the same name as your local one. This means you can have many different changes going at once with no conflicts.

Here's how I do it (from memory, so I hope there's no errors here!):

```
git fetch upstream  # get the latest code from the official HabitRPG repository
git checkout -b my_branch_name upstream/develop   # makes your new branch identical to the official 'develop' branch
# make your changes, test, and commit them
git push origin my_branch_name
# do a pull request from that branch in your repository in github
```

**Comment by crookedneighbor** [comment]
Closed via https://github.com/HabitRPG/habitrpg/commit/c4e62fc79ba16d55344f391a9b6b8f049d0afadd
