### ISSUE TITLE
No "Leave" buttons on Public Guilds list -- "Join" button is displayed instead

### ISSUE THREAD

**Issue by TwasBrillig1** [HabitRPG/habitica#4427]
On the public guild page, all the buttons on the right side of the page are the green "Join" button, even for guilds in which I'm currently a member. Example: 

![image](https://cloud.githubusercontent.com/assets/6257190/5561655/dd90e782-8db3-11e4-8ffa-1b839af099a8.png)

Clicking the Join button for one of the already-joined guilds seems to only bring me to the guild's page, where the Leave button appears as normal. 

UUID: 3ab30744-c44f-491a-b69e-c9eeefa5f24e
I'm using Chrome Version 39.0.2171.95 m in Windows 7. 

There were some errors in the console, not sure if they're related: 
https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=medium&hl=e…_1419694621429&parent=https%3A%2F%2Fhabitrpg.com&pfname=&rpctoken=29889000 Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/plugins/like.php?action=like&app_id=17252516279391…=en_US&ref=.VJ7SHBS6ZmQ.like&sdk=joey&send=false&show_faces=false&width=90 Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habi…8%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey Failed to load resource: net::ERR_CACHE_MISS

**Comment by Alys** [comment]
Confirmed on Chrome and Firefox, Mac OS

**Comment by melissamcewen** [comment]
On Chrome in Mac when I click that Join on Public Guilds for a guild I'm a member of, it crashes the browser

**Comment by melissamcewen** [comment]
I think it can't check if the user is a member because the member list isn't loaded. I'm relatively new to JS but that's what it looks like just looking at ng-inspector comparing the challenges where the similar system works vs. this where it doesn't
![habitrpg___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/1251094/5594527/17b64806-9216-11e4-84f4-0140af6f5476.png)

![habitrpg___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/1251094/5594528/270eea2e-9216-11e4-996c-130e8a771ef0.png)

**Comment by gisikw** [comment]
The issue here is that the member list is truncated to the first 15 members, so the front-end logic checking whether a user is a member of a group is only comparing against that first 15.

I should be able to wire up the backend to forward user inclusion info to get the join/leave button behavior working correctly :)

**Comment by Alys** [comment]
@gisikw I'm pretty sure we have some code related to this already, waiting for approval. Give me a few minutes to get through some other stuff, and then I'll look for it and comment here again.

**Comment by Alys** [comment]
Nope, can't find it. I might have been thinking of something else. @gisikw if you could fix this, we would be grateful and happy!

**Comment by crookedneighbor** [comment]
@alys were you thinking of the PR you reverted the other day: https://github.com/HabitRPG/habitrpg/pull/4908

**Comment by gisikw** [comment]
Ah, that looks like it should do it.

**Comment by crookedneighbor** [comment]
For reference, here's the comment that (I think) reveals the reason we had to revert it: https://github.com/HabitRPG/habitrpg/pull/4908#issuecomment-86543390

**Comment by Alys** [comment]
@crookedneighbor Thank you, yes, that was it.

**Comment by GreenAppleFields** [comment]
I noticed a similar issue. The leave button is showing in the guild list, but not on the guild page, where it's replaced by the join button.

**Comment by ian-lucario** [comment]
i have the same issue.

**Comment by Alys** [comment]
It could take a while to sort this out - perhaps architecture changes might be needed - so I'm wondering if it's worth putting both a join and leave button inside the guild. It couldn't be significantly more confusing than it is now, and it would certainly be more convenient for those who weren't confused. Any objections? @lemoness?

**Comment by gisikw** [comment]
I thought the reverted commit just needed some small revisions, no?

**Comment by gisikw** [comment]
Actually...the client must already _know_ the current user's guilds, because it's used for navigation. This could be handled client-site without requiring any adjustments to the DB, I think.

**Comment by Alys** [comment]
I thought there were significant problems with anything involving guilds and more than the default 15 people. 

However if you have a reliable way of fixing the join button, go go go! :)

**Comment by deilann** [comment]
How does it know to show the leave button on the public guild page?

**Comment by gisikw** [comment]
For the full query, _isMember is populated. That's not the case with the findOne endpoints.

**Comment by gisikw** [comment]
w00t. Yep, I've got functionality working. Just need to do some quick styling :)

**Comment by lemoness** [comment]
A Join AND Leave button inside the Guild is better than no Leave button at
all, but I will leave it to you to decide if it is worth the effort.

**Comment by crookedneighbor** [comment]
@lemoness The PR is all done, and works well, just waiting on some opinions for comments I left a little while ago.
