### ISSUE TITLE
[Suggestion] Habit Undoing

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#443]
I just clicked the '-' (minus) button on one of my Habits to test something, and I lost some Health. I wanted to undo it but I couldn't find out how. Is there already a way to do it that I am missing? I know this already exists for Dailies and Todos.

**Edit**: Sorry, I didn't see issue #6, and I can't find a way to delete this post...

Thanks,
busterroni

**Comment by lefnire** [comment]
in the queue: [trello](https://trello.com/card/undo-button/50e5d3684fe3a7266b0036d6/20) - high priority
