### ISSUE TITLE
To-Do Checklist- Hitting "enter" opens a new field, but does not move the cursor with it

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#4430]
This is a pretty minor annoyance, but worth mentioning, I thought:

The new To-Do Checklist formatting I'm seeing looks pretty slick, so props on that. But when I hit "Enter" to add a new item to the list, it opens a new field to type, but my cursor stays in the previous field. So unless I click the next field, I end up typing "SweepMop" instead of making two separate items that say "Sweep" and "Mop".

I'm on Firefox, using Windows 7. 

UUID: 9fe7183a-4b79-4c15-9629-a1aee3873390

**Comment by Alys** [comment]
Probably related to this direct commit: https://github.com/HabitRPG/habitrpg/commit/118ba88d3ddfaadb4d72952c8f83263d7a48586c

**Comment by crookedneighbor** [comment]
@beffymaroo Should be fixed on the next deploy

**Comment by beffymaroo** [comment]
@crookedneighbor Great! Thank you!

**Comment by beffymaroo** [comment]
As of today it's working (if you wanted/needed confirmation).

**Comment by crookedneighbor** [comment]
Thanks for letting us know @beffymaroo

**Comment by benmanley** [comment]
Thanks @crookedneighbor.

**Comment by beffymaroo** [comment]
So this same issue has just started happening to me again, with both To-Do's and Dailies with checklists (I noticed as of today, 1/19/15).

**Comment by crookedneighbor** [comment]
Seems to be something with the `bo-id` attribute. Did upgrading Angular break bindonce?

**Comment by deilann** [comment]
I really hope not.

**Comment by edunham** [comment]
I came here to report the "cursor doesn't move when I hit enter" thing as well, then found this ticket. It's been happening consistently over the past few days for me too.
 :bug: :hammer:

**Comment by lemoness** [comment]
Happening to me as well, consistently.

**Comment by crookedneighbor** [comment]
@lemoness should I up the priority on this?

**Comment by lemoness** [comment]
It's still pretty minor, I think, unless it's an easy fix.

**Comment by aedunn6** [comment]
I'll just echo edunham:
"I came here to report the 'cursor doesn't move when I hit enter' thing as well, then found this ticket."

**Comment by nthomsn** [comment]
The selector `$("#task-" + task.id)` doesn't find anything and produces an error. The id attributes of the `<li>` of each task are undefined. Don't know how to go about fixing it, without an id each `<li>` looks the same to jquery.

**Comment by Adaram** [comment]
This is happening for me as well. I am using Chrome Version 41.0.2272.89 m

**Comment by betaveros** [comment]
So I dug through the history and it appears that we stopped using bindonce after upgrading angular here: https://github.com/HabitRPG/habitrpg/commit/2023cf852ed1b11af641607d156d3cb9466d9aaa

That commit also replaced all the bindonce usages with new angular notation, but I guess the change for tasks got lost somewhere between then and now. It's an easy fix to reintroduce the change.

**Comment by Adaram** [comment]
Not sure about any of the coding stuff, but glad to see it's an easy fix :) I'll have to change my habits once it's fixed now. Instead of enter, TAB, then type, it will just be Enter, then type :)

**Comment by Adaram** [comment]
Tested and works great!

**Comment by beffymaroo** [comment]
Yay! Thanks!

**Comment by deilann** [comment]
This is occuring for me again.

**Comment by AnitaYCheng** [comment]
What will also happen is when I press "Enter" and a new checklist item is opened, the refresh progress bar stalls and the edit module will save and close before I can type anything. I have to press "Edit" again to open it up once more. Not sure if it's related, but it might be if it's a refreshing syncing issue.

**Comment by deilann** [comment]
That's a different bug and usually can be avoided by syncing first,
although not always.

It has to do with the user object updating in some way, iirc, in the time
since you last synced? I can't remember.

**Comment by deilann** [comment]
Well then... this persisted at being broken again over multiple To-Dos and through a refresh, but now it seems to be fixed. Must have been momentary for me.
