### ISSUE TITLE
API changes aren't visible enough to third-party developers/partners

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4432]
Recently, a change was made to HabitRPG's API that caused the Beeminder-HabitRPG integration to break (users were unable to make new HabitRPG goals in Beeminder). Beeminder staff have already fixed the problem so we don't need to investigate or change anything at our end, but this highlights the need to make API changes very obvious (ideally in advance) to third party developers. It's for HabitRPG's benefit as well - for example, if a long-time Beeminder user decides to try HabitRPG because the integration exists, we could lose a potential customer if the integration is broken.

So, this issue is for us to discuss ways that API changes can be made more visible. 

One option is that third-party developers can watch our files in GitHub for any changes. If they do that, is [src/routes/apiv2.coffee](https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv2.coffee) the ONLY file they would need to watch to be sure of noticing ALL changes that might affect their use of the API?

Something else that could help is if we try to submit all changes to the API through pull requests rather than through direct commits. PRs are much more obvious to anyone watching the repository (that includes HabitRPG admins and devs as well as third-partiers) and so are more likely to allow API changes to be recognised. It would also be good if the title of the PR mentioned the API.

I think it might also help if PRs that affect the API are left unmerged for a couple of days to give people time to comment on them and/or adjust their own code. Of course that does depend on how urgent the change is - we might not always be able to wait.

Would it be practical to set up some kind of mailing list / discussion group / notice board that's dedicated to API changes? Somewhere where we can state our intentions to change the API or notifcations that we have just changed it? Or would that be more trouble and effort than it's worth?

Does anyone have any other thoughts or improvements/criticisms of these ideas?
##

**Comment by dreeves** [comment]
Beautifully said, Alys! It's also possible we were doing something dumb with the API we never should've depended on. So maybe more important than visibility of changes is better documentation? Either way, it was no big deal. The first user who ran into the problem let us know and Alice Monday fixed it the same day!

**Comment by Alys** [comment]
## How to publicise upcoming changes to the API

When the API is changed, we should publicise the expected change _before_ they goes live. See https://github.com/HabitRPG/habitrpg/pull/4994#issuecomment-91761752 for an example of why. 

There should probably be a dedicate channel somewhere so that API users can see API news without also having to see other kinds of HabitRPG news, and it should probably not require a HabitRPG log-in because some developers might not be regular HabitRPG users (and should not be forced to be).

Suggestions for how to publicise changes _(this will be updated as new ideas appear below)_:
- Social Media posts
- posts to the Aspiring Coders guild
- dedicated Twitter account
- RSS endpoint
- ?  _Your ideas go here!_  :)

**Comment by Alys** [comment]
There should probably be a dedicate channel somewhere so that API users can see API news without also having to see other kinds of HabitRPG news, and it should probably not require a HabitRPG log-in because some developers might not be regular HabitRPG users (and should not be forced to be).

**Comment by gisikw** [comment]
RSS endpoint?

**Comment by Alys** [comment]
I do love RSS although it's so out of use now I'd temporarily forgotten about it... :blush:

**Comment by gisikw** [comment]
Probably gives developers the most flexibility as far as subscribing to changes though, as they could set up email notifications or just check the feed through some other means.

**Comment by Alys** [comment]
I wonder if it's feasible to introduce a new version of the API every time existing behaviour changes. That would be the most robust solution I think, from the -party point of view.

**Comment by gisikw** [comment]
That could get unwieldy pretty quickly though. I'd say you want to introduce a new `/api/vX` only when changes to the API are backward incompatible.

Though it could be feasible to use semantic versioning, and auto-map stuff to the most up-to-date endpoint?

i.e.
- `/api/v2.0.3/groups`
- `/api/v2.1.0/groups`
- `/api/v2/groups` routes to `/api/v2.1.0/groups`
- `/api/v2.0/groups` routes to `/api/v2.0.3/groups`

**Comment by Alys** [comment]
Ah yes, by "existing behaviour changes" I meant "backwards incompatible". I think the current change under review counts as that.

**Comment by crookedneighbor** [comment]
I think the most straightforward way to handle this is to set up a mailing list for 3rd party developers about API changes.

Whenever a breaking API change comes out, we'd want to send out an alert some time before it is deployed detailing what the change is and how to prepare their integration for it.

**Comment by paglias** [comment]
We now have a blog for devs (http://devs.habitica.com) and should not make any breaking change to the API
