### ISSUE TITLE
German translation issue

### ISSUE THREAD

**Issue by okuegow** [HabitRPG/habitica#4433]
Your German translation of "morning" or "in the morning" needs to be fixed:
The spelling of the word "morgends" is wrong, correct would be "morgens".

**Comment by Alys** [comment]
Thank you!

Are you interested in helping with the translations? If so, have a look at [Guidance for Linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists). If not, we can get another translator to fix this.

**Comment by ghost** [comment]
@Alys for the sake of housekeeping, this issue seems a duplicate of https://github.com/HabitRPG/habitrpg/issues/4031 to me. Neither Transifex nor GitHub searches return any occurrence of typo in question ("morgends") now.

**Comment by Alys** [comment]
Thanks @GitHubSphinx!
