### ISSUE TITLE
Inconsistent alignment of Gem prices in Seasonal Shop

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4434]
In the Seasonal Shop, the Gem costs for Quests don't line up the same way the costs for gear pieces do:

![2014-12-28 14_50_07-habitrpg _ your life the role playing game](https://cloud.githubusercontent.com/assets/4501321/5564950/0bb3f486-8ea1-11e4-9bae-b1bf873340f6.png)

Should be a simple Jade fix: find a style that will work for these elements and apply it in both places in `inventory.jade`. The Quests could also use a `&nbsp;` to get the right spacing between numeral and icon.

**Comment by melissamcewen** [comment]
I'm not sure I did this right, but I worked on this and created a pull request
https://github.com/HabitRPG/habitrpg/pull/4437
Let me know

**Comment by SabreCat** [comment]
I see your commit adds the 'nbsp;`, cool! I don't see anything about the right vs. left alignment, though, are you still working on that? Sorry if it was unclear in the issue ticket, I mentioned two things at once there.

**Comment by crookedneighbor** [comment]
The inventory page has them aligned to the right:

![screen shot 2014-12-29 at 6 34 02 pm](https://cloud.githubusercontent.com/assets/2916945/5574586/547766d8-8f89-11e4-8a5d-cb7095028183.png)

It'd also be great if you could add the `nbsp;` to the main market stuff too.

**Comment by crookedneighbor** [comment]
I took care of the alignment and merged in the PR. Had a class named `center` instead of `text-center`
