### ISSUE TITLE
How do you keep node_modules like HabitRPG Shared up to date on local development environment

### ISSUE THREAD

**Issue by melissamcewen** [HabitRPG/habitica#4436]
I have a local development environment set up and I know how to rebase, but what about the things living in node_modules? How do I keep this up to date?

**Comment by Alys** [comment]
Firstly, it's important that you follow the instructions in "Work with habitrpg-shared" in http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths . That will put your local habitrpg-shared repository in the correct location under node_modules, and will ensure that when you update it, then all the changes will be automatically applied to the correct locations.

Keeping it updated with the latest changes from the upstream repository is then just a matter of rebasing or merging.

You'll need to run grunt from time to time to ensure that changes are compiled (e.g., when you edit files under habitrpg-shared/scripts). There's some information about grunt in http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths and http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally

Keeping the other material under node_modules up-to-date depends on what changes are needed. Every so often, new or updated node or bower modules are added to the site, and then you'll need to follow the instructions under "Updating" in http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally (section 4).

This information might not be enough to answer all your questions! Have a look through the information I've referenced, and then ask us any follow-up questions you might have.

**Comment by melissamcewen** [comment]
Thanks!
