### ISSUE TITLE
Translate old private code from old habitrpg-shared-premium

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#4442]
Moved from https://github.com/HabitRPG/habitrpg-shared/issues/371
##

**Comment by crookedneighbor** [comment]
@paglias Would you mind making a tag named something like "Migration from HabitRPG-Shared" or even just "HabitRPG-Shared"?

I'm going to do some moving of issues like this, and it'd be great to have them grouped together after I'm done.

**Comment by Alys** [comment]
@blade: 'Migration from HabitRPG-Shared' label created. You likely have access to create labels yourself: https://github.com/HabitRPG/habitrpg/issues -> "Label" tab near the top of the page -> New label. I had to be told about it too; it's not obvious.

**Comment by crookedneighbor** [comment]
@Alys THANK YOU. And also, thanks for being gracious in the way you told me.

I forgot that Github doesn't allow you to create new labels on the fly.

**Comment by Alys** [comment]
"create new labels on the fly" is EXACTLY what I tried to do too, and then
gave up and asked the staff. :)
