### ISSUE TITLE
Include sexism in list of unacceptable behavior

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4443]
[Originally posted here](https://github.com/HabitRPG/habitrpg-shared/issues/391)

@lacrimae

> I don't feel comfortable changing this myself without an OK from someone higher up first: namely changing the Community Guidelines to explicitly include sexism in the list in [commGuideList02B](https://github.com/HabitRPG/habitrpg-shared/blob/aeceb70b5439c9521e437f0aad29ec35957ca3d6/locales/en/communityGuidelines.json#L37).

ping @lemoness and @Alys

**Comment by lemoness** [comment]
I'm happy to have sexism added to the list! It's implicit in the discrimination clause, but it can't hurt to make it explicit as well.

**Comment by crookedneighbor** [comment]
ping @lacrimae

**Comment by Alys** [comment]
Added to upcoming updates in https://github.com/HabitRPG/habitrpg/issues/4457
