### ISSUE TITLE
Consider using Amazon S3 for static resources

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4444]
[Originally reported here](https://github.com/HabitRPG/habitrpg-shared/issues/353)

@YokoZar

> I noticed server costs and performance issues have been a thing for Habit for a while now. From what I can tell, static assets are being served from the same servers.
> 
> One easy win here is to offload as much static content as possible to an external service such as Amazon's S3. This will result in higher availability of this content (and, if versioned by filename, no issues with grabbing out of date or newer than expected files either).
> 
> I've done this sort of thing before and would be willing to help if needed.

@lefnire 

> That is something we'd like to do. It won't save us much right now, 99% of the load is in `user#batch-update()` controller function, per NewRelic. Almost certainly due to https://github.com/HabitRPG/habitrpg/issues/4079 . Once we have the biggest bottlenecks squashed first, we'l move on to smaller bits like this.

@crookedneighbor

> @lefnire Putting the sprite images and css files on S3 will allow the mobile app to reference the new equipment automatically, right?
> 
> @YokoZar Just curious, but what are the next steps if we want to go this route? We're archiving the shared repo soon, and this could be a good step.

@paglias 

> @crookedneighbor the mobile app uses local version of the files actually, it wouldn't change much with s3. What we need is a way to download the new sprites and also the new habitrpg-shared.js files on mobile. Making sure not to break anything with new code that might have been added
> 
> @crookedneighbor to do this I'd say we need to add a task to the grunt task that pushes to an s3 bucket and references the files there not with the relative url but with http://ourbucket.s3-aws-region.amazonaws.com in front of the file path I suppose

@crookedneighbor

> @paglias Are you saying that we can't have the mobile app point to external resources to download content like images and css for spritesheets? I guess that would make sense, especially for iOS, where everything is so sandboxed.

**Comment by paglias** [comment]
@crookedneighbor I'm not sure, we could link the css/javascript to the online version, get it cached and then change the link after any update but I'm not sure we can do it.

**Comment by paglias** [comment]
@YokoZar the files are generated inside the build process. But they are delivered as they are, the server just throws them to the browser.

I would revew this when we move habitrpg-shared inside habitrpg as we're going to refactor the build process I think

**Comment by crookedneighbor** [comment]
I second refactoring the build process. I think that anything that is not edited directly shouldn't be version controlled and should be compiled upon deploy.

**Comment by paglias** [comment]
what stopped us from using this approach is that bower doesn't support a way to compile stuff like a `postinstall` command so we had to deliver compiled stuff in habitrpg-shared but I hope we can solve this having everything in the same repo

**Comment by paglias** [comment]
[This](https://github.com/niftylettuce/express-cdn) seems to be exactly what we need

**Comment by Alys** [comment]
Can this be closed now?

**Comment by crookedneighbor** [comment]
We should still consider it, but not enough to keep an open issues.
