### ISSUE TITLE
Better pluralization for beastMastText2

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4445]
[Originally reported here](https://github.com/HabitRPG/habitrpg-shared/issues/342)

Condensed version:

The string actually is:

> and has released their pets a total of <%= count %> times

Which sounds funny when pets have been released "1 times".

Suggested solution: @taldin

> How about: "Keys to the Kennel used: <%= count %>" or something similar?
##

**Comment by librarianmage** [comment]
@crookedneighbor Also triadBingoText2 has that problem

**Comment by librarianmage** [comment]
I can work on this!

**Comment by khipkin** [comment]
This issue applies to the "beastMasterText2", "mountMasterText2", and "triadBingoText2" strings in `pets.json`.
