### ISSUE TITLE
Shirt and warrior armor have pixels always hidden by head outline

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4446]
Originally reported here: https://github.com/HabitRPG/habitrpg-shared/issues/171

@PeterHatch 

> So the top of the shirts and the warrior armors have four colored pixels that will always be overridden by the bottom of the head outline, which is presumably not what the artist originally intended.
> 
> Not sure what should be done about this. The healer armor, at least, goes down one pixel farther, so one option would be to redraw with things moved down one pixel, except the arms.
> 
> (Where the bottom of the head outline is Healer armor has pixels the same color as the head outline, Rogue armor has transparent pixels, and Wizard armor generally has pixels the same color as the head outline, except two transparent pixels at the center. I think it'd be easier to tell how the armor would look on an avatar if they all had pixels matching the head outline.)
##

**Comment by lemoness** [comment]
If I understand the request correctly, this is a very basic, if somewhat
tedious, pixel job. It's pretty low priority, though. Should I just mention
it to some of the pixelists to see if there's anyone who's interested and
tell them to post to this ticket when they're done?

**Comment by crookedneighbor** [comment]
Sure, sounds great.

**Comment by lemoness** [comment]
Posted! We'll see if we get any takers.

**Comment by k8sullyvan** [comment]
Potentially the Armour template should be adjusted to prevent future occurrences, or was it just on the original sets of armour?

**Comment by lemoness** [comment]
It should just be on the original sets of armor, unless I am mistaken!

**Comment by librarianmage** [comment]
@crookedneighbor, is this still a problem?

**Comment by paglias** [comment]
pinging, is this still a problem?

**Comment by lemoness** [comment]
Honestly, though it still happens, it's basically unimportant -- those pixels that are covered have always been covered and fixing it isn't really necessary. I'm closing this ticket, but if anyone disagrees they can comment here.
