### ISSUE TITLE
Re-canvas Mounts as 105x123, adjust positioning

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4449]
Originally reported here: https://github.com/HabitRPG/habitrpg-shared/issues/50

@lefnire 

> Before grunt-spritesmith #37, we were using mounts on a single spritesheet 105x105 (simpler to work with squares in PS). Now we've moved to spritesmith, we can easily batch-automate re-canvas them as 105x123 & adjust their position so the avatar looks better riding them. Poor positioning example:
> 
> ![1](http://gyazo.com/2883d1aa4cf3b227129d768d5dab6ad4.png)
> 
> @wc8 @Fandekasp @SabreCat and anyone else, just a heads up on this ticket in case people start complaining about mount positioning. I'm assigning to me, the position tweaks will roll out with `classes` branch (actually... I might look into merging in #37 to `develop` if `classes` takes too long, spritesmith brings huge benefit to habit's pixel world)

**Comment by lemoness** [comment]
Kiwibot recently finished some art tweaks to the mounts, if you need them! I'd be interested to see if the wolves could be readjusted differently, but other than that, I think most of her solutions are great: http://sta.sh/229fwtoanwz

**Comment by crookedneighbor** [comment]
These are awesome!

**Comment by crookedneighbor** [comment]
@lemoness How about when all the mounts are ready, post here, and I'll work on adjusting the proportions and alignment.

I can rig up a demo page to preview it and y'all can tell me if anything needs tweaking.

**Comment by lemoness** [comment]
How's this wolf look on the avatar? 
![mount_wolf1b](https://cloud.githubusercontent.com/assets/3494081/5767751/a971f016-9cbf-11e4-8289-62ad04978596.png)
![mount_wolf1a](https://cloud.githubusercontent.com/assets/3494081/5767750/a96d2518-9cbf-11e4-8ddb-45422f766d9c.png)

**Comment by SabreCat** [comment]
@lemoness:
![image](https://cloud.githubusercontent.com/assets/4501321/5944615/ff5afc7e-a6ed-11e4-822f-5b302fb8bad6.png)

I love Kiwibot's work! I would maybe move the bears 1-2 big!pixels rightward so the avatars don't look like they're in the process of dismounting (which might require also moving the bears down by a big!pixel), but otherwise they're lovely.

**Comment by lemoness** [comment]
Hm, what does it look like with the tail moved so it's fully in the box -
or is that impossible?

**Comment by SabreCat** [comment]
Put it through a -12 x offset and got this:
![image](https://cloud.githubusercontent.com/assets/4501321/5950064/df1f136e-a71a-11e4-9c55-bd0be0a0fab6.png)

Not too shabby!

**Comment by lemoness** [comment]
Awesome, I think that looks good! Will get you the rest of the wolf
recolors soon.

**Comment by lemoness** [comment]
Wolf mount repositions are done! Including a fixed version of the Base Wolf.

You should now have updated versions of all the mounts. Let me know if you need any more art!

![mount_wolf_bluebody](https://cloud.githubusercontent.com/assets/3494081/7876648/16e5e4f4-0584-11e5-94ed-5e579b0744b1.png)
![mount_wolf_desertbody](https://cloud.githubusercontent.com/assets/3494081/7876647/16e2c1a2-0584-11e5-9fed-849015c522b3.png)
![mount_wolf_shadebody](https://cloud.githubusercontent.com/assets/3494081/7876649/16e6b618-0584-11e5-93c6-ad6a55e2bff8.png)
![mount_wolf_goldbody](https://cloud.githubusercontent.com/assets/3494081/7876650/16ef9e40-0584-11e5-96b3-4d2b82dbe677.png)
![mount_wolf_whitebody](https://cloud.githubusercontent.com/assets/3494081/7876654/16fe91f2-0584-11e5-87de-b094a92c59bd.png)
![mount_wolf_redbody](https://cloud.githubusercontent.com/assets/3494081/7876651/16f32e84-0584-11e5-9884-1784282aacfc.png)
![mount_wolf_pinkbody](https://cloud.githubusercontent.com/assets/3494081/7876652/16fb73e6-0584-11e5-9091-8f1ccf429a9b.png)
![mount_wolf_skeletonbody](https://cloud.githubusercontent.com/assets/3494081/7876653/16fc5e14-0584-11e5-8cb4-963cb8eb58a2.png)
![mount_wolf_zombiebody](https://cloud.githubusercontent.com/assets/3494081/7876655/16ffe0e8-0584-11e5-9c2f-e6adfb7897e2.png)
![mount_wolf_basebody](https://cloud.githubusercontent.com/assets/3494081/7876656/1704518c-0584-11e5-8129-ff610179ee8a.png)
![mount_wolf_bluehead](https://cloud.githubusercontent.com/assets/3494081/7876657/1706b51c-0584-11e5-87a4-1960d0ad02be.png)
![mount_wolf_pinkhead](https://cloud.githubusercontent.com/assets/3494081/7876658/1713cfa4-0584-11e5-9621-4b3f01c19ab0.png)
![mount_wolf_deserthead](https://cloud.githubusercontent.com/assets/3494081/7876659/17141c48-0584-11e5-83d1-0d6925724cfc.png)
![mount_wolf_basehead](https://cloud.githubusercontent.com/assets/3494081/7876661/171b218c-0584-11e5-8d16-24c5d1dc919a.png)
![mount_wolf_shadehead](https://cloud.githubusercontent.com/assets/3494081/7876660/171a987a-0584-11e5-9534-d753bf247410.png)
![mount_wolf_redhead](https://cloud.githubusercontent.com/assets/3494081/7876662/171f6c4c-0584-11e5-8ee4-bef2ffddc1f5.png)
![mount_wolf_whitehead](https://cloud.githubusercontent.com/assets/3494081/7876663/172095fe-0584-11e5-8d70-77d11008a037.png)
![mount_wolf_skeletonhead](https://cloud.githubusercontent.com/assets/3494081/7876665/1737c760-0584-11e5-861f-21b9cee2b390.png)
![mount_wolf_goldenhead](https://cloud.githubusercontent.com/assets/3494081/7876664/17363562-0584-11e5-86a0-632dd297b301.png)
![mount_wolf_zombiehead](https://cloud.githubusercontent.com/assets/3494081/7876666/173fa318-0584-11e5-8c70-887abe3039da.png)

**Comment by SabreCat** [comment]
I think this got done a while back but wasn't closed. Doing so now!
