### ISSUE TITLE
[Suggestion] World Map

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#445]
So, I was thinking, every good RPG has a world map.  It might be nice to see your party's icons on the map perhaps using Google Latitude.  If users don't want to share that kind of info maybe we could see our own personal avatar at our location and generic other characters based on a heatmap of activity across the 8-bit world.

Map location could also set the skin and background of an individual's interface.  There could be a couple of patterns like city, mountain, hills, grassland, woods, desert, and sand.  The browserquest tilesheet is a good start.

Too bad Google's 8-bit quest map feature was only an April fool's joke, because that is the kind of thing I'm thinking of.

Obviously this would be for later.

**Comment by wc8** [comment]
As another way of achieving privacy, a game world? Let the users pick their own location.
Maybe somehow users who want to display their location could be accommodated as well by allowing the game to assign a location based on their real location. 

I'd like to see a map, but I have a general policy (for security reasons) against telling websites my name, location and birth date, etc..

**Comment by dbueller** [comment]
I have a great idea!  We could use the map of the internet (
http://xkcd.com/256/) and have location taken from the chrome extension.
 OK, I admit, probably not everyone would like it.

**Comment by ghost** [comment]
I like the idea of using an actual map, but giving users the opportunity to use it as an option (to their discretion). Possibly limiting the specificity of their location on the map.

**Comment by lemoness** [comment]
I would definitely say that they idea of having my general location displayed on a real-world map would freak me out.... but I like the idea of choosing my location from a fantasy map with several kinds of terrains, and having that terrain show up as my background :)

**Comment by wc8** [comment]
Follow link(s) and vote for your preferences or comment with concerns/ideas:
[Map: User Locations](https://trello.com/c/iGLFb8aX)
[Map: Fantasy User Locations](https://trello.com/c/MyUoEMFg)

**Comment by wc8** [comment]
The two ideas are possibly compatible with map modes: Geolocation, HabitRPG world, Internet Heat Map, etc. 
In Geolocation, fewer users would be shown as only the opt-in users would be displayed.

**Comment by Pandoro** [comment]
Personally I am a bit against a real world map. It will only lead to complaining users that don't want it and find their privacy in danger. Of course it is an opt-in thing, but for both I am wondering a little what the actual use is. It is of course fun, but that is it right? The actual background thing can also be realized without the map location, but simply as selectable skins if that was the main goal of this suggestion. 

The things are on Trello and discussion seems to be pretty much over here. 

I will close this ticket, but feel free to reopen it :)
