### ISSUE TITLE
Cron (The 'Errors that shouldn't be errors')

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4450]
Originally reported here: https://github.com/HabitRPG/habitrpg-shared/issues/199

@markusholdings

> I decided to take this issue out of #1057 because I dont want to clutter that thread any more than I already have.
> 
> So I found that in your daysSince method, you're measuring the difference in days, which means when you log in during the critical time, then log in again that same day, it returns a 0, even past the dayStart. So I picked with it a bit and added a conditional, at first it was working, but rigorous testing found that it was still returning a 0 even on two consecutive days of logging in at the critical time. So I added another conditional to account for that. That's when the 'erroneous errors' appeared.
> 
> Here are the errors:
> 
> ```
> 1) Cron dailies new day due yesterday due today pre-dayStart checked
> 3) Cron dailies new day due yesterday NOT due today pre-dayStart checked
> 5) Cron dailies new day not due yesterday pre-dayStart
> 
> (+) expected (-) actual
> 
> {
> "buffs": {
> (+) "con": 0,
> (+) "int": 0,
> (+) "per": 0,
> (-) "con": 1,
> (-) "int": 1,
> (-) "per": 1,
> "stealth": 0,
> (+) "str": 0,
> (-) "str": 1,
> "streaks": false
> },
> "class": "warrior",
> "con": 1,
> 
> 2) Cron dailies new day due yesterday due today pre-dayStart un-checked
> 4) Cron dailies new day due yesterday NOT due today pre-dayStart un-checked
> 
> (+) expected (-) actual
> 
> "class": "warrior",
> "con": 1,
> "exp": 0,
> "gp": 0,
> (+) "hp": 50,
> (-) "hp": 48,
> "int": 1,
> "lvl": 1,
> "mp": 32,
> "per": 1,
> ```
> 
> Location of the Test where the errors are appearing: https://github.com/HabitRPG/habitrpg-shared/blob/develop/test/algos.mocha.coffee#L501
> 
> The thing is, these errors all look like expected behavior. If you leave a daily unchecked, then you should take damage. And if you check it, you should keep your buff. But when I run the test, these are the only ones that fail. Can someone else look at these and tell me whether or not I'm crazy?
###### NOTE: Edited to wrap errors in code formatting

@lefnire 

> Ahh! Interesting find. (i see you're using algos.mocha, ignore my previous comment about that). I'll take a second gander when I can then
##

**Comment by crookedneighbor** [comment]
For additional conversation, read here: https://github.com/HabitRPG/habitrpg-shared/issues/265

**Comment by Alys** [comment]
I don't think this happens any more. Reopen if I'm wrong.
