### ISSUE TITLE
Salt spell doesn't check to see if you have enough Gold

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4454]
I bought enough Snowballs to reduce myself to a handful of Silver in the bank, then clicked Salt. The spell went off, removing the snowman from my avatar, and reduced me to -5 Gold!

**Comment by deilann** [comment]
You'll never be able to buy Steam games now.

**Comment by SabreCat** [comment]
Probably good for me, that. Though my backlog manages to increase anyway,
with all the gifts I've been getting through Steam lately!

**Comment by melissamcewen** [comment]
Yep, I did it too on my dev install. I bought a snowball, transformed myself to a snowman, then cast salt, now I have -5 too.

**Comment by melissamcewen** [comment]
What's the recommended solution for this? Is adding an IF clause in the cast OK?

**Comment by SabreCat** [comment]
Yep, basically. Take a look at how the New Year's cards handle it - we
might be able to pass it through the same check.

**Comment by melissamcewen** [comment]
Thanks @SabreCat , could we implement 
User.user.stats.gp < spell.value
or do you think we need the check still? 
      if (spell.key == 'nye' && User.user.stats.gp < spell.value)
and add the salt one to that? If guess in the future if there are plans to have more usage of value for spells, it might make sense to keep the check there?

**Comment by SabreCat** [comment]
Checking against spell.value should be safe; current design plans are to
use value for Gold costs and mana for MP costs.

**Comment by joshbDev** [comment]
This also is also with the new years eve cards. Though that is over soon (or now) it may be worth looking into.

**Comment by crookedneighbor** [comment]
@thehindenburg It's covered in @melissamcewen's [PR](https://github.com/HabitRPG/habitrpg/pull/4458)

**Comment by joshbDev** [comment]
:+1:  just making sure
