### ISSUE TITLE
New Year's Card price doubled

### ISSUE THREAD

**Issue by itsasooz** [HabitRPG/habitica#4455]
The price listed in the shop is 10G, but when I "cast" it on a person, it debits 20G 90S from my account:
http://i.imgur.com/LUCPGx6.jpg

UID 312f9e64-7c17-40dc-b10c-3c03afc948a3
Browser is Chrome, using Windows 8

**Comment by crookedneighbor** [comment]
Odd. I just did it and it deducted the correct amount:
![screen shot 2014-12-31 at 1 30 52 pm](https://cloud.githubusercontent.com/assets/2916945/5590052/677dc420-90f1-11e4-9a0a-6fcf90eed20d.png)

Are you sure you didn't purchase a reward in another window, and then when you activated the card, it started a sync process, prompting it to calculate the full amount of gold spent for the card + other item purchased previously?

Would you mind trying again? You can use the [fix character values button on the settings page](https://habitrpg.com/#/options/settings/settings) to reimburse yourself for the gold.

**Comment by itsasooz** [comment]
I only had one window open.  It happened repeatedly (I bought cards for all my party members).  

Trying it again has removed the issue, so I guess chalk it up to a gremlin or something.  Oh well.  It's not like I'm hurting for the scratch.

**Comment by crookedneighbor** [comment]
Probably impossible to tell since you have over 1,000 (and thus is difficult to see at a glance smaller increments), if it actually deducted the correct amount on a refresh or not.

Okay, well, it if happens again, report back here.
