### ISSUE TITLE
First New Year's Card is Unreadable

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4456]
First card received does not show up in inventory. Same issue as for Valentine's Day cards? (https://github.com/HabitRPG/habitrpg/issues/2842)

**Comment by crookedneighbor** [comment]
@Anysia Have you refreshed the page?

**Comment by crookedneighbor** [comment]
I see from your post in the tavern that you have refreshed:

Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by ghost** [comment]
Yes. Repeatedly. When I got the second card only the second showed up in inventory. If you look at the Valentine's Day card issue I linked it looks like this was never fixed so will recur every time there are cards.

**Comment by ghost** [comment]
db190b28-8ce5-422e-8076-d43a62a7b204

**Comment by crookedneighbor** [comment]
Yes, thanks for linking to that issue, it's helpful. I'm looking into it now. 

You don't happen to know how many new years cards you have sent and received total, do you?

**Comment by ghost** [comment]
I have sent 5 cards, received 2, and opened none (though I can tell from the popover that the one showing up in inventory is the second one). Thanks for the effort. :)

**Comment by crookedneighbor** [comment]
Well, your user does show 7 being sent/received. I assume the 2 you received were from different people? Or the same person?

[This seems to be the line that was giving the trouble in the other issue](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L708), but I don't know why.

``` coffeescript
(target.items.special.nyeReceived ?= []).push user.profile.name
```

For me, I'm able to see and open them all right, but the user name isn't getting pushed to the array at all:

![screen shot 2014-12-31 at 2 39 07 pm](https://cloud.githubusercontent.com/assets/2916945/5590468/d0b08c9e-90fa-11e4-9398-29bcb508ee52.png)

Here's my user data:

``` json
    "special": {
      "nyeReceived": [],
      "valentineReceived": [],
      "spookDust": 6,
      "snowball": 8
    },
```

Earlier, I cast one on myself to try it out, and I did see my name in the nyeRecieved array. But it too has vanished.

**Comment by ghost** [comment]
Yes, they were received from different party members (that's how I know it's the second one showing up and not the first).

**Comment by crookedneighbor** [comment]
Thanks. Earlier your `special.nyeRecieved` array had a user name in it, now it's empty. WEIRD.

**Comment by crookedneighbor** [comment]
Oh, I see. When you open the letters, the name disappears. I guess that's intentional.

**Comment by ghost** [comment]
Except I haven't opened any cards (only moused over to see who sent it).

**Comment by crookedneighbor** [comment]
Oh gosh, my mistake, you still have a user in your array. I had both the member pane (you) and the user pane (me) and was looking at mine when I said you had an empty array.

**Comment by crookedneighbor** [comment]
@SabreCat 
Would separating it out help, like [lefnire suggested](https://github.com/HabitRPG/habitrpg/issues/2842#issuecomment-35137759):

(correct my coffeescript if it's incorrect)

``` coffeescript
target.items.special.nyeReceived = [] if !target.items.special.nyeReceived
target.items.special.nyeReceived.push user.profile.name
```

**Comment by crookedneighbor** [comment]
Here's how it's getting compiled:

``` javascript
nye: {
      text: t('nyeCard'),
      mana: 0,
      value: 10,
      target: 'user',
      notes: t('nyeCardNotes'),
      cast: function(user, target) {
        var _base, _base1;
        if (user === target) {
          if ((_base = user.achievements).nye == null) {
            _base.nye = 0;
          }
          user.achievements.nye++;
        } else {
          _.each([user, target], function(t) {
            var _base1;
            if ((_base1 = t.achievements).nye == null) {
              _base1.nye = 0;
            }
            return t.achievements.nye++;
          });
        }
        ((_base1 = target.items.special).nyeReceived != null ? _base1.nyeReceived : _base1.nyeReceived = []).push(user.profile.name);
        if (typeof target.markModified === "function") {
          target.markModified('items.special.nyeReceived');
        }
        return user.stats.gp -= 10;
       }
```

**Comment by SabreCat** [comment]
@lefnire said it didn't do much, in that ticket, but you're welcome to give
it a shot! I won't have a chance to tinker with it until tomorrow morning.

**Comment by crookedneighbor** [comment]
Merged in:
https://github.com/HabitRPG/habitrpg-shared/commit/439f72cb91cefb8e51e3a782abbd448fcfbb0f50

@lefnire or @paglias let me know when the next deploy happens so we can ping the tavern.

**Comment by Alys** [comment]
It's probably worth doing one straight away since it's a timely issue. I'll try a deployment to the beta site unless one of the staff says not to in the next few minutes (I'll contact them separately to make sure they're aware of this). Depending on how well that goes, I'll then do one to the production site.

**Comment by Alys** [comment]
Nope, beta's in use for cron tests, and I don't want to push directly to production first. I'll leave it to one of the staff.

**Comment by Alys** [comment]
@crookedneighbor : @SabreCat has deployed to production

**Comment by crookedneighbor** [comment]
Okay. Let's leave this issue open through the weekend and then close it if we don't get any further reports.
