### ISSUE TITLE
Community Guidelines Updates

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4457]
Ticket for updating the Community Guidelines.

Here are the changes we need to make so far:
- Address PMs (Ability to send users direct messages
  Ability to block individual users
  Ability to opt out of private messaging)
- add a line explicitly forbidding spamming (implied but not overt), including spamming Guilds and spamming PMs
- add a line about not spamming people asking for gem or subscription gifts
- add a note about making new accounts to get around consequences being a ban-worthy offense.
- Add sexism to list
- Add Blade to list of mods

Anything else I should add in when I'm doing the edits?

**Comment by crookedneighbor** [comment]
@lacrimae suggested that sexism should be listed explicitly: https://github.com/HabitRPG/habitrpg/issues/4443

If you don't want to add that, the issue can be closed.

**Comment by lemoness** [comment]
Edited to add listing sexism, and having spamming include PM spamming and Guild Spamming.

**Comment by lemoness** [comment]
Edited to add clarification that asking for gems is spamming.

**Comment by lemoness** [comment]
- [ ] Switch mod image to add Blade:

![npc mods2](https://cloud.githubusercontent.com/assets/3494081/6071292/967c112e-ad51-11e4-862f-9e4cdec15bbf.png)
- [ ] Add info about Blade to Meet the Mods:

"Bailey (It's Bailey in Tavern chat)
Ryan (deilann on GitHub/Wikia)
Alys (LadyAlys on Wikia)
Blade (crooked neighbor on Github)
Breadstrings
Megan
Daniel the Bard"
- [ ] Address PMs 

Public Spaces in Habitica:
"Private spaces are Private Guilds and party chat." 
becomes "Private spaces are Private Guilds, party chat, and Private Messages."
After "In private spaces, users have more freedom to discuss whatever topics they would like, but they still may not violate the Terms and Conditions, including posting any discriminatory, violent, or threatening content." add the following: "Private Messages (PMs) have some additional guidelines. If someone has blocked you, do not contact them elsewhere to ask them to unblock you. Additionally, you should not send PMs to someone asking for support (since public answers to support questions are helpful to the community). Finally, do not send anyone PMs begging for a gift of gems or a subscription, as this can be considered spamming."
- [ ] explicitly forbidding spamming

New bulletpoint in the Public Spaces in Habitica List:

Do not spam. Spamming may include, but is not limited to: posting the same comment or query in multiple places, posting links without explanation or context, posting nonsensical messages, or posting many messages in a row. Repeatedly begging for gems or a subscription may also be considered spamming.
- [ ] list sexism in list

Public Spaces in Habitica:

"Do not post images or text that are violent, threatening, or sexually explicit/suggestive, or that promote discrimination, bigotry, racism, hatred, harassment or harm against any individual or group." 
becomes "Do not post images or text that are violent, threatening, or sexually explicit/suggestive, or that promote discrimination, bigotry, racism, sexism, hatred, harassment or harm against any individual or group."
- [ ] make dupe accounts to avoid consequences ban-worthy

Add new bullet point to Severe Infractions:

Creating a duplicate account to avoid consequences (for example, making a new account to chat after having chat privileges revoked)

**Comment by lemoness** [comment]
I've added in the edits for the Community Guidelines. Does anyone have any suggested edits? If not, we can go ahead and add these in :)

**Comment by Alys** [comment]
I've posted to the Aspiring Coders guild to see if any relatively new programmers want to do this.

**Comment by lemoness** [comment]
Great!

**Comment by ojintoad** [comment]
I would be willing to do this as a way of feeling my way around the code base and getting my ducks in a row with my dev environment. Feel free to assign it to me.

**Comment by Alys** [comment]
Fantastic, thank you! Ask here if you have questions or run into trouble.

**Comment by ojintoad** [comment]
Okay, shall I assume I should only update the language files for english and experienced translators will handle others?

**Comment by crookedneighbor** [comment]
@ojintoad Correct. All non-English files are managed by Transifex. See [this file for more details](https://github.com/HabitRPG/habitrpg-shared/tree/develop/locales).

**Comment by ojintoad** [comment]
@crookedneighbor Okay, great, thank you for clarifying.

**Comment by ojintoad** [comment]
See [PR 4654](https://github.com/HabitRPG/habitrpg/pull/4654) and [PR 465](https://github.com/HabitRPG/habitrpg-shared/pull/465)

**Comment by Alys** [comment]
Thanks Todd! Can you please upload screenshots of all the parts of the
Guidelines that have changed (with some surrounding material for context),
so that Lemoness can do a final review of her chosen wording and check the
layout with respect to the images?

**Comment by ojintoad** [comment]
[Here's a pdf of the whole page printed out if you want maximum context](https://drive.google.com/file/d/0B_WbHvD-FSFPWU5lUnc3RXFMNFk/view?usp=sharing) or see below.

Do not spam:
![do not spam](https://cloud.githubusercontent.com/assets/3084796/6102103/18d6bfb2-affe-11e4-9910-d117c80cfb88.PNG)

Duplicate accounts:
![dupe accounts](https://cloud.githubusercontent.com/assets/3084796/6102104/18d80908-affe-11e4-86da-9ab20edbb612.PNG)

Added mod:
![mod update](https://cloud.githubusercontent.com/assets/3084796/6102108/18ddfd0e-affe-11e4-9c27-362bfcfe77d4.PNG)

Clarified private message behaviors:
![private message behaviors](https://cloud.githubusercontent.com/assets/3084796/6102105/18db0892-affe-11e4-9215-0042f770ec61.PNG)

Private messages are private spaces:
![private messages are private spaces](https://cloud.githubusercontent.com/assets/3084796/6102106/18db3df8-affe-11e4-8fff-b9c2f78927df.PNG)

Sexism update:
![sexism update](https://cloud.githubusercontent.com/assets/3084796/6102107/18dc189a-affe-11e4-9c0d-4cbb19becb91.PNG)

**Comment by lemoness** [comment]
These look good! One small thing: can you put a paragraph break after the
PM guidelines and before it says "Furthermore, some public spaces in
Habitica have additional guidelines"?

**Comment by crookedneighbor** [comment]
The blacksmith section looks out of date:

> The following users are members of the HabitRPG repo:
> lefnire (Tyler)
> Alys
> benmanley (Pixel)
> colegleason (Cole)
> deilann (Ryan)
> djuretic
> Fandekasp
> Lemoness
> litenull
> paglias
> SabreCat
> Sinza-
> snicker
> thepeopleseason
> wc8
> zakkain

### Missing:

crookedneighbor (Blade)
@huaruiwu - habit username?
negue
ruddfawcett - habit username?
wogsland - habit username?

### [No longer listed here](https://github.com/orgs/HabitRPG/people).

wc8
djuretic

**Comment by negue** [comment]
Habit Username is the same :)

**Comment by crookedneighbor** [comment]
@negue Great, updated the list.

Also, Ryan should be Ryan v*

**Comment by Alys** [comment]
Should we add MagicMicky and viirus to the Blacksmiths since they'll be
working on their mobile apps for us?

**Comment by lemoness** [comment]
Great catch, Blade! And yes, I think we should add viirus and MagicMickey :)

**Comment by ojintoad** [comment]
Please see [PR 4654](https://github.com/HabitRPG/habitrpg/pull/4654) latest commits for updates including the paragraph spacing as requested by @lemoness and Blacksmith name list updates per @crookedneighbor and others.
