### ISSUE TITLE
return key causes chat messages to be submitted - should we change that?

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4460]
When you're typing a chat message, the keyboard's enter key causes it to be sent instead of producing a new line. That's common behaviour for HTML forms when you're typing in text boxes, but not in textareas, which the chat message box appears visually to be.

When writing long messages, new lines are beneficial and it's annoying to have to type shift-enter (also easy to forget).

We get quite a few users who submit multiple messages when really they should be in a single one, and I suspect that at least sometimes that's because of the enter key behaviour. 

So, should we change the chat form so that enter in the textarea will not submit it?

Users who do want to submit with keystrokes could still hit tab twice to put the focus on the submit button (and we could make that more convenient by moving the markdown link out of the tab path, or using tabindex to change the focus order).
##

**Comment by crookedneighbor** [comment]
I'm in favor of this. 

I just did a version that changes it from `ui-keypress='{13:"postChat(group,message.content)"}'` to `ui-keydown='{"meta-enter":"postChat(group,message.content)"}'` which submits the form on ctrl/cmd + enter, just like Github has for comments.

We could also move the markdown link for those used to tabbing to submit forms.

Regardless, I think there would need to be a Bailey announcement to go along with this, I know I would be confused if the chat system suddenly changed. We'll stick get people reporting the "bug", but I think far fewer if we include it in an announcement.

**Comment by SabreCat** [comment]
:+1:

**Comment by crookedneighbor** [comment]
If we enable `meta-enter` for the chats, we should do the same for private messages.

**Comment by UnexpectedMushroom** [comment]
Please do, that would be very helpful.

**Comment by paglias** [comment]
Closing in favor of #8066
