### ISSUE TITLE
Repositioning of TO-DOs in the list is random

### ISSUE THREAD

**Issue by fergusincoronato** [HabitRPG/habitica#4464]
When I try to reposition a To-DO in the list, another (apparently random) TO-DO gets repositioned.

My ID is 1cefbadb-72d6-4fcf-a900-81c4dd19fcbf

I tried both with latest Chrome and latest Firefox Portable

My OS is Windows 7

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/2606 for a description of this problem, and a workaround, and to follow the progress of the fix if you wish to (you can subscribe to notifications with the button in the right-hand column).
