### ISSUE TITLE
The change username and display name options are confusing. Email address option doesn't explain how to change it.

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4468]
As described in "Display Name vs. Username" in the wiki's [User](http://habitrpg.wikia.com/wiki/User#Display_Name_vs._Username) page, we have `Settings -> Site -> Change Username` for changing the user's login name and `User -> Profile` for changing the name displayed in chat and on their avatar. It's not obvious from each of the two preferences screens what each name option is for, or that the other option exists.

I think it would be beneficial if each option had a brief description of what it is for, and a link to the other option with a brief description of what that is for.

We might even want to rename "Username" to "Login Name".

The email address portion of `Settings -> Site` could perhaps also have a brief description of how you can change your email address (i.e., send an email to admin@habitrpg.com and include both old and new addresses and your User ID). We get that question in the guilds every so often.

@lemoness what do you think about these ideas? Since it will mean adjusting the user interface, we shouldn't proceed unless you're happy.

This is probably a good task for a relatively new programmer. When you've made these changes, please include a couple of screenshots in your request so it's easy to see what your changes will look like.

**Comment by SabreCat** [comment]
I like the idea of "Login Name".

**Comment by lemoness** [comment]
I also think that we should use "Login Name" as opposed to "Display Name."

**Comment by nataliechan** [comment]
Does this need to be done asap? If not, can I maybe claim it so I have something to work towards? (Just got my local install up and am wanting to poke around, but not sure where to start)

**Comment by Alys** [comment]
It's not urgent. I think it would be a good thing for a new programmer.  It's yours! :)  Be sure to ask here if you run into problems or have any questions.

**Comment by nataliechan** [comment]
Quick question - I've finally found one of the files I need to edit (still trying to figure out the file system and where things are located), and I noticed that by changing"Username" to "Login Name", it might get confusing because the variable(s) associated all use "Username", e.g. "changeUsername", "newUsername" - should I somehow change all the variables to be "changeLoginName", etc, or just leave it?.

**Comment by deilann** [comment]
No, no, don't change the variables. The coders are not confused by the
difference.
