### ISSUE TITLE
No incentive to continue game past lvl 25

### ISSUE THREAD

**Issue by m1rrag** [HabitRPG/habitica#4469]
This is actually the issue about amount of food drops/ that the ratios are askew. I'm making this a new subject because no one ever did anything about the issue. I've actually stopped playing HabitRPG because there have literally been no incentives for me to keep playing past level 20 unless I start cheating the game. I'm even part of a group and it seems everyone's stopped playing because no one is getting enough food drops. The game is moot outside of the intrinsic rewards I get for doing things anyways (which I don't need HabitRPG for). 

For other suggestions/ discussion from users on this subject, see: https://github.com/HabitRPG/habitrpg/issues/2479#issuecomment-65039532

What I'm trying to say is this is a valuable tool for people like me who have issues with task management and incentive in the real-world for completing tasks. I'm someone who needs some form of immediate reward otherwise I turn to my bad habits to reward myself (which is why I came here in the first place). But by having no real game rewards past level 25ish, there is no point in using HabitRPG. If you want your app to be valuable to people who actually need it, check out that thread, please. I think designing a continual game that rewards those short term goals would be a fun challenge for developers. Hell, you could get grants for this thing for empowering people with cognitive and mood issues, if you actually kept developing it. I think it could be a great tool in a big way.

**Comment by lemoness** [comment]
HI Mirah!

We have a variety of things in the works that should help with this.
1. More equipment from the upcoming "Enchanted Closet" reward, unlocking
   only after you have Ultimate Gear in your class.
2. Gold-purchasable quests.

Also, note that there are nine more quests still to unlock after level 20!
At Level 30, you will unlock the Vice quest line; at Level 40, the Golden
Knight quest line; and at Level 60, the Necromancer quest line.

Thanks for your feedback!

**Comment by lemoness** [comment]
Mirah, in case you're interested - we have indeed released both the
Enchanted Armoire (more equipment) and Gold-Purchasable Quests :)
