### ISSUE TITLE
Shading not responding correctly to frequency

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#447]
One of my Habits that I've hit many times is yellow and is still giving me 1.1 gold each time I do it and two of the tasks that I've only done once each are green (which means I'm doing good at that task, right?)
With all my other Habits, Dailies, and Todos, they are responding correctly.

**Comment by lefnire** [comment]
it's not an only + or only - item?

**Comment by cleave29** [comment]
All three are plus only items, although the one yellow I've used many times and the other two greens I've used only once each.

**Comment by cleave29** [comment]
I've gone ahead and switched all of them to + / - and it seems to have adjusted.  I'm going to vote for one of the changes on Trello.  
Thanks, Tyler.  I appreciate all of your (and others') hard work on this!
