### ISSUE TITLE
winston-newrelic broken

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4471]
winston-newrelic starts up with app error here https://gist.github.com/lefnire/19f37418a0c7a0d2a0a4. https://github.com/mcku/winston-newrelic/commit/eff336f2de8edb400c33026a775913c4ba225b62 is supposed to have fixed the error, but no cigar. In the meantime, we're disabling winston-newrelic until we can find a solution. FWIW, I've tried pinning `"winston": "0.8.0",` _and_ `"winston": "~0.8.x",` (ie, pinning to 0.8.0 as well as upgrading).

**Comment by paglias** [comment]
Errors on newrelic are still shown... I'm wondering what that module did then

**Comment by lefnire** [comment]
Interesting :/

**Comment by Alys** [comment]
Is this still relevant?

**Comment by Alys** [comment]
Closing. Reopen if still relevant.
