### ISSUE TITLE
missed Dailies reduce MP gained at cron -- related to Skill Rebalancing (for 'rebalancing-2014-12' feature branch)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4473]
**Verabird is working on this**

This is related to the skills rebalancing that we are doing, as described in [Fix Overpowered Skills - Issue #3029](https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382). It will go live at the same time as the modified skills.
#### Requirements:

The amount of MP gained at cron should be reduced by Dailies that had been due but were not completed. This could possibly be done as a percentage: If you have 10 active Dailies and you leave 3 incomplete, your Daily MP Boost is reduced by 30%. However other mechanisms could be considered if you can think of something better.

The cron code is a little complex, so testing this thoroughly will be important. When you're ready to submit a PR, please list the tests you have done. If you're not sure how to test cron, or if you'd like help thinking of or performing tests, just ask here!
#### Notes:
- Do pull requests to the `rebalancing-2014-12` feature branch, not to the `develop` branch (ask in the comments here if you're not sure how):
  - [HabitRPG/habitrpg at rebalancing-2014-12](https://github.com/HabitRPG/habitrpg/tree/rebalancing-2014-12)
  - [HabitRPG/habitrpg-shared at rebalancing-2014-12](https://github.com/HabitRPG/habitrpg-shared/tree/rebalancing-2014-12)

**Comment by Verabird** [comment]
I submitted a PR but the test build didn't work. I'm a little confused about the error though. Is it more obvious to anybody else?

**Comment by Alys** [comment]
`expected 1 to sort of equal 0`  What's not to understand? ;) :)

You can ignore that. It's a test that's been failing for a while now due to code changes that aren't related to your work. We need to fix the test (or possibly the code; I haven't looked into it, but I expect others have).

I'll try to look through your code at least briefly today (Friday for me) but I will definitely look at it in detail on Saturday. Thank you for this!

**Comment by Verabird** [comment]
Thanks Alys. I just wasn't sure if the error might be applicable because I actually touched cron code this time.
