### ISSUE TITLE
prevent attribute points being gained above level 100 - related to Skill Rebalancing (for 'rebalancing-2014-12' feature branch) [$25]

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4474]
This is related to the skills rebalancing that we are doing, as described in [Fix Overpowered Skills - Issue #3029](https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382). It will go live at the same time as the modified skills.
#### Requirements:

When a user levels up beyond level 100, they should no longer be given a new attribute point to assign to one of their attributes.
#### Notes:
- Do pull requests to the [rebalancing-2015-03](https://github.com/HabitRPG/habitrpg/tree/rebalancing-2015-03) feature branch, not to the `develop` branch.
##

**Comment by deilann** [comment]
I am stupidly busier than I thought I'd be right now... If someone gets to
this before me, I will not be upset. I would like to do it, but I cannot
possibly do it fast enough.

**Comment by Alys** [comment]
Note to other developers, @deilann has been proceeding with the code required for this.

**Comment by Alys** [comment]
I have updated this issue to include a link to the new feature branch [rebalancing-2015-03](https://github.com/HabitRPG/habitrpg/tree/rebalancing-2015-03)

**Comment by Alys** [comment]
Done in https://github.com/HabitRPG/habitrpg/issues/4852

**Comment by Alys** [comment]
@chimericdream As mentioning in the PR for this, you're eligible to claim the bounty on this issue.

**Comment by chimericdream** [comment]
@Alys Cool, thanks!
