### ISSUE TITLE
Challenges are not shown in the user profile.

### ISSUE THREAD

**Issue by gpraveenkumar** [HabitRPG/habitica#4479]
Since the last two days nothing is shown in the section "Was the winner of the following challenges:" (I have won many challenges!)

Screenshot below:
![bug1](https://cloud.githubusercontent.com/assets/3744347/5620351/17b554ce-94f9-11e4-81c0-67f435cc8c29.png)

**Comment by Alys** [comment]
Can you please tell us your unique User ID? It's from Settings -> API (be sure to copy only the user ID, not the API Token).

**Comment by Alys** [comment]
Never mind, found it from the Tavern. This is GoldDust 2793ede7-f2b1-48a7-ade5-3d22bd342f8e, and there are definitely challenge wins that should be showing:

```
    "achievements": {
        "challenges": [
            "@GoldDust is a HAPPY BADGER, having completed 7 days of Healthy Badgering!!!! (Badger 101 Round 1)",
            "GoldDust is a happy badger, having completed 7 days of Healthy Badgering!!!! (Badger 101 Round 2)",
            "Weekly Focus Finder (Nov 3-9, 2014)",
            "Friendly Badgers",
            "Theme Week 45",
            "Theme Week 46",
            "GoldDust saw a RAINBOW by completing the STAG Nov 2014 Rainbow challenge!",
            "GoldDust is a happy badger, having completed 7 days of Healthy Badgering!!!! (Badger 101 Round 3)",
            "Badger @Clara Oswald to go study",
            "Badger Anysia to Write",
            "Theme Week 47",
            "Weekly Focus Finder (Nov 24-30)",
            "Clutter Patrol -- November",
            "December GEM Pom Party Tuesday (#4)",
            "Evening Pom Party 4",
            "Afternoon Pom Party 4",
            "Theme Week 49",
            "GoldDust is a happy badger, having completed 7 days of Healthy Badgering!!!! (Badger 101 Round 3)",
            "Award for Consistently Badgering Anysia to Write (@GoldDust)",
            "Hit the scrolls (belated Dec edition)",
            "Climbing the Andes with Llamas",
            "Tiny Habits Baby Steps"
        ],
```

**Comment by Alys** [comment]
This is unlikely to be a browser-specific problem because when I look at GoldDust's profile, I don't see challenges, but when I look at other people's profiles on the same browser, I do see their challenges. But regardless, I've confirmed it in recent versions of Chrome and Firefox on Mac OS.

**Comment by crookedneighbor** [comment]
It's that `"GoldDust is a happy badger, having completed 7 days of Healthy Badgering!!!! (Badger 101 Round 3)"` is in there twice.

I get this error when I open up the profile:
![screen shot 2015-01-05 at 4 23 45 pm](https://cloud.githubusercontent.com/assets/2916945/5621048/446b7d4c-94f7-11e4-834a-68b53326ec6a.png)

**Comment by gpraveenkumar** [comment]
Ah I see. That matches the timeline of the bug as well. Could you please update the database to "Round 4" instead of "Round 3"? This would fix it.

**Comment by crookedneighbor** [comment]
I'll just change the code to allow for duplicates.
