### ISSUE TITLE
Reward "Are you sure?" button

### ISSUE THREAD

**Issue by ravage484** [HabitRPG/habitica#448]
I just spent some of my coins on accident because of clicking on the reward with a touchpad, which was dissapointing.  Maybe it would be better if there was a solution such as an "Are you sure you wish to purchase X reward with Y coins?". That would prevent people repeating my clumsiness haha.

**Comment by cleave29** [comment]
Or the Undo button could take care of this.  issue #6

**Comment by wc8** [comment]
See also/vote for [Confirmation for Gold Spending](https://trello.com/c/uEo7wjkH)
