### ISSUE TITLE
Can't change habit direction/action

### ISSUE THREAD

**Issue by rebepart** [HabitRPG/habitica#4481]
b9986d66-dadd-4a3a-be72-fc62e88b61f8

rebepart

Im currently using Google chrome Version 37.0.2062.120

I made a new habit in HabitRPG and when I try to change the direction/action I click it and the buttons move so that + is above - 

when i leave edit the new habit still has both the + and the -

idk what is wrong...if there is another post like this im sorry I looked for one and found nothing...

---EDIT---

I checked again and just found out that when I press + it still moves so that the + is over the - but it does work. I'm trying to take away the - though and no matter what it's not working :/

I also tried reloading the page, logging out then logging back in, and deleting the new habit and writing it out again but the same thing happens.

**Comment by paglias** [comment]
Do you save the changes?
Il 06/gen/2015 15:33 "rebepart" notifications@github.com ha scritto:

**Comment by rebepart** [comment]
Yes I save it

**Comment by crookedneighbor** [comment]
@rebepart Would you mind taking a couple screenshots?

**Comment by rebepart** [comment]
Sure it will have to be tomorrow I have no computer currently

**Comment by rebepart** [comment]
I believe the problem was the computer itself. I was using a school computer so there was most likely something wrong with it not with the website (I will mention that I have used HabitRPG with the same computer before and it worked normally). When I went to habitRPG with my Laptop it worked fine (the buttons still moved a little bit but not enough to make them not work)

I'll try again with the same computer and let you know if it is the computer

**Comment by crookedneighbor** [comment]
Ok. I'll close this issue, but I'd still be curious to see it.
