### ISSUE TITLE
Dates on to-dos only showing part of the date

### ISSUE THREAD

**Issue by kaitmiller** [HabitRPG/habitica#4482]
When I switched the date format to the new option of yyyy-mm-dd, I noticed that only the year was showing on my to-dos, no month or day. It occurred to me that only the month and day showed under the old format, so maybe there just isn't enough space for the whole date.

Here's what it looks like under yyyy-mm-dd:
![screen shot 2015-01-05 at 10 14 04 pm](https://cloud.githubusercontent.com/assets/8716943/5630498/6133186e-958c-11e4-8d2d-761277eb3842.png)

And here it is back to the standard mm-dd-yyyy:
![screen shot 2015-01-06 at 10 03 23 am](https://cloud.githubusercontent.com/assets/8716943/5630499/67b10822-958c-11e4-817b-8fab698e97cb.png)

I'm using Chrome on a MacBook Air. Just to check, I moved my dock to the bottom of the screen and made my browser window as wide as it could get, and that didn't make any difference in how the numbers appeared.

My user ID: 0974a026-4ff0-4f84-bc0c-c06f8e3c4303

**Comment by crookedneighbor** [comment]
[Here's the culprit](https://www.npmjs.com/package/edit-google-spreadsheet):

```
{{task.date | date:user.preferences.dateFormat.substr(0,5)}}
```

**Comment by deilann** [comment]
Yeah, I figured that's what it would be...

**Comment by crookedneighbor** [comment]
@deilann Do you have an opinion about whether it should be done in the jade file ([like my pr](https://github.com/HabitRPG/habitrpg/pull/4484)) or as a custom Angular filter?

I'm fine with just getting it done in the Jade file for now, the only reason I can think of to create a filter for it is if the truncated version of the date gets used in more than just the tasks.

**Comment by deilann** [comment]
I'd say the more agile way to do it is to go ahead and do it in the jade
file then consider an Angular filter in the long run.

**Comment by crookedneighbor** [comment]
Sounds good to me.
