### ISSUE TITLE
Cannot find module '../build/Release/bson' (and proposed fix)

### ISSUE THREAD

**Issue by tohn** [HabitRPG/habitica#4483]
I'm running habitrpg on my own server (Thank you for this great app btw! :)) and I'm getting a BSON Error/Warning at start:

```
[habitrpg@server ~]$ grunt nodemon
Running "nodemon:dev" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./src/server.js`
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

A fix for me was this (found it via `grep -irs "build/Release"`):
Change all occurences of `bson = require('../build/Release/bson');` to `bson = require('bson')` in the file `/path/to/habitrpg/node_modules/mongoose/node_modules/mongodb/node_modules/bson/ext/index.js` and install bson via `npm install bson`.

My OS: Arch Linux x86_64 (Kernel: 3.17.2-1-ARCH)

**Comment by PortNumber53** [comment]
Had the same issue while trying something completely different, but still Mongoose. so it seems Mongoose package is too  blame :)

**Comment by tohn** [comment]
I just did an update to the latest development and this issue was no issue anymore, so I will close it ;)
