### ISSUE TITLE
Suggestion: Ability to join groups/clans for similar interests

### ISSUE THREAD

**Issue by gitirs** [HabitRPG/habitica#449]
I was hoping for a very simply addon. Suppose I want to practice guitar. I go to the clan/group for people making guitar into a habit. There people can message each other and give each other "high fives"(RPG wise=clan strength points?) of some sort for accomplishing the daily task/hobby(the guitar group will have a sidebar that shows when a member finishes the daily habit). This brings a feeling of community which really helps in forming new habits and what not because the clan only gets as strong as the members in the group finish their daily habits.

**Comment by busterroni** [comment]
I like this idea, however it is not as simple as you think... The idea may be simple but the developers would need to code a lot. Still, with the progress they're making they could do it quickly :P

**Comment by wc8** [comment]
You can read more discussion about Groups/Party feature here:#58
I added [Shared Interest Groups](https://trello.com/c/CuEnnOpe) since it has been at least referenced indirectly as part of other requests.
