### ISSUE TITLE
Custom Day Start box registers changes too quickly (can trigger cron inappropriately)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4490]
As reported by papabearrr in the Tavern, when you are typing into the Settings -> Site -> Custom Day Start box, every keystroke can be immediately saved to the server. Confirmed in Firefox and Chromium on Ubuntu.

For example, if it starts as 23 and you want to change it to 17 by hitting backspace twice and then typing 1 and 7, it will save three separate times: 2, then 1, then 17. Using the arrow buttons is even worse if you're arrowing to a number several hours away from the current number.

Because changing the Custom Day Start can trigger cron immediately, this can result in unpleasantness.

A workaround is to type the time you want in a text editor and copy-paste it into the Custom Day Start box, but that's far from intuitive for any users who aren't already aware of the need for this.

Can the box be changed so that it doesn't save the result until the user explicitly requests a save? Or perhaps a drop-down of all hours so that your only option is to pick the correct hour in one click? But the latter might be troublesome for people who have poor mouse control.

**Comment by quettandil** [comment]
I think I had this issue, too. I was changing my custom day start from 9 a.m. to 10 a.m., at around 3 p.m. I had already logged on after my original 9 a.m. cron and didn't die, but as I was changing the CDS, sometime in the middle of hitting backspace I died, and then noticed it hadn't been working as I expected, that there was a persistent "0" and I needed to just put the "1" in front of it, instead of deleting it... but too late, I was dead.

**Comment by lemoness** [comment]
I wonder if this is the majority of the "changing custom daystart sometimes
triggers cron" issue? Do we have indication that it is something else, or
could this be it?

**Comment by crookedneighbor** [comment]
Would it be as simple as changing `ng-change='saveDayStart()'` to `ng-blur='saveDayStart()'`?

The one case where it might be a problem is if the user clicks on something without leaving the input. I'll do some testing on my local install.

**Comment by crookedneighbor** [comment]
Worked even when navigating away to a different page on the site. Submitting a PR.

**Comment by Alys** [comment]
Awesome, thanks @crookedneighbor!
