### ISSUE TITLE
Costume does not appear in app

### ISSUE THREAD

**Issue by mlivits** [HabitRPG/habitica#4491]
Hello,

The avatar's costume does not appear in the app, instead you can only see the avatar's underlying and active gear.  When I pull up the avatar on my iphone's search engine, I can see the costume.

877e1b83-96a6-4669-8a10-1f9e2c9b47c9

**Comment by Alys** [comment]
When new art is added to the website, it always takes a while to show up on the phone. The next time the app is updated, the items will appear. That should be very soon now. The android app has already been updated; I believe Apple's iOS approval process is slower.

**Comment by lefnire** [comment]
yeah, apple takes ~2weeks to approve. I submitted yesterday

**Comment by crookedneighbor** [comment]
@lefnire did you resubmit with the fixes you and @negue made?

**Comment by lefnire** [comment]
resubmitted at https://github.com/HabitRPG/habitrpg-mobile/commit/b1586f848598a66b4f0b13b69083ee5d4ccda645
