### ISSUE TITLE
open "tasks" page only with choosen tags

### ISSUE THREAD

**Issue by thaenor** [HabitRPG/habitica#4495]
Hi, this is a suggestion I came up with, noticed that now that started having too many dailies and habits and filtered them with tags.
When first opening the "tasks" page I suggest only a set of tags (defined by the user) be displayed.

Maybe a user doesn't want to see all his tasks, dailies and habits and start filtered out by a specific tag.

**Comment by Alys** [comment]
Your tags last used should be selected when you reopen the tasks page, which I realise isn't exactly what you ask for, but it might help. For your actual request, it's not a bug but a feature request, so it's best reported on Trello with related feature requests. To do that, use the Help menu and select Request a Feature. Follow the instructions on the page you'll be taken to. The Trello card that you want is called "TAGS v.2 (Tag ideas/enhancements)"
