### ISSUE TITLE
Cannot Remove Inactive Challenge

### ISSUE THREAD

**Issue by Kaelan13** [HabitRPG/habitica#4496]
(So I hope I am explaining this right and posting it in the right place)
I have a daily challenge from Clean the Dungeon (December Edition) that I cannot remove or delete. There is no button and I already left C.t.D (Dec).

**Comment by deilann** [comment]
Click one of the tasks as if you did it. Sync. The megaphone should now be
broken and allow you to remove the tasks.

**Comment by Kaelan13** [comment]
I've tried that but the megaphone did not highlighted

**Comment by Alys** [comment]
@Kaelan13 See the instructions in "Deleting a Challenge Task" in the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) page. As it says there, you might need to do this a few times before it works, or you might have better luck on the mobile app. I'm sorry it's so annoying! Let us know in a couple of days if it's still not working (or immediately if you've already been trying for two days, and if the mobile app hasn't helped or you don't have access to a mobile device).

**Comment by Kaelan13** [comment]
I didn't even think to try the mobile app! That helped me so much, it is gone! Thank you so much for your help!

**Comment by Alys** [comment]
Thanks for letting us know! :)
