### ISSUE TITLE
Add due date for Todos tasks

### ISSUE THREAD

**Issue by p-matvienko** [HabitRPG/habitica#45]
Please, add due date for tasks. If task expires then health decreases.

**Comment by racuna** [comment]
:+1:  very usefull for paying bills.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote here for [Disease on Missed Deadline](https://trello.com/c/QmhxaBRE) and [Urgency: Dates & Deadlines](https://trello.com/c/i6kXvNY2)
