### ISSUE TITLE
New habits/todos and XP not sticking across different browser sessions

### ISSUE THREAD

**Issue by thatgirldm** [HabitRPG/habitica#450]
I had the site open on my home browser, then went to work, where I added a few tasks and got some XP for habits. When I got home, after signing back in, the new tasks and XP weren't reflected on my profile. I re-created the tasks (but didn't attempt to fix the lost XP). When I got to work the next day, again after signing back in, the new tasks were gone, and today when I got home, again the items and XP I'd added at work were gone. 

I use Firefox, 18.0 at home and I believe 17.1 at work. Neither is set to remember any history, to keep caches, or to allow third-party cookies (although primary cookies are allowed). There's no error messages, although I was getting hit hard by the server-overloaded bug for a while. If there's any other data you want me to try to capture, let me know.

**Comment by tmas** [comment]
This almost certainly means that you're not actually connected to the server while you're using habit. Habit isn't very good at dealing with disconnections, so you should refresh the page to make sure you're connected when you're ready to make changes. You can see if you're connected by glancing at the top of the page, where habit will tell you that it's offline and give you the option to reconnect (which is not as reliable as refreshing the page).

**Comment by thatgirldm** [comment]
I'll give that a shot. I did notice that it sometimes said "disconnected", but when I saw that I would log out, refresh, and log back in (within the same browser), and it would reconnect with all my tasks, etc still there, so I didn't think that was the problem...

**Comment by wc8** [comment]
One more thing: I find refresh AFTER changes is sometimes as important as refresh before. That way, I can confirm the changes registered. I think connected/disconnnected issues are an area that's being worked on.

**Comment by horusofoz** [comment]
Resolved as behaviour caused by connection interruptions.
