### ISSUE TITLE
Checklist backending

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4500]
As I understand it, when creating checklists for a task, the backending for the "new item" is a bit wonky, something that particularly affects me since Habit is very slow for me.

Correct me if I'm wrong: You hit the enter button to create a new checklist item. Habit says, oh, okay, you're adding a new checklist item, let me increment this and that, and start notifying the server (which returns a lot of lag). Alright, got that done, now let's create the new input box, fade in effects or whatever, which come through very, very slowly for me, now move your cursor. You can type now!

Of course, on the user's end, this is bad UI design. As soon as I hit that enter button, I'd like to be typing. Not only is there (for me) amplified lag in creating the box, but I can't type in the box as soon as it appears, sometimes making me type the first few characters in the old box and then continuing my keystrokes in the new box.

Thus, I propose that moving the cursor to the box is the first thing that happens upon enter, even if the box has not appeared visually yet, and then whatever server-update stuff (which I personally think is updated too many times during typing, increasing the lag for me).

I expect not many have as much lag I do, but I feel like the code should be done a bit differently. Excuse me if I'm just being annoying about code structure; you can ignore if you'd like. :P
##

**Comment by crookedneighbor** [comment]
@negue Do you think the directive conversation in [your latest pr](https://github.com/HabitRPG/habitrpg-mobile/pull/325) will help with the lag?

**Comment by lemoness** [comment]
This happens to me frequently as well.

**Comment by paglias** [comment]
still an issue?

**Comment by lemoness** [comment]
Yes, this still happens to me!

**Comment by librarianmage** [comment]
Is this still an issue, with the new client?

**Comment by paglias** [comment]
should be
