### ISSUE TITLE
Datepicker Week numbering is off

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4502]
On the datepicker for due dates: At least for me, the weeks of January are numbered 52 through 57, which, if I'm not mistaken, is not supposed to be like that. The weeks of February are also numbered starting on 5. I don't know if we want the first partial week of January to be 1 or 52 (as the last partial week of December), but all I know is that I don't think there's a 55th week to the year, and it certainly doesn't normally occur in January ;D

That is, unless you're all aliens and I didn't know you started years on the 5th week, in February. idk.
##

**Comment by crookedneighbor** [comment]
Here's a screenshot:

![screen shot 2015-01-09 at 10 06 57 pm](https://cloud.githubusercontent.com/assets/2916945/5690391/e0ca8190-984b-11e4-8637-24b9eed7542b.png)

**Comment by librarianmage** [comment]
@crookedneighbor Has this been taken care of? When I use the datepicker, it shows:
![screenshot 2016-04-15 at 1 33 43 pm](https://cloud.githubusercontent.com/assets/12386291/14571418/c4169672-030e-11e6-843b-06b28486af03.png)

**Comment by Alys** [comment]
It might be browser-dependent, or maybe even year-dependent. It might also have been fixed by the third-party library that we use for the calendar.

@MathWhiz what browser were you using just then? Is it correct for 2015 too?

**Comment by librarianmage** [comment]
@Alys Chrome, and it is correct for 2015

**Comment by Alys** [comment]
It doesn't happen for 2015 in Firefox either. Let's assume the third-party library was fixed. Thanks @MathWhiz !
