### ISSUE TITLE
Additional information in the translated versions.

### ISSUE THREAD

**Issue by naever** [HabitRPG/habitica#4506]
I posted this question on trello and was asked to come here, so here I am! I _think_ I'm in the right place, otherwise, my apologies... 

I've been translating the community guidelines to portuguese on transifex and it dawned on me that a lot of what's there is really unhelpful (and even misleading) to someone without any grasp of english. It all deals solely with parts of the site where that is the only spoken language, and members of the team who (I'm assuming, sorry if I'm wrong.) should be spoken to in that language as well.

So I wondered whether it might be good idea to add some extra information. Like, a warning on the overwhelming majority of english use on most areas, a link to a local guild where non english speakers can find help from other users along with the newbies guild, the languages the mods speak along with the names and emails provided to contact them, perhaps the names of the team translators that would be willing to act as interpreters, that sort of thing. I'm not sure but I think other areas of the site, like tutorials and contact pages, might need the same kind of tweaking.

Should I do any of that? (or something else entirely?). I'm mostly asking this regarding the portuguese translation I'm working on, but I believe all translations would benefit from the added clarification. I don't know what that would entail, but maybe it's just a matter of communicating between teams? 

Anyway, that's all just a suggestion. Thank you for your attention!
##

**Comment by Alys** [comment]
I'm very much in favour of anything that makes the site easier to use for people who don't have good English skills, although being an English-only speaker I don't have many helpful ideas. A couple of points though:

You write _"It all deals solely with parts of the site where that is the only spoken language, and members of the team who (I'm assuming, sorry if I'm wrong.) should be spoken to in that language as well."_ The Tavern and the Newbies guild aren't English-only areas. We get posts regularly in other languages, and that's a good thing. I've seen at least one staff member respond in a language other than English, so English is definitely not a requirement for those areas. We also monitor non-English posts just as we monitor English ones. I use Google Translate on every post I see in other languages, and I have deleted several that don't abide by the Guidelines. Now that we have community flagging, our multilingual users have started flagging inappropriate non-English posts. 

Links to language-specific guilds can be found at [Guilds Guide](http://habitrpg.wikia.com/wiki/Guilds_Guide#Language_and_Local_Community_Guilds). I was thinking just this morning that it would be good to bring them into HabitRPG itself in some way. Perhaps for each language, there could be a short piece of text that describes one place to go for more information (one guild perhaps or one wiki page, and that location could provide as many links as required to other places), and then that piece of text is displayed somewhere on HabitRPG when the site is being used in non-English languages.

I like your other ideas too. If you have any more, definitely add them here. We certainly should discuss this.

**Comment by lemoness** [comment]
I speak Spanish and some French!

I really like the idea of directing users to a certain guild when they
automatically sign in using that language - social features are really
important to keeping people interested in HabitRPG, and many of our
non-English-speakers have to work harder to search that out. Maybe display
the message over the Tavern and Guild pages?

Something like
"Welcome to the Tavern! Most people speak English here, but you can join
one of our multilingual guilds [here]."
or
"Welcome to the Tavern! Most people speak English here, but you can join
our guild for speakers of X [here]."

**Comment by GreenAppleFields** [comment]
I believe I'd seen the original comment on transifex and already thought it was a good idea :) If anything is decided about this I'd gladly help out with dealing with Italian users.
