### ISSUE TITLE
232/200 XP, no level up

### ISSUE THREAD

**Issue by galinavaks** [HabitRPG/habitica#4509]
User:
9183afb2-fe40-4dc4-99b0-1feeee2a52c6
![image](https://cloud.githubusercontent.com/assets/10512457/5717941/b139a2ea-9b10-11e4-9b52-eca2e85cc1d1.png)

**Comment by deilann** [comment]
Please search before opening new issues.

See: https://github.com/HabitRPG/habitrpg/issues/2143
