### ISSUE TITLE
Suggestion: Shading on To-Do-List starting less red

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#451]
Someone mentioned this passing on Trello as well, I think: the new to-do items start out yellow and progress to red (or at least reddish) quite fast. And while that does bring a sense of urgency, it's also quite daunting - at least to me, when I have a long list of tasks that all just need more time for finishing, even if I am working on them.
So maybe new items could start out blue and then progress to red?

I could also imagine it would be nice, once the subquests (checklists) are in the system, that the colour freezes for a while or goes back up one shade each time you complete one of the subtasks. This could give a sense of "yes, I'm working on it, there is progress" even with a very long to-do list with lots of larger tasks.

**Comment by wc8** [comment]
You can vote for this request here: [Slow reddening of Todos](https://trello.com/c/FBHGlCbd)
Press "v" to vote if you don't see the vote button there.
