### ISSUE TITLE
Dragging a card off the bottom of the screen extends the page

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#4511]
Title says it all, really. Once you move the card (habit, daily, to-do or reward) back up, the page shrinks again. Chrome 39, Ubuntu 14.04; some extensions (including Stylish) installed, but the issue persists even with all custom CSS disabled.
##

**Comment by paglias** [comment]
I'm going to close it, if someone is still bothered by this behavior we can reopen
