### ISSUE TITLE
Some dailies remain checked the next day.

### ISSUE THREAD

**Issue by zarbars** [HabitRPG/habitica#4512]
I have this issue repeatedly and it clears up after a day or two, but I cannot continue completing certain dailies because they remain checked the following day. Refreshing or syncing multiple times doesn't solve the issue. It doesn't seem like I'm taking damage from them or losing money, but it defeats the purpose of the "daily" function. 
Good luck, habitrpg team!

**Comment by Alys** [comment]
Is it only SOME of your completed Dailies that remain ticked? It's not all of them?

**Comment by zarbars** [comment]
Yes, it seems to change around different dailies, but there tend to be a few that remain checked sometimes. Most of them refresh as normal, it's just 3-4 dailies that glitch.

**Comment by Alys** [comment]
Thanks @zarbars! This is a known issue (https://github.com/HabitRPG/habitrpg/issues/4313) and we are trying to work out what's causing it. If you have any more problems with it, could you please report it there? I've mentioned your latest report there already.
