### ISSUE TITLE
Converting Tasks to other Types (Should it be allowed?)

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4514]
See #4513 for why this is important.

Either the API needs to be adjusted so [type can not be changed](https://gist.github.com/lefnire/6b9f183d09d9a391a85b), or adjusted so that when type is changed, [it moves it to the appropriate user attribute](https://gist.github.com/lefnire/afbcf83f6d1dac6617dd). (Both gists from lefnire)

Anybody have thoughts or preferences? 

Since data specific to the task type, I'm thinking of daily and habit history, can not be moved to a task of a different type without major wonkiness, I'd prefer that type just be immutable. If a user or program interacting with the API really wants to convert a task, they can always copy the data, make a new task of the desired type and paste in the relevant data for that type.

**Comment by Alys** [comment]
Create new task of correct type, copy appropriate data, delete old task. If you do it that way, as opposed to just editing an existing task, there's probably less chance of forgetting to change some of the attributes, especially if HabitRPG later adds new attributes to some task types and old code isn't updated to match.

**Comment by crookedneighbor** [comment]
@Alys So are you in favor of making the `type` attribute immutable then?

**Comment by Alys** [comment]
I haven't thought much about it, and probably won't develop a solid opinion either way for that specific question.

There's probably several ways a badly-written third-party app could mess up a task, not necessarily with the type attribute. What we probably want is a sanity-checker for all tasks that checks all attributes and gives them appropriate values when needed, if the API doesn't already enforce that.

**Comment by crookedneighbor** [comment]
From my initial testing, the simple act of forcing the type to be immutable cleared up the wonkiness I was able to create in the todoist issue. Will do some more thorough testing later.

**Comment by paglias** [comment]
There's something I don't understand looking at the code, we store habits/dailies/todos/rewards in different object in the user model (https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L349-L352) so I think we could simply remove the `type` attribute at all

**Comment by lefnire** [comment]
@paglias we could remove it, but the type attr is used as a convenience in various locations (html, cron, score, etc) - which would be overhead to determine given the list it's in.

Eventually, I'm moving to tasks stored as objects, which would mitigate a lot of this ([main](https://github.com/habitrpg/habitrpg/tree/tasks-obj), [shared](https://github.com/habitrpg/habitrpg-shared/tree/tasks-obj))

**Comment by paglias** [comment]
@crookedneighbor since your pr is merged, we can close?
