### ISSUE TITLE
Casting Burst of Flames can grant more experience than the leveling threshold without the character leveling.

### ISSUE THREAD

**Issue by kngspook** [HabitRPG/habitica#4517]
The experience bar in the screenshot sort of explains it. I just cast Burst of Flames repeatedly on a very red daily.

![screen shot 2015-01-14 at 3 46 03 am](https://cloud.githubusercontent.com/assets/37399/5738355/31adcb6a-9ba0-11e4-94c2-0f951139a93e.png)

I then checked off a habit, and immediately leveled.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2143
