### ISSUE TITLE
Challenge daily still there, Challenge is not

### ISSUE THREAD

**Issue by BrassOtter** [HabitRPG/habitica#4519]
Alright, so after a brief leave of absence, I returned to habit RPG to find myself back at level one. Not surprising at all. But, I've got four challenges on my tasks list, and they don't how up in the challenges tab. I can't rejoin them to remove the tasks, and I'm stuck with a broken daily that I have to complete and get 'free' EXP and gold or it damages me.

**Comment by Alys** [comment]
Please see "Deleting a Challenge Task" in the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) page. If the full process described there doesn't help, tell us here and we will reopen this issue.
