### ISSUE TITLE
 Feature Request: integration with Goodreads or similar.

### ISSUE THREAD

**Issue by excentris** [HabitRPG/habitica#452]
It would be nice to integrate with Goodreads or LibraryThing (or something similar) for reading habits, goals and accomplishments. Goodreads and LibraryThing both have an API. I am not sure about their terms and conditions though...

**Comment by horusofoz** [comment]
Raised as [Trello Card #176](https://trello.com/c/CyxYB38C). Please navigate to the page and vote for your suggestion.
