### ISSUE TITLE
Cron related issue between mobile and browser?

### ISSUE THREAD

**Issue by djstinkay** [HabitRPG/habitica#4520]
I am having a cron issue - and it seems to be related to using my browser and my mobile device.  I'll check off as many dailies as i can on my browser before I go to bed, then make sure to hit sync, shut down my browser and machine, and use my mobile device to check of the remaining items just before hitting the sack.  
Starting a few days ago, when I make this switch, many of the tasks I already checked off are unchecked on my phone (even after a restart, logging out and back in, and syncing/refreshing).  If I check them off from my mobile (for a second time), they are STILL checked in the morning - both on my phone and on my laptop.  

This has only been happening for less than a week.

My mobile device is an Xperia Z3 running on KitKat
User ID: 2187527d-e137-4800-9089-1ea27e21a3be
Chrome version Version 39.0.2171.95 m

**Comment by paglias** [comment]
@djstinkay thanks for the report. Could you check that you're using the latest version of the app and that Google Play shows no updates for it?

**Comment by djstinkay** [comment]
I just double checked, and everything is up to date. 

Sent from my ludicrously huge smartphone.

---- Matteo Pagliazzi wrote ----

**Comment by Alys** [comment]
The only time I ever had a cron problem (excluding the problems of cron just not running at all or running twice) was when I was using both phone and mobile (something I don't usually do): https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-67069390  I wasn't able to replicate it.

@djstinkay's report here is another instance of there seeming to be two "versions" of his data like this: https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-69973523 but with refreshing not helping as paglias notes here: https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-69984389

**Comment by Alys** [comment]
@djstinkay We're tracking this problem in the issue I linked to above, so I'm going to close this one now, but I recorded your report in the other issue so it won't get lost.
