### ISSUE TITLE
Quest stats not updating?

### ISSUE THREAD

**Issue by Shibara** [HabitRPG/habitica#4523]
Hi,
It seems something might be off with my quest stats. When the quest system first was introduced, I did a lot of quests on my own. A few weeks ago I joined a party and we have been questing together, even quests I did before on my own. My stat monitor still does show that I did all quests only x1, and at least one quest is even completely missing (Laundromancer/Mundane pt. 3). As a result, I also didn't get the quest item. However, I did get pets from pet quests.
Did I do something wrong, or might there be a glitch with my account? Thanks for looking into that matter :)
API: 604f9b07-6221-4309-a8e3-c44817f91132

**Comment by crookedneighbor** [comment]
Using the member look up service in the api, this is what is displayed for your completed quests:

```
{
   "quests": {
      "penguin": 1,
      "atom1": 1,
      "moonstone1": 1,
      "goldenknight1": 1,
      "moonstone2": 1,
      "spider": 1,
      "octopus": 1,
      "harpy": 1,
      "vice1": 1,
      "rat": 1,
      "hedgehog": 1,
      "gryphon": 1,
      "ghost_stag": 1,
      "evilsanta": 1,
      "egg": 1,
      "dilatory": 1
    }
}
```

I believe mundane quest line has the key of atom1, atom2, atom3. You should have the nameless helm (`head_special_2`) if you completed the mundane quest line, but I don't see it in your owned equipment object. Did you die and lose it? If so, is it available for purchase in your rewards?

Devs, I haven't had a chance to peak into the code regarding this, but joining or leaving a party shouldn't reset your quest achievements, right?

**Comment by deilann** [comment]
No, it shouldn't.

There's also a question: did you actually participate in the atom3 quests?
Does your party chat show you ever doing damage/finding items? If you join
a party in the middle of a quest or they start before you accept, you are
not actually participating and you will not get the achievement/rewards.

**Comment by Shibara** [comment]
Thanks for checking :)
I should have participated, yes. When I first joined the party, they were already in a quest, that's where I learned about participation (earlier I had tried to recruit my own party, had a member and he was not doing any damage because he was in the party, but not in the already started quest). 
Problem is, this has happened... probably at the beginning of December, and I can't truly recall anything from that. But just two days ago my party did Free Yourself of the Dragon's Influence. I did this quest on my own just when it came out, I'm absolutely sure of that.
Regarding the quest log, I don't see any entries dealing damage, neither from me nor from others. Haven't since I joined that guild (Mandalorian Guild) - my single person guild showed damage entries. I only see all of us casting party spells, and I see collection prompts (we just started Mundane 1 and I collected 0 bars of soap).

**Comment by crookedneighbor** [comment]
I just want to clarify, you said "guild" a couple of times, but you meant "party", right? I ask because guilds don't do quests, just parties. I'm sure that's what you meant, since you describe participating in a collection quest with the party later.

Just to be sure, whenever a quest is initiated from another member of your party, a modal pops up for you that asks if you want to accept the quest. If you decline, or your party begins the quest without you being a part of it, the quest will begin without you participating. You'll still see the other members progress in the quest, but you won't be a part of it.

I want to confirm that for the second time you did Free Yourself of the Dragon's Influence (`vice1`), you either started the quest or accepted the invitation from a fellow party member. Is that correct?

**Comment by Alys** [comment]
Free Yourself of the Dragon's Influence is "vice1" which is in your list of accomplished quests.

To be sure of seeing all quest log entries, you need to click the "Fetch Recent Messages" button. Don't rely on a reload or full-page sync.

Note to devs, the "Mandalorian Guild" party is huge - close to 40 members the last time I looked (less than a month ago).

**Comment by Alys** [comment]
@crookedneighbor, the "Mandalorian Guild" is definitely a party. :) I've looked into it before.

**Comment by Shibara** [comment]
Oh myyy... sorry, yes, of course I meant a party, not guild! (confusing name! ;) )
Yes, I know the popup, and I have experienced all possible outcomes (declined, accepted and party started without me). I was a member of the party and I had accepted the invitation. I also was shown in the quest list before the initiator started the quest as having accepted.

However... it might just be that I had no "the quest is over, all members have been awarded their stuff"-window. I honestly can't remember exactly, sometimes the popups dissapear quite quickly or I'm ticking them off automatically. 

As Alys said, the party is huge, so the entire quest was over within hours. I think from the moment the quest was started until it was finished I was not online once. Could this be a reason? 
But that wouldn't explain why I see never anyone dealing damage, regardless which quest - others take longer and I should be able to read it in the logs, shouldn't I?

Sorry for causing trouble and thanks for your ideas! :)

**Comment by Shibara** [comment]
We just finished one of the dinosaur quests (the one with the rage bar) and for the first time since joining the party I see how much damage everyone was dealing (can't see any damage I dealt, but that's probably because I log in only in the evening and everyone else had dealt a lot of damage already). So... maybe my problem might be solved if the questlog now apperas correct. I will update you when we do a quest series if I receive the legendary item.

**Comment by crookedneighbor** [comment]
@Shibara Thanks, keep us updated!

**Comment by deilann** [comment]
@Shibara Did you receive the legendary item?

**Comment by Shibara** [comment]
Oh, I'm so sorry, I forgot to update you :( Yes, I have received the item. Still have not figured out where the problem was at first, but now everthing is working just fine. Thanks for all your help! :)

**Comment by deilann** [comment]
My guess would be the boss was usually finished before you cronned. :) I'm going to close this. If you have issues again, just let us know and it can be reopened.
