### ISSUE TITLE
Habit progress chart duplicate date

### ISSUE THREAD

**Issue by jakechen** [HabitRPG/habitica#4525]
Hi all,

Clicked '+' on a habit tonight and checked the chart. Instead of modifying the existing score it added a new point as if it was tomorrow. However both dates now displays today. See below for example.

![screen shot 2015-01-15 at 8 56 21 pm](https://cloud.githubusercontent.com/assets/449311/5771004/744f5bb8-9cfa-11e4-8fb5-acafc17db277.png)

Perhaps something with the timezone? E.g. my local timezone is still day 1 evening but GMT is day 2.

---

ID: 7dab6dbe-ad41-4b50-82c9-3079eeb48991
Chrome Version 39.0.2171.95 (64-bit)

**Comment by paglias** [comment]
@jakechen I would say this is the normal behavior for a plus habit, you can have multiple entries in a single day. Dailies instead will show the score only once per day
