### ISSUE TITLE
Can't accept quest invite

### ISSUE THREAD

**Issue by cthiess1** [HabitRPG/habitica#4526]
User ID-  c32d7d5b-3faf-42c8-8a45-10d7a0b17048

Whenever I click accept on my quest invite, this message pops up in my browser.

"Error Cannot read property 'rage' of undefined" (see Chrome console for more details).

This occurs even when I close everything and try again in Internet Explorer. Here are the Javascript errors that came up after I tried to load the page in Chrome with all my extensions disabled.

 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-7b1bd051.js:27 Object
https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=medium&hl=e…_1421414961512&parent=https%3A%2F%2Fhabitrpg.com&pfname=&rpctoken=19946941 Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habi…c%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey Failed to load resource: net::ERR_CACHE_MISS
https://www.facebook.com/plugins/like.php?action=like&app_id=17252516279391…=en_US&ref=.VLkSLbqrGI8.like&sdk=joey&send=false&show_faces=false&width=90 Failed to load resource: net::ERR_CACHE_MISS

Additionally, whenever I try to access my party page now, the screen says I'm in either not in a party or it's loading too slowly. It doesn't seem to be running slowly at all, and I can still see my party members' avatars at the top of my page.

**Comment by Alys** [comment]
The two error messages are likely from the same source. Something is stopping the party from loading correctly, and the quest error is probably saying it can't read property 'rage' of an undefined party.

@cthiess1 is definitely in a party (gid aa7fbf5d-4c6c-4025-8b62-1d817316bc81, has nine members in total).

I could adjust the party data to record cthiess1's acceptance of the quest invitation, but cthiess1 is the final person to accept (all others have already accepted) and I'm not sure if the quest would then automatically start. I'll look into that if we can't quickly find a solution for the error.

This might be just a temporary error. @cthiess1 try again in a couple of hours. Definitely tell us if it's still not working!

FYI to other devs, it's past my bedtime so if anyone else wants to look into this, feel free!

**Comment by Neopkwaii** [comment]
cthiess1-I'm in the same boat, although I only have the first error.

UserID: 2e17c18a-54d6-4a85-9a18-117541a4222b

I have been in the inn for the past week (during the Ragemonster strike), and I am the last person to accept the quest for my party of 4, and I receive this error:

Error cannot read property 'rage' of undefined"  (see Chrome console for more details.

When I visit the party screen, it states that I'm not in a party-yet I see all 4 avatars across the top of my page.

I've used the ap on my phone, 2 browsers on my phone (dolphin & regular verizon/Samsung browser), and 2 browsers on a tower (ie version 9 & just installed yesterday Mozilla)-so it's not the equipment....and I'm not on anything google....clearing cache doesn't work as this is the first time I've logged into Habit on this browser.

*editing for ease of use.  Realized it didn't actually describe my problem the first time.

**Comment by nhessler** [comment]
Error: "Error Cannot read property 'rage' of undefined" (see Chrome console for more details).

We are having this problem in our group as well. The person with this error is unable to accept quest invites or invite others to a quest. We've removed member from group and re-added, as well as trying different quests and different browsers (Safari, Chrome) but the error still pops up for them in every scenario we've tried. Below I've listed our GroupID and The UserID of the person having the problem.

GroupID: a84e9f7e-eef3-4b81-b118-9edb1c57eabc
UserID: 6485fab9-b829-43d2-8522-e911a2e6c1ca

**Comment by unclebeard** [comment]
This error troubled my party today when trying to accept Moonstone Chain. No matter which user was last to accept, the last user got the error. We canceled and tried one of the new dinosaur quests with no problem.

**Comment by Alys** [comment]
Are all of the quests that are showing this problem collection quests? I.e., no boss? If so, it could be that there's code somewhere that references `boss.rage` without checking to see if `boss` exists. I'll look into that soon if no one else does first.

**Comment by Neopkwaii** [comment]
Alys; we are trying to do the polarbear pet quest from last winter season.  I honestly don't know if it's collection or not, but I believe so.

And I thought you were going to bed 2 hours ago!!!!

**Comment by Alys** [comment]
@Neopkwaii yes, it is, thank you!

**Comment by Alys** [comment]
**devs**: 

I reckon this is it: https://github.com/HabitRPG/habitrpg/blob/develop/views/options/social/boss.jade#L56-61

When HabitRPG tries to display the quest box in the party page, it fails for collection quests because there's no `boss.rage` to satisfy the `ng-if` and other code there.

I'm lacking sleep so I shouldn't be programming for production fixes. :) Can someone else do a fix?

**Comment by crookedneighbor** [comment]
@Alys I'll look at it now. GO TO SLEEP.

**Comment by Alys** [comment]
I can't! Too wired!!!! :)  Thanks for taking this.

**Comment by crookedneighbor** [comment]
It's actually this line: https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L665

The if conditional above that checks for boss needs brackets. Pushing now.

**Comment by SabreCat** [comment]
Whoops! My bad there!

**Comment by crookedneighbor** [comment]
No problem. Happens to everyone!

**Comment by crookedneighbor** [comment]
We'll be deploying this fix in the next half hour. Thanks for your patience everyone!

**Comment by Neopkwaii** [comment]
Thank you so very much @crookedneighbor !   I'm fixed!

**Comment by nhessler** [comment]
My group is fixed as well. Thanks Guys!
