### ISSUE TITLE
I bought gems but I doesn't work well.

### ISSUE THREAD

**Issue by Anon141** [HabitRPG/habitica#4527]
I was building a guild, I bought gems for it ($5), paid by Paypal.
While check out, page didn't work. 
it didn't back to HabitRPG page from Paypal page. (page does not responsive..??), 
I couldn't get any gems but I paid my $5 to HabitRPG..

My User ID : 08da4688-1f5d-4c3f-9f24-be87902b8365
Broweser : Chrome.
OS : Win8

what should I do now?
please help me and thank you.

**Comment by Alys** [comment]
@Anon141 This is just a quick note to reassure you that we will look into this very soon and we will sort it out for you. I'm not going to now because it's way past my bedtime :) but other devs should be online in the next few hours.

**Comment by crookedneighbor** [comment]
ping @lefnire 

@Anon141 Based on your description, it sounds like you tried to purchase 20 gems for $5 (rather than paying $5 a month for a subscription).  Can you forward a copy of the receipt you received from Paypal to tyler@habitrpg.com?

**Comment by lemoness** [comment]
@Anon141 Please copy leslie@habitrpg.com on the email if you haven't
already sent it! We will get your gems back soon.

**Comment by Anon141** [comment]
@lemoness @crookedneighbor @Alys thanks for all kind comment and your help. :) 
I sent the receipt to leslie@habitrpg.com. please let me know if you need anything else!

**Comment by lemoness** [comment]
I've restored your gems!

**Comment by Anon141** [comment]
Thanks a lot, Lemoness! now I can make a guild and drag my friends.
have a nice day all of you!  :)

**Comment by Anon141** [comment]
Hello. I have same problem. I sent my paypal receipt to @lemoness  could you check email for me please? thank you. :)

**Comment by deilann** [comment]
Are you saying you've had this problem again? You are the one who opened
this ticket last time. :) If you are having it again and you sent your
receipt to @lemoness, don't worry. She'll get on it ASAP. But in her time
zone, it's 1AM and she gets a lot of emails so it might be a little while.

**Comment by Anon141** [comment]
Yes it happened again, and don't worry I can wait. thanks a lot! =)

**Comment by lemoness** [comment]
Hi Anon; I've just checked, and I didn't receive your new receipt. Can you
send it again please? Sorry about the hassle!

**Comment by Anon141** [comment]
@lemoness  I sent you receipt again. thanks for your help!  :)

**Comment by lemoness** [comment]
We're looking into this now! It may take a while. Sorry about that!

**Comment by lemoness** [comment]
@Anon141 Okay, I've given you your gems! You should see them when you refresh the page. Thank you so much for your patience.

**Comment by Anon141** [comment]
Thank you so much for your help @lemoness ! and sorry for my late check. (I had an off for days.)  umm but I believe I paid $5 for 20 gems and you gave me 40 gems. XD so please take 20 gems back.

thank you. :)

**Comment by crookedneighbor** [comment]
@Anon141 I'm going to subtract 15 gems. You can keep the extra 5 gems for the trouble!

**Comment by Anon141** [comment]
Thank you @crookedneighbor ! Have a nice day~ :)
