### ISSUE TITLE
Dinosaur mounts put a white vertical bar to the right of the avatar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4531]
Dinosaur mounts cause a white vertical bar to appear to the right of the avatar. 

It looks like this with any dinosaur mount:
![screen shot 2015-01-17 at 9 56 39 am](https://cloud.githubusercontent.com/assets/1495809/5786373/a8b52f6e-9e2f-11e4-8206-681f13319167.png)
See also all the other colours of mounts in the hidden section at [The Dinosaur Unearthed](http://habitrpg.wikia.com/wiki/The_Dinosaur_Unearthed#Quest_Pets_and_Mounts) - they have the same problem.

With any other kind of mount the white bar does not appear:
![screen shot 2015-01-17 at 9 56 24 am](https://cloud.githubusercontent.com/assets/1495809/5786372/a8ab021e-9e2f-11e4-896b-49a676ad16bf.png)

**Comment by lemoness** [comment]
@sabrecat

Is this related to the resizing frustrations we had?

**Comment by SabreCat** [comment]
Could be an error in how I shifted the images leftward to fit in the frame.
I will investigate!

**Comment by crookedneighbor** [comment]
Yeah, that's exactly it. Batch removing the white space now.

**Comment by crookedneighbor** [comment]
Done

**Comment by crookedneighbor** [comment]
@SabreCat Sorry, realizing now that I should have asked if you were in the process of adjusting them already. Haven't had enough sleep the last couple of nights and it's making me foggy.

**Comment by SabreCat** [comment]
@crookedneighbor No big, I was away from my computer so wouldn't have had a chance to fix it until just now!
