### ISSUE TITLE
Patch for for Shared-277: Fixes getting 'perfect day' buff if there were no active dailies.

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4535]
https://github.com/HabitRPG/habitrpg-shared/pull/277.patch

From @efim

> Resolved conflicts from https://github.com/HabitRPG/habitrpg-shared/pull/98.
> Since in that pull-request 'from' is an 'unknown repository' (probably branch was deleted) I don't know how to include original commits from @Alys.
> Tested on local copy - seem to work well.
##

**Comment by Alys** [comment]
I've linked to this issue in the top comment in https://github.com/HabitRPG/habitrpg/issues/2565 ("perfect day is awarded if all Dailies are unticked Grey Dailies, or there are no Dailies") so I'm closing it now. No point having two issues open.
