### ISSUE TITLE
Patch for for Shared-232: Update npc.json

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4536]
https://github.com/HabitRPG/habitrpg-shared/pull/232.patch

@wc8 

> DanielTavern strings for in progress update of tavern.jade
> DanielText and DanielText2 strings are left in place so nothing breaks before tavern.jade is updated. They can be deleted later.

**Comment by Alys** [comment]
Do we still want these text changes to the Tavern messages?

**Comment by crookedneighbor** [comment]
I vote no, but @lemoness please re-open if desired.

**Comment by lemoness** [comment]
Nope, I think they are outdated!
