### ISSUE TITLE
subscription issues

### ISSUE THREAD

**Issue by LostInAForest** [HabitRPG/habitica#4537]
user id: b92c0adf-1741-47b4-8710-163b906409ed

i've been away from habitrpg for something like six months, and when i logged back in a couple of days ago i saw a stack of mystery items waiting for me. huh? must've forgotten to unsubscribe. strange, but oh well. (didn't log on to my bank to double check if i'd been charged, because lazy.)

however, yesterday i thought i'd buy some gems and... i can't because i don't have a subscription. huh? double checked my bank account and nothing is showing up for months.
so i decided to renew my subscription just to see what would happen and now i get this:

![skarmklipp 2015-01-19 10 52 45](https://cloud.githubusercontent.com/assets/10595812/5798660/e4753e7c-9fc9-11e4-86d2-d7f462cf7769.png)

everything else seems normal (i can buy gems et c), except i still have all the mystery stuff from when i wasn't subscribing.

**Comment by Alys** [comment]
I've checked your account from a database backup that was made earlier this month (i.e., from before your subscription changes today) and your previous subscription had a termination date of 2014-08-01. You do have mystery items available to you from after that date (up to December 2014) but I suspect that's due to a bug, which we'll investigate - thank you for letting us know about this!

You said that you checked your bank statement but nothing is showing up for months. I recommend that you look closely at it so that you know exactly what transactions have been performed for your account. If the months that don't have payments aren't what they should be, let us know.

If you would like any of the mystery items removed, please tell us which ones. This will probably depend on what you find when you look through the payments made from your bank account.

**Comment by LostInAForest** [comment]
the last payment to HABITRPG is from 2014-07-25 so that checks out fine. i was pretty sure i terminated the subscription around that time, good to know my memory isn't completely untrustworty after all. =)

so if you could remove all the mystery items from august to december that'd be great. or, actually a litte bit sad... but only fair, haha!

**Comment by Alys** [comment]
@LostInAForest I've removed those items. We appreciate your honesty! If you notice any problems with your gear, be sure to comment here and we'll reopen this issue.

For the record, this was the gear owned object before:

```
            "owned" : {
                "armor_mystery_201406" : true,
                "armor_special_gaymerx" : true,
                "armor_special_summerMage" : true,
                "armor_special_summerWarrior" : true,
                "armor_warrior_1" : true,
                "armor_wizard_1" : true,
                "armor_wizard_2" : true,
                "body_special_summerMage" : true,
                "head_mystery_201406" : true,
                "head_special_gaymerx" : true,
                "head_special_summerMage" : true,
                "head_special_summerWarrior" : true,
                "head_warrior_1" : true,
                "head_wizard_1" : true,
                "head_wizard_2" : true,
                "shield_special_summerWarrior" : true,
                "shield_warrior_1" : true,
                "weapon_special_summerMage" : true,
                "weapon_special_summerWarrior" : true,
                "weapon_warrior_0" : true,
                "weapon_warrior_1" : true,
                "weapon_wizard_0" : true,
                "weapon_wizard_1" : true,
                "weapon_wizard_2" : true,
                "eyewear_special_summerWarrior" : true,
                "head_special_nye" : true,
                "head_mystery_201407" : true,
                "armor_special_winter2015Mage" : true,
                "armor_mystery_201407" : true,
                "head_mystery_201408" : true,
                "armor_mystery_201408" : true,
                "headAccessory_mystery_201409" : true,
                "armor_mystery_201409" : true,
                "back_mystery_201410" : true,
                "armor_mystery_201410" : true,
                "head_special_winter2015Mage" : true,
                "head_mystery_201411" : true,
                "weapon_mystery_201411" : true,
                "head_mystery_201412" : true,
                "armor_mystery_201412" : true,
                "weapon_special_winter2015Mage" : true,
                "head_special_snowflake" : true,
                "head_wizard_3" : true
            }
```

and this after:

```
            "owned" : {
                "armor_mystery_201406" : true,
                "armor_special_gaymerx" : true,
                "armor_special_summerMage" : true,
                "armor_special_summerWarrior" : true,
                "armor_warrior_1" : true,
                "armor_wizard_1" : true,
                "armor_wizard_2" : true,
                "body_special_summerMage" : true,
                "head_mystery_201406" : true,
                "head_special_gaymerx" : true,
                "head_special_summerMage" : true,
                "head_special_summerWarrior" : true,
                "head_warrior_1" : true,
                "head_wizard_1" : true,
                "head_wizard_2" : true,
                "shield_special_summerWarrior" : true,
                "shield_warrior_1" : true,
                "weapon_special_summerMage" : true,
                "weapon_special_summerWarrior" : true,
                "weapon_warrior_0" : true,
                "weapon_warrior_1" : true,
                "weapon_wizard_0" : true,
                "weapon_wizard_1" : true,
                "weapon_wizard_2" : true,
                "eyewear_special_summerWarrior" : true,
                "head_special_nye" : true,
                "head_mystery_201407" : true,
                "armor_special_winter2015Mage" : true,
                "armor_mystery_201407" : true,
                "head_special_winter2015Mage" : true,
                "weapon_special_winter2015Mage" : true,
                "head_special_snowflake" : true,
                "head_wizard_3" : true
            }
```
