### ISSUE TITLE
Update NPM version for deploys

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4538]
When deploying to the site, Heroku displays a warning that npm 1.2.8 has various issues/vulnerabilities, and recommends upgrading to npm 2.2.0. Any reason not to?
##

**Comment by paglias** [comment]
No one :) but be sure to specify one in the engines part of package.json
because otherwise it will use that installed in your version . 2.x.x should
be ok
Il 19/gen/2015 18:33 "Sabe Jones" notifications@github.com ha scritto:

**Comment by Alys** [comment]
This no longer happens and we see "remote:        Using default npm version: 1.4.28"

**Comment by SabreCat** [comment]
When a production build fails, I still get the suggestion that npm 1.4.28 has known issues. https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version says that the 2.1.x branch is preferable.

**Comment by paglias** [comment]
Using npm@3 now
