### ISSUE TITLE
Plusses on Habit buttons are slightly zoomed out

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4539]
On Chrome, the + on the new style of Habit buttons looks slightly misproportioned, more like a religious symbol than a plus sign:

![image](https://cloud.githubusercontent.com/assets/4501321/5805010/c124451a-9fd0-11e4-8c31-51394b461df6.png)

If I zoom in to 110%, the symbol is correctly proportioned:

![image](https://cloud.githubusercontent.com/assets/4501321/5805021/e2ed8fb2-9fd0-11e4-80dd-baa29b7f117d.png)
##

**Comment by SabreCat** [comment]
Ping to @benmanley!

**Comment by crookedneighbor** [comment]
Also, the progress graph is overlapping on the buttons:

![screen shot 2015-01-19 at 2 48 46 pm](https://cloud.githubusercontent.com/assets/2916945/5807584/6686ae62-9fea-11e4-8db6-c6d9f1dd379f.png)

**Comment by benmanley** [comment]
@sabrecat That’s weird. Not getting it on Chrome for Mac. I don’t have an easy way to test on Chrome for Windows. Any chance you could try inserting the following at [tasks.styl#L499](https://github.com/HabitRPG/habitrpg/blob/develop/public/css/tasks.styl#L499):

``` css
      table-layout: fixed
```

@crookedneighbor Ah. Looks like it’s an existing layout issue with the progress graph. It does the same thing for Dailies and also affects Habits now that I’ve made the layout more consistent :unamused:

I’ll take a look at it when I can.

**Comment by SabreCat** [comment]
No effect from adding that style attribute in the console, at least.

**Comment by benmanley** [comment]
Thanks. I'll think I'll try a different way of achieving the same effect and see if that solves the problem.

**Comment by benmanley** [comment]
@SabreCat I've attempted a fix with dc5f980083a16ac91ac3465f94c6f4e0f3c2cb25. Let me know if it's done the trick.

**Comment by SabreCat** [comment]
@benmanley Doesn't appear to have done. I'll see what it looks like when it's deployed to the main site, but they still look lopsided on Chromium on Ubuntu.

**Comment by SabreCat** [comment]
If I give it a `zoom` attribute of `1.1` it looks fine, just as if I'd zoomed in at the browser level... xD

**Comment by librarianmage** [comment]
Is this able to be closed?

**Comment by crookedneighbor** [comment]
I believe it is still an issue, but as we're going to make improvements to the ui soon, I will close it.

**Comment by librarianmage** [comment]
Ok, thanks for the rest info! I really appreciate you letting me drag you
through history.
