### ISSUE TITLE
Completed To-dos not showing

### ISSUE THREAD

**Issue by freeman26** [HabitRPG/habitica#4541]
I completed some To-Dos and clicked on "Completed," but the Completed section is empty. :frowning: What do I do?

(Edit: You want the User ID? Oops! Here: 7ffb2a83-1ff5-4884-bf26-c2d185e3009d

**Comment by crookedneighbor** [comment]
Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

Is it possible you have a tag enabled? Click the clear button just in case, even if you don't think you have a tag enabled:

![clear tag](https://cloud.githubusercontent.com/assets/2916945/5807619/a9474b30-9fea-11e4-9db5-cf52099894eb.png)

**Comment by Alys** [comment]
If the tag clear button doesn't help, keep in mind that completed To-Dos are archived three days after they have been completed, and then you can't see them again through that web interface. You can see them if you export your data (Settings -> Export -> "user data" option) and you can also see them through Data -> Data Display Tool -> To-Dos Completed.

**Comment by freeman26** [comment]
I cleared it, and it still didn't work. I made it/marked it today, and checked the Completed section moments later, so it should still be there. I tried the Data -> Data Display Tool -> To-Dos Completed thing, and found it.
I don't need to unmark it or anything, but I wanted to mention the issue because other people might bump a checkmark (or the wrong one) before they are finished, and won't be able to unmark it.
Thanks!

**Comment by Alys** [comment]
Did this To-Do have a date assigned to it?

I think there's a bug related to the new Dated tab that's causing dated To-Dos to not appear in Completed.

**Comment by Alys** [comment]
In fact, I've confirmed it. Thanks for reporting this @freeman26! We'll get this fixed.

**Comment by Alys** [comment]
Oh no, it's all completed To-Dos that aren't showing. This, I do not understand. I am CERTAIN that I tested completed To-Dos in the change that introduced the Dated tab!

**Comment by Alys** [comment]
Hmmmm. Completed To-Dos ARE showing up in the Completed tab on my local install. I'm going to see if we can do another deployment, in case some change didn't get deployed properly to production and beta. <shrug> That clutching at straws though.

**Comment by Alys** [comment]
Deployment didn't help. We're looking into whether a recent change to third-party libraries caused the Completed tab's code to break.

**Comment by freeman26** [comment]
Yes, it did have a due date: January 21 (this Wednesday).

**Comment by Alys** [comment]
Okay, fixed now. lefnire ran grunt over habitrpg-shared and deployed that. Thanks again for reporting this @freeman26. You might need to reload to get the fix working for you.

**Comment by freeman26** [comment]
Okay, great! Thanks!
