### ISSUE TITLE
I have lost 14 gems by sending them to myself as a gift

### ISSUE THREAD

**Issue by lolai** [HabitRPG/habitica#4545]
My user ID is: 6692d9ce-2c4e-42d0-b97e-704f25716fd5
Here is a screen shot saying I sent the 14 gems:
![screenshot](https://cloud.githubusercontent.com/assets/10591133/5811934/a7e4cc6c-a013-11e4-838a-caf554a804e4.png)

**Comment by Alys** [comment]
Hi @lolai. We're looking into this!

**Comment by Alys** [comment]
@lolai Are you certain that is your unique user ID? It seems to be someone else's. Please go to Settings -> API and paste in your User ID as listed there. Don't paste the API Token!

**Comment by Alys** [comment]
Actually, never mind. You've changed your display name in the past couple of days, which is fine. :) I've given you back 14 gems. Let us know if they haven't appeared after you've reloaded the page!
