### ISSUE TITLE
No quest reward?

### ISSUE THREAD

**Issue by dkemmer** [HabitRPG/habitica#4547]
Hello! My character name is Ferin and my User ID is d9b9c1f8-e78a-4e21-9cdf-f15abacc49ad.

I completed the "Egg Hunt" quest about a month ago. Never received a reward and didn't think too much about it. I waited a while but it never registered that I had completed the quest. Everyone else, 4 others, in the party received them and have the quest listed as completed in their profile.  I don't know if this is a common problem but I thought I should report it.  There are some attached screens below proving I completed it and was in the party.

![egghunt bug](https://cloud.githubusercontent.com/assets/10617918/5822023/78d34b66-a09e-11e4-85f2-eb02fe397e28.PNG)
![egghunt bug2](https://cloud.githubusercontent.com/assets/10617918/5822024/78d735be-a09e-11e4-985d-65650b7b5024.PNG)

**Comment by crookedneighbor** [comment]
@dkemmer Weird.

I can confirm that @dkemmer does not have any egg eggs, or egg pets in inventory and does not have the quest achievement.

``` json
# Quests
 "achievements": {
    ...
    "quests": {
      "atom3": 1,
      "atom2": 1,
      "atom1": 1,
      "penguin": 1,
      "dilatory": 1
    },
    ...
}
```

I'm going to award you the 10 eggs from the quest. Let us know if you continue to have quest weirdness!

**Comment by dkemmer** [comment]
Wonderful! Thank you so much for taking care of this so quickly! Am I just out of luck with the achievement though? This quest is no longer available.  I can confirm that the eggs went in my inventory.  Again, thank you for the quick response and support!

**Comment by Alys** [comment]
The achievement is a bit more complex. It requires direct database manipulation. I'll do that for you, but it will take a bit of time. :)

**Comment by dkemmer** [comment]
Well thank you! If its too much of a hassle don't worry about it. Not a big deal. :)

**Comment by Alys** [comment]
@dkemmer It's done. :)  Comment here if the Egg Hunt achievement doesn't appear correctly in your achievements tab.

**Comment by dkemmer** [comment]
@Alys... YOU ROCK! Thank you, it's there. :) I appreciate the hard work you put into this! Awesome support like yours and @crookedneighbor is why I subscribe to help out.  Have a great day and stay wonderful!
