### ISSUE TITLE
SP rewards (value < 1) are off by one on the notification in the browser. a reward of value 0.01 shows undefined.

### ISSUE THREAD

**Issue by MHDante** [HabitRPG/habitica#4548]
uid: e5804925-e53c-48b5-90ed-03d656da0f2e
Browser: Chrome Version 39.0.2171.99 m
OS: Windows 10 Build 9879

How to reproduce: 
Create a Reward with a value of 0.01. Other values that are messed: 0.02, 0.51, etc
Purchase the Reward.
Observe the top right notification.
![bug](https://cloud.githubusercontent.com/assets/4652122/5824082/fe48d5a2-a0af-11e4-90a4-303080f24933.png)
##

**Comment by Alys** [comment]
Habitica's code has recently undergone large changes, which means that the code that caused these bugs probably does not exist any more. I'm closing this, but if you notice the same problem happening again, please open a new issue.
