### ISSUE TITLE
Can enter letters in Rewards field

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4549]
After I got a Twitter report, I tested this and confirmed it. After I saved it, it displayed a blank number. Purchasing the reward took a long time to load but had no other effect.
##

**Comment by crookedneighbor** [comment]
Related to #4018 

If the save and close button is clicked, a validation popup appears to fix the value. If the x or checkmark are used, it saves and, depending on the system, can crash the browser.

**Comment by librarianmage** [comment]
I can work on this!

**Comment by librarianmage** [comment]
Should this be delayed now?

**Comment by librarianmage** [comment]
I think that, with the new client update coming up, this Issue should be delayed until after the update.

**Comment by Alys** [comment]
I'm closing this because I can't replicate it and it will be covered in the fix for [Negative reward crashes the website - Issue #4018 · HabitRPG/habitica](https://github.com/HabitRPG/habitica/issues/4018)
