### ISSUE TITLE
New Flavicon?

### ISSUE THREAD

**Issue by nchezrony** [HabitRPG/habitica#455]
I think the flavicon should be something more "gamish", a sword, shield, etc.

**Comment by horusofoz** [comment]
@lefnire Should be a quick and easy. Should we create a Trello Card to vote on some possibilities?

My preference is for sword or sword and shield in Zelda like tradition.

**Comment by Pandoro** [comment]
What about the chest? That has seriously established itself on twitter and
on the blog.

**Comment by horusofoz** [comment]
@Pandoro A great point and I feel we should consider it as an addition to the logo as well. Thanks Pandoro.

**Comment by nchezrony** [comment]
This will also help for the app icon, when that rolls out.

**Comment by lefnire** [comment]
It should be the chest since that's used everywhere, but for the life of me - I [couldn't get this working](http://stackoverflow.com/questions/11658035/unable-to-change-favicon-with-express-js). We've had favicon.ico in the public dir since forever, I think I spent like 45m grinding my gears on `express.favicon()` and tossed in the towel. Will revisit.

**Comment by switz** [comment]
I can help you out with this Tyler, hop on IRC.

**Comment by switz** [comment]
Leaving this open in case you want to talk about switching to a chest favicon (right now it's two swords), but this is fixed in https://github.com/lefnire/habitrpg/pull/461

**Comment by horusofoz** [comment]
New favicon introduced.

**Comment by horusofoz** [comment]
![Image 1](https://f.cloud.github.com/assets/3202339/214272/8ae6d414-8406-11e2-897b-cf9dbbe60faa.png)
I think it's time we switch to the chest favicon. 

Keeps things consistent and looks better too. See our Tumbler favicon above for example.

**Comment by lefnire** [comment]
awesome, I tried shrinking the chest.png image down but couldn't achieve a reasonable img. I'll download the tumblr

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/commit/afaf3580053a2bf27df063f7a3bc914e8eb8fc93 (with next push - then you'll have to visit habitrpg.com/favicon.ico, refresh)
