### ISSUE TITLE
Strange set of glitches - extra level, habits changed color, extra todos spawned

### ISSUE THREAD

**Issue by ShwetaNarayan** [HabitRPG/habitica#4554]
When I switched between the tavern and my tasks at about 10:30pm GMT on Jan 22 2015, at least three different weird things happened.
1) I levelled, going from about 3500/5220 XP into level 124 to about 2000 XP into level 125, for no apparent reason
2) Several (maybe all?) of my habits got much bluer; at least two went from yellow to teal or blue.
3) One of my todos replicated itself 8 or so times. 

I may have ended up with extra gold; I'm honestly not sure, I haven't been keeping good track of it.

I'm also not sure if anything strange happened to my dailes, as I'd done them all by then & they continue to be greyed out. I guess I'll find out after cron.

My HabitRPG username is Shweta, and user id is f36ee400-e77b-4856-9f14-f556faaca5be 

This isn't anything I need help on myself - I reset my level/XP and deleted the extra todos, and dont much care about my habits being bluer; but I'm recording this for future reference.

**Comment by crookedneighbor** [comment]
Thank you @ShwetaNarayan, 1000 x :+1:

**Comment by ShwetaNarayan** [comment]
Follow-up note: At cron, a number of extra copies of my newest daily popped up. It's now listed 6 times. Here's a screenshot in case that's useful - the reduplicated daily is "inhalors", the green one. http://vorpus.org/~shweta/habitrpg-bug-screenshot-jan2315.png

And... I'm not 100% certain of this, sorry, but I _think_ my habits may have reset to how they were before they got blued? Or maybe it's just that they all shift towards yellow at cron. I wish I'd paid more attention to exactly which ones were how blue.

**Comment by Alys** [comment]
I suspect that the extra copies of the Daily did not appear at cron, but appeared at the same time as the earlier glitches, only you didn't notice because they'd already been completed. The extras are exact copies of the original, so they would have appeared already ticked off. Cron would have caused them all to become unticked.  Tell me if this does not sound believable!

I'm going through your tasks now to remove duplicates. I'm pretty sure that will fix the problem with the duplicates permanently.

For your Habits, if you'd like to track their values, you can use Data menu -> Data Display Tool. The "Task Overview" section shows the values of each task. There's a drop-down filter menu to show only Dailies. You could screenshot that before cron and then after, and we could look at the values to see if they're changing in sensible ways.

**Comment by ShwetaNarayan** [comment]
That's entirely possible. I _did_ look at my dailies to see if anything was weird at the time, but I am so out of it today I may well not have noticed 6 checklisted ones in a row.

Query, are you suggesting I do a screenshot before/after the next cron, that is, the one in 23 hours? Just want to make sure I'm doing the right thing/providing the right data.

**Comment by ShwetaNarayan** [comment]
Actually just looking at the numbers I can say pretty confidently that cron did not undo the glitch on the habits, it just did its usual thing - because several habits that are normally yellow have values above 3, while others that are normally green have values in the 1-2 range; so the 3s are a ways higher than I'd expect.

I've taken one screenshot, and will take another after tomorrow's cron.

**Comment by Alys** [comment]
The duplicated Daily has been fixed. I haven't found any indication that other duplicates might occur. Of course if they do, we definitely want to know! :)

I wouldn't expect cron to be able to reverse the effects of the glitch, so I think you're correct in your previous comment. A screenshot before and after the next cron, is what I was referring to. But this is just if you would like to; we don't need it done to investigate this. It's looking very much like this was a once-off glitch that won't cause ongoing odd behaviour, so everything in HabitRPG should behave normally from now on. Your Habits will become yellow at the normal rate for blue/green Habits. But if you prove me wrong, that will give us useful information! :)

**Comment by crookedneighbor** [comment]
@ShwetaNarayan Any more hiccups related to this?

**Comment by ShwetaNarayan** [comment]
As far as I know, no. Definitely no more duplications or extra levels. Beyond that I can't do better than "probably not" at the moment, because my brain is goo. I've failed to actually catch the habits and get screenshots before & after cron because I keep forgetting I'm doing that and clicking on things absentmindedly :/

I'll be more with it next week after I move to California, & will try to get some screenshots & double check things then.

**Comment by crookedneighbor** [comment]
Okay, we'll leave it open for now. I'll set a todo to check back in with you in a week.

**Comment by ShwetaNarayan** [comment]
ok! I will too, to get some screenshots next weds/thurs.  Before that is not gonna happen, reasonably speaking.

**Comment by crookedneighbor** [comment]
@ShwetaNarayan Just checking in, have you experienced any issues this week?

**Comment by ShwetaNarayan** [comment]
@crookedneighbour It all looks okay on casual glance. I've been in the tavern because of an intl. move. I only just checked out yesterday & got the pre-cron screenshot of habits; I'll get the post-cron one in a minute and put them up here. Don't expect anything weird, but the data's probably good to have.

I notice that Atramagus reported a very similar set of bugs for their wife a couple days ago (overnight oddities, #4622). Just want to note for the record: I have no idea if my streaks were affected, I don't keep good track of them. But I DO have the issue they mentioned with sorting todos, where they just resort themselves somewhat arbitrarily. I had (probably shouldn't have, sorry!) assumed that was a known issue, since I've had it for  months.

**Comment by Atramagus** [comment]
apparently the resorting of todos is a known issue by iteslf, usually having to do with having too many completed todos. This seems to have been resolved with the deleting of the todos (linked here: http://habitrpg.wikia.com/wiki/To-Dos#Rearranging_To-Dos and under cleanup). I'm assuming that as more todos accumulate, this issue will appear again, and will again be resolved by the deletion of the todos.

**Comment by ShwetaNarayan** [comment]
@Atramagus thanks for the heads up! 

@crookedneighbor here are screenshots - 
yesterday's: http://vorpus.org/~shweta/HabitRPGtasks-2015-02-04%2021:08:06.png
today's: http://vorpus.org/~shweta/HabitRPG-tasks-2015-02-05%2010:10:24.png

Everything's working sa predicted as far as I understand, except that my bright blue tasks don't seem to be changing numbers at all. Which may be how the numbers got quite that high? I'd been wondering how they did. Should I delete those and redo them as new habits?

**Comment by ShwetaNarayan** [comment]
For the record, when I click on the negative sign for those habits, the number does decrease. It just didn't decrease on cron.

**Comment by rachteo** [comment]
I think this might have happened to me, but I wasn't paying attention enough to be sure if habits got bluer or I got bonus gold/xp, but my massive list of todos got re-sorted, and a few of my habits and todos got duplicated multiple times. I tried deleting all of one set of duplicated todos, but only one got deleted in the end. 

My username is rachoune and my UID is 64dffeb1-723c-4d73-a783-026544bfefa9
I saw this error on Google Chrome on Mac OS X 10.9.5, although I also have the app on my iPhone 5S running iOS 8.1.2. I hadn't opened the app in several hours, though. 

![image](https://cloud.githubusercontent.com/assets/1234900/6072444/9569f0f8-ad56-11e4-82d5-3d2fbd66f470.png)

**Comment by Alys** [comment]
@rachteo I'll sort out your tasks on the weekend (about 24+ hours from now).

**Comment by rachteo** [comment]
@Alys no worries, I managed to delete the duplicates; I think it's just the original that couldn't be deleted. As to the rest of it, I'm not sure if anything happened so I'm not particularly bothered, I just wanted to report the bug

**Comment by Alys** [comment]
We think duplicate tasks have been prevented by https://github.com/HabitRPG/habitrpg/pull/4845 (which was merged in https://github.com/HabitRPG/habitrpg/commit/ca72b9a9e1e86262fcab15c7d52ae902953dc7b8).

I am hoping that the other problems reported here were once-off glitches that won't happen again.

I'm closing this but can be reopened if I'm wrong.
