### ISSUE TITLE
Vertical dividing line in Market doesn't extend all the way

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4556]
In the Market, the dividing line between the player's inventory and Alexander's items for sale doesn't extend all the way through the page:

![image](https://cloud.githubusercontent.com/assets/4501321/5867901/775b7d88-a267-11e4-9838-1142699af517.png)

It's somewhat resolution-dependent. The above was on my 4:3 monitor; if I move it to my widescreen, the line makes it past the first row of Food items.

**Comment by crookedneighbor** [comment]
It's because the border is applied to the div on the left, not the right, and in most cases, since the market will have more items than the user, the div on the left has a shorter height than the one on the right.
