### ISSUE TITLE
Mana not updating correctly

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#4557]
Mac OSX 10.9
Browser is Fluid, Version 1.8.3 (Safari Version 8.0.2 (10600.2.5)), possibly Android v0.0.46

I'm seeing two strange behaviors related to Mana, which may or may not be affecting each other. 

1) I don't seem to be receiving the 10 Mana each morning when I log in. I noticed it first yesterday, and thought perhaps it was a browser sync issue. However, I did not use my phone to spend any mana yesterday (actually, I don't recall casting any skills yesterday, and come to think of it, I don't actually see my skills in the rewards, so I'm not sure I've ever used my phone to cast a skill). When I logged out last night, my browser showed me at 27; I now have 34 Mana.

2) When I originally logged in, it actually subtracted 15 Mana from my score (for a score of 12). However, scrolling the page a few pixels down bumped it from 12 to 34, and then back to 12 when I scrolled back up to the top of the page. See the following screen shots:

![screen shot 2015-01-23 at 5 20 34 am](https://cloud.githubusercontent.com/assets/101778/5870493/47986d90-a2c6-11e4-8f61-063d6495f583.png)
![screen shot 2015-01-23 at 5 20 39 am](https://cloud.githubusercontent.com/assets/101778/5870494/47a11152-a2c6-11e4-98fc-beadfb79b7d8.png)

Logging in with other browsers (FF, Chrome) seems to show 34 Mana regardless of scrolling. And restarting Fluid completely now shows the correct Mana. I will try to avoid using Fluid/Safari for awhile, as I've seen other odd bugs (e.g., tasks not keeping their order when doing a page refresh, images missing, seeing other people's avatars instead of my own, which may be related to my choice of browser).

userid: fedc44cb-088a-4bc8-8f4f-3e6a1882f042

**Comment by kamni** [comment]
One more comment I should mention: I am currently traveling in a different time zone than I normally play. I may have noticed the issue on the day of travel, where I used my laptop in the morning, and then used my cell phone (updated automatically) in a different time zone later in the day.  The next day I used my laptop (on the old time zone) and noticed something odd with the Mana but attributed it to phone sync. And this morning I used my laptop with the time zone updated.

**Comment by kamni** [comment]
Finally, notice the difference in armor between the party member on the far right (I just noticed the difference myself) between the 2 screen shots. For some reason scrolling a few pixels seems to be alternating between an old set of data and a newer set of data.

**Comment by Alys** [comment]
I'm closing this since it sounds like the weird behaviour was due to bugs in the Fluid browser, however it can be reopened if the same thing is happening in Chrome or Firefox.

When travelling through timezones, it's recommended to [Rest in the Inn](http://habitrpg.wikia.com/wiki/Rest_in_the_Inn) while your device's time is being changed, until all of your Dailies have been marked as completed, because cron can occur at an unexpected time. It's also important to ensure that all devices you use HabitRPG on have the same time and same timezone, for the same reason.
