### ISSUE TITLE
Date format setting doesn't apply to progress charts

### ISSUE THREAD

**Issue by dxsmiley** [HabitRPG/habitica#4558]
I'm currently using the d/m/y date format, but it does not apply to the dates displayed on the progress charts, as seen below.
![image](https://cloud.githubusercontent.com/assets/7530928/5871278/044c3b2a-a32f-11e4-9ba0-010f3dacb06a.png)
I also tried using the y/m/d format and it didn't affect it either.

**Comment by Verabird** [comment]
Thanks for finding this

I'll get right on it
