### ISSUE TITLE
members[uid].items.weapon prevents use of cached members data

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4559]
ping @lefnire and @paglias because this seems to be ancient code. ("It was like that when I got here")

In public/js/services/memberServices.js, we have [this line](https://github.com/HabitRPG/habitrpg/blob/develop/public/js/services/memberServices.js#L67):

`if (members[uid] && members[uid].items && members[uid].items.weapon) {`

which seems wrong because there is no `items.weapon` in our schema any more, and even if there was, why would it be important there? That `if` statement wraps around some code that reads cached members data, and when the `if` statement fails (always), an `else` statement fetches the data from the database. At least I think that's what's happening.

Can we change that `if` statement to just this?
`if (members[uid]) {`
##

**Comment by paglias** [comment]
@Alys good catch! I don't think I wrote it but _maybe_ we check for `items.weapon` because otherwise we could have `members[uid]` cached but with less data than needed for displaying the member modal. Maybe if you have the user in a guild you already have it cached but the only data is username and uuid... But it's just an idea

**Comment by Alys** [comment]
@paglias, thank you! That does seem plausible. I'll advertise this in the Aspiring Coders guild to see if anyone wants to investigate it.

**Comment by taldin** [comment]
Some digging I did on my part turned up that it's used in the (non-working) Ultimate Gear achievement, and some migration code.   The 'easy' approach is just to eliminate the extra checks.  The 'thorough' solution is to maaaaybe think about getting Ultimate Gear/Gear Set achievements up and running?

**Comment by lemoness** [comment]
For what it's worth, I'd love to have the Ultimate Gear achievements back.

**Comment by taldin** [comment]
I've been thinking about working on that when I get my life back after this release is done.  10+ hour days 7 days a week for work is not conducive to coding. :)

**Comment by Alys** [comment]
bumping this for consideration again now that ultimate gear achievement is fixed

**Comment by SabreCat** [comment]
Client code refactoring. Pending for after the redesign.

**Comment by lemoness** [comment]
@sabrecat @paglias Has this been refactored already?

**Comment by Alys** [comment]
That code is gone now. There's no active code containing `items.weapon`
