### ISSUE TITLE
Cannot install Chrome Extension into Chrome Portable (PortableApps.com)

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#456]
I tried and miserably failed to install the Chrome extension to Chrome Portable (PortableApps.com Format).

Every attempt yields the error below:
![Image 3](https://f.cloud.github.com/assets/3202339/175930/c3548740-7b61-11e2-8629-f2f4f70f5b28.png)

**Comment by tmas** [comment]
Have you tried this with other extensions? It may be on the PortableApps side. I'm pretty sure chrome extensions don't have any control over where they're downloaded to.

**Comment by horusofoz** [comment]
@tmas Great pick up. I posted without thoroughly testing. Just tried with RTM as same error so appears to be PA.com issue. Thanks :)
