### ISSUE TITLE
Quest stuck even though it should have completed

### ISSUE THREAD

**Issue by jeffnielson** [HabitRPG/habitica#4560]
My quest won't complete. It is stuck with about 12 health remaining.  Been like that 2 days.   Thanks. 

4e08a4fe-1f1e-4000-9143-551ca628dec2

**Comment by Alys** [comment]
According to the database, your quest has ended. Have you reloaded the party page? That's likely to show you that the quest is gone. If it doesn't, log out of HabitRPG, clear your browser's cache (make sure it really is the cache you are clearing, not just browsing history or anything else), log back in, go to the party page, and if necessary reload it again.
