### ISSUE TITLE
Died, but have 2 days streak on tasks

### ISSUE THREAD

**Issue by Lexidh** [HabitRPG/habitica#4562]
I died today, even though I marked all my dailies as done yesterday, and I have a 2 day streak (should be much much more) on all those tasks except one, that task is only for one day in the week. None of the daily tasks I should do every day are blue, the only blue I have today are tasks that wasn't active yesterday. 
I did 1.9 damage on my guild quest, it's usually over 20. Suffered 39.4 damage. I'm quite sure I had 50 health, so the death isn't very logic in that respect either.

**Comment by deilann** [comment]
Is 39 damage what was recorded on the party page? If so, do remember that
you take both the boss damage from your dailies and the boss, so that does
actually make sense.

The rest definitely does sound buggy though.

@Alys does this sound like the two versions of data bug to you?

**Comment by Lexidh** [comment]
Ah yes, that makes sense, boss + dailies damage. Totally forgot about that.

**Comment by Lexidh** [comment]
I guess I found the tasks that did damage, two that are blue today and have 22 days streak. That makes no sense at all either, since it is tasks I do 7 days a week, and I haven't died (or paused) since December 2nd (the day we couldn't reach the site).

**Comment by deilann** [comment]
The tasks that would have done damage are the ones with too low of streaks,
not the ones with high streaks/are blue. Alys should be able to give more
info.

**Comment by Lexidh** [comment]
Biggest issue is that they are almost all greyed out today, like I've done them, but I haven't. I did them yesterday, marked them, but died anyway. And still have 2 day streaks. I'm also quite sure I marked the two that must have done damage, are blue today and have 22 day streaks at the same time as the rest. They are kinda connected to other tasks, can't be marked until other things are done.

**Comment by deilann** [comment]
Yeah, that definitely sounds like the issue Alys has been looking at.
She'll be able to give more info.

What you can do, though, is grab your stats, uncheck them, then use Fix
Character Values to put your stats where they should be. Then, you'll be
able to do your tasks and won't have lost your XP and GP.

The ones that probably did the damage are NOT the ones that are blue
today... they are the ones that are grey today. Basically, Habit thinks
you've done them today... but didn't do them yesterday, so is damaging you
for them yesterday. Really sorry about this... it's a frustrating bug we're
working on hard right now.

**Comment by deilann** [comment]
Oh, on top of the Fix Character Values (which is in Settings > Site by the
way) you can also manually fix your streaks if you know approximately how
long they were in the Advanced settings under each daily.

**Comment by deilann** [comment]
Here is the ticket on the issue:

https://github.com/HabitRPG/habitrpg/issues/4313

I'm going to close this ticket, and you can follow more info there!

**Comment by Alys** [comment]
I agree with everything @deilann said. There's a workaround here in case it keeps happening: https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-70820170 . Sorry it's such a nuisance! It's a hard bug to track down.

**Comment by Alys** [comment]
I agree with everything @deilann said. There's a workaround here in case it keeps happening: https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-70820170 . Sorry it's such a nuisance! It's a hard bug to track down.
