### ISSUE TITLE
Double clicking habits

### ISSUE THREAD

**Issue by Magoosducki** [HabitRPG/habitica#4563]
When I go to mark a habit either a plus or minus, I am receiving double the rewards/damage. I have made sure this is not just an issue on my computer by testing on the phone app, and it is occurring there as well. 
My User ID is: 9985235a-c8b6-4dde-8511-42767bb02867

Thank you.

**Comment by crookedneighbor** [comment]
@Magoosducki Did you figure out what was going on?

**Comment by Magoosducki** [comment]
Yes, I believe it is an issue with my mouse. I first noticed it on Habitrpg, but have since noticed it on other pages.

**Comment by crookedneighbor** [comment]
Okay, thanks for the update!
