### ISSUE TITLE
Skeletal T-Rex Healed beyond initial 500 HP

### ISSUE THREAD

**Issue by clusterpainter** [HabitRPG/habitica#4564]
Hello, lovely bug crushers. We are fighting the Skeletal T-Rex. One of my party members didn't log in for a few days and the T-Rex did a whopping 60 pts of damage to our party! That filled up the fossil's rage bar and now, the dreaded bone beast has 523 HP! Per Blade's suggestion, I am opening this ticket.

**Comment by crookedneighbor** [comment]
Thanks, you rock! Now we just have to figure out if that's a "feature" or a bug. :smile:

**Comment by SabreCat** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/ec114d6a3e277242fefcd3bdb9640a2a034ab2f8.
