### ISSUE TITLE
Completed Todos don't show up on rebalancing-2014-12 branch

### ISSUE THREAD

**Issue by Verabird** [HabitRPG/habitica#4569]
rebalancing-2014-12 branch:
![image](https://cloud.githubusercontent.com/assets/8468001/5888207/dbce1138-a3c3-11e4-8887-8b7455ef6678.png)

develop branch:
![image](https://cloud.githubusercontent.com/assets/8468001/5888217/3bb2d44e-a3c4-11e4-8518-a5ae13c8fe33.png)

Not sure if this is known already or not

**Comment by Alys** [comment]
Oh yes, that's a bug that was fixed in develop. I just haven't rebased rebalancing for a few days. I've made a to-do to do that later today. Thanks!

**Comment by Alys** [comment]
merge done and pushed to github.

Sorry about that @Verabird. It must have made testing with completed To-Dos harder than it should have been.
