### ISSUE TITLE
Notable loss of data on iOS client

### ISSUE THREAD

**Issue by wswld** [HabitRPG/habitica#4571]
I've lost a substantial amount of data today. Basically around 12 hour worth of new to-dos, habits, rewards and even a levelup were just rolled back as if nothing really happened. It was iOS client and I had semi-stable connection throughout the day, but I certainly have updated it several times having a strong or cellular WiFi connection, relaunched the app. It seemed to have synced and then it just all disappeared and I was back to the yesteday state of affairs. I did had occasionally bought leather armour yesterday (seemed to be a finger slip) it is gone too now. All the gold was returned, but I do miss lots of custom rewards I've added throughout the day.

**Comment by paglias** [comment]
I think it's done to the offline syncing that had some bugs. It should be ok in an update that should come in a few days, waiting for apple to approve it

**Comment by wswld** [comment]
So, this is irreversible? I just should abstain from using the iOS app before the next update to avoid other issues like that? Could the state of my profile be rolled back to the 11 AM MSK today, or it's impossible?

**Comment by paglias** [comment]
Sadly we can't rollback your account to a precious version because probably
it never really synced to the server. You should try not to use it offline
in the meantime and if you do make sure to close the app before using it
again (from the list of open apps)
So, this is irreversible? I just should to abstain from using the iOS app
before the next update to avoid other issues like that? Could the state of
my profile get rolled back to the 11 AM MSK today, or it's impossible?

**Comment by wswld** [comment]
OK then. Thanks for the assistance.

**Comment by wswld** [comment]
Actually I kinda localized the issue. The trouble start when I edit something within an issue (change difficulty, checklist) and then the sync seems to break (loading indicator not showing on swipedown) and all the changes after this moment seem to get lost on restart. Even issues that aren't edited just added after you edit this one are lost. Just an observation.

**Comment by wswld** [comment]
If I avoid editing issues, just adding and marking checking them off, everything seems to work fine. If I edit an issue (habit, todo, daily doesn't matter), whatever is done afterwards — lost.

**Comment by clife026** [comment]
I used the app online but it never synced with the server? All the ticked dailies didn't sync and so i died and lost the streaks, gold, armour, etc. How do I prevent this from happening again?

**Comment by Alys** [comment]
@clife026 If you go to one of the task screens and drag down from near the top, you can force syncing to happen (a spinner will appear). You can also go to the website or the Data Display Tool (from the website's Data menu) to check that your Dailies are marked as completed there - if they are, then you can be sure that syncing with the server was complete. The website works well in most modern phone browsers and has several more features than the app.

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
