### ISSUE TITLE
Wacky Cron: some dailies grayed out, no perfect day, drop cap already reached

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#4572]
Ran into an odd problem today, after refreshing my account after cron.

1) **Some of my dailies were already checked off.** The first four were not (which are active today). Then there's something that is normally grayed out because it's Monday. After that, everything that had been checked off yesterday remained checked off.

2) **No perfect day.** Despite this, all of my streaks have been preserved; and I didn't seem to take any damage.

3) **Damage to the boss was resolved, albeit reduced.** If I can remember, the Data Display predicted more damage than was resolved. I could have that wrong though. Regardless, the damage was resolved.

4) **Drop cap reset, but sort of messed up.** I usually have a drop cap of 18 by the end of a non-perfect day by using Perception items. I hit 18/18 yesterday, and when I refreshed today, it said 14/14 (which is correct with the items that I was holding). I was able to get four more drops (to get 18/18), but I don't know why it started at 14 drops already and didn't reset to 0.

Note: Popitop in the Tavern reported having a similar problem.
##

**Comment by HSalgo** [comment]
Wait, some additional notes:

2a) **Streak values have been mysteriously altered.** After unchecking all of the pre-checked off things today, I realized that anything that anything I'd unchecked now had a Streak Value of 1. This means that anything that started off gray today had a streak value of 2 for no reason. Note that other things that were NOT checked off (including tasks that should have been activated today or yesterday) were unaffected. This means that this was probably NOT an issue of multiple crons happening at once.

3a) **No damage was received from the boss.** I'm still at full health, despite not having a perfect day, which is sort of odd. Again, this suggests that multiple crons didn't happen in a row, or I might be dead.

**Comment by Alys** [comment]
This could be a very aggressive example of https://github.com/HabitRPG/habitrpg/issues/4313 ("two versions of your data" bug). Maybe if enough tasks were held in local storage, they could give you 14 drops when they were saved to the server after cron ran?? Although I wouldn't have expected the caching problem to last for that long - usually it's just the last few tasks ticked off at the end of the day. So... I don't know... I'm definitely leaving this open so we can think about it some more.

@HSalgo If it happens again, you might want to consider the workaround described in [this comment](https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-70820170) (in brief, regularly reload at the end of the day, then sync, then check your tasks). Please do let us know here if you have any other problems like this.

**Comment by HSalgo** [comment]
Did anyone else have this problem yesterday? I wonder if it was something funky with the World Boss getting defeated? I have no idea.

Anyway, the problem did not persist until today, so I'm going to say that we should leave this open to see if anyone else has this problem in the long term. Sound good?

Thanks for your help!

**Comment by Alys** [comment]
We haven't seen anything as extreme as your report but there are similar, milder problems in that issue I linked to. It wouldn't be related to the World Boss; that code is very similar to the normal quest code and there's no room in it for extreme errors like this one.

I agree about leaving this open, at least until we've developed a good understanding of what has happened or until enough time has passed that we can be confident it won't happen again.

Thanks for all the details, by the way. It's always good to have this much information.

**Comment by Alys** [comment]
Since this was logged, we've seen other examples of #4313 (local storage bug) where significant changes were held back by the browser and then applied after cron, so I think that's what was happening here. We haven't seen anything else that could cause this.
