### ISSUE TITLE
Pet progress

### ISSUE THREAD

**Issue by DPlatz** [HabitRPG/habitica#4574]
With the pets, the growth progress bar isn't showing up. 
![petprogressbarnotshowing](https://cloud.githubusercontent.com/assets/10714076/5907037/f79820a0-a569-11e4-9cd2-135bad5b05ca.PNG)

**Comment by Alys** [comment]
That's a known issue with Internet Explorer, which has several non-standard features that cause problems like this. If you use Chrome or Firefox, you won't experience this problem.

Do let us know if you are not using IE but are still seeing this!

We would like to fully support IE and we probably will at some time in the future, but unfortunately the extra code required to work around IE's bugs takes more time than we have programmers for at the moment. :(

**Comment by DPlatz** [comment]
Yes, I was using IE.
Will check Chrome...

**Comment by DPlatz** [comment]
Works fine in chrome. Thanks!

**Comment by paglias** [comment]
@DPlatz which version of IE you were using?
