### ISSUE TITLE
Quest scrolls difficulty for the colorblind

### ISSUE THREAD

**Issue by nagledb** [HabitRPG/habitica#4575]
The new feature that adds a color border to each quest scroll indicating its difficulty level ("Easy Boss = Green, Medium Boss = Yellow, Hard Boss = Red, Collection Quest = Blue, Rage Bar Boss = Purple speckles") is a great addition, but as a colorblind person I can't differentiate some of them. Would it be possible to represent that difficulty information in a non-color-coded way as well?

Even just adding a note at the end of the quest descriptions would be great.

**Comment by deilann** [comment]
+1

**Comment by lemoness** [comment]
Frankly, I would like to make it so that instead of displaying the quest
text on hover, it instead displays relevant details, for example:

Vice Awakens
HP: 1500
Str: 3
Rewards:
Stephen Weber's Shaft of the Dragon
2 Dragon Eggs
2 Shade Hatching Potions
100 GP
1000 XP

**Comment by crookedneighbor** [comment]
@lemoness Something like this:

![screen shot 2015-01-27 at 3 58 04 pm](https://cloud.githubusercontent.com/assets/2916945/5928049/5caa07be-a63d-11e4-8e6a-32bd069a87ce.png)

**Comment by Alys** [comment]
I'd suggest "Boss health" and "Boss strength" otherwise we'll get newbies thinking it will give them 500 health.

**Comment by crookedneighbor** [comment]
Good thinking.

**Comment by deilann** [comment]
I'd like that. The quest description is too much for the pop over anyway.

**Comment by lemoness** [comment]
Agreed on the "Boss Health"/ "Boss Strength" - other than that, looks great!

**Comment by crookedneighbor** [comment]
![screen shot 2015-01-27 at 4 18 22 pm](https://cloud.githubusercontent.com/assets/2916945/5928348/2ce6faac-a640-11e4-8992-dcde002bfbe9.png)

![screen shot 2015-01-27 at 4 18 31 pm](https://cloud.githubusercontent.com/assets/2916945/5928354/363926a2-a640-11e4-872e-eefd171fdedd.png)

**Comment by Alys** [comment]
So nice!

**Comment by lemoness** [comment]
Any way to bold the bits before the colons, just to make them pop?
(Thinking in particular for the rewards.) If it's a hassle, just merge
as-is.
