### ISSUE TITLE
Rooster mounts artwork not consistent with style

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4576]
Most mount, pet, and equipment artwork features a dark outline--not necessarily black, but more than 50% of the way there. Rooster mounts, however, feature artwork whose outline doesn't differ much from the interior colors of the sprite, leading to an odd washed-out look compared to other sprites. It makes the mount look more like it's part of the background than the hero's accoutrements:

![image](https://cloud.githubusercontent.com/assets/4501321/5910601/8d9bd242-a581-11e4-94a5-6049a554f304.png)

**Comment by Alys** [comment]
I agree.

Useful new wiki page (still underconstruction) for comparing all Mount images: http://habitrpg.wikia.com/wiki/Art_Credits#Mounts

**Comment by lemoness** [comment]
Beffymaroo is already working on the revamped art! She's nearly done :)
I'll link here when she's finished.

**Comment by lemoness** [comment]
And she's done! (@sabrecat) 

All recolored files here: https://trello.com/c/5laTwynp/22-rooster-recolors
