### ISSUE TITLE
Additional Sample To-Dos

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4577]
I know we want to revamp the tutorial to make it better, but as a quick stop-gap, I think we could add some extra Sample To-Dos so that people's accounts have some guidance.

Ideally, the mobile app and the website would have different ones, because the website supports links but links block the mobile app (at least on iOS). If that won't work, we could take out the links in favor of listing the drop down path.

Definitely comment/edit/add more! We definitely want to get this in soon, before we get another traffic surge.

EDITED SAMPLE TO-DOs version 1, pre-links (Website and Mobile):
- [x] Join HabitRPG (Check me off!)
- [ ] ~~Edit me!~~
  - ~~move this checklist to the bottom~~
  - ~~move this checklist to the top~~
  - ~~check out "Advanced Options"~~
  - ~~check me off!~~
- [x] Set up a Habit
  - create a Habit
  - make it "+" only, "-" only, or "+/-" under Edit
  - set difficulty under Advanced Options
- [x] Set up a Daily
  - decide whether to use Dailies (they hurt you if you don't do them every day)
  - if so, add a Daily (don't add too many at first!)
  - set its due days under Edit
- [x] Set up a To-Do (can be checked off without ticking all checkboxes!)
  - create a To-Do
  - set difficulty under Advanced Options
  - optional: set a Due Date
- [ ] ~~Customize Your Character (User/Profile > Avatar)~~
- [x] Start a Party (private group)  with Your Friends (Social > Party)
- [x] Join the Newbies Guild and introduce yourself (Social > Guilds > Newbies Guild)
- [ ] ~~Try HabitRPG on Website and App~~
  - ~~website (habitrpg.com)~~
  - ~~mobile app~~

> ### EDIT: Blade - Applied strikethrough style to the ones @lemoness had me remove.

VERSION 2: EDITED SAMPLE TO-DOs, post-link fix (Website and Mobile):

Demo Task: Click me and see what happens!

Edit me!
- move this checklist to the bottom
- move this checklist to the top
- check out "Advanced Options"
- check me off!

Set up Habits (see samples here: http://habitrpg.wikia.com/wiki/Sample_Habits)
      - create a Habit
    - make it "+" only, "-" only, or "+/-" under Edit
    - set difficulty under Advanced Options

Decide whether to use Dailies (tasks that hurt you if you don't do them every day)
     - check out sample Dailies: http://habitrpg.wikia.com/wiki/Sample_Dailies
     - decide whether to use Dailies 
     - if so, add a Daily (don't add too many at first!)
     - set its due days under Edit

Set up To-Dos (see samples here: http://habitrpg.wikia.com/wiki/Sample_To-Dos)
     - create a To-Do
     - set difficulty under Advanced Options
     - optional: set a Due Date

Customize Your Character (User/Profile > Avatar)

Start a Party (Social > Party)

Join the Newbies Guild and introduce yourself (Social > Guilds > Newbies Guild)

Check out the Data Display Tool (Data > Data Display Tool)

@deilann @veeeeeee @Alys @sugarfiend @ anyone else

**Comment by Alys** [comment]
The sample tasks are placed into the user's database record when the user creates their account, so different tasks for website versus mobile would require some large(?) changes. And if users start off by using both website and app together (the ideal situation I would think), separate sets of tasks could be troublesome. I think it would actually be an advantage to specify the menu path rather than a direct link. It gets them used to the menu system and prevents later questions like "I've deleted the task that has the link for Xyz. Can someone give me the link please?" :)

**Comment by crookedneighbor** [comment]
I agree with Alys. Really, we need to make fixing the bug where you can't exit the in-app browser a priority.

**Comment by veeeeeee** [comment]
What if we start them off with a few "gimme" tasks, like "register for HabitRPG"? Or even more straight forward, "Demo task: Watch what happens when you check this off!" Mildly interactive, but shouldn't require any extra coding.

*Edited for a completely screwing up a word.

**Comment by crookedneighbor** [comment]
:+1: for "Demo task"

**Comment by Alys** [comment]
I'd like to see a To-Do that makes users aware that we have a website and apps (especially useful for people who have started with the app). Maybe something like below, where the app links point to the app stores.

![screen shot 2015-01-27 at 7 19 13 pm](https://cloud.githubusercontent.com/assets/1495809/5916133/799a0b1e-a659-11e4-96e2-43cef789ce5b.png)

Optionally, the Note could explain that you don't have to tick off all checklist items before you tick off a To-Do, and that the earnings you receive depend on how many items you tick off. This seems like a good place for that description since the users would be likely to tick off at most two items.

**Comment by lemoness** [comment]
Lots of good ideas!
- I agree that Item Path is important, although for external links like the
  wiki, there's no obvious route.
- How hard is it to fix the bug in mobile that opens links in the same
  page? How quickly can it be done? We want to get these in as soon as we
  can, so maybe we should do two pushes - one without links, and one with
  links.
- Idea for another to-do: check out the Data Display Tool? Or is that too
  complicated for a new user? It might be nice for them to see how much
  damage they are going to take.
- I love the "Demo" task idea. What about a similar "Edit me" task?
- I think the "Try on different platforms" is great, but worry that people
  will be confused if the note is only in popover, especially in the mobile
  app. (Can you see checklists yet in the mobile apps without clicking?)

**Comment by crookedneighbor** [comment]
ping @negue and @huarui regarding how easy the fix for the external links bug will be: https://github.com/HabitRPG/habitrpg-mobile/issues/227

**Comment by lemoness** [comment]
Okay, I've updated the original card. Let's roll out the link-free versions first, because even if we fix the bug quickly, Apple will take a million years to deploy the update, and this is a sooner-the-better fix.

Anyone else have any qualms/comments about the new version of the list?

**Comment by lemoness** [comment]
FYI: we're entering stage 2 of the tutorial revamping! Soon we're going to swap out these stop-gap tasks in favor of a more interactive tutorial that we've designed based on a bunch of user testing videos (which were agonizing to watch). Tyler's tackling it now!
