### ISSUE TITLE
Have to Re-Buy Seasonal Items after using Orb of Rebirth

### ISSUE THREAD

**Issue by fioskal** [HabitRPG/habitica#4578]
User ID: 53be6816-f011-4c25-99dd-682fcab643a8
Browser: Firefox

I bought every single item in the Seasonal Shop earlier this month. I used the Orb of Rebirth yesterday to restart my character. None of those items are still in my inventory, I can't re-buy them for coins, and the Seasonal Shop wants me to repurchase these items for one gem an item.

**Comment by deilann** [comment]
You can repurchase then if you are the right class. So say seasonal mage
armor, you need to be a mage

**Comment by fioskal** [comment]
I bought all of them with no problem earlier, however. And I am a warrior right now - it is still showing me as having to spend gems to get the warrior items back, in addition to all the other items.

**Comment by crookedneighbor** [comment]
@fioskal It might just appear that you need to purchase from the seasonal shop. 

I'm remembering now that I wrote the code to conditionally apply that class if the value is in your inventory, since you did the orb of rebirth, the values for those items are set to `false` instead of not being in existance. The code that applies the transparent class doesn't know the difference, and will need to be adjusted.

I bet if you actually try it'll say "Whoops! You already have this item. No need to buy it again!" after asking you to confirm the purchase. Would you mind trying? I'll refund you the gem if it actually takes it.

**Comment by fioskal** [comment]
If you can wait until the 1st, I'd be happy to - I'm all out of gems for the month. :)

**Comment by crookedneighbor** [comment]
@fioskal Can you check your rewards column on the tasks page? That's where the seasonal warrior gear should be for purchase with coins after rebirth.

**Comment by crookedneighbor** [comment]
Should look like this (after unlocking item drops):

![screen shot 2015-01-26 at 6 54 33 pm](https://cloud.githubusercontent.com/assets/2916945/5911571/d1b03bde-a58c-11e4-834a-05c2ccf1aff4.png)

**Comment by crookedneighbor** [comment]
This commit should fix the seasonal shop view: https://github.com/HabitRPG/habitrpg/commit/3b1743dee86d9b81a3d6fa5fefd263bee91dd013

**Comment by fioskal** [comment]
Yes, the warrior ones (none of the other classes) are on the task page now, I didn't see them earlier.

**Comment by crookedneighbor** [comment]
@fioskal Would you do me a favor and take a screenshot of your rewards column and attach it to a comment here? Note, you won't be able to do it through email, it'll have to be on the issue page on Github.com.

**Comment by fioskal** [comment]
![rewardscolumn](https://cloud.githubusercontent.com/assets/10717368/5912136/e849eac4-a583-11e4-8b0b-c68306e9f3be.png)

**Comment by fioskal** [comment]
That's as much as I could fit on one page without splicing an image together. I think that's all of the items, just missing custom rewards.

**Comment by crookedneighbor** [comment]
@fioskal You're a warrior right now, so the only seasonal items from last year that you can purchase as a warrior are the yeti-tamer items. The rest are available to be purchased, but you need to be the appropriate class to buy them.

**Comment by crookedneighbor** [comment]
It is, admittedly, a little confusing since you were able to purchase them for gems no matter what class you were.
