### ISSUE TITLE
my character has died out of the blue

### ISSUE THREAD

**Issue by jen2472** [HabitRPG/habitica#4579]
For the second time in perhaps a week, my character has died out of the blue.  This last time, I had 48/50 life points yesterday afternoon, I check in this evening, and I'm dead.  
my ID: 111f9978-217f-4755-8fef-a469ded53947
Group ID: ea8af266-a349-49b5-bb18-21090ae83cad

The boss we’re battling has only taken 7.6 points from us in the last 17 hours.  I'm completely non computer savvy, so I hope this is enough info.  Thx.

**Comment by jen2472** [comment]
It turns out that two of my fellow party members have died, too.  Not sure what's going on.

**Comment by Alys** [comment]
Click the "Fetch Recent Messages" button above party chat and then look back over the past 24 hours for red messages listing boss damage. You'll probably find one or more with a very high amount of damage that caused the three of you to die. Let us know if that's not the case.

**Comment by jen2472** [comment]
18 hours ago, the Rat King attacked for 49.1 damage.  That's all.  Is that enough to kill 3 of us?

**Comment by crookedneighbor** [comment]
That's 49.1 damage to each member of the party.

**Comment by jen2472** [comment]
Well, then, that explains it, doesn't it?  Thanks for the help.

**Comment by crookedneighbor** [comment]
@jen2472 Time to snowball whoever forgot to do their dailies :smile:
