### ISSUE TITLE
Issues with Footer on /static/front

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4580]
- [x] Language select box doesn't actually let you select a language.
- [ ] Twitter, Facebook, and Google Plus missing from social tab
- [x] ~~Donate button missing from company column (probably because it's designed to give user gems for donating)~~

![screen shot 2015-01-26 at 10 47 21 pm](https://cloud.githubusercontent.com/assets/2916945/5913652/727d27e6-a5ad-11e4-8fb9-15077fdf11b5.png)

**Comment by paglias** [comment]
For languages is this line https://github.com/HabitRPG/habitrpg/commit/2306b7c57289d2db9e053b528ccf3c5a473ee24e#diff-b15b92fe8a80bfe66aec828f1d8f71ceL7 which doesn't resolve to `true` anymore when on a static page

**Comment by paglias** [comment]
Fixed languages list here https://github.com/HabitRPG/habitrpg/commit/42c0b443d7d81fab5260fed7252c5fc6f807a8a1

Gems are disbled by purpose: https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/footer.jade#L18

**Comment by crookedneighbor** [comment]
:+1: Awesome. I'll strike the donate button from the list.

**Comment by paglias** [comment]
and for the addThis script I think it's https://github.com/HabitRPG/habitrpg/blob/develop/views/index.jade#L13-L14 which has been moved from footerCtrl to index, but I can't test it right now

**Comment by paglias** [comment]
@crookedneighbor fixed addthis https://github.com/HabitRPG/habitrpg/blob/develop/views/static/layout.jade
