### ISSUE TITLE
Changing subscription methods interrupts consecutive counter

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4583]
From an email:

> I had to change payment information because I could no longer send money to my PayPal account, and unfortunately, the only way I knew how to do this was to resubscribe. Although I was not supporting for a few minutes, I really feel as if I have been part of this premium gig for a solid three months with no plans on stopping. Is there any way I could please garner this incentive reward despite this mishap?

**Comment by crookedneighbor** [comment]
Did you edit the db for the user?

**Comment by lefnire** [comment]
Yeah, they're set - should've mentioned

**Comment by Alys** [comment]
Closing because you can now cancel a subscription before it ends and resubscribe without a break in the counter.
