### ISSUE TITLE
Deleting reward also deducts gold

### ISSUE THREAD

**Issue by ArachneJericho** [HabitRPG/habitica#4584]
Hello, 

User ID: 6b3b90f3-619a-4a0e-90d9-6efaa33e5b5c

I deleted a reward, "Fields of Arle", which was 2000 gold. The next thing I knew, 1000 gold was deleted from my account. I'm using the Chrome browser, version 40.0.2214.91. 

JS console errors: 

Failed to load resource: net::ERR_CONNECTION_REFUSED
2760:1 Unhandled promise rejection Promise__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: TypeError: Network request failedmessage: "Network request failed"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }**proto**: Error

Can I at least have my gold back? I can't find the menu item to set my character values.

**Comment by deilann** [comment]
Settings > Site > Fix Character Values

**Comment by ArachneJericho** [comment]
Oh, ok, thank you.
