### ISSUE TITLE
Erroneous Triad Bingo achievement notification

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#4586]
Right now I'm at 89 gen-1 pets with all the mounts. I just hatched a quest pet (octopus) and got a notification that I had achieved Triad Bingo. When I checked my stats page, sure enough, the Triad Bingo achievement was listed. I refreshed the page and the achievement went away, so all is well now, but I figured I'd mention it here so someone can look into it. The temporary achievement could be confusing for someone who isn't keeping as close track of whether they actually achieved it or not.

**Comment by crookedneighbor** [comment]
@hattieshoe Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

I thought I fixed this issue, but apparently not. I'm going to try to replicate it with your pet and mount data on my local install.

**Comment by hattieshoe** [comment]
User ID 0b670754-57f5-4704-854f-9a9c92107b9b
Not sure if this helps, but it happened this morning when I hatched the first of 2 octopus pets. Possibly desert. I then hatched a second octopus - didn't think to refresh first and see if the second would give me the notification again.

**Comment by crookedneighbor** [comment]
Hmm... @hattieshoe tried it on my local install and it's working as expected. 

It's possible that you have an old version of the hatching code and triad count script cached in your browser. Do you think you could reload your browser and try hatching another pet?

**Comment by hattieshoe** [comment]
I just cleared my cache, reloaded the browser and bought an octopus egg and a white potion since that's one of the two octopi I didn't have yet. I hatched the egg and got the same Triad Bingo notification, and the Triad Bingo is showing up again in my achievements. -- Then after doing ctrl-F5 again, the achievement is gone again.

**Comment by crookedneighbor** [comment]
Oh, I'm dumb. I forgot to remove the triad bingo achievement from local install. I've removed it now and I'm trying again.

**Comment by crookedneighbor** [comment]
Yep, there it is. Erroneous Triad Bingo Achievement.

I've fixed the script, now that I look at it (AGAIN), I see what was wrong. I've patched it and the new code should be deployed later today.

Thanks for your help on this!

**Comment by crookedneighbor** [comment]
Here's the commit that closed this issue: https://github.com/HabitRPG/habitrpg/commit/23c31083ef5c78ac1de4c0b5dfd190e67e1975f6
