### ISSUE TITLE
Casting Spooky Sparkles and a Snowman on a Character displays both a ghost and a snowman

### ISSUE THREAD

**Issue by joshbDev** [HabitRPG/habitica#4589]
The heading pretty much says it. Photo for evidence. It's a really small priority, but I thought I'd at least log it.
![screen shot 2015-01-28 at 12 50 21 pm](https://cloud.githubusercontent.com/assets/5234453/5949300/09f0fde2-a701-11e4-86ee-d28e8c7303da.png)

**Comment by Alys** [comment]
I've seen more people appreciate this as a feature than consider it a bug (I personally like the effect a lot and there was another comment saying that in the Tavern within the past day), but regardless, it's already been reported as a bug at https://github.com/HabitRPG/habitrpg/issues/4335 so you can follow the progress of it there.

**Comment by joshbDev** [comment]
oh, sorry! Thanks for the heads up.
