### ISSUE TITLE
Vagrant machine without npm?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4597]
I tried setting up habitrpg locally with vagrant but there are some issues.
I have the github windows program set up, cloned the habitrpg project and opened from github in the git shell.
Vagrant up works fine but when I login through vagrant ssh the user is vagrant@precise64 and not vagrant@habitrpg. Then when trying to npm start it says that npm is not installed. When I try to apt-get it it can't connect to the server.

**Comment by Alys** [comment]
I believe this indicates that the virtual machine that you logged in to is not the HabitRPG vagrant one, but instead is a different, unrelated VM. 

I'm guessing you did follow the Vagrant instructions in [Setting up HabitRPG locally](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Vagrant), but if not, it's important to follow the exactly.

I recommend that you completely delete all virtual machines you might have (assuming you don't need them for other purposes!) then check that your Vagrant version is recent enough (see the version number in those instructions) and then try again from the beginning. Keep a careful watch for any errors or warnings, including very early in the installation process. 

Let us know here as soon as you see something that looks wrong or that isn't easily understandable!

BTW, in the next week or two probably, the local install process will be simplified significantly. This might require a re-install for all existing local installs, or at least some manual changes to them. Unless you're eager to get started now, you might like to wait until the new process is in place.

**Comment by ghost** [comment]
thanks for the fast response, seems like the classic 'have you turned it off and on again' did the trick this time, I'll await agerly for the new process!
