### ISSUE TITLE
Mobile website exception

### ISSUE THREAD

**Issue by sergej-brazdeikis** [HabitRPG/habitica#4598]
_Observation_
Tried to access the homepage while loggedin on iPhone. When refreshing, the issue is the same.

```
{"err":"/app/views/shared/profiles/achievements.jade:35\n 33| =env.t('contribText')\n 34| |&, env.t('readMore'))\n 36| | .\n 37| hr\n 38| \n\nObject #<Object> has no method 'aLink'"}
```

_Browser_: iOS 8.13.3 Safari
_UserId_: 3fb933b9-522c-484a-9854-fd08a608e69f

![img_2845](https://cloud.githubusercontent.com/assets/1146115/5979420/c94d6b4c-a8a7-11e4-90f2-25439bfebd12.jpg)

**Comment by paglias** [comment]
We're sorry about this! It was a brief problem due to some broken code but
it should be fixed now. Could you try reloading one last time?

If it's still not working you should post it here.

And sorry again!
Il 30/gen/2015 17:43 "Sergej Jevsejev" notifications@github.com ha
scritto:

**Comment by sergej-brazdeikis** [comment]
Ok, I confirm, Its working! Thank for extremely fast response ;)
