### ISSUE TITLE
Orb of rebirth in pirate english misspelling

### ISSUE THREAD

**Issue by Sporax** [HabitRPG/habitica#4599]
![screen shot 2015-01-26 at 8 11 12 pm](https://cloud.githubusercontent.com/assets/10322112/5987130/390aa266-a942-11e4-94e5-79dafc917db7.png)

In the description of the Orb of Rebirth the word history is spelled _histroy_.
I wasn't sure where issues for other languages are posted so I added it here.

**Comment by crookedneighbor** [comment]
Thanks for pointing that out! I've fixed it and it'll show up on the app the next times the translatable strings get added to the repo.
