### ISSUE TITLE
Suggestion: Browser for the profiles of others

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#460]
This may have already been announced as a future project, but is there a way to browse the profiles of other Habit users so that I can invite them to join my party?

**Comment by horusofoz** [comment]
Please see our list of various sharing options currently up for voting on [Trello](https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6).

**Comment by wc8** [comment]
The two ideas [Map: Fantasy User Locations](https://trello.com/c/MyUoEMFg) and [Map: User Locations](https://trello.com/c/iGLFb8aX) could be one possible way of browsing users.

**Comment by cleave29** [comment]
Thanks, @wc8 !
