### ISSUE TITLE
Treasure not being spent

### ISSUE THREAD

**Issue by mxrowanthomas** [HabitRPG/habitica#4600]
So I sold a load of eggs/hatching potions yesterday and then spent the treasure on gems (I'm a subscriber) and when I logged in today it looks like the treasure is acting like it was never spent - I had <20 treasure when I finished yesterday and logging in today (in the browser I'd done the selling purchases yesterday) it said +320 treasure!!!!

Obviously I can just set character values to get rid of this but it seems a weird bug.

OS x V 10.9.5 Firefox 35.0.1 (up do date) UID: c03e41bd-501f-438c-9553-a7afdf52a08c

**Comment by Alys** [comment]
I'm attributing this to a [sync error](http://habitrpg.wikia.com/wiki/Sync_Errors). Sometimes, glitches like this just happen. If anything more serious occurs, definitely let us know!

I recommend checking that you still have all the gems you bought, and if not, buy them again now before the end of the month causes your gem cap to reset.
