### ISSUE TITLE
Purchased Subscription, Charged, Gems Don't Show Up

### ISSUE THREAD

**Issue by tulosai** [HabitRPG/habitica#4603]
My user ID is 29af8c6e-4116-4766-8f14-57344879cf1a

I purchased a subscription last night via paypal automatic transfer- not paypal using a credit card.  I have been charged, sent a message from Habit RPG about the new 'benefits' I have, and I do have my starry night armor and helm- thanks. However, I do not have any gems, and I do not have the ability to convert gold into gems.  Prompt attention to this would be extremely appreciated because I purchased the subscription  now in order to be able to buy the holiday hair styles-with gems. Since those are going away at midnight, it would be very useful to have the gems I purchased before then.

I can provide documentation of any of this promptly as necessary. Again I am truly hopeful this can be resolved before midnight EST. 

Thank you.

**Comment by paglias** [comment]
@tulosai hi,

If you bought a subscription it's normal that you didn't receive the gems directly, they are given only with a one time donation. But you should have the ability to convert gems to gold. 

Can you confirm that even after refreshing the page in your browser you don't have the ability at the bottomo of the inverntory (https://habitrpg.com/#/options/inventory/drops)?

**Comment by deilann** [comment]
Can you show a screenshot of the bottom of the market, where gems would be
purchaseable?

**Comment by tulosai** [comment]
My mistake actually thank you.  Form what I was seeing it looked like you
could purchase gems up on top of the screen where the gem icon is.  I
didn't realize you have to go to the drops.

Thanks again.

On Sat, Jan 31, 2015 at 10:19 AM, deilann notifications@github.com wrote:

> Can you show a screenshot of the bottom of the market, where gems would be
> purchaseable?
> 
> On Sat, Jan 31, 2015 at 7:14 AM, tulosai notifications@github.com
> wrote:
> 
> > My user ID is 29af8c6e-4116-4766-8f14-57344879cf1a
> > 
> > I purchased a subscription last night via paypal automatic transfer- not
> > paypal using a credit card. I have been charged, sent a message from
> > Habit
> > RPG about the new 'benefits' I have, and I do have my starry night armor
> > and helm- thanks. However, I do not have any gems, and I do not have the
> > ability to convert gold into gems. Prompt attention to this would be
> > extremely appreciated because I purchased the subscription now in order
> > to
> > be able to buy the holiday hair styles-with gems. Since those are going
> > away at midnight, it would be very useful to have the gems I purchased
> > before then.
> > 
> > I can provide documentation of any of this promptly as necessary. Again
> > I
> > am truly hopeful this can be resolved before midnight EST.
> > 
> > Thank you.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4603.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4603#issuecomment-72321672.

## 

American University Washington College of Law
Juris Doctor
