### ISSUE TITLE
Server failed to register my activity before cron

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#4607]
I ticked off a to-do and booked myself out of the tavern late tonight (but before my midnight cron). Only none of this happened according to the server. So I have derailed on Beeminder because the task did not get ticked off and I wasted some MP because the Stealth spell only lasts the day even if I am in the Tavern, plus I have missed out on the Perfect Day bonus and cannot tick things off today because they are all greyed out. Is there anything doable to fix the issues this end before I start my day tomorrow?

UUID: 4182cdea-64db-4db4-9713-dc587d86c662

**Comment by Alys** [comment]
This is an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4313
No need to comment there; I'll just add a link to this one. You can follow the progress of this bug there.

You can use Settings -> Site -> Fix Character Values (FCV) to change your MP and HP. You can also record your current GP and XP, untick your Dailies, then use FCV to set your GP and XP back as they should be.

You will have received a derailment email from Beeminder. Reply to it to briefly explain the problem and they will undo your derailment.

See this comment for a workaround that might help future occurrences: https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-70820170
