### ISSUE TITLE
Tutorial ends on avatar customization page, refreshes randomly on tasks page

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica#4608]
Just ran 3 remote usability tests on the current onboarding, and this happened 2 out of the 3 times (though the last tester didn't even get to the page where the problem was happening). So this is a pretty major bug in onboarding, and we just never saw it in real-time with real users.

When the test participants followed the tutorial and clicked to customize their avatar (the first thing it asks you to do), the tutorial disappears after the "Avatar Customization" popover, even when the user clicked on the "next" arrow. It's up to the user to find the tasks page again and restart the tutorial there manually, if they manage to find it in the menu.

If the tasks page refreshed automatically when the tutorial is not active, it'll also restart the tutorial from the very beginning, which confused one user who proceeded to ignore it.

For reference, see the two videos and annotations here:
- [User clicks "next" on avatar page, tour ends. Back-buttons to tasks page and restarts tutorial manually](http://www.usertesting.com/videos/3ascO3UWo83LyCO-xWAjAA)
- [User clicks "next" on avatar page, the tour ends. Eventually finds the tasks page, where tutorial refreshes automatically and she ignores it](http://www.usertesting.com/videos/4A7K7DDz4_zp9W4uYOxqsw)

**Comment by Alys** [comment]
We've changed the tutorial since then and I can't replicate this so I'm closing it. Reopen if desired!
