### ISSUE TITLE
XP from 'Burst of Flames' not triggering level up

### ISSUE THREAD

**Issue by AndersTrolle** [HabitRPG/habitica#4609]
I used 'Burst of Flames' on one of my Dailies. This gave my enough XP to go up a level, but instead my XP bar stayed full and said '1,316/1,300'.

Upon gaining XP again, this problem resolved itself, no XP was lost and no harm done.

User ID: 45d4b028-9571-46aa-b3ac-3e8133e48376

**Comment by Alys** [comment]
You can follow the progress of this bug fix here: https://github.com/HabitRPG/habitrpg/issues/2143
