### ISSUE TITLE
Inviting user to guild/party doesn't give feedback

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#4610]
No message is shown and invited list is not updated
##

**Comment by tsujin** [comment]
Do you mean feedback from the inviting party's end? Or from the receiving party's end? I'm not sure where to see the invited list, but I did receive a notification that said "Invitation(s) sent!" when I invited my friend to my guild:

![pggvnxv](https://cloud.githubusercontent.com/assets/11325100/6657279/18878ca0-cb1d-11e4-96c0-d42e31ea52b0.png)
This was on Google Chrome v41.0.2

**Comment by waldofe** [comment]
@paglias The "bug" persists? Could you check and close the issue if it's already okay?

**Comment by Sara-lily** [comment]
I saw the "Invitation sent" message as well, but the person I sent the invitation to never received the e-mail and they don't show up in the "Invited" section of my party.

**Comment by paglias** [comment]
Should be fixed
