### ISSUE TITLE
Iphone App Lost Progress

### ISSUE THREAD

**Issue by macdonaldethan** [HabitRPG/habitica#4612]
I am new to HabitRPG so I not really in a position to make this sort of modification myself. I am using HabitRPG mostly on my iPhone as it is usually with me and I can see most of the things that I can on the website. I've found conflicts are not resolved well when I am logged in on more than one device, so this is another reason I am mostly interested in using it on the iPhone. So.. I am about a week into using the app, and liking it so far.. maybe eventually I can start making some code mods myself.. Anyway, the issue I am struggling with is that I sometimes loose a lot of progress in the app, basically I think what is happening is that the progress that is registering on the app is not being sent to the main server? and then somehow queries the state back to a previous state I was in.. so I lose progress. This is really quite frustrating. I notice on the website there is a 'sync' button. Something like this could easily resolve the issue and I could force push my progress to the server? How hard would a feature like this be to add? 

I'm quite interested in seeing the support community for HabitRPG! Hola!

**Comment by crookedneighbor** [comment]
@macdonaldethan Dragging down on the iPhone from the top of the screen (like refreshing for new mail) should prompt it to sync.

There is a known bug where data doesn't get saved when the phone can't connect to the internet, and it's been patched and submitted to the App Store, but the store has been even slower than usual to approve the update. So, all that to say, look for the update, it should be deployed soon (hopefully).

**Comment by macdonaldethan** [comment]
Okay, thanks Neighbour. I'll close this issue.
