### ISSUE TITLE
Cannot create checklists for challenge

### ISSUE THREAD

**Issue by edunham** [HabitRPG/habitica#4613]
![2015-02-02-153228_1032x477](https://cloud.githubusercontent.com/assets/812892/6011520/7d9a74f0-aaf1-11e4-8564-f1d1c15b6109.png)

Can others reproduce this? If so, is it "correct" behavior? 

I'm trying to create a checklist on a TODO task for a guild challenge, and the "create checklist" box is missing. 
Checklists are working as well as they ever do on my personal TODO items. I saved the challenge, reloaded the page, went to "edit challenge" and am still not getting the option of creating a checklist. It might be worth noting that I'm not getting the button to create checklists on daily tasks when making a challenge either. 

There's a big awkward blank space within the "edit task" box where the checklist button would normally appear, which makes me think it should be possible to create them in challenges.

**Comment by Alys** [comment]
It is correct behaviour. Disallowing checklist for the challenge creator means that the participants can add checklists, which has some desirable consequences. If a checklist is important to your challenge, create a To-Do with instructions for what to add. Please read the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges) page for documentation about this.
