### ISSUE TITLE
Client side error tracking

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#4620]
We should start tracking client side errors as they happen, it would have been really useful in a few situations we are dealing with right now

**Comment by paglias** [comment]
https://habitrpg.loggly.com/sources/setup/js

**Comment by lefnire** [comment]
NewRelic also supports client-side tracking, if we prefer staying on that

**Comment by paglias** [comment]
The version with error tracking costs 99$/mo http://newrelic.com/browser-monitoring/pricing

We could start with the 14 days trial and see how useful it is and in the meantime find cheaper solutions

**Comment by paglias** [comment]
btw, I've disabled loggly since I don't use it anymore but we can add it
again very easily if we need to

2015-02-03 21:17 GMT+01:00 Tyler Renelle notifications@github.com:

> NewRelic also supports client-side tracking, if we prefer staying on that
> 
> On Tue, Feb 3, 2015 at 1:12 PM, Matteo Pagliazzi notifications@github.com
> 
> wrote:
> 
> > https://habitrpg.loggly.com/sources/setup/js
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4620#issuecomment-72724887.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4620#issuecomment-72725814.

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
Woa mama, didn't realize! Let's try your solution then ;)

**Comment by paglias** [comment]
I'm not even sure we can use the trial since we have Browser Lite
listed in our new relic subscription. will try tomorrow and report
back

2015-02-03 21:23 GMT+01:00, Tyler Renelle notifications@github.com:

> Woa mama, didn't realize! Let's try your solution then ;)
> 
> On Tue, Feb 3, 2015 at 1:22 PM, Matteo Pagliazzi notifications@github.com
> wrote:
> 
> > The version with error tracking costs 99$/mo
> > http://newrelic.com/browser-monitoring/pricing
> > 
> > We could start with the 14 days trial and see how useful it is and in the
> > meantime find cheaper solutions
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4620#issuecomment-72726660.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4620#issuecomment-72726913

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
It looks like we can have the trial! I'll activate it after the next deploy

**Comment by Alys** [comment]
I'm closing this because as far as I'm aware, we have various kinds of tracking now and I think this issue is outdated. Feel free to reopen though. :)
