### ISSUE TITLE
Gems Disappeared after I bought them  -- gems being subtracted twice?

### ISSUE THREAD

**Issue by justicar347** [HabitRPG/habitica#4624]
Using Chrome version 40
User ID: 7f4483a2-b6b1-434f-82b1-899927234c98

I subscribed for 12 months and used some of my built up gold to buy gems. I had a total of 47. I spent 15 to get a background set and 3 to change my class. Then yesterday after cron I only had 11 left.

**Comment by Alys** [comment]
@justicar347 Could you please go to [Settings -> API](https://habitrpg.com/#/options/settings/api) and check that the User ID above is correct, and can you also please tell me what your HabitRPG profile name is? That's the name that appears on your avatar in the header and on your messages in party or Tavern or guild chat.

**Comment by justicar347** [comment]
It is correct and my User ID should be Seth.

**Comment by Alys** [comment]
Thanks @justicar347. I've given you back the missing 18 gems. If you don't see them after reloading, comment here again. We'll see if even though this issue will be closed.

**Comment by justicar347** [comment]
My gems have disappeared again. This is concerning.

**Comment by Alys** [comment]
Can you please give us specific details? How many gems? Were you trying to buy something at the time? If so, what? What did you click on? What should have happened, and what did actually happen?

**Comment by justicar347** [comment]
28 gems. They were just gone when I logged on in the morning. I did not try to buy anything. So far as I know I have not clicked on anything.

**Comment by Alys** [comment]
can you tell me roughly how many hours ago you logged in?

**Comment by justicar347** [comment]
19 hours I think.

**Comment by Alys** [comment]
I'm starting to investigate now (I've been asleep over the past several hours). 

How many gems did you have after the 28 gems disappeared? If you still had some left, did you buy anything with them in the past 10 hours? I'd like to know this so that I can properly track the effects of the bug that caused this problem.

**Comment by Alys** [comment]
@justicar347 Sorry, my second question should say: If you still had some left, did you buy anything with them at any time between when the 28 gems disappeared and now?

**Comment by Alys** [comment]
I have done some investigation into this and am discussing it with Lemoness.

**Comment by Alys** [comment]
@justicar347  I checked your account by examining a few database backups and the gems didn't actually disappear. Instead they were used to buy seven quests at some time between 6 and 12 February. So this isn't actually a bug at all.

**Comment by justicar347** [comment]
You are correct. I feel stupid for forgetting that. Thank you.
