### ISSUE TITLE
[UI] Empty items denied starting from 2nd try, instead of 1st.

### ISSUE THREAD

**Issue by mdolbin** [HabitRPG/habitica#463]
Not a big deal but you can add one empty item per each list (habits, Daily, Todos, Rewards) per page refresh. The very first empty item assignment for each list isn't handled as error as it happens with following.

<pre>
    # Don't add a blank task
    if /^(\s)*$/.test(text)
      console.error "Task text entered was an empty string."
      return
}
</pre>

text variable is undefined at the 1st click, later on, after 1st click, it becomes to be an empty value. I made a quick fix:

<pre>
    # Don't add a blank task
    if /^(\s)*$/.test(text) || text == undefined
      console.error "Task text entered was an empty string."
      return
</pre>

but there is still an issue should be fixed: why is it undefined at the very beginning?

![habitsrpg](https://f.cloud.github.com/assets/3534827/177931/1f436f74-7ba5-11e2-9375-fd102573f2af.jpg)

**Comment by Pandoro** [comment]
Has this been merged into the master branch ?

**Comment by lefnire** [comment]
just now I did
