### ISSUE TITLE
Checking a Todo during tour starts it over

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4632]
And it's only effected by ToDos (Dailies etc are just fine). Normally whatever, but users are likely to check a todo at this section of the tour given the default "Join HabitRPG (check me)" ToDo.

![tour](https://cloud.githubusercontent.com/assets/195202/6057396/2e6834bc-acdb-11e4-88a4-9e2598dbefb4.gif)

**Comment by deilann** [comment]
Pretty sure this is intentional behaviour. Feature, not bug. @lefnire Can
you read the guidelines for submitting issues in this repo, and make sure
to post your UUID and OS/Browser? If you need help finding this info, just
let us know!

**Comment by lemoness** [comment]
;p

**Comment by lefnire** [comment]
Strangely, it's caused by something in [user.log](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/userServices.js#L186), but I haven't pegged it. I've created a [branch](https://github.com/HabitRPG/habitrpg/tree/lefnire/introjs) using [intro.js](http://usablica.github.io/intro.js) instead of bootstrap-tour, which gets around the issue. However, I'm not satisfied with introjs after implementing - it's less flexible and slick. Will need the flexibility coming up with interactive tours, so will probably need to stick to bootstrap-tour
