### ISSUE TITLE
Server queries user from DB 7x / page-view

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4639]
Upon page refresh, the server queries (finds) the viewing user from MongoDB 7 separate times, plus 1 update (`{$set:{_v:xxx}}`) https://gist.github.com/lefnire/751483e04fb4a47ca540. Quite unnecessary. I haven't investigated how many loads per operation of an already loaded page (scoring, edits, etc) but I imagine it'll also be unnecessarily high. Fixing this can reduce server load theoretically by ~7x. 
##

**Comment by paglias** [comment]
@lefnire even when cron doesn't run?

**Comment by lefnire** [comment]
@paglias correct

**Comment by paglias** [comment]
Anyway what I found is:
1. Auth: find user
2. Cron: 
   1. If cron doesn't run: nothing
   2. If cron runs but no quest: save user
   3. If cron runs with collect quest: save user, run quest updates (update group, sometimes upgrade user) and then reload use
3. Batch update: save user

We could compact the user save at the end of the op but still we're far from 7

**Comment by lefnire** [comment]
Anything on the page, after the initial load, which might make more requests for the user? Eg, does it run `User.log({})` too many times after the page is already loaded client-side?

**Comment by paglias** [comment]
I thought it was 7xReq not page view, then we have: https://github.com/HabitRPG/habitrpg/blob/ec114d6a3e277242fefcd3bdb9640a2a034ab2f8/src/controllers/groups.js#L363 to update lastSeen, a User.log({}) to sync the user data

**Comment by paglias** [comment]
What I don't get are the 4 find user by _id only, not even by id and apiToken

**Comment by paglias** [comment]
One is probably to log in using the session

**Comment by paglias** [comment]
@lefnire using your gist as a reference:
- `0` is query to get party 
- `1` session authentication
- `2` no idea (_v update)
- `3` is call to https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv2.coffee#L549 seenMessage 
- `4` is auth for ajax call
- `5` is auth for ajax call to get party
- `6` no idea (find by _id)
- `7` no idea (find by _id and apiToken)
- `8` no idea (find by _id)

**Comment by paglias** [comment]
@lefnire do you have a party in the request you tested? Because then I think a lot of the `find user by _id` are calls to populate the `members` field of the party and in case of `challenges` those will be populated too (huge for big parties)

**Comment by paglias** [comment]
@lefnire and finally the `_v` update is due to each api call that triggers a `user.save` (like an empty batchUpdate) because of this line https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L485

I think we have all of them.

Possible solution:
- cache members in parties
- send the user and the party along with the page

**Comment by lefnire** [comment]
Testing user wasn't in a party. That query happens even without a party, and as you can see `_id` is the same each time. If you want to test locally, here's what I do. In mongo shell run:
1. `db.setProfilingLevel(0);db.system.profile.drop();db.setProfilingLevel(2)` - this clears and turns on query-profiling. I do this between each thing I want to test, so it's fresh for just that scenario
2. Refresh the page
3. `db.system.profile.find({ns:{$not:/habitrpg.system..*/}}).sort( { ts : -1 } )` - this shows you all the queries which were run since step 1

**Comment by paglias** [comment]
Ok so we have three unknown queries:6,7,8

Anyway the populations for parties are probably impacting a lot

**Comment by paglias** [comment]
Should be fixed in v3, also read queries are fast and cheap
