### ISSUE TITLE
Page completely unresponsive, visuals messed up/gone. Works fine on phone app though

### ISSUE THREAD

**Issue by strawberrymilano** [HabitRPG/habitica#4640]
![habitrpgbug](https://cloud.githubusercontent.com/assets/10870556/6069115/bc2ddbb6-ad4f-11e4-83e9-b767d38944d1.png)

It's been like this for over three days now, with no change. Nothing happens when I refresh the page. It's exactly the same. There are no buttons that work on it, either. The only reason I haven't died yet is because the phone app doesn't seem to have any problems. There are no JavaScript error pop-ups, either. Please help this is horrible and killing me slowly on the inside. 

OSX 10.9.5
Using Firefox 35.0.1 
User ID: 04ce8883-aefc-44d8-b3f5-a0f0351c524d

**Comment by paglias** [comment]
@strawberrymilano sorry about this! You should open the console (ctrl+shft+k in fiefox) and report any error you see there. Also could you try using a different browser/cleaning your cache (but only after you have opened the console!) to see if it works

**Comment by strawberrymilano** [comment]
I opened the console, this is what came back: 

GET http://habitrpg.com/ [HTTP/1.1 302 Moved Temporarily 179ms]
GET https://habitrpg.com/ [HTTP/1.1 200 OK 1138ms]
GET https://habitrpg.com/bower_components/github-buttons/github-btn.html [HTTP/1.1 304 Not Modified 63ms]
<source> element has no "src" attribute. Media resource load failed. habitrpg.com
All candidate resources failed to load. Media load paused. habitrpg.com
"Error: JSON.parse: expected ':' after property name in object at line 1 column 131078 of the JSON data
@https://habitrpg.com/app-f8b3d369.js:27:18066
i@https://habitrpg.com/app-f8b3d369.js:5:17575
c@https://habitrpg.com/app-f8b3d369.js:5:15971
i@https://habitrpg.com/app-f8b3d369.js:5:17575
Tc/j.$injector<@https://habitrpg.com/app-f8b3d369.js:5:15621
g@https://habitrpg.com/app-f8b3d369.js:5:17210
i@https://habitrpg.com/app-f8b3d369.js:5:17544
id/this.$get</</<@https://habitrpg.com/app-f8b3d369.js:6:9189
pb/<@https://habitrpg.com/app-f8b3d369.js:6:3523
x@https://habitrpg.com/app-f8b3d369.js:4:24723
pb@https://habitrpg.com/app-f8b3d369.js:6:3507
r@https://habitrpg.com/app-f8b3d369.js:5:29977
h@https://habitrpg.com/app-f8b3d369.js:5:29025
g/<@https://habitrpg.com/app-f8b3d369.js:4:31189
we/this.$get</j.prototype.$eval@https://habitrpg.com/app-f8b3d369.js:7:17083
we/this.$get</j.prototype.$apply@https://habitrpg.com/app-f8b3d369.js:7:17317
g@https://habitrpg.com/app-f8b3d369.js:4:31147
i@https://habitrpg.com/app-f8b3d369.js:5:17575
xb/g@https://habitrpg.com/app-f8b3d369.js:4:31066
xb@https://habitrpg.com/app-f8b3d369.js:4:31376
wb@https://habitrpg.com/app-f8b3d369.js:4:30599
@https://habitrpg.com/app-f8b3d369.js:9:1420
n.Callbacks/j@https://habitrpg.com/app-f8b3d369.js:1:26906
n.Callbacks/k.fireWith@https://habitrpg.com/app-f8b3d369.js:1:27724
.ready@https://habitrpg.com/app-f8b3d369.js:1:29516
I@https://habitrpg.com/app-f8b3d369.js:1:29707
nrWrapper@https://habitrpg.com/:1:11505
" app-f8b3d369.js:6

I'll try another browser just to see if it works there, sure. And I'll try emptying the cache as well.

**Comment by paglias** [comment]
@strawberrymilano in firefox load the page fully, open the console (ctrl+shift.k), at the bottom there is a line where you can write, enter localStorage.clear() and press enter, then reload the page, it should redirect you to /static/fron after a bit. From there you'll be able to login again. If it doesn't redirect you then manually go to habitrpg.com/static/front and try logging in.

Let me know

**Comment by strawberrymilano** [comment]
IT WORKED! THANK YOU <3

**Comment by paglias** [comment]
@strawberrymilano great :)
