### ISSUE TITLE
The hero didn't level even the experiences are over the limit.

### ISSUE THREAD

**Issue by PJ007** [HabitRPG/habitica#4642]
I grabbed enough experiences to level up. In spite of theht I have 573 of 460 Exp.
How can I level then?
PJ007, ID
a3aa9d1e-7826-42ed-9f72-6a787869f252
Win 7, Chrome Version 40.0.2214.111 m

**Comment by crookedneighbor** [comment]
The next time you check off a task, you'll level up. 

Duplicate of #2143

**Comment by PJ007** [comment]
Thank you. It works.
I got myself over by casting the "Burst of Flames" spell two times.
