### ISSUE TITLE
Boss damage not applied when completing to-dos on app?

### ISSUE THREAD

**Issue by itokro** [HabitRPG/habitica#4643]
On the Android app, I checked off a couple of dailies and two high-value to-dos. I then returned to my computer, where I had the HabitRPG website open, and checked the Data Display Tool to see how much damage I'd managed to do. The damage in the DDT was surprisingly low, and I realised that the app-based changes hadn't yet been synced. I then synced properly, and the damage in the DDT did increase - but only by a couple of points, equivalent to what I'd expect from the dailies alone (given how old these to-dos were, and the fact that one of them had a 7-item completed checklist, there's no way the to-dos would have done this little damage!). It therefore looks like boss damage wasn't calculated or applied from the to-dos I checked on the app, although I have no idea why this might be.

**Comment by Alys** [comment]
Are the To-Dos still marked as completed when you look at them on the website?

**Comment by itokro** [comment]
They are indeed! (I have now manually fixed the lack-of-boss-damage issue for myself by unchecking and rechecking the To-Dos, but they were marked as completed on the website even before this)

**Comment by Alys** [comment]
@paglias @lefnire FYI. @itokro ticked off tasks on the app, and that action was synced to the server, but `party.quest.progress.up` was not incremented for them. This is new and odd.

@itokro I'm sorry that happened! If you notice this happening again, please do tell us about it! It might be a while before we can work out what's causing this. :(

**Comment by Alys** [comment]
@itokro I'm sorry we never solved this. I'm closing it now because the old apps are being replaced by new ones and whatever caused the bug is unlikely to be in them.
