### ISSUE TITLE
Gems display in item purchase popup is a little confusing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4645]
Today I bought a Fortify Potion, and was disoriented for a minute because the upper right corner of the modal said 5 Gems, but the price of the item was 4 Gems. I thought there was some sort of inconsistency going on! After my double-take, I realized that the 5 was my current balance, not the price of the item. Perhaps the Gem balance readout could say "You have N Gems" instead of simply "N Gems", for clarity?

**Comment by Sporax** [comment]
I could give it a shot

**Comment by mareps** [comment]
Is it done?

**Comment by Alys** [comment]
@mareps When significant progress is made on issues, there is always some kind of update on the issue, even if it's an automatic one that links to pull requests containing fixes. When issues are completed, they are usually closed; sometimes we forget to close them but you can tell that that's happened when the issue links to pull requests that have been merged. When you don't see any updates like that (as in this case), then the issue has not been done.

**Comment by remmz0r** [comment]
@Alys Where would I find the modal for the Fortify popop?

Edit: found it

**Comment by remmz0r** [comment]
@SabreCat - would it be fine if it said (19) Your Gems ??

**Comment by remmz0r** [comment]
@crookedneighbor - I've got code ready to push for this, if it's allowed to say "X Your Gems"

**Comment by crookedneighbor** [comment]
@remmz0r Can you take a screenshot and post it here?

**Comment by remmz0r** [comment]
Where is the code that is included by +gemButton in reroll.jade? So I can make the change specifically for the gemButton only.

For instance changing Gems to Your Gems makes the gem popup on the main gem button at the top of the site say Your Gems too...

**Comment by crookedneighbor** [comment]
@remmz0r This should help: https://github.com/HabitRPG/habitrpg/search?utf8=%E2%9C%93&q=gemButton

**Comment by remmz0r** [comment]
Need to edit some extra code so it doesn't affect the buy menu either. I'll keep at it.
![untitled-1](https://cloud.githubusercontent.com/assets/11038374/6238051/dc32f490-b732-11e4-9afd-a1f2736e9f70.png)

**Comment by crookedneighbor** [comment]
@SabreCat Should the gem button even appear if you have enough gems to buy the potion?

**Comment by remmz0r** [comment]
It's not my place to put input here, but if for instance someone wants to fortify but they are saving gems for a background set as well, they might want to buy ontop of purchasing the potion. My 2c.

**Comment by SabreCat** [comment]
If the popup were positioned such that you can still see the currency readout, there'd be no problem omitting the Gems in the modal itself. You'd want to check that works OK even under squeezed resolutions, though.

"10 Your Gems" reads pretty oddly, in the proposed screenshot. Maybe "Your Gems [gem] 10"?

**Comment by crookedneighbor** [comment]
We could also make the text smaller and say "You have x Gems":

![screen shot 2015-02-17 at 9 47 37 pm](https://cloud.githubusercontent.com/assets/2916945/6242134/9f20a758-b6ee-11e4-9374-29c7d3f87e2d.png)

**Comment by remmz0r** [comment]
I can make it say [gem] You have [x] gems, or Your Gems [gem] [x]  now that I know where the gemButton is =) Let me know which way you'd like me to proceed.

**Comment by Alys** [comment]
"You have [x] Gems". It's good English and unambiguous.

**Comment by remmz0r** [comment]
Is that a definitive? I will do it right now for you if so

Edit: I've pushed that change anyway

nb. this PR also changes the gems display in the buy gems modal

**Comment by SabreCat** [comment]
Sounds good to me!

**Comment by remmz0r** [comment]
@crookedneighbor - Fixed the code as you requested
