### ISSUE TITLE
Hair color selection buttons are inconsistent

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4646]
The baseline hair colors use simple color swatches for their buttons, while all subsequent hair colors have sprite previews of what they look like on their buttons. This is inconsistent and a little odd, especially if you happen to have the earliest premium hair colors available right next to them:

![image](https://cloud.githubusercontent.com/assets/4501321/6093356/ab8eaa06-aec6-11e4-8fe1-306ef02f9ba1.png)

I know I frequently find myself thinking, "wait, where are the normal colors?" before I realize the brown box is the thing I'm looking for. We should update the baseline hair colors to use the same style of button as everything else.

**Comment by lemoness** [comment]
Agreed! Do you need me to get you any different sprites, or can you use the
current ones in Spritesmith?

**Comment by SabreCat** [comment]
I think they use the existing sprites? I will look into it!

**Comment by SabreCat** [comment]
This'll be fixed with the Valentine's Day rollout.

**Comment by lemoness** [comment]
Hooray!
