### ISSUE TITLE
Please reload: Error inviter not in party

### ISSUE THREAD

**Issue by obishop** [HabitRPG/habitica#4649]
My friend sees this error every time she refreshes the page and cannot click her habits and dailies. Her user id is 9c3ec74b-8f79-43eb-91f1-b884bcea93b6.

While we were trying to figure out party invites, I think we created a party and left it, and created a new one. This probably got our data into a bad state somehow.

The party id of the one we are in now is 984fc1e6-ac09-41cd-b404-e913c7adebbb, but this may pertain to the one we created and left.

It's a 500 internal server error in the chrome console.

**Comment by Alys** [comment]
I can probably do something about this in about an hour. I think it will help if you could tell me the user ID of the person who sent the invitation, if you're able to work that out. If you're not sure who sent it, giving me a few possibilities might help -- although if it could be anyone in your current party, just tell me that and I can easily pull the user IDs from the database.

**Comment by Alys** [comment]
@obishop I don't need the user ID information I asked about. I've had a look at your friend's account and there are no invitations stored in her data. I believe the invitation would have been cached in her browser - I experienced something similar myself a while back. 

Firstly, if she has another browser available to her, she should try logging in using it. If it works, then it's definitely just a caching problem in her original browser. But if she gets the same error in a second browser, then she should let us know!

If she wants to keep using her first browser, she should try clearing her cache. If she's not sure how, googling for instructions for her particular browser should show her some instructions.

She should also make sure that the URL she is using in EITHER browser does not contain any parameters. If she has HabitRPG open in any browser, she should close it. She should go back to the site by using this exactly URL: **https://habitrpg.com**

**Comment by paglias** [comment]
Should be fixed now

**Comment by obishop** [comment]
Thanks!

—
Olivia Bishop
