### ISSUE TITLE
Clicking on a challenge from a guild opens an empty challenges page with an error under the settings icon.

### ISSUE THREAD

**Issue by btallitsch** [HabitRPG/habitica#4650]
Hi. This is my first issue. Here is my user ID: 2925b7ac-237b-4e76-8c85-5406c7f5dbcf

When I click on a challenge from any guild page, it opens an empty Challenges page with a "Please reload error" in red. When I reload the page, the same error appears. 

See attached image of error:

![screen shot 2015-02-08 at 3 33 37 pm](https://cloud.githubusercontent.com/assets/1752682/6098322/b1d50f62-afa8-11e4-8596-3fc15231b567.png)

I am using Google Chrome on Mac version 40.0.2214.111 (64-bit)

In the chrome console, there are 2 errors relating to a 500 internal server error: 

![screen shot 2015-02-08 at 3 44 30 pm](https://cloud.githubusercontent.com/assets/1752682/6098339/6a73b816-afa9-11e4-9453-e4a3fb09941d.png)

**Comment by deilann** [comment]
I am sorry that no one got back to you on this? Is this still happening to you? These kinds of errors are usually transient.

**Comment by btallitsch** [comment]
I believe it was a server error. I am not seeing his as an issue still

Thanks, 
Bill Tallitsch

**Comment by deilann** [comment]
Glad to hear it! :+1:
