### ISSUE TITLE
PayPal Gift payment for own account not successful

### ISSUE THREAD

**Issue by ZidaneTribal** [HabitRPG/habitica#4651]
Hello,
I tried today to gift myself a subscription using Paypal, but after the success page from Paypal I got the following error: {"err":"member is not defined"}
Shortly after that I got a confirmation mail from Paypal. So I guess I paid for a subscription that did not reach my account.
I tried to gift myself since this seems to be the only way to pay for a subscription from Germany.

I have saved the query parameters paymentId, token and payerId from the Paypal response call. 

My User-Id is 7a04a8e8-204c-42ad-a57c-d1bfbed09974
The PayPal transaction code is 44266808VF073271N

I have waited for a while to see if there would be a delayed message in HabitRPG but it seems that my account was not found, which is strange since I am currently logged in and everything is working.

So in the end I am quite confused where my money went. I hope you can clear that up for me

**Comment by ZidaneTribal** [comment]
Seems to be a problem related to gifting... Since I could just buy gems successfully with the same account (in Paypal as well as HabitRPG)

**Comment by paglias** [comment]
Sorry about this. I found the problemi and will fix everything before
tomorrow. Thanks forma the patience and for the report
Il 08/feb/2015 23:47 "ZidaneTribal" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
The bug has been fixed, @paglias have we given @ZidaneTribal the missing gems?

**Comment by paglias** [comment]
No, it's a subscription
Il 09/feb/2015 20:47 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by ZidaneTribal** [comment]
Yes it was a 12 month subscription, would be nice if I could get it until the weekend ;-)

**Comment by ZidaneTribal** [comment]
Guys, what is the current state of my subscription? I am normally quite patient but my patience is running low at the moment :-(

**Comment by deilann** [comment]
Can you email admin@habitrpg.com linking the ticket and repeating some of
the info?

**Comment by lefnire** [comment]
@ZidaneTribal I just ran the migration, could you check all went through ok

**Comment by ZidaneTribal** [comment]
Ads are gone and the subscription is shown in the purchase dialog (ending 02/22/2016). So I would say everything looks fine, thank you :-)
