### ISSUE TITLE
"error processing string" message on eggs and potions

### ISSUE THREAD

**Issue by selena-ariel** [HabitRPG/habitica#4652]
# EDIT from Blade: There is no need to add new comments to this issue, we're aware of the problem and are currently working on it. Thanks for your patience.

I got [this](https://scontent-a-lga.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10959549_1609090509335850_1018625190706270762_n.jpg?oh=3fc31618e94a1043e214988cbdfff9ef&oe=554D80EE) error message for a few drops. I also get [this](https://scontent-b-lga.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10246531_1609090976002470_988516759641887639_n.jpg?oh=e120ea2f72cdf585dc6459f96e1c0cb0&oe=554A3A24) message whenever I hover over any of my items.

I have no idea what it's about, or why I'm getting these messages, because nothing seems to be wrong. (As far as I know, I'm getting all of the 'string-missing' drops, but it's hard to tell because I have so many already.) I can feed and hatch my pets without a problem. But @Alys said I should report it, so I did. Hope it helps, and let me know if you need any more info...

**Comment by selena-ariel** [comment]
Oh, oops, ps: I realized that I only showed the message for Dragon Eggs. It isn't only about Dragon eggs, though, it's the same message for any type of drop or any inventory item, both of the pics being dragon eggs is just an accident.

**Comment by antil0pa** [comment]
came here to report the same bug:

> You've found a Lion Cub Egg! Error processing string. Please report to http://github.com/HabitRPG/habitrpg.

Firefox 35.0.1, Archlinux

**Comment by stringb** [comment]
I also got the first error message for (only?) one of my drops (about 15-30 minutes ago). 

(c0b5a9b3-d65a-4b97-9526-f5cbfd3a5d16, Safari 8.0.3, Yosemite 10.10.2)

**Comment by mayajosyula** [comment]
I'm encountering the same problem when I hover over any of my eggs/hatching potions in the Market. My quest scrolls and food appear normal though. 
Edit: Recently got a drop, and I'm getting the same error message as the first post for that too. I use Chrome on Windows 8.

**Comment by kathcmills** [comment]
I am also getting this error, both when I receive the drops and on eggs and potions in the Market. I use Chrome (Version 40.0.2214.111) on Windows 7.

**Comment by rahaeli** [comment]
Another person having the same problem:

You've unlocked the Drop System! Now when you complete tasks, you have a small chance of finding an item. You just found a Wolf Egg! Error processing string. Please report to http://github.com/HabitRPG/habitrpg.

**Comment by kaitmiller** [comment]
I'm getting the same error message.
![screen shot 2015-02-08 at 6 47 26 pm](https://cloud.githubusercontent.com/assets/8716943/6099966/393b7cf4-afd4-11e4-8a72-617c493580dc.png)

**Comment by LostInAForest** [comment]
yep, same issue for me too.

user id: b92c0adf-1741-47b4-8710-163b906409ed
win 8.1, firefox 35.0.1

**Comment by crookedneighbor** [comment]
@negue Could this be related to your PR: https://github.com/HabitRPG/habitrpg-shared/pull/460

**Comment by Sophi007** [comment]
This has happened to me too. When I hover on any of my items in inventory, it says "Error, processing string, report to Github."

I use a Windows 7 Huelet Packer, and Internet Explorer.

**Comment by jengoesup** [comment]
Samesies...Chrome, Mac OS Yosemite.

**Comment by eapearce** [comment]
Same issue. Windows 7, Chrome. Received the error when I got drops for a dragon egg and a cotton candy pink hatching potion.

**Comment by Shadowmancer** [comment]
![habitrpghatchingpotion](https://cloud.githubusercontent.com/assets/10917624/6101750/a1434b58-afe6-11e4-81bc-95f2e18de6e3.png)
It affects eggs and hatching potions. Anything else? I first noticed it getting a base potion / dragon egg.

**Comment by negue** [comment]
@crookedneighbor it will work once the uptodate habitrpg-shared is published too (just saw that you also compiled habitrpgh-shared.js https://github.com/HabitRPG/habitrpg-shared/commit/e5e9f054d19cec6056ba755a1f32298e147c5fa5 )

**Comment by Atramagus** [comment]
Adding another receiving the message on all hatching potions and eggs.

**Comment by akat88** [comment]
I also received this error message several times starting 2/8/15. Any tips on how to get it sorted out?

**Comment by crookedneighbor** [comment]
Thanks everyone, we've pinpointed the problem and are working on it currently.

**Comment by paglias** [comment]
should be fixed

**Comment by Atramagus** [comment]
Refreshed the page, can confirm that the error message is gone.

**Comment by akat88** [comment]
Thank you so much for fixing it :)

**Comment by Sophi007** [comment]
I logged out and logged back in. Error is gone! Thanks so much! :)
