### ISSUE TITLE
Can't access old account

### ISSUE THREAD

**Issue by sarusoule** [HabitRPG/habitica#4653]
I stopped using HabitRPG for a while, with the last usage being well before the apps were out and when it wasn't possible to register using a specific name or email (instead using the UID and API Token to log in). I've been trying to access my old account, but obviously things have changed a lot. Luckily my old info (UID and Token) are still stored in the Chrome Ext, but I have no way to log into the main site with them. Fortunately, I can still use that information to log into the Android app. I was a Kickstarter backer, so I'd hate to not be able to access this account using a web browser

**Comment by Alys** [comment]
We'll need to know the user ID for your old account otherwise there's no way we can work out which one it is. Do not tell us the API Token (it's a password).

**Comment by Alys** [comment]
To clarify: Once we know what your old account is, we can tell you how to get access to it (e.g., the email address for logging in, or similar information).

**Comment by sarusoule** [comment]
The UID of my old account is 1f3dfd7a-d1b2-4607-92a6-58dfc076eb5e

**Comment by Alys** [comment]
I've looked at your account and I believe that the reason you weren't given a username and password for it is that you registered with Facebook. Can you please try using the Facebook login option to get access to it in your browser?

**Comment by sarusoule** [comment]
That worked. I don't remember syncing it with Facebook (it even gave me the prompt usually reserved for an initial bind), but again, it's been a while since I last made use of HabitRPG. I went ahead and registered a user and email. I appreciate your help on the matter

**Comment by Alys** [comment]
No worries! Thanks for letting us know it's all working now! Welcome back. :)
