### ISSUE TITLE
error processing string

### ISSUE THREAD

**Issue by hazyhazy** [HabitRPG/habitica#4656]
Hello, I got this message in the window when I got a Dragon egg. It said I should report it here. I hope any problems, if they are there, will be fixed.

**Comment by nelle013** [comment]
I got the same thing. Seems like it's only happening when an egg drops, not food.

**Comment by swensonj** [comment]
The message also occurs when I hover over an egg or hatching potion in the Market.

**Comment by nthanaw1** [comment]
I received this message as well upon an egg drop, and now it appears when I hover over items in my inventory or the market.

**Comment by crookedneighbor** [comment]
Duplicate of #4652
