### ISSUE TITLE
Double Damage?

### ISSUE THREAD

**Issue by AmandaMock** [HabitRPG/habitica#4657]
I seem to be doing double damage in my party and taking double damage. It killed myself and my party when it wasn't supposed to :( 

User id: 2d98182f-cd24-4048-aca8-f691708a1f14
Group ID: fbed4fb8-73c7-48e8-88c3-208713f02a3a

**Comment by crookedneighbor** [comment]
@AmandaMock do you use Habitrpg on more than one device? If so, are the timezone settings different between them?

Is the damage identical, or different? Can you post a screenshot of your party chat where it shows the damage being done to the boss and your party? (You'll have to do this by logging into Github and dragging your screenshot onto a comment, it will not work by attaching a screenshot to an email)

**Comment by Alys** [comment]
@AmandaMock This has already been reported in https://github.com/HabitRPG/habitrpg/issues/2805 so could you please add the additional information there?

I'm going to close this issue now so we don't have duplicates in the system, but it's been linked to from the primary issue. If you want notifications when the primary issue is updated, you can use the "subscribe" button in the right-hand column.

Note the advice about recovering from the deaths at the end of the first post in that issue.

@crookedneighbor I totally did not just steal your words for that section. :)

**Comment by AmandaMock** [comment]
I'm confused now, I contacted cusotmer support and they had me reach out,
now I'm getting a notification that it's closed? What's the status of this?

**Comment by Alys** [comment]
Amanda, did you see a message from me at about the same time you got a
message that it was closed? That explains why I closed it. You should be
able to see it on github if you don't have the email. In brief, I closed it
because there's another issue for it already. But regardless, you can keep
commenting here if you want and we'll still see you messages and help you.

**Comment by AmandaMock** [comment]
I see both as closed which is why I'm confused. 

Here is a screenshot of the issue 
![habitdbl](https://cloud.githubusercontent.com/assets/8353055/6119886/bb734404-b083-11e4-8b02-e15d3e132f6e.png)

**Comment by Alys** [comment]
The original issue is still open, not closed. There should be a green
"open" tag near the top of the issue.

Thanks for the screenshot! That's helpful and interesting.

We still need some extra information though. Do you use Habitrpg on more
than one device? If so, are the time or timezone settings different between
them? Can you think of anything that changed three days ago, even if it
doesn't seem directly related?

**Comment by AmandaMock** [comment]
I sometimes log in on my mobile device and the timezones are the same. And
no, nothing recently changed.
