### ISSUE TITLE
Some dailies don't un-gray/un-check the next day

### ISSUE THREAD

**Issue by kalikokalikova** [HabitRPG/habitica#4658]
Hey guys, I'm using Chrome on a macbook pro running OS X 10.9.5. For the last four or five days, two of my dailies have not reset to their unchecked/non-gray state. Let me know if you need any more information from me to help.

Thanks!

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/4313 so I'll close this new issue as a duplicate. You can subscribe to notifications for the original issue in the right-hand column. Please see "What to do if you experience this bug often" in the first post on that issue.

**Comment by paglias** [comment]
@calico-g could you do me a favor and open the console (ctrl+shift+j) and report any error there?
