### ISSUE TITLE
Error processing string

### ISSUE THREAD

**Issue by preston-m-price** [HabitRPG/habitica#4659]
![string_error](https://cloud.githubusercontent.com/assets/5125809/6116095/5f4faa8a-b067-11e4-8687-d20474c0bfa4.png)

The 4 potions below the egg also show the same message when mousing over them

**Comment by paglias** [comment]
Can you reload the page and see if it's fixed?
Il 09/feb/2015 22:26 "preston-m-price" notifications@github.com ha
scritto:

**Comment by preston-m-price** [comment]
Works now, thanks!
