### ISSUE TITLE
Suggestion: login directly from home page

### ISSUE THREAD

**Issue by toebu** [HabitRPG/habitica#466]
When I want to log into Habit, I always first need to press on 'play' from the home page. This creates a new user that is never used and clogs up the database. I know that the stale users are regularly removed, but might it be worth to be able to login directly without first starting the application with a freshly created user?

**Comment by lefnire** [comment]
a wise suggestion. not super pressing (since as you said, we preen) but we'll do that

**Comment by mgopher** [comment]
Agreed, the extra click is a bit annoying, especially as I find if I close the browser without logging out at work, and then log in again at home, I sometimes lose my last few actions from the previous session (separate issue obviously, but my temporary fix means I am always logging in and out).

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
