### ISSUE TITLE
Sticky starter guilds to the top of the Guilds page

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4660]
Going through old notes, this one isn't important but was requested: Pin/sticky the starter guilds (Newbies, LFG, Archery, Aspiring Legends, Aspiring Coders, etc) to the top of the Guilds page. Challenges uses an ["official" flag](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/challenge.js#L12), might be be able to do the same for Guilds (maybe rename as `sticky`?)
##

**Comment by deilann** [comment]
I actually do think this is pretty important, specifically for Newbies and LFG.

It would also allow us to "feature" guilds that seem pretty cool but are low down on the list for the month of X to try and idk, help people realize they exist. The more guilds we get, the more some of them drown in obscurity.

**Comment by lemoness** [comment]
Agreed; I would love to have Newbies Guild and Party Wanted right at the
top of the page.

**Comment by librarianmage** [comment]
Is this still desired? If so, may I take a look?

**Comment by lemoness** [comment]
This should definitely be on-hold because the Guilds page is getting completely revamped.

**Comment by lemoness** [comment]
The Habitica Help Guild is already far at the top now, and the other sticky Guilds will be added in a future update with suggested Guilds, so I'm closing this ticket for now. A new one will be opened when the designs are ready!
