### ISSUE TITLE
Can't access email and forgot password

### ISSUE THREAD

**Issue by Somebuddy12** [HabitRPG/habitica#4662]
User ID: 774b4978-2535-4bc0-9977-8e5a4881ce69
My email has become inaccessible and I can't seem to remember my password on here. Would it be possible to change my email to hockeycatgirl@gmail.com ?
Thank you

**Comment by Alys** [comment]
We can do that. I'm about to send a separate email to your new address,
just to confirm that you really do own it. :) Sorry about that,  but it's
important for data security. Please reply when you get that email!

**Comment by Alys** [comment]
I've replaced your old email address with hockeycatgirl@gmail.com

I'm closing this now but if you still have trouble accessing your account, reply to this post and we'll reopen this issue and keep helping you.

(For the record, I did send a test email to hockeycatgirl@gmail.com, as I described above, and SomeBuddy replied as expected.)
