### ISSUE TITLE
Error processing string for Wolf Egg

### ISSUE THREAD

**Issue by AikidoJunky** [HabitRPG/habitica#4666]
When I last leveled up, I got this message:

You've unlocked the Drop System! Now when you complete tasks, you have a small chance of finding an item. You just found a Wolf Egg! Error processing string. Please report to http://github.com/HabitRPG/habitrpg

And when I mouse over the wolf egg in the Inventory screen I get:
Error processing string. Please report to http://github.com/HabitRPG/habitrpg

**Comment by crookedneighbor** [comment]
@AikidoJunky This issue has been fixed, please refresh your browser (and if necessary, clear your browser's cache) and check again. If it still persists, comment back and I'll re-open this issue.
