### ISSUE TITLE
Party leader left and a new one was never chosen

### ISSUE THREAD

**Issue by vegetalover168** [HabitRPG/habitica#4668]
I was the party leader and I left. Now no one has admin rights. It has been a couple of days. According to the wikia it should have automatically switched to a new leader. They would like it to be switched to a party member, but we don't know how. I do not have access to the party any more as I am in a new one.

Here is a screen shot of the party members. None of them have the blue highlight: http://screencast.com/t/Z3iBruFE

My ID: 0b2bf43b-391b-48af-a57f-8396c20dba98
Party ID: b0f6a355-f816-4afd-b693-7a54e5fd942b

I can't give computer details because it's not my party.

**Comment by Alys** [comment]
When the leader leaves a party without assigning a new leader, the most senior remaining party member is made leader. This did happen with your ex-party, however the most senior person was someone who had actually deleted their account at some time in the past, and a bug had prevented their account ID number from being removed from the list of party members. 

I've removed that ID and now the next most senior person (MotherflippingOak) is the leader. They have the ability to change the leader to be any other party member.

**Comment by vegetalover168** [comment]
Awesome, thank you so much.
