### ISSUE TITLE
overdue (non)Daily shows grey

### ISSUE THREAD

**Issue by Gumnos** [HabitRPG/habitica#4669]
If a daily is set to only happen on a given day of the week (say, Thursday), and you miss it, the task goes to grey making it look like it was just skipped, rather than going red or having some indicator that the task still needs to be checked off.  This means a grey task will ding you for health daily while being difficult to detect what is causing the issue.

**Comment by Alys** [comment]
Grey Dailies (Dailies that are not scheduled for the current day) never cause you to lose health, not even when you didn't tick them off on the days when they were due. You lose health for uncompleted Dailies only on the days when they are scheduled.

If you're seeing any behaviour that makes it look as if you're losing health from a Grey Daily, please give us details of what you're seeing.

**Comment by Gumnos** [comment]
@Alys I noticed my health dropping steadily so I pulled the history.csv of my data to see what's going on.  My "Daily" dusting task for Thursday has been dinging me (mostly) daily for one unit of health since I skipped it last week.  The corresponding excerpt of my history.csv for the task:

```
"Task Name","Task ID","Task Type","Date","Value"
"Dust","4e3ffb1a-4ea4-47ac-90a9-2847cd7a2ce0","daily","02-05-2015 16:21:55","0"
"Dust","4e3ffb1a-4ea4-47ac-90a9-2847cd7a2ce0","daily","02-06-2015 17:08:58","-1"
"Dust","4e3ffb1a-4ea4-47ac-90a9-2847cd7a2ce0","daily","02-08-2015 02:09:12","-1"
"Dust","4e3ffb1a-4ea4-47ac-90a9-2847cd7a2ce0","daily","02-10-2015 16:07:54","-1"
"Dust","4e3ffb1a-4ea4-47ac-90a9-2847cd7a2ce0","daily","02-11-2015 17:19:14","-1"
```

Strangely, there's a gap on 2015-02-07 and 2015-02-09

**Comment by deilann** [comment]
That doesn't mean it's dinging you for one point of health. That means its
value is -1 and as that only changed once, it should have only dealt damage
once.

**Comment by Alys** [comment]
@Gumnos you might be interested in the wiki's [Task Value](http://habitrpg.wikia.com/wiki/Task_Value) and [Data Export](http://habitrpg.wikia.com/wiki/Data_Export#How_to_Understand_the_Data) pages, and also the Data Display Tool (from habitrpg.com, go to the Data menu then select Data Display Tool). If you'd like to analyse your tasks in depth, then they might give you useful information.

The gap between 02-07 and 02-09 could be from a few reasons. In the Data Display Tool, go to Dailies History and click "show explanation" - it lists some of the reasons.
