### ISSUE TITLE
Avatar customization/Profile page flickers and closes.

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#467]
Click avatar. The avatar customization page appears. It stays visible for a second or so, flickers and then closes. 

If you click one of the customization options fast enough, it solves the problem.

**Comment by busterroni** [comment]
Not happening for me.

**Comment by wc8** [comment]
Hm…I reproduced this consecutively in three different browsers, Fluid, Safari and Chrome. 
Now, however, I am not always able to reproduce it. Sometimes the dialog stays open, sometimes it closes.

**Comment by lefnire** [comment]
I believe it. There's some fine dance between setupJavascripts and resetDom
happening in app/browser.coffee that's likely the culprit, i'll keep my eye
on this

**Comment by horusofoz** [comment]
@wc8 Is this still an issue?

**Comment by wc8** [comment]
No.
