### ISSUE TITLE
Change Links for Looking for Group

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4670]
We've decided to move the official Looking for Group page from the Archery on the Wiki to a Guild in order to make it easier to find and join a party. The Guild is here:

https://habitrpg.com/#/options/groups/guilds/f2db2a7f-13c5-454d-b3ee-ea1f5089e601

Now we need to go through and change all the Looking for Group links that were pointing to the Archery (such as on the Party page and in the Tavern) to point to this new Guild instead.

Is this an easy enough task for aspiring coders?

**Comment by Alys** [comment]
Yes, easy enough. The hardest part would be finding all the links - although that's very easy for someone who knows how to grep through the codebase, and learning how to do that effectively will be a valuable thing for a new coder. I'll advertise this in the Aspiring Coders guild.

**Comment by Alys** [comment]
Message posted to Aspiring Coder's guild:

"There's a good task for a new programmer: [Change Links for Looking for Group - Issue #4670](https://github.com/HabitRPG/habitrpg/issues/4670). This would give Tier 1 to a new contributor and would count towards Tier 2 for someone a bit more experienced. 

"NOTE that if you don't yet have a local install, I recommend not setting one up yet. The local install process will be simplified soon and it would probably be a better use of your time to wait for that.  There will be other simple programming jobs in the future."

**Comment by remmz0r** [comment]
Might take a look at this tomorrow!

**Comment by remmz0r** [comment]
Just a query, should I be working on stuff like this against the develop branch? Or the master branch? I couldn't get a master branch server to run... @Alys @lemoness

**Comment by paglias** [comment]
develop, we use it as our main branch. Master is several months behind and
not used
Il 17/feb/2015 14:35 "remmz0r" notifications@github.com ha scritto:

**Comment by remmz0r** [comment]
I went through this code and could only find 2 changes to be made... this doesn't sound right. Any advice?
