### ISSUE TITLE
Side bar doesn't completely pull down to shore health on iOS app

### ISSUE THREAD

**Issue by ooker777** [HabitRPG/habitica#4673]
Can't completely pull down. It always restrain like this. 

![](http://i.imgur.com/BwNcqb5.jpg)

**Comment by kangabell** [comment]
This screenshot illustrates this issue, I think (@ooker777 let me know if I'm misunderstanding). I am able to pull down to view the content at the top, but by default it is cut off.

![habitsidebar-ios](https://cloud.githubusercontent.com/assets/5122304/6314922/c6516b8c-b9be-11e4-9687-eaee8dddd76c.PNG)

**Comment by ooker777** [comment]
Yes, that's what I want to say.

**Comment by deilann** [comment]
ping @negue Have thoughts?

**Comment by negue** [comment]
No sorry :(, none, can't test / build without a mac/iphone.

**Comment by crookedneighbor** [comment]
Should be fixed in this PR: https://github.com/HabitRPG/habitrpg-mobile/pull/349

**Comment by crookedneighbor** [comment]
I'll be purchasing a developer's license in the next couple of weeks so I'll be able to test the build.

**Comment by pjay-io** [comment]
I'm pretty sure it's fixed because I removed the menu bar

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. You can install it at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if you have any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
