### ISSUE TITLE
New hair options not showing up

### ISSUE THREAD

**Issue by itsasooz** [HabitRPG/habitica#4674]
Just purchased the new hair options.  The site seems to have registered that I've purchased everything, but the options are not showing up, despite several reloads:
http://i.imgur.com/GMXvM8v.jpg

UID 312f9e64-7c17-40dc-b10c-3c03afc948a3
Using most recent version of Chrome, Windows 8.1

**Comment by crookedneighbor** [comment]
Weird, they're showing up for me:

![screen shot 2015-02-12 at 2 20 27 pm](https://cloud.githubusercontent.com/assets/2916945/6176185/55aca4c6-b2c2-11e4-949c-9b08684a4c80.png)

Can you try clearing your browser's cache and then logging out and logging back in?

**Comment by crookedneighbor** [comment]
Oh, you know what, @SabreCat is theorizing that it's a problem with the purple hair color specifically. Can you switch to a one of the default hair colors and just confirm whether the new styles are absent still?

**Comment by itsasooz** [comment]
Looks like the purple hair was indeed the issue.  Seems the new styles aren't an option with the Halloween colors. :/

ETA: Tanks for the help!

**Comment by crookedneighbor** [comment]
@itsasooz They will be! Hold fast!

**Comment by crookedneighbor** [comment]
Will be deployed shortly. Closed with: https://github.com/HabitRPG/habitrpg-shared/commit/36dc1b42aa0df3e1f90b232df5b0bba084407f1a

**Comment by crookedneighbor** [comment]
@itsasooz Should be available now! Let us know if it isn't.
