### ISSUE TITLE
Strength 20 000 and critical hit +40 000% - is this normal?

### ISSUE THREAD

**Issue by sirtonyx** [HabitRPG/habitica#4675]
can someone comment on this? all I did was cast multiple valorous presence spells and proceeded to tick off my to-do tasks, when I suddenly started getting progressively higher critical hit bonuses. those in turn also restored my mana and allowed me to cast even more valorous presence spells. when I finally ran out of finished to-do items to tick off, I ended the day with a strength of almost 20 000 and the last critical hit was +40 000%, which gave me 3100 XP for that task.

a screenshot from my last critical hit: https://www.dropbox.com/s/jbipt8wbmnb7p70/valorous.jpg?dl=0

and a screenshot from my stats: https://www.dropbox.com/s/pq5d7kldlwwasij/stats.jpg?dl=0

is this normal, a well known bug or did I just find a way to break the game mechanics for warrior class?

**Comment by lemoness** [comment]
This is a way to break the warrior class, unfortunately. The good news is
that it will be fixed soon! In the meantime, you can set your stats back
down by going to Settings > Site > Fix Character Values. Sorry for the
frustration!

**Comment by sirtonyx** [comment]
thank you for the answer! on a somewhat related note (players doing too much damage to bosses) - some players in our party are doing up to 3000 damage per day, so questing has become about who of them manages to hit the boss first, since even the toughest 2000 HP bosses fall from just one strike. any chance of getting 10 000+ bosses to fight?

**Comment by lemoness** [comment]
Not currently.... but Burst of Flames, the mage skill that leads to that
damage, is also being nerfed so that it will be more balanced. These fixes
are all part of a massive skill rebalancing effort which is almost done :)

**Comment by sirtonyx** [comment]
good to hear! right now our party has three mages doing seven ethereal surges per day, which recharges their mana and gives everyone else almost 2-3 times their max mana, so the biggest damage guys are actually warrios with their brutal smashes (level 100+ with 600-700 mana allows for quite a few devastating brutal smashes).

**Comment by Alys** [comment]
As @crookedneighbor explained, we are rebalancing the skills to stop this happening, so I'm closing this issue, but you can track the progress of the rebalancing project by going to https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382 and clicking the subscribe button.

In the meantime, if you need any help with issues arising from over-use of skills, you can post again here.
