### ISSUE TITLE
Save task by shortcut (while inside Description field)

### ISSUE THREAD

**Issue by JorisDebonnet** [HabitRPG/habitica#4677]
When in a task's title, you can easily save by pressing return. But that doesn't work when you're in the description since you can type newlines there. 

I would love to be able to press control-return, alt-return, or anything else in order to be able to save from within the description field! 

Alternatively (even better perhaps), add an option to require shift-return for newlines in the description box, so that a normal return also triggers a save (much like in Facebook messages). 

[edit: by 'description' I mean the "Extra Notes" field]
##

**Comment by TheHollidayInn** [comment]
I believe this happens because of the browser default handling of the return key inside a textfield versus a textarea. When in a textfield, the form will submit and not when in the textarea.

Implementing what you asked should be easy, but maybe we should have some input from others.

**Comment by librarianmage** [comment]
Is this still desired?

**Comment by JorisDebonnet** [comment]
Well, not by me, as I don't use HabitRPG anymore at the moment. I still think my report makes sense though, as control-return is a pretty widespread way to submit textareas in software :) (here on Github for example!)

**Comment by lemoness** [comment]
I'm not sure we want this right now, actually, so I'm closing it. We can always reconsider in the future and reopen it!
