### ISSUE TITLE
Valorous Presence Abuse

### ISSUE THREAD

**Issue by lurichan** [HabitRPG/habitica#4679]
Edit: Found how to reset my values, so now I can at least fix my own part of the issue. 

My roommate decided to cast enough Valorous Presence to fill the entire party screen with it and caused the whole party to experience the following issues: 
High Exp. and gold gain. 

Now, to most people this might sound like a good thing, but it's not. Imagine spending several months to work your way to lvl 42 just to have someone come along and mess that all up and suddenly pole vault you up to lvl 1459. You can't NOT do your dailies and loose your streak bonus, and when they callously say "well you can just use something to go back down to lvl one" they are basically saying your options are to just "Deal with it" or start over from the beginning, well that is just frustrating, rude, and downright demeaning to all of your prior accomplishments. 

Then he said he would do a bug report....well that didn't happen. So now I'm having to write this up since callously decided to do something that would affect the entire party without a care for anyone else's feelings on the matter, and doesn't seem to believe their IS a problem, when there obviously is. 

It seems that now that the 24 hour period has past (he was supposed to do a report after he got home from work, but chose not to), that the buff is no longer in affect, but the damage it caused is still apparent. Game balance is important, and now  my character is at an unrealistic lvl that doesn't reflect MY achievements whatsoever. It's vexing to say the least. 

User ID 63739f60-dc9d-4ccd-a3ba-c61049c0613e
Group ID 973492fc-012b-4f39-975b-e1c0470b70c8

Running on chrome, not that this particular issue would be browser related. ~_~

**Comment by crookedneighbor** [comment]
I don't suppose this is your party member's bug report: #4675 

Even if it isn't, please read through the comments, which explain that we are actively working on a skills rebalancing project so this kind of thing doesn't happen. 

As for what to do to fix it in the mean time, you can go to [the settings page](https://habitrpg.com/#/options/settings/settings) and choose the "Fix Character Values" button to change your level and gold back to where they should be.

**Comment by Alys** [comment]
As @crookedneighbor explained, we are rebalancing the skills to stop this happening, so I'm closing this issue, but you can track the progress of the rebalancing project by going to https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382 and clicking the subscribe button.

In the meantime, if you need any help with issues arising from over-use of skills, you can post again here.
