### ISSUE TITLE
[Suggestion] Doit.im Integration

### ISSUE THREAD

**Issue by ill66** [HabitRPG/habitica#468]
Great GTD-webservice & app - integration would be awesome!

**Comment by wizonesolutions** [comment]
They don't have an API currently, so it'd be tougher.

**Comment by ill66** [comment]
Oh, too bad :\
What about NirvanaHQ? I'm currently considering to switch....

**Comment by Pandoro** [comment]
Hmmmm, according to a quick search I did, there is no API open to teh public yet. 

https://twitter.com/nirvanahq/status/294465854677061632

So probably there is no real option to integrate either of both services you suggested. 

Do you have any other suggestions regarding possible GTD services you want to get integrated?

**Comment by ill66** [comment]
hemm... i'm not sure if i actually would want my habitRPG to be a full-fledged GTD-app^^
currently i work around the not-integration with a +/-habit "check a task" (and a daily: "no tasks [for today] left".
works quite well in fact.

what i'm awaiting most eagerly at the moment is a feature for habits/tasks "x times a week/month" in addition to "dailies" :)

**Comment by Pandoro** [comment]
Okay :) These are high up on trello, so I think they will come soon enough :) 

It seems that you are quite happy with the current situation then? Can we close this issue?

**Comment by ill66** [comment]
"Make it so" ;D

Thanks for your quick response and your overall great work!! <3

**Comment by Pandoro** [comment]
Yes sir! 

Thank you for the input :)

**Comment by ill66** [comment]
i'm no sir, but you're welcome ;D

**Comment by fro0m** [comment]
zendone has a syncronization with evernote nd google calendar,and i manually transfer todos from zendone2habitrpg.will be great if automatu this

**Comment by wc8** [comment]
If zendone syncs with google calendar and evernote, will integration with either of those meet your integration needs?

**Comment by fro0m** [comment]
zendone import new inbox items from evernote notebook and create events in g-l cal. That is todos doesn't exist in evenote.
