### ISSUE TITLE
implement castCancel() on page change for cancelling skills, gift cards (Valentines), purchasable buffs (snowball, spooky sparkles)

### ISSUE THREAD

**Issue by flutterbye** [HabitRPG/habitica#4681]
When I try to purchase a card, nothing happens except a small cross appears next to my mouse.  I then find that when I click on my tasks I get an 'invalid target' message.  I have to refresh the browser to click tasks again. 

_edit by admin:_

The issue here is that if you click on a skill or gift card or purchasable buff, and then change your mind about using that item and go to another page instead of clicking on a target, then the skill/card/buff selection remains and your mouse cursor shows that it's still active. 

The desired behaviour is for the skill/card/buff selection to be cancelled as soon as you navigate to a different page.

NB: You can already cancel a skill/card/buff selection by hitting the ESC key on your keyboard, so that code for cancelling it can probably be reused on page change.
##

**Comment by crookedneighbor** [comment]
@flutterbye the target for the valentines is yourself or a party member. Try that instead of going to the tasks page.

@SabreCat Looks like pressing the tasks link after clicking on a valentine but before choosing a person to give it to allows you to go to the tasks page, and the valentine is still active, giving the impression that you should be able to put it on a task like other spells on the task page. Should we write something so the card is cancelled if the user leaves the market?

**Comment by flutterbye** [comment]
hmmm so am i supposed to click on a party member, then the card is
purchased?  i expected it to work like a snowball

**Comment by SabreCat** [comment]
It may be a good idea to get some handling for that in general, so you
don't do the opposite either (go to Market with a task spell active). Can
we implement a castCancel() on page change?

**Comment by SabreCat** [comment]
flutterbye: Click the card, then the party member. It doesn't shut in your
inventory like a snowball - you buy and send in one step.

**Comment by SabreCat** [comment]
*sit in your inventory

**Comment by flutterbye** [comment]
ah ok I understand now, thank you!

**Comment by paglias** [comment]
I think this has been implemented (press ESC)

**Comment by SabreCat** [comment]
This suggestion is about having the ESC happen automatically when you change pages.

**Comment by Ozzystrasza** [comment]
Is this on hold because of the redesign?

**Comment by Alys** [comment]
Yes. The current undesirable behaviour might disappear completely with the
new design, and this issue isn't reported often to make it a high priority.

**Comment by lemoness** [comment]
Transformation items are handled differently now, so I'm closing this ticket.
