### ISSUE TITLE
Subscription screen does not look secure - makes people nervous

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4682]
One player reported this in the Newbies guild:

"My other question is how secure is subscribing... I'm feeling nervous about the way the screen looks. Is it actually a secure transaction? ... I guess because it's a pop-up that asks for your email and cc/csv code. It seems so casual, rather than being really formal like the paypal one. I don't see it saying anywhere that it's secure or the normal warm and fuzzies I would expect with a credit card request. It seems like there's normally some message that says the method of encryption or etc... one thing it doesn't ask is for my name as appears on credit card. Wouldn't it need to know that?"
##

**Comment by Alys** [comment]
Also: "one thing it doesn't ask is for my name as appears on credit card. Wouldn't it need to know that?"

**Comment by lemoness** [comment]
Hm, good to know. Pinging @anitaycheng

**Comment by Alys** [comment]
Screenshots from an account that has never subscribed:

Screen you see when you click on the toolbar's gem:
![screen shot 2015-02-14 at 8 21 22 am](https://cloud.githubusercontent.com/assets/1495809/6196290/d2ecb334-b422-11e4-9ff7-0142e74d157a.png)

Buying gems:
![screen shot 2015-02-14 at 8 21 35 am](https://cloud.githubusercontent.com/assets/1495809/6196291/d2f611f4-b422-11e4-8b11-6cd7107e8c1d.png)

Buying subscription:
![screen shot 2015-02-14 at 8 22 04 am](https://cloud.githubusercontent.com/assets/1495809/6196292/d2feb322-b422-11e4-90d8-9f1a8aec4e22.png)

Screen you see when you click on the subscribe button (the "card" button's popup is the same as above):
![screen shot 2015-02-14 at 8 25 08 am](https://cloud.githubusercontent.com/assets/1495809/6196331/3cfe60a6-b423-11e4-8f75-5ebfdb771a93.png)

**Comment by AnitaYCheng** [comment]
I think the subscription info page is too "Boostrappy." We should use Paypal's brand style button, as well as some credit card icons to show that we're officially associated with them. Just having the two buttons there (and in Bootstrap's default style) makes us look like a fly-by-night operation. Having a space where they put their billing name and zip code would also be a good idea for that as well. It's what people are used to seeing when they use their credit card remotely.

Association with other well-known, legitimate companies helps people feel comfortable giving their financial information online. To that end, changing the "Card" text to "Pay by credit card with Stripe" would give them much more information about what we're using. Stripe is a very legitimate service that handles credit card transactions, but it isn't obvious at all that we're using them.

**Comment by Alys** [comment]
Regarding the zip code: Is that really a common thing? It's not here in Australia. My thoughts when I see a request for zip code are "Why the heck do you need to know where I live? That's private! Do you want to do targeted marketing based on my location?"

**Comment by veeeeeee** [comment]
I wonder if it might be useful to provide a link at point of sale to an FAQ on Stripe, either our FAQ or theirs? I think market penetration of these companies is not as thorough as we tech-immersed folks might imagine (thinking of the time I went to a wedding and other guests were THOROUGHLY weirded out by the idea of Airbnb--which is a much more consumer focused brand)

**Comment by Alys** [comment]
@veeeeeee Agreed. I don't think I'd heard of Stripe before I saw it on HabitRPG.

**Comment by AnitaYCheng** [comment]
@veeeeeee An FAQ for Stripe wouldn't hurt, although I'm also guessing that people who'd be using HabitRPG are more tech-savvy than the average person. But if we wanted to go into more markets, we can't bet on that.

@Alys, companies often ask for your entire billing address, even when it's a virtual item! We can at least try billing name first, and see how it goes.

**Comment by lemoness** [comment]
I'd say skip the zip code, since I always hate providing it, but definitely
include Billing Name.

**Comment by deilann** [comment]
Because HabitRPG is an online retailer, I would not get rid of AVS. The
billing zip is _not_ something you can gather from a physically stolen card
-- unlike billing name and CVC. Asking the entire billing address is
overkill (and besides, only parts of it are used for AVS) but we should do
something to ensure that the person using the card is the card holder.

**Comment by makosblade** [comment]
Just to toss my 2¢:
@veeeeeee Stripe FAQ seems like the most important first step since it's really more a problem of users not being familiar with Stripe as a secure, reputable credit card handler.

Adding the billing name seems fine to me but what is actually being done with that information?

Maybe even adding an icon like the SSL secured icon would suffice.

**Comment by devmage** [comment]
Another payment platform to consider would be Braintree, which can accept PayPal as well (and is itself, in fact, a PayPal product). Among other things, they offer a [drop-in payment UI](https://www.braintreepayments.com/features/drop-in) as part of their v.zero SDK.

_Disclaimer: PayPal are my corporate overlords._

**Comment by khipkin** [comment]
These ["Powered by Stripe" Badges](https://stripe.com/about/resources) seem like a good place to start, if you guys continue to use Stripe!  I know I always look for some kind of "Secured by..." or "Protected by..." badge when I purchase something online.

Ex: ![Dark version of badge](https://stripe.com/img/about/logos/badge/small/dark.png) ![Styled, bigger version of badge](https://stripe.com/img/about/logos/badge/styled.png) ![Dark outline version of badge](https://stripe.com/img/about/logos/badge/small/dark_alt.png)

**Comment by librarianmage** [comment]
@khipkin the "Powered by Stripe" button could link to a FAQ

**Comment by khipkin** [comment]
Suggestion: [entry level coding] or [medium level coding]

**Comment by Alys** [comment]
Actually I'm going to put this on hold. The credit card button has been improved since this was logged ("Credit Card (using Stripe)" now) and redesigning the screen to make it look more professional is best done during the website improvement project, which this issue is already tagged for. @khipkin Thanks for drawing our attention to it!

**Comment by lemoness** [comment]
A large redesign for the subscription page is still in the works, so I am closing this ticket for now.
