### ISSUE TITLE
Missing checklist

### ISSUE THREAD

**Issue by benjijames618** [HabitRPG/habitica#4684]
One of my checklists for one of my tasks is missing, unless I pull it up in the edit menu. I have tried retyping my checklist several times for the one task, and it still does not appear once I submit the change. There are currently two tasks I have with checklists, and one of them is missing. This has been a problem for several weeks now.

**Comment by crookedneighbor** [comment]
@benjijames618 That's very strange.

Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

Would you also post a screenshot of your task, both in normal view and in edit view? You will not be able to attach it via en email, you'll have to log into Github and drag it onto your comment.

**Comment by deilann** [comment]
Is it collapsed? You can collapse a checklist by clicking the X/X (like
3/4), which hides it until you click it again.

**Comment by crookedneighbor** [comment]
@deilann Good tip, I didn't realize that was something you could do with checklists. I bet that's it :+1: 

@benjijames618 Can you confirm that for us?

**Comment by benjijames618** [comment]
User ID: d760208c-e650-442d-a802-0cb2f120f3a7

![screen shot 2015-02-15 at 4 07 07 pm](https://cloud.githubusercontent.com/assets/11006051/6205012/d802e824-b52c-11e4-8a49-3cdcc26451e2.png)

![screen shot 2015-02-15 at 4 07 11 pm](https://cloud.githubusercontent.com/assets/11006051/6205015/e2d7123e-b52c-11e4-8ed4-6c1431a8efa6.png)

**Comment by deilann** [comment]
Yes, click on the 0/2. Your checklist is collapsed.

**Comment by benjijames618** [comment]
Thank you @deilann the problem is now resolved.
