### ISSUE TITLE
Burst of flames exp boost does not cause level up when exp. reaches target.

### ISSUE THREAD

**Issue by preston-m-price** [HabitRPG/habitica#4685]
Have not had an opportunity to try to reproduce this issue yet. But here is how I caused it:
Get enough experience to be near leveling up.
Cast Burst of Flames on a red task and get an experience bonus.
Experience will go up past the target for causing a level up (in my case I now have 291/280 exp).
Thanks!

![exp bug](https://cloud.githubusercontent.com/assets/5125809/6200377/87c20d36-b432-11e4-9bf8-95702ba9ae07.png)

Update:
Completing another todo triggered the level up.

**Comment by crookedneighbor** [comment]
@preston-m-price the issue has been reported here: #2143 

I'm going to close this ticket, but you can track the progress of the bug by going to issue #2143 and clicking the subscribe button.
