### ISSUE TITLE
Cannot Clear "Holidary Card" Notif

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4686]
The holiday card notifications do not have a button to clear them, unlike guild notifications. I understand why some notifs don't have this option, such as party invites, but I see no reason why I couldn't ignore holiday card notifs.

This is especially concerning to me because I actually have quite a few valentine's cards -- some of which are from last year. I don't want to get rid of all of them, which is the only way to clear the notif. I'd like them to be able to sit in my inventory, like they did before.

**Comment by crookedneighbor** [comment]
Ping @SabreCat

**Comment by SabreCat** [comment]
Mm, good point. I'll see what I can do! At worst, I can disable the notification after the event ends.

**Comment by deilann** [comment]
Thank you! :)
