### ISSUE TITLE
Challenge creator cannot be easily contacted

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4687]
Currently, to contact the creator of a challenge (a semi-frequent request in the Tavern), you need to be able to find a guild in which they have posted a message so that you can see their profile to access the private message function.

Suggestion: Make the challenge creator's name a link to their profile. Even if they have opted out of PMs, you'd still be able to see their last logged in date, which would give you some idea of whether they are active or not (and then don't both joining a challenge if they haven't logged in for weeks).

Can anyone think of any disadvantages?

Would we want to make it optional to have their name as a link (with the default option probably being yes)?

If they have opted out of PMs (or even if they haven't), would we want to provide an optional field in the challenge creation screen where they could write alternative ways of contacting them? (E.g., "For questions about this challenge, post a message in Xyz guild.")

Any better solutions?

**Comment by TheHollidayInn** [comment]
I think the idea of linking to their profile is great. I don't have much input, but I believe this could be solved easily. 

My next thought would be that if we link directly to the challenge creator's profile, and they were unaware of the opt out of pm option, will there be many complaints from challenge creators?

**Comment by Alys** [comment]
I'm sorry - I never replied to your question about complaints from the creators! It should be fixed by https://github.com/HabitRPG/habitrpg/issues/4848 (move the Opt Out option to a more obvious spot) and we've already had one person interested in working on that.

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/4849
