### ISSUE TITLE
"Swagger UI" (https://habitrpg.com/static/api) doesn't work anymore (shows only text)

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#4688]
Copy-'n'-pasting from the Tavern yet again:

Me:
"What happened to the [Swagger UI](https://habitrpg.com/static/api)? (Did something change, or is it just my computer blocking stuff?) I get the text but I don't see the "get/put" part of the site anymore. (Current problem is, I want to send a participant of a challenge I created a message, but can't find a way to do so without finding them somewhere else than as participant of the challenge. So I wanted to try to find out the User ID and then find a way to do it with that.)"

@Alys :
"Darnit! Recent site changes must have broken it. Would you be able to log an issue on github? You won't need to include much detail.
If you were able to find their UUID, I think you would be able to send a message using the swagger interface, if swagger were working...."

**Comment by crookedneighbor** [comment]
Here's the Chrome console from the api page:

```
api:1 GET https://habitrpg.com/bower_components/swagger-ui/dist/lib/handlebars-1.0.0.js 
api:1 GET https://habitrpg.com/bower_components/swagger-ui/dist/lib/swagger.js 
swagger-ui.js:390 Uncaught TypeError: undefined is not a function
swagger-ui.js:253 Uncaught TypeError: undefined is not a function
api:1 GET https://habitrpg.com/bower_components/swagger-ui/dist/lib/underscore-min.map 404 (Not Found)
```

**Comment by crookedneighbor** [comment]
We're not pinning a specific version of swagger-ui on this line: https://github.com/HabitRPG/habitrpg/blob/develop/bower.json#L36

So, I think the repo updated with some breaking changes, and we just didn't notice.

**Comment by Alys** [comment]
This is working for me now. Not sure when it was fixed but I'm closing this now. @habitrpguser We can reopen this if it's still not working for you or if you find any problems with it!

**Comment by habitrpguser** [comment]
Umm, the exact same thing (Swagger UI showing only text) is happening again now. (No idea if it has the same cause though.) Should I open a new issue or will this one be reopened?

**Comment by crookedneighbor** [comment]
Output from Chrome console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://habitrpg.com/bower_components/swagger-ui/dist/lib/handlebars-1.0.0.js Failed to load resource: the server responded with a status of 404 (Not Found)
https://habitrpg.com/bower_components/swagger-ui/dist/lib/swagger.js Failed to load resource: the server responded with a status of 404 (Not Found)
swagger-ui.js:9 Uncaught TypeError: Handlebars.template is not a function
api:2 Uncaught ReferenceError: SwaggerUi is not defined
```

**Comment by crookedneighbor** [comment]
It's because a new version of swagger ui has been released. https://github.com/swagger-api/swagger-ui/releases

It was a breaking change, so I'm going to update our implimenation and then pin us to a specific release number

**Comment by crookedneighbor** [comment]
New plan. Upgrading is going to take a non-trivial amount of work. Pinning to the previous version we were using for now.

**Comment by habitrpguser** [comment]
@crookedneighbor Thanks for the quick fix! Page looks normal again and will probably work. (Will try now.)
