### ISSUE TITLE
Buy button does not do anything when purchasing Gems

### ISSUE THREAD

**Issue by blendax78** [HabitRPG/habitica#4689]
Hello, in the Android App, I'm attempting to purchase Gems.  When I go to Menu -> Purchase Gems and then click on the "Buy" button. Nothing happens.  It darkens slightly to show my keypress, but that's it.
Nexus 4 - Android 5.0.1

**Comment by Alys** [comment]
Confirmed on Android. App version 0.0.47.

**Comment by crookedneighbor** [comment]
Ping @negue

**Comment by leelmx** [comment]
This is happening to me as well on Android. I just got the app yesterday. Thanks!

**Comment by deilann** [comment]
This appears to be fixed on the latest version of the app.
