### ISSUE TITLE
new task plus (+) buttons doesn't give feedback when no text has been entered

### ISSUE THREAD

**Issue by ChadBou** [HabitRPG/habitica#4692]

**Comment by ChadBou** [comment]
User ID: 25964707-7853-4a95-b629-716d598e66ea
Windows 8.1
Chrome 40

I can't add tasks or anything with a + button. I just joined yesterday, was able to add a few tasks, but then after a few minutes all + buttons to add Habits, To-Dos, Rewards stopped working. They all respond to roll-over (turn darker grey), but there is no result from clicking at all. Occasionally I get a feedback graphic on depression (darker grey), but no other result. I'm able to delete tasks and change tabs, so the interface is at least partially responsive. I have closed and opened my HRPG account dozens of times to check for a fix. No result. 

I'm using Chrome, most recent version, on a Windows 8 desktop machine. I uninstalled, downloaded, and re-installed Chrome in hopes that it would help, but no result. I have also tried with Firefox, but no result and same issue. 

Here's some text from my console log after refreshing the page: 

 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
ads?client=ca-pub-3242350243827794&format=234x60&output=html&h=60&slotname=9529624576&adk=396032316…:1 GET https://encrypted-tbn3.gstatic.com/favicon?q=tbn:ANd9GcT_AcsCEjiPU5e7dIuWoyKAz1jCkCQL_ZqyHE8qcudPOTAh5ZmzNjpRRQYzW9RsZJdqZ21tGm884A 404 (OK)
ads?client=ca-pub-3242350243827794&format=234x60&output=html&h=60&slotname=9529624576&adk=396032316…:1 GET https://encrypted-tbn0.gstatic.com/favicon?q=tbn:ANd9GcTL7H70v7UiFFbrCvcx3l_cUy1VNNuB33vvs6tKBeroxFRJKX2LHeTT-6dqjs2Sd1VWeT0HHcRSS4lZ 404 (Not Found)
ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1 Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by Alys** [comment]
Are you typing text into the new task box before you click on the + button?

**Comment by ChadBou** [comment]
Holy heck, no I wasn't! I couldn't find an issue similar to mine because I have been uniquely stupid! Thanks very much for the help. Issue resolved!

**Comment by Alys** [comment]
Heh heh. :)  But don't feel bad - you aren't stupid. We've had this question asked before in the Tavern and we should have done something about it then. It's clearly a usability issue on the site - you shouldn't have had to go through that pain. I'm leaving this open and renaming it so we'll fix it this time! Sorry about the trouble. :(

**Comment by crookedneighbor** [comment]
@ChadBou No worries, your ticket has me thinking though, should we program in some kind of error notification if someone tries to make a task without filling in the title?

**Comment by ChadBou** [comment]
Maybe so. If the field border changed to red or maybe if it threw a popup error for the empty field I might have figured it out. But again, I blame myself on this one.

**Comment by ChadBou** [comment]
Super helpful and friendly responses, by the way. Confidence is totally restored in this app and I look forward to using it lots.

**Comment by TheHollidayInn** [comment]
Hello,

I'm taking a look into this issue. I'm not too familiar with AngularJS validation patterns.

Would the recommended way to solve this issue be to add a div with some alert class and use the ng-show directive on that div? 

Here is a reference I am using: http://product.moveline.com/angular-validation-part-1-form-basics.html . Under the "Do you validate?" heading is an example of what I am thinking.

Thanks!

**Comment by ChadBou** [comment]
Wow, so cool to see that this complaint became a whole thing. Go coders, go!

**Comment by TheHollidayInn** [comment]
I believe this issue is fixed, but I didn't add the "fixes" command. Can someone confirm and close?

**Comment by Alys** [comment]
Fixed it is, thank you @TheHollidayInn!
