### ISSUE TITLE
List bullets for Extra Notes in tasks, habits, todos are place outside the popup bubble

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4693]
The list bullets should be inside the popup bubble which show Extra Notes. Currently they sit on the border. The screenshot makes it clearer.

![habitrpg list](https://cloud.githubusercontent.com/assets/878118/6219624/2802d638-b652-11e4-8bb8-5823ed516bc1.png)

**Comment by crookedneighbor** [comment]
Fixed. Will be live on the next deploy. Until then, here's a preview: 
![screen shot 2015-02-16 at 4 04 44 pm](https://cloud.githubusercontent.com/assets/2916945/6219986/2a77ad8c-b5f6-11e4-82b4-262bcc0b49cf.png)

**Comment by ghost** [comment]
Will be looking forward to it.
