### ISSUE TITLE
Small alignment issue for task text

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4694]
If the first word for a task is too long compared to the space required for small icons on the right, then it starts below the small icons on the right. I don't know what an ideal solution would be. But I usually expect the task text to start at the top left.

Here _Exercise_ is positioned below the icons on the right. I would expect it to be positioned on the same line as the icons on the right, and maybe you could move the icons on the right to the bottom.
![habitrpg align](https://cloud.githubusercontent.com/assets/878118/6219845/c9f72dac-b654-11e4-94a4-df24fa061452.png)

My solution:
Here asterisks represent the icons that usually come on the top right

```
 ---------
|Text     |
|Text     |
|    * * *|
 ---------
```

**Comment by crookedneighbor** [comment]
I'd like to hide the "push to top", "edit", "trash", and "graph" icons until mouseover. That could significantly free up space. We could also put all those different icons into a submenu, maybe opened by pressing a gear icon?

**Comment by Alys** [comment]
I like the idea of hide + show-on-hover (and it was discussed elsewhere with a general intention of doing that). If we can get the hide/show working well, then there'd be no need for a submenu. I use the icons a lot and would rather not have an extra click. The hide/show should probably show the icons under the task text so that you don't get the visual annoyance of watching the text jump down when you hover.

**Comment by Alys** [comment]
No, I'm wrong, there were concerns about hover: https://github.com/HabitRPG/habitrpg/issues/3921

**Comment by Alys** [comment]
But then there were less concerns later in the thread (except for mobile browsers). And look, we have a PR: https://github.com/HabitRPG/habitrpg/pull/3923

**Comment by Alys** [comment]
@richcocoa I've copied a summary of your suggestion to that other issue, and I recommend we continue the discussion there to keep it all in one place.

**Comment by ghost** [comment]
@Alys can you please close this issue then, if the discussion is being tracked on #3921

**Comment by Alys** [comment]
@richcocoa You're welcome to join the discussion in https://github.com/HabitRPG/habitrpg/issues/3921 if you wish, or you can subscribe to notifications with the button in the right-hand column of that issue. @crookedneighbor has done a mockup of your idea with icons at the bottom, and I like the way it looks! Thank you for suggesting this and prompting us to talk about it! I'm closing this now but we'll keep discussing it elsewhere.

**Comment by Alys** [comment]
@richcocoa Heh heh. We were thinking as one. :) Note that in github you're always able to close issues that you created yourself.
