### ISSUE TITLE
New Survey Badge

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4695]
We have a brand-new HabitRPG survey! Hooray! It's here: https://www.surveymonkey.com/s/62RXRF3

We'd like to incentivize users to fill it out the same way we did last time: with the Helped Habit Grow badge. However, before we could do that, we'd have to do three things:
1. Make the "Helped Habit Grow" badge stackable OR create a new badge. I'd rather it be stackable if we can manage it.
2. Swap the link in the text to point to this new survey.
3. Find a way to add the badge to the accounts of users who fill out the survey. (@lefnire how did we do this last time?)

The sooner we can do this, the better - some of these questions will help us focus our efforts going forwards.

**Comment by SabreCat** [comment]
Points 1 and 2 are easy. (We will have a vestigial badge in the system similar to what happened with the Valentine's Day cards, but that's not a big deal.) The tricky part is number 3. If the survey includes a question that asks for the participant's user ID, then we can add the achievement manually, at least. @lefnire, was that how the prior survey was handled? I do seem to recall a bit of delay between accomplishing the survey and getting the badge.

**Comment by lefnire** [comment]
We exported the results to csv, then we took the rows and concat'd a string as `["uuid1","uuid2",...]` to console, which allowed us to copy/paste that in as the query string (`db.users.update({_id: {$in: PASTE }}, {...}, {multi:1})`). The script is [here](https://github.com/HabitRPG/habitrpg/blob/develop/migrations/csvexport.py) (python?? lol, wasn't me) if you need a starting poing

**Comment by lefnire** [comment]
let me know when you get to this point @SabreCat i'll help you out

**Comment by SabreCat** [comment]
I believe this was accomplished long ago. Closing.
