### ISSUE TITLE
Original User Badge

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4696]
The "Original User" achievement does not display a badge, but one was made a long time ago by zoebeagle and apparently never added. It's here:

![original_user_badge_by_zoebeagle](https://cloud.githubusercontent.com/assets/3494081/6220875/807f99b6-b5f0-11e4-8dc6-1f47e10ae27d.png)

**Comment by lemoness** [comment]
Would this be easy enough for an Aspiring Coder?

**Comment by SabreCat** [comment]
Yes!

**Comment by crookedneighbor** [comment]
I added and compiled the sprite, `.achievement-alpha` will be the class used.

Looks like the veteran and the original user achievement are combined right now. [Here are the lines that would need to be changed](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/achievements.jade#L128-L135)

**Comment by remmz0r** [comment]
Do you want it to display on the same line as the other badge? Or on a new row(ie under a new hr)

**Comment by lemoness** [comment]
I think on the next row beneath it, like all the other badges.

**Comment by remmz0r** [comment]
Thanks. I think I have the code fixed just gonna push it to my branch in a moment

**Comment by remmz0r** [comment]
Well I think I did the pull request properly... lets see !

Edit: hmm nope, I'm setting up vagrant now to test

**Comment by remmz0r** [comment]
Hmm nope, setting up Vagrant now to test locally

**Comment by remmz0r** [comment]
How do I make a user an 'originalUser' ? Should it automatically be an original user on my develop install?

**Comment by Alys** [comment]
In the document for that user in the mongodb `users` collection, set `achievements.originalUser` to true.

Let us know if you're not sure how.

**Comment by Alys** [comment]
Let us know if you're not sure how.

**Comment by remmz0r** [comment]
@lemoness : should I be pulling this from develop branch?

**Comment by remmz0r** [comment]
@lemoness my latest update works on the develop branch I pulled, screenshot attached
![origuser](https://cloud.githubusercontent.com/assets/11038374/6223923/ec411932-b6ad-11e4-9ddd-d28510d21376.png)

**Comment by remmz0r** [comment]
@Alys  for some reason it failed to build but it ran fine when I launched the server using grunt run:dev

**Comment by Alys** [comment]
@remmz0r Can you add a link to your PR(s) from this issue please?

**Comment by Alys** [comment]
@remmz0r Never mind, I found it. 

If you add "fixes #4696" (where that's the issue number) in the body or title of your PR, there'll be automatic linking between the two records, and the Issue will become closed automatically if the PR is merged.

**Comment by remmz0r** [comment]
Ok thanks @Alys  -- appreciate the help. Have done so!

**Comment by crookedneighbor** [comment]
@Alys I think it needs to be "closes #issuenumber" for it to work.

**Comment by crookedneighbor** [comment]
Never mind, fixes works too. I'm just sleep deprived.

**Comment by deilann** [comment]
There are actually quite a few that work...

**Comment by crookedneighbor** [comment]
@deilann I know. I don't know what I was thinking.
