### ISSUE TITLE
Infinite gold

### ISSUE THREAD

**Issue by JleruOHeP** [HabitRPG/habitica#47]
You can set negative cast for reward and gain as much gold as you want

**Comment by lefnire** [comment]
Lol! Don't you people know the Konami code? Jk, i'll fix this thanks.

**Comment by hookang** [comment]
When you get all that wonderful negative gold... and buy everything...

There's a blank for armor and weapons above gold level.

That was fun...

**Comment by Andrew565** [comment]
If this is still an open issue I'll tackle it tomorrow.

**Comment by hookang** [comment]
It is. All I think that needs to be done is to remove being able to add a negative number as a reward.

**Comment by lefnire** [comment]
@Andrew565 check out https://github.com/chriso/node-validator while you're in there.

**Comment by dbueller** [comment]
We could use:

money -= Math.abs(taskObj.value)

in the scoring.coffee file to have the reward always cost gold until we work out the validation.

Edit:  OK. I think I uploaded the files correctly.  That should fix it and stop any more free gold from getting out.

**Comment by Pandoro** [comment]
I hope @lefnire can get a look at this. The question is though, will this also work if we put in "asdfs" ?

So far this caused the GP counter to become NaN and this means buy whatever you like until a day reset ;) 

It would also be nice to have something like this while setting the value. I don't know about the syntax but something like:

money = Math.abs(taskObj.value)
if(money ==NaN){
 //display some error
}else{
 // create task
}

**Comment by dbueller** [comment]
It reverts back to the unedited value if a non-number is entered and gives a tooltip with an error when a negative value is entered.

**Comment by Pandoro** [comment]
Is this included in your pull request :) ?

**Comment by dbueller** [comment]
Yes.  My update should fix it.

**Comment by Pandoro** [comment]
Cool :) Well then I hope Tyler can take a look at your pull request soon :)
Although I must say the negative gold is Very useful when testing on the
test server ;)

**Comment by lefnire** [comment]
merged, will go out with the next push. @Pandoro, once I get some proper accessControl in I'll build some debug tools for us - maybe activated by the Konami Code ;)

**Comment by tjwds** [comment]
Checking and unchecking a daily will produce infinite gold, albeit in small increments.

**Comment by lcnv** [comment]
Adding to what tjwds said, you can also keep all the item drops from clicking and unclicking the dailies. Includes pets, food, crits, and hatching potions. (Crits meaning that critical hits will keep the difference in exp too.)

**Comment by deilann** [comment]
That's not an issue wrt drops, considering there's a drop cap. I'm also not
really concerned about this simply because well, if people are that into
button clicking and missing the point of Habit... they should enjoy their
gold? It would be a lot easier to go into Fix Character Values.
