### ISSUE TITLE
Conflicting Prices

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#470]
I know this isn't really a bug, it's more of something that doesn't make sense: A leather helmet and a wooden shield both reduce damage by 2%, however a leather helmet costs 15 gold and a wooden shield costs 20 gold. I'm not sure if this was done on purpose or not, just thought I'd let you guys know.

**Comment by StanLindsey** [comment]
Thanks, the shield is supposed to do slightly more defense than the shield (because you can block with a shield in RL). It was supposed to be 3% if I recall so I've changed it for the next push. Thanks =D
