### ISSUE TITLE
Chrome Console Error on Party Page - TypeError: Cannot read property 'chat' of undefined

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4705]
Not sure what's causing it, but it doesn't seem to prevent chat from loading.

```
TypeError: Cannot read property 'chat' of undefined
    at Object.a.chatChanged [as fn] (app-e77ebc49.js:28)
    at j.$digest (app-e77ebc49.js:7)
    at j.$apply (app-e77ebc49.js:7)
    at HTMLAnchorElement.<anonymous> (app-e77ebc49.js:8)
    at HTMLAnchorElement.n.event.dispatch (app-e77ebc49.js:2)
    at HTMLAnchorElement.r.handle (app-e77ebc49.js:2)
    at HTMLAnchorElement.nrWrapper ((index):1)
```

**Comment by Alys** [comment]
If each group page load in details for all groups that the user is part of (I don't know if it does), then it could be related to the "undefined" group being in some of the users' data. Ref https://github.com/HabitRPG/habitrpg/pull/3936. Now that I have access to run that migration script myself, I really should get on to doing that. It MIGHT fix this problem, but that's mostly a wild guess at this stage.

**Comment by Alys** [comment]
I ran the migration script mentioned in my previous comment and the notification icon is now going grey as it should.

Since then, I haven't noticed the `Cannot read property 'chat' of undefined` error, but I don't know how consistently it had been appearing.

If anyone still sees that error, please post here and include the full error message.

**Comment by TheHollidayInn** [comment]
```
TypeError: Cannot read property 'chat' of undefined
at Object.$scope.chatChanged [as fn] (groupsCtrl.js:215)
at Scope.$digest (angular.js:14226)
at Scope.$apply (angular.js:14489)
at angular.js:16215
at completeOutstandingRequest (angular.js:4902)
at angular.js:5282
```

Every time I access a guild page I see the error above. I do not see the error on my party page though.

**Comment by Alys** [comment]
related: https://github.com/HabitRPG/habitrpg/issues/4293

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/commit/522181890e3ce068b518029f1590a9421fd490bd
