### ISSUE TITLE
Planned To-dos tab doesnt work at all

### ISSUE THREAD

**Issue by Sapsality** [HabitRPG/habitica#4710]
Hi there
I haven't been using habitrpg for a while and yesterday stumbled upon this new feature.
Tried to check it out, but everything i tried to post on planned to-dos (or mb postponed, i'm not currently using eng version) ended up in active to-dos tab.

Is there anything i could do to make it work?
This thing looks quite useful to me and I'd like to be using it A LOT.

**Comment by Alys** [comment]
I'm assuming you mean the To-Dos tab that's in the middle. In the English version it's called "Dated". It's designed to show all uncompleted To-Dos that have been assigned a date. When you create a To-Do and then edit it to give it a date, it will always appear in the Dated tab (and also in the Active tab).

This probably indicates that the translation for your language could be improved slightly. Could you please tell us what language it is? And do you have a suggestion for a name for the tab that would make its meaning more obvious to you?

**Comment by Sapsality** [comment]
Oh, I get it know, T.Hanks.

My language is russian, and in my version of habbitrpg this tab is named "planned tasks", and unfortunately there's no better way to translate it so it would take less than 4 or even 5 lines.

You know, it would be so much better if to-dos that go to "dated" tab would disappear from the list containing current (active) to-dos. So that people could only see tasks they're about to perform today.

And when the time comes "dated" tasks would show up within current (active) to-dos.
It would make using habitrpg much more pleasant for me, because when I look at this huge list of to-dos (most of them are dated), I get super frustrated.
And it really takes up a lot of working memory (in human mind it's like RAM for computers) just to look at this list and to see lots of things you dont need to see at the moment.

**Comment by crookedneighbor** [comment]
I would recommend trying out the tag system. That can be a good way of organizing your tasks into workable bunches.

**Comment by Sapsality** [comment]
Ths for the advice. I did what you said and it worked miracles for my tasks.
My hero!
