### ISSUE TITLE
Disable Dailies deduction if last deducted within ~24hr

### ISSUE THREAD

**Issue by AnmAtAnm** [HabitRPG/habitica#4711]
This edge issue is for the edge case where someone has just set up a new daily deduction time. If they move from the default midnight to, say... 3am, they may looking at a double deduction if they perform the change in that time window between 12am and 3am.

Granted, minor issue, since it is a rare edge case, and the user is in complete control... if they have the forethought to make the change at the right time.

**Comment by deilann** [comment]
Don't we already check for this? I think it's not 100% accurate, but I thought we check to see if the last cron was 24 hours ago or more.

 @lefnire @SabreCat @crookedneighbor

**Comment by Alys** [comment]
This is the code where cron checks how far back it was run: https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1444 
and it refers to this daysSince function: https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L70
and this startOfDay function:
https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L58

The latter function uses dayStart (the Custom Day Start time) so maybe things go wrong there when the time is changed. It might need someone to work through the arithmetic for a few examples.

**Comment by peterjcarroll** [comment]
I was affected by this today. I wasn't thinking about it when I set the cron time from 3am to 5am, and did so after 3am. I logged in today at 6pm and got hit hard by the quest boss my party currently has and all my streaks are broken. It's not a big deal to me but I just wanted to make you guys aware that this does happen.

**Comment by Alys** [comment]
This is being discussed in https://github.com/HabitRPG/habitrpg/issues/4488#issuecomment-103954722 so I'm closing this issue now. If you'd like to follow the discussion, there's a subscribe button on the right of that other issue.
