### ISSUE TITLE
Weird username in Challenges

### ISSUE THREAD

**Issue by ooker777** [HabitRPG/habitica#4718]
Today I find a super long name in the [Arrive On Time](https://habitrpg.com/#/options/groups/challenges/813809ec-547a-4f34-a83a-e716c6cf840a) challenge:

> Analgésique frémissant de longanimité bilieuse phoque ours poil Rosalie Gérard, irréductible gaulois. Mon pilum est plus solide que votre sternum. Spooky sparkles. Sauce, Barbra, flebelebeleb murgepoil. Ce qui ne devrait pas être : déontologie cylindrique soupesée.

I don't know if this is an intentional name or not, but I don't feel so. I use Firefox, always updated. I don't know if I'm using JavaScript or not. My user ID is `d0d2b675-2a55-4e18-bc53-410e04a2e437`.

Here is the screenshot:
![screenshot 2](https://cloud.githubusercontent.com/assets/6695517/6273168/b7854c92-b89f-11e4-9441-a38a251fbbf9.png)

**Comment by crookedneighbor** [comment]
You definitely have Javascript turned on, the site wouldn't work without it! :smile:

Believe it or not, that's a real user's display name. I used the API to look it up. They've been a member since 2013. 

Going to close this. Let me know if you have any other questions.
