### ISSUE TITLE
challenge's guild drop-down menu selects incorrect guild on iOS

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4719]
My apologies if this posts twice, but I posted it 5 minutes ago and nothing showed up.

Short version: I made a challenge with 10 gems that got posted to the wrong guild. As I understand it, if I delete it I'll lose the 10 gems. I'd like to know if there is any way to move the challenge or at least get my gems back (particularly since this happened, in part, due to an interface bug).

Long version: I made a challenge that was supposed to go in my private guild. Unfortunately, the drop down menu for choosing a challenge's guild does not work properly on iOS. Specifically, the guild assigned is the one below the guild that you choose from the menu. I was certain that I had chosen the right guild despite this bug, but when I created the challenge, it went into a public guild above my private guild in the menu.

User ID: db190b28-8ce5-422e-8076-d43a62a7b204

Challenge: https://habitrpg.com/#/options/groups/challenges/78a2a650-fb67-479a-b6c2-27b5d98aba25

Wrong Guild (current): https://habitrpg.com/#/options/groups/guilds/f1343080-c952-4327-a829-df6422374d1d

Right Guild (intended): https://habitrpg.com/#/options/groups/guilds/d7010893-a301-46c0-acb1-ee9504c9dd38

**Comment by Alys** [comment]
You can declare yourself the challenge winner to get the gems back. 

I am about to change the title to emphasise the iOS bug. Can another iOS user please confirm the bug?

**Comment by crookedneighbor** [comment]
I wasn't able to reproduce it. I created a challenge successfully in my private guild. The drop down worked as expected, it said the name of the guild and that was the guild that got the challenge.

**Comment by ghost** [comment]
@Alys yeah, I was hoping to avoid a useless challenge title but that would work. @crookedneighbor This specifically happens in mobile Safari (it is not a problem on the desktop version). Is your guild in the middle of the dropdown list or at the top or bottom?

**Comment by crookedneighbor** [comment]
Using mobile Safari on my iPhone to test it. 

The private guild is third from the bottom, followed by my party and the Tavern. Where is your guild in the list? I'll try to approximate the same position by creating a new guild.

**Comment by ghost** [comment]
So just tried this again, and the FIRST time I choose from the dropdown menu, it selects the guild below the guild I actually click on. Every click AFTER that seems to select the right guild (aka the same as the one you click on) so I'm not sure what's going on.

**Comment by ghost** [comment]
Also, I'm on an iPad (not sure if that would make a difference). My private guild is second from the bottom (right above the Tavern) but it doesn't matter, I can click on any guild and if it's the first time I click on that dropdown menu it selects the wrong guild.

**Comment by crookedneighbor** [comment]
Trying on iPad now, let's see...

Wow. Doesn't happen on my phone, but it does happen on my iPad. I think it's because it starts out with a blank value at the top of the select box, but the blank value disappears when you actually pick a value. So, for some reason on an iPad, that causes it to shift. That also explains why it only messes up the first time around, since the blank selection has been removed.

**Comment by deilann** [comment]
Yeah there's a ticket already for the removal or creation of guilds
screwing up the ordering visually.

**Comment by ghost** [comment]
Interesting. So, yay, I'm not seeing things. And boo, more mobile Safari weirdness. I guess I'm just going to have to select twice to make sure I get the right guild.

@deilann But there was no creation of a guild involved. Only the creation of a challenge and choosing of an already established guild.

**Comment by crookedneighbor** [comment]
I think @deilann is trying to say that it could be related.

**Comment by crookedneighbor** [comment]
We could have it default to the Tavern...

**Comment by crookedneighbor** [comment]
How about if it defaults to the first guild in the list? Any objections?

[This line](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/challengesCtrl.js#L36) should be:

```
group: $scope.groups[0]._id,
```

**Comment by ghost** [comment]
No objections from me either way (defaulting to 1st guild or Tavern). Thanks for putting in the time.
