### ISSUE TITLE
Losing points despite doing everything in a day

### ISSUE THREAD

**Issue by samjam** [HabitRPG/habitica#472]
I recently lost 5 points, despite the fact that I checked off everything on my dailies. Is this a glitch?

**Comment by lefnire** [comment]
Yeah, sounds like a glitch. Did all your dailies become unchecked just fine?

**Comment by ghost** [comment]
Same thing happened to me, but I lost 2.8 or something like that. Everything unchecked

**Comment by Pandoro** [comment]
Could it be the case that you checked all of them, but that the server didn't actually get the "check". Often if you check some daily, you might notice that you didn't get exp. Then if you refresh the site, you will see that it is unchecked again. This is a frequent thing that is occurring. So if you are just checking everything, and then at 12pm the site runs the day change stuff, you might actually not have "really" checked it for the server. I suggest a lot of refreshing until the server is more stable :x 

Just a thought, it might also be a different bug, but this would fit considering the thing I mentioned also happens a lot lately.

**Comment by wildcate** [comment]
Happened to me as well - 0.4 HP docked though I completed all dailies yesterday (and got XP for them all).

**Comment by horusofoz** [comment]
Has there been any further occurrences of this for anyone since we updated the algorithm?

**Comment by wildcate** [comment]
I cannot tell because it's been a while that I completed all my dailies :(

**Comment by lefnire** [comment]
let's follow up at #777, dupe and i added some detailed comments there
