### ISSUE TITLE
android app: white screen

### ISSUE THREAD

**Issue by illuscat** [HabitRPG/habitica#4722]
Hello! I used the android app this morning, and it worked as usual. When I logged in this evening, all I got was a white screen. I tried restarting the phone, uninstalling and reinstalling the app several times, but no dice. Any ideas what may be happening? I have run to the end of my knowledge base, sadly :)

**Comment by negue** [comment]
I`ll look into that once im Home in about 8 hours :/

I think something went wrong on the android update, sorry about that!

**Comment by Zelah-Meyer** [comment]
In case it's any use to anyone, just reporting that I've got the same issue.  It was working when I first connected to wifi and opened the app today, then it updated, and when I opened the app again it was just a white screen.  I tried re-booting my tablet (an Asus Fonepad) and that didn't resolve the issue.  It might also be worth me mentioning that I go a long time between connections to the internet on my tablet - so it's possible that I was more than one update behind.

**Comment by Jadziyah** [comment]
Coming here to confirm the same issue. I installed the update that just came out, and as soon as I open the app...white screen of death. Same with my husband. I run a samsung gs5, he has a gs4. Many many others reporting the same on the app reviews. Super looking forward to this fix because _push notifications_! :D :+1:

**Comment by jonathanfalkner** [comment]
I am also having this issue.
Galaxy S4 Active
Android 4.4.2

Also, when the app went whitescreen, I let it sit for a bit to see if there were any other odd behaviors to report.  After letting it sit for about 5 minutes, 20% of my battery life was consumed.  Sounds like an infinite loop somewhere in the codebase.

**Comment by negue** [comment]
I am so sorry guys!

The fix is being uploaded as we speak, so hopefully in minutes (depending on where the google store updates the apk at first) you can use the mobile app again.

Really so sorry!

**Comment by crookedneighbor** [comment]
[There's a new update that fixes the white screen of death](https://play.google.com/store/apps/details?id=com.ocdevel.habitrpg&hl=en). 

Note: there's a reminders bug in this version (0.0.49) that is being worked on currently. That should be fixed soon, but we wanted to get y'all up and running again as soon as possible.
