### ISSUE TITLE
Align ad on iPad

### ISSUE THREAD

**Issue by ooker777** [HabitRPG/habitica#4723]
I'm not really care about ads, but the untidiness of them makes me hate them more :angry:. I use Safari in iPad to see them.
![Image of Yaktocat](https://kvcq7w.dm2304.livefilestore.com/y2pXqYCMc6Jk_ZFqN2a7M3Ei-Ijqrb9o5zyZSzoTCCS4b4YGVHrVaTDlFwmAQeLl--vwsP63S0uOQwN1fLx2kxH3ECAE15zoOl0QFLMbDwnHhI7r2Ovq9bzhlj_xzA8NRpTOOp3xfo9W2mNnFCvDO0GtQ/20150217_180156000_iOS.png)

**Comment by deilann** [comment]
I think this is not just an issue on the IPad.

**Comment by Alys** [comment]
I believe all ads have been removed so I'm closing this. We can reopen it if I'm wrong.

**Comment by ooker777** [comment]
why do you choose to remove the ads? I'm curious. 

Ooker.
