### ISSUE TITLE
Just installed the app, and all I get is a black screen

### ISSUE THREAD

**Issue by Trollivier** [HabitRPG/habitica#4725]
I really want to use this app.

When I start the app, I only get a black screen, sometimes white. Restarting the device didn't help. Reinstalling the app didn't help.

OS is Android 4.4.2, on Samsung Galaxy S4

**Comment by crookedneighbor** [comment]
Duplicate of #4722 

I'm going to close this ticket. If you would like updates on the progress of the issue, please click the subscribe button on the #4722 page.

**Comment by Trollivier** [comment]
Thank you
