### ISSUE TITLE
Dailies counted to next day

### ISSUE THREAD

**Issue by Jotempe** [HabitRPG/habitica#4727]
Got this problem yesterday: I finished all my dailies in time (I have custom day start set to 3AM, but I actually finished them well before local midnight). All dailies were grey. This morning however I found, that four of them have been counted as done today instead of yesterday - with associated bad effects, like streak counts reset.

**Comment by Alys** [comment]
Hi @Jotempe. This is an example of the bug reported in https://github.com/HabitRPG/habitrpg/issues/4313. I am sorry you were hit by it! If you look near the top of that page, you will see some information about how to fix your data now, and what to do if you notice it happening again. (Wait about five minutes and I will add something to it about fixing streaks.)

I'm closing this issue, but you can track the progress of the bug by going to that page and clicking the subscribe button in the right-hand column.
