### ISSUE TITLE
Odd Issue this Morning

### ISSUE THREAD

**Issue by PWoF** [HabitRPG/habitica#4729]
I had a weird experience thismorning with my account.  BTW my account name is PWoF.

The issue centered around my Dailies and my To-Do list.  When I went to refresh the page to have my dailes and td's reactivated it, was suddenly given a lot of experience points and only one Daily task showed up.  in the To-Do, it replicated 3 To do's I had just created.  So I went to my dailies and I unchecked all the ones that were supposed to reset.  i then decided to wait till the next day, so I check my adventurer into the inn.  That's when i noticed my gems.  I thought I had 9 left but there was only 6.  I am unsure what's going on or if i can get those gems back.  Could someone please help?

**Comment by Alys** [comment]
We will need to know your user ID. You can read how to find it from step 6 at https://github.com/HabitRPG/habitrpg/issues/2760

**Comment by PWoF** [comment]
Whoops, sorry about that.  Here is my ID
7618e1b5-b5eb-43c1-8969-9958e7638fbf

**Comment by Alys** [comment]
Thanks PWoF! Can you tell me please about when were the last two or three times that you changed class? Do you remember what you changed from and to each time?

**Comment by PWoF** [comment]
I only changed classes once.  It was at the beginning when i reached level 10.  I chose wizard, then decided against it and chose rogue.  That was the only time I ever changed classes.

**Comment by Alys** [comment]
Was that just in the past couple of days?

**Comment by PWoF** [comment]
Yesterday, I believe.  Yesterday my time I should say.  I am on central time.

**Comment by Alys** [comment]
The second class change would have cost 3 gems. Is that where the missing gems went? Or did you have 9 gems after you finished changing classes?

I've looked through your To-Do ID numbers and I can't see any duplicates. Do the duplicated To-Dos still appear in your list? If so, please reload the page using your browser's refresh button - are they still there now?

**Comment by PWoF** [comment]
No, I deleted the duplicates.  Sorry.  I only read about reporting bugs after I tried correcting everything myelf.

I had 9 gems left after changing classes.

**Comment by Alys** [comment]
Okay, no worries, but if you come across other problems in future and report them, please let us know if they then get fixed so that we don't spend time looking into them. I've refunded your 3 gems.

If you have the problem with the Dailies not being reset again, it will be this issue: https://github.com/HabitRPG/habitrpg/issues/4313 . There's a section close to the top of the page that explains how you can fix it and how you can prevent it if it keeps happening, until we can work out how to fix it properly. I'm sorry about the trouble it caused you!

**Comment by PWoF** [comment]
No problem.  Thank you for taking the time to investigate.  I will any bugs I encounter immediately next time.  Sorry i couldn't be more helpful to you and your team.

**Comment by Alys** [comment]
That's okay! We're sorry it happened to you!
