### ISSUE TITLE
Can't see icons and ''buy'' pets or weapons

### ISSUE THREAD

**Issue by Joie-zz** [HabitRPG/habitica#473]
=( It's been a few days that I can't either ''buy'' or see de icons of the weapons
and pets. 
I'm using macOSX
Thanx!

**Comment by lefnire** [comment]
Oi, that's strange - so you can see the items / pet icons themselves, but
not the gold button to purchase them? Anyone else experiencing this?

**Comment by Joie-zz** [comment]
Humm no,
For the pets, I see question marks in blues boxes instead of the icons...
For the weapons, there's no icon at all, but I see de gold buttons.
If I press the gold button of the weapons, it does nothing.
Those of my rewards (not weapons) are working though...

2013/2/21 Tyler Renelle notifications@github.com

**Comment by Joie-zz** [comment]
Finally, I tried to open the game with firefox instead and it perfectly work! Thank you for your concern =)!

**Comment by lefnire** [comment]
Hmm. Well the problem was that those sprites you weren't seeing are
downloaded last, so I was thinking either some error the page halted
execution, or something was causing extreme slowness. I'm pleasantly
surprised to see it working for you now, lol!
