### ISSUE TITLE
Coin images (gold and silver) should be pixellated

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4731]
Other things like Gems, Quest Scrolls, Pets, etc. are all pixellated / drawn using pixel art. The images for coins alone are smooth. I believe they should be changed into their pixellated form to maintain consistency.
![habitrpg coins](https://cloud.githubusercontent.com/assets/878118/6315064/ea8268d2-ba1b-11e4-876c-6b1071a98406.png)
##

**Comment by crookedneighbor** [comment]
Ping @lemoness

**Comment by deilann** [comment]
@lemoness Didn't someone work on this?

**Comment by lemoness** [comment]
They're still being worked on - seems like a pretty slow back-and-forth.

**Comment by aipsensmall** [comment]
Has there been any movement on this? I'm not exactly an illustrator, but I am a designer and this sounds like a fun little project.

**Comment by aipsensmall** [comment]
I gave it a shot for fun, and this is what I came up with:
<img width="434" alt="screen shot 2015-07-25 at 2 18 23 pm" src="https://cloud.githubusercontent.com/assets/8648444/8891285/4a882c00-32d8-11e5-81e7-6a8ed716f98b.png">

**Comment by lemoness** [comment]
An artist still holds the claim to this art, although their claim is set to
expire if I don't hear back from them in a week. If you're interested, you
can apply to claim them on this Trello card:
https://trello.com/c/Xey7Guzc/28-miscellaneous Be sure to read all the
rules for Trello claims first!

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by Alys** [comment]
Still waiting for artwork to be done, following the process from that Trello card.

**Comment by librarianmage** [comment]
@Alys On the [Trello](https://trello.com/c/Xey7Guzc/28-miscellaneous), @lemoness said (regarding the coins):

> We have decided to go in a different direction for the new gold and silver icons, so no need to continue on those. Sorry about that!

**Comment by Alys** [comment]
@MathWhiz Thanks for finding that! Nice work.

For the record, the date of that comment from Lemoness was Oct 2, 2015 at 10:35 AM (that's probably displayed to me in the UTC+10 time zone so the time might be different for others).

I'm closing this.

**Comment by librarianmage** [comment]
@Alys (Here it says 10/1/15 at 7:36 PM, and I am in UTC-6, if I remember correctly)
