### ISSUE TITLE
Unable to access website

### ISSUE THREAD

**Issue by jonvmey** [HabitRPG/habitica#4738]
I am currently unable to access the website by browser out by the android app. I keep getting 503 errors or sometimes it will load but I can't actually do anything and it can't pull in any recent data. I was able to log out on both browser and the app but can no longer log in again. 

UUID:5a2e7e10-dcb1-46d6-902a-895389a81cc1

**Comment by lemoness** [comment]
We're very sorry about this! We got a recent influx of traffic and it broke
our site. We're working on it right now. We'll be sure to keep you posted
when it's fixed!

Thanks for reaching out, and thank you for your patience.

**Comment by crookedneighbor** [comment]
@grimmn This has been reported here: #4737 

We're using that ticket to track the progress, so if you'd like email updates, you can click the subscribe button on that issue. 

Very sorry about this, we're working as fast as we can.
