### ISSUE TITLE
Did the API's CORS settings change? 

### ISSUE THREAD

**Issue by edunham** [HabitRPG/habitica#4739]
I enjoy using https://oldgods.net/habitrpg/habitrpg_user_data_display.html but it hasn't been working at all today. While the main site was down it makes sense for the API to be down, but now the site is back and the data display is still not working. 

I tried re-copying my user ID and API key, in case they changed in the move, but it still doesn't work. 

The error I get in the JavaScript console is 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://habitrpg.com/api/v2/user?_=1424735264830. This can be fixed by moving the resource to the same domain or enabling CORS.
```

(my user ID is ebd8b986-c851-4d9c-ba0b-a27262248a93, which is not the ID that was being passed to the API, so maybe it's the site's fault? but the sudden change in behavior is strongly correlated to the recent instability of the main site, so I figure it's worth asking here)

**Comment by Alys** [comment]
@edunham The HabitRPG site is still having significant problems, so any website that uses its API (such as the Display Tool) will also not be working. 

See https://github.com/HabitRPG/habitrpg/issues/4737 for details. We're using that ticket to track the progress, so if you'd like email updates, you can click the subscribe button on that issue.
