### ISSUE TITLE
[Suggestion] Integration: UP wristband by Jawbone

### ISSUE THREAD

**Issue by Narayume** [HabitRPG/habitica#474]
As the title suggests, I would love to see HabitRPG integrated with the UP wristband that will be hitting the EU soon and is already out in America. It incorporates more features than the wristband by Fitbit and has quite a following in America (from what I have heard), so it would be great to see UI integration with their step counter.

**Comment by wc8** [comment]
Follow link to vote for [UP wristband by Jawbone](https://trello.com/c/nKnptOoZ) integration. If vote button is not visible, press "v" to vote.
