### ISSUE TITLE
Errors after leaving inn

### ISSUE THREAD

**Issue by adoniadragon** [HabitRPG/habitica#4740]
Hey all. I just came back to HabitRPG after leaving for a few months. I was able to navigate the site fine, but when I left the inn I could barely load the tasks page. Once there, none of my clicks seemed to register. The task would get selected, but not disappear or register as completed. I tried reloading the page and now I cannot access the site at all.

I'm on Chrome, username Dragnmistris

Thanks!

**Comment by Alys** [comment]
I'm very sorry about this, @adoniadragon, but HabitRPG is having significant problems today. We're working to fix it as fast as we can. See #4737 for details. We're using that ticket to track the progress, so if you'd like email updates, you can click the subscribe button on that issue.

**Comment by adoniadragon** [comment]
Thanks Allison! Didn't realize it was the same issue. Keep up the good work :D
