### ISSUE TITLE
Android App Crashes Immediately

### ISSUE THREAD

**Issue by blendax78** [HabitRPG/habitica#4741]
After the latest update, the Android App crashes immediately when I try to open it up. I tried clearing my cache, clearing all my data, and even reinstalling it, but no luck.  This seemed to occur immediately after buying gems. I'm not sure if it was due to some issue there, or because it also happened to be when the site went down yesterday.

I'm using a Nexus 4 with Android 5.0.1

**Comment by deilann** [comment]
Cannot reproduce.

What version of the app are you using, and what is your User ID?

**Comment by blendax78** [comment]
I'm using 0.0.50.
My user ID is Blendax78.

**Comment by deilann** [comment]
That's your display name or username. We'll need your User ID, which you
can find under Settings > API

**Comment by blendax78** [comment]
Ah .. Duh.  Sorry about that.
My ID is:
84a00cbc-66c6-4821-806b-6d165c92698d

**Comment by negue** [comment]
Yeah there is a bug after buying gems I try my best to get this fixed ASAP. Sorry that you can't use the android app :(

**Comment by blendax78** [comment]
No problem.  Thanks for looking into it!

Also, I should mention that after I bought gems, they never arrived in my account.

**Comment by crookedneighbor** [comment]
@blendax78 Would you email your uuid and the receipt you received to admin@habitrpg.com?

**Comment by deilann** [comment]
Hi @blendax78 ! Is the app working for you again? Did you ever email admin@habitrpg.com and get the gems sorted out?

**Comment by blendax78** [comment]
Hello,

Yep, everything's working and the gem issue got sorted out.  Thanks for the help!

**Comment by deilann** [comment]
Glad to hear it!
