### ISSUE TITLE
Tasks Didn't reset

### ISSUE THREAD

**Issue by PWoF** [HabitRPG/habitica#4744]
ID: 7618e1b5-b5eb-43c1-8969-9958e7638fbf

I had reported this once before and it has happened again.  It might have something to do with the regex issue and the site being inaccessible.

what ahppend this time is that my tasks didn't fully reset.  Also, under my To Do's my two newest items have been duplicated.  I tried refreshing but that seems to give me MORE exp and gold, so I have stopped doing anything completely.  Also, my character has been put into the Inn and is resting.  I was currently on a solo quest and that means i didn't get to inflict damage, unfortunately.

I am currently using the ticket #4313 to fix the Dailies Issue, but I thought I should report the to do duping and the no damage to the boss issue.  I have checked out of the Inn.  Let me know if I can answer more questions

**Comment by deilann** [comment]
See https://github.com/HabitRPG/habitrpg/issues/4742
