### ISSUE TITLE
Duplate damage (both ways) and dailies not unchecked

### ISSUE THREAD

**Issue by AmandaMock** [HabitRPG/habitica#4745]
I understand that you guys had some issues, but even after I took myself out of the in I still have all my dailies checked off and unable to do them. 

Also All of my tasks were duplicated (I deleted them to clear out my list) but at the same time I am dealing and taking double damage.

**Comment by crookedneighbor** [comment]
Having your dailies remain checked when checking out of the inn is normal, being in the inn prevents your cron from running, so it'll run normally tonight and your dailies will be back to normal. If you'd like to get credit for the dailies, you can [follow some instructions written here.](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Resetting_After_an_Unplanned_Tavern_Visit)

RE: the tasks being duplicated, that is not normal. When you say you're taking double damage, are you referring specifically to habits? That's the only kind of task that can hurt you right away without involving cron. Are you getting two notifications? Or is the damage notification just bigger than you expect?

Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

**Comment by AmandaMock** [comment]
2d98182f-cd24-4048-aca8-f691708a1f14

and see the screen shot in terms of what I am referring to, I've opened
another ticket on this before and all the support person said was "that's
an interesting error" with a smiley face and nothing else after. THis was
about a month ago... I'm also a paid subscriber so that left me a little
miffed. Especially since I opened that ticket since it killed myself and my
party when it really shouldn't have.

**Comment by AmandaMock** [comment]
My email didn't
![habitdbl](https://cloud.githubusercontent.com/assets/8353055/6356766/86104234-bc14-11e4-92c3-3293cd7c408f.png)
 add the image, stilly email.

**Comment by Alys** [comment]
_"all the support person said was 'that's an interesting error' with a smiley face and nothing else after."_  That's not exactly what happened: https://github.com/HabitRPG/habitrpg/issues/4657#issuecomment-73631694  I said that the screenshot was "helpful and interesting" (no smiley face) and then I asked for more information, which you provided. Unfortunately I have no idea what is causing the error, so I wasn't able to help further. I did link your report to the main issue for this problem https://github.com/HabitRPG/habitrpg/issues/2805. I'm about to link this one too and then close it so that we don't have duplicates (open duplicates can make problems harder to resolve because they split the investigation comments into multiple places). I am sorry that we still haven't resolved this but at the moment we really have no idea what is causing this.

**Comment by AmandaMock** [comment]
Alice,

you really haven't been very clear in my support with you in the past. So
to be honest, I'm not even feeling served by this right now.

So to be clear, my error will continue and I could indeed keep experiencing
death because of it? And.... the only resolution is that it's
happening..... and that's it?

I get that you guys aren't a premium service, and that I'm only paying you
$5/mo. for something that is otherwise free, That's cool.... but seeing as
how it effects my main experience with you guys I guess I'm starting to not
see why I should keep using the service. The fun element of it (the game
aspect) is basically going to result in me potentially dying over and over
again if I happen to have one bad day.

**Comment by Alys** [comment]
@AmandaMock I am very sorry but yes, that error probably will continue for you. I wish I could tell you that it would stop, but to the best of my knowledge we have no idea what makes this error happen, and therefore we also don't know why it would happen to you so often, or how to make it stop.

It might be possible that if a player had HabitRPG open in two tabs at once and then reloaded both of them at exactly the same time first thing in the morning, then that would trigger cron twice, but it really would have to be a simultaneous reload in both tabs, which would be very difficult to get the timing right for, so I would be surprised if this is what is happening for you every day. But if you do typically have the website open in two tabs and reload both at once in the morning, try to avoid that and see if that helps - if it does help, please tell us!

**Comment by AmandaMock** [comment]
That's not what's happening, I've canceled my payment and moved to
Wunderlist. Dieing every day or risking it constantly ruins the gaming
experience. Thanks.

**Comment by Alys** [comment]
Thank you for letting us know. I have recorded that in the original issue (https://github.com/HabitRPG/habitrpg/issues/2805). I am sorry it didn't work out for you. If you do decide to give HabitRPG another go in future, you can check that issue for information about the progress of the bug.
