### ISSUE TITLE
Android app link to github - Going back to the app doesn't work

### ISSUE THREAD

**Issue by davidmanheim** [HabitRPG/habitica#4752]
I clicked a link in community chat to github, and awesomely, it opens. Much less awesomely, the back button doesn't ever let me get back to the App. Instead, I had to kill the app and re-launch it.

Please confirm that this occurs generally - I was only able to test it on my Galaxy S4.

User ID: 20cfbc43-45ef-4e1b-a301-1232098051b5

**Comment by crookedneighbor** [comment]
Seem awfully similar to this issue: https://github.com/HabitRPG/habitrpg-mobile/issues/227

@negue Thoughts?

**Comment by negue** [comment]
Huh, strange that bug should be already fixed, in some minutes / hours the Update 0.51 should be in the store, could you test again if thats happens again ? @davidmanheim

**Comment by davidmanheim** [comment]
@negue That fixed it; links open in a browser now.

**Comment by negue** [comment]
Great! :)
