### ISSUE TITLE
Quest has no "begin" button

### ISSUE THREAD

**Issue by emily381** [HabitRPG/habitica#4755]
A member of the party started a quest. We have a lot of members in our party and some aren't currently playing so I usually have to manually begin the quest. I am the party leader and until today I have been the one to start the quest. Another member started the quest today and does not see the option to "begin" the quest and when she hits the "cancel" button nothing happens. I am not sure if this is user error. I would like to go ahead and begin the quest if possible. I think it would also be great if party leaders had the option to cancel a quest. I understand not having the option to begin it since the item didn't come from my inventory but it would be nice to be able to cancel it. 

Group ID: 98e27972-d8e5-4423-8485-9a03ff8cb6e4

**Comment by Alys** [comment]
The quest owner is Tamera (full name not included for privacy). They should definitely have both a begin and cancel button at the bottom of the quest box. Could you please ask them to reload the party page using their browser's refresh button and then look for the buttons again? If they still don't see them, please ask them to make a screenshot showing the entire quest box and then you or they can come to this github page and drag the screenshot into a new comment to upload it here (sending it by email won't work).

**Comment by Alys** [comment]
@emily381 Can you please let us know if you still need help with this? Was Tamera able to see the begin button. If not, can you please let us see a screenshot?

**Comment by emily381** [comment]
Sorry I was only getting this second  hand but it looks like it cleared up
after logging out and logging back in.

On Saturday, February 28, 2015, Alys notifications@github.com wrote:

> @emily381 https://github.com/emily381 Can you please let us know if you
> still need help with this? Was Tamera able to see the begin button. If not,
> can you please let us see a screenshot?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4755#issuecomment-76514384.

## 

Sent from Gmail Mobile

**Comment by Alys** [comment]
Thank you for letting us know!
