### ISSUE TITLE
Time Travellers hour glass

### ISSUE THREAD

**Issue by DemonOfIrony** [HabitRPG/habitica#4759]
Hi there i just had an quick question about consecutive monthly subscriptions. I have the monthly subscriptions items from the last four months that I have been subscribed for and yet i  haven't received a time travellers hour glass yet. I thought you got one after three months?
5d1f5f97-9ed6-454b-84fa-2a460ce0718b

**Comment by deilann** [comment]
You should receive it around the first of the month, which is when
consecutive months are updated.

**Comment by DemonOfIrony** [comment]
Ah ok thanks I'll comment again if for some reason I still don't receive it by the 3rd

**Comment by deilann** [comment]
np! I'm closing this, but don't worry -- if you comment, we'll still get emails and you can always reopen it if need be.
