### ISSUE TITLE
View current status of character (show modifiers from items)

### ISSUE THREAD

**Issue by bitflung** [HabitRPG/habitica#476]
Currently I've got armor and swords and things that affect my status - and I can see what is "next" and how that next item will modify my stats - but there is no way to see what my stats are NOW or what the CURRENT items are doing, exactly.

**Comment by wc8** [comment]
Follow the link and vote for this feature request here: [View Applied Equipment Bonus](https://trello.com/c/nbTCZreI). (Type "v" if the vote button is not visible.)
