### ISSUE TITLE
Basi-list quest not received

### ISSUE THREAD

**Issue by Milamber1202** [HabitRPG/habitica#4760]
I created a party and invited two friends. When they joined I expected to receive the Basi-list quest but never did. The two members joined a few days apart and neither time prompted the quest to arrive.

My UserID is: acaf9c1b-8881-431d-a0d7-611f2dafef59
The party GroupID is: c4d765c4-dfc2-4f50-815b-24a149fbd888
I predominately use the website (Chrome on Mac OSX) and the Android App.

**Comment by deilann** [comment]
Confirmed that the quest is not in the user object.

How did you invite the friends? Via email or via UUID?

**Comment by Milamber1202** [comment]
Via UUID. For both of them.

**Comment by deilann** [comment]
Can you refresh  your inventory and tell me if you've received the scrolls
I just added to your account?

**Comment by Milamber1202** [comment]
Confirmed! Thank you very much.
