### ISSUE TITLE
Dailies aren't starting over each day

### ISSUE THREAD

**Issue by KatyJo** [HabitRPG/habitica#4761]
Hi,

My dailies remain checked day to day instead of refreshing.

Thanks for your help,

Katy Jo

**Comment by crookedneighbor** [comment]
@KatyJo Please make sure you're not checked into the inn (if you are, your avatar will have closed eyes and zzz's above their head). You can check out by clicking the social button on the website, or by clicking settings on the mobile app.

We had an influx of new users on Monday and it crashed the server for several hours. As a precaution, we put every active user in the inn to stave off unfair deaths.

If you are not in the inn, can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token).

**Comment by KatyJo** [comment]
Ah! Great! I was in the inn. So tomorrow I should be good to go and refreshed (the page that is).

Thanks so much!

**Comment by crookedneighbor** [comment]
Yep, no problem!
