### ISSUE TITLE
default task for new user has misleading checklist description

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4762]
One of the default tasks for new users says:
**"You can add checklists to Dailies and To-Dos. As you progress through the checklist, you will get a proportionate reward."**

The checklist will increase the rewards gained for To-Dos (although only on completion of the whole To-Do) but it won't for Dailies. Should we change the words? Or for simplicity, leave out the explanation? Or link to [Checklist](http://habitrpg.wikia.com/wiki/Checklist) on the wiki for full details?

FYI, it's in defaultTasks.json with they key "defaultDaily4Notes".

**Comment by lemoness** [comment]
Is this in the current set of sample tasks, or in the new tutorial that is
underway? If it's the old sample tasks, we're going to throw them out soon,
so it's not worth changing.

**Comment by Alys** [comment]
Oh! I beg your pardon! It's in the current set. I had thought these tasks were sticking around for a while. I have not being paying attention. :)

**Comment by lemoness** [comment]
Heh. no worries! Hopefully they won't stick around much longer at all.
_crosses fingers_
