### ISSUE TITLE
You already have that pet. Try hatching a different combination!

### ISSUE THREAD

**Issue by mooooooose** [HabitRPG/habitica#4764]
I attempted to make a cotton candy pink wolf and my internet disconnected as I hatched the pet. The potion and egg are still in my inventory and I have no cotton candy pink wolf in my inventory, yet when I try to hatch the egg again I get the error that I alerady have this pet. The issue is present in multiple browsers on different computers.

1c2349ef-973a-47d6-9c86-a540a7d76307

**Comment by deilann** [comment]
Hm. Strange. I don't see you as having any hatching potions in your
inventory.

**Comment by crookedneighbor** [comment]
Are you sure the egg you're trying to hatch is a wolf? This is what I see for your hatching potions, eggs, and pets:

```
{
    "hatchingPotions" : {
        "White" : 0,
        "CottonCandyPink" : 1,
        "Red" : 0,
        "Base" : 1
    },
    "eggs" : {
        "Wolf" : 0,
        "Fox" : 1
    },
    "pets" : {
        "Wolf-White" : 12,
        "Fox-CottonCandyPink" : 5,
        "Wolf-Red" : 5
    }
}
```

That tells me that you had a wolf egg previously, but now don't. The only egg you have is for a fox, and you already have a cotton candy pink fox. Can you double check and make sure the egg is for a wolf and and not a fox? If it is for a wolf, can you take a screenshot and show us the eggs you have?

**Comment by deilann** [comment]
Guess whose name is Ryan and forgot to refresh before bringing up the user
object...

**Comment by mooooooose** [comment]
This is what I get when I don't get enough sleep. Close my ticket as I tuck my wolf or fox tail between my legs and retreat to the Inn for some needed rest.

**Comment by crookedneighbor** [comment]
No worries.
