### ISSUE TITLE
Push task to top... back to the bottom

### ISSUE THREAD

**Issue by Lexidh** [HabitRPG/habitica#4767]
I have a lot of issues with my tasks. They sometimes multiply, can't get them marked as done (unless I delete them, and that doesn't always work either), but the most annoying right now is that they sort themselves, completely random, and I can't push the ones I want on top to the top, they just keep popping back down to the bottom straight away! I don't have any dates on any of them, it's just regular, single tasks I added to the list. They where added on different days as well. But there are a LOT of them, so not being able to sort is, to put it mildly, annoying. It got even worse when I added some challenges a couple of weeks ago.

**Comment by deilann** [comment]
Try this: https://github.com/HabitRPG/habitrpg/issues/2606

**Comment by Lexidh** [comment]
There was just a few that wasn't from a challenge... which is disturbing, because I haven't deleted done tasks in a long time... =/

**Comment by deilann** [comment]
Non-challenge to-dos archive after three days. When you Delete Completed it
gets rid of the archived ones as well, which is often what's messing up the
sort order.

**Comment by Lexidh** [comment]
Oh dear. They are just half-deleted then, and messes up everything ;P
Thanks, I'll remember to do this if the issue comes back.

**Comment by deilann** [comment]
That about sums it up! :)
