### ISSUE TITLE
Can't gain Feb 2015 Mystery Item

### ISSUE THREAD

**Issue by angelwedge** [HabitRPG/habitica#4768]
I have had no trouble with previous mystery items, but can't gain this month's.

The box shows that I have 2 of them. I click it and the number on the mystery item gift box goes down, but I don't gain the item. After a resync  or refresh, I have the 2 boxes again and the "New Mystery Item" notification reappears. I have tried several times on different days, using different browsers, and using the Android app. I have also used different Internet connections in order to discount the possibility of a proxy messing something up.

I checked in the tavern, and at least one other person has the same issue.

UserID: c54131a9-0a08-4d26-8969-cb6f96bc95bd

**Comment by pho3nixf1re** [comment]
I was having this issue as well, but today it seems to have been resolved. Has it for you @angelwedge ? It would be great if the resolution was posted here for posterity.

**Comment by angelwedge** [comment]
Yes, thankyou. Seems to be working now.
