### ISSUE TITLE
'Error processing string' in Subscribe (polish translation)

### ISSUE THREAD

**Issue by adamkijak** [HabitRPG/habitica#4769]
![image](https://cloud.githubusercontent.com/assets/431490/6412807/e6d9644e-be88-11e4-9c4b-8732a7e2371e.png)

my User ID: 7d0cbc67-0ac1-4d9d-9737-142927b86746

**Comment by paglias** [comment]
@adamkijak Thanks for the report, it's fixed now. It should go live in a few days, in the meantime you can switch to the english version
