### ISSUE TITLE
Changing from Facebook login to sign-in?

### ISSUE THREAD

**Issue by MdmeLibrarian** [HabitRPG/habitica#477]
Against my better judgement I began HabitRPG using the Facebook login, and now I wish I had registered my email and a password instead. Is there a way to transfer my account, or will I need to start over from scratch?

**Comment by lefnire** [comment]
I can transfer you over, but it's a manual process that takes some effort -
for now stick to FB for a bit, I'll get back to you as soon as I get some
time cleared up

**Comment by MdmeLibrarian** [comment]
Thank you for responding. Just knowing that there's an option for me makes me feel better. I'll be patient and wait for when you have less on your plate.

**Comment by horusofoz** [comment]
Is this still in progress?

**Comment by lefnire** [comment]
@MdmeLibrarian I can transfer your account if you want. [email me](mailto:tylerrenelle@gmail.com) and we can get this under way

**Comment by wc8** [comment]
@lefnire [AlphaRevi](http://community.habitrpg.com/content/please-can-i-change-my-username-invasive-unnerving#new) wants to make the switch, too—[update] or to have a username assigned to his facebook login for chat privacy.

**Comment by lefnire** [comment]
@wc8 sorry for the delay, just followed up on that

**Comment by deilann** [comment]
@lefnire Now that you have an actual shiny FAQ on this, I'm gonna close this ticket. (Someday... fewer than 200 tickets!)
