### ISSUE TITLE
Account Confusion Avatar sleeping on Phone Dead on PC

### ISSUE THREAD

**Issue by amyheller2006** [HabitRPG/habitica#4771]
Hello, I have been on pause b/c of an illness. I went to log in today and the screen went a bit crazy with all of this infomration and updates . It then basically told me I was dead.  I am not dead . I was in the lodge. I still am in the lodge on my phone. I would like to resume the game and all of my info as it was.

The userid of the phone account (the one I want to access and use) is: 67c7b393-f006-4932-94bc-11b871e7ff88

The user id of the PC (dead avatar account) is 8cb530f0-8f80-449d-b530-a8595c7fd8e6

Please help! Thank you!

**Comment by deilann** [comment]
When you see the wrong account, delete it. Then log back in.

**Comment by amyheller2006** [comment]
Ok I deleted the dead account but now i cant log in to the other.  I need to know how to get into this account on the PC.  67c7b393-f006-4932-94bc-11b871e7ff88. Thaks for your quick response BTW.

**Comment by deilann** [comment]
Is that account connected to Facebook?

**Comment by amyheller2006** [comment]
i dont think so. I cant recall.

**Comment by amyheller2006** [comment]
the only email being recognized is amy.heller@wgirls.org

**Comment by amyheller2006** [comment]
Now it does not seem to recognize it.

**Comment by amyheller2006** [comment]
Im afraid to log out of the account on my phone b/c I dont want to lose everything.  I cant figure out what it is linked to.

**Comment by Alys** [comment]
You said that you can't recall if the account is linked to Facebook, which means that it might be. Can you please try logging in with Facebook? You can use a different browser on your PC if you wish. You can also go to Settings -> Site to read your own registration information there.

**Comment by amyheller2006** [comment]
That worked!  It will not log me in throuh chrome but it did on IE.  How do i figure out what the login details are so that i can update them.  Thanks !!!!!

**Comment by Alys** [comment]
See my previous comment for how to do that.

**Comment by amyheller2006** [comment]
Thank you for all of your help!
