### ISSUE TITLE
Can't use Esc to cancel pet actions

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#4772]
When casting a spell, pressing the Esc key aborts the action. This, however, is not the case with pet actions like hatching and feeding. It'd be nice to be able to cancel one of those actions in progress by the same method.

**Comment by deilann** [comment]
Jsyk you can cancel those by clicking back on the same thing you clicked on

**Comment by SabreCat** [comment]
Yeah, I'm aware of that. Doesn't stop me from hitting Escape first thinking it'll help me, though. xD

**Comment by pjay-io** [comment]
Easy fix!
