### ISSUE TITLE
Items being automatically duplicated

### ISSUE THREAD

**Issue by CaliforniaDreamin** [HabitRPG/habitica#4773]
tags, habits, dailies and todos are being automatically duplicated. I have multiple instances of being generated offline for everything I create.

**Comment by Alys** [comment]
Thanks for letting us know! 

I think (although I'm not yet certain) that you'll be able to delete the duplicates if you start from those at the bottom of the list, rather than at the top. Please let us know if that works for you.

**Comment by britrochtay** [comment]
This is happening to me too

**Comment by britrochtay** [comment]
Deleting from the bottom worked for me.

**Comment by Alys** [comment]
@britrochtay Thanks very much for letting us know!

**Comment by Alys** [comment]
We think duplicate tasks have been prevented by https://github.com/HabitRPG/habitrpg/pull/4845 (which was merged in https://github.com/HabitRPG/habitrpg/commit/ca72b9a9e1e86262fcab15c7d52ae902953dc7b8) so I'm closing this. It can be reopened if I'm wrong.
