### ISSUE TITLE
Getting one more than the level to level up

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#478]
Even when you get all the points you need to level up (like on level one you need 20 points) you don't level up, you need to get one more than the required. When I first started I had 19 points and I needed 20, so when I got one more (20/20) I was confused when I didn't level up. I actually needed _21_ points. I then started with one point at level two. In RPG's you generally need to get the exact amount of points (or experience) and then you start at 0 for the next level. Is this a bug or was it done intentionally?

**Comment by Pandoro** [comment]
This is a problem with the rounding. Once you get 19.5 exp or more, the
counter will show 20/20 as it is rounded to 20. Now this is still smaller
than the actual 20, so you don't level. If you get 1 more exp though, you
will level and stick to 0.5 in the next level, which is again rounded to 1
on the viewer.

So yes, this is kind of a bug, but not really a big issue, it will be fixed
in some revision though I guess :)

**Comment by horusofoz** [comment]
This is being addressed under ticket #56

**Comment by busterroni** [comment]
I just realized this is a duplicate of #236
