### ISSUE TITLE
Pet drop deleted by Chrome

### ISSUE THREAD

**Issue by MikaShennon** [HabitRPG/habitica#4780]
Hey, I got a wolf egg through a random drop but soon after Chrome forced me to reload, saying there was an error, and the egg was nowhere to be found. Please help, this is my first egg!

473d0ed9-7371-476e-ba61-ce01f5f2978a
Username: MikaShennon

**Comment by MikaShennon** [comment]
Update: The wolf egg started showing up on my mobile version and now it appears to be back in my inventory on the website. Sorry for the trouble, I panicked! ^^;

**Comment by Alys** [comment]
No worries! :) Thank you for letting us know it's fixed!
