### ISSUE TITLE
Yesterday's dailies appear checked today but appear incomplete in my history

### ISSUE THREAD

**Issue by catonwall** [HabitRPG/habitica#4781]
My day didn't restart: the dailies I checked off yesterday are still checked off, but in my History they seem like it wasn't checked off.

Like this: http://puu.sh/ggIQF/3f67664233.png

The one in blue was the only one that wasn't checked off this morning.

I marked all yesterday, even the ones that weren't due that day.

![ss 2015-02-28 at 03 31 11](https://cloud.githubusercontent.com/assets/11248838/6427850/3854247c-bf5f-11e4-88aa-800e18c27f1d.png)

This is my user ID: e1140ee0-1828-4c7b-a345-7376f09765ba

---

Well, I just restored the streak of every daily and unchecked them all.

But my history can be changed? It just feel so sad to throw away such a productive day...

**Comment by Alys** [comment]
Hi @catonwall  This is an example of the bug reported in https://github.com/HabitRPG/habitrpg/issues/4313. I am sorry you were hit by it! If you look in the first post on that page, you will see some information about a workaround for today ("How to fix Dailies that should have become unticked"), and what to do if you notice it happening again ("What to do if you experience this bug often").

I'm closing this issue, but you can track the progress of the bug by going to that page and clicking the subscribe button in the right-hand column. If you have questions, you can ask them here and we'll see them and help you.
