### ISSUE TITLE
Selective enabling/disabling  of Facebook Login and Stripe support in production mode

### ISSUE THREAD

**Issue by evangineer** [HabitRPG/habitica#4782]
Need to run my own instance of HabitRPG in production mode without Facebook Login and Stripe support.  

Config.json would be a good place for flags that enable and disable these features.  Ideally, the same would also apply to New Relic and Paypal, but I'm not so fussed about those.

**Comment by paglias** [comment]
@evangineer if you create a Pull request I think we won't have any problem accepting the changes.

**Comment by Alys** [comment]
I'm closing this since it's old now, but @evangineer we'd still be happy to review any pull request you'd like to submit.
