### ISSUE TITLE
New Relic-related crash on startup in production mode [$15]

### ISSUE THREAD

**Issue by evangineer** [HabitRPG/habitica#4784]
Despite having a valid New Relic license key and successfully connecting to the New Relic collector, HabitRPG is crashing.  The following is from newrelic_agent.log:

```
{"name":"newrelic","hostname":"cerberus","pid":1813,"level":30,"msg":"Starting New Relic for Node.js connection process.","time":"2015-03-02T11:32:32.946Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":1812,"level":30,"msg":"Starting New Relic for Node.js connection process.","time":"2015-03-02T11:32:32.944Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":1812,"component":"new_relic_response","level":30,"msg":"Reporting to: https://rpm.newrelic.com/accounts/798744/applications/5724108","time":"2015-03-02T11:33:23.730Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":1813,"component":"new_relic_response","level":30,"msg":"Reporting to: https://rpm.newrelic.com/accounts/798744/applications/5724108","time":"2015-03-02T11:33:23.732Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":1812,"component":"collector_api","level":30,"msg":"Connected to collector-106.newrelic.com:443 with agent run ID 1292229117.","time":"2015-03-02T11:33:23.734Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":1813,"component":"collector_api","level":30,"msg":"Connected to collector-106.newrelic.com:443 with agent run ID 1292229116.","time":"2015-03-02T11:33:23.735Z","v":0}
```

Upstart log contains the following:

```
admin@cerberus:~$ sudo tail /var/log/upstart/habitgame-web-1.log
    at Request.<anonymous> (/home/habitgame/habitgame/node_modules/request/request.js:1146:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/habitgame/habitgame/node_modules/request/request.js:1097:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:463:13)
    at process.<anonymous> (/home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
[nodemon] app crashed - waiting for file changes before starting...
```
##

**Comment by evangineer** [comment]
Increased logging to trace in newrelic.js and restarted.  Here's what newrelic_agent.log says now:

```
"name":"newrelic","hostname":"cerberus","pid":2240,"component":"remote_method_invoke","level":20,"msg":"Finished receiving data back from the collector for metric_data.","time":"2015-03-02T12:07:42.439Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2234,"component":"remote_method_invoke","level":20,"msg":"Finished receiving data back from the collector for metric_data.","time":"2015-03-02T12:07:42.441Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2240,"component":"new_relic_response","level":10,"response":{"return_value":[]},"msg":"Deserialized from collector:","time":"2015-03-02T12:07:42.442Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2240,"component":"mapper","level":20,"msg":"No new metric mappings from server.","time":"2015-03-02T12:07:42.445Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2240,"level":20,"msg":"No errors to send.","time":"2015-03-02T12:07:42.445Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2234,"component":"new_relic_response","level":10,"response":{"return_value":[]},"msg":"Deserialized from collector:","time":"2015-03-02T12:07:42.447Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2234,"component":"mapper","level":20,"msg":"No new metric mappings from server.","time":"2015-03-02T12:07:42.447Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2234,"level":20,"msg":"No errors to send.","time":"2015-03-02T12:07:42.448Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2234,"component":"error_tracer","level":10,"err":{"message":"Cannot read property 'metrics' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'metrics' of undefined\n    at Request._callback (/home/habitgame/habitgame/website/src/middleware.js:46:46)\n    at Request.self.callback (/home/habitgame/habitgame/node_modules/request/request.js:237:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/home/habitgame/habitgame/node_modules/request/request.js:1146:14)\n    at Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous> (/home/habitgame/habitgame/node_modules/request/request.js:1097:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at process._tickDomainCallback (node.js:463:13)\n    at process.<anonymous> (/home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"},"msg":"Got exception to trace:","time":"2015-03-02T12:08:28.761Z","v":0}
{"name":"newrelic","hostname":"cerberus","pid":2240,"component":"error_tracer","level":10,"err":{"message":"Cannot read property 'metrics' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'metrics' of undefined\n    at Request._callback (/home/habitgame/habitgame/website/src/middleware.js:46:46)\n    at Request.self.callback (/home/habitgame/habitgame/node_modules/request/request.js:237:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/home/habitgame/habitgame/node_modules/request/request.js:1146:14)\n    at Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous> (/home/habitgame/habitgame/node_modules/request/request.js:1097:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at process._tickDomainCallback (node.js:463:13)\n    at process.<anonymous> (/home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"},"msg":"Got exception to trace:","time":"2015-03-02T12:08:28.770Z","v":0}
```

**Comment by paglias** [comment]
I'm not sure this is related to NewRelic, probably another feature
used in production, give a look to the where the request method is
used

2015-03-02 13:15 GMT+01:00, Mamading Ceesay notifications@github.com:

> Increased logging to trace in newrelic.js and restarted.  Here's what
> newrelic_agent.log says now:
> 
> ```
> "name":"newrelic","hostname":"cerberus","pid":2240,"component":"remote_method_invoke","level":20,"msg":"Finished
> receiving data back from the collector for
> metric_data.","time":"2015-03-02T12:07:42.439Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2234,"component":"remote_method_invoke","level":20,"msg":"Finished
> receiving data back from the collector for
> metric_data.","time":"2015-03-02T12:07:42.441Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2240,"component":"new_relic_response","level":10,"response":{"return_value":[]},"msg":"Deserialized
> from collector:","time":"2015-03-02T12:07:42.442Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2240,"component":"mapper","level":20,"msg":"No
> new metric mappings from server.","time":"2015-03-02T12:07:42.445Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2240,"level":20,"msg":"No
> errors to send.","time":"2015-03-02T12:07:42.445Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2234,"component":"new_relic_response","level":10,"response":{"return_value":[]},"msg":"Deserialized
> from collector:","time":"2015-03-02T12:07:42.447Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2234,"component":"mapper","level":20,"msg":"No
> new metric mappings from server.","time":"2015-03-02T12:07:42.447Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2234,"level":20,"msg":"No
> errors to send.","time":"2015-03-02T12:07:42.448Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2234,"component":"error_tracer","level":10,"err":{"message":"Cannot
> read property 'metrics' of undefined","name":"TypeError","stack":"TypeError:
> Cannot read property 'metrics' of undefined\n    at Request._callback
> (/home/habitgame/habitgame/website/src/middleware.js:46:46)\n    at
> Request.self.callback
> (/home/habitgame/habitgame/node_modules/request/request.js:237:22)\n    at
> Request.emit (events.js:98:17)\n    at Request.<anonymous>
> (/home/habitgame/habitgame/node_modules/request/request.js:1146:14)\n    at
> Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous>
> (/home/habitgame/habitgame/node_modules/request/request.js:1097:12)\n    at
> IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n
>    at
> /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n
>    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/c
>  ontinuat
>  ion-local-storage/node_modules/async-listener/glue.js:188:31\n    at
> process._tickDomainCallback (node.js:463:13)\n    at process.<anonymous>
> (/home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"},"msg":"Got
> exception to trace:","time":"2015-03-02T12:08:28.761Z","v":0}
> {"name":"newrelic","hostname":"cerberus","pid":2240,"component":"error_tracer","level":10,"err":{"message":"Cannot
> read property 'metrics' of undefined","name":"TypeError","stack":"TypeError:
> Cannot read property 'metrics' of undefined\n    at Request._callback
> (/home/habitgame/habitgame/website/src/middleware.js:46:46)\n    at
> Request.self.callback
> (/home/habitgame/habitgame/node_modules/request/request.js:237:22)\n    at
> Request.emit (events.js:98:17)\n    at Request.<anonymous>
> (/home/habitgame/habitgame/node_modules/request/request.js:1146:14)\n    at
> Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous>
> (/home/habitgame/habitgame/node_modules/request/request.js:1097:12)\n    at
> IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n
>    at
> /home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n
>    at /home/habitgame/habitgame/node_modules/newrelic/node_modules/c
>  ontinuat
>  ion-local-storage/node_modules/async-listener/glue.js:188:31\n    at
> process._tickDomainCallback (node.js:463:13)\n    at process.<anonymous>
> (/home/habitgame/habitgame/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"},"msg":"Got
> exception to trace:","time":"2015-03-02T12:08:28.770Z","v":0}
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/4784#issuecomment-76702130

## 

Matteo Pagliazzi - paglias.net

**Comment by evangineer** [comment]
Where would I look to see what's happening?  Haven't got my head around the habitrpg codebase yet.

**Comment by paglias** [comment]
Maybe it's this one https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/src/middleware.js#L42
