### ISSUE TITLE
Dailies/Cron still bugged- syncing issue?

### ISSUE THREAD

**Issue by Finnicky** [HabitRPG/habitica#4787]
User ID: adf2885e-070d-4200-b659-52df1e2a7c5e

Over the past few days, I've noticed my HabitRPG iOS app failing to sync with my in-browser data. I've also noticed my dailies were acting weird. The problem that made me report this is that today, my dailies refused to refresh. No, I am not in the Inn; I checked out of the state mentioned in #4742 several days ago. When I opened HabitRPG in another window, I died, but my dailies remained in their current state. The sync button in the browser does not do anything.

Edit: iPod app needs no update. I am running iOS 6 or something if that has any effect.

**Comment by Alys** [comment]
I am sorry that has happened to you! The problem with your Dailies sounds like this bug: https://github.com/HabitRPG/habitrpg/issues/4313
See the three pieces of advice given in the first post in that issue.

The sync problem with the iOS app might be the same or not; I'm not very familiar with app syncing. It might be this issue: https://github.com/HabitRPG/habitrpg/issues/4571

Please post the version of the app that you are using. 

Also could you please check Apple's app store to see if there is an update and if so, install it, and let us know if that fixes the problem?

**Comment by Finnicky** [comment]
I did the first advice in #4313 and it may have worked? I can't tell yet. However, now my Habits are doubled; there are 2 of each of them. A task I made on my iPod has come over, though.

**Comment by Finnicky** [comment]
I fixed the doubled habits by deleting the doubles. The sync button at least looks like its doing something. We'll tell if I'm working tomorrow.

**Comment by Finnicky** [comment]
And my dailies are fixed! Thank you very much.
