### ISSUE TITLE
Real "white-label" service (different from orig. white label idea)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#479]
Ok, I'm starting to realize I may habe been using "white-label" wrong all along, lol. Someone had this recommendation:

> I have one question. Is there any plans for using habitrpg as service for another sites or games?
> What do I mean.
> 1) Assume I have some simple mobile game like match tree or I have some site like reddit.
> 2) I create account on habitrpg for this game or site, for example RedditRPG.
> 3) Next I create some tasks like "Next 100 commet points" or "1000 karma points for one post"
> 4) User can join any of this registered games of sites, but all this tasks are readonly.
> 5) When user complete any task, site change his status via API.

I'll put t in Trello if it gets some traction and gets fleshed out. Pretty good idea, actually - but may take quite some effort

**Comment by Pandoro** [comment]
If I get the idea right, that would mean you would need some admin view for
the owner of the originial service, where this person could set up all
these things and for each site you would have to do an individual api
integration. However I could imagine that if the money is right, this could
very well work out.

I am wondering though who will actually use this for their site? Right now
let's be fair. HabitRPG has grown rapidly, but we don't have the huge
community just yet, where any site or service owner can assume people
already have an account. So it remains to be seen if anyone who would set
this up for their service would actually get a lot of the users to use it.

The other version of the white-label approach, namely use it in classrooms
or businesses does not suffer from this approach, as if someone sets this
up for their company, they can just force all the employees to work with it
;)

So for the time being I am a bit sceptical about how often this version
will actually be requested. Once we hit the size of facebook, I have no
doubt this will be the case :D Can you already see the button everywhere?
Next to the share on facebook, tweet, blog and mail buttons. An add this as
todo on HabitRPG button :D

**Comment by wc8** [comment]
:+1: for _Add this as a todo on HabitRPG button_ ;-)

**Comment by Pandoro** [comment]
Cross mentioning #25 for organization.

**Comment by deilann** [comment]
Hey @lefnire This seems kind of out-dated... can it be closed?

**Comment by lefnire** [comment]
yeah, let's close and follow up on Trello. Org plans are pretty much in the wild, and any future additions will be Trello / email convos
