### ISSUE TITLE
Trial are not removed

### ISSUE THREAD

**Issue by Mon1k** [HabitRPG/habitica#4791]
I joined to trial "C.t.D. Feb 2015". 1 mart timeout, but she don't delete and dont button delete.

**Comment by Alys** [comment]
I think there is information on the wiki that might help you. It is in the [Challenges page in the "Deleting a Challenge Task" section](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task). Read through that section and try each item in turn, until one works. Ask here if you have questions or need more help.

**Comment by Mon1k** [comment]
don't broken megaphone for delete challenfe task
![1](https://cloud.githubusercontent.com/assets/1167446/6459124/8890ec06-c19c-11e4-95b5-a3e43bca740f.png)

**Comment by deilann** [comment]
Did you try these parts:

If the challenge appears to no longer exist but you don't have a broken
megaphone yet, try checking off any Habit, Daily, or To-Do that belongs to
the challenge, then reload HabitRPG. That should sync your task list with
the server and turn the megaphone into the broken megaphone icon.

In some cases, you might need to repeat those actions a few times, possibly
over several hours, before the broken megaphone icon appears (e.g., if your
first attempt doesn't work, wait a few hours and try again, then if
necessary, try again the next morning, and then a few hours after that).

**Comment by Mon1k** [comment]
> Did you try these parts: If the challenge appears to no longer exist but you don't have a broken megaphone yet, try checking off any Habit, Daily, or To-Do that belongs to the challenge, then reload HabitRPG. That should sync your task list with the server and turn the megaphone into the broken megaphone icon.

It helped, but not very obvious. Well that they themselves had been removed or the delete button.
Thank you for your help.

**Comment by deilann** [comment]
The fact that it's not obvious is why Alys linked you to it. ;)

You're welcome!
