### ISSUE TITLE
Buy Quest Eggs After Defeating Boss Once

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4792]
After looking at the number of upcoming quests, we've concluded that people should be able to buy quest eggs from the Market after defeating a Boss just one time, not twice. 

Is this easy enough for a beginning programmer?

**Comment by crookedneighbor** [comment]
To let users purchase after completing once is easy, this is the only line that needs changing: https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/inventory/inventory.jade#L187

Adding the "Can buy X eggs in Market" is a little trickier. First a `"Can buy <%= type %> eggs in Market"` string will need to be created and added to the appropriate file in `/common/locales/en`.

I would probably add some kind of type category to the quests on these lines, maybe something like `type: petQuest`
https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content.coffee#L907-L1534

And then, on the rewards section, have it check if `quest.type == 'petQuest'` and if so, show the new string 
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/quest-rewards.jade

This isn't something I'd give to someone as their first contribution, but it shouldn't be too difficult.

**Comment by lemoness** [comment]
Should we split them out into two different tickets, then? The first one
for changing the requirement, and then later adding the new string?

**Comment by crookedneighbor** [comment]
Is it just the wiki that states that quest eggs can be purchased after completing the quest twice? If so, then I see no problem with separating it out.

**Comment by lemoness** [comment]
I believe so - and the change will be announced via social media and in a
Bailey, so the wiki editors will have plenty of notice to update it.

Let's make this ticket just for the egg-granting change, then!

**Comment by lemoness** [comment]
Edited the original post to take out the string requirement :)

**Comment by SabreCat** [comment]
If nobody from the aspiring-coders crowd nabs this, I can easily update it next time we're rolling out a pet quest.

**Comment by lemoness** [comment]
Sounds good! I'll make a note for the March pet.
