### ISSUE TITLE
Can't get the "Invite to challenge" button in challenge creation to work

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#4796]
(... or maybe I'm just too stupid to find out how to use it properly.)

When creating a challenge, there's a new button now that says "Invite to challenge". When I click it, I get an error message "Cannot GET /modals/undefined.html". This happens no matter whether it's a Tavern, Party, public guild or private guild challenge. I've tried it in three different browsers (Firefox, Chrome, IE) too.

Challenge creation is the only time I see that button. It doesn't seem to show up in an existing challenge anywhere (not during editing either). I don't know if that's intentional.

Anyway, thanks to the coders for adding this button which will be really useful once it works!

**Comment by Alys** [comment]
That button was added in this commit: https://github.com/HabitRPG/habitrpg/commit/6d637e89a28e7c01dc635488ac7eead35e843d01

I'm wondering if it's part of an incomplete change and it was added by accident. It isn't related to the primary purpose of that commit. @paglias?

**Comment by jordaofranca** [comment]
got the same error

**Comment by paglias** [comment]
Ops! This was not meant to be committed (not the whole commit, only the
invite button). I'll remove it tomorrow
Il 09/mar/2015 16:20 "Jordão França Barroso" notifications@github.com ha
scritto:

**Comment by crookedneighbor** [comment]
@paglias No worries, I'll remove it now.

**Comment by crookedneighbor** [comment]
@habitrpguser I'm sure we'll actually add this in, in the future. We just don't have the backend stuff ready for it to work right now!

**Comment by paglias** [comment]
Yeah, Blade is right. I was working on it and it probably got in the middle
of this other commit. I should use separate branches more
Il 09/mar/2015 23:43 "Blade Barringer" notifications@github.com ha
scritto:
