### ISSUE TITLE
Laundromancer: No quest rewards

### ISSUE THREAD

**Issue by freckles2006** [HabitRPG/habitica#4797]
My party completed the Laundromancer quest this morning. It's Attack of the Mundane Questline, Pt. 3: The Laundromancer. While other members of my party seem to have gotten their rewards as usual, I got nothing. No pop-up saying the quest was completed, no items that I can find anywhere, no nothing. It's like I didn't even do it, and I did accept the party invitation and deal damage to the boss. I did a refresh, hard refresh, and logged out and back in. What can/should I do?

**Comment by crookedneighbor** [comment]
@freckles2006 Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api) (be sure to copy only the user ID, not the API Token). Also, it'd be helpful to have the group id. That can be found on the party page.

**Comment by freckles2006** [comment]
User ID: 762e505f-a8b4-4fa8-8c89-6ffb5a790db3

Group ID: 98e27972-d8e5-4423-8485-9a03ff8cb6e4

They've started another quest so I'm not sure if that'll affect anything.

**Comment by elsoan** [comment]
I am having the same issue with the same quest, and was in the same group.  

User ID: 8876a901-7a66-4bd5-8eca-c182478a814a

**Comment by crookedneighbor** [comment]
@freckles2006 and @elsoan You can grant yourself the xp (125) and gold (25) using the fix character values button on [settings page](https://habitrpg.com/#/options/settings/settings). I will award you the items and achievement in the next few minutes.

**Comment by crookedneighbor** [comment]
You should have the items now.
