### ISSUE TITLE
Tags or categories

### ISSUE THREAD

**Issue by witalick** [HabitRPG/habitica#48]
Greetings,

Probably it make sense adding support for tagging or categorizing tasks? It might help to organize things better.

Thanks,
    - V

**Comment by lefnire** [comment]
absolutely, will happen when I have time to work on all this.

**Comment by racuna** [comment]
+1
Tags would be awesome for developing our "character" with special tags like strength (lifting weights, taking stairs, running), magic powers (yoga, meditation, reading, keep calm) or perseverance (not smoking today, cleaning the apartment, productive work). So, we can turn our character in a wizard, a warrior or something else.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
[Trello 43](https://trello.com/c/q7v02jAw)

**Comment by derekantrican** [comment]
Question: Are tags purely for categorization or will they change the outcome of gp/xp/hp?

**Comment by wc8** [comment]
Related Question: are tags going to factor into stats/attributes/classes?

**Comment by lefnire** [comment]
@derekantrican purely categorization
@wc8 i think we'll just add a button group for stats, like easy/hard/medium looks now

**Comment by wc8** [comment]
sounds nice and simple
