### ISSUE TITLE
I cannot join a certain challenge

### ISSUE THREAD

**Issue by Cobradabest** [HabitRPG/habitica#4800]
When I try to join this challenge, I get "Error exception: Resulting document after update is larger than 16777216", and no matter how much I refresh the page, the problem persists. It doesn't do this with any other challenges I've tried joining since, it's just this one...
##

**Comment by deilann** [comment]
What challenge?

**Comment by Cobradabest** [comment]
Oh sorry, I forgot to mention, it's the "Fight Back Against Depression" challenge on the tavern.

**Comment by deilann** [comment]
Can you try again for me now?

**Comment by Cobradabest** [comment]
I still get the error...

**Comment by deilann** [comment]
I think the issue is that simply the challenge is too big! @lefnire any
thoughts? I can't join it either.

**Comment by RebeccaF** [comment]
I'm getting the same error when joining challenges with a lot of participants (something over 900). I can't see any workaround to this, maybe there is one someone can point me to for the meantime? 

I'm getting this on Chrome and Firefox on Mobile.

**Comment by UnexpectedMushroom** [comment]
I'm not sure if I'm getting the same problem or a different issue with the same result. I am unable to join the [Learn Spanish Daily](https://habitica.com/#/options/groups/challenges/b96642a7-8e3b-4587-bfa8-3716b52b29ff) challenge in the Duolingists guild. It has 142 paricipants. The blue line takes much longer than usual, and when it finishes I get "Entity too large". I'm using chrome.

**Comment by ninetyd** [comment]
I think I have a similar issue. When trying to join https://habitica.com/#/options/groups/challenges/f5469002-b21d-4657-8450-2d194e846a73 I get the following error message :"Error request entity too large". I'm using Firefox 41.0.2.

**Comment by Alys** [comment]
@ninetyd What is your User ID? You can see it at Settings -> API.

**Comment by Alys** [comment]
@ninetyd I'm closing this now because we are tracking this bug in https://github.com/HabitRPG/habitrpg/issues/1471 however please do comment here with your User ID and then I will add you to the challenge you listed.

Anyone else who has this bug, please report it at https://github.com/HabitRPG/habitrpg/issues/1471

**Comment by derronbrown** [comment]
Having the same problem joining "10 Habits You Should Do Every Day" - 6acfcb07-d0b5-489f-9ee0-509813bb81e0

**Comment by Alys** [comment]
@derronbrown I'm sorry, the error on that one is too persistent and I can't add you.

**Comment by derronbrown** [comment]
:( thank you for trying.
