### ISSUE TITLE
Kick from Group Should Generate Message

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4801]
now that we've created email alerts and PMs, when a user is kicked from a group, it should generate some sort of notification

It would also be nice if the person doing the kicking can give an optional short user-generated message with the reason for the kick.

**Comment by lemoness** [comment]
ping @paglias

How's this?

subj: Removed from Party

You have been removed from your Party, [NAME]. You can form your own party
under Social > Party, or look for a new one in the [Party Wanted Guild](link).

(optional) Your former Party Leader has provided the following message:
[Message]

**Comment by TheHollidayInn** [comment]
Good idea.

@lemoness I like the message. Should we have options to state if the reason for kick was a negative reason, such as not following guidelines, and then inform the kicked member?

**Comment by paglias** [comment]
@lemoness for simplicity since the logic for removing a member and an invited member is currently the same, it's ok if this feature (email with optional message) is used also for when removing invited only users? Or do you want to stay with the popup for invited?

**Comment by lemoness** [comment]
I think it can be the same!

On Mon, Mar 16, 2015 at 11:04 AM, Matteo Pagliazzi <notifications@github.com

**Comment by paglias** [comment]
@lemoness can we change that text to make it good for both guilds & parties? or do you want to have different versions of it? because right now it's very party specific

**Comment by TheHollidayInn** [comment]
This can be closed via: https://github.com/HabitRPG/habitrpg/pull/5596
