### ISSUE TITLE
TRex Mount Images Much Wider Than Others

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4803]
![](http://i.snag.gy/v87U0.jpg)

The TRex Mount images are very wide... which causes them to take up two rows in my browser, full screen, at a 1366x768 resolution in Chrome on Windows 7.

**Comment by crookedneighbor** [comment]
Related- We discussed reworking the way mounts are displayed on the page to only show the head of the image: #4618

**Comment by SpenserJ** [comment]
This can be closed as a duplicate of #4618, and the T-rex specific issue seems to have been fixed in 7c5b2457be111c99259a6f776cda37dea63acc47
