### ISSUE TITLE
Rock Pets Out of Alignment with Other Pets

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4804]
![](http://snag.gy/tRxTc.jpg)

The Rock Pets are out of alignment with the other pets on the user screen in Chrome on Windows 7.

**Comment by lemoness** [comment]
It's also worth noting that they overlap the background borders in a way
that looks odd - should I make a separate ticket for that?

**Comment by crookedneighbor** [comment]
@lemoness Can you just put a screenshot here?

**Comment by crookedneighbor** [comment]
How's this:

![screen shot 2015-03-05 at 2 26 52 pm](https://cloud.githubusercontent.com/assets/2916945/6513855/b2aff7ae-c343-11e4-824b-2bd2fb5514d7.png)

**Comment by crookedneighbor** [comment]
Here's a screenshot with the background:

![screen shot 2015-03-05 at 2 29 45 pm](https://cloud.githubusercontent.com/assets/2916945/6513903/188228f4-c344-11e4-8e85-eafb45cf26fb.png)

**Comment by lemoness** [comment]
Ah, so by chance, that's a background with a super light border - here are some more in case people have trouble seeing that one:
![screen shot 2015-03-06 at 12 56 18 pm](https://cloud.githubusercontent.com/assets/3494081/6536209/9b49febc-c400-11e4-963e-c896cf533e26.png)
![screen shot 2015-03-06 at 12 56 25 pm](https://cloud.githubusercontent.com/assets/3494081/6536210/9b68d012-c400-11e4-86e1-c7c2e5068abb.png)
![screen shot 2015-03-06 at 12 56 47 pm](https://cloud.githubusercontent.com/assets/3494081/6536211/9b68c630-c400-11e4-9339-8e5fc5e2ccaf.png)

**Comment by deilann** [comment]
The rabbits are also not on the grid.

**Comment by deilann** [comment]
The rabbits are now on the grid!

**Comment by deilann** [comment]
And it appears the slime pets are behaving properly. So I'm going to close this now.
