### ISSUE TITLE
Keys to the Kennels Free After Triad Bingo

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4806]
Similar to the Orb of Rebirth becoming free after you have hit Level 100, we want to make Key to the Kennels free after you've achieved Triad Bingo.

@deilann in case you have further comments!

**Comment by Alys** [comment]
@lemoness FYI,  the next time we deploy the site, the Key to the Kennels will become free if you have Triad Bingo and if you choose to release pets and mounts together. It will not be free if you release only pets or only mounts.

**Comment by lemoness** [comment]
Great! Integrating into Bailey announcement and SM queue.
