### ISSUE TITLE
Shield Guy Sideways on Overloaded Server Page

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#481]
![Screen Shot 2013-02-21 at 4 04 32 PM](https://f.cloud.github.com/assets/3424032/182246/8d782d84-7c6a-11e2-9a96-9a1bfaefe674.png)
Not a major bug just thought I'd let you guys know that the guy in armor is sideways on the server overload page. I don't know why the picture came out so blurry, it's fine when I open it up in preview.

**Comment by ruddfawcett** [comment]
Oh yeah... Noticed this as well...

**Comment by Pandoro** [comment]
I think that was intended, as in "the server fell due to the heavy  load
and died" ;)

**Comment by busterroni** [comment]
Ahhhh... xD Smart. For whatever reason everything suddenly became centered, maybe the page didn't load properly last time?
![Screen Shot 2013-02-21 at 4 09 47 PM 1](https://f.cloud.github.com/assets/3424032/182262/0bc78f22-7c6b-11e2-9fe8-5166ab7970ca.png)

**Comment by lefnire** [comment]
yes, he fell over.
