### ISSUE TITLE
Eclosion potion didnt work

### ISSUE THREAD

**Issue by MilaFairy** [HabitRPG/habitica#4810]
I used a eclosion potion in a egg, but nothing happened. The potion just desapear! What happened?

**Comment by deilann** [comment]
Look in your pets section.

**Comment by MilaFairy** [comment]
I already did it... But there is no pet .

**Comment by Alys** [comment]
Please tell us your User ID (UUID) which you can get from the website at [Settings -> API](https://habitrpg.com/#/options/settings/api) or from the app under Settings.

**Comment by SpenserJ** [comment]
This might be worth closing off after four months without a reply from @MilaFairy.

**Comment by crookedneighbor** [comment]
@MilaFairy I'm closing this now, but if you're still having issues, please reopen it.
