### ISSUE TITLE
"Fetch recent messages" button hides party members from all lists (invitation, quest participants, & members)

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#4816]
When a quest invitation has been sent out but the quest hasn't started yet, hitting the "fetch recent messages" button hides some members in the invite list (in my case, 7 members). The members only reappear after refreshing the page. The member's quest status (accepted, rejected, pending) doesn't appear to have an effect on whether they disappear or not. That being said, the same members disappear each time.

Additionally, when "fetch recent messages" is pressed, the "member(s) list" is also updated. Before the button is pressed, the list shows every member of the party. After the button is pressed, only some of the members are shown, with a "7 more members" note under the list (the "note" looks like a greyed-out button). The 7 members that no longer appear on this list are the same members that no longer appear in the invitation list.

~~I don't know whether this bug occurs when a quest is in progress. I'll test that once my party's current quest starts, and update this post accordingly.~~
Update: This same bug occurs when a quest is in progress.

User ID: 8ac7242d-8f18-4d6f-b4f4-8f6302f7fa0b
Group ID: 24208f39-2381-47d9-9e27-ef7baf81c2d5

**Comment by TheHollidayInn** [comment]
Hello,

I can't check out your user or group, but I am trying to recreate this. I'm not having any success.

Are you still experiencing this issue? If so, is there any customizations you have made to your party?

Thanks!

**Comment by hairlessbear** [comment]
The issue is still happening, and I haven't made any customizations (I recently installed the HabitRPG chat extension, but the issue was happening long before that). I think the issue is at least partially caused by the fact that I'm in a very large group (22 members), as explained below.

Due to a recent change in party membership (we gained and then lost a new member), I noticed that the number of members in the truncated list is always 15. Before the new member left, the "7 more members" message was changed to "8 more members", so it seems like the number 15 is important. 

In the interest of completeness, here's what the member list looks like after "fetch recent messages" is pushed.
![habitrpg_bug](https://cloud.githubusercontent.com/assets/7059890/6810574/02c80f12-d238-11e4-94da-e3b092a75a58.png)

**Comment by TheHollidayInn** [comment]
Hmmm, I believe the 7 more members is the intended behavior. When looking at the code, the members are only supposed to show 15 at a time.

**Comment by crookedneighbor** [comment]
@TheHollidayInn that is true for guilds, but I believe parties aren't supposed to have a limit on how many members are shown. Someone correct me if I'm wrong.

**Comment by gisikw** [comment]
Both are fetched through the same endpoint, so that hard cap of 15 members is there at the API-level.

Honestly, we probably want to look at adding a `groups/{gid}/members` endpoint to the API, since this restriction seems to be a headache for both guild and party features alike.

My only concern is that's potentially 17k records for large guilds :-/ Perhaps a paginated endpoint?

**Comment by crookedneighbor** [comment]
@gisikw I vote for a paginated endpoint.

**Comment by paglias** [comment]
@gisikw 17k is way too large and we can't sustain this load on the db. Especially because each member is a query to mongo which would mean 17k queries. So pagination is mandatory in this case

**Comment by gisikw** [comment]
Wait, why is each member an individual query? Can't it simply be done with `$in: [member_ids]`?

**Comment by paglias** [comment]
@gisikw so the `members` field is populated using mongoose (http://mongoosejs.com/docs/populate.html) https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/groups.js#L40 which I think uses a single query for all the records. So something like `$in: [member_ids]`, you were right.

Anyway the pagination is still necessary I believe, with 17k records for a not really important operation we would probably block both the server and the database itself

**Comment by gisikw** [comment]
Yep, definitely agree that pagination is necessary. Just wanted to make sure we weren't executing 16 queries to fetch a group :)

**Comment by hairlessbear** [comment]
Just to be clear, the members list isn't the only list that changes. As I mentioned in the original post, the list of quest participants is also truncated, but without any indication of members disappearing (i.e., no "7 more members" label or anything similar). The number of participants doesn't seem to matter here, but the users removed from this list are the same ones removed from the members list. [Here's a quick video of the behavior](https://hairlessbear.tinytake.com/sf/MTE2MjQ2Xzc1OTU0OQ).

**Comment by hairlessbear** [comment]
For some reason, refreshing the page no longer brings back the missing members. Now, after "Fetch Recent Messages" is pressed, the only way to bring back the hidden members is to open HabitRPG in a new tab/window. This is a particularly annoying problem when trying to determine which party members have accepted a quest. "Fetch Recent Messages" must be pushed to update the members' statuses, but then a new window must be opened to see the results.

**Comment by joyheron** [comment]
Are you sure? Refresh still works for me.

**Comment by hairlessbear** [comment]
@joyclark I'm sure it was happening yesterday when I tested it, but it appears to be back to normal now. A recent code update must have changed the behavior back to what it originally was. Thanks for double-checking and catching that!

**Comment by hairlessbear** [comment]
@joyclark it's happening again. Refreshing has no effect, but opening a new page does.

**Comment by deilann** [comment]
If opening a new page works, a hard refresh should also work. But you have
to be doing a hard refresh.

**Comment by crookedneighbor** [comment]
@hairlessbear When you say "refresh" do you mean pressing the sync button or refreshing the browser?

**Comment by hairlessbear** [comment]
@crookedneighbor refreshing the browser, but the sync button doesn't fix it either. But as far as I can tell, the sync button doesn't effect the member list or their quest status (pending, rejected, accepted). Pushing sync doesn't change the quest status values or hide the members, so I don't think it affects them.

Also, refresh is now working again (normal, not hard). I'm not sure why the behavior keeps changing.

**Comment by crookedneighbor** [comment]
I was just trying to clarify that you were indeed refreshing the browser and not just syncing. Deilann is right, refreshing the browser should have the same effect as opening a new tab or window.

**Comment by hairlessbear** [comment]
I figured out the refresh issue I was having. I'm using the chat extension, and when you get to your party via the chat extension, it doesn't take you to `/groups/party`; it takes you to `/groups/guilds/<party_id>`. That is the page that the refresh issues were occurring on, not the `/groups/party` page. In other words, there is no refresh issue; I just confused myself.
