### ISSUE TITLE
Have Dailies Only Appear On Days They Are Due

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#482]
It would be useful to have the dailies only appear on the day they are due otherwise they look cluttered.
![HabitRPG Gamify Your Life](https://f.cloud.github.com/assets/3267747/182293/0c949cd2-7c6c-11e2-9cb1-0352ead7571a.jpeg)

**Comment by busterroni** [comment]
I think this has already been suggested. On a side note, how did you get a pet at level 2?

**Comment by ghost** [comment]
I reset occasionally because I level up to quickly and it is similar to https://trello.com/card/repeat-every-n-days/50e5d3684fe3a7266b0036d6/108 but not the exact same thing. I only want to see what is due that day and nothing else.

**Comment by horusofoz** [comment]
@Neohuman [Trello 109 - Option: Hide Until Due](https://trello.com/c/G14jkPYd) has you covered. Navigate to the link and vote for your idea.
