### ISSUE TITLE
website gives security certificate warning, then HTTPS authentication

### ISSUE THREAD

**Issue by andrewtinka** [HabitRPG/habitica#4825]
When I go to https://habitrpg.com in Chrome, I first get a NET::ERR_CERT_COMMON_NAME_INVALID warning:  "This server could not prove that it is habitrpg.com; its security certificate is from *.sandbox.cf3.us. This may be caused by a misconfiguration or an attacker intercepting your connection."

If I proceed, I get the HTTPS authentication dialog box (not the usual HabitRPG login screen).  I didn't enter my username/password there.  When I click "cancel", I get a fairly bare 401: Authorization Required screen.

If I try using Firefox, I get the same thing, but without the security warning.  Firefox seems to be taking me to http://habitrpg.com, not https.

I'm running Ubuntu 14.04, with Firefox 36.0 and Chromium 40.0.2214.111.

**Comment by deilann** [comment]
Cannot reproduce on Windows 7 (Chrome and Firefox) or Ubuntu 14.04 (Firefox
and Chromium).

I know you're running Ubuntu, but I highly suggest that you scan for
malware.

**Comment by Alys** [comment]
Probably related, this was posted to the Tavern 9 hours ago by K.N. (8e0573bc-bba6-47bd-99b9-2d4feb7b08ae):

"Did anyone else get an HTTPS error coming here? It kept trying to redirect me to another site"

**Comment by Alys** [comment]
@andrewtinka Could you please open up a command prompt (run cmd.exe) and type this:

`nslookup habitrpg.com`

and then hit enter. Please take a screenshot of the command and the entire output and add it to this issue. You'll need to come to github to drag the image into a comment, rather than sending it by email which would not work.

**Comment by Alys** [comment]
Or to phrase that in a much more useful way... Don't use cmd.exe, use a Ubuntu terminal. Sorry @andrewtinka! 

Thanks @deilann :)

**Comment by andrewtinka** [comment]
No worries.  Two screenshots attached, one using my default DNS, the other using Google.

I had the same symptoms when I tried to reach the website using Chrome on my Android phone _with WiFi_.  When I turned WiFi off and used my phone's 3G network, the site loaded normally.

So it sounds like something upstream of my devices is doing something naughty?  Possibly my wireless router, or something in the network?

I use Comcast in Cambridge, MA.
![nslookup1](https://cloud.githubusercontent.com/assets/7281227/6574492/f5cb40be-c6fb-11e4-89dd-95627273aac9.png)
![nslookup2](https://cloud.githubusercontent.com/assets/7281227/6574494/f9e38530-c6fb-11e4-837b-6da0cadf9785.png)

**Comment by lefnire** [comment]
Just ran a thing, can y'all check again? Note, it may take some propagation so if it's not working now check back in a few hrs? (If it is fixed now, I'll just close the ticket)

**Comment by andrewtinka** [comment]
checked at 6:30 PM Eastern Time, March 10; still has certificate error.

**Comment by Alys** [comment]
@andrewtinka The problem is most likely that your default DNS server has the incorrect 107.\* IP address. The change that lefnire made was probably a DNS change. DNS changes can take up to 24 hours to propagate (sometimes even longer). Please try again in about 18 hours (or sooner if you like, of course). If it's still not working in 18 hours, definitely tell us then.

**Comment by andrewtinka** [comment]
Checked at 11:30 PM Eastern, March 11; still has certificate error.

nslookup returns 107.21.115.213, 54.243.81.24, 54.243.176.203 .

**Comment by andrewtinka** [comment]
Still had bad nslookup results at 2 PM on March 14.  Changed my DNS server to 8.8.8.8 (thanks Google) and everything works fine.
