### ISSUE TITLE
All old alerts persist upon logging in to HabitRPG

### ISSUE THREAD

**Issue by berriganator** [HabitRPG/habitica#4828]
Each time I log in to HabitRPG, all the alerts I have ever received are all piled on top of each other, all the way down to the "you've unlocked the drop system" alert. I have to click through a pile of alerts each time to get to my tasks. 

I am running Firefox 36.0.1 on a Mac with Better Privacy running that deletes LSO cookies. I do not know if that has anything to do with it.
##

**Comment by crookedneighbor** [comment]
As a first step, I'd turn off the plugin and see if it still persists. I think that is the most likely culprit.

**Comment by berriganator** [comment]
I am not seeing an LSO cookie for HabitRPG, so I don't think it's related.
I just thought to mention it in case.

**Comment by paglias** [comment]
@berriganator you're seeing the tour that was shown when you signed up? 

I would try anyway with removing all the addons you're using as @crookedneighbor suggested.

Let us know what happens

**Comment by SpenserJ** [comment]
I think this is safe to close since it has been four months since @berriganator had the issue.

**Comment by berriganator** [comment]
I do keep having the issue, but have just been dealing with it. Thanks!

**Comment by Alys** [comment]
Then we won't close this. It should be fixed. Thanks for replying @berriganator and I'm sorry we haven't fixed it yet.

**Comment by Alys** [comment]
However, the first thing I would like you to try is turning off all extensions, as described above, then log out of HabitRPG, log in, and if it still happens, log out and log in again.

Alternatively, try using HabitRPG in another browser (one that doesn't have the extensions in it) - log in to HabitRPG, see if the problem occurs, and if it does, log out then log back in and see if it happens again.

If neither of those things help, we'll need your user ID. To find it, please go to Help -> Report a Bug and see step 6.

**Comment by berriganator** [comment]
I have isolated the problem, and it seems pretty specific: all the old
alerts appear only after restarting Firefox for Mac 39.0 when I was logged
in to HabitRPG when the browser was closed. Because I rarely log out of
HabitRPG before closing the browser, I see it all the time.

_Problem persists in Firefox for Mac 39.0 when_
- Logged in to HabitRPG when browser is closed, browser is restarted, logs
  in to HabitRPG automatically
- Logged in to HabitRPG when browser is closed, browser is restarted, logs
  in to HabitRPG manually
- Logged in to HabitRPG when browser is closed, browser is restarted in
  safe mode with all extensions disabled, logs in to HabitRPG automatically
- Logged in to HabitRPG when browser is closed, browser is restarted in
  safe mode with all extensions disabled, logs in to HabitRPG manually

_Problem disappears when_
- Logged out of HabitRPG prior to closing Firefox 39.0, logs in to HabitRPG
  manually
- Logging in (for the first time ever) on Google Chrome for Mac Version
  43.0.2357.134
- Logged in to HabitRPG when browser is closed, followed by restart with
  manual login

Thanks!
Caitlin

**Comment by Alys** [comment]
If at all possible, please try to use HabitRPG on only Google Chrome for a couple of days. Don't log out of HabitRPG any more than you normally would - just use it exactly as normal but in Chrome instead of Firefox. After a couple of days, please tell us if the problem occurs at all in Chrome.

After that we can look at what's causing it on your preferred browser.

**Comment by berriganator** [comment]
Ok I will try to do that and see if it persists in Chrome.

**Comment by paglias** [comment]
This should be fixed now that localstorage isn't used anymore
