### ISSUE TITLE
Party invite not appearing on party screen

### ISSUE THREAD

**Issue by VivaLaPanda** [HabitRPG/habitica#4833]
I recieved an invite from another user, and got the email about it:
Greetings, VivaLaPanda! 

Behzad Khoker would like you to join their party on HabitRPG! 

Together, you can keep each other accountable for your goals while battling monsters and leveling up your avatars. It doesn’t matter if you’re flossing more or finishing that big assignment – either way, you’ll be earning gold, hatching pets, and unlocking weapons! 

What are you waiting for? Come adventure at Behzad Khoker’s side! 

Stay productive, 
Tyler, Vicky, and Leslie 
HabitRPG 

However, upon visiting the link, or going to the party page manually, I am given no option to accept the invitation.

**Comment by deilann** [comment]
Have you tried refreshing?

**Comment by VivaLaPanda** [comment]
Yes

**Comment by deilann** [comment]
Have you tried logging out and then logging back in?

**Comment by VivaLaPanda** [comment]
I'm heading to work, bit I'll try it at about 7 and get back to you.

**Comment by deilann** [comment]
Thanks! Have a good day at work. :)

**Comment by VivaLaPanda** [comment]
OK, I relogged to no avail.

**Comment by Alys** [comment]
Has the quest already started? Go to the party page, reload it, and look at the quest box on the left. Is there a list of participants with "accepted", "rejected", "pending" next to their names (invitation stage), or just a list of participants with no annotations (quest has been started by the quest owner therefore the invitation is no longer current)? 

If that doesn't resolve your question, we will need further information from you before we can investigate properly. Please go to the [Report a Bug instructions](https://github.com/HabitRPG/habitrpg/issues/2760) and give us the IDs described in step 6.

**Comment by VivaLaPanda** [comment]
@Alys , the problem is that I'm not in a party to begin with. The party page just has the thing to make a new party.

**Comment by Alys** [comment]
Sorry! Party invitation, not quest invitation!

I'd guess that they withdrew the invitation. However as I said, there's nothing we can do to investigate this properly without extra information from you - please tell us your user ID.

**Comment by VivaLaPanda** [comment]
UID: 3dd73d43-c0fa-47fc-bfe5-1b957daf88ca
Link in the party invite email: http://mandrillapp.com/track/click/30295795/habitrpg.com?p=eyJzIjoiVTR5TGRHdG1jNmVZb1UxX3h6bU81U1F6WnpFIiwidiI6MSwicCI6IntcInVcIjozMDI5NTc5NSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2hhYml0cnBnLmNvbVxcXC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPXRyYW5zYWN0aW9uYWwmdXRtX2NhbXBhaWduPW1lc3NlbmdlcnMlNDBoYWJpdHJwZy5jb20jXFxcL29wdGlvbnNcXFwvZ3JvdXBzXFxcL3BhcnR5XCIsXCJpZFwiOlwiN2ExNDFmNjkwZWM2NDM1MzgxMmRiYzViYWFkZTk3NjVcIixcInVybF9pZHNcIjpbXCJlNzZiNTMxZjliNmRhMzdmNTdiZjJhMzE1OTRhN2M4ZDAwNGU4ODEwXCJdfSJ9

**Comment by Alys** [comment]
You have no pending invitations. If one was sent to you using your UID, then either the party that sent it cancelled it or someone using your account (e.g., if you left your PC unattended) rejected it.

If the invitation was sent using your email address, it might be a different email address than the one you use with HabitRPG.

**Comment by VivaLaPanda** [comment]
Well, I found the issue. Apparently the user who sent me an invite's account has disappeared.
