### ISSUE TITLE
Gift subscription doesn't hide Ads or lets me buy gems -- subscription / gem purchase screen needs to be clearer

### ISSUE THREAD

**Issue by greatgreenArcleseizure** [HabitRPG/habitica#4837]
I have used the workaround for the paypal-bug in foreign countries.
I gave myself a gift subscription for a whole year but it doesn't hide ads and i still have no possibility to buy gems.
All that changed was that i recieved 20 gems.

User-ID
00c4c436-f7e8-4ed0-9985-47f8966f820c

Browser: Firefox 36.0.1 For Ubuntu Canonical 1.0
Add-on: Noscript (allowing HabitRPG, Github and Stripe.com)
System: Ubuntu 14.02
##

**Comment by Alys** [comment]
So, as soon as you made the transaction, 20 gems appeared in your account - is that correct? 

Can you tell us how you made the transaction? For example, what did you click on first, then what after that, ...?

**Comment by greatgreenArcleseizure** [comment]
Jep, that is correct. It was back in January though but i didn't notice as i use adblock and didn't have the need to purchase gems until now.

Back then there was an option to send a gift to yourself. I clicked on my profile and a menu popped up where i could see my stats and achievements. I clicked on the "send gift" button and chose "12 Month(s): $48".
I paid via paypal which worked fine and the gems appeared shortly after.

**Comment by Alys** [comment]
Okay, that's very odd. Your account shows no sign of a subscription existing (that's why you're still seeing ads and you can't buy gems). Also gems appearing by themselves is not something that happens when you buy a subscription (instead, you get given 20 gems if you make a once-off non-subscription donation of $5). 

Do you still have the receipt that shows you spent $48? If so, please email it to admin@habitrpg.com and include a link to this issue (github.com/HabitRPG/habitrpg/issues/4837) in your email. They will sort this out for you.

**Comment by greatgreenArcleseizure** [comment]
Are the transaction details from paypal enough?

**Comment by Alys** [comment]
Probably, but I can't say for sure. Definitely send them if that's what you have!

**Comment by greatgreenArcleseizure** [comment]
Thank you. :+1:

**Comment by lefnire** [comment]
I fixed this via email, but let's keep it open for a time - I hope to investigate all the major subscriptions issues next week

**Comment by kaitmo** [comment]
Hi! I have the same issue and someone suggested I come report it. I subscribed, was given the 20 gems, but can't purchase additional gems.

**Comment by deilann** [comment]
When you subscribe, you don't get any gems... you have to purchase all of
them. It sounds like you did an a la carte gem purchase (20 gems for $5)

**Comment by kaitmo** [comment]
Well that's bizarre. I completely intended to do the yearly subscription and selected that bubble, but it must have gone through differently. Thanks! That would definitely explain it.

**Comment by Alys** [comment]
@kaitmo Do you remember if you clicked on the card/paypal button that was above the subscription options, or the card/paypal button below them?

**Comment by kaitmo** [comment]
I don't!

**Comment by lemoness** [comment]
There was some discussion of trying to improve the UI of that page so that
there was no chance of getting confused between the two - might be
something to look into. @sugarfiend?

**Comment by crookedneighbor** [comment]
I know I was confused when I first subscribed.

**Comment by Alys** [comment]
@anitaycheng This is what a user sees if they are not subscribed when they click on the gem in the menu bar. I suspect some users are using the top card/paypal buttons when they should be using the lower ones. How would you recommend that we make this clearer? (This might not be relevant to the person who started this issue, but might be to others who have similar problems but from the non-gift options.)

![screen shot 2015-04-18 at 8 37 22 am](https://cloud.githubusercontent.com/assets/1495809/7218206/fdd111d6-e6a3-11e4-85ea-13f2d5f5e986.png)

**Comment by AnitaYCheng** [comment]
Personally, it was not clear to me at all that I had to convert gold to gems at the bottom of the Market page. I truly expected it to be at the top of that window you posted, or in the Rewards column on the tasks page, if anything. (@crookedneighbor posted a mockup of what it would look like to add it in the Rewards column in Trello, which looked awesome!) Not sure how much development effort it will be to put it in the screen you posted, but I believe having it there would be an extremely good idea.

I sketched up a new layout while waiting for the CMS at work, which is slow as rocks today:

![photo 1](https://cloud.githubusercontent.com/assets/6760632/7420876/1901d780-ef35-11e4-8eea-f6218f9df0e7.JPG)
![photo 2](https://cloud.githubusercontent.com/assets/6760632/7420889/372da310-ef35-11e4-97a7-c226cbc4c473.JPG)

**Comment by lemoness** [comment]
I like this new layout a lot! Some notes:

We're using "buy" and "purchase" pretty interchangeably on this page, which
is confusing because buying gems can refer to buying with money or buying
with gold. It's a tiny tweak, but I would like us to separate "purchase
gems with money" from "buy gems with gold" in this messaging.

First panel: "Purchase Gems"

> "Purchase using Credit Card or Paypal"

 "To buy gems with gold,
Become a Subscriber"

> "Subscribe using Credit Card or Paypal"

---

Second panel: OK

---

Third panel:

"Purchase Additional Gems"

> "Purchase using Credit Card or Paypal"

**Comment by AnitaYCheng** [comment]
Yup, wording is totally up to you! I was debating between "Buy Gems separately" or "Buy Gems with Credit Card or Paypal." Hence the white-out. :wink: But whatever consistency works for you!

**Comment by Alys** [comment]
@AnitaYCheng Would the subscription section still be at the bottom of the screen? If so, how can we make it more obvious which set of buttons to use? [ref this comment](https://github.com/HabitRPG/habitrpg/issues/4837#issuecomment-94235895)

**Comment by AnitaYCheng** [comment]
@Alys I think we should encourage them to subscribe, because purchasing gems separately can get expensive quick! How about putting the subscription in a light gray box, so it's more separated from the purchase flow?

![photo](https://cloud.githubusercontent.com/assets/6760632/7506917/fcde478c-f41b-11e4-9395-95314f8bd324.JPG)

**Comment by Alys** [comment]
@AnitaYCheng Something else to consider adding: this comment from Lemoness to briefly explain about gifting a subscription to yourself when you can't use the normal PayPal subscription option: https://github.com/HabitRPG/habitrpg/issues/3381#issuecomment-75918337

**Comment by Alys** [comment]
Other related issues:

[Not clear from Subscription page whether sub is for calendar month, or 30 days - Issue #2650](https://github.com/HabitRPG/habitrpg/issues/2650)

[Subscription screen does not look secure - makes people nervous - Issue #4682](https://github.com/HabitRPG/habitrpg/issues/4682)

**Comment by Alys** [comment]
Pull requests:

[Conditional buy gem modal by AnitaYCheng - Pull Request #5875](https://github.com/HabitRPG/habitrpg/pull/5875) (closed)

[(WIP) Conditional Buy Gem modal, cont'd by SabreCat - Pull Request #6346](https://github.com/HabitRPG/habitrpg/pull/6346)

**Comment by paglias** [comment]
I think this can be closed now, feel free to reopen if it's still valid
