### ISSUE TITLE
Task creation does not check for duplicate IDs

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#4838]
When creating a task with the API, you can provide an id for the task. When this id already exists, a new task with the same id is created. Both tasks are now displayed in the web interface, but all interactions happen on one of the tasks (I think it's always the oldest). Resolving the issue is only possible by deleting one of the tasks (again, this may not be the one the user wanted to interact with). As the only way this could happen is with custom extensions, I'm not sure what the best fix would be. Rejecting new tasks with existing ids could be undesirable if the extension wants to interact with the task at a later time. Assigning a new random uuid could be problematic for the same reason.

**Comment by Alys** [comment]
For reference for anyone unfamiliar with the [API](https://habitrpg.com/static/api), this is using `POST /user/tasks`

I think rejecting the task with an informative error message would be the best option. Two tasks with the same ID is clearly an error situation, so it makes sense for the API to throw an error.

If the third-party tool wants to modify an existing task, it can use `PUT /user/tasks/{id}`

**Comment by chimericdream** [comment]
I submitted a pull request for this, but don't have a setup where I can easily test the remote API. @vIiRuS, if you have HabitRPG running locally, can you pull my branch and verify the fix?

**Comment by Alys** [comment]
fixed in #4845
