### ISSUE TITLE
Quest Invitations on Mobile

### ISSUE THREAD

**Issue by aedunn6** [HabitRPG/habitica#4839]
Sorry if this is a duplicate -- I see that there are a [couple](https://github.com/HabitRPG/habitrpg/issues/4279) [issues](https://github.com/HabitRPG/habitrpg-mobile/issues/283) open for adding push notifications to mobile, but those are more general. 

We have a couple party members that primarily use the mobile version of Habit, rather than desktop version. They are always the last members to accept new quests (and they must be told explicitly to accept the quest) because the invitations don't pop up on the app. Can this be added, please? :)

**Comment by Alys** [comment]
We're rewriting the mobile apps from scratch (the iOS one has already been released) and then we'll be adding features from the website to them until they're complete. Quest invitations will be part of that, so I'm closing this issue/feature request now.
