### ISSUE TITLE
Daily uncheck subtracts less than gives.

### ISSUE THREAD

**Issue by hjarrell** [HabitRPG/habitica#484]
SORRY

When i uncheck on of my dailies it took off 1.6 and when i clicked it again it gave me 1.8.

**Comment by busterroni** [comment]
Pretty sure this is the same thing as #56

**Comment by Pandoro** [comment]
Yes, this has been posted several times. It will be changed at some point probably, but for now we will just have to deal with it. Which isn't all that hard ;)
