### ISSUE TITLE
Checklist won't be numbered correctly due to standard markdown list behaviour

### ISSUE THREAD

**Issue by sparkhee93** [HabitRPG/habitica#4843]
My User ID:  36c80ade-4469-4e2e-af98-cc86e2403d03
Browser/Operating system: Chrome Version 40.0.2214.115 m  / Windows 8.1

When I try to create a checklist and number it like the format below:
![before](https://cloud.githubusercontent.com/assets/6036105/6612981/dd05ac78-c853-11e4-818e-abfed7997c42.PNG)

And once I save it, I get this:
![after](https://cloud.githubusercontent.com/assets/6036105/6612982/dd0d3ccc-c853-11e4-825d-b2ee26e1defa.PNG)

The issue seems to be happening for all categories.

**Comment by Alys** [comment]
@sparkhee93 Tasks and checklist items use markdown, in which a leading digit followed by a period has a special meaning - it always means that markdown should create a numbered list with the correct numbers automatically inserted by markdown itself. This has benefits when you are using markdown in a text document (you don't need to worry about counting the list items yourself and can move the items around without renumbering them manually). However when markdown is used in a checklist, each checklist item is considered to be an individual "document" and so markdown starts renumbering from scratch within each "document", with the result being what you see in your screenshot.

You can insert numbers yourself and have them not converted by markdown by escaping them with a preceding \ - for example: `\2. second item`.

There's more information about markdown on the wiki: http://habitrpg.wikia.com/wiki/Markdown_Cheat_Sheet

**Comment by sparkhee93** [comment]
@Alys I tried what you suggested but the escape character won't work.

For example, when I did "\1. a", it just showed up as "\1. a" directly.

**Comment by Alys** [comment]
Oh darn, that's annoying! Sorry about that. I'll have a look around and see if there's some other way around it.

**Comment by Alys** [comment]
Try putting the slash before the period like this: `2\. second item`

**Comment by sparkhee93** [comment]
@Alys Yup that seems to have done it. Thanks!

Before I close the issue, do you know if this is something that will be modified for the users' sake so that escape character is not needed?

**Comment by Alys** [comment]
To be honest, I'm not sure it could be easily. We use a third-party library for converting markdown and I'm not sure if it provides configuration options. Modifying the third-party code would be undesirable because we'd have to repeat it every time the library was updated. Also as a general guideline, it's usually best to not break standard behaviour for widely-used tools such as markdown (although this is one occasion when non-standard behaviour might be more desirable).

We should leave this open for a while for us to think about it.

**Comment by deilann** [comment]
Definitely think it shouldn't be modified.

**Comment by SpenserJ** [comment]
I agree that it makes more sense to leave it as the standard markdown behavior. If it is a persistent issue that comes up, another solution would be some code that scans the checklists to see if they're formatted as `1. ___`, `2. ___`, etc and either notifies the user or automatically escapes it. In the mean time, this is probably safe to close.

**Comment by crookedneighbor** [comment]
You can also format your checklists like this:

> 1) a
> 2) b
> 3) c

And that will render as expected. It's just the `#.` syntax that markdown overrides.
