### ISSUE TITLE
inbox "Clear All" needs confirmation dialog; "Clear All" and "Opt Out" should be at top of page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4848]
Currently, in a player's inbox, there is a "Clear All" button and an "Opt Out" checkbox, but they both appear at the bottom of the messages so it's really easy to forget they are there. I'd like to see them at the top of the page.

BUT BEFORE we do that, we should make "Clear All" have a confirmation screen, because when it's at the top it will be too easy to click on accidentally (currently, one click means that all messages disappear instantly). I think it would also help to have "Clear All" renamed to "Delete All Messages" to make it really obvious what it does. The confirmation screen should also point out that it will delete messages in your own inbox, not any messages from you in other people's inboxes.

These are two separate changes, so if a programmer wants to work on only one of them that's perfectly fine, but we would not merge a change to the location of the button and checkbox until after the confirmation dialog had been created.

**Comment by lemoness** [comment]
I think these are very good ideas!

**Comment by Alys** [comment]
In the Aspiring Coders guild, katinahat (5a43ad99-f151-4875-964d-b2ce2564512f) has expressed interest in doing this, so we'll consider this claimed by them unless they say otherwise.

**Comment by stillsnowedin** [comment]
That's me (katinahat). I've got it mostly done, but I can't figure out which controller to put my 'delete messages' function in. First I thought it was groupsCtrl, but that isn't working... then I saw there are 7 other controllers in the file and thought it might be one of them... except none are for the inbox! Bah. Soon as I find the right spot, the actual coding will be easy, haha.

**Comment by stillsnowedin** [comment]
Nevermind, I was right all along! Just had a typo. Should be able to finish this tonight.

**Comment by stillsnowedin** [comment]
Please excuse the extraneous references in commits; I'm new to this forking stuff and accidentally messed up my repo history and had to clean it up before making the pull request. The only commit that matters is the most recent one.

**Comment by Alys** [comment]
That's absolutely fine. :) We've all been through the process of learning about github. The commit in your PR is neat and clean and that's what really matters.
