### ISSUE TITLE
Chrome Extension Feature Suggestion: Adjustable work hours for each day.

### ISSUE THREAD

**Issue by MarcMcClain** [HabitRPG/habitica#485]
I'm a student and don't have a regular schedule each day.  Some days I start classes at 8:30AM, and others not until noon.  It would be great if you could adjust the set work hours for each day to account for varying, non-traditional schedules.  As it stands right now, I have my work hours set from 8AM-3PM.  On days I'm don't start class until noon, I will be penalized for general surfing before class at noon.

**Comment by ghost** [comment]
This belongs in the chrome repo
https://github.com/lefnire/habitrpg-chrome/issues/50

**Comment by MarcMcClain** [comment]
Sorry.  This is my first submission on GitHub.  Thank you for the clarification.
