### ISSUE TITLE
To-Dos: "Push Task To Top" not working

### ISSUE THREAD

**Issue by patrickkellogg** [HabitRPG/habitica#4858]
I have a list of 53 items on my To-Do list. If I click on the "Push task to top" icon for a lower item, it will move it to the top. However, Refreshing the page, or closing the webpage and going back to Habitrpg.com will erase any changes that I made. Instead, a different item will be at the top of the list. It doesn't seem to be the item preceeding or following the item I wanted to move - I'm still trying to figure out which item is getting swapped to the top.

A similar thing happens if I click-and-drag an item from the middle of the list to the top. It will look correctly at the head of the list, but if I refresh (or open and close the browser), the top item is again something different and random. Thanks a lot for your help - I can send screen snapshots if you like. 

This bug happens when trying to modify the To-Do list on Windows or Mac running Chrome. I am also using the iOs moblie app, but made sure it was closed down before recreating this problem.

Patrick Kellogg
User-Id: 0c5457b9-5875-4717-96c6-c1e84c9e7474

**Comment by deilann** [comment]
See this issue for an explanation and how to fix it: https://github.com/HabitRPG/habitrpg/issues/2606
