### ISSUE TITLE
API Down - receiving 504 HTTP response code on request

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#486]
Is the current api for up/down of tasks down?  Or is it just me?

**Comment by switz** [comment]
I just tried it out and it seems to work for me. What's not working specifically?  

$.ajax({url:'/v1/users/redacted/tasks/redacted/up', data: {apiToken:"redacted"},type:'POST'}, function(data) {console.log(data)});

**Comment by switz** [comment]
Ah, I actually noticed that `req.is('json')` wasn't working properly (@lefnire). For now, try appending `?play=1` to your request.  

[0] https://github.com/lefnire/habitrpg/blob/master/src/server/middleware.coffee#L3

**Comment by switz** [comment]
Yeah, that website just went down so I can't give you a full example, but here:  

$.ajax({url:'/v1/users/redacted/tasks/redacted/up?play=1', data: {apiToken:"redacted"},type:'POST'}, function(data) {console.log(data)});

**Comment by switz** [comment]
are you POST-ing? is redacted a task-id?

**Comment by elssar** [comment]
I'm getting a 504 too. The same script worked fine a week or so ago.

**Comment by elssar** [comment]
Getting a 504 even after appending `?play=1` to the url.

Guess I'll work on my app next week.

**Comment by elssar** [comment]
Python command line app - https://github.com/elssar/pyhabit

**Comment by switz** [comment]
I'll take a look into this tomorrow, as I can't really fix the issue this second anyway. Meanwhile, we're working on a new API, so I wouldn't invest too much in the current. Sorry for the issues, guys.

**Comment by elssar** [comment]
@switz no problem. I'd rather the new api get up and running quickly :)

**Comment by lefnire** [comment]
Working on this

**Comment by lefnire** [comment]
fixed
