### ISSUE TITLE
Day ends randomly?

### ISSUE THREAD

**Issue by MikaShennon** [HabitRPG/habitica#4867]
Since Daylight Savings, Habitrpg has been registering my "day" as being over (and thus any undone dailies damaging me) at odd times. It used to be consistently at 3:00AM (which was odd but at least consistent with my computer randomly flipping 3 hours back on me), but since daylight savings went back to 12:00AM. This was alright, but then last night it registered my day being over when I checked in around 11:00PM (if not earlier, could have been between my checking at 9:00PM and 11:00PM). Now today I was damaged around 2:46PM for "unfinished dailies". Can you please help? 

User ID: 473d0ed9-7371-476e-ba61-ce01f5f2978a
MikaShennon

**Comment by MikaShennon** [comment]
Additional notes: *Just in case it's also hurting my partner in our party the Group ID: 305771ab-70f1-4f2d-a8b6-0d01c1a2d173 (Puppy-Cat)
                           *I am a Chrome user and unsure of the operating systems version but the issues are also on the mobile version (which I use concurrently with the online version)

**Comment by MikaShennon** [comment]
Last note: I think it also broke my "18 Perfect Days" achievement streak, which is very upsetting.

**Comment by deilann** [comment]
There isn't an achievement streak for perfect days. That achievement is the
number of 21 day streaks you have on Dailies.

First and foremost, I suggest clearing your cache. It may be that the old
time is cached in.

**Comment by Alys** [comment]
@MikaShennon You said: "It used to be consistently at 3:00AM (which was odd but at least consistent with my computer randomly flipping 3 hours back on me)". The way I read that, it sounds like the time set on your computer was changing itself at random times. Is that correct? Is that still happening? If so, I would expect crons at odd times because cron runs based on your computer/mobile device's time.

**Comment by MikaShennon** [comment]
It seems like clearing the cache and doing my best to fix the computer's clock again worked, I waited to post to make sure the day ending didn't start early again. Thank you for the advice and I'll reopen it for further help if this solution doesn't stick. 
Also @Alys yes unfortunately for some reason my computer randomly flips back 3 hours (ex: if it's 5PM it will flip to 2PM with no warning) and it sometimes messes with websites/apps, but it seemed like it was more than that. Not sure how to fix the larger time flipping issue...

Thank you again!
MikaShennon
