### ISSUE TITLE
To-dos with dates on iOS app: weird format

### ISSUE THREAD

**Issue by kaitmiller** [HabitRPG/habitica#4869]
The dates on to-dos with dates have started looking odd to me on the iOS app recently. Screenshot:

![img_0870](https://cloud.githubusercontent.com/assets/8716943/6679223/5b046d9c-cc1b-11e4-92ee-129fa55de76f.PNG)

My user ID: 0974a026-4ff0-4f84-bc0c-c06f8e3c4303

**Comment by easement** [comment]
Looks like UTC. Have we thought about using moment.js for date stuff. It seems like it would resolve a lot of date issues with the JS. It's already a bower package.  http://momentjs.com/

**Comment by negue** [comment]
Fixed with https://github.com/HabitRPG/habitrpg-mobile/commit/cf652fcf4b7425f1b4f264362b843322c21c8fdb
