### ISSUE TITLE
SCRUM-y features

### ISSUE THREAD

**Issue by killroy42** [HabitRPG/habitica#487]
Perhaps it might be possible to start adding some data, perhaps through tags and categories. Eventually HRPG might learn what I am good with, what I have trouble with, when I underestimate (add a ToDo I'll never get done), or over estimate (add a habit or daily that I'll do easily). And perhaps it can start guiding my automatically with rewards or quest-master tips to improve my performance!

**Comment by wc8** [comment]
What are some of the SCRUM features you'd like to see implemented?

**Comment by killroy42** [comment]
Tagging might help me track a task through several states before completion (trello style). But what I am curious about is automating some things our Scrum Master does. This is related to tracking performance and predicting accuracy of estimates. For example HRPG might over time learn what sort of things I procrastinate on. If i tag something in certain ways, for example work-related, urgent, big-task, etc. it might know ahead of time that I'll never complete the task and warn me accordingly. Or better even, offer to break the task intomini-quests, dungeons or other HRPG specific tools to help me complete the tasks.

Over time according to the development of my RPG character and skills, HRPG might "know" things about my work habits and actalaly actively help me improve my performance. If this doesn't make sense. I'll ponder it some more and try to come up with specific use cases.

**Comment by horusofoz** [comment]
I understand what your requesting and though it would be truly awesome, it won't be on the cards for a long time. We don't have the knowledge or capacity to introduce prediction into the app just yet.

A great suggestion and we'll review it again in a year or so.

**Comment by killroy42** [comment]
I have a personal interest in machine learning. Perhaps this can be an external service via the API.

**Comment by wc8** [comment]
Does Scrum Master have/work with an API or do you know of a similar Scrum app that does?

**Comment by killroy42** [comment]
Our sscrum masters API is Whiskey and a pencil I guess ;) I was more thinking perhaps this would have to be created fro mscratch and integrated via the API.
