### ISSUE TITLE
Health and Experience bars always appear full in Internet Explorer

### ISSUE THREAD

**Issue by OlasDAlmighty** [HabitRPG/habitica#4876]
Although it shows up fine in both Chrome and Firefox, I've noticed when I logged into HabitRPG in IE11 the bars for displaying both Health and Experience points both appear completely full, even though I know they aren't and can even see as such by the numbers on the right hand side.

I have tried reloading the page, logging out and back in, and closing and reopening the browser.  

Obviously this isn't a huge issue, it just makes the UI less convenient, and it won't affect people on other browsers.  Unfortunately the computers I use at work, where this tool comes in most handy, only have IE installed, so I'll have to deal with it until it gets resolved.

Right now I'm using Windows 8.1 and Internet Explorer 11 on the desktop.  I don't know whether the issue is still present on other operating systems or versions of IE.

**Comment by gisikw** [comment]
I was able to reproduce this in a Windows VM. I'll take a look and see if I can track this down :)
