### ISSUE TITLE
Aborting a Quest Should Add System Message to Party Chat

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4879]
Currently, when a quest is aborted, no message is put in party chat. This means that there is no explanation for where a quest went to the rest of the party, which can be rather confusing. When a quest is completed, there is a message added. When a quest is aborted, a system message should be posted, saying:

`Alys aborted the party quest The Spirit of Spring.`

or something similar.
##

**Comment by crookedneighbor** [comment]
I'm in favor of always blaming Alys for canceling a quest.

**Comment by deilann** [comment]
I'd take it a step further:

I'm in favor of always blaming Alys.

**Comment by Alys** [comment]
_**So**_ angry right now!

-- _Alys_
_Guardian Blackguard, Quasher of Quests, Poacher of Progress, Destroyer of Dreams_

**Comment by FriendlyPopo** [comment]
I've been trying to poke at this but I have encountered a few issues.

**habitrpg\website\src\controllers\groups.js** ln906 (api.questAbort function)

``` javascript
  User.findById(group.quest.leader, function(err, aborter){
    if (err) return next(err);
    var abortedQuestMessage = aborter.profile.name + " aborted the current party quest.";
    group.sendChat(abortedQuestMessage);
  }); 
```

1) The system message appears in the UI but not in the db (so fetching new messages erases it)
2) I'm also trying to get the quest name, and my best guess to get it was:

``` javascript
var questName = shared.content.quests[group.quest.key];
```

But it group.quest.key is _null_.

Any ideas / pointers?

Thanks in advance!

**Comment by Alys** [comment]
If the quest key is null, it's almost certainly because the quest has already been aborted. Note that async.parallel causes all functions within it to be executed at the same time (or if not exactly the same, in an unpredictable order), so if your code is within the async.parallel block, you'll need to take it out.

If that's not enough to fix it, please upload your code to your github clone of the repo and paste a link to the relevant sections of the scripts in here.

**Comment by FriendlyPopo** [comment]
No, the code is all outside the async.parallel block.

See it here: https://github.com/Horacious/habitrpg/blob/develop/website/src/controllers/groups.js#L906-L910

**Comment by Alys** [comment]
https://github.com/Horacious/habitrpg/blob/develop/website/src/controllers/groups.js#L906  is `.leader` correct? Also I can't see where you're referring to group.quest.key in your new code. Has your code changed since you asked those questions? If so, please let us know which questions are still relevant.

**Comment by FriendlyPopo** [comment]
No it's not correct. Sorry about that (and other inconsistent PRs).

Feels like I spend minutes coding and hours trying to get Git to do what I want it to. Just disregard them all, I'll start over from scratch after learning more about Git & github.

**Comment by abatula** [comment]
Is this still a problem? I can work on it if it is.

**Comment by Alys** [comment]
@abatula Please do work on this if you'd like to! Comment here if you have questions or run into problems.

A related issue is this one: https://github.com/HabitRPG/habitica/issues/8072 "when a quest starts, a `system` message should be written to party chat" and a fix is being developed in this PR by dumindux : https://github.com/HabitRPG/habitica/pull/8107. You might find useful code ideas there and/or things that could be done a similar way in your PR for this issue, for consistency.

**Comment by Alys** [comment]
A related issue is this one: https://github.com/HabitRPG/habitica/issues/8072 "when a quest starts, a `system` message should be written to party chat" and a fix is being developed in this PR by dumindux : https://github.com/HabitRPG/habitica/pull/8107. You might find useful code ideas there and/or things that could be done a similar way in your PR for this issue, for consistency.
