### ISSUE TITLE
Math for HP Loss/Exp gain for habits with a Plus AND Minus option is different from those with either a Plus OR Minus option

### ISSUE THREAD

**Issue by danj3ris** [HabitRPG/habitica#488]
Any habit with a plus and minus option works on a different math system than habits that only have a plus or a minus option. I like the way the system works, where a habit with plus and minus options will shade differently and either hurt or reward you more depending upon how far negative or how far positive you are within that habit.

A habit with only a plus or a minus does not work this way. Clicking a plus will always reward me the same and clicking a minus will always hurt me the same. The habits will not change shade either.

To relate this to my own situation, I have a bad habit that I wish would hurt me more every time I performed it. This is not a double sided habit, there is no alternative but to not perform the habit. There is no positive.

The only way I can make the performance of this habit hurt me progressively worse each time is to list it as a Positive/Negative habit and never click the positive.

I have no problem doing this, but shouldn't the option exist for bad habits to be given a math similar to double sided habits? In this case I'm guessing the passage of time would make performance of the bad habit hurt less?

I leave the math of positive habits up to others to decide. The same idea can't really be applied to singular positive habits because there is no stopping point like there is for negative habits (death).

**Comment by cleave29** [comment]
I think this relates to #447.  I experienced something similar.

**Comment by danj3ris** [comment]
Thanks for showing me that issue @cleave29. I was under the impression that habits with either a single plus or a single minus were purposely supposed to act differently than habits with both options. My post was more so a suggestion to @lefnire that they act similar to the habits with both options, especially in my case the bad habits, whose increasing HP drain would reinforce my choice to stop the habit once and for all.

If it is indeed a bug, now I know!

**Comment by PhilipHow** [comment]
This could be implemented as you say, progressively worsening each negative habit currently, as it does with Positive/Negative habit.

It could be made consistent by employing the same with the positive habits (i.e. a positive habit increases XP gain per day with each successful tick) but with specifying "limits". i.e. Eating a successive piece of fruit a day is good for you, but anything more than 5 you probably get diminishing returns. It's the same with exercise, so I think this model works well.

The user could specify the limit themselves (as it will change for each habit), but I think there should be a hard cap coded to prevent gaming the system - I'm not sure there's one employed already for P/N habits, but I will check!

It's probably worth putting in a cap for Negative habits as well, but perhaps only a hard cap. I can't think any bad habits that reach a point of diminishing returns.

**Comment by tmas** [comment]
What if + habits got a bit redder (and - habits got a bit greener) each day they weren't done? If this was implemented, the +/- button on the habit would act normally and use the same algorithms as normal +/- habits that simply didn't give benefits or do damage when they weren't performed. This way doing a good habit you haven't done in a while is more rewarding (which motivates you to do it) and doing a bad habit gets worse and worse the more you do it while not affecting you as negatively when you do it for the first time in months.

**Comment by wc8** [comment]
@tmas check out [Shading on +/- "Only" Habits](https://trello.com/c/YSXfecBt)
@MrConcept hard cap coded into the system is controversial. I'm thinking for it to be high enough to allow for flexible use of HabitRPG might be difficult. On the other hand, I think the user defined cap might be useful.

**Comment by wc8** [comment]
@MrConcept follow this link to vote for [User-Defined Per Habit Cap](https://trello.com/c/hpi6wlGA).

P.S. The algorithm gives diminishing returns by click frequency.

**Comment by horusofoz** [comment]
@danj3ris With the tweaks to the algorithms and proposed features, would you consider this resolved?

**Comment by paglias** [comment]
I think this is resolved now. Just made a fast checking, if it still happens, just post a comment and I'll reopen it
