### ISSUE TITLE
unable to complete tasks on mobile app

### ISSUE THREAD

**Issue by evasager** [HabitRPG/habitica#4884]
Last night I was having trouble marking dailies as completed.  When I touched them, nothing happened.  I switched to the "ToDo" view and switched back to "Dailies" and everything that I checked was now checked, so I figured it wasn't an issue.  I completed all my Dailies and made good progress on my Habits - it was a good day.  This morning I woke up and I was dead.   It was as if nothing non of my Dailies got logged.  I read up on how to reset my stats and did that...  but wanted to report the bug so that it can get fixed.  This isn't the first time I had the non-responsive issue - but it is the first time I died from it.  I think the other times I ended up correcting things by switching to a computer.  I was using IOS and my user id = e5834253-f7ec-4796-bac6-6b9c979a349d

**Comment by lemoness** [comment]
Hi evasager, we're sorry that happened to you! It sounds like the app was not online, so the tasks you checked off did not sync to the server. In the future, you can try pulling down to manually sync.

You can restore your stats and your daily streaks on the website. Go to task edit to reset the streaks, and Settings > Site > Fix Character Values to restore your gold, XP, and level.

Let us know if you have any trouble, or if there is anything else we can do to help!

**Comment by Alys** [comment]
@evasager We're tracking iOS sync problems at https://github.com/HabitRPG/habitrpg/issues/4116 so I'm going to close this issue, but if you need further help, you're welcome to comment again!
