### ISSUE TITLE
new computer = having to start over?

### ISSUE THREAD

**Issue by shaineraizel** [HabitRPG/habitica#4894]
I started on my old laptop (win 8) and luckily i downloaded the app on my tablet.  When I got a new laptop (still win 8) I went to log in, and it restarted me like it was a brand new account.  I really dont use the android app since sometimes it bugs on tasks, but it showed my old account ,so luckily I got myself in the inn.I have tried resetting my password and syncing.  neither has worked, and i am out of ideas.  I would really like to use my laptop for hapbitrpg, especially with some of the challenges I was in the middle of.  The user ID is 789209db-3378-40a5-bd14-9dacf2a01fd.  That is from my tablet and the original account.  The brand new one has a different one though it is the same email.

**Comment by crookedneighbor** [comment]
Please post the new user id as well.

**Comment by deilann** [comment]
No need to post the New user id. Just delete the imposter account and log
back in.

**Comment by Alys** [comment]
@shaineraizel I'm closing this but if it's still a problem, comment here.
