### ISSUE TITLE
Lost gems!

### ISSUE THREAD

**Issue by Ganryuuu** [HabitRPG/habitica#4896]
Hello, i started off today with 25 gems and i have spend just 10, but my gems have decreased to 10 after use my pickpocket spell, someone can help me?

"Hi, I started off today with 21 gems that I got through my subscription (gold -> gems). This afternoon I noticed that I only have 14 gems, and have therefore lost 7 gems. I've been scouring my inventory to see if there is something I bought by accident, but I can't find anything new!
I did get a 'Server Unreachable' error earlier today after casting my rogue pickpocket spell, but that is it.. Nothing out of the ordinary, I'm baffled!"

Forgive my bad english x.x

https://github.com/HabitRPG/habitrpg/issues/4857

**Comment by Alys** [comment]
@Ganryuuu I'm investigating this to work out what happened.

**Comment by Ganryuuu** [comment]
Ok, Thanks. =]

**Comment by Alys** [comment]
@Ganryuuu I've given you back the missing 5 gems, although I'm still trying to work out exactly what happened.

 It looks like you bought the Beards and Mustaches. Was there anything else you bought?

**Comment by Ganryuuu** [comment]
Beards and mustaches (5 gems), and the kit rogue of  Seasonal Shop (5 gems), right? nothing more :o

Thanks for help

**Comment by Alys** [comment]
Thanks for the information! I think what happened was that due to a sync error or similar, you were double-charged for one of those purchases. Sorry about the trouble! Let us know if the 5 gems I gave you didn't show up, or if it happens again.
