### ISSUE TITLE
Complex Todos

### ISSUE THREAD

**Issue by witalick** [HabitRPG/habitica#49]
May be folded/unfolded.

For instance...

A "C++" courserra course
- templates
-  STL
- etc

Pros:
- Better progress tracking;
- More involving;
- A user is being rewarded for each step during the process of task execution and probably some extra reward once the Todo is completed

Many thanks. Very nice project,
    - V

**Comment by lefnire** [comment]
we'll keep follow-up on #67

**Comment by wc8** [comment]
[Checklists](https://trello.com/c/PJ1iJ413)
