### ISSUE TITLE
More errors running locally

### ISSUE THREAD

**Issue by tmas** [HabitRPG/habitica#490]
Not sure exactly what this error is caused by, but it certainly prevents me from using habit locally (with the same symptoms as #429).

![error](https://f.cloud.github.com/assets/271652/186723/bdde3398-7d36-11e2-83ed-8709eab8b4e3.png)

**Comment by lefnire** [comment]
You running off the `develop` branch? That should be fixed, by pinning the browserify version at 1.x. If not, do 

```
rm -rf node_modules/racer/node_modules/browserify
npm install browserify@1.17.3 --save
```

**Comment by tmas** [comment]
I tried both the master and develop branches, both gave the same error.

**Comment by lefnire** [comment]
https://github.com/codeparty/racer/pull/84

**Comment by tmas** [comment]
Alright, those commands fixed it. Now I can finally start contributing once I've learned derby :D
