### ISSUE TITLE
Dailies not resetting

### ISSUE THREAD

**Issue by Myntax** [HabitRPG/habitica#4901]
My dailies aren't unchecking themselves every day like they used to. They will remain checked from the previous day, so I have to manually uncheck them each day.

My user ID is fd81fd7e-e327-4f5e-9522-940acd3d440b
My browser is Chrome and I'm using OS X version 10.9.5

**Comment by crookedneighbor** [comment]
@Myntax Your user is currently in the inn, which pauses activity on dailies.  

If using the website, [go here](https://habitrpg.com/#/options/groups/tavern) and click the big green button that says check out of the inn. If you're using the mobile app, go to settings to check out.

**Comment by crookedneighbor** [comment]
If you're still having issues after checking out, feel free to respond again here.
