### ISSUE TITLE
Notification for Guild invitation leads to a empty page

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4902]
I've juste been invited to a guild. I received a notification that I can click. If I indeed click the notification, this leads me to https://habitrpg.com/#/options/groups/guilds, which looks like this:

![screenshot - 23032015 - 00 29 20](https://cloud.githubusercontent.com/assets/4882150/6772114/dff4078c-d0f4-11e4-8008-603baa4bf6fa.png)

This is on Firefox 36 on Xubuntu. I also tested it on Firefox Mobile and Chrome Mobile on Android Lollipop with the same result.

![2015-03-22 23 29 05](https://cloud.githubusercontent.com/assets/4882150/6772121/5e85b4d8-d0f5-11e4-94a4-1af6b3d50789.png)

(The cache has obviously not been updated in this last screenshot, but the problem is the same after a refresh)

What strikes me in here is that, of all the guilds options (_Public Guilds_, guilds I already joined or _Create a Guild_), none of them is selected at this point.

Now, from this page, if I click on _Public Guilds_, I am then lead to https://habitrpg.com/#/options/groups/guilds/public, which tells me that I have been invited, and I can accept or reject (or browse public guilds). This looks like the page I should have arrived in the first place. I did not find another page which allows me to accept the invitation.

My understanding is that the link in the notification is incomplete and should add `/public` to lead the user to the right place. Or maybe I missed something obvious ?

**Comment by Alys** [comment]
If you've accepted the invitation, could you please invite me to the guild, or ask the guild leader to invite me? I just want to see what happens for myself, and I won't join the guild (except possibly by accident, but then I'd leave immediately without reading anything).

**Comment by ghost** [comment]
I've not yet accepted the invitation, so that I can reproduce it anytime, but I'll ask the Guild to invite you anyway so that you can reproduce this behaviour on your own.

**Comment by Alys** [comment]
Yes, the correct URL is definitely https://habitrpg.com/#/options/groups/guilds/public but the notification in the HabitRPG menu bar takes you to https://habitrpg.com/#/options/groups/guilds

This should be an easy fix. I have advertised it in the Aspiring Coders guild for a new programmer to try.

FYI, accepting the invitation from the email does take you to the correct URL.

Thanks very much @Blablux! This was very useful.

**Comment by ghost** [comment]
I indeed tried to track this bug myself, but the codebase seems just too huge for my petty skills. I guess I'll stick to analyze and report.

**Comment by gkjt** [comment]
I think I have this fixed, just need to sort a pull request out, if I could message someone to just check a couple of things? (Or I could ask on here, if its ok to pollute this a little)

**Comment by paglias** [comment]
You can write here, don't worry
Il 23/mar/2015 19:15 "gkjt" notifications@github.com ha scritto:

**Comment by gkjt** [comment]
Ok, thanks, with the pull request branch comparing screen, do I set the base to be the develop branch or a branch that is specifically for this fix?

**Comment by paglias** [comment]
I think the base is develop and you should compare it to your own branch
for fixing this
Il 23/mar/2015 19:26 "gkjt" notifications@github.com ha scritto:

**Comment by gkjt** [comment]
Ok, thank you, I've just posted it
