### ISSUE TITLE
Quests keep disappearing

### ISSUE THREAD

**Issue by Jymaru** [HabitRPG/habitica#4912]
User ID: 3f2066ac-191b-45bd-ad65-09ba98aa656e
Browser: Firefox (also tested from Chrome, Opera, and the HabitRPG App)
Operating System: Windows 7 (Also tested from Android 4.4)

I run a solo party to do quests. But my quests keep disappearing, along with all messages relating to them, as if they'd never existed. Sometimes they come back, sometimes they don't

I'm currently attempting the quest SnackLess Monster, and it disappeared over a month ago, and hasn't returned even once since. This has also happened with the Golden Knight and Dragon's Influence quests, and these quests can be activated whilst another quest is technically running, and they will end up stacking, but none of them will stay appeared for very long

**Comment by deilann** [comment]
Oh, this sounds like the two party issue.

Try leaving your empty party that is quest-less, then log out, and log back
in. See what happens.

**Comment by Jymaru** [comment]
That seems to have fixed the issue, thank you (I wonder why it does that)

**Comment by deilann** [comment]
Is your account older? There was a bug that caused some folks to be in two
parties at once a long time ago.
