### ISSUE TITLE
Spring 2014 gear gone

### ISSUE THREAD

**Issue by carolab** [HabitRPG/habitica#4916]
I remember I used to have the 2014 spring gear. It's all gone, and I didn't even notice, I don't remember losing it any of the times I died. I just noticed when I was looking at the seasonal shop.
I'm using Chrome, my user ID 7e08d2af-5daa-48b0-b8c3-f5ef305ae51b

**Comment by deilann** [comment]
Your account data seems to imply that you never purchased the 2014 spring
gear.  Are you positive you were active on the site during that period and
purchased it?

**Comment by carolab** [comment]
I remember I was active and at least bought the mouse ears... Now I'm starting to doubt. But if the data says I never purchased it, maybe I got confused. Thanks for the reply.

**Comment by neverasuspect** [comment]
All 10 of my egg basket mounts disappeared 2 days ago. They were eggs left over from last year's egg quest that I fed.
User ID 0309ae9c-d809-4506-8a09-0b8848233171 using Firefox

**Comment by Alys** [comment]
@neverasuspect Your account shows that you still own all of those mounts, and the pets, so this is just a temporary display problem. Reload the website and they should reappear. 

They probably won't appear in the app for a few days until the latest update is approved by Apple/Google (could be a few weeks for Apple; they've very slow).

**Comment by SpenserJ** [comment]
This can probably be closed after four months with no reply from @carolab and @neverasuspect.

**Comment by crookedneighbor** [comment]
@neverasuspect I'm closing this now, but if you're still having issues, please reopen it.
