### ISSUE TITLE
Dailies Reset, DMG, and Streak Reset Before 00:00

### ISSUE THREAD

**Issue by Amputatoes** [HabitRPG/habitica#4918]
The issue is best summarized in this conversation:

@Jajbit Is there a way to make it so cron only happens with the time? Right now it appears if I sign out then sign back in within the same day I take damage from incomplete dailies (before 00:00). If I understand the FAQ that's working as intended? Please advise.

@Alys Cron should happen only once a day and only when you use HabitRPG for the first time after your Day Start time (00:00 usually). Are you signing out of one computer and signing in to another one? If so, one the second one, you'll see a summary of all the changes to your stats since the last time you used that computer. So, for example, if you sign OUT of a work computer at 5pm, and then use HabitRPG at home that night and the next morning, and then later that morning sign back in at work, you'll be told at work about the health change that happened since 5pm the previous day. This doesn't mean that the health is being removed a second time; it just means you see the notification again.

Does that sound like it might explain what you are seeing?

@Jajbit no, my dailies are completely reset so even though 24 hrs have not passed any dailies that were complete are shown as not complete before 00:00. This causes me to take dmg from all dailies once the clock does change to 00:00, as well.

@Alys Did your Dailies reset the first time that you used HabitRPG today? Or was it after that?

@Jajbit after. now that it's 00:03 I can confirm the following: dailies reset and dmg dealt after signing in at work computer ~22:00, dmg dealt was too high (~39 to 10) (confirmed just now that all dailies, not just incomplete ones, would take me from 39 to 13), dmg dealt for all dailies (now reset to incomplete) at 00:00. also please note this is the third time it happened this way

@Jajbit streaks also reset at 22:00 (signing in from work computer). If I'm not mistaken this doesn't happen if I stay signed in at my home computer but I won't be able to confirm that until tomorrow

User ID: b09a0615-7abe-4041-9c0d-44bea5de7647
OS: Windows 7 (Home), Windows 8 (Work)
Browser: Chrome (Home), Chrome (Work)

**Comment by Amputatoes** [comment]
Left myself signed in at home computer and then logged into work computer to see if it would happen or not, the bug still happened so being logged in or out at home computer doesn't seem to have any effect. Tomorrow I'll not log in at work and advise

**Comment by Amputatoes** [comment]
Did not sign out from home computer and did not sign in at work computer and bug did not occur. I should also mention that I have been using the Android app between using home and work computer, I did this again while not signing in at work computer (using habitrpg at home computer, not signing out, using android app) the bug did not occur.

**Comment by Alys** [comment]
Do your home and work computers have different times set (even slightly different)? Or different timezones? If so, that could be causing cron to run twice in a day.

**Comment by Amputatoes** [comment]
Yes! my work computer's clock is wrong. Thank you for all your help, I think that fixing it should resolve the issue.

**Comment by Alys** [comment]
Great! I'll close this issue now, but do comment here if you need any more help! We'll still be notified of your comments and can reopen this if needed.
