### ISSUE TITLE
Bought 20 Tokens, Still Haven't Recieved

### ISSUE THREAD

**Issue by busterroni** [HabitRPG/habitica#492]
About 15 minutes ago I purchased 20 tokens ($5 value). I still haven't received them, is this a bug or does it take some time? 

Username: buster
User ID: 0eb129b6-db0c-4011-ae90-6ab4874eb296

Thanks,
busterroni

**Comment by ghost** [comment]
@busterroni sorry about that
@lefnire have you been able to replicate this bug?

**Comment by busterroni** [comment]
Sorry for the constant closing and opening, I accidentally clicked the close button and then I lagged :/

**Comment by lefnire** [comment]
I added tokens to your account, and I'm elevating this to critical. Sorry @busterroni !

**Comment by busterroni** [comment]
Thanks @lefnire , were you able to duplicate this? I think the problem might have been that I did it from my phone and it opened in a new tab, but the cookies should have saved, so I'm not sure if it was my side or a bug. I also had already bought a pet and should have had 21 tokens but you gave me 24 tokens. I would feel dishonest if I didn't tell you :P

**Comment by lefnire** [comment]
should be fixed now https://github.com/lefnire/habitrpg/commit/69c8d7835211e5fdc2959d148ce4ff5e44c208c8
