### ISSUE TITLE
Got March subcribers Items, but I did not renew my subscription

### ISSUE THREAD

**Issue by proxforge** [HabitRPG/habitica#4921]
Hello Guys,

I got March subcribers Items, but I did not renew my subscription. Thats my user-id: 
7374977d-317f-4764-9234-31c870977c48 I had a one-month subscription as I gift, but I did not renew for another month.

Best Greetings, johnny

**Comment by deilann** [comment]
When were you gifted your subscription?

If it was towards the end of last month, your subscription would still be
active.

**Comment by proxforge** [comment]
Today. My subscription ended on March the 25th. I even cant buy gems for 20 gold and so on ... I was gifted the subscription on february the 25th.

**Comment by deilann** [comment]
Sounds like you got the migration at the very end of your subscription!
Lucky you! Perfect timing. This is expected behavior. You were a subscriber
when the mystery gifts were given out, which was yesterday in the US.
