### ISSUE TITLE
Mobile not working?

### ISSUE THREAD

**Issue by cammi** [HabitRPG/habitica#4922]
No matter what I try, I can't log in on the mobile.

**Comment by paglias** [comment]
What do you mean by can't log in? Does it says your email/password combination is not valid?

You should check that you didn't signup via facebook.

Also could you give us your UUID (Settings->API) and if you're using iOS or Android?

**Comment by Alys** [comment]
I'm closing this but, @cammi if you're still having trouble, tell us the information @paglias asked about and we'll reopen it.
