### ISSUE TITLE
iOS issue - Syncing and Editing To-Dos

### ISSUE THREAD

**Issue by kevinritt1** [HabitRPG/habitica#4924]
I've noticed an issue with my iOS app, and it seems to be different than most of the ones I've seen elsewhere on here (sorry if I missed it!). My problem isn't with health or dailies, but with to-dos.

I've essentially stopped using my phone for the input, edit, or "checking off" of any to-dos, because the sync is inconsistent. Sometimes it works fine, but more often only the input function will work - I'll input a handful, edit them (checklists, difficulty etc), and check some off, but when I come back they will all be input in their original format (no checklist, easy difficulty) and any completed tasks will be back. It seems like the input gets cached, but any updates don't sync, so when I open up the app later it defaults to that original backup. It doesn't SEEM to happen with my dailies or habits, but I definitely use to-dos when I'm on the run more.

Additionally, whenever I edit a to-do, a subscript of "undefined" appears under that task. Lastly, when I manually "sync" my to-dos by pulling down and letting it refresh, the top "refresh" bar appears, but it's whited out, and generally doesn't disappear until I navigate away and come back to the to-do page. (IDK if these are related, just wanted to throw them out. Happy to send screenshots if you think it would be helpful)

Any ideas? I'm not worried about recovering anything, just want to know if there's a patch so I can use the app on my phone more. Thanks for any help - love the game!

User ID: 1fb5a397-c946-4469-98c8-842f46aa9a80
iOS - 8.1.3 (iPhone 5c)
Habit App version 0.0.48

**Comment by ModernHedonist** [comment]
Yes! I'm having this problem as well - or at least, I think it's the same. I lose my checklists created through the app.

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. You can install it at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if you have any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
