### ISSUE TITLE
Invite Friends totally non-responsive

### ISSUE THREAD

**Issue by berriganator** [HabitRPG/habitica#4927]
I tried to first invite my friend by email, but the dialogue box in both Firefox (36.0.4) & Chrome (41.0.2272.101) on Mac was completely unresponsive. Clicking the + did nothing, adding an existing user name (once she got it going by herself), also was unresponsive. The only responsive button in the window is "close". 

![screen shot 2015-03-26 at 10 34 08 pm](https://cloud.githubusercontent.com/assets/11406808/6857611/4dccfea6-d408-11e4-889e-b8158475e2bd.png)

**Comment by paglias** [comment]
@berriganator sorry about that. It was a guild or a party? Also, if it happens again in Chrome you should open the console (Ctrl+Shift+J) and report anything you see there

**Comment by berriganator** [comment]
Actually it was from the settings page. I got this in the console:

Given URL is not allowed by the Application configuration: One or more of
the given URLs is not allowed by the App's settings.  It must match the
Website URL or Canvas URL, or the domain must be a subdomain of one of the
App's domains.

I don't know if that's relevant at all.

When I went to the party page instead and tried to invite there, the
username didn't work (user not found), but the email invitation did work.

Thanks!

**Comment by deilann** [comment]
username won't ever work -- it's asking for User ID, not username, which is
a long character string.

Where in settings did you find an invite button? The invite buttons are
pretty much for guilds and parties, so I don't think one is meant to be
there. If so, we should probably get rid of it!

**Comment by berriganator** [comment]
Aha. Thank you for the clarification on User ID / username.

This is where it is in settings. Again, the email here didn't work either. Thanks!

![screen shot 2015-03-26 at 11 08 23 pm](https://cloud.githubusercontent.com/assets/11406808/6858249/40822a78-d40d-11e4-9a07-f7590c913c99.png)

**Comment by paglias** [comment]
Ohh I didn't know about that Invite friends! Thanks for the report, I'll
fix it in the coming days
Il 26/mar/2015 23:10 "Caitlin Berrigan" notifications@github.com ha
scritto:

**Comment by berriganator** [comment]
Thanks!

**Comment by paglias** [comment]
I've opted to remove that button. It requires a party to work and in that case there's the invite feature in the party page that works exactly the same, also a new way to invite friends from the home page is going to be added soon.
