### ISSUE TITLE
Completing Daily - Gold count wrong

### ISSUE THREAD

**Issue by geekeasy** [HabitRPG/habitica#4928]
When I complete a daily task the amount of gold I'm rewarded it obviously wrong.  I was just rewarded 70 gold for clicking off a daily task, according to the text boxes which temporarily pop-up.   Perhaps it's the total amount of gold which has been given for the history of this daily task?

And this issue is repeatable every time I check one off.

UserID:  b95b417c-d969-4347-b142-c9c6193a1d4d
OSX 10.9.5
Safari 7.1.4

![70_gold](https://cloud.githubusercontent.com/assets/889825/6857629/696d8f88-d3c5-11e4-83e2-4f0b5156f95d.jpg)

**Comment by deilann** [comment]
That's 70 _silver_ or .7 gold. No worries. :)

**Comment by geekeasy** [comment]
Ah ha.  Thank you.

But I wonder if other people are confused by this too.

Might a color change help, such that a reward of silver does not show up in a gold color bar?

**Comment by deilann** [comment]
I don't think other people are confused by this. This is the first time I've seen this confusion in over 2 years. The amount is clearly next to a piece of silver. Changing the growl logic so when a reward is less than 1 seems like it wouldn't be worth it.
