### ISSUE TITLE
Suggestion: To-Do progress graph

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#493]
My To-Do progress graph has been plummeting downwards, probably because I added many more to-do items than I finished. Since this is the thing that will happen when starting out with Habit, and probably something that will occur from time to time when a new batch of tasks comes up, would it be possible to not factor in the number of unresolved items, but maybe just the ones fulfilled? Maybe with more progress shown on the graph for the higher-ticket items that gave more XP and Gold? 

This might tie in nicely with the cumulative XP/Gold view that someone also requested, I think. (Plus my graph would look much less frustrating ; ) which would also be nice.)

**Comment by horusofoz** [comment]
I feel your pain man.

![Image 13](https://f.cloud.github.com/assets/3202339/200003/97acaa62-80b3-11e2-9b0a-15cf0501c275.png)

Unfortunately this is the way it will be kept as it is an accurate display of progress. When we introduce the On Hold option it should help to balance things out a bit more.

**Comment by wildcate** [comment]
If only it would look so good on my graph...
![unprogress](https://f.cloud.github.com/assets/3587347/200493/81619ba8-80c9-11e2-97ca-d4a12c74231a.png)

**Comment by horusofoz** [comment]
At least your on the rise? ;)

**Comment by wildcate** [comment]
I actually have a backlist that is not on the list yet - I can't sort stuff and it's getting too confusing otherwise. So that's just a short spike  : )

How is that graph made? Does it really take the number of items added vs. number of items removed? If so, how come you get back to or above zero while I did not?

**Comment by horusofoz** [comment]
Not sure but detailed info can be found here -
https://github.com/lefnire/habitrpg/wiki/Algorithms

**Comment by wildcate** [comment]
I couldn't find details for the todo progress graph, neither there nor on the page linked...

**Comment by horusofoz** [comment]
@lefnire Could you advise?
_Horusofoz_
*
*
"Live to learn. Learn to live." J.W.S.

**Comment by lefnire** [comment]
it's the total value of the todos for that day. A todo value is what determines it's color, if it's red it has negative value, if it's green it has positive value.

**Comment by wildcate** [comment]
The todos plus dailies and habits? (The fresh to-dos on my list are sort of light orange already, not green.) So if I have very few todos, but many green dailies, I'm in the positive but with lots of to-dos it will be always in the negative, right?
I'm not sure if this type of graphing will be very helpful to me, maybe over time if I get to a less red and less long list (though I sort of doubt that will happen). Does a fresh to-do count as positive, negative, or neutral? 

From the position of the graph I would have expected that it only refers to the to-dos, not the overall progress, especially since the habits (actually) and the dailies (once the bug will be gone) all have their own little progress graphs.
