### ISSUE TITLE
can't unsubscribe from mailing list

### ISSUE THREAD

**Issue by hambailey** [HabitRPG/habitica#4937]
Email received. Clicked "here" to unsubscribe using galaxy note 2. Took me to home page. Didn't see option on site anywhere.

**Comment by paglias** [comment]
You can unsubscribe from Settings -> Notifications
Il 28/mar/2015 17:14 "hambailey" notifications@github.com ha scritto:

**Comment by lemoness** [comment]
Hm - I assume it leads to the homepage instead of the notifications page if
you're not signed in. Is there a way to show the notifications page even if
you aren't signed in?
