### ISSUE TITLE
Dailies not greyed out when inactive

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#494]
Probably not urgent, but confusing: I have a list of dailies that are inactive on the weekend, but three of them are not greyed out on Sat and Sun; it works fine for the others. I'm not sure whether they will also dock points (I'll try to see if they did that tomorrow).

And on a site note concerning dailies as well: It is possible to mark a daily as "done" even when greyed out and to receive gold and XP for it. Is that on purpose? Or a glitch/bug? IMO there's no harm in being able to perform a daily on a day that it's not due in addition to the normal times and get rewarded for it but you should probably be aware of that in case you weren't already.

**Comment by wildcate** [comment]
They did dock HP - I just checked. Good thing I have not bought stuff I cannot afford ;-)

**Comment by wc8** [comment]
> I have a list of dailies that are inactive on the weekend, but three of them are not greyed out on Sat and Sun; it works fine for the others.

The grey color indicates the system considers them inactive. If it's not seeing them as inactive, they're going to dock points. Are you saying you set them to inactive and it didn't take?

Re: able to mark grey task as done. I can't speak for the developer, but in IMO, that's a feature. That way I can have a task on my list that I'd like to do, but might not have time for. If I get to it, good and I get points. If I don't, well, it doesn't matter, I didn't have to do it, no HP loss.

**Comment by wildcate** [comment]
Yes, that's exactly what happened - I set them inactive, but they still colour as active. At least one of them (I don't remember the others, have to wait until next weekend) is one of the original entries there upon sign-up - I just changed title and active days.

**Comment by wildcate** [comment]
It's weekend! All three dailys that are not greyed out as they should be are the three pre-made ones from starting Habit, where I changed the text and active days instead of deleting them and adding my own new ones.

**Comment by Pandoro** [comment]
@wildcate  can you confirm that this only happens with these 3 dailies? 

I noted this before and also reported it in #285 

It would be very good on one hand, because I think this would seriously make the problem by far easier to fix. 

In your case, what you can do is toggle the tasks for all the days, so turn them on and off / off and on again. This should fix it I think. The initial 3 todos simply seem to be broken :X

**Comment by wildcate** [comment]
@Pandoro Yes, it's only these three dailies. I tried the toggling thing, and they are all grey now. I'd never have thought of that for fixing it, thanks!

**Comment by Pandoro** [comment]
Glad you could fix it for yourself now. @lefnire  explained to me why this is happening. It should be an easy fix. I will list this as critical to make sure no more confusion happens as soon as possible.

@lefnire Did you fix it as you said yesterday evening? If so you can close this maybe :)

**Comment by lefnire** [comment]
last night I fixed the case where the _default tasks_ have broken day selectors (you have to toggle off, on, off the first time for the day toggle to work). So default tasks are fixed now (will go out with the next push), just want to make sure none of this ticket applies to any _new_ tasks people added?

**Comment by Pandoro** [comment]
Well according to the last comment of @wildcate, it only applies to these three tasks.

**Comment by horusofoz** [comment]
@wildcate Is this still an issue?

**Comment by wildcate** [comment]
Since I repaired mine as per the instructions further up - no. And lefnire said that he fixed the broken default selectors - so I think this can be closed.
