### ISSUE TITLE
Avatar Broken on iOS 7

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4942]
In the menu of the mobile app, the avatar is completely missing, although it displays under profile.

No avatar on:

iPhone 5, iOS 7.1.1
iPhone 5S on iOS7

Avatar DOES work on:

iPhone 5S on iOS 8

Based on this, it may be an issue with iOS 7.

**Comment by AnitaYCheng** [comment]
I have iOS7 on an iPhone5S and this is what it looks like. My username will appear in flashes occasionally, but that's it:

![photo 1](https://cloud.githubusercontent.com/assets/6760632/6890714/6c520d12-d665-11e4-9aea-9734d917f997.PNG)

It shows up fine on the profile screen:
![photo 2](https://cloud.githubusercontent.com/assets/6760632/6890715/72d147f2-d665-11e4-8c59-ab9025b78a43.PNG)

**Comment by lemoness** [comment]
My username also flashes occasionally.

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
