### ISSUE TITLE
ToDo list keeps reordering, won't leave some tasks at the top

### ISSUE THREAD

**Issue by ModernHedonist** [HabitRPG/habitica#4944]
It may be related to challenges - things just won't stay at the top and other todos jump to the top randomly.

**Comment by Alys** [comment]
Please see this issue for a workaround and to follow the progress of this bug: [To-Do List isn't saving the sort order [$56] - Issue #2606](https://github.com/HabitRPG/habitrpg/issues/2606)

Let us know if you still have problems. You can comment here even though this issue will be closed.
