### ISSUE TITLE
Unable to reorder tags.

### ISSUE THREAD

**Issue by deertheory** [HabitRPG/habitica#4945]
When I go to drag a tag from where it is to somewhere else in the tag cloud/list, the site does not seem to acknowledge where my mouse is when considering where to drop the tag. With that said, I have about 3 rows of tags and am unable to place any in the top row at all when reordering. I have tried on  Chrome and Firefox. Is the solution here to simply delete and remake my tags and re-tag existing to-do items?

**Comment by Alys** [comment]
I don't recommend deleting and remaking them - it will be a lot of work. There's at least a couple of other options.

First, try zooming out using your browser's zoom function (Vew menu probably, at least in Firefox). If you can make the tags as small as possible while still being able to recognise them, they might take up fewer lines and be easier to move. Also expand your browser to full screen, if it is not already.

**Comment by deertheory** [comment]
Thanks for the recommendation. I am currently at work and will try tomorrow
and report back.

**Comment by TheHollidayInn** [comment]
Hello,

I can't exactly replicate the issue. I have added 3 rows worth of tags, and (with some maneuvering) I am able to reorder the tags. I'm going to see if I can make the reordering smoother by fixing the drag and drop.

Can you provide any more information to help me recreate the issue?
--Does the browser show that you are dragging a tag?
--Do other tags seems to wiggle when you are dragging a tag?
--Can you provide a screen shot?
--Anything else?

Thank you!

**Comment by Alys** [comment]
@deertheory The change that we believe has fixed this is now live on the HabitRPG site. Can you please tell us whether you are still having trouble sorting your tags or not?
