### ISSUE TITLE
Play Now button (Mobile view)

### ISSUE THREAD

**Issue by Lorddan** [HabitRPG/habitica#4947]
The main "Play Now" button on the HabitRPG home page rather then read the word's "Play Now", it reads 

{{chosenVariation==1 ? "Play Now - It's Free!" : chosenVariation==2 ? "Start" : "Play"}}

This is breaking the width of the page, 

button.btn.btn-primary.btn-lg#frontpage-play-button(ng-click='playButtonClick()')
24            | {{chosenVariation==1 ? "Play Now - It's Free!" : chosenVariation==2 ? "Start" : "#{env.t('playButton')}"}}

If the problem is what i think it is this will be obvious at a glance.

**Comment by lemoness** [comment]
Attention @lefnire!

**Comment by lemoness** [comment]
Here's a screenshot.
![unnamed-5](https://cloud.githubusercontent.com/assets/3494081/6907240/63954692-d6e9-11e4-869b-4ac59f4280c0.png)

**Comment by lefnire** [comment]
No idea what's going on here, I can't replicate on my devices and the following code checks out just fine: `chosenVariation = Math.floor(Math.random()*3);chosenVariation==1 ? "Play Now - It's Free!" : chosenVariation==2 ? "Start" : "Play"`. @lemoness there's no winner/looser anyway, can we just kick this A/B?
