### ISSUE TITLE
Fix Fortitude Potion Art

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#4952]
The art was slightly wonky for the fortitude potion, so @uncommoncriminal fixed it up.
![fortitudepotion_by_cosmic_caterpillar-d8nu1t4](https://cloud.githubusercontent.com/assets/3494081/6955664/393e37b0-d896-11e4-90e1-4b7012345fc4.png)

**Comment by TheHollidayInn** [comment]
Are the dimensions supposed to changed to 21 x 30 rather than the 54 x 57? If so, I can adjust this. I just wanted to make sure before I changed the css.
