### ISSUE TITLE
Cannot Complete Newbie Tour due to Training Sword Already Purchased

### ISSUE THREAD

**Issue by dmaurice001** [HabitRPG/habitica#4953]
- I used the HabitRPG android app to create an account.  I purchased the training sword in the app.
- I logged into the HabitRPG website, and use the website to reset my account
- The newbie tour began, but it cannot proceed past step 8 "To proceed, buy the Training Sword with the gold you just earned!"
- The Training Sword is in my inventory.  The Training Sword does not appear in the list of purchasable items.
- I can work around this by reloading the webpage and making sure not to click the "Continue Tour" icon (a small avatar face at the top right of the screen).  Not a huge problem, afaik, but thought I'd mention it.

User ID
58165e52-450b-4560-8efa-4b728f3c1668

**Comment by lemoness** [comment]
@dmaurice - You can buy any item or the healing potion to proceed past that
step. If you don't have enough gold yet, click ESC to minimize the tour.

**Comment by Alys** [comment]
@dmaurice001 Thanks for reporting this! Another workaround is to buy any other piece of equipment, or the health potion. You might wish to go to Settings -> Site -> Fix Character Values to give yourself the gold needed for a health potion, and then restart the tour and buy the potion, so that you can get rid of the Continue Tour icon. You should be fairly close to the end of the tour and I don't think there's any other accidental traps in it after this one.

**Comment by crookedneighbor** [comment]
We should have the logic check if the user has the training sword in the inventory.

**Comment by lemoness** [comment]
That would be helpful. I'd actually like it so that app users don't get
that same initial tutorial at all.

**Comment by TrevorBrennan** [comment]
Hello,

There is a similar issue with completing the default task in the app. The task will be removed, but, when you log into the website, the tutorial will ask you to check it off.

A work around is to create a new task and check that off. Unfortunately, the tutorial on how to add tasks/Habits/Dailies is later in the tutorial, so players might not know how to do that yet.

Android Device Version: 21.44.12.en.US
Android App: HabitRPG version 0.0.51

Computer OS: Windows 8.1
Chrome Version 41.0.2272.118 m

User Id: f75e36b3-3df3-4dc5-9f9a-b6122fe045eb

**Comment by Alys** [comment]
We've changed the tutorial since this was reported so I'm closing this but it can be reopened if the problem still exists (I believe it doesn't).
