### ISSUE TITLE
Just "magically" jumped 5 levels

### ISSUE THREAD

**Issue by geekeasy** [HabitRPG/habitica#4955]
I'm not sure if this is the "sync bug" or something else, but I somehow just jumped up 5 levels from level 12 to level 17. 

I ended up with duplicate todos.  I deleted both of them.  I recreated the todo.  

Then, somehow, I had jumped to level 17.  

I saved the xml and json files if some of the info in there will help track down this problem.
##

**Comment by geekeasy** [comment]
Sorry, I forgot my user id:  b95b417c-d969-4347-b142-c9c6193a1d4d

**Comment by paglias** [comment]
Reopen if it happens again
