### ISSUE TITLE
Can't get rid of Daily 

### ISSUE THREAD

**Issue by ShibbyBiscuits** [HabitRPG/habitica#4959]
I have a daily that was from a challenge I did about a year ago. Now that I've re-started using HabitRPG, I got rid of the challenge since it was no longer pertinent, but I can't get rid of the accompanying daily task. There is no trash button, and no option to delete the daily. I use the lastest version of Chrome on a Windows 7 computer.

**Comment by Alys** [comment]
There's a list of steps you can follow at [Challenges : Deleting a Challenge Task](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task). Go through them in order until one works, and then let us know if you've tried them all and you still can't delete the task.

**Comment by ShibbyBiscuits** [comment]
Thank you! That does appear to work.

**Comment by Alys** [comment]
Thanks for letting us know! :)
