### ISSUE TITLE
Feature Request: allow dailies to be required N times per week rather than just specific days

### ISSUE THREAD

**Issue by thewoolleyman** [HabitRPG/habitica#496]
Hi,

Thanks for habitrpg.

One issue I have is having to complete dailies on an exact day.  I would like to have a setting where I could specify I must complete a daily N times per week.

For example, I try to write a journal entry for every day, but because of travel or other issues I don't actually write it every day (or log on to habitRPG every day).

So, I'd like to be able to say "I will write in my journal 4 times per week", and as long as I check off that entry four times in a week (e.g. Mon-Sun), I would get credit for "Perfect".

-- Chad

**Comment by StanLindsey** [comment]
This is the top voted feature on our Trello board. [Vote for it here](https://trello.com/c/XuVokK2V)

=D
