### ISSUE TITLE
Api issue "Cannot call method 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by MagicMicky** [HabitRPG/habitica#4962]
I'm having an issue while trying to use habitrpg.com's API. Note that it doesn't happen on the beta api.

`curl -v --compressed -H "Accept-Encoding: gzip" https://habitrpg.com/api/v1/status` is returning a
`{"err":"Cannot call method 'toLowerCase' of undefined"}`

whereas  `curl -v --compressed -H "Accept-Encoding: gzip" https://beta.habitrpg.com/api/v1/status` returns `{"status":"up"}`

**Comment by eshapard** [comment]
I'm having this issue as well using the version 2 api.
My curl command is:
<code>
curl -X GET --compressed -H "Content-Type:application/json" -H "x-apt-key:....." -H "x-apt-user:....." https://habitrpg.com/api/v2/user/tasks
</code>
All calls to the API v1 and v2, so far give me:
<code>
{"err":"Cannot call method 'toLowerCase' of undefined"}
</code>

I noticed this problem today (April 2, 2015)

Tried beta.habitrpg.com and it works fine.

**Comment by crookedneighbor** [comment]
@paglias fixed this, but I don't believe it has been deployed yet. Could someone do a production deploy so we can close this issue?

**Comment by crookedneighbor** [comment]
Should be fixed now. @maggick Can you confirm for me?

**Comment by lemoness** [comment]
Pinging @lefnire!

**Comment by paglias** [comment]
I've just tried and it's fixed. Sorry about this @MagicMicky @eshapard

**Comment by maggick** [comment]
Wrong nick @crookedneighbor ;)

**Comment by crookedneighbor** [comment]
Whoops. Sorry!
