### ISSUE TITLE
Dailies repeat "1" vs "true"

### ISSUE THREAD

**Issue by MagicMicky** [HabitRPG/habitica#4964]
It seems that there is two kind of dailies in the database, that can cause parsing issues.
When you get your list of tasks, dailies have a repeat full of Boolean, whereas when you create a daily (without setting days for it), the array is filled with Integer.

**Posting a Daily**
`curl -X POST -d @/tmp/created.json -H "x-api-user:MyApiUser" -H "x-api-key:MyApiKey" --compressed -H "Content-Type:application/json" https://beta.habitrpg.com:443/api/v2/user/tasks`

with /tmp/created.json = `{ "type": "daily", "text": "test"}`
You get a daily with a repeat full of integer :

``` json
{
"type":"daily",
"text":"test",
"id":"3c99db78-d677-499d-a37c-36999c9857db",
"dateCreated":"2015-04-03T06:50:49.345Z",
"repeat":{"su":1,"m":1,"t":1,"w":1,"th":1,"f":1,"s":1},
}
```

**In the User's tasks**

``` json
  {
    "text": "test",
    "dateCreated": "2015-04-03T06:26:44.440Z",
    "id": "7f16c5a8-e3af-4859-b96f-3bbe7b79b9fd",
    "repeat": {"su": true, "th": true,  "s": true, "f": true,  "th": true, "w": true, "t": true,  "m": true},
    "type": "daily"
  }
```
##

**Comment by paglias** [comment]
Fixed in v3
