### ISSUE TITLE
Shiny seed count does not appear on the reward column after 100.

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4966]
After buying a few (102 at this moment) shiny seeds, I found out that the total count does not appear on the reward column:
![canvas](https://cloud.githubusercontent.com/assets/4882150/6981550/9ffb3656-da03-11e4-8bab-aee9cc57ac82.png)
This behavior was reproduced on Firefox (Ubuntu) and Safari (Mac OSX).
Using a few of them and going below 100 does make the total count appear.
Also, it seems to me that the Shiny seed icon is attached to the bottom of the box, while all other items are centered.

**Comment by crookedneighbor** [comment]
The shiny seed sprite is 40px by 40px. It needs to be 32px by 32px to match the snowball and spooky sparkles so it'll be aligned correctly. I should be able to fix it at the end of the week, but @SabreCat, if you want to take care of it before then, feel free.
