### ISSUE TITLE
Burst of Flames Experience does not Level Up Character

### ISSUE THREAD

**Issue by cbleisch** [HabitRPG/habitica#4970]
**User ID:** e8461e47-7a1c-4cb3-b103-0f09472f6cde
**Browser:** Google Chrome (version: 41.0.2272.101 m)
**OS:** Windows 8.1 Pro, 64-bit

When I cast Burst of Flames on one of my Dailies it provided enough experience that my character should have leveled up. Instead, my experience is at 687/640 and I did not gain a level.

![burst of flames bug](https://cloud.githubusercontent.com/assets/1851792/6982605/d830300c-d9e1-11e4-8f43-ca935f1668c8.PNG)

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/2143 for a previous report of this issue and a fix.
