### ISSUE TITLE
Offline Access

### ISSUE THREAD

**Issue by cyotee** [HabitRPG/habitica#4971]
The one thing that keeps me from switching to HabitRPG entirely is the lack of offline access. Like in Wunderlist. Whether done through a seperate application, or within the browser doesn't matter. Just some way to use HabitRPG as my TODO list while offline.

**Comment by Alys** [comment]
This is really more a feature request than a bug report. You might like to go to Help -> Request a Feature to suggest it there or vote on it if it has already been suggested. That will allow the idea to be considered in the context of all other requested features and then plans made for implementation in the most appropriate way.

**Comment by paglias** [comment]
Anyway the mobile app fan be used offline. Also the site, you just need an
internet connection to load it the first time
Il 03/apr/2015 22:26 "Alys" notifications@github.com ha scritto:

**Comment by cyotee** [comment]
No, the mobile can't be used offline. If you try it gives you an error. Don't lie.
