### ISSUE TITLE
(WEB) String error in czech version

### ISSUE THREAD

**Issue by Rohlik** [HabitRPG/habitica#4984]
Hi there!
I found a error in my stable today :)
This error is show after mouseover on slot. It does not matter whether empty or tame.
I´m using last version of Chrome.
![string error](https://cloud.githubusercontent.com/assets/2051154/7005293/f6d4d944-dc76-11e4-9281-1e21f906b56b.png)

**Comment by Alys** [comment]
Did you try reloading the page? I suspect your browser just doesn't have the latest code. Please try that if you haven't already. If it is still happening, please tell us which language the website is using (the name of the language as it appears in the drop-down list of languages in the [Settings -> Site screen](https://habitrpg.com/#/options/settings/settings)).

**Comment by crookedneighbor** [comment]
The issue title says Czech.

**Comment by Alys** [comment]
Yes but "Czech" doesn't appear in the drop-down list. I don't know the language's own name for the language.

**Comment by paglias** [comment]
It's Čeština @Alys from the screenshot do you understand which string is it?

2015-04-07 18:04 GMT+02:00 Alys notifications@github.com:

> Yes but "Czech" doesn't appear in the drop-down list. I don't know the
> language's own name for the language.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4984#issuecomment-90622200.

## 

Matteo Pagliazzi - paglias.net

**Comment by Alys** [comment]
It's the Egg-CottonCandyPink mount.

**Comment by Alys** [comment]
Confirmed on my account using that language, for several other species of mount as well.

**Comment by Rohlik** [comment]
Reload with deleted cache don't fix my problem :(
In my case this error occur on all mount, not only Egg-Cotton Candy Pink.
I can confirm Czech = Čeština.

**Comment by paglias** [comment]
Fixed, will go live in a few days

**Comment by Rohlik** [comment]
Confirm!
