### ISSUE TITLE
Party Army bug

### ISSUE THREAD

**Issue by jlriddell** [HabitRPG/habitica#499]
I had accepted a party invite from my boyfriend, and found I wasn't displaying on his status bar (I know it's a bug now, but didn't realize it at the time). We thought that if I added him to the party, it might fix it. Instead... we found a bug.

![Screen Shot 2013-02-23 at 10 54 32 PM](https://f.cloud.github.com/assets/3612559/189187/00a79320-7e51-11e2-98d0-3971249ea478.png)

Steps to reproduce:
Be invited to a party and accept.
Copying the inviter's (or any existing member?) user ID, paste and enter it into the invite field.
Ignore the error message and keep entering.

Viola, you've created an army and can't see the tops of your lists.

---Edit---
A refresh will fix it, but it's still interesting.

**Comment by wc8** [comment]
I'm listing this as minor since a refresh will fix it. Thanks for following up.

**Comment by horusofoz** [comment]
@jlriddell Is this still an issue with the changes introduced since you posted this bug?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
