### ISSUE TITLE
iOS app to-do list "undefined"

### ISSUE THREAD

**Issue by TyranoTank** [HabitRPG/habitica#4999]
when editing details on your to-do list if you do not select a due date the to-do item will say "undefined". If you enter editing again and back out it will assign the due date for as far back as the rolling date selector will allow. The first issue is merely annoying, the second issue could cause some harm if I missed a to-do item for 50 years...

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
