### ISSUE TITLE
HabitRPG API on checklists: possible bug or missing docs?

### ISSUE THREAD

**Issue by cra** [HabitRPG/habitica#5004]
My user id: d6cc0b1b-f48f-4596-9b06-f54d7f169019

I want to use [Python-Requests](http://docs.python-requests.org/) and HabitRPG API to tick a specific checklist item of my daily vitamins intake habit. I found out the dict which I'm supposed to send, using [API tool](https://habitrpg.com/static/api#!/user/user_tasks_id_GET).

Here's the exact dict:
![api-test](https://cloud.githubusercontent.com/assets/408698/7071505/08b474b4-dee6-11e4-9066-51acf49ae90d.png)

Apparently, it won't work when I try to use the [simple script I wrote](https://gist.github.com/cra/49469df2aa43df226d5a)

I suspect that this might be a python json convertation issue, but it took me a while to find out how am I supposed to work with checklists. Is there an easier way? Shouldn't I be able to just access the specific checklist item by it's id? If that's true, there is no mention of that in the docs
##

**Comment by cra** [comment]
I managed to make it work with [httpie](https://github.com/jakubroztocil/httpie):

<pre>
echo '{
    "checklist": [
        {
            "text":"Vitamin D",
            "id":"'${id_vitam_d}'",
            "completed":'${vitam_d}'
        },
        {
            "text":"MultiVitamin",
            "id":"'${id_multi_v}'",
            "completed":'${multi_v}'
        },
        {
            "text":"FishOil",
            "id":"'${id_fishoil}'",
            "completed":'${fishoil}'
        }
    ]
}' | http PUT ${TASKS_URL}/${VITAMINS_TASKID} x-api-user:${USER} x-api-key:${TOKEN}
</pre>

I'm still battling the pythonic part though. I still believe the part on checklists should be in the docs.

**Comment by Alys** [comment]
@cra I'm sorry we haven't responded about this yet. We are interested in improving the API.

If I understand correctly, you're requesting a new API route for updating a single checklist item in one task - is that right? You'd supply the task ID and the checklist ID. Would you want the route to allow you to change the checklist item's text, or to mark the checklist item as completed/uncompleted? Or a route for each separately?

**Comment by cra** [comment]
Hi! Thanks you for responding!

Just so you understand my intentions better: my goal is to have a set of buttons (real-world physical buttons) next to my box with vitamins so I could press them when I take the pills. Just for fun.

I would greatly benefit from an additional API route for checking (even "unchecking" is not necessary for me). Aside from that, an easy way to query a specific checklist for completion would be nice.

I doubt that I would ever use API for editing the checklist item's text (or even creating a new one).

**Comment by deilann** [comment]
mmmph now I want to make and market Habit routed pill minders.

**Comment by Alys** [comment]
Habitica's API has been updated to version 3 and it includes better support for checklists. Documentation is at https://habitica.com/apidoc/
