### ISSUE TITLE
I can't join the party quest

### ISSUE THREAD

**Issue by mauvedragon** [HabitRPG/habitica#5009]
I can't join the latest party quest. I don't recall pressing the decline button. I run the app on my Ipad. as well as using the website on Chrome on the Ipad, and the website on Mozilla on laptop (running Windows 7).

179ade8e-bbff-4c17-aa56-d54acc97d319

**Comment by Alys** [comment]
The quest owner might have started the quest before you had a chance to accept it. Go to your party page on the website (Social -> Party) and then reload the page using your browser's refresh button. Look at the quest box on the left-hand side of the page. It will have either a list of invited people with their accept/deny status (if the quest has not started), or it will show the quest as being active and will have a list of people who are participating in the quest.

If the quest has been started without you, the quest owner can, if they wish to, cancel the quest. The quest scroll will go back into their inventory for them to reuse to start the quest again.
