### ISSUE TITLE
Click-and-drag kills the ability to rearrange tasks

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#501]
If I load up HabitRPG and don't click anywhere, task rearrangement can still work.

If I load up HabitRPG and click without moving the mouse cursor even a pixel (I can do that on a trackpad), task rearrangement can still work.

If I load up HabitRPG and click anywhere other than a task (including on a blank area of the page) and move the mouse even a few pixels (i.e., I appear to click and drag), task rearrangement _no longer works_ until I reload the page. From then on, the mouse cursor acts as a text-selector only when dragging even though it properly changes appearance to the four-arrowed move cursor.

If it's important for this issue, I'm on Chrome 25.0.1364.97 m (Windows 7, 64-bit), though it happened with Chrome 24 as well.

**Comment by Olathe** [comment]
This appears to be intermittent. Sometimes it can still work. I'll investigate it a little.

**Comment by Laflamme** [comment]
I have the same problem on OSX 10.8.2 running Safari 6.0.2

**Comment by wc8** [comment]
This is probably related to #324.

**Comment by Olathe** [comment]
Good find. I'll close this issue since it seems to be the same as #324.
