### ISSUE TITLE
Can't log in on iOS app

### ISSUE THREAD

**Issue by agno33** [HabitRPG/habitica#5010]
I cannot log in on the mobile app, I have tried my email address and user ID.

**Comment by Alys** [comment]
Please try your user name rather than your user ID or email address. You can find out what your user name is from the website at [Settings -> Site](https://habitrpg.com/#/options/settings/settings).  Note that if you register with Facebook, then user name and password will not work and you'll need to use the Facebook option for logging in. If you no longer want to use Facebook to log in, you can change that also under Settings -> Site.

**Comment by agno33** [comment]
I changed my password and for some reason that worked.

On Fri, Apr 10, 2015 at 7:29 PM, Alys notifications@github.com wrote:

> Please try your user name rather than your user ID or email address. You
> can find out what your user name is from the website at Settings -> Site
> https://habitrpg.com/#/options/settings/settings. Note that if you
> register with Facebook, then user name and password will not work and
> you'll need to use the Facebook option for logging in. If you no longer
> want to use Facebook to log in, you can change that also under Settings ->
> Site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5010#issuecomment-91728555.

## 

Amy Duthler

**Comment by crookedneighbor** [comment]
Glad to hear you were able to log in.

**Comment by baekhesten** [comment]
I am having the same issue, but changing my password did not work. I have tried rebooting the phone as well, which didn't work either. When I try to login, I get an "ERROR 404" message. Here's a screenshot:

![img_0056](https://cloud.githubusercontent.com/assets/11915245/7107565/3c05cf76-e12e-11e4-83c8-8c620a05bdfd.PNG)

I am on an iPhone 4s using iOS 8.3. My User ID is 917fc8c1-1f95-4f97-b7e1-356951617517.

**Comment by paglias** [comment]
From the screenshot it doesn't seem the official HabitRPG app
Il 12/apr/2015 23:09, "baekhesten" notifications@github.com ha scritto:

**Comment by baekhesten** [comment]
I am not sure what else it would be as it's the only HabitRPG app in the App Store, and was created by OCDevel?

**Comment by paglias** [comment]
Then it's that, sorry but I just tried on my Android and the login is
different (the app is the same on iOS and android). Can you look in the app
store which version is it?
Il 12/apr/2015 23:19, "baekhesten" notifications@github.com ha scritto:

**Comment by baekhesten** [comment]
It's version 0.0.53
