### ISSUE TITLE
Stronger visual reminders for streaks

### ISSUE THREAD

**Issue by SirFreedomlancealot** [HabitRPG/habitica#5011]
I've always thought this was needed. I read this article recently which covers why very nicely.

http://jamesclear.com/paper-clips?__s=gqis25ue4bugkgxqf19o

**Comment by lemoness** [comment]
I agree that this would be nice! However, it's a feature request, not a bug report, so until we're ready to implement it, please list it on this Trello card: https://trello.com/c/q7uM2Ymq/92-dailies-v-3-dailies-minimum-does-not-apply-button-weekly-rolling-over-streak-history

Sorry for the confusion!
