### ISSUE TITLE
I have -1 Shiny Seeds

### ISSUE THREAD

**Issue by melissamcewen** [HabitRPG/habitica#5014]
Died last night and at the time I was a flower and also had 1 shiny seed in my inventory. Now I have -1 shiny seeds. 
![habitrpg___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/1251094/7101927/d19a97d8-e034-11e4-8fc6-a8c631866e6c.jpg)

**Comment by Alys** [comment]
If you would like us to fix this, tell us your user ID from Settings -> API. 

`whispers` But you might not want us to fix this. Try casting the seed on yourself or a party member....

**Comment by melissamcewen** [comment]
Hahaha, I changed my entire party and now I have -6 seeds
![habitrpg___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/1251094/7107282/60730a02-e126-11e4-8a9a-79a00a8bd14a.jpg)
