### ISSUE TITLE
copying a Challenge is now harder - need clone challenge feature

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5017]
With recent changes to how challenges work, it is now possible to view only one challenge at a time - this makes it easier to see a challenge, but harder to create a new one by copy-pasting from an old one. E.g., on an iPad, you can't reliably have two challenges open in different tabs or browsers because focussing on one often causes it to reload (discarding all changes you have made).

The ideal solution for this would be a feature allowing you to clone an existing challenge. The new challenge would have all the same attributes as the old one (including tasks) but all attributes would be editable (choose a new guild, new gem price, etc). This would be beneficial for many people, not just iPad users, because it's common to have challenges that repeat regularly.

I'm not sure how easy it would be to allow a new guild to be chosen for the cloned challenge. If it's not simple, then that feature could be implemented in a second stage or not at all.

I would suggest that you should be able to clone any challenge, even ones that you did not create. If anyone disagrees with this, comment here.

**Comment by deilann** [comment]
+1

**Comment by Dewines** [comment]
I've been running a monthly challenge for a while now and what I do is have all the challenge explanatory text and the details of the habits, dailies and To-Dos saved in a Word document. This is OK as a workaround, but being able to clone the challenge and simply edit details would be so much easier.

**Comment by ghost** [comment]
Cloning a challenge would be awesome. I have at least five challenges that repeat and being able to clone them would be so useful.

**Comment by beffymaroo** [comment]
Another +1 !

**Comment by lemoness** [comment]
I would love this ability. It would make it so much easier to run recurring
Challenges!
