### ISSUE TITLE
Rearranging the ToDo list does not load properly / Cannot read property 'shortcut'

### ISSUE THREAD

**Issue by Phonox** [HabitRPG/habitica#5018]
FROM THE CHROME CONSOLE:
2 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'shortcut' of undefined
    at chrome-extension://faminaibgiklngmfpfbhmokfmnglamcm/script/script.js:3:9extensions::uncaught_exception_handler:8 handlerextensions::uncaught_exception_handler:100 exports.handleextensions::event_bindings:384 EventImpl.dispatch_extensions::event_bindings:401 EventImpl.dispatchextensions::SafeBuiltins:19 target.(anonymous function)extensions::utils:94 $Array.forEach.publicClass.(anonymous function)extensions::messaging:316 dispatchOnMessage

WHAT I DO
- I rearrange my ToDo list. As I haven't Prioritized right from start or lots of new things got added in the process. (Most of my things are rather red right now)
- I now refresh or close the window and start the page again.

WHAT I EXPECT
That the ToDo list is in the order as i ordered it last time. (that my last order would persist)

WHAT REALY HAPPENDS
When i refresh the page, I do see that the page is this >< close to have them in my order, but when the refresh is done, the order is in the order which was before i rearranged the order, either 1 minut ago or 2 days ago

MY PROFILE/SETTINGS/ENVIRONMENT:
ID: 05ac01f8-4141-408f-89b1-505de586e517
OS: Win 8.1
Chrome Version 41.0.2272.118 m
Hardware: Lenovo Yoga 2 Pro (8gb RAM version, ask for more info)

Keep up the good work! ;)
You make my day ago abit better! :)

**Comment by Alys** [comment]
For the To-Dos not staying sorted, see this issue: https://github.com/HabitRPG/habitrpg/issues/2606
There's a section in bold near the top that explains what to do.

For the "Cannot read property 'shortcut' of undefined" bug, I think that's actually coming from an extension that you have installed and not from HabitRPG. It's almost certainly this one: https://chrome.google.com/webstore/detail/panicbutton/faminaibgiklngmfpfbhmokfmnglamcm?hl=en

**Comment by bean5** [comment]
I agree with @Alys, it appears that the console output you listed is actually from panicbutton. If it is causing things to not work, you may want to file a but report with them--I wouldn't expect their code to interfere here, so if it is, I'd say it is their code, note HabitRPG's that is at fault. That being said, the ToDo list ordering is a known bug. There are work-arounds to getting it to work, from what I understand, but they are not pretty. The coders know that it is going to be one of the harder things to fix. :( You can learn more about the work-around at https://github.com/HabitRPG/habitrpg/issues/2606 .

**Comment by Alys** [comment]
Thanks bean5. The extension and its bug definitely won't be having any effect on the To-Do list.
