### ISSUE TITLE
All li elements on page ridiculously tall in local install

### ISSUE THREAD

**Issue by tmas** [HabitRPG/habitica#502]
![bug](https://f.cloud.github.com/assets/271652/189712/4244e23e-7ea5-11e2-8ab3-660c29aacc29.png)
I really have no idea what could be going on here, since I'm on the master branch and this doesn't show up on the main site. It seems like every li element on the page is 220 px tall, but I can't figure out where that property comes from (height: 220px shows up under computed styles in Inspect Element).

EDIT: this occurs on both the master branch and the develop branch.

**Comment by dbueller** [comment]
I have the same problem!  No solution for it though.

**Comment by tmas** [comment]
I think I found the issue here. It looks like git doesn't checkout other repositories that have been added when running git clone --recursive under the windows command prompt, which leaves all the folders under public/vendor empty. The solution is to install the windows explorer extension and right click in the folder you want to clone the repo into, then select "Git Bash Here" and enter the command.

**Comment by tmas** [comment]
Whoops, never mind. totally unrelated problem.

**Comment by tmas** [comment]
Interestingly enough, this only shows up on my windows installation of habit; if I log into my ubuntu-based habit server, everything is completely normal. Hopefully knowing this will help someone fix it.

**Comment by horusofoz** [comment]
@tmas Is this still an issue?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
