### ISSUE TITLE
Batch Feeding Pets

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5024]
Feeding pets individually takes a lot of clicking and is a waste of time! It would be nice to implement batch feeding pets.
##

**Comment by octern** [comment]
In case anyone is curious, earning the triple bingo achievement requires 2,971 clicks. Every third click can be a keystroke instead.

**Comment by lemoness** [comment]
My conviction that this is needed has been strengthened 2970fold.

**Comment by TheHollidayInn** [comment]
Does that include clicking the alert boxes?

**Comment by deilann** [comment]
I assume so, as those are the only ones that can be done with keystrokes.

**Comment by octern** [comment]
That's correct, it includes the alert boxes.

**Comment by chimericdream** [comment]
As part of this, I would like to see an option to disable the confirmation popup. Users who are comfortable enough with the food/pet combinations can suppress it, knowing they assume the risk of accidentally feeding a "bad" food to a pet on a missed click.

**Comment by TheHollidayInn** [comment]
I like that. If we have a concensus, I'll admmemd the PR.

**Comment by lemoness** [comment]
I like that, too!

**Comment by TheHollidayInn** [comment]
Actually, I just realized that I have added a new modal box for batch feeding, so you would only need to confirm the items and amounts once. You can see on the PR my changes.

**Comment by sarojinirao** [comment]
So I just disabled the notification for confirming the feeding and can no longer feed my pets. I've tried reloading the page multiple times and logging out/logging back in, but to no avail. Any ideas? Also, I've never seen the modal box for batch feeding -- how do I activate this?

**Comment by Alys** [comment]
@sarojinirao The checkbox that allows you to disable notifications is a browser feature and isn't under the control of Habitica. The way to reset the setting is to close all browser windows. When you reopen them, the notification will appear again. There is no need to log out of Habitica before you close the windows. The modal for batch feeding is still under development, testing, and review. When it's released, it will be enabled for all players - you won't need to activate it.

**Comment by sarojinirao** [comment]
@Alys That was fast, thanks! I just saw that suggestion on another thread, so will do that now.

**Comment by librarianmage** [comment]
What is the status of this?

**Comment by lemoness** [comment]
This will be handled after the upcoming redesign.

**Comment by librarianmage** [comment]
@lemoness Then should it be marked as "on hold" in stead of closed?

**Comment by lemoness** [comment]
I closed it because it will be implemented in a different way than is
described earlier in this issue, since it will be integrated with the new
site design. That being said, if devs feel that it's helpful to keep this
issue open in the interim, I'm happy to do so!
