### ISSUE TITLE
Feature suggestion: display progress towards rewards

### ISSUE THREAD

**Issue by Laflamme** [HabitRPG/habitica#503]
Two ideas to increase motivation : 

1 - Rewards could be colour shaded according to how much gold they cost vs how much gold the user currently has. 

2- The user could be able to drag and drop a coveted reward on a special row in the rewards panel, where it would assume the appearance of a progress bar displaying how much gold that user has vs how much that reward costs. 

Over that progress bar could also be displayed the estimated day the user should be able to buy his reward based on his average daily gold gains.

**Comment by KristenEberts** [comment]
I really like this idea! If it were on Trello I'd vote it right up. Perhaps the progress bar could appear when the user mouses over the cost of the reward?

**Comment by Laflamme** [comment]
I think the mouseover solution you propose could be very elegant!

Oh, and also, shading rewards in red when you don't have enough gold pieces to buy them would be a good reminder you're about to lose life points if you buy them anyway.

**Comment by wc8** [comment]
@AntiquatedMeme "vote it right up": [show progress toward reward](https://trello.com/c/K7xOkD7a)

**Comment by Pandoro** [comment]
@Laflamme love the idea!
