### ISSUE TITLE
Users can send messages to themselves

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5032]
This can be done either by clicking the PM icon next to one of their own posts, or by clicking on their name in The Hall (if it's there) and clicking on the PM icon from the resulting profile pop-up. 

This issue is probably trivial, but I figured you'd like to know.

**Comment by TheHollidayInn** [comment]
Thanks, @hairlessbear!

Should we keep this as is? I personally email myself all the time, so maybe PMing yourself would be useful?

**Comment by lemoness** [comment]
I can imagine this being useful as a reminder technique, or way to send
memos to yourself. I'd rather it weren't changed!

**Comment by hairlessbear** [comment]
@TheHollidayInn @lemoness, good point. I should've mentioned this in the OP, but I didn't really mean this as a bug report. I brought it up because I thought there was a chance it was an unintended feature, and wanted to make sure you guys were aware of the behavior. I'm glad to hear it's not a problem; you guys have enough work on your hands as it is!

**Comment by lemoness** [comment]
Thanks so much for reporting it, regardless - I wasn't aware it was
something you could do, and now I am interested in using it myself. You've
been very helpful on Github recently!

**Comment by hairlessbear** [comment]
Thanks! HabitRPG is the first project I've come across that is just _so awesome_ that I can't help but get involved in any way I can :) As soon as I relearn Javascript and learn Angular, I'll be fixing the bugs with you guys instead of just reporting them.

**Comment by Alys** [comment]
Thanks @hairlessbear! This was a deliberate feature though. As well as letting you send messages to yourself, it allows admins to more easily test the PM system, and it allows any user to test how PMs work before sending a message to any other user. There's no disadvantage to it since you can't accidentally send PMs to yourself (or if you do, you can easily delete them).
