### ISSUE TITLE
Reorganized Equipment Page and/or Equipment Sorting

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5033]
We're about to start implementing a new feature that will add more Equipment to an already-overcrowded page, so this is a good time to start working on reorganizing the Equipment Page to be more usable.

There have already been proposals for better ways to sort, such as by item type (helm, head accessory, armor, etc) in addition to item class (rogue, mage, mystery, etc.). There have also been some requests for sorting by color and sorting by stat.

I'm not sure if we want to do a full reorganization, or just implement sorting on top of the organization that we currently have.

Pinging @anitaycheng @crookedneighbor @Alys 
##

**Comment by Alys** [comment]
For sorting by colour, my idea was that each piece of equipment would have assigned to it one to three colours (chosen from a set list of colour names), indicating the predominant colour(s) for the piece. Hence if you wanted a costume to match your red pet, you could filter for red gear.

**Comment by AnitaYCheng** [comment]
My first thought is to present the equipment that's best suited for the user's class first, then filter down by color/type from there. I don't think we need to put in a search bar, just a filter bar.

I like @Alys's suggestion about color, since a lot of people do use their equipment for fun things like that. :smile:

**Comment by UnexpectedMushroom** [comment]
A favourites section up the top would be handy.

**Comment by lemoness** [comment]
We've since added a bunch of sorting options. I'm closing this ticket but feel free to comment if you think it should be reopened!

**Comment by khipkin** [comment]
Personally, I would really love if the sort option persisted! Even if it's just on a per-session basis.
