### ISSUE TITLE
Get rid of /static/front redirect

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5035]
From @lefnire:

"Angular wants our app at an endpoint. Since Habit started with the app endpoints, with no static pages, "root" was the app endpoints, so I kinda did the opposite and added static pages at their own endpoint, ignored by Angular. The solution is to move Habit's angular endpoints to /app/_, and ignore /app/_ through express."
##

**Comment by TheHollidayInn** [comment]
If I am understanding this correctly, are we needing to move the static routes here:
https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/src/routes/pages.js

to here: 
https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/public/js/app.js
?

**Comment by librarianmage** [comment]
@Alys I can do this

**Comment by Alys** [comment]
I think this should wait till after API v3 too. It feels like there'd be changes in many places for this, so keeping it well separate from other work that involves many changes would be sensible.

**Comment by librarianmage** [comment]
@Alys do you know if there is a timeline for the v3 release?

**Comment by Alys** [comment]
Yes, a timeline for the remaining work is being developed. It won't be too
much longer.

**Comment by librarianmage** [comment]
@Alys Can I work on this now?

**Comment by Alys** [comment]
@MathWhiz I'm not sure whether or not it's something we still want. Don't proceed unless one of the other admins responds. It might be a while until they do since they're focussing on critical bug fixes at the moment.

**Comment by crookedneighbor** [comment]
I think we should put this off until the site redesign. No sense in working on it right now.

**Comment by khipkin** [comment]
I think it would be helpful to have a new label for issues that should be addressed in the frontend redesign.

**Comment by crookedneighbor** [comment]
Anything with the interface label will be that.

**Comment by lemoness** [comment]
Has this been addressed? If so, it should be closed.
