### ISSUE TITLE
Gift API Issues

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#5038]
### `POST /members/{uuid}/gift`
- [ ] accepts floating point numbers as a gift, should only accept integers
- [ ] displays an undefined value for the message if message is not provided
- [x] does not have documentation for message param in swagger
##

**Comment by paglias** [comment]
@crookedneighbor the first 2 points are still valid? Regarding 1 I think we should allow multiples of 0.25

**Comment by Alys** [comment]
Seems fixed.

```
    req.checkBody('gemAmount', res.t('gemAmountRequired')).notEmpty().isInt();
```

```
if (req.body.message) {
  message += req.body.message;
}
```
