### ISSUE TITLE
Lag on attribute allocation page - points allocated to wrong attributes

### ISSUE THREAD

**Issue by MaidM** [HabitRPG/habitica#5040]
Significant loading speed issues on page, areas I clicked were ignored, areas I didn't click were allocated.  An improvement would be to separate attribute selection from the commit action so that user confirms overall point assignments before they are spent and unretrievable, which protects against page rendering issues.
##

**Comment by Alys** [comment]
@sabrecat I think you're working on changes to points allocation?

**Comment by SabreCat** [comment]
Aye, this is generally my territory.

**Comment by librarianmage** [comment]
Is this still an issue with the redesign?

**Comment by Alys** [comment]
The new layout prevents this happening even when there's a lag.
