### ISSUE TITLE
Customized Setup for New Users

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5041]
We've been getting a lot of feedback from users who say that, while HabitRPG's blank-slate flexibility is an asset, it can lead to an extremely daunting set-up.

As a result, we want a system that prompts the new user, on their first website sign-in/account creation, to pick some things that they want to manage with HabitRPG and then generate default tasks based on what they picked, and display a list of recommended Guilds (possibly in the corner). These tasks could then be edited, deleted, kept... whatever the user chose.

We should probably have something in place that gives them only a maximum of 1 or 2 Dailies to avoid overwhelming them if they check many boxes.

Note that these tasks should appear BELOW the sample tasks used for the current tour. We're still iterating on and developing the tour, so we should try to keep these separate if we can for now. We'll be testing the effectiveness of different sample tasks over time once this feature is implemented.

Here's the current text!

When users join for the first time, a pop-up asks them:

What do you want to manage with HabitRPG? (Pick all that apply)
- Work
- Exercise
- Health + Wellness
- School
- Teams
- Chores
- Creativity
### Work

HABIT: + Process Email
DAILY:  Most Important Task
TO-DO: Work project (1, 2, 3, 4)

RECOMMENDED GUILDS:
Newbies https://habitrpg.com/#/options/groups/guilds/5481ccf3-5d2d-48a9-a871-70a7380cee5a
Working from home https://habitrpg.com/#/options/groups/guilds/32dcf8f2-c89d-45ab-9ff2-c00ede2ce2e0
### School

HABIT: +/- Study/Procrastinate
DAILY: Do homework
TO-DO: Finish assignment for class (1, 2, 3, 4)

RECOMMENDED GUILDS:
Newbies
The Scholars https://habitrpg.com/#/options/groups/guilds/82fe50b1-4fa5-4e94-8114-aa66516c0d9d
Graduate Student Guild https://habitrpg.com/#/options/groups/guilds/160234e0-7a3b-46e6-8b9f-3245ac6f1678
### Health + Wellness

HABIT:  +/- Eat healthy/junk food
DAILY: Floss
TO-DO: Schedule self-care time

RECOMMENDED GUILDS:
Newbies
The Health Nuts https://habitrpg.com/#/options/groups/guilds/b422b8a5-8d66-4197-9f91-d4edb8610264
The Happy List Guild https://habitrpg.com/#/options/groups/guilds/a1d9d3fd-fa2f-4eb5-89b9-194246963ac0
### Exercise

HABIT:  +10 min cardio
DAILY: Stretching
TO-DO: Set up workout schedule 

RECOMMENDED GUILDS:
Newbies
The Health Nuts https://habitrpg.com/#/options/groups/guilds/b422b8a5-8d66-4197-9f91-d4edb8610264
Evidence-based Fitness https://habitrpg.com/#/options/groups/guilds/fd345cc5-da2e-4651-8b64-78dc0d6d5d1e
### Teams

HABIT: + Check in with Team
DAILY: Update Team on Status
TODO: Complete Team Project (1, 2, 3, 4)

RECOMMENDED GUILDS:
Newbies
Entrepreneurs https://habitrpg.com/#/options/groups/guilds/2c6ffb73-80d0-4727-ae92-8713844f4a42
### Chores

HABIT: + 10 minutes cleaning
DAILY: Wash Dishes
TODO: Organize Closet (1, 2, 3, 4)

RECOMMENDED GUILDS: 
Newbies
Make Your Home Sweet Home
https://habitrpg.com/#/options/groups/guilds/d33f834c-9c24-4484-9d1c-95dfa323175e
Clutter Busters https://habitrpg.com/#/options/groups/guilds/225b1279-3e46-401f-9302-b575269eec6d
### Creativity

HABIT: + Study a master of the craft
DAILY: Work on creative project
TODO: Finish Creative Project (1, 2, 3, 4)

RECOMMENDED GUILDS: 
Newbies
The Wordsmiths: https://habitrpg.com/#/options/groups/guilds/48c084a8-81a7-40cc-a8c1-b8e93357424d
Artists: https://habitrpg.com/#/options/groups/guilds/dea7a124-9e69-4163-a708-d3e961a96159
##

**Comment by lemoness** [comment]
Note that if the architecture for Recommending Guilds is more difficult, that can be postponed into a part 2.

**Comment by deilann** [comment]
I'd really prefer stag not be recommended to every new user who says they
use habit for work

**Comment by Alys** [comment]
Short-Term Accountability Guild tends to be used for personal tasks more
than work tasks (lots of discussion of laundry, tidying, decluttering,
general housework).

It also has a lot of its own specific terminology (poms,
pom-trees/palm-trees, sparkle points, cone of shame, many of those often
indicated with emoji rather than words). I was confused for a few days
after I joined, and that was when I'd been a site admin for months. :) I
wouldn't recommend it to new users in bulk.

**Comment by TheHollidayInn** [comment]
Would we use the tour system to implement this?

**Comment by lemoness** [comment]
@deilann - No problem! Editing original post now.

Does anyone have a replacement Guild that might work as a recommendation
for people who use HabitRPG for work?

@thehollidayinn - No, this would be separate, since the tour is still being
updated and changed around.

**Comment by lemoness** [comment]
Some of the necessary groundwork for this feature will be included in https://github.com/HabitRPG/habitrpg/issues/2301 (templates), so we should wait until that is complete before proceeding with implementation - but we can absolutely continue to discuss!

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by Alys** [comment]
Still suggestion-discussion. 

The issue referred to in Lemoness's most recent comment has been closed.

**Comment by khipkin** [comment]
I think "Health + Wellness" could be broken down further into physical health+wellness vs emotional/mental/spiritual health+wellness.

---

**Health + Wellness**

HABIT: +/- Eat healthy/junk food
DAILY: Floss
TO-DO: Pick a specific time to go to bed every night

RECOMMENDED GUILDS:
Newbies
The Health Nuts https://habitrpg.com/#/options/groups/guilds/b422b8a5-8d66-4197-9f91-d4edb8610264

---

**Recovery + Self-Care**
_(Dailies from the [BACE Method for Self-Care](https://habitica.com/#/options/groups/challenges/0c3b47d4-6743-4673-957e-ff1e36070df9) Challenge.)_

HABIT: + Compliment yourself.
DAILY: Body (e.g. excerise, hygiene, proper sleep, healthly meals, etc.)
DAILY: Achievement (e.g. chores, work, personal projects, etc.)
DAILY: Connect (e.g. see a friend, call someone, send a message, etc.)
DAILY: Enjoy (something fun, relaxing, or enjoyable)
TODO: Make a self care box (http://www.howtomakealife.com/2014/03/creating-self-care-box/) for a rainy day.

RECOMMENDED GUILDS:
Mentally Ill https://habitica.com/#/options/groups/guilds/54846572-9b87-421c-a2f5-11f72ee8ecfc
The Happy List Guild https://habitrpg.com/#/options/groups/guilds/a1d9d3fd-fa2f-4eb5-89b9-194246963ac0

**Comment by TheHollidayInn** [comment]
I think this should be closed with the redesign.
