### ISSUE TITLE
Clearing Browser Cache and logging in via facebook created second account with unique API

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5042]
Recently I cleared my browser cache/history in chrome.

After that I had to log back into everything (including facebook) When I logged back in to habitrpg using facebook it generated a new account with user ID: 8e3fbe2f-3578-45ac-8335-e26504c62bfb (which is a level 1 account with none of my progress.)

When I log in using facebook on other machines it comes up with my original account: 5f5604ef-298c-46d0-9811-15f036962cdc

I tried clearing my cache and logging back in again on this machine, but it is sticking with 8e3fbe2f.

**Comment by deilann** [comment]
Delete the incorrect account, then log back in again.

**Comment by lemoness** [comment]
Sorry about this! The good news is that there is a pretty easy fix. When
you are logged in to the duplicate account, go ahead and delete it (under
Settings > Site > Delete).Then log back in, and you should have your old
account!

Let us know if that works for you.

**Comment by Alys** [comment]
I'm closing this since the fix described above has always worked in the past but, @tpreader, if you're still having trouble, post here and we'll reopen it and/or keep helping you.
