### ISSUE TITLE
No Mystic Hourglass with Subscription Renewal

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5043]
Hello,

I am on my second three month subscription period. When I renewed my subscription, I thought I would be awarded a mystic hourglass, but I have not yet seen it in my inventory.

Any idea what may be happening?

TIA

**Comment by hairlessbear** [comment]
Was there any break in your subscription between the first and second period? As detailed [here](http://habitrpg.wikia.com/wiki/Mystic_Hourglass), the subscriptions must be consecutive to recieve an hourglass. 

Also, can you please include you User ID (located in Settings -> API)? I'm not an admin, but the admins will need your UID so they can access your user data and determine what's going on.

**Comment by ghost** [comment]
I have not had a lapse in subscription and it renews automatically through Paypal.

User ID is: 48c81f20-a653-48b1-8595-c30a1543d6a1

I started to wonder if the new one is awarded at the end of the subscription period, based on the list of stats I found on my subsciption page:

**You have 0.61 months of subscription credit.
 Consecutive Subscription**

   **Consecutive Months: 7**
   **Gem Cap Extra: 10**
   **Mystic Hourglasses: 0**

Thanks for your response, hairlessbear.

**Comment by deilann** [comment]
Attn: @lefnire Another 3 month subscription renewal not granting the
hourglass

Sorry! We've been having trouble specifically with block subscription
renewals not granting the hourglass upon renewal. We'll be able to manually
grant it to you, though. :) (@Alys, can you do that for me?)

**Comment by Alys** [comment]
Yes, I'm able to do subscription fixes like this now, I was just waiting on the uuid. @Dracoluna I'll fix this for you in several hours when I get home from work.

**Comment by Alys** [comment]
@Dracoluna I've fixed that for you. You should now have an increased monthly gem cap and one new hourglass. If they don't appear after you've reloaded the website (browser refresh button), then post here and we'll reopen this and keep helping you.

**Comment by ghost** [comment]
Thank you! Everything has appeared as promised.

**Comment by boskdeox** [comment]
I think I had the same thing happen .  I clicked to cancelled my subscription a month ago, but now I was charged again for another 3 months AND I did not receive an hourglass.

Double Whammy.  I would like to have my money refunded.
User ID: af9f18a4-224f-4b4c-88c7-4b61b4b567c3

**Comment by crookedneighbor** [comment]
@boskdeox Please email your receipt to admin@habitica.com

**Comment by crookedneighbor** [comment]
Don't worry, we'll get you sorted out :smile:
