### ISSUE TITLE
Way to Invite Friends from the Tasks Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5044]
It would be nice to have a way to invite friends from the tasks page, to make it more obvious to new users that this is something they can do. 

For solo parties, could we add a "+" or something similar to the space where a party member would be that, when clicked,pops up the "Invite a Friend" modal?

We'd also need something under Settings that would let you turn it off or hide it, for people in solo parties who didn't like it.

**Comment by TheHollidayInn** [comment]
What if we added a message that says invite friends or join a party and sent them to the looking for parth guild?

**Comment by lemoness** [comment]
Personally, I think using the pop-up is easiest - it doesn't redirect them,
so it reduces the number of steps, and it gives them an option to invite
real-world friends as well, which is good for Habit. The Looking for Party
Guild is pretty easy to find.
