### ISSUE TITLE
Tasks disappeared/duplicated

### ISSUE THREAD

**Issue by HRingler** [HabitRPG/habitica#5045]
Half my tasks are duplicated, and at least one disappeared. The one that disappeared, I was working on it an hour ago, and it was fine. Unfortunately, it was the really important task where all of my schoolwork-related tasks for the week are.

825b5d35-7d03-4f35-a7db-2b0396409427

My browser is the latest version of chrome, and my OS is Yosemite 10.10.2.

**Comment by hairlessbear** [comment]
When you say "tasks", are you referring to habits, to-dos, dailies, or some combination? If you could specify which category of item was duplicated, and which was deleted, that would be extremely helpful.

I'm not an admin, so I can't look at what happened with your account specifically, but one of them will be along to help as soon as they have the time. For reference sake, this issue may be related to #4470 (and maybe #4773 and #5012).

**Comment by HRingler** [comment]
Oops! To-Dos, sorry.

**Comment by hairlessbear** [comment]
No need to apologize, just clarifying for easier troubleshooting :) Hopefully an admin will be able to help you soon!

**Comment by Alys** [comment]
@HRingler First, click the clear button next to your tags, even if it looks like no tags were selected. Then, look at your completed To-Dos to see if the missing one was accidentally marked completed.

If neither of those work, tell me something about the task that I can use to identify it in a database backup (e.g., a few words from the task title). If it is private, you can do that by PM (find my name in the Tavern under the new message box).

When I have found your missing task, I will want to show you it and all its checklist items so that you can check if it's the correct one. Is it okay if I do that here, or should I keep it private?

**Comment by HRingler** [comment]
I clicked clear - I don't have any tags, so it didn't work very well, heh. Also, the missing one was not accidentally marked completed, and half of them are still duplicated.

The missing one was called Week 12 To-Dos, I think, and the checklist is full of items like '579 read ____'.  You can show it here, if you find it - it's nothing private, just a comprehensive list of schoolwork I need to get done...

**Comment by Alys** [comment]
This is from a backup made on 2015-04-15. Is it the correct task? Are all the checklist items there. There was no Week 12 task, but if it was added after 2015-04-15 (or if the task below was edited after then), then I can get a more recent backup.

```
"text" : "Week 11 (?) To-Dos",
"checklist" : [
    {
        "text" : "520 revise process writing piece",
        "completed" : true
    },
    {
        "text" : "520 read the rest of Romano's Blending Genre etc",
        "completed" : true
    },
    {
        "text" : "520 read Christensen's Essay With An Attitude",
        "completed" : true
    },
    {
        "text" : "520 actually read a couple of articles for research pape",
        "completed" : true
    },
    {
        "text" : "520 draft 5, 6, 7th pieces for research paper (double voice poem w/ferryman?)",
        "completed" : true
    },
    {
        "text" : "520 review takeaways from student writing on wiki",
        "completed" : true
    },
    {
        "text" : "520 read A Map of Writing in Terms of Audience and Response",
        "completed" : true
    },
    {
        "text" : "520 Kirby & Covitz ch.8",
        "completed" : true
    },
    {
        "text" : "520 make feedback for student writing sample",
        "completed" : true
    },
    {
        "text" : "520 take notes on learning, using, and teaching grammar for class",
        "completed" : true
    },
    {
        "text" : "541 read Talking About Reading As Thinking pdf",
        "completed" : true
    },
    {
        "text" : "541 Read VVM Chapter 2",
        "completed" : true
    },
    {
        "text" : "541 Read Adolescents Checklist PDF",
        "completed" : true
    },
    {
        "text" : "541 Read Online Reading Comprehension PDF",
        "completed" : true
    },
    {
        "text" : "541 Watch video on Padlet and respond",
        "completed" : true
    },
    {
        "text" : "541 New Literacies forum",
        "completed" : true
    },
    {
        "text" : "579 Issues & Concerns in Behavior Change",
        "completed" : false
    },
    {
        "text" : "579 Read Shea and Bauer",
        "completed" : false
    },
    {
        "text" : "579 Read handouts",
        "completed" : true
    },
    {
        "text" : "579 Read Hardin",
        "completed" : false
    },
    {
        "text" : "579 Read Soodak & McCarthy",
        "completed" : false
    },
    {
        "text" : "541 Teach Lesson to Lucy",
        "completed" : false
    },
    {
        "text" : "541 Finish Reflection on SRE",
        "completed" : false
    },
    {
        "text" : "579 Continue taking notes on George's YouTube habits",
        "completed" : false
    }
]
```

**Comment by Momogajo** [comment]
All of my tasks, habits and to-do's are gone, only the core rewards remain.

f3df5aad-6e4c-4825-a907-095c0928f72d

I'm on google chrome and windows 7

**Comment by paglias** [comment]
@Momogajo sorry about this! all your data is safe and if you reload everything should be ok.

**Comment by Momogajo** [comment]
Thanks it worked

**Comment by HRingler** [comment]
That's not the one - that's the older one. Maybe it's on the more recent backup?Sent from Yahoo Mail for iPhoneAt Apr 22, 2015, 3:18:30 AM, Alys wrote:This is from a backup made on 2015-04-15. Is it the correct task? Are all the checklist items there. There was no Week 12 task, but if it was added after 2015-04-15 (or if the task below was edited after then), then I can get a more recent backup.

"text" : "Week 11 (?) To-Dos",
"checklist" : [
    {
        "text" : "520 revise process writing piece",
        "completed" : true
    },
    {
        "text" : "520 read the rest of Romano's Blending Genre etc",
        "completed" : true
    },
    {
        "text" : "520 read Christensen's Essay With An Attitude",
        "completed" : true
    },
    {
        "text" : "520 actually read a couple of articles for research pape",
        "completed" : true
    },
    {
        "text" : "520 draft 5, 6, 7th pieces for research paper (double voice poem w/ferryman?)",
        "completed" : true
    },
    {
        "text" : "520 review takeaways from student writing on wiki",
        "completed" : true
    },
    {
        "text" : "520 read A Map of Writing in Terms of Audience and Response",
        "completed" : true
    },
    {
        "text" : "520 Kirby & Covitz ch.8",
        "completed" : true
    },
    {
        "text" : "520 make feedback for student writing sample",
        "completed" : true
    },
    {
        "text" : "520 take notes on learning, using, and teaching grammar for class",
        "completed" : true
    },
    {
        "text" : "541 read Talking About Reading As Thinking pdf",
        "completed" : true
    },
    {
        "text" : "541 Read VVM Chapter 2",
        "completed" : true
    },
    {
        "text" : "541 Read Adolescents Checklist PDF",
        "completed" : true
    },
    {
        "text" : "541 Read Online Reading Comprehension PDF",
        "completed" : true
    },
    {
        "text" : "541 Watch video on Padlet and respond",
        "completed" : true
    },
    {
        "text" : "541 New Literacies forum",
        "completed" : true
    },
    {
        "text" : "579 Issues & Concerns in Behavior Change",
        "completed" : false
    },
    {
        "text" : "579 Read Shea and Bauer",
        "completed" : false
    },
    {
        "text" : "579 Read handouts",
        "completed" : true
    },
    {
        "text" : "579 Read Hardin",
        "completed" : false
    },
    {
        "text" : "579 Read Soodak & McCarthy",
        "completed" : false
    },
    {
        "text" : "541 Teach Lesson to Lucy",
        "completed" : false
    },
    {
        "text" : "541 Finish Reflection on SRE",
        "completed" : false
    },
    {
        "text" : "579 Continue taking notes on George's YouTube habits",
        "completed" : false
    }
]

**Comment by Alys** [comment]
I downloaded a backup from 2015-04-18T001820 (within a day before you logged this issue). That doesn't have a "Week 12 To-Dos" task in it either. I'll download the backup just after that one. It takes several hours to download and import backups, so it will be a while longer before I report back again.

**Comment by Alys** [comment]
@HRingler The next backup also does not have your Week 12 task. The backup after that was created after you logged this issue. Had you created the task just an hour or two before it disappeared? If so, that would have been useful information to know because it means it will not be in any backup. Or could it have a different title since you weren't sure of it's name ("called Week 12 To-Dos, I think")? Or do you still have the information that it was created from? I am guessing it was a made from a formal requirement of your schoolwork that week, so perhaps you could ask your teacher or a classmate to give you another copy of the information?

**Comment by HRingler** [comment]
Well, I'd created it a few days before it disappeared, actually, and had been ticking things off. I'm 95% sure (it's finals week so 100% sure of anything is impossible) it was called Week 12 To-Dos, because that's the pattern I've been using all semester, so I guess it just vanished into the aether. Thanks for all your hard work looking! I'll see if I can recreate it.

**Comment by Alys** [comment]
Because it was created a few days before it disappeared, it would definitely have been in any one of the backups I have looked at. However none of them had a task labelled "Week 12". Are you sure it was not the "Week 11" task I pasted in here earlier? That did have a ? in its name so maybe it was for Week 12. Or can you make another guess at its name?

**Comment by HRingler** [comment]
Nope! The ? was because I wasn't sure what week it was, and that task is still in my inbox. The only guess I have is that I might have given up entirely on naming it by week and just called it To-Dos... 

```
 On Thursday, April 23, 2015 1:35 PM, Alys <notifications@github.com> wrote:
```

 Because it was created a few days before it disappeared, it would definitely have been in any one of the backups I have looked at. However none of them had a task labelled "Week 12". Are you sure it was not the "Week 11" task I pasted in here earlier? That did have a ? in its name so maybe it was for Week 12. Or can you make another guess at its name?—

**Comment by Alys** [comment]
I'm sorry, there's nothing like that in the backups made in the 24 hours before you logged this issue.

**Comment by damiananero** [comment]
I've got such a problem!
A problem appeared when I tried to deal with a habit of ended challenge (tried to keep it).
After page refresh disappeared everything custom (not from challenges) - habits, dailies, to-do, rewards. And added two 'third party' habits with names cb9ea102-fae7-493b-af6c-27b9c3ef194f and 1a687d54-d4a7-4b0a-9485-b443607b7fd6.
The same picture is on backup site and in android app. I don't have any browser plugins/apps/smth else, connected to habit.

my ID: 362a1835-b723-4db7-9cc5-389a803c3b82
browser: http://whatsmybrowser.org/b/P3TWXLX
(copy from #5060 'cos it's closed already)

**Comment by crookedneighbor** [comment]
@damiananero You probably have a tag selected by accident. Click the clear button even if you're sure you don't have a tag selected.

![tags](https://cloud.githubusercontent.com/assets/2916945/7668119/dde8d9a4-fbec-11e4-8056-312dc237d094.png)

If your tasks don't reappear, post back here.

**Comment by damiananero** [comment]
Nope, it didn't help =\
(And wouldn't challenges disappear too if it was because of tag?)

**Comment by Alys** [comment]
@damiananero's problem is being sorted out in https://github.com/HabitRPG/habitrpg/issues/5060#issuecomment-102698667. @damiananero Please don't report problems in two places at once. As you've seen, you'll get replies in both places and so it increases the time we spend helping you.
