### ISSUE TITLE
[Suggestion] Game settings panel

### ISSUE THREAD

**Issue by tmas** [HabitRPG/habitica#505]
A game settings panel would remove one step from the implementation of each suggestion that might not appeal to everyone. It could go under a new tab in the settings menu. It seems like it would be pretty simple to implement, so I might give it a shot myself.

**Comment by tmas** [comment]
Alright, got the settings panel itself up. Now I just have to find a worthy suggestion that isn't too hard to implement and could use an option in the panel.

**Comment by tmas** [comment]
Pull request at #506

**Comment by tmas** [comment]
Good idea, but I can't implement it myself because a. I don't know every language and b. Habit isn't set up to be translated yet. There's a suggestion for translation, but I don't think that we even know how that's going to happen yet.

EDIT: the suggestion for translations is #62

**Comment by lefnire** [comment]
Soon my friends, it's high on the roadmap - next week or two

**Comment by wc8** [comment]
@ruddfawcett [Trello's Translation Card:](https://trello.com/c/SvTsLdRF)

> If everybody interested in translations could email stan@habitrpg.com we'll add you to our list and get your involved early.

**Comment by wc8** [comment]
Options to test with, in case they are still needed: 
- Show/Hide Header
- Always show/hide Advanced in Edit of a task
- Show/Hide Difficulty
