### ISSUE TITLE
Incorrect Daily Damage Counting

### ISSUE THREAD

**Issue by morrcahn** [HabitRPG/habitica#5050]
Multiple times I have had this issue within the past couple weeks. When I log in for a new day, I take 30+ damage, even though I only miss one or two of my dailies. I then check my party's quest, and it shows that I should have only taken < 10 damage. Are there any other explanations for this other than a bug?

**Comment by Alys** [comment]
The damage you take from your own Dailies is not necessarily the same as the damage that the boss does to the party. It can be higher or lower - it depends on which quest you are doing. Also, you will take damage from the incomplete Dailies of other quest participants (you can see how much from the messages in party chat) and if that damage happened overnight, then it will be applied when you log in at the same time your own Dailies' damage is applied. Also your browser might not be correctly syncing your actions to the server, so HabitRPG might think that more of your Dailies are left uncompleted than actually are - to check for this, at the end of the day, reload the HabitRPG website and ensure that all your Dailies are still ticked (or use the Data menu -> Data Display Tool to see a list of Dailies Incomplete).

We can't give you more tailored advice without knowing your user ID. If you'd like a proper investigation, please go to the Help menu and select Report a Bug. The page that takes you to has instructions for how to find your user ID (step 6).

**Comment by Alys** [comment]
I'm closing this since it's been a few months without a response, but @morrcahn let us know if you are still having this problem and see my previous comment for suggestions.
