### ISSUE TITLE
Quests not autostarting after all party members have accepted invite

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5051]
Exactly what it says in the title. For the last several (at least five) quests everyone in the party has accepted the quest invite but the quest did not autostart and had to be manually started by the quest owner. 

The first incident of the bug coincided with Crimson, a former party member deleting her account so our parties working theory is that the quest invite system is still waiting for her response but we have nothing to back this up besides the timing.

Group ID: bc9f45d5-3177-4cd7-82b8-43cb72ff115f
My User ID: 908c5a51-52b1-4734-8414-ef10cbe9404b

If anyone in the party knows Crimson's User ID I'll post that as well, but this is all the information I have right now

**Comment by deilann** [comment]
I'll bet crimsons uuid is still in the party object and that's exactly
what's causing this bug.

@Alys can you check, confirm, and remove?

**Comment by Alys** [comment]
@AnnaLibertas I've removed the deleted member from your party. The quest owner will need to start this quest manually but after that all of the quests should start by themselves when everone has accepted. If that turns out to be not the case, comment here and we'll reopen this.

**Comment by ghost** [comment]
Awesome, thank you so much

**Comment by Productiviteam** [comment]
My party has come across a similar problem. The quest leader left the party, and the party leader for some reason did not automatically become the new quest leader. We asked everyone to rsvp to the quest, and even then the quest did not start. The original quest leader was Danielle Miller with UI: 9251d222-ca02-45e2-9411-87dd92f80f95 in case that helps you. The party UI is 4c2b3587-77bc-4533-97a4-0ac273084b6a.

**Comment by Alys** [comment]
@Productiviteam I've removed the stuck quest from the party. The original quest owner has retained the scroll that they purchased.

**Comment by Productiviteam** [comment]
@Alys Thank you so much!
