### ISSUE TITLE
Contributor titles/tiers aren't displayed in profile popups (scope issues)

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5052]
`profile.jade` and `members.jade` are both supposed to display a user's contribution title(s), tier, and tier color. But these only show up on the profile page; the members pages (i.e., profile popups) show nothing (the tiers should show up [here](https://github.com/HabitRPG/habitrpg/blob/83407e046375795efa3ba5d7e7bd84d547f44509/website/views/shared/modals/members.jade#L5) and [here](https://github.com/HabitRPG/habitrpg/blob/83407e046375795efa3ba5d7e7bd84d547f44509/website/views/shared/modals/members.jade#L32)).

[`contribText`](https://github.com/HabitRPG/habitrpg/blob/e1a623d3e09b7d6ae8bb63dfbf6ad6fd164eeb1f/website/public/js/controllers/rootCtrl.js#L159) is the function that isn't performing as expected. It looks like it's returning nothing, which it should only do if `profile.contributor` and `profile.backer` don't exist. But what's confusing me is that `members.jade` uses `profile.contributor.level` successfully, indicating that `profile.contributor` exists, and therefore `contribText` shouldn't return with nothing. (For reference, [this line](https://github.com/HabitRPG/habitrpg/blob/eddade48a4e40971d9a1e98021e35b0ab6da267d/website/views/shared/profiles/achievements.jade#L40) is where `profile.contributor.level` is successfully used to set the color of the tier titles). 

I've been trying to debug this for a while, but I'm stuck. I'm still really new to web development, so it's possible I'm missing something embarrassingly obvious. Any ideas?

**Comment by Rbrinkley** [comment]
Here are some images to show the issue. 

Alys:
![alystierdisplayproblem](https://cloud.githubusercontent.com/assets/7588148/7242551/13460bd0-e789-11e4-90b5-baf321ed54af.png)

Lemoness:
![lemonesstierdisplayproblem](https://cloud.githubusercontent.com/assets/7588148/7242576/444f624e-e789-11e4-8b2c-3d4769109af5.png)

Rbrinkley (Me)
![rbrinkleytierdisplayproblem](https://cloud.githubusercontent.com/assets/7588148/7242583/5228e46c-e789-11e4-979a-e24546014387.png)

Hope these help.

6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by Rbrinkley** [comment]
This would probably be a better image to show. Sorry I should have done that earlier.

![alystierdisplayproblem2](https://cloud.githubusercontent.com/assets/7588148/7242616/a6e7e7d2-e789-11e4-8575-8bd7ab2ed38d.png)

Hope This helps.

6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by hairlessbear** [comment]
Huh, that's interesting; I didn't notice that the tier color wasn't being properly applied to the avatars as well, but there it is. Good catch.

And just to be clear, the titles are supposed to be right after the hyphen in the header, and right next to the achievement firefox badge.

**Comment by deilann** [comment]
I've meant to report this has been broken for over a year.

I'm good at life. :)

**Comment by Rbrinkley** [comment]
Oh. I thought that was what you were talking about. Well. I guess I helped? I do good? I hope me do good.

**Comment by deilann** [comment]
Those are exactly what was being talked about. Thank you for the
screenshots

**Comment by Alys** [comment]
@Rbrinkley I approve of any action that publicises lots of images of me. :)

@hairlessbear I did have a look at the code you were asking about but wasn't able to come up with anything intelligent. If no one has helped in the next couple of days, I'm going to ping some people who are likely to be much more helpful than I can be, but the ones I have in mind are busy at the moment, so it might take a few more days for them to respond. Thank you for looking into this! I also had noticed the problem but not got around to reporting it...

**Comment by hairlessbear** [comment]
@Alys @deilann considering you guys work on the site-breaking issues and new features, I'm not surprised something small like this fell through the cracks. 

Just to be super clear what the problem is, there are three different, related issues going on here: 1) the avatar coloring; 2) the contributor titles not showing up in the header; 3) the contributor titles and tier color not showing up next to the achievement-firefox. This is where 2 and 3 should be showing up
![a6e7e7d2-e789-11e4-8575-8bd7ab2ed38d](https://cloud.githubusercontent.com/assets/7059890/7243304/ae67277e-e799-11e4-92ec-6e5a25d371a2.png)

And this is what 3 should look like (but with Alys' tier info, obviously); 2 should look the same, but without the achievement-firefox and coloring.
![selection_001](https://cloud.githubusercontent.com/assets/7059890/7243305/ae67dca0-e799-11e4-96b2-f3a6ca7b8ca1.png)

And now I know how to do Paint-like editing on Linux. I don't know whether that's a good or bad thing.

**Comment by hairlessbear** [comment]
One more thing: although the avatar coloring is likely caused by the same error (an issue with `profile.contributor` not being passed properly), it's using a different function for coloring, [`userLevelStyle`](https://github.com/HabitRPG/habitrpg/blob/e1a623d3e09b7d6ae8bb63dfbf6ad6fd164eeb1f/website/public/js/controllers/rootCtrl.js#L48), on [this line](https://github.com/HabitRPG/habitrpg/blob/eddade48a4e40971d9a1e98021e35b0ab6da267d/website/views/shared/header/avatar.jade#L90).

**Comment by gisikw** [comment]
To clarify here, the issue was not that `profile.contributor` wasn't being passed - rather it was that the `userLevelStyle`, `contribText`, etc were not available inside that scope. Anyways, fixed in the PR :)

**Comment by hairlessbear** [comment]
@gisikw See, this is why I really need to learn Javascript. Thanks for the clarification, and for fixing it!

**Comment by gisikw** [comment]
Haha, no worries. It's a combination of Angular being weird, and a bit of code-abuse to provide a global scope.

**Comment by crookedneighbor** [comment]
I figured that was the issue, but hadn't had time to investigate. Thanks!
