### ISSUE TITLE
Reorganizes task list

### ISSUE THREAD

**Issue by iatecthulhu** [HabitRPG/habitica#5054]
Every so often items on the task list reorganize and I have to put them back in the order I prefer. It would be better if the organization didn't shift about wantonly.

**Comment by deilann** [comment]
Is it just To-Dos?

**Comment by iatecthulhu** [comment]
Yes, just the To-Dos.

**Comment by deilann** [comment]
See this ticket for a workaround and why it's happening: https://github.com/HabitRPG/habitrpg/issues/2606
