### ISSUE TITLE
PM Notification Confusing to Get Rid Of

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5056]
When you have a PM, you get a number count by social. However, clicking on social does not take you to the PM -- it takes you to the Tavern. In order to access the PM (and get rid of the notification number by Social) you have to click on the menu button next to social and then click on Inbox.

To me, that's just not logical. Either PM notifications should go with the other chat notifications and can be handled that way or maybe if you have a PM and you click on social it takes you to it, but if you don't, it takes you to the Tavern.

That inconsistency would drive me bonkers, though.

Thoughts @AnitaYCheng?

**Comment by lemoness** [comment]
I like the number by Social, but I think that there should then also be a
number by Inbox, so you can see where the notification is! This also leaves
us the potential to expand notifications to other things as well (such as #
of mentions in the Tavern, for example).

**Comment by crookedneighbor** [comment]
I would like something like this: 

![screen shot 2015-04-21 at 8 05 41 pm](https://cloud.githubusercontent.com/assets/2916945/7265607/db4739b4-e861-11e4-90bb-6c31324b06de.png)

Number is a separate button that is a shortcut to inbox, social opens up the tavern, and the menu button expands the social menu.

@lemoness I like the idea of expanding to include Tavern mentions, but that'll require a lot of (necessary) rewriting of the chat system. Maybe there number button would open a new page of social activity information?

**Comment by lemoness** [comment]
@crookedneighbor I like that solution! Don't worry about the Tavern mention
notifications right now - since chat needs lots of other things overhauled
before we focus on that, there's nothing pressing about it.

**Comment by deilann** [comment]
I think that might work. Not sure. I just know when PMs were first
implemented, it took me quite some time to figure out what I was supposed
to do with that number.

**Comment by AnitaYCheng** [comment]
I like @crookedneighbor's solution too. :smile:  Adding the number to its corresponding menu link would also be very helpful!

**Comment by crookedneighbor** [comment]
@deilann re-open this if the pr doesn't solve your issue.

**Comment by deilann** [comment]
kk :) Thanks for the quick solve.
