### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5057]
Right now, many new users don't have a sense of how much cool stuff is still awaiting them. It would be great to have a "Next Milestone" button to give them a goal to work towards. Possibly under the Mana bar?

Suggested Milestones:

4: Pets + Mounts Unlocked
10: Class System Unlocked
11: First Skill Unlocked
12: Second Skill Unlocked
13: Third Skill Unlocked
14: Final Skill Unlocked
15: Quest Line: Attack of the Mundane
30: Quest Line: Vice the Shadow Wyrm
40: Quest Line: The Golden Knight
60: Quest Line: Recidivate the Necromancer
100: Free Orb of Rebirth
##

**Comment by TheHollidayInn** [comment]
This is awesome! I was also thinking something about "Recommendations" on what to do next. As in, join a party, join a guild, etc. I'll take a look at this issue this weekend unless someone else wants it.

**Comment by AnitaYCheng** [comment]
Left this comment under #5062, but would also like to bring the discussion here since @lemoness mentioned it:

My concern about putting a milestone bar under the mana bar is that the role of the milestone bar doesn't match the rest of the bars. The other 3 bars mark progress _within_ the level, to so say, so the units are a lot smaller and they visually change more readily. The milestone bar's units are "level" which will go up a lot more slowly than the others. Since they have different roles, they should be grouped separately.

Although I'm not quite sure where it should go if not in the header with the other bars. Just wanted to add my thoughts about grouping.

**Comment by AnitaYCheng** [comment]
Responding to @lemoness's comment in #5062, but in a more general way:

Are we envisioning this to be a persistent reminder, or maybe a minimized icon that can expand to hold more information when the user taps on it? If the reminder is persistent and the milestone takes a long time to achieve, they might ignore it. But I can also envision how some might want it persistent, like a motivational Post-It or poster.

**Comment by lemoness** [comment]
Is there a reason to comment here instead of on the pull request? I'd
prefer we consolidate the commentary to one or the other.

I think that it should be persistent, but maybe we could experiment with
having a simple number counter or something like that (3 levels to go!) to
keep it engaging... but I don't think it should be a bar like the other
bars.

**Comment by deilann** [comment]
Yes, if the pull request is abandoned, general info stays in a useful place.

Whatever is done, I'd _really_ appreciate the ability to hide in. In fact,
I don't think it should be implemented without some way to hide it for
older users or users who want to be surprised. Or users who don't care and
thinks it's taking up valuable space.

**Comment by TheHollidayInn** [comment]
Yea, I guess I went a little overboard with the bar. I wasn't sure what "style" I was needing to use.

Either way, the functions are in place, so I can easily change the style to some sort of text display.

I can add a hide feature, but should I make this a local store or a user flag?

**Comment by deilann** [comment]
user flag

If users are using it to hide spoilers and then they logged on somewhere
else and suddenly got hit in the face with it... that would suck.

If users are using it because they've been on the site for over two years
and it's annoying, they wouldn't want to have to hide it everywhere.

**Comment by Alys** [comment]
We've decided to go in a different direction with this. Closing
