### ISSUE TITLE
data.habitrpg.com is down: "No server is available to handle this request"

### ISSUE THREAD

**Issue by me-and** [HabitRPG/habitica#5059]
Clicking the "Data" button at the top of the screen sends me to [data.habitrpg.com](http://data.habitrpg.com/?uuid=1186f4a9-a39c-4448-bc18-1c4e00e818bc), but the server there appears to be down, returning the following (as assembled from Chrome's developer tools):

```
HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

[Checking with isup.me](http://isup.me/http://data.habitrpg.com/?uuid=1186f4a9-a39c-4448-bc18-1c4e00e818bc) indicates it's not just a problem for me.

[The data display tool itself](https://oldgods.net/habitrpg/habitrpg_user_data_display.html?uuid=1186f4a9-a39c-4448-bc18-1c4e00e818bc) appears to be working just fine, so it does look like it's HabitRPG at fault.

**Comment by hairlessbear** [comment]
It looks like this may be fixed (at least, it's working for me). Try it again.

**Comment by hairlessbear** [comment]
More accurately, they seem to have added a redirect to the data display tool. But at least the link doesn't lead to a dead page anymore.

**Comment by me-and** [comment]
Yes, it seems to be working again now!

**Comment by Alys** [comment]
@hairlessbear FYI that redirect has always been there. It must have temporarily stopped working?

**Comment by hairlessbear** [comment]
@Alys I guess so? This occurred at around the same time that there were other issues with the site (see #5061 and [#4951](https://github.com/HabitRPG/habitrpg/issues/4957#issuecomment-95220955)), maybe it was related?

**Comment by gisikw** [comment]
Those issues were strictly within the compiled JS, so I don't think it likely.

Possible that redirect isn't present during a deploy though?
