### ISSUE TITLE
Everything dissapeared

### ISSUE THREAD

**Issue by syntapy** [HabitRPG/habitica#5061]
My list of ToDos, dailies, and habits, all dissapeared. I tried reloading the page. I'm a relatively new user: I had my first level-up last night, now everything is gone.

ID: 2b0e50ec-ffe5-4dae-a927-75777289231f
Browser: Firefox 37.0.1
               Firefox for Ubuntu Canonical 1.0
Browser Plugins: Vimperator 3.9
                            NoScript 2.6.9.22 (All scripts except googleanalytics were enabled)
                            LastPass
Operating System: Ubuntu 14.04

**Comment by taneltomson** [comment]
Same problem.

**Comment by paglias** [comment]
@syntapy @taneltomson sorry about this! all your data is safe and if you reload everything should be ok.

**Comment by taneltomson** [comment]
All restored, thanks.

**Comment by syntapy** [comment]
Thanks a bunch! No problem. I really appreciate you doing this software.

"Arts, crafts and sciences uplift the world of being and are conducive to its exaltation."

**Comment by syntapy** [comment]
I'm kinda curious though: what happened?

**Comment by paglias** [comment]
@syntapy still investigating but probably there was a bunch of code which prevented the tasks from displaying. It's a problem on the client side the data was transmitted correctly but couldn't be shown.
