### ISSUE TITLE
Static.Front page speech testimonial bubbles off center/not aligned properly.

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5067]
Hello! I went and checked back onto the static front page and everything looks a lot better now and It's a lot easier to read the text without it moving away. I did however notice a small issue with speech bubble placement and alignment. On the "Players use HabitRPG to Manage" section, the subsections of "School" and "Chores" have a misaligned speech bubble.

Here are some photos to help.

![staticfrontspeechbubblemisplace1](https://cloud.githubusercontent.com/assets/7588148/7289480/737a9e40-e936-11e4-872a-0d87896098ca.png)
(Chores problem location: -popover.content)
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L409

---

![staticfrontspeechbubblemisplace2](https://cloud.githubusercontent.com/assets/7588148/7289481/797adcb0-e936-11e4-84e0-fdae5f22b2ae.png)
(School Problem Location: -popover.content)
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L328

---

This is what the normal line of code should be looking like:
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L372

I will shortly post a pull request with an easy fix to the problem. I hope that since the issue is so small that it will alright to post the pull request as well as I have worked on this file before.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb
##

**Comment by lemoness** [comment]
Good catch!

**Comment by Rbrinkley** [comment]
Thanks! I also found another misalignment on this section
![staticfrontspeechbubblemisplace3](https://cloud.githubusercontent.com/assets/7588148/7289667/cf5457fe-e938-11e4-9c77-5d8c4e223389.png)

**Comment by librarianmage** [comment]
Should this wait until the redesign?

**Comment by paglias** [comment]
Not sure, it can be worked on but it'll be overwritten by the redesign.

@Alys @crookedneighbor ?

**Comment by Alys** [comment]
I think it would be best to leave it to the redesign, so I'm marking it on hold. Thanks @MathWhiz!

**Comment by lemoness** [comment]
The front page has been updated and this is no longer relevant, so I am closing this ticket!
