### ISSUE TITLE
Habits reset to neutral?

### ISSUE THREAD

**Issue by FireSidoni** [HabitRPG/habitica#5069]
This is the second or third time this has happened to me in the past week or so (=since I started HabitRPG). When I sync or refresh the page, there's some chance that some or all of my habits will reset to neutral yellow. Past progress still shows up, and I still have all the money and XP from those habits, but they're visually reset, and pop back to giving me a full 1GP/6XP on completion. I've only seen it happen when I refresh/sync from the task page, but I think that's also the only place I've done it from, so that's not actually that informative.

User ID is a7e2e372-e60c-4ca1-acfa-2b7298a4aaf7; Mac OS X 10.8.5; Chrome 42.0.2311.90; and the Javascript error console popped up "Error in event handler for (unknown): TypeError: Cannot read property 'length' of undefined
    at chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:225:20handler @ extensions::uncaught_exception_handler:8
tweet_button.46489b28ee1023601b810a443ee8af43.en.html:1Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
ping:1 Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains." (This is the most recent time; I didn't check the other time(s).)

**Comment by deilann** [comment]
Are they + only or - only Habits?

If so, this is expected unless you're doing them many times a day. Because
they only go in one direction, they trend back to neutral (halved value
every day) at cron.

**Comment by FireSidoni** [comment]
... really? Huh. Didn't realize that was a thing. So if they're set as +/- Habits, they won't do that?

**Comment by deilann** [comment]
That's correct. +/- Habits won't do that.
