### ISSUE TITLE
Scammed by the Rewards system

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#507]
I had 30 gold coins. I clicked to buy a 15gp Helm and nothing happened, I clicked it again and realized that not only did I not receive the Helm on my character I lost 30gp. 

Thanks, Obama!

**Comment by horusofoz** [comment]
@loldude101 I don't suppose this corrected it self after a refresh or something?

**Comment by loldude101** [comment]
No, I tried everything but nothing worked.

On 2013-02-27, at 2:41 AM, horusofoz notifications@github.com wrote:

@loldude101 https://github.com/loldude101 I don't suppose this corrected
it self after a refresh or something?

—
Reply to this email directly or view it on
GitHubhttps://github.com/lefnire/habitrpg/issues/507#issuecomment-14160955
.

**Comment by lefnire** [comment]
Hey @loldude101 , just [restore your GP](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account) for now while we work on these bugs

**Comment by loldude101** [comment]
It's not that big of a deal for me, I just wanted to make you aware of the
issue so hopefully nobody else it hurt by it.

On 27 February 2013 09:26, Tyler Renelle notifications@github.com wrote:

> Hey @loldude101 https://github.com/loldude101 , just restore your GPhttps://github.com/lefnire/habitrpg/wiki/Restoring-Your-Accountfor now while we work on these bugs
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/507#issuecomment-14176005
> .

## 
- Igor Demchenko http://goplus.us/igor-demchenko

**Comment by lefnire** [comment]
Gotcha.

**Comment by horusofoz** [comment]
@loldude101 IS this still occurring for you?

**Comment by loldude101** [comment]
No.

On 2013-04-01, at 1:03 AM, horusofoz notifications@github.com wrote:

@loldude101 https://github.com/loldude101 IS this still occurring for you?

—
Reply to this email directly or view it on
GitHubhttps://github.com/lefnire/habitrpg/issues/507#issuecomment-15704426
.
