### ISSUE TITLE
Make Dailies Refresh While in Inn

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5070]
When the Inn was originally devised, Dailies were frozen because we wanted to discourage cheating. Since then, we've taken a much more laissez-faire approach to cheating (it's only cheating if it's not motivating to you, and even then, you're only cheating yourself), and we've also gotten a lot of feedback from users who find it frustrating that their Dailies don't reset while they are resting in the inn. This sometimes leads to people leaving HabitRPG during a time when it could be most helpful, for example during finals or a flare-up of illness, or forces them to use cumbersome work-arounds when they are already stressed or sick.

The only change to make here would be to make the Dailies refresh every day, without causing damage, while you are resting in the Inn. You'd still get full credit for checking them off (as if you were checking a grey Daily) and you still wouldn't attack a boss or collect quest items until you checked out of the inn.

**Comment by hairlessbear** [comment]
@lemoness, I have a question. Do you want the dailies to reset every day, no matter what, or reset when cron runs? Running it with cron seems like that would give the desired functionality since they need to open the site to leave the inn, which would trigger cron and reset their dailies.

**Comment by hairlessbear** [comment]
If it's cron, I'm almost positive I have a working fix ready to go.

**Comment by Alys** [comment]
cron runs every day, whether you are in the Inn or not (IF your account is active in some way on that day). When you are in the Inn (`preferences.sleep` is true) then most of the functions of cron are not executed. So this change needs to be made to the cron code for the case when `preferences.sleep` is true.

Note that Dailies must reset on cron even when the player does not leave the Inn. However the normal health loss for Dailies must not happen.

Feel free to do a PR for your fix if you still think it is correct!

**Comment by lemoness** [comment]
The desired functionality is that every new day when you
log in, your Dailies reset - but if you are in the inn, they shouldn't
damage you. Does that make sense?

This shouldn't be dependent on leaving the inn.

**Comment by lemoness** [comment]
Aha, Alys has clarified! Editing my post :)

**Comment by hairlessbear** [comment]
I'm currently testing it to make sure it works! Interestingly, I actually didn't write the fix myself; I found it buried deep in the HabitRPG codebase. 

When looking at index.coffee, I noticed an [intriguing comment](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1486) on the cron code for the inn:

> User is resting at the inn. Used to be we un-checked each daily without performing calculation (see commits before fb29e35) but to prevent abusing the inn (http://goo.gl/GDb9x) we now do _not_ calculate dailies, and simply set lastCron to today

It took a lot of digging, but I [found the code referred to in the comment](https://github.com/HabitRPG/habitrpg-shared/blob/d42ac5d53ca077ebc746d8d0f48cc1f51e37ae63/script/algos.coffee#L326). It was way back in the commits of the habitrpg-shared repository. I modified it slightly so it will work on the current system, but I basically didn't write it.

**Comment by Alys** [comment]
Nice! Saved time, re-used code, validated the existence of that comment. A win for everyone!

**Comment by hairlessbear** [comment]
Ha, it works! I'll commit and create the PR momentarily. Should I change the comment as well?

**Comment by Alys** [comment]
Yes, please.

**Comment by Alys** [comment]
@lemoness We should probably have new words to go around the Rest / Check Out button. Would you like to write them or should we?

**Comment by lemoness** [comment]
Welcome to the Tavern! Stay a while and meet the locals. If you need to
rest (vacation? illness?), I'll set you up at the Inn. While checked-in,
your Dailies won't hurt you at the day's end, but you can still check them
off.

Be warned: If you are participating in a Boss Quest, the Boss will still
damage you for your party mates' missed Dailies!  Also, your own damage to
the Boss (or items collected) will not be applied until you check out of

## the Inn.

How's that?

**Comment by Alys** [comment]
@hairlessbear Would you like to add the text from Lemoness's comment above to your PR?

**Comment by hairlessbear** [comment]
@Alys yup; I'll do it tomorrow.

**Comment by hairlessbear** [comment]
@Alys @lemoness I have a small suggestion for the wording of the last sentence. Could we change it to "Also, you can't damage the Boss (or collect quest items) until you check out of the Inn."? That seems a little clearer to me. The current wording sort of implies that the damage they do while at the inn is cumulative, and will be counted all at once when they check out.

**Comment by Alys** [comment]
The damage (or items collected) is cumulative but isn't applied until a
full cron runs after checking out of the inn. I guess the current wording
does imply that it's applied immediately upon checking out.

**Comment by hairlessbear** [comment]
Ah, I didn't realize it was cumulative; my mistake. In that case, I rescind my suggestion; I think the wording it fine.
