### ISSUE TITLE
Improvements to Challenges edit and save buttons

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#5071]
- moved to https://github.com/HabitRPG/habitrpg/issues/5754 <strike>When the join button is clicked, the filters appear to reset to "either", but the radio buttons don't revert back to either. Clicking on the desired radio button again, even if it's already selected corrects the behavior. My desired behavior is that it remain filtered.</strike>
- this no longer happens <strike>Clicking the leave button causes the selected challenge to disappear. Forcing a refresh to see it again. There may be an intentional reason for this, but I do not know what it is.</strike>
- When a challenge is created, I would like a second save button to appear at the bottom right of the challenge. I find it annoying that you have to scroll back up to the top to save.
- When a challenge is edited, then saved, the edit button is no longer available until a refresh or you click on the challenge name.
##

**Comment by Alys** [comment]
I've edited the top post to mark one item as completed and to move another item to another issue (link provided in top post).

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer be relevant afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Challenges are now handled differently, so I am closing this ticket.
