### ISSUE TITLE
System Messages Show Up in @ Tagging

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5072]
If you are in a party that has recently had system messages (for quests and whatnot) and you use @ tagging to select the name of a member of your party, then use the arrow keys to choose the name, you will sometimes pause on what looks like the line between two names. Selecting this give you nothing.

Nothing at all.

I'm pretty sure what's going on here is that it's letting you choose the system messages as a valid choice, but because they have no display name to choose, the world ends.

With nothing.

**Comment by crookedneighbor** [comment]
@joyclark you're our resident autocomplete controller expert now :wink:, want to take a stab at this?

**Comment by joyheron** [comment]
@crookedneighbor I can take a stab at it. But I promise nothing! =)
Is there an easy way to create a system message so that I can test this out?

**Comment by crookedneighbor** [comment]
Start a party on your local account, using the debug menu in the footer (only available in dev environment), grant yourself some gems, buy a quest and start it, in the debug menu click 1 missed day, refresh. Your party page should now have a chat from the system about the quest progress.

**Comment by joyheron** [comment]
Are there any other kinds of messages which can come up in the tests? I adapted my filter function to filter out system messages, but if there are other kinds of messages, I would like to adapt the tests...My implementation actually threw an exception (EEK! so disgusting! I am ashamed!) because I didn't know that system messages were included in the list....

**Comment by crookedneighbor** [comment]
@joyclark To my knowledge, the only kinds of messages are messages from actual users and system messages.

**Comment by SpenserJ** [comment]
If system messages are filtered out now, and the only other messages are from users, we should be safe to close this.

**Comment by Alys** [comment]
I think this is fixed. We can reopen if I'm wrong.
