### ISSUE TITLE
(WEB) Text overflow in spells section - Czech

### ISSUE THREAD

**Issue by Rohlik** [HabitRPG/habitica#5076]
Hello there!
I found this little bug in my Chrome browser. Look at word "Mana". "a" is under button when.
I use 1366x768 resolution on my monitor and "Čeština" language.
![spells](https://cloud.githubusercontent.com/assets/2051154/7319554/bbdac6e0-ea96-11e4-82ac-0884d189bfd4.PNG)

**Comment by NotGonnaGitUs** [comment]
I looked into this and it is a translation error in the Czech language. In "character.list" {"mp": "Mana"} is the translation, which by convention, has been {"mp": "MP"} in almost all other languages.

I also tried to post the issue on Transifex but changing languages to Czech in my profile did not give me sufficient privileges to post an issue in the Czech specific board. Hopefully @paglias  or @Alys can look into it.

**Comment by paglias** [comment]
@NotGonnaGitUs https://www.transifex.com/projects/p/habitrpg/translate/#cs/characterjson/21450702 it's ok?

**Comment by NotGonnaGitUs** [comment]
Yep! This should be fixed now.

**Comment by Rohlik** [comment]
Confirm!
