### ISSUE TITLE
My party's button keeps saying "Join" instead of "Leave"

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5077]
Multiple times a day, when I go to my party's page, the button says "join" instead of "leave". I haven't figured out how to reliably reproduce the issue yet, and it goes away after a page reload. 

![selection_003](https://cloud.githubusercontent.com/assets/7059890/7321317/7093c898-ea6f-11e4-8193-303854dff664.png)

**Comment by gisikw** [comment]
Just to confirm the issue - you have > 15 members in your party, yes?

**Comment by crookedneighbor** [comment]
Hmmm... I think that button should only appear when on a public guild that you are not a part of. Thanks for the report. Should be able to pretty easily make that explicit to only apply to guilds.

**Comment by hairlessbear** [comment]
@gisikw Yes, 31 to be specific.

**Comment by gisikw** [comment]
Yeah, this is a known issue (wherein the join/leave button is based on the group members, but we can only return 15), though we've done a workaround for guilds. I should be able to get a workaround for parties working.

**Comment by hairlessbear** [comment]
Cool, I'm glad this one will be easy to fix.

**Comment by Alys** [comment]
I believe this is fixed, based on the linked PRs, so I'm closing this. @hairlessbear Tell me if it's not and I'll reopen it.
