### ISSUE TITLE
armor not working on undeserved rewards

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#508]
I took an self-made reward (20) when I had no money and it subtracted 20 hp.  I had leather armor, a leather helm, and a wooden shield, so shouldn't that have made a difference?

**Comment by Pandoro** [comment]
I think rewards are actually a fixed price which is not something you can change by having armor. At least I would think that it should be like this!

@lefnire  maybe you can clarify this? I see that the labels are actually listing this as a bug, but I wonder if this is really a bug.

**Comment by wc8** [comment]
The question is whether armor should protect you from HP loss from buying a reward you don't have the money for.  If equipment protects from all forms of HP loss (simplest) then it's a bug. If equipment doesn't protect from self-inflicted HP loss via "stolen" rewards, that needs to be clear to the user—in that case it's a support issue. I can see a reason for both approaches.

I agree that armor/equipment shouldn't make rewards less expensive (GP). Changing the price of custom rewards by equipment modifiers would be confusing. Equipment could give you a boost the value of your tasks, in that sense making reward purchases easier.

**Comment by cleave29** [comment]
If self-made rewards are not modified by armor and them's the rules, then them's the rules.  
Personally, I would hope for armor to protect me from damage from undeserved rewards.  How would we figure out what other people think?
I can't buy items with money I don't have and I am _very_ much in favor of that.  Please keep that the way it is.

**Comment by Pandoro** [comment]
I personally feel against protection  of stolen rewards. But I agree with @wc8 that it should be clear. I think we should get around to writing good tutorials and FAQs once the forum is there, this way people will not wonder and everything is cool :)

**Comment by horusofoz** [comment]
What was the required action for this ticket? Is it just adding the info to the FAQ?

**Comment by cleave29** [comment]
Either adding it to the FAQ, changing it so armor works against self-made undeserved rewards, or voting on it.

**Comment by wc8** [comment]
I think @lefnire needs to weigh in on whether this is a bug or not. 
If he says no, armor isn't supposed to protect against "stolen" rewards, then a FAQ is in order, else a fix and/or voting as @cleave29 said.

**Comment by lefnire** [comment]
I'm actually neutral on the issue, I'll defer to you @wc8. If you think we should apply armor though, should we "minor" tag this, or is it actually important?

**Comment by cleave29** [comment]
OK, sounds like there are bigger fish to fry.  
How about put it in the FAQ and call it good?

**Comment by wc8** [comment]
I'm neutral, as well. (No idea where/when important came in, changed it to minor.) 
FAQ entry: [What are the benefits of wearing armor?](http://community.habitrpg.com/faq-page#n78)

**Comment by cleave29** [comment]
Thanks for adding it to the FAQ.
