### ISSUE TITLE
Subscribers not receiving items consistently when opening April's gifts (fixed on refresh)

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5081]
This happened to me (UID: 8ac7242d-8f18-4d6f-b4f4-8f6302f7fa0b) and at least one other user in the tavern (Drakani; UID: fc56b96f-4911-4e42-a937-cf7a9a50f637). The gift box icon displayed 2 as expected, but clicking on it just made the number go down; no popup displayed, and no new items were in the inventory.

Fortunately, refreshing the page caused the gift number to go back to 2, and it functioned as expected this time. So the issue may have been a one-off; I figured I should report it anyway, just in case :)

**Comment by deilann** [comment]
The issue is known: you don't have all the new code yet. So you need to
refresh to get it.

**Comment by hairlessbear** [comment]
Got it. I'll go ahead and close this.
