### ISSUE TITLE
Inbox Text in Social tab bubble isn't aligned with other sections

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5083]
Hello! I noticed this as I was checking my social. It appears that the text for "Inbox" isn't aligned up properly to the other text lines underneath it. I'm including a photo with an added green line to illustrate it.

![socialtabinboxspacing](https://cloud.githubusercontent.com/assets/7588148/7331177/ebed2424-eacb-11e4-9173-3ee017fce9da.png)

It's a minor issue but I just wanted to make sure it was noted. 

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by crookedneighbor** [comment]
Oh yeah, that was my fault. Will fix in the next couple of days.

**Comment by crookedneighbor** [comment]
Fixed. Should be fixed on the site at the next deploy.
