### ISSUE TITLE
AutoComplete in Group Chat has weird behavior when finding users

### ISSUE THREAD

**Issue by joyheron** [HabitRPG/habitica#5084]
![chat](https://cloud.githubusercontent.com/assets/1502724/7332458/8a394c74-eb40-11e4-81cb-f1621d1e294e.png)

Typing "@" and a given letter doesn't automatically filter the user names that way that it would be expected.

**Comment by joyheron** [comment]
I would like to test this out and try to fix this bug. I've been wanting to learn AngularJS and I wouldn't mind getting a Contributor badge at some point either, but to do that I think I need to get a feel for the code base by fixing some small annoying minor bug.

**Comment by Alys** [comment]
It would be lovely if you'd work on this! Thank you!

It's actually already been reported here: https://github.com/HabitRPG/habitrpg/issues/1866
so I'm going to close this issue as a duplicate, but if you'd like to put a brief comment in that other issue to say that you'll work on it, that would be great! If you run into any trouble or have any questions, you're welcome to ask for advice in that issue. Also, there's some useful information in [Guidance for Blacksmiths](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths) and the linked pages, if you haven't already seen them.
