### ISSUE TITLE
Did not get sand hourglass after subscribing 3 months on the go with gifting-option (paypal workaround)

### ISSUE THREAD

**Issue by proxforge** [HabitRPG/habitica#5086]
"Tyler und Vicky Du brauchst eine Mysteriöse Sanduhr, um die mysteriösen Zeitreisenden herbeizurufen! Abonnenten verdienen für alle drei Monate, in denen sie hintereinander abonniert haben, eine Mysteriöse Sanduhr. Komm wieder, wenn du eine Mysteriöse Sanduhr hast, und die Zeitreisenden werden dir ein Abonnenten-Set aus der Vergangenheit holen... oder sogar aus der Zukunft."

I did not get one, can u fix this?  7374977d-317f-4764-9234-31c870977c48

**Comment by Alys** [comment]
Sorry about that @j0hnnycode! I have given you one hourglass and increased your gem cap by 5. To see the changes, you might need to reload using your browser's refresh button. 

I'm going to close this now, but if they haven't appeared, comment here and we will keep helping you!
