### ISSUE TITLE
Gem info bubble over overlaps gem image 

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5088]
Hello! I know this is a really minor issue but when I was looking for any inconsistencies I noticed that the arrow for the info bubble that pops out when you mouse over the gem icon slightly overlaps the gem image and isn't aligned with the same position of the info bubbles of the gold and silver ones.

I've included images to show the issue and ones for comparison.

---

Gems:
![gemsarrowoverlapissue](https://cloud.githubusercontent.com/assets/7588148/7335222/83b273fe-eb76-11e4-9881-f77ebab268a9.png)

---

Gold (For Comparison):
![gemsarrowoverlapissuegoldcomparison](https://cloud.githubusercontent.com/assets/7588148/7335224/924985ba-eb76-11e4-8841-148e84cc099a.png)

---

Silver (For Comparison):
![gemsarrowoverlapissuesilvercomparison](https://cloud.githubusercontent.com/assets/7588148/7335231/9cb6966e-eb76-11e4-929d-441a9e3ebede.png)

---

Again I know this is a minor issue, but it might just be placement of the image hitboxes that might be causing the slight overlap. 

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by crookedneighbor** [comment]
It's aligned to the exact center of the gem image + the number of gems you have. So for me, with my gems in the double digits, it looks like this:

![screen shot 2015-04-25 at 6 40 11 pm](https://cloud.githubusercontent.com/assets/2916945/7335304/880576b4-eb7a-11e4-9c78-b70bba1260c8.png)

If I manipulate the HTML dom to increase the number of digits, you can see that it adjusts the exact position to be in the direct center:

![screen shot 2015-04-25 at 6 40 59 pm](https://cloud.githubusercontent.com/assets/2916945/7335310/d0652922-eb7a-11e4-8e07-5d56935e3cc5.png)
![screen shot 2015-04-25 at 6 41 17 pm](https://cloud.githubusercontent.com/assets/2916945/7335312/d0683a54-eb7a-11e4-82e6-6b772ea4a1bc.png)
![screen shot 2015-04-25 at 6 41 32 pm](https://cloud.githubusercontent.com/assets/2916945/7335311/d0683874-eb7a-11e4-821b-282d1dc8f220.png)

I'm going to close this, but if you think there's still an issue here, feel free to re-open it and I'll re-visit it.

**Comment by Rbrinkley** [comment]
I just still think it looks odd how its significantly higher up than the other two image's infoboxes are. I think that it it would be best to just have the info bubble appear more in line with the other infoboxes. It's a really small issue, so I'm still on the fence about reopening it. I just would prefer that they would look consistent, but I am not familiar with this adaptive code so I don't know which would work better.

The thing is with the gems, not many people have a significant amount of gems, most if any, have none. Maybe most people who have them will at most have gems maybe in the 3 digits. I doubt that anyone would have more than 999 gems unless they bought them or are an admin. I think in this case it would make more sense to have an infobox that is aligned more with the other two infoboxes.

What do you think? You seem to have much more knowledge about this type of code then me, so I don't want to question this issue too much.

**Comment by Alys** [comment]
Admins do not typically have more than 999 gems.

**Comment by Rbrinkley** [comment]
Further proving my point. I don't want to make such a big issue out of this, if it takes a lot of code fixing to resolve this issue then I would rather not inconvience someone to fix such a small issue. I just think that if the info bubbles were in a consistent position, regardless of gem/gold/silver amount, then the presentation would look better. 

Again, really minor issue. Sorry if i'm making a really big deal out of this. I never intended to do so.

**Comment by crookedneighbor** [comment]
Oh, you are right. I was looking at the horizontal position, which is consistent, but the vertical position is definitely significantly higher. I wonder why that is?

Gonna re-open the issue.

**Comment by crookedneighbor** [comment]
@Rbrinkley How's this look?

![screen shot 2015-04-25 at 9 05 27 pm](https://cloud.githubusercontent.com/assets/2916945/7335562/f1825d6e-eb8e-11e4-9199-b838a57547ff.png)

**Comment by Rbrinkley** [comment]
I like it a lot better. How does it match up next to the other info bubbles? I think a comparison would help me visualize it a lot better. Thanks for doing this.

**Comment by crookedneighbor** [comment]
It's 2 pixels higher than the the other two (horizontal line added to make it obvious), but it is much better now that it's not overlapping on the gem image.

![screen shot 2015-04-25 at 9 05 27 pm](https://cloud.githubusercontent.com/assets/2916945/7335610/20505a54-eb91-11e4-91c6-41bdcd320679.png)

**Comment by Rbrinkley** [comment]
It looks a lot better now then. I hate to ask you this but would you mind moving it down those two pixels? Now that you mentioned it it would bother me a lot knowing that they aren't aligned in the same pixel plane. I know its just 2 pixels but I don't think it would be a lot of work to change it. Then again I am not familiar with the code so I might be completely wrong. Thank you again.

**Comment by Rbrinkley** [comment]
Thanks! I really appreciate it.
