### ISSUE TITLE
iOS UI: Comments

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#509]
I talked to @lefnire about a native iPhone client for HabitRPG.  As the API is currently limited, I can only get so far, but this also allows me to spend more time on the UI. 

Some screenshots (There is mostly no content, these are just to get a feel for the tab bar, segmented controller, navbar and color scheme):

For all addition of experience/gold, their will be simple slide down alerts, as in Instagram or Facebook to notify user of increase/decrease in area.

![Home](https://f.cloud.github.com/assets/3122471/190762/5f634230-7f0d-11e2-93c1-19c1dec2d0ca.png)

**The "Home Tab" would have a bar with the users health (in red), their experience (in that goldish yellow) as well as their level, username and, via a settings button, access to their apiTokens and UserIds.  They would also be able to join parties from this view.  The Home tab would also have the user's avatar as well as token count, gold and silver coins.**

![Habits](https://f.cloud.github.com/assets/3122471/190763/613f93e2-7f0d-11e2-9a29-7f3cfac589a9.png)

**The "Habits Tab" would have all habits, ability to delete and add habits, as well as see graphs (if included in the API and in another view).  They could + or - their habit from this view.**

![Daily](https://f.cloud.github.com/assets/3122471/190765/709d77f0-7f0d-11e2-85bf-99b8e58ce93f.png)

**The "Daily Tab" would have the same concept of the Habits Tab**

![Todos](https://f.cloud.github.com/assets/3122471/190767/789ec4c2-7f0d-11e2-81ea-7f75a13cf632.png)

**The "Todos Tab" would have the same concept of the Habits and Daily Tab - ability to edit, delete etc.  However, their will be a possible calendar view, as well as segmented control for Completed and Remaining todos**

![Rewards](https://f.cloud.github.com/assets/3122471/190768/7d895a74-7f0d-11e2-943d-e86d6190dfe3.png)

**The "Rewards Tab" would have the same concept of Rewards system online. Add a reward, purchase a pet, purchase a reward, etc.**

**Comment by tmas** [comment]
Looks pretty nice to me. I'm interested to see how you make it fit the theme of habit as well as the native iOS theme. I guess the home tab will have to be chock full of pixel art and rpg info.

**Comment by tmas** [comment]
As much as a lot of people dislike apps that rely heavily on graphics, I think iOS is a place where trying to integrate pixel art into the interface would really fit the OS theme. I'm not sure how it'd look, but having a custom-ish UI might be interesting if it wasn't too overpowering.

**Comment by horusofoz** [comment]
I've linked to this thread on the [Mobile App Trello Card](https://trello.com/c/FYmitllH) so the relevant devs are aware of your suggestion. Feel free to navigate to the card and add your voice to the discussion around the Mobil App's development direction.
