### ISSUE TITLE
When replying to a user, it requires 2 clicks to choose from the list of users

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5094]
Hello! I noticed this while I was typing out messages to people in the tavern. Whenever you use the @ symbol to start a reply to someone, for example "@Rbrinkley Hello! " , if you try to choose a name from the drop down list the first time you click on a name the name will not appear. 

I am referring to this process here (Names blacked out for privacy)
![chatdropdownlisterror](https://cloud.githubusercontent.com/assets/7588148/7339772/3d8495c2-ec40-11e4-85a1-7a03a21ef5c0.png)

It is only until the second time you try and click that name, a process requiring retyping out the name or at least part of it, then you will be able to click from it and the name will appear.

So the process usually is:
Type out @ symbol **--->** Type out part of name **-->**  List appears **-->** click on intended user**-->** click fails to register **-->** retype entire name or part of name **-->** list appears **-->** click on intended user **-->** click registers and name is transferred to message box **-->** user types out message and sends.

I at first thought it was deliberate. Maybe to prevent accidentally clicking on the wrong name and other things. But I noticed that any name at all you choose from on the list, the first click attempt will not work, but the second attempt will. And every attempt after that will work, so it doesn't seem to be a confirmation click, I think it is just an error or bug involved with the clicking, it gets quite annoying to deal with. 

I'm not sure if this has already been mentioned before, its kinda hard to describe this issue but I just wanted to point it out.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by hairlessbear** [comment]
Huh, interesting. Not sure how to fix it, but FYI, you can select names from the list by traversing it with your arrow keys, and hitting `tab` or `enter` when the name you want is highlighted.

**Comment by deilann** [comment]
Yeah, I've noticed the issue with clicking, but always felt like it was my
fault. Arrow keys work phenom for me, and so I keep forgetting that
clicking _should_ work. Never thought that it would work the second time.

**Comment by Rbrinkley** [comment]
I keep forgetting about the arrow keys, I still prefer clicking, I'm so used to it by now I don't know how I would get out of the habit. Also I find that I would less likely make a mistake in choosing the correct user when using my mouse. So there's that.

**Comment by Rbrinkley** [comment]
Is this the code that might be causing the issue? https://github.com/HabitRPG/habitrpg/blob/1da1160e1061f5adc6cf9f38b0db4dce74a9f872/website/views/options/social/chat-box.jade#L16 or at least any code around it?

**Comment by lemoness** [comment]
This has always been the case for me as well - it reliably takes 2 clicks.
I assumed it was my mouse - guess not!

**Comment by joyheron** [comment]
I _think_ isAtListHidden is set to true as soon as something is typed. For reference, I think the code that controls it is here: https://github.com/snicker/Angular-At-Directive/blob/master/src/at.js#L118-195
(It is one of the bower components that is imported).

If no one sees an obvious answer, I can maybe try to debug it.

**Comment by ghost** [comment]
It seems to me, the issue has been addressed, hasn't it?

**Comment by crookedneighbor** [comment]
No, it still takes two clicks.

**Comment by ghost** [comment]
Yes, please fix this! It has been a problem for months and unfortunately there are no arrows if you don't have a physical keyboard so that workaround doesn't work.

**Comment by ghost** [comment]
Hmmm... I'm not sure why, but I don't seem to face the issue if I disable the adblock plus extension in firefox... @crookedneighbor do you use anything of a kind?

UPDATE: nope, there's something else that influence this behavior. Now I'm not getting the issue even with the extension enabled.

**Comment by LittleRabbitBeta** [comment]
This is a most annoying problem, I thought about reporting it months ago but I figured someone else would...apparently not...and now...well it's been months and I can't remember what changes I'd send elsewhere when this started happening...or not happening as it were. Very annoying because it was a feature that worked and then it was "taken away" but some evilness. Please fix please please please :rabbit:

**Comment by Rbrinkley** [comment]
@GitHubSphinx I know that this isn't related to firefox. But I usually never have adblock enabled on habitrpg for chrome. But I tested it out without the extension being enabled at all and I still had the problem. Maybe adblock is connected to the issue in some way for firefox but I think something else is afoot.

**Comment by joyheron** [comment]
I've done a bit of debugging, and it seems to be a problem with the combination of the ng-show and ng-click functions (which come from the [Angular-At-Directive](https://github.com/snicker/Angular-At-Directive) ). I think the directive defined some weird click behavior, but since the directives are imported from a separate Git repository, I was able to create similar functions in the AutocompleteCtrl so that clicking works correctly. I can do a PR and have someone test out my implementation.

**Comment by Rbrinkley** [comment]
I would love to try that code out but I still haven't set up HabitRPG locally. _Hides behind desk_ .Hopefully it fixes the problem . _Continues hiding behind desk_
