### ISSUE TITLE
Sorting of Red To-do List items

### ISSUE THREAD

**Issue by macdonaldethan** [HabitRPG/habitica#5097]
Once my to-do list items have become red, I seem to no longer be able to sort them. He sort, but when the page refreshes the order is not kept. This seems to only be the case when the items are 'red.'

**Comment by deilann** [comment]
It's actually more likely this: https://github.com/HabitRPG/habitrpg/issues/2606

Follow the workaround there, and you should be able to get the order to stick. :)
