### ISSUE TITLE
Deleted a challenge - lost the gem

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#5099]
I created a challenge with a 40 gem prize.  When I tried to create it I hadn't selected Tavern yet, so I selected Tavern and created the challenge without reviewing again.  Turns out, when I selected challenge, it reset my prize from 40 to 1 gem.  When I tried to edit the challenge, my habit wasn't there, the gem prize didn't allow me to edit the amount, so I deleted the challenge and started from scratch.  But it ate my 1 gem.  I now have only 39 gems and cannot recreate my 40 gem prize.  May I please have my gem back?  Thank you.

**Comment by deilann** [comment]
can't do thay w/o your uuid

**Comment by Memry** [comment]
And I bet  you'll need my ID.  It's 

e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by Memry** [comment]
Wrote while you were writing.

**Comment by deilann** [comment]
fixed

in the future to avoid this award the challenge to yourself. you can change
the title first... usually what i do.

**Comment by Memry** [comment]
Thanks.

**Comment by deilann** [comment]
np! sorry for shortness have two wrist braces on
