### ISSUE TITLE
A purpose of a "silver" (or "platinum"?) coin?

### ISSUE THREAD

**Issue by witalick** [HabitRPG/habitica#51]

**Comment by horusofoz** [comment]
I believe that silver coin is basically a .X of a gold coin. For example when the rewards algorithm decides you deserve 0.8 gold for your 50 push-ups, you get 8 silver pieces. When you reach 10 silver it is automatically rounded up into a gold piece. Make sense?

**Comment by witalick** [comment]
Absolutely. My question was a bit premature. I thought silver "doesn't work" coz I didn't see its growth after some very shallow experiments.

Thanks for reply.

**Comment by horusofoz** [comment]
You're welcome.

@lefnire Close it up.

**Comment by lefnire** [comment]
thanks @horusofoz

**Comment by Flimm** [comment]
I also found this confusing. Could this issue be re-opened, as a TODO item to improve the usability of silver items?

**Comment by lefnire** [comment]
yeah, we'll keep it open. I need to
1. Make silver 100, not 10
2. Add copper
3. Add tooltips

**Comment by horusofoz** [comment]
This has been resolved

**Comment by lefnire** [comment]
vote this card if we want copper added: https://trello.com/card/add-copper-to-gp-system/50e5d3684fe3a7266b0036d6/225
