### ISSUE TITLE
Chrome is making my task disapear

### ISSUE THREAD

**Issue by StudioBrou** [HabitRPG/habitica#5100]
Hi, I noticed a few weeks ago that my taks diseapeared, but only when I open Habit RPG with Chrome, when I swith to Firefox it's fine. In Chrome only the task are blank, all the rest is fine. 
I waited for some time in case it was temporary but it is still the case now and I seem to be the only one on my friend group that have this probleme. Anyone else ?

**Comment by deilann** [comment]
Click "Clear' on your tag filters, even if no tags are selected.

**Comment by StudioBrou** [comment]
I'm so silly. Thank you !!
