### ISSUE TITLE
Quest still active after all participants left

### ISSUE THREAD

**Issue by pantherman594** [HabitRPG/habitica#5101]
Group ID: `c56de723-1487-4bd6-8288-13c3626d8429`
Browser: Google Chrome Version 42.0.2311.90 m

One of my party members started off on a quest, and was the sole participant, but before it was completed he was booted from the party, and now we can't start a new quest. Can you fix this?

**Comment by Alys** [comment]
I've removed the quest from your group and given the quest scroll back to the person who started it. Please reload the party page to see the change. Let us know here if there are any problems.
