### ISSUE TITLE
facebook login is too hard to remember - add reminders for failed logins

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5103]
Surprisingly often, people report that they can't log in (e.g., username or email not accepted) and it turns out that they registered with Facebook but had forgotten they'd done that.

Can we have reminders in a couple of places? For example, in each of the dialog boxes below, could we have a new message under the current message that says something like "Perhaps you registered with Facebook? If you might have, please try logging in with Facebook."

@lemoness @anitaycheng What do you think?

![screen shot 2015-04-16 at 10 26 01 am](https://cloud.githubusercontent.com/assets/1495809/7389278/c50ae084-eeaf-11e4-9731-3ddb8636b4f5.png)

![screen shot 2015-04-16 at 10 25 46 am](https://cloud.githubusercontent.com/assets/1495809/7389282/cb8fbfa6-eeaf-11e4-8e01-216cea4d7bc1.png)

**Comment by lemoness** [comment]
I think this is definitely needed! I have to field questions about this all
the time on social media.

How's this for text:

1.

Uh-oh - your username or password is incorrect.
- Make sure your username or email is typed correctly.
- You may have signed up with Facebook, not email. Double-check by trying
  Facebook login.
- If you forgot your password, click "Forgot Password."

2.

Sorry, we can't find a user registered with email x@x.com!
- Make sure your email address is typed correctly.
- You may have signed up with Facebook, not email. Double-check by trying
  Facebook login.

**Comment by crookedneighbor** [comment]
Looks good to me.

**Comment by Alys** [comment]
@lemoness I love the wording. I've advertised this in Aspiring Coders for a new programmer to do.

If the programmer who takes this up needs any advice, they can ask questions here.

**Comment by cavejay** [comment]
I'm looking into this at the moment. I've not made a contribution previously, so I'm not entirely sure what the process is, I know I just want to help.
I've just been through the process to setup a local habitrpg instance and that's running into errors but I'm wondering if this is actually anything more than a string replacement?

**Comment by Alys** [comment]
Probably just a string replacement, but ideally you would search first to ensure the strings are used in only one place each. Because the new strings are more complex (some HTML formatting), we'd want to see screenshots of them in the dialog boxes.

The process is basically: you'd create a new branch locally (you could work directly in the `develop` branch but it's better not to), do your changes in that branch and test them locally, take screenshots, commit the changed files, push the branch to your own GitHub fork of the HabitRPG repository, then do a  pull request.

In the pull request, you'd write `fixes #5103` (that creates an automatic link between this issue (5103) and your PR, and you'd briefly explain what the PR did, and you'd include the screenshots.

If you need help with your local install, you can describe the problems in the Aspiring Coders guild.

**Comment by Alys** [comment]
If you need help with your local install, you can describe the problems in the Aspiring Coders guild.

**Comment by cavejay** [comment]
I have made the pull request, does everything look okay?
