### ISSUE TITLE
Front page is not translatable

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5104]
See https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade most strings are plain text, we need to move them to locales files.

**Comment by ghost** [comment]
Thank you @paglias !
As it seems to me, there are also some untranslatable lines in https://habitrpg.com/static/contact

**Comment by Alys** [comment]
I've advertised this as suitable for new programmers in the Aspiring Coder's guild.

If anyone takes it up and needs advice about it, post your questions here.

**Comment by ghost** [comment]
Thank you @Alys ! The only difficulty might be that some lines have already been translated on transifex, as far as I remember, so I guess the job will need checking the existing translation aliases.
Should this issue be merged with / linked to https://github.com/HabitRPG/habitrpg/issues/4522 ? I believe static pages are of more importance, actually.

**Comment by Alys** [comment]
No, that issue is already being dealt with. This issue is for a specific
page, it's fine as it is.

**Comment by NotGonnaGitUs** [comment]
I am working on this and am halfway. Should be done in a couple of hours.

**Comment by ghost** [comment]
@NotGonnaGitUs Thank you! And :thumbsup: for your nick!
@paglias Will we be getting new strings on transifex?

**Comment by paglias** [comment]
Of course, you should have them in a few minutes :)
Il 03/mag/2015 21:21, "Sphinx" notifications@github.com ha scritto:

**Comment by ghost** [comment]
@paglias I guess the rest of our team will only see it tomorrow as we wake up - so we are not so quick as you are!
Thank you :clap:

**Comment by NotGonnaGitUs** [comment]
@GitHubSphinx Thanks for your work on translations too!

I tried working on transifex, but translators (this is what I sign up as) are language locked so I couldn't comment on things outside my given languages during sign up. I ended up deleting the account to retry from scratch knowing this fact >.< 
But apparently, once deleted I cannot remake the account either.
