### ISSUE TITLE
Unreasonably huge buff from Tools of the Trade

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#5109]
Got a perfect day buff from yesterday, cast Tools of the Trade from the beta site a few minutes after logging in today. According to the data display tool, which I checked before casting, it should have provided a buff of 3 PER, but instead appears to have buffed me and my party by 57 PER (!!!)

http://i.imgur.com/jd8hvpg.jpg My stat display after casting. This appears identical on both the beta and main site, and while I thought it might be a display issue, the data display tool seems _approximately_ in accord with the site - all attributes according to the site are 0.5 higher than according to the DDT. http://i.imgur.com/psYFiPM.jpg Current MP according to the site is indeed 16.2 (well, 16.18, or 16.1756… in the fix character values display), but max MP is displayed as 166 rather than 165. Unfortunately, I can't recall what my MP recovery amount was.

The only person in my party who doesn't have a 57 PER buff is one of our other rogues (we are a six-person party of four rogues and two healers. it is a boss quest nightmare), who cast Tools of the Trade yesterday and hasn't hit chron yet. Her casting, unlike mine, correctly provided a 3 PER buff if I calculated the spell effect properly as [(0.2 \* 57.5) => rounded up to 3]. http://i.imgur.com/CEALVzf.jpg (+12 perfect day buff for level 25 character, +3 from her casting, +57 from mine)

(57 seems such an arbitrary number. I cannot find what relation it might have to my actual stats. This is a surprisingly disconcerting aspect of this whole thing. Although all of this was a few minutes of mental math while checking every stat display, so my working memory may have dropped some values somewhere.)

**Comment by deilann** [comment]
You say this shows on beta and on prod.

Did you cast the skill on beta or did you cast the skill on prod?

**Comment by GrayDays** [comment]
On beta.

**Comment by deilann** [comment]
There are skill changes currently being tested on beta.

**Comment by GrayDays** [comment]
I figured that might be the cause, since the skill descriptions changed there recently - wouldn't have thought it odd if the change weren't so drastic. If it did indeed happen as intended, I shan't worry.

**Comment by GrayDays** [comment]
I infer, based on the fact that the stat discrepancy between the site and the DDT affects more than just PER, that said discrepancy is unrelated to the increased buff. Is there a reason for this / is it a known issue? I don't remember seeing anything mentioned but I could easily have missed it.

**Comment by lemoness** [comment]
If you are using the beta site - not recommended, as we are frequently
testing potentially buggy features there, and standard features like new
equipment and translations will usually be much slower to arrive - then I
believe the DDT will not be an accurate reflection of your account, since
it uses prod.

**Comment by hairlessbear** [comment]
I'm having this issue on the production site, and with Protective Aura as well. The stats below are a result of my party mates casting Tools of the Trade twice and Protective Aura four times.
![hrpg big stats](https://cloud.githubusercontent.com/assets/7059890/7478406/b2a4048e-f328-11e4-8c54-ef0f92cece80.PNG)

**Comment by deilann** [comment]
We're asking everyone to wait _two weeks_ before giving feedback on the
skill changes.

**Comment by hairlessbear** [comment]
Crud, I forgot about that. Sorry!

**Comment by Alys** [comment]
Also we will probably be more interested in the **effects** of the buffs, rather than the size of the buffs. If after two weeks you are noticing that your healing/damage protection or gold/drops are too high, that would be worth reporting. Simply a large buff might not be a problem if it has no negative impact.

**Comment by hairlessbear** [comment]
I should have been more specific: the reason I was reporting was because I
noticed that I was taking almost no damage for anything, which I really
didn't like. I'll check back in a couple weeks if it's still an issue.

**Comment by remjey** [comment]
Hi, I’ve just stumbled upon this problem on the production website. It has happened each time one of our rogues cast Tools of the Trade. On the other hand, my Valorous Presence spell seems to apply a correct bonus value.

**Comment by Alys** [comment]
@remjey Can you give us more details? What buff were you expecting to get? What buff did you actually get? How many times was Tools of the Trade cast? Which player cast it (their User ID please, which you can find near the top right of their profile, which you see when you click on their name in party chat or party membership list). What is your User ID (to find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu))?

**Comment by remjey** [comment]
@Alys I’m sorry, my bad, I was using a translated wiki article as a reference, but actually it is very outdated. I made the calculations again with the formulas from the english wiki and everything is fine.

**Comment by Alys** [comment]
@remjey Thanks for letting us know!

Would you mind telling us which wiki article it was? We should get that retranslated. I'm really sorry it caused confusion. :(

**Comment by remjey** [comment]
Sure, on http://fr.habitica.wikia.com/wiki/Voleur it says that « Outils de Travail » (Tools of the Trade) will give a PER × 0,03 buff, with examples for PER==50 => buff==1.5 and PER==100 => buff==6.

**Comment by Alys** [comment]
@remjey Thanks! I've posted in the [Commonwealth of i18n - Aspiring Linguists of Habitica](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) guild to ask if someone will update the French page. 

Of course if you'd like to, you'd be welcome to! :) If you're interested in getting involved in wiki translations, we have [Guidance for Linguistic Scribes](http://habitica.wikia.com/wiki/Guidance_for_Linguistic_Scribes) to help you through the process, or [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists) for translating Habitica itself.

**Comment by remjey** [comment]
I see somebody did it already, so I guess maybe next time I spot an inconsistency ;)
