### ISSUE TITLE
Stop reporting vice sites if idle for some time?

### ISSUE THREAD

**Issue by pankajmore** [HabitRPG/habitica#511]
I left my computer on and went to classes keeping a vice site open. When I returned , I got killed and I have to restart from Level 1 now. The extension should at least stop reporting after some idle time. Else , a manual undo event for such a catastrophe from your side also might help :)

**Comment by wc8** [comment]
This issue/suggestion belongs to the chrome extension, right? I've copied it to: [From: pankajmore: Stop reporting vice sites if idle for some time?](https://github.com/lefnire/habitrpg-chrome/issues/55)
Please post further extension tickets here: [habitrpg-chrome](https://github.com/lefnire/habitrpg-chrome/issues)
