### ISSUE TITLE
"In a few seconds" time stamp for chat messages instead of "a few seconds ago"

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5112]
## The summary

**Problem**: If you see the time stamp "in a few seconds" instead of "a few seconds ago" (and respective alternatives translated into your display language) for most recent chat messages - it is because your computer/device time is incorrect by a few seconds.

**Solution**: get your computer/device time in sync with http://time.is/

**Explanation**: as far as I understand, Habitica stores the time of the post as reported by its own sources (some always in sync online time) then to display a time stamp the site checks how much time has past since the initial record against your computer/device time. So if you see "in a few seconds" your computer/device time must be some moments behind the right time for your timezone.

---

**The original report (which has been proven inaccurate below)**
I remember this issue having been addressed a while ago. However now it turns out the fix is partial and I can't find the thread.

The thing is, if you post to comment to a guild or Tavern chat the Russian equivalent for the time stamp "a few seconds ago" is incorrectly shown as "через несколько секунд" = "in a few seconds" (relating to the future).

Strange enough, posts of other people have the correct time stamp "несколько секунд назад" = "a few seconds ago". You can see the difference on the screen shot below.
http://oi59.tinypic.com/m7mfk.jpg

I know it's not exactly the issue of HabitRPG, but rather a one of the chat engine used. However I can't find the engine's name or repository or anything. 

I'm pretty sure HabitRPG is using up-to-date version of the chat engine. So could someone please give me a hint of its origin, so that I could send a request to the developers of the chat engine

**Comment by Alys** [comment]
This has nothing to do with translations or the chat engine. The time on your PC/device is incorrect by a few seconds. If you fix that, the times will be reported correctly (the times stored on the server are correct; the chat timestamp reports those times relative to your device's time).

**Comment by ghost** [comment]
Thank you @Alys for considering my question.

I'm terribly sorry, if I don't get it right, but it seems to me the problem is not with my pc's time settings.
I think so because:
1. In English everything is ok.
2. If I make 2 posts from Me and from TestingMe (testing account) - each account will see the own post with incorrect timestamp while the other post - with the correct one.
3. The time stamps from (2) never change from "in a few seconds" to the right "a few seconds ago" only to "1 minute ago" - practically simultaneously.

And I remember from the previous discussion that these lines are translated not within HabitRPG, but within the third-party project of chat engine.

Could you please reconsider my question?
And please excuse me, if I say something wrong.

**Comment by Alys** [comment]
Okay but first, go to http://time.is/ and show us a screenshot of what it says. An incorrect time is by far the most common cause of this "bug" report, and we must rule it out completely before we go further.

**Comment by ghost** [comment]
Thank you @Alys !
My PC is syncing with time.windows.com. Time.is shows my pc's time runs behind by 1,1 second. I'll check if I can set syncing with time.is

**Comment by ghost** [comment]
At last I've got the time perfectly sync, thank you for this tricky challenge @Alys !
And you are totally right! It seems to have fixed the "bug" )
Please excuse me for doubting your words and sorry for wasting your time... I'll try not to repeat this mistake ever again.
I wish you all the best!

**Comment by Alys** [comment]
Thanks for letting us know. Can you please delete your test messages from the Newbies guild now that you don't need them? You can leave in place the one that shanaqui replied to.

**Comment by ghost** [comment]
I've already done it!
