### ISSUE TITLE
Cannot view progress of habits: "TypeError: f is null"

### ISSUE THREAD

**Issue by Flimm** [HabitRPG/habitica#512]
Clicking the progress button on my habits has no effect. Funnily enough, clicking the progress button on my dailies does work.

In Firefox's web console, I can see this Javascript error as soon as I click the progress button on one of my habits:

```
TypeError: f is null @ https://habitrpg.com/gen/X1OM1JHxPk0rqD2xK-oJIQ.js:19
```

**Comment by wc8** [comment]
Hi, are these + only or - only habits or habits that are +/-?
If it is positive only or negative only this is probably the same as #299

**Comment by Flimm** [comment]
All my habits are + or - habits only. I created a +/- habit and it doesn't have this problem. This issue can closed as duplicate of #299.

**Comment by Flimm** [comment]
Actually, I get this error for the first two habits (one is +/- and one is +), and I don't get this error for the third habit (a + only).

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/commit/d5d8a9ef69d93982f3e40b0d7b56a16b5efad384 may have fixed this, still an issue?

**Comment by Flimm** [comment]
Looks like it's fixed now. Thanks!
