### ISSUE TITLE
Didn't get attribute point

### ISSUE THREAD

**Issue by Imbecamiel** [HabitRPG/habitica#5120]
I just leveled up, and went to allocate my attribute point, but... I didn't get one. I did try refreshing the page a couple of times, but nothing changed.

Since this is the first time it's happened, I'm wondering if it's a glitch that could have anything to do with the recent updates?

My user ID's:90b87ff7-d77a-4246-ab36-290401d9b1ca

I'm working on a Mac running Yosemite, with Chrome as my browser.

**Comment by Alys** [comment]
You're above level 100. Please see the description of the changes that the Bailey message linked to: http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes ("Attribute Points Change" section).
