### ISSUE TITLE
Pixel Art Fixes

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5123]
Finally posting a bunch of tiny pixel art fixes that have been accumulating.

The octopus egg was a slightly incorrect size. Uncommon Criminal has fixed it:
![octopus_egg_by_cosmic_caterpillar-d834m49](https://cloud.githubusercontent.com/assets/3494081/7439980/b6a52c1c-f04d-11e4-8390-9d9db7898431.png)

The lightest skin option had a mouth that was too faint in comparison to the other skin:
![newskin2](https://cloud.githubusercontent.com/assets/3494081/7439994/73e39ebc-f04e-11e4-89ae-12f29a5f4244.png)
![newskin1](https://cloud.githubusercontent.com/assets/3494081/7439995/73fb8608-f04e-11e4-8b0f-ee5846067731.png)

Some of the shirts available on the avatar customization screen did not have shading:
![slim_shirt_thunder](https://cloud.githubusercontent.com/assets/3494081/7440039/2ea77c44-f051-11e4-8cf8-757d28cdf172.png)
![broad_shirt_thunder](https://cloud.githubusercontent.com/assets/3494081/7440040/411b3e88-f051-11e4-913a-8db7ca3b0962.png)
![slim_shirt_cross](https://cloud.githubusercontent.com/assets/3494081/7440055/f21c5b5e-f051-11e4-9467-828aee3eaf47.png)
![broad_shirt_cross](https://cloud.githubusercontent.com/assets/3494081/7440054/f20ff576-f051-11e4-84f3-d72181ff0421.png)
![broad_shirt_convict](https://cloud.githubusercontent.com/assets/3494081/7440092/223ddc0c-f054-11e4-9905-72239ad73491.png)
![slim_shirt_convict](https://cloud.githubusercontent.com/assets/3494081/7440093/224acdb8-f054-11e4-82aa-5b8aa7d1e783.png)
![broad_shirt_redblue](https://cloud.githubusercontent.com/assets/3494081/7440126/f52ad29a-f055-11e4-9e14-768fd3c44744.png)
![slim_shirt_redblue](https://cloud.githubusercontent.com/assets/3494081/7440127/f532b046-f055-11e4-8107-c123e5bb580d.png)
![slim_shirt_rainbow](https://cloud.githubusercontent.com/assets/3494081/7440175/2693b912-f058-11e4-874a-ceb99101c366.png)
![broad_shirt_rainbow](https://cloud.githubusercontent.com/assets/3494081/7440176/26a0597e-f058-11e4-859e-800e71fd7146.png)
![slim_shirt_purple](https://cloud.githubusercontent.com/assets/3494081/7440182/a67688b2-f058-11e4-9032-7eeedadecf93.png)
![broad_shirt_purple](https://cloud.githubusercontent.com/assets/3494081/7440183/a697b4e2-f058-11e4-9525-b6c034895566.png)

**Comment by crookedneighbor** [comment]
@lemoness I couldn't find skin sprite with the dark outline around the head, so I left that out. If you can find it, would you point it out to me? https://github.com/HabitRPG/habitrpg/tree/develop/common/img/sprites/spritesmith/customize/skin

I also made the same change to the color of the mouth to the sleeping version of that skin tone.

**Comment by lemoness** [comment]
@crookedneighbor Upon further investigation, it looks like that skin set doesn't have an outline - some of the skins do, and some do not! A project for me for another day.
