### ISSUE TITLE
Class Tutorial Issues (misleading info)

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5125]
![image](https://cloud.githubusercontent.com/assets/6274734/7440402/615c8218-f067-11e4-9d01-d82cb1b5bdee.png)

There is no hover text for the stats here.

![image](https://cloud.githubusercontent.com/assets/6274734/7440406/992440f0-f067-11e4-9036-2c0d85b730a9.png)

This makes it seem like task-based allocation is the only kind of auto-allocation. This has been causing issues, I think because I've seen a few comments in the Tavern where people didn't realize that flat allocation or class-based allocation exist.

![image](https://cloud.githubusercontent.com/assets/6274734/7440411/c3b143c2-f067-11e4-979a-bde7c95b805a.png)

This information is obsolete and not actually correct for how it used to work. (10% daily and 1% per to-do with a minimum of 10 MP and 1 MP respectively.) While I understand that usually players seeing this tutorial don't have over 100 max MP, this would be good for them to know because it would encourage them to put points into Intelligence if they desire more mana recovery.

![image](https://cloud.githubusercontent.com/assets/6274734/7440421/14de04ba-f068-11e4-89da-783b388e2720.png)

This is just weird phrasing. "See Wikia." Check out our wiki? Or maybe "For more information, read the wiki page on the Class System. Still have questions? Ask in The Newbies guild!"
##

**Comment by deilann** [comment]
pinging @lemoness and @anitaycheng and um... @alys because it makes me feel powerful also is @SabreCat heavily involved in tutorial stuff still?

**Comment by lemoness** [comment]
Yep, class tutorial revamp was definitely on the list, but DANG, I didn't
realize it was this out of date. Bumping up in priority!

**Comment by SabreCat** [comment]
I wasn't heavily involved in the last round of tutorials, but this would definitely fall in my wheelhouse for near-term projects. Do we need any different steps and highlight zones, or just a wording overhaul? We could also easily add hover text for the attributes.

**Comment by lemoness** [comment]
For now, let's stick to a wording overhaul. We're still ripping up and
redoing the other tutorial, so lets not be too radical here until we see if
there's something special that works for the initial one.

**Comment by librarianmage** [comment]
What is the status of this?

**Comment by Alys** [comment]
I'm closing this in favour of this new, related issue: https://github.com/HabitRPG/habitrpg/issues/7958

Thanks @MathWhiz !!
