### ISSUE TITLE
Accounts uniqueness

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5126]
cc @Alys @lefnire 

See also #3986 .

The fields we want to enforce uniqueness on are:
- [x] `auth.local.email` (sparse)
- [x] `auth.facebook.id` (sparse)
- [x] `auth.local.username` (sparse)
## Steps
1. Delete all duplicates
2. Create compound index on this fields so we can drop the existing indexes without slowing down the site. For example `{email: 1}` could become `{email: 1, _id: 1}` so that emails can be searched without problems when we temporarily drop the index
3. Delete existing, non unique indexes
4. Block new registrations
5. Create new unique indexes
6. Drop temporary compound indexes
## Possible problems
- [x] Sparse indexes have some limitations http://docs.mongodb.org/manual/core/index-sparse/#index-type-sparse
- [x] Indexes creation: background or foreground? See http://docs.mongodb.org/manual/core/index-creation/#background-construction
- [x] What about emails: should be case sensitive or not? Currently registration is case insentive but login is case sensitive (to allow old accounts that may have case sensitive emails to be accessed). If we don't identify any duplicate when transforming all emails to lower cases we should simply force lower cases at registration and then migrate the rest. 
- [x] Duplicates with different combination of email/username. For example same username, but different emails: probably belong to two different people.
- [ ] Handle mongo errors
- [x] Block multiple submissions of signup form (#5141)
##

**Comment by Alys** [comment]
So far I've deleted 4319 user accounts that were easily identified as duplicates (e.g., created date = loggedin date and level=1, while a different account with the same email address had loggedin > created and level > 1). I have backups of all the deleted accounts.

More to go....

**Comment by Alys** [comment]
I've deleted 115 accounts that had no authentication details (no username, email, facebook). I.e., `auth` contained only timestamps and sometimes hashed_password and salt.

Note the comment below from Tyler about an account with no auth data, which explains at least some of those accounts. (Comments made a while back. Somewhere. Citation needed.)

"I think that user must have asked me to move them from facebook to local
and they're giving you the old facebook UUID
which will indeed have a blank auth{} post-migration. I know it's dirty, but I keep those accounts around (rather than deleting them) just in case there's a mistake somewhere
that's why you get `db.users.count()` != `db.users.count({ $or:[{'auth.local.username':{$ne:null}}, {'auth.facebook.id':{$ne:null}}] })
"

I have made an executive decision that dirty is bad, and that mistakes are never made. :)

I have a backup of all deleted accounts.

**Comment by Alys** [comment]
Another 3369 duplicates backed up and deleted.

**Comment by paglias** [comment]
@Alys I'm goint to start migrating `auth.facebook.id` to a unique index to see how things go, it doesn't require any deploy to production and I'll keep a fallback index avalaible just in case

**Comment by Alys** [comment]
Sounds great. I still haven't found any duplicates for that field.

**Comment by paglias** [comment]
Steps taken:
1. Create `{"auth.facebook.id": 1, "_id": 1}` compound index. It took ~650 seconds and slowed down database responses 2-3x. Also `_id` should be avoided next time, it's causing the index to be quite big
2. Delete `{"auth.facebook.id": 1}` index
3. Couldn't create unique index, with error `Unable to create index because the existing documents violate the unique constraint` for `auth.facebook.id`

**Comment by Alys** [comment]
Darn, sorry, I was thinking of email addresses stored with facebook login accounts. :(  Those didn't have duplicates.

**Comment by Alys** [comment]
359 duplicates for auth.facebook.id have been backed up and deleted.

Roughly one hundred remain to be analysed.

**Comment by Alys** [comment]
Actually, sorry, more remaining. I've been ignoring the more-than-2 duplicate sets so far.

**Comment by Alys** [comment]
Another 47 facebooks removed.

**Comment by Alys** [comment]
And another 50 facebooks removed. About 100 remain. Sorry about the rapid updates, I kept finding new easy ways to identify the bad duplicates. I'm finished now for today.

**Comment by Alys** [comment]
I've backed up and removed the remaining facebook duplicates.

**Comment by Alys** [comment]
Another 1304 duplicate accounts (email login) have been backed up and removed.

**Comment by paglias** [comment]
Hopefully no new duplicate facebook account will be created in the next few
hours, then as soon as I'm home I'll switch to the unique index.
Il 04/mag/2015 13:07, "Alys" notifications@github.com ha scritto:

**Comment by Alys** [comment]
Another 146 duplicate accounts (email login) have been backed up and removed.

**Comment by Alys** [comment]
There are currently no duplicate accounts with case-SENSITIVE values for `auth.local.email`
I expect there'll be more tomorrow though. I'll keep checking regularly until we have the index in place.

I'm about to start looking into case-insensitive email addresses (i.e., when a person has manually signed up once with an email address and then later signed up again manually with the same email address but written with different upper/lower-case letters).

**Comment by Alys** [comment]
Ewww. 951 people have signed up twice with the same email address but in different cases.

I'm working on cleaning that up. It might require negotiating with various users about which parts of their accounts they want merged together, in which case I'll talk to Lemoness first.

**Comment by paglias** [comment]
So no duplicates except for case issues? I'll be able to create an index on
email in a ~2-3 hours and hopefully we won't have anymore. Alys if you want
you can create the index from the Mongolab dashboard
Il 06/mag/2015 12:27, "Alys" notifications@github.com ha scritto:

**Comment by Alys** [comment]
I won't because it's a bit too close to my bedtime for me to be trying something new. 

Hopefully you'll be able to create it, without too many new accounts to clean up first! Good luck. :)

**Comment by paglias** [comment]
Of course we some new ones :) I'm going to find a way to block multiple registrations or otherwise we'll never end with this and then delete the remaining

**Comment by paglias** [comment]
@Alys right now we have 4 duplicates email but over 30 duplicate usernames so they must have different emails. I fear some of them will be different people at all, we'll need to find a way to convince one of them to change it.

For case sensitive emails we can do it after we're done with unique indexes

**Comment by lemoness** [comment]
@alys @paglias - If you need user contact for sorting out the hairier ones,
ping me.

**Comment by Alys** [comment]
All the case-sensitive duplicate usernames have now been removed (31 accounts).

That's also cleared up a few of the case-insensitive duplicate emails. I'll keep working on the rest.

**Comment by paglias** [comment]
Usernames have an unique index now, we've achieved our main goal :)

**Comment by Alys** [comment]
@paglias What are we up to with this? From memory, which might be wrong, I collated a list of all users who had duplicate accounts created with the same email address but with different case (e.g., joe@thing.com and JOE@thing.com). We were going to email them to explain that they had two accounts and offer help with merging them.

**Comment by Alys** [comment]
`auth.local.email` can now be given a case-insensitive unique index.

**Comment by Alys** [comment]
@paglias Can this and https://github.com/HabitRPG/habitrpg/issues/3986 be closed now?
