### ISSUE TITLE
UX: Editing a task involves a lot of scrolling -> pop over?

### ISSUE THREAD

**Issue by marcelklehr** [HabitRPG/habitica#5127]
When editing a task, I always think, "man, this would be way better in a pop over".
The advantage of a pop over is that you can use screen estate, particularly the width of the screen, so you don't need to scroll.

These are just my two cents. Awesome project, though. Keep up the good work!

**Comment by AnitaYCheng** [comment]
I know it was discussed between me and @lemoness and @redphoenix some time ago, but I'm not sure if there are active plans in making that happen. Making the edit module a popup wouldn't help with real estate issues on the mobile site, but a responsive solution might work, to take advantage of the desktop space as you mentioned. Your main concerns certainly seems related to #4730.

**Comment by deilann** [comment]
I'm going to close this... I think it's best for discussion to all be kept in #4730 

@marcelklehr I'm not closing it because I think it's unimportant. It's just easiest if the conversation all happens in one place. :)
