### ISSUE TITLE
Inn Text Needs Clarification About Boss Damage

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5128]
We regularly get asked in the Tavern if all members of the party are checked into the inn if they will still take boss damage from incomplete Dailies of their party mates.

This could easily be fixed by changing the Inn text to state that you will still take damage from your party member's missed dailies, if they are not also resting.

@lemoness Do you feel like coming up with "official" verbage?

**Comment by crookedneighbor** [comment]
@lemoness Can we get two versions of the Tavern text? One for when the user _is not_ resting in the Inn and one for when the user _is_ resting in the Inn?

**Comment by deilann** [comment]
This is the ticket I assumed you meant to comment on, as it's where @lemoness posted the latest inn text: https://github.com/HabitRPG/habitrpg/issues/5070

**Comment by lemoness** [comment]
Assuming it's for the upcoming refreshing feature:

1.
Welcome to the Tavern! Stay a while and meet the locals. If you need to
rest (vacation? illness?), I'll set you up at the Inn. While checked-in,
your Dailies won't hurt you at the day's end, but they will still refresh
every day. Be warned: If you are participating in a Boss Quest, the Boss
will still damage you for your party mates' missed Dailies unless they are
also in the Inn! Also, your own damage to the Boss (or items collected)
will not be applied until you check out of the Inn.

2.
You're resting in the Inn! While checked-in, your Dailies won't hurt you at
the day's end, but they will still refresh every day. Be warned: If you are
participating in a Boss Quest, the Boss will still damage you for your
party mates' missed Dailies unless they are also in the Inn! Also, your own
damage to the Boss (or items collected) will not be applied until you check
out of the Inn.

How's that? Do we want more variance?

**Comment by Alys** [comment]
I like the wording.

Can we put one of the messages above the Rest in the Inn button (probably the one for when you are not resting) and the other one below it? That will make it more obvious that the message has changed and give another visual indication of whether you are resting or not.

**Comment by crookedneighbor** [comment]
@lemoness related: https://github.com/HabitRPG/habitrpg/pull/5146

**Comment by crookedneighbor** [comment]
@Alys we could also have the color of the rest in the inn button change depending on whether or not you're currently resting.

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/pull/5195 and https://github.com/HabitRPG/habitrpg/commit/d6e1d765da050cae02230e4241ab6bd57d1ba61d
