### ISSUE TITLE
[Feature] Daily could change name depends on the days

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#513]
A daily could change its name depends of which day it is.
For example, “up before 7a.m” in the week become “up before 10a.m” in the week-end, or “go to the gym” on Mondays become “go to the pool” on Fridays…
It will certainly be quite delicate to implement, I suppose (technically and functionnaly), but it could permit to synchronise look-alike dailies (and cumulate bonuses and maluses for similar tasks).

(Sorry, I have the feeling my English really is terrible in this post, I hope I made myself understandable nonetheless)

**Comment by horusofoz** [comment]
Hey @LazuliKazeno. Welcome to the community.

Creating dailies for each of the activities and setting to be active on the relevant days would provide you with the function your looking for.

This combined with the [Hide Until Due](https://trello.com/c/G14jkPYd) option would tidy it up to.

**Comment by Pandoro** [comment]
@horusofoz, I also thought that at first, but you would have trouble with
the different accumulated rewards/penalties.

For now I would just include it in the title of the task, but I see that
this looks less tidy.

**Comment by horusofoz** [comment]
@LazuliKazeno Can you advise if the proposed solution will suffice?

**Comment by ghost** [comment]
My point really was to synchronise rewards/penalties for similar tasks (as "I woke up early this week, so I could ease-up in the week-end"). Presently, either I have multiple dailies (with days parameters, but without any synchronisation) or I put long title/comments to explain the different behaviour.

So, yeah, I do with it for the moment. As I said, it seems to me a nice feature (at least one I would definitely use), but I suppose it is hard to implement, so I didn't really expect a big implementation right now.

**Comment by Pandoro** [comment]
@LazuliKazeno let's leave it upon for a while and see what other people think ;) 

I understand that the way you want to use it, the proposed solution will not work. If many people would like this, it is something to think about, but as you said it will not be trivial indeed.

**Comment by wc8** [comment]
https://github.com/lefnire/habitrpg/issues/262#issuecomment-13052528 shows a picture of how @SlappyBag is handling this.

**Comment by horusofoz** [comment]
Is this going forward or getting scratched?

**Comment by deilann** [comment]
This would be better for Trello.

**Comment by wc8** [comment]
@deilann previous workflow was to create a new card in Trello, add a link to the Trello card here, then close the thread. Is there a way to track closed tickets that need a Trello card, so that the ideas don't get lost, or are you moving them over?
We could simply create a label "needs Trello card" maybe.

**Comment by deilann** [comment]
Sorry, @wc8 -- I closed over 100 tickets today. This one I didn't bother moving to Trello myself because it hadn't been touched for 10 months, after a call to everyone who had commented as to where thoughts were going.

**Comment by wc8** [comment]
@deilann moving tickets to Trello & closing threads is fantastic. No need to be sorry, I just wasn't sure. I'm relieved, actually. I wasn't sure what to do about this ticket myself.
