### ISSUE TITLE
Multi-cron

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#5130]
I am getting this rather a lot, but here is one particularly spicy example. The most recent occurrence was last night. I am concerned that if I am not Stealthed then I will end up getting smacked multiple times for damage. I have cron set for midnight, and use the desktop version of the site, the official app, and the data tool. I was using Beeminder, but not any longer.

![triple-cron](https://cloud.githubusercontent.com/assets/3580439/7442246/4f4c2ec6-f101-11e4-999a-140c5a873092.png)

**Comment by Alys** [comment]
This has been reported in https://github.com/HabitRPG/habitrpg/issues/2805 so I am going to close this issue now, but you can subscribe to notifications from that one if you wish. This post of yours has been linked to from it. Could you please comment in it to tell us if you generally have HabitRPG open in more than one tab at once?
