### ISSUE TITLE
Party Chat Doesn't Update Until Message Fetched

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5131]
When you visit a guild, the chat automatically updates. When you visit your party, however, it does not.

This makes sense for the Tavern, for performance reasons. However, I can't imagine it makes sense for party chat. And because party chat is where things like boss damage appear, this leads to a lot of bug reports where people think their damage was not applied. I'm not referring to https://github.com/HabitRPG/habitrpg/issues/2126 where the bar doesn't change, but where people simply don't see the system message because it requires fetching.

This especially is problematic because party chat gives a chat notif, just like guilds. So users get a notif which sends them to their party chat, but the chat isn't updated.

I heavily suggest that we alter party chat to auto fetch, like guilds. It will make support so much easier.

**Comment by lemoness** [comment]
Agreed!!

**Comment by hairlessbear** [comment]
This was fixed in #5298, so this can be closed.
