### ISSUE TITLE
Leveled up while in inn and didn't get skill point.

### ISSUE THREAD

**Issue by Aurornis** [HabitRPG/habitica#5138]
I was at the tail end of lvl 103 when I completed a red to-do item, but I had forgotten to check out of the inn.  I got no notification that I had another skill point, which I usually get when I level, and when I went to my characters stats page I only have 103 points to spend.  Reloading doesn't fix this, and neither does opening a new HabitRPG tab.
![habitglitch](https://cloud.githubusercontent.com/assets/6277293/7447130/f2d6d24c-f1a3-11e4-9235-8cc40c8ceef9.png)

My userID:
3698ff36-4e86-4152-842d-7efce1e4cd9e

This happened while using Google Chrome Version 42.0.2311.135 m on Windows 7 Home Premium SP1

**Comment by Alys** [comment]
Attribute points are no longer awarded after level 100. For information about this and other recent related changes, please see the latest Bailey message, which has been copied to [Whats New](http://habitrpg.wikia.com/wiki/Whats_New_2015#Skills_Rebalancing) on the wiki, and the post that it links to which you can access directly here: [Skills Rebalancing and Other Changes](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes)
