### ISSUE TITLE
No longer able to feed pets

### ISSUE THREAD

**Issue by WhitneyFox** [HabitRPG/habitica#5139]
I had a back log of food to feed my pets. When you feed more than one item to the same pet in a row it pops up a box that asks if you want to continue receiving the messages "Are you sure you want to feed this pet". As I had so many items to feed, I clicked "Don't receive any further messages" (I can't remember the exact wording, but it is something like that). Now it won't allow me to feed anything or to add a potion to an egg to hatch a new pet. It seems that by turning off the notifications it's turned off the whole pet system.

As far as I can tell, everything else in the game works.

I am using the website in Firefox in Windows 7.

Thanks.

**Comment by Alys** [comment]
That's your browser's standard message to you to allow you to prevent notifications from spammy websites. HabitRPG has no control over that. Stop and restart your browser (all tabs and windows) to get the notification back.

**Comment by WhitneyFox** [comment]
Fantastic, Thanks, that worked.

**Comment by deilann** [comment]
That's a Firefox setting to keep you from getting extraneous popups. It's
not part of Habit. When you use that setting, you then can't confirm
anything, and so can't hatch pets.

The good news is that it's easy to fix. All you need to do is close your
browser and reopen it.
