### ISSUE TITLE
task skills (Burst of Flames, etc) - not clear that you must click on a task

### ISSUE THREAD

**Issue by MsMadGirl** [HabitRPG/habitica#5140]
Firefox 37.0.2 on OSX 10.9.5
ef140088-589d-4e9c-9053-c972799944b2

When I click on Burst of Flames, the spell does not cast, and the plus sign in the green circles stays on the pointer no matter where on the page it is. No error message.

**Comment by Alys** [comment]
To cast Burst of Flames, you click on the skill first, then on a task. Is that what you've been doing? Does the pointer change after you've clicked on a task?

**Comment by MsMadGirl** [comment]
Ah. Well, now I feel stupid. Yes, it works.

-- 
Rebecca MadGastronomer
Sent with Airmail

On May 4, 2015 at 2:00:04 AM, Alys (notifications@github.com) wrote:

To cast Burst of Flames, you click on the skill first, then on a task. Is that what you've been doing? Does the pointer change after you've clicked on a task?

**Comment by Alys** [comment]
Don't feel stupid! There's no instructions on the page. 

We should perhaps fix that. @lemoness?

**Comment by lemoness** [comment]
Can we add "Click on a task to cast" to the description for this and other single-task skills?

**Comment by AnitaYCheng** [comment]
@lemoness :+1:

**Comment by mayajosyula** [comment]
If no one has done this yet, would it be possible for me to try it? (I've never contributed to the code base before, so I'm not sure if I'm overstepping anything here - sorry.)

**Comment by Alys** [comment]
That would be great! Thank you @agentx999! If you run into problems or
would like advice, you can ask here. You might also like to join the
Aspiring Coders guild.

**Comment by mayajosyula** [comment]
I don't have a local install so this was all rather confusing (did the entire thing online), but I _think_ I found the right file and I _think_ I submitted a request? I added the sentence after the description that was already there but before the part in parentheses ("Based on: STR", etc.) because I thought it would be more consistent that way, but I can change it if you want the order to be different.
