### ISSUE TITLE
Information Missing from Participant Challenge Tasks (progress graphs)

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5143]
If you go to look at a challenge participant's tasks, you cannot look at the progress graph. This is actually really problematic for scoring challenges and should be fixed ASAP.

![image](https://cloud.githubusercontent.com/assets/6274734/7455229/1be3ec2a-f22f-11e4-9d69-8f1ab312feae.png)
##

**Comment by beffymaroo** [comment]
Yep, just came over here to say the same. I can only judge how Habits/Dailies were completed based on color and streaks, which is not that helpful when the criteria for being a potential challenge winner was "make a clear effort to keep up on the Habit and Daily".

**Comment by librarianmage** [comment]
Should this be closed?

**Comment by lemoness** [comment]
It should!
