### ISSUE TITLE
Earning MP back after each completed Habit and Daily?

### ISSUE THREAD

**Issue by keithhir** [HabitRPG/habitica#5145]
I had cast Earthquake and several Burst of Flames this morning, and I started to notice that for each Daily I checked off, I would earn around 5 MP back, while Habits would earn 1.5 MP.  Possible bug?

User ID: 57ab6504-1fd6-493e-b984-9b4ad2946c62
Group ID: 30fea9dc-239d-4d99-b529-1258cc9d87df

**Comment by NotGonnaGitUs** [comment]
Hey, these are part of the new changes from 01/05/2015 making mana more relevant. 

> MANA DIRECTLY LINKED TO PROGRESS
> 
> Mana was pretty broken: you gained it overnight no matter what you'd done the day before, and it was only linked to To-Dos. This meant that using skills was pretty detached from how well you were doing in your real life, which defeated the purpose of the game!
> Now you can gain Mana from Dailies and positive Habits as well as To-Dos! You still gain Mana overnight, but how much you gain depends on how many of your Dailies you did.
> You can also lose Mana by hitting negative Habits. Yikes! Better not indulge...

[Full description](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes)
[Summary](https://habitrpg.com/static/old-news)

**Comment by keithhir** [comment]
Ah, thanks.  Must have missed that bit when skimming notes.
