### ISSUE TITLE
Add Task plus not vertically centered

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5148]
On Chrome, the plus sign for adding a new task to one of the four main columns is not vertically aligned in its button. It's substantially higher than center:

![image](https://cloud.githubusercontent.com/assets/4501321/7465087/ffaec94c-f28f-11e4-9748-5b53db4b2006.png)

Note that the screenshot above also features the "cross" look from #4539, which may or may not be related. 
##

**Comment by JstAlx** [comment]
I have noticed that is also the case in other web browsers, Safari, Firefox for Mac, Chrome for Mac, Safari iOS 7 for iPhone, iPod Touch and iPad, Chrome for Windows, Firefox for Windows, and Internet Explorer. All of these web browsers have the same issue as shown in the image above.
These web browsers are also experiencing issues with +/- on the "Habits" tab as noted in #4539.

**Comment by averrin** [comment]
![plus-fix](https://cloud.githubusercontent.com/assets/426007/7868397/856bfa4e-0584-11e5-9ade-2b08f409df1c.png)
fix: add vertical-align css property to span.glyphicon

**Comment by SabreCat** [comment]
Amusingly, it appears the + drops down to the correct position while I'm adding a task...
