### ISSUE TITLE
Burst of Flames no longer functioning properly

### ISSUE THREAD

**Issue by stephenmac7** [HabitRPG/habitica#5149]
The Burst of Flames mage skill seems to not be changing the task value anymore, as it did prior. However, it seems to still have different effect based on the task value.

**Comment by Alys** [comment]
The skills and some other features were changed a few days ago. Please see [Skills Rebalancing and Other Changes](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes) for a description of the changes. There's also some brief information in the latest Bailey message with a link to that page for more information.

**Comment by stephenmac7** [comment]
So, why is the amount of damage still based on the task value, if it doesn't modify the value? Wouldn't it now make sense to just function without picking a specific task to apply it to?

**Comment by Alys** [comment]
As described in the Bailey message about the skills changes, we are giving people two weeks to get used to the skills before we accept feedback. Around 15 May, a location will be opened for you to write feedback. If you still think the skill is broken then, please tell us.

**Comment by stephenmac7** [comment]
Okay, thanks.
