### ISSUE TITLE
Github issue tagging

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#515]
@wc8 @Pandoro @horusofoz - you three seem to be the champions of the Github & Trello requests - seem to have your hands in every ticket. At least that was last time I checked, I've been out of the loop working on the server issues for so long - so if I'm missing somebody important, tell me and I'll add them as a collaborator.

Favor to ask you guys: could you tag Github tickets as `critical` or `important`?  There are so many tickets to keep track of, I'm just going to start tackling only the critical ones. We'll want to keep criticals to a minimum, so only if it's really a problem in the community (sounds like "The Basis of Death" is becoming a `critical`, for example). We can tag less critical issues as `important` or `minor`. Also, if I have any tickets tagged `critical` that you don't think are that vital, feel free to remove the tag (except the memory leak ;)

I'll start tagging things by difficulty as well, that way beginners can start jumping into the repo.

**Comment by wc8** [comment]
What types of tickets fall under the support label? Wiki suggestions? Questions about how HabitRPG works? Pixel art offerings?

**Comment by lefnire** [comment]
exactly! :) Bugs are obvious; suggestions are features, really - and graduate to Trello; and everything else is  support

**Comment by Pandoro** [comment]
Those mentioned are up to date, can we close this to keep the board clean :) ?

**Comment by lefnire** [comment]
ah yes! thanks sir

**Comment by wc8** [comment]
I added a "design/interface" label to help with locating related suggestions/issues. I'm assuming if it gets in your way, @lefnire it can just be deleted.

**Comment by lefnire** [comment]
Nope! You are my organization champion, friend @wc8

**Comment by wc8** [comment]
I recently saw and commented on the related G+ thread, but it's old, and maybe no one's being notified. Hopefully just adding @lefnire @paglias and @SabreCat will notify you. Maybe we can use this ticket #515 to come up with a list?

Simple recap of my comments:
- my tag use is to support developers, so set them up however you need them, and I'll follow along.
- some indicator of suggestion, trello-card-exists, and maybe suggestion-for-github has been helpful so far for tracking what to move out of github
- I've been using _support_ for questions for a developer [i.e. developer or staff input needed] and admin-account type issues (e.g. probable user corrupted database item, paypal issues, etc.), but it maybe's not clearest?

**Comment by lefnire** [comment]
The only ones I don't use are work-item and interface, but I think other devs are using it. Good to know about `support`, I didn't know that. You can alternatively assign me on the ticket, since I'm the only one (currently) with database access. Vicky had concern with my granting db access to any devs, which I need to quell soon since other devs will need it eventually

**Comment by wc8** [comment]
There’s a gem/coin label, but usually coins and gems are not the same type of issue.
Would it be useful to create a “points" or “HP,XP,GP,MP” label so you can filter to those kinds of problems, and/or convert the existing label to just gems?

Oh, and I deleted custom-day-start in favor of cron per what @SabreCat said on G+, but later I saw @lefnire mentioned it in his list, do you need it back? I can restore it, I think.

**Comment by lefnire** [comment]
Actually, to be honest I'm not using tags a _whole lot_. I'm relying instead on sorting in Zenhub columns, which I'm mostly managing myself (feel free to re-order if you want, but I think I've got a pretty good handle on Github - unlike Trello where I fell into oblivion). I think things are in a pretty good state right now unless anyone has objections, and if so feel free to change
