### ISSUE TITLE
Server giving intermittent 503 error when loading from API

### ISSUE THREAD

**Issue by josh-audio** [HabitRPG/habitica#5154]
http://i.imgur.com/DmNDhfK.png

Here's the URL that the console says is returning a 503:
https://habitrpg.com/api/v2/user/batch-update?_v=865&data=1430841728437&siteVersion=1

This has happened twice so far within the last hour or two. This may not actually be a problem that needs fixing, but I thought I'd submit an issue just in case. Feel free to close it.

User ID: 8ec3ebc2-6dd2-4614-9e2e-aee4cba351a0

As per issue reporting standards, here's my system setup:
Google Chrome Version 42.0.2311.135 m
Windows 8

**Comment by paglias** [comment]
@SecondFlight if you're still experiencing this plese reopen. Probably it was a temporary glitch
