### ISSUE TITLE
/user/tasks/{id}/{direction} ignores up/down parameters on create

### ISSUE THREAD

**Issue by tom-sequoya** [HabitRPG/habitica#5156]
Calling /user/tasks/{id}/{direction} to create a new habit and score it up seems to ignore the parameter to create this as an up-only task. The other parameters in my json are being processed so there's either a bug or I'm doing it wrong. 

Here is an example of the json I'm passing:

{ "text": "Test 003 text", 
  "notes": "this is my note test 003", 
  "id": "Test 003", 
  "down": false, 
  "up": true, 
  "type": "habit" 
}
##

**Comment by Nowbob** [comment]
It was a bug, I submitted a pull request for it. Easy fix

**Comment by tom-sequoya** [comment]
It appears that this route _also_ ignores the "repeat" parameter.  I tried to create a Daily that is set for M-F but the resulting task is flagged for every day of the week.  The json I passed was an edited version of what I got back on a query of a task that was built in the UI so I'm pretty sure it's correct unless the input json != output json.  :-)

**Comment by crookedneighbor** [comment]
I am unsure at this point if there's intention behind limiting what can be created with the score method. I don't think there is, but, as I said, I'm unsure about it.

**Comment by paglias** [comment]
Should be fixed, reopen if it happens again
