### ISSUE TITLE
Missing gem

### ISSUE THREAD

**Issue by phizzwizard** [HabitRPG/habitica#5158]
I bought a gem for 20 coins, and used it, along with the other 3 gems I already had, to buy a pink hatching potion, and hatched a pink bear. Then the browser crashed. When I pulled it back up, the pink bear was not there, and I only had 3 gems in my account, instead of 4. But the 20 coins are gone, and my gem purchase number was down by one. So the bug stole a gem from me.

**Comment by hairlessbear** [comment]
Could you please provide your User ID (located under Settings -> API)? I'm not an admin, but the admins will need your User ID to see what's going on with your account.

**Comment by phizzwizard** [comment]
Sure thing. User ID: 9bec527c-79cf-4882-8802-584efd9433fd

**Comment by Alys** [comment]
@phizzwizard I've restored your missing gem.
