### ISSUE TITLE
ToDo reappearing on check

### ISSUE THREAD

**Issue by WillyReyno** [HabitRPG/habitica#5159]
Hi everyone,

i've been encountering an issue since yesterday.
Everytime I check a ToDo, it's disappearing then reappearing...
The blue line at the top starts loading, then stops and go back to zero, then restart. When completed, my task is still here, unchecked. And I think that I don't lose the gold and experience I'm winning from checking this ToDo.

 I've tried many time to do some Sync, logout/relogin, emptying my cache, but none of that worked.
It the same problem on the android application.
My girlfriend also have the same bug.

My user ID is : aa137fd1-9b36-4c2f-ae2b-e651e2b764c5
My girlfriend's user ID : f5df6207-20ef-47a8-8e0b-e1a0a711cb10

**Comment by hairlessbear** [comment]
Is this happening with a single, specific to-do, or with all to-dos? Regardless of your answer, please try the following:
1) Click on "Done" in the To-Dos panel
2) Click "Delete Completed"
3) Try checking off the To-Do again

**Comment by WillyReyno** [comment]
The bug is not showing anymore, I did what you told me to before, and maybe that's why the bug isn't there anymore, thank you !

(It was on every ToDos except those that I added after the bug started showing)

**Comment by hairlessbear** [comment]
Awesome! In that case, would you mind closing this bug?
