### ISSUE TITLE
weapon upgrade purchase is a downgrade

### ISSUE THREAD

**Issue by atsepkov** [HabitRPG/habitica#5163]
My account is 2bac9f4a-b280-47b3-a907-d3fcd96c5cad and the next weapon up is a a Quartz rod with +3 int. However, my current weapon that I already bought a few months ago is an Amethyst rod with +5 int. Is this a glitch?

**Comment by hairlessbear** [comment]
You should have had to buy the Quartz rod before you were able to buy the Amethyst rod. Did that happen?

Also, did you die while the Quartz rod was equipped? If so, it's possible that dying caused you to lose it, meaning that you have to re-buy it. I believe this happens even if you own the upgraded weapon.

**Comment by atsepkov** [comment]
I don't remember the names, but I've always had to buy things in order, so I'm pretty sure I bought both. I did die while going on vacation, so it probably got dropped then.

Could I clarify how the dying system works then, because it seems counter-intuitive. If a character dies, the game can not only drop the latest bought item, but an older-bought item? In the later case, wouldn't I then have to buy all items starting from that older one (even if I already have them)? Or do I just have to fill in that gap?

**Comment by hairlessbear** [comment]
Below are relevant excerpts from the ["Lost Equipment" section of the Death Mechanics wiki page](http://habitrpg.wikia.com/wiki/Death_Mechanics#Lost_Equipment), with emphasis added:

> The piece of equipment that is lost upon death is **randomly chosen from among the equipment that is specific to the player's current class and equipment that is not class-specific (e.g., the Contributor Rewards equipment)**. Equipment from other classes, as well as free items (with the exception of the Warrior's Training Sword), will remain safe.
> 
> If an item that is currently being worn is lost, then the starter item for that type of equipment will replace the lost equipment as the player's worn equipment. Lost equipment can be re-purchased in the Item Store. This includes special and limited-time items that are no longer available.
> 
> **If the piece of equipment that is lost is not the ultimate gear (and is class-specific), then it must be repurchased before better equipment in that tier can be bought (or repurchased)**.

You only have to buy the equipment that was lost, nothing more. Does that make sense?

**Comment by jclau463** [comment]
Yeah. Hairless is right on this one.
