### ISSUE TITLE
Late CDS + Specific Day Dailies Issues

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5167]
When CDS is set late, say 6pm or later, it's frustrating to have to set all tasks for the day after they're due. Frex, if CDS is set for 11pm, Dailies that are set due on Wednesday will in effect be due on Thursday.

There are a lot of good reasons to set a CDS for before midnight. I suggest that if CDS is set after 6pm, it considers it the day after the day -- so if cron is set for 11pm, when it triggers on Wednesday, it treats it as Thursday.

Am I making sense?
##

**Comment by Nowbob** [comment]
Are we able to set the time to a negative value? say -1 for 11pm? If not, might I suggest adding the functionality?

**Comment by Alys** [comment]
I'm closing this because we're focussing on bugs in GitHub these days but it can be reopened when we're ready to work on it.
