### ISSUE TITLE
Inconsistency: joining guild challenge as non-guild member is possible, staying in challenge when leaving a guild is impossible

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#5168]
It's not really a bug, just an inconsistency:
- If you have the direct link to a guild, you can look at the guild page without joining, click on one of the guild challenges, and join it without being a guild member.
- If, on the other hand, you are a guild member, participate in one of its challenges, then leave the guild, you automatically leave all guild challenges (and are given the choice to keep or delete the tasks). You don't have the possibility to stay in the challenge.

As far as I can guess, being able to join a challenge without being a guild member was probably unplanned and came about with the code change that made it possible to see single challenges directly? (Also, if it's possible to join a challenge without being in the guild, it gets hard to leave it again since you can't see it in your challenges list. You'd have to first join the guild to leave the challenge.)

The simple fix would probably be to check when joining if the would-be participant is a guild member, and deny joining if they are not.

The harder fix would probably be to a) give people the option to stay in challenges when leaving guilds, and b) to show all challenges you participate in (even if you are not a guild member) in your list of challenges. (Preferably also all challenges you created in guilds you are no longer a member of.)

I actually like the option to participate in a challenge in a guild I'm not a member of. (Do the challenge, switch off the chat...) I consider it a feature. But I understand it wasn't planned for and would be harder to implement consistently than just making guild membership mandatory for challenges (as it was before being able to show single challenges).
##

**Comment by deilann** [comment]
I think it would be preferable to not even allow users to _see_ challenges for which they are not a guild member.

This loophole opens up the ability to show challenges from a private guild to anyone, which is not okay. I think it's also not a good idea to allow people to join challenges of guilds they are not a member. I do not think it's unreasonable to require folks to join the guild in order to access the guild challenges.

**Comment by habitrpguser** [comment]
@deilann Would you think it ok to at least be able to read the challenges of public guilds? I really like the fact that, as it is now, that has shortened from "click on guild link - join guild - read challenges - leave guild" to "click on guild link - read challenges" (if you have the direct link to a guild, say, from the Guilds Guide wiki page). It's not a big deal, it just makes it faster.

I understand about challenges in private guilds and parties though. (I think no one who isn't a guild member there should even have the URL or they can read the chat any time, too. I wonder how that is currently dealt with if someone gets thrown out of a private guild. Of course, there would be the workaround to "move" the guild to another URL by recreating it... But I digress, that's another topic.)

**Comment by deilann** [comment]
If you give someone the address to a private guild, it throws an error if
you try to access it.

I'd really prefer just to block all challenges if they are visited by
saying "not a member" rather than to search and see if the guild they're
part of is private or public. It'd be better for performance and I really
don't think having to join a guild to see the challenges is a huge
impediment.

**Comment by habitrpguser** [comment]
@deilann Ah, I didn't know about private guild URLs throwing an error, that's great! (Obviously I never tried to sneak into a private guild. :) ) If such a guild's challenge URLs don't throw an error and aren't blocked yet, that's probably a privacy loophole and should be fixed, as you said.

As I said, having to join a guild to read the challenges isn't a big deal for me. I like it the fast way as it is now (and still think it would be great if public guilds' challenges would be readable even if they aren't joinable), but can live with how it was before.

If/when that gets fixed (in such a way that only guild members can be challenge participants), there will probably already be a few people who are participating in guild challenges where they are not a member. I'm sure you won't forget to give them fair warning and the possibility to join the guild before throwing them out of the challenge! :)

**Comment by Alys** [comment]
@habitrpguser _"If/when that gets fixed (in such a way that only guild members can be challenge participants), there will probably already be a few people who are participating in guild challenges where they are not a member. "_ -- Good point. Thank you for mentioning it. 

**If approved by the staff. we could run a script over the database to find such users and make them members of the associated guild.** (bolded to help us keep it in mind if it becomes necessary).

**Comment by habitrpguser** [comment]
I checked this again. When you leave a guild now, you still automatically leave all the challenges you joined in there - only now, you are no longer offered the choice whether you want to keep or remove the tasks (nor in any other way automatically made aware that you are also thrown out of the challenges). The tasks are kept. While the behavior was just inconsistent before, I think it can be problematic now: At a first glance, the Tasks page looks like you're still in the challenge. (The only difference is that the tasks don't have the megaphone icon.) Plus all the challenge tasks have to be deleted by hand now. This can get especially difficult if someone actually assumes that they are also automatically thrown out of the challenges (or visits their challenges page and notices it), and deletes the tags, too, before seeing that the tasks are still there. They can then no longer find out which tasks once belonged to which challenge, they just have to go through their tasks lists manually and delete all tasks that neither have a megaphone nor look like they were created by themselves. (Not that going through one's tasks lists now and then and deleting some is such a bad thing to do... ;P )
This isn't a big problem for me (now that I know it - I'll just join and leave guilds and challenges in such a way that I'll avoid it), so, as far as I am concerned, there's no need to answer quickly (or at all). I just thought that, with all the current challenge bugs, it might be helpful to let you know.

**Comment by khipkin** [comment]
@habitrpguser There is another issue related to this that has active discussion! Issue #7764.  It is being looked into. :smiley:

**Comment by habitrpguser** [comment]
@khipkin Ah, thanks! Good to have the link here now.

**Comment by khipkin** [comment]
Just my opinion, but I think this issue can be closed, since we already have #7764.

**Comment by Alys** [comment]
@khipkin Good point! Since there were no disagreements in https://github.com/HabitRPG/habitrpg/issues/7764 to staying in challenges when you leave a guild, we can consider this inconsistency resolved in favour of that behaviour. It will be implemented in #7744
