### ISSUE TITLE
 Overflow sort stage error while trying to open the Challenges tab

### ISSUE THREAD

**Issue by DemosMirak** [HabitRPG/habitica#5169]
Hello,

I just tried to open the challenges tab again, which worked fine before, and got this error:

Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33825948 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

Reloading did not help, and the java console gave the following:

GET https://habitrpg.com/api/v2/challenges 500 (Internal Server Error)nrWrapper @ (index):1(anonymous function) @ app-bca8a57e.js:7s @ app-bca8a57e.js:7f @ app-bca8a57e.js:7j @ app-bca8a57e.js:8(anonymous function) @ app-bca8a57e.js:8j.$eval @ app-bca8a57e.js:8j.$digest @ app-bca8a57e.js:8j.$apply @ app-bca8a57e.js:8(anonymous function) @ app-bca8a57e.js:8p @ app-bca8a57e.js:5(anonymous function) @ app-bca8a57e.js:5nrWrapper @ (index):1

app-bca8a57e.js:41 Object {data: Object, status: 500, headers: function, config: Object, statusText: "Internal Server Error"}responseError @ app-bca8a57e.js:41j @ app-bca8a57e.js:8(anonymous function) @ app-bca8a57e.js:8j.$eval @ app-bca8a57e.js:8j.$digest @ app-bca8a57e.js:8j.$apply @ app-bca8a57e.js:8s @ app-bca8a57e.js:7w @ app-bca8a57e.js:7y @ app-bca8a57e.js:7nrWrapper @ (index):1

I use the newest version of Chrome in conjunction with Windows 8, all updates.

A similar error occurs when I try to leave the solo party I created:

Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33826477 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

The Java console message is the same.

A similar error occurs when I try to leave the solo party I created:

Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33826477 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

The Java console message is the same.

**Comment by deilann** [comment]
Is this still occurring? Errors like this are usually intermittent.

**Comment by DemosMirak** [comment]
It no longer occurs.
