### ISSUE TITLE
set guidelines for parties and guilds

### ISSUE THREAD

**Issue by DanielReeLee** [HabitRPG/habitica#517]
I know the current party system can only old up to 4 people. This should be good for a small group of friends but not good for a large group. To accommodate the large group there should be a guild for large groups. There should be no limit on the amount of people in a guild but there should be differences between both.

**Comment by lefnire** [comment]
yep yep: https://trello.com/card/groups-guilds/50e5d3684fe3a7266b0036d6/84

**Comment by DanielReeLee** [comment]
Thanks

Korean Spy

Feb 25, 2013 16:42 "Tyler Renelle" notifications@github.com 작성:
