### ISSUE TITLE
Older skins missing dark outline on avatar customization page

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5171]
Recent skin sets have a dark outline around them to make it easier to tell what the skin will actually look like when used on one's avatar. However, older sets, such as the free skin colors and the old Spooky Skins, lack the outline. This makes for an inconsistent look:

![image](https://cloud.githubusercontent.com/assets/4501321/7542003/2396d222-f57f-11e4-9d25-348f62f7f490.png)

**Comment by lemoness** [comment]
I will ping the Pixels in Progress Guild about this!

**Comment by lemoness** [comment]
Done, thanks to Painter de Cluster! Let me know if you're missing any.
![skin_f69922_sleep](https://cloud.githubusercontent.com/assets/3494081/8118114/1cbc9418-1042-11e5-8873-67c29908cae6.png)
![skin_f69922](https://cloud.githubusercontent.com/assets/3494081/8118115/1d055b44-1042-11e5-9369-8f47a240199d.png)
![skin_f5d70f_sleep](https://cloud.githubusercontent.com/assets/3494081/8118119/1d7b4d04-1042-11e5-961f-ae7aa66f0e9d.png)
![skin_f5d70f](https://cloud.githubusercontent.com/assets/3494081/8118120/1d87fd10-1042-11e5-984d-c2b9b78102e7.png)
![skin_f5a76e_sleep](https://cloud.githubusercontent.com/assets/3494081/8118124/1d980854-1042-11e5-8001-ebf4c07e9496.png)
![skin_f5a76e](https://cloud.githubusercontent.com/assets/3494081/8118125/1d98096c-1042-11e5-8d48-b13c47c54856.png)
![skin_eb052b_sleep](https://cloud.githubusercontent.com/assets/3494081/8118122/1d8dff4e-1042-11e5-84ac-0ed5d6748a4b.png)
![skin_eb052b](https://cloud.githubusercontent.com/assets/3494081/8118116/1d2d67b0-1042-11e5-9194-a6c6d1862527.png)
![skin_ea8349_sleep](https://cloud.githubusercontent.com/assets/3494081/8118117/1d4b3f7e-1042-11e5-993d-2350a6d0ac18.png)
![skin_ea8349](https://cloud.githubusercontent.com/assets/3494081/8118118/1d722e36-1042-11e5-990f-dfa220d0cd51.png)
![skin_ddc994_sleep](https://cloud.githubusercontent.com/assets/3494081/8118121/1d8bdbb0-1042-11e5-9e4b-03a84932d1d7.png)
![skin_ddc994](https://cloud.githubusercontent.com/assets/3494081/8118123/1d93feda-1042-11e5-981c-ed739ef10cd7.png)
![skin_d7a9f7_sleep](https://cloud.githubusercontent.com/assets/3494081/8118126/1da0ff40-1042-11e5-9c03-4136487bd6e2.png)
![skin_d7a9f7](https://cloud.githubusercontent.com/assets/3494081/8118127/1da640a4-1042-11e5-802e-7d8128a76f2f.png)
![skin_c3e1dc_sleep](https://cloud.githubusercontent.com/assets/3494081/8118128/1daabd32-1042-11e5-81cf-de3f17562bb0.png)
![skin_c3e1dc](https://cloud.githubusercontent.com/assets/3494081/8118129/1daf192c-1042-11e5-8530-10d26ca14d00.png)
![skin_c06534_sleep](https://cloud.githubusercontent.com/assets/3494081/8118132/1dbb0a02-1042-11e5-8861-62dc95331401.png)
![skin_c06534](https://cloud.githubusercontent.com/assets/3494081/8118130/1db8ab54-1042-11e5-8a0e-f6e9820cd2e3.png)
![skin_98461a_sleep](https://cloud.githubusercontent.com/assets/3494081/8118131/1dba0440-1042-11e5-825d-894b207b5c8c.png)
![skin_98461a](https://cloud.githubusercontent.com/assets/3494081/8118133/1dbddfd4-1042-11e5-831f-b65df00bc5f6.png)
![skin_915533_sleep](https://cloud.githubusercontent.com/assets/3494081/8118134/1dc786f6-1042-11e5-8560-0920505c4071.png)
![skin_915533](https://cloud.githubusercontent.com/assets/3494081/8118135/1dc7eccc-1042-11e5-8ff7-3d9eec7000fe.png)
![skin_800ed0_sleep](https://cloud.githubusercontent.com/assets/3494081/8118136/1dd7654e-1042-11e5-8189-3396eac9ffe8.png)
![skin_800ed0](https://cloud.githubusercontent.com/assets/3494081/8118137/1dd8eaa4-1042-11e5-89aa-5d5219594e61.png)
![skin_6bd049_sleep](https://cloud.githubusercontent.com/assets/3494081/8118138/1de4830a-1042-11e5-9273-42fe65f2f95b.png)
![skin_6bd049](https://cloud.githubusercontent.com/assets/3494081/8118139/1de8246a-1042-11e5-8d50-1e4972d159b3.png)
![skin_2b43f6_sleep](https://cloud.githubusercontent.com/assets/3494081/8118140/1de8fc32-1042-11e5-91eb-feb611a46d6e.png)
![skin_2b43f6](https://cloud.githubusercontent.com/assets/3494081/8118141/1decef22-1042-11e5-9e55-30b77cfa86d6.png)
![skin_0ff591_sleep](https://cloud.githubusercontent.com/assets/3494081/8118142/1df4b108-1042-11e5-9b92-d97b6ba95960.png)
![skin_0ff591](https://cloud.githubusercontent.com/assets/3494081/8118143/1df73e78-1042-11e5-9435-07897f96e7ee.png)
