### ISSUE TITLE
windows phone app

### ISSUE THREAD

**Issue by 13uLL** [HabitRPG/habitica#5177]
App is broken and won't load after first login. Seems to be a common issue for a lot of users. Please fix asap. I would love to new able to show this off to my friends and help grow the community.

**Comment by crookedneighbor** [comment]
Pinging @negue

**Comment by negue** [comment]
@13uLL  What Winows Phone App do you mean?
1. http://www.windowsphone.com/en-us/store/app/habitrpg-metro/16136b45-3188-4c93-b6f1-da0b9e23ba4f 
2. https://www.windowsphone.com/en-us/store/app/habitrpg/3ce66e8b-811d-4701-b78b-b05fb766457d
3. http://www.windowsphone.com/en-us/store/app/habitrpg-unofficial/e9d4bd28-9868-4b5e-a568-6f63510aa645

**Comment by 13uLL** [comment]
Number two. I'm downloading 1 to try that.

**Comment by negue** [comment]
Every of these 3 are unofficial apps.

The first one is mine^^, so if this one not working I can help :)

The 2nd seems not to be updated anymore since... 2 years.

**Comment by 13uLL** [comment]
Yep First one works great. Thank you very much!!

-----Original Message-----
