### ISSUE TITLE
New Adventurer (Avatar), Inventory, Achievement And Profile Screen Concepts

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#518]
Concept to replace current pop up that appears when clicking on an Avatar.

Basic looking at the moment but hoping our [merry band of artists](https://github.com/lefnire/habitrpg/issues/107) can polish up them up.

Note the current avatar customization screen would be accessible by clicking on the avatar image within Inventory screen.

Images and ODG files used to create available [here](https://docs.google.com/file/d/0B1BZD9T72VKAS0pibnZYM0RpTGM/edit?usp=sharing).

![HabitRPG Adventurer Concept 01](https://f.cloud.github.com/assets/3202339/194756/06de4456-7fbd-11e2-89a1-c8bb80cea061.png)
![HabitRPG Inventory Concept 01](https://f.cloud.github.com/assets/3202339/194758/0722d06c-7fbd-11e2-8ba5-7e37eaecfcbb.png)
![HabitRPG Achievements Concept 01](https://f.cloud.github.com/assets/3202339/194757/06f65096-7fbd-11e2-856f-6961508f9f42.png)
![HabitRPG Profile Concept 01](https://f.cloud.github.com/assets/3202339/194759/07227496-7fbd-11e2-9cc9-73a4d0b869b2.png)

**Comment by horusofoz** [comment]
From Shaners:
Looks great! I would maybe go for a more pixely font, silhouetted icons for inventory slots, and something like bar graphs for stats in relation to one another so you could at a glance know which you are more powerful at. Are strength, int, dex going to be related to task type completed? e.g. if you complete a work out tasks you'll gain more str stat? This is more of a question in general. Maybe even experience and tnl could be a pixel bar.﻿

**Comment by horusofoz** [comment]
Possible font - http://www.thealmightyguru.com/GameFonts/Series-ChronoTrigger.html
![Image 6](https://f.cloud.github.com/assets/3202339/195052/0592564e-7fd3-11e2-9221-f7c8bbe6fd76.png)

**Comment by wc8** [comment]
The original font seems to suit the character of the pixel art, if not matching the pixel art style itself.

**Comment by wildcate** [comment]
The original font is lovely, but I find it quite hard to read on the profile page mockup - I can't tell whether it's "Jeff" or "Jepp". Numbers (stats page) are also not easiest to read. Curiously, the "join date" numbers sort of seem different from the rest of the font style.
Maybe combine the original font (for headings) with a second font that is a little clearer for the text in profile etc.?

**Comment by busterroni** [comment]
I think @wildcate 's idea is good. The headings could be the first font and the information could be the more pixelated one (Chrono Trigger).

**Comment by lemoness** [comment]
I like the different pages, for sure! 
1. I definitely agree that this font is very hard to read. When I want to see my stats, simpler is much better. It doesn't even need to be that pixelated - just readable. Plus, I don't think curlicues fit our style.
2. Will that be the actual picture on the adventurer page? I'm not a big fan of it. If not, what will replace it?
3. There should be a page for pets/mounts.
4. For the item page, we'll probably need more space for costumes (and possibly items).  Maybe an armory? After all, people are probably going to want to swap through various costumes, especially things they have bought with tokens.

**Comment by horusofoz** [comment]
Hey gals and guys.

Just wanted to clarify these concepts are for tinkering, modding, scrapping
and recreating as your creative minds see fit.

What I've provided are basic "sketches" of how I imagine the basic shape to
appear. The images, fonts, screen layout, etc, all are encouraged to be
changed up to be more aesthetically pleasing.

Looking forward to what you guys come up with.

_Horusofoz_
*
*
"Live to learn. Learn to live." J.W.S.

**Comment by Pandoro** [comment]
I really like this idea. The current profile page looks a little pale, so getting something more stylish in there sounds like a great thing! We should probably think about the other proposed [GUI changes](https://github.com/lefnire/habitrpg/issues/361) #361 . There is no real purpose of designing this if we then change the general GUI and this doesn't fit anymore. 

I agree that the font should probably be changed into something more pixelish, or something more similar to how the font is looking currently. The Achievement page will be something that is needed most definitely at some point and the stats page as well once stats are there. 

I really like the idea of an inventory as well. I have said this as several occasions that it would be nice to keep the items you have bought earlier, maybe for trading or reselling them at a smaller GP reward. This would also add the option to realize something as proposed by #207 and it would be a good place to keep items you bought with tokens, or the backers only stuff. You could organize the pets you own and show these slots where you can place the items you want to use currently.

**Comment by orangisque** [comment]
Awesome, a more substantial profile/inventory/player doodads page is definitely needed.

I think it will be nice to include our RPG history in there too. We have those bar graphs that are attached to each task, but it'll be nice to compare how often (or not!) we do certain tasks to each other. Or stats on our "longest stale task" or longest ongoing streak for a habit. I know the streak thing really helps me keep up with Codeacademy, so something similar can be used here? 

I agree that the design of this should probably fit with the overall site look and design, if it ends up changing at the end. Just the general use of the container, typographic and colour choices to match and then other stuff can be pretty customized (for example, the inventory).

**Comment by horusofoz** [comment]
Update Screens :) HUZZAH!

Avatar Screen. I've combined the inventory and character info onto one as I think it's a better use of space. Also if we have stat modifying item it would be good to see their effect as you put them on rather than have it on a different tab.
![HabitRPG Avatar Screen Avatar](https://f.cloud.github.com/assets/3202339/242663/4e739520-8a24-11e2-9352-991dcde452d0.png)

Mount Screen. As we are introducing new features around the mount/pet I thought it would be good to have it's own tabe with it's info and items. I doubt we'd have this much equipment for it or at least for a while but when we do we know we'd have the space with this design. The items section here is for mount specific items such as modifiers.
![HabitRPG Avatar Screen Mount](https://f.cloud.github.com/assets/3202339/242664/4f521372-8a24-11e2-8c31-7d993b0016fe.png)

Achievements Screen. Not much different here. Note recorded achievements are badges/trophies the user chooses to statically display where as recent achivements are dynamically updated.
![HabitRPG Avatar Screen Achievements](https://f.cloud.github.com/assets/3202339/242662/4e6f495c-8a24-11e2-8e31-702c264042b2.png)

Profile Screen. The profile screen is probably going to have a toggleable option to make publicly viewable so I've included recorded achievements for showing off. The big avatar on the screen is in place of a user uploaded image/photo. No need to double post my mug ;)
![HabitRPG Avatar Screen Profile](https://f.cloud.github.com/assets/3202339/242665/4f5efc90-8a24-11e2-9600-6319de315962.png)

What do you think?

**Comment by lemoness** [comment]
@horusofoz  

I really like them! Two comments:
1.  I like the mount/pet features, but what are these equipable items? Are they going to be visible, or are they just for stats? There also needs to be a way to display more than one pet and more than one mount (since you-ll choose an active one of each, but we don't want to discourage players from having more, although it's fine if we cap it at like, five) and maybe for pets a progress bar showing when they can evolve into a mount.
2. I understand why you might want to combine info and the character page, BUT I think that actually it isn't the best idea, because we want people to have a lot of different clothing and weapon options that they can easily switch between. Only seeing one line of that at a time seems very cramped, given the potential number of things and the fact that people will be keeping/displaying all their old armor. So if you have four hats and three robes and  three shields and two swords, plus a specialty weapon and a holiday hat and three custom outfits, plus two miscellaneous backgrounds.... it really builds up! To say nothing of people who have gotten all the way to the top in their class.

This can be alleviated a little bit if you don't show people's old outfits, but I really like being able to see them and maybe having the possibility of switching back and forth, ESPECIALLY once we add class to the mix, and thinking farther down the line where people might have more than one color option that they can buy. It's like a badge of honor - check out all the different armors that I own!

Even if we do decide not to show old armor and items, we're penalizing users who want to buy a lot from the store. 

Given that multiple outfits are one of Habit's biggest potential money-makers, in my view, it's better to give people a big empty armory to fill.

**Comment by caycefischer** [comment]
Its interesting that you show a version of the avatar where the clothing, armor, etc is separated off. That's kind of cool, usually we only see it on the character. We shoud probably do it like most RPGs do and show the avatar clothed AND have the boxes as you show.

Also, re: talk of fonts and such, remember that we're forking our UI - there's basic mode, which is currently using Lato for a font, and "badass retro mode", which is where we can go whole-hog with chrono-trigger style fonts. Just so we keep the discussion separate and don't push ourselves into a compromise between the two that nobody really likes.

I'm really digging the extended profile page and the way you have the top tabs, I think it organizes this info really well and would fit right into a mobile or tablet interface without any trouble at all. And I agree, this is the perfect place to integrate history/stats, and get it out of the task view.

Also, have we talked about gear for the pets at all? That's awesome too.

@horusofoz some good work here :)

ONe thing that's missing is char customization, not equipment but the interface we have now for hair, skin, etc etc etc. That probably goes in the fourth tab somewhere

**Comment by horusofoz** [comment]
@lemoness 
Mount: The equipment for the mount is an idea for the future. I don't think we would introduce it any time soon. The mount screen minus the equipment but with items list for food etc would be product at this time. I didn't know we were going to have multiple pets. Is this confirmed?

Equipment: I understand what your saying. I would counter that having limited item storage slots (10~) is a good way of encouraging users to think about their storage the same way you would with a normal RPG where you would sell or drop items of lesser value to make space. A thought arisen from this would be an extended item storage option as a monetization factor. Very reasonable IMO and believe it exists in current RPGs.

**Comment by caycefischer** [comment]
I think we are supporting multiple pets (as we do now). The one we display
with the avatar depends on the user's choice—the rest hang back and chill
in the Stable while they're out adventuring.

On Tue, Mar 12, 2013 at 11:09 AM, horusofoz notifications@github.comwrote:

> @lemoness https://github.com/lemoness
> Mount: The equipment for the mount is an idea for the future. I don't
> think we would introduce it any time soon. The mount screen minus the
> equipment but with items list for food etc would be product at this time. I
> didn't know we were going to have multiple pets. Is this confirmed?
> 
> Equipment: I understand what your saying. I would counter that having
> limited item storage slots (10~) is a good way of encouraging users to
> think about their storage the same way you would with a normal RPG where
> you would sell or drop items of lesser value to make space. A thought
> arisen from this would be an extended item storage option as a monetization
> factor. Very reasonable IMO and believe it exists in current RPGs.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/518#issuecomment-14780587
> .

## 

_– Zachary Kain_

Designer, Creative Technologist
416-712-8895
zakkain@gmail.com
→ view my resume/profile http://zerply.com/zakkain/public

**Comment by horusofoz** [comment]
@zakkain 
Avatar Equipment Appearance: I agree. It will look better if you can see "live" what equipment changes would look like without exiting the avatar screen.

Fonts: I like the idea of the two aesthetic modes. For myself would probs use basic in the office and switch to Chrono mode when at home.

Pet Equipment: I figure since pets have evolved to the point of near being an additional avatar they deserve more limelight. Equipment ideas are Enchantment for claws/teeth, collar, helmet, saddle and armour.

Character Customization: As advised way up the thread, this would be accessed by clicking on the Avatar image on the Avatar Screen. Alternatively we could add a button between the avatar image and items list to trigger this.

Multiple Pets: Awesome. We'll still only need the one screen then as the rest are chilling at the Stable.

**Comment by caycefischer** [comment]
Rad. I can't wait to put a helmet on my cactus

On Tue, Mar 12, 2013 at 11:20 AM, horusofoz notifications@github.comwrote:

> @zakkain https://github.com/zakkain
> Avatar Equipment Appearance: I agree. It will look better if you can see
> "live" what equipment changes would look like without exiting the avatar
> screen.
> 
> Fonts: I like the idea of the two aesthetic modes. For myself would probs
> use basic in the office and switch to Chrono mode when at home.
> 
> Pet Equipment: I figure since pets have evolved to the point of near being
> an additional avatar they deserve more limelight. Equipment ideas are
> Enchantment for claws/teeth, collar, helmet, saddle and armour.
> 
> Character Customization: As advised way up the thread, this would be
> accessed by clicking on the Avatar image on the Avatar Screen.
> Alternatively we could add a button between the avatar image and items list
> to trigger this.
> 
> Multiple Pets: Awesome. We'll still only need the one screen then as the
> rest are chilling at the Stable.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/518#issuecomment-14781303
> .

## 

_– Zachary Kain_

Designer, Creative Technologist
416-712-8895
zakkain@gmail.com
→ view my resume/profile http://zerply.com/zakkain/public

**Comment by lefnire** [comment]
wait, we're equipping pets? :/

**Comment by caycefischer** [comment]
RUH ROH

![hugemistake](https://f.cloud.github.com/assets/546495/249449/fbf2cee6-8b2d-11e2-8fca-64c37be40a8e.gif)

**Comment by horusofoz** [comment]
@Tyler Just an idea at this point which I've incorporated into the mockup
to show how it could work. If the screens were introduced tomorrow there
would be no equipment slots for the mount, just the item slots for food and
other pet stuff. If we decide to add the equipment theres no need for a
major overhaul as the layout already is designed to accommdate it.

I havent put the mount equipment idea on Trello yet as dont want to
generate interest when its something Id expect down the track when we've
delivered on the KS goals, rounded out the GTD feature requirements and got
everything polished. Again a bit off at this stage.

**Comment by lefnire** [comment]
Gotcha

**Comment by wc8** [comment]
Maybe this is the point of the UI fork, but in case: I think the UI fork could address many, if not all, of the requests in #211 which on Trello as [Gamification Options](https://trello.com/c/EKxy5lYI). See the trello card for some of my ideas about how.

**Comment by horusofoz** [comment]
I think another good function for the Avatar screen would be to a button to toggle whether you see the equipment worn or plain clothes for your avatar. This way by default you see your character in plain clothing but if you want to you can switch to equipped to see what item changes do to your appearance as well as stats from the one screen.

**Comment by lemoness** [comment]
Testing a reply straight from my email for the first time; let me know that
it worked!

**Comment by lemoness** [comment]
Looks like it's all set. Actual reply:

I love the Stables! Perfect, perfect, perfect. Sans equipment for now,
mount screen is good to go!

@horusofoz Selling and dropping items makes a lot of sense! However, do you
really think that people will want to pay for more space so they can pay
for more token items? It seems like we're layering the two moneymaking
schemes on top of each other. I can easily see people being discouraged
from buying extra token items because they'd have to "pay twice", once for
the item and once for the space.

  How about a compromise - keeping the small number of "active equipment"
slots, we could introduce a similar space to the Stables - an Armory! You
could have the option of displaying it to your friends to show off your
collection, or just use it as storage. We could give a large number, like
30 slots, and after that to expand you have to pay either a lot of gold or
a small number of tokens.

It keeps the profile clean while not limiting people who want to support us
by buying customization :) Plus it's another opportunity for an NPC!

**Comment by wc8** [comment]
I think the armory to display one's armor is a great idea. It particularly seems reasonable to charge tokens for extra armory containers, as it's something that doesn't change the game outcome at all.
Would one be likely to have more than 30 pieces of armor? How many are there now?

**Comment by horusofoz** [comment]
I think an armory idea has merit I would say no more than an additional 10 slots by default. Then say 2 tokens ($2) for an additional 10 storage slots. A real game example is the [WoW Bank](http://www.wowwiki.com/Bank).

**Comment by Pandoro** [comment]
Keep in mind the eggs, the food, the quest drops, all items. If you want
your gear to be switchable and save up some food for that one darn egg you
have been waiting for, while doing a quest, you better get yourself a new
inventory ;)

Additionally the token items, which will most likely be pure looks anyway,
could be in a separate infinite inventory if desired.

**Comment by wc8** [comment]
:+1: Armory and purchased containers for armor & weapons. I think it's a good outlet for token use. As I understand it, it wouldn't affect the game outcome at all (you'd still have the other armor, you just wouldn't be able to display it). The 10 default slots seems better in that case than 30.
Would there be a mechanism for choosing which purchased items were visible in the slots?

I agree, since you're purchasing the pets you shouldn't have to pay to display them. After all, the display is a form of advertising: one user sees a neat pet on his party member's page and thinks neat, I'd like that.

I think quest items, especially active quest items would need their own page or its own set of pages, even if one of the pieces happens to be armor. It wouldn't be good to have to purchase slots to see where you are in your quest. 
Would quests need their own achievements page?

**Comment by lemoness** [comment]
Yeah, I agree that quest items should be kept separate. 

Assuming that the Armory also works as an inventory for your stuff, as @Pandoro pointed out, I still think that 10 might fill up quickly... maybe let's compromise with 20 initial ones, and then you add 10 each time? 

Should I make a new github thread for the Armory, or just put it straight on Trello?

**Comment by wc8** [comment]
I suggest: Armory (weapons/armor), Chest/Keep (general inventory), Stables (pets?) be separate. 
If the Armory is going to be for everything then call it a Keep.

**Comment by lemoness** [comment]
Yeah, I like Armory, Chest, Stables separate.  Armory and Stables have an
NPC, Chest does not?

Also, is this on Trello yet?

**Comment by horusofoz** [comment]
My thoughts.

Armoury for weapons/armour with 10 slots by default accessed at a certain level and expandable storage through tokens.

Chest/Keep for general inventory, pet modifiers, etc with 10 slots by default accessed at a certain level and expandable storage through tokens.

Stables for pets/mounts with 10 slots by default accessed at a certain level and expandable storage through tokens.

Note this would hypothetically be in addition to the Avatar and Mount Inventories of 10 slots a piece.

Haven't put to Trello yet as idea needs to be nutted out a bit more IMO. e.g. Need to define Exactly what would be included in the first iteration. My thoughts are pretty much how it is now but with no equipment for the mount/pet.

@lefnire @switz @zakkain  Can you define the parameters of what would make it in then we can put it on Trello?

**Comment by lemoness** [comment]
@horusofoz - Sounds perfect to me! Only thing that might be up for debate
is whether pet-related items go in the Stables or not, but personally I
think they work fine in the Chest.

Does the Chest have an associated NPC? Maybe The Guard?

Armory NPC is apparently "Armorer"?
http://dictionary.reference.com/browse/armorer?s=t How do we feel about
that? I think it sounds like we're making it up. Then again, pretty
straightforward....

**Comment by horusofoz** [comment]
An armoury and chest/misc item storage NPC sounds good. But this is a ways off.

Lets get back to what can be implemented ATM.

Avatar/Inventory screen with the standard 10 item slots for quest items, etc. Not a great many but better than no inventory.

Mount Screen with info and 10 pet modifier,etc items. Possibly with no slots if too hard to implment at this first pass.

Achievements screen should be good as is. I envision users can drag/drop or similar mechanic to move badges/trophies between recent and recorded achievements for longer term display as desired.

Profile page can be implemented pretty much as is minus Forum Name. Maybe sub with GitHub and Trello name fields.

@lefnire @zakkain @switz Can you advise if this basic implementation would be deliverable within the first pass?
