### ISSUE TITLE
some info-popover don't vanish automaticaly 

### ISSUE THREAD

**Issue by wuschLOR** [HabitRPG/habitica#5180]
Hi there got an issue that’s bugging me for a long time - especial when hatching stuff:

the info texts that pop up don't vanish - this makes hatching more than 2 egs anoying

![popups dont go away](https://cloud.githubusercontent.com/assets/2751321/7554318/3882eb84-f724-11e4-9b09-5516295f71bd.png)

EDIT: running kubuntu 14.04 / Firefox 37.0.2
##

**Comment by crookedneighbor** [comment]
This does not occur for me. On a mac, tried it in: Chrome, Firefox and Safari. 

I don't have a linux machine at the moment. Do any other devs have the ability to boot up a Kubuntu machine and try it in firefox?

@wuschLOR Is it just the hatching potions that are doing this? Or more things? I'm wondering if [the service we use to generate the dynamic popovers](http://angular-ui.github.io/bootstrap/#popover) is incompatible with that version of Firefox for some reason.

Can you list for me specific examples of things (other than potions of course) that exhibit this behavior, as well as specific examples of things that do not? That'll help me track down patterns in the code. 

Would you also mind trying the page in another browser? I'm curious if it's limited to Firefox or if it occurs in other browsers on Kubuntu.

**Comment by wuschLOR** [comment]
@crookedneighbor 
Tried it with chromium - no problems here (I think had nothing to hatch) - therefore seems to be firefox related

I think its the combination of the info + clicking (behavior like the menu buttons) - while item equipping doesn't reproduce this behaviour

Just to be sure the menu points should they stay open when I clicked on them or is that also unwanted? Cause I can only close them when clicking on exactly the same button - clicking somewhere else doesn't work ;) 
(behaviour chromium + firefox the same in this regard )

PS: ty for the actual term - I meant the popover not popup sorry for the wrong term

**Comment by crookedneighbor** [comment]
No worries about the term, it was clear from your screenshot what you meant. 

Yes, the menu popovers should appear on click and persist (so you can click on the links). 

The potions popovers should appear on hover, not click, and should not persist. 

The only real difference I see between the potion popover and the equipment popovers is that the potion elements are buttons under the hood, while the equipment ones are not. I wonder if that's why the behavior is slightly different. The quests and eggs are also buttons, can you confirm whether or not they are behaving the same way as the potions?

**Comment by wuschLOR** [comment]
quests and seeds don't have this problem apparently.

eg seem to have it too 
![popups dont go away2](https://cloud.githubusercontent.com/assets/2751321/7554672/57edc676-f731-11e4-8057-aafa19e2ffa3.png)

and this is so persistent that it survives the quest popup
![popups dont go away3](https://cloud.githubusercontent.com/assets/2751321/7554675/71f0e71a-f731-11e4-845d-5d773aca0d78.png)

having no idea of the code - I assuming seeds and quest have some visual follow up 
- quests -> popup
- seeds -> crazy mouse courser 

egs and potions don't have this
when the dropsystem rewards me with some food i try to reproduce it with the pet feeding

**Comment by ghost** [comment]
I have the exact same issue on Xubuntu 15.04 / Firefox 38.
As far as I can tell, this appears only when feeding pets / hatching eggs. It seems that the confirmation required to feed / hatch prevents the popover to get the information that the mouse does not hover the image anymore (probably because this confirmation does steal the focus).

**Comment by deilann** [comment]
That's not what causes it. You can make this happen without feeding a pet.

**Comment by ghost** [comment]
You're certainly right, but I didn't find any other way to trigger it _yet_ on my system, while hatching or feeding is a way to trigger it each and every time, for me.
I'm willing to test any other trigger you can get your hands on.

**Comment by deilann** [comment]
Interesting. I used to be able to just mouse over and back, but that's
since been fixed.

Other things that trigger it:

Using keyboard commands to select things (this annoyingly causes a
permanent popup for _everything_ that you can't get rid of without the
mouse)

**Comment by ghost** [comment]
I'm curious. I didn't find any keyboard command to select things within the application. I tried almost anything I know without triggering anything, but maybe I don't use the right commands. Which command do you use ?

**Comment by deilann** [comment]
Through vimium.

**Comment by ghost** [comment]
The vimium extension for firefox is outdated, so I can't test it right now (might have to install chromium first). Anyway, seeing it in action makes me think that it somehow also adds some kind of overlay that steals the focus from the info-popover, which brings me back to my first idea.

**Comment by joedragons** [comment]
Happens in Windows 7 (Firefox 38.0.5) as well.

Mousing over icon associated with the "lurking" text (eg. the eggs) causes it to vanish again.

ADDENDUM: Here's a screen of it happening when feeding pets.  Note it is affecting when you scroll as well (aka my data isn't a tiger cub=)).
![habitrpgpets](https://cloud.githubusercontent.com/assets/9559205/8506061/8e203eb8-21cf-11e5-9f10-89ee671e3435.jpg)

**Comment by khipkin** [comment]
@Alys I think this can also be closed because of the redesign.

**Comment by Alys** [comment]
True! It's low priority and it will be made redundant by the upcoming website improvement project so I'm closing it.
