### ISSUE TITLE
Bulleted Markdown in groups doesn't indent correctly

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5181]
When trying to add a link list to a Guild I own, I ended up with this:

![image](https://cloud.githubusercontent.com/assets/4501321/7554799/cc6dbb72-f6fb-11e4-92e5-ef05d1d062e9.png)

Ideally, the bullets would align with the text on the line above, with the bulleted text indented beyond that.

(Chrome on Windows 7)

**Comment by crookedneighbor** [comment]
This has been bugging me for a while too. Turns out all that was needed was for `ul` to have `list-style-position` set to `inside`
