### ISSUE TITLE
Allow cancel editing group infobox

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5182]
When editing the description of a Guild, there is no obvious way to cancel editing without saving. There's a "Save" button, the "Leave" button for quitting the Guild (which really shouldn't be visible at all at that point), but no way to back out of the edit other than hitting the Back or Refresh button on the browser.

Suggestions:
- Add a Cancel button. A good place for it might be where the "Leave" button now appears.
- Allow usage of the Esc key to bail out.

Using either of the above should discard all changes and return the group infobox to read-only state.
##

**Comment by AnitaYCheng** [comment]
+1 for the cancel button, for sure! And of course, the Esc key is a good failsafe.

**Comment by vinsonizer** [comment]
I've forked the code and written a simple implementation of this that is working, but I am not sure how to contribute it back (new to git/github).  Can someone give me hints on how to do this and also how to get contributor credit (if possible)?

**Comment by crookedneighbor** [comment]
You can follow this guide to initiate a pull request: https://help.github.com/articles/using-pull-requests/

**Comment by vinsonizer** [comment]
Do i need to do anything with my user id for contribution?

**Comment by vinsonizer** [comment]
Thanks @crookedneighbor, got it worked out (i think).  If i don't get credit it is fine, but it would be neat to get the contributor badge.

**Comment by Alys** [comment]
@vinsonizer When a pull request is accepted and merged, we always ask for the submitter's Habitica User ID and use that for recording the contribution to a tier. You can add your User ID to your pull request now if you wish, although be aware that not all requests can be accepted (it's rare that one is rejected outright though).

**Comment by vinsonizer** [comment]
Ok, I am modifying it to use a angular.copy for a local working copy while editing.  This should be pretty light-weight and it would be all client side till the save button is used.  I will try to update later today and then see if i can figure out how to modify my pull request.

**Comment by crookedneighbor** [comment]
@vinsonizer When you push to your branch, your PR gets updated automatically.

**Comment by vinsonizer** [comment]
Should this issue be closed?

**Comment by SabreCat** [comment]
Ahyes! I thought GitHub would have closed it automatically, but maybe the # tag wasn't in the right place.

**Comment by vinsonizer** [comment]
No problem.  Perhaps on my next one @crookedneighbor won't have to re-write most of my tests.
