### ISSUE TITLE
Mana bar is not full immediately after unlocking classes

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5187]
Immediately after hitting level 10 my new mana bar was not full.

I hadn't allocated any attribute points and had no buffs. I used an Orb of Rebirth immediately before the class rebalance. I don't think I even had a cron between using the Orb and the rebalance going live, although I'm not certain. I hadn't performed any tasks since hitting level 10. After hitting a couple of negative habits my mana was reduced, as expected. Syncing and refreshing did not change anything.

Since I'll have at least one cron before I can use any mana this doesn't affect gameplay however it's certainly unexpected. Reporting in case it was introduced in the class rebalance and has the potential to manifest in more serious ways.

![screen shot 2015-05-11 at 22 05 41](https://cloud.githubusercontent.com/assets/2931465/7575060/ead2cb32-f829-11e4-8452-69353c5bba84.png)

40891154-6548-4dc0-a752-adc284396af0

**Comment by Alys** [comment]
@ghswa I'm sorry - we should have replied to you before now. This isn't unexpected behaviour. Mana isn't ever gained by leveling up, not even by leveling to 10. It's always earned through tasks and at cron, so it's not impossible to reach level 10 without having a full bar.
