### ISSUE TITLE
Duplicated Tasks

### ISSUE THREAD

**Issue by CCapra** [HabitRPG/habitica#5189]
As in #5161 & some others I noticed - This just happened to me too. Duplicate habits, dailies, to dos, and rewards. Even checked off dailies show up (duplicate greyed-out dailies, with checkmarks) It seems like all the duped ones were just created yesterday - older items aren't duped. I think I started using habitrpg on a second computer around the time they are duped after.

Some things are duped as much as 12 times. Tags were not effected. 

I'll delete from the bottom as recommended. But is there a fix? I'm using win8.1 and Chrome in each computer.

**Comment by hairlessbear** [comment]
Unfortunately, there isn't a fix at this time. The issue is being worked on though. If you'd like to follow the progress, you can subscribe to email updates on #4470. Sorry I can't be of more help!

**Comment by CCapra** [comment]
Thanks, I'll watch #4470.
