### ISSUE TITLE
Typed Text Disappears When Page Loads

### ISSUE THREAD

**Issue by ctuirmt00** [HabitRPG/habitica#519]
Sometimes my HabitRPG takes a while to load, so while it's loading I'll be typing some new task in my ToDo.  (I'm in Chrome) One the litlte loading sign in the corner disappears, meaning the page fully loaded, the text disappears and I have to retype everything again.

It's a huge nuisance.  Thank you to anyone who can fix it!  :)

**Comment by wc8** [comment]
Currently, it is best not to try to make changes while HabitRPG is loading. Sorry for the inconvenience.
