### ISSUE TITLE
Missing Special Warrior Equipment from Spring Fling 2015

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#5191]
I did not notice this sooner, for which I am kicking myself, but despite buying all of the special warrior equipment - indeed, all the equipment for all classes - in the Spring Fling 2015 it is not showing in my inventory. I have now switched class again to check that it has not been destroyed by one of my recent deaths (though I believe that it is now no longer the case that equipment is lost from non-active classes?). I have paid another 6 gems - in order to switch there and back again - and it is showing that this is not the case that these items are available. The only exception is the dog ears. I bought everything at the same time, so clearly some sync error occurred which went undetected by me at the time. Is there any way the equipment can be restored to me? I have spent the gems twofold now and it is frustrating that I will be missing out on the equipment (I hitherto had everything across all classes) due to a fault.

UID: 4182cdea-64db-4db4-9713-dc587d86c662

**Comment by hairlessbear** [comment]
Just to clarify, are you sure that the items aren't available for purchase in the Rewards section? When you die, you lose a piece of equipment specific to your current class (or a non-class-specific item). So, if you were a warrior when you died, you could have lost the warrior equipment, but it would be available for purchase in the Rewards section. You may have already checked this, but I just want to make sure :)

**Comment by deilann** [comment]
Eiron page has been around long enough to understand how the site works. :)

When I get home I can fix this if someone else hasn't gotten to it first.

**Comment by eiron** [comment]
Bless you. I do not need a refund on the gems. The site can have those as payment for my failure to check my actions on the fly. Long enough to know how the site works, but not long enough clearly to know to be sure that is has done so.

**Comment by deilann** [comment]
Dinosaurs. I'm not using my computer, so I don't have a json parser. Does
someone else mind fixing this?

**Comment by Alys** [comment]
@Eiron I've assigned the equipment to you. Please check and let me know if any are still missing.

I've also given you back the 6 gems. No arguments please. ;-)

_"though I believe that it is now no longer the case that equipment is lost from non-active classes?"_
That's correct.

**Comment by deilann** [comment]
Thanks @Alys!

To further cut back on any arguments... @Eiron just use them for your
awesome challenges we all love. Seriously. Challenge... Accepted? does so
much good for the site.

**Comment by eiron** [comment]
Well, then. Next challenge is going to have a bonus bundle of gems attached. My way of paying forward.
