### ISSUE TITLE
Guilds not loading, and dropping errors

### ISSUE THREAD

**Issue by davegregg** [HabitRPG/habitica#5192]
I am getting errors when I try to go to any of my guilds in Beta web, and they will not load. I can load the Party and Challenges just fine.

**User ID:** `a05571cb-6048-47f3-bd8a-f8c273d17dfa`
**Group IDs:** They do not show on the Guild page with this bug, but I copied what I suspect is the Group ID from the red error tooltip: `06ed27a3-a8fe-4e0a-bffb-eb2019af0d1d` ('The Classical Scholars'). All my guilds have this error, including 'Life Hackers', 'The developers guild', et al.
**Browser/OS:** _Firefox Developer Edition 39.0a2 (2015-05-11)_ on _Windows 10 Insider Preview Build 10074._

The red error tooltip says this:

```
Please reload, "Error Object { _id: '06ed27a3-a8fe-4e0a-bffb-eb2019af0d1d',
inbox: {},
stats: { training: {}, buffs: {: {},
backer: {},
auth: { timestamps: {}, local: {} },
achievements: {} } has no method 'push'" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.
```

My Firefox console displays these:

```
"Error: a.group is undefined
a.chatChanged@https://beta.habitrpg.com/app-7efa481d.js:44:1
wd/this.$get</j.prototype.$digest@https://beta.habitrpg.com/app-7efa481d.js:8:15972
wd/this.$get</j.prototype.$apply@https://beta.habitrpg.com/app-7efa481d.js:8:17526
g/m<@https://beta.habitrpg.com/app-7efa481d.js:8:25528
p@https://beta.habitrpg.com/app-7efa481d.js:5:21505
Yb/f.defer/c<@https://beta.habitrpg.com/app-7efa481d.js:5:23506
nrWrapper@https://beta.habitrpg.com/#/options/groups/guilds/3f88cb57-e491-471e-90a3-b5a6cdb6a3d4:1:11505
" app-7efa481d.js:7:25758
e/<() app-7efa481d.js:7
kc/this.$get</<() app-7efa481d.js:7
wd/this.$get</j.prototype.$digest() app-7efa481d.js:8
wd/this.$get</j.prototype.$apply() app-7efa481d.js:8
g/m<() app-7efa481d.js:8
p() app-7efa481d.js:5
Yb/f.defer/c<() app-7efa481d.js:5
nrWrapper() beta.habitrpg.com:1
```

```
Object { data: Object, status: 500, headers: tc/<(), config: Object, statusText: "Internal Server Error" } app-7efa481d.js:41:25881
.responseError() app-7efa481d.js:41
j() app-7efa481d.js:8
k/<() app-7efa481d.js:8
wd/this.$get</j.prototype.$eval() app-7efa481d.js:8
wd/this.$get</j.prototype.$digest() app-7efa481d.js:8
wd/this.$get</j.prototype.$apply() app-7efa481d.js:8
s() app-7efa481d.js:7
w() app-7efa481d.js:7
y() app-7efa481d.js:7
nrWrapper() beta.habitrpg.com:1
```

**Comment by Alys** [comment]
Please do not use the beta website. We use it for testing various features and it cannot be considered reliable. If you find that the same error occurs on the production site, log out, clear your browser's cache, close all browser windows, and then try again. Let us know if it still happens on production.

**Comment by crookedneighbor** [comment]
Just for the record, this was my fault. Apparently I don't know how arrays work?

Fixed with: https://github.com/HabitRPG/habitrpg/commit/4050e9ad0c16dfb9449d04d0a3e737dd76413768
