### ISSUE TITLE
Can't Select Dailies With Keyboard

### ISSUE THREAD

**Issue by Satvik** [HabitRPG/habitica#5196]
I'm a keyboard user and can't regularly use my mouse due to wrist pain. I used to be able to select the checkbox for dailies and hit enter. Sometime in the last two weeks, there's been a UI change and the checkboxes for dailies are no longer selectable, meaning I can no longer use the keyboard (and that makes HabitRPG unusable for me). For example, the screenshot shows letters over everything that's selectable: 
https://www.dropbox.com/s/we8c9in17urgf72/Screenshot%202015-05-13%2008.43.57.png?dl=0

Note that habits and rewards can still be checked, but for some reason dailies can't.

Chrome 42 on Yosemite: whatsmybrowser.org/b/S3RNUDA

**Comment by Alys** [comment]
I'm labelling this as "priority - important" because I believe we should consider usability problems like this to be bugs that need to be fixed promptly.

@Satvik We'll have to do some experimentation to work out what caused this change. I can't replicate the behaviour that allows me to use the keyboard to check Habits and Rewards (and so I won't be able to check Dailies either when we find the code that changed). Do you have something in your browser that gives that behaviour and that inserts those letters? Or is it an OS setting? I'm running chrome on Mac OS so I have a good chance of being able to use the same software.

**Comment by Satvik** [comment]
Thanks @Alys! I'm using Vimium on Chrome: https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en

Installing vimium and hitting "f" shows the letters, then typing the letter clicks the link. I was also previously able to get to the checkboxes by hitting tab several times.

**Comment by deilann** [comment]
uh, not only is this prio important, but this ticket may have just changed
my life because I need to rely less on the mouse.

so thank you.

**Comment by Alys** [comment]
Yes, those Vimium controls are really convenient! I think I'll keep using it. @Satvik Thanks also for using http://www.whatsmybrowser.org. We'll add that to our Report a Bug instructions.

I'm going to go back through the site's versions for the past couple of weeks until I see where the checkbox feature disappeared. That should give us a good idea of what caused it. This might take me a few days though. :(  However I should be able to prioritise it on the weekend.

**Comment by deilann** [comment]
To note, this also affects To-Dos.

**Comment by deilann** [comment]
@Satvik Is the persistent popovers a continual issue as well? Because then
without mouse, they're very difficult to get rid of. Which I think makes
them a higher prio issue than we've been considering them.

**Comment by Satvik** [comment]
Those haven't been an issue, I'm able to close them with Vimium

**Comment by deilann** [comment]
Curious -- how do you close them?

**Comment by Satvik** [comment]
Oh, in my previous comment I was thinking of alerts, not popovers. I never
end up triggering the information popovers because I don't use the mouse.

**Comment by deilann** [comment]
Whenever I do something like sync or select an item (like to hatch a pet),
it's triggering the popovers for me. And then I can't get rid of them
because they persist.

**Comment by Satvik** [comment]
Oh, got it. I never run into that because I don't use those features (I
pretty much only use the habits, dailies, spells, and some party features.)

**Comment by deilann** [comment]
kk. I think (I also have wrist pain issues) I am going to up the prio on
those as well because that's a usability of those features issue for folks
using keyboard commands.

**Comment by Alys** [comment]
@Satvik I've gone back to a few versions of HabitRPG's source code, the earliest being from mid February, and I can't find any versions in which the Dailies checkboxes can be used with the keyboard. It's possible I'm misunderstanding what should happen. 

With Vimium installed, I should be able to hit "f" and then control letters will appear on top of each Daily's checkbox - is that right? Also, I should be able to hit tab repeatedly until I get to the Dailies, and then use tab to move to the desired checkbox for a Daily - yes?

Unfortunately I can't get either of those things to work from the source code from February.

Until recently, have the Dailies checkboxes **always** worked? Or have there been other times in the past when they stopped working for a while?

Another possibility is that one of the third party libraries that we use has been updated in a way that conflicts with vimium. That could be harder to track down.

I don't suppose there's any way you can more precisely work out when the problem started? I'll understand if there isn't. :)

**Comment by Satvik** [comment]
I'm pretty sure it started within the last 3 weeks, I don't think I ever
had problems using Vimium for habitRPG before that, and I've been using
both for more than a year.

It could also be a Vimium update that caused the issue, Vimium has had two
version updates in the last few weeks (and they usually don't.)
Unfortunately I couldn't figure out how to revert to an old version of
Vimium to test this

**Comment by Alys** [comment]
Thanks for that! That gives me something else to look into.

**Comment by deilann** [comment]
I really hope we can get it working. This has made more detailed Habit
setups viable for me.

**Comment by Alys** [comment]
I still haven't been able to find anything that changed in HabitRPG that clearly caused this, and the descriptions of the recent vimium changes don't seem to be relevant. I'm considering asking the vimium developer(s) if they'd be interested in investigating, although they're probably busy....

**Comment by deilann** [comment]
Hey, it's worth a try!

**Comment by TheHollidayInn** [comment]
How did the task look when you selected it before? With a simple css change I can make the input selectable, but it looks like this.

![screen shot 2015-06-29 at 7 36 47 pm](https://cloud.githubusercontent.com/assets/1253400/8421557/3351973e-1e96-11e5-820d-d1da4a8ed347.png)

**Comment by Satvik** [comment]
It did look like that! But that didn't bother me.

**Comment by TheHollidayInn** [comment]
Sweet. :) I will fix it after I get off work.

**Comment by crookedneighbor** [comment]
This change will go live in the next couple of days. Not only will you be able to select dailies/todos/habits/rewards with the tab key, but also with Vimium!

Big kudos to @TheHollidayInn for working on it and putting up with my demands :smile:

**Comment by TheHollidayInn** [comment]
:) All for the greater good!

**Comment by unaimed** [comment]
Hey there,

I think this issue has been reintroduced after the rewrite: 6fb4c1b57643aef987b381c99650e519ec57bf4b
A fix would be a great help for accesibility.

**Comment by Alys** [comment]
@unaimed Thanks! We have this reported again at https://github.com/HabitRPG/habitica/issues/9796
