### ISSUE TITLE
Random rewards

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#52]
Random rewards and the possibilities for motivation: if you think you might miss an award because a task randomly comes up you will fear missing the chance to get points. (I hope it is ok that I grabbed your email via the HabitRPG site.) I wanted to share the article that I referenced relating to power that email holds: "So you get an e-mail from your mom, or you get an e-mail from your boss—they contain snakes or berries or bears, but they’re not self-evident until you look" The [Atlantic Nov 2012](http://www.theatlantic.com/magazine/archive/2012/11/busy-and-busier/309111/?single_page=true). This topic is also popular in behavioral economics as an explanation for why random reward systems (ie slots) trigger such strong impulses for some people. Though it seems to tap into a "flaw" in human rationality, it seems that most behavioral modification has to tap into something rather basic.

**Comment by wiber** [comment]
Food for thought. Thinking. Key word: Meaningful. Tricky. That goes down the (deep) rabbit hole of rankings, sharing tasks in a news feed, (woopsie) or other social dynamics where your consistency / performance has an impact. There do be dragons in there.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Not the original request but a possible outlet for the idea: in #199 [Mini-Games](https://trello.com/c/tJl77IMU) "Certain dailies or todos could grant a random bonus for fight of the day."

**Comment by wc8** [comment]
The [Game Items](https://trello.com/c/A7rlkOlN) proposal is a random reward scheme.
