### ISSUE TITLE
Ruby Gem?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#520]
Would anyone find a Ruby gem for habitRPG useful?  If so ill whip up one...

**Comment by wc8** [comment]
It sounds like a good idea. I suggest you check in via #107 to see if there are any guidelines (eg. size) to keep in mind.

**Comment by tmas** [comment]
@wc8 Pretty sure he's talking about [this kind of ruby](http://www.ruby-lang.org/en/).

**Comment by wc8** [comment]
LOL. I'd been reading all kinds of requests for gemstone features and drops. I didn't even think of the other kind of ruby.

**Comment by ghost** [comment]
Go nuts
https://github.com/lefnire/habits-rails

**Comment by lefnire** [comment]
Oh! Haha, be careful with that app! That's habitrpg v1, written on rails
and before I converted it to javascript. It's and old deprecated app.

**Comment by wizonesolutions** [comment]
...I'd be interested in a Ruby gem implementing the API.

**Comment by wizonesolutions** [comment]
I already went with node.js, so no worries. Rolled my own with what I needed. https://github.com/wizonesolutions/habitrpg-todo-sync
