### ISSUE TITLE
prevent ongoing questions about no attribute points after level 100

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5203]
Now that attribute points are not gained above level 100, we're going to get ongoing questions about that; we've had several over the past few days. I suggest that when you are above level 100, the User -> Stats screen contains a message stating that there's no more points, but that you can keep levelling up, or use the Orb of Rebirth for free. It could perhaps go just under the arrowed text in the image below.

@lemoness What do you think?

![screen shot 2015-05-13 at 8 14 57 pm](https://cloud.githubusercontent.com/assets/1495809/7629054/e1ee6036-fa6c-11e4-951f-ef0ff9ef8096.png)

**Comment by deilann** [comment]
YES

**Comment by lemoness** [comment]
Yes, yes, yes, a thousand times yes.

"Congrats! Now that you've hit level 100, you won't gain Attribute Points
any more. You can keep leveling up, or you can use the [Orb of Rebirth] in
the Market to reset to level 1!"

**Comment by SabreCat** [comment]
:+1:

**Comment by Alys** [comment]
I've advertised this in Aspiring Coders.

To whoever takes this on: comment here so that everyone else knows you've claimed it. In your PR, please include a screenshot showing the new text. If you run into trouble, you're welcome to ask for help here.

**Comment by hairlessbear** [comment]
I got this, I'll push the PR momentarily.
