### ISSUE TITLE
make costume option more noticeable and understandable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5204]
A surprising number of users (and not just new users) don't realise that they can use the equipment costume option to wear one set of gear while still using their best stats-giving gear. We see a comment in the Tavern at least once a month from a user who doesn't know that, and there's bound to be others who never post about it.

When you aren't using the costume option, there's a lot of blank space on that side of the equipment page. Perhaps we could have a message there explaining what the costume is for? @lemoness what do you think?

![screen shot 2015-05-14 at 1 47 05 pm](https://cloud.githubusercontent.com/assets/1495809/7629226/4369e744-fa6e-11e4-82fb-289383c98235.png)

**Comment by deilann** [comment]
Yeah. We've got users who have been on the site over a year who don't
understand it (or know that it exists).

At the very least, it'd be nice to have a link to the wiki page on the
costume feature.

**Comment by lemoness** [comment]
"Click "Use Costume" if you want to wear equipment that does not affect
your stats!

For example, you can wear lower-level equipment as a Costume, and
higher-level equipment as Battle Gear. The higher-level equipment in Battle
Gear will affect your stats, and the lower-level Costume will display on
your avatar."

Not totally happy with it, so feedback is welcome.

**Comment by SabreCat** [comment]
Do we have a Justin visit on the Gear page? If everybody got a quick explanation the first (or next, for those who've been there already) time they visit, we wouldn't need a bunch of clunky help text sitting around.

**Comment by AnitaYCheng** [comment]
Honestly...I still don't understand it either. `hides under table` I think it's because I'm not sure what "costume" entails. I thought what I was wearing was my costume!  @lemoness's explanation clears it up a little for me. But it's still unclear as to what selecting "Use Costume" is going to do.

When I've clicked on it before, it's removed everything I was wearing, so I just don't touch it and haven't experimented with it further. I definitely will now, now that we're talking about it. :smile:

**Comment by deilann** [comment]
Is your Battle Gear not snazzy enough for day-to-day Habit interactions?
Are you feeling locked into one look by Ultimate Gear? Click "Use Costume"
and you can set what your avatar looks like in the header and your profile
apart from what you equip for stats. (more info -- click thing like where
we show the extra CDS info)

Once you click "Use Costume" your avatar will look pretty basic... but
don't worry! If you look on the left, you'll see that your Battle Gear is
still equipped. Next, you can make things fancy! Anything you equip on the
right won't affect your stats, but can make you look super awesome. Try out
different combos, mixing sets, and coordinating your Costume with your
pets, mounts, and backgrounds.

This means that you can equip for the best stats on the left, and dress up
your avatar with your equipment on the right. Got more questions? Check out
the Costume page on the wiki. Find the perfect ensemble? Show it off in the
Costume Carnival guild or brag in the Tavern!

**Comment by Alys** [comment]
@SabreCat We can't rely on people reading or remembering the Justins, especially if the Justin teaches them several things at the same time.

**Comment by SabreCat** [comment]
@Alys: True, though I was thinking of it as a single-topic one, not part of a longer tour.

Maybe a Justin display on first visit, then a ? bubble to fold out some help text? Or help text you can acknowledge and put away? Static help text all over the place starts to get to be a nuisance after a while.

**Comment by Alys** [comment]
I believe that if people don't notice or think to click on the "use costume" option, then they're unlikely to notice or think to click on a "?" icon. 

Too many Justins could also become a nuisance and we don't want to "train" the users to close Justins without reading them because they're seeing too many of them.

Can we start with static text and then in a couple of weeks, if we're finding it annoying, then put in something to allow us to hide it?

**Comment by Alys** [comment]
Current stats for usage of the costume option, counting all users who created their account more than 60 days ago and logged in within the past 30 days (i.e., established, returning users):

{ "_id" : { "preferences_costume" : false }, "count" : 11418 }
{ "_id" : { "preferences_costume" : true }, "count" : 12923 }
{ "_id" : { "preferences_costume" : null }, "count" : 18774 }

About 30% are using a costume.

**Comment by hairlessbear** [comment]
What about a message/link on the avatar customization page? For users who only buy the standard class gear, they may never go to the equipment page, since each upgraded piece of gear is auto-equipped. But, if they want to visually alter their avatar, they will go to the avatar customization page no matter what, so I think some sort of mention/link about the costume option would be appropriate there.

**Comment by hairlessbear** [comment]
I also agree with @Alys that a question mark won't help. Currently, the "Costume" title has a popover that says "_If you prefer the look of other gear to what you have equipped, check the "Use Costume" box to visually don a costume while wearing your battle gear underneath._" If questions are still be asked with that available, I doubt a question mark will make a substantial difference.

**Comment by lemoness** [comment]
Tweaked version of Ryan's text:

Click "Use Costume" to equip items to your avatar without affecting the
stats from your Battle Gear! This means that you can equip for the best
stats on the left, and dress up
your avatar with your equipment on the right.

[More Info]

Once you click "Use Costume" your avatar will look pretty basic... but
don't worry! If you look on the left, you'll see that your Battle Gear is
still equipped. Next, you can make things fancy! Anything you equip on the
right won't affect your stats, but can make you look super awesome. Try out
different combos, mixing sets, and coordinating your Costume with your
pets, mounts, and backgrounds.

Got more questions? Check out
the [Costume page] on the wiki. Find the perfect ensemble? Show it off in
the
[Costume Carnival guild] or brag in the Tavern!

**Comment by Alys** [comment]
Current stats for usage of the costume option, counting all users who created their account more than 60 days ago and logged in within the past 30 days (i.e., established, returning users):

{ "_id" : { "preferences_costume" : false }, "count" : 11100 }
{ "_id" : { "preferences_costume" : true }, "count" : 13112 }
{ "_id" : { "preferences_costume" : null }, "count" : 18595 }

30% use a costume

See also the [results above](https://github.com/HabitRPG/habitrpg/issues/5204#issuecomment-102745617) from about six weeks ago.

**Comment by Alys** [comment]
{ "_id" : { "preferences_costume" : false }, "count" : 11689 }
{ "_id" : { "preferences_costume" : true }, "count" : 13853 }
{ "_id" : { "preferences_costume" : null }, "count" : 20553 }

30% still use a costume - no change. Let's pretend this was worthwhile anyway. :-/

**Comment by hairlessbear** [comment]
I still think the issue (if there is one) is that many users never visit the equipment page, so they aren't aware of the costume option. The best solution I can think of is a link on the Avatar page. This makes sense to me because the Avatar page is where you go to modify every aspect of your character's appearance other than the equipment. Some mention of the equipment page and the costume option might help.

**Comment by Alys** [comment]
@hairlessbear Fair point, and I remember you did say that before. @lemoness Any comments about adding something to the Avatar page about equipment/costumes?

**Comment by hairlessbear** [comment]
To be fair, the suggestion is mostly based on my own confusion. There was a very long period where I kept going to the Avatar page to change my costume. I could be wrong, but I suspect other users may have the same intuition that I did (i.e., expecting all of the avatar options to be on the same page), leading them to not seek avatar customization settings anywhere else.

**Comment by crookedneighbor** [comment]
@hairlessbear I think that's a common thing.

**Comment by lemoness** [comment]
I think that is a very good idea!

Something simple, along the lines of:
"To change your avatar's equipment or use a costume, go to the [Equipment
Page](link)!"

Eventually we will probably be reorganizing the way this is handled to make
things easier, but this is a good solution for the interim.
