### ISSUE TITLE
Visiting Inbox Via Email Alerts Does Not Clear PM Notifs

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5205]
When a user receives a PM, an email is sent out. That email has a direct link to the user's inbox.

However, if the user uses that link to check the PM, it does not get rid of the PM notification. In order to do that, the user has to leave their inbox, then click on the PM notification.

Preferably, the notifications would drop to 0 upon visiting the inbox via direct link, such as from email.
##

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This is no longer applicable, so I'm closing this ticket.
