### ISSUE TITLE
Healer armour description doesn't work 

### ISSUE THREAD

**Issue by NandinVJ** [HabitRPG/habitica#5206]
Hello, I found that the description for the healer robes doesn't work, and says to report the error.
Only happens with the robe, the weapon, shield and head are ok.
I'm using google Chrome in a Windows 8.1 
Sorry for my bad english.
![error healer clothes](https://cloud.githubusercontent.com/assets/11577848/7630704/0a3755d6-fa39-11e4-9213-98b64c443bff.png)

**Comment by NandinVJ** [comment]
BTW seems that the last two tiers the description of the robes are correct

**Comment by deilann** [comment]
Thanks for letting us know!
