### ISSUE TITLE
sellForGold line isn't nice with eggs and potions

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5209]
sellForGold line in npc.json is used to Form a phrase of the merchant `Sell Basic Cake for 1 Gold?` and comprises two variables: `Sell <%= item %> for <%= gold %> Gold`

However in case of Eggs and Potions only their type is considered as item. In case of an Egg it may be not so misleading: `Sell Bear Cub for 3 Gold` instead of `Sell Bear Cub Egg for 3 Gold`. But in case of potion it turns into mysterious `Sell White for 3 Gold`; `Sell Base for 3 Gold` or `Sell Desert for 3 Gold` or `Sell Shade for 3 Gold` but of course my favorite - is trading liquid Zombies and Skeletons ))

**Comment by ghost** [comment]
An easy fix would be adding an env.t inside a variable of another env.t - but I don't believe actually that a thing like the following one will work for [inventory.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/inventory/inventory.jade) (changed parts marked with __ from both sides):

`button.btn.btn-primary(ng-show='selectedEgg', ng-click='sellInventory()')`
`=env.t('sellForGold', {item: "__=env.t("egg", {eggType: "{{selectedEgg.text()}}__"})", gold: "{{selectedEgg.value}}"})`
`button.btn.btn-primary(ng-show='selectedPotion', ng-click='sellInventory()')`
`=env.t('sellForGold', {item: "__=env.t("potion", {potionType: "{{selectedPotion.text()}}"})__", gold: "{{selectedPotion.value}}"})`

Any suggestions would be appreciated!

**Comment by ghost** [comment]
I can't find another way to have one and the same line returning a translated version of Egg/Potion inside it.
It seems I'll have to create two new lines for the purpose of fixing this one:

`sellForGoldEgg : "Sell {{selectedEgg.text()}} Egg for {{selectedEgg.value}} Gold"`
and
`sellForGoldPotion : "Sell {{selectedPotion.text()}} Potion for {{selectedPotion.value}} Gold"`

and keep the line
`sellForGold : "Sell {{selectedFood.text()}} for {{selectedFood.value}} Gold"`
only for food

I'll make a commit tomorrow if nobody helps me by coming up with a more elegant solution

**Comment by crookedneighbor** [comment]
I feel like I've dealt with this before, so hold off working on it. I'll take a look.

**Comment by crookedneighbor** [comment]
After fiddling with it for a while, I think your three strings solution makes the most sense. Though, I would name them `sellEggForGold` and `sellPotionForGold`. We can keep the food one as `sellForGold` because it can be reused for things in the future that don't have a qualifier.

**Comment by ghost** [comment]
Oh, I've come across an old bug that I wanted to report separately. But it can become more obvious with the changes suggested:
The button.btn.btn-primary may exceed the limits of the popover for some languages.
Screenshot as it is now, before the suggested changes for Russian:
![Screenshot](http://i.snag.gy/WJStg.jpg)
I guess the popover should be made wide like the ones used for time travelers or the seasonal shop.
I will try to look into this in some hours.

Edit:
The popover is inside a table in inventory jade:
`.row-fluid`
`table.npc_alex_container`
`tr`
`td`
`.pull-left(class="#{env.worldDmg.market ? 'npc_alex_broken' : 'npc_alex'}")`
`td`
`.popover.static-popover.fade.right.in`

And I can't seem to find a way to make it wider yet, unfortunately...

**Comment by hairlessbear** [comment]
@GitHubSphinx I think that should be a separate issue, because it affects all strings, not just ones in other languages. I'll create the ticket now.

**Comment by ghost** [comment]
Closed in favor of the new issue. Thanks @hairlessbear
