### ISSUE TITLE
TypeError: Cannot read property 'members' of null

### ISSUE THREAD

**Issue by tfksilent** [HabitRPG/habitica#5211]
GET /js/controllers/groupsCtrl.js 304 1.482 ms - -
GET /js/controllers/inventoryCtrl.js 304 2.046 ms - -
GET /js/controllers/footerCtrl.js 304 1.617 ms - -
GET /js/controllers/challengesCtrl.js 304 1.798 ms - -
GET /js/controllers/hallCtrl.js 304 1.598 ms - -
POST /api/v2/groups/undefined/chat/seen 200 61.170 ms - 2
POST /api/v2/user/batch-update?_v=4&data=1431656755830&siteVersion=1 200 125.078 ms - -
error: TypeError: Cannot read property 'members' of null

at Promise.<anonymous> (/data/habitrpg/website/src/controllers/groups.js:141:35)
    at Promise.<anonymous> (/data/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/data/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/data/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/data/habitrpg/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (/data/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/data/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/data/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Immediate.cb (/data/habitrpg/node_modules/mongoose/lib/query.js:1153:30)
    at Immediate._onImmediate (/data/habitrpg/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback](timers.js:358:17)

originalUrl: /api/v2/groups/party

auth: 050f9013-f2d7-46fd-afe4-1d3bae67f40d | e616adf9-b046-402b-868d-ca5179985a83

headers: {"host":"10.14.22.69:3000","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0.1) Gecko/20100101 Firefox/4.0.1","accept":"application/json, text/plain, _/_","accept-language":"en-us,en;q=0.5","accept-encoding":"gzip, deflate","accept-charset":"ISO-8859-1,utf-8;q=0.7,*;q=0.7","keep-alive":"115","connection":"keep-alive","x-api-user":"050f9013-f2d7-46fd-afe4-1d3bae67f40d","x-api-key":"e616adf9-b046-402b-868d-ca5179985a83","referer":"http://10.14.22.69:3000/","cookie":"connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%7D%2C%22userId%22%3A%22050f9013-f2d7-46fd-afe4-1d3bae67f40d%22%7D.MZZrl8bAfYs%2BkOzI4Tw1cD9CZtgagBnQw1NyVNkRGiE; __atuvc=2%7C19; __atuvs=55555933b30251e9000","if-none-match":"W/\"35-345803290\""}

body: {}
GET /api/v2/groups/party 500 48.096 ms - 53
GET /common/dist/sprites/spritesmith4.png 304 13.549 ms - -
GET /common/dist/sprites/spritesmith3.png 304 31.417 ms - -
GET /common/dist/sprites/spritesmith1.png 304 30.663 ms - -
GET /common/dist/sprites/spritesmith2.png 304 28.880 ms - -
GET /common/dist/sprites/spritesmith0.png 304 27.723 ms - -
GET /bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff 304 1.360 ms - -
[Fri May 15 2015 09:26:07 GMT+0700 (WIB)] [worker:1508] kill timeout, exit now.
[nodemon] app crashed - waiting for file changes before starting...

**Comment by tfksilent** [comment]
please help me for this case i think in this case for coding json ?

**Comment by crookedneighbor** [comment]
@tfksilent Can you give us more information about this? Are you having trouble with your local install?

**Comment by tfksilent** [comment]
@crookedneighbor 

yes i have install on locall  in UNIX  this is my source http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally

i have success in step 12 and step 12 then in step 12 run habbit 

i meet the problem ?

thank you if you can help me

**Comment by tfksilent** [comment]
@crookedneighbor
wht u need information mr , i can provide ?

**Comment by tfksilent** [comment]
i have clone fix and same this is branch https://github.com/HabitRPG/habitrpg

**Comment by tfksilent** [comment]
![1](https://cloud.githubusercontent.com/assets/12293487/7646467/39ebd198-faee-11e4-89c4-560ba9e03efc.PNG)

this is ui information if eror

**Comment by tfksilent** [comment]
![capture2](https://cloud.githubusercontent.com/assets/12293487/7646484/6bd060fc-faee-11e4-8430-d954dfb98c53.PNG)

this is information eror message in server

**Comment by crookedneighbor** [comment]
This was just fixed. Best guess is that you don't have the most up to date version of the code. 

Is [there a reason you eliminated the git history and started a new repo](https://github.com/tfksilent/habitrpg) instead of [forking HabitRPG's](https://help.github.com/articles/fork-a-repo/)? Doing so will make it harder to pull in the latest commits.

**Comment by tfksilent** [comment]
ok in can try for you advice thanks a lot

**Comment by tfksilent** [comment]
this problem solve just fork in my repo and upto date 

@crookedneighbor  thank you for helping :+1:

**Comment by GitHubSphinx** [comment]
And for this particular reason I had to install python first and MS Visual Studio then - as a walk-around... )
