### ISSUE TITLE
I died while being in a tavern AND dailies don't reset

### ISSUE THREAD

**Issue by Ventsel** [HabitRPG/habitica#5214]
Hi! Used ID 9d7352a2-d6dc-4dd4-93a3-ebca470190d5 here.

I checked in the tavern yesterday, and today when I logged in, I was dead AND I was not in the tavern. And on top on it my dailies did not reset. 

I am in a party of two on a boss quest. However, my only other party member is my family, we both are on vacation now and so we both checked in the tavern yesterday. It worked as it should for him - he still is in the tavern today and just got some damage from my unchecked dailies. His dailies are reset, too.

To put it in order: I did some dailies, including one with critical hit. I checked in the tavern. 
Next day: I am dead. I am not in the tavern. My dailies didn't reset. I didn't deal any damage to the boss.

So... I got damage as if I wasn't in the Tavern. My dailies didn't reset as if I was in the Tavern - an old tavern, that is, before in update, should not dailies reset in the Tavern too?

Please, fix it. I can live with a fake death (though it was a nasty surprise), but being "kicked out" of the Tavern AND dailies not reset makes using HabitRPG difficult...
##

**Comment by Alys** [comment]
You were probably hit by [this bug](https://github.com/HabitRPG/habitrpg/issues/4313) and/or by a [sync error](http://habitrpg.wikia.com/wiki/Sync_Errors) when you checked into the Inn. There's information in the "Advice" section near the top of the former link to help you recover from the damage, and the latter link has some advice about how to ensure that you really are Resting in the Inn (see the "How to Minimize Sync Errors" section, but in brief, reload the page and check that you are still Resting, or use the Data -> Data Display Tool which will confirm if you are Resting).

**Comment by deilann** [comment]
We were also having server issues last night, so that could have caused the
sync error.

**Comment by justicar347** [comment]
ID: 7f4483a2-b6b1-434f-82b1-899927234c98

Hello, I have had similar problem. I just died while resting in the inn. I went in a few days ago and was about to check out and discovered that I have died. I did not have any checked dailies and was not fighting a boss. I checked to see if I was synced and it looks like I am.

**Comment by Alys** [comment]
Habitica's code has been changed significantly since this was logged, including changes to avoid the bug I linked to above, so I'm closing this now. If it reoccurs, we can reopen or create a new issue.
