### ISSUE TITLE
Visual indicator in header of active quest?

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica#5215]
The only way to see if your party is in a quest, is to check the party chat page. I accept every quest I'm offered, but they often don't start for a while. And I sometimes forget to check the chat to see when the quest leader announces when they're going to start the quest. (And I'm sure some quest leaders don't announce at all, meaning one has to check the party chat to see if the quest is active, or finally notice when they take more damage than usual....which is what happened to me oops!)

It would be great if there was some kind of indicator in the header that a quest is active, so players could either be more diligent about doing their dailies, or cast some spells. I tend to save my mana for quests, and definitely would have cast a few spells to protect my party (as well as myself), had I noticed the quest was on!

Since the party members avatars and backgrounds will all look different, how about adding a highlighted border around the progress bars? A quick mockup here:

![habitrpg](https://cloud.githubusercontent.com/assets/6760632/7656895/7e8862aa-fae2-11e4-99a6-5d07cd8d2a9c.png)
##

**Comment by lemoness** [comment]
We've had some requests on Trello to make the boss itself easily visible
from the front page.

Some quotes:

"I love the boss fights but when I'm on my tasks screen there is no
indication that I'm in a fight. Would there be a way to add the boss in
your party/status bar and some basic info of the fight?"

"I'd love to see a summary of the Quest Progress / Boss Fight up in the
main party status area. Showing the boss icon and progress aligned to the
right along side the party members (you could put a "vs" or other divider
between) would show progress at a glance, and give more of a feeling of
participation. Having to leave the main Tasks screen to check Quest
progress makes me less engaged with the Quest."

Not sure how we would accomplish that without cluttering the screen
unnecessarily, though :/

**Comment by deilann** [comment]
Do you have email alerts turned off? You might want to turn them on. I'm
not saying your suggestions might not help, but email alerts will send you
a message once a quest has started.

**Comment by Alys** [comment]
I'm certainly not against a quest indicator on the tasks page, but I think it needs to be less subtle than a highlighted border. We'd get endless questions about what the border means. :) It should be an indicator that is obvious at a glance because of those players who don't read the tutorials and hints.

Personally, I like the idea of seeing the quest boss on the tasks page because the artwork is usually very attractive, but I agree that clutter needs to be considered.

**Comment by deilann** [comment]
What if the boss were put in your header just to the left of your
party-mates with special sized down art made to be the size and shape of
one of your party-mates?

**Comment by AnitaYCheng** [comment]
@deilann The party bar is already populated with colorful party mates, so what @Alys mentioned re: subtlety may come into play. It's a good idea, I'm just afraid many people simply won't notice, because it isn't too out of place compared to what's usually there.

How about putting the top half of the quest boss image in the nav bar header, where Bailey is? It's an unusual enough spot that I think most people would notice (presumably, they notice Bailey there), and a hover could reveal the progress of the quest. That's all the info someone needs on a consistent basis. If they want to see more detailed info, that would remind them to check the party chat.

Another quick mockup:
![activequest](https://cloud.githubusercontent.com/assets/6760632/7663797/3a7d87a4-fb26-11e4-95cc-62363a4aca46.png)

**Comment by deilann** [comment]
ooooh, I like that

**Comment by crookedneighbor** [comment]
Me too!

**Comment by lemoness** [comment]
That looks great!

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer be relevant afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
We're open to considering a feature like this in the future, but Github is really more of a place for bugs and new features that have a roadmap for implementation, rather than feature requests, so I'm closing this for now.
