### ISSUE TITLE
All due dailies complete but no perfect day

### ISSUE THREAD

**Issue by benkc** [HabitRPG/habitica#5216]
Last night (2015-05-14) I completed all of my due dailies, but this morning I do not have a perfect day buff.

The data display tool is a bit confusing, and I'm not sure if this is because of my custom cron time (3 AM local, which is UTC-10 if I'm mathing right), or related to this bug, but I think the latter.  It shows 2015-05-13 as having all dailies completed or "gray" (dash), but iIt shows 2015-05-14 as having all dailies gray.

Given that 2015-05-12 does show one of my "weeklies" checked that I did indeed do on the 12th, it looks like it is indeed labelling the days as I'd expect, and so my 2015-05-14 day was considered "all dailies gray" even though I had 14-15 active dailies completed.

Oh, and this is interesting: I'm pretty sure that I added a new daily after midnight and before my local cron time, and checked it off.  This morning, it's not even in my task list!  I also believe I edited one of my old dailies' description, and it does not have the updated description.  (I was splitting one daily into two.)  The old, edited (but-edits-lost) daily has lost the streak bonus, and shows _two_ entries for today in the "progress" graph on the tasks page, both with the same value (decreased from yesterday).

UUID: 08e9920c-64d6-4537-a9ef-29e900eb7045
Browser: whatsmybrowser.org/b/MZLWLS1

I use the browser interface almost exclusively, but I may have fired up the mobile app at some point recently just to trigger my cron or look at things.  That might also be relevant?

**Comment by Alys** [comment]
I'm very sorry but it looks like you were hit by [this bug](https://github.com/HabitRPG/habitrpg/issues/4313). That would explain the inconsistent handling of your completed Dailies and the missing edits. There's an Advice section near the top of the page that will help you recover from the unfair damage.

**Comment by benkc** [comment]
Thanks.  I normally hit reload a lot, but I think I haven't been as much recently.  I'll go back to doing that!

I _think_ I didn't actually take damage, just missed out on perfect day (and maybe drops).  I can't be sure though.

I'll close this and make a brief comment over there just in case my data is at all useful. :)
