### ISSUE TITLE
No sample dailies when registering from Germany

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#5217]
I heard/read that directly after creating a new HabitRPG account, there are usually some sample dailies in your dailies list. (I don't remember if there were any when I first registered.) However, when you register from Germany (locale + language set to Germany, HabitRPG login website automatically appears in German), there are no such sample dailies.

I'd never have noticed that on my own, and if I had, it wouldn't have bothered me. But one of the German wiki scribes noticed it while trying to find out what those beginner dailies look like in the German version, and remarked on it in the "Wizards of the Wiki" guild. A few days later I made a second account for completely different reasons, and used that occasion to confirm that, indeed, in the German version the dailies are missing. And then @Alys asked me to please write the bug report. :)

I didn't do any experiments for various cases. (For example, I didn't try to first switch the login webpage to English, and then register and see if the settings then start in English and the dailies exist.) I just went to the website and registered. I used a laptop, not a mobile.

**Comment by deilann** [comment]
When my friend signed up recently, there weren't sample dailies anymore.

In fact, there were no sample tasks at all.

The tutorial gave some ideas of what to add, though.

I don't think this is a bug -- I think this is one of the tutorial setups
we're testing. @Lemoness can you confirm?

**Comment by habitrpguser** [comment]
Ok, now I did do the testing (made an English and a German test account - and deleted them afterwards). Comparison shows that they behave in exactly the same way, everything is as it should be, there are no sample dailies in either version (but the tutorial suggests some), and there are three generic habits in both versions (good, bad, and ~~ugly~~ plus/minus) with examples for each noted in the Extra Notes. No bug or inconsistency or bad translation at all. I'm sorry about having made this bug report (which can probably be closed now) and will tell the wiki scribe in question.

**Comment by Alys** [comment]
@habitrpguser Thanks for letting us know! No need for an apology - I also didn't realise there were no longer any sample Dailies, and I should have been keeping myself up to date with it. :)

**Comment by lemoness** [comment]
Sorry for the confusion, guys - the tutorial and sample tasks are all in
flux, right now, so the parts of the wiki describing it may be out of date.
