### ISSUE TITLE
Challenge Page DEMANDS that I reload. Forever.

### ISSUE THREAD

**Issue by ReyasWI** [HabitRPG/habitica#5219]
When I go to the challenge page I get this:  
Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33722281 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

UserID:  
f27f9821-e1b8-4d4a-9aab-175d93c4b5ae

Browser Stuff:  
whatsmybrowser.org/b/FHQ2KH1

Log outputs:

Failed to load resource https://platform.twitter.com/widgets.js
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://habitrpg.com/api/v2/challenges
Object
config: Object
data: Object
headers: function (c){if(!b)b=sc(a);if(c){var d=b[g(c)];if(d===void 0){d=null}return d}return b}
status: 500
statusText: "Internal Server Error"
**proto**: Object
 app-c9d8e338.js:39
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping:1
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://habitrpg.com/api/v2/challenges
Object
config: Object
data: Object
headers: function (c){if(!b)b=sc(a);if(c){var d=b[g(c)];if(d===void 0){d=null}return d}return b}
status: 500
statusText: "Internal Server Error"
**proto**: Object
 app-c9d8e338.js:39

**Comment by deilann** [comment]
These errors happen intermittently. If you are still experiencing this in
24 hours, please let us know.

**Comment by crookedneighbor** [comment]
@ReyasWI If you're still experiencing this issue, please re-open this.
