### ISSUE TITLE
Different stats in Android app and on web

### ISSUE THREAD

**Issue by csalee15** [HabitRPG/habitica#5222]
When I look at my stats in the Android app, they're different than they are on the web version.  I don't think it's a sync issue, since they've been mismatched for two days now and everything else (tasks, gold, experience, etc.) seems to be synced perfectly.  

So, for example, on the Android app my strength is listed as 1.5, whereas on the web version it's listed as 2.  I'm using the latest version of the Android app.  

Here's my app screenshot:
![habitrpg_android1](https://cloud.githubusercontent.com/assets/3800929/7666371/e6892d52-fbb0-11e4-9b16-597cbaa3b97f.png)

And here's my web screenshot:
![habitrpg_web](https://cloud.githubusercontent.com/assets/3800929/7666355/5a72f654-fbb0-11e4-9988-9294ff4f0fed.jpg)

Why the 0.5 difference in all my stats?  New to HabitRPG and love it so far, just curious about the stats mismatch.

User ID: d71f3536-2e21-430e-9bb6-e7a46f8dd424
whatsmybrowser.org/b/SRMX3Z5

**Comment by deilann** [comment]
We fixed a display error on the website, but it hasn't been added to the
mobile app yet.

For future reference, whenever there is a discrepancy between the site and
the mobile app, the website is the one that is correct. It can take quite
some time for updates to be pushed through for the mobile apps.

**Comment by csalee15** [comment]
Thanks for the quick response!  One followup question: does the mobile app use these incorrect stat values in making its calculations?  For example, say I mark a task as finished using the mobile app, and I get a critical hit.  Is my bonus calculated using the mobile app's incorrect strength value, or the website's correct strength value?

**Comment by deilann** [comment]
The local info may show up wrong until a sync happens, but the server-side
calculations are where all that's stored, so it'll be the stats from the
website.

**Comment by Alys** [comment]
I'm closing this because it's a cosmetic problem rather than one that affects your stats and progression through the game, and also because we are working on a new, native app for Android which will be an improvement over the current one. It's not finished yet but is close.
