### ISSUE TITLE
In the Tavern, checked dailies after midnight, didn't reset the next day

### ISSUE THREAD

**Issue by alestanis** [HabitRPG/habitica#5226]
Hi,

User id: c5a8c2cc-5a4e-4526-abdc-a33b0fbbddc5

I checked in the Tavern after the dailies resetting feature was added (thanks a lot!). 
The first nights, everything worked like a charm but yesterday I checked my dailies after midnight (I have a custom con time to 2am).

This morning, my dailies were not reset.

**Comment by Alys** [comment]
When you say you "checked your Dailies after midnight" do you mean that you marked them as completed after midnight, or do you mean that you looked at your Dailies after midnight to confirm that they were marked as completed and you saw that they were? Sorry about this but "checked" can have both meanings and I want to be sure which one is correct here.

Were _all_ your Dailies not reset or just some of them? For the ones that weren't reset, did you untick them yourself this morning?

**Comment by alestanis** [comment]
I marked them as checked after midnight. This morning I manually unchecked
them, then reset my experience, money and mana values and reset my streaks.

**Comment by alestanis** [comment]
Oh, and this morning they were exactly as yesterday night. The ones I had
checked were checked and the ones I had not checked were unchecked.

**Comment by TheresaVestal** [comment]
I checked into the inn yesterday and checked off some stuff before midnight. This morning the dailies have not reset. Do I need to reset everything manually? Also if I reset it manually while I am still in the inn will I need to reset my streaks? I did try refreshing the page with no effect.

**Comment by TheresaVestal** [comment]
Also if I reset it manually while I am still in the inn will I need to reset my streaks?

**Comment by Alys** [comment]
@TheresaVestal Were all your Dailies not reset or just some of them? 

It's up to you whether you reset them manually or not. It's very likely that they will become reset automatically tomorrow night. 

Whenever you untick a Daily (whether you are Resting or not), the streak always decreases by one, so if you do reset them manually, you might also want to increase the streaks manually.

**Comment by TheresaVestal** [comment]
It looks like none were reset.

**Comment by Alys** [comment]
We've made some changes to Resting in the Inn and cron since this was reported so I'm closing it now, but please tell us if it happens again.
