### ISSUE TITLE
Ethereal Surge splits mana deduction into two parts

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5228]
![etereal surge split](https://cloud.githubusercontent.com/assets/7059890/7670601/a3f1f6e0-fc78-11e4-93d0-da37d9e5cd7e.jpg)

This doesn't occur with any other Mage spells, and I haven't tested it with any other classes.

**Comment by hairlessbear** [comment]
I just finished testing on my local copy with every spell from every class, and Ethereal Surge is the only one that exhibits this behavior. 

Also, the split values vary. If using Ethereal Surge without logging out or making any other major changes, the split values stays consistent. But anytime major changes are made (e.g., change class, log out then back in), the split values can change. But even though they change, the split always occurs like the screenshot above shows (i.e., -`value1` MP, "You cast Ethereal Surge for the party.", -`value2` MP).

**Comment by Alys** [comment]
The split changes depending on your INT. One notification shows how much MP the skill gives (to the other party members, not to you), and that MP depends on your INT. The other notification shows the remaining amount that you spent.

FYI, the two notifications were made to appear at the same time in https://github.com/HabitRPG/habitrpg/pull/4919 (previously, one would appear first, and then the other after a sync occurred).

**Comment by hairlessbear** [comment]
Huh. The current implementation doesn't make that clear at all. The two notifications are styled identically and give no indication that they're referring to two different things. I still can't tell which value is which.

I think it would be much better if one notification was the expected `-30 MP`, and the other was something like "Your party gains <value> MP!"

**Comment by Alys** [comment]
Yes, it would be better if it gave a single notification of "-30 MP". If you can work out how to make that happen, please do a PR. I don't think we should have a second notification saying that your party gains MP, because that's the point of the skill and we don't have those notifications for any other party skill.

**Comment by hairlessbear** [comment]
I'll try to figure it out. I'm unfamiliar with any of the spells code though, so it may not happen anytime soon.

**Comment by Alys** [comment]
No hurry!
https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content.coffee#L523
https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content.coffee#L543

**Comment by hairlessbear** [comment]
Thanks! I actually found that on my own; the code I was looking for was the code that actually runs the spells. I think I found it though; it's a combination of [this](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/rootCtrl.js#L244-285) and [this](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/user.js#L341-410), right? The thing I'm still having trouble locating is where the `-<value> MP` notification is. I know that the `you cast X` notification is [here](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/rootCtrl.js#L274-281), but I haven't found the other notification yet.

**Comment by Alys** [comment]
There's a thing that watches the value of your MP and sends a notification whenever it changes:
https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/notificationCtrl.js#L44

**Comment by hairlessbear** [comment]
@Alys have I told you you're wonderful recently? Because you definitely are :smile:. Thank you! I didn't realize that's how some of the notifications work; that probably would've taken me a while to find on my own.

**Comment by Alys** [comment]
You may show me exactly how wonderful you think I am by documenting that somewhere on the wiki. ;)
