### ISSUE TITLE
New quest modal pops up before notification of old quest completion

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica#5229]
My party is extremely quest-happy as of late, and someone offered a new quest immediately after we defeated the previous boss, when I wasn't online. Due to the order of notification priority (I presume), the alert for a new quest invitation popped up before "You've defeated X boss!" modal. Once I accepted the new quest, the "You've defeated X boss!" modal was underneath. 

To minimize confusion, I propose the "You've defeated X boss!" modal take precedence over the new quest notification.

**Comment by hairlessbear** [comment]
This was fixed in #5298; would someone mind closing it?
