### ISSUE TITLE
API Not working, returning HTML.

### ISSUE THREAD

**Issue by NotChrisPlease** [HabitRPG/habitica#523]
The API has not been working for me, It just returns HTML when I call it.
I'm using Python with urllib2.

**Comment by lefnire** [comment]
What's the html you see? Is it the splash page?

**Comment by NotChrisPlease** [comment]
@lefnire Looks like it,

**Comment by switz** [comment]
This should be moot in a matter of hours. The new api middleware is ahead of the splash middleware, so we shouldn't run into this issue again. Follow here for updates: https://github.com/lefnire/habitrpg/pull/522

**Comment by NotChrisPlease** [comment]
@switz Alright I'll do that.
