### ISSUE TITLE
Allow Habits and To-Dos to "age" while Resting in the Inn

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5232]
When you are **not** Resting in the Inn, each time cron runs, it makes uncompleted To-Dos more red and it adjust plus-only and minus-only Habits to move towards yellow.

We would like the same thing happen when you are Resting. 

Ref: https://github.com/HabitRPG/habitrpg/pull/5073#issuecomment-97277606 with approval from Lemoness at the bottom of that issue.

_edit by Alys 2017-10-22:_
When this is implemented, the wording on the banner from https://github.com/HabitRPG/habitica/issues/9188 will need to be changed. Either change it on the website as part of the fix for this issue if https://github.com/HabitRPG/habitica/issues/9188 has already been completed, or put a comment in https://github.com/HabitRPG/habitica/issues/9188 to say that the wording needs to change.

_edit by Alys 2018-08-02:_
Habit counters should also reset when resting.

**Comment by ModernHedonist** [comment]
I agree

**Comment by librarianmage** [comment]
I can work on this!

**Comment by Alys** [comment]
Sorry we didn't reply earlier, @MathWhiz! Are you still interested in working on this?

**Comment by Alys** [comment]
Sorry we didn't reply earlier, @MathWhiz !

**Comment by librarianmage** [comment]
I think I'll keep it open for another user right now.

**Comment by Alys** [comment]
No worries! 

Labels updated.

**Comment by Alys** [comment]
When this is implemented, the wording on the banner from https://github.com/HabitRPG/habitica/issues/9188 will need to be changed. Either change it on the website as part of the fix for this issue if https://github.com/HabitRPG/habitica/issues/9188 has already been completed, or put a comment in https://github.com/HabitRPG/habitica/issues/9188 to say that the wording needs to change.

I'm copying this comment to the top post to be sure it's not forgotten.

**Comment by Alys** [comment]
I'm working on this as part of adjusting cron so that the actions performed while resting are handled by the main cron code instead of the `performSleepTasks` function -- https://github.com/HabitRPG/habitica/issues/6941#issuecomment-387927531
