### ISSUE TITLE
MP rounds down, MP alerts round up...

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5233]
It makes sense for MP to round down... if it rounded up, it'd look like you could afford skills you can't.

However, MP alerts round up, which makes for some surprising total amounts of MP now. This is especially apparent because of the 1/4 amounts Habits give you.
##

**Comment by TheHollidayInn** [comment]
Can you give me the steps to replicate this error? I'm not sure what you mean by MP alerts.

If you know, is this an issue with rounding mp in scoring? https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1152-L1156

**Comment by crookedneighbor** [comment]
@TheHollidayInn He means the notifications you get when new mp is received by completing todos, habits, etc (similar to exp or gold gained).

Possibly related to how the rounding is done in the notification itself: https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/notificationServices.js#L79

**Comment by SabreCat** [comment]
Client display issue. Pending for frontend redesign.

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by Alys** [comment]
MP in the stats bar is still being rounded down correctly. MP in the notification you get when completing a task is either rounded or truncated to one decimal place - we'll have to look at the code to see which (I can do that later if no one gets to it first).

**Comment by lemoness** [comment]
That would be very helpful, thanks!

**Comment by Alys** [comment]
MP in the notifications is rounding up/down depending on the exact value being rounded. The correct behaviour is to round down. This is very low priority though.

I've updated the labels.
