### ISSUE TITLE
Issue with Purchasing things with gems

### ISSUE THREAD

**Issue by ladyaynjell** [HabitRPG/habitica#5235]
I purchased all of the new Animal ears set (all 5 gems were taken from my account), however now it is telling me that I do not own all of the items, even though I was just wearing the item it says I do not own.
It wants me to repurchase the Tiger ears for 2 gems.
This is frustrating.

**Comment by Alys** [comment]
To help you, we need to be able to identify your account. On HabitRPG, please go to Help -> Report a Bug where you'll find some instructions. One of those steps describes how to find your "User ID". Please paste the User ID into this issue.

**Comment by ladyaynjell** [comment]
Oh, many apologies

2098f113-af21-469f-a085-b259f45801dd

Here it is

**Comment by Alys** [comment]
Thanks @ladyaynjell 

Could you please go to your tasks page, and look in the Rewards column. Are the Tiger Ears available to buy there for zero gold (and zero gems), in the same place where you buy swords, armour, etc? If they aren't listed there, could you please reload the page and look again?

**Comment by ladyaynjell** [comment]
No, it isn't there to buy under the Rewards column. I even cleared my cache.

**Comment by Alys** [comment]
Sorry about that! You should be able to see the Tiger ears now and put them on for free, from either the Avatar customisation page or your Equipment page.

I'm going to close this now, but definitely reply if it still isn't right and I'll keep helping you!

**Comment by thebat137** [comment]
This just happened to me too.  In my case, I think it may have had something to do with using the Orb of Rebirth recently, possibly combined with the fact that the ears show up both as "Avatar" items and as "Equipment" items.  I repurchased them from the Avatar page (for gems) just to see what would happen, and that seems to have given them back in both places.  Also, putting them on my character in the equipment page puts them on on the avatar page, but not vice versa.  So I think something may be wonky with the logic here.

My userid is dea8a9e8-c084-438a-9a14-7fe96a73fd0a.

**Comment by Alys** [comment]
@thebat137 Before you bought them with gems, were they appearing for sale with gold in the Rewards column?

**Comment by thebat137** [comment]
Alys, I think they were.  I am not 100% sure, though.  Feel free to "take" them from me again if you want me to check.

**Comment by Alys** [comment]
@thebat137 No, it's okay, all our testing showed that they would be available in Rewards, so I won't do that, but thank you for offering. I'm sorry but I'm not sure what problem you're experiencing. Can you tell me exactly what went wrong or what is wrong now?
Also tell me how many gems you spent on them. I'll return the gems to you since you didn't need to spend them.

**Comment by thebat137** [comment]
I spent 5 gems, so, a pittance, really.  But I have a suspicion that what happened is that I bought the ears with gems, used the Orb of Rebirth, and then I didn't "have" them anymore, so the game offered to let me purchase them again in the usual (gem-based) fashion.  As far as I know, the ears are the only item that is both an avatar item and an equipment item, so I'm wondering if they may have responded incorrectly to the Orb's reset?

**Comment by thebat137** [comment]
To be clear, I have the ears again, and they're no longer showing as needing purchase either with gems or gold.  I can put them on and take them off and everything.  The only thing that seems wrong now is that if I put them on from the Avatar screen, they don't show up as being worn when I go to the Equipment screen, but it does seem to work when I do it the other way around.

**Comment by thebat137** [comment]
Oh, no, looks like I'm wrong about that.  I just needed to refresh the page.  When I put them on from the Avatar screen, they go into my "costume" on the Equipment screen.

So, everything is correct now.  It was just the post-Orb repurchase that seems to have been glitched.

**Comment by Alys** [comment]
Thanks for letting us know! I've given you back the gems.

**Comment by thebat137** [comment]
Thanks, Alys.  I'll keep a lookout for future issues with the ears and post here if I have any more problems.
