### ISSUE TITLE
In iOS glitch/issue: When hatching prompt happens twice, for two different pets

### ISSUE THREAD

**Issue by dragonesper** [HabitRPG/habitica#5237]
I've hatched pets twice in the app as of yet and this occurs:

I get prompted twice to hatch two different pets with the hatching potion in use.
Things I've noticed when this happens:
- There's a minor lag
- The app itself has acted slowly at that point

I'm suspecting the cause lies in the lag and is triggered by impatiently tapping to hatch while the lag occurs.

My User ID: 107b260d-4b1e-4603-8d01-8771dae8a365

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
