### ISSUE TITLE
To-Do list multiples and random extra levels

### ISSUE THREAD

**Issue by smadimou** [HabitRPG/habitica#5238]
I just gained 7 levels I was not supposed to have

I also, and more seriously, have my to-do list covered in extra copies of my tasks and they don't delete, nor do they disappear when I complete them.

**Comment by deilann** [comment]
Try deleting the tasks from the bottom up. If that doesn't help you delete
them, let us know.

Also, if you want to go down the 7 levels, you can use Site > Settings and
click on "Fix Character Values"

**Comment by smadimou** [comment]
I managed to refresh, delete one or two, then refresh again to allow a few
more to be deleted.

**Comment by deilann** [comment]
Awesome. Unfortuantely, we're still not entirely sure why tasks are
duplicating for some users.

Have you managed to get all the duplicated tasks sorted out?

**Comment by smadimou** [comment]
Yes, by refreshing, I managed to remove all the extra.  Thank you

**Comment by deilann** [comment]
No problem! I'm closing this now (we have another ticket on duplicating
tasks in general) but if you need more help, feel free to reopen it!
