### ISSUE TITLE
Use of API Token for each user?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#524]
With the API, there may be services that would like to use a HabitRPG's user data.  How will a service grab information if they need an API token for each user AS WELL AS an User Id?  Here is a solution that I propose:

Service has login page
Service sends username and password to server and the response is the user's userId and apiToken (that's it)
Service can then use this info to access API methods?

Please let me know your thoughts (@lefnire @switz)!

P.S. Sorry if this is mentioned/already implemented/not a viable solution.

**Comment by ruddfawcett** [comment]
@switz I understand the use of the header mechanism, and I would not like to falsify that, but I think that a service should send a simple GET or some HTTP request using the user's username and password to get the userId and apiToken of the player.  For a player who likes HabitRPG and isn't ask technologically advanced, this would be a useful feature.

**Comment by switz** [comment]
Oh, you mean to just add another route to obtain the API key. We can definitely add that.

**Comment by ruddfawcett** [comment]
Yep.  Something like a POST to http://habitrpg.com/v2/users/verify with username and password and in return you would get

``` json
{
    "username":"rexfinn",
    "userId":"xxxx-xxxx-xxxx-xxxx",
    "apiToken":"xxxx-xxxx-xxxx-xxxx"
}
```

It would probably be best to POST a hashed password for security.

**Comment by switz** [comment]
Follow this branch: https://github.com/switz/habitrpg/tree/api-auth

**Comment by horusofoz** [comment]
@switz What is the status on this issue?

**Comment by paglias** [comment]
This is implemented now.
