### ISSUE TITLE
"Set a Reminder" Feature in iOS app is Unresponsive

### ISSUE THREAD

**Issue by Luthien22** [HabitRPG/habitica#5241]
Under settings in the iOS app is an option to set a reminder to log in. By default there is no reminder. There's a button you're supposed to press to set a reminder; however, this button is unresponsive.

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
