### ISSUE TITLE
Empty Quest 

### ISSUE THREAD

**Issue by amatoraqua** [HabitRPG/habitica#5242]
A party member started a solo quest, and in trying to cancel it accidentally left the party. Now there are no participants, but the quest has remained even after cron, and it's preventing us from moving on to another quest. 

Group ID: cdaab70e-f844-4baf-beb3-6979afe2c253
User ID: a8007d90-0e78-4ef3-872b-fb94eebfc418
http://whatsmybrowser.org/b/A4EKGVS

**Comment by crookedneighbor** [comment]
I've removed the quest from your party. Please refresh your browser on the party page and report back here if it's not fixed.

**Comment by amatoraqua** [comment]
Thanks! It's all gone.
