### ISSUE TITLE
Incorrect class name in tutorial text after class change

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5245]
I've just switched from a healer to a rogue however during the class tutorial I'm told I'm a warrior. At the end of the tutorial the basic rogue gear was equipped as expected. FWIW, I did choose warrior when I initially unlocked the class system.

I considered reporting this in #5125 but figured those changes might be a while coming whereas this might be a quick fix to be done now.

![screen shot 2015-05-20 at 09 24 14](https://cloud.githubusercontent.com/assets/2931465/7721914/8d38e604-fed3-11e4-9db4-e0cd47a4953d.png)

![screen shot 2015-05-20 at 09 24 32](https://cloud.githubusercontent.com/assets/2931465/7721916/8eafb134-fed3-11e4-999e-2c6a577921a2.png)

**Comment by ghost** [comment]
It seems that the text is using the previous class rather than the new one. When switching back from a rogue to a warrior I see the following:

![screen shot 2015-05-26 at 11 41 35](https://cloud.githubusercontent.com/assets/2931465/7810763/d8f4f7e0-039c-11e5-964b-dd16a50d1073.png)

![screen shot 2015-05-26 at 11 41 51](https://cloud.githubusercontent.com/assets/2931465/7810765/e04f4cf2-039c-11e5-9505-e16c79efebe0.png)

**Comment by Alys** [comment]
This has been reported in https://github.com/HabitRPG/habitrpg/issues/4888

If you'd like to follow the progress of that issue, you can subscribe to notifications using the button in the right-hand column.
