### ISSUE TITLE
Error in badge string processing

### ISSUE THREAD

**Issue by ak84ak** [HabitRPG/habitica#5246]
Error processing string (Ukrainian language localization).
Go to "User" -> "Stats & Achievements" -> Right side of page -> Badge "8 perfect days". Note for badge is: "Error processing string. Please report to http://github.com/HabitRPG/habitrpg". See attached
![s](https://cloud.githubusercontent.com/assets/3965127/7722658/f3a93512-feea-11e4-83f0-81eb2b21eb42.png)
 sreenshot.

**Comment by ghost** [comment]
Thanks for reporting it.
Error in translation (<%= perfects %> has been translated)
Line key perfectText
Unfortunately the line has been reviewed. I've left a comment for the reviewers on Transifex now - they should get a notification and fix the issue.

**Comment by ghost** [comment]
The string has been fixed by @leeder on Thansifex just now. The fix should be online when @paglias updates locales in some days.

**Comment by paglias** [comment]
Locales are being updated now, another few days until we deploy the new version of the production site.
