### ISSUE TITLE
Tools of the Trade does not buff all party members

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#5250]
I've cast Tools of the Trade six times this morning, resulting in a buff for me of 465 according to the data tool - but party members have buffs of 453 (mage), 852 (rogue), 42 (warrior, this includes the perfect day buff) and 426 (mage). 

A similar thing happened the last few days when I spoke TotT.

**Comment by deilann** [comment]
Buffs last until a player crons, so if they cronned at different times, it makes sense that they'd have different buffs. Does that make sense?

**Comment by wildcate** [comment]
We all have cron at midnight (at least me and the un-buffed person) - so
different cron shouldn't be the reason in our case...

2015-05-21 13:27 GMT+02:00 deilann notifications@github.com:

> Buffs last until a player crons, so if they cronned at different times, it
> makes sense that they'd have different buffs. Does that make sense?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5250#issuecomment-104234661.

## 

Katrin Kania: "Kleidung im Mittelalter. Materialien - Konstruktion -
Nähtechnik. Ein Handbuch."
529  S. mit 357 s/w-Abb. und 51 farb. Abb. auf 24  Taf. Böhlau-Verlag Köln
2010.
Preis 67,90 €
ISBN 978-3-412-20482-2

Dr. Katrin Kania M.A.
An der Lauseiche 8
91058 Erlangen

Telefon: 09131-816665
mobil: 0160-91614276
www.pallia.net
Blog (englisch) auf togs-from-bogs.blogspot.com

**Comment by deilann** [comment]
I don't think you quite understand how cron works.

Cron runs the first time someone logs in after their CDS (which for you
would be midnight). Unless you are all signing in at exactly the same time,
your cron will not be simultaneous.

**Comment by deilann** [comment]
So what most likely happened is you cast Tools of the Trade 6 times this
morning, then your warrior logged in, so never got a chance to partake of
the buff. Does that make sense?

**Comment by wildcate** [comment]
Yes, that makes sense... it also means that either me and the other early
bird won't have the effect of a party buff during our day, if I wait for
the late folks, who usually log in in the afternoon/evening, or the
late-comers never get the buff.

I would have supposed that the buff still works for someone logging in
after the spell is cast until their next cron, not until their next login
after the previous cron. Does that make sense?

2015-05-21 14:33 GMT+02:00 deilann notifications@github.com:

> So what most likely happened is you cast Tools of the Trade 6 times this
> morning, then your warrior logged in, so never got a chance to partake of
> the buff. Does that make sense?
> 
> On Thu, May 21, 2015 at 5:27 AM, Ryan yandoryn@gmail.com wrote:
> 
> > I don't think you quite understand how cron works.
> > 
> > Cron runs the first time someone logs in after their CDS (which for you
> > would be midnight). Unless you are all signing in at exactly the same
> > time,
> > your cron will not be simultaneous.
> > 
> > On Thu, May 21, 2015 at 5:08 AM, wildcate notifications@github.com
> > wrote:
> > 
> > > We all have cron at midnight (at least me and the un-buffed person) - so
> > > different cron shouldn't be the reason in our case...
> > > 
> > > 2015-05-21 13:27 GMT+02:00 deilann notifications@github.com:
> > > 
> > > > Buffs last until a player crons, so if they cronned at different
> > > > times,
> > > > it
> > > > makes sense that they'd have different buffs. Does that make sense?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/HabitRPG/habitrpg/issues/5250#issuecomment-104234661
> > > > .
> > > 
> > > ## 
> > > 
> > > Katrin Kania: "Kleidung im Mittelalter. Materialien - Konstruktion -
> > > Nähtechnik. Ein Handbuch."
> > > 529 S. mit 357 s/w-Abb. und 51 farb. Abb. auf 24 Taf. Böhlau-Verlag Köln
> > > 2010.
> > > Preis 67,90 €
> > > ISBN 978-3-412-20482-2
> > > 
> > > Dr. Katrin Kania M.A.
> > > An der Lauseiche 8
> > > 91058 Erlangen
> > > 
> > > Telefon: 09131-816665
> > > mobil: 0160-91614276
> > > www.pallia.net
> > > Blog (englisch) auf togs-from-bogs.blogspot.com
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/HabitRPG/habitrpg/issues/5250#issuecomment-104249323>
> > > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5250#issuecomment-104255199.

## 

Katrin Kania: "Kleidung im Mittelalter. Materialien - Konstruktion -
Nähtechnik. Ein Handbuch."
529  S. mit 357 s/w-Abb. und 51 farb. Abb. auf 24  Taf. Böhlau-Verlag Köln
2010.
Preis 67,90 €
ISBN 978-3-412-20482-2

Dr. Katrin Kania M.A.
An der Lauseiche 8
91058 Erlangen

Telefon: 09131-816665
mobil: 0160-91614276
www.pallia.net
Blog (englisch) auf togs-from-bogs.blogspot.com

**Comment by deilann** [comment]
There's a lot of discussion on the best way to handle this. It's kind of complicated and not the highest priority. Check out these tickets:

https://github.com/HabitRPG/habitrpg/issues/3071
https://github.com/HabitRPG/habitrpg/issues/2523

One thing you could do now is ask the late-comers if they'd be able to log in earlier, even if they aren't planning on checking off any tasks. They could even set an auto-refresh on their computer to do it for them. I've done that in the past, when I wanted to make sure my cron triggered as early as possible.

If you ask, they may also not be that worried about the buffs. I highly suggest talking to your party about it. The best way to handle it will be different depending on the group.
