### ISSUE TITLE
Error - cannot start new quests

### ISSUE THREAD

**Issue by jrenee25** [HabitRPG/habitica#5252]
My party (Group ID: 7297fa28-47f8-4ea8-8b35-f451102cdf9e) is running into an issue starting a new quest: when a member clicks on an inventory scroll and clicks the "Invite Party" button, they get the following error message:

![image](https://cloud.githubusercontent.com/assets/12550635/7758224/b5af456a-ffcd-11e4-8dac-1337a1e4f817.png)

Members of the party get a quest invitation emailed to their linked email address, but when you click on the link in the email and are redirected to the party's page, there is not an option to accept the quest:

![image](https://cloud.githubusercontent.com/assets/12550635/7758322/79a5c584-ffce-11e4-8cf0-420c42b8fa97.png)

So far six members of my party have attempted to start quests and have encountered this issue.  Please let me know if you need any additional information to address this issue.

My UserID: 37635d5f-c9cb-4842-8c86-2a0be1263afa
Browser: whatsmybrowser.org/b/LGYG7VA

**Comment by Alys** [comment]
@jrenee25 Your party's member list contained one person who had deleted their HabitRPG account (we'll fix the bug that makes that possible). I have removed that person from the members list. Could you please reload HabitRPG and try sending the invitation again? Just try once; if this problem still occurs then you don't need to get anyone else to try. Please let us know if it's working or not!

**Comment by PauloDeSouza** [comment]
Thanks Alys for helping us out - Prodigy here :D

**Comment by Alys** [comment]
Does that mean that you can now start quests? Please confirm so that we know whether we need to keep investigating or not.

**Comment by jrenee25** [comment]
@Alys thank you - the steps you took fixed the problem.  Our party is now able to quest again - yay!!!
