### ISSUE TITLE
when player deletes HabitRPG account, they are not removed from party (and guilds?)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5253]
When a player deletes their HabitRPG account, they remain in the members list of the party they had been in. This can cause problems with starting quests (e.g., the quest won't start automatically once all members have accepted or rejected).

The code to delete a player's account should check to see if they are in a party and if so remove them.

We should also check to see if the same problem exists for guilds, although that's not as critical since it can't cause significant problems.
##

**Comment by TheHollidayInn** [comment]
Okay, I was taking a look into this.

I can check if the user is group, but I'm not sure if I am correctly calling the groups leave function. Can anyone help my call and pass the correct parameters? I'm looking into the Express api now, but help would be welcome!

```
//Check if user is in groups and remove the user from them
  var q = Group.findOne({type: 'party', members: {'$in': [user._id]}})

  q.exec(function(err, group){
    if (err) return next(err);
    if(group){
      groups.leave();
    }
  });
```

Here is the part where I need to pass parameters.
`groups.leave();`

I included the groups controller like this

`var groups = require("../controllers/groups")`

**Comment by crookedneighbor** [comment]
First off, you're going to want to look at the [mongoose api (v 3.8.x)](http://mongoosejs.com/docs/3.8.x/docs/api.html#model_Model.findOne), not express. 

I think using `groups.leave()` here is the wrong approach. Why not just remove the member's ID from the array and then call `group.save()`?

Also, is the exec call needed here? Couldn't you do:

``` js
Group.findOne({ type: 'party', members: {'$in': [user._id]}}, function (err, group) {
  if (err) // handle err
  if (group) {
    // code to pop member's id from array
    group.save();
  }
})
```

**Comment by crookedneighbor** [comment]
Regarding guilds, I feel like the same should be done for guilds, but I'm not sure how easy it would be to grab all the guilds that include a user. Challenges hold onto user ids too, right?

**Comment by Alys** [comment]
@crookedneighbor Probably. I'd be happy to see only parties fixed for now, and guilds sorted out later. Even party challenges could be sorted out later. The biggest problem is dead accounts in members lists.

BTW, for the existing parties that contain dead accounts, I can do stuff in the database to tidy that up, after the code fix goes live.

**Comment by TheHollidayInn** [comment]
Aren't the group functions in the group.js controller Express?

Also, the reason I call group.leave is because the user needs to be removed from quests and challenges.

**Comment by TheHollidayInn** [comment]
Actually, I think what I will do is abstract the functions in groups.leave to use them. I'll send some examples.

**Comment by Alys** [comment]
If a guild leader deletes their account without first leaving the guild, a new leader won't be automatically chosen. This should be fixed too.

**Comment by TheHollidayInn** [comment]
Can definitely do. Does from this line down not take care of that? https://github.com/HabitRPG/habitrpg/pull/5264/files#diff-bda86c52880f0950a5eb0e2f0538b936R405

**Comment by Alys** [comment]
Oh, you'd already fixed it! Sorry about that! I was in a rush with many things to do yesterday and didn't even think to look to see if it was already included in your changes.

Thank you. :)

**Comment by TheHollidayInn** [comment]
No worries :) That code was already there, though. I am writing a test to confirm and will submit it soon!

**Comment by Jolanda5** [comment]
Is this done or is there anything else to do here?

**Comment by Alys** [comment]
@Jolanda5 I'm not certain, but Habitica's API and related code is being rewritten at the moment, and the new code is likely to either already have a fix for this issue or make it easier for a fix to be written. I'll mark this issue as "wait" and we'll look into whether a fix is still needed when the new API is released, which should be just a few weeks away.

**Comment by paglias** [comment]
This is fixed in v3
