### ISSUE TITLE
Skills not available after leveling and choosing class in inn.

### ISSUE THREAD

**Issue by mxrowanthomas** [HabitRPG/habitica#5254]
I just leveled up to level 10 (after being reborn) while in the inn and choose class (warrior) but the skills are not available under rewards. I've tried reloading, logging out and in, using a different device and checking out of the inn to not avail. User id: c03e41bd-501f-438c-9553-a7afdf52a08c

**Comment by Alys** [comment]
Skills don't become available until levels 11 to 14. Please see http://habitrpg.wikia.com/wiki/Skills for more information.

**Comment by mxrowanthomas** [comment]
Whoops, thanks for the fast response.
