### ISSUE TITLE
Moving of To-Dos items doesn't work as intended

### ISSUE THREAD

**Issue by ondrowan** [HabitRPG/habitica#5255]
If I have multiple items in To-Dos (and I guess there's the same issue in other lists) and move the last one to the first position, some other issue is moved instead. I cannot consistently replicate it, but it usualy looks as follows:
- Move item from the last position to the first. Frontend changes are applied as intended. 
- Refresh page.
- Item in first position is either unchanged or there's some completely different item is in its positon.

It seems there could be some strange off-by-X error.

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/2606 for this issue. It contains a description of a workaround.
