### ISSUE TITLE
Cannot invite party to quest

### ISSUE THREAD

**Issue by trueriddel** [HabitRPG/habitica#5256]
Error message is the following: "Please reload, "Error Cannot read property 'pushDevices' of null" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages."

Group ID: 934aaf6e-d5a0-45ed-97ed-006fb1176dca

**Comment by Alys** [comment]
We can't help with this without knowing how to find your account in HabitRPG. Please go to Help -> Report a Bug and follow the instructions there for either your user ID or party ID (either will do for this problem).

**Comment by Rossalli** [comment]
Hi, 

I'm with the same problem. I'm cant' attaching evidence images, so I upload in google drive.

Evidence 1: https://drive.google.com/file/d/0B8Z_MmboIYcMRS05STBrY01pTVE/view?usp=sharing

Evidence 2: https://drive.google.com/file/d/0B8Z_MmboIYcMQ3FUdHFTWi1OMjA/view?usp=sharing

My User ID: 3a51643b-39c2-4b95-b0d6-b0e047e52df6

My Group ID: 4fa24419-47e6-47f0-b8fc-580fbfea9bb8

My Browser: whatsmybrowser.org/b/WUKKPEY

Thanks!

**Comment by crookedneighbor** [comment]
@Rossalli I've removed the deleted user. Please try again and report back here if it does not work.

(Mods, for reference, user id was `38f758b6-545a-4ac2-ab80-635e1360a762`)

**Comment by crookedneighbor** [comment]
Re: the deleted user comment, see here for more context: https://github.com/HabitRPG/habitrpg/issues/5253

**Comment by Alys** [comment]
I've removed deleted user accounts from about 500 parties that contained them, so that should solve this problem for all parties at least in the very short term (and soon the "'pushDevices' of null" fix will go live to prevent the problem for new occurrences).
