### ISSUE TITLE
Reaching Lvl 30 by Backstab Leads to 500 Internal Server Error

### ISSUE THREAD

**Issue by VersorVerbi** [HabitRPG/habitica#5257]
User ID: 90b995d4-2cbd-4a70-88ca-dffbc6de68e5

Whatsmybrowser.org is reporting a 503 Service Not Available error at the moment, but I can at least mention that I have version 43.0.2357.65 m of Google Chrome.

JavaScript console:
POST https://habitrpg.com/api/v2/user/class/cast/backStab?targetType=task&targetId=34497e75-c35a-4efc-813d-a4f29dd5b9b9 500 (Internal Server Error)
nrWrapper @ (index):1
(anonymous function) @ app-55c20289.js:7
s @ app-55c20289.js:7
f @ app-55c20289.js:7
j @ app-55c20289.js:8
(anonymous function) @ app-55c20289.js:8
j.$eval @ app-55c20289.js:8
j.$digest @ app-55c20289.js:8
j.$apply @ app-55c20289.js:8
(anonymous function) @ app-55c20289.js:10
n.event.dispatch @ app-55c20289.js:2
r.handle @ app-55c20289.js:2
nrWrapper @ (index):1

How to Reproduce:
I have a Rogue at level 29 with 613.41 XP / 640. I have 16.51 mana, so I can cast Backstab on my bluest task, one valued at 54.68 according to the Data Display Tool, which would result in 9.27 GP and 46.1 XP, again according to the Data Display Tool. I am in a party with two other players, one of whom is already level 39 and has the level 30 quest in her inventory; she has also invited the party to start the quest (but we have not yet started it, since the other party member has not agreed yet).

When I cast Backstab, I gain 9.27 GP, a level, and a notification about receiving the quest, but when it attempts to make the drop, I get the error: Please reload, "Error Cannot set property 'drop' of undefined" If the error persists, etc., etc., etc.

![jserror_habitrpg1](https://cloud.githubusercontent.com/assets/12559872/7771605/1e9d61de-005e-11e5-8a07-643c2df3d96b.jpg)

When I reload, I lose what I gained from casting Backstab (gold, level) and I regain my 15 MP.

**Comment by crookedneighbor** [comment]
It's because of the quest scroll drop. Level up without a skill, get the quest scroll, then skill level ups should work as normal.

**Comment by Alys** [comment]
You can follow this issue at https://github.com/HabitRPG/habitrpg/issues/4986 if you want to track the progress of the fix.
