### ISSUE TITLE
Background doesn't appear in iPhone app

### ISSUE THREAD

**Issue by swissdot** [HabitRPG/habitica#5258]
I noticed that the new backgrounds (from April and May) don't appear behind my character in the iPhone app. Instead, I see only a grey background. I haven't purchased backgrounds from any other months, so I can't test to see if this happens with the old backgrounds as well. I have no problems when I use the website.

I'm using an iPhone 6 with v0.0.53 of the app.

My user ID is 1e4fb590-3ddf-4ada-8d53-e4e20693b974.

Thanks for your help!
swissdot

**Comment by lemoness** [comment]
So, right now the iOS is always behind with artwork, especially as it takes
Apple a long time to approve each update. The new backgrounds will be in
the next update!
