### ISSUE TITLE
Link Facebook to HabitRPG account with email as username

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#526]
I love that you can sign-in with Facebook, but I think that you should be able to link your Facebook to an account, i.e. have a username and password for HabitRPG as well (for example, use the user's email).  This way, you could use #524 when signing in, if the service doesn't support Facebook sign-in.

**Comment by wc8** [comment]
[Social Sharing](https://trello.com/c/8TbkzhtR) and [consolidate social network accounts](https://github.com/lefnire/derby-auth/issues/16) related to this.

**Comment by paglias** [comment]
Follow up at #477
