### ISSUE TITLE
Display Current Selected Customizations

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5260]
Right now, there's no way to tell which customizations are currently displayed your avatar, in contrast to the Equipment page, which highlights them. This has been especially confusing to new users.

It would be nice to have some sort of highlight or indicator for the currently selected items on the customizations page like the one on the Equipment page.

**Comment by deilann** [comment]
I think we already have a PR for this.

**Comment by hairlessbear** [comment]
Yup, #5231. Just waiting for someone to review it!

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/5231

**Comment by lemoness** [comment]
Fantastic!
