### ISSUE TITLE
Overview for New Users should be at the top of the Help dropdown

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5261]
Right now, the link for "Overview for New Users" is last in the Help drop down, and the FAQ is first. The FAQ is not helpful to new users, since it involves much for detailed information. They should be swapped so that the Overview is first and the FAQ is last.

**Comment by ghost** [comment]
Screenshot of changes: http://oi59.tinypic.com/21eat20.jpg
Screenshot of changes for slim/mobile view: http://oi58.tinypic.com/52bb6p.jpg

@lemoness Please excuse me for asking, but could you please confirm, that I got it right:
1. The wording of FAQ and Overview for New Users remains the same ([screenshot 1](http://oi59.tinypic.com/21eat20.jpg))
2. The "mobile" menu should have the same changes ([screenshot 2](http://oi58.tinypic.com/52bb6p.jpg))
3. The settings menu also containing FAQ remains unchanged ([screenshot 3](http://oi62.tinypic.com/90at14.jpg))
4. The Overview for New Users is a link to the wiki front page

Am I right about these points?

**Comment by lemoness** [comment]
All correct, thank you!

Whether or not we should include the FAQ in the Settings list vs. the
Overview for New Users vs. Nothing is a separate debate that we can have,
but it shouldn't hold up this PR.

**Comment by Alys** [comment]
@GitHubSphinx That's a good collection of screenshots! Including the mobile view was thoughtful. Thank you!

**Comment by hairlessbear** [comment]
Any particular reason this shouldn't be closed?
