### ISSUE TITLE
Text Improvements

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5262]
There is a lot of text around that site that needs improving.
- [x] Checklist Hover Text

The current Checklist hover text is overly detailed. We could possibly have a "Learn More" link somewhere, but in the meantime, the text should be simplified.

Suggested replacement text :
Break a task into smaller pieces! Checklists increase the Experience and Gold gained from a To-Do, and reduce the damage caused by a Daily. 
- [x] Difficulty Hover Text

Seems weird to tell users to use sparingly - we don't prescribe a certain way to use the site. Also, "organic value-adjustment algorithms" is... not exactly user-friendly. We will need to update this when we change the difficulty settings, but that's not for a while.

Suggested Replacement Text:
The harder a task, the more Experience and Gold it awards you when you check it off... but the more it damages you if it is a Daily or Bad Habit!
- [x] Tavern pop-up text:

"Freeze account" is 1) frequently associated with banning and 2) not that accurate, with the recent change to the Inn.

Suggested Replacement Text:
Welcome to the Tavern, an all-ages chatroom! You can keep your Dailies from hurting you in case of illness or travel by clicking "Rest in the Inn." Come say hi!
- [x] Challenge pop-up text:

Needed a sentence of explanation.

Suggested Replacement Text:
Challenges are themed task lists created by users! Joining a Challenge will add its tasks to your account. Compete against other users to win gem prizes!
- [x] Pet Page Speech Bubble

Some pre-level 4 users have been confused about why they don't have pets/how to get them.

Suggested Replacement Text:
Welcome to the Stable! I'm Matt, the beast master. After level 4, you can hatch pets using eggs and potions. When you hatch a pet in the Market, it will appear here! Click a pet's image to add it to your avatar. Feed them with the food you find after level 4, and they'll grow into powerful mounts.
- [x] Mount Page Speech Bubble

Needed explanation of how to get a mount.

Suggested Replacement Text:
Shall I bring you your steed, NAME? Once you've fed a pet enough food to turn it into a mount, it will appear here. Click a mount to saddle up!
- [ ] Pop-up button change

In all the one-time pop-ups, such as the Tavern pop-up that appears for the first time you navigate into the Tavern, there are two buttons: "Previously" and "Finish Tour." Neither makes sense.

Suggested Fix:
Remove the "Previously" button from the one-time pop-ups altogether, and change "Finish Tour" to "Okay!" (or, if possible to do individual ones.... "Okay!" "Nifty!" "Awesome!" "Cool!" "Spiffy!" etc)

**Comment by hairlessbear** [comment]
@lemoness Could I add an item to the list? The mystery item popover text ([located here](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/generic.json#L18)) contains the sentence "_See the wiki's 'Mystery Item' page for the exact date._", but has no link to the [Mystery Item wiki page](http://habitrpg.wikia.com/wiki/Mystery_Item). I see no reason to not include a link.

**Comment by Alys** [comment]
@hairlessbear Alas, the popup would disappear whenever you tried to click on the link. :)

**Comment by hairlessbear** [comment]
@Alys I was confused about what you meant until I tried to click on a popover's text. I totally understand now :)

Man, if we had introduced that...I cringe at the thought of the bug reports.

**Comment by Alys** [comment]
@lemoness May I suggest another change? It's in the instructions in the quest box on the party page.
- [x] Quest instructions text:

Currently: "To hurt a boss, complete your Dailies and To-Dos. Higher task damage means higher boss damage (completing reds, Mage spells, Warrior attacks, etc)." 
We've had some users asking if the first sentence means that you must finish **all** your To-Dos.

Suggested Replacement Text (or something like this):
"Each completed Daily and To-Do and each positive Habit hurts the boss. Hurt it more with redder tasks or Brutal Smash and Burst of Flames."

**Comment by lemoness** [comment]
@alys - Sounds great!

**Comment by lemoness** [comment]
Another piece of text to change, in Challenges:
- [x] Sample Challenge Task intro text:

OLD: "These are the challenge's tasks. As users participate, they will change color and gain graphs to show you the overall progress of the group."
NEW: "These are the Challenge's tasks that will be added to your task dashboard when you join this Challenge. The sample Challenge tasks below will change color and gain graphs to show you the overall progress of the group."

**Comment by Alys** [comment]
EDIT: This point should be discussed in https://github.com/HabitRPG/habitrpg/issues/5125 where it's already been mentioned along with other related things. _In the Wizards of the Wiki guild, Purplatypus has pointed out "I just took the class system tour, and it said 'Your mana replenishes 10 points per day, plus 1 point per completed To-Do.' But now it can be fewer than that if you don't complete all your Dailies, right? Should that text be changed?"_

FYI to other coders, I'll be doing this on Saturday (GMT+10 timezone) if no one else gets to it first, so if you're a beginning programmer looking for an easy text change coding job, jump in now! If you feel that the "Pop-up button change" is too advanced for you, I can do that part.

**Comment by deilann** [comment]
I pointed out a while ago that is an inaccuracy along with many other
things in the class tutorial. You can see the ticket here:
https://github.com/HabitRPG/habitrpg/issues/5125

**Comment by Alys** [comment]
Ugh, sorry deilann. I'm editing my post to link to yours for that item to be discussed there instead of here.

**Comment by mayajosyula** [comment]
Could I try doing this? I don't think I can do the "pop-up button change" part, but I can definitely do all the text changes.

**Comment by hairlessbear** [comment]
@agentx999 Of course, as long as you beat @Alys to the punch ;) If you have any issues, don't hesitate to ask here.

**Comment by Alys** [comment]
All text changes have been done.

I'm working on the "Pop-up button change" task.

**Comment by Alys** [comment]
Waiting for https://github.com/HabitRPG/habitrpg/pull/5307 to be merged.

**Comment by Alys** [comment]
It looks like the "Pop-up button change" was done under a different issue so I'm closing this.
