### ISSUE TITLE
>20 Days of Intermittently Missing Daily Data

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#5263]
When I view my data on the [HabitRPG Official User Data Display page](https://oldgods.net/habitrpg/habitrpg_user_data_display.html?uuid=90145e45-71ca-4c83-8ecf-703e40ccdcda) and click on "Dailies History", I see a lot of gray bars even though I know I haven't been to the inn that often (see attached screenshot). I also appear to be missing a huge # of days. For example, "Did exercises" is a daily item that has been running for over 2 months.

Furthermore, if I try to export the data as XML (see attached data extract) and look at the history section for the item, the history is suspiciously short.

Context:
- User ID: 90145e45-71ca-4c83-8ecf-703e40ccdcda
- What's my Browser:

`Service Temporarily Unavailable`
`The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`
`Apache/2.2.15 (Red Hat) Server at www.whatsmybrowser.org Port 80`

F12 Developer Toolbar Console:

SCRIPT5: Access is denied.

File: sh.0c665a7f.html, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: hub.f15fe2cd70788a40560e69fa17341d5e.html, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: like.php, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: tweet_button.b169aa788731255dd55f1bb243b660e1.en.html, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: fastbutton, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: QrU_tEEWym9.js, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: ping, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: postmessageRelay, Line: 1, Column: 1

**Comment by Zian** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1581929/7782284/cb23a95e-00c2-11e5-9739-2c77d3a03667.png)

**Comment by Zian** [comment]
I can't seem to attach the XML extract so I will copy and paste the contents.

**Comment by Zian** [comment]
<dailys>
    <text>Did exercises</text>
    <challenge/>
    <attribute>str</attribute>
    <priority>1</priority>
    <value>-2.370509252897958</value>
    <tags/>
    <notes></notes>
    <dateCreated>2015-03-10T04:57:45.660Z</dateCreated>
    <id>bf25b685-5517-432e-bb32-ed67278dda2e</id>
    <streak>2</streak>
    <collapseChecklist>false</collapseChecklist>
    <repeat>
      <su>false</su>
      <s>false</s>
      <f>true</f>
      <th>true</th>
      <w>true</w>
      <t>true</t>
      <m>true</m>
    </repeat>
    <completed>false</completed>
    <history>
      <value>-4.4307037622097285</value>
      <date>2015-03-10T18:39:39.985Z</date>
    </history>
    <history>
      <value>-1.944664568628732</value>
      <date>2015-04-01T14:12:04.326Z</date>
    </history>
    <history>
      <value>-0.49239610023888947</value>
      <date>1430489843124</date>
    </history>
    <history>
      <date>1430593538596</date>
      <value>0.5203017613134533</value>
    </history>
    <history>
      <value>0.5203017613134533</value>
      <date>1430666833360</date>
    </history>
    <history>
      <date>1430749300169</date>
      <value>0.5203017613134533</value>
    </history>
    <history>
      <value>-0.466453712073727</value>
      <date>1430832564929</date>
    </history>
    <history>
      <date>1431008216873</date>
      <value>-2.5170922470897015</value>
    </history>
    <history>
      <value>-1.4504646771444651</value>
      <date>1431156973970</date>
    </history>
    <history>
      <date>1431195561316</date>
      <value>-2.488333032775873</value>
    </history>
    <history>
      <value>-2.488333032775873</value>
      <date>1431271535182</date>
    </history>
    <history>
      <date>1431331309894</date>
      <value>-2.488333032775873</value>
    </history>
    <history>
      <value>-1.4224912464231168</value>
      <date>1431439958757</date>
    </history>
    <history>
      <date>1431526627721</date>
      <value>-2.4596158888213635</value>
    </history>
    <history>
      <value>-3.5246736186802763</value>
      <date>1431612627105</date>
    </history>
    <history>
      <date>1431698919100</date>
      <value>-2.430147291538055</value>
    </history>
    <history>
      <value>-3.49440104777558</value>
      <date>1431919191586</date>
    </history>
    <history>
      <date>1432022384306</date>
      <value>-3.49440104777558</value>
    </history>
    <history>
      <value>-4.588078624049792</value>
      <date>1432022409920</date>
    </history>
    <history>
      <date>1432131308472</date>
      <value>-3.463315983349018</value>
    </history>
    <history>
      <value>-2.370509252897958</value>
      <date>1432320691935</date>
    </history>
    <type>daily</type>
  </dailys>

**Comment by Zian** [comment]
And, since GitHub wrecked the text, here's a set of screenshots from Notepad++.

**Comment by Zian** [comment]
![part 1](https://cloud.githubusercontent.com/assets/1581929/7782293/312d987c-00c3-11e5-93d0-9879a0b0c13c.png)
![part 2](https://cloud.githubusercontent.com/assets/1581929/7782292/312aff40-00c3-11e5-8e2f-6bd94cbbd415.png)

**Comment by deilann** [comment]
Are you a subscriber? If not or if you weren't during that period that's
expected. Non subscriber data is condensed to save space. See.the.details
info in the ddt for more info.

**Comment by Zian** [comment]
What's a "ddt"? I don't see anything about subscriber vs. non subscriber data on the HabitRPG Official User Data Display page.

**Comment by Alys** [comment]
DDT = Data Display Tool

If you click "show explanation" on the section you are looking at, you will see something about subscriber vs. non subscriber data.

**Comment by deilann** [comment]
"The table below shows historical data for your dailies. If you are a
subscriber, you will see data for every day going back to the date on which
you subscribed. If you are not a subscriber, you will see data for every
day for the past week, but before that your data points start to be merged
together (this is to save on expensive database storage space). In the
table are symbols indicating your actions on each day:"

**Comment by Zian** [comment]
Thanks for pointing it out. Is the data permanently lost?

It looks like the caution is only shown in the place you referred to rather than in the main documentation that is displayed before loading data. The page seems to have a lot of text even though users don't read.

I will contact Ms. Harris about it as she writes that "If you have questions, problems, or suggestions, you're welcome to contact me, although I cannot guarantee that I'll always be able to spend a lot of time on this. Email to lady_alys@oldgods.net is the best way to reach me,"

**Comment by Alys** [comment]
The caution is shown on the page where it is relevant. If it were shown in the main documentation, even fewer people would read it. The main documentation is an overview of the entire tool. Specific information about individual sections is shown in those sections.

**Comment by Alys** [comment]
Any data that has been merged together is permanently merged. There is no way to get it back.

_"The page seems to have a lot of text even though users don't read."_  If there were less documentation on the page, we'd get more questions about it. I don't think it's unreasonable to provide text that explains the tool.
