### ISSUE TITLE
decrease in mana

### ISSUE THREAD

**Issue by nightstitched** [HabitRPG/habitica#5266]
today my maximum mana suddenly decreased. Yesterday I had somewhere around 80 maximum, but now today it decreased to 58.

my Id number is: 8f711a4a-b928-4428-9de4-0c3325d84ed3

thanks

**Comment by lemoness** [comment]
Never fear - your mana varies with your avatar's Intelligence stat, so if
your Intelligence was buffed, for example by a Perfect Day, or if you
switched to different armor, your Mana will decrease. Good incentive to get
another perfect day!

I'm closing this now, but feel free to respond if you have more questions :)
