### ISSUE TITLE
Please delete the unnamed Tavern challenge with CID 4bd19776-15f8-4503-9479-598cd437cdd5 (created by @Austinchesworth, UID: c3e11505-815a-4307-878e-c7dd051bf19d)!

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#5269]
The challenge is completely empty - no title, no text, no tasks, but 9 participants. :) The creator last logged in 24/04/2015, so I didn't even bother to message em.

I'm still proud I even found out the CID! (It's not straightforward, the only thing you can click on this challenge is "Join/Leave", you can't even click it open to read it.) In the Tavern challenge list, it can be found between "Psionic Development" and "AP Test Review help".

**Comment by Alys** [comment]
Done, thank you!
