### ISSUE TITLE
Markdown Formatting for guilds does not appear in main guild listings

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5273]
Hello! I'm not entirely sure if this is deliberate or not but I noticed that the markdown formatting for text does not appear to be showing up in the guild listing descriptions for guilds on the main guild lists.
## Here is a photo showing 2 guilds with markdown not showing uo:

![guildlistingmarkdownnotshowing1](https://cloud.githubusercontent.com/assets/7588148/7789447/5ea64222-0226-11e5-8adb-28853b7464e8.png)

---

Here are the respective guild descriptions within their guilds:
![guildlistingmarkdownnotshowing3](https://cloud.githubusercontent.com/assets/7588148/7789451/6df5d670-0226-11e5-9045-250ae06e1d19.png)

and

![guildlistingmarkdownnotshowing2](https://cloud.githubusercontent.com/assets/7588148/7789452/73a22362-0226-11e5-9b58-e6cdcb2e0bd3.png)

---

I might be correct in this being deliberate but if not it might be good to look into maybe allowing markdown in the guild descriptions or at least some parts of the markdown if possible. Having giant banners of words might not be best to have in the guild listings but that would be up to the staff and others. 

Thank you and have a great day.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by crookedneighbor** [comment]
I'm okay with allowing descriptions to have markdown in the list view and should be trivial to do.

@Alys @lemoness @deilann Do y'all have opinions?

**Comment by deilann** [comment]
I've long felt like the markdown should show.

**Comment by Alys** [comment]
@Rbrinkley thanks for bringing up this problem! I'm closing this now that I've created https://github.com/HabitRPG/habitrpg/issues/5311 which describes how we (probably) want to resolve this issue. Feel free to comment on that issue if you have anything you'd like to add!

**Comment by Rbrinkley** [comment]
@Alys Glad to help! I'll make sure to comment if I have anything I might want to add. Thank you for all your help on this issue. Also thanks to everyone else who helped and is currently helping with the issue too. Glad to see this getting some steam. Thanks again!
