### ISSUE TITLE
Can't cancel my subscription

### ISSUE THREAD

**Issue by drdiggit42** [HabitRPG/habitica#5276]
When I attempt to cancel my subscription I get the this message:
 {"err":"Cannot read property 'current_period_end' of null"}

My user ID is : 8467fff2-c527-4930-a662-f7c290edcd96

Whatismybrowser.org is not working, but I am using Chrome 43 on a WIndows 7 64bit PC

**Comment by Alys** [comment]
I've fixed that for you. Your subscription should terminate in a week.

If you were cancelling so that you could resubscribe with a different method, then you would be able to do that now.

Thank you for letting us know about whatismybrowser!
