### ISSUE TITLE
Randomly died

### ISSUE THREAD

**Issue by TyranoTank** [HabitRPG/habitica#5278]
I completed all but 2 dailies, I had about 30 health, and not in a boss quest. I am unsure why I logged in and died. I need someone to reset me to an old state or something. I had a lot I had accomplished which is now lost. I primarily use the app on iOS. User id: 7067f595-e0b5-48ed-8386-5599668b4a2a

**Comment by deilann** [comment]
You can patch yourself up using FCV on the website. (Settings > Site > Fix
Character Values). We generally do not download database backups and upload
them for issues of this sort as it's a multi-hour process and users can use
FCV to fix it themselves for the most part.
