### ISSUE TITLE
Semi-sudden death!

### ISSUE THREAD

**Issue by MiriamELewis** [HabitRPG/habitica#528]
Hi so yesterday I was having trouble getting in to the site but I left the extension recording my productiveness for the work day (7 hours). Toward the end I noticed my hp was set 1hp but I couldn't log-in during the evening and so assumed it was a glitch. 
I've just now logged in and it killed me!

I remember my level and armour but not my hp & xp. 

I wasn't logged into my vice sites much yesterday so if it was the extension that killed me it killed me with productivity! (ha)

Anyways- hhhhheeeeelp!

**Comment by horusofoz** [comment]
Hi @MiriamELewis 

Can you email your UID from User Menu>Settings to our lead developer [Tyler](mailto:tylerrenelle@gmail.com)?

@lefnire Can you provide the user with a restore from yesterday?

**Comment by MiriamELewis** [comment]
Done :) (emailed him)

**Comment by lefnire** [comment]
I responded to Miriam via email, but for anyone else who experiences this - follow [these instructions](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account) to restore your avatar until we get these bugs fixed
