### ISSUE TITLE
Add semanitc ids to community guidelines

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#5281]
Right now, the different [sections of the community guidelines](https://habitrpg.com/static/community-guidelines) do not have ids, which makes it hard to link to specific sections.

It'd be useful if the major sections had an id with the name of the section, all lower case, with hyphens instead of spaces. So "Public Spaces In Habitica" would become `#public-spaces-in-habitica`

**Comment by lemoness** [comment]
Agreed! I would find this feature very useful.

Also while you're in there, we need to add Beffymaroo to the list of mods!

I'll nab the updated mod art right now.

**Comment by lemoness** [comment]
![npc mods3](https://cloud.githubusercontent.com/assets/3494081/7825242/6dce0f88-03bf-11e5-9084-7172e17b1d33.png)

**Comment by JWPapi** [comment]
should be closed shouldnt it?

**Comment by Alys** [comment]
Thanks @JWPapi!
