### ISSUE TITLE
Make Help Button More Obvious

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5283]
It would be nice to make the help button in the header more obvious, perhaps by changing its color. 

Would this be a suitable project for an aspiring coder?

**Comment by crookedneighbor** [comment]
Sure would. Just needs a [bootstrap class](http://getbootstrap.com/) applied to it.

**Comment by averrin** [comment]
![header-help-button](https://cloud.githubusercontent.com/assets/426007/7833301/71617f22-046e-11e5-82bc-1f8d54a7cfb3.png)
Something like this?

**Comment by averrin** [comment]
or this:
![header-help-button1](https://cloud.githubusercontent.com/assets/426007/7833537/4e3ef158-0470-11e5-9204-7a8d5447758e.png)

**Comment by deilann** [comment]
Yes, but bright green is probably not the way to go.

**Comment by lemoness** [comment]
Agreed - can we try a shade of blue, perhaps? And not quite so bright.

**Comment by excentris** [comment]
@lemoness something like the subscribe button? I'd like to fix this as my first contribution :)

**Comment by averrin** [comment]
@excentris 
i have already some variants: #5300 but its not so easy. To decide, not to develop.

**Comment by excentris** [comment]
@averrin @crookedneighbor Ah, alright. By the way, is there a way to see if somebody is working on an issue? I started working on this because I did not see an Assignee.

**Comment by averrin** [comment]
@excentris i dont know how it work, its my first contribution. And im slightly dissapointed.

**Comment by crookedneighbor** [comment]
Only members of the org can be listed as an assignee, unfortunately. 😔

**Comment by excentris** [comment]
@crookedneighbor Thanks! What is then the best way to indicate that you are working on an issue? Leaving a comment on the issue itself?

**Comment by deilann** [comment]
Yes, that's the best way.

**Comment by excentris** [comment]
@lemoness @crookedneighbor The pull request opened by @averrin was not working for me, so I opened a new pull request #5314 taking into account the '?' improvement proposed by @averrin and using current stylus mixins and colours for consistency.
