### ISSUE TITLE
Challenge Sample tasks should not be clickable

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5284]
Right now, you can click on the sample Dailies and To-Dos in a Challenge, and a checkmark appears. This is misleading - there should be no interaction.
##

**Comment by Ozzystrasza** [comment]
I'd like to try this one, if it's ok.

**Comment by crookedneighbor** [comment]
Go for it. If no one has claimed it, feel free to just say you're looking at it and go for it. (Just comment back if you can't do it after all)

**Comment by Ozzystrasza** [comment]
@lemoness I fixed it on challenge view and individual user view (under "How's everyone doing?"). Do you also want it to be non interactable when creating or editing a challenge?

**Comment by crookedneighbor** [comment]
Yes. It should not be interact able in any context where it doesn't make sense to be able to score.

**Comment by Ozzystrasza** [comment]
After my changes nothing happens when you click on the tasks on challenge view, creation or editing. However, on creation or editing it still shows the V when you hover the mouse on the button . I'm having trouble disabling that. Any suggestions?
