### ISSUE TITLE
Adding Blurbs to Certain Pages

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5286]
Some of the pages on HabitRPG don't have any explanation of what they are, other than the one-time pop-up the first time a user visits those pages. To avoid confusion and minimize questions, the following blurbs should be added. (Feel free to suggest improvements to the text!)
- [ ] Hall of Heroes

This is the Hall of Heroes, where open-source contributors to HabitRPG are honored. Whether through code, art, music, writing, or even just helpfulness, they have earned gems, exclusive equipment, and prestigious titles. You can contribute to HabitRPG, too! [Find out more here.](http://habitrpg.wikia.com/wiki/Contributing_to_HabitRPG)
- [ ] Hall of Patrons

This is the Hall of Patrons, where we honor the noble adventurers who backed HabitRPG's original Kickstarter. We thank them for helping us bring Habitica to life!
- [ ] Inbox

This is where your private messages are stored! You can send someone a message by clicking on the letter icon next to their names in Tavern, Party, or Guild Chat.
- [ ] Guilds Page

Guilds are common-interest chat groups created by the players, for the players. Browse through the list and join the Guilds that interest you!
- [ ] Challenges Page

Challenges are created by your fellow players. Joining a Challenge will add its tasks to your task dashboard, and winning a Challenge will give you an achievement and often a gem prize!

**Comment by hairlessbear** [comment]
#### Hall of Heroes

I don't think "open-source" is necessary; I'd remove it. Also, I think "prestigious titles" should link to the [contributor titles wiki page](http://habitrpg.wikia.com/wiki/Contributor_Titles), and "gems, exclusive equipment" should link to the [contributor rewards wiki page](http://habitrpg.wikia.com/wiki/Contributor_Rewards). Both of these links are contained in the intro paragraph of the linked "contributing to HabitRPG" page, but I think more people will see them if they're included individually.

#### Inbox

The suggested text doesn't mention that the letter icon is in member pop-ups as well. Maybe that should be added?

#### Guilds Page

I think creating your own guild and guild challenges should be added. Something like "Guilds are common-interest groups created by the players, for the players. They allow players to chat and create challenges. Browse through the list and join the Guilds that interest you, or create your own!"
(That second sentence needs polishing, but you get the idea.)

#### Challenges Page

Do challenges often have a gem prize? I thought the vast majority of them had no prize. If my perception is correct, this is a bit misleading.

**Comment by Alys** [comment]
I like "open source" being there. It emphasises that anyone can contribute. I think it's an important point.

Can "letter icon" be changed to "envelope icon"? I kept wondering what letters (of the alphabet) it was talking about until it clicked. :)

I wouldn't mention the member pop-ups for that, because they don't always have the icon, and you can only get to the ones that do from the same places that the icon is. We don't want the text to be too long or at all confusing.

**Comment by lemoness** [comment]
Yes, "envelope icon" is fine!

I'm happy for extra links to be included in the Hall.

I like the amended sentence that includes a mention of creating Guilds.

All Tavern Challenges are required to have a gem prize, so I think this is
fine.

**Comment by MatthewMcP** [comment]
Hi there, just joined so hoping to make this my first commit. I'm a bit confused as to where this text should go? Some of the pages have infinite scrolling so I can't place at the bottom. I could make them appear on mouse-over like the ones in the top bar?

**Comment by hairlessbear** [comment]
@MatthewMcP They should go somewhere at the top of the page's content (i.e., below the header). 
Personally, I think they should go here:
![selection_026](https://cloud.githubusercontent.com/assets/7059890/8138479/2a8af878-1119-11e5-973e-3fcfe63bfcba.png)
(that is, somewhere in between the navigation buttons and the page content).

Exactly how they're styled is up to you, as far as I know. Do whatever you think is best and submit a PR with screenshots. The wonderful thing about code is it's infinitely changeable, so if the admins prefer a different style than you initially submit, you can tweak it as necessary.

**EDIT:** To be clear, I'm not an admin, and the above should be read as my opinions, _not_ hard requirements.

**Comment by MatthewMcP** [comment]
Whats a PR? Here's your first idea implemented.
![image](https://cloud.githubusercontent.com/assets/8578541/8139892/06aee6ea-114f-11e5-957e-163029a70a96.png)

An alternative would be 
![image](https://cloud.githubusercontent.com/assets/8578541/8140067/753c6d70-1150-11e5-9a96-6d946a654d91.png)

Neither are ideal as it's a very prominent place to be shown every time. an question mark icon with the text displayed on click would be better in my opinion as users will not need to see this message every time.

**Comment by hairlessbear** [comment]
Oops, sorry. PR = pull request. It's how you submit changes to the codebase. Instructions on how to do that are [here](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths#Create_a_New_Feature).

The problem with a question mark icon is that many users won't click on it, defeating the purpose of the blurb. I think the phrases are short enough that their prominent placement isn't problematic, but that's just my opinion. You'll have to wait for @lemoness or another admin to give you true guidance on what to do.

**Comment by MatthewMcP** [comment]
No problem, I'll learn the lingo quick! I'll wait for @lemoness as I should have free time on Sunday to implement this. Thanks for all your help @hairlessbear, really appreciate it!

**Comment by hairlessbear** [comment]
Glad to help! I've received huge amounts of help from the admins since I started coding for HabitRPG; it's the least I can do to help other users when I can.

Quick note: in your screenshots, you didn't include the links mentioned in my response to @lemoness's original post. Make sure you add those links in the final version (you may already know this, I just wanted to make sure). It should look like: "This is the Hall of Heroes, where open-source contributors to HabitRPG are honored. Whether through code, art, music, writing, or even just helpfulness, they have earned [gems, exclusive equipment](http://habitrpg.wikia.com/wiki/Contributor_Rewards), and [prestigious titles](http://habitrpg.wikia.com/wiki/Contributor_Titles). You can contribute to HabitRPG, too! [Find out more here](http://habitrpg.wikia.com/wiki/Contributing_to_HabitRPG)."

**Comment by lemoness** [comment]
I don't think it will be annoying to have a single line of text there
(think, for example, of the NPC blurbs, which always display). I like the
first screenshot best, with the full sentence. Be sure to include the links!

**Comment by MatthewMcP** [comment]
Great, I'll start implementing this tomorrow evening - with links!

**Comment by hairlessbear** [comment]
This has been solved with #5513; would someone mind closing this?

**Comment by Alys** [comment]
Thank you. :)
