### ISSUE TITLE
Dailies Checked automatically when different days set for dailes

### ISSUE THREAD

**Issue by gsalvadi** [HabitRPG/habitica#5287]
When I set different set of days for different dailies, like 'Daily1' Mon, Tue, Wed, Thu and for 'Daily2' Fri, Sat, Sun and so on. I had around ten dailies with different day scheduled. After 12 00 AM, few dailies were checked done automatically. I tried unchecked it. But it appeared again checked the next day. The checked dailies were dailies they were muted on certain days of week.

**Comment by Alys** [comment]
Is this still happening? If so, please tell us your user ID (you can find out how to get your user ID by going to Help -> Report a Bug and looking at step 6 in the instructions there). Please add it as a new comment rather than editing your post, because we don't receive email notifications for edits. 

You don't need to include your user ID if it's no longer happening. In that case, it was probably this bug: https://github.com/HabitRPG/habitrpg/issues/4313

**Comment by NOMINDTR** [comment]
I made adjustments watching for two days. I have added similar daily. Will
update if the problem prevails tomorrow.
Thanks

*Gokul Salvadi*
Chop wood; carry water

**Comment by gsalvadi** [comment]
I made adjustments watching for two days. I have added similar daily. Will
update if the problem prevails tomorrow.
Thanks

**Comment by gsalvadi** [comment]
Unlike [Issue 4313](https://github.com/HabitRPG/habitrpg/issues/4313) , I did not have any damages for dailies I did. On cron, few dailies appeared checked automatically. This happened on the day I made few dailies only for few days of the week. I will check again. 

My user ID is 70d88957-673a-4edd-b97e-f1ecb018dd89

**Comment by deilann** [comment]
Did you try refreshing? Sometimes this happens to me until I refresh, and
then they show unchecked.

**Comment by gsalvadi** [comment]
Yes. I remember I tried refreshing. I will update here.

**Comment by Momogajo** [comment]
f3df5aad-6e4c-4825-a907-095c0928f72d I'm having the same problem, many of my dalliances were pre-checked off and dalliances I did last night apparently didn't count and damaged my party during our boss battle

**Comment by Momogajo** [comment]
I'm on chrome and am using Windows 7(I think)

**Comment by deilann** [comment]
The reason we think this might not be
https://github.com/HabitRPG/habitrpg/issues/4313 is because this user did
not take damage. If damage was taken, Momogajo, it is that issue.

**Comment by Momogajo** [comment]
No I don't think I took damage, it just said that the party was hit for points and my dallies didn't change over

**Comment by deilann** [comment]
If your party was hit for damage, then this is different, and is 4313, like
I linked.

**Comment by Momogajo** [comment]
I asked if anyone was hit for damage and haven't received a response back from anyone so I am going with the solutions you sent in that link

**Comment by deilann** [comment]
If it showed that you did boss damage, they would have been hit.

**Comment by Alys** [comment]
It sounds like these problems didn't keep happening or were adequately explained by @deilann, so I'm closing this but it can be reopened if needed.
