### ISSUE TITLE
Didn't get Green Knight equipment?

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#5289]
Hi, I logged in today to see Bailey saying that the subscriber set's been revealed so I went to my inventory and used the two presents. However, I didn't get a pop-up in the upper right saying what I got, so I went into my equipment and found that even though my present count is now 0 I still don't have this month's subscriber set.

User ID: 8a1db51b-01f8-4794-8f9b-a0da605b9bcb
Browser: Google Chrome
Operating System: Windows 7
Console errors:

Received message of type object from https://platform.twitter.com, expected a string
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
Failed to load resource: net::ERR_NETWORK_CHANGED
Google login url is detected: https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fhabitrpg.com#rpctoken=499556320&forcesecure=1
Second factor url is not detected: https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fhabitrpg.com#rpctoken=499556320&forcesecure=1
Failed to load resource: the server responded with a status of 404 (Not Found)
TypeError: Cannot read property 'key' of undefined
    at a.ops.openMysteryItem (https://habitrpg.com/app-55c20289.js:34:5241)
    at Object.m.ops.(anonymous function) [as openMysteryItem](https://habitrpg.com/app-55c20289.js:38:294)
    at g (https://habitrpg.com/app-55c20289.js:8:4596)
    at e (https://habitrpg.com/app-55c20289.js:10:12654)
    at j.$eval (https://habitrpg.com/app-55c20289.js:8:17252)
    at j.$apply (https://habitrpg.com/app-55c20289.js:8:17487)
    at HTMLButtonElement.<anonymous> (https://habitrpg.com/app-55c20289.js:10:12715)
    at HTMLButtonElement.n.event.dispatch (https://habitrpg.com/app-55c20289.js:2:6466)
    at HTMLButtonElement.r.handle (https://habitrpg.com/app-55c20289.js:2:3241)
    at HTMLButtonElement.nrWrapper (https://habitrpg.com/:1:12133)
Empty

**Comment by deilann** [comment]
Are you a subscriber? Have you tried refreshing?

There's absolutely no information in this ticket... no UUID, no explanation of what's going on. We'll need at least some info to go on.

**Comment by Sethycakes** [comment]
Sorry! I accidentally pressed enter after writing the title and it submitted the ticket before I could write anything. I was hoping I could edit some info into my ticket before anyone could see but I was barely too late.

**Comment by deilann** [comment]
Editing wouldn't send the info to anyone's email anyway and many of us do
support via email, not Github's site directly.

**Comment by Sethycakes** [comment]
So then what do you suggest I do? Close this and submit a new properly written ticket?

**Comment by deilann** [comment]
Having read what you've edited in

for email posterity:

Hi, I logged in today to see Bailey saying that the subscriber set's been
revealed so I went to my inventory and used the two presents. However, I
didn't get a pop-up in the upper right saying what I got, so I went into my
equipment and found that even though my present count is now 0 I still
don't have this month's subscriber set.

User ID: 8a1db51b-01f8-4794-8f9b-a0da605b9bcb
Browser: Google Chrome
Operating System: Windows 7
Console errors:

Received message of type object from https://platform.twitter.com, expected
a string
Given URL is not allowed by the Application configuration: One or more of
the given URLs is not allowed by the App's settings. It must match the
Website URL or Canvas URL, or the domain must be a subdomain of one of the
App's domains.
Failed to load resource: net::ERR_NETWORK_CHANGED
Google login url is detected:
https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fhabitrpg.com#rpctoken=499556320&forcesecure=1
Second factor url is not detected:
https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fhabitrpg.com#rpctoken=499556320&forcesecure=1
Failed to load resource: the server responded with a status of 404 (Not
Found)
TypeError: Cannot read property 'key' of undefined
at a.ops.openMysteryItem (https://habitrpg.com/app-55c20289.js:34:5241)
at Object.m.ops.(anonymous function) as openMysteryItem
https://habitrpg.com/app-55c20289.js:38:294
at g (https://habitrpg.com/app-55c20289.js:8:4596)
at e (https://habitrpg.com/app-55c20289.js:10:12654)
at j.$eval (https://habitrpg.com/app-55c20289.js:8:17252)
at j.$apply (https://habitrpg.com/app-55c20289.js:8:17487)
at HTMLButtonElement. (https://habitrpg.com/app-55c20289.js:10:12715)
at HTMLButtonElement.n.event.dispatch (
https://habitrpg.com/app-55c20289.js:2:6466)
at HTMLButtonElement.r.handle (https://habitrpg.com/app-55c20289.js:2:3241)
at HTMLButtonElement.nrWrapper (https://habitrpg.com/:1:12133)
Empty

you just need to refresh

**Comment by deilann** [comment]
In the future, just respond to your regular ticket, so an email gets sent.

**Comment by Sethycakes** [comment]
I refreshed and still can't seem to find it. I assume it would appear under the "Mystery" category because that's where most of the subscriber equipment is. http://i.imgur.com/s1oTknn.png This is a screenshot of my Mystery equipment post-refresh.

**Comment by deilann** [comment]
No, you need to do a hard refresh and the mystery box should repopulate and
you can claim it there. It won't just appear in your mystery section. If
refreshing isn't working, log out and log back in again. You need to
populate the code that's been added.

**Comment by Sethycakes** [comment]
I got it now, many thanks!
