### ISSUE TITLE
Multiple stage tasks?

### ISSUE THREAD

**Issue by nevans11** [HabitRPG/habitica#529]
I was thinking that there should be an option for tasks to be multi stage (ie require mulitple 'ticks' before they are completed). eg 'take pills twice a day' would require two ticks for the task to be designated complete etc.

Thoughts?

Cheers

**Comment by wc8** [comment]
It would certainly consolidate my daily task list!
Of course, having two tasks for each pill allows for putting tasks in the order of completion, but users would still have that option.

This has been mentioned before #142. There's currently a request in Trello for [Completion Quotas](https://trello.com/c/E5CVJlW6), while the example given in the comments is for weekly completion quotas, perhaps the idea could be extended to daily quotas.

**Comment by wildcate** [comment]
For the normal to-do list, you could just use the checklists that are planned (there's also a Trello card for that).

**Comment by wc8** [comment]
I'd appreciate the list consolidation that would come with multiple boxes for one task

> ☐☐☐☐☐ Eat Meal
> ☐ Exercise 30
> ☐☐☐ Check Stats
> ☐☐ Take Pill _X_
> ☐ Study for 1 hour
> ☐ Take out Trash

versus:

> ☐ Eat Meal 1
> ☐ Eat Meal 2
> ☐ Eat Meal 3
> ☐ Eat Meal 4
> ☐ Eat Meal 5
> ☐ Exercise 30
> ☐ Check Stats morning
> ☐ Check Stats noon
> ☐ Check Stats evening
> ☐ Take Pill _X_ a.m.
> ☐ Take Pill _X_ p.m.
> ☐ Study for 1 hour
> ☐ Take out Trash

However there might need to be a max limit. or there could be word wrap problems:

> ☐☐☐☐☐☐☐☐☐☐Mak…

For reference, the Trello card @wildcate mentioned: [Checklists for To-Do Items](https://trello.com/c/PJ1iJ413)

**Comment by dfjkla** [comment]
I like these suggestions. Here some thoughts cross-posted from another thread:

I have a few tasks which increment in value (Easy>Medium>Hard) at each step. For example, I have "eat fish" as a daily task to encourage me to eat more fish. First time of the week is Easy, second time is Medium, and third fish meal of the week is Hard.

So to refer to wc8's suggestion which is elegant, you could also add arbitrary difficulty levels to each. By default they'd all be the same, but you could edit them if necessary. These tasks should also have arbitrary time periods (daily, weekly, fortnightly, etc.) set by the player.
