### ISSUE TITLE
Missing Forest Walker subscriber set despite being a subscriber from the beginning

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#5290]
Hello, I've been a subscriber since Habit RPG offered the option to subscribe. However, looking at the Time Travelers seems to indicate that I don't have the Forest Walker set of March 2014. I know for a fact that I've been subscribed since before then, because I have the Winged Messenger Set (February 2014) and I also have email receipt for a subscription dated 3/07/14.

User ID: 8a1db51b-01f8-4794-8f9b-a0da605b9bcb
Browser: Google Chrome
Operating System: Windows 7
Console errors: None

**Comment by deilann** [comment]
Refresh. I should have added them to your account.

**Comment by Sethycakes** [comment]
Thank you!
