### ISSUE TITLE
Share > Download Generates Image w/ Level w/o Contrib Color

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5291]
If you click "Share" on your avatar, you can click download, which generates an image like this:

![](https://habitrpg-dev.s3.amazonaws.com/avatar-e7b5d1e2-3b6e-4192-b867-8bafdb03eeec.png)

That's my current avatar. However, I feel if it's going to show the level, it should include the contrib color (aka, mine should be dark blue, not grey).
##

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Sharing will be handled differently when it is implemented again, so I am closing this ticket for now.
