### ISSUE TITLE
Multiple issues with front page avatar sharing

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5294]
#### In game

![selection_018](https://cloud.githubusercontent.com/assets/7059890/7815992/ba95b9ae-0399-11e5-9f85-d9b8a5919381.png)
#### Front page

![selection_019](https://cloud.githubusercontent.com/assets/7059890/7816003/c35324a0-0399-11e5-846e-17d0a55a6642.png)

The front page version is missing the contributor level + colors, class, equipment and total mana and experience. 

Also, something interesting: the front page version displays the stats correctly, while the in-game version lumps the equipment stats into "Class Bonus"  (mentioned in [#5135](https://github.com/HabitRPG/habitrpg/issues/5135#issuecomment-100303275) and [#5165](https://github.com/HabitRPG/habitrpg/pull/5165#issuecomment-100303018)). 
#### In game

![selection_020](https://cloud.githubusercontent.com/assets/7059890/7816123/84b82e92-039a-11e5-9765-26bbadf23ccc.png)
#### Front page

![selection_021](https://cloud.githubusercontent.com/assets/7059890/7816128/8d15197e-039a-11e5-951b-43515a45b9c8.png)
##

**Comment by crookedneighbor** [comment]
I believe the contributor title stuff is happening because the function that creates it is on the app's rootController and not on the static front page's controller. It should be extracted and put into a service.

**Comment by hairlessbear** [comment]
@crookedneighbor Probably related: #5291

**Comment by librarianmage** [comment]
@Alys should this be put on hold / closed due to its inclusion in #7687?

**Comment by SabreCat** [comment]
Pausing this for the frontend redesign.

**Comment by lemoness** [comment]
Sharing will be handled differently when it is implemented again, so I am closing this ticket for now.
