### ISSUE TITLE
Subscribed but did not receive gems immediately

### ISSUE THREAD

**Issue by HerrZog** [HabitRPG/habitica#5295]
Hello )
I'm a subscribed user of HabitRPG, and my auto-payment has been sent 11th May - transaction ID is 0E554854MW398522U. But looks like I still don't have crystals at my account, and its very sad ((. Could you check it please?
Regards,
Anna

---

_edit by admin_:
# What to do if this happens to you:

**Please be aware that when you subscribe you are not actually meant to be given gems immediately. Instead, you are given the ability to buy gems with gold (at least 25 gems per month, more if you subscribe for longer). The wiki's [Subscription](http://habitrpg.wikia.com/wiki/Subscription) page describes all of the subscription benefits, and the [Gems](http://habitrpg.wikia.com/wiki/Gems) page explains the ways to obtain gems.**

**Comment by hairlessbear** [comment]
Please include your user ID (follow the instructions [here](https://github.com/HabitRPG/habitrpg/issues/2760) to locate your ID) so an admin can help you. Note that there are only a few admins, so it may take a few days before they are able to help.

**Comment by deilann** [comment]
As a subscriber you don't get your gems immediately. If you go to the
market and scroll down to the bottom, you'll see you can purchase them with
gold now!

**Comment by HerrZog** [comment]
2hairlessbear - whoops, sorry. My ID is 7ad3b058-a7b2-485d-b829-426f1935faba

**Comment by hairlessbear** [comment]
HerrZog, [this](http://habitrpg.wikia.com/wiki/Subscription#Individual_Subscription) is the wiki page listing subscriber benefits. This is the list, with emphasis added:

> Disables ads.
> **Allows purchase of gems with gold.**
> Retains full history entries (available for graphs and for export).
> Doubles the daily drop-cap.
> Gives a limited-edition monthly item exclusive to subscribers (items do not increase stats).
> Mystic Hourglass after 3-month consecutive subscription
> Supports the developers.

As you can see, you aren't given gems for subscribing, but you gain the ability to buy gems with gold. If you go to the market, at the bottom of the page, you'll see that you can now buy gems for 20 gold a piece.
