### ISSUE TITLE
First Guilds/Party Chat Notification Clicked Does Not Disappear

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5299]
When you click on a chat notification, the expected behavior is that it should disappear. However, lately, the first chat notification I click on does not go away as expected:

![image](https://cloud.githubusercontent.com/assets/6274734/7836584/0cc6992c-0436-11e5-9d15-6379d3b10c2b.png)

There, you can see that I'm in the Legendary Book Club of Habitica. I got there via the notification on the top. Yet it's still there!

Now I move to the ADHDers Guild:

![image](https://cloud.githubusercontent.com/assets/6274734/7836594/28da68fa-0436-11e5-9590-f1e4dfcfa09e.png)

That notification goes away, but the first one is still there, despite having gotten to the guilds page via it.
##

**Comment by hairlessbear** [comment]
I've been unable to replicate this. Is it still happening?

**Comment by deilann** [comment]
Intermittently, yes.

**Comment by hairlessbear** [comment]
After much testing, this finally happened to me (with my party), and I have a theory as to what's happening. 

After I clicked the notification to get to the page, and saw that the notification was still there, I pressed the "fetch recent messages" button and new messages showed up. I think that when the notification isn't cleared, it's because the new messages aren't displayed when you visit the page, causing the message to not be "seen", thus causing the notification to not be cleared.

**Comment by deilann** [comment]
I've had it happen when there were no new messages to be shown.

On Fri, Jun 12, 2015 at 12:38 PM, hairlessbear notifications@github.com
wrote:

> This finally happened to me (with my party), after much testing, and I
> have a theory as to what's happening.
> 
> After I clicked the notification to get to the page, and saw that the
> notification was still there, I pressed the "fetch recent messages" button
> and new messages showed up. I think that when the notification isn't
> cleared, it's because the new messages aren't displayed when you visit the
> page, causing the message to not be "seen", thus causing the notification
> to not be cleared.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5299#issuecomment-111596534.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by hairlessbear** [comment]
Darn. Regardless, I'm almost positive that adding a call to `Groups.seenMessage(k)` to the click action for the [group link](https://github.com/HabitRPG/habitrpg/blob/fac855898f31a3a779c967c34e369fa5215d2b9a/website/views/shared/header/menu.jade#L199) would fix the issue. Not sure how to test this though; I've been trying to recreate the bug every day since you first reported this, and it's only happened once.

**Comment by deilann** [comment]
I can't reliably recreate it myself, but it happens pretty regularly. And
it's always only the first one.

On Fri, Jun 12, 2015 at 1:46 PM, hairlessbear notifications@github.com
wrote:

> Darn. Regardless, I'm almost positive that adding a call to
> Groups.seenMessage(k) to the click action for the group link
> https://github.com/HabitRPG/habitrpg/blob/fac855898f31a3a779c967c34e369fa5215d2b9a/website/views/shared/header/menu.jade#L199
> would fix the issue. Not sure how to test this though; I've been trying to
> recreate the bug every day since you first reported this, and it's only
> happened once.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5299#issuecomment-111610100.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by hairlessbear** [comment]
My best guess is you see it more because you check more often than I do; I only check once or twice a day on average. Thanks for the info; I'll try to look into this further at some point.

**Comment by hairlessbear** [comment]
Also, I just had the bug _not_ happen when there were new messages to display, so my original idea is definitively incorrect.

**Comment by SabreCat** [comment]
Is this still happening since the v3 upgrade? Other than #7393, which was recently closed, I haven't seen anything like this.

**Comment by khipkin** [comment]
This has been happening to me consistently for the last few days.

**Comment by khipkin** [comment]
And it only happens for guilds, not parties.  If I visit my party page first, that notification clears.  Then, for the first guild I visit after that, the notification doesn't clear.

**Comment by SabreCat** [comment]
Yup, just had this happen to me too. Reopening!

**Comment by khipkin** [comment]
Now that the message count notification has been added, I noticed that when I go to the first guild page after the site reloads, the count momentarily flickers down by one but then increments again once the page fully loads.

This makes me think the message for the guild is being dismissed locally only, which then gets overridden by the values on the server when the sync completes.

**Comment by khipkin** [comment]
If I _don't_ fetch recent messages, leaving the notification count artificially high, then cast a buff for my party that shows up in the party chat, the client syncs and the +1 count for my party chat cancels out the fake +1 from the already-read guild chat.

Seems like a race condition where the client tries to update the server while the server tries to update the client; the server wins, so the client is updated with the old value BEFORE the server is updated with the new value.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This should no longer be an issue with the new site, so I'm closing this ticket!
