### ISSUE TITLE
Daily items priorities

### ISSUE THREAD

**Issue by sergiobc** [HabitRPG/habitica#53]
_Edited by wc8: See [Importance, Priority, Duration/Difficulty, Deadlines](https://trello.com/c/4C8w1z5h)_
Hi,

I think it would be great to add user defined priorities to Daily Items.
Now items that have low priorities for me have the same effect on the HP as the most important.
The priorities may be scaled from 1 to 10. Or just the order in the list may define a priority (there's the problem with items with equal priorities then).
Then items with higher priorities have more impact on the HP.

Thanks

**Comment by lefnire** [comment]
task values are determined organically over time. The worse you are at something, the more valuable it becomes (red). The better you are at something, the less valuable it becomes (green). It sounds sketchy at first, but it'll grow on you - this organic value system is actually what led me to build Habit in the first place, so I'm not likely to switch over any time soon

**Comment by sergiobc** [comment]
I understand current system and I like it a lot. 
What I was suggesting is not the replacement of it, but an addition to it.
So, for example, experience for my completed item was calculated to be 0.9 (it is green, so it is not very high).
Then this experience is multiplied then by the priority index. 
Let's assume the priorities scale starts from 0.5 (for 1 priority) to 1.5 (for 10 priority).
My priority for the item was 10.
so the resulting experience would be: 0.9*1.5

**Comment by lefnire** [comment]
I see. KK, will reopen so others can chime in. If it picks up steam I'll put it on the roadmap

**Comment by wc8** [comment]
+1\* (update for clarity)

I like this modifier method more than ranking https://github.com/lefnire/habitrpg/issues/105 because I'm afraid ranking tasks would be time consuming, especially as the list grows longer.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by horusofoz** [comment]
I have already posted this elsewhere but this now seems the ticket the Trello card wa based from.

I think an easy way of implementing priority/importance that would be forward compatible with minimal engineering is to add a multiplier based on priority to the existing equations used to calculate HP loss, XP/GP rewards and shading.

For example a three tiered priority system (my preferred system) would have the current algorithms unchanged for priority three tasks. Priority two tasks would have a 1.5 multiplier applied to HP loss, XP/GP rewards and shading. Priority One tasks would have a 2x multiplier applied.

All new tasks would be priority three by default and the user can increase priority if desired.

This method is easy to use and see the effect it has.

Additionally it would be able to be implemented parallel to the Due Date feature requested elsewhere and perceived as clashing with priority/importance setting.

**Comment by horusofoz** [comment]
Suggestion enhancement not already noted from @ZequeZ under #189 

"Also, with the party system we could moderate our tasks by averaging. So let's say I set one tasks to difficulty 5, but a friend of mine thinks is a bit far fetched, so he set it's to 3. So it averages at 4."

**Comment by wc8** [comment]
[Party Moderating](https://trello.com/c/2gTPmhHc). Added direct link to main Trello card. [I had a "little" setback to updating Trello, and adding in relevant links, sorry.]

**Comment by wc8** [comment]
Trello card here [Importance, Priority, Duration/Difficulty, Deadlines](https://trello.com/c/4C8w1z5h)
It may need to be broken up into parts, with links between the cards, but I wasn't quite sure where the best breaks would be. I probably will move Deadlines & Dates to its own card though.

**Comment by Pandoro** [comment]
So lefnire did a first implementation of this feature. Pretty much keeping it very related to the current outline of the task. However I, and I think other people as well, would like a bit more flexibility than the current 3 levels of urgency.

I asked Tyler why he did not just use a field to put a number, he explained that user tests have shown that people make better use of the feature of they have a fixed setup. He referred to a system where you could set something between 1 and 5.

I would personally like 1 to 5, maybe even 1 to 7 (Where the the actual multipliers are not equal to the levels.) To get a better customizability. Some discussion and all of your opinions would be very helpful here! :)

**Comment by sergiobc** [comment]
It is great that this feature appeared on the site. 
The most important for me would be the possibility to reduce the importance of the task as well as to increase it. 
So, with the current system it would be logical to have these multipliers: I - 0.5, II - 1, III - 1.5.
The scale of 3 levels is also seems insufficient. I would like to have a scale 1-10, at least 1-5 but not less. With the middle of the scale having a multiplier of 1.

**Comment by lefnire** [comment]
we were going from tried-n-true: http://blog.astrid.com/key-words-for-creating-tasks/ . 1-5 is quite possible, it's the pivotal tracker system (the project pandoro said i mentioned). Part of the usability study was try to use a small range, odd numbers. so 5 will be our max if we decide to increase

**Comment by StanLindsey** [comment]
Considering these are comments of a feautre and not a bug; lets keep the discussion to Trello:

[Importance, Priority, Duration/Difficulty, Deadlines](https://trello.com/c/4C8w1z5h)

**Comment by codinatrix** [comment]
I would like to have four different To Do Lists: ASAP, Soon, Whenever, and Someday. Then the organic system adjusts accordingly. So if I haven't done it after 2 weeks and it was marked ASAP, it should turn red and maybe I should even lose health. If it was marked Someday, then it should still be green.
