### ISSUE TITLE
Cant login 

### ISSUE THREAD

**Issue by Tonqe** [HabitRPG/habitica#530]
when I try to log in I get the message: "User not found with that username." I'm sure that the credentials are correct...and if I try to register with the same credentials tells me: "Username already taken" or "email already taken"
HELP! :(

**Comment by lefnire** [comment]
hey @mykill18 , check out the bottom of https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account ("User not found")

**Comment by ghost** [comment]
@mykill18 , I had the same thing happen... but the capital lettering in my username was throwing me off. I'm not accustomed to case sensitive usernames.

**Comment by lefnire** [comment]
I added an issue here https://github.com/lefnire/derby-auth/issues/29

**Comment by horusofoz** [comment]
@mykill18 Is this still happening?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
