### ISSUE TITLE
Inn Warning Showing Despite not Being in the Inn

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5301]
![screenshot from 2015-05-27 14 19 36](https://cloud.githubusercontent.com/assets/6274734/7847889/99221c12-047b-11e5-8499-bfa59ca09abc.png)

As you can see from my avatar I am not in the inn. However, last time I signed into HabitRPG on this computer I was. Likely this is a caching issue, however, I think it's something that needs to be addressed because it could severely mislead users and scare them into thinking they are in the inn when they are not. This could lead to them either worried that they they are in the inn, despite other tabs showing they aren't. I know that'd cause me some distress. On the other hand, it could lead some users to believe they really _are_ in the inn, which would be an unpleasant surprise if that's where they want to be and they wake up taking a lot of damage...

**Comment by Alys** [comment]
I think this will have been fixed by https://github.com/HabitRPG/habitrpg/commit/dbbd03e6cb0d574eb445b43c18a5e865e25d46fc so I'm closing this, but we can reopen if it happens again.
