### ISSUE TITLE
Occasionally being directed to alternate Tavern page (?)

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5303]
Sometimes when I go to the Tavern, I end up at `https://habitrpg.com/#/options/groups/guilds/habitrpg` instead of `https://habitrpg.com/#/options/groups/tavern`. This makes the page behave strangely in multiple ways, all of which I believe are due to the site trying to format the Tavern like a normal guild instead of, well, the Tavern.
![tavern screenshot](https://cloud.githubusercontent.com/assets/7059890/7876047/4b8352c8-0593-11e5-9265-95dacc26914b.png)

As you can see, Daniel, Resources, and Player tiers are missing, and a members list and a normal guild description area are added.

**Comment by hairlessbear** [comment]
I forgot to mention that I have yet to figure out how to reproduce this consistently. It just happens sometimes; I haven't found the pattern yet.

**Comment by Alys** [comment]
Are you a member of the "Tavern" guild (gid habitrpg)? If so, clicking on the Tavern button in your list of the guilds that you have joined will cause you to go to the guild view instead of to the proper Tavern view. 

We can probably fix this most easily by adjusting the guild list page so that gid habitrpg never appears in it, and then (optionally) running a database migration script to un-join the current 40-odd members. Whether we want to do that is another question. Perhaps those people like having the guild view of the Tavern. It's been like this forever, and this is only the second comment I've seen about it. It's probably best to change it though.

**Comment by mayajosyula** [comment]
I just wanted to add that this happens to me whenever I go to the Tavern from the Chrome chat extension (by using the link at the top of the Tavern chat window). I'm not a member of the Tavern guild and I haven't been able to get to the "Tavern guild" page any other way.

**Comment by hairlessbear** [comment]
@agentx999 Ah-ha! That's how I've been doing it! Thank you! 

@Alys I'm not a member of the Tavern guild; I've been getting to it via the method @agentx999 described.

**Comment by hairlessbear** [comment]
@Alys Should I close this since the issue is actually with the chat extension, or leave it open to encourage someone to remove the ability to view the Tavern as a normal guild?

**Comment by crookedneighbor** [comment]
Please leave it open. In my opinion, if someone navigates to the guild url with the habitrpg id, it should redirect to the tavern page.

**Comment by hairlessbear** [comment]
Sounds good to me. I might take a crack at implementing that tomorrow if no one else has done it by then.

**Comment by deilann** [comment]
I disagree actually. I like being able to navigate to the Tavern that way
because when it's treated like a guild it auto-updates.

**Comment by crookedneighbor** [comment]
Wait, guilds auto-update? Like, chat messages appear automatically, or do you mean something else?

**Comment by deilann** [comment]
When you visit the Tavern, you have to click "Fetch New Messages" to make
the new messages show up. When you visit a guild, the latest messages
automatically appear.

**Comment by crookedneighbor** [comment]
Interesting. To me, that sounds more like a bug in the tavern versus a feature in a guild.

**Comment by deilann** [comment]
The Tavern does that on purpose for performance reasons.

**Comment by crookedneighbor** [comment]
Yeah, I was thinking of it on the client end, not the server end. On the client end, it wouldn't be any more resource intensive than a normal guild, but obviously on the server end, it would be a lot more resource intensive.

**Comment by hairlessbear** [comment]
@deilann @crookedneighbor Is there a consensus on this? Should the behavior be kept or changed? If it should be changed, I can do a PR, but if it's staying as-is, I'll close this.

**Comment by Alys** [comment]
I don't think the current behaviour is a problem. I've only ever seen one person confused by it (they asked about it in the Tavern), and if it's useful for some players, I think we might as well leave it as it is.

**Comment by crookedneighbor** [comment]
Will possibly revisit when we overhaul the chat system to be real time.
