### ISSUE TITLE
gifting a subscription fails, maybe because a previous subscription had existed in the past

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5309]
A player reported to us via the admin@habitrpg.com email address that when they tried to gift a subscription to their sister, it failed. They tried twice with the same result so I think it was not a temporary glitch. My current theory is that it might have failed because their sister had had a subscription previously (now expired) and **possibly** that got in the way of the new gift subscription being created. After the second gift subscription attempt, their `purchased.plan` data was:

```
    "purchased" : {
        "plan" : {
            "customerId" : null,
            "dateCreated" : ISODate("2014-05-10T05:30:31.923Z"),
            "dateTerminated" : ISODate("2014-09-01T00:00:00Z"),
            "dateUpdated" : ISODate("2015-05-10T13:42:08.129Z"),
            "paymentMethod" : null,
            "planId" : null,
            "consecutive" : {
                "trinkets" : 0,
                "gemCapExtra" : 0,
                "offset" : 0,
                "count" : 0
            },
            "mysteryItems" : [
                "weapon_mystery_201505",
                "head_mystery_201505"
            ],
            "gemsBought" : 0,
            "extraMonths" : 0
        },
        "txnCount" : 1
    }
```

`dateTerminated` had not been updated. I fixed the sister's subscription manually, so this isn't an urgent problem for them.

I tried something similar with my own test account and got similar results. The dates for an expired subscription had been:

```
            "dateTerminated" : ISODate("2015-04-30T00:54:59.845Z"),
            "dateUpdated" : ISODate("2015-03-30T00:54:59.846Z")
```

and when I gave a new subscription to that account they were:

```
            "dateTerminated" : ISODate("2015-05-30T00:54:59.845Z"),
            "dateUpdated" : ISODate("2015-05-30T01:40:04.754Z"),
```

I.e., the dateTerminated was the same day that I gifted the subscription on.
##

**Comment by paglias** [comment]
@Alys still an issue?

**Comment by Alys** [comment]
Unless the subscription code has been substantially rewritten to have new behaviour, rather than just refactored, I think this would still be an issue. I've seen other examples of it occasionally over the months, reported by email (I fixed them each manually).

**Comment by Alys** [comment]
I haven't seen this reported for a while so I'm closing this. It can be reopened if we see more reports of it.
