### ISSUE TITLE
Feature request: Deleted account restoration e-mail

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#531]
If accounts are going to be purged when they've been inactive too long, you could put their tasks and level and all that in a text file and append a cryptographic signature to it in order to verify that it hadn't been tampered with when they used it later. The text would be both in the body and as an attachment, in case attachments are deleted by the person's e-mail system.

Then, the Create New Account screen would have an option to restore from a text file. Perhaps it could be called an account restoration file instead of a text file, though.

This could also be done whenever anyone deletes their account in a sorry to see you go e-mail. That way, if they realize it was a mistake or they have an annoying roommate, it would be recoverable. If they actually wanted to just leave, deleting an e-mail is pretty easy.

**Comment by lefnire** [comment]
Registered account are never purged, accounts are only purged if they were never officially registered and become inactive. When you first visit the site as a newcomer, it creates a "dummy account" for you to play with to see if you even like HabitRPG. Then when you decide "yes", you click "Register" in the top right - and link it to an email address or Facebook login. If that 2nd step was never taken, and the user never comes back (aka, they decided "No") - then that dummy account is purged after a week. As such, there's nothing we can tie these dummy accounts to in order for them to restore it.

**Comment by Olathe** [comment]
Oh, I see. I'd thought that you meant in issue 220 that you would delete fully-formed accounts that hadn't logged in for a month.
