### ISSUE TITLE
No markdown in notifications

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5310]
I'm pretty sure this only matters when you cast a spell on a task with Markdown in the title, but there may be other use cases that I'm missing.

![notification no emoji](https://cloud.githubusercontent.com/assets/7059890/7895754/47239632-066c-11e5-9d2c-fed30d15555a.jpg)
![notification no markdown](https://cloud.githubusercontent.com/assets/7059890/7895755/49094370-066c-11e5-8f17-458e3c0e54bb.jpg)

**Comment by ghost** [comment]
Just for the sake of connection https://github.com/HabitRPG/habitrpg/issues/2927

TBH, I don't like the wording of the issue reported by myself previously, so that one may be actually closed in favor of this one.

Waiting for a moderator's opinion.

**Comment by Alys** [comment]
Thanks @GitHubSphinx. We should have listened to you last year. :) I'll keep this new issue open since the other one has extra conversation in it.

**Comment by hairlessbear** [comment]
Closing due to #5313 fixing the issue.
