### ISSUE TITLE
Guilds should have a new, plain-text field for a description on the guild list page 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5311]
_Do not start work on this until approved by @lemoness. This message will be removed when it is approved._

Currently, when you create a guild, you write a "Description", which can be many lines of text, with markdown. The Description is shown on the guild's own page (which is good), but also on the list of all guilds, which can look bad when the description is too long or has markdown - see https://github.com/HabitRPG/habitrpg/issues/5273 for examples.

As discussed in https://github.com/HabitRPG/habitrpg/pull/5277, we want to create a new field for guilds that can contain a limited amount of text (perhaps 500 characters?). This field will be displayed on the [list of all guilds](http://localhost:3000/#/options/groups/guilds/public). It will not be displayed on the guild's own page.

For a public guild, the new field should be mandatory (so when you create a guild or edit an existing one, you are forced to enter the text), however if the guild does not have any value for that field, the "Description" is displayed on the list of all guilds (that's to cater for all the existing guilds which initially won't have this field).

The new field should have a message next to it explaining that markdown will NOT be enabled. If the guild creator enters markdown, it will show up on the list of all guilds as raw markdown, just as you see now (so, ideally, the guild creator will NOT enter markdown - let's hope they read the message).

Emoji should be enabled.

The "Description" field and the new field should each have a message explaining what they are for. Something about how the new field is intended to advertise your guild to potential members, while the "Description" field is to be shown to people who have already joined.

For private guilds, the new field should be optional or disabled since private guilds never show up on the list of all guilds.
##

**Comment by Alys** [comment]
@lemoness (and others) : All of that is just my initial thought about how this could work. Please state what changes you want!

**Comment by lemoness** [comment]
So, right now there are actually two ways to display information - in the
Description that displays on the Public Guilds page, and in the Message
from Group Leader (when you edit a group that you own), which only displays
within the Guild. Is there a way that we can consolidate this preexisting
system into the new proposal?

One example of how to do this (NOT necessarily the best way):
1. Descriptions renamed "Promotional Descriptions" and capped at 500
   characters with no markdown for new Guilds.
2. Message from Group Leader added to Create Guild page, with descriptions
   of the differences between the two.
3. Old Guilds with a separate Description and Message stay exactly the
   same. If they edit the Description, the new rules apply.
4. Old Guilds with a Description only have it copied to Message, so it
   displays identically in both places. If they edit the Description, the new
   rules apply.

Thoughts about this?

**Comment by deilann** [comment]
I'd really prefer that there's still a markdown enabled description that
doesn't go above chat. (Where the guild info is currently placed.)

Reasons for this: many guilds would want to have longer descriptions,
including resources, and images, which don't fit as well in the rather
narrow message from guild leader and that message pushes down chat.

However, I do agree that the "message from group leader" should be added to
the create guild page.

**Comment by Rbrinkley** [comment]
Maybe have the box for the guild description at a set size and if the markdown gets too big the box will scroll. It would likely make those who are trying to have the markdown enabled to try and fix their description to that size and avoid making giant banners at the cost of making users having to go through the trouble of scrolling. Just an idea. What do you guys think of that? The box doesn't have to be small either. Would be a reasonable size.

**Comment by librarianmage** [comment]
Shouldn't this be closed?

**Comment by lemoness** [comment]
It should!
