### ISSUE TITLE
Challenge boss's damage taken gets SMALLER every day!

### ISSUE THREAD

**Issue by DSDragon** [HabitRPG/habitica#5312]
A few days ago, the health bar of The Snackless Monster said that I had done a total of 217/300 damage to it.  Yesterday, it said I had done 203.  Today it says 194.  That is VERY BAD, especially since I have consistently done it damage, instead of it doing me damage.  Please fix this bug that makes the damage go down instead of up!
![image](https://cloud.githubusercontent.com/assets/12192688/7898846/5f63bd0c-06db-11e5-85f0-c4564d14cfe3.png)

**Comment by ghost** [comment]
@DSDragon The bar shows the remaining health of the boss. You can see the amount of damage dealt to the boss by you or other party members (if there are any) in the party chat:
`DSDragon attacks The Snackless Monster for XX.X damage...`

So it's the expected behavior.

**Comment by deilann** [comment]
Yes, the health bar is the health _remaining_, not the damage you've dealt. It starts at 300 and goes down.

**Comment by DSDragon** [comment]
It's always been the other way before. In previous quests, it was the
amount of damage done.

**Comment by Alys** [comment]
You might have done only collection quests in the past. In the quest box for collection quests, it shows how many items you have collected (so the number goes up over time). For boss quests, the number has always been the boss's health and so it has always gone down.
