### ISSUE TITLE
Exported To-Dos not readable

### ISSUE THREAD

**Issue by lpezzullo** [HabitRPG/habitica#5317]
I've tried opening both the CSV and JSON export files in Sublime 2 and TextEdit, and consistently, the names of my to-dos are encoded as numbers with long decimal points. My quest achievements are preserved as readable text - it's just the to-dos that are numbers. Is this a problem on my end?

**Comment by crookedneighbor** [comment]
Can you copy and paste a selection of each as a comment here? Feel free to anonymize any personal details if present. 

My json export has two todos sections. A main one where everything is normal, and the details of the tasks display normally. The second one is bested under history, and just shows the value changes over time (this is what I expect you are seeing)

I'd recommend using the text search feature in your text editor and look for `todos`

**Comment by Alys** [comment]
I'm closing this because we can't investigate without the requested details, but it can be reopened if it's still happening.
