### ISSUE TITLE
Feature Request: Educational Usage Mode

### ISSUE THREAD

**Issue by loganblue** [HabitRPG/habitica#532]
I'm a special ed teacher and I work with a behavior analyst everyday who uses many of the lifestyle monitoring and and rewards techniques that are available to educators today. Like anything else used, however, motivation for kids to use a program to track themselves is lacking. We try new products all the time, but we haven't seen anything like HabitRPG that could benefit students. I was a Kickstarter backer. I'm a gamer myself and I wanted it to help me get myself motivated, but once I started using the program, I realized how much it could benefit kids and those educators who are willing to try something new to get through to those kids. 

While I know that the features are far from completed, I would propose to you that creating either a version or a separate mode for educational use could potentially elevate this project past the singular user and open it to the educational market. I don't have to tell you how financially beneficial such an application would be. Whether it be a mode difference or a separate, but similar product is up to you of course. It would need a hierarchy control, so that the educator can monitor the students' activities as well as give credit for activities not able to be accumulated by the students themselves (no cheating that way). And of course, the educator would be the only one with access and control of a whole group of student users, being the only ones who can give out physical or virtual rewards. A similar app which has been very useful for teachers but not as interactive for students is iReward. http://goo.gl/Jlb2S . Just throwing it out there. If properly implemented, it could be huge for you. 

Any thoughts?

**Comment by lefnire** [comment]
Hey @loganblue , this is absolutely on our agenda - actually how we plan to monetize Habit. See No. 2 specifically of https://github.com/lefnire/habitrpg/wiki/Business-Model

**Comment by loganblue** [comment]
I totally missed that. My bad. If you need any special Ed services help or advice let me know. I'm sure that this would be huge.

**Comment by Pandoro** [comment]
@loganblue I would actually be interested to get a general idea of what you would mean by such a version. Of course you already said that you want to have control etc. But what about the general theme of the game?

I guess not everyone is into the RGB theme and I guess in such a theme buying pets with tokens would not really be desirable. Would you also allow students to play with their existing habitrpg account? Meaning they could just keep on playing with their current account, but you could add special rewards that only you can control? 

It would be good to see your take on how the game would need to be modified or which features are really lacking right now.

**Comment by loganblue** [comment]
I'll be honest, I haven't had enough time to really play with it. I'm still trying to understand how everything works. I'll give you some ideas soon.

**Comment by wc8** [comment]
I think this falls under the [Manager Accounts](https://trello.com/c/kGFZUYH8) suggestion.
