### ISSUE TITLE
Failing to Update Values when Leveling Up

### ISSUE THREAD

**Issue by diogo-cruz** [HabitRPG/habitica#5320]
The values of mana, health and experience fail to update when I try to use the skill Burst of Flames to level up (since I'm close to the maximum experience for the current level). After I use it and click on a daily, it does not update even when I reload the page or click Sync. The dailies continue to show the green square when I hover over them, and the cursor continues to show the little plus sign next to it, so it seems that it gets stuck on "daily choosing mode" for the skill.
To clarify, the values "on screen" get updated, but if I try to do anything else, like going to the Inventory or Syncing they return to the previous values, as if I had not used Burst of Flames.
I'm not sure if it has to do with that, but I used Burst of Flames about 8 times in a row. It was when I was going to use it for the ninth time, to level up, that the problem appeared.

**Comment by deilann** [comment]
Are you using it to get to level 15, 30, 40, or 60?

**Comment by hairlessbear** [comment]
For what it's worth, I just used Burst of Flames 10 times in a row to get to level 79, and didn't experience this issue.

**Comment by diogo-cruz** [comment]
Yes, to level up to level 40. I've tried again today, and it still doesn't work. It has the same issues.

**Comment by Alys** [comment]
It's probably this issue: https://github.com/HabitRPG/habitrpg/issues/4986

Do you see an error message on screen like "Error Cannot set property 'drop' of undefined"?

**Comment by deilann** [comment]
Yes, this is a known issue for levels 15, 30, 40, and 60 because of the
interaction with the quest scroll drop on these levels. You can simulate it
by using Fix Character Values in Settings > Site to add on the XP and
reduce your MP. Then trigger any task to level up... you can even create a
one time dummy task to do it. Sorry this hasn't been fixed yet.

**Comment by diogo-cruz** [comment]
I think it's that. The first time I tried to use the skill that message appeared. I was able to level up using a habit now (and received the quest).

**Comment by Alys** [comment]
Thanks for letting us know.

When you're reporting bugs, it's always worth telling us if there was an error message, even if you can't remember exactly what it said. Letting us know as much as you can remember helps us solve errors faster.
