### ISSUE TITLE
New tutorial pops up for existing users, and can't be avoided

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5321]
I'm assuming this is a result of #5307 being merged. I have all of my tasks set up how I like them, so I have no need to go through the tutorial, but there's no way to close it. You have to click "I'm ready", which I don't want to do because I don't know whether it'll force changes to my set up.

pinging @SabreCat for help

**Comment by crookedneighbor** [comment]
Just click "I'm Ready". It doesn't make any changes. (Just tried it myself)

**Comment by hairlessbear** [comment]
Awesome, thanks @crookedneighbor! Should I leave this open for users with similar concerns to see, or just close it?

**Comment by SabreCat** [comment]
Leave it open. It wasn't meant to show up for existing users.

**Comment by Alys** [comment]
I've been running a migration to set a flag for all existing users so that they won't see the new screen. All users who logged in within the past five days have been done. The remainder are running now.

**Comment by crookedneighbor** [comment]
Since the people who are active on the site have been taken care of, I'm going to close this now.

**Comment by Alys** [comment]
All users done now.
