### ISSUE TITLE
Drop not rolled back

### ISSUE THREAD

**Issue by gsalvadi** [HabitRPG/habitica#5322]
When I clicked a task from the list, I got XP,Gold and a Hatch Potion. As it was a check done by mistake, I went to the list of tasks done and unchecked it. In rollback, the hatch potion did not disappear. I just want to record this though this is not a critical bug.

**Comment by Alys** [comment]
Already reported at https://github.com/HabitRPG/habitrpg/issues/4626
Please see the first comment that explains why this is not considered to be a bug.
