### ISSUE TITLE
Beast Master progress count incorrect

### ISSUE THREAD

**Issue by cyChop** [HabitRPG/habitica#5328]
I found a discrepancy when displaying the Beast Master progress.

I have 8 pets (not counting quest pets).
In my user stats, I have the following:
![stats](https://cloud.githubusercontent.com/assets/1841583/7923379/e2cacf18-08b2-11e5-9df5-e19cfa96ff00.png)

Yet in the inventory, I have this:
![inventory](https://cloud.githubusercontent.com/assets/1841583/7923378/e2c90e4e-08b2-11e5-9779-d029caf56cbc.png)

User ID: `1d80ec78-7fb7-4d8b-b34c-9f58569cdb2d`
Chromium/Windows 7, no JS error ; extensions which could be of consequence: Ghostery, HTTPS Everywhere

**Comment by Alys** [comment]
Please reload the inventory page. Does it still say 6 / 90?

FYI for devs:

```
{
    "_id" : "1d80ec78-7fb7-4d8b-b34c-9f58569cdb2d",
    "items" : {
        "mounts" : {
            "MantisShrimp-Base" : true,
            "Turkey-Base" : true,
            "Mammoth-Base" : true,
            "Dragon-Red" : true,
            "Wolf-Shade" : true
        },
        "pets" : {
            "MantisShrimp-Base" : 5,
            "Turkey-Base" : 5,
            "Wolf-Base" : 39,
            "Wolf-Shade" : -1,
            "Wolf-Veteran" : 5,
            "JackOLantern-Base" : 5,
            "Mammoth-Base" : 5,
            "Seahorse-Shade" : 5,
            "Wolf-Skeleton" : 22,
            "Dragon-Red" : -1,
            "Wolf-Red" : 5,
            "Wolf-White" : 30,
            "PandaCub-Base" : 5,
            "PandaCub-CottonCandyPink" : 30
        }
    },
```

**Comment by cyChop** [comment]
Nope, the problem seems to be fixed. Thank you!

**Comment by Alys** [comment]
Thanks for letting us know!

It's always worth doing a reload whenever you see anything odd because that will fix any temporary glitches.

**Comment by cyChop** [comment]
As a developer myself, I am aware of the old tricks. I thought I did some reload (not sure I forced a cache-cleaning, though). I tried on another computer this morning, so no cache problem possible. Thank you anyway (for the answer and the great habit tracker for those who respond well to gamification like myself)!
