### ISSUE TITLE
HabitRPG won't open in browser at all

### ISSUE THREAD

**Issue by pmeinertzhagen** [HabitRPG/habitica#5332]
I've had this problem for well over a week now. When I try and hit the "play" button on the HabitRPG website on both Safari and Chrome, the app doesn't open - there is a blue bar that quickly moves across the top of the browser, indicating something loading, but the screen stays the same. However, the web app does open on Safari on my iPad, which is where I'm having to use it currently.

**Comment by pivotal-rebecca** [comment]
Are there any red messages in your console when this happens? To view the console, right click anywhere in Chrome and choose Inspect Element. Choose 'Console' from the tabs at the top of the opened interface. Paste any output you see in your console here.

**Comment by Alys** [comment]
@pmeinertzhagen I'm closing this because I'm assuming that the problem has disappeared, but if it's still happening for you, please reply and follow the suggestions from @pivotal-rebecca. Tell us if you're having trouble getting to the Console and we can help!
