### ISSUE TITLE
Double Damage in quests

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#5334]
The last two quests I was in, I did double damage to the boss.  Two lines appeared when I logged in, each detailing exactly the same amount of damage.  And it definitely did actually apply.  Today I killed the boss pretty much single handedly.  My ID is e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by Alys** [comment]
Hi @Memry. We're not sure what causes this but you can follow the progress of the bug fix in https://github.com/HabitRPG/habitrpg/issues/2805. It seems to be intermittent and rare.
