### ISSUE TITLE
sudden death on system clock change

### ISSUE THREAD

**Issue by ibcbooth** [HabitRPG/habitica#534]
I moved my system clock from today's date feb-27th-2013 to feb-1st-2013 (and back again) with HabitRPG up and my character instantly died.

I used the restore and rollback features to get the character back to its pre-death state.

**Comment by Pandoro** [comment]
Hmmm, this of course is an annoying thing :( I'm sorry that occurred to you. Luckily you were quickly able to restore your character. Since it is somewhat of a border case, since you probably will not change the date frequently, I think this will not have a high priority, but hopefully this will be fixed at some point!

**Comment by wc8** [comment]
Just a note: I know someone who's computer clock resets to Jan 1, 2008 or so anytime the battery runs out.
It's still an unusual case, though.

**Comment by horusofoz** [comment]
Is this something we can fix? Use the server time?

**Comment by lefnire** [comment]
this is going to be difficult to fix, and is extremely edge case. I hate to say it, but i don't think we're going to be addressing this ticket this year - use the "Restore" tool to get your character back on track.

We can't use server time for user cron. Server v Client cron is something I've wrestled with for as long as habit has been under development, and the definite conclusion is cron has to be run on the client. I have a buried workflowy node with my notes i can dig up if needs be.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
