### ISSUE TITLE
Tasks in To-Do List are repeating themselves

### ISSUE THREAD

**Issue by zebular13** [HabitRPG/habitica#5342]
Around 4pm PDT I added some new tasks to my to-do list. When I got back to my computer I was shocked to see that not only had my character died (she was at 40 health beforehand), two of the new tasks I had added had replicated themselves ad infinitum (eg, more than 20x)
I checked the extra ones off and kept playing (I got back to my original level) but it happened again tonight around midnight with three more tasks. They each replicated themselves once.

**Comment by Alys** [comment]
I answered your question about that in the Tavern just after you first asked it there four hours ago:

"@zebular13 : I'm sorry about that! I have heard of it happening to others but it's not common. You can restore your lost level, gold, etc by going to Settings (the gear-shaped icon) -> Site -> Fix Character Values. For the duplicated tasks, try deleting them starting from the ones closest to the bottom of the page. If you delete from the top down, it usually doesn't work. I'm sorry it's such a nuisance! We haven't yet worked out what causes it."

When you ask questions in the Tavern or the Newbies guild, you'll almost always get an answer, so you very rarely need to ask a second time either there or somewhere else. Check back after several minutes or a few hours and either scroll through chat to find highlighted posts (anything with your name in it will be highlighted), or search for your name using your browser's find feature.

**Comment by Alys** [comment]
The issue has been reported before in https://github.com/HabitRPG/habitrpg/issues/4773. If you'd like to follow the progress of the investigation, you can subscribe to notifications from that issue.
