### ISSUE TITLE
Some issues on source English

### ISSUE THREAD

**Issue by SnowCrasher** [HabitRPG/habitica#5345]
Hello! I hope I'm doing this right. It's my first time posting anything on GitHub so I'm a little lost here. XD
I was translating in Korean on Transifex (known as NaYa there) and I noticed some grammar and term issues, and @paglias told me to report here, so here I am.

**1.** There are a couple occasions where "**Options**" is mentioned in an instruction, but in the game there is no "**Options**" because it is displayed as "**Menu**" instead when the main toolbar is collapsed (closed). Shouldn't the instructions also say "**Menu**" then to be consistent, or vice versa? Below are the lines I've found so far that contain this word.

_habitrpg/common/locales/en/generic.json
Line 73 "untilNoFace": "Until we add Facebook, use your UUID and API Token to log in (found at https://habitrpg.com > **Options** > Settings).",_

_habitrpg/common/locales/en/quests.json
Line 6 "questSend": "Clicking \"Invite\" will send an invitation to your party members. When all members have accepted or denied, the quest begins. See status under **Options** > Social > Party.",_

**2. Misuse of comma** (Hate to be a grammar nazi, but other translators have also commented on it, so a lot of others are probably also botered by it.)

_habitrpg/common/locales/en/character.json
Line 51 "battleGearText": "This is the gear you wear into battle, it affects numbers when interacting with your tasks.",_

This should not have a comma, but a semicolon or a period instead, like below:
"This is the gear you wear into battle. It affects numbers when interacting with your tasks."

**Comment by hairlessbear** [comment]
`untilNoFace` isn't used anywhere, which makes sense, because HabitRPG has Facebook integration, so the message isn't needed. Maybe it should be removed. `questSend` seems to be the only other instance of "Options" being used like this; [search results here](https://github.com/HabitRPG/habitrpg/search?utf8=%E2%9C%93&q=options+path%3Acommon%2Flocales%2Fen).

**Comment by crookedneighbor** [comment]
Good work. 

Yes, untilNoFace should be removed.

Yes, Options should be changed to Menu

Yes, that should be a period or semicolon; I vote semicolon!

I'm advertising this issue in the [Aspiring Coders Guild](https://habitrpg.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f)

**Comment by hairlessbear** [comment]
@crookedneighbor I think "Options" should just be removed in this case. There are no instances of instructing users to click on something by clicking "Menu -> [item]" ([search results](https://github.com/HabitRPG/habitrpg/search?utf8=%E2%9C%93&q=menu+path%3Acommon%2Flocales%2Fen&type=Code)). The phrasing is always the name of the tab, then the name of the submenu item (in this case, "Social > Party").

**Comment by crookedneighbor** [comment]
Sounds good to me.

**Comment by SnowCrasher** [comment]
Good to see that the issues are addressed right away! You guys are awesome.
I found another one.

[https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/defaultTasks.json](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/defaultTasks.json)
Line 4  `"defaultHabit1Notes": "Sample Good Habits: + Eat a vegetable +15 minutes productive work",`

_(Edit: + is for positive, not bullet like I guessed earlier, but the issue still stands)_
I'm pretty sure there's supposed to be a space between `+` and `15`, but when I try to correct that on my translation and write "+ 15 minutes" it gives me an error saying the translation is missing the number "+15".
Aside from the need for a missing space, I guess it thinks positive number is different from natural number? o_O

**Comment by crookedneighbor** [comment]
I think you're write. It needs to be corrected in the English version before it can be done in the translation.

**Comment by mayajosyula** [comment]
I can probably do this right now, if that's okay?

**Comment by hairlessbear** [comment]
@agentx999 get to work! ;) In all seriousness though, you don't need to ask
for permission to work on issues. If no one else is working it, just claim
it as your own so others know it's being worked on. Your help is greatly
appreciated.

**Comment by mayajosyula** [comment]
Got it, thanks! Sending pull request momentarily, haha. ^^

**Comment by GitHubSphinx** [comment]
Adding 2 cents from translators: front.json:

`"dreimQuote": "When I discovered HabitRPG last summer, I had just failed about half of my exams. Thanks to the Dailies&mldr; I was`

&mldr; is not needed
