### ISSUE TITLE
Messed up dailies and to-dos

### ISSUE THREAD

**Issue by cyChop** [HabitRPG/habitica#5346]
I've encountered a quite nasty bug. The to-dos and dailies I created in the latter days (yesterday and maybe the day before) have been multiplied, and I cannot delete them.

I checked the JSON being passed, and tasks indeed appear several times. I have emptied the cache, tested under Chromium and IE but the problem is still the same.

Not sure I can do something more to help, but I'll be glad to.

User-ID: 1d80ec78-7fb7-4d8b-b34c-9f58569cdb2d

**Comment by cyChop** [comment]
OK, I can delete the duplicates, I only have to refresh the whole page between each deletion.

**Comment by cyChop** [comment]
Tags were affected too.

**Comment by hairlessbear** [comment]
This is a duplicate of #4470/#4773. Although there isn't yet a way to stop the bug from occurring, if you delete the duplicated tasks starting at the bottom of the list, they should be removed properly.

**Comment by cyChop** [comment]
OK, I did not see the original. Closing this issue as duplicate. Thanks for letting me know.
