### ISSUE TITLE
Hatched pet disappeared

### ISSUE THREAD

**Issue by Weyrsinger** [HabitRPG/habitica#5347]
Today I hatched a cotton candy blue wolf. I got the normal message saying it hatched and to go to the pet page to view it, but when I went to view it it wasn't there. So now my hatching potion and egg are both gone, and no pet to show for it.

**Comment by Alys** [comment]
Unfortunately we can't help you without being able to identify your HabitRPG account. Please go to Help -> Report a Bug and see the instructions there for how to find your User ID.

Before you do that, please reload both the pets page and the inventory page. That might make the pet or the egg and potion reappear.

**Comment by Weyrsinger** [comment]
I've tried reloading, and opening the page on different devices; it didn't help. My User ID is f253cc36-1630-4db5-99e1-1e4cd07f89ee

**Comment by Alys** [comment]
@Weyrsinger I've given you the pet. Sorry about the trouble! Post here if you still can't see it.
