### ISSUE TITLE
All non-challenge tasks disappeared

### ISSUE THREAD

**Issue by skybluefusion** [HabitRPG/habitica#5348]
I did all the troubleshooting I could figure out to try. Tags are cleared. Site has been reloaded, synced multiple times. The data page has been giving multiple errors as well. I've not left all but one challenge which leaves me with only one daily, one habit. No to-dos. I am EXTREMELY frustrated. I have become dependent on HRPG to guide me through my day, especially since my cognitive abilities are often largely messed up by seizures and cognitive fog from the chronic pain issues I have. What did I do to cause all my tasks to disappear and is there a way to get them back? 
My user id is  8d1a2e31-3f04-4204-98ce-452210cde59a
What other information do you need?
Thank you for any assistance you can provide.

**Comment by Alys** [comment]
Can you please tell us how many hours (or days) ago the tasks disappeared? We can use this information to find them in a database backup, if that turns out to be necessary. If you're not sure exactly how many hours, it's better to overestimate rather than underestimate (i.e., give us a larger nubmer of hours rather than a smaller one). Please note it does need to be a number of hours (or days) rather than a date and time, because timezones make date+time harder to work with.

**Comment by skybluefusion** [comment]
I think it was about 2-3 days ago. I struggle with perception of time, especially when thrown for a loop by technical issues and bad seizure days, which have coincided recently. Habitrpg is my guide through the day.

**Comment by Alys** [comment]
@skybluefusion I've started downloading a database backup. It will have finished downloading when I wake up tomorrow (in about 12 hours from now) and then I'll work on extracting your data and restoring it. That part might take another couple of hours (mostly time waiting for the database extraction to run - it's slow). You should have your tasks back within 24 hours, probably sooner.

**Comment by Alys** [comment]
@skybluefusion I'm working on restoring your tasks now. There are some problems with some giving errors when they're imported into the database, so I'm still investigating that problem. While I'm doing this, you might find your tasks appearing and disappearing, but please be assured it's only temporary. By the time I've finished, you should have back all your tasks from the backup made about four days ago.

Also note that I've set your account to Rest in the Inn. That means that if your Dailies reappear while you are sleeping, you will NOT take any damage from not having completed them today. If you're not familiar with Resting in the Inn, you can learn more about it at http://habitrpg.wikia.com/wiki/Rest_in_the_Inn or you can ask here.

**Comment by Alys** [comment]
@skybluefusion All of your tasks from about four days ago should be restored now. Please tell me if you think anything is missing. 

If there are challenge tasks there that you do not want, you'll need to delete them, but if you are nervous about doing that, I can help with it. Please tell me the name of one of the tasks from the challenge, and I can use that to identify all tasks from that challenge to be removed.

**Comment by skybluefusion** [comment]
Only the challenge tasks returned, not the ones that  I created myself (and are more important). Thank you for attempting to fix my issues but the issues remain.

**Comment by Alys** [comment]
Okay, then the problem must have happened more than four days ago. I'll download another copy of the database. Do you have an idea of how many days back I should go?

**Comment by skybluefusion** [comment]
As I said before, my concept of time is umm difficult. I use habitrpg to help mark the days. I am in and out of it throughout the day due to a dozen or more seizures daily. Once the site started screwing up to the point I couldn't use it i lost all track. Sorry. My life is $$$$ right now and I'm not dealing with life in general so I know I'm not helping you help me well and I apologize. I greatly appreciate all the time you've been spending trying to fix my issues. maybe it was 5 or 6 days ago when the tasks started disappearing. i'm not sure they disappeared all at once. i noticed my to-dos had a bunch missing first but had so many challenges active at the time that my task list was far too long. the tasks that are missing tho are the ones i actually kinda need. i'm planning to leave most of the challenges and been trying to figure out how to streamline my tasks list but its in increments. sorry i'm just ramblingg now. my head is so messed up. time for meds

**Comment by Alys** [comment]
What if I use a backup from ten days ago? Will that be too far back?

**Comment by skybluefusion** [comment]
10 days is fine. As long as at least the majority of my personal tasks get
returned i can deal with whatever might have been added since then. i just
need the backbone of my routine back so i have something to work then i can
adjust my list little by little again as i had started to work on when
things got wonky. thank you

Help The Office of Letters and Light continue to provide such wonderful
programs as NaNoWriMo: http://www.stayclassy.org/fundraise?fcid=153247#
AIM:  Confusedalotly,
facebook: facebook.com/skybluefusion http://www.facebook.com/skybluefusion
Music:  http://www.last.fm/user/skybluefusion
http://twitter.com/skybluefusion
http://www.skybluefusion.com

**Comment by Alys** [comment]
No worries, I'll use the backup from 10 days ago. I'll download and import that over the next several hours, so you should have those tasks back in 12 to 24 hours at most.

**Comment by skybluefusion** [comment]
Thank you so much. When I'm functional enough I'll promote habitrpg on my
blog and social media and if there's anything else I can do (I lack
coding/art skills but used to do a lot of writing) please let me know.
It's been a very useful and motivating tool for me over the last months.

On Fri, Jun 5, 2015 at 11:08 PM, Alys notifications@github.com wrote:

> No worries, I'll use the backup from 10 days ago. I'll download and import
> that over the next several hours, so you should have those tasks back in 12
> to 24 hours at most.

Help The Office of Letters and Light continue to provide such wonderful
programs as NaNoWriMo: http://www.stayclassy.org/fundraise?fcid=153247#
AIM:  Confusedalotly,
facebook: facebook.com/skybluefusion http://www.facebook.com/skybluefusion
Music:  http://www.last.fm/user/skybluefusion
http://twitter.com/skybluefusion
http://www.skybluefusion.com

**Comment by Alys** [comment]
@skybluefusion I've uploaded your tasks from 2015-05-27 which is the oldest backup we have. It seems to have some non-challenge tasks in it, so I hope it's okay. It took much longer than usual - I am sorry about the delay. I've given you some extra gems as an apology for the trouble. Please tell me if there are still problems or if you want help deleting challenge tasks. I'm going to bed now but I'll be online again in eight or nine hours probably.

**Comment by skybluefusion** [comment]
Thank you so much. Sorry, I've been extra ill and offline for the last day or two. All your help is much appreciated and it appears the  tasks I need have returned. The new armoire or whatever it was appeared briefly during the time I checked to see if tasks were back. Now that I have my tasks back the new reward mentioned in news disappeared. I'm hoping that issue will resolve itself with time and am not too concerned about it, just a curiosity. 
Thank you again for all your help and bonus. I can get tasks deleted, merged, cleaned up now that I have my list to work with again so I dn't have to start from a blank slate as my brain is not functional enough lately to do that.

**Comment by Alys** [comment]
No worries. I'm glad the tasks you need are back! I've made a local backup of them so if they disappear again it will be much faster for me to restore them.

I know what's gone wrong with the Armoire - that was something I messed up while I was restoring your account. I'll have it fixed up in the next few hours (it's not difficult, but I'll have to wait until I finish work today). You should see the Armoire again soon.

Comment here if you have any more problems!

**Comment by skybluefusion** [comment]
@Alys, you are great. Thanks for working so hard to keep the site going. It
is very much appreciated, and I doubt you get nearly enough credit for your
service.

On Mon, Jun 8, 2015 at 9:43 PM, Alys notifications@github.com wrote:

> ave it fixed up in the next few hours (it's not difficult, but I'll have
> to wait until I finish w

Help The Office of Letters and Light continue to provide such wonderful
programs as NaNoWriMo: http://www.stayclassy.org/fundraise?fcid=153247#
AIM:  Confusedalotly,
facebook: facebook.com/skybluefusion http://www.facebook.com/skybluefusion
Music:  http://www.last.fm/user/skybluefusion
http://twitter.com/skybluefusion
http://www.skybluefusion.com

**Comment by skybluefusion** [comment]
Although the issues were resolved in general all the challenges I was participating in (which was too many) no longer showed in the list of "participating" so I had to search through the list of "all" challenges and re-join each and everyone of them in order to leave them. Unfortunately, there is one challenge I was never able to find and therefore have had a set of tasks I do not need nor want but have been unable to remove. This set does not have a challenge-related tag. I have searched the list of challenges from all the guilds I've ever joined. It's a long list and its possible I've just missed it but after searching multiple times between the time the original issue arose and now I finally give up. I am trying to futher clean up my tasks but these stubborn ones won't leave. How do I remove these challenge tasks for a challenge I cannot find to leave? I'm not sure what guild the challenge was from. 

The tasks I'm trying to remove are:

rebute "You can't..."
rebute "I hate everything"
rebute "You're an idiot"
rebute "All food is poison"

I do realize you are likely all extra busy currently with whatever issues may have arrisen with the switch-over to habitica. There is no rush on solving my very low-priority issue. I appreciate any assistance whenever it becomes possible. Thank you.

**Comment by crookedneighbor** [comment]
@skybluefusion I've removed those tasks for you. Reload the site and double check that they are gone now.

**Comment by skybluefusion** [comment]
Thank you very much. :) The tasks have disappeared.
