### ISSUE TITLE
Every second to last list item on each Tasks help list displays: "Error processing string. Please report to http://github.com/HabitRPG/habitrpg."

### ISSUE THREAD

**Issue by cmoedk** [HabitRPG/habitica#5349]
![error](https://cloud.githubusercontent.com/assets/11811026/8004205/d78339ba-0b7d-11e5-9797-20fc2e6bc106.jpg)

UserId: 38040a8f-6adb-4bc0-93e2-be69cec72326

Chrome 43.0.2357.81 m, Windows 7 SP1

I have changed the language from danish to english, but don't know if the error was there before changing.

**Comment by hairlessbear** [comment]
Good catch! I'll fix this right now.
