### ISSUE TITLE
Orb of Rebirth is not unlocked by the new Ultimate Gear achievements

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5352]
The Orb of Rebirth is not unlocked by the new Ultimate Gear achievements.

Assuming we still want that - @lemoness ?

I'm thinking that it might make sense to NOT unlock the Orb when you have an Ultimate Gear achievement. Players tend to get it around level 20 to 30 I think (very roughly), which is rather soon for thinking about rebirth. And now that Ultimate Gear unlocks something else, it would still be special even without unlocking the Orb.

**Comment by Alys** [comment]
Assuming we still want that - @lemoness ?

**Comment by Alys** [comment]
I'm thinking now that it might make sense to NOT unlock the Orb when you have an Ultimate Gear achievement. Players tend to get it around level 20 to 30 I think (very roughly), which is rather soon for thinking about rebirth. And now that Ultimate Gear unlocks something else, it would still be special even without unlocking the Orb.

**Comment by SabreCat** [comment]
The logic for Rebirth unlock is far out of date--see the discussion on #2742. This might be a good time to go ahead and do that overhaul.

**Comment by lemoness** [comment]
Personally, I don't think Ultimate Gear should unlock Rebirth, for the
reasons stated.

**Comment by Alys** [comment]
Excellent! I'm closing this and setting our wiki editors to adjusting the wiki! Thanks @lemoness.
