### ISSUE TITLE
Organize the Rewards column

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5356]
At the very beginning of Habit, the most you would ever see in the static section of Rewards was five items: a weapon, an armor, a helmet, a shield, and the Health Potion. Now, however, with the Enchanted Armoire, contributor gear, and (especially) buyback items from death and Rebirth, the Rewards column can get extremely long and ungainly. A user who buys a Rebirth after many months of mystery items, legendary quest equipment, Armoire, etc., etc., may have a Rewards column requiring multiple pages of scrolling.

A couple of ideas:
- The Rewards column could have drawers that automatically collapse once a given category grows beyond three or four items. They could organize in fashions similar to the Equipment page (Armoire, Mystery, each class...), perhaps with the grouping options functionality recently proposed.
- Items that the user can buy back for 0 aren't really Rewards. Rebirth needn't remove them at all; they can stick around in the user's inventory indefinitely.
##

**Comment by crookedneighbor** [comment]
I'm :+1: on mystery equipment not appearing in rewards section after rebirth.

**Comment by Alys** [comment]
See some ideas here: https://github.com/HabitRPG/habitrpg/issues/4981 "Rewards, Equipment, Skills need better filtering options and maybe sorting options"

**Comment by librarianmage** [comment]
What is the current status on this?

**Comment by Alys** [comment]
Still suggestion-discussion and also probably best to wait for the website improvement project as described in [my comment in #6933](https://github.com/HabitRPG/habitica/issues/6933#issuecomment-284971739)

**Comment by SabreCat** [comment]
This became much lower priority after Rebirth was modified not to remove equipment, as well.

**Comment by librarianmage** [comment]
With the new update, is this Issue still needed?
