### ISSUE TITLE
Detail Costume selections when viewing other user's profile

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5358]
Often, when I pop open somebody's profile (especially a party member's!), I am curious to see what pieces of equipment make up their visible avatar. However, the modal profile view doesn't list costume pieces, only battle gear. It'd be nice to have a way to see "ooh, how did they make that?"
##

**Comment by hairlessbear** [comment]
Oh man, this has been on my to-do list for a couple months. Maybe I'll finally get around to implementing it. 

I'm certainly not laying claim or anything though; if anyone else wants to take a stab at it first, feel free!

**Comment by librarianmage** [comment]
I would be interested in taking a stab at this!

**Comment by Alys** [comment]
@MathWhiz I think this would be fine for you to work on. Please note though that since it's not urgent, it might be a while before your PR is reviewed, if we're still fixing high priority bugs at that time.
