### ISSUE TITLE
Audio submenu is missing close button on mobile

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5359]
## The following isn't a bug; see @crookedneighbor's response for the actual bug.

All items in `menu.jade` contained within `ul.toolbar-controls` aren't being displayed. There are three instances of this.

[First instance](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/menu.jade#L72-76):

``` jade
ul.toolbar-controls
  li.toolbar-subscribe-button
    button(ng-if='!user.purchased.plan.customerId',ui-sref='options.settings.subscription',popover-trigger='mouseenter',popover-placement='bottom',popover-title=env.t('subscriptions'),popover=env.t('subDescription'),popover-append-to-body='true')=env.t('subscribe')
  li.toolbar-controls-button
    a(ng-click='expandMenu(null)')=env.t('close')
```

[Second instance](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/menu.jade#L209-213):

``` jade
ul.toolbar-controls
  //-li
    //-a(ng-click='') Clear all
  li.toolbar-controls-button
    a(ng-click='expandMenu(null)')=env.t('close')
```

[Third instance](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/menu.jade#L256-258):

``` jade
ul.toolbar-controls
  li.toolbar-controls-button
    a(ng-click='expandMenu(null)')=env.t('close')
```

Is fixing this desirable? As far as I can tell, three of the four hidden items are "close" buttons that are supposed to appear at the bottom of certain submenus. Considering these menus can be closed in many other ways, I don't think a "close" button is necessary.

**Comment by crookedneighbor** [comment]
These are all used for the mobile menu. Shrink the window size down till each task column fills the whole screen, you'll see that the top section collapses to a few buttons. Opening each of them will show a close button at the bottom. 

For some reason, the audio one is messed up and is also missing the close button:

![screen shot 2015-06-06 at 5 41 15 pm](https://cloud.githubusercontent.com/assets/2916945/8021771/445d2398-0c73-11e5-9483-d204e37b5f50.png)

**Comment by hairlessbear** [comment]
Ah-ha, that makes so much more sense. Thank you.

**Comment by hairlessbear** [comment]
The audio menu doesn't contain a close button because one isn't programmed to be there (the three instances above are for the left-most button [tasks/guilds etc.], notifications, and settings).
