### ISSUE TITLE
Variant front page text does not display properly on iPhone

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#5360]
iPhone 6:

![2015-06-06 17 34 08](https://cloud.githubusercontent.com/assets/2916945/8021746/698ee648-0c72-11e5-964e-17c122ca5873.png)

**Comment by hairlessbear** [comment]
Can't replicate on Galaxy S5 (Android 5.0; chrome and built-in browser) or Nexus 7 (Android 5.1.1; chrome and firefox).

**Comment by crookedneighbor** [comment]
@hairlessbear Thanks, looks like it's limited to iOS then. I've updated the issue title.

**Comment by robeden** [comment]
I can confirm this.

**Comment by robeden** [comment]
Interestingly, I can't reproduce this problem in the iOS simulator, but I can see it every time on my 6+. I've tried cache clears, etc.

Looks like the problem is probably related to an ng-cloak directive introduced in a090fed10bd171e9ff9a9b15c8084f29b99520e8.
