### ISSUE TITLE
Purchased eggs with gems do not appear in inventory.

### ISSUE THREAD

**Issue by PlasmoMage** [HabitRPG/habitica#5361]
I have purchased several eggs with gems. After the purchase they did not appear, but the gems required for the purchase were still deducted. I have refreshed and tried different browsers (Chrome, FF & IE all on Windows 7), and still my purchase has not appeared nor have my gems been refunded. 

User ID: 0ed31de0-92ff-469f-819d-94b5ae4c55a7

**Comment by Alys** [comment]
I'm afraid we can't help you without more details. Which eggs and how many of each did you buy?

**Comment by Alys** [comment]
Also, how many minutes or hours in the past did you make the purchases?

**Comment by PlasmoMage** [comment]
Three rooster eggs and four slime eggs, not 100% about the slime eggs but
it was four other eggs with the rooster eggs. .
This was purchased about 23 hours ago.

On Sat, Jun 6, 2015 at 4:00 PM, Alys notifications@github.com wrote:

> Also, how many minutes or hours in the past did you make the purchases?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5361#issuecomment-109656574.

## 

~Thaddeus Lemelle

**Comment by Alys** [comment]
Thanks for the details. I'll download a backup of the database from before the problem occurred to check out the state of your account. That might give us hints about what might have gone wrong. Once I've finished investigating, I'll add any eggs that are still missing.

**Comment by Alys** [comment]
I've put the eggs into your account. Please reload the Inventory page to see them.
