### ISSUE TITLE
Release Pets/Mounts Dequips Quest Pet/Mounts

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5366]
Minor, but if you release pets/mounts, it will dequip your pet/mount from your avatar... even if you are currently sporting quest pets/mounts, which are not released.
##

**Comment by abatula** [comment]
If no one else is working on this I can try to fix it.

**Comment by Alys** [comment]
@abatula Thanks! Comment here if you have questions or run into trouble!
