### ISSUE TITLE
Quick add browser extension or bookmarklet?

### ISSUE THREAD

**Issue by orschiro** [HabitRPG/habitica#5368]
Dear all, 

What a fantastic work you're doing with HabitRPG. Thank you a lot! 

I have been starting to use it personally but also as a researcher interested in sustainable behaviour, I am very interested in your approach. 

But let me quickly ask a very practical question. 

Is there any way to 'quick-add' habits, dailies and todos without having to open the application, e.g:
- through a bookmarklet 
- or browser extension (preferably Chrome/Chromium)

Thankfully,

Robert
##

**Comment by lemoness** [comment]
Hi Robert,

Hopefully one of these extensions will help you:

http://habitrpg.wikia.com/wiki/QuickToDo
http://habitrpg.wikia.com/wiki/Webservice::HabitRPG_-_Perl_API (for
programmers)
http://habitrpg.wikia.com/wiki/HabitRPG_CLI_Client_-_PHP (might be just for
prog's)
http://habitrpg.wikia.com/wiki/HabitRPG_.NET_Simple_Client (for prog's)
http://habitrpg.wikia.com/wiki/HabitRPG-CLI_-_Windows
http://habitrpg.wikia.com/wiki/HabitRPG-TXT
http://habitrpg.wikia.com/wiki/Hrpg_command_line
http://habitrpg.wikia.com/wiki/PHP_API (for prog's)
http://habitrpg.wikia.com/wiki/Tasker-habitrpg (requires Tasker on Android)

Let us know if you have any more questions!

If you're interested in sustainable behavior change, you may also be
interested in the Habitversary blog, which collects success stories from
users who have used HabitRPG for at least one year:
http://habitversary.tumblr.com

**Comment by orschiro** [comment]
Hi @lemoness,

Thanks for the links!

> http://habitrpg.wikia.com/wiki/Hrpg_command_line

If I have looked at the list correctly, then this is the only Linux solution, correct? 

Moreover, there is so far no simple browser extension (Chromium) to quickly add a habit, daily, or especially todo. Does the api support bookmarklets in principle?

> http://habitversary.tumblr.com

I will certainly have a look at this, thanks!

**Comment by Alys** [comment]
I'm closing this because it's a request for third-party developers rather than a bug report for Habitica.

In the footer of the website (exept on the Tasks page) is a link to wiki's "Add-ons & Extensions" page, which lists third-party tools that use the API to create features like this. Also the Aspiring Coders guild exists for third-party developers so you could ask there for a dev to create a tool, if any of them are interested in the idea.
