### ISSUE TITLE
Ultimate gear lost after class change

### ISSUE THREAD

**Issue by X3SED** [HabitRPG/habitica#5369]
Hello, 

I was happy to see that I have 3 badges today of the 3 classes I passed before "Rogue, Mage and Healer" So I decided to switch from my current "Rogue" class to a "Warrior" for the last badge (3 gems). But now I just see two badges after finishing my Warrior set "Rogue & Warrior"... The Heal & Mage badges aren't here anymore :(

**Comment by SabreCat** [comment]
What's your User ID from Settings > API? That'll help us figure out what went wrong and get your badges restored.

**Comment by X3SED** [comment]
Sure here is my user id : 8de125a2-a4ba-47c8-b1ff-a4cf4f831bbe

Thanks for the fast answer!

**Comment by ghost** [comment]
Redirected from Newbies guild. @Alys thank you!
TBH, I'm not sure if I've really faced the issue, but for the sake of possible debug:

I hit the specific ultimate gear achievement 06/08/2015 as an opted-out-warrior after rebirth. It is the only "class-specific ultimate gear" shown on stats now.
UID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2

Things I'm not quite sure about:
- I believe I've had an ultimate gear achievement as a mage - universal achievement obtained in March'14-May'14. At least it's been suggested as a reason why I have had Orb of Rebirth unlocked at lvl 41.
- It seems the universal achievement had been grayed by the time when I logged in back at the end of April'15

Please excuse me for taking your time if I'm wrong about it.

**Comment by Alys** [comment]
@SabreCat I've had only a brief look at this so I might be wrong, but this line looks like it might cause problems:
https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.coffee#L1697
If the user gains a UG badge for one class, then rebirths or looses a top-tier gear piece from that class due to death, and then after that gains a new UG badge for a different class, the act of gaining the new UG badge will remove their UG badge for their first class, because `owned[found.key]` won't be true for the top-tier piece from the first class.

**Comment by SabreCat** [comment]
I think you're right, @Alys. What we need to do is modify that block so it never flips a `true` to a `false`.

Tagging in @lefnire because he wrote most of that code.

**Comment by SabreCat** [comment]
Actually, I think I've figured out a fix. Testing it now.

**Comment by SabreCat** [comment]
@X3SED @GitHubSphinx: The fix is on its way to the site now. You (and anyone else affected by the bug) should see any missing badges come back within the next hour or so.

**Comment by ghost** [comment]
@SabreCat Thank you very much for being so impressively fast with fixing it!

For some reason your attention to this rebirth-related bug gave me light feeling of [Stayin' Alive by Bee Gees](http://www.youtube.com/watch?v=I_izvAbhExY) about my mage badge =)

**Comment by X3SED** [comment]
Awsome. It now works smooth!! Thanks
