### ISSUE TITLE
Extended "Deadline" [Suggestion]

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#537]
Often I work till midnight so when I get home, I get marked off for those tasks that I "didn't complete" after work (like brush teeth, clean up room before bed, etc) because it's past the midnight "deadline" for dailys. Could the deadline be extended to 2am?

**Comment by wildcate** [comment]
There's already two cards on Trello that would help in your situation: "Record Yesterday's Activity" and "Custom Day start". Both are pretty popular cards with lots of votes so they will probably be implemented soon; you can vote for them there if you like.

**Comment by Pandoro** [comment]
@wildcate pretty much nailed the answer already.
[Record Yesterday's Activity](https://trello.com/card/record-yesterday-s-activity/50e5d3684fe3a7266b0036d6/60)
[Custom Day start](https://trello.com/card/custom-day-start/50e5d3684fe3a7266b0036d6/15)

Please vote for the one that fits your needs better, or both if you like them both ;) 

Closing this for now, feel free to comment further on this though.
