### ISSUE TITLE
Some translation strings are not in use anymore

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5372]
I'm not sure what to suggest if we find a translation string in locales files which is not in use from the code side anymore. However I believe it would be better to keep locales clean if possible. 

Can it be handled with a script? Or should translators keep the track of unused strings to decide case by case on deleting (in case of a line being taken over by other string) or putting them back on code (if it turns out there has just been a mistake)?

Examples:
- generic.json: `expandToolbar` and `collapseToolbar` - toolbar toggle popups, if I remember right
- generic.json: `January`, `February` and so on

**Comment by crookedneighbor** [comment]
I've been meaning to write a utility script that can run and check if any strings are not being used. I just haven't done it. 

For individual strings, you can run this, replacing `String_Name_Here` with your desired string:

``` bash
git grep -c "String_Name_Here" | grep -v "common/locales" | grep -v "website/public/front/more-info.html"
```

That basically searches the repository for instances of that string and outputs the file name, while ignoring the `common/locales` folder and the file `website/public/front/more-info.html` (which includes a compiled version of all the strings)

`expandToolbar` and `collapseToolbar` are safe to remove, as far as I can tell, they were added in [this commit](https://github.com/HabitRPG/habitrpg/commit/8650dc9256580c3fcf3bf221b7941d9b424698d2) and never used. 

I'd leave the months. Those could be useful in the future.
