### ISSUE TITLE
Can only run site in Incognito Mode since Memory Leak Incident

### ISSUE THREAD

**Issue by patach** [HabitRPG/habitica#538]
Using Chrome.

Site was running fine for me all the way until the Memory Leak occurred.  

Now for some reason I can only log in through Incognito Mode.  The normal mode on Chrome  still shows the memory leak message, as it automatically redirects me to https://habitrpg.com/500.html.

I've tried disabling each extension I've had, but to no avail.  I've cleared cache from the beginning of time, and it still reveals no results.

Even weirder is that when I tried using Internet Explorer, it STILL takes me to the memory leak message.

**Comment by lefnire** [comment]
That's a fluke I'm sure. The memory leak is on the server, not effected by what your'e doing on the browser. When you're getting that page, it means the server has hit max RAM capacity and is on it's slow decline to a restart. It could take some time for [forever](https://github.com/nodejitsu/forever) to kick in.

HabitRPG will simply not work in any way on IE, I'm sad to say. A project for another day. Follow [codeparty/saddle](https://github.com/codeparty/saddle) for that progress

**Comment by patach** [comment]
Just to update.  The Site also apparently works on Android.
