### ISSUE TITLE
Android app will not open

### ISSUE THREAD

**Issue by illuscat** [HabitRPG/habitica#5380]
Since the latest update to the app, I can no longer open the Android HabitRPG app at all. It shows me a logo, then an error message, and closes. I have a Samsung S3 phone.

(Thanks for reading!)

**Comment by crookedneighbor** [comment]
Pinging @negue

**Comment by negue** [comment]
Working on it!

**Comment by negue** [comment]
@illuscat Sorry! and I've uploaded Version 55, should be available soon in the Google Play Store :)

**Comment by illuscat** [comment]
Thanks!

**Comment by illuscat** [comment]
Unfortunately,  the update did not solve the problem for me. I still get an error message on start. Sorry!

**Comment by Alys** [comment]
Uninstall the app and reinstall. If that doesn't help, tell us what version of Android you are running, and whether you are running any software that modifies the OS (e.g., cyanogenmod). Include the version number of that software too.

**Comment by illuscat** [comment]
Thank you! The uninstall/reinstall did the trick!
