### ISSUE TITLE
Enchanted Armoire not available in App

### ISSUE THREAD

**Issue by gsalvadi** [HabitRPG/habitica#5383]
Not sure if this post belongs this place. But can't find an appropriate place to post this (somebody guide if there is an appropriate place). May be this has been planned / deferred. But the app doesn't know about weapons from armoire. Strength and other attributes of the equipment from armoire is not being used in play I guess.

**Comment by crookedneighbor** [comment]
The stats are calculated on the server, just not displayed correctly on the app. Rest assured, you are getting the correct stats. :)

**Comment by gsalvadi** [comment]
Do you mean that there is no influence of the app even I use only app? Guess so :)
Thank you.

**Comment by lemoness** [comment]
This will be fixed in an upcoming app update, so I am going to close this now.
