### ISSUE TITLE
Filter tasks by searching for a keyword

### ISSUE THREAD

**Issue by JiriChara** [HabitRPG/habitica#5385]
I would love to have a functionality to search tasks by a keyword.  It is one of the features I really miss, because I have to use browser's native "crtl+f" instead.

My suggestion is to put a search input field right before the "tags" button group and whenever user types into the field, all the tasks get filtered - only the tasks matching the text will be shown (in all groups habits/dailies/todos).

I will try to implement it this weekend. All the filtering will just happen in front-end.

**Comment by Alys** [comment]
FYI for other admins, JiriChara suggested this in Trello and I said to go ahead.

@JiriChara I'm really looking forward to seeing what you come up with! I think this will be a popular feature. If you find anything in the code base that gives you trouble, don't be hesitant about asking here for advice. 

I suggest allowing the filtering to work on Rewards too - some people have a lot of Rewards and this would be useful to them.

**Comment by JiriChara** [comment]
#5389
