### ISSUE TITLE
Rewards update

### ISSUE THREAD

**Issue by mrshinesward** [HabitRPG/habitica#5386]
Hello!

My friends noted that a new reward has been set up on their accounts; however, I did not receive the update. (screenshot attached below) Evidently, there was an update that allows users to spend 100 G and receive drops? I'd love to see that reward feature on my account as well.

Thank you!

![screen shot 2015-06-10 at 9 28 21 am](https://cloud.githubusercontent.com/assets/12832965/8088003/2424c472-0f53-11e5-9311-a9538a41f1eb.png)

**Comment by crookedneighbor** [comment]
The enchanted armoire only appears once you've gained the ultimate gear achievement for at least one class. You get that by purchasing all the normal reward equipment for that class. I see you still have a short sword to buy as a rogue, do you have all the equipment from a different class?

If so, post your UUID (found in [Settings > API](https://habitrpg.com/#/options/settings/api)) here and one of us will investigate.

**Comment by mrshinesward** [comment]
Thanks so much for the quick response!

**Comment by hairlessbear** [comment]
@mrshinesward Does that mean that you don't have all of the equipment from a different class? If so, could you please close this ticket?

Of course, if you _do_ have all of the equipment from a different class, or you believe there is another issue, please post your User ID using the method @crookedneighbor described.

One last thing: if you'd like to read more about the Enchanted Armoire, [this is its wiki page](http://habitrpg.wikia.com/wiki/Enchanted_Armoire).
