### ISSUE TITLE
Ultimate Gear non-class-specific badge is showing for user(s) that don't have Ultimate Gear

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5387]
Reported by Magnolia60555 (d8467454-73d0-444d-be8f-7f161d75ea48) in the Tavern. See their profile screenshot below. They do not have all the gear for any class (I checked).

Here's their achievements data:

```
    "achievements" : {
        "challenges" : [ ],
        "perfect" : 46,
        "streak" : 6,
        "quests" : {
            "atom1" : 1
        },
        "ultimateGear" : false,
        "ultimateGearSets" : {
            "healer" : false,
            "wizard" : false,
            "rogue" : false,
            "warrior" : false
        }
    }
```

![screen shot 2015-06-11 at 8 03 42 am](https://cloud.githubusercontent.com/assets/1495809/8095491/f2663c3a-1011-11e5-9270-5538a6d4ddfe.png)

**Comment by crookedneighbor** [comment]
It's supposed to be muted if they don't have it, but the check to make it muted is looking for if `ultimateGearSets` doesn't exist, but it does. 

https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/achievements.jade#L81-L83
