### ISSUE TITLE
Then I click  on help icon for Habits, Dailies or To-Dos there is a string Error processing string "Please report to http://github.com/HabitRPG/habitrpg"

### ISSUE THREAD

**Issue by ivan133** [HabitRPG/habitica#5388]
Then I click  on help icon for Habits, Dailies or To-Dos there is a string Error processing string "Please report to http://github.com/HabitRPG/habitrpg" in every help list.
Here is a screenshot:
http://www.awesomescreenshot.com/image/315662/9a6f462c17d2fea92fb1ff97e7e1d583

**Comment by crookedneighbor** [comment]
It's just been fixed. Will go out in the next deploy.
