### ISSUE TITLE
Editing Profile Tab Switches to Avatar

### ISSUE THREAD

**Issue by cbleisch** [HabitRPG/habitica#539]
I decided to add my info to my profile and every time I enter a character (for instance the first letter of my first name) the tab switches and displays the Avatar tab. This happens for every form field in the Profile tab. I found copying my text first and pasting it in entered all the data, but the tab still switches.

**Comment by lefnire** [comment]
ahhh boy. It's the fact that we're using `{dynamicBindings}` which save to the database with each character. We should use `{{oneTimeLoadBindings}}` + `x-bind="submit:saveProfile"` on the done button. Assigning to myself

**Comment by lefnire** [comment]
switching to `difficulty-hard`, this bug is weird.

**Comment by lefnire** [comment]
thoughts: it appears always to be an issue inside tabs..

Edit, maybe not - tried removing the tabs. Second though, it's always inside a dynamic-binded `{#if _whatever}`. With rewards, the solution was changing the generic truthy test `{#if _user.flags.petsEnabled}` to an equals test `{#if equal(_user.flags.petsEnabled,true)}` - which shouldn't have fixed it (truthy has always worked just fine..). Tried that hack-fix here, didn't fix it.

**Comment by lefnire** [comment]
possible leads: 
- https://github.com/codeparty/derby/issues/214
- https://github.com/codeparty/derby/issues/117
- https://github.com/codeparty/derby/issues/119
- https://github.com/codeparty/derby/issues/215

I think it has something to do with nested live-binds (if, when, each), and possibly with multiple templates. Also, @toebu this might be a lead on our tags issue. I'm gonna investigate tonight
