### ISSUE TITLE
Gear rewards, automatic refunding

### ISSUE THREAD

**Issue by TehDanny** [HabitRPG/habitica#5390]
I currently have this issue where I buy my last piece of gear and get the achievement for doing so, but after a short while, or the next day, I lose that piece of gear and the achievement and get my gold refunded. This has happened around 10-15 times now. The bug also occurred for a few lower-quality equipment, but that only happened a few times.

**Comment by Alys** [comment]
Can you please tell us your user ID? To find out how to find it, go to Help -> Report a Bug (on the HabitRPG website) and follow step 6 in the instructions there.

**Comment by TehDanny** [comment]
a56db72f-f44f-4e61-ace4-d079b01fa238

**Comment by TehDanny** [comment]
a56db72f-f44f-4e61-ace4-d079b01fa238

**Comment by Alys** [comment]
@TehDanny At the moment, you have all the gear and the achievement. As soon as you see the gear being un-bought, please immediately (before you do anything else) go to Data -> Export Data, and click on the "JSON" link. Please email the resulting file to admin@habitrpg.com and then make a brief post here to say you've done that.

**Comment by TehDanny** [comment]
The bug has changed again, now it happens when I spend 100g on Enchanted Armoire. I lose the gold, get no reward and later I get the gold again.

**Comment by Alys** [comment]
There's nothing obviously wrong in your account, so I think it's either a sync error or an example of [this bug](https://github.com/HabitRPG/habitrpg/issues/4313)

Have a look at [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) on the wiki, especially the "How to Minimize Sync Errors" section.

Also try reloading the page before and after you use the Armoire, which should help if it's actually from that bug.

Let us know how it goes.

**Comment by Alys** [comment]
You might also want to try deleting your browser's cache and local storage (you can google instructions for your particular browser) or try a different browser to see if that makes a difference.

**Comment by TehDanny** [comment]
Buying and then reloading the page reproduces the bug. Also after running Ccleaner. Using firefox. With internet explorer it worked. Spend the gold, got a piece of equipment (Gladiator Armor) and it's still there after I reload the page, even on firefox. I suppose it's fixed then... sort of. It would be a bit tiresom to switch to internet explorer each time I want to buy something.

**Comment by Alys** [comment]
Did you reload the page in Firefox BEFORE you bought the item as well as after?

**Comment by Alys** [comment]
If not, please do both reloads next time you use the Armoire.

After the first reload, open the Web Console (Tools -> Web Developer -> Web Console), make sure the "JS" option is highlighted in blue and the other options are not, click the clear button in the console, then use the Armoire. If anything appears in the Web Console, record it for us (copy-paste and/or screenshot), and then do the second reload, and tell us if the equipment (or food or XP) stays or goes.

**Comment by TehDanny** [comment]
Ehm well I didn't exactly press the "reload current page" or F5, before I bought it, but I went from social, so I guessed that the data was as fresh as possible.

I followed your instructions with my second Armoire purchase. The console showed nothing after the purchase, but it gave the attached result after I reloaded. The gold I used got refunded and the xp I gained didn't stay.

I'm guessing JS stands for javascript and have a feeling that my NoScript addon has something to do with this bug. It shouldn't, as I've allowed scripts to work on habitrpg.com, but it could have something to do with it.Ehm well I didn't exactly press the "reload current page" or F5, before I bought it, but I went from social, so I guessed that the data was as fresh as possible.

I followed your instructions with my second Armoire purchase. The console showed nothing after the purchase, but it gave the attached result after I reloaded. The gold I used got refunded and the xp I gained didn't stay. Hm, I'm having issues with attaching the screenshot.

I'm guessing JS stands for javascript and have a feeling that my NoScript addon has something to do with this bug. It shouldn't, as I've allowed scripts to work on habitrpg.com, but it could have something to do with it.

**Comment by TehDanny** [comment]
Ehm well I didn't exactly press the "reload current page" or F5, before I bought it, but I went from social, so I guessed that the data was as fresh as possible.

I followed your instructions with my second Armoire purchase. The console showed nothing after the purchase, but it gave the attached result after I reloaded. The gold I used got refunded and the xp I gained didn't stay. Ehm, I'm having issues attaching the screenshot.

I'm guessing JS stands for javascript and have a feeling that my NoScript addon has something to do with this bug. It shouldn't, as I've allowed scripts to work on habitrpg.com, but it could have something to do with it.

**Comment by TehDanny** [comment]
![unavngivet56](https://cloud.githubusercontent.com/assets/12846822/8132138/cb341dbc-111f-11e5-918d-6388d1d1bab0.jpg)

**Comment by Alys** [comment]
@TehDanny I'm sorry we didn't respond sooner! If this is still happening, please disable all browser extensions (as a temporary measure at least) and see if that fixes it. Alternatively, please try using HabitRPG in a different browser that doesn't have any extensions installed. Does that help?

**Comment by TehDanny** [comment]
Yeh I was wondering why I didn't hear from you guys, but nevermind I'm on a break from Habit now and I'm pretty positive that some javascript was being blocked by my extension.

**Comment by Alys** [comment]
@TehDanny Thanks for letting us know, and sorry again about the delay. I'll close this now but we'll reopen it if you notice the problem reoccurring without extensions.
