### ISSUE TITLE
Abandoned Quest

### ISSUE THREAD

**Issue by jrenee25** [HabitRPG/habitica#5397]
We have a party member that started a quest but then has not returned to our party to start the quest.  Can you please help?

My user ID: 37635d5f-c9cb-4842-8c86-2a0be1263afa
Group ID: 7297fa28-47f8-4ea8-8b35-f451102cdf9e
Quest: Attack of the Mundane Questline, Pt. 1: Dish Disaster!
Quest owner: Walyson Naves Gonçalves Pilaf

**Comment by Alys** [comment]
The quest owner (1a7e1b36-3858-4861-a62f-6e88a884c8f6) last logged in on 2015-06-10 - only a few days ago. I'd prefer to not cancel the quest just yet. Please send them a PM. If they have email notifications turned on, they'll be told that they have a message and will hopefully then log in. If the quest still hasn't started in two days, post again here.

Note that you can make the quest start without the quest owner doing anything by getting all members of the party to accept or reject it.

**Comment by jrenee25** [comment]
Sounds good - I'll let you know in two days if he logs back in.

**Comment by jrenee25** [comment]
He has still not logged back in - can you please cancel the quest?  The rest of our party is getting really upset because we are all just waiting.

**Comment by jrenee25** [comment]
The quest started - not sure who did it or how, but I'm going to go ahead and close this issue.

**Comment by Alys** [comment]
The quest leader started the quest.
