### ISSUE TITLE
flattr donation support

### ISSUE THREAD

**Issue by orschiro** [HabitRPG/habitica#5398]
Hi all, 

Is it possible to support donations through flattr.com?

Looking forward to your opinion. 

Thanks!

Robert

**Comment by hairlessbear** [comment]
@orschiro As I said in your other ticket, feature requests belong [on Trello](https://trello.com/c/odmhIqyW/440-read-first-how-to-request-a-feature-table-of-contents), not here. In this case, you should request this on the [integration card](https://trello.com/c/jW0pKNIm/438-request-integration).

**Comment by Alys** [comment]
@orschiro  I also have some specific feedback about this idea, from a discussion with other admins (sorry about the delay, I was giving time for several people to respond).

While Flattr is a good service and we appreciate your desire to donate to us, we think that the time required to set up and maintain integration with Flattr would be greater than the benefit we'd receive from it. 

It would require more than only adding the Flattr button - we'd have to provide a description of what it was for, an explanation that it gave no benefits, documentation on the wiki, answers to questions about it in HabitRPG's chat areas, and we'd have to deal with requests to reverse the donation when people clicked and then changed their minds. These kinds of user support take a surprisingly large amount of time. I know that to someone familiar with Flattr, all of that might seem unnecessary, but our experience with our current methods of donation indicates that it will be essential and that user confusion will happen.

We also prefer to give our players some benefit in return for their donations, which Flattr would not allow.

Thank you for suggesting this, but we won't be implementing Flattr integration.

**Comment by orschiro** [comment]
@Alys 

I appreciate your detailed reasoning behind your decision, thanks!

@hairlessbear Thanks also for pointing me to the Trello purpose. I wasn't aware of its use here.

Warm regards to both of you,

Robert
