### ISSUE TITLE
minor css annoyance with elete, edit, progress icons and long texted tasks

### ISSUE THREAD

**Issue by wiber** [HabitRPG/habitica#54]
when hovering a task/habit the icons appear for delete, edit, progress etc. These make the box flicker when hovered if the text is long enough to wrap when icons appear (on hover, in chrome) 

eg class="icon-trash"

**Comment by horusofoz** [comment]
@lefnire Was this resolved with the word wrap fix?

**Comment by horusofoz** [comment]
Resolved.
