### ISSUE TITLE
Feature Request:  Rewards for doing multiple dailies

### ISSUE THREAD

**Issue by Tam-Lin** [HabitRPG/habitica#540]
I'm not sure how to capture this, and you could do this by having both a habit and a daily entry, but there are things I want to make sure I do at least once a day, and if I do more than once, even better.  So, for example, I want to spend at least 30 minutes a day on treadmill, but if I spend two hours, then that's a very good thing.  And if I don't spend at least  30 minutes, then that's a bad thing.

**Comment by wc8** [comment]
I handle this with a daily for the minimum and a habit for the extras. 

> daily: 15 minutes exercise
> habit: 15 minutes exercise

In this case, 1 hours would be logged as 1 daily and 3 habit completions.
For each, I make the amount the smallest measure I deem worth counting. For instance, I could make the daily 30 m. and the habit 15 m.

**Comment by Tam-Lin** [comment]
Right, that's definitely one way of handling it; I'd just think it would be cleaner to have only a single entry for a goal, instead of having to have the same activity in multiple columns.

**Comment by wc8** [comment]
(I've wished for this [a single entry] myself, actually.)

Maybe we could call this **Extra Completion for Daily**

One method: a checkbox and a **+** button beside it.
The checkbox would register the completion, the **+** button would log good habit clicks:

> **☐⊕** 20 minutes study
> **☐⊕** 1 hr. working on project X
> **☐⊕** 30 min. exercise + 15 min.

More complex method: allow user to enter # of units for each completion

**Comment by horusofoz** [comment]
This is currently being investigated under [Trello 182](https://trello.com/c/wTiRWiB2). Navigate to the provided link, vote for your suggestion and add your voice to the discussion to determine how it will be implemented.

**Comment by Tam-Lin** [comment]
No, not really the same thing.  Trello 182 is for streaks, doing the same thing every day for an unbroken string of days.  This is for doing the same thing multiple times in a single day, where you should suffer some sort of loss if you don't do it at least once (or possibly a configurable number of times), but want to be rewarded if you do it more than the minimum number of times.  You can do this by having a habit entry and a daily entry for the same thing, but it isn't as clean, and more prone to error (ie, forgetting the daily, and just incrementing the habit).

**Comment by Pandoro** [comment]
There must have been a small mistake there, sorry :)

This is now really investigated under [trello card 207](https://trello.com/card/extra-completion-for-daily/50e5d3684fe3a7266b0036d6/207).

I pretty much just edited the card together by taking some of the stuff from this ticket. Please let me know if something is missing or not, so that I can again close this.

**Comment by Tam-Lin** [comment]
No, that's pretty much the basic version.  The one change/possible enhancement I'd add would be to have it be a user-set number of units as a minimum (ie, don't do that many, and you fail), and then any number of units over that minimum is a bonus.  ie, I want to exercise 45 minutes a day; I actually exercise 75.  I could think of a few different ways to handle the entry, depending on how precise people wanted to be.

**Comment by Pandoro** [comment]
I changed the more advanced option at the bottom of the card. I think that was actually what @wc8 meant. Feel free to post additional ideas on the trello card :) 

Thank you for closing.

**Comment by wc8** [comment]
Thanks @Pandoro! 
I made a slight adjustment to the last sentence:

> After this the task is counted complete (no HP loss) but more (bonus) units can be logged and points gained by clicking the plus button. 

rather than:

> After this it could either be counted as complete and no more units can be clicked, or more points can be gained by still clicking the plus button.
