### ISSUE TITLE
No benefit for 12 months subscription

### ISSUE THREAD

**Issue by slylysylar** [HabitRPG/habitica#5400]
Dear Support,

My API User ID is 261abc9f-ddff-4417-b6db-057f7691fce6
I supported the site with the 12 months subscription back in Dec 28, 2014.

Later on this year, I canceled the subscription hoping it won't charge me for the next year 2016.
However the problem is I no longer have any of the subscriber benefits even though I paid for the whole year.

The site helps me a lot so I'm not expecting any refund or anything like that.
But it would be nice to keep my benefits for the remaining months that I supported.

Would you kindly look into this? 
Thank you very much for your help!

**Comment by Alys** [comment]
I'll get this fixed for you in the next day. You'll have the benefits for
the full year. Sorry about the trouble!

**Comment by slylysylar** [comment]
that's awesome, thank you!

**Comment by Alys** [comment]
I think everything should be right now, but please check and comment here if you see any problems. I'm closing this now but we can reopen it and keep helping you whenever necessary!

**Comment by slylysylar** [comment]
Hi Alys,
Thank you very much for your quick work!

I was not sure how to check if changes were applied however so I looked at the HabitRPG Official User Data Display Tool. 
It's still saying my drop cap is 8 instead of 16 for the subscribers.

Could you please verify? Thanks again!

**Comment by Alys** [comment]
Please show me a screenshot of the HabitRPG subscription screen (click on the gem in the navigation bar). If you don't want to upload it here, email it to admin@habitrpg.com.

**Comment by slylysylar** [comment]
not a problem, here's the screenshot

![gems](https://cloud.githubusercontent.com/assets/12881649/8173498/d5e3e3ca-1393-11e5-8286-7fd85d608613.PNG)

**Comment by Alys** [comment]
Can you please click on the sync button and check again?

**Comment by slylysylar** [comment]
Got it now. Thank you! You're the best :3
