### ISSUE TITLE
Cannot delete todos

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#5402]
This is an issue I noticed yesterday. Somehow, the cursor doesn't have the click event enabled anymore when mouseovering the bin icon next to the todo. A bit annoying since I'd like to clean my todos and remove the ones that have become useless. I'll mark them as done, then reset my stats, but hopefully this bug can be solved quickly (chrome 43)

**Comment by crookedneighbor** [comment]
@Fandekasp I was not able to reproduce this. Is there any other information you can give us?

Can you [open the Chrome console](https://developer.chrome.com/devtools/docs/console) and tell us if any errors occur?

What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by crookedneighbor** [comment]
Actually, I bet I know what's going on. When you click the trash can icon, and alert box appears. If earlier in your session you told Chrome to stop future alert boxes from the site, even for a different part of the site, the confirmation box to delete the task will not be allowed to be shown, and thus you'd never be allowed to delete it. 

Try reloading the tasks page and try again.

**Comment by Alys** [comment]
Closing since there's been no response about this. @Fandekasp tell us if @crookedneighbor's suggestion didn't work.
