### ISSUE TITLE
Translation errors housekeeping for future - minor suggestions

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5405]
As of now, whenever there's an error in the string in locales a user will see the message:
![http://github.com/HabitRPG/habitrpg.](http://i.snag.gy/cJxp9.jpg)

**Suggested changes:**
**1.** reword the error message
- to give the UI-related guidance rather than URL
- to guide the user's way to the starting point on GitHub which is _#2760, as far as I understand
- I'm thinking about the message `Error processing the string. Please see Help > Report a bug` It will look like this:

![Screenshot](http://i.snag.gy/OFLaa.jpg)

A larger screenshot with the menu item referenced: http://snag.gy/UMJVO.jpg (nothing is changed but the error message, error is intentional for testing)

I'm ready to make a commit addressing this suggestion if you find it useful. The error message is not translatable as I haven't found the way to use t() inside `catch e` in [i18n.coffee](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/i18n.coffee)

**2.** Could you please consider maybe having an all-in-one ticket where users can report about the case where they see exactly this message. The opening post of such ticket may give all instructions of how to report about such a bug. The ticket may also address users who don't want to report on github (no account?) to the guild for translators - [Commonwealth of i18n guild](https://habitrpg.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) - to have translators/reviewers fix the issue for them or report to GitHub on their behalf, if it takes time/effort to solve.

**3.** Could you please consider maybe adding a special note to _#2760 about this kind of errors. E.g. if a user sees exactly this error, there's no need for them to provide UID and other specs. What is needed is the selected language, explanation of the place where an error message is seen, and maybe a screenshot. If the all-in-one ticket is created, the _#2760 can only give a line like "If you see THIS message - please follow instructions of _#xxxx".

**Comment by Alys** [comment]
1. Yes, absolutely, that's a much better idea! Please do make your commit.

2 and 3 we'll consider. I like them, but we don't want the instructions in 2760 to get too large, and I don't want to encourage users to report bugs in places other than GitHub. I'll try out some options on 2760.

**Comment by ghost** [comment]
@Alys thank you very much for considering my suggestions!
I tried to make suggestions 2 and 3 reflect that I do understand that of course the the staff members and moderators are the ones to decide and choose what is right and more convenient for you to maintain! So it's not meant as suggesting what may be better, but rather an offer to help in arranging some entry-level bugs which may come up from time to time... Once again, thank you very much!

**Comment by Alys** [comment]
@GitHubSphinx I've created https://github.com/HabitRPG/habitrpg/issues/5465 to cover most of your comments in point 2 above. Please let me know if you can think of any improvements. 

I'm still reluctant to suggest that people who don't have a GitHub account could report it in the Commonwealth of i18n guild. I don't want to encourage bug reports elsewhere than here, and I think it's not impossible that if we suggested your guild for this, you'd end up getting bug reports for other things too.

I've added the "Memorable" label to the new issue and I've updated the "Report a Bug" instructions to include a link to all Memorable issues ("the most common issues" link in the third step).

**Comment by ghost** [comment]
@Alys thank you very much! A suggestion about possible help from the guild has been meant only as a topic for discussion. I've just thought of errors in translations as not exactly bugs, but rather mistakes of translators. All in all, of course I agree with you that it's best to keep consistent in reporting all issues only to GitHub.
