### ISSUE TITLE
Party invitation without name

### ISSUE THREAD

**Issue by kamilpowalowski** [HabitRPG/habitica#541]
My friend invite me to a party. After clicking on this invite I saw https://www.diigo.com/item/image/2lfms/xwcr Invitation is without party name. And for sure party name was entered. After accepting invite I can see the party name in options.

**Comment by Pandoro** [comment]
Apart from the name not showing up, did you get into the party without any further problem ?

**Comment by kamilpowalowski** [comment]
I connected to the party without any other problems,

**Comment by Pandoro** [comment]
Okay, In that case, I will degrade this issue to minor. I know it is inconvenient, however, it takes up only a very small percentage of the time you spend in habitrpg. 

In case someone ends up in a wrong party, just leave it and ask for a new invite if it is necessary.  

Nevertheless it should be fixed at some point. I am guessing it is a simple display bug, so I am wondering who tagged it as difficulty-medium though :o ? 

Thank you very much for reporting it though :D

**Comment by horusofoz** [comment]
@lefnire Has this been looked at?

**Comment by lefnire** [comment]
this has been fixed in a recent push, yay!
