### ISSUE TITLE
"Error request entity too large"

### ISSUE THREAD

**Issue by mashfanficchick** [HabitRPG/habitica#5412]
User ID: 9e784738-ed81-42ae-a455-128af83a00e0

Guild: Mentally Ill
Challenge: BACE Method for Self-Care

I hit the Join button and got the error message listed above: "Error request entity too large" (I tried multiple times, including reloading the page; I got the same response every time).

![habitsrpg error message 6-15-15](https://cloud.githubusercontent.com/assets/12906452/8176346/df0e1f0e-13c7-11e5-8a6d-64f19b1dfca5.png)

**Comment by mashfanficchick** [comment]
Forgot to mention, I don't know how to get any computer data. (I'm not very skilled with computers.)

**Comment by Alys** [comment]
That's okay! Thanks for reporting it. It's usually a temporary error so if you try again later it might work.

We are redesigning things to make this sort of problem less likely, but it's a big job and takes quite a while.

**Comment by Alys** [comment]
ref: https://github.com/HabitRPG/habitrpg/issues/1471

**Comment by Alys** [comment]
I'm going to close this in favour of https://github.com/HabitRPG/habitrpg/issues/1471 and I've added some helpful information to the start of that issue (although really, it's just "try again later", so not that helpful I'm afraid). If you keep having the problem, comment here and we'll see if we can do anything to help.

**Comment by Alys** [comment]
Sorry, I've just noticed you said you tried multiple times. Were they all within a short space of time? If so, wait an hour or two and then try again.

**Comment by mashfanficchick** [comment]
Alys, it was in a small amount of time, but it's still like that. Also, several other challenges (but not all of them!) are giving me the same error message. The challenges in question are:

Tavern:
https://habitrpg.com/#/options/groups/challenges/1ffe1741-9193-4b74-9483-67dd812faff3
https://habitrpg.com/#/options/groups/challenges/fc20383a-c688-479b-af39-7c69f28ff308
https://habitrpg.com/#/options/groups/challenges/f929f9a2-b97f-4a37-a939-53c86ea08e08
https://habitrpg.com/#/options/groups/challenges/778a0107-65f5-47d6-84a0-4b428f0e3895
https://habitrpg.com/#/options/groups/challenges/ceb8548a-80ce-4275-92c8-e9979e94ddb8

Mentally Ill
https://habitrpg.com/#/options/groups/challenges/f8c335b7-5607-4d0b-bb80-7be5b36412fa

As I said, it appears to be an issue with these specific challenges, because I've joined several other challenges even as I continue getting error messages on the ones listed above.

Thanks for all your help trying to sort this out! :-)

**Comment by paglias** [comment]
@mashfanficchick the problems you're encountering are probably due to some challenges being too big for the db, we're working on it but it'll take some time. I'm sorry

**Comment by mashfanficchick** [comment]
Thanks for the info, paglias! It really helps to know the problem isn't on my end. :-)
