### ISSUE TITLE
Mage Doing Occasional Double Damage to Boss

### ISSUE THREAD

**Issue by Zelah-Meyer** [HabitRPG/habitica#5414]
Hi,

I am currently a Mage and, every now and then when fighting a boss, I'll do two hits for the same amount of damage.  It's not every time, and I haven't noticed anything in particular that is triggering it.  As far as I'm aware, I'm not doing anything differently to the times when it doesn't happen.

I think it's been since the class tweaks.  At first I thought it was just splitting my damage into two - because I hadn't mentally adjusted to the damage figures for Burst of Flames post-tweaks.  However, last night was the fist night of fighting Vice's Shade (though not the first time we've done that quest) and the boss has 750hp.

The Warrior did 393.9hp damage, the Rogue did 45.3hp, and I did 2 x 199.9hp.  If my damage had only counted once, then it should have only been 639.1hp damage in total - not enough to defeat Vice's Shade.  However, we defeated the boss, and started a new quest.

In this instance, I can confirm that the damage should have been just the one lot of 199.9hp - because I'd checked what my damage would be on the Data Display tool that night - and it stuck in my mind because I was only 0.1hp short of 200.  I can also confirm that the two lots of damage share the same time stamp in the party feed.

It's not a huge issue for me personally, because I've done all the main questline quests, and on the occasions where I do hit twice, it just takes me back up to the damage levels I was at before the Burst of Flames damage reduction.  However, I thought I'd mention it because I'm reasonably sure that it's not supposed to be happening, and therefore you might need to know about it.  :o)

**Comment by SabreCat** [comment]
I believe this is #2805. Follow there!
