### ISSUE TITLE
User with uid not found

### ISSUE THREAD

**Issue by tjlaxs** [HabitRPG/habitica#542]
Now this is with the habitrpg.com and I don't know about the version or such.

It seems the third party API has been broken somehow. A perfectly working software stopped working and I started to investigate it and got the following result: "User with uid=..., token=... not found. Make sure you're not using your username, but your User Id"

With the curl example on API page I get the same results, of course with my UID and TOKEN changed in.

**Comment by Pandoro** [comment]
@switz Any Idea regarding this? (I hope you are the right guy to talk too for this :x )

**Comment by ruddfawcett** [comment]
@tjlaxs I had this same problem and @lefnire is aware of this rare case.  He's working on it...

**Comment by switz** [comment]
I would start using the new API. It's live. See https://github.com/lefnire/habitrpg/pull/522

edit: Reopen if you're still having issues.

**Comment by ruddfawcett** [comment]
It's live?!!?!! @switz?

Whooohoo!

I'll have to jump on that as soon as possible!

**Comment by dpfu** [comment]
It seems I have an issue with my uid. I want to recreate the pomodoro example using bash.
 `curl -X POST -H "Content-Type:application/json" -d '{"apiToken":"{...}"}' https://habitrpg.com/v1/users/.../tasks/productivity/up` it gives me `{"err":"No user found."}`

I tried the second API version with the same result:
`curl --compressed -H "Content-Type:application/json" \
  -H 'x-api-user: {...}' \
  -H 'x-api-key: {...}' \
  https://habitrpg.com/api/v1/user
`
I checked the uid and api-key several times, the should be ok. Am I doing this wrong? Is this some shell stupidity where I need to escape something?

TIA

**Comment by AdrienLemaire** [comment]
Getting the same issue, {"err":"No user found."}  using my user id and api key. No idea why, and there is no option for regenerating keys. Any support would be appreciated, thanks in advance.
