### ISSUE TITLE
velvet hat- enchanted armoire

### ISSUE THREAD

**Issue by kdschu** [HabitRPG/habitica#5421]
user id: 13f49ba1-b064-40c1-b9ce-b1372fcee280
im using internet explorer 11

I've received the hat twice, but it hasn't showed up either time.

**Comment by Alys** [comment]
This will be an example of the bug reported at https://github.com/HabitRPG/habitrpg/issues/5376 so I'll close this issue. You can follow #5376 if you'd like to keep track of the progress of the bug fix.

Could you tell us please: Did both occasions occur immediately one after the other with you taking no other actions of any kind in between?

You can go to Settings (the gear-shaped icon) -> Site and use the Fix Character Values button to give yourself back your wasted gold. Sorry about the trouble.

**Comment by deilann** [comment]
Also, if you're using Internet Explorer, please try to use Habit on Firefox
or Chrome. IE has major issues that keeps it from playing well with others.
By using Firefox or Chrome, you will likely find that most other websites
behave better.

On Wed, Jun 17, 2015 at 9:08 PM, Alys notifications@github.com wrote:

> This will be an example of the bug reported at #5376
> https://github.com/HabitRPG/habitrpg/issues/5376 so I'll close this
> issue. You can follow #5376
> https://github.com/HabitRPG/habitrpg/issues/5376 if you'd like to keep
> track of the progress of the bug fix.
> 
> Could you tell us please: Did both occasions occur immediately one after
> the other with you taking no other actions of any kind in between?
> 
> You can go to Settings (the gear-shaped icon) -> Site and use the Fix
> Character Values button to give yourself back your wasted gold. Sorry about
> the trouble.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5421#issuecomment-113028795.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by kdschu** [comment]
No, The drops were not one after the other. Probably a few drops in between.  I noted my gold level. Clicked on the armoire and then the velvet hat dropped. I went to inventory, clicked refresh, but it didn't appear. Forgot about it and then built more gold and click, click and then just this last time another velvet hat drop but no show. :)

Thanks!
I love this site!!!

Date: Wed, 17 Jun 2015 21:08:36 -0700

**Comment by kdschu** [comment]
Right on. Thank you!

Date: Wed, 17 Jun 2015 21:09:58 -0700

**Comment by Alys** [comment]
Thanks @kdschu, that's useful information. If it's any consolation, you probably received XP or food instead of the equipment, based on our current understanding of this bug. It's also likely to be an intermittent problem, so it shouldn't always happen, but if it occurs once or twice more, comment again here and we'll give you the item manually. We'll see your comment and help you even though this issue is closed.
