### ISSUE TITLE
Creating Checklists not possible on hitting "Enter"

### ISSUE THREAD

**Issue by supervossi** [HabitRPG/habitica#5423]
Hi, 

to create a new checklist entry in your tasks you have to hit the "Enter" button. This worked well an I used checklists in about 80 % of my Tasks and dailies. Unfortunately hitting the "Enter" button on my Keyboard recently (like this week) expands or inflates the menu hence it is not possible to create new checklist entries.

User ID:
07072d9c-f6cf-45b5-a983-42a034b97d4d

Operating System:
Windows 7 

Browser:
Internet Explorer (yeah yeah I know but I dont have access to a different browser in the Office)

I am not sure if the issue appears in different browsers.

Help is appreciated.

Cheers

supervossi

P.S.: sorry for potential bad english --> non native speaker

**Comment by Alys** [comment]
Your English is fine! Thank you for reporting this.

Can you tell us which menu expands? Is it always the same one?

I'm not noticing this on Chrome on Mac OS; I can still add checklist items using Enter. 

Tomorrow, I'll try on Linux and on Firefox on Windows, if no one adds comments about them before then.

**Comment by supervossi** [comment]
Thanks for the quick response,

it is the top menu with the options and the gold / money counter. 
see the screenshots.

the first is with the expanded menu and the second with the minimized menu. ( i wrote inflated in my first post wich is wrong .. i meant to say minimize)

![menu1](https://cloud.githubusercontent.com/assets/12948737/8228491/74eee2cc-15af-11e5-91b0-847c63ffb5c8.JPG)
![menu2](https://cloud.githubusercontent.com/assets/12948737/8228490/74edd120-15af-11e5-98f8-9d1c5163fd12.JPG)

**Comment by hairlessbear** [comment]
I don't think this is an error with the checklists. It looks like the menu toggle button was selected somehow, so when you hit enter, it opened/closed the menu. Reloading the page should fix it. Are you still having the error?

**Comment by supervossi** [comment]
Thats the thing: reloading does not fix this. The menu toggle button always gets selected and you/i cant switch through the "buttons" with [tab].

Only seems to be an issue on the office computer though. 
with chrome there is no problem and i tried it at home also with windows 7 and internet explorer and it works fine. 

is there a way to disable the menu button? this might solve the problem.

**Comment by Alys** [comment]
I also wasn't able to reproduce this on Linux or Windows browsers (including IE).

I don't believe there is currently a way to disable the menu toggle.

I actually find that toggle quite annoying. I'll often trigger it when I mean to click on the Settings button, and then either I do click before I notice the close button has sprung open so I have to click again to reopen the menu, or I instictively move my mouse left to get to the new position of Settings but that closes the toggle so Settings pops back to the right and I have to move the mouse again (and occasionally trigger the close again)... Does anyone else have trouble like this? I've been wondering for a while if that close button is actually good for usability in its current format. @AnitaYCheng What do you think?

**Comment by hairlessbear** [comment]
I can't reproduce the issue either; multiple browsers, multiple operating systems. @supervossi: I'm guessing there's something wonky with the settings on that one browser that are causing this. Not quite sure how to best troubleshoot it.

@Alys I've definitely had the same frustrating thing happen, more often than I'd like to admit.

**Comment by supervossi** [comment]
Hi, 
@hairlessbear I came to the same conclusion. Maybe ist something in the companies workstation settings.
 I just now figured a workaround. When holding the left mouse button while pressing [enter] it adds a new checklist item. 

So I can make this work.

Thanks for all the help.
