### ISSUE TITLE
Weekly Progress Update: XP graph

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5424]
![screen shot 2015-06-18 at 11 13 38](https://cloud.githubusercontent.com/assets/2931465/8229339/c50fd84e-15ad-11e5-9934-0548860eb789.png)

There are a couple of issues with this graph:
- It only shows my XP change for a single day rather than the whole week
- It would be better for i18n if the dates were in the form Jun 10 rather than 06/10

I think the graph should show XP earned each day, rather than the absolute amount of XP earned:
- Rebirths wouldn't mess the y-axis up and make the graph unreadable (my rebirth was only from level 25)
- Direct comparisons could be made to previous weeks. It might be interesting to plot "last week" and "this week".
##

**Comment by paglias** [comment]
@ghswa thanks for the report. The graph is made taking your last cron, substracting 7 days and showing all the values in the middle. Can you give me your UUID so that I can check wheter the data is ok?

**Comment by ghost** [comment]
UUID: 40891154-6548-4dc0-a752-adc284396af0

Are you able to check when I used the orb, when I've been in the inn and when I've had crons? I don't want to confuse matters by trying to recall them from memory (and getting it wrong).

**Comment by paglias** [comment]
@ghswa sorry for the delay in the answer. The way the graph is built it done taking the last week values for experience history from the db. Unfortunately it seems that rebirth is doing some operation on those values that cause them to appear in that strange format on the graph. You should get another email in less than 7 days, if the problem persist, let me know.

A normal graph will be like this one:

![selezione_036](https://cloud.githubusercontent.com/assets/589911/8271117/6a4e1910-1806-11e5-9141-8787773b7298.jpg)

Regarding i18n dates, I just want to be sure that a longer format like `Jun 10` won't cause dates to overlap when there are more values in the graph.

And finally, regarding comparison to last week: it would be a very cool feature but unfortunately we compress values in the db after some time or they would grow too much and kill our database. We're in the middle of an overhaul and this might be possible in the future but now it isn't.

Thanks

**Comment by librarianmage** [comment]
@Alys As the weekly progress emails are currently turned off, is this still an issue?

**Comment by paglias** [comment]
@MathWhiz we want this to stay open for when we'll restart weekly recap emails

**Comment by librarianmage** [comment]
@paglias That makes sense

**Comment by paglias** [comment]
Going to close this since when we'll restart weekly emails we'll redesign them
