### ISSUE TITLE
Size of Login button?

### ISSUE THREAD

**Issue by carolstone** [HabitRPG/habitica#5425]
As an utter newbie having a hard time getting myself logged into local habitrpg once I finally got my vagrant box to run "npm start" successfully, I found myself incredibly irked by the tiny login button. I am no graphic designer, but the various button widths on the page were bugging my sense of balance. Further research showed me there are 3 buttons that are narrower and controlled by the same .css file. Login, Submit (forgot password) and Register. Here are pictures of the current button width:

![current login](https://cloud.githubusercontent.com/assets/9287541/8241913/0352e566-15da-11e5-858c-6c551505dfd7.PNG)
![current register](https://cloud.githubusercontent.com/assets/9287541/8241606/55dc1a20-15d8-11e5-8b02-72ef930d4b43.PNG)

I would like to modify them to be the same width as the input areas, like this:
![proposedlogin](https://cloud.githubusercontent.com/assets/9287541/8241655/9bb7ea06-15d8-11e5-8881-3930ecee02d1.PNG)
![proposedregister](https://cloud.githubusercontent.com/assets/9287541/8241662/a36770e6-15d8-11e5-9baa-bf8f1a8d5b50.PNG)

I figured out how to do it, and it's just a little css change (addition of .btn-block) in 3 places. But it would be a great start for me, since I am at a point where I'd like to learn to create a branch and issue a pull request. Is there any interest in this? Is it the way it is for a reason? Is it on a bucket list somewhere to make it match a different width? (I'd love to go figure that out!)

**Comment by Alys** [comment]
@AnitaYCheng and @lemoness What do you think?

**Comment by lemoness** [comment]
I kinda like it, but definitely would like a designer's input.

**Comment by crookedneighbor** [comment]
I think we should also be using the btn-lg class

**Comment by AnitaYCheng** [comment]
Btn-lg is good. A block button that goes all the way across might be misleading since people can interpret that as a heading or separate section instead of a button. If it's going to be a block and go all the way across, it should be taller as well, to convey its "button-ness."

**Comment by carolstone** [comment]
So you can see it, here are two pictures with btn-lg and btn-block. It does set them off a bit better from the forgot password header.

![loginwithbtnlg](https://cloud.githubusercontent.com/assets/9287541/8297030/719cec7a-1926-11e5-8738-78fc4d178f64.PNG)
![registerwithbtnlg](https://cloud.githubusercontent.com/assets/9287541/8297032/7561904a-1926-11e5-8c64-5c35d4d49f22.PNG)

**Comment by harrislapiroff** [comment]
+1 on using `.btn-block` and `.btn-lg`.

**Comment by carolstone** [comment]
This appeared in the last upgrade. I'm going to close the issue. Thank you, all!
