### ISSUE TITLE
Guild doesn't have a leader

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5426]
The [Library of Shared Lists Guild](https://habitrpg.com/#/options/groups/guilds/adcd6903-e3c6-4c27-a0e9-21f2e7515cd6) doesn't ~~appear to~~ have a leader.

![selection_033](https://cloud.githubusercontent.com/assets/7059890/8244178/dbd56ac4-15eb-11e5-9465-64262bbfced9.png)

~~If this is true~~ Checks should be added to prevent this from occurring. 

EDIT: Just checked this with the API, and the group definitely doesn't have a leader. The relevant entry is: `"leader": null`

Off the top of my head, situations that may lead to this:
1. Leader leaving a group
2. Leader deleting their account

The question is what to do if this happens. Randomly assigning leader to another group member doesn't seem wise. Since cases like this are probably rare, maybe the admins should be notified somehow?

**Comment by Alys** [comment]
The leader deleted their account without first leaving the guild.

I've started a nomination and voting process in the guild to choose a new
leader.

I've added a comment to https://github.com/HabitRPG/habitrpg/issues/5253 to
report this.

**Comment by hairlessbear** [comment]
Thanks @Alys.
