### ISSUE TITLE
Unable to login to site with Facebook Account with Microsoft Edge

### ISSUE THREAD

**Issue by TheWebJustWorks** [HabitRPG/habitica#5428]
Hi from Microsoft!  Here is an issue that has been identified on habitrpg.com using Microsoft Edge (https://blogs.windows.com/msedgedev/2015/04/29/introducing-microsoft-edge-the-browser-built-for-windows-10/) the new browser included with Windows 10 (https://insider.windows.com/)

Reference #: 2233810
Steps to Reproduce:
1. Using Microsoft Edge navigate to https://habitrpg.com/static/front 
2. Click on the Play for free button
3. Click on "Login/Register with Facebook"
4. Enter credentials and click Login
5. Observe that user is not able to login to the site with a Facebook account

Developer Notes: Habitrpg has the following code

```
            l = function(a) {
                var e = window.open(a, "_blank", "resizeable=true,height=" + d + ",width=" + c + ",left=" + j + ",top=" + k);
                if (e && e.addEventListener) {
                    var f = hello.utils.url(b),
                        g = f.origin || f.protocol + "//" + f.hostname;
                    e.addEventListener("loadstart", function(a) {
                        var b = a.url;
                        if (0 === b.indexOf(g)) {
```

In this code, it's effectively doing this
    var e = window.open('facebook...)
    if (e && e.addEventListener) {
        ...
    }
    someMoreScript();

Attempting to access e.addEventListener is thrown an access denied exception because e is for a facebook url and the caller is running in the habitrpg.com domain.  In Chrome this works because window.open doesn't navigate the new window away from about:blank (which the caller does have access to) until after the script block returns.  In Microsoft Edge, the window.open opens up an asynchronous navigation that progresses immediately, introducing a race condition between the window.open call and attempting to evaluate e.addEventListener.  That race condition almost always results in the query of addEventListener throwing an access denied exception which keeps someMoreScript() from executing.

Rather than continue to propagate this race condition, we recommend that the site not depend on this behavior.  From our analysis, it's non-obvious what the event listener being added is intending to do and we were unable to find an instance of it firing in either IE11 or in Chrome.  Here are two possible solutions for resolution.
1.  Remove the addEventListener portion of the code completely 
2.  Add a try/catch around the addEventListener query so that the code which needs to execute after will still execute

Thanks!
##

**Comment by SabreCat** [comment]
In fact, I'm finding that I can't launch the login window _at all_ on Microsoft Edge. I cilck "Play Now" or any of the other blue login buttons on the front page, but nothing happens. The developer console doesn't show anything awry happening.

**Comment by pezbemine** [comment]
Was any solution found for this? I'm not able to use Microsoft Edge to log into Habitica using the Facebook log in. A window pops up for a moment and then closes.

**Comment by TheWebJustWorks** [comment]
Not getting a repro here in Windows 10 and was able to log in using Facebook UI. Screenshot or Video would be helpful - thanks!

**Comment by pezbemine** [comment]
If I click on Login/Register with Facebook, this window pops up and then disappears and I'm not logged in.
![wp_20160113_15_56_35_pro](https://cloud.githubusercontent.com/assets/16688729/12307632/7d79c32c-ba0e-11e5-9405-641bd3062a02.jpg)

**Comment by TheWebJustWorks** [comment]
thanks for the feedback - still not seeing a repro whether logged in or not. Will investigate further

**Comment by Kiphen** [comment]
I'm seeing the same issue in Edge on Windows 10 Mobile, build: 10.0.10586.63

When I tap on the Facebook login the page will refresh and not log me in.

**Comment by ATTILA0817** [comment]
Same problem on W10M and Desktop Edge FB login not working

**Comment by syts** [comment]
Can repro this on Surface Pro 4, Windows 10, Microsoft Edge 38.14393.0.0

**Comment by stillnotsure** [comment]
Getting the same issue on Surface Pro 3, Windows 10, Edge 38.14393.0.0

**Comment by paglias** [comment]
This should be fixed now, can you try it and check?

**Comment by Kiphen** [comment]
@paglias It works! Tried on Edge - Windows 10 Mobile
