### ISSUE TITLE
Critical hits don't add to quest damage

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5429]
While poking around in the algorithms for doing damage to quest monsters, I noticed that critical hits don't actually do any more damage to boss monsters than normal clicks. Crits are assessed during `addPoints()`, which occurs after `changeTaskValue()` where boss damage is applied.

This strikes me as very sad! Warriors ought to dish out extra damage via their mighty critical blows, but alas, they avail them nothing.
##

**Comment by abatula** [comment]
Is this still an issue that should be fixed? If so I can work on it.

**Comment by Alys** [comment]
@abatula Please go ahead, thank you!

**Comment by x-N0** [comment]
Is this really fixed? It's something that still happening.

**Comment by Alys** [comment]
@x-N0 can you please give us details about what you're seeing that makes it look like this bug is happening?

**Comment by x-N0** [comment]
Sometimes I get 500%, and when I attack the amount of damage given is not the amount that will apply with the 500%, its just the amount given from my stats or my power attacks... so I don't really know if that's a normal thing or...??

**Comment by x-N0** [comment]
I gotta take a closer look at the stats, I'm starting a new quest, I will take a closer look to the damage I deal from my super attacks and will be back with any observation, Im using this formula from the wikia:

`1.5 + {(4 x STR) / (STR + 200)} = overall damage multiplier`

The multiplication is done at the end of my cron (when the damage gets applied)? or it's done before the points reach the party's quest statics?

**Comment by Alys** [comment]
@x-N0 All calculations are done at the time that a task is completed, so you should see the damage multiplier having an effect on your pending damage immediately.
