### ISSUE TITLE
Class change reports that I've equipped old class's gear instead of new.

### ISSUE THREAD

**Issue by relsqui** [HabitRPG/habitica#5430]
Apologies if this is a dupe; I did a search but didn't see anything that looked right. I'm using Chromium in Ubuntu and my user ID is 6b0c10d3-85e9-4d03-8b8e-1306bf1ee35f.

My class for the last couple dozen levels and few weeks has been wizard. I just purchased a class change, going from wizard to rogue, and was reassured that my old class gear was in my inventory, while I'd been freshly equipped with "apprentice wizard gear" (not rogue). My new class and equipment are correct; it seems to be just the message which is wrong.

Attempting to reproduce it, I changed class again from rogue to healer. The message still said "apprentice wizard gear" (neither rogue nor healer). Refreshing cleared the message, so I couldn't see if it affected anything.

I then hard-refreshed and did one last change from healer back to rogue. This time the message said "apprentice healer gear."

The message I saw was this one: https://github.com/HabitRPG/habitrpg/blob/4042c1ce7ae07c84da927501d7915cd828a10be3/common/locales/en/npc.json#L31
It seems to be getting its variable here: https://github.com/HabitRPG/habitrpg/blob/1743899dd49adae7887f73c300f9802a35307b9b/website/public/js/services/guideServices.js#L60

I'm not familiar enough with HabitRPG's tech stack yet to trace it further, but I might take a crack at it later if someone doesn't beat me to it. :)

**Comment by Alys** [comment]
Hi @relsqui. This has been reported at https://github.com/HabitRPG/habitrpg/issues/4888 but it took me two searches to find it and I already knew it existed, so don't feel bad about not finding it. :)  One fix was proposed by adding a watch but we're trying to reduce the number of watches so we didn't accept that approach.

If you'd like to work on it, please do! We should consolidate this into one issue so I'm closing this now, but please do copy your comments to that issue if you wish to, and definitely drop a note into it if you decide to work on it.

I'm refunding you the six gems you spent testing this (thank you!!!). Tell me if I have miscounted. :)

**Comment by Alys** [comment]
I've just edited the title of that old issue, so it might be easier to find in future.
