### ISSUE TITLE
Damage to boss by quest leader immediately after starting quest

### ISSUE THREAD

**Issue by diyadas** [HabitRPG/habitica#5436]
As far as I can tell from what people have explained to me, this was not supposed to happen:

I manually started a quest yesterday 6/19, around 13:30 (as quest leader). Almost immediately afterward, when I refreshed my party chat, I found that I had dealt damage to the quest boss.

My custom day start is set at 5:00, and I think I first logged in around 11:00, though I may be misremembering this.

Group ID: 07f1c3d2-3c8d-46c8-bfba-e32acd1ce50f
User ID: 13018811-220f-4025-93a0-9ed6b6a21032
##

**Comment by Alys** [comment]
@InfH I'm sorry we didn't reply to this. I do recall seeing it at the time, and I kept a watch out for other examples of the same bug, but we haven't seen any. I think this was a once-off glitch. We're actually part way through rewriting a large amount of the site's code to improve its performance and reliability, so once that goes live, problems like this should be much less common.
