### ISSUE TITLE
Emoji for Dailies checklist not appearing on iOS

### ISSUE THREAD

**Issue by Sabnak69** [HabitRPG/habitica#5438]
Hi,

have set up the dailies with Emoji inside the checklist, works fine with the web app, but only the emoji for the higher level Daily is showing on iOS,the ones for the checklist do not appear and the emoji code is visible instead.

**Comment by Alys** [comment]
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if anyone has any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com
