### ISSUE TITLE
Strange issue when attempting to purchase Coral Collar, Shining Capelet, Eyepatches

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#5439]
http://i.imgur.com/nTe3A96.jpg
after clicking OK: http://i.imgur.com/gbunuXg.jpg

I closed mobile safari, cleared website data for habitrpg, and logged back in, but that hasn't had any apparent effect. There doesn't seem to be any way to purchase the Coral Crown at the moment. Alas, I have not checked if this is an issue with any of the other Seasonal Shop items yet because my equipment being out of order bugs me way too much.

**Comment by Alys** [comment]
Thanks for letting us know! We're looking into it now.

**Comment by Alys** [comment]
Confirmed.

**Comment by Alys** [comment]
Found the cause. Working on a fix.

**Comment by Alys** [comment]
@GrayDays I've made a fix that works locally and I'm pushing it to our test site now. After that I'll push it to production. You should be able to buy the item in the next half hour. I'll comment here when it's live.

Thank you very much for reporting this so quickly! We appreciate knowing about bugs promptly!

**Comment by Alys** [comment]
And... I forgot to comment here when it was live. @GrayDays It should be all working now.
