### ISSUE TITLE
Can't buy pirate eye-patch without buying more gems

### ISSUE THREAD

**Issue by swissdot** [HabitRPG/habitica#5440]
Hello!

Even though I have seven gems in my inventory, when I try to buy the pirate eye patch from the newly-opened seasonal shop, I get a prompt to buy more gems:

![screen shot 2015-06-21 at 9 07 10 am](https://cloud.githubusercontent.com/assets/12563127/8270817/7d6e1776-17f6-11e5-9058-b3b048485428.png)

My husband is also a Habit RPG user and has found the same thing.

Thanks for your help!
swissdot

**Comment by Alys** [comment]
It's the same issue as this one, which is in the process of being fixed. In about an hour, please reload the Seasonal Shop and it should be working correctly.

(FYI, I added "eyepatches" to the title of that issue just now, so if you searched for it before logging this one, you wouldn't have found it.)
