### ISSUE TITLE
"Please choose the Mystery Item Set you would like." Where?

### ISSUE THREAD

**Issue by Cassolotl** [HabitRPG/habitica#5442]
I'm in the Time Traveller section, and it says "please choose the Mystery Item Set you would like" but there is no obvious place to choose and no explanation.

![screen shot 2015-06-21 at 09 40 38](https://cloud.githubusercontent.com/assets/6607512/8271043/1760bd7c-17fa-11e5-810f-614f91d6093a.png)

If it's because I've got them all (and I don't think I have), there should be some "you've got them all" message, right? And it says "You can see a list of the past item sets [here](http://habitrpg.wikia.com/wiki/Mystery_Item)!" which links to the wiki page showing all the past items, but that's not a way to select an item you would like.

**Comment by Alys** [comment]
You're right that the wiki won't let you choose the items but it will let you see them all, and you can compare them with the "Mystery" section in you Equipment page. However it is most likely that you do have them. I've just tested the Time Travellers page and it's working as expected for me.

**Comment by Alys** [comment]
@lemoness Would you like a message to be added to that page for the case when the user already owns all Mystery Items?

**Comment by Cassolotl** [comment]
@Alys @lemoness 

> Would you like a message to be added to that page for the case when the user already owns all Mystery Items?

That would be brilliant, and would have resolved my confusion immediately. :)

**Comment by lemoness** [comment]
Yes, good idea!

"Congratulations! You already own all of the Mystery Items. Thanks for
supporting the site!"

**Comment by Alys** [comment]
I've advertised this in Aspiring Coders.

**Comment by melarish** [comment]
Working on this right now. So far I've managed to add a Debug menu function to add an Hourglass to my test user, so I can actually get to the Mystics screen. Will post again if I have more updates/issues.

**Comment by melarish** [comment]
Does this look okay? 

![image](https://cloud.githubusercontent.com/assets/5783115/9741274/70ddc8b4-5651-11e5-85d3-0d5013a65767.png)

**Comment by Alys** [comment]
@melarish I think it would look nicer if there was a bit more whitespace above the new message - perhaps about 1em or thereabouts? But that's basically what we're after, so feel free to do a PR!

**Comment by crookedneighbor** [comment]
Would it make more sense to be in an alert box?

**Comment by Alys** [comment]
Alert boxes need to be dismissed. I'm not sure the extra step is necessary here.

**Comment by crookedneighbor** [comment]
Sorry, I meant the bootstrap alert class.

**Comment by melarish** [comment]
Added a margin of 1em; created pull request.

**Comment by melarish** [comment]
Added a margin of 1em; created pull request (sorry for double PR, I forgot to upload the latest code!)

**Comment by unwitting** [comment]
@melarish could you reference the PR here? Is it closed now? If so, sounds like this issue's closable!

**Comment by Alys** [comment]
@unwitting Excellent point, thank you!

https://github.com/HabitRPG/habitrpg/pull/5903 (closed)

https://github.com/HabitRPG/habitrpg/pull/5904 (merged)
