### ISSUE TITLE
Is there any reason in having Guild Bank displaying zero balance - maybe hide it?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5444]
Currently, I see no point in showing the `0 Guild Gems` (Guild Bank or wallet) message for the guilds after the initial 4 Guild Gems have been used for creating challenges. 

My suggestion is to hide the message of the Guild Bank when there's no more Gems left:
- it will save a line for the message from the guild leader / chat for most guilds
- it won't affect marketing/paying/donation aspects as there's no way to refill the balance currently
- it will save some users from wondering how to refill the balance (again, there's no such feature currently)

Guild Bank is not a feature of common use. I believe even if there are some question about why guild bank is not shown - the answer is quite logical and may be addressed in the [Guild Bank section of the wiki page for guilds](http://habitrpg.wikia.com/wiki/Guilds#Guild_Bank).

I'm making a commit - not because I'm sure about it, but rather for quite the opposite reason - I'm not sure I'm thinking about implementing it the right way. I will appreciate comments and help with this suggestion.

**Comment by crookedneighbor** [comment]
Personally, I'd like there to be a way to add gems to the guild bank, rather than hiding it when there are none.

**Comment by ghost** [comment]
@crookedneighbor Apart from discussion in https://github.com/HabitRPG/habitrpg/issues/1774 I believe I've seen some discussion in chat mentioning that guild bank is not a high priority feature after introduction of the _send-gift_ feature which can be used to send gems to guild leader or any other user.

That's what made me thinking about having a constant `0 Guild Gems` line in most guilds as something that may be rather discouraging. Of course hiding it is a temporary thing, not addressing functionality of the Guild Bank. I believe its extension may be a separate discussion for Trello.
