### ISSUE TITLE
Button in Alexander the Merchant popover is too long (with certain strings)

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5446]
Originally reported in [#5209](https://github.com/HabitRPG/habitrpg/issues/5209#issuecomment-112869188).

![a](https://camo.githubusercontent.com/e1f9045642af11314f354be8de871cc24365bb0b/687474703a2f2f692e736e61672e67792f574a5374672e6a7067)

![selection_034](https://cloud.githubusercontent.com/assets/7059890/8272028/8de1b904-1801-11e5-8bb7-60cca0f08d90.png)
##

**Comment by ghost** [comment]
I'd say the popover is too narrow for such button =)

Possible solutions I've been thinking of:
- making the popover wider like the popovers in the Seasonal Shop or Time Travelers. However I haven't found a way to do it; though, I believe it shouldn't be difficult - it's just about me not being a programmer =(
- restyling popover in a way so that it would say:
  - p="Welcome! ..."
  - p(if item selected)="Oh, don't you need that < strong>(Adjective) Item< /strong> you possess?"
  - button(if item selected)="Sell one for # Gold"

**Comment by crookedneighbor** [comment]
Y'all, this could be solved quite easilly by adjusting the nowrap property of the button:

![screen shot 2015-06-21 at 10 05 34 am](https://cloud.githubusercontent.com/assets/2916945/8272133/396ee31e-17fd-11e5-8993-591e297f58fa.png)

Though, that said, I'm intrigued by @GitHubSphinx's idea. It would require some refactoring for how the button works, but that's not a bad thing.

**Comment by hairlessbear** [comment]
@crookedneighbor I probably should've mentioned that I posted this in the Aspiring Coders guild. Would you mind adding the "entry level coding" label?

**Comment by crookedneighbor** [comment]
Done

**Comment by hairlessbear** [comment]
:+1:

**Comment by ghost** [comment]
@crookedneighbor of course if there's a simpler solution, it should be the one to be used, I believe

**Comment by crookedneighbor** [comment]
Well, a wrapping button looks better than a button bursting out of the popover, but it still doesn't look great in my opinion. Here's a mockup of your idea:

![screen shot 2015-06-21 at 10 41 58 am](https://cloud.githubusercontent.com/assets/2916945/8272288/2dde1f92-1802-11e5-8090-0c9aa77ac39a.png)

**Comment by crookedneighbor** [comment]
@lemoness What do you think of that?

**Comment by hairlessbear** [comment]
Oh wow, that looks cool! One minor thing: I'd change the wording to "you don't need" instead of "don't you need".

I really like that change. The image makes it much easier to ensure that you're selling the correct item. And it looks better too.

**Comment by ghost** [comment]
@crookedneighbor It's actually much better image of what I've thought of! Great!

@hairlessbear I'd vote for keeping it a question rather than a statement
I've suggested "Sell one for # Gold" to highlight the fact the user is not suggested to sell _all_ items of the kind - for the sake of right understanding by newbies.

However, I'm not sure about both aspects - if they do sound right for native speakers

**Comment by crookedneighbor** [comment]
I think specifying that you're selling a single one is good. As for the exact wording, I'll let @lemoness make the call.

**Comment by ghost** [comment]
@crookedneighbor Thank you very much! And please excuse me for being the cause why this old issue has become worse...

Letting the staff decide on wording (of course) I just wanted to mention I could have been wrong when suggesting a negative type of question. @hairlessbear thank you for your comment! After reconsidering it, I've understood I might have been wrong in translating my thoughts into English. I thought of the question that will suggest "I've noticed something interesting that you own! If you don't need it, I can take it from you!" - and in English I guess it would be closer to "Oh! _Do_ you need that < strong>(Adjective) Item< /strong> you own?". However, once again I can't know for sure which words will sound natural to a native speaker (so please excuse me for making suggestions at all =)

**Comment by crookedneighbor** [comment]
Not a big deal. The issue was there before. And your proposed solution is very :+1: in my opinion.

**Comment by lemoness** [comment]
Definitely "Oh, you don't need that NAME?" - otherwise, it sounds like Alex
is questioning your decision to sell.

Actually, something more straightforward like "Do you want to sell your
NAME?" may be even less confusing.

**Comment by crookedneighbor** [comment]
I prefer the "Do you want to sell your <ITEM>?" option.

**Comment by hairlessbear** [comment]
Ditto. Zero ambiguity and it still allows for the UI improvement.

**Comment by ghost** [comment]
It does sound better!

**Comment by lemoness** [comment]
Great, let's go with that one!

**Comment by mxrowanthomas** [comment]
Is anyone working on this? If not I'd like to have a go as a first contribution.

**Comment by ghost** [comment]
Hmm, screenshots above gave me an impression that @crookedneighbor got it elegantly fixed and trying to replicate them would be a "duplicate effort". @crookedneighbor please excuse me if I got it wrong and screenshots were there only to encourage other contributors ((

**Comment by crookedneighbor** [comment]
I didn't change any code. I just manipulated the dom using the Chrome inspector. 

@mxrowanthomas Please go for it.

**Comment by mxrowanthomas** [comment]
@crookedneighbor I thought that would be the case I will get on with that.

**Comment by bagedevimo** [comment]
I'd like to maybe have a go at this, if you're not still working on @mxrowanthomas?

**Comment by crookedneighbor** [comment]
@bagedevimo It's been a month since @mxrowanthomas mentioned wanting to work on it. I say go for it.

**Comment by mxrowanthomas** [comment]
@bagedevimo please do go for it. @crookedneighbor I've been unexpectedly overwhelmed with work as well as illness the past month, I will contribute once things are a bit quieter.

**Comment by crookedneighbor** [comment]
@mxrowanthomas Looking forward to your contributions!

**Comment by Zibidibodel** [comment]
@bagedevimo  any update here / are you still working on fixing this?

**Comment by crookedneighbor** [comment]
If someone doesn't get on this soon, I'm going to do it myself :smile:

**Comment by Zibidibodel** [comment]
I have the instance all set up locally and will have it fixed tonight (unless there's some crazy string that gets pulled) I just don't want to step on toes.

**Comment by Thrashmandicoot** [comment]
@crookedneighbor heya, I decided to work on this since the last activity is on Aug 22nd. Here's what I've got so far.

![wolf-egg-market](https://cloud.githubusercontent.com/assets/7241887/10355952/7bc5e9a0-6d26-11e5-877f-a4b252055ce1.png)

Todo:
The wolf egg is a placeholder. I figure the best way to approach getting the image is to extract the class of the selected item and re-apply the class to my div via the javascript egg/item selector functions.

What I have a question on, is how would one go about applying bold to just the json variable for jade?

For example:

``` html
div(ng-show='selectedEgg || selectedPotion || selectedFood')
              div.customize-option.Pet_Egg_Wolf(style='float:left;' ng-show='selectedEgg')
              div(style='float:left;width:70%' ng-show='selectedEgg')=env.t('displayEggForGold', {itemType: "{{selectedEgg.text()}}"})
```

itemType is what shows the custom wolf egg text, but I'm not sure how to just get that particular piece bold. Do you maybe have a recommendation or point in the right direction? I appreciate any feedback. :metro:

**Comment by Alys** [comment]
@Thrashmandicoot Bolding can be inserted in the locales file that contains the 'displayEggForGold' string. As an unrelated example, this is from common/locales/en/settings.json :

`"deleteText": "Are you sure? This will delete your account forever, and it can never be restored! You will need to register a new account to use Habitica again. Banked or spent Gems will not be refunded. If you're absolutely certain, type <strong><%= deleteWord %></strong> into the text box below.",`

**Comment by Thrashmandicoot** [comment]
@Alys thanks! That worked out great.

I added the bolding to the item, how's this look? If it looks good, I'll finish up the fixes and probably submit the pull later this eve.

![newmarket](https://cloud.githubusercontent.com/assets/7241887/10356751/3ec6b18e-6d2f-11e5-8681-2d95d5dafde7.png)

**Comment by crookedneighbor** [comment]
Looks great!

**Comment by Thrashmandicoot** [comment]
I made a pull request with the fixes and changes. Please review :) :metal: 

My apologies for the delay, moved, switched computers, and needed to re-setup all my environments.
