### ISSUE TITLE
503 error - is this a planned downtime?

### ISSUE THREAD

**Issue by carolstone** [HabitRPG/habitica#5450]
I have access to tracert info from two different IP addresses (both in CT, but via different cable providers). Posting in case you need it. First here, 2nd in next comment.

Tracing route to habitrpg.com [54.235.89.55]
over a maximum of 30 hops:

  1     2 ms     1 ms     1 ms  source - me
  2     \*        \*        \*     Request timed out.
  3    10 ms     9 ms     8 ms  crr01nwtwct-tge-0-4-0-19.nwtw.ct.charter.com [96.34.87.117]
  4    17 ms    18 ms    15 ms  bbr01nwtwct-bue-1.nwtw.ct.charter.com [96.34.2.40]
  5    22 ms    22 ms    23 ms  bbr02ashbva-bue-2.ashb.va.charter.com [96.34.0.48]
  6    21 ms    20 ms    21 ms  prr01ashbva-bue-6.ashb.va.charter.com [96.34.3.89]
  7    24 ms    19 ms    18 ms  96-34-148-54.static.unas.mo.charter.com [96.34.148.54]
  8    24 ms    26 ms    30 ms  54.239.108.238
  9    20 ms    22 ms    21 ms  54.239.109.45
 10    21 ms    21 ms    22 ms  205.251.245.234
 11     \*        \*        \*     Request timed out.
 12     \*        \*        \*     Request timed out.
 13     \*        \*        \*     Request timed out.
 14    20 ms    29 ms    33 ms  216.182.224.91
 15     \*        \*        \*     Request timed out.
 16     \*        \*        \*     Request timed out.
 17     \*        \*        \*     Request timed out.
 18     \*        \*        \*     Request timed out.
 19     \*        \*        \*     Request timed out.
 20     \*        \*        \*     Request timed out.
 21     \*        \*        \*     Request timed out.
 22     \*        \*        \*     Request timed out.
 23     \*        \*        \*     Request timed out.
 24     \*        \*        \*     Request timed out.
 25     \*        \*        \*     Request timed out.
 26     \*        \*        \*     Request timed out.
 27     \*        \*        \*     Request timed out.
 28     \*        \*        \*     Request timed out.
 29     \*        \*        \*     Request timed out.
 30     \*        \*        \*     Request timed out.

Trace complete.

**Comment by Alys** [comment]
It's not planned downtime. I think if ever we were going to do planned downtime, we'd put out a notification about it.

The site is working for me, although perhaps a bit slower than usual. Can you please try reloading? If it still doesn't work, try again after a few minutes.

**Comment by carolstone** [comment]
Tracing route to habitrpg.com [50.17.188.0]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  - me
  2     8 ms     7 ms    10 ms  50-78-28-110-static.hfc.comcastbusiness.net [50.78.28.110]
  3     \*       25 ms    20 ms  te-0-7-0-4-sur01.bristol.ct.hartford.comcast.net [68.87.153.153]
  4    23 ms    25 ms    28 ms  be-55-ar01.berlin.ct.hartford.comcast.net [68.85.106.201]
  5    27 ms    39 ms    21 ms  be-55-ar01.berlin.ct.hartford.comcast.net [68.85.106.201]
  6    23 ms    27 ms    38 ms  he-0-11-0-0-ar01.needham.ma.boston.comcast.net [162.151.112.17]
  7    26 ms    30 ms    82 ms  he-0-11-0-0-ar01.needham.ma.boston.comcast.net [162.151.112.17]
  8    37 ms    37 ms    39 ms  be-7015-cr01.newyork.ny.ibone.comcast.net [68.86.90.217]
  9    37 ms    25 ms    29 ms  he-0-15-0-0-pe03.111eighthave.ny.ibone.comcast.net [68.86.84.250]
 10    42 ms    31 ms    25 ms  as16509-3-c.111eighthave.ny.ibone.comcast.net [50.242.148.118]
 11    34 ms    39 ms    37 ms  54.240.229.82
 12     \*        \*        \*     Request timed out.
 13     \*        \*        \*     Request timed out.
 14     \*        \*        \*     Request timed out.
 15     \*        \*        \*     Request timed out.
 16    48 ms    41 ms    34 ms  72.21.222.149
 17    33 ms    37 ms    38 ms  72.21.222.149
 18     \*        \*        \*     Request timed out.
 19     \*        \*        \*     Request timed out.
 20     \*       56 ms    31 ms  216.182.224.73
 21    43 ms    38 ms    51 ms  216.182.224.73
 22     \*        \*        \*     Request timed out.
 23     \*        \*        \*     Request timed out.
 24     \*        \*        \*     Request timed out.
 25     \*        \*        \*     Request timed out.
 26     \*        \*        \*     Request timed out.
 27     \*        \*        \*     Request timed out.
 28     \*        \*        \*     Request timed out.
 29     \*        \*        \*     Request timed out.
 30     \*        \*        \*     Request timed out.

Trace complete.

**Comment by carolstone** [comment]
I waited about 10 minutes before posting anything, but I think you're right - the comcast one goes through quickly now. I'll re-check the charter.

**Comment by carolstone** [comment]
Seems good from charter now, too. I'll close this myself. Sorry to bother you.

**Comment by Alys** [comment]
No worries. :) If it had been a real thing, your troubleshooting would have been useful! Thank you for taking the time to report it.
