### ISSUE TITLE
Errors and (purchased) inventory disappearing after refresh

### ISSUE THREAD

**Issue by joyheron** [HabitRPG/habitica#5454]
![screenshot](https://cloud.githubusercontent.com/assets/1502724/8280800/5d65bd44-18e1-11e5-9687-acc63853ac05.png)

I've been getting a lot of errors (see above screenshot) which I think are related to the seasonal shop (and perhaps syncing errors). I had purchased all of the equipment from the seasonal shop with gems AND used gems to change classes and buy all of the seasonal gear for all of the other classes. And I know that I actually bought it because I was able to dress my avatar in pirate equipment. 

Now, after a refresh, a lot of my equipment is gone (including 8 items I purchased with gems).

![screenshot-1](https://cloud.githubusercontent.com/assets/1502724/8280938/e60876cc-18e2-11e5-8232-1bcc49fab927.png)

There doesn't seem to be any pattern in the items that are missing (I think the sailor outfit is complete, but I only retained one item from the Rogue set that I purchased).

After all of my purchases, I had approximately 1000 GP. Now almost all of it is gone. I lot my pirate gear and my avatar reverted to wearing the knight gear that it was wearing beforehand. 

I'm not that concerned about the missing GP because I know I can fix it with fcv, but I am still missing the 8 gems that I used to buy the items I no longer have in my inventory and any gems that I will have to use to change classes and get all of the other equipment.

I just refreshed and got this:

![screenshot-2](https://cloud.githubusercontent.com/assets/1502724/8281012/f2bdc22c-18e3-11e5-89da-748d85b12595.png)

Also, and this might be related, this morning while I was checking off my dailies and habits, I didn't get a single drop (and I checked this in User Data Display). Now, when I go into the User Data Display, it says I got 23 drops (and a lot of food has suddenly appeared in my inventory). So I think it is some kind of sync error.

Likely this just due to a server overload problem with the Summer Splash, but I wanted to make a detailed bug report just in case it is useful. A gem refund would be nice (at least for my pirate hat!), but it is also possible that I should just learn to not be so greedy, particularly when the server appears to be slow. =)

User Id: 63e151fa-0a95-47c6-9bfd-6824b19ebcfc

**Comment by polysting** [comment]
This has been happening to me aswell today.

![application error](https://cloud.githubusercontent.com/assets/12999371/8281237/f6da2e16-18e5-11e5-89f4-63faffb44f36.png)

Most of the time when I do something on the site, I get these application errors:

![application error2](https://cloud.githubusercontent.com/assets/12999371/8281259/231ed9ae-18e6-11e5-9424-26cd6c0fa6f5.png)

It never finishes the loading either.

It also says I'm not in a party or any guilds, even though I actually am.

![application error3](https://cloud.githubusercontent.com/assets/12999371/8281317/e82e1a84-18e6-11e5-9378-b4592d96c4d7.png)

![application error4](https://cloud.githubusercontent.com/assets/12999371/8281319/f033c4f4-18e6-11e5-9a64-cf927db941fd.png)

I'm using google chrome and my operating system is Windows 7 64-bit.

User-ID: 7c6ab525-9073-4817-91e6-0bf487ce9da1

**Comment by carolstone** [comment]
FWIW: This is exactly the type of loading error I was getting last night just before I reported the 503 error in issue [5450](https://github.com/HabitRPG/habitrpg/issues/5450). I wasn't having any trouble with missing purchased items (because I wasn't purchasing anything), but partial page loads and errors in the console (but never the same one twice) were typical. I had been getting "server unreachable" messages off and on all day, and eventually I was getting an application error. Good luck figuring out if it's your server or the route to your server.

**Comment by crookedneighbor** [comment]
@joyclark I've refunded your 8 gems. Refresh and let me know if they don't appear for you.

Are you still having issues? I'm not experiencing any connectivity problems at the moment.

**Comment by joyheron** [comment]
@crookedneighbor Thanks. =) I just refreshed and everything appears to be normal now.

**Comment by polysting** [comment]
HabitRPG seems to be working fine now, I don't have any issues anymore.

**Comment by MaidM** [comment]
Similar problems here - I also noticed that some of the pets I had fed up to be mounts had reverted to pets, and I lost a few gems plus several hundred gold in addition to all my new rogue gear.  I also get the pink application error windows at times - as a note, I also use two different laptops and three different mobile devices to log onto habit rpg.  My dailies always appear to be as done as I last left them on whichever device, but inventory goes haywire every time.

**Comment by Alys** [comment]
@joyclark I've refunded you the gems you'll need to changes classes again.

@MaidM I'm afraid we can't help you without specific details. Can you tell us exactly how many gems you lost? We'll also need your user ID to identify your account. To find it, go to Help -> Report a Bug and see the instructions there (step 6 talks about the user ID).

**Comment by joyheron** [comment]
@Alys Thank you. :)

**Comment by mzDem** [comment]
I had a similar problem. I didn't use Gems to make my purchases. But I purchases all my warrior equipment, and now I'm missing the ruby sword and it's back in the rewards section. Which is weird, because I still have my golden sword. I also got a Soothing Lunar Sceptre from the enchanted armoire,  but that's seems to have turned into the head bow. And something like 500 gp disappeared too. Very weird.

**Comment by trotro** [comment]
I had the same issue this morning. Got the screen load trouble then some items were missing.
I purchased rewards and half went away after a refresh. Seems that the same happened to one of my eggs. Dunno if any other items went away.
- I was using chrome version 43.0.2357.130 m (64-bit) on Windows 8.1 and the android mobile app
- player ID : dfb0bc41-bd8a-4e57-8065-143d4f0980e5
- items purchased that are missing now
  - oiled leather armor
  - renegade sash
- items lost
  - one baby panda egg
  - maybe hatch potion or food, I don't know.
    I did the purchased today between 11am and 12pm (UTC+1).
    I think you'll have more information in your logs.

**Comment by Alys** [comment]
@mzDem The Armoire issue is described in https://github.com/HabitRPG/habitrpg/issues/5376 and you can follow that if you want to keep track of the progress of the bug. You'll get the Soothing Lunar Sceptre in a future use of the Armoire. 

@mzDem and @trotro You can use  [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to get back any lost gold.

@trotro I've given you one Panda Cub egg. Please reload your inventory and tell me if it hasn't appeared. Also tell us which hatching potion or food you'd like to have.

**Comment by trotro** [comment]
@Alys thanks. The egg is back. I don't know if I really lost any other items. I thought you might find it in the logs. So don't bother for the food and potion. And thanks for the fix.

**Comment by crookedneighbor** [comment]
We did some work server side. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.

**Comment by wrenns** [comment]
I'm not sure if this is the same issue, but today I bought out of the Enchanted Armoire, and received a Cowboy Hat. It showed up in my inventory, I outfitted my avatar in it, and it stayed for several minutes. It disappeared on refresh, though, and appears to have been replaced by a Gladiator Helm. I can't say for sure whether any gold was lost in the transaction, but I'm not too worried about that - I just want my cool Cowboy Hat back :)

UID: ed9d75b6-780b-4a99-a684-3945f3412cbc

**Comment by KiwiBA** [comment]
I had the same problem as wrenns. it happend two times (not with the same item, but with another) that i had after a few minuits or so another item of the enchanted armoire. 
its no problem for me, but i thought i should write it...
if you need, my ID is: 6b914d15-4f51-4d03-ae2f-f886f31f188a
