### ISSUE TITLE
Jumped up levels

### ISSUE THREAD

**Issue by Kayim42** [HabitRPG/habitica#5455]
Hi
I know that there seem to be some connectivity issues with the site, but I've just noticed that my character has levelled up from 15 to 23 in the last couple of hours!  I've also had a bunch of drops that I don't remember getting.  

My party is still in mid-quest, so it's not XP from that.  And while I've been marking off a few dailies and to-dos, I can't possibly imagine that it's enough for that amount of XP.

If it's _is_ from my tasks, not a problem, but if not, I'd quite like to be returned back to the level I was at please!  

My user ID is 48c20d00-9a35-4b54-836f-5f85b7a2659a
I'm using Firefox browser on Windows 7 and the Android app (it's the same on both).

Thanks

Kayim

**Comment by crookedneighbor** [comment]
We've had reports of intermittent connection problems, so it's likely related to that. 

You can adjust your stats yourself by navigating to Settings > Site and click on the "Fix Character Values" button.
