### ISSUE TITLE
Completed Dailies not counted/recogtnized

### ISSUE THREAD

**Issue by GreenDreamTM** [HabitRPG/habitica#5457]
In addition to the issue of my inventory not loading properly at first (very similar to the one reported in #5454), I woke up to find that the dailies I completed the day before appeared to not be counted (I took damage) and 4 of the 5 that are to refresh were still marked as completed. I've seen this across two machines now.
![haprgerror](https://cloud.githubusercontent.com/assets/13001550/8284099/f1424f0a-18af-11e5-8609-a874b290563a.jpg)

USER ID: 893389a5-a741-4c0e-87da-3259d66d1b37
Browser: Firefox

**Comment by Alys** [comment]
Sorry about this @GreenDreamTM! Please see the Advice section near the top of #4313 especially points 1 and 2. The other points are likely not relevant.

Comment here if you need more help or any clarification!
