### ISSUE TITLE
I had gold taken from an error message

### ISSUE THREAD

**Issue by kirblezgerbelz** [HabitRPG/habitica#5458]
I went to open my HabitRPG to check off what I have done thus far today and an error message kept appearing.  During this time i had 3.5k in gold and 89 silver after I hit refresh it my gold was taken and I was left with 12 gold and 8 silver.  I have had error messages before but refreshing usually helped.  I am not sure what happened with this one.

**Comment by Alys** [comment]
We've had server errors over the past few days (they seem to have stopped now).

You can use [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to restore your gold.
