### ISSUE TITLE
Cron counted dailies that I checked off before cron as uncompleted after cron, but preserved streaks

### ISSUE THREAD

**Issue by Luthien22** [HabitRPG/habitica#5459]
Last night I checked off the majority of my dailies thirty minutes before cron. A couple hours later, I was having issues getting the website to work (I was receiving an "application error" message), so I checked the app on my phone. My phone was able to connect to the servers, and reported those dailies to the server as missed. However, when I logged in this morning on my laptop, the dailies I checked off when I began having server issues were still checked. Furthermore, their streaks were preserved. My user ID is 54da67e5-10cf-4f10-8d14-e0333ec80187

**Comment by Alys** [comment]
Sorry about this @Luthien22! Please see the Advice section near the top of https://github.com/HabitRPG/habitrpg/issues/4313 especially points 1 and 2. The other points are likely not relevant.

Comment here if you need more help or any clarification!
