### ISSUE TITLE
 pop-up with daily totals on mouse over of habits

### ISSUE THREAD

**Issue by peakgeek** [HabitRPG/habitica#546]
It would be nice if similar to the items in the store, when you mouse over the habits a small pop-up would appear telling you how many times you've clicked that habit during the day. 

Allowing Habit RPG to keep track of what we have and haven't clicked would be really helpful.

**Comment by ruddfawcett** [comment]
You can tell the volume of clicks for a particular habit by its background color, but I agree that it would be nice to be able to see an exact number of clicks.

**Comment by Pandoro** [comment]
This has already been suggested before and is part of [Trello card 11](https://trello.com/card/progress-views-and-options/50e5d3684fe3a7266b0036d6/11)

You can vote for it there. I am personally also in favor of such a thing, as it can be very hard to determine if you clicked something or not from the current graphs. 

Closing this. Please vote for that card, but feel free to post here if there are any more questions.

**Comment by wc8** [comment]
Also: [Habit/Reward Day Totals](https://trello.com/c/uaIl9x5r)
