### ISSUE TITLE
Eggs Disappeared from Inventory/Sell Error?

### ISSUE THREAD

**Issue by dinosaurpants** [HabitRPG/habitica#5460]
I sold a significant amount of my spare eggs for gold yesterday but I left about 10 of each so that I'd have plenty to hatch once I earn enough food to turn them into mounts. However today when I launched the site I found that I was missing almost all of my eggs. I don't feel that I was selling them that quickly and by leaving so many it seems like it would be difficult for me to have accidentally sold all of them.

**Comment by Alys** [comment]
I'm afraid we can't help you properly without specific details. Can you tell us exactly which kinds of eggs and how many of each you lost? We'll also need your user ID to identify your account. To find it, go to Help -> Report a Bug and see the instructions there (step 6 talks about the user ID).

**Comment by Alys** [comment]
I'm closing this since we couldn't help without the details we asked for.
