### ISSUE TITLE
Shade Fox Pet

### ISSUE THREAD

**Issue by thekidd1984** [HabitRPG/habitica#5461]
Hi, this is a relatively small issue, but it seems that I can no longer equip my Shade Fox pet. In the pet selection interface I can see my Shade Fox, but its opacity is at about 50% and clicking on it no longer equips it. 

This of course is in no way game breaking, but I thought you guys should know nonetheless.
Thanks!

User ID: dea878ec-d705-41f3-a963-4a113417e73b

**Comment by robeden** [comment]
By chance, did you feed it enough to turn it into a mount? If so, you'll need to hatch a new pet from the market.

**Comment by Alys** [comment]
@thekidd1984 As @robeden says, did you turn it into a [mount](http://habitrpg.wikia.com/wiki/Mounts)?

**Comment by thekidd1984** [comment]
I feel silly now. I'm fairly certain this is what happened, thanks guys!

**Comment by Alys** [comment]
Thanks for letting us know! :)
