### ISSUE TITLE
Blacksmith background blank/missing

### ISSUE THREAD

**Issue by nutloaf** [HabitRPG/habitica#5463]
Hello. I've been in the Tavern for about 2 weeks. I returned today and my background was blank (I had assigned the "blacksmithy" from Set 9: Released February 2015). I went to the backgrounds page to reset it; that particular background (and only that one) is blank, even after several page reloads. Screenshot is hopefully attached.

User ID: adc5292b-1122-4242-a1df-63c2c3c54464
Browser: Safari
OS: OSX 10.10.2 (Yosemite)

Thanks much for any help! :)

![screen shot 2015-06-22 at 3 11 46 pm](https://cloud.githubusercontent.com/assets/13007916/8294453/af477764-18f1-11e5-9597-be57758e3090.png)

**Comment by nutloaf** [comment]
Annnnd... after changing tabs and returning, it seems to have resolved itself. Thanks.

**Comment by nutloaf** [comment]
Gone again, same browser session. Will update if anything else changes.

**Comment by Alys** [comment]
This will be a local browser problem. Please clear your cache and clear local storage and that should fix it. It will probably also fix itself in time as the browser clears its own data. Alternatively you could use a different browser or perhaps incognito mode in the same browser.

**Comment by nutloaf** [comment]
Brilliant. Thank you so much for the quick help, Alys.
