### ISSUE TITLE
"Error processing the string. Please see Help > Report a Bug."

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5465]
![687474703a2f2f692e736e61672e67792f4f464c61612e6a7067](https://cloud.githubusercontent.com/assets/1495809/8302536/816df6da-19da-11e5-8e5e-acffc16f38c3.jpg)

If you see the message **"Error processing the string. Please see Help > Report a Bug."** please take note of which part of the site it was on and what you were doing at the time that it appeared. Read the comments below (if any) to see if anyone has already reported that exact problem - if they have, you do not need to report it again.

If no one has reported it here, please tell us:
1. Which language HabitRPG uses for you.
2. Where on the site the message appears.
3. What you clicked on (if anything) that caused the message to appear.
4. If you think that a screenshot will be helpful to illustrate the problem, you are welcome to include one, but it's not essential.

You do **NOT** need to tell us your User ID, browser, operating system, or JavaScript Console errors.

**Note for Translators:** Most of these bugs come from mistyped variables. IE, if the english string contains `<%= int %>` and a translation renders it as `<%=int%>` or `<% = int %>` or `<%= int>` or any similar combination, it'll display this error. 

_Please note that once we have fixed the error you report here, we might delete your comments and our replies after a few days, to keep this issue easy to use for future errors of this kind. This error reoccurs periodically so retaining all reports of it would get messy after a while. :)_
##

**Comment by andressabertolini** [comment]
This message appears when I use it in Brazilian Portuguese in tasks. 
![image](https://cloud.githubusercontent.com/assets/12105987/8467513/b1076528-2035-11e5-9220-d539ff4c2cfb.png)

**Comment by crookedneighbor** [comment]
@andressabertolini This has been fixed on Transifex and will be deployed to production soon. Thanks for reporting it!

**Comment by Alys** [comment]
For the **pt** language, the Basic Crossbow shows this error in its mouse-over text.

**Comment by Jazzis18** [comment]
This message appears when I hover mouse at item Soothsayer Robes (Мантия Предсказателя) in Item Store:
![2015-07-22_192716](https://cloud.githubusercontent.com/assets/4019829/8827716/b14e60d6-30a7-11e5-84ab-8349aa7af528.png)

**Comment by Anatolt** [comment]
Same message in inventory
![](http://at02.ru/i/2015-07-26_145621.png)

**Comment by crookedneighbor** [comment]
Copied from https://github.com/HabitRPG/habitrpg/issues/5674

> There is no description for Soothing Lunar Sceptre on portuguese language. In English, it shows normal. Just Checked the translation at transifex and there is no problem there.

> I'm Using chrome browser and windows 7.

> ![capture](https://cloud.githubusercontent.com/assets/2285976/8909491/ef1ff934-3457-11e5-8b8b-a6f7b743b22b.PNG)

**Comment by crookedneighbor** [comment]
@Jazzis18 @Anatolt I've just updated the strings on the site. Are you still getting that error?

**Comment by Anatolt** [comment]
@crookedneighbor yep, it still here

**Comment by Jazzis18** [comment]
@crookedneighbor yeah, it still here

**Comment by crookedneighbor** [comment]
@Anatoit @Jazzis18 I've found the offending string on Transifex and fixed it. 

@lothrus I've fixed your string as well. 

Both should be live on the site after  refresh.

**Comment by crookedneighbor** [comment]
@andressabertolini for some reason the crossbow text never did get updated :disappointed: I've fixed it just now and will deploy the change soon.

**Comment by lothrus** [comment]
@crookedneighbor I'm a translator at Transifex for portuguese language. There is something i can do to fix if i see another one or anything i should avoid doing to dont bug it?

**Comment by crookedneighbor** [comment]
@lothrus Most of these bugs come from mistyped variables. 

IE, if the english string contains `<%= int %>` and a translation renders it as `<%=int%>` or <% = int %>` or `<%= int>` or any similar combination, it'll throw this error. 

I'm working on a script that will identify these problems and email the appropriate people to correct it so it can be fixed _before_ the code is deployed.

**Comment by lothrus** [comment]
Good to read that. I will pay attention to it when reviewing. Thank you

**Comment by Jazzis18** [comment]
Now all right :) Thank you.

**Comment by woodroof** [comment]
Hover on item in Rewards section, Russian.
![bug](https://cloud.githubusercontent.com/assets/5821956/8941759/5afbc9d0-3593-11e5-8196-6f1c09bc7053.png)

**Comment by diogoalves** [comment]
1. Language: Brazilian Portuguese
2. Where: in front page, inside help text of "Hábitos, Tarefas diárias, Afazeres, Recompensas"
3. just clicked in ? button
4. screenshot
![captura de tela 2015-07-29 as 17 33 58](https://cloud.githubusercontent.com/assets/326518/8969225/52dc4d58-3618-11e5-8966-8ae49b406a5e.png)

**Comment by lothrus** [comment]
@diogoalves I've fixed that string on Transifex, will be deployed soon. Thank you.

@crookedneighbor There is a way to request a deploy of the offending string or we just wait after fixed on Transifex?

**Comment by crookedneighbor** [comment]
if it gets reported here, I try to deploy after it gets fixed, so I'll do that tomorrow. Just commenting here saying you've fixed it is great.

**Comment by Alys** [comment]
Kampfausrüstung; Verzauberter Schrank; "Viehzüchter Lasso" -- the Lasso has this bug in German. https://github.com/HabitRPG/habitrpg/issues/5704

**Comment by crookedneighbor** [comment]
Lasso fixed with https://github.com/HabitRPG/habitrpg/commit/919c072b5d725fe464acc635fbd5f61128584262

**Comment by Alys** [comment]
Copied from https://github.com/HabitRPG/habitrpg/issues/5735

> Siena Leslie
> Error processing the string. Please see Help > Report a Bug.
> 
> In Season Limited Shop.
> 
> UI use translated Traditional Chinese

**Comment by lothrus** [comment]
@crookedneighbor Found another string with problem in protuguese translation, but i haven't found the problem at transifex. can you have a look please? Thank you.

![capture](https://cloud.githubusercontent.com/assets/2285976/9070244/db0faeb2-3ac4-11e5-9e48-1bf1ccb0f9fe.PNG)

**Comment by crookedneighbor** [comment]
@lothrus The problem is that the English string was updated to use a hardcoded link to the wiki so that translations could point to the language specific version of the article. However, it wasn't updated on Transifex yet, doing that now.

**Comment by crookedneighbor** [comment]
Going to go through here and delete the comments (including this one) that are no longer relevant.

**Comment by Alys** [comment]
From Tavern by Eli1802 (f8d2ed19-f180-4801-b268-9bb0ba069793) `"language": "it"`

Does anyone else have problems with the Blue Hairbow? When I pass my mouse over it tells me "error processing the string"...

**Comment by ghost** [comment]
@Alys this line has English text from other Hairbow copied as translation. I've replaced it with original English text, which should solve the issue, but the line will still need attention from Italian translators

Upd: I've deleted the false "translation" for this line on Transifex  so it will be shown untranslated.

**Comment by ghost** [comment]
Hello dear people from Habitica, encountered my first error today...
Which language HabitRPG uses for you: Dutch
Where on the site the message appears: This bug appears at my stats page at the ''perfect day'' notification.
What you clicked on (if anything) that caused the message to appear: I had a ''perfect day'' and it won't process it.
Thanks!

**Comment by crookedneighbor** [comment]
@GitHubSphinx I wrote a version 1 of the task to detect bad strings, but it sorely needs to be rewritten. 

I'm thinking about having the strings get updated automatically whenever we do a production deploy, and detect bad strings then which would automatically post to transifex to remove the bad translation and leave a comment about the error.

**Comment by mchlltt** [comment]
Hello! 

Which language HabitRPG uses for you: German
Where on the site the message appears: When I click on an egg or potion on the Market page to sell it, the blue box below "Are you sure you want to sell a ____?" says "Error processing the string" etc instead of "Verkaufe ___ für _ Gold" The issue does not occur when I click on food items.
What you clicked on (if anything) that caused the message to appear: Any egg or potion.

**Comment by Alys** [comment]
@miche1 Thank you for telling us! @crookedneighbor has fixed that. The blue button currently shows English text but that will change when the text is translated. Please reload if you're still seeing the error.

**Comment by mchlltt** [comment]
@Alys Great, thanks! It now reads the correct text (in English), which is much better than the error message.

**Comment by montymero** [comment]
Hello everybody,
Which language HabitRPG uses for you: czech
Where on the site the message appears: Inventory > Equipment - royal attire (I don't know the exact name, since I have it in czech)
What you clicked on (if anything) that caused the message to appear: anytime I want to select this item or hover above

**Comment by giuz09** [comment]
Hi!!! really for the description bug??

**Which language HabitRPG uses for you.** Spanish
**Where on the site the message appears.** in the page of habitica tasks -> Rewards: Description of "Túnica de médico" (medical tunic)
**What you clicked on (if anything) that caused the message to appear**. I used the application for android to buy a reward chest but in the next rewards ("Túnica de médico", medical tunic)  when i move the pointer over the icon.

**Comment by ghost** [comment]
Fixed typos on Transifex 
Czech - armorArmoireRoyalRobesNotes
Spanish - armorHealer2Notes
 should be live with the next update
Mistake in Dutch reported by @thewillslyingcat seems also to have been fixed a while ago.
Thank you for reporting it @thewillslyingcat, @giu09 and @montymero! (sorry it took some time to find those strings =)

**Comment by GitHubSphinx** [comment]
For the sake of housekeeping, mistake in Dutch reported above has also been fixed.

**Comment by ghost** [comment]
@Alys do you still need this ticket open now as you have the bug reporting guild?

**Comment by Alys** [comment]
Ah no, thank you. If you're happy with the way that I copy reports of translation problems to your i18n guild, then this isn't needed.
