### ISSUE TITLE
"optional" or "weekly" Grey Dailies are too hard to see - need option for "always show in Due tab"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5466]
At the moment, in the Dailies column, we can see either all grey Dailies or none of them. This is assumes that grey Dailies never need to be actioned today.

However there's a couple of uses for grey Dailies where you would want to see **some** of them mixed in with the Dailies that are due. You can have optional Dailies - things that you'd like to do but don't want to be punished for if you don't have time for them. You can have a Daily due at the end of the week with a checklist that you tick off during the week (the completed checklist items are preserved while the Daily remains grey).

So I'd like to see an option in each Daily's edit screen for "always show in Due tab" (or similar words). It should be in the Advanced Options section. It should have on-hover text (like "Start Date" has) to explain that this option will NOT cause the Daily to be due, but just to appear in the Due column.

When that option is selected, the Daily appears when the "Due" tab is active, even though the Daily is not actually due. If the Daily is marked as completed, it should disappear from the "Due" tab.

This should be a fairly easy change so I'm advertising it in Aspiring Coders for a mid-level contributor. You can search through the code base for `startDate` to see how the recent Start Date option was set up - that will show you how to add a new option to the task model (ignore any code you find that's related to cron or related to how we work out whether a Daily is due or not). Also search for `remaining` to find the code that controls visibility for tasks (you'll also find some other things, but it should be obvious which code is related to tasks). Ask here if you have any questions!
##

**Comment by khipkin** [comment]
Is this ready to be worked on?  If so, I'm interested.

**Comment by crookedneighbor** [comment]
I don't think it's worth working on since the UI is going to change soon.

**Comment by librarianmage** [comment]
Now that the UI has been changed, should it be reopened?

**Comment by lemoness** [comment]
Actually, I'm not sure that this is something that we still want to do, as I worry it would lead to confusion.

**Comment by Alys** [comment]
We've spoken in the past about splitting `priority` (difficulty) into importance and difficulty (or "damage" and "reward"), with different settings being possible for each, so if we ever do that and we include an option for zero damage, that would cover most of this use case - take no damage from incomplete optional Dailies (although also no Perfect Day).
