### ISSUE TITLE
Paid subscription but not been on Habit for months 

### ISSUE THREAD

**Issue by lothlorienwoods** [HabitRPG/habitica#5469]
I have not logged into Habit for several moths but still paid the subscription cost. I was with out  pc until recently and I have limited internet on the my phone so I quit using the apo on my phone. I recently got a new laptop and started using Habit again. I love the program and don't mind paying the subscription. It is so worth supporting you guys, but can I please be able to buy the gems with gold for the months I did not log in but still paid, otherwise I just wasted a bunch of money. There is about 100 gems I need and I don't want to shell out over 20 bucks for that when I already paid for the ability to buy gems with gold for my subscription. There should be a rollover thing for the times people don't get a chance to  log in that month so they don't have their money wasted. The last time I used this was Jan  or Feb. I got June's gems. I want March April and May. If I have to end up paying for these gems I want may pull my subscription, because I despise having money wasted if I did not use the program. Is there a way to find out when I last logged on besides today? I don't want to get gems for a month  I used it and I can't remember if the last time I was on was Jan or Feb.If  there is not a possible way to add gems to buy with gold because I reached the cap for this month, can I just have my money back for those months I did not use it so I can use that to buy the gems I need? Thanks. Nice to see the program is growing nicely and getting some nice recognition. I have tried other type of programs, mainly fitness ones, and nothing comes even  close to the quality of Habit RPG, they all suck compared to you. I quit using them and just put my fitness stuff on here! Keep up the amazing work! 
Heather A

**Comment by deilann** [comment]
We can't help you unless you supply your User ID. You can find it at
Settings > API

Make sure not to paste your API Token. (that's like a password)

On Tue, Jun 23, 2015 at 12:30 PM, lothlorienwoods notifications@github.com
wrote:

> I have not logged into Habit for several moths but still paid the
> subscription cost. I was with out pc until recently and I have limited
> internet on the my phone so I quit using the apo on my phone. I recently
> got a new laptop and started using Habit again. I love the program and
> don't mind paying the subscription. It is so worth supporting you guys, but
> can I please be able to buy the gems with gold for the months I did not log
> in but still paid, otherwise I just wasted a bunch of money. There is about
> 100 gems I need and I don't want to shell out over 20 bucks for that when I
> already paid for the ability to buy gems with gold for my subscription.
> There should be a rollover thing for the times people don't get a chance to
> log in that month so they don't have their money wasted. The last time I
> used this was Jan or Feb. I got June's gems. I want March April and May. If
> I have to end up paying for these gems I want may pull my subscription,
> because I despise having money wasted if I did not use the program. Is
> there a way to find out when I last logged on besides today? I don't want
> to get gems for a month I used it and I can't remember if the last time I
> was on was Jan or Feb.If there is not a possible way to add gems to buy
> with gold because I reached the cap for this month, can I just have my
> money back for those months I did not use it so I can use that to buy the
> gems I need? Thanks. Nice to see the program is growing nicely and getting
> some nice recognition. I have tried other type of programs, mainly fitness
> ones, and nothing comes even close to the quality of Habit RPG, they all
> suck compared to you. I quit using them and just put my fitness stuff on
> here! Keep up the amazing work!
> Heather A
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5469.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by lothlorienwoods** [comment]
lol sorry about that. I thought you knew it from my email address.

e8195b11-320e-40fc-9431-085882ec5a1c

On Tue, Jun 23, 2015 at 2:32 PM, deilann notifications@github.com wrote:

> We can't help you unless you supply your User ID. You can find it at
> Settings > API
> 
> Make sure not to paste your API Token. (that's like a password)
> 
> On Tue, Jun 23, 2015 at 12:30 PM, lothlorienwoods <
> notifications@github.com>
> wrote:
> 
> > I have not logged into Habit for several moths but still paid the
> > subscription cost. I was with out pc until recently and I have limited
> > internet on the my phone so I quit using the apo on my phone. I recently
> > got a new laptop and started using Habit again. I love the program and
> > don't mind paying the subscription. It is so worth supporting you guys,
> > but
> > can I please be able to buy the gems with gold for the months I did not
> > log
> > in but still paid, otherwise I just wasted a bunch of money. There is
> > about
> > 100 gems I need and I don't want to shell out over 20 bucks for that
> > when I
> > already paid for the ability to buy gems with gold for my subscription.
> > There should be a rollover thing for the times people don't get a chance
> > to
> > log in that month so they don't have their money wasted. The last time I
> > used this was Jan or Feb. I got June's gems. I want March April and May.
> > If
> > I have to end up paying for these gems I want may pull my subscription,
> > because I despise having money wasted if I did not use the program. Is
> > there a way to find out when I last logged on besides today? I don't want
> > to get gems for a month I used it and I can't remember if the last time I
> > was on was Jan or Feb.If there is not a possible way to add gems to buy
> > with gold because I reached the cap for this month, can I just have my
> > money back for those months I did not use it so I can use that to buy the
> > gems I need? Thanks. Nice to see the program is growing nicely and
> > getting
> > some nice recognition. I have tried other type of programs, mainly
> > fitness
> > ones, and nothing comes even close to the quality of Habit RPG, they all
> > suck compared to you. I quit using them and just put my fitness stuff on
> > here! Keep up the amazing work!
> > Heather A
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/5469.
> 
> ## 
> 
> Currently Reading
> <
> https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
> 
> > [image: Book Cover]
> > <
> > https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5469#issuecomment-114617951.

## 

"I cant carry it for you but I can carry you"

**Comment by deilann** [comment]
You should be good now. :)

**Comment by lothlorienwoods** [comment]
how long does it take? It still shows I can't buy anymore gems with gold
because I bought the mont's max but that is just for this month. Will it
show that I can buy 120 gems with gold for the 3 months I was not on?  I
checked when  I last went on a quest and it said 4 months ago, so I was on
in Feb. I don't need Feb gems for gold. I just need Mar, April, and May

On Tue, Jun 23, 2015 at 2:39 PM, deilann notifications@github.com wrote:

> Closed #5469 https://github.com/HabitRPG/habitrpg/issues/5469.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5469#event-338201255.

## 

"I cant carry it for you but I can carry you"

**Comment by Alys** [comment]
@lothlorienwoods You have 141 gems currently. That seems like you've been given all the gems you've asked for. Can you please check again carefully?

**Comment by lothlorienwoods** [comment]
I was looking a the market. I did refresh and it showed 133 gems. I had 2
previous so it shows 135.

On Tue, Jun 23, 2015 at 3:53 PM, Alys notifications@github.com wrote:

> @lothlorienwoods https://github.com/lothlorienwoods You have 141 gems
> currently. That seems like you've been given all the gems you've asked for.
> Can you please check again carefully?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5469#issuecomment-114639120.

## 

"I cant carry it for you but I can carry you"

**Comment by Alys** [comment]
@lothlorienwoods Please be aware for the future that unused gems from the monthly subscription gem allotment are not intended to roll over into future months. I believe this is because the gems are considered as a motivational feature as well as as a subscriber benefit - you "need" to do sufficient tasks each month to earn the gold to buy the gems. Of course if you don't find this motivating or aren't using HabitRPG for tasks, then you can use [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to give yourself enough gold each month. The gem gift to you today was a once-off thing and not something that we do regularly. It's recommended that while you maintain a subscription, you log in once a month to buy your gems before they expire at the end of every month.
