### ISSUE TITLE
TODOs with a due date in the future shouldnt give you minus health today.. 

### ISSUE THREAD

**Issue by Daij-Djan** [HabitRPG/habitica#547]
I have 8 todos right now. 6 are due someday next week
2 are due now (have no specific date)

They all turned red at the same time (Today) and they all cost me health AFAICS

---

I dont think TODOs with a due date in the future shouldnt give you minus health.. else todos are kinda pointless IMO

**Comment by lefnire** [comment]
See https://trello.com/card/only-start-todo-devaluing-when-they-re-past-due/50e5d3684fe3a7266b0036d6/198. Turns out some disagree, vote on that card though to get it some priority.
