### ISSUE TITLE
Unsubscribing from all emails leaves individual boxes checked

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5471]
When you choose to unsubscribe from all emails under Settings > Notifications, the checkboxes for individual notification events become disabled, as you'd expect. However, if those boxes started off checked, they don't clear, making the final listing ambiguous:

![image](https://cloud.githubusercontent.com/assets/4501321/8316263/72b49ba4-19bb-11e5-953b-261dac0899fc.png)

If the individual checks cleared out when you hit "unsubscribe all", it'd be completely clear that you've removed all notifications.

**Comment by hairlessbear** [comment]
@Alys I advertised this in the Aspiring Coders guild, would you mind adding the Entry Level Coding label?

**Comment by crookedneighbor** [comment]
Done

**Comment by hairlessbear** [comment]
:+1: Much appreciated

**Comment by paglias** [comment]
Just one thing for future reference to anyone who is going to fix this. We only want checkboxes to show as unmarked (and disabled) when you unsubscribed from all the emails, not to modify any value in the database, those must not change.

**Comment by TheHollidayInn** [comment]
Eh, I did this yesterday before I saw the entry coding tag. I can just wait for someone to code it and show my fix if no one does. So, leaving this comment for sub reasons.

**Comment by Alys** [comment]
I think you should post your fix. If you've done the work, we should use it. Entry-level issues don't always get taken up quickly, and there'll always be more of them.
