### ISSUE TITLE
Can't access Challenges: Error Runner error

### ISSUE THREAD

**Issue by Tormen** [HabitRPG/habitica#5478]
Page displays error message, when accessing (all) Challenges:

Please reload, "Error Runner error: Overflow sort stage buffered data usage of 36132884 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

UserID: 48a749fd-f6a1-4dd2-9d0d-f7be9b0ebd1b
OS: Linux / OpenSUSE 12.3
Browser: Firefox 38.0.1

**Comment by hairlessbear** [comment]
Is this happening consistently (i.e., after you refresh, close the browser, reboot etc.)?

**Comment by Tormen** [comment]
For now it was only temporary (for maybe 15 min).

**Comment by hairlessbear** [comment]
There have been multiple server issues recently, so this was probably a result of that. But I could be wrong; one of the admins will pop by eventually and clarify.

**Comment by crookedneighbor** [comment]
Usually we see this error when a user is a part of a lot of challenges, and it resolves itself after a refresh or two.

That said, we did do some work server side to combat the issues we've been having recently. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.

**Comment by tinytito** [comment]
I have started having this problem as well. The error persists after page refresh and closing/reopening browser. It seems only the "challenges" page is affected, the rest of the site is working fine for me.

**Comment by stuffity** [comment]
Same problem here. Not a member of any Challenges; in fact I was attempting to go to the Challenges page to join my first one. Refreshing browser did not help.

Exact same error message as in OP, except buffered data usage of 35455495 bytes exceeds internal limit.

Console says:

GET https://habitica.com/api/v2/challenges 500 (Internal Server Error)nrWrapper @ (index):1(anonymous function) @ app-7ceb9834.js:6s @ app-7ceb9834.js:6$get.f @ app-7ceb9834.js:6j @ app-7ceb9834.js:7(anonymous function) @ app-7ceb9834.js:7$get.j.$eval @ app-7ceb9834.js:7$get.j.$digest @ app-7ceb9834.js:7$get.j.$apply @ app-7ceb9834.js:7g @ app-7ceb9834.js:4i @ app-7ceb9834.js:5g @ app-7ceb9834.js:4xa @ app-7ceb9834.js:4wa @ app-7ceb9834.js:4(anonymous function) @ app-7ceb9834.js:9o.Callbacks.j @ app-7ceb9834.js:1o.Callbacks.k.fireWith @ app-7ceb9834.js:1o.extend.ready @ app-7ceb9834.js:1I @ app-7ceb9834.js:1nrWrapper @ (index):1
app-7ceb9834.js:36 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}responseError @ app-7ceb9834.js:36j @ app-7ceb9834.js:7(anonymous function) @ app-7ceb9834.js:7$get.j.$eval @ app-7ceb9834.js:7$get.j.$digest @ app-7ceb9834.js:7$get.j.$apply @ app-7ceb9834.js:7s @ app-7ceb9834.js:6w @ app-7ceb9834.js:6y @ app-7ceb9834.js:6nrWrapper @ (index):1
2sdk.js&version=v2.0:64 Received message of type object from https://platform.twitter.com, expected a string
ping?client_id=172525162793917&domain=habitica.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1 Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

UUID 3f2b9e91-0cdc-44c5-8c72-0d6bf44b7cbe

**Comment by tinytito** [comment]
It eventually disappeared and I was able to access challenges again. Not sure exactly how long it took but the next day for sure I was able to. I just checked and I am still able to open challenges. I have no idea why it happens, obviously, but give it time and it fixes itself - at least temporarily.

**Comment by ghost** [comment]
I also had the same problem a while ago. Although it only lasted for less than 30 minutes. I made a few screenshots. Thought they might help. I get a different number for buffered data usage every time I refresh the page. I also tried to close the browser and opened it.

![screenshot 1](https://cloud.githubusercontent.com/assets/13826710/9297985/0e92b2b0-44da-11e5-81b6-32919eeb8083.png)

![screenshot 3](https://cloud.githubusercontent.com/assets/13826710/9298000/49035c42-44da-11e5-9425-93725161c08e.png)

![screenshot 4](https://cloud.githubusercontent.com/assets/13826710/9298004/4cad87be-44da-11e5-9725-ce59ba0879dc.png)

![screenshot 5](https://cloud.githubusercontent.com/assets/13826710/9298005/4ff8ffca-44da-11e5-9ecc-cb1a6619dfc5.png)
