### ISSUE TITLE
Changed avartar name, not propagated

### ISSUE THREAD

**Issue by Tormen** [HabitRPG/habitica#5479]
Hi,

To reproduce:
1.) Change avartar NAME under "user" -> "profile".
2.) Click on ". Go to Settings->Site and " link, there you'll see the old profile Name.

Tormen

**Comment by hairlessbear** [comment]
The display name (profile page) and your login name (settings page) are two different items. The display name is what displays when other users view your profile, and your login name is what you use to log in to HabitRPG. So if you change your display name, it shouldn't change your login name, and vice versa. Does that make sense?

**Comment by Tormen** [comment]
Ooops. I should have read the half sentence until the end...
...sorry.

**Comment by hairlessbear** [comment]
No need to apologize! Most websites don't have a feature like this, so it can be a bit confusing. Thanks for reporting it, even if it was just a misunderstanding. The developers rely on users reporting issues to keep HabitRPG running smoothly, and I hope you'll report other issues you find in the future :smiley:
