### ISSUE TITLE
Checked all dailies, yet I still died

### ISSUE THREAD

**Issue by Awesumounk** [HabitRPG/habitica#5481]
Although, I talked to Velinde, I still wanted to report this.  For the past two days now, even that I checked all my dailies, I still died.  My UUID is: e1536063-eb67-4efc-83b7-8eefb48654f0
Velinde said in the Tavern that it may be a server error, but I'm using all of my gold up by buying and re-buying my items.  (Nameless Helm, and Iciie Amour)  Velinde also said that quite a few people are having this problem!

**Comment by Alys** [comment]
I'm sorry that happened to you. You experienced either sync errors or this bug: https://github.com/HabitRPG/habitrpg/issues/4313. Please see the advice section near the top of that bug for information about how to recover from the unfair damage and the gold loss.
