### ISSUE TITLE
nodemon doesn't automatically restart the server when the code changes

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5484]
According to [our wiki](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Run_HabitRPG), `nodemon` is supposed to restart the server whenever it detects code changes. I've been developing locally for a few months, and this has never happened. Not sure why. Manually restarting using `rs` does work properly.

Possibly relevant: I'm developing with the Vagrant box.

**Comment by Alys** [comment]
When you edit the files, do you use an editor running within the VM or one on your host machine? Back in my early days of using the VM, I found that the latter did not always cause a restart to happen. I don't know about now; I'm in the habit of just always restarting manually, because I know I can rely on that.

**Comment by hairlessbear** [comment]
I edit the files on my host (I don't want to deal with subshells if I don't have to). I'll try to setup a local instance on my host box soon and see if `nodemon` automatically restarts then. If it doesn't, there's definitely a bug somewhere, but if it does, I'll just update the wiki with the relevant info and close the ticket.

Fake edit: I just found a possibly useful ticket on `nodemon`'s GitHub that I'm [linking here](https://github.com/remy/nodemon/issues/146) for when I mess around with this later :)

**Comment by crookedneighbor** [comment]
Nodemon restarts for me (not using Vagrant).

**Comment by hairlessbear** [comment]
The last comment of the `nodemon` ticket says that this is a [known issue with VirtualBox](https://www.virtualbox.org/ticket/10660) that's marked as WONTFIX. From the VirtualBox ticket:

> The reason is that the host and the guest might have different file systems and vboxsf would have to implement a generic protocol to forward that information from the host to the guest. And this would have to work between many different host/guest combinations. Therefore marking this ticket as "won't fix", sorry.

Oh well. As long as `rs` works, it's not a major issue.
