### ISSUE TITLE
Clicks register on site, don't appear on unoffical site

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#5489]
https://habitrpg.com/#/tasks shows various dailies accomplished. They don't show on https://oldgods.net/habitrpg/habitrpg_user_data_display.html. (I.e they do appear in the list of dailies not yet done.) That would be the usual SNAFU, except I've done a browser refresh of both pages. I even relogged into https://oldgods.net/habitrpg/habitrpg_user_data_display.html

Ubuntu 12.04
Firefox 37.0.2

IIRC, this has happened before, and cleared _eventually_, but that was before the latest update, the one that has https://habitrpg.com/#/tasks sometimes self updating. 

I am not using the "every X days" feature, or the "start date" feature, and won't until they work with https://oldgods.net/habitrpg/habitrpg_user_data_display.html I am using a custom day start, but this is happening outside of the special period, where my day isn't the same as the "real" day.

**Comment by Alys** [comment]
Whenever you see different information on habitrpg.com and the Data Display Tool (DDT), it means that your actions on habitrpg.com have not been synced with the server, and so are not fully saved and are likely to disappear. Sometimes more than one refresh of habitrpg.com is needed; try refreshing it again, then refetching data into the DDT, then reloading habitrpg.com and refetching in the DDT, etc, until they both show the same information. Reloading the DDT is not needed - just click the refetch button. Please also see the Advice section near the top of https://github.com/HabitRPG/habitrpg/issues/4313 - you've probably been affected by that bug.

I'm sorry this is happening to you! I know it's annoying. :(

**Comment by ArlieS** [comment]
_sigh_ Is there no way the client can indicate failure to sync?

**Comment by Alys** [comment]
Failure to sync can be indicated by the absence of the blue bar (see the Advice section near the top of #4313 for more details).
