### ISSUE TITLE
Different Exp and HP scales

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#549]
I have seen several posts now, which are complaining about the fact that hp and exp are rounded in the wrong way. A rather trivial way would be to multiply both the hp and the exp by 100. That would mean we have 5000 hp and we need somewhere between 2000 and.... exp. 

The pros: 
- The rounding bug is nearly fixed, it will be unlikely you get EXACTLY 2000 exp, but probably you will get 1999 or something, meaning it is clear why you don't level in almost all cases.
- You get for example 524 exp instead of 0.5 exp. This is, in my opinion, somewhat more motivational and more accurate.
  The cons:
- It might be a bit harsh to see that you need 20.000 exp, but the actual levelling speed would not change at all. 
- ???

This obviously has an extremely low priority, but I would like to know what people think about it.

**Comment by wildcate** [comment]
Hm... seeing that it takes 100 xp to go from level 5 to level 6, I'd imagine that numbers will seem astronomically high very soon. I don't mind the small numbers, and I also don't mind that the level-up occurs with one xp more than the number given beside the bar. Losing, say, 500 health for not taking the stairs also seems a little weird to me :)

**Comment by lefnire** [comment]
@MrConcept is just about done with some awesome algorithm adjustments

**Comment by Pandoro** [comment]
@wildcate true true, the positive effect you get from a multiplier on one side will also be a negative effect on the other side. I guess I like the bigger numbers better, as the games I played also moved in those directions. But in the end it doesn't make a big difference I guess.

Okay I am excited to see the adjustments :D

**Comment by Pandoro** [comment]
Closing this, as there are valid arguments against it and we should only discuss this again if necessary after the stuff @MrConcept did for us :D
