### ISSUE TITLE
Subscriber items not appearing

### ISSUE THREAD

**Issue by Yosituna** [HabitRPG/habitica#5491]
I just attempted to get the subscriber items for this month from the gift box, which listed 4 items as available; the first two were retreads of the Green Knight items from last month (which I already had, and didn't get another copy of), and the second two gave no response and no items, just ticked down the number of items in the box.

My user id is 14fa10ff-f73e-4ad4-adca-c13c67d4c20f, and I'm using Windows 7 and Google Chrome.
##

**Comment by hairlessbear** [comment]
Have you tried refreshing and clicking the box again?

**Comment by Alys** [comment]
The Green Knight set reappearing is a known, harmless bug and can be ignored.

@hairlessbear is right about trying a refresh. When we see reports of this problem, refreshing always fixes it, so I'm going to close this issue now. However if it happens to not work for you, comment here and we'll reopen.

A refresh is always worth trying whenever you see anything odd on the site, or when you don't see something you expect to see. It forces your browser to get the latest images and other data from our server. In this particular case, your browser did not yet have the mystery items images and data.
