### ISSUE TITLE
Bizarre custom day start behavior

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5496]
In my timezone, it is currently 00:28, and this happened just a few minutes ago (UID: 8ac7242d-8f18-4d6f-b4f4-8f6302f7fa0b). I usually have my CDS set for 1, but I just changed it to 2. After doing this, I checked off a task, and then cron ran. This means it ran before my original CDS _and_ my new CDS. Any ideas why that happened?

**Comment by Alys** [comment]
I don't suppose you know the time that your previous cron ran? Even an approximation might be helpful.

**Comment by Alys** [comment]
Ooo, if you were in a quest for the previous one, the quest message will give you the exact time. And your Dailies' history timestamps should too.

**Comment by hairlessbear** [comment]
I was on a quest! Time was `00:25:11`

**Comment by deilann** [comment]
Isn't this just the cron running as soon as CDS is changed bug?

On Thu, Jun 25, 2015 at 10:15 PM, hairlessbear notifications@github.com
wrote:

> I was on a quest! Time was 00:25:11
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5496#issuecomment-115517658.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by Alys** [comment]
00:25:11 - is that the one that JUST ran (this buggy one), or the previous one? If it's the previous one, it was early too.

**Comment by hairlessbear** [comment]
The buggy one.

**Comment by hairlessbear** [comment]
If it's useful, previous cron was `01:33:47`

**Comment by Alys** [comment]
Can you work out the time for the previous one? :)

**Comment by hairlessbear** [comment]
Heh, simultaneous comments. Previous cron was `01:33:47`

**Comment by Alys** [comment]
Ah, I see that you can. :)

I think this is expected behaviour, and correct as far as the server is concerned. Your cron ran at 1:30 on day 1. On day 2, it didn't run because 1am hadn't rolled around yet. But on day 2, you changed CDS to 2:00. The server then did its "is cron due" check, which it does with every event, and it realised that the previous cron was at 1:30 on day 1, whereas the CDS is 2:00, meaning that cron had not run after 2:00 on day 1, therefore cron was due. The cron you just received was actually a cron for day 1, not for day 2. 

Does that make sense? I can reword it.

**Comment by hairlessbear** [comment]
Took me a couple reads to understand, but  I got it now. That's really interesting; I didn't realize that's how cron worked.

I wonder if there's some way to modify the code to make the setting more intuitive. Your description makes sense, but from a usability standpoint, this is far from ideal. Hmm...I'll have to think about that when I'm more awake.

Regardless, since this isn't a bug, I'll go ahead and close this. Thanks for the explanation :)

**Comment by Alys** [comment]
This is the most promising suggestion I've seen: https://github.com/HabitRPG/habitrpg/issues/4488#issuecomment-103954722
