### ISSUE TITLE
Stuck with Justin head

### ISSUE THREAD

**Issue by wwqrd** [HabitRPG/habitica#5497]
The Justin head is stuck in my menu.

If I mouse over I see the "Continue Tour" caption, and if I click on him then I get a blue loading bar followed by... nothing happens.

Tried it on Chrome and Firefox. No console errors.

User ID: `6f6ae29c-bfcf-4342-8282-5fc56e116391`

I don't actually need to continue the tour so I don't personally consider this urgent.

**Comment by steeeve** [comment]
Fixed it by loading up the console and reseting my broken tour flags:

```
var $body = angular.element(document.body);
var $rootScope = $body.injector().get('$rootScope');
$rootScope.$apply(function () { $rootScope.User.set({'flags.tour.classes':-2}); });
$rootScope.$apply(function () { $rootScope.User.set({'flags.tour.intro':-2}); });
```

**Comment by SabreCat** [comment]
Noticed this today while making tutorial improvements. I think I know how this happens and will set something up to fix it.

**Comment by wwqrd** [comment]
Great! :-)
