### ISSUE TITLE
Problems with a unexpected death

### ISSUE THREAD

**Issue by Senshi-kun** [HabitRPG/habitica#5499]
I'm in a group and I changed the option of time that damages hits my character. Them, I thought it was going to hit just tomorrow, and Everybody received a large damage and lost a leve because of me. Is it possible to restore their characters and mine for how it was before the death? I mean combos, HP and everything else...

**Comment by Senshi-kun** [comment]
Our users ID:
817fbc11-4373-4cc5-9065-1beb3b5b5863
bc814ab5-93bb-494b-9c79-3f56d75e702d
02ef7f10-b551-44fd-aa54-ee76dfb39f4a
069a0cfe-d123-4ee4-a2a0-a4954ed6d0c2
6a9fbbd5-d6e3-4b18-b06e-a60afaa4109

The damage was at 10 o'clock is it possible to restore our accounts for what was before that? Thanks!

**Comment by hairlessbear** [comment]
Unfortunately, there isn't a way for the admins to restore your settings. That being said, you can each use [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to give yourselves back the gold/level/experience/health that you lost. In terms of the streaks, you'll have to restore those on each daily individually. I apologize for the inconvenience; I actually had a [similar issue](https://github.com/HabitRPG/habitrpg/issues/5496) yesterday, and I know how frustrating it can be. 

In the future, I'd recommend either checking off all of your dailies or resting in the Inn before changing your custom day start time. It can be a little inconvenient, but it does prevent issues like this.

**Comment by Alys** [comment]
@Senshi-kun We're considering methods to prevent cron running when you change Custom Day Start in https://github.com/HabitRPG/habitrpg/issues/4488 so I'm going to close your report now, but it is linked from that issue so that we can refer back to it.

In the meantime, as @hairlessbear says, it's best to follow the advice listed above the Custom Day Start form if you need to change the time again.

**Comment by Senshi-kun** [comment]
Thanks, everybody!
