### ISSUE TITLE
Viewable log of Habit +/- presses

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#55]
Occasionally I can't remember if I gave a "+" or "-" to a "Habit" already.  It would be nice to see a daily log with "Habit" name and the button "+" or "-" applied.  Personally I would prefer a single log for the day, but any verification of what I've pressed would help me greatly.  (P.S. Thanks for the awesome site.)

**Comment by lefnire** [comment]
Undo button and short term log planned. On phone now, can't find the ticket

**Comment by ghost** [comment]
I thought I had read all of the Issues, but #6 mentions the log.  Thanks!
