### ISSUE TITLE
guild / party with long name has the title running over the leave/join button

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5505]
If a guild or party has a long name, the name does not wrap neatly around the leave / join button:

![screen shot 2015-06-27 at 7 08 48 pm](https://cloud.githubusercontent.com/assets/1495809/8391264/06164572-1d00-11e5-99bf-127b3f89cb95.png)

I blame the pirates.
##

**Comment by habitrpguser** [comment]
Heh! I'm not the first though: I noticed this in other guilds before, but didn't think it grave enough to create a github issue.

**Comment by Alys** [comment]
It's watery grave now!

**Comment by kangabell** [comment]
![partyleader](https://cloud.githubusercontent.com/assets/5122304/11664705/448b43c0-9db1-11e5-85f8-29c5a0b0969b.png)
Note: if you're a party leader you have an additional button that exacerbates the issue.

**Comment by pleavin** [comment]
Is this still an issue? I'm looking for something to try to tackle and this seemed relatively entry-level from first glance.

**Comment by Alys** [comment]
@pleavin If you can find an easy, quick fix, then yes, please do. Feel free to start! 

If it turns out to be difficult for any reason, it would be best to not do it now because we're part way through a project to make many improvements to the website's code, which would fix this issue.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this issue might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This is no longer happening in the new site, so I am closing this issue!
