### ISSUE TITLE
if deleting challenge tasks fails, user is removed from challenge anyway

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5506]
When leaving a challenge and deleting challenge tasks, a rare bug can cause the challenge ID to become "lost" at the point where the tasks are deleted. This used to result in all non-challenge tasks being deleted (https://github.com/HabitRPG/habitrpg/issues/4466) but now it merely results in the tasks remaining while the user is removed from the challenge (https://github.com/HabitRPG/habitrpg/pull/5504). This means that the user has to delete the tasks manually.

It would be better if the user was not removed from the challenge if deleting the tasks fails. I.e., the code that removes the user should check for success/failure of deleting the tasks and not take other actions if the deletion is not successful.
##

**Comment by jeremyabbott** [comment]
I'd like to pick this up if that's okay.

**Comment by Alys** [comment]
That would be great, thank you @jeremyabbott! If you have any questions or run into problems, you can ask questions here in this issue. You're also welcome to submit an early pull request if you have partially completed code that you'd like us to look at.

**Comment by jeremyabbott** [comment]
@Alys here's a [link to the early PR for the issue](https://github.com/HabitRPG/habitrpg/pull/6034). I'd still like to write tests for the update. Please let me know if this is what you had in mind

**Comment by michaelabon** [comment]
Given that #6034 was merged in, should this Issue be closed as fixed?

**Comment by Alys** [comment]
@mkenyon Thank you for asking but no, the pull request was closed, not merged, which means it hasn't been accepted yet and the bug still exists. A merged PR has a purple marker at the top under the title, rather than red one.

I'm marking this issue as "wait" until the new API is released.

**Comment by paglias** [comment]
Should be fixed, reopen if it happens again
