### ISSUE TITLE
Guild bank goes beneath the guild description and moves leave/join buttons in slim view

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5507]
While experimenting with hiding the guild bank ( #5445 ) I've noticed that in slim/mobile view the guild bank goes beneath the guild description and moves join/leave button to the left, which looks very odd:
Screenshot (taken on ff 38.0.5):
![Screenshot](http://i.snag.gy/RswgC.jpg)

Making a connection to #5505
##

**Comment by Alys** [comment]
I'm closing this because we're most of the way through a project to change the website's front-end code and this is likely to no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.
