### ISSUE TITLE
Standard rewards not working

### ISSUE THREAD

**Issue by kwilson328** [HabitRPG/habitica#551]
Everything running smoothly today. All clicks working except for the standard armor and weapons rewards. I've got 45g and my eye on that chainmail, but when I click it nothing happens. Tried a refresh, no luck. Created a 1g custom reward and was able to purchase it successfully.

OS X 10.7.5
Chrome v25.0.1364.99

**Comment by lefnire** [comment]
any javascript errors thrown (chrome console, firebug, etc)?

**Comment by kwilson328** [comment]
Nope, just the usual 403.

**Comment by kwilson328** [comment]
Op, just tried it again, it froze for a second and then processed correctly. Must have been a local error or something. Happy chainmail to me!

**Comment by lefnire** [comment]
403! access denied?? hm, i'll investigate. we'll leave this open for now

**Comment by horusofoz** [comment]
@kwilson328 Is this still an issue?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
