### ISSUE TITLE
Fetch new messages button in Tavern is misplaced if Community Guidelines are not yet accepted

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5512]
[Fetch new messages] button is misplaced if Community Guidelines are not yet accepted:

![Screenshot](http://i.snag.gy/i0930.jpg)

Screenshot taken in ff 38.0.5 for win
##

**Comment by Alys** [comment]
I can't replicate this on Chrome on Mac OS, nor on Firefox 45.0.1 on Windows, so I think it's fixed, but tell me if I'm wrong and we'll reopen this and mark it for help welcome.
