### ISSUE TITLE
Addthis (i.e. "Share") button doesn't display on mouseover of avatar

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5514]
### EDIT:

It is highly unlikely that the following error message is related to this issue. See [this comment](https://github.com/HabitRPG/habitrpg/issues/5514#issuecomment-119373111) for an explanation.

---

Not sure when this started, but it's probably related to this console error:

> Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitrpg.com" from accessing a frame with origin "https://s7.addthis.com". Protocols, domains, and ports must match.

**Comment by lemoness** [comment]
Pinging @sabrecat

**Comment by SabreCat** [comment]
What browser and platform are you seeing this on? Do you have any additional security scripts installed? I can't currently reproduce this, so I'm wondering what other factors might be at work.

**Comment by hairlessbear** [comment]
Chrome 43.0.2357.130, Linux Mint 17.1. I have AdBlock Plus installed, but it's disabled for HabitRPG, and disabling it completely made no difference. Although I have no other security scripts installed, I went through my installed extensions, and disabled anything that seemed like it might cause this, but nothing made a difference.

**Comment by hairlessbear** [comment]
Wait, scratch that, something else just happened. Will update momentarily.

**Comment by hairlessbear** [comment]
I disabled StayFocusd, which caused the console error to disappear, but the AddThis button still didn't display. I tried a hard refresh, but that didn't make a difference. I then deleted all of HabitRPG's locally stored data and tried again, but it still didn't display.

Still not sure how to fix this, but at least we now know which extension was causing the issue. I'm not sure why StayFocusd is causing the error though; HabitRPG isn't in any of its lists, so it shouldn't be doing anything here.

**Comment by hairlessbear** [comment]
Just tried this in Firefox (which I never use and which doesn't have the StayFocusd extension), and there was no console error, but the button still didn't display.

**Comment by hairlessbear** [comment]
So this is interesting: on my local install, I get the same console error above, but the AddThis button _does_ show up! There are a couple messages that display on production but not my local install. I didn't think they were relevant before, but who knows? Here they are:

> Received message of type object from https://platform.twitter.com, expected a string

(^^That warning happens twice)

The message below isn't categorized in the console as a warning or an error.

> Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by hairlessbear** [comment]
To be clear, the above messages occur even if StayFocusd is disabled.

**Comment by hairlessbear** [comment]
@SabreCat Looks like this issue is either specific to Linux, or more likely, my machine. The Share button displays properly on Windows, even though all of the error messages above show up. Not sure what to do to try to solve this, but it's not a major problem.

**Comment by ghost** [comment]
I see no share button above avatar on mouseover. Should it be there?
My config: http://whatsmybrowser.org/b/S1FMNW6

**Comment by ghost** [comment]
Well, it's now fixed for me - I can see the share button

**EDIT**: and again no share button for me

**Comment by hairlessbear** [comment]
Button is appearing again. Not sure what the cause of this was, but it appears to have solved itself, so I'm  closing this.

**Comment by lemoness** [comment]
We'll have to keep an eye out for any similar reports, since we had issues
with this in the past that we thought were fixed! Let us know if it ever
disappears again.
