### ISSUE TITLE
Pirate Library (Library of Shared Lists) Challenge reorganisation - deletions, new owners, etc

### ISSUE THREAD

**Issue by jdrapic** [HabitRPG/habitica#5515]
Please delete the "Getting Things Done (GTD)" Pirate Library challenge with CID 2e06fe21-e5ed-4b02-93ee-c31abb023046 (created by @Cojo Warrior Princess, UID: 07376ffd-375d-4bd6-a34a-e8f16ac25a3e)!

It has 0 tasks/habits/dailies and the owner hasn't logged in since 1/1/15. The Pirate Library is trying to clear out and organize the challenges for the guild they've taken over, and I think this one's a candidate for deletion.

**Comment by Alys** [comment]
I've deleted the "Getting Things Done (GTD)" Pirate Library challenge with CID 2e06fe21-e5ed-4b02-93ee-c31abb023046

If you have other challenges to delete or that need to have new owners, add a comment here. I'm about to adjust the title of this issue to make it more generic for any challenge modifications, and I'll leave it open until the Pirate Library has finished rearranging its challenges, or until it has been burned and sunk to the bottom of the ocean. :)

**Comment by jdrapic** [comment]
Awesome possum. Thank you! 

—

**Comment by LordVladneutral** [comment]
I have recreated the "Pokemon Tasks" challenge (adcd6903-e3c6-4c27-a0e9-21f2e7515cd6 and no owner) in an other appropriated guild and told all the members where it will be gone. So I think you can delete it.

Thanks in advance.

**Comment by fabellalin** [comment]
I think the challenge "Everyday Things" (72dee980-021a-4a2a-83dd-2e03be74385f) should be deleted since it doesn't seem active and the owner last logged in on 17/01/2015

**Comment by LordVladneutral** [comment]
I think it shouldn't be deleted, but rather I'll take care of it and improve it. My user ID is ce36e72e-50fd-4e98-908b-34b3c06e9664 .

**Comment by habitrpguser** [comment]
As current Library guild leader, I'm happy with both suggestions regarding "Everyday Things" - if @LordVladneutral wants to take care of it and improve it, that's fine with me, please give @LordVladneutral ownership! If @LordVladneutral wouldn't, I'd be all for deletion, too. (I messaged the old owner, they're definitely inactive (last login January 2015) and, of course, didn't answer. I also checked the 3 participants, they're all inactive, too - two since 2014, one since only middle of June 2015 - but even so, if the challenges doesn't get reconstructed elsewhere, they don't need to be messaged, I think.)

I also agree about the "Pokemon Tasks", I think they can safely be deleted now.

**Comment by Alys** [comment]
@LordVladneutral You are now the owner of "Everyday Things" (72dee980-021a-4a2a-83dd-2e03be74385f).

The adcd6903-e3c6-4c27-a0e9-21f2e7515cd6 challenge doesn't exist. Is this the pokemon challenge that can be deleted now? https://habitrpg-staging.herokuapp.com/#/options/groups/challenges/2212ed56-c769-4b90-b0ca-33cfb21c6427

**Comment by LordVladneutral** [comment]
@Alys Yes it is, sorry for the wrong ID, I'm quite a beginner with the API, I must have gotten it wrong. and I didn't check.

**Comment by Alys** [comment]
@LordVladneutral No worries! No harm done. :) I've deleted that challenge.

**Comment by breadstrings** [comment]
@Alys - In follow up to my HabitRPG PM (I just discovered this github issue!), Mara has recommended that the "booty" challenges ownership be transferred to me so I can award them as per her request whilst she is away.

Challenge IDs:

```
587c82f6-c2da-4452-a57f-83ccd40e5f43

c53165fa-6811-43c4-a7b8-cea36e6fc38f
```

Thank you!

**Comment by Alys** [comment]
@breadstrings I've made you the leader of those two challenges.

**Comment by Alys** [comment]
I'm closing this since we've modified the challenges identified so far, but you are all welcome to post here again if you see more changes that are needed.
