### ISSUE TITLE
Constant "internal server error" and subsequent loss of data upon reload

### ISSUE THREAD

**Issue by GloomyMoonie** [HabitRPG/habitica#5516]
Upon every second chage to what ever task, to-do or habit, this thing pops up, and as described in the title, when I reload the page all the modifications are lost, including the completed tasks! What's most annoying though is that when the alert doesn't pop up, as in when the day resets and I reload the page to load the new dailies, only to get a massive reduction in exp, gold and mana, because all of the data from xx:xx time wasn't saved. Makes the experience almost intolerable.
Please fix!
![1](https://cloud.githubusercontent.com/assets/11799668/8398422/5bec0e72-1df6-11e5-9951-f340955ae239.PNG)

**Comment by Alys** [comment]
If you have a second browser installed, can you please try HabitRPG on that browser and tell us if the errors keep occurring? This is just a temporary workaround. If it fixes the problem, there are things that can be done to your preferred browser to try to make the error stop.

**Comment by Alys** [comment]
Closing from lack of response. @GloomyMoonie If it's still happening, please see my previous comment.
