### ISSUE TITLE
Party member doesn't show up in chat @ tagging

### ISSUE THREAD

**Issue by carolstone** [HabitRPG/habitica#5517]
We have a member in our party who left for a while and has now come back. He shows up in the list of members, and his avatar is there, but when you type @ for a name in the chat, he doesn't show up. I don't know if anything else isn't quite right, but his profile says he started in Feb. of 2013 and he has Veteran and Original User achievements, so I'm wondering if this might be a known issue for user IDs that have been around for a while. I'm hoping this is trivial to fix!

Naffster's ID is: 67fb91b5-de32-443c-b8a3-2d46c6fd6a58

Our Group ID is: 925571bc-e23a-4ead-8560-1c72b9962dd7

![naffster](https://cloud.githubusercontent.com/assets/9287541/8399789/bc8f6abc-1de2-11e5-9293-a9c4d99de793.PNG)

![dropdown](https://cloud.githubusercontent.com/assets/9287541/8399791/c0411e3a-1de2-11e5-908b-bf6189f26088.PNG)

**Comment by crookedneighbor** [comment]
The chat autocomplete is not populated by the members in the guild, but by the users that have posted recent chats. So if Naffster has not written chats recently, their name won't appear in the autocomplete list. 

Closing this now, but re-open if you think there's still something wrong.

**Comment by hairlessbear** [comment]
Has he actually typed anything in the chat? If I remember correctly, the only users that show up for @ tagging are those that have actually participated in the group's chat.

**Comment by hairlessbear** [comment]
Whoops, @crookedneighbor's response didn't load until I posted my own. My bad.

**Comment by crookedneighbor** [comment]
No worries.

**Comment by carolstone** [comment]
Complete misunderstanding of how it works on my part. Thank you. I don't remember if he said anything in chat last time he was in the party, but he certainly doesn't have anything recent in the chat. Someone else who left and who I know was a member and chatted and has since left (and not come back) also doesn't show up in chat, but I would think that would be a good thing. OTOH, that's how I came to mis-understand how chat works. Thank you for explaining it to me!
