### ISSUE TITLE
Notifications do not get cleared by clicking the clear button

### ISSUE THREAD

**Issue by mgpc3** [HabitRPG/habitica#5519]
When I click the little "x" next to the notification nothing happens. I tried refreshing and opening the website in a new tab and it still didn't work, however notifications still get cleared if I click the link to the page in question instead of the clear button.

![notification bug](https://cloud.githubusercontent.com/assets/5097204/8402046/137ef9e0-1e2f-11e5-87dc-82ab089038e1.png)

UUID: 8f21e403-8e3a-4d75-8824-74fe4712b2ce
I'm using Windows 8.1 
I'm experiencing this with both Google Chrome and Firefox.

**Comment by Alys** [comment]
Confirmed. Firefox and Chrome on Mac OS.

Thank you for telling us @ptdaisy! We'll get this fixed, although it might not be very soon because we're investigating a quest bug at the moment.

**Comment by crookedneighbor** [comment]
This is probably my fault. I was doing some refactoring of the chat code. Looking into it.

**Comment by hairlessbear** [comment]
@crookedneighbor Possibly relevant: there's a console error being thrown every time a guild page is loaded. It doesn't happen on the party or Tavern pages.

```
TypeError: Cannot read property 'chat' of undefined
    at Object.a.chatChanged [as fn] (app-95996026.js:30)
    at j.$get.j.$digest (app-95996026.js:7)
    at j.$get.j.$apply (app-95996026.js:7)
    at g (app-95996026.js:4)
    at Object.i [as invoke] (app-95996026.js:5)
    at g (app-95996026.js:4)
    at xa (app-95996026.js:4)
    at wa (app-95996026.js:4)
    at HTMLDocument.<anonymous> (app-95996026.js:9)
    at n.Callbacks.j (app-95996026.js:1)
```

**Comment by crookedneighbor** [comment]
Yeah, I just figured out why that's happening and have submitted a fix.

**Comment by hairlessbear** [comment]
@crookedneighbor: Ignore this if the fix just hasn't been deployed yet, but I'm still getting the console error above every time I load a guild page. That being said, it doesn't seem to affect my ability to interact with the guild in any way. I reloaded the page multiple times to ensure that I have the most up-to-date version of the code.
