### ISSUE TITLE
Todo History drops hugely because of bookkeeping (unconnected to actual task value)

### ISSUE THREAD

**Issue by jkshroads** [HabitRPG/habitica#5524]
I have two huge drops (from around +1500 to around -2000) in my Todo History graph now.

The first one was because I added a checklist item to a very red task. It was a long-term task and I realized I needed to subdivide it more, but adding a single item to it caused this huge negative drop, even though I did nothing "wrong" in real life. When I finally completed the task, some time later, my history graph shot back up again.

The second was just a few days ago. I gave up and cleared my completed Todos (even though keeping that history was the main reason I subscribed), so I could reorder them and not forget certain ones at the bottom of the list. That caused the graph to drop again, by a similar massive amount. I don't know if it's because I cleared the task that caused the first drop, or because I have another very red task right now.

I know it seems like a minor display bug, but I find it really demotivating because my Todo History is now so zoomed out that I can't see day-to-day fluctuations at all, and because every time I look at it, it looks like I massively messed up my life on those days, when it really had nothing to do with my actual, real-life progress on the tasks I need to do. It's made one of my favorite features almost useless.

My user ID is ae04b701-3f6f-4fb6-906d-630083213ec4 .

![screen shot 2015-06-29 at 3 01 18 pm](https://cloud.githubusercontent.com/assets/12630156/8415926/226a7cb8-1e70-11e5-9ce0-b2393e5f503a.png)
##

**Comment by Alys** [comment]
Task history/progress graphs have been removed and will be replaced by a better feature in future so I'm closing this.
