### ISSUE TITLE
[Monthly] Rollover is not occurring at midnight in the user timezone

### ISSUE THREAD

**Issue by qarylla** [HabitRPG/habitica#5532]
User ID: 810b6fce-697f-417e-afa1-1a632700cbff
Browser: Internet Explorer 11
OS: Sadly Windows 8.1

When logging into the system at 10:18 Eastern Time to purchase my remaining gems for the month, I went to the market to see that the monthly rollover is not necessarily timed to match the timing of the daily rollover. 

If the monthly rollover is not automatically timed to coincide with the daily rollover time, then it would be great to have that in the FAQ or other documentation.

**Comment by Alys** [comment]
Are you saying that your gem cap has not yet reset but it should have, or it has reset but it should not have yet?

What timezone are you in, in terms of UTC +/- a number? Timezone names tend to not be meaningful to people outside the local area (for example, there's at least two countries that have an eastern time).

What date is it where you are?

**Comment by qarylla** [comment]
The gem cap reset before it should have. I was checking on June 30. around 2200-2230 local time, which is UTC-5.

**Comment by Alys** [comment]
Can you tell me please how many gems had you bought from last month's supply, and how many did you buy after you saw that the rollover had happened?

I'm downloading backups to examine what happened.

**Comment by Alys** [comment]
@qarylla I'm closing this but I'm happy to reopen it if you can give me the gem purchase information from my previous comment.
