### ISSUE TITLE
Checklists added to TODO item on iOS are not saved

### ISSUE THREAD

**Issue by mariyadavydova** [HabitRPG/habitica#5534]
STR:
- Create a TODO item either in browser or in iOS app.
- Go to editing mode on iOS app and add some items in checklist.
- Save item.
  ER:
- Checklist is added an visible both in iOS app and in browser.
  AR: 
- Checklist seems to be added, but when opening browser version, the is no one. It also disappears from TODO item details in iOS app.

My User-ID is 4b95e7de-a0ef-4f2a-b42f-6fb393a570be

**Comment by Alys** [comment]
@mariyadavydova After you posted this, we released a new, native iOS app called Habitica. You can install it at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

I'm closing this issue but if you have any problems with the new app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com

**Comment by mariyadavydova** [comment]
@Alys Thank you very much for your reply and especially for the direct link. Unforturnately, the old app is still more useful for me as I use it via my iPad (not an iPhone), and Habitica looks ugly on an iPad right now. However I hope your team adds IPads support to Habitica soon.
