### ISSUE TITLE
Links in task notes popups can't be clicked

### ISSUE THREAD

**Issue by RossBrunton** [HabitRPG/habitica#5536]
Apologies if this has already been reported or in the pipeline.

If you add a URL in a task's "additional notes" section, when you roll over the task the URL appears as a link in the popup. Unfortunately, there is no way to click this link, as the popup goes away as soon as you move your mouse off the task.

_edit by admin:_

**Comment by hairlessbear** [comment]
That's not a bug; that's just how pop-ups work. They display when the mouse is hovering over the item the pop-up is attached to (in this case, a task), and stop displaying as soon as the mouse moves off of the item.

If you'd like to see this functionality added, I strongly encourage you to head over to the [feature request Trello board](https://trello.com/c/odmhIqyW/440-read-first-table-of-contents) and, if this request doesn't already exist, add it.

**Comment by crookedneighbor** [comment]
You can click on the notes icon on the task and that will make the popup persist.

**Comment by quenz** [comment]
I think this functionality is slightly confusing. The link shouldn't be formatted as clickable when hovering, or a little smaller note in italic or something should read "click note icon to freeze", or something like that..
