### ISSUE TITLE
Challenge page for a challenge that is not found may have a more noticeable message 

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5538]
Currently if you click a link to the challenge which no longer exists the page will show two buttons "Back to all challenges" and "Create challenge". [An example](https://habitrpg.com/#/options/groups/challenges/someid).

A standard notification on the right that the challenge is not found may be not quite enough, as it disappears and can be easily missed while the page is loading. And an empty page itself looks like something that shouldn't have happened.

So the page may need some kind of a blurb: `Unfortunately, the challenge you are looking for cannot be found.` If it's difficult to tell if there's no such challenge, I believe a phrase might be used like the one with the party: `Challenge #id not found or it takes time to load`
##

**Comment by corinnaj** [comment]
I'd like to take a look at this issue, if no one else is working on it.

**Comment by Alys** [comment]
@corinnaj That would be great, thank you!  Comment here if you have questions or find problems!
