### ISSUE TITLE
gulp test should report summaries even when suites fail

### ISSUE THREAD

**Issue by gisikw** [HabitRPG/habitica#5539]
Right now, if you run `gulp test` and any individual component fails, the remaining tasks (and the summary) will be terminated. This is not ideal since in the Vagrant environment, the e2e specs will fail by default.

The best approach here would be to modify `gulp.task('test'` to run "safe" versions of the suites (which do not pass any errors to their callbacks. i.e. `gulp.task('test', ['test:common:safe', 'test:api:safe', ...etc`

These new tasks should still push to `testResults`, but deliberately won't fail the task if one of the individual tests fails (this can be done by simply not passing the `err` object to the task's callback).

Then, the body of the overall `test` task should be updated to first report the suite summaries, and then throw an error at the very end if there were any failures in any of the suites (this is critical, since `gulp test` is what's used for CI).

/cc @alexbragdon, as he's looking to do some free labor! ;)

**Comment by gisikw** [comment]
It also occurs to me that once these `test:x:safe` tasks exist, the original `test:x` tasks don't need to push anything to `testResults` at all, since they'd only be run in isolation.

**Comment by alexbragdon** [comment]
I think I've addressed all your concerns in #5541. Let me know if that's what you had in mind.

**Comment by hairlessbear** [comment]
@gisikw Can this be closed?

**Comment by gisikw** [comment]
Whoops, sorry to have left this open :)
