### ISSUE TITLE
Feature suggestion : improved graphs

### ISSUE THREAD

**Issue by Laflamme** [HabitRPG/habitica#554]
I'd like to see on a graph how much xp and gold I earned and how many hp I lost for each day in a given year/month/week, so I can easily tell how I'm doing and correlate the data with events in my life (for example, did last week's cold really kill my productivity? by how much? on what day of the week am I the most productive? Comparing data from HabitRPG with data from SleepCycle, can I say my best days of work follow my best nights of sleep? Did I get more stuff done since I started using the pomodoro technique? Do I get more done if I run in the morning or at night? etc. )

**Comment by horusofoz** [comment]
Currently being considered under [Trello 98](https://trello.com/c/wYKm5cS5). Navigate to the link, vote and add your voice.
