### ISSUE TITLE
Reward changing name back to a previous version of it.

### ISSUE THREAD

**Issue by fgenu** [HabitRPG/habitica#5544]
So, last time I logged on habitRPG using Chrome, the first reward of my list reverted its name to a much older name. I know this seems unimportant, but I use this reward name to track my debt in coins and other stuff, so it can really mess up how I track it. Before logging in that time, I was using Firefox on the same computer (I use Chrome mostly for studying, and Firefox for leisure browsing). After logging back on firefox, the name had really changed to the older version, and I couldn't retrieve the newest one.

My ID: e327bb17-3ed0-4bcc-ada0-2b1c9da109ad

**Comment by Alys** [comment]
@wonderboy26 I'm sorry about this! It's probably an example of the bug described in https://github.com/HabitRPG/habitrpg/issues/4313. Chrome's local storage would have held on to an earlier version of the Reward and would have overridden the more recent version.

If it is important to you that you see the more recent version, we might be able to extract it from a database backup, but please note that this will be a multi-hour process so it can't be done immediately. Downloading a backup takes two to three hours, sometimes longer, and importing it into a local database server takes up to three hours, and then there's time required to search for the task and update your account with the backed-up version (usually just a few minutes but not always). If you would like us to try this, please tell us how many hours in the past you last saw the correct version of the reward.

**Comment by fgenu** [comment]
Thanks for the attention c: But I made an estimate of how I should change it back, and now I'll use Habit on Chrome only for the time being :P 

Btw, I skimmed the link you provided and I don't really think it's related to Cron, as the older version was a couple days old.

**Comment by Alys** [comment]
That issue that I linked to isn't actually directly related to Cron either, it's just that Cron makes the problem very obvious (but doesn't cause the problem). The issue is about a browser holding in to old data for an inappropriate amount of time, and then releasing it later, which I believe is what happened to your Reward.
