### ISSUE TITLE
Find the Cub Art Complete

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5545]
Eevachu has created art for the Find the Cub quest!
![findthecub2_300p_by_eevachu-d8xlouj](https://cloud.githubusercontent.com/assets/3494081/8466565/d7b64388-2008-11e5-8f09-cc26179c1181.png)

**Comment by hairlessbear** [comment]
@lemoness This helps with #4936, right?

**Comment by crookedneighbor** [comment]
Sure does.
