### ISSUE TITLE
Background changed overnight

### ISSUE THREAD

**Issue by madisonparklove** [HabitRPG/habitica#5547]
Yesterday, I purchased the Ruins of Dilatory background for 7 gems. Today, the background has mysteriously changed to the Sunken Ship background, and I am unable to change back to Ruins of Dilatory (it is locked).

User ID: 9d462b64-137a-4a91-800b-02e0bf1cd2ca
Mac OS X Yosemite

**Comment by Alys** [comment]
Sorry about that. There was a bug that caused this for a few users. I thought I'd captured all of them but I must have missed you. I've given you the Ruins background in addition to the ones you already owned.

**Comment by madisonparklove** [comment]
Thanks!

_Madison Parker_
_Author of YA LGBT Fiction_
Website http://madisonparklove.com/ | Subscribe to Newsletter
http://eepurl.com/AxSN1
=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:=:
Latest Release: Grand Adventures Anthology
http://www.dreamspinnerpress.com/store/product_info.php?products_id=4873
