### ISSUE TITLE
inability to log in with one particular account (not browser dependent)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5548]
The bug report below was sent to the admin@habitrpg.com email address. In brief, Mark is unable to log in to HabitRPG using his account (d10e2e95-3b4f-41be-8700-e893af0df33f). He's tried on multiple browsers on more than one machine. Extensions have been ruled out as the cause. He was able to create a new account and log in with that multiple times, on the same browser that failed for his real account. We could transfer data from his real account to the new, working one, but he has said that he would prefer the original account to be fixed and the underlying problem understood.

---

From: Mark Montague
To: admin@habitrpg.com 
Date: Jul 1 1:42 Am
Subject: Subscriber account/login problem - markmont

Hi,

I'm a new HabitRPG paid subscriber.  I've been unable to log in to my HabitRPG account since sometime Saturday or Sunday.  I go to https://habitrpg.com/ click the "Play HabitRPG" button and in the Login/Register sheet's login tab I enter my username (markmont) and password and then click the "Login" button.  If my password is correct, nothing appears to happen.  (If I deliberately enter the wrong password, I do get the "Uh-oh - your username or password is incorrect." error message, though).

I usually use Firefox 38.0.5 under MacOS X 10.10.3 on my laptop, but I have also tried Safari 8.0.6 and Google Chrome 43.0.2357.130 (64-bit) on the same machine.  Clearing all caches/history/private data and restarting the web browser does not help.  I have tried both from my home network and my work network.  I have also tried other computers, including a Red Hat Enterprise Linux 6 machine running Firefox 31, and a Microsoft Windows 7 machine running Internet Explorer 11, and the problem occurs on those machines, too.

Below is the HTTP request and reply headers that are captured using the Live HTTP Headers add-on for Firefox when I try to log in.  As you can see, the authentication request gets sent to /api/v2/user/auth/local in a 200 OK reply, but the next request to /api/v2/user/batch-update fails with a 500 Internal Server Error.

Can you fix this login problem for me?
## 

  Mark Montague

https://habitrpg.com/api/v2/user/auth/local

POST /api/v2/user/auth/local HTTP/1.1
Host: habitrpg.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: application/json, text/plain, _/_
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Content-Type: application/json;charset=utf-8
Referer: https://habitrpg.com/static/front
Content-Length: 64
Cookie: connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%7D%7D.CPXK0RnK2zumH54OudFNmEJIyz18ZXT2hkQjZWQCGhE; _ga=GA1.2.1355915207.1435678580; _gat=1; amplitude_idhabitrpg.com=eyJkZXZpY2VJZCI6IjczYmFiYWRjLThmODctNGI1Yi04NDNmLWFlNjAyNDkwYzRhMyIsInVzZXJJZCI6bnVsbCwib3B0T3V0IjpmYWxzZX0=
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
{"username":"markmont","password":"XXXXXXXXXXXX"}
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
X-Ratelimit-Limit: 80
X-Ratelimit-Remaining: 79
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key
Vary: X-HTTP-Method-Override, Accept-Encoding
Content-Type: application/json; charset=utf-8
Content-Length: 92
Date: Tue, 30 Jun 2015 15:36:40 GMT
## Via: 1.1 vegur

https://habitrpg.com/api/v2/user/batch-update?data=1435678601012&siteVersion=1

POST /api/v2/user/batch-update?data=1435678601012&siteVersion=1 HTTP/1.1
Host: habitrpg.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: application/json, text/plain, _/_
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
x-api-user: d10e2e95-3b4f-41be-8700-e893af0df33f
x-api-key: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Content-Type: application/json;charset=utf-8
Referer: https://habitrpg.com/static/front
Content-Length: 4
Cookie: connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%7D%7D.CPXK0RnK2zumH54OudFNmEJIyz18ZXT2hkQjZWQCGhE; _ga=GA1.2.1355915207.1435678580; _gat=1; amplitude_idhabitrpg.com=eyJkZXZpY2VJZCI6IjczYmFiYWRjLThmODctNGI1Yi04NDNmLWFlNjAyNDkwYzRhMyIsInVzZXJJZCI6bnVsbCwib3B0T3V0IjpmYWxzZX0=
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
[{}]
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
X-Ratelimit-Limit: 80
X-Ratelimit-Remaining: 79
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key
Vary: X-HTTP-Method-Override, Accept-Encoding
Content-Type: application/json; charset=utf-8
Content-Length: 28
Set-Cookie: connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%7D%2C%22userId%22%3A%22d10e2e95-3b4f-41be-8700-e893af0df33f%22%7D.e4GC3TK1w91ShEMh52xhx8%2F43DCladZmZ1AldnEm0gA; Path=/; Expires=Tue, 14 Jul 2015 15:36:40 GMT; HttpOnly
Date: Tue, 30 Jun 2015 15:36:41 GMT
## Via: 1.1 vegur

https://www.google-analytics.com/collect?v=1&_v=j37&a=1353989576&t=event&_s=3&dl=https%3A%2F%2Fhabitrpg.com%2Fstatic%2Ffront&ul=en-us&de=UTF-8&dt=HabitRPG%20%7C%20Your%20Life%20the%20Role%20Playing%20Game&sd=24-bit&sr=2560x1440&vp=1287x1168&je=1&fl=18.0%20r0&ec=behavior&ea=login&_u=SEAAAEABI~&jid=&cid=1355915207.1435678580&uid=&tid=UA-33510635-1&z=83950852

GET /collect?v=1&_v=j37&a=1353989576&t=event&_s=3&dl=https%3A%2F%2Fhabitrpg.com%2Fstatic%2Ffront&;ul=en-us&de=UTF-8&dt=HabitRPG%20%7C%20Your%20Life%20the%20Role%20Playing%20Game&sd=24-bit&sr=2560x1440&vp=1287x1168&je=1&fl=18.0%20r0&ec=behavior&ea=login&_u=SEAAAEABI~&jid=&cid=1355915207.1435678580&uid=&tid=UA-33510635-1&z=83950852 HTTP/1.1
Host: www.google-analytics.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: image/png,image/_;q=0.8,_/*;q=0.5
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: https://habitrpg.com/static/front
Connection: keep-alive

HTTP/2.0 200 OK
Access-Control-Allow-Origin: *
Age: 301554
Alternate-Protocol: 443:quic,p=1
Cache-Control: private, no-cache, no-cache=Set-Cookie, proxy-revalidate
Content-Length: 35
Content-Type: image/gif
Date: Sat, 27 Jun 2015 03:50:46 GMT
Expires: Mon, 07 Aug 1995 23:30:00 GMT
Last-Modified: Sun, 17 May 1998 03:00:00 GMT
Pragma: no-cache
Server: Golfe2
x-content-type-options: nosniff
## X-Firefox-Spdy: h2

https://api.amplitude.com/

POST / HTTP/1.1
Host: api.amplitude.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://habitrpg.com/static/front
Content-Length: 896
Origin: https://habitrpg.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
client=e8d4c24b3d6ef3ee73eeba715023dd43&e=%5B%7B%22device_id%22%3A%2273babadc-8f87-4b5b-843f-ae602490c4a3%22%2C%22user_id%22%3A%2273babadc-8f87-4b5b-843f-ae602490c4a3%22%2C%22timestamp%22%3A1435678601016%2C%22event_id%22%3A3%2C%22session_id%22%3A1435678580200%2C%22event_type%22%3A%22login%22%2C%22version_name%22%3Anull%2C%22platform%22%3A%22Web%22%2C%22os_name%22%3A%22Firefox%22%2C%22os_version%22%3A%2238%22%2C%22device_model%22%3A%22Mac%22%2C%22language%22%3A%22en-US%22%2C%22api_properties%22%3A%7B%7D%2C%22event_properties%22%3A%7B%22hitType%22%3A%22event%22%2C%22eventCategory%22%3A%22behavior%22%2C%22eventAction%22%3A%22login%22%7D%2C%22user_properties%22%3A%7B%7D%2C%22uuid%22%3A%2267d8593b-6090-40e9-947b-75a14aaf6d79%22%2C%22library%22%3A%7B%22name%22%3A%22amplitude-js%22%2C%22version%22%3A%222.2.0%22%7D%7D%5D&v=2&upload_time=1435678601016&checksum=4378926a8a7a4617d8c02456fc2d4ef8
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=UTF-8
Date: Tue, 30 Jun 2015 15:36:43 GMT
Server: TornadoServer/3.2.2
Content-Length: 7
## Connection: keep-alive

---

From: Mark Montague
To: admin@habitrpg.com 
Date: Jul 1 10:34 Pm
Subject: Re: Subscriber account/login problem - markmont

Thanks for your reply!  Sorry for this long message -- the short version is that I successfully created a new account and the new account details are at the end of this message, if you want to skip to that.

Here is the in-depth information on what I tried at your request:

I have several browser add-ons in Firefox on my Mac (such as Live HTTP Headers, Certificate Patrol, Privacy Badger, and several developer related extensions) but no extensions or plugins beyond the default ones that come with the browser (Adobe Flash, Oracle Java, Apple Quicktime).  I definitely do not have any ad-blocking extensions.  Firefox on my laptop is my main web browser.

However, I have NO additional add-ons, extensions, or plug-ins installed in Safari, Google Chrome, or Microsoft Internet Explorer.  And I've tested Firefox and Internet Explorer on separate machines from my Mac Laptop and I get the same result in all places and from three different networks (one of which was a wired network, no WiFi), so I'm sure the problem is not related to the operating system on my laptop or anything else on my laptop.  Note that when I tested Firefox on a separate machine, the other machine was Linux (RHEL6) running an older version of Firefox (version 31) in an absolutely default configuration with no add-ons, no additional extensions, and had never been used before (so no cache, history, or stored data).

But, per your request below, I cleared ALL private data, caches, and browsing history in Safari (from the beginning of time), disabled all extensions, disabled all plug-ins, and also turned off WebGL, and then restarted Safari.  As far as I can tell, EVERYTHING was turned off in Safari except for JavaScript, pop-ups, location services, and cookies from websites I visit.  The problem was still present -- I could not log in.  I then changed the cookie settings from "allow from websites I visit" to "always allow", turned off the "Do Not Track" HTTP request header, cleared the history and private data again, restarted Safari, and tried again -- this didn't help either; I still could not log in.

I'd be happy to provide a screencast of all of this, if it would help -- just let me know.

Also: I had installed the mobile client on my iPhone (iOS 8.3, HabitRPG mobile app v0.0.56).  I had been able to use the iPhone app just fine before the problem started.  Once the problem started, the iPhone app does not work any more either -- I was still logged in via the app, but when I enter the app, I get a yellow bar briefly appearing at the top of the screen saying "!Error contacting the server. Please try aga...".  After this, a spinner appears in the top bar, and the spinner never stops.  I can navigate to different screens, but the mobile app shows my old data (e.g., tasks) from last week, and not any of the changes I made over the weekend.  The problem with the mobile app occurs when using the mobile app on my work wireless network, my home wireless network, and with wireless turned off entirely so that the phone uses only my LTE cellular data plan.

I created a new account, as you requested.  I had no problems creating the new account and was able to log out and back in again several times, clearing all browser history and private data in between times.  So the problem does seem to be related to my specific original account in HabitRPG.  Here is my old and new account information:

New account Login Name: markmontague
New account email address: markmont@xxxxxxx
New account UUID: 02c43b57-226e-454a-a463-954f1bcf352e

Original account Login Name: markmont
Original account email address: mark@xxxxxxxx
Original account UUID: d10e2e95-3b4f-41be-8700-e893af0df33f

If you can move all my data (including my subscription status) from my original account to the new account, that would be terrific.

Is there any indication in the server logs why, after the authentication request succeeds on my original account, the request to /api/v2/user/batch-update fails with a 500 Internal Server Error?

---

From: Mark Montague
To: admin@habitrpg.com 
Date: Jul 2 10:17 Am
Subject: Re: Cami, Don’t Let Your Avatar (or Good Habits) Die!

Thanks!  I did receive a reply from Alys earlier today, and I have attached a copy of that correspondence.  The problem is not solved yet.  I'd prefer the original account to be fixed and the underlying problem understood, but will happily take transferring the data to a new account if that is the only way forward.

**Comment by markmont** [comment]
Thanks for creating this issue, Alys!   Let me know if I can provide any additional information or help out.

**Comment by crookedneighbor** [comment]
This is possibly a dumb question, but have we tried the reset password option?

**Comment by markmont** [comment]
No, but I tried logging in to my original account just now before resetting the password and found I was able to log in and everything looks good (someone even put me in the Inn!).  I'm wondering if the HabitRPG admins fixed something in the last 12 hours or so.  No changes on my end since the last unsuccessful attempt yesterday morning.

**Comment by crookedneighbor** [comment]
Very strange. Well, I'm going to close this. Comment back here if you have issues logging in again.

**Comment by Alys** [comment]
@markmont  I put you in the inn when I saw your first email about this.

None of us made any other changes to your account.

**Comment by markmont** [comment]
Thanks, Alys!  I agree with Blade that this is very strange, then.  I've tested on multiple browsers and the problem no longer exists on any of them.  In addition, the iOS mobile app has started working again for me, too.
