### ISSUE TITLE
Inconsistent damage from undone Dailies

### ISSUE THREAD

**Issue by spudderpillar** [HabitRPG/habitica#5549]
I'm signing in via Safari on iOS. For the last several days (week?), my undone dailies have not awarded damage during cron roll over. I'm still awarded xp, mana, and found items upon completing tasks. 

I came back from vacation and checked out of the inn about 1.5 weeks ago. It might be related to that but it says I'm no longer checked in and I'm pretty sure I received damage from some dailies the first few days I was back.

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

Note, some changes were just deployed that solved an issue with dailies not damaging even though they were left uncompleted. I'm guessing it's the same issue, so if your dailies have started to work normally starting now, let us know.

**Comment by spudderpillar** [comment]
My Use ID is 3b848c3a-bc43-473b-931e-39ffea0e60e3 .

My dailies didn't award damage this morning when I signed in. If my dailies work right tomorrow, I'll let you know. 

Thank you for helping!

-D

**Comment by crookedneighbor** [comment]
@spudderpillar Awesome, let us know tomorrow. If possible, please give specific information about the dailies that are not causing damage so we can inspect them.

**Comment by spudderpillar** [comment]
Good morning,

The glitch is still there. Yesterday, I had 7 Dailies incomplete (Apply face stuff, Foot meds morning, Foot meds night, Foot stretches morning, Foot stretches night, Wear hearing Aids, Feed/water cats). The streaks did not reset on them either. If you need any more info, let me know and I'll get it to you. 

-D

**Comment by crookedneighbor** [comment]
I did some spot checking and all but one of the dailies I looked at listed above did not have a startDate. The one that did was set to today (I assume was set today when poking through the advanced features of dailies or to check a streak).

Pinging @Alys. Not sure what's wrong, your change to the shouldDo script should have covered that.

**Comment by crookedneighbor** [comment]
Would it be worth running a migration to add startDates when they don't exist?

**Comment by spudderpillar** [comment]
The dailies I looked at had a start date of yesterday or today. I'm guessing you're right and it self-populated when looking at the advanced features. I'll let you know if that fixes it and it penalizes me tomorrow. 

You're above my head. I don't know how to do a migration. If you can walk me through it, I can try.

**Comment by Alys** [comment]
@spudderpillar Sorry that was confusing - the migration comment was directed at me. :)

@crookedneighbor In theory it shouldn't be necessary, but maybe. I'll keep it in mind after I've done some more investigation into this today and tomorrow.

**Comment by Alys** [comment]
@crookedneighbor Yes, darnit, any task that doesn't have a startDate is picking up the default of `moment().startOf('day').toDate()` from website/src/models/task.js, which I would have realised sooner if I'd finished the startDate test that I said I'd do. Sorry. :(  I'll write a migration script.

**Comment by Alys** [comment]
Migration script is running. It will take some time.

**Comment by Alys** [comment]
Migration finished.
754722 users examined
617180 users modified

**Comment by spudderpillar** [comment]
That worked: the missed dailies hurt this morning. Thank you both for fixing it!

**Comment by crookedneighbor** [comment]
Great job @alys
