### ISSUE TITLE
Suggestion: Quest Arcs

### ISSUE THREAD

**Issue by richard3030** [HabitRPG/habitica#555]
Related to the To Do list:
It'd be great to be able to combine to dos into quest arcs. For example, if I have several smaller tasks to do for an assignment, combining those tasks into a group (maybe with a plus to open and close the list) would be handy. Each task should still give gold and XP when completed, but completing all of the tasks in a group might trigger some extra reward.

All tasks in a quest arc might share the same due date, or tasks could be due sequentially.

**Comment by wc8** [comment]
See [Checklists](https://trello.com/c/PJ1iJ413)

**Comment by richard3030** [comment]
Ah, fantastic. Thank you @wc8. This is exactly what I meant. Glad to see it's already on the radar.
