### ISSUE TITLE
Wrong max level messages after rebirth

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5550]
I used the Orb of Rebirth after reaching level 104. All related messages and texts state that my max level was 100. I had my only other rebirth at 100.
##

**Comment by lemoness** [comment]
This is intentional, because the game is only optimized for levels 1-100. As a result, the max level displayed is 100. 

Maybe we should change the wording to "100 or more"?

**Comment by ghost** [comment]
If this is the intended behaviour (which is fine for me) then the last sentence of the message you get after using the orb is at least misleading if you use the orb at Level 100+.
"rebirthAchievement" in "rebirth.json" says:
"You've begun a new adventure! This is Rebirth <%= number %> for you, and the highest Level you've attained is <%= level %>. To stack this Achievement, begin your next new adventure when you've reached an even higher Level!"

**Comment by crookedneighbor** [comment]
The text definitely needs adjusting. I set my test character to level 150 and then used the orb of rebirth:

![screen shot 2015-07-03 at 7 17 23 pm](https://cloud.githubusercontent.com/assets/2916945/8505796/3b775c08-21b8-11e5-810f-9f2cd58ade1f.png)

![screen shot 2015-07-03 at 7 18 11 pm](https://cloud.githubusercontent.com/assets/2916945/8505800/45a703d6-21b8-11e5-8acb-9546bb51901b.png)

@lemoness Let me know what you'd like the text to be and I'll change it.

**Comment by SabreCat** [comment]
Aye, the text was written back when level 100 was a hard cap. Definitely needs tweakage!

**Comment by lemoness** [comment]
I think we can keep it quite simple:

"Reborn, max level 100+"

"The highest level you've attained is [n]/[100 or higher]!"

"...begin your next new Adventure when you are at least level [n+1]/[100]."

Do we need more clarification?

**Comment by ghost** [comment]
I think your suggestion is clear enough.

**Comment by Alys** [comment]
For anyone wanting to work on this, there are some useful comments about the code affected in this comment and possibly the one(s) after it: https://github.com/HabitRPG/habitrpg/pull/6020#issuecomment-146280632

Post here if you intend to work on it in case it's already being worked on. :)

**Comment by AminArria** [comment]
I will work on this.

Any other suggestions besides what is on #6020 ?
