### ISSUE TITLE
chat +1 button should have on-hover text to explain what it is

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5555]
When you hover over the +1 button in any chat area, there should be on-hover text, as there is for the other buttons, to explain what the +1 button is for. We get questions about it often enough for this to be worth adding.

@lemoness, would you like to choose the wording?

**Comment by lemoness** [comment]
I'd say "Click if you like this post!"

**Comment by Arbixal** [comment]
This looks easy enough. I'm happy to do this as my first fix.
