### ISSUE TITLE
Suggestion: Give users more information about their subscription

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5556]
I apologize for not using the Trello board for this, but it seemed more appropriate here. I'll move it if necessary.

This is the subscription information available to me:
![selection_018](https://cloud.githubusercontent.com/assets/7059890/8505999/1d254cf6-21cc-11e5-8196-13755be48f6f.jpg)

In my opinion, this display is lacking in several ways. Some additional information I think would be beneficial:
1. Start date of current OR consecutive subscription, favoring whichever date is older ("Subscribed since DATE")
   1. Example 1: I subscribe on January 5th for a month. Until the subscription runs out, it says "Subscribed since January 5th, 2015"
   2. Example 2: I subscribe on January 5th for a month. I buy another month long subscription on February 17th. Until the subscription runs out, it says "Subscribed since February 17th, 2015"
   3. Example 3: I subscribe on January 5th for a month, then buy to a 3 month subscription on January 29th, then buy a month on March 1st. Until the subscription runs out, it says "Subscribed since January 5th, 2015"
2. End date of current subscription ("Your subscription will end on DATE"). Or, if the subscription is recurring, "Your subscription will be renewed on DATE"
3. The next date you are able to receive an hourglass
   1. This would be shown even if the subscription ends before this date, in the hopes that it may encourage users to extend their subscription.
4. How many months that you have subscribed in _total_, even if not consecutive, or if user doesn't currently have a subscription (something like "You have supported HabitRPG for X months!" or "You have helped pay for X months of HabitRPG's server time!")

pinging @crookedneighbor @Alys @lemoness for input.
##

**Comment by lemoness** [comment]
I really like those suggestions, especially showing how long until they
earn another hourglass. Let's go for "You have supported HabitRPG for X
months" if we decide to do that latter.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer be needed afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Should this still be on hold? Also, the "End date" part of the Issue has already been added in the new redesign.

**Comment by Alys** [comment]
labels updated

I've marked this as suggestion-discussion rather than on-hold so that we can decide what we want displayed, although the staff might decide to close this if it's being discussed internally along with other payment issues.

**Comment by lemoness** [comment]
We've been discussing these internally, so I'll move these suggestions over and we can close this ticket!
