### ISSUE TITLE
challenge participants cannot be easily contacted - turn their name on progress screen into a link

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5558]
Challenge creators often have trouble getting in touch with winners or runners up, so we should enable profile links for all participants. 

Clicking on a person's name in the list of participants should keep working as it does now -- it shows you the screen that shows their progress. However their name in that screen should become a link to their profile so that the PM and gift buttons are easily accessible.

![screen shot 2015-07-01 at 6 22 55 pm](https://cloud.githubusercontent.com/assets/1495809/8506215/71e29c9a-224d-11e5-90c3-adf42f4f93a4.png)

**Comment by ghost** [comment]
Suggestion: Will it be much more difficult to add buttons to the footer of the modal?
![screenshot](http://snag.gy/3aMy7.jpg)
/ See profile - new icon needed? / Send PM icon / Send gift icon
No particular reasoning ATM, but I believe it may be more intuitive

**Comment by crookedneighbor** [comment]
Aren't you already viewing the profile in the member modal?

**Comment by ghost** [comment]
Oh, please excuse me for poor wording of my suggestion. What I meant by 'modal' is the screen of a user's progress created with name-buttons https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenges.jade#L54 (sorry, can't trace it further from phone)

It may be just other sort of a profile view, from a technical side, of course, but it doesn't provide a way to send a pm. So thinking about the task of this ticket, I had the following idea:

> Clicking on a person's name in the list of [challenge] participants [...] shows you [...] their progress

And having buttons in the footer of this user's progress modal may be more intuitive to use rather than a link in the header, if it's possible

I'm sorry if I misunderstand the ticket or your comment @crookedneighbor

**Comment by Alys** [comment]
@GitHubSphinx That's an interesting idea! I think I'd like both, if the buttons are easy to add there

I believe a link to the profile is still important to allow you to see if the player has logged in recently, what other challenges they've won (might be relevant), and other useful stuff.

**Comment by Alys** [comment]
Sorry, you had included an icon to link to the profile in the buttons. That's good. But I still like the idea of the name being a link (as well as the icon) because to me it seems natural to click on the name to see the profile (it's similar to what's done for challenge owners).

**Comment by ghost** [comment]
@Alys OK, thank you for considering my suggestion!

## Edit

for other contributors: I'm not working on this one (lack of skill*time-ATM :disappointed: ), feel free to take it!

**Comment by crookedneighbor** [comment]
@GitHubSphinx I misunderstood what you were asking. Since I could only see the bottom left corner of the modal in your screenshot, I thought it _was_ the member modal, and not the challenge progress modal.

**Comment by sgabler** [comment]
I'd like to try implementing it. But I have to agree that @GitHubSphinx's suggestion kind of makes sense. Maybe the name could be clickable, and there could be a button at the bottom. Best of both worlds.

The name would lead to the profile, whereas the button would only send a private message. What do you guys think?

**Comment by Alys** [comment]
@sgabler Sounds good. Let's see what it looks like! :)  Feel free to ask here if you run into trouble or want advice about anything.
