### ISSUE TITLE
tokens for holidays/birthdays?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#556]
I think it would be pretty cool if there was a present system using tokens for birthdays or holidays?  2 tokens maybe?  Because, otherwise you would have to purchase tokens...

**Comment by wc8** [comment]
Suggestions for a birthday field: opt-in, never required; allow entry of month, day without year; allow user's character's "join day" to stand in for birthday.

(The purchase of tokens is a way to contribute to HabitRPG development.)

Can you explain your birthday/holiday idea more? Is this for HabitRPG to give you tokens or for other users to give you tokens?

**Comment by ruddfawcett** [comment]
Oh of course I completely support the use of tokens to support HabitRPG.  However, I think it would be nice for a user to receive an automated token for his/her birthday? Just a suggestion...

**Comment by wildcate** [comment]
Handing out one or two free tokens on a birthday (special day, whatever) might actually get people eager to spend more - once one sees the possibility of spending stuff. This probably depends on how the initial token amount will be handled in the future, how much a token will cost when bought, and how high the token-purchaseable items are priced. I had some tokens in my virtual pocket when the pets were unlocked, which I thought extremely nice, and giving a token or two for the special day would be sort of similar to handing out a "birthday voucher". Which serves nicely to remind people of the possibility to spend tokens, and thus actual money, in a nice way that makes one feel appreciated at the same time. Best amount, in my opinion, would be a number of tokens that allows to buy a very small thing so it's not an almost useless gift (like the vouchers that promise you "5 money units off! If you spend at least 500 money units! But not if you spend it on variation x or y or brand z! Redeem it today!") but no large gift.

**Comment by Pandoro** [comment]
@wildcate, seeing this take on it, somehow really convinces me that it
sounds good to do it ^^  I really like the reminder function!

**Comment by wc8** [comment]
Hm... labelled Trello, but I don't see it there. Maybe this should just be brought to the attention of @lefnire directly?
(surprise some users the first time if implemented)

The only thing I would stress is making this opt-in and allowing a stand-in for any birthday based features such as join date. Personally, I dislike it when sites ask for that info, let alone require it. 

Thanks, @wildcate for chiming in.

**Comment by wc8** [comment]
[Added under Send Gifts](https://trello.com/c/BLIOj4Ty)
