### ISSUE TITLE
Cannot log in on iOS App

### ISSUE THREAD

**Issue by amyeds** [HabitRPG/habitica#5561]
I'm using the app on iPhone 6: I enter my username and password and it tells me that it's incorrect. I've tried resetting it. I've tried logging in with my username. I've tried logging in with my email. I've copy pasted the password from the password reset. I've uninstalled and re-installed the app. The only thread I found on this has been dead for months.

Anyone know how to fix this?

**Comment by Alys** [comment]
Your username is case-sensitive -- are you entering it **exactly** as it is shown in the password reset email? It's best to copy-and-paste it as well as the password.

Please go to the app store and see if there's an update for the app. If there is, let us know if that fixes the problem or not.

If it doesn't, please tell us the version of iOS your phone is using and the version of the HabitRPG app that's installed (from the About screen). Also tell us your user ID -- you can find instructions for finding that in step 6 at https://github.com/HabitRPG/habitrpg/issues/2760

**Comment by amyeds** [comment]
Oh, that was the problem! iPhones automatically capitalize the first word: I never considered that usernames might be case sensitive. Thanks!

**Comment by Alys** [comment]
Thanks for letting us know!
