### ISSUE TITLE
Pin specific versions of Bower and Node libraries

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5563]
In our `package.json` and `bower.json` files, we have a number of entries that look like the following:

> "Angular-At-Directive": "git://github.com/snicker/Angular-At-Directive#master",
> "js-emoji": "git://github.com/snicker/js-emoji#master", 

This means that when the corresponding Git repositories of those libraries update, they automatically update in our builds. While it might sound great to stay always up-to-date with our dependencies, this more often means that things break unexpectedly. A library might update in a way that obsoletes the way we currently use their functionality (we had this happen with `js-emoji`), or that causes builds to fail outright (this recently occurred with `css-social-buttons`). 

Better practice would be to pin specific known working commits or version tags, then update libraries consciously and as needed by committing changes to the package files. To fix this issue ticket, all existing library entries should resemble these, pinned to known working versions:

> "ngInfiniteScroll": "1.0.0",
> "jquery-colorbox": "~1.4.36",

**Comment by crookedneighbor** [comment]
Just an FYI that the version number syntax only works (I believe) if the package is registered (in the bower registry for bower.json or node registry for package.json).  if its not in the registry, you can still pin to a specific tag or commit on Github. Some quick googling will show you how to do that. 

Tags are preferable, but commits can be used if tagging is not utilized for the package.

**Comment by paglias** [comment]
I'd say that as a general rule we should pin git repositories to a specific tag or commit, not a branch, while for npm/bower packages it should be safe to use `~x.x.x` which will only upgrade patch versions that shouldn't break anything. 

If there are packages that are used to introduce breaking changes in patch version we can pin them to a specific version but I think they are very rare.
