### ISSUE TITLE
Button in invite-friends (to guild) modal is too long - adjust nowrap property or maybe universal solution?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5564]
The nowrap property of the button in [invite-friends modal](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/invite-friends.jade) may need adjustment as suggested by @crookedneighbor in https://github.com/HabitRPG/habitrpg/issues/5446#issuecomment-113912409 - not to be too long for the modal.

Screenshot: http://snag.gy/0vm3V.jpg

Or may there be a universal solution for all the buttons?

**Comment by ghost** [comment]
@crookedneighbor May I get some help with this one please? As far as google tells me, solution requires adding a css rule
`.btn {`
`white-space: normal;`
`}`

But I don't seem to be able to find the right place for it... At the same time I'm not sure if it won't affect other buttons in a way that is unwanted...

**Comment by crookedneighbor** [comment]
I'd create new class, maybe something like `.btn-wrap` with that property.

**Comment by ghost** [comment]
@crookedneighbor Thank you!
I'm afraid it may take me too much time to get an idea of how to do that =) So I'll be glad if someone else handles it - for I think it's generally an entrance level coding, isn't it?

**Comment by ghost** [comment]
Actually it turned out to be really easy. I have it working locally. What's left is to figure out what css file to use to be sure boostrap config is overridden...

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/5586
