### ISSUE TITLE
Community guidelines text may need update due to new moderator

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5566]
[Community guidelines](https://habitrpg.com/static/community-guidelines) text may need update due to new moderator
e.g. https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/community-guidelines.jade#L79

**Comment by crookedneighbor** [comment]
This should wait until the pixel art avatar is ready from @lemoness.

**Comment by Alys** [comment]
I'm going to close this because it might be some time until lemoness has done the artwork. Experience from past moderators tells that she'll log a new issue for the text change and artwork insertion when it's ready.

Thanks anyway @GitHubSphinx!  :) We will get this fixed in time.
