### ISSUE TITLE
Bug on frontpage: Dailies&mldr

### ISSUE THREAD

**Issue by ooker777** [HabitRPG/habitica#5571]
![capture](https://cloud.githubusercontent.com/assets/6695517/8541614/c052d656-24b9-11e5-97e8-f86861b6d07d.PNG)

**Comment by Alys** [comment]
@ooker777 Thank you for telling us about that!

**Comment by ghost** [comment]
Making connection to my previous report https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-110843828

Another occurrence of an html symbol code without ! in jade:
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L285
https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/front.json#L163

**Comment by ghost** [comment]
It may look different, but I'd suggest just changing json files to have text equivalents of the symbols:

![screenshot](http://i.snag.gy/ewCNU.jpg)

I know, it's not what's considered best practice, but I believe it's present in json files here and there

EDIT: of course there's another option to just add ! to jade and make strings html-ready. Which is also quite simple. It just requires making strings html-ready whenever they are changed to include symbol codes

**Comment by lemoness** [comment]
Pinging @anitaycheng!
