### ISSUE TITLE
Expand then contract checklist removes daily text in new iPhone Habitica app

### ISSUE THREAD

**Issue by wysawyg** [HabitRPG/habitica#5572]
Steps to reproduce
1) Go to dailies screen and add/have a daily with a checklist
2) Expand checklist
3) Contract checklist
4) Daily no longer has its name attached.

Found with an iPhone 5S running iOS 8.3

**Comment by hairlessbear** [comment]
Thanks for reporting, but it won't be seen by the iOS devs here. Please close this issue and report the bug in the [habitrpg-ios](https://github.com/HabitRPG/habitrpg-ios/issues) repository.

**Comment by crookedneighbor** [comment]
I've copied your issue here: https://github.com/HabitRPG/habitrpg-ios/issues/86
