### ISSUE TITLE
(WEB) No progress bar in pet section

### ISSUE THREAD

**Issue by Rohlik** [HabitRPG/habitica#5576]
Hello,
I have some problem with my one pet as You can see below:

![habbatica](https://cloud.githubusercontent.com/assets/2051154/8570787/3195bf4e-2583-11e5-9007-23d57e397e89.PNG)

My user ID is abf7a2d4-caf0-4a98-b053-49313e8fc262

**Comment by crookedneighbor** [comment]
This is expected behavior.

You've already raised a red wolf to a mount and then re-hatched a new red wolf. Once that happens, the feed bar doesn't appear, because you are unable to raise a second red wolf into a mount.
