### ISSUE TITLE
Cron running when it shouldn't kills me off and pwns my party

### ISSUE THREAD

**Issue by Ealasaid** [HabitRPG/habitica#5577]
I tend to use HabitRPG on multiple devices (mostly my laptop and my phone, both using the web browser). Last night I checked off almost all my dailies, on my phone. This morning, I opened my laptop and clicked the tab with HabitRPG in it (my computer was closed but on overnight) and it apparently ran a new chron because I died and did 22 damage to my party! It looks like it reloaded the tab, refreshed my dailies, and then ran a chron on me with all my dailies unchecked. :( 

Here's what I saw when I went over to my party to see if they'd gotten hit too:
![7-8-2015 7-19-16 am](https://cloud.githubusercontent.com/assets/11813679/8572480/bb118e66-2541-11e5-8a5c-184f15e14b8b.png)

My user ID is: ac82c0a6-46d4-46fc-8948-acaf238016e6
My laptop is Windows 7 64bit, and I am using Chrome.
My phone is a Moto X running Android version 5.1. (it also says I'm running Build number LPA23.12-15 and system version 222.21.15.ghost_row.Retail.en.US if that's helpful) I'm using Chrome on there too.

Stuff similar to this has happened before, but I figured I had messed something up. This time I feel pretty sure I didn't, so I wanted to report it. In the meantime, I will be careful to close HabitRPG tabs when I stop using them. :)

**Comment by Alys** [comment]
I'm very sorry about this @Ealasaid! You've been hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313. Please see the Advice section near the top for how to recover from the unfair damage and for workarounds for preventing it. If you'd like to follow the progress of the bug fix, you can subscribe to notifications in that issue (there's a button in the right-hand column).

By the way, "cron" is spelt without the h. That's important if you're ever searching for information about it. :)

**Comment by Ealasaid** [comment]
Oh dang, I looked for but didn't see the pre-existing bug. My misspelling probably didn't help! Thanks on both counts.
