### ISSUE TITLE
Habitica App/Facebook login

### ISSUE THREAD

**Issue by dspshadow** [HabitRPG/habitica#5578]
Joined six months ago and used facebook login to create account. Have consistently used facebook login to access account. Just got Habitica app and there's no support for facebook login. Only supports standard login. Tried facebook email + facebook password and was rejected. Presuming that HabitRPG changes info slightly, but website does not display account information. Therefore, cannot log in to Habitica app. Please add facebook login support?

**Comment by crookedneighbor** [comment]
Have no fear, it's being added to the next release.

**Comment by lemoness** [comment]
Good news! That will be a feature in the next update. In the meantime, the workaround is to add an email and password on the website as described here: http://habitrpg.wikia.com/wiki/Settings#Switch_from_Facebook_Authentication We're sorry for the inconvenience!

**Comment by lemoness** [comment]
I'm closing this now because we're already working on it, but feel free to post again if you have more questions!
