### ISSUE TITLE
"This request is too large to handle" bug when updating my Guild

### ISSUE THREAD

**Issue by Awesumounk** [HabitRPG/habitica#5579]
Earlier today, I wanted to update my Guilds' message to have the links to the MOTB website, wishlist and wiki and I got an error message which read, " The request is too large to handle"  I didn't give up until 4 or 5 times of this same message.  I don't have a screenshot because by time my screen grasp program loaded the message was already gone.  Can someone look into this, before other people get the same message (if not, probably already), and also so I can update my guild.

**Comment by crookedneighbor** [comment]
@Awesumounk Usually this kind of bug is temporary. Can you try refreshing your browser and updating it again? If you're still experiencing the error, post the guild id and what you'd like the description to say and I'll update it for you.

In the meantime, know that we are working on a refactoring the app to fix issues like this permanently, it's just not done yet.
