### ISSUE TITLE
Dying with almost full HP

### ISSUE THREAD

**Issue by dfjkla** [HabitRPG/habitica#558]
I died at midnight although I had almost full HP 24 hours ago.

Two days ago I gained a level before midnight, and my low HP was replenished. Now, after midnight, I died. It is impossible to die in one day with my setup - I lose at most around 10 HP per day.

**Comment by dfjkla** [comment]
I restored my character. I'll see if I can reproduce the issue.

**Comment by Pandoro** [comment]
Are you by any chance using the chrome extension? Or are you maybe logged in on multiple computers?

This sounds like a serious bug, but similar behaviour has occurred in the past when people could answer one of the two with yes. This is of course no desired behaviour, but it will help during debugging!

**Comment by dfjkla** [comment]
Don't have Chrome, and I only use Habit on FF with one computer. I suspect it has something to do with the fact that two days ago I was close to dying, and would have died if I didn't level up before midnight. I did level up and survived, but I ended up dying 24 hours later anyway.

Tough to reproduce, though.

**Comment by rixx** [comment]
#777, I think.

**Comment by lefnire** [comment]
yes indeed, let's follow up there
