### ISSUE TITLE
Help Text for GroupID

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5583]
I see a lot of folks post their GroupID when trying to find members for parties. No one can join a party with the GroupID, so it might be useful to provide some help text.

Something like: "This is an ID to help the admins find your party if any troubleshooting is needed. There's no need to keep it secret; no one can join your party using it."
##

**Comment by lemoness** [comment]
We're working on revamping the Create Party page, and this should
definitely be part of it!

**Comment by deilann** [comment]
It won't be as helpful on the Create Party page, as much as on an actual
created party page. There's no GroupID for a party that hasn't been created.

On Thu, Jul 9, 2015 at 10:00 AM, lemoness notifications@github.com wrote:

> We're working on revamping the Create Party page, and this should
> definitely be part of it!
> 
> On Thursday, July 9, 2015, deilann notifications@github.com wrote:
> 
> > I see a lot of folks post their GroupID when trying to find members for
> > parties. No one can join a party with the GroupID, so it might be useful
> > to
> > provide some help text.
> > 
> > Something like: "This is an ID to help the admins find your party if any
> > troubleshooting is needed. There's no need to keep it secret; no one can
> > join your party using it."
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/5583.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5583#issuecomment-120070273.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by lemoness** [comment]
_facepalm_

That's what I get for responding to Github tickets first thing in the
morning.

When we add this message, is there a less prominent place where we can move
the Group ID? Right now it's near the top of the page, which makes it more
notable. Moving it to a less conspicuous place may also help.

**Comment by librarianmage** [comment]
I can work on this!

**Comment by Alys** [comment]
I'm actually wondering if there's any point ever showing the Group ID on the page. For parties, we can easily get it from the player's account, and that's a more reliable method than asking the player to give it to us (probably also faster, given the time taken to describe how to find it). For guilds, we can ask players to send us the URL - something they can find more easily than the ID on the page.

Any disagreements?

**Comment by librarianmage** [comment]
I don't know why one would need it, but I don't know.

**Comment by librarianmage** [comment]
Group IDs are no longer shown on Guild pages; should this be closed?

**Comment by Alys** [comment]
Indeed.

Anyone wanting the Group ID can get it from the URL. It's only ever needed to ask for help with some bugs.
