### ISSUE TITLE
All Habits, Dailies, To-Dos, Rewards and purchased equipment vanished

### ISSUE THREAD

**Issue by Yevaud13** [HabitRPG/habitica#5585]
I've been using HabitRPG very happily for a couple weeks, but, when I logged in this afternoon, **all of my tasks, task histories, rewards, purchased items (via gold and gems) were gone and my character stats were completely reset to level 1**.  Followed recommendations on issue #4957 (to retrieve tasks) but no luck. 

Can anyone here help retrieve the tasks/items? The most important thing to me is getting my tasks back, since I've come to rely on HabitRPG to remember things for me. :)  

**Other info: Updated to Habitica on my iPhone yesterday (7/8). Today (7/9), Habitica started automatically downloading to my iPad, but stalled out ("Waiting") for an hour or two, so I cancelled the download by deleting the app from the home screen (touch+hold, then select "x"). Bug observed after that.**

Any help would be appreciated! 

User ID: 1858ef8e-4b79-40a2-b544-01fde6161b21

**Comment by Alys** [comment]
It's possible that in the past, two accounts were created for you by accident and today have logged into the wrong one.

Can you tell me how you usually log in to the website? For example, is it with facebook authentication, or username and password, or email address and password? Did you use the exact same method today? Did you enter the username / email address in the EXACT case that you've always used it in (i.e., upper-case and lower-case letters the same)?

How many hours ago did you last see your account looking correct? We can use that information to download an appropriate backup if necessary.

**Comment by Yevaud13** [comment]
I don't think so. I've been logging in as Yevaud (exact case) since I started a couple weeks ago, mostly through the website but also on the HabitRPG app (previously) and now on Habitica. Haven't ever used the site through Facebook. The change happened without me having to log in again, so an account mix up seems unlikely. I did also notice just now that while I had 10 gems left on my account this afternoon, I have 8 now (haven't been online in between), so I'm starting to wonder about hacking, and I'll change my password when I get to my computer. 

Everything was definitely normal last night around midnight ET.

**Comment by Alys** [comment]
How many hours ago did you last see your account looking correct? The number of hours is better than the time because timezones make exact times difficult to work with. If you can tell me that, I can download a backup to restore your tasks (although it's a slow process; it might be a day or two before it's finished).

**Comment by crookedneighbor** [comment]
@Yevaud13 If you noticed the 8 gems on the Habitica app, that's a display error that will be resolved in the next app store update.

**Comment by Yevaud13** [comment]
@crookedneighbor That's exactly true. Still showing as 10 on the website. Thanks!

@Alys  Oh, I see. That would be approximately 22 hours ago. Thanks for looking into it!

**Comment by Alys** [comment]
@Yevaud13 I've updated your account by merging in tasks, stats, and equipment owned from a backup made on 2015-07-09 00:00 UTC. Please let me know if anything is wrong or if I've missed anything!

@vIiRuS FYI, please see the bolded items in the original post, in case Habitica stalling isn't a coincidence. In addition to what is written there, everything in `items.gear.owned` had been changed from true to false (I think those are the only purchased items that @Yevaud13 refers to; all other gem-purchasable items appeared to be unaffected). I have saved a copy of the account from the backup and from before I merged in the backed up data in case we need to refer to them. (@Yevaud13 we'll do everything we can to keep your tasks and other information private, including from ourselves as much as possible, if we do need to investigate this further.)

**Comment by phillipthelen** [comment]
The stalling is a coincidence. It happened during the installation process and at that point the app on the iPad didn't have any data (so also no information which account )

**Comment by Yevaud13** [comment]
@Alys Thank you SO much! Everything looks just right. :)  Completely understand about needing the backups for reference -- I hope they're helpful.
