### ISSUE TITLE
unable to open links in task notes

### ISSUE THREAD

**Issue by isaact-d** [HabitRPG/habitica#5589]
If there is are hyperlink in notes. you can't click it when you move cursor off the task into the bubble the note is hidden.

**Comment by Alys** [comment]
Click on the note icon to open the note and freeze it in place. You can then click on the links. Click on the icon again to close it.

We have an issue to make this more obvious, since it is quite obscure.

Comment here again if it doesn't work for you!

**Comment by isaact-d** [comment]
Okay that's cool. Would be more intuitive if it was hidden when you mouse off the note
