### ISSUE TITLE
Gifts [suggestion]

### ISSUE THREAD

**Issue by derekantrican** [HabitRPG/habitica#559]
I was surprised to not see this listed already! I think there should be a gift option for sending other users (maybe not even in one's own party, but through email, where one doesn't have to know another person's username or user ID) certain items such as Tokens, GP, or a certain amount of XP (as for the XP, the sender could either dock it from their own amount or pay for it in the equivalent amount of gold since...I believe... gp values = xp values). Maybe even a pet?

**Comment by wc8** [comment]
Vote: [Trello: Send Gifts](https://trello.com/c/BLIOj4Ty)

**Comment by derekantrican** [comment]
Thanks!

-Derek

deltamu.com

Philippians 1:18,20-21

**Comment by wc8** [comment]
I think GP and XP are separate. XP works towards leveling up, which restores health.

**Comment by derekantrican** [comment]
Yes, but what I mean by "gp values = xp values" is that xp (in a way) is essentially an "never-negative" gold. That is to say, a user earns the same amount of xp and gp for every task he/she completes. So the combination of all the xp a user has (current AND through levels), is essentially how much gold that user has earned in their "HabitRPG lifetime".

Of course, I could be ignorant of something. Feel free to correct me if I'm wrong.

**Comment by Pandoro** [comment]
I very much like the idea of gifts, although the balancing should be
discussed a little here. (As in what can who give to whom.)

Right now GP  might be something similar to EXP, but with the new system
that is coming soon, this will be very much different! Stay tuned :)

**Comment by wc8** [comment]
I added a checklist item for discussing who can give what to whom to the Trello card. I'm going to close this for now, we can reopen later if and when needed.
