### ISSUE TITLE
Update to Firefow browser on work network caused front page gibberish

### ISSUE THREAD

**Issue by aldo1001** [HabitRPG/habitica#5594]
Hi, I use HabitRPG as my work todo list on Mozilla Firefox. (I think it updated a day or two ago).  Yesterday, I asked my network admin (security team prevents me from doing my own installs) to update Java and Flash to the latest versions on my computer. 
Later that afternooon, HabitRPG looks like this. 

![habitrpg](https://cloud.githubusercontent.com/assets/13276696/8623817/80dfed2a-26e8-11e5-993a-a295571ea2c8.jpg)

I can use it just fine on Chrome, but for various reasons, Firefox is my preference. Any insights on what might be going on?  I have user clearance to change settings on Firefox, but I can't so much as install a font on my computer without the security team's permission, so that's my limits on troubleshooting.

**Comment by crookedneighbor** [comment]
I'm on the latest version of Firefox on my Mac, and I'm not seeing this. Can you refresh the page? If it still persists, can you open up your console and report any errors? Do you have any extensions that may be blocking HabitRPG code?

**Comment by aldo1001** [comment]
I'll have to come back to this issue-- I'm going to be away from my work computer for a while. Thanks for looking.

**Comment by crookedneighbor** [comment]
I'm going to close this now. I would try clearing your browser cache. Reopen this if that doesn't solve the issue.
