### ISSUE TITLE
Tasks do not sync from iOS to desktop

### ISSUE THREAD

**Issue by kamazon** [HabitRPG/habitica#5595]
Since I updated the app two nights ago, no To Dos I have added on my phone have appeared on the web version. Also, clicks I make on my Dailies in the iPhone app are not registering properly. Help?

**Comment by kamazon** [comment]
To follow up: tasks I mark as done in one place do not register in the other, in both directions. 

However, tasks I put into the web application _do_ appear on the iOS version.

**Comment by Alys** [comment]
Are you using the old HabitRPG iOS app (logo is a brown chest) or the new
Habitica app (logo is a purple and white creature)? If the former, please
try the new one (search the app store for "Habitica"). I know you said you
updated the app, but we need to be sure which app.

**Comment by kamazon** [comment]
Thank you! That worked. :)
