### ISSUE TITLE
Extra notes cannot be clicked

### ISSUE THREAD

**Issue by orschiro** [HabitRPG/habitica#5597]
Hi all,

I just noticed an annoying bug. When providing information in the extra notes field, on mouse hover the appearing bubble does not stay open long enough to being able to click on a provided link.

Example screencast: https://www.youtube.com/watch?v=7wwJ67J2-2U&feature=youtu.be

Warmly,

Robert

**Comment by Alys** [comment]
Hi Robert. You can click on the note icon to open the note and freeze it in place. You can then click on the links. Click on the icon again to close it. Let us know if it doesn't work for you!

ref: https://github.com/HabitRPG/habitrpg/issues/5536

**Comment by orschiro** [comment]
>  You can click on the note icon to open the note and freeze it in place

This worked perfectly. Thank you very much!
