### ISSUE TITLE
when a user joins a party with a quest in the invitation stage, they are not able to accept/reject

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5598]
It used to be that when a user joined a party, they would automatically receive an invitation to the party's quest if that quest was still in the invitation stage. This no longer happens.

Now, when a user joins a party that has a quest in the invitation stage, they are still added to the party's `quest.members` object with a `null` value (i.e., the quest will not start until they accept/reject or until the owner force-starts it). However in their own user document, they are not given a value for `party.quest.key` (the quest's key, e.g., atom1) or a true value for `party.quest.RSVPNeeded`. This means that they never see the accept/reject buttons.

We could fix this by adjusting the code that adds the user to the party. It should check to see if a quest is in the invitation stage, and if so, give the user appropriate values for `party.quest.key` and `party.quest.RSVPNeeded`.

**Comment by crookedneighbor** [comment]
Pinging @hairlessbear, is this something you want to work on?

**Comment by hairlessbear** [comment]
@crookedneighbor Sure, I'll take a shot at it; seems pretty simple.

[Link to relevant code](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/groups.js#L444) (so I don't have to look it up later :smile:)
