### ISSUE TITLE
different amount of gems on website and app

### ISSUE THREAD

**Issue by Paulnaveau** [HabitRPG/habitica#5599]
It's simple, on the website I have 19 gems,
on the new app on the iPad I only have 16

I'm: d58d0567-1154-45c7-be1a-46fcc1c99845
I'm using Chrome 43.0.2357.132 m  on Windows 8

**Comment by hairlessbear** [comment]
Do you know which amount is correct?

Also, have you tried refreshing both instances (i.e., refreshing the browser page, and closing + reopening the iPad app)?

**Comment by crookedneighbor** [comment]
The new Habitica app has an error for displaying the gems. It'll be fixed in the next update.

See https://github.com/HabitRPG/habitrpg-ios/issues/88
