### ISSUE TITLE
Ghost Quest

### ISSUE THREAD

**Issue by jea0009** [HabitRPG/habitica#5602]
Group ID: 8a88a106-843e-4e91-a9e9-a91a18f4eeac

Hey! So a member of my group started a quest, then accidently pressed begin quest before anyone else could join. He wouldn't respond or stop the quest, so the leader of the group kicked him out and then re-invited him. Unfortunately, now there is a quest in our groups page that no one is a member of. Is there any way you could delete the quest from our group so we can start a new one?

Thank you!

**Comment by Alys** [comment]
I've done that. Reload your party page to see the change.
