### ISSUE TITLE
Daily "Repeat Every" day buttons give insufficient feedback about due/not due

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5603]
For Dailies that use the "On Certain Days of the Week" repeat option, it's fairly common for players to not know whether a highlighted day button means the Daily is due or not due on that day. We should have some kind of brief documentation in the form.

For example, when you hover over the "Repeat Every" text, you could see a popup explaining that highlighted days are due, and when you hover over a day button, a small popup could say "due" or "not due" (if that can be done without the popup being annoying while you are changing the days). 

Other ideas welcome! I'll wait a few days for feedback then advertise this in the Aspiring Coders guild.

**Comment by crookedneighbor** [comment]
Sounds good to me.
