### ISSUE TITLE
Challenges can add habits without a term or option to delete, it's stupid

### ISSUE THREAD

**Issue by isaact-d** [HabitRPG/habitica#5604]
Challenges need an end 2 weeks, 50 days ect ect not forever after

**Comment by Alys** [comment]
Hi @isaact-d. There's actually a few good reasons to allow challenges to have no end dates. For example, some challenges aren't about doing the best you can over a limited time, but instead are for long-term or permanent behaviour change, and so the participants would want to keep the tasks forever. Some challenges are templates for sets of tasks for specific purposes that players can add to their own lists and then adjust as needed; they aren't intended to have any competitive aspect or end date. If we enforced end dates, these useful techniques would stop working. I understand that they might not be suitable for you, but they are suitable for other players, so we don't consider them to be stupid.

You are always able to delete challenge tasks if you no longer want them. To do that, you leave the challenge and choose the option to remove the tasks. You can learn more about how to do this on the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges) page. If you have any trouble deleting challenge tasks, or any questions about what you read there, I recommend going to the habitrpg.com website and using the Help -> Ask a Question menu option. There are many experienced players there who will answer your questions and give you any advice you need.

If you'd still like to suggest changes to how challenges work, please go to Help -> Request a Feature, and describe your ideas there. Please remember that different players have different ways of using HabitRPG, so you might find more support from other players if you express your ideas with respect for alternative viewpoints. I do encourage you to provide suggestions there if you still find that challenges aren't working well for you!

**Comment by isaact-d** [comment]
Yeah that was the problem my option to remove the habit was taken away
