### ISSUE TITLE
Not Receiving Hatching Potions (Related to Issue #2176)

### ISSUE THREAD

**Issue by Biondom** [HabitRPG/habitica#5606]
User ID: 8298f9b5-6852-4ef9-86be-bef92e18d0ed

Browser/OS: Google Chrome on Windows laptop.

Issue: I commented on Issue #2176 because it was related, but received no response. It's also a closed issue so I thought perhaps I should start a issue.

Basically, over the past few weeks, I have stopped earning hatching potions; instead I have been earning mostly eggs and a little food. This is irritating; I have 8 eggs and no way to hatch them.

In the grand scheme of things, it's not that big a deal, but I'd love to resolve it. 

Thanks.

**Comment by Alys** [comment]
For the record, as Biondom found, we had replied in the other thread.

@Biondom, we receive notifications for comments made on both closed and open issues, although GitHub seems to be having problems at the moment with sending notification emails. If you ever don't get a response, just reply to the same issue. 

Eight eggs and no hatching potions is not at all unusual. It's a very small run of bad luck.
