### ISSUE TITLE
Request feature: explaining/marking tiling backgrounds

### ISSUE THREAD

**Issue by TheChumBucket** [HabitRPG/habitica#5607]
When I found out backgrounds can tile, I was ecstatic! I was thinking how fun it would be if different backgrounds could tile together (either release them in the same month, or one-a-month for however many "matching" backgrounds there are). They could either tile interchangeably, or be in a specific order to create one large background. This would also require the party to be "sorted by background". Lastly, I thought it would be informative if the backgrounds page marked the backgrounds that can tile. It might be obvious to some or most, but it isn't to an art-challenged player like myself. Sorry if a "provide more information" issue has been created, but I couldn't find it on GitHub nor the main Trello card.

**Comment by crookedneighbor** [comment]
@TheChumBucket Feature requests are [done through Trello](https://trello.com/c/odmhIqyW/440-read-first-how-to-request-a-feature-table-of-contents). 

Going to close this now, but feel free to comment on Trello about this.

**Comment by Alys** [comment]
See also the Tiling section in [Backgrounds](http://habitrpg.wikia.com/wiki/Backgrounds) on the wiki.
