### ISSUE TITLE
Number of Seafoam not displayed (if over 100?)

### ISSUE THREAD

**Issue by LittleMupsMum** [HabitRPG/habitica#5609]
The number of Seafoam I have available stopped showing up, after I bought a large number.  Alys tells me I have 117. It was working when I had 80-ish.  I wonder if it's because the icon is slightly offset compared to the gold coin icon. Screenshot attached: 
![seafoam](https://cloud.githubusercontent.com/assets/13087501/8666473/1384dccc-2a35-11e5-8852-7c3bffba29c7.png)
I am having this same issue on my Nexus 9, Macbook and large flat-screen monitor so I'm pretty sure it's not display-dependent.

**Comment by Alys** [comment]
117 confirmed.

@LittleMupsMum Thanks very much for the screenshot and platform details! That will be helpful.

**Comment by LittleMupsMum** [comment]
Just noticed that the number does show up in the Inventory:Market page, so it's just the Tasks page where this bug is occuring.

**Comment by LittleMupsMum** [comment]
Now that the buff has worn off, I noticed that the number does actually appear - in the line below.  I am guessing it was covered up by the Sand before:
![seafoam unbuffed](https://cloud.githubusercontent.com/assets/13087501/8697788/5465c0d8-2b3b-11e5-8054-b6b6b3241df9.png)

**Comment by Alys** [comment]
Thank you again!

**Comment by crookedneighbor** [comment]
Sigh. This happens every time we introduce a new item like this. The dimensions are 32 x 32, not 40 x 40 :disappointed:
