### ISSUE TITLE
Are weapons giving more experience now?

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#561]
I have a question.  It's great how you separated the experience gains from the Gold gains (looks great!), and now I'm wondering if weapons are actually giving more experience.  I just got a big reward for 8.3 Gold and 8.3 XP, so if I have an axe (which gives a 6% bonus, I think), wouldn't that give me 8.8 XP instead of 8.3?  
Or is it giving me more XP and I don't realize it?  Is my math right?

**Comment by horusofoz** [comment]
User's should be receiving more XP than GP in such circumstances as separate GP booster items are planned.

**Comment by PhilipHow** [comment]
The changes haven't been made to the main site (hence the same values for Gold and XP). So the original task value was 8.3 / (1.06 + (0.02 \* level)).

**Comment by lefnire** [comment]
your level also adds strength and defense

edit; ah, mrconcept already mentioned

**Comment by cleave29** [comment]
Interesting.  
Um, why the division symbol?  If 1.06 (the modifier for the axe?) is in the denominator, wouldn't that mean weapons make you get less XP?  I'm confused.
Wait, you said "original task value" so it was 7.28, then you added a bonus for weapon and strength!   Got it!  :) 
That's pretty clever!
