### ISSUE TITLE
After install of Habitica taking damage twice a day

### ISSUE THREAD

**Issue by Thunderhawke** [HabitRPG/habitica#5611]
Hi,

Since I installed Habitica, I seem to be taking damage twice a day (for example I died today when I should have only taken 22 damage from dallies and 22 from quest (am questing alone). 

My user id is - 831a485c-170d-4f1a-bb76-7eeaadc37de0

I use Chrome, and Habitica. 

Thanks

AT

**Comment by Alys** [comment]
Did you take both sets of damage at the same time, or different times? Do you use the website as well as Habitica, or any other HabitRPG apps? For all the devices (PC, phone, tablet, etc) that you use HabitRPG/Habitica on, are the times and timezones EXACTLY the same?

**Comment by Thunderhawke** [comment]
Different times, the damage on Habitica sometimes comes when I am updating
dailies, I have installed but have stopped using HabitRPG app and most of
the time I use Chrome (windows and mac) to update but tend to use
Habititica at night. Timezones are all EST, and times are set by server.

Cheers

AT

---

Andrew Natenshon
Mobile: +1-617-335-6240
ATN123@GMAIL.COM

**Comment by Alys** [comment]
The most recent three messages about your quest progress show that cron has occurred about 24 hours apart for three days, so I don't think that the damage you are taking is from cron running more than once a day. 

When you've use HabitRPG on one device and then switch to a second one, the first time you take an action on the second device (e.g., ticking off a task), a sync to the server will be done, and your device will be updated with the latest changes from the previous device. This means that you often see notifications that you've seen before on the previous device. This doesn't mean that the damage, etc from the notifications has been applied twice, it just means that you've see two reports of it. Does this seem to explain what you have observed?

When you took two damages today/yesterday, were they both for the same amount?

**Comment by Thunderhawke** [comment]
Didn't seem to appear today, and I noticed what you stated but the problem
of the quest damage of 22 leading to a death makes me still think I got
double hit with damage at some point, it is hard to track down past damage
drivers though so I can't be sure.

---

Andrew Natenshon
Mobile: +1-617-335-6240
ATN123@GMAIL.COM

**Comment by mollmoll** [comment]
Hi Alys,

The past two crons, my damage to and from the boss (Octothulhu) have tallied twice (at the same time). This has affected both me and my quest-mate.

My User ID is 6d09777c-2f34-4797-b9e1-65f8eb2f6104

All my devices are in EST and all times are set by servers.

I use HabitRPG, Chrome, Android (full site, not app), Windows and occasionally Linux.

Please let me know what other information would be helpful to you. I'm quite non-techy ;-).

Thanks!

mollmoll

**Comment by Alys** [comment]
@mollmoll Your problem is an example of this bug: https://github.com/HabitRPG/habitrpg/issues/2805. You can subscribe to notifications from that issue if you wish, although we're not at all certain what causes this so there's unlikely to be a fix soon. I'm sorry I can't give you better news. :(

@Thunderhawke Are you still having that problem? If so, can you post a screenshot of the quest damage messages from the past few days?

**Comment by Thunderhawke** [comment]
I am doing ok on this issue now, doesn't seem to be an issue right now.

---

Andrew Natenshon
Mobile: +1-617-335-6240
ATN123@GMAIL.COM

**Comment by mollmoll** [comment]
Thanks, Alys! Mollmoll 

```
 On Wednesday, July 29, 2015 9:17 AM, Thunderhawke <notifications@github.com> wrote:
```

 I am doing ok on this issue now, doesn't seem to be an issue right now.

---

Andrew Natenshon
Mobile: +1-617-335-6240
ATN123@GMAIL.COM
