### ISSUE TITLE
No flying pig or tiger eggs 

### ISSUE THREAD

**Issue by VittorioAstone** [HabitRPG/habitica#5612]
User ID: 5c6ce2df-779b-4c25-96b4-0a4f03049c70

Browser/OS: Firefox on Windows 7

Issue: Simply put, I'm level 32 and I've never found any pig or tiger eggs, while the other pets seems to appear regularly. Could possibly be pigs and tigers are so rare? 

(I haven't found any related issue, sorry if there is one)

Thank you!

**Comment by SabreCat** [comment]
See the last few comments in the conversation on #2176.
