### ISSUE TITLE
Outbox or sent messages

### ISSUE THREAD

**Issue by isaact-d** [HabitRPG/habitica#5616]
I'll often put a lot of effort into a proposal challenge to send to my guild leader but they don't always implement they ideas so it'd be nice to be able to take that idea across to another guilt leader to see what they think.

**Comment by Alys** [comment]
Your sent messages can be seen in your inbox.

Also, many guilds allow you to create challenges yourself. You might find
that for the guilds you are interested in, you don't need to ask the leader
to create the challenges for you.

If these points don't cover what you are wanting, please use the "Request a
Feature" option in the Help menu.
