### ISSUE TITLE
Clicks not registering

### ISSUE THREAD

**Issue by Skater6780** [HabitRPG/habitica#562]
When I go to click on a Habit and click the + or - nothing happends, When I try to check a daily it checks, but I dont gain xp or gold, and if I refresh its gone, If i click my username the button pushes down, but once again nothing happends

**Comment by Pandoro** [comment]
Hmmm, this is an older bug, which I had hoped was fixed as it stopped happening for me.

Please be sure to let the page load completely (no more spinning icon in the tab header.) before you try to click stuff.

Regarding the username button, I think this is a button indeed, but it simply does nothing. You should however get the menu if you click on the arrow on the right next to your name.

**Comment by mkirmes** [comment]
I have the same problem.
All the stats are stuck on what they were two days ago, clicking anything (apart from the links at the bottom of the page) leads to nothing: menu doesn't open, edit or progress doesn't open, (+) and (-) don't do anything, dailies can't be changed (setting a checkmark doesn't register), can't switch to complete tab in todos...

I have tried this in both Chrome and Firefox (plus in private mode), on different computers, and even on my phone, same result everywhere.
I can, however, use habitrpg as usual when I"m not logged in (in the trial sandbox). So I assume that something within my individual user account broke. :-(

**Comment by Pandoro** [comment]
Okay, this is bumped up to critical, @lefnire , sorry for the spam, but I guess this deserves you looking at it. With two users having this problem, and especially as persistent as described, this seems bad. :(

**Comment by lefnire** [comment]
Not at all, very helpful for me! @mkirmes @Skater6780 can either of you check your console (Chrome Console in Chrome, Firebug for Firefox) for any javascript errors when you click the buttons?

**Comment by mkirmes** [comment]
Alright, FF/Firebug does not show any errors when I click on things, only the same error twice when I load the page:

TypeError: t[n] is null
...);return o&&(r=n,n=e,e=o[2],t=o[1]),"number"!=typeof n&&(r=n,n=1),this._sendToMi...
in line 3

Chrome is potentially more helpful. On loading the page, I get:
ET https://habitrpg.com/img/sprites/ 403 (Forbidden) habitrpg.com:7
Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:236
Uncaught TypeError: Cannot read property 'length' of null QS3GhcxEo8T9ffe1YyMgMA.js:3
Uncaught TypeError: Cannot read property 'length' of null QS3GhcxEo8T9ffe1YyMgMA.js:3

Clicking on things, I get the respective function errors:
Uncaught Error: Bound function not found: score QS3GhcxEo8T9ffe1YyMgMA.js:6
Uncaught Error: Bound function not found: buyItem QS3GhcxEo8T9ffe1YyMgMA.js:6
Uncaught Error: Bound function not found: toggleTaskEdit QS3GhcxEo8T9ffe1YyMgMA.js:6
Uncaught Error: Bound function not found: toggleChart QS3GhcxEo8T9ffe1YyMgMA.js:6
Uncaught TypeError: Object #<MouseEvent> has no method 'concat'

For the lines that pop up below each error, I'll attach a screenshot
![habitChrConsole](https://f.cloud.github.com/assets/3756758/214505/7a3c76b0-8428-11e2-89ac-4ac8c5d67d0f.jpg)
(buyItem, toogleTaskEdit and toogleChart have the same as score)

**Comment by lefnire** [comment]
There we go, that's the kinda stuff I like! Ok thanks, will keep this handy for when I dive in

**Comment by Skater6780** [comment]
It has been happening for the past 2 days for me aswell

**Comment by lefnire** [comment]
@Skater6780 and @mkirmes , could you [email me](mailto:tylerrenelle@gmail.com) your [uuids](https://github.com/lefnire/habitrpg/wiki/User-ID)? It looks like something might be breaking on cron (start-of-day reload), which causes the rest of the page to not load properly

`Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:236` is from a chrome extension. But you did say you've tried in Incognito (your chrome extensions disabled for incog?)

**Comment by oralion** [comment]
Hi,
I've the same problem, things are stuck from Saturday.
The daily that I completed on saturday are still ticked, and when I try to tick something else nothing happens. Same with the setting menu, it just does not open :(
However, I see the notifications on about the new features, but I can't close them.

Thank you for your great work :)

**Comment by lefnire** [comment]
shoot me your uuid (or email or username or something), I'll look at all 3 y'all tomorrow morning

**Comment by mkirmes** [comment]
Just sent you my uuid. :-)
And yes, if I do go in incognito mode in Chrome, with extensions disabled, that error message does not appear anymore, but the problem persists.
The new extension rollout did by the way not only create the notifications, but also successfully changed the level requirements, so the stats apparently aren't completely frozen.

**Comment by Skater6780** [comment]
I Cant send My UUID because when I try to get to click the down arrow next to my name nothing happends

**Comment by lefnire** [comment]
no worries, a few sent me theirs i'll have something to work with. if I need your usename or email, i'll come hit you up

**Comment by lefnire** [comment]
try that

**Comment by Skater6780** [comment]
How?

**Comment by lefnire** [comment]
aka, did the latest change I pushed to the server fix the issue for you?

**Comment by Skater6780** [comment]
I Just checked and it fixed for me, Thanks : P

**Comment by lefnire** [comment]
cool, I'll wait for @mkirmes and @oralion and then close this

**Comment by oralion** [comment]
Fixed :) Thanks :+1:
