### ISSUE TITLE
Tail rubi description error

### ISSUE THREAD

**Issue by bazani** [HabitRPG/habitica#5625]
Hi, the item "Cauda Rubi" (Tail rubi) isen't showing the item description.
![screen shot 2015-07-15 at 10 48 50](https://cloud.githubusercontent.com/assets/676162/8699909/2d4f6226-2adf-11e5-8860-852bb3cf2107.png)

**Comment by ghost** [comment]
Thanks for reporting it! 

The string is reviewed, but I'm contacting the reviewers of the Portuguese team. Should be easy to fix! 

String key: [armorSpecialSummer2015RogueNotes on Transifex](https://www.transifex.com/projects/p/habitrpg/translate/#pt/$/51023779?key=armorSpecialSummer2015Rogue)

**Comment by crookedneighbor** [comment]
I've corrected the error. It'll be updated on the site in a couple of days.
