### ISSUE TITLE
ShareIt: Triggers a click on avatar anyway

### ISSUE THREAD

**Issue by 71** [HabitRPG/habitica#5628]
**Browser:** IE11 on Windows 8.1 Pro.  
**UUID:** `59844e50-2963-424f-a092-60d0c1a171f6`.

When clicking on the _ShareIt_ button, the click toggles both the "_share menu_" and the click on the avatar (Tasks <=> User/Avatar). Tried to reproduce that on Chrome, but the ShareIt button doesn't even popup, according to #5514.

**PS:** I'm on it.

**Edit:** I have found a way to solve the problem, using `ng-mouseover` and `ng-mouseout`, here's a [Plunk](http://plnkr.co/edit/js6mbyl5lzwDtWoVXw1E?p=preview).
##

**Comment by hairlessbear** [comment]
For what it's worth, the browser doesn't make a difference. This same behavior occurs with Chrome and Firefox.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This is no longer applicable to the new site, so I am closing this issue.
