### ISSUE TITLE
Can't leave party

### ISSUE THREAD

**Issue by aaalyssa** [HabitRPG/habitica#5630]
I created a party and decided I would rather join one then have my own but I cannot leave now. When I try to leave it says: Error Runner error: Overflow sort stage buffered data usage of 33952769 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

**Comment by Alys** [comment]
We can delete the party for you but we'll need information from you to identify it. Please go to Help -> Report a Bug and see step 6 of the instructions for how to find your ID and your party's ID.

**Comment by Alys** [comment]
I'm closing this since we can't do anything currently, but if you post the IDs we'll remove you from the party.
