### ISSUE TITLE
Typos repository - errors in English text and suggested text improvements

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5631]
## edit by Alys, 22 May:  new strings start at this comment: https://github.com/HabitRPG/habitrpg/issues/5631#issuecomment-226582108

An attempt to start a repository for typos in English text
### Typos
- [ ] **_not considered yet**_:  There is a space missing in front.json - marketing4Lead1 `...eachother...` - as reported by bouncyballboy
- [x] Successully instead of SuccessFully in two lines (77-78) of [settings.json](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/settings.json#L77) - as reported ([detachedFacebook](https://www.transifex.com/projects/p/habitrpg/translate/#nl/$/40458061?issue=yes) and [addedLocalAuth](https://www.transifex.com/projects/p/habitrpg/translate/#es/$/40458062?issue=yes)) on Transifex
### Style, commas, dashes, and other suggestions
- [ ] **_not considered yet**_: unwanted comma in npc.json - spellsText: `You can now unlock class-specific spells. You'll see your first at level 11. Your mana replenishes 10 points per day[,] plus 1 point per completed`
- [ ] **_not considered yet**_: unwanted comma in front.json - marketing3Lead2 `...you lose points when browsing unproductive websites[,] and gain points when on productive ones...`
- [ ] **_not considered yet**_: hyphen/em-dash issues in the Community guidelines: `elsewhere-we` (spaces missing), several occurrences of `--`
- [x] question seems broken in challenge.json - sureDelCha - `Delete challenge, are you sure?` https://github.com/HabitRPG/habitrpg/pull/5818
- [x] In the [challenges.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/challenge.json#L36) "Max = #gems you own (+ guild.gems, if you created this challenge's guild)." no period is needed between "guild" and "gems" and maybe the string needs to be rewritten to sound more natural - as [suggested](https://www.transifex.com/projects/p/habitrpg/translate/#ru/$/21450809?issue=yes) on Transifex.
- [x] In the [questsContent.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/questsContent.json#L117) "The Golden Knight shouts to the figure, "Father, no!" but knight shows no signs of stopping."  it should be "the knight" or "the Iron Knight" - as [suggested](https://www.transifex.com/projects/p/habitrpg/translate/#nl/$/37178587?issue=yes) on Transifex by [Shirviu](https://www.transifex.com/accounts/profile/Shirviu/)
- [x] In the [npc.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/npc.json#L34) there is an "a" missing; it should be: "Each time you level up, you get one point to allocate to a particular stat." as [suggested](https://www.transifex.com/projects/p/habitrpg/translate/#nl/$/21450415?issue=yes) on Transifex
- [x] In the [front.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/front.json#L112) "We all know how glued to phones and games students are these days, harness that power!" the comma before the word harness should be a semicolon - as reported on Transifex by [@bouncyballboy](https://www.transifex.com/accounts/profile/bouncyballboy/).
### Not a typo
- ~~With a final bellow~~ [questsContent.json#L195](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/questsContent.json#L195) (reported on Trello by [RealBG](https://trello.com/5d0a31b437be426fbe6ba709baadbda2), thanks to @Alys for clarification!) 
- ~~In the [questsContent.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/questsContent.json#L23) "But rumor has it, if you feed them milk after midnight, they grow quite irritable." there should be no second comma between "midnight" and "they" - as [suggested](https://www.transifex.com/projects/p/habitrpg/translate/#ru/$/22955925?issue=yes) on Transifex~~
- ~~In the [front.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/front.json#L105) "Bosses are "super accountability mode" - a day you miss the gym is a day the boss hurts" hyphen should be an emdash – as reported on Transifex by [@bouncyballboy](https://www.transifex.com/accounts/profile/bouncyballboy/) and [@luveluen](https://www.transifex.com/accounts/profile/luveluen/)~~ (we've decided not to change the dash)
- ~~In the [npc.json string](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/npc.json#L59) "They appear here - use them to hatch pets!" hyphen should be an emdash – as [reported](https://www.transifex.com/projects/p/habitrpg/translate/#nl/$/41995822?issue=yes) on Transifex~~ (we've decided not to change the dash)

**Comment by Alys** [comment]
I don't think "bellow" is wrong. The previous Stressbeast update spoke of the beast making a lot of noise, so going out with a final bellow makes sense. A bellow is a deep roar.

**Comment by ghost** [comment]
@Alys Thank you for clarification!

It seems I've added all the relevant comments marked as issues on Transifex. Could someone please review the items in the opening post and evaluate suggestions.

May I ask the moderators to feel free to edit the opening post if needed - as in a couple of days I'll be gone off-line for the next 2-3 weeks and won't be able to edit it.

**Comment by Alys** [comment]
"We all know how glued to phones and games students are these days, harness that power!"  I'd change the comma to a semi-colon rather than a period.

"But rumor has it, if you feed them milk after midnight, they grow quite irritable."
I think the second comma between "midnight" and "they" is correct. It's separating a conditional clause from a main clause. http://dictionary.cambridge.org/grammar/british-grammar/conditionals ("Order of clauses" section)

**Comment by crookedneighbor** [comment]
I agree on both counts.

**Comment by crookedneighbor** [comment]
I'm updating the description of the original issue.

**Comment by dschur13** [comment]
I'm a new developer and wanted to help contribute. Is this issue being worked on by someone else currently?

**Comment by crookedneighbor** [comment]
Yes it is.

**Comment by hairlessbear** [comment]
@dschur13 https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-110843828 has some similar work that you could do.

**Comment by lemoness** [comment]
Quick confirmation that bellow is indeed intentional.

**Comment by joedragons** [comment]
Maybe obvious but I think the first typo on your list has a typo.
"Successully instead of SuccessFully in two lines (77-78) of settings.json" I assume should be "Successfully instead..."?
Sorry if I'm confused.  Hope that helps otherwise!

**Comment by sgabler** [comment]
I think the uppercase F was just meant to emphasise the change @joedragons. It should be `Successfully`, like you said

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/5759

**Comment by ghost** [comment]
A minor note for the sake of possible future reference before closing an issue reported on Transifex by CaffeineVelocity:

> defaultTasks.json - defaultDaily3Text - 45m Reading
> This is by no means an urgent matter, but the abbreviation for minute is "min".

The string is currently inactive (commented in content.coffee) as other default dailies and the issue is not urgent to fix what's not used ATM. However it may need to be changed/referenced if other strings will use #m format for minutes.

**_UPDATE**_ Thank you, Alys, for addressing it!

**Comment by Alys** [comment]
No no, it's 45 metres of reading. Line those books up! :)

We should probably delete those unused default Dailies. We can always get them back if we want them from version history. Thank you for mentioning it!

**Comment by ghost** [comment]
There's a comment on Transifex about a supposedly unneeded comma I've missed out previously. I have a feeling it's been discussed already somewhere, but I can't find it now. So I'm reproducing it here for consideration:
`npc.json` - `spellsText`:
`You can now unlock class-specific spells. You'll see your first at level 11. Your mana replenishes 10 points per day, plus 1 point per completed`

As reported by bouncyballboy:

>  The comma before the word "plus" is incorrect because the separated portions of the sentence directly correlate. It should be written "Your mana replenishes 10 points per day plus 1 point per completed[ task]".

**Comment by ghost** [comment]
- challenge.json - sureDelCha - `Delete challenge, are you sure?`
  As reported by Evropi:
  
  > Would prefer something more like "Are you sure you want to delete this challenge?" I like the friendly tone of these strings, but broken English is unacceptable.
- front.json - marketing3Lead2 `...you lose points when browsing unproductive websites, and gain points when on productive ones...`
  As reported by bouncyballboy:
  
  > The comma in this part of a sentence should not have a comma

**Comment by ghost** [comment]
@Alys Hi! Posting here not having found the new right place for reports like the following one.
Reported by Jazzis18 on Transifex
questOctopusCompletion

> Completion: With a final blow, the creature slips away...

_Completion is not needed both in the original line and in translations as it comes from Trello where it's used to indicate the text concluding a quest_

**Comment by Alys** [comment]
Thanks @GitHubSphinx and Jazzis18. I've made that change in the repo. It will go live in a few days.

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
**_Fixed**_

> Reported on Transifex by @lyubomirv:
> 
> `shieldSpecialSpring2015RogueNotes` is supposed to be exactly the same as >`weaponSpecialSpring2015RogueNotes` however it has a typo:
> 
> Don't let the sound fool you - these explosives pack a punch. Increases Strength <%= str %>. Limited Edition 2015 Spring Gear.
> 
> "by" is missing in "Increases Strength <%= str %>."

**Comment by crookedneighbor** [comment]
Please submit a pr. I'll merge it right in.

**Comment by ghost** [comment]
Reported on Transifex by @lyubomirv:
`gemButton` says 

> You have <%= number %> Gem**s**

even if number is 1

introduced with https://github.com/HabitRPG/habitrpg/pull/4733

**Comment by ghost** [comment]
Using this old thread as an external memory:

the following system message doesn't look natural:

> Birds of Preycractination attack**_s**_ party for 0.0 damage

**Comment by ghost** [comment]
[Help wanted] Typos in new notifications/error messages reported to Transifex:
- [x] 'cardTypeNotAllowed' **_Unkown**_ _card type_
- [x] 'emailsMustBeAnArray' _Email invites must be_ **_a an**_ _Array._ - "a" is odd, why is Array capitalized, should anything be in quotation marks? 
- [x] 'uuidsMustBeAnArray' _UUIDs invites must be_ **_a an**_ _Array._ - same as above

**Comment by Alys** [comment]
@GitHubSphinx Thanks! We'll fix these ourselves since we know what they're supposed to say. Feel free to add more here.

FYI, in programming, there are "data types", like Integer, Number, Array, Object. They're always capitalised when used in that specific meaning, so it's easy for a programmer to forget to stop capitalising when they're writing English. :)

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg/commit/fa009a19f4dd733ca8069df8068cc2ae5a3909b1

**Comment by ghost** [comment]
- [x] typo in `noCompletedTodosChallenge` 'Completed' is misspelled:

> "includeComepletedTodos" is not supported when fetching challenge tasks.

Nice catch by @CAKS42 on Transifex

**Comment by ghost** [comment]
- [x] minor inconsistency in `tip7`:

> Some backgrounds tile, like the Mountain Lake, Pagoda, Rolling Hills, Winter Twinkly Lights and Harvest Festival.
> 
> **_Racobot**_ The string in the Backgrounds resource is called "Pagodas", while here it's called "Pagoda" (note the 'S')

**Comment by Alys** [comment]
@GitHubSphinx I'll fix Pagodas tonight while I'm making another tips change, and do includeComepletedTodos at the same time.

Thanks to you and Racobot and CAKS42!

EDIT (not worth more email spam): Ah, Pagodas was already fixed in a previous tips change to remove the confusing "tile" terminology.

https://github.com/HabitRPG/habitrpg/commit/337cb22a9deb36777ac955a37724fab3d31c6312
https://github.com/HabitRPG/habitrpg/commit/514962a9c7be61b2e46ad3a4499b97d4e1a29dfe

**Comment by ghost** [comment]
- [x] Minor inconsistency pointed out on Transifex by @lyubomirv: out of 28 *UnlockText strings, 10 strings have pet name beginning with the first capital letter while 18 others mention pet without capitalization, for comparison:

> Unlocks purchasable Cheetah eggs in the Market
> 
> Unlocks purchasable whale eggs in the Market

@Alys @Blade @lemoness would you consider this an issue?

**Comment by Alys** [comment]
I think it should be consistent and I think upper case is nicer. We'll wait a bit to see if there's any opinions for lower case.

**Comment by lemoness** [comment]
I also like upper case!

**Comment by ghost** [comment]
- [x] Another typo found by @lyubomirv in `questFrogCompletion`:

_"You can even see the tiny tadpoles and through the clear casing!"_ - aspiring quest writers have agreed that _"and"_ is odd here.
- [x] And another inconsistency with `questAtom1Drop` and `questAtom2Drop`mentioned in https://github.com/HabitRPG/habitrpg/issues/7629#issuecomment-225453537 (hasn't been addressed yet, as far as I understand)

> **_walderich**_ There seems to be another inconsistency regarding the quest scrolls. They are usually suffixed with "(Scroll)", but The SnackLess Monster and The Laundromancer use "(Quest Scroll)".

@Alys thank you so much for fixing the previous typos!
