### ISSUE TITLE
Says 1 Mount tamed when I didn't tame any.

### ISSUE THREAD

**Issue by fraukej** [HabitRPG/habitica#5634]
In the Stats & Achievements section, when scrolled down to pets and mounts, it says that I tamed 1 mount, when I didn't tame any yet. On the mount master quest progress it says "0/90" which is absolutely correct. This happened to some of my friends, too, they are all below lvl 10 and didn't tame a mount yet, some of them don't even have pets yet and still it says they have 1 mount tamed.

My User ID: e17b2483-bf26-4034-ac0b-b3ab45866b90
Browser: Google Chrome
Operating System: Windows 7
- no javascript errors.

A screenshot:
![bug](https://cloud.githubusercontent.com/assets/13371437/8734939/b4d6200c-2c0d-11e5-9e29-9e993192b54a.PNG)

**Comment by deilann** [comment]
You should have the Orca mount, which is 1 mount tamed! But it doesn't
count towards Mount Master, as you can see.

On Thu, Jul 16, 2015 at 1:55 PM, fraukej notifications@github.com wrote:

> In the Stats & Achievements section, when scrolled down to pets and
> mounts, it says that I tamed 1 mount, when I didn't tame any yet. On the
> mount master quest progress it says "0/90" which is absolutely correct.
> This happened to some of my friends, too, they are all below lvl 10 and
> didn't tame a mount yet, some of them don't even have pets yet and still it
> says they have 1 mount tamed.
> 
> My User ID: e17b2483-bf26-4034-ac0b-b3ab45866b90
> Browser: Google Chrome
> Operating System: Windows 7
> - no javascript errors.
> 
> A screenshot:
> [image: bug]
> https://cloud.githubusercontent.com/assets/13371437/8734939/b4d6200c-2c0d-11e5-9e29-9e993192b54a.PNG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5634.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by fraukej** [comment]
You're right - thank you for clearung this up :)

**Comment by deilann** [comment]
No problem!

On Thu, Jul 16, 2015 at 3:02 PM, fraukej notifications@github.com wrote:

> You're right - thank you for clearung this up :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5634#issuecomment-122116841.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature
