### ISSUE TITLE
Party page not displaying in Android app

### ISSUE THREAD

**Issue by RebeccaF** [HabitRPG/habitica#5636]
Since yesterday's update to version 0.0.56

The party page is empty for me and only displays the standard "to manage invitations..." text. The website shows my party. 

This is on Android 5.1.1

**Comment by illuscat** [comment]
This is happening for me as well.

**Comment by superbrewers** [comment]
This is happening for me, as well. Here is a screenshot from my phone.
![screenshot_2015-07-20-21-18-44](https://cloud.githubusercontent.com/assets/13484048/8874691/d1046cd6-31d8-11e5-8fc3-a06d81417fe9.png)

Here is what my party screen looks like when logged in to the web site, using Safari. 

![screen shot 2015-07-24 at 7 53 33 am](https://cloud.githubusercontent.com/assets/13484048/8874733/20d551d0-31d9-11e5-880d-291b07c0089c.png)

I am using Android version 4.4.2 and the HabitRPG app version 0.0.56

If there is any testing I can do, please let me know.

**Comment by Alys** [comment]
Please upgrade to version 0.0.58, as soon as the Play Store lets you do that (that version of the app is already there, but the Play Store might not have refreshed itself for your account yet).

This bug is fixed in that version. Sorry about the inconvenience over the past several days!

**Comment by superbrewers** [comment]
Thank you, Alys. I manually went into "My Apps" in the Play Store and see the update. Now I'm just waiting for it to install. 

Thanks for all your work on the app.
