### ISSUE TITLE
Had over 40 health, took 6.8 damage and died

### ISSUE THREAD

**Issue by Atramagus** [HabitRPG/habitica#5637]
My wife had over 40 health last night. This morning she took 6.8 damage and died, losing over 5.4k gold and she's unsure of any items that may have been lost. 

Anything that could have caused that?

**Comment by Alys** [comment]
Please ask her to read this message:

Please go to your party chat page and click on Fetch Recent Messages, then look for any messages about damage from a boss. If they don't explain what happened, then take a screenshot of the page and paste it into a comment here. Also add your user ID (to find out how to get it, can go to Help -> Report a Bug and see step 6 for instructions).

**Comment by Alys** [comment]
I'm closing this but we'll be happy to reopen it if she posts here to ask for further help.
