### ISSUE TITLE
Some users getting way too much GP / Exp with new algos

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#564]
Getting quite a few emails of people with billions of GP / Exp

quote from KS, we should look into:

> I just got 4482736 / 800 experience and about 379958 gold for filing my taxes XD

Screen from another:

![Screen Shot 2013-03-03 at 2 51 05 PM](https://f.cloud.github.com/assets/195202/214750/ebf35eec-8444-11e2-9519-9a4526a72022.png)

@MrConcept

**Comment by PhilipHow** [comment]
Are these both todos? They're potentially old todos that's value has changed..I'll look into it.

**Comment by horusofoz** [comment]
Similar issue. 

Just got unknown amount for what should have been a medium high reward resulting from a +/- Habit. 

Also note Habit went from my worse performing to Blue with a +.

See resulting XP status:
![Image 4](https://f.cloud.github.com/assets/3202339/215225/1adbfa96-8474-11e2-803f-4db5a8d1cac6.png)

**Comment by lefnire** [comment]
likely related to https://github.com/lefnire/habitrpg/pull/557/files , like an integer overflow problem. Though I don't know why any integers are that high / low

**Comment by horusofoz** [comment]
This appears to have normalised now however I've gained 6 levels and gold armour (couldn't resist XD ) from activity earlier in the day. 

Is there a way to revert this for all users to where they should be or alternatively perform a restore?

**Comment by junglist** [comment]
I have the same problem. It was an 'old' todo, but I created a new one and added it and it still gave weird results.

And I have the same guilty admission as the guy above, I couldn't resist adding lots of armour, but can I reset it?

**Comment by Pandoro** [comment]
Well if you want to manually reset it, you should be able to use the
restore function in the settings menu.

**Comment by horusofoz** [comment]
@Pandoro Can't believe I missed the Restore option. A quick Github search wasn't able to find it but saw it in your [Tumblr comment](http://habitrpg.tumblr.com/post/44468869138/custom-day-start-better-algorithms-auth-enhancements#comment-818293004).

For other's interested you can restore settings by:
1) Go to User Menu>Settings.
![Image 1](https://f.cloud.github.com/assets/3202339/216424/7b204c3e-84c1-11e2-8046-f0af8d311e74.png)
2) Scroll to bottom of page and select Restore.
![Image 2](https://f.cloud.github.com/assets/3202339/216425/7ed0acf2-84c1-11e2-8fb9-cf90b63431a0.png)
3) Modify your stats to previous level.
![Image 3](https://f.cloud.github.com/assets/3202339/216427/7f0326aa-84c1-11e2-80cb-d917f0a98792.png)

**Comment by junglist** [comment]
haha I missed this too, although my excuse is that OS X lion hides scroll bars so I didn't know you could scroll down on the settings page, I checked it 2 or 3 times too hehe

**Comment by PhilipHow** [comment]
@junglist what steps did you recreate to get the same results with a new todo?

**Comment by junglist** [comment]
Nothing special, I just added a new todo then checked the box. It gave me +10 and -600 XP (roughly). Although, I just tried it again now and it seems to be fixed.

Edit: I did also reset my account, maybe that has something to do with it.

**Comment by PhilipHow** [comment]
Ah the -600XP is from levelling up. The update was supposed to suppress it, I'll have another look.

**Comment by lefnire** [comment]
found it, we got a fix coming

**Comment by lefnire** [comment]
phew! thanks @MrConcept , saved the day: https://github.com/lefnire/habitrpg/pull/582
