### ISSUE TITLE
Orca mounts interacting weirdly with mermaid tails

### ISSUE THREAD

**Issue by katiegoodwin** [HabitRPG/habitica#5646]
![orca-mount-issue](https://cloud.githubusercontent.com/assets/1459849/8764594/961cac52-2db2-11e5-8ada-b3500434c1e3.gif)

When a user is wearing one of the seasonal mermaid tails (from either 2014 or 2015) and riding the Orca mount, a bright out-of-place pixel can be seen on the Orca's fin. A very trivial problem, but it's been bugging my party!
##

**Comment by crookedneighbor** [comment]
@lemoness I agree that the orca mounts could be adjusted a little. Thoughts?

**Comment by lemoness** [comment]
This is a pretty easy fix from an art perspective - just requires adding a
line of pixels. Not high on my priority list, but I will add it to my
To-Dos. If someone would prefer to adjust it with CSS before I get to it,
go ahead!

**Comment by beffymaroo** [comment]
The sprite for the front of this mount has been edited so that it does not interact weirdly with the mer-creature tails. :) File can be found at below link.

https://trello.com/c/0AJaHdE7/19-corrected-orca-mount-head-front-sprite

**Comment by librarianmage** [comment]
Should this be closed? If I understand this correctly, it has been fixed.
