### ISSUE TITLE
Cron partially ran - lost streaks but no daily damage, MP or quest reward

### ISSUE THREAD

**Issue by Pexpy** [HabitRPG/habitica#5650]
I had a few dailies unchecked last night; cron ran and didn't seem to work properly.

The streaks were still lost and task value dropped but none of the unchecked dailies dealt damage and I didn't regain any MP from cron. 

Also, I didn't seem to get any boss rewards. I dealt the killing blow that night due to another bug I found. I got the popup and the achievement but no gold or exp. My party members are also reporting they didn't receive anything either.

I've never stayed at the inn and since my streaks were reset and task value went down, I'm not sure that's the case anyway.

This said, I had a few issues during yesterday and I'm not sure if any of them were the cause:
- Errors after casting Pickpocket too fast. Loading anything that day (syncing, loading profiles) after that took 2-3 times longer even after refreshing the page.
- Checking and unchecking a large task several times and using Fix Character Values to repair my level, exp and gold from unwanted crits / difficulty setting. My attributes are still iffy but I've heard it fixes itself on level up.
- Excessive boss damage after the above; possible reward glitch from being overkilled?

My user ID: 4352e75b-0c23-4aa0-b64c-ea82543aa2a3
Group ID: 3918426d-5a0a-42bf-8247-737e890fe32d

(Side question: If I have to use Fix Character Values to give myself the gold/xp back from the boss, are stats taken into account or is it a flat reward? It was only the Basi-List so thankfully there's no eggs or scrolls that we're missing out on)
##

**Comment by Alys** [comment]
@Feragore The Dailies not resetting will be this bug: https://github.com/HabitRPG/habitrpg/issues/4313. There's an Advice section near the top that might help.

For the XP and GP that you should have received from the quest, you can get it by using Fix Character Values.

Boss damage is done when you tick off a task. It is not undone when you untick the task. That explains the excessive boss damage.

The rewards that you should gain from a quest are listed in the quest scroll, and are always exact. There's never any variation based on your stats.
