### ISSUE TITLE
Resting at the Inn quick check out

### ISSUE THREAD

**Issue by harrislapiroff** [HabitRPG/habitica#5651]
Currently when you're resting at the inn you see a warning on your tasks page like this:

![screenshot 2015-07-20 19 03 18](https://cloud.githubusercontent.com/assets/296631/8789606/2f32a9fe-2f12-11e5-90ac-f8457db4f7ca.png)

The functionality of resting at the inn is kind of tucked away and hard to find (under the Social dropdown on the Tavern view, with no menu item mentioning the Inn at all), which is maybe a separate issue. One change that could somewhat alleviate that, though, would be to add a button under the alert labelled "Check Out of Inn".
##

**Comment by Alys** [comment]
This is really more of a feature request than a bug report, so it should in theory go under Help -> Request a Feature, however I've thought exactly the same thing myself often lately and this should be an easy-ish fix.

@lemoness Is it okay if we do this? It should be suitable for a mid-level contributor so I can advertise it in the Aspiring Coders guild.

**Comment by harrislapiroff** [comment]
Apologies for misfiling. I'm still figuring my way around the wonderful world of contributing to HabitRPG. :) Thanks for looking at it anyway!

**Comment by lemoness** [comment]
I think this is a good idea!

**Comment by Alys** [comment]
@harrislapiroff You mentioned contributing... are you interested in getting into coding for Habitica? If so, do you want to work on this? We can help if you find you need advice or direction.

Otherwise we can advertise this in the Aspiring Coders guild, so don't feel you need to work on it! :)

**Comment by harrislapiroff** [comment]
I am interested in coding, but I'm not going to have much free time until mid August. I'd be happy to take this up then or seek out a different task when the time comes. Either way! :)

**Comment by Yvaine8** [comment]
I would love to work on this. It will be my first try, though, so it might take me a while, but since it's not urgent and doesn't seem too difficult, I think I can try (if @harrislapiroff doesn't mind)  :)

**Comment by gauthamchandra** [comment]
@Yvaine8 are you working on this? If not, I can tackle this.

**Comment by Yvaine8** [comment]
I'm on it. I know how to do it, just need to test and make sure I'm not breaking anything...

**Comment by crookedneighbor** [comment]
@Yvaine8 feel free to open a WIP pull request if you'd like some help with it.

**Comment by Yvaine8** [comment]
Sorry, I had to completely reinstall my computer, so it seems like I'm not going to be able to do this any time soon, so @gauthamchandra, this is all yours if you want it.

**Comment by gauthamchandra** [comment]
yea. I can tackle this. I will have a PR by the end of the weekend.
