### ISSUE TITLE
HabitRPG App crashes on Open

### ISSUE THREAD

**Issue by melissab603** [HabitRPG/habitica#5652]
I have a Samsung Galaxy S4 Active (Android Phone) and the HabitRPG app crashes every time I open it. It sometimes crashes when the phone starts up as well. I have "reported" the issue, but not sure how to put that information here.

**Comment by SpenserJ** [comment]
I'd suggest starting by clearing the application's cache, and if that doesn't work, the application data as well. You can find instructions on how to do so at [AndroidCentral](http://www.androidcentral.com/android-201-how-and-when-clear-app-cache-or-data).

If that doesn't fix it, please post the version of Android that you're running ([instructions](http://support.bell.ca/Mobility/Smartphones_and_mobile_internet/Samsung-Galaxy-S4.how_to_find_the_software_version_of_my_samsung)).

**Comment by melissab603** [comment]
Thanks!
