### ISSUE TITLE
Crossbow - Error processing the string 

### ISSUE THREAD

**Issue by mlordelo** [HabitRPG/habitica#5654]
Basic Crossbow item show "Error processing the string. Please see Help > Report a bug" in mouse over .

User ID: b61e2b46-fb3e-48ec-afed-96051f8df93b

Javascript error:
https://platform.twitter.com/widgets.js Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://s-static.ak.facebook.com/connect/xd_arbiter/X9pYjJn4xhW.js?version=41#channel=f3bb0bbe9&origin=https%3A%2F%2Fhabitrpg.com Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://www.facebook.com/connect/ping?client_id=172525162793917&domain=habi…9%26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://www.facebook.com/v2.0/plugins/like.php?action=like&app_id=172525162…Va94JIHLHPc.like&sdk=joey&send=false&share=false&show_faces=false&width=90 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED

**Comment by Alys** [comment]
Thanks @mlordelo. I've copied your bug report to this issue: https://github.com/HabitRPG/habitrpg/issues/5465 (see the final comment).

**Comment by crookedneighbor** [comment]
I've fixed the error in the translation. Will deploy shortly.
