### ISSUE TITLE
Subscription went away 

### ISSUE THREAD

**Issue by proxforge** [HabitRPG/habitica#5657]
User-ID: 7374977d-317f-4764-9234-31c870977c48
I bought premium a few days ago, now its gone?

**Comment by proxforge** [comment]
I did a gift-option for 1 month via paypal, than I had the premium options. Then I bought 1GEM with 20Gold .. ehmm than I did not look very often into habitrpg for 1-2 days. Now I looked today, and the premium-options and things are gone... :)

**Comment by Alys** [comment]
Sorry about that! I've confirmed that there's no active subscription on your account and I've given you a refund of the $5 payment you made a couple of days ago, although it might take a few days for PayPal to credit the amount to your account.

Please try again (if you'd like to!) and comment here if it's happens again. I think it should be okay next time though. I've cleared out old subscription data from your account in case that was what was causing the problem.

For our reference:

```
    "purchased" : {
        "plan" : {
            "paymentMethod" : null,
            "planId" : null,
            "customerId" : null,
            "dateTerminated" : ISODate("2015-06-25T12:16:43.896Z"),
            "dateUpdated" : ISODate("2015-07-22T13:16:20.226Z"),
            "consecutive" : {
                "trinkets" : 0,
                "gemCapExtra" : 0,
                "offset" : 0,
                "count" : 0
            },
            "mysteryItems" : [ ],
            "gemsBought" : 0,
            "extraMonths" : 0
        }
    },
```
