### ISSUE TITLE
Got wrong message for item lost upon death

### ISSUE THREAD

**Issue by harrysalzman** [HabitRPG/habitica#5659]
When I died, I got the message that my "Scimitar" broke, but it's a Kukri that's showing up as re-purchaseable in the store.

User ID is e1255e0c-1c80-456c-87d3-fae3006d7161

Using Firefox 39.0 and Windows 7 Enterprise.

**Comment by Alys** [comment]
How long ago was this? Please tell us in terms of a number of minutes or hours in the past, rather than a specific time because timezones make specific times hard to deal with.

**Comment by Alys** [comment]
The reason I'm asking is that we had a code change very recently and then another one after that, and I'm hoping to pin down exactly which pieces of code were on the site when this happened.

**Comment by harrysalzman** [comment]
This happened this morning - sometime between ~5 and 9 AM EST, roughly.

**Comment by Alys** [comment]
Please can you tell us how many hours ago that was.

Or at least tell us what the exact time is right now in that timezone
(gnthub's timestamps will then tell us what we need).

**Comment by harrysalzman** [comment]
Sorry! At this moment, it is 1:55 PM EST.

I saw the message at 9 AM EST, which was 4 hours, 55 minutes ago.

**Comment by Alys** [comment]
Thanks @harrysalzman 

For our reference: The rollback happened 9 hours ago. https://github.com/HabitRPG/habitrpg/issues/5624#issuecomment-124018717

**Comment by Alys** [comment]
We haven't seen any other instances of this recently, so I'm going to attribute this to a once-off glitch, but I've recorded it in our original issue for this problem so that we can track it easily.
