### ISSUE TITLE
Suggestion: Undo Button

### ISSUE THREAD

**Issue by marcusds** [HabitRPG/habitica#566]
If I accidently I did or didn't do something, let me hit undo.

**Comment by Pandoro** [comment]
This has been suggested frequently before. You can, or can not vote for it at this [trello card](https://trello.com/card/undo-button/50e5d3684fe3a7266b0036d6/20)

It is one of the top rated features, so it will be there eventually. [That is why I say you can or can not ;)] Right now it doesn't make a big difference. However as lefnire explains on the card, it is a fairly complicated thing to implement and many other features, which have a greater meaning to large parts of the community right now, will probably be implemented earlier.

Hopefully this will not cause too much inconvenience for you! 

I will close this issue, to keep the board clean, but feel free to post more on here if you have further feedback or questions.
