### ISSUE TITLE
Death followed by quest completion = no XP or gold rewards

### ISSUE THREAD

**Issue by harrysalzman** [HabitRPG/habitica#5660]
My party was running "Vice Awakens", and when the cron rolled over, I apparently took enough damage to die. Four hours later (going by the Party chat timestamps), my party defeated the dragon.

As a result, when I logged on this morning, I got a "You died" message, followed by a "Quest successful" message - but I did not get any of the XP or gold rewards for this quest, presumably because my death wiped them out.

The XP reward would have been enough by itself to push me up to a new level, too, which is more than a little galling.

User ID is e1255e0c-1c80-456c-87d3-fae3006d7161

Using Firefox 39.0 and Windows 7 Enterprise.

**Comment by crookedneighbor** [comment]
@harrysalzman If you feel that death was unfair, you can grant yourself the xp and gold with the "Fix Character Values" button in settings > site. Everything else (achievement and quest awards) should have been awarded correctly.

**Comment by harrysalzman** [comment]
Thank you for the info.
