### ISSUE TITLE
iOS app doesn't sync any of its progress to Website

### ISSUE THREAD

**Issue by GoranTomacruz** [HabitRPG/habitica#5662]
I recently added many dailies and checked of many tasks yesterday on my mobile app (I didn't use my computer). However, what happened was all my progress was removed hours later and my dailies and tasks reset to that of the website. Also, this took /hours/, and I was hoping that both would sync in a minute or so. Please fix this! I appreciate your help. Thank you. :)

**Comment by crookedneighbor** [comment]
@NobleNeon Are you using the old iOS app (treasure chest icon) or the new [Habitica app](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) (purple with white gryphon icon). 

If you're using the old one, please try out the new one. It's much improved.

If you are using the new one, please open your issue in the [repository for the iOS app here](https://github.com/HabitRPG/habitrpg-ios).
