### ISSUE TITLE
key to the kennels not working

### ISSUE THREAD

**Issue by glitterwaif** [HabitRPG/habitica#5668]
I have Triad Bingo so decided to use the free Key to the Kennels, but when I select it, it does not give the option of actually using it. The only option is "Not Yet" (apart from the button to buy gems).
I've tried re-synching, logging out and back in again, logging in on a different browser (I mainly use Firefox and have also tried on Safari) but nothing has worked yet. What's going on? I have all these drops and nothing to use them on, and I'm getting rather bored...

![screen shot 2015-07-26 at 1 59 39 am](https://cloud.githubusercontent.com/assets/13499624/8890640/38fb51d0-333a-11e5-8a98-2c73ad60cdd8.png)

**Comment by SabreCat** [comment]
What's your user ID? (from the Settings gear icon > API; please don't share your API Token)

**Comment by crookedneighbor** [comment]
This may be related to some recent changes I made to the counting scripts. I won't be near a computer to troubleshoot it for the rest of the day, but I can investigate tomorrow. I suspect an ng-if needs to be updated.

**Comment by Alys** [comment]
Confirmed on my account (d904bd62-da08-416b-a816-ba797c9ee265). I have all mounts and all pets (hatched+rehatched) and the Key to the Kennels modal has only the "not yet" button.

**Comment by crookedneighbor** [comment]
I figured it out. Previously the pet/mount counts were on $rootScope. I put them on the inventory controller scope instead, but the keys to the kennel modal wasn't being managed by the inventory controller. Deploying.

https://github.com/HabitRPG/habitrpg/commit/e72543641c5c4418be132b80d268a8e69d503926
