### ISSUE TITLE
Text in `code` gets out of the window

### ISSUE THREAD

**Issue by Jazzis18** [HabitRPG/habitica#5669]
Desrcription in the issue title.
My UserID: `ca1d308f-49db-460b-b3dd-e321cfc2e9aa`
Browser: Chrome 44.0.2403.107 m
OS: Windows 7 Ultimate x64
Screenshot:
![2015-07-26_155809](https://cloud.githubusercontent.com/assets/4019829/8893584/58dd4a2e-33af-11e5-86b7-7cf7364e5f44.png)

**Comment by sgabler** [comment]
@Jazzis18: One of the purposes of code blocks is to keep the formatting, so long lines are usually not wrapped (as far as I know). Why do you need the code block in the description, if you don't mind me asking?

It's definitely possible to wrap code here, the question is just if it wouldn't make more sense to just display the backticks `` here instead? Ideas?

**Comment by Jazzis18** [comment]
@sgabler A simple text selection. No more.

**Comment by Alys** [comment]
The conversion of backticks to code blocks is a standard part of markdown, so we should keep that conversion and not display the backticks instead.

It probably should wrap but that might be something controlled by the library we use (which is not to say we won't change it; it just might not be a simple change).

**Comment by Jazzis18** [comment]
@Alys I see =)
