### ISSUE TITLE
Guild Description Edit - entity too large

### ISSUE THREAD

**Issue by MaxHedrm** [HabitRPG/habitica#5671]
When editing my guild description, I get:

> Please reload, "Error request entity too large" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

This happens regardless of the change. The only thing I haven't tried is making the description blank. I have reloaded. I have also tried it across several days. On 2 different computers. Safari (Mac), Chrome (Win7).

The group in question is: https://habitrpg.com/#/options/groups/guilds/896f82a1-a7d9-489c-9bdd-4fccd3373630

My userID: b7fd010e-bf83-47af-a2a1-70144c224b93

**Comment by Alys** [comment]
Tell us what changes you'd like to have made and we'll make them for you.

**Comment by MaxHedrm** [comment]
That fixes the description, but doesn't fix the bug. :-)

This is what I want to change it to:

We are considering a Guild name change, PM me (MaxHedrm) with suggestions and I'll create a voting Challenge.

---

**Just a guild for those of us going the Coursera route! Or any other MOOC (Massive Online Open Course) provider for that matter.**

---

MOOCs provide a great way to increase your knowledge and skills affordably, but their online nature can lead to a feeling of isolation. This was created as a social guild, but Challenges are always welcome!

**Comment by Alys** [comment]
Yes, I know it won't solve the bug, but we have the bug reported in this issue: https://github.com/HabitRPG/habitrpg/issues/1471 and so we don't need to track it here as well. We are making large, site-wide changes that will prevent this happening but those changes take time. In the meantime, when you want changes that you aren't able to make yourself, we will do it for you. Comment here or in that other issue if you need more done in future. I've made this change.
