### ISSUE TITLE
Bug description for Soothing Lunar Sceptre on portuguese language

### ISSUE THREAD

**Issue by lothrus** [HabitRPG/habitica#5674]
There is no description for Soothing Lunar Sceptre on portuguese language. In English, it shows normal. Just Checked the translation at transifex and there is no problem there.

I'm Using chrome browser and windows 7.

![capture](https://cloud.githubusercontent.com/assets/2285976/8909491/ef1ff934-3457-11e5-8b8b-a6f7b743b22b.PNG)

**Comment by crookedneighbor** [comment]
I've copied this report here where we're keeping track of these issues: https://github.com/HabitRPG/habitrpg/issues/5465#issuecomment-125432854

Feel free to subscribe to that issue to track the progress of this.
