### ISSUE TITLE
Cantras Mod Avatar

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5676]
We're ready to update the Community Guidelines to include Cantras as a mod! I'm attaching the updated image. (As a side note, it's gotten quite long, so the next time we add a mod, I will be changing the layout of the image.)
![npc mods4](https://cloud.githubusercontent.com/assets/3494081/8918443/e58b6b64-346c-11e5-99e2-6763b238755c.png)

**Comment by Alys** [comment]
I'm advertising this in the Aspiring Coder's guild but if it's not taken up in a couple of days, I'll do it.

**Comment by sgabler** [comment]
I'd like to grab this task, if it's still available. Cloning the repository currently on a very slow 1 Mbps connection :turtle:

**Comment by Alys** [comment]
Please do! I still haven't had time to get to it. Thank you.
