### ISSUE TITLE
Mobile Iphone App Bug 

### ISSUE THREAD

**Issue by mataulvr** [HabitRPG/habitica#5677]
I recently entered the inn with my own character and then signed out of my account and into my boyfriends account to enter him into the inn as well. When I signed back on to my character our pets, items, food and quest scrolls seem to have merged. I cannot use his items and I get Server issue warnings when I tried using the items. When I restart the app the items still remain there. When I sign on, on my computer I just see my items and not the other accounts. 
Not sure exactly what this means but I thought it was an interesting enough issue to post here. Thanks! 
![img_6292](https://cloud.githubusercontent.com/assets/13454263/8919375/164ef9a0-347c-11e5-8a19-fcaf9b47fdb1.PNG)
![img_6291](https://cloud.githubusercontent.com/assets/13454263/8919374/1644947e-347c-11e5-8908-806151e18ae1.PNG)
![img_6293](https://cloud.githubusercontent.com/assets/13454263/8919376/1658636e-347c-11e5-9b71-ecc3a475feae.PNG)

**Comment by crookedneighbor** [comment]
Thanks for reporting it, I've copied your text and opened an issue on the ios repo here: https://github.com/HabitRPG/habitrpg-ios/issues/134

Feel free to comment there or subscribe to the issue if you'd like to keep track of the progress.
