### ISSUE TITLE
Google Calendar task integration failure

### ISSUE THREAD

**Issue by dborbon** [HabitRPG/habitica#5678]
I love the idea of integrating tasks on Google Calendar with the app, however, every time I create a new task, a pop-up appears that says something like, "I thought you were done with that :(" and it takes health away. This is a problem because these are tasks that I have NOT already done, though there may be tasks that I may repeat from time to time, like a chore. My suggestion, is that the feature that subtracts health for making new tasks would be fixed/disabled, so that we actually want to use this very useful integration! Thank you.
##

**Comment by Alys** [comment]
Are you using the [Chrome Extension](http://habitica.wikia.com/wiki/Chrome_Extension) for integrating your tasks? If so, I'm very sorry but it is no longer supported. We don't have enough developers to be able to continue to work on it while also doing everything that needs to be done on HabitRPG and its mobile apps.

If you're using something else to achieve the integration, you'll probably need to talk to the developer of the tool, although if you wish to you can leave details here in case it is something we can help with. However we'll need to know what you're using and exactly what the error message is.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
I'm closing this since I haven't heard any recent reports of it.

@MathWhiz Thanks!
