### ISSUE TITLE
Uncompleting a completed task

### ISSUE THREAD

**Issue by rjpursley** [HabitRPG/habitica#5679]
ID affected: 49920c2d-065c-45e0-8df1-f4c85a1289cd

I recently uncompleted a task that I was trying to click on for the Backstab skill that accidentally completed the task out instead. Once I undid my mistake it said minus double xp(that's fine it was my bad). But looking at my ex it says -1500 xp. That's not accurate by 1200 xp. Can this get fixed please?

**Comment by Alys** [comment]
You can adjust your stats using Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).

Let us know if you have any problems with that!
