### ISSUE TITLE
Username superimposed on a chat message

### ISSUE THREAD

**Issue by Jazzis18** [HabitRPG/habitica#5681]
In any chat, a username superimposed on a chat message, if it has a slider.

![2015-07-28_145146](https://cloud.githubusercontent.com/assets/4019829/8928537/8e684a9c-3538-11e5-8079-3bd5b030c6e2.png)

My UserID: `ca1d308f-49db-460b-b3dd-e321cfc2e9aa`
Browser: Chrome 44.0.2403.107 m
OS: Windows 7 Ultimate x64

**Comment by Alys** [comment]
It's meant to be like that as soon as you start scrolling down.

Is it like that before you've scrolled?

**Comment by Jazzis18** [comment]
Before scrolling all right.
![2015-07-28_162230](https://cloud.githubusercontent.com/assets/4019829/8930176/0e48ad36-3545-11e5-854e-c1b23c5eee51.png)

**Comment by Alys** [comment]
Thanks @Jazzis18.

The name appears over the text as you scroll down so that you can still see the author.
