### ISSUE TITLE
'Invite Party' Button Not Working

### ISSUE THREAD

**Issue by JenniferMartin** [HabitRPG/habitica#5687]
When trying to start a new quest, I click on the 'Invite Party' button, it animates with a key press, and then nothing happens. I can click many, many times, and still there's no response, making it impossible to start the quest. The 'Cancel' button works, and I can also close the quest window by clicking in the gray area around it.

It is not giving me an error message; it simply doesn't respond.

I have tried refreshing the page, hard refreshing the page, and switching browsers, but the behavior does not change. I have tried launching other quests, but they have the same issue. I am running Windows 7 64-bit; my primary browser is Firefox 39.0, and the other browser I tried is Chrome 44.0.2403.107.

Some potentially relevant background: I quest solo. This would be the fourth time in a row I'm starting the same quest (it's the owl egg quest). I only use the web version of HabitRPG, and only on a PC. My user ID is 154802ac-9567-4916-ac66-79ea5ba81ec7.

**Comment by crookedneighbor** [comment]
Thanks for reporting this. I've replicated the problem and am working on a fix now.

**Comment by crookedneighbor** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/442c1f358bb8a5d122272bf821c29b2a4b548a1b

Should be fixed now. Sorry for the inconvenience.

**Comment by JenniferMartin** [comment]
Thank you very much for getting to this so quickly!

It is indeed working now.
