### ISSUE TITLE
Incorrect damage first rollover after accepting quest.

### ISSUE THREAD

**Issue by jacornis** [HabitRPG/habitica#5691]
Every time I have accepted a quest, it seems that on the first rollover night I give/get the normal amount of damage, but then a few hours later another rollover is calculated. Since this is around 4 AM, I haven't done most of my dailies and massive damage is dealt. I do use both the android and desktop apps. See logs from party below (I'm Jacqueline Cornish):

![image](https://cloud.githubusercontent.com/assets/6456358/8966406/7f999e7e-35ee-11e5-9a74-beb3bff79650.png)

![image](https://cloud.githubusercontent.com/assets/6456358/8966480/d173e63c-35ee-11e5-94e3-fef8845c4eac.png)

**Comment by Alys** [comment]
Please check that your PC(s) and phone(s) and tablet(s) are all set to
EXACTLY the same time and timezone.

**Comment by jacornis** [comment]
This is definitely the issue. I've been having trouble with the timezone on different apps on my phone for about a year now. I'll just avoid using the mobile app while I'm doing quests from now on until I get a new one. Thanks for the help!

**Comment by Alys** [comment]
@jacornis Thanks for letting us know!

Note that even when you're not on a quest, it's likely that [cron](http://habitica.wikia.com/wiki/Cron) is still running twice every day to damage you for your incomplete Dailies, it's just harder to tell that's happening when you don't have the quest messages to see the duplicates. However we're planning a change to cron that might help with this. I'm not sure when it will be released though.
