### ISSUE TITLE
Cannot login into habitca.com using FB auth due to domain change

### ISSUE THREAD

**Issue by Simmiah** [HabitRPG/habitica#5694]
Went to habitica.com and tried clicking login/register with facebook on opera/chrome.
Got this error message from FB.
![fb_login](https://cloud.githubusercontent.com/assets/4175038/8972509/c94315c0-360f-11e5-8f1a-7c1c42d2cb1c.png)

User ID: e5f755ba-d5d0-4012-8c47-e9be3a6945fa

I worked around this by making a local auth but I like lazy logins :laughing:

**Comment by Alys** [comment]
@Simmiah Thank you very much for taking the time to report this, even after you'd worked around it! That bug is very important for us to know about! :heart:

**Comment by gisikw** [comment]
@Simmiah Thanks for bring this to our attention. I believe the issue should be resolved now :) Please feel free to reopen this if you're still encountering issues!
