### ISSUE TITLE
Triple boss attacks in a day

### ISSUE THREAD

**Issue by FeralemTau** [HabitRPG/habitica#5697]
I've got a serious issue with my party. There were three boss attacks by me:
"Feralem Tau attacks The Iron Knight for 14.4 damage, The Iron Knight attacks party for 49.4 damage." 07/30/2015 00:19:33, local time - 07/29/2015 23:19. Visited HabitRPG from a laptop, Windows 7, Google Chome 44.0.2403.107 m
"Feralem Tau attacks The Iron Knight for 20.6 damage, The Iron Knight attacks party for 0.0 damage." 07/30/2015 01:32:59, matching local time. Visited from a tablet, Android 4.0.4, HabitRPG app for Android.
"Feralem Tau attacks The Iron Knight for 0.0 damage, The Iron Knight attacks party for 81.3 damage." 07/30/2015 12:16:27, local time - 07/30/2015 11:16, laptop, Windows 7, Google Chome 44.0.2403.107 m

My ID: 6715eb84-8db6-458f-b918-31660bf2047b
Party ID: f992c95e-71ee-4595-ac84-7f0292d66a3f

**Comment by Alys** [comment]
@FeralemTau Please check the time and timezone on all the devices that you use HabitRPG on. Are the time and timezone EXACTLY the same on all of them? 

Do any of them have any problems with the clock being inaccurate or resetting itself?

Have you changed the time or timezone on any of them in the past day?

Have you changed the [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) setting in HabitRPG in the past day?

**Comment by Alys** [comment]
I'm closing this because I think it's probably a time/timezone setting issue on one of the devices you use, but if you'd like us to keep investigating, please look into the questions in my previous post and let us know if none of them applied.
