### ISSUE TITLE
Skeleton Dragon Mount is standing in front of avatar

### ISSUE THREAD

**Issue by Gwillewyn** [HabitRPG/habitica#5698]
User-ID: 6e28bf49-0dd3-47b7-9a32-e4785acad894

Both in my browser (Firefox 39.0, on Windows 8) and on my phone (Android 4.4.2), my Skeleton Dragon Mount is standing in front of my Avatar, blocking it almost completely from view.  It's been like that for days.
![infront](https://cloud.githubusercontent.com/assets/7745263/8980514/8ccf35a4-36b1-11e5-96e1-7aa23f85ff62.png)

![2015-07-30 09 47 03](https://cloud.githubusercontent.com/assets/7745263/8980484/52875f34-36b1-11e5-8478-aee636b6ef2f.png)

Is it supposed to be that way?  Have I fallen through its ribcage?

**Comment by Alys** [comment]
Yes, that's how it's meant to be. You're riding on the back (on the spine) of the skeleton. Its head and shoulders are in front of you (as for all mounts), as is one of its wings. It's the same for the other dragon mounts: http://i.gyazo.com/8d7b9e9b2d765e81d214abfca62b20ed.png
