### ISSUE TITLE
Gems randomly disappearing?

### ISSUE THREAD

**Issue by Kathryn-the-Writer** [HabitRPG/habitica#5700]
On July 20, I contributed $5 via Google Play and got 20 gems. 10 of them I spent that day. The other 10 gems have been sitting in my account since then.

This afternoon it says I have 8 gems. I haven't bought anything since the 20th, so I should still have 10, right? But both the Android app and Chrome are now showing that I have 8 gems.

Any ideas? :-)

Thanks,

Kathryn the Writer
User ID: 78127855-083c-4436-a024-08310fa863ae

**Comment by Alys** [comment]
@Kathryn-the-Writer I've downloaded a recent backup of the database so that I can examine your account before and after the gem loss. It might take a bit of time but I'll get back to you.

**Comment by Alys** [comment]
@Kathryn-the-Writer I've given you two extra gems.
