### ISSUE TITLE
Some references to HabitRPG still exist

### ISSUE THREAD

**Issue by bean5** [HabitRPG/habitica#5701]
navbar-brand used at https://habitica.com/static/community-guidelines is one location that can be quickly fixed (doesn't have to wait for icon/image updates).

**Comment by Alys** [comment]
Thank you but we're handling all these changes behind the scenes with automatic updates and other processes. :) 

It might take a little time for all mentions of HabitRPG to be changed. See the Bailey messages for updates!

**Comment by bean5** [comment]
Awesome!
