### ISSUE TITLE
Kampfausrüstung; Verzauberter Schrank; "Viehzüchter Lasso"

### ISSUE THREAD

**Issue by Babaachan** [HabitRPG/habitica#5704]
I have obtained the item "Viehzüchter Lasso".

The item description says:

"Error processing the string. Please see help > Report a bug."

**Comment by Alys** [comment]
Thanks @Babaachan ! I've copied your report to the issue we're using to keep track of this: https://github.com/HabitRPG/habitrpg/issues/5465
You can follow the progress there if you like, but it will be fixed in a day or two.
