### ISSUE TITLE
Some API users getting 401

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#571]
some are experiencing 401 or 403 access-denied for verifiably accurate uid / apiToken API calls. (thought this was an issue, close if dupe).

Couple people via email have mentioned same issue.

**Comment by lefnire** [comment]
unrelated - some more people wanting to get involved in native iOS - i created a [discussion here](https://trello.com/card/native-iphone-app/50e5d3684fe3a7266b0036d6/209) and mentioned you

**Comment by switz** [comment]
What routes are you attempting to use?

**Comment by switz** [comment]
Confirmed, some users reporting user not found. I think this might have to do with `req._isServer = true` being set after the query has been made. We'll try out the fix tomorrow when Tyler is around to deploy it.

**Comment by ruddfawcett** [comment]
@switz Cool, thanks!  Btw, I had a post here regarding my testing... I might've deleted it by accident? anyway, thanks

**Comment by elssar** [comment]
I was getting 504s when I tried it out earlier today, about 9 hours ago.

**Comment by lefnire** [comment]
getting some mixed results on the new api:

`$.ajax({type:"GET",url:'https://habitrpg.com/api/v1/user',headers:{'x-api-user':'ad71feef-056f-40d9-b1fb-144ce156cd4d','x-api-key':'285dec52-d032-4860-acf4-b589dc64d857'}})`
=> 401 (Unauthorized) 
(my dummy account, we can mess with this guy)

same route, but swapping in my real user credentials sometimes gives me simply "error" as a responseText (can't replicate now, getting 401 instead). Deprecated routes work just fine

**Comment by lefnire** [comment]
fwiw, I deployed CORS https://github.com/lefnire/habitrpg/commit/6bfe1d076e2de488d6f05943e65bf6773e2dea95

**Comment by switz** [comment]
401 is just malformed request (I.e. no user found) we'll have to dive in and see what's stopping racer from finding those users.

**Comment by lefnire** [comment]
@litenull is making great progress in this, we think it's CORS at present. Seems x-api-user & x-api-key headers aren't being accepted from external domains.

**Comment by lefnire** [comment]
ok, everyone that was experiencing issues - give that a shot

**Comment by elssar** [comment]
Still getting 504s

**Comment by lefnire** [comment]
bummer. Ok, litenull me & switz are gonna do a pair-session tomorrow morning, hopefully will have this pegged soon

**Comment by switz** [comment]
I'm not convinced this is CORS. Why does my account work locally in curl, but his doesn't? CORS shouldn't necessarily affect that.

**Comment by litenull** [comment]
It was CORS, at least the first problem we solved. Now I can make cross
domain calls, but my account doesnt work. Tyler's account works. So its
something with the getting from db.

On Sat, Mar 9, 2013 at 5:05 AM, Daniel Saewitz notifications@github.comwrote:

> I'm not convinced this is CORS. Why does my account work locally in curl,
> but Rudd's doesn't? CORS shouldn't necessarily affect that.
> 
> On Friday, March 8, 2013 at 7:13 PM, Akshay Bist wrote:
> 
> > Still getting 504s
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/lefnire/habitrpg/issues/571#issuecomment-14653575).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/571#issuecomment-14657566
> .

## 

LP, Tomaž :)

**Comment by lefnire** [comment]
and now?

**Comment by lefnire** [comment]
woohoo!

**Comment by elssar** [comment]
Hate to be the party-pooper here, but I'm still getting 504s.

Then I tried it on [hurl.it](http://www.hurl.it/), and got [a 404](http://www.hurl.it/views/6f7949bd7f677b9d20ac5eb5eb711be2feeac1e2) there.

**Comment by switz** [comment]
504 is a gateway timeout. Can you provide a little more info as to how you're constructing your api calls?

**Comment by elssar** [comment]
I'm using Python's requests library to make the, erm, requests. Here is the code that I use

```
from requests import get
headers= {'content-type': 'application/json', 'x-api-user': user, 'x-api-key': token}
url= 'https://habitrpg.com/api/v1/user'
res= get(url, headers= headers)
```

Don't think there is anything wrong there. If it's not the server, then it is possible it might be my internet connection, which can sometimes be finicky when it comes to anything not coming from the browser. But api calls to other services like github or coderbits work just fine.

But it works on the REST console I just installed, so it must be something on my end.

**Comment by litenull** [comment]
Replace = with :
Headers is a JSON object.

On Sat, Mar 9, 2013 at 5:34 PM, Akshay Bist notifications@github.comwrote:

> I'm using Python's requests library to make the, erm, requests. Here is
> the code that I use
> 
> from requests import get
> headers= {'content-type': 'application/json', 'x-api-user'= user, 'x-api-key'= token}
> url= 'https://habitrpg.com/api/v1/user'
> res= get(url, headers= headers)
> 
> Don't think there is anything wrong there. If it's not the server, then it
> is possible it might be my internet connection, which can sometimes be
> finicky when it comes to anything not coming from the browser. But api
> calls to other services like github or coderbits work just fine.
> 
> But it works on the REST console I just installed, so it must be something
> on my end.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/571#issuecomment-14665948
> .

## 

LP, Tomaž :)

**Comment by elssar** [comment]
@litenull oh yeah, that was a typo here, i was using `:` in my code.
