### ISSUE TITLE
Name still shows up as HabitRPG in password reset email

### ISSUE THREAD

**Issue by dmhowcroft** [HabitRPG/habitica#5710]
The re-branding of HabitRPG to Habitica happened today, but the password reset email hasn't been updated yet.

Expected behavior:
1) Email will arrive from admin@habitica.com
2) Subject line will read "Password Reset for Habitica"

Actual behavior:
1) Email arrives from admin@habitrpg.com
2) Subject line reads "Password Reset for HabitRPG"

To reproduce:
1) Request a password reset from the login (in-screen) pop-up on habitica.com

Should be a quick fix :)

**Comment by Alys** [comment]
Thanks but we've fixed that already. :)

**Comment by Alys** [comment]
Note the URLs in the reset email are still pointing to the old site but they'll redirect. We'll get them fixed up soon. They use config variables that we need to change cautiously.

**Comment by dmhowcroft** [comment]
Ah, okay. Not fixed in the production version, though, I assume? (I received said email at 9:58 GMT.)

**Comment by Alys** [comment]
No, it's fixed in production. I did a test and the email had the Habitica name. It might have been after your email was sent.

**Comment by dmhowcroft** [comment]
Hm, alright. I can confirm that it now works for me as well. You guys must be fixing issues mighty fast!
