### ISSUE TITLE
Trouble logging in through facebook

### ISSUE THREAD

**Issue by johncostanzo** [HabitRPG/habitica#5712]
Since the Habitica update, I cannot login through facebook. I click the "Login / register with Facebook" button, it opens up another Habitica page very quickly, and then closes. And then nothing happens.

**Comment by Alys** [comment]
Which browser are you using, including version number. Which operating system / mobile device are you on?

**Comment by johncostanzo** [comment]
Brower - Microsoft Edge 20.10240.16384.0
OS - Windows 10

**Comment by Alys** [comment]
Thanks! This is a duplicate of https://github.com/HabitRPG/habitrpg/issues/5428 so I'll close this issue now, but if you wish to, you can subscribe to notifications from that issue using the subscribe button in the right-hand column.

**Comment by Alys** [comment]
If you have another browser available to you, the login should work in that.
