### ISSUE TITLE
www.habitica.com is NXDOMAIN

### ISSUE THREAD

**Issue by teh-maxh** [HabitRPG/habitica#5717]
Expected behaviour:

```
$ nslookup www.habitica.com 8.8.8.8
Server:     8.8.8.8
Address:    8.8.8.8#53

Non-authoritative answer:
Name:   www.habitica.com
Address: 45.79.172.232
Name:   www.habitica.com
Address: 45.79.106.117
```

Actual behaviour:

```
$ nslookup www.habitica.com 8.8.8.8
Server:     8.8.8.8
Address:    8.8.8.8#53

** server can't find www.habitica.com: NXDOMAIN 
```

Suggested fix:

Add a DNS record for `www.habitica.com`. Personally, I would make the `A` records for `www.habitica.com` and `CNAME` `habitica.com` to `www.habitica.com`, but keeping the `A` records for `habitica.com` and `CNAME`ing `www.habitica.com` to `habitica.com` or (less optimally) adding additional `A` records for `www.habitica.com` would also fix the problem.

**Comment by crookedneighbor** [comment]
Thanks, we'll get this fixed up soon.

**Comment by teh-maxh** [comment]
I don't want to be a bother, but this hasn't been forgotten, has it?

**Comment by Alys** [comment]
@teh-maxh No, it's not forgotten; we have things that are higher priority to work on.

**Comment by teh-maxh** [comment]
Alright, just wanting to make sure. 👍

**Comment by gisikw** [comment]
All fixed! Sorry for the delay :)
