### ISSUE TITLE
Can't Leave Party I Created

### ISSUE THREAD

**Issue by The-Raggamuffin** [HabitRPG/habitica#5718]
My User ID is: 3e5fd45a-ab0d-4520-9fc3-9fc81f6a313a
Can someone please help me to shut down this party (9412287c-488d-4fc8-aea7-cb2bc6b7e61e).

I created it and was going to add a friend but he has already created a party with some of our friends in it so I tried to leave. When I tried I received this message: 
"Please reload, "Error Runner error: Overflow sort stage buffered data usage of 34293652 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages."
I have reloaded. I have closed and reopened my browser, and I have tried on another browser.

**Comment by Alys** [comment]
I've deleted your party. If you reload your party page now, you should see that you're no longer in a party and you should able able to receive party invitations.

I'm closing this now, but if there's any problems, comment here and we'll keep helping.

For the record: there were no other people in the party and no quest.
