### ISSUE TITLE
Cannot delete tags on iPad

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5719]
Since the switch over to Habitica, I cannot delete tags on the iPad (iOS 8.4, Chrome). Nothing happens when I tap the garbage pail next to the tag. This worked on HabitRPG up until the switch.

**Comment by ghost** [comment]
Either something was changed or it was a glitch. Working now.

**Comment by Alys** [comment]
We didn't change anything. It would have been a temporary browser problem.
