### ISSUE TITLE
Reward cost bug

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#572]
I just tried setting a reward that only costs silver. I set a reward to 0.1, upon clicking I only payed 9 silver. 

This is probably minor, but there have been bugs before regarding the cost of stuff, so it might be part of a larger bug. 

OR did the new system incorporate the armor into the cost calculation @MrConcept ?
I would be very much against that :x

**Comment by PhilipHow** [comment]
Yeah, can replicate (just about with #553) I'll look into it. I'll also add #573

**Comment by rixx** [comment]
Fixed for me. Entering 0.1 Gold docks 10 Silver as it should.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
