### ISSUE TITLE
Gibberish code (Math.floor(user.stats.exp) etc) on homepage / tasks page prevents viewing tasks AGAIN

### ISSUE THREAD

**Issue by bbaharan** [HabitRPG/habitica#5720]
Hello dear colleagues,
Today, I tried to log on my account but I couldn't. Then I refreshed the page and I saw my task page blank with two red (health) and yellow (experience) bars on the top as in the attached picture. I tried all the ways suggested in a similar issue in the following link:
https://github.com/HabitRPG/habitrpg/issues/5473
I tried the app on my phone, but I cannot log in. My boyfriend tied my account on his pc, the same problem as on my pc. Would you please help me get my account back? I thank you in advance.
Bahareh
![habitica problem](https://cloud.githubusercontent.com/assets/13599790/9021678/a9bb0e46-384f-11e5-9e31-49536cb54a1b.jpg)

**Comment by bbaharan** [comment]
I just realized that my account does not exist anymore. I tried to make an account with the email with which I submitted my account, it worked; so my account has been deleted! Why? First my account does not work properly and now it is deleted?! Help!

**Comment by Alys** [comment]
@bbaharan Your account has not been deleted. I have replied to the email that you sent to our admin address to give you a reminder of your username and the email address that you used when you created your account.

The email address that you used an hour ago to create a new account is not the same one that you used when you created your real account.

When you have logged in to your real account, please reply here to tell us if you are still seeing gibberish.

**Comment by bbaharan** [comment]
@Alys 
Dear Alys
It's OK now! Thank you so much!

**Comment by Alys** [comment]
no worries :) Thanks for letting us know!
