### ISSUE TITLE
Cannot get gems after purchase

### ISSUE THREAD

**Issue by gitobx** [HabitRPG/habitica#5727]
I just bought 20 gems in the Habitica app (iOS) but didn't get any gems.  I'm sure that App Store charged me for it.

User ID:664063bc-78bc-4b00-864b-12d76739975c

**Comment by Alys** [comment]
Could you please email your App Store receipt to admin@habitica.com and include your User ID and a brief description of the problem? We'll handle it by email instead of here so that your personal financial details aren't displayed publicly.
