### ISSUE TITLE
"Open new tasks in edit mode" does not work in Dailies

### ISSUE THREAD

**Issue by dgmagno** [HabitRPG/habitica#5728]
The option doesn't work in single Dailies creation. (the new created task stays closed for edition)
The option works fine in single Habits and To-Dos creation. (the new created task stays opened for edition)
The option doesn't work in any multiple task creation. (the new created tasks stay closed for edition)

Tested on Google Chrome Version 44.0.2403.125 (64-bit)
##

**Comment by Alys** [comment]
Confirmed. The Daily closes after the sync is complete so it might be related to https://github.com/HabitRPG/habitrpg/issues/2965 although I can't at the moment think of any reason why a Daily would cause syncing to happen differently than for another kind of task.
