### ISSUE TITLE
Add Silver to Rewards

### ISSUE THREAD

**Issue by PhilipHow** [HabitRPG/habitica#573]

**Comment by horusofoz** [comment]
@lefnire Is this ticket still required?

**Comment by lefnire** [comment]
Let's keep it open. You can add decimal numbers to your rewards value, but it breaks the css, doesn't validate the html5 validation rule, and I'm not sure if it works properly when you purchase rewards (I haven't tested). Will revisit

**Comment by paglias** [comment]
This is fixe now, which means that it doesn't trigger validation errors and works. But it breaks css when you have 4+ digits (10.01 or 1000) and it isn't specified anywhere that you can use silver, the icon is the gold one.

So we can close this unless you do want to add more silver-specific options & fixes.
