### ISSUE TITLE
App Shows Veteran Wolf's Growth Bar + Feed Error

### ISSUE THREAD

**Issue by RoseyMorearty** [HabitRPG/habitica#5730]
On the Habitica app, clicking on your Veteran Wolf gives it a growth bar. When you click on it, it gives you the option to feed it, but if you try, it will give you a network error (Couldn't connect to the server. Check your network connection). This is incorrect because this error should be caused because Veteran Wolves cannot be fed. A growth bar does not exist for the wolf either so it should not be shown. I hope this makes sense, I am not a programmer :)

My user ID: 1e0accf1-32c0-4066-85ec-1a6d6b6fdab5
Browser: (none, on iphone). Operating system: iOS 8.4

**Comment by crookedneighbor** [comment]
Thanks for reporting this. I've copied your issue to the iOS repo. If you'd like to track the progress of the bug, you can click the subscribe button in this issue: https://github.com/HabitRPG/habitrpg-ios/issues/144
