### ISSUE TITLE
Experience value exceeds experience bar limit

### ISSUE THREAD

**Issue by wilfredtee** [HabitRPG/habitica#5734]
Hi,

Today opened up website, experience bar value is higher than the experience bar limit:-

i.e. : 251 / 220

I've tried the following, it did not seem to fix the problem:-
1. logout, and then login
2. used a different browser
3. cleared cache
4. manually clicked on "sync"

see screenshot attached.

![image](https://cloud.githubusercontent.com/assets/13635683/9053384/d8ff6a22-3aa6-11e5-9367-42b40d3ff9ba.png)

**Comment by Alys** [comment]
Please see this issue for the explanation and fix: https://github.com/HabitRPG/habitrpg/issues/2433
