### ISSUE TITLE
Error processing the string in Season Limited Shop.

### ISSUE THREAD

**Issue by sujunmin** [HabitRPG/habitica#5735]
Siena Leslie
Error processing the string. Please see Help > Report a Bug.

In Season Limited Shop.

UID ac6fbe37-b0dc-40d8-ba14-77dde66fbfa8
Chrome 44.0.2403.89 (64-bit) Mac OSX 10.10.4

UI use translated Traditional Chinese

**Comment by Alys** [comment]
Thanks @sujunmin ! I've copied it to this issue where we collate these problems: https://github.com/HabitRPG/habitrpg/issues/5465

**Comment by SabreCat** [comment]
D'oh, that was my fault. I changed the way we link to the wiki in that string, so translators could link to translated wiki pages where available. But that broke existing translations that expected the wiki link to be inserted programmatically. :crying_cat_face:
