### ISSUE TITLE
When guild / party leader leaves, next member doesn't automatically become leader until someone else leaves

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#5737]
The [wiki](http://habitica.wikia.com/wiki/Guilds#Transferring_Guild_Ownership) says:

_"If the guild owner leaves without assigning a new leader, the most senior party member will be assigned the new leader automatically."_

... and that's probably how the code is supposed to work - but it doesn't. Actually, the guild leader change isn't triggered when the guild leader leaves (nor - if that leaves the guild empty - when someone else joins), but only when the next person leaves the guild.

If this can't be fixed in the near future, the workaround should probably be documented in the wiki. 

Usually the workaround is easy enough to use once you know about it. There are usually other guild members, or other Habiticans, who can be asked to leave and rejoin, or join and leave again. People can even make second accounts and do it with those. If it's an otherwise empty guild, leaving and rejoining oneself also works. (I've been thinking about suggesting that you could ask the WikiFAQ_bot to join and leave, but I guess anyone who is so new and helpless that they can't find any other way shouldn't be burdened with being guild leader anyway. %} )

**Comment by paglias** [comment]
Moved to #5871
