### ISSUE TITLE
Multiple consecutive identical drops

### ISSUE THREAD

**Issue by orion1919** [HabitRPG/habitica#5738]
I received about 6 consecutive dragon eggs while working this morning (literally back to back). I logged out, logged back in and died. I had been using habitica all morning, all party members had already logged in (so damage had been dealt), and still had plenty of health. No idea what caused me to die =(

**Comment by teh-maxh** [comment]
Please post your user ID; an admin will probably need it to look into what happened. You can find it on the [API settings](https://habitica.com/#/options/settings/api) page. Make sure to post the user ID, **not** the API token.

**Comment by deilann** [comment]
Actually, this is not unexpected.

Randomness allows this to happen. With so many users, it's not unsurprising
to have a user get six dragon eggs in a row. I've gotten four of the same
kind of drop in a row multiple times.

On Tue, Aug 4, 2015 at 9:56 AM, Max Harmony notifications@github.com
wrote:

> Please post your user ID; an admin will probably need it to look into what
> happened. You can find it on the API settings
> https://habitica.com/#/options/settings/api page. Make sure to post the
> user ID, _not_ the API token.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5738#issuecomment-127675333.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by deilann** [comment]
Sorry; didn't see the latter part of the ticket. Too early and going too much off the title, apparently! The drops are likely unrelated.

Do you use Habit on multiple devices?

Regardless, if you go to Settings (gear wheel) > Site and click the "Fix Character Values" button, you can patch yourself up to reverse the unfair death.

**Comment by orion1919** [comment]
Oh awesome!! I didn't realize I could fix myself up. Thank you!! 

I do use it across multiple devices (web and iPhone). I've noticed some odd things over the past few days with damage coming at times I couldn't explain. This morning was very different though. Thank you for the help!!

-Jonathan

**Comment by deilann** [comment]
No problem! It's probably related to using Habit on multiple devices. If
this has been happening more recently, I'd suggest trying to use only one
device for a bit and see if that reduces weirdness.

On Tue, Aug 4, 2015 at 10:09 AM, orion1919 notifications@github.com wrote:

> Oh awesome!! I didn't realize I could fix myself up. Thank you!!
> 
> I do use it across multiple devices (web and iPhone). I've noticed some
> odd things over the past few days with damage coming at times I couldn't
> explain. This morning was very different though. Thank you for the help!!
> 
> -Jonathan
> 
> > On Aug 4, 2015, at 9:03 AM, deilann notifications@github.com wrote:
> > 
> > Sorry; didn't see the latter part of the ticket. Too early and going too
> > much off the title, apparently! The drops are likely unrelated.
> > 
> > Do you use Habit on multiple devices?
> > 
> > Regardless, if you go to Settings (gear wheel) > Site and click the "Fix
> > Character Values" button, you can patch yourself up to reverse the unfair
> > death.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5738#issuecomment-127677974.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by Alys** [comment]
@orion1919 For all the causes of death, see the wiki's [Death Mechanics](http://habitica.wikia.com/wiki/Death_Mechanics) page. The section "Sudden, Unexpected Death" will contain one or more reasons that could apply in your case.
