### ISSUE TITLE
Automate updating of Armoire test

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5739]
Currently, the tests for the Enchanted Armoire in `algos.mocha.coffee` have some components that need to be manually updated every time the Armoire is restocked:
- The `fullArmoire` object describing what a user's `items.gear.owned` should look like when they've emptied the Armoire
- The specific pieces of gear dropped when an equipment drop occurs

If the test could be restructured in such a way as to make manual updates unnecessary, it'd smooth the process of monthly Armoire additions and make the tests themselves more valuable.

**Comment by crookedneighbor** [comment]
@SabreCat Why is the basic warrior weapon included in the full armoire in that test?

**Comment by SabreCat** [comment]
@crookedneighbor: The test checked the status of the user's `items.gear.owned` object. With the way we initialize a new user, we start them with the Warrior training sword, so object equality looking for just Armoire items would fail. Maybe not a concern with the way you've set things up.

**Comment by SabreCat** [comment]
:+1:
