### ISSUE TITLE
Chrome Extension pop-up notification won't switch off

### ISSUE THREAD

**Issue by MiriamELewis** [HabitRPG/habitica#574]
Title says it all really, I've tried everything can but I can't switch off the notification pop-ups. I'm sure I used to be able to but no more. I can switch on/off other extensions' notifications and I want to use the extension but without being given those little score updates.

**Comment by wc8** [comment]
Seems like this might be more related to the chrome extension than HabitRPG itself. If so, please post here: https://github.com/lefnire/habitrpg-chrome

**Comment by rixx** [comment]
(And if you posted it over there, you might close this ticket.)

**Comment by MiriamELewis** [comment]
I'll close it now. Changes to the website have made it completely unusable by me and the same has happened to the Chrome extension. I don't have the time to look into the issues so I've simply left for the time being. Its a shame as it worked fine enough until the Kickstarter finished and you got my money. >.<

**Comment by lefnire** [comment]
Miriam what specifically isn't working on the website?
