### ISSUE TITLE
Quest vanished

### ISSUE THREAD

**Issue by AikidoJunky** [HabitRPG/habitica#5740]
1. I clicked on a quest in my inventory ("Attack of the Mundane, Part 1: Dish Disaster").
2. I clicked on Invite.
3. An error popped up (sorry I didn't write down the text, but I think it mentioned something about 'undefined').
4. Clicked on quest again, and was told it wasn't in my inventory.
5. Refreshed page.
6. The quest vanished from inventory, but I'm not on it.
7. Checking the Market again, if I click on that Quest to buy it, it says: "You already earned this quest by attaining level 15. Buy this quest with 4 of your gems?"

Where did my quest go?

Note:  I have a group of just one (myself).  Not sure if that's causing an issue or not.

**Comment by crookedneighbor** [comment]
Can you check your party page and see if you are currently on the quest?

**Comment by AikidoJunky** [comment]
No quests listed on the Party page. Refreshed the page a few times to make sure.

On Aug 04, 2015, at 03:46 PM, Blade Barringer notifications@github.com wrote:

Can you check your party page and see if you are currently on the quest?

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by AikidoJunky** [comment]
Sorry for the delay.  Mail decided this was Junk apparently :(

26231c50-2580-46e7-812a-0c7bea2baef3

On Aug 04, 2015, at 06:21 PM, Blade Barringer notifications@github.com wrote:

What's your User ID? You can find it in Settings > API. Be sure to only copy the User ID and not your API Token.

**Comment by Alys** [comment]
I've given you that quest. Please refresh your quests page and tell me if it does't appear on the left-hand side. I'm closing this now, but we'll still see any replies you make.
