### ISSUE TITLE
Next equipment piece in class gear progression doesn't appear right away

### ISSUE THREAD

**Issue by soar9** [HabitRPG/habitica#5743]
The Royal Shield item for healers does not immediately disappear when purchased. If the player clicks again, the gold will be deducted as many times as they click. After a while the item does disappear, but the gold is still gone.
This problem is on IE, Windows 8.1.
User ID: f1cd9be7-4291-4d94-a609-01d0563dc576

**Comment by Alys** [comment]
Please reload the site and then click the sync button in the top right hand corner. Does the gold now reappear?

**Comment by SabreCat** [comment]
Edited the title to be a more generic description of the issue. This frequently happens with any class gear piece, not just the Royal Shield.

**Comment by Alys** [comment]
I've been trying to track down when this bug appeared. If I revert my local install to https://github.com/HabitRPG/habitrpg/commit/16f0ece2f8d8ecb1bca801efa2288858b7a18911 then gear disappears from the Rewards column as soon as I click on it with no need to wait for the sync to finish (and the next item appears immediately). This is the ideal situation, I believe.

If I revert to the commit after that (https://github.com/HabitRPG/habitrpg/commit/8f744b043a148fa805e27872d4c56dcb2a8675ea) there is a delay - the gear does not disappear until the end of the sync that occurs when you purchase the item.

Here's the diff between those two commits: https://github.com/HabitRPG/habitrpg/compare/16f0ece2f8d8ecb1bca801efa2288858b7a18911...8f744b043a148fa805e27872d4c56dcb2a8675ea

If I revert to the current develop branch, the gear does not disappear until the sync AFTER the sync from the purchase (definitely undesirable).

I haven't yet tracked down which bit of code causes the problem. I might not have a chance to look at this again soon so if anyone else wants to take over, feel free.

**Comment by crookedneighbor** [comment]
I've tracked down the offending change. Going from a regular watch to a watch group is mucking up the auto update: https://github.com/HabitRPG/habitrpg/blame/develop/website/public/js/controllers/tasksCtrl.js#L215-L217

**Comment by Alys** [comment]
Oh, it was the watchGroup! I was playing around with the things being watched in that line, without success. Missed it by that much. :)

**Comment by crookedneighbor** [comment]
@Alys I basically just started reverting each line, one at a time, until it stopped being borked.

When someone is ready to fix this, they should write a test first that exhibits the failure. Then fix it.

**Comment by SabreCat** [comment]
My fault again! :stuck_out_tongue_closed_eyes:

**Comment by crookedneighbor** [comment]
I'm going to try to fix it real quick.
