### ISSUE TITLE
Weekly Progress Report typo?

### ISSUE THREAD

**Issue by KarboniteKream** [HabitRPG/habitica#5745]
I noticed that in the Weekly Progress Report mail I just received, the tip of the week states "You’ll continue to unlock content as you level up - from Pets and Mounts at level 4", but I've had a pet since level 3.

**Comment by SabreCat** [comment]
Ah, yes. The drop system used to start at level 4, but we nudged it back to level 3. Looks like we missed a spot referencing the old unlock point.

**Comment by lemoness** [comment]
Fixing this now!

**Comment by lemoness** [comment]
Fixed :) Thanks so much for reporting!
