### ISSUE TITLE
Problem with quests

### ISSUE THREAD

**Issue by GayTor26** [HabitRPG/habitica#5747]
My friends and I formed a Party and our Party Leader died. She was in the middle of the Basi-List quest. She was the only one participating in the quest.

Now I am the party leader and I can't start a new quest because it says party members are already involved in one. How do I fix this?

**Comment by Alys** [comment]
Please tell us your user ID and the party's group ID. To find out what they
are, go to Help -> Report a Bug and see step 6 of the instructions.

**Comment by GayTor26** [comment]
My user ID is f9d8bf8b-5154-4f3c-a27d-b36af549894c  GayTor26 . Our Party is 1ae0a1fa-40c7-4464-ba01-6fda2b32a149

**Comment by Alys** [comment]
I've removed the quest from your party. Please let us know if you still can't start a new one! Reload the party page if you still see the old quest.

**Comment by GayTor26** [comment]
Thank you. That worked!
