### ISSUE TITLE
Possible number overflow?

### ISSUE THREAD

**Issue by Zwemvest** [HabitRPG/habitica#575]
So, I've been using HabitRPG for a small while now, and ment to use it more/better, explaining my lack of tasks and such, but when I completed a task this morning my exp and coins rolled over into ridiculously large numbers. I don't know if this error is present with other users.
![Bug](https://f.cloud.github.com/assets/2368175/217034/30b9b6c2-84de-11e2-9687-5821a89d3522.png)

**Comment by lefnire** [comment]
#564 - yeah, we think overflow too.

**Comment by Zwemvest** [comment]
Thank you.
