### ISSUE TITLE
Chrome extension messing up

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5751]
Hey!
I have recently started using the Chtome extension again and I have noticed a bug. After finishing an interval, the extensions suddenly labels a "good" website as "bad" and I get damage because of it. When I click on the icon, the menu pops down and doesn't go up on a second click. I have to click somewhere else, then the menu closes and the website is suddenly "good" again.
##

**Comment by Alys** [comment]
@Miisa I'm very sorry we never responded to this! The extension has been updated recently (February 11, 2016) and I haven't seen any other reports of this, so I think it might be fixed. However if it's still happening and you're running the latest version of the extension, please tell us and we'll reopen this.
