### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by nightstitched** [HabitRPG/habitica#5752]
My friend, Winter Rose forgot her password, so she without think hit reset password. The problem is that email address on her account no long exists. Now she has absolutely no idea what the password is, and cannot log into her account.

Is there anyway for her to fix this, or should she just start a new account?

her ID is   dd656c42-c404-43c8-847c-5bfd0c37a66e 
thank you

**Comment by crookedneighbor** [comment]
Please have the user email admin@habitica.com with their user id so we can verify their identity and help them get access.

**Comment by Alys** [comment]
I'm closing this because I'll deal with it from the email, when it arrives.
