### ISSUE TITLE
Challenges filter is forgotten after joining one

### ISSUE THREAD

**Issue by fogbank** [HabitRPG/habitica#5754]
When I filter the challenges in the challenges page (for example by guild) and join one from there, the page is reloaded without the filter.
Leaving a challenge doesn't show this behavior.

Might be an issue, might be intended, I don't know.
##

**Comment by Alys** [comment]
Copied from crookedneighbor's post at https://github.com/HabitRPG/habitrpg/issues/5071 :

When the join button is clicked, the filters appear to reset to "either", but the radio buttons don't revert back to either. Clicking on the desired radio button again, even if it's already selected corrects the behavior. My desired behavior is that it remain filtered.

**Comment by Alys** [comment]
related: https://github.com/HabitRPG/habitrpg/issues/7539 "Challenge filtering reverts after closing challenges"

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Joining challenges does not happen on the same "page", so is this still desired?

**Comment by fogbank** [comment]
No, I don't think it's relevant anymore.
