### ISSUE TITLE
change Fortify Potion's popup text to make it attractive to players with blue Dailies?

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5758]
The Fortify Potion returns all tasks to yellow. It's marketed as being good for players who have too many red tasks. However it could also be used by players whose Dailies are no longer challenging because they are too blue. There's already some information about that on the wiki in [Fortify Potion > When to Use](http://habitica.wikia.com/wiki/Fortify_Potion#When_to_Use), but we could add it to the potion's popup screen as well.

@lemoness would you like the text to be changed? Here's the current version:

"Fortify will return all your tasks to a neutral (yellow) state, as if you'd just added them, and top your Health off to full. Consider this an option of last resort! Red tasks provide good incentive to improve. But if all that red fills you with despair, and the beginning of each new day proves lethal, spend the Gems and catch a reprieve!"

![screen shot 2015-08-09 at 6 53 18 pm](https://cloud.githubusercontent.com/assets/1495809/9154208/eeb05492-3ec7-11e5-920c-1e7fb7b478f0.png)

**Comment by Alys** [comment]
I should have mentioned: This was Velinde's idea.

**Comment by lemoness** [comment]
Very good point. How about this?

"Fortify will return all your tasks to a neutral (yellow) state, as if
you'd just added them, and top your Health off to full. This is great if
all your red tasks are making the game too hard, or all your blue tasks are
making the game too easy. If starting fresh sounds much more motivating,
spend the Gems and catch a reprieve!"

**Comment by Alys** [comment]
Done in https://github.com/HabitRPG/habitrpg/commit/665c32ee540ef4579b7bd4930fbeec15469f8664
