### ISSUE TITLE
The name Habitica may look/sound very odd in some languages (reopened for RTL languages)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5760]
Originally raised in discussion in the [Commonwealth of i18n guild](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) (by Mikoto Yato) the following questions may become more important after HabitRPG-Habitica rebranding:
- the word Habitica may look/sound really odd and unnatural in some languages, e.g. silent 'H' or 'c' sounding like [s],[ts],etc. or odd syllable stressed. An example for Czech: please follow http://www.speechtech.cz/cs/produkty/synteza-reci/demo.html#Iva210 , type Habitica in and press Syntetizovat
- words in a sentence containing `Habitica` may need to reflect it's gender which may be different if the word means a country/land, a city, a game or a program (etc.)

Reportedly, the question has been raised long ago and got no official answer.
As of now, the guidelines on [Trello](https://trello.com/c/SvTsLdRF/12-translations) clearly state that translators should

> keep the names "HabitRPG" and "Habitica" untranslated (as is).

However, I believe translators may appreciate some additional guidelines and help on this. Could the staff please consider possible suggestions:
- having the front static/page clearly explaining the origin of the name. e.g. Habitica is the land/city/etc. for people willing to replace bad habits with good ones - and habit is the English for [habit] OR _maybe_ English is the very first native language of Habiticans(?) and they have called their land/city/etc. Habitica (IDK really =)
- deciding on what Habitica is by default: a land/city/program/etc. (by default means the string doesn't have anything like "the country of H." or "the mountain H." or the "capital of H."
- _maybe_ consulting with lawyers/native speakers/translators about the possibilities of altering the brand for some overseas markets that (may potentially) give a reasonable number of paying users
- other suggestions from other translators?

Linking https://github.com/HabitRPG/habitrpg/issues/5703 [List of strings with Habitica in them - for translations](https://github.com/HabitRPG/habitrpg/issues/5703) just in case

**Comment by ghost** [comment]
A note from Mikoto Yato regarding possible Habitica-Habitika shift in Czech:

> One thing that I remember. I actually talked about the c/k change with my professor at uni and he told me that it is tricky, but sometimes it is necessary for the language to do such a change. As an example he talked about the Harry Potter series in which all the surenames were translated into Czech, so they would sound witty to even small readers who don't have any idea about other languages and they can still enjoy the meaning in them

**Comment by lynxlynxlynx** [comment]
HabitRPG was unmistakibly a name, a foreign name. Habitica will sound normal in most Slavic languages and at many times it is really hard to keep it undeclinated, additionally so as the same word is used for the land. It just looks and reads wrong, so I'll be breaking the general rule where the end result will be better.

**Comment by ghost** [comment]
Mikoto Yato here! 
Just to more closely introduce the issue - it is a minor issue with how the users perceive the name Habitica phonetically. Since the name is only in its written form, the users can interpret the name in their minds based on the phonetic system of their native language. As I tried to demonstrate with the example with the Czech synthetized pronunciation, which is far from the English one. We must consider some factors:
- how natural or unatural would Habitica, in its unaltered state, look in the sea of translated text and how much it would affect the user's experience
- how big a change would the name undergo for different languages to maintain the same pronunciation with the price of alternative spelling and if it even worth it
- is it a registered trademark, in which case it should not be altered and possible incorrect user interpretation and pronunciation would be tolerated or not cared about

Regarding adding land/city/etc. before the name - that would be very handy for languages that treat the name Habitica as a proper noun and as such, they have to decline it depending on the case it occurs in. It would take focus from 'Habitica' and shift it to the word preceding it, which then would be declined and the word 'Habitica' would remain untouched in majority of cases (I can think of some Czech cases, that would require declination of Habitica as well, but it could be left as it is and it would be rather informal in result).

**Comment by crookedneighbor** [comment]
Pinging @lemoness

**Comment by lynxlynxlynx** [comment]
Prepending app/service and land/w.e. would indeed work for most cases. Where there are spatial constraints (if any), it would surely be clear it is about the app and there'd be no need for explicit disambiguation via prefix.

**Comment by lemoness** [comment]
I'm going to talk this over with the rest of the staff to see if we can
come to a consensus. It's very interesting! We probably want to keep the
name "Habitica" the same if we can, though, for search engine optimization.

**Comment by lemoness** [comment]
So, we definitely want to keep the name "Habitica" the same regardless of
the localization. Although it may sound odd, if we change the spelling
we'll be opening ourselves up to a host of problems that we would rather
avoid!

As for the gender, default to having Habitica be a program, unless it is
very clear that it's a land, for example in quests. For the latter, it's
okay if translators add things to the string like "the land of Habitica" in
the translation to make it more obvious why the gender changed.

I hope this helps! Let me know if you have more questions.

**Comment by ghost** [comment]
Great to have things cleared up! :) I have one question, if I may. A natural descriptive element (land, web app) introducing a foreign element (Habitica) would not only shift the focus of concord, but it is also a very common translation technique of introducing new words in specialized contexts. Introducing it for every instance of Habitica would make it not only distinguishable, but also easier for the user to accept. With "the land of Habitica" it is clear, but what about other instances, what would be better to use there? The program Habitica or maybe the web app Habitica?

**Comment by lemoness** [comment]
The "program"! Since we are a site and an app, it's better to be more
general.

**Comment by ghost** [comment]
Thank you! It's better to have it written out and confirmed like this than to assume. Saves a lot of trouble (especially with clients when translating for living) :)

**Comment by ghost** [comment]
@lemoness thank you for your comments!

**Comment by eburcat** [comment]
@lemoness Sorry to bring it up again just now. While in other languages using Habitica may be a minor issue - in RTL languages, unfortunately - it's a major translation issue, as it might be evident here: https://github.com/HabitRPG/habitrpg/issues/3465 . leaving Habitica as an English text in the Hebrew translation - completely messes up a lot of the texts (same happens to user names in the quests, by the way...).
Since fixing the code will probably take a lot of time, a Great workaround for Hebrew would be to translate Habitica to Hebrew - and keep whole sentence RTL. I understand there may be SEO implications - I think they are minor compared to problems reading the site in Hebrew. I also understand there may be a legal problems(?) (copyright? trademark?) - maybe we can gather money in order to trademark the Hebrew translation of Habitica in Israel?

**Comment by Alys** [comment]
@eburcat   This could be a completely ignorant question, and if so, I am sorry, but is the problem that the letters in "Habitica" untranslated read left-to-right while all the other words read right-to-left? If so, would "translating" it as "acitibaH" help?

@veeeeeee If that did help, would it be acceptable from a trademark point of view?

**Comment by eburcat** [comment]
@Alys unfortunately this won't help... Mixing a single non-rtl letter in an RTL text can mess up the alignment if the html element is not marked as containing a right-to-left text. And since Habitica is made up of TONS of different HTML elements - finding the right places to add the HTML notation for RTL languages is a complicated task.

**Comment by paglias** [comment]
This has been addressed in a recent discussion in the Commonwealth of i18n guild so I'm closing it
