### ISSUE TITLE
Malformed Translation String Variables

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#5761]
This issue is intended for language reviewers and admins on Transifex. @GitHubSphinx will probably be interested in this. 

The following strings are either missing variables or are incorrectly formatted. For instance, in the first string below, the variable should be `<%= surveys %>`, but it is rendered as `<%= surveys%>`. The missing space between the `s` and `%>` at the end of the word causes the translation to break (the error processing string message). 

When you have fixed the string on transifex either comment here or in [the Commonwealth of i18n guild](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7)
## Czech
- [x] cs - contrib.json - surveysMultiple - Pomohl Habitice růst vyplněním <%= surveys%> dotazníků. Nejsou žádné aktivní dotazníky. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#cs/contribjson)
- [x] cs - gear.json - weaponSpecialCandycaneNotes - Mocná kouzelnická hůl. Silně VYNIKAJÍCÍ, máme na mysli! Zbraň pro obě ruce. Zvyšuje Inteligenci o <%= int%> a Vnímání o <%= per%>. Limitovaná edice Zimního vybavení 2013-2014!
- [x] cs - settings.json - correctlyUnsubscribedEmailType - Správně odhlášen z "<%= email Type %>" emailů. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#cs/settings) 
## Danish
- [x] da - gear.json - armorSpecialSummer2015HealerNotes - Denne rustning lader enhver vide at du er en ærlig købmandssejler, som aldrig ville opføre sig som en landkrabbe. Øger Konstitution med <%= con >. Specielt 2015 Forårsudstyr. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#da/gear) 
- [x] da - settings.json - subscriptionRateText - Løbende $<%= price %> hver <%= months%>. måned [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#da/settings) 
- [x] da - tasks.json - habitHelp1 - Gode Vaner er noget du ofte gør. De giver Guld og Erfaring hver gang du klikker på <%= plusIcon%> [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#da/tasks) 
- [x] da - tasks.json - habitHelp2 - Dårlige Vaner er noget du gerne vil undgå at gøre. De fjerner Helbred hver gang du klikker på <%= minusIcon%> [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#da/tasks) 
## German
- [x] de - gear.json - weaponWarrior2Notes - Zweischneidige Stretaxt. Erhöht Stärke um 6. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#de/gear) 
- [x] de - gear.json - weaponArmoireRancherLassoNotes - Lassos: das ideale Werkzeug zum Einfangen und Zäumen. Erhöht die Stärke um <% = str %>, Wahrnehmung um<% = pro %> und Intelligenz um <% = int %>. Verzauberter Schrank: Viehzüchter Set (Artikel 3 von 3). [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#de/gear) 
- [x] de - gear.json - armorSpecialFinnedOceanicArmorNotes - Obwohl empfindlich, macht diese Rüstung Deine Haut bei Berührung so gefährlich wie Feuerkorallen. Erhöht die Stärke um <% = str%>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#de/gear) 
## Spanish
- [x] es - gear.json - weaponSpecialYetiNotes - Esta lanza permite que el usuario comande a cualquier yeti. Incrementa Fuerza en <%=str%>. Edición Limitada Equipo de Invierno de 2013-2014 [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - gear.json - headHealer1Notes - Casco enjoyado, para enfocarse en la tarea en mano. Aumenta Inteligencia por <% = int%>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - gear.json - shieldSpecialGoldenknightNotes - ¡Encuentros, monstruos, malestar: superados! ¡Machacados! Aumenta la Constitución y la Percepción en <%=attrs%>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - gear.json - shieldSpecialFallWarriorNotes - Se vierte misteriosamente sobre las batas de laboratorio. Aumenta la Constitución en <%=con%>. Equipo de Otoño Edición Limitada 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - gear.json - shieldSpecialWinter2015WarriorNotes - Este escudo aparentemente azucarado se hace en realidad con vegetales nutritivos y gelatinosos. Aumenta la Constitución en <% = con%>. Equipo de Invierno 2014-2015 Edición Limitada [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - gear.json - shieldSpecialWinter2015HealerNotes - Este escudo desvía el viento helado. Aumenta la Constitución en <% = con%>. Equipo de Invierno 2014-2015 Edición Limitada. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - gear.json - shieldSpecialSpring2015HealerNotes - Puedes descansar la cabeza en esta almohada suave, o puedes luchar contra ella con tus temibles garras. ¡Rawr! Aumenta la Constitución en <% = con%>. Equipo de Primavera 2015 Edición Limitada. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/gear) 
- [x] es - generic.json - buyThis - Comprarás este <%=text%> con <%=price %> de tus <% gems%> Gemas? [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/generic) 
- [x] es - limited.json - agriculturalFriendsText - Tus compañeros te han transformado en flor <%=seeds%> veces. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es/limited) 
## Spanish (Latin America)
- [x] es_419 - gear.json - armorWizard1Notes - Traje protector de mago. Incrementa la Inteligencia por <%=int %> [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es_419/gear) 
- [x] es_419 - generic.json - buyThis - ¿Comprarás este <%=text%> con <%=price %> de tus <% gems%> Gemas? [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es_419/generic) 
- [x] es_419 - limited.json - seasonalShopTitle - Hechicera estacional [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#es_419/limited) 
## French
- [x] fr - character.json - youCastParty - Vous avez lancé <%= spell%> pour l'équipe. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/character) 
- [x] fr - gear.json - weaponRogue1Notes - Une lame légère, facile à cacher. Augmente la Force de <%=str %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponRogue2Notes - Une épée tranchante, prompte à délivrer un coup mortel. Augmente la Force de <%=str %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponRogue3Notes - Le couteau distinctif du guérillero, à la fois arme et outil de survie. Augmente la Force de <%=str %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponRogue4Notes - De lourds bâtons qui tournoient, reliés par une chaîne. Augmente la Force de <%=str %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponRogue5Notes - Aussi fine et mortelle que les ninja eux-mêmes. Augmente la Force de <%=str %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponRogue6Notes - Une arme complexe, apte à prendre les opposants au piège pour les désarmer. Augmente la Force de <%=str %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponHealer1Notes - Conçue pendant l'initiation d'un guérisseur. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponHealer2Notes - Surmonté par une gemme aux propriétés curatives. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponHealer3Notes - Élimine le poison par simple contact. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponHealer4Notes - La marque d'une fonction aussi bien qu'un outil de guérison. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponHealer5Notes - Prévu pour orner la main d'un monarque ou celle de celui qui se tient à sa droite. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponHealer6Notes - Soulage la douleur de tous ceux qui y portent le regard. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponSpecialSpringHealerNotes - VA CHERCHER ! Augmente l'Intelligence de <%=int %> points. Équipement en Édition Limitée du Printemps 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponWizard1Notes - Un simple outil en bois taillé. Augmente l'Intelligence de <%=int %> points et la Perception de <%= per %>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponWizard2Notes - Concentre le pouvoir dans une pierre précieuse. Augmente l'Intelligence de <%=int %> points et la Perception de <%= per %> . [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponWizard3Notes - Recouvert de métal pour conduire la chaleur, le froid et la foudre. Augmente l'Intelligence de <%=int %> points et la Perception de <%= per %>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponWizard4Notes - Aussi puissant qu'il est lourd. Augmente l'Intelligence de <%=int %> points et la Perception de <%= per %>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponWizard5Notes - Aide à jeter les sorts les plus compliqués. Augmente l'Intelligence de <%=int %> points et la Perception de <%= per %>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - weaponWizard6Notes - Moulé à partir d'orichalque, l'or alchimique, puissant et rare. Augmente l'Intelligence de <%=int %> points et la Perception de <%= per %>. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headArmoireRedHairbowNotes - Devenez fort, tenace et brillant en portant ce magnifique Nœud Rouge!  Augmente la Force de <%= str%> points, la Constitution de <%= con %> points et l'Intelligence de <%= int %> points. Armoire Enchantée: Objet Indépendant. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - armorWizard1Notes - La tenue du mage de protection. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear)
- [x] fr - gear.json - armorWizard2Notes - La tenue d'un faiseur de prodiges ambulant. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - armorWizard3Notes - La marque de l'initiation aux secrets de l'élite. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - armorWizard4Notes - Les esprits et les élémentaires s'inclinent devant elle. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - armorWizard5Notes - Symbole du pouvoir derrière le trône. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - armorSpecialSpringMageNotes - Les souris vous sourient ! Augmente l'Intelligence de <%=int %> points.. Équipement en Édition Limitée du Printemps 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headHealer1Notes - Couvre-chef orné de joyaux, pour rester concentré sur la tâche à venir. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headHealer2Notes - Des goûts de luxe pour une profession modeste. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headHealer3Notes - Brille pour montrer à ceux qui souffrent que le salut est à portée de main. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headHealer4Notes - Émet une aura de vie et de croissance. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headHealer5Notes - Pour un roi, une reine, ou un faiseur de miracles. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headSpecial0Notes - Le sang et la cendre, la lave et l'obsidienne donnent à ce heaume sa prestance et son pouvoir. Augmente l'Intelligence de <%=int %> points. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headSpecialSnowflakeNotes - Le porteur de cette couronne n'a jamais froid. Augmente l'Intelligence de <%=int %> points. Équipement en Édition Limitée de l'Hiver 2013-2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headSpecialSpringHealerNotes - Cette couronne symbolise la loyauté et la dévotion envers ses compagnons. Le chien est le meilleur ami de l'aventurier, après tout ! Augmente l'Intelligence de <%=int %> points. Équipement en Édition Limitée du Printemps 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - gear.json - headSpecialSpring2015HealerNotes - La perle au centre de cette couronne calme et conforte les personnes qui l'entourent. Augmente l'Intelligence de <%=int %> points. Équipement en Édition Limitée du Printemps 2015. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gear) 
- [x] fr - generic.json - habiticaDayPluralText - Fêté <%=number %> Jours d'Appellation! Merci à vous pour être un utilisateur fantastique. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/generic) 
- [x] fr - limited.json - annoyingFriendsText - Votre équipe vous a lancé <%=snowballs %> boules de neige. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/limited) 
- [x] fr - pets.json - egg - Œuf de <%= eggType%> [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/pets) 
- [x] fr - pets.json - petKeyBegin - Clé du Chenil : Expérimentez à nouveau le frisson du Maître des Bêtes ! [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#fr/pets) 
## Hebrew
- [x] he - subscriber.json - timeTravelersTitleNoSub - <%= linkStartTyler %>טיילר<% linkEnd %> ו<%= linkStartVicky %>ויקי<%= linkEnd%> [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#he/subscriber) 
## Italian
- [x] it - gear.json - weaponSpecialFallWarriorNotes - Questi artigli acchiappa-tutto sono l'avanguardia della tecnologia. Aumenta la Forza di <%=str %>. Edizione limitata, autunno 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#it/gear) 
- [x] it - gear.json - armorSpecialFallRogueNotes - Vivido. Vellutato. Vampirico. Aumenta la Percezione di <%=per %>. Edizione limitata, autunno 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#it/gear) 
- [x] it - gear.json - armorSpecialFallMageNotes - Questa veste ha tasche in abbondanza per contenere porzioni extra di occhio di tritone e lingua di rana. Aumenta l'Intelligenza di <%=int%>. Edizione limitata, autunno 2014. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#it/gear) 
- [x] it - quests.json - mustLevel - Devi essere di livello <% = livello%> per iniziare questa missione. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#it/quests) 
## Dutch
- [x] nl - groups.json - invitedTo - Uitgenodigd voor <%= name%> [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#nl/groups) 
## Polish
- [x] pl - contrib.json - surveysMultiple - Pomógł rozwinąć Habitica poprzez wypełnienie <%=surveys %> ankiet. Brak aktywnych ankiet. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pl/contrib) 
- [x] pl - gear.json - weaponSpecialWinter2015RogueNotes - Z całą pewnością, zdecydowanie, najzwyczajniej podniosłeś go po prostu z ziemi. Edycja Limitowana Zima 2014-2015. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pl/gear) 
- [x] pl - gear.json - shieldSpecialWinter2015RogueNotes - Z całą pewnością, zdecydowanie, najzwyczajniej podniosłeś go po prostu z ziemi. Edycja Limitowana Zimowego Wyposażenia 2014-2015. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pl/gear) 
- [x] pl - settings.json - correctlyUnsubscribedEmailType - Poprawnie zrezygnowano z subskrypcji e-maili "<%=emailType %>". [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pl/settings) 
## Portuguese
- [x] pt - character.json - haveUnallocated - Você tem <%=points%> Ponto(s) de Atributo não usados [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pt/character) 
- [x] pt - gear.json - armorSpecialSummer2015WarriorNotes - Esta peça de vestuário de escamas cintilantes transforma quem usa em um Guerreiro Peixe-sol de verdade! Aumenta a Constituição em <%= con%>. Edição Limitada Conjunto de Verão 2015. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pt/gear) 
- [x] pt - pets.json - triadBingoText2 - e libertou um estábulo cheio um total de <%= count%> vezes [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#pt/pets) 
## Russian
- [x] ru - gear.json - weaponSpecialTridentOfCrashingTidesNotes - Дает вам способность повелевать рыбами, а также [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#ru/gear) 
- [x] ru - gear.json - weaponSpecialSummer2015WarriorNotes - Солнечная Меч-Рыба это оружие, наводящее ужас, только если не давать рыбе трепыхаться. Увеличивает Силу на <% = str %>. Экипировка ограниченного выпуска лета 2015. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#ru/gear) 
- [x] ru - gear.json - weaponSpecialTridentOfCrashingTidesNotes - Дает вам способность повелевать рыбами, а также [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#ru/gear) 
- [x] ru - gear.json - weaponSpecialSumtaka. [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#ru/gear) 
- [x] ru - limited.json - seasonalShopClosedTitle - Сиена Лезли [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#ru/limited) 
## Slovak
- [x] sk - tasks.json - streakText - Má na konte 21-dňové série na denných úlohát%> vezes [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#sk/tasks) 
## Serbian
- [x] sr - pets.json - petKeyBegin - Ključ štenare: Postanite ponovo Krotitelj zveri! [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#sr/pets) 
## Swedish
- [x] sv - challenge.json - prizeValue - Pris [transifex link](https://www.transifex.com/habitrpg/habitrpg/translate/#sv/challenge) 
##

**Comment by ghost** [comment]
Czech is fixed :)

**Comment by crookedneighbor** [comment]
@Miisa Thanks so much!

**Comment by ghost** [comment]
No prob, I am in the middle of 'The assimilation of voice, manner and place in English and in Czech. Connected speech phenomena (liaison, linking and intrusive r, glottal stop, yod coalescence)' question anyway, it is 12:47pm, so this was a nice bit of relax :D

**Comment by MarchRPG** [comment]
Dutch is also fixed!

**Comment by ghost** [comment]
@crookedneighbor
Could you please give me a hint what `ru - gear.json - weaponSpecialSumtaka.` is? I can't find an error in any of the `weaponSpecialSum*` strings.

WIP:
- [x] Danish
- [x] German
- [x] Spanish
- [x] Spanish (Latin America)
- [x] French
- [x] Hebrew
- [x] Italian
- [x] Polish
- [x] Portuguese
- [x] Russian
- [x] Slovak
- [x] Serbian
- [x] Swedish

**Comment by ghost** [comment]
@crookedneighbor All seems fixed to me, except for one mysterious string in Russian (`weaponSpecialSumtaka`). Unfortunately, Transifex batch find-and-replace doesn't work as expected for variables - so it's been a manual work and I could have missed something out with all those %). May I ask you to rerun the script when you have time to.

**Comment by gitte-k** [comment]
Danish fixed and reviewed (thanks @GitHubSphinx )

**Comment by crookedneighbor** [comment]
@GitHubSphinx I think that one mysterious string was just a typo on my part. Great job with all that work!

Here are the remaining strings with issues:
- [x] fr - gear.json - weaponSpecialSummerMageNotes - Ce trident est utilisé pour harponner les algues avec efficacité, idéal pour les récoltes de varech extra-productives ! Augmente l'Intelligence de <%= int %> points. Équipement en Édition Limitée de l’Été 2014.

Missing `per` variable : https://www.transifex.com/habitrpg/habitrpg/translate/#fr/gearjson/26903937?key=weaponSpecialSummerMageNotes
- [x] he - generic.json - buyThis - לרכוש את <%= text %> באמצעות <%= price %> מאבני החן שלך?

Missing `gems` variable: https://www.transifex.com/habitrpg/habitrpg/translate/#he/genericjson/21450525?key=buyThis
- [x] hu - rebirth.json - rebirthAchievement - Új kalandot kezdtél! Ez a(z) <%= number %>. Újjászületésed. Ahhoz, hogy halmozd ezt a Kitűntetést kezdj új kalandot, amikor elértél egy mégmagasabb Szintet!

Missing `level` variable: https://www.transifex.com/habitrpg/habitrpg/translate/#hu/rebirthjson?key=rebirthAchievement
- [x] zh - limited.json - valentine1 - "玫瑰红艳<%= lineBreak %>紫罗兰也开的绚烂<%= lineBreak %>让我们一起<%= lineBreak %>与邪恶抗争!"<%= lineBreak %>PS：邪恶/恶习 紫罗兰花语：永恒的美与爱，我很喜欢你

Has 3 line breaks instead of 2: https://www.transifex.com/habitrpg/habitrpg/translate/#zh/limitedjson/40621646?key=valentine1

**Comment by ghost** [comment]
Done:
- [x] French

and I'll ask for help with the other ones

**Comment by ghost** [comment]
@crookedneighbor may we go on with Chinese poem? I believe it's meant to be that way and I don't think extra linebreak will cause errors

**_UPD**_
And thank you for your help with the line in Hebrew - please excuse me I haven't made sure how the variables are rendered in RTL languages =(

**Comment by crookedneighbor** [comment]
I agree with you regarding the poem, but it doesn't make sense to me to code in a special exception for that one string. Instead, the format off that particular string should probably be changed to be markdown so that translators can translate it however they want, without having to worry about a variable. 

I've done that, so the string will need to be retranslated, but the translators won't have to worry about the line break.

**Comment by ghost** [comment]
@crookedneighbor Please excuse me, I've lost track of your work on auto-check feature for "Error processing a string". Is it working?

Could you please look at
 Ru - jear.json headArmoireHornedIronHelmNotes https://www.transifex.com/habitrpg/habitrpg/translate/#ru/gearjson/53855957 the history in short:

> `<%= cob %> <%= str >`
> by Jazzis18, 2 months ago

i.e. error in **_cob**_ instead of **_con**_ 

> `<%= cob %> <%= str %&gt;`
> by crookedneighbor, 2 months ago

trying to fix?

> `<%= con %> <%= str %>`
> by grammarware, 14 days ago

fixed manually

Has some exception of an auto-check occurred?

**Comment by librarianmage** [comment]
@crookedneighbor is this done?

**Comment by ghost** [comment]
From what I remember, all the issues mentioned in the ticket are fixed
