### ISSUE TITLE
Death Warning Modal

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5763]
@Alys had a very good idea in the wake of the discovery that death was driving away a huge number of users: warning new users the first time their health drops to 30 or so. The goal is to educate new users about how to heal and how to make sure that their initial tasks are not too ambitious. We can experiment with showing the modal at different HP levels once it's in the game to see if it's more effective.

Here's the suggested text for the one-time popup modal, which should probably be similar to the Death Modal for consistency:

"Careful - You're Losing Health!

Level up to be fully healed, or buy a healing potion from the Rewards column to heal 25 HP. Don't let your health drop to zero! If you do, you'll lose a level, your gold, and a piece of equipment.

Losing health quickly? Reassess your Habits and Dailies to make sure that you're starting slowly and building up tasks over time. Incomplete Dailies hurt you overnight, so be careful not to have too many at first! If a Daily isn't due on a certain day, you can disable it by clicking the pencil icon.

 Good luck!"

**Comment by granthusbands** [comment]
I think it might also be good to stop reducing the health of relatively new users who aren't active. Or keep them on the brink of death until they return and hopefully do something about it. You'd only need to do it once, hopefully.

I'm one of those who was driven away by death, months ago, in that my character died fairly quickly and I haven't yet started again for fear of again killing it. A warning wouldn't have affected my behaviour, I think. I'm only one user, though.

**Comment by SabreCat** [comment]
@granthusbands: I believe that first concern has already been addressed--you only lose Health for one day's worth of missed Dailies if you return after a long hiatus.

**Comment by granthusbands** [comment]
Ah, thank you; that's fantastic news.

**Comment by Alys** [comment]
I believe this has been done. Reopen if I'm wrong.
