### ISSUE TITLE
subscription information mentions ads

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5765]
@lemoness When you hover over the subscription button, the text talks about disabling ads:

**"Disable ads, buy gems with gold, monthly mystery item, retain progress history, double daily drop-caps, supports the devs. Click for more info."**

Would you like this to be changed?

![screen shot 2015-08-11 at 4 46 48 am](https://cloud.githubusercontent.com/assets/1495809/9197312/76790aae-4076-11e5-81cc-930fb036ab56.png)

Note to devs: If we change this, we could delete these unused strings at the same time:

```
common/locales/en/subscriber.json:5:    "disableAds": "Disable ads",
common/locales/en/subscriber.json:6:    "disableAdsText": "Ads are disabled while you have an active subscription (original donors are grandfathered).",
common/locales/en/contrib.json:56:      "removeAds": "Subscribe to remove ads",
```

**Comment by ghost** [comment]
for what it's worth, other strings that may need changes if no-ads policy is applied:
- subscriber.json `subDescription` Disable ads, buy gems with gold, monthly mystery item, retain progress history, double daily drop-caps, supports the devs. Click for more info. [**_in use**_]
- subscriber.json `gameNoAds` Ads disabled for members [not in use]
- subscriber.json `buySubsText` Buy gems with Gold, No Ads, Support the Devs [not in use]
- contrib.json `hideAds` Hide Ads [not in use]
- contrib.json `whyAds` Why Ads? [not in use]

**Comment by lemoness** [comment]
Yes, references to ads and ads disabling should be removed.
