### ISSUE TITLE
Un-earned pets / mounts

### ISSUE THREAD

**Issue by stretchyudon** [HabitRPG/habitica#5766]
Hello,

I somehow have a Veteran Wolf pet, an Orca mount, and a Royal Purple Gryphon mount. I have not made any contributions to the site yet, so I'm not sure how / why I should have earned these. If it was in error, is there someway I can have them removed? I feel odd having something I did not earn.

I'm running on Chrome and using the Apple app.

User ID: 6771b630-288d-48d6-aee5-3e3d0183aa94

Thank you,
Stretchy Udon

**Comment by gbear605** [comment]
The Orca mount was "Given to players who joined Habitica before Derby Day 2015." (Wiki). The Veteran Wolf pet and the Royal Purple Gryphon mount were given to anyone who joined Habitica before naming day, which was a few days ago. You receiving them was not in error (unless you joined more recently than those days).

**Comment by stretchyudon** [comment]
Thank you so much for clearing these things up for me! Sorry for wasting
your time. (I did join before these events but wasn't actively using the
app back then).

Thanks again,
-Stretchy
