### ISSUE TITLE
Habit +/- options are highlighting weirdly

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5767]
In both Chrome and Firefox on Win 7. 
Selecting a +/- button throws a highlight around the entire outside of it, regardless of whether it's being switched on or off. on/off are shown with the box being darkened. The usual shadow effect around the "on" boxes is still present, but it isn't revealed unless you click something else. 

Difficulty, daily day-selection etc seem normal. 

---

Possibly overkill screenshot section!

New Habit starts like this -- 
![1](https://cloud.githubusercontent.com/assets/9494342/9211694/64982e96-4049-11e5-92a8-6e8e69f3365b.png)

Clicked on + 
![2](https://cloud.githubusercontent.com/assets/9494342/9211717/8a49ea62-4049-11e5-9ed2-5e7fa8d128b6.png)

clicked on -   (so now they are both inactive)
![3](https://cloud.githubusercontent.com/assets/9494342/9211741/b00af412-4049-11e5-8874-3f1a13a52ccd.png)
- again
  ![4](https://cloud.githubusercontent.com/assets/9494342/9211761/ca36d144-4049-11e5-9428-13eed4215832.png)
- again (both reactivated)
  ![5](https://cloud.githubusercontent.com/assets/9494342/9211782/e948ff30-4049-11e5-821a-5866348eb7d3.png)

**Comment by crookedneighbor** [comment]
Thanks for reporting it. This was an unintended side effect of making the input buttons for the tasks more keyboard accessible. Fixed now.
