### ISSUE TITLE
Dailies Overload Warning

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5768]
Right now, a common problem is that new users overload themselves on Dailies without fully understanding the ramifications, and then get discouraged by frequent deaths. We'd like to have a non-obtrusive, easily dismissible warning when a new user is adding too many Dailies at once to remind them that they will be damaged by incomplete Dailies and that it is better to start small. This should NOT be a popup that will interrupt their user experience or prevent them from adding more Dailies. Rather, it should probably be a message above the Dailies, like the inn message. It should be easy to remove.

We can discuss what would best trigger it. Maybe adding 5 or more Dailies within your first week?

Suggested text (improvements welcome):

"Be careful when adding Dailies! Incomplete Dailies will damage you overnight. We recommend starting slowly, and then gradually adding more tasks over time."
##

**Comment by crookedneighbor** [comment]
I wouldn't put a limit on the time. A user could start an account, not use it for a while, and then come back to it. They would still benefit from the warning.

**Comment by Alys** [comment]
That's definitely true - I see a lot of new players who signed up a long
time ago. Without a time limit though, we could run into the situation
where a person adds a Daily once a week, and then on their fifth week we
tell them they're going too fast. I'm not sure if there's a good way to
handle both situations. We could use the task creation dates to work out if
they've been added rapidly, but that's extra overhead.

**Comment by lemoness** [comment]
Hm, good point. Maybe we could have two different use cases that trigger
it, one if you add tasks in your first week, and one if you add many tasks
all at once. That seems like a lot of extra work, however.

I'm more concerned about the first week, because analytics show that most
users don't even make it to the end of the week.

**Comment by crookedneighbor** [comment]
@lemoness Do those analytics show how many dailies those users have by the end of the week?

**Comment by lemoness** [comment]
Good question! I don't think so, but I can try to investigate.

**Comment by deilann** [comment]
If the reminder is easy to dismiss, why not just have it for all new users?

**Comment by crookedneighbor** [comment]
I agree with that. No need to make it unnecessarily complicated.

**Comment by Alys** [comment]
I think new users would be likely to dismiss it immediately and then forget the information when they need it a day or two later. However you're right that it would be easier. Perhaps we could create it like that initially and then change it if it looks like we need to - if the analytics will give us information about that?

**Comment by deilann** [comment]
If it's triggered when there are five dailies no matter what for any new
user (or we could do it for old users with less than five dailies) rather
than immediately, it's less likely to be dismissed, but requires less
fiddly logic.

**Comment by SleepieBear** [comment]
As a new user myself, it might be helpful if the text stayed above your dailies until you were say... level 3 and then dismissed automatically.  I'm not sure if that would be difficult to do, but the information would stay if a user quit early and then came back and after level 3 (or 5) people generally know if they want to continue using the program.

**Comment by lemoness** [comment]
This is no longer a feature that we're actively pursuing, so I'm closing this for now.
