### ISSUE TITLE
Habitica Refresh Issues

### ISSUE THREAD

**Issue by hepedoto** [HabitRPG/habitica#5769]
It started yesterday.  I logged on to Habitica after a day and a half away (I'd logged into the Tavern to avoid damaging my party) to find I had died.  I tried to comment to apologize to the massive damage I'd done my party to find that I could type out the message but it wouldn't send. 

I tried to fix character values, but after I refresh my gold goes back to zero and my level goes back down.  I can't log into the Tavern, or rather, I can but when I hit refresh I'm out again (which is what must have happened while I was gone). I can't check off tasks, because when I hit refresh it erases my progress.

I'm on Google Chrome.  My ID is: 02e3b882-e6da-4e2a-b143-7aa4f2489a6d
I tried on Firefox, too, but got the same issues.

**Comment by Alys** [comment]
@hepedoto I can't see anything wrong in your account that might be causing this. This sort of thing is usually a browser error, but it's concerning that it's happening in two browsers. Are you able to test in a browser on a different PC or on a mobile device? The website works on most tablets and phones.

**Comment by hepedoto** [comment]
@Alys I got it working.  I cleared my cache on Chrome and it solved the problem.  Not sure why it didn't work in Firefox, but I'm not looking a gift horse in the mouth. I have an iPad but it's too old to support the Habitica app.

**Comment by Alys** [comment]
Thanks for letting us know! Perhaps it was just a coincidence that both browsers had the same glitch.
