### ISSUE TITLE
Several issues on staging server

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#577]
1. Anything I click is shown twice in the notification pane. (Only affects values once.)
2. Some todos still give this EXTREME exp and gp reward. After which I always level whenever I do something. So far I have only seen it for old rewards. 
3. Notifications sometimes appear very very slowly, meaning they are pretty much delayed. 

What does work: 
- Sorting works again.
- The priority multiplier seems to work.

**Comment by lefnire** [comment]
1) Fix coming in next push, check staging again in 5m
2) #564 - a critical bug @MrConcept and I are looking into
3) Still diagnosing that one as well, but TMK that's an issue on live site too?

**Comment by Pandoro** [comment]
@3 Yes, possibly, not sure, somehow when turbo clicking stuff on the staging server it freezes my browser. 

I just wanted to get it in here as to keep a list of what is going on, on the staging server.

**Comment by wildcate** [comment]
I could re-order all tasks except the custom rewards, but they got mixed up/shuffled after I re-ordered. And when I logged out and back in on the normal habit, all the re-ordering was undone and it's back to the old sequence.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Also notice that re-ordering tasks and notifications are still to be ported in the next days so that's why they are missing.
