### ISSUE TITLE
"undefinedBuy this quest with x of your y Gems?"

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#5770]
_"undefinedBuy this quest with x of your y Gems?"_

is the message I get when I buy a quest scroll.

Everything works as it should. The only bug about this is that there's the word "undefined" at the start of the message. I've tried this in different browsers, it's the same.

**Comment by Alys** [comment]
Confirmed using the default English setting, so this isn't a translation issue.

**Comment by Alys** [comment]
Bug found, I believe. Fixing and testing.

**Comment by Alys** [comment]
Thanks @habitrpguser! The fix for this should go live within a few days.
