### ISSUE TITLE
iOS mobile app on iPad is small/iPhone version

### ISSUE THREAD

**Issue by mxrowanthomas** [HabitRPG/habitica#5778]
Just updated to using the Habitica app when prompted (since it doesn't come up on the Appstore search) and it seems to have confused my tablet with a mobile see:
![photo 13-08-2015 15 55 49](https://cloud.githubusercontent.com/assets/116831/9253069/d72e8ca8-41d3-11e5-8f3b-82b6f4a915a6.png)
Apologies if this is a duplicate bug.

**Comment by Alys** [comment]
Issues with the mobile app, or feature requests, are best reported from within the app using the Menu > About > Request a Feature / Report a Bug options. That will send your report to the mobile developers with some automatically generated information that helps the developers do troubleshooting.

However in this particular case, there's no need to report it. We're aware that the app is functional but not as attractive as it could be on larger mobile devices and we are intending to change that. Our focus so far has been on getting the most important functions running on all devices, but I believe that changes to more cosmetic issues are coming soon.
