### ISSUE TITLE
When I login with facebook, it still says HabitRPG in emails from facebook

### ISSUE THREAD

**Issue by bean5** [HabitRPG/habitica#5779]
To quote the facebook email:

Your account was recently logged into from a new browser or device. Was this you?
....
HabitRPG

**Comment by Alys** [comment]
We've been delaying the final change from habitrpg.com to habitica.com until we are certain that nothing will break, including widely-used third-party applications. Today we made the final switch, which will have updated the domain name in the emails. It's possible that we'll need to revert it if any problems become apparent (which would also revert the emails' links) but that would be only a temporary measure.

**Comment by bean5** [comment]
Sounds like you are covering your bases well. Good luck and thanks for the awesome SaaS!

**Comment by paglias** [comment]
@Alys I think @bean5 means the name showed when logging in witn Facebook and it's still HabitRPG with the old logo, I believe it's to be changed from the application srttings on Facebook 

cc @lemoness

**Comment by lemoness** [comment]
This should be fixed now (it took them a long time to change our name over). If it isn't, let us know and we'll investigate!

**Comment by bean5** [comment]
I'll try to keep a look out for it. It wasn't a crashing bug, just an inconsistency. Glad you got around to fixing it (and to reopening). Thanks for the awesomeness!
