### ISSUE TITLE
Guide Tour broken

### ISSUE THREAD

**Issue by SmokeMaster1** [HabitRPG/habitica#5780]
After registration I don't play the tutorial aka "Justin the Guides Tour". I deleted all the habits and the To-Do and just start playing. Now I'm not able to complete the Tour.
I try it with a brand new Acc, without deleting the start habits and the To-Do but I can't start the tour.
I've try it on my Android 5 Phone using Dolphin browser, my Android 4 Tablet with Dolphin and Chrome, my Notebook with Ubuntu 14.04 using Chrome and Fire Fox. All whith booth acounts, my main acc and the new Test one. But: all whith German language, changing after registration to english don't fix it.
My User ID (main Acc) is: db0065a2-b009-4c08-89f8-3f51ca1f1a86

**Comment by Alys** [comment]
I believe I've reset all the tours for you so that you should be able to see them all from the beginning. Comment here if you have any problems.

**Comment by SmokeMaster1** [comment]
Shame on me, i forgot very important things to write :(

I can see Justin the guide, and i can klick him. The blue loading cicle appears, load a bit but nothing else happens. Sry, that's very important. I don't know why i forgot this. Maybe it was a bit late for me yesterday...

Still no change at all, i can see and click Justin but nothing happens.

**Comment by Alys** [comment]
Go to the Chrome browser, log out of Habitica. Clear cache, cookies, and local storage (google for how to clear local storage if you don't know; it's different than clearing the cache). Then close all Chrome windows. Reopen and log back into Habitica.

If you still can't see the tour, open View -> Developer -> JavaScript Console. Reload the page again, then click on Justin. Show us a screenshot of everything in the console and also copy and paste the contents here.

**Comment by SmokeMaster1** [comment]
I've do all of this, nothing works. Java script console shows two entrys after reload the page:

`Resource interpreted as Script but transferred with MIME type text/html: "https://payments.amazon.com/gp/apa/csm/jsonp?sellerId=undefined&data=%7B%27…27tags%27%3A%5B%5D%7D%5D%2C%27info%27%3A%5B%5D%2C%27entries%27%3A%5B%5D%7D".f.Widgets.Utilities.addScriptNodetoBody @ Widgets.js?_=1439615263423:45n @ Widgets.js?_=1439615263423:45(anonymous function) @ Widgets.js?_=1439615263423:45h.Metrics.Collector.publish @ Widgets.js?_=1439615263423:45(anonymous function) @ Widgets.js?_=1439615263423:45ai.extend.ready @ Widgets.js?_=1439615263423:39
Widgets.js?_=1439615263423:45 Resource interpreted as Script but transferred with MIME type text/html: "https://payments.amazon.com/gp/apa/csm/jsonp?sellerId=undefined&data=%7B%27…27tags%27%3A%5B%5D%7D%5D%2C%27info%27%3A%5B%5D%2C%27entries%27%3A%5B%5D%7D".`

see screenshots for opended entrys. I klick on Justin, but no changes in the JavaScrips console.

Maybe this is helpfull: I'm now at lvl 10 and Justin opens itself in a dialog box to say that my items are in my inventory. I click on "continue tour" in this dialog box and the box closed.
![bildschirmfoto von 2015-08-15 06 59 30](https://cloud.githubusercontent.com/assets/13787827/9287604/a9bb990a-431d-11e5-9e69-662fb96ebdcb.png)
![bildschirmfoto von 2015-08-15 07 00 05](https://cloud.githubusercontent.com/assets/13787827/9287606/abf47ae8-431d-11e5-817a-f1bd989323b2.png)

**Comment by Alys** [comment]
I've reset all the tours for you so that they are now all marked as completed. Please reload and tell me if Justin disappears.

**Comment by SmokeMaster1** [comment]
Ok, i've reloaded and Justin is gone! Thank you!

**Comment by Alys** [comment]
Thanks for letting us know!
