### ISSUE TITLE
"Equipment & Skills" tab not showing in the Habitica app

### ISSUE THREAD

**Issue by sporeball** [HabitRPG/habitica#5783]
Today I leveled up to level 10 on the Habitica app and no class-exclusive equipment showed up. The browser version is working correctly and showing the "Equipment & Skills" tab, but this is not shown on the Habitica app, even after I reloaded the content multiple times.

**User ID:** ce3d1e2b-be53-4e5e-8101-273157548178
**Operating System:** iOS 8.4

_My Rewards column_
![habitrpg](https://cloud.githubusercontent.com/assets/12767408/9265844/d0370dde-41ed-11e5-8bf5-83b3007bb56f.png)

**Comment by crookedneighbor** [comment]
Thanks for reporting this. I've opened an issue on the iOS repo here: https://github.com/HabitRPG/habitrpg-ios/issues/160

If you'd like to follow the progress of the bug, you can click the subscribe button on that issue.
