### ISSUE TITLE
To-Do's keep shuffling when page refreshes and will not stay in order

### ISSUE THREAD

**Issue by jveopops** [HabitRPG/habitica#5790]
Hey there. So I like to keep my to-do's in an actual list so that I know what needs to be done and in what order. My to-do's keep shuffling themselves around whenever the page refreshes and mixes my order of things all up and it is starting to become quite frustrating. Is there a way that this can be fixed?? Thanks in advance!

**Comment by Alys** [comment]
Please see issue https://github.com/HabitRPG/habitrpg/issues/2606 for a workaround and to follow the progress of the fix.
