### ISSUE TITLE
Static pages other than front page use old design

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5791]
@crookedneighbor if you want to give a look when you work on the front page
##

**Comment by crookedneighbor** [comment]
:+1:

**Comment by paglias** [comment]
Also it miss some javascript (like addthis, newrelic) that are instead in `index.jade` and `static/layout.jade`

**Comment by librarianmage** [comment]
@Alys wair until UI update?

**Comment by Alys** [comment]
Definitely! <3

**Comment by khipkin** [comment]
@Alys Is this still an issue?  If so, perhaps the [wait] label would be better than closing the issue altogether?

**Comment by Alys** [comment]
@khipkin Sorry, I should have given more details! The upcoming website improvement project will cover all pages on the site and there will be significant improvements to the code that creates the pages. Any current inconsistencies in the static pages will disappear naturally as a result of that - I don't believe there's any chance that any pages would be missed. Thus I don't think this issue will be needed for that project and I don't think it's critical enough for us to work on it before the project.

**Comment by khipkin** [comment]
Thanks, @Alys! That makes sense. :+1:
