### ISSUE TITLE
Quests information via the API

### ISSUE THREAD

**Issue by philadams-zz** [HabitRPG/habitica#5795]
Hopefully I'm not mistaken here, but I don't see detailed quests information anywhere in https://habitica.com/static/api - I don't think there's a `quests` endpoint?

Under `user/party/quest` there is a `progress` key, but it shows only what the ego user has done, and how many HP/eggs/whatever are left.

What I want to do is display quest progress, something like

```
Quest "Quest Name Here": 145/500
```

That should work generally for most types of quests. Any recommendations for the best way to gather this information? Thank you!

**Comment by Alys** [comment]
Have a look at the groups commands. `GET /groups/{gid}` will get you all party data, and the quests object in that contains the key for the current quest. The `content` route will let you look up the quest name and other details from the key. Is that what you're after?

**Comment by crookedneighbor** [comment]
@Alys If I'm not mistaken, the group quest data only displays information about the progress of the quest from each user's last cron. It does not show progress made during the day. That only gets applied at cron.

**Comment by Alys** [comment]
Yes, that's correct, but you can get that same-day progress from the user's own data. The party group route can be used to get generic information about the quest.

**Comment by crookedneighbor** [comment]
Right, but I think @philadams wanted to get up to date info about the progress of the party as a whole. I think, currently, the only way to do that would be to look up the member ids using the group route, and then look up each user using the members route. 

So:

``` js
// Get details about the parties quest
// GET https://habitica.com/api/v2/groups/party
// Subbing in party for the group id returns your party
// result.quest;
{
  "members": { 
    "user-id" : true,
    "another-user-id": true,
    "yet-another-user-id": true
  }
  "leader": "user-id",
  "key": "whale",
  "progress": {
    "hp": 500,
    "collect": {}
  },
  "active": true
}

// Get details about the content of the quest
// GET https://habitica.com/api/v2/content
// result.quests.whale
{
  "text": "Wail of the Whale",
  "notes": "You arrive at the Diligent Docks, hoping to take a submarine to watch the Dilatory Derby. Suddenly, a deafening bellow forces you to stop and cover your ears. \"Thar she blows!\" cries Captain @krazjega, pointing to a huge, wailing whale. \"It's not safe to send out the submarines while she's thrashing around!\"<br><br>\"Quick,\" calls @UncommonCriminal. \"Help me calm the poor creature so we can figure out why she's making all this noise!\"",
  "completion": "After much hard work, the whale finally ceases her thunderous cry. \"Looks like she was drowning in waves of negative habits,\" @zoebeagle explains. \"Thanks to your consistent effort, we were able to turn the tides!\" As you step into the submarine, several whale eggs bob towards you, and you scoop them up.",
  "value": 4,
  "category": "pet",
  "boss": {
    "name": "Wailing Whale",
    "hp": 500,
    "str": 1.5,
    "def": 1
  },
  "drop": {
    "items": [
      {
        "type": "eggs",
        "key": "Whale",
        "text": "Whale (Egg)"
      },
      {
        "type": "eggs",
        "key": "Whale",
        "text": "Whale (Egg)"
      },
      {
        "type": "eggs",
        "key": "Whale",
        "text": "Whale (Egg)"
      }
    ],
    "gp": 37,
    "exp": 275,
    "unlock": "Unlocks purchasable whale eggs in the Market"
  },
  "key": "whale",
  "canBuy": true
}

// Loop through the member ids found in the party object
// GET https://habitica.com/api/v2/members/another-user-id
// result.party.quest.progress
{
  "collect": {},
  "down": 0,
  "up": 43
}
```

That should do it. @philadams Let me know if you need anything clarified.

**Comment by crookedneighbor** [comment]
Does anyone else think it's silly that you have to download the WHOLE 16,000 line content json to get specific information about a quest?

Shouldn't we have routes to pull down just the info we need? If we already have that, why isn't it documented?

**Comment by Alys** [comment]
I have the impression that he is asking how to find the quest name and other information apart from what a user has done. @philadams, if we haven't given you what you need, let us know. :)

More content routes would certainly be convenient.

**Comment by philadams-zz** [comment]
Thank you for such complete answers!

 I feel that a lot of time when just checking in, I want to simply get a quick summary:

```
---------------
Level 7 Warrior
---------------
Health: 50/50
XP: 98/220
Mana: 89/138
Pet: None (316 food items)
Mount: None
Quest: 385/500 ("Wailing Whale")
```

I can get all that summary content from simply `/user`, except quest info.

The routes (namely, `/groups/party/<party_id>` at `quest.progress` and `/content` at `quests.<quest_key>`) allow me to get at the current quest's progress indicator (as in, 385/500 for collectables or boss HP or whatever). And `/content` at `<quest_key>.text` gives me the title. Thank you!

And yes, I definitely agree with @Alys that a more convenient route for current quest(s) summaries (complete with a humanized string for quest progress) would be excellently wonderful :)

**Comment by philadams-zz** [comment]
With a little trickery around collection vs boss/HP quest types, of course.

**Comment by crookedneighbor** [comment]
@philadams The normal group route is `/groups/:group_id` but `/groups/party` is a special route which looks up the user's party without having to know the id. 

Other than that, you're spot on!

**Comment by philadams-zz** [comment]
@crookedneighbor brilliant! thanks :)

**Comment by Alys** [comment]
@philadams I'm going to close this but feel free to keep asking questions in this issue if you wish.

@crookedneighbor I don't know if we want to open a new issue for additions of content routes to the API, or just keep it in mind?
