### ISSUE TITLE
Thank you Cards

### ISSUE THREAD

**Issue by melrdennis** [HabitRPG/habitica#5797]
These thank you card or greeting cards - I think maybe a dialog box is supposed to open but nothing is happening? Can we fix this please?
![thank_you_card](https://cloud.githubusercontent.com/assets/13742177/9291905/c0192f06-438f-11e5-982f-68b2f9442bc0.png)

**Comment by deilann** [comment]
You're supposed to click on the party member you want to send them to.
Notice that the cursor changes when you click on them.

On Sat, Aug 15, 2015 at 8:54 PM, melrdennis notifications@github.com
wrote:

> These thank you card or greeting cards - I think maybe a dialog box is
> supposed to open but nothing is happening? Can we fix this please?
> [image: thank_you_card]
> https://cloud.githubusercontent.com/assets/13742177/9291905/c0192f06-438f-11e5-982f-68b2f9442bc0.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5797.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature

**Comment by melrdennis** [comment]
There is no party member list coming up. I click on the image of the card
and _nothing happens_ like I stated before.

What would you suggest?

Melissa Dennis
(517) 672-0779

**Comment by Alys** [comment]
Please see the instructions at the bottom of the wiki's [Cards](http://habitica.wikia.com/wiki/Cards) page. If you have any questions, either keep asking here or drop in to the Habitica website's Help -> Ask a Question guild.

**Comment by melrdennis** [comment]
Is there a reason this isn't linked in the news bulletin?

Melissa Dennis
(517) 672-0779

**Comment by Alys** [comment]
Yes, it's only been created in the past couple of days.

The cards work the same way as party skills do, and as previous cards have done, and for new players who aren't aware of details like that, the Help -> Ask a Question area is populated by many experienced users who can explain site features when anyone asks.
