### ISSUE TITLE
Visualizing which items have increased priority

### ISSUE THREAD

**Issue by mfcovington** [HabitRPG/habitica#580]
Once I set the priority for an item, it would be great to be able to see at a glance what priority level an item has without clicking on its edit button.

Although there might be more elegant solutions, an easy one would be adding **!!** or **!!!** before or after the item description for items with increased priority.

**Comment by wildcate** [comment]
Speaking of priority settings, I found out that I don't really care for that possibility at all, and I would prefer not to have that option visible when setting a new task. Having to assign (or even just feeling like one should maybe assign) a certain priority to certain tasks was, in retrospective, one of the things that made me stop using other GTD systems. I love the very simple basic Habit where the algo takes care of setting the value, and if it's sometimes not really fitting to a simple task that I put off for ages, well - that's what makes it feel more like a game to me.

I can see that priority setting will be very attractive and useful and appreciated for a lot of people, but it would be really nice for me to not see that bit in my "add new" dialogue. (Also the longer dialogue makes me scroll the screen to hit save/close.)

**Comment by mfcovington** [comment]
@wildcate Perhaps a toggle in the main settings panel to enable/disable the priority feature?

**Comment by wildcate** [comment]
@mfcovington Yes, that would be perfect!

**Comment by wc8** [comment]
I added the subrequest (option to hide priority feature) to the [Priority Multiplier](https://trello.com/c/4C8w1z5h) card.

Do you really feel the need to assign a priority just because the feature is there?
I also put in a suggestion to add a normal rank to the priority levels. Maybe that would help? Just always use normal?

**Comment by lefnire** [comment]
we'll hide this, and any other "opt in" features (such as class-system stats attrs) in an advanced collapsible fieldset (@zakkain, I'm gonna re-institute this after all). We'll not set them as toggle on/off in the system, since they default to "off" behavior by setting everything to 1x multiplier. Similar mechanics will set other opt-in features to default behaviors without needing to be toggled on/off

**Comment by Pandoro** [comment]
@lefnire I said I aws against the "advanced menu"-button in the G+, but
after seeing a lot of the features appear which will be hidden, I think it
is a good idea indeed. This way we can hide everything in that menu, while
not needing to make the actual settings.

What do you think about this @wildcate ?

**Comment by caycefischer** [comment]
@lefnire That's cool, there's some good user-driven reasons for it. Test, test, test! :+1:

**Comment by wildcate** [comment]
@wc8 I can see this is puzzling people - I explained it to @Pandoro in #506. The TL;DR: It makes me think too much about priorities, which usually are quite fluid for me and handled completely by my subconscious. Plus it makes the edit menu much longer. And a small part of it is me thinking "I don't want to use it, so I don't want to see it."

I'm fine with having toggles/hiding options/whatnot in an extra advanced popup menu, that way it's easy to keep the normal (main) options nice and slim and those who want to meddle with advanced settings can still do so.

**Comment by wc8** [comment]
@wildcate I saw your explanation in #506 after I posted the question. I get it.
Perhaps default to advanced or basic could be an option, with the user able to switch back and forth.

**Comment by deilann** [comment]
There are some good Trello discussions of priority.
