### ISSUE TITLE
Attribute points shown in stats far less than current level

### ISSUE THREAD

**Issue by gabekr** [HabitRPG/habitica#5803]
For whatever reason, I only have 7 attribute points, despite being at level 38. Any ideas what would cause such a thing?
My user ID is c557274e-6ae9-48dd-bfa7-9e7e7801be7c and I'm running HabitRPG on Chrome. 
Thanks!
##

**Comment by Alys** [comment]
Have you used Fix Character Values to adjust your level?

If so, the next time you level up, you'll probably get the extra attribute points. In fact, that should happen regardless of how this came about. There are two or three conditions under which attribute points can get out of sync, but they all never or hardly ever happen under normal circumstances, so we haven't fixed them yet. There's issues open for them already, so we'll close this one once we've finished helping you.

**Comment by Alys** [comment]
I'm closing this in favour of [Issue #6482: incorrect attribute / stats points from various causes - need generic function to do allocation / deallocation](https://github.com/HabitRPG/habitrpg/issues/6482)
