### ISSUE TITLE
FAQ link in mobile UI leads to HabitRPG wiki

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5804]
I'm using the mobile UI, where the menus are simplified. When clicking on the gear icon, I can access the parameters. There's also a link to the FAQ, which redirects to http://habitrpg.wikia.com/wiki/FAQ, which itself leads to http://community.wikia.com/wiki/Community_Central:Not_a_valid_Wikia since I guess it should be http://habitica.wikia.com/wiki/FAQ instead.
I can't verify right now if it's the same on the desktop site.

**Comment by TheHollidayInn** [comment]
Hey, @Blablux .

I am being redirected to the correct page when using the link from the gear menu. Can you tell me which browser you are using?

**Comment by crookedneighbor** [comment]
Going to the faq from the new iOS app leads to a broken page. 

@viirus that is fixed now, right?

@alys can we set up a redirect on the old wikia?

**Comment by Alys** [comment]
The old wiki already has redirects. They're managed fully be Wikia and were created when the new wiki was created.

The redirects always work for me. I am assuming that they have intermittent failures. It's not something we have control over.

**Comment by ghost** [comment]
This is strange. I just tested it on the tablet, and the redirect worked. So I tested it on the phone again, and got to the Wikia Community Central page. Both were tested using Firefox mobile on Android. The only difference is the UI, since the tablet has the desktop UI, and the phone has the mobile UI with the shortened menu. I verified the link on both devices, and it is exactly the same.
I tested it multiple times, roughly at the same time, and while one device redirects correctly, the other doesn't. Is there any information I can provide on the device that can be helpful in understanding this behaviour ?

**Comment by nathalieaynie** [comment]
![2015-08-18 09 43 25](https://cloud.githubusercontent.com/assets/9162238/9324862/54ae9ed0-458e-11e5-951b-8967c4e7785e.png)
 Doesn't work on iOS 8.4.1 either. Tested it a few minutes ago on Safari.

**Comment by ghost** [comment]
I've experienced some issues with redirect not working if a wikia page opens with mobile skin - and no problem at all if forcing reload of the same wiki page with desktop skin at the same time. Those bugs were persistent and quite oddly found only on a few pages I've tested. Unfortunately, I've had no time to test it deeper after I've got an overall impression of wikia mobile skin using alternative caching.

**Comment by ghost** [comment]
Could someone experiencing this issue please try adding `?action=purge` at the end of the wikia page address as described here: http://community.wikia.com/wiki/Help:Purge

EDIT: not for http://community.wikia.com/wiki/Community_Central:Not_a_valid_Wikia but the initial http://habitrpg.wikia.com/wiki/FAQ instead.

So you may just try following the link: http://habitrpg.wikia.com/wiki/FAQ?action=purge

**Comment by nathalieaynie** [comment]
Clicked on the FAQ link from my iPhone, copied the link, added the action, and it still shows the same 'Community Central: Not a valid Wikia' page

Link I get is: http://habitrpg.wikia.com/wiki/FAQ?action=purge
It redirects to: http://community.wikia.com/wiki/Community_Central:Not_a_valid_Wikia

**Comment by Alys** [comment]
I really don't think it's worth worrying about the wiki redirection not working all the time. We'll change the link in the app, if we haven't already, so that it points to the new wiki.

**Comment by nathalieaynie** [comment]
The 'purge' link above works perfectly on my laptop, though. I agree with Alys, might be simpler to just change the link in the menu.

**Comment by Alys** [comment]
We are definitely changing the link, if we haven't already.

**Comment by crookedneighbor** [comment]
This is now fixed.
