### ISSUE TITLE
There's an To-Do in the Habit column that can't be deleted

### ISSUE THREAD

**Issue by mustard-jedi** [HabitRPG/habitica#5807]
user id : 33861742-5009-483c-86fc-86da9e233f00
group id : bec22c88-bc22-427a-b6d4-6e1e21abbdf9

![screen shot 2015-08-18 at 6 12 44 am](https://cloud.githubusercontent.com/assets/2805854/9317814/9a38e208-4570-11e5-8a51-20e1e0e4716a.png)

special request: can you just delete it so I can move on with my life? :P 

currently just hiding it by using Tags. it's a bit annoying.

**Comment by crookedneighbor** [comment]
I've deleted it for you.

FYI for the devs, it was in the habits array, but had a type of `todo`

**Comment by mustard-jedi** [comment]
thanks! :)

*Live Long And Prosper, *

_DENNIS MICHAEL T. MEJIA__Real Estate Broker_, Nurse, Programmer
_PRC License No. 0018817 | *_HLURB COR No. 2015-03-042*
mobile: +63 _9158029924_ | email: dennis.mejia@thinkfirstrealty.com

_Think First Realty & Marketing Services_
tel: 049 _545 9855_ | Address: Calamba City, Laguna, Philippines
http://www.thinkfirstrealty.com

[image: Facebook] https://www.facebook.com/thinkfirstrealty [image:
Twitter] [image: Google Plus] [image: Youtube] [image: Linkedin]
http://lnkd.in/bTEVB8 [image: Instagram] [image: Pintrest] [image:
Dribbble] [image: Skype]

_For your own protection, please transact only with government licensed
real estate brokers & sales persons._

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Think First
Realty & Marketing Services is not responsible for errors or omissions in
this message and denies any responsibility for any damage arising from the
use of e-mail. Any opinion and other statement contained in this message
and any attachment are solely those of the author and do not necessarily
represent those of the company.
