### ISSUE TITLE
"Gained 0.0 Mana" before mana is introduced on iOS native app

### ISSUE THREAD

**Issue by gbear605** [HabitRPG/habitica#5809]
On the iOS native app (Purple Griffin logo), when you complete a daily it says "You earned X experience and Y gold and gained Z mana". However, while I have not yet unlocked mana, it still says "gained 0.0 mana". I suggest that before you reach level 10, it doesn't say anything about mana.

**Comment by crookedneighbor** [comment]
I've copied your issue to the iOS repo here: https://github.com/HabitRPG/habitrpg-ios/issues/162

You can follow the progress by clicking the subscribe button.
