### ISSUE TITLE
Phantom tags on tasks - a tag remains invisibly after it is deleted

### ISSUE THREAD

**Issue by me-and** [HabitRPG/habitica#5810]
Using the API to fetch tasks, I can see some of my tasks have tags with IDs that don't appear in my list of tags, and don't appear as tags in the web interface.

Here's some code to demonstrate the problem:

``` python
>>> import requests
>>> from pprint import pprint

>>> pprint(requests.get(
...     'https://habitica.com/api/v2/user/tasks/d18b692e-2356-40a2-b5d3-e60d77853cc5',
...     headers={'content-type': 'application/json',
...              'x-api-user': '1186f4a9-a39c-4448-bc18-1c4e00e818bc',
...              'x-api-key': api_key}
...     ).json()['tags'])  # This gives the list of tag IDs on the specified task
{'5d6dbf8a-f818-4f92-8b34-832555cfd00d': True}

>>> pprint(requests.get(
...     'https://habitica.com/api/v2/user',
...     headers={'content-type': 'application/json',
...              'x-api-user': '1186f4a9-a39c-4448-bc18-1c4e00e818bc',
...              'x-api-key': api_key}
...     ).json()['tags'])  # This gives the definitions of all the tags on my account
[{'challenge': 'true',
  'id': '4a22b72c-c4c9-40b0-be0a-0f3a07ade6c0',
  'name': 'Challenges'},
 {'id': '26b54d83-8337-400f-941d-b1d6e32d3077', 'name': 'recurring'},
 {'id': '645f0380-6f11-4fa9-b8ef-efda496cc160', 'name': 'Today'}]
```

Note the `5d6dbf...` tag on the task in the first request just doesn't appear in the list of tags in the second request.

It appears to be impossible to delete the tag, too. It doesn't appear on the web interfaces, so cannot be deleted there, and attempts via the API seem to have no effect:

``` python
>>> requests.put(
...     'https://habitica.com/api/v2/user/tasks/d18b692e-2356-40a2-b5d3-e60d77853cc5',
...     headers={'content-type': 'application/json',
...              'x-api-user': '1186f4a9-a39c-4448-bc18-1c4e00e818bc',
...              'x-api-key': api_key},
...     data={'tags': {}})
<Response [200]>

>>> pprint(requests.get(
...     'https://habitica.com/api/v2/user/tasks/d18b692e-2356-40a2-b5d3-e60d77853cc5',
...     headers={'content-type': 'application/json',
...              'x-api-user': '1186f4a9-a39c-4448-bc18-1c4e00e818bc',
...              'x-api-key': api_key}
...     ).json()['tags'])
{'5d6dbf8a-f818-4f92-8b34-832555cfd00d': True}
```

This is neither the only task with this phantom tag, nor the only such phantom tag.
##

**Comment by Alys** [comment]
This typically happens when you assign a tag to a task and then later delete the tag.

If the tag's value in the task is true, then the tag was assigned to that task at the time it was deleted. If the tag's value is false, then it had once been assigned to the task, but later unassigned before it was deleted.

These phantom tags never cause any problems that we are aware of and can be ignored, but let us know if they are causing you problems.

I expect that at some time in the future, we'll change the code to remove tags from tasks when they are deleted (especially if a contributor submits a good pull request for that) but it's not a priority.

**Comment by me-and** [comment]
Okay, that makes sense. It is causing problems for the Python API module I'm trying to write, as that is trying to parse those tags and failing because the information is missing, but I'll just work around that for now, and possibly look at writing that code to remove the tags when they're deleted.

**Comment by Alys** [comment]
I believe this has been fixed now that API v3 has been released. This can be reopened if I'm wrong.
