### ISSUE TITLE
Debug "skip day" option no longer counts missed Dailies

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5813]
Since the changes @Alys made to prevent Dailies from punishing a user repeatedly if they log in again after being away for a few days, the "+1 Missed Day" and "+2 Missed Days" debug buttons (available only in non-production environments) no longer trigger damage from Dailies. Bosses always hit for 0, etc.

**Comment by Alys** [comment]
All those buttons do is subtract days from the user's lastCron value so they'll still be working.

Are you testing with Dailies that you've just created? If so, their startDate will be today and so they won't trigger damage from yesterday's cron.

**Comment by SabreCat** [comment]
Hmm, that could be the case. I'll take a look tomorrow and see if it's still doing the same thing.

**Comment by Alys** [comment]
I've tested locally and the buttons work so I'm closing this. It can be reopened tomorrow if needed.

**Comment by crookedneighbor** [comment]
hmmm I experienced this bug where the quest progress button wasn't being applied. Had nothing to do with dailys

**Comment by Alys** [comment]
Quest progress button?

Do you mean that no new quest progress message appeared in party chat? Or that you did zero damage to the boss / zero items collected? If the latter, had your user.party.quest.progress been cleared out by a recent previous cron?

**Comment by SabreCat** [comment]
Maybe the +1000 Boss Quest Progress Up debug button? That worked for me yesterday.

**Comment by SabreCat** [comment]
OK, confirmed @Alys's suspicion about why I've been having trouble. Test user with existing Daily takes damage from it just fine when using the debug button.

Just means I can't create new test users willy-nilly for looking at boss battles and whatnot :P

**Comment by Alys** [comment]
You can edit the Dailies to set the start dates in the past.
