### ISSUE TITLE
Restrict keyboard navigation during tutorials

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5814]
At present, when a Justin tutorial is active, attempting to use the keyboard to navigate the site continues to move around the elements behind the modal fadeout. Ideally, when a tutorial modal pops up, keyboard focus should default to the Next or conclude button, and tab navigation should only move to elements within the modal, not out to the veiled page content.
##

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
@sabrecat is this still an issue?

**Comment by Alys** [comment]
keyboard navigation does't do anything in the new Justin tutorial
