### ISSUE TITLE
Walked away for a day, got damage but no streaks reset

### ISSUE THREAD

**Issue by fogbank** [HabitRPG/habitica#5821]
As it says: I forgot to log into the site at all on august 19 and when I logged in the next day I got damage, but the streak values didn't get reset to zero. Not that I'm pissed, quite the contrary :sweat_smile: , but you might want to take a look and fix it.

I haven't tried to reproduce it, because if it worked this time it would kind of suck. :stuck_out_tongue_winking_eye: 
##

**Comment by fogbank** [comment]
Sorry, this is likely a duplicate of #5459. That issue was marked as closed, though.

**Comment by Alys** [comment]
Habitica's code has recently undergone large changes, which means that the code that caused these bugs probably does not exist any more. I'm closing this, but if you notice the same problem happening again, please open a new issue.
