### ISSUE TITLE
Plus (+) Habit counts negatively

### ISSUE THREAD

**Issue by lmrigo** [HabitRPG/habitica#5822]
I had a habit with + and - buttons. Since I only pressed + I thought it would be a good idea to remove the - button. My graphic used to be a crescent line, with some flats on the days I skipped it. Now that I don't have the - button anymore, my statistic goes down and down. Is this a bug? 

See screenshots below.

My User ID: 963086c0-7a97-472b-aad3-f0caad838eb0
My Browser and System: Chrome Version 44.0.2403.155 m, Windows 7

![habitbug](https://cloud.githubusercontent.com/assets/3036345/9408882/90807252-47ec-11e5-87c8-ef9f1766a0c2.png)

![habitbugtrend](https://cloud.githubusercontent.com/assets/3036345/9408954/19326d4e-47ed-11e5-970f-327a828d5da4.png)

**Comment by SabreCat** [comment]
Nope, not a bug. The graphs track the value of the task over time--the bit that's expressed on the site as the task's color. One-direction Habits float back toward yellow if untouched, so their value drops each day.
