### ISSUE TITLE
Getting way more eggs than hatching potions.

### ISSUE THREAD

**Issue by amberlea84** [HabitRPG/habitica#5823]
I play with both my roommates and neither of them are having this issue, but I have 19 eggs and no hatching potions, and it's been this way as long as I've been playing. I just keep getting more and more eggs and the hatching potions are few and far between. I don't know what could be causing this.

**Comment by Alys** [comment]
@amberlea84 Please see https://github.com/HabitRPG/habitrpg/issues/2176 for earlier reports of this and an explanation (in bold in the top comment). In brief, the run of eggs you're experiencing is just a random fluctuation.
