### ISSUE TITLE
iOS Translations - multiple strings

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5826]
Hello! 

I started translating the iOS app and I noticed that some strings are there multiple times - To-Dos are there 4 times, Profile 3 times. Just like that on their own. The problem is, we distinguish between the title of the column To-Dos and the To-Dos tasks themselves. I looked into the Info about the strings and I cannot determine which is which so now I dunno which translation to use.

**Comment by crookedneighbor** [comment]
Hi @Miisa, this should be reported in the repo for the Habitica iOS app: https://github.com/HabitRPG/habitrpg-ios
