### ISSUE TITLE
Express 4: res.json is deprecated in a favour of res.status().json()

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5827]
As per Express 4.x

```
deprecate res.json(status, obj) -- use res.status(status).json(obj) instead
deprecate res.jsonp(status, obj) -- use res.status(status).jsonp(obj) instead
deprecate res.send(status, body) -- use res.status(status).send(body) instead
express deprecated res.send(status): Use res.sendStatus(status) instead
```

**Blocker**: in `batchUpdate` we override `res.json`, so it would require to rewrite it in order to allow for `res.status().json()`. Will probably wait until we have to break `batchUpdate` for tasks migration.

Also give a look if we're overriding `res.json` in batchUpdate not only for the current request but for every of them, given that it should be a prototype (see https://github.com/strongloop/express/blob/master/lib/response.js#L36).
##

**Comment by markstos** [comment]
Could you link to the official deprecation notice? I don't see it in either the [3.x->4.x upgrade doc](https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x, nor in the [4.x API docs](http://expressjs.com/api.html). 

_Update_ I still haven't found the official doc notice about this, but [the deprecation notices for `res.json` are clearly in the source code](https://github.com/strongloop/express/blob/master/lib/response.js#L229)

**Comment by paglias** [comment]
@markstos you can find them in the changelog here https://github.com/strongloop/express/blob/master/History.md#470--2014-07-25
