### ISSUE TITLE
Migrate existing Grunt tasks to Gulp

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5829]
Gulp is better and also we don't like having 2 build tools
##

**Comment by noppanit** [comment]
I think it's a great idea. Anybody pick this up? May I?

**Comment by crookedneighbor** [comment]
@noppanit Go for it. I'll be happy to review it.

**Comment by librarianmage** [comment]
Is this still a thing?

**Comment by Alys** [comment]
It's still desirable and no current work is being done on it.

In https://github.com/HabitRPG/habitrpg/pull/6112#issuecomment-168100390, @crookedneighbor says:
**"Let's do smaller PRs extracting one grunt task at a time."**
I suggest that anyone working on this follows that advice.

**Comment by Alys** [comment]
I'm changing this to a medium priority though because it's not as important as some of the bugs we have.

**Comment by librarianmage** [comment]
Is this still a thing?

**Comment by paglias** [comment]
done!
