### ISSUE TITLE
task actions are slower than before

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#583]
The effects of interacting with tasks (eg, notifications, stats updates, task value updates, etc) are now much laggier than before. This isn't critical, since most of these are done client-side - and nobody's reporting crashed browsers yet, but we'll need to optimize this sooner than later.

I _suspect_ either the new algos' more intense client-side JS math, or possibly we have too many model listeners being triggered?

**Comment by lefnire** [comment]
something in https://github.com/lefnire/habitrpg/commit/16b9ea3b58177a6d7b62e1ae11ed8d9ecf865496 (or rather, the inverse of that, since that's a revert of the commits) _seemed_ to fix the problem - so maybe it's something to do with the html structure, using `{{}}` instead of `{}` as often as possible, or adding namespaces to tasks & rewards. I'll be re-applying those commits manually in coming days - had to revert due to some heavy merge conflicts

**Comment by Pandoro** [comment]
Oooh man :( I feel you! This kind of stuff always sucks!

**Comment by lefnire** [comment]
Can't remember how, but we fixed this along the way. MrConcept to the rescue.
