### ISSUE TITLE
Standard error handling

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5835]
We're handling errors in a lot of different way, there are a few steps we should take:
- 5xx errors should be reserved ONLY for things we don't control (like server/libs errors, exceptions..)
- Errors should have a common response format (like `{message: "", code: 4xx, ....`)
- Errors should be logged (maybe with newrelic?)
- All errors should be handled in the same place. for example passing them to an error handling middleware with `ǹext()`
- All user-visible error messages should be translatable
##

**Comment by Alys** [comment]
I've added this:

- All user-visible error messages should be translatable
