### ISSUE TITLE
"Old News" page is not very pretty

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5836]
We have a static page for viewing old news entries. However, it has several notable problems:
- None of the headings are bold, the way they are on Bailey's modal, making everything run together.
- The current news is included, which is not such a bad thing, except that...
- ...the "older news" link still appears, to no purpose.

**Comment by zedutch** [comment]
@SabreCat Could you take a quick look at PR #5884? I might have handled this issue so I think it can be closed. Unless you have some remarks/comments about my solution or more suggestions for the design of this page?
