### ISSUE TITLE
Cannot see Challenges all of a sudden

### ISSUE THREAD

**Issue by Howler-zz** [HabitRPG/habitica#5839]
My API ID: 51d93091-c349-4d2c-9814-3033baf54512

Error: The Challenges page loaded correctly not five minutes ago. Then, when I came back to it after joining some Guilds, the header and sidebar loaded, but not any of the Challenges themselves. I got this error message: 
'Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33718516 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.'
This has persisted even after I "allowed all on this page" in the NoScript extension, and confirmed that AdBlock Plus was blocking no content.

Browser: Firefox 40.0.2 for Mac
OS: OSX 10.9.5

Please advise.

**Comment by Alys** [comment]
@Howler I'm sorry we never got back to you about this. These errors tend to be temporary so it's likely that the problem has fixed itself by now. If it hasn't, please tell us.
