### ISSUE TITLE
WAY to much XP received

### ISSUE THREAD

**Issue by philippludwig** [HabitRPG/habitica#584]
Today, I marked a task as complete and gained 23521099245212 XP. The task has been living in my todo-list for several weeks, but I don't think that this is correct.

Additionally I've got 2045312977206 Gold now.

**Comment by lefnire** [comment]
what time was that at? #564 which fixed this in the afternoon today

**Comment by Pandoro** [comment]
Hmmmm @lefnire this post was made after the fix though, unless I am mixing something up here?

**Comment by PhilipHow** [comment]
Woops, I forgot that existing low values would still push out high deltas. #588
