### ISSUE TITLE
Cannot equip Cheetah Items

### ISSUE THREAD

**Issue by awoitte** [HabitRPG/habitica#5840]
User ID: 26a8b996-7702-40ac-9997-e3e44f309e0f
Browser: Chrome
OS: Windows 7 and 10

When I equip the new subscriber cheetah items they do not remain equipped after a refresh. I suspect the server is not saving the item change. I'm trying to equip them as costume.

No console errors on equip, however I have been receiving the following error on page load since I signed up (so it's probably not related):
Uncaught TypeError: (t.data || "").search is not a function

**Comment by awoitte** [comment]
More info:
batch-update Post request is returning 200 OK . 

Eg. Request Payload:
[{"op":"equip","params":{"type":"costume","key":"armor_mystery_201508"}}]

Eg. Response:
{"_v":1034}

**Comment by Alys** [comment]
The fix for this has gone live. If you're still experiencing problems, reload, and if still then, log out of Habitica, clear cache, cookies, and local storage, close all browser windows, then reopen and log back in. Let us know if that doesn't fix it!
