### ISSUE TITLE
Make search quest difficulty proportional to party size [request]

### ISSUE THREAD

**Issue by IntermittentlyRupert** [HabitRPG/habitica#5842]
It would be good if the difficulty of quests where the user is searching for items (e.g. The Moonstone Chain, Part 1) was proportional to the size of the party. The current setup means solo/small questing parties can take a very long time to complete such quests - I have been running The Moonstone Chain, Part 1 for a little under two months and I am less than half way to completion. Such slow progress can be quite demotivating.

**Comment by Alys** [comment]
@kaotik4266 We already have an issue for this at https://github.com/HabitRPG/habitrpg/issues/5618 so I'll close this one to avoid splitting the conversation. Could you post your suggestion in that issue?
