### ISSUE TITLE
Armoire seems to be limited to 10 items per month?

### ISSUE THREAD

**Issue by carolstone** [HabitRPG/habitica#5843]
fccb1fc7-a4fc-465b-9dcc-0cfdf37cbb59

I feel like I'm being a pest, but if I've had the Armoire for two months, (and I thought I had it a little longer than that) shouldn't I be able to get more than 10 items from it per month? Last month it told me it had run out of items when I was short of the full 14 and I don't remember if it told me I had run out this month or not, but right now I only have 20 items and it has pretty reliably given me a lot of XP and a few food drops for over a week. Is there anything funny in my account setup? Or am I imagining things?

**Comment by SabreCat** [comment]
There are 20 items in the Armoire at present, so you have everything. The number of items available increases each month, but if you've already acquired all the previous items, you'll only have the new ones available to get at that point. Say we add 4 new items in September: you'll have 4 items to get, totaling 24.

**Comment by SabreCat** [comment]
Oh, one further comment--what you saw with the Armoire reporting it was empty when you still had items to get was indeed a bug, but that's been fixed for this month's restock. If you see it proclaiming it's empty early again, do report that!

**Comment by carolstone** [comment]
Thank you very much!
