### ISSUE TITLE
Quest stuck for party

### ISSUE THREAD

**Issue by WezCorp** [HabitRPG/habitica#5844]
Hi guys,

We had a member start a quest - and then become inactive so we couldn't start the quest (as we had a few members in the inn).
I had to boot the inactive member and now we need the quest removed so we can start another.

Party ID: 42599d3d-3058-44c3-bc22-07d007499d5f

Thanks

**Comment by Alys** [comment]
The leader of that quest isn't inactive. They last logged in yesterday/today (2015-08-25 13:45 GMT). Please invite them back to your party and they they should be able to abort the quest.

If they get back into your party but aren't able to abort the quest, or if they haven't responded to your invitation after a couple of days, comment here and we'll work on manually removing the quest.

**Comment by WezCorp** [comment]
Thanks Alys - will do. Asked via numerous ways (party chat and inbox) over the last week, but I will see if they respond to the party invite.

**Comment by Spriteman11** [comment]
I had a similar issue but on the other end! I was the inactive member in a party (sorry!) And what happens is a quest page from the party shows up whenever I log in, and if I hit accept or reject a notice says "no group found" and the page continues to show up each time I log in. 
User id: 465beffc-0712-4bbe-8e40-2f4ab8098eb5
os: osx yosemite 
browser: Firefox

**Comment by Alys** [comment]
@Spriteman11 I believe I've fixed that for you. Comment here if it's still happening.

@WezCorp Do you need help now with your party's quest?

**Comment by WezCorp** [comment]
Oh Alys I'm sorry I should have replied days ago. It has been fixed now and we have moved on from that quest thankfully. You can close this issue, and thanks

**Comment by Alys** [comment]
No worries. :)
