### ISSUE TITLE
Pixel art images should use image-rendering:pixelated

### ISSUE THREAD

**Issue by RossBrunton** [HabitRPG/habitica#5846]
https://developer.mozilla.org/en/docs/Web/CSS/image-rendering

Basically, whenever you zoom in, the browser tries to "correct" the image without knowing it's pixel art, meaning that the image looks kinda jpegy or something. Apparently image-rendering is a new thing that allows you to specify "hey, this is pixel art, don't do any of that magic" and preserves the pixel-artiness of it.

First image is "normal", second is with image-rendering set to pixelated.

![nonpixelated](https://cloud.githubusercontent.com/assets/662364/9491741/300dd242-4be9-11e5-966b-e69e6ac417bb.png)
![pixelated](https://cloud.githubusercontent.com/assets/662364/9491745/3650170a-4be9-11e5-85a8-e3d502002807.png)

**Comment by TheHollidayInn** [comment]
Hmm, cool find! The feature is still experimental, but if we want to adopt this, I think we can advertise this to entry level coders.

**Comment by RossBrunton** [comment]
I tried to do this myself, but I have a bit of a problem knowing which things to apply the style to. At the moment, it seems that setting it on non-img tags works, since everything that is pixelated is pulled from a spritesheet in a span or div, whereas images that aren't sprites, such as the big image on the homepage, use a "traditional" img tag. Is this okay?

**Comment by TheHollidayInn** [comment]
Yea, so from your link, there are two examples:

One, you can add the css property to `img` tags.
Two, you can add the css property to tags that have the `background:url` or `background-image` property set.

Does that clarify?

**Comment by RossBrunton** [comment]
Not really, but I probably didn't explain myself clearly enough, sorry. Basically, you have images like https://d2afqr2xdmyzvu.cloudfront.net/front/images/intro.png which shouldn't be pixelated. I'm just wondering if it's the case that ALL images that shouldn't be pixelated are in img tags, and there are no images which should be pixelated that are in img tags.

I'll just submit a pull request and you can see if it works as it should.
