### ISSUE TITLE
Easy to (even accidentally) abuse intro tutorial bonuses

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5852]
The [recent tweaks to onboarding to have the tutorial award Experience and Gold](https://github.com/HabitRPG/habitrpg/pull/5851) have some basic code in place to prevent tutorial steps from awarding their bonuses twice. However, the protections get thrown off if the user refreshes the page, so it's not too difficult to end up with the tour awarding more bennies than intended. We could improve this functionality with more persistent tracking of what awards have been given out.
##

**Comment by Alys** [comment]
As a side effect of this issue, a new player who repeats tutorial steps can gain more than max XP without leveling up. It's common to see questions like this in the Tavern:
**"just joined the game, I have enough exp for lvl 2 (I'm lvl 1 right now with my xp showing 265/150) but nothing is happening?"**

If this issue can't be fixed easily, is it possible to put in a workaround to prevent the tutorial giving more than 150 XP? Or have a check for a level-up condition when the user completes (or abandons) the tutorial?

It's a confusing situation for a new user to find themselves in.

**Comment by markhowson** [comment]
Looking into this now (and #5854, etc)

**Comment by markhowson** [comment]
I'm quite new to the project, and not yet 100% familiar with the way Habitica likes to do things. I still need to do more thinking/testing before I do a PR, but any feedback would be great. So far:
- Added flags.tourRewards in user data to keep track of awarded steps persistently. 
- Using the tracking built-in to the bootstrap tour component to follow which step we're at (ie. local/session storage). I figure most of the time, this is 'good enough' to keep the user in the right place (it'll hold after refresh, for example). Either way, it won't reissue duplicate awards, and simplifies the code a little.
- I've kept the meaning of flags.tour the same for compatibility (i.e -2 for completion), but it doesn't store the intermediate step values.

**Comment by SabreCat** [comment]
@markhowson: That sounds like you're on the right track! If you'd like, you can put your work-in-progress into a PR so we can follow along and provide feedback as needed. You can put "WIP" in the title to make clear you don't intend for it to be merged right away.
