### ISSUE TITLE
Dailies checkboxes have no selectable spot using speech recognition

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#5853]
There's nothing to click on when I try to check off a Dailies.

Steps to Reproduce:
1. Start Internet Explorer
2. Go to http://www.habitrpg.com
3. Say "Show Numbers"

I expected to see big clickable areas like the ones under Habits (e.g. 81). Unfortunately, I only see a column of tiny squares (e.g. 82).

I've also included a screenshot.
![show numbers](https://cloud.githubusercontent.com/assets/1581929/9556150/77277544-4d87-11e5-8df0-62f7d4885a75.png)

Background:
- Browser: Internet Explorer 11
- Operating System & Speech Recognition: Windows 7 SP1 x64 EN-US
- User ID: 90145e45-71ca-4c83-8ecf-703e40ccdcda

F12 Developer Tools Console:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: habitica.com

HTML1300: Navigation occurred.
File: habitica.com

CSI/tbsd_: 4,537.021ms

CSI/_tbnd: 4,537.285ms

Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

SEC7118: XMLHttpRequest for https://fbstatic-a.akamaihd.net/rsrc.php/v2/yD/r/jART5Bl0xO-.js required Cross Origin Resource Sharing (CORS).
File: like.php

**Comment by Alys** [comment]
I'm pretty sure that "show numbers" is intended to give you numbers that you can say out loud to "click" things, so the size of the number shouldn't matter. What happens when you say 82?

**Comment by Alys** [comment]
I'm closing this but if you are having trouble completing tasks with voice commands, comment here with as much detail as you can give (e.g., exact behaviour noticed, javascript console error messages if any, examples of voice commands that do work if any).

**Comment by Zian** [comment]
On the initial page load, I guess the following error in the developer tools console:
SCRIPT5: Access is denied.

File: widgets, Line: 1, Column: 1

When I say show numbers against the following image:
![untitled picture](https://user-images.githubusercontent.com/1581929/34088908-504f5fdc-e361-11e7-82f9-36c67607af3d.png)


When I say "check floss", nothing happens.  Nothing new appears in the developer tools.  When I say " click health potion", nothing happens either.

Unfortunately, appears that the site redesign has made things even harder to use with Windows Speech Recognition.  If it's any consolation, GitHub is not too friendly either for speech recognition.  It is impossible two and even click a link to upload a screenshot.

**Comment by paglias** [comment]
I'm merging this issue with #6426
