### ISSUE TITLE
Can't feed pets anymore

### ISSUE THREAD

**Issue by celentanoad** [HabitRPG/habitica#5856]
I'm using Habit RPG on Safari.  Whenever I fed my pets, I would get a pop up that asked me to confirm.  It was pretty annoying, so I checked a box that would make it no longer pop up and ask me to confirm before I fed the pets.  Now, when I try to feed my pets, nothing happens.  I click the food, which causes the pets to get the green shadow behind them, then when I click the pet I want to feed nothing happens.  The food doesn't decrease and the green shadow stays there.  I tried to go through safari's preferences and turn the option to have the pop up back on, but I can't find it anywhere.

**Comment by Alys** [comment]
The option to block the pop up is a feature that your browser itself implements. If you close your browser (all open windows), then your browser's setting will be reset and the pop up will appear again.
