### ISSUE TITLE
Can't use my account, screen is stuck

### ISSUE THREAD

**Issue by NessyNoinex** [HabitRPG/habitica#5857]
This is what I see when I log in my account
![habitica](https://cloud.githubusercontent.com/assets/6381483/9561961/8452b31a-4e5d-11e5-9c08-780deaa447a3.PNG)
I've tried to log out and in but options don't work, I've closed the tab and opened it again and nothing changes. It works if I log in to my account from an incognito window but it's a lot more comfortable for me if I can use the web from the not-incognito windows.
My id is: a7b42b00-3ff9-4e52-8486-ec367fa564ad
I use chrome and windows 7
Chrome console says this:
![habt](https://cloud.githubusercontent.com/assets/6381483/9561981/3f3458a0-4e5e-11e5-985d-02ed6c120dee.PNG)

**Comment by crookedneighbor** [comment]
Try pressing `ctrl + shift + r` - this will force a full refresh of the page

If that doesn't work, follow these instructions to clear your cache: https://support.google.com/chrome/answer/95582?hl=en

If that still doesn't resolve the issue please press the link on the line that says `Uncaught SyntaxError` and take a screenshot of highlighted code it will show.

**Comment by crookedneighbor** [comment]
I'm going to close this since I haven't heard back from you, but if you're still having issues, feel free to re-open it.
