### ISSUE TITLE
Rewards for XP in party-- getting XP without joining quest.

### ISSUE THREAD

**Issue by patatbeerho** [HabitRPG/habitica#5858]
I'm not 100%, but I think I am receiving xp awards for defeating quests even when I am not in the questing party. My group just finished a fairly hard boss that I was not in the questing party for, and I got a ton of xp this morning on log-in.

Using: desktop site and Android OS app.

Group ID: e523326e-597b-437f-b5b4-31191f659332

**Comment by patatbeerho** [comment]
Group ID: e523326e-597b-437f-b5b4-31191f659332

**Comment by SabreCat** [comment]
@patatbeerho: Given that you're using Habitica on both the desktop and a mobile app, what you're probably seeing on login is one catching up to everything you did on the other. For instance, if you check off several tasks on the mobile app, earning 100 Experience and 10 Gold, then log in to the Web site, you'll see a +100 Experience +10 Gold notification appear.

Closing this for now, but feel free to reopen if the above doesn't describe what you're seeing!
