### ISSUE TITLE
Cannot cancel subscription

### ISSUE THREAD

**Issue by nightgigjo** [HabitRPG/habitica#5859]
I went to /settings/subscription to cancel my subscription tonight, and clicking Cancel Subscription brought up this error message on a new page: {"err":"Cannot read property 'current_period_end' of null"}

My User ID is 8db34268-08f6-47b2-88be-5c7d25f70070 - using Firefox 39.0.3 on iOS 10.10.4.

**Comment by Alys** [comment]
This means that your subscription has already been cancelled by our payment processing company because they were unable to extract payments from your credit card. I've removed the subscription information from your Habitica account. Sorry about the inconvenience!

**Comment by nightgigjo** [comment]
Oh, OK! Thank you for clearing that up!

J

On Sat, Aug 29, 2015 at 9:26 PM, Alys notifications@github.com wrote:

> Closed #5859 https://github.com/HabitRPG/habitrpg/issues/5859.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5859#event-395912872.

## 
- Jo
