### ISSUE TITLE
Excessive Experience Reward causes overfull Experience Bar

### ISSUE THREAD

**Issue by kalmduck** [HabitRPG/habitica#586]
I have a Daily that I have gotten quite behind on, but I actually managed to do it today after placing a !! priority on it.  When I checked it as completed, I was awarded many thousands of Experience points and a little over 600 gold.  As this caused me to level up several times, it seems like the reward may have been a little excessive.

Also, the Experience bar now shows as overfull with me having 7420/980 Experience to level up (see screenshot)
![BugShot](https://f.cloud.github.com/assets/3541909/219721/afb5d0ee-853f-11e2-97d7-a0efbf95384c.png)

**Comment by cleave29** [comment]
I think this might be related to #564 although it sounds a tad different because of the priority

**Comment by Pandoro** [comment]
Hmmmm yea, but the priority multipliers really just multiply the stuff.
While 7.4k exp sounds like a LOT the previous error was caused by an
overflow. This rather sounds as if the formula itself just gave a too big
reward. @MrConcept? Any ideas?

**Comment by Pandoro** [comment]
Once this happens, your values are recorded wrong and it cannot be fixed by
new code changes.

What you can do though, is click the "Restore your exp here" link in the
top green bar ( also visible in your screenshot.)  There you need to set
the values you had before htis happened, and you can restore your character
to these values. Of course you can cheat here, but that isn't the purpose
here :p

Sorry for the inconvenience, hopefully you can get your values back, feel
free to ask if anything goes wrong!

**Comment by lefnire** [comment]
this should have fixed the issue: https://github.com/lefnire/habitrpg/commit/ce09d72708529935b362e41652e127a80333cd0b - however, it was pushed a fews hours before some people reported the same problem. It could be they have delayed reports, let's wait and see. If we get any new high-exp bug reports, we're gonna revert back to the old `delta` & `value` algorithms, still keeping @MrConcept's exp / gp separation & notifications

**Comment by kalmduck** [comment]
I just completed the delinquent daily, and there weren't any specific problems.  It did award almost 400 exp, but I could believe that from just being very far behind on the task.  I did not experience the "overfull experience bar issue" this time, so I'll close this one unless it resurfaces.

**Comment by PhilipHow** [comment]
Fantastic, thanks kalmduck. Out of interest, what is your level and current weapon? And did you have an priority multipliers on it?

**Comment by kalmduck** [comment]
I'm level 7 with a Blue Sword, and I had the !! priority multiplier on the daily.
