### ISSUE TITLE
Reset Quest please: Unable to start or cancel Quest in party

### ISSUE THREAD

**Issue by vicsta83** [HabitRPG/habitica#5860]
Group ID: 962a311c-ea89-4be3-b0e1-d9f66657af25
Group leader ID: 57de2a69-20ef-48c9-a183-4b01cd8468bb

Could you please reset this party's quest as we are unable to start.  The quest owner has left and no one else was assigned. All have accepted/rejected but quest still hasn't started.

Thank you

Vicsta83

**Comment by Alys** [comment]
The original quest owner has deleted their Habitica account.

I've made you the quest owner. You can reload the party page to see the quest begin and cancel buttons. If you choose to begin the quest, it will behave just as if you started the quest with your own scroll. If you cancel the quest, the quest scroll will go into your inventory for reuse later.

Comment here if you still have problems, but it should be fine now.
