### ISSUE TITLE
Current Equipment cannot be removed from Avatar

### ISSUE THREAD

**Issue by colbyfromage** [HabitRPG/habitica#5861]
Basically what the title says. The Rancher Hat, Lasso, and Soothing Lunar Armor have been stuck on my Avatar for a few weeks. No matter how much or in what combination I try to change it, it never changes, though my equipment list shows the items I want as being selected. I also receive the buffs from whatever equipment I choose, therefore everything is working except the actual visual change to other equipment. Refreshing the page does not fix this.

**Comment by crookedneighbor** [comment]
Is it possible you're using the costume option?

**Comment by colbyfromage** [comment]
Yes, yes it is. Thanks!!!
