### ISSUE TITLE
API should return flagged messages in chat only to mods

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5865]
Chat messages with more than 2 flags should be returned by the API only if they are requested by a moderator.
##

**Comment by paglias** [comment]
When it's done the client side code used to do this should be removed. In mobile apps too

**Comment by valeriecodes** [comment]
I'll take a crack at this.

**Comment by Alys** [comment]
@azelma <3  Thank you! Feel free to post here if you have questions or run into problems. You're also welcome to submit an early pull request if you have partially completed code that you'd like us to look at.

**Comment by srrvnn** [comment]
finished working on this one, and I was trying to write a test. it looks like it should live in `tests/server_side/controllers/groups.test.js`. But running gulp test:server_side doesn't seems to run that file. How do I run tests in groups.test.js?

**Comment by crookedneighbor** [comment]
@srrvnn I'm in the middle of reworking the api tests, so don't worry about it right now. I'll add it as part of the work I'm doing. Go ahead and open a pull request for us to review.

**Comment by TheHollidayInn** [comment]
Does this issue need anymore work? It seems to have a fix merged.

**Comment by Alys** [comment]
Thanks @TheHollidayInn!
