### ISSUE TITLE
Missing Item

### ISSUE THREAD

**Issue by mara16121** [HabitRPG/habitica#5873]
I received the Lunar Scepter the other day and I equipped it. Today I was looking at my character and I noticed it was not there, so I checked my inventory. It's gone. As far as I know, I didn't die. Is this a glitch that caused me to lose the item?
I had previously been told I had this item and when I went to my inventory I had a different one. I have read about this glitch that gives you a different item than the notification claims. This time, though, I was actually able to equip the lunar scepter.

**Comment by SabreCat** [comment]
I do think this is the same thing as #5376. You'll note that some other folks who have run into the issue have also been able to equip the item before it swaps out. It's a matter of timing: if you get to the Equipment page and put on the item before your browser syncs up with the site, you'll be able to equip it but it'll vanish later; if you sync after getting the item but before visiting the Equipment page, the item will be gone before you get to click it.
