### ISSUE TITLE
problem with challenges page

### ISSUE THREAD

**Issue by locheed9** [HabitRPG/habitica#5874]
Recurring error message from top right of screen, stating: 
Please reload: error runner error: overflow sort stage buffered data usage 33818640

**Comment by locheed9** [comment]
PLEASE AND THANK YOU MY SISTER WOULDN'T SAY IT

**Comment by zedutch** [comment]
I think this is a duplicate from #5839

**Comment by crookedneighbor** [comment]
Yes, this does sound very much like a duplicate of that issue. Closing this one. You can track the progress by clicking the subscribe button on that issue.
