### ISSUE TITLE
Text on party hidden by grid! (iOS app)

### ISSUE THREAD

**Issue by gigantera** [HabitRPG/habitica#5880]
Hi, folks,
I couldn't help but notice all texts published on the party history with more than 3 lines can't be read from the 3rd line beyond.
Hope it helped!
-Luiza Dornelles

**Comment by Alys** [comment]
There should be a scroll bar at the edge of each message for scrolling down to see the end. If there isn't tell us which browser you are using (including version number), which operating system it's on (including version), and please show us a screenshot of a chat message that has more than three lines.

**Comment by gigantera** [comment]
Here it goes. I'm using latest habitica app to date (09/01/2015) for iOS in an iPhone 4S. 
-Luiza Dornelles

**Comment by Alys** [comment]
Can you please report that in the app using the Menu -> About -> Report a Bug option? That will send information about your device to the mobile developers which assists with troubleshooting.

**Comment by Alys** [comment]
I'm closing this because we don't use this repository for mobile development and bug fixes, but the mobile devs will definitely look into this.
