### ISSUE TITLE
Error Cannot set property 'drop' of undefined

### ISSUE THREAD

**Issue by brandonlichtenwalner** [HabitRPG/habitica#5881]
Situation: Casting "Burst of Flames" which causes me to level to 60 (and the first time it happened I saw that I received the Moonstone quest). Reloading does not help and I receive the same error upon subsequent casts.

Error: Please reload, "Error Cannot set property 'drop' of undefined" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

Javascript Console Output: https://habitica.com/api/v2/user/class/cast/fireball?targetType=task&targetId=18e9d924-6113-4e34-9512-ee5fc80ba30b Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by Alys** [comment]
Please refer to https://github.com/HabitRPG/habitrpg/issues/4986 for the fix

**Comment by brandonlichtenwalner** [comment]
Thank you Alys. I searched a bit but didn't come across #4986; sorry for
posting a duplicate!
