### ISSUE TITLE
Reward price notification reports inaccurate prices

### ISSUE THREAD

**Issue by peregra** [HabitRPG/habitica#5883]
When I purchase a reward (Enchanted Armoire, health potion) the correct amount of gold is pulled from my account, but the popup notification reports an inaccurate price. 

For the Enchanted Armoire the popup shows that I am charged 103 gold 42 silver. The rewards column price shows a cost of 100 gold as expected. I have verified that only 100 gold is pulled from my account. 

For the health potion the popup shows that I am charged 28 gold 42 silver. The rewards column price shows a cost of 25 gold as expected. I have verified that only 25 gold is pulled from my account.

So while I am not actually being charged extra, the notification is inaccurate.

**Comment by Alys** [comment]
@peregra Thanks for the details, especially the part about how it's only the notification that's inaccurate! I've copied your comments to https://github.com/HabitRPG/habitrpg/issues/4113 where we're tracking this issue.

We're not sure what causes it, so I'm afraid I can't give you any information about a fix for it yet. :(
