### ISSUE TITLE
Firebase questions

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5891]
- [ ] When user is deleted from Habitica -> delete on firebase too -> what about old messages?
- [ ] When group is deleted from Habitica -> delete on firebase too -> what about old messages?
- [ ] Handle firebase synchronization errors? or just fire and forget?
- [ ] Handle firebase authentication state changes?
- [ ] What happens if an operation is sent before firebase is authenticated on the server?
##

**Comment by Alys** [comment]
When a user is deleted from Habitica, their messages should remain, with
their name still on them. They'll often be part of conversations, so later
messages will not make as much sense without them.
