### ISSUE TITLE
Guild Invite Doesn't Disappear, Can't Receive Party Invites -- Guild Invite goes into Party Invite Object

### ISSUE THREAD

**Issue by PendragnJenna** [HabitRPG/habitica#5892]
I'm submitting this on behalf of Merepersiflage (1194253a-d3c7-420f-8c86-ba399fdd59fb), who's a fairly new user. The other day, I (PenDrag'n e77d6c97-8850-4f31-bd46-c412243d6035) invited her to a private guild. She's accepted the invite, but it still appears in her Notifications tab and when she clicks on the Guilds tab. When she clicks to accept the invite again, it says she can't join a group to which she isn't invited.

Meanwhile, I'm also trying to invite her to join my party (Doom Busters b4b6ac39-43c5-4374-8d4b-ac8d153e38be), but it won't let me send the invite because it says she already has one outstanding. When she looks at her account, however, she has no party invite, just the persistent invite to the private guild to which she's already a member.

@Alys is this something you can fix from your end? If not, can you please provide some guidance that I can pass along to her? Thanks!
##

**Comment by Alys** [comment]
@PendragnJenna I've deleted the invitation from her account. She should no longer see it and should be able to accept party invitations now, although she might need to reload first.

For admin reference:

Her account contained the details of the guild (I confirmed it is a guild) in the party section of the invitations object:

```
    "invitations" : {
        "party" : {
            "name" : "Name of Guild",
            "inviter" : "e77d6c97-8850-4f31-bd46-c412243d6035",
            "id" : "1a11bc7c-f2e8-4276-91ea-0c8b063e225c"
        }
    },
```

**Comment by PendragnJenna** [comment]
Thank you, @Alys -- all is well now!

**Comment by PendragnJenna** [comment]
@Alys And now it looks like it's happening to her again. We're switching parties, and even though she's left the other party, it says Invite Pending when I try to invite her to the new one (09d91c4f-c632-4bd4-b39f-d10295a4777f). Not sure if this is a contributing factor, but in the private CR Writers Guild (1a11bc7c-f2e8-4276-91ea-0c8b063e225c), she's showing as both a member and pending. So maybe that pending invite is what's causing everything else to get stuck...? Thanks!

**Comment by Alys** [comment]
I'm sorry about this @PendragnJenna! You should be able to invite her to the party now.

You are correct about the CR Writers Guild. She was a member but was still in the invitations list, and in her user account, an invitation for that guild was in both her party and group invitation (details below for devs). I've removed all of that incorrect data.

```
from user document:
    "invitations" : {
        "party" : {
            "name" : "CR Writers Guild",
            "inviter" : "e77d6c97-8850-4f31-bd46-c412243d6035",
            "id" : "1a11bc7c-f2e8-4276-91ea-0c8b063e225c"
        },
        "guilds" : [
            {
                "id" : "1a11bc7c-f2e8-4276-91ea-0c8b063e225c",
                "inviter" : "e77d6c97-8850-4f31-bd46-c412243d6035",
                "name" : "CR Writers Guild"
            }
        ]
    },
```

```
from group document:
    "invites" : [
        "1194253a-d3c7-420f-8c86-ba399fdd59fb"
    ],
    "members" : [
        "e77d6c97-8850-4f31-bd46-c412243d6035",
        "1194253a-d3c7-420f-8c86-ba399fdd59fb"
    ]
```

**Comment by PendragnJenna** [comment]
@Alys I still can't invite her. And when I look at the member list in the CR Writers Guild, it still shows as her being both a member and pending. Does something need to be changed on my account, as well? Thanks!

**Comment by Alys** [comment]
Sorry @PendragnJenna. I probably just created the database commands but didn't actually run them or something stupid like that. I was a bit short on sleep this morning. :-/  I'll check this out as soon as I get home from work in about six to eight hours.

**Comment by Alys** [comment]
@PendragnJenna I've cleared out all the invitations from her account and from the CR Writers Guild. I'm not sure if I didn't do it properly earlier today or if something put some of the invites back - we have seen odd behaviour in the past where invitations are very persistent.

Please reply again if you still have trouble.

**Comment by PendragnJenna** [comment]
@Alys Thank you! I was able to send the invite, so I'm assuming it's all been fixed.

**Comment by PendragnJenna** [comment]
Hi, @Alys -- I'm really starting to wonder if this is a problem with my account somehow. I invited Poisontaster (d213b138-4f0e-4383-83aa-87fb13e0e72f) to my party (09d91c4f-c632-4bd4-b39f-d10295a4777f), and now she's also showing up as being both a member and still invited. I'm guessing this is going to cause problems when we start a quest and I try to invite her to join it...?

**Comment by SabreCat** [comment]
@PendragnJenna : If Poisontaster is in the party and can see the other members, chat, etc., then you'll be fine. There's occasionally an issue where somebody stays in the invite list even after they've joined.

**Comment by Alys** [comment]
@PendragnJenna I've removed the party invitation from your party and from Poisontaster's account (double-checked and they're definitely gone). However we have seen in other issues that they can come back, possibly because of browser caching of invitation data, so let me know if they reappear. As SabreCat says, the invitations won't cause any harm (unless Poisontaster wants to leave and join another party).

**Comment by PendragnJenna** [comment]
Thanks, @Alys -- I appreciate it!

**Comment by Nate-Clark** [comment]
Hello @Alys, I think we are experiencing a similar problem. I was invited to a quest by "maera", but before I accepted, she changed her name to "elf arrow". Whether because of that or something else, I can neither accept nor reject her invitation. I get the error "Group not found". And it seems to not want me to start or accept another quest until that invitation is taken care of. So we seem to be stuck. Can you help?

**Comment by Alys** [comment]
@Nate-Clark I'll need to know your User ID. Can you please go to Help -> Report a Bug from the Habitica website and see step 6 for information about how to find your User ID?

**Comment by Nate-Clark** [comment]
f60a8883-bc41-4092-8ae1-b319d1e3cd62

**Comment by Alys** [comment]
@Nate-Clark It looks like the invitation has disappeared by itself. Comment here again if you're still having trouble.
