### ISSUE TITLE
D&D/RPG themed notifications for events/activtiy

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#59]
_Edited by wc8: Vote for this feature here: [Awards and Badges](https://trello.com/c/4uWICvDf)_

I think small one line D&D/RPG themed notifications for completed tasks, lost HP, rewards, etc would be a great way to add flavour to the game. Where possible a it of humour would not hurt.

To ensure the notifications relevance there could be a way of detecting key words in a task/habit, an event type parser and a pool of notifications that the key words/event applies to to randomly select from.

Some examples for how these could be coded are:
- Todo completed with "dishes" in the title = "Dishes wiped out by Tyler's Bastard Sword Attack".
- Todo not completed with "dishes" in the title = "Dishes taunt Tyler for -1HP".
- Habit "plused" with "exercise" in title = "Tyler can almost see the outline of a bicep". (lower levels)
- Habit "minused" with "exercise" in title = "The dumbbells of destruction have stared down Tyler for -2HP".
- Daily completed with "drink water" in title = "Tyler teaches Thor a lesson in Skulling"
- Daily not completed with "drink water" in title = "Tyler's thirst for water saps -1HP"
- Daily not completed for fifth day in a row with "drink water" in title = "Tyler's parched lips are cracking"

Death notifications could be quite fun.
- The Legendary slayer of a thousand foes, Tyler The Awesome now lies on the battlefield bleeding out. With his last thoughts he asks himself... "Why did I not raise that ticket with HabitRPG for notifications".
- It is the only death I know caused by failing to "Adhere to budget". Didn't see that one coming.
- Death by Tooth Decay. In the next life our hero will remember to "Brush twice a day, not just mornings".

Levelling notifications should be a combination of motivational with some humour. A good example are the Oblivion levelling messages at http://www.uesp.net/wiki/Oblivion:Leveling#Messages.

Additional notifications for deadlines approaching when due dates are implemented would be helpful.

Reading all of these in an activity log would make for an interesting past time as you recall your day's/Week's/Month's/Year's progress.

**Comment by lefnire** [comment]
Brilliant. I'll keep this around for when the time comes.

**Comment by hookang** [comment]
Love this idea. Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
[Trello 19 Awards and Badges](https://trello.com/c/4uWICvDf)
