### ISSUE TITLE
Can't leave a single member party

### ISSUE THREAD

**Issue by mxrowanthomas** [HabitRPG/habitica#5905]
Bug Report, on attempting to leave a party with a single member, whether created by that member or not we receive the following error:

Please reload, "Error User is not defined" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

This persists across reloads, and appears via both Chrome standard and Waterfox (a 64 bit build of firefox) on the Windows 10 system, and Firefox and Chrome on Mac 10.10.

Our user details are as follows:

Win 10 User: User ID: 88381d15-0639-4e53-aa13-6f095cc164a8
Party ID: 29737661-01bb-4505-8b5a-af6aa1c7a924
Mac User: User ID: c03e41bd-501f-438c-9553-a7afdf52a08c
Group ID: 26224704-ef8d-475a-88ab-e14893c4903f

In chrome, I am seeing the following console errors on the Win 10 machine:

When first loading the page:

```
ping?client_id=172525162793917&domain=habitica.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1 Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
```

When attempting to leave the party:

```
POST https://habitica.com/api/v2/groups/29737661-01bb-4505-8b5a-af6aa1c7a924/leave?keep=keep-all 500 (Internal Server Error)(anonymous function) @ app-65608fa9.js:6s @ app-65608fa9.js:6a.$get.f @ app-65608fa9.js:6j @ app-65608fa9.js:7(anonymous function) @ app-65608fa9.js:7a.$get.j.$eval @ app-65608fa9.js:7a.$get.j.$digest @ app-65608fa9.js:7a.$get.j.$apply @ app-65608fa9.js:7(anonymous function) @ app-65608fa9.js:8o.event.dispatch @ app-65608fa9.js:2o.event.add.r.handle @ app-65608fa9.js:2
app-65608fa9.js:36 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}
```

(This appears when clicking the 'confirm' button)

**Comment by Brenstem** [comment]
I'm having the same problem as you are, hoping someone comes with a fix soon.

**Comment by paglias** [comment]
@mxrowanthomas @Blackeagle3 we're sorry about this! we've just fixed the bug, if you try again it should work
