### ISSUE TITLE
Updating Press Kit

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#5906]
The press kit is a bit out of date since the rebrand.

 We need to remove the following:
- old logo 
- Computer with old app
- postcard that says "HabitRPG"
- both old app screenshots

I am attaching some images that should be uploaded in their stead:

![basi-list_promo](https://cloud.githubusercontent.com/assets/3494081/9773888/fb39dd10-56f9-11e5-9c93-87c51a19dee1.png)
![drog_on_battle_pig_by_cosmic_caterpillar-d8dqeuh](https://cloud.githubusercontent.com/assets/3494081/9771897/d0e09628-56ed-11e5-9d7c-bcf3328eca0c.png)
![habitica_wordmark](https://cloud.githubusercontent.com/assets/3494081/9771983/5a41a0ba-56ee-11e5-8667-33dd4d1438f3.png)
![habitica_lockup](https://cloud.githubusercontent.com/assets/3494081/9771984/5a4f9526-56ee-11e5-9340-b1bc9d7c4a3b.png)
![gryphon_logo](https://cloud.githubusercontent.com/assets/3494081/9772053/c0d08ecc-56ee-11e5-9c51-8b332da9f0d6.png)
<img width="480" alt="screen shot 2015-08-31 at 1 41 54 am" src="https://cloud.githubusercontent.com/assets/3494081/9773789/59ece006-56f9-11e5-890f-1e37005a2ff1.png">
![gryphon-purplef8](https://cloud.githubusercontent.com/assets/3494081/9773790/5a3421dc-56f9-11e5-9ee9-eb54f750e384.png)
##

**Comment by crookedneighbor** [comment]
I'll work on this.

**Comment by crookedneighbor** [comment]
Whoops. I never did this :grimacing:

**Comment by Bunjl** [comment]
I could do this.

**Comment by Alys** [comment]
@Bunjl  Thank you! That would be lovely!

If you run into problems or have questions, you're welcome to ask questions here.

**Comment by lemoness** [comment]
Looks like this has been done except for the Basi-list, which still needs to be added. However, we'd like to add the following iOS screenshots as well:

![en-us-iphone5-0-dailies-portrait](https://cloud.githubusercontent.com/assets/3494081/11050152/5587d51e-86f8-11e5-8a83-89a76c829d87.png)
![en-us-iphone5-1-levelup-portrait](https://cloud.githubusercontent.com/assets/3494081/11050148/557827a4-86f8-11e5-801c-1095b35ed3c9.png)
![en-us-iphone5-2-pets-portrait](https://cloud.githubusercontent.com/assets/3494081/11050150/5586f496-86f8-11e5-8348-b4d6879b20e4.png)
![en-us-iphone5-3-party members-portrait](https://cloud.githubusercontent.com/assets/3494081/11050151/5587416c-86f8-11e5-8578-b8a2ecf263bf.png)
![en-us-iphone5-4-quest details-portrait](https://cloud.githubusercontent.com/assets/3494081/11050149/55859574-86f8-11e5-9804-8790b29ae8f1.png)

**Comment by danielvancamp** [comment]
Hey guys, 

I could help with this one as well. Just downloaded the presskit to get the logo from it. Seems there is one low res screenshot as well. I could replace this too if you like : 
- Tasks Page.png
  ![tasks page](https://cloud.githubusercontent.com/assets/8830345/11373341/14f90ca8-92d2-11e5-8b59-181d1af1816b.png)

So the tasks that need to be done here are : 
- Add IOS screens
- Get file names structured (useful?)
- Add Basi-list (this one is in there already?)
  ![basi-list](https://cloud.githubusercontent.com/assets/8830345/11373431/94693e68-92d2-11e5-96a6-6588a6482193.png)
- Update Tasks Page.png (useful?)

Let me know!
Cheers!

**Comment by librarianmage** [comment]
@Alys @lemoness Is there anything that needs to be done currently?

**Comment by Alys** [comment]
Yes, the items in lemoness's comment from Nov 10, 2015 need to be done, with all images being in the zip file and on the page at  https://habitica.com/static/press-kit

@danielvancamp I'm sorry we didn't reply to your question. Do you still want to work on this?

It's probably best to not change any existing file names, because that could cause problems for people who are already using the press kit. New file names can match the existing ones, where possible.

**Comment by librarianmage** [comment]
@Alys I can work on the comment made by lemoness.

**Comment by danielvancamp** [comment]
Hey guys,

@MathWhiz go ahead, let me know if i can assist you in any way.

Cheers

**Comment by librarianmage** [comment]
@danielvancamp Ok, I'll get right on it!

**Comment by librarianmage** [comment]
@Alys @danielvancamp So what I need to do is:
- [ ] Add ios screenshots (File names?)
  - [ ] to .zip
  - [ ] to folder
- [ ] Replace Tasks Page.png (Higher-res?)

Note: while the Basi-list is in the folder and the .zip, it does not show on the website.

**Comment by Alys** [comment]
@MathWhiz Sorry, we seem to be appallingly bad at replying to questions on this issue. :(

Yes to adding the iOS screenshots to both the zip and folder. Choose file names that follow any conventions that already appear in the zip file (there might be two or more conventions; if so, just choose any one of them).

Also make it so that the Basi-List image does appear on the website.

You can start on those now if you wish.

@lemoness Do you want a high-res version of Tasks Page.png to be used? That's the image shown in this comment: https://github.com/HabitRPG/habitrpg/issues/5906#issuecomment-159330810

**Comment by librarianmage** [comment]
@Alys Okay, I will get right on it.

**Comment by librarianmage** [comment]
### Progress:
- [ ] Add iOS screenshots
  - [ ] to presskit.zip
  - [ ] to presskit folder
  - [ ] to press-kit.jade (show up on website)
- [ ] Add Basi-List.png to presskit page

@Alys

**Comment by lemoness** [comment]
Yes, a hi-res version would be great!

**Comment by librarianmage** [comment]
@Lemoness @Alys Ok! Will do (hopefully done this weekend)

**Comment by lemoness** [comment]
Can we also add the following images?
![Uploading HabiticaiOSLogoIcon.png…]()
![habitica_icon_logoandroid](https://cloud.githubusercontent.com/assets/3494081/13193021/3835c82a-d727-11e5-890e-70784baec698.png)

**Comment by lemoness** [comment]
![habiticaioslogoicon](https://cloud.githubusercontent.com/assets/3494081/13193025/47b51c38-d727-11e5-87ee-468f93dc57c3.png)

**Comment by librarianmage** [comment]
@Lemoness Sure!

**Comment by librarianmage** [comment]
@Lemoness should I also rename the images under a unified naming convention?

**Comment by lemoness** [comment]
Yes, that would be fine!

**Comment by librarianmage** [comment]
@Lemoness Awesome!

**Comment by librarianmage** [comment]
@Alys @lemoness Not sure if it is different, but should I add screenshots of the new Android app?

**Comment by librarianmage** [comment]
@Alys Should I split the images into folders, i.e.
-  Logos / Promos
- Sample Screens
- Bosses

?

**Comment by Alys** [comment]
I like that idea, but it's not up to me. @lemoness ? Is there any reason to keep the press kit as similar as possible to its current state, or can we make large improvements?

**Comment by librarianmage** [comment]
@Alys @lemoness In the Jade Template that displays the press kit, there seems to be unused code for a carousel:

```
 //-#carousel.carousel.slide(data-ride='carousel')

    ol.carousel-indicators

      each img, i in imgs

        li(class=i==0?'active':'', data-target='#carousel', data-slide-to=i)

    .carousel-inner(role='listbox')

      each img, i in imgs

        .item(class=i==0?'active':'')

          img(src="/presskit/#{img}.png")

          //.carousel-caption=img

    a.left.carousel-control(href='#carousel', role='button', data-slide='prev')

      span.glyphicon.glyphicon-chevron-left(aria-hidden='true')

      span.sr-only= env.t('previous')

    a.right.carousel-control(href='#carousel', role='button', data-slide='next')

      span.glyphicon.glyphicon-chevron-right(aria-hidden='true')

      span.sr-only= env.t('next')

```

Is it still needed?

**Comment by librarianmage** [comment]
@Alys @lemoness Also, the code only looks for `.png`s, but some of the images are `.jpg`. Any thoughts on how I should resolve it?

**Comment by librarianmage** [comment]
What I did was convert all of them into `.png`s

**Comment by librarianmage** [comment]
Can this be closed?
