### ISSUE TITLE
Reloading Tasks Page Resubmits Hours Of Data

### ISSUE THREAD

**Issue by aeridus** [HabitRPG/habitica#5908]
User ID: 844497bd-ff23-4c76-ae9f-1f593929ba6e
Browser: SRWare Iron (Chrome Knockoff)
OS: Windows 7 64-Bit

When I woke up this morning I saw my dailies had not reset yet, so I tried reloading the Tasks page. Somehow this caused many of the +/- clicks I did yesterday to re-submit, causing a huge chunk of my health to disappear. Also, there seems to be no way to undo mistakes. I just created a new account a couple days ago and there were a lot of mis-clicks while I was getting used to the system.

**Comment by Alys** [comment]
When changes that you made recently are reapplied, it's an example of this issue: #4313 The bug also (more commonly) causes actions you took in the past to be undone. What's happening is that your browser is holding on to the actions that you took without properly syncing to the server and then later when a sync happens, it either resends the same data that it had already applied (in your case) or loses the data (causing actions to be undone). 

I'm very sorry about the inconvenience! If you look at that issue, you'll see an Advice section near the top (that's really the only part you need to read). Point 2 will tell you how to recover from the unfair health loss, using [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values). You can also use that tool to undo the effects of mistakes (e.g., remove some XP if you clicked a positive Habit by accident).

Comment here if you have any questions!

**Comment by aeridus** [comment]
Thanks!! I appreciate the help.
