### ISSUE TITLE
Keep getting damage form boss even though the day isn't done yet

### ISSUE THREAD

**Issue by afrozenflower** [HabitRPG/habitica#5910]
So I am in a party and we are fighting a boss. So just as usual the day ended and I did my damage, and then after a couple of hourse I remembered that there was a daily I forgot to check, so I went to restore the streak. This happened:
![capture](https://cloud.githubusercontent.com/assets/14225676/9802835/812a45d0-581d-11e5-89dc-63a98b97c01a.PNG)
And me and all the other members in the party died.
And today it happened again. It is a little over 12 AM here and I checked one daily and it happened again.
![jt](https://cloud.githubusercontent.com/assets/14225676/9802859/b6f1b6b2-581d-11e5-8b16-2b9ac7bb36b9.PNG)
I don't understand what it keeps happening.
I am using Google Chrome. My API is: 48ee0fd0-9dc5-497c-a215-9618b352b25a.
and the Group ID is:  43ea0101-b99d-499d-b63d-f6b2546fcb98

**Comment by Alys** [comment]
Are you using Habitica on two different devices (PCs, mobile phones, tablets, etc)?

If so, please check carefully to ensure that both the time and timezone are identical on all devices you use it on.

Let us know whether the time and timezone are identical or not.

**Comment by afrozenflower** [comment]
Both have the same time (12:50 AM), but Habitica automatically adds one hour. That is because where I live (Egypt) is GMT +2 and usually adds another hour in the summer. But the thing is, this didn't happen this year,  so instead of being GMT +3 like every summer, we are back to normal. But the automatic internet-provided timezone is still GMT +3, so I changed on my PC and on my phone.

**Comment by afrozenflower** [comment]
I learnt to adapt and I try to check off my dailies before 11 PM (which would be 12 AM in Habitica) but I don't understand why it would be a problem here, because now it is 12:54, which means it is 1:45 according to Habitica, so the day is still starting.

**Comment by Alys** [comment]
Habitica never adds an hour. It goes by exactly the time and timezone set on your own devices.

If you have changed the time/timezone on your devices, then the change might not have been made identically on all of them, and this would cause cron to run twice.

Please check carefully to ensure that both the time and timezone are identical on all devices you use Habitica on.

**Comment by afrozenflower** [comment]
The internet-provided timezone for Egypt is GMT+3, because of the summer time. But here we don't use that, so it GMT +2. The time on my PC and mobile now is 1:04 AM (I changed them both when summer started) while if I use the autmatic one from the internet, it would 2:04 AM. 
I got that Habitica used the automatic timezone from the internet, so that is why I check my dailies before 11 PM.

**Comment by Alys** [comment]
No, Habitica does **not** use the timezone from the internet. It uses the timezone (and time) set on your PC and on you mobile phone / tablet.

If the timezone is set differently on your devices, then two crons a day can occur because Habitica uses the different timezone on each device. Your devices do not necessarily use the automatic timezone from the internet. It's important that you check exactly which timezone your devices are configured to or you will keep getting double crons.

**Comment by afrozenflower** [comment]
Okay I checked again and apparently on my phone I unchecked the "automatic time zone" option but didn't actually change the time zone, so that might be why. 
I will see if the problems occurs again tomorrow. Thanks for your help and sorry for bothering you. :)

**Comment by Alys** [comment]
No worries. :)

**Comment by Alys** [comment]
@afrozenflower I'm closing this issue now but please do comment here if you still need help with this! We'll still see your comment and we'll keep helping you.
