### ISSUE TITLE
Jumbled images

### ISSUE THREAD

**Issue by GrayDays** [HabitRPG/habitica#5911]
Like a bad penny, what I assume is that intermittent spritesheet issue in mobile Safari has returned. This time it's affecting avatars, gold/silver graphics, NPCs, and most items other than hatching potions.

http://i.imgur.com/RrjKBlh.jpg
http://i.imgur.com/NjLSxbs.jpg

**Comment by crookedneighbor** [comment]
Ugg. Thasks for reporting it. We'll need to adjust the count on the grunt file again :/

Should really write a test to check the dimensions of the compiled images.
