### ISSUE TITLE
Warning when browser has Javascript disabled?

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica#5913]
Not sure how often this comes up, but when Javascript is disabled, the site is very broken. 
![screen shot 2015-09-10 at 11 14 40 pm](https://cloud.githubusercontent.com/assets/6760632/9808231/479ec35a-5812-11e5-8423-a14f55bc803c.png)

Which is to be expected, since it runs on AngularJS.

Facebook also needs Javascript to run properly, so when you have Javascript disabled and try to to go Facebook.com, the following screen appears:

![screen shot 2015-09-10 at 11 15 18 pm](https://cloud.githubusercontent.com/assets/6760632/9808291/ca2d1b1e-5812-11e5-86f5-7783f4f18b9f.png)

Was wondering if something like that might be useful for Habitica?
##

**Comment by passerinea** [comment]
The login screen is JS-based as well, so you cant even login if JS is disabled! An error message there would be super helpful too.

Definitely seconded that an error page would be a great addition.

**Comment by benaubin** [comment]
Try something like: `<noscript><!-- Error Message --></noscript>` if Habitica is not pre-rendering the page, then that will show instead of the page itself.

**Comment by Alys** [comment]
@AnitaYCheng or @lemoness If this is still desired, would you like to mock up what it should look like?

**Comment by lemoness** [comment]
I think that we can start with a straightforward warning. Something like:

Alas! Your browser doesn't have JavaScript enabled, so Habitica can't
properly display the site. Enable JavaScript to continue!

We can also have a cute picture, such as this one:
https://trello-attachments.s3.amazonaws.com/52e9d25cd467121630c6350d/52ec8ff45478b402281557b7/150x150/cf8e7db9bca60c76fca5723ec5e4ee2d/coding_3_by_phoneix_faerie-d7idtti.png

**Comment by benaubin** [comment]
Love that picture!
