### ISSUE TITLE
To-Do list doesn't preserve sort

### ISSUE THREAD

**Issue by MaidM** [HabitRPG/habitica#5921]
I have a massive list of to-do items, some with dates, some not, some tagged, some not, and with a variety of difficulty levels.  I keep trying to put them in date order (in terms of due dates and for non-dated items, roughly when I expect to get to them).  Whenever I add a new item or take other actions (not sure which actions), the whole list drops the sort order that I so painstakingly put in place and reverts to its original order.  This is incredibly frustrating.  If it's too complicated in the short term to make it save as I make changes, then please just give me a save button or something that lets me confirm the order I want my items in.

**Comment by crookedneighbor** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/2606 for how to solve this problem.

We're working on a fix so this work-around won't be necessary, but it's a big project.
