### ISSUE TITLE
Error message when attempting to send private message

### ISSUE THREAD

**Issue by stawberri** [HabitRPG/habitica#5923]
I tried sending a private message to Alys today (before I was told that support via PM is discouraged), and a red message appeared on my screen, stating

> Please reload, "Error Validation failed" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

After I saw this, I tried sending it again, only to see the same message again. I was getting extremely confused, so I stopped trying to send them and returned to trying to use "The Newbies" guild chat to ask for help instead. However, a little later, I noticed that the message I tried to send did appear inside of my Inbox, twice (because I tried to send it twice).

Since Alys asked about the error message in "The Newbies" afterward, I sent a test message once again and confirmed that the error was still popping up. The test message also appeared inside of my Inbox, but I have no idea if Alys received it or not.

```
Me: a1d4a7da-835c-4a75-96e3-39a5af78e578

Browser: Google Chrome Version 45.0.2454.85 m
Operating System: Windows 10 Pro

Error message (during my message sending attempt):

POST https://habitica.com/api/v2/members/d904bd62-da08-416b-a816-ba797c9ee265/message 500 (Internal Server Error)
Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}config: Objectcached: falsedata: Objectheaders: Objectmethod: "POST"transformRequest: Array[1]transformResponse: Array[1]url: "/api/v2/members/d904bd62-da08-416b-a816-ba797c9ee265/message"__proto__: Objectdata: Objecterr: "Validation failed"__proto__: Objectheaders: (c)arguments: (...)caller: (...)length: 1name: ""prototype: Object__proto__: ()<function scope>status: 500statusText: "Internal Server Error"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
```
##

**Comment by Alys** [comment]
Thanks for reporting this, @stawberri! 

I didn't receive any of the messages. 

I've just tried sending a message from a test account to my "Alys" account and that worked, so this isn't a site-wide problem, fortunately.

Could you please reload the Habitica site and try once more?

**Comment by stawberri** [comment]
I tried using incognito mode and even Firefox, and it still hasn't worked. :confused:

What's really weird is that the messages in my Inbox don't look like local caching, because I could see my Chrome incognito mode messages in Firefox and my Firefox messages in Chrome.

```
Firefox 35.0
Windows 10 Pro

Object { data: Object, status: 500, headers: tc/<(), config: Object, statusText: "Internal Server Error" } app-65608fa9.js:36
```

![My Inbox](https://cloud.githubusercontent.com/assets/9897819/9835666/ef398804-59aa-11e5-80cd-cb723d5720aa.png)

**Comment by stawberri** [comment]
I decided to try sending a message to another person to see if it would work, and it did, so it seems to be specific to me sending messages to Alys only. :confused:

![More message attempts](https://cloud.githubusercontent.com/assets/9897819/9835691/b0ee709e-59ac-11e5-9038-21bd3a346106.png)

My message to Avia worked, but I still got an error when trying to send a message to Alys.

```
Other person: 92be6f19-d30a-41b6-8c99-00db733a5172
```

**Comment by Alys** [comment]
@stawberri I'm so sorry, we never got back to you about this! I'm wondering if there was some weird caching of data related to messages specifically to me (e.g., maybe the first message failed due to a temporary glitch but then the corrupted version of the message hung around to corrupt all future attempts). That's wild speculation though. If it's at all accurate, then the caching has probably cleared itself by now. I would be interested to know if you're now able to send a PM to me, if you don't mind testing again.

**Comment by stawberri** [comment]
It looks like it worked! If you received my message, I guess that means you're right! :smile:

**Comment by Alys** [comment]
@stawberri I did! Thank you very much for testing again!
