### ISSUE TITLE
Audio Volume

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitica#5924]
http://danielstern.github.io/ngAudio/#/
Would this be a good option for volume control?

The only reason i never use the audio is that there's no way for me to control the volume for just habitrpg alone, and end up getting blasted after listening to just about anything else first and then doing a task.

I've been using habitrpg for a 5 year old, and I thought the audio might make habitrpg more interesting.
##

**Comment by crookedneighbor** [comment]
That looks good to me. :+1:

**Comment by crookedneighbor** [comment]
*looks not lols

**Comment by SabreCat** [comment]
There was also some discussion of normalizing the audio levels of the themes on the site. Are we tracking that issue already?

**Comment by bennyty** [comment]
@SabreCat I'm looking to help with Habitica and I know Audacity well enough to use the audio normalizing filter. To what level do you want the sound normalized?

EDIT: I've been doing some reading and there are programs that analyze more than the peak audio. They look at how the whole audio piece will sound to the human ear and try to balance around that. While I realize this is less important for the short sound effects we have, I have just run the algorithms over the sound effects in common/audio and the results seem impressive enough.

**Comment by SabreCat** [comment]
@bennyty: That sounds great, no pun intended! Could you submit the modified audio files in a pull request so we can all have a listen?

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer be relevant afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This isn't a current need, so I'm closing this for now. We can always reopen if necessary.

**Comment by Etherfly** [comment]
I'd like to highlight that this is still a problem with the website that needs solving.
https://www.reddit.com/r/habitica/comments/n1mxvd/how_do_i_turn_the_sound_down/

I personally feel that the volume is too high for most sound themes, and the only theme that I currently find okay in terms of volume is the LuneFox's theme. All others blast twice as loud and way louder that everything else I might have in the browser.
