### ISSUE TITLE
Stealth did nothing

### ISSUE THREAD

**Issue by joshutt** [HabitRPG/habitica#5925]
Yesterday I cast stealth.  I had two unchecked dailies left at the end of the day.  I came back today and had taken hit points for both tasks, my streaks were reset and my mana was gone (so I know the spell had been cast).  But it looks like casting did absolutely nothing.  This is not the behavior I've seen in the past.

User id: 1c530473-2c9f-4300-a01a-40307dd97a30

**Comment by Alys** [comment]
@joshutt I'm sorry about this! Sometimes a bug occurs where an action is only partially saved. It's probably an example of https://github.com/HabitRPG/habitrpg/issues/4313

There's an advice section near the top that will tell you how to recover from the unfair damage.

If you want to be sure that Stealth has been cast successfully, you can go to the Data Display Tool (from the habitica.com website's Data menu) and look at the "Dailies Incomplete" section. If you've cast Stealth, there'll be a column that shows which Dailies are stealthed and which are not. That tool takes its data directly from Habitica's database, so if you see that your Dailies are stealthed there, you can be certain that they really are.
