### ISSUE TITLE
Quest completed but party members did not receive rewards

### ISSUE THREAD

**Issue by jrenee25** [HabitRPG/habitica#5926]
My party just finished the "Moonstone Chain Part 1" quest, but none of our party members got any rewards.  I was the person who started the quest and when I look at my Quest tab, I no longer see this quest listed as being available.  Can you please assist?  I have attached a screenshot of the message in the Party thread that states that the quest was completed.

Party ID: 7297fa28-47f8-4ea8-8b35-f451102cdf9e
![completed quest screenshot](https://cloud.githubusercontent.com/assets/12550635/9837731/7e5ed6b6-5a0e-11e5-90ee-b3698700b642.jpg)

**Comment by Alys** [comment]
@jrenee25 Sorry about that! It tends to happen when collection quests finish in very large parties.

I've given the quest rewards to all members of your party.

**Comment by jrenee25** [comment]
@ Alys, thank you so much for fixing this.  However, my party has a new issue related to this quest.  Because our Party leader has abandoned the party, party members voted to all leave the team after this quest ended and then join a new party that one of our active members is going to create and manage.  However, since this quest didn't conclude properly, none of us can leave the party.  When we click on the "Leave" button and select an option to keep or discard the party challenges, we get an error message that says that we cannot leave while in a quest.  Here's a screenshot:
![cannot leave party](https://cloud.githubusercontent.com/assets/12550635/9838987/ceca7060-5a31-11e5-83c4-276683e3392e.jpg)

**Comment by Alys** [comment]
Sorry about that! Can you try again now please?

**Comment by jrenee25** [comment]
Never mind, I think I figured it out.  I simply started a new quest then immediately canceled it, and then I was able to leave.  I PM'd the other team members and told them it worked.
