### ISSUE TITLE
i love this app the only issue i have is i cannot set a time for the to dos task!!!!!

### ISSUE THREAD

**Issue by rdeaton8** [HabitRPG/habitica#5927]

**Comment by rdeaton8** [comment]
When a had a new task and click to set a due date, it says 0NaN-NaN-NaN and I cannot set a date or time

**Comment by rdeaton8** [comment]
That should say when I  add a new task...

**Comment by Alys** [comment]
If this is for the iOS "Habitica" app (which has a purple gryphon as a logo), please use the in-app bug report form under Menu > About > Report a Bug. That will send relevant information about the bug to the developers which will help them solve it faster.

If it's for the old iOS "HabitRPG" app (which has a brown chest as a logo), it's recommended that you use the Habitica app instead. It's has better performance and more features.

If it's for the Android "HabitRPG" app (which has a brown chest as a logo), I'm sorry about the inconvenience! We're creating a new app for Android which will have this bug removed.

**Comment by Alys** [comment]
Also note that if you can't set the date on the app, you can use the website at https://habitica.com - it works in most mobile browsers, and PC browsers of course. Date setting will work in the website.

It's not possible to set a time for a task, only a date.
