### ISSUE TITLE
Missing/Wrong link in faq.json

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5928]
In the new `faq.json` file, the string `iosFaqAnswer10` contains the following markdown text: [...]`Subscribe on the [website](link) and unlock the ability`[...], while it should certainly be [...]`Subscribe on the [website](https://habitica.com/#/options/settings/subscription) and unlock the ability`[...]
##

**Comment by librarianmage** [comment]
Has this been taken care of?

**Comment by Alys** [comment]
Yes, thanks!
