### ISSUE TITLE
Quest leader Inactive, Can't start Quest

### ISSUE THREAD

**Issue by P33bs** [HabitRPG/habitica#5930]
The quest starting member was inactive for a very long time so they were booted from the party. No new quest leader was assigned and now we cannot start a new quest or cancel the current one. Group ID is: b58e0cb1-c6e1-4936-8519-aba1dbdb0fc1

**Comment by crookedneighbor** [comment]
I've reset the stalled quest.

**Comment by katieshmatie** [comment]
I have a similar problem. Our quest leader has gone inactive, and all party members except one have accepted. The remaining member is inactive as well, so we're stuck waiting for one of them to log back in (I don't want to boot them from the party). I'm trying to find the correct forum to request an admin to cancel the quest invite so an active member can start up a new quest.

Group ID is 05e7137d-b3fd-4c69-8106-54983903f2c1

**Comment by Alys** [comment]
@katieshmatie This is the correct place to post, as we advised you in the Newbies guild. I've deleted the quest from your party.
