### ISSUE TITLE
major health loss / experience change overnight

### ISSUE THREAD

**Issue by ellem-0** [HabitRPG/habitica#5931]
user id: 3b4c0d6b-1618-45e5-bf59-4b760cd5955c

This morning when I opened Habitica (in Firefox, most likely the latest version, on Windows 7) I found that I had lost most of my health and gained almost a full bar of XP. This surprised me, for I'd completed most of my dailies. Also, I shouldn't be gaining XP just for logging in... 

Stranger still, I am now level 14. Yesterday (after using a skill which gave me loads of XP), I leveled up to 15 - I'm sure of this, for I recall getting my first quest scroll. Today, it's gone.

The data display tool shows the right dailies as having been completed.

I think the amount of health and experience (but not the level) are roughly appropriate for what my stats would have been if I had not used the skill which leveled me up (and thereby refilled my health and emptied my XP bar).

possibly relevant details:
- the previous time I logged in was on the same computer, using the same browser, roughly 16 hours earlier
- the bubbles showing the health loss / XP gain did appear, but they're always gone in a flash - I never manage to read them properly
- I did not get the 'you ran out of health' message, so I don't think I 'lost' a level, the database simply forgot I ever earned it
- I have not observed any changes to my gold, but I might not have noticed them
- my mana is full (at 62/62), which is probably incorrect (since I used a skill yesterday)
- I'm not in a party
- both the health loss and XP gain are more than all of my dailies put together are worth (so an extra cron wouldn't explain this - I'd need several)
- when I logged in, none of my dailies were checked (so that's normal), unlike with the "two versions of your data" bug (which I've experienced in the past)
- I found my first quest scroll yesterday

All told, I think it would all make sense if my use of Burst of Flames somehow got canceled - but I saw it take effect.

I'm not sure I pressed the Sync button before closing the browser, but I guess I'll be more careful in the future...

**Comment by zedutch** [comment]
Do you use Habitica on other devices besides that computer? (not only on your previous login)
I think this might be related to #5919 
There's some suggestions as to what may fix this in that issue, but I can't guarantee it'll work for you.

**Comment by ellem-0** [comment]
Yes, I do use multiple devices. There's my home and work computers, both of which I use several times a week, and occasionally, when I 'must' tick off a daily, I'll use a tablet.

However, any explanation involving multiple crons would require something like 10 crons (depending on whether things stay ticked or not) to work up to this amount of damage/experience. Also, it doesn't explain how my quest scroll got lost.

The more I think about it, the more I convince myself that somehow, my account status was reset to _after_ I ticked off my dailies but _before_ I fired off the skill. It's not that the skill just 'didn't take' or something like that, for then I wouldn't have gained that level + quest scroll.

I will check the time on all of these devices. Is it safe to assume that as long as I'm not using them concurrently (at least half an hour gap when switching), a minute or so wouldn't cause problems? I would expect the issue to occur when the same time stamp 'happens' twice...

**Comment by Alys** [comment]
@ellem-0 It's most likely an extreme instance of this bug: https://github.com/HabitRPG/habitrpg/issues/4313
Your browser was holding on to some changes and not sending them to the server, and then when a sync with the server happened, some changes were reverted. You'll get the quest scroll back when you level up again.

**Comment by crookedneighbor** [comment]
@Alys I'd peg it on https://github.com/HabitRPG/habitrpg/issues/4986 since @ellem-0 went from level 14 to 15 using a skill.

**Comment by crookedneighbor** [comment]
Also, why have we not fixed #4986 yet :disappointed:

**Comment by Alys** [comment]
Fair point. I'd forgotten about that one!

**Comment by Alys** [comment]
@ellem-0 If you level up by using tasks rather than a skill, everything will work normally. Use Settings -> Site -> Fix Character Values to give yourself XP if you feel you've been cheated out of it!

**Comment by ellem-0** [comment]
Thanks everyone for your insights - I never saw the error message mentioned in #4986 but other than that, it fits my observations perfectly. That makes me really happy, because it means I can fix my stats and put everything back in order.

I had to do an interesting back-and-forth to get everything where I thought it should be (health was trickiest, since leveling up would have refilled the bar), mostly because I'd already adjusted my stats to what I thought they were before.

I assumed that it would not be safe to grant myself the level via the 'Fix Character Values' (I doubt I could get the scroll that way), and a single daily was worth much less than the skill. Here's my work-around for that:
- make sure you have a daily available to check off (if necessary, uncheck one)
- calculate how much XP you need to get to one point less than a full bar and make a note of this number
- use the skills section of the User Data Display Tool to estimate how much XP you'll gain from the skill; _continue only if this exceeds the amount you wrote down in the previous step_
- use 'Fix Character Values' to increase you XP to 'full bar minus one'
- check off the one available daily; you will gain a level
- cast the skill
- use 'Fix Character Values' to decrease your XP by the amount you wrote down

**Comment by Alys** [comment]
_I assumed that it would not be safe to grant myself the level via the 'Fix Character Values' (I doubt I could get the scroll that way)_

No, it is safe to level up that way, even multiple levels at a time. You always gain unlocked items when you reach or pass the appropriate levels.
