### ISSUE TITLE
Can't leave party 

### ISSUE THREAD

**Issue by NIckB619** [HabitRPG/habitica#5932]
No matter how many times I refresh using google crome, the party wont let me leave :( 

group id Group ID: 5249033a-56aa-4f61-9cb7-f9d3186109e8

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.  

We'll need that as well to diagnose the issue.

**Comment by NIckB619** [comment]
e20ca385-1d3d-4682-be46-e90b741907ab Thanks for the prompt response 
Cheers

**Comment by crookedneighbor** [comment]
I'm guessing it's because you have a large party, did you get any error messages or anything? 

I've manually removed you from the party. Please refresh and see. Comment back here if you are still a part of the party.

**Comment by NIckB619** [comment]
Every time I clicked on leave party it would try to refresh the browser but It wouldn't complete the action, I also assume because it was such a large party that it was causing problems, I never had any issues when I left a smaller party in the past. At least now if you have other people raise this issue, it's got something to to do with large parties/ lots of members, anyways thanks for getting back  really quickly. Great community and idea, Cheers .
