### ISSUE TITLE
Use $(npm bin) in npm scripts

### ISSUE THREAD

**Issue by ziir** [HabitRPG/habitica#5933]
Hello,

At the moment, `package.json`refers to "best-used-globally" module binaries in its npm scripts.
Their presence in the user's PATH is assumed, though `gulp` and `bower` are explicitely stated as dependencies in the package.json.
This causes the app's build cycle to break (especially `npm install` because of the postinstall script)
on all environments that do not match this requirement.
Most of the time, even though it's kinda annoying anyway, the user can just run `npm install -g bower` and fix the issue.
Unfortunately it's not the case 100% of the time, so I guess it'd be better to simply refer to "preferGlobally" binaries using `$(npm bin)` inside npm scripts.
## 

Tim

**Comment by crookedneighbor** [comment]
@ziir Want to open a PR?

**Comment by ziir** [comment]
Sure thing
