### ISSUE TITLE
Add ZenHub to readme?

### ISSUE THREAD

**Issue by feluraschi** [HabitRPG/habitica#5936]
Hey, I'm on the ZenHub.io team. I noticed this repo uses ZenHub task boards to organize issues.

To help contributors know to check the task boards for current priorities, what do you think about adding the ZenHub badge to your ReadMe (or adding a mention to your contributor guidelines)? I'm happy to create a PR. A lot of people don't know ZenHub is free for open-source users :smile:

Thoughts?

**Comment by crookedneighbor** [comment]
To my knowledge, we don't use ZenHub. Looks interesting though. 

Can you show me where it says we're using it?

**Comment by feluraschi** [comment]
Hi @crookedneighbor! 
It seems that you have about 460 issues organized in our boards, this is a screenshot:
![screen shot 2015-09-16 at 1 02 03 pm](https://cloud.githubusercontent.com/assets/8772523/9916810/310b0ddc-5c73-11e5-913b-4c47e9c1f8cf.png)

By downloading the extension you'll be able to see ZenHub in full effect :)

**Comment by crookedneighbor** [comment]
I checked with some of the other devs that maintain this project, and it looks like a dev that no longer works on it used it for a while. Looks promising though. I'll give it a try, and if a majority of the maintainers use it, we'd be happy to add it to the readme.

I've set a reminder for myself to check back in on this in one month to see if enough of us are using it and add it to the readme if we are.

**Comment by crookedneighbor** [comment]
Also, you said:

> A lot of people don't know ZenHub is free for open-source users

I agree, I was on your website and could see absolutely no indication that it was free for open source projects. Honestly, I never would have added the extension if you hadn't explicitly told me it was free for OS. (So I'm glad you did!)

**Comment by Alys** [comment]
@feluraschi How do we "register" HabitRPG as an open-source project? The HabitRPG organisation's ZenHub account is frozen and I can't see an open-source option behind the "buy licences" button.

**Comment by Alys** [comment]
I think this might be why I stopped using the extension ages back - the free trial period expired. But that was months ago so I might be misremembering. :)

**Comment by feluraschi** [comment]
Hi @crookedneighbor & @Alys, ZenHub is automatically free on public and open-source repos but if you are facing any problems please contact support@zenhub.io.
Also- we just published a blog post with all the information you need about ZenHub for open source: https://www.zenhub.io/blog/open-source/
Let me know if you have any other questions, would be happy to help :)

**Comment by Alys** [comment]
Okay, thanks. I was looking at the dashboard for the HabitiRPG organisation (https://dashboard.zenhub.io/#/organizations/HabitRPG), which talks about buying licences, but I guess that's because it's for the organisation and not one of the repos.

**Comment by feluraschi** [comment]
Hey @Alys, this is because there are private repos in the org. When we detect this (using GH's API) we automatically show that org in the dashboard. ZenHub is free if it used on open-source/public repos :)

**Comment by crookedneighbor** [comment]
I like the tool, but not enough members of the org use it consistently for us to put it on our README. thanks for reaching out, I'll definitely be using and recommending it for other projects.
