### ISSUE TITLE
Missing member count in party / guilds

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#5937]
Since some days I've noticed that the count of members inside a group / party are missing, couldn't the fix yet, because in the templates the code seems to be still there :/

I think we should move the number to the panel title instead at the end of the members list
##

**Comment by Jolanda5** [comment]
As far as I can see it this is still an issue. Is somebody working on this or can be worked on this at the moment?

As for the suggestion made: I think the number would better fit into the panel title

**Comment by paglias** [comment]
Is this a client side problem or the number is missing from the database?

**Comment by Alys** [comment]
@paglias It looks like it's a database problem. There's 34 groups that have memberCount 0 and at least two of those do have members (I didn't bother checking the others).

There's also four guilds with negative member counts, although each of them has one member:
{ "_id" : "8d6bee0e-140b-4c80-83b8-d63ef2b6da62", "memberCount" : -1 }
{ "_id" : "bcbf367c-49a9-40d7-8b9a-da318b1b5d7b", "memberCount" : -1 }
{ "_id" : "d42f0e7a-bf45-425d-9082-c6b6db2d8d3b", "memberCount" : -1 }
{ "_id" : "599b178a-b0aa-482f-bb66-dbe24af7fefc", "memberCount" : -6 }

@Jolanda5 Thanks for asking about this! We'll sort this out by cleaning the database data.

**Comment by paglias** [comment]
Thanks, this too is fixed in v3!
Il 02 mag 2016 12:47 AM, "Alys" notifications@github.com ha scritto:
