### ISSUE TITLE
Cannot set property 'menu' of undefined

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#5939]
When clicking menus on the site, an error is often logged to the JS console:

`Uncaught TypeError: Cannot set property 'menu' of undefined`

To reproduce, open the JS console, then click "Inventory".

The offending line appears to be https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/directives/close-menu.directive.js#L17
##

**Comment by TheHollidayInn** [comment]
I believe this is because I used to initialize the variable in the MenuCtrl, but that is no longer the case. Which is how it should be. The property needs to be initialized elsewhere.
