### ISSUE TITLE
Subscription won't show as active + allocation points reset with every page reload

### ISSUE THREAD

**Issue by artkarapetov** [HabitRPG/habitica#5940]
I bought the $5 subscription and got the gems, and the site is reacting very weird; on the subscription page it shows me the default page for purchasing subscription, so I can't stop it or do anything about the existing subscription. 

Also allocation points reset with every page reload, and when I click to accept my party's quest pop-up it says "no such group found". There were also a couple of times when the top bar with the party members avatars disappeared and instead the "play with friends" button was showed, as if I wasn't in a party, and it goes back to normal after refresh. 

All this started to occur yesterday, before I bought the sub. 

I'm on Chrome on OS X Yesomite. Everything worked beautifully since I started "playing" a few weeks ago, and then suddenly all these issues... 
##

**Comment by Alys** [comment]
Sorry about this @artyomkarapetov! The site is undergoing some server problems at the moment, which most likely explains the problems with the attribute points and the party page. We'll post here when the server problems are fixed, and then we'll see if the odd behaviour you're experiencing is still occuring.

By the way, when you buy a $5 subscription, do you not get gems immediately. If you did receive gems as soon as you made the purchase, then you didn't buy a subscription; you just bought one set of gems for a once-off payment. You can read more about subscriptions if you wish to on the wiki's [Subscription](http://habitica.wikia.com/wiki/Subscription) page. Comment here if you have questions about that.

**Comment by artkarapetov** [comment]
Oh I see, that's most likely the problem. I'm not sure about the subscription, it just said: 
![habitica___your_life_the_role_playing_game](https://cloud.githubusercontent.com/assets/14325615/9926395/304ff5ae-5ce3-11e5-9049-e01b9e9cbdd0.jpg)

**Comment by Alys** [comment]
If you received 20 gems as soon as you made a $5 payment, then you definitely didn't purchase a subscription.

If you didn't receive 20 gems immediately, and instead had to buy the gems with gold, then you did purchase a subscription. If your subscription information isn't showing up, it will be because of the current site errors.

**Comment by artkarapetov** [comment]
I guess I bought the gems though the top menu then. Thanks for your help, will wait until the site gets back to normal and will report if the errors persist. 

Have a great day/night! :)
