### ISSUE TITLE
Can't Unsubscribe from Happiness Challenge

### ISSUE THREAD

**Issue by Cephalopod-Dreams** [HabitRPG/habitica#5942]
I haven't been on Habitica for a while - since it was HabitRPG. The last time I logged on I subscribed to the happiness challenge but since I've logged back on the Challenge doesnt show up in the challenges list and I cant unsubscribe.

The failed habits and dailies are slowly killing my character and I cant see how to remove them. Please see attached a screenshot of the offending tasks.
![happiness tasks](https://cloud.githubusercontent.com/assets/13288717/9927516/0b5ae91e-5d17-11e5-8b87-7212040affcc.png)

**Comment by Alys** [comment]
@Cephalopod-Dreams Please see the instructions in bold near the top of this issue: https://github.com/HabitRPG/habitrpg/issues/2763

Comment there if you still have trouble after a couple of days. I recommend marking the Daily as completed each night until then.
