### ISSUE TITLE
Emails & Usernames should be stored as downcased strings

### ISSUE THREAD

**Issue by gisikw** [HabitRPG/habitica#5944]
The performance overhead for querying

``` json
{
  "$or": [
    {
      "auth.local.email": {
        "$regex": "^user@address\\.com$",
        "$options": "i"
      }
    },
    {
      "auth.local.username": {
        "$regex": "^username$",
        "$options": "i"
      }
    }
  ]
}
```

...causes DB performance problems at scale. To improve performance, we need the following:
- A migration such that `User.auth.local.username_d = User.auth.local.username.toLowerCase(); User.auth.local.email_d = User.auth.local.email.toLowerCase();`
- `website/src/controllers/auth.js` should be updated to use direct comparisons against username_d/email_d, rather than regexp matches (search the file for use of the `RegexEscape` function - those are all candidates to be rewritten)
- On user signup, email_d and username_d should be automatically populated
##

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/issues/5126 would need to be finished first.

**Comment by Alys** [comment]
I believe we've done everything required for this.

@paglias please reopen if I'm wrong.
