### ISSUE TITLE
Problem adding Full Name to Profile

### ISSUE THREAD

**Issue by Otocinclus** [HabitRPG/habitica#595]
I was trying to add my name to the Profile (click on sprite, open Profile tab) but every time I type a letter, it switches to the avatar tab. The letter stays put, but I can only put one in at a time. Just a little bug, probably not high priority but thought it should be mentioned.

**Comment by Pandoro** [comment]
Hello,

This has been mentioned before in #467 Sadly we have no fix for this yet, but we are aware of it. Sorry for the inconvenience this is causing :( 

If you still want to add your name, there is a, possible but quite tedious, workaround. You will have to write your name in some text field, copy it from there and the go to the name field (or whatever field for that matter), then select everything (Ctrl+A) and paste it in there (Ctrl+P). After that the page will directly close again, but your info should be stored. 

I will close this thread, if you have any more questions, please post in #467
