### ISSUE TITLE
The server responded with a status of 502 (Bad Gateway)

### ISSUE THREAD

**Issue by HawkZero** [HabitRPG/habitica#5957]
Hi!

I have been experiencing a bug for about 6-8 hours now. Habitica was showing Bad Gateway messages, I tried reloading and this is the error messages I got (Chrome console):

https://habitica.com/app-e057c946.js Failed to load resource: the server responded with a status of 502 (Bad Gateway)

https://habitica.com/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular-a0537a78.woff Failed to load resource: the server responded with a status of 502 (Bad Gateway)

https://habitica.com/bower_components/github-buttons/github-btn.html?user=habitrpg&repo=habitrpg&type=watch&count=true Failed to load resource: the server responded with a status of 502 (Bad Gateway)

https://habitica.com/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular-4dab103b.ttf Failed to load resource: the server responded with a status of 502 (Bad Gateway)

ping:1 Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

https://habitica.com/bower_components/github-buttons/github-btn.html?user=habitrpg&repo=habitrpg&type=watch&count=true Failed to load resource: the server responded with a status of 502 (Bad Gateway)

I'm using Chrome on Windows 7, all other websites are working normally. 

(Can't attach User ID, since I can't access Habitica. I will attach it if needed after Habitica resumes its work!)

All the best and thank in advance for resolving the issue!

**Comment by crookedneighbor** [comment]
Heroku had an outage this morning which is likely the cause of the errors you saw. Should be resolved now.
