### ISSUE TITLE
Not dealing or receiving any damage to/from boss (other party members are able to do so).

### ISSUE THREAD

**Issue by D-Crypt** [HabitRPG/habitica#5958]
User ID: a6cbf103-b51a-4428-ba1f-8414bfd6301c
- Windows 10 Pro (64-bit)
- Google Chrome

I began a quest with my own quest scroll (as opposed to another party member starting it) a couple of days ago; although I am a participant, I'm not dealing nor receiving any damage to or from the boss at all, yet every other participant in the party are doing so as usual. It's been longer than two days, so it isn't a cron issue (any tasks done for the day should count anyway). I have been able to deal and receive boss damage for every other quest that other party members have started, so this seems to be specific to me using my own quest scroll somehow.

**Comment by crookedneighbor** [comment]
I don't see anything strange about your account. You haven't been resting in the inn, right?

Tomorrow, after your next cron, if you still haven't done damage, could you take a screenshot of your party chat and post it here?

**Comment by D-Crypt** [comment]
That's right, I haven't used it at all.

Here are the screenshots since I started the quest:

![c3](https://cloud.githubusercontent.com/assets/12638378/9985679/4916a2b6-6028-11e5-9011-1e5b43158258.png)
![c2](https://cloud.githubusercontent.com/assets/12638378/9985680/4a59a682-6028-11e5-8b7c-19ae5109c8d0.png)
![c1](https://cloud.githubusercontent.com/assets/12638378/9985681/4b55d7d6-6028-11e5-971f-1b3e2a0388d7.png)

**Comment by Alys** [comment]
@D-Crypt This should be fixed for your next cron. It wasn't related to you owning the scroll and starting the quest; that was just coincidental.

For devs, I've change the user.party.quest object from this:

```
    "party" : {
        "quest" : {
            "RSVPNeeded" : false,
            "completed" : "",
            "progress" : {
                "collect" : {
                },
                "down" : 0,
                "up" : 7.63892644253122
            },
            "key" : null
        }
    },
```

to this (the key was missing):

```
    "party" : {
        "quest" : {
            "RSVPNeeded" : false,
            "completed" : "",
            "progress" : {
                "collect" : {
                },
                "down" : 0,
                "up" : 7.63892644253122
            },
            "key" : "goldenknight3"
        }
    },
```

**Comment by D-Crypt** [comment]
@Alys Brilliant, thanks for the help. I'll close the issue if it works as intended tomorrow morning.
