### ISSUE TITLE
Killed by boss despite full health

### ISSUE THREAD

**Issue by angelraix** [HabitRPG/habitica#5960]
I had 50 health and received 19 damaged from a boss, but it took my health to -19.

**Comment by Alys** [comment]
That's expected if something else had very recently caused you to die and either you hadn't yet taken any action on the site that brought yourself back to life (i.e., you were still at zero health when you took 19 damage), or you had been brought back to life but a sync error had reversed that at about the same time you took the 19 damage. If you ever feel that any damage is unfair, you can reverse the effects by using Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).

I'm going to close this now, but if what I've described doesn't sound like it matches the problem, we can reopen this, however we'll need to be able to identify your account - see step 6 in the [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions.
