### ISSUE TITLE
Third party creating new habits

### ISSUE THREAD

**Issue by bionicallyironic** [HabitRPG/habitica#5961]
Today I noticed a habit I did not enter that looked like a bunch of gibberish. 

![screen shot 2015-09-21 at 2 08 07 pm](https://cloud.githubusercontent.com/assets/14624700/10002494/0cb2c6b6-606d-11e5-9a41-7d876c44ed7d.png)

When I hover over it, I get this message: "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task."

![screen shot 2015-09-21 at 2 30 15 pm](https://cloud.githubusercontent.com/assets/14624700/10002543/69329b46-606d-11e5-9b75-310aaa4a73f3.png)

I noticed this on my app first, but then on my desktop as well. Reloading the page does not make them go away, and even if I delete the task, a new one shows up sometime later. I've been using HabitRPG for almost two months, and this is the first time I've seen this happen. 

Can someone please assist?

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/1402 or the "Known Bugs" section in the wiki's [Habits](http://habitica.wikia.com/wiki/Habits) page for details.

"a new one shows up sometime later" - how much later? How many times has that happened?

**Comment by bionicallyironic** [comment]
It's happened three times, anywhere from thirty minutes to an hour after I've deleted one.

**Comment by bionicallyironic** [comment]
Also, thank you!

**Comment by Alys** [comment]
Can you please post on https://github.com/HabitRPG/habitrpg/issues/1402 to add your comment from above about how how it's happened, and also identify your account - see step 6 in the [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions.
