### ISSUE TITLE
My stock of Spooky Sparkles appears to be overdrawn!

### ISSUE THREAD

**Issue by amandaleee** [HabitRPG/habitica#5964]
Hi all! Yesterday I bought enough Spooky Sparkles to cast on myself and everyone in my party. Today, I'm seeing a negative number of Spooky Sparkles under "Special" in the Inventory tab. 
<img width="189" alt="screen shot 2015-09-22 at 10 03 45 am" src="https://cloud.githubusercontent.com/assets/2200300/10022384/287ac038-6112-11e5-9517-2d85b40dd071.png">

My user ID: 46879cf2-9a78-4450-b420-8f97841db0c7
The party's group ID: 593b9374-3696-4d56-a7e4-0815d3ce41d3

There are no javascript errors when the page loads - however, I do get "Given URL is not allowed by the Application configuration:"

<img width="1077" alt="screen shot 2015-09-22 at 10 12 20 am" src="https://cloud.githubusercontent.com/assets/2200300/10022445/875db222-6112-11e5-8eb3-d7b863645db3.png">

Just now, I purchased one more Spooky Sparkles and the increment went up in the correct way, so it's counting fine; it just thinks I was able to use more than I had, I guess. Any idea why this would happen?

**Comment by Alys** [comment]
There might have been a sync error which made your browser think you had more Sparkles than you actually had (allowing you to cast them) and then when things synced up, you ended up with a negative number. I've reset the number for you. If you're out any gold, use [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to give it back to yourself. I'm sorry about the trouble!

Comment here if you have any questions or if it happens again.

**Comment by amandaleee** [comment]
Cool, thanks for checking on this!
