### ISSUE TITLE
Missing equipment

### ISSUE THREAD

**Issue by pipisafoat** [HabitRPG/habitica#5966]
I purchased all of the special seasonal equipment, but none of it is showing in my equipment tab (and it's gone from purchasable and the money is also gone, so I know it happened) - this has been a couple days and nothing has reappeared.

**Comment by Alys** [comment]
Log out, clear your browser's cache, cookies, and local storage, and log back in (or try in a different browser). 

If that doesn't solve the problem, we'll need to be able to identify your account. Please go to Help -> Report a Bug and see step 6 of the instructions.

**Comment by pipisafoat** [comment]
apparently I had to do that on all computers I've been using instead of just one. but it's fixed now! thanks!

**Comment by Alys** [comment]
Thanks for letting us know! That's interesting news. Do you have your browser set up to share resources across all computers? Which browser is it? If you can, please tell us the version of the browser and also which operating systems you use it on, but if you're not sure about some of the details, just the name of the browser(s) would help.

**Comment by pipisafoat** [comment]
Yes, I use Chrome synced to two computers, an Asus laptop running Windows 10 and a Mac Pro running 10.10.5, browser fully updated on both. apparently it would delete from one computer but instead of deleting the other as well, it would just reload all the info from that computer - so I had to delete history et al on both at basically the same time to make it work. (I think it's the crossing windows/mac platform that makes that weird and buggy.)

**Comment by pipisafoat** [comment]
Version 45.0.2454.85 (64-bit) on Mac Pro; have put laptop to sleep now.

**Comment by Alys** [comment]
Thank you very much for the details! That's very useful information for us.
