### ISSUE TITLE
Simple habits that need to be repeated multiple times per day to form the needed habit = Tallymarks for habit completion?

### ISSUE THREAD

**Issue by gitirs** [HabitRPG/habitica#597]
Suppose I wanted to add a specific habit/skill. I want to repeat it 5 times a day. So when I go to my habit I can tally mark it. After I do it the necessary times, I get points for it. I understand the multiplier works in this case, but the game would be to easy because the habit I want to add are very simply actions that need to be repeated multiple times throughout the day. 

Instead of a task being 1x, 1.5x, 2x, I want it to be like .2x, .25x, etc. If that is too complicated, perhaps make a small note on the edge of the habit where the tally marks can be counted. After you hit the daily count, you get the normal 1x points. 

Thanks

**Comment by ruddfawcett** [comment]
Interesting idea (no in a bad way).  I definitely see how this could be useful!

**Comment by wildcate** [comment]
There are two similar suggestions in the Trello list [here](https://trello.com/card/completion-quotas/50e5d3684fe3a7266b0036d6/169) and [here](https://trello.com/card/extra-completion-for-daily/50e5d3684fe3a7266b0036d6/207).

**Comment by wc8** [comment]
@gitirs can you explain more of what you mean by:

> Instead of a task being 1x, 1.5x, 2x, I want it to be like .2x, .25x, etc. If that is too complicated, perhaps make a small note on the edge of the habit where the tally marks can be counted. After you hit the daily count, you get the normal 1x points.

**Comment by wc8** [comment]
I'm closing this for organization, but if the two suggestions previously mentioned don't meet your needs, just write back with what's missing.
