### ISSUE TITLE
Advanced Options setting is inverted, when creating a new task

### ISSUE THREAD

**Issue by sidawson** [HabitRPG/habitica#5981]
**PAGE**
On the website
Menu: Site | Settings
Url: https://habitica.com/#/options/settings/settings

**SETTING**
Advanced Options in tasks start collapsed

**PROBLEM**
1. If ticked, the Advanced Options (task difficulty) are visible
2. If unticked, the Advanced Options are collapsed

**CONCLUSION**
Behaviour is opposite of expected. 

**TOFIX**
Suggest inverting the text (and tool tip). No change required to code or database records.

from:
- Advanced Options in tasks start collapsed
- With this option set, Advanced Options will be hidden when you first open a task for editing

to:
- Advanced Options in tasks start expanded
- With this option set, Advanced Options will be visible when you first open a task for editing
## 

user id: 78810b6b-221d-4baf-b6e7-1cbb8f028042

**Comment by Alys** [comment]
Are you certain about this? I can't replicate it, using two accounts.

Note that I'm not saying you're wrong, just asking you to double check. :) There might be an particular mixture of settings that produces this behaviour. If you're sure it's happening repeatedly to you, we will examine all of your preferences (we can do that in the database; you don't need to report them all).

**Comment by sidawson** [comment]
Hmm. That's interesting.

I have open tasks in edit mode ticked, maybe that?

But yes. Verrrry certain about this.

Something that's bugged me for a few weeks. And I just spent half an hour
trying to write the clearest bug report possible, so yes, it's been very
checked :)

If I have that option ticked then the difficulty is visible when I create a
new task. So I have to click the little dropdown to change the difficulty.
If I have that option unticked, I can just select the difficulty and hit
save&close on the new task.

If there's any tests you'd like me to run from here, I'm more than happy to
help nail this one.

I'm running Chrome 44.0.2403.157 (64-bit) (latest ver) on OSX 10.10.5
(latest ver).

I do have a LOT of javascript/spyware/adware/crap stopping plugins working
- although I've given habitica full access - they may be a factor.

I'll check right now that I can repro this in two other browsers, and get
back to you.

Si

**Comment by sidawson** [comment]
Ok, just checked in Vivaldi (1.0.219.53 (Developer Build) (64-bit)) and
Safari (8.0.8) - both latest vers.

I logged out everywhere before logging in on each browser.

Here's exactly what I did:
1. Sign in
   ( check if the "settings | site | advanced options collapsed" flag was on
   or off)
2. Click Tasks
3. Enter "test" in the task title
4. Click the "+"
5. See that the difficulty WASN'T visible (if the option was unticked - ie,
   opposite of expected)
6. Click Trashcan (to delete task)
7. Go to Settings | Site
8. Toggle the "Advanced Options Collapsed" check box (ie, if on it was
   changed to off; if off it was changed to on)
9. Click Tasks
10. Enter "test" in the task title
11. Click the "+"
12. See that the difficulty WAS visible (if the option was ticked - ie,
    opposite of expected)
13. Click Trashcan (to delete task)
14. Sign out

So. Checked both ways on all three browsers.

I didn't change any other settings. These site options are currently all on:

Show Header
Sticky header
Open new tasks in edit mode
Tag list in tasks starts collapsed
Display Invite To Party button when party has 1 member.

(the others are off)

Hrm.

Si

**Comment by Alys** [comment]
Thanks for the details! Looks like it's the "Open new tasks in edit mode" setting that's causing the checkbox to behave the wrong way around. We'll get that fixed, although we'll probably leave the wording as it is now, and change the behaviour to match the wording.

Good bug report, BTW. Very clear. I am sorry I doubted you. :)

**Comment by sidawson** [comment]
No problem. Always better to double check and be absolutely certain.

Wording change was suggested assuming a simple, independent, inversion bug.

If it's two settings interfering, then sadly yes, coding will be required :)

**Comment by TheHollidayInn** [comment]
Looks like the logic was backwards `if user.preferences.advancedCollapsed then task._advanced = false`  has now been changed from `if user.preferences.advancedCollapsed then task._advanced = true` . 

I'll submit a PR soon, but I was wondering why you think the "Open new tasks in edit mode" is messing with the other setting.

Also, are either of you able to create a new task and have it be open for editing with the "Open new tasks in edit mode" setting on. I'm not sure if that makes sense.

**Comment by Alys** [comment]
When you have "Open new tasks in edit mode" ticked, and you create a new task, the behaviour of the advanced options section is the opposite of what the "Advanced Options in tasks start collapsed" tickbox indicates. That's the problem that needs to be fixed.

Try it like this: Tick "Open new tasks in edit mode". Go to the tasks screen. Sync so that you have the latest data from the server (because a sync later will cause an open task to close). Create a new To-Do or Habit (not Daily because of https://github.com/HabitRPG/habitrpg/issues/5728). The advanced options section will be open/closed depending on the _opposite_ of the "Advanced Options in tasks start collapsed" setting.

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/f035dfd8b91809521125a940991c57c6ccc63c26
