### ISSUE TITLE
Service Unavailable?

### ISSUE THREAD

**Issue by yavulan** [HabitRPG/habitica#5983]
On load:
![1](https://cloud.githubusercontent.com/assets/7360866/10132859/73771130-65e1-11e5-849b-9122d7878716.png)

After reload frontend seems to be ok, but console says:
_Object { data: "<!DOCTYPE html>     <html>     <hea…", status: 503, headers: tc/<(), config: Object, statusText: "Service Unavailable" } app-8bdd0355.js:36:22066_

Firefox 40.0.3

**Comment by paglias** [comment]
@yavulan probably you encountered a one time only error, everything seems fine now. let us know if it happens again
