### ISSUE TITLE
No "begin", "cancel" and "abort" buttons for quests in android app

### ISSUE THREAD

**Issue by jkadlubo** [HabitRPG/habitica#5987]
The title says it all: since there are no such buttons, I cannot begin (or abort an already running) quest using the app (at least I can invite my party).
my ID: 7d6c309a-50ea-4c30-9717-58f9e2906979
party ID:  7e4e9fa1-7421-4aed-aec9-1094570ab5c8

**Comment by Alys** [comment]
@jkadlubo I'm sorry about the inconvenience! The Android app does not contain all the features of the habitica.com website. However the website works in most mobile browsers, so you might find that you can control quests by logging in to the website on your phone. 

We're developing a new Android app that will replace the one you're using now. When it's first released, it also might not contain quest controls, but it will continue to be developed and will in time contain all, or at least almost all of the features of the website. When the new app is released, there'll be a Bailey message about it, so keep watching those messages for updates.
