### ISSUE TITLE
quest progress not being applied, quest damage not being received (and maybe other non-quest problems)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5988]
This is one of those annoyingly vague bug reports that we might not be able to do anything with, but I've seen enough odd comments in the past day to indicate that maybe Something Is Happening with quest updates on cron, or maybe there's Habitica-wide oddness.

In one party I'm in (gid f3de857c-03d3-4042-bf30-d452876661f4), three players are in a collection quest at the moment. For two of them, they cronned today and weren't resting in the inn, but **party chat does not contain any messages stating how many items they found** (confirmed by looking at the chat log in the database). The third player in the quest was me, but I was resting in the inn last night.  

Commander Bear (66437e2b-9c8e-4f6b-9cce-ef2bd6eaf224) reported in the Tavern in two messages, 15 and 12 hours ago:
"Is Cron delayed globally or maybe broken for me? I burned half my mana last night, and data display tool showed I was going to do 408 damage to the party quest boss, but **I have no line in the party chat for me vs the boss today**."
"IDK if I should file a github issue for this, but cron didn't apply my damage to the party quest (group id 9eb8aad8-16ea-48be-b168-cc32df92d55c). I've logged in, done actions, resync'd, nothing."

I've confirmed Commander Bear's report by looking at the database.

Velinde (8f21e403-8e3a-4d75-8824-74fe4712b2ce) in the Tavern two hours ago said:
"Weird thing happened: according to my party page **the boss I'm fighting attacked my party 4 hrs ago for 13.7 damage, but I'm not sure if that damage was applied to all of us**. It certainly doesn't look like it was applied to me. I have 47/50 HP and I haven't completed any tasks or bought any potions yet."

I've confirmed that Velinde is in that party's quest and that 13.7 damage should have been received by all quest participants. I have not checked Velinde's stats (too hard to analyse stats for this after the fact), but I have more than enough confidence in Velinde's understanding of Habitica to be certain this report is accurate.

Also, there's a couple of things unrelated to the quest system, which might be coincidental or might be signs of a wider problem:

Issue https://github.com/HabitRPG/habitrpg/issues/5986 from 16 hours ago says "**I just died twice in a single morning**". It's not from quest damage or time/timezone issues.

In the Tavern 9 hours ago there was this report from cecilyperez (d2a1934c-6007-412e-8fd6-5a5a7b38b0bf)
"hey, something weird happened. i logged on and, from earlier today, **i went from depleted mana to full mana, a bunch of habits that had just turned green were bright blue, and i jumped 20-odd levels**. dailies and habits are the same."

I haven't done anything to try to confirm that report since getting data from before the event would require downloading a database backup, but we have occasionally seen reports of massive level jumps and tasks changing colour wildly, so cecilyperez's report is believable.
##

**Comment by Alys** [comment]
There's also a LOT more reports of https://github.com/HabitRPG/habitrpg/issues/4313 in the Tavern today than usual (Dailies not being reset / unfair damage).

**Comment by poychamp** [comment]
Hello, the quest damage not being received issue just happened to me today. I don't know if it was because my connection was really slow or there maybe was a problem in the server at that moment, but I was getting an Application Error on load. I'm using Habitica on the browser. The thing is, I was trying to catch up with the time, because the daily reset was near. I tried to force the issue and casted 17 brutal smash spells and I made sure I casted 17--i did a lot of refresh in between to check that my remaining mana was 27. Anyway, after the daily reset, there was no damage. Here is my User ID for reference: eefe5fa8-4179-41b6-9766-a632ea3936ad .

**Comment by aeris921** [comment]
Hi, my party is also having issues with damage to quest bosses not showing up either right at Cron (me), or sometimes even at all (my husband).

My userid: b47cbf74-84b1-40b1-8242-b8bcf7ede693
My husband's userid: 885f9906-7712-4b0f-9d14-c400299e0a97
Our Group ID: 93404b47-7274-4267-b560-9dc14d358157

Also, everyone in my party is fairly new/inexperienced on Habitica and with questing, so I can't tell when something's not right, but one of my party members (who is the lowest level) randomly did 108.3 damage to the boss when most of the rest of our hits on this boss have done less than 15 damage. I can see having a particularly successful day and shooting up to 20 or 30 damage, but how does 108 damage happen when we're averaging about 15? Is that normal?

**Comment by Alys** [comment]
@aeris921 Some information that might help make sense of this: your cron runs when you use Habitica for the first time each day (it doesn't run exactly at midnight, or at your Custom Day Start time if you've set one). So if your damage is appearing at different times each morning, that will be because you start using Habitica at different times. Also, you sometimes have to click the "Fetch Recent Messages" button before new messages will appear, which can make it seem as if there's further delays. Doing 100 damage or even several hundred damage at once is possible by using the Mage's Burst of Flames skill or the Warrior's Brutal Smash skill. Both are designed to do up to about 20 or 30 damage each time you cast them (less for lower powered players), and you can cast them as many times as you have mana available.

When you have questions about anything you see, you'd be most welcome to ask in the Newbies Guild. You can get to it from the Help -> Ask a Question menu option. There's a lot of experienced users there who can answer almost any question.

**Comment by petathames** [comment]
My party is having weird quest issues, but its more to do with extra damage with crons running twice or at the wrong time.  I know in my case it's not related to #5919 as I haven't changed my timezone recently and I only access Habitica via the webpage (I do have the android app installed but rarely use it).

Group ID: 1b2f65f1-0720-4491-9db3-4973fd2c982e
My ID: 4733870a-a49b-4fb5-bcc6-c5863973ccc1

A day ago we had a double attack from Berylbee (86c684db-54da-4414-85fa-7c14454da972).

A little earlier my cron went off at midnight my local time when it's set to 10am.  It then didn't trigger at 10am.  After that, I reset my cron to 11am, it triggered, and now I've set it back to 10am.

Two days ago sarahb (add76731-799a-4fc9-9be9-dfe134ec2842) reported that her cron triggered early also.

Our previous quest run a couple of weeks back, we had a lot of issues with crons running at the wrong time also.  All our quests prior to these last two have been fine.

**Comment by IceManX2X** [comment]
I'm new to this but I need to submit a bug.  Not sure if I'm in the right place.  My party and I just finished the quest Dilatory Distress Part 1 but no one received the armor and the 2nd quest scroll.  There was no notification that we finished but in our group chat it stated all items had been found and party members received their rewards.  The quest is not listed under my completed quests either.
MyGroup ID: b2dd018a-078c-4837-9bf1-af48dde0a52a
My User ID: e01dcb6b-6239-40d1-a6e1-f3606d1109ef

Please help!

**Comment by Alys** [comment]
@IceManX2X Sorry about that, and thanks for letting us know! I've given the quest achievement and rewards to you and your party members. Post again here if there's still any problems (note that you might need to reload first to see the changes).

**Comment by Ishmaeel** [comment]
I think our party (**84895e1d-df4c-4af0-b72e-6187492edfd3**) is experiencing this very same bug. It's especially noticable with a certain member (**eefdb692-9a10-4b22-9559-dfd0922c485b**) who consistently causes a large amount of damage from bosses, but the damage has never been applied to me so far. It has happened at least four times that I noticed. I'm sure I haven't died. The most recent instance of that happening is seen in our chat for 2016/01/06 12:03:30 (My time zone is GMT +2).

We have also experienced quest rewards not being delivered at least two times. Perhaps @Alys might remember me from Tavern, who fixed it for us both times.

My own user ID: **604d93c2-7ef2-43be-9d0b-d34869b586b1**

What appears to me is that the cron job is being interrupted due to some kind of error and only applies damages/rewards to some of the party members.

**Comment by Quesseriel** [comment]
Our party also (f050b02e-3c6a-4bd2-8d03-7597ae262079) is experiencing this bug. I (2cba45b4-7cc8-4f33-9ea1-a4a7369e6fa1) very rarely take damage from others from the boss.  Our party is pretty big (25 currently) and it's only been happening for a couple of weeks, but I'm pretty sure that generally only a few members, usually the same ones, take damage for everyone.  The progress and damage reports show up, but only the few actually take the damage.  As far as I know, everyone has been receiving the quest rewards at the end of quests.  I access with Firefox on Android and desktop.  Not sure about the others in the party, but I can ask if pertinent.

**Comment by Alys** [comment]
@Quesseriel and everyone else here: we're close to the end of a large project to improve Habitica's back-end code (make it more reliable, stable, efficient, etc). There's a chance that it will prevent this bug or make it occur less often, or at least make it easier to investigate! For the moment, we're not going to keep looking into this, however I've added it to my list of issues to get back to when the new code is live, so I'll post here then and if the bug still seems to be happening, we can start monitoring it in detail.

@Quesseriel : the platforms that your party members are using won't be pertinent so no need to find out, but thanks for offering! This will all be happening in the backend - it's probably timeouts that occur when Habitica is trying to update the database records for all party members.

**Comment by Alys** [comment]
A similar report from Fancazzone (1799656c-e917-4200-9099-4ea81f07b10e) in the Tavern: "Tonight a ghost stag attacked my party for 20 damage, but when I woke up, I had suffered no wounds." No heals had been cast to remove the damage before Fancazzone saw it.

**Comment by Alys** [comment]
Another report in the Tavern from Felis.Mau (f5b75d40-e57d-4fd7-8db8-a57c5d12ba8a):

"I started a quest yesterday before I checked of my dailies, I didn't check in the tavern but I didn't do any damage today... Normally I make a few hundreds of damage..."

I've confirmed that Felis.Mau:
- forced started the quest at Jul 2, 2016 10:03:44 pm UTC
- cronned at Jul 3, 2016 6:11:32 am UTC according to both Amplitude and `user.lastCron`
- had a progressUp of about 307 at cron
- did not produce any quest progress message in party chat for that cron
- did not cause any health loss to the boss
- is still a participating member of the quest
- has progressUp of 0 now

I.e., cron definitely ran and definitely performed some of its actions (e.g., setting `lastCron` and deleting yesterday's quest progress) but did not perform all of its actions (e.g., did not damage the boss).

**Comment by Alys** [comment]
Another report in the bug guild from AC (03a02bbb-d54d-48c6-96f9-117c804d8590):

"I logged in today and my tasks reset, but I didn't deal any damage to our boss, despite having done a lot of work yesterday. I didn't do any damage to the party either, even though I left a couple of dailies undone. There's just no line about my damage at all in the party chat. Is this some sort of bug? I was logged into the Tavern the day before yesterday but not yesterday.

"Also, another member of my party has the same problem - no damage has been logged from her. (And she didn't check into the Tavern recently, either)"  [I'm seeking information about her too.]

I've confirmed that AC is part of the quest. Their most recent quest message was:

```
"text": "`AC attacks Snail of Drudgery Sludge for 81.2 damage.` `Snail of Drudgery Sludge attacks party for 0.9 damage.`",
"timestamp": 1468188307315, //      UTC: 2016-07-10 22:05:07
```

Since then, Amplitude says they cronned at Jul 12, 2016 11:01:52 pm UTC (resting false), so that should have given a quest progress message but didn't. 

User and party data is:

```
    "party": {
        "quest": {
            "key": "whale",
            "progress": {
                "collectedItems": 8,
                "collect": {},
                "down": 0,
                "up": 101.57488863943985
            },
            "completed": null,
            "RSVPNeeded": false
        },
        "orderAscending": "ascending",
        "order": "party_date_joined",
        "_id": "a5bb9da8-a8fe-4b3a-8ee1-27826878da08"
    },
```

```
    "_id": "a5bb9da8-a8fe-4b3a-8ee1-27826878da08",
    "quest": {
        "leader": "03a02bbb-d54d-48c6-96f9-117c804d8590",
        "key": "whale",
        "extra": {},
        "members": {
            "df................................1f": true,
            "9b................................45": true,
            "30................................b7": true,
            "24................................bd": true,
            "03a02bbb-d54d-48c6-96f9-117c804d8590": true
        },
        "progress": {
            "hp": 388.30638301580353,
            "collect": {}
        },
        "active": true
    },
```

**Comment by Alys** [comment]
Tavern, Moosy (7583232e-3233-4ce6-81de-8ac8b67f9a4b):
"@AC You are not the only one, I also didn't deal any damage :("

Most recent quest progress message:

```
"text": "`Moosy attacks Necro-Vice for 87.1 damage.` `Necro-Vice attacks party for 2.4 damage.`",
"timestamp": 1468292195961, //      UTC: 2016-07-12 02:56:35
```

A more recent cron in Amplitude: `Jul 13, 2016 3:29:29 am UTC` (resting false)

```
{
    "_id": "7583232e-3233-4ce6-81de-8ac8b67f9a4b",
    "profile": {
        "name": "Moosy"
    },
    "party": {
        "quest": {
            "key": "moonstone3",
            "progress": {
                "collectedItems": 5,
                "collect": {},
                "down": 0,
                "up": 14.021918263235518
            },
            "completed": null,
            "RSVPNeeded": false
        },
        "orderAscending": "descending",
        "order": "level",
        "_id": "80a2ea28-3f19-4f38-89ca-68177f1eeb60"
    },
```

```
{
    "_id": "80a2ea28-3f19-4f38-89ca-68177f1eeb60",
    "quest": {
        "leader": "7583232e-3233-4ce6-81de-8ac8b67f9a4b",
        "key": "moonstone3",
        "extra": {},
        "members": {
            "7583232e-3233-4ce6-81de-8ac8b67f9a4b": true,
            "24.................................1": true,
            "73.................................a": true,
            "a8.................................8": true
        },
        "progress": {
            "hp": 1264.8393869296683,
            "collect": {}
        },
        "active": true
    },

```

**Comment by Alys** [comment]
Bug guild, ann (01b5a3ef-933e-4258-ac27-4b6af46d85fc):
"I also had the same problem as AC, none of my damage to the monster was recorded last night. Haven't been resting in the tavern for a couple weeks."

Most recent quest progress message:

```
"text": "`ann attacks Serpent of Distraction for 317.4 damage.` `Serpent of Distraction attacks party for 0.0 damage.`",
"timestamp": 1468287700791, //      UTC: 2016-07-12 01:41:40
```

A more recent cron in Amplitude: `Jul 13, 2016 4:53:15 am UTC` (resting false)

```
{
    "_id": "01b5a3ef-933e-4258-ac27-4b6af46d85fc",
    "profile": {
        "name": "ann"
    },
    "party": {
        "quest": {
            "key": "snake",
            "completed": null,
            "RSVPNeeded": false,
            "progress": {
                "collectedItems": 12,
                "collect": {},
                "down": 0,
                "up": 15.490059430617185
            }
        },
        "orderAscending": "ascending",
        "order": "level",
        "_id": "2736a7e0-2725-4de6-ba56-055e4c4a1d04"
    },
```

```
    "_id": "2736a7e0-2725-4de6-ba56-055e4c4a1d04",
    "quest": {
        "leader": "01b5a3ef-933e-4258-ac27-4b6af46d85fc",
        "key": "snake",
        "extra": {},
        "members": {
            "01b5a3ef-933e-4258-ac27-4b6af46d85fc": true
        },
        "progress": {
            "hp": 782.5980378561408,
            "collect": {}
        },
        "active": true
    },
```

**Comment by Alys** [comment]
Bug guild, leviatus (6ff8d2fb-6f5b-411e-985b-18e8195e4aee):
"Hi, I am facing a similar issue to AC in which I did not deal any dmg to the party boss. There seems to be a problem resetting some tasks as well."

**Three of leviatus's Dailies are marked as completed and have no history entry from the most recent cron (the other Dailies do have that history entry).**

Most recent quest progress message:

```
"text": "`leviatus attacks Vice, the Shadow Wyrm for 31.4 damage.` `Vice, the Shadow Wyrm attacks party for 8.7 damage.`",
"timestamp": 1468280956713, //      UTC: 2016-07-11 23:49:16
```

A more recent cron in Amplitude: `Jul 13, 2016 12:40:36 am UTC` (resting false)

```
{
    "_id": "6ff8d2fb-6f5b-411e-985b-18e8195e4aee",
    "profile": {
        "name": "leviatus"
    },
    "party": {
        "quest": {
            "key": "vice3",
            "progress": {
                "collectedItems": 2,
                "collect": {},
                "down": 0,
                "up": 8.378845816362027
            },
            "completed": null,
            "RSVPNeeded": false
        },
        "_id": "9ef1c514-272d-4687-8eba-2c30a31d42ec"
    },
}
```

```
{
    "_id": "9ef1c514-272d-4687-8eba-2c30a31d42ec",
    "quest": {
        "leader": "5de7b147-2115-4873-aabb-bcbaa6c917cb",
        "key": "vice3",
        "extra": {},
        "members": {
            "86................................98": true,
            "6ff8d2fb-6f5b-411e-985b-18e8195e4aee": true,
            "09................................59": true,
            "5d................................cb": true
        },
        "progress": {
            "hp": 810.13705438544,
            "collect": {}
        },
        "active": true
    },
}
```

**Comment by Alys** [comment]
Another confirmed report from Zebedee (94fae8ce-e89b-4984-9a76-0ce709267f24): 

Cron ran `Jul 13, 2016 5:46:17 am UTC`, no quest progress.

**Comment by Alys** [comment]
Possibly related:
- cTheDragons (bc10ec41-4213-4482-bbb8-558e3c3ea8d5) reported that after using the Orb of Rebirth, two of her non-challenge To-Dos were still orange (I confirmed that by looking at their values)
- Bug guild 10 hours ago from CritterDoc42 (e01b9191-194f-4dfc-9461-9dca3fdc49e8): "On the website I keep getting a red error message saying an unexpected error occurred. It asks me to reload the page. When I do I continue to get the same error."
- Bug guild 8 hours ago from Th3supr3m3 (5930fb55-0b28-461f-8fd2-29e756069ed8): "Hey, so every time I open the webpage for the first time I get a " Yikes! There was a problem loading the page..." I often get several of these cards, between 2 and 5. But as far as I can tell, there is nothing actually wrong with the page - it loads normally and everything functions properly. In fact, the only thing wrong with the page is all of the error messages!"
- Lemoness [reported](https://habitica.slack.com/archives/ios/p1468377448000329) slow behaviour in the iOS app 4 hours ago but that might have been network problems.
- Over the past couple of hours, I've been getting a few "Yikes, an error occurred" (haven't been using the Habitica website much before that today so I don't know if they would have happened earlier)

Server overloaded?

**Comment by Alys** [comment]
Another confirmed report from Timothy Crittenden (7bbf8061-0609-466c-9705-62a47e94939c):

Cron ran `Jul 12, 2016 10:10:04 pm UTC`, no quest progress.

**Comment by Alys** [comment]
Lyna (60418e8f-ee15-428a-8f3a-9b7b13dc5f7c) 
`Jul 13, 2016 3:56:03 am UTC`

**Comment by Alys** [comment]
Jlbl (bc612705-7cb4-4f3e-ba39-0871980b1a11) `Jul 13, 2016 5:05:35 am UTC`

**Comment by Alys** [comment]
- Another person with two Dailies that didn't become uncompleted and that have no history entry for the most recent cron: Wraith Lord (ac6cdf93-afca-4121-8cbc-c8e5c34ce17d) 
- Someone with a Daily they didn't finish which did not lose its streak and they didn't lose any HP: Ava (5d3c3da9-651c-404c-b02e-1a1ff3126b35). I confirmed that one of their Dailies is missing the most recent history entry.

**Comment by Otocinclus** [comment]
Hi Alys, I'm the other one in a party with AC (I'm dfa5d988-992a-4dec-8183-c15c8adb041f) We were doing the Wailing Whale quest at the time. I'm showing my previous check in as normal (7/10/16 @ 0:34), and then it jumps to (7/12/16 @ 4:56 am). I check in every day, and definitely was not awake at 5 in the morning. I have my cron set to 4:00am, so I wonder if my 7/11 check in got delayed and therefor got counted for 7/12? I might not actually belong in this thread unless it's a server delay issue.

**Comment by Alys** [comment]
The several entries above here starting at https://github.com/HabitRPG/habitrpg/issues/5988#issuecomment-232235844 were due to a specific problem that was fixed (I'll track down the details later). The earlier ones and the ones from now on are likely due to something else.

---

Another confirmed report from gravitonbit (Habitica name is mus; 5b7a8716-8e74-44c2-ae9e-48feaa05000a) at https://github.com/HabitRPG/habitrpg/issues/7805.

Cron ran Jul 18, 2016 1:58:44 pm UTC, not resting, no quest progress message.

They write: "When I logged in a error message showed up but couldn't recall what was it as I immediately closed it."

**Comment by Alys** [comment]
Another confirmed report from Nebrets (49d31f0b-ec0a-4629-b25e-db953f27cbe8). Their cron at Aug 16, 2016 10:02:51 am UTC ran according to Amplitude but did not produce a quest progress message for an active quest.

And from Prita (9874841c-c18f-4628-837d-02f9eaa0b46d). Their cron at Aug 18, 2016 1:51:20 am UTC  ran according to Amplitude but did not produce a quest progress message for an active quest. I'm looking at log files for this one to see if anything shows up.

**Comment by Alys** [comment]
Another report of this from Nowhere man (4e971bdc-492c-4a38-861f-b114d3974510) in the Report a Bug guild:

"I'm in a quest, but I am no longer taking any damage when the boss attacks. Last time this happened to me, I also ended up not getting the quest reward. This also happened to other members of the party, and some members of the party also didn't recieve a reward. Thank you! And don't worry about fixing my health. I'll take care of it once the bug is resolved"

The party contains 128 members so the problem is likely caused by there being more updates being performed at one time than can be handled. Timeouts or similar are probably occurring.

**Comment by varjmes** [comment]
hi!

I am doing the egg collection quest but my eggs did not get shared today after the cron was supposed to tick over. All was fine yesterday. Any help greatly appreciated!

UUID: (81d68426-6be9-4433-9e33-410a7c5e7941)

**Comment by Alys** [comment]
@Charlotteis From what I can see from our records, you were resting in the inn that night - is that correct? If so, it's expected that you made no progress on the quest the next morning. That's one of the effects of resting in the inn.

**Comment by varjmes** [comment]
@Alys I never asked to rest in the inn, but it's possible I accidentally clicked something? That's very weird! I kept receiving eggs from my tasks.

The quest is over now, but I'll definitely check the inn next time. Thanks so much!

**Comment by Otocinclus** [comment]
Back with the same issue today (it's been a while since I noticed it happen!) I'm Chickenfox (dfa5d988-992a-4dec-8183-c15c8adb041f) I checked in last night hours before my cron from the iOS mobile app. My streaks are intact. When I logged in on Chrome this morning, I got a Daily Check in Incentive of 1 purple potion, but it is not appearing in my inventory (I have previously received a potion, that I used)
We are working on the Cheetah quest (group a5bb9da8-a8fe-4b3a-8ee1-27826878da08) and today is the first day of the quest. Two members of the party have done damage (as indicated in the group chat) but no damage from me is reported. I'm wondering if the issues are connected?
Thanks for the continued support on this vague and difficult bug! Let me know if you need any more information from me that I can get.

**Comment by Alys** [comment]
@Otocinclus Your check-in counter is 9, which means you've only received one Purple potion so far. The other incentive notification was telling you that a potion will be your next prize when you reach 10 check-ins. I'm sorry about the confusion! The incentive notifications of upcoming prizes are actually supposed to display a generic image rather than a specific prize to avoid people thinking that they've been given a prize on days when no prizes are due. We're going to get that fixed! Your lack of progress on the quest was probably just the normal occasional bug (although it's getting less occasional these days :( ). If it happened again on the next day, tell me because there can very rarely be a problem with corrupt data that prevents cron completing every day.

**Comment by Alys** [comment]
I haven't seen any reports of this in a while so I'm closing this. We can reopen it if it returns.
