### ISSUE TITLE
Third party tasks, blank tasks, otherwise really weird stuff

### ISSUE THREAD

**Issue by djstinkay** [HabitRPG/habitica#5989]
Checked off tasks last night using my pc, android phone, and ipad, no problem.  Woke up this morning and checked off a couple others on pc, still no issue.  Came in to work, about to check off another on my work pc and...what the hey??  Absolute gibberish habits and a blank "to-do".  Refreshed. Nothing.  Checked my android phone...the same gobbledegook!  Even weirder, the hover text for those gibberish habits reads "this task was created by a third-party service.  feel free to edit, it won't harm the connection to that service.  Additionally, multiple services may piggy-back off this task".  this is disconcerting, to say the least.  Why am I getting third party tasks??????
![image](https://cloud.githubusercontent.com/assets/10546438/10164550/1ebbd660-6688-11e5-995e-e3e042faef57.png)
![image](https://cloud.githubusercontent.com/assets/10546438/10164559/271ecbb4-6688-11e5-8f75-66ce640e78f1.png)
![image](https://cloud.githubusercontent.com/assets/10546438/10164569/3b675ae6-6688-11e5-8a9e-bda00cd0357b.png)

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/1402 for an explanation of the Habit. The To-Do will be from a similar cause. You can delete them.
