### ISSUE TITLE
API not returning max health & max exp (exp to level up)

### ISSUE THREAD

**Issue by arscan** [HabitRPG/habitica#599]
I've created a client using the API, and the piece of data that I'm really missing is max health & exp needed to level up (my client shows a progress indicator, similar to the website).  That seems like something that belongs in the data returned by /api/v1/user.

Thanks!

**Comment by switz** [comment]
@arscan We'll definitely add this, thanks for the suggestion. If you have any other comments on the API, please don't hesitate to contact us.

@lefnire how can we calculate this? 

https://github.com/lefnire/habitrpg/blob/master/src/app/scoring.coffee#L141 Where does `_tnl` get set?

**Comment by ruddfawcett** [comment]
Yep @arscan, had this exact problem as well.  You could also look at the TNL alg in the meantime...

**Comment by PhilipHow** [comment]
@switz https://github.com/lefnire/habitrpg/blob/master/src/app/algos.coffee#L11

The algorithm will be changed, but update there.

**Comment by switz** [comment]
@MrConcept Thanks. I've gone ahead and implemented that here: https://github.com/switz/habitrpg/commit/ef7d705059ac08cc58a56e9b9e0e016bffe8c7bb

Right now, I just added a `tnl` field to `user.stats`. Perhaps we should name it something a bit clearer.

Do you know where the max health is calculated? I'll send a pull request once I get max health in as well.

**Comment by switz** [comment]
Hmm, looks like health is constant at a max of 50. If I'm mistaken, please let me know. Sending pull request now.

If you want, @arscan, I can add a `maxHealth` field in as well, just in case we decide to raise the `maxHealth` one day.

**Comment by arscan** [comment]
Ah, sorry @switz, I didn't really take time to investigate how that maximum health value was calculated last night (it was late).  I thought perhaps some of the rewards might alter your max health.  I could just hardcode 50 on my side, but having rewards that increase your health is consistent with the RPG theme (although, I must admit that it would encourage procrastination).  I suppose from a game mechanics standpoint the longer you play for, the more you should get dinged for not performing tasks on time... and then you could upgrade your max health to give you more breathing room.  But that's out of the scope of this discussion.

Anyhow, I personally suggest adding that maxHealth into the data model and passing it back in the api.  Worst case it stays at 50, which will be a little more overhead in the api calls... but that is negligible compared to all the history data that is being shipped.  And I don't see the concept of a maximum health to disappearing anytime soon.

**Comment by switz** [comment]
Yup! I'll add it to the pull request. Should be live later today. https://github.com/lefnire/habitrpg/pull/601

**Comment by lefnire** [comment]
Yeah, well change max health with levels likely in the future, so this is
good to add

**Comment by switz** [comment]
Just note, I changed `user.stats.tnl` to `user.stats.toNextLevel` for clarity. If you already implemented `.tnl` please update it.
