### ISSUE TITLE
Unexplainable death?

### ISSUE THREAD

**Issue by dlshelman** [HabitRPG/habitica#5990]
Total damage recorded by Laundromancer was 27.7. I've done all my dailies. All my streaks have been reset to 0, I lost gold and such. I can't find a reason for the death! Additionally, I'm suddenly not dealing much damage at all compared to before. I used to average around 12-13, now it's 3, but none of my habits or dailies have changed at all. username grits32808. I know it wasn't because of someone else in my party because I'm the only one in the party.

**Comment by Alys** [comment]
I'm sorry about this @dlshelman! It will be an example of this bug: https://github.com/HabitRPG/habitrpg/issues/4313
There's an "Advice" section near the top of that issue which will help you recover from the unfair damage.
