### ISSUE TITLE
Pets Not Hatching 

### ISSUE THREAD

**Issue by Queenofjava** [HabitRPG/habitica#5993]
I have the potions and I have the eggs, but my pets are not hatching.  I have 90 out of 90 pets and 86 out of 90 mounts, this just started today.  

I mounted up one of my pets "zombie wolf" and tried to hatch another "zombie wolf" however it is not responding when I try to. I click on either the potion or the egg, try to click on the other and no response.

update - I was able to hatch the egg through my mobile app, so this is a problem with the site not the server.

**Comment by Alys** [comment]
Please reload the site and try again.

If it still fails, please go to Help -> Report a Bug and tell us the information requested in steps 6, 7, and 8.

**Comment by Alys** [comment]
Note that I can hatch pets using the site, so it's not a consistent problem. That's why we need the information requested.

**Comment by Queenofjava** [comment]
Step 6 - 4bdc9731-f7c2-4f32-a4f4-dc6670e6c6a4
Step 7 - I am using Safari on a MacBook Pro 
Step 8 - I get no javascript warning, actually I get nothing at all, when I click on the potion it highlights the egg that can hatch but I am unable to have it hatch, I try to click on it and nothing happens.

**Comment by crookedneighbor** [comment]
I just tried it on safari, and was not able to reproduce the error. 

@Queenofjava my best guess is that you have confirmation boxes disabled. When you click on a potion/egg, it asks you to confirm the hatching. If you have the confirmation box disabled, nothing will happen. 

Another place where it asks for a confirmation is in feeding a pet. Could you try feeding a pet and see if you get the same behavior? If you do, then it is most certainly that you have blocked confirmation dialogs.

**Comment by Queenofjava** [comment]
I can feed a pet with no problem.  My grand daughter was on my computer, is there anyway that she could have disabled the confirmation boxes?  If so, how can I enable them again???

**Comment by Alys** [comment]
@Queenofjava Close all browser windows to reset the confirmation.

**Comment by Queenofjava** [comment]
thank you Alys, closing all the browser windows did reset the confirmation :+1:

**Comment by Alys** [comment]
Thanks for letting us know!
