### ISSUE TITLE
Changes aren't made on the server after casting "Burst of Flames"

### ISSUE THREAD

**Issue by LuneFox** [HabitRPG/habitica#5994]
Maybe it's a temporary bug, but I think that I'll leave it here just in case.

I'm trying to cast Burst of Flames on a task, and casting it should make me level up (from 29 to 30) and grant me a level 30 quest scroll. Local calculations in a browser are made, and I see the info about unlocked quest, but the result isn't sent to the server. At the same time an error pops up as a notifiaction that says `Cannot set property 'drop' of undefined`.

When I refresh the page, I see the old numbers that were there before leveling up. Even after restarting the browser, using a different browser and refreshing the page again, nothing changes. Repeating an action causes the same thing - I level up, get a scroll, an error pops up, and refreshing the page proves that nothing has changed on the server. It doesn't matter what task I cast the skill on.

Other changes are reflected and stored on the server just fine (adding tasks, renaming tasks, completing other tasks work well, and the results are stored after the page is refreshed.) It seems that the script cannot process this specific action. 

P.S. All previous instances of Burst of Flames on that day also worked fine. It's somehow linked to levelling up.

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/4986 for the explanation and fix.
