### ISSUE TITLE
Bug:  Dailies not resetting

### ISSUE THREAD

**Issue by ctuirmt00** [HabitRPG/habitica#600]
For some reason my dailies aren't resetting.  For the past two days (coincides with when I enabled custom time start, but might not be related?) my dailies have not reset.  They stayed greyed out and checked, from Sunday.. It's not Wednesday.  Just letting you know.  That's the only information I have!

EDIT:  Nevermind.  It actually just reset!

**Comment by Pandoro** [comment]
Ooooh I was just going to report this as OMG CRITICAL :D 

Glad it worked out again. Please let us know if it occurs again. This is the kind of stuff that is really critical, hopefully it was just some minor hick-up. 

There have been other cases where the daily custom reset has not worked, but not in this kind of way. We are looking into this! Hopefully it will cause no more problems! 

I will close this for now, too keep the board clean and tidy, but feel free to re-open this, or to create a new ticket if it occurs again!
