### ISSUE TITLE
Avatar customization buttons are too large

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6001]
The current layout of the avatar customization page uses the full size of the component sprites for each of the buttons:
![image](https://cloud.githubusercontent.com/assets/4501321/10257742/c850b180-691e-11e5-9700-83a205c62d3c.png)
Until recently, it wasn't that way. We used smaller versions of the sprites, focused in on the specific piece instead of the full avatar size:
![image](https://cloud.githubusercontent.com/assets/4501321/10257599/f831f4be-691d-11e5-9c54-30c3d7dcb161.png)
Running `git bisect` while examining the customizations page tracked the issue to commit d3d365a, which was when we first ran our sprite compilation script using `gulp` instead of `grunt`.

Starting at https://github.com/HabitRPG/habitrpg/commit/d3d365a74ac6cf8395add8e934e214726e9e3591#diff-26a7d7ac95076ca33f51a210fce258c0R112 , setting up `sprite.custom` is supposed to build out `.customize-option.SPRITENAME` classes that shrink the buttons down to the relevant portion of the sprite. However, this is not happening; the `customize-option` class applies a `margin-right` of `10px` and nothing more.
##

**Comment by Alys** [comment]
This was fixed.
