### ISSUE TITLE
Hatching pets - in the pop up a dialog box comes up 

### ISSUE THREAD

**Issue by webir** [HabitRPG/habitica#6004]
Hatching pets and when the pop up dialog box came up to confirm hatching, there was a box to click to turn off the pop up. I assumed it meant I wouldn't have to confirm that pop up to hatch a pet. Instead? Can't hatch my pets (using magic potions). 

Help?

**Comment by Alys** [comment]
That ability to turn off the popup is implemented by your browser, not by Habitica. Ticking that checkbox prevents Habitica from showing you the confirmation step, and hence prevents you from feeding your pets. Close all browser windows and reopen them to make the popup come back.
