### ISSUE TITLE
Estimate issues duration

### ISSUE THREAD

**Issue by urecio** [HabitRPG/habitica#6012]
Atm there are more than 400 issues opened.
As an idea to get more collaborators, (I know this could be very subjective) If someone with enough experience on the project could mark (with a tag) the estimated duration of some issues, people with a "concrete" free time will be able to pick up issues more easily.
Example of tags:
- Quick: 15 - 30 mins
- Medium: 1 - 2 hours
- Long: 1 - 2 days

**Comment by Alys** [comment]
@urecio Thank you for suggesting it. I've been thinking about it and it does seem like a good idea in theory, but I think in practice it would cause problems and perhaps make things harder for the contributors. The time taken to resolve an issue depends very heavily on the technical knowledge and experience of the coder, and also on the method they choose to solve it. We can't predict any of that so any time we estimated for an issue could end up being very inaccurate. In addition, after a coder has submitted a pull request, we review it and we might need to make several suggestions for further changes for code quality or other reasons. It's not impossible that an issue tagged as quick could end up taking a week or more.

Any programmer looking for an easy issue can look through those tagged with the [entry level coding](https://github.com/HabitRPG/habitrpg/labels/entry%20level%20coding) label. That identifies issues that should be easy to fix, although we still can't predict the time that the programmer would take. Any issues not listed there are likely to be medium or large fixes.
