### ISSUE TITLE
can't delete anything

### ISSUE THREAD

**Issue by leafyavian** [HabitRPG/habitica#6019]
Hello! I've come back to habitica after maybe half a year of absence, but I don't seem to be able to delete habits, dailies, to-dos, or rewards. This is the only issue I've noticed -- I can still create, edit and check them off, but attempting to delete them results in nothing happening. I've reset the page a few times, logged out and in again, and left and re-entered the tavern, but haven't tried anything else. 

i'm using google chrome on windows 10, and my user ID is e3455c7c-8e66-4fd7-84bf-f6467f3445d9.

**Comment by Alys** [comment]
It's most likely that they are tasks from challenges. Please see the wiki's [Challenge](http://habitica.wikia.com/wiki/Challenge) page for information about challenge tasks - the "Deleting a Challenge Task" section (section 9) should help. Let us know if they aren't challenge tasks.

**Comment by leafyavian** [comment]
They weren't challenge tasks -- but they're deleting just fine today, so I won't worry too much about it.

**Comment by Thomas0921** [comment]
because we check the "Stop creating additional dialog" after we click the trash icon. So it wont ask us about want to delete it or not anymore. Help

**Comment by Alys** [comment]
@Thomas0921 https://github.com/HabitRPG/habitica/issues/6330#issuecomment-257988635
