### ISSUE TITLE
Daily tasks reset?

### ISSUE THREAD

**Issue by hoylemd** [HabitRPG/habitica#602]
My daily tasks for today got reset somehow an hour or so ago.  I'll try to reproduce it when i have some time.

**Comment by wc8** [comment]
I'm assuming you don't have a custom day start for when that reset happened then, but just in case: you can check in the settings (drop-down menu next to login).

**Comment by hoylemd** [comment]
I actually didn't have one set at all.  I thought i had it set for 2am, but I guess not.  I suspect that custom start times are related, but I haven't gone into the code yet.

**Comment by rixx** [comment]
Has this happened again or were you able to reproduce it?

**Comment by hoylemd** [comment]
I haven't actually been using HabitRPG regularly for quite awhile, but I don't remember it happening again sicne I opened this issue.

**Comment by rixx** [comment]
Might aswell close it, then :)
