### ISSUE TITLE
levelling up after level 100 becomes progressively harder but with no matching benefits

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6021]
I'm not sure if this is something we want to change, so coders should not work on it until it's been discussed.

Habitica is optimised for levels up to 100 only. After level 100 we don't give attribute points, and when a player rebirths at above level 100, we don't state the exact level - we treat all levels above 100 as if they were 100.

However the amount of XP needed to level up keeps increasing at each level after 100. This seems inconsistent and perhaps unfair. If we don't give benefits to extra levels, should we be making them harder to achieve?

Should we instead make it that every level after 100 can be reached with 3640 XP (the amount of XP needed to level up from 99 to 100)?

@lemoness What do you think? Opinions from others are very welcome too!

Reference: The level-up formula and numbers are given in [Experience Level Chart](http://habitica.wikia.com/wiki/Experience_Level_Chart). 
Code: [api.tnl in script/index.coffee](https://github.com/HabitRPG/habitrpg/blob/51355f7eea68376e29b92fb5c13e20a72c074fda/common/script/index.coffee#L137) and [addOneLevel in footerCtrl.js](https://github.com/HabitRPG/habitrpg/blob/51355f7eea68376e29b92fb5c13e20a72c074fda/website/public/js/controllers/footerCtrl.js#L121)

**Comment by Thrashmandicoot** [comment]
In Heroes of the Storm, a moba by Blizzard entertainment, the developers chose to keep the standard algo when advancing past lvl 10 (harder to earn lvls past 10). 

While they offer small rewards for reaching certain levels, they don't offer any additional asthetics (which players gain while progressing up to 10) which makes it comparable to Habitica. I think the rebirth orb offers a great solution for players that want it easy, they can start over, and for those that enjoy progressively harder leveling, can choose to stay 100+. Plus, it's less to modify if there is to be a benefit past 100 in the future.

**Comment by SabreCat** [comment]
I'm in agreement with @Thrashmandicoot. The Orb is free to use once you hit 100, so people can kick it in or not at their discretion. As far as game design goes, it's pretty solid.

That said, the design might not be super clear to users at the moment--do we provide an explanation of post-100 play when you reach that point?

**Comment by relsqui** [comment]
I also think it's okay as it is. Another analogy is skill levels above 100 in Runescape -- they don't do anything, but some people choose to pursue them anyway just for style points or to compete on the leaderboard. Getting to high level is a bragging right, and it's easy not to pursue it if that's not valuable to you.

**Comment by crookedneighbor** [comment]
I agree that this should not be changed.

**Comment by lemoness** [comment]
Since this is something that we don't want to change at this time, I am going to close this ticket. If anyone still feels that this point should be debated, feel free to keep commenting.
