### ISSUE TITLE
A "completed date" for todo tasks that have been finished would be very useful for my API client

### ISSUE THREAD

**Issue by arscan** [HabitRPG/habitica#603]
I've set up my client so that it shows you how much "stuff" you've done over the last 24 hours (e.g. +4 habits today, 2 todos completed today, etc).  I'm able to calculate that number for habits by looking through the habit history and watching how many times the associated score went up/down over the last day, but I don't think there is anything I can key off of for todos.

The most straightforward solution would be to add a "completedDate" (or more generically "lastActionDate" or something similar so it would apply to the other task types) to the task.  That way I can figure out how many todos I've done in the last day.  That would also let me continue to show my recently completed tasks in the interface... I'd like to keep those showing up for a day (with a checkmark) so I can see how much I've done today.

A screenshot of what I'm building towards in the README of the project in the following link... note I wanted to keep recently completed todos around, and have a running tally of todos completed during the day:  https://github.com/arscan/habitrpg-ncurses

It seems like a pretty straightforward enhancement and could be used it many ways (to generate reports, etc).  Or let me know if I've missed any data in the API that I could use for this functionality.

Thanks!

**Comment by switz** [comment]
Cool, I'll add this in. We don't currently record when a task is complete, but it's something we should track. Hopefully we'll have this in by tomorrow for you. Nice suggestion.

**Comment by lefnire** [comment]
Hey Rob! habitrpg-ncurses, big hit - we're talking about it over in IRC :) Quick thought, since you're an API consumer, and a JavaScript dev to boot, any way I can con you into helping in the API? [This](https://github.com/lefnire/habitrpg/blob/master/src/server/api.coffee) is the file, if there's anything you want that we're not providing, don't hesitate to PR us.

**Comment by paglias** [comment]
I'm going to add this, but @lefnire... what to do with old todos?

**Comment by lefnire** [comment]
if we do this after we move to subdocs user.todos, we can give it a default value:

``` javascript
habits: [{...}],
dailys: [{...}],
todos: [{
  value: ..,
  completionDate: {type: Date, 'default': Date.now}
}],
```

If we don't want to wait till then, I can run a migration script to set all completeds to `+new Date()`. I recommend we wait till we're using subdocs, we can tackle that this week or weekend

**Comment by paglias** [comment]
No problem waiting for subdocs :)
Il giorno 18/set/2013 20:39, "Tyler Renelle" notifications@github.com ha
scritto:

**Comment by kenfink** [comment]
I'd love to help with this if I can.  Can someone point me in the right direction?

**Comment by lefnire** [comment]
This is actually complete, stored as task.dateCompleted
