### ISSUE TITLE
"All", "Due", "Gray" tabs in task switcher looks incorrectly positioned for some languages

### ISSUE THREAD

**Issue by Anton-Davydov** [HabitRPG/habitica#6030]
Hi guys,

I noticed that for some languages tabs in task switcher are incorrectly positioned.

This is what I mean:
![image](https://cloud.githubusercontent.com/assets/2435179/10402843/628e1150-6ed0-11e5-94d9-66e807291f9a.png)

Look at the daily switcher - "Обязательно" takes two lines, and "Все" looks misplaced because of it. I tried to switch between languages, and it looks fine for English, but for Nederlands, Russian, and maybe more it looks misplaced.

I think that in such cases buttons in tabs should have height = 100% and label in this button should be vertically centered.

**Comment by Alys** [comment]
Thanks for reporting this @Anton-Davydov but we're tracking this display issue in https://github.com/HabitRPG/habitrpg/issues/5980 so I'm closing this one. You're welcome to comment on that issue if you wish.
