### ISSUE TITLE
cannot keep order of to-do list

### ISSUE THREAD

**Issue by jessyjetpacks** [HabitRPG/habitica#6032]
my id 50ae9990-45f6-4fbc-9225-8a189b682267
using safari browser. OS mac x yosemite 10.10

i am able to push tasks to the top of the to-do list. but they will not stay in the order i put them. they rearrange seemingly at random as soon as i do a task or refresh the page, or log in after logging out. 
it has always been like this. but it would be really good if it wasnt because i would like to prioritise tasks, and now im a paying member i thought i would report this bug. 

thanks

**Comment by Alys** [comment]
This has been reported in https://github.com/HabitRPG/habitrpg/issues/2606 so you can subscribe to notifications on that issue to receive updates about the fix (subscribe button is in the right-hand column) and you can read about a workaround in it. Note that it happens to all players equally, including to all paying subscribers.
