### ISSUE TITLE
No spells available for a mage character

### ISSUE THREAD

**Issue by Manyack** [HabitRPG/habitica#6036]
Hello, 

My nephew has just reached the level 10 and chosen the Mage class, but he has not spells available. 
My son has chosen the rogue and has no problem, and when I chose the healer long time ago, I had no problem too. 

Could you please tell me what's wrong with the mage? My nephew character is the one named ET.

**Comment by Alys** [comment]
The first skill for any class becomes available at level 11, the others at each level after that. You can learn more on the wiki's [Skills](http://habitica.wikia.com/wiki/Skills) page. Note that if you are using a mobile app, skills might not be available on it yet.
