### ISSUE TITLE
After "Orb of Rebirth", all previous-class limited gear missing

### ISSUE THREAD

**Issue by r0flm4k3r** [HabitRPG/habitica#6037]
User ID: e713810b-fde5-4335-a200-2851af2e5c8f

After using "Orb of Rebirth", I was under the impression that I would keep all of my previous class gear, including espeically "Special" items, such as the Summer and Fall (Halloween) items.

I used an Orb sometime after level 100 as a Mage (several levels, not sure when exactly), and reset back to level one. After reset, none of my mage gear is available. 

After purchasing all available Warrior gear, including more than several "Enchanted Armoire", enough to get all of the new class's (Warrior) limited Halloween gear. My Mage's Summer and Fall (Halloween) gear, along with all other previously earned Mage gear (except for Apprentice Staff) is gone.

Is this a bug, should my Mage gear, especially the limited time gear, be available at this point?

**Comment by Alys** [comment]
Please see my response to https://github.com/HabitRPG/habitrpg/issues/6031 for an explanation about how the Orb works with respect to equipment. The wiki link there will explain further.

**Comment by r0flm4k3r** [comment]
"Limited edition equipment that the player had previously purchased (for gold, or for gems in the Seasonal Shop) will become available to be purchased again. Items that had been purchased for gems will be purchasable for gold, at their usual gold price."

Then this does not apply?

**Comment by Alys** [comment]
Yes, it applies.

Please see the paragraph immediately after that that explains about class-specific gear.
