### ISSUE TITLE
Can't Add Tag to Task in API With Javascript

### ISSUE THREAD

**Issue by krekkon** [HabitRPG/habitica#6047]
I try to build my own task inserter.

Everything is posted correctly to my account except the tags.
The tags are working as I do not send anything, but i send.

Here is my actual code: http://jsfiddle.net/Krekkon/ke64ovjd/
The intresting part is at line 67 of Javascript section.

Could you please have a look why the tags are not stored with the task. I belive there is issue with the types or posting properties, but do not see the way to solve it.

Here are two picture (http://imgur.com/a/vSxNXl) the post, first is my implementation, second it the Public API. As you know mine not working, but the API do. :)

**Comment by crookedneighbor** [comment]
I've confirmed this behavior. Looks like the api doesn't allow setting a tag on task creation? Looking into fixing this.

**Comment by krekkon** [comment]
Thank you very much, It would help a lot.

**Comment by Alys** [comment]
I create tasks very often using the API and tags are certainly added to those tasks correctly. Here's debug output from my shell script from a successful test:

```
$task_json:  "text":":house: test","type":"todo","value":"0","priority":1 , "tags": { "2a1295e3-7bd2-44fb-a1ce-52be79fc90a0": true, "8864f41e-40e1-4a03-867b-456f8b4ed58a": true, "acc99185-dfe2-4680-b887-f5b8b4688ee3": true }

eval curl https://habitrpg.com:443/api/v2/user/tasks -s -X POST --compressed -H "Content-Type:application/json" -H "x-api-user: $userid" -H "x-api-key: $api_token" -d "{ $task_json }"
```

**Comment by Alys** [comment]
I've just tested your code now without making any changes to it except that I put in the IDs for my own tags, and it worked correctly. The right tags were added to the tasks. Do the tag IDs in your test code match the tag IDs in your Habitica account?

**Comment by crookedneighbor** [comment]
@alys, I did the same thing and could not get the tags to apply. :/

**Comment by Alys** [comment]
Odd.  I just did a second test and it's still working for me. I created a html file with the basic html, head, script, body tags, pasted the js code from http://jsfiddle.net/Krekkon/ke64ovjd/ into the script tag, pasted the html code into the body tag, edited `var apiUser = "";` and `var apikey = "";` to contain the correct values (for a different account than previously), then edited `"tags": {"dfd72d92-0868-4f8d-8e78-adf4b2fa32df" : true, "964b610e-7b51-42c9-a263-50fc604c24c7": true},` (line 72 from the jsfiddle) to change the tag IDs. That's all I changed. When I clicked send, the "Create HTML For API" task was created with the tags I had chosen when I edited line 72.

**Comment by Alys** [comment]
One additional thing I did: I put this at the top of the <head> tag: `<script type="text/javascript" src="https://ajax.microsoft.com/ajax/jQuery/jquery-1.4.2.min.js"></script>`

**Comment by krekkon** [comment]
I made a demo account for this, (and for other purposes also) but you can use that for testing.
Krekkon_Demo/asdasd

And here is the small skeleton of the code with the demo credentials:

http://pastebin.com/PmvtjMiU

Still not apply tags.

**Comment by Alys** [comment]
I'm still not seeing the problem. I've done numerous tests with my account and with your Krekkon_Demo account, and every one has inserted the tags correctly. On your test account, I've done it with the "New" and "New2" tags, and with all five tags, and with just the default "morning" tag, and they've all worked as expected. 

Also, the tasks that were in the demo account before I used it do have tags applied. 

Can you please describe why you think the tags aren't being applied?

**Comment by krekkon** [comment]
Hmmm Nice, 
I know already what could be the issue there. :)
Please Edit the Alys todos. Once you open up the edit screen of the todo, you will see no tick next to "Morning". 
All of my previous test were checked like this. 

But as i can see when I select "Mornig" from menu, to find morning todos, some of them is select.

So we probably tested it differently. :)

I think this is a bug, But not so big as I thought, and not so small as you thought.
Only the tags should be ticked on edit screen.

**Comment by Alys** [comment]
Okay, I see the problem now. Describing what you see in detail when there's a bug can help us solve it more quickly. :)

Your code is inserting tag values as `"true"` (with quotes), whereas it should be making the values just `true`.

The only change we might want to make to the API is prevent it accepting incorrect values. If we decide to do that, we'll put it into a different issue. We're planning some big changes to the API in future so that's probably something for that change.

**Comment by Alys** [comment]
The first couple of hits here look promising:

https://www.google.com.au/search?q=jajax+sedning+json+converts+true+to+string&oq=jajax+sedning+json+converts+true+to+string&aqs=chrome..69i57.7470j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=ajax+sending+json+converts+true+to+string

**Comment by crookedneighbor** [comment]
That must have been what was happening when I tested the script. Good work @Alys

**Comment by krekkon** [comment]
Hmm finally found:
contentType: "application/json"
data: JSON.stringify(data),

These two property what was used incorrectly, or not together. Previously tried a lot of combination, but this one was not in the set. Even with the request header content-Type wasnt worked, but that seems to be the really different thing.

Btw Thank you very much guys. Here is the actual working demo
http://pastebin.com/Y3riSipq

And here is the implemented bigger one with full fancy, if you are intrested in.
http://pastebin.com/hTVVjjXT

Thank you again, guys.
