### ISSUE TITLE
Party invitation does not go away.

### ISSUE THREAD

**Issue by swistak** [HabitRPG/habitica#6051]
![party_invitation_error](https://cloud.githubusercontent.com/assets/22162/10538440/aef45cde-73f8-11e5-988c-fed01cd0da58.png)
After joining a party the invitation does not get away. I get notified non stop about joining new party (the same one I'm currently in).

I've tested this on several different parties. Invitations simply seem not to expire when they are accepted.

**Comment by Alys** [comment]
@swistak I'm afraid we can't help you without being able to identify your Habitica account. Could you please go to Help -> Report a Bug in the Habitica website and see step 6 in the page you'll be taken to? That tells you how to find your User ID. Once we have that, we can fix this for you.

**Comment by swistak** [comment]
user id: a847788d-5f96-4bf3-94c5-7e1ac7b4cb0c

problem does not seem to exist anymore though

**Comment by Alys** [comment]
Thank you for telling us. If it happens again, please post your user ID to this issue: https://github.com/HabitRPG/habitrpg/issues/5649
