### ISSUE TITLE
Cannot leave a group.

### ISSUE THREAD

**Issue by swistak** [HabitRPG/habitica#6052]
While trying to leave a group i get an error:

```
Please reload, "Error Runner error: Overflow sort stage buffered data usage of 34313539 bytes exceeds internal limit of 33554432 bytes" 
```

The API returns

`"NetworkError: 500 Internal Server Error - https://habitica.com/api/v2/challenges"`

**Comment by Alys** [comment]
Please tell us your User ID and the ID of the group - see step 6 of Help -> Report a Bug for details.

**Comment by swistak** [comment]
user id: a847788d-5f96-4bf3-94c5-7e1ac7b4cb0c

I dont' have group id of that group. Friend of mine left it and it got disbanded i think?

**Comment by Alys** [comment]
Okay, thanks for letting us know. I'm closing this since no action is needed now.
