### ISSUE TITLE
Cannot register or log in using javascript forms

### ISSUE THREAD

**Issue by swistak** [HabitRPG/habitica#6053]
After signup or log in, I don't get redirected at all, have to reload the page to log in.

**Comment by crookedneighbor** [comment]
Please provide more details about the device and browser you are using. I.e., is it a Windows 7 pc on internet explorer 8? Or an iPhone 6 using mobile safari?

**Comment by swistak** [comment]
Sorry about this. Tested on both Linux and Windows, Chrome and Firefox. Neither worked.

**Comment by swistak** [comment]
After killing all cookies I can confirm it now works everywhere. Seems there's an issue with angular.js. I think lots of errors I've been having are related to one core error in angular that happened when I registered through email invitation. I don't know what was the root cause, but it causes whole tons of issues that made Habitica completely unusable for me.
