### ISSUE TITLE
Notifications button/icon is difficult to maintain

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6058]
The structure of the notification bubble ![image](https://cloud.githubusercontent.com/assets/4501321/10553587/aa306390-7421-11e5-96d4-bbfe4c276153.png) makes it very difficult to extend as new notifications are added. To add a new notification, the following places need to be updated:
- The `selectNotificationValue` function https://github.com/HabitRPG/habitrpg/blob/2d862593ae4152e2b3a61c66f71dc203ea2341de/website/public/js/controllers/menuCtrl.js#L12
- The `hasNoNotifications` function https://github.com/HabitRPG/habitrpg/blob/2d862593ae4152e2b3a61c66f71dc203ea2341de/website/public/js/controllers/menuCtrl.js#L44
- The `ul` containing the list of notifications in the menu, https://github.com/HabitRPG/habitrpg/blob/2d862593ae4152e2b3a61c66f71dc203ea2341de/website/views/shared/header/menu.jade#L179
- (Optional but often needed) A means of clearing the notification, e.g. https://github.com/HabitRPG/habitrpg/blob/2d862593ae4152e2b3a61c66f71dc203ea2341de/website/public/js/services/chatServices.js#L24
- (In some cases) A place in the user model to contain the notification, e.g. https://github.com/HabitRPG/habitrpg/blob/a4b1c6cf64e2197792f317bcc8e5fed1b983bb42/website/src/models/user.js#L123

There ought to be a more extensible way of factoring this, where we maintain a single list of notification types and then iterate over that to generate the menu and choose the icon. ~~Perhaps an array or object in our `content` files?~~
##

**Comment by Spidy88** [comment]
What about an AngularJS [constants](https://docs.angularjs.org/guide/providers#constant-recipe) or [values](https://docs.angularjs.org/guide/providers#value-recipe) array/object that holds all the values.

Then add a NotificationsService that holds all logic related to notifications. Then any Controller that needs it just injects it and calls it. Keeps the logic out of controllers

**Comment by crookedneighbor** [comment]
I'm interested in the constants route.

This should not be stored in content. As it is not content.

**Comment by Alys** [comment]
I've marked this as on hold until coding is started for the website improvement project, but if any other admin disagrees, I'm happy for it to be changed to help welcome.

**Comment by lemoness** [comment]
Is this still an issue @sabrecat?

**Comment by TheHollidayInn** [comment]
Yea, we need to refactor this. There are three ways to refactor Type code and I’m sure we can remove some other parameters etc here.

**Comment by paglias** [comment]
This will be fixed in #9716
