### ISSUE TITLE
[Suggestion] Varied food for the pets

### ISSUE THREAD

**Issue by Spidernaevi** [HabitRPG/habitica#606]
Hi there,

I've seen the [Pets and Mounts Trello card](https://trello.com/card/pets-and-mounts/50e5d3684fe3a7266b0036d6/166) and I've been wondering about the nutrition of the pets/mounts. I was wondering if there are any alternatives to meat as quite some people are vegetarian and might take offence. There could even be a funny touch to it, like pink and blue cotton candy/lollipops for the cotton candy versions, strawberries for the red version, an acid potion for the skeletons or alchemy powder for the golden versions (you know turning copper into gold). 

I know it is just a game, but I think having more options than only meat would be cooooool!

**Comment by wc8** [comment]
I added your suggestion as a comment on the Trello card.

**Comment by Spidernaevi** [comment]
Thank you :)
