### ISSUE TITLE
No site icon on mobile (favicon for website on mobile browsers)

### ISSUE THREAD

**Issue by alarsyo** [HabitRPG/habitica#6060]
I'm using Habitica on my phone (Android 5.1.1, Chrome 45), on the mobile website rather than the app because of its lack of feature.
To easily access the website, I used the Chrome option to pin a shortcut to the site to my homescreen, and this usually uses the website icon (favicon ? ) as the homescreen icon. 

But on mobile, the Habitica website icon isn't displayed (works fine on chrome desktop), so instead of the purple dragon I get the first letter of the site's name, a huge H on my homescreen. I'm sure this is easily fixable. 

![screenshot_2015-10-17-14-02-37](https://cloud.githubusercontent.com/assets/15170378/10558649/208565ac-74d8-11e5-9cb6-008ef3a10890.png)
![screenshot_2015-10-17-14-03-08](https://cloud.githubusercontent.com/assets/15170378/10558648/208487cc-74d8-11e5-86ba-a0f28c889144.png)
##

**Comment by alarsyo** [comment]
Interesting find that might help understanding the problem : 

I was using Android's "merged tabs and apps" feature, that displays browser tabs with other applications. So browser tabs look this way : 

![screenshot_2015-10-17-14-09-21](https://cloud.githubusercontent.com/assets/15170378/10558701/dff55dd8-74d9-11e5-822b-2e355391722b.png)

Now we can see that facebook's website, and Android Police, display their icon correctly, while Habitica does not. 
Now if I switch to a standard "tabs within the Chrome app" view, I get this : 

![screenshot_2015-10-17-14-10-25](https://cloud.githubusercontent.com/assets/15170378/10558716/218fb482-74da-11e5-88c8-c47011ba9c29.png)

The icon is, this time, displayed correctly. However, while attempting to pin it to my homescreen, I still get the same result : Huge purple H instead of the dragon : 

![screenshot_2015-10-17-14-11-17](https://cloud.githubusercontent.com/assets/15170378/10558723/627dbaf2-74da-11e5-966a-cacdbf26db6b.png)

While this works fine with other sites : 

![screenshot_2015-10-17-14-11-53](https://cloud.githubusercontent.com/assets/15170378/10558724/7eb9d368-74da-11e5-8cc5-c786d6db1c1b.png) 

![screenshot_2015-10-17-14-12-56](https://cloud.githubusercontent.com/assets/15170378/10558728/9d10ba16-74da-11e5-8c44-8929cf40537e.png)

So the problem would be that Chrome grabs the icon a different way when creating a shortcut, or using merged tabs and apps, and Habitica doesn't provide an icon in this case ?

**Comment by crookedneighbor** [comment]
If Android handles it like iOS, it'll require a special meta tag that provides the image. Anyone using an Android want to verify that and submit a PR?

**Comment by anilanar** [comment]
@crookedneighbor It does require a meta tag as you've suspected. I'll test it on Android and do a pull request.

**Comment by anilanar** [comment]
I've tried adding `<meta name="mobile-web-app-capable" content="yes">` as documented and tested it on Chome 46, Android 4.4.2 on an LG device with no avail. It still displays the correct icon in tab switcher while fails when trying to "Add to homescreen".

**Comment by anilanar** [comment]
I tested it with a random 144x144 png icon and it worked. Adding to homescreen won't work either because of ICO file format or 32x32 resolution. Android docs recommend 192x192 PNG icons.

**Comment by Spidy88** [comment]
Jade:
`link(rel='icon', sizes='192x192' href='/apple-touch-icon-144-precomposed.png')` 
HTML:
`<link rel="icon" sizes="192x192" href="/apple-touch-icon-144-precomposed.png')`

Using one of the existing icons, this fixes the issue. Now we just need the right icon at the recommended 192x192 pixels. 

![screenshot_2015-10-17-20-31-27](https://cloud.githubusercontent.com/assets/1076168/10562400/682c5d70-750f-11e5-9999-77bbce9b9005.png)

**Comment by Stercus** [comment]
I would like to take this.

**Comment by Stercus** [comment]
![habitica-192x192](https://cloud.githubusercontent.com/assets/15823400/11131554/37fb7128-8959-11e5-9e2d-96a44ea9b5b4.png)

**Comment by danielvancamp** [comment]
Hey guys, 

just checking into this one, here is the favicon in 192x192.
I couldn't find the SVG (or other vector format) for the logo though. Is it around or is it useful if i make it?

![favicon_192x192](https://cloud.githubusercontent.com/assets/8830345/11372955/6b46ac70-92d0-11e5-9a5a-8c80abf71e1e.png)

if you want i can create a pull request (i think) and put the resource file in the codebase, just let me know. 

Thanks!
