### ISSUE TITLE
Page never fully loads, Returns error

### ISSUE THREAD

**Issue by BrandonStitt** [HabitRPG/habitica#6063]
My user ID: 8902a7ac-cd66-48cb-86cf-fb539b612a15
My group ID: ef6d7285-5af3-4168-860f-7b750c103a79

When I reload the Habitica page, my group partner isn't shown and the page loads slowly. After it gets to ~98%, it stops loading and gives an error message a few minutes later. If I go to the party menu, it shows me as not being in a group at first, but once it loads past ~75%, it shows my party menu just fine. Even once I'm in the party, my group partner's avatar doesn't show on the top bar. When I first joined the group, it said I had an invitation to the group I was in after I joined, but I ignored it. Now that invitation doesn't show anymore. I attached three screenshots that will hopefully help

Initial page laoding:
![image](https://github-cloud.s3.amazonaws.com/assets/15184646/10565810/97b00388-758e-11e5-9405-43be073182f4.png)

Error message:
![image](https://github-cloud.s3.amazonaws.com/assets/15184646/10565813/ac8eb7e0-758e-11e5-9d36-59daa47fb34a.png)

Party page: 
![image](https://github-cloud.s3.amazonaws.com/assets/15184646/10565817/bdd91f72-758e-11e5-9c86-0ee937feb7aa.png)

Thanks for the help!

**Comment by BrandonStitt** [comment]
This seems to have fixed itself. I'll reply to this if it happens again. Sorry for wasting your time

**Comment by crookedneighbor** [comment]
No worries, glad it's working.
