### ISSUE TITLE
Unable to delete task "Habit"

### ISSUE THREAD

**Issue by hartalex** [HabitRPG/habitica#6067]
![screenshot](https://cloud.githubusercontent.com/assets/2790192/10582495/cfb1b2ee-764d-11e5-9699-ac75898d2077.png)

I have a habit that I am unable to delete.
I've renamed the task to "Cannot Delete".
I get the delete confirmation, but then nothing happens.
I tried on the website and in android.

This task seems to be in a strange state, as it also shows the check box instead of the usual +/- buttons for habits.

Can you please delete this task?

Thank you,
Vorgone

18be44b2-acf0-47a8-a7af-1dcde2ff09a2

**Comment by crookedneighbor** [comment]
I've removed it. It was a task with `type: 'daily'` in the habits array:

```
{
            "text" : "Cannot Delete",
            "challenge" : {},
            "attribute" : "str",
            "priority" : 1,
            "value" : 29.0727152167346503,
            "tags" : {},
            "notes" : "",
            "dateCreated" : ISODate("2014-10-22T01:30:50.769Z"),
            "id" : "c3013402-de86-433e-b2f5-c0fdc43a2884",
            "down" : true,
            "up" : true,
            "history" : [ 
                {
                    "value" : 1,
                    "date" : 1413941489849.0000000000000000
                }
            ],
            "type" : "daily"
        }, 
```
