### ISSUE TITLE
Can't see Habit, To-Do and Daily

### ISSUE THREAD

**Issue by Forzan** [HabitRPG/habitica#6070]
Hello, I can't see any of my habits, to-dos or dailies in the home of Habitica. I can only complete my habits and to-do using the Android app but not with the ability of my class.

User ID: 96103a0b-5f1d-453d-9112-afc928b52a9d
User Party: 8097ebf2-96e9-4c6d-bafc-dc772669dd7c
Browser: Google Chrome
Operating system: Windows 10

**Comment by Alys** [comment]
Please click the "clear" button to the left of your tags, even if it looks like no tags are selected. Please also ensure that there is no text in the search box above the Rewards column.

Does that make your tasks reappear in the website?

**Comment by Forzan** [comment]
Yeah!
Thanks you so much! :)

Date: Tue, 20 Oct 2015 12:27:34 -0700
