### ISSUE TITLE
Babel task causes nodemon to restart the server repeatedly

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6071]
When starting up a Habitica server using `npm start`, `nodemon` starts up before `babel:common` does. `babel` then does a bunch of compile work, changing files that `nodemon` monitors, so `nodemon` restarts the server. Dozens of restarts can occur before `babel` finishes. It doesn't seem to have a huge adverse effect, but it is at least a nuisance when examining server output in the terminal.

Perhaps `nodemon` could wait to launch until after file-modifying tasks have completed?
##

**Comment by SabreCat** [comment]
Pinging @crookedneighbor, who I believe knows how to fix this.

**Comment by TheHollidayInn** [comment]
Can we just reorder the Gulp tasks to fix this? I'm happy to try it out.

**Comment by SabreCat** [comment]
This actually isn't happening for me anymore. It restarts once, but it doesn't fill several terminal screens with restart notifications like it used to.
