### ISSUE TITLE
Dailies progress bug

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#608]
I use habitrpg in the latest version of Firefox, adbock is turned off.
Habits progress chart works fine, but none of the dailies charts are working:

![2013-03-07_052800](https://f.cloud.github.com/assets/3543515/230533/6330daba-86c6-11e2-8d11-f759cd97e196.png)

**Comment by wc8** [comment]
See #315

**Comment by hjalmberi** [comment]
Thank you, it didn't show up in the search

**Comment by wc8** [comment]
I'm closing this for housekeeping. Follow up via #315
