### ISSUE TITLE
Mounts staying in Pet Area - not transferring

### ISSUE THREAD

**Issue by jrodii** [HabitRPG/habitica#6081]
User ID: beaeaaa0-3528-4a6e-9ef8-440db88e8795
OS: Windows 10
Browser: Google Chrome

Hey
I have 90/90 pets and am now working on turning them all into Mounts. Some of my pets still do transfer when completed, but some of them get stuck and stay on the 'Pets' page.
The two pets that should be mounts are the Cotton Candy Blue Flying Pig and the White Bear Cub.
I can't feed them because it tells me they are mounts, but they're stuck in the 'Pets' page.

I can also still equip them as pets, and they appear beside my character.

**Comment by Alys** [comment]
Your account shows that you have the FlyingPig-CottonCandyBlue and BearCub-White mounts. Have you tried reloading the Mounts page? If not, please try that now and tell us if it makes the mounts appear.

**Comment by jrodii** [comment]
Hello
Sorry, I should've clarified. They do appear on the mounts page but they also appear on the pets page. I just tested then and I am able to ride the White Bear Cub while simultaneously having it next to me as a pet.

**Comment by Alys** [comment]
That's permissible. When you convert a pet to a mount, you can rehatch the same pet.

If you didn't create the new pets yourself, it's possible that a bug resulted in them being created or not removed. I haven't seen that reported before though, so I'm assuming for now it's a once-off glitch. I'm closing this, but we can reopen it if it keeps happening.
