### ISSUE TITLE
Very few hatching potions drop

### ISSUE THREAD

**Issue by MrFifths** [HabitRPG/habitica#6083]
Hi,

I've been noticing quite a difference in the amount of hatching potions I get in relation to other people I know using HabitRPG. Ive been using the app for about a month and a half and have received only 5 hatching potions in that time, as a comparison someone who started using the app the same day as me has had 19 hatching potion drops....as far as I can tell my hatching potion drop rate is well below the average 30% as I have received 17 food items and 13 eggs...im just wondering if some users accounts ever get bugs that mess with drop possibilites...

Thanks for any help you can provide.

**Comment by Alys** [comment]
When you get a drop, the chance of getting an egg or potion or food is -- on average -- 30%, 30%, and 40% respectively. However it's chosen randomly so there will always be some variation. Habitica has many thousands of users, and when you have that many people involved with a random action, you will always get some people who have long streaks that seem exceptional. Imagine many thousands of people flipping coins - some will get long streaks of heads. The code that decides which type of drop you get is seeded by your current gold balance, but apart from that there is nothing that is linked to your account. It is not possible for specific user accounts to have bugs that affect the randomness. As time goes on, you will find that you get more potions.
