### ISSUE TITLE
Completed old tasks stays in color in the "To do" list

### ISSUE THREAD

**Issue by Mokasiliquide** [HabitRPG/habitica#6084]
Hello everyone !

I haven't used Habitrpg for a few months and now that I am back on it, every time I complete an old task (and only the old tasks), it stays like before (as if I hadn't completed it).

What can I do ?

Thanks a lot.

**Comment by Alys** [comment]
Go to the To-Do list's "Done" tab and click on the delete button at the bottom to delete all completed To-Dos. Then try deleting the tasks that won't disappear. You might have to delete them a few times before they go away for good. If that doesn't help, tell us your User ID (to find it, go to Help -> Report a Bug and see step 6 of the instructions).

**Comment by Mokasiliquide** [comment]
That seems to work !
Thank you a loooot :+1:
