### ISSUE TITLE
Wrong subscriber benefits comparisons

### ISSUE THREAD

**Issue by ItsMirre** [HabitRPG/habitica#6085]
Hello,

I was looking into the differences between subscribing for 3 consecutive months and 12 and the green bars that usually indicated the Buy Gems with Gold "Cap raised to _" and the "+_ Mystic Hourglass(es)" aren't functioning properly.

The green bars aren't there when "Recurring $5 every 1 months" is selected, which is what they're supposed to be.

But for the "Recurring $15 every 3 months", "Recurring $30 every 6 months", and "Recurring $48 every 12 months" the greens bars say "Cap raised to 26" and "+0 Mystic Hourglass". Even when switching back and forth and re-loading the page, and logging out and back in again.

My User ID: 2e7cc3ad-48b6-4f2a-a132-b1a0cb66ec34
Not sure if relevant, but I'm on the Version 46.0.2490.71 (64-bit) of Google Chrome on a OS X Yosemite, Version 10.10.4.

I hope it gets fixed; and I'll keep refreshing to see if/when it's fixed.

Sorry for any inconvenience!
##

**Comment by Alys** [comment]
Confirmed. See the green highlighted text in the left-hand side of the image below. Those texts should contain numbers.

![screen shot 2015-11-07 at 6 31 38 am](https://cloud.githubusercontent.com/assets/1495809/11008002/6a49f7c4-8519-11e5-862e-68e4516706f7.png)

@ItsMirre When this is fixed, you should receive an email saying that it's closed, so you don't need to keep refreshing to check. :) Thanks for telling us about this! We'd never noticed.

**Comment by ojeytonwilliams** [comment]
Hi.  I've been looking at this recently and I have half a fix (correct numbers now appear, but the badge sometimes hides), and just realised I should probably mention that I'm working on it!

**Comment by Alys** [comment]
@ojeytonwilliams Thank you! :) If you run into any problems, you're welcome to ask questions here, and/or submit a PR with partially completed code for us to look at.

**Comment by ojeytonwilliams** [comment]
You're very welcome!  Part of the reason I'm doing this is to figure out how to do it, so I'll hold off asking questions for the moment.

I don't think the total fix is going to be very large (or take me much longer), but if it's more useful to see partially completed code, I'd be happy to submit what I have.  Up to you!

**Comment by Alys** [comment]
@ojeytonwilliams  I think we would only want to see partially completed code if you had questions, or if the new code was a large, complex piece of work that would benefit from an early review to ensure it was going in the right direction, but that shouldn't be the case here.

**Comment by ojeytonwilliams** [comment]
Sounds good.  Thanks for the help :)

**Comment by ojeytonwilliams** [comment]
@Alys There is something I'd like clarification on.

Currently, if you mouse over "Buy Gems with Gold", it tells you that you initially have a cap of 25 gems and that cap is increased by 5 for every 3 month block you subscribe for.  However, the badge is invisible if you select "Recurring $5 every 1 months" and, to my mind, it should be visible and say "Cap raised to 25".

Then the other options would be 30, 35 and 45 respectively.  Is this correct?

**Comment by Alys** [comment]
@ojeytonwilliams For the one-month option, the gem cap isn't raised immediately - you have to wait three months before the first raise happens. If the badge was there, it would need to say "cap is 25" rather than "cap raised to 25". I think it's best though that the badge only appears for the multi-month options, because that helps to highlight that they have better advantages.
