### ISSUE TITLE
Quest didn't start when all party members accepted

### ISSUE THREAD

**Issue by blueberryblue** [HabitRPG/habitica#6087]
I am user: 03553670-60c2-4b8e-a379-d15f2e2a7c7a responding to a request in my party's chat. cTheDragons asked "Could someone log a bug on official board... the Quest hasn;t started."   Quest is: Trapper Santa     Party is: Insert Party Name Here
Group ID: e3c001ca-f0dd-4510-b313-ba38dbfc7294

**Comment by cTheDragons** [comment]
This issue can be closed as the Quest owner has started the Quest manually.

**Comment by Alys** [comment]
Thanks for letting us know.
