### ISSUE TITLE
I lost 3 gems

### ISSUE THREAD

**Issue by KGBoo** [HabitRPG/habitica#6088]
Two days ago, there was a bug on habitica: all the stuff done in the afternoon disappeared at night and everything reappeared the next morning. During that afternoon, I used gems to change class. I had 3 gems left at the end at the afternoon. The next morning, instead of having 3 gems, I had 0 gem. I still have 0, even after refreshing, re-connecting, etc. So, I lost 3 gems. Could you do something about that? Thanks!

**Comment by Alys** [comment]
We'll need to be able to identify your Habitica account before we can help you. On the Habitica website, please go to Help -> Report a Bug and see step 6 on the page that takes you to. It explains how to find your unique User ID.

**Comment by KGBoo** [comment]
ooops... Sorry about that!

d6208b0e-a7e0-4ddd-ae0b-06a8f5853702

**Comment by Alys** [comment]
@KGBoo I've looked into this you did lose 3 gems. I'm very sorry about that! I've given them back to you.
