### ISSUE TITLE
Android browser redirects to 500 error page

### ISSUE THREAD

**Issue by pinandstutter** [HabitRPG/habitica#609]
Desktop browser works fine, but trying to access https://habitrpg.com or pushing the "Play" button on /splash.html redirects to /500.html

Running CM10 (4.1.2), default browser (no changes to default, but CM10 may have some tweaks built in), Samsung Galaxy S II.

Interestingly, the mobile site loads fine on Dolphin Browser, just not on the default browser. Also tried using a different User Agent, to no avail.

**Comment by rixx** [comment]
This issue is fixed - at least for me on a Galaxy S mini.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
