### ISSUE TITLE
Can't feed pets after ticking an option for the page not to generate notifications

### ISSUE THREAD

**Issue by miracleray** [HabitRPG/habitica#6090]
Hi Habitica,

Yesterday I noticed that the pop-up that double-checks whether you want to give a pet some food had a tick box that allowed me to prevent the page from generating such notifications. I thought this would mean one fewer click needed to feed my pets. Instead today I realized my ability to feed pets had been prevented completely since I could not confirm the action. 

I've tried refreshing the page and poking around the settings to see if I can undo this preference. No luck. Please help! My pets will go hungry! 

I'm using Habitica in Chrome v46.0.2490.71 (64-bit) on a late 2013 Macbook Pro running Yosemite 10.10.5.

Thanks so much,
MiracleRay

**Comment by Alys** [comment]
That checkbox is a feature that your browser implements., not part of Habitica. To reset your browser's setting for it close and reopen your browser. Ensure that all browser windows become closed.

I'm closing this but you can still comment here if you have questions.

**Comment by miracleray** [comment]
Got it - thanks so much! Sorry to bother you with a turn-it-off-turn-it-on-again problem!

**Comment by Alys** [comment]
Heh heh. :) No worries!
