### ISSUE TITLE
Layout Issue with Wolf Mounts

### ISSUE THREAD

**Issue by geekeasy** [HabitRPG/habitica#6094]
All of the other types of mounts look fine, but there's a spacing/layout issue with the wolves where excess horizontal space between the wolves causes them to be spread across two rows.

OSX 10.9.5
Safari 7.1.8  

![wolves](https://cloud.githubusercontent.com/assets/889825/10708608/789dac00-79c3-11e5-8923-9fa29345caa8.jpg)

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/4618 for details and to track the progress of this display issue.
