### ISSUE TITLE
I somehow kicked myself out of the party I made, and Habitica stopped responding to anything & says "application error, please reload"

### ISSUE THREAD

**Issue by duran0820** [HabitRPG/habitica#6095]
My User ID is: e5004b63-cbf8-43b3-90b1-c477c655b117

I had a party named "YEAH". To complete a quest, I made a secondary account, invited that account to my party, and then somehow ended up inviting myself to the party. That invitation didn't go away no matter how many times I accepted it. I got annoyed and started clicking around, and ended up kicking myself out of my party. 

After that, Habitica stopped functioning. Even if I complete my Dailies, it won't give me any rewards or say anything. The same thing with To-Dos. I can't add anything to my To-Dos list, either. When I click around, Habitica occasionally tells me that there is an application error, and that I should reload the page. Reloading doesn't fix anything, though.

Could I fix my account so that it would function again?
##

**Comment by Alys** [comment]
There almost certainly won't be anything wrong with your account that's causing this, and it's probably coincidental that this happened after you left your party. 

If you have access to another browser, please try logging in to Habitica there. You should find that your account then works correctly. Tell us if it does not!

If you don't have access to another browser, try using incognito mode in your normal browser, and tell us if that doesn't fix the problem.

To make your preferred browser work in normal mode (without incognito), you probably need to clear local storage. Note that that's different than clearing your cache or cookies and you might need to google for how to do it for your preferred browser. However, I recommend trying one or both of the above suggestions first, just to confirm that it isn't your account at fault.

**Comment by pipisafoat** [comment]
I followed these directions and got my account working on my preferred browser again, but it took advantage of that to get rid of most of my spooky pets, return SOME of my gems to me (but not all of them!), and delete almost all of my gold. I know how to reset my gold count, but is there any way for me to get my spooky pets back, or at least the rest of my gems if I can't have all the pets? (I had every spooky pet; now I have the wolf but none of the others, no spooky potions, and of course it's past time to be able to buy the potions anyway. For some reason it only gave me half my gems back, too.)

**Comment by Alys** [comment]
@pipisafoat tell us your User ID (see step 6 in Help -> Report a Bug) and how many gems are missing.

**Comment by pipisafoat** [comment]
Ah, sorry! User ID: b2293f3a-bffb-4e01-8db3-7b6926677f36
I am missing 8 gems. (No way to get my spooky pets back? I really loved my spooky tiger cub especially! It's okay if not. I appreciate you helping with the issue, whatever the resolution ends up.)

**Comment by Alys** [comment]
@pipisafoat Yes we can give you the pets back, I just wanted to do all the changes at the same time rather than the pets first and then the gems after you told me how many were missing. Also, I needed your user id first. :) Wait about ten minutes then reload the site. Comment here again if it's not all correct then.

@duran0820 I'm closing this issue now, but if you're still having trouble, please comment here.
