### ISSUE TITLE
Party member and invited still

### ISSUE THREAD

**Issue by badgerwizard** [HabitRPG/habitica#6097]
In my party my friend is both a member and invited. When I remove them from the invited list it comes back up as invited when I refresh. They keep getting re-invited and If they accept the additional invitation to join my party it just comes up again. I've tried to kick them out completely but they still get invited even if I don't add them myself. Help?
User ID: 92be8df3-b3e8-4724-b73e-0296420a21a3
Group ID: d86c0e34-d154-4fa1-82b4-41139827f35a
Browser: Mozilla Firefox
OS: Windows 7

**Comment by Alys** [comment]
I've deleted the invitation from your party and from their user account.

These invitations do sometimes come back though, possibly because they're being cached your browser or your party mate's browser. Please comment here if it reappears.

**Comment by badgerwizard** [comment]
Hi, the invitation has come back, should my party mate and I clear our caches?

**Comment by Alys** [comment]
I've cleared the invitations again in the database, but yes, it might be best if you do clear your caches, and also clear local storage for habitica.com (google for how to do that for your types of browsers because it can be different than clearing your cache).
