### ISSUE TITLE
Upgrade to Mocha >= 1.18.2

### ISSUE THREAD

**Issue by czan** [HabitRPG/habitica#6098]
Would we be open to moving to a newer version of Mocha than what is currently being used? We're at Mocha 1.12.1 at the moment, but upgrading to a newer version could bring some useful new features.

In particular, in 1.18 they added support for promise based tests, instead of the old `done` API. This would be really useful for the new API tests. It would mean instead of writing this:

```
it('fails for non-existent tags', (done) => {
  api.get('/user/tags/not-an-id')
    .then((fetched) => {
      done(new Error('Request should have failed'));
    })
    .catch((err) => {
      expect(err.code).to.eql(404);
      done();
    })
    .catch(done);
});
```

We could write this:

```
it('fails for non-existent tags', () => {
  return api.get('/user/tags/not-an-id')
    .then((fetched) => {
      throw new Error('Request should have failed');
    }, (err) => {
      expect(err.code).to.eql(404);
    });
});
```

This might not seem like that much of an improvement, but removing all the littered `done`s from the code would make things a bit clearer, as well as removing a potential mistake people could make when writing tests.

**Comment by crookedneighbor** [comment]
Yes. Very open to that.

**Comment by crookedneighbor** [comment]
I've updated the dependencies.

**Comment by crookedneighbor** [comment]
We're fully upgraded and I converted the tests to no longer need the done callbacks.
