### ISSUE TITLE
Awards or Badges

### ISSUE THREAD

**Issue by hookang** [HabitRPG/habitica#61]
_Edited by wc8: Vote for this feature here: [Awards and Badges](https://trello.com/c/4uWICvDf)_

Makes it fun even though their are digital trophies.

Adds to gamification.

Maybe 4 Tiers of Awards
Bronze - You completed your first habit, daily task, todo 
Silver -  You've mastered 1 habit , You've hit level 1
Gold -  You've mastered 5 habits
Platinum - You are a habit making master, you've hit 
Etc...

Each award / badge is kept somewhere so the public can see via profile - if you allow them. 
Each award / badge is gives you a small amount of currency

**Comment by horusofoz** [comment]
+1

I would also display latest or highest level award in the header next to the sprite, if not a small section where they were all overlayed with the latest on top. A separate "profile" with them all listed, date awarded, action awarded for, etc would be great. Maybe the same page that displays the activity log or a tab thereon.

Additionally maybe some sort of humorous title which would go from something like "Apprentice Procrastinator" at low levels to "Knight of the Order of The Pomodoro" or "Arch Mage of GTD".

**Comment by lefnire** [comment]
Sounds like a good'n!

**Comment by racuna** [comment]
Amazing!!! With an activity log page we can follow friends too.

**Comment by timothyCoxon** [comment]
Don't forget social sharing with these badges. e.g. Share this on Facebook, tweet this.
Essential for the purpose of promoting the project itself.

**Comment by racuna** [comment]
@timothyCoxon yeah! I been thinking about that, like a button "share in FB/Twitter/G+" when I level up so depending of the possibilities of that networks share images, text and links like: 
&lt;img src="http://habitrpg.com/img/avatarLvl3.png&gt; &lt;a href="http://habitrpg.com/racuna"&gt; I just level up in habitRPG&lt;/a&gt;
Other idea is make a widget with the avatar or/and the progress bar linking with the public profile for sharing in a personal website or blog.

**Comment by timothyCoxon** [comment]
@racuna maybe post that as another feature request? Good idea :+1:

**Comment by horusofoz** [comment]
@timothyCoxon +1 to Facebook/Twitter/Google+ share. Both enhances achievements and helps spread the word of the game. Create a new ticket for that feature request so we can chime in to lend our support behind the idea.

**Comment by racuna** [comment]
@horusofoz @timothyCoxon  I prefer if one of you do it, maybe you can express better the idea 'cause my native language is spanish and I use a very small vocabulary. (I always check on Gtranslate but sometimes i think is not enought)

**Comment by timothyCoxon** [comment]
Added a feature request for that. I think @lefnire needs to confirm new feature requests as I've posted about five so far and none have so far shown up.

**Comment by lefnire** [comment]
What, your new tickets aren't showing up? Github doesn't throttle or
anything, make sure you're sorted by last submitted and there are no
filters. Ps, I LOVE all these feature requests coming in, this is getting
me pretty pumped

**Comment by switz** [comment]
Maybe it's because you keep closing them immediately? https://github.com/lefnire/habitrpg/issues/127

**Comment by timothyCoxon** [comment]
Nope, 127 was closed for some reason but there are also #124, #125, #126, #127, and #129
I am fairly new to github so unsure of some of the intricacies... 
Okay so I guess I need to label the issues as features but I can't seem to do that...

**Comment by wc8** [comment]
See also https://github.com/lefnire/habitrpg/issues/59
I'd want to privacy settings for tasks if sharing was incorporated.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
@horusofoz I added [Profile Page](https://trello.com/c/9LNJafFM)
