### ISSUE TITLE
Still Haven't Recieved 20 Tokens

### ISSUE THREAD

**Issue by Sandor13** [HabitRPG/habitica#610]
I'm a backer and i've already used Habitrpg for a cuple of weeks. I've responded on survey, but received no additional tokens. 

Alex Anikin
777c2c3c-8bc8-4877-a3cc-87c0069158c8

**Comment by lefnire** [comment]
Rewards haven't rolled out yet, we need to finish the pet system first, and wrap up t-shirts so we can finish sending the surveys. See [this update](http://www.kickstarter.com/projects/lefnire/habitrpg-mobile/posts/412752). Hmm... I actually get this question quite a lot even though I sent out that KS update.. any recommendations?

**Comment by Sandor13** [comment]
Sorry, i didn't read that update carefully - it's too hard to extract this bit of information from all the text. That's the problem as i see it.
I recommend to make another update for tokens only, were you can explain the situation with all the questions about tokens and the date of release. And/or make a notification in the app, if you can make it for backers only.

**Comment by lefnire** [comment]
Got it. Yeah, second read - you're right about the buried text. Adding to my todos
