### ISSUE TITLE
Daylight saving issues.

### ISSUE THREAD

**Issue by Tenerezza** [HabitRPG/habitica#6103]
Looks like there is a issue with daylight saving as today it rolled over 'twice' for me, I first logged in a few minutes past midnight just to see the quest progress and now I logged in a bit later today just to notice that I have taken damage and basically failed to do any progress for a whole day.

Losing both my Progress & Streaks is quite annoying in this regard, hopefully it can be resolved so it will affect less peoples in the future.

**Comment by NessaP** [comment]
Though I had done all my tasks yesterday, I have taken damages today. Plus two of my tasks appeared to be already done when I logg on this morning...

**Comment by Alys** [comment]
@Tenerezza We're working on a workaround for the daylight saving problem that will be in place by 1 November.

@NessaP You were probably affected by [this bug](https://github.com/HabitRPG/habitrpg/issues/4313). There's an Advice section near the top that will help you recover from the unfair damage.
