### ISSUE TITLE
Nothing displays

### ISSUE THREAD

**Issue by Thor333** [HabitRPG/habitica#6108]
Hi guys,
For me it's a huge issue, nothing happens on any browser i try.

With https://habitica.com/ 
it's an «Application Error An error occurred in the application and your page could not be served. Please try again in a few moments.If you are the application owner, check your logs for details.»

with https://habitica.com/static/front with a incognito mode
it's a blank page, but with lots of source code behind.
and with another browser it's the same.

Any ideas? Just wait?

**Comment by Alys** [comment]
Yes, I'm sorry, our database has crashed so the site is unavailable. We've asked the company that hosts our database to investigate.

**Comment by Alys** [comment]
I've opened an issue describing the problem: https://github.com/HabitRPG/habitrpg/issues/6109

We'll post all updates to that.

Once again, I'm really sorry! We and our database company are doing everything we can to get the database working again.
