### ISSUE TITLE
Habitica unavailable 26 October - "Application Error" (database outage)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6109]
**EDIT: The problem described below has been fixed. Habitica's website and mobile apps should be running normally but we are continuing to monitor them.**

---

The Habitica website and mobile apps are currently unavailable due to a database outage.

We have asked the company that hosts our database to see if there's anything they can do to get it running again.

The website will be displaying an "Application Error" message.

The mobile apps might seem to work **but none of your changes will be saved permanently**.

We're very sorry about this! We'll report here as soon as we have news about the database.

Please note that your data won't be lost. The very worst case scenario is that we'd have to revert to a database backup from about 12 hours ago, but even that will probably be unnecessary.

**Comment by Alys** [comment]
We've heard back from our database company. The database has been restarted but its indexes need to be rebuilt. That's happening now but it will take a while. After that's finished, other actions might be needed. 

The fix is progressing but we don't yet know when the site will be back up.

**Comment by Alys** [comment]
It's looking like there'll be no data loss, or at worst we'll have lost the most recent minute or two of data.

**Comment by Mr-Kumar-Abhishek** [comment]
Good news. I was using it when it happened.

**Comment by Alys** [comment]
The process to rebuild the database's indexes is about halfway through. We're estimating another half hour for that, and then some additional time after that to apply a patch that should stop this problem happening again.

**Comment by pierreozoux** [comment]
What is your database provider and the size of the database? (just for the record?)

Thanks for your work :)

**Comment by Alys** [comment]
Our database provider (mongolab) is estimating that there's still another 35 minutes before the indexes are rebuilt. There'll be a bit more downtime after that for patching.

**Comment by Alys** [comment]
The database index has finishing being rebuilt! We're now applying a patch to prevent this happening again.

**Comment by paglias** [comment]
and then came back again

2015-10-26 12:50 GMT+01:00 Alys <notifications@github.com>:

> The database index has finishing being rebuilt! We're now applying a patch
> to prevent this happening again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HabitRPG/habitrpg/issues/6109#issuecomment-151109827>.
>



-- 
Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
The site is up and running again. Let us know if you experience any other issue

**Comment by Alys** [comment]
Many thanks to the people at [mongolab](https://mongolab.com/) who helped us through this and we SO responsive to our emails!
