### ISSUE TITLE
Clasify, Organize Habits

### ISSUE THREAD

**Issue by iMariodroid** [HabitRPG/habitica#611]
Sometimes the list of habits can be very long, I got lost between them... can you create a way to organize them, like making folder or categories so we can clasify our habits and find them more quickly

**Comment by lefnire** [comment]
Very close to having this done, see
https://trello.com/card/tags-categories/50e5d3684fe3a7266b0036d6/43

**Comment by ericwilmoth** [comment]
that'll be very handy.
