### ISSUE TITLE
Party activity didn't sync (dailies did)

### ISSUE THREAD

**Issue by ladynthread** [HabitRPG/habitica#6110]
My party activity didn't sync at cron but my dailies did.  I tried to sync at cron from my Nexus7 tablet just shortly after my cron time (EST) using android chrome browser (not android app) and at that time I received the Application Error message so I waited until I could use my laptop.  However, now that I've tried syncing on my laptop (Windows 7 and tried both Chrome and Firefox) the last days party activity still hasn't synced.

Group ID: c87be826-1925-4ce2-a87d-c8a9f620687d
User id: 37eece51-4f9b-4ec2-89ce-a1d5d55c2b88

**Comment by Alys** [comment]
Can you please tell us what party activity you're referring to?

**Comment by ladynthread** [comment]
The one that applies the daily damage to the quest.

**Comment by Alys** [comment]
Sorry about that! It's probably a side-effect of this bug: https://github.com/HabitRPG/habitrpg/issues/6109

The bug has been fixed now so your quest progress should be reported normally tomorrow.

**Comment by ladynthread** [comment]
No problem, I was afraid of that but wanted to report in case it wasn't.  I'll check back tomorrow if it hasn't resolved.
