### ISSUE TITLE
drop of 'undefined'

### ISSUE THREAD

**Issue by Ainoah** [HabitRPG/habitica#6111]
Hi,

I had a bug in my account, "Error cannot set property 'drop' of undefined". 

I don't know what it means. I've reached the level 60 when casting a spell and that bug came. I've reloaded my page to see if it continued to appear and it did.

I'm uploading the image of this here.

Thanks a lot for your hard work ! (and sorry for my english)

![erreur habitica](https://cloud.githubusercontent.com/assets/15324368/10729192/10112f14-7be8-11e5-80d6-b54183c2e14d.png)

Edit : The game make me go one level under (59) and restore the mana I've used to pass the level.

**Comment by crookedneighbor** [comment]
This is a duplicate of https://github.com/HabitRPG/habitrpg/issues/4986

You can follow the advice at the top of the issue as a work-around.
