### ISSUE TITLE
Unable to tick off dailies (website down?) resulted in loss of hp..death...loss of lots of gold

### ISSUE THREAD

**Issue by MrFifths** [HabitRPG/habitica#6116]
my fiance couldnt tick off her dailies yesterday because both her app and the website was being very buggy (was the same on my phone and pc)...she ended up losing a level and a bunch of items/gold as a result. Is there anything we can do about this?

**Comment by MaidM** [comment]
Same problem here!  I run Habitica across 4 devices - 2 iOS, 2 laptops.  Everything was showing correctly completed on the laptop, but not on the iPad.  None of my day's progress was showing there even after I logged off, removed the app, went back out to the laptop, completed another daily, went back to the tablet, reinstalled the app and relogged on.  Now my entire party is dead as a result and I've lost about 200 gold and a scimitar.  I've also noticed that all of the costume & equipment changes I made yesterday have been removed (i.e. not replaced with the items I had the day before, but removed altogether and put back into my inventory.)

Also: worryingly, all of my progress from yesterday is still showing as done on the laptop again this morning, even though I haven't ticked off any dailies today.  I've tried clicking sync and refreshing the browser, closing the window, launching a new tab, etc.  Nada.

Please help - this is a big issue.

**Comment by Alys** [comment]
@MrFifths We're sorry about the outage! You can read about it in [this issue](https://github.com/HabitRPG/habitrpg/issues/6109) if you would like to know the details. Your fiance can use Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to restore her level and gold, and enough extra gold to buy back the equipment lost. Settings is the gear-shaped icon on the top right of the website. If she has any questions, please ask her to comment here.

@MaidM You were hit by [this bug](https://github.com/HabitRPG/habitrpg/issues/4313).  I'm sorry about that! There's an "Advice" section near the top that will help you recover from it.
