### ISSUE TITLE
Reward costs changed

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#612]
I just leveled up to l. 8 (I seem to level up much faster than with the old algorithm) and the custom rewards I have that were priced at more than 10 gold all changed their price to 21.27 gold instead. The 10 gold ones are unchanged, as are the non-custom ones.

I now feel very tempted to have a very cheap reward  ; )

**Comment by Laflamme** [comment]
Same problem, plus I now have 539 / 240 XP.

**Comment by lefnire** [comment]
Ok, rolling back the algorithms update. Will post back when we have fixes.

**Comment by lefnire** [comment]
Ok, the new system has been deployed - check your exp, it should be set to a proper percentage

**Comment by wildcate** [comment]
Yes, looks similar to how it did before. Thanks!

**Comment by lefnire** [comment]
sweet. Check out http://habitrpg.tumblr.com/post/44800417533/new-algorithms-the-lowdown for the details
