### ISSUE TITLE
Cursor stuck as 'scrolling down' cursor

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6124]
Sometimes when I load the main page, my cursor is stuck in the 'down direction' scrolling. (Something like this: http://cdn3.howtogeek.com/wp-content/uploads/2008/03/270x238ximage136.png.pagespeed.ic.otxzs_VmdR.png but only with down, not with up).

This usually happens when there are notifications or quest redemption. It does not go away with refreshing, but will if I close the window, then open a new one. I am in chrome with windows 8. I have never had this issue with any other website, but it comes up occasionally here.

!["screenshot"](http://cdn3.howtogeek.com/wp-content/uploads/2008/03/270x238ximage136.png.pagespeed.ic.otxzs_VmdR.png)
##

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Closing. We can reopen if this still happens on a recent Windows version.
