### ISSUE TITLE
Application Error. Site not loading. Server Issue

### ISSUE THREAD

**Issue by nelle013** [HabitRPG/habitica#6125]
I tried to reload my page when my tasks weren't syncing, but it says Application Error and won't even load the page on Safari, Chrome, and the app says Application Error. Please fix... just started a quest!

**Comment by crookedneighbor** [comment]
We've restarted the app. Are you still experiencing issues?

**Comment by nelle013** [comment]
Nope all working! Thanks!!

Janelle Rowe
School Psychology Student
University of Alabama
(585) 727-8433
