### ISSUE TITLE
Lost Gems after hitting refresh

### ISSUE THREAD

**Issue by Tsuruga** [HabitRPG/habitica#6128]
Hi,

I have lost 15 gems after I hit refresh on the website.

So today I have bought 45 gems by 900 golds from the market. Then I bought the November 2014 Sets of Theme for 15 gems, and I had 30 gems left, 

Then, after I hit refresh, I saw I only have 15 gem left. I have back the 900 golds I used to buy 45 gems, but there is no more gem available in the market for me to buy from.

My User ID is: 3b304728-4d68-4246-83c0-c79bfd3d06ff

I use Chrome browser ver 46.0.2490.80 on Mac OS.

Thanks.

**Comment by Alys** [comment]
I've given you back the 15 gems. Comment here if there's any further problems related to them.
