### ISSUE TITLE
Short lived error message in Chrome, about being unable...blah blah... drop...  Could not copy the rest

### ISSUE THREAD

**Issue by lamachine** [HabitRPG/habitica#6129]
e699f7e2-a640-4315-86e2-dde7dd02bfb1
Gave me a new quest window that I could not click through (later or invite).  Reloading the page repeated the error.  

https://habitica.com/api/v2/user/class/cast/fireball?targetType=task&targetId=a502b897-6440-4ab0-999a-a83f82990915 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-d19051ed.js:36 
Object
config: Object
data: Object
headers: (c)
status: 500
statusText: "Internal Server Error"
**proto**: Object

**Comment by Alys** [comment]
Please see this issue: https://github.com/HabitRPG/habitrpg/issues/4986

If that's not it and it's still happening, comment here and we'll reopen this but I'm afraid in that case we will need the full error message. If you have a screenshot facility on your computer, you might be able to catch an image of it in time.

**Comment by lamachine** [comment]
Exactly the problem I was having, I will clear my cache, but it was at a level-up, using a skill, and with a scroll drop.  Thanks.
