### ISSUE TITLE
Cron fail

### ISSUE THREAD

**Issue by hartalex** [HabitRPG/habitica#6131]
My Cron failed last night.  Just an FYI if you are keeping track of these.

**Comment by Alys** [comment]
Can you give us some details about how it failed? For example, did it not run at all? Did it run twice? Did it run at the wrong time? Did it run but some of the things it should have done did not happen? Did something else go wrong?

**Comment by hartalex** [comment]
It's like it half ran,  I completed all of my dailies, however only half of them reset.  I'm also doing a quest, so we took damage for the dailies that didn't reset. The dailies that did reset did end up damaging the boss.

**Comment by hartalex** [comment]
The dailies that didn't reset were checked and I had to uncheck them manually.

**Comment by Alys** [comment]
Thanks @Vorgone. That wasn't actually cron failing. You were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313
In brief, when you ticked off your Dailies yesterday, your browser had not sent those actions to the server for permanent storage, and then after your cron ran, it did send the actions, causing the Dailies to be incomplete when cron ran and then completed afterwards.
There's an Advice section near the top of that issue which will tell you how to untick your Dailies without losing gold, etc, and how to recover from the unfair damage.
