### ISSUE TITLE
Mystic Hourglass Problem

### ISSUE THREAD

**Issue by JustTeaForMe** [HabitRPG/habitica#6132]
I have been a member for almost two years now. And a while back I had purchased the 12 month subscription. I cannot recall ever receiving an hourglass for consecutive months except from switching my subscription from monthly to yearly. So I have kept an eye out for hourglasses. 

Maybe I am not understanding the process of how it works, but on the Time Traveler's Page it says, "You'll need a Mystic Hourglass to summon the mysterious Time Travelers! Subscribers earn one Mystic Hourglass for every three months of consecutive subscribing. Come back when you have a Mystic Hourglass, and the Time Travelers will fetch you a rare pet, mount, or Subscriber Item Set from the past... or maybe even the future."

I have a recurring bill of $48 every 12 Months
My account says that I have 19 consecutive months
And that I have 0 Mystic Hourglasses

What do I do now?
Feel free to contact me at my email, PaintMeALine@gmail.com

Thank you, Emily.
##

**Comment by Alys** [comment]
Can you please tell us your user ID so that we can identify your Habitica account? To find your User ID, go to Help -> Report a Bug and see step 6 of the instructions.

**Comment by JustTeaForMe** [comment]
Sorry, it is 346d6f99-5fa7-4f05-bed8-39949732e5e4

**Comment by Alys** [comment]
Sorry about that! I've given you the four Hourglasses that you should have received when your twelve-month subscription was renewed.
