### ISSUE TITLE
Can't leave the Inn

### ISSUE THREAD

**Issue by BanktownUSA** [HabitRPG/habitica#6134]
I've tried for weeks to log out of the tavern and each time the tavern screen shows that i log out, but the little zZZ don't disappear and when i return to main page it still has the little yellow box telling me i'm resting in the Inn. I've logged out, refreshed, synced etc nothing seems to work.

7a64f655-6147-40a1-8ca5-6634279e0516

Using Chrome and Mac OS X version 10.7.5

**Comment by Alys** [comment]
I've taken you out of the Inn.

However it's not impossible that something in your browser is caching the Inn and it might put you back in. Comment here if that happens. Also, try using a different browser, or incognito mode in the same browser, or clear local storage in your browser (that's different than cache and cookies).
