### ISSUE TITLE
Bought gems with PayPal but they never showed up

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#6135]
On Monday Oct 26 I bought 20 gems through PayPal. The transaction went through in PayPal, but when I would normally have been redirected back to Habitica and my gem number would have been updated, I got an "Application Error" message instead. I received a confirmation email from PayPal, but not the usual one from Habitica. A few minutes afterward, I noticed the Habitica site was having trouble loading and giving a lot of error messages, so I'm guessing I bought the gems at a bad moment. I emailed admin@habitica.com, but have not heard back yet; I'm posting here in case this issue is better dealt with through github. I had 13 gems at the time, now have 1, but the 20 were never added. My userID is 0b670754-57f5-4704-854f-9a9c92107b9b.

**Comment by Alys** [comment]
I'm very sorry hattieshoe! The email had been filed away in our email system and so I only found it when went searching there for your user ID. I'll reply there soon.

**Comment by hattieshoe** [comment]
Thank you very much! :-)
