### ISSUE TITLE
Lost all (50) health overnight and now my dailies are not resetting

### ISSUE THREAD

**Issue by cosmiclaurel** [HabitRPG/habitica#6137]
I don't think I should have lost all 50 health in one night, but regardless, my dailies are not resetting. Many of them are grey with the black checkmark.

**Comment by Alys** [comment]
I'm sorry about this! You were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313 Please see the Advice section near the top for how to recover from it.
