### ISSUE TITLE
closed dialog boxes, now can't feed pets

### ISSUE THREAD

**Issue by bunnyplanet** [HabitRPG/habitica#6139]
I was feeding a pet today when I noticed that in the box where it says something like "do you want to feed the cotton candy to your pet" there was a checkbox saying something like "close additional dialog boxes."  I thought this meant it would stop asking me the question in future, so I clicked it. It seemed to work for a time or two, but then trying to feed the pet, or any other pet just stopped working completely. When I try, the blue sync line appears, but nothing happens to the food or the pet.

I've tried reloading the page without any change. Is there a way to uncheck the box?

**Comment by SabreCat** [comment]
Close your browser and reopen it. You'll then start seeing the prompts again!
