### ISSUE TITLE
Some clicks not registiring

### ISSUE THREAD

**Issue by Skater6780** [HabitRPG/habitica#614]
Once again clicks are registering, when I click a daily or habit nothing h appends, but if I can customize my character and stuff like that - Thanks for your time  Skater6780

**Comment by lefnire** [comment]
even after a refresh?

Edit - so clicks are registering, but you're saying _except_ for dailies and habits?

**Comment by cleave29** [comment]
I have 35.99 Gold and it won't let me but a Buckler for 35.  I think I remember reading about this bug before, but I don't know if it's related to the old bug or this bug.

**Comment by wc8** [comment]
@cleave29 I think you might be thinking of #514

**Comment by cleave29** [comment]
@wc8 Yes that's it.  Thank you!

**Comment by Skater6780** [comment]
Yea actions not registering

**Comment by Skater6780** [comment]
I also dont get Xp when I complete a task, but it does disappear

**Comment by lefnire** [comment]
sorry for the silence, i'll be debugging this again as soon as i can

**Comment by electblake** [comment]
@lefnire Did you discover/research anything you can report? I think I experienced this myself (not sure if it's same bug) but trying to recreate locally now

_From my understanding of this bug description.._
It's when a user clicks the plus (or minus) icon for an action, and although the points do tally, they don't update exp/health live (but do after refresh)

**Comment by lefnire** [comment]
I tried logging in as @Skater6780 on local just now to test his account. The actions register, @Skater6780 are they working for you ok on production right now? @electblake can you [send me](mailto:tylerrenelle@gmail.com) your user id that I can test your account? any javascript errors happening in chrome console / firebug?

**Comment by yangit** [comment]
Issue #769 could be related.

**Comment by lefnire** [comment]
#769 definitely related (at least, I think 769's resolution will solve this). Let's follow up there
