### ISSUE TITLE
Error when selecting an equipment

### ISSUE THREAD

**Issue by CleberDSantos** [HabitRPG/habitica#6142]
when selecting an equipment displays an error message, follow the pintscreen
![error-habitica](https://cloud.githubusercontent.com/assets/1626423/10844736/39774844-7ee9-11e5-823f-8fce05dd8980.png)
![error-habitica-console](https://cloud.githubusercontent.com/assets/1626423/10844737/3ba9c22c-7ee9-11e5-8e9f-edbf1ae461b7.png)

**Comment by CleberDSantos** [comment]
my user id: 0240b278-6591-4b2d-8339-6c6e0ebb4998

**Comment by Alys** [comment]
There's application errors across the site intermittently. We're rolling back some recent changes to see if that improves matters. Please try again in a few minutes, and if it's still giving you errors, try again in an hour or two. We're continuing to monitor the site so we'll definitely get this fixed soon.
