### ISSUE TITLE
Shiny seed and Spooky sparkles do not affect avatar

### ISSUE THREAD

**Issue by Midgey** [HabitRPG/habitica#6154]
A member of my party used "spooky sparkles" on everyone in the party, however my avatar never changed into a ghost (everyone else's did). Previously someone used "shiny seed" on me and my avatar did not turn into a flower. Both of these times a message was generated in the party chat saying the item had been used on me.

User ID: f1e7288a-67c9-47b2-8610-7fc0aa45244a
Browser: chrome
OS: Windows 10
Group ID: 20ebfefe-05c9-44bf-9bb3-8825225a7592

**Comment by Alys** [comment]
Those items take effect until your next cron and then the effect disappears.

Did your party mates cast them on you after you'd stopped using Habitica for the day? If so, they would have worn off as soon as you started using Habitica the next day (when your cron ran).

Let us know if that's not the case or if you need any clarifications!
