### ISSUE TITLE
Reward costs no longer have right side padding on Chrome

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6158]
Sometime within the last few days, the items in my Rewards column lost part of their padding, leading to a chopped-off, uneven look:

![image](https://cloud.githubusercontent.com/assets/4501321/10870014/bc0cca70-8085-11e5-9422-f924ec32af62.png)

I'm using Google Chrome on Windows 10. @Alys has reported that this issue ~~doesn't happen for her~~ also occurs in SeaMonkey, a Firefox-based browser.

**Comment by Alys** [comment]
It happens to me on Chrome 46.0.2490.80 (64-bit) on Mac OS 10.6.8

**Comment by Alys** [comment]
It's happening on SeaMonkey too now. Perhaps it's a recent change and I hadn't reloaded since it started? Sorry, I thought I did reload when I checked but I must have forgotten.

So, yeah, not a browser-specific problem.

**Comment by SabreCat** [comment]
Thanks for checking back! Updated the main issue text.

**Comment by crookedneighbor** [comment]
I think I've tracked down the offending commit.

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/commit/78cfbd2c6ac7e1a3d319f982ac0080f45ca19cec
