### ISSUE TITLE
inactive user with perfect day stays buffed [sync / cron issue?]

### ISSUE THREAD

**Issue by dirad** [HabitRPG/habitica#6162]
hi,
Fairly new to Habitica, i have a party with some ppl i found online. 
One of the users have not been active for a few days, and i see they have not logged in.
Despite this fact, the perfect day buff they gained a week ago still appears in the avatar & in the stats.

Maybe no sync ?

I dont know if i should post their userID for privacy reasons. 

Windows8.1 / FF 41.0.2

**Comment by SabreCat** [comment]
Players' accounts don't update unless they log in. What you're seeing is to be expected based on what you've described.
