### ISSUE TITLE
Bought a set using gems, only have access to one of the set items.

### ISSUE THREAD

**Issue by pierrotte** [HabitRPG/habitica#6164]
Hello, I purchased the hairstyle set 1, and had access to all of the options at first, but when I came back a few days later I realized I can now only use the hairstyle I'd left on my avatar, which isn't even one I particularly like. All the other ones in the set have greyed out again. Help? 

I'm using google chrome on a computer running windows 7. 
My user ID is: 3fe99ac8-e1e4-4f0a-baf2-4b5ddbeb2c47

**Comment by Alys** [comment]
Sorry about that pierrotte! I've given you the items you bought. Please reload if they don't appear straight away.

I'm closing this now but if they don't appear after a reload, comment here and we'll keep helping you.

**Comment by pierrotte** [comment]
I just wanted to say thanks, it's all sorted out! :smile:
