### ISSUE TITLE
Didn't receive quest rewards

### ISSUE THREAD

**Issue by Deztiny7747** [HabitRPG/habitica#6165]
Hello! We defeated Burnout and the Exhaust Spirits today. Everyone received their rewards except me. I received the phoenix pet and mount, but not the candies. I've also noticed that sometimes when i receive candy through the mobile app, it does not appear in my inventory. Do you know how to fix it?

My ID is 709674a5-8bd5-4e90-ae97-bff149d562b8

**Comment by Alys** [comment]
Sorry about that! I've given you the food.

Regarding this:
"sometimes when i receive candy through the mobile app, it does not appear in my inventory"
If the mobile app you are using is the iOS "Habitica" app with the purple gryphon logo, please report that through Menu > About > Report a Bug

If it's the iOS "HabitRPG" app with the brown chest logo, we recommend no longer using it and using the Habitica one instead. If it's the Android "HabitRPG" app, a new "Habitica" app will be released to replace it in the not too distant future, and so we regretfully aren't able to do bug fixes for it, except for critical bugs.
