### ISSUE TITLE
Move Overview for New Users to Website

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6168]
Right now, the Overview for New Users is located on the wiki, which we've discovered is confusing to new users, who sometimes don't even realize that it is there on the linked page. For this reason, I am proposing a new page on the website, similar to the FAQ, that contains the Overview for New Users. (We will also want to add a line to the top of the website's FAQ that says something along the lines of "Brand new user? Check out the Overview for New Users!" with a link.)

Here is my edited version of the text from the wiki:

---

Overview for New Users

Need some tips on how to begin? Here's a straightforward guide!

Step 1: Enter Tasks
Habitica is nothing without real-world goals, so enter a few tasks. You can add more later as you think of them! 

1a. Set up To-Dos
Enter tasks you do once or rarely in the To-Dos column, one at a time. You can click the pencil to edit them and add checklists, due dates, and more!
1b. Set up Dailies
Enter activities you need to do daily or on a particular day of the week in the Dailies column. Click the item's pencil icon to 'edit' the day(s) of the week it will be due. You can also make it due on a repeating basis, for example, every 3 days.
1c. Set up Habits
Enter habits you want to establish in the Habits column. You can edit the Habit to change it to just a good habit (+) or a bad habit (-).
1d. Set up Rewards
In addition to the in-game Rewards offered, add activities or treats which you want to use as a motivation to the Rewards column. It's important to give yourself a break or allow some indulgence in moderation!

If you need inspiration for which tasks to add, you can look at the wiki's pages on Sample Habits(http://habitica.wikia.com/wiki/Sample_Habits), Sample Dailies(http://habitica.wikia.com/wiki/Sample_Dailies), Sample To-Dos(http://habitica.wikia.com/wiki/Sample_To-Dos), and Sample Rewards(http://habitica.wikia.com/wiki/Sample_Custom_Rewards).

Step 2: Gain Points by Doing Things in Real Life
Now, start tackling your goals from the list! As you complete activities, you will gain experience points (XP), which help you level-up, and gain gold points (GP), which allow you to purchase Rewards. If you fall into bad habits, or miss your Dailies you will lose health points (HP). In that way, the Habitica experience and health bars serve as a fun indicator of your progress toward your goals. You'll start seeing your real life improve as your character advances in the game.

Step 3: Customize and Explore Habitica
Once you're familiar with the basics, you can get even more out of Habitica with these nifty features:
- Organize your tasks with tags (edit a task to add them).
- Customize your avatar under User > Avatar.
- Buy your equipment under Rewards and change it under Inventory > Equipment.
- Connect with other users via the Tavern.
- Starting at Level 3, hatch pets by collecting eggs and hatching potions. Feed them to create mounts.
- At level 10: Choose a particular class and then use class-specific skills (levels 11 to 14).
- Form a party with your friends under Social > Party to stay accountable and earn a Quest scroll.
- Defeat monsters and collect objects on quests (you will be given a quest at level 15).

Have questions? Check out the FAQ (https://habitica.com/static/faq/)! If your question isn't mentioned there, you can ask for further help in the Newbies Guild.(https://habitica.com/#/options/groups/guilds/5481ccf3-5d2d-48a9-a871-70a7380cee5a)

Good luck with your tasks!

**Comment by Alys** [comment]
I've advertised this in the Aspiring Coders guild

**Comment by AminArria** [comment]
I'll work on this.
This would be another static page like the faq right?

**Comment by SabreCat** [comment]
@AminArria: Exactly!

**Comment by TheHollidayInn** [comment]
I believe this is done. A PR seems to have been merged to fix this.

**Comment by Alys** [comment]
Thanks!
