### ISSUE TITLE
Expensive rewards reset to 21.27

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#617]
Any self-made reward that was above 49 Gold got reset to 21.27.  Easily fixed, but just thought you should know.

**Comment by PhilipHow** [comment]
Damn. Apologies, I missed that in the migration script! @lefnire?

**Comment by lefnire** [comment]
argh, my bad. sorry to say can't do anything about it at this point, just set it back manually :/

**Comment by cleave29** [comment]
No prob.  Already set it back.  Just thought you should know.
