### ISSUE TITLE
Cannot see party members in large group

### ISSUE THREAD

**Issue by juicysteak42** [HabitRPG/habitica#618]
I invited a friend of mine to a party where we already have 5 people. When I invited my friend, I was able to see him in the party, and he shows up on my party screen. However, he cannot see me in the party, nor can he see me in the party screen. We both can see everyone else in the party, and everyone else is also visible on the party screen.

**Comment by lefnire** [comment]
oi, a bug indeed. Gonna be some heavy debugging, so may be a while before I can get to this one.

**Comment by lefnire** [comment]
@justinnstuff can you try both leaving the party and rejoining, see if it works?

**Comment by juicysteak42** [comment]
As soon as my friend and myself get on Starcraft 2 tonight, I'll be sure to tell him to do so. I'll keep you posted. Also, I love the beta site. Great work!!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
