### ISSUE TITLE
Can't activate Triad Bingo

### ISSUE THREAD

**Issue by slylysylar** [HabitRPG/habitica#6184]
Dear Support,

Could you please help me investigate why I can't activate the Triad Bingo award?
I got both Beast Master and Mount Master award.
And this morning I found all 90 pets again but still no Triad Bingo.

Thank you very much for your time!
Regards.

**Comment by crookedneighbor** [comment]
Hi @slylysylar, we'll need your User ID to investigate.  You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.   

Note: Your user id is not the same as your profile name.

**Comment by slylysylar** [comment]
thanks for the lightning fast reply!
My user ID is as follows
261abc9f-ddff-4417-b6db-057f7691fce6

**Comment by Alys** [comment]
Hi @slylysylar. You've already released your Mounts. To get the Triad Bingo award, you need to have all pets and all mounts at the same time.

**Comment by slylysylar** [comment]
oh no, I thought that would be the normal procedure. Catch, tame, release, and catch again :(
Is there any way you guys can assist with this or I'm outta luck Alys?

**Comment by Alys** [comment]
I've given you the achievement.

**Comment by slylysylar** [comment]
Thank you so much. You are awesome!
