### ISSUE TITLE
Cannot create to-do checklists

### ISSUE THREAD

**Issue by jea0009** [HabitRPG/habitica#6187]
Lately whenever I press enter after adding one part of a checklist, all of my recent achievements pop up and block the screen instead of adding a new line for me to type in the second part. I am on a work computer so I only have access to IE.
 My ID is 7415cb9f-32c0-4173-ab76-cdef1216481d

**Comment by Alys** [comment]
Can you give us more details about what the recent achievements are? For example, do you see all the notifications of the gold, mana, experience, and drops that you've earned? Or do you see your profile page or your stats page that list your achievements, such as quests completed?

**Comment by SabreCat** [comment]
Possibly the same issue as encountered in #5423 / #5690 ?

**Comment by jea0009** [comment]
I see the notifications of all the gold, mana, experience and drops that I
have.  However, I just tried to take a screen shot to show you and it seems
that after 2 weeks of not working, it suddenly is working fine. Thank you!

On Thu, Nov 5, 2015 at 2:46 PM, Alys notifications@github.com wrote:

> Can you give us more details about what the recent achievements are? For
> example, do you see all the notifications of the gold, mana, experience,
> and drops that you've earned? Or do you see your profile page or your stats
> page that list your achievements, such as quests completed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6187#issuecomment-154170060.

## 

_Jaclyn Adamo_

Juris Doctor Candidate, Class of 2017
*Northeastern University School of Law *

Vice Chair of Social Activities - SBA
Chair of External Relations - Women's Law Caucus

Cell: 407-455-0921

**Comment by SabreCat** [comment]
OK, I can close this for now, but let us know if it recurs!

**Comment by Alys** [comment]
@jea0009 Thanks for letting us know. Are you using IE 10, or another version of IE?

**Comment by jea0009** [comment]
I am using IE 10

On Thu, Nov 5, 2015 at 3:00 PM, Alys notifications@github.com wrote:

> @jea0009 https://github.com/jea0009 Thanks for letting us know. Are you
> using IE 10, or another version of IE?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6187#issuecomment-154173813.

## 

_Jaclyn Adamo_

Juris Doctor Candidate, Class of 2017
*Northeastern University School of Law *

Vice Chair of Social Activities - SBA
Chair of External Relations - Women's Law Caucus

Cell: 407-455-0921

**Comment by Alys** [comment]
Do you happen to have the "Show All Notifications" bookmarklet installed in IE? That's the one described in the Bookmarklets section on the wiki's [Customizations](http://habitica.wikia.com/wiki/Customizations) page.

**Comment by jea0009** [comment]
I don't think so, I don't have any idea what the wiki's customizations page
is though.

On Thu, Nov 5, 2015 at 3:19 PM, Alys notifications@github.com wrote:

> Do you happen to have the "Show All Notifications" bookmarklet installed
> in IE? That's the one described in the Bookmarklets section on the wiki's
> Customizations http://habitica.wikia.com/wiki/Customizations page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6187#issuecomment-154178923.

## 

_Jaclyn Adamo_

Juris Doctor Candidate, Class of 2017
*Northeastern University School of Law *

Vice Chair of Social Activities - SBA
Chair of External Relations - Women's Law Caucus

Cell: 407-455-0921

**Comment by Alys** [comment]
If you click on the link in the previous message, it will take you to that page. However if you don't recall installing the bookmarklet, then I expect you haven't. Thanks for answering our questions! This information will hopefully get us a step closer to working out what IE is doing when it does that checklist bug.
