### ISSUE TITLE
Can't leveling over 14!

### ISSUE THREAD

**Issue by SimpleCreater** [HabitRPG/habitica#6190]
Hi there,
If I become level 15 an error pops up and it will not save my stats any more.
I hope you can help me out.

Error message:
Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.

your,
Skymen

**Comment by Alys** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4986
