### ISSUE TITLE
iOS Daily Reminder Time Jumped Back 3 Hours

### ISSUE THREAD

**Issue by sidawson** [HabitRPG/habitica#6192]
## PROBLEM

On iOS my daily reminder time (Settings > Reminder > Every Day at) was set to 10pm (22:00). Today it self-changed to 7pm (19:00).
## TO REPRODUCE

Unable to reproduce. Sorry
## NOTES
- It's hard to tell if this was because a) of the v1.1.1 update or b) timezones shifting - since both are happening at the moment
- It's possible this is because the daily reminder time is stored in the database in GMT (or similar not-my-timezone (NZT), eg PST).
## SUGGESTION

(if this isn't already the case) store the reminder time as a basic number, without timezone. Since the reminder is only done on my phone (not the web app) and my phone is always in my timezone, it will always be correct - even if I travel to different timezones
- If the intent was to provide (at some future point) web app reminders, note that the browser knows what time (& TZ) it is where the user is, so we don't need to know their local TZ, just what time (their time) they want an alarm - and to do it all client side (although obviously we use their TZ for their daily rollover/cron)
- Unfortunately, this may be a pita to transition to. Ugh. Timezone math. 
- If you have TZ + GMT/whatever reminder times for everyone and want them converted to their local time, I'm happy to volunteer to whip up a script to do this.

**User Id:** 78810b6b-221d-4baf-b6e7-1cbb8f028042

**Comment by librarianmage** [comment]
If it is a problem with the iOS app, it may be better to open an issue at [HabitRPG/habitrpg-ios](https://github.com/HabitRPG/habitrpg-ios).

**Comment by Alys** [comment]
@sidawson As @MathWhiz says, could you please copy this report to the iOS repository?
