### ISSUE TITLE
enchanted armoire gear later replaced with different gear

### ISSUE THREAD

**Issue by inquiryqueue** [HabitRPG/habitica#6194]
I had a golden tunic from the enchanted armoire and my avatar was wearing it as a costume.
When I logged in today, the golden tunic had been replaced with the "plague doctor overcoat" in my inventory (both for equipping and using as a costume) and on my avatar.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/5376
Please see the bold text near the top for an explanation.
