### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mtancoigne** [HabitRPG/habitica#62]
_edit by admin:_
## If you would like to help with translations, please see [Guidance for Linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists) which explains how translations are done.

You do not need to comment in this issue.

_end of edit by admin_

---

Hi all !
I discovered HabitRPG and I think there may be a lack of translations. As this project uses node.js, the translations may be possible with node-gettext (https://npmjs.org/package/node-gettext)
As I don't know node really much, I can help for French translations, if this proposition is kept.

**Comment by ghost** [comment]
I have friends that are willing to translate the website but they don't know code.

**Comment by griessauer** [comment]
I would like to help, I use c# so it shouldnt be a problem getting into that. I can translate it to german. (Native speaker)

**Comment by ghost** [comment]
Wonderful by any chance do you know any coders that speak more than one language as well?

**Comment by racuna** [comment]
I can help with spanish translation.

**Comment by griessauer** [comment]
A friend of mine speaks some slavic languages, I have to ask him if he wants to help!

**Comment by lefnire** [comment]
Ok cool, I'll put a framework in place (likely using that gettext project) with a README on contributing translations, then I'll check back here once that's done. You'll know I'm working on it when this ticket is tagged "current"

**Comment by coolandsmartrr** [comment]
I can help with the Japanese translation!

**Comment by ghost** [comment]
Do you know of anyone that knows any other Asian language? I have a guy who knows code and is willing to translate to Italian by the way. Furthermore I have at least one person who knows Arabic and can code. Plus on top of that I know a guy who can code and knows both Hindi and Marathi. Maybe Duolingo.com would be of great use to us?

**Comment by mtancoigne** [comment]
Translating using gettext files is really easy as each translation have it's own file containing the strings, making it easy to use as they are separated from code. Updates are easy too, as translated files refers to a "base" file, and if there are modifications is this file, your translation software can easily see the diffs... I recommend POEdit, Lokalize (spelling may be wrong as i'm not at home) or other open source softwares to do the job...

**Comment by lukelex** [comment]
I can help translating to portuguese.

**Comment by Karottes** [comment]
I can help for a french translation. Or make it alone !

**Comment by mtancoigne** [comment]
@Karottes I'm on it too :D

**Comment by Zequez** [comment]
I can help with the spanish translations!

**Comment by lefnire** [comment]
So everyone knows, I consider this task high-priority - will be getting to this as soon as the crits are nails, so expect to hear from me in a week or two

**Comment by racuna** [comment]
good to know :D

## 

oɔıɟíuƃɐɯ sǝ ɐunɔɐɹ ןǝ

**Comment by hpineroo** [comment]
I could Help whit the Translation to Spanish, I know a little to code so i could help on that. already send an email to lefnire.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by Elyriah** [comment]
I'm able to translate into German and Swedish, if that's still needed.

**Comment by CrazyBeggar** [comment]
I can help with the (brazilian) portuguese translation.

**Comment by lanseg** [comment]
What about not only translation, but a complete localization? For example, week, that starts with Sunday confuses me a lot.
And I can help you with russian translation (I have only basic skills of js, but I don't think it is criticall for gettext)

**Comment by ghost** [comment]
If there's any need in French and Dutch translation, let me know

**Comment by lefnire** [comment]
we should keep this one open

**Comment by w13** [comment]
I can translate into Urdu and Indonesian.

**Comment by wc8** [comment]
Note: This has a card [Translations] in Trello (https://trello.com/c/SvTsLdRF)

**Comment by dannyqwertz** [comment]
German native speaker here, will be glad to help!

**Comment by brohhr** [comment]
I can help with the Spanish translations too, if needed.

**Comment by dariatrainor** [comment]
I can help with Russian translation too.

**Comment by DDzwiedziu** [comment]
I can translate to Polish.

**Comment by kamilpowalowski** [comment]
I can polish @DDzwiedziu 's Polish translation.

**Comment by StanLindsey** [comment]
Just to let you know guys this is now one of our top priorities. Make sure to follow our [Tumblr](http://habitrpg.tumblr.com/) and/or our [Twitter](https://twitter.com/habitrpg) for all public updates.

That said we will make sure to update this thread and also feel free to [email me](mailto:stan@habitrpg.com) so I can add you to a list of future translators.

**Comment by lefnire** [comment]
So I just heard an awesome story of a spanish speaker putting all their tasks in the "Todos" column, because "Todos" in spanish means "Everything". Hahah, the user had 3 empty columns and one giant column

**Comment by hjalmberi** [comment]
I can help with the Russian translation as well.

I must say my Todos column also tends to be giant compared to the others :D

**Comment by tropister** [comment]
I'm a localization specialist and software translator (English>German), would be happy to help - including internationalizing source :)

**Comment by ghost** [comment]
I can help with the Swedish <--> English translations. I am a native Swede.

**Comment by lefnire** [comment]
awesome everyone. Stay tuned, we'll be tackling this within about 2 weeks

**Comment by lefnire** [comment]
@switz assigning to you, feel free to assign back if you don't want it. We need to coordinate with @SlappyBag as he's been collecting contacts for the process. This and REST API are important to do sooner than later because they set people up to contribute in the background while we work on other things.

**Comment by tmas** [comment]
gettext seems like it'll be pretty easy to integrate, but it will take some time. I'd recommend creating a [Crowdin project](http://crowdin.net/), so people who want to contribute can start contributing in a centralized location even before translation is implemented in the code.

**Comment by ruddfawcett** [comment]
Would there be an efficient way to do this?  I know, for example, in iOS Objective-C, you can use a `.strings` file.  Is there a similar method for JavaScript/CoffeeScript?

**Comment by tmas** [comment]
As mentioned above, the node.js module node-gettext.

**Comment by lefnire** [comment]
https://github.com/jamesknelson/derby-i18n

**Comment by tropister** [comment]
Translating without context tends to result in "interesting" translations, so I wouldn't recommend that.
Typically l10n projects (the properly managed ones that is) start with a glossary and a style guide where in a sense the "rules" are laid out, only once that's settled do translations commence.
I personally would recommend running internationalization checks first to ensure that not only all text is externalized, but also that there are no concatenation problems which tend to multiply rapidly depending on the number of languages. I can run i18n checks, but I would need a set of files containing externalized strings.
This is a bit more work up front, but it will make the whole process a lot smoother later.

**Comment by StanLindsey** [comment]
Considering this is a suggestion and a known current priority (which I'm now able to work on properly) lets move discussion to [Trello](https://trello.com/card/-/50e5d3684fe3a7266b0036d6/12)

**Comment by neameta** [comment]
If you need someone for French translation, i'm French and webmaster with a master degree in Multimedia Editorship.

**Comment by StanLindsey** [comment]
Hi @neameta - check out the [Translations tutorial](https://www.youtube.com/watch?v=BtUNAIBuqaU)

**Comment by petitemort** [comment]
I speak Spanish and French fluently. I can help with either or both if you need more volunteers.

**Comment by deilann** [comment]
@petitemort Check out [this Trello card](https://trello.com/c/SvTsLdRF/12-translations).

**Comment by Sazzie** [comment]
I can help with German and Spanish :)

**Comment by Alys** [comment]
Hi @Sazzie. Please see [Guidance for Linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists) which explains how translations are done. Thanks for helping!

**Comment by sujunmin** [comment]
Hi I just complete Chinese (Taiwan) Translation for Andoid, but there is no reviewer, somebody help me to review them, thanks.

**Comment by ghost** [comment]
@sujunmin you may want to apply to become one using [the Trello card](https://trello.com/c/SvTsLdRF/12-translations)

**Comment by sujunmin** [comment]
OK I apply for it.
