### ISSUE TITLE
Graph on Experience Bar Decreasing

### ISSUE THREAD

**Issue by kalmduck** [HabitRPG/habitica#620]
I've noticed my graph of Experience progress behaving strangely since the overhaul of the weighting algorithms.  The first day the update was pushed, there was a huge spike in my experience on the graph.  This was before I had the gigantic reward from performing a delinquent daily.  The experience went down a little bit after I adjusted the value, but it then started rising as expected when I completed tasks.

The Between the last two days, the experience dropped significantly (almost 1000).  While it is true that I haven't been as productive of late, It seems weird that the experience would be going down...

![Decreasing Graph](https://f.cloud.github.com/assets/3541909/237090/3e300d5a-8809-11e2-9e67-ddd2c723625c.png)

**Comment by lefnire** [comment]
the new algorithms have more sane caps, task values were adjusted from 1000-pt value (which was ridiculous, and a bug) back down to sane values (the low numbers you're seeing). So most graphs in the system that were very high should see a drop, and graphs that were very low should be brought back up. Hate this phrase, but "it's a feature" ;)
