### ISSUE TITLE
Timezone used by Habitica should be visible to the user

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6204]
When a player logs in to the website (i.e., literally logs in using the login form) or when they reload the website, their browser reads the timezone that their PC is set to and uses that for determining when cron should run and which Dailies should be visible. The timezone is stored in         `preferences.timezoneOffset` as a negative minutes offset (e.g., UTC+10:00 is -600).

It would be useful for this timezone to be visible to the user, to reduce questions about which timezone Habitica uses and to make it clear when the user's PC is set to the wrong timezone. (It would also be a first step in implementing a manual timezone setting https://github.com/HabitRPG/habitrpg/issues/6079.)

The timezone could be displayed on the [Settings -> Site](https://habitica.com/#/options/settings/settings) screen under the Custom Day Start form. It should be displayed as a numerical zone, relative to UTC, e.g., **UTC+10:00**

It should include a message that states these things (not necessarily with these words or in this order):
- Habitica uses the timezone set on your PC / mobile device.
- If you use two or more PCs / devices, the timezone should be the same on them all otherwise cron will be unpredictable.
- The timezone displayed here is the one that Habitica currently believes is yours.
- If that timezone is wrong, first reload the website to ensure that Habitica is reading the most recent timezone information from your PC. If it is still wrong, adjust the timezone on your PC.

We might also want to include more advanced instructions for users who do use more than one device. For example, after getting the timezone correct on one PC, repeat that process on all other PCs. If you use mobile devices, log in to Habitica there, and the come back to the Settings -> Site screen in the website and sync (NOT reload) to see which timezone the mobile device has set Habitica to; if it's incorrect, adjust your mobile device's timezone.

A developer working on this can use placeholder text until we determine the exact wording we want to use.

**Comment by AminArria** [comment]
I'll work on this.

This timezone would be displayed inside the Custom Day Start form right? Not in another form below it

**Comment by Alys** [comment]
Thanks @AminArria!

It should be in its own form under the CDS form. They're two different concepts so they need to be kept separate, and we don't want the users thinking that CDS is a good way to compensate for a wrong timezone.
