### ISSUE TITLE
Application error on load

### ISSUE THREAD

**Issue by gaballison** [HabitRPG/habitica#6206]
Pretty much every day when I try to log on to the Habitica website I get an application error telling me `Failed to load resource: the server responded with a status of 503 (Service Unavailable).` If I refresh the page several times that usually fixes it and my dailies reset, etc., although sometimes I think that contributes to my random duplicate damage entries.

Today, however, instead of the standard 503 error I got this:

```
TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (app-9d153fae.js:11)
    at j (app-9d153fae.js:7)
    at app-9d153fae.js:7
    at j.$eval (app-9d153fae.js:7)
    at j.$digest (app-9d153fae.js:7)
    at j.$apply (app-9d153fae.js:7)
    at s (app-9d153fae.js:6)
    at w (app-9d153fae.js:6)
    at XMLHttpRequest.y (app-9d153fae.js:6)(anonymous function) @ app-9d153fae.js:6
```

You can see in this screenshot that the page is just hanging there and the loading circle continues to spin:
![habitica-issue](https://cloud.githubusercontent.com/assets/12204283/11068536/c6193096-879f-11e5-9263-f0ea7680362b.png)

I refreshed the page and now it's working and my dailies have reset, I just thought I'd share since I hadn't seen this issue before. If you have any suggestions for why I'm getting the 503 error every day, I'd also appreciate help with that.

**Comment by ToraOkami** [comment]
I'm getting a similar Application Error, only when I try refreshing the page it thinks for a very long time then gives me the Error again. I have to completely close that webpage and open a fresh tab for Habitica to continue working properly.

**Comment by jlriddell** [comment]
I'm getting a similar error and reloading does not fix the issue - I also need to open a new page. 

```
Uncaught TypeError: Cannot set property 'menu' of undefined
https://habitica.com/api/v2/groups/undefined/chat/seen Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-bac72697.js:31 ObjectresponseError @ app-bac72697.js:31
app-bac72697.js:32 Uncaught TypeError: Cannot set property 'menu' of undefined
https://habitica.com/api/v2/user/batch-update?_v=785&data=1447950490252 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-bac72697.js:31 ObjectresponseError @ app-bac72697.js:31
```

**Comment by Alys** [comment]
@ToraOkami @jlriddell I've just restarted the website which typically fixes application error problems. Please comment here if it happens again today.

@gaballison We've restarted the site a few times over the past few days. Are you still getting an application error every day when you try to log on?
