### ISSUE TITLE
Change in XP gained for BoF

### ISSUE THREAD

**Issue by Thor333** [HabitRPG/habitica#6207]
Hi guys,
I've seen this many times, when in cast Burst of Flames on the same task multiple times in a row, the XP gained may change (a bit).
So, is it worthwhile bothering about it?
(Other stuff, is this thinkable to add some sound effects to the spells?)
++
![habitica 2](https://cloud.githubusercontent.com/assets/11922087/11069148/f2d902b6-87d4-11e5-9a99-e89671131ee3.jpg)
![habitica 3](https://cloud.githubusercontent.com/assets/11922087/11069149/f392d272-87d4-11e5-867f-99a6cc0707fc.jpg)
![habitica](https://cloud.githubusercontent.com/assets/11922087/11069150/f3a21e12-87d4-11e5-8606-0348b930d404.jpg)

**Comment by Alys** [comment]
It's possible to get a critical hit while casting that skill, which increases the XP gained by a small amount. That's what you're seeing when the XP is higher than normal. There is no critical hit notification for skills.

For sound effects, you might like to suggest them on our feature tracker, which you can get to at Help -> Request a Feature.
