### ISSUE TITLE
Header Bar not staying attached in Android Tablet Browser.

### ISSUE THREAD

**Issue by 1e7ksi** [HabitRPG/habitica#621]
![Screenshot_2013-03-01-09-54-28](https://f.cloud.github.com/assets/3770720/238084/88929da6-882a-11e2-9d0b-1d42e993ebd1.jpg)

I am on an Asus Transformer prime, running Android 4.1.1. The bug I found was that when I use the default browser, the header bar doesn't like to stay attached to the top. This isn't an issue in chrome.

Once floating, it tends to stay floating through turning the tablet.

**Comment by lefnire** [comment]
thoughts @zakkain ? Ps, that's the first time i've seen someone play undead :)

**Comment by caycefischer** [comment]
I know exactly what this is – a hole in our responsive design. Two things happen at a certain media query: the header becomes un-fixed and the top-margin on the main content wrapper gets modified. One or the other must not be triggering. 

I'm on it – @1e7ksi, is it possible for you to keep an eye on this issue, and sometime tonight or tomorrow I'll post ask you to test this again for me?

**Comment by caycefischer** [comment]
Actually, I think it's a different issue. I'm not positive yet but I think the Browser app is built on a webkit that doesn't support `position:fixed` and since the Transformer Prime has a 1280x800 resolution, it isn't triggering the MQ that un-fixes the header

edit: Nope, research indicates that Android 4.1.1 supports `position: fixed` no problem. Hmm

**Comment by caycefischer** [comment]
@1e7ksi can you please visit the following pages and report back?
1. http://bradfrostweb.com/demo/fixed/index.html
2. http://bradfrostweb.com/demo/fixed/noscale.html

---

_notes to self:_
- [ ] test modernizr detection
- [ ] drop pos:fixed usage?
- [ ] position: sticky?

**Comment by 1e7ksi** [comment]
I did a bit of playing and I was also able to replicate the original issue in Dolphin Browser. 

After a fair bit of playing, I was not able to get the header or footers to dislodge on your sites @zakkain on either the default browser or Dolphin Browser.

**Comment by caycefischer** [comment]
Ok, thanks a lot! That might narrow it down a bit.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
