### ISSUE TITLE
Error: Cannot set property 'drop' of undefined

### ISSUE THREAD

**Issue by startmyquest** [HabitRPG/habitica#6210]
I am unable to level up my character as every time I do it, I get the above error message

![screenshot 2015-11-11 at 08 27 49](https://cloud.githubusercontent.com/assets/4692218/11086988/5b78df52-884e-11e5-931d-3f0ffa633737.png)

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/4986 for an explanation and fix.
