### ISSUE TITLE
"Error Cannot read property (User ID) of undefined"

### ISSUE THREAD

**Issue by dzmcclure** [HabitRPG/habitica#6212]
Getting that every time I try to use the page in chrome.

Console log:
Navigated to https://habitica.com/
app-9d153fae.js:6 GET https://habitica.com/api/v2/groups/party 500 (Internal Server Error)(anonymous function) @ app-9d153fae.js:6s @ app-9d153fae.js:6f @ app-9d153fae.js:6j @ app-9d153fae.js:7(anonymous function) @ app-9d153fae.js:7j.$eval @ app-9d153fae.js:7j.$digest @ app-9d153fae.js:7j.$apply @ app-9d153fae.js:7g @ app-9d153fae.js:4i @ app-9d153fae.js:5g @ app-9d153fae.js:4xa @ app-9d153fae.js:4wa @ app-9d153fae.js:4(anonymous function) @ app-9d153fae.js:9j @ app-9d153fae.js:1k.fireWith @ app-9d153fae.js:1o.extend.ready @ app-9d153fae.js:1I @ app-9d153fae.js:1
app-9d153fae.js:37 danger
app-9d153fae.js:37 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}config: Objectdata: Objecterr: "Cannot read property '9f251795-7626-44c6-a1b5-ff88b285ea8f' of undefined"**proto**: Objectheaders: (c)arguments: (...)caller: (...)length: 1name: ""prototype: Object__proto__: ()<function scope>status: 500statusText: "Internal Server Error"**proto**: Object__defineGetter__: **defineGetter**()**defineSetter**: **defineSetter**()**lookupGetter**: **lookupGetter**()**lookupSetter**: **lookupSetter**()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get **proto**: get **proto**()set **proto**: set **proto**()responseError @ app-9d153fae.js:37j @ app-9d153fae.js:7(anonymous function) @ app-9d153fae.js:7j.$eval @ app-9d153fae.js:7j.$digest @ app-9d153fae.js:7j.$apply @ app-9d153fae.js:7s @ app-9d153fae.js:6w @ app-9d153fae.js:6y @ app-9d153fae.js:6

**Comment by Alys** [comment]
Please reload. If that doesn't fix it, clear local storage (google for how
to do that in your browser; it can be different than clearing cache). Tell
us if that doesn't work.

**Comment by Midgitus** [comment]
Getting the same error in Firefox on Windows 7. Of note, the error message shows up twice when I try to navigate to my party, which seems to have disappeared (problematic, since I was just part of a quest).

User ID: 128fffed-ede4-4ee8-9ff7-eb702e0282bf

Web Console (immediately after logging in):

<source> element has no "src" attribute. Media resource load failed. habitica.com
All candidate resources failed to load. Media load paused. habitica.com
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] platform.twitter.com
danger app-9d153fae.js:37:1965
Object { data: Object, status: 500, headers: tc/<(), config: Object, statusText: "Internal Server Error" } app-9d153fae.js:37:106

This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] fls-na.amazon.com
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] dbn3wu0k6poiv.clou

**Comment by Alys** [comment]
@Midgitus You're still in the party and quest. Did you try my suggestions from my previous comment? If not, can you please, and tell us if that helps or not?

**Comment by Midgitus** [comment]
Thanks, @Alys. I did try your suggestions. Unfortunately, they didn't help.

**Comment by paglias** [comment]
Could you try clearing your cookies? Or trying an incognito tab?

**Comment by Alys** [comment]
@Midgitus Can you try logging in using a different browser? If you have no other browser installed and aren't able to install one, please try using incognito mode in your current browser. Note that this is just a temporary workaround.

**Comment by Midgitus** [comment]
Cookies are cleared, still the same message.

@Alys I've tried in IE with the same error message. Trying Chrome now, but Chrome is hanging on me (not anything Habitica-related - it appears to be doing this with any site I'm on.) Just tried incognito in Firefox, with the same error message.

**Comment by paglias** [comment]
I fear that for some reason their data got corrupted in the database
Il 11 nov 2015 4:51 PM, "Midgitus" notifications@github.com ha scritto:

**Comment by Alys** [comment]
Party object for Midgitus (chat removed)

```
{
    "_id": "2ba2c769-45cd-4726-89fe-5ce0f5d11f0f",
    "__v": 268,
    "_v": 0, 
    "challengeCount": 0,
    "invites": [],
    "leader": "128fffed-ede4-4ee8-9ff7-eb702e0282bf",
    "memberCount": 1,
    "members": [
        "128fffed-ede4-4ee8-9ff7-eb702e0282bf"
    ],
    "privacy": "private",
    "quest": {
        "progress": {
            "rage": 0,
            "hp": 465.72753222511756
        },
        "active": true,
        "leader": "128fffed-ede4-4ee8-9ff7-eb702e0282bf",
        "members": {
            "128fffed-ede4-4ee8-9ff7-eb702e0282bf": true
        },
        "key": "trex_undead"
    },
    "type": "party"
}
```

**Comment by Alys** [comment]
And for dzmcclur (chat removed):

```
{
    "_id": "2eb5d3c7-77f1-42c5-84fc-a4dd01f37a69",
    "__v": 181,
    "challengeCount": 0,
    "challenges": [],
    "invites": [],
    "leader": "9f251795-7626-44c6-a1b5-ff88b285ea8f",
    "memberCount": 2,
    "members": [
        "9f251795-7626-44c6-a1b5-ff88b285ea8f",
        "6c199402-9c77-4359-81c9-1bbb98009ec1"
    ],
    "name": "[removed]",
    "privacy": "private",
    "quest": null,
    "type": "party"
}
```

Interestingly, Midgitus's party has no name field. I'm adding one now.

**Comment by Alys** [comment]
@Midgitus Can you please go to the party page and reload it? I have no idea if the changes I've made will help, but it's worth a try. :)  If it works, you can edit the name, description, etc, that I added. If it doesn't work, can you try a few other pages to see if errors also occur?

```
db.groups.update({_id:'2ba2c769-45cd-4726-89fe-5ce0f5d11f0f'}, {$set:{ 
    "name": "name goes here",
    "challenges": [],
    "description": "description goes here",
    "leaderMessage": "leader message goes here",
    "leaderOnly": { "challenges": false }
}});
```

**Comment by zoebeagle** [comment]
I am also getting this message... just started this morning.  I am using Chrome on Windows 10. I cleared all temp files/cookies and tried in incognito mode, none of which fixed it.  My party has seemingly disappeared.  If you need more info, please let me know.  Thanks.

<start error>
Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.

"Error Cannot read property 'e09e3b3c-a2ac-4a01-ab6e-739e83c79115' of undefined" 

If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.
<end error>

**Comment by Midgitus** [comment]
@Alys Worth a shot, but still giving me the error twice and prompting me to start a party.

**Comment by Midgitus** [comment]
@Alys The error is occurring on every Habitica page, actually. It just happens to be showing up on the party page twice.

**Comment by Alys** [comment]
@zoebeagle Your party still exists (the same applies to anyone else seeing these errors). It will come back as soon as we work out what's causing this.

**Comment by aideelad** [comment]
Hi!

I'm also getting this problem on party and tasks as well as several other pages of the site. I've tried clearing the cache and cookies on Chrome (Version 46.0.2490.80 m) and Opera (
Version:    33.0.1990.58) with no change. My user ID is  27b67351-41b1-4718-90ed-7dc510005747

Thanks!
Aidee

**Comment by GlassGypsy** [comment]
I am experiencing this exact same bug (including quest/party disappearance).  It's also preventing login to the oldgods site.  I'm accessing Habitica via Chrome on my android. Clearing cache/trying incognito mode hasn't worked.

Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.

"Error Cannot read property '7b9f2806-57c6-4643-833e-9c040ffa54a5' of undefined" 

If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

**Comment by zoebeagle** [comment]
Thanks @Alys you guys rock :)

**Comment by Alys** [comment]
Could everyone experiencing this please reload the site and tell me if it's still happening now?

**Comment by zoebeagle** [comment]
Looks like everything is back to normal here.  Thank you!

**Comment by GlassGypsy** [comment]
It showed the questless screen briefly at first, but corrected to normal by the time the page finished loading.  Oldgods site also working again. Thank you!

**Comment by Midgitus** [comment]
Beautiful - looks like everything is back to normal here. Thanks, @Alys !

**Comment by dzmcclure** [comment]
Whew this got fixed fast. Everything looks ok for me as well. Thank you!

**Comment by Alys** [comment]
Thanks everyone, especially for your fast replies to our questions! 

FYI to fix it we reverted some very recent changes to the site which shouldn't have caused errors, and certainly didn't during our testing, but obviously something was wrong. We'll go through those changes in detail to work out what it was.
