### ISSUE TITLE
Automatic logging of client side errors

### ISSUE THREAD

**Issue by gauthamchandra** [HabitRPG/habitica#6216]
This app doesn't currently seem to have any sort `onerror` hook to capture and send to us browser errors that might be happening.

Adding a tool such as [Rollbar](https://rollbar.com) or [Raygun](https://raygun.io/javascript) could help us solve this problem and fix bugs pre-emptively.

Worst case scenario, we should at least add a manual `onerror` event handler ourselves and then use it to log the error to LocalStorage so if they want to report a bug, then the UI can show them exactly what they should paste in the description of the Github issue.

--------

NOTE from @paglias: if possible let's use Loggly for this

**Comment by crookedneighbor** [comment]
I've added this to the API-v3 milestone.

**Comment by paglias** [comment]
Let's do this with the redesign

**Comment by lemoness** [comment]
@paglias Was this completed?

**Comment by paglias** [comment]
Not yet but we can use Loggly for this too I think

Il 16 Ott 2017 22:53, "lemoness" <notifications@github.com> ha scritto:

**Comment by lemoness** [comment]
Okay -- then should I close this issue, or change the status?

**Comment by paglias** [comment]
I've changed the tags and updated the description
