### ISSUE TITLE
Random Death

### ISSUE THREAD

**Issue by justicar347** [HabitRPG/habitica#6220]
I logged on today and found that I had died. I should not have taken any damage. All dailies were checked and I am not fighting a boss. I think this may have happened several weeks ago as well. I had dailes unchecked, but seemed to take way to much damage.

User ID: 7f4483a2-b6b1-434f-82b1-899927234c98

Using Chrome and windows 7

**Comment by justicar347** [comment]
A quick update. I just noticed that several dailies are still checked. However, I checked them well before cron last night.

**Comment by Alys** [comment]
Sorry about that! You were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313
Please see the Advice section near the top.
