### ISSUE TITLE
No tutorial or way to start the tutorial?

### ISSUE THREAD

**Issue by TrainerAnade** [HabitRPG/habitica#6225]
I joined the website yesterday afternoon and was never shown a tutorial or any way to go through a tutorial. I never saw an error, either. I tried closing the browser completely and coming back in and I tried logging out and back in, but I never got a tutorial, error, or notification of a tutorial. I signed up through Facebook and hadn't downloaded the app yet, so I'd only been on the website.

I was able to figure out how to do things through the FAQs and wiki, but I wanted to mention it so hopefully no one else has to try to figure out how to use everything on their own. I asked in the Newbie Guild and looked through the issues here and didn't see anything similar.

My User ID: fb8f5c3c-cd6f-4478-8a01-67648b6ddb37
I'm on a laptop running Windows 10, using Goodle Chrome Version 46.0.2490.86 m

**Comment by crookedneighbor** [comment]
@JJStamm Thanks for reporting this! I think I know what's wrong and am testing a fix for new users.

Would you like me to reset the tutorial for you? Or do you have it handled?

**Comment by crookedneighbor** [comment]
That is to say, do you feel like you understand the app well enough that you don't want to do the tutorial :)

**Comment by TrainerAnade** [comment]
@crookedneighbor I've figured out things at this point, I think and don't need a tutorial. But thank you for the offer!
