### ISSUE TITLE
Cannot hatch eggs

### ISSUE THREAD

**Issue by madisonparklove** [HabitRPG/habitica#6230]
I cannot hatch any of my eggs. When I click on a potion (or egg), Alexander the Merchant asks me if I want to sell it, and then when I click on an egg (or potion) nothing happens. My only options seems to be to sell the items, which I don't want!

**Comment by Alys** [comment]
You should get a pop-up dialog saying "do you want to hatch..." (or similar). It contains a checkbox that asks if you don't want to see those pop-ups again (that's added by your browser and we have no control over it). Did you tick the checkbox once before? If so, you won't see those pop-ups again, and hatching won't work. You can tell your browser to reset that setting by closing all browser windows.

**Comment by Alys** [comment]
I'm closing this but if you still need help comment here.
