### ISSUE TITLE
Buying Mage Staff causes shield hand equipment to unequip with auto-equip off

### ISSUE THREAD

**Issue by esmanning** [HabitRPG/habitica#6231]
I have "Auto-equip new gear" turned off, but whenever I buy a Mage staff, I get the "[staff name] is two handed" message, and my shield hand equipment (Mustaine's Milestone Mashing Morningstar) unequips itself. My weapon hand equipment remains as it was before the purchase.

UID: 809d8b43-07a1-49ab-9bb5-ad3ba461688d

**Comment by Alys** [comment]
Nice catch. I've advertised this in Aspiring Coders since it should be fairly easy to track down.

**Comment by ojeytonwilliams** [comment]
@Alys I think I found a solution to this, but it made me realise there's something about the habitica code I can't get my head around.  What are the files in common/script/src used for?  I assumed they would compile into common/script, but that doesn't seem to be the case.

**Comment by crookedneighbor** [comment]
They are not used. That was my attempt at an es6 refactor. They will be deleted soon.
