### ISSUE TITLE
23 Perfect Days Achievement for no Dailies

### ISSUE THREAD

**Issue by camachoborracho** [HabitRPG/habitica#6238]
First go under User > Stats & Achievements and scroll down to various achievements.

If you find new people who haven't added Dailies yet and have been on for a while, you may notice this. I added mine about 2 days ago but, I got an award for not doing any Dailies (which seems to defeat the point of accomplishing actual Dailies, no?).

"23 Perfect Days
Completed all active Dailies on 23 days. With this achievement you get a +level/2 buff to all attributes for the next day. Levels greater than 100 don't have any additional effects on buffs."

At the time that I started out I had no Dailies for about a month, though now I have added 2 Dailies and only been following them for 2-3 days, so there's no way that this is correct. I believe there's a bug somewhere along the lines of No Dailies = Not Missing Dailies = Streak (For X days) = Award (for X Days)
![habitica dailies bug](https://cloud.githubusercontent.com/assets/15842968/11162168/5e228ce6-8a4a-11e5-8dde-34c5974e044e.png)

**Comment by Alys** [comment]
Thanks @camachoborracho. We have this recorded (somewhat messily) at https://github.com/HabitRPG/habitrpg/issues/4535 and it's also closely related to https://github.com/HabitRPG/habitrpg/issues/2565 which I've just edited to explicitly describe this case.
