### ISSUE TITLE
Party Recruitment Trouble

### ISSUE THREAD

**Issue by sagerpg** [HabitRPG/habitica#6239]
hi when I try to invite an existing user to join my party it gives me a message saying "User already pending invitation." but the they haven't received the invite

My User ID is: 8be36885-7014-4f45-8fcb-f87e90a31a12
the group ID is: 30b0c744-0040-41c3-85ec-db3a9b7c71ac

**Comment by Alys** [comment]
What is the user's ID?

**Comment by sagerpg** [comment]
8b24dae5-23f9-48d5-9374-5380c72c4ad4

**Comment by sagerpg** [comment]
I also had a similar problem when i tried to invite our other member but I don't remember how I solved it

**Comment by Alys** [comment]
That user already has a pending invitation for a party, so the message you saw was correct. They'll need to reject that existing invitation before they can receive a new one (or accept it of course if they want to be in that party, in which case they also won't be able to receive new invitations).

I'm going to close this now, but if they have any problems with rejecting the invitation, they can comment here. Sometimes invitations persist after being rejected or accepted.
