### ISSUE TITLE
Tags not re-ordering when I re-order them also randomizing when I edit a Daily

### ISSUE THREAD

**Issue by Awesumpunk** [HabitRPG/habitica#6241]
My UUID is: f7c356cf-3888-4884-acfa-ff61e7f51321
This just started this morning (11/14/2015) and it's very annoying.  What happens is I try to re-order my tags in a way that makes sense so that the Challenge tags are at the bottom of the list, and they don't stick after I press the sync button.  Then I click the Grey Dailies button and go to untag the "Still Needs Improvement" tag from some dailies that I find rather easy to work on now and not only are my tags not "stuck" but they've completely rearranged themselves again.  [Saturday's are my "Dr. Meta" day, by the way]  This is very annoying and I know that while it's probably not on the top of your list of To-Do's I would love it fixed before I go "tag insane".

**Comment by Alys** [comment]
I can't replicate this so I think it's a local problem with your browser. 

First try reloading the site to see if that fixes it.

If it does not, please log out of Habitica, clear cookies, cache, and local storage, close all browser windows, and then log back in and try again.

If that doesn't fix it, and if you have another browser installed, please try on that. This is a temporary workaround and you won't have to keep using that other browser permanently. Tell us if it works or not on that other browser.

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see the suggestions from my previous post, and let us know if any of that helped. We'll still see your reply and can reopen this if necessary.
