### ISSUE TITLE
enabling pushTaskToBottom

### ISSUE THREAD

**Issue by bill-mcgonigle** [HabitRPG/habitica#6248]
I'm a fairly new user (again) - I'm using pushTaskToTop regularly, but adding new ToDo's is a chore because my list is so long I have to plan on spending half a minute per entry, as I have to drag most tasks all the way to the bottom.  Having pushTaskToBottom working would save me quite a bit of time (and encourage good habits...).

I see that pushTaskToBottom is there but commented out:
https://github.com/HabitRPG/habitrpg/blob/2d862593ae4152e2b3a61c66f71dc203ea2341de/website/views/shared/tasks/meta_controls.jade#L18  
I didn't see any commits explaining why.  If it's for UI clutter reasons, I'd like to suggest binding ctrl-click on pushTaskToTop as a UI element.  I need to do my sorting on desktop anyway, so it's not a real problem that I can't ctrl-tap on mobile.

I don't have an instance setup here at this point.  I didn't want to go to the trouble of doing that and submitting a pull request if there's a reason pushTaskToBottom isn't currently enabled (like maybe it doesn't actually work yet).

**Comment by Alys** [comment]
Ohhh... ctrl-click..... That's a clever idea.

It is only for clutter reasons that we don't have push-to-bottom fully implemented yet, although I very much want it when we reorganise the task icons (https://github.com/HabitRPG/habitrpg/issues/3921). The feature would work if there were a UI element for it. We added the code for it to try to help with the To-Do sorting bug and so `pushTask(task,$index,"bottom")` is already in use when you complete a To-Do (https://github.com/HabitRPG/habitrpg/pull/4007).

@lemoness Can we allow ctrl-click on the "push to top" icon to implement "push to bottom"? It would be an obscure feature, but it's not essential so it doesn't matter if some players don't find it (a tool-tip could help with that anyway). It would make my To-Do processing so much more convenient, and I've seen comments from others saying similarly. I don't see any downside to this idea.

**Comment by SabreCat** [comment]
I like the ctrl-click idea too! Especially if the push-to-top icon flips to a push-to-bottom icon while Ctrl is held.

**Comment by crookedneighbor** [comment]
:+1: to icon flipping

**Comment by bill-mcgonigle** [comment]
just a quick note - before figuring out how to do a local habitica install (->To-Do), I tried this just using the Chromium debugger, and it didn't work for me.  I'm not really sure how the interplay of the debugger and Angular work though, so maybe it wasn't a valid test:

`a(ng-click='if($event.metaKey || $event.ctrlKey) { pushTask(task,$index,'bottom') } else { pushTask(task,$index,'top') }'', tooltip=env.t('pushTaskToTop'))`

metaKey because ctrlKey reportedly doesn't work on Mac, but command-click does.

**Comment by crookedneighbor** [comment]
I think we should have a global listener for the meta key. On keydown, it applies a class to the body element. On keyup, it removes that class. 

The button toggle will then be as easy as hiding one and showing the other when the class is applied and the reverse when the class is not applied.

It will also allow us to do similar things in the future without any hackery.

**Comment by Alys** [comment]
@bill-mcgonigle Did you have any questions about crookedneighbor's suggestion for a global listener? Or about the local install? If you run into problems with either, you're welcome to comment here for assistance. If the local install isn't going smoothly, it often helps to run `npm install` more than once (e.g., that eliminates problems due to temporary network outages), and if it still doesn't work, show us the full output of the command.

**Comment by TheHollidayInn** [comment]
I have actually added something similar to what @crookedneighbor is describing here: https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/inventoryCtrl.js#L260
https://github.com/HabitRPG/habitrpg/blob/71473a93ad415d84f20ccd2bdfefa9a93f9728db/website/views/index.jade#L3

This is a global event that can be fired and watched. I used this for hitting the escape key to cancel pet actions.

**Comment by Alys** [comment]
@TheHollidayInn Thank you! That should be very helpful!
