### ISSUE TITLE
Suggestion: Detach from realtime

### ISSUE THREAD

**Issue by zommuter** [HabitRPG/habitica#625]
Apart from server outages: Since I sit in front of a computer all day long at work, I sometimes really prefer to not continue this at home. My proposal is therefore an option "Detach from realtime": When one logs in, the RPG-time is still at the date set last time, and one can manually click on "next day" after having entered the actions of that day. This allows both for habits like "Don't use your computer too often" and to not punish someone with the bad luck of having no internet connection.

**Comment by wc8** [comment]
[Account Freeze on Lengthy Inactivity](https://trello.com/c/UqxYFiqG) was suggested for that very reason.

**Comment by zommuter** [comment]
That's also a good suggestion, but it doesn't help in a "one week without internet (on purpose) while still doing daily exercises" scenario - especially if you want to be honest about having missed out last Wednesday...

**Comment by wc8** [comment]
Hm... so perhaps what you're looking for is more the start new day manually idea mentioned on [Record Yesterday's Activity](https://trello.com/c/CaAm7APS)

**Comment by zommuter** [comment]
If the "Yesterday" is changed to an arbitrary day in the past (up to a sensible limit) and includes a day-wise progression, that is it, yes.

**Comment by wc8** [comment]
I added a sub-request for correcting previous days history. Perhaps 7 days is a good limit?

**Comment by zommuter** [comment]
Thanks, I guess seven days are fine. Though from a technical point of view I don't understand why there even has to be a limit, it's not like that'd be using up more resources. In the unlikely event of so-called vacation (yeah, that's just a myth, I know) it'd fail again - though then one could disable the dailies and later on and add fake rewards for going to the beach :-7

**Comment by wc8** [comment]
Hm... I added a limit because I thought you were suggesting it. 

> to an arbitrary day in the past (up to a sensible limit) 

It might use up more resources... I think the history/progress might be preened after a certain period.
