### ISSUE TITLE
Guild description is too narrow on guild page

### ISSUE THREAD

**Issue by lvdpal** [HabitRPG/habitica#6252]
When looking at a guild page with a long description the site forces you to scroll very far down, even if you have a screen that has plenty of space too allow it to be wider.

![image](https://cloud.githubusercontent.com/assets/3662798/11206257/169e9f06-8d0e-11e5-8c90-87537da14c1c.png)

It would be nice if this had a variable width, so it would just use the space that is available. For example like this: 
![image](https://cloud.githubusercontent.com/assets/3662798/11206298/600e4fe2-8d0e-11e5-8376-864d24720cdd.png)

**Comment by Alys** [comment]
That would be nicer!

Everyone: Unless there's any objections in the next couple of days, I'll mark this as "help welcome now" and advertise it in the Aspiring Coders guild.

**Comment by markhowson** [comment]
The existing wide popover doesn't seem wide enough, so created a new little class just for this one. It's my first commit and I'm no CSS guru, so apologies if this is a terrible idea!

**Comment by lvdpal** [comment]
I already had a look at the code myself, (but had some trouble getting it installed locally to test it) and as far as I could see the wide popover was only used for this one location. But I couldn't test it, so I didn't dare make the change. (Especially since it would be my first commit too.)

**Comment by markhowson** [comment]
Oops, sorry, didn't mean to step on your toes! You're quite right, though - I'd searched and thought wide-popover was being used in the seasonal shop/etc, but it's not in the code any more. Amended.

**Comment by lvdpal** [comment]
No toes were stepped on, no worries!
Op 26 nov. 2015 14:01 schreef "markhowson" notifications@github.com:
