### ISSUE TITLE
"You do not own this pet" (or mount) message when displaying a pet / mount you have just hatched / raised

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6253]
When you hatch a pet and click on the "display" button in the modal screen that appears, you sometimes see the message ":You do not own this pet" and the pet does not appear in your avatar. However when you go to your Pets page, you can see the pet there, and it remains after a sync.

![screen shot 2015-11-17 at 8 20 10 pm](https://cloud.githubusercontent.com/assets/1495809/11208867/4ddc979c-8d69-11e5-9748-1a0c6a951709.png)

A similar thing can probably happen when raising a mount.
## What to do if this happens to you:

Find the pet in your [Inventory -> Pets](https://habitica.com/#/options/inventory/pets) page (or the mount in your [Inventory -> Mounts](https://habitica.com/#/options/inventory/mounts)  page) and click on it. It will then be displayed in your avatar. Click on it a second time if you decide you don't want it there.

The error message is almost always just a temporary glitch and it doesn't mean that you don't own the pet or mount. However in rare circumstances, a sync error might later cause the hatching action to be reversed, in which case the pet (or mount) will disappear, but the hatching potion and egg and (or food/saddle and pet) should reappear in your inventory and you can use them again to re-hatch the pet (or re-raise the mount).

You do **_not**_ need to report this error by commenting below. We know it can happen to any user.

**Comment by SabreCat** [comment]
Hmmmm. Can we confirm it has to do with speed of clicking? While developing those buttons, I had this issue with any egg or hatching potion that included spaces in its name (e.g. Flying Pig, Cotton Candy Blue), but I thought I had addressed that. It's possible the issue has recurred.

**Comment by SabreCat** [comment]
I was able to equip a just-hatched Tiger Cub, so that disproves my hypothesis at least on the egg side.

Can we use some kind of queueing to avoid a race condition here? ( @crookedneighbor ?)

**Comment by SabreCat** [comment]
While doing some testing on fixes to the sharing modals, I got this error again with a Cotton Candy Pink pet.

**Comment by Alys** [comment]
Ah, it might be related to spaces in the potion name. I just had it happen with two spaced-potions and not with one non-spaced potion.

**Comment by Alys** [comment]
I've removed the speed of clicking comment from the OP.

**Comment by Alys** [comment]
Well that was significantly faster to fix than I thought it would be. :-/
