### ISSUE TITLE
Typo in suggestion to read "Communit Guidelines"

### ISSUE THREAD

**Issue by TheSchwamm** [HabitRPG/habitica#6254]
When one has not yet agreed to follow the Community Guidelines, the following text appears above Party Chat:  "If you would like to post messages in the Tavern or any party or guild chat, please first read our Communit Guidelines and then click the button below to indicate that you accept them."  The trailing "y" is missing from "Community."

**Comment by crookedneighbor** [comment]
Fixed with 6bd0ed76cc7e2355af2697d6fb5fe898bcebbc5a
