### ISSUE TITLE
Not receiving damage from quest boss

### ISSUE THREAD

**Issue by EmanonSuomynona** [HabitRPG/habitica#6257]
For the Icy Arachnid quest that I (and my rather large party) am on, I have not been dealt damage even though the boss we're fighting has damaged the party.This is probably an issue I shouldn't be complaining about, but without any boss damage, it's a little bit boring. :)

My User ID is 8cb48592-37f4-4925-a1fd-9b030f6d8619.

**Comment by SabreCat** [comment]
Have any of your party members been using the "Blessing" ability to heal the party? When you log in, Blessings and damage from Dailies including boss damage get totaled up, then the overall change to Health is applied. So if, for instance, the boss hit you for 10 and 5, but your party Healers sent out Blessings totaling 20, you wouldn't see your Health go down at all.

**Comment by EmanonSuomynona** [comment]
No, none of my party members have cast Blessing since the damage.
Here is the party chat record.
![image](https://cloud.githubusercontent.com/assets/15892973/11220621/786c6e9e-8d26-11e5-9a4d-02107418dd8a.png)

Also, for some strange reason, the problem was fixed just now when the boss dealt 3.5 damage... I have no idea why... Anyway, sorry for the trouble, I guess...

**Comment by SabreCat** [comment]
OK! Keep an eye out; you can reopen this issue if it starts happening again!
