### ISSUE TITLE
Completing task wipes get certain days of the week with swagger UI and python requests

### ISSUE THREAD

**Issue by natfarleydev** [HabitRPG/habitica#6258]
I am feeding the 

```
post /user/tasks/{id}/{direction} 
```

method a task from

```
get /user/tasks/{id} 
```

. When I do this, it wipes the 'certain days of the week' information, even though it is present (I think?) 

The task in question is here (with history redacted)

```
{
  "text": "Morning prayer",
  "challenge": null,
  "attribute": "str",
  "priority": 1,
  "value": 600.6831555473431,
  "tags": {},
  "notes": "",
  "dateCreated": "2014-03-31T06:30:00.190Z",
  "id": "4d711783-0bff-4776-b0e8-733692682dd6",
  "streak": 46,
  "checklist": [],
  "collapseChecklist": true,
  "repeat": [
    "th",
    "f",
    "m",
    "su",
    "s",
    "t",
    "w"
  ],
  "completed": true,
  "history": [
    {
      "date": 1396327814509,
      "value": 1
    }
  ],
  "startDate": "2015-07-02T18:13:06.522Z",
  "everyX": 1,
  "frequency": "weekly",
  "type": "daily"
}
```

After running the "up" action on the task, the `"repeat"` section is not altered.

**Comment by natfarleydev** [comment]
I should say that although the `"repeat"` section is not altered, on Habitica.com the task does not show up as an active daily.

After completing the task, it looks like this (history redacted again):

```
{u'attribute': u'str',
 u'challenge': None,
 u'checklist': [],
 u'collapseChecklist': True,
 u'completed': True,
 u'dateCreated': u'2014-03-31T06:30:00.190Z',
 u'everyX': 1,
 u'frequency': u'weekly',
 u'history': [{u'date': 1447752357976, u'value': 601.3246351584752}],
 u'id': u'4d711783-0bff-4776-b0e8-733692682dd6',
 u'notes': u'',
 u'priority': 1,
 u'repeat': [u'th', u'f', u'm', u'su', u's', u't', u'w'],
 u'startDate': u'2015-07-02T18:13:06.522Z',
 u'streak': 47,
 u'tags': {},
 u'text': u'Morning prayer',
 u'type': u'daily',
 u'value': 601.2541552167252}
```

**Comment by Alys** [comment]
You've said that it wipes the day of week information but you've also said that it's not altered, so I'm not sure what behaviour you're seeing. Using `direction` is meant to just mark the task as completed or not completed. For a Daily, if you mark it as completed, it will turn grey in the website because it is no longer due that day (but it should still have the same due days configured so that it can become due again on that day next week).

Can you clarify the problem?

**Comment by natfarleydev** [comment]
Sorry, it wasn't very clear. The problem is that when 'Morning Prayer' is completed with the API method, it deletes the days from the 'certain days of the week' on the website, so that the daily never occurs.

On further inspection, it looks like the problem is that the 'Morning Prayer' task has somehow had it's 'repeat' property corrupted. This means that instead of `"su": true`, 'Morning Prayer' only has `"su"`.

Compare with

```
{
  "text": "Brand new daily",
  "challenge": {},
  "attribute": "str",
  "priority": 1,
  "value": 0,
  "tags": {},
  "notes": "",
  "dateCreated": "2015-11-17T21:54:04.669Z",
  "id": "4e75c17b-148f-4dc5-ae61-711756c4be8a",
  "streak": 0,
  "checklist": [],
  "collapseChecklist": false,
  "repeat": {
    "su": true,
    "s": true,
    "f": true,
    "th": true,
    "w": true,
    "t": true,
    "m": true
  },
  "completed": false,
  "history": [],
  "startDate": "2015-11-17T21:54:04.669Z",
  "everyX": 1,
  "frequency": "weekly",
  "type": "daily"
}
```

**Comment by Alys** [comment]
When you use `post /user/tasks/{id}/{direction}` with a direction of `up` on a task that doesn't have the 'repeat' property corrupted, does it work correctly? I.e., does the task get marked as done, but the repeat settings are not changed inappropriately?

Separate to that, do you have any idea what could have caused the repeat settings to be corrupted for your prayer Daily? Was the Daily created through the Habitica website, or through a mobile app (which one?), or through the API?

**Comment by natfarleydev** [comment]
When the repeat parameter is not corrupted, `post /user/tasks/{id}/{direction}` works fine.

I was able to reproduce the corruption bug but only in python (not with Swagger UI). I think it may be a bug in the requests library, since the corruption only happens when I use `requests.put` method. When I use the `requests.put` method in python with `put /user/tasks/{id}`, the repeat item becomes corrupted.

**Comment by Alys** [comment]
Okay, I'm closing this, but if you need help with your Python code that uses the API, you're welcome to show us the code!
