### ISSUE TITLE
Level dosn't rise

### ISSUE THREAD

**Issue by LetArch** [HabitRPG/habitica#626]
When I got the experience from an extention for Chrome, I didn't have level up, but the experiense is 213/210

**Comment by arscan** [comment]
Same issue for the core API (not just extensions).

**Comment by lefnire** [comment]
all our `model.on` subscribers are client-side. I'll just have to run the api functions through /app/scoring.coffee -> updateStats(). Easy fix, and I'll need it for my mobile development coming up, so expect a fix soon

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
