### ISSUE TITLE
Only one sub-task can be checked off before application error is thrown for other sub-tasks

### ISSUE THREAD

**Issue by salfej** [HabitRPG/habitica#6268]
Working on Chrome Version 46.0.2490.86 m. Habitica is a pinned tab that opens up when launch chrome, and I'm already logged on. I access it on several computers, and this particular computer I haven't used to access Habitica in about a week. When I logged on, I got messages for the past 5 achievements I received (leveling up, hatching a dragon, etc.). I have Daily tasks with several sub categories to check off. 

![image](https://cloud.githubusercontent.com/assets/10404888/11276319/46082ae2-8ea7-11e5-99d0-0859134cb951.png)
When I check off one, the loading bar at the top goes very slowly and fails at about 98%. It gives me a service 503 error. If I try to click a subsequent sub-task within one of my daily tasks, more application errors are thrown. Checking off main tasks does not see the same issues (as long as they are not click when the loading bar is processing).

![image](https://cloud.githubusercontent.com/assets/10404888/11276235/dfe2b1b0-8ea6-11e5-940c-8cac5f89c2d4.png)

I've refreshed the tab a few times, closed and reopened chrome. I have not signed out and signed in again yet. I don't believe this is happening on any of my other devices/computers. It could be an authentication issue, but I find it strange that the first item I check off IS being saved while the rest throw errors.

**Comment by sjvrijn** [comment]
Same problem here. Also with Chrome version Versie 46.0.2490.86 m, not as a pinned tab. Wanted to create 2 new habits and reorder them. Kept throwing the error after 1 (saved) action. Refreshing meant I could do one more thing, then the errors came again. Same console log messages

**Comment by Alys** [comment]
I've just restarted the website which typically fixes application error problems. Please comment here if it happens again.

**Comment by salfej** [comment]
The restart seems to have worked. My sub-tasks don't throw errors anymore, and the response time is quick again. Everything seems to be in working order again!

However, the first uncaught security error is still present. I logged out and logged back in just to make sure it wasn't an authentication thing. Haven't cleared cache and cookies yet, but I could try that later. The https://s7.addthis.com/ website has a very interesting (almost haiku) message. I'm not sure I've seen it anywhere around Habitica before. The error doesn't seem to interfere with usability, though, so I guess this issue is resolved. Thanks!

**Comment by citrusella** [comment]
Addthis provides the share button on the avatar. Dunno why there's a security error, but simple layman me thought I'd mention that. XP

**Comment by Alys** [comment]
I'm closing this because the restart we did seems to have fixed the server errors. The security warning about addthis.com isn't related, and isn't a security problem for any players (at worst, it would prevent the avatar being sharable).
