### ISSUE TITLE
The Moonstone Chain, part 3 hasn't been unlocked

### ISSUE THREAD

**Issue by Aidenbloodaxe** [HabitRPG/habitica#6271]
Hello, the Moonstone Chain, part 3 hasn't been unlocked even though I've just completed part 2, I'm level 73(requirement is 60) & I was supposed to receive the quest as a reward for completing part 2.
- Kind Regards

**Comment by Alys** [comment]
Thank you for reporting it, but this is the same issue that's being tracked at https://github.com/HabitRPG/habitrpg/issues/4252 so I'll close this one. If you'd like us to give you the rewards for the quest, please comment on that issue with your User ID (it's different than your name; to learn how to find your User ID, see step 6 from the instructions at Help -> Report a Bug). There's probably others in your party who are missing the rewards too, so either you or they can give us their User IDs too (it doesn't all have to be at the same time).
