### ISSUE TITLE
Unable to leave party

### ISSUE THREAD

**Issue by natfarleydev** [HabitRPG/habitica#6279]
I am currently unable to leave my party. I press 'leave' but I stay in the party. Any suggestions?

**Comment by Alys** [comment]
Try clearing local storage for the habitica.com domain (that's different than clearing your cache so you might need to google how to do it for your browser). You can also try on a different browser, or an incognito window in the same browser.

If none of those things work, tell us what happens when you try each of them, and then we can try to help further, but we'll need information about your account, party, and platform. Please see Help -> Report a Bug (from the Habitica website's toolbar) for a description of the information we'll need.

**Comment by natfarleydev** [comment]
Clearing localStorage did not help unfortunately.

I'm running Fedora, with the latest Firefox installed.

When I press 'leave', I get the following error in the js console:

```
Error: b.group is null
b.clickLeave/</c<@https://habitica.com/app-0281e5d3.js:33:10397
Va@https://habitica.com/app-0281e5d3.js:29:6295
b.clickLeave/<@https://habitica.com/app-0281e5d3.js:33:10374
j/</v[f]/s<@https://habitica.com/app-0281e5d3.js:10:20975
j@https://habitica.com/app-0281e5d3.js:7:9455
k/<@https://habitica.com/app-0281e5d3.js:7:9652
wd/this.$get</j.prototype.$eval@https://habitica.com/app-0281e5d3.js:7:16398
wd/this.$get</j.prototype.$digest@https://habitica.com/app-0281e5d3.js:7:14857
wd/this.$get</j.prototype.$apply@https://habitica.com/app-0281e5d3.js:7:16676
s@https://habitica.com/app-0281e5d3.js:6:12595
w@https://habitica.com/app-0281e5d3.js:6:14213
y@https://habitica.com/app-0281e5d3.js:6:13875
```

My UUID is: `ecc53331-4aa1-4b02-b3b3-e794d0ff6827`
My Group UUID is: `260a8b42-e73f-431a-aaf2-0f5fc178880a`

As for possible cause, I'm currently building a python API for Habitica (https://github.com/nasfarley88/pyhabitica), so it's possible I've accidentally corrupted my user. This is unlikely however, since at the moment I have only used POST and PUT on tasks.

**Comment by Alys** [comment]
Thanks for the information about your python work but I agree with you that it's unlikely to be related (when it's finished though, post about it to the Aspiring Coders guild and I'll add a page to the wiki for it).

Your account had three closed/deleted challenges in its challenges array which _might_ have been causing the problem (details below for our reference). I've set your challenges array to [](empty). Please reload the site and tell me if you're now able to leave the party.

```
    "challenges": [
        "3354bbeb-655b-46d6-82d8-ba6db0530d2f",
        "f84158b1-f397-46fb-8a3f-c223def013e5",
        "c348496c-8e8e-4490-98db-b3868f139f20"
    ],
```

**Comment by natfarleydev** [comment]
No effect. I used `localStorage.clear()` in Firefox again just to be safe, but I get the same error message when I press 'leave'.

**Comment by Alys** [comment]
Can you please try in a different browser? If that doesn't work, I'll edit your account and the party in the database to remove you.

**Comment by natfarleydev** [comment]
Fresh install of Google Chrome yields the same result (i.e. I don't leave the party).

**Comment by Alys** [comment]
@nasfarley88 I've removed you from the party - tell me if that's still not looking right for you! I'm about to close this but we'll still see any comments you make here.

I'm sorry about the immense annoyance this must have caused you, and thank you for helping us troubleshoot it. Your js console errors will be of use with trying to work out what's going wrong, so we'll keep note of this issue.

**Comment by Alys** [comment]
Actually, sorry, I'll leave this open because we don't seem to have another issue for it, although I've seen other reports of it. @nasfarley88 you can unsubscribe from notifications for this issue, if you wish to, using the button in the right-hand column on this page.

Extra information about nasfarley88's account and party (before removal):

```
user:
    "party": {
        "quest": {
            "RSVPNeeded": false,
            "completed": "",
            "progress": {
                "collect": {},
                "down": 0,
                "up": 2.3641520711997943
            },
            "key": null
        }
    },

party:
    "quest": null,
```

There's another user in the Newbies guild now with this complaint and their party also has `"quest": null,` so I'm adjusting that value for the party to this to see if it helps:

```
    "quest": {
        "leader": "",
        "members": { },
        "key": "",
        "progress": { "collect": {} },
        "active": false
    },
```

**Comment by Fabalian** [comment]
I have been experiencing difficulties leaving my party and the Newbies Guild recommended I contact you this way. I have tried to leave the party by clicking the red “leave party” button on the party page, but nothing happened (you see a think blue bar load from left to right, at the top of the browser page but then the same party page appears again). 

My party is doing a quest at the moment but I’m not part of the quest. I am taking part in challenges but my party does not have any party-challenges going. 

The Newbies Guild suggested I clear my browser’s cookies and go to Habitica’s Clear Browser Data page and click the button there (https://habitica.com/static/clear-browser-data). I did this with both my browsers, Google Chrome and Microsoft Edge. Afterwards when I have tried to leave the party, still nothing happens in Google Chrome. In Microsoft Edge I will click “leave party” and for about 3 seconds I will see the page “invite friends to a party” before the page reloads to my party which I’m trying to leave.

I have tried clearing Habitica’s and the browsers’ data several times, I’ve tried leaving the party several times over a couple of days and on different laptops with different internet connections. Nothing seems to work. 

Information which might be useful:
My OS is Windows 10
Browsers: Google Chrome Version 47.0.2526.106 m, Microsoft Edge
User ID: c89a8a06-3766-49bf-aa42-8339e88c264f
party's Group ID: 6e86cd55-3aec-449b-a2ea-e3c302711532

I'm not a techy person at all, the screenshot above mean nothing to me, but I'll try to provide you with anything you need to help me sort this :) THANKS

**Comment by Alys** [comment]
@Fabalian Excellent bug report! Very thorough - thank you! I'm sorry it's been so much trouble for you.

Could you please try one more thing? On Google Chrome, please go to View > Developer > JavaScript Console, which should open a small sub-window at the bottom of the Habitica site. Then reload that page, and tell us what appears in the Console. You can either copy and paste all the text or take a screenshot. The top of the Console can be dragged upwards to make it larger if necessary.

**Comment by Fabalian** [comment]
Thanks Alys, 

I could not find View - Developer - Java Scipt, what I've done instead is Settings - More Tools - Developer Tools, I hope that's the window you mean. 

Here is the first screenshot with the developer tool open whilst reloading the Habitica Task page:
![image](https://cloud.githubusercontent.com/assets/16738401/12375238/0f0407cc-bcb1-11e5-802b-adcbf725de1e.png)

Here is another screenshot from what happens when I click the "leave party" button:
![image](https://cloud.githubusercontent.com/assets/16738401/12375235/df8ef1aa-bcb0-11e5-99bb-86203d7c7c0a.png)

**Comment by Alys** [comment]
@Fabalian Sorry about that - I'd forgotten that it's not in the same menu position. My bad. :( You can get to the correct place by clicking "Console" at the top of that sub-window (in between Elements and Sources, near the left). Reload to clear out old information from it then click "leave" and show us what appears.

**Comment by Fabalian** [comment]
thanks and sorry about the confusion!

Here is a pic after I hit reload whilst viewing the task page:
![image](https://cloud.githubusercontent.com/assets/16738401/12375275/96289e1a-bcb2-11e5-9ea7-bf291f494915.png)

Here is a pic after I click the "leave group" button:
![image](https://cloud.githubusercontent.com/assets/16738401/12375279/acd6e414-bcb2-11e5-9eb6-3d0942cad38a.png)

...the mystery continues :D

**Comment by Alys** [comment]
@Fabalian Don't be sorry - I gave you bad instructions! 

That second screenshot contains interesting information for us: 
_TypeError: Cannot read property '_id' of null_

Just to confirm - you never see the popup confirmation link when you click on the leave button? Not in any browser?

**Comment by Fabalian** [comment]
nope

**Comment by Alys** [comment]
@paglias @crookedneighbor @SabreCat :
For Fabalian's case, I can't see anything wrong in the user or group data related to the party. Do you want to look into this or get Fabalian to give you any other information? If not, I'll remove Fabalian from their party manually.

**Comment by paglias** [comment]
@Alys I'd say the only thing @Fabalian can try if they didn't already is to logout. Otherwise just remove them from the party manually

**Comment by Fabalian** [comment]
@Alys & @paglias  I've logged in and out several times during the "clearing HAbitica  data" process and when trying different browsers - I've just tried logging in and out again and what I get in Google Chrome is the "invite your friends to a party" page for about 3 seconds before going back to the party page - so far this has only happened in Micorsoft Edge, not Chrome.

**Comment by Alys** [comment]
@Fabalian I've removed you from the party. Please reload the site and tell me if it hasn't worked.

@paglias I saved a copy of all relevant information from the database in case it helps us investigate this further. Do you have any idea what `TypeError: Cannot read property '_id' of null` might have been referring to?

**Comment by paglias** [comment]
@Alys I fear I do not know, every model has an _id field and without source maps it's impossible to see where the error originated. It's strange though because I don't think mongo ever save something without an id which makes me think of a client side only error

**Comment by Fabalian** [comment]
thank you guys! I'm out of the party woho @paglias @Alys  if you'd like me to provide you with anything else so you know what happened I'm very happy to :)

**Comment by Hydraaa** [comment]
I seem to be having the same problem, can't leave party after "clearing Habitica data", refreshing, trying multiple browsers. In chrome (Version 47.0.2526.111 m) the console displays the same error as above after clicking leave party button: 

Screenshot:
http://puu.sh/mCP4k/09ce649a21.png

For reference:
TypeError: Cannot read property '_id' of null
    at app-cd4a7de1.js:34
    at hb (app-cd4a7de1.js:29)
    at Function.Yd (app-cd4a7de1.js:29)
    at app-cd4a7de1.js:34
    at app-cd4a7de1.js:10
    at j (app-cd4a7de1.js:7)
    at app-cd4a7de1.js:7
    at j.$eval (app-cd4a7de1.js:7)
    at j.$digest (app-cd4a7de1.js:7)
    at j.$apply (app-cd4a7de1.js:7)
(anonymous function) @ app-cd4a7de1.js:6
(anonymous function) @ app-cd4a7de1.js:6
j @ app-cd4a7de1.js:7
(anonymous function) @ app-cd4a7de1.js:7
j.$eval @ app-cd4a7de1.js:7
j.$digest @ app-cd4a7de1.js:7
j.$apply @ app-cd4a7de1.js:7
s @ app-cd4a7de1.js:6
w @ app-cd4a7de1.js:6
y @ app-cd4a7de1.js:6

My User ID: 4e56413c-e2e6-4de3-b4bb-393bcfac7f14
My Group ID: 3908c727-60d1-4453-a545-463b431a7d86
OS: Windows 7 Ultimate

**Comment by Alys** [comment]
@Hydraaa  I've removed you from the party. Please reload the site and tell me if it hasn't worked.

**Comment by Hydraaa** [comment]
It worked, thanks a bunch!

I hope what I posted was helpful, as well. Lemme know if you need any more info.

**Comment by redopus** [comment]
I have the same problem with @Fabalian and @Hydraaa .
I can't leave the party. I've tried different computers and cleared Habitica Data but the leave button stlii doesn't work. My party is doing a quest now but I'm not taking part in it.
I also tried the Developer Tools and the result is similar to Fabalian's. 

My OS is Windows 7 Professional
My User ID is 4a6e7272-a4c6-46b8-b43b-1e91474f5973
Group ID is e03753c8-8a2e-4d8b-a891-c78f6b7cbb3f

Could you please remove me from my party if the problem would be hard to solve in a short time? Thanks a lot!

**Comment by Alys** [comment]
@redopus I've removed you from the party.

**Comment by redopus** [comment]
@Alys Thank you so much! And I'd like to provide anything helpful if you need.

**Comment by Alys** [comment]
Another instance of this was reported in https://github.com/HabitRPG/habitrpg/issues/7006

UUID: 2ebb7eab-6306-4055-af27-db70b4b36bad
GID: 1ea8c09b-8a24-44bd-98f4-bdc5e92f8707

```
app-c16ee834.js:6 TypeError: Cannot read property '_id' of null
      at app-c16ee834.js:36
      etc
```

**Comment by maiatoday** [comment]
Argh sorry I can't leave the party either.

Ubuntu 14.04 Chrome and firefox. 
uuid=c34cbae3-a66f-4211-884f-0c90d48d71fc
Group ID=fc2ac851-37d0-4f10-991c-1458952e453c

Also no confirmation dialog.

app-19b22806.js:6 TypeError: Cannot read property '_id' of null
    at app-19b22806.js:36
    at hb (app-19b22806.js:31)
    at Function.Yd (app-19b22806.js:31)
    at app-19b22806.js:36
    at app-19b22806.js:10
    at j (app-19b22806.js:7)
    at app-19b22806.js:7
    at j.$eval (app-19b22806.js:7)
    at j.$digest (app-19b22806.js:7)
    at j.$apply (app-19b22806.js:7)

**Comment by maiatoday** [comment]
I have another small piece of the puzzle, maybe it helps...

I had accepted a pending quest when I tried to leave.

**Comment by Alys** [comment]
@maiatoday Thanks for all of those details! There's no quest at the moment, in either the party or your user account, so it looks like that quest has been cancelled. Do you recall if you tried to leave the party after it was cancelled or before?

Could you please try leaving again now? If it doesn't work this time, I'll delete your from the party myself.

**Comment by Rhynn** [comment]
Now here's an interesting one. This involves both me and a friend. The friend involved is MonstrHugger.

We both signed up today, and we're trying to form a party with me as the leader.

I started creating a party through the 'Battle Monsters with Friends' button. After sending the invite, I looked around at a quest to start - the 'Basi-List' quest was the only available so I wanted to start it, but it told me to invite a friend to a party to start it.
I canceled the invite to her, which also seemed to delete the party as a whole, and started the party anew through the quest item.

However, while I was doing that, she apparently accepted the invite and got put into the party. So now we have the situation where I'm in the newest party with the quest active, and a pending invite to her.
But she's in the other party, and she's unable to leave it. She gets the error "group not found or you dont have access". In other words, she's in a party which doesn't exist, and can't leave it because it doesn't exist, but can't join a new party because she's in another party... which doesn't exist.

Clearing cache, cookies etc. has not had any effect.

**Comment by maiatoday** [comment]
@Alys I was part of a quest when I first tried to cancel. I thought I couldn't leave because of the quest. Then the quest starter cancelled the quest. I still couldn't leave the party after. It is as if it broke something when I tried to leave the party while being in quest accepted state. Then after it didn't matter what I did the backend was in a broken state.

I just tried leaving and I still did not get the confirmation dialog. It reports the same error in the console.

**Comment by Alys** [comment]
@maiatoday Thanks for that, and I'm sorry for the trouble! I've removed you from the party. Please reload the site and tell me if there's still problems.

---

@Rhynn Yes, that is interesting. Although clearly annoying for both of you. :(  It sounds like there might be something odd in the "Battle Monsters with Friends" process, which we'll look into. Thank you for all those details! They will help us.
Assuming your friend's profile name is exactly "MonstrHugger", her account is 5c57cb4a-ab3b-4f7a-96c5-794d5c4b8862, and she isn't currently in a party. She does have an invitation to your new party. 

If she's still getting errors, it's possible she's affected by this bug: https://github.com/HabitRPG/habitrpg/issues/5649 . Unfortunately that's something that's happening entirely within her browser so we can't fix anything on the server to help. :( There's a series of steps to follow in the top post of that bug report, which are a bit laborious but which might work. If she goes through them and still has problems, please tell us!

**Comment by maiatoday** [comment]
@Alys All working again thank you.

**Comment by mael2** [comment]
same issue here
@Alys can you remove me from my party please?

UUID 6c470c1d-5238-4af7-84b8-da5f95b2fb11
Group ID: 190d313c-f286-4c08-8b5c-f07c1226613d

thanks!

**Comment by Alys** [comment]
@mael2 That should be done now. Please reload the website or refresh the app (or you might need to log out of the app) and tell me if anything doesn't look right.

**Comment by mael2** [comment]
thanks for the fast response, i'm no longer in the party

**Comment by abejr** [comment]
@Alys I was able to leave party, but now it seems that habitica is trying to find my old party. When I try to create a new party or invite a friend to a new party, or event go to the party page I get the following:

https://habitica.com/api/v3/groups/party?userV=513 -> returns 404

Response:
{success: false, error: "NotFound", message: "Group not found."}
error:"NotFound"
message:"Group not found."
success:false

Can you help me?
P.S.: Same ocurred for my friend who was in the party

**Comment by Alys** [comment]
@abejr Sorry about that. :( You can ignore that Group not found message. We'll get rid of it. 

I'm closing this issue because these problems with leaving parties occurred under Habitica's new code. If similar problems still exist, they'll have a new cause, so we'll open a new issue for them.

**Comment by abejr** [comment]
@Alys I'm afraid I can't just ignore the message because I'm not able to create a new party or join one, it keeps telling me I'm already in a party, try refreshing.

Sorry for insisting.

**Comment by Alys** [comment]
@abejr No, you're absolutely right to insist. I'm so sorry - I read your message far too fast and missed the kind of error it was. This one we definitely do need to fix for you. 

Could you please tell me your user ID? On the website, go to [Settings -> API](https://habitrpg.com/#/options/settings/api) to find it (it is a long string of random characters and is not the same as your Habitica name). On the mobile apps, you can find it under Settings > Account Details.

**Comment by abejr** [comment]
@Alys No problem, my id is: 140ca18c-1f4e-4260-a6fd-d8f309dd4d3a and friend's id (He was in the same party and having the same problem) is e4826bd8-15d8-41be-ba75-897e2e17ae72

Thank you so much =D

**Comment by Alys** [comment]
@abejr I think I have that fixed up for you now. You should both be back in your original party, but it was a manual fix so I might still need to tweak something. If there are any problems at all, please do comment here! Thank you for your patience and for being so polite about my error before!

Technical details for other admins: Both players had the correct party ID in their party object, but the party didn't exist. I extracted it from the old database, made a couple of changes for the new schema, and inserted it.

**Comment by abejr** [comment]
@Alys Thank you, it's working
