### ISSUE TITLE
Refreshing constantly

### ISSUE THREAD

**Issue by leahsmiles** [HabitRPG/habitica#628]
Hello,
For the past two days when I try to open habitrpg it keeps refreshing constantly. The starting "tour" message pops up, and then a few seconds later it keeps refreshing. I've tried using internet explorer and the latest firefox, and this issue is happening on both of them. I'm using Windows 7. Really want to get back to using this app.

**Comment by lefnire** [comment]
note-to-self, see multiple subscriptions and (partySubscribe) and see if SLaks racer#master commit fixes this

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
