### ISSUE TITLE
Avatar's eyes are closed in modals while in the Inn

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#6282]
If you're checked in to the Inn, the various modals for congratulations and social media sharing show the closed-eyes version of the avatar:

![image](https://cloud.githubusercontent.com/assets/4501321/11347080/7b713d22-91e5-11e5-957d-3e483daa1d02.png)

There's a parameter when displaying `generatedAvatar` to force the avatar's eyes closed regardless of Inn status, for the purposes of the "knocked out" look in the 0 Health modal, but it might be valuable to also manage the opposite (always show open eyes). Perhaps `null` for the parameter shows the avatar in whatever their current state actually is, while `true` and `false` force open/closed.

**Comment by abatula** [comment]
If no one has started on this, I can take a look at it.

**Comment by crookedneighbor** [comment]
:+1:
