### ISSUE TITLE
503 (Service Unavailable)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6283]
Hello there, this is a constant error I have encountered today. If I refresh the main page this error appears before I have done anything. I'm not sure if this is the proper code to have posted as I am not accustomed to this happening. Let me know if there is anything else I can add. 

![503 service unavailable](https://cloud.githubusercontent.com/assets/15988730/11351047/4a0021d2-91e9-11e5-9a71-0accf48db193.jpg)

**Comment by Alys** [comment]
If this is still happening, please try using a different browser or using incognito / private mode in your current browser. If that works, then clearing local storage in your preferred browser might fix the problem.

**Comment by nelle013** [comment]
I'm getting a 503 error frequently today on Chrome. Now I can't even access the website at all.

**Comment by Alys** [comment]
This issue is now being used for tracking recent server issues: https://github.com/HabitRPG/habitrpg/issues/6700

@nelle013 When you've reported a problem, you don't need to report it again, even if you find another existing report of it. :)
