### ISSUE TITLE
Android update removed health potion

### ISSUE THREAD

**Issue by FoxDilemma** [HabitRPG/habitica#6284]
Hello,

After the most recent app update the health potion disappeared from my rewards.  The rewards tab also scrolls with a stutter.  The health potion is still available on the website.  I've tried clearing the cache and uninstalling and re-installing the app, no change.

I have a Samsung Galaxy 3, I'm running Android 4.1.2
User ID: 8a8ab479-8339-46ed-a619-88d525e2728b

**Comment by Alys** [comment]
Hi @FoxDilemma. This has been reported at https://github.com/HabitRPG/habitrpg-mobile/issues/396 so I'll close this issue. If you wish, you can subscribe to notifications for that issue in the right-hand column of that page.
