### ISSUE TITLE
No pop-up for raising Mount

### ISSUE THREAD

**Issue by maryrobinette** [HabitRPG/habitica#6288]
After the update to the site, I was getting the pop-up window when I raised a mount. Then it stopped appearing. The ticky box in Site settings "Don't show popup when raising a pet into a mount" was unchecked. 

I have tried checking it, and then unchecking it. No luck.
I've raised mounts with it checked and unchecked. 
I've reloaded the page multiple times.

And now I'm at the end of potential fixes that are in my skill set. Any ideas?

**Comment by SabreCat** [comment]
I haven't been able to reproduce this yet - I got the popup as expected when I raised a Spooky Bear just now. What mounts have you raised recently? Does the browser console show any errors?

**Comment by maryrobinette** [comment]
Thanks for trying. I've raised Pink Lion, Red Panda, Desert Lion, Blue Panda, Zombie Fox, Skeleton Panda.

No error messages on the browser console. I do get the small popup notification, but not the large one.

**Comment by SabreCat** [comment]
Aha. It looks like a recent change that made it possible to get the popup for premium and quest mounts may have messed with the popup's display when you raise one of the drop-items-only combinations. (FYI @Alys) I'll look into it!

**Comment by maryrobinette** [comment]
Thanks so much! I miss the pretty, pretty popups.

**Comment by SabreCat** [comment]
My first hypothesis, about the premium and quest mounts vs. drop mounts, was incorrect, but I'm getting closer to figuring out what's actually going on. My current supposition is that our `countTotal` thing is adding up `false` mounts as well as `true` ones, which means that nothing changes when a `false` mount turns `true`, and thus the modal doesn't fire if you're re-raising a mount that you've had in the past. @maryrobinette, have you by chance ever used the Key to the Kennels to release the mounts from your stable?

**Comment by maryrobinette** [comment]
I have used the Key to the Kennels. 

I tested this theory by saddling one of my quest pets (Golden Cheetah) to see if the popup appeared and it did. 
I also tried the Golden Lion, and the popup was absent.

**Comment by maryrobinette** [comment]
Hurrah! Thank you for fixing it. I just raised a mount and the popup appeared as expected.
