### ISSUE TITLE
Incorrect Computer Dates

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#629]
Funny story... My computer date was off by a couple of years today because I had to remove my motherboard battery.  I wasn't really paying attention to the date, and I loaded up habit.  I checked off a couple of things.  I tried to go to another web site and it told me that I had a bad date that needed to be fixed for certificates to work.  I fix my date and next time I look at habit I am dead from not doing my dailies for a couple of years.  No big deal, I restore my guy without any problem.  Only problem is that now all of my todo's and dailies are red.  I can do them and get too much xp each time or I can delete/retype them and take the HP hit.  Any other way around this?

**Comment by lefnire** [comment]
I added enough tokens to your account to do a "reroll" (bottom of the item store), that brings all the values back to 0
