### ISSUE TITLE
Data population script for mongo?

### ISSUE THREAD

**Issue by gauthamchandra** [HabitRPG/habitica#6291]
For easier testing of certain cases, we should have some sort of mongo script that gets loaded when we run the mongo shell.

For example, for #6215, a tool to generate a vast amount of dailies, habits, and todos for a specific user might be useful when testing the performance of our Angular code.

Is there something similar to this available right now or in the works? If not, I might tackle this as part of investigating #6215

**Comment by paglias** [comment]
@gauthamchandra I think we have something similar to generate users on the go for testing https://github.com/HabitRPG/habitrpg/blob/develop/test/helpers/api-integration.helper.js#L73 but it goes through the api, not directly on mongo

**Comment by gauthamchandra** [comment]
I see. I might enhance this a bit and add some dedicated generators to populate the DB using the API.

**Comment by Alys** [comment]
This would be nice to have but it's more of a feature request so I'm closing it. However if a contributor wants to work on this, please comment here and we'll reopen it.
