### ISSUE TITLE
Notifications when equipping and unequipping items lack clarity

### ISSUE THREAD

**Issue by ojeytonwilliams** [HabitRPG/habitica#6298]
When a user directly unequips an item by clicking on it on the equipment page, a message pops up saying "<%= itemText %> un-equipped".  However no message appears if the user unequips it indirectly (by equipping something that conflicts with it).

I think the messages should inform the user they've unequipped something in both cases, with an extra notification about two-handed weapons if the two-handedness matters.

I'd be happy to implement this.

**Comment by crookedneighbor** [comment]
I think it makes sense to have an un-equip notice for the offhand item when using a two handed weapon, but I don't think it's necessary to announce that you've unequipped one sword when you equip another sword. It should be obvious, and I think adding extra notifications will just add extra clutter.

**Comment by ojeytonwilliams** [comment]
How about the following, in order of precedence:

equip any weapon while having one or zero weapon(s) equipped -> no notifications
equip a two-handed weapon -> habitica tells you what (if any) off-hand item you've unequipped
equip an off-hand item -> habitica tells you what (if any) two-handed weapons you've unequipped

**Comment by crookedneighbor** [comment]
That sounds reasonable to me.
