### ISSUE TITLE
Mobile Safari (and other browsers) improvements

### ISSUE THREAD

**Issue by sigboe** [HabitRPG/habitica#63]
This will be little work, big reward. And it will give you more time to complete the native iOS App, since it will give a better experience for mobile iOS users while they wait.

Make HabitRPG iOS web app compliant.
1. Hide Safari User Interface Components (VERY IMPORTANT PLEASE)
   Add this line to the header
   meta name="apple-mobile-web-app-capable" content="yes"             (Within brackets like this < > ofcourse)
2. No mouse over for mobile browsers (this would make every mobile user happy)
   Simply if its a mobile browser, you can assume it cannot do mouse over any good. So make the edit and trash buttons visible all the time for mobile browsers. I do not know how hard this is, but I don't think its that hard.
3. Add Startup Image (Not important, but little work to make a very nice detail)
   Follow this link to look at examples to make sure its iPhone 5 compliant, i its not it will make ugly letterboxing bars on the iPhone 5, which would be much worse than not having a startup image.
   http://taylor.fausak.me/2012/09/20/iphone-5-web-app-startup-image/
4. Least Important totally personal estetic change
   Make the top bar float when scrolling down :D
   I don't know at all how to do this, but I know it is possible, and it would be very cool with this app :dancers: 
   Screenshot below

Here is a screenshot which I mocked up, it has the Hide Safari Interface tag, it has the edit and trash buttons visible since its a mobile device, and it shows example of the floating top bar.
![habitrpg-request](https://f.cloud.github.com/assets/2087930/64738/1df9e3f0-5e59-11e2-89a8-2c5c93026ef1.PNG)

**Comment by lefnire** [comment]
legit

**Comment by sigboe** [comment]
:D
Please the number 1 issue is a one liner.
I hope to see in soon.

I'd set up my own server with it, but I don't want to lose out on your updates when they happen :(
Especially the potential upcoming multiplayer features.

**Comment by lefnire** [comment]
pushing to heroku, refresh in 5-10 m & hit me up if that helped

**Comment by sigboe** [comment]
Haha, the funny part is that I looked up what heroku meant on UrbanDictionary, and they also use it as a platform :) It is not defined in their dictionary though xD

**Comment by sigboe** [comment]
Very nice! It worked.
But one sad thing, letterboxing on iPhone 5 :(
Can you see when you have time if you can take a look at the link I supplied, it said it had information to remove the letterboxing. Great step forward anyway :D

![2013-01-14 17 05 05](https://f.cloud.github.com/assets/2087930/64996/7b35eb94-5e64-11e2-9093-e488712e900b.png)

**Comment by lefnire** [comment]
How vital is it? I don't use iphone so I'm not sure if it's rending the app unusable in iphone; I have a few show-stoppers in the queue otherwise.

**Comment by sigboe** [comment]
I found some more information, I will be really greatful if you could make it work,
scroll down to "Home Screen Web Apps" and see if it is something you can add fast. If not, I'll be happy to be put in the queue :)
http://www.mobilexweb.com/blog/iphone-5-ios-6-html5-developers

**Comment by lefnire** [comment]
I think that will take me a sit-down to properly test, will get to later. should I revert my last commit until I can implement this?

**Comment by lefnire** [comment]
Also, I'm quite amenable to pull-requests ;)

**Comment by sigboe** [comment]
I vote leave it as it is!!! :D
the letterboxes only take up more vertical pixels than the safari buttons. But the iPhone 5 black level in the screen is good enough that it blends with the bezel almost completely in normal lighting conditions. ;)

Just a quick note to boot, it says in the web page:

Instead of changing all your viewports right now, the following script will make the trick changing it dynamically:
if (window.screen.height==568) { // iPhone 4"
document.querySelector("meta[name=viewport]").content="width=320.1";
}

I'd read it in context when you have the time just to be sure :)

**Comment by sigboe** [comment]
As far as I can read that JavaScript, it says, 

If the screen is that many POINTS (not pixles), activate this viewport setting.
Maybe it would require an "If its an iOS device statement too". IDK

Sitting at work while I found your app, Love it!!!!!

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.
