### ISSUE TITLE
Simple API creating duplicate habits

### ISSUE THREAD

**Issue by NotChrisPlease** [HabitRPG/habitica#630]
The simple API for habit up/down operations, has been creating duplicate habits.

For example this code

``` python
import urllib2, urllib

user_id = "User ID here"
api_token = "API token here"

url = 'https://habitrpg.com/v1/users/' + user_id + '/tasks/test/up'
headers = {"apiToken":api_token, "title":"Test"}

urllib2.urlopen(url,urllib.urlencode(headers))
```

Creates two identical habits, But if a habit with the name Test already exists it creates two more.

**Comment by switz** [comment]
Is this gone? I haven't had a second to look into it, sorry.

**Comment by NotChrisPlease** [comment]
@switz I discovered that it was just a visual problem, Everything's fine upon page refresh.
