### ISSUE TITLE
Subscription renewal

### ISSUE THREAD

**Issue by arfmach** [HabitRPG/habitica#6301]
Hello. My ID is b27cbb47-5546-430f-ae4f-8f05731780a9. I've subscribed in 2015-09-09 so there were already 3 payment transactions (2015-09-09, 2015-10-09, 2015-11-09). The last one wasn't approved by Credit Card company in the first try, but in the second one; I think the Habitica system didn't properly recognize it, since it's showing only 2 consecutive months in https://habitica.com/#/options/settings/subscription and I didn't get any Mystic Hourglass nor additional gem-cap.

**Comment by Alys** [comment]
Hi @arfmach. I'm sorry about this! I'm trying to find your payments in the website of the payment processor that you chose, but I'm not able to. It looks like you use a different email address for that than you do for your Habitica account, which is fine but I just need to know what it is. To protect your privacy, please email admin@habitica.com and state the ID for this issue, which is 6301, and tell us which email address you use to log in to the payment website. If you still have the most recent receipt email from them for your Habitica subscription, please forward that to us too.

**Comment by arfmach** [comment]
Ok, thank you. I've just forwarded the receipt email, with additional info.

**Comment by Alys** [comment]
Thanks @arfmach! I've fixed your month count, Hourglass, and gem cap. Please reload the site to see the changes, and comment here if there's any problems. We'll see your comment and keep helping even though I'm closing this now (it can be reopened if needed).

**Comment by Dumboldt** [comment]
Hi, I think my problem relates to this one : I simply didn't receive my subscription renewal's mystic hourglass. I'd be glad if you'd check this issue. My ID : e3e1c551-22ae-403a-911d-8cc05650035c

**Comment by Alys** [comment]
@Dumboldt I've given you the Hourglass and the extra 5 on your gem cap.

**Comment by Dumboldt** [comment]
Thanks a lot @Alys !
