### ISSUE TITLE
Eyepatch stuck on character after reset

### ISSUE THREAD

**Issue by MooToYouToo** [HabitRPG/habitica#6304]
A while back I reset my character and an eye patch I must have bought as a different class is now stuck on my character and not in my equipment. I cannot rebuy it, I assume because I am a healer now wheras before I might have been a warrior. It doesn't disappear when using a costume.

I noticed there were other issues with this same problem but they are all closed. For example this one #3377.

256b6828-5d68-4c10-abac-fe0b8e34f987 Using Windows 7

**Comment by Alys** [comment]
I'm afraid we can't help you without being able to identify your account. To do that we need your User ID. Can you please go to Help -> Report a Bug and see step 6 of the instructons? That will tell you how to find your User ID. It's different than your profile name.

**Comment by MooToYouToo** [comment]
Sorry, forgot. Updated with my User ID.

**Comment by Alys** [comment]
Can you sync please and tell me if it's gone or not?

**Comment by MooToYouToo** [comment]
Yep, totally gone, thank you!
