### ISSUE TITLE
quest owner hasn't logged in

### ISSUE THREAD

**Issue by valene** [HabitRPG/habitica#6308]
my USER ID : 20049d70-043b-4281-a8ce-94cc5a6c448f
our group ID :  fe5fd5df-2e36-4bc0-a591-14e05fa7c87e

We would like to request assistance in removing this quest. Wiki says this is the place to request for this kind of problem.

**Comment by Alys** [comment]
@valene I've deleted the quest information from the party and all members of the party. The quest scroll has remained with its original owner.

I'm closing this now but if there's any problems, comment here and we'll see it and keep helping you.
