### ISSUE TITLE
Cannot use Backstab to level up to LV 40

### ISSUE THREAD

**Issue by salfej** [HabitRPG/habitica#6311]
I had a lot of mana built up over the past few days and started using backstab to get some exp and money. I used backstab about 4 times just fine before I leveled up and no. 5 returned an error. It tried to give me the level 40 quest (it displayed the pop-up for it), and I tried backstabbing once more but got the same error.

![image](https://cloud.githubusercontent.com/assets/10404888/11453150/242b6478-95c5-11e5-8192-bc22329ef403.png)

![image](https://cloud.githubusercontent.com/assets/10404888/11453171/d3ebb390-95c5-11e5-9344-7f09f016a194.png)

I duplicated the tab to see what the last saved action was, and it was the 4th backstab. I used backstab once more and got the same 'drop' attribute error message. I reloaded the page yet again and used two habits to level up, and there was no error message. When I did level up, I got the level 40 quest and a Tiger egg. I don't know which item attribute 'drop' is referring to, but I'd guess it's the quest. I can use backstab just fine now that I've gone past level 40 and am not using it to roll-over from level 39 to level 40.

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/4986 "Cannot level up with skill (burst of flames, backstab) to levels 15, 30, 40, 60 (from levels 14, 29, 39, 59) -- "Error Cannot set property 'drop' of undefined" for a workaround for this problem.
