### ISSUE TITLE
Getting up and running on Habitica as a developer

### ISSUE THREAD

**Issue by NathanMaton** [HabitRPG/habitica#6316]
Hey - I'm interested in contributing to the codebase here but was wondering if there's a chat room or anywhere people working on it hang out. I've only built 1 other app in Node so would love to chat.

**Comment by Alys** [comment]
Hi @NathanMaton! Thank you - we'd love to see contributions from you! 

Our wiki's [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) page, and the pages it links to, will help you set up and use a local copy of Habitica. If you run into any problems, you can paste the install output and errors into this issue.

There's a guild called [Aspiring Coders](https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f) that we recommend all contributors join. You'd be welcome to chat and ask questions there.

I'm going to close this issue now, but we'll still see and respond to any posts you make in it!

**Comment by NathanMaton** [comment]
Thanks, just joined the guild!
