### ISSUE TITLE
Collection quests seem to use strength instead of perception

### ISSUE THREAD

**Issue by swistak** [HabitRPG/habitica#6317]
As in title, I was surprised when I found much more soap then a rouge in my party (who had more then 28 the perception), so I checked the code, and I cannot find _any_ reference to perception being used to find items instead of strength (despite tooltip indicating otherwise).

Am I missing something?

**Comment by Alys** [comment]
The code is here: https://github.com/HabitRPG/habitrpg/blob/develop/common/script/index.js#L2149
It uses Perception.

**Comment by swistak** [comment]
Thank you!
