### ISSUE TITLE
Keep getting invited to the party that I am already a part of.

### ISSUE THREAD

**Issue by Aquamandias** [HabitRPG/habitica#6318]
I am currently a member of a party but my name is in both the members box as well as the invited box. I keep getting party invites to my own party.

API: 38f7770d-a176-4e8d-a1e0-a4d16175eb25

Group ID: 64d91ada-0a7c-4ad5-9bb3-6dcab06f4d5a

I am using the Habitica webpage on chrome, my computer is running windows 10. Both are up to date.

**Comment by Alys** [comment]
Sorry about this! I've removed the invitation. However it has a tendency to come back under some circumstances. I'll watch for it a couple of times a day for the next few days and keep deleting it. If you're still seeing it a week from now, please comment here again.
