### ISSUE TITLE
All my dailies, to-dos and habits suddenly disappeared

### ISSUE THREAD

**Issue by Klint-psk** [HabitRPG/habitica#6319]
Exactly what says on the title. I was resting on the Inn since Friday, and this evening I went to check my account and... POOF, all of my dailies, to-dos and habits are gone, EXCEPT one challenge habit. My UID is: 92636bec-ca7d-4895-8d8f-7e99d7f99960
I'm using Firefox 42.0, and checking the Firebug console I can see an error:
TypeError: t.getComputedStyle(...) is null
https://secure.assets.tumblr.com/client/prod/standalone/share-button-internal/index.js?_v=e910d1eba39d4cccac48f8362e86baea
line 4, column 18981

Thank you very much in advance.

**Comment by SabreCat** [comment]
Try clicking "Clear" on your list of tags. It sounds like you might have a challenge tag selected, hiding everything but the challenge's tasks.

**Comment by Klint-psk** [comment]
Indeed, that was the problem, thank you very much. The strange thing is that I never ever selected a challenge tag :s

**Comment by SabreCat** [comment]
Glad it was as simple as that! I'll close this for now, but if you see the tag getting selected again without your clicking it at all, we can reopen for further investigation.
