### ISSUE TITLE
Grey daily still gives damage

### ISSUE THREAD

**Issue by Fancazzone** [HabitRPG/habitica#6322]
Dear developers,

I am having this problem which is affecting three of my dailies. In all three cases, they are set to repeat with a non-daily frequency: two are activated once per week and the third only once per month. 
The bug shows itself on THE DAY AFTER I complete one of these dailies. While the daily in question is grey and listed as inactive (as it should be since it not a day in which it is set to be completed), it still appears to count as active: unless I click on it again, I and my party receive the relative damage when the cron runs. The data display tool seems to confirm this analysis: if I access it, it reports the daily as uncompleted, even though it lists it as grey. If I click on the daily and complete it again, then the daily is definitively marked as completed and it does no longer give any problem until the following time it is supposed to be completed. If I do not click on it, however, the daily will again count as active on the following day. In practice, it is as if I am required to complete the daily twice in two days before it can reset correctly.
To surmise:
- The bug only affects dailies set to repeat at a non-daily interval
- It affects some, but not all, of such dailies
- For those which are affected, it presents itself constantly and consistently (i.e. every time and always at the same time)
- It always shows itself on the day after I complete the daily. It is listed as inactive, but still counts as active for the system
- If I click on the daily and complete it again, the bug disappears until the next reset
- If I do not click on the daily, the bug shows itself again on the following day.
- In all those cases, the daily always resets at the correct day (i.e. if it set to reset on Tuesday, it still resets on Tuesday, no matter whether it is bugged or not)
- Finally, something weird happened to those dailies which might be connected with this bug: hey were all originally set to activate on the day before from the one they actually reset. For example, the one I have on Tuesday (backup your data) was originally scheduled for Monday.

**Comment by Alys** [comment]
Please tell me what the start date is for the Dailies that are having trouble (you can see it under Advanced Options in each Daily's edit screen).  Do the Dailies use the "Every X Days" setting or the "On Certain Days of the Week" setting.

How are you determining that these Dailies are the ones causing you to lose health? For example, are you noticing that their streaks are reset to zero when they should not be?

Please also tell me what timezone you are in, and whether you went through a daylight savings change (in either direction) before this problem started happening.

**Comment by Fancazzone** [comment]
The first one started on 8 September 2015 and is set to repeat every 7 days.
The second one started on 25 August 2015 and it is set to repeat every 30 days.
I am not really sure about which one is the third one right now. In fact, they might be the only two.

I determined it is them because every evening, after I have completed all my dailies, I check my status via the data display tool. In the situation I described (the day after I completed one of these dailies) the tool says that I will receive x damage from 1 uncompleted daily and when I ask it to show me which one it is, I get that one (the one I completed the day before) as the culprit. If I click on it on the dashboard and reload the DDT, It then shows me correctly 0 uncompleted dailies.

I am in GMT+1 and we went through a daylight savings change on the 25th of October (clocks went one hour back). I am unable to recall if the problem started before or after this event, what I am sure is that it has been going on for some time, so it might actually have started right after daylight savings.

**Comment by Alys** [comment]
I think the problem here is that the Data Display Tool is displaying them incorrectly as being due when they are not. I've seen this before with other Dailies set to "Every X Days" but I'm not sure how to fix it.

If you aren't noticing their streaks changing incorrectly or aren't taking more damage than you should when you don't complete them, then they aren't being treated by Habitica as due when they are grey. 

Please change the Start Date for them to after 25th October and see if that fixes the problem. I think the date library that the DDT is using is throwing off the due date by one day because it's using timezone information based on the Start Date, which is no longer appropriate now that you are in a different daylight savings period.

**Comment by Fancazzone** [comment]
Ok, thanks
