### ISSUE TITLE
Lost gems for unlocking set of backgrounds?

### ISSUE THREAD

**Issue by RydiaWithASpoonyBard** [HabitRPG/habitica#6323]
d3c00a84-aa96-440e-8d39-c7cefd26681a

Browser: Chrome
OS: Windows 7

I'm not sure exactly what happened, but when I tried to unlock the SET 15 (August 2015) set, it didn't work properly.
1. I went to the backgrounds page and clicked "Unlock Set -15" next to the SET 15 (August 2015) backgrounds.
2. The page refreshed without unlocking the set.  I wasn't sure what happened there.
3. I clicked "Unlock Set - 15" again next to the Set 15 to get the backgrounds, received a pop-up and confirmed the transaction, and then it unlocked properly.

My balance beforehand was 62, and then it dropped to 32 so I'm guessing that when the page refreshed without unlocking the set I got charged again...

Is there any way to fix my gem balance to where it should be (47 gems)?

**Comment by Alys** [comment]
Sorry about this! I've given you the 15 gems that were taken incorrectly.
