### ISSUE TITLE
Bought eggs with gems, now have neither

### ISSUE THREAD

**Issue by randomfrom** [HabitRPG/habitica#6325]
I bought 7 snake eggs with my gems and now neither show up. I've restarted my browser, cleared cache and cookies, and logged out and back in. This happened once before and I just assumed it was a one time issue. Am I missing something?

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by randomfrom** [comment]
6e9b35c4-3ddf-476f-b9bf-58c4b4ab0720

**Comment by randomfrom** [comment]
Any pointers on what happened? I'm nervous to buy eggs in case I lose even more.

**Comment by Alys** [comment]
Sometimes a sync error prevents an action taking effect. Usually the full effects of the action are reversed (items bought are removed and gold or gems used to buy them are returned) but sometimes only half of it happens. I've given you seven Snake eggs. Sorry about the delay!
