### ISSUE TITLE
Quest Owner is Not Acive

### ISSUE THREAD

**Issue by joeywoneill** [HabitRPG/habitica#6326]
I'm in a party and the quest owner is inactive. The last time the quest owner logged in was on the 25th of November.
User ID: e89e54ff-45dc-4761-83bb-4fdd6e26a966

**Comment by Alys** [comment]
I've confirmed their last login date. That is too far in the past for a quest owner, especially in such a large party. 

I've cancelled the quest and returned the scroll to the owner. Your party should now be able to start a new quest.

Comment here if there's any problems. We'll see your replies and keep helping you even though I'm closing this now.
