### ISSUE TITLE
Page continuously reloads on Firefox on Windows 10

### ISSUE THREAD

**Issue by shsanders** [HabitRPG/habitica#6328]
Habitica cannot load on Firefox on Windows 10. The website continuously reloads, variables aren't being displayed, and there are Javascript errors in the console.
[Uploading habitica_error.txt…]()
![screenshot 1](https://cloud.githubusercontent.com/assets/1735838/11572899/569dbf40-99b8-11e5-9e2e-6fdd29c10bcd.png)

**Comment by Alys** [comment]
Please clear local storage in your browser. Note that that's different than clearing cache, so you might need to google for how to do it for the version of Firefox that you're running. If you can't find the right method fairly quickly, let us know.

In the meantime, you should be able to access Habitica by using incognito mode / private browsing in Firefox, or by using another browser.

**Comment by paglias** [comment]
Going to close this. Reopen if it happens again
