### ISSUE TITLE
Suggestion: Reward limits

### ISSUE THREAD

**Issue by ericwilmoth** [HabitRPG/habitica#633]
I was thinking, if the rewards had an option to set a custom daily (or perhaps weekly) limit, then above and beyond 'paying' for them, we could more easily keep track of our intention to limit such rewards to a volume we think is fair.

For example, I intend to limit myself to 6 beers a day; right now I can pay for each beer, but if i set the limit to 6 in RPG, then after that 6th beer I'd no longer be 'allowed' to 'reward' myself with more that given day.

what do you think?

**Comment by wc8** [comment]
HP loss if taken anyway or just not allowed?

You might eat that fourth cookie anyway... would it be an HP loss? or would you just not count it?

**Comment by ericwilmoth** [comment]
Glad you asked--figured that'd come up. My current approach has been doing essentially a separate, custom, higher cost penalty if I go over. If something like that could also be integrated, man that would be a great feature that would simplify staying true to intentions...or pay the price!

**Comment by wc8** [comment]
I'm getting a message the servers are down, so I'll confirm later the card took and supply a link for voting.
Here's the request as I planned it for trello: 

> The option, for each reward, to set a maximum permitted reward per day. Taking rewards beyond the maximum cost Health Point loss.
> 
> Example:
> - Eat slice of cake, maximum 3
> - Eat cookie, maximum 10
> - Watch TV episode, maximum 3
> - Drink beer, maximum 5
> - Read a book, no maximum
> 
> Original request [here](https://github.com/lefnire/habitrpg/issues/633)

**Comment by ericwilmoth** [comment]
cool--thanks!

**Comment by wc8** [comment]
[Reward Maximums](https://trello.com/c/QvNDlE9I)
