### ISSUE TITLE
Collar Icon Fix

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6336]
The Unconventional Armor collar icons were the incorrect size.

Here are the fixed files:

![conventioncollarblackicon](https://cloud.githubusercontent.com/assets/3494081/11603477/d2a10492-9a96-11e5-96f5-d34bab1f0244.png)
![conventioncollarredicon](https://cloud.githubusercontent.com/assets/3494081/11603476/d29292fe-9a96-11e5-93f2-cb7aa937a374.png)
![conventioncollaryellowicon](https://cloud.githubusercontent.com/assets/3494081/11603475/d290c0a0-9a96-11e5-9937-564862138bcc.png)

**Comment by cassidypignatello** [comment]
hey there, I can grab this one if that's all right!

**Comment by Alys** [comment]
@cassidypignatello Please do! Thank you!

**Comment by cassidypignatello** [comment]
I've replaced the icons in the wondercon folder, but when I try to run `grunt compile:sprites` it says it's not found. I was looking around the Gruntfile and didn't see that task in there either. am I missing something? thanks for any help!

**Comment by crookedneighbor** [comment]
It's been moved to gulp. You can run the sprites compilation task with `npm run sprites`

**Comment by crookedneighbor** [comment]
@cassidypignatello I've updated the readme in the common folder to reflect the new command. Sorry for the trouble.

**Comment by cassidypignatello** [comment]
@crookedneighbor oh no problem, that was super helpful. thanks so much for clarifying!

**Comment by NathanMaton** [comment]
This issue can be closed

**Comment by Alys** [comment]
Thank you. :)

A useful github tip: If you write "fixes #6477" in the title or the description, there's an automatic association between an issue and its PR, and the issue will be closed by GitHub when the PR is merged. I find putting it in the description is good because that also creates a link for people to click on.
