### ISSUE TITLE
Habit progress graph shows wrong values

### ISSUE THREAD

**Issue by lynxlynxlynx** [HabitRPG/habitica#6337]
As per https://github.com/HabitRPG/habitrpg-email-server/issues/5 , my flat-lining habits aren't showing as approaching 0, but are displayed at -1.02665731... — which is above the neutral task threshold of -1. The actual task values are fine and neutral, just the plotted points are wrong, so perhaps something is going wrong during preening.

Consider the timespan on this composite:
![mostec1](https://cloud.githubusercontent.com/assets/121515/11607332/6434da90-9b42-11e5-9304-4c376d276e1d.jpg)

**Comment by Flaffers** [comment]
My progress graphs for my To-Dos also act very weird. Here's a picture of them. 
![todos](https://cloud.githubusercontent.com/assets/6238628/16348280/84fbf64c-3a1f-11e6-86ce-9a509c353778.PNG)

The shape you see has been stuck like that for several months, even though the very height of the trapezoid (value of 40,000 or so) is shown as 5/21.

My graphs also aren't spaced normally on the x-axis. Several years will be crunched into one tick mark and then the other 30 tick marks will be the last thirty days. I don't know if that's normal or not but it's always how mine's been.
![overall](https://cloud.githubusercontent.com/assets/6238628/16348359/068d988c-3a20-11e6-907f-a85efa3669b4.PNG)

But as you see below, new habits and dailies that I create seem to act normal.
![habit](https://cloud.githubusercontent.com/assets/6238628/16348373/201f4372-3a20-11e6-9bbe-a21958f5b36d.PNG)

My user ID is cb7da19e-f7b6-4288-a9c6-3c5eec034f19

Thanks!

-Charlie

**Comment by librarianmage** [comment]
Given that the graphs are currently not existent, should this be closed?
