### ISSUE TITLE
Streak moving from negative to zero triggers false streak achievement

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#6341]
I edited a streak to -1 for a daily I wanted to set the streak to zero for when I checked it off, and it popped up that I had 84 21-day streaks. I tried a few other times, and I think it counted up a few times when I did it on the same page to different dailies, but leaving and returning to the tasklist (as well as looking in my profile) reset it to say 84, which is what my profile has read after each one.

**Comment by Alys** [comment]
We actually have a report of this already, surprisingly enough since it's a hard bug to find. :) https://github.com/HabitRPG/habitrpg/issues/2578

I'll close this one now in favour of the older one.

**Comment by citrusella** [comment]
Oops! I managed to miss that despite doing a search for my issue before posting! 0_o XD
