### ISSUE TITLE
static page to clear local storage and cookies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6344]
Several temporary bugs can be fixed by clearing local storage and cookies, but this can be hard to do for players who don't know how (especially local storage on some browsers).

The Habitica website needs a page that contains a button to clear all local storage and cookies for habitica.com. It should be a "static" page (e.g., like https://habitica.com/static/apps ) so that you don't have to log in to use it. Above the button should be text explaining what it will do.

**Comment by bkovacik** [comment]
Hi, I'm trying to create a page to do this, but the page I created isn't being included when I npm start. I assume I need to edit some file, but I'm not sure which one.

**Comment by Alys** [comment]
website/src/routes/pages.js

Useful tip: grep through the code base for the name of an existing static page, and ignore the node_modules and bower_components directories because they don't have Habitica-specific code:

`grep -rl community-guidelines * | egrep -v "node_modules/|bower_components/"`

**Comment by crookedneighbor** [comment]
If you use `git grep` it'll automatically ignore anything in the `.gitignore` file

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/commit/7df3b333f62b39212c170cf6936bcdf35bf72eeb
