### ISSUE TITLE
deleting or checking a task

### ISSUE THREAD

**Issue by merri-schwarz** [HabitRPG/habitica#6345]
i get an error when i try to check a task as done or if i try to delete a task. in the console i get:

app-5e9c75fe.js:6 TypeError: d.user.ops.score is not a function
    at j.a.score (app-5e9c75fe.js:33)
    at g (app-5e9c75fe.js:7)
    at D.|| (app-5e9c75fe.js:6)
    at f (app-5e9c75fe.js:7)
    at e (app-5e9c75fe.js:8)
    at j.$eval (app-5e9c75fe.js:7)
    at j.$apply (app-5e9c75fe.js:7)
    at HTMLAnchorElement.<anonymous> (app-5e9c75fe.js:8)
    at HTMLAnchorElement.o.event.dispatch (app-5e9c75fe.js:2)
    at HTMLAnchorElement.r.handle (app-5e9c75fe.js:2)(anonymous function) @ app-5e9c75fe.js:6(anonymous function) @ app-5e9c75fe.js:6j.$apply @ app-5e9c75fe.js:7(anonymous function) @ app-5e9c75fe.js:8o.event.dispatch @ app-5e9c75fe.js:2r.handle @ app-5e9c75fe.js:2
app-5e9c75fe.js:6 POST https://habitica.com/api/v2/user/batch-update?_v=59&data=1449496655613 503 (Service Unavailable)(anonymous function) @ app-5e9c75fe.js:6s @ app-5e9c75fe.js:6f @ app-5e9c75fe.js:6j @ app-5e9c75fe.js:7(anonymous function) @ app-5e9c75fe.js:7j.$eval @ app-5e9c75fe.js:7j.$digest @ app-5e9c75fe.js:7j.$apply @ app-5e9c75fe.js:7g @ app-5e9c75fe.js:4i @ app-5e9c75fe.js:5g @ app-5e9c75fe.js:4xa @ app-5e9c75fe.js:4wa @ app-5e9c75fe.js:4(anonymous function) @ app-5e9c75fe.js:9j @ app-5e9c75fe.js:1k.fireWith @ app-5e9c75fe.js:1o.extend.ready @ app-5e9c75fe.js:1I @ app-5e9c75fe.js:1
app-5e9c75fe.js:31 Object {data: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta …Error</p>↵      </iframe>↵    </body>↵    </html>", status: 503, config: Object, statusText: "Service Unavailable"}

tried refreshing the website, but i get the same problem. i can add tasks. it happens most of the time i try. 
using windows 7 and chrome 46.0.2490.86 m.
user ID: 931b314d-b25f-4dad-a461-eeacdadf6339

**Comment by merri-schwarz** [comment]
tried mozilla firefox and it seems to be ok so far (1 day)

**Comment by Alys** [comment]
I think this is happening in Chrome because Chrome has something corrupted saved in its local storage. Can you please log out of Habitica in Chrome, go to chrome://settings/clearBrowserData and clear data using the "Cookies and other site and plugin data" option. Then reload Habitica and try again. Please tell us if that helps or not.

**Comment by Alys** [comment]
I'm closing this, but if you still need help, please send us a reply to my message above.

**Comment by merri-schwarz** [comment]
Hey, sorry for my late answer. I was out of town for a few days/ The problem got solved after I deleted my cache. I still get the error every now and then, but then after refresh it works again. Thanks for the help.
