### ISSUE TITLE
Clicking one task checks another?

### ISSUE THREAD

**Issue by owlivion** [HabitRPG/habitica#6347]
((I couldn't find a similar enough issue to post this on so...))

Occasionally I encounter a strange glitch where I click on one task only for it to check another, mostly it seems to happen to the (almost) mirrored task of ones on the bottom half. It's infrequent enough I thought I was just misclicking at first, but then I watched today as clicking my second last task checked and unchecked the third task in the list. It behaves just like I was purposely checking it, complete with getting and losing xp/gold, even though I'm really doing another. It tends to fix itself if I refresh once or twice, but it's really bothersome and sometimes I end up in a bit of a loop where I don't even realize it's happening.

User ID: 24afac51-541a-44f0-a3c6-6758d982e36f
Windows 10; Google Chrome Version 46.0.2490.86 m

**Comment by Alys** [comment]
When this happens, if reloading doesn't fix it, please clear local storage -- go to the Chrome Settings -> Privacy -> Clear Browsing Data screen (chrome://settings/clearBrowserData ) and use the "Cookies and other site and plugin data" option.

If it persists even after clearing local storage, comment here again.
