### ISSUE TITLE
Can't leave party

### ISSUE THREAD

**Issue by kyleelynn99** [HabitRPG/habitica#6349]
Every time I leave the party that I'm in I get an Application Error, and when I refresh the page there is an invite to the same party that I just left. If I reject this party request, it just comes up again when I refresh.

Invites to new parties are not showing up.

Using Safari.

**Comment by Alys** [comment]
If it's still happening, we'll need to identify your account to see what's wrong, and also identify the party. Please go to Help -> Report a Bug from the Habitica website and see step 6 for how to find the User ID and Group ID.

**Comment by acyuta** [comment]
I can't leave group to the same group. 
![2015-12-10-194514_774x339_scrot](https://cloud.githubusercontent.com/assets/3022834/11716831/507e94ac-9f6e-11e5-99ef-bb995812bf4a.png)

**Comment by Alys** [comment]
@acyuta For the text that appears above the green button, can you please copy it into a comment here as plain text? That will let us run Google Translate over it so that we can see what it says. Also please see my previous comment for information that we need (your User ID and Group ID).

**Comment by crookedneighbor** [comment]
That's the leave your current party for a new party button.

**Comment by acyuta** [comment]
@Alys 
When i click on "Join new party" i getting the same screen, but when i click on "Decline Invitation" i getting Application Error. I registering with invitation by this group. 
![2015-12-12-094054_981x587_scrot](https://cloud.githubusercontent.com/assets/3022834/11760039/41eb27ae-a0ac-11e5-9b2c-f4e91637c261.png)

**Comment by Alys** [comment]
@acyuta Could you please go to https://habitica.com/#/options/settings/api and tell us what is written in the "User ID"  field? I think it might be "ID пользователя" in Russian.

Please do NOT tell us the "API Token" ("это пароль") because it is like a password and must stay secret.

**Comment by acyuta** [comment]
@Alys This is my user ID: cacc8f61-50cd-49ed-b1c4-f6e170f7e9cf

**Comment by Alys** [comment]
@acyuta Thanks! What's happening is that the invitation you used to join your current party keeps coming back even though you no longer need it. I've deleted the invitation, however it's likely to reappear a few times over the next few days. I'm going to keep checking twice a day and deleting it when it appears, until it's gone permanently.
