### ISSUE TITLE
I can't seem to join a challenge

### ISSUE THREAD

**Issue by amita86** [HabitRPG/habitica#6350]
Hi, there's a challenge I found in the habitica tavern which i can't join. The title is: Be extraordinarily productive. The error message that appears is:
Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.
"Error request entity too large"

**Comment by Alys** [comment]
This is a common problem with large challenges. Sometimes you're able to join if you happen to try during a less busy period, but even that doesn't always work.

We're making some large changes to our database and back-end code that should fix this problem, but it will take a while for that to be complete.

If you're still unable to join the challenge and want to be added to it, please copy the URL of the challenge and your User ID to a new comment in this issue. We'll then try to add you, although occasionally it even fails for us. :) To find your User ID, please see step 6 in the instructions at Help -> Report a Bug.

**Comment by Rmntdrawings** [comment]
I would like to be added to challenge, which url is: https://habitica.com/#/options/groups/challenges/a34025ca-7bf1-4efc-b01e-85988532e206, my used ID is 62e97649-48df-49df-bd0e-4129e6f42d45. thank you :)

**Comment by Alys** [comment]
@Rmntdrawings That challenge has been closed in the past day or two.
