### ISSUE TITLE
Vertical gray bars in task data, but user wasn't resting

### ISSUE THREAD

**Issue by dirad** [HabitRPG/habitica#6352]
im checking my data in the Data DIsplay tool.
In Dailies History, i see gaps, and the explanation notes they are "days resting at the Inn", but i was not resting....
![habit bars](https://cloud.githubusercontent.com/assets/12030851/11699645/0502cdcc-9ece-11e5-80c9-2122ee0798ed.jpg)

UPDATE:
this . . . graph . . .
![habit graph strangness](https://cloud.githubusercontent.com/assets/12030851/11699802/dd01a162-9ece-11e5-9ad5-76335d052a41.jpg)
also discovered my graph has no entry points from Nov12 till Dec1

**Comment by Alys** [comment]
Resting in the inn is just one example of what might cause those bars. The first part of that sentence is the important part: it's a gap in the record where there's no data. I'm afraid the data is gone and there's no way to get it back. It's probably due to the data merging process that happens regularly, including at the beginning of each month. Please see "Limitations on Data Stored" in the wiki's Data Export page at http://habitica.wikia.com/wiki/Data_Export

**Comment by Alys** [comment]
You're welcome to post here if you have questions. We'll see them and respond even though I've closed this.

**Comment by dirad** [comment]
sadface .

but also, why is the graph like that ..?

**Comment by Alys** [comment]
Do you mean why are there no entry points from Nov12 till Dec1? It could be because of the data averaging that happened at the start of the month. Show us that portion of the graph if you wish, and include your user id if you'd like us to investigate further.

**Comment by dirad** [comment]
what i mean is that on dec12 , on the gray highlighted graph there is a "loop"; the graph line passes dec12, and returns to it... 
Also other graphs appear somewhat odd on that day.

**Comment by Alys** [comment]
It could be just a quirk in the graphing library that we used to insert those graphs, or there might be something odd with your data on that day. I'm afraid I can't really tell from looking at the graph alone. If you'd like us to investigate, please give us your User ID -- go to Help -> Report a Bug and see step 6 for how you can find it.

**Comment by dirad** [comment]
im just a little weary about posting it -  bf308953-1ed7-4b9d-aa51-c335bc2a6556

also - how can i also br a "collaborator" ?
technically i am sure i can contribute. =]

**Comment by crookedneighbor** [comment]
@dirad http://habitica.wikia.com/wiki/Contributing_to_Habitica

**Comment by dirad** [comment]
@crookedneighbor i do mean on Github tho

**Comment by crookedneighbor** [comment]
If you have a change you'd like to make, feel free to [submit a pull request](https://help.github.com/articles/using-pull-requests/)

**Comment by Alys** [comment]
@dirad That double-back effect on the graph seems to be just something that the graphing library did. There's nothing odd in your data. The data points that the graph shows will be correct, but the line that's drawn between them will be interpolated in some way by the library. I haven't seen any other reports of this so it doesn't seem to be something that happens often. If you'd like to investigate, have a look at the source code - it shows the d3.min.js and c3.min.js libraries that are used for this. There might be something on the libraries' website that describes the problem. If you find a way of fixing it for the DDT, I'd be happy to review a pull request, and if accepted, it would count towards a contributor tier.
