### ISSUE TITLE
Missing Silly Hat after rebirth

### ISSUE THREAD

**Issue by jylyn** [HabitRPG/habitica#6353]
I rebirthed a few weeks ago and have just noticed that my Silly Hat seems to have gotten lost in transit.  I still have my Silly Robes and my full Absurd ensemble but I'm afraid of becoming a laughing stock if I wear the Absurd Hat together with the Silly Robes!

User ID: 987c6d4f-72f2-49a7-888a-e853b11eaff7

**Comment by Alys** [comment]
You are right, that would be completely unacceptable! :)  I've given you back the Hat. Please reload your equipment page if you don't see it there straight away. Comment here if it still doesn't show up! :)
