### ISSUE TITLE
Missing Equipment

### ISSUE THREAD

**Issue by BibliophileJC** [HabitRPG/habitica#6354]
API: 0ad25cfc-c53b-4985-bc0f-bf9bd5d70c89
Hi, I bought the full golden armor on my character and unlocked the armoire, but now it seems that armor is missing from my inventory, along with the gold used to purchase it. Please help!

**Comment by Alys** [comment]
Whenever you lose any gold, health, experience, or mana unfairly, you can go to Settings -> Site -> Fix Character Values to restore it. 

The behaviour you describe was just a sync error. It's unlikely to happen again if you buy the armour again.
