### ISSUE TITLE
Application Error....

### ISSUE THREAD

**Issue by mommie4life** [HabitRPG/habitica#6355]
Getting the following error. It's sometimes coming up in an error box and then all you see is Application Error, but then when I tried to reload the page the last time it gave me the following error. There doesn't seem to be anything in particular that makes it come up, but every fourth thing I touch or so it comes up. Whether changing the page, clicking a task, editing a task, etc.

"Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

**Comment by Alys** [comment]
Thanks @mommie4life ! We've restarted the server, which should fix that. Please comment here if you still notice it.
