### ISSUE TITLE
Avatar clipping in the wrong spots

### ISSUE THREAD

**Issue by Zer0t3ch** [HabitRPG/habitica#6356]
Not sure if this is the right place for this issue, but it's just something that I noticed on Habitica.com
http://i.imgur.com/V5HoHAf.png
This was noted with the "Absurd Party Robes" used as part of the costume on the "Royal Purple Gryphon" mount.

User ID: 17bbc7b9-95bf-48b1-9bab-c550c2084c0b
OS: Windows 7 Pro
Browser: Firefox 42

**Comment by pnrich** [comment]
This is actually the intended effect. Each mount is represented by 3 different .png files, only two of which are included in the generation of the avatar. The mount's body is added before anything else, then the character sprite (including armor), then the mount's head. This, I presume, is supposed to give the effect of 'riding' your mount. However, with some of the armor-mount combinations, such as the one you have here, the sprites do not mesh exceedingly well.

**Comment by Zer0t3ch** [comment]
@pnrich So is this something that needs to be changed?

**Comment by pnrich** [comment]
It may be something to refer to the designers and pixel artists, but the code is working exactly as it should.

**Comment by Zer0t3ch** [comment]
Okay, fair enough. Thanks.

**Comment by crookedneighbor** [comment]
@lemoness Please review this issue. 

![gryphon and party robes](http://i.imgur.com/V5HoHAf.png)

**Comment by lemoness** [comment]
So, we could re-layer the art for the gryphon to prevent this from happening, which I think would probably look better. I'll add it to the list of things we need on Trello.

**Comment by lemoness** [comment]
The re-layers have been completed by the talented @nonight! They're ready to be put in-game. If there's any issue with the following files, let me know. 

![mount_body_gryphon-base1xb_zpsi4kotjft](https://cloud.githubusercontent.com/assets/3494081/12409302/ba239ef2-be1d-11e5-8776-e535d765dd8b.png)
![mount_body_gryphon-base1xf_zpsdhfstxc8](https://cloud.githubusercontent.com/assets/3494081/12409304/ba280d20-be1d-11e5-941e-ef6396fb1bb0.png)
![mount_body_gryphon-red1_zpsxyptrafs](https://cloud.githubusercontent.com/assets/3494081/12409303/ba26e148-be1d-11e5-976b-4ee63b18777b.png)
![mount_body_gryphon-pink1_zpsaelj6ihh](https://cloud.githubusercontent.com/assets/3494081/12409305/ba286388-be1d-11e5-84ae-e929cba1751d.png)
![mount_body_gryphon-desert1_zpsewjzckrv](https://cloud.githubusercontent.com/assets/3494081/12409307/ba2a7b78-be1d-11e5-8b29-a1dc606f005f.png)
![mount_body_gryphon-gold1_zpsrbd2jigk](https://cloud.githubusercontent.com/assets/3494081/12409306/ba2a7d94-be1d-11e5-9e78-4e5cfb482522.png)
![mount_body_gryphon-shade1_zps33yxt9sa](https://cloud.githubusercontent.com/assets/3494081/12409308/ba3b958e-be1d-11e5-92b3-69b6d068ba52.png)
![mount_body_gryphon-white1_zpszo68oxqt](https://cloud.githubusercontent.com/assets/3494081/12409311/ba74ade2-be1d-11e5-958b-477aec5e367f.png)
![mount_body_gryphon-blue1_zpssnslnmjs](https://cloud.githubusercontent.com/assets/3494081/12409312/ba751188-be1d-11e5-98f4-82c5669ac57c.png)
![mount_body_gryphon-zombie1_zpsmnggnhkz](https://cloud.githubusercontent.com/assets/3494081/12409313/ba758f50-be1d-11e5-98d1-99c0d1a708b9.png)
![mount_head_gryphon-blue1_zpshj42gvry](https://cloud.githubusercontent.com/assets/3494081/12409309/ba72dfbc-be1d-11e5-8453-dd4f01786f5c.png)
![mount_head_gryphon-desert1_zpsvhqk93wi](https://cloud.githubusercontent.com/assets/3494081/12409310/ba748ace-be1d-11e5-97f0-64d1aeaa1690.png)
![mount_head_gryphon-pink1_zpspynanboj](https://cloud.githubusercontent.com/assets/3494081/12409314/ba81874c-be1d-11e5-92b3-809d35a73992.png)
![mount_head_gryphon-red1_zpscawzdydq](https://cloud.githubusercontent.com/assets/3494081/12409315/babd7450-be1d-11e5-8e37-b06bde9c2ead.png)
![mount_head_gryphon-gold1_zpsk25awhw3](https://cloud.githubusercontent.com/assets/3494081/12409320/babeeb14-be1d-11e5-8326-d0de383eb38c.png)
![mount_head_gryphon-white1_zpsyekeodoo](https://cloud.githubusercontent.com/assets/3494081/12409316/babdc130-be1d-11e5-9573-795fa1172733.png)
![mount_head_gryphon-shade1_zpsd2raylur](https://cloud.githubusercontent.com/assets/3494081/12409317/babe6432-be1d-11e5-836f-d87109e126dc.png)
![mount_head_gryphon-zombie1_zpsjdpu5ynj](https://cloud.githubusercontent.com/assets/3494081/12409318/babe9240-be1d-11e5-8624-97fb16a032fc.png)
![mount_body_gryphon-royal1_zps7rb8u13h](https://cloud.githubusercontent.com/assets/3494081/12409319/babea9d8-be1d-11e5-810e-5ebafc94190e.png)
![mount_head_gryphon-royal1_zpstazajnu2](https://cloud.githubusercontent.com/assets/3494081/12409321/baf27150-be1d-11e5-925b-eb7868e788cd.png)
![mount_body_gryphon-skeleton2_zpspiemdhyb](https://cloud.githubusercontent.com/assets/3494081/12409323/baf5210c-be1d-11e5-84dc-8be5ec8b564d.png)
![mount_head_gryphon-skeleton2_zpsc3viihfb](https://cloud.githubusercontent.com/assets/3494081/12409322/baf4315c-be1d-11e5-82f3-16221e339ec1.png)

**Comment by taldin** [comment]
So the solution for this one is to download these PNG files, copy them into the spritesmith directories on top of the old ones, and then grunt spritesmith, then pull, yes?

**Comment by crookedneighbor** [comment]
Yes, except that we're no longer using grunt for it. You can run the sprite task with:

```
npm run sprites
```

**Comment by taldin** [comment]
Aha, so the Wiki recording is out of date.  I'll take this one for a spin for today's blog post.
