### ISSUE TITLE
Beta Android App - "no Android key hashes configured"

### ISSUE THREAD

**Issue by jlriddell** [HabitRPG/habitica#6358]
User ID: 1edcea2f-2576-4da1-a11e-45c9104b34bc 

I attempted to login to the beta Android app using Facebook, and got an error:
"This app has no Android key hashes configured. Configure your app key hashes at http://developers.facebook.com/apps/128307497299777" [button that says OKAY]
I was then redirected to the app login.

I use a Nexus 6P and am running Android 6.0

**Comment by phillipthelen** [comment]
Hi!

This issue has been resolved. You should be able to log in with facebook now.
