### ISSUE TITLE
"Quest Invitation:  The Basi-List" Keep coming up regardless of accept/ reject/ ask later

### ISSUE THREAD

**Issue by AdamORHK** [HabitRPG/habitica#6361]
Dear all,

I encountered a bug of "Quest Invitation:  The Basi-List" Keep coming up regardless of accept/ reject/ ask later.
Anyone encountered similar situations and can offer an advice?
Your help is very appreciated.

**Comment by Alys** [comment]
Please log out of Habitica (in all browser windows that you might have open), and then clear your browser's cache, cookies, and local storage. Clearing local storage is important, and is something done differently than clearing cache and cookies, so if you don't know how to do it, google for instructions for whatever your browser is. After you've done that, close all browser windows, then reopen and try accepting or rejecting the invitation one last time (don't chose ask later).

If that doesn't help, we'll need more information. Please go to Help -> Report a Bug and give us the details requested there in step 6 and onward.

**Comment by AdamORHK** [comment]
Dear Alys,

Thank you for your kind help.
But the problem still exists...
After each time I click any of the options, it will show "Group not found or you don't have access."
then each time I come back, it will be there.

My User ID: f66cc8ad-0c1f-4a61-94cd-8187c15adf50

I think It is a "Quest Invitation: The Basi-List" from one of these Group.
Group ID: f2db2a7f-13c5-454d-b3ee-ea1f5089e601
Group ID: 5951dcf9-a006-4ab1-a58f-d252c0bcdea5

Browser: Chrome
Operating System: Windows 10

Thank you so much and I really appreciate your kind help!

**Comment by Alys** [comment]
The quest invitation was issued in a party that you used to be a member of, but aren't any longer. That's why you "Group not found or you don't have access" when you try to use the quest invitation.  

I've deleted the invitation from your account so you shouldn't see that error again.

**Comment by AdamORHK** [comment]
Thank you so much for your kind help!!!
