### ISSUE TITLE
Android beta: Filter can cause all tasks to disappear, leading to crash

### ISSUE THREAD

**Issue by skaulana** [HabitRPG/habitica#6362]
My user ID = cb953dc8-5075-4e63-9f34-a58d6949f5e0

Just taking the new app (0.0.22) for a quick spin, able to get a consistently reproing crash with Android 4.4.2 on a Samsung Galaxy Tab S:
1. Launch Habitica when already logged in (so you see your character and the Habits screen)
2. Rotate the device (either portrait -> landscape or landscape -> portrait) so the screen refreshes
3. Tap the filter icon in the corner, then tap the hardware back button
   - Notice: all tasks are gone! (should've just been a no-op)
4. Now tap the refresh icon in the corner
   - Result: crash

Here's a quick screencap of the device after step 3:

![image](https://cloud.githubusercontent.com/assets/1870844/11749031/3aab42b6-9fe0-11e5-9681-ab31c5236801.png)

**Comment by Alys** [comment]
Thanks very much for those details! I've copied your entire post to our Android repository here where we're tracking this issue: https://github.com/HabitRPG/habitrpg-android/issues/122#issuecomment-164094556
That link won't work for you at the moment, but it will in a few days when we open-source the app (the GitHub repository will then become public).

If you notice anything else related to this, please comment here! I'll copy across any other comments you make.
