### ISSUE TITLE
Bought gems, gold is gone but no gems

### ISSUE THREAD

**Issue by jnerraw** [HabitRPG/habitica#6363]
This has happened twice this week...the first time I thought maybe I'd clicked something else by accident but this time I know I didn't. I purchased two gems with gold, and my gold was taken, but Habitica is still saying I have no gems.

User ID: cc591758-bc84-4562-91d1-e2b32198646f

Windows 7, Firefox 42.0

**Comment by pipisafoat** [comment]
I've had a similar issue - in trying to purchase the peppermint hatching potion, I've spent gems but not gotten the potion. (I had 1, tried to buy 4 more, 8 gems are gone but I still only have 1 potion!) I've tried refreshing, deleting history/cookies/etc and refreshing; nothing worked. (interestingly, I had the same issue with the last magic potion!)

User ID: b2293f3a-bffb-4e01-8db3-7b6926677f36
OS 10.11.1, Chrome 47.0.2526.80 (64-bit)

**Comment by Alys** [comment]
@jnerraw Sorry about that! Whenever you lose gold or other stats unfairly, you can go to Settings -> Site -> Fix Character Values to get the gold back. Settings is the gear-shaped icon at the top right of the website. Let us know if the count of gems remaining to be bought is incorrect.

@pipisafoat I've given you back the gems. Post again here if it happens again.

**Comment by jnerraw** [comment]
Thanks Alys!
