### ISSUE TITLE
Diablo-Style 'Hardcore' Mode w/ Buybacks

### ISSUE THREAD

**Issue by Gr4ssh0pper** [HabitRPG/habitica#637]
For me in particular, keeping my character alive isn't a huge incentive or motivation. If he dies there is not much repercussion as I will just come right back to life. Going back to lvl 1 and losing gold isn't a huge deal for me. 

I'd like to propose an opt-in Hardcore mode where lives are attained through in-app purchases. If i'm spending my real hard earned money to invest in myself then I would be a lot more motivated to make sure I stay alive. Even at $1 per life I could see myself making sure to check in and record my daily stats and accomplishments to avoid death. 

That is the basic idea anyway. I think this incentive of putting my own money towards my game can open up a large horizon of other ideas as well. Maybe a kind of cumulative reward for staying alive with possibly interest making your life more valuable the longer you stay on that life. (In-game rewards are nice, but I think in the hardcore mode real money should play a bigger roll for the more serious about their Life's RPG.)

**Comment by Shaners** [comment]
Really like this idea. It's one I've suggested before and think more than a few would like to have this option available.

**Comment by wc8** [comment]
Added note to Hardcore on [Death Mechanic](https://trello.com/c/k2MWBcxl)
