### ISSUE TITLE
Gems and Gold Disappeared

### ISSUE THREAD

**Issue by Indubitably1** [HabitRPG/habitica#6371]
Hi,

Last night I had 59 gems and over 700 gold. Upon logging in today I noticed that only have 1 gem and 15 gold remaining. I didn't purchase anything with gems yesterday or today, and I don't recall using any gold.

I used the Habitica iOS app yesterday, and today I checked the website and noticed the gems and were gone. So then I opened the app and it showed 59 gems and 700+ gold, but then the screen refreshed and it showed only 1 gem and 15 gold remaining. I only used the app to access my account, not the website.

Any suggestions?

User ID: 57aef3cc-7fe3-4d34-bbb2-26260c83d616

**Comment by Alys** [comment]
I'm sorry about that, @Indubitably1! I've given you back the gems. You can restore your gold through Settings -> Site -> Fix Character Values on the website.

**Comment by Indubitably1** [comment]
Thank you!
