### ISSUE TITLE
No reward after part 1 of the Moonstone Chain.

### ISSUE THREAD

**Issue by Lalaitha** [HabitRPG/habitica#6376]
Seems like no party member got the quest rewards from the Moonstone Chain part 1 collection quest.

UUID: 7bdfa0b4-e06b-4a2f-b334-8011e9c03d95
Group ID: da883092-5ef8-4554-a390-85a5e34f3b07

**Comment by Alys** [comment]
I've given the rewards to all party members. Please get everyone to reload and check that they have them. You can all see what the rewards should be at http://habitica.wikia.com/wiki/The_Moonstone_Chain
Comment here if anyone is missing anything.

If it happens for future quests, leave a comment in this issue: https://github.com/HabitRPG/habitrpg/issues/4252
