### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#638]
As a suggestion
Could we make certain tasks nestable for easier organizing todos? I'm glad that we can finally sort again and at least they're together but it could be easier to read
Like I do bookkeeping, obviously I cannot do a reconciliation this month if last month's is not done. 
or
"I need to bake cookies for the annul bake sale, but first I need to go to the store and buy milk, eggs, and flour"

**Comment by wc8** [comment]
Would the [Checklists](https://trello.com/c/PJ1iJ413) suggestion help you?
