### ISSUE TITLE
Can't found friends

### ISSUE THREAD

**Issue by pitchou19** [HabitRPG/habitica#6382]
Hi,

I sent an invite to a friend but he were'nt invite to my party when they sign up. I try to had him after by looking for existing member but I can't add him. He can't add me either.

Can you help me with that?

Thank

Kakou Pitch

**Comment by Alys** [comment]
Tell him to post a message to the Tavern saying something like "hi pitchou19". You can then click on his name to view his profile, and then you'll see his User ID, which is a long string like 92782948-daea-47ad-be64-ac7757a8d36e. You can use that to invite him to your party. 

If he has already joined a party or created his own, he will need to click the "leave" button on the party before you can send him an invitation.

**Comment by Alys** [comment]
@pitchou19 I'm closing this, but if you are still having trouble, comment here and we'll keep helping you.
