### ISSUE TITLE
Wrong Number of Monthly Gems

### ISSUE THREAD

**Issue by selena-ariel** [HabitRPG/habitica#6385]
I just bought a 12-month subscription. (Gifted to myself, from myself. We're friends.) The trouble is as follows: The Market, where I can buy gems, says that my cap is 15 gems, which makes no sense, because my subscription page says that I'm supposed to be getting an _extra_ 20 gems above the base rate. (I haven't bought any gems yet. Just got the subscription a few minutes ago. I could've waited to see if it spontaneously adjusts itself tomorrow or something, but I have no idea how likely that scenario is.)

![wrong-gems](https://cloud.githubusercontent.com/assets/9969311/11916089/a5f90f3e-a694-11e5-82a7-45c76f603a3d.png)

And I have no idea if this is a bug or not, I don't know how subscriptions are calculated exactly, but it says my subscription is due to run out  03/11/2016, and I can't figure out how that works out either way (is that March 11, 2016  or November 3, 2016?). It seems to me that it ought to be Dec 19, 2016 - or roughly around there, but neither of those months could possibly indicate next December. 

![subscription](https://cloud.githubusercontent.com/assets/9969311/11916092/e6bb4ac8-a694-11e5-8425-42ed3b2ab838.png)

Just for the record, I have the right number of Time Traveller thingies (4). So _something_'s working, but I'm not sure what's what.

User ID: 0abfdfb6-b523-48e9-8948-92b56b5bc96a

(And yes, I tried refreshing the page, and I've tried using different browsers. No change.)

**Comment by Alys** [comment]
The incorrect end date is because there was some information left over in your account from an earlier subscription; I'll get that fixed for you. Reload in fifteen minutes and you should see the correct date.

Your monthly gem cap was increased by 20 gems, however your gems purchased from last month was being held over too, resulting in an incorrect number remaining to buy. I'll fix that as well.

Sorry about the trouble!

**Comment by Alys** [comment]
That should be all fixed now. Comment here if it's not.

**Comment by selena-ariel** [comment]
@Alys Yes! It's fixed! Thanks a million, I didn't expect it to be taken care of so quickly. All good now.

PS - Thanks for all your work on the site, it's really one of the most incredible apps I've ever come across.  The most dedicated devs :)
