### ISSUE TITLE
Weird item placement on avatar?

### ISSUE THREAD

**Issue by penguindigo** [HabitRPG/habitica#6387]
User ID: 72a0ac9c-d3b9-4a36-a3bc-14451b64c319
Mac OS X 10.11 (El Capitan)
Safari

Sorry if there's an issue already for stuff like this: I couldn't find it.  I suppose it isn't a "bug" so much as a suggestion? It's not clear.

I've recently purchased (with Gems) the "Winter-lit Staff" for my mage.  I've found that, compared to other staffs, which my avatar holds in the middle of the shaft.  Sorta looks like I'm wielding a Q-Tip.  For comparison, this is how most staffs look: 
![typical staff placement](https://cloud.githubusercontent.com/assets/16387732/11935729/6d8d3c62-a7d7-11e5-8951-b73c3384799b.png)

The Winter-Lit staff, by contrast, looks like this:
![weird staff placement](https://cloud.githubusercontent.com/assets/16387732/11935741/7d75bfd2-a7d7-11e5-9809-6f364698e1e9.png)

So, ideally, I think it'd look better, and more consistent with other staffs (staves?) to have the avatar by holding the staff in the middle.

Thanks!

**Comment by Alys** [comment]
I'm pretty sure this is by design since it's a year old now, but @lemoness might want to comment.

**Comment by lemoness** [comment]
This is intentional! It's part of the design because of the way the color schemes interact in the full outfit. However, if you don't like the way it looks after spending gems for it, let us know and we can turn it back into gems for you.
