### ISSUE TITLE
I was wondering if you exept code in python.

### ISSUE THREAD

**Issue by convon11** [HabitRPG/habitica#6389]
I was just wondering weather you except code in python?

**Comment by Alys** [comment]
I am sorry but no. For Habitica's own code, we accept only the languages already in use, which are listed in the "Technology Stack" section at the top of http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths

However if you want to make any of your own third-party tools, you'd be welcome to use Python! There's a list on the wiki of some tools that other coders have already made: http://habitica.wikia.com/wiki/App_and_Extension_Integrations

**Comment by convon11** [comment]
thank you.
