### ISSUE TITLE
Starting values stuck when reloading site

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6390]
Every time I open the site, it reloads all my information from a fixed starting point, even though it refreshes to my current stats. This started when Bailey's last notice popped up, and the load page starts with Bailey's notice every time (I always dismiss the message, to no avail). I'm stuck in a Groundhog Day of endless cron. I've included two pictures for comparison. In the first, I just opened the site. In the second, I checked off some tasks then reloaded the site. It just seems to reload from the same point every time.

![habitica bailey bug1](https://cloud.githubusercontent.com/assets/8877144/11945342/d14e97c4-a81c-11e5-94df-0538bd619151.png)

![habitica bailey bug2](https://cloud.githubusercontent.com/assets/8877144/11945346/dacdf628-a81c-11e5-92fa-468b41d2c21d.png)

**Comment by Alys** [comment]
Log out (if you can), clear cache, cookies, and local storage (that part is important - google for how to do it for your browser; it can be different than clearing cache), then try again. Alternatively (especially if you're not able to clear local storage), try using another browser or using incognito/private mode in your current browser. Does any of that help?

**Comment by ghost** [comment]
Hi Alys,
I cleared the cache and cookies, but I can’t clear local storage. The problem is still there. I can open the developer in Firefox and look at the contents of storage, but I can’t seem to do anything to alter it. I don’t know enough about coding to know what to do about that. All the help I could find was far too technical for me to understand.

**Comment by Alys** [comment]
Sorry about that! We're currently building a tool to clear local storage with a single button-click, so this will become easier soon. Did the other browser or incognito mode help?

**Comment by ghost** [comment]
I took the problem to an IT friend who told me to hit Ctrl+Shift+R. Worked perfectly (so far). I don’t know why clearing the cache didn’t work while that did. Maybe recommend that as a first fix if you come across someone else like me with limited knowledge of developing.
