### ISSUE TITLE
Subscription announcement email is missing a phrase

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitica#6391]
Got an email regarding the message received when one has been gifted a subscription: "Congratulations, [receiving user]!

[giving user] has gifted you a 3 to Habitica! Now you'll get mystery items, disabled ads, and the ability to buy gems for gold! Head over to the site to enjoy the perks. "

Habitican 3s are possibly very useful, but I think we are missing the words "-month subscription" after the 3.

**Comment by paglias** [comment]
fixed
