### ISSUE TITLE
avatar and items don't show up

### ISSUE THREAD

**Issue by birchjosh** [HabitRPG/habitica#6396]
the icons for my avatar don't show up, or any hairstyles and whathave you

**Comment by Alys** [comment]
Please try reloading the avatar customisation page. If that doesn't help, please go to Help -> Report a Bug from the Habitica website and see steps 6 and 7. We'll need the information there about your User ID and browser and OS.

**Comment by birchjosh** [comment]
I actually updated Firefox, and that fixed it

```
  From: Alys <notifications@github.com>
```

 To: HabitRPG/habitrpg habitrpg@noreply.github.com 
Cc: birchjosh birchjoshua@yahoo.com
 Sent: Tuesday, December 22, 2015 10:19 PM
 Subject: Re: [habitrpg] avatar and items don't show up (#6396)

Please try reloading the avatar customisation page. If that doesn't help, please go to Help -> Report a Bug from the Habitica website and see steps 6 and 7. We'll need the information there about your User ID and browser and OS.—
