### ISSUE TITLE
Error when subscribing with Paypal

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#6399]
Hello,

When try to use the Paypal option for my subscription, I am getting the following error:
`{"err":"Cannot read property 'start' of undefined"}`

---

_edit by admin:_
### What to do if this happens to you:

Please comment below and tell us your User ID (to find it go to Settings -> API from the Habitica website). Please also state whether the PayPal transaction appears to have gone through or not.

If you received a receipt from PayPal, please forward it to admin@habitica.com and include your User ID in that email as well.

We'll make sure that every person who tells us about this does receive the December Mystery Items, even if we're not able to get your subscription active until January (but it's unlikely that it will take that long to fix it!). We'll also make sure that if your payment has already been taken, you will get the subscriber benefits for the full period you have paid for.

**Comment by Alys** [comment]
Sorry about this! We'll get it fixed up as soon as we can. You can be assured that if you are not able to subscribe before the end of this month, we will still give you this month's Mystery Items.

**Comment by Alys** [comment]
I've added this to the top post to ensure any other users who have this problem will see it:

_edit by admin:_

### What to do if this happens to you:

Please comment below and tell us your User ID (to find it go to Settings -> API from the Habitica website). Please also state whether the PayPal transaction appears to have gone through or not.

If you received a receipt from PayPal, please forward it to admin@habitica.com and include your User ID in that email as well.

We'll make sure that every person who tells us about this does receive the December Mystery Items, even if we're not able to get your subscription active until January (but it's unlikely that it will take that long to fix it!). We'll also make sure that if your payment has already been taken, you will get the subscriber benefits for the full period you have paid for.

**Comment by TheHollidayInn** [comment]
No worries! I'll take a look and see if I can fix it :) But, don't let that stop anyone else who wants to.

**Comment by Alys** [comment]
@TheHollidayInn I think Blade and SabreCat have already worked out what's wrong. :)

**Comment by SabreCat** [comment]
Yup. We're missing an entry for the eligible dates for the most recent mystery set. Should be now through Jan 2.

**Comment by TheHollidayInn** [comment]
Sweet! Thanks :)

**Comment by ZahRey** [comment]
Would this happen when subscribing using a credit card too? I just did that and I think something went wrong. I'm still seeing the option to subscribe and gems are not available to buy for gold. I got an email from my credit card saying it had been charged but I also saw a habitica error message (though unhelpfully I didn't write down what it was, and i tried to solve the problem by signing out and in). User name: Zah_Rey

**Comment by SabreCat** [comment]
Fixed in 7a41d36834f7a59622d6c198277a25c053148f0c.

@ZahRey, yes, this would affect subscriptions made in the last few hours using any payment method. If you go ahead and email admin@habitica.com, we'll get it sorted for you!

**Comment by ZahRey** [comment]
Thanks so much! Will do.

**Comment by TheHollidayInn** [comment]
Okay, to follow up, here is my userID: 206039c6-24e4-4b9f-8a31-61cbb9aa3f66 .

Paypal shows that I have an active subscription to Habitrpg. I had two active subs (because I tried to pay twice), but I cancelled one of the subs. However, my habit account doesn't show me as subscribed.

**Comment by Alys** [comment]
@TheHollidayInn I've refunded both PayPal purchases and cancelled both PayPal profiles so that they shouldn't charge you again next month. However it would be wise to check on or after 23 January to make sure you haven't been charged.

The `purchased` object in your Habitica user account is clean so you shouldn't have any trouble creating a new subscription now. Sorry about the bother! If I'd tried to link one of those PayPal payments to your account, I'd have had to set it all up manually and there'd be a decent chance of human error. :)

**Comment by Alys** [comment]
I'm closing this since we've fixed the code that caused the bug, but if you're still having trouble, keep posting here and we'll keep helping.

**Comment by TheHollidayInn** [comment]
Sweet. Everything is working now! Thanks!

**Comment by Alys** [comment]
Thank YOU for subscribing!
