### ISSUE TITLE
Error, level 2 items

### ISSUE THREAD

**Issue by Starfevre** [HabitRPG/habitica#640]
I just reached level 2, having signed up this morning for this game and while I know I'm supposed to be able to read the hovertext when mousing over the new items from the item shop, all I get is a cross arrows symbol and no hovertext at all.  Firefox 19.0.

**Comment by Grossemite** [comment]
I have the same problem. I'm level 4.
Chrome.

**Comment by rixx** [comment]
Happened for me until yesterday or so; seems to be fixed now. (At least in Firefox/Ubuntu.)

**Comment by Tryskel** [comment]
I have the same problem for all balloons icons : it seems the size of the reactive zone is too small.
Win 7, Chrome Version 26.0.1410.64 m

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
