### ISSUE TITLE
Challenge API allows to create challenges that cannot be deleted, and seem to cause UX malfunction

### ISSUE THREAD

**Issue by HabitualPhoenix** [HabitRPG/habitica#6408]
It seems that the API allows to create guild challenges that 1) it will not be possible to delete, either through the API, or the UI; 2) will make the guild page not loadable for any of the guild's members; and 3) will make the challenges page filters malfunction for the challenge owner.

I think the problem is related to accepting values for the `id` fields in the `"todos"`, which might then lead to wrong object linking, but I might be wrong.

This is how this happened in my case, leaving me with a challenge I could see in the list of challenges I own in the UI (and, showing up as a part of the `challenge` resource collection, with an `_id` = 568065dc932b260d01abeca0), but with no UI option to delete it (and returning _"Challenge 568065dc932b260d01abeca0 not found"_  in response to any request for the `challenge/568065dc932b260d01abeca0` resource):

0. I had a challenge I owned, with multiple todos, and a party as its group. When the party was dissolved, I wanted to move the challenge to our guild instead. At that point, the UI did not allow me either to clone or to re-assign the challenge (the latter limitation being more understandable than the former). 

1. Not wanting to re-create the todos by hand, and hoping to preserve the relationship between the challenge and its former participants, I tried to use the API to update the group associated with the challenge by POSTing a `challenge` resource with a modified `"group"`. The request returned 200, but the `"group"` field changed from the guild group ID I provided, to something that didn't seem to exist (it no longer was the original party's group ID, I believe, but I might be wrong).

2. Failing to re-attach the old challenge to a new group (something, frankly, I didn't think would likely work anyway), I tried to "clone" the challenge manually, by using the API, and POSTing the JSON resource derived from the old challenge, while setting the `"_id"` to _null_, and the `"group"` to the guild's ID. Unfortunately, I forgot to change the `"id"` fields for the todos -- they were left referring to the existing todos, parts of the old challenge.

This is what my request looked like:

```
POST https://habitica.com/api/v2/challenges
{
  "_id": null,
  "name": "Don't Procrastinate!",
  "description": "Finish . . . dailies before 5 pm.",
  "leader": "8f660cd4-057b-45d9-ac72-c3fbd874e72f",
  "group": "42dbb940-46ab-45d5-a130-fdb0d4972cd3",
  "shortName": "by 5pm",
  "__v": 0,
  "prize": 1,
  "memberCount": 0,
  "members": [],
  "timestamp": "2015-12-25T22:36:35.263Z",
  "rewards": [],
  "todos": [
    {
      "text": "Finish . . . by 5pm (3)",
      "date": "2015-12-30T05:00:00.000Z",
      "challenge": {},
      "attribute": "str",
      "priority": 1,
      "value": 0,
      "tags": {},
      "notes": "",
      "dateCreated": "2015-12-27T20:58:21.291Z",
      "id": "8995dbe5-9969-46cc-8ca7-c5cac3077a4c",
      "checklist": [],
      "collapseChecklist": false,
      "completed": false,
      "type": "todo"
    },
    {
      "text": "Finish . . .  by 5pm (2)",
      . . .
      "id": "8aae2be5-129f-4ab7-b25b-db769274dbf9",
      . . .
    },
      . . .
  ],
  "dailys": [],
  "habits": [],
  "official": false
}
```

3. The request succeeded with the code 200. However, from that point on, the guild page was no longer accessible to any of the guild members (it would load only partially, with no data or action buttons), and the filters on my challenges page stopped working (all challenges were always shown, not filter option made any difference).

4. I was able to resolve the UI problems by a) quitting the guild, which solved the challenge filtering problem for me; and b) by having the guild owner to create a new guild challenge, which solved the guild page loading problem for the members. As steps (a) and (b) were carried out in that order, I am unsure whether (a) was necessary for the guild page to start working, but it was definitely not sufficient for it by itself. 

I must also mention that, at some point between 3 and 4, I deleted the old challenge -- unfortunately, I do not remember where exactly in the sequence of the events that happened.

5. I now own two challenges I cannot delete: one with the reported ID of 568065dc932b260d01abeca0, a direct result of the actions above, and another, with the reported ID of 56807cdcfc92ca4d03771c56 (possibly accidentally created while trying to get the transcript of my actions from Postman, and hitting Send an extra time -- not certain, though). Both can be seen in the UI with the Owned filter. Neither can be deleted in the UI, or through the API, as both are _"not found"_. 

(On the positive side, there is no adverse UX effects any more.)

As can be seen in the JSON above, my User ID is 8f660cd4-057b-45d9-ac72-c3fbd874e72f, and the formerly-affected guild group ID is 42dbb940-46ab-45d5-a130-fdb0d4972cd3.

**Comment by Alys** [comment]
pinging @paglias and @crookedneighbor since this is probably something we'll want to prevent the API from doing.

I'll clean up the bad challenges and anything else that might need fixing. If I find any interesting data, I'll post it here.

**Comment by paglias** [comment]
Hmm.. definitely not something we want to happen. It's going to be impossible to do something like this in API v3, for now though it seems a bit of an edge case

**Comment by Alys** [comment]
From the user document (note the use of `null` as a challenge id):

```
{
    "_id": "8f660cd4-057b-45d9-ac72-c3fbd874e72f",
    "challenges": [
        "0f16ea93-da52-44af-b923-a286c0cfd6ef",
        "7ab8ce4a-9065-4907-b07b-d23476abf373",
        "0518c907-b4ac-43cb-ada6-adec22eec41c",
        "64cb6355-03cb-4dc6-9266-1e83dd44a304",
        null,
        "6871b98c-1037-475e-98f2-3eb68bcd86cb"
    ],
```

From the group document (note the TWO challenges with `null` as a challenge id):

```
{
    "_id" : "42dbb940-46ab-45d5-a130-fdb0d4972cd3",
    "balance" : 1,
    "leader" : "4dfa573c-5174-449e-a994-d6ecd50c9c38",
    "type" : "guild",
    "name" : "Friends Of Fire Guild",
    "quest" : {
        "progress" : {
            "collect" : {
            }
        },
        "active" : false
    },
    "challenges" : [
        null,
        "a8f09ff0-49aa-4dde-b674-138116898230",
        "6871b98c-1037-475e-98f2-3eb68bcd86cb",
        null
    ],
    "challengeCount" : 4,
    "memberCount" : 4,
    "leaderOnly" : {
        "challenges" : false
    },
    "chat" : [  REDACTED ],
    "privacy" : "private",
    "invites" : [ REDACTED ],
    "members" : [ REDACTED ],
    "__v" : 14,
    "logo" : "REDACTED, not that it's bad"
}
```

`db.challenges.find({}, {'_id':1})` returns 9394 challenges with normal values for `_id` and also the two below. None have a value of null for `_id`.

```
{ "_id" : ObjectId("568065dc932b260d01abeca0") }
{ "_id" : ObjectId("56807cdcfc92ca4d03771c56") }
```

@HabitualPhoenix Don't take those "note..." comments as being directed at you in any kind of accusatory way. ;)  This is clearly something that the API shouldn't have allowed to happen. It's good of you to report this in such detail. Version 3 of the API is being developed, and it will be better, stronger, faster.

**Comment by paglias** [comment]
@Alys 

> Version 3 of the API is being developed, and it will be better, stronger, faster

sounds like a good slogan :)

**Comment by Alys** [comment]
:)

I have:
- deleted those two challenges
- removed the `null` value from the user document's challenge array
- removed the two `null` values from the group document's challenge array

That should sort out the problems listed above. @HabitualPhoenix tell us if anything is still broken. (I've seen your second email and am dealing with that now but I don't think that will affect the things you've reported here.)

**Comment by HabitualPhoenix** [comment]
@Alys Thanks a lot! I will let you know if I come across anything strange. 

On your previous comment, it would've certainly helped if I knew better what I was doing :)  I was not sure which, and if any, values needed to be given to the ID when a new resource was created. I was hoping that POSTing to the general `challenges` route would lead to a new object creation, which would then, I reasoned, replace the IDs by ones of its own choosing... So, _null_ seemed like a good idea...

**Comment by Alys** [comment]
I can understand how it seemed that way! I believe the best approach is to completely delete the `_id` key and its value from the data that you're about to import. The database will then fill one in with a value that it's happy with (the same applies to any ids anywhere in the data). You can also do the same for fields like `dateCreated`, and I think pretty much any of the others if you're happy to have the default values. I'd always put something in the `text` field though.

**Comment by Alys** [comment]
In the user document, tasks from the bad challenges have this in their data:

```
        {
            "text": "REDACTED",
            "challenge": {
                "id": null
            },
```

As @HabitualPhoenix reported by email, some of his tasks that were NOT from those challenges have this data:

```
        { 
            "text": "REDACTED",
            "challenge": {
                "broken": "TASK_DELETED"
            },
```

I'm hoping that's a once-off glitch related to the challenge weirdness, rather than a problem that might reoccur. Regardless, once API v3 is in place, this sort of thing shouldn't happen any more.

**Comment by HabitualPhoenix** [comment]
I'd add that _all_ of my own tasks (habits, dailies, and todos) had this problem. None of them were a part of any challenge at all.

In fact, only the tasks assigned to me as a part of other challenges were OK (and a couple of tasks I added after the incident).

**Comment by Alys** [comment]
Not all of your To-Dos had this problem when I investigated them. Some had `"challenge": {},` and some had a proper challenge ID in that object. I'm certain of that because I was checking the challenge objects carefully. However I was avoiding looking at the other To-Do data as much as possible, so perhaps the unaffected To-Dos were created after the challenge mishaps. 

I have worked out why non-challenge To-Dos were affected. When you leave a challenge, the code looks for all tasks that have the challenge's ID in their `challenge` object, and either deletes those tasks or marks them as no longer being part of a challenge (depending on your choice). When the challenge's ID is `null`, the code will look for all tasks that have `null` in their challenge object. And that of course means all non-challenge tasks. :)

**Comment by HabitualPhoenix** [comment]
Yes, I am pretty sure those not affected were created later. I added a couple of todos before I realized this was happening, and also recreated a few, once I did.

Your explanation about looking for a `null` ID and hitting all tasks with no challenges makes a lot of sense. I guess, the only remaining mystery is the two strange non-null `_id` values in `db.challenges`...

Almost all of my tasks are now fixed. Thank you so very much, @Alys !

**Comment by Alys** [comment]
@HabitualPhoenix _"the only remaining mystery is the two strange non-null _id values in db.challenges"_   That's a standard mongod thing: https://docs.mongodb.org/v3.0/reference/object-id/ . I believe that normally we don't see that style of ID because our own code supplies IDs in a different style first.
