### ISSUE TITLE
Difference between habits and dailies

### ISSUE THREAD

**Issue by anshbansal** [HabitRPG/habitica#6419]
Hi

I am new to Habitica. There needs to be better explanation of the difference between habits and dailies. It is really confusing.

**Comment by Alys** [comment]
As mentioned in https://github.com/HabitRPG/habitrpg/issues/6421 , Help -> Request a Feature is the best place to make feature suggestions, but first, I'm just checking: Are you using the Habitica website (habitica.com) or a mobile app? If you've only used an app so far, I recommend the website. Above each task column is a "?" icon which gives you information about each task type. Also, from the menu system, Help -> FAQ has two or three answers about tasks that might help, including the "sample tasks" entry that links to wiki pages with several examples that might clarify things for you. Other wiki pages of use might be these:
- http://habitica.wikia.com/wiki/Establishing_Your_Tasks
- http://habitica.wikia.com/wiki/Dailies
- http://habitica.wikia.com/wiki/Habits
- http://habitica.wikia.com/wiki/FAQ#Should_this_task_be_a_Habit.2C_Daily.2C_or_To-Do.3F ("Should this task be a Habit, Daily, or To-Do?" in the wiki's FAQ).

You'd also be welcome to use the Help -> Ask a Question to ask for further clarification. 

Also I'd certainly recommend making a feature request if you're finding that the help on the habitica.com website isn't sufficient or isn't easy to find!
