### ISSUE TITLE
World Adventure: Campaigns, Encounters, Build City

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#642]
After a certain level, you unlock the **ability** to use gold to **buy land and a charter to build a castle** on the [game map](https://trello.com/c/MyUoEMFg). 

Your character rules the city. His stats (intelligence, dexterity, charisma, strength), benefit city accordingly, eg. charisma gives population bonus. As settlement (house, hamlet, village, town, city) grows, ruler's title increases (eg. mayor, knight, lord, baron, earl).

Parties can build city together, with each member given a role in the city (stat bonus accordingly), or, form an alliance of member cities.

Choose where your completed task benefits go:
- **Houses/Population** increases tax revenue, resulting in gold. Gold can be used for custom rewards or for building your city.
- **Resources** (food, stone, wood, metal) supplies to build walls (defenses), houses (population), garrisons (troops)
- **Walls/Defenses** like armor, giving you defense against days you don't do as many tasks.
- **Troops** give to-dos more value and help with battles

Fail to complete daily tasks, yield to bad habits or miss due dates: city gets accordingly plundered, population decreases, troops become ill, walls/buildings suffer damage and need repair. 

Building city would make your character immune from dying, although he might be sent back in his city's hospital. Consequences would amount to damage, plunder of the city which would have to be repaired/regathered.

**Adventures**
A Player, Party or Temporary Companions (see [temporary guild quests](https://github.com/lefnire/habitrpg/issues/58#issuecomment-12947686), similar to can travel through the World Map as he/they complete tasks. Difficulty of task might increase distance one can travel.

[HabitRPG World Map](https://trello.com/c/MyUoEMFg): resource plots (mountains for stone, forests for wood, plains for farming food), non-player character cities for raiding, neighbor player cities.

When moving through locations (#110), a chance of a quest appears, perhaps requiring travel to a different location in order to complete it. This is similar/related to the [drops](https://trello.com/c/A7rlkOlN) idea. In fact, some of the treasure hunts could be enhanced by traveling to different locations (on task completion) to find items for a dwarven ring, for example. The header changes—see [Ongoing Realtime Adventure](https://trello.com/c/edwHxp5G) #252 —based on the location on the map. 

Users near by have the **option** to be alerted to each other's presence and the option to interact based on their character stats. Example: an encounter between warriors: choose fight/spar, join (start campaign), ignore (walk by), give gift. Battle would be determined by stats. A rogue might attempt to pickpocket another rogue only to discover, because his stats & levels were low that he failed and is now missing his bow.

Two cities or two alliances might decide to fight (for the fun of the challenge). They would agree to a length of battle (3 days) and have that time to battle by completing tasks. The results would be determined by completion of habits, daily tasks, to-do items. Daily tasks would count in terms of percentage. 

_Invisibility Cloaks & Shields_: Users who want to participate in castle/city building or travel through the world map have the option of invisibility (privacy), that will shield their city or their character from other users outside their party. In this case they would be able to interact with non-player-characters, cities, and locations. 

This idea came from someone asking me about HabitRPG and the benefits of leveling up. It's a major concept with the potential to integrate a number of previous requests. I've tweaked it just a little to suit what I know of HabitRPG and other requests.

**Possible Concerns & Solutions**
_[Distracting](https://github.com/lefnire/habitrpg/issues/153#issuecomment-13227372) from Productivity_
1) It's **optional**: don't buy land, if it would be distracting
2) For RPG fans, this makes completing items on your task list inherently rewarding. All game-play is task-completion-based.
Some have requested HabitRPG be more "addictive", i.e. provide more incentive to look at and complete one's task lists. This desire spawned various suggestions (#319 other role playing premises, #252 [Ongoing Realtime Adventure](https://trello.com/c/edwHxp5G), [Mini-Games](https://trello.com/card/mini-games/50e5d3684fe3a7266b0036d6/88), [drops](https://trello.com/c/A7rlkOlN), #319 lords/city building, #70 [random challenges between users](https://trello.com/c/zQ7lwk73), etc), which to varying degrees are part of, can be incorporated into or complement this idea.
3) To not overwhelm new users: unlock option after by your or a party member's achieving a certain level. If your party member is on the map, he can help you understand it and make progress.

_#325 Normalization of Campaigns, Encounters_
1) don't worry about comparisons to other players, after all: you can **opt-out** if your would-be enemy is too strong, you never have to fight
2) Battle can take percentage of daily tasks, rather than quantity of tasks into consideration. Perhaps a charisma bonus/penalty depending on level of your opponent: (pluck reward for fighting higher level, penalty for pick on a lower level player).
3) Party contributions can help normalization
4) Have countries and allow the countries to set "laws" towards normalization; deterring faking completion. This may not be ideal because of difficulty enforcing. 
5) Provide ways for players to help each other (gifts, etc.), and bonuses for doing so.  

_Development Resources_
1) Develop this later

Thoughts?

**Comment by JellyBean22** [comment]
Love this idea!

**Comment by deilann** [comment]
This is already on Trello, yeah?
