### ISSUE TITLE
Feature request | current streak

### ISSUE THREAD

**Issue by anshbansal** [HabitRPG/habitica#6420]
Hi

It would be great if the current streak is shown for habits like many other habit apps. Streak of how many days we have been doing a particular habit consecutively. The graph is fine but it appears if we click on the button. A simple number alongwith the description would be great.

**Comment by Alys** [comment]
As mentioned in https://github.com/HabitRPG/habitrpg/issues/6421 have a look through the Help -> Request a Feature card, and then the card you want to comment on might be one of these: https://trello.com/c/wYKm5cS5/98-reports-statistics-history-log-enhanced-graphs-meta-data or https://trello.com/c/1d1BqCM1/144-mastered-habits-dailies or https://trello.com/c/cwQvDQI9/208-habits-v2-expected-habit-frequency-onlies-habit-maximum-custom-habit-names (or you might find a better one in the list).
