### ISSUE TITLE
Feature request | indication of something done today or not

### ISSUE THREAD

**Issue by anshbansal** [HabitRPG/habitica#6421]
Hi

Currently habits do not show whether it was done today or not. It is a problem as I might have clicked on that today but there is no indication showing that

**Comment by Alys** [comment]
Hi @anshbansal GitHub is used primarily for reporting bugs. Feature requests are done through the Help -> Request a Feature menu item on the Habitica website. I'm closing the issues that you logged, however I'll provide tips on each about how to best request them.

For this one, you should read through the Help -> Request a Feature instructions first, but then the cards you want might be one of these: https://trello.com/c/wYKm5cS5/98-reports-statistics-history-log-enhanced-graphs-meta-data or https://trello.com/c/1d1BqCM1/144-mastered-habits-dailies or https://trello.com/c/cwQvDQI9/208-habits-v2-expected-habit-frequency-onlies-habit-maximum-custom-habit-names . There might also be other, better cards. You can pick the one that seems closest and make your suggestion there (there's no need to duplicate your request onto others). If there's actually a better card for it, we'll let you know!
