### ISSUE TITLE
Special character in the gift subscription message box causes error/blockage

### ISSUE THREAD

**Issue by PrincesseGrenadine** [HabitRPG/habitica#6422]
Hello! So, a week ago I wanted to gift my sister a subscription. 

I tried twice through the credit card process, completing the card information and everything, and it didn’t work. I got a message saying {"err":"Unexpected end of input"}, and I didn’t know if the payment had been made.

It seemed it hadn’t cause I didn’t get any message, so after a while I tried again through Paypal: it opened a page with the same message, no access to Paypal possible.

I finally had an idea of what was causing the problem and had a fourth try, again with Paypal, and it worked. It seems that all the time, what was causing the problem was a special character in the message box (I had written "Joyeux Noël de Papa & Maman"). I first thought the "ë" was the problem but I just tried again and it would seem that it actually comes from the ampersand.

So, there, I’m telling you guys. If it’s too much of a pain to fix and I’m the only old-fashioned one using ampersands, maybe a simple message warning about special characters in the message box would be enough? (If this is indeed the problem: I haven’t tried with other special characters like ; or }.)

My ID is 23c9e7d5-5f62-41fa-9b0c-80d0e759ff80 and I think I used Firefox (sure) on an Android/Samsung tablet and a Windows 8 laptop.

**Comment by Alys** [comment]
Confirmed from my account. `&` in the message causes `{"err":"Unexpected end of input"}` after clicking on the paypal button.

@PrincesseGrenadine Thank you very much for letting us know!

**Comment by PrincesseGrenadine** [comment]
@Alys you’re very welcome :)
