### ISSUE TITLE
Write Tests for Angular Payment Service

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#6429]
There are currently no tests around this file: https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/paymentServices.js

**Comment by thompsnm** [comment]
Looks like the link in the initial comment is returning a 404, is there an updated link?

**Comment by crookedneighbor** [comment]
We're going to do a total rewrite of the client code which will be fully tested, so this issue is no longer needed.
