### ISSUE TITLE
Unable to use the API from Node.js

### ISSUE THREAD

**Issue by justy** [HabitRPG/habitica#643]
Most likely a rather nooby Q, but:
1. I'm able to cURL the API with no problems at all
2. Attempting the same via https.request in node.js gives me 404's, 504's, and 302's, depending on what I try in the headers.

Here's a sample of my node code- trying to up score a task called 'test_task'.  As I say, the cURL works; I know my user and key are correct.

``` javascript
function habitUpVote() {

    console.log("Habit UpVote");

    var str_res = "";
    var str_body = "{'apiToken':'working_api'}"; 

    var options = {
      hostname: 'habitrpg.com',
      port: 443,
      path: '/v1/user/working_user/tasks/test_task/up',
      method: 'POST',
      headers: {
        'content-type' : 'application/json',
        'content-length' : str_body.length
      }
    };

    var req = https.request(options, function(res) {
      console.log("statusCode: ", res.statusCode);

      res.on('data', function(d) {
          console.log("data!");
          str_res+= d;
      });
    });

    req.write(str_body);
    req.end();

    req.on('error', function(e) {
      console.error(e);
    });


}
```

**Comment by switz** [comment]
Hm, not entirely sure what the issue is. Regardless, I'd suggest using a wrapper over the request module. Something like requestjs or superagent. I'm currently using superagent in the tests so I can assure that it works. You can see how I use superagent here: https://github.com/lefnire/habitrpg/blob/master/test/api.mocha.coffee

**Comment by justy** [comment]
I'll admit my enquiry was more of the form "Help I'm stuck" rather than an issue with habitrpg, so thanks very much for the advice.

**Comment by switz** [comment]
Cool, please reopen this if you have any issues.
