### ISSUE TITLE
String 'mysterySet201512' not found in Time Travelers

### ISSUE THREAD

**Issue by tcrwt** [HabitRPG/habitica#6433]
There's a string not found in Time Travelers. See image:

![image](https://cloud.githubusercontent.com/assets/6892123/12063965/89dab63a-afaf-11e5-9779-c9d60ac8aae2.png)

Using Chrome on Windows 10
My User ID: 5a86b405-e61b-4ba2-91fd-48fe99bce2ed

**Comment by Alys** [comment]
Thanks very much for letting us know! The fix for this will appear on the website soon.
