### ISSUE TITLE
Quest Accept/Decline buttons don't show up, Firefox

### ISSUE THREAD

**Issue by d6felix** [HabitRPG/habitica#6435]
Windows 7, Firefox 43.0.3, Quest Invitation: Attack of the Mundane, Part 1: Dish Disaster!
In party window i can see pending for new quest, but buttons don't show. Everything works in Internet Explorer.
User ID: e60a6155-25ca-4273-911c-51942ee40bf2
Group ID: b1b47025-a1d7-4f79-99be-4c6c3dc94bd9

**Comment by Alys** [comment]
@d6felix Sorry about this! 

Could you please show us a screenshot of what it looks like in Firefox?

**Comment by d6felix** [comment]
Quest alredy begun. Once we start another - i post screenshot, if bug occurs again.

**Comment by crookedneighbor** [comment]
Just tried it in Firefox and the buttons are there. Going to close this issue now, but if the bug occurs again, please re-open it with a screenshot.
