### ISSUE TITLE
503 Service Unavailable error using batch-update.

### ISSUE THREAD

**Issue by jclevine** [HabitRPG/habitica#6437]
This just seemed to start happening literally within the last 30 minutes. I tried refreshing multiple times to no avail. Just before this started happening, I sold a bunch of eggs/potions in succession (hence the batch, I assume).

Attached is the webpage error as well as much of a traceback as I could fit into a screenshot (I didn't have logging enabled at the time).

![habitica_app_error](https://cloud.githubusercontent.com/assets/134599/12067664/e4db7d82-afcb-11e5-867d-d01503f4fd4b.png)
![habitica_app_error_console](https://cloud.githubusercontent.com/assets/134599/12067665/e4dcb35a-afcb-11e5-83c0-41c5a73fc6c4.png)

**Comment by ghost** [comment]
I'm seeing the same thing.
![habitica page errors](https://cloud.githubusercontent.com/assets/16504228/12067713/be9050a2-afcc-11e5-9f42-3b2044b05cf1.png)

**Comment by crookedneighbor** [comment]
I've restarted the app. Should be fine now.
