### ISSUE TITLE
Challenge task for completed/removed challenge can't be removed?

### ISSUE THREAD

**Issue by megbkwyrm** [HabitRPG/habitica#6439]
I can't get rid of a challenge task ("mail it") for a long ago challenge. There's no trash can button on the task, and the challenge is no longer showing up anywhere. Is this just me being an idiot, or a bug? (User id: 8e140422-dfc5-4173-adaf-c9d1948866ef )

**Comment by Alys** [comment]
@megbkwyrm Please see this issue for the fix (in bold near the top of the issue): https://github.com/HabitRPG/habitrpg/issues/2763

**Comment by megbkwyrm** [comment]
Thank you! Sorry I couldn't find that topic on my own. I did look around a bit before asking, but apparently not long enough!

**Comment by Alys** [comment]
No worries. :) There are a lot of topics to look through!
