### ISSUE TITLE
Inviting to party gives error "User already in a party or pending invitation"

### ISSUE THREAD

**Issue by Gooseus** [HabitRPG/habitica#644]
He says he hasn't gotten an invite and I don't think anyone in the party has invited him.  What information do you need?   Should I post his id here?

**Comment by lefnire** [comment]
he might have created a party of his own? current setup is you create "named parties" (maybe not the best approach, subject to change). If you created one, you then belong to it - even if nobody's in it. If he opens the "Party" dialog (user -> party), does he see a Leave button?

**Comment by Gooseus** [comment]
He just joined, so I don't think he had access to parties.  I just looped
him in here so he can confirm that

**Comment by Gooseus** [comment]
Hi Tyler,

It wasn't that. I don't even know how to create a party, and I can't seem
to find the "User" section. I'm currently a Level 2.

There is a "1" next to my user name in the top-right, but nothing happens
when I click it. Does clicking on the user name supposed to open a menu?

Cheers,
Evan

**Comment by lefnire** [comment]
Click the arrow next to the user name:
http://gyazo.com/00c0584948197b455bb6ed0ff42ece6e

**Comment by Gooseus** [comment]
Hey Tyler,

I actually saw somewhere that there is a limit to the party system?  You
can only have 5 people in a party at the same time?  If that is true, that
could be an issue, though then I suppose the bug would be in the error
notification.  Let me know if you think this is the case

**Comment by lefnire** [comment]
The limit has yet to be implemented, so you can have as many people in a party as you want at present. Not recommended, gonna cause slow-down - but yeah.

**Comment by Gooseus** [comment]
Hmm... then I'm still unsure, do you want mine (I'm the party creator) or
Evan's user ids?  Is there anything else we can look at?

**Comment by lefnire** [comment]
yeah, [shoot me](mailto:tylerrenelle@gmail.com) your user ids and i'll see what I can do

**Comment by lefnire** [comment]
Ok @Gooseus I fixed you up, see if that works for you two. I was able to confirm this as a bug too, I'll diagnose soon.

**Comment by Gooseus** [comment]
I tried to invite him and got the same error... should he already be
invited?  I haven't been able to confirm with him yet

**Comment by lefnire** [comment]
I manually put you two in the same party in the database, is it not showing up for you?

**Comment by Gooseus** [comment]
Nope, don't see his character and don't see him listed in the party screen

**Comment by lefnire** [comment]
turns out it's a conflict of party invitations and not having parties unlocked yet, which I thought I had already solved. I'm just going to enable parties from the start, and simply notify at level 4 if they haven't started using already. sorry everyone, y'all were right all along about parties being unlocked

**Comment by lefnire** [comment]
ok, fixes to this should be coming in now in a few hours. re-open if anyone else experiences this issue

**Comment by ezekeal** [comment]
I am having this issue at the moment.

**Comment by Alys** [comment]
The message you are seeing is almost certainly accurate - the user you are trying to invite is probably already in a party. If they leave the party, then the invitation will work. If the user is CERTAIN that they are not in a party, paste their User Id here (the long string of characters that you are using to invite them).

**Comment by ezekeal** [comment]
Yeah, we had a bunch of friends just sign up and got the message for all of them, but it seem s they were able to join anyway, so the message is wrong but they are still able to join.

**Comment by Alys** [comment]
I can't replicate the error - created two new users, created party with one, invited the other, no "already in a party" message.  @ezekeal : What browser and operating system are you using? Please include the version numbers as well as the names (e.g., IE 8.2 on Windows 7 SP1).

**Comment by lefnire** [comment]
@ezekeal what's your UUID, and the UUID of the person you're inviting
