### ISSUE TITLE
A typo in the Habitica's homepage

### ISSUE THREAD

**Issue by Sepehr2016** [HabitRPG/habitica#6443]
I recently found a small typo in the Habitica's homepage. In the "Players use Habitica to manage..." section and in the "Chores" tab; at the left side of the page. The title is "Sample Dailies" but below it are habits!

**Comment by Alys** [comment]
Thanks very much @Sepehr2016 !

The same thing occurs for "Goals".

I'm fixing this now.

**Comment by Alys** [comment]
Hmmm, actually, @lemoness we should get clarification from you.

"Goals" and "Chores" both have tasks that are formatted like Habits, but the text indicates that maybe they're meant to be Dailies. For example, "20 mins of housework" is there as a plus-and-minus Habit, but the minus doesn't make much sense in that context.

Also, none of the sections currently contain Dailies that are formatted as Dailies. 

How would you like this fixed?

**Comment by Sepehr2016** [comment]
@Alys Thanks for your attention!
I agree with you that they're meant to be Dailies.
I think this issue should be fixed soon, otherwise; It may confuse people that are looking forward to join Habitica.

**Comment by lemoness** [comment]
Great catch! Both are indeed meant to be Dailies.

**Comment by Alys** [comment]
advertised in Aspiring Coders

**Comment by Sepehr2016** [comment]
Here in the Wikia guide of the game, it says that they are habits:
http://habitica.wikia.com/wiki/Sample_Habits#Housework

**Comment by Alys** [comment]
@Sepehr2016 They're okay on that wiki page because they can be implemented as Habits (e.g., if you didn't want to be punished each day for not doing them). However the minus signs didn't make sense so I've removed them. Thank you!

**Comment by NathanMaton** [comment]
I'll give this bug a shot. See upcoming PR

**Comment by librarianmage** [comment]
Can this be closed?

**Comment by Alys** [comment]
@MathWhiz Thanks!

**Comment by librarianmage** [comment]
@Alys You're welcome!
