### ISSUE TITLE
 Quest Accept/Decline buttons don't show up, Firefox

### ISSUE THREAD

**Issue by d6felix** [HabitRPG/habitica#6445]
![firefox_button_bug](https://cloud.githubusercontent.com/assets/13944504/12074150/f0647a16-b154-11e5-9d39-94b8ee3f8b6f.png)

Windows 7, Firefox 43.0.3, Quest Invitation: Attack of the Mundane, Part 1: Dish Disaster!
In party window i can see pending for new quest, but buttons don't show. Everything works in Internet Explorer.
User ID: e60a6155-25ca-4273-911c-51942ee40bf2
Group ID: b1b47025-a1d7-4f79-99be-4c6c3dc94bd9

**Comment by Alys** [comment]
@d6felix I'm so sorry! We completely missed this issue! :(  I can see that you're currently in a running quest now, so I'm closing this, but if it happens again or if you experience any other problems, please do report them. We very rarely miss bug reports like this. :(
