### ISSUE TITLE
Quest Part 2 did not drop although the UI says that it did.

### ISSUE THREAD

**Issue by lordmatt** [HabitRPG/habitica#6447]
My party and I compleated Trapper Santa (inventory_quest_scroll_evilsanta) which does not say anything about Find the cub (inventory_quest_scroll_evilsanta2) in the description. However when I went to puchase Find The Cub it insists that I should already have it.

My ID is: 96d68c04-a526-4141-b3ae-1ec7cb0d91c8

Cheers.

**Comment by Alys** [comment]
Sorry about that! That's a mistake in the text of the second quest. We'll be changing that quest to remove the text (see https://github.com/HabitRPG/habitrpg/issues/6405 ). It does need to be purchased with gems.
