### ISSUE TITLE
Find The Cub not listed as completed

### ISSUE THREAD

**Issue by cpsmartin** [HabitRPG/habitica#6449]
My party just completed the Find The Cub quest but my stats page does not show that I have completed it and I have not yet received the reward while other members in my quest have. I purchased the quest scroll and started the quest without one of the party members but on the quest invite page it showed that I had accepted the quest.

User ID: 1d59570b-6dd5-4bfd-8108-ce62507941b6
Group ID: 349ab088-36c2-4976-bc28-f5f58cf5728c

Windows 10, Google Chrome

**Comment by Alys** [comment]
Sorry about that! Sometimes a collection quest does this. I've given you the achievement and rewards. If any other party members are missing them, you or they can paste their User IDs into a new comment here. I'll see that and action it even though I'm closing this now.
