### ISSUE TITLE
Reward from Challenge won't disappear

### ISSUE THREAD

**Issue by FaerytaleInk** [HabitRPG/habitica#6450]
I have a reward from an old challenge that just never went away. I believe the challenge had something to do with filing taxes. I can't delete it, or edit it, and the challenge itself is gone along with the all the tasks, but this reward remains. 

My user id is: d9e9ed68-3c3f-4442-9ed6-4a5cc3fde66c

I'm running windows 10, but this started when I was on 7 and my browser is firefox.

Thank you!

**Comment by Alys** [comment]
We can help by deleting it but you need to tell us what the reward is. Otherwise we'll have to look through all your rewards, which isn't ideal for your privacy, and we might not be able to correctly identify it.

**Comment by FaerytaleInk** [comment]
It's "Buy yourself a nice lunch. But only once you are done with taxes." It's the only reward I have right now I believe. Thank you so much!

**Comment by Alys** [comment]
That makes it easy. :) It's gone. Sorry about the trouble!
