### ISSUE TITLE
Rescue me from my own stupidity (Tavern issue)

### ISSUE THREAD

**Issue by hlnewman** [HabitRPG/habitica#6457]
Hey all - I'm traveling and was in the Tavern. I checked out briefly to take the screenshot to go with this article - http://www.forbes.com/sites/hnewman/2015/12/31/use-your-tech-to-make-your-life-a-productive-game-new-years-revolutions-part-3/  (yay!) - and thought I put myself back into the Tavern afterward. Apparently, that was not the case. Not only did I take a huge health hit, but I slammed my questing party as well. Halp!!

My user ID is dc69a928-0231-4dc9-836a-9a21fa90e8a5. My party's group ID is 262edc67-a63c-4b57-9afa-894808c02549. My party members are Ruoh, MKay, James Douglas, Kasey and hendenk.

Could you help undo what I've done to myself and my party members as well? Bless you. :(

**Comment by crookedneighbor** [comment]
You and your party can use the "Fix Character Values" button in [Settings > Site](https://habitica.com/#/options/settings/settings) to correct any unfair damage or gold loss.
