### ISSUE TITLE
Missing Pet

### ISSUE THREAD

**Issue by burton1064** [HabitRPG/habitica#646]
I bought a zombie wolf when I reached level 3 and now my zombie wolf has run away!  Please return my zombie wolf to me!!  ~Scott

**Comment by burton1064** [comment]
hmm, I just reached level 4 and the pet option reappeared.  It's given me 4 tokens so I'll go ahead and re-buy my zombie wolf and see if he stays around this time.

**Comment by lefnire** [comment]
Looks like some data didn't persist? See [Lost Progress](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account). This working OK now though?

**Comment by burton1064** [comment]
noted, thank you
