### ISSUE TITLE
Upgrade amount of users on static page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6460]
We've hit another milestone, which means it's time to update the static page.

It should now say, "Join over a million people making it fun to achieve goals!"

:)

**Comment by Alys** [comment]
advertised in Aspiring Coders

**Comment by lemoness** [comment]
Another similar change that is needed: adding the Discover Magazine logo to
the list of press logos. Should I make a separate ticket for that, or can
it tag along with this one?

**Comment by Alys** [comment]
Tag along, to reduce review effort. :)

**Comment by NathanMaton** [comment]
how do you upload content to https://d2afqr2xdmyzvu.cloudfront.net/front/images/presslogos/ ?

**Comment by crookedneighbor** [comment]
They go in here: https://github.com/HabitRPG/habitrpg/tree/develop/website/public/front/images/presslogos

We'll upload them manually to cloudfront if your PR gets merged.

**Comment by NathanMaton** [comment]
Ok sounds good. I went ahead and fixed this locally but just saw now Sighne has a PR open. Next time I'll know. Thanks.

**Comment by crookedneighbor** [comment]
Closed with #6476
