### ISSUE TITLE
It doesn't save my recent actions

### ISSUE THREAD

**Issue by Reemeela2121** [HabitRPG/habitica#6461]
There a pop-up saying i need to refresh my browser, b/c there was an error when it came to saving any recent actions. Yet, it's a persistent problem as I continue to refresh my page- it continues to pop up! What should I do? I would like to continue using Habitica in the near future...

**Comment by Alys** [comment]
We restarted the server in the past half hour, which might have fixed the problem, but if you're still seeing that error after one more reload, go to https://habitica.com/static/clear-browser-data and click the button (read the text above it first). Tell us if it keeps happening after that.

**Comment by Alys** [comment]
I'm closing this but if you're still having trouble, comment here again.

**Comment by Reemeela2121** [comment]
Sorry, forgot to reply. It's working fine again! Thanks!
