### ISSUE TITLE
To-Do sublist won't sort correctly on Android app

### ISSUE THREAD

**Issue by rmkoske** [HabitRPG/habitica#6463]
This is my first bug report - notes for how to do better are appreciated.

I'm using the Habitica Android app, v 0.0.24.  I'm on a Samsung Galaxy S5, if it matters.

For one of my to-dos I created a list of sub-items using the android app.  

To Do "Read AofSE" has subtasks:
- Decide reading goal
- Friday
- Saturday
- Sunday
- Monday
- Tuesday
- Wednesday
- Thursday

They were entered in the order above, and appear in that order on the website, but for some reason in the android version the weekday subtasks keep resorting to this:
- Friday
- Thursday
- Wednesday
- Tuesday
- Monday
- Sunday
- Saturday

I've sorted it back into the correct order twice now on different days.  I thought it held the first time, but the second time I did it, it only held long enough for me to check one off, and then it was back in the incorrect order.  Resorting is not super-easy on the phone (it's hard to grab the task without entering text-edit mode, and the keyboard keeps getting in my way) so I didn't bother to try reordering them a third time.

(LOVE the app, by the way.  It has so much functionality!  I'm hoping to start contributing to the site with code or testing, and it's really exciting to watch the process as I try to learn how this works.)

**Comment by crookedneighbor** [comment]
I've copied your report to the android app repo: https://github.com/HabitRPG/habitrpg-android/issues/363

You can track the issue there by clicking the subscribe button.

**Comment by rmkoske** [comment]
Oops!  Thanks!
