### ISSUE TITLE
503 Service Unavailable error using batch-update.

### ISSUE THREAD

**Issue by jclevine** [HabitRPG/habitica#6467]
See [Issue 6437](https://github.com/HabitRPG/habitrpg/issues/6437). It's happening again. Can you reopen the bug?

**Comment by Alys** [comment]
@jclevine When you're aware of a bug that's happening again, the best thing is to comment on that issue in a new comment. We get notified of all comments even when they're made in closed issues.

I've been noticing a couple of errors too, so I've restarted the server, which should fix it. Comment on that issue or this one if you still have problems after a reload.
