### ISSUE TITLE
Application Error : Page could not be served

### ISSUE THREAD

**Issue by Mcatll** [HabitRPG/habitica#6469]
![applicationerror](https://cloud.githubusercontent.com/assets/16571592/12136555/05e09f14-b484-11e5-8b18-1311c9aa9143.jpg)

A red bar appears on right side of my page when I go in habitica, and after I refresh the page it is still the same. I couldn't change the language to English for you guys to see because the red bar is blocking me from clicking setting. However, the sentences in the bar said that the changes I've did might not be saved, and ask me to refresh again.

But refresh doesn't help :( 
Currently, one of the problems is I can't get rewards because it has no effect on whatever task I clicked.

Please help me :O 

MY UID: 0f5454b2-b993-4aff-9171-de8e66e36512

Browser: Google Chrome
Windows 8.1

**Comment by keysmashes** [comment]
Seems fine now. Just a thing that happens sometimes, sadly.

**Comment by Mcatll** [comment]
It is still there for me :( all-day.

**Comment by paglias** [comment]
@Mcatll @anowlcalledjosh  thanks for the report. Could you try doing the following:

If you have Chrome installed navigate to habitica.com, open the Console Ctrl(Cmd on Mac)+Alt+J and switch to the Network tab
Try completing an action on the site that should trigger the error, report here anything that appears in the Network tab, you should see a new red item which you can click

**Comment by Mcatll** [comment]
I don't get what you mean by navigate to habitica.com, but I've try to open
the page and press Ctrl+Alt+J but nothing happen :(

On Fri, Jan 8, 2016 at 12:39 AM, Matteo Pagliazzi notifications@github.com
wrote:

> @Mcatll https://github.com/Mcatll @anowlcalledjosh
> https://github.com/anowlcalledjosh thanks for the report. Could you try
> doing the following:
> 
> If you have Chrome installed navigate to habitica.com, open the Console
> Ctrl(Cmd on Mac)+Alt+J and switch to the Network tab
> Try completing an action on the site that should trigger the error, report
> here anything that appears in the Network tab, you should see a new red
> item which you can click
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6469#issuecomment-169721121.

## 

Regards, Mcat Chan

**Comment by paglias** [comment]
@Mcatll try opening https://habitica.com/static/clear-browser-data and follow the instructions there. Let me know if after that it works

**Comment by Mcatll** [comment]
: (  I've tried but I couldn't tell you the result first because I've
problem of logging in...  I used to sign up habitica with my facebook
account, but after that everytime I press logged in with facebook seems
like nothing happen. Sometimes I logged in successfully after very very
long time @@ I don't know why this happen. My network connection is
actually more than average, can you please help me? :(

On Fri, Jan 8, 2016 at 10:45 PM, Matteo Pagliazzi notifications@github.com
wrote:

> @Mcatll https://github.com/Mcatll try opening
> https://habitica.com/static/clear-browser-data and follow the
> instructions there. Let me know if after that it works
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6469#issuecomment-170021324.

## 

Regards, Mcat Chan

**Comment by paglias** [comment]
@Mcatll the page I linked you doesn't require login. Are you sure you can't open https://habitica.com/static/clear-browser-data?

**Comment by Mcatll** [comment]
I can open that page, and it leads me to homepage, but then I can't login
to my account to check whether the problem is solved.

On Fri, Jan 8, 2016 at 11:27 PM, Matteo Pagliazzi notifications@github.com
wrote:

> @Mcatll https://github.com/Mcatll the page I linked you doesn't require
> login. Are you sure you can't open
> https://habitica.com/static/clear-browser-data?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6469#issuecomment-170031216.

## 

Regards, Mcat Chan

**Comment by paglias** [comment]
@Mcatll try using a different browser, it should work. If it does manually clear cookies and localstorage from Developers Tools (Ctrl/Cmd+Alt+J -> Resources tab)

**Comment by Mcatll** [comment]
Oh yeahh! I've tried to use IE and it is work! then I do the manual clear
of cookies as you taught, and I've successfully login with no error! Thank
you!!

On Mon, Jan 11, 2016 at 1:42 AM, Matteo Pagliazzi notifications@github.com
wrote:

> @Mcatll https://github.com/Mcatll try using a different browser, it
> should work. If it does manually clear cookies and localstorage from
> Developers Tools (Ctrl/Cmd+Alt+J -> Resources tab)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6469#issuecomment-170373711.

## 

Regards, Mcat Chan
