### ISSUE TITLE
Cannot accept party invitation

### ISSUE THREAD

**Issue by joreshipley** [HabitRPG/habitica#6472]
I received an email from the Habitica team telling me that a party had invited me to join. However, the invitation isn't appearing in my notifications. I've cleared my browser cache, reloaded the page multiple times, and waited a few hours to see if it showed up. Nothing worked. Help!

**Comment by Alys** [comment]
The invitation was probably cancelled by the party leader.

If you think this mightn't have happened, we can reopen this and look into it further, but we'll need to be able to identify your account. Please go to Help -> Report a Bug and see step 6 in the instructions. You don't need to provide the group ID for this.

**Comment by joreshipley** [comment]
Hi Alys: it was a fairly large group run by a writer, so I'd be kind of surprised if I were uninvited. I'll post my ID, and I would really appreciate it if you'd check it out. Thank you!
Regards, 
Jordan S. 

Sent from Outlook Mobile

On Wed, Jan 6, 2016 at 3:19 PM -0800, "Alys" notifications@github.com wrote:

The invitation was probably cancelled by the party leader.

If you think this mightn't have happened, we can reopen this and look into it further, but we'll need to be able to identify your account. Please go to Help -> Report a Bug and see step 6 in the instructions. You don't need to provide the group ID for this.

**Comment by joreshipley** [comment]
Here is my user ID: da342808-780c-4d8b-8d3c-2e88398b9c2a.

**Comment by Alys** [comment]
You don't have any party invitations in your account. This means that the invitation either wasn't sent correctly or was revoked by the party leader after it was sent.

By the way, I am assuming that the person inviting you did so by User ID, which means that you would see a notification in Habitica, until the invitation was cancelled. However if they invited you by email address, then I'm not sure how it would work since you already have a Habitica account. I think the email address method is intended to be used for players who don't have an account yet.

What was the exact text of the email?

**Comment by joreshipley** [comment]
Hi Alys: this is copied and pasted directly from the email. Greetings, jo.re.shipley! 
blakebo would like you to join their party on Habitica! 
Together, you can keep each other accountable for your goals while battling monsters and leveling up your avatars. It doesn’t matter if you’re flossing more or finishing that big assignment – either way, you’ll be earning gold, hatching pets, and unlocking weapons! 
What are you waiting for? Come adventure at blakebo’s side! 
Stay productive, Leslie and the Habitica Team Habitica 
Follow Habitica on social media! https://twitter.com/habitica https://www.facebook.com/Habitica http://habitica.tumblr.com 

Sent from Outlook Mobile

On Wed, Jan 6, 2016 at 3:34 PM -0800, "Alys" notifications@github.com wrote:

You don't have any party invitations in your account. This means that the invitation either wasn't sent correctly or was revoked by the party leader after it was sent.

By the way, I am assuming that the person inviting you did so by User ID, which means that you would see a notification in Habitica, until the invitation was cancelled. However if they invited you by email address, then I'm not sure how it would work since you already have a Habitica account. I think the email address method is intended to be used for players who don't have an account yet.

What was the exact text of the email?

**Comment by Alys** [comment]
Thanks. That's not the email sent to players who don't have an account so you probably were invited by ID. Ask the person who did so to send a new invitation.

**Comment by joreshipley** [comment]
Okay, I'll do that. Thanks Alys!

Sent from Outlook Mobile

On Wed, Jan 6, 2016 at 3:53 PM -0800, "Alys" notifications@github.com wrote:

Thanks. That's not the email sent to players who don't have an account so you probably were invited by ID. Ask the person who did so to send a new invitation.
