### ISSUE TITLE
Inactive translators on Transifex

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6480]
Hi, I have been dealing with the issue of attracting new translators for my language, because there is already a team formed on Transifex. But the only one active there is me. Many of the translators in the team came, translated 20-30 strings, applied for the badge and then disappeared. The latest translators to join told me that they hesitated to join because there "already is such a big team". Being the only translator and reviewer for the language, I desperately need help, because I run my own company IRL and I have very limited amount of time for translating. It would really help me to cut the inactive translators, so new translators would actually feel needed and would help. What are your thoughts on cutting inactive translators? And is there even a way how to do it? Thank you in advance

**Comment by paglias** [comment]
@Miisa on this one I think we may get some input from @Alys and @lemoness 

Are you sure that possible translators feel demotivated by the number of listed translators? I though that as long as one saw that some strings missed translations they would felt encouraged to help anyway

**Comment by Alys** [comment]
My biggest concern about removing inactive translators is the time it might take for an admin to do it. It seems like it might be a labour-intensive process to (semi-)regularly review all the translators and work out which ones should be removed.

I wonder if a similar effect can be achieved by clearly stating in [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists) and/or the [Translations Trello card](https://trello.com/c/SvTsLdRF/12-translations) that assistance is still welcome even if there are many translators. It could explain that translators often become inactive and that seemingly large teams can actually be tiny. In theory at least, new translators should be looking at those documents before they get to the point of logging in to Transifex. @Miisa what do you think?

**Comment by ghost** [comment]
I only suggested this based on the feedback I got from the last two translators that came (and went again). The last one told me directly, that she hesitated to join because the translations were kept up to date and the team seemed big enough to handle it. I told her what the situation is and she helped now and then so I was kinda relying on her and then she disappeared and there was a batch of about 150 strings that nobody touched for 2 months until I made some time for it during Christmas. 

To be perfectly honest, I am very close to abandoning the translations. As I said, I run my own busines, so I am out of the house for 13 hours a day on average, we have recently bought a flat that needs total reconstruction that we will be doing ourselves, so in the following three to four months I will have zero time for translating. But at the same time I don't want the translations to die, because I have put a lot of work keeping it up by myself for the past almost two years. But there is nobody to leave the job to.

**Comment by ghost** [comment]
**_Edit by author:**_
This post contains personal vision and some controversial suggestions. Some of them have already been reconsidered by the author. All the suggestions are planned to be later discussed one by one (or at least in manageable portions of related questions).

---

May I post a comment here and not on Trello, please? I think it may be easier to link it in the future if needed.

I've spent some time just peeking inside some language teams on Transifex and chatting with the Transifex support to find some options we might want to try out to improve the translation management. 

**Some preliminary notes**
1. I can't say I have clear understanding of what is best for the translation management. So I just would like to suggest some topics for consideration. I'll be glad if some of them may be useful; and I'll be glad as well if the issues listed below receive different solutions.
2. I haven't tested any of the suggestions listed below or discussed them with translators yet. They are based solely on Transifex documentation and replies from support. It may happen so that during testing we may receive more input from translators and practical side itself.
3. The free Transifex plan has some limitations on the range of available tools, but none of them should influence implementation of the suggestions.
4. Transifex team claim that they want their service to be as flexible as possible. It's good, but on the other hand the projects need more effort in organizing the things in efficient way.

**Goal**
To have high quality translations of Habitica into as many languages as possible.

**Tasks**
1. Let the project be open to new contributors who can improve translations and introduce new languages
2. Maintain high level of translations - rely on translators who spend from 1 month to 1 year contributing
3. Make translations more self-managing - needing staff involvement only in case of difficulties)

**Current Issues**
1. Confusing organization structure: 3 projects, each having its own language teams
2. Hit-and-run translators: there are many translators who seem to never come back to Transifex after receiving the first "hello world" badge. This results in (a) seemingly large teams not needing more contributors and (b) possibly poor quality of these first "hello world" Translations
3. No incentives for reviewers to remain active and efficient
4. Translators cannot modify reviewed strings, and have confusing options of drawing reviewer's attention to their suggestion (due to Transifex limitations)
5. Reviewers may be reluctant to lock the translated strings as reviewed not being sure the best equivalents have been found.

**Suggestions**
1. Have single "team" assigned to the 3 projects of the organization and divided into language-specific sub-teams. In such a way translators wouldn't need to join different teams for the same language in different projects and it simplifies the work of coordinators, maintainers (it should be possible, needs testing for the free Transifex plan)
2. Each language team gets a coordinator who is responsible for internal team management (a team can have several coordinators)
3. Reviewers are regarded as active experienced translators, not as just those having privileges. They are encouraged to lock the strings as reviewed to motivate translators to become reviewers.
4. Translators are regarded as either newbies or inactive translators and should ask coordinators to make them reviewers when they prove to be experienced and skilful enough
5. Previously obtained contributor badges are grandfathered. A slightly modified (a bit more difficult) system is introduced to be more in-line with other contribution fields and organization structure

**Vision of the organizational structure**
Actually the structure of Transifex team can be linked to Habitica contributors' tiers.
Default Transifex organization structure:
![default structure](http://docs.transifex.com/images/introduction/user_roles_2015.png)
I believe it may be applied to Habitica projects "as is"
http://docs.transifex.com/introduction/#user-roles-in-transifex

_Role I - Translator_
aka a newbie, aka a Friend
Objectives: Study! Join Transifex project, join (request) language team, translate new strings, improve strings translated but not yet reviewed, check translated and reviewed strings, contribute to glossary, make suggestions in comments pinging reviewers, take part in team discussions
Responsibility: Avoid deliberate harm to project (translate into a language they don't actually know, use Google Translate, use batch translating for controversial edits etc ). Try their best to maintain good quality of translations (it's OK for now if translations are not very good, they'll be subject for reviewing).
Rewards: Tier 1 requirements: 2 weeks after joining a team, has translated some lines (if there are not-yet-reviewed lines), public activity (if applicable)
Tier 2 requirements: 1 month after joining a team + the same as for Tier 1
Punishment: in case superiors find repetitive deliberate harmful actions they report to the staff and Contributor badge is withdrawn (no matter from lvl1 or lvl2 to Contributor lvl 0)
Risks: too many translators - newbies should be told to respect both each other and retired reviewers who were made back to translators - and notified that the main job is mostly done by reviewers. No new translators - it's the job of the coordinator to find new translators and encourage them to go up the ladder

_Role II - Reviewer_
aka experienced active translator, aka Elite
Objectives: Do the main Job! Maintain good quality of translation, let translators (if any active) translate new strings and review them, improve previously reviewed strings (incl review suggestions from translators), contribute to glossary, start team discussions.
Responsibility: obtain reviewer status from coordinator/team manager (e.g. by PMing them) and accept responsibility - not sooner than 1 month after joining a team, stay active translating and reviewing the strings, communicating with translators, avoid deliberate harm to project
Rewards: Tier 3 requirements: 3 months after joining a team, reviewer status, be active translating and reviewing lines (at least after obtaining a reviewer status) - proven with a screenshot of activity grapgh, public activity (if applicable), 
Tier 4 requirements: 6 months after joining a team + the same as for Tier 3
Punishment: reviewers are made translators (back) as soon as a coordinator/team manager notices 3 months of inactivity (a reviewer is then considered having lost the track of recent changes in the project), or the team decides that translations are controversial and coordinator supports that decision. Contributor badges remain even if a reviewer is made a translator, but they can be withdrawn by the staff (e.g. in case of not following community guidelines).
Risks: too many reviewers may be a problem in case of personal arguments which should be handled within a team or with the help of the superiors. In case no reviewers are left, the superiors should work directly with translators waiting for an opportunity to promote them. If reviewer is made back a translator by accident (from either side) they can be promoted to reviewers by superiors without additional waiting period.

_Role III - Coordinator_
aka supervisor, aka Champion
Objectives: Maintain effectiveness of a particular language team, assign reviewer status and withdraw it, open language team discussions, promote translation activities in language-specific guilds to invite new translators
Responsibility: stay active managing a particular language team
Rewards: Tier 5 requirements: not sooner than 6 months after joining a team, ask for coordinator status from another coordinator/team manager/staff accepting responsibility and punishment
Punishment: coordinator status is withdrawn (back to reviewer) and Tier 5 is withdrawn (back to tier 4 Elite) if a coordinator is (a) away without notice for 2 months /1 month if there are no other coordinators in the team/ or (b) announces leaving if they are the only coordinator for a team and don't wait for other reviewers being promoted up to coordinators
Risks: no reviewers want to become coordinators - superiors work directly with reviewers/translators waiting for ambitious contributor. Too many coordinators - no real feeling of responsibility should leave only the most motivated active. Some may be not effective enough in managing the team - they should be helped by the team manager.

_Role IV - Team Manager_
aka super-supervisor, aka Champion
https://www.transifex.com/blog/2014/introducing-team-managers/
Objectives: manage coordinators and do their job if particular teams have no coordinators
Responsibility: stay active managing difficulties
Rewards: Tier 6 requirements: not sooner than 1 year after joining a team, ask for team manager status from staff accepting responsibility and punishment
Punishment: Team manager status is withdrawn (back to coordinator) and Tier 6 is withdrawn (back to tier 5) if a team manager is (a) away without notice for 1 month or (b) announces leaving if they are the only team manager and don't wait for other coordinators to be promoted up to team managers
Risks: too much time needed to handle the things - possible delays, but managers are there to help the staff, at least as much as they can =) 

_Role V - Project Maintainer_
Objectives: manage files in projects, must be something else
Responsibility: stay active managing files
Appointed by the staff

I'm sure I must have forgotten some ideas just as I've been typing, but I'm posting it anyway hoping someone may have other ideas.

**Comment by ghost** [comment]
I've got a quick update from Transifex support confirming that it's possible to simplify the projects-teams-languages structure:

> This is exactly what we had in mind when we created Teams and Projects so that the administrator would create one team and assign several projects to that team. In your case, the most convenient would be to create a Team, named for example "Habitica", put someone trustworthy as Team Manager and have him invite your people to the team and manage it. The Team Manager role is optional, but from our experience, it's helping very much to share roles and responsibilities.
> 
> If you need more information about Teams you can take a look at our documentation [here](http://docs.transifex.com/features/teams/).

**Comment by paglias** [comment]
@GitHubSphinx The suggested organization seems a good idea, that being said it would require big changes and a group of people willing to manage each language in a very active way

**Comment by ghost** [comment]
@paglias Thank you for your comment!
I was afraid those thoughts could sound like a call for revolution. However in fact it's just my vision, for what it's worth. I can't say what will actually work best. That's why I'd suggest taking it step-by-step monitoring the results. I'll try to squeeze the suggestions out of that open stream of thoughts =)

**Comment by ghost** [comment]
**_Edit by author:**_
This post contains personal vision and some controversial suggestions. Some of them have already been reconsidered by the author. All the suggestions are planned to be later discussed one by one (or at least in manageable portions of related questions).

---

Suggestions by estimated difficulty of implementation:

##### 0. Have Guidance for Linguists up-to-date no matter what changes take place

_It also includes improving the Transifex part of welcoming new translators - i.e. giving them particular recomendations, including language related ones._
_In fact there are some questions regarding Transifex features, I doubt we could ever use effectively, including suggestions, comments, discussions, announcements. Transifex support admits, they have only few projects that have so many collaborators_languages_files*lines. They do seem willing to help, but there won't be ideal solution for our language team discussions. So it will always seem that we tend to make any Transifex discussion opportunity a bit messy_ 

##### 1. Define more precise requirements for the first badge e.g. corresponding to the first badge as Linguistic Scribe

_Unfortunately, a requirement of a particular number of lines translated will very difficult to administrate (some languages are 100% translated and almost 100% reviewed; free-for-opensource Transifex plan doesn't provide detailed reports about translators' activities, search filters show only the last translator, contributed to the sting). So the suggested parameters may be: (a) more than a month using Habitica (b) regular contribution during a certain period of e.g. 2 weeks - proven by a screenshot of the profile page (it may be 100 lines today and 2 weeks waiting for the badge, or 20 lines twice each week or just a couple of lines each day - something like that). I've seen only one question from a pro translator who had asked to translate everything quicker and get tier++ faster - but I do believe that Transifex projects are ongoing trial and error rather than one time finding seemingly the best solution job_

##### 2. Simplify the teams

_Our Transifex "organization" Habitica ( https://www.transifex.com/habitrpg/ ) has 3 projects (web, iOS, Android). Currently translators should join 3 teams responsible for these 3 different projects, then they have to be made reviewers for 3 different projects... Transifex offers a way to simplify team management. Some mechanic basics: we may have one team "Habitica" assigned to all the three projects. If a particular language (e.g. Greek) is requested for e.g. Web project - it won't be automatically added to the other 2 projects. However if all the 3 projects have a particular language (e.g. Greek) a user could just join the team Habitica specifying the Greek language and start translating any of the three projects. If a user translating the Web project becomes a reviewer for Greek language of the team they will be a reviewer for all the 3 projects. The same will apply for coordinators._

_The roles in the team are assigned and managed by the team managers_

_Transifex support gives the following example when several team might be needed. "Some customers choose to create a second team of trusted collaborators and assign them some projects that contain sensitive information or content with specific terms, like legal documents"._

_When merging teams there are several options, including the 2 major ones: assign the first HabitRPG team to all the three projects having all translators already its members; or create the brand new team and have all translators rejoin it_

##### 3. Define the way to understand reviewers and the process of reviewing

_Reviewing is the tool of quality control on Transifex. Reviewers are translators who can lock the line from editing by not-reviewers. Currently we give extra tier to translators appointed reviewers. The problems are: (a) we have inactive reviewers (who got their tier and left) and (b) there are many lines containing mistakes or just not-the-best translations locked from editing by not-reviewers (c) one translator-reviewer teams sometimes used to review everything they'd translated themselves - new translators could suggest better alternatives. In theory, translators should leave comments pinging reviewers or coordinators - but many of them are inactive. So translators just prefer to mark lines as issues to notify maintainers and staff. Those messages are difficult to manage because of the language barrier (like one of the today's - "Should it be 3015年2月" `just kidding` Oh, well, it turned out easy. =)_

_Transifex support suggested making all(!) translators reviewers when they've seen how many language related issued we have. However I don't think that will be a balanced decision. We do need more active reviewers, but assigning reviewers status only after a translator has proven themselves trustworthy - e.g. if there are many lines they translate and edit that noone disagrees and fix later. It can also be a decision individual for a language team._

_I'd still suggest not awarding tiers for just being appointed a reviewer but rather stick to the pattern of timed contribution. That way we may come to having only those reviewers who want to review and edit rather than just getting tier+. I think reviewers will still be reviewing motivated by the timed badges (3 months, 6 months, etc) and idea of making translation better_

_Reviewers status can be assigned by a team manager or a language coordinator._

##### 4. Define the requirements for appointing language coordinators

_Coordinators are reviewers who have the team manager's power for a certain language. I think we could try appoint the most responsible reviewers coordinators and try delegating responsibility of appointing reviewers. After thinking it twice, I believe this should be first tested on one or two language teams._

**Comment by Alys** [comment]
I'm not competent to comment on most of this (I love the effort and detail you're putting into this though!) but a couple of points:

**"Have Guidance for Linguists up-to-date no matter what changes take place"** -- Absolutely! If you become aware of any changes needed and don't have time to make them yourself, do please describe them in the Wizards of the Wiki guild and the wiki editors will be happy to help.

**"Define more precise requirements for the first badge e.g. corresponding to the first badge as Linguistic Scribe"** -- Best to not use the Linguistic Scribe tiers as any sort of comparison. The process for awarding them has very little rigour. It's impossible for me to judge the quality of the wiki translations, and the Wikia points system isn't reliable (even for the English wiki) because points can be gained for low-value edits. The best I can do is make a vague guess at whether someone deserves a Linguistic Scribe tier. (I'd be keen for that process to be improved, but the time for that is probably later.)

**Comment by Alys** [comment]
I'm closing this because these days we're using GitHub for bug reports but there's some great information here.  It's probably best handled by copying it to a wiki page and developing improved processes from there.
