### ISSUE TITLE
Can't leave party

### ISSUE THREAD

**Issue by dgodovanets** [HabitRPG/habitica#6481]
"Ошибка Runner error: Overflow sort stage buffered data usage of 34523394 bytes exceeds internal limit of 33554432 bytes" 

This error is shows, when I press "Leave" on page of party.

**Comment by Alys** [comment]
I'm afraid we can't help you without being able to identify your account.

Please go to Help --> Report a Bug on the Habitica website and see the instructions there for providing your User ID (step 6).

**Comment by dgodovanets** [comment]
Sorry, I don't read that :)
6b4563cf-ef71-4508-839e-f553d358dab9

---

After copmuter reload problem gone.
