### ISSUE TITLE
Error after syncing

### ISSUE THREAD

**Issue by dgodovanets** [HabitRPG/habitica#6484]
Упс, произошла ошибка! Пожалуйста, перезагрузите страницу, ваше последнее действие, возможно, было сохранено неправильно.

"Ошибка " 

Если ошибка появляется вновь, пожалуйста, сообщите о ней через меню Помощь > Сообщить о проблеме. Если вы знакомы с консолью браузера, пожалуйста, включите в отчет возможные сообщения об ошибках.

Error after syncing.
Translate of error: It is could be, that last event was saved wrong.
**User ID: 6b4563cf-ef71-4508-839e-f553d358dab9**

**Comment by Alys** [comment]
Google Translate:

**Oops, there was an error! Please reload the page, your last action could have been stored properly**

**"Error "**

**If the problem persists, please report it via the menu Help> Report a Problem If you are familiar with the console browser, please include in your report any error messages**

Error after syncing 
Translate of error: It is could be, that last event was saved wrong

**Comment by Alys** [comment]
**@Eramik Please reload the site.**
**If the error still happens, go to https://habitica.com/static/clear-browser-data and click the button.**
**After that, tell us if the error still happens.**

Google Translate:
Bitte laden Sie die Seite.
Falls der Fehler immer noch geschieht, gehen Sie zu https://habitica.com/static/clear-browser-data und klicken Sie auf die Schaltfläche.
Danach sagen Sie uns, wenn der Fehler immer noch geschieht.

**Comment by Alys** [comment]
Sorry, I wrong language. I was doing some German translations for someone else and the setting stuck in Google Translate.

Пожалуйста, перезагрузите сайт.
Если ошибка все еще происходит, перейдите к https://habitica.com/static/clear-browser-data и нажмите кнопку.
После этого, сообщите нам, если ошибка все еще происходит.

**Comment by dgodovanets** [comment]
I understand English well, and it is unnecesary to translate for me. But thanks :)
**After reloading and cleaning problem is still there.**

**Comment by Alys** [comment]
Thanks @Eramik  :)

@paglias this might be another instance of https://github.com/HabitRPG/habitrpg/issues/6478 (persistent application errors). I've bolded the most relevant parts of the above comments.

**Comment by dgodovanets** [comment]
CTL+ALT+J is not working :/
Some new info. I have invite to the party, wich I consist now.
Вас пригласили в команду! Вы хотите покинуть эту команду и вступить в jtanhabitica's Party?
You was invited to the party! Do you want to leave this party and join in jtanhabitica's Party?
I press yes, page reloaded and invite come again.

**Comment by paglias** [comment]
@Eramik if you give us your permission and your UUID we'd like to try replicating the error by making a request to the server on your behalf. We need that in order to be able to see what's really happening on our side

**Comment by Alys** [comment]
Ctrl-Alt-J not working is odd!  Can you try going through the menus? View -> Developer -> JavaScript Console.

The party invitation problem isn't related to this. It's something that happens sometimes. I've deleted the excess invitation, but it will probably come back several times before it finally disappears. I'll keep checking twice a day and deleting it when I see it until it's gone for good. If you received the invitation after you used the button at https://habitica.com/static/clear-browser-data , then it might help to use that button again now - that might make the invitation disappear permanently straight away. However, it's possible that the person who sent the invitation would also need to click that button.

**Comment by paglias** [comment]
If you're on a mac you should use Cmd instead of Ctrl

**Comment by dgodovanets** [comment]
I give you all premissions. I using windows. Now I'll try goin trough the menu

**Comment by paglias** [comment]
@Eramik ok, we'll need your UUID for this, you can find it into Settings -> API

**Comment by Alys** [comment]
@paglias it's in the top comment. :)

**Comment by paglias** [comment]
Thanks :) Didn't see it

**Comment by paglias** [comment]
@Eramik Ok, I tried making requests on your behalf and the site loads and works correctly. Which means that the problem is probably related to your computer, which is not to say it's your fault just that the error is not due to data stored in the database. 

Could you try using a different browser?

**Comment by dgodovanets** [comment]
Okay, I'll try.

**Comment by dgodovanets** [comment]
In another browser all good. But I cleaned up browser data many times :/
Developer console https://youtu.be/0DcQr-AJqgc

**Comment by paglias** [comment]
@Eramik thanks, that's very useful. So replicating the same set of actions in a different browser the error doesn't happen?  From your video it seems that the error only happen when you've visited your party page, right?

To clear browser data, try this:
1. Open the developer console
2. Switch to the Resources tab on the top of the console
3. On the left expand Local Storage and select `https://habitica.com`
4. Delete all entries especially `habitica-mobile-settings` and `habitica-user`
5. On the left expand Cookies->habitica.com and delete all entries there too
6. Reload the page

I'll try once more making a request on your behalf from the party page

**Comment by dgodovanets** [comment]
It happen ater I accept party invite and go to the party page. In another broser after accepting invite is gone and all right.

**Comment by dgodovanets** [comment]
Some offtop question. How to disable damage from tasks(not daily or habits)?
For example, I add task, that I want to do on next week, but I take damage every day.
Set do time for every tasks it's very long.

**Comment by paglias** [comment]
@Eramik you mean from Todos? You don't take damage from todos, they just become more red as time passes which means you'll get more points when you do them.

**Comment by dgodovanets** [comment]
But when they become red I took 1 damage per task :/
Daily and habits all right

**Comment by dgodovanets** [comment]
"To clear browser data, try this:"
It is not helps. Invite still there D:

I don't want to clear all browser data. I logged in many sites. And I don't like browsers, except Google Chrome. This invite is annoying :C

**Comment by Alys** [comment]
To-Dos very definitely do not cause any damage for you. We're absolutely certain of that. There's no code that could allow them to damage you.

If you're finishing all your Dailies each day and you aren't clicking negative Habits, but you are still being damaged, there's two possible causes. One is that you're being damaged by a quest boss if you are on a quest and your party mates aren't finishing all of their Dailies. The other is that you might be affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313 -- what happens there is that your browser shows you that your Dailies are completed, but it doesn't send that information to Habitica's servers, which means that when cron runs the next day, Habitica thinks you have not finished your Dailies. Have you been noticing your streaks dropping to zero when they should not be? If so, it's that bug. There's an "Advice" section near the top that might help.

The party invitation will keep coming back. Just ignore it as best you can. I'll keep deleting it when I see it in your account and it will disappear permanently in a few days.

**Comment by dgodovanets** [comment]
Nice, thanks. Rather it is boss

**Comment by Alys** [comment]
@Eramik Are you still getting the errors often after syncing? We made a change to the server a couple of days ago which we think might have fixed it.

**Comment by dgodovanets** [comment]
No. All right.
