### ISSUE TITLE
Challenge botton

### ISSUE THREAD

**Issue by dgodovanets** [HabitRPG/habitica#6487]
User ID: 6b4563cf-ef71-4508-839e-f553d358dab9

I joined to challenge. After 10 minutes I leave it, but challenge button not gone.
When I leave it, I choosed "Delete challenge tasks". Task was deleted automaticly, but button not.
http://prntscr.com/9oaudc

**Comment by Alys** [comment]
That's a deliberate feature. Please see the second comment (from me) in this issue: https://github.com/HabitRPG/habitrpg/issues/4062

If you'd like to give feedback about it, you're welcome to comment on that issue to keep the conversation in one place.
