### ISSUE TITLE
Can't register normally.

### ISSUE THREAD

**Issue by denning** [HabitRPG/habitica#649]
This seems to be different than issue #639 

Running Windows 7 SP1 (version 6.1.7601)

Chrome v. 25.0.1364.152:
- Page loads fine
- I click on Login/Register and window pops up
- I click on "Register" tab; four input fields appear
- I type in a username, I try to click on the email input field and it kicks me back to the main page (no error message)
- Similar result if start with password field first, etc.

Firefox v. 19.0.0.0:
- Same as above

IE v. 9.0.8112.16464:
- Page loads normally
- If I click on Login/Register, nothing happens
- If I view the page in compatibility mode, there are layout issues and clicking on Login/Register still does nothing

(I ended up just using the Facebook login/register button via Firefox, which worked.)

**Comment by bouil** [comment]
I confirm in Mac/Chrome. I cannot register, the register modal popup disappear.

**Comment by lefnire** [comment]
one by one, all our form fields are busting: see https://github.com/lefnire/habitrpg/issues/539 .
It's so weird that these problems are incremental. First rewards hit us, then profile fields, now registration. Oi, ok looking into

**Comment by lefnire** [comment]
i'm gonna follow up with my musings in #539, then once it's solved we'll be able to close all 3

**Comment by Jimflip** [comment]
+1 doesn't work for me :(

doesn't work in firefox either on osx

**Comment by lefnire** [comment]
fixed https://github.com/SLaks/racer/commit/fcfed82b43da1f43120d042f8695416594fed7f0 , thanks @SLaks!
