### ISSUE TITLE
Integrate tasks with Google Reminders (Google Inbox)

### ISSUE THREAD

**Issue by dbarnett** [HabitRPG/habitica#6492]
I'd like to mirror tasks between Habitica and [Google Reminders](https://support.google.com/inbox/answer/6062813) so that when I mark a task done in one, it's marked done in the other.

**Comment by dbarnett** [comment]
This would be a part of #3750 for Google integrations in general.

I have no idea whether Google has exposed an API to do what we'd need. http://stackoverflow.com/questions/26528778/api-for-inbox-by-gmail suggests they haven't.

**Comment by librarianmage** [comment]
@dbarnett You might want to post this on the [Trello Board](https://trello.com/b/EpoYEYod/habitica) so it can be organized with other suggestions. (@Alys, should this be closed?)

**Comment by Alys** [comment]
Yes, I'm closing this because feature requests are best collated in Trello.
