### ISSUE TITLE
Application Error (Cosmetic)

### ISSUE THREAD

**Issue by ambergohn** [HabitRPG/habitica#6494]
The Application Error popover/slide-in/whatever has a cosmetic error on it.
<img width="1503" alt="2016-01-11_0924" src="https://cloud.githubusercontent.com/assets/6862467/12236014/7a161232-b845-11e5-89aa-ee91a51abf74.png">

**Comment by AnnaFromPoland** [comment]
yup, it's annoying, even more than the error itself.
<img width="1440" alt="0028-01-12 11 54 08" src="https://cloud.githubusercontent.com/assets/16665256/12261948/ab4491f0-b924-11e5-8bd7-b6f1df3333cc.png">

**Comment by xxstaten** [comment]
Also getting the same problem, anyone have any ideas on fixes D: ?

**Comment by librarianmage** [comment]
Is the "Application Error" part an iframe? I get it occasionally, but I've never checked.

**Comment by Alys** [comment]
We're tracking this error now at https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this one. There's some advice at the top of that issue for anyone who experiences this problem.

**Comment by deilann** [comment]
I don't think that we're tracking the visual appeal of the application
error at #6700 are we? This is about how the application error looks.

On Sun, Mar 6, 2016 at 2:39 PM, Alys notifications@github.com wrote:

> We're tracking this error now at #6700
> https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this
> one. There's some advice at the top of that issue for anyone who
> experiences this problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6494#issuecomment-193009499.

## 

Currently Reading
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=reading_link&utm_source=email_signature
[image: Book Cover]
https://www.goodreads.com/user/email_signature_destination/35215676?utm_medium=cover&utm_source=email_signature
