### ISSUE TITLE
Application Error When Using PC/Chrome

### ISSUE THREAD

**Issue by kwhold** [HabitRPG/habitica#6495]
Console log attached.
[habitica.com-1452522198774.zip](https://github.com/HabitRPG/habitrpg/files/85857/habitica.com-1452522198774.zip)

**Comment by kwhold** [comment]
Additional Info:
  User ID: 4919c088-c263-4dab-bc77-7d8bd35a275b
  Browser: Chrome Version 47.0.2526.106 m
   OS: Windows 7 Enterprise, Service Pack 1

**Comment by lvdpal** [comment]
I have this problem a lot lately as well. It's mostly complaining of a bad request:
Failed to load resource: the server responded with a status of 400 (Bad Request) https://api.amplitude.com

I'm also seeing a "Failed to load resource: the server responded with a status of 503 (Service Unavailable)" https://habitica.com/api/v2/user/batch-update?_v=80&data=1452541897649

**Comment by ghost** [comment]
I am seeing the same message again, too: the 503 Service Unavailable error. Last month when this happened, the admins just reloaded/restarted the program and it fixed it.

**Comment by cymr0** [comment]
Hi, I'm getting the same problem. too. I've attached my console log.

Browser: Chrome Version 47.0.2526.106 (64-bit)
OS: OSX 10.11.2
User ID: b4219281-e2e3-4602-922a-33968e4ac5ba

[habitica.com-1452543458417.zip](https://github.com/HabitRPG/habitrpg/files/86340/habitica.com-1452543458417.zip)

**Comment by FoxySophie** [comment]
I'm also getting a lot of "Application Errors" on the page recently, started about 3 days ago I think (January 9th). I'm not exactly using Chrome but Opera which basically uses the same engine so I didn't want to open a separate issue.

Browser: Opera 34.0.2036.47 (64-bit)
OS: Win7 Professional 64bit SP1
User ID: 63beb263-03bc-4d2b-9a67-26642b17383f

**Comment by Alys** [comment]
We made a change to the server a few days ago that seems to have reduced the frequency of application errors, so I'm closing this. However if you notice them happening again often, you can comment here and we'll keep investigating.
