### ISSUE TITLE
I Love Data

### ISSUE THREAD

**Issue by hookang** [HabitRPG/habitica#65]
What would also be interesting if you could collect anonymous data to figure out which habits people do well? Why they do well? etc...

After all I would imagine the goal of this app is to help people create good habits.

**Comment by lefnire** [comment]
eventually planning to provide default common tasks - like 'exercise' and 'stop smoking' - based on items entered commonly in the database. But as far as data-analysis, that might have to be a separate project - a 2nd codebase crunching the database in background jobs & providing a d3 charting interface. Sounds awesome indeed, but I probably won't be tackling that myself. Hey, open source ;)

**Comment by horusofoz** [comment]
Jumping on the idea of common tasks can I suggest if D&D theme is active consider them quests from various people or bodies.

Example could be "The Fighter's Guild of Skyrim have issued a common challenge to exercise 7 days in a row. Warriors that accept this challenge will receive xGP. If successful you will receive xGP or xLoot. If you fail you will lose xGP and receive a sound beating at the hand of the guild's elite warriors for -xHP." Exercise routine can be self defined. If looking for inspiration check out Xlink.

Alternate example could be "The Mayor of Healthville has issued a 7 day ban on smoking while the "Healthiest City In The World" competition inspectors are in town. Healthville inhabitants that comply with the ban will receive a reward of xGP or xLoot. If you are found out to be smoking in Healthville during the ban you will be evicted, tied down outside of town and forced to smoke 11 cigarettes of cat hair  for -xHP. Do you wish to travel to Healthville for the Smoking Prohibition Challenge?

A couple examples which could be written much better but there is the concept.

**Comment by hookang** [comment]
Those are excellent ideas... I would imagine administering them or creating an administration portal could be a pain an additional hassle

**Comment by horusofoz** [comment]
I would think rather than requiring an admin portal for these (at least in the initial single user app, could be a good enterprise for much later) these could be global/public quests. Similar to the random rewards.

**Comment by racuna** [comment]
An easy way to share good examples of Habits, Dailies, Todos or Rewards between users without implementing a monster data-analysis engine could be implementing a php forum, or maybe open a google or facebook group or a g+ community and just put a link to that platform in the footer. 
That could be a great way to know other habitRGP users too.

**Comment by wc8** [comment]
I don't like the idea of my habits being collected even anonymously so I would want an opt-out option.
I do like the "quest" idea though whether it ends up being called quest or campaign. I think it's kind of a party version for https://github.com/lefnire/habitrpg/issues/59

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
I think the initial request falls under [Library of Crowd Sourced Tasks](https://trello.com/c/dwIeOjZQ). Follow the link to vote for it.
[Awards request](https://trello.com/c/4uWICvDf) is also relevant.
If any request was missed, please comment back.

**Comment by StanLindsey** [comment]
I for one love meta-data it can be a fantastic motivator if used properly as well.

**Comment by wc8** [comment]
[Community Challenges](https://trello.com/c/qRmRIYDd) were also mentioned above. Follow the link for voting.
