### ISSUE TITLE
Equipment way too expansive

### ISSUE THREAD

**Issue by samoKroslak** [HabitRPG/habitica#650]
Hi, 

I'm lvl 5 and I check-in around 3-4 daily and 2-3 pluses in habits, 
I don't use tasks, 
in my case - rewards (helmets, armor, weapons) are way too expansive, so far I managed to buy only one sword, 
I had to set-up my rewards to 1-7 gold per reward, just so I won't get bankrupt/dead within days :D and I only spend like 1-3 gold per day for rewards maximum, 

I can't imagine having a reward costing the default 20 gold - that would mean for me 1 reward per 1-2 weeks. 

is everything alright with me? is making new habits really supposed to be that hard?

**Comment by lefnire** [comment]
This is the first complaint to that effect., most people seem to be buying
1 or 2 items a day. Wanna show us your setup maybe? Could be you have too
few tasks in your lists

**Comment by samoKroslak** [comment]
here, take a look: 
http://www.evernote.com/shard/s5/sh/348c787c-13d6-4686-aa6a-8e03edfa81c0/d189d67648eae261940118d1caa0e0a0 
btw, I'm saving for the leather armor for the last couple of days :) 

edit: sorry, distorted image... but you can probably see what's going on

**Comment by lefnire** [comment]
Yeah, to few items. My lists all take up almost exactly my screen height,
and since I put this originally for myself, the prices match my completion
patterns. Some people have way more tasks than me and this game is too easy
for them. There's a conversation floating around about normalization, I'm
on my phone now so I can't look it up but give it a search

**Comment by samoKroslak** [comment]
uhm, okay, that explains it, 
so I'll keep track with that normalization issue and in the meantime adjust reward prices down so they won't kill me soon, 

thanks and keep up the awesome work  :+1:

**Comment by wc8** [comment]
#325 Difficulty Normalization
Also, as well as adjusting the cost of custom rewards, you can use the Difficulty setting to increase the value (and HP loss) of tasks.

**Comment by wc8** [comment]
Perhaps the discussion can to #325 then? I'll close this one for organization purposes, but you can still reply here.

**Comment by samoKroslak** [comment]
okay, I'll try adjusting difficulty of habits/daylies as well
