### ISSUE TITLE
Party Challenge "to-do's" will not go away 

### ISSUE THREAD

**Issue by skatergoat** [HabitRPG/habitica#6500]
I have been meaning to report/fix this problem for a while but I have been too busy to try, But I made a Challenge in my group party, mostly for me and my boyfriend/roomate to join and complete, but the point is I finished the task, but when i would click them to be done, they would not go away, i tried to delete the challenge hoping that it would make the tasks go away so not to be annoying, but nope they stay but now if you check them off they just say " task not found" but still will give you gold and drops and etc, but they wont go away.
My API is : 8a655a7b-f152-46ef-843f-c886b9593dd6
( dont know if this is needed but ) Group ID: 05515d0b-d41d-4f35-a4c7-a3e2a256c6b0 
my browser is Google Crome  and operating system OS X Yosemite

**Comment by Alys** [comment]
This bug has been reported here: https://github.com/HabitRPG/habitrpg/issues/2763

In the first comment there, there's some text in bold that links you to a wiki page with some steps to try. It sounds like you've already tried some of the steps, but please read through that section and try anything you haven't already (e.g., using the mobile app). Let us know how that goes!

**Comment by skatergoat** [comment]
Hello i went to the wiki, and the only thing i had not tried was the mobile app, i downloaded it and signed in and the it only had one of the many broken to-do's i checked it off and it went away on the app but not the site, but when closing the app and coming back it is still there, ive tired to check them off countless times and nothing happens

**Comment by Alys** [comment]
So the website is showing you tasks that don't appear on the app? It's possible that they have been deleted on Habitica's server, but your browser is still showing them to you. That would explain the "task not found" message. Please go to https://habitica.com/static/clear-browser-data and click the button there. Does that make them disappear?

**Comment by ParodyKnaveBob** [comment]
Howdy. I have some background in bug reports, but I just started playing this a couple days ago, (liking it so far!) and this is my first post here. Bear with the newbie, please. ;)

User ID: 17b3b3c0-5355-4277-a0f6-289424052d4a
Browser: latest stable Google Chrome (47.0.2526.106 m)
OS: Windows 7 Home Premium SP1
(I'm having trouble getting the Javascript console info, sorry.)

I've gotten the "Task not found." error today multiple times dealing with my To-Dos, but I've not joined any challenges. I did poke around, **looking at** some challenges, including looking at (and pushing a couple buttons in) some of the Challenge Details and Participant Progress boxes, but I haven't joined any.

Earlier in the day, I checked off a To-Do task, and it said "Task not found." and rewarded me experience and gold. I unchecked it, and it properly took back the experience and gold. I checked and unchecked again. I refreshed the browser and tried again. Always "Task not found." I searched Help and so forth and came across this page and the link to clear my browser data for Habitica. When I logged back in, **it properly stated the task**, yay.

Then, many hours later, I checked off another To-Do task, and it did the same -- "Task not found." and experience and gold -- but this time, I also got my first potion drop, the Zombie Potion. (I already got two eggs through the day via other stuff I got done.) I unchecked, checked; unchecked, checked; refreshed; unchecked, checked; still "Task not found." and it unfortunately gave me the same Zombie Potion drop every time, thus I have three ill-gotten potions for a total of four. I cleared the browser data, but this time, when I logged in and once again checked off the task, (and refreshed and unchecked, checked again,) it **still** said "Task not found." -- but at least it stopped dropping items (just experience and gold).

I want to make sure I get another major To-Do task finished within the next bit here, plus the last couple of my Dailies. Afterward, I'll report back here what gets properly stated vs. "Task not found."

"P.S." I'm torn between selling the three extra potions for gold then removing the gold manually using that stat-modifying feature ... vs. just keeping those potions as an extra reward for having to go through all this including signing up for GitHub. :D ..addendum: Now that I've read #4626, yeah, I'm much more inclined to just keep the potions in this case. Thanks, Habitica! ;b lol

**Comment by Alys** [comment]
@ParodyKnaveBob You can ignore the "Task not found" message. It occurs when a task is moved from one position in your task list to another if the new neighbour task in the new position can't be found - it's just an indication that your action to change the sort order of your To-Dos might not have occurred correctly. It can occur when ticking off a To-Do because completed To-Dos are automatically moved to the bottom of your To-Do list. You're probably finding that you see the message whenever you have a To-Do filter applied (e.g., you're using a tag or using the "Dated" To-Do tab), but not at all or hardly even when there's no filter applied (e.g., no tag and the "Active" To-Do tab) -- this is because having a filter in place does make it harder for Habitica to accurately sort To-Dos.

**Comment by ParodyKnaveBob** [comment]
@Alys - Ah! Thank you, okay. That makes me feel better. And yeah, I'm definitely taking advantage of the Dated tab. :) I'd like to take more advantage of the sorting for my own visual priority, but going between Active and Dated (and Done and reloading for any reason) messes with that, thus .. oh well.

All right, my wall of text seems unrelated then. Carry on. Thanks again. :)

**Comment by Alys** [comment]
@skatergoat Do you still have old challenge tasks that you can't delete? If so, tell us the text of one or two of them - that should let us identify all them by their challenge IDs and we can try some database commands to remove them.
