### ISSUE TITLE
Getting multiple 503 errors on two different accounts.

### ISSUE THREAD

**Issue by bjcj123** [HabitRPG/habitica#6501]
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

Anytime I refresh I get the same error for different files each time. Using Chrome 47.0.2526.106 m. Internet connection is stable, accessing from Australia. 

Example:
https://habitica.com/api/v2/groups/undefined/chat/seen Failed to load resource: the server responded with a status of 503 (Service Unavailable)

Assume this is because there is server maintenance or something?

**Comment by SabreCat** [comment]
This might be related to a sporadic local storage issue we're investigating. Can you try visiting https://habitica.com/static/clear-browser-data and/or using an incognito browsing session and see if you can log in cleanly after that?

**Comment by Alys** [comment]
@bjcj123 We haven't heard back from you so I'm guessing it's now working for you and I'm going to close this, but if you're still having trouble, please see the previous comment from SabreCat and tell us how that goes.
