### ISSUE TITLE
No way to calculate previous delta

### ISSUE THREAD

**Issue by doyler** [HabitRPG/habitica#6503]
While calculateReverseDelta() and calculateDelta() work just fine for checking tasks, there is currently no calculatePreviousDelta() method for when a Daily or a To-Do is unchecked.

Using calculateReverseDelta() ALMOST works for this (see Issue #5648 and subsequent commit), it calculates the delta based on the current values, so ends up slightly off.

Adding a method to calculate the previous delta will allow any damage etc. done to be completely instead of partially reverted.

**Comment by abatula** [comment]
Is anyone working on this? I can look into it if not.

**Comment by Alys** [comment]
@abatula I'm sorry about the late reply. I'm working on refactoring common/script/ops/scoreTask.js in https://github.com/HabitRPG/habitrpg/pull/7607. There's a lot of confusing code in the current live version which was masking some bugs so it's probably best that you don't work on it yet.  I'm putting this issue on hold until I've finished the tests for that PR. I'll try to get it finished soon. :(

**Comment by lemoness** [comment]
Is this still something that needs to be done?

**Comment by beffymaroo** [comment]
Any updates on the status of this issue? @Alys

**Comment by Alys** [comment]
The issue still exists but I'm not sure it's important enough to fix it. The difference is very small. Also if the user's own stats have changed in between ticking and unticking the task, then the calculation would be wrong anyway. 
There's been talk about keeping a history of actions and results so if that's ever done, that would be a better source of data for accurately undoing task completions.
I'm closing this but it can be reopened if needed.

(The refactoring described above was never finished. I'd asked for advice about tests and left it on hold for that, and so the code changes eventually became too outdated to be useful.)
