### ISSUE TITLE
Basi-list quest not received

### ISSUE THREAD

**Issue by Kaznotar** [HabitRPG/habitica#6508]
I joined a party and invited one friend via their User ID. When they joined I expected to receive the Basi-list quest but never did.
My User ID is: 82d32884-e683-4b7f-8b7c-23aefecd565c
The party Group ID is: 1339c2e1-545e-4e62-9169-5f2fd5ed061e
I predominately use the website (Chrome on Windows 7) and the Android App.

**Comment by Alys** [comment]
I've checked your account and you have two Basi-List quest scrolls. Have you reloaded the site since they accepted the invitation? A reload is always a good idea when you don't see something you're expecting to see because the change might just not have been picked up by your browser yet.

**Comment by Kaznotar** [comment]
Thanks
