### ISSUE TITLE
Duplicate invitation to same account

### ISSUE THREAD

**Issue by MattCurry-Nano** [HabitRPG/habitica#6514]
User ID: 21dbd8d5-51fa-4713-83a0-cebb5437ce7a
Group ID: 9871525b-f65a-4d32-8631-3cbe2ab0de0d

My account appears to have gotten the same invitation to the party twice, the result being that although I'm already in the party, I get a banner box asking whether or not to ditch my current party for the _same_ party.

The Members and well as the Invited lists both contain my username as well.  It's almost like there are two linked accounts or something.

Currently, I'm on Windows 7, Chrome Version 47.0.2526.106 m

The banner message is really annoying: each time I log in again it keeps returning.

**Comment by Alys** [comment]
I've deleted it but please see the comment in bold at the top of https://github.com/HabitRPG/habitrpg/issues/5649
You don't need to comment on that issue.

**Comment by MattCurry-Nano** [comment]
Hmm, I did a search for duplicate invitations and nothing came up.  Thanks.

**Comment by Alys** [comment]
In your defence, that issue wasn't marked as "memorable" and didn't have that bold text at the time you created this one. :)
