### ISSUE TITLE
feature request: sync tweets or rss feeds  automatically to  chat in the party?   

### ISSUE THREAD

**Issue by longlu** [HabitRPG/habitica#6516]
feature request: sync tweets or rss feeds  automatically to  chat in the party?

**Comment by Alys** [comment]
Hi @longlu. GitHub is used primarily for reporting bugs. Feature requests are done through the Help -> Request a Feature menu item on the Habitica website. I'm closing this that you logged, however it's an interesting idea so I definitely think you should request it.

Read through the Help -> Request a Feature instructions first, but then the card you want is probably "CHAT (Tavern Talk Enhancements; Party Talk Enhancements; Friend List)" https://trello.com/c/LlJccgmY/293-chat-tavern-talk-enhancements

There might also be other, better cards. You can pick the one that seems closest and make your suggestion there (there's no need to duplicate your request onto others). If there's actually a better card for it, we'll let you know!
