### ISSUE TITLE
"Show chat messages in reverse order" checkbox is easy to click accidentally

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6517]
There's a few reports in the Tavern that the "Show chat messages in reverse order" checkbox can be accidentally selected when clicking on the "send chat" or "fetch recent messages" buttons.

citrusella says:

**It appears it happens most often when I approach the button from below; it seems sometimes it's catching the "hitbox" of the reverse link and not letting go when the mouse is moved to the fetch button.**

Ishmaeel says:

**I think it happens because of the tooltip. When you "approach from below", you trigger the tooltip popup (and its hitbox extends to the checkbox) and even after the tooltip appears to be disappeared (heh), it actually lingers for a while there, invisible. When you click the button, you're actually clicking the tooltip.  I can even toggle the checkbox by clicking the chat textbox: 1)hover over checkbox. 2)quickly move the mouse up and click in the textbox where the tooltip was.**

One possible fix is moving the checkbox to a region where there's no other UI elements above it.

**Comment by Alys** [comment]
More specifically, the "Show chat messages in reverse order" checkbox can be accidentally selected when clicking on the "send chat" or "fetch recent messages" buttons. 

One possible fix is moving the checkbox to a region where there's no other UI elements above it.

(I've edited my first comment to contain this info.)

**Comment by GeorgeSG** [comment]
I just checked this out. Ishmaeel is right, this is happening because the tooltip is not disappearing instantly. Clicking on the tooltip triggers the checkbox.

I think a viable solution is just to make the tooltip appear at the bottom. Or possibly try to disable the click action when hovering the tooltip?

Edit: to be clear - moving the tooltip to the bottom will just make it so this happens in the reverse direction - when moving the mouse from top to bottom and clicking somewhere in the blue Note alert

**Comment by GeorgeSG** [comment]
Actually, do we even need the tooltip? I think the label might be enough.

The idea of the tooltip was to show which pages are affected by the checkbox (when it was on the Settings page), but now every page that is affected also has the checkbox itself...

**Comment by Alys** [comment]
@GeorgeSG I think you're right! The tooltip doesn't seem necessary now and getting rid of it would be an easy fix.

Perhaps wait a few hours to see if anyone objects, and then if you'd like to submit a PR for that, please do! Or do the PR without waiting if you don't mind a small risk that it might be rejected. I don't think it would be though. (If I'm wrong, I will give you five gems. ;) )

**Comment by Ishmaeel** [comment]
Chiming in:
- Moving the tooltip to the bottom would make the mouse pointer obscure the text and it would look clunky and ugly. I'd vote for removing it completely over this solution.
- I don't think the tooltip is entirely devoid of useful information. Those who are not very computer-savvy might find the note about "the oldest are on top" helpful. I, for one, wouldn't miss the tooltip though.
- Moving the checkbox where it won't overlap with anything is the best solution IMO. However, I'd vote for removing it completely again, if this would be too hard from a design standpoint (don't forget that it should not overlap even with the chat box).

**Comment by GeorgeSG** [comment]
@Alys, I'm at work and can't open a PR to remove the tooltip in the next 6-7 hours anyway. :) So we have a few hours to see if anyone else has different ideas.

**Comment by GeorgeSG** [comment]
@Ishmaeel - you have a point about the "oldest are on top" info.

Can we reword the label itself to give that info? Perhaps `Show chat messages in ascending order` or something like that? Maybe something shorter - `Show older messages first` or `Order oldest to newest`? Another one is `Show newest messages at the bottom`

**Comment by Ishmaeel** [comment]
@GeorgeSG - Well, I'm trying to put my feet into the shoes of somebody who is relatively computer-illiterate, and both "show in reverse order" and "ascending order" sound like mumbo-jumbo to me. Best I can come up with at the moment is similar to one of your suggestions, only longer: "Sort messages from oldest to newest".

On the other hand, maybe I am overthinking it. We are living in a world where even 5-6 year olds are familiar with chatroom conventions after all.

**Comment by citrusella** [comment]
Maybe, if the tooltip is removed, the checkbox would be clearest if it read something like "reverse chat order (oldest on top)" (maybe with "messages" after "oldest"). Reasonably succinct and would explain the button fairly clearly to someone who might misunderstand "reverse"?
