### ISSUE TITLE
No Reward for Rat King Request

### ISSUE THREAD

**Issue by rebhill** [HabitRPG/habitica#6519]
Hi, My questing party "Dapper Fellows" completed the Rat King quest and none of us got the quest rewards.  

here is a copy paste of the quest being completed:

You defeated Rat King! Questing party members receive the rewards of victory. -2 days ago+1  
sethed attacks Rat King for 242.4 damage, Rat King attacks party for 0.0 damage. -2 days ago+1  
thejeffcho attacks Rat King for 15.6 damage, Rat King attacks party for 2.0 damage. -2 days ago+1  
MKS90 attacks Rat King for 31.0 damage, Rat King attacks party for 0.0 damage. -2 days ago+1  
Azuredraco attacks Rat King for 138.6 damage, Rat King attacks party for 0.0 damage. -2 days ago+1

**Comment by Alys** [comment]
I've given the quest rewards to all party members who were on that quest. They should reload if they don't see them immediately. I'm closing this now but please comment here if anything is still not right.
