### ISSUE TITLE
301 on up/down voting task?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#652]
I'm getting a 301 HTTP code when I try to use the "extension" API to up/down vote tasks.  Is this just me? Of is this an issue?

**Comment by switz** [comment]
301 is a permanent redirect, where is it redirecting to. We need more context.

**Comment by ruddfawcett** [comment]
Yeah, I realize that it's a redirect, but I'm using the proper URL scheme...

**Comment by lefnire** [comment]
Shoot us a gist, removing your apitoken

**Comment by ruddfawcett** [comment]
Remember to use HTTPS for anybody else getting this!
