### ISSUE TITLE
Typo in "Show chat messages in reverse order" tooltip

### ISSUE THREAD

**Issue by itokro** [HabitRPG/habitica#6524]
When I mouse over the new "Show chat messages in reverse order" text at the top of Habitica's chat spaces, I get a tooltip that says, "Show the messages in the Tarvern, Guild and Party chats in reverse order, so that the oldest are on top." This is a very helpful tooltip, but it would be even better if it said "Tavern" rather than "Tarvern" ;-)

**Comment by Tyler-Hilbert** [comment]
I've found where the typo is. It's in \common\locales\en\settings.json on line 14. I fixed the problem locally but can't figure out how to commit it -_-. Can someone help me with git?

**Comment by crookedneighbor** [comment]
We've removed the tooltip entirely to fix another issue. It will go live soon.
