### ISSUE TITLE
Didn't receive Mystic Hourglass

### ISSUE THREAD

**Issue by KGBoo** [HabitRPG/habitica#6529]
Hi! I didn't receive the Mystic Hourglass I was supposed to.

API: d6208b0e-a7e0-4ddd-ae0b-06a8f5853702

Thanks!

**Comment by Alys** [comment]
Sorry about that! Please reload, it's there now.

**Comment by AhoyMatey** [comment]
My 2nd year subscription automatically came, as well as the receipt over a month ago; but I never received my Mystic Hourglasses. Please help!

**Comment by Alys** [comment]
@AhoyMatey Could you please tell us your User ID? To find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by AhoyMatey** [comment]
Yes, my User ID is: 20315fb3-1053-444b-b7a3-42e8468a05ce

Thanks for helping :-)

**Comment by Alys** [comment]
@AhoyMatey I've given you the Hourglasses, and the increased gem cap, and the five gems that you would have been able to buy last month if the cap had been increased then. Reload if you don't see them. Comment here if they still don't appear.

**Comment by AhoyMatey** [comment]
Oh thank you so very much! Yes, I see them now. ~so cool! 
Thanks for helping so quickly!
