### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by LemonNerdBoy** [HabitRPG/habitica#653]
Last night I attempted to get onto habitrpg.com with my username "Muntjack" and could not get it to log in.  Whenever I clicked on the login button, I can put in my username.  As soon as I start my password it kicks the screen back to the main page.  This has continued today.  I have used 2 computers from 2 different locations.  Any suggestions?

**Comment by lefnire** [comment]
same issue as https://github.com/lefnire/habitrpg/issues/649 , follow the conversation on https://github.com/lefnire/habitrpg/issues/539 - I'm working on this specific task today

**Comment by lefnire** [comment]
fixed (see resolution on #649)
