### ISSUE TITLE
Enchanted Armoire does not change the "equipment pieces remaining" count 

### ISSUE THREAD

**Issue by camachoborracho** [HabitRPG/habitica#6534]
The Enchanted Armoire does not change the "equipment pieces remaining" count from 40 down to anything else. I excluded food and XP as a potential bug since those aren't equipment pieces, but I have gotten 4 equipment items from this but it still says 40 not 36. Same applies on the iOS app version.

**Comment by Alys** [comment]
Thanks for letting us know!

Can you please reload the website and tell us if the count is now accurate.

FYI for other devs, I've confirmed that camachoborracho owns four Armoire gear items, assuming that "camachoborracho" is also his Habitica profile name (@camachoborracho if it isn't, please tell us your User ID -- go to Help -> Report a Bug and see step 6 of the instructions).

**Comment by camachoborracho** [comment]
Hi Alys,

Yes, my avatar name is camachoborracho, and your investigation turned out to be correct. Unfortunately when I closed out of my browser and reset it, I have the 40 still:

![40 pieces](https://cloud.githubusercontent.com/assets/15842968/12374792/2846191e-bc5c-11e5-842d-edae279e837a.png)

![equipment collected](https://cloud.githubusercontent.com/assets/15842968/12374795/471bebac-bc5c-11e5-998c-8e4674b1096b.png)

**Comment by Alys** [comment]
I just checked on my account, which has all the gear. There's currently 44 Armoire items. The count is correct. :)

**Comment by camachoborracho** [comment]
Really? Weird. It had started out as 40 as I remember it initially dropping to 38 with 2 purchases, but maybe with the update a few days ago more got added and bumped up to 44? OK fair enough. Will see after the next one. Thanks

**Comment by Alys** [comment]
New items are added to the Armoire every month. You can see all of them at http://habitica.wikia.com/wiki/Enchanted_Armoire
