### ISSUE TITLE
Typo in Dailies help (?) button

### ISSUE THREAD

**Issue by Beuks** [HabitRPG/habitica#6539]
Just joined the site and love it so far. Being new is probably what helped me catch this error:

When you click the question mark (?) beside Dailies for more information about that type of task, one of the bullet points reads "Dailies turn redder when you miss them, and bluer when you complete them. The _redder_ the Daily, the more it will _reward_ you... or hurt you."

Should this instead read, "The redder the Daily, the more **completion** will reward you...and the more **incompletion will hurt you**", or something to that effect?

Edit: I did some digging and I get what the help is trying to convey now, so changed my post to suggest a way to avoid that confusion.

Cheers!
Steve Beukema aka SteviePotato

**Comment by crookedneighbor** [comment]
Actually, the redder the daily, the more it rewards you for completing it. 

See the "Other Effects" section on this article: http://habitica.wikia.com/wiki/Dailies

**Comment by Beuks** [comment]
Haha you beat me to my edit! I understand that now, I changed it to suggest a way to avoid the initial confusion for newcomers - as currently it seems that being in the red will reward you :P
