### ISSUE TITLE
Rewards header and Gold value overlap

### ISSUE THREAD

**Issue by justerhan** [HabitRPG/habitica#655]
I noticed that the Rewards header and gold overlap a bit. I'd fix it myself but I'm shy since I'm new ;) Check out screen shot.

Firefox 19.02 on OS X Mountain Lion
SHA: 905719725e8d7f63ae3dda53059fcd103fefe876

![overlap](https://f.cloud.github.com/assets/866011/261490/be29532c-8cf5-11e2-9437-c5f70c5addd0.png)

**Comment by lefnire** [comment]
Look at Erhan hanging out in the Habit repo! Welcome friend :)

**Comment by justerhan** [comment]
Thanks! Looking forward to lending a hand =D

**Comment by wc8** [comment]
Related: #37

**Comment by rixx** [comment]
Doesn't happen anymore, I think.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
