### ISSUE TITLE
Tags tooltip is misaligned compared to other tooltips

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6550]
The tooltip when you hover over the tags icon is 1px lower than the other icon tooltips.

![tags](https://cloud.githubusercontent.com/assets/9433472/12385411/c30e8faa-bdb3-11e5-877d-546b1fd07b2a.png)

![edit](https://cloud.githubusercontent.com/assets/9433472/12385414/c8e0bd72-bdb3-11e5-80ef-cab69b2c868b.png)

**Comment by DrStrangepork** [comment]
The style for that tooltip is indeed different. The tag tooltip style="top: -19.5px" while all the other tooltips are style="top: -20.5px".

**Comment by Alys** [comment]
This will be fixed in an upcoming website improvement project so I'm closing this.
