### ISSUE TITLE
Collection Quest Art: Message in a Bottle and Moonstone Chain

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6555]
We have two new pieces of collection quest art to be implemented!

Message in a Bottle, by mako413:

![message_in_a_bottle_3x_zpspxgfati2](https://cloud.githubusercontent.com/assets/3494081/12433972/cfdd9392-beb8-11e5-92a5-7707b806fbdf.png)

Moonstone Chain, by eevachu:

![themoonstonechain_300p_by_eevachu-d9o91kw](https://cloud.githubusercontent.com/assets/3494081/12433879/67f46e54-beb8-11e5-99e0-0096c3339907.png)

**Comment by kirbyblox** [comment]
Just wondering, where are the quests? I'm new. Thanks in advance.

**Comment by taldin** [comment]
@kirbyblox :  You can find the quests in https://github.com/HabitRPG/habitrpg/blob/8ee535b4fa10805e85029c80d702a9fcb2230e05/common/script/content/index.js
...or (habitrpg/common/script/content/index.js) in your local installation.

**Comment by librarianmage** [comment]
@lemoness @SabreCat @Alys Should this issue be closed?

**Comment by Alys** [comment]
@MathWhiz Thank you, yes!
