### ISSUE TITLE
Error request entity too large

### ISSUE THREAD

**Issue by lordmatt** [HabitRPG/habitica#6568]
Error triggered by attempting to join the challenge: https://habitica.com/#/options/groups/challenges/7fea221e-d48e-4a7d-ad66-9a81c87fc913

Error request entity too large.

**Comment by Alys** [comment]
@lordmatt Thanks for letting us know. This is a problem that occurs sometimes with popular challenges. We have it reported at https://github.com/HabitRPG/habitrpg/issues/1471 so I'm closing this now. Please see the text in bold at the top of that issue - in brief, it's sometimes a temporary error so if you try again it might work. If not, tell us.
