### ISSUE TITLE
hiding/minimizing character and other game-like features to make workplace use acceptable

### ISSUE THREAD

**Issue by efglb** [HabitRPG/habitica#657]
I'd like to use HabitRPG at work more, but I'm worried others in the office will think I'm playing a game if they see the header with the character, HP, and EXP bars up at the top.

Is there some way to set up a minimize feature that would still display these stats in some way while making them look less game-like?

**Comment by wc8** [comment]
Vote for [Toggle Header](https://trello.com/c/GHYcVQfD) suggestion.
You may also be interested in the discussion about [Gamification Options](https://trello.com/c/EKxy5lYI).

**Comment by ruddfawcett** [comment]
@efglb I could implement this... What is your idea as to where to position the toggle button?

**Comment by efglb** [comment]
Thanks for the quick response!

My thought is to have a little up/down combo arrow button positioned in the center of the bottom border of the header area. 

Click it once, and the top collapses into a numerical view, click it again, and it re-expands into the original character/status bar view.

**Comment by ruddfawcett** [comment]
How about this?  Keep the username in upper right hand corner.  There is an option which is toggle header (in the dropdown).  Then, the header animates out/in, with some animation type using jQuery.  Therefore, you still have the option to easily access the "username" menu, and it doesn't actually add any elements to the page.  Thoughts?

**Comment by efglb** [comment]
i'd go for that if it's quick and easy!

**Comment by ruddfawcett** [comment]
Should be.  I won't be able to start working on it for another hour, probably, though.

**Comment by caycefischer** [comment]
Toggling the header definitely doesn't need jQuery animations, we can animate with CSS for a big performance win.

I like this idea a lot.

**Comment by lefnire** [comment]
`$('#header').toggle();` is so simple though! what's the scoop there?

**Comment by caycefischer** [comment]
Definitely implement that now, 'cause it's easy and fast and gets the feature out there to users—but in the long haul I'll switch it out for a better technique. There's a few things:
- javascript/jquery isn't GPU-accelerated, and 
- is blocking

so it might be choppy (esp. on shit computers or tablets) and/or hold up other processes. Also, 
- `.toggle` uses style injection to set `display: none`

which is both messy from a code point of view, and not great for a11y.

**Comment by lefnire** [comment]
actually, scratch that we'd need to do it in derby anyway in order to save the preference across refreshes (which they have to do at work because of the memory leak): here's the starter code: commit https://github.com/lefnire/habitrpg/commit/823f524d57c37e4344ae15323033987db3a632d1 ([branch](https://github.com/lefnire/habitrpg/tree/toggle-header))

**Comment by caycefischer** [comment]
Ahh right, makes sense

**Comment by caycefischer** [comment]
So how does derby do that kind of stuff... is it `display: none`ing?

**Comment by lefnire** [comment]
pushed to `develop`, test in an hour or so. It's in the settings modal now (user -> settings). @zakkain naw, it actually removes it from html - when `{#if}` is falsy, that whole html block is removed

**Comment by efglb** [comment]
works like a charm. you guys rock.

**Comment by switz** [comment]
You could use local storage, that way the setting is per browser. i.e. your work browser the bar is always hidden, but at home the bar is visible. Plus, it's one less thing for racer to handle.

**Comment by caycefischer** [comment]
That's brilliant, @switz.

![limitless](https://f.cloud.github.com/assets/546495/266353/15ba1a32-8def-11e2-9198-f3659a4ec0c0.gif)

Simple, elegant—just brilliant!

**Comment by wc8** [comment]
Shall we close this or do we need it open for the per browser setting suggestion?

**Comment by lefnire** [comment]
We can leave it open if y'all are keen on the localStorage thing. I think
we should postpone that because it sounds like a rabbit hole to me
(potentially worth while, but we have bigger fish right now). i'll be
moving this button into the tags list, along with column-toggles, in the
near future.

**Comment by wc8** [comment]
I added LocalStorage to checklist for [Gamification Options](https://trello.com/c/EKxy5lYI). So, if you like we can close this issue and follow up (later) when Gamification Modes/Options are considered.

**Comment by lefnire** [comment]
Sounds goid
