### ISSUE TITLE
Experience Points issue

### ISSUE THREAD

**Issue by mbaumanndev** [HabitRPG/habitica#6575]
Hi !

I have an issue with my XP. I have 151xp/150xp.
Here is a screenshot.
![xp](https://cloud.githubusercontent.com/assets/499268/12539879/58d88ffc-c2fc-11e5-9ebe-7e65932d2a56.png)

**Comment by Alys** [comment]
That's an example of this bug: https://github.com/HabitRPG/habitrpg/issues/2433 - see the text in bold at the top for an explanation. You will level up when you complete a task.
