### ISSUE TITLE
Completed "Find the Cub" but did not get credited

### ISSUE THREAD

**Issue by Kfearnley85** [HabitRPG/habitica#6576]
I purchased and started the "Find the Cub" Quest. I had one other party member join. Upon completing the quest she was credited for having completed the quest and was rewarded her polar bear. I have no credit showing that i completed the quest and I did not get my polar bear :(

2230253c-ffbb-4d41-83d2-009bcb5789c1

**Comment by Alys** [comment]
Hi @Kfearnley85 

I've given you the quest rewards. Reload if you don't see them immediately. Comment here if there's still a problem after that.

If it happens for future quests, you can comment on https://github.com/HabitRPG/habitrpg/issues/4252
