### ISSUE TITLE
I did all my tasks yesterday (24/01/2016) but the system didn't save

### ISSUE THREAD

**Issue by MagnusBardon** [HabitRPG/habitica#6577]
I could have died, and now my days in a row combos were reset

**Comment by Alys** [comment]
@MagnusBardon I'm sorry about that! It sounds like you were affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313

There's an "Advice" section near the top that will help you recover from the unfair damage and losses.

If you have questions, comment here (even though I'm closing this now; we'll still see comments), or go to Help -> Ask a Question from the Habitica website's menu.
