### ISSUE TITLE
Can't feed pets

### ISSUE THREAD

**Issue by colwem** [HabitRPG/habitica#6580]
When I click on a food then click on a pet it does nothing.  I might be doing it wrong but I seem to remember that this is how you feed your pets.

UID: 041abe75-7ebc-4e11-a32d-9d54f77d74f8
Browser: Google Chrome Version 47.0.2526.111 (64-bit)
OS: OS X Version 10.10.5

**Comment by Alys** [comment]
Did you get a popup in Habitica some time in the recent past, and you ticked a checkbox on it that said you did not want to see more popups? If so, that's what's stopping you feeding your pets - you need to do the confirmation step before the food will be applied.

That checkbox is a feature that your browser implements., not part of Habitica. To reset your browser's setting for it close and reopen your browser. Ensure that all browser windows become closed before you reopen any.

**Comment by colwem** [comment]
Ah thanks, but that's still a bug.  Or at least it's really bad design and should be fixed.  Maybe use a JS popup rather than the native popup system.

**Comment by Alys** [comment]
Yes, we have a new design partially created.
