### ISSUE TITLE
Got in the inn yesterday and still lost health

### ISSUE THREAD

**Issue by AxelDornelles** [HabitRPG/habitica#6588]
As says the title, I got in the inn yesterday but lost health and even died today morning, losing a hige amount of money and when I had more than half the experience needed for the last level.
My party is taking part in absolutely no quests and, in fact, we haven't done so in the last 3 months.
I have played Habitica for a long time and that haven't happened in a long time.
Why did that happen?
What are the chances of happening again?
How can I recover what was unfairly lost?

I also managed to get some screenshots related to it, is there anywhere I can send it?

**Comment by Alys** [comment]
I'm sorry about this! I know how frustrating it must be! What would have
happened is that your browser recorded that you wanted to rest in the inn
and showed that you were, but it did not send that information to
Habitica's server, so when cron ran, it did not know that you were supposed
to be resting. It's an instance of this bug:
https://github.com/HabitRPG/habitrpg/issues/4313  There's an advice section
near the top that will tell you how to recover from the unfair damage and
losses. It also describes how you can use the Data Display Tool to check
each evening that your actions have been recorded - it speaks about
checking that Dailies are ticked but you can use the same tool to check
that you are resting.

**Comment by AxelDornelles** [comment]
Thank you very much, Alyss!
That solved my problems perfectly and further informed me to avoid future
inconveniences.
I also plan to use the correction tool to supply myself with more funds in
order to recover the equipment lost in the process without, of courser,
sabotaging myself by adding more than the strictly necessary.
Em 26/01/2016 19:26, "Alys" notifications@github.com escreveu:

**Comment by Alys** [comment]
@AxelDornelles Thanks for letting us know!

Good idea to give yourself gold for the lost equipment too!
