### ISSUE TITLE
If you have a big sword, it covers up your pet

### ISSUE THREAD

**Issue by mstksg** [HabitRPG/habitica#659]
my girlfriend bought a mace by accident and it covered her pet's whole face; this is rather unsettling and unfortunate.

**Comment by Shaners** [comment]
Awe, yea this is being worked on.

**Comment by cleave29** [comment]
refer to #500

**Comment by mstksg** [comment]
I'm not too familiar with the whole development process, but I think I have wrote in a non-hackish decent fix to this in the source code.  How would I go about suggesting my improvement/modification for review?  I am but a humble non-special man.

**Comment by lefnire** [comment]
@mstk send a pull-request against `develop`. you familiar with how to do that?

**Comment by rixx** [comment]
I think this is not an issue anymore, since pets were moved a bit downwards.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
