### ISSUE TITLE
Can't log in at all!

### ISSUE THREAD

**Issue by dalmationer** [HabitRPG/habitica#6593]
On the main page, all that happens when I attempt to log in is the little bar at the top slowly fills, then when it's finished, absolutely nothing happens.
I've tried loading the site on both chrome and firefox, to no avail! Oddly, this only seems to happen on my laptop, not on any other computer.

I will update this with my specs later.

**Comment by Alys** [comment]
On both of those browsers, clear your cookies and then go to https://habitica.com/static/clear-browser-data and click the button there. Does that help?

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see the question from my previous post, and let us know if there's any other information you can give us. We'll still see your reply and can reopen this if necessary.
