### ISSUE TITLE
Can't add people to my party

### ISSUE THREAD

**Issue by emilysrisa** [HabitRPG/habitica#6596]
I am not able to add anyone to my party via email or their unique code. I am able to click on "invite, " which then allows me to add a friend's email address, however nothing happens after that. Thanks!

**Comment by Alys** [comment]
Please log out of Habitica, close all browser windows, reopen your browser, delete cookies, and then go to https://habitica.com/static/clear-browser-data and click the button there.

Does that fix the problem?

**Comment by Alys** [comment]
@emilysrisa I'm guessing this is fixed since you haven't replied, so I'm closing this, however if you're still unable to add anyone to your party after trying the steps from my previous post, please comment here and we'll reopen it and keep helping you.
