### ISSUE TITLE
Boss Battles

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#66]
Would be awesome if there were boss battles every so often against your worst habit.

**Comment by lefnire** [comment]
Planned. Will either be, as you said, your worst habit (once a week or some
such), or the last item of a tagged set. We could even keep both, one
acting as "mini bosses"

**Comment by ghost** [comment]
A weekly boss is good and a miniboss on a irregular basis would be good.

**Comment by benmanley** [comment]
Bosses could be referred to as "Demons", since this is a battle against our personal demons after all!

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote: [Boss Battles](https://trello.com/c/WP3dXij9)
