### ISSUE TITLE
"Sticking to Your Resolutions: 2016" challenge task won't remove itself

### ISSUE THREAD

**Issue by breebrouwer** [HabitRPG/habitica#6601]
Hey, there,

I joined the Sticking to Your Resolutions: 2016 challenge last week, and then after deciding I didn't like the tasks it was bringing up, I left the challenge. Now, however, there was one task that wasn't removed: "Joined/left a guild." I tried re-joining the challenge, adding the challenge's tag to the task, and then leaving the challenge a second time. The task is still there, and I'd rather it be gone because it doesn't apply to my productivity routines.

My user ID is 7251ccaf-0862-495d-8eff-798ab1011ebb, and I'm using Google Chrome's latest version on Windows 7 Home Premium. 

Thanks!

**Comment by Alys** [comment]
@breebrouwer I've removed the task for you. If it happens with other challenges in future, see "Deleting a Challenge Task" in the wiki's Challenges page at http://habitica.wikia.com/wiki/Challenges

**Comment by breebrouwer** [comment]
Thanks, @Alys! I didn't check trying to delete via mobile, but I had already tried waiting a day to see if I had the option to delete the task and I simply didn't.
