### ISSUE TITLE
Android App: Invalid App ID: CHANGE_ME

### ISSUE THREAD

**Issue by sntk** [HabitRPG/habitica#6602]
Sign In with Facebook is broken on Android, it however works just fine on iOS. The Facebook error is "Invalid App ID: CHANGE_ME" ;)

Android Version: 0.0.25

![screenshot_2016-01-28-08-04-33](https://cloud.githubusercontent.com/assets/951859/12632844/27e597d0-c529-11e5-8d51-0e856ae135cb.png)

**Comment by rmkoske** [comment]
I dropped a mention of this issue over at the [HabitRPG - android](https://github.com/HabitRPG/habitrpg-android/issues) issues list.  It seemed related to an existing issue, so it's [here](https://github.com/HabitRPG/habitrpg-android/issues/395).

**Comment by SabreCat** [comment]
Fixed with the 0.0.25.1 update!
