### ISSUE TITLE
 try to install the cordova in in mac os x yosemite am i getting the error "npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm." 

### ISSUE THREAD

**Issue by kraom** [HabitRPG/habitica#6603]
npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

help me

**Comment by Alys** [comment]
Is this for working on the old HabitRPG mobile apps? They did use PhoneGap, now called Cordova, so I think that's what you're referring to. If so, please be aware that those apps are no longer supported and we aren't doing any more development on them, nor accepting code contributions.

We have two native apps now, with the source code available at https://github.com/HabitRPG/habitrpg-android and https://github.com/HabitRPG/habitrpg-ios. If you're interesting in contributing, please do!

If this isn't relevant to the problem you've reported here, can you please give us more information about what you're trying to do?

**Comment by crookedneighbor** [comment]
Regardless, that message is from a dependency of a dependency of the project. It is a warning, not an error. If you're having issues, it's almost certainly not related to that message. 

Closing this now, but feel free to re-open this issue with more details if you're having trouble.
