### ISSUE TITLE
Extra crons when finishing, starting quest on same day

### ISSUE THREAD

**Issue by jpazniokas** [HabitRPG/habitica#6606]
This seems fairly minor, because the damage done is usually very minimal, but in case it's been noticed by others:

On the (rare) days when we are so on-the-ball that we start a new quest on the same day that we completed the last one, one party member usually triggers a spurious cron in the middle of the day, or so it appears from the party chat.  

As an example: yesterday, we finished the Kraken and started the Harpy.  The Kraken ended on my cron, around 5:30am, and everyone logged in over the next few hours to accept the Harpy quest, which started at around 8:30am. Less than 12 hours later, one party member "attacks Harpy for 0.0 damage, Harpy attacks party for 0.9 damage," per the party chat.  Still the same day as the quest acceptance.  (She has a lot of dailies, so it wasn't a full cron.  She and the harpy couldn't have combined for only 0.9.)

This is at least the third time I've noticed it, and in each case, it was on a day where we ended a quest and immediately started another one.

Just thought I'd post it.

**Comment by Alys** [comment]
This doesn't necessarily indicate a problem. Even though her cron happened at the middle of the day for you, it could have been early in the day for her. The fact that she caused only 0.9 damage to the party indicates that she'd done almost all her Dailies, so it looks like a normal cron. Doing 0 damage to the boss just means that the quest started after she'd finished her tasks for the day.

Please ask her if she thinks that her cron is running at the wrong time. If she does, she should post here and include her User ID and her party's Group ID (to learn how to find them, she can go to Help > Report a Bug and see step 6).

**Comment by jpazniokas** [comment]
Oh, interesting.  I thought that the boss damage was calculated just at cron.  I didn't know there was a concept of "before/after the quest started," within the same day.  Good to know.

That said, she should have had a cron earlier in the day, when she logged in.  Right?  She had to have logged in to accept the new quest.  There's no party-chat log of her cron, because it happened after my quest-ending cron.  But her profile did indicate she'd logged in that day, prior to the 0.0/0.9 cron.

**Comment by Alys** [comment]
@jpazniokas Boss damage is calculated only at cron. When you see a boss damage message, that person definitely cronned at that time.

"She had to have logged in to accept the new quest." -- Yes. However that doesn't mean she cronned then.

When she crons depends on what her Custom Day Start time is (midnight is the default but she could have changed it to anything else) and what timezone she's in. If she's in a very different zone than you, then she will cron at a very different time. Accepting the new quest might have been earlier in the day from your point of view, but might have been yesterday from hers.

**Comment by jpazniokas** [comment]
Sorry, I didn't respond to that conjecture: same timezone.  (Same house, actually.  Same room.  She's my wife.)

**Comment by Alys** [comment]
Please ask her to post here and include her User ID and the party's Group ID (to learn how to find them, she can go to Help > Report a Bug and see step 6). To help with this we'd need to examine her account and talk to her about it.

**Comment by taldin** [comment]
The other thing that can happen is if she's left herself logged in somewhere and her auto refresh triggers cron -- or if she accepted from a mobile device.   Our party had one person who logged in for the first time late in the day (triggering the previous day's cron) and then was still logged in after midnight (their cron time) and when they did something, it updated their cron again, so they had two crons process within 5 hours of each other.   Your cron never processes while you're not logged in, but it does process immediately once you do for the first time that day, no matter when in the day it is.

**Comment by Alys** [comment]
@jpazniokas I'm going to close this now but if your wife is still having trouble with cron, she can post her User ID here (from Settings -> API) and we'll do whatever we can to help!
