### ISSUE TITLE
Double invited to party, application errors on party page

### ISSUE THREAD

**Issue by deadmonkies** [HabitRPG/habitica#6607]
I was invited to join a party with a group of friends and got several application errors during signup and joining the group. I've logged out and logged back in, tried different browsers and different computers. Now, when I view the party screen, it shows me as both a member of, and also invited to this same party. I cannot decline the second invitation or I get an application error. If I accept the second application (which to my understanding should make me leave the party and re-join it) I still see the extra invitation. I don't get any application errors using the android app. Just the web interface. 

list of computers I've tried on
Windows 7 running firefox, chrome, IE

Windows 10 running chrome and IE

User ID: 538556a8-4f92-4ac2-a8a7-f24ab9306fd7
Group ID: f60bca5b-79c3-42af-8298-9144f477085e

**Comment by Alys** [comment]
I've removed the invitation but please see the text in bold at the top of this issue: https://github.com/HabitRPG/habitrpg/issues/5649
