### ISSUE TITLE
Accepted a quest, using skills, but not a participant?

### ISSUE THREAD

**Issue by lightlines** [HabitRPG/habitica#6608]
Hi, 

I hope I'm reporting this right. I was invited to join a party, which I accepted, and have been casting skills (?) for the party, which show up, but my dailies aren't doing damage and nothing like 'username did x damage to the boss' is coming up? In the app, I'm a participant, but in browser I'm just a member. What do I do?

Thanks!

**Comment by Alys** [comment]
We'll need to be able to identify your account and the party to help you with this. Please go to Help > Report a Bug and see step 6 of the instructions.

**Comment by lightlines** [comment]
Apologies, I read that and then forgot to put it in! 4faa74d6-061e-4384-bb9b-a9c139ef06e2 is the User ID. I'm using Chrome/the latest iOS

**Comment by Alys** [comment]
No worries. :)  You actually aren't a participant of the quest. The quest owner must have started the quest before you could accept the invitation, or you joined the party after the quest had started.

The quest owner can, if they wish to, abort the quest. The scroll will go back into their quests page and they can use it to restart the quest. They should not click the "begin" button on the quest until you have accepted the invitation.

If the app is showing you as a participant, please take a screenshot and email it to mobile@habitica.com. Please include the URL of this issue which is github.com/HabitRPG/habitrpg/issues/6608#issuecomment-176278405

**Comment by lightlines** [comment]
Thanks! That's so odd - I accepted the invite before the quest started :( I've sent the screenshots to that email; it says '2' participants - I clicked on it and there are 7! Odd bug. 

Thanks for your help.

**Comment by Alys** [comment]
That is odd. Could you please check your User ID on the app? If it's not the same as 4faa74d6-061e-4384-bb9b-a9c139ef06e2, please let us know what it is. On Android, you can see it at Settings > Account Details. I'm not sure where it is on iOS but it should be somewhere similar.

**Comment by ghost** [comment]
I'm having this same trouble, and am pretty sure I accepted the invite from the iOS app before the quest started.

My iOS app shows me as a participant, but the website only shows me as a member.

My User ID is f00405f3-b64b-49f2-b165-56e38b7ad006 on both the website and in the iOS app. Should I send the screenshots as mentioned above?

**Comment by Alys** [comment]
@mymble I've checked Habitica's database and you are not a participant in the quest.

If the app is showing you as a participant, please take a screenshot and email it to mobile@habitica.com. Please include the URL of this issue which is github.com/HabitRPG/habitrpg/issues/6608#issuecomment-176278405. No need to send a screenshot from the website.

The quest owner can, if they wish to, abort the quest. The scroll will go back into their quests page and they can use it to restart the quest. They should not click the "begin" button on the quest until you have accepted the invitation.
