### ISSUE TITLE
Usernames with periods are not-taggable

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#6609]
I am in a party with a member called "loop.rw". Trying to type "@loo..." does not result in his name showing up in autocomplete (only mine).

I have not dug deeper to confirm the cause, but I suspect it is failing because of the period.

**Comment by Alys** [comment]
I think the autocomplete reads from players who have posted to chat. Has that person posted any messages recently? Or any at all?

I've just tested in the Tavern and autocomplete worked on a name with a . in it.

**Comment by colegleason** [comment]
Nope, that's the problem. Please excuse my ignorance.

**Comment by Alys** [comment]
I wouldn't call it ignorance! It's not an obvious thing. :)
