### ISSUE TITLE
add party stats (hp, exp) to avatars

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#661]
I added party stats ([screenshot](http://gyazo.com/5ae54cb3727b8d2a67e66e37a7a1b6dd.png?1363363257)) to [this branch](https://github.com/lefnire/habitrpg/tree/party-stats). What do you think @zakkain , too cluttered? Should I put the stats in a popover? Re-work floats to get lvl & stats to show on one line?

**Comment by lefnire** [comment]
in develop (modal)

**Comment by caycefischer** [comment]
@lefnire Too cluttered for the current header, but as we re-do the header and get stuff more organized, I think having something like this would be great. A **Party** modal is definitely the way we're headed I think, similar to the Inventory or Stable.

I think _for now_, a tooltip showing this info would be really cool. Like @ruddfawcett said, hover on a party member and this popover comes up.

**Comment by lefnire** [comment]
Pushed, this should be showing up on beta.habit in 30m or so
