### ISSUE TITLE
Quest invite refuses to go away

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6613]
Every time I reload Habit, the quest invite modal pops up. Regardless of what button I press, the next time I reload it pops up again. I've tried clearing local storage/cookies with the 'clear browser data' page, but nothing changed. There are several JS errors, which I'll post below.

Before pressing 'reject':

![image](https://cloud.githubusercontent.com/assets/9433472/12670130/dece194c-c65d-11e5-993e-1faa4e8c9dc2.png)

After pressing 'reject':

![image](https://cloud.githubusercontent.com/assets/9433472/12670132/eb9134b6-c65d-11e5-9934-01eaff3e25b7.png)

User ID: `0e1d15f7-f36b-4f15-a9e1-0c31b732dac9`

Browser/OS: Chrome 47/Ubuntu 14.04

**Comment by Alys** [comment]
I've deleted the quest invitation. Comment here if it comes back.

**Comment by keysmashes** [comment]
Cleared local storage again and it's gone! Thanks :)
