### ISSUE TITLE
PayPal Subscription callback request hanging

### ISSUE THREAD

**Issue by confuser** [HabitRPG/habitica#6616]
Trying to subscribe to the 12 month option through PayPal.

However, after agreeing to the subscription on PayPal, it appears to hang on a request to `https://habitrpg.com` until it eventually times out.

**Comment by Alys** [comment]
Sorry about this!

If PayPal has taken the payment from your account, please forward the receipt to admin@habitica.com and include the link to this issue: github.com/HabitRPG/habitrpg/issues/6616 . If you didn't get a receipt, email us anyway and tell us which email address you use to log in to PayPal. Please also include your User ID (see step 6 of Help > Report a Bug).

If the money hasn't been taken from your account, could you please wait a few hours and try again. The timeout should be just a temporary problem. However comment here if it happens again.

Thank you for trying to support Habitica. :)

**Comment by confuser** [comment]
All sorted. Thanks :+1:
