### ISSUE TITLE
Disappearing dailies

### ISSUE THREAD

**Issue by melodiesonmusic** [HabitRPG/habitica#6619]
Whenever I save a daily after editing it, it disappears. I can't find it under any of the tabs, but it shows up in my data display tool.

**Comment by Alys** [comment]
Click the tag's "clear" button and delete any text that might be in the search box above the Rewards column. Do all your tasks appear now?

**Comment by melodiesonmusic** [comment]
Yes! They do.

Thank you :) I feel silly and relieved now

**Comment by Alys** [comment]
No worries. It's not an uncommon question. :)
