### ISSUE TITLE
Alert comes back randomly even if dismissed

### ISSUE THREAD

**Issue by mrafaeldie12** [HabitRPG/habitica#6622]
Sometimes when opening the Habitica main page the alert comes back even if perviously dismissed.

Using Chrome on Windows.

![image](https://cloud.githubusercontent.com/assets/1855740/12697879/c0f20966-c774-11e5-8600-350cf3a950a7.png)

**Comment by Alys** [comment]
Are you certain you've dismissed it by clicking on the orange button, not the white one? Sorry, I know it sounds obvious but I have to ask to be thorough. :)

Has this happened with previous Bailey messages? Roughly how often has it happened?

**Comment by mrafaeldie12** [comment]
@Alys 

Yes I have dismissed this alert several times. I don't know the criteria to make it re-appear.. but sometimes when switching computers/rebooting/opening up new windows it appears again.

This has happened with every single message in habitica since i joined. I notice this also happens to other people I know as well (not the only one thankfully

**Comment by paglias** [comment]
Should be fixed now that we don't use local storage anymore
