### ISSUE TITLE
Scroll Bar is Appearing in front of everything on Chrome

### ISSUE THREAD

**Issue by Luthien22** [HabitRPG/habitica#6623]
For the past couple of days on Habitica, the scroll bar has been appearing on top of everything. Here's an image for reference:

![image](https://cloud.githubusercontent.com/assets/10780745/12698152/81fccffe-c763-11e5-8dd2-0083176bd682.png)

I tried clearing my browser cache, as well as using https://habitica.com/static/clear-browser-data, but the problem still persists.

**Comment by keysmashes** [comment]
Seems like a Chrome problem, similar things happen to me all the time when I have overlay scrollbars enabled in chrome://flags (but for reference, that experiment isn't available on Mac). Did you install/update any extensions recently? Does it happen in other browsers?

**Comment by Luthien22** [comment]
Sorry it took me so long to get back to you. I tried Habitica on Firefox, and the scrollbars acted normally, so this is probably a chrome problem. I'm on Mac, so it shouldn't be chrome://flags. To my knowledge, I haven't updated any extensions lately, and I know I haven't installed any new ones recently.

**Comment by keysmashes** [comment]
Looks like it is a Chrome issue: https://stackoverflow.com/questions/16874546/strange-z-index-behavior-with-scrollbars-under-chrome

If scrolling the yellow part of [this jsfiddle](https://jsfiddle.net/kvNFW/) causes the same problem (and looks like the image below), it's definitely a problem with Chrome.

![image](https://i.stack.imgur.com/V61dh.png)

**Comment by Luthien22** [comment]
It's acting the same way on the jsfiddle, so it seems chrome is the issue. How do I fix this?

**Comment by taldin** [comment]
It's not happening for me on my Chrome (Windows) installation, even on the jsfiddle.  What's your hardware/OS setup?

**Comment by Luthien22** [comment]
I'm running Mac OS El Capitan on a 2013 Macbook Pro.

**Comment by keysmashes** [comment]
@taldin Does it happen if you enable overlay scrollbars in chrome://flags?

**Comment by taldin** [comment]
Nope.   Doesn't happen to me; might be a Mac thing, possibly.
![image](https://cloud.githubusercontent.com/assets/9312226/12732468/91f54a70-c8ea-11e5-97f8-d422327d3581.png)

**Comment by rmkoske** [comment]
As a datapoint: I don't think I'm seeing the fiddle error either.  Mac version 10.7.5 Chrome version 48.0.2564.97.  (I say "don't think" because my screen doesn't look like what @taldin posted.  The scrollbar vanishes completely behind the red box. It's half-way down in my screenshot.)
![scrollbar screenshot_small](https://cloud.githubusercontent.com/assets/16406613/12784255/020c1568-ca54-11e5-851b-c69f17fd4d09.png)

(Edited to add a missing word)

**Comment by crookedneighbor** [comment]
I see the JSFilddle (mac 10.10.5) weirdness, but have no problems on the website.

**Comment by Luthien22** [comment]
I'm not sure what happened, but the problem seems to have resolved itself on Habitica. I'm not having the scroll bar issues anymore. However, the JS Fiddle is still showing the error.

**Comment by librarianmage** [comment]
Is this still a problem?

**Comment by Alys** [comment]
I haven't seen recent reports of this, and it seems to be resolved for the people here, and we'll be redesigning the client code, so I'm closing this.
