### ISSUE TITLE
Missing  Mystic Hourglass?

### ISSUE THREAD

**Issue by crystalphoenix** [HabitRPG/habitica#6627]
I have been a subscriber ever since subscriber items were started. When the yearly subscription became an option, I did that for one year. This past December, I unfortunately had to stop my subscription because my financial situation changed. As I recall, I did not spend all of my allotted Hourglasses. I had bought up all of the Time Travelers exclusive items, but it left me with some Hourglasses since I already had all past items. But when I decided to check the shop, I don't seem to have any Hourglasses to use. The cessation of my yearly subscription was done through email because I didn't realize the renewal was coming up, so it was refunded. Can someone check if I am indeed missing items?

User ID: 52dc70a2-896e-4537-b306-4b449ba196e5

**Comment by Alys** [comment]
@crystalphoenix I'll download a database backup to examine your account from last December. Please note that this will take some time because the backups are very large. I'll post again here as soon as I have some information about this.

**Comment by Alys** [comment]
@crystalphoenix I've given you five Mystic Hourglasses, which is how many you had in December shortly before you asked us to cancel your recurring subscription. Please reload if don't see them immediately.
