### ISSUE TITLE
Instead of leveling up, the experience bar keeps counting

### ISSUE THREAD

**Issue by Codemon72** [HabitRPG/habitica#6628]
![bildschirmfoto 2016-01-31 um 10 15 55](https://cloud.githubusercontent.com/assets/16984175/12701249/dd0b56e0-c803-11e5-8993-e70e668221fd.png)

4e73c359-4230-4b94-b37b-be832e5aa648

using chrome and osx

**Comment by Alys** [comment]
You'll level up as soon as you complete a task or click a positive Habit.

**Comment by Codemon72** [comment]
Thank you, Alys!
I thought I had done that already, but it worked.
Cheers, Ugyug

2016-01-31 10:23 GMT+01:00 Alys notifications@github.com:
