### ISSUE TITLE
De-leveling -1XP, Level Unchanged

### ISSUE THREAD

**Issue by caycefischer** [HabitRPG/habitica#663]
If you check a Daily and level up, and then un-check it, this happens:

![Screen Shot 2013-03-15 at 2 44 20 PM](https://f.cloud.github.com/assets/546495/264937/77ec53a4-8da0-11e2-8eb8-2b99d3aea12c.png)

My level is still 8, not 7, but my XP is displayed as -1.

**Comment by rixx** [comment]
I've had this happen, too, but thought it was intentional, since levelling down would be difficult - e.g. what to do with the HP you gained when you got the level up? I thinkit might be kind of complicated to take them away again, but leving you with full HP doesn't seem right, either.

**Comment by Alys** [comment]
There are some comments about this issue at https://github.com/HabitRPG/habitrpg/issues/5736#issuecomment-127677025 and below. In brief, we believe it's simpler, more obvious to the players, and less bug-prone to allow negative XP after unticking a task than to reverse a level-up.
