### ISSUE TITLE
Cron - Dailies reset, no boss damage and buffs don't reset. 

### ISSUE THREAD

**Issue by kawunngg** [HabitRPG/habitica#6632]
Hello all,

i noticed this some days in a row now... my dalies reset normally. when my party was in a quest i did not do any boss damage, neither did the boss damage my party, it just wasn't counted. no message in the party chat, i wasn't in the Inn and i also checked if my damage happened at an other time (like accidental log in with the app or something).
but the buffs also don't reset which is really tiring because now i level up almost every task i finish... 

an other topic and i will add this to trello soon, i'd be happy if there was a reset buff button, because my party is buffing like mad sometimes ;)

my User ID: ce935e7f-00e6-44bc-a44a-5280553810f0
Firefox 34.0.4 on Win7

thanks guys!

**Comment by Alys** [comment]
Hi @kawunngg.

Firstly, I think the reset buff button is a great idea and well worth suggesting. It could go on the Fix Character Values screen, and we could also have something that allows you to add Perfect Day buffs for those cases when a bug prevents all your Dailies being recorded correctly.

The problem where you are in a quest but don't do any boss damage is something that happens sometimes. It's because when the quest starts, Habitica doesn't correctly update your account to indicate that you are in a quest. We can fix that when it happens, although it's not something we can investigate after the quest has finished, unfortunately - all the evidence is gone by then.

It looks like you are properly in the current quest. Was it a previous quest that the bug happened in?

If you notice yourself not doing quest damage again, tell me so that I can examine the state of the quest data in your account. It is also possible that you're being affected by a different new bug, so I'd love to know as soon as it happens again.

Buffs not resetting is worrying. That's not something we've seen before (unless it's a weird thing that local storage is doing). Are you certain that they don't reset? Could it be that high-powered players in your party are casting a very large number of buffs very often so that even when your buffs do reset each day, they build up again quickly? The next time you cron, could you please go to your User -> Stats page straight away and if there are any buffs recorded there, take a screenshot of the Attributes section, then reload the page, then take another screenshot if the buffs have changed.

**Comment by kawunngg** [comment]
hello Alys! 

the quest i talked about ended and i got all the rewards. in the current quest i already did some damage, it looks normal. unfortunately (in this case) we're pretty fast with quests, but i will report if i notice it again.

we have some people in our party casting a lot of spells. seems like tonight i opened the habitica app accidentally after my cron time, even though i can't renember, but i did boss damage 5 minutes after my cron time, 3 am. so i could not check properly what happened in the morning. 

i have very high INT right now, but a party member casted a lot of etheral surges since cron. so today everything could be ok. 
but the last mornings i noticed very high buffs too, with a big jump from day 1 to 2. might be coincidence. day 1 there was no quest going on, day 2 i did no damage. day 3 was without a quest.

not renembering to use the habitica app (android) makes me wonder if something happened since the app update some days ago that it logs in or something and triggers my cron. but i'm just thinking aloud, it's possible that i opened the app and just don't renember because i was half asleep. but it would make some sense if i would have collected all the buffs between my day start time and me getting up and it would also explain why i did not do any boss damage. the quest started between my day start time and me getting up. 

i will have an eye on this with this possibilities in mind.

**Comment by kawunngg** [comment]
same same. i woke up, had already some buffs, but clearly not as many as yesterday. i checked the party chat, i cronned shortly after my day start time at 3am. so seems like there is nothing wrong with my buffs. but i definitely did not touch my mobile phone tonight. 
i only use my computer (it was off tonight) und my smartphone to access habitica. i have both the old and the new apps installed, but since the old one did not change, it must be connected to the new habitica app?

**Comment by Alys** [comment]
@kawunngg Thank you for all that information! There definitely does seem to be something triggering cron very early in the morning.

Maybe it's possible that the Android app is running in the background and updating its data, which would cause cron. I'll ask our mobile devs about that.

Do you use any third-party tools? I.e., anything that you've put your User ID and API Token into? If so, those tool(s) might be running in the early morning and triggering cron. For example, do you use Beeminder's Habitica goals? Or a browser extension that can do plus/minus "clicks" on your Habits?

The Data Display Tool can't cause this, unless you've set up something in your browser to automatically reload the tool and automatically log in (that would be a bit tricky to set up so if you don't recall doing this, then I'd say you definitely haven't).

**Comment by kitsunami** [comment]
I'm also having this issue. Still on a quest for several days with no boss damage. I don't use any 3rd party tools, and am not currently using the app, either.

User ID: f79460b8-c54d-4f48-82bf-339411caa06d

**Comment by Alys** [comment]
@kitsunami when the quest started, your account wasn't updated to contain the correct quest information. I've updated it now. The next time you cron, you should see a progress message in party chat showing damage that you've done to the boss. Comment here if you don't.

**Comment by kawunngg** [comment]
sorry for the late feedback!

it was beeminder that caused cron. i neglected it a while ago, so i did not think much about it... sorry!
~two weeks ago came that mail that beeminder has changed the way they treat habitica tasks and i had a look at it, so my beeminder goal was active again. i archived it and of course everything is normal now.

i don't renember that beeminder caused cron at unwanted times when i used it in the past. also i did not found where i could change the time beeminder checks my progress, but this could as well be my fault.

**Comment by Alys** [comment]
@kawunngg Ah, yes, Beeminder would have triggered cron. Thanks for letting us know!

If you ever want to start using a Beeminder goal again and want to adjust the time, ask me then. The Beeminder folks are currently making a lot of improvements to how the settings are handled and displayed, so anything I told you now would likely be outdated later. :)

**Comment by amisme** [comment]
I am seeing this issue also. I am on a quest with my party but I am not contributing to boss damage.

User ID: 33f8cf75-df38-4048-a66e-86e55e7a68ac

**Comment by Alys** [comment]
@amisme Your account had not been updated correctly by Habitica when the quest started. I've fixed that now. You should see a quest progress message tomorrow morning - tell us if you don't!

**Comment by DonMiti** [comment]
Good day Alys.
Please assist in updating my account too. I too have the same issue.
d9a57a32-1fb9-46ee-abb2-cc49171a68d6.
Thank you, I appreciate it.

**Comment by Alys** [comment]
@DonMiti You don't seem to be in a party or in a quest. Can you tell us please what's going wrong or what needs to be updated inn your account?

**Comment by Alys** [comment]
@DonMiti Sorry, ignore my previous comment! I was looking at your data using a broken script. You definitely are in a party and in a quest. 

There seems to be something odd with your party. We are looking into it.

**Comment by crookedneighbor** [comment]
@DonMiti While helping with this issue https://github.com/HabitRPG/habitrpg/issues/7574#issuecomment-222981954, I inadvertently removed some data from your party.

I've restored the data from a few days ago, but you may be missing some chat messages. I can download a more recent backup and restore the chat messages from that, if you'd like. 

I'm also sending you 4 gems for the inconvenience. So sorry about this!

**Comment by crookedneighbor** [comment]
@DonMiti I've added back in the missing chat message.

**Comment by DonMiti** [comment]
I appreciate all the time you put into fixing the problem. Thanks a lot.
Habit really helps me keep my life in check. You are doing amazing work.

Regards.
