### ISSUE TITLE
Large tasks are difficult to rearrange

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6633]
When a task has many checklist items, dragging it to initiate a rearrange results in all tasks below it moving up by the size of the checklist (i.e. the large task only leaves a regularly-sized gap in the task list). This makes it difficult to see where the task will end up.

Moving a normal-sized task:

![image](https://cloud.githubusercontent.com/assets/9433472/12724680/f0afc844-c906-11e5-8524-afcf75255638.png)

![image](https://cloud.githubusercontent.com/assets/9433472/12724646/b8771bd0-c906-11e5-9caf-d46f85129a7f.png)

Moving a task with many checklist items:

![image](https://cloud.githubusercontent.com/assets/9433472/12724671/deafb9ce-c906-11e5-9c95-d569bcf0747e.png)

![image](https://cloud.githubusercontent.com/assets/9433472/12724674/e53e0bc4-c906-11e5-97e7-ac45d43ae410.png)

**Comment by Alys** [comment]
Click on the checklist number indicator (0/7) to collapse the checklist.
Dnes that help?

**Comment by keysmashes** [comment]
Yep, that works :) Thanks!
