### ISSUE TITLE
Paypal Subscription issue..?

### ISSUE THREAD

**Issue by Cartogenic** [HabitRPG/habitica#6634]
Hello, 

Today I bought 20 gems (5$), and everything worked fine.

Then I decided to subscribe (5$ / mo) using paypal, and the subscription was activated in the website, but paypal doesn't show any payment.

Do I only get billed after the first 30 subscription days? Paypal shows 0.00$ billed for this first month, but says there's a currently active 5$ monthly recurrent payment, so It looks like in a month from now I'll get billed the first payment..?

I created account yesterday, my user UUID is -(not needed anymore so removed).

Also, what happens if I have no funds in paypal (and no bank account associated and no credit card?). I do have credit card associated with paypal, but I'm just wondering what happens in case there was no fund or backup payment option in paypal,, would the subscription be cancelled, or would paypal balance go negative and I'd owe money to paypal?

Thanks in advance.

**Comment by Cartogenic** [comment]
nobody answered...oh well, but I got billed 5$ now on paypal, so everything seems fine.

**Comment by Alys** [comment]
Thank you for letting us know.

Please be aware that in general, it can take us some time to respond to bug reports, especially when an error is in your favour and so isn't urgent for you. I was intending to start investigating this later tonight.

To answer your questions: You are normally billed as soon as the subscription is created; I assume in this case that there was a delay in PayPal. If you have no funds in PayPal and no means of PayPal extracting funds, then each month's payment will be added to the next month, until funds are available. When funds do become available, all the payments are extracted at once, so one month you would find that the payment is a multiple of $5.

**Comment by Cartogenic** [comment]
So basically, I'll start owing paypal in case I have no funds?
Thank you!

**Comment by Alys** [comment]
No, you'll start owing Habitica. PayPal won't give us money until it can extract money from your account.
