### ISSUE TITLE
Dailies checked, but considered not checked

### ISSUE THREAD

**Issue by KGBoo** [HabitRPG/habitica#6637]
Few people in my party noticed that sometimes, we check all our dailies, but when we sign up the day after, we lose points from the boss. For example, last friday I did all my stuff, but we lost 17 points on the boss, when I signed up on saturday morning. Also, the dailies from the day before were still checked. The sync worked, because I used Brutal Smash many times and it worked.

**Comment by KGBoo** [comment]
My user ID : d6208b0e-a7e0-4ddd-ae0b-06a8f5853702

**Comment by Alys** [comment]
I'm sorry about this! You've been affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313
Please see the "Advice" section near the top for how to recover from unfair damage and how to try to avoid the bug. You can comment here if you have questions.
