### ISSUE TITLE
only 25 gems to buy this morning

### ISSUE THREAD

**Issue by KGBoo** [HabitRPG/habitica#6639]
Hi! When i signed in this morning, there was only 25 gems to buy in the market. I'm supposed to have 35. 

User ID: d6208b0e-a7e0-4ddd-ae0b-06a8f5853702

Thanks!

**Comment by Alys** [comment]
Your account in the database shows that you've bought 35 gems. 

If there still seems to be a problem, can you give us some more details about what you've noticed with the gems available to be bought over the past couple of days? For example, how many gems were showing as purchasable yesterday?

**Comment by KGBoo** [comment]
Few days ago, around Jan 26th, I noticed I had few gems to buy from january. I bought them all. May be they were considered as february gems?

**Comment by Alys** [comment]
They wouldn't have been considered as February gems.

So are you absolutely certain that in January you bought all the gems available?

**Comment by KGBoo** [comment]
Yes, absolutely certain, since we are Feb 1st...

**Comment by Alys** [comment]
The gem cap resets in the first three days of the month so it might not have reset yet (see the message in the screen you get to when you click on the gem in the header; you can also see it if you try to buy gems after they are all bought).

However the date isn't relevant to my question - are you certain that you bought all the available gems in January? When you looked at the gem icon in the Market yesterday, did it say there were zero gems available, or did it have a different number?

**Comment by KGBoo** [comment]
It said zero yesterday.

**Comment by Alys** [comment]
That means that the gem cap must have reset already this month, since there were gems available to buy today. The database is definitely showing that you've bought 35 gems. Do you have a screenshot of it saying 25 gems this morning? Does it say zero gems now?

**Comment by KGBoo** [comment]
It says zero right now. I don't have the screen shot, because I thought it would have no value, I could have already bought some gems.

**Comment by Alys** [comment]
I think it must have just been a display problem. Possibly the website was showing an old cached version of the page that said only 25 gems were available. Because it said zero yesterday, and you were able to buy gems today, and the database says you've bought 35, it looks like the gem cap was 35 (the value shown on the website wouldn't have affected that). Were you buying a lot of gems at once? Did it seem like you were able to click on the gem icon more than 25 times?
