### ISSUE TITLE
re-establish tooltips & popovers when page is redrawn

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#664]
I thought I was covering my tracks well enough by listening to `app.on('render')` and setting up tooltips & popovers [from there](https://github.com/lefnire/habitrpg/blob/master/src/app/browser.coffee#L205), but they still disappear periodically. Something's calling a page redraw and that I'm not listening for (note to self, check into `bulkUpdate`)

**Comment by Gooseus** [comment]
Hey Tyler... I had a nifty little script that I was running i another project to re-initialize pop-overs/tooltips and any other bootstrap components:

``` javascript
        var initializeComponents = function($el) {
            $el.find('.tool-tip').tooltip();
            $el.find('.nav-tabs').tab();
        }

        setInterval(function() {
            $(document).find('.js-unbound').each(function(i,el) {
                var $el = $(el);

                $el.removeClass('js-unbound').find('.js-unbound').removeClass('js-unbound');
                initializeComponents($el);
            });
        }, 300);
```

There are probably more elegant ways to do things, but I've also found it tricky to track down every instance of a redraw.  Of course, this method requires that you add "js-unbound" or some other DOM hook to any dynamic HTML section and make sure it's always redrawn with that class.

**Comment by lefnire** [comment]
I thought about that - having an interval based re-tooling. We may in fact use that solution, but I wanna last-resort if possible. 

`app.on('render')` should be triggering every time a redraw is invoked, but it doesn't seem to be the case - it seems to only trigger on the first draw. This would be the optimal place to hook into, and I think it's being called multiple times throughout the page cycle dude to `model.emit('bulkUpdate')`

**Comment by lefnire** [comment]
https://github.com/lefnire/habitrpg/pull/757 might be the fix! I'll take a look at this soon

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
