### ISSUE TITLE
Signed for a 12 month subscriber plan, but stop receiving gems at the 3rd month

### ISSUE THREAD

**Issue by zefisio** [HabitRPG/habitica#6641]
Hi,
I signed for a 12 month subscriber plan in December 2015, but I didn't received my gems on this month (February 2016)
ID: babf1497-3bf6-46d9-b1c3-a16fe7113a9c
I am using safari (Mac iOS)

**Comment by Alys** [comment]
It looks like you cancelled the subscription after buying it but the cancellation took effect far too early. I've fixed that for you now, but please check and comment here if anything still doesn't work correctly or looks wrong.

**Comment by Alys** [comment]
Actually, there's no sign in PayPal of a cancellation, although it looks like it was cancelled in Habitica. Did you try to cancel the subscription after creating it? E.g., if you wanted to subscribe for only 12 months and not have it renew automatically?

**Comment by zefisio** [comment]
Hi Alys,

I cancelled only on paypal. I did nothing on habitica. Actually, I don't
even know how to canceal the subscription on habitica.
I will check now if everything is ok. If it is, I will post it.

Many thanks!

**Comment by Alys** [comment]
To cancel a subscription, you can go to the same place where you made it - either Settings -> Subscription or the gem in header (which will then direct you to Settings -> Subscription).

**Comment by zefisio** [comment]
Everything fine now! Many thanks
