### ISSUE TITLE
Images way too big and group missing (Firefox)

### ISSUE THREAD

**Issue by artemisclyde** [HabitRPG/habitica#6643]
The images are normally sized on chromium tho.

![share_temp](https://cloud.githubusercontent.com/assets/16636453/12752091/fa0d3e84-c9c0-11e5-8f9c-9736fa4f1d58.png)

I already tried **restarting** firefox and my computer, **deleting local data**, **disabling addons**.

**Comment by Alys** [comment]
Please reload the site and check your browser's zoom settings.Does that
help?

**Comment by Alys** [comment]
@artemisclyde  I'm closing this but if you still need help, please see my previous comment.

**Comment by artemisclyde** [comment]
Sorry, haven't checked this in a week.
So the problem seems to be that the character-avatars don't resize responsively in firefox.

I usually have a browser zoom of ~75% for habitica to have a good view on all tasks. On my chromium, the avatars resize properly, on firefox it screws up the whole avatar bar.

**Comment by Alys** [comment]
I can't replicate this on Firefox unless I have the "zoom text only" option turned on (in which case not adjusting the sizes of images is correct). Is that turned on in your browser? If so, can you try turning it off?

**Comment by artemisclyde** [comment]
A-mazing. You just helped me out big time, my fault. Thank you very much!
