### ISSUE TITLE
Bought seasonal equipment then later it disappeared and the gold was refunded

### ISSUE THREAD

**Issue by Vataro** [HabitRPG/habitica#6644]
Last night I earned enough to purchase the Sorcerer's Snowboard, and happily did so. However, when I logged in this morning, I no longer own it (and I have the gold back). I'm using Chrome on Windows, though this seems to be more of an account issue than a browser issue (my account is displaying the same on the Android app as well). My user ID is 050772dc-2721-4ed4-9137-724ac783b089. Thank you for your help, as I was really hoping to get the item before it went away!

_edit by admin:_
### What to do if this happens to you:

**If you bought any of the Limited Edition 2016 Spring gear listed below and it disappeared, comment here to say which piece(s) they were and include your User ID (to learn how to find your User ID, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions).**
- Healer:
  - Fluffy Bunny Breeches  
  - Blossom Diadem 
  - Purple Bunny Ears  
  - Floral Buckler 
  - Spring Flower Wand
- Mage:
  - Grand Malkin Robes 
  - Grand Malkin Hat  
  - Yellow Cat Ears  
  - Staff of Bells
- Rogue:
  - Canine Camo Suit  
  - Good Doggy Mask  
  - Fire Bolas (main hand) 
  - Fire Bolas (off hand)  
  - Green Dog Ears
- Warrior:
  - Mighty Mail 
  - Mouse Guard Helm  
  - Cheese Wheel  
  - Cheese Mallet  
  - Red Mouse Ears

**Comment by Alys** [comment]
This happens at the end of the period when items are available. It's from timezone differences - your browser thinks we're still in the limited edition period but the server disagrees. I've put the item into your account. Reload and you'll see it.

I'm leaving this open for others with the same problem to comment on.

https://github.com/HabitRPG/habitrpg/issues/6169 is the issue we're using to discuss a fix for this.

**Comment by Vataro** [comment]
Thank you very much! I'll pay closer attention to the time next time!

**Comment by simbs** [comment]
@Alys I think this might have happened to me too, but now I can't remember if I managed to buy the Snowboard in time or not, don't know if there's a way you can check it. id 33980d5c-67d3-4b82-bdb4-90434149148a

**Comment by Alys** [comment]
@simbs I've given you the missing items.

**Comment by Gourganator** [comment]
I have the same probleme but with the Mouse Guard Helm, my ID is b1cf915d-fd2f-4f13-ae4c-74e630e3a8e2

thanks if you can help!

**Comment by Alys** [comment]
@Gourganator You have the Warrior seasonal items now. You'll see them on your Equipment page (reload if they don't appear immediately).

**Comment by loksonarius** [comment]
@Alys 
Hello, I've been redirected to this page by someone from the tavern. I had the same issue happen to me, except that I rebought the armor and the transaction completed, but a few seconds later the Mouse Armor disappeared from my inventory and the 90 gold I spent was gone for good.

I was wondering if I could get some help?

-Dan (891b455c-ca57-488d-9e75-e0cf4c48272f)

Thank you!

**Comment by Alys** [comment]
@loksonarius already fixed in the Tavern

**Comment by loksonarius** [comment]
@Alys  Thank you!

**Comment by Gourganator** [comment]
@Alys the Mouse Guard Helm isn't in my inventory and I still have my 60 gold (I reloaded a lot in the last hour ), is it an other problem or I have to wait?

b1cf915d-fd2f-4f13-ae4c-74e630e3a8e2

thanks for helping!

**Comment by Alys** [comment]
@Gourganator That's weird - I was sure I checked after I fixed it. Anyway, the gear is there now. If you'd like to subtract the gold, you can use a custom reward or Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) on the website. Sorry about that.

**Comment by Gourganator** [comment]
@Alys thanks! it's perfect!

**Comment by ToxicCosmos** [comment]
I've lost my Bat-tle Armor, some time in the last few days... I wasn't paying attention, unfortunately.  And I don't know if I was refunded my gold... unless you lose gold when you don't complete a daily (I've missed 3 this week, I believe. I haven't noticed. It cost 90g and I have 74g.
4aa77137-e41f-408d-9c9b-9c6876744140
Using Chrome on Windows 10

**Comment by Alys** [comment]
@ToxicCosmos That's a different situation and not from a bug. You lost the item because your health dropped to zero and you "died". You can read about the effects of death at http://habitica.wikia.com/wiki/Death_Mechanics or ask for more information at the Newbies guild (Help > Ask a Question from the website, or Menu > Guilds on the app). As always with an item lost from death, you can buy it back in the Rewards section.
