### ISSUE TITLE
"Error request entity too large" when attempting to join 'Mobile App Challenge!'

### ISSUE THREAD

**Issue by matthardy-coraid** [HabitRPG/habitica#6646]
Attempted to join 'Mobile App Challenge!' and receive the following error:
"Error request entity too large"

Cleared cache and reloaded several times over last 2-3 hours but behavior persists. 

Chrome Version 48.0.2564.97 (64-bit)  on Mavericks.

**Comment by mgpcoe** [comment]
The request sends the complete list of all participants in the challenge and a bunch of empty JSON about each one of them. 1800+ participants and the server tells you to go get stuff.

Requests to (e.g.) join challenges should send only the relevant data for the action in question--that _this_ user wants to join _that_ challenge. Nothing more, there's no use in sending all that data over the wire.

**Comment by matthardy-coraid** [comment]
Thanks. Previously I was attempting to join from the specific challenge page:
https://habitica.com/#/options/groups/challenges/c14e8130-b22f-4e60-9bcb-7a34e5756829

I was able to join it from the list of challenges:
https://habitica.com/#/options/groups/challenges

**Comment by Alys** [comment]
There's a new version of the challenge now, which you will be able to join: https://habitica.com/#/options/groups/challenges/1aa1adbb-0df2-4bd0-a0df-590d4021b6fa
