### ISSUE TITLE
Quickly died after leveling up, and a suggestion

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#665]
Yesterday I leveled up and then just now I died, even though I had 50 health this morning. Not a huge deal as this is still in development, but possibly an issue. If  there's any information you need from me that might fix or see what the problem is, let me know.

Also, I was wondering if it could be possible to see what is eating away at your health. Maybe a graph or something?

**Comment by wc8** [comment]
As far as having a history or graph of what you've done, you may be interested in this [suggestion](https://trello.com/c/h0pezwDR). 

Had you logged a negative habit when you died? Do you have a custom time set for day start? Or did you just die for no apparent reason when the page refreshed?

**Comment by ghost** [comment]
I was on vacation for a week so I unchecked all of the Dailies, and yesterday I then started them up again.

Also, I just died again. It looks like it's my "Browser Productivity" but I currently don't have anything on procrastinating websites. So I don't know what the deal is.

**Comment by ghost** [comment]
My browser productivity was at -203 (I'm not sure why), so I kept pressing the plus button and the issue seems to be fixed. I'm thinking it may be a bug in the Chrome extension.

**Comment by wc8** [comment]
OK. I created a new issue for this on the extension repo: https://github.com/lefnire/habitrpg-chrome/issues/57

**Comment by lefnire** [comment]
You can just delete browser-productivity for now, it gets re-created by the
extension at 0

**Comment by wc8** [comment]
Closing since it's an extension issue, right?
