### ISSUE TITLE
Avatar facial hair set unlocked & gems taken but now set seems locked.

### ISSUE THREAD

**Issue by Kettlehead** [HabitRPG/habitica#6651]
After purchasing the Avatar Facial Hair set for 5 gems yesterday, I was able to select the items and my avatar has updated its image but then an application error warning occurred. I hoped that it would correct itself but sadly not. The avatar still has the beard and moustache but any attempts to change it prompt the purchase of the set again. The gems have not been refunded.

User ID: f0340a82-576c-48ff-a4bf-52dc243431ba
Using Mac OSX 10.11.3 & Chrome 48.0.2564.97

Thanks in advance! :)

**Comment by Alys** [comment]
@Kettlehead Could you please take a screenshot of the User > Avatar page and drag it into a new comment here? (Attaching it to an email won't work.)

**Comment by Kettlehead** [comment]
![screenshot 2016-02-04 10 24 15](https://cloud.githubusercontent.com/assets/8167458/12812348/af89c8e0-cb29-11e5-8160-2bd2167b64c9.png)

Here ya go! Do you need a bigger screenshot or is that what you're interested in?

**Comment by Alys** [comment]
@Kettlehead It looks like the purchase of the entire set failed but that you then purchased two facial hair styles individually for 2 gems each. Did you notice if your gem balance went down by 4 or by 5? Or by 9?

I've given you 5 gems to buy the entire set.

**Comment by Kettlehead** [comment]
Thanks @Alys, I've repurchased the set. It definitely decreased by 5 as I only had 5 in total.
