### ISSUE TITLE
Loss of Party started an error

### ISSUE THREAD

**Issue by jfannin** [HabitRPG/habitica#6652]
User ID: 3fdb7166-1fc0-4461-8ecd-9090b7f5261e
Browser: Chrome
OS: Windows and IOS 7.1
Java Error: Failed to load resource: the server responded with a status of 400 (Bad Request)
https://habitica.com/api/v2/user/batch-update?_v=1042&data=1454521564285 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-027344d3.js:32 ObjectresponseError @ app-027344d3.js:32
www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1762910064.1454035174&jid=915780659&_v=j40&z=1780770985:1 GET https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1762910064.1454035174&jid=915780659&_v=j40&z=1780770985 net::ERR_BLOCKED_BY_CLIENT
amplitude-2.2.0-min.gz.js:1 POST https://api.amplitude.com/ 400 (Bad Request)Request.send @ amplitude-2.2.0-min.gz.js:1Amplitude.sendEvents @ amplitude-2.2.0-min.gz.js:1Amplitude._logEvent @ amplitude-2.2.0-min.gz.js:1Amplitude.logEvent @ amplitude-2.2.0-min.gz.js:1(anonymous function) @ app-027344d3.js:32

My party was disbanded and now errors are popping up. It's not saving my progress now. I'm wondering if it was because I was invited and then joined that it was a part of the issue.

**Comment by jfannin** [comment]
Update: my IOS 7.1 is working just fine now that I've joined a new party, also the public computers are fine. It's just my laptop that has the error it might have changed.

Java Errors: 
Failed to load resource: the server responded with a status of 400 (Bad Request)
https://habitica.com/api/v2/user/batch-update?_v=1039&data=1454545705884 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-52821948.js:32 Objectconfig: Objectdata: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta name="viewport" content="width=device-width, initial-scale=1">↵      <style type="text/css">↵        html, body, iframe { margin: 0; padding: 0; height: 100%; }↵        iframe { display: block; width: 100%; border: none; }↵      </style>↵    <title>Application Error</title>↵    </head>↵    <body>↵      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">↵        <p>Application Error</p>↵      </iframe>↵    </body>↵    </html>"headers: (c)status: 503statusText: "Service Unavailable"**proto**: ObjectresponseError @ app-52821948.js:32
app-52821948.js:6 TypeError: d.user.ops.sortTask is not a function
    at j.a.pushTask (app-52821948.js:35)
    at g (app-52821948.js:7)
    at D.&& (app-52821948.js:6)
    at Array.f (app-52821948.js:7)
    at b (app-52821948.js:7)
    at j.$eval (app-52821948.js:7)
    at app-52821948.js:8
    at app-52821948.js:8
    at x (app-52821948.js:4)
    at $$writeModelToScope (app-52821948.js:8)

**Comment by Alys** [comment]
On the browser that this is happening in, log out of Habitica, clear your browser's cookies, then go to https://habitica.com/static/clear-browser-data and click the button there. Does that help?

**Comment by jfannin** [comment]
Perfect! That worked like a charm. Thanks for all the knowledge
