### ISSUE TITLE
Application error and repeated party invites ("Cant do this... Habitica")

### ISSUE THREAD

**Issue by WingsofFreedom43** [HabitRPG/habitica#6656]
It keeps on telling me to join a party that im already in and on IOS it shows that I still have my old party members... heres the error picture and dont pay attetion to anything else, I burrowed this picture, it has the same error wording so yeah: http://i.imgur.com/4jkExoU.png?1

**Comment by Alys** [comment]
@WingsofFreedom43 Did you try the things I suggested in the Tavern?

"Reload the site. If it's still not showing what you expect, go to https://habitica.com/static/clear-browser-data and click the button (read the text above it first). If you're still seeing your old party, you're probably still in that party. Leave it again and ask for a new invitation to the new party."

If not, please try them now and tell us how it goes. If you still need help after that, we'll need to know your User ID - please go to Help -> Report a Bug and see step 6 of the instructions.

**Comment by Alys** [comment]
@WingsofFreedom43 I'm closing this but if you still need help, please see my previous comment.

**Comment by WingsofFreedom43** [comment]
It's still happening, I don't know why

**Comment by Alys** [comment]
We'll need to know your User ID and the Party's Group ID so please go to Help -> Report a Bug (https://github.com/HabitRPG/habitrpg/issues/2760 ) and see step 6 of the instructions.

**Comment by Floydius** [comment]
I'm in the same boat here; in a party.  seems like there are multiple invites and one never supercedes the other.   leaving the party and then accepting the remaining invite just re-starts the process.

user id:  c52d4ff8-a022-4726-8508-9e9096ec3285
group id:  c6de41d3-0de2-444e-a10a-3088d7d6e04e

I have tried logging out, logging back in.  reloading, and using the clear habitica data page, but so far no luck.  at the moment, it's a 2-person party, but only the leader is actually in the quest, it would seem.

**Comment by Alys** [comment]
@Floydius Please see https://github.com/HabitRPG/habitrpg/issues/5649 for the fix. If you have trouble with it or the instructions don't make sense (there's a lot of them!) please comment on that issue so that we can keep the conversation about that bug in one place.
