### ISSUE TITLE
Rainbow Hair not unlocked, but Gems were spent

### ISSUE THREAD

**Issue by K-B-G** [HabitRPG/habitica#6660]
On 2/3/2016 I bought 21 gems from the habitica mobile app with paypal. I then clicked on the unlock set button on the android app. It deducted the 5 gems, but did not unlock the hair; currently have 17 gems. I have updated the android app as of 2/4/2016 1:00 PM, and tried refreshing and re-syncing my account on desktop, but it still has not fixed the problem. I noticed a similar issue with someone buying the beard set, then having it lock as well. https://github.com/HabitRPG/habitrpg/issues/6651 

Here is a screen shot of my desktop on windows 7
http://puu.sh/mVMoH/ef02e81d3a.png 

Hope this helps debug it.

**Comment by Alys** [comment]
@K-B-G Sorry about that! If you tell us your User ID we'll give you back the gems (see Help -> Report a Bug step 6).

**Comment by K-B-G** [comment]
No prob
fddf753e-2447-4603-b9ab-a52bb0cbf34a

**Comment by Alys** [comment]
I've given you back the gems. Reload if you don't see them immediately. Comment again here if there's still a problem after that.
