### ISSUE TITLE
Subscription vanished

### ISSUE THREAD

**Issue by Sharkules** [HabitRPG/habitica#6664]
I paid for a 6 month subscription, then cancelled it a week later to avoid being rebilled by surprise. 
Now the site seems to think I'm not subscribed at all, though the first month went without a hitch.
The payment wasn't reversed, so now I have no money and no gems. 

I'm unsure if this is a bug or not, but I didn't know where else to post it. 

User ID: a866de05-3302-4b14-84fe-4950ca5e907c
Using Firefox and Windows 7

**Comment by Alys** [comment]
It's a bug - sorry about that! We'll get it sorted out for you as soon as
we can.

**Comment by Sharkules** [comment]
Thank you very much!

**Comment by Cartogenic** [comment]
Please advise once you fix it, I want to buy 12 month subscription :(

**Comment by Alys** [comment]
@Sharkules I've set up your subscription again with a bit of extra time on the end. Sorry for the trouble! Please tell me if anything still doesn't look correct.

The most reliable option for giving yourself a once-off subscription that doesn't repeat is to use the gift subscription option for yourself. Find your name in any chat area (e.g., party chat or the Tavern), click on it to access your profile, click on the gift box icon at the bottom left of your profile, and then select the subscription option from there. Those subscriptions work identically to the ones you can buy from the Site > Subscription page (or from the gem in the header) except that they don't recur.

**Comment by Cartogenic** [comment]
Oups I didn't see this last message and already subscribed for 12 months... Is there a way I can cancel now In order to not get surprise bills ?

**Comment by Alys** [comment]
@Cartogenic Tell us your User ID and cancel the subscription. I'll use your User ID to make sure the cancellation worked correctly.

**Comment by Cartogenic** [comment]
Oups I opened a new issue. I'm sorry,, my uuid is 5d6089f4-c814-49c4-8043-044bdbb27d21.
Thank you :)

**Comment by Alys** [comment]
no worries, thanks.

**Comment by Cartogenic** [comment]
I got an error when canceling: https://i.gyazo.com/aa1786b47334bff57048baac6a939f7e.png
Seems that I'll have to wait in order to get billed first on paypal, the last time I subscribed I was only billed several hours later.

**Comment by Alys** [comment]
@Cartogenic Yes, that's typical for new PayPal subscriptions. The cancellation should work fine after a day or so.

**Comment by Cartogenic** [comment]
Thank you very much, it worked :)

**Comment by Cartogenic** [comment]
@Alys nope, it didn't work https://i.gyazo.com/fd1f4368d9de4970954bc05c5f190893.png

I had already 1 month subscription (so the subscription says ending in 08-march of this year when it should be 2017)

**Comment by Alys** [comment]
@Cartogenic No worries, I'll get that fixed for you in a day or two at most (my current net connection won't let me connect to the database but I should be able to this time tomorrow).

**Comment by Cartogenic** [comment]
@Alys You're always very helpful, thank you so much :)

**Comment by Alys** [comment]
@Cartogenic Your subscription should be fine now. Comment here if it isn't.

**Comment by Cartogenic** [comment]
@Alys it says the subscription will end January 31st 2017 https://i.gyazo.com/4595923e1f8a690e87becd5a1d2a4f7e.png, 
but I had paid 1 month before subscribing for extra 12 months, so it was 13 months subscription total, see here before: https://embed.gyazo.com/fd1f4368d9de4970954bc05c5f190893.png
So it should be ending 8th March 2017.

I'm sorry for the bother and thank you for your help!

**Comment by Alys** [comment]
@Cartogenic Can you please email your two receipts to admin@habitica.com? Mention my name in the email and include this issue's URL which is github.com/HabitRPG/habitrpg/issues/6664 . If you don't still have the receipts, send the email anyway and say which payment method(s) you used for the subscriptions and what email address you use to log in to the payment site.

**Comment by Cartogenic** [comment]
Sure! Thank you

**Comment by Cartogenic** [comment]
@Alys Email sent :)

**Comment by Alys** [comment]
Okay, that all makes sense. There wasn't any trace of the original one-month subscription in your account so I missed it. Please reload the subscription page and tell me if the date still isn't correct.

**Comment by Cartogenic** [comment]
@Alys  Yes sir! Everything alright, thank you! 
Have a wonderful day :)
