### ISSUE TITLE
I keep getting annoying quest pop-up after leaving party

### ISSUE THREAD

**Issue by Cartogenic** [HabitRPG/habitica#6666]
I recently got invited to a quest, in a rather inactive party - which I decided to leave, without rejecting or accepting the quest. 

Now every time I open a page, it doesn't matter if I click "ask later" or "reject", it says "No quest invitation has been sent out yet." in a blue message box, and the message keeps showing up.

Currently I created a new party and I'm working on joining active members so maybe our first quest will get rid of this annoying popup, but in any case my user uuid is [--- not needed anymore, check below]

**Comment by Cartogenic** [comment]
man this pop-up is getting on my nerves
https://i.gyazo.com/40f6bc91bbdcd3dc6ab20afec3760235.png
Here's the error message, when I click either reject, ask later or accept:
https://i.gyazo.com/aa2f52a9f27ef0b500c68e68cebb4b7f.png

**Comment by Cartogenic** [comment]
Fixed the problem by joining a new quest, on a new party.
But remains a bug.

**Comment by Cartogenic** [comment]
I'll leave it open just so you guys know about it

**Comment by Alys** [comment]
We have this recorded at https://github.com/HabitRPG/habitrpg/issues/6598 so I'm closing this issue. Thanks for letting us know that it's fixed for your case.
