### ISSUE TITLE
Plays wrong sound when cannot buy item due to insufficient gold

### ISSUE THREAD

**Issue by ksmith6** [HabitRPG/habitica#6668]
My User ID: 6d9d36a8-d91f-4737-8e8c-4fe9a4d632fe
I'm using Windows 7, Chrome 48.0.2564.103 m.

When you try to buy an item when you don't have enough gold, it still plays the "success" sound as if you bought it, even though the "Not Enough Gold" message appears in the upper right corner of the browser window.

The expected behavior for this is to play a different sound, just like the sounds for "+" and "-" on a habit are different.  The sound should indicate that the transaction was not completed (something similar to the "lost health" sound.

**Comment by Alys** [comment]
Thanks for telling us! I've marked this as an issue that we want to have fixed.

However I think it's better to have no sound when the reward can't be purchased. We don't really have a sound for an error condition, and reusing a sound that's used for other actions could cause confusion (e.g., "I clicked on a reward but it sounded like I clicked on a negative Habit - did I lose health?")

**Comment by taldin** [comment]
Preliminary investigations I've made make this a non-trivial fix -- the sound occurs as soon as you click, and before the check whether you purchase something goes through.

**Comment by kdcarlsen** [comment]
If nobody else is working on this I'd like to take a stab at it

**Comment by kdcarlsen** [comment]
@Alys Any idea where to start looking in the code?

**Comment by Alys** [comment]
@kcswordfish If you search through the code base for "audio", you'll find some of the code that handles sound effects, and that will give you other search terms (e.g., function names). NB: https://git-scm.com/docs/git-grep

Some wiki pages that might also help are http://habitica.wikia.com/wiki/Guidance_for_Bards and http://habitica.wikia.com/wiki/Audio

**Comment by kdcarlsen** [comment]
Excellent - I'm on it.  Thanks

**Comment by kdcarlsen** [comment]
@Alys Hope it's alright I ask - do you have any idea where the default value for a reward cost (10) is set?  I've located the code that plays the sound effect and have an idea of how to fix it but I can't figure out how to access/check the cost of a reward.  I looked in task.js and found 
`
var RewardSchema = new Schema(
  _.defaults({
    type: {type:String, 'default': 'reward'}
  }, TaskSchema)
  , { _id: false, minimize:false }
);
`
but from what I can tell that only sets the task type and has nothing to do with the value I need.

EDIT: Nevermind, it seems that the task just gets treated like an item and it's cost is stored in the value parameter

**Comment by crookedneighbor** [comment]
Closed in #6668
