### ISSUE TITLE
Party is missing a group leader

### ISSUE THREAD

**Issue by btrowbridge** [HabitRPG/habitica#6669]
For some reason when creating a group, it did not make me the leader. Instead, nothing shows up next to "Group Leader: "

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.   

What is the group id?

**Comment by btrowbridge** [comment]
Here it is:
aea634c6-36e3-4970-9725-bed7aa1c0781

**Comment by btrowbridge** [comment]
Also the Group ID:
 4b22dba3-1142-462f-9bb7-a0b413c464ec

**Comment by Alys** [comment]
I've set you as the leader. reload to see the change.

**Comment by btrowbridge** [comment]
Great! thank you for being amazingly responsive :)
