### ISSUE TITLE
Insurance feature for missing updates due to sickness, internet down, etc.

### ISSUE THREAD

**Issue by dfjkla** [HabitRPG/habitica#667]
I've come close to dying a few times because I forgot to update my HabitRPG due to life getting in the way, and yesterday I actually died. I feel dying is too hefty a punishment for when you get sick or your internet dies, for example.

My suggestion to fix this is an insurance feature. If there is no up/down activity on the account during any given day, you would not get the rewards and punishment at day-end. It would be important that it is actual activity that is missing, not just having the tab open - you might have the tab open, but unable to update HabitRPG. Next time you go to HabitRPG tab or log on, there would be a popup saying along the lines: "Your insurance is active due to inactivity on your character. Click here to de-activate insurance, and record activity since [date](inclusive)".

Insurance could be bought for gold. Your insurance premium would go up every time it goes active, to discourage abuse - it should be a fall-back measure on rare occasions. Alternatively, insurance could be a feature from reaching level x, or a quest reward.

There are Trello cards for vacation feature, but this is slightly different. This would tie with and likely require the Trello card for updating yesterday's activity.

**Comment by wc8** [comment]
Have you seen: [Account Freeze on Inactivity](https://trello.com/c/UqxYFiqG)?

**Comment by dfjkla** [comment]
Now I have - thanks!

Account freeze is what I'm looking for, but I feel insurance terminology better describes its functionality.

**Comment by wc8** [comment]
OK. "Account Freeze" is just what it does, not the best name. I added a note for a better name, including insurance as a suggestion.
