### ISSUE TITLE
Loss of gems

### ISSUE THREAD

**Issue by pqhunter** [HabitRPG/habitica#6671]
I lost my Internet connection in the middle of changing my class. When I had intended again I had been charged double for changing my class. I had 20 gems, now I have 14 instead of 17. I'd like my gems back please. My user ID:0298735e-b2e1-4720-a605-4f4a00c70338

**Comment by crookedneighbor** [comment]
We don't get notified when issues are updated, just when new comments appear. Just posting this so the other devs get the notification that you added your user id:  0298735e-b2e1-4720-a605-4f4a00c70338

**Comment by Alys** [comment]
Thanks @crookedneighbor .

@pqhunter I've given you three gems.

**Comment by pqhunter** [comment]
Thank you!
