### ISSUE TITLE
when buying block subscription through gem in header, perk amounts aren't shown

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6672]
When you buy a block subscription (three months or more) through the gem on the header, the "cap raised to" and "mystic hourglass" green texts don't contain values:

![screen shot 2016-02-07 at 6 16 57 am](https://cloud.githubusercontent.com/assets/1495809/12869147/74722fe6-cd62-11e5-80f0-7de56a5db09a.png)

When you buy through the "subscribe" button, they are displayed correctly:

![screen shot 2016-02-07 at 6 17 10 am](https://cloud.githubusercontent.com/assets/1495809/12869146/74715f76-cd62-11e5-8713-3d4c0bde095e.png)

**Comment by kogelnikp** [comment]
@Alys I would like to work on a fix for this one.

**Comment by Alys** [comment]
@kogelnikp Thank you! Please do!
