### ISSUE TITLE
How can I cancel the recurring subscription (without the subscription vanishing)?

### ISSUE THREAD

**Issue by Cartogenic** [HabitRPG/habitica#6673]
Hi, I apologize for having to open a new issue regarding #6664 , but I just subscribed for 12 months and I don't want to get surprise bills next year (just in case) and I'd like to cancel the recurring billing without losing my subscription status.

Any way to do that?

my uuid, just in case: 5d6089f4-c814-49c4-8043-044bdbb27d21

Thank you!

**Comment by Alys** [comment]
duplicate: https://github.com/HabitRPG/habitrpg/issues/6664

**Comment by Cartogenic** [comment]
Oups, problem solved in #6664 I thought since I couldn't re-open the issue, no one would see my last sent message. Thanks.
