### ISSUE TITLE
XP overload

### ISSUE THREAD

**Issue by Rohlik** [HabitRPG/habitica#6674]
Hello,
today I got interesting XP bug.
As You can see, I have more XP than max, also I didn't get new level.

![habbit](https://cloud.githubusercontent.com/assets/2051154/12871975/98bfd65c-cd92-11e5-820a-5d8cb9ad8355.PNG)

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/2433 for the explanation and fix. In brief, you'll level up as soon as you tick off a task.
