### ISSUE TITLE
Exp Overflow Problem

### ISSUE THREAD

**Issue by Cartogenic** [HabitRPG/habitica#6675]
Well, they say an image is worth a thousand words, so here you go
https://i.gyazo.com/526cca5c4218f52b965950df0d38ada9.png
What to do?

**Comment by Cartogenic** [comment]
A fixed it, created a trivial habit to get +1 exp and leveled up.

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/2433
