### ISSUE TITLE
Dailys active on specific days do not respect Custom Day Start

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#668]
I noticed my Dailys that are meant to become active until tomorrow became active after 12:00 AM rather adhering to my Custom Day Start setting of 2:00 AM.

Minor bug but worth getting everything starting at the same time.

**Comment by cleave29** [comment]
Kinda sounds like #587

**Comment by horusofoz** [comment]
It's the same issue. Thanks. I'll close this thread.
