### ISSUE TITLE
Checking a checklist item opens the task edit window

### ISSUE THREAD

**Issue by MaidM** [HabitRPG/habitica#6680]
Came out of the inn today after a couple of weeks away so this is the first time I've noticed this happening.  Occasionally lets me just check the checklist item, but most of the time it opens the task edit window.  I'm using the laptop so this isn't a fat finger issue.

If I tick the box, it shows the tickmark, then opens the edit window, then if I click cancel (or sometimes just mouseover the task), it returns me to the main view, but with the checkbox unticked again.  The task I'm having trouble with has a 5-item checklist, if that makes a difference.

**Comment by Alys** [comment]
Can you tell us which browser you're using, and which version of the browser, and which operating system and version?

**Comment by MaidM** [comment]
Browser is Chrome, version 48.0.2564.103 m
OS Windows 7 SP1 64 bit

Problem was rife over the last couple of days, even with a restart of the laptop.  Haven't seen it today.

**Comment by Alys** [comment]
@MaidM Has the problem come back since then? If not, I think it's likely to be a temporary glitch that you hopefully won't see again.
