### ISSUE TITLE
subscriptions are not always created correctly - missing data, needs to be checked after creation

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6682]
I've noticed that sometimes when a subscription is created, not all of the subscription's data is saved to the user's account in the database. I've seen `purchased.plan` objects with missing values for `dateUpdated` and `consecutive.gemCapExtra`, and there could be others.

There isn't anything in the code that could account for this so it must be that even though the code is creating the data, it's not being correctly written to the database, presumably due to server load issues.

I think we should add a section to the end of the subscription code that reads the new data back from the database and compares it to what should have been written, and then fixes any errors, and repeats the check.

If anyone has any better ideas, comment here. If there's no objections in a couple of days, I'll advertise this in the Aspiring Coders guild.

**Comment by paglias** [comment]
@Alys is data saved in multiple steps or all at once? If all at once (ie a single user.save or user.update) then it should never happen. if it's saved in different locations instead it's probably worth a fix

**Comment by Alys** [comment]
It's saved all at once at the end of createSubscription() in website/src/controllers/payments/index.js :

```
  async.parallel([
    function(cb2){data.user.save(cb2)},
    function(cb2){data.gift ? data.gift.member.save(cb2) : cb2(null);}
  ], cb);
```

and yet I have seen missing data.

**Comment by paglias** [comment]
Still happening?

**Comment by Alys** [comment]
If I had to guess, I'd say probably yes, but I have no direct evidence of it. Closing. Will reopen with specific examples if I find any.
