### ISSUE TITLE
Suggestion: Changes to Achievement descriptions

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#6685]
Hello everyone! I'm jumping back into GitHub and Habit after a long time away, so pardon me if I seem like I'm missing something obvious...

Reading over the achievements page, a few potential alterations have come to mind that an entry level coder could probably do:

**Helped Habitica Grow:** - Change the second sentence to read "_There are currently no active surveys. Watch out for the next official Habitica survey so you can get this achievement too!_" or something similar [I think it would be great to at least add the "currently" -- the sentence flows better and is more clear]
**Streak Achievements:** - Rewrite as "_Has maintained a 21-day streak on a Daily [#] times_" [greater clarity]
**Beast Master:** - Multiple changes smushed together: "_Has found all 90 base pets_" [clarifies that quest pets don't count]; "_(incredibly difficult,_ " [more accurate and more respectful to our many Habiticans with mental illness]; "_congratulate this person!). This user has also released their pets a total of [#] time(s)_" [makes it more clear that releasing pets is not a requirement to get the achievement]
**Mount Master:** - Change to read "_Has raised all 90 base pets into mounts (even MORE difficult, congratulate this person!). This user has also released their mounts a total of [#] time(s)_" [similar clarifications as Beast Master]
**Triad Bingo:** - Rewrite as "_Has raised all 90 base pets into mounts and then found all 90 base pets AGAIN! (This takes a VERY long time!!!). This user has also released their entire stable a total of [#] time(s)_" [greater clarity, like its siblings]

I also think the organization would make more sense if the achievements that list all the challenges a user has won and the quests they have participated in were relocated to the bottom of the achievement list.

Thoughts? If nothing else I would love for the Beast Master "insanely" to be changed to something else. That one's bothered me for a long time.

**Comment by Alys** [comment]
You're right about "insanely". It should never have been there, and we should have noticed that problem a long time ago. I'm sorry that we didn't. I've just made a fix for that one word and it will go live the next time we deploy changes to the site (within a few days at most). 

I'll leave the rest of your suggestions for discussion. I see nothing wrong with them. I especially like your idea of moving the quests to the bottom of the list.

**Comment by quin-jay** [comment]
Thank you for rushing that one Alys! :+1: 

Editing to add: Maybe the achievement "Was the winner in the following challenges" should also be moved to the bottom along with the quests. I didn't see that one earlier.

**Comment by harshhpareek** [comment]
Hi, Trying to get involved with Habitica. Here are my recommendations and file numbers for later reference:
- Helped Habitica Grow [contrib.json:55, 56, possibly 29]
  - Change the second sentence to read "There are currently no active surveys. Keep watching the [Official Habitica blog](http://blog.habitrpg.com) for survey announcements!"
- Streak Achievements [tasks.json:80,82] 
  - Rewrite as "Has maintained a 21-day streak on a Daily [#] times"
  - Perhaps remove the "[#] times" if it hasn't been done yet. This change could also be done to the Perfect day achievement
- Beast Master [pets.json:43] 
  - "Has found all 90 original pets (incredibly difficult, congratulate this user!)" [changed wording to "original" to be clearer and consistent with the wiki, I think user as in the game is better than person here]
  - I think the part about releasing their pets seems odd here and should instead be added in the [wiki](http://habitica.wikia.com/wiki/Achievements)
- Mount Master [pets.json:49] 
  - "Has tamed all 90 mounts (even MORE difficult, congratulate this user!)" [ I prefer the tamed wording]
  - Similar update as above to wiki
- Triad Bingo[pets.json:53] 
  - I prefer the current wording, sounds more fun, and the meaning is clear.

If you agree with this, I'll go ahead and make the changes. Perhaps we could add a suggestion for an achievement regarding releasing mounts. I'm not sure how to add the counter yet.

Have not looked into the reorganization yet.

**Comment by SabreCat** [comment]
We could probably take out the difficulty and admonition-to-congratulate parentheticals entirely.

**Comment by Alys** [comment]
I quite like those "congratulate" messages! I think it encourages people to post in the Tavern when they've made the achievement and helps promote the supportive nature of the site.

@harshhpareek I think "original" when describing pets won't help new users because they won't know that the quest pets were added to the site later than the generation 1 pets. Unfortunately "generation 1" has the same problem, and "base" can imply base hatching potions. "Basic" perhaps? 

We should settle on a meaningful name for the non-quest, non-rare pets and put that as a subheading on the pets and mounts pages (and in the achievement of course).

The information about the number of times they've released their pets is part of the achievement and should remain.

We've been using "player" rather than "user" recently because it is more friendly; less like a technical user-support term.

Consistency with the wiki isn't important because the wiki is based on the website (although of course many parts of the wiki use approved terminology, and consistency with that terminology is important).

**Comment by quin-jay** [comment]
Just dropping a note to say that #4445 discusses specifically the achievement strings about using Keys to the Kennels and #7125 discusses the naming of generation 1 (non-quest, non-rare pets). If there are PRs made, I'll post a recap here of what still needs deciding.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by SabreCat** [comment]
Yes, on a cursory look these strings have not been changed.

**Comment by lemoness** [comment]
These strings are slated to be separately reviewed and changed, so I'm closing this ticket for now.
