### ISSUE TITLE
Egg Hunt quest (collect 100 eggs). I'm the only one who's getting eggs.

### ISSUE THREAD

**Issue by partemios** [HabitRPG/habitica#6686]
Hi,

Fairly new to Habitica. Got a party of five - all of us on the 100 egg hunt quest, but I'm the only one who seems to be collecting the eggs. Other member are definitely doing their tasks and they're higher level than I.

Windows 7, Chrome.
User ID: 7a752a6f-401b-429f-9411-333e83b383be

**Comment by Alys** [comment]
You're the only person participating in the quest. You can confirm that by looking at the list of quest participants on the party page on the website - click the participants tab. I'm guessing that either the other party members joined the party after the quest had started, or you clicked the "begin" button on the quest before they accepted the invitation - the next time you start a quest, see the text above the begin button for details.

You can click the "abort" button on the quest now, if you wish to. The scroll will go back into your inventory and you can use it to restart the quest with new invitations sent out to your party members.
