### ISSUE TITLE
Tags getting duplicated while trying to sync between two computers

### ISSUE THREAD

**Issue by guptabhavesh** [HabitRPG/habitica#6689]
While trying to sync between two computers, I noticed that all my tags got duplicated and got doubly assigned to the dailies and To-Dos. Have a look.

![image](https://cloud.githubusercontent.com/assets/17165341/12956984/adb8997a-d050-11e5-918c-96d7e8c3bf80.png)

Chrome Version 48.0.2564.109 m
Windows 10 32-bit
User ID: d15276d3-784e-4be1-82d9-9ad27c95d4cd

**Comment by Alys** [comment]
Did you create the tags on one computer and then go to the second computer and notice that the new tags weren't there so you had to create them again?

**Comment by guptabhavesh** [comment]
Nope, I didn't recreate them on the other computer.
- I had opened Habitica on Computer 1.
- Did some tasks addition.
- Left it open.
- Opened Habitica on Computer 2.
- Created tags.
- Added tasks, rewards, etc.
- Went on the other Computer 1 (couple of hours later), which had the
  page open (unsynced).
- Tried Syncing on Comp 1. No change.
- Tried Syncing on Comp 2.
- Then Came back and tried syncing on Comp 1 again. No change.
- After couple of attempts and page refresh, it started showing synced
  stuff on Comp 1 as well.
- But tags were automatically duplicated.

Hope it helps.

Regards,
Bhavesh Gupta

**Comment by Alys** [comment]
Technical info (@guptabhavesh you can ignore this if you wish):

The tags have been duplicated, even down to their ID numbers:

```
    "tags": [
        {
            "name": "Home",
            "id": "f2afaa92-c6c3-46d9-af1e-e769984d3baa"
        },
        {
            "name": "Office",
            "id": "5691fff8-2a65-4ea4-8647-114b9de8ad0c"
        },
        {
            "name": "Outdoors",
            "id": "9b7ce4cf-6a80-4886-8779-fea38e9e8051"
        },
        {
            "name": "Phone",
            "id": "83c1d1b6-aba0-4611-af04-8ab1dad2e27c"
        },
        {
            "name": "Internet",
            "id": "b4b5b20c-b252-48ae-8067-ca30f4be14a9"
        },
        {
            "name": "Home",
            "id": "f2afaa92-c6c3-46d9-af1e-e769984d3baa"
        },
        {
            "name": "Office",
            "id": "5691fff8-2a65-4ea4-8647-114b9de8ad0c"
        },
        {
            "name": "Outdoors",
            "id": "9b7ce4cf-6a80-4886-8779-fea38e9e8051"
        },
        {
            "name": "Phone",
            "id": "83c1d1b6-aba0-4611-af04-8ab1dad2e27c"
        },
        {
            "name": "Internet",
            "id": "b4b5b20c-b252-48ae-8067-ca30f4be14a9"
        }
    ],
```

There's no duplication within the tasks - each tag ID occurs at most once per task.

**Comment by Alys** [comment]
Fortunately that makes this really easy to fix. :) @guptabhavesh Could you please reload the site? You should have only one set of tags now.

**Comment by guptabhavesh** [comment]
Sure, there is only one set now :-). Thanks.
