### ISSUE TITLE
Username already taken / Username not registered

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#669]
Many people experience the bug where "Username not registered", but when you try to register "Username already taken". This happens when either the site goes down or is at the peak of it's leak cycle, both due to #165. The solution is to wait a while and try again. Also, you'll likely experience this issue if you use Internet Explorer - so use Chrome or Firefox instead. If still experiencing, please contact admin@habitica

**Comment by lefnire** [comment]
(closing, just created so I can direct people here - the real bug is #165, so no need to track here)

**Comment by ghost** [comment]
Hi I am trying to change my username but it's not allowing me and it is showing error like "Login is already taken". Can you please help how to fix this. Basically I to show my name instead of ID to the users.

**Comment by Alys** [comment]
@shail-mmt Go to User -> Profile and click on Edit to change your Display Name. For questions about how to use or configure HabitRPG, you'll find it easier to go to Help -> Ask a Question, instead of using GitHub. GitHub is primarily for bug reports.

**Comment by ghost** [comment]
Thanks Alys, 
I am able to change this (Basically it was not allowing me to change as I was giving same name which I was already given some time back)

**Comment by ghost** [comment]
> This happens when either the site goes down or is at the peak of it's leak cycle, both due to #165

Seems that there exists at least one other reason. Seems to me that certain names are not wanted.

**Comment by Alys** [comment]
@blogsettings There is currently no filtering preventing certain names being used when a new account is created, except names that are already in use (which cannot be used again for another account). What problem are you experiencing specifically?

**Comment by ghost** [comment]
I wanted to rename my username to blogspot which apparently does not exist:
https://gist.github.com/blogspot/ - Result: **Page not found**
**404 - This is not the web page you are looking for.**
So why is it not possible to choose the name?

**Comment by Alys** [comment]
That's referring to a GitHub user account, whereas this closed issue was referring to accounts on the https://habitica.com (Habitica / HabitRPG) website. We can't help you with GitHub account issues. You can access your GitHub profile at https://github.com/blogsettings and it might allow you to change your username, but if you need help with that, try contacting GitHub.

**Comment by symbolic** [comment]
Hi, I want to change my username to "w". But it is showing error like "Login is a reserved word". 
When I input "https://github.com/a" "https://github.com/z" “https://github.com/0” “https://github.com/9”，they are all okay. What's wrong with "https://github.com/w"? Could you fix this?
Thanks.

**Comment by crookedneighbor** [comment]
@symbolic See the comment right above your comment

> That's referring to a GitHub user account, whereas this closed issue was referring to accounts on the https://habitica.com (Habitica / HabitRPG) website. We can't help you with GitHub account issues. You can access your GitHub profile at https://github.com/blogsettings and it might allow you to change your username, but if you need help with that, try contacting GitHub.
