### ISSUE TITLE
unable to start or abort quest

### ISSUE THREAD

**Issue by raggedknitter** [HabitRPG/habitica#6691]
User rgdkntr
Userid  00e8be72-a72e-4b10-8002-0190d343b5f5

Bug:

Quest Invitation: Attack of the Mundane, Part 1: Dish Disaster! Was sent to Group ID: f04c7db5-0d6b-48d2-8a0c-c693f0401475

Need to be started  manually as one party member has not accepted

The option to start the quest does not display on my screen where it should.      There are no available actions for me to take – cannot start or even abort the quest which leaves the entire party in limbo.

I am working on a laptop (not IOS/Android), have tried logging out and back in but that didn't help

thanks

**Comment by Alys** [comment]
I've confirmed that you are the quest owner and so you should be able to start the quest. I'm sorry you can't!

Can you please show us a screenshot of the quest box where the "begin" button should be? We'd like to see that to help with the bug fixing. Once we have everything we need for this, we can do something to help the quest start.

**Comment by raggedknitter** [comment]
Thanks for getting back to me so quickly !  I couldn't get everything on
one screen so there are 2 attachments.  The only thing I cropped out was
the quest description and party member names.   As you can see there is no
start button.  Appreciate the assist

**Comment by Alys** [comment]
Ah, I'm sorry, I forgot to explain this. :(  Images attached to emails don't appear in the GitHub issue. Could you please go to the issue in your browser and drag the images into a new comment?

**Comment by raggedknitter** [comment]
![image](https://cloud.githubusercontent.com/assets/17168498/12965544/fcbac998-d024-11e5-99af-268b97c571d7.jpeg)
![image](https://cloud.githubusercontent.com/assets/17168498/12965545/fcd34702-d024-11e5-8355-4af029a5ee23.jpeg)

**Comment by Alys** [comment]
Thanks for that!

I believe I've started the quest correctly for your party, and updated all of the participants' user accounts. However if anything seems odd over the progress of the quest, especially in the first day or two, post again to this issue (even if it's closed). For example, you might find that the participants aren't recording any progress on the quest at the start of each of their days.

NOTE that none of the participants would have received the usual email stating that the quest has started so you might want to put a note in party chat about it. It's a collection quest though so they won't cause damage if they don't notice it's started.
