### ISSUE TITLE
Android Banner on Mobile Site

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6692]
Now that we have the Android app up and running, when Android users are browsing the mobile site on their phones, we should add a banner that they can click to download the Android app.

**Comment by librarianmage** [comment]
@Alys @lemoness at least for me, this doesn't have a banner on iOS either

**Comment by librarianmage** [comment]
@Alys @lemoness Nvm, it's just Chrome for iOS acting weird `shrug`
