### ISSUE TITLE
Never received Enchanted Armoire

### ISSUE THREAD

**Issue by haelog1** [HabitRPG/habitica#6699]
User ID: 53c81acf-ab6b-4676-ac90-056708868e03

I received the Ultimate Gear achievement and was told of the Enchanted Armoire, but it never actually showed up in my rewards. Help?

**Comment by haelog1** [comment]
By the way, I use a combination of my phone (Android), tablet (iOS) and my computer. It doesn't show up on any of them.

**Comment by Alys** [comment]
I've confirmed that you had an Ultimate Gear achievement but that the Armoire hadn't been opened for you.

I've opened it now. Please reload the website. If it still doesn't appear under Rewards, comment here and drag a screenshot of the Rewards column (the equipment section) into the comment. You can see what the Armoire should look like in the first image in http://habitica.wikia.com/wiki/Enchanted_Armoire

**Comment by haelog1** [comment]
I see it now. Thanks!
