### ISSUE TITLE
Partial Habits/Dailies

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#67]
For the habits or even the dailies have a level of completion. Basically subdivide the daily or habit into parts depending on how many parts you do you get a certain number of experience points.

**Comment by lefnire** [comment]
I like this. Like "Checklists" in Trello. I figure any further breaking-down of lists beyond one level and we'll just direct users to use Workflowy, and provide some intelligence there in the Chrome extension.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
[Checklists](https://trello.com/c/PJ1iJ413)

**Comment by wc8** [comment]
Perhaps even more related to the original request: [Extra Completion for Dailies](https://trello.com/c/ZO1YrAKz) or [Completion Quotas](https://trello.com/c/E5CVJlW6)

> For the habits or even the dailies have a level of completion. Basically subdivide the daily or habit into parts depending on how many parts you do you get a certain number of experience points.
