### ISSUE TITLE
Multiple Characters

### ISSUE THREAD

**Issue by rewdra** [HabitRPG/habitica#670]
Suggestion: Have multiple characters under one account

It's more intuitive to have different characters represent the different hats I wear in my life than to have all my habits mashed together under one character.

Good and bad habits at...
- work (finish project on time, don't browse reddit for more than 1hr, etc.)
- personal life (exercise, 45m reading, etc.)
- league of legends (time dragon & other map objective for team, called MIAs, etc.) 

I'd love having a character for each major domain of my life. Each character has their own set of good and bad habits and develops (lvls up) at their own rate. Maybe you could even put them all together in a party? Having multiple characters to work with feels true to the RPG genre too. I imagine having all characters at the top like tabs, selecting one would make it active bringing up their habit setup.

This would make evaluating progress in different areas of life easier too. Rather than categorizing the habit as work, personal, etc, those habits would just be owned by the 'Work' or 'Personal' character.

**Comment by wc8** [comment]
Sounds like Stephen Covey's Roles with one role for each "hat" you wear in life.
Would [Tags & Categories](https://trello.com/c/q7v02jAw) with filters with [Stats, Attributes](https://trello.com/c/L1H6LiZ3) meet your needs or are you really hoping for a character for each "hat" you wear?

**Comment by wildcate** [comment]
I like this idea of multiple characters! And I think it would be quite different from the tags approach. Plus you can play around more with different looks or character types (rogue at work, warrior in the household, ...)

**Comment by rewdra** [comment]
Tags would not offer an equivalent experience as I would like to see a break out of these different parts of myself and see them grow/lvl up corresponding to the development in that domain of my life.

Different characters is much more intuitive to me than tags. (I don't know if this is the same for other people.) But I think it's a great way to give more depth without making it more complex.

Stephen Covey was a good man. 
The idea of different roles or hats is also present within Sociology.
http://en.wikipedia.org/wiki/Role#Determinants_and_characteristics_of_social_role
(eg, One woman is a Mom, Daughter, and Doctor)

The picture below is how i envisioned it. As the example I used in my OP, good habits and intentions for League of Legends, Work and Personal are found in different characters. This offers a very simple way of creating parent-child relationships for categories of tasks/habits without depending on a more complex #tagging system. 
![habitrpg](https://f.cloud.github.com/assets/3891591/271520/7b5c8ec4-8fe8-11e2-80f6-30f7f16cc463.jpg)

**Comment by wc8** [comment]
Similar request #140 alteregos (or pets)

**Comment by rewdra** [comment]
Issue #193 also has a very similar intuitive feel too! 

I love the idea of habits being contextual based on 'buildings' or places your character 'goes' -> at home (a house), at work (office), at fitness center (fitness center).

**Comment by wc8** [comment]
I've added it to Trello suggestions: [Role Alteregos](https://trello.com/c/W0XdPYwT) so development can take user interest (votes) into account as they assess whether this would fit into HabitRPG.

**Comment by rewdra** [comment]
edit: sorry, didn't read the trollo entry you made. seems to capture the gist of it.

Thanks wc8.

Will the alterego, which is similar, capture the idea of being able to create and manage multiple characters under one account? Seems to limit what this could be by restricting it to a two character: pet and character or play/work characters dynamic.

The use cases seem more expansive and dynamic with the multiple characters functionality.

**Comment by wc8** [comment]
I updated the description to hopefully make this clearer: _multiple alteregos_. Alteregos (Other self) just seems a handy way to describe the extras.
