### ISSUE TITLE
Chat Time Display Says "In a Few Seconds"

### ISSUE THREAD

**Issue by joeywoneill** [HabitRPG/habitica#6703]
When you post something in the chat, sometimes it says "In a few seconds" in the section where it tells you how along it was posted. [screenshot](https://cloud.githubusercontent.com/assets/10093125/12998838/0b38638a-d0fd-11e5-8e0d-d9ab913bdd08.png)

**Comment by Alys** [comment]
Please see my first couple of posts in this issue: https://github.com/HabitRPG/habitrpg/issues/5112 - ignore the fact that that issue discusses Russian; it's the same problem. In brief, it's your PC's time that's incorrect. 

If you have questions, you're welcome to post here even though I'm closing this now.

**Comment by ghost** [comment]
@Alys as you've pointed to my silly report, I'm updating that one to contain the summary in the initial post as follows:

> Problem: If you see the time stamp "in a few seconds" instead of "a few seconds ago" (and respective alternatives translated into your display language) for most recent chat messages - it is because your computer/device time is incorrect by a few second.
> 
> Solution: get you computer/device time in sync with http://time.is/
> 
> Explanation: as far as I understand, Habitica stores the time of the post as reported by its own sources (some always in sync online time) then to display a time stamp the site checks how much time has past since the initial record against your computer/device time. So if you see "in a few seconds" your computer/device time must be some moments behind the right time for your timezone.

Please correct me if I'm wrong in details

**Comment by Alys** [comment]
@GitHubSphinx That's perfect! Thank you very much!
