### ISSUE TITLE
Add automatic message to Guilds with 5000+ Members

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6706]
A new change to the site to promote stability has made it so that Guilds with more than 5000 members no longer support notifications. This change automatically takes effect when a Guild hits 5000 members.

When this happens, a message should automatically display at the top of the Guild stating that there will no longer be automatic notifications.

Suggested text (feel free to edit!):
"NOTE: This Guild is now too large to support notifications! Be sure to check back every day to see new messages."

**Comment by Alys** [comment]
The code that prevents notifications for large guilds is here: https://github.com/HabitRPG/habitrpg/blob/00f98d90b6f498fa86b338da68f942bff94b1ac3/website/src/models/group.js#L167
The `5000` number should become a variable that's used in both that code and the new code required for this PR.

**Comment by khipkin** [comment]
@Alys I am interested in working on this issue!

**Comment by Alys** [comment]
@khipkin Awesome, thank you! Please do!
