### ISSUE TITLE
The bubble of the leader's opening post in chat doesn't stretch horizontally

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6708]
If the bubble of the opening post by the leader in the guild/party chat is meant to stretch horizontally, it doesn't seem to do so for me but rather has a fixed width.

I'm Using Firefox 44.0.2 for Windows (Win10 Home). The console shows a critical warning about loading mixed content via secured connection for
 view-source:https://habitica.com/app-c14655c7.js
 but I can't judge if it's related.

Screenshots:
![Pic1](http://oi67.tinypic.com/2lnvki0.jpg)
![Pic2](http://oi67.tinypic.com/154gdoy.jpg)
![Pic3](http://oi68.tinypic.com/292pssg.jpg)

Reporting this as suggested in the Aspiring Coders guild and not having found related threads.

To quote @DrStrangepork from similar issue:

> The https://habitica.com/app-bf28709d.css line 5 says "table {max-width: 100%;}" but in my Firefox browser the table always renders at width 194. I copied the markdown of the leader message from Aspiring Linguists to my local install and was able to duplicate the problem there as well: width is rendered to some hard number relative to zoom level in Firefox, but in Chrome it renders to 100% width (up to 1095px, at which point it remains at 1095px even if the zoom level is so small that it could be wider).

**Comment by Alys** [comment]
This is an example of what it's supposed to look like (Chrome 48 on Mac OS):

![screen shot 2016-02-13 at 9 57 16 pm](https://cloud.githubusercontent.com/assets/1495809/13027458/ddad235a-d29c-11e5-9c06-7d193880935b.png)

**Comment by DrStrangepork** [comment]
The table "group.leadermessage" contains only one row and column: `<div class="popover static-popover fade right in wide-popover">`. In the Firefox Developer Tools, I found the Computed CSS:

> max-width: 276px;
> .popover > 276px; : bootstrap.css:null;

This because the rules include:

> http://hab.rickkasten.com:3000/app.css:6946
> .wide-popover {
>     ~~max-width: max-content;~~
> }

Firefox reports the error "Invalid property value" for ~~max-width: max-content;~~. There is also this:

> http://hab.rickkasten.com:3000/bower_components/bootstrap/dist/css/bootstrap.css:null
> .popover {
>     ~~position: absolute;~~
>     top: 0;
>     left: 0;
>     ~~z-index: 1010;~~
>     ~~display: none;~~
>     **max-width: 276px;**
>     padding: 1px;
>     text-align: left;
>     white-space: normal;
>     background-color: #fff;
>     background-clip: padding-box;
>     ~~border: 1px solid #ccc;~~
>     border: 1px solid rgba(0, 0, 0, .2);
>     border-radius: 6px;
>     ~~-webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, .2);~~
>     box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
> }

While in the Chrome Developer Tools, there is this in Computed CSS:

> max-width max-content
> max-content .wide-popover app.css:6946
> ~~276px~~ .popover popovers.less:15

And Styles shows

> http://hab.rickkasten.com:3000/app.css:6946
> .wide-popover {
>     max-width: max-content;
> }
> http://hab.rickkasten.com:3000/bower_components/bootstrap/dist/css/less/popovers.less
> .popover {
>     ~~position: absolute;~~
>     top: 0;
>     left: 0;
>     ~~z-index: 1010;~~
>     ~~display: none;~~
>     ~~max-width: 276px;~~
>     padding: 1px;
>     text-align: left;
>     white-space: normal;
>     background-color: #fff;
>     background-clip: padding-box;
>     ~~border: 1px solid #ccc;~~
>     border: 1px solid rgba(0, 0, 0, .2);
>     border-radius: 6px;
>     ~~-webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, .2);~~
>     box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
> }

So it appears the Firefox reported error "Invalid property value" for `max-width` is the problem.

**Comment by DrStrangepork** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/max-width, the hover over **max-content** says: "This is an experimental API that should not be used in production code."

**Comment by DrStrangepork** [comment]
So I have fixed the issue by changing the app.css file within my vagrant VM, but in my local install I cannot find that file. Where should I make that change in code that can actually be used to create a pull request?

**Comment by DrStrangepork** [comment]
@Alys bump

**Comment by DrStrangepork** [comment]
:camel: 
That's a "bump".

**Comment by Alys** [comment]
app.css is a generated file, so it shouldn't be edited manually. The source files are under website/public/css/

Note that some of the site's css will come from third-party libraries installed under node_modules, and those also shouldn't be edited, since any changes you made would be overwritten the next time the libraries were updated, and they wouldn't be pushed to github since the node_modules directory is ignored by git.

**Comment by librarianmage** [comment]
@Alys I can try looking at this!

**Comment by ghost** [comment]
@MathWhiz It seems you are quite busy with other issues. Would you like us to advertise the issue among other aspiring coders?

**Comment by librarianmage** [comment]
@GitHubSphinx Yes, please!

**Comment by ESWAT** [comment]
@GitHubSphinx looking into this. :)

**Comment by citrusella** [comment]
I noticed today that the smaller width still happens in Internet Explorer 11. Not sure how important that is, but it felt worth bringing up.
