### ISSUE TITLE
Starting a quest - does not recognise party

### ISSUE THREAD

**Issue by eddie-tidus** [HabitRPG/habitica#6709]
I am trying to fight the Basi-list for the second time,  but Habitica does not recognise my current party and asks me to invite people by email or User ID. When I add my party member's ID, I am told they are already in a party. So I am unable to join this quest (I am level 4 so unable to test on other quests). This problem occurs via the quest page,  or via the party page->start a quest. 
Accessed on Android software Samsung using Chrome browser.

**Comment by Alys** [comment]
Can you please tell us your User ID? If you're not sure how to find it, see step 6 on the Help > Report a Bug page.

Also, if you have access to a PC, can you try starting the quest there? It might just be that your mobile phone's browser isn't loading all of the website.

**Comment by eddie-tidus** [comment]
Hi Alys. It is

b3c819d6-bb78-4cf3-a09f-25019cde917f

I don't have a PC at the moment but tried on an ipad and the same issue happens.

**Comment by eddie-tidus** [comment]
Hi, I tried on a PC and the same problem occurs. It does not recognise that I already have a party with one member (we already defeated the basi list together once before)

**Comment by Alys** [comment]
@eddie-tidus The database says that you're still in a two-person party, and I can't see anything wrong with the configuration of the party.

Can you upload a screenshot of the party page, taken from your PC? You'll need to visit this issue in a browser and drag the screenshot into a new comment. Attaching it to an email won't work.

Wait a minute or two after visiting the party page to ensure it's loaded completely.

**Comment by eddie-tidus** [comment]
HI Alys

Here are some screenshots, hope this is what you were looking for. I accessed quests via Party screen:

![image](https://cloud.githubusercontent.com/assets/17216459/13030369/5c3363e4-d2a0-11e5-81b6-cb6b003d31a2.png)

![image](https://cloud.githubusercontent.com/assets/17216459/13030372/90ffeb7e-d2a0-11e5-964a-8813a8afdb53.png)

![image](https://cloud.githubusercontent.com/assets/17216459/13030380/aec978a0-d2a0-11e5-94ce-7db280091c88.png)

**Comment by ghost** [comment]
@eddie-tidus , you only had one basi-list scroll, which you've used (and now under "your quests", it says "you don't have any quest scrolls"). The basi-list scroll is acquired by successfully inviting someone to your party -- so when you click it under "quests for sale", it asks you to invite someone.  Once you invite someone and they accept, you'll be given another copy of the scroll, and then it'll appear under "Your quests" and you can start it as usual. 

If you don't want to invite another person to your party, either you can get your partymate to leave so you can reinvite them, OR you can invite WikiFAQ_bot, 29bfa638-cb88-40e8-a0d0-48f455e7b2bd , and it will join your party (granting you the scroll) and leave.

**Comment by Alys** [comment]
@eddie-tidus I'm closing this, but if you have more questions, you can still comment here.

Cantras, thank you!

**Comment by eddie-tidus** [comment]
Thanks, it worked :)
