### ISSUE TITLE
Carons not supported by font; Cyrillic symbols not supported by font

### ISSUE THREAD

**Issue by sczther** [HabitRPG/habitica#6710]
As I am from Czech Republic, i want to write a lot of messages using carons (https://en.wikipedia.org/wiki/Caron ) as they are very common in my language. The font used by the webpage sadly doesn't support them so they are in a different font and stick out badly. It's just a minor issue, but i would be glad if a different font was used or if this one got support for carons.

---

**edit by admin:**

As described in https://github.com/HabitRPG/habitrpg/issues/2956, Cyrillic symbols are also not supported by the font currently used. Roboto is usually suggested to use alongside with Lato for latin-cyrillic pages.

http://www.google.com/fonts/specimen/Roboto
http://www.google.com/fonts#UsePlace:use/Collection:Roboto
It is licensed under apache license 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

Examples of pairings by google:
http://www.google.com/fonts/specimen/Lato#pairings
Droid Sans and Source Sance Pro look good, but I'm not sure if they support cyrillic

Refer to https://github.com/HabitRPG/habitrpg/issues/2956 for more details.

**Comment by Alys** [comment]
@sczther Can you show us a screenshot of the problem? I'm not sure it will be needed but it might help. To add the image to this issue, visit the issue in a browser and drag the image into a new comment; attaching it to an email won't work.

**Comment by sczther** [comment]
![example](https://cloud.githubusercontent.com/assets/17219314/13053141/2f7947ba-d403-11e5-84b8-5be2bece4198.PNG)
Here it is!

**Comment by keysmashes** [comment]
Font used is [Lato](https://www.google.com/fonts/specimen/Lato), which doesn't support carons apparently:

![image](https://cloud.githubusercontent.com/assets/9433472/13090038/78a9e190-d4eb-11e5-93a7-3676d9ad22aa.png)

![image](https://cloud.githubusercontent.com/assets/9433472/13090255/8f61dcde-d4ec-11e5-850a-bdf9bd57565d.png)

OTOH, [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro) does support carons:

![image](https://cloud.githubusercontent.com/assets/9433472/13090232/6f72f8ea-d4ec-11e5-87e0-147999cfd9a5.png)

![image](https://cloud.githubusercontent.com/assets/9433472/13090268/9f82b5ac-d4ec-11e5-8aca-dbd556429737.png)

The fonts look relatively similar (can't work out a quick way to change the font used for Habit, sorry):

Lato:
![image](https://cloud.githubusercontent.com/assets/9433472/13090342/1d1601f4-d4ed-11e5-9095-16e1d616c187.png)

SSP:
![image](https://cloud.githubusercontent.com/assets/9433472/13090353/2f8d1340-d4ed-11e5-82b0-625a32eda541.png)

**Comment by sczther** [comment]
What about modyfing Lato? It can't be that hard to add additional symbols...

**Comment by keysmashes** [comment]
It's under the [OFL](http://scripts.sil.org/OFL), so it's legally permissible as I understand it (I think the modified version would need to be renamed and under the same license).

**Comment by Alys** [comment]
I think it would be best for us to use a different font that already has all the symbols we need. That way we'd benefit in future from any other updates the font creator makes.

**Comment by tunefulTriangulist** [comment]
![image](https://cloud.githubusercontent.com/assets/10682461/13200000/7d24fc8c-d89c-11e5-926a-19bf02faddbd.png)

Source Sans Pro is a bit thinner and smaller than Lato at the same font size, so if we decide to change the font, maybe we want some minimal size adjustments?

PT Sans could also work, I think:

![image](https://cloud.githubusercontent.com/assets/10682461/13200108/9565c102-d89f-11e5-8d6b-b3297bed318e.png)

(I kept Lato for the task-column headings in that second screenshot, because I don't think there is a 300-weight version of PT Sans.)

**Comment by tunefulTriangulist** [comment]
If nobody else is working on this, and we agree on a font, I'm happy to commit the adjustments.

**Comment by Alys** [comment]
@tunefulTriangulist We should probably use the same font everywhere for consistency, so Source Sans Pro would be better if PT Sans can't be used for the headings (but we could probably use CSS to get around that problem).

@lemoness Are you okay for the font to be changed for better non-English support? Source Sans Pro has a lot of characters that our current font, Lato, does not have. It is not missing anything from Lato.

There might be even better fonts than Source Sans Pro but I'm not sure how much time would be needed to find a better one.

**Comment by ghost** [comment]
When applying the changes, could you please test the Cyrillic symbols as well

For what it's worth linking https://github.com/HabitRPG/habitrpg/issues/2956

**Comment by Alys** [comment]
@GitHubSphinx Can you please review [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro) to see if it has all of the characters required? If it does not, we should probably try to use a different font.

Everyone, I've added this information to the top post:

---

As described in https://github.com/HabitRPG/habitrpg/issues/2956, Cyrillic symbols are also not supported by the font currently used. Roboto is usually suggested to use alongside with Lato for latin-cyrillic pages.

http://www.google.com/fonts/specimen/Roboto
http://www.google.com/fonts#UsePlace:use/Collection:Roboto
It is licensed under apache license 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

Examples of pairings by google:
http://www.google.com/fonts/specimen/Lato#pairings
Droid Sans and Source Sance Pro look good, but I'm not sure if they support cyrillic

Refer to https://github.com/HabitRPG/habitrpg/issues/2956 for more details.

---

**Comment by ghost** [comment]
Well, some googling led me to the conclusion that Source Sans Pro is even a bit worse than Lato in terms of Cyrillic characters support. They both are reported to have dev branches with extended Cyrillic support which can be found on the web, but those are not incorporated (yet) in the Google fonts release.

So if you stick to Source Sans Pro by Paul D. Hunt, in order to get support for Cyrillics, the font should be recompiled to include Cyrillic characters from some branch from https://github.com/pauldhunt/SourceSansPro or maybe https://github.com/adobe-fonts/source-sans-pro

In addition Source Sans Pro is reported to have no italic for Cyrillic characters.

Sorry, don't have knowledge*time to investigate it deeper now

**Comment by tunefulTriangulist** [comment]
PT Sans supports Cyrillics, including italicized Cyrillics:

![image](https://cloud.githubusercontent.com/assets/10682461/13201975/08f05022-d8ed-11e5-8eee-905c115f2f30.png)

It lacks a 300-weight version, though. Open Sans has both a diverse range of weights and good special-symbol support, but it looks noticeably different from Lato:

![image](https://cloud.githubusercontent.com/assets/10682461/13202006/98adf10a-d8ee-11e5-90d7-0c5d3993b1a6.png)

Maybe, if we adjusted the font sizes for Open Sans (certainly a more tedious job than adjusting the font face, but doable), it would resemble Lato more closely.

**Comment by Alys** [comment]
@lemoness Does it matter if we use a font that doesn't look very similar to our current one? I would think not, but maybe there are branding reasons that make the exact font appearance important.

**Comment by tunefulTriangulist** [comment]
I was thinking that significant aesthetic considerations may have gone into the font choice. ;) Designers are picky like that, right?

**Comment by tunefulTriangulist** [comment]
**Update:** like GitHubSphinx indicated, Lato's newest release-- 2.015-- includes support for both carons and Cyrillic characters, including italic versions. (I tested them in the textareas on Lato's homepage.)

There are font files with only the new Latin characters in them:

![image](https://cloud.githubusercontent.com/assets/10682461/13202224/a4edfc0e-d8f7-11e5-9b7c-f391a15d801c.png)

Perhaps, if it's imperative to preserve the look, we could include LatoLatin font files with the static files for now, and return to using Google's API exclusively when the latter gets updated? Or would we prefer to avoid such promises?

**Comment by ghost** [comment]
@tunefulTriangulist I wouldn't hold my breath... This release may never make it to Google Fonts

**Comment by tunefulTriangulist** [comment]
@GitHubSphinx Hmm, yeah, fair point. We could permanently include the LatoLatin files. I suppose whether that's worth it depends how important the font is to aesthetics and branding.

**Comment by colwem** [comment]
So I go to the site, select Čeština as my language and I see carons everywhere.  Am I missing something or is this fixed.

**Comment by tunefulTriangulist** [comment]
@colwem The carons and Cyrillic characters get displayed in your system's default sans-serif font, because Google Fonts' version of Lato doesn't support them. The issue here is purely aesthetic-- the carons are displayed in a different font from the other characters, and so look out of place.

**Comment by ghost** [comment]
@colwem you can see an example of how it may look like in the first message of https://github.com/HabitRPG/habitrpg/issues/2963

**Comment by lemoness** [comment]
@Alys It would be nice if it were a sans-serif font that looks fairly similar to what we have. Would also like to hear if @AnitaYCheng or Sara have any thoughts/ideas for fonts that might work.

**Comment by tunefulTriangulist** [comment]
@lemoness It's possible to get the non-English support we want with the font that we have, if we use the newest version of it. We'd need to add some static files, though, because Google's API still uses the older version. Would that be preferable to a font change?

(I spent some time browsing Google Fonts, and it might be hard to find a perfect fit-- after all, the less popular a font is, the less likely it is to support Latin characters, so we may be out of luck if we can't find anything among the popular fonts. Best bet is probably Open Sans, if we'd rather keep using the API, but it doesn't look quite the same as Lato.)

**Comment by Alys** [comment]
@crookedneighbor @paglias @SabreCat Any objections to the suggestion above from @tunefulTriangulist about using the latest version of Lato as opposed to Google's version?

**Comment by crookedneighbor** [comment]
One benefit to using Google's is that it is very popular and many users will have it cached on their browser from visiting other sites that use it. If we host our own, we don't get that benefit. 

Not that we shouldn't, but that's really the only reason I can think of to stick with Google Fonts

**Comment by tunefulTriangulist** [comment]
@crookedneighbor Yeah, I was thinking that too. But we don't need to get rid of the API, I don't think-- Lato's newest release includes font files with _just_ the new Latin characters in them, so, in theory, we'd only need to host those.

**Comment by sczther** [comment]
Any news on this?

**Comment by librarianmage** [comment]
Not sure how close it is, but we could look into the new-ish [Noto](https://www.google.com/get/noto/) font. It looks kind of close to Lato, and supports over 800 languages.

**Comment by paglias** [comment]
@MathWhiz yes, i saw that too! We're considering it for the redesign

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this is one of the things we're considering during it. Even if that project doesn't change the font, afterwards there'll be new code that will need to be modified to fix this issue.

**Comment by librarianmage** [comment]
Does this still happen, with the new font?

**Comment by librarianmage** [comment]
After doing some quick 'testing', it appears to have been fixed.

**Comment by paglias** [comment]
Comment if it happens again and I'll reopen the issue
