### ISSUE TITLE
Cant see all of the members in my guild

### ISSUE THREAD

**Issue by Zax133** [HabitRPG/habitica#6711]
Hi. I've created the EZ Street Gang Guild and it now has 93 members, but for some reason when I go to the page and look under the members, there are a good number of invited people, but only 14 actual members listed. There are users that I know are in the group and are posting, but their names to not appear under the "members" list.

I have to send out a couple gems to winners of a challenge, but I can't see their names.

Any ideas why this is or if there is another way to find these  users to send them their gems?

**Comment by joeywoneill** [comment]
Hi! Guild membership lists are limited to preserve server space. If you have to send them gems, you can ask them to post in the chat so you can click on their username and send them gems from there.

**Comment by joeywoneill** [comment]
close #6711

**Comment by joeywoneill** [comment]
`close #6711`

**Comment by Alys** [comment]
@Zax133 The information from @joeywoneill is correct, and that recommendation is the best way to give them gems (although you mentioned that you know they're posting so you can probably see their name in chat already). We have an issue logged for changing this feature at https://github.com/HabitRPG/habitrpg/issues/1806 so I'm closing this one now. You're welcome to comment on that other issue if you wish.
