### ISSUE TITLE
Group leader message width not rendering properly in Firefox

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#6712]
As reported by Sphinx, and I confirmed, the group leader messages at the top of guild pages is not rendering properly in Firefox. The [CSS: line 5](https://habitica.com/app-bf28709d.css) says "table {max-width: 100%;}" but in my Firefox browser the table always renders at width 194. I copied the markdown of the leader message from [Aspiring Linguists](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) to my local install and was able to duplicate the problem there as well: width is rendered to some hard number relative to zoom level in Firefox, but in Chrome it renders to 100% width (up to 1095px, at which point it remains at 1095px even if the zoom level is so small that it could be wider).

**Comment by Alys** [comment]
This has been reported here: https://github.com/HabitRPG/habitrpg/issues/6708
You might like to add your comment to that issue.

**Comment by ghost** [comment]
@DrStrangepork thanks for investigating it! you findings were added to my report. Please excuse me for not letting you know in the guild chat.
