### ISSUE TITLE
Guild Join Area Says Join and Leave

### ISSUE THREAD

**Issue by joeywoneill** [HabitRPG/habitica#6713]
Sometimes in a guild join area, it says Join and Leave at the same time. ![screen shot 2016-02-12 at 3 20 56 pm](https://cloud.githubusercontent.com/assets/10093125/13029919/4596ad28-d24e-11e5-9afe-9e0cf3ad2535.png)

**Comment by khipkin** [comment]
@joeywoneill I'm having trouble reproducing this.  Can you give more details?

**Comment by joeywoneill** [comment]
@khipkin This happens randomly and I don't know why it happens.

**Comment by colwem** [comment]
I've also seen this happen.

**Comment by paglias** [comment]
Please comment if it happens again
