### ISSUE TITLE
I died while resting at the inn

### ISSUE THREAD

**Issue by hogglea10** [HabitRPG/habitica#6715]
I've been napping for several days now and I logged in today to find I've lost a level, gold, equipment, etc, even though I'm clearly resting in the inn.
[habita error.docx](https://github.com/HabitRPG/habitrpg/files/129547/habita.error.docx)

**Comment by Alys** [comment]
If you're in a boss quest, then you can still take damage from the boss from your party members' missed Dailies. There's a bit of information about that on the Tavern page on the website where you check into the inn, and more on the wiki at http://habitica.wikia.com/wiki/Rest_in_the_Inn

If that doesn't explain your death, please tell us your User ID (go to Help > Report a Bug from the Habitica website and see step 6). 

BTW, I'm not able open the docx file you linked to. If it contains an image that shows error messages, can you please drag the image into a comment here? If it contains error message texts, please paste the text into a comment.

**Comment by hogglea10** [comment]
[image: Inline image 1]

Looks like my friend did indeed take a significant damage, to the extent I
can only imagine it was in error.  I'll have to ask her about it.

**Comment by Alys** [comment]
The "Advice" section near the top of this image https://github.com/HabitRPG/habitrpg/issues/4313 will help you both recover from unfair damage.

I'm assuming that explains your death, so I'm closing this now, but comment here again if it doesn't. If the image is still relevant for us to see it, please drag it into a comment here.
