### ISSUE TITLE
Task title is overwritten whenever I try to edit it

### ISSUE THREAD

**Issue by mkwray** [HabitRPG/habitica#6719]
I have a problem where when I'm entering the title of a task, it keeps disappearing and being overwritten by the word "on".  This only happens when I'm editing a task.

In addition to the title, some of the subtasks are also overwritten -- usually not all of them, but some of them.  If I retype the information, save the task, and then go back to edit it again, it's the same subtasks that are being overwritten. 

This happens when I first pull up the task to edit it -- the text I had written for the title and subtasks is overwritten, and the word "on" appears in their place.  "on" also appears in the date field.

It's always the same word: "on".  

Sometimes this problem happens more frequently, every time I edit a task.  Other times, the program will go for many hours without a problem...then suddenly, the problem will come back.  This has happened over the course of the past 2 weeks.

I've tried restarting my computer, restarting my browser, clearing the cache, logging out & back in of Habitica, and nothing seems to help.

I've attached a screenshot so you can see what I mean.

Do you have any suggestions for what I could do?  Otherwise I'm really enjoying the game, but this makes me concerned about continuing to use Habitica, because I worry that tasks with lots of information may accidentally be deleted anytime I try to edit them.

My User ID is: 5db16a77-e200-49b7-9907-0686c52f32be

I am using Chrome browser, Version 48.0.2564.109 (64-bit)

![screen shot 2016-02-15 at 11 34 55 am](https://cloud.githubusercontent.com/assets/17171266/13055992/8034b5e0-d3e0-11e5-934d-f0cf82f2e526.png)

**Comment by Alys** [comment]
@mkwray I'm so sorry about that - that's a very weird error! It will be related to the frequent server errors we are having, and we're documenting our progress on preventing them in this issue: https://github.com/HabitRPG/habitrpg/issues/6700 . This comment in that issue has our latest update: https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-184375608

When it happens, the best thing you can try is logging out of Habitica, and clearing cookies might also help. Restarting your computer or browser, or clearing the cache are unlikely to be worth trying. You might find that a different browser performs better. However when we can solve the rash of errors we're getting, I'm hoping this "on" problem will disappear.

I'm sorry I can't offer any better help at the moment.

**Comment by paglias** [comment]
Hopefully this is resolved, reopen if it happens again
