### ISSUE TITLE
Editing profile resets dialog back to avatar tab

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#672]
Steps to reproduce:

0) Click the avatar on the top bar
1) Click the 'Profile' tab
2) Click the 'edit' button
3) Click the 'blurb' text area'
4) Type any character (eg, 'k')
5) The character is accepted, but the dialog then resets back to the 'avatar' editor.

Currently happening on both firefox 19.0.2 and chromium/24 (both on Ubuntu Linux)

In case this is just affecting me, my username is 'pjf'.

**Comment by lefnire** [comment]
This should be fixed on https://beta.habitrpg.com/ (and later merged into master). It's part of an overall issue I'm diagnosing presently ([notes here](https://workflowy.com/shared/a53582ea-43d6-bcce-c719-e134f9bf71fd/))

**Comment by pjf** [comment]
And this seems to be fixed on live as well.  Thank you! <3

**Comment by lefnire** [comment]
Oh woa.. Haven't yet pulled into master, i'll investigate

**Comment by pjf** [comment]
Oh no, it's back. :)

I also wrote a command-line client in Perl, but that's for another ticket. :)
