### ISSUE TITLE
allow attribute points to be allocated from within level-up modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6720]
As suggested by David Barnett on Trello:

**Can the "Leveled Up" dialog embed a small input for attribute points allocation?**

The attribute allocation section should appear only if you don't have automatic allocation turned on.

**Comment by keysmashes** [comment]
How much of the existing stats page UI should be in the dialog? Presumably we just want the number of points (un)allocated and buttons for each attribute, leaving out the 'automatic allocation' checkbox and 'change class' button?

**Comment by dbarnett** [comment]
+1
I'd be in favor of even condensing it down further from there, maybe 4 very small buttons with all the explanation on hover, like

```
Allocate 1 point: [STR] [CON] [INT] [PER]
                      \_ [[Allocate point to Strength]]
```

**Comment by keysmashes** [comment]
I've made an initial version (sorry about the second screenshot being dimmed, screenshots of tooltips are hard):

![image](https://cloud.githubusercontent.com/assets/9433472/13095012/9a7565a4-d506-11e5-9151-0b5deee314b9.png)

![image](https://cloud.githubusercontent.com/assets/9433472/13095075/09d3df16-d507-11e5-925f-f5aef55f1b5d.png)

I'm open to suggestions about where the 'allocate attribute points' block should go (above or below the 'huzzah'/close button), or basically anything else about the dialog (what colour should the buttons be? what should go in the tooltip? what order should the buttons be in?).

**Comment by Alys** [comment]
I think it's important to show how many points are allocated to each stat already. For me, that always influences which stat I increase. I see that you have the current number on hover, but we've found that people don't always notice hover text, and hovering over each button to compare all the points won't be as convenient as seeing them all at once.

I also think it would help people understand this new feature if it had a very similar appearance to the form on the Stats page. If they look different, we're likely to get repeated questions about whether the effects are different.

Can you try replicating the existing form onto the modal? You're right that the 'automatic allocation' checkbox and 'change class' button can be left out.

**Comment by keysmashes** [comment]
I did try that first, but it takes up a large amount of vertical space. That might not be an issue, depending if you have a strong preference for modals to scroll or not (or if you object to the social buttons not being above-the-fold).

![image](https://cloud.githubusercontent.com/assets/9433472/13109787/6ceead12-d573-11e5-8a1b-6efa2e4f3eed.png)

The tooltip on 'unallocated attribute points' might also need reworking/removing, as it mentions automatic allocation.

**Comment by rmkoske** [comment]
(Sorry if I'm intruding)

What about a button that says "you now have X unallocated points.  Want to allocate them now?" that takes you to the regular spot instead of totally integrating allocation on the modal? (Or does it already do that? I can't recall how mine is set.)

**Comment by keysmashes** [comment]
That would avoid code duplication, but going to a new page means a several-second delay while it loads, and I assume the point of the feature request was to avoid that wait. It's a good idea though :)

**Comment by Alys** [comment]
Hmm, yes, scrolling would be bad, and that table does take up a lot of space. It doesn't have to be exactly the same code / appearance though - just something similar enough to be quickly recognisable. Can you try using a smaller button style for the '+' buttons, instead of .btn-primary? It would probably also look better without the table striping.

**Comment by keysmashes** [comment]
Even with the smallest buttons Bootstrap provides (.btn-xs), the dialog still scrolls:

![image](https://cloud.githubusercontent.com/assets/9433472/13128490/ffe2c216-d5cd-11e5-98ac-541f91c58c14.png)

If we remove the padding underneath the table, all content is visible (but there's still a scrollbar):

![image](https://cloud.githubusercontent.com/assets/9433472/13128558/7f8adf4e-d5ce-11e5-81c7-1d8915fe99d8.png)

Padding above and beneath the 'don't show again' checkbox and above the table has to be removed to stop any scrolling:

![image](https://cloud.githubusercontent.com/assets/9433472/13128608/ecc1bf92-d5ce-11e5-8f60-e81b9eb743ab.png)

**Comment by crookedneighbor** [comment]
You could also use an accordion to hide the stat allocation stuff and only have it appear if you press an "allocate stats" button or something. That would keep it fairly clean unless you wanted to actually allocate your stats.

**Comment by keysmashes** [comment]
Using the default [Bootstrap collapse](https://getbootstrap.com/javascript/#collapse) works, for values of works:

![image](https://cloud.githubusercontent.com/assets/9433472/13161377/283c5dfe-d695-11e5-8a3a-59723194706b.png)

![image](https://cloud.githubusercontent.com/assets/9433472/13161383/33257138-d695-11e5-85e7-c74e91db35b2.png)

If that looks OK, I can fix the padding and make it i18n-friendly (and try to work out why it does weird stuff to the favicon...)

**Comment by Alys** [comment]
I like that!

**Comment by keysmashes** [comment]
Before level 10, stat allocation isn't shown:

![image](https://cloud.githubusercontent.com/assets/9433472/13174749/bc4eef76-d6fd-11e5-98b3-d641da801ec1.png)

At level 10, the dialog isn't shown at all, but from 11 onwards, the stat allocation is shown:

![image](https://cloud.githubusercontent.com/assets/9433472/13174796/fcf7c084-d6fd-11e5-908a-677e93466cb9.png)

![image](https://cloud.githubusercontent.com/assets/9433472/13174810/0f9f1214-d6fe-11e5-80ec-b1a08a8e3d95.png)

After level 100 (dialog isn't shown at 100), the standard warning about 'no more attribute points' is shown, the same as the stats page:

![image](https://cloud.githubusercontent.com/assets/9433472/13174888/91f205be-d6fe-11e5-88d4-ee4ef356c4f6.png)

When there are no more points to allocate, the plus buttons disappear (which I think is the same behaviour as on the stats page):

![image](https://cloud.githubusercontent.com/assets/9433472/13174863/63d0de62-d6fe-11e5-812f-5c960bf395cb.png)

The show/hide allocation button doesn't appear if you opted out of classes or have automatic allocation enabled.

Tooltips on the buttons are the same as the stats page (i.e. 'Add a point to Strength/Intelligence/etc.'), as is the tooltip on 'Unallocated Attribute Points' -- do you think it's worth creating a new string so that it doesn't mention automatic allocation, given that's not visible on this screen? Currently it says

> Each level earns you one point to assign to an attribute of your choice. You can do so manually, or let the game decide for you using one of the Automatic Allocation options.

**Comment by Alys** [comment]
All of that sounds great!

I think it is worth creating a new string so that the hover text is customised, however it's probably worth saying something about how you can go to the User > Stats page to change the allocation method.

**Comment by dbarnett** [comment]
This is beautiful! Thanks all three of you for making it happen (or however many people actually contributed to it).

Fair warning, I will be asking for something like this from the Android app as well. =)
Even just a simple web link to https://habitica.com/#/options/profile/stats would be an improvement for me.
