### ISSUE TITLE
Cannot rearrange tasks when editing a challenge

### ISSUE THREAD

**Issue by brianminsk** [HabitRPG/habitica#6722]
This concerns editing the tasks in a challenge. Though the cursor changes while hovering over a task there is no way to move it. Also, the Push Task to Top arrow does not work.

UserID 8da9ca27-8fdd-4612-936e-0ed56241d9d7
Chrome Version 48.0.2564.109 m
Windows 10 version 1511

**Comment by Alys** [comment]
We have this issue recorded at https://github.com/HabitRPG/habitrpg/issues/1703 so I'm closing this one now.
