### ISSUE TITLE
Cannot add multiple tasks when creating or editing a challenge

### ISSUE THREAD

**Issue by brianminsk** [HabitRPG/habitica#6723]
When editing a challenge clicking Add Multiple does nothing.

UserID 8da9ca27-8fdd-4612-936e-0ed56241d9d7
Chrome Version 48.0.2564.109 m
Windows 10 version 1511

**Comment by colwem** [comment]
I can confirm that this happens.  I'll look into it.

**Comment by makkoi** [comment]
I agree, I also cannot add multiple tasks when editing a challenge that I own. I am not even given the option to add multiple tasks. It doesn't show up.

![screen shot 2016-05-28 at 1 46 18 pm](https://cloud.githubusercontent.com/assets/19537840/15629276/ab48fef8-24da-11e6-973e-e9796ef022c4.png)

user ID: b3e66733-ab6f-432f-a052-6fa64585da5a
Browser: Google Chrome Version 50.0.2661.102 (64-bit)
OS: Mac OS X Version 10.9.5

**Comment by paglias** [comment]
Is this still happening?

**Comment by crookedneighbor** [comment]
Yes. There is a pr to fix it.
