### ISSUE TITLE
Randomly starting new day outside of 24hr cycle

### ISSUE THREAD

**Issue by AnnaLink** [HabitRPG/habitica#6725]
When I log on use multiple devices it seems to sometimes through off my 24 hours cycle.  For example I am in a quest and I finished my dailies, around midnight it tallied my score for the day on android.  When I logged on the next morning on the PC it tallied it again even though it was only 11 hours later.  Obviously I hadn't completed any activities and this just about killed me and the rest of my party.  Username AnnaLink

**Comment by Alys** [comment]
The first thing to check is that all of your devices are set to use the same timezone. Can you please go to Settings > Site in your PC's browser (https://habitica.com/#/options/settings/settings ), then reload the page (to make Habitica pick up your time zone from your PC), and then look at the "Time Zone" section at the bottom left of that page. Please read that section carefully and repeat the check on your mobile device(s), including the reload step which is important. Let us know what that tells you.

**Comment by AnnaLink** [comment]
Where do I check it on the app?

**Comment by Alys** [comment]
You can't check it on the Habitica mobile apps. Please check it on a browser on your mobile devices.

**Comment by AnnaLink** [comment]
They were on different time zones. They are on the same now.

**Comment by Alys** [comment]
Great! Thanks for letting us know! This will fix the problem.
