### ISSUE TITLE
Why are compiled spritesheets part of the Git repo?

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6726]
It seems odd that every time a sprite needs to be changed, the spritesheets and CSS have to be compiled and committed; this makes changing sprites at the same time as other people awkward, as any change to upstream sprites while you have commits that also modify sprites will always conflict, regardless of if you actually changed the same sprites or not. It would make more sense to me if `gulp sprites:compile` (or whatever the command is) was run before starting the server.

**Comment by Alys** [comment]
See common/README.md for the reason ("Because of some wonkiness with Heroku...").

We'll change this if we move off heroku.
