### ISSUE TITLE
Problem to persist Due Date on Mobile

### ISSUE THREAD

**Issue by aramizu** [HabitRPG/habitica#6727]
Hello,

I'm trying for many times persist due date for TODO list on Android but always return to current date. Changing on Web and synchronizing on Mobile is ok.

**Comment by Alys** [comment]
Thank you for letting us know but we have this reported in the Android repository at https://github.com/HabitRPG/habitrpg-android/issues/417 so I'm closing this one now. There'll be a fix soon.

If you'd like to report future bugs there, you can get to the repository at https://github.com/HabitRPG/habitrpg-android and that link is recorded permanently near the top of the Habitica website's Help > Report a Bug page.
