### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by RaphaelBatagini** [HabitRPG/habitica#6728]
In the mission "A basi-Lista" there is a text where is writen "causa DANDO no Chefão". The correct sentence should be causa DANO no Chefão.

**Comment by Alys** [comment]
@RaphaelBatagini Thank you for letting us know! I've notified our translators in the [Commonwealth of i18n - Aspiring Linguists of Habitica](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) guild and someone will fix it from there. You'd be welcome to join that guild if you'd like to, and/or become a member of the translation team - you can learn about how to help with translations in the wiki's [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists) page.
