### ISSUE TITLE
Role Models #white label #suggestion

### ISSUE THREAD

**Issue by rewdra** [HabitRPG/habitica#673]
Feature suggestion: Role model or Archetype templates/modules.

Players could activate or unlock a Role Model template that comes with preset habits, behaviors and progression paths (as skills/habits are mastered new ones are unlocked).

Want to be a coder? A fitness buff? A permaculture consultant? Unlock that Role Model and start playing from lvl 1 to 60.

Inspired by my college and MMORPG experience-

MMORPG: I have the end character in mind, in terms of gameplay playstyle, when selecting my player class and skill progression. Want to be a super strong melee due on the front lines? Better pick that barbarian bruiser. Want to have lots of utility and team support skills and spells? Better pick that cc/healer cleric.

COLLEGE: I also had this experience going to school with students in an undergraduate Sustainability degree. I observed there were a few different 'Paths', 'Tracks' or Sustainability Archetypes that students could pursue (these weren't made explicit within the program). A few examples of these Archetypes include:
- Community Sustainability Consultant (a sustainability generalist/consultant)
- Energy Systems designer/installer (more vocational/applied)
- Sustainability Policy (business or government sustainability policy writer/consultant)
- Non-profit Community work (emphasis in non-profits, grant writing, community activism)

If these archetypes were described up front to new students they would have had an easier time figuring our which track they resonated with. Further, the school could have set up courses, in-house or third-party certifications, and extracurricular projects or cross functional teams that embraced these archetypes/tracks. Students would have a good idea of their end-state and be able to intuitively pick up courses, certificates, internships, etc. that contributed towards being the type of Sustainability professional they were most excited by.

Instead many students took a hodgepodge of courses that were presented on equal footing as "sustainability classes" and lacked a coherent vision of what their final degree was culminating towards. This dissatisfying experience/sentiment was verified verbally by many students.

This feature has use cases relevant to educational and professional institutional settings. (Business Model # 2) 
eg, Company A could create a "Manager Archetype" with predefined habits, behaviors, and progression routes. Or simply make the progression routes within the company explicit and transparent via the habitrpg format. "From new employee to VP of product development in 1 year."

Outside of an institutional setting, Role Models / Archetypes could be developed privately by a knowledgeable professional (eg, a coder) and they could collect a royalty based on a "pay-per dl" purchase. Alternatively, archetypes could be setup as a more open, evolving, model with multiple contributors or wiki style contribution

This feature could be monetized as:
- premium version (premium user has access to role model library)
- pay-per role model (normal user buys a role model for $2)
- role model custom suite (development contract fee from company client)

**Comment by rewdra** [comment]
Gave it some thought and I think this can be broken into two discrete features relating to Quests:
- Quest Editor
- Quest Export/Import

-=Quest Editor=-
Want to get an 'A' on that final paper? How about getting into one of your favorite colleges? Create a Quest!
Quest Editor supports the design of quests. Quests involve a series habits, dailies, or todos that are all part of a larger goal. From the Quest Editor page you can design a quest by adding all the habits, dailies and todos that support you in completing your goal, the goal of the Quest. These todos could be a progression of steps 

Example of ToDos that would be added for the Apply to College Quest:
1. Talk with Guidance Councilers
2. Research difference schools
3. Create list of top 5
4. Contact top enrollment center
5. Take SATs & ACTs
6. Organize College visit trip
7. Start working on applications
8. Send off applications by deadline

You could also imagine how there could also be habits and dailies associated with this Apply to College Quest (studying, volunteer time, etc.) 

From the quest screen you could manage the progression of ToDos (prerequisites) via drag and drop, set rewards, penalties and deadlines. When one ToDo is completed the next ToDo in the quest automatically populates an active ToDo slot.

This could be integrated with the #tagging system currently being worked on. Activities could be added to a quest category through the tagging system. All tagged activities would show up on the Quest Editor screen.

Manager Account / White label: The Quest Editor could be the screen that teachers or managers use as well.

-=Quest Export/Import=-
As the name implies, people can export quests they've created or import ones others have designed.

**Comment by lemoness** [comment]
I really like this! I think it would be an excellent GTD feature :D

**Comment by rewdra** [comment]
Cool.

I think it would bring a very unique flavor to life planning. I've never
seen anything like it. I can write up some more if needed.

**Comment by rm909** [comment]
Careers Team in my college will definitely love the Quest feature.
Maybe quests can be done in parties?

**Comment by wizonesolutions** [comment]
Ooh, so questing basically brings light project management features to Habit :)

That could even be fun professionally with some clients.

**Comment by deilann** [comment]
Can this be moved to Trello?
