### ISSUE TITLE
Removed from being party leader; position is now vacant

### ISSUE THREAD

**Issue by LupusCallidus** [HabitRPG/habitica#6730]
I am the leader of 6317ed2d-0cf8-4c16-9a72-bb1cc430ef89 but was kicked out of the position by a glitch when renaming the group using the ios app. How can I be reinstated as leader?

Thanks,
Lupus Callidus
6b0b7171-e5e7-4f55-9f47-a07671cfe0c7

**Comment by Alys** [comment]
Thanks for the information about when this happened! I've added it to the issue for this bug: https://github.com/HabitRPG/habitrpg/issues/6313

I'll put you back as the leader. If it happens again, could you please comment on that issue?
