### ISSUE TITLE
Item Missing

### ISSUE THREAD

**Issue by eklingen88** [HabitRPG/habitica#6731]
I had the Dragon Tamer Helm and it is suddenly missing.  This isn't the first time an enchanted armoire item has gone missing.  I can't think of anything that would have caused this to happen on my end.

Please advise.

**Comment by Alys** [comment]
Hi @eklingen88. Please see https://github.com/HabitRPG/habitrpg/issues/5376 for an explanation of the problem and how to avoid it (just read the bold text near the top of the issue). In brief, the Armoire doesn't always correctly tell you which item you received.

If you wish, you can use Settings > Site > Fix Character Values to give yourself back the 100 gold you had spent on it.

**Comment by eklingen88** [comment]
I've had that happen to me before.

It's worth mentioning that at one point I even had the Dragon Tamer Helm
equipped.

Can't remember whether or not it was in the same session though.

**Comment by Alys** [comment]
It is possible to equip an item, and even keep wearing it for a while, before the website syncs with the server and it's removed.
