### ISSUE TITLE
Typo on Time Travelers feature

### ISSUE THREAD

**Issue by Venguis** [HabitRPG/habitica#6734]
I have found a typo in the "Time Travelers" feature (Inventory>Time Travelers) at the very bottom. I'm pretty sure it isn't intentional, but it says at the very bottom for the Steampunk  standard and accessories sets that they are for the year 3015, not 2015. I can't add a picture because you need to hover over one of the items and I can't do that while snipping. You should probably see for yourself. Here is something I copy pasted: 

Eyewear Goggles
No eyewear could be fancier than a pair of goggles - except, perhaps, for a monocle. Confers no benefit. April 3015 Subscriber Item.

Please fix.

**Comment by Alys** [comment]
Thank you but it's intentional because they are time travellers. :)
