### ISSUE TITLE
Market Place #white label #suggestion

### ISSUE THREAD

**Issue by rewdra** [HabitRPG/habitica#674]
Suggested Features:
- Online Marketplace (good/gold exchange system)

Community members can post up things they are willing to exchange for gold.

Inspiration: When i was a 6th grade student my teacher had 'Headlee Bucks' that could be earned from various classroom activities/responsibilities or in a Harry Potter 'instant feedback' reward kind of way. These Headlee Bucks could be spent on homework passes, at a bi-annual auction of donated goods, and for trade between students. Students were given 30-60 minutes a few times a week for a student market place. My friends sold pencils, popcorn balls, japati bread, origami, math tutoring and tons of other things. Students also used Headlee bucks to buy magic cards from each other.

2nd Inspiration: Community Currencies projects such as Berkshares.
http://en.wikipedia.org/wiki/Complementary_currency

Applications:
Public/Internet wide (eg, bitcoins)
In a classroom (like the above story)
In a town/community (a local listing)

Community Application
A user or community could register (pay for?) a Community Marketplace Manager account and set up an iteration is his/her own community. For example, I could set one up for my town of 10,000 people, Iowaville.  I would be responsible for promoting white label, Iowaville, instance to my fellow Iowavillians. One people are using it and earning coins they can take place in a local marketplace of real goods and services facilitated via habitrpg coins.

Monetize/biz model
People could purchase coins to access goods and services available in the marketplace (like free to play shop games). I know we shifted away from the idea of coin purchasing but i think that may have been due to its relationship with other features.

**Comment by rewdra** [comment]
Elaboration on Community Application:

Deploying white label for communities could be implemented in tandem with community betterment projects (eg, Blue Zones -> http://www.bluezones.com/) to support better adoption rates.

Communities would pay a setup fee for their local instance or annual subscription free (or both).
Optionally a community manager could earn a % of habitrpg revenue generated out of that community depending on the monetization strategy. 

Business Model - I worked setting up a volunteer program in my town where volunteers earned access to exclusive coupons offers given by local business. Coupons were designed to make use of underutilized business capacity: off-peak hours or days, open massage or restaurant tables, stale inventory, etc. Coupons were purchased using points earned by volunteers doing volunteer activities. Program was monetized using a % of the coupon savings. (This type of coupon business model represents an enormous market. eg, groupon $1.6B 2011 revenue)

**Comment by wc8** [comment]
[Marketplace](https://trello.com/c/5R22kcxc)
I added a placeholder checklist item there also for the Community Market white label edition, linking back here.
