### ISSUE TITLE
503 Error "Server Unavailable"

### ISSUE THREAD

**Issue by pqhunter** [HabitRPG/habitica#6749]
Hey!  I'm getting a 503 Error "Server Unavailable"  I have tried refreshing the page multiple times without anything changing.

**Comment by CanuckMonkey** [comment]
Same problem here, have been refreshing for about 90 minutes now. http://www.downforeveryoneorjustme.com/habitica.com says the site is up, though, so I assume it's some kind of internal configuration error?

**Comment by ghost** [comment]
Yup, me too. Could get in about 6 hrs ago but not in the last 3.

**Comment by CanuckMonkey** [comment]
I still can't get onto the website on my PC via web browser (Chrome) but I just checked the Android app and it seems to be working fine.

Then I checked on my desktop using Firefox, and that gets the same 503 error as Chrome. Something with the browser application but not the mobile apps, perhaps?

**Comment by pqhunter** [comment]
I've been able to get on using the browser (Chrome) on my tablet, but no luck with Chrome on my computer.

**Comment by paglias** [comment]
@pqhunter @CanuckMonkey things should be better now. Can you try reloading the website?

**Comment by pqhunter** [comment]
It seems to be working now

**Comment by kawunngg** [comment]
i'm still not able to access the site... 

EDIT: new Android app says i have no internet connection and old App says syncing error.

**Comment by CanuckMonkey** [comment]
I just tried reloading twice in Chrome (second time a hard reload, Ctrl-F5) and am still getting the 503 error.

**Comment by keysmashes** [comment]
Try going directly to habitica.com again rather than reloading habitica.com/#/tasks. Worked for me, but YMMV.

**Comment by Nolori** [comment]
I'm not able to access habitica.com on Chrome, Firefox or Safari. I've tried restarting my computer and going to habitica.com rather than /#/tasks. I'm still receiving the 503 error. No reloads have worked for me either, even with the hard reload. I've also cleared my cache, which didn't fix the problem for me.

**Comment by ghost** [comment]
Working for me now on multiple iOS browsers: Safari, Firefox, Opera Mini, & Chrome.

**Comment by CanuckMonkey** [comment]
I started refreshing habitica.com (instead of /#/tasks) several hours ago as well, and I'm still getting the 503 error on the root site as of now.

**Comment by CanuckMonkey** [comment]
Has there been a DNS change or something? Maybe some of us are stuck waiting for DNS caches to be updated?

**Comment by citrusella** [comment]
I get fairly standard loading on my phone (that is, nothing seems out of the ordinary and the chat is recent) but am getting intermittently stuck behind syncs and 503 errors on the website via my PC.

**Comment by CanuckMonkey** [comment]
@paglias I just had a successful load on desktop on Chrome.

**Comment by citrusella** [comment]
I appear to be reliably into the site now as well.

**Comment by Alys** [comment]
This should be working for everyone now. If anyone is still getting 503 Service Unavailable errors, please comment again here.

**Comment by colwem** [comment]
Yeah, it's better now, but I seem to get these 503 errors very frequently at different times every other day.  The android app also seems like it's getting an error like this.  It doesn't say so but it very frequently tells me I'm not connected to the internet when I very clearly am connected to the internet.  My first guess is that It's communicating over the same api that's responding with a 503.  Also android tends to have trouble at the same time my browser does.

**Comment by Fractionless** [comment]
I'm starting to get the 503 error again. Running in Windows 10/Chrome.

**Comment by Luthien22** [comment]
I'm also getting the server error again. Mac OS Mavericks, Chrome. It's kind of sporadic. Sometimes I'll be able to get to my tasks page, but I'll receive an error message, other times I can't get to the website at all.

**Comment by ghost** [comment]
severe sync issues during past hour or so

**Comment by pqhunter** [comment]
I'm also getting 503 Error when I try and reload. I'm using Chrome on an
Android Tablet

**Comment by Fractionless** [comment]
Seems to have resolved on my account for the moment. If it returns I'll comment.

**Comment by Luthien22** [comment]
I'm having application issues again. At first I got the standard 503 Server Unavailable error. Now my browser is able to load Habitica most of the way, but isn't able to completely load it (I'm getting an application error.)

**Comment by pqhunter** [comment]
I am having the same issue as Luthien22.  I got the 503 error, I tried to
refresh and the site refused to load completely, and now I'm getting an
application error.

**Comment by Alys** [comment]
We're tracking this error now at https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this one. There's some advice at the top of that issue for anyone who experiences this problem.
