### ISSUE TITLE
Suggestion: Notes/annotations when completing habits

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#675]
I have habits which would benefit greatly if I were able to annotate why I marked them as completed. This might be recording how many push-ups I've done, which emails I responded to, what unhealthy food I just ate, or all manner of other things.  These don't need to influence HP/XP/GP, but they're great for information recording.

There probably needs to be some sort of activity log first before this is useful.

Super-bonus points if these are readable/writeable via the API. Most of the things I want to push into HabitRPG will be from automated programs watching my inbox/beeminder/trello/rememberthemilk/foursquare/etc.

Many thanks!

**Comment by wc8** [comment]
Like [this](https://trello.com/c/hXRlE9DB)?

**Comment by pjf** [comment]
Not quite. That sounds like entering quantitative data which can be graphed. I'm just after straight, freeform annotations which can be attached to events, and which can be viewed in a log. For example, if one of my habits is "1 pomodoro of useful work" then I can record what that useful work actually was.

**Comment by wc8** [comment]
Here you are: [Completion Notes](https://trello.com/c/C8dIB6JL).
Let me know if I missed something.

**Comment by pjf** [comment]
That looks awesome!  Thank you so much! :)

If your workflow involves closing github suggestions that have been moved to trello, then it would give me great delight for you to consider this closed.

**Comment by wc8** [comment]
Thank you, that is the workflow.
