### ISSUE TITLE
503 Error - Service Unavailable

### ISSUE THREAD

**Issue by kimboslice44** [HabitRPG/habitica#6750]
Hello!

In the past week I have been having problems with the website not syncing, I would put in a new task and it wouldn't save it. (there was a red box on the side telling me to refresh the page as it hadn't been saved or something like that) Now I cannot even go to the website. It gives me the following error:

503 Service Unavailable
No server is available to handle this request.

I have tried restarting my browser, but to no avail. The mobile site still works for me, on my android phone, so I am assuming that the site isn't down, just my instance of it. Thanks for your help!

**Comment by paglias** [comment]
@kimboslice44 things should be better now. Can you try reloading the website?

**Comment by kimboslice44** [comment]
I just retried, no change. I'll try restarting my computer.

**Comment by kimboslice44** [comment]
That did it! Thanks!

**Comment by Alys** [comment]
This should be working for everyone now. If anyone is still getting 503 Service Unavailable errors, please comment again on this issue where we are tracking the problem:  https://github.com/HabitRPG/habitrpg/issues/6749
