### ISSUE TITLE
Chrome Works but Firefox Gives 503 Error

### ISSUE THREAD

**Issue by J9fire** [HabitRPG/habitica#6751]
I've tried to log in to habitica.com through Firefox since early this morning, but I get a 503 error (no server available). I can log in fine with Chrome though.

**Comment by paglias** [comment]
@J9fire  things should be better now. Can you try reloading the website?

**Comment by Alys** [comment]
This should be working for everyone now. If anyone is still getting 503 Service Unavailable errors, please comment again on this issue where we are tracking the problem:  https://github.com/HabitRPG/habitrpg/issues/6749
