### ISSUE TITLE
HABIT Task Added by "Third Party Service"

### ISSUE THREAD

**Issue by Denice54** [HabitRPG/habitica#6752]
Have received 503 error server down for a couple of hours. FINALLY got back in and happened to see this "new" Habit at the bottom of my Habit List. Apparently from Github? All it shows is a User ID number (NOT mine). The "third party service" info is an associated comment. I want to DELETE this but wonder if it is safe to touch it!
![wth 20160221_01](https://cloud.githubusercontent.com/assets/17161142/13205562/cf2ee6d4-d8b8-11e5-9526-5d73b2e0e23b.JPG)

**Comment by Denice54** [comment]
This is the text comment associated with the task: "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task."

**Comment by citrusella** [comment]
I've never had to directly deal with one of those, myself, but from what I hear, they're safe to remove and weren't actually added by a service almost any of the time if they have a UID or task ID as the title

**Comment by Denice54** [comment]
Oops! CLOSED IN ERROR!

**Comment by Denice54** [comment]
Is it possible it's the actual code for a Listed Task? If so, I need to figure out which one and restore it! <smile>

**Comment by Alys** [comment]
@citrusella Is correct. It's safe and you can just delete it. No damage has been done to your account.

Please see this bug for details: https://github.com/HabitRPG/habitrpg/issues/1402

**Comment by Denice54** [comment]
Thanks, Alys! I looked for the bug before I put this in, but didn't find it. I'll delete and move on!
