### ISSUE TITLE
Missing gem-purchased avatar customisations

### ISSUE THREAD

**Issue by proarunas** [HabitRPG/habitica#6769]
Maybe two weeks ago I've unlocked two sets of customisations (ears/hair1). At some point after that whole ear set and one item from the hair set became locked again for no reason, without refunding the gems.

UserID: 8afffbf1-851e-4cef-92ba-9d79a49d4347

**Comment by Alys** [comment]
So sorry about this, @proarunas! We'll check back through the logs to confirm what happened and then once we've finished that, we'll fix it all up for you!

**Comment by Alys** [comment]
@proarunas Those items should now be appearing has purchased and available to use. Reload the site if you don't see that straight away. Comment here if they still don't look right!
