### ISSUE TITLE
Important Derby pro-tips

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#677]
@toebu @zakkain @switz @MrConcept, my lovely codesters! 

Been fixing some of the DOM bugs we're experiencing (editing profiles, tags, the duplicate rewards hack-fix, etc). Some random pro-tips, which y'all might already know but I found useful:

`{{_this}}` is for static binding (things that don't change, like `user.id`) and `{_that}` is for dynamic binding (updated every time the variable is changed).

There's a Derby bug with nested `{#each}` and `{#if}` live-bound blocks under certain circumstances. I'm still trying to figure it out, [here's the backstory](https://github.com/codeparty/derby/issues/215), and it's the cause for the tags issue (which I've mostly solved - I'll follow up with you Tobias, see https://github.com/lefnire/habitrpg/commit/494d5cecf9727b4579be396c0f10855f33f21195).

Most importantly! I learned this forever ago, but totally forgot. Every iteration of `{#each}` must print **exactly one** html element.
**Good**: 
`{#each _list}<li>{.name}</li>{/}`
**Bad**: 

``` html
{#each _list}
  {#unless .hidden}
    <li>{.name}</li>
  {/}
{/}
```

bad because when #unless evaluates false, exactly one item _isn't_ returned (0 items) - which breaks DOM bindings

``` html
{#each _list}
  <span>{.name}</span>
  <span>{.description}</span>
{/}
```

bad because 2 items are returned.

**Comment by lefnire** [comment]
self-destructing message!

**Comment by toebu** [comment]
Nice, those are some useful tips! Good work also on finding a work around for the tags issue.

**Comment by caycefischer** [comment]
![selfdestruct](https://f.cloud.github.com/assets/546495/276436/adef1036-90ac-11e2-81fc-7537cff6b9a7.gif)
