### ISSUE TITLE
Completed Quest "Dilatory Distress, Part 1: Message in a Bottle" haven't provided the item Finned Oceanic Armor (Armor) and Exp.

### ISSUE THREAD

**Issue by taciolobo** [HabitRPG/habitica#6770]
My Party has completed the Quest Dilatory Distress, Part 1: Message in a Bottle, but only a few members who have participated on the quest received the Rewards, and most don't.

**Comment by Alys** [comment]
We can help with this, but we need to be able to identify you and your party. Also, we have an issue for this open already, so I'm closing this one. Can you please add your User ID and Party ID to a new comment in https://github.com/HabitRPG/habitrpg/issues/4252 and mention "Message in a Bottle". To find the IDs, see step 6 of Help > Report a Bug. We'll then get that fixed up for you all within a day.
