### ISSUE TITLE
New start date when editing task after midnight but before cron is saved as start date - 1 on android

### ISSUE THREAD

**Issue by colwem** [HabitRPG/habitica#6772]
Not sure if this is an android specific issue or app wide issue.  Last night while changing the start date of a few of my tasks at about 1:00am I noticed that it always saved the date as a day earlier than I chose.  My guess is that this is a bug caused by an attempt to fix the problem mentioned in issue #5525. When you create a task towards the end of the "cron day" of the 24th you expect it to start on the "cron day" of the 24th even if it's actually the 25th according to the clock.  So a solution is to just automatically decrement the day when you're creating a task after midnight.  And this makes sense when the user isn't manually picking the start date.  However if he is manually picking the start date then this is a problem.  When I pick the 25th in the early morning of the 25th I expect it to start on the 25th "cron day" not the 24th "cron day".

**Comment by paglias** [comment]
This is probably an android-related issue, if it happens again it should be reported in the android repo
