### ISSUE TITLE
Intelligence could use a nerfing

### ISSUE THREAD

**Issue by spirograph** [HabitRPG/habitica#6773]
Observations:
- [This Mage guide](http://habitica.wikia.com/wiki/The_Keep:Mage_Guide) recommends putting everything into Intelligence. So far, no surprises, it's a Mage's primary stat.
- The Rogue guides [here](http://habitica.wikia.com/wiki/The_Keep:Merfy%27s_Rogue_guide) and [here](http://habitica.wikia.com/wiki/The_Keep:Rogue_Guide) also recommend putting everything into Intelligence. Fair enough.
- The [Healer guide](http://habitica.wikia.com/wiki/The_Keep:Healer_Guide) recommends putting everything into Intelligence as well. This is starting to get weird.
- And even the [Warrior guide](http://habitica.wikia.com/wiki/The_Keep:Warrior_Guide) recommends putting everything into Intelligence...???

There is something wrong with this picture.

I think the optimized build for each class should be meaningfully different, and the ratios used by our current class-based automatic allocation system should be used as a _target_ for what each class's optimized build should look like. (As opposed to Intelligence being so obviously useful that it eclipses all the other stats.)

I'm not sure I have any meaningful answers as to _how_ precisely to do this, but the question needed to be asked.

**Comment by Alys** [comment]
We're collecting suggestions for changes to skills (and hence to mana and attributes) on the feature request Trello board in this card: [SKILLS v3: Stat Rebalancing](https://trello.com/c/TjZc6PnC/466-skills-v3-stat-rebalancing). Can you please add any suggestions for improvements that you can think of to that card?

Note that all of the guides you have linked to are not official guides. Each one is created by one player and describes there personal opinions about how Habitica works best for them.
