### ISSUE TITLE
Markdown rendering of blockquotes could be improved.

### ISSUE THREAD

**Issue by colwem** [HabitRPG/habitica#6774]
The text just gets bigger which makes little sense for a block quote.  Should have a marker of some sort down the side to indicate that it's a quote and if anything the text should get less strong rather than more.  I'm a reddit user so I use 

> quotes like this

All the time to remind people of what comment I'm referring to.  Instead of being rendered like it is in github above it's rendered more

**Comment by ghost** [comment]
@colwem I see people make quotes with Habitica's markdown from time to time
![Screenshot](http://i.snag.gy/0IyA3.jpg)
Seems like _pre_ text. But it's not `>` which indeed makes a line look like a header

May it just be added to the http://habitica.wikia.com/wiki/Markdown_Cheat_Sheet at first?

**Comment by colwem** [comment]
Well there's no point in using the > feature until it works right?  So I think we should add it to the wiki after it's fixed.  At least when using reddit the `>` is easily the most useful piece of markdown syntax.

**Comment by colwem** [comment]
I made a change but I don't know if I should submit it when I don't know if it's wanted.  ![Here's](http://i.imgur.com/jtIaqqF.png) a screenshot of how chat will look if it's merged in

**Comment by Alys** [comment]
@colwem You're talking about using `>` at the start of text to indicate a blockquote? It already does have a marker in the places I've looked at it, but you're right that the font is larger.

It's hard to judge at the moment if we would want your fix, so submit a PR if you wish.

Note though that if you've changed the behaviour by modifying a third-party library that we're using, then we wouldn't be able to accept the PR.

**Comment by colwem** [comment]
@Alys I guess, you're right. It does have a bar down the side already.  No my PR doesn't modify a third-party library.
