### ISSUE TITLE
Changes to Community Guidelines

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6779]
It's time to make a few tweaks to the Community Guidelines! They are described below.

1 The following section requires an edit:

"Do not spam. Spamming may include, but is not limited to: posting the same comment or query in multiple places, posting links without explanation or context, posting nonsensical messages, or posting many messages in a row. Repeatedly begging for gems or a subscription may also be considered spamming."

It should become:

"Do not spam. Spamming may include, but is not limited to: posting the same comment or query in multiple places, posting links without explanation or context, posting nonsensical messages, or posting many messages in a row. Asking for gems or a subscription in any of the chat spaces or via Private Message is also considered spamming."

2 The following section needs an addition.

"In private spaces, users have more freedom to discuss whatever topics they would like, but they still may not violate the Terms and Conditions, including posting any discriminatory, violent, or threatening content." 

Add the following sentence to the end:

"Note that, because Challenge names appear in the winner's public profile, ALL Challenge names must obey the public space guidelines, even if they appear in a private space."

3 The following section needs an addition.

"Habitica has two kinds of social spaces: public, and private. Public spaces include the Tavern, Public Guilds, GitHub, Trello, and the Wiki. Private spaces are Private Guilds, party chat, and Private Messages." 

Add the following sentence to the end:

"All Display Names must comply with the public space guidelines. To change your Display Name, go on the website to User > Profile and click on the "Edit" button."

**Comment by andrewcham** [comment]
I'll take this as my first quest towards being a Blacksmith ;)

I noticed that some strings are duplicated across `communityGuidelines.json` files that are not located in `common/locales/en`. Do you want those strings to be updated as well?

**Comment by Alys** [comment]
@andrewcham Thank you! Please go ahead. Note though that you should only edit the files in `common/locales/en`, not in the other locales directories. See the _README_FIRST.md file in any of those directories for the reason why (in brief, all translations are handled in Transifex).

**Comment by andrewcham** [comment]
Got it, will update the PR, missed the README in huge bold letters ;)
