### ISSUE TITLE
Python module/CLI for HabitRPG (WIP)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#678]
I've started working on a CLI/module for HabitRPG in python, currently all the API methods are supported and you can call it from command line or import it.

https://github.com/xeross/python-habitrpg

Pull requests, suggestions, etc. welcome

**Comment by ghost** [comment]
And in my rush to cook something up I completely missed a pyhabit already existing.

**Comment by lefnire** [comment]
Will you be ditching yours and joining pyhabit's efforts? Or shall I put this one on [Extensions](https://habitrpg.com/static/extensions) ?

**Comment by ghost** [comment]
This depends on what the direction of @elssar wants to take it, if he's sticking to CLI this can exist alongside, otherwise I'll start hacking on his code.

**Comment by lefnire** [comment]
Cool cool, I'll let you follow up with him - hit me up on this ticket later
if you want me to put your module into the extensions page

**Comment by elssar** [comment]
That's interesting. I never thought about making pyhabit importable. Now I can see the different use cases that might have. Nice.

As for the direction, either is fine with me - I'd be more than happy to collaborate with @xeross . We can decide on whose code we want to work on and take it from there. Though pyhabit as a name sounds a little better IMO, so I suggest we keep that.

Let me know what you decide.

**Comment by rixx** [comment]
Since python-habitrpg doesn't exist anymore, I'd guess you now both work on pyhabit? In that case we might close this ticket.

(Also, let me know if I can help over there!)

**Comment by ghost** [comment]
Affirmative. I have renamed my version to pyhabit (https://github.com/xeross/pyhabit), however unfortunately both me and elssar have been a bit busy so it's almost identical to python-habitrpg except for the name

**Comment by rixx** [comment]
Ok, thanks, then I know where to go.

(Can you close this issue then? I always feel sorry for lefnire when I see the gazillion open issues.)
