### ISSUE TITLE
Change Menu Names

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6783]
We have a few changes that we need to make to the names of items on the drop-down menus, for the sake of clarity.

Here is a list of changes:
Avatar > Customize Avatar
Stats > Avatar Stats
Tavern > Tavern Chat
Hall > Hall of Heroes

This is probably suitable for an Aspiring Coder.

**Comment by keysmashes** [comment]
NB 'Hall' contains both the Hall of Heroes and the Hall of Patrons; the UI starts to look a bit weird (IMHO) when you have something like this:

![image](https://cloud.githubusercontent.com/assets/9433472/13380034/65e8a670-de2f-11e5-869b-0398009579f5.png)

I don't really have any ideas for how to make it better, apart from making the Hall of Patrons a top-level section:

![image](https://cloud.githubusercontent.com/assets/9433472/13380106/ec43331e-de31-11e5-9981-82f4e9be3ffa.png)

![image](https://cloud.githubusercontent.com/assets/9433472/13380109/f6910ca6-de31-11e5-9126-37b2a78e4a71.png)

I'm not sure if I think that looks better or worse.

**Comment by Alys** [comment]
pinging @lemoness

**Comment by nrbunn** [comment]
I agree the duplicate hall of heroes made it look weird. Another option would to be change some wording if you want to keep format. 
![menu_rename](https://cloud.githubusercontent.com/assets/8887847/13382253/83d784d4-de35-11e5-8d28-2c1478178dec.PNG)

**Comment by querry43** [comment]
This might be an opportunity for something new.  The Halls are kind of a dead end that most players would never visit, right?  I wonder if there is a way to build more community around it.

What if the hall was sorted not by tier but by the most recent contribution.  That would make it quite a bit more dynamic.  Then we could perhaps involve the community with "thank you" buttons that would send thank you card to the contributor.  I don't know about others, but I like to get feedback as an opportunity for improvement.

Since getting my badge, several people have asked about what they could do.  I get the impression that some additional dialog could energize parts of the community to contribute.  Aside from a little design work, including menu adjustments, this doesn't seem like much work given the existing thank you card mechanism.

**Comment by lemoness** [comment]
Why don't we call the top menu "Hall of Heroes" and then split it into "Hall of Contributors" and "Hall of Patrons."

@querry43 That's a very cool idea, but would need to be done in a different ticket, since that actually would be more complicated. (For example, right now the cards only work for your party members.) Still, I'd definitely be open to something like that in the future!

**Comment by Alys** [comment]
fixed in https://github.com/HabitRPG/habitrpg/pull/6793

**Comment by mandyzhou** [comment]
Hmmm, what was the rationale for the change to "Tavern Chat"? Now that I see the new menu items in action, I feel like "Tavern Chat" doesn't seem to convey that the page has other features, most notably the Rest in the Inn button. 

Also, the heading above the chat box says "Tavern Talk" -- not a huge issue, but it might be better to keep the wording consistent.

**Comment by keysmashes** [comment]
I agree. OTOH, I don't think "Tavern" conveys much to a totally new user at all -- I definitely wouldn't have had a clue what it was if the wiki hadn't existed.

**Comment by mandyzhou** [comment]
I see what you mean, but I think the same could be said about "Party" or "Guilds" as well. I found Daniel's message on the Tavern page pretty helpful when I first started; maybe we could include a link to the wiki in the message and make the message clearer/more prominent?

**Comment by lemoness** [comment]
I think it's worthwhile changing "Tavern Talk" to "Tavern Chat" to be
consistent! It was added because we wanted users to understand that it was
a public chat room. Although Rest in the Inn is currently located there, we
are going to explore having it in other places too (like under a Vacation
Settings page), so it's not as crucial to mention.

Recommendations for Guilds and Parties are welcome, but as those are more
complicated social features than the Tavern chat, which is at its heart a
simple chat room, we didn't find an easy way to relabel them. I'd be
curious to hear what you think!

**Comment by mandyzhou** [comment]
Thanks for clarifying, that makes sense! Hopefully those changes to Rest in the Inn will happen relatively soon so as not to confuse too many new users.

I see what you mean about Guilds and Parties being harder to relabel -- everything I can think of (e.g., "Common-Interest Guilds") is a bit too long. I'll let you know if I come up with anything, though!

**Comment by alexlarsongit** [comment]
FYI, I've made the wiki updates to reflect this change on the following pages: Acronyms, Avatar, Avatar Customizations, Chat, Hall of Heroes, Social, Staff, Tavern, Toolbar, User.  

Please ping me here or on Habitica (I'm Lexinatrix there) if you see more updates you think should be made to the wiki.  

Thanks!
