### ISSUE TITLE
Should subtasks should give gold?

### ISSUE THREAD

**Issue by howdoicomputer** [HabitRPG/habitica#6784]
Right now I'm spring cleaning my house. It's represented under a single task (todo) and has thirty subtasks. I'm about three hours in and really ready for a break. The task will probably take another four hours but it'd be nice to 'buy' a break in between all the subtasks.

**Comment by Alys** [comment]
Feature requests or suggestions like this are best given on Trello through Help > Request a Feature from the Habitica website's menu. That lets us collect similar suggestions from many players and develop new features to suit as wide a range of players as possible.

There are workarounds that you can use now though - to learn how some other players deal with this, ask in either the Tavern (from the Social menu) or the Newbies guild (Help > Ask a Question; it's not just for Newbies) - e.g., you can click a Habit each time you finish a subtask.
