### ISSUE TITLE
Purchased Items and Hatched Eggs Disappear

### ISSUE THREAD

**Issue by veryemmappropriate** [HabitRPG/habitica#6789]
On Friday 2/26 I purchased gems to feed my Skeleton Tiger Cub enough to grow into a Mount. I also used a White potion to hatch one of my Unicorn eggs and hatched a few other eggs as well. When I left the app and reloaded the page, the changes I had made were reverted--the Skeleton Tiger Cub was no longer a mount, my White Unicorn was reverted to an egg, but the potions that I used didn't reappear in my item inventory and the gold I used to purchase the (5) gems wasn't returned to my account. Please help!

**Comment by ghost** [comment]
Can you post your UUID, please? Go to Settings->API and post the first long gibberish number. DON'T post the second one, the API token, which is like a password.

Also, do you recall whether your gem cap went back up 5 as well? Basically, does the gem cap think you bought 5 gems, or not?

(I personally can't help you, but the people who can help you are going to ask those questions, and can't start without your UUID.)

**Comment by veryemmappropriate** [comment]
Yes, sorry! Thanks for letting me know. UID: 04e29307-702f-450c-add6-d832cde6494d

And no, my gem cap didn't go back up 5 either, so it's as if I purchased the gems and they just disappeared into the ether.

**Comment by jcmoore65** [comment]
Just happened to me as well.
UUID: bbde9cd8-1275-4dbf-be1c-00f43186bfaf
Bought the Monkey Quest, the site timed out/asked for a reload/Red application error screen. When I refreshed the scroll was gone as well as my Gems. :(

**Comment by Alys** [comment]
@veryemmappropriate I've given you the 5 gems you were missing, a Skeleton Tiger Cub mount, and a white Unicorn pet.

@jcmoore65 I've given you a Monkey Quest scroll. 

I'm closing this now, but if there's still missing items, or if these changes don't appear (reload the site first), please tell us! We'll see your comments and keep helping you.

@Cantras Thank you!
