### ISSUE TITLE
Beta feedback

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#679]
Sorry if there is a spot already used for feedback on the beta server, but I could not find it. And it probably deserves its own issue, so things don't get buried in some other thread...

Here's my first feedback, then.

Login: I was told that no such username exists; I typed in my password anyway and login was possible in spite of that message.

Interface: The new interface eats lots more space for me - my todo descriptions tend to be quite long (I blame you, German language!) and thus I often have two lines of text. In the production, that is not so bad - but in the beta, there's lots of space between the lines so I can see about 3-5 items max on the screen at the same time. Not helpful!

Plus-Minus buttons: Related to the space-eating issue, the +/- buttons are so large that they also often force the text into a second line. For my taste, they are much too big this way (though yes, that makes them easy to click) and seem much too important.

Font: I do not like the font used at all - it's weirdly thick and thin, the letter spacing and line spacing does not work for me, and I find it very hard to read. Sorry @zakkain but I'd even prefer Helvetica to that. Had the original Habit looked like that, I would not have started with it.

Sorry to have so much negative feedback! And now back to work - today wants to see at least one more item crossed off that list...

**Comment by caycefischer** [comment]
We are hearing a bit of feedback on the size issue... aside from maybe reducing overall padding _a bit_ I don't think that's going to change. The increased size is much more appropriate for touch interfaces and higher-res/larger screens in general, and overall legibility. The text-wrapping is currently not very elegant, that I definitely agree, but we're at a loss for a better option right now. I'm still working on it.

In general, you can zoom-out the UI by hitting cmd-minus on your keyboard (or ctrl-minus on Windows/super-minus on Linux). The UI will scale down pretty nicely.

Typography is still being worked on, I think you're right that the font-weight isn't ideal with all the colours going on.

Thanks for the feedback @wildcate :)

**Comment by wc8** [comment]
@zakkain maybe you got this, but just in case: I think it's not the size of the items in general @wildcate is having trouble with: but the spacing between the text. It could be a font issue.

![daily comparison](https://f.cloud.github.com/assets/3326182/276505/18fb026c-90ae-11e2-846f-5b7273634aaf.jpg)

Otherwise, with short (one line) names, I see just one more task on the old one than on the new one. The trade-off of one task overall for the gain of accuracy on zoom-out works in my favor. :+1: 

That said, a slight reduction of padding could be helpful. I'd love it if I could see everything without scrolling at a reasonable zoom-out on my large screen.

Related Font Size Suggestion: **_smaller Column Header**_ after all, once one knows what the columns are, does one really read the titles any more?

**Comment by wc8** [comment]
P.S. in the image above, that was supposed to be _lines_ not lives ;-)

**Comment by caycefischer** [comment]
Ohhh dang that's a really good point. Dat line height. I don't have any
wrapping tasks really, I didn't notice.

Noted, will patch!

_– Zachary Kain_

Designer, Developer
Writer, Educator
416-712-8895
zakkain@gmail.com
➝ http://draftingcode.com

**Comment by cleave29** [comment]
@zakkain , did you mean to leave your phone number and email on github?

**Comment by caycefischer** [comment]
@cleave29 I usually don't care about that stuff—where are you seeing my phone # though, it isn't on my profile O_o

**Comment by lefnire** [comment]
Email signature when responding to GH via email. Meh, people can find that
shit anywhere

**Comment by caycefischer** [comment]
Ohhh right

Yeah, yeah that's not a problem.

**Comment by caycefischer** [comment]
Thanks for the find guys! I totally forgot about that.

![tngohshit](https://f.cloud.github.com/assets/546495/282181/29962b42-918a-11e2-99a0-b6c65b62d078.gif)
