### ISSUE TITLE
Some habits progress have return to zero after server's problem.

### ISSUE THREAD

**Issue by BasilYinYang** [HabitRPG/habitica#6798]
## ENVIRONMENT

Win8, Ubuntu 14.04, GChrome Version 45.0.2454.93 (64-bit)
User ID: 93f4da09-fd0b-419f-ad7b-0ccb1c7ec224

---
## DESCRIPTION

As I know, today was problem with Habitica server. And now the progress of many from my habits return to zero. Could it be fixed?

**Comment by Alys** [comment]
In case you mean the colour of the Habits: Habits that are only negative or only positive (i.e., they don't have BOTH + and - buttons) will change colour back to yellow over time. This is to let you see when you haven't been doing positive Habits very often, and to let you see your good progress in avoiding negative Habits.

In case you mean that data points seem to have disappeared from the progress graph: That happens at the start of each month: data for the previous month is merged together to save database space.

If this doesn't answer your question, please let us know and give us some information about what you're seeing that looks wrong. We'll be happy to reopen this and keep helping you!

**Comment by BasilYinYang** [comment]
Thank you, very much, Alys!
