### ISSUE TITLE
Export Data

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#68]
The ability to export your data maybe be able to show it to a doctor for the habit of tracking blood pressure would be really useful.

**Comment by silverymoon** [comment]
I would love that option as well.

**Comment by ghost** [comment]
So would my doctor.

**Comment by yene** [comment]
+1 for this option for when the website is unstable. I would love export format to be a simple plain text.

**Comment by ghost** [comment]
I was thinking exporting to an excel spreadsheet

**Comment by Andrew565** [comment]
It would be relatively straight-forward to support multiple output formats. Plain text and HTML could be done with a simple template, just like creating a standard view. JSON is pretty-much a no-brainer to output too.

For excel, you can use [jQuery-CSV](https://code.google.com/p/jquery-csv/) to output to CSV, which is usable in Excel.

Once support for these has been prototyped, could wrap in an API.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Vote for [Import/Export request here](https://trello.com/c/29qEE1DF)
