### ISSUE TITLE
API acts weird when called over http rather than https

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#680]
- The API allows unencrypted http calls. This should probably be discouraged or disabled, since anyone could snoop API and user keys.
- When called over regular http, the type parameter in `/user/tasks?type=whatever` gets ignored. It works fine over https.

Suggested fix: Disable API access over unencrypted http.

**Comment by switz** [comment]
You shouldn't be able to access the API over http. Can you give us some more details?

nginx should kick in ssl long before it even hits express.

**Comment by pjf** [comment]
The easiest way I can demonstrate what's happening is with the `hrpg` command-line ( https://github.com/pfenwick/WebService-HabitRPG ).  (Note that HRPG_API_BASE is only supported in dev, so the following won't work (yet) on the cpan releases):

Using https:

```
$ HRPG_API_BASE=https://habitrpg.com/api/v1 hrpg daily
[ ] PatientsLikeMe
[ ] Moodscope
[ ] Update idonethis
[ ] 10 minutes Anki
```

Using http:

```
$ HRPG_API_BASE=http://habitrpg.com/api/v1 hrpg daily
 +  Go Shopping
 +  Laptop backup
 +  Exercise
 +- Are these public?
 +  Coursera Lecture
 +  Blog post
 +  Co-work somewhere (#office)
 +  Respond to email
  - Meat
 +  1 Pomodoro of paid work
 +  Floss Teeth
  - Junkfood
 +  1 Pomodoro of anything useful
 +  Dancing
[ ] PatientsLikeMe
[ ] Moodscope
[ ] Update idonethis
[ ] 10 minutes Anki
  * Adventure Time!
  * 10 pages comic rocket
  * 1 page of comic rocket
```

Under the hood these are both making the same `/user/tasks?type=daily` call, but over http I'm getting back everything!

If nginx is redirecting http https calls then the GET parameter is getting lost somewhere (which could actually be within my user-agent libraries). However I'd argue that we'd be better off with a flat out DENIED if we see any API call come in over http. Redirecting means people can accidentally write code that uses unencrypted connections (which is exactly what happened to me).

**Comment by switz** [comment]
Plausable fix in https://github.com/lefnire/habitrpg/pull/852 - will reopen if still an issue.
