### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by RaphaelBatagini** [HabitRPG/habitica#6803]
In the pt-br translation, when you defeat the Basi-Lista, is thrown a message with a grammatical error.

"A Basi-Lista se espalhou em recortes de papel, que brilham gentilmente em um arco-íris colorido. "Ufa!" diz @Arcosine. "Que bom que vocês estavam por perto!" Sentindo-se mais **esperiente** do que antes, você coleta um pouco de ouro do meio dos papéis."

Esperiente is incorrect, this should be **experiente**.

**Comment by ltorroba** [comment]
I added a suggestion to correct the typo here: https://www.transifex.com/habitrpg/habitrpg/translate/#pt/questscontentjson/37178595?qt=esperiente

Unfortunately the string seems to be reviewed already, so I cannot apply the change. I'll see if I can ask someone to look into it through Trello.

**Comment by RaphaelBatagini** [comment]
See what can be done, this is a gross portuguese error.

**Comment by paglias** [comment]
I've unreviewed the string

**Comment by ltorroba** [comment]
Should I update the common/locales/pt/questscontent.json file in the repo with the fix?
