### ISSUE TITLE
When current XP value is equal to the value needed to level up, leveling up doesn't occur until more XP is gained.

### ISSUE THREAD

**Issue by Dionamus** [HabitRPG/habitica#6808]
Say for example, I have 770/770 XP. I do not level up when I am at this value until I have gained more XP.

**Comment by Alys** [comment]
URGENT! :) If your account is still at that state, please don't do any more tasks just yet!

**Comment by Alys** [comment]
Okay, not really urgent, but it would be useful to see your account before you level up. :) 

Can you please give us your User ID? See Help > Report a Bug step 6 to find out how to get it.

If you have levelled up, are you certain that your XP was exactly 770, or was it something like 769.8?

**Comment by colwem** [comment]
Don't refresh the page either because that might trigger it also.

**Comment by Dionamus** [comment]
Too late now. :/

**Comment by rogefm** [comment]
I'm with the same problem.
I should level up at 150, and I'm with 283

ID:
f3f8fec1-6b34-4ee6-8808-438d71b5b3b6

**Comment by Alys** [comment]
@Rogerfm That situation arises when you go through the tutorial steps more than once. You'll level up as soon as you tick off a task and no Experience will be lost.

@sporto15 : You didn't comment on my question about what the exact XP was, and my own tests show that when you have exactly the right amount to level up, then you do level up, so I'm guessing that you did have slightly less than 770 XP and I'm going to close this now. If you're certain that you had exactly 770 XP (e.g., you checked the exact value in Settings > Site > Fix Character Values), please tell us. Please always include your User ID when reporting bugs as it can help us investigate rapidly.
