### ISSUE TITLE
Emoji?

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#681]
While I wait for [Tags](https://trello.com/c/q7v02jAw) & [Icons](https://trello.com/c/FCVdjdUd), I started using Emoji to highlight tasks on my task list (eg. :pill: :exclamation: :one: :two: :three: :postbox: :file_folder: :scroll:)

This, currently only works in Safari type browsers. I noticed recently that github and a few others [support emoji](http://www.emoji-cheat-sheet.com/) after a fashion. I wonder if there would be an interest in HabitRPG support for emoji characters within text fields like notes, titles and descriptions? 

Would this be difficult development-wise?

**Comment by snicker** [comment]
as of https://github.com/HabitRPG/habitrpg/commit/13a7292377cf16d14a475b9cdbac18d29d20d6ce, emoji works in all fields that support markdown... currently this is only profile blurbs and tavern chat. Possibly supporting emoji (but not the rest of markdown)

**Comment by lefnire** [comment]
Truth! We can close this one
