### ISSUE TITLE
About "To do"

### ISSUE THREAD

**Issue by rogefm** [HabitRPG/habitica#6810]
When you create a task "To do", the date don't save.

example:

I created a task "To do" with limit date 03/04, and today is 03/03. Now I will edit, when I open the task, the date is 03/03.

**Comment by Alys** [comment]
Is this on the Android app? If so, it's a known bug, and a fix will be coming soon.

If it's not for the Android app, please tell us!

If you'd like to report more Android app bugs in future, there's actually better ways than using this repository (not all of the app developers review this one). If you go to Help > Report a Bug from the Habitica website, you can see all the ways (in brief, an app menu item, or email, or the app-specific repo).

**Comment by rogefm** [comment]
Good morning, it's just in app android man.
Thanks mate.
Em 03/03/2016 00:55, "Alys" notifications@github.com escreveu:

**Comment by Alys** [comment]
Thanks @Rogerfm! You'll find that fixed in a future update, probably not too far away.
