### ISSUE TITLE
Spritesheet not getting resolved

### ISSUE THREAD

**Issue by Noah-Silvera** [HabitRPG/habitica#6812]
**Problem**
Items from this spritesheet https://habitica.com/common/dist/sprites/spritesmith-main-6-92e097bd.png are not resolved, and the images are missing on the site. 

![image 147](https://cloud.githubusercontent.com/assets/8933450/13487495/55cc1d88-e0cf-11e5-82a0-882ef4445032.png)

This occurs most visibly in the 'Market' page

**Enviroment**
Chrome 48.0.2564.116 Windows 8.1 Desktop Site

**Comment by Alys** [comment]
Thank you for giving that much detail!

We think it's connected with new servers that we're trialing.

I believe that this problem should fix itself in time, but I'd be interested to know how long it takes. If you notice those images appearing, can you please comment here to tell us when?

**Comment by Noah-Silvera** [comment]
I'm in QA, it's force of habit :+1: 
I'll keep an eye out.

**Comment by paglias** [comment]
This should be fixed
