### ISSUE TITLE
Inconsistency issues after menu name change

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica#6813]
Since the Tavern menu item was renamed to "Tavern Chat" (#6783), it might be a good idea to rename the "Tavern Talk" heading (above the chat box) to "Tavern Chat" as well for consistency. @lemoness  mentioned that this might be worthwhile to do here: https://github.com/HabitRPG/habitrpg/issues/6783#issuecomment-191456297

Additionally, it looks like the "Avatar Stats" and "Stats & Achievements" menu items/tabs refer to the same page (see screenshot below) -- should they have the same label? On that page, there is also one subsection (out of many) called "Avatar Stats" so the "Avatar Stats" menu item, which is supposed to refer to the entire page, is a little confusing.

![bug](https://cloud.githubusercontent.com/assets/279805/13537083/290634f8-e211-11e5-8aa2-6da8bacea8c3.png)

**Comment by ltorroba** [comment]
Seems like a matter of changing the following lines on the base translation sheet. Don't know about whether any changes are required for other languages.

`common/locales/en/groups.json:17:    "tavernTalk": "Tavern Chat"`
`common/locales/en/character.json:2:    "statsAch": "Avatar Stats"` (corresponds the button on the page)
`common/locales/en/generic.json:10:    "titleStats": "Avatar Stats"` (corresponds to the page title)

I'll get right to it.

**Comment by Alys** [comment]
@zesme I don't think "Stats & Achievements" should be renamed, since that subheading is currently the only place that Achievements are mentioned in the menu/heading system. At some point in the future, we'll split stats and achievements into their own pages (there's an issue for that already) and then we'll make the headings consistent with the menu items.

For the non-English languages, please see the _README_FIRST.md file in any of of the directories.

**Comment by ghost** [comment]
@Alys concerning the changes for the non-English languages, FYI I believe Transifex hasn't seen these changes uploaded yet. The last changes date back to around February 15. So currently all non-English language still have translations of the previous versions of the menu names.

@crookedneighbor could you please give me a hint of the current policy of updates being up/down-loaded to/from Transifex?

**Comment by crookedneighbor** [comment]
The policy is that we just need to do it. I'll update it now. 

The real problem is that it is no one person's responsibility, so somethings it slips through the cracks. 

 I have a vision for doing this automatically on a remote server once or twice a day, but it just hasn't happened yet.

**Comment by crookedneighbor** [comment]
@lemoness @veeeeeee Is this something we can prioritize?

**Comment by ltorroba** [comment]
@Alys That makes perfect sense. I'll only alter the `tavernTalk` tag in that case.

@GitHubSphinx @crookedneighbor Couldn't we use Webhooks or something of the like to allow for automatic updating of the base translation document? Seems like [Transifex also implements Webhooks](http://docs.transifex.com/integrations/webhook/) for when a language is fully translated and/or reviewed, so I suppose we could go as far as automatically pulling new translations into the repo. What do you think?

**Comment by ghost** [comment]
I've been looking more in direction of
http://docs.transifex.com/integrations/github/ But it seems there are more
preparatory steps...

**Comment by crookedneighbor** [comment]
My plan was to just implement a cronjob that would pull in the new translations once or twice a day. Seems like it would be the simplest strategy.

**Comment by ghost** [comment]
Sounds great!  Linking https://github.com/HabitRPG/habitrpg/issues/5155 as
I'm afraid I've raised an offtopic discussion in this ticket.

Last note (for what it's worth, as far as I understand the procedure): it
might be great, if TF gets files updated before the English json files go
live, e.g from GH development. Then it doesn't push translations directly
on production, but rather back to the development on GH. So when changes go
live, there's a chance translators will have already translated new
strings. That'll address the issue of changes ruining the look and feel of
fully translated site.

**Comment by khipkin** [comment]
This inconsistency is addressed in #7804.

**Comment by Alys** [comment]
Closed because the Stats & Achievements change is being handled in #7804, as @khipkin says, and the "Tavern Talk" to "Tavern Chat" issue is fixed in https://github.com/HabitRPG/habitrpg/commit/320d8cac5fa47e287d53199684ddfe16ec1f0ea9
