### ISSUE TITLE
Removed from being party leader

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6817]
I am no more the party leader of my group, don't know why.
I use both the web version and the ios app.

Group id: 7c393f74-8457-4644-8c0c-709c87ac4b73
My id: 40e3aa17-5f0f-42a5-82f0-ea42bbca5894

**Comment by Alys** [comment]
Sorry about that! It's a bug that happens when you edit your party (e.g., change the name or description) on the iOS app. It's been fixed but the fix isn't in the app store yet. The next update should prevent this happening.

I've made you leader of your party.
