### ISSUE TITLE
Can't reject quest - left party

### ISSUE THREAD

**Issue by hopealso** [HabitRPG/habitica#6818]
Was invited to a quest in a party. Clicked "Ask later" Decided to leave the party. Now am asked if I want the quest every time I start Habitica. When I click Reject, receive error message that I am not in the party (so I cannot reject the quest.)

Also ever since then I cannot load data through data display tool at oldgods.net.

Running habilitica.com in Chrome on Windows 10. Tried manually removing cookies relating to Habitica in Chrome content settings, and using "Clear Local Storage" here: https://habitica.com/static/clear-browser-data. Both had no effect.

Thanks!

**Comment by Alys** [comment]
We can remove the quest invitation from your account, but we'll need to be able to uniquely identify your account. Can you tell us your User ID from Settings > API?

**Comment by hopealso** [comment]
Sure here it is: 6a7474e1-22fb-4833-8917-2eec310d59ab

Thanks!

**Comment by hopealso** [comment]
FYI my account is now very excitingly entirely broken. Hopefully you're aware and working on a fix!

**Comment by crookedneighbor** [comment]
@hopealso Would you describe for us what you mean by entirely broken? If there's a problem, we definitely want to fix it, but we need to know where to start looking to figure it out.

**Comment by hopealso** [comment]
Well, that's odd. I went to log in again to take a screen shot and it went back to the way it was before. The last I checked I had a strange screen where every drop down was displayed open and my avatar was changed and all my tasks were gone. But now when I log in I just get the invitation to quest again and the error. 

Sorry about that, next time I report a change I'll be more explicit and include a screenshot!

So at this time the state of things is exactly as it was when I first reported the issue.

**Comment by Alys** [comment]
@hopealso Whenever you see anything really odd on the website, or don't see anything you're expecting to see, reloading often helps, and if that fails, logging out can be useful (if you can't get to the login button, you can go to https://habitica.com/static/clear-browser-data and click the button there, which logs you out). 

I've removed the quest invitation from your account. Sorry about not doing it earlier! Your User ID came in while I was asleep. If you provide your User ID with every bug report you make, it can help us fix things more quickly - glance through the Help > Report a Bug instructions each time as a reminder. :)

Everything should be fine now but do please comment here if you still see problems!

**Comment by hopealso** [comment]
OK great thanks it looks good now.
