### ISSUE TITLE
Email, salt, and hashed password are leaked via the API.

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#682]
The API provides access to the user's hashed password, salt, and email address. These seem like questionable things to reveal to an application; some users may not wish to reveal their email address to third party apps, and hashed password+salt lets run off-line password cracking tools.

Steps to reproduce:
- Call the `/api/v1/user` API
- Look at the `{auth}{local}` hash that's returned.

Suggested fix:
- Remove the `{auth}` section entirely from what's returned by the API.
- Move `{auth}{local}{username}` to `{profile}{username}` if it's deemed useful.

**Comment by lefnire** [comment]
removed hashed_password & salt: https://github.com/lefnire/habitrpg/commit/dcb0f7e111c27bb17d086f72f3192462e15f8304 . I'll follow up with the the full suggestion after I've played around a big building the mobile app, see if we need email for anything
