### ISSUE TITLE
Missing images, pixel-art isn't showing, little icons on the tasks are gone

### ISSUE THREAD

**Issue by AABSteen** [HabitRPG/habitica#6820]
_edit by admin:_

**The Habitica website currently has an intermittent problem with some images not appearing. This is only because the browser hasn't yet been able to load all of the images. It does not indicate that any items you have owned have been lost, or that anything else has gone wrong with your account, quest, etc. It's purely a visual glitch.**

**This is happening more often at the moment because we're trialling some additional servers to help with site load, and a temporary side-effect is that images aren't always loading the way that they normally do. That will be sorted out in time.**
### What to do if this happens to you:

**Reloading the site using your browser's refresh or reload button might cause the images to appear immediately, but if not, the images should load themselves correctly fairly soon.**

**You do NOT need to comment here. We know that the problem can happen to any user.**

---

_AABSteen's original post:_

Hey, 
I was already noticing that my habitica was functioning quite slowly and I could hardly type in chats. Now, that is something I also deal with on some other places (example: my hotmail app), so that could be my tablet windows surface thing. I can only have IE on this tablet so that's the browser I'm using. 
Now, since some time, I can only see my own hair and the hair of my party members on my 'task' screen. Also, on the pets page, I can only see the pixel art of the food on the right, but not the pets or the person who takes care of them. 
Also, on my tasks were those icons for the streak, tags, editing and deleting. But now theres only a number showing and a little dot, which I can luckily click to edit the task... 

These together make it quite tiresome to use habitica for me :/

**Comment by glitterninja** [comment]
I came here to report the same thing. Only part of my mount is showing (the back end!) on the task page, and the little icons on the task are missing. I'm using Firefox so I don't know if it's a browser issue or not. Tried clearing cookies and cache but that didn't help.

**Comment by colwem** [comment]
I've had the same issues with typing in chat but it only happens in guilds.  It doesn't happen in my party.  My first guess would be that it has something to do with the fact that there are a lot fewer members in my party than in guilds.  Maybe?  Could it be the \@uname completion script?  When there's too many users it slows down?

**Comment by keysmashes** [comment]
Slow typing in Tavern is a known issue, it is caused by the number of members AFAIR.

**Comment by keysmashes** [comment]
Screenshot of what it was looking like a minute ago:

![image](https://cloud.githubusercontent.com/assets/9433472/13542940/a63f872e-e25e-11e5-85eb-c064b899bbea.png)

It's now fine for me, will update if it breaks again.

**Comment by Alys** [comment]
Slow typing in the chat boxes has been reported at https://github.com/HabitRPG/habitrpg/issues/6462

For the missing images: It's just from the browser not having loaded all the images yet. Reloading might fix it immediately, but if not, the images should load themselves correctly fairly quickly. This is happening more often at the moment because we're trialling some additional servers to help with site load, and a temporary side-effect is that images aren't always loading the way that they normally do. That will be sorted out in time.

**Comment by AABSteen** [comment]
Hey, thanks for the explanation! 
The pixel art pictures are loading somewhat more now, here are two screenshots. 
I understand it won't happen like this again, that it's temporary, this is only so people can see what I meant in one glance :) 

![pets](https://cloud.githubusercontent.com/assets/17648502/13547532/b2945968-e2d7-11e5-94b2-7c5233bb055f.png)
![tasks 2](https://cloud.githubusercontent.com/assets/17648502/13547533/b296cb26-e2d7-11e5-8228-2326a869f58b.png)

**Comment by airanimechiic** [comment]
Thanks!
However, what I'm experiencing is _all_ the dropdown menus stuck open with most images missing. when i refresh I end up getting stuck with this:
![habitrpg](https://cloud.githubusercontent.com/assets/17673802/13547849/56e3a740-e296-11e5-918e-6bd75f7cad69.jpg)
It takes several more refreshes to clear up and sometimes it still doesn't work until I quit Safari. Is this the same issue as everyone else? Is there anything else we can do?

**Comment by Fractionless** [comment]
FYI, this problem also referenced in #6812 Spritesheet not getting resolved. Essentially same issue.

**Comment by colwem** [comment]
@Fractionless what does _resolved_ mean in this context? 

I have this problem too and the cause is clearly a lot of **404 Not Found** errors.  Some of them are the spritesheets but it's certainly not limited to them alone.  I assume the "open menus" is due to js files not being loaded.  I assume server's just having some issues.

**Comment by Fractionless** [comment]
@colwm I think the ticket originator is using "resolved" to mean "fully load."
