### ISSUE TITLE
3 different messed up avatar pics in the past 36 hours

### ISSUE THREAD

**Issue by ArlieS** [HabitRPG/habitica#6829]
I've noticed 3 different messed up avatar pictures in the past 36 hours. Reloading the page (with the browser's reload function) does not help. I'm using the desk top app, in firefox 43.0.4, on ubuntu 12.04

I have not tried the new "clear browser data" button I found when I went to report this bug. 

Here's the latest, and least obviously messed up avatar pic. I didn't take the time to screenshot the others - difference between weekend and workday ;-)

![screenshot from 2016-03-05 09 32 18](https://cloud.githubusercontent.com/assets/4530463/13549173/1604d1bc-e2b5-11e5-96fc-58ed31077c97.png)

**Comment by ArlieS** [comment]
I tried the clear local storage button. It did not result in any obvious change, not even the expected need to relog in to habitica - but when I once again used the browser's reload button, the correct avatar appeared. Looks like the only problem is that the methods which worked for similar problems in the past no longer work, and it's non-obvious to users what will work.

**Comment by colwem** [comment]
This is essentially the same issue as #6820 and #6827.  Spritesheets aren't fully loading.

**Comment by Alys** [comment]
@ArlieS Please see the bold text at the top of https://github.com/HabitRPG/habitrpg/issues/6820 for information about this bug. You can follow that issue for updates (there's a subscribe button on the page if you want emails), so I'm closing this one now.
