### ISSUE TITLE
Random dailies not processed as completed

### ISSUE THREAD

**Issue by HadIKnown** [HabitRPG/habitica#6833]
User ID: 1163b3e7-2e2a-44ac-b367-2678d86ebbf6
Browser: Chrome
OS: Mac OS El Capitan

I finished all my dailies yesterday, but when I went to the app this morning, I noticed that some of my dailies were 1) still greyed out in the "complete" state; and 2) I lost at least one 50+ day streak on a daily that wasn't still greyed out. My cron resets at 8 am every day, and I was definitely done with my dailies by no later than 1 am. I would say I just forgot to check them off, but my least important "right before bed" dailies were the ones that were still checked off, and I wouldn't dare neglect the 50+ day streak. 

I hope this issue can be resolved so that nobody else loses a huge streak... and it'd be lovely if I could get that streak back somehow... :3 

Thank you!

**Comment by Alys** [comment]
@HadIKnown, sorry about this! You were affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313
There's an "Advice" section near the top that will show you how to recover from the unfair damage and how to reset your streaks.
