### ISSUE TITLE
The lines mentioning USD (in connection to subscription, buying gems) have USD translatable

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6838]
Bringing up the question from the [i18n guild](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) and [Trello](https://trello.com/c/SvTsLdRF/12-translations#comment-56dc7ff8c2cac88f8dab2307):

> **_Blablux**_ Hi everyone. While reviewing the french translations in Transifex, I noticed someone recently translated the currency USD as EUR. This seems wrong to me as, to my knowledge, it is used to give the costs of subscriptions. But I'm not convinced that costs are converted to any other currency. Can someone confirm me that USD should still be translated as USD, in order to show the right costs ? Or am I mistaken ?
> ... while these lines are not the most confusing, I believe they can lead to sensitive issues if mistranslated, as a user may end up paying a different amount than the one shown on the Habitica website. In this particular case, I believe some guidance is needed. 

And main points of further discussion:

> **_Oto Ravenstaff**_ Better than mitigation, why not just fix it? Sure we can't omit the acronym for ordering differences, but the string could be changed to use a token. And then use an untranslatable "USD" for it directly
> 
> **_Sphinx**_ I do support the general policy to make the lines flexible to allow translators some language-specific transformation. I see your point about the need to make translations error-proof, but that may result in lines looking badly translated. ... I believe we have reviewers to filter errors like the one in question and I'd leave the current way those lines are made translatable. ... I'll check if I have enough rights to edit instructions then
> 
> **_Mikoto Yato**_ The whole reason why those abbreviations exist is to be understood internationally. Because only the symbols $, ¥ do not cut it. That is why we have $ USD or $AUD - American or Australian dollar. Or ¥ CNY and ¥ JPY, Chinese and Japanese are languages with a different orthography, just like Russian, but you see these abbreviations on international sites as well, because they can be understood this way

Additional reference:
- [USD being google-translated](https://docs.google.com/spreadsheets/d/1ilQVR0nU6-mzVNiXq_0FhrbE22X8ElUYgLmgmVywcMs/edit#gid=0) (it doesn't mean that I believe Google Translate is to any extent a reliable source (you'll see some mistakes). It's just for the purpose of possible future reference - as of scope of languages that would certainly NOT use any translation of "USD")
- The breakdown as of now [on Transifex](https://www.transifex.com/habitrpg/habitrpg/translate/#ach/$/21450377?q=USD) (not very accurate due to the lack of time now, may be double-checked if needed):
  - Most languages have USD as is (not including those with one or two lines): Dutch, English (UK), Hungarian, Indonesian, Lithuanian, Norwegian, Pirate English, Polish, Romanian, Slovenian, Spanish (x2), Tagalog, Vietnamese, 
  - Only a couple of languages utilize the option to translate USD: Hebrew, Russian, Arabic (partial)
  - Inconsistent, but having other equivalents too (including partially translated (even 1 line =)): Chinese (x3), Czech, Danish, Finnish, Greek, Japanese, Latin, Portuguese, Serbian,  
  - **_FIXME**_ Not mentioning dollars being the ones of the US (incl. in some lines): Catalan, Italian
  - **_FIXED on Transifex**_ erroneously converted into local currency (EUR): French, German
- Unfortunately Transifex doesn't allow us to set up warnings for specific terms, they have only general rules for warnings/errors
- It seems I do have enough rights to add instructions to the strings in question on Transifex - something like "Please don't convert the currency, keep the short version of the United States dollar" - according to the final decisions.
### So, the questions:
1. Should translators leave USD (string key: "USD" in particular) as is and not convert it into the local currency (presumably, yes)?
2. Wouldn't it be better to have USD as an untranslatable token to make the 7+1 sensible lines error-proof (presumably, what's best =)?

**Comment by ghost** [comment]
A bit of explanation of my humble opinion on the questions above:
1. I believe all the methods of payment available in the web app will charge $X USD, so it shouldn't be converted e.g. into EUR. Android app charges in the currency of a user's Play Market account - and the mobile app doesn't state the currency. However, I'm not the right person to confirm that.
2. Currency codes (USD, EUR, etc - [some Wikipedia background](https://en.wikipedia.org/wiki/ISO_4217)) are universal and internationally recognized - and thus should be _understood_ all over the world. However it doesn't necessarily mean that all the languages will use the codes universally to denote currency of purchase. E.g. in most countries, you may expect to see the _code_ (USD) almost in any use; while in some countries - only in specialized literature, limited use in banking, etc. - because a particular language may have failed to integrate the code to that extent, that it would look natural in any other uses - and equivalent of the _currency name_ (United States dollar) or an equivalent of an _abbreviation_ (US$, U.S. dollar, American dollar etc.) would be used instead - according to local customs. 
   Let's take a different example from another field for me to show you the way it may look like in some languages. The symbols of the chemical elements are universal and understood all over the world. However, you would expect to read "100 Gold and 50 Silver" rather than "100 Au and 50 Ag" - while the latter option might look quite OK in specialized magazines on Chemistry (or Latin) =) That's why I'm personally slightly against using the untranslatable token for "USD" - but it's only my humble opinion; and once again, I'll be glad to learn other opinions.

**Comment by GitHubSphinx** [comment]
The opening post is edited to include:
4. It seems I do have enough rights to add instructions to the strings in question on Transifex - something like "Please don't convert the currency, keep the short version of the United States Dollar" - according to the final decisions.

**Comment by paglias** [comment]
Regarding question 1: absolutely the price should be left in USD. The site will charge directly USD, mobile apps may charge a converted amount but it'll always be 5 USD in X currency so the only reliable amount is 5 USD

**Comment by ghost** [comment]
@paglias Thank you!

Transifex translation fixed for French and German, instructions added: "Please don't change the currency, keep the abbreviation of the United States dollar" - to the 7 lines in question (the only line with symbol ($) and no code is kickstartName - "Kickstarter Backer - $<%= tier %> Tier", but I believe it's OK).

Question 1 is solved, I believe. Thank you @Blablux!
Question 2 is still open.

**Comment by citrusella** [comment]
I'm not a translator by any means, but I think it might be better to leave it translatable, in case a language might see the use of "USD" as downright unnatural given the context... but then I don't know very much about any of the languages Habitica is currently available in or languages it could potentially be put in...

Maybe an instruction to not change the meaning would be good but still leave it open in case it needs translation in any sort of language?

I don't know. :-/ I felt like saying this, but now that I've written it, I'm not sure it makes sense...

**Comment by ghost** [comment]
It seems like no additional points for making an untranslatable token for currency, so I'm closing the issue leaving the strings mentioning "USD" translatable (as is).
