### ISSUE TITLE
Changing challenge daily doesn't change the notes

### ISSUE THREAD

**Issue by Style13** [HabitRPG/habitica#6840]
I have decided to have a daily that is on _weekly rotation_, so instead of adding tons of dailies, every week I give participants another daily replacing the former one. First week, I created a new weekly with no problems. Second week, I changed first week's daily but the notes didn't change at all. I tried logging on the app and deleting cookies, other browsers etc. 
The edit page shows the new notes but the task page still keeps the old notes. 
I deleted the first week and created another daily for second week. Now all participants reported to have **2 dailies of the same name**, one is with broken challenge link. 

Is this a feature or a bug, I'm not sure. I'm aware challenges are not meant to be on a rotation like this, however, I think challenge creators should be able to change the notes of a task as well, even if people have already accepted them.

API: 9eea0945-8205-40c4-829d-1bf9f3d870a8
[Challenge Link](https://habitica.com/#/options/groups/challenges/6d48ad75-c64c-4217-b1c7-d57be8f06632)

**Comment by crookedneighbor** [comment]
This is in fact a feature. Please read http://habitica.wikia.com/wiki/Challenges#Challenge_Participant.27s_Permissions for more information.

The TL;DNR version is that challenge participants are allowed to change the notes.
