### ISSUE TITLE
Level bonus and Perfect Day achievement descriptions not accurate

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica#6841]
The level bonus description on the Stats & Achievements page says, "Each attribute gets a bonus equal to half of (your Level minus 1)." However, this formula only seems accurate for odd-numbered levels. For example, someone at level 100 gets a level bonus of 50 to each attribute, not 49.5. Would it be more accurate to say something along the lines of "Each attribute gets a bonus equal to half of your level, rounded down to the nearest whole number."

Additionally, the Perfect Day achievement description tells us, "With this achievement you get a +level/2 buff to all attributes for the next day." Again, this doesn't seem accurate, as players with odd-numbered levels get their buffs rounded up to the nearest whole number (e.g., a level 41 player gets a Perfect Day buff of 21). Should we rephrase to something like "With this achievement you get a +level/2 buff (rounded up to the nearest whole number) to all attributes for the next day"?

**Comment by lemoness** [comment]
This isn't currently a need for this, so I'm closing this for now.
