### ISSUE TITLE
Unable to start or abort quest

### ISSUE THREAD

**Issue by Sigmas7** [HabitRPG/habitica#6844]
Recently, there was a member who joined our party that was a much higher level than the rest of the party and they attempted to start a quest that is not supposed to be unlocked until level 40 and none of us are near that level. The member that started the quest left and now we can't do anything with the quest since one person is in the inn. 

Group ID: 05383c72-b5cc-4f17-bf56-ed6720581f54

**Comment by Alys** [comment]
@Sigmas7 I can't see a quest in that party. Did the quest owner remove it? I'm closing this now, but if there's still a problem, please comment here and we'll reopen this and keep helping you.
