### ISSUE TITLE
Completing a daily task is causing the previously completed daily to uncomplete.

### ISSUE THREAD

**Issue by pengguna** [HabitRPG/habitica#6845]
As the title says, upon the ticking off of a daily the previously completed task uncompleted and became available (taking away the gold and experience earned). By changing the most recent daily (excluding the one that refused to be completed) by manually unchecking another grey daily and then ticking it, the target of the uncomplete caused by the troublesome daily would shift.

This behaviour was consistent until the tab was reloaded with Ctrl+Shift+R. 

user-ID: a33c839c-b90e-4304-ab4a-b767b96626e4
using Chrome on Windows.

**Comment by Alys** [comment]
@pengguna  For odd glitches like this, reloading is the best solution. If that didn't help, logging out and logging back in should fix it. It's not from a bug in the code, so there's nothing specific that we can fix; it's just from the browser getting confused and out of sync, and reloading typically fixes that. 

If it occurs again, comment here, but this is typically a very rare problem.
