### ISSUE TITLE
Egg hunt

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#6847]
One of my teammates hosted a quest, Egg Hunt, we completed the quest, it said reward is 10 plain eggs. No one, including me, received any eggs 
This quest doesn't even appear on any of our list as completed quest in our stats
This effected the entire party that played
In Wiki,  quest was dated March 2015
Reward 10 plain eggs 
The quest is no longer available in Quest section
We played this quest in late February,  early March
I can't find any record of it...

**Comment by Alys** [comment]
What's your User ID and party ID? See step 6 of Help > Report a Bug if you're not sure how to find them.

**Comment by JerseyEmerald** [comment]
Group id:   743aac61-a781-41e1-8017-1610873fcfa4

My id.     :    29c5340b-d150-4347-862c-fec571a18b8a

Team name afternoon tea,  we had 7 more players join us since this quest.. 
Thank you for your help!

**Comment by Alys** [comment]
@JerseyEmerald Are you able to give me a list of the players who did take part in this quest? Or the players who joined after the quest ended?

**Comment by JerseyEmerald** [comment]
Yes I have the names of all who participated! 

Lazyez8 (50.0 HP)
Smokeflower (48.0 HP)
Roberto (50.0 HP)
SlayerSSavate (50.0 HP)
dennislala (50.0 HP)
JerseyGirl (50.0 HP)      this is me ☺
corilannam (50.0 HP)
KarlBear (50.0 HP)
Kinsey (50.0 HP)
August Matzko (50.0 HP)
MuzikalNotes (50.0 HP)
Ak14523 (50.0 HP)
  Thank you once again! ☺

**Comment by JerseyEmerald** [comment]
Heres a few more, sorry
The conscientious mage  
Spicklehead 
PhoenixFlorid  
HageshiKami 
andianiherlina  
Akai Akane  
claritastic

**Comment by Alys** [comment]
Sorry about the delay! All of those people should now have the eggs and achievement from the Egg Hunt quest. Reload if you don't see the changes. Post here if there's any still missing!
