### ISSUE TITLE
Look at Tweeria for additional ideas/inspiration?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#685]
Tweeria is an RPG for twitter, basically using your tweets for progress/action in the game, I was thinking that perhaps some ideas/concepts from Tweeria would make sense in HabitRPG 

http://tweeria.com

**Comment by Pandoro** [comment]
Looks very interesting :D 

Especially seeing Guilds there, with leader boards seems to make a lot of sense here as well! If people are motivated to become stronger thus becoming better in the ranking will motivate them to work harder to complete their tasks :)

**Comment by rixx** [comment]
I'm all for a ranking, too. It's motivating for some, and we don't need to make it too prominent so no-one will be discouraged.

**Comment by deilann** [comment]
I'm closing this for now.
