### ISSUE TITLE
Didn't receive party invitation

### ISSUE THREAD

**Issue by Aarca** [HabitRPG/habitica#6852]
I received an invitation to a party by email. Both of the two links included in the email brought me to the Party page. However, there wasn't anything new on the page, just the normal "Start a party with your friends!" button. I've pressed the sync button, exited out of my browser and gotten back on, and checked the app. I don't see any party invitation on the page.
My User ID is bcad0ac6-b0da-43e3-9b00-79603a7e187b
My browser is Chrome and my operating system is Chrome OS.

**Comment by Alys** [comment]
Can you please forward the email to admin@habitica.com? Please include this URL in your email so that we know which issue it refers to:

https://github.com/HabitRPG/habitrpg/issues/6852

**Comment by Alys** [comment]
Thanks! I had a look at the email. I believe what's happened is that the party that the invitation was sent for has been disbanded.

If you know how to contact the person who sent the invitation, give them your User ID and they can use that to invite you to their current party. The User ID is a more reliable way of issuing an invitation.

I'm going to close this now but you are welcome to comment here if you have questions, or if what I've written doesn't seem correct! We'll see your comments and keep helping you.
