### ISSUE TITLE
Unable to Join Challenge - "request entity too large"

### ISSUE THREAD

**Issue by robcthegeek** [HabitRPG/habitica#6855]
Hey,

I was just trying to join the "[Happy List Challenge](https://habitica.com/#/options/groups/challenges/0638a61c-80fd-47c7-892a-cd267971a012)" - but I keep getting the following error come back in the response from the server:

`{"err":"request entity too large"}`

I had a quick look at what was being sent up in the request, and it seems that:
-  The currently-participating `members` array is also sent with the request (actually seems _everything_ about the challenge is sent back).
- The members array is huge - see the attached files.
- Cookies and other request headers look fine - :warning: **_I've removed API Key and Cookies from the samples._**
## Fix

I took the very same cURL request - changed the `members` to be an empty array and re-issued the request. **Tasks were added fine and I am showing as enrolled in the challenge.** :tada: 
## Sample Files

[borked-curl-req.txt](https://github.com/HabitRPG/habitrpg/files/166755/borked-curl-req.txt)
[fixed-curl-req.txt](https://github.com/HabitRPG/habitrpg/files/166756/fixed-curl-req.txt)

**Comment by keysmashes** [comment]
Known: #1471

**Comment by robcthegeek** [comment]
Ah, sorry I didn't find this in my (admittedly quick) search earlier.

Seems #5830 is the root cause of this one - I'll close it!

**Comment by Alys** [comment]
@robcthegeek That is however a very clever workaround! In at least some cases, it would help those players who have enough technical knowledge to do that. I'll edit #1471 to add a pointer to your tip. Thank you!

**Comment by aliceminotto** [comment]
Hi!! would you mind post a mini-guide on how to do that somewhere (here on in the website)? I'm getting the same error over and over again and i think it could be useful!

**Comment by robcthegeek** [comment]
Cooking up a little somethin-somethin that might help...

**Comment by robcthegeek** [comment]
OK guys and girls - I've hacked together something here.

:warning: **I smashed it out pretty quick so please have a look and let me know if you seen any problems!**
- :zap:  Check out the completed form [here](https://jsfiddle.net/robcthegeek/qnc4g5g6/embedded/result/).
- :computer: Check out the code [here](https://jsfiddle.net/robcthegeek/qnc4g5g6/).

Hope this helps! :smile: 

> PS: Sorry for the delay in wrapping this up - got a very busy weekend!

**Comment by Alys** [comment]
@robcthegeek   Excellent work, [Comrade](http://habitica.wikia.com/wiki/Contributor_Titles) ;)

**Comment by robcthegeek** [comment]
Hahaha! :laughing:  Awesome, thanks @Alys! Hope this helps! :smile:

**Comment by robcthegeek** [comment]
@aliceminotto - Let me know if this works for you, if you need any help - do shout! :smile:
