### ISSUE TITLE
Inconsistent html in locale source strings

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6859]
Bringing up the conversation from the [i18n guild](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7):

> **_Blablux**_ [...] The string is in `groups.json` line 103 [on Transifex], and it reads (excerpt): [...]`but are not limited to: <p></p></br><ul style='margin-left: 10px;'><li>swearing`[...]. What's bothering me here is the `<p></p>`. While fundamentaly valid, this html paragraph doesn't seem to be of any purpose. You can get this text in the site by trying to report any user message, and while it adds some space in that message, I'm not sure that it's either intended, neither the way to do it.
> 
> **_Blablux**_ And now that I wrote about it, I'm just seeing the `</br>` tag which, as far as I know, is invalid. It should be either `<br>` or much better `<br />`...

For reference, in the locale file, this goes to line 104 `"abuseFlagModalBody"`.

> **_Sphinx**_ I don't know the reason, but the pages of Habitica will have empty paragraphs from time to time. In this case, my guess would be that this paragraph was introduced by something in the [jade source ](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/members.jade#L103)and was simply transferred to plain html when this part was made translatable. Deleting this empty paragraph doesn't seem to influence the way the modal looks.
> Line break does work, but I agree with you that it may be not the best practice to have it in such a way
> 
> **_Blade**_ Hmm.... that looks really wrong to me. I'll investigate it later today.
> 
> **_Blablux**_ While we're at it, I checked if there was some other parts like this in Transifex. I didn't found any like `<p></p>`, but I noticed that the text in `contentQuest.json` is usually just plain text, but from time to time, it has html formating. Here also, this may be the intended behaviour (though I don't always see why), but there are times where you have some text like `<p>[...]</p><br/><p>[...]</p>`. And while it is valid html, the line break between the two paragraphs seems redundant and not that useful.
> 
> **_Blade**_ In my opinion, all the quest content should be in markdown. Not html. Obviously, that's a change that needs to happen in the source strings.

For example, see `"questMoonstone1Notes"` in `questcontent.json` locale file.
### Long story short:

There are some html inconsistencies in the source strings.  
As far as I understand it, all the html should be written in markdown instead in the source. If that's indeed the case, I may be able to help tracking them and correcting them.  
If the cause of these inconsistencies is deeper than just the source strings, well that's another story. I may still be able to track and report them.

Can someone confirm that all (or part ?) of the source strings should be written in markdown, and not html ?

**Comment by crookedneighbor** [comment]
I _thought_ we were rendering markdown for the quest content, but upon further investigation we are not.

We should leave these as html for now, because markdown rendering will take longer to load. The only thing that should be done is to correct the poorly formatted html.

**Comment by ghost** [comment]
Okay, then I'll try to correct that poorly formated html and submit a pull request.
