### ISSUE TITLE
Unresponsive script in Fiefox

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#686]
Appears every time when I open habitrpg
![2013-03-21_034239](https://f.cloud.github.com/assets/3543515/283648/f8f185b2-91b7-11e2-9dec-73c8d3377359.png)

**Comment by lefnire** [comment]
feedlyhabitrpg? Also, try https://beta.habitrpg.com and see if same issue

**Comment by hjalmberi** [comment]
Didn't delete the first word, just habitrpg now. Beta showed this:
![2013-03-21_035640](https://f.cloud.github.com/assets/3543515/283723/08320888-91ba-11e2-9b5d-6be4d746a42f.png)
Then this 
![2013-03-21_035759](https://f.cloud.github.com/assets/3543515/283727/1a5a83a0-91ba-11e2-8b21-43a02674ee7f.png)
And this (closed it after that)
![2013-03-21_035925](https://f.cloud.github.com/assets/3543515/283731/438cb57c-91ba-11e2-8621-e47140bbb6a3.png)

**Comment by hjalmberi** [comment]
It appears in Safe mode as well, so extensions aren't causing it. Deleting cookies and web-cache also didn't do anything. What else could that be? Too many tasks in to-do?

**Comment by lefnire** [comment]
I'm gonna keep a tab on https://github.com/codeparty/derby/issues/233 and revisit if that's not the issue

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
