### ISSUE TITLE
Missing coins,experience points,mana

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#6863]
I came online at 12:30 am 
I noticed my dailes didn't reset
I verified cron set for 12 am
I went to data display tool
It showed I had 43 undone dailes (they were still gray in  TASK  menu)
I exited out of  DATA display tool
Going back to my task
A msg flashed on my screen
-4000 coins
-1000 experience 
- 2 mana
  It disappeared before I could get a screen shot
  My dailies  were all reset
  I know it's odd, for the past few days, no matter what I was working on in Habitica,  I would get random messages
  -3 gold, or -26 mana,  it's random
  Issues with using my armoire,  where it would take my coins, but I wouldn't get anything
  I was using mobile browser thru Chrome
  My id is29c5340b-d150-4347-862c-fec571a18b8a

**Comment by JerseyEmerald** [comment]
![screenshot_20160311-004612](https://cloud.githubusercontent.com/assets/17463902/13701441/f1aa1322-e755-11e5-8668-5ad7b1a5c59b.png)

**Comment by JerseyEmerald** [comment]
I took a pic through data display tool, I actually have 50 dailes that are undone, after this pic I was going back to my task menu.

**Comment by Alys** [comment]
I'm sorry, we never replied to this! It looks like it was either or both of the bugs mentioned in https://github.com/HabitRPG/habitrpg/issues/6862 (syncing problems or the DST bug). I'm closing this, but let us know if you have problems that can't be explained by either of those!
