### ISSUE TITLE
Suggestion: Sick day

### ISSUE THREAD

**Issue by yacob841** [HabitRPG/habitica#687]
I thought of this because it happened to me recently and that would be I was sick had the flue for two days and was barely able to do anything on my lists.  So the option was to die or to lie and say I did them but I would get exp and coins I didn't earn so this way if you click sick then you dont get harmed for the things  you couldn't do.

**Comment by wc8** [comment]
Current Solution: disable your daily tasks, via Edit > unclick each day of the week.
Other Suggestions for sick day handling here: [Rest in Tavern](https://trello.com/c/A2w2orSc) and [Auto Account Freeze](https://trello.com/c/UqxYFiqG)

**Comment by horusofoz** [comment]
Closing as the wondrous WC8 has provided the planned solution of Rest in Tavern.
