### ISSUE TITLE
Stuck in quest after leaving party, now tasks won't "refresh"

### ISSUE THREAD

**Issue by gfinockio** [HabitRPG/habitica#6880]
Left a party, was not in any quests. Now I'm getting a quest invite every time I visit the Tasks page, and no matter what I click, it reappears the next time I visit the page. Also, none of my "dailies" or "habits" are refreshing.

**Comment by gfinockio** [comment]
User ID c73a82d2-31d3-4cc6-b63a-bf74669bdf9b

**Comment by Alys** [comment]
I've removed the quest invitation. 

Please reload the site. If your tasks are still not behaving or anything else is wrong, log out of Habitica. If you can't get to the logout button, you can use the button at https://habitica.com/static/clear-browser-data - it will log you out. You can log back in as soon as you've logged out. Let us know if it's still not working correctly after that.
