### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by IstraLouise** [HabitRPG/habitica#6881]
I'm getting an application error that tells me to reload the page.  When I do, it comes up again.  If I try to copy the exact message it disappears before I can hit 'copy' though, which is new. usually these things are pretty persistent

**Comment by citrusella** [comment]
For what it's worth (I don't know an answer to "application error" other than "server-side issue"), if you were clicking the bubble to try to copy the message, that tells the site to make the bubble disappear (you can do this with any notification bubble like that to disappear it faster). Most times I've seen someone try to capture the application error, they take a screenshot of it.

**Comment by Alys** [comment]
@IstraLouise We restarted the server several hours ago which has made things better from what we're seeing. Is it better for you now?

@citrusella Thanks, good point!

**Comment by IstraLouise** [comment]
Yes, thanks, Alys!! It is all better now!
