### ISSUE TITLE
Official Habitica Challenges - cannot get rid of tasks

### ISSUE THREAD

**Issue by Otocinclus** [HabitRPG/habitica#6882]
Habitica browser in Chrome:
Wanted to get rid of the "optional" and incomplete tasks from 2 "official" Habitica challenges (Video share challenge, New Years' Resolutions)
Could not delete any of them (which is how it's supposed to work, according to Alys in [this thread ](https://github.com/HabitRPG/habitrpg/pull/6872) ) Even though a few were "optional" (resetting your character, use an orb of rebirth, stuff I don't want to do that is cluttering my ToDos.)
I deleted the tags on my task page, which wasn't the right way to go about it, but now it is impossible to remove the tasks.
What I did:
Edit task tags
Delete Resolutions and Video challenge tags
Saved
Tasks still there but cannot delete (no trashcan icon)
Tag for Video challenge came back ?
Went to challenges page, not listed as participating in either (on my participation list)
Refreshed and tried finding it several times to no avail.
Cannot find the challenges in the Challenges list to rejoin them, so cannot leave the challenges the right way. The Video challenge tag came back but it is not in my participation list so I cannot leave the challenge? I don't want to just click the ToDos and get points for not doing the thing, and there's nothing I can do to remove the Habits.

What do I do? And maybe it shouldn't work this way, especially not for official challenges that are using functionality that doesn't exist or work with the current system (mostly the "optional" items)

I hope this wasn't mentioned elsewhere, I DID check to see if I could find a related Issue. Sorry in advance if this is a duplicate. 

![task list](https://cloud.githubusercontent.com/assets/3780244/13753314/afeeb362-e9cf-11e5-9779-1fd4b1aab6a0.JPG)
![challenges participation](https://cloud.githubusercontent.com/assets/3780244/13753315/afef4de0-e9cf-11e5-9c76-e99f5b979144.JPG)

**Comment by citrusella** [comment]
Have you tried checking one off to induce the red megaphone? Your challenge icon on the tasks isn't highlighted in red, but usually checking off a task will give the server a kick so you have the option to click the megaphone and delete them.

**Comment by Otocinclus** [comment]
Thanks citrusella. I have tried that (checked off a 2 ToDos and a Habit) but it did not activate the broken challenge megaphone.

**Comment by Otocinclus** [comment]
There might be some kind of delay, I restarted my browser (again) and it finally worked, gave me the red megaphone on a Habit and some of the ToDos were just gone. Weird!

**Comment by Alys** [comment]
@Otocinclus Thanks for letting us know it's working for you now! 

If you have a similar problem in future, there's a list of steps on the wiki at http://habitica.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task (Challenges > Deleting a Challenge Task).

**Comment by thebat137** [comment]
Just wanted to mention that I was having this same problem for a few weeks with the "Sticking to your Resolutions" challenge, until today.  I  tried the "checking off a task" trick on several occasions to no avail.  The only thing that I did differently today (AFAIK) is that I deleted the challenge tag first before checking off the task this time.  Is that supposed to be part of the trick?

**Comment by Alys** [comment]
@thebat137 No, I think that was probably just coincidence. The challenge tag isn't connected with the tasks in a way that would help to delete them. Success in deleting them might depend to some extent on how busy the server is at the time, so it can be variable. But thank you for asking!

**Comment by thebat137** [comment]
Huh.  Has anyone had any luck tracking down the source of this bug?  I seem to get hit with it every single time I join a challenge (although this has been the worst so far), and it is kind of frustrating.

**Comment by Alys** [comment]
@thebat137 We know that's it caused by the server timing out before it's able to finish all of the actions required to close a popular challenge that involves a large amount of users' accounts, all needing to be modified. We're modifying the server code to make various actions more efficient, which should help with problems like this.
