### ISSUE TITLE
Not receiving Weekly Progress Update

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6884]
Hi all,

I haven't gotten a Weekly Progress Update in my inbox since January 21st. I was getting them weekly before that. I only noticed today because I needed to reset my longest streak and I use those emails as a reference for it. I checked my settings, and all of the boxes are still checked (except the Unsubscribe one, of course), including the weekly summary. The summary emails aren't in my spam folder, either.

User ID: d1b80ee0-2506-4f2d-b78a-e361d3929972

Thanks!

**Comment by librarianmage** [comment]
I haven't gotten them either since 1/21/16.

**Comment by paglias** [comment]
@gallahergh @MathWhiz sorry about this, unfortunately we were starting to see some performance issues due to the big number of Weekly Recap emails we were sending and we had to stop sending them. We hope to be able to restart them in the near future but I can't give you an exact date.

**Comment by librarianmage** [comment]
@paglias Ok! That makes sense.

**Comment by librarianmage** [comment]
@paglias Should this be closed?

**Comment by ghost** [comment]
@paglias Makes sense to me too. Is that explained anywhere on the website? Could you at least put a temporary note by the "receive weekly updates" checkbox or something like that?

**Comment by paglias** [comment]
@MathWhiz let's keep this open as reference

@gallahergh good point, I don't have the time to do it but we'll be happy to accept a pull request for it if anyone wants to do it
