### ISSUE TITLE
Item store minimization overlaps

### ISSUE THREAD

**Issue by SaraDGore** [HabitRPG/habitica#689]
Similar to the issue with the coins when minimizing the browser. Item store text and icons overlap. I tested in Chrome and Firefox 17.0.1. 

![bug](https://f.cloud.github.com/assets/2285473/286086/61184e70-9233-11e2-8062-4d571d05c3a9.png)

**Comment by lefnire** [comment]
How does it look on https://beta.habitrpg.com? We'll be migrating that over to production soon enough, so as long as it's fixed there we can close this ticket.

**Comment by SaraDGore** [comment]
Yep, it's fixed there.
