### ISSUE TITLE
Member date is wrong

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#6891]
I joined Habitica  on 1/26/2016, my profile member date shows 1/31/2016
 I know,  it's me again ☺
My member ID is   29c5340b-d150-4347-862c-fec571a18b8a
Sorry for being a pain in the button
How I know about the date I joined, I have a few dailies with that date on it and I remember that date as well

**Comment by Alys** [comment]
Confirmed. `auth.timestamps.created` is `2016-01-31T17:04:38.665Z` and yet there's one Daily that was created on 2016-01-26, another on 2016-01-28, and another on 2016-01-30.

```
            "dateCreated": "2016-01-26T21:55:22.887Z"
            "dateCreated": "2016-01-28T05:47:48.116Z"
            "dateCreated": "2016-01-30T14:33:37.203Z"
            "dateCreated": "2016-01-31T00:32:39.067Z"
            "dateCreated": "2016-01-31T02:36:48.434Z"
            and more on 2016-01-31 and after
```

**Comment by JerseyEmerald** [comment]
I know I had more than 1 daily on 26 but that was my first day, I was still learning what every thing was.

**Comment by Alys** [comment]
I've adjusted the date to 2016-01-26T17:04:38.665Z (UTC) although that might be incorrect by one day because of time zones. If the date still looks wrong to you, please tell me what date you see now when you look at your profile.

**Comment by JerseyEmerald** [comment]
It's correct thank you!!
