### ISSUE TITLE
Background Set Purchase

### ISSUE THREAD

**Issue by LostnSound** [HabitRPG/habitica#6895]
I bought a Background set for fifteen gems. The gems are gone but I only have two of the backgrounds from Oct 2015.

My user id is b7d2d06f-bf12-4cb1-9f61-f8f17bd12c89

**Comment by Alys** [comment]
I'm sorry about that! I've given you seven gems to buy the missing background. Please reload if you don't see them straight away.

**Comment by LostnSound** [comment]
thank you so much!
