### ISSUE TITLE
Error loading page

### ISSUE THREAD

**Issue by ChiCheryl** [HabitRPG/habitica#6897]
I get a pink error box, error loading page. Has happened a few times the last couple of days. Using Chrome 49.0.2623.87 m, Windows 10.

Here is console script. Thanks!

RAPID WARNING: Invalid key/value pair (canonicalUrl=https://habitica.com/static/front) Size must be < 8/300 respectively.
https://habitica.com/bower_components/github-buttons/github-btn.html?user=habitrpg&repo=habitrpg&type=watch&count=true Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://habitica.com/api/v2/user/batch-update?_v=287&data=1458133893647 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-9edbdf35.js:33 ObjectresponseError @ app-9edbdf35.js:33
VM48 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'activated' of undefined
    at updateUI (chrome-extension://mcglgmippekbdbmniknikdgkmnnpdnmh/content/data2ui.js:103:13)

**Comment by Alys** [comment]
@ChiCheryl I'm sorry about that! It was an example of this bug: https://github.com/HabitRPG/habitrpg/issues/6700

We restarted the server a few hours ago which should have fixed it for a while at least. Thank you for telling us!
