### ISSUE TITLE
Habit Rouletee

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#69]
_Edit by wc8: Users can vote [here] ((https://trello.com/c/bvKatkjQ) for [Random Good Habit **Death** Challenge](https://trello.com/c/bvKatkjQ)_
Every so often HabitRPG should through a random good habit your way. Read for an hour, 5 pushups, etc. It should have a duration limit and should you meet that limit you win a lot of gold(tbd) and a special item(tbd). Should you fail you loose all your gold and everything else. Wouldn't be rouletee without consequences.

**Comment by FunnySunshine** [comment]
I think it's a good idea, but losing all your gold may be a little too drastic ;)

**Comment by ghost** [comment]
Maybe but in real rouletee you loose it all too

**Comment by FunnySunshine** [comment]
Yeah, I understand the idea. It's just that sometimes, you really don't have time to perform these unplanned tasks and it would be kind of unfair to lose everything because of it.

**Comment by ghost** [comment]
Very true maybe not everything but still something will have to be lost

**Comment by shmumbz** [comment]
I'd be on board for this. Sorta like Halo's Daily and Weekly challenges.

**Comment by mtancoigne** [comment]
Maybe just an XP loss or a certain percentage of gold...

**Comment by mgatten** [comment]
Who goes "all-in" on Roulette?  Better to put up a bounty of your own choosing. You bet an amount that you'll complete a random thing, and then you are assigned a random thing after you've committed your gold. The "lose everything" isn't Roulette - it's Russian Roulette, and Russian Roulette is never a good idea.

**Comment by wc8** [comment]
I can't imagine many users would want to wager away weeks of work for one task, unless they were dying anyway (see #140 -death) and hoping to revive to their last highest score, but there's already potions, re-roll.

**Comment by shmumbz** [comment]
Not completing a random good habit or daily activity shouldn't dock you too much. It should act like a regular daily activity but grant you bonus experience and gold to entice a person to actually do it. Some will be more worthwhile than others, some may be a daily or a weekly habit.

Halo Reach and Halo 4 daily and weekly challenges would be a good model for this.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Is this another variation or an enhancement of #95?

**Comment by ghost** [comment]
69 comes before 95... and this is complete different from 95

**Comment by wc8** [comment]
[Random Good Habit Challenge](https://trello.com/c/bvKatkjQ)

Initial Description:

> Every so often, HabitRPG challenges the user to complete a random good habit (Read for an hour, 5 pushups, etc.). 
> The user has a limited time to complete the challenge. 
> If the challenge is met, a to-be-determined amount of gold is won and a special item. 
> If the user fails the challenge, consequences follow.

I'm thinking an opt-out might be a good idea (especially if the consequences are going to be all-or-nothing). 
So, the confirmation dialog says something like:

> You are challenged to Read 5 pushups for 5 gold coin in the next 5 minutes, on penalty of 5 HP if you fail. Do you accept?

Or:

> You are challenged to Clean the Kitchen for 25 gold coin in the next 5 minutes, on penalty of death. Do you accept?

That way if the challenge is impossible, the user can opt out.

**Comment by ghost** [comment]
The latter is better sounds more like an RPG

**Comment by StanLindsey** [comment]
Rewards and positive thangs are a better motivator than punishments and negative affects. I'd vote no downsides, the point is to introduce new habits/routines to the user.

**Comment by Nelmalih0** [comment]
The way i would do it is, you would randomly get a challenge for the day, and you can choose if you want to do it or not, you don't need to accept it, but if you want to do it, then you do it and check it off, if you just leave it, it goes away without penalty

**Comment by Nelmalih0** [comment]
or maybe a weekly challenge sort of thing, which adds a Daily, Habit, or Todo and you get no penalty for not doing it, and it changes every sunday

**Comment by wc8** [comment]
@Nelmalih0 Absolutely, if the user does not click Yes, it should equal the same as clicking No.
No would be a way of dismissing it, if you realize right away you have to much on your plate and you want to hide the notice.
Also, I like the daily and/or weekly challenge idea. Ideally, users can select which day of the week to have a new challenge appear. For example, some might want them to appear before the weekend, or on Monday morning.

The only way I can think of to address both suggestions and the concern about penalties is either:
- a no penalty setting, if checked, challenges never display a penalty only a potential reward
- or challenge offers a choice of a smaller reward without a penalty or a larger reward with a penalty; 
  - maybe three choices: the third one being an all-or-nothing (although I can't see many users opting for it) for a greater reward.

Personally, if it's just habits, the simple challenge plus a small reward would be plenty for me.
I suppose a greater challenge might be useful for a habit that's been long neglected. I would not have a use for a death challenge.

**Comment by StanLindsey** [comment]
Check out [this trello card](https://trello.com/c/qRmRIYDd) for community wide challenges.

**Comment by ghost** [comment]
Okay this has strayed incredibly far from my original intention so here is
what I think.Yes this should be a opt in kind of thing,yes I think you
should be able ti loose it all,and yes it is harsh and risky but that is
the point. Anything stemming from this original idea please start a new
issue and trello card.

**Comment by wc8** [comment]
Does the current card need any modification to keep in line with your suggestion or is it a good description of it?
Note: I updated the title to: **Random Good Habit Death Challenge**.

I can easily add a separate _Random Good Habit Challenge (not to death)_ card, if others are interested or we find a separate suggestion issue in github.

**Comment by wc8** [comment]
Update: Users wanting random habit challenge without death can follow up [here](https://trello.com/c/EPxvwrrh).

**Comment by ghost** [comment]
@wc8 thanks man
