### ISSUE TITLE
Can't equip or unequip equipment / gear (weapons, armor, etc)

### ISSUE THREAD

**Issue by jimbotherisenclown** [HabitRPG/habitica#6902]
As the title says, I am unable to equip anything. This is a new bug; I've been able to use equipment just fine before. I've tried re-syncing and unchecking 'auto-equip new gear'. I was able to unequip my current set, but when I tried clicking on various pieces of equipment, the page appeared to load for a moment before precisely nothing happened. This has happened in Chrome and Opera.

USERID: 5b35f697-071e-49ae-8661-28e146e62e93

**Comment by Alys** [comment]
Confirmed. Will be happening for everyone, so no one else needs to report this. Thank you @jimbotherisenclown

**Comment by citrusella** [comment]
Should it be reported if this is also happening with unequipping? (I can't equip now, either (I could less than 5 minutes ago), but am unable to unequip as well.) jimbotherisenclown doesn't mention being unable to unequip, which is why I figured I'd ask.

**Comment by Alys** [comment]
No need to report unequipping either.

**Comment by Alys** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/9d50201180e8c2570670916ba60b3b6232c4599b

We'll be re-deploying that inventory sorting feature but we'll adjust it first for performance and bug fixes.
