### ISSUE TITLE
Very bad performance of inventory page.

### ISSUE THREAD

**Issue by swistak** [HabitRPG/habitica#6903]
Very recently I've noticed the performance on inventory page is just horrible.
On my quite fast machine (4 cores 3GHz each) with healthy 8 GB of ram just opening inventory makes CPU spike (100% usage on one core), and tooltips change after few seconds.
Using inventory on Nexus 7 Tablet is now impossible.

Opening inspect tools in Chrome or firebug in Firefox almost kills the browser (I tried to debug equipment issue #6902 ). You can reproduce this quite easilly by trying to use firebug in Firefox on inventory page.

**Comment by swistak** [comment]
I've tried to do some debugging on my own and it seems some code inside app.js (obfuscated by compression unfortunately), is constantly running in very tight loop, taking 100% of CPU time.

Is there any way to get uncopressed assets without running local instance of habitica?

**Comment by Alys** [comment]
It's looking very much like this is related to a recent change which we're reverting, so this isn't worth investigating just yet.

You can see the uncompressed assets in the repository, but I'm not sure there's any way to use them on the site without running up a local install. If you wanted to try installing locally, we'd help you with any problems you ran into.

**Comment by Alys** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/9d50201180e8c2570670916ba60b3b6232c4599b

We'll be re-deploying that inventory sorting feature but we'll adjust it first for performance and bug fixes.
