### ISSUE TITLE
prevent this page from creating additional dialogs bug! game breaker !!!!

### ISSUE THREAD

**Issue by keccy** [HabitRPG/habitica#6909]
hi, before anything, sorry for the misspelling.

my ID is : Emanuel Martins 
Im on a computer with windows 8 , and im assessing the site with google chrome.
when you perform some actions on habitica like :
-deleting or editing a task,
-hatche a pet egg,
-feed a pet 

an box message appers asking if you are sure you realy want to do it. 
this box has an option to “prevent this page from creating additional dialogs” ( witch makes you tink that next time you do the action there will be no box an the action will be done instantly, **its realy missleading**)
but in reality, the next time you try to do one of the actions that create an messae box, you will press the button to give th comand but nothing happens.
I think that when the box message dosnt apper, theres no "okey button" to press an so  the action can not be perfromed

the Clear Browser Data dos not solves the problem 
only Reset Chrome browser settings solved the problem this is a guide in how to do it: 
https://support.google.com/chrome/answer/3296214?hl=en
this may not be easy for some,to do, and its a big bumer becuse you have to insert again all you passwords on any priveusly  password saved site like facebook, gmail, habitica, etc . 
for some of the sites I disnt even remenber the passwords.
ps : realy good game :)

**Comment by librarianmage** [comment]
Unfortunately, it is a feature built in to most browsers, so there is nothing that can be changed.

**Comment by crookedneighbor** [comment]
This has been reported elsewhere. We're working on using custom messages instead of relying on the browser built ins. Should fix the problem.

**Comment by Alys** [comment]
@keccy The easiest way to make the popups come back is to close all browser
windows and reopen them

**Comment by keccy** [comment]
ok, tanks to all for answering my post =)
