### ISSUE TITLE
Subscription was not canceled even though the debit card was closed

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#6910]
Apparently I'm still a subscriber, but it's been several months since I've seen a charge from Habitica on my bank statements. I think what happened is I froze my debit card and got a new one, but for some reason the subscriber status persisted even though there were no successful payments being made. 

I can "Update Card" or "Cancel subscription" but I shouldn't be seeing those buttons if I haven't been paying for a subscription.

Possible "ideal behavior": Payment fails > email user (gentle reminder to update payment info or else the subscription will be automatically canceled at the end of the month) > actual cancellation; must re-subscribe to receive benefits

I'm going to hold off on manually cancelling in case you guys want to poke around first. Let me know if that's not necessary and I can go ahead and cancel. UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68

**Comment by Alys** [comment]
Hi @lynnyliz. Thank you for asking us about this! I'm about to email you at the address stored in your Habitica account, since this is about your finances. Comment here again if you haven't received the email in a day.
