### ISSUE TITLE
Removed from being party leader

### ISSUE THREAD

**Issue by Jordan-Heath** [HabitRPG/habitica#6911]
I'm having the same problem as was listed here #6817 
I assume that this is the appropriate place to post about individual instances like this
Thanks in advance for your help, love the app!

Group ID: bfb30b98-bc0e-4842-b2f8-8b3c9cb5593b
User ID: 7a804ef5-fc51-4aea-bc17-b8fa07e5bde8

**Comment by Alys** [comment]
I've made you leader again. This was caused by a bug in the iOS app which has recently been fixed so it shouldn't happen to you again.
