### ISSUE TITLE
Bug in habitica after login

### ISSUE THREAD

**Issue by goviedo** [HabitRPG/habitica#6913]
I have a constant bug receantly, about 30 minutes early i was just fine.

![error-habitica](https://cloud.githubusercontent.com/assets/5203719/13868716/8278e62c-ecaa-11e5-8d2f-299d6b5da449.jpg)

I post an image with my error and with chrome bug console.

**Comment by Alys** [comment]
I'm sorry about this! We restarted the server and added extra monitoring and we can't see any errors now, so I'm closing this, but tell us if you still have problems.

The main issue for these errors is https://github.com/HabitRPG/habitrpg/issues/6700 and you can check there if you see this in future. We'll put any major updates into that one. There's advice near the top of that issue that might help when these errors happen.
