### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by chococookiiie** [HabitRPG/habitica#6915]
![bildschirmfoto 2016-03-18 um 12 33 53](https://cloud.githubusercontent.com/assets/17926482/13876645/f4ae3552-ed05-11e5-89a3-fbaa2e3a5a31.png)
I tried it on different devices. On chrome and safari. And on my ios apps. I refreshed everything, cleared cache and cookies and everything else. I restarted my computer. Still appearing everytime i refresh the site. Logged in and out. It's so annoying I don't know why this keeps appearing.

What can i do about it?

**Comment by malyix0013** [comment]
Have the same problem.
![habit](https://cloud.githubusercontent.com/assets/17928537/13878987/5add661a-eceb-11e5-971a-1bbadfaa3ba6.PNG)

**Comment by crookedneighbor** [comment]
Thanks for reporting it, we're working on it right now.

**Comment by Alys** [comment]
@cmmata @chococookiiie @malyix0013 We restarted the server and added extra monitoring and we can't see any errors now, so I'm closing this, but tell us if you still have problems.

The main issue for these errors is https://github.com/HabitRPG/habitrpg/issues/6700 and you can comment there if you see this in future. We'll put any major updates into that one. There's advice near the top of that issue that might help when these errors happen.
