### ISSUE TITLE
I can't join to the quest

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6919]
I don't know what happened. Just buttons "begin" and "cancel" vanished, but I'm pending in the quest list. And now I can't join to the quest. (Tried from Chrom, Opera and Android app).
screens
http://imgur.com/rwHYxin
http://imgur.com/BMTP7DC

**Comment by mandyzhou** [comment]
Someone in my party is having a similar issue (via the website). My party's Group ID is 50ac605a-074b-49a2-9d65-232eaba4144b and my party member's User ID is 8c1506b0-1c84-4ecf-8c9d-3b10e14f94da.

My party member who can't join the quest reported that they never got a pop-up asking them to join the quest. They are listed as "Pending" in the quest invitations list.

I've already suggested that they clear their browser data and log out and back in, but this did not help.

**Comment by Alys** [comment]
They could look in the quest box to see if accept/reject buttons are there.
They might need to reload first (the reload might cause the popup to appear
too).

I'll look at their account in a couple of hours when I'm at a computer to
see if anything's wrong.

**Comment by ghost** [comment]
@Alys My user ID: 3b52d0c2-a8f7-4738-9a72-f01325c73dce.  Party ID: b9e989e8-7cf6-4c08-b66a-0a8133c292af

**Comment by Alys** [comment]
@Tabachok @mandyzhou Both should see accept/reject buttons for the quest now (reload to make them appear). Comment here if there's still a problem.
