### ISSUE TITLE
Need Group Quest Reset

### ISSUE THREAD

**Issue by KarlBear** [HabitRPG/habitica#6920]
User ID: 0362b681-28a6-4438-a8ae-326c5c5d557e

Issue posted here as directed by instructions from Wikia.

I am part of a large party called Afternoon Tea, and we are in need of a quest reset. The quest owner is not starting or withdrawing the quest, and with two of our users not having responded to the quest invite, our group has been sitting in limbo for the past 6 days.

We have reached out to the quest owner numerous times without response (though it does appear they are logging in each day). Can we please get this reset?

Please let me know if there is any other information you need.

-KarlBear

**Comment by crookedneighbor** [comment]
@KarlBear Did the quest owner finally get in contact with you?

**Comment by KarlBear** [comment]
Yes, I have closed this issue. Thanks!
