### ISSUE TITLE
Cannot join party member's quest

### ISSUE THREAD

**Issue by Vylierant** [HabitRPG/habitica#6925]
Hi, I am trying to join a quest in my party but I never got the pop up invitation. This has been going for almost 2 days since quest leader has not started the quest yet. I got the email inviting me to the quest but whenever I click the link it just gets me to the party page and nothing happens.

**Comment by Alys** [comment]
Can you please tell us your User ID? See step 6 of [Help > Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) for how to find it on the website or app.

**Comment by Vylierant** [comment]
6788c1ff-bae5-4c79-ae5e-0227f5e3af8a

**Comment by Alys** [comment]
Please reload the website and you should see the invitation appear. Comment again here if you don't.
