### ISSUE TITLE
Issue and Pull Request Templates

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6926]
Recently, Github introduced [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates), which would be a helpful reminder for what needs to be included (User ID, decription of bug, browser being used, what issue the pull request fixes, pictures, etc.). Does anyone think this is a good idea? I would be interested in doing this if it was accepted. @lemoness

**Comment by crookedneighbor** [comment]
Go for it. Just haven't had time to do it myself. We can refine the wording when you have a PR out.

**Comment by librarianmage** [comment]
Ok!
