### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6932]
**Note:** I wasn't sure where this should go, so if I put it in the wrong place, please notify me!

In the most recent iOS update, push notification support for tasks have been added. This would be a great thing to also support in browsers using [Web Notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification), which is supported in [quite a few browsers](http://caniuse.com/#feat=notifications). Any thoughts?

**Comment by keysmashes** [comment]
What kind of thing would a notification be sent for?

**Comment by librarianmage** [comment]
A similar idea to what is on iOS - time based notifications
