### ISSUE TITLE
Facebook account VS email

### ISSUE THREAD

**Issue by Felipe-NS** [HabitRPG/habitica#6939]
Hello, i am a alpha user but the sincronization can't see this

My old id: eee07edc-4acc-46e4-b64a-117b5113c41f
My actual id: e8f552a1-4df3-4c32-8b5a-014ec6fc1581

It has some way to unite them without I miss anything?
the most important for me is the achivement "Original User"

Thanks

**Comment by Alys** [comment]
We can update your e8f552a1-4df3-4c32-8b5a-014ec6fc1581 to give it the same starting date and "Original User" achievement as your eee07edc-4acc-46e4-b64a-117b5113c41f account. Is there anything else you want to keep from your old account?

**Comment by Felipe-NS** [comment]
No, that's enough
Thank You!

**Comment by Alys** [comment]
@Felipe-NS I've transferred your original starting date (2013-02-28 15:43 UTC) and the Original User achievement. I also transferred four gems that you had in the old account. I checked the old accounts other achievements and there's no others that you don't already have.

Could you please check that your new account is the way you want it to be?

Once it is, you can delete your old account if you want to by logging in and going to [Settings > Site](https://habitica.com/#/options/settings/settings) - there's a red delete button near the bottom right.

**Comment by Felipe-NS** [comment]
It's everything ok
Thanks
