### ISSUE TITLE
Save Avatar as Image

### ISSUE THREAD

**Issue by driftlessdev** [HabitRPG/habitica#694]
I wanted to use my avatar as my Twitter photo, but can't find a good way to get it. I see the avatar image is constructed by CSS backgrounds. I can get an image of it through a screenshot, but I'd love if there was a standard way I could download it as a PNG.

**Comment by wc8** [comment]
I added your suggestion to Trello. You can vote for it here: [Save/Share Character](https://trello.com/c/P0RndCsd).
