### ISSUE TITLE
Android app - reoccurring connectin error

### ISSUE THREAD

**Issue by artemisclyde** [HabitRPG/habitica#6942]
![share_temp](https://cloud.githubusercontent.com/assets/16636453/13946215/9097da94-f013-11e5-8f99-6c4514552646.jpg)

This error kept coming for the past week despite uninstalling and installing habitica. I also read one comment in the google playstore describing the same problem.
For me it's resolved for now, I uninstalled habitica, restarted my phone and installed it again. Still an error grinding my gears.

**Comment by Alys** [comment]
Thanks for letting us know! I'm sorry it lasted that long for you! I believe usually clearing the app's data fixes it, but it sounds like it was much more frustrating for you. :(

If you have any other errors, you can report them through About > Report a Bug on the app, or by email to mobile@habitica.com, or in the Android repository at https://github.com/HabitRPG/habitrpg-android/issues (there's a summary of those methods at Help > Report a Bug from the Habitica website).
