### ISSUE TITLE
Spell / Skill misspelled

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6947]
General Info
- UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee
- Browser: N/A
- OS: N/A
### Description

In habitrpg/common/script/content/spells.js, the spell name for the Healer's blessing is `heallall`. Should it be `healall`?

**Comment by crookedneighbor** [comment]
Meant to comment on this. It is misspelled, but we can't change it because it would be backwards incompatible.

**Comment by librarianmage** [comment]
That makes more than enough sense! Thanks.
