### ISSUE TITLE
Consistent up voting for services utilizing API?

### ISSUE THREAD

**Issue by ruddfawcett** [HabitRPG/habitica#695]
Would it be possible to add an optional parameter say `"consistent"` that would be `true` and would allow a service to consistently upvote a habit?  For a service, say they give you one upvote on a task every x times, if you do something with the services, you'll get "x" votes.  However, you really be getting 10 xp, then 9 xp, then 6 xp until you get to like .1 xp each vote (note these numbers are not accurate).  That would be really helpful.  Thanks!

**Comment by switz** [comment]
I'd be ok implementing this, but what do people think? Do we need this?

**Comment by ryjm** [comment]
I would use this - it would give a really nice Eve Online-esque "skill training" feel. You could have some habits (your "skills") that you can clock in on which continuously give you experience as long as you are clocked in. It would also fit in really nicely with the clocking mechanism in org-mode without having to make a timed api call.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
