### ISSUE TITLE
Social section (bottom of page) doesn't work

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6951]
General Info
- UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee
- Browser: Chrome
- OS: ChromeOS
### Description

In the footer of most pages, the "Social" section is blank.

![screenshot 2016-03-23 at 2 35 34 pm](https://cloud.githubusercontent.com/assets/12386291/13998817/34b3ed54-f107-11e5-96e4-829f14e0868a.png)

The code of the footer section is:

```
<div class="col-sm-3">
   <h4>Social</h4>
   <div addthis:url="https://habitica.com" addthis:title="Habitica - Gamify Your Life" ng-init="loadWidgets()" class="addthis_toolbox addthis_default_style">
      <table>
         <tr>
            <td>
               <div data-href="https://habitica.com/static/front" data-layout="button" data-action="like" data-share="true" data-show-faces="true" class="fb-like"></div>
            </td>
         </tr>
         <tr>
            <td><a href="https://twitter.com/intent/tweet?text=Improve+yourself+in+the+land+of+Habitica!&amp;via=habitica&amp;url=https://habitica.com/&amp;count=none" class="twitter-share-button">Tweet</a></td>
         </tr>
         <tr>
            <td><a data-href="https://habitica.com/static/front" data-notes="none" class="tumblr-share-button"></a></td>
         </tr>
         <tr>
            <td><a g:plusone:size="medium" class="addthis_button_google_plusone"></a></td>
         </tr>
         <tr>
            <td><iframe src="/bower_components/github-buttons/github-btn.html?user=habitrpg&amp;repo=habitrpg&amp;type=watch&amp;count=true" allowtransparency="true" frameborder="0" scrolling="0" width="85px" height="20px"></iframe></td>
         </tr>
      </table>
   </div>
</div>
```

**Comment by librarianmage** [comment]
As an aside, in `/website/views/shared/tasks/footer.jade`, there is:

```
audio#sound(autoplay)
   source#oggSource(type="audio/ogg")
   source#mp3Source(type="audio/mp3")
```

which doesn't do anything.

**Comment by crookedneighbor** [comment]
I beg to differ about the audio element:

https://github.com/HabitRPG/habitrpg/blob/e59f614568b61cd2de39f7cb5690b137abeab041/website/public/js/controllers/rootCtrl.js#L83-L90

**Comment by librarianmage** [comment]
Ohhhh! That makes more sense.

**Comment by crookedneighbor** [comment]
Loading for me on a Mac:

![screen shot 2016-03-23 at 5 43 09 pm](https://cloud.githubusercontent.com/assets/2916945/14003167/bf2fcd38-f11e-11e5-8ea6-340fe0dac922.png)

Might be a plugin you have installed or something specific to a chrome book. There are no javascript console errors?

**Comment by librarianmage** [comment]
I didn't see any...

**Comment by Alys** [comment]
The Social column is empty for me until I disable extensions, then if I reload the site, it shows the same ones from the screenshot above, and also Google Plus. I didn't bother trying to work out which extensions caused it, since there's likely a wide variety out there.

This isn't a Habitica bug, but I'm wondering if it's worth adding some text link(s) to the Social column so that there's something there for those who do have all the buttons blocked. @lemoness ?

**Comment by librarianmage** [comment]
Maybe its an adblocker

**Comment by crookedneighbor** [comment]
I don't think it's worth it to do anything. It's not an essential part of the site and it's specific to the extension settings (likely adblockers) that particular users have enabled. Someone re-open the issue if you feel strongly about it.
