### ISSUE TITLE
Press Kit doesn't show changes

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6952]
General Info
- UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee
- Browser: Chrome
- OS: ChromeOS
### Description

https://habitica.com/static/press-kit (which was changed in #6846) hasn't updated to reflect the changes. Were these not integrated yet?

**Comment by crookedneighbor** [comment]
It just hasn't been deployed yet.

**Comment by librarianmage** [comment]
Oops
