### ISSUE TITLE
Static Pages still reflect Bootstrap theme

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#6953]
General Info
- UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee
- Browser: Chrome
- OS: ChromeOS
### Description

The static pages (other than the front page) show the dark Boostrap theme. See https://habitica.com/static/press-kit for reference.

**Comment by crookedneighbor** [comment]
Can you point me to the PR or commit where this was supposed to be changed? Not sure that this is actually a problem.

**Comment by crookedneighbor** [comment]
Going to close this, because I don't recall anything where we were moving away from the dark bootstrap theme for the other static pages, but feel free to re-open if you know something I don't. (quite likely)
