### ISSUE TITLE
List Featured Third Party Apps

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#6954]
@Alys had the idea to highlight some of our favorite third-party apps:

"On the page where we list the UUID and token, we could have featured third-party apps: Beeminder, the Chrome chat extension, DDT, [and] link off to the wiki for others."

**Comment by librarianmage** [comment]
I'll be happy to do this!

**Comment by librarianmage** [comment]
How do I add translatable strings?

**Comment by librarianmage** [comment]
Do I need to add the key (to the string I am using) to every locale?

**Comment by librarianmage** [comment]
Never mind, on http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths#Adding_Translatable_Strings it just says to add them to the `en` locale.
