### ISSUE TITLE
API URL changed?

### ISSUE THREAD

**Issue by jasoncyu** [HabitRPG/habitica#696]
When I do this but with my data

```
curl -X POST --compressed -H "Content-Type:application/json" \
-H 'x-api-user: {user id}' \
-H 'x-api-key: {api token}' \
-d '{"text":"from the api!","type":"todo"}' \
https://habitrpg.com/api/v1/user/task
```

I get the following

```
  Moved Temporarily. Redirecting to /500.html%
```

Something change? This used to work for me.

**Comment by switz** [comment]
Hmm, working for me. You probably hit the request when the server was restarting. Unfortunately, there isn't much we can do about this. But, if you re-run the request in about 5-10 seconds, you should be a-ok. Please reopen this thread if the issue persists.
