### ISSUE TITLE
Clicking 'show stat allocation' button rapidly will desync text and collapse state

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#6961]
General Info
- UUID: n/a
- Browser: Chrome 49
- OS: Ubuntu 14.04.3
### Description

The Bootstrap collapse will not toggle when partway through its animation. The button to show/hide it, however, changes its text on every click – if you double-click the show/hide button, you end up with this:

![image](https://cloud.githubusercontent.com/assets/9433472/14056708/85ac5764-f2e7-11e5-90a1-f75cf7bd0fc6.png)

The collapse fires several [events](https://getbootstrap.com/javascript/#collapse-events), which would presumably help to fix this.
#### Console Errors

n/a

**Comment by Alys** [comment]
Confirmed. Thanks for the details and the link!

**Comment by Hus274** [comment]
I don't see the show stat allocation button on the stat page currently.

**Comment by crookedneighbor** [comment]
It's in the level up modal.

**Comment by Hus274** [comment]
Got it, thanks!

**Comment by Hus274** [comment]
Changing this dialog from a collapsible element to one that uses ng-show takes care of this issue. The only change in functionality from the user perspective (outside of fixing the bug) is it no longer has a slow open effect where the table slides down to be displayed. Now it just appears. Does this work?

Example:
Old Collapse Style - http://i.imgur.com/iKqar66.gif
New ng-show style - http://i.stack.imgur.com/z94GJ.gif

**Comment by SabreCat** [comment]
Client issue. Pending for frontend redesign.

**Comment by librarianmage** [comment]
Stat allocation isn't displayed like this anymore; should this Issue be closed?

**Comment by SabreCat** [comment]
Yup, good call. There are still sync errors associated with rapid clicking of attribute assignment, but the specific visual issue here is no longer present.
