### ISSUE TITLE
Unreliable sound when clicking Armoire

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#6963]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 45.0.1
- OS: Windows 7 Service Pack 1 (via Bootcamp on 2011 Macbook Pro, if that's relevant)
### Description

Sound (in LuneFox's theme at least) does not play reliably when clicking Armoire or Health Potion when it used to do so. Not sure if this is a bug or some sort of intended change (I'm leaning toward unintended because the sound is unreliable), so thought I'd report it to be sure if it was unintended that you guys caught wind of it. (There's also no sound when casting spells, but I don't cast spells enough to remember if that's normal.)

If I had to give a percentage to how much the sound is playing, I'd have to say it's generally not playing a sound (maybe 90-95% of the clicks?) but occasionally is doing so. I only tested the health potion once and got no sound for that. I don't generally buy health potions.
#### Console Errors

No JS errors to speak of.

**Comment by crookedneighbor** [comment]
The sound now only plays when you have sufficient funds to purchase a reward/potion/armoire item. Are you experiencing something different?

**Comment by crookedneighbor** [comment]
Let me clarify, this is a recent change to make it so the sound only plays when you have sufficient funds (IE, the purchase was successful)

**Comment by citrusella** [comment]
I've been noticing this when I just (actually) get something from the Armoire. It's rare that I accidentally click when I don't have the funds to use it, and I can't consciously remember that occurring. It's certainly not the only time the sound's not playing.

So I believe it is different, because the sound is unreliable when I am indeed receiving the reward in question. (Though for what it's worth, when I tested the health potion I had full health, so the reward was useless... but I did have enough money to buy that, too.)

**Comment by Alys** [comment]
From several tests, if I have anything up to 199 gold, it does not play a sound; if I have 200 or more it does. I.e., it does not play a sound when I have enough gold to use the Armoire but after I've used it, I do not have enough gold to use it again.

The same does not occur for other rewards.

I'm guessing that this is related to the recent change that prevents the sound playing when you don't have enough gold to buy a reward, and that perhaps for the Armoire, the code that plays the sound occurs after the code that subtracts the gold. I have not confirmed this by actually looking at the code though. ;)

I'm advertising this in the Aspiring Coders guild.

**Comment by crookedneighbor** [comment]
Probably a bug I missed when reviewing the sound change.

**Comment by citrusella** [comment]
Huh... that would explain why the time I know I definitely heard the sound was when I cheated my gold up to 300 to test it for this report. :sweat_smile: Would also explain why I usually don't hear it, because I'm one of those people who uses the armoire pretty much as soon as I have the funds. XD

**Comment by Redmega** [comment]
Looking at this now, unless someones worked on it already?

**Comment by Redmega** [comment]
I've confirmed the behavior to be what @Alys said:

> the code that plays the sound occurs after the code that subtracts the gold.

But it's not just occuring on the armoire. It happened for a few other items as well. Haven't tested everything but it seems to be all of them.

EDIT: Seems to be all reward-purchase sounds, and seems to be on all themes as well. Looking for the file I need to modify now.

**Comment by Redmega** [comment]
This one was a quick fix. @crookedneighbor You just had two lines flipped ;)
