### ISSUE TITLE
Make links to wikia translatable

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6966]
Raised by @Demoinho on Transifex regarding the string `spellsText`

> "You can now unlock class-specific spells. You'll see your first at level 11. Your mana replenishes 10 points per day, plus 1 point per completed"
> 
> Can this string be changed to have the complete sentence? In some languages, you won't say it like "completed task" but like "task completed".

The thing is https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js#L85 like a few other occurrences use the following pattern:
`<Beginning of the sentence> <link to wiki> <ending if any>`
which makes such lines sometimes tricky to translate.
##### Notes
- Some links and references to previous discussions on having links to wikia translatable can be found in https://github.com/HabitRPG/habitrpg/issues/5202 - as well as the practices of making lines with links translatable
- Having all the links to wikia translatable is good for consistency reasons
- As of now translatable links have instructions on Transifex: "String can link a translated article on a particular language wiki (e.g. on FR.habitica.wikia.com for French) but please first double-check that the wiki exists in your language and the linked page (a) exists (b) has enough info (c) looks nice"
- There's an ongoing discussion in the Wizards of the Wiki about the best possible way to notify a user seeing a translated wiki page that they could also check the original English page
- This ticket is about lines having links to wikia, and _not_ about other split up strings or strings with other links
- Currently I'm not able to work on this myself, unfortunately, so anyone can feel free to take it
##### Suggestions
- Identify the lines in question
- Change strings in json files to include the links in html
- Change the way the strings are used to enable html (and reflect the changes in the strings)
- Make sure no visual changes are introduced

[priority - minor] [entry level coding] [translations]

**Comment by Alys** [comment]
Agreed and labelled. Thanks @GitHubSphinx !

**Comment by crookedneighbor** [comment]
:+1:

**Comment by librarianmage** [comment]
I can try this!

**Comment by Redmega** [comment]
@MathWhiz Any progress?

**Comment by librarianmage** [comment]
@Redmega Not yet (on vacation). I will, however, look into it ASAP.

**Comment by librarianmage** [comment]
@GitHubSphinx is it okay that this would likely end up with different keys?

**Comment by ghost** [comment]
@MathWhiz 
When you keep the key and update the string in a json file, Transifex allows translators to browse the history of the string with this key. If you invent a new key, Transifex won't suggest anything for the string, and translators will have to compose the translation from the scratch.

So I would choose to keep the keys when possible. 

E.g. [the string with the spellsText key](https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/npc.json#L44):
`"spellsText": "You can now unlock class-specific spells. You'll see your first at level 11. Your mana replenishes 10 points per day, plus 1 point per completed ",`

[implemented with](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js#L85)
`content: window.env.t('spellsText') + " <a target='_blank' href='http://habitica.wikia.com/wiki/Todos'>" + window.env.t('toDo') + "</a>."`

would turn into
`"spellsText": "You can now unlock class-specific spells. You'll see your first at level 11. Your mana replenishes 10 points per day, plus 1 point per completed <a target='_blank' href='http://habitica.wikia.com/wiki/Todos'>To-Do</a>",`

and
`content: !window.env.t('spellsText')`
(TBH I'm not sure where the `!` should go)

@crookedneighbor could you please correct me if I'm wrong about the approach or the exclamation mark...

**Comment by librarianmage** [comment]
Okay! But if that happens and the site gets updated before all of the
translations are finished, wouldn't that break stuff?

**Comment by ghost** [comment]
@MathWhiz, oh, please excuse me for not mentioning it! When you update strings in en locale and the files are uploaded to Transifex, Transifex will:
- store the old translation in the history
- make the updated strings "untranslated" for all the localization languages

So the old translations won't be used and the users of localized UI will have this text in English until translators don't do their job: revisit the strings and update the translations - checking what has changed in the English strings and altering the translation from the history accordingly.

**Comment by MathWhiz** [comment]
Yeah, but if I implement the above example, wouldn't that mean it would
show the translated version of `You can now unlock class-specific spells.
You'll see your first at level 11. Your mana replenishes 10 points per day,
plus 1 point per completed ` to non-English users until the string is
updated?

**Comment by librarianmage** [comment]
### Files and Lines (for reference)
- [x] [habitrpg/website/public/js/services/guideServices.js](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js)
  - [x] [L85](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js#L85)
  - [x] [L89](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/services/guideServices.js#L89)
- [x] [habitrpg/website/views/options/social/challenge-box.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenge-box.jade)
  - [x] [L6](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenge-box.jade#L6)
- [x] [habitrpg/website/views/static/plans.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/plans.jade)
  - [x] [L18](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/plans.jade#L18)
  - [x] [L20](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/plans.jade#L20)
  - [x] [L26](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/plans.jade#L26)
- [x] [habitrpg/website/views/options/social/tavern.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade)
  - [x] [L42](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade#L42)
  - [x] [L45](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade#L45)
  - [x] [L48](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade#L48)
  - [x] [L60](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade#L60)
  - [x] [L74](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade#L74)
  - [x] [L77](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/tavern.jade#L77)
- [x] [habitrpg/website/views/shared/footer.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/footer.jade)
  - [x] [L30](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/footer.jade#L30)
  - [x] [L53](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/footer.jade#L53)
  - [x] [L55](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/footer.jade#L53)
- [x] [habitrpg/website/views/options/inventory/pets.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/inventory/pets.jade)
  - [x] [L54](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/inventory/pets.jade#L54)
- [x] [habitrpg/website/views/shared/header/menu.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/menu.jade)
  - [x] [L69](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/menu.jade#L69)
  - [x] [L170](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/menu.jade#L170)
- [x] [habitrpg/website/views/shared/modals/achievements.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/achievements.jade)
  - [x] [L116](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/achievements.jade#L116)
- [x] [habitrpg/website/views/options/social/challenges.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenges.jade)
  - [x] [L152](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenges.jade#L152)
- [x] [habitrpg/website/views/shared/profiles/achievements.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/achievements.jade)
  - [x] [L32](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/achievements.jade#L32)
- [x] [habitrpg/website/views/static/community-guidelines.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/community-guidelines.jade)
  - [x] [L339](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/community-guidelines.jade#L339)

If anyone is able to double check some of these to confirm them, that would be great!

**Comment by librarianmage** [comment]
@GitHubSphinx @crookedneighbor When the translatable string is being used in different places (without the Wikia link), I have created a new string called "`[original name here]`Link". Is that okay?

**Comment by librarianmage** [comment]
@GitHubSphinx @crookedneighbor @Alys In /website/views/options/social/tavern.jade, `env.t(FAQ)` links to http://habitica.wikia.com/wiki/FAQ, and everywhere else it links to https://habitica.com/static/faq/. Would it be possible if I just change the link in the tavern to /static/faq/? Then it would just be one change.

**Comment by ghost** [comment]
@MathWhiz nice catch!

@lemoness could you please consider the inconsistency noticed by @MathWhiz - the list of resources in the Tavern still has link to the FAQ on the Wiki, not to the static FAQ.

For reference:
- from #6466 - _update help menu and FAQ to jump to Wikia_

> **Alys** It's deliberate that the wiki's FAQ is no longer linked to because it is very overwhelming for new users - the staff have done user testing that shows that.
> 
> **Alys** It adds "or on the wiki FAQ" to the text below, on both the website FAQ and the iOS FAQ (and changes the "Last updated" date at the top of the FAQ):
- from #5773 - _New FAQ (web)_

> **lemoness** Right now, the FAQ link leads to the wiki, which is confusing and overwhelming to new users.

**Comment by librarianmage** [comment]
@GitHubSphinx @lemoness Some other challenging sections:

#### [habitrpg/website/views/options/social/challenge-box.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenge-box.jade#L6)

``` jade
a.pull-right(target='_blank', href='http://habitica.wikia.com/wiki/Challenges')
  small=env.t('moreInfo')
```

#### [habitrpg/website/views/options/social/challenges.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/challenges.jade#L152)

``` jade
a.hint.vertical-20(target='_blank', href='http://habitica.wikia.com/wiki/Tags',
  popover=env.t('challengeTagPop'), popover-trigger='mouseenter', popover-placement='right')
    =env.t('moreInfo')
```

Both of these use 'moreInfo', but in different ways, and with different links.

---

#### [habitrpg/website/views/options/inventory/pets.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/inventory/pets.jade#L54)

``` jade
a(target='_blank', href='http://habitica.wikia.com/wiki/Contributing_to_Habitica')
  button(ng-if='!user.items.pets["Dragon-Hydra"]', class="pet-button pet-not-owned", popover-trigger='mouseenter', popover-placement='right', popover=env.t('rarePetPop1'), popover-title=env.t('rarePetPop2'))
    .PixelPaw-Gold
```

How should I change this?

---

#### [habitrpg/website/views/shared/profiles/achievements.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/achievements.jade#L32)

``` jade
+aLink('http://habitica.wikia.com/wiki/Contributing_to_Habitica', env.t('readMore'))
```

`aLink` (found in [habitrpg/website/views/shared/profiles/achievements.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/mixins.jade)

``` jade
mixin aLink(url, label)
  if mobile
    a(href="", ng-click="externalLink('#{url}')")= label
  else
    a(href='#{url}', target='_blank')= label
```

This is the only time that `aLink` is used

**Comment by librarianmage** [comment]
@GitHubSphinx What do you think I should do to resolve these problems?

**Comment by ghost** [comment]
@MathWhiz I'm sorry but I can't help you with these strings, as even cases simpler than these has always turned into trial-and-error search for me here (I haven't had any chance to develop my programming skills since the times of Delphi 5 and MS VS 6 :smile:). I believe you may leave it as is for now for you or someone to revisit it later. You may also mention these lines in the comment to your PR.

**Comment by librarianmage** [comment]
@GitHubSphinx Oh, I will mention those on my PR! Thanks!

**Comment by lemoness** [comment]
The link in the Resources list should indeed link to the static FAQ, not
the wiki!

**Comment by librarianmage** [comment]
@Lemoness Thanks!
