### ISSUE TITLE
Name and Level box hiding my avatar

### ISSUE THREAD

**Issue by Laflamme** [HabitRPG/habitica#697]
It think this needs a little tweaking ;)

![Sans titre](https://f.cloud.github.com/assets/3687644/288984/c17c1976-928e-11e2-8b54-29db9b046ae2.png)

Also, I have the same problem with the names of my party members.

**Comment by ghost** [comment]
Same here.

Thanks,

Michael Garcia, a.k.a. The Crazy GM http://www.TheCrazyGM.com

**Comment by wildcate** [comment]
Same in my husband's account. He'd prefer having the info as mouseover, btw (similar to how it's done for the party members) than obscuring his avatar...

**Comment by lefnire** [comment]
tagging @zakkain - sounds like most people preferring mouseover on main avatar

**Comment by caycefischer** [comment]
Hmm, I liked someone's idea of bringing the user menu into the avatar. That two-line wrapping is a real problem across the board though, party members too.

Will remove the Level from the top to get more room as a hotfix

**Comment by caycefischer** [comment]
BOOM: https://github.com/lefnire/habitrpg/pull/726

That should help right away, I'll think on a permanent solution.

**Comment by caycefischer** [comment]
(note, I know I haven't removed the actual overlay to only show it on hover—I'll do that maybe tonight, I want to re-jigger a few things) 

@lefnire can you deploy the hotfix?

**Comment by rixx** [comment]
Huh? What did I miss; why'd you reopen this issue? It looks fixed for me.

**Comment by caycefischer** [comment]
O_o I'm not sure. Could have been a mis-click

**Comment by ghost** [comment]
```
                            Hi,


                                Michael has posted a new update message to "Medical Bills - Mental Hospital "
                                See below or visit this page:Take me to this page >>










                            New Update from Michael...


                                10% in one day. not bad, not bad at all.
                                Continue Reading >>
                                You are receiving this email from Michael Garcia, a registered GoFundMe user.

                                Stop emails from this person.




                            What is GoFundMe?


                                GoFundMe is a personal fundraising website that has helped thousands of people raise millions of dollars for the things that matter to them most.






                                Sent from GoFundMe's Headquarters in California

                                PO BOX 711798 San Diego, CA 92171
                                Don't want emails from GoFundMe?

                                We're sorry. You can unsubscribe here.
```
