### ISSUE TITLE
Problem reseting account

### ISSUE THREAD

**Issue by rightless** [HabitRPG/habitica#6973]
General Info
- UUID: b2b55607-9ed0-4195-b26e-9fbd1d00b760
- Browser: Opera
- OS: Windows 7
### Description

Good morning,
I reseted my account yesterday and my attributes continue the same, and i would like them to reset. Also i have a message that keeps showing from a previous invite to a quest that no longer is active.
#### Console Errors

Sorry if it didn't help, but i think it is it:

VM48 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'hiding' of undefined
    at Object.adblock_begin.handleHiding (chrome-extension://aobdicepooefnbaeokijohmhjlleamfj/adblock_start_chrome.js:104:13)
    at chrome-extension://aobdicepooefnbaeokijohmhjlleamfj/adblock_start_common.js:200:12handler @ VM48 extensions::uncaught_exception_handler:8
browser.js:42 Opera has modified script or content on staticxx.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). 
See browser.js for details
browser.js:42 Opera has modified script or content on www.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details

https://habitica.com/api/v2/groups/a1348415-dd08-4daa-bb80-866f9d935dd5/questReject Failed to load resource: the server responded with a status of 400 (Bad Request)

https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=18693311.1447612663&jid=1036674994&_v=j41&z=1415509829 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=18693311.1447612663&jid=1870031650&_v=j41&z=1674142468 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by Alys** [comment]
I've deleted the quest invitation and attribute points. Please reload if you don't see the change immediately.

**Comment by rightless** [comment]
Thanks, everything is fine now... and omg, you guys are fast as hell, i saw it like in Jim Carey's Bruce Almighty when he is tipping? hahahaha
Thanks again.
