### ISSUE TITLE
Editing a challenge-based tag does not change the tag

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#6974]
General Info
- UUID: 30983c37-52c3-415d-977c-38af6c7db91c
- Browser: Firefox 45
- OS: Windows 10
### Description

I created a challenge for my party and created a tag for it. After saving, I realized that I had used this same tag on a previous challenge, so I edited the challenge to modify the tag. After saving the update, the tag name remained the original tag name and stayed the original after subsequent attempts to edit it. Only by using the Swagger API was I able to modify the tag successfully.
#### Console Errors

No errors were reported.

**Comment by Alys** [comment]
I'm not sure if it's desirable for a challenge owner to edit a challenge's tag after the challenge has been created.

It might be the API that is buggy for allowing the tag to be edited.

Once a player has joined a challenge, the tag is under the control of the player. While still being in the challenge, a participant can edit or delete the tag, or use it for other tasks. Challenge tags are basically a method for the participants to filter the challenge tasks for their own task management purposes. If a participant modified the tag to suit themself (e.g., to highlight a challenge they really cared about), they'd be inconvenienced if the tag was later changed by the challenge owner.

There's one case where you especially want a participant to have control over the tag: A player might join two challenges created by different owners that happened to have very similar tags. The player would want to modify one or both tags to distinguish the challenges. I think allowing that is more important than allowing a challenge owner to change their mind about the tag (a minor edit from the owner might make the tags indistinguishable again).

Other opinions are welcome! If there's no contrasting comments in a couple of weeks, I'll close this and check that API v3 doesn't allow the tag to be edited.
