### ISSUE TITLE
Reset account; Item still appearing as equipped.

### ISSUE THREAD

**Issue by Raeby** [HabitRPG/habitica#6975]
General Info
- UUID: c3ed4204-7c14-4c3a-9a73-a5ac64710bd1
- Browser: Chrome Version 49.0.2623.108 m
- OS: Windows 10
### Description

I recently reset my account and one of the items that I was previously wearing (mask) is visibly still equipped to my character but doesn't exist in my inventory. I tried resetting the account again and it's still showing the mask as equipped.

**Comment by Alys** [comment]
Sorry about that! You'll find that mask available for purchase in your Rewards column and once you've bought it, you'll be able to unequip it (and re-equip it) as normal. On the website, you can go to Settings > Site and use the [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) button to give yourself the gold needed to buy it.
