### ISSUE TITLE
rollover glitch

### ISSUE THREAD

**Issue by larewenevenstar** [HabitRPG/habitica#6976]
General Info
- UUID: da975ccc-2fd2-4e97-9da8-cfcc269c008b
- Browser: safari
- OS:  mac os X el captain
### Description

i completed all my dailies yesterday, but then when it rolled over to the new day, it said that i'd missed all my dailies from the previous day, and i lost all my health and all my gold. this is the first time this has happened since i complete all my dailies every day, so i lost all the gold and silver i'd gathered since i joined the site.
it's possible this was because i changed my rollover time for 4am to 5am (to work in line with another site and with the change in daylight savings), 
#### Console Errors

[//](#): #none that i know of

**Comment by Alys** [comment]
I'm sorry about that! Changing your Custom Day Start time (CDS) can cause cron to run early (although if you do it on the website, you'll see a confirmation screen that tells you when cron will next run). Timezone changes can also cause unexpected crons, and that with a CDS change at the same time could be unpredictable. :(

It is also possible that you were affected by [this bug](https://github.com/HabitRPG/habitrpg/issues/4313). There's an "Advice" section near the top that will help you recover from the unfair damage (points 1 and 2) - even if it wasn't that bug that damaged you.

We're hoping to make changes soon that will prevent unexpected crons from timezone changes, and the CDS confirmation screen will be on the mobile apps in future.

I'm closing this now but if you have questions or need further help, you're welcome to comment here and we'll still see it and reply.

**Comment by larewenevenstar** [comment]
hi there,

 i don't think it was that other bug, though that has happened to me a couple of times, i'm pretty sure it was to do with the timezone change.
but is there any way to get back the gold i lost? since it works at as most of the gold i've earned since i joined the site, apart from the small amount i've spent on weapons, armour and armoires. i think there was at least 20k in there, if not more. i cant remember exactly how much it was, but it was quite a lot to lose :S

**Comment by Alys** [comment]
Yes, see the Advice section near the top of [that bug report](https://github.com/HabitRPG/habitrpg/issues/4313). Points 1 and 2 will help you recover from the unfair damage even if it wasn't that bug that damaged you. That includes getting your gold back.
