### ISSUE TITLE
Confusing Transifex team management structure

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6977]
**The issue**: Confusing Transifex team management structure: 3 projects, each having its own team and language sub-teams

**Link**: a point from #6480 (Inactive translators on Transifex), preferably being discussed before addressing the issue of defining requirements for translators applying to become reviewers.

**Main question**: Do you think we need to separate the reviewers and coordinators of the three translation projects for the sake of presumably more reliable reviewing or have the same set of reviewers and coordinators for all the three projects for the sake of simplifying team management?

**Details:**
Our Transifex "organization" Habitica ( https://www.transifex.com/habitrpg/ ) has 3 projects (web, iOS, Android). Currently translators should join 3 teams responsible for these 3 different projects, then they have to join the language sub-teams of respective teams. To be made reviewers they need to apply to become ones of the 3 different teams... 

Transifex support think that there's no real point in having 3 teams with the same team management policies (they give the following example when several team might be needed: "Some customers choose to create a second team of trusted collaborators and assign them some projects that contain sensitive information or content with specific terms, like legal documents"). Transifex offers a way to simplify team management: we may have one team and all the three projects assigned to it.

Possible consequences, as I see them having tested a similar structure on a dummy Transifex organization (now deleted):

Pros:
- new translators would need to join only one team (and the languages sub-teams they want) to be able to translate all the projects having the respective languages
- when a language that exists in one project is added (created) to another project, corresponding language sub-team should automatically get access to translation without the need to join other teams (or at least get an invitation)
- the language sub-teams would be a bit easier to manage having  unified teams of reviewers/coordinators assigned to all the 3 projects (if language sub-teams get active coordinators in the future, managing a single language sub-team will be easier for them then managing 3 almost identical sub-teams of the 3 project teams)
- team discussions would be in one place for each language sub-team
- I seem to have enough right to implement the change not bothering the staff and developers busy with more important tasks :smile: 

No change:
- projects (files for translation) would be managed separately
- project announcements would be managed separately for each project
- adding a language to a project won't result in adding it to other projects, project languages are managed separately
- translators would have equal rights to edit all the three projects regardless of their actual access to the platforms to test (but without the need to join several teams)

Cons: 
- reviewers would have equal rights to review and edit strings in all the three projects regardless of their actual access to the platforms to test

I would appreciate some comments from @crookedneighbor @luveluen @paglias @vIiRuS as well as from other staff members and developers and of course opinions from translators.

[translations] [suggestion-discussion] [priority - minor]

**Comment by crookedneighbor** [comment]
1 team with 3 projects makes the most sense to me. Honestly didn't realize it was 3 teams until just now.

**Comment by ghost** [comment]
As far as I'm concerned, being a reviewer for a project without having access to the test platform isn't that much of a con, as it allows me to sync my corrections in all projects at the same time. Quite often, correcting some words on one project affects the others ; being a reviewer to all projects allows me to stay consistent across the platforms.

**Comment by ghost** [comment]
A quick update: I won't be able to do it myself as a team manager (not enough rights), as [Transifex documentation](http://docs.transifex.com/introduction/) has been updated to include:

> Organization Administrators ... Assign/move projects between teams:
> Projects are assigned to teams to be translated. A project can be assigned only to one team at a time, but a team can have many projects assigned. So, if you have three projects that get translated to the same target languages you only need to create one team and add the languages and their members once and not three times. You just assign the three projects to the same team and you're done!

and on [Teams](http://docs.transifex.com/features/teams/)

> #### Adding people to a Team to work on a Project
> 
> The team page is the place where you have an overview of all your teams and the assigned projects. All your collaborators (translators, reviewers, coordinators) are managed from your team page. 
> 
> From the same page you can assign a project to any other team at any time. Project languages will not be affected, the project will just start being translated by the people who participate in the new team.
> 
> ...Simply add or invite a person by clicking add member and your team will automatically support any languages this person speaks... This won’t add <_languages_> to the <...> projects that are assigned to this Team, since languages exist on a project level.

So if the suggestion is approved, we'll need the help of an admin on Transifex organization to unassign Android and iOS projects from their own teams and assign these projects to Habitica (habitrpg) project.

**Comment by ghost** [comment]
As there's been no objections and I've been granted access to assigning projects to teams, I'll be implementing the suggested changes in a couple of days:
- [x] Unassign the mobile teams from the mobile projects (as suggested by Transifex documentation; those teams may then be deleted)
- [x] Assigned all the three projects to HabitRPG team
- [x] Rename "HabitRPG team" to "Habitica contributors" team.
- [x] Make an announcement about the changes

BTW, is there any purpose the "[Team 1](https://www.transifex.com/habitrpg/teams/)" has been created on the organization? @paglias @crookedneighbor @vIiRuS

**Comment by crookedneighbor** [comment]
Not to my knowledge. Want aware of its existence.

**Comment by crookedneighbor** [comment]
*wasn't aware

**Comment by paglias** [comment]
Me neither, I've deleted it since it has no translators nor projects

**Comment by ghost** [comment]
Closing this as done.
I'll reopen it if we have any issues reported.
