### ISSUE TITLE
Problem running locally

### ISSUE THREAD

**Issue by jamesmgg** [HabitRPG/habitica#698]
![Screen Shot 2013-03-21 at 10 16 11 PM](https://f.cloud.github.com/assets/774806/289244/f431b87a-929e-11e2-8eea-0382729470eb.png)
Anyone know what's wrong with this? I followed the instructions on here: https://github.com/lefnire/habitrpg/wiki/Running-Locally however, I cannot get the server to run locally on OS X Lion

**Comment by lefnire** [comment]
Is it still a problem? I removed a lot of submodules?

**Comment by jamesmgg** [comment]
I have this problem with the latest code on the develop branch. Do I have to do anything extra with the mongodb? As I see the issue is a problem with the database.

**Comment by lefnire** [comment]
can you connect to mongo? `mongo habitrpg`

**Comment by switz** [comment]
Your mongod isn't running. Open a new terminal and run mongod

**Comment by jamesmgg** [comment]
thanks @switz doing that got rid of the problem I had in the screenshot. However, now connecting to the to localhost:3000 just hangs. And it returns an error after trying to load the page for a while

**Comment by switz** [comment]
Make sure you pull in the most recent code.

`git pull origin develop`

`npm install`

`git submodule init && git submodule update`

edit: updated

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
