### ISSUE TITLE
Huge cursor lag when typing in chat box for guilds and parties on website

### ISSUE THREAD

**Issue by imafable** [HabitRPG/habitica#6980]
General Info
- UUID: 5468b1fe-d50a-4180-9b99-14105a1941b4
- Browser: Chrome
- OS: Chrome Android and Windows 7
### Description

Whenever I access Habitica on PC or on Chrome on my mobile I can't really type efficiently. The cursor lags big time. It takes 3-5 seconds for what I've typed to appear in the box. That being said I prefer chatting via the Android App since this doesn't happen.

**Comment by Alys** [comment]
@imafable Thank you for reporting this, but we have it recorded at https://github.com/HabitRPG/habitrpg/issues/6462 so I'll close this now. 

If you do want to chat on the website, you might like to type your message first into a text editor and then paste it in. Pasting is instantaneous. Also, the [Chrome Chat Extension](http://habitica.wikia.com/wiki/Chrome_Chat_Extension) is an excellent tool and has no lag (although I haven't tried it on a mobile browser; it works well on a PC though).
