### ISSUE TITLE
Laundromancer Quest Participation Bug

### ISSUE THREAD

**Issue by lonealchemist** [HabitRPG/habitica#6987]
General Info
- UUID: 2c9105c1-bf5e-467c-a97c-386120d9f16d
- Browser: Chrome
- OS: Windows 10
### Description

Hi! This issue involves both the phone and the computer, so I'm not sure where it best fits. I hope that it is here :).

My party is having an issue with the quest participation in the Laundromancer. GoblinClan initiated the quest, and an e-mail was sent out. I went to accept it on my iPhone (5c), and it said that everyone already accepted the quest (see picture). I didn't think anything of it until the next day, when the only person who dealt damage was GoblinClan. I looked at the participant tab on the computer and it says that only GoblinClan is participating (see picture).

Thanks!

![iphone pic](https://cloud.githubusercontent.com/assets/17229058/14156411/e554a8f4-f68b-11e5-90a2-204ecd300a3e.PNG)

![computer](https://cloud.githubusercontent.com/assets/17229058/14156426/00fec382-f68c-11e5-86dc-2d54cbc43963.PNG)

Take care,
Maria

**Comment by Alys** [comment]
@lonealchemist Thanks for all the details and screenshots!

Could you please ask GoblinClan if e clicked on the "Begin" button at the bottom of the quest box? If e did, approximately when did e do so -- e.g., immediately after using the quest scroll to send invitations, or a few hours later, or...?

Also, could you please look on the iPhone app again and tell me if it still says "4 Participants" just above the red bar that shows the boss's health?

**Comment by lonealchemist** [comment]
GoblinClan doesn't remember, unfortunately. As for the participants, I took that picture right before I sent the request. I checked again and it still shows that there are 4 participants. Thanks :)!

**Comment by Alys** [comment]
I think it's likely that GoblinClan would have clicked the "Begin" button before you and the other party members had a chance to accept the invitation. That would explain the behaviour you describe, although it's possible there is also a bug that caused it.

The "Begin" button is intended for only situations where some party members do not reply to the invitation promptly, and it will cause the quest to start immediately. No other players can join the quest after that. If all party members are active and respond to quest invitations quickly, there's usually no need to use the "Begin" button. However, I'm not sure if the quest owner sees instructions about that that are clear enough for relatively new players to understand.

If you you notice something similar happening in future quests when the quest owner is certain they did not click on the "Begin" button, we definitely want to hear about it!

For the current quest, it's not possible by normal means for you to join it after it has started. Our usual advice is that the quest owner can abort the quest and send the invitations again. However I see that this is a quest with a strong boss and significant progress has already been made, so aborting it is undesirable! If GoblinClan approves, I can add you (and other party members) to the quest - it will keep running as normal but you will be participants. GoblinClan can comment here or send an email to admin@habitica.com and mention this issue's URL which is  github.com/HabitRPG/habitrpg/issues/6987. GoblinClan should say which party members should be added (or just say the whole party).

The thing where the app says "4 Participants" for the quest is definitely wrong. I've reported it as an iOS bug at https://github.com/HabitRPG/habitrpg-ios/issues/350

**Comment by GoblinClan** [comment]
I approve of adding the whole party to the quest. Sorry :(!

**Comment by Alys** [comment]
No worries, @GoblinClan! It could have happened by a bug.

I've added the whole party to the quest. 

If any of the party members don't do damage to the quest boss on the next time their cron happens, please comment here! I'm closing this now but we'll still see your comments and keep helping you.
