### ISSUE TITLE
I am a subscriber, but I am not receiving the mystery items

### ISSUE THREAD

**Issue by zefisio** [HabitRPG/habitica#6991]
Hi,

My USER ID is babf1497-3bf6-46d9-b1c3-a16fe7113a9c

I am not receiving my mystery items around 2 or three months.
I have subscribed to habitica in December (12 months subscription). However, the subscription goes automatically to the auto-renew. So, I canceled it in paypal. After that I stopped receiving gems.

The gems called my attention first, and I started to get them again after complaining here. But it seems the mystery items are still not working...

Thanks
Joe

**Comment by Alys** [comment]
Sorry about that! The dateTerminated value was in the wrong format, which was preventing the scripts that give you mystery items from working for your account. I've placed the four missing items into your Equipment page.

**Comment by zefisio** [comment]
Thank you!
