### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by thepixelmonk** [HabitRPG/habitica#7]
Apparently clicking the facebook connect button crashed the site :P

**Comment by lefnire** [comment]
something about the change made in [src/server/auth.coffee](https://github.com/lefnire/habitrpg/commit/79fd3f06898ecdd1f4a6d690ce9ca4599a36028f), reverted for now - try again

**Comment by lefnire** [comment]
Ok, hopefully d504cbea38 fixed this. @saiko-chriskun , could you try logging in again per chance?

**Comment by thepixelmonk** [comment]
I can log in, however seem to have some issues with the bar at the top right: http://ompldr.org/vZng4OQ

**Comment by lefnire** [comment]
Ah yes, that's another bug that's been vexing me since the dawn of time. Just log out and log back in.

**Comment by thepixelmonk** [comment]
Yep works now :P

**Comment by lefnire** [comment]
I promise it's not as janky as it seems, you're discovering my easter eggs :D

**Comment by thepixelmonk** [comment]
hehe :P

**Comment by pfraces** [comment]
same top right bar weird effect
having to logout and login again is a bit annoying
is better to open another issue for this?

**Comment by lefnire** [comment]
looking into. restarted for now, should be up. Heroku logs showing https://gist.github.com/3948997

**Comment by lefnire** [comment]
lotta issues going on right now with habit + heroku that I'm trying to pan out, site keeps going down with [this error](https://gist.github.com/3949864) (uids should be guids, I added some checks that uid is legit). Heroku's not accepting my git pushes with attempted fixes, I have a ticket in the issue queue - i'll keep you all posted. for now, i'll keep restarting when it crashes

**Comment by lefnire** [comment]
there we go, server crashing fixed a la 198987dfa0f5411cf6ef10bfd1e9f78f22c106a9

**Comment by lefnire** [comment]
moving the login/logout bit to new issue #10
