### ISSUE TITLE
Random Challenge

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#70]
_wc8: Vote here: [Random](https://trello.com/c/zQ7lwk73)_
Every so often HabitRPG sets up a challenge between you and another user. Everything is random the amount of gold or items gained/lost and the duration.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
Indexed on Trello: [Random Challenges Between Users](https://trello.com/c/zQ7lwk73)
