### ISSUE TITLE
Unable to leave party

### ISSUE THREAD

**Issue by thirdtruck** [HabitRPG/habitica#7006]
General Info
- UUID: 2ebb7eab-6306-4055-af27-db70b4b36bad
- Browser: Chrome Version 49.0.2623.110 (64-bit)
- OS: Ubuntu Linux
### Description

Howdy. Clicking the `Leave` button under my current party has no effect; I'm unable to leave the party. I get an error in the console instead.

It appears related to https://github.com/HabitRPG/habitrpg/issues/6279. Clearing the browser cache, the local storage, and using Incognito mode all failed.
#### Console Errors

```
app-c16ee834.js:6 TypeError: Cannot read property '_id' of null
    at app-c16ee834.js:36
    at hb (app-c16ee834.js:31)
    at Function.Yd (app-c16ee834.js:31)
    at app-c16ee834.js:36
    at app-c16ee834.js:10
    at j (app-c16ee834.js:7)
    at app-c16ee834.js:7
    at j.$eval (app-c16ee834.js:7)
    at j.$digest (app-c16ee834.js:7)
    at j.$apply (app-c16ee834.js:7)
```

Thank you for looking into this!

**Comment by Alys** [comment]
Can you please reload the party page (that part is important!) and then try leaving again?

**Comment by thirdtruck** [comment]
No luck. :frowning:

**Comment by Alys** [comment]
I've removed you from the party and I've copied the details of this issue to #6279 to keep it all in one place. If you reload now, the party should be gone but tell us if it isn't.

**Comment by thirdtruck** [comment]
All good now. Thanks!
