### ISSUE TITLE
Everything is so big!

### ISSUE THREAD

**Issue by ShabbyX** [HabitRPG/habitica#702]
The latest interface seems to have made everything too big. One may argue about how the Windows-8 style is actually beautiful or not, but I think even with that same style, making things a bit smaller would be nice.

Previously, on a normal monitor, habits in each section were almost all visible with one look, but now you'd have to scroll up and down, look around and move the mouse in larger arcs to find and click on them habits.

Perhaps making the fonts slightly smaller, decreasing the margins a bit wouldn't be bad (worth a try).

It may also help if "New ..." input boxes were moved below the list? I think we'd be trying to get ourselves into some habits that we have already written there, rather than getting into a new habit everyday. So the "New ..." fields are probably not as much used as the habits already inserted.

**Comment by Shaners** [comment]
See issue #585, a lot of discussion of that going on there.

**Comment by wc8** [comment]
(Regarding new input boxes many people requested them to be placed above the list.)
I'm closing this for housekeeping, since this is being discussed on the thread Shaners referenced.

**Comment by ShabbyX** [comment]
Sorry about the duplicate. I took a look over the interface tag and didn't find that issue. D'oh!
