### ISSUE TITLE
Quest with no rewards

### ISSUE THREAD

**Issue by matheusg1** [HabitRPG/habitica#7024]
ID: cc792df7-ad4d-427e-b5a1-7e2e56c57f85
Browser: Chrome
OS: Win7

I have finished the quest "A Stern Talking-To" with my team. I accepted the quest by my Android and I did my tasks using that phone, I know that the app don't show the rewards yet, so I decide to see what I won using my notebook, but when I entered my account there was no rewards. I have accepted some others quests before on my Android and it was alright with the rewards, but I have logged at least one time on the computer during the quest. This time I didn't do that if I remember well, it was all by the phone.

**Comment by crookedneighbor** [comment]
@matheusmt021 Were you able to figure it out?

**Comment by crookedneighbor** [comment]
Oh, I see, you found a previously opened issue.

**Comment by matheusg1** [comment]
Yes, thanks.
