### ISSUE TITLE
"Application error"

### ISSUE THREAD

**Issue by headhunter7987** [HabitRPG/habitica#7027]
General Info
- UUID: d42cffe7-54bf-4b84-b886-70b43e3b6d03
- Browser: Google Chrome
- OS: OSX Yosemite (10.10.3)
### Description

This is an occasional bug which crashes the site completely and leaves the words **"Application Error"** bolded across the top left of the screen. It normally happens two or three times in a row, and then Habitica begins functioning normally

**Comment by scott-joe** [comment]
I was editing a number of Habits in sequence before the save bar finished and after a moment, I was greeted with this.

<img width="313" alt="screen shot 2016-04-06 at 10 48 09" src="https://cloud.githubusercontent.com/assets/2026866/14321170/15a601f6-fbe6-11e5-95f1-26df0bb8f0f6.png">

So I refreshed...
![screen shot 2016-04-06 at 10 49 05](https://cloud.githubusercontent.com/assets/2026866/14321192/314ad10c-fbe6-11e5-9f06-08d3d447e1c3.png)

This only appeared once, over the next 10 refreshes, various assets would time-out leaving me with missing icons or no styling at all and a series of 503 console errors. Now the page appears to load correctly, but the only errors I get are:

<img width="874" alt="screen shot 2016-04-06 at 10 58 27" src="https://cloud.githubusercontent.com/assets/2026866/14321274/8c64f7b6-fbe6-11e5-8041-60f35dd1be2d.png">

**Comment by qwixilver** [comment]
I also got the same error. Mine is a bit more consistent than what Scott reported above. I've been refreshing for about 5 minutes but the error persists. I am running chrome Version 49.0.2623.110 m on a windows 10 desktop pc. I have a few more errors in my console than what Scott has reported. They are as follows:

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-05136417.js:33 ObjectresponseError @ app-05136417.js:33
https://habitica.com/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular-4d650026.woff Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://habitica.com/common/dist/sprites/spritesmith-main-2-ef39f5af.png Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://habitica.com/common/dist/sprites/spritesmith-largeSprites-0-4b0e6495.png Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1392595313.1459461263&jid=1178667871&_v=j41&z=1811532240 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://habitica.com/api/v2/user/batch-update?_v=458&data=1459955286809 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-05136417.js:33 ObjectresponseError @ app-05136417.js:33j @ app-05136417.js:7(anonymous function) @ app-05136417.js:7j.$eval @ app-05136417.js:7j.$digest @ app-05136417.js:7j.$apply @ app-05136417.js:7s @ app-05136417.js:6w @ app-05136417.js:6y @ app-05136417.js:6nrWrapper @ habitica.com/:1
```

**Comment by ghost** [comment]
I get the same error picture as Scott-Joe, but it's not going away. I tried to do a fast sequence of events in Habitica before the update scroll bar finished. While Habitica seems to load my stats correctly, the error still appears after every action. 6ad90f79-531d-4d71-a2ef-2b9505212a5e

**Comment by ditabug** [comment]
Happening to me as well. 5240ba4c-aabd-484c-9129-285c77ad196a

**Comment by scott-joe** [comment]
Yeah... it's still happening... being a 503 server error, I'm beginning to
think it's not just me.

**Comment by ghost** [comment]
Mine went away. Not sure why, but thank you Habitica team!

**Comment by SabreCat** [comment]
We've finished migrating to a new server platform that should help us catch these situations faster. Thanks for bearing with us!

**Comment by lemoness** [comment]
We are so sorry about this! Some of our servers went down, which was causing the errors. It should be fixed now. Please let us know ASAP if it isn't! 

 If you lost health, gold, or anything else due to the server outages, you can restore your lost stats on the website under Settings > Site > Fix Character Values. You can also restore lost streaks on the website when you edit a task. Feel free to ask if you have any questions and thank you so much for all of your patience!
