### ISSUE TITLE
Repeated deaths due to red dailies

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#703]
I wasn't able to use HabitRPG for a while, and I expected to die due to that. What I didn't expect was my daily tasks staying red so that I died the next day as well for not completing some of them. It's very hard to recover, which is demotivating.

I wish the tasks lost their redness or something like that.

**Comment by lefnire** [comment]
use re-roll, bottom reward

**Comment by Olathe** [comment]
Oh, I see. Thanks.
