### ISSUE TITLE
Greedy click-off, two at a time, or just random

### ISSUE THREAD

**Issue by Lexidh** [HabitRPG/habitica#7031]
General Info
- UUID: 
- Browser: 
- OS: 
### Description

I'm having some really weird issues these days. (Reboot done, didn't help, actually it got worse.)
When I try to click off a daily or task it doesn't just take one, it takes the next one in line too and marks it as done, OR just pretends to do so (I get two sets of xp/coin/loot/messages) OR if it is a daily it sometimes picks something else at random from the all blue list. Chrome browser, no updates or whatever lately. Does not seem to happen if I haven't scrolled in a little bit. Am I totally daft, or do I remember something like this from waaaay back when? Dooo eeeverything sloooowly, or a bug arises? I think it was the other way around, that if I clicked stuff too quickly, it wasn't marked as done at all. Now we seem to be at the other end of the scale ;P

**Comment by Alys** [comment]
Please log out of Habitica and tell us if it still happens after that.

It's probably the same issue as reported in https://github.com/HabitRPG/habitrpg/issues/6670 and seems to happen when the browser gets confused. Logging out typically fixes it.

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see my previous post, and let us know if that worked or not.
