### ISSUE TITLE
Cron reset issue

### ISSUE THREAD

**Issue by bunniphish** [HabitRPG/habitica#7033]
My cron did not reset properly last night. All of my dailies are still greyed out, and the current quest I am on (Golden Knight Part 1) says I collected 0 items. Since I gained a level and a half yesterday, that can't be correct. The blue sync bar appeared every time I clicked on something yesterday, and again this morning. I attempted to fix the problem by hitting the sync button, logging out then back in, clicking a task, and casting a spell, to no avail. 
- UUID: 278d706c-0f1a-4b21-b0b5-c34d467beb4e
- Browser: google chrome
- OS: windows

**Comment by citrusella** [comment]
Did you take any unexpected damage? If so, you may be experiencing this bug: #4313 . If not, then... _patiently waits for someone more knowledgeable but wanted to provide the info I did know_

**Comment by bunniphish** [comment]
No, I did not experience any unexpected damage. All my dailies were completed, and I retained full hp.

**Comment by Alys** [comment]
@bunniphish Has cron run properly on the days since then? I've checked the cron-related settings in your account and can't see anything wrong there, so I'm wondering if this was just a once-off glitch.

**Comment by bunniphish** [comment]
It appears to be a one-time problem.

**Comment by Alys** [comment]
Thanks for letting us know! Tell us if it happens again.
