### ISSUE TITLE
Consistent 504 error on every page

### ISSUE THREAD

**Issue by bronzebow** [HabitRPG/habitica#7038]
- UUID: 0b9c2804-388a-4425-a794-5ab914782014
- Browser: Chrome Version 49.0.2623.110 m
- OS: Windows 7 64bit

I receive a red timeout error on every page (text below in quotes). This started whenever I was the leader in a party of myself and one other person (Let's call her Alice). Alice sent me a party invite which I accepted, and for a while I had trouble even viewing the Party page. That eventually resolved but now I'm stuck with this constant 504 attempt to load:

"Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.

"Error
504 Gateway Time-out

The server didn't respond in time.

" 

If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages."

I also receive this JavaScript error:
![image](https://cloud.githubusercontent.com/assets/10726408/14363834/c64c09d4-fccb-11e5-91c6-3d6871dc1368.png)

**Comment by crookedneighbor** [comment]
Are you still experiencing this? Does logging out and logging back in help?

**Comment by crookedneighbor** [comment]
Going to close this now, but please respond if you're still having issues.

**Comment by bronzebow** [comment]
Apologies, I was traveling this week.

No, I'm not seeing this anymore. Thanks!
