### ISSUE TITLE
Weird API behavior using curl vs the browser

### ISSUE THREAD

**Issue by wfjackson3** [HabitRPG/habitica#704]
The API documentation shows some examples using curl. I can't get anything to work as I would expect based on the documentation.

If I go to https://habitrpg.com/api/v1/status in the browser, I see the expected json response.

If I use curl to the same URL, I get a 404. I played around with it for a while, and found that if I use:

> curl -v -H "Accept-Encoding: gzip" https://habitrpg.com/api/v1/status

I get a 200 code, but of course the response is compressed. What am I missing here?

**Comment by switz** [comment]
Add in the `--compressed` flag.

**Comment by wfjackson3** [comment]
Yeah that makes me feel silly, but hey, at least I wasn't the only person who missed it here.
