### ISSUE TITLE
Test dependencies not installed in vagrant.sh

### ISSUE THREAD

**Issue by lucubro** [HabitRPG/habitica#7054]
Hi! I'm trying to set up habitica locally and I stumbled upon [this line](https://github.com/HabitRPG/habitrpg/blob/develop/vagrant_scripts/vagrant.sh#L60). Is it actually meant to be

```
/vagrant/vagrant_scripts/install_test_dependencies.sh
```

?

If that's the case, I can open a PR and fix it.

**Comment by Alys** [comment]
That seems reasonable, and I've just successfully run that script on my local install so it does work. Thanks!

**Comment by lucubro** [comment]
All right! I'll open a PR soon then.
