### ISSUE TITLE
Incorrect SSL Certificate

### ISSUE THREAD

**Issue by AMorporkian** [HabitRPG/habitica#7055]
HabitRPG.com is currently serving the SSL certificate for *.habitica.com. Just thought you folks might want to know. I believe previously HabitRPG.com was giving a 301 to Habitica.com.

**Comment by librarianmage** [comment]
What do you mean? habitrpg.com still redirects to habitica.com.

**Comment by AMorporkian** [comment]
And now it's working again. I can assure you, it was serving on 443 with a *.habitica.com certificate. It's resolved though, so I'm closing.

**Comment by librarianmage** [comment]
Odd... _shrug_

**Comment by crookedneighbor** [comment]
We made some changes to the DNS settings and _think_ this is related. Re-opening this so we can keep track of it.

**Comment by AMorporkian** [comment]
Well, now it has the proper domain, but the cert expired today.

![mrpcdi6](https://cloud.githubusercontent.com/assets/5653369/14407661/7a6debd6-fe97-11e5-9320-c5180acacc33.png)

**Comment by AMorporkian** [comment]
(And yes, I'm aware that this is because my homepage is to the old URL, and I could very easily correct it, but I'm sure I'm not the only one with outdated links)

**Comment by crookedneighbor** [comment]
Weird. When I go to `https://habitrpg.com` or `http://habitrpg.com` on my computer, it redirects me (correctly) to `https://habitica.com`. Same thing on my mobile browser for `http`, but `https://` resolves instead stays on `habitrpg.com`

We're looking into this. The correct behavior is that `habitrpg.com` should _always_ redirect to `habitica.com`. Thanks again @AMorporkian for reporting it, but I would definitely use `habitica.com` instead, especially while we sort this out.

**Comment by AMorporkian** [comment]
@crookedneighbor, I have a little more info for you. It appears my computer is hitting 50.16.225.80, which is serving the expired SSL certificate. 50.16.225.80 appears to redirect from http:// to https:// on the same hostname, which is giving me the error. Due to the multiple A records, it would depend on your DNS whether you would happen to hit it, which explains why you're unable to see the error.

Manually change your hosts file so 50.16.225.80 -> habitrpg.com, and you should be able to reproduce.

![mrpcdi6](http://i.imgur.com/2Cv85sQ.png)

**Comment by crookedneighbor** [comment]
This _should_ be resolved now.
