### ISSUE TITLE
Comforting Crown string error

### ISSUE THREAD

**Issue by Janmetdepet** [HabitRPG/habitica#7057]
I just found a small bug.

The Comforting crown description says: "error processing the string".

I've refreshed, that doesn't work.
I'm using the Dutch translation, as you can see in the screenshot below.
http://snag.gy/Y6nEb.jpg

**Comment by ghost** [comment]
Thank you very much for reporting it! I've fixed the string on Transifex, where we manage translations and it should be online we the next locales update.

I've checked the translations made by the translator responsible for this, and it seems to be just an accidental typo. Unfortunately there's no way we can filter those small typos in variables now - other than user reports.

This ticket will be closed. If you (or someone else finding this ticket) happen to come across another instance of an "Error processing the string", please post to the ticket #5465
