### ISSUE TITLE
Can't close challenge

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7059]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 49.0.2623.110
- OS: Windows 7
### Description

Can't end challenge. I choose the winner (@NovaVita), the pop-up comes, asks if I am sure, I click yes, then nothing happens. I can close other challenges, but not this one.
Some users also reported previously, that they couldn't join the challenge.
https://habitica.com/#/options/groups/challenges/575e5251-fc44-4279-9620-d31643b2937e

**Comment by Alys** [comment]
I've closed the challenge and awarded the prize to NovaVita.
