### ISSUE TITLE
form for changing display name and profile blurb and photo URL does not mention Community Guidelines

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7060]
The form at [User > Profile](https://habitica.com/#/options/profile/profile) > Edit allows you to change your Display Name and profile photo and blurb. All three must abide by the [Community Guidelines](https://habitrpg.com/static/community-guidelines) but there is no mention of that on the form.

I believe we should have a link to the Guidelines and one or two sentences to describe what should not be used (no adult topics, no insulting material, etc).

@Lemoness, if you agree, would you like to supply some words?

**Comment by lemoness** [comment]
I do agree!

How about:

Please keep in mind that your Display Name, profile photo, and blurb must comply with the [Community Guidelines](https://habitrpg.com/static/community-guidelines) (e.g. no profanity, no adult topics, no insults, etc). If you have any questions about whether or not something is appropriate, feel free to email leslie@habitica.com!

**Comment by librarianmage** [comment]
@Alys @lemoness If everything is taken care of, I can do this!

**Comment by Alys** [comment]
@MathWhiz yes, please do this if you wish to. Include a screenshot of what it looks like in the PR.

**Comment by librarianmage** [comment]
Ok!
