### ISSUE TITLE
Can't delete daily task for expired challenge

### ISSUE THREAD

**Issue by aksteele** [HabitRPG/habitica#7062]
I've got a task on my daily task list I'd like to delete. I can't delete it from the daily task list, and I can't locate the actual challenge to leave the challenge.

**Comment by citrusella** [comment]
Try checking off the task. Does the megaphone turn red? If the megaphone is red, you can click the megaphone to leave the challenge. If that doesn't work, go through the steps [here](http://habitica.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task).

**Comment by aksteele** [comment]
Thanks! This worked.

**Comment by Alys** [comment]
@aksteele Thanks for letting us know!

@citrusella Thanks for the help!!
