### ISSUE TITLE
Purchased Hairstyle Set 1 (gems), some styles now missing

### ISSUE THREAD

**Issue by viiibithero** [HabitRPG/habitica#7063]
General Info
- UUID: 21af5c90-5aa7-4a6c-bea5-df57657a6d16
- Browser: Chrome 48.0.2564.116
- OS: Windows 10
### Description

I purchased Hairstyle Set 1 with 5 gems a little while ago, and when I go back to customize my avatar only 2 of the total hairstyles are unlocked.

**Comment by Alys** [comment]
I'm sorry about that! We can definitely get it fixed for you!

To help us work out what went wrong, could you please tell us:
- Approximately how long ago did you buy the set? Hours/days/weeks?
- Did you buy it on the website or iOS app or Android app?
- Do you recall seeing that all the hairstyles were unlocked after you bought them? I.e., did they become locked some time after that?

**Comment by viiibithero** [comment]
I think I bought the set last week sometime

I bought it on the website

I remember trying on a few hairstyles so yes they were all unlocked

And yes I just noticed today that only 2 of the set appear as unlocked, the rest are locked.

Thanks so much for your help!  Let me know if you need anything else!

**Comment by Alys** [comment]
Thanks for the details! I've given you five gems; reload if you don't see them yet. Can you please try buying the set again and tell us how it goes?
