### ISSUE TITLE
Avatar and name in level-up (to 15) dialog have cursor: pointer

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7066]
General Info
- UUID: 0e1d15f7-f36b-4f15-a9e1-0c31b732dac9
- Browser: Chrome 49
- OS: Ubuntu 14.04
### Description

When leveling up to level 15 (and presumably other levels), a special dialog is displayed showing the quest scroll you just got awarded. In this dialog, your avatar and level show a pointing cursor, but clicking on them does nothing. This is due to the `.herobox` class on the divs surrounding them.

~~I can take a proper look at this within the next few days~~, unless someone else has a burning desire to make a new class, stick `cursor: pointer` on it, apply it to the main avatar and remove `cursor: pointer` from .herobox, which I suspect is all it will take to fix this. OTOH, I haven't done any kind of testing to see which dialogs it happens on, and I don't know where (or why) .herobox is used.
#### Console Errors

n/a

**Comment by keysmashes** [comment]
On second thoughts, I have no idea how the avatar rendering works, and I can't get my local install working, so I probably won't be able to get this done.

**Comment by Hus274** [comment]
I can take a look into this
