### ISSUE TITLE
Hi! I have a problem with one of my Dailies, I'm sure I checked it before it turned 00:00 but when I reloaded the page it behaved as if I missed the Daily. Couldn't you advise me what to do?

### ISSUE THREAD

**Issue by LeicaEnergizer** [HabitRPG/habitica#7075]
General Info
- UUID: 
- Browser: 
- OS:

**Comment by Alys** [comment]
Hi @LeicaEnergizer . You were affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313

There's an "Advice" section near the top that will help you recover from the unfair damage and fix the streak.

I'm closing this now but if you have any questions, comment here. We'll still see your reply even though this is closed.
