### ISSUE TITLE
Party completed Vice part 2, did not receive quest scroll for part 3

### ISSUE THREAD

**Issue by Hypevosa** [HabitRPG/habitica#7077]
General Info
- UUID: 1fe76c37-0935-4849-8260-fffaa1137ca5
- Browser: Chrome
- OS: Windows
### Description

[//]: # Party completed the Vice part 2 quest where you collect the light crystals, but I did not receive the Vice part 3 quest scroll, so we cannot continue with it.

**Comment by Alys** [comment]
I've given the achievement and rewards to you. Reload if you don't see them. Please tell me if they don't appear after that!

If other party members also didn't receive the rewards, you or they can put their User IDs here. 
I'm closing this now but we'll still see your reply.
