### ISSUE TITLE
Joined a friend's party and now I'm no longer in it?

### ISSUE THREAD

**Issue by wasteofrage** [HabitRPG/habitica#708]
My friend added me to her party, and I accepted, and she was showing up in the header on my page, but later today I went back on and her avatar was gone, and I was told I was not currently in a party. I never clicked anything that said "leave party".

**Comment by lefnire** [comment]
can you rejoin her party? (she may have to re-invite you). If not, [shoot me](mailto:tylerrenelle@gmail.com) your user id and I'll investigate. May be related to https://github.com/lefnire/habitrpg/issues/644

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
