### ISSUE TITLE
Dilatory Distress, Part 1: Message in a Bottle

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#7083]
General Info
- UUID: 29c5340b-d150-4347-862c-fec571a18b8a     \*      *Browser: Web browser  Chrome
- OS: android app, mobile browser 
### Description

Quest said All items found, party received their awards, no one received any  awards, some of us already completed this quest  some time ago

**Comment by JerseyEmerald** [comment]
Another quest problem,  might had something to do with android app update  going out and our team quest ending, possible system overload, anyway here's the info...
Our quest Dilatory Distress, Part 1: Message in a Bottle 
It said All items found! Party has received their rewards. -10 hours
No one received the Rewards
Finned Oceanic Armor (Armor)
75 Experience
**\* please note, many of us already completed this quest before which is why it's listed in our stats :) ***

My id    29c5340b-d150-4347-862c-fec571a18b8a
Party    Afternoon Tea 
Group id. 743aac61-a781-41e1-8017-1610873fcfa4
Players that didn't get rewarded 

Group Leader:Lazyez8
Lazyez8 (50.0 HP)
Smokeflower (50.0 HP)
Roberto (50.0 HP)
SlayerSSavate (50.0 HP)
JerseyGirl01 (50.0 HP)
corilannam (50.0 HP)
KarlBear (50.0 HP)
Kinsey (50.0 HP)
Ak14523 (50.0 HP)
PhoenixFlorid (50.0 HP)
claritastic (50.0 HP)
Bomber1705 (50.0 HP)
nickdin (50.0 HP)
An Na (50.0 HP)
Miyuki47 (50.0 HP)
Absolute_Zero (50.0 HP)
mourad244 (50.0 HP)
Arthur__ (50.0 HP)
Fly (50.0 HP)
I hope this helps and thank you 🙂

**Comment by Alys** [comment]
Sorry about that, @JerseyEmerald! I've given the quest rewards and achievements to those players. Reload if you don't see them. Please tell me if they don't appear after that!

**Comment by JerseyEmerald** [comment]
Thank you!!!
