### ISSUE TITLE
Party member is under Member and Invited at the same time

### ISSUE THREAD

**Issue by Suamppa** [HabitRPG/habitica#7084]
I added a friend of mine as a member to our party through an email invite like all the others, but for some reason he has been duplicated as both a member and an invited member at the same time. Below is a screenshot of the members list with the issue. As you can see, Zetrou is on both of the lists.

![image](https://cloud.githubusercontent.com/assets/18483942/14561863/025f16f8-0322-11e6-87c6-fd38f85d75df.png)

He did mention that for some reason, the invite link included in the email always threw him into the _Tasks_ page. He had to manually go to the _Create Party_ screen to see the actual invite.

My user ID is 2d4cca17-592e-40ae-9f60-f40dd274bc71
Zetrou's user ID is 08878f8a-f79e-4b0a-8a0f-ec21dfb5dbd5
Our party's group ID is ac22c253-b712-47c9-a3c0-11c74b723d9c

I am using Chrome version 49.0.2623.112 m (64-bit) on Windows 7 Ultimate SP1.

I can see one warning in the JavaScript console. I'm not sure if this is even related but here it is:
`Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error
    at p.zone (https://habitica.com/app-393f3006.js:32:27256)
    at Object.q.authenticate (https://habitica.com/app-393f3006.js:34:4153)
    at Object.<anonymous> (https://habitica.com/app-393f3006.js:34:5337)
    at Object.i [as invoke] (https://habitica.com/app-393f3006.js:5:16822)
    at Object.c [as $get] (https://habitica.com/app-393f3006.js:5:15218)
    at Object.i [as invoke] (https://habitica.com/app-393f3006.js:5:16822)
    at https://habitica.com/app-393f3006.js:5:14868
    at g (https://habitica.com/app-393f3006.js:5:16455)
    at Object.i [as invoke] (https://habitica.com/app-393f3006.js:5:16789)
    at D.instance (https://habitica.com/app-393f3006.js:6:8436)
`

**Comment by crookedneighbor** [comment]
The console error is not related.

**Comment by Suamppa** [comment]
I tried using _Boot Member_ on the copy of Zetrou under the _Invited_ list. At first this worked and the copy disappeared from the _Invited_ list while Zetrou remained on the _Members_ list. Just to make things sure, I went to the Tasks screen and then back to the Party screen _(I've found this to be a more reliable refreshing method than just hitting the browsers refresh button)_, and Zetrou had moved from the _Members_ list to the _Invited_ list _(Luckily, without a copy this time)_. However, all this time he remained on the avatar list of party members next to mine, so I tried the old log out and log back in method, which worked and he disappeared. After this I went to the party screen and booted the invited Zetrou as well. This time he seemed to stay gone so I sent him a new invite. Hopefully this one doesn't do anything weird.

**Comment by librarianmage** [comment]
@Zambad Related: #5649

**Comment by Alys** [comment]
@Zambad I'm closing this, but if it happens again, tell us and we'll reopen it.

**Comment by Suamppa** [comment]
Well yes, it is currently getting worse:

![image](https://cloud.githubusercontent.com/assets/18483942/14646129/094e45b4-0661-11e6-9a42-76290c6b31af.png)

It was just wartzu for a while after we got Zetrou back, and now it seems he has been cloned as well. I'll send them both that fix linked by @MathWhiz as soon as I know that they'll be able to do it instantly (otherwise they _will_ forget).

Wartzu's user ID is d0a56754-a49e-4ec5-8637-ab4ffeccc3d3

This is currently not directly affecting our party in any way, so I'm not hugely worried about this, but I do find this issue to be curious and wish to help fix it in any way I can.

**Comment by Alys** [comment]
@Zambad No worries, I'm reopening this. From your previous message with no follow up, it looked like the problem had stopped. It's always worth telling us when there's a change to an open issue so that we know we need to keep working on it. 

We can delete the excess members from the invitation list. Tell us when wartzu and Zetrou have gone through that process from MathWhiz's link.

**Comment by Suamppa** [comment]
This will take some time because wartzu won't have access to a computer until next Monday.

**Comment by Suamppa** [comment]
Wartzu has done the fix but I'm still trying to kick Zetrou to action...

**Comment by Alys** [comment]
@Zambad When wartzu did the fix, the excess invitation for wartzu's account disappeared from your party's invitations section without me needing to do anything. The same is most likely to happen when  Zetrou does the fix, and even if Zetrou never does, the excess invitation won't be doing any harm, so I'm going to close this now.

We're close to the end of a project to make some changes to Habitica's back-end code, which will prevent this problem happening again.
