### ISSUE TITLE
Purchased Weapon is not Appearing

### ISSUE THREAD

**Issue by ninjasophia** [HabitRPG/habitica#709]
This issue (https://github.com/lefnire/habitrpg/issues/233) is back again. 

I purchased the Morningstar, the gold was taken but the weapon didn't show up on my avatar--it's still the second level sword.

I'm using Chrome on LinuxMint14.

**Comment by lefnire** [comment]
i'll close this and re-open that since we have some background info from there to go off of. [shoot me](mailto:tylerrenelle@gmail.com) your user id and i'll investigate
