### ISSUE TITLE
Issue installing on c9.io

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#7090]
General Info
- UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee
- Browser: N/A
- OS: Ubuntu (I think)
### Description

When running `npm install` in a cloud9 box, I get this error

```
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/babel-register/lib/node.js:3:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! habitrpg@0.0.0-152 postinstall: `bower --config.interactive=false install -f; gulp build;`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitrpg@0.0.0-152 postinstall script 'bower --config.interactive=false install -f; gulp build;'.
npm ERR! This is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --config.interactive=false install -f; gulp build;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs habitrpg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
```

What should I do to fix this?

**Comment by librarianmage** [comment]
If needed, I can also include more of the error

**Comment by BrunoAssis** [comment]
I have the same error when trying to run `npm install` in my local machine (OS X 10.11.4), [using Docker](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Docker).

**Comment by Alys** [comment]
I'm doing a local install from scratch on Mac OS (OS X 10.11.4; El Capitan) using the Vagrant process (but with https://github.com/HabitRPG/habitrpg/blob/develop/vagrant_scripts/install_node.sh#L19 modified to use npm@2). I haven't noticed any errors in the process until this happens:

```
angular#1.3.9 website/public/bower_components/angular
module.js:327
    throw err;
    ^
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:325:15)
```

There's more context below.

I was also getting similar errors with other modules on the weekend when I was experimenting with a direct install on a Ubuntu host. All the modules were related to babel.

I'll be looking into this further again tomorrow.

```
bower BrowserQuest#c3a960b03031dad5d                 install BrowserQuest#c3a960b030
bower angular#1.3.9                                  install angular#1.3.9

github-buttons#3.0.0 website/public/bower_components/github-buttons

css-social-buttons#1.1.1 website/public/bower_components/css-social-buttons

swagger-ui#2.0.24 website/public/bower_components/swagger-ui

Angular-At-Directive#c27bae207a website/public/bower_components/Angular-At-Directive

bootstrap-growl#162daa41cd website/public/bower_components/bootstrap-growl

js-emoji#f25d8a303f website/public/bower_components/js-emoji

angular-bootstrap#0.13.0 website/public/bower_components/angular-bootstrap
└── angular#1.3.9

angular-ui#0.4.0 website/public/bower_components/angular-ui

angular-ui-utils#0.1.0 website/public/bower_components/angular-ui-utils
└── angular#1.3.9

bootstrap-tour#0.10.1 website/public/bower_components/bootstrap-tour
├── bootstrap#3.1.0
└── jquery#2.1.0

angular-ui-select2#afa6589a54 website/public/bower_components/angular-ui-select2
├── angular#1.3.9
├── jquery#2.1.0
└── select2#3.4.8

angular-sanitize#1.3.9 website/public/bower_components/angular-sanitize
└── angular#1.3.9

angular-resource#1.3.9 website/public/bower_components/angular-resource
└── angular#1.3.9

marked#0.2.9 website/public/bower_components/marked

ngInfiniteScroll#1.0.0 website/public/bower_components/ngInfiniteScroll

jquery-ui#1.10.3 website/public/bower_components/jquery-ui
└── jquery#2.1.0

jquery.cookie#1.4.0 website/public/bower_components/jquery.cookie
└── jquery#2.1.0

angular-filter#0.5.1 website/public/bower_components/angular-filter
└── angular#1.3.9

angular-mocks#1.3.9 website/public/bower_components/angular-mocks
└── angular#1.3.9

pnotify#1.3.1 website/public/bower_components/pnotify

sticky#1.0.3 website/public/bower_components/sticky
└── jquery#2.1.0

angular-loading-bar#0.6.0 website/public/bower_components/angular-loading-bar

angular-ui-router#0.2.13 website/public/bower_components/angular-ui-router
└── angular#1.3.9

jquery-colorbox#1.4.36 website/public/bower_components/jquery-colorbox
└── jquery#2.1.0

jquery#2.1.0 website/public/bower_components/jquery

hello#1.5.0 website/public/bower_components/hello

select2#3.4.8 website/public/bower_components/select2
└── jquery#2.1.0

bootstrap#3.1.0 website/public/bower_components/bootstrap
└── jquery#2.1.0

BrowserQuest#c3a960b030 website/public/bower_components/BrowserQuest

angular#1.3.9 website/public/bower_components/angular
module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/babel-register/lib/node.js:3:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.15.3
npm ERR! code ELIFECYCLE
npm ERR! habitrpg@0.0.0-152 postinstall: `bower --config.interactive=false install -f; gulp build;`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitrpg@0.0.0-152 postinstall script 'bower --config.interactive=false install -f; gulp build;'.
npm ERR! This is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --config.interactive=false install -f; gulp build;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs habitrpg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by librarianmage** [comment]
@Alys If I remember correctly, the first time I ran `npm install`, one part
of it didn't seem to respond but quickly filled up the RAM, causing c9.io
to quit the program.

**Comment by librarianmage** [comment]
@Alys after explicitly installing `babel-runtime`, I get this error:

``````
Error: Cannot find module 'lodash/lang/cloneDeep'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/babel-register/lib/node.js:9:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! habitrpg@0.0.0-152 postinstall: `bower --config.interactive=false install -f; gulp build;`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitrpg@0.0.0-152 postinstall script 'bower --config.interactive=false install -f; gulp build;'.
npm ERR! This is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --config.interactive=false install -f; gulp build;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs habitrpg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log```
``````

**Comment by librarianmage** [comment]
@Alys and after installing `lodash`, I get the first error that I had. 😛

**Comment by lucubro** [comment]
Interestingly, when I install with vagrant with npm 2 (as Alys did) I get yet another error. `npm install` finishes (almost) successfully but `npm start` complains. The only difference is that I'm still on OSX 10.10.5.

```
vagrant@habitrpg:/vagrant$ npm install
npm WARN package.json Dependency 'vinyl-source-stream' exists in both dependencies and devDependencies, using 'vinyl-source-stream@^1.1.0' from dependencies
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN peerDependencies The peer dependency stream-browserify@* included from bl will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.11
npm WARN optional dep failed, continuing fsevents@1.0.11

> kerberos@0.0.3 install /vagrant/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/vagrant/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory `/vagrant/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos/build'
npm WARN deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.

> phantomjs@1.9.20 install /vagrant/node_modules/phantomjs
> node install.js

/vagrant/node_modules/phantomjs/node_modules/extract-zip/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_readable.js:121
    this.decoder 


SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/phantomjs/node_modules/extract-zip/node_modules/concat-stream/node_modules/readable-stream/readable.js:6:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> bson@0.2.2 install /vagrant/node_modules/mongoskin/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)


-
vagrant@habitrpg:/vagrant$ npm start

> habitrpg@0.0.0-152 start /vagrant
> gulp run:dev

/vagrant/node_modules/gulp/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:69
  if (stream instanceof Duplex) this.objectMode = this.objectMode || 


SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/gulp/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:29:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.3.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.3.1/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.15.3
npm ERR! code ELIFECYCLE
npm ERR! habitrpg@0.0.0-152 start: `gulp run:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitrpg@0.0.0-152 start script 'gulp run:dev'.
npm ERR! This is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp run:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs habitrpg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by librarianmage** [comment]
@Alys I searched up `Error: Cannot find module 'babel-runtime/helpers/interop-require-default'`, and found these:
https://github.com/babel/babel-loader/issues/39
https://github.com/jhabdas/react-native-webpack-starter-kit/issues/2
http://stackoverflow.com/questions/36235228/yeoman-angular-fullstack-generator-cannot-find-module-babel-runtime-helpers-i

**Comment by librarianmage** [comment]
@Alys, babel was updated (by @crookedneighbor) to v6 a month ago, but I don't think that would change anything.

**Comment by librarianmage** [comment]
Possibly useful: https://babeljs.io/docs/plugins/transform-runtime/

**Comment by librarianmage** [comment]
... And I just installed it on a new box and it worked. What. the. heck.

**Comment by Alys** [comment]
@MathWhiz Can you think of anything different between the old box and the new one that might have helped it work?

**Comment by librarianmage** [comment]
I think for a preset, I selected "Blank Template", but I think I did that
the time before.

**Comment by Alys** [comment]
I've finally had a success with this! I've got rid of all the errors like the one below just by setting up a swap file. The normal recommendation for the size of a swap file is the same as or double the amount of RAM, but I went with four time the amount of RAM because I had enough free space; however less than that might well be enough.

digitalocean provides a nice guide for adding a swap file to Ubuntu 14.04: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
For other platforms, the process might be similar but I recommend googling if you're not familiar with it.

I'm still getting problems running npm start, but I'll post more about that later.

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/lang/cloneDeep'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/alys/habitrpg/node_modules/babel-register/lib/node.js:9:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by Alys** [comment]
Wow..... Those problems I had running npm start were because I had neglected to copy config.json.example to config.json. You know what I should do? I should read [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) and work through the instructions on that page from the top. :blush: :stuck_out_tongue_winking_eye:

Anyway, I now have a working local install again, finally. 

Anyone who's having trouble, feel free to ask here for help, but I recommend first deleting your current install and starting from scratch, referring back to [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) for each step. Don't rely on any of the information you obtained from it previously because it's been changed recently. Pay particular attention to the "Important Notes" section.

**Comment by librarianmage** [comment]
@Alys ... I'm getting the errors again.

**Comment by Alys** [comment]
@MathWhiz The "Error: Cannot find module ..." errors? Does your cloud9 box have a swap file and if so how big is it and your RAM? If it doesn't have one, can you add one and try again? If that doesn't help or is irrelevant, post the full output to a [gist](https://gist.github.com) or similar.

**Comment by librarianmage** [comment]
It comes with a swap file, but only has 256 mb (I think) of memory. I have
no idea how I got it to work before

**Comment by Alys** [comment]
How big is the swap file?

Getting it working before might have been luck if the box was just performing better than usual for some reason. Increasing the swap file size might help.

**Comment by librarianmage** [comment]
@Alys I don't believe I can, but I will try

**Comment by quin-jay** [comment]
I'm also having "cannot find module" errors. My c9.io installation stopped working, so I created a fresh Ubuntu VM, created a swap file right away using the DigitalOcean link @Alys provided, and then followed the Wiki's guide on setup as closely as I could.

My swap file is 4GB, and my VM's memory is 512MB (the VirtualBox default).

(Update: Issue persists even when raising "swappiness" from 10 to 50.)
(Update 2: Issue persists even after increasing VM memory to 2GB.)

**Comment by librarianmage** [comment]
Okay, so here is a detailed walk-through of what I go through (with pictures! `such pro`):

### 1. Clone my `habitrpg` repo and set up the `upstream` remote

![image](https://cloud.githubusercontent.com/assets/12386291/14939539/1b700b02-0f11-11e6-9e29-5abd5a7e33e4.png)
c9.io allows you to automatically start a box with a cloned git repository, and it installs without a hitch

### 2. Check `node` / `npm` version

![image](https://cloud.githubusercontent.com/assets/12386291/14939581/493f4204-0f12-11e6-8b24-ae0cfa77fac7.png)

### 3. Install `gulp`, `grunt-cli`, and `bower` (mongodb is preinstalled)

![image](https://cloud.githubusercontent.com/assets/12386291/14939609/7f4863c0-0f13-11e6-88a6-1ea8f17343a6.png)
Everything seems to run fine

### 4. Check RAM / Swap File

![image](https://cloud.githubusercontent.com/assets/12386291/14939594/bb07f1e2-0f12-11e6-90b7-dc940363edf6.png)
![image](https://cloud.githubusercontent.com/assets/12386291/14939598/e447fcb4-0f12-11e6-82f1-b380a4ad125f.png)

### 5. Run `npm install`

This is where it gets interesting. The CPU and Memory skyrocket, and the machine seems to halt
![image](https://cloud.githubusercontent.com/assets/12386291/14939645/64c79190-0f15-11e6-8b15-f7bac2d55e6b.png)
And then it gets killed :frowning:

### 6. Re-run `npm install`

And I get [this](https://gist.github.com/MathWhiz/a220776121ecc9ac453795a46006167d)

**Comment by Alys** [comment]
@MathWhiz and @lynnyliz : I'm pretty sure the only problems are that there's a LOT of modules to install and any box that doesn't have enough power can't handle it (although lynnyliz's box sounds beefy enough). I've been using a server recently on which the installation process works well most of the time, but sometimes it does give the "Cannot find module" errors. When I see those, I run "npm install" again, and that fixes it - so it can't be caused by missing or broken software on the server; it's just a temporary problem that resolves itself if you're lucky. Sorry, I realise that's not very helpful.

What happens if you try running "npm install" a couple more times? Does it get any better?

**Comment by quin-jay** [comment]
@Alys It didn't (kept getting stuck on babel-runtime/helpers/interop-require, or something to that effect). HOWEVER, I deleted node_modules, ran npm install again (and then again, since it failed on phantom-js), and then after that npm start acted a little funny but everything was fine after an rs! I'm half worried I won't get this running again if I shut it down now (lol), so I'm off to get some code done right away (that rushing is also why I'm being less thorough with backticks and such -- the excitement is real!)

For some reason I'd been under the impression that I could run the server in my VM but do all my coding and testing in my host OS, but that doesn't seem to be the case. I'll experiment some -- maybe get used to programming in Ubuntu, or maybe just code in my host OS, and pull the commits into the VM (but that seems way inefficient). Either way, I'm excited to get started! Thank you so much for your help :grinning:

**Comment by Alys** [comment]
@lynnyliz Once you have the node modules installed and npm start is working, then shutting it down and restarting it should be safe. `npm start` is a pretty simple process and should just keep working (assuming your own code changes will compile). The only time you're likely to run into problems is when Habitica's code requires new or updated modules and you have to run npm install again. Even then, it's not always troublesome.

Don't rush on the code. We're coming to the point in our API rewrite where we're close to being finished and are wanting to avoid code conflicts while we test the API changes. It's possible that anything you submit now won't be able to be reviewed for a while. We would definitely look at it later though!

When I run a Vagrant VM on my Mac, I'm able to do all the file editing on the Mac, and use the Mac's browser for viewing the site. The only thing I use the VM for is hosting the database, running the webserver, compiling the Habitica code, and running the test suite. If you're on a Mac, that should definitely be possible for you too. If you're on a Windows machine, I'm grimacing and backing away slowly. :)  Feel free to ask for help with it though!

**Comment by Alys** [comment]
MathWhiz has got a local install running on a more powerful server, and it looks like @lynnyliz has it working too. 

@BrunoAssis (or anyone else) If you're still having trouble, delete the node_modules directory so that you can get a fresh start with the `npm install` commands, rebase your local install to get the latest code, compare config.json with config.json example and add any new items that are missing from config.json, and then go through the [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) instructions, making sure that your machine has a lot of swap space (there's a new section near the top of those instructions that discusses the swapfile). If you're still having trouble after that, please log a new issue with a link to a [gist](https://gist.github.com) or similar containing the full output of the installation process.
