### ISSUE TITLE
Subscription status wrong

### ISSUE THREAD

**Issue by NickyInWonderland** [HabitRPG/habitica#7092]
General Info
- UUID: 0694844a-bb8f-4bd7-9106-a5c8e95dfc7a
- Browser: Firefox
- OS: Linux Fedora 22

Hey everyone

I was gifted a 3 month subscription a month ago by my boyfriend and at first I was able to buy gems and the subscription showed up in my subscription menu, but ever since the start of the second month it's gone. I can't buy gems, no subscription is shown. What should I do? I cleared all local data but it didn't change anything. 

Here is the PN I got: 
Hello NickyInWonderland, harlequix has sent you 3 months of subscription! -vor einem Monat  
(well, since I'm german, the last thing says: - a month ago)     

Thanks a lot, Nicky

**Comment by Alys** [comment]
Hi Nicky. Just letting you know that we've seen this and we'll definitely get it sorted out for you.

**Comment by Alys** [comment]
Hi Nicky. I think I have that all fixed for you now, but please comment here if anything looks wrong, either now or at any time over the next couple of months until it expires! I'm sorry about the trouble.

I'm closing this now but we'll still see any replies you make and will help you as needed!

**Comment by NickyInWonderland** [comment]
Hello again..

everything was working fine, until the new month started. My subscription is gone again, even though it hasn't officially ended yet. And I just realized, that I haven't received the subscribers gift for April as well...

What should I do? I already tried to delete my local data again, but it didn't work.

Thanks again for your help :)

**Comment by Alys** [comment]
Sorry, Nicky. :( I've given you another three-month subscription and the missing Mystery Items (still in their gift box). Please do tell us again if anything else happens.

For admins, here's the data I've just added. Might be useful to work out where it's gone wrong, if this happens again.

```
    "purchased": {
        "plan": {
            "extraMonths": 0,
            "gemsBought": 0,
            "mysteryItems": [
                "head_mystery_201604",
                "armor_mystery_201604"
            ],
            "consecutive": {
                "count": 0,
                "offset": 0,
                "gemCapExtra": 5,
                "trinkets": 1
            },
            "paymentMethod": null,
            "planId": "basic_3mo",
            "customerId": "Gift",
            "dateUpdated": "2016-05-21T00:00:00.000Z",
            "dateCreated": "2016-05-21T00:00:00.000Z",
            "dateTerminated": "2016-08-21T00:00:00.000Z"
        }
    },
```

**Comment by NickyInWonderland** [comment]
Thanks a lot  :D  :+1:
