### ISSUE TITLE
No Rewards Upon Completion of Quest

### ISSUE THREAD

**Issue by IAlwaysWantedToBeAWizard** [HabitRPG/habitica#7093]
For the last two quests I've completed with my party, I've received no reward. I should have three falcon eggs and 10 egg basket eggs but I don't. Other members have this problem as well.

User ID: f5eac8d9-4d73-403c-b158-6efb34d737db

Group ID: 84f03be9-33d6-4a95-a12e-8623ad2721bd

Browser: Google Chrome

OS: Windows 10

**Comment by Alys** [comment]
Can you tell me the names of the other party members who have this problem? If it's all party members for both quests, you can say just that.

**Comment by NicoleNobody** [comment]
I’m the leader of the mentioned party. I didn’t receive eggs after finishing the quest either. 

My user ID is 96bad0fe-e963-43dd-b6f7-bcb73ddc4ebd

Another member that didn’t recieve anything from both quests is haralali (dd45acb4-b0f5-421f-8566-5ba9711bacb4)

**Comment by NicoleNobody** [comment]
Users maccaches (6e5c40f2-9cd3-4b61-965d-cd5d81b02176) and padfoothpcat (3ae15e79-f9d2-4a52-8486-54dc68c65e6a) didn’t receive a reward from the Egg hunt quest.

Thank you for looking into it.

**Comment by Alys** [comment]
I've given the achievement and eggs to those five players. Reload if you don't see them. Please tell me if they don't appear after that!

I'm closing this now but if you hear of more party members who didn't get the rewards, comment again here. We'll still see your reply even though this is closed.
