### ISSUE TITLE
Purchased Quest Not Showing Up in Inventory

### ISSUE THREAD

**Issue by etchling** [HabitRPG/habitica#7098]
General Info
- UUID: etchling
- Browser: Safari 9.1
- OS: OS X 10.11
### Description

I purchased "Dilatory Distress Part 3" Quest Scroll. The 400 Gold was subtracted from my character's total, and at first the scroll appeared in Inventory, but clicking it consistently resulted in a "you don't own that scroll" notification on the right side of the screen. Upon logging out and logging back in, and reloading the inventory page, the scroll icon was gone completely. So now I'm out 400 gold, but the scroll doesn't show as part of my inventory. Nor am I involved in the quest with my party.

**Comment by Alys** [comment]
So sorry about this, @etchling ! It sounds like a [sync error](http://habitrpg.wikia.com/wiki/Sync_Errors). It's unlikely to happen again so it should be safe to try to buy it again (although we're having server troubles at the moment, but once that clears up, you shouldn't have any trouble). You can get back your lost gold at on the website at Settings > Site > [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).
