### ISSUE TITLE
HabitRPG Ugrade

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#71]
After a certain amount of time or when you reach a certain level the RPG should upgrade. New armor, new weapons, new currency, etc. Maybe lvl 100 like Pokemon(yes I just went there).

**Comment by hookang** [comment]
@neohuman Not understanding this quite... would like to add to Master List of Features

**Comment by ghost** [comment]
The RPG as a whole changes after a certain level

**Comment by horusofoz** [comment]
@Neohuman If skills, classes, expanded digital items range, etc were to implemented, would you feel "Master Levels" with everything re-skinned and stats inflated would still be required? 

My thought is the re-playability that game designers are looking for with features like you're describing is to keep gamers playing. HabitRPG is meant to motivate users to complete tasks in real life. I think by the time a user reaches level 100 they would have mastered many of their desired habits and not require a re-skinning to stay motivated after achieving such results.

Another perspective is there is no beating HabitRPG. You WIN through it but you don't beat the game. If you reach level 100 your life will have changed, and no game aesthetics are going to boost that.

One last thought on this. If you, I or any other user reaches a level cap or hits a wall of repetitiveness within the game that reduces our motivation to achieve our goals, thanks to the Awesomeness of Open Source we can contribute ideas or code to Tyler to make things exciting again.

With that said, are you cool to close this ticket?

**Comment by ghost** [comment]
With that level of thoughtful input yes I am

**Comment by wc8** [comment]
Closing then.
