### ISSUE TITLE
QUESTION about task value and organic system

### ISSUE THREAD

**Issue by sgtorange** [HabitRPG/habitica#710]
does the option to set task difficulty easy/medium/hard is in addition to the organic system?
as in a red task set to hard is worth more than a red task set to medium. Or does it ignore the organic system if user set a task to easy, medium, or hard to begin with?

may be a silly question but just trying to clarify.

**Comment by wc8** [comment]
It is in addition to it, more precisely, it is a multiplier of the task's value, more info: [Multiplier](https://trello.com/c/4C8w1z5h) (currently called _difficulty_ rather than priority).

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
