### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by kasmiman** [HabitRPG/habitica#7101]
General Info
- UUID: Can't access Habit to report
- Browser: Firefox 45.0.2
- OS: Windows 7 Professional

Also:
- Browser: Safari (on iOS)
- OS: iOS 9.3.1
### Description

Get 503 error upon trying to load Habit:

```
503 Service Unavailable
No server is available to handle this request. 
```
#### Console Errors

`
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
`

**Comment by titalvi** [comment]
I've got the exact same problem. On Chromium (Version: 50.0.2661.75) as well as Firefox (Version: 45.0.2), both running on Linux Mint Debian Edition.

**Comment by Hellacio** [comment]
Same here:
Firefox 45.0.2OS X

**Comment by AlainPlusPlus** [comment]
-Firefox 45.0.2
-OS: OS X 10.9

Description: 503 Service Unavailable
No server is available to handle this request.

**Comment by Alys** [comment]
So sorry about this everyone! We're working on this as fast as we can! Please check https://github.com/HabitRPG/habitrpg/issues/6700 for updates.

**Comment by Alys** [comment]
Everyone, the site is back for us now although we're still monitoring it closely to make sure it's okay. All further updates will be in https://github.com/HabitRPG/habitrpg/issues/6700
