### ISSUE TITLE
Social-Themed Starting Tasks

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7103]
Now that both mobile apps have Guild access, we'd like to make some extra starting tasks that show up in new accounts. We hope that these will help encourage new Habiticans to become members of the community!

Alternate task and wording suggestions are very welcome!

These To-Dos should appear underneath the "Join Habitica" To-Do. The tasks on the website should be different from the ones on the mobile app, because the directions to get to the pages will be different. Of course, if the user tries both platforms the tasks will be incorrect one of them, but I am not sure there is an easy way to change that. Someone please chime in if I am wrong!

WEB

Learn about Habitica
Checklist: 
1) Read the Overview for New Users (on the top bar, under Help)
2) Read the FAQ (under Help)

Join the Newbies Guild (under Social > Guilds)
Note: This is the best place to ask questions!

Introduce yourself in the Tavern (Social > Tavern Chat)
Checklist:
1) Read the Community Guidelines
2) Post a fun fact about yourself, like a habit you want to improve or your favorite hobby!

MOBILE

Read the Habitica FAQ 
Note: Under Menu > About > Help & FAQ

Join the Newbies Guild (Menu > Social > Guilds)
Note: Ask questions here!

Introduce yourself in the Tavern (Menu > Social > Tavern Chat)
Checklist:
1) Read the Community Guidelines
2) Post a fun fact about yourself, like a habit you want to improve or your favorite hobby!

**Comment by librarianmage** [comment]
I like all the wording. How would we make sure that the mobile people see the mobile stuff and the website people see the website stuff. What would happen if they switched halfway through?

**Comment by librarianmage** [comment]
Oh, just saw that part earlier

**Comment by citrusella** [comment]
> Of course, if the user tries both platforms the tasks will be incorrect one of them, but I am not sure there is an easy way to change that. Someone please chime in if I am wrong!

Could the notes on the task contain the instructions/locations for the alternate platform? Then if someone tries but doesn't check those tasks until they're on a different platform, they still have the notes in order to know how to get there from a different platform? It's a bit imperfect, though...

**Comment by librarianmage** [comment]
Or both of the instructions could be in the notes

**Comment by librarianmage** [comment]
@lemoness @citrusella This is my idea for the planned tasks:

### Learn About Habitica

#### Notes

Overview of New Users:
💻 only: Top Bar, Under Help
FAQ:
📱: Menu > About > Help & FAQ
💻 : Top Bar, Under Help

#### Checklist
1. [ ] Read the Overview of New Users (Website only)
2. [ ] Read the FAQ

### Join the Newbies Guild

#### Notes

📱: Menu > Social > Guilds
💻: Social > Guilds
This is the best place to ask questions!

### Introduce Yourself to the Tavern

### Notes

📱: Menu > Social > Tavern Chat
💻: Social > Tavern Chat

### Checklist
1. [ ] Read the Community Guidelines
2. [ ] Post a fun fact about yourself, like a habit you want to improve or your favorite hobby!

To increase the similarities between the mobile app and the website (and to make this easier 😛), would it make sense to move the content of the "Overview of New Users" into the FAQ on the website?

**Comment by quin-jay** [comment]
Man, the instructions are so similar for almost every platform (kudos to the devs for that consistency, btw). This would be much easier if there was only an emoji that looked like the menu button.

But if we pictorally represent the menu button, it could look like so:

### Join the Newbies Guild

#### Note:

![menu-icon](http://icons.iconarchive.com/icons/icons8/windows-8/16/Very-Basic-Menu-icon.png) Social > Guilds

With the icon, app users could know that they have to press the menu button, and site users could either press that menu button in the toolbar or just click the labeled button itself, it doesn't matter for them. But it would be an unintrusive way to convey "menu" for both platforms.

How sluggish would it be to embed a small image using markdown? ~~Would doing so allow more text on the same line?~~ Edit: Should've just tried it myself the first time :stuck_out_tongue_winking_eye:

**Comment by librarianmage** [comment]
There is &#9776 (looks like ☰). Unfortunately I have no idea if it is
supported, as it is a Chinese symbol

**Comment by librarianmage** [comment]
This is because markdown (currently) is not supported on the phone apps

**Comment by librarianmage** [comment]
There is also ≡ (equivalence)

**Comment by librarianmage** [comment]
However, on the website, they use ☰ (U+2630)

**Comment by librarianmage** [comment]
On the website (last is the one currently used on the site):
![screenshot 2016-04-28 at 8 20 40 pm](https://cloud.githubusercontent.com/assets/12386291/14906265/08fc34de-0d7f-11e6-9e3b-2871b9e8c5b8.png)
On iOS:
[iOS](https://goo.gl/photos/1KPug42sPf5wEZBw8)

**Comment by quin-jay** [comment]
With the exception of the middle symbol, it looked good to me on both platforms. Was that the iOS app?

**Comment by librarianmage** [comment]
The pic is the website, the link is to ios. The last symbol is the one
currently used on the website, so that would most likely be preferable (and
if we reach a consensus, I would like to work on this)

**Comment by quin-jay** [comment]
Yeah, sounds great! I just wanted to chip in my idea about using an icon. I agree that the third symbol is preferable, too

**Comment by quin-jay** [comment]
And for the record, here's what the third symbol looks like on the Android app:

![image](https://cloud.githubusercontent.com/assets/6640915/14907320/c26a64e4-0d62-11e6-8c2c-f0c061a4eaee.png)

**Comment by librarianmage** [comment]
@lynnyliz That looks really good!

**Comment by quin-jay** [comment]
@MathWhiz Yeah I think that symbol is a great choice, it looks good on all platforms! I'm glad it can be the same tasks for everyone, I have no idea how you'd go about specifying that a task should only show up for Android or website users :hushed:

**Comment by librarianmage** [comment]
So now my plan is:

### Learn About Habitica

#### Notes

Overview of New Users:
💻 only: ☰(Menu - Top Bar) > Help
FAQ:
📱: ☰ > About > Help & FAQ
💻 : ☰ > Help > FAQ

#### Checklist
1. [ ] Read the Overview of New Users (Website only)
2. [ ] Read the FAQ

### Join the Newbies Guild

#### Notes

☰ > Social > Guilds
This is the best place to ask questions!

### Introduce Yourself to the Tavern

### Notes

☰ > Social > Tavern Chat

### Checklist
1. [ ] Read the Community Guidelines
2. [ ] Post a fun fact about yourself, like a habit you want to improve or your favorite hobby!

The only problem is the "Learn about Habitica" task, as they are similar enough to look redundant, but different enough that it could cause confusion. @lynnyliz any suggestions?

**Comment by quin-jay** [comment]
@MathWhiz hmm... Well, you tell them that they're looking for the FAQ, so theoretically they'll know to click it once they see it... What if you did ☰ > Help for both? In mobile, there's also another menu item "About" under the section heading "About", so that might get confusing and might be worth leaving off this time. 

Pros:
-succinct
-consistent across platforms
-thematically similar to how we're telling people to go join the Newbies Guild but they have to find it themselves once they get to the guild section

Cons:
-inconsistent with other directions, which DO specify the section header in the mobile menu
-potentially still confusing because of that

But short of changing the app, I can't think of anything else, really...

**Comment by librarianmage** [comment]
@lynnyliz or the website, but yeah, I think they could be made more succinct

**Comment by librarianmage** [comment]
Note to self - Default tasks are in https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content/index.js#L2721

**Comment by librarianmage** [comment]
This should probably be no longer be marked as "In Progress"

**Comment by Alys** [comment]
Hmm, good point.

@lemoness just checking: This is still desirable?

**Comment by lemoness** [comment]
We're going in a different direction now, involving achievements instead, so let's table this for now.

**Comment by librarianmage** [comment]
What is the status on this?
