### ISSUE TITLE
Party Chat/Messageboard

### ISSUE THREAD

**Issue by pheldurin** [HabitRPG/habitica#711]
It would be nice to have a message board or chat window that party members can post on, e.g. "gratz on the new armor!" or "wow I love this new habitrpg feature!"
I envision it being similar to the chat in google docs (off to the side, you can hide it, it notifies you if party members are online and active/away).

**Comment by wc8** [comment]
See [Community Forum](https://trello.com/c/V584GSSl) suggestion.

**Comment by lefnire** [comment]
This is a separate suggestion - chat within your party. It's actually a check-list item on "Parties": https://trello.com/card/parties/50e5d3684fe3a7266b0036d6/75

**Comment by wc8** [comment]
Oh yes, I missed the party focus [up too late], glad you caught that. I followed up on [Parties](https://trello.com/c/GPc3MvYv) with a few thoughts on the chat idea.

**Comment by wc8** [comment]
Closing since it's listed on Trello.
