### ISSUE TITLE
iOS app not fully displaying tags

### ISSUE THREAD

**Issue by Alex-Keyes** [HabitRPG/habitica#7112]
I've noticed that when creating a new habit the iOS app cuts off the last tag that I have. I can still click on it via scolding up but if I do not do that then it is not visible ![photo of the bug](http://i.imgur.com/lkJAlOM.jpg)

**Comment by Alys** [comment]
Issue moved to [HabitRPG/habitrpg-ios #363](https://github.com/HabitRPG/habitrpg-ios/issues/363) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by Alys** [comment]
@Alex-Keyes Can you please go to the new location for this issue (https://github.com/HabitRPG/habitrpg-ios/issues/363 ) and click the subscribe button in the right-hand column? That will allow the iOS developers' comments to reach you by email, which could be important if they need to ask you questions about this.

Thanks for reporting it! If you find any other bugs in iOS, there's a quick link to the iOS repo from the Habitica website's Help > Report a Bug instructions

**Comment by Alex-Keyes** [comment]
@Alys Sounds great! I wasn't sure where exactly iOS issues were supposed to go.  Thanks for the heads up!
