### ISSUE TITLE
Can't leave guilds

### ISSUE THREAD

**Issue by horatio5000** [HabitRPG/habitica#7114]
General Info
- UUID: f852bc5b-9473-4142-8666-52029bee1e21
- Browser:   Safari
- OS:   10.8.5
### Description

Hello! This is a similar issue to #6279, but I can't leave guilds. When I click leave, nothing happens. I can join guilds OK.
I created another account on the website and I can join and leave guilds perfectly fine on that one. It just seems to be my account - I have done some recommended things like trying a different browser, clear local data etc.   I don't want to leave my party but that might not be working too.  I would like to leave all of my guilds.

Thanks for your help.

**Comment by Alys** [comment]
@horatio5000 We'll need your User ID (UUID) before we can help with this. Please add it to a new comment here (we won't be notified if you edit it into your original post).

**Comment by horatio5000** [comment]
Ah, sorry about that!   It's:    f852bc5b-9473-4142-8666-52029bee1e21

**Comment by Kristyjnh** [comment]
I have the same problem. I'll see the little blue loading bar but nothing else will happen. UUID: 4ee77f18-6288-4f57-9c46-b8fe8cbc7357

**Comment by Alys** [comment]
@horatio5000 and @Kristyjnh  I've removed you from all your guilds, but not from your party.

Comment here if you have more problems.

**Comment by horatio5000** [comment]
Thank you! But i have another problem.  It's that I can't thank you enough!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Alys** [comment]
@horatio5000 Awww! Thank you! :) :)
