### ISSUE TITLE
Facebook Login Error

### ISSUE THREAD

**Issue by teafunnyc** [HabitRPG/habitica#7118]
General Info
- UUID: 
- Browser: Chrome
- OS: Mac
### Description

Logging in via Facebook on Chrome. Clicking on the login via facebook button, a popup comes up but immediately closes back to the static front page. The blue progress bar on the top fills when I click "Play Habitica" again but freezes right before it reaches the right side of the window.

**Comment by Alys** [comment]
Please delete all habitica.com cookies from your browser (or just delete ALL cookies that your browser has, if that's easier). Then go to https://habitica.com/static/clear-browser-data and click the redebutton you'll see there.

Can you now log in?

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see the advice from my previous post, and let us know whether that worked or not. We'll still see your reply and can reopen this if necessary.
