### ISSUE TITLE
emojis have no colour in windows browser

### ISSUE THREAD

**Issue by Vampitch** [HabitRPG/habitica#7119]
UUID: 0e28c7af-59e6-4f0a-bc86-ae3356502211
Browser: Chrome 50.0.2661.87
OS: Windows 8

Maybe somebody is working on this but I couldn't find it in the other issues.

I use emojis to colour code my dailies, to-dos and habits. So this is very important for me. It was fine until yesterday. Today the emojis are greyed out. The same thing happens when I post in party chat for instance, they are still grey. This affects all emojis (as far as I can see).

Emojis in the rewards section are working fine however.

Got a friend to check their account, same thing happening.

I use Chrome on Windows. I checked Internet Explorer, also grey. 
Safari and Chrome on Mac are working fine. 
I used a different Windows pc, Chrome and Firefox, which are also grey. 

Also I just noticed if I post emojis using the emoji cheet sheet code in Windows, it's working. But if I use an iOS phone to do it (like I used to for the past four months or so), the emojis are grey when viewing from a Windows browser.

Any help is appreciated. Thanks!

**Comment by crookedneighbor** [comment]
Thanks for reporting this. I'm working on it.

**Comment by ghost** [comment]
@crookedneighbor I don't know if it's related (maybe not), but not to create a new issue:

`:watch:` is now converted to `function(watch) {[native code]}` for me in FF for win

I believe it may have got broken after the recent markdown changes

Please excuse me, if I'm reporting it to the wrong ticket

![scr](https://i.snag.gy/0tywIn.jpg)

**Comment by GitHubSphinx** [comment]
Screenshot added
![scr](https://i.snag.gy/0tywIn.jpg)

**Comment by crookedneighbor** [comment]
@GitHubSphinx I'm able to reproduce this on firefox on a mac and I'm working on a fix. I'm curious why we haven't got more reports...

**Comment by GitHubSphinx** [comment]
I'm the only one who uses :watch: emoji for my brick-laying activities?

**Comment by crookedneighbor** [comment]
Both issues will be fixed on the next deploy.

@Vampitch https://github.com/HabitRPG/habitica-markdown/commit/6207fc32f117512a17a275dd5b7e1dd166fc0f74
@GitHubSphinx https://github.com/HabitRPG/habitica-markdown/commit/eaf59b35d456196b589dd9b84a2b2e85919c5485
