### ISSUE TITLE
Did not receive pet and mount after world boss

### ISSUE THREAD

**Issue by Megabjarne** [HabitRPG/habitica#7120]
General Info
- UUID: e9095b54-f079-4ca1-9348-bbdffe9e689e
- Browser: Chrome V.49.0.2623.112
- OS: Windows 7
### Description

After the defeat of Be-Wilder, i did receive the defeat-notification, and i received all of the items, except the pet and mount, all the foods was accounted for.

**Comment by Vampitch** [comment]
This was being talked about in the Tavern, and the majority have not received their bee pets and mounts yet. Lemoness said it just takes a while for the pets and mounts to be given out to everybody. I quote 

> Everyone! If your own fuzzy magical bee pet and mount are a little slow to arrive, never fear -- they are merely stopping to smell the roses wink There are lots of intrepid Habiticans to reward, so it can take a while to roll them out, but the migration is slowly running and giving a bee to every Habitican. Be patient, and they will come bumbling up soon smiley

**Comment by lemoness** [comment]
Yes, the migration just goes very slowly. Everyone should have their bee pets and mounts now! If you're on Android and still don't see them, you'll need to do a content refresh. The easiest way to do this is to go to the Rewards page and reload. I'm going to close this issue now, but feel free to ask more questions if you have any!
