### ISSUE TITLE
Haven't received red hatching potion despite having received 43 total other hatching potion drops

### ISSUE THREAD

**Issue by joeysilva** [HabitRPG/habitica#7122]
General Info
- UUID: 4d444b75-982b-420c-8f30-3415d560fd34
- Browser: Chrome
- OS: Linux and Mac
### Description

I've received a total of 43 hatching potions from random drops, but not a single one of them has been a red hatching potion. I'm not sure if you have a way of verifying if this is just bad luck or not; I computed the odds of this situation to be (9/10)^43 = 1%, so it's not crazy I guess, but still...

**Comment by Alys** [comment]
It's just bad luck. There's no code other than the random generator that controls which drops you get. Habitica has over a million user accounts, so something that happens with a chance of 1% can be expected to happen to several thousand players. You're one of those players at the moment, but in future you'll get red potions.
