### ISSUE TITLE
Idea: Rebrand Generation 1 Pets as "Wild"

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7125]
I know there has been talk of what to call the "original" 90 Generation 1 pets, since new players have no context that those used to be the only ones you could get. What if we called those pets "Wild"? My thoughts on how this would fit into Habitica conceptually and logistically:

Conceptually:
- If the pets are "wild", then egg drops hearken back to "random encounters" in other RPGs ("A wild Pikachu appeared!" as you're running through grass)
- Quest pets are less abundant in the "nearby environment", which is why you must set out on a quest to find them

Logistically:
- The Generation 1 pets and mounts get a new heading over them to identify what they are specifically
- "Beastmaster Progress: xx/90 Wild Pets [Found/Caught/Tamed]" -- Will now be abundantly clear which pets count for the achievement
- I'm also thinking "Mountmaster Progress: xx/90 Wild Pets Raised" -- Besides this one box that says "tamed", everywhere else seems to talk about "raising" pets to mounts (we're also feeding them, not training them)
- Achievement text itself would also be updated

My c9.io installation should be in good enough shape for me to get started on this, once I get a go-ahead. In the meantime, I'm happy to discuss and refine this idea. Any thoughts?

**Comment by librarianmage** [comment]
You may also want to suggest this in the [Trello](https://trello.com/c/odmhIqyW/440-read-first-table-of-contents).

**Comment by quin-jay** [comment]
Well I first broached this idea in the Aspiring Coders guild chat, and Alys suggested that Github would be a better setting for discussion -- she didn't mention Trello. I tend to agree with her; this isn't a new feature, it's a discussion about changes to make to specific, existing code. 

That said, if more people think Trello is the best setting for it after all, I'm happy to post there too.

**Comment by librarianmage** [comment]
@lynnyliz Now that you talk about it that way, that makes more sense! `Retracts previous statement`

**Comment by crookedneighbor** [comment]
I think labelling them as "wild" is a great idea.

**Comment by librarianmage** [comment]
@crookedneighbor @lynnyliz Related to some of the strings you will be changing: #4445

**Comment by quin-jay** [comment]
Thanks for the link, @MathWhiz! The issue in the reference above (6685) also deals with achievement text strings. I think that 6685 and 4445 combined will have enough alterations to make a full PR, so if we don't decide either of those right away I think it'll be fine. This one also seems important enough to do without waiting for the others -- the Beast Master progress box is pretty confusing without the specification of which pets count.

@crookedneighbor and @Alys (in guild chat) both gave me an OK, so I'm gonna get to work! I'll leave the issue open for further discussion in the meantime.

**Comment by Alys** [comment]
I'm definitely in favour of this. The only problem I can see is that when terms are gamified, some users have a lot of trouble understanding them, and "Wild" will probably be one of those cases, but I love the term and think it works and we should use it. We can minimise confusion by having a small sentence on the Pets and Mounts pages explaining what "Wild" means. Something vaguely like "These are the pets you get from dropped eggs and potions" (but better worded than that).

This is also a great opportunity to add a bit more text to explain that pets can be fed to make mounts and that they have food preferences, with a link to http://habitica.wikia.com/wiki/Food for those who want to learn the preferences immediately. For the Magic Potion pets, the text can say outright that the pets like all foods.

**Comment by quin-jay** [comment]
@Alys Oh, right, I meant to also suggest how to explain the terminology! What if we updated the tutorial that pops up when you unlock drops*? I can't find the proper file at the moment, but I think Justin already pops up to explain that eggs drop, right? 

I do love your idea to have small sentences on the Pets and Mounts pages explaining how you get each kind of pet. And I envision the link to the wiki page as floating above the food drawer, so people can take their time deciding whether to click it.

*Example:

> You've found a wild Wolf egg! As you complete tasks, you'll often find wild eggs, and potions you can use to hatch them. Collect all 90 wild pets to earn the Beast Master achievement!

**Comment by Alys** [comment]
The've been rebranded as Standard.
