### ISSUE TITLE
Mana cap not accurately reflecting allocated intelligence

### ISSUE THREAD

**Issue by humanehero** [HabitRPG/habitica#7127]
General Info
- UUID: 71fa11e9-592f-45c0-9995-f05822c255a2
- Browser: Google Chrome 49.0.2623.112 m
- OS: Windows 10
### Description

Prior to today, I had 2 points allocated to intelligence and a mana cap of 50. I recall adding points to INT and seeing my cap go up. I added another point to INT today and my cap went up to 52. With 3 points allocated, my cap should be 56, right?

![habitica mana cap](https://cloud.githubusercontent.com/assets/18725980/14898020/b17bb1ca-0d52-11e6-9967-4bd94e1035f5.png)

**Comment by citrusella** [comment]
Did you take off a piece of clothing that granted intelligence points? Is it possible you could have had a buff to your intelligence yesterday that you don't have today? Your maximum MP should be 2 times your intelligence at any given time, plus 30.

**Comment by Alys** [comment]
Your maximum mana depends on your entire current Intelligence, not just on allocated points. The formula for it is on the wiki's [Mana Points](http://habitica.wikia.com/wiki/Mana_Points) page  --- and exactly as I was typing that, @citrusella ninja'ed me with the formula. :)

I can see from your profile that your current INT is 11 (level: 8, allocated: 3), so a max of 52 is correct. 

I'm closing this now, but if you notice it being incorrect, based on the formula, please comment here again and include a screenshot that shows your total attributes as well. You're also welcome to comment now if you have questions.
