### ISSUE TITLE
I can not be invited to party

### ISSUE THREAD

**Issue by janepernille** [HabitRPG/habitica#713]
I was invited to a party before I had enabled the party function. Now I have enabled party, but I can't find the invite, and the inviter can't invite me again. 

Dum di dah!

**Comment by lefnire** [comment]
[shoot me](mailto:tylerrenelle@gmail.com) your user id, parties are experiencing some issues - so i'll dig

**Comment by janepernille** [comment]
cbab9282-8989-4ca4-a4c2-3f3e66252b6d

User id ;)

**Comment by lefnire** [comment]
So when you go to User -> Party, it shows the "create new party" dialog?

**Comment by janepernille** [comment]
Yes

After I activated the partyfunction, it now does

**Comment by lefnire** [comment]
Ok, I zero'd your party property - can you try having the person invite you
again?

**Comment by janepernille** [comment]
WOHOOOO!

I'm officially in a party ^^

Thank you!

Sincerely,
Jane

p.s. I accidentally logged out and in after you sent that last message. I
didn' try to log out and in after the invitation was sent and I didn't get
the invite. Perhaps you want to try to check that out.

And the name of the party didn't show up on the invite - it actually
doesn't show anywhere :P

Just thought I should let you know.

Great game though! :D

**Comment by lefnire** [comment]
Oh dear. Party bugs galore! Well, glad you're in :)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
