### ISSUE TITLE
Fix Character Values labels are confusing on small screens

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7130]
In the Settings > Site > Fix Character Values screen, the labels are currently on the right of the fields, and when the screen is viewed in a small window (e.g., a phone), the labels drop down to the next line and it's easy to become confused about which field is which:

![screen shot 2016-04-30 at 9 26 15 am](https://cloud.githubusercontent.com/assets/1495809/14932163/ab553ec4-0eb5-11e6-8ca9-6a45d697cbda.png)

The simplest solution would probably be to move the labels to the left of the fields. I think that's a more standard location for them anyway.

**Comment by ghost** [comment]
Thank you so much for reporting it! I've been thinking about it for quite some time already. 

May I add another modal which doesn't look nice for me...

> moved to #7132

@Alys would you rather like me to create new ticket for these issues?

**Comment by Alys** [comment]
@GitHubSphinx A new issue would be best. Thank you!

**Comment by GitHubSphinx** [comment]
@Alys sorry, that wasn't meant as an attempt to high-jack your ticket. Moving my comment to another one.

**Comment by librarianmage** [comment]
I can do this (will have to wait until my box works, though)
