### ISSUE TITLE
The death modal looks messy on small screens

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7132]
The [death modal](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/death.jade) looks messy for me both on Opera for Android and FF for win - when viewed with small window width

Screenshot is taken in Russian to show all the issues:
![scr](https://i.snag.gy/r35xN4.jpg)
- image and text look misplaced
- dontDespair heading overlaps the image
- the button with refillHealthTryAgain caption needs wrapping (e.g. using the class introduced with https://github.com/HabitRPG/habitrpg/pull/5586 )

**Comment by librarianmage** [comment]
@Alys I can do this!
