### ISSUE TITLE
Flower not appearing on avatar transformed with shiny seed; unsure if this is intended behavior

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7133]
General Info
- UUID: 
- Browser: Firefox
- OS: Windows 7 (via Bootcamp on a Macbook Pro)
### Description

Didn't include my UUID because it's apparently happening to everyone (according to discussion in the Tavern), but the hair flowers aren't appearing on flower-transformed avatars. I didn't know if this was an intended change (especially since the wiki still mentions flowers as being the only things flowers can wear), so I figured I'd log it.

![image of avatar customization; the flower in the avatar is wearing a red flower but it is not displaying on the avatar](https://cloud.githubusercontent.com/assets/14182450/14939440/fef20346-0f14-11e6-9e8e-a871363db081.png)

Expected behavior is outlined here: http://habitica.wikia.com/wiki/Transformation_Items#Shiny_Seed

I could understand this being something it's not worth it to "fix" (if it's actually unintended), but I figured I'd bring it up.
#### Console Errors

None.

**Comment by Alys** [comment]
The new behaviour is more consistent from a coding point of view (the avatar transformation buffs are meant to override everything on the avatar), and it probably came about when the code was refactored (i.e., the original behaviour might have been a bug) but I'd really like to see the original behaviour brought back if it can be done without too much unpleasant code. When the Shiny Seeds were first introduced, there were several amused comments in the Tavern about the flower-on-flower effect, and it adds a little bit of extra adorable quirkiness to Habitica.

However nothing should be done about this until API v3 is released to avoid code conflicts. I'm marking this as "wait".

![flower](http://vignette1.wikia.nocookie.net/habitrpg/images/3/39/Rogue-0.png/revision/latest?cb=20150401092851)

**Comment by librarianmage** [comment]
Would I be able to work on it now?

**Comment by Alys** [comment]
@lemoness Is it okay if this is changed to put back the adorable winking flower effect? :)

**Comment by lemoness** [comment]
Yes :)

**Comment by Alys** [comment]
@MathWhiz Feel free to start if you still wish to!

**Comment by librarianmage** [comment]
Ok! (I already did it ;) )
