### ISSUE TITLE
No Contributor's License Agreement for Transifex Team

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7137]
Discussing a way to put an extra comment somewhere on Transifex regarding styling (and maybe give extra link to the Guidance) we've noticed that Habitica Contributors team on Transifex doesn't have Contributor license agreement ([wikipedia explanation](https://en.wikipedia.org/wiki/Contributor_License_Agreement)). Looking into the question, I'd like to point out the following aspect - for what it's worth, as I'm not an expert in legal things in any way.

It may seem that Habitica's [Terms of Use](https://habitica.com/static/terms) somehow don't mention that the "Public User Content" (translations in this case) can be uploaded, transmitted or submitted _not_ via the Services (not via "HabitRPG Applications and Sites" but via a third party's service - e.g. Transifex).

I believe, contributor license agreement (CLA) can be used on Transifex to make extra connections to the Terms of Use, Community Guidelines and Guidance for Linguists.

CLA is shown before contributor joins the team. For example it looks like this for another third-party project:
![pic](http://i.snag.gy/XaJAb.jpg)

E.g. it may be something like this (Transifex doesn't make links clickable as of now):

> Habitica translations comply with the Terms of Use (https://habitica.com/static/terms) with the source text for translation representing HabitRPG Content and translated text being Public User Content. The members of the Habitica Contributors team are to respect the Community Guidelines (https://habitica.com/static/community-guidelines) and follow the Guidance for Linguists (http://habitica.wikia.com/wiki/Guidance_for_Linguists)

[translations] [suggestion-discussion]

**Comment by Alys** [comment]
pinging @veeeeeee (redphoenix)

**Comment by veeeeeee** [comment]
Duly noted. It might take me a bit to get to this, but yes, it's necessary.

**Comment by librarianmage** [comment]
@veeeeeee What is the status on this?

**Comment by lemoness** [comment]
Vicky is currently quite swamped with other projects, but it's still on the list!

**Comment by lemoness** [comment]
This is on our internal list, but doesn't need to stay open as a GH ticket, because we use that more for bugs + things that require coding, so I'm closing this for now.
