### ISSUE TITLE
Stuck quest invite

### ISSUE THREAD

**Issue by switchchan** [HabitRPG/habitica#7138]
General Info
- UUID: 03c6c12c-3ae8-4c4b-bded-d8c326517c95
- Browser: Firefox 45.0.2
- OS: Windows 8.1
### Description

Almost the same issue as: https://github.com/HabitRPG/habitrpg/issues/6880
Left a party, joined another one. Now I'm getting a quest invite every time I visit Habitica, and no matter what I click, it reappears the next time I visit the page.
Tried logging out, cleaning cache etc. Could not find a solution on my end.

**Comment by Alys** [comment]
I've remove the quest invitation from your account. If you're still seeing it, please reload the site.

I'm closing this now but if you have more problems, comment again here. We'll still see your reply even though this is closed.
