### ISSUE TITLE
Checking off a daily via the API provides rewards TWICE

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#714]
When completing a daily via the API, rewards are given twice. This may also apply to TODOs (untested).  As far as I know, checking off a daily should only give a single reward.

Steps to reproduce:
1. Make a daily item through whatever means you like.
2. Leave your browser open on the HabitRPG website.
3. Mark the task done using the `/user/tasks/:id/up` route. (`hrpg + taskname` if using http://github.com/pjf/WebService-HabitRPG )
4. Observe the XP/GP dialogs appear _twice_ (presumably once for scoring the task, and once for checking it off). Also note that the XP and GP gain is twice what you'd see if checking off a task via the web.

**Comment by switz** [comment]
This is definitely plausible. I'll look into it today, thanks for bring it it up.

**Comment by switz** [comment]
I've reproduced this bug. It's scoring on the checkbox check, along with the `score` call. I'll push up a fix soon. Thanks @pjf

**Comment by switz** [comment]
Gonna wait for @lefnire to pair up on this one. This has to do with our batch updates. Sorry for the issue.

**Comment by wfjackson3** [comment]
I am seeing two potentially related bugs just testing out some TODO middleware I am writing.

First:
Create todo via API call, give it a value of 1 (not sure why that isn't default behavior).
Complete said todo via webapp.
Appears to double count the gold, giving 1g 97s.

Second:
Create todo via API call, give it a value of 1.
Complete said todo via API PUT
Observe that you get a positive XP/gold event, followed by an equal negative XP/gold event for a net zero in both.

**Comment by pjf** [comment]
I don't think I've seen this behaviour recently, but I haven't gone out of my way to check. Has this been resolved?  (Ulterior motive: I get XP for closing issues.)

**Comment by wfjackson3** [comment]
I haven't been using the API because of this bug, so I have no idea if it is fixed or not. I should have time to check it in a week or so if nobody gets to it again before that.

**Comment by wizonesolutions** [comment]
I'm pretty sure this was fixed. I remember seeing it but not actually
_getting_ the rewards twice, so I've ignored it since.

**Comment by pjf** [comment]
I can no longer reproduce the bug, and the API (via the hrpg cmdline client) is my primary way of interactive with HabitRPG.

I'm marking this as closed, but feel free to re-open if you are able to spot it in the wild. :)
