### ISSUE TITLE
Subscribed and got a gift in my inventory but when I click it is says empty

### ISSUE THREAD

**Issue by PuzzleTheDragon** [HabitRPG/habitica#7143]
General Info
- UUID: ed3b794e-4188-45d6-9380-eb540063d87b
- Browser: Opera
- OS: Windows 10
### Description

Subscribed today and got a present in my inventory when I click it it says empty and there is a little 0 in the corner of the present
![image](https://cloud.githubusercontent.com/assets/19199148/15035397/1a8a80a8-1247-11e6-8abb-e7095ed179fd.png)

**Comment by Alys** [comment]
That's expected. The Mystery Items are usually released about one week before the end of the month. The box is empty until then. If you hover over the gift box, you'll see a brief message about that, but if you'd like more information, the wiki's [Mystery Item](http://habitica.wikia.com/wiki/Mystery_Item) page has details.
