### ISSUE TITLE
Not recieving awards of a quest

### ISSUE THREAD

**Issue by luhm** [HabitRPG/habitica#7147]
General Info
  UUID: 551e07b9-9c6b-4d59-835a-bba077de6911
Browser: Chrome
OS: Windows 7
### Description

I completed a quest with a group and I haven't recieved the rewards, despite another quest started. The Quest I finished was the "The Moonstone Chain, Part 1: The Moonstone Chain Quest". It started around 29th april.
There's another member that experienced the same issue, but I do not have their information.

**Comment by Alys** [comment]
@luhm Sorry about that!  I can give the quest rewards to you and the other party member. Can you please click on their name in party chat or in the list of party members to see their profile and tell me what their User ID is? You'll see the User ID near the top right of their profile.

**Comment by luhm** [comment]
Sure!
user @small_ginger_pirate
User ID: d11b15cd-1fca-4831-9fc1-420cd36a7f47

**Comment by Alys** [comment]
Thanks luhm! 
I've given the achievement and rewards to both of you. Reload if you don't see them. Please post again here if they don't appear after that!

**Comment by luhm** [comment]
Hey, I know it have been closed, but another member said he haven't recieved the rewards too.

User ID: 5dac9a81-e0b8-4190-88b3-69bce26aa9f0

**Comment by Alys** [comment]
@luhm No worries; replying to a closed issue is correct if you're experiencing the same problem! I've given the achievement and rewards to that player.
