### ISSUE TITLE
I can't delete an old task/challenge?

### ISSUE THREAD

**Issue by BlueeCookie** [HabitRPG/habitica#7149]
General Info
- UUID: a96ff047-9d73-4e62-add2-741aeee2a454
- Browser: Chrome
- OS: Windows 10
### Description

[//](#): # I haven't been on in a while, but I know that I should be able to delete this challenge/task? It's not showing up in my participating challenges, and I haven't gotten a notification saying that it's been broken/deleted... When I click on the challenge icon nothing happens?

!["image"](https://i.gyazo.com/cb5626128780bac278b64b7e458ec2ed.png)

**Comment by Alys** [comment]
This is an example of this bug: https://github.com/HabitRPG/habitrpg/issues/2763

Please see the steps listed in "Deleting a Challenge Task" on the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges) page. Let us know how that goes!

**Comment by Alys** [comment]
@BlueeCookie I'm closing this now but if you'd need more help, let us know how those steps from the Challenges page went. You can comment here and we'll still see your reply and can reopen this if necessary.
