### ISSUE TITLE
Cannot join a challenge

### ISSUE THREAD

**Issue by Cl0udyy** [HabitRPG/habitica#7150]
Hi guys,

I can't seem to be able to join the challenge 'First Years' from the guild Hogwarts School of Witchcraft and Wizardry (https://habitica.com/#/options/groups/challenges/338b0609-2ccf-4cb3-84ae-15cfc789b094) as it keeps loading once I've pressed the button to do so. I've already contacted the admin and they want me to write a bug report so here I am. 

Does anyone know what to do?

![capture d ecran 2016-05-07 a 12 30 32](https://cloud.githubusercontent.com/assets/19237566/15091684/cddd3e9c-1450-11e6-8620-3c2814fb0d91.png)

**Comment by Alys** [comment]
Please see this bug report: https://github.com/HabitRPG/habitrpg/issues/1471
The only part you need to read is the section in bold at the top under the heading "What to do if you see "request entity too large" from any action involving a challenge or a guild" (even if you haven't seen  that exact error message, that section in bold should help). Comment here if you still need help!

**Comment by Cl0udyy** [comment]
Thank you so much for your help, it works now!

Sorry I didn't take time to go through the other topics to find the solution.

**Comment by Alys** [comment]
No worries, and thanks for letting us know!
