### ISSUE TITLE
Max mana fluctuation

### ISSUE THREAD

**Issue by NicCHab** [HabitRPG/habitica#7151]
General Info
- UUID: 8cfa1365-9d42-4dfe-b4e0-480cc6fcc0ac
- Browser: Firefox
- OS: Windows 7

The upper limit of my mana bar keeps switching back and forth between 88 and 126 (so right now I have 87/88 in the mana bar, but last night I had 70/126). It does this maybe once or twice a day, but not on any pattern I can see.

At first I thought maybe it had something to do with whether I'd completed all my dailies or not, but the wiki indicates that this should only affect the level of available mana, not the max amount I can possibly have. Am I missing something in the FAQ, or is this a bug?

**Comment by crookedneighbor** [comment]
It is related to doing all your dailies. When to complete all of them, it gives you a stat boost for the next day, which includes intelligence, which determines how much mana you have.

**Comment by NicCHab** [comment]
Understood; thanks very much!
