### ISSUE TITLE
What format is history timestamps in via the API?

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#716]
History data that comes back via the API seems a little odd. For example, check out the date here (from a fragment generated with `hrng dump` and from a regular habit goal):

```
 {                                       
    'value' => 1,                                                                               
    'date' => '1363662300012'                                                                           
  },
```

That's not seconds from the epoch, unless we're _way_ in the future:

```
perl -E'say scalar localtime(1363662300012)'
Mon Sep 27 21:20:12 45182
```

However if we chop it down to the first 10 characters, it _is_ a valid time:

```
perl -E'say scalar localtime(substr(1363662300012,0,10))'
Tue Mar 19 14:05:00 2013
```

So, what are those extra digits? Are we reporting with microsecond precision?

Suggested solution: Only report seconds from the epoch, or include a decimal point if reporting sub-second history data.

**Comment by lefnire** [comment]
Likely a bug, that's just +new Date

**Comment by paglias** [comment]
13 digit it javascript Date format, milliseconds since January 1, 1970
