### ISSUE TITLE
[API v3] Old API page should be moved to new url and renamed with info for v3

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7162]

**Comment by ghost** [comment]
@paglias will there be any additional info on this task in the future?

added:
e.g. "the new url"?

added:
Never mind, I guess it'll be in https://github.com/HabitRPG/habitrpg/issues/7348

**Comment by GitHubSphinx** [comment]
e.g. "the new url"?

**Comment by GitHubSphinx** [comment]
Never mind, I guess it'll be in https://github.com/HabitRPG/habitrpg/issues/7348

**Comment by paglias** [comment]
@GitHubSphinx if you go to v3.habitica.com in 15 minutes there'll be some new links in the footer under "Developers" (below Community). They may change before the release though
