### ISSUE TITLE
RFC: Allow (specially flagged) resettable accounts via the API

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#717]
One of the gotchas when working with APIs is testing them, both from a producer and a consumer standpoint. I'd love to expand the test suite of WebService::HabitRPG to do all sorts of things and make sure we see consistent results, but that either requires lots of mocking (which I should do anyway), or a live account. And resetting live accounts isn't exactly easy.

So, two possible ideas here are to implement some sort of transaction based system. We can begin a transaction with the API at the start, do a bunch of things, and then either rollback/commit it at the end. I _don't_ think that's a great idea, because I think we want our API to be stateless, but maybe it's useful.  (Maybe it's the basis of some sort of 'save point'?)

What I _do_ think is handy is if an account can be set as 'resettable' (not something that you'd see on a user account), and a /reset path returns it to some pristine state.  Dying may already do this, I'm not sure, as I haven't died yet.  This means I can have test suites which reset an account, perform a bunch of actions, and make sure they return the desired results.

The reason one wants the 'resettable' flag only on test accounts is because we don't want API accidents where someone zorches their real account. That would totally suck!

In any case, this is an RFC, so thoughts and ideas definitely appreciated. :)

**Comment by StanLindsey** [comment]
Settings > Reset account. 

=D

**Comment by pjf** [comment]
@SlappyBag : Perfect! Now, is that something I can call via the API?  `make test` shouldn't require touching a web browser.  ;)

**Comment by lefnire** [comment]
cool beans, will definitely add this API bit down the pike. I'll mark as "important | API", but heads up that we'll probably not be getting to some of the edge-case API bits until the future. Our hands our full at present to fulfill the [kickstarter promises](http://www.kickstarter.com/projects/lefnire/habitrpg-mobile). good to have these tickets handy though, so keep them coming - and if you ever start feeling cozy in coffee, we're PR-merging junkies 'round here :)

**Comment by pjf** [comment]
No probs, and congrats on the successful kickstarter. :)

**Comment by paglias** [comment]
I think this is actually possible via the api, closing, reopen just in case!

**Comment by lefnire** [comment]
ah yes, sorry forgot to mention this @pfj . we have a whole bunch of new API routes. I didn't want to publicize just yet since they're still in flux. Our near-term goals are to get everything to follow proper REST paradigms (we were kinda newbies shooting from the hip when we first wrote the API), and to play nicely with ngResource in our mobile & web apps. Once that's panned out, we'll re-document the API and send out a notif to all the consumers
