### ISSUE TITLE
enchanted armoire issues

### ISSUE THREAD

**Issue by larewenevenstar** [HabitRPG/habitica#7175]
- Browser: safari
- OS: os x (10.11.4)

Description
since the announcement of the new enchanted armoire items, i've not been able to get any of the new sets from it. i've not had this problem previous months. when i open the armoire i get either just experience or food from it, but never the new items. i checked my equipment and i don't see any of them there, so it's not just that i missed a notification. 
anyone else having problems with  this?

**Comment by Alys** [comment]
To investigate this, we need to be able to look at your account, so we need your User ID. To find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by larewenevenstar** [comment]
here's my user ID: da975ccc-2fd2-4e97-9da8-cfcc269c008b
sorry i didn't include it before, i only noticed the bit about the API and didn't want to include it for obvious reasons. ^^

**Comment by Alys** [comment]
@larewenevenstar You have all of the Armoire's items, including the ones from this month.

Sometimes the Armoire reports a different item than it actually gives you (to avoid that happening, sync before using the Armoire, and allow the automatic sync to finish after each Armoire purchase before you make another one). I think it's likely that that's what happened when you were given the new items. You can see what the latest items look like in the wiki's [Enchanted Armoire](http://habitica.wikia.com/wiki/Enchanted_Armoire) page (search for "graduate set" and "flowers"). 

If you still can't see them on your Equipment page on the website, show us a screenshot of the Armoire section of that page. To add the image to this issue, visit the issue in a browser and drag the image into a new comment; attaching it to an email won't work.

**Comment by larewenevenstar** [comment]
they seem to have appeared now, they were there when i last checked,
thanks for your help, sorry to bother you! you can go ahead and close this now if you want ^^
