### ISSUE TITLE
Activate or remove skipped tests in server code

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7178]
We have a lot of skipped tests in the server side code, they should be activated or removed

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by paglias** [comment]
yes

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by Alys** [comment]
@TheHollidayInn is making this kind of fix part of his regular routine so I'm closing this.
