### ISSUE TITLE
[API v3] Rename website/src and website/public to /website/server and website/client

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7179]
Something I've been wanting to do for a long time :)

@SabreCat @Alys @crookedneighbor what do you think?

**Comment by SabreCat** [comment]
Definitely more readable that way!

**Comment by crookedneighbor** [comment]
Do it.

**Comment by paglias** [comment]
Will do after client is merged

**Comment by Alys** [comment]
Awesome idea. Much easier to understand.
