### ISSUE TITLE
different fonts for different languages

### ISSUE THREAD

**Issue by hjalmberi** [HabitRPG/habitica#718]
The picture says it all:
![2013-03-25_063018](https://f.cloud.github.com/assets/3543515/296367/18a21ffe-94f4-11e2-96ce-1d2859f78954.png)

For me it would be perfect to be able to choose the font for English that doesn't require anti-aliasing to be turned on, the current one looks a bit blurry.
##

**Comment by crookedneighbor** [comment]
@Hjalmberi Is this still an issue? Tried out a few languages and it all looked fine to me.

**Comment by paglias** [comment]
The problem is for non latin charachters which are not supported by [Lato](https://www.google.com/fonts/specimen/Lato#charset) and so use system font

**Comment by KORraNpl** [comment]
Can we use latin-ext subset of Lato font? This should resolve some issues with fonts, e.g. polish letters like "ą", "ź" etc.

**Comment by ghost** [comment]
@Hjalmberi Thanks for your suggestion!
FYI https://github.com/HabitRPG/habitrpg/issues/2956 reports the same issue with another suggestion - why not have cyrillic with the same font? Or is it just the case that you'd prefer another font? I believe you might try Stylish browser extension to override the fonts.

@crookedneighbor yes, it's still an issue. We are looking forward to hearing from Lato dev team till the summer ends =) 

@KORraNpl I've seen some examples explaining how to use your own fonts on a site alongside with google fonts, but I believe in Lato devs - to keep their promises =) At the same time twardoch hasn't specified the year of that summer

**Comment by lemoness** [comment]
Did we ever hear back from the Lato dev team on this fonts issue? If not, we may need to look in to a different solution.

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/issues/6710 has some more recent conversation about this and it takes over from #2956 mentioned above.
