### ISSUE TITLE
Error on guild pages

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7187]
General Info
- UUID: 0e1d15f7-f36b-4f15-a9e1-0c31b732dac9
- Browser: Chrome 50
- OS: Ubuntu 14.04
### Description

Going on any guild page causes an error. It doesn't happen in the Tavern, only guild pages (so I assume it's nothing to do with chat).

![image](https://cloud.githubusercontent.com/assets/9433472/15196411/f99e5216-17c3-11e6-8d37-4eebfb674169.png)

![image](https://cloud.githubusercontent.com/assets/9433472/15196472/4f6075bc-17c4-11e6-999b-b7646f1fd40b.png)

**Comment by Alys** [comment]
Thank you! We found and fixed that error. Reload and it should stop now.
