### ISSUE TITLE
'How it works' page (/static/features) could use some TLC

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7188]
https://habitica.com/static/features ([code](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/features.jade)) has screenshots of the old mobile apps, and the boss image is broken. Having buttons sprinkled throughout a paragraph also doesn't look great IMHO:

![image](https://cloud.githubusercontent.com/assets/9433472/15196716/b1e722d4-17c5-11e6-9982-58aa8f26bbaf.png)

I know there's currently a code freeze for the new API; I can probably tackle this once APIv3 is out (assuming it won't be for a few weeks/until the end of May).

**Comment by librarianmage** [comment]
Some of the pictures could be taken from the press kit

**Comment by librarianmage** [comment]
I'll give this a try!

**Comment by khipkin** [comment]
I think a PR was already merged in to fix the broken boss image, but I can't find it any more.

**Comment by librarianmage** [comment]
I believe there has, but there are some problems and some TODOs that can be
taken care of.

**Comment by khipkin** [comment]
Yeah, there's definitely still stuff to be done! I was just talking about that one issue with the page. :)

**Comment by Alys** [comment]
Replacing badly outdated images with new ones would be good, especially if the images already exist on the site (e.g., press kit). @MathWhiz If you want to do that, please go ahead!

For anything else we might want to wait for an upcoming website improvement project, so ask here before  starting any other changes to that page.

**Comment by librarianmage** [comment]
Ok! Here are the things I want to work on:
-  Fix Link Paragraph
-  Update App picture
-  ~~Remove lead from paragraphs (the text looks overly large)~~
-  Fix grammatical mistakes / Inconsistencies
-  Add a link to the login modal at the bottom of the page

I don't know how soon the visual update will be, but there were a few TODOs
in there that I think we should at least prepare some content and pictures
for (achievements, pics for bottom section).

I was also wondering if we should add badges for the Apple App store,
Android Store, and the Chrome store. I know the visual redesign is coming,
but it might make sense if they were going to be added to have all of the
attribution stuff ready.

**Comment by librarianmage** [comment]
Is the new UI update planned to be before the end of the year?

**Comment by paglias** [comment]
@MathWhiz it will start before the end of the year but we don't know how much it'll take

**Comment by librarianmage** [comment]
@Alys is there anything on the list that should wait until the redesign?

**Comment by Alys** [comment]
I think this shouldn't be done yet:
-  Remove .lead from paragraphs (the text looks overly large)
  It's probably intended to look like that? Anyway, it's definitely a wait-for-redesign consideration.

The rest looks good I think!

**Comment by librarianmage** [comment]
I was suggesting removing .lead because it looks inconsistent to the rest
of the site. Also, it should only take a few minutes to complete.

**Comment by Alys** [comment]
It does look different to the rest of the site, but this page has a different purpose than the others and seems intended to have a different appearance. Please leave `.lead` in place for now. At the least, I'd want Lemoness to ask for it's removal, and she's on holidays.

**Comment by librarianmage** [comment]
Ok!

**Comment by crookedneighbor** [comment]
The grammar has been addressed here: https://github.com/HabitRPG/habitica/pull/8021
The broken image has been addressed here: https://github.com/HabitRPG/habitica/commit/540353f0247e1f1072f54a53fc67f0bc7da57b31

The rest we're deferring for the redesign.
