### ISSUE TITLE
Minor bug: Text won't scroll when entering new item

### ISSUE THREAD

**Issue by mgopher** [HabitRPG/habitica#719]
Chrome 25.0.1364.172, Windows 7

![habitrpgbug](https://f.cloud.github.com/assets/3960155/296430/0397cf92-94f8-11e2-94a3-1bcde811bd80.png)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
