### ISSUE TITLE
Habits keep resetting

### ISSUE THREAD

**Issue by mrshinesward** [HabitRPG/habitica#7192]
General Info
- UUID: 10dcd1dd-db7d-4aba-b0e7-ad9179f217b6
- Browser: Chrome
- OS: OS X Yosemite
### Description

I tick off my habits but they keep resetting to yellow

**Comment by TheHollidayInn** [comment]
Do they immediately reset or does this happen the next day?

**Comment by mrshinesward** [comment]
It happens the next day. I just ticked one off, so it's green, but I did the same thing yesterday, and today it was yellow.

**Comment by crookedneighbor** [comment]
This is the intended behavior. See http://habitica.wikia.com/wiki/Task_Value for more details.
