### ISSUE TITLE
[API v3] Client TODOs

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7194]
- [x] load completed todos if Completed tab is clicked
- [ ] review @TODOs
- [x] remove localStorage for the user CAN'T DO

@TheHollidayInn

**Comment by TheHollidayInn** [comment]
- [x] Fix Party members in header
- [x] Fix party via invite user
- [x] Fetching party chat
- [x] Fetching tavern chat
- [x] Change get user guilds param to userGuilds
- [x] Fix server message for incorrect group type
- [x] API Token does not appear on settings page
- [x] Guild descriptions do not show
- [x] Challenge member check is not working
- [x] Challenge add tasks is sending request to early
- [x] Buying pets and mounts with Mystic hour glass does not work
- [x] No message for buying travelers outfit with no Mystic Hour glass
- [x] Buying items has wrong text. Ex: You purchased a Floral hatcingPotions
- [x] Error appear when trying to buy a pet you already own
- [x] Error appears when buying something you don't have enough gold for
- [x] Some dailys do not validate when checking
- [x] Deleting PMS does not work

**Comment by paglias** [comment]
- [x] target should not appear for skills that have no target (like Searing Brightness)

**Comment by paglias** [comment]
- [x] views calls User.user.ops.opName instead of User.opName

**Comment by paglias** [comment]
- [x] Tags selection is broken (adding / removing tags from tasks)

**Comment by paglias** [comment]
- [ ] User.sortTag is not a function

**Comment by paglias** [comment]
- [x] Battle monsters with friends button (when not in a party or partying solo) doesn't work
- [x] Changed site language doesn't reload page

**Comment by TheHollidayInn** [comment]
Fixed:
-  (the one about the timezone is needed)
- Changed site language doesn't reload page
- Tags selection is broken (adding / removing tags from tasks)
- Battle monsters with friends button (when not in a party or partying solo) doesn't work
- load completed todos if Completed tab is clicked
