### ISSUE TITLE
Haven't Received Rewards of Pet Quest

### ISSUE THREAD

**Issue by DeweyReadmore** [HabitRPG/habitica#7196]
General Info
- UUID: ac2fd2a7-ab57-4fd9-8512-99d526544e40
- Browser: Firefox
- OS: 
### Description

My party recently completed The Icy Arachnid (I was the quest owner), and at least a couple of us have failed to receive the rewards, including myself and user petrajaga, UUID:     94924696-eb5d-4124-a436-ee6f1c71d04f 
Can this be fixed? Sorry for the trouble!
Thanks for your help!

**Comment by Alys** [comment]
No need to apologise! I'm sorry this bug hit you!

I've given the achievement and rewards to you both. Reload if you don't see them. Please post again here if they don't appear after that!
