### ISSUE TITLE
Frog Pets are Backwards

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7197]
The frog pets are facing the wrong way! Their sprites should be reversed.

**Comment by sporeball** [comment]
Is this still a problem even though it's been more than three weeks since this issue has been opened?

**Comment by Alys** [comment]
Yes. It's a low priority bug so we haven't rushed to fix it. If you're wanting to know whether you can work on it, then you would certainly be welcome to!

**Comment by sporeball** [comment]
@Alys Sorry for not 100% following the guidelines on Wikia, but here's the fix.

User ID: ce3d1e2b-be53-4e5e-8101-273157548178
