### ISSUE TITLE
Ultimate Consequences

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#72]
_Edited by wc8: Vote for this feature here: [Consequences](https://trello.com/c/PQz88jll)_
After a certain number of failures you have ultimate consequences. These differ from the regular consequences in that it will start to shutdown or take things from you. It might shut down your Facebook for a day or so. Maybe take money out of your account and put it into an unreachable account. Which will only become reachable after a certain number of completions. I know this is extreme but this makes habitrpg real. I think this is what will ultimately force people to stick to their habits.

**Comment by lefnire** [comment]
Let's re-visit this in the future, I think the party system will be the
biggest incentive-provider, then we'll tackle these personal
incentive-providers

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
This sounds like a gaming version of Mac apps like Concentrate, Vitamin-R and Self-Control. So, there may be some user interest. (Yes, probably best revisited later.) It might be difficult to accomplish website restriction with a web app as opposed to an offline/desktop/mobile app.

**Comment by ghost** [comment]
That is what I was thinking
