### ISSUE TITLE
[API v3] Are drops working?

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7206]

**Comment by lemoness** [comment]
I have been paying close attention to this, but have not received any drops, even after boosting my perception and checking off many tasks.

**Comment by lemoness** [comment]
Correction! There are now some drops in my inventory that were not there previously, but they never displayed while checking off tasks.

**Comment by shanaqui** [comment]
I am also getting drops, but not the pop-ups.

**Comment by Memry** [comment]
I just checked off enough to-dos to raise my level twice.  Not a single drop said it displayed and I have no new food for my pets.

**Comment by Memry** [comment]
Still not getting drops.  And I have changed class to Rogue and have a perception of 166

**Comment by crookedneighbor** [comment]
I'm looking at this. 

@Memry I found I needed to reload the page before the drops appeared, but I _was_ getting them.

This suggests to me that the client is just not doing the `randomDrop` calculation.

**Comment by paglias** [comment]
The client doesn't do any calculation for drops, it sends notifications
when the server sends a user._tmp object
Il 15 mag 2016 1:33 AM, "Blade Barringer" notifications@github.com ha
scritto:

**Comment by crookedneighbor** [comment]
This is fixed and will be live in the next hour.
