### ISSUE TITLE
[API v3] Clicking a checkbox causes task to lose checklist and tags

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7207]
General Info
- UUID: 28771972-ca6d-4c03-8261-e1734aa7d21d
- Browser: Chrome
- OS: Win 7
### Description

 Attempted to click a checkbox. Blue bar goes across, checklist disappears, as do tags. 
This also happens when clicking that "0/3"-type button that shows/hides the checklist.

Edit: Syncing returns them.

**Comment by crookedneighbor** [comment]
Taking a look.

**Comment by lemoness** [comment]
Further update: if you try to add another checklist, it will only let you add one, and it will not be saved.
