### ISSUE TITLE
[API V3] Rogue Skill Outcome Display Error

### ISSUE THREAD

**Issue by russodd** [HabitRPG/habitica#7208]
General Info
- UUID: 883df187-945c-44ce-b187-e4400398eefd
- Browser: Chrome Version 50.0.2661.94 (64-bit)
- OS: OS X Yosemite
### Description

When I use one of my rogue skills on a task (tried both Backstab and Pickpocket), a popup saying "Task "undefined" not found." comes up in the top right instead of the message saying that the skill was applied to the task.  All of the other popups appeared to be correct, and the skill seemed to execute successfully.
#### Console Errors

(index):1 POST https://v3.habitica.com/api/v2/user/class/cast/backStab?targetType=task&targetId=undefined 404 (Not Found)
nrWrapper @ (index):1
(anonymous function) @ app-010542b5.js:6
s @ app-010542b5.js:6f @ app-010542b5.js:6
j @ app-010542b5.js:7
(anonymous function) @ app-010542b5.js:7
j.$eval @ app-010542b5.js:7
j.$digest @ app-010542b5.js:7
j.$apply @ app-010542b5.js:7
(anonymous function) @ app-010542b5.js:8
o.event.dispatch @ app-010542b5.js:2
r.handle @ app-010542b5.js:2
nrWrapper @ (index):1

**Comment by Gooseus** [comment]
I'm getting the same thing casting Burst of Flames as mage:

![screen shot 2016-05-13 at 9 50 25 pm](https://cloud.githubusercontent.com/assets/39137/15265548/24392bc6-1955-11e6-8cf7-3676d0d1af27.png)

**Comment by citrusella** [comment]
I get the same with Brutal Smash. I have no idea if it's even having an effect and won't know for a whole 24 hours. XP

**Comment by TheHollidayInn** [comment]
Thanks! I believe this is happening for all skills that require a target.

**Comment by paglias** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.
