### ISSUE TITLE
Quest Owner won't start quest

### ISSUE THREAD

**Issue by agentdwib** [HabitRPG/habitica#7209]
Hopefully I am doing this correctly - the Wiki made me do it :innocent: 

BecomeUberHuman is our party and we are stuck waiting for the current quest owner to start the quest.  We'd either like to get the quest started, or abort it so we can start a new quest.

My User ID:  1789fa21-4df8-4064-a555-616dbc032964

**Comment by Alys** [comment]
How long has it been since the quest invitation was sent?

What attempts have been made to get in touch with the quest owner? I can see that they're still logging in to Habitica.

**Comment by agentdwib** [comment]
Apparently this has been resolved.  The party leader was able to remove the
quest owner from the party and this removed the quest.  Sorry to bother
everyone!

**Comment by Alys** [comment]
No worries! Thanks for letting us know!
