### ISSUE TITLE
UI issues in Opera - CSS outlines

### ISSUE THREAD

**Issue by ra100** [HabitRPG/habitica#721]
There are some graphical issues in Opera, as you can see, the lines(borders) of boxes visible on top of everything. And are not in perfect shape.
![Screenshot - 03252013 - 08:26:32 AM](https://f.cloud.github.com/assets/3185410/296913/6163604e-951d-11e2-86e8-6a4eec8477fc.png)

**Comment by ra100** [comment]
I have found, that problem is with outline: 1px solid rgba(0, 0, 0, 0.149); and different implementations, outline should be used to higlight element, not for borders. Could you change all outlines to box-shadows? like box-shadow: 0px 0px 0px 1px rgba(0, 0, 0, 0.149);

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
