### ISSUE TITLE
[API v3] Errors when Unequipping Battle Gear

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7211]
When you click "Unequip Battle Gear" the following messages display:

![apitest1](https://cloud.githubusercontent.com/assets/3494081/15265430/0b38bdb6-1938-11e6-9463-de23f10712cd.png)

**Comment by crookedneighbor** [comment]
Closed with 4dd7c29bafd07faa9d4f079e76b865b81bc41a42
