### ISSUE TITLE
[API v3] Social > Challenges Error: 'Must supply a valid "type" query string'

### ISSUE THREAD

**Issue by ltorroba** [HabitRPG/habitica#7213]
General Info
- UUID: 8ac1be04-4201-4eed-a2a4-436eada5c0e9
- Browser: Chrome, Firefox
- OS: Mac OS X
### Description

Upon accessing the Social > Challenges page (#/options/groups/challenges), the following popup shows up:

![](http://i.imgur.com/II6Z1v0.png)

Furthermore, no challenges whatsoever are listed. This behaviour was observed on both Chrome and Firefox.
#### Console Errors

`GET https://v3.habitica.com/api/v3/groups?type=party,publicGuilds,privateGuilds,habitrpg 400 (Bad Request)`

**Comment by ghost** [comment]
Can't make one, either. The drop-down menu with Tavern etc is empty, and it gives "Challenge validation failed" when trying to save.

**Comment by shanaqui** [comment]
I could make challenges appear by selecting a group, but the all/none buttons didn't work, and the participating/not participating and owned/not owned sections don't seem to work either.

**Comment by crookedneighbor** [comment]
The original issue is fixed. Not sure about 

> Can't make one, either. The drop-down menu with Tavern etc is empty, and it gives "Challenge validation failed" when trying to save.

If that's still occurring, open a new issue.
