### ISSUE TITLE
[API v3] Errors from dailies from ended challenge

### ISSUE THREAD

**Issue by froggily** [HabitRPG/habitica#7216]
General Info
- UUID: 634ef54c-8d52-4293-8adc-f0e810dd85dc
- Browser: Google Chrome Version 50.0.2661.86 (64-bit)
- OS: Mac OS X Yosemite 10.10.5
### Description

Clicking either the megaphone or the pencil on a daily from an ended challenge causes an empty grey box to appear where the challenge-ended message should be in the edit menu. Clicking the save button from the edit menu causes a "daily validation failed" message to appear. The same message appears when the daily is checked or unchecked, and it unchecks itself when it syncs.
#### Console Errors

(index):1 PUT https://v3.habitica.com/api/v3/tasks/fa4eda75-e347-486d-bbe0-380ac38391b8 400 (Bad Request)nrWrapper @ (index):1(anonymous function) @ app-010542b5.js:6s @ app-010542b5.js:6f @ app-010542b5.js:6j @ app-010542b5.js:7(anonymous function) @ app-010542b5.js:7j.$eval @ app-010542b5.js:7j.$digest @ app-010542b5.js:7j.$apply @ app-010542b5.js:7(anonymous function) @ app-010542b5.js:8o.event.dispatch @ app-010542b5.js:2r.handle @ app-010542b5.js:2nrWrapper @ (index):1
(index):1 POST https://v3.habitica.com/api/v3/tasks/fa4eda75-e347-486d-bbe0-380ac38391b8/score/down 400 (Bad Request)nrWrapper @ (index):1(anonymous function) @ app-010542b5.js:6s @ app-010542b5.js:6f @ app-010542b5.js:6j @ app-010542b5.js:7(anonymous function) @ app-010542b5.js:7j.$eval @ app-010542b5.js:7j.$digest @ app-010542b5.js:7j.$apply @ app-010542b5.js:7$$debounceViewValueCommit @ app-010542b5.js:8$setViewValue @ app-010542b5.js:8Qe.k @ app-010542b5.js:8o.event.dispatch @ app-010542b5.js:2r.handle @ app-010542b5.js:2nrWrapper @ (index):1
www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=844698911&_v=j43&z=718896516:1 GET https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=844698911&_v=j43&z=718896516 net::ERR_BLOCKED_BY_CLIENT

**Comment by citrusella** [comment]
Could this be related to the fact that absolutely no challenges seem to be listed on the test site? For that issue, I get a message reading "you must supply a valid "type" query string".

EDIT: Bleh, searched the list before replying to this and managed to miss the separate challenge issue. ~~I need sleep.~~

**Comment by paglias** [comment]
@froggily the tasks you're having a problem with are correctly linked to a finished challenge on habitica.com?

**Comment by paglias** [comment]
@citrusella I've fixed the daily validation error and the fix is going live in a few hours with the next deploy. For the non-working megaphone see #7234
