### ISSUE TITLE
Dailies change active/inactive indicator before end of day

### ISSUE THREAD

**Issue by Gooseus** [HabitRPG/habitica#722]
I set my EOD to be 2am and I have some dailies that run on weekends and others set for weekdays.

When I check at 1am on Sunday, it's confusing because my Monday daily is active and my Sunday daily is de-activated.

It appears that the style state of the page doesn't follow the same timing as the backend system.

**Comment by lefnire** [comment]
same issue as https://github.com/lefnire/habitrpg/issues/587?

**Comment by wc8** [comment]
@Gooseus if it's not #587, comment back and we'll reopen.
