### ISSUE TITLE
[API v3] Sticky header not working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#7220]
General Info
- UUID: bb089388-28ae-4e42-a8fa-f0c2bfb6f779
- Browser: Chrome 50.0.2661.102 m
- OS: Windows 10
### Description

[//](#): # Sticky header option is not working despite being enabled; it doesn't work when I refresh or check and uncheck it, either.
#### Console Errors

[//](#): # None that I can see, but I am not very familiar with the console.

**Comment by paglias** [comment]
Fixed, will go live in a few hours
