### ISSUE TITLE
[API v3] Mage skills

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#7221]
General Info
- UUID: bb089388-28ae-4e42-a8fa-f0c2bfb6f779
- Browser: Chrome 50.0.2661.102 m
- OS: Windows 10
### Description

[//](#): # Casting Earthquake immediately returns the mana on sync. Message appears in the party window, but buff doesn't seem to be applied.

Burst of Flames appears to work, with the caveat that there's an error message "task "undefined" not found". This occurs on all types of tasks.

(When casting another skill I got back the mana spent on Burst of Flames.)

Ethereal Surge also immediately returns mana, though a message appears in the party window.

**Comment by paglias** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.
