### ISSUE TITLE
[API  v3] Blessing costs no mana

### ISSUE THREAD

**Issue by taldin** [HabitRPG/habitica#7223]
Casting Blessing deducts 25 mana, but then gives you 25 right back.

**Comment by paglias** [comment]
@taldin is blessing applied at all?

**Comment by taldin** [comment]
It's being applied, yes, but you wind up getting the 25 mana back (-25, +HP, +25 MP)

**Comment by paglias** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.

**Comment by ghost** [comment]
@paglias. The same issue for the revived Valorous Presence and the Gaze. It seems they give mana back

**Comment by paglias** [comment]
@GitHubSphinx if you reload the page the problem persists? it should be fixed now

**Comment by ghost** [comment]
I've reloaded the page, cleared browser data from static/clear-browser-data, ctrl+f5'ed, opened in Opera for Android.

Valorous Presence and Intimidating Gaze still return mana for me.

**Comment by paglias** [comment]
Confirmed on v3.habitica but can't reproduce locally :(

**Comment by ghost** [comment]
It's gone. No more mana refunds for me.

But it's gone alongside with debug menu. And I started to get 502 reds when trying to cast Brutal Smash (

**Comment by paglias** [comment]
@GitHubSphinx sorry the app went offline while updating, try reloading now.

**Comment by ghost** [comment]
Great!

Oh @paglias and sorry for taking your time (

**Comment by GitHubSphinx** [comment]
Oh @paglias and sorry for taking your time (

**Comment by paglias** [comment]
Thank you for reporting bugs!
Il 15 mag 2016 10:58 PM, "Sphinx" notifications@github.com ha scritto:
