### ISSUE TITLE
[API v3] Clicking habits until blue sends them to the bottom of the list

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#7224]
General Info
- UUID: bb089388-28ae-4e42-a8fa-f0c2bfb6f779
- Browser: Google Chrome
- OS: Windows 10
### Description

[//](#): # Clicking +only habits until they're blue sends them to the bottom of the list the next time you sync. Clicking on them just a couple of times doesn't seem to have that effect, nor does clicking on an already blue +/- habit.

**Comment by paglias** [comment]
This is definitely #7235
