### ISSUE TITLE
[API v3] Challenge tag length popup error message is misplaced

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7225]
When creating a challenge, if you enter a tag name that's too short, the popup that it must be at least three characters long is pointing at the title field instead of the tag field.

![screen shot 2016-05-14 at 4 26 53 pm](https://cloud.githubusercontent.com/assets/1495809/15266696/eac9b6f2-19f0-11e6-87f9-ae223e9f1bed.png)

**Comment by TheHollidayInn** [comment]
I can't reproduce this.

**Comment by Alys** [comment]
Ah, I'm sorry, it's browser dependent, and I should have specified my browser, and thought to test in other browsers.

It happens in Vivaldi, a Chrome / Opera offshoot that is not common enough to worry about for now.

I can't reproduce it in Chrome. 

In Firefox, the popup doesn't appear at all, but I'll log that separately.

I'm closing this. We might reopen it later, after API v3 is live.
