### ISSUE TITLE
[API v3] Gems cannot be gifted (sent) from one player to another

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7227]
### Description

When using the "Send Gift to" modal, the "send" button does not do anything.
#### Console Errors

```
angular.js:11594 ReferenceError: message is not defined
    at Scope.$scope.sendGift (memberModalCtrl.js:42)
```

There's also incomplete code in the API's transfer-gems route.

I'm working on a fix for this now.

**Comment by Memry** [comment]
I tested it within the last hour and I it said it sent.  My gem counter decreased by one.  (I sent the gem to Kryzowski 432192fb-66ed-413c-88f6-b1ece628d943)

My UUID is e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by Alys** [comment]
Yes, the fix for it has gone live. Thanks Memry!
