### ISSUE TITLE
[API v3] Chat does not keep updates since last refresh, even when updated or synced

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7229]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Mozilla Firefox 46.0.1
- OS: Windows 7 Professional Service Pack 1 (via Bootcamp on a late-2011 Macbook Pro)
### Description

Fetching recent messages updates the chat... but only for as long as you are on it. Going to another page on the site (without a reload) and coming back puts the chat back in the state it was in when the site was last reloaded. Syncing does not bring the chat up to date in regards to this; only a full reload seems to change how recent the messages are without fetching them. I only tested this in the Tavern but would assume it could be happening in other chats, too.

I think it may be related: Chat also isn't updating with new messages right after I post a message. (Or it isn't updating reliably. XP)
#### Console Errors

None to speak of.

**Comment by paglias** [comment]
@TheHollidayInn new group object is not being sinced?
