### ISSUE TITLE
[API v3] Cannot flag chat messages (and probably can't unflag either)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7230]
### Description

When trying to flag a message, the confirmation modal appears, but clicking on the "Report Violation" button does not dismiss the modal. If you cancel the modal, you can see a flag on the message but the flag disappears as soon as you refetch chat (i.e., it's applied client side but not server side).
#### Console Errors

```
app-010542b5.js:6 TypeError: Cannot read property 'flagChatMessage' of undefined
    at j.a.reportAbuse (app-010542b5.js:45)
```

I believe that's referring to this code from `website/client/js/controllers/memberModalCtrl.js` :

```
      $scope.reportAbuse = function(reporter, message, groupId) {
        message.flags[reporter._id] = true;
        Chat.utils.flagChatMessage({gid: groupId, messageId: message.id}, undefined, function(data){
          Notification.text(window.env.t('abuseReported'));
          $scope.$close();
        });
      };
```

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/tree/api-v3

**Comment by paglias** [comment]
correct link is https://github.com/HabitRPG/habitrpg/commit/73dd9f5920dc87d8cdd081bd89821dbec33a6206
