### ISSUE TITLE
[API v3] After joining a guild, the join button remains

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7231]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

After joining a guild and going to the guild page, the "Join" button remains (next to the Leave button). AFAIK it should disappear. When clicking it, it states "User already in that group"

**Comment by TheHollidayInn** [comment]
@paglias This should be working now with my latest fixes.

**Comment by crookedneighbor** [comment]
Should be fixed now. Re-open if not.
