### ISSUE TITLE
[API v3] Checklists - only one checklist item can be added

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7233]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

So, after I've created a new daily, I wanted to add a checklist, but it didn't add a second one, I can only create one checklist item. Same for old dailies and todos overall.

**Comment by Alys** [comment]
Confirmed, and also after reloading, the checklist item disappears.

**Comment by crookedneighbor** [comment]
I've fixed this, but the new version of the code has not been deployed. Will leave this issue open so it's easier for people to find.

**Comment by crookedneighbor** [comment]
This is deployed.
