### ISSUE TITLE
[API v3] Can't remove or keep tasks from challenges that have ended

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7234]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

Challenges that have ended and have the broken megaphone icon. You click the broken megaphone, then it offers you to keep or remove the tasks, but neither of them does anything.

**Comment by crookedneighbor** [comment]
Copying from #7239

A challenge shows the "Broken Challenge Link" message and the megaphone marked in red but when I go into the challenge it does not give the usual "This challenge has been completed and the winner was " message and option to remove tasks

![image](https://cloud.githubusercontent.com/assets/7385423/15268660/140768d0-199b-11e6-960a-fdf7a048f82c.png)

**Comment by paglias** [comment]
Will look into this, when migrating there where a lot of tasks where not linked to any challenge...

@Kryzowsky this task on habitica.com was linked to a challenge that had been closed?

**Comment by paglias** [comment]
@Kryzowsky can you try now?

**Comment by Treegona** [comment]
User ID: 039fcf70-8eab-4c84-9ccd-8e9bf4d600f9
Browser: Firefox 46.0.1
OS: Windows 10

I have a possibly related bug? It involves a missing challenge. 
I joined a challenge about 2 months ago. I never received a notification that the challenge ended and the megaphone doesn't have a red background, but when I look through the challenges page I can't find it -I searched for the challenges I'm participating in and it didn't show up. I can't remove the habits or the dailies, but I can't leave the challenge either.

**Comment by paglias** [comment]
@Treegona hi, this issue is about a testing site not the main https://habitica.com, where did you notice it?

**Comment by Treegona** [comment]
@paglias Oh, sorry, I followed the instructions on Habitica's report a bug page which sent me to [this page](https://github.com/HabitRPG/habitrpg/issues/2760). One of the links took me to [here](https://github.com/HabitRPG/habitrpg/issues). From there I just searched for challenges, I hadn't realised that this wasn't where I was supposed to be.
Edit: Could you maybe point me to where I should be?

**Comment by paglias** [comment]
@Treegona don't worry, can you open a separate issue about this?

**Comment by paglias** [comment]
This should be fixed, reopen if it's not

**Comment by Kryzowsky** [comment]
It is not. I click the red megaphone, it tells me the winner, then if I click Remove Tasks or Keep Them, neither does anything. - In the upper right corner - "Invalid request parameters"

**Comment by paglias** [comment]
@Kryzowsky would you mind trying once again? It should finally work. Thanks for your patience!
