### ISSUE TITLE
[API v3] New tasks appear on the bottom

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7235]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

When adding new tasks, after refreshing the page, they are at the bottom of the list

**Comment by Kryzowsky** [comment]
Umm, sorry, I found out just after posting this (error regarding multiple to-dos) that this has already been posted, so I changed this to an other issue.

**Comment by Alys** [comment]
Thanks @Kryzowsky! Don't be worried about creating too many issues though. It's okay to close ones that are no longer needed and open new ones. :)

For anyone keeping track of this by email, this issue, which used to be "Adding multiple habits/dailies/to-dos error", is now about this bug:

"When adding new tasks, after refreshing the page, they are at the bottom of the list"

It might be related to https://github.com/HabitRPG/habitrpg/issues/7224

**Comment by paglias** [comment]
@TheHollidayInn This seem to be because tasks on the client don't follow user.tasksOrder

**Comment by paglias** [comment]
Fixed, going live in 15 minutes
