### ISSUE TITLE
[API v3]: Pet pop-up doesn't show when hatching a pet

### ISSUE THREAD

**Issue by Wariannem** [HabitRPG/habitica#7236]
[//]: # General Info
- UUID: a1f425bb-1fa4-4fcc-93d7-56737a8edfe2
- Browser: Chrome (Version 50.0.2661.94 (64-bit))
- OS: Mac El Capitan
### Description

[//]: # The Pet hatched pop-up  doesn't show after hatching a new pet. I ticked the option to show the pet pop-ups just before hatching.

**Comment by crookedneighbor** [comment]
@Wariannem Can you quickly follow up and explain why you closed the issue? I assume you figured it out and it wasn't actually an issue, but I'd like to be sure.

**Comment by Wariannem** [comment]
@crookedneighbor Yes I realised it was not an issue, the error was on my end. Tested it again and it all worked fine.
