### ISSUE TITLE
Enchanted Armoire items not appearing in inventory

### ISSUE THREAD

**Issue by lordmatt** [HabitRPG/habitica#7238]
General Info
- UUID: 96d68c04-a526-4141-b3ae-1ec7cb0d91c8
- Browser: Chrome
- OS: Ubuntu
### Description

I clicked the Enchanted Armoire a bunch of times. I got two rare items Comical Arrow and Curved (something or other) amour. However, the number of items in my inventory is unchanged. I have no idea if the pet food appeared as I do not know how much of that I had sitting about before hand.

**Comment by Alys** [comment]
Please see this issue for an explanation and work-around: https://github.com/HabitRPG/habitrpg/issues/5376 (see the text in bold near the top).
