### ISSUE TITLE
[API v3] Broken Challenge Lnks

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7239]
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7
### Description

A challenge shows the "Broken Challenge Link" message and the megaphone marked in red but when I go into the challenge it does not give the usual "This challenge has been completed and the winner was " message and option to remove tasks

![image](https://cloud.githubusercontent.com/assets/7385423/15268660/140768d0-199b-11e6-960a-fdf7a048f82c.png)

**Comment by librarianmage** [comment]
Same as #7234?

**Comment by Memry** [comment]
Yep.  I searched ahead of time but didn't see it.  My mistake.
