### ISSUE TITLE
[API v3] No gems in challenges

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7240]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7
### Description

No gems in challenges

I have several challenges I have created usually worth about 1 gem each.  (The one displayed is a challenge I use to clone, and yes, it has no participants but should have a gem value.)

Test site image for challenge https://v3.habitica.com/#/options/groups/challenges/10f8e27e-ddab-4aae-9a79-d3cee7d4ca45
![image](https://cloud.githubusercontent.com/assets/7385423/15268746/2a123878-199e-11e6-82b8-10c02175e6be.png)

Real site image for challange https://habitica.com/#/options/groups/challenges/10f8e27e-ddab-4aae-9a79-d3cee7d4ca45

![image](https://cloud.githubusercontent.com/assets/7385423/15268757/3ff9397a-199e-11e6-897e-f8b3a17fffaf.png)

**Comment by crookedneighbor** [comment]
Looking now.

**Comment by crookedneighbor** [comment]
@paglias I think this is an issue with the migration script.

**Comment by paglias** [comment]
This is fixed in https://github.com/HabitRPG/habitrpg/commit/708f495684d6ddcb32d5c2af9cbdaeb21b87efd8 and was indeed a bug in the migration. Unfortunately it won't go live while testing :/
