### ISSUE TITLE
[API v3] Challenge filter

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7241]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7
### Description

On the challenge page it comes up with no groups selected.  I can select individual groups but when I select "All" nothing happens.  "None" works fine.

**Comment by crookedneighbor** [comment]
Looking. I think I know what it is.

**Comment by crookedneighbor** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/a697d028b7e999c5e29ad66158ff7d1cffddd09d and deployed.
