### ISSUE TITLE
[API v3] data display tool

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7242]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7

Data display tool shows inaccurate information.

I just refreshed the display and it shows me with the wrong health, resting in the inn, and with todos due today.  (I just clicked done on all my dated to dos).  

![image](https://cloud.githubusercontent.com/assets/7385423/15268825/cffa424c-19a0-11e6-95cf-85e0c1f8ec1a.png)

![image](https://cloud.githubusercontent.com/assets/7385423/15268831/efc07a38-19a0-11e6-8c3f-5ce9d00c804b.png)

**Comment by librarianmage** [comment]
I think the DDT only shows info from the main site

**Comment by Alys** [comment]
Yes, @MathWhiz is correct. That version of the DDT is linked to the habitica.com site.

There'll be a test version for the API v3 site soon.

**Comment by Memry** [comment]
OK
