### ISSUE TITLE
When editing the details of task, the input area of description can be expanded exceed the limit of the task panel.

### ISSUE THREAD

**Issue by TianJinRong** [HabitRPG/habitica#7243]
General Info
- UUID: 0207d2fe-a324-4ae1-9cd9-60772ce89a8b
- Browser: Google Chrome
- OS: Win 10
### Description

![image](https://cloud.githubusercontent.com/assets/9194532/15269045/62905234-1a25-11e6-9132-fbeabc6ec1a5.png)
When editing the details of task, the input area of description can be expanded exceed the limit of the task panel.

**Comment by Alys** [comment]
That's deliberate. It allows a player to give themselves more room to read or write notes. It does look ugly, but it's fully under the control of the player so they can shrink it back down if they don't want it to be that large. For long notes or notes with wide lines, it can be very useful.

**Comment by TianJinRong** [comment]
Should we only limit the width of the input area might be better?

**Comment by crookedneighbor** [comment]
No. This has been brought up before and we decided against it at the time. We're going to start work on a redesign of the frontend, so we'll revisit this then.

**Comment by TianJinRong** [comment]
WOW~ Look forward to NEW VERSION :)
