### ISSUE TITLE
[API v3] Attribute points cannot be manually allocated

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7244]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Mozilla Firefox 46.0.1
- OS: Windows 7 Professional Service Pack 1 (via Bootcamp on a late-2011 Macbook Pro)
### Description

Decided to test rebirth (which appears to be working fine) and class selection (I chose rogue). Previous incarnation, I had auto-allocation for task based selection turned on. Upon upgrading to rogue, I had no attribute points at level 10, save one that was auto-allocated. I turned off auto-allocation and leveled to 11, at which point I got the other ten I should have had. I attempted to allocate them but was told I did not have enough points to do so. The allocations appeared to hold their places (I gave one to each category other than the auto-allocated one) until I refreshed. At that point I lost my manually allocated points and the unallocated points, leaving me only with the one that had been manually allocated.
#### Console Errors

None.

**Comment by citrusella** [comment]
Turns out the server just didn't actually level me up but my browser thought I was. XP Whoops. Still only had one allocated by the auto-allocation, though--is that normal?

**Comment by paglias** [comment]
This one needs a further look

**Comment by ghost** [comment]
Automatic allocation based on task specs.

General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10

Habit - hard, red, Physical, level 1. +++ = OK
The same habit, changed to Other,
--- = death, back to level 1
+++ = level up, `error object Object`, no attribute point, no level up after sync

Console output:

```
"Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
w/<@https://v3.habitica.com/common/dist/scripts/habitrpg-shared.js:14:14980
userServices.authenticate@https://v3.habitica.com/js/services/userServices.js:400:26
@https://v3.habitica.com/js/services/userServices.js:481:9
invoke@https://v3.habitica.com/bower_components/angular/angular.js:4182:14
enforcedReturnValue@https://v3.habitica.com/bower_components/angular/angular.js:4035:20
invoke@https://v3.habitica.com/bower_components/angular/angular.js:4182:14
createInjector/instanceCache.$injector<@https://v3.habitica.com/bower_components/angular/angular.js:4000:20
getService@https://v3.habitica.com/bower_components/angular/angular.js:4141:39
invoke@https://v3.habitica.com/bower_components/angular/angular.js:4173:13
$ControllerProvider/this.$get</</<@https://v3.habitica.com/bower_components/angular/angular.js:8441:11
nodeLinkFn/<@https://v3.habitica.com/bower_components/angular/angular.js:7693:13
forEach@https://v3.habitica.com/bower_components/angular/angular.js:331:11
nodeLinkFn@https://v3.habitica.com/bower_components/angular/angular.js:7692:11
compositeLinkFn@https://v3.habitica.com/bower_components/angular/angular.js:7075:13
publicLinkFn@https://v3.habitica.com/bower_components/angular/angular.js:6954:30
bootstrapApply/<@https://v3.habitica.com/bower_components/angular/angular.js:1451:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://v3.habitica.com/bower_components/angular/angular.js:14384:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://v3.habitica.com/bower_components/angular/angular.js:14483:18
bootstrapApply@https://v3.habitica.com/bower_components/angular/angular.js:1449:9
invoke@https://v3.habitica.com/bower_components/angular/angular.js:4182:14
bootstrap/doBootstrap@https://v3.habitica.com/bower_components/angular/angular.js:1447:5
bootstrap@https://v3.habitica.com/bower_components/angular/angular.js:1467:12
angularInit@https://v3.habitica.com/bower_components/angular/angular.js:1361:5
@https://v3.habitica.com/bower_components/angular/angular.js:26054:5
o.Callbacks/j@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:2:26671
o.Callbacks/k.fireWith@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:2:27489
.ready@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:2:29281
I@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:2:29451
" habitrpg-shared.js:14:14752
"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
minErr/<@https://v3.habitica.com/bower_components/angular/angular.js:63:12
beginPhase@https://v3.habitica.com/bower_components/angular/angular.js:14738:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://v3.habitica.com/bower_components/angular/angular.js:14482:11
hideTooltipBind@https://v3.habitica.com/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2809:15
o.event.special[a].handle@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:9617
o.event.dispatch@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:6003
o.event.add/r.handle@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:2813
[91]</t.exports@https://v3.habitica.com/common/dist/scripts/habitrpg-shared.js:7:18433
callOpsFunctionAndRequest@https://v3.habitica.com/js/services/userServices.js:110:11
userServices.buyMysterySet@https://v3.habitica.com/js/services/userServices.js:287:11
$parseFunctionCall@https://v3.habitica.com/bower_components/angular/angular.js:12332:15
ngEventHandler/</callback@https://v3.habitica.com/bower_components/angular/angular.js:21389:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://v3.habitica.com/bower_components/angular/angular.js:14384:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://v3.habitica.com/bower_components/angular/angular.js:14483:18
ngEventHandler/<@https://v3.habitica.com/bower_components/angular/angular.js:21394:17
o.event.dispatch@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:6003
o.event.add/r.handle@https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:2813
" angular.js:11594:18

Object { data: Object, status: 500, headers: headersGetter/<(), config: Object, statusText: "Internal Server Error" } config.js:45:11
.responseError() config.js:45
processQueue() angular.js:13171
scheduleProcessQueue/<() angular.js:13187
$RootScopeProvider/this.$get</Scope.prototype.$eval() angular.js:14384
$RootScopeProvider/this.$get</Scope.prototype.$digest() angular.js:14200
$RootScopeProvider/this.$get</Scope.prototype.$apply() angular.js:14489
done() angular.js:9646
completeRequest() angular.js:9836
requestLoaded() angular.js:9777
```

or should it be reported to a separate issue?

**Comment by GitHubSphinx** [comment]
correction: no level up (after sync) with that error

**Comment by GitHubSphinx** [comment]
or should it be reported to a separate issue?

**Comment by paglias** [comment]
@GitHubSphinx it's fine to keep it here!

**Comment by GitHubSphinx** [comment]
Something (maybe going above level ten) has fixed the automatic allocation for me

**Comment by GitHubSphinx** [comment]
Nope, the problem with automatic allocation is back (I'll be deleting the previous message and this one)

**Comment by paglias** [comment]
@GitHubSphinx sorry but I'm having some trouble replicating this, can you explain again the steps to see the problem?

**Comment by ghost** [comment]
@paglias It may be something with my account actually - i.e. due to dying a lot. It doesn't show up all the time. And I have difficulties reproducing it on a fresh account myself. However the steps which produce the error for me now:
1. fix character values: level 12, 
2. in stats go for Automatic Allocation - Distribute points based on task activity
3. create new habit, make it Social and Hard (optional)
4. do negative side of habit enough times to die (maybe optional)
5. do positive side of habit enough times to level up
6. the first time the attribute point received is allocated not for Int, as far as I remember
7. repeat steps 4-5 to get an error

Account:
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10

**Comment by ghost** [comment]
It seems I really can't make this issue show up on a fresh new account. Sorry

**Comment by paglias** [comment]
@GitHubSphinx If you still have access to the account where it happened, can you try replicating it once again after having hard refreshed the page? (refresh it 2 times just to be sure)

I searched in the logs and I think it could be a bug I fixed a few minutes ago

**Comment by GitHubSphinx** [comment]
just a couple of minutes

**Comment by ghost** [comment]
@paglias tested several times. No error occurred. Automatic allocation seems fixed!

**Comment by paglias** [comment]
thanks for all the testing!
