### ISSUE TITLE
[API v3] Challenges filter by membership doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7247]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

In challenges nothing is listed if I choose to filter the ones I take part in, or the ones I don't take part in. Only All works fine

**Comment by TheHollidayInn** [comment]
I'll fix this

**Comment by paglias** [comment]
This should be fixed now, reopen if it isn't
