### ISSUE TITLE
[API v3] Unable to delete a tasks when editing a new challenge

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7248]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

I'm creating a new challenge: I add a habit/daily/task/reward, but before saving the challenge I decide to delete the habit/daily/task/daily. The site gives an error: Task not found

**Comment by ghost** [comment]
After saving a new challenge, it seems there's still no way to delete a task

**Comment by TheHollidayInn** [comment]
I am fixing this.

**Comment by paglias** [comment]
This should be fixed now, reopen if it isn't
