### ISSUE TITLE
[API v3] No info about participants in challenges

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7249]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

Challenges show the number of participants, but the details don't show the How's Everyone Doing? section. When I try to end a challenge and declare a winner, the list of participants is empty

**Comment by Memry** [comment]
Me too

UUID e495bd8b-f2f1-48e8-8f5f-9a52710999cf
Browser Chrome Version 50.0.2661.102 m
OS Windows 7

**Comment by TheHollidayInn** [comment]
I'll fix this

**Comment by paglias** [comment]
This should be fixed now, reopen if it isn't
