### ISSUE TITLE
[API v3] Can't leave challenge -- "Remove-" and "Keep tasks" links both non-functioning

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7250]
UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
Browser: Chrome 50.0.2661.94 m
OS: Windows 10
### Description

Possibly (or probably) related to #7234. Steps to replicate:
1. Join a challenge
(1a. Confirm success by syncing and checking task list -- the button doesn't change from "Join" to "Leave" right away)
2. Click the Leave button
3. In the bubble that pops up, the cursor becomes a pointer finger when hovering over either "Remove tasks" or "Keep tasks", showing that they are recognized as links
4. Clicking either link does nothing; only the Cancel link works

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/0f7964cac11f0bcdb82336eb82903391ed52ad0c

@lynnyliz note that there are still some bugs when leaving a challenge for example the Join button may still act like if you're still participating until you reload the page

**Comment by quin-jay** [comment]
@paglias Yep, just confirmed that that's the case. Another issue I just noticed is that the "Leave challenge and..." heading no longer has the grey background so the text is hard to read, but I'm sure you're already aware of that. Good work to you and everyone else, I know you're all working overtime to squash all these bugs! :+1:
