### ISSUE TITLE
[API v3] Mistakes in new notification texts

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7251]
There is now a new notification when selling items, but depending on the case, its text contains some minor mistakes:

![capture d ecran de 2016-05-14 19-51-54](https://cloud.githubusercontent.com/assets/4882150/15270030/fc601804-1a11-11e6-8ffe-53e46fc3848a.png)
No space between _Pet_ and _Cub_, and _eggs_ is plural but only one can be sold at a time.

![capture d ecran de 2016-05-14 19-57-18](https://cloud.githubusercontent.com/assets/4882150/15270031/fc6f12aa-1a11-11e6-9d3c-d50c1f1755a4.png)
No space between _hatching_ and _Potions_, and _Potions_ is plural but only one can be sold at a time.

**Comment by ghost** [comment]
Found a few more new notifications that looks ... wrong:

![capture d ecran de 2016-05-14 20-54-49](https://cloud.githubusercontent.com/assets/4882150/15270209/2c10cc56-1a17-11e6-87e6-017804ed64d1.png)
![capture d ecran de 2016-05-14 20-54-55](https://cloud.githubusercontent.com/assets/4882150/15270210/2c145a24-1a17-11e6-9260-f822cea0c1c7.png)
![capture d ecran de 2016-05-14 20-55-05](https://cloud.githubusercontent.com/assets/4882150/15270211/2c175288-1a17-11e6-92d2-a8c069fa17ee.png)

No caps for _birthday_, _greeting_ and _thankyou_, and no space in _thankyou_.

**Comment by ghost** [comment]
I haven't tested it on production, but buying a saddle gives notification about "buying saddle food"

**Comment by ghost** [comment]
Purchasing quests are missing an _a_ in _purchased_. Also, some quests titles seems odd.
![capture d ecran de 2016-05-15 10-19-10](https://cloud.githubusercontent.com/assets/4882150/15272954/dab8e8ac-1a89-11e6-935e-1054ffb79ead.png)
![capture d ecran de 2016-05-15 10-21-38](https://cloud.githubusercontent.com/assets/4882150/15272953/dab8a2ca-1a89-11e6-93c8-e212bfbdb6aa.png)

**Comment by paglias** [comment]
I think we're passing the item's keys instead of translated name...

**Comment by quin-jay** [comment]
Just wanted to confirm the same behavior when _purchasing_ eggs as well (including the typo mentioned by @Blablux):
![screenshot 7](https://cloud.githubusercontent.com/assets/6640915/15276932/dc5b8392-1ac3-11e6-9db7-191aa29ac8b6.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/6640915/15276933/dc5dbedc-1ac3-11e6-99c0-4363484dab12.png)

**Comment by ghost** [comment]
Just noticed the typo in _purchased_ (purchsed) on the screen shots. Is it also there on production?

**Comment by quin-jay** [comment]
@GitHubSphinx Right now there are no notifications in the live/production site, whether for confirming sale of an item or purchase of any item

**Comment by Wariannem** [comment]
When using the website in another language (tested french) the notification comes twice and in different versions for feeding pets. For purchasing the notification comes in english with the typo mentioned earlier by @GitHubSphinx and @Blablux. 
![screenshot 2016-05-17 15 58 12](https://cloud.githubusercontent.com/assets/19360357/15324835/647e81a4-1c48-11e6-8e8a-f722ea540638.png)

**Comment by paglias** [comment]
@Alys should these new notifications removed (you purchase a ..., you sold a ...)

**Comment by paglias** [comment]
Removed 2 strings and fixed the error with non english languages
