### ISSUE TITLE
[API v3] Server unreachable notification when creating / joining a guild

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7254]
### General Info
- UUID: a75eb6f8-5a29-482f-a971-7aff7438da86
- Browser: Firefox 46
- OS: Ubuntu
### Description

When creating a new guild, I'm getting a _server unreachable_ notification (or some similar text, I have the french version of this text):

![capture d ecran de 2016-05-14 20-43-01](https://cloud.githubusercontent.com/assets/4882150/15270155/6c91c1f6-1a15-11e6-97df-c3c5bfea5e6e.png)

I reproduced it when creating another guild (after completely reloading Habitica, just in case), so this doesn't seem to be a one-time scenario.

**Comment by paglias** [comment]
@Blablux can you try again now? thanks

**Comment by ghost** [comment]
@paglias Just tried now, same punishment. I might just add that the guild is indeed created, with nothing looking wrong right now. It's just that this notification is weird.

Side note: I may be able to test this a few more times, but I'll soon be completely broke :smile:

**Comment by crookedneighbor** [comment]
I can't reproduce this. Can you provide all the details to reproduce this? IE, the exact text you're putting into the fields?

**Comment by ghost** [comment]
The guilds were created as public guilds, with random text in title and description, except for one thing, all guild titles began with _[API v3]_ followed by the random text.

![capture d ecran de 2016-05-14 21-14-34](https://cloud.githubusercontent.com/assets/4882150/15270249/023a4ac2-1a19-11e6-8ac8-725e40c6b4a9.png)
![capture d ecran de 2016-05-14 21-14-35](https://cloud.githubusercontent.com/assets/4882150/15270250/0245f214-1a19-11e6-94e7-117cf92e2edf.png)

And the part were the guild owner will be the only one to create challenges was left unchecked.

I then hit the _Create Guild_ button, have a popup message asking me if I want to create a guild for 4 gems. I click on yes and immediately get the _Server unreachable_ notification. While the notification is shown, the guild appears in a blank state while the page is loading, see the full screenshot below:

![capture d ecran de 2016-05-14 20-56-55](https://cloud.githubusercontent.com/assets/4882150/15270276/f2b20a9e-1a19-11e6-9870-d6e8d1be324a.png)

And when the page finished loading, everything appears correctly (and the notification disappear)

**Comment by crookedneighbor** [comment]
Great, thanks for the info.

**Comment by ghost** [comment]
I get the exact same notification when joining an existing guild (reproduced on four different guilds). I load the _Public guilds_ list, hit the _Join_ button on any guild, and while the newly joined guild is loading, I once again get a _Server currently unreachable_ notification.

![capture d ecran de 2016-05-14 21-59-06](https://cloud.githubusercontent.com/assets/4882150/15270397/2af411b8-1a1f-11e6-960d-498b40094ab7.png)

I once again tried to disconnect/reconnect, reload the page, I'm still having this message on any guild I join (I tried the first four of the list).

**Comment by crookedneighbor** [comment]
Hmmm... @paglias is it possible that the request is just timing out before it can finish? I'm not seeing any of these issues.

**Comment by ghost** [comment]
Now that I can reproduce it at any time, I can give a little more insight about the timing (if that is of any interest).

When joining a guild, first the blue loading/syncing bar on top of the site loads (almost instantly), and give the notification. Then the page itself loads as a whole.

This may also be interesting to note that I'm only seeing this behaviour with the guilds. I still have much to test, but I'm not getting this error yet in any other part of Habitica that require a sync (or even while manually syncing).

**Comment by paglias** [comment]
@Blablux still getting this error?

**Comment by ghost** [comment]
@paglias I just tried right now, and I'm still getting the notification while joining a guild.

**Comment by paglias** [comment]
@Blablux  :( can you try with a new account?

**Comment by ghost** [comment]
I just created a new account, but I'm somehow stuck after logging in:
![capture d ecran de 2016-05-16 23-16-03](https://cloud.githubusercontent.com/assets/4882150/15304213/52366746-1bbc-11e6-81ed-290caa7ad423.png)
I tried reloading, closing and reopening, but right now I'm still stuck there.

**Comment by paglias** [comment]
Sorry, reload in 5 minutes and it'll work
Il 16 mag 2016 11:18 PM, "Benoit Hetru" notifications@github.com ha
scritto:

**Comment by ghost** [comment]
Yes, I figured that out, I'm now getting a 502 / Bad Gateway :smile:

**Comment by ghost** [comment]
Still the same with a new account:
![capture d ecran de 2016-05-16 23-24-14](https://cloud.githubusercontent.com/assets/4882150/15304401/66ee4608-1bbd-11e6-8a05-4490c17ff673.png)
User ID b8db48a7-3afa-425e-9731-9286ee1d8bae if this is of any help.

**Comment by paglias** [comment]
Last thing: can you try with a different browser / a smartphone or an
incognito window?
Il 16 mag 2016 11:26 PM, "Benoit Hetru" notifications@github.com ha
scritto:

**Comment by ghost** [comment]
Just tried on Android 6.0.1 with Firefox mobile:
![screenshot_20160516-233557](https://cloud.githubusercontent.com/assets/4882150/15304754/63f084aa-1bbf-11e6-8385-f1a576ecba20.png)
Still getting the error message

**Comment by paglias** [comment]
@Blablux wow this bug is so strange, if you have the possibility, can you try the same thing from a different wifi or mobile network?

**Comment by ghost** [comment]
Just tried on a mobile network on a third device, still the same error (unfortunately I can't upload the screenshot yet, I may do it tomorrow if needed)

**Comment by ghost** [comment]
Here is the screenshot on a mobile network, on a HTC m8 running Cyanogenmod 12.1.
![2016-05-17 16 25 26](https://cloud.githubusercontent.com/assets/4882150/15368021/12f8bb30-1d2c-11e6-9172-db26c6e8bede.png)

**Comment by GitHubSphinx** [comment]
@Blablux have you tried it with a fresh new account?

**Comment by GitHubSphinx** [comment]
oh, yes, sorry I've missed it. Deleting my question

**Comment by TheHollidayInn** [comment]
@paglias Do we log errors? Maybe we can view errors on the server at the time.

Has anyone else been able to reproduce?

**Comment by paglias** [comment]
@TheHollidayInn we do log errors but there aren't linked to @Blablux 's account and the type of notification he gets means that the request has timed out, like if it got stuck somewhere

**Comment by ghost** [comment]
Just to follow up on this bug, since v3 went live for all users, I do not have this notification when joining a guild anymore. So as far as I'm concerned, it doesn't happen in production right now.

**Comment by crookedneighbor** [comment]
👍
