### ISSUE TITLE
[API v3] Key to the Kennels does not work

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7255]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Mozilla Firefox 46.0.1
- OS: Windows 7 Professional Service Pack 1 (via Bootcamp on a late-2011 Macbook Pro)
### Description

Key to the Kennels gives a "not found" message after hanging for a few seconds, at least with the free option, but then _appears_ to work (i.e., the paws return). Hatching a pet afterward (which highlights the eggs as if they are available) gives the standard "you already have that pet" message, because it doesn't actually release the pets/mounts, though it makes the pets we "already had" appear in the grid and takes the egg/potion. Syncing will display the pets/mounts again and return any gen 1 eggs/potions hatched before the sync.
#### Console Errors

I didn't see any at any point during the process.

**Comment by paglias** [comment]
@citrusella can you do me a favor an try using Key to the Kennels again? then post here when you've received the message. I've searched through the logs but can't find this error

Also just before you try to use it, can you open the console and switch to the network page. When the error occurs a new red request will appear, click on it and copy the Request URL

**Comment by citrusella** [comment]
The URL (from the 404 error in the network page list) was https://v3.habitica.com/api/v3/user/releaseBoth

Also of note (I think, but maybe not) in regards to my original description, since I noticed them as I was doing this: Though the sync brings back the pets/mounts, until a full reload the key is unusable and the numbers for the master achievement progress remain at whatever new hatch attempts (and mount taming) was done before the refresh.

**Comment by paglias** [comment]
@citrusella this should work now!
