### ISSUE TITLE
[API V3] Leaving a party with only you in it causes an error

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7256]
General Info
- UUID: 0e1d15f7-f36b-4f15-a9e1-0c31b732dac9
- Browser: Chrome 50
- OS: Ubuntu 14.04
### Description

To reproduce:
1. Be not in a party
2. ~~Go to https://v3.habitica.com/#/options/groups/party~~ not necessary
3. Press 'Battle Monsters With Friends'
4. Press 'Send Invitations' and close the popup
   - _you are now in a party containing only yourself_
5. Press 'Leave' and 'Confirm'
6. Observe 'Group not found.' error at top-right; this error is not present on the production site when following the same steps.
#### Console Errors

![image](https://cloud.githubusercontent.com/assets/9433472/15270402/ef3456ea-1a16-11e6-9907-15b0f1b7dd2a.png)

**Comment by paglias** [comment]
Fixing this one

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/6ab3280045525011bbf906a2965403d2ccad8ecc

Thanks @anowlcalledjosh ! It'll go live at the next deploy
