### ISSUE TITLE
[API v3] Tags will not filter tasks

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7258]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7
### Description

When I select a tag on my Tasks screen - nothing displays.  All tasks disappear.  
#### Console Errors

![image](https://cloud.githubusercontent.com/assets/7385423/15271124/127da19c-19ef-11e6-9262-7166bfdce1dd.png)

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/commit/cb0939a38c9c63c164455ce16dcc5a0bbd6ba17b
