### ISSUE TITLE
[API v3] Death lies! Greedily!

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7259]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
  - OS: Windows 7
### Description

I tested death.  It took my gold as expected, but it also told me my violet floppy hat broke.  What actually broke was my Stephen Weber shaft of the dragon.

**Comment by Alys** [comment]
Ah nostalgia... How nice to see this bug again. :scream: :imp: :rage:

To save anyone else's time if they're thinking of searching for this, this is how we fixed it last time: https://github.com/HabitRPG/habitrpg-shared/pull/295/files
but that when the gear was in an array, whereas now its not, so that fix is no longer relevant.

**Comment by Alys** [comment]
Huh, correction: randomVal does put them into an array, but it's already sorting it. And the seed isn't specified, so it should be PI, so you'd expect the same behaviour on client and server. Odd.

@Memry Do you feel like dying a few more times to see if Death always lies? :)

**Comment by Alys** [comment]
Note the `health = 1` option in the debug menu at the footer of the page. That plus one negative Habit is a fast way of dying.

**Comment by Alys** [comment]
Something else to test: If you buy the lost item back before dying again, do you always lose the same item? With no seed being specified, I'd expect that you would, at least until you obtained brand new gear. If that happens, we'll want to change that.

**Comment by citrusella** [comment]
Death only lies until it syncs (in my experience with dying), at least as far as I can tell? Is that important to note? It said my diploma broke, presented the Horned Iron Helm in the rewards list, and then fixed itself to diploma when I synced.

**Comment by paglias** [comment]
This can be due to some differences in stats (for example critical hits are broken right now in v3 so they won't be accounted for on the client)

Will review this at the end of testing when hopefully it'll have disappeared automatically.

Idea for the future: run this code only on the server like for randomDrops

**Comment by crookedneighbor** [comment]
@paglias That's what I was thinking. Same for armoire purchases.

**Comment by Memry** [comment]
When I came back on today and had refreshed for another reason, it showed my violet floppy hat as the item to purchase and the shaft of the dragon was back in my inventory and back on my gear (I had been carrying it when it "broke".  

I died again, and it said my sleek cat suit broke, showed the nunchaku as the item to purchase, but when I checked in inventory and tried to equip the sleek cat suit it game me a "gearNotOwned" message.  

Second death it said my icicle drake mask broke but showed the umbral armor as purchasable.  Refresh fixed it also.  

And re-purchasing the item did not result in the same item breaking.

**Comment by Alys** [comment]
Death now reports that you lost two items. One of the items is the one that appears immediately in the Rewards column but that goes back into your inventory after a sync (Death's client-side choice). The other is the item that appears in the Rewards column after the sync (Death's server-side choice).

For anyone wanting to test Death, thanks to @crookedneighbor the Debug menu in the footer now contains a "Modify Inventory" option  with a Gear section that has an "Own All" button. Using that then clicking "Apply Changes", and then dying makes it really easy to see which item you lose.

**Comment by paglias** [comment]
What about having the revive code running only on the server? So the bug
can't exist
Il 17 mag 2016 4:00 AM, "Alys" notifications@github.com ha scritto:

**Comment by Alys** [comment]
That would fix the problem forever and I would love it beyond all things.

**Comment by paglias** [comment]
Let's wait until the end and if we can't fix it we'll switch to server only code

**Comment by paglias** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/7ea581bb38881f36f8b651172c871fb99b0fde5e
