### ISSUE TITLE
[API v3] "Start a quest" button showing up while already in a quest

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7266]
### General Info
- UUID: a75eb6f8-5a29-482f-a971-7aff7438da86
- Browser: Firefox 46
- OS: Ubuntu 16.04
### Description

I started API v3 already in a quest, but the _Start a quest_ button is showing up below the current Quest.

![capture d ecran de 2016-05-15 10-27-01](https://cloud.githubusercontent.com/assets/4882150/15272895/f2d1e81e-1a87-11e6-831b-2add3ddc416c.png)

Clicking on it brings up the available quests, and I can select any of it. When trying to launch a new quest, I get an error message telling me that I'm already in a quest.

**Comment by ghost** [comment]
Just to be sure it wasn't related to the fact that I was on a quest while migrating to API v3, I aborted the quest and created a new one. The _Start a quest_ button is still showing up.

**Comment by paglias** [comment]
@TheHollidayInn confirmed

**Comment by paglias** [comment]
Fixed, will go live in a few hours
