### ISSUE TITLE
[API v3] "Join" button not replaced by "Leave" after joining a challenge

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7267]
### General Info
- UUID: a75eb6f8-5a29-482f-a971-7aff7438da86
- Browser: Firefox 46
- OS: Ubuntu 16.04
### Description

I went to the challenges page and picked a challenge.

![capture d ecran de 2016-05-15 11-03-59](https://cloud.githubusercontent.com/assets/4882150/15273030/fd0cbe4e-1a8c-11e6-99ca-ee26cf8499b1.png)

Hitting the _Join_ button does increase by 1 the numbers of participants, but the _Join_ button is still showing up.

![capture d ecran de 2016-05-15 11-04-20](https://cloud.githubusercontent.com/assets/4882150/15273031/fd449076-1a8c-11e6-9a16-684e0e2d7069.png)

Hitting _Join_ again does bring an error message stating that I'm already participating.

![capture d ecran de 2016-05-15 11-04-30](https://cloud.githubusercontent.com/assets/4882150/15273032/fd4801a2-1a8c-11e6-8d18-98b4decd4ebd.png)

Syncing that page does not change anything. 
But I found out that, if I go to the Tasks page and there try to do a sync, then the new tasks are showing up, and going back to the challenges page does correctly show a _Leave_ button

![capture d ecran de 2016-05-15 11-05-21](https://cloud.githubusercontent.com/assets/4882150/15273033/fd496f4c-1a8c-11e6-8a2c-949cbb84ae8a.png)

**Comment by TheHollidayInn** [comment]
I'll take this one.

**Comment by Memry** [comment]
I created a challenge at it first showed Join still, then showed Leave after I refreshed.  But the tasks never showed on my task page, just the tag.  I tried sync and refresh, neither brought up the tasks. 

UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by paglias** [comment]
This should be fixed now, reopen if it isn't
