### ISSUE TITLE
Dailies are on my HabitRPG are still checked from yesterday

### ISSUE THREAD

**Issue by MarilynLau** [HabitRPG/habitica#727]
I have a problem today with my Habit RPG. Am I the only one? All the "daily" I checked yesterday are still checked today! Since this morning, I don't know how many times I loaded the page to see if it would get okay and it don't! Now I'm scared that I won't be able to check them again today and that I'll lose all my life during the night!

**Comment by wc8** [comment]
Just to start off, what is your end of day/custom start time setting, if any? (You can find it under your username menu > Settings)

Also, try clearing your browser cache. Which browser are you using?

**Comment by lefnire** [comment]
@MarilynLau are you familiar with Chrome Console or Firebug that you can see if there are any javascript errors? (I really need to write an FAQ page for js error debugging). If you can't do that, [shoot me](mailto:tylerrenelle@gmail.com) your user id and I'll debug you locally

**Comment by Silverai** [comment]
This seems like what I have.  Last Saturday, I knew I'd be out late so I made my EOD 2am.  I got home and ticked off my last daily at 1:30am.  When I checked it next day (Sunday), it was still grey out, and the progress calendar said I had ticked it on Sunday, and I lost health from apparently not ticking it the day before.  This is a daily set for all days.  Thinking it could be an hour +/- that was the issues, I then set the EOD for 4am for future.
Last night (Tuesday) I ticked off three dailies at 10:30pm.  This morning 7:30am (Wed) they are still greyed out and I have lost health from apparently not ticking them yesterday.  

Last night I made two of these dailies not valid for Fri, Sat, and Sun, but the third I left as daily for all days, so I don't believe that would be affecting it.
I am using Firefox 19.0.2  Screen shot below.
![20130327HabitRPGscreenshot](https://f.cloud.github.com/assets/3979943/306110/6ffcd8f4-966e-11e2-838a-8fade94d6044.png)

**Comment by dfjkla** [comment]
I have the same issue. Custom day end set at 6am. I typically update well after midnight. It's now 1:30am, and I still have items checked which I checked 24 hours ago. Latest Opera.

**Comment by lefnire** [comment]
@dfjkla I've been hearing some Opera issues all around, can you try Chrome / Firefox?

**Comment by Eevachu** [comment]
I've got the same problem in Firefox, my custom day start is 6am, but whenever I check something off past midnight it checks it off for the next day and I lose health when the custom day starts.

**Comment by dfjkla** [comment]
It works now.

**Comment by jaybers** [comment]
i'm having the same issue.... but it's not a consistant problem, sometimes they do reset.... i'm a night owl so pretty much every day i have checked off the last of my dailies after midnight... i have my custom day start set at 5am and i am using chrome on a mac or chrome on my galaxy s3..

**Comment by lefnire** [comment]
When they aren't unchecked, it's almost certainly a case that a javascript error halted execution of the page scripts, and "cron" is never reached. If anyone experiences this issue, open up firebug / chrome console / etc, to get the javascript error and paste it here. If you get it consistently, [email me](mailto:tylerrenelle@gmail.com) your user id and I can test it locally to see what's up

**Comment by lefnire** [comment]
@mihakuu i think you were experiencing this too

**Comment by Mihakuu** [comment]
I did yesterday. My habits refreshed over night for today though.

**Comment by Silverai** [comment]
I seem to be having success with refreshing the tab, waiting, then refreshing again, then doing ticks etc.  Then I wait a bit, then I refresh again before I close down, to confirm the changes have taken hold.  So far I haven't had any more issues.  It could be coincidence of course.  I'm still happy to have no further issues so far.

**Comment by wizonesolutions** [comment]
Closing in favor of https://github.com/lefnire/habitrpg/issues/1057
