### ISSUE TITLE
[API v3] Stealth wants a target

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7276]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Version 50.0.2661.102 m
- OS: Windows 7

When I select "Stealth" it give me the indicator that I need to select a task.  When I then try to click on anything it give me a message "invalid target"  It won't go away until I select another skill.

**Comment by GitHubSphinx** [comment]
Warrior skills: gaze and valorous presence - produce `Invalid request parameters.` error

**Comment by paglias** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.
