### ISSUE TITLE
[API v3] Typos in api docs

### ISSUE THREAD

**Issue by aviskase** [HabitRPG/habitica#7277]
General Info
- UUID: 266104ca-889e-4a7a-956d-3bd9a94244d3
### Description

1) Two entries with a heading "Group - Accept a pending quest". [1](https://v3.habitica.com/apidoc/#api-Group-AcceptQuest) [2](https://v3.habitica.com/apidoc/#api-Group-ForceQuestStart)
The second one is wrong, because it's about force starting: `https://v3.habitica.com/api/v3/groups/:groupId/quests/force-start`

2) Entry ["Task - Create a new task the user."](https://v3.habitica.com/apidoc/#api-Task-CreateUserTasks)
Sounds strange, probably should be "Task - Create a new task belonging to the user."

3) Entry ["User - DELETE an authenticated user's account"](https://v3.habitica.com/apidoc/#api-User-UserDelete)
No need for all caps, just "User - Delete an authenticated user's account"

4) Entry ["User - Reser password"](https://v3.habitica.com/apidoc/#api-User-ResetPassword)
Should be "User - Reset password"

5) Description for entry ["User - Update email"](https://v3.habitica.com/apidoc/#api-User-UpdateEmail) --- "Che the user email"
Should be "Change the user email"
I suspect that parameters description for this entry can be wrong too.

**Comment by Alys** [comment]
I'll fix these where I can, and report back if there's anything I can't do.

**Comment by aviskase** [comment]
Thanks! One more spotted ---
6) Typo in the endpoint for entry ["Meta - Get all paths for the specified model"](https://v3.habitica.com/apidoc/#api-Meta-GetUserModelPaths)
Displayed: `https://v3.habitica.com/api/v3s/models/:model/paths`
Should be: `https://v3.habitica.com/api/v3/models/:model/paths`
