### ISSUE TITLE
[API v3] No message on reaching level 100+

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7279]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

Please excuse me if I'm wrong, but it seems there should be a message on reaching level 100+. I don't get it on v3 beta
#### Console Errors

seems like none

**Comment by Alys** [comment]
On the production site, you get the normal level-up modal when reaching 100 (i.e., the same as for other levels). There isn't a special one for level 100.

**Comment by ghost** [comment]
Thank you! Ah, the message about not receiving more attribute points must then be on the character stats page... Sorry
