### ISSUE TITLE
[API v3] Debug boss progress up feature not working

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7281]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

Boss progress up feature from the debug menu doesn't work producing error: (something like) the path `party.quest.progress.up` hasn't been saved. The path is reserved.

I'm not sure if it's an issue. Please excuse me for reporting if it's not.
#### Console Errors

PUT XHR https://v3.habitica.com/api/v3/user HTTP/1.1 401 Unauthorized 245ms

**Comment by ghost** [comment]
Also `+1 missed day` and `+2 missed days` give `Not found` response.

**Comment by crookedneighbor** [comment]
The missed day things are fixed. Will go out on the next deploy. I'll fix the boss progress problem.

**Comment by crookedneighbor** [comment]
This is fixed and will be live on the next deploy. Likely tomorrow.
