### ISSUE TITLE
[API v3] streak on Daily can't be edited

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7285]
### Description

When you edit a Daily to adjust its streak, and then save, the new streak number appears. When you sync, the previous streak number reappears. I.e., edits to the streak appear to be not saved to the database.
#### Console Errors

none

**Comment by TheHollidayInn** [comment]
@paglias Looks like the request is being sent correctly from client. I think this line might be the cause: https://github.com/HabitRPG/habitrpg/blob/api-v3/website/server/models/task.js#L59 .

**Comment by paglias** [comment]
Yeah it's that
