### ISSUE TITLE
[API v3] After manually changing XP to level up, 500 Internal Server Error when clicking tasks

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7288]
UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
Browser: Chrome 50.0.2661.94 m
OS: Windows 10
### Description

What I did: 
1. Clicked +1 Level button in the debug menu. This didn't immediately level me up, but rather added a level's worth of experience, as expected
2. Clicked on a task (either positive or negative) to trigger levelup modal, which usually works, but instead gave this:
![screenshot 10](https://cloud.githubusercontent.com/assets/6640915/15277507/d2d46a62-1ad4-11e6-94a6-e82d6490707d.png)

Reloading the page or syncing leads it to revert any task clicks I did in the meantime:
![screenshot 11](https://cloud.githubusercontent.com/assets/6640915/15277514/1d55e99e-1ad5-11e6-918a-7f8baee3da26.png)

This was NOT fixed by going to Settings > Site > Fix Character Values and setting experience to 769/770. So I played around a bit, trying different XP amounts and following them with positive task clicks:
- Fixing XP to 600 resulted in a successful task click
- Fixing XP to 760 resulted in an error when rolled-over XP would've been 1/800
- Fixing XP to 759 resulted in an error when rolled-over XP would've been 0/800
- Fixing XP to 758 resulted in two successful task clicks: One that made my XP 769/770, and one that successfully leveled me up, with rolled-over XP being 7/800
- Fixing XP to 795/800 (now that I've leveled up) resulted in an error when rolled-over XP would've been 7/820

So as near as I can tell, the bug is this: **Manually changing your XP to a high enough number will break task clicks if they're supposed to trigger a levelup.** Negative clicks are okay as long as you're below the XP threshold for a levelup. Reloading the whole page doesn't trigger levelup, only a task click will.

My fear is that this also applies to XP earned from defeating a boss. I haven't been able to test that (clicking the Boss Quest Progress Up button gave me some other error which I haven't looked much into yet but which might be because the boss I'm fighting only has 400 HP, not 1000 which the button applies).
#### Console Errors

[This gist](https://gist.github.com/lynnyliz/5855ed1229df4c47c174eca58b03936f) shows the log after I grabbed the first screenshot, reloaded, and clicked a bunch of tasks. I can provide more logs if you need them; with so many errors it was a little confusing, but it looked like copy+paste and "save as .log" only showed certain details if I'd expanded the error messages in the console first.

**Comment by Alys** [comment]
Sorry, this isn't your main point, but anyway, FYI:

> (clicking the Boss Quest Progress Up button gave me some other error which I haven't looked much into yet but which might be because the boss I'm fighting only has 400 HP, not 1000 which the button applies).

That won't be what's causing the button's error. They button just adds 1000 to `party.quest.progress.up`, which means you'll do 1000 damage to the boss when you cron. The boss's HP doesn't matter. It's just like using Brutal Smash multiple times to over-kill the boss.

**Comment by quin-jay** [comment]
@Alys Oh, that totally makes sense, thank you for explaining! I'm still getting an error, but it looks like it's going to be fixed soon (#7281). When that fix deploys, I'll test whether quest XP triggers this issue too. I'm having visions of users not being able to click any tasks because they finished a quest, so I really wanna test everything just to make sure

**Comment by paglias** [comment]
@lynnyliz I think I fixed this (an error with auto allocation), can you check if it's working? I couldn't replicate myself

**Comment by quin-jay** [comment]
@paglias Yep, it seems to be fine now! I tested it with class-based and task-type-based auto allocation, and both seem to be working again. Thanks :)
