### ISSUE TITLE
Daily tasks only clear via the web interface, not the API

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#729]
Original report at pjf/WebService-HabitRPG#16 .

Daily tasks only get cleared when the HabitRPG webpage is loaded. If one is exclusively using the API (eg: phone/cmdline) then they never get cleared.

**Comment by pjf** [comment]
And sometimes they don't seem to clear even when I do visit the website. o_O
Have no idea if this is time related. It's 22:24 localtime (GMT+11), which is later than I'd normally visit.

I can probably manually uncheck tasks using the PUT API, but I suspect that's not what mere mortals will do. :)

**Comment by pjf** [comment]
When using the command-line client, `hrpg clear daily` can now be used to force a clear of daily tasks.

**Comment by MagicMicky** [comment]
Any news about this ?
@pjf does your fix for hrpg make it work like on the website ? I mean, will it make you loose HP if you don't do a daily, and reset the dailies when you use `hrpg clear daily` ?
I tried to read your code to see how you do the fix, if I understood well, you update the task and set "completed" to false?

**Comment by pjf** [comment]
@MagicMicky : It does not, I'm afraid. It just uses magic to set the 'completed' attribute to zero. There's no HP loss involved. :(  So if you're in the habit of completing all your dailies every day, it could be an aceptable workaround.

I did try using the API to 'down' a daily task that was uncompleted, but I seem to recall instead of it removing HP, it instead removed GP and XP instead (effectively an 'undo'). I seem to recall I have an open bug about that somewhere.

In theory I could do some magic where I clone incomplete dailies to a temporary area as tasks, mark them 'down' (which should cause the appropriate XP loss), copy the task level and history information back to the original daily task, and then delete the temporary tasks...  but that would be a monumental workaround which I'm not actually convinced would work the same way as clears on the website.

**Comment by MagicMicky** [comment]
@pjf Ok, thanks for your answer. I guess we will have to wait for an API update, because it doesn't allow full-fledged applications right now. I'll try to take a look to the source code to see how it is done and how we could update the API to do it, but I'm not a web developer...
Maybe it will be updated for it to work with HabitRPG official mobile app?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
