### ISSUE TITLE
[API v3] Orb of rebirth didn't reset tasks to yellow

### ISSUE THREAD

**Issue by CloJo** [HabitRPG/habitica#7290]
General Info
- UUID: 99463fab-e36e-4f8b-87f6-a6f925850ed8
- Browser: Safari
- OS: OSX Yosemite version 10.10.5
### Description

[//](#): # Using orb of rebirth did not reset all tasks to yellow.  The to-dos range in colour from red to yellow (no dark red)  Dailies range in colour from orange to yellow.  Habits have all reset to yellow.  
#### Console Errors

![screen shot 2016-05-16 at 12 16 37 pm](https://cloud.githubusercontent.com/assets/13231001/15278760/4d713454-1b60-11e6-9cf6-d3d568dc5ebf.png)

**Comment by Alys** [comment]
Confirmed that using the Orb of Rebirth doesn't change the task colours, but if you do a manual sync immediately after the rebirth has finished, then the tasks revert to yellow. Something wrong with the way the tasks are saved?

```
api.userRebirth = {
  method: 'POST',
  middlewares: [authWithHeaders()],
  url: '/user/rebirth',
  async handler (req, res) {
    let user = res.locals.user;
    let query = {
      userId: user._id,
      type: {$in: ['daily', 'habit', 'todo']},
    };
    let tasks = await Tasks.Task.find(query).exec();
    let rebirthRes = common.ops.rebirth(user, tasks, req, res.analytics);

    await user.save();

    await Bluebird.all(tasks.map(task => task.save()));

    res.respond(200, ...rebirthRes);
  },
};
```

**Comment by Alys** [comment]
Also note that all of CloJo's Habits, which did reset to yellow, belong to active challenges, so that might have allowed rebirth to work correctly.

When I tested, my Habits behaved in the same way as the other tasks (did not become yellow until after a manual sync). None of my Habits are from active challenges.

**Comment by paglias** [comment]
This is fixed, let me know if you see it again
