### ISSUE TITLE
[API v3] Custom Day Start time will not set

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7291]
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7

Tried to set a custom cron.  It returned the error message "path lastCron was not saved" and when I refresh the old custom cron time shows.
![image](https://cloud.githubusercontent.com/assets/7385423/15280408/e4c2a74c-1ae4-11e6-94b9-4a89f5c348ba.png)

**Comment by Alys** [comment]
I'm about to rename this to "Custom Day Start time will not set".

I believe setting lastCron is an important part of this feature as it protects the user from a surprise cron at the time of changing or too soon afterwards.

**Comment by TheHollidayInn** [comment]
@crookedneighbor I think you created the new route `/debug/set-cron`. I think we should move the route to the user controller to fix this issue.

**Comment by paglias** [comment]
@crookedneighbor do you want to use debug/set-cron (moved to user controller) or the old way of updating the user with PUT /user whitelisting lastCron?

**Comment by crookedneighbor** [comment]
I think the real question is do we want to give clients the ability to set lastCron to _any_ date? If so, yeah, I'm fine moving it to the user controller or making it adjustable. 

If we want to control how lastCron is set, I'd make setting a custom day start a separate route.

**Comment by paglias** [comment]
Well in v3 we tried to limit the paths freely updatable but I've been forced to undo many changes like streaks on tasks. The option here is to make lastCron settable or create a new route to change the custom day start

**Comment by TheHollidayInn** [comment]
I think we move the debug route to the user controller. Then it becomes a "setter" and we can add restrictions.

**Comment by paglias** [comment]
I agree with @crookedneighbor , let's create a new route to set custom day start

**Comment by TheHollidayInn** [comment]
@crookedneighbor finished this up. So this should be fixed now.

**Comment by crookedneighbor** [comment]
I don't think this has been deployed to the test site yet.
