### ISSUE TITLE
[API v3] Challenge participants can edit settings of tasks that only the challenge owner should edit

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7294]
### Description

After joining a challenge, the participants can edit their own copies of the challenge tasks in ways that only the challenge creator should be able to do.

These are the only things a challenge participant should be able to edit ([ref.](http://habitica.wikia.com/wiki/Challenges#Challenge_Participant.27s_Permissions)):
- Add/edit checklists
- Add/edit notes
- Assign/remove tags (their own tags and/or the challenge tag)
- Change the tasks' attributes (CON, INT, PER, STR)
- Edit the streak on Dailies

**Comment by Alys** [comment]
More specifically, this is using the API directly, or the mobile apps. The website's client code still prevents those edits.

**Comment by paglias** [comment]
So the website UI doesn't require any change? Just extra validation for the API?

**Comment by citrusella** [comment]
As far as I can tell, the v3 site still prevents the relevant settings from being changed, but the app still allows for the changes (i.e. the API still allows the changes).

**Comment by Alys** [comment]
> So the website UI doesn't require any change? Just extra validation for the API?

Yes.

**Comment by Alys** [comment]
Sorry, another thing that a challenge participant must be able to do:
- Edit the streak on a challenge's Daily

It's necessary for the case where bugs / internet outage causes an unfair cron that removes the streaks.

I've updated my first post here to include this.

**Comment by paglias** [comment]
Fixed
