### ISSUE TITLE
PUT requests with changed task-id via API: bug or feature?

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#730]
It's possible to use a `PUT` operation in the API to submit a _different_ task-id than the task which is being modified. This has the effect of creating a new task which the id specified, which clones its values from the task specified in the original URL.

This is either a feature (since it allows us to have task 'templates'), or a bug (which I suspect is more likely).

I've got a hunch I can overwrite _existing_ tasks this way, but I haven't tested that. I'm pretty sure that would be a bug.

cc/ @switz

**Comment by paglias** [comment]
This should be fixed as soon as we switch to subdocs for tasks

**Comment by jbutz** [comment]
I know this is assigned, but since the issue was opened a while ago and the change was small I went ahead and fixed this. Here is a link to the pull request: https://github.com/HabitRPG/habitrpg-shared/pull/173

**Comment by jbutz** [comment]
My change has been merged. This should be closed out.
