### ISSUE TITLE
[API v3] Open new task in edit mode not working

### ISSUE THREAD

**Issue by dfecko** [HabitRPG/habitica#7300]
General Info
- UUID: 2fb6b0c7-a7eb-4903-a2a9-2f5a0916de47
- Browser: Chrome
- OS: Windows 7
### Description

[//](#): Setting checked to open new task in edit mode.  Remains open for a second, but then quickly collapses

**Comment by paglias** [comment]
@dfecko can you try again? This is working for me

**Comment by Alys** [comment]
@dfecko If this problem happens only with Dailies, then it's a known bug that happens in the current production site too. https://github.com/HabitRPG/habitrpg/issues/5728

It can also sometimes happen in the current production site with other kinds of tasks if the website isn't yet synced with the server. https://github.com/HabitRPG/habitrpg/issues/2965#issuecomment-156799671

**Comment by dfecko** [comment]
After trying again it looks like I was running into the bug mentioned
below. Habits and to-dos are working fine.

**Comment by crookedneighbor** [comment]
Will close this now then. Thanks for verifying it!
