### ISSUE TITLE
[After API v3] Add ability to return all completed todos (on website just from last 30)

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7301]
@Alys 

_edit by Alys:_

The code to be modified is in website/server/controllers/api-v3/tasks.js in `async function _getTasks()`

Currently there's a limit of 30 imposed in the code.

**Comment by Alys** [comment]
Thanks @paglias. 

I think we can get away with this not being done before go-live if it can't be fitted in easily. For the DDT, I can add a note that all completed To-Dos can still be found in an export.

**Comment by paglias** [comment]
Moving to POST API v3

**Comment by Alys** [comment]
@paglias Is it okay if we add an option to return all completed To-Dos at once? Or did you want it to be done so that you have to request the first 30, then the second 30, and so on?

**Comment by paglias** [comment]
@Alys go ahead! All at once is okay, just not display all of them on the
site
Il 05 giu 2016 10:49 AM, "Alys" notifications@github.com ha scritto:
