### ISSUE TITLE
[API v3] Enable Class System button in settings before level 10

### ISSUE THREAD

**Issue by dfecko** [HabitRPG/habitica#7302]
General Info
- UUID: 2fb6b0c7-a7eb-4903-a2a9-2f5a0916de47
- Browser: Chrome
- OS: Windows 7
### Description

[//](#): There is an Enable Class System button in Settings -> Site after performing a rebirth while still at level 1.  Clicking it shows a popup that says I must be level 10.

**Comment by paglias** [comment]
@dfecko it doesn't show on habitica.com?

**Comment by dfecko** [comment]
I'm not sure, I'm above level 10 on my real account and don't want to mess
with it like I'm doing in the test instance.

**Comment by Alys** [comment]
It does not display before level 10 in production (neither for a new account nor for an account that has rebirthed)

**Comment by TheHollidayInn** [comment]
Hmm. It looks like this only shows if you have disabled classes. I'm not able to replicate this as an error.

`button.btn.btn-default(ng-if='user.preferences.disableClasses==true', ng-click='User.changeClass({})', popover-trigger='mouseenter', popover-placement='right', popover=env.t('enableClassPop'))= env.t('enableClass')`

**Comment by Alys** [comment]
I can't reproduce the bug in the test site. After rebirth, the button doesn't appear until after I've reached level 10 and opted out.
