### ISSUE TITLE
[API v3] Resetting from settings doesn't reset attribute points

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7303]
General Info
- UUID: a46cf6fa-189e-44fa-b5b6-aa9371ecac8b
- Browser: FF 46
- OS: win10
### Description

I'm resetting the account from the danger zone. However the attribute points (auto allocation based on tasks) are still there

**Comment by paglias** [comment]
@GitHubSphinx are they reset in v2?

**Comment by paglias** [comment]
I can't find it in the code

**Comment by ghost** [comment]
I believe I tested it yesterday, and they did reset in v2. Resetting is supposed to produce a fresh new account with the same credentials, as far as I understand

**Comment by ghost** [comment]
I'm double-checking it now

**Comment by paglias** [comment]
Thanks, @Alys I can't see the code to reset points here https://github.com/HabitRPG/habitrpg/blob/develop/common/script/ops/reset.js but I may be missing something

**Comment by ghost** [comment]
@paglias @Alys I'm sorry, I'm wrong about it. Attribute points are not reset when you reset account. Both in v2 and v3 =(

**Comment by ghost** [comment]
addition:
I'm tripple checking it, and it may actually be something with un-allocated points which kept bothering me.

When I reset the account un-allocated points are in place (as the allocated ones) but then with the first level change the un-allocated points are taken away. 

I'll close the issue until I figure out what really should be reported.

**Comment by Alys** [comment]
FYI, it will be covered by whatever fix we make for this issue: https://github.com/HabitRPG/habitrpg/issues/6482 which is a catch-all for all attribute point problems.
