### ISSUE TITLE
[API v3] Invalid request parameters if wrong email when signing up

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7304]
General Info
- UUID: none
- Browser: FF 46.0.1
- OS: win 10
### Description

Trying to sign up with
- login mememe1
- email me@me.me1

produces specific error about email being incorrect on production, but v3.beta gives just "Invalid request parameters" error

I'm not sure if it's an issue or a feature, reporting in just in case
#### Console Errors

none

**Comment by paglias** [comment]
Yeah we'll want to show the underlying error messages, not the Invalid request parameters one.

**Comment by paglias** [comment]
Fixed
