### ISSUE TITLE
[API v3] Leveled up immediately after death

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7307]
When I opened the test site for the first time today, it correctly told me that I had died. However, after clicking through that modal (and the "choose a class" modal, which popped up due to probably-unrelated a bug on the mobile app), there was a popup congratulating me on leveling up.

**Comment by paglias** [comment]
It's possible that you last used the site as say level 8 and before dying you had reached level 10?
In this case the site would show the level up popup for going from 8 to 9

**Comment by lemoness** [comment]
Aha, that was probably it, since I was testing the mobile app a lot this weekend! And would explain why I have not been able to replicate it.
