### ISSUE TITLE
[API v3] User.sortTag is not a function

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7312]
General Info
- UUID: 
- Browser: 
- OS:

**Comment by TheHollidayInn** [comment]
@paglias The front end is an easy fix, however, the tags don't have any tagOrder field like tasks do. I think we need to add a index key to the tag model and update the api to use this. Does that sound correct to you?

**Comment by paglias** [comment]
Hmm. The tags are saved as an array so we can directly reorder it
Il 20 mag 2016 8:20 AM, "Keith Holliday" notifications@github.com ha
scritto:

**Comment by TheHollidayInn** [comment]
Oh, well never mind then :P

**Comment by TheHollidayInn** [comment]
I still think I will need to add a new route. Maybe User update tags? Or should I add it to the tag controller?

**Comment by paglias** [comment]
Oh yeah a new route is necessary, I'd say in the tags controller
Il 20 mag 2016 1:20 PM, "Keith Holliday" notifications@github.com ha
scritto:
