### ISSUE TITLE
[API v3] A Tavern challenge can be created without a gem prize

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7313]
### Description

When creating a challenge in the Tavern, you aren't forced to set a gem prize.
#### Console Errors

none

**Comment by Kryzowsky** [comment]
Also, as of now all challenges are featured without a gem prize (except when creating an entirely new one).

**Comment by Alys** [comment]
> Also, as of now all challenges are featured without a gem prize (except when creating an entirely new one).

@Kryzowsky That's a known problem caused by the migration a few days ago when the test site was created. You can ignore it. It won't happen in the next migration.

**Comment by paglias** [comment]
Fixed
