### ISSUE TITLE
[API v3] Challenge creation: no validation message for missing group (lower priority)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7314]
### Description

When creating a challenge, if you neglect to select a group from the drop-down, you don't get any validation error messages until you click "save", and then you get the blue growl saying "Error Challenge validation failed". 

The ideal behaviour would be for client-side javascript to give you a warning when you click save but before anything is sent to the server (in the same way that you get a warning if you leave the title field blank).

I believe this does not have to be fixed before go-live.
#### Console Errors

POST https://v3.habitica.com/api/v3/challenges 400 (Bad Request)

**Comment by paglias** [comment]
Fixed since a group must be selected now
