### ISSUE TITLE
[API v3] server error notification blue colour / color doesn't scream "error"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7315]
### Description

The server errors now use a blue growl, but should they be a different colour? Blue is typically a positive colour, and is similar to the mana notification. It might be harder for people to realise that an error has occurred. The red colour from the old server errors might be better?

If this is changed, I believe it would not need to be done before go-live.

![screen shot 2016-05-17 at 12 21 01 pm](https://cloud.githubusercontent.com/assets/1495809/15309384/f43b5b6a-1c29-11e6-8f21-96c216a7abd8.png)

BTW, I do like the new notifications. So much nicer than the old ugly ones!

**Comment by crookedneighbor** [comment]
I agree, anything with a response code of 400 or higher should be a different color.

**Comment by paglias** [comment]
@crookedneighbor @Alys just change the notification color to red?

**Comment by crookedneighbor** [comment]
Yeah

**Comment by paglias** [comment]
What about "Not enough gold"? In production is a blue notification, should it be an red one too?

**Comment by crookedneighbor** [comment]
I think it should be red.

**Comment by crookedneighbor** [comment]
Since it denotes an error.

**Comment by paglias** [comment]
Server errors return a red notification.
Client notifications have not been changed, we can change them later
