### ISSUE TITLE
[API v3]Cannot accept/reject quest from Party interface

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7317]
General Info
- UUID: 
- Browser: Chrome
- OS:  Win10
### Description

Accept/Reject buttons next to Ian do not work. They get the blue outline highlight, but do not do anything. Have to refresh page to get the quest invite pop-up again.

**Comment by TheHollidayInn** [comment]
Fixing this.

@paglias The issue here is the return structure of force start does not send response.data.quest like other quest routes. Is it okay to change this structure on the server side? I am adding a hack on the client side for now.

**Comment by TheHollidayInn** [comment]
@paglias same issue as #7332

**Comment by paglias** [comment]
This should be fixed now
