### ISSUE TITLE
[API v3] Old challenges, which I own and participate in - I can't be selected as winner

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7319]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

In older challenges, transported from the site, which I did not newly create, I can't be selected as a winner (I am not on the list or at the bottom), even though I participate in them (even according to the filter).

**Comment by Alys** [comment]
@Kryzowsky That's probably due to a bug in the mgiration that created the test accounts.

When I create a new challenge on the test site, I am able to select myself as the winner.

**Comment by ghost** [comment]
- Old challenge, I'm the owner and a member - OK, but I had to refresh to see the congratulations modal
- Old challenge, I'm the owner but not a member - not able to declare myself a winner (I guess it's OK)
- Old challenge, I'm the owner but not a member - after joining - OK (as in point 1)
- New challenges (including new v3 ones cloned from v2 ones a couple of days ago) - OK

@paglias all in all seems fixed to me

**Comment by paglias** [comment]
@GitHubSphinx thanks!
