### ISSUE TITLE
[API v3] Cannot send a card to a party member

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7322]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7
### Description

I cannot send a card to a party member.  I can send it to myself, but not to Sphinx. I tested all three cards.  

Also - do you want as a separate issue that when I click the notification that I received a card - it does nothing.

**Comment by paglias** [comment]
It's okay to keep them in 1 issue

**Comment by paglias** [comment]
Fixed (going live shortly the inability to send a card, opening a new issue for the redirect issue)
