### ISSUE TITLE
[API v3] Start a quest button not working

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7323]
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7
### Description

I am in a party with Sphinx we created just for testing quests and other party items.  We just completed a quest and when I select the "Start a quest" button, nothing happens.

**Comment by paglias** [comment]
Any console error?
Il 17 mag 2016 3:00 PM, "Memry" notifications@github.com ha scritto:

**Comment by Memry** [comment]
Nothing.  There is no response at all.  I might as well be clicking a blank space.

**Comment by ghost** [comment]
confirmed. Party ID e3565aa7-2917-4460-9716-c930e4fd778d

**_added:**_
I've been able to start a quest from inventory
... abort it... and now the "start" button works again

**_added after that:**_
In case it may be relevant:

> _Sphinx_ Finding more than enough bars of soup was accompanied by an object-object error for me

meaning the previous quest ended with a couple of errors. We'll test it once again today

**Comment by GitHubSphinx** [comment]
I've been able to start a quest from inventory

**Comment by GitHubSphinx** [comment]
... abort it... and now the "start" button works again

**Comment by GitHubSphinx** [comment]
In case it may be relevant:

>*Sphinx* Finding more than enough bars of soup was accompanied by an object-object error for me

meaning the previous quest ended with a couple of errors. We'll test it once again today

**Comment by paglias** [comment]
@GitHubSphinx would you mind inviting me to your party? UUID ed4c688c-6652-4a92-9d03-a5a79844174a

**Comment by GitHubSphinx** [comment]
done

**Comment by ghost** [comment]
@paglias done

added: Quest completed. No errors this time

**Comment by paglias** [comment]
Dup #7232

**Comment by ghost** [comment]
This is just to notify @Memry about the findings from #7339 

> START A QUEST BUTTON doesn't work if the party is opened via the options/groups/guilds/id address: https://v3.habitica.com/#/options/groups/guilds/e3565aa7-2917-4460-9716-c930e4fd778d
