### ISSUE TITLE
[API v3] No more batch-update means changes not synced automatically

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7325]
One of the few advantages of batchUpdate was that it automatically reconciled the browser data with the database data every time a request was sent in case the user was updated by using a mobile app, 3rd party integration, quest boss, ...

Now this doesn't happen anymore so it's possible to work on the site for a long time without syncing and the updated values will never show up.

@Alys @crookedneighbor

**Comment by Alys** [comment]
So as an example, you could be at low health, and a party member casts a skill to increase your health, but you don't see if for potentially a long time afterwards?

If you use negative Habits before the healing is synced to the browser, could that cause problems with the browser thinking you should die when the server knows you shouldn't?

**Comment by paglias** [comment]
Yes

**Comment by paglias** [comment]
One option to fix this is to send back user._v with every server response and if the difference between the client _v and the _v sent by the server is > 1 force a sync

**Comment by paglias** [comment]
The options I see here are two:
- return {data, success, message, userV} at every request
- return userV only if ?userV=Number was passed in the request

**Comment by TheHollidayInn** [comment]
This would be in the user controller? I think return userV on every request. I like the idea of change for a change and syncing if need be.

**Comment by paglias** [comment]
I'm a bit against to adding it automatically to every response because it would be a bit like saying that the userV is the only meaningful version to keep track of while instead this is not true (there are tasks, groups, ...) and tracking only the user version is a sort of simplification

**Comment by TheHollidayInn** [comment]
Well, the related items are synced differently, so I think the simplification is correct. We don't need to sync the groups and tasks at the same time we sync the user.

**Comment by paglias** [comment]
Fixed with https://github.com/HabitRPG/habitrpg/commit/b49826129a544d80e537e34aaad47a6f82831dee
