### ISSUE TITLE
[API v3] Challenges list inside a group doesn't show the note if no challenges

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7326]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

If a party/guild has no challenges, the list will say _No challenges yet, visit  Challenges to create one._ on production. However this note is note displayed for me on v3beta

added: the note is there for guilds, but not for a party
#### Console Errors

none afaict

**Comment by GitHubSphinx** [comment]
added: the note is there for guilds, but not for a party

**Comment by paglias** [comment]
@TheHollidayInn I think this is because the $scope.group behaves differently than in v2

**Comment by ghost** [comment]
I've just created a new account and new party of one... and the note is in place. Strange.

Added:
but the problem remains for my account and the party:
![sc](https://snag.gy/w6JGDV.jpg)

**Comment by GitHubSphinx** [comment]
The note is back for my account too

**Comment by GitHubSphinx** [comment]
and disappeared again...

**Comment by TheHollidayInn** [comment]
Fixing this.

**Comment by paglias** [comment]
This should be fixed now

**Comment by ghost** [comment]
Confirming that it's fixed for me!
