### ISSUE TITLE
[API v3] Party name defaults to "group name"

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#7331]
General Info
- UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee
- Browser: Chrome
- OS: Windows
### Description

On the production server, the party I am in has no name:
![image](https://cloud.githubusercontent.com/assets/12386291/15327884/a1f799ec-1c18-11e6-8ce8-bb3e646cf5c8.png)

However, on the API v3 server, the party I am in has been renamed to "group name"
![image](https://cloud.githubusercontent.com/assets/12386291/15327971/f226ad72-1c18-11e6-854a-5828d9e9730f.png)

**Comment by paglias** [comment]
@MathWhiz thanks, this is expected. In v3 the party name is required so to avoid getting validation failed errors I've defaulted groups with missing names to "group name". You can change it to something else if you want
