### ISSUE TITLE
[API v3] Forcing quest start doesn't update party page

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7332]
Manual refresh is needed to show that quest has started

**Comment by TheHollidayInn** [comment]
Fixing this.

@paglias The issue here is the return structure of force start does not send response.data.quest like other quest routes. Is it okay to change this structure on the server side? I am adding a hack on the client side for now.

**Comment by paglias** [comment]
Yeah, let's change it on the server before we release v3
Il 18 mag 2016 12:06 AM, "Keith Holliday" notifications@github.com ha
scritto:

**Comment by TheHollidayInn** [comment]
Actually, never mind. I'm not seeing any route that returns quest in the response. Maybe it was an old v2 thing.

**Comment by paglias** [comment]
This should be fixed now

**Comment by ghost** [comment]
@paglias I don't know if it's related or if it maybe waiting a deploy, but when I finished a quest (+progress +missed_day from debug) I got a message about completing a quest, but the page didn't refresh and quest info was still there until manual refresh.

**Comment by paglias** [comment]
@GitHubSphinx could have been due to the deploy, can you reload the page and try again?

**Comment by ghost** [comment]
- initiate -> autorefresh (autosync)
- cancel -> autorefresh (autosync)
- start -> autorefresh (autosync)
- abort -> autorefresh (autosync)
- complete -> ??? (I've missed the opportunity to test the completion after a missed day as the debug menu is gone =)

After second thought, I believe it maybe something with missing a day (it does notify "please refresh"), not actually with quest completion. I'll test it with normal cron later and will report back

**Comment by ghost** [comment]
Update on completing a quest:
- +progress +missed_day - manual sync - completion modal and no autosync
- +progress +missed_day - manual refresh - completion modal and Error Unexpected error (config.js:57:11)

I'll test normal cron in about half an hour (if CDS works)

**Comment by ghost** [comment]
@paglias FYI after your test from 15 minutes ago I keep getting quest invitation each time I refresh the page. Accepting or rejecting gives an error "No quest invitation found" or "No invitation has been sent out yet"

**Comment by paglias** [comment]
@GitHubSphinx the quest invitation should clean up itself when the quest finishes

**Comment by ghost** [comment]
@paglias no active quest, but I still see the modal each time I reload a page

**Comment by paglias** [comment]
okay, can you open a new issue?
