### ISSUE TITLE
Issue with getting equipment from the Enchanted Armoire 

### ISSUE THREAD

**Issue by L1st3r** [HabitRPG/habitica#7334]
General Info
- UUID: e177e5a0-2606-40b7-b448-bbc7359ca30f
- Browser: Chrome 50.0.2661.102 m
- OS: Windows 10
### Description

After receiving I believe 4 pieces of equipment out of about 6-8 tries, I now have a streak of at least 8 attempts in a row that did not result in any equipment. There HAS to be a bug here, I realize that it's random, but that is crazy unlucky! 

It's almost as if the code doesn't think I have any equipment left to get out of there (I have 19 pieces in there still to get) and so it's just always giving me XP and food.

**Comment by L1st3r** [comment]
So of course the next two gets were equipment. What are the percents for getting the equipment?

**Comment by Alys** [comment]
Randomness does unpleasant things like that sometimes. If you keep trying, you'll get the gear. 

Note this issue: https://github.com/HabitRPG/habitrpg/issues/5376 -- you might have been given gear on some of the times when it said you hadn't.

You can see the randomness stats here: http://habitica.wikia.com/wiki/Enchanted_Armoire

If you're using Settings > Site > Fix Character Values to give yourself gold before each attempt at using the Armoire (a fair strategy if you're feeling ripped off!), note that the randomness is seeded on your gold balance. If you use the Armoire with the exact same amount of gold as previously, you'll get the same result. So add 101 gold the first time, 102 the second, etc (or 100.1, 100.2 - anything that's a bit different).
