### ISSUE TITLE
make it more obvious that casting skills onto challenge tasks is impossible

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7336]
_edit by admin:_

It is no longer possible to cast a skill on a challenge task and have the effect last, however there is no visual indication of that. You can attempt to cast a skill on a task and then you see an error message and the skill casting is reversed (i.e., the API prevents the skill being cast), but we want that to be more user-friendly.

To fix this issue, we need to modify the web interface so that after you've clicked on a skill, if you hover over a challenge task, the task is not highlighted in green and clicking on it does nothing.

It might also be nice if, when you hover over a challenge task for more than the time it takes to move the mouse past it, then you see a message explaining that you can't cast skills on challenge tasks. That's optional though and if it's not easy to do, it could be done later or not at all.

_end of edit by admin_

---

UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
Browser: Chrome 50.0.2661.94 m
OS: Windows 10 
### Description

Casting Backstab or Pickpocket onto a challenge task is not supposed to be permitted in v3, but it's still possible despite the notification saying otherwise:
![screenshot 29](https://cloud.githubusercontent.com/assets/6640915/15338014/204d3a4e-1c4c-11e6-86a2-194d3527cd34.png)

After a sync, resources are returned, and the task's score presumably is changed as well (though we should double check that, just in case). Note that although there was no notification, it did fix my XP as well:
![screenshot 30](https://cloud.githubusercontent.com/assets/6640915/15338042/3270ec7a-1c4c-11e6-835f-beb9159d64f1.png)

I imagine the ideal is to prevent the skill from being cast on challenge tasks altogether, perhaps by graying them out or using a red outline on hover/target. 
#### Console Errors

`https://v3.habitica.com/api/v3/user/class/cast/backStab?targetId=dad01f87-c352-4716-b3b9-5d9a8a2b18e0 Failed to load resource: the server responded with a status of 400 (Bad Request)`

**Comment by Alys** [comment]
Checking task values for the test site can be done with [this version of the Data Display Tool](http://oldgods.net/habitrpg/ddt_for_v3_site_using_APIv2.html) -- see the Task Overview section.

**Comment by quin-jay** [comment]
@Alys Ah thank you, this'll come in handy! Just to make sure -- The only skills that actually change task value are Brutal Smash and Searing Brightness, right? There's no universal score increase just for targeting on a task?

**Comment by Alys** [comment]
@lynnyliz That's correct!

**Comment by quin-jay** [comment]
@Alys Schweet, I'll get to testing and post an update here in a few minutes (not to overwhelm y'all with emails... :grimacing:)

**Comment by quin-jay** [comment]
I wasn't able to test Searing Brightness because of [an earlier issue](https://github.com/HabitRPG/habitrpg/issues/7210) that's still present for me. But it looks like Brutal Smash didn't create a persistent change in task value -- it turned the challenge task blue until I synced again, at which point it became green and I got my mana back. So we're all good there!

**Comment by paglias** [comment]
yeah we should block this from the UI... in the meantime I made a change so when an error like this occurs it'll automatically sync the user without a manual reload

**Comment by paglias** [comment]
Going to be a change for after v3

**Comment by quin-jay** [comment]
Now that Searing Brightness is working for me again, I can confirm that the skill does not change challenge tasks -- neither in color nor in score. Also, it didn't do the thing Pickpocket was doing, where it looked like it DID work on challenge tasks until I synced or refreshed. 

I just checked Pickpocket again, and @paglias your automatic sync works beautifully: XP, gold, and mana are immediately returned to where they should be, so it's immediately clear that casting on challenge tasks isn't a thing you can do (ie the potential for confusion is pretty much gone now). Definitely works as a stopgap until the UI changes are in place.

The only thing I might change is in the string of the 'error'/warning notification itself: Right now it says "Casting a skill on challenge tasks is not supported," but I think "allowed" might work better. Just my 2¢, and obviously that's a low priority, so feel free to ignore it.

**Comment by Alys** [comment]
I agree on "allowed" - it's much more natural language. I'll push a fix.

**Comment by Alys** [comment]
@paglias Two tiny text changes which I did as a direct commit since they're so small. Tell me if you'd prefer that not be done for api-v3. https://github.com/HabitRPG/habitrpg/commit/b9d55e35620ba6b7e56493d8cb3c15e69cb4bb1c

**Comment by quin-jay** [comment]
Does this commit add UI indications that you can't cast skills on challenge tasks? I think that's what this ticket was left open for. I couldn't find it in the commit but there was a lot to filter through :smirk:

**Comment by Alys** [comment]
@lynnyliz It does not. Thank you! I was wrong to close this. I'm about to edit the top post to indicate what still needs to be done.

**Comment by quin-jay** [comment]
@Alys Ah, good tip! Next time there's still work to be done on a ticket I'll edit the top post so that it's easily noticed without rereading the entire thread :)

**Comment by Alys** [comment]
This will be covered by https://github.com/HabitRPG/habitrpg/issues/2470 "Invalid spell targets shouldn't provide green highlight" so I'm closing this one. I've copied notes about it to the top post on that issue.
