### ISSUE TITLE
API v3:  Error message selling potions

### ISSUE THREAD

**Issue by CloJo** [HabitRPG/habitica#7338]
General Info
- UUID: 99463fab-e36e-4f8b-87f6-a6f925850ed8
- Browser: Safari
- OS: OSX Yosemite v10.10.5
### Description

Selling potions returns the error message "Key not found for user.items hatchingPotions"  Potion number is decreased by one and gold is properly increased.

**Comment by Memry** [comment]
I was able to sell potions earlier with no issues.

UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
Chrome Version 50.0.2661.102 m
OS: Windows 7

**Comment by paglias** [comment]
Probably due to a sync error, reopen if it's not working
