### ISSUE TITLE
[API v3] Party notifications go to "guild" url but otherwise function fine

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7339]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Mozilla Firefox 46.0.1
- OS: Windows 7 Professional Service Pack 1 (via Bootcamp on a late-2011 Macbook Pro)
### Description

Instead of going to https://v3.habitica.com/#/options/groups/party (what the main site goes to from a notification), the notification that pops up (i.e. via a boss strike or a skill/buff) goes to the group id of the party in question, i.e. https://v3.habitica.com/#/options/groups/guilds/d9796b59-2c12-4774-aad9-5595ed118d91

Outside of that, it _seems_ to function entirely like the party page (other than the fact that the guilds tab is highlighted in the bar above it), but I figured it still should be brought up here.
#### Console Errors

None that I could see.

**Comment by ghost** [comment]
@citrusella wow thanks for reporting it!

It helped me trace the bug from https://github.com/HabitRPG/habitrpg/issues/7323

START A QUEST BUTTON doesn't work if the party is opened via the options/groups/guilds/id address: https://v3.habitica.com/#/options/groups/guilds/e3565aa7-2917-4460-9716-c930e4fd778d

FYI @paglias

**Comment by paglias** [comment]
@GitHubSphinx Yay, I noticed that too and a fix is coming soon, thanks!
