### ISSUE TITLE
Adjusted browsing times/days and still being docked

### ISSUE THREAD

**Issue by emilysalmon** [HabitRPG/habitica#734]
I have tried to set my browsing tracking to allow for free browsing in the evenings and on my days off, but it still docks me points regardless of the day/time. In frustration, I even went so far as to remove Facebook from the list of "vice" sites, but STILL I'm being docked for it. Fix this please?

**Comment by wc8** [comment]
It seems this is a [Chrome Extension issue](https://github.com/lefnire/habitrpg-chrome/issues), no?

**Comment by emilysalmon** [comment]
YES thank you. Looks like an ongoing problem...

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
