### ISSUE TITLE
couldn't select the class of my character - closed window by mistake

### ISSUE THREAD

**Issue by ivamir** [HabitRPG/habitica#7340]
General Info
- UUID: 
- Browser: 
- OS: 
### Description

I couldn't select the type of my character. I wanted to be a Rogue and now there is no way to select it as the windows closed by mistake. How can I select the character I want when I didn't select any and I've closed the window by mistake?

**Comment by Alys** [comment]
Reload the website. If that doesn't give you the class change button again, tell us and please provide the User ID as requested in the issue template. To find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by ghost** [comment]
I might be misunderstanding the question, but I believe there's the "Enable class system" button in the right column of the page "[Avatar stats](https://habitica.com/#/options/profile/stats)" which should bring up the window to choose class. Tip: click an icon of the class in that window (as the names of classes are links to the wiki descriptions) and then confirm your choice clicking the Select button
