### ISSUE TITLE
[API v3] Public guild with no members is still on the list

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7343]
_Originally reported in the Tavern Chat by @Memry but it seems I can't find the corresponding issue on GitHub, sorry if it's duplicating another ticket_

A guild with no members is still on the list of public guilds, e.g. https://v3.habitica.com/#/options/groups/guilds/870e2ca0-30b1-49df-9107-75188a58cb00

When trying to access an abandoned party, e.g. https://v3.habitica.com/#/options/groups/guilds/d0bc616f-8bca-41ee-824b-a5a42fa5c9de I get "group not found error" as expected.

**Comment by Alys** [comment]
Ah, that's actually okay! Public guilds aren't automatically removed when they have no members because it's possible for new members to join.

It's only private guilds and parties that are deleted when the last member leaves. :)
