### ISSUE TITLE
[API v3] Redirected to party after inviting a user to a guild (and possible issues with email invitiation)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7345]
General Info
- UUID: several
- Browser: FF 46.0.1
- OS: win10
### Description

Inviting a user to a guild works, but then the page refreshes and I'm taken to https://v3.habitica.com/#/options/groups/party.

Besides, it seems that I'm not getting invitations by email (I'm not creating a separate issue, because I'm not sure that email features are supposed to work - I'm not getting any emails from v3 beta)

**Comment by citrusella** [comment]
> I'm not sure that email features are supposed to work - I'm not getting any emails from v3 beta

I felt the need to mention when I read this that I've gotten email notifications for private messages at least.

**Comment by paglias** [comment]
@GitHubSphinx can you invite me to a guild?

**Comment by ghost** [comment]
@paglias It's any guild for me and my second testing account

You had been invited to a private guild and I've invited you to another one just now

**Comment by GitHubSphinx** [comment]
You had been invited to a private guild and I've invited you to another one just now

**Comment by paglias** [comment]
Hmm not sure why but I'm not getting any email

**Comment by ghost** [comment]
nononono. I've invited you with your UID. What email should I use?

Added: I've sent invitation to the email you usually use

**Comment by GitHubSphinx** [comment]
Please check the one you usually use to contact me

**Comment by paglias** [comment]
@GitHubSphinx my UID is linked to that email, it's probably something wrong with the code that send emails, we'll check later, now I'm having problems logging in to our email provider

**Comment by paglias** [comment]
Fixed, will go live later

**Comment by ghost** [comment]
I've just tested it
- no redirect (OK)
- got e-mail notification when invited by email (OK)
- didn't get email notification when invited by UID (FAIL)

**Comment by ghost** [comment]
Just to confirm about email notifications:
- challenge won - OK (as an example of other notifications working)
- invitation to a guild via email - OK
- invitation to a guild via UID - invitation is shown in Habitica OK, email notification FAIL

**Comment by paglias** [comment]
Fixed, test in one hour and it'll work
