### ISSUE TITLE
Danger zone (delete and reset account) may need password protection

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7346]
It struck me when dealing with multiple testing accounts: deleting or resetting the account doesn't require the password. So anyone can reset or delete account if they find a device with Habitica page opened and user signed in. It just doesn't feel right.

Suggestion: confirmation modal may have two text fields:
_Confirm your action_: **_DELETE**_ or **_RESET**_ _(typed in)_
_Confirm your password_: `*******` _(typed in)_

I believe it may result in a hundred of abandoned accounts with forgotten passwords but may save one account from accidental or malicious deletion or reset. 

[Post API v3] [Suggestion - discussion]

**Comment by paglias** [comment]
@GitHubSphinx thanks! This reminded me of https://github.com/HabitRPG/habitrpg/issues/7350

**Comment by quin-jay** [comment]
I just tried to delete a test account from the v3 site (I'm pretty sure it'll be deleted eventually anyway, but you know, just in case). It gave me the old confirmation modal and had me type `DELETE` into a text box, but when I clicked the confirm button I got an error notification that said "Missing password" as well as a console error:

```
(anonymous function) @ angular.js:9814sendReq @ angular.js:9615serverRequest @ angular.js:9331processQueue @ angular.js:13171(anonymous function) @ angular.js:13187Scope.$eval @ angular.js:14384Scope.$digest @ angular.js:14200Scope.$apply @ angular.js:14489(anonymous function) @ angular.js:21394o.event.dispatch @ jquery.js:4371r.handle @ jquery.js:4057
angular.js:9814 DELETE https://v3.habitica.com/api/v3/user?userV=39 400 (Bad Request)
```

It looks like we've told the site that we need a user's password to confirm the action, but haven't provided a place to enter it. Is that still in the works, or am I seeing a bug?

**Comment by paglias** [comment]
It looks like we've updated the delete method to ask for a password but forgot to update the UI!
