### ISSUE TITLE
[API v3] Display name inexplicably changed to "Anonymous"

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7352]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Mozilla Firefox 46.0.1
- OS: Windows 7 Professional Service Pack 1 (via Bootcamp on a late-2011 Macbook Pro)
### Description

My display name changed from "citrusella, the serving wench" to "Anonymous" for no clear reason. Login name and info remains normal. This may have coincided with my getting a notification of invitation to a guild on v3 via the old HabitRPG app somehow (but I don't think that did it, since my name still read right when I posted in guild and accepted the invitation via the v3 site), or it may have happened with my getting booted from that guild to test if the notification would appear again (it didn't, but all these weird factors surrounding my account now make me wonder if that's the only reason it didn't and it would if I fixed things and got invited a _third_ time). I was definitely renamed after having joined the guild a second time, though I'm not sure that's what **caused** the rename.
#### Console Errors

Nothing, but I didn't think to check the first moment I noticed it.

**Comment by paglias** [comment]
Fixed, it happened when booting a user! Thanks foe the report, it was difficult to spot
