### ISSUE TITLE
[API v3] After quest is started quest box becomes empty

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7356]
Refresh fixed @TheHollidayInn

**Comment by TheHollidayInn** [comment]
How did you start the quest?

**Comment by paglias** [comment]
Sorry, not started, I invited the party sign the Start a quest button
Il 18 mag 2016 6:40 PM, "Keith Holliday" notifications@github.com ha
scritto:

**Comment by ghost** [comment]
I really don't know if it's related, so please take it for what it's worth.

When testing for https://github.com/HabitRPG/habitrpg/issues/7332#issuecomment-219986340 and https://github.com/HabitRPG/habitrpg/issues/7332#issuecomment-219988758 I've seen it a couple of times but only in some combination of the following conditions:
- start a quest as normal
- +progress and +missed_day from debug
- f5'ed to refresh, get an error
- attempt to initiate a new quest
- autorefresh happens, but quest box is empty

added:
that's not actually a "combination", but rather the sequence that may also need some external factors to produce the bug

added:
I can't make it happen on a new account in a party of one

**Comment by GitHubSphinx** [comment]
added:
that's not actually a "combination", but rather the sequence that may also need some external factors to produce the bug

**Comment by GitHubSphinx** [comment]
I can't make it happen on a new account in a party of one

**Comment by TheHollidayInn** [comment]
I can't replicate this issue. When I click the start a quest button and follow through with creating a quest, everything updates normally.
