### ISSUE TITLE
Being able to change missed days

### ISSUE THREAD

**Issue by Darwinning** [HabitRPG/habitica#736]
There are some days where I'm not at a computer or not able to get to the internet due to travelling, work, etc. I find it disappointing when I lose health or sometimes even die because I'm away from my computer for a certain length of time. Is there a way to implement a system to go back to previous days?

**Comment by wc8** [comment]
If either of these meet your needs, you can show your interest by voting and share any comments you may have:
- [Rest in Tavern](https://trello.com/c/A2w2orSc)
- [Account Freeze](https://trello.com/c/UqxYFiqG) which includes a possibly enhanced version of [Record Yesterday's Activity](https://trello.com/c/CaAm7APS)

**Comment by wc8** [comment]
Closing for organization, you can still reply back if something was missed.
