### ISSUE TITLE
[API v3] "There is no account that uses those credentials"

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7362]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 46.0.1
- OS: Windows 7 Service Pack 1 (via BootCamp on late-2011 Macbook Pro)
### Description

Get the error in the title when I attempt to do... pretty much anything. Usually two, but sometimes up to eight on a reload of the site. My account still seems to exist, in that it's providing me all the relevant things I should see, though I have no access to the Tavern, a party, or ANY guild. I also can't get mine or any other valid user ID I can come up with to appear on the static user profile screen, i.e. https://v3.habitica.com/static/front/#?memberId=2d6ef231-50b4-4a22-90e7-45eb97147a2c . My tasks all still seem to be there, though, and my avatar shows up as well as all my stats on-site.

It seems to make errors endlessly on the stats page if you sync there, though.
#### Console Errors

401 errors everywhere on the Network page, to the following URLs at least:

https://v3.habitica.com/api/v3/user/
https://v3.habitica.com/api/v3/groups?type=guilds
https://v3.habitica.com/api/v3/groups?type=publicGuilds
https://v3.habitica.com/api/v3/groups/party
https://v3.habitica.com/api/v3/groups/habitrpg
https://v3.habitica.com/api/v3/groups?type=party,guilds,tavern
https://v3.habitica.com/api/v3/challenges/user
https://v3.habitica.com/api/v2/hall/heroes

**Comment by paglias** [comment]
Sorry I messed up with the testing database and right now we don't have a working testing site

**Comment by ghost** [comment]
May we have this issue open maybe to get it somewhere on top for those who browse only the list of open tickets?

**Comment by paglias** [comment]
Good idea

**Comment by lemoness** [comment]
mLab is working on restoring a backup now! We'll keep you posted when it's complete.

**Comment by paglias** [comment]
It should work again. But the data may comes from a backup so your last actions weren't saved
