### ISSUE TITLE
[API v3] Searing Brightness doesn't stick

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7364]
UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
Browser: Chrome 50.0.2661.94 m
OS: Windows 10
### Description

This is an issue I was having this morning, but halfway through writing this report I had to go out and do things for most of the day. Now I'm unable to test this because of the database issue, but it was pretty consistent for me this morning, and I managed to get a couple of screenshots.

When I cast Searing Brightness, it turns my tasks green for a moment, but after the loading bar at the top is finished (as in, after the automatic sync), they go back to yellow. Mana is deducted but the spell's effect doesn't seem to persist. Both versions of the v3 site's data display tool show no changes in task value after casting Searing Brightness, syncing Habitica, and pressing the Re-Fetch Data button.

Immediately after casting:
![screenshot 34](https://cloud.githubusercontent.com/assets/6640915/15381048/01f5ff50-1d4a-11e6-9c89-aa5b1498eab5.png)

A couple of seconds later:
![screenshot 35](https://cloud.githubusercontent.com/assets/6640915/15381053/0777ef2e-1d4a-11e6-8b35-0dec04c874c1.png)

This may no longer be an issue by the time the database comes back online, and I suppose it's possible it was just a fluke to begin with (I know @paglias wasn't able to replicate in [#7210 (comment)](https://github.com/HabitRPG/habitrpg/issues/7210#issuecomment-220089240)). I'll check again tomorrow evening -- I'm traveling for quite a long time tomorrow, so I won't be able to do much with my computer in the meantime.
#### Console Errors

Weirdly (?), none.

**Comment by paglias** [comment]
@lynnyliz could you try again for the last time? thanks!

**Comment by paglias** [comment]
I was able to replicate this

**Comment by paglias** [comment]
Fixed, in 30 minutes it'll be live

**Comment by quin-jay** [comment]
Yep, the skill works now! Thank you :D
