### ISSUE TITLE
Fix small typo on quest notes

### ISSUE THREAD

**Issue by teles** [HabitRPG/habitica#7373]
General Info

UUID: 616cdbe4-edd9-4cf4-8789-dbf2872ae97b
Browser: Chrome
OS: Linux
### Description

There is a small typo in the "Ataque do Mundano, Parte 3: O Lavadeiromante" quest. In portuguese there is no such word "ATRAVE" and the correct would be "ATREVE".

So, this line 

> "Com um grito ensurdecedor, e cinco tipos de queijos deliciosos saindo de sua boca, o Monstro de Lanchinhoness cai aos pedaços. \"COMO VOCÊ SE ATRAVE!\" ecoa uma voz debaixo da superfície da água. Uma figura com uma túnica azul emerge da água, empunhando uma escova de vaso sanitário mágica. A roupa suja começa a borbulhar da superfície do lago. \"Eu sou o Lavadeiromante!\" ele com raiva anuncia. \"Você tem muita ousadia - lavando meus pratos deliciosamente sujos, destruindo meu animal de estimação, e entrando no meu domínio com essas roupas limpas. Prepare-se para sentir a ira encharcada de minha magia anti-limpeza!\",

should be replaced like this:

> "Com um grito ensurdecedor, e cinco tipos de queijos deliciosos saindo de sua boca, o Monstro de Lanchinhoness cai aos pedaços. \"COMO VOCÊ SE ATREVE!\" ecoa uma voz debaixo da superfície da água. Uma figura com uma túnica azul emerge da água, empunhando uma escova de vaso sanitário mágica. A roupa suja começa a borbulhar da superfície do lago. \"Eu sou o Lavadeiromante!\" ele com raiva anuncia. \"Você tem muita ousadia - lavando meus pratos deliciosamente sujos, destruindo meu animal de estimação, e entrando no meu domínio com essas roupas limpas. Prepare-se para sentir a ira encharcada de minha magia anti-limpeza!\",

I know it's a very small detail.

**Comment by Alys** [comment]
I"m sorry but we can't accept changes to translations through GitHub because they are done in Transifex. Could you please see the _README_FIRST.md file in the directory that this changed file is in? That will point you to documentation about how to help with translations - we'd love to have your help in Transifex!
