### ISSUE TITLE
[API v3] Special potion pets (except floral) only seem to display the ones you've hatched

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7375]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 46.0.1
- OS: Windows 7 Service Pack 1 (via BootCamp on late-2011 Macbook Pro)
### Description

In my pets page (and mounts page), after I've used all of a special potion, the pet spaces on the list for that potion in the stable only show the hatched (or tamed to mount) pets/mounts. (That is, on the pets page, it will not show any black paws, though the mounts page will show paws for animals that are currently hatched pets.) This fixes itself after a "purchase" (in this case adding it to my inventory) and a sync, but it will not fix itself if you sync or refresh while you have no potions of that type. This does not happen with the floral pets.

Sorry if this was a confusing description. XP
#### Console Errors

23:30:38.617 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create1 habitrpg-shared.js:7:4294
23:30:38.795 <source> element has no "src" attribute. Media resource load failed.1 v3.habitica.com
23:30:38.795 All candidate resources failed to load. Media load paused.1 v3.habitica.com
23:30:38.795 All candidate resources failed to load. Media load paused.1 v3.habitica.com

(Last three appear to be specific to the pets page.)

**Comment by SabreCat** [comment]
@citrusella: If I'm following correctly, this is the intended behavior. The black paws are meant to show "this is a pet you could obtain!" That's only true if (a) you have a potion of that type; or (b) the potions are available for purchase. Since Spooky and Peppermint Potions are not currently "in season", the only way you'll see the black paws is by adding one or more of those potions to your inventory administratively.

**Comment by citrusella** [comment]
Ah! I had no idea that was intended behavior, probably because I keep one of each potion lying around after the season ends and have yet to use any of them, so I wouldn't have seen that happen on the production site. I guess I learn something new every day! :smile:
