### ISSUE TITLE
[API v3] Unable to see challenges in Parties.

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7378]
**General Info**
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description
- Create challenge and attach to party.
- Go to Party and unable to challenge (as per image)
  ![Unable to See Challenge in Party](https://cloud.githubusercontent.com/assets/14116069/15422170/67f02922-1eba-11e6-9be6-feaf7b01bf51.png)

But can see in Challenge Page
![Can see challenge in Challenge page](https://cloud.githubusercontent.com/assets/14116069/15422171/67f3639e-1eba-11e6-9d3c-d598c682ce3c.png)

Also able to see challenge if you use the GUID, That is access the party page as a guild page.

**Comment by Alys** [comment]
Confirmed.

**Comment by TheHollidayInn** [comment]
I got this.

**Comment by cTheDragons** [comment]
Noticed it also not working in the Tavern too. New Ticker or with this suffice?

![tavernchallengesnotshowing](https://cloud.githubusercontent.com/assets/14116069/15438194/4b3e3856-1f0e-11e6-8572-c571c749152f.png)

**Comment by TheHollidayInn** [comment]
They are related, so keep it here. Thanks!

**Comment by paglias** [comment]
Fixed, will go love shortly
