### ISSUE TITLE
[API v3] Unable to see who is invited the party

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7380]
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description

In the party page, invite user via UID. 
Unable to see invited user in list.
![partyinvitednotshowing](https://cloud.githubusercontent.com/assets/14116069/15425847/4d518958-1ece-11e6-8a19-0997bb4df762.png)

Can see Anonymous in Guild view.
![partyinvitedshowingviaguildview](https://cloud.githubusercontent.com/assets/14116069/15425846/4d50f6aa-1ece-11e6-9c16-5f09a0f635a1.png)
User name is actually @:alien:

**Comment by paglias** [comment]
Fixed, note that the Anonymous issue will remain on v3.habitica because it requires a migration but is fixed
