### ISSUE TITLE
[API v3] Path shortName is required - if challenge tag isn't at least 3 symbols long

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7382]
General Info
- UUID: -
- Browser: ff 46.0.1
- OS: win10
### Description

Creating a new challenge...
- set no tag - get notification in your default (system?) language (not the one Habitica is set to use) - looks strange
- set tag of e.g. two symbols - get error "Path `shortName` is required" instead of a specified error for this case
#### Console Errors

![scr](https://snag.gy/MVgKCI.jpg)

**Comment by paglias** [comment]
@GitHubSphinx The errors are in your system language because they come directly from the browser validation and we cannot really tweak them

**Comment by paglias** [comment]
Cannot replicate, if I enter a shortName of 2 letters it doesn't let me create the challenge at all. But I'm using chrome, a different browser may behave differently

**Comment by ghost** [comment]
Yes, the challenge is not created. What seems wrong is that I get error
instead of a bubble notification near the text field which is shown on
production. That's not urgent.

**Comment by ghost** [comment]
@paglias you are right, chrome works as expected - shows bubble notification near the text field in both of the below mentioned cases, but...

Firefox and Edge show bubble notification if I don't enter Tag at all.
![scr](https://snag.gy/2Qc9vY.jpg)

However if I enter two symbols, the check in the text field is not processed and browsers fire the error

![scr](https://snag.gy/Wxh0b5.jpg)

As far as I understand (from the fact that translations are handled somewhere else) the text field check is done by a separate (3rd party?) feature... I may say it may have problems in FF and MS Edge.

**Comment by TheHollidayInn** [comment]
FF and MS Edge don't support to number value validation: http://caniuse.com/#feat=input-minlength . Maybe we should change the error message or we could use angular to validate.

**Comment by Alys** [comment]
I'd like to see it validated in a similar way to the other fields on that page so that we can get the nice customised error messages. For example, if you leave out the title and try to save, you get a neat notification explaining exactly what the problem is. In this case, it would be something like "The tag name must be at least three characters long."

**Comment by TheHollidayInn** [comment]
Yea, I agree. 

However, we have this for group errors: if (!challenge.group) return alert(window.env.t('selectGroup')); .

I was just going to clone that in put in a check for shortName. I almost have what you said: 'Short Name must have at least 3 characters'

**Comment by Alys** [comment]
Sounds good!
