### ISSUE TITLE
[API v3] Unable to change party leader

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7384]
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description
- Party was migrated.
- Party is only 7 users
- Trying to assign another user as leader.
- Get Request Entity Too Large Error message
- Party Leader not change
- Can't edit party unless refresh.
- Seems to be related too https://github.com/HabitRPG/habitrpg/issues/1471 but doesn't fit into the criteria. More likely something due to the migration?

**Comment by ghost** [comment]
I was able to change party leader as expected in a new party.

@cTheDragons something you may want to test a bit more (possibly what you've mentioned in the v3 Tavern):
- old leader had notification about a new message in the party
- old leader leaves the party
- notification stays there even if you click it (will result in the error group not found)
- you can clear this notification with the X button

**Comment by cTheDragons** [comment]
Still not able to change the party leader for my migrated leader. Still receiving error above.

Re the notification this was a different error that I was trying to replicate that had nothing to do with parties (or leaving).
