### ISSUE TITLE
Add art credit to old news

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7385]
The Bailey announcement for the Tangle Tree is missing credit for one artist: plumilla! They should be added to the list of artists who contributed to that quest art.

**Comment by Alys** [comment]
I'll do this now.

**Comment by Alys** [comment]
@lemoness Do you want a deployment to production specifically for this? I'm happy to do that if desired.

**Comment by lemoness** [comment]
No, it can go with the next planned one!

**Comment by Alys** [comment]
Also done in api-v3 branch: https://github.com/HabitRPG/habitrpg/commit/d36c514c06428acaee6bdd9e62830de88c848183
