### ISSUE TITLE
[API v3] v2 task update routes should not change _id

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7387]
https://github.com/HabitRPG/habitrpg/blob/d36c514c06428acaee6bdd9e62830de88c848183/website/server/models/task.js#L152

Looks like this would set the `_id` on a task. Is that right?

**Comment by paglias** [comment]
I think it's right. v2 tasks only used id so if the server sends a request to create a task from v2 it'll only include the id and not the _id so the saved _id would be different. Anyway I think Mongoose automatically does this (setting id sets _id too) anyway so we could also remove it and it would be the same
