### ISSUE TITLE
[API v3] not urgent - critical hit notification appeared twice

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7389]
Bug occurred on:
- https://v3.habitica.com/
- a few minutes before I logged this issue (not sure if the latest code has been deployed)
### Description

I marked one Daily as completed and received a critical hit. The critical hit notification appeared twice.

I'm certain it was a duplicate notification, not a separate notification from another event, because that was the only task I had marked completed for some time.
#### Console Errors

none when I opened the console but that wasn't till after the notification had appeared

**Comment by ghost** [comment]
I got the critical hit notification doubled only once. Then the notifications went on as expected only by one at a time

**Comment by paglias** [comment]
Probably the server and the client didn't have the same data. Reopen if it happens again
