### ISSUE TITLE
new timezone is not saved to user document immediately

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7390]
### Description

I suggest that this isn't fixed until after the migration is finished and tested, unless it's a **really** easy, obvious, safe fix.

In the old API v2 website, when your PC's timezone changed and you reloaded the browser, the new timezone was immediately saved to `preferences.timezoneOffset` in the user's document in the database (confirmed by fetching raw data from the database as soon as I reloaded).

On v3.habitica.com, if you change the timezone and reload the browser, you can see the new timezone displayed at Settings > Site (bottom left of the screen), but it is not saved to the database. Reloading and syncing also doesn't save it. You have to mark a task as completed (or presumably do some other action like editing a task) before the timezone will be saved.

This doesn't affect how cron processes timezone changes, so I believe this isn't urgent (and that's why I haven't noticed it before now, although I should have checked what was going into the database). 

However it probably should be fixed reasonably soon, just in case. I don't think this new behaviour could possibly affect anything if the user reloaded and then immediately started using the website to create or complete tasks. But if the user loaded the website just to view their tasks without making changes, and then later cronned by using a third-party tool (e.g., one that adds tasks), cron wouldn't know about the new timezone - in that situation it would have been good for website to have already saved the new timezone to the user document.

Relevant code:
- https://github.com/HabitRPG/habitrpg/blob/d36c514c06428acaee6bdd9e62830de88c848183/website/server/middlewares/api-v3/cron.js#L34
- https://github.com/HabitRPG/habitrpg/blob/d36c514c06428acaee6bdd9e62830de88c848183/website/client/js/services/userServices.js#L502

**Comment by SabreCat** [comment]
By my read, this is something the client would need to do as needed, so I'm pending this for the frontend redesign. If your understanding is different, @Alys, go ahead and flip it back!

**Comment by Alys** [comment]
This issue is no longer happening. Now when you change time zone and reload the page, the change is saved to the database immediately.
