### ISSUE TITLE
[API v3] missing a day via debug gives 500 error after refresh

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7391]
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: ff 46.0.1
- OS: win10
### Description

If I miss a day (dailies not checked) with debug menu and then sync everything is OK.
If I miss a day (dailies not checked) with debug menu and refresh the page without syncing manually it will load with a couple of instances of "Error An unexpected error occurred"
#### Console Errors

![scr](https://snag.gy/fnqp65.jpg)

**Comment by paglias** [comment]
Cannot replicate

**Comment by TheHollidayInn** [comment]
Same, can't replicate. Is there anything else you notice about your set up?

**Comment by ghost** [comment]
@paglias @TheHollidayInn I believe it's OK to just close the ticket as it deals with debug feature and I can't access v3 right now to give it another try
