### ISSUE TITLE
[API v3] Recent completed To-Dos are not displayed on website

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7392]
### Description

No completed To-Dos are displayed in the "Done" column on the api v3 test website, even when ones have been completed very recently.
If you complete a To-Do and then immediately view the "Done" column, you see the To-Do, but it disappears as soon as you sync.
The To-Dos DO exist in the database and ARE returned by API calls. It's just a website display problem.

---

_edit by Alys, 1 June:_

**The bug behaviour and the workaround are:**

When you go to the "Done" tab for To-Dos, you see all your completed To-Dos from the past three days (as intended, and as happened before the Maintenance). However while you're looking at the completed tab, if you sync or if something causes a sync to occur, then all the completed To-Dos will disappear. Syncing again won't bring them back. What you have to do to see them again is reload the site (using your browser's reload/refresh button) and then go back to the Done tab.

The fix should be that when the "Done" tab is active, all completed To-Dos should always be visible.

**Comment by Alys** [comment]
#### Console Errors

none


#### Extra Description

The To-Dos DO exist in the database and ARE returned by API calls. It's just a website display problem.

**Comment by paglias** [comment]
@Alys can't replicate this, if works for me. Note that completed todos are loaded only when you open the Completed Tab so if they don't appear immediately that's the reason. But when I open the Completed tab for the first time a request is immediately dispatched to the site and they appear really quickly

**Comment by SabreCat** [comment]
I saw this in action on production just now. I brought up the Completed To-Dos list; it showed more items than I'm used to, but worked. Then I took another action (a Brutal Smash, in this case), and the entire list vanished.

Hard refresh brings back the list.

**Comment by paglias** [comment]
This happens when the user is synced because user.todos is replaced completely

**Comment by Hus274** [comment]
The api call that is being made when sync is called only calls for the uncompleted todos and then overwrites the entire todos object as paglias said. I've updated the sync method to also call for completed todos. Just want to write some tests before committing.

**Comment by Hus274** [comment]
Actually I'm not seeing any tests around the client side JS files so I'm not sure quite how I would further test this in addition to the manual validation. I'll submit the pull request for now, I can go back and add tests if needed.

**Comment by crookedneighbor** [comment]
We're putting off tests on the client side js until the client rewrite. Just do a lot of manual testing for now.
