### ISSUE TITLE
[API v3] Party notifications not clearing in the browser.

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7393]
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description

**Notification occurs in the party page.**
- Manual browser to the party page; _Notification_ **_does not**_ _clear._
- Using the notification link; _Notification_ **_does not**_ _clear._
- Using the guild link for the party; _Notification does clear._ 
- Manually clearing the link; _Notification clears._

To state the obvious, notification should clear for the first two options as well as the last.

Have confirmed the notifications do clear correctly for both migrated, and new public guilds as well as new private guilds

**Comment by ghost** [comment]
For what it's worth, I've been able to replicate it only for:
- party notification received before migration
- party notification received before leaving a party

**Comment by Alys** [comment]
Also, new chat messages aren't automatically shown when you visit the party page. When you do fetch the messages by clicking the fetch button, then the notification clears.

**Comment by khipkin** [comment]
@Alys I also noticed this issue for messages sent after the update.

Weren't new messages previously loaded automatically? and aren't they still loaded automatically for guilds?

**Comment by Alys** [comment]
@khipkin thanks for the update! Good to know.

Yes, there'll be something wrong with parties specifically that's preventing the messages getting loaded automatically.

**Comment by JerseyEmerald** [comment]
I'm still having this problem with party notifications not clearing in the browser as well.

**Comment by thebat137** [comment]
The version of the problem I'm presently seeing is that if I go to the party page (by any means, including reloading the page when I'm already on it), the new notifications seem to load automatically, but the "new message" indicator only gets cleared if I click the "fetch messages" button.  This generally doesn't find any further notifications beyond the ones I just loaded, but it clears the flag.  I used to have the problem (after the maintenance) where I could only get all the new messages using the fetch button, but that seems to have gone away now.

I dunno if it makes any difference, but I'm in a solo party.

**Comment by ghost** [comment]
This is just about to go under the cut in the Aspiring Socialites guild chat:

> **_Alys**_ Also, when you go to the party page, the messages no longer load automatically, and the new-message notification in the guild/party notification icon won't clear automatically. The workaround is to click the "fetch recent messages" button. We'll get it fixed up so that going to the party page does load and clear correctly.

[memorable]

**Comment by khipkin** [comment]
This has been happening to me for the last few days in other guilds as well, not just the Tavern and my party chat.  Specifically, it has been happening in the [Achieve, Accomplish, Aspire guild](https://habitica.com/#/options/groups/guilds/588519bb-5c2e-4a12-a5a7-8c9f73192f9f).

**Comment by veeeeeee** [comment]
This is happening for me in my party and Tomes of Compelling Significance for this current session. I noticed it yesterday for my party and for Ink Slingers. Yesterday the notifications would dismiss if I clicked through two or three times. Today it seems to take a few more clickthrough attempts before they'll dismiss.

**Comment by JerseyEmerald** [comment]
I'm still having this same problem,  on my computer and Web browser...I log off all the time, chrome is updated

**Comment by khipkin** [comment]
I don't think the fix has been deployed yet.

**Comment by crookedneighbor** [comment]
It has not, I'm about to deploy.

**Comment by crookedneighbor** [comment]
It's been deployed.
