### ISSUE TITLE
[API v3] Data menu in navbar still links to v2 Data Display Tool

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7398]
UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
Browser: Chrome 50.0.2661.102 m
OS: Windows 10
### Description

Whether you click "Data" in the navbar or click the "Data Display Tool" link in the submenu, you're brought to the old DDT which was built with the v2 API. I imagine that'll stop working after the migration and eventual v2 deprecation, so either that link will need to be changed to the v3 DDT instead or the DDT code itself will have to be swapped. This might be on y'all's radar already but I didn't see it in any of the deprecation checklists so I wanted to be sure.

Pinging @Alys because afaict the DDT is her creation

**Comment by Alys** [comment]
That's expected, and not a problem. When the maintenance window is over, the old code in the DDT will be replaced by the new code. The URL won't change so we didn't change the menu link. Thanks anyway! :)
