### ISSUE TITLE
Drag to reorder Rewards column not working

### ISSUE THREAD

**Issue by NoisyText** [HabitRPG/habitica#740]
For Habits, Daily, and ToDo you can click and drag to reorder the entries in each column. The Rewards column will do this the first time, but on the second try it will highlight the text (as it would on a regular text block) and stop trying to move the entry. 

Work around: You can reload the page and it will work but only the first time. Then you have to refresh again to move the next item.

**Comment by NoisyText** [comment]
Sorry, I forgot to mention that I am using Firefox 19.0.2. Thanks.

**Comment by wc8** [comment]
This issue sounds like #324

**Comment by SyntaxPickax** [comment]
I also can't reorder the Rewards column, not even the first time.  I also can't click on any of the reward items. Well, I can, but they are just links directed to habitrpg.com/# which have no effect.

I'm guessing the new heading for my Daily list is not unrelated:
![Screen Shot 2013-03-28 at 6 09 15 PM](https://f.cloud.github.com/assets/1245093/316285/6b78f3d0-980d-11e2-878a-bd3c56940325.png)

:-)

**Comment by wc8** [comment]
@SyntaxPickax are you also using Firefox?
If either of you are familiar with firebug, do you see any errors through it? If so, that may help the developers.

**Comment by SyntaxPickax** [comment]
@wc8 Forgot to mention. No, Chrome on a Mac. I don't see any errors in the JS console.

**Comment by wc8** [comment]
I'm getting en.app.Daily, suddenly, too. No problems with drag & drop, though.
P.S. Fluid browser

**Comment by lefnire** [comment]
this is due to recent translations framework in place. @switz thoughts?

**Comment by switz** [comment]
Hmm, no idea why this is happening. Should we disable translations for now?
fwiw, I'm not seeing it.

**Comment by switz** [comment]
Okay for some reason beta.habit has Daily and habit.com has Dailys. So someone must have changed something recently.

**Comment by lefnire** [comment]
yeah, let's disable but leave the framework files in place?

**Comment by paglias** [comment]
This should be working now.
