### ISSUE TITLE
After maintenance, my party was disbanded?

### ISSUE THREAD

**Issue by jlriddell** [HabitRPG/habitica#7408]
**EDIT FROM MODS:
If you are having this issue, simply reload the page to get the latest code, and your party will reappear! Let us know if you have any more trouble.**

---

General Info
- UUID: 1edcea2f-2576-4da1-a11e-45c9104b34bc
- Browser: Chrome
- OS: Microsoft 8

Description
I was in a 2 person party before the maintenance, and after maintenance, my party no longer exists. I was one day away from defeating my current boss D: 
My other party member was resting in the Inn and wouldn't have disbanded the party.

**Comment by lemoness** [comment]
Hi there! The good news is that this has an easy fix. Simply reload the page to get the latest code, and your party will reappear! Let us know if you have any more trouble. 

Devs: I am leaving this open for now so that people can see the fix.

**Comment by jlriddell** [comment]
Thanks lemoness! I was about to update that I was only in a party on certain pages.

**Comment by Alys** [comment]
Closing this because we've also been putting instructions to the users in https://github.com/HabitRPG/habitrpg/issues/7429 (sorry @lemoness).
