### ISSUE TITLE
Due Date Option Unavailable When Cloning Challenge

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7410]
I just tried cloning a challenge. When I went to add a due date I noticed that option is not available (only difficulty can be set). I've tried this on both a tablet (latest iOS, Safari)) and a desktop computer (latest El Capitan, Safari).

**Comment by Alys** [comment]
I'm pretty sure this is a side-effect of not being able to edit challenges and so will be fixed when https://github.com/HabitRPG/habitrpg/issues/7320 is fixed, but I'm leaving it open in case I'm wrong. It should be tested again after https://github.com/HabitRPG/habitrpg/issues/7320 is closed.

**Comment by ghost** [comment]
This was actually fixed (deliberately, I thought so I didn't come back to Github). Doesn't seem to be an issue anymore.
