### ISSUE TITLE
Update kicked me from my Party

### ISSUE THREAD

**Issue by Aurora020** [HabitRPG/habitica#7411]
After the latest update I logged on and I was no longer a member of my party, The Lone Rangers. My party leader always messages people before he kicks them and would have notified me if there was a problem. The Party page does not let me request to rejoin my Party but I have messaged our leader and asked that I be invited back. I have also had this issue with my Iphone IOS. The app does not sync up with the website and it says that I am not a member of a party when I have been able to log in on my laptop and access my party's page.

**Comment by Alys** [comment]
This is probably just a display glitch. Please reload your party page a couple of times. If that doesn't put you back in the party, we'll need to know your User ID - please see the Help > Report a Bug instructions for that.

**Comment by TahriTahri** [comment]
I have the same problem, I've definitely lost my party. Tried reloading it a bunch of times. My user ID is 1a70a40f-b50e-4974-8386-cbcf97ac378f

**Comment by cTheDragons** [comment]
@TahriTahri Did you try logging out and clearing your cache and logging back on? Some users have found this is necessary to clear out any bad data sitting in cache.

It likely to be linked to this [issue](https://github.com/HabitRPG/habitrpg/issues/7408)

**Comment by TahriTahri** [comment]
It seems to have fixed itself? Or someone fixed it for me? Thanks mysterious party fixer!

**Comment by rfabi** [comment]
I was also kicked out of my party. I logged out and back in, but that didn't fix it. I've also been re-invited to the party, but the invitation won't work. User ID: 77cf781b-8a0d-4bb5-a06b-d88186a9cb34

**Comment by Alys** [comment]
@rfabi I've put you back in your party and quest. Please tell me if anything doesn't look right! Tomorrow, after your Dailies have reset, please go to party chat and look for a message saying how much damage you've done to the quest boss. If you're on the website, you might need to click "fetch recent messages" before it appears. If you don't see that message, please tell us!

**Comment by rfabi** [comment]
@Alys thanks! I am back in my party, but it looks like I didn't do any quest damage (even after clicking fetch recent messages).

**Comment by Alys** [comment]
That's really odd. :( It looks like you have gone through a daily reset since I added you back to the party, and I can't see anything wrong with how your quest information is set up, so I'm not sure what went wrong. I'll sleep on it and look at it again tomorrow. If you do make quest progress before then, please let us know!

**Comment by Alys** [comment]
@rfabi I still can't see anything wrong. :(  Please post again after your next daily reset and tell me whether you made progress or not.

**Comment by rfabi** [comment]
Will do, thanks @Alys!

**Comment by Alys** [comment]
@rfabi I think this might be a similar problem to yours: https://github.com/HabitRPG/habitrpg/issues/7470

If you have time, could you please read that issue and tell me if you've seen any of the things reported there? If you could put your comments on that issue, rather than this one, that would help us track that particular problem in one place.

**Comment by Alys** [comment]
@rfabi I'm closing this because when I was investigating your account again to try to find the problem, I noticed that you are now making progress on the quest.
