### ISSUE TITLE
Unselected tags are being added to new tasks and tags cannot be removed from new/existing tasks

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#7412]
# System

UUID: fedc44cb-088a-4bc8-8f4f-3e6a1882f042
Browsers: Safari, FF, Chrome 
OS: OS X 10.11.4

The browser seems to 'accumulating' tags that were previously selected in the tag filter on the page so that new tasks created have all the tags that were previously selected, even if they are no longer highlighted. Refreshing the browser clears the accumulation so that new tasks added don't have multiple tags. But it is not possible to remove a tag from a task once it has been added.
# How to reproduce:

1) Clear cache and reload the page.
2) Select multiple tags.

<img width="1439" alt="screen shot 2016-05-22 at 3 13 18 am" src="https://cloud.githubusercontent.com/assets/101778/15452840/38849378-1fcb-11e6-8e6d-caa0aef70f60.png">

3) Unselect the tags.
4) Select only one tag, and create a new task.

<img width="1439" alt="screen shot 2016-05-22 at 3 11 50 am" src="https://cloud.githubusercontent.com/assets/101778/15452834/f69868c2-1fca-11e6-93ed-eb7592653962.png">

5) Open the task to see the tags and note that all of the tags previously selected are on the task (there should be only one tag, but instead there are 5)

<img width="364" alt="screen shot 2016-05-22 at 3 13 31 am" src="https://cloud.githubusercontent.com/assets/101778/15452841/3ef0e900-1fcb-11e6-9b5d-62f51b883020.png">

6) Deselect the unwanted tags and save the task.
7) Reopen the task and note that the unselected tags are still selected.
8) Refresh the page. Note that no tags are selected in the tag filter at the top of the page (this is a new behavior -- previously it was possible to reload the page and not lose the tags that were selected)
9) Select one tag and create a new task.
10) Open the task to see the tags and note that now it has only the one tag that was selected.
11) Deselect the tag and save the task.
12) Reopen the task and note that the unselected tag is still selected.
## Console Errors:

None, but there are several unrelated warnings
<img width="499" alt="screen shot 2016-05-22 at 3 21 12 am" src="https://cloud.githubusercontent.com/assets/101778/15452901/7ce22b92-1fcc-11e6-86c5-3b782d3a1023.png">
<img width="496" alt="screen shot 2016-05-22 at 3 22 18 am" src="https://cloud.githubusercontent.com/assets/101778/15452902/7cf3b8ee-1fcc-11e6-8619-c3bab1f6cff7.png">

**Comment by Alys** [comment]
I've confirmed that I can't remove tags from a task by the normal method (as described by kamni). 

However if I open the task to edit it, click on the checkbox of the tag that I want to remove, and then **immediately** click on it a second time - i.e., basically do a double-click on the checkbox - then I see a red error message "No tag item was found with given id" and a sync occurs and the task editing form closes, but when I check the task, that tag is now no longer selected.

So there IS a workaround that allows you to edit a task to remove a tag, but it's not intuitive. @kamni I'd be interested to know if that works for you.

I've also confirmed the rest of kamni's report: the browser is 'accumulating' tags for adding to new tasks.

**Comment by kamni** [comment]
I can confirm that if I immediately click on it a second time, I get the error message, but the tag is removed once the page refreshes. 

On a side note, the double-clicking on the checkbox also replicates the behavior in #7413, which deselects all selected tag filters on page refresh.

**Comment by ReveWeber** [comment]
My UID: e8221ba8-e0fa-4a6b-9eb1-d1ba9724bbbf
I have this same problem with Chrome on Mac OS 10.11.4, and the double-click workaround fixes it for me as well; in fact without refreshing the page it automatically closes the To-Do's panel and when I reopen it only the intended tag is checked. The only thing showing in my console is a moment() deprecation warning, but a different one from kamni's.
<img width="708" alt="screen shot 2016-05-22 at 12 35 56 pm" src="https://cloud.githubusercontent.com/assets/11982927/15455152/db1fca96-2019-11e6-9874-138b55e811fc.png">

**Comment by kellarules** [comment]
Also encountered this problem and the work around work for me as well.

**Comment by ShulamitLH** [comment]
I am having the same problem in Firefox. I tried clearing the cache and reloading, but that doesn't fix it.

**Comment by vgbandit** [comment]
Same thing for me. My UID: df66dbf9-8e2a-45d2-8e26-ce9549a40928. I use Google Chrome on my Mac.

**Comment by Memry** [comment]
I have been having that problem in Chrome as well.  I am having another problem with tags and it was suggested the problem might be related.  My tags won't stay in order.  I used to be able to arrange my tags and the next time I opened my account the tags were in the same places as before.  Now they routinely rearrange on me.  And not always the same way.  I'm never entirely sure which tags will be where when I first open Habitica.

**Comment by jcmoore65** [comment]
Same issue. Chrome Browser. Windows 10 OS.

I encounter it by:
1. Filter by a tag
2. Create a new To-Do
3. Observe the new item is tagged 
4. Edit the item to clear the tag
5. Observe the item is still tagged

**Comment by ShulamitLH** [comment]
I'm having the same issue, though the workaround helps (double-clicking on the unwanted tag and letting Habitica sync). I'm now having a related problem, though. If I select a tag and then mark something off or reload, that tag is no longer selected. This is a problem when I want to quickly mark off several things filtered by that tag. It's also a problem on the Sabbath (I have a Sabbath filter/tag) when I want most of my to-dos to not show. It's rather disconcerting when that gets unselected multiple times during the day, exposing me to things I do not want to show that day.

**Comment by Alys** [comment]
@ShulamitLH We have that problem of selected tags being cleared reported at https://github.com/HabitRPG/habitrpg/issues/7413 ("Clicking sync (or doing other activities) removes selected tags in the tag filter"). You do not need to comment there because we know it affects all players. If you'd like to receive notifications for that issue, you can subscribe to them with the button in the right-hand column on that issue's page.

**Comment by veggiet** [comment]
I have encountered this same issue. The double click workaround worked for me as well. I'm glad I searched github before making a new report.

**Comment by ltorroba** [comment]
Just encountered this issue for the first time. The fix suggested by @Alys works perfectly as described.

Is anyone working on this? Perhaps I could take a look.

**Comment by crookedneighbor** [comment]
Go for it.
