### ISSUE TITLE
Clicking sync (or doing other activities) removes selected tags in the tag filter

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#7413]
_edit by admin: This also occurs when clicking sync._
# System

UUID: fedc44cb-088a-4bc8-8f4f-3e6a1882f042
Browsers: Safari, FF, Chrome
OS: OS X 10.11.4

Doing multiple activities in short succession -- e.g., adding several new tasks or completing several tasks in a row, without waiting for the response to come back from Habitica -- causes the display to re-render/refresh. The refresh is expected behavior; however when the refresh occurs it unselects any tags that were previously selected in the tag filter at the top of the page. This deselection is new and unwanted behavior.
# How to reproduce

1) Clear the cache and reload the page.
2) Select multiple tags in the tag filter at the top.

<img width="1439" alt="screen shot 2016-05-22 at 3 35 27 am" src="https://cloud.githubusercontent.com/assets/101778/15452943/451348de-1fce-11e6-8e23-1189f408fd90.png">

3) Create three dummy tasks

<img width="357" alt="screen shot 2016-05-22 at 3 36 59 am" src="https://cloud.githubusercontent.com/assets/101778/15452946/7bc2041a-1fce-11e6-917e-1e8050fe463f.png">

4) Check them off in short succession, so that the response from Habitica does not have time to return before the next one is clicked. (This may take a few tries to reproduce a lag, or trying other close-succession behaviors like Brutal Smashing several tasks in a row)

5) Notice that the display re-renders/refreshes (expected behavior). Notice that tags that were previously selected are now unselected (new, unexpected and undesired behavior).

<img width="1438" alt="screen shot 2016-05-22 at 3 44 22 am" src="https://cloud.githubusercontent.com/assets/101778/15452974/845bf03a-1fcf-11e6-8766-64cac2ed62f4.png">
## Console Errors

None, but there are unrelated warnings that show up.
<img width="499" alt="screen shot 2016-05-22 at 3 21 12 am" src="https://cloud.githubusercontent.com/assets/101778/15452971/6f0a4542-1fcf-11e6-9252-be00fb368434.png">
<img width="496" alt="screen shot 2016-05-22 at 3 22 18 am" src="https://cloud.githubusercontent.com/assets/101778/15452972/6f1bb7dc-1fcf-11e6-9024-a6d4dcc0b8c1.png">

**Comment by kamni** [comment]
This can also be confirmed by following the workaround provided by Alys of double-clicking a tag in a task. See #7412

**Comment by kellarules** [comment]
I experienced this too except that my tags seemed to de-select at random, like when I navigated away from habitica or occasionally when I went to a page other than the task page. It was never consistent. I always keep two tags selected by default so it's a big difference when they're gone. This has been happening since the recent update.

**Comment by andrewperkins-wf** [comment]
I have seen this as well - I always have one tag selected when on a specific computer, and it will (it seems) randomly deselect it.

**Comment by shervinmathieu** [comment]
It seems not persisting selected tags was an intended change? That is what is written in the code's comments:

> no longer persisting this, it was causing a lot of confusion - users thought they'd permanently lost tasks

Should I still look into this despite that?

Also a very recent commit has removed all usage of localstorage to persist user info https://github.com/HabitRPG/habitrpg/commit/f7be7205e7a7a9e2eb0a9e44f65a8173f16e148e
so "fixing" this would require to revert those changes.

**Comment by jcmoore65** [comment]
Oh please don't let this be the new normal. It comes up in other situations where it doesn't make sense. For instance, if you are a Rogue and cast a spell (Tools of Trade, I believe) it removes the selected tag.

**Comment by SabreCat** [comment]
Tags deselecting mid-session is not intended, no. That comment refers to tags staying selected _across_ sessions--logging into Habitica for the first time in a day and not seeing your entire task list tended to be disorienting.

**Comment by paglias** [comment]
@velezsarain to fix this it should be enough to comment these 3 lines https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/user/schema.js#L111-L113

**Comment by paglias** [comment]
actually, the best thing is to also `plainObj.filters = undefined` here https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/user/hooks.js#L15
