### ISSUE TITLE
Unable to leave closed challenges

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#7415]
General Info
- UUID: 4182cdea-64db-4db4-9713-dc587d86c662
- Browser: Chrome
- OS: Windows
### Description

Seems there are currently no options to stay in or to leave a challenge once it is concluded. This means it is also impossible presently to remove any of the tasks associated with that challenge. Having closed one of my own challenges today, I can verify this is true only of challenges closed before the update. An example:

![image](https://cloud.githubusercontent.com/assets/3580439/15453504/4947744c-2010-11e6-90ba-067249251a81.png)
#### Console Errors

(Not necessary.)

**Comment by TheHollidayInn** [comment]
Does this happen with new challenges for you, @Eiron ?

**Comment by eiron** [comment]
All looks okay to me now.
