### ISSUE TITLE
Enchanted Armoire appears too early and without Ultimate Gear achievement

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7418]
For a new player, the Enchanted Armoire appears before you have bought all the gear for one class.

Example:
1. Create a new account
2. Buy all the Warrior swords (must be all of them).
3. Sync after buying the final sword.
4. The Armoire appears but it tells you that you can't use it: "You can't buy this item."

At this point you don't have the Ultimate Gear achievement and none of the flags associated with the Armoire have been changed, so this is purely a display problem: the Armoire is displayed too early.

**Comment by TheHollidayInn** [comment]
Looking into this. Do you know if your `user.achievements.ultimateGearSets` was set to true?

**Comment by Alys** [comment]
@TheHollidayInn The achievement was not set to true.

**Comment by TheHollidayInn** [comment]
Perfect, I think I know what it is then.
