### ISSUE TITLE
Unable to rejoin a challenge

### ISSUE THREAD

**Issue by Dewines** [HabitRPG/habitica#7419]
I joined the The Great Eclipse (Maintenance Downtime Fun!) challenge before the downtime happened. https://habitica.com/#/options/groups/challenges/2e03c569-d781-4e55-9f61-86797dec9092
This was with my work account. When I logged in this morning, the undone challenge tasks showed the red megaphone icon, but the challenge was still running. I checked off the remaining To-Dos and in order to see what would happen, I left the challenge and opted to remove the tasks. I then thought I'd rejoin, but when I did that, I wasn't added to the list of participants. I've now joined and left a few times and this is what happens.

Join: the number of participants increases from 52 to 53 and the tasks are correctly added to my tasks page. However, my username does _not_ appear in the list of participants, even after refreshing. Counting the participants shows only 30 though the challenge thinks there are over 50 people in it.

On clicking "Leave" then "Remove tasks", the number of participants decreases from 53 to 52 and the tasks are correctly removed from my task page.

If I try to join the challenge using my main account or my writing account, the challenge behaves as it should. Neither of these accounts was in the challenge before or during the maintenance down time but my DewinesAtWork was and that is the account that is unable to rejoin the challenge.

**Comment by Dewines** [comment]
I've just discovered that all challenges (or at least the few I looked at) only display 30 names in the participants list, regardless of how many people are actually in the challenge. I don't know whether this helps you work out what the problem is?

**Comment by Alys** [comment]
@Dewines Thanks! https://github.com/HabitRPG/habitrpg/issues/7422

**Comment by Dewines** [comment]
@Alys I have therefore solved my own problem.My work account _was_ joining the challenge, but because the sorting is no longer based on date of joining the challenge, my work account name wasn't in the first 30 and thus didn't show. DewinesAtWork didn't show in the list whereas my other two accounts apparently pushed @aust out of the challenge. So this issue isn't actually an issue but merely a display issue.
