### ISSUE TITLE
Checking off multiple tasks in quick succession

### ISSUE THREAD

**Issue by jasoncyu** [HabitRPG/habitica#742]
When I do this (usually for two tasks), subsequent tasks refuse to be checked off and give exp/gold until I refresh the page. The checkmark will fill the box but no exp/gold gets added.

**Comment by lefnire** [comment]
Are you able to get exp/gp at all now, or is it just in the browsing
session after you rapid-click? If 1, i'll mark this as crit & investigate,
if 2 I'll mark important I'm come back to

**Comment by jasoncyu** [comment]
After I refresh the page I can get exp/gold again.

On Mar 28, 2013, at 2:38 PM, Tyler Renelle notifications@github.com wrote:

Are you able to get exp/gp at all now, or is it just in the browsing
session after you rapid-click? If 1, i'll mark this as crit & investigate,
if 2 I'll mark important I'm come back to

On Thursday, March 28, 2013, Jason Yu wrote:

> When I do this (usually for two tasks), subsequent tasks refuse to be
> checked off and give exp/gold until I refresh the page. The checkmark
> will
> fill the box but no exp/gold gets added.
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/lefnire/habitrpg/issues/742>
> .

—
Reply to this email directly or view it on
GitHubhttps://github.com/lefnire/habitrpg/issues/742#issuecomment-15616262
.

**Comment by wc8** [comment]
Marking important as you can, with a workaround, get gold & XP
@lefnire I trust you'll upgrade to critical if that's not what you intended.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
