### ISSUE TITLE
challenges display only 30 names in the participant list

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7422]
Ref: https://github.com/HabitRPG/habitrpg/issues/7419#issuecomment-220828710 
"I've just discovered that all challenges (or at least the few I looked at) only display 30 names in the participants list, regardless of how many people are actually in the challenge. I don't know whether this helps you work out what the problem is?" -- @Dewines

Challenges need to display all participants to allow the creators to choose winners fairly.

**Comment by paglias** [comment]
We have to do find a way to do this without killing the database. Some challenges simply have too many members

**Comment by Dewines** [comment]
Generally it's only the Tavern challenges that get very big, but 30 is definitely too few. Even my challenges in small guilds regularly get more than 30 participants.

**Comment by Sulfirh** [comment]
Hey there o/
Same here : the [Clean the Dungeon](https://habitica.com/#/options/groups/challenges/f3af2863-1fec-4e1c-aac0-71bd1fac1e4c) challenge only shows 30 names, and it seems that the others participants (not part of the 30 chosen ones) have a broken challenge icon :/
Is there anything I can do (or tell to the challengers) to help?

**Comment by Alys** [comment]
@paglias Do you think we could increase the limit, even if we can't show all the names yet?

**Comment by Dewines** [comment]
I've had a quick look at the number of participants in various challenges and the Tavern is undoubtedly the biggest culprit in hammering the database. There are a few tiny challenges with less than 10 people, but most have 150-200 participants and the largest is over 1000. There are also a lot of challenges in the Tavern.

Newbies is another guild that attracts large numbers to the challenges, but if it were possible to increase the limit to 200, the majority of the Newbie and Tavern challenges would display all participants correctly.

In the other guilds, however, if you simply doubled the display limit to 60, the majority of challenges in the smaller guilds would show all participants.

**Comment by Alys** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/releases/tag/v3.2.0
