### ISSUE TITLE
IOS Issues with New App: Frequent "Death" and Crashes

### ISSUE THREAD

**Issue by Kgatliffe** [HabitRPG/habitica#7424]
General Info
- UUID: ddb68b6c-296a-4dd2-abaf-dd1f562ac140
- Browser: iOS App
- OS: iOS 9.3.2
### Description

I am using the new iOS app, and appear to have two issues. 
1. Feeding pets causes the app to crash every time.
2. Other activities (like selling excess potions or eggs) are often accompanied by a loss of signal message and then the death screen. All my stats will be zeroed, but I don't seem to be losing levels (not sure about equipment, I recently rebirthed and have a lot of upbought equipment). I _think_ the app might be triggering death when it has trouble connecting to the server, I will have lots of chance to test that hypothesis today and will let you know more.

**Comment by paglias** [comment]
@Kgatliffe hi, can you post this issue in the iOS repository? https://github.com/HabitRPG/habitrpg-ios

Thanks

Pinging @vIiRuS

**Comment by phillipthelen** [comment]
The feeding error is known and fixed, so no additional info will be needed for that. Information about the death screens would be welcome though.
