### ISSUE TITLE
Moving top task to same place causes error

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7426]
General Info
- UUID: 0e1d15f7-f36b-4f15-a9e1-0c31b732dac9
- Browser: Chrome 50
- OS: Ubuntu 14.04.3
### Description

Dragging the top task (including rewards) in a list to initiate a move, then releasing it back at the top of the list causes the following error to appear. It doesn't affect any tasks but the top one.

![image](https://cloud.githubusercontent.com/assets/9433472/15454680/b7e61864-2037-11e6-9193-909c0efadb8d.png)
#### Console Errors

none

**Comment by crookedneighbor** [comment]
This is fixed now. Thanks for reporting it!
