### ISSUE TITLE
Unicode emoji not changing to images

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7428]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 46.0.1
- OS: Windows 7
### Description

Emoji (like, the actual text characters (i.e. 🌃🌈🌄😊 ...though you can't tell here because Github converts them), not things like :emojicode:) are not converting to images like they were doing before the v3 update. Instead they are remaining their text counterparts (or possibly what the operating system displays them as by default).
#### Console Errors

None.

**Comment by crookedneighbor** [comment]
I've opened an issue for this here: https://github.com/HabitRPG/habitica-markdown-emoji/issues/1

Something about the code was causing problems in Firedox. I'm investigating it.

**Comment by crookedneighbor** [comment]
Fixed with https://github.com/HabitRPG/habitica-markdown-emoji/commit/6b6f633a75c92650631b3190a3d5290aa67278b2

Will go out with the next deploy.
