### ISSUE TITLE
Party's member no more in party

### ISSUE THREAD

**Issue by Acedia95** [HabitRPG/habitica#7432]
General Info
- UUID: f0dc7b3a-6edd-4f24-868d-e6c378672277
- Browser:  Chrome, Puffin Browser and App
- OS: Android and Windows 10
### Description

My party's member (her UUID is before than this Description) is disappear from my party, we refreshed the page more and more times, but nothing.
After this description i give my personal UUID and party ID (I'm team leader)

My UUID: 8308b933-e386-4e6b-9b53-e8b9bcec3c8e
Party ID: c002ad19-f886-4e7e-bfd1-2df82f1cca1c

Thanks for your time :D

**Comment by Alys** [comment]
@Shirito I've put her back into your party and quest. Sorry about the trouble!
