### ISSUE TITLE
My friend and I are already in the party?

### ISSUE THREAD

**Issue by Sayuki74** [HabitRPG/habitica#7434]
Hello.
After the maintenance my and my friend's party was kind of disbanded I guess. When I had logged on the page for the first time after update I saw the info that we defeated the boss but then I noticed that we're not in the party anymore. I went on the party's page and it turned out that I'm not in the party and I can only create the new one. I've tried to do so, I invited my friend but then the information that she's already in a party popped out. I've informed her about it, she said that she had the same issue - she can only create new party and can't invite me because I'm "already in a party". Of course I've tried reloading the page (many times), logging out and in, it doesn't help. 

My ID: 277646ea-7343-4187-aa41-f3bf6c49d719
My friend's ID: 2536a422-b40f-4992-81ab-0d08d636976a

**Comment by Alys** [comment]
Sorry about that! You're both back in the party now.

Post again here if you find out that you or your friend didn't receive the quest rewards. I think it was this one: http://habitica.wikia.com/wiki/The_SnackLess_Monster and that page shows what the rewards should be

**Comment by Sayuki74** [comment]
Thank you very much! ^^
And it looks like we received the rewards so now it's all ok ^^
