### ISSUE TITLE
Unable to edit cloned challenge titles

### ISSUE THREAD

**Issue by CloJo** [HabitRPG/habitica#7435]
General Info
- UUID: 99463fab-e36e-4f8b-87f6-a6f925850ed8
- Browser: Safari
- OS: OSX Yosemite 10.10.5
### Description

[//](#): # Cloned a challenge.  Unable to edit any of the challenge's titles to change them for the new challenge.  the title fields are greyed out.  Screen shot attached.

![screen shot 2016-05-23 at 12 40 07 pm](https://cloud.githubusercontent.com/assets/13231001/15459016/0e544232-20e4-11e6-9658-2d757c97e012.png)

**Comment by Alys** [comment]
Confirmed.

If you tell me the challenge URL and the changes you want, I can make them for you.

**Comment by CloJo** [comment]
It's actually a fairly large bit of changing in the to-dos.  By the time I typed them out to you I could just just set it up manually :). Thank you for the offer though!
