### ISSUE TITLE
tasks/dailies/to do list doubled

### ISSUE THREAD

**Issue by Krispy-Rice** [HabitRPG/habitica#7436]
General Info
- UUID: 5c859d2a-d9f2-413b-8152-c1be9f54d88c (Fox.0f.Jade)
- Browser: Firefox/Safari
- OS: Windows 10/iOS9.3.2
### Description

I apologize if this is a known issue; I could not find any similar issues posted.  

After the update on 5/21/16, it looks like most of my tasks and dailes were duplicated.  Many items on my to do list were also doubled, and a lot of items that were already completed and checked off have reappeared.

I tried signing out & back in, as well as restarting my devices, but the issue persists.

Thank you!

**Comment by hairlessbear** [comment]
Man, this is like a trip down memory lane. #5045, #4773, #5012, #4838, and the granddaddy of them all, #4470. It was supposed to be fixed in #4845, but it's possible it came back in the refactor. Hopefully an admin can provide further insight.

**Comment by Alys** [comment]
I think it's more likely that this was a problem that occurred during the migration, rather than an ongoing bug. Duplicated tasks seem to be from challenges and we know there were problems with the challenge migration.

**Comment by Alys** [comment]
@Krispy-Rice Sorry, I should have added:  We're working on a way to try to clean up the challenge migration errors, which should fix at least some of your duplicated tasks.

**Comment by ghost** [comment]
One of my challenges has duplicated tasks (but they weren't duplicated yesterday after the migration), Safe to assume it's the same bug?

**Comment by Alys** [comment]
@Anysia Did you leave the challenge (or did you seem to be forced out of the challenge) and did you then rejoin it?

**Comment by khipkin** [comment]
Not sure if this is related or should be a totally separate bug, but I've been double-counted for my party's quest ever since the migration.  Every day, I collect items twice:
![image](https://cloud.githubusercontent.com/assets/5641207/15468982/9ed34bde-20e7-11e6-9eda-ecd89934a3fd.png)

**Comment by Alys** [comment]
@khipkin That's this bug: https://github.com/HabitRPG/habitrpg/issues/2805

**Comment by ghost** [comment]
@Alys I didn't do anything other than check off Dailies as usual for the challenge (it's one of my private challenges so I also run it and am the only participant).

**Comment by Alys** [comment]
Another report is at https://github.com/HabitRPG/habitrpg/issues/7472 with console errors but I'm not sure they're related.

**Comment by Krispy-Rice** [comment]
@Alys thank you for the info. To clarify, are you saying I should just be
patient?  I don't mind waiting (I'm not sure I have another option, since I
can't seem to delete the tasks myself), but I am concerned about what it's
doing to my daily health. Any suggestions?

**Comment by ghost** [comment]
@Krispy-Rice I only have one challenge duplicated but what I've been doing is noting my HP, XP, MP and gold then checking off all the duplicates, then going into Fix character values and putting them back to where they were. The duplicates still affect damage done to quest bosses but otherwise it's as neutral workaround as I can think of.

**Comment by Krispy-Rice** [comment]
@Anysia... Thanks for that idea.  I'll try it out. :)

**Comment by Alys** [comment]
@Krispy-Rice I'm sorry, yes, just waiting was what I meant. :( Although a fix for not being able to delete broken challenge tasks has been made now. Can you please reload the website and tell us if you're still not able to delete broken challenge tasks?

**Comment by Tister** [comment]
I just deleted my broken challenge task and dailies.

**Comment by paglias** [comment]
I'm assuming this is fixed, comment if it's still happening
