### ISSUE TITLE
all menus are dropped-down, code is showing on tasks page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7438]
General Info
- UUID: d904bd62-da08-416b-a816-ba797c9ee265
- Browser: Vivaldi (Chrome-based)
- OS: Mac OS 10.11.4
### Description

This just happened to me when I was visiting https://habitica.com/#/options/groups/guilds/b422b8a5-8d66-4197-9f91-d4edb8610264
![screen shot 2016-05-23 at 7 40 31 pm](https://cloud.githubusercontent.com/assets/1495809/15466722/4a218a74-211e-11e6-84cb-e366678a3e30.png)
#### Console Errors

Failed to load resource: the server responded with a status of 404 (Not Found)

This was in the network tab for app-00ad4002.js which was highlighted red:

```
General:

Request URL:https://habitica.com/app-00ad4002.js
Request Method:GET
Status Code:404 Not Found
Remote Address:45.79.106.117:443

Response Headers:

HTTP/1.1 404 Not Found
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Mon, 23 May 2016 09:37:32 GMT
ETag: W/"3b-zI2ygB3A5OSlt0Atu6+COA"
Server: nginx/1.8.1
Vary: Accept-Encoding
X-Powered-By: Express
Content-Length: 71

Request Headers:

GET /app-00ad4002.js HTTP/1.1
Host: habitica.com
Connection: keep-alive
Cache-Control: max-age=0
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36 Vivaldi/1.1.453.59
DNT: 1
Referer: https://habitica.com/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: session-set=true; connect:sess=eyJwYXNzcG9ydCI6e30sInVzZXJJZCI6ImQ5MDRiZDYyLWRhMDgtNDE2Yi1hODE2LWJhNzk3YzllZTI2NSJ9; connect:sess.sig=MyQERMC3Q2BPT5vBaZ7zq2kWRNg; amplitude_idhabitica.com=eyJkZXZpY2VJZCI6IjdhZTRmZjhhLWU3MTYtNDczYy1hNGE3LTRiNTE0YTUxNzk4NiIsInVzZXJJZCI6ImQ5MDRiZDYyLWRhMDgtNDE2Yi1hODE2LWJhNzk3YzllZTI2NSIsImdsb2JhbFVzZXJQcm9wZXJ0aWVzIjp7IlVVSUQiOiJkOTA0YmQ2Mi1kYTA4LTQxNmItYTgxNi1iYTc5N2M5ZWUyNjUiLCJDbGFzcyI6IndpemFyZCIsIkV4cGVyaWVuY2UiOjE5NzcsIkdvbGQiOjE2OTIsIkhlYWx0aCI6NDgsIkxldmVsIjo4MiwiTWFuYSI6MzY3LCJ0dXRvcmlhbENvbXBsZXRlIjp0cnVlLCJOdW1iZXIgT2YgVGFza3MiOnsiaGFiaXRzIjoxMywiZGFpbHlzIjo2MCwidG9kb3MiOjEyMCwicmV3YXJkcyI6MTN9LCJjb250cmlidXRvckxldmVsIjo4LCJzdWJzY3JpcHRpb24iOiJiYXNpYyIsInBhcnR5U2l6ZSI6NCwicGFydHlJRCI6ImFlOWJmM2EyLTgwNTAtNDI1My04NWJhLTE0ZWFiNmIxOWU3MiJ9LCJvcHRPdXQiOmZhbHNlfQ==; _ga=GA1.2.929367226.1462137699; __atuvc=41%7C18%2C29%7C19%2C50%7C20%2C9%7C21; __atuvs=5742cf2dfee296e6000
If-None-Match: W/"164b35-154d8f17337"
If-Modified-Since: Sun, 22 May 2016 14:49:42 GMT
```

@paglias Tell me if there's any other information I should get if this happens again.

**Comment by Eddyboy12** [comment]
That just happened to me too. Just close chrome completely and open it again.

**Comment by vsy** [comment]
Having the exact same issue for several days in a row now. But on the index / home page.

In Safari it happens on nearly every occasion when browsing to the website. While in Chrome it happens occasionally. Restarting the browser sometimes helps, but more often it doesn't.

Error in the javascript console:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (app-873cc63c.js, line 0)`

**Comment by HataKare** [comment]
### General Info
- UUID: b8637b91-9d24-4a00-8054-24654a0eae7a
- Browser: Vivaldi and Chrome
- OS: Windows 10 Pro

### Description

Same issue in both Vivaldi (runs on Chromium) and Chrome. I cannot change my login password or email either. That is super problematic because I reset it, and now it's the auto-generated random numbers.

Note: If I reload the page a few times, the page returns to normal and seems to function properly. The password changing does not though.

**Comment by khipkin** [comment]
This has been happening to me occasionally since I started using Habitica, long before the migration.  It seems to happen when my internet connection is super slow; something doesn't load correctly, so the placeholders never get processed.  It seems page-independent, but it usually happens to me on my tasks page (just because that's the page I always have open in my browser, Chrome).

**Comment by paglias** [comment]
Clearing the cache should fix this!

**Comment by Alys** [comment]
Yes, sorry, I should have specified, it is fixed immediately by a reload, but I was seeing a few other reports of that problem - more than usual! - but without any error details, so I was hoping there was something informative in the console. I really should have said that in my initial post.

If I do see it again, is there anything you want me to look at (or other users when they get this), or should I just close this issue now?

**Comment by HataKare** [comment]
The page glitch is resolved for me now.
