### ISSUE TITLE
Skills list not appearing

### ISSUE THREAD

**Issue by Eddyboy12** [HabitRPG/habitica#7439]
- UUID: 3ea24edb-ded2-4eb6-b279-69c85b3ce1c9
- Browser: Google Chrome
- OS: Windows 8.1

Description
I have just then hit lvl10 and the skills list does not appear however I do have the mana bar.

**Comment by Alys** [comment]
Skills appear at level 11. :)  If you have questions about them either now or when they appear, drop in to Help > Ask a Question from the Habitica.com website's menu!
