### ISSUE TITLE
Can't Login to Beta and Non-Beta alike.

### ISSUE THREAD

**Issue by NinKenDo64** [HabitRPG/habitica#744]
When I input my login details, it loads for a bit, then just drops me back at the anonymous interface again.

Happened first with the Beta site, which I was never able to login to, but now also happening with the vanilla site.

**Comment by horusofoz** [comment]
@CapitalistKenCat Can you try clearing your browser cache or an alternative to see if that has any impact?

**Comment by NinKenDo64** [comment]
Tried it and it didn't help. Beta page reports password as incorrect.

**Comment by horusofoz** [comment]
Can you confirm that is for both using an alternative browser and clearing
the browser cache?

If so can you advise;
OS: (Windows, Mac OSX, *Linux, *BSD, Android, iOS, Symbian, Windows Phone,
etc)
Browser: (Firefox, Chrome, Internet Explorer, Safari, Lynx, etc)
Version: (Version number of browser usually found under Help>About)
Connection Type: (Ethernet, Wifi, 3G, 4G, satellite, etc)

**Comment by NinKenDo64** [comment]
Browsers Confirmed: Chrome v26.0.1410.43 m, Internet Explorer 10 v10.0.9200.16521
OS: Windows 7 x64
Connection Type: ADSL through Ethernet

**Comment by lefnire** [comment]
So it loads your actual account for a bit, but then it turns you into anonymous? I'm wondering if it's not [this issue](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found). How long ago (roughly) did you first register?

**Comment by NinKenDo64** [comment]
As far as I can tell, it never loads my account. It stays on Anonymous the whole time as far as I can see.

**Comment by lefnire** [comment]
so you had an account in the past with data, and now that you're trying to log in it's not allowing you? how long ago did you register originally? i wanna make sure you're not victim to https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found, in which case let's see if we can restore your old account

**Comment by NinKenDo64** [comment]
I had an account a while before the kickstarter closed. Although I've never been able to access the Beta which I contributed for, the non-Beta worked a little while after Beta came out, but has since stopped working.

**Comment by lefnire** [comment]
can you [email me](mailto:tylerrenelle@gmail.com) your user id, username, or email? I can take a stab at the backups in the morning to see what's wrong

**Comment by NinKenDo64** [comment]
Done.

**Comment by lefnire** [comment]
Ken & I solved this offline. Looks like he was unable to progress in login / registration until the "end tour" button was clicked, a very strange bug which I'll be looking into on local.
