### ISSUE TITLE
Gems missing from Guild

### ISSUE THREAD

**Issue by EmyreCaster** [HabitRPG/habitica#7440]
Not long before the Maintenance, I created a guild for my household's day-to-day chores, and subsequently placed someone else in charge of it. After the maintenance, the four gems that were previously in the Guild's account are missing and have not shown back up. 

My User ID is f6f44a3e-2466-4716-9fbd-296cf1736877

The person who I put in charge of the guild is b83dd2da-617f-4cd0-825a-c1a5c11cc26e

Lastly, the guild's Group ID is e2f6fd05-953c-44d4-9285-c525c6060636

**Comment by Alys** [comment]
Did the guild leader use the gems as prizes for challenges? If you don't see any open challenges with gem prizes, did they create one and then close it with a winner, or delete it with no winner?

Do you remember when the guild was created?

**Comment by EmyreCaster** [comment]
No, the gems were definitely not used as prizes, as we've only started using it today, and the Guild only has two members at the moment.

I believe the guild was created on Friday. It may have been Thursday night, though.

**Comment by Alys** [comment]
Thanks for the details! It looks like the gems were removed during the migration - I'm very sorry! I've added them back. If you don't see them immediately, reload the guild's page and post here if they still don't appear!
