### ISSUE TITLE
Date Joined Party Changed? (sort) -- "sort by date joined the party" needs to be removed

### ISSUE THREAD

**Issue by dfecko** [HabitRPG/habitica#7442]
General Info
- UUID: 2fb6b0c7-a7eb-4903-a2a9-2f5a0916de47
- Browser: Chrome
- OS: Win 7
### Description

Did the date joined party attribute change in last weekend's maintenance?  My party is sorted differently this morning.  I'm still sorting my party by date joined, ascending, which I was doing before the maintenance.  For example, UUID 7b4987fd-9c6e-402e-8266-22871d1b3f11 was the last person to join our party, but for me they're showing up in the middle of the list rather than at the end.

Group ID: f3fd093a-09d6-407a-ba05-67facbd2b029

**Comment by Alys** [comment]
Oh yes, I'm sorry about that. :( That sort order won't work any more.

In the past, Habitica didn't actually store the date joined, it just put players into a list, with each new person going at the bottom of the list. The "date joined" sort order put the players into the same order they were in the list.

However the maintenance we did changed how players are linked to parties, and there's no longer a list of them, so it's no longer possible to use that sort order. We should have thought to remove the option. We'll do that soon.

I'm sorry. It's just not possible to implement that sorting option any more.

**Comment by crookedneighbor** [comment]
We could accomplish this by adding a dateJoined property to the user object's party property.

**Comment by librarianmage** [comment]
I can remove it, unless the decision is to add the property.

**Comment by Alys** [comment]
@MathWhiz Let's remove it - thanks! There were never very many complaints about this sort order no longer working, and the fix to make it work again would have taken more time than we had available then. Ping me when it's ready and I'll try to review it.
