### ISSUE TITLE
Unable to invite to a party

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7444]
General Info
- UUID: df8b14f2-e135-4789-970d-5056e99fcc3f
- Browser: Internet Explorer 11.0.9600.18314
- OS: Windows 7
### Description

I attempted to invite user Paladin54 UUID 7195d518-a4e3-48c0-891b-9da787b6eb79 to my party.  (Party Faith Uniting, Group ID: d43e16a2-f005-455f-a7e9-e6b133ca812b)  I received the error message Please reload the page.  I tried again, same message.  I reloaded, same message.  

![image](https://cloud.githubusercontent.com/assets/7385423/15474942/1611d5b6-20bc-11e6-8d99-e99a5b01b109.png)

**Comment by Alys** [comment]
@Memry Thank you for telling us! That user was in a party that did not exist. I've removed the non-existent party ID from their account and you should now be able to invite them.
