### ISSUE TITLE
Party notifications do not go away

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7445]
### Description

I have a continuous notification that there are fresh posts in my party.  The notification does not go away when I check the party.  I have to delete the notification.  This is happening on all my accounts.

General Info
- UUID: df8b14f2-e135-4789-970d-5056e99fcc3f
- Browser: Internet Explorer 11
- OS: Windows 7

General Info
- UUID: 2dc2722b-fdc1-4a36-894f-c22418b67a30
- Browser: Opera version 37.0.2178.41
- OS: Windows 7

General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7

**Comment by quin-jay** [comment]
Do they go away when you click the "Fetch recent messages" button? This may be related to #7393

**Comment by crookedneighbor** [comment]
Yes. this is a duplicate issue.
