### ISSUE TITLE
Cancelling monthly stripe subscription results in internal server error

### ISSUE THREAD

**Issue by vxxed** [HabitRPG/habitica#7448]
### General Info
- UUID: 69b9e5f4-0523-49f3-8cb2-c1d07b362ab8
- Browser: Chrome 49.0.2623.112 m
- OS: Windows 10
### Description

Went to Subscription
Clicked on Cancel Subscription for type "Consecutive Subscription (monthly stripe)"
Clicked "OK" for cancellation confirmation
Shown the following error text on blank white screen:
{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}
#### Console Errors

{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}

**Comment by paglias** [comment]
@vxxed sorry about this! I've fixed the problem. If you try in 24 hours it'll work

**Comment by ghost** [comment]
Same issue here. 
UserID: 1dd87975-da69-465f-b3b1-ef949a5e6f20
