### ISSUE TITLE
JS scripts very slow / "script not responding"

### ISSUE THREAD

**Issue by BelgarathS** [HabitRPG/habitica#745]
Hi,

I am using ubuntu (12.10 and 13.04) and tried all major browsers (Opera, Firefox, Chromium) and all of them are very slow (adding a todo item takes about a minute).
My network connection should be OK (20Mbps and no noticeable lag to server) 
Whenever I add or complete a todo or a daily task the cpu usage goes to 100% and stay there for prolonged period of time (with the browser being the main user of cpu). 
My Cpu is : Intel(R) Core(TM)2 Duo CPU     T7250  @ 2.00GHz (running at 2.00 all the time - performance mode) and I have 4 GB of ram on that machine.
I am addicted to habitrpg already so can you please let me know if I can do any more tests or do something to improve the performance as it is becoming unbearable.

Thank you for a great piece of software.

Best Regards

**Comment by lefnire** [comment]
this is most certainly due to https://github.com/lefnire/habitrpg/issues/165, which as recently gotten worse than before. Let's follow up there

**Comment by switz** [comment]
So this is happening on the server and the client? I'll do some more poking around.

**Comment by lefnire** [comment]
not a client issue, just seems like it because the server is streaming portions to the client slowly while it's working undre 6gb load. Yeah, still an issue (the mem leak)

**Comment by BelgarathS** [comment]
I humbly disagree, even if the server is not responding the client should not go to 100% cpu usage because of it (waiting shouldn't take all cpu cycles) and after further investigation it really looks like the client is waiting for server response (one last or last two calls out of the series - all the others are done straight away) but somehow it manages to kill the thread by waiting.

**Comment by lefnire** [comment]
oh word! I'm sorry, I didn't do your ticket a just reading because I was so quick to attribute it's cause - "slowness.. yep, mem leak."

Ok, re-opening for investigation

**Comment by BelgarathS** [comment]
let me know if I can help, I tested beta and have same issue (both ff and chrome) and in ff I can't even switch tabs unless the call is complete.

**Comment by rixx** [comment]
I've hade this problem forever - I don't even remember if it was different in the very beginning, though it might have been. Have had it on up-to-date Firefox under Android, Arch Linux and Ubuntu Linux.

**Comment by BelgarathS** [comment]
Actually in current betta it seams to be much better on all actions other than initial load (or reload)

**Comment by rixx** [comment]
Same here; the initial load remains problematic, though, and sometimes comes close to crashing my browser.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
