### ISSUE TITLE
When creating challenge, cannot alter task difficulty level

### ISSUE THREAD

**Issue by makkoi** [HabitRPG/habitica#7450]
user ID: b3e66733-ab6f-432f-a052-6fa64585da5a
Browser: Google Chrome Version 50.0.2661.102 (64-bit)
OS: Mac OS X Version 10.9.5

After the update, I have experienced a problem when creating a task when I am the owner of a challenge. I can create a task and edit it, but I cannot change the task difficulty level. It is not greyed out, but I am not allowed to click on it or edit it. I have tried saving the challenge and editing it later, and this is still a problem.

I am not seeing any Java Script errors on screen when this happens.

Despite this, the update did help with other problems I was having with challenges, thank you~

**Comment by cTheDragons** [comment]
I am able to change task difficulty level on new tasks as the challenge owner.

See below image:
![challengetaskcansavewithlevel](https://cloud.githubusercontent.com/assets/14116069/15481113/42394812-216c-11e6-9898-189fee8024b6.png)

The save task can be clearly seen with the level set.
![challengetasksavewithlevelwithouttag](https://cloud.githubusercontent.com/assets/14116069/15480610/d0e526d8-2169-11e6-9b70-0cb90188ca8e.png)

@makkoi  have you tried clearing your cache on your website?

Confirm that tags are not automatically added as per issue:
https://github.com/HabitRPG/habitrpg/issues/7449

**Comment by makkoi** [comment]
I logged out of Habitica, cleared my cache, and logged in, to the same error. I can upload a video of it if you need me to? (it's not visible with screenshots)

I think I already confirmed the tag issue. Do I have to include screen shots or further information?

**Comment by cTheDragons** [comment]
I'm not a dev but video might be good so the devs can see what going on.

**Comment by makkoi** [comment]
@cTheDragons You're very helpful, thank you!

Here's a video of the error that I uploaded onto mediafire. 
http://www.mediafire.com/download/23ahvn2kfucnaja/taskerror.mov
The video size is 9.46 MB, format is .mov

The circular ripples that appear in the video are mouse clicks.

**Comment by ShulamitLH** [comment]
I'm having the same problem both with old challenges that I own and a new one I tried to create to test.

**Comment by ShineAugustine** [comment]
Also having problems with this. I was initially able to select the difficulty levels when setting up the to-do tasks for my challenge, and set all three of the tasks to different levels (easy, medium, and hard). Now all three are mysteriously set as easy and I cannot change their values when I go to edit the tasks. I can open the edit option for the task, everything appears normal, but when I click a different difficulty button nothing happens.

I'm using the latest version of Chrome on Windows 7.

Here is my challenge page if it helps:
https://habitica.com/#/options/groups/challenges/270a4131-43d6-4ac2-b108-56ffaf772ba8

**Comment by Alys** [comment]
@makkoi Your video shows that the error occurs when editing a challenge, and we have that bug reported at https://github.com/HabitRPG/habitrpg/issues/7320

I can't replicate this when creating a challenge - I am able to set the difficulty on tasks in a new challenge as I'm creating it, and the selected difficulty persists when I view the challenge after saving it and after reloading (so the difficulty selection is definitely being saved to the database). I'm going to close this, but if you (or @ShulamitLH) are still finding that you cannot set difficulty when you are first creating a challenge - i.e., before you have clicked the "save" button for the first time), please comment again here.

**Comment by makkoi** [comment]
@Alys Yeah, sorry, the video shows when it's being edited when this happens. It first happened to me when I was creating the challenge, not editing it (I didn't think to create a new challenge).

I just went to create a video example of creating a challenge, but now when I try to create a challenge task, it allows me edit the difficulty. So, it either fixed itself or someone fixed it, which is great! Thanks.
