### ISSUE TITLE
Armoire: incorrect notifcation

### ISSUE THREAD

**Issue by jpazniokas** [HabitRPG/habitica#7452]
Not a big deal, but an interesting hiccup this afternoon.

I clicked on the Armoire (I've already got the month's Armoire items), and I got two messages: I found milk and I wrestled with the armoire for experience.

The milk did show up in my inventory, but when I went to feed that milk to a pet, I got the standard "xxx really likes the milk" and a ";food item not found", or something like that.  (Sorry... missed it.)  I refreshed the page, and the pet's health bar was down where it was before the feeding.

So, a bit of a ghost piece of food.  I figured I'd post it, if it's been happening frequently to others.  First time for me.

**Comment by Alys** [comment]
The Armoire actually didn't give you the milk, but something else, incorrectly reported. See https://github.com/HabitRPG/habitrpg/issues/5376 for details. I'm closing this but you're welcome to ask here if you have questions!
