### ISSUE TITLE
[API v3] Documentation for task scoring has incorrect HTTP method 

### ISSUE THREAD

**Issue by ethack** [HabitRPG/habitica#7458]
### General Info
- UUID: ec488a95-daaa-4fe5-848e-0271e5053fd0
- Browser: N/A
- OS: N/A
### Description

The documentation for scoring a task in v3 of the API says to use `PUT` as the HTTP method.  However, using this returns a 404.  Using `POST` works as expected.

Link to the docs: https://habitica.com/apidoc/#api-Task-ScoreTask

Note: I am using the new UUID as returned by the `GET /api/v3/tasks/user` endpoint. I did not use the `_legacyId`
#### Console Errors

```
curl -X PUT -q --compressed -H 'Content-Type:application/json' -H 'x-api-user: ec488a95-daaa-4fe5-848e-0271e5053fd0' -H 'x-api-key: xxxxx' https://habitica.com/api/v3/tasks/5477e395-c3d2-44d3-90ab-4b39bd574ddc/score/up | jq
{
  "success": false,
  "error": "NotFound",
  "message": "Not found."
}
curl -X POST -q --compressed -H 'Content-Type:application/json' -H 'x-api-user: ec488a95-daaa-4fe5-848e-0271e5053fd0' -H 'x-api-key: xxxxx' https://habitica.com/api/v3/tasks/5477e395-c3d2-44d3-90ab-4b39bd574ddc/score/up | jq
{
  "success": true,
  "data": {
    ...
  }
}
```

**Comment by crookedneighbor** [comment]
Want to open a pull request?

**Comment by crookedneighbor** [comment]
@ethack Never mind, I took care of it.
