### ISSUE TITLE
Can not buy tokens 

### ISSUE THREAD

**Issue by janepernille** [HabitRPG/habitica#746]
I really want to buy a token to buy my golden potion thing for pet - is that not enabled yet, or is it a bug?

**Comment by StanLindsey** [comment]
I've tagged the devs on this feature below, till then try some refreshed. Sorry, Thanks for the bug report though! We'll get it fixed ASAP. 

@lefnire @switz  - I've marked this down as important.

**Comment by switz** [comment]
Not reproducing this. We'll look into it further.

**Comment by switz** [comment]
Clear you cookies and your cache. Should work again.

**Comment by lefnire** [comment]
naw, I'm able to repro this on all my browsers too (even after clearing cache / cookies) - doesn't bring up the stripe modal from the various points in the app that normally would. I wonder if there are too many open modals and JS is wigging out?

**Comment by litenull** [comment]
It works fine for me.

Did you checkout if there are any errors ? SlappyBag got

Uncaught TypeError: Cannot call method 'postMessage' of null checkout.js:602

On Fri, Mar 29, 2013 at 11:14 PM, Tyler Renelle notifications@github.comwrote:

> naw, I'm able to repro this on all my browsers too (even after clearing
> cache / cookies) - doesn't bring up the stripe modal from the various
> points in the app that normally would. I wonder if there are too many open
> modals and JS is wigging out?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/746#issuecomment-15663241
> .

## 

LP, Tomaž :)

**Comment by lefnire** [comment]
Yep, that's the one. `frame` is undefined in checkout.js. It might be related to the redraw issue in the "ads not showing" ticket. @litenull, when this works fine for you - are ads showing ok?

**Comment by litenull** [comment]
No, not really.

The ads are another error:

Uncaught TypeError: Cannot read property 'contentWindow' of null

it seems like the DOM is redrawn and the scripts fail.

On Fri, Mar 29, 2013 at 11:22 PM, Tyler Renelle notifications@github.comwrote:

> Yep, that's the one. frame is undefined in checkout.js. It might be
> related to the redraw issue in the "ads not showing" ticket. @litenullhttps://github.com/litenull,
> when this works fine for you - are ads showing ok?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/746#issuecomment-15663498
> .

## 

LP, Tomaž :)

**Comment by switz** [comment]
@lefnire Derby should only load scripts once. Unless, that is, they're in a require tag, in which case they might be loaded multiple times.

**Comment by lefnire** [comment]
it won't re-draw the `<Scripts:>` section on `app.render()` (when invoked multiple times)? Could be this isn't the issue, I'll keep digging - but the stripe error is quite intermittent, sometimes it works sometimes not

**Comment by litenull** [comment]
Can you do a setTimeout with 10s on the ad script appending so we can see
if we can solve the consistency part ? Just wondering, i dont know how you
add the script stuff.

On Fri, Mar 29, 2013 at 11:39 PM, Tyler Renelle notifications@github.comwrote:

> it won't re-draw the <Scripts:> section on app.render() (when invoked
> multiple times)? Could be this isn't the issue, I'll keep digging - but the
> stripe error is quite intermittent, sometimes it works sometimes not
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/746#issuecomment-15664030
> .

## 

LP, Tomaž :)

**Comment by litenull** [comment]
Oh, the tokens dont work for me anymore. +1 for not consistent

On Fri, Mar 29, 2013 at 11:45 PM, Tomaž Korenika litenull@gmail.com wrote:

> Can you do a setTimeout with 10s on the ad script appending so we can see
> if we can solve the consistency part ? Just wondering, i dont know how you
> add the script stuff.
> 
> On Fri, Mar 29, 2013 at 11:39 PM, Tyler Renelle notifications@github.comwrote:
> 
> > it won't re-draw the <Scripts:> section on app.render() (when invoked
> > multiple times)? Could be this isn't the issue, I'll keep digging - but the
> > stripe error is quite intermittent, sometimes it works sometimes not
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/746#issuecomment-15664030
> > .
> 
> ## 
> 
> LP, Tomaž :)

## 

LP, Tomaž :)

**Comment by lefnire** [comment]
As per some comments here
http://stackoverflow.com/questions/1142861/jquery-append-google-adsense-to-divwe
gotta make sure we're not violating any adsense policies when
appending
google ads to the dome via jquery (currently they're part of the
server-rendered html)

**Comment by litenull** [comment]
OK, not sure if right way, but worth a shot.
Also, its 90% possible <script> rendering is causing problems

On Fri, Mar 29, 2013 at 11:49 PM, Tyler Renelle notifications@github.comwrote:

> As per some comments here
> 
> http://stackoverflow.com/questions/1142861/jquery-append-google-adsense-to-divwe
> gotta make sure we're not violating any adsense policies when
> appending
> google ads to the dome via jquery (currently they're part of the
> server-rendered html)
> 
> On Friday, March 29, 2013, litenull wrote:
> 
> > Can you do a setTimeout with 10s on the ad script appending so we can
> > see
> > if we can solve the consistency part ? Just wondering, i dont know how
> > you
> > add the script stuff.
> > 
> > On Fri, Mar 29, 2013 at 11:39 PM, Tyler Renelle <
> > notifications@github.com<javascript:_e({}, 'cvml', '
> > notifications@github.com');>>wrote:
> > 
> > > it won't re-draw the <Scripts:> section on app.render() (when invoked
> > > multiple times)? Could be this isn't the issue, I'll keep digging -
> > > but
> > > the
> > > stripe error is quite intermittent, sometimes it works sometimes not
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lefnire/habitrpg/issues/746#issuecomment-15664030>
> > > .
> > 
> > ## 
> > 
> > LP, Tomaž :)
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lefnire/habitrpg/issues/746#issuecomment-15664259>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/746#issuecomment-15664369
> .

## 

LP, Tomaž :)

**Comment by lefnire** [comment]
Ok, fixed this particular one (see https://groups.google.com/forum/?fromgroups=#!topic/derbyjs/x8FwdTLEuXo for the solution). Now to try to fix the adsense one
