### ISSUE TITLE
static/api redirect

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7461]
habitica.com/static/api should point to https://habitica.com/apidoc/ with a HTTP response status code 301.

We will also need to update all links on the wiki and elsewhere.

**Comment by cTheDragons** [comment]
Wiki I believe has been completed except for previous posts like
http://habitica.wikia.com/wiki/Thread:39944

Google Search used :
- "habitica.com/static/api" site: habitica.wikia.com
- "habitica.com/static/api" site: habitica.com

**Comment by crookedneighbor** [comment]
Implemented https://github.com/HabitRPG/habitrpg/commit/f9b759ae57278118453edf8264e12a5a2a89e4b9
