### ISSUE TITLE
tests are needed for cron safe mode and cron semi-safe mode

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7464]
This is so that I'm kept accountable for doing this, or at least guiding a contributor through doing it.

In PR https://github.com/HabitRPG/habitrpg/pull/7286, "cron safe mode" was implemented. It causes cron to behave differently than normal, with the differences described here: https://github.com/HabitRPG/habitrpg/issues/7161#issuecomment-218096217

In PR https://github.com/HabitRPG/habitrpg/pull/7462, "cron semi-safe mode" was implemented. It allows cron to behave normally in all ways except that a quest boss does not cause damage, and the the message in party chat when you attack the quest boss explains that the boss has not caused damage.

We need tests for all of that. Current cron tests are in:
- ./test/api/v3/integration/debug/POST-debug_set-cron.test.js
- ./test/api/v3/unit/libs/cron.test.js
- ./test/api/v3/unit/middlewares/cronMiddleware.js

**Comment by cmcarthur** [comment]
Is this able to be picked up? Looking for something to get started with.

**Comment by Alys** [comment]
@cmcarthur Yes, if you'd like to work on this, that would be great! Post here if you have any questions or run into any problems.

**Comment by cmcarthur** [comment]
Great, just got my env set up, working on this over in https://github.com/cmcarthur/habitrpg/tree/cron-tests
