### ISSUE TITLE
New tasks tagged with random incorrect tags

### ISSUE THREAD

**Issue by chrispower115** [HabitRPG/habitica#7468]
General Info
- UUID: d28f85ee-1895-4175-87ad-330e6f294784
- Browser: Chrome Version 50.0.2661.94 m (64-bit) or 
  Vivaldi 1.1.453.59 (Stable channel) (32-bit)
- OS: Windows 10 Enterprise
### Description

When created, New tasks are tagged with random incorrect tags.
EG: New task created with "Work" tag might be tagged by the system with "Home" + "Afternoon".
This happens even when other tags are NOT selected or checked.
Seems to have happened since the maintenance last weekend.

Manually editing the task and removing the unwanted tags sometimes works, othertimes the edit attempt is ignored.

**Comment by Alys** [comment]
Sorry about that! It's this bug: https://github.com/HabitRPG/habitrpg/issues/7412

The top post and comments have some information about workarounds that might help (e.g., reload before creating tasks; double-click a tag's checkbox to remove it).
