### ISSUE TITLE
Challenge Extra Notes Missing in creator's copies of tasks after creating a challenge

### ISSUE THREAD

**Issue by omtigger** [HabitRPG/habitica#7469]
General Info
- UUID: 84c14a15-4d8a-4bf7-a10b-e6bd3ddf0fa1
- Browser: Firefox 
- OS: Windows 10
### Description

Extra notes made in challenge creation are not showing when I go to my "Tasks" screen. Tried reloading tasks, and edited challenge (needed to fix tag anyway) and saved again.

**Comment by Alys** [comment]
As far as I can tell from my testing, this happens only when a challenge creator first saves the challenge - the tasks that are added to the creator's task list at that time don't have anything in the "Extra Notes" field. 

If the challenge creator leaves the challenge, choosing to delete the task, and then rejoins the challenge, the new copies of the tasks do have notes.

If anyone else joins the challenge, their own copies of the tasks do have notes.

**Comment by Alys** [comment]
related: https://github.com/HabitRPG/habitrpg/issues/7449 "Challenge Tags are not automatically associated with Challenge Tasks when creating new challenges"

**Comment by Alys** [comment]
I'm closing this because we've decided to do this instead: https://github.com/HabitRPG/habitica/issues/9248 "challenge creator should not automatically join their own challenge"
