### ISSUE TITLE
Died mysteriously when I went to bed with 50 health, most of tasks checked off, etc

### ISSUE THREAD

**Issue by lunikilo** [HabitRPG/habitica#747]
I woke up this morning and my toon was dead. I went to bed with full health, and most of my tasks checked off, so that shouldn't have happened. What I think is part of the problem is that I set up a lot of new dailies yesterday, and they're missing. I also ticked off some to-dos that are now back in my list. It shouldn't have been a connectivity problem because I always refresh before I check things off, just in case.

**Comment by lefnire** [comment]
let's follow up on https://github.com/lefnire/habitrpg/issues/700 (duplicate)
