### ISSUE TITLE
Mages damage twice every cron in Party since update

### ISSUE THREAD

**Issue by patricedenis** [HabitRPG/habitica#7471]
Hi every one.
### Description

Since update, we found that our magos striked twice every cron on our quest monsters.
It seems like a bug for us as the vilains are fired really quickly with this effect.
Our group ID is the following : 6ef26f59-6fe1-46f7-a942-9cee31a3a47e

Cheers,

Iodor

**Comment by Alys** [comment]
Thanks for letting us know! We're tracking the problem in https://github.com/HabitRPG/habitrpg/issues/2805
so I'll close this issue now. No need for you to comment on the other one - there'll be an automatic link between them. We're working on a fix for this!
