### ISSUE TITLE
Quest damage tripled for party member

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7474]
General Info
- UUID: db190b28-8ce5-422e-8076-d43a62a7b204

Group ID: d71ba110-e2b0-4d12-a0d3-96a83a9f503c
### Description

Couldn't find a description of this elsewhere. Started a quest after maintenance (Treeling). One party member's damage ran normally (1x). Mine ran 3x! Not just a triplicate message in party chat as the boss loss 3x the health.
Edit: screenshot removed for party privacy

This was not a problem with the previous quest (Sabrecat) that was started before maintenance and ended after maintenance.

**Comment by Alys** [comment]
Hi @Anysia : We're tracking this bug in https://github.com/HabitRPG/habitrpg/issues/2805

If you'd like to get email updates you can subscribe to it with the button in it's right-hand column.

**Comment by ghost** [comment]
Additional: I accessed Habitica on my iPad using Safari to trigger cron. I just remembered that the Habituca app was also open (I was trying out the reminders function) but I hadn't used the app since yesterday morning. Habitica is open on my desktop but that computer is idle at night and shouldn't trigger anything (and never has before). The app running in the background on the iPad may or may not be relevant.
