### ISSUE TITLE
Damage to boss issued twice for some party members

### ISSUE THREAD

**Issue by Starfevre** [HabitRPG/habitica#7477]
Since maintenance, for me and one other member of our party on the Treeling quest (but not the third member), the damage done to the boss has been done twice for each day.  From the damage to the boss, it's not just a notification error because twice the damage is actually occurring.

Here is our log:

Starfevre attacks Tangle Tree for 24.8 damage. Tangle Tree does not attack, because it respects the fact that there are some bugs post-maintenance and it doesn't want to hurt anyone unfairly. It will continue its rampage soon! -2 hours ago+1   

Starfevre attacks Tangle Tree for 24.8 damage. Tangle Tree does not attack, because it respects the fact that there are some bugs post-maintenance and it doesn't want to hurt anyone unfairly. It will continue its rampage soon! -2 hours ago+1   

Huh, guess you found a bug 😁 -8 hours ago+1  
 xlb 

I think your damage just counted twice. Which means mine probably did as well. Somehow Elsa escaped. -18 hours ago+1  
 Starfevre 

xlb attacks Tangle Tree for 13.3 damage. Tangle Tree did not attack the party because it was asleep while maintenance was happening. -21 hours ago+1   

xlb attacks Tangle Tree for 13.3 damage. Tangle Tree did not attack the party because it was asleep while maintenance was happening. -21 hours ago+1   

ElsaM attacks Tangle Tree for 32.6 damage. Tangle Tree did not attack the party because it was asleep while maintenance was happening. -a day ago+1   

Did my damage just count twice? -a day ago+1  
 Starfevre 

Starfevre attacks Tangle Tree for 19.4 damage. Tangle Tree did not attack the party because it was asleep while maintenance was happening. -a day ago+1   

Starfevre attacks Tangle Tree for 19.4 damage. Tangle Tree did not attack the party because it was asleep while maintenance was happening. -a day ago+1

**Comment by Alys** [comment]
Thanks for the details! We're tracking this bug in #2805

No need to report it again there because a link has been created between this issue and it. I'm closing this one since we're tracking it in the other one.

If you'd like to get email updates you can subscribe to it with the button in it's right-hand column.
