### ISSUE TITLE
problems with challenges

### ISSUE THREAD

**Issue by ShulamitLH** [HabitRPG/habitica#7480]
Something is wrong with the challenges. I tried editing one I created and own, but I couldn't add any new tasks or change difficulty for any task.

**Comment by quin-jay** [comment]
Related issues: #7450 (owner can't edit challenge difficulty level) and #7320 (owner can't edit challenge). @ShulamitLH Do you want to comment on those threads reporting that you see those bugs too? The admins may close this issue if they think it's too similar to others that have been opened.
