### ISSUE TITLE
Triple quest rewards

### ISSUE THREAD

**Issue by esmanning** [HabitRPG/habitica#7482]
General Info
- UUID: 809d8b43-07a1-49ab-9bb5-ad3ba461688d
- Browser: Chrome
- OS: El Capitan
### Description

I completed the Sabre Cat quest last night and received triple the normal rewards (I definitely got 9 eggs and the achievement x3; I didn't pay close enough attention to GP and XP, but I noticed having a lot more gold today than I expected so I assume those were both tripled as well).

Possibly-relevant background info:
-I'm in a solo party
-I was in the Inn for about a week prior to this, so this was my first cron since before the maintenance

**Comment by Alys** [comment]
I had though this could be related to https://github.com/HabitRPG/habitrpg/issues/2805 (double/triple quest progress messages) but your final boss attack appears just once. It might be a similar mechanism though. 

Thanks for reporting it! I've removed two of the achievements.

**Comment by thebat137** [comment]
I think something similar to this may have happened to me, although I didn't catch it at the time.  I have a solo party, and we were on the Moonstone Chain, Part 1 quest during the maintenance.  I did get the triple quest progress bug (same number of moonstones found three times by me during the first full day after maintenance) but I assumed it was some form of intended compensation for the missed days, so I didn't worry about it.  Then, a day or so later, I completed the quest and started Part 2 and didn't notice any issues.

But today, when I finished Part 2 and wanted to start on Part 3, I noticed I still had the scroll for Part 2.  When I went to check my quest completion logs, my completions were 3 for Part 1, 2 for Part 2, and 1 for Part 3.  As far as I know I've never deliberately done Part 1 without doing Parts 2 and 3 (I think this is only my second run-through of the quest chain, and I'm pretty sure I didn't have any Part 2 scrolls before I started Part 1 this time around).  So I am wondering whether I perhaps got double rewards for completing Part 1 after the maintenance --- two achievements and two quest scrolls.  Unfortunately, I don't have any pre-maintenance records to confirm this with, but nothing else seems to make sense.

UUID: dea8a9e8-c084-438a-9a14-7fe96a73fd0a
Party ID: 33d17c3a-402f-4f29-a7a4-b35925807deb
Browser: Firefox 45.1.0
OS: Debian Linux

**Comment by Alys** [comment]
@thebat137 I've checked in a database backup from just before the maintenance and you had only one quest achievement for each of the Moonstone quests, so since you have three now for Moonstone 1, it looks like you did get the quest rewards and achievements twice. I've removed one of the achievements (you now have two for all Moonstone quests), but I haven't removed anything else.

If you want extra quest scroll(s) removed to reduce clutter, I'm happy to do that, but I'm also just as happy to let you keep it. :)

**Comment by thebat137** [comment]
@Alys, thanks for your help. Please do delete the extra scroll for Moonstone Part 2 as well --- I'd rather not use it, to keep my achievements "even".

**Comment by Alys** [comment]
@thebat137 I've deleted the extra Moonstone 2 quest scroll.

I'm going to close this because we haven't seen any other reports of it and it might have been fixed by the same change that fixed the double/triple quest damage bug. We can always reopen it later if it reoccurs.
