### ISSUE TITLE
[Suggestion] Epic quest (for long-term goals)

### ISSUE THREAD

**Issue by ancientcampus** [HabitRPG/habitica#749]
Tasks now support "due dates". This got me thinking -
Many people have long-term goals that they break up into smaller parts. Example:
-finalize requirements
-build wireframe
-code back end
-code UI
-QA
-publish
(For me, I'm studying for board exams. Others may have fitness goals, writing projects, etc.)

Suggestion:
Allow users to create an "Epic Quest". This ain't no "collect 10 lizard heads", it's a bona-fide "toss the ring into Mount Doom" journey. They select items from their ToDos, specifying one as the goal, and others as objectives along the way. Make a map of a fantasy world (this could be pre-rendered or not), draw the "road" with various objectives (just select random icons like "fortress" and "mountain pass" and "dragon cave", etc) pasted along the map, ordered according to their various due dates. Move the player's icon along the road as time goes on.

You wouldn't need to involve habits or dailies, they're the metaphorical "random encounters" along the way. Although, you could add some kind of "victory stamp" on the road on any day the player completed every daily.

I'd love to try my hand at this, but as I said earlier, I have board exams. :) Maybe in a few months.

**Comment by wc8** [comment]
[Checklists](https://trello.com/c/PJ1iJ413)? Checklists has been suggested as a one way of engaging a [Boss Battle](https://trello.com/c/WP3dXij9)
