### ISSUE TITLE
User permanently gone?

### ISSUE THREAD

**Issue by lynxlynxlynx** [HabitRPG/habitica#7490]
This is a bit odd and so far more of a support request than a bug report.

With the migration, our party lost one member. At first we thought it's the same cache invalidation bug that everyone experienced, but the user hasn't cropped up yet. He was active before the migration and just before hitting level 100 for the first time.

While unlikely, it is possible he closed the account, because when we try to invite him back, the user is either gone or there is a bug somewhere:

> User with id "5d37cd24-af91-4a16-aa23-4361ebeef3bf" not found.

I did check that the error message is still ok when inviting members already in the party.

Can someone please check in the db? For confirmation, the username is aavantasia.

**Comment by Alys** [comment]
That account is definitely not in the database now, but was before the maintenance window.

I'm talking to the staff about this.

**Comment by Alys** [comment]
@lynxlynxlynx We've established that your party member was still in the database after the migration was finished. It seems that they deleted their account a couple of days ago.

**Comment by lynxlynxlynx** [comment]
Ok, thanks!
