### ISSUE TITLE
Invite self to own party

### ISSUE THREAD

**Issue by foxbow** [HabitRPG/habitica#7491]
### General Info

UUID: 35f19d1c-bffe-4c5b-8c2b-753b4ace4e86
GroupID: 0be1fdc6-7da1-40e4-a76a-b5921be11e51
Browser: Firefox 46.0.1
OS: Ubuntu 14.04 LTS
### Description

I can invite myself to my own party that I am already leader of. This leads to some confusion as I cannot join but apparently cannot cancel the invitation either.

**Comment by crookedneighbor** [comment]
Thanks for reporting this!
