### ISSUE TITLE
Show challenge members in separate page

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7492]
After https://github.com/HabitRPG/habitrpg/commit/adce786ae2cc933d2fad2d36c9975a98f1c31e11 and https://github.com/HabitRPG/habitrpg/commit/042ac16c485ea66a3b02fc5649f194e4f2cbc1dc all challenges members are loaded when opening a challenge on the website.

For big challenges with more than 100 users this is a very slow operation so we should move the list of members to a separate page that is only shown on demand

**Comment by khipkin** [comment]
Should this be put on hold, or can someone start working on it?

**Comment by Alys** [comment]
@khipkin Thanks! I've marked it help welcome now. If you want to do it, comment yes briefly and I'll change it to in progress.

**Comment by khipkin** [comment]
@Alys Thanks! No, I'll pass this time. I'm currently super busy. :scream:

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer be relevant afterwards, or if it does, there'll be new code that will need to be modified to fix it.
