### ISSUE TITLE
Quest Owner left the party

### ISSUE THREAD

**Issue by sethscolex** [HabitRPG/habitica#7497]
User named Muhammad Osman Karim left our party recently and left us with a quest we'd like to abort. Please help.

Party ID:c5787e63-cdcb-4936-9910-9e3d2408952d

Thank you in advance and tell me if i need to put more info.

**Comment by Alys** [comment]
We'll certainly help with this!

admins:
I'm not sure it's possible for an owner to leave while the quest is in a
pending state. This might be another case of accidental removal.

**Comment by sethscolex** [comment]
yes, it seems to be some kind of accident because the user is now visible in the party and the quest has begun. anyway the problem fixed itself, thank you for your time

**Comment by Alys** [comment]
Thanks very much for letting us know!
