### ISSUE TITLE
Add New Boxes

### ISSUE THREAD

**Issue by racuna** [HabitRPG/habitica#75]
Please add the posibility to add new boxes, like a new "todo box" of personal stuff, and other "todo box" for office work tasks. Or having other types of "weekly" and "monthly" boxes.

**Comment by lefnire** [comment]
there may be new boxes in the future (and the ability to disable boxes, some people don't use Habits). But those _specific_ recommendations will be where tags comes in, when that's built. there will be a row of tags you can select to filter your tasks down, such as #personal, #office, #weekly, #monthly

**Comment by lefnire** [comment]
#48
