### ISSUE TITLE
Unable to edit guild challenges with no participants

### ISSUE THREAD

**Issue by a-solo-guild-owner** [HabitRPG/habitica#7504]
User ID: 193b5f2c-cbd0-42bf-92e1-42d4a019cc27

Group ID: 1345eb8e-4e0a-46a9-a5f4-7e3470630175

General Info
- UUID: 193b5f2c-cbd0-42bf-92e1-42d4a019cc27
- Browser: Chrome
- OS: Windows 10 or Mac OS X 10.9.5 (either computer has the same problems with challenges.)
### Description

I have a solo guild for longer range planning and goals. After the update, I am no longer able to edit challenge tasks. There are no active participants in the challenges I am trying to edit. I am setting up my next round of goals and actions, for example an 84-day fitness challenge I plan on starting on Monday. The website will not allow me to add tasks, habits, or dailies to solo guild challenges I own or modify the tasks, habits, or dailies already included in challenges with no participants. I can start new challenges, add a few habits and then the challenge locks down. It resets user programmed difficulty levels to "Easy" for tasks, habits, and dailies and will not allow change. It force changes user defined habit preferences from "+" or "-" to "+/-". Text descriptions are also locked down in tasks, habits, and dailies. Essentially, the website challenge creation is completely broken. Please fix this. It reduces Habitica's usability for me substantially. Thus far, I have only used the website--not the mobile app. Thank you for the work you have done on Habitica. This RPG has helped me greatly. :-)

---SparkyWarrior

**Comment by Alys** [comment]
I'm sorry about this! We are tracking this problem in https://github.com/HabitRPG/habitrpg/issues/7320 and it's one of our high priorities. I'm closing this issue now but if you want to follow the progress of the issue, you can subscribe to notifications using the button in the right-hand column of that issue.
