### ISSUE TITLE
Never-ending Quest Invitation

### ISSUE THREAD

**Issue by kaleighm** [HabitRPG/habitica#7505]
General Info
- UUID: 753dfa74-ea7d-4b37-ab9f-7387e69b55b1
- Browser: Chrome Version 50.0.2661.102 (64-bit)
- OS: OS X 10.11.5 (15F34)
### Description

Three days ago, and after the maintenance this past week, my party began the "The Serpent of Distraction" quest. I got to the invitation too late to accept (or I did accept and it didn't go through, I'm not sure) but the quest invitation notification still comes up whenever I come back on the site. It doesn't matter if I accept, reject, or say to ask me later; accepting and rejecting both give me the "Your party is already on a quest." bubble. This has been happening for 3 days.

I don't know what happens when the Serpent quest is completed, or when the next invitation goes out, because they haven't defeated it yet.
#### Console Errors

I've attached a screenshot of the console.

![screen shot 2016-05-26 at 9 45 00 am](https://cloud.githubusercontent.com/assets/19591822/15576583/8ea6db7c-2326-11e6-9aea-eba8ffd2c9ec.png)

**Comment by ghost** [comment]
Thanks for reporting it! I believe it's already being worked on (https://github.com/HabitRPG/habitrpg/issues/7353). @Alys do you need UIDs of the party members here too?

**Comment by Alys** [comment]
@kaleighm @GitHubSphinx No, the party member IDs aren't needed. @kaleighm Sorry about the delay on this - I've been recovering from a broken laptop and the other admins have been very busy with bug fixes. I'll be clearing this invitation out of your account in the next couple of hours most likely.

@GitHubSphinx Thanks for the link to the other issue!

**Comment by Alys** [comment]
@kaleighm I've looked through your account and I can't see any pending quest invitation. It looks like the problem has already fixed itself. I'm closing this but comment here if you are still having trouble.
