### ISSUE TITLE
Challenge Order: Desired Behavior

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7507]
In general, Challenges should display in order of newest-oldest, to offer exposure for newly-created Challenges.

The only exception to this rule are Official Habitica Challenges, which should stick to the top of the list, marked with the "Official Challenge" tag. These Challenges are designated by a staff member marking the corresponding checkbox during Challenge creation.

@crookedneighbor

**Comment by Memry** [comment]
Just subscribing so I can see updates

**Comment by shervinmathieu** [comment]
I've been looking into this today,

It seems that date of creation has never been saved for challenges, and that they are pulled from the database in the order that they are stored.

I'm not sure how to fix this for existing challenges as they are now out of order and with no way of figuring out which was created first. For future challenges, we could either leave it as is (and hope that no more database migrations will be needed), or add an additional date of creation field to the database.

I'm going to try to implement this date of creation field locally, I'll post more comments when I get something going.

Edit: Disregard everything I said above, as timestamps are being stored and the get methods for the challenges already sort them as required. Now to find out why when challenges are being displayed this order is ignored...

**Comment by crookedneighbor** [comment]
I can tell you definitively that there is a `createdAt` field for all challenges in the database.

**Comment by crookedneighbor** [comment]
Never mind, didn't see your edit.
