### ISSUE TITLE
Sporadic failing tests on score task routes

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7509]
### Description

When builds run on Travis CI, errors occur idiosyncratically in the tests for task scoring routes. They are of the format `POST /tasks/:id/score/:direction habits it scores and adds history`, suggesting they come from https://github.com/HabitRPG/habitrpg/blob/develop/test/api/v3/integration/tasks/challenges/POST-tasks_challenges_challengeId_tasks_id_score_direction.test.js.

Restarting the build sometimes causes it to run clean, so it doesn't appear to be a test failing outright, but perhaps some race condition that throws errors some times and not others.
#### Console Errors

The error thrown is `invalid request parameters`. I'm not seeing any further detail in the Travis log.

**Comment by paglias** [comment]
Fixed
