### ISSUE TITLE
Challenge Tasks Losing Notes

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7514]
Reported issue from admin email: "When cloning a Challenge, the challenge tasks lose their description set by challenge owner (i.e. don't have any description at all when being added to user's task list)."

**Comment by Alys** [comment]
We have this reported at https://github.com/HabitRPG/habitrpg/issues/7469 and the mention of "cloning" here is misleading because I think that person was referring to joining a challenge, rather than cloning. I've just tested and cloning a challenge does not remove notes.
