### ISSUE TITLE
Constant "Invalid UUID" messages, something wrong with my account.

### ISSUE THREAD

**Issue by KodeIn** [HabitRPG/habitica#7516]
General Info
- UUID: 46897d9f-0703-4480-9361-3dc694b32986
- Browser: Firefox 46.0.1
- OS: Windows 10
### Description

I keep on getting "Invalid UUID" messages. I tried to reload the page, to re-launch the browser and even tried the Android app, but nothing seems to work. Even the Android app gives a "todo validation failed" error message. 

When I try to check a task, I get a "a._statsComputed is undefined" error message.
#### Console Errors

"NetworkError: 400 Bad Request - https://habitica.com/api/v3/user/?userV=804"
![habiticaerror](https://cloud.githubusercontent.com/assets/224962/15607917/8e61e288-2416-11e6-8ec8-0d8b80ef9624.png)

**Comment by paglias** [comment]
@KodeIn this should be fixed now, can you reload the site / close the mobile apps and try again? Let me know if it still doesn't work

**Comment by KodeIn** [comment]
I've closed the app and reloaded the site, even tried to load it in Edge, I still get the same errors.
I get a "NetworkError: 400 Bad Request - https://habitica.com/api/v3/user/" on the login screen.

**Comment by paglias** [comment]
@KodeIn okay, I _think_ I've fixed that, can you try again?

**Comment by KodeIn** [comment]
It's fixed, thanks.
