### ISSUE TITLE
"Push task to top" notification not going away after task moved to top.

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#7517]
General Info
- UUID: fedc44cb-088a-4bc8-8f4f-3e6a1882f042
- Browser: FF
- OS: OS X 10.11.4
### Description

When clicking the icon to move a task to the top of the list, there is a hover notification that pops up, "Push task to top. Hold ctrl or cmd to push to bottom". When the task is pushed to the top, the notification fades, but does not go away entirely.

<img width="344" alt="screen shot 2016-05-27 at 8 17 19 am" src="https://cloud.githubusercontent.com/assets/101778/15607937/6aab09d2-23e4-11e6-80f3-503fc13a25ac.png">

This does not happen when simply mousing over the icon and the mousing off, without moving it to the top. This also does not happen when holding cmd/ctrl and clicking to move it to the bottom. It only happens when the task is moved to the top of the list.
#### Console Errors

No errors; unrelated warnings that I have seen when posting other bug tickets.

**Comment by Alys** [comment]
FYI for anyone investigating this; It's not new behaviour from API v3. I've noticed it a few times over the past few months (never got around to reporting it, although I should have).

**Comment by Alys** [comment]
I'm closing this because a website redesign will be done in the not-too-distant-future and this isn't an urgent problem. Other admins are welcome to reopen if they disagree!
