### ISSUE TITLE
Constant "Invalid UUID" messages

### ISSUE THREAD

**Issue by jhendricks611** [HabitRPG/habitica#7522]
General Info
- UUID: 3e11b4bf-6306-430c-9a2f-c9e629042606  
- Browser: Chrome v 50.0.2661.102
- OS: MacBook Air on El Capitan
### Description

Whenever I load the tasks page, I get a series of "Invalid UUID" messages in Chrome, and my party is lost. I know that I am in a party and we are currently working on a quest. Here is a photo of the UUID error message series:
![invalid uuid and party lost](https://cloud.githubusercontent.com/assets/19598500/15614348/22ce7230-23ed-11e6-8999-b5154f8c860f.png)

I've tried refreshing the page, logging out and back in, this continues to happen. I tried the app on iPhone (using the most recent updates of both iOS and the Habitica app) and I get the error message, "Network error. Couldn't connect to the server. Check your network connection." I am connected to an online network. I've tried logging out and back in on iPhone as well, no luck.

**Comment by jhendricks611** [comment]
Also, when I try to check off a task, I get the message, "Cannot read property 'str' undefined," and I am almost dead, which is incorrect. Last I checked I had 47 life.

**Comment by paglias** [comment]
@jhendricks611 II'm sorry this is happening :( Do you remember how long ago it started? Could you do me a favor and try this: open the browser console, switch to the Network tab and load the site. You'll see some requests marked in red with urls like ?userV=Number or something similar. Click on one of them and from copy everything you can find in the Preview tab

**Comment by jhendricks611** [comment]
@paglias No worries, that's why I'm here. :) I've been having issues with the quest not loading in my party since the last update, but the lack of function mentioned in this thread started this morning. I followed the instructions above, and only found one ?userv=715 and this is what was in the preview tab:

{success: true,…}
data
:
{_id: "3e11b4bf-6306-430c-9a2f-c9e629042606", migration: "20160521_veteran_ladder.js", pushDevices: [],…}
success
:
true
userV
:
817

I scrolled through the Network tab and was only able to find that one line item with the description you provided. However, the app is now reading that I am dead, so that might be the reason it isn't loading the way we'd expect. Let me know what else you need.

**Comment by paglias** [comment]
@jhendricks611 there was a bug in your data so probably your cron hasn't run for several days and now that we finally solved it it counted several missed days and that's why you died. From now on everything should be back to normal, let me know if it happens again and sorry for the trouble!

**Comment by crookedneighbor** [comment]
Closing this. Let me know if you're still having issues.
