### ISSUE TITLE
Clicking sync causes existing tags filters to be unselected

### ISSUE THREAD

**Issue by jcmoore65** [HabitRPG/habitica#7524]
This is similar to https://github.com/HabitRPG/habitrpg/issues/7413 but not nearly as complicated.

General Info
- UUID: bbde9cd8-1275-4dbf-be1c-00f43186bfaf
- Browser: Chrome
- OS: Windows 10
### Description
1. Click a Tag to filter items 
2. Observe: Tag is selected and items are filtered
3. Click the Sync button
4. Expect: Tag is still selected and items are still filtered
5. Observe: the Tag is unselected and items are no longer filtered
#### Console Errors

No console errors are reported

**Comment by Alys** [comment]
Thanks for reporting this! It will be the same problem as reported in https://github.com/HabitRPG/habitrpg/issues/7413 although it didn't mention syncing specifically so I've just updated it to say that.
