### ISSUE TITLE
Charachter un-equip/re-equip

### ISSUE THREAD

**Issue by EmilyD1037** [HabitRPG/habitica#7526]
### Description

fcdbb86a-bbcb-47a2-b40c-2fdade76d798  User ID

character "clothes/weapons are not showing on the screen.
If you click un-equip it says it is unequipped, but when you try 
to re-equip, it doesn't show on the character. I have reloaded 
several times, left it over the day with no resolution.

**Comment by Alys** [comment]
@EmilyD1037 On the habitica.com website, the Equipment page has two columns. On the left is your Battle Gear (equipment that affects your stats), on the right is your Costume (equipment that appears on your avatar if you have the "Use Costume" option turned on).

I can see from your account that you do have the "Use Costume" option turned on. This means that when you equip or unequip or re-equip an equipment piece from the left-hand side of the screen, you will NOT see the change appear on your avatar. When you equip or unequip or re-equip an equipment piece from the right-hand side, you will see the change on the avatar.

Does this solve the problem?

If not, please tell us which side of the screen you're clicking on and whether you want to adjust the appearance of your avatar (the Costume) or your stats (the Battle Gear).

If any of this isn't clear, please ask for clarification! You can do that either here or at Help > Ask a Question from the habitica.com website's menu (or Guilds > The Newbies Guild from the mobile app).

**Comment by crookedneighbor** [comment]
Closing this. Let me know if you're still having issues.
