### ISSUE TITLE
Cron treated dailies as if they were unchecked

### ISSUE THREAD

**Issue by JenniferMartin** [HabitRPG/habitica#7527]
General Info
- UUID: 154802ac-9567-4916-ac66-79ea5ba81ec7
- Browser: Firefox
- OS: Windows 7 64-bit
### Description

When I logged in this morning (Saturday), I took damage from and had the streaks reset on all my Friday dailies. I also lost the Perfect Day bonus. I know I had checked off all my due dailies yesterday, and I did not lose any gold this morning (i.e., from things not having saved correctly to the server). Everything appeared to be functioning normally on the site yesterday, including the blue sync bar.

I do have a custom day start set, but I set that months ago and have not changed it since.

I am not currently on a quest, so I cannot tell if I cronned twice or not (i.e., cronned once correctly and then cronned a second time for the same day).

I do not believe this is issue #5919 because: 1.) Cron appears to have run at the correct time (4 AM--I know it had not run as of 1:30 AM last night). 2.) I do also have the iOS Habitica app, but both the phone and my computer are on the same timezone. 3.) The timezone has never been changed on either device for as long as I've been using Habitica on each.

I do not believe this is issue #4313 because my dailies are not still ticked--they look exactly how I would expect they would for the start of the day Saturday, except for the lost streaks.

**Comment by Squeemu** [comment]
I think I'm having the same issues: streaks were reset on my Friday dailies and Perfect Day bonus lost, even though I checked all my dailies off. 

I'm currently on a quest and it appears that I cronned twice, both times appearing as "an hour ago." The first cron shows that I did damage to the boss and took no damage, the second one shows that I did zero damage but took damage from the boss. 

I only use Safari (Version 8.0.5 (10600.5.17)) to update Habitica -- no apps. 

UID: df5a0dda-0b53-45a2-9366-d239aa6663bf
Browser: Safari (Version 8.0.5 (10600.5.17))
OS: X Yosemite 10.10.3

**Comment by Alys** [comment]
@JenniferMartin We can't rule out #4313 because its effects aren't always consistent and it might not have left your Dailies ticked. However this could also be an example of the double cron bug (https://github.com/HabitRPG/habitrpg/issues/2805 ) so I've noted it in that issue.

@Squeemu I've noted your report in #2805 too.

Thank you both for reporting this!
