### ISSUE TITLE
Checkbox Error

### ISSUE THREAD

**Issue by JellyBean22** [HabitRPG/habitica#753]
Since the latest update the checkboxes are not displaying correctly (see image).
Also the re-roll button too.

Occurs in release and beta versions.

Chrome version: 27.0.1453.3 dev-m

![Untitled](https://f.cloud.github.com/assets/3935712/320531/8f15dbf4-9949-11e2-84e3-f348f62631fa.png)

**Comment by wc8** [comment]
It's a font problem, I think. I believe @zakkain is aware of it and working on a fix.

**Comment by JellyBean22** [comment]
Cool, just thought I should let you guys know about it!

**Comment by caycefischer** [comment]
Thanks! Can you report your browser and OS/device?

**Comment by lefnire** [comment]
Android 2.3 for me

**Comment by JellyBean22** [comment]
Windows 7 64bit
Chrome version: 27.0.1453.9 dev-m

Also...
Android 2.2.2
Stock Android Browser

**Comment by JellyBean22** [comment]
This can be closed, for me anyway it's fixed
