### ISSUE TITLE
Creating Challenge: Cannot Add Multiple Tasks under "To-Do"

### ISSUE THREAD

**Issue by makkoi** [HabitRPG/habitica#7530]
I saw and commented on the issue where you can't add multiple tasks while editing a challenge, [#6723](https://github.com/HabitRPG/habitrpg/issues/6723), because I am having that problem as well.
### Description

I can't add multiple tasks under "To-Do" when creating a challenge (not just editing it).
Red arrow in shot below ↘
![screen shot 2016-05-28 at 1 11 40 pm](https://cloud.githubusercontent.com/assets/19537840/15629227/316281b4-24d9-11e6-83a2-5283a48cbf79.png)

If I hit 'enter' on my keyboard when typing in a new To-Do under a challenge creation, instead of jumping to a new line and allowing me to create multiple tasks, it creates the one task, and that is all I am allowed to create.
A video example of this (if required): [http://www.mediafire.com/download/561p315zzpecep4/multiple.mov](http://www.mediafire.com/download/561p315zzpecep4/multiple.mov)
### Console Errors

None
### General Info

user ID: b3e66733-ab6f-432f-a052-6fa64585da5a
Browser: Google Chrome Version 50.0.2661.102 (64-bit)
OS: Mac OS X Version 10.9.5

**Comment by Alys** [comment]
This is the same bug as the one reported in #6723. I've edited the title of that issue to specify creating and editing challenges.
