### ISSUE TITLE
when moderator unflags a post, email must be sent

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7535]
Currently, when any player flags a post, an email is sent to some of the moderators.

We need a similar email to be sent when a moderator removes the flags from a post.

The recipient list should be the same as for flag emails.

The subject should be the same so that the unflag email is threaded with the matching flag email.

The body can be very similar, but with moderator name and unflagging date instead of the name etc of the person who flagged, and with a clear message near the top that the post has been unflagged.

**Comment by shervinmathieu** [comment]
I'm going to work on this.

**Comment by shervinmathieu** [comment]
However, is there any way to enable emails in development? I can't test changes if there is no way to do so.

**Comment by quin-jay** [comment]
@velezsarain You may have already figured this out, but in your local install there's a config.json file that includes a line where you can specify an email address. I believe any tests you do with your local account will send a real email to that address (and it has nothing to do with login information, so you can use the same email address as your real Habitica account).

**Comment by quin-jay** [comment]
Although, if the email is to be sent to mods only, config.json won't help. Oops, disregard previous message! :relaxed:

**Comment by paglias** [comment]
@lynnyliz the email setting you see in config.json is only used for password recovery that for 100% delivery have to be sent directly from our server. All other emails are sent through Mandrill
