### ISSUE TITLE
Can't cancel tags, only add them

### ISSUE THREAD

**Issue by DeathTimer** [HabitRPG/habitica#7536]
The problem first occured a week ago. I'm trying to cancel a tag in one of my To-Do's and after I save the settings, the tag still exists. When trying to give it another tag, it adds up and yet again cannot be removed.

I'm using Chrome, fully updated.
User ID: 443336c4-bac4-44f6-a10f-b6603c019f13

**Comment by Alys** [comment]
We're tracking this bug in https://github.com/HabitRPG/habitrpg/issues/7412 

See the first comment from me for a work-around (in biref, double-click on the tag's checkbox). 

If you'd like notifications about the progress, there's a subscribe button in the right-hand column.
