### ISSUE TITLE
Participation in Quests Not Working Properly

### ISSUE THREAD

**Issue by jrsimonelli13** [HabitRPG/habitica#7537]
- tried to go to https://github.com/HabitRPG/habitrpg/issue but it sent me to a 404 page

General Info
- UUID: 250ad625-2ddf-45ce-b6f3-50efb4b7ecf2
- Browser: firefox
- OS: windows 10
### Description
- Boss quest isn't registering my activity, only the activity of my partner (see photo below). This has been going on for  several days now. You can see at the bottom left corner that I am participating in the quest, just not causing any damage. I am jrsimonelli13

![untitled](https://cloud.githubusercontent.com/assets/19633590/15633018/d6219694-2570-11e6-9eab-4dee6eee1716.png)

**Comment by crookedneighbor** [comment]
The correct link is  https://github.com/HabitRPG/habitrpg/issues (s on the end). Where did you see the other link so I can correct it?

Your quest object on your user was missing the quest key. I've added it. 

For admin reference:

```
// previous quest object
{
    "progress" : {
        "collect" : {},
        "up" : 5.02530875405756,
        "down" : 0
    }
}

// new quest object
{
    "key" : "vice1",
    "progress" : {
        "collect" : {},
        "up" : 5.02530875405756,
        "down" : 0
    }
}
```

**Comment by jrsimonelli13** [comment]
I very much appreciate your help on this crookedneighbor!! I am showing this now though.

![untitled1](https://cloud.githubusercontent.com/assets/19633590/15633127/da6cfbb4-2573-11e6-9f21-9118f748e07c.png)

The page you asked for with the link is this:

![untitled2](https://cloud.githubusercontent.com/assets/19633590/15633128/e9e12728-2573-11e6-961c-eef9d38edf5a.png)

**Comment by crookedneighbor** [comment]
So sorry about that, I'll fix it in a second.

**Comment by crookedneighbor** [comment]
Uhg, I need to download backup of the database to restore your user. It'll be restored in less than 2 hours. I feel terrible about this and will award you some gems to say sorry about the inconvenience.

**Comment by jrsimonelli13** [comment]
No worries. I very much appreciate all you are doing to help me with this issue. Thanks!!

**Comment by crookedneighbor** [comment]
Okay, could you try reloading the page now?

I've awarded your user 4 gems.

**Comment by jrsimonelli13** [comment]
The page seems to be loading normally, though I took a health hit and a gold hit (maybe from built up boss attacks I assume?). I will check the quest page first thing tomorrow to see if I hit the boss at all since nothing has shown up for my user yet and I believe it updates only upon the first login of the day. 
I can't thank you enough for your hard work on this issue. I am hardly deserving of these four beautiful gems!

Thanks!!

**Comment by crookedneighbor** [comment]
@jrsimonelli13 I just realized that your cron probably ran again. I've reset you back to the restore point again and set you to be asleep in the inn. Refresh the page, check out of the inn, and everything should be back to normal.

**Comment by crookedneighbor** [comment]
You can restore any gold you've lost using fix character values on the settings page.

**Comment by jrsimonelli13** [comment]
Will do. Thanks again!
