### ISSUE TITLE
Challenge filtering reverts after closing challenges

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7539]
- Browser: Chrome
- OS: Win10
### Description

After selecting to show only the challenges I own, and/or only the challenges in the ghost ship guild, I then select a winner for one of the organ donor challenges. The action is taken, the blue bar starts to go across and it appears normal, but then the page reverts to showing me challenges from all guilds/all owners.

**Comment by Alys** [comment]
related: https://github.com/HabitRPG/habitrpg/issues/5754 "Challenges filter is forgotten after joining one"

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Now, the page redirects back to the challenge list when a challenge is closed, so should the filter still persist?

**Comment by lemoness** [comment]
I'm open to it -- @Cantras would this still be a helpful feature in the new flow?

**Comment by ghost** [comment]
I think it matters less, since you can open all the challenges you want in new tabs, which you couldn't before. It might still be helpful for others, but for my own workflow it's irrelevant.
