### ISSUE TITLE
Missing Helm

### ISSUE THREAD

**Issue by SiakelA** [HabitRPG/habitica#754]
I am on Chrome and Windows Vista. I just bought the plate helm. It removed the gold from my character, but my avatar did not update to show the helm. I tried to refresh to see if that would fix the issue, but it did not. So, no gold and no helm. :(

**Comment by JellyBean22** [comment]
Check if the "Show Helm" checkbox is ticked, in your avatar section

**Comment by SiakelA** [comment]
It is. I can see the chain mail helm.

**Comment by lefnire** [comment]
Use the restore tool for now to increase your helm:
https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#restoring-your-avatar-stats-items-accidental-death-etc.
There's a known issue where sometimes purchasing an item lags out,
I'll
be working on it.

**Comment by SiakelA** [comment]
Thanks :)

**Comment by wc8** [comment]
Can this be closed then, since you're addressing it already, @lefnire?

**Comment by lefnire** [comment]
let's leave this open unless we can find the duplicate ticket, since it's a bug that needs to be fixed

**Comment by wc8** [comment]
#514 or #507 (closed) might be the original ticket.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
