### ISSUE TITLE
Gem Sent Text in the Inbox does not formatted "as code" anymore

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7540]
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
### Description

Previously before API v3 any gems sent to a user will be formatted in the Inbox as
`@ThisPerson has sent you gems.` Message from User

Now it just showing:
@ThisPerson has sent you gems. Message from User

**Comment by phrohdoh** [comment]
With my naive peek into the codebase it seems the message is still wrapped in ticks so perhaps something is stripping them out before converting markdown to html.

https://github.com/HabitRPG/habitrpg/blob/fb035c414cfada1f20bd1a30c632f981156c712a/website/server/libs/api-v3/payments.js#L169

**Comment by Alys** [comment]
The backticks aren't making it into the database now. This is a gem gift message that was sent today:

```
    "inbox": {
        "optOut": false,
        "messages": {
            "2e318a66-4fef-4332-9bc8-d43c42d1e601": {
                "sort": 427,
                "user": "ALittleYellowSpider",
                "backer": {},
                "contributor": {},
                "uuid": "3e595299-3d8a-4a10-bfe0-88f555e4aa0c",
                "flagCount": 0,
                "flags": {},
                "likes": {},
                "timestamp": 1464844824202,
                "text": "Hello Alys, ALittleYellowSpider has sent you 1 gems! zdfgsdf sdgf dfsadf",
                "id": "2e318a66-4fef-4332-9bc8-d43c42d1e601"
            },
            "fb0b0769-e8c1-4d3c-a7ce-be5734ffe9e3": {
                "sort": 425,

```

and here's one sent a few months ago, with correct backticks (although there really should be a space after the closing backtick):

```
            "049b3b01-b0ca-4151-a0d6-f1a40b8d9ddc": {
                "sort": 12,
                "user": "xxxxx",
                "backer": {},
                "contributor": {},
                "uuid": "xxxxx",
                "flagCount": 0,
                "flags": {},
                "likes": {},
                "timestamp": 1454925725868,
                "text": "`Hello xxxxx, Alys has sent you 4 gems!`Hi xxxxx.....",
                "id": "049b3b01-b0ca-4151-a0d6-f1a40b8d9ddc",
                "sent": true
            },
```

**Comment by SabreCat** [comment]
Possibly something that started happening when we changed Markdown libraries? @crookedneighbor

**Comment by crookedneighbor** [comment]
No. The controller is just not including them. 

https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/members.js#L358

**Comment by cTheDragons** [comment]
Also another point I noticed the @ symbol is missing front of the users' name.

So it is currently:
ThisPerson has sent you X gems.

As opposed to
'@ThisPerson has sent you X gems'

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/pull/7671
