### ISSUE TITLE
Tags cannot be sorted / reordered

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7541]
Tags cannot be sorted. If you change the order of the tags, the next time a sync occurs, they change back.

**Comment by Alys** [comment]
This might be browser-dependent. cTheDragons says it works in Opera. I can't get it to work in Chrome or Firefox.

**Comment by shervinmathieu** [comment]
I don't think this is browser dependent. It is broken in all of my browsers.

**Comment by shervinmathieu** [comment]
I found out that while the API call to reorder tags works, as it passes the tests and updates the database properly, reordering the tags in the client itself will not update the database but will call the API anyway. I'm believe that the client files are not passing the correct argument to the API calls however this would be strange too since the karma tests are also passing...

**Comment by crookedneighbor** [comment]
Are there karma tests for tag re-ordering?

**Comment by shervinmathieu** [comment]
Now that you mention it, there does not seem to be karma coverage for this function, the karma code reads:

```
&nbsp;
        sortTag: <span class="fstat-no" title="function not covered" >function (data) {</span>
<span class="cstat-no" title="statement not covered" >          user.ops.sortTag(data);</span>
<span class="cstat-no" title="statement not covered" >          Tags.sortTag(user.tags[data.query.from].id, data.query.to);</span>
        },
```

When this is fixed maybe this test should be written? Although I have zero experience with writing karma code.

**Comment by shervinmathieu** [comment]
I was right, the API is being called with wrong arguments.

The tag being passed to the API is not the one that is being moved, but actually the tag in the destination position.

This causes the API to move the destination tag to the same position its in.

This behaviour is broken if the tags have already been sorted and the client is not synced, and tags are actually sorted then. But not always in the order the user wants them to be.

**Comment by paglias** [comment]
@velezsarain good investigation!

**Comment by shervinmathieu** [comment]
It seems this function is the culprit :

```
        sortTag: function (data) {
          user.ops.sortTag(data);
          Tags.sortTag(user.tags[data.query.from].id, data.query.to);
        },

```

Sometime between the beginning of it, when the data is valid, and the call to `Tags.sortTag()`, a function in common/script/ops/sortTag.js is called, will sort the data, and cause the call to the other sortTag function to fail (because the data was already sorted).

There needs to be a way to store the tag info before it is modified client side.

**Comment by texastoland** [comment]
I'm hesitant to open a separate issue. I see the function in the client but it doesn't appear to be called anywhere. Can tags no longer be sorted in the UI?

**Comment by paglias** [comment]
It looks like the new UI doesn't support sorting tags, given the way the UI works now I'm not sure reordering tags is a necessary feature

**Comment by texastoland** [comment]
> I'm not sure reordering tags is a necessary feature

Why not? As a user, when I create a new tag, that is related to some other tag (e.g. Kanban-style `later` and `next`), I want them grouped together in the filters instead of in creation order. Am I missing some context? It sounds straightforward to add given their UX similarity to task list items.

**Comment by Alys** [comment]
The inability to sort tags is one of the reasons I don't use them at all on the new site (the other is the increase in clicks and scrolling required to apply tags). I had tags for priority, time of day, location, and project - sort of a GtD style setup - with each type of tag grouped together and sorted appropriately within the group. New projects were sorted into appropriate places within the existing ones, as were challenge tags. That system can't be maintained now, so I don't use it any more.

Any advanced tag setup is impossible or very difficult to create without sorting.

**Comment by paglias** [comment]
Pinging @Tressley

**Comment by texastoland** [comment]
My other usability issue is #2695 where @Alys linked the Trello card. I'm willing to implement I just don't know the change process.

**Comment by majestic-owl448** [comment]
Was this abandoned? Or just overlooked?
 @paglias @Tressley

**Comment by Alys** [comment]
It looks like it might have been overlooked. I'm reopening it. Thanks @Ieahleen 

It's still an issue for players as indicated above and by this recent discussion about it:

_Transcender (e64eedd4-d51c-4cdc-8635-a063fd22a62c): "Hi, is there a way to reorder tags? I have many tags so it's very messy, but I can't seem to reorder them. Dragging them doesn't work :/"_

_tseren (8d1bee26-4a44-496d-89b5-1e8778d82c7d): "Although you ought to be able to reorder tags by dragging and dropping them using the left mouse button, there is currently a bug preventing this on the website."_

_Transcender (e64eedd4-d51c-4cdc-8635-a063fd22a62c): "Oh I see, is there a rough estimate to when it would be fixed?"_
