### ISSUE TITLE
'null' is not a valid enum value for path 'challenge.broken' 

### ISSUE THREAD

**Issue by him89088** [HabitRPG/habitica#7546]
General Info
- UUID: 3225d5f9-46d2-4995-b670-8583ecacd82b
- Browser: Chrome 50.0.2661.102 m
- OS: Windows 10 Pro
### Description

Hi, 
So I opened my Habitica page, just after beginning of my cron (00:00 IST for me). As soon as it opened, a dialog box appeared notifying me that I have suddenly zero health. As well as continuous wave of notifications **'null' is not a valid enum value for path 'challenge.broken'** kept showing. 
Me and my team were in a quest The Laundromancer (Attack of the Mundane part 3) with Boss health remaining 6.2 HP. 

I logged out. Reset my browser and logged in again. And it just keeps loading, with everything turned to be zero. I have included the console error for this. And the screenshots too.

![habitica](https://cloud.githubusercontent.com/assets/4967571/15656992/8b30a44e-26ca-11e6-8964-632de4f09fe6.JPG)

![habitica 2](https://cloud.githubusercontent.com/assets/4967571/15656991/8afe95e4-26ca-11e6-9e6b-e2079a0f2da3.JPG)

![console error](https://cloud.githubusercontent.com/assets/4967571/15656990/8af76b7a-26ca-11e6-9229-99600ccd4674.JPG)
#### Console Errors

Actually, it starts with this

Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-c45ccd28.js:40:27273)
    at Object.u.authenticate (https://habitica.com/app-c45ccd28.js:44:8863)
    at Object.<anonymous> (https://habitica.com/app-c45ccd28.js:44:10013)
    at Object.i [as invoke](https://habitica.com/app-c45ccd28.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-c45ccd28.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-c45ccd28.js:5:16822)
    at https://habitica.com/app-c45ccd28.js:5:14868
    at g (https://habitica.com/app-c45ccd28.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-c45ccd28.js:5:16789)
    at D.instance (https://habitica.com/app-c45ccd28.js:6:8436)

app-c45ccd28.js:6 TypeError: Cannot read property '_id' of undefined
    at Object.o [as party](app-c45ccd28.js:43)
    at new <anonymous> (app-c45ccd28.js:45)
    at Object.i [as invoke](app-c45ccd28.js:5)
    at D.instance (app-c45ccd28.js:6)
    at app-c45ccd28.js:6
    at x (app-c45ccd28.js:4)
    at pa (app-c45ccd28.js:6)
    at r (app-c45ccd28.js:5)
    at pa (app-c45ccd28.js:6)
    at r (app-c45ccd28.js:5)

And it keeps going on for everything

**Comment by crookedneighbor** [comment]
This was my fault. I'm fixing it.

**Comment by him89088** [comment]
That was quick! A'ight, man. Thanks for letting me know. Hope things get back on track soon. Cheers.

**Comment by shrisnerd** [comment]
I am also having this issue, but when I check off tasks related to a challenge I built/own and am the only member of. The task itself doesn't get checked off, but it does give me XP, mana, gold.. The message is the same, it's just the circumstances are slightly different. 
![image](https://cloud.githubusercontent.com/assets/19655344/15657547/ea947d3e-267f-11e6-9114-fcab8441ef54.png)

**Comment by paglias** [comment]
This should be fixed now. @shrisnerd @him89088 if you reload the site it should work!

**Comment by him89088** [comment]
It does. Thanks

**Comment by crookedneighbor** [comment]
@shrisnerd @him89088 did y'alls tasks get very red when this happened? I think this caused cron to run multiple times, messing with the history of dailies and the value of your tasks. If you'd like, I can restore the color and history back to the state they were in yesterday. Just let me know.

**Comment by him89088** [comment]
@crookedneighbor Yes they did. I would really appreciate it if you could restore it. Also, it happened with my teammate. Is it possible for you to restore hers too? Her UUID is 1bb1d942-6867-48f1-94ab-42b5eac400a4.
Thanks

**Comment by shrisnerd** [comment]
Thank you for asking. My tasks did not get red--it was fixed the very same day I saw the problem, so everything is fine now for me.

shrisnerd

**Comment by crookedneighbor** [comment]
@him89088 The tasks should be fixed now. Report back if they are not.

**Comment by him89088** [comment]
@crookedneighbor Yes. They are fixed now. Thanks a lot.
