### ISSUE TITLE
Can't delete completed tasks

### ISSUE THREAD

**Issue by Maslor** [HabitRPG/habitica#7549]
UUID: 84947daf-c445-4bf6-b49c-e62adcd2043d
Browser: Safari 
OS: OS X El Capitan

On my TODOs, I try to "Delete Completed" tasks and sync but after I refresh my browser, the completed tasks come back. I've tried to delete them more than three times but they always come back, even if I sync right after deleting. 

---

_edit by Alys, 2016-06-16:_

I'm seeing different behaviour now. Clicking the "Delete Completed" button makes the blue sync line appear but the completed To-Dos are still visible, however if you reload, then the completed To-Dos disappear, so it's probably related to https://github.com/HabitRPG/habitrpg/issues/7392 . There's also no confirmation step; I thought there used to be but I could well be wrong.

The desired behaviour is:
1. Click on the "Delete Completed" button.
2. See a confirmation step of some kind.
3. After choosing to proceed:
   - all completed To-Dos are deleted from the database 
   - they disappear immediately from the current view (if essential, this could be done by forcing a reload; that might be the best approach until https://github.com/HabitRPG/habitrpg/issues/7392 is fixed)

**Comment by Alys** [comment]
Confirmed. When you click on the "Delete Completed" button in the "Done" tab, you don't see the normal confirmation step, and no To-Dos are deleted.

There are no errors in the javascript console.

**Comment by Hus274** [comment]
I believe this has already been fixed. I tested on both ubuntu and on el capitan using safari and wasn't able to replicate the bug.

**Comment by Alys** [comment]
Yeah, I'm seeing different behaviour now. Clicking the "Delete Completed" button makes the blue sync line appear but the completed To-Dos are still visible, however if you reload, then the completed To-Dos disappear, so it's probably related to https://github.com/HabitRPG/habitrpg/issues/7392 . There's also no confirmation step; I thought there used to be but I could well be wrong.

The desired behaviour is:
1. Click on the "Delete Completed" button.
2. See a confirmation step of some kind.
3. After choosing to proceed:
   - all completed To-Dos are deleted from the database 
   - they disappear immediately from the current view (if essential, this could be done by forcing a reload; that might be the best approach until https://github.com/HabitRPG/habitrpg/issues/7392 is fixed)

I'm copying this comment to the top post for the convenience of coders who are looking for work to do. :)

**Comment by Alys** [comment]
@Hus274 is currently doing a fix for #7392 (thank you!) so probably best that no one works on this issue until that one is completed because it could cause the delete button's behaviour to change.
