### ISSUE TITLE
Please provide a way to avoid using external websites when self-hosting HabitRPG

### ISSUE THREAD

**Issue by ClearlyClaire** [HabitRPG/habitica#755]
Hi,
I'm using HabitRPG on my home server for a little over a week, and I've to admit I've been quite shocked when I've discovered it started to use Google ads, and CloudFlare for third-party JS and CSS files...
The point of self-hosting it is to not relying/be tracked by third-parties, and I consider such changes to be an issue... Thus, I would like a convenient way to:
- disable ads globally
- use self-hosted copies of third-party libs, as it was previously the case
- do not use Stripe when no account has been configured (could be done by testing the value of STRIPE_API_KEY)

Although I do not know anything about CoffeeScript, node.js or derbyjs, I am willing to contribute patches, and I'll start right away.

**Comment by lefnire** [comment]
We added CDN scripts for technical reasons: https://github.com/lefnire/habitrpg/issues/658 (and ads / stripe so we can survive). Pull requests will indeed be appreciated, self-hosting is a bit self-serve - so I thank you for being willing to contribute patches.

**Comment by lefnire** [comment]
There are a lot of references to "if NODE_ENV is production", "if NODE_ENV is development" - best bet would be add a third option "local" to check for removing ads, using public/vendor/\* js / css, etc

**Comment by ClearlyClaire** [comment]
#658: Hum, what about not having derby concat/minify them, and just refer to them with "/vendor/..." instead of "//cdn..."?
NODE_ENV: sorry if this is a dump question, but isn't that also used by libs HabitRPG depends on? What if I want a “development” or “production” setting while disabling ads and the like?
Another question: is views/static/head.html used? It contains references to third-party scripts but none of them seems to be in the pages served by HabitRPG...
I have some patches on the way, but I'm not too happy with them for now...

**Comment by lefnire** [comment]
fixed, see above commit lot

**Comment by HLFH** [comment]
@lefnire So, I don't understand everything. I use a local HabitRPG. How can I remove **all the trackers** ? Which branch must I use ? Do develop and master branches include directly this commit > https://github.com/lefnire/habitrpg/commit/72ee444608c97a5395275d94c504fd3ec9d43ea1. Which NODE_ENV is required to remove trackers...?

**Comment by lefnire** [comment]
There's no built in way to exclude trackers, ads, or external scripts. Feel
free to submit a PR which would use an environment variable to that effect
(probably not NODE_ENV since we're both going to want to use "production").

**Comment by HLFH** [comment]
Thx. Ok I will try that.
