### ISSUE TITLE
Leveling Up Contrib Tier: "Path `flags.contributor` was not saved, as it's a protected path"

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#7550]
General Info
- UUID: Can't get to it
- Browser: Chrome
- OS: Chrome OS
### Description

I just gained a contributor tier (thanks @crookedneighbor!), and went to the site to dismiss the alert. However, when I click on it, it loads a bit and then gives the error "Path `flags.contributor` was not saved, as it's a protected path" before popping up the modal again. I mean, I'm grateful and all for becoming Tier 3, but I'd kind of like to get back to my tasks 😁, so if anyone would help, that would be great!
#### Console Errors

I am unable to get to the console (disabled by the organization I have my chrome account from)

**Comment by ltorroba** [comment]
I just faced the same issue after gaining a contributor tier (thanks @crookedneighbor and the Habitica team!). Here's a screenshot of the modal:

![](http://image.prntscr.com/image/77cfb066025e44a484e98287ad4e5683.png)

Refreshing the browser window made the problem go away.

UUID: 8ac1be04-4201-4eed-a2a4-436eada5c0e9
OS: Mac OS X
Browser: Chrome

**Comment by crookedneighbor** [comment]
Whelp, that's awkward.

I've dropped each of you down a tier. Can you confirm that it has started working again? I'll bump you back up when I've fixed this.

**Comment by librarianmage** [comment]
After refreshing, I no longer get the notification, although I still have
the 3 gems from the tier increase and the crystal helm is still unlocked
for me

**Comment by crookedneighbor** [comment]
That is expected.

**Comment by ltorroba** [comment]
Same here - 3 extra gems and crystal armour unlocked.

**Comment by librarianmage** [comment]
When signing in on another computer, I received a notification for "reaching tier 2" that only dismissed after refreshing the page

**Comment by librarianmage** [comment]
@crookedneighbor I just checked and I do not have the crystal helm unlocked anymore

**Comment by ltorroba** [comment]
Here too - no access to crystal armour. Gems are still there though.

**Comment by crookedneighbor** [comment]
Working on this now

**Comment by crookedneighbor** [comment]
Going to keep this open until I deploy the fix tomorrow morning so that I remember to award y'all your tiers.

**Comment by librarianmage** [comment]
Thanks!

**Comment by crookedneighbor** [comment]
I've applied the tiers. Refresh the website for it to take effect.
