### ISSUE TITLE
Text does not show up immediately when typed into guild chat

### ISSUE THREAD

**Issue by Xehias** [HabitRPG/habitica#7555]
General Info
- UUID: bfaa6b85-aa5a-4c2d-900b-84278ee5fc03
- Browser: Google Chrome 50.0.2661.102 (64-bit)
- OS: Mac OS X 10.9.5
### Description

Whenever I type into any guild chat, the text takes a few seconds to show up. The faster I type, the worse it gets. If I type continuously, the text appears in chunks. This problem does not happen in my party’s chat.

**Comment by Alys** [comment]
We have this reported at https://github.com/HabitRPG/habitrpg/issues/6462

If you'd like notifications about the issue, there's a subscribe button on that page.

A good work-around is you type your message into a text editor then paste it into chat. Pasting is instant. You can also use the Chrome chat extension - if you'd like details about it, please go to Help > Ask a Question and someone will be sure to answer you soon!

**Comment by Xehias** [comment]
My bad—I hadn’t noticed the issue had already been reported, even though I skimmed the reports list! Thank you for replying quickly and for the workarounds.
