### ISSUE TITLE
Sorting rewards works only once, item tooltips don't show up

### ISSUE THREAD

**Issue by ClearlyClaire** [HabitRPG/habitica#756]
Hi,
I've noticed rewards can only moved only once.
Additionally, item tooltips will not show up on unlocking, and will stop showing up if the user changes the order of the rewards.

**Comment by wc8** [comment]
Perhaps related to #740

**Comment by lefnire** [comment]
TMK ThibG fixed in the PR, I'll be merging that soon as I ge a moment to test it

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Please notice that sorting still has to be ported in the next days so now it isn't working
