### ISSUE TITLE
Repeated error messages + undeserved death + interface not loading correctly

### ISSUE THREAD

**Issue by Sawseruquo** [HabitRPG/habitica#7566]
### General Info
- UUID: 787283cd-0e7b-41f4-8474-9d0d224a2869
- Browser: Safari 9.1.1
- OS: 10.11.5
### Description

Refreshed my Habitica page on Safari this morning to get two 'Yikes' error messages at once – this happened a couple of times. I tried closing Safari and opening Habitica in Chrome (50.0.2661.102), whereupon I got the following mathematical gobbledegook (Fig 1).

![fig 1](https://cloud.githubusercontent.com/assets/19674758/15689643/1bbd78ee-27bf-11e6-9617-34e3c3330b76.png)

Went back into Safari and reloaded again – and got a message saying you have lost all your health (complete with a little popup in the top left saying –50 health). This doesn't make sense. I was on full health and had only one uncompleted daily when I went to bed last night – and I'm a Rogue, and had cast stealth. I shouldn't have lost any health, let alone all of it. And I had 910 gold saved up!

Upon reloading, this is what my screen looks like now (Fig 2): 

![fig 2](https://cloud.githubusercontent.com/assets/19674758/15689806/d480d86c-27bf-11e6-8887-de1b2101dcd5.png)

Error messages still there, the mana bar appears to be broken, I have my gold back, but the dailies are still confused – a couple more that I checked off yesterday should have reappeared at the top of the 'due' list.

Meanwhile, when I try to use the iOS app, I get the following message (Fig 3):

![fig 3](https://cloud.githubusercontent.com/assets/19674758/15689903/32f2740a-27c0-11e6-8dc5-8da1c5bdc0db.jpg)

What's going on?

**Comment by SabreCat** [comment]
@Sawseruquo: I've done some repairs to your data. If you reload now, does it behave better?

Your party was listed as being on the Egg Hunt quest, but your personal data had you on Moonstone Chain Pt. 1. That got things confused when it tried to display what items you'd collected. So we'll need to track down how that happened! Did you change parties or quests recently?

**Comment by Sawseruquo** [comment]
Thanks @SabreCat. Just reloaded again – the screen now behaves fine, but I've lost another level and all my streaks on my dailies – and all my to-dos are now dark red when some of them were different colours before. Is there any way to reset the data to the way it was last night?

![fig 4](https://cloud.githubusercontent.com/assets/19674758/15690802/6b700e7e-27c4-11e6-8e98-85c6b939caea.png)

I've joined a couple of parties in the last couple of days, but eventually decided to go it alone, as everyone else's buffs threw out the reward system – I got too much gold! In my solo party I was doing the egg hunt quest.

**Comment by SabreCat** [comment]
@Sawseruquo: I'll pull down a database backup and see what I can find for you!

**Comment by crookedneighbor** [comment]
@Sawseruquo I've restored your task colors, streaks, and history from yesterday. 

If you wan to adjust your level and gold, you can do so by going to Settings > Site and using the "Fix Character Values" button.

**Comment by Sawseruquo** [comment]
Legend. Thank you!
