### ISSUE TITLE
Level-Down and Draining Gold Bug

### ISSUE THREAD

**Issue by wdiip** [HabitRPG/habitica#7571]
### General Info
- UUID: 9433d95d-4896-4730-99f9-16dd24d88364
- Browser: Chrome
- OS: Windows 7
### Description

I just became level 10 and chose to Opt-Out of the class system. I had 4 HP when I levelled up, and right after levelling up I selected a negative Habit which subtracted 4 HP from my newly re-filled HP meter. Everything worked as normal.

I re-opened Habitica a short while later and was greeted with the "Out of HP" popup and I was downgraded 2 levels to Level 8 for some reason. What's worse, all 311 of my gold pieces are gone.

![habitica problem](https://cloud.githubusercontent.com/assets/15808745/15697499/b4e4fb14-2788-11e6-92d8-9c2638d88d66.png)

![habitica problem2](https://cloud.githubusercontent.com/assets/15808745/15697609/c0208dc6-2789-11e6-9d1b-0602c7b9720a.png)

**Comment by citrusella** [comment]
Sounds like you may have been affected by #7551 

If it helps, you can restore the levels and gold (plus the gold to buy the two items you should have lost) by using Fix Character Values in the site area under the settings cog/gear.

**Comment by crookedneighbor** [comment]
@citrusella I checked the user id, and this user was not affected by that issue.

**Comment by Alys** [comment]
@wdiip It's possible that you were affected by this bug: https://github.com/HabitRPG/habitrpg/issues/4313
In brief, for a period of time, your browser was unable to communicate with the server. It kept on allowing you to take actions, and applied those actions to the website as best it could (e.g., causing you to appear to level up) but it wasn't sending any of your actions to the server for permanent storage. When it finally did communicate with the server again, the actions you had taken and their effects were reversed. There's an "Advice" section near the top of that issue which will show you how to recover from the unfair losses (Fix Character Values).

I'm leaving this open in case any other admins have other ideas about what might have happened.

**Comment by wdiip** [comment]
@Alys That Fix Character Values button is really useful in case of bugs like this, thank you. I'll keep an eye out for the blue sync bar from now on.

**Comment by paglias** [comment]
Reopen if it happens again
