### ISSUE TITLE
Not Dropping Zombie Hatching Potions At All

### ISSUE THREAD

**Issue by D-Patterson** [HabitRPG/habitica#7573]
General Info
- UUID: 647a138e-e27e-4cd1-aba0-afbf5ed72955
- Browser: Google Chrome
- OS: Windows 8
#### Description

I have been playing Habitica for a long time, and I haven't gotten a single zombie hatching potion in about two months. (I only know it's been that long since I've been waiting to hatch a zombie dragon for the beast master achievement.) I think I might be getting an excess of another potion instead--it seems like almost every day I get a shade potion.
I should mention that I also play on the mobile app (the most recent update for Android), but this has not change the rate at which I am receiving drops.
#### Console Errors

None.

**Comment by Alys** [comment]
This is just from random chance. You'll get zombie potions in future. Please see this issue for more details: https://github.com/HabitRPG/habitrpg/issues/2176
