### ISSUE TITLE
Chat message submitted does not appear until you Fetch Recent Messages

### ISSUE THREAD

**Issue by NikicaJEa** [HabitRPG/habitica#7575]
When I write something and hit enter as this is usually the button that submits your message , it deletes my message which is quite annoying.

**Comment by crookedneighbor** [comment]
I cannot reproduce this. Where is this happening? What browser are you using?

What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by NikicaJEa** [comment]
Sorry,  it shows after I click on the button "fetch  recent messages" .  I was just thinking it should automatically show it like when I click  the button " send chat"

**Comment by NikicaJEa** [comment]
I use mozilla 
95ad2725-8209-4fbe-8e58-db346d5c5467

**Comment by Definitia** [comment]
The exact thing described in the title happens to me as well - when I submit a message or use a skill, it does not appear in the chat automatically, I have to "fetch" it; same for the boss damage message when I first log in after the Cron. However, it only occurs when I'm at work and thus using Chrome - normally I use Firefox. It started after the last big maintenance and was very confusing at first. My UID is fbcc1ddd-a6ef-499a-ae30-fa817b000438

**Comment by Alys** [comment]
@NikicaJEa @Definitia Thanks for the reports! We had something very similar reported at https://github.com/HabitRPG/habitrpg/issues/7407 so I've updated that with your comments, and we'll use that for tracking and fixing the issue.
