### ISSUE TITLE
"No such customer" error trying to cancel subscription with failed payments

### ISSUE THREAD

**Issue by wysawyg** [HabitRPG/habitica#7577]
General Info
- UUID: 93d5429b-6f05-4e08-bd76-1e449678330d
- Browser: Chrome
- OS: Windows 8
### Description

I tried to cancel my subscription today and the first time I got an json internal server error (I didn't capture the exact detail).
On subsequent attempts, I get: {"success":false,"error":"Error","message":"No such customer: cus_4iWhikZtiXoOR6"}
However the subscription page still shows me as having a subscription. I'm worried that something got detached in the front end but the underlying subscription is still active.
#### Console Errors

None seen except a 404 for /stripe with my api key in (hence not copied)

**Comment by SabreCat** [comment]
This happens when your credit card payments have failed enough times that our payment processor stopped trying to charge you, but the notification didn't make it back to Habitica to cancel the subscription on our end. So the good news is that you haven't been charged any extra times! I'll get the subscription canceled in Habitica for you.

**Comment by paglias** [comment]
@SabreCat there's an error recorded for @wysawyg `error: TypeError: Cannot read property 'current_period_end' of null`

**Comment by SabreCat** [comment]
@paglias Ah, yes. That's the one! Prior to v3, that's the error that end users saw in this same situation.

**Comment by paglias** [comment]
@SabreCat cool! do you know why we haven't setup Stripe webhooks to tell us of failed payments? Also do we know how many users are affected?

**Comment by SabreCat** [comment]
@paglias: Webhooks would definitely be the solution; no specific reason other than not having the opportunity/resources yet. I don't know how to tell how many users currently have failed Stripe subscriptions that are still active in Habitica, but we get a mid-single-digits number of reports of the issue every month.

**Comment by wysawyg** [comment]
Ah, that makes sense. My debit card expired end of April and I forgot to update it on here. Thanks.

**Comment by Alys** [comment]
@wysawyg's subscription has been removed from Habitica and we have this bug reported elsewhere so I'm closing this.
