### ISSUE TITLE
party members HP, quest, etc doesn't update automatically - multi refresh / logouts required

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitica#7578]
General Info
- UUID: 29c5340b-d150-4347-862c-fec571a18b8a
- Browser: any
- OS: any
### Description

Since the maintenance was done I have to reload 5 to 7 times and refresh 5 to 7 times EVERY TIME I want to check my party Members HP, it subtracts my mana immediately HOWEVER,  when I go to my party page, it doesn't show there and the mana doesn't apply to those who are low in HP unless I reload 5/7 times and refresh 5/7 times every single time, every time I'm on Habitica,  every single day!!! This has become extremely annoying and I'm at a point where I dread logging in. My current class is a healer and it's vital for me to make sure my team mates don't  die during the Boss Quest,  Please help! Thank you!

**Comment by JerseyEmerald** [comment]
Ps this happens on my android,  mobile browser and my computer... I use Google Chrome, it's current, andriod app is current

**Comment by JerseyEmerald** [comment]
During tree quest,  I always log out, when I logged in, participating members hp showed 50
I checked off my dailes 
Then a msg showed  -34 mana (why??)
My hp showed 50, after I did a refresh 6 times, then reload page 5 times I saw the reason 
It was all false..every team member hp ranged from 13 to 23!!!!!
I used all my up casting blessing skill to get them all up to 50!!!!!
This is extremely annoying and would have ended really bad if I didn't do all those reloads and refresh

**Comment by JerseyEmerald** [comment]
The real problem is constant reloading and refreshing the page, every single hour, every day., even when I leave messages in the chat area for the party I'm in, same happens when I go to the INN, it's ridiculous

**Comment by Alys** [comment]
A problem that might be related is described here: https://github.com/HabitRPG/habitrpg/issues/7134#issuecomment-223549787 (quest doesn't appear until logging out and relaunching browser).

I can't replicate JerseyEmerald's problem (if I use direct database update commands to adjust my party members' health, the change appears in the website after a single reload). However that's a party of four people while JerseyEmerald's has 25.

@JerseyEmerald : The next time you are checking your party members's health, please take a screenshot of the section of the party page that shows all their healths BEFORE you do any reloads, and then after EVERY reload, take another screenshot. When you've finished as many reloads as you need to see the correct data, please drag all the screenshots into a new comment here. I want to see how the health is updating each time, and the screenshots will help.

**Comment by JerseyEmerald** [comment]
![screenshot_20160603-183844](https://cloud.githubusercontent.com/assets/17463902/15794843/040e8aa4-29bc-11e6-8986-2598b538d2ba.png)
![screenshot_20160603-183853](https://cloud.githubusercontent.com/assets/17463902/15794851/12eb7b36-29bc-11e6-9b91-74cafedc2920.png)
![screenshot_20160603-184050](https://cloud.githubusercontent.com/assets/17463902/15794861/29362ada-29bc-11e6-8c4e-10079a21e14a.png)

![screenshot_20160603-184111](https://cloud.githubusercontent.com/assets/17463902/15794872/40e7bf7c-29bc-11e6-8fc1-1d880f93aba6.png)
![screenshot_20160603-184133](https://cloud.githubusercontent.com/assets/17463902/15794879/5a623374-29bc-11e6-8dca-ff82309574fe.png)
![screenshot_20160603-184043](https://cloud.githubusercontent.com/assets/17463902/15794889/69dd5842-29bc-11e6-8d47-2df7e29bdd32.png)
![screenshot_20160603-184154](https://cloud.githubusercontent.com/assets/17463902/15794909/94ac23aa-29bc-11e6-8bb6-281f6bd36438.png)
![screenshot_20160603-184319](https://cloud.githubusercontent.com/assets/17463902/15794919/a8339912-29bc-11e6-851d-63457684198e.png)

**Comment by Alys** [comment]
I've confirmed that right now, all party members have 50 hp.

GitHub isn't great at displaying multiple images clearly, so here's links to each of them:
https://cloud.githubusercontent.com/assets/17463902/15794843/040e8aa4-29bc-11e6-8986-2598b538d2ba.png
https://cloud.githubusercontent.com/assets/17463902/15794851/12eb7b36-29bc-11e6-9b91-74cafedc2920.png
https://cloud.githubusercontent.com/assets/17463902/15794861/29362ada-29bc-11e6-8c4e-10079a21e14a.png
https://cloud.githubusercontent.com/assets/17463902/15794872/40e7bf7c-29bc-11e6-8fc1-1d880f93aba6.png
https://cloud.githubusercontent.com/assets/17463902/15794879/5a623374-29bc-11e6-8dca-ff82309574fe.png
https://cloud.githubusercontent.com/assets/17463902/15794889/69dd5842-29bc-11e6-8d47-2df7e29bdd32.png
https://cloud.githubusercontent.com/assets/17463902/15794909/94ac23aa-29bc-11e6-8bb6-281f6bd36438.png
https://cloud.githubusercontent.com/assets/17463902/15794919/a8339912-29bc-11e6-851d-63457684198e.png

**Comment by Alys** [comment]
@JerseyEmerald : Have you done the reloads yet to see how the party members' health changed? If not, when you do do the reloads, take a screenshot of the section of the party page that shows all their healths before you do start the reloads, and then after every reload, take another screenshot. When you've finished as many reloads as you need to see the correct data, please drag all the screenshots into a new comment here. I want to see how the health is updating each time you reload.

If you've already done reloads to see the effects of the skills you cast earlier, then don't worry about more screenshots for now. The next time you want to check your party members' healths, please take the screenshots then.

**Comment by JerseyEmerald** [comment]
Ok here's a new set, just taking.. please note, there are no error msgs on my side..

**Comment by JerseyEmerald** [comment]
Just logged and went to part page, I was down in HP along with Lazyez8 who was at 45.7 but u can't see her hp in this
![screenshot_20160604-002441](https://cloud.githubusercontent.com/assets/17463902/15797647/8763daae-29ed-11e6-9383-908659338f6a.png)
   RELOADED PAGE..just to make sure there wasn't aby one else
![screenshot_20160604-002535](https://cloud.githubusercontent.com/assets/17463902/15797650/a48aeb7c-29ed-11e6-9d36-be8c10b55ecf.png)
    I checked off a few dailes and  leveled up..it showed hp being added to my health but it didn't change on the party screen...
![screenshot_20160604-003006](https://cloud.githubusercontent.com/assets/17463902/15797663/d89dc420-29ed-11e6-815e-7dbd13cf4cd7.png)
   I cast blessing and it didn't show either,  another reload
![screenshot_20160604-003026](https://cloud.githubusercontent.com/assets/17463902/15797667/17117a58-29ee-11e6-88f2-d9f5110bfeff.png)
Lazyez8  was still down in HP but it showed my blessing in chat room
![screenshot_20160604-003006](https://cloud.githubusercontent.com/assets/17463902/15797672/48d5de8a-29ee-11e6-8f04-b4420697227c.png)
![screenshot_20160604-003026](https://cloud.githubusercontent.com/assets/17463902/15797673/56472c5e-29ee-11e6-8a60-c543970b4c3e.png)
![screenshot_20160604-003112](https://cloud.githubusercontent.com/assets/17463902/15797680/660a666a-29ee-11e6-8785-41f028bb2470.png)
![screenshot_20160604-003201](https://cloud.githubusercontent.com/assets/17463902/15797681/7147e5d4-29ee-11e6-9790-aece02fcf25d.png) 
    Lazyez8 was still low after 3 reloads
![screenshot_20160604-003220](https://cloud.githubusercontent.com/assets/17463902/15797694/f5c2ee9e-29ee-11e6-9086-8515779dda6f.png)
  Cast blessings again...
![screenshot_20160604-003409](https://cloud.githubusercontent.com/assets/17463902/15797697/1939ef62-29ef-11e6-91c0-af37f4430401.png)
     Party page..
![screenshot_20160604-003437](https://cloud.githubusercontent.com/assets/17463902/15797699/2a49c8d6-29ef-11e6-9011-3deb22a47b2c.png)
    Chatroom
![screenshot_20160604-003449](https://cloud.githubusercontent.com/assets/17463902/15797707/60f8b7fc-29ef-11e6-9a52-8f24c5ebc295.png)
     Reload
![screenshot_20160604-003503](https://cloud.githubusercontent.com/assets/17463902/15797714/7a6e2dde-29ef-11e6-981f-935e9e8a518c.png)
   Party page
![screenshot_20160604-003527](https://cloud.githubusercontent.com/assets/17463902/15797716/8a00cf04-29ef-11e6-9aeb-db4e21fbd9cb.png)
![screenshot_20160604-003538](https://cloud.githubusercontent.com/assets/17463902/15797722/98b836ea-29ef-11e6-80ab-e89a33eacd83.png)

**Comment by jtgithub2016** [comment]
I'm using Vivaldi 1.2XXX on Windows, and having trouble getting Party status to update when issuing new quest invitations or after finishing a boss quest.  It will update if I log off, close the browser, and re-open, but doesn't seem to update short of that.

**Comment by Melissarie** [comment]
I'm having a similar issue! Although it also hasn't been letting me see more than a select handful of party members, and the party chat almost never updates so I at this point have no clue what's going on in the party anymore. I know I'm apart of a large party but has been seriously bogged down since maintenance. @Alys  
Oh and I can't see all the party members at the top anymore either :/ Just a select few, most of the inactive party members, so now I have to actively search out our active members during quests :(

**Comment by JerseyEmerald** [comment]
Also, I have the same problem that's reference  in   #7393

**Comment by crookedneighbor** [comment]
I'm working on this now.
