### ISSUE TITLE
Not recieving awards of a pet quest

### ISSUE THREAD

**Issue by luhm** [HabitRPG/habitica#7579]
General Info
UUID: 551e07b9-9c6b-4d59-835a-bba077de6911
Browser: Chrome
OS: Windows 7
### Description

My group completed the pet quest of Zombie Sabre Tooth and I had recieved the invitation for it day may 29th and accepted it by the Android APP. The last 3 days I only used the Habitica Andoid APP, and when I entered the habitica website interface today I recieved another invitation but for the same quest! I accepted again and entered my group's page. Then I saw that this quest had already been finished and the invitaton that is open is for another quest (The night owl)! I haven't recieved neither the rewards of the first one, neither the invitation for the second one.
I have already accepted the new invitation by the button in the group's page, but I don't know what happened with the Zombie Sabre Cat's rewards and all.

**Comment by quin-jay** [comment]
@luhm Just to confirm: Did you see in party messages that you were doing damage to the boss?

**Comment by Alys** [comment]
You're already a participant in the Owl quest - you can confirm that by looking at the participant list on the website's party page (reload the page to ensure you're seeing the latest information). You would have accepted it when you accepted the incorrect Sabre Tooth invitation (basically, you **were** given the invitation for the Owl quest, but there was some incorrect cached data in your account that made it look like a Sabre Tooth quest - we're making a code change to prevent that happening).

You aren't shown in the quest progress log as someone who attacked the Sabre Tooth boss, but the quest was over in less than a day so it might have just been too fast for your damage to register. :) I've given you the quest rewards and achievement. Reload if you don't see them straight away.

**Comment by luhm** [comment]
Thank you!
I'll pay more attention next time to be certain that I am participating in the quests I accept.
:)
