### ISSUE TITLE
Add back drop tracking for analytics

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7581]
### Description
#7547 moved some drop-related code around in such a way that we no longer send drop data to our analytics providers. It's not one of our top needs, data-wise, but it would still be nice to have again. We should implement it in the server code for drops instead of on the client.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by lemoness** [comment]
That's a question for @SabreCat!

I've updated the labels on this ticket.
