### ISSUE TITLE
Party's chat box does not update

### ISSUE THREAD

**Issue by Aschkal** [HabitRPG/habitica#7582]
As in the title, the chat box for my party does not update.
The time of when the messages were sent keeps increasing but no new message appears. It happens for both chat messages and activities.

UUID: b393a2e7-239d-4782-9851-a9f57d0c72a6
Browser: Google Chrome
OS: Ubuntu (16.04)

**Comment by crookedneighbor** [comment]
This is expected. The chat is not real time (yet!), you need to press the fetch chat messages button.
