### ISSUE TITLE
Already in Party 

### ISSUE THREAD

**Issue by lizbernstein** [HabitRPG/habitica#7584]
General Info
- UUID: 4ae99914-c77a-4939-af33-c15dbf8a9ae3
- Browser: Chrome
- OS: Windows 10 
### Description

[//](#): # My friends and I just joined. I tried to invite them to a party, but every time I try it says they're already in a party (even though they're not, obviously).

**Comment by crookedneighbor** [comment]
Do you have your friend's user id?

**Comment by lizbernstein** [comment]
Yes. It does it for both of them. I just had one of them invite me and it
worked though.

**Comment by crookedneighbor** [comment]
I meant, could you post your friend's user id so I can check the database and see if there's any strange data in their account that would prevent you from inviting them. It sounds like you're now successfully in a party with them, so I'm going to close this.
