### ISSUE TITLE
Bug: Lost my gems

### ISSUE THREAD

**Issue by Balduranne** [HabitRPG/habitica#7585]
Hello,

I'm not sure what happened, but all my gems for June (I'm a subscriber) disappeared after I had bought a scroll for them.
The gold is gone, and I can't buy more gems, I was only able to get one after this happened.

My user ID is 44a335a6-e09a-4537-b4c4-8b6fc7f81953
I'm one Chrome, Win10

**Comment by Alys** [comment]
Can you tell us what you mean by "after I had bought a scroll for them"? Do you mean you bought a quest scroll with gems, or something else?

How many gems did you have before that, and how many just after?

If you did buy a scroll, do you still have it?

**Comment by Balduranne** [comment]
I bought 45 gems with gold, purchased a Tangle Tree scroll (With Gems). After that I either clicked on the scroll I bought or tried to get a different one, but the 45 Gems just disappeared, along with the gold I used to buy it and the quest scroll I got.
For some reason after that I could buy a single gem for the remaining gold (Which I did). Right after the bug happened I only had one gem that I had left from the previous month.

To reiterate: Gold gone, gems gone, scroll gone.

**Comment by Alys** [comment]
I've given you back the missing 44 gems. If you're still short of gold, Settings > Site > Fix Character Values will fix that for you. Best guess I can make is that this was some sort of error with the website not syncing correctly with the server but still acting as if it was working and storing changes in local storage, but then not syncing them to the server later. We're getting rid of local storage to stop things like this happening.
