### ISSUE TITLE
Missing Contribution Guidelines

### ISSUE THREAD

**Issue by awitherow** [HabitRPG/habitica#7589]
As I look through a lot of these pull requests, I see a lot of inconsistency in the code being implemented. I would like to head an effort to creating a contributing.md file to help standardize the codebase.

**Comment by paglias** [comment]
@awitherow we do have a CONTRIBUTING.md file https://github.com/HabitRPG/habitrpg/blob/develop/.github/CONTRIBUTING.md

Regarding inconsistencies in the code we've done a full refactor of the server code and it's is now completely consistent and linted using ESLint. The client side code will adopt a standard code style as soon as we start refactoring it too.

**Comment by paglias** [comment]
Feel free to propose any improvement to the existing contribution guildelines and current client side code, just keep in mind that because a client side code refactoring is being planned right now we're not actively improving the code style and any work may be undone as soon as the refactoring starts

**Comment by awitherow** [comment]
Refactoring should be a rolling process, the features and bugs aren't going to stop coming in... should start making small changes towards standardization within every PR 😄 but yeah sure, I'll look into it.

**Comment by paglias** [comment]
@awitherow when I talk about refactoring I mean a complete rewrite of the client side code moving away from Angular 1, right now it doesn't make sense for us to spend time and resources of the core team in refactoring a code that will be replaced soon

**Comment by awitherow** [comment]
@paglias are you guys going to be going Angular 2 or have you considered rewriting in React? I'm quite biased to React, but I've been really enjoying the maintainability of React with Atomic principles.

**Comment by paglias** [comment]
@awitherow we've shortlisted React and [Vue](https://vuejs.org/)
