### ISSUE TITLE
Character death due to refresh 

### ISSUE THREAD

**Issue by smokey186** [HabitRPG/habitica#759]
Hello, I've twice had an issue where I simply refresh my page, and all the of negative hp refreshes along with it, basically double hitting me with an unfair amount of negative points, killing my character. 

Is there any way to sort this out or perhaps even revert the last changes? I lost a level 7 the first time and just lost a level 9 i believe. . It's very frustrating to get pretty far along, refresh, and find you're suddenly dead.

**Comment by wc8** [comment]
Does it happen at a specific time of day? Does it happen at all near the custom start date or midnight?
In the meantime... for bug induced deaths: check out Restore under Settings in the drop-down menu where you login.

**Comment by smokey186** [comment]
Ah, thanks, hadn't noticed the restore function, could have saved myself loads of trouble there. Thanks.

It just seems to happen on a refresh, after not completing a task, I refresh, and the negative points are applied again.

**Comment by wc8** [comment]
#777 perhaps

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
