### ISSUE TITLE
Challenge names changed into "challenge-name"

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#7591]
Several challenges had their names replaced with "challenge-name" during the API change.

Examples:
- All challenges in the [Fighters Guild](https://habitica.com/#/options/groups/guilds/b70667de-9c04-43f8-bbaa-924640489ddb)
- this [Tavern challenge](https://habitica.com/#/options/groups/challenges/7d78870c-5473-496a-b1cd-bdb288590c7a)

I didn't search for others.

I've seen it on the website (with various different browsers). It has been mentioned in various guild chats by different people (so it's not something to do with my account). According to one user's post it has also happened to a party challenge.

I'm surprised this hasn't been reported before. (Please delete/close/merge this issue if it has!)

**Comment by UnexpectedMushroom** [comment]
Here are a few others:

https://habitica.com/#/options/groups/challenges/56825dea-5761-48f3-9068-ddb14280a554
https://habitica.com/#/options/groups/challenges/e1c22fa4-d4de-4731-8482-03a929ffbd07
https://habitica.com/#/options/groups/challenges/d7a0da37-b793-4722-a933-e9f0ea3561e4
https://habitica.com/#/options/groups/challenges/83ddb5f5-8e36-47b8-9f90-3649e369906d

This one was called "Learn ASL"
https://habitica.com/#/options/groups/challenges/8be28417-eb81-49cc-b07e-f5e6ee47bb32

**Comment by Alys** [comment]
We'll do a search for all challenges with that incorrect name and adjust them all to use the names that existed in a backup of the site from just before Maintenance. 

I'll do that this weekend if no one else does it first (other admins: feel free to if you want to).
NOTE: Several of the challenge owners now know about this problem and are likely to fix it in their own challenges, so we should be careful to not overwrite their changes - e.g., search for affected challenges, find their correct names, then do another search just before applying the fixes to avoid any that have already been changed (the owner's most recent choice of name should take precedence over the one from the backup).

**Comment by Alys** [comment]
Ugh. About 430 challenges affected. I'm definitely cleaning this up today.

**Comment by Alys** [comment]
All of the challenges that had the name "challenge-name" now have the name that they had before the migration, except for the ones listed below. Previously, they had no name (an empty string); now they have the name "no name". They're likely to be test challenges, or otherwise unneeded, so I'll look through them a bit later today.

**Comment by Alys** [comment]
And I've just realised some might have private information so I've deleted that list.

**Comment by Alys** [comment]
Out of those "no name" challenges, all but two had no tasks, description, nor gems, so I deleted them. The other two had tasks so I left them alone.

All done.

Thanks for reporting this @habitrpguser and @UnexpectedMushroom! We hadn't previously known about it.

**Comment by UnexpectedMushroom** [comment]
np ^^
