### ISSUE TITLE
Music & Sound Effects?

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#76]
_Note by wc8: Vote Here: [Music & Sound Effects](https://trello.com/c/tljx8gKC)_
What do we think of music / sound-effects? Obviously opt-in, and disabled by default - but option to enable? I'm thinking sound effects for leveling, music for boss battles, etc

**Comment by racuna** [comment]
In the future mobile app would be amazing (not so much in the webapp at the office)

**Comment by scottsheffield** [comment]
Hell, a mute button would fix the office situation problem. I think sound effects should maybe be disabled by default and have the tour mention them specifically.

Sound effects for tasks (two, one for completing, one for failing) would be nice. Maybe have separate sound effects for each part of the process. For example, I click [+] on a task to complete it, and a success chime sounds out, then a beat later my XP goes up with an XP up sound effect to go with it. And I click on a [-] to mark failure of a task, I get a down-ish sound, and a beat later my guy grunts or "ow!"s.

Maybe a glissando up proportional to how much of the bar was increased? And of course, a DING or some kind of success jingle would be great for levelling up. Maybe both (one followed by the other). 

I imagine something between full on 8bit (NES) and 16 bit (SNES) for the instrumentation. If you wanted to get real fancy with theming and such, you could have different themes to match different classic gaming eras, with music and sound effects to match. Color scheme goes blue with white text, simple graphics for the Commodore 64 theme, complete with filtered low-fi analog synth sound effects. Color scheme has a bit more polish and higher (but still low) resolution for the 16bit SNES style theme, complete with downsampled wav sound effects and simple wavetable synths.

I realize the themeing gets outside of the music question here, but I think a lot of fun could be had there. Maybe include that as a kickstarter goal? Reach x level of funding and get certain bonus themes?

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.
