### ISSUE TITLE
after accepting a guild/party invitation, the invitation persists

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7600]
If you accept a guild invitation, the invitation is correctly deleted from your user document in the database, but it still appears in the browser until you reload. If you try to accept it again, you receive an error message (which is expected and correct, but not user-friendly).

The desired behaviour is that as soon as you've accepted the invitation, the notification for it should be removed from the notification icon in the menu bar.

**Comment by Alys** [comment]
(sorry, misclicked on submit).

If you accept a guild invitation, the invitation is correctly deleted from your user document in the database, but it still appears in the browser until you reload. If you try to accept it again, you receive an error message (which is expected and correct, but not user-friendly).

The desired behaviour is that as soon as you've accepted the invitation, the notification for it should be removed from the notification icon in the menu bar.

**Comment by Hus274** [comment]
I'll have a fix out for this shortly.
