### ISSUE TITLE
Transparent glasses files

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7601]
The current glasses are not transparent, which makes it look odd when your avatar is sleeping. Here are new glasses files by James Danger that have transparent lenses! They should replace the old ones.

![top_frame_-_black-2](https://cloud.githubusercontent.com/assets/3494081/15795635/5ac13b58-29a8-11e6-8294-d15ea3dbf4d6.png)
![top_frame_-_blue-2](https://cloud.githubusercontent.com/assets/3494081/15795636/5ac5d7da-29a8-11e6-95ce-ac7f330cb452.png)
![top_frame_-_green-2](https://cloud.githubusercontent.com/assets/3494081/15795634/5ac0d99c-29a8-11e6-9d7f-a609fd9e6348.png)
![top_frame_-_pink-2](https://cloud.githubusercontent.com/assets/3494081/15795641/5acec426-29a8-11e6-8976-317e3ab321a2.png)
![top_frame_-_red-2](https://cloud.githubusercontent.com/assets/3494081/15795638/5ace7cdc-29a8-11e6-9021-49240ee5cf82.png)
![top_frame_-_white-2](https://cloud.githubusercontent.com/assets/3494081/15795637/5acccc98-29a8-11e6-92d9-719b36953d44.png)
![top_frame_-_yellow-2](https://cloud.githubusercontent.com/assets/3494081/15795642/5adfe3aa-29a8-11e6-87f4-dd0d9e502093.png)

**Comment by Maslor** [comment]
I have 2 questions:
1 - On which branch should I change the files?
2 - Do you know what the file is that references the current glasses?

**Comment by Maslor** [comment]
I got this @lemoness

**Comment by Maslor** [comment]
I downloaded each of the files, changed their names to the current glasses names and overwrote them in the eyewear directory.
