### ISSUE TITLE
Subscription benefits code needs refactoring/future-proofing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7602]
### Description

With #4819 closed, loyal subscribers should be getting their Mystic Hourglasses and related benefits on schedule again. However, this error resulted from the subscription award logic (https://github.com/HabitRPG/habitrpg/blob/develop/website/server/libs/api-v3/cron.js#L47-L69) being a bit unnecessarily complex and difficult to follow. We may be able to write cleaner logic that e.g. dispenses with the `purchased.plan.consecutive.offset` countdown.

**Comment by TheHollidayInn** [comment]
I'm going to close this because:
1. I am working on cron refactoring in another PR
2. Because issues of refactoring should defer to our codecliamate: https://codeclimate.com/github/HabitRPG/habitrpg/website/server/libs/cron.js and our internal processes
