### ISSUE TITLE
Text on not-due dailies has become dark

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7605]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 46.0.1
- OS: Windows 7
### Description

Text on done and grey dailies (and done to-dos) is the same color as it is on due tasks. (My browser says that's rgb 51 51 51 (#333333).)
#### Console Errors

None.

**Comment by crookedneighbor** [comment]
Whoops, this was me. Fixed. Will go out with the next deploy.
