### ISSUE TITLE
Vivaldi Todo Creation/Update Issue

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#7608]
General Info
- UUID: e44e6069-2e30-49cf-ab49-db41d3134045
- Browser: Vivaldi 1.2XXXX
- OS: Windows
### Description

Having trouble with creating/updating Todos in Vivaldi:
1) Sometimes (but not always) I cannot get a checklist to manifest within the Todo.  So I write a Todo, assign a name, difficulty, etc.  But if I go back later to add a checklist, it will not be visible after I save the Todo.  If I reopen the Todo to edit it some more, the checklist will be there, but then if I save it, the checklist will not be visible, making it impossible for me to check off items.  This is a fairly rare occurrence.

2) More recently, I've been having trouble with checking and unchecking Todos.  The system did not seem to be responding, so I checked the "done" box twice.  This resulted in a second, undone Todo being checked as done.  So I went into my completed Todos, but could not uncheck it.  The incorrectly completed Todo was visible, but I could not uncheck it.  

3) Where do I go to report typographical errors & suggest language fixes?  Some of the Chinese text for the website seems off to me, and I would like to propose fixes.

**Comment by Alys** [comment]
Vivaldi is a relatively new browser, so it might have non-standard behaviour (I use it myself and love it, and I know it's based on Chrome, but it does have differences). Are you able to use Chrome for a while to see if the same problems occur?

When you notice the checklist being invisible in the To-Do (on any browser), please take a screenshot of the To-Do in edit mode, and in normal mode. Come to this issue to drag the screenshots into a new comment (attaching them to an email won't work).

I can't replicate the To-Do unchecking problem on Vivaldi. Unchecking a complete To-Do works as normal. When you say that you could not uncheck it, can you give more details as to why? For example, do you get an error message, or is there no checkbox to untick, or do you untick it and then it becomes reticked by itself, or does clicking on the checkbox not do anything?

Are there any error messages in the JavaScript console for either of these problems?

Typographical errors in the English version of the website can be reported in GitHub.

For problems with translations, please see [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists) - if you'd like to help with translations, that will show you how. If you'd just like to report translation problems, you can do so in the "Commonwealth of i18n" guild, and someone else will make the change.

**Comment by jtgithub2016** [comment]
Ok, thanks.

**Comment by Alys** [comment]
@jtgithub2016 I'm closing this now, but if you still need help, please post again here and give us whatever answers you can from my questions.
