### ISSUE TITLE
Turns back time when I level up

### ISSUE THREAD

**Issue by janepernille** [HabitRPG/habitica#761]
I just leveled up from level 2, and when I refreshed it was like my profile went back in time. Old todos came up and I was back on 47/160 xp

I think this has happened several times as well. 

User-ID: c336c106-03fc-4954-a611-e3cea91a87d5

**Comment by janepernille** [comment]
I just went to settings and restored myself --> Thank you for that option :)

**Comment by rixx** [comment]
Might be related to #777?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
