### ISSUE TITLE
Pop-ups with pet names do not disappear

### ISSUE THREAD

**Issue by mleah** [HabitRPG/habitica#7610]
#### General Info
- UUID: 2fd8e68b-4105-4bba-9378-82e4f64c858c
- Browser: Google Chrome Version 50.0.2661.102 (64-bit)
- OS: Mac OSX Yosemite
#### Description

While on the pets page, I began feeding many of my pets.  As each one grew into a mount, the pop-up with the pet name below the corresponding pet remained.  The pop-ups didn't disappear when scrolling or clicking on them.  They only disappeared when I navigated away and came back to the page.  Additionally, just feeding a pet without it growing into the mount does not make the pop-up remain.
##### Steps to reproduce
1.  While on the pet page, feed pets their favoured food.
2.  When pet grows into mount and mount pop-up appears, click "Ride Later."
   2b.  The pop-up below the pet that just grew into a mount remains on the view.
3.  Continue steps 1-2b two more times with different pets.
4.  Navigate to market page, then back to pet page.  Pop-ups below pets have disappeared.
###### Multiple Pop-ups

![screen shot 2016-06-05 at 2 49 43 pm](https://cloud.githubusercontent.com/assets/10436592/15807481/550ca75c-2b2d-11e6-98d7-dfc3092ccdfb.png)
###### HTML Elements

![screen shot 2016-06-05 at 2 50 59 pm](https://cloud.githubusercontent.com/assets/10436592/15807482/56f0193c-2b2d-11e6-8c2d-b58b3774bf7d.png)
#### Console Errors

There was one js warning, but I don't think it is related as it is linked to a different app issue.  I've included it below just for documentation purposes.

![screen shot 2016-06-05 at 2 54 27 pm](https://cloud.githubusercontent.com/assets/10436592/15807500/c7f084fa-2b2d-11e6-87b2-80bbc1d17eda.png)

**Comment by citrusella** [comment]
Probably a similar issue to #7517 , #7521 , and #5180 . (Just for reference.)

**Comment by SabreCat** [comment]
Definitely the same category of trouble, if not an exact duplicate. This is not something we'll likely tackle until rewriting the Web frontend in a new framework later this year, but if a contributor submits a good solution, we're happy to have it!

**Comment by khipkin** [comment]
@Alys I think this can also be closed because of the redesign.

**Comment by Alys** [comment]
True. It's low priority and it will be made redundant by the upcoming website improvement project so I'm closing it.
