### ISSUE TITLE
Flower not appearing on any avatars

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7613]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 46.0.1
- OS: Windows 7
### Description

Flower does not show up at all on avatars when equipped. (I even took all head equipment off in case it was under it for some reason.) I could test it when transformed with a shiny seed... but I kind of wanted to wait until I was a rogue to use the seed again. :-/
#### Console Errors

No console errors (or anything suspicious in the network tab, which I also checked).

**Comment by crookedneighbor** [comment]
Uhg. Clearing I didn't test this well enough before merging. I'll look at this and fix it.
