### ISSUE TITLE
New tag can't be moved (without manually reloading the page)

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#7614]
General Info
- UUID: 1aff9116-34b0-438c-9877-06038bdce161
- Browser: several (Chrome, Firefox)
- OS: Windows (website bug, not app)
### Description

When trying to move a new tag directly after creating and saving it, I get the error message "No tag item was found with given id." Once I've reloaded the page in my browser, everything works fine again.

I've also tried creating the tag, then doing another Habitica action, then reordering the tags - with mixed results: When I clicked a daily, it worked, when I clicked a habit, it didn't. (It doesn't have to be the difference between daily and habit though - I didn't test it much and didn't try to establish a rule. But apparently not every little Habitica action is enough as a workaround.)

My totally uninformed guess is that, when "Save" is clicked after editing tags, no (or insufficient, or incorrect) syncing happens, and that maybe the bug could be fixed by changing that.

As far as I'm concerned, you don't have to answer to this immediately, or at all (before you get around to trying to fix it). I know you're currently swamped with other bugs (some high priority), this one has a simple workaround (reloading the page in your browser), and most people don't create new tags every five minutes. So take your time! :)
#### Console Errors

?? Should I write the error notifications here that appear briefly in the upper-right corner of the screen? In that case, that's

"No tag item was found with given id."

**Comment by Alys** [comment]
I've merged this with https://github.com/HabitRPG/habitrpg/issues/7820 so I'm closing this now.
