### ISSUE TITLE
Party Page Requires Manual Reloading Since Maintenance

### ISSUE THREAD

**Issue by PendragnJenna** [HabitRPG/habitica#7616]
General Info
- UUID: e77d6c97-8850-4f31-bd46-c412243d6035
- Browser: Chrome
- OS: Mac OS X 10.11.5
### Description

Since big maintenance weekend, the Party page doesn't show new quest invitations, update party member HP, or show new messages unless you both "Fetch New Messages" and manually reload the page in the browser. The new message notification icon also continues to display even after having visited the Party page, unless you "Fetch New Messages" to clear it. Before the maintenance upgrade, all of this happened automatically when visiting the Party page, so it's now a slower and more manual process, making it a usability downgrade rather than an upgrade.

**Comment by JerseyEmerald** [comment]
Refer to #7578
