### ISSUE TITLE
Dying when I log in the next day

### ISSUE THREAD

**Issue by GrandBastard** [HabitRPG/habitica#762]
Pretty much the title. I was not using it for a while but came back to HabitRPG, the character had died obviously, but then the character has continued to die for the the past few days every time I log in again the next day. I have now used restore and given myself a level 5 to see if it happens again once I re-log tomorrow.
I will update and tell you what happens. In the meantime, any other tips?

With much love,
GrandBastard

**Comment by wc8** [comment]
If you skipped habitrpg for awhile, you probably have many orange/red/dark red daily tasks. Anytime you miss them, they'll exact a hefty HP loss. Reroll will reset them to yellow.

**Comment by wc8** [comment]
P.S. if you're finishing everything and still dying, that's different. In that case, certainly reply back.

**Comment by GrandBastard** [comment]
Hey thanks, 
That seems to be the issue, forgot about dark red items.

**Comment by wc8** [comment]
I'll close this then, if it seems to have occurred for a different, unexpected reason, reply back and it can be reopened.
