### ISSUE TITLE
Orb of Rebirth and Reset do not clear buffs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7623]
When you use an Orb of Rebirth or Reset, the buffs to your Constitution, Intelligence, Perception, and Strength are not set to zero. I believe they should be because a level 1 player with large buffs has a very different experience than a player with no buffs.

In addition, players occasionally try to use Reset to get rid of extremely high buffs (and hence levels) given by over-enthusiastic party members, and that fails since the buffs remain, and leveling up still happens too quickly.

The data to change is this (showing the desired values after Rebirth):

```
        "stats.buffs": {
            "con": 0,
            "per": 0,
            "int": 0,
            "str": 0,
        },
```

I'll leave this open as suggestion/discussion for a few days, then depending on feedback, mark it as help welcome.

**Comment by SabreCat** [comment]
Seems uncontroversial to me. Reset and Rebirth are supposed to be slate-cleaners; this was an oversight, not anything desirable.

**Comment by crookedneighbor** [comment]
Do it.

**Comment by keysmashes** [comment]
On rebirth, `user.stats.buffs` is already set to an empty object (`{}`), in two places ([line 50](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/ops/rebirth.js#L50) and [line 98](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/ops/rebirth.js#L98)). Does it need to be prefilled with all attributes set to 0 instead? If so, I'm happy to fix this.

**Comment by paglias** [comment]
Hmm strange... it could be due to that mongoose bug that was solved in the last version. Can someone check if it's still happening?

**Comment by paglias** [comment]
I'll check it, be sure to run `npm update` before trying

**Comment by paglias** [comment]
Confirmed

**Comment by paglias** [comment]
Opened an issue in the mongoose repo https://github.com/Automattic/mongoose/issues/4218

**Comment by paglias** [comment]
This should be fixed once the next patch version of Mongoose gets released.
