### ISSUE TITLE
Cannot set property 'new Messages' of undefined when visit inbox

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7626]
General Info
- UUID: 
- Browser: Opera
- OS: Android
### Description

I got email about new message, followed the link and got the blue notification message: Cannot set property 'new Messages' of undefined.

**Comment by librarianmage** [comment]
I don't get this error when I go to the Inbox. Is this fixed?

**Comment by Alys** [comment]
I don't recall seeing it for ages. Let's assume it's fixed. Thanks @MathWhiz !

If anyone notices this still happening, comment here and we'll reopen this.
