### ISSUE TITLE
Toggl Button no longer appears on tasks

### ISSUE THREAD

**Issue by mike-s-6** [HabitRPG/habitica#7628]
General Info
- UUID: 024f7c53-a21c-48b8-a813-1d7d0dd2642e
- Browser: Chrome 51.0.2704.79
- OS: Windows 7
### Description

The Toggl button extension no longer appears on the tasks, as described in  http://habitica.wikia.com/wiki/Toggl

This is how it appears for me:
![sampletask](https://cloud.githubusercontent.com/assets/19829115/15916256/4e365740-2e23-11e6-93bb-0465c8b4f3c6.jpg)

I have tried updating the extension, removing and reinstalling the extension, updating my browser, clearing browser cache, cookies, log in and out of habitica.
#### Console Errors

I am looking at the background page for the extension, and there is this error, although I'm not sure if it is relevant.

> https://www.toggl.com/api/v8/me?with_related_data=true Failed to load resource: the server responded with a status of 403 (Forbidden)
> background.js:494 GET https://www.toggl.com/api/v8/me?with_related_data=true 403 (Forbidden)
> ajax  @   background.js:494
> fetchUser @   background.js:88
> newMessage    @   background.js:1270
> target.(anonymous function)   @   extensions::SafeBuiltins:19
> EventImpl.dispatchToListener  @   extensions::event_bindings:388
> target.(anonymous function)   @   extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @   extensions::utils:151
> EventImpl.dispatch_   @   extensions::event_bindings:372
> EventImpl.dispatch    @   extensions::event_bindings:394
> target.(anonymous function)   @   extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @   extensions::utils:151
> messageListener   @   extensions::messaging:205
> target.(anonymous function)   @   extensions::SafeBuiltins:19
> EventImpl.dispatchToListener  @   extensions::event_bindings:388
> target.(anonymous function)   @   extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @   extensions::utils:151
> EventImpl.dispatch_   @   extensions::event_bindings:372
> EventImpl.dispatch    @   extensions::event_bindings:394
> target.(anonymous function)   @   extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @   extensions::utils:151
> dispatchOnMessage @   extensions::messaging:336

**Comment by crookedneighbor** [comment]
Our own @SabreCat opened a PR on the extension to fix this. Should go out in the next release. 

See https://github.com/toggl/toggl-button/issues/570
