### ISSUE TITLE
Cannot boot user from party

### ISSUE THREAD

**Issue by tjittedevries** [HabitRPG/habitica#7630]
General Info
- UUID: c6662b6c-8958-402a-a9e9-36dbdd2e8cdb
- Browser: 51.0.2704.84 m
- OS: Windows 10
### Description
- I invited someone to my party, this user says the invite was never delivered. So we agreed to re-invite them. 
- I'm booting this user from the party, I click the button, the user disappeared from the list. Now I reload Habitica, or I switch to some screen and then back to the Party screen, and the booted user is back in the list.
- I tried clearing the cache, booting member, clear the cache, boot the member routine, doesn't work either.
- I tried this during a quest, and after we finished a quest and no quest was active.

In the end, I cannot boot a member from my party.
#### Console Errors

No errors here, only some soft deprecation warnings.
In the Network panel I get a success in the response on the JSON request.

**Comment by Alys** [comment]
I've found the two player who have invitations to your party. The invitations look correctly formatted so I'm not sure why they aren't appearing. Please ask them to log out of the Habitica website, then log back in, and click on the notification icon in the menu bar. If they still can't see the invitation notification there, they should take a screenshot of the notification icon with all the notifications dropped-down (i.e., when they see after they click on the icon). They should then go to their party page, reload it using their browser's reload or refresh button, and if they don't see the invitation accept/reject buttons, take a screenshot of the page.

**Comment by Alys** [comment]
Ah, one of them (MadMouze) is actually already in a party. They'd need to leave that party before they could accept your invitation, and in fact I'm not sure that it should have been possible to invite them. The other one is not in a party.

**Comment by tjittedevries** [comment]
Ok, so one user has now joined the party using the story you've written. So the reason for this ticket has been solved, booting members hasn't though.
Is there a way to boot MadMouze from the party, as he is in another already?

**Comment by Alys** [comment]
Can you give me MadMouze's User ID? I think if you click on his name, you'll be able to see his profile. I didn't keep my data from yesterday that had his ID in it.

**Comment by tjittedevries** [comment]
020225f7-c8d5-4914-a7f6-04f948f5caf4

**Comment by Alys** [comment]
I've deleted the invitation to your party from MadMouze's account.

I'm leaving this issue open because I want to try to replicate the bug to see if it's a code error or a once-off glitch. Possibly the code to revoke invitations doesn't work if the player is in another party.

**Comment by Alys** [comment]
I haven't seen other examples of this so I think it's been fixed by a code change. I'm closing it but we can reopen if it happens again.
