### ISSUE TITLE
Disallow @habitica.com email addresses for new accounts

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7633]
### Description

It's possible when signing up for a Habitica account to specify a habitica.com email address. That causes all notification emails meant for the new user to arrive in the administrative inbox.

Pending a more thorough email verification workflow, we should at least disallow @habitica.com email addresses when validating the field, so people are clear that they should specify an email address they already own rather than a hypothetical new Habitica address. (If we add any new administrators to the list of legitimate habitica.com addresses, we can associate those with Habitica accounts by hand!)
#### Console Errors

N/A

**Comment by librarianmage** [comment]
I can try this! Should it be server-side, client-side, or both?

**Comment by crookedneighbor** [comment]
Server side for sure. We can add client side later if needed.
