### ISSUE TITLE
Minor Icon Fixes

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7635]
A few of the icons for helms incorrectly had outlines, but Balduranne has fixed them. They'll need to be added to the game :)

![icon-rmw-helmet-2](https://cloud.githubusercontent.com/assets/3494081/15952223/e50165f2-2e73-11e6-8d11-f2bc0013a2c4.png)
![icon-miner-helmet-3](https://cloud.githubusercontent.com/assets/3494081/15952222/e5013212-2e73-11e6-896b-bdf5c04c4bb7.png)
![icon-archer1-hat-3](https://cloud.githubusercontent.com/assets/3494081/15952224/e501cb5a-2e73-11e6-9d27-c225f97228aa.png)

**Comment by Hus274** [comment]
I can take this up.

**Comment by Hus274** [comment]
It looks the following also have this outline:
shop_head_special_spring2016mage.png
shop_head_armoire_dragonTamerHelm.png
