### ISSUE TITLE
v3 API Documentation

### ISSUE THREAD

**Issue by eshapard** [HabitRPG/habitica#7637]
I think the documentation for the v3 API has a typo.

The url for reqesting a single task seems to be:

```
https://habitica.com/api/v3/tasks/:taskId
that's taskS with an S!
```

At least, that's what's working for me; not

```
https://habitica.com/api/v3/task/:taskId
```

as described at: https://habitica.com/apidoc/#api-Task-GetTask

**Comment by crookedneighbor** [comment]
Good catch. Want to make a PR?

**Comment by eshapard** [comment]
I would, but I don't really know how PRs work... not that savvy with github.

**Comment by crookedneighbor** [comment]
You sure? I can point you to the line that needs changing: https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/tasks.js#L231

**Comment by eshapard** [comment]
Thanks, I updated that code and created my first pull request.

Looks like that line was commented out, though. Is there some other program
that generates the documentation based on those comments?

**Comment by crookedneighbor** [comment]
We use http://apidocjs.com/ to generate the docs.
