### ISSUE TITLE
Can not add new Webhook (the "enabled" parameter should be a boolean)

### ISSUE THREAD

**Issue by kdemerath** [HabitRPG/habitica#7640]
General Info
- UUID: 0b697098-44b7-47bb-9844-4a5129f0947b
- Browser: Chrome 51.0.2704.84 m
- OS: Windows 10
### Description

When trying to add a new Webhook under https://habitica.com/#/options/settings/api by adding a valid URL and pressing "add" button the following message appears: the "enabled" parameter should be a boolean

**Comment by crookedneighbor** [comment]
This has just been fixed and will go live this week.

See https://github.com/HabitRPG/habitrpg/pull/7622
