### ISSUE TITLE
Undoing daily task doesn't remove received item from user's inventory

### ISSUE THREAD

**Issue by viktoradavid** [HabitRPG/habitica#7644]
UUID: bb7bc7ae-d12c-4275-b054-fa14902b224d
Browser: Chrome Version 46.0.2490.80 (64-bit)
OS: Linux 3.13.0-24-generic

After finishing a daily task, user can receive XP, money and items. After **undoing** the daily task, received XP and money are taken from the user, but received item remains in user's inventory. Finishing the task again grants the user the same item again. This allows farming infinite number of items. 

I also wonder what would happen after undoing a daily task after user spends the money received, unable to test this now.

**Comment by paglias** [comment]
@Fanarim there's a limit to the number of drops you can get daily. Also there are other ways to cheat like creating many tasks. Cheating is possible and there's no way we can prevent it from happening given the way Habitica works  but in the end if you cheat it'll only affect yourself.
