### ISSUE TITLE
Habitica Page Just Keeps Loading?

### ISSUE THREAD

**Issue by thebadwolfgirl** [HabitRPG/habitica#7646]
General Info
- UUID: 
- Browser: Chrome
- OS: Windows 10
### Description

For a few days now, Habitica won't open properly on my laptop. It will just keep loading? It works just fine on my Kindle Fire, but if I try to open it on my laptop, all it does it give me this loading screen:

![image](https://cloud.githubusercontent.com/assets/17323884/15985280/34583b56-2fb6-11e6-9984-2f2dca8e8184.png)

I waited for ten minutes and nothing happened, it just kept loading. So I've been having to use Habitica on my Kindle Fire, which does not have a very speedy browser. 
Any help would really be appreciated!

**Comment by Alys** [comment]
Go to http://habitica.com/static/clear-browser-data and click the button you'll see there, then clear your browser's cookies for the "habitica.com" domain. After that, you should be able to log in.

This works in nearly every case that we've seen of this problem, so I'm going to close this issue now, but if it doesn't work for you, do please comment here and we'll reopen it as soon as we see your comment!

**Comment by thebadwolfgirl** [comment]
Oh my goodness thanks! =D

**Comment by paglias** [comment]
We should add a link to that page if loading takes more than x seconds

**Comment by thebadwolfgirl** [comment]
Ya I totally agree!
