### ISSUE TITLE
can't log in after manually clearing all local storage data; clear-browser-data button does not work

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7652]
General Info
- UUID: d904bd62-da08-416b-a816-ba797c9ee265
- Browser: Chrome Version 51.0.2704.79 (also Vivaldi, a Chrome-like browser)
- OS: Ubuntu 16.04
### Description
1. I manually deleted all local storage data for habitica.com. 
2. Go to https://habitica.com/
3. After a moment, the URL changes to https://habitica.com/#/tasks (as expected) and the following items appear in local storage:
   ![screenshot from 2016-06-12 08-09-14](https://cloud.githubusercontent.com/assets/1495809/15987683/ffad2e1a-3074-11e6-9b1a-bfd23f798b69.png)
   The final one (in grey) appeared a second after the others
4. The loading page doesn't change - the loading dots just keep cycling.
5. Nothing is in the console
6. When I go to https://habitica.com/static/clear-browser-data this appears in the console:
   ![image](https://cloud.githubusercontent.com/assets/1495809/15987697/9be27cc2-3075-11e6-9571-9402b3a07345.png)
7. When I click the red "Clear Local Storage" button, the button itself responds to show that I've clicked on it, with that little kind of jiggle it does, but nothing else happens. No other messages appear in the console.
8. The Play button in the header on the clear-browser-data page behaves the same way as the clear button.
9. If I go to the Contact Us page from the links in the header, the console becomes clear and the play button now brings up a login form.
10. When I log in, the loading screen appears again but then after a couple of seconds it disappears and I am successfully logged in to the site.

I've seen one other person report that the clear-browser-data button does nothing, so they were probably having the same problem.

**Comment by Alys** [comment]
Step 7 is misleading, sorry. It should read:

When I click the red "Clear Local Storage" button, the button itself responds to show that I've clicked on it, with that little kind of jiggle it does, but nothing else happens. No other messages appear in the console.

I'm about to edit the original post.

**Comment by Alys** [comment]
There's several reports in the Tavern/Newbies guild/Bug guild today of similar problems and at least one a day or two ago that was probably the same thing. A couple of people have reported that reloading the site or opening it in a new tab will fix the problem.

**Comment by Alys** [comment]
For the record, a few hours ago, @crookedneighbor redeployed the production site because paglias found that the AWS servers had different js files.

Now, when I repeat the steps above, steps 1 to 5 are the same. When I go to the clear-browser-data page, I do not see the `GET` error in the Console (no errors appear at all), the button on that page does work, and I'm then able to log in.

If I manually delete local storage and also delete cookies at the same time, this bug doesn't happen - I can reload the site and log straight in.

This bug happened for me because I manually deleted local storage, which most users won't do, but from the reports in the Tavern earlier today, it seems that this can happen without being caused by any user action.

Is it possible to detect if the loading page has been loading for longer than we think appropriate and then either tell the user how to clear local storage and cookies, or (better) clear them automatically and reload the page?

Related issue: https://github.com/HabitRPG/habitrpg/issues/6490 "Clear cookies in Clear Browser Data page"

**Comment by crookedneighbor** [comment]
Yep. Can definitely do that.

**Comment by paglias** [comment]
I had opened an issue about the same thing yesterday https://github.com/HabitRPG/habitrpg/issues/7648

**Comment by Alys** [comment]
Ah, I think that's where I got the idea. :)  It would be nice if the clearing could be done automatically though. It would then look like the site was just slow rather than seeming buggy.

**Comment by paglias** [comment]
@Alys consider that with local storage being removed this bug should not happen anymore. What happened a few days ago was that the server had two different JS files with different names. I think a link to the login page after X seconds should be enough

**Comment by Alys** [comment]
I'm pretty sure this is still happening for people. For example, from the Report a Bug guild three hours ago: 

Indiana Kleks (dc37f933-94fe-438c-bcaa-277e6ac577f2):
Hi. Can't log on to Habitica. I use FB login and:
on Safari I keep seeing Habitica logo and tips and it does not move beyond that
I managed to log on on Chrome, but for the past 2 days even on that browser I was getting the same effect as described above on Safari.

cTheDragons:
Hi @Indiana Kleks ! Yes a few ppl have been attacked by that bug. Could you try the Reload the page a couple of times. If that doesn't help, go to https://habitica.com/static/contact and click the blue "play" button in the header. That should give you a login form. Tell us if it doesn't. (Ignore the contact details on that page - if the play button doesn't work, can you post here if it doesn't work.)

Indiana Kleks (dc37f933-94fe-438c-bcaa-277e6ac577f2):
@cTheDragons - did as advised. Problem #solved. Thank you!

**Comment by paglias** [comment]
What I'm saying is that going to the front page and logging back in seems
enough to fix it as described in that bug report. So adding a link to the
front page that says "try to log in again" should be enough

2016-06-13 14:34 GMT+02:00 Alys notifications@github.com:

> I'm pretty sure this is still happening for people. For example, from the
> Report a Bug guild three hours ago:
> 
> Indiana Kleks (dc37f933-94fe-438c-bcaa-277e6ac577f2):
> Hi. Can't log on to Habitica. I use FB login and:
> on Safari I keep seeing Habitica logo and tips and it does not move beyond
> that
> I managed to log on on Chrome, but for the past 2 days even on that
> browser I was getting the same effect as described above on Safari.
> 
> cTheDragons:
> Hi @Indiana https://github.com/Indiana Kleks ! Yes a few ppl have been
> attacked by that bug. Could you try the Reload the page a couple of times.
> If that doesn't help, go to https://habitica.com/static/contact and click
> the blue "play" button in the header. That should give you a login form.
> Tell us if it doesn't. (Ignore the contact details on that page - if the
> play button doesn't work, can you post here if it doesn't work.)
> 
> Indiana Kleks (dc37f933-94fe-438c-bcaa-277e6ac577f2):
> @cTheDragons https://github.com/cTheDragons - did as advised. Problem
> #solved. Thank you!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/7652#issuecomment-225568220,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAkAV73DaqwMw6eqI4SIoOt0chmF4Vbxks5qLU5mgaJpZM4Izp8a
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by lemoness** [comment]
Getting a bunch of complaints about this on social media, so adding the extra message asking them to try logging in again is definitely high priority.

**Comment by SabreCat** [comment]
We've found what's causing this and are updating our deploy process to prevent it from happening!

**Comment by khipkin** [comment]
@SabreCat what was the problem??

**Comment by SabreCat** [comment]
@khipkin: It's caused by the interaction of our Web architecture and the Node dependency installation process. We run between 5 and 7 Web servers that automatically scale up and down to keep site latency at acceptable levels. When a new server is added as part of that auto-scaling, it installs the application and all its dependencies. If dependencies have new versions between the time of the last overall deploy and when the new instances come up, the new instances have different code than the older ones. It thus becomes a roll of the dice whether you get one or the other `app.js` when connecting to the site, which gets the browser... confused.

The solution is to use [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) to ensure that we always use the same set of dependency versions when installing a given Habitica commit.

**Comment by Alys** [comment]
The app.js filenames being different seems to cause only some of these problems.

There's a related issue at https://github.com/HabitRPG/habitrpg/issues/7669#issuecomment-226383893 which was fixed by using the clear-browser-data page and then deleting cookies before logging in (clear-browser-data alone didn't seem to be enough). Adding cookie clearing to the clear-browser-data page would make this issue easier to recover from (https://github.com/HabitRPG/habitrpg/issues/6490 is the issue for that).
