### ISSUE TITLE
empty parties exist in database

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7654]
The database's `groups` collection contains at least one party with no members, possibly as a side effect of https://github.com/HabitRPG/habitrpg/issues/7653 ("a player can be in two quests at once, even though in only one party") or possibly left over from glitches with the APIv3 migration. We should go through the database and purge empty parties and private guilds. Not urgent.

For example, I can't find any members currently in this party, and the person in the quest is a member of a different party now:

```
{
    "_id": "0109db56-cb8a-480d-ac43-8e3615397b64",
    "__v": 8,
    "description": "[redacted]",
    "leader": "af38d52e-7777-4762-8242-06b8c24c8c47",
    "name": "[redacted]",
    "type": "party",
    "quest": {
        "leader": "af38d52e-7777-4762-8242-06b8c24c8c47",
        "key": "vice1",
        "extra": {},
        "members": {
            "af38d52e-7777-4762-8242-06b8c24c8c47": true
        },
        "progress": {
            "hp": 572.6983181975496,
            "collect": {}
        },
        "active": true
    },
    "balance": 0,
    "challengeCount": 0,
    "memberCount": 1,
    "leaderOnly": {
        "challenges": false
    },
    "privacy": "private",
    "chat": [ redacted ]
}
```

**Comment by Alys** [comment]
I've deleted 14 parties that had no members, including the one listed above, as part of the fixes for https://github.com/HabitRPG/habitrpg/issues/7653

I'll do a search for other empty parties and private guilds some other time.

**Comment by cmajames** [comment]
@Alys Can this bug be closed or were you planning on doing another purge?

**Comment by Alys** [comment]
I still need to search again. Thanks for the reminder!

**Comment by khipkin** [comment]
@Alys Now that #7653 is closed, this looks like it's ready for ya!

**Comment by Alys** [comment]
True. :) Thanks!
