### ISSUE TITLE
Item/gold bug Chrome mobile

### ISSUE THREAD

**Issue by DesignLemming** [HabitRPG/habitica#766]
Tried to purchase gold armor on Chrome mobile, site/server froze and on refresh gold was gone but the item was not added.

**Comment by wc8** [comment]
Seems related to #754, see the restore instructions there.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
