### ISSUE TITLE
Dockerfile npm 3 install issue

### ISSUE THREAD

**Issue by Inouju** [HabitRPG/habitica#7661]
### Description

Docker has trouble creating a new image at 
`RUN npm install -g gulp grunt-cli bower npm@3`
giving
`code MODULE_NOT_FOUND`
#### Console Errors

[Gist of `docker-compose up -d` output](https://gist.github.com/Inouju/ffdc5abe2e948dc787ec9e7ff5f3d5ac)
#### Possible fix

Install npm@3 first, then other dependencies.

_Dockerfile:_
# Install global packages
RUN npm install -g npm@3
RUN npm install -g gulp grunt-cli bower

**Comment by thompsnm** [comment]
I believe the suggested fix was put in place in #7681 to fix a duplicate bug I had opened (sorry about that!), so this issue can be closed.

**Comment by Alys** [comment]
Thanks!
