### ISSUE TITLE
Update bower dependencies

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7667]
### Description

Many of our Bower dependencies are pinned to very old versions. Version pinning is good for keeping our production instances consistent, but it does mean we ought to review every so often to update them manually. We haven't done that in a while! We should try to get packages updated where they don't specifically depend on an old version.

**Comment by paglias** [comment]
Going to do this with the redesign, we'll also stop using Bower in favor of NPM

**Comment by librarianmage** [comment]
What is the status on this?

**Comment by paglias** [comment]
@MathWhiz the new client is using updated deps with NPM

**Comment by librarianmage** [comment]
Is this still an issue?
