### ISSUE TITLE
Opening page redirects back to opening page after login

### ISSUE THREAD

**Issue by IstraLouise** [HabitRPG/habitica#7669]
General Info
- UUID: I don't have my user ID because I can't properly log in from the main page through the computer
- Browser: Firefox 47.0
- OS: Windows 8.1

Description
  The first time ONLY that I click on one of the two buttons on the main page, I get a login window.  When I try to login, it starts to redirect, but redirects in such a way that I end up still on the main page that explains what Habitica is to new people and invites them to play and set up an account.  Subsequent attempts just redirect the page back to itself and there is no login unless I go to the clear cache button that Alys sent me the address for.  I haven't found another GIThub issue with this as the problem, but on the Facebook page there is a comment with at least 3 other people having the same issue with the main page. One of them saying that its been occurring for at least 24 hours before.

Console Errors
  There are no error messages, just the page going through things like Google analytics etc and then ending up in the same place, not actually having gone anywhere.

**Comment by Alys** [comment]
This is probably related to https://github.com/HabitRPG/habitrpg/issues/7652 but the repeated redirections seem different.

@IstraLouise Can you please go back to https://github.com/HabitRPG/habitrpg/issues/7652 and click the red button again, and then BEFORE trying to log in, clear your browser's cookies for habitica.com. Are you able to log in after doing that?

**Comment by IstraLouise** [comment]
That worked!  Thank you!

**Comment by paglias** [comment]
This should be fixed now
