### ISSUE TITLE
Protocol for testing

### ISSUE THREAD

**Issue by switz** [HabitRPG/habitica#767]
@lefnire @yangit I see more tests being added. Moving forward, what's the protocol I should be following for ensuring the build passes before I send out a pull request. Also, any ideas on adding tests? It seems about time we should start doing that with new features.

**Comment by yangit** [comment]
Switz,
I'm working on it. So far there is no protocol as we are having troubles with tests consistency (i.e. they pass and fail randomly :) ).
Once it is figured out we will update you.
