### ISSUE TITLE
Undefined signing in facebook in Chrome/FF

### ISSUE THREAD

**Issue by maxygo** [HabitRPG/habitica#7670]
Steps to reproduce:
1. Click  login / register via facebook
2. just close opened modal window
3. get an undefined error alert

screen - https://img.in6k.com/screens/Habitica__Your_Life_the_Role_Playing_Game_2016-06-15_23-48-47.png

**Comment by Alys** [comment]
Was the window you closed the one that asks you to log in to Facebook? I.e., the one that says "Log in to use your Facebook account with HabitRPG"?  If so, I can confirm that the bug is reproducable when I do that.

Or was it a different modal window?

We should change HabitRPG to Habitica, BTW.

**Comment by maxygo** [comment]
Yes, exactly this window.

**Comment by aManNamedTed** [comment]
Maybe there's a variable that's setting that pop-up response to undefined regardless if there's an interaction in the window?

**Comment by OnyxWings** [comment]
I tried it in Chrome and it worked fine, but the undefined error still shows up in Firefox.

**Comment by OnyxWings** [comment]
I did find something after clicking the Facebook login button, receiving the message box, and looking in Firefox's debugger:

`LoggedIntoFacebook:undefined,LoginStatus:undefined`

Is there an "if" option for closing the Facebook login pop-up?

**Comment by OnyxWings** [comment]
The debugger also had 

`LoggedIntoFacebook:undefined,LoginStatus:undefined`

**Comment by SabreCat** [comment]
Client side quirk. Placing on hold for frontend redesign.

**Comment by Alys** [comment]
I haven't seen this reported for a long time. Closing.
