### ISSUE TITLE
Link to join party is no good

### ISSUE THREAD

**Issue by evelynwightman** [HabitRPG/habitica#7677]
Received an emailed invitation to join a party, but the links redirect to the home page regardless of browser, mobile or computer. Link is: 
https://habitica.com/static/front?groupInvite=a7126ac805642f066c0d1a3b5cdbf027b45efa7641553dfbb87fcad34f311878f47c0b75dfead1067bc72d471f625a3d158f47b6b722ea7533f0d8732463fcc04a11462aa129968cbc6f3af911fd0707477061177b77686e8a68ee29f6bab79b98eab163a3b86688a8f219a4dfcad588359764cdc2

**Comment by khipkin** [comment]
Maybe the invite was canceled?

**Comment by Alys** [comment]
@evelynwightman When you log in on the home page (the blue "play" button), where does it direct you to after that?

If you don't see the invitation after logging in, what happens if you stay logged in and go back to your email and click the link again?

**Comment by paglias** [comment]
That link should only be sent to email addresses that are not registered to Habitica. Are you sure you received the invite at the email address used for your account?

**Comment by evelynwightman** [comment]
The invite was fresh. I was signed in on the same browser using the same email address the invite came to.

**Comment by paglias** [comment]
@evelynwightman can you tell us your UUID (Settings -> API)? Also can you send me in a private message on Habitica (my username is `paglias`) the email at which the invite was sent? Thanks

**Comment by evelynwightman** [comment]
User ID: b9c8f0be-2658-466d-ba94-9e680ae672b7

**Comment by paglias** [comment]
I've not been able to reproduce this, I got the correct email invitation. @evelynwightman I'll try to invite you

**Comment by evelynwightman** [comment]
Huh. I received an email invite like last time, but on this one the link worked. Took me to my main page with a huge invite on it. The original invite still doesn't work.

**Comment by paglias** [comment]
I've checked the code but was unable to reproduce / find any bug. If it happens again we'll reopen
