### ISSUE TITLE
New To-Dos being moved to the bottom of the list on refresh

### ISSUE THREAD

**Issue by kriscrat** [HabitRPG/habitica#768]
New To-Dos are moving to the bottom of the list after I reload the page.

**Comment by rixx** [comment]
Can't confirm - I think it would help if you could specify what OS and browser you are using.

**Comment by kriscrat** [comment]
The issue has stopped now.  I don't remember if I was using Chrome or
Firefox.  Windows 7 home premium.

**Comment by rixx** [comment]
Why not close the issue then? :)

(Just so poor lefnire has one ticket less on his list.)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
