### ISSUE TITLE
My mount vanished...

### ISSUE THREAD

**Issue by jmoraispk** [HabitRPG/habitica#7680]
Hey. I noticed and know a very specific bug and I think it is quite easy to understand it and resolve shouldn't be hard... 
THE BUG IS:
When I equiped a animal to mount, it desapeared and a warning showed up saying something like: " 'notMount' missing. I am pretty sure it has to do with that 'do not display mount' on the equipment tab.

My mount was deleted...

**Comment by crookedneighbor** [comment]
@soqueroprogramar I can't reproduce this.

What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by jmoraispk** [comment]
@crookedneighbor My ID is fd7e9510-09cc-4bcd-ab66-11159cfde467

After a while I noticed my bear didn't vanished however it is like 2 peaces of meat were taken out of his mouth and it became small again and I got my 2 meats back...  I still think it is a bug and not an internet glich because the bear I was growing wasn't even the last animal that I fed before mounting it... additionally, it passed quite a while before mounting it because I was feeding other pets. If I had fed him and then mounted him really quick maybe that option was a possiblity, but it wasn't the case.

**Comment by paglias** [comment]
Please reopen if it happens again
