### ISSUE TITLE
String 'headAccessoryCapitalized' not found

### ISSUE THREAD

**Issue by Gumnos** [HabitRPG/habitica#7683]
General Info
- UUID: 
- Browser: Chromium
- OS: Linux (Debian Stable)
### Description

Trying the new "Group by type" option for equipment, I get a section with the error

> String 'headAccessoryCapitalized' not found

![habitica_head](https://cloud.githubusercontent.com/assets/1056674/16168767/32f4ae1a-34da-11e6-9fae-f5f8b95a78ff.jpg)

**Comment by joedragons** [comment]
Not surprisingly also affects Firefox browser in Windows7.  Thanks for reporting!

**Comment by Gumnos** [comment]
heh, the template had spaces requesting my browser+OS so I filled them in, but you're right, I suspect browser doesn't matter.

As a side-note, it was annoying that I had to hand-transcribe that since the header/message was unselectable for copy/paste purposes and even my browser Find functionality couldn't target it to try Cursor mode (toggled with `F7` in FireFox)

**Comment by crookedneighbor** [comment]
Thanks for reporting this. There was just a typo. I've fixed it and will deploy soon.
