### ISSUE TITLE
Missing pieces in "static" url members / users profile

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7687]
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Firefox 47
- OS: Windows 7
### Description

Pieces of the profile produced by a "static" url (i.e. https://habitica.com/static/front/#?memberId=2d6ef231-50b4-4a22-90e7-45eb97147a2c ) are missing. The parts I count:
- Max mana (but not the current amount out of that mana; it displays as "null", i.e. 56/null)
- Totals for stats (but not the breakdown of the total)
- Pets and mounts displays of any kind (it's as if you haven't collected any pets)
- Won challenges (but not its header/table)
- The contributor tier/type (mine is Elite Socialite (bright red), and it's not appearing in either the header by my name or at the top of the "Has contributed to Habitica (code, design, pixel art, legal advice, docs, etc). Want this badge?" area)

None of these problems occur on the on-site profiles.
#### Console Errors

None.

**Comment by habitrpguser** [comment]
The profile blurb is missing, too. Is this intentional? I think it's a pity!
(The profile photo is displayed properly though.)

**Comment by khipkin** [comment]
Woah I didn't even know that page existed!

**Comment by citrusella** [comment]
> The profile blurb is missing, too. Is this intentional? I think it's a pity!
> (The profile photo is displayed properly though.)

Huh, I hadn't even noticed that (probably because my profile blurb is kind of old and useless, so I'd forgotten I had one XD).

EDIT: Reading around, it might be intentional (the pet/mounts might also be intentionally missing as well?).

**Comment by librarianmage** [comment]
Are there things that can't be accessed through the front page?

**Comment by paglias** [comment]
@MathWhiz the list of public fields is here https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/user/index.js#L9

**Comment by librarianmage** [comment]
Unless this should wait, I can work on this!

**Comment by Alys** [comment]
@MathWhiz My personal feeling is that this should probably wait, since the code for it would have to be redone during the site design, so I'm changing this to on hold, but if any other admins disagree, listen to them not me! :)

**Comment by mandyzhou** [comment]
I know this is on hold, but I just wanted to note that most of the achievements (i.e., everything except quests and the challenges heading/table) are missing as well. Battle gear is also missing, although that might be intentional.

**Comment by citrusella** [comment]
I wonder if that's a side effect of their being removed/added? (For the new achievements, anyway, since the ones that are big now are the only ones that have become missing since this started.)

**Comment by Alys** [comment]
It's sounding like it's buggy enough to be worth working on now, even though it might have to be redone during the website improvement project. If no other admins say otherwise in the next couple of days, I'll take this off hold.

**Comment by librarianmage** [comment]
I can do this!

**Comment by Alys** [comment]
@MathWhiz  Great!

**Comment by librarianmage** [comment]
To be clear, the parts I should add are:

* Max Mana
* Challenges Won
* Totals for stats
* Pets/Mounts
* Contributor status
* Achievements
* Profile Blurb

**Comment by Alys** [comment]
@MathWhiz Yes, all of those, and also the user's Battle Gear and class.

**Comment by librarianmage** [comment]
I am not sure where the code is that opens the modal with the user's information.

**Comment by librarianmage** [comment]
@paglias How does this even work? I am unable to find the code that pulls up the modal.

**Comment by paglias** [comment]
@MathWhiz I'm not 100% sure but I think the code is here https://github.com/HabitRPG/habitica/blob/develop/website/client-old/js/static.js#L13

**Comment by Alys** [comment]
@MathWhiz  I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this issue might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it. We'll assess it after the new website code is live and then if it's still needed, you'd be welcome to keep working on it if you wish.

**Comment by librarianmage** [comment]
Should this be closed, as it hasn't been reimplemented yet?

**Comment by paglias** [comment]
Yes, let's close this one
