### ISSUE TITLE
Item found in task duplication

### ISSUE THREAD

**Issue by patrick96** [HabitRPG/habitica#7690]
General Info
- UUID: 0be969bd-d1c0-4009-bedd-703990e983a9
- Browser: Firefox 46.0
- OS: Arch Linux
### Description

When I complete a daily task and find an item, I can un and recheck the task again to receive the item over and over again without it being removed when unchecking the checkbox (the Gold and Silver was removed properly).
This happened to me with a daily task that repeats every 7 days and I got Chocolate. But I assume this is going to happen with any item and any type of task and it's probably because when unchecking a task, the items found during that task are not removed.

**Comment by Alys** [comment]
Please see the first comment on this issue: https://github.com/HabitRPG/habitrpg/issues/4626
for an explanation of why that is the correct behaviour. If you'd like to comment on it, please comment on that issue rather than this one to keep the conversation in one place.
