### ISSUE TITLE
party invitation cannot be declined/rejected if you are already in a party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7691]
If you are in a party with only yourself, it's possible for other players to send you invitations to their party (this is correct behaviour).

However it's not possible for you to reject those invitations - the decline button doesn't work.

I'm marking this as high priority, because it prevents you from receiving invitations to other parties. Also it's probably affecting a fair proportion of new players, since it's easy for a new player to create their own party, sometimes without realising they've done so if they don't read the button descriptions carefully, and this bug will be giving them a negative impression of the party system.

**Comment by crookedneighbor** [comment]
Looking at this.
