### ISSUE TITLE
Minor translations issues repository

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7695]
The issue is created to have reports about minor issues with translations which: are easy to fix, require changes to the code, don't require taking decisions on the look&feel of the site or the way to handle the situation.

New issues will be added as comments, the ticket may be closed and reopened whenever there's the need for it.
- [x] The header has "Mana" untranslatable. 
  Found by **Racobot** on Transifex. **_Fixme**_: The line https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/header.jade#L25 should be altered to replace `Mana` with `env.t('mana')`

**Comment by GitHubSphinx** [comment]
- [ ] The header has "Mana" untranslatable. 
Found by **Racobot** on Transifex. ***Fixme***: The line https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/header/header.jade#L25 should be altered to replace `Mana` with `env.t('mana')`

**Comment by crookedneighbor** [comment]
@GitHubSphinx I've added the labels and moved the mana untranslatable to the top area. Thanks for opening this!
