### ISSUE TITLE
Customize the avatar

### ISSUE THREAD

**Issue by silverymoon** [HabitRPG/habitica#77]
I'd love to be able to change the avatar (most pressing would be having a female avatar, but hair color etc. might be nice as well). Or maybe purchase that as flair?

**Comment by lefnire** [comment]
Female avatar in the works, other customizations will be purchaseable flare.

**Comment by silverymoon** [comment]
Awesome!

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
See also request for [Custom Profile Picture](https://trello.com/c/lrIqemFX) and [this comment](https://github.com/lefnire/habitrpg/issues/181#issuecomment-12743635) and the reply following.
