### ISSUE TITLE
:food not found in user.items.food

### ISSUE THREAD

**Issue by amandaleee** [HabitRPG/habitica#7702]
General Info
- UUID: 46879cf2-9a78-4450-b420-8f97841db0c7
- Browser: Chrome Version 51.0.2704.84 (64-bit)
- OS: Mac OS 10.10.1
### Description

A couple of times over the last few days, I've gotten the same drop twice in a row when clicking on a habit twice in a row [because I completed it twice that day]. After this happens, I can see I have two of a kind of the particular drop I got in my inventory. However, when I go to my stable to feed the two items to my pets, I'm only able to feed them on of the two. On the second, I get the following error in a flash message: 

:food not found in user.items.food

Here's a screencap: 
<img width="275" alt="screen shot 2016-06-20 at 7 25 18 pm" src="https://cloud.githubusercontent.com/assets/2200300/16214391/665af620-371d-11e6-8118-67e4586a68c1.png">

EDITED TO ADD: I was just able to replicate this and when I fed the second food to the pet, I lost the HP and MP that I'd received when I received the drop. 
#### Console Errors

Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-f461e428.js:40:27860)
    at Object.authenticate (https://habitica.com/app-f461e428.js:44:10815)
    at Object.<anonymous> (https://habitica.com/app-f461e428.js:44:12036)
    at Object.i [as invoke](https://habitica.com/app-f461e428.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-f461e428.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-f461e428.js:5:16822)
    at https://habitica.com/app-f461e428.js:5:14868
    at g (https://habitica.com/app-f461e428.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-f461e428.js:5:16789)
    at D.instance (https://habitica.com/app-f461e428.js:6:8436)

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitica.com" from accessing a frame with origin "https://staticxx.facebook.com". Protocols, domains, and ports must match.

https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=947894166.1463280156&jid=760559466&_v=j44&z=1741007695 
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

Failed to load resource: the server responded with a status of 404 (Not Found)
https://habitica.com/api/v3/user/feed/Deer-Base/Meat?userV=2688

And here's a screencap of the console errors: 
<img width="976" alt="screen shot 2016-06-20 at 7 30 41 pm" src="https://cloud.githubusercontent.com/assets/2200300/16214406/8558856a-371d-11e6-8463-42346e77f63b.png">

Please let me know if you need more details - I can try to replicate this and do more testing if you'd like.

**Comment by khipkin** [comment]
Here's the implementation of the API method: https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/user.js#L740

Semi-related, but there's a copypasta mistake in the URL in the documentation.  It says `/api/v3/user/equip/:pet/:food` but it should say `/api/v3/user/feed/:pet/:food`.

**Comment by crookedneighbor** [comment]
Please submit a pr to fix it.

**Comment by amandaleee** [comment]
Going to close this since @khipkin fixed in a PR. Thanks everyone! <3 <3

**Comment by Alys** [comment]
@amandaleee We actually need to keep this open because the PR was just for a related documentation error, not a fix for the bug. But thank you for wanting to keep the issue queue neat!

**Comment by amandaleee** [comment]
Oh, got it! Thanks, sorry, I hadn't seen it in awhile so I thought it had been fully fixed and deployed. :D

**Comment by paglias** [comment]
I'll close this, please comment if it happens again
