### ISSUE TITLE
app.reset() in production branch removes everything even preset Rewards

### ISSUE THREAD

**Issue by yangit** [HabitRPG/habitica#771]
app.reset() in production branch removes everything even preset Rewards.
Probably should reset to the original new user state with some Tasks and Rewards in place

**Comment by wc8** [comment]
Previously requested, #139

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
