### ISSUE TITLE
Unclaimed Mystery Items are purchasable with hourglasses

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7712]
If a subscriber leaves the gift in the mystery box, there is nothing preventing them from purchasing the item in the time traveler shop.

**Comment by Hus274** [comment]
Is there a way to get a mystery item in the test environment?

**Comment by Alys** [comment]
This will give you the latest set:

  'purchased.plan.mysteryItems': ['head_mystery_201606','armor_mystery_201606']

**Comment by Hus274** [comment]
Perfect, thanks Alys!

**Comment by crookedneighbor** [comment]
The API just needs an extra check to see if the item in question is in the mystery box array and error if it is. Should be straightforward.

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]
