### ISSUE TITLE
eyeglasses (eyewear_special_*TopFrame) can be lost and then can't be re-purchased

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7714]
It's possible for the eyeglasses to have false values in a user's account, and when that happens, the user cannot get them back. They do not appear in the Rewards column for purchase (not even for zero gold), and when you click on them in the User > Customise Avatar screen, you get the `gearNotOwned` error.

I don't know how they can be given false values. I've tested death, rebirth, and reset and none of them set the eyeglasses to false in my test account. However one user reported this (9db797f4-ef95-443f-9635-e74973294f08, their data is below, although it's now been fixed) and I found another 241 users in the database who had at least one eyeglass with a false value.

```
            "items.gear.owned": {
                "weapon_warrior_0": true,
                "eyewear_special_yellowTopFrame": false,
                "eyewear_special_whiteTopFrame": false,
                "eyewear_special_redTopFrame": false,
                "eyewear_special_pinkTopFrame": false,
                "eyewear_special_greenTopFrame": false,
                "eyewear_special_blueTopFrame": false,
                "eyewear_special_blackTopFrame": false,
                "weapon_warrior_1": true,
                "weapon_warrior_2": true
            }
```

I'm going to adjust those 241 accounts to give them true values for all eyeglasses. Before I do that, does anyone want to do any investigation? @crookedneighbor ? @paglias ? @viirus is there anything in the apps that could cause this? I'm not going to bother looking through the accounts to see if I can find anything that correlates, but I will save the UUIDs. If I don't hear otherwise, I'll fix all of those accounts in a bit over 24 hours from now. I'll then periodically look for more accounts with the same problem to see if it was a once-off glitch or an ongoing bug.

If we can't find the cause soon and if we think it might reoccur, it might be worth removing whatever restriction prevents the eyeglasses from appearing in the Rewards column. If the user can buy them back for zero gold, this becomes just a minor annoyance.

**Comment by Alys** [comment]
The person who reported this (9db797f4-ef95-443f-9635-e74973294f08) says "I did do a reset when I first started using Habitica, because the tutorial and my experimentation left me with a ton a unearned gold and XP. That probably did it. I just never noticed it earlier. Very odd." Their start date is 2016-05-12T21:05:47.994Z so the reset would probably have been soon after that. However it's not confirmed that the reset caused this (not reproducible in the one test I did).

**Comment by Alys** [comment]
I've fixed the glasses for the 241 users who had false values. I'll check for more periodically.

I'm leaving this open until we either know and fixed what caused it, or have adjusted the code so that lost eyeglasses can be bought back for zero gold just like other equipment (my favourite solution because it will be a good workaround for any future bug that might cause this to happen again, even if we have fixed whatever the current bug is).

**Comment by SabreCat** [comment]
I think all that's needed here is to add a `canOwn` property using the `ownsItem` function to the glasses in https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content/gear/sets/special/index.js.

**Comment by Ozzystrasza** [comment]
I will try this.

**Comment by khipkin** [comment]
[help welcome now] --> [in progress]
