### ISSUE TITLE
Start Date can be set to null / empty string on a Daily

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7715]
When editing a Daily on the website, you can delete the Start Date. After saving, the task has a Start Date of `null`.

This is confusing because it's not obvious to the player how cron will treat it (immediately due versus never due) and because the official and unofficial site/apps/tools will display the due-ness of the Daily in different ways (e.g., website says not due, Android app says due).

I believe the API should prohibit a non-existent or nonsensical Start Date. It should always be a valid date, and if a valid date isn't supplied, then default to the current date, which is what cron does anyway:
common/script/cron.js:  `let taskStartDate = moment(dailyTask.startDate).zone(o.timezoneOffset);`

The website should also handle deletion of the Start Date in a more informative way. For example, if there's no Start Date then don't let the Daily be saved, or save it but set the Start Date to today so that you see the date if you edit the task again, or set the Start Date to today as soon as you move focus out of the Start Date field. I think the latter is my favourite option at the moment.

**Comment by Alys** [comment]
oops, saved prematurely. I've changed the final paragraph to this:


The website should also handle deletion of the Start Date in a more informative way. For example, if there's no Start Date then don't let the Daily be saved, or save it but set the Start Date to today so that you see the date if you edit the task again, or set the Start Date to today as soon as you move focus out of the Start Date field. I think the latter is my favourite option at the moment.

**Comment by Alys** [comment]
Ha, I'm an idiot. Cron treats Dalies with no Start Date as starting on the day that cron runs (`moment()`), which means they were NOT due on  the previous day.

So I guess if there's no Start Date supplied, the default could be `tomorrow`, although I still sort of like the idea of setting it to today, for consistency with new Dailies. I don't have a strong preference though.

**Comment by ghost** [comment]
So in other words, if no start date is set, it'll always be tomorrow i.e. never, won't it?

**Comment by Alys** [comment]
@GitHubSphinx That's correct, with the current implementation. I'd encourage anyone reading this to not rely on that always being the case.

I can see that that could be considered a useful feature (an easy way to make a Daily permanently not due) but I don't think it's intuitive, and it relies upon all possible clients (official and unofficial; current and future) handling a missing Start Date in the same manner (that won't make any difference to cron but it will affect how the user perceives which Dailies are due).

**Comment by paglias** [comment]
Can be fixed by setting `required: true`, making sure it's a default value and running a migration to set the missing dates to today (?)

**Comment by Alys** [comment]
Sounds good, although we should probably make the migration set the date as a day or two in the future.

**Comment by librarianmage** [comment]
I can look into this!

**Comment by Alys** [comment]
Thanks @MathWhiz! When the fix is ready to be merged, I'd appreciate it if you could remind us that a migration is needed to fix all Dailies that don't have a start date (being especially cautious about challenge Dailies, if any of them need fixing). An admin will write the migration script.

**Comment by librarianmage** [comment]
Should I wait to work on this until #8414 is merged?

**Comment by Alys** [comment]
@MathWhiz I think it should be fine to work on this now. It's for Dailies and #8414 is for To-Dos so there should be no conflicting overlap. However the method used to fix that other issue might be suitable for this one too and we'll probably steal and adjust the migration script from 8414. :)

**Comment by librarianmage** [comment]
In [/website/server/models/task.js](https://github.com/HabitRPG/habitica/blob/develop/website/server/models/task.js#L223), there is this code:

```javascript
export let DailySchema = new Schema(_.defaults({
  frequency: {type: String, default: 'weekly', enum: ['daily', 'weekly']},
  everyX: {type: Number, default: 1}, // e.g. once every X weeks
  startDate: {
    type: Date,
    default () {
      return moment().startOf('day').toDate();
    },
  },
  repeat: { // used only for 'weekly' frequency,
    m: {type: Boolean, default: true},
    t: {type: Boolean, default: true},
    w: {type: Boolean, default: true},
    th: {type: Boolean, default: true},
    f: {type: Boolean, default: true},
    s: {type: Boolean, default: true},
    su: {type: Boolean, default: true},
  },
  streak: {type: Number, default: 0},
}, habitDailySchema(), dailyTodoSchema()), subDiscriminatorOptions);
```

What does the `startDate` part of the schema do?

**Comment by TheHollidayInn** [comment]
Start date helps with calculating frequency of the dailies.

**Comment by librarianmage** [comment]
I mean, what does the default bit do?

**Comment by TheHollidayInn** [comment]
It returns a formatted string of today starting at the 0th hour. For example: 2/27/2017 0:00:00 (but probably ISO format or some standard.)

**Comment by librarianmage** [comment]
@TheHollidayInn Doesn't that mean that it is already converted into a date if it is empty? Am I missing something?

**Comment by TheHollidayInn** [comment]
Yea, if the value is empty and you save a document, it will add that value by default. 

http://mongoosejs.com/docs/defaults.html

**Comment by librarianmage** [comment]
Then what needs to be changed? I am not clear on this.

**Comment by librarianmage** [comment]
Hi, I am not sure what needs to be changed.

**Comment by Alys** [comment]
@MathWhiz Probably these things:

- adjust the `startDate` object that you found in https://github.com/HabitRPG/habitica/issues/7715#issuecomment-282597680 so that it has the `required` attribute (https://github.com/HabitRPG/habitica/issues/7715#issuecomment-228525675 )
- adjust the edit modal for Dailies so that it's not possible to save your edits if you have deleted the original start date and not chosen a new start date

Also, if you use the iOS app, test there to see if it's possible to delete the start date when editing a Daily. If it is, we'll probably have to get the iOS app changed to disable deletion before the `required` attribute goes live, otherwise confusing errors might occur.

I've tested on the Android app and I can't delete the start date there.

**Comment by librarianmage** [comment]
I do in fact use the iOS app (which makes sense due to my recent posts in
the Comrades guild), and it is not possible to delete the date there either.

**Comment by paglias** [comment]
The startDate field is now required
