### ISSUE TITLE
new Mystery Items from gift box require reload before they work correctly

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7717]
We often see questions and bug reports from subscribers who try to get their new Mystery Items but see errors or don't see the items because their browser hasn't loaded the new content yet.

It would be nice if a reload could be forced at some appropriate point, perhaps when they click on the Mystery Box (and only if a reload is actually needed), but other options could be considered too.

**Comment by mcooledge** [comment]
I would be interested in poking at this a bit. Would be learning the stack as I go so it may take a bit of time to figure out - based on currently open issues, this seems like a good place to start.

I can't think of a better way to do it than (check if content needs to be loaded)(force reload if necessary), so I'm willing to keep that open for discussion as well.

**Comment by mcooledge** [comment]
I don't know if I'm actually going to get to this or not, if someone else really wants it they can have it, just comment. Otherwise I'll work on it when I get the chance.

**Comment by librarianmage** [comment]
Has this been fixed with the redesign?

**Comment by lemoness** [comment]
I think it has, but we can reopen this ticket or make a new one if it happens again!
