### ISSUE TITLE
create FAQ answers for Android

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7719]
`common/locales/en/faq.json` needs to be edited to add answers for Android, in the same way that answers for iOS exist. For example, create a new string for `androidFaqAnswer0` just under the `iosFaqAnswer0` string. 

If anyone wants work on this before this issue contains any other advice, then make all the Android answers the same as the iOS answers initially, and make adjustments later based on our feedback.

For `androidFaqAnswer11`, the text is probably better written as something like "You can report a bug, request a feature, or send feedback under About > Report a Bug and About > Send us Feedback! We'll do everything we can to assist you."

**Comment by sougat818** [comment]
Hi @Alys,

I would like to work on this.

**Comment by Alys** [comment]
@sougat818  Thanks, please do!

**Comment by Alys** [comment]
@lemoness and @vIiRuS  We're proposing that the FAQ answers for Android be the same as for iOS, except that the "Report a Bug" answer uses "About" instead of "Menu" as described above. Should there be any other differences?

**Comment by lemoness** [comment]
They should be the same aside from any pathway differences. As I'm an iOS
user, I can't actually check to make sure, but maybe @thehollidayinn can.

**Comment by ghost** [comment]
I would also like to contribute to this if its still needed.

**Comment by Shadow-Byte** [comment]
I just proposed the edit.
