### ISSUE TITLE
Habitica's favicon is hard to see on Windows 10 task bar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7720]
_Reported in the Report a Bug guild:_

"On Windows 10, the task bar is dark so that when you pin Habitica's icon to it, the dark purple doesn't show up."

![http://i.imgur.com/UBjZNFV.png](http://i.imgur.com/UBjZNFV.png)

Possibly we could make a version of the icon with a white background or outline and use an appropriate meta tag to deliver it to only Windows 10 users.

**Comment by PowerlinxJetfire** [comment]
Presumably this was added to the taskbar via Chrome, since that's the only browser in the screenshot, and I can't figure out a way to pin websites there with Edge. Chrome won't follow any Microsoft-specific meta tags, so I don't think there's any way to target Windows specifically.

But, this isn't just a problem on Windows, so that's okay. If a user adds a desktop or homescreen shortcut from any browser on any OS, then the current icon risks blending into the wallpaper. For instance, I just added it to my home screen on Android, which is mostly black, and the icon is even harder to see.

The icon should be changed to have background protection on all platforms.

**Comment by 32gits** [comment]
I could mess around with some alternate favicons.

**Comment by Alys** [comment]
@veeeeeee @lemoness Would you like @32gits to experiment with creating new favicons? If so, are there any guidelines that should be followed?

**Comment by lemoness** [comment]
I think a white background for our current favicon would work well.

**Comment by 32gits** [comment]
Yeah I've already swapped it out on my end and it looks good. I was just waiting to hear back on this.

**Comment by 32gits** [comment]
I don't have Habitica setup on my Windows machine, but here's what the new favicon looks like on a light/dark browser tab.

![habitica-compare](https://cloud.githubusercontent.com/assets/10841727/20857346/373c4984-b8e6-11e6-9db8-1b87a1c6eada.png)

**Comment by Alys** [comment]
@32gits Cool! If you'd like to make a pull request, please do.

I'm not sure if [legal permissions](http://habitica.wikia.com/wiki/Guidance_for_Artisans#Becoming_an_Artisan) are needed for this type of image change - @lemoness ?

**Comment by 32gits** [comment]
I just received confirmation tonight on the permissions I sent for pixel art. Let me know if I need to send anything else. Thanks.

**Comment by Alys** [comment]
@32gits No, that's perfect then. No other permissions would be needed.

**Comment by 32gits** [comment]
Okay cool. What's the best command to get my build up to date before a pull request? I feel like I've seen a few different suggestions depending on where you look.

**Comment by Alys** [comment]
My preference when I haven't yet made a pull request is to do this:

	git fetch upstream
	git checkout [your_branch_name]
	git rebase upstream/develop

**Comment by 32gits** [comment]
Hmm. best course of action here?
```
Development/habitrpg$ git rebase upstream/develop
First, rewinding head to replay your work on top of it...
Applying: no changes
Applying: reverted stuff
Applying: updated package.json and config.json
Using index info to reconstruct a base tree...
M	package.json
Falling back to patching base and 3-way merge...
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
error: Failed to merge in the changes.
Patch failed at 0003 updated package.json and config.json
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by khipkin** [comment]
@32gits You have to open up the file `package.json`, manually resolve the merge conflicts, do `git add package.json` once the conflicts are resolved, then do `git rebase --continue`.

**Comment by 32gits** [comment]
I added package.json but when I `git rebase --continue` I get this:
```
Applying: updated package.json and config.json
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```
my commit "updated package.json and config.json" was just from when I put habitica on my new PC and found some files were out of date so I manually copy/pasted from the repository source code. I'm guessing there was a better way to do that via Git... I'm about ready to delete my branch and re-fork to start fresh. What should I do here? Sorry I'm still kind of a noob when problems arise in Git.

**Comment by khipkin** [comment]
Ahh.  If I were you, I would start fresh and copy over your changes.  There may be a better way, but this way will probably be simpler.
