### ISSUE TITLE
Gem Receiving text is in native language of sender

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7722]
_Admin note: Edits made to bring original ticket up to date with conversation_
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 37.0.2178.43
Windows 8.1 32-bit
## Description
- Text for the receiver of a gem gift appears in the native language of the sender. _(See Example below)_.  **The text for the sender of the gem should be in the native language of the sender and for the receiver the gem receive text would be in the native language of the receiver.**
- ~~The @ symbol is missing in front of the usernames. (This occurs regardless if the sender is sending in a different language.~~

For example a French  User sending to myself, an English speaker, I myself see this:

> `Bonjour cTheDragons, FrenchHabitican vous a envoyé1 gemmes!` Extra user comment here

It should appear as:

> `Hello cTheDragons, FrenchHabitican has sent you 1 gems!`  Extra user comment here

**Comment by habitrpguser** [comment]
Just confirming this (though only by hearsay): Someone mentioned in guild talk on 29 July 2016:

> "@XYZ Spreek je Nederlands? (Your message came up as "XYZ heeft je gezonden 4 edelstenen", which I assume means XYZ has given you 4 gems)"

So I went looking if this is already a known bug - and here it is! :)

**Comment by khipkin** [comment]
Suggestion: add [translations] label.

**Comment by crookedneighbor** [comment]
We've decided that the leading @ should not be added.

**Comment by khipkin** [comment]
Suggestion: update issue title to prevent future wasted effort

**Comment by librarianmage** [comment]
Should this be marked as In Progress?
