### ISSUE TITLE
non-empty private group (guild/party) can be deleted if memberCount is wrong

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7723]
If a private group contains multiple members but the memberCount is 1, then when one player leaves the group, the group will be deleted (i.e., the group is treated as empty).

This situation arose recently when I was manually creating a private guild for a huge party that needed to be split up, and I added all the members to the guild but forgot to set the memberCount to the correct number, so when I left the guild, the guild was deleted. That was clearly my error, but it's  possible for the memberCount to be inaccurate for other reasons. For example, https://github.com/HabitRPG/habitrpg/issues/7454 and also I imagine if a player joins a group and a timeout happens, the memberCount might not be updated -- a two-party group would then have a memberCount of 1.

Since deletion of a group is a drastic action, resulting in lost chats, quest progress, and group description (which might contain important information), and possibly lost access to challenges, I think it's worth checking for this situation before deleting a group with a memberCount of zero. I.e., the code that deletes an "empty" private guild or party should first search for players that still have that group's ID in their accounts. If the code finds any such players, it should update the memberCount and not delete the group.

I'll wait a day or two for feedback, and if there's no objections or better ideas, I'll mark this as help wanted for that suggested fix.

**Comment by sougat818** [comment]
Hey @Alys I would like to work on this.

**Comment by Ozzystrasza** [comment]
@Alys Just to make sure I understand, your suggestion was to search through all users of Habitica and check if they have the gid? If so, do you know if there is already a way to access that info from all users?

**Comment by Alys** [comment]
@Ozzystrasza Searching for all users with a gid is how the membership lists are created for guilds and parties, and it's done when notifications are sent, or quest damage/rewards are applied, so there'll be code for that somewhere. `members` is probably a good keyword to search for. It's possible that looking through the tests might be the fastest way to find relevant code, or to find pointers to relevant code.

@sougat818 Just checking: Is this something you'd still like to work on? If not, that's fine, just let us know so that others can take it up.
