### ISSUE TITLE
cannot leave a party that no longer exists

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7724]
If a player's account contains a `party._id` for a party that no longer exists, they are unable to leave the party, or create a new one, or be invited to a new one. I found a case of this today - confirmed that the `party._id` in their account did  not correspond to any existing group.

I don't know how this situation happened, but I imagine that any action to leave or be removed from a party could time out, resulting in the ID not being deleted. Also it could arise from this bug: https://github.com/HabitRPG/habitrpg/issues/7723

This situation triggers the `groupNotFound` error ("Group not found or you don't have access."). 

I think it would be good if the code that finds that error in this particular situation would delete the party ID from the player's account, ideally without reporting an error to the user. I'm going to wait a day for feedback about this, and if there's no complaints or better ideas, I'll mark it as help welcome for that solution.

**Comment by luanmuniz** [comment]
Investigating i think i found the source:

https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/group.js#L164
This query is returning `null` and than
https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/groups.js#L130
This return the error

Any ideas how should we approach the solution?
When is appropriate to delete the partyId?

**Comment by Alys** [comment]
I think it would be appropriate to delete `party._id` and also any guild ID from the user's `guilds` object at any time that a query for a group with that ID finds no matching group.

The code you've found looks relevant!

**Comment by crookedneighbor** [comment]
So you basically need to add this after the group lookup, right before the group is returned.

``` js
if (!group && isUserParty) {
  delete user.party._id;
  await user.save();
} else if (!group && isUserGuild) {
  removeFromArray(user.guilds, groupId);
  await user.save();
}
```

In my opinion, it should still send back a 404, since that particular request was unsuccessful.

**Comment by paglias** [comment]
I agree that it should return a 404

**Comment by Ozzystrasza** [comment]
Is this how it should look like in [line 158](https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/group.js#L158) and on? Or am I completely wrong?

``` ruby
...
  let mQuery = this.findOne(query);
  if (fields) mQuery.select(fields);
  if (populateLeader === true) mQuery.populate('leader', nameFields);
  let group = await mQuery.exec();

  if (!group && isUserParty) {
  delete user.party._id;
  await user.save();
} else if (!group && isUserGuild) {
  removeFromArray(user.guilds, groupId);
  await user.save();
}
  return group;
...
```
