### ISSUE TITLE
no quest progress made by non-resting quest participants

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7727]
I sometimes see reports of players who are in a quest and who are not resting in the inn going through cron but with no quest progress message appearing in party chat. I'm going to start recording them here so we can track the bug.

ldykstra (b3c228d9-954e-4136-b60e-5ec8a1578864)  -15 hours before now:
"Hello! My party is currently on a quest. When I logged in this morning (through mobile), my completed tasks from yesterday didn't do any damage to the boss we are fighting. There is no 'Ldykstra attacks the Laundromancer for xx damage" in our party's chat. Any way that can be fixed?"

I confirmed that they are in the quest and were not resting in the inn and did not produce a quest progress message. Amplitude's dates for cron are below, and it says resting false for all three:

Jun 26, 2016  4:00:47 am UTC
Jun 25, 2016  1:47:54 pm UTC
Jun 24, 2016 12:01:27 pm UTC

Here are the corresponding quest progress messages - there was none for Jun 25:

```
        {
            "id": "4b0bb2a6-8beb-4f66-ac35-2b40636fb5bf",
            "text": "`ldykstra attacks The Laundromancer for 64.9 damage.` `The Laundromancer attacks party for 0.0 damage.`",
            "timestamp": 1466913647036, //      UTC: 2016-06-26 04:00:47
            "flagCount": 0
        },

        {
            "id": "c722e0d8-355c-49af-b688-289a6ab2742f",
            "text": "`ldykstra attacks The Laundromancer for 25.5 damage.` `The Laundromancer attacks party for 0.0 damage.`",
            "timestamp": 1466769686744, //      UTC: 2016-06-24 12:01:26
            "flagCount": 0
        },
```

----

**UPDATE by Alys 2017-01-14:** 
I've been forgetting to report examples of this bug here, but it's happening often. We see reports in the Report a Bug guild at least once every few days, usually more often. It's not consistent though - one player might have it one day and then not again for some time, so it's likely to be from something like timeouts when updating the party object during cron, rather than a code bug. I'm wondering if it could be worked-around with a change similar to @Hus274's fix for the quest rewards bug: #8251

**Comment by brightbold** [comment]
I think this happened to me this morning. I received an email saying our quest started at 5:30AM EST. I logged in on mobile (iPhone) sometime around 8:00 I think and repeatedly refreshed the party page, first trying to get the active quest to show up (originally it was still showing that only a few members had accepted, but after a refresh or two it showed the quest in progress), and then trying to get my "BrightBold attacks the Indulgence Armadillo" message to appear. It never appeared on mobile but I assumed it was a fluke in the app. But when I checked on my laptop around 8:15, the two spells I cast were registered, but my quest damage was not.

This seems like the bug Alys is reporting above, UNLESS I had left my laptop on overnight with my browser open and cron ran during the night before the quest started. I don't think this happened but I can't remember for sure. My user ID is 6cb6695a-abf5-48bf-bd02-9d2ac12c32ca in case you want to check and see if that's what happened.

**Comment by Alys** [comment]
@brightbold Your cron ran at 2016-08-27 08:30 UTC+0. I'm not sure how that matches up with your quest start time of 05:30 EST. I can look into it tomorrow if it doesn't give you any insights into what happened.

**Comment by brightbold** [comment]
Well it seems as if cron ran an hour before the quest started. I guess I must have left my laptop on after all, since cron triggered while I was sound asleep. So, never mind — this doesn't support your bug report after all. (Although if people started reporting this around the time that you guys made the change so that an open Habit browser page will periodically self-refresh, and their quests started before they first checked Habitica for the day but after their cron might have been triggered unbeknownst to them, then their reports could have the same explanation as mine.)

**Comment by Alys** [comment]
@brightbold Fantastic! Thanks for letting us know! You're right that some reports could be due to that.

There's been two or three reports since I logged this issue that I confirmed were actual failures for the quest progress message to appear. I've been forgetting to record them here though. :(

**Comment by Alys** [comment]
Another confirmed case twice in the past two days for candybubbles🍭 (aa373af3-62b0-477b-a674-664b3da80609):
"I'm currently in a quest and my attacks/damages to the boss aren't showing up along with everyone else's."

---

UPDATES:

Another confirmed case reported at Tue Sep 13 05:08:44 AEST 2016 by Kharon (3807fed9-ada8-41eb-9174-baa26246b57e) :
"My cron ran on schedule 15 minutes ago during a boss quest but an error message displayed. 600+ damage wasn't applied and there doesn't seem to be any notification generated in the party chat. No change yet after clearing the cache and restarting the browser. Can anyone advise please?"

Another confirmed report for jjmcgaffey (8f0f2f48-73b0-4b27-a95a-40603cc919e7) who cronned at Sep 15, 2016 7:16:12 pm UTC:
"Another no-damage-to-boss report; I'm shown as taking part in the quest (which started yesterday), but although I've (obviously) cronned today, there's no message about me dealing damage. Several other participants have. ??"

**Comment by Memry** [comment]
Happened to my mememry account UUID 2dc2722b-fdc1-4a36-894f-c22418b67a30 this morning.  Still shows damage pending.  Just not damage done. I was not in the inn.  No idea why it could have happened.  Kind of bummed because it should have meant we killed the Hedgebeast today and then I would have started another quest.  Oh well, after the weekend, I suppose.

**Comment by Alys** [comment]
Another confirmed report from about Sep 26 03:00 AEST 2016:

dazlious549 (68a39cf7-de3c-4f72-b79d-8d924901d908) 
"Hello! For some reason, yesterday's damage hasn't dealt on my quest. My day started at 2 AM PST, and I've just logged in for the first time today at 9:15, but the damage is still pending. I've got 74.1 I'm supposed to deal. This number was 69.1 ish when I first logged in, but I've checked off a few dailies since then. I've tried: changing my start time, logging out and logging back in, and writing in my party's chat."

UPDATE:

Another confirmed report for a cron that occurred at Oct 14, 2016 12:21:32 pm UTC from Ainy Rainwater ( b10fef38-3623-4478-9196-c53fd413a836 ): "I just logged in (on app) & got NO damage against boss. I don't mean zero damage: I mean there was no system message at all! This is the second time this has happened to somone in my party. (The other person it happened to didn't report it because the quest almost over.) I had a great day yesterday & should've done about 40 pts of damage. Instead, my login wasn't even noted by the system. :("

**Comment by Alys** [comment]
Another confirmed report for a cron that happened at Oct 16, 2016 5:02:48 am UTC for kirylin ( 8bca3269-8db1-4def-9840-a1e3784eecf2 ). This was in the server logs (the final line is the most interesting):

```

i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-2016-10-16T05:02:48.594Z - error: Error
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at model.wrappedPointCut [as save] (/var/app/current/node_modules/mongoose/lib/document.js:1907:27)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at /var/app/current/website/transpiled-babel/middlewares/cron.js:206:65
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Array.forEach (native)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at _callee$ (/var/app/current/website/transpiled-babel/middlewares/cron.js:205:29)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:62:40)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:336:22)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:95:21)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:62:40)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:278:24)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:95:21)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:572:26)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:612:10)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:691:18)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:138:16)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:148:10)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461-    at Immediate.Async.drainQueues [as _onImmediate] (/var/app/current/node_modules/bluebird/js/release/async.js:17:14)
i-0970058819c78df27/var/log/nodejs/rotated/nodejs.log-1476626461:    at processImmediate [as _immediateCallback] (timers.js:383:17) method=PUT,
        originalUrl=/api/v3/tasks/465ac4e4-f602-4bb4-a27c-ddb09f7fd620?userV=9493,
        host=habitica.com,
        x-real-ip=..........., x-forwarded-for=......................
        content-length=1001, accept=application/json, text/plain, */*, accept-encoding=gzip, deflate, sdch, br, accept-language=en-US,en;q=0.8,
        content-type=application/json;charset=UTF-8, dnt=1, origin=https://habitica.com, referer=https://habitica.com/,
        user-agent=...............................,
        x-api-user=8bca3269-8db1-4def-9840-a1e3784eecf2, x-client=habitica-web, x-habitica-lb=Yes,
        x-user-timezoneoffset=...,
        x-forwarded-port=443, x-forwarded-proto=https,
        _id=465ac4e4-f602-4bb4-a27c-ddb09f7fd620,
        text=......
        userId=8bca3269-8db1-4def-9840-a1e3784eecf2, _legacyId=9360eeba-3a30-443f-b5ad-2c4fdc4f8c30, type=daily,
        notes=, value=2.9253562257358428, priority=1.5, attribute=str, createdAt=2016-04-27T02:29:06.854Z, updatedAt=2016-10-15T05:21:17.984Z,
        checklist=[id=1ce9ac8b-9759-4bcc-9714-8641f925a145, text=................., completed=false, id=cf33fe30-a7ca-4a17-97a6-c0a78137ada2, text=.................., completed=false, id=59dc905c-d3f0-49a2-a813-8f96c2a203e5, text=.................., completed=false, id=b96cca0c-fbc1-4c16-91a7-454aeee71409, text=.................., completed=false],
        collapseChecklist=false, completed=false, streak=3, su=true, s=false, f=false, th=false, w=false, t=false, m=false, startDate=2016-04-27T02:29:06.854Z, everyX=1,
        frequency=weekly, id=465ac4e4-f602-4bb4-a27c-ddb09f7fd620,
        httpCode=500, isHandledError=false, message=No matching document found for id "465ac4e4-f602-4bb4-a27c-ddb09f7fd620", name=VersionError
```

It refers to this task:

```
{
    "_id": "465ac4e4-f602-4bb4-a27c-ddb09f7fd620",
    "type": "daily",
    "text": "...................",
    "notes": "",
    "tags": [
        "24a59658-4c7a-4796-b4bc-73592aac7b7d"
    ],
    "value": 3.853133245658556,
    "priority": 1.5,
    "attribute": "str",
    "challenge": {},
    "reminders": [],
    "userId": "8bca3269-8db1-4def-9840-a1e3784eecf2",
    "_legacyId": "9360eeba-3a30-443f-b5ad-2c4fdc4f8c30",
    "createdAt": "2016-04-27T02:29:06.854Z",
    "completed": false,
    "collapseChecklist": true,
    "checklist": [
        {
            "id": "1ce9ac8b-9759-4bcc-9714-8641f925a145",
            "text": "...................",
            "completed": false
        },
        {
            "id": "cf33fe30-a7ca-4a17-97a6-c0a78137ada2",
            "text": "...................",
            "completed": false
        },
        {
            "id": "59dc905c-d3f0-49a2-a813-8f96c2a203e5",
            "text": "...................",
            "completed": false
        },
        {
            "id": "b96cca0c-fbc1-4c16-91a7-454aeee71409",
            "text": "...................",
            "completed": false
        }
    ],
    "history": [
        {
            "date": 1461769888591,
            "value": 0
        },
        {
            "date": 1462079081392,
            "value": 4.53201056602885
        },
        {
            "date": 1464801329163,
            "value": 8.132014427156857
        },
        {
            "date": 1467351203492,
            "value": 11.324041596015766
        },
        {
            "date": 1470029273624,
            "value": 13.411027850369377
        },
        {
            "date": 1471503644116,
            "value": 13.53200648607811
        },
        {
            "date": 1471620659377,
            "value": 13.53200648607811
        },
        {
            "date": 1471709154132,
            "value": 13.53200648607811
        },
        {
            "date": 1471763334509,
            "value": 13.53200648607811
        },
        {
            "date": 1471842432013,
            "value": 14.23897787876845
        },
        {
            "date": 1471968448761,
            "value": 14.23897787876845
        },
        {
            "date": 1472058107371,
            "value": 14.23897787876845
        },
        {
            "date": 1472104363484,
            "value": 14.23897787876845
        },
        {
            "date": 1472188344458,
            "value": 14.23897787876845
        },
        {
            "date": 1472277072198,
            "value": 14.23897787876845
        },
        {
            "date": 1472403081692,
            "value": 14.23897787876845
        },
        {
            "date": 1472448366595,
            "value": 14.933256723256155
        },
        {
            "date": 1472537021292,
            "value": 14.933256723256155
        },
        {
            "date": 1472623464567,
            "value": 14.933256723256155
        },
        {
            "date": 1472706179199,
            "value": 14.933256723256155
        },
        {
            "date": 1472793084332,
            "value": 14.933256723256155
        },
        {
            "date": 1472881377835,
            "value": 14.933256723256155
        },
        {
            "date": 1472968971160,
            "value": 14.933256723256155
        },
        {
            "date": 1473051760757,
            "value": 15.615292692592663
        },
        {
            "date": 1473138118663,
            "value": 15.615292692592663
        },
        {
            "date": 1473226444490,
            "value": 15.615292692592663
        },
        {
            "date": 1473311271497,
            "value": 15.615292692592663
        },
        {
            "date": 1473397577789,
            "value": 15.615292692592663
        },
        {
            "date": 1473484198728,
            "value": 15.615292692592663
        },
        {
            "date": 1473570312617,
            "value": 15.615292692592663
        },
        {
            "date": 1473656437056,
            "value": 16.28551191211884
        },
        {
            "date": 1473742992061,
            "value": 16.28551191211884
        },
        {
            "date": 1473829330130,
            "value": 16.28551191211884
        },
        {
            "date": 1473916285426,
            "value": 16.28551191211884
        },
        {
            "date": 1474005631817,
            "value": 16.28551191211884
        },
        {
            "date": 1474089053226,
            "value": 16.28551191211884
        },
        {
            "date": 1474176460720,
            "value": 16.28551191211884
        },
        {
            "date": 1474261359526,
            "value": 16.94431857878008
        },
        {
            "date": 1474347727052,
            "value": 16.94431857878008
        },
        {
            "date": 1474434626107,
            "value": 16.94431857878008
        },
        {
            "date": 1474527571913,
            "value": 16.94431857878008
        },
        {
            "date": 1474609994805,
            "value": 16.94431857878008
        },
        {
            "date": 1474694050980,
            "value": 16.94431857878008
        },
        {
            "date": 1474781526290,
            "value": 0
        },
        {
            "date": 1474866015837,
            "value": 1
        },
        {
            "date": 1474990865639,
            "value": 1
        },
        {
            "date": 1475039048676,
            "value": 1
        },
        {
            "date": 1475125434226,
            "value": 1
        },
        {
            "date": 1475212168420,
            "value": 1
        },
        {
            "date": 1475298305624,
            "value": 1
        },
        {
            "date": 1475472764448,
            "value": 1.9747
        },
        {
            "date": 1475557377894,
            "value": 1.9747
        },
        {
            "date": 1475646241857,
            "value": 1.9747
        },
        {
            "date": 1475730461510,
            "value": 1.9747
        },
        {
            "date": 1475816549777,
            "value": 1.9747
        },
        {
            "date": 1475904067305,
            "value": 1.9747
        },
        {
            "date": 1475989825640,
            "value": 1.9747
        },
        {
            "date": 1476075626800,
            "value": 2.9253562257358428
        },
        {
            "date": 1476162233737,
            "value": 2.9253562257358428
        },
        {
            "date": 1476254378700,
            "value": 2.9253562257358428
        },
        {
            "date": 1476335216797,
            "value": 2.9253562257358428
        },
        {
            "date": 1476421872901,  //  UTC: 2016-10-14 05:11:12
            "value": 2.9253562257358428
        },
        {
            "date": 1476508877774,  //  UTC: 2016-10-15 05:21:17
            "value": 2.9253562257358428
        },
        {
            "date": 1476680700176,  //  UTC: 2016-10-17 05:05:00
            "value": 3.853133245658556
        }
    ],
    "frequency": "weekly",
    "everyX": 1,
    "startDate": "2016-04-27T02:29:06.854Z",
    "repeat": {
        "su": true,
        "s": false,
        "f": false,
        "th": false,
        "w": false,
        "t": false,
        "m": false
    },
    "streak": 4,
    "updatedAt": "2016-10-17T05:05:00.383Z",
    "__v": 274,
    "group": {
        "assignedUsers": []
    }
}
```

The history array doesn't contain an entry for the cron that happened on 2016-10-16. All the other Dailies do show history entries for that day. Looks like when that Daily was being processed, something stopped cron from finishing processing it, and presumably stopped cron going on to apply the quest progress as well.

**Comment by reneamac** [comment]
This just happened to me. My party started fighting Fire Skull Swarm around 4:30am on Oct. 24, and when my tasks cron at 3:00am (Oct. 25), nothing happened. I had racked up enough damage to defeat the boss, and nothing. It's irritating because the quest should be finished, but instead, I'm still taking hits to my health.

Thanks for working on this!!

User ID: 862f595d-72a7-42fc-a1d0-324bbb139456

**Comment by Alys** [comment]
I've been forgetting to report examples of this bug here, but it's happening often. We see reports in the Report a Bug guild at least once every few days, usually more often. It's not consistent though - one player might have it one day and then not again for some time, so it's likely to be from something like timeouts when updating the party object during cron, rather than a code bug. I'm wondering if it could be worked-around with a change similar to @Hus274's fix for the quest rewards bug: https://github.com/HabitRPG/habitica/pull/8251

I'm copying this comment to the original post and marking this issue as help welcome.


(By the way, there is an unrelated problem where a player's cron fails to finish **every** time it runs, but we've always found that that's due to a problem with unexpected or corrupt data in a specific task, causing cron to halt as soon as the task starts being processed. I've seen enough of the once-off quest progress failures to be sure that it's a different problem.)

**Comment by Alys** [comment]
We've identified that this happens due to problems that cause cron to fail part way through, such as tasks with large history arrays / VersionErrors. @TheHollidayInn is working on concurrency fixes that should help.
