### ISSUE TITLE
UI Problem - elements all appear at once

### ISSUE THREAD

**Issue by applejess** [HabitRPG/habitica#773]
![habitrpg](https://f.cloud.github.com/assets/4059212/339027/0f62cd3c-9d2b-11e2-86a3-5a67baf3167f.jpg)

The page loads this way in both Firefox and IE, on every computer I've access to, and has been doing so for a week or two now. Every notification, every menu, all opens at once and gets stuffed up at the top of the page so I have to scroll all the way to the bottom to actually use the site.

**Comment by lefnire** [comment]
holy crap! is anyone else experiencing this? I can't replicate. This is basically what happens on localhost if you don't have an internet connection, because it can't find the CDN js/css files. There's no reason it should be happening on prod however. I'll mark to crit and investigate

**Comment by applejess** [comment]
Opened up the error console in Firefox. I'm seeing a lot of "error in parsing value... declaration dropped" and "unknown property... declaration dropped" etc. if that helps at all.

**Comment by lefnire** [comment]
@applejess can you try beta.habitrpg.com and see if the above commit fixed the problem?

**Comment by applejess** [comment]
I would, but I just keep getting "The server is experiencing issues."

On the bright side, everything isn't loading at once anymore! Only because nothing is, but it's a start. Sort of.

**Comment by lefnire** [comment]
can you try again? you probly hit it on the 165 2h cron restart cusp.

**Comment by applejess** [comment]
Nope. Been trying for the past four hours now, periodically.

**Comment by lefnire** [comment]
@applejess what's your uuid or username?

**Comment by applejess** [comment]
6e59b675-7168-4088-a2ad-6c08e5a1d26b

**Comment by lefnire** [comment]
The story gets more interesting! I'm debugging your account locally, everything loads just fine for me. Now, beta.habit is running great, low resources & I can load my account. also, We just pushed websockets to beta & prod. I have a hunch... can you clear cookies for habitrpg.com and try again?

**Comment by applejess** [comment]
I didn't even need to clear cookies. It's working now! Thanks.
