### ISSUE TITLE
"undefined" in a notification from up-scoring a task

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7731]
![untitled_1](https://cloud.githubusercontent.com/assets/1495809/16376156/44f2251e-3ca2-11e6-9247-74cf4edd27b8.jpg)

That was reported in the Report a Bug guild by Okha (dc378150-cd9b-435a-a402-e1250b0ccf6c):

"Hi! Today I received "undefined" as a drop. I wonder what that might be... Here's the screenshot: https://s31.postimg.org/hfmv3xvgr/Untitled_1.jpg ... , it happened around 11:10 - 11:20 AM (Kyiv Time, +3 GMT), June 26"

From Amplitude, it seemed to be from clicking up on a Habit, but I couldn't find any other useful information.

Not high priority but I'm logging it in case we see it more often. We could however make sure that notifications aren't shown if the amount isn't defined.

**Comment by SabreCat** [comment]
Could this be a duplicate of #4548?

**Comment by Alys** [comment]
Let's assume it is. Nice catch.
