### ISSUE TITLE
Notification about the party is not deleted after check automatically.

### ISSUE THREAD

**Issue by dgodovanets** [HabitRPG/habitica#7735]
General Info
- UUID: 6b4563cf-ef71-4508-839e-f553d358dab9
- Browser: Google Chrome Version 53.0.2774.3 dev-m
- OS: Windows 7

About bug:
When I check my notifications about gild, it is deleted after check. But when I check notification about party, it is not deleted. I do it by click on X

**Comment by Alys** [comment]
Hi @Eramik. We have this reported at https://github.com/HabitRPG/habitrpg/issues/7393 so I'm closing this issue but you can follow #7393 for the progress of the fix. If you click the "fetch recent messages" button, the party notification is usually cleared.
