### ISSUE TITLE
Reset forgotten password should display a pop-up when mail is sent

### ISSUE THREAD

**Issue by Nairwolf** [HabitRPG/habitica#7737]
General Info
- UUID: 
- Browser: Firefox 47
- OS: Xubuntu
### Description

When you try to log in and you forget your password, you go in this [page](https://habitica.com/static/front#/forgot-password-panel). When you write your mail address, and you valid it by clicking on the submit button, there is no pop up or something else to tell you that it's okay, your password has been reset, and you received an email. 

Because nothing confirmed I clicked on the "submit" button, I recently clicked twice on the button. That would be great to add something here. 

Thanks

**Comment by Alys** [comment]
There is a standard JavaScript alert popup that appears after you've clicked "submit", saying "If we have your email on file, a new password has been sent to your email."

Please close all browser windows then reopen and try using that form again. 

If it still doesn't appear, look in your browser settings including in all your extensions, to see if you've blocked popups from Habitica in some way, and if so, unblock them.

If you still can't see the alert popup, tell us what extensions you have installed.

**Comment by Nairwolf** [comment]
Hi @Alys, 

I don't know why I haven't see that before, but yes, now, I see the JS alert popup which say this message "If we have your email on file, a new password has been sent to your email.". 

This issue can be closed

Thank you for your contribution and time on Habitica.

**Comment by Alys** [comment]
No worries. :) Thanks for letting us know!
