### ISSUE TITLE
The sprites for some equipment can touch the knockout image in the death modal

### ISSUE THREAD

**Issue by sporeball** [HabitRPG/habitica#7738]
**OS:** Windows 10
**Browser:** Google Chrome
**User ID:** ce3d1e2b-be53-4e5e-8101-273157548178 

Example:
![](http://i.imgur.com/HqdjknA.png)

I'll open a pull request to fix this soon.

**Comment by ghost** [comment]
For possible reference, the latest changes were introduced with https://github.com/HabitRPG/habitrpg/pull/7156 (I don't know if this issue is actually related to those changes, but linking just in case)

**Comment by sporeball** [comment]
Accidentally tapped the button to close the issue on GitHub's mobile site, haha. We're not done yet. 

@GitHubSphinx Looks like that issue just fixed some formatting with the text in the modal for the Russian translation. Thanks, though.

**Comment by sporeball** [comment]
@Alys This looks like it'll require changing the size of one of the spritesmith-main spritesheets (to make the knockout image in the spritesheet bigger). Is it fine if I do that?

**Comment by SabreCat** [comment]
@MrEikono: Editing any of the spritesheets directly won't help, because those images will be overwritten the next time we compile sprites. You'll want to edit the knockout image itself, found in `common/img/sprites/spritesmith/misc`.

**Comment by sporeball** [comment]
I don't know why my pull request fixing #7197 and the pull request I sent to my fork of the HabitRPG repository to update it are referenced in #7752 , but if changing the knockout image itself is the only thing I need to do, #7752 adds 80 pixels of width to the knockout image, which looks it like it should be enough.

**Comment by sporeball** [comment]
Just changed the width of the knockout image again in 7b9a340. Here's a screenshot -

![image](https://cloud.githubusercontent.com/assets/12767408/16542945/032bf550-4072-11e6-81f7-82e0d882430c.png)

**Comment by SabreCat** [comment]
@lemoness, what do you think?

**Comment by lemoness** [comment]
That might be a little too far to the right. How does it look over the user's head?

**Comment by sporeball** [comment]
@lemoness Does this look okay? 
![image](https://cloud.githubusercontent.com/assets/12767408/16718292/87caf4de-46d3-11e6-869e-9ffc9ac355f4.png)

**Comment by sporeball** [comment]
Don't mind the 30 or so new commits in #7752 , I'm just bad at rebasing apparently

**Comment by ghost** [comment]
@MrEikono for what it's worth it feels that some pieces of head gear might touch the knockout image if it's placed above the head like that. You may want to test the [Shade Helm](http://habitica.wikia.com/wiki/Backers#Backer_items) for example, [Flame of Mind](http://vignette3.wikia.nocookie.net/habitrpg/images/b/b9/Head_mystery_201405.png/revision/latest?cb=20150712063217) or [Crown of Tentacles](http://vignette3.wikia.nocookie.net/habitrpg/images/c/cb/Head_mystery_201406.png/revision/latest?cb=20150712063218)

**Comment by SabreCat** [comment]
...I only just now got the joke inherent to "Flame of Mind".

I'm slow. Like, two years slow, apparently.

**Comment by lemoness** [comment]
I guess you just weren't in the right frame of mind for it ;)

But yes, I think that many of the helms will unfortunately overlap.

**Comment by Alys** [comment]
Oh.... frame of mind.... I TOTALLY got that after Sabe's comment and didn't have to wait for Lemoness's reply AT ALL. :blush:

**Comment by sporeball** [comment]
Fixed the fork. Testing various pieces of head gear now.

**Comment by sporeball** [comment]
Even the Shade Helm doesn't overlap with this setup. (Is the knockout image too close to the health bar now, though?)

![](http://i.imgur.com/UWIcr6X.png)

I'll have to adjust the dimensions of the knockout image accordingly if this is fine, so we won't have to use any `top` or `left` values on `.knockout`, but here's what I did in Chrome's developer tools:

![image](https://cloud.githubusercontent.com/assets/12767408/16828457/c05d4338-4944-11e6-9eb1-21d11d53bd45.png)

Quick question, though - how do I get the backer-only items as equipment in my inventory when using Habitica locally? I had to change the style for the element for the head gear to this just to get it to show up and be centered correctly:

![image](https://cloud.githubusercontent.com/assets/12767408/16828505/2095ff74-4945-11e6-83b7-2811d4d6ee08.png)

**Comment by lemoness** [comment]
Hm. How does it look in that position with a variety of different helms
(and no helm at all)? Having a variety of equipment in the mockups will
make it easier to see what looks best overall.

**Comment by sporeball** [comment]
@lemoness I'll be at my computer a bit less until Thursday, but I'll try to find some time to test with as many helms as possible. 😊

**Comment by sporeball** [comment]
Ended up being a bit more busy than I thought I would be, but I'm testing every helm as I write this. And: 
![image](https://cloud.githubusercontent.com/assets/12767408/17063020/3e733466-4fea-11e6-81fd-588bdf076069.png)

@lemoness I'm a bit skeptical about moving the knockout image even higher than in the screenshot with the Shade Helmet, because then it would be really, really close to the health bar; what do you think about that?

**_Edit:**_ Looks like the only helms that come into contact with the knockout image when it's put at the position shown a few comments ago are the Crystal Crescent Helm (above) and the Marching Bard Hat: 
![image](https://cloud.githubusercontent.com/assets/12767408/17063747/a9d56492-4fed-11e6-8d37-459f78da9d82.png)
 The Cat Hats come pretty close but don't touch the knockout image.

Here's [an imgur gallery](https://imgur.com/a/UwGOF) with a few different helms, as requested.

**Comment by audiolion** [comment]
the off centered knockout animation with some of the hats makes it look a little strange. It is unfortunate that we do not have more space to separate the two because if it was higher above it would be more distinct and centering wouldn't matter as much I feel like.

**Comment by lemoness** [comment]
It's turning out to be tougher than expected to get something that looks
good consistently. Some other options we can try:
- two knockout sprites on either side of the avatar, out of weapon/shield
  range
- a knockout sprite ABOVE the health bar, separated from the avatar

**Comment by sporeball** [comment]
Knockout sprite above the health bar:

![](http://i.imgur.com/C0PiOxF.png)

Maybe two knockout sprites could look something like this:

![](http://i.imgur.com/o1i80UZ.png)

I also tried putting the knockout sprite under the avatar:

![](http://i.imgur.com/vHDYSDb.png)

**Comment by khipkin** [comment]
I think the double icons look the best!  It also matches the way double achievement icons are shown in achievement modals.

**Comment by sporeball** [comment]
@lemoness Which one should we go with?

**Comment by lemoness** [comment]
I also like the double knockout, for the same reason. Let's go with that
one.

**Comment by sporeball** [comment]
I'm probably just being a complete idiot right now, but I can't figure out how to make a single sprite with two knockout faces work without using extra CSS values... Is using extra CSS values even viable?

**Comment by SabreCat** [comment]
@MrEikono: Additional CSS is okay. The CSS that's there is a bit of a mess of inline styles, too, so if you see opportunities to standardize things / make classes, go for it.

**Comment by sporeball** [comment]
I'm unable to compile sprites to test the changes I've been making recently, so I'll continue fixing this issue as soon we figure out a solution to that problem.

I just opened #7915 for the problem with compiling sprites.

**Comment by sporeball** [comment]
Okay, so I'll finally have a decent chunk of time to get back to this issue tomorrow on October 10.
Sorry for the insane delay guys. ;_;

**Comment by sporeball** [comment]
... 

So, the chunk of time from earlier got negated because of git merge conflict nonsense. Sorry, people who reacted with confetti. 

However! I have a break from school for the next week! Hopefully I can use this time to **get. this. issue. done...!!**

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by sporeball** [comment]
oh gosh i completely forgot Habitica was ever a thing (and, accessorily, this problem)
i'm so sorry 😞 
i'll get my act together and check very soon

**Comment by sporeball** [comment]
looks like this is no longer a problem since the knockout image isn't in the death modal anymore.
what is an issue is that my costume now slightly touches this circle
![image](https://user-images.githubusercontent.com/12767408/31749473-149d42a8-b42f-11e7-8edb-3acefcef6888.png)
but that's a new issue, so i guess i'll close this one

**Comment by lemoness** [comment]
Thank you very much!
