### ISSUE TITLE
no weapons after restore

### ISSUE THREAD

**Issue by kriscrat** [HabitRPG/habitica#774]
I bought a weapon, but had to use restore to get it because things froze partway through buying it.  Now I have no weapons I can buy.  Help?

![Capture](https://f.cloud.github.com/assets/4007169/340407/da688fca-9d4f-11e2-9205-4c05b6254ea6.PNG)

**Comment by lefnire** [comment]
Did you restore the Gold Sword? That's the last weapon, buy armor instead

**Comment by kriscrat** [comment]
Ok! Sorry for a silly question.  In the restore I noticed I could go above level 6, so I thought there were more. Thank you! 

From my Android phone on T-Mobile. The first nationwide 4G network.

-------- Original message --------

**Comment by rixx** [comment]
The issue can be closed, then?
