### ISSUE TITLE
Bailey announcements no longer have dates in the titles

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica#7741]
The last three Bailey announcements have omitted dates from the titles. The dates were helpful for several reasons:
- Users are in different time zones, so statements like "This is the final day to subscribe and receive the Selkie Item Set" are more precise/meaningful.
- The dates made the [Old News page](https://habitica.com/static/old-news) easier to read since the numerals helped signal each separate announcement.
- In the wiki, we include dates on the [What's New](http://habitica.wikia.com/wiki/Whats_New_2016) pages and sometimes provide dates features were released on other pages.

**Comment by crookedneighbor** [comment]
@SabreCat @lemoness

**Comment by SabreCat** [comment]
Yup, just an oversight. I usually add them in if they're not part of the text @lemoness provides, but I must have spaced out the last few times. I'll add it to my checklist!
