### ISSUE TITLE
500.html is out of date

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#7745]
[/website/client/500.html](https://github.com/HabitRPG/habitrpg/blob/28f2e9c356d7053884107d90d04e28dde75fa81b/website/client/500.html) is very out of date.
- [ ] The page title uses "HabitRPG" instead of "Habitica".
- [ ] It either directs the user to a long-closed bug in the old repo ([here](https://github.com/lefnire/habitrpg/issues/165)) or to a blog post that no longer exists ([here](http://habitrpg.tumblr.com/post/55655159428/0-5-upgrade-aborted-angularjs-future)).
- [ ] There's an invitation for all angular developers to join the angular-rewriting efforts in the `angular_rewrite` branch in the old repo ([here](https://github.com/lefnire/habitrpg/tree/angular_rewrite)), which no longer exists.
- [ ] The page also suggests that users try out [the beta site](https://beta.habitrpg.com/), which may or may not still exist.  (It seems like it doesn't exist, but I'm not sure.)

**Comment by crookedneighbor** [comment]
That page is not actually used anymore. It should just be deleted.
