### ISSUE TITLE
giftedSubscriptionInfo string may be inacurate 

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7747]
Reported by @Racobot and @lyubomirv on Transifex

`giftedSubscriptionInfo` string is `<%= name %> gifted you a <%= months %> Subscription`

With regard to its use in payment.js 

`message: shared.i18n.t('giftedSubscriptionInfo', {months, name: byUserName}),`

the string supposedly results in e.g. `"User gifted you a 3 Subscription"` (for 3 months subscription) which doesn't feel right.

The string should be changed to include `month(s)` or be rethought to provide for pluralization: 1 month, 3/6/12 months

**Comment by crookedneighbor** [comment]
month(s) seems like the right solution to me.

**Comment by Alys** [comment]
Yes, in the code `months` is just a number, so the word "month(s)" will be missing from the message.

Also something for us to check: is the language being chosen correctly for that message? Is it picking up the receiver's language (desired) or the sender's language (incorrect)? https://github.com/HabitRPG/habitrpg/blob/develop/website/server/libs/api-v3/payments.js#L109-116

**Comment by khipkin** [comment]
@Alys that localization problem is also addressed in #7722.

**Comment by ghost** [comment]
A separate issue, but from the same field:

an inbox message about sending/receiving gems from [members.js#L366](https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/members.js#L366):

```
    let message = res.t('privateMessageGiftIntro', {
      receiverName: receiver.profile.name,
      senderName: sender.profile.name,
    });
    message += res.t('privateMessageGiftGemsMessage', {gemAmount});
    message =  `\`${message}\` `;

    if (req.body.message) {
      message += req.body.message;
}
```

has a space missing which results in

`Hello <%= receiverName %>, <%= senderName %> has sent you4 gems! <optional message>`

**Comment by Alys** [comment]
The missing space in @GitHubSphinx 's second comment (just above) has been fixed.

**Comment by librarianmage** [comment]
Just for clarification, what exactly is the issue here?

**Comment by Alys** [comment]
@MathWhiz  Embarrassingly, it turned out to be a one-word fix that could have been done at any time. I've fixed it here: https://github.com/HabitRPG/habitica/commit/9aa4b8aa64ccdfa3af4a6832cc3dded4b102b73e
Thanks for asking about it!

@GitHubSphinx Note my comment about pluralisation at the top of https://github.com/HabitRPG/habitica/commit/9aa4b8aa64ccdfa3af4a6832cc3dded4b102b73e

**Comment by ghost** [comment]
@Alys thank you for taking time to fix it! I'll add comment to Transifex about pluralization.
