### ISSUE TITLE
Post cron damage report does not include boss damage

### ISSUE THREAD

**Issue by joedragons** [HabitRPG/habitica#7749]
General Info:
- UUID: 66902097-c79b-496f-acd9-b78cc5867b28
- Browser: FF (47)
- OS: Windows 7

Description:
I noticed that after shutting down my machine for the evening pre-cron, when I wake the next day and load habitica, damage for incomplete dailies is given but that damage does not include damage (also from incomplete dailies) given by a quest boss you're fighting.

---Example---
Before I went to bed full health:
![habitica-nightbefore2](https://cloud.githubusercontent.com/assets/9559205/16536474/1c9912a0-3fc0-11e6-89d9-756317d0dcf8.png)

Next day when I got up (see damage is different than cron damage overnight report):
![habitica-dayafter2](https://cloud.githubusercontent.com/assets/9559205/16536499/505a8db2-3fc0-11e6-88b2-6460ecd19510.png)

The boss damage (added together they total what I took correctly):
![habitica-damage](https://cloud.githubusercontent.com/assets/9559205/16536505/59b16d54-3fc0-11e6-9eb2-045b94959c65.png)

I spoke to @Alys about this in the Report a Bug Guild (now scrolled off) and was suggested that I post screens if I saw a discrepancy and I felt this was the right place (rather than there again).  Not convinced I explained it very well there; hopefully this is a bug.  Let me know if still unclear.

If it's intentional, I'm curious if a suggestion to include it would be accepted (if one doesn't already exist) or if that'd be a waste of my time.  It seems like seeing all the damage you've taken would be useful rather than partial.  This seems to be how it works when I switch between machines (gives a summary of gains/losses since last accessed rather than just the latest entry or individual entries).

@Alys also mentioned when helping me in the Report a Bug Guild that my health was different at that time then post-cron which is also currently true.  If it helps to keep my health the same after this occurs I probably can (at least for a while=)).  I wasn't sure the relavence so decided to go about my normal day.

PS: I don't believe related but when I mentioned I was doing this to my party member today, they mentioned that they had not taken any damage that day despite me taking it from the boss (and their cron going off; I checked and indeed they had damaged the boss after me).  I am mentioning in the off chance it's related (and maybe specific to my group somehow).  I've never noticed this myself but probably because they are kind and never damage me.

**Comment by Alys** [comment]
That health notification that you see is meant to tell you the total health
loss/gain since the last time the website synced to the server. Did a
healer in your party cast a skill to increase everyone's health either just
after your boss damage message in party chat, or any time in the several
hours before? If so, they increased your health enough that the total
health change you experienced was only -0.2. Let us know if that explains
it or not!

**Comment by joedragons** [comment]
@Alys Thanks for the reply.  I confirmed with my party member, who is (currently) a healer, that they did not heal me between the time of the two screenshots or at all since.  It also does not show in the party log (which I can attach more of if it helps).

I did cast a personal heal later in the day, but it was hours later.

**Comment by joedragons** [comment]
RE:PS- This occurred to me again this morning and this time my party member did take damage so I suspect it is unrelated as I originally stated (tho maybe another bug lurking).

However, of note to the original description, I asked them to check if they received a window in the morning from the overnight boss damage and they did not receive anything though their HP was down the "correct" amount.  I believe this is also the same bug.  (I verified they had completed all their dailies and none of the damage they received was self inflicted)  They asked if they should take a screenshot but there's really no screenshot to take since there's no window, so I told them no.

**Comment by paglias** [comment]
Now that local storage isn't used anymore the damage notification won't include the boss damage. We should probably add a new type of notification to user.notifications for this case

**Comment by Hus274** [comment]
I can take a look into making this notification.

**Comment by joedragons** [comment]
FYI, I logged in this AM to accept my damage and did not notice any change.  I am now on Windows 10 and FF51 but otherwise seems to behave the exact same for me.  I am not sure if there's any reopen procedure or I should file again or what.  I will keep an eye out to make sure I am not just sleepy and missed it but I am certain I saw the non-boss damage and I am certain I took damage so unless they're largely seperated messages I am pretty sure.  It seemed pretty much as I originally described.  I take damage rarely (yay:P) so not sure when I'll get a chance the next time.  If I can provide any more info here please let me know.  cc/ @TheHollidayInn @Hus274 

UPDATE: Noticed again 2/22/2017
UPDATE2: This morning (7/20/17), I noticed this fix applying.  This is the first time I've noticed but I admit to not paying attention every day (nor do I take damage every day).  Thanks for all the hard work=)
