### ISSUE TITLE
Native macOS app

### ISSUE THREAD

**Issue by saada** [HabitRPG/habitica#7753]
Hey Habitica team, 

I didn't know where else to reach you. I just built a [native macOS version of the web app](https://github.com/saada/Habitica-macOS).
I'd be more than happy to move my repo to your official Github organization.

Thanks for making Habitica,
- Moody

**Comment by crookedneighbor** [comment]
Hi @saada, at this time we won't be supporting an desktop apps that wrap the web app. You can, however, add your app to the [Habitica wiki](http://habitica.wikia.com/wiki/Category:Apps).

If you need help with that, feel free to [chat in the Aspiring Comrades guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e), which is focussed on developing 3rd party apps and extensions for Habitica.

Also, I'm happy to mark you as a contributor for this app. What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by saada** [comment]
Thanks @crookedneighbor 
my userid: 4d6b8d45-d4d0-44b8-b149-e25b5c7ede09

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!
