### ISSUE TITLE
[Suggestion] Create debug script to give char gems

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#7756]
### Description

Today i tried to test a part of the website that need Gems at my local env but i could not find how to give my char Gems. Maybe is as simple as editing the gold amount at the database, but i didn't find out how.

Since we have debug scripts to equips, mounts and pets, we should have for gems too.

**Comment by crookedneighbor** [comment]
Go to the footer: 

![screen shot 2016-07-02 at 11 01 24 pm](https://cloud.githubusercontent.com/assets/2916945/16543706/ed83b166-40a8-11e6-99a7-cd5f108d9d08.png)

**Comment by luanmuniz** [comment]
@crookedneighbor Thank you, didn't saw that. Maybe mention it in the readme, next to the debug scripts?
