### ISSUE TITLE
Can't Delete To-Do's and Tasks for Closed Challenges

### ISSUE THREAD

**Issue by RedCloakLife** [HabitRPG/habitica#7757]
I have joined a few challenges over my time on Habitica and each time one comes to an end the tasks/dailies/to dos are still on my page and I cannot delete them. I can't find the challenge to leave it since the challenge is closed and I don't know how to clear these items from my lists.

User ID: baec4cdf-61d1-4f42-aa63-42cce8a1866d

**Comment by khipkin** [comment]
Do any of them have a little red megaphone icon next to them?  If so, try clicking on that.  A "remove" option should pop up.

**Comment by RedCloakLife** [comment]
Ooph, that worked perfectly. Thank you so much!

**Comment by Alys** [comment]
@RedCloakLife thanks for letting us know it's working.

@khipkin Thank you!
