### ISSUE TITLE
API rate limiter

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7759]
In v2 we had a middleware to throttle API requests, it's been removed in v3 because it was not supported anymore but we should add something back to limit the number of requests an IP can make.

The last used version can be found here https://github.com/HabitRPG/habitrpg/blob/47f6f2febecb3aea2b805ba77a0c8e1c8b095389/website/src/middlewares/apiThrottle.js

**Comment by luanmuniz** [comment]
https://github.com/HabitRPG/habitrpg/blob/develop/website/server/middlewares/apiThrottle.js
This file still exist, with another module making the limit. But this file is not called anywhere.

Can you explain in details what we should do? that way i can send a PR. Thank you

**Comment by paglias** [comment]
@luanmuniz unfortunately this will require some deep changes because the app is spread across multiple server and a local throttler would be pretty meaningless as there isn't an easy way to share the data about requests across servers. 

Thanks for the interest but for now I don't think we'll make any change for this

**Comment by luanmuniz** [comment]
There are a few modules that can plug a Redis store in it and it can work in multiple instances
https://www.npmjs.com/package/express-rate-limit
https://www.npmjs.com/package/rate-limit-redis

But the problem here is that we need a Redis instance, i could not find anything mentioning redis in the code so i think we don't have one today.

**Comment by paglias** [comment]
Yeah, no Redis or any other in memory store for now

**Comment by lemoness** [comment]
Is this still something we need?

**Comment by paglias** [comment]
Yes

**Comment by lemoness** [comment]
I've updated this labels on this issue!

**Comment by TheHollidayInn** [comment]
This will be handled internally because we will most likely implement this at the devops level.
