### ISSUE TITLE
Challenges: "Select All" doesn't select all challenges

### ISSUE THREAD

**Issue by camdroid** [HabitRPG/habitica#7763]
General Info
- UUID: beb555b6-31ab-4da2-b168-0d02d4c6dda9
- Browser: Chrome 51.0.2704.106
- OS: OS X El Capitan 10.11.5 (15F34
### Description

When clicking "Select All" in the Challenges view, not all challenges are actually selected.

After clicking "None":
<img width="1395" alt="screen shot 2016-07-05 at 2 44 46 pm" src="https://cloud.githubusercontent.com/assets/189652/16601194/106e7378-42c0-11e6-83fc-89102b342d62.png">

After clicking "All":
<img width="1390" alt="screen shot 2016-07-05 at 2 45 00 pm" src="https://cloud.githubusercontent.com/assets/189652/16601286/7fab594a-42c0-11e6-8962-cb22a4010e74.png">
#### Console Errors

Doesn't seem to be related, but this pops up when I click "All"."
`Mixed Content: The page at 'https://habitica.com/#/options/groups/challenges' was loaded over HTTPS, but requested an insecure image 'http://s33.postimg.org/59bddirb3/You_Tube_logo_full_color.png'. This content should also be served over HTTPS.`

**Comment by khipkin** [comment]
Weird. Maybe an off-by-1 error or something?

[Here](https://github.com/HabitRPG/habitrpg/blob/28f2e9c356d7053884107d90d04e28dde75fa81b/website/views/options/social/challenges.jade#L86) is the "All" group filter button, which calls the challenge controller's `selectAll()` function ([here](https://github.com/HabitRPG/habitrpg/blob/28f2e9c356d7053884107d90d04e28dde75fa81b/website/client/js/controllers/challengesCtrl.js#L366)).

**Comment by Alys** [comment]
It currently shows you all the guilds that host challenges you have joined, but the select all button highlights only guilds that you are a member of.

The desired behaviour is to highlight all guilds in that list.

**Comment by IanThorp** [comment]
I will take a look at it later today. See if I can do anything to help.

**Comment by Ozzystrasza** [comment]
@IanThorp Did you get a chance to work on this? If not I will try to fix it.

**Comment by Ozzystrasza** [comment]
I could reproduce this by joining a guild then joining a challenge in that guild, then leaving the guild. Doing that also kicked me out of the challenge but the guild name still appears in the filter list and the "all" button won't select it.
Question: Should I just fix the "all" button to select that guild along with the others, even though I'm not participating in the challenge anymore(got kicked out), or should that guild stop appearing in the filter list?

**Comment by Alys** [comment]
The "all" button should be fixed so that it selects all guilds in the list.

There are other ways to be in a challenge without being in the guild, and they also cause the guild to appear in the list without being selected by the button.

Being kicked out of challenges when you leave a guild is going to be fixed in another issue.
