### ISSUE TITLE
can't flag system messages in party chat

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7767]
It's no longer possible to flag the system messages in party chat - i.e., the messages that report skills cast and quest progress. They need to be flaggable so that players can report them when the person mentioned has an inappropriate name.

The error message is: `"member" must be a valid UUID.`

Having a UUID check is good, but we should make an exception for system messages.

**Comment by Hus274** [comment]
I can take a look into this.

**Comment by shanaqui** [comment]
This needs to be reversed -- in practice, people don't use it to flag offensive usernames (which would be fine in private chat anyway), and instead, it seems to cause a lot of confusion, or people hoping we'll delete them if they flag them.

**Comment by Alys** [comment]
@shanaqui I've logged it here: https://github.com/HabitRPG/habitica/issues/8824
