### ISSUE TITLE
Some pets appear on top of the background border

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7769]
General Info
- UUID: 60e9e6cd-efdb-4e9d-8035-3277c3276d52
- Browser: Chrome
- OS: Windows 10
### Description

I'll just copy paste my comment from the Report a Bug guild:

> Idk if this counts as a bug, but some pets appear on the background border. Click on my profile (or check this [screenshot](http://vignette2.wikia.nocookie.net/habitrpg/images/6/66/8c1d6f2e-22c9-41fd-8e04-d698e4118cf1.png/revision/latest?cb=20160705200351)) to see what I mean.
> I noticed that this happens with the plain egg and the falcon pets. I don't have enough pets to find more, but you can tell which pets this happens with by going to the pets page - any pet that "touches" the food bar will end up on the background border.
> _by "touches" I mean that there's no space between the pet image and it's food bar, like [here](http://i.imgur.com/E58Y2Ti.png)._
> I guess it could be fixed by editing the PNGs of those pets and moving the art a little bit up?

Alys contacted Lemoness about this, and she said that she'd like to have that fixed by having the pets positioned higher.

I'm not sure if she meant to position them higher by editing the PNGs of the specific pets this happens with, as I suggested, or by changing the code to move all pets a little bit up.

I have to say I don't think changing the position of the pets by changing the code is the best idea. First, there are some backgrounds which are designed with pets in mind, so altering this might make these backgrounds look weird. And secondly, I also noticed now another odd behavior in the Pets page, which I believe is related to the misaligned sprites. When feeding pets, some sprites get cropped off, like [here](http://i.imgur.com/g4etSMf.png). This is clearly visible on the Egg pets, but also slightly on the Gryphon and Deer pets.

I looked around, and I'm pretty sure this is caused due to the pet sprites being located in the corner of the image. Check the [Flacon](https://github.com/HabitRPG/habitrpg/blob/develop/common/img/sprites/spritesmith/stable/pets/Pet-Falcon-Base.png) and [Egg](https://github.com/HabitRPG/habitrpg/blob/develop/common/img/sprites/spritesmith/stable/pets/Pet-Egg-Base.png) sprites, for example. Their art is right there in the corner. Now if you'd check the [Wolf](https://github.com/HabitRPG/habitrpg/blob/develop/common/img/sprites/spritesmith/stable/pets/Pet-Wolf-Base.png), you'd see that the art is more centered.

I know that it's possibles to align photos to the center using Photoshop or GIMP, and that it can also be used in a batch. So I wouldn't mind doing that myself, just give me the word :)

**Comment by Alys** [comment]
Speaking for myself, I quite like it when the pets are more to the left because it hides less of the mount and avatar. Perhaps you could move the Falcons and Eggs up a pixel or two without moving them horizontally? That's a personal opinion though.

I'm pretty sure Lemoness meant editing the PNGs. I agree with you that changing the code wouldn't be the best approach.

**Comment by ghost** [comment]
@Alys yeah, good idea. I could probably do that. But I'd still rather do it for all pets...

I mean, I'm sure there are other pets that behave like this, other than the Egg and Falcon, so moving all pets will fix it for any other ones this is happening to.
And I think it would be nice for all pets to appear at about the same spot, instead of having each pet in a slightly different place.

I'm now starting to think that it might be best to just center all pets, and _then_ change the code so they would appear slightly more to left of the avatar. This will also make sure that pets aren't cropped when highlighted by feeding.

Anyway, this was all my personal opinion now, I'm gonna leave the decision up to you (or Lemoness).

**Comment by ghost** [comment]
So, uhmm.. commenting again since it looks like this has been forgotten.

Still waiting for a response on how this should be done..

**Comment by ghost** [comment]
Okay, I decided to go on and just make 2 versions - one where all of the pets are at the bottom middle, and another where they'all at the bottom left (except for the flying pig, which is at the top).

They can be downloaded here:

pets_middle.rar - [Google Drive](https://drive.google.com/file/d/0B7Jc0QSXtv_qNlBOWDdwWURrUUU/view) | [ZippyShare](http://www53.zippyshare.com/v/3SxNRFaE/file.html)

pets_left.rar - [Google Drive](https://drive.google.com/file/d/0B7Jc0QSXtv_qbjBIT3UyMGpHU0E/view) | [ZippyShare](http://www53.zippyshare.com/v/CLMWNRvf/file.html)

As I mentioned before, I think the best method would be to use the middle version, and then change the code to move all pets a bit to the left of the avatar.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Is this still something that needs to be done?

**Comment by Alys** [comment]
Since no one has reported this as still happening in the new website, I'm closing it but we can reopen if needed.
