### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7775]
General Info
- UUID: b17c9359-9ed1-44df-9437-cf954cb49b98
- Browser: Safari
- OS: 
### Description

Hello, I am trying to delete my account, but it seems that I have the wrong password. If you can help me in any way, please and thank you. Below, it shows what happens after I hit enter for the passwords. 

<img width="287" alt="screen shot 2016-07-11 at 10 40 22 am" src="https://cloud.githubusercontent.com/assets/20402723/16736780/152631d8-4754-11e6-8441-7f5d90a9a315.png">

**Comment by paglias** [comment]
@aslinkma it looks like yours is a Facebook account and currently we have a bug preventing those accounts from being deleted correctly, sorry about this!

Right now the only way to deleted FB accounts is to add local authentication to your account (email and password) from the settings page, then you'll be able to delete the account using the same password:

<img width="702" alt="schermata 2016-07-11 alle 18 08 37" src="https://cloud.githubusercontent.com/assets/589911/16737642/90c559f2-4792-11e6-961e-4fb564016ccd.png">

**Comment by ghost** [comment]
Thank you!
