### ISSUE TITLE
static/features: missing image

### ISSUE THREAD

**Issue by lynxlynxlynx** [HabitRPG/habitica#7778]
https://habitica.com/static/features has a reference to https://habitica.com/common/img/sprites/spritesmith/quests/quest_vice3.png (above "Fight Bosses") which can't be found anymore.

**Comment by khipkin** [comment]
Confirmed.
![image](https://cloud.githubusercontent.com/assets/5641207/16750838/e28a25aa-47d4-11e6-9595-901f8f9a4dd3.png)

**Comment by citrusella** [comment]
I believe the correct URL is https://habitica.com/common/img/sprites/spritesmith/quests/bosses/quest_vice3.png, after working out the syntax from [this](https://github.com/HabitRPG/habitrpg/blob/develop/common/img/sprites/spritesmith/quests/bosses/quest_vice3.png).
