### ISSUE TITLE
Boss rage effect message in chat doesn't have code style which may look odd

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7779]
The rage effect string in party chat doesn't use the code formatting. It looks a bit odd among other system messages.

Example:

![pic](https://snag.gy/FMYzNX.jpg)

Place in the code: https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/group.js#L531

**Comment by Ozzystrasza** [comment]
I'd like to work on that one, if it's ok.

**Comment by Alys** [comment]
@Ozzystrasza Please do! Thanks!

**Comment by Alys** [comment]
@Ozzystrasza You can reproduce this error by starting the The Magical Axolotl quest, leaving some due Dailies uncompleted, then forcing cron by using the "missed +1 day" button in the debug menu in the footer of the website on your local install and then clicking the sync button. Tell us if you need more details!

**Comment by Ozzystrasza** [comment]
@Alys That worked thanks! And I fixed the problem! Well at least in my local version, now I don't know exactly how to make the same changes here.
I made changes to these files:
common/locales/ja/questscontent.json
common/locales/en/questsContent.json 
common/locales/ro/questscontent.json 
common/locales/sk/questscontent.json 
common/locales/zh_TW/questscontent.json 
common/locales/en@pirate/questscontent.json 
common/locales/uk/questscontent.json 
common/locales/sv/questscontent.json 
common/locales/sr/questscontent.json 
common/locales/hu/questscontent.json

**Comment by Alys** [comment]
@Ozzystrasza In general, you need to commit your changed files, then push your changes to your own GitHub copy of the repository, and then do a pull request. See Guidance for Blacksmiths for more details, or look at any good git instruction website (the Guidance page has links to one or two good ones).

However note that in this particular case, you don't want to commit all of those files - just the `.../en/...` file. See the README files in the other language directories for the reason why. To commit just that one file you can do this:

`git commit common/locales/en/questsContent`

**Comment by ghost** [comment]
TBH I would be slightly against solving it this way. If I get it right, you want to add markdown styling in locales text. It would leave space for inconsistencies if/when translators misunderstand the purpose of "those symbols at the beginning and at the end". If there's no other way, I would add instructions to translators, but I'm almost sure we'll end up having at least one language not processed as expected

**Comment by Ozzystrasza** [comment]
hmmm I could try a diferent way, but I did that because the first line of the text ("Magical Axolotl uses AXOLOTL REGENERATION!") already had markdown styling in the locales text, so I thought someone just forgot to do the same for the second line.

**Comment by crookedneighbor** [comment]
I see your point @githubsphinx, but we should just  change the locale for now. We're going to do a redesign of the frontend soon and we may decide to change how system messages are displayed. We can make decisions about how the locales are done then.

**Comment by ghost** [comment]
OK, you got me convinced XD
