### ISSUE TITLE
Task notes don't always disappear properly after hover

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7784]
General Info
- UUID: `0e1d15f7-f36b-4f15-a9e1-0c31b732dac9`
- Browser: Chrome 51
- OS: Ubuntu 14.04
### Description

![image](https://cloud.githubusercontent.com/assets/9433472/16819931/8be4633c-4946-11e6-8028-e1177819103d.png)

To reproduce:
1. have a task with extra notes
2. hover over task, notes appear
3. hover over progress button, tooltip appears
4. move cursor up over tooltip as it disappears and onto the extra notes popup
   - cursor has to move fairly slowly (moving too fast makes the popup disappear), but must move onto the notes popup by the time the tooltip vanishes
5. move cursor off notes popup, popup does not dismiss
#### Console Errors

None

**Comment by keysmashes** [comment]
I did some more testing, and I think in order to reproduce, you can just leave the cursor on a tooltip like 'Progress' until the tooltip disappears. The extra notes popup is then wedged open until the mouse moves onto and off the task.

**Comment by dv4quadcore** [comment]
Hi, I'm interested in addressing and fixing this!

**Comment by SabreCat** [comment]
@dv4quadcore: You're welcome to have a look! Note, however, that we're working on a rewrite of the front-end design, so this issue may become moot within the next few months. If you don't mind your work being incorporated with that caveat, though, carry on!

**Comment by Alys** [comment]
@dv4quadcore  I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this issue might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it. We'll assess it after the new website code is live and then if it's still needed, you'd be welcome to keep working on it if you wish.

**Comment by lemoness** [comment]
This is no longer relevant in the new site, so I am closing this ticket!
