### ISSUE TITLE
A cheap way to get free eggs

### ISSUE THREAD

**Issue by acrylicconstellations** [HabitRPG/habitica#7786]
General Info
- UUID:  d0fcef2a-f556-4dae-aeb5-c6b19c63ae38
- Browser: Google Chrome
- OS: Chromebook
### Description

Sometimes when you complete dailies, an egg gets dropped. I accidentally found while trying to fix some values that if you keep clicking to complete/uncomplete dailies, you can get a lot of eggs of that certain pet. It could be a way to cheat, I don't know if it even counts as a bug.

**Comment by Alys** [comment]
Thanks for telling us! However we don't really mind about this. :) It can even be useful as part of a custom reward. See my comment at https://github.com/HabitRPG/habitrpg/issues/4626 for more details.
