### ISSUE TITLE
When an invitation is accepted, the inviter should be notified.

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7788]
When a Party or Guild invitation is accepted, the person who sent the invitation should receive a notification that it was accepted.

Sample text:

[NAME OF USER] accepted your invitation to [NAME OF GUILD/PARTY]!

**Comment by Hus274** [comment]
I can work on this.

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]
