### ISSUE TITLE
party invitations can't be removed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7793]
Reported by Kingkrimmson (cea63e37-cf21-4296-a2d5-416dd8664e9a) in the Report a Bug guild:

**Hey, I'm a party leader and noticed that when I try to "Boot Member" for someone who has been invited but hasn't join yet (effectively to rescind invite), they are removed from the list, but when I come back to the party screen, they're still listed. Is this a known issue, or am I missing something?**

I've seen similar comments before but looks like we don't have an issue for it. I haven't tested yet to see if it's reproducable. If anyone seeing this would like to test and comment, please do, otherwise I will later when I have some free time.

**Comment by Hus274** [comment]
I was able to reproduce this. It appears that the invite is not rescinded. The invitation shows up on the party screen again after refreshing the page and the invited user is still able to join the party.

**Comment by Alys** [comment]
@Hus274 Thank you! I've marked this as help welcome.

**Comment by Hus274** [comment]
This appears to only happen with parties, not with guilds.

**Comment by Hus274** [comment]
I'll look into this
