### ISSUE TITLE
Guild gems box doesn't align with anything else

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#7796]
General Info
- UUID: `0e1d15f7-f36b-4f15-a9e1-0c31b732dac9`
- Browser: Chrome 51
- OS: Ubuntu 14.04
### Description

![image](https://cloud.githubusercontent.com/assets/9433472/16820387/b0cfb3d4-4948-11e6-861e-815c39515b37.png)

IMO the guild gems box looks kind of odd stuck to the right-hand side like that. I don't know what it looked like before (or even if it changed, I might just be going mad), but I think it might look better if it 
aligned with the infobox on the left and speech bubble below and had centred text and icon:

![image](https://cloud.githubusercontent.com/assets/9433472/16820725/68e9b63a-494a-11e6-81a7-4c95df6dbedf.png)

If people think this looks better, I'd like to work on it.
#### Console Errors

n/a

**Comment by Hus274** [comment]
I think this looks good!

**Comment by ghost** [comment]
As far as I can judge from the picture, the changes also fix #5507

**Comment by keysmashes** [comment]
If anyone knows what `.tile.flush` is currently used for (or has a way to find out), I'd love to know! [This](https://github.com/HabitRPG/habitrpg/blame/develop/website/client/css/tasks.styl#L512) is affecting the guild gems box, and I'd love to just delete it given it was last touched in 2013.

Also, is there anywhere I should be putting guild-related CSS? I've been finding stuff strewn across several files, and no obvious place to put new styles. I guess I'll probably put it in website/client/css/inventory.styl, since there's some stuff about `.gem-wallet` at the top of that.

**Comment by khipkin** [comment]
@anowlcalledjosh `.tile.flush` is used [on these two lines](https://github.com/HabitRPG/habitrpg/blob/b4b0d7e89cd2fa0a7de63f145ce7523f082e6125/website/views/shared/mixins.jade#L4-L5) and [on this line](https://github.com/HabitRPG/habitrpg/blob/e920734648f60fde77b982aff42c1fc59e51652d/website/views/options/social/group.jade#L3).
