### ISSUE TITLE
On-hover pop-out is out of the screen

### ISSUE THREAD

**Issue by dgodovanets** [HabitRPG/habitica#7799]
General Info
- UUID: 6b4563cf-ef71-4508-839e-f553d358dab9
- Browser: Google Chrome, Version 53.0.2785.8 dev-m
- OS: Windows 7

Screenshot - http://prntscr.com/btwh9w [EDIT by Alys: screenshot is pasted in below]
When I start quest and hover my pointer under the quest scrolls, I can see pop-outs with info about quest, but that window is half out of my screen. You should do pop-out to down.

![image](https://cloud.githubusercontent.com/assets/1495809/16899572/331506b8-4c4c-11e6-9f05-f9dcf11e0917.png)

**Comment by audiolion** [comment]
looks like a case where the translation is longer than expected resulting in the visual bug. The best way to approach this is to use a popout library that looks to determine where is the best place to pop out info if the default (top in this case) is cut off. Not sure what approach Habitrpg would like to take though. I have noticed similar issues with cut off popouts in other areas.

**Comment by Alys** [comment]
This also occurs for the English version.

It's something for us to consider in the upcoming website improvement project, if not sooner. In the project, we should test all hover / pop-out features on all items that occur at the top, bottom, far left, and far right of the respective areas.

**Comment by audiolion** [comment]
one solution is to use a popout library that will dynamically extend left, right, down, or up depending on where it will fit on the screen

**Comment by librarianmage** [comment]
Should this be put on hold for after the client update if it is still applicable?

**Comment by Alys** [comment]
@MathWhiz Great point, thank you!

**Comment by lemoness** [comment]
The quest modal is handled completely differently now, so I am closing this ticket.
