### ISSUE TITLE
Show the current number of tokens

### ISSUE THREAD

**Issue by silverymoon** [HabitRPG/habitica#78]
I haven't died yet, and thus I have no idea about my current number of tokens. Is that somewhere in the UI and I haven't found it yet? I f not, it would be useful to show it...

**Comment by lefnire** [comment]
you won't need them yet, except for reroll (which nobody uses). i'll make them visible once we have purchaseable things

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
If the plan is already to make them visible once there are items for purchase, do we need a trello card for this?

**Comment by StanLindsey** [comment]
@wc8 - I guess not, its a confirm feature to see your tokens, it doesn't really need voting or discussion. (The use of the them can be voted and discussed on the other hand on Trello cards)
