### ISSUE TITLE
How change locale setting ?

### ISSUE THREAD

**Issue by Swizz** [HabitRPG/habitica#780]
Hi,
I want to make a french translation. 
Nevertheless, i did not find the way to change the locales on my own server.
I try to set this for yesterday evening, to check my translation localy.

Thanks for your help.

**Comment by lefnire** [comment]
Translations haven't been implemented yet, check out https://trello.com/card/translations/50e5d3684fe3a7266b0036d6/12 . Let's follow up there or https://github.com/lefnire/habitrpg/issues/62
