### ISSUE TITLE
Party member did not log damage to boss

### ISSUE THREAD

**Issue by gravitonbit** [HabitRPG/habitica#7805]
General Info
- UUID:  5b7a8716-8e74-44c2-ae9e-48feaa05000a
- Browser: Chrome, Firefox.
- OS: Mac
### Description

[//](#):I'm currently a participant and owner of a quest (http://i.imgur.com/l9ITshX.png) everything was working fine but today I logged in Cron and my dailies got updated, but when I log into the party chat there's no message of my attack at all (http://i.imgur.com/ufQgCjx.png). I was not in the Inn at all since streaks were reset as well for items I didn't do yesterday. I've tried refreshing the page, refetch message, click on daily tasks, done some, tried to login in the mobile app, logged in another browser, cleared cache etc. When I logged in a error message showed up but couldn't recall what was it as I immediately closed it.

**Comment by Alys** [comment]
Thanks very much for telling us, and I'm sorry about the trouble! We're recording this in another issue and I've copied details of your report there: https://github.com/HabitRPG/habitrpg/issues/5988#issuecomment-233460142

This is likely to be a once-off or very rare event, so you should be back to normal tomorrow.
