### ISSUE TITLE
Says "Invitations Sent" even if you leave "Email" or "User ID" fields empty

### ISSUE THREAD

**Issue by Ozzystrasza** [HabitRPG/habitica#7807]
General Info
- UUID: 8389891a-ba52-4580-b08b-2cb706c7e0b4
- Browser: Chrome Version 51.0.2704.103 (64-bit)
- OS: Windows 10
### Description

In the "Invite Friends" window of either party or guild, if you leave the fields "Email" or "User ID" empty and click on the "Send Invitations" button, you will receive a notification saying "Invitations Sent".

**Comment by JuliaCBrown** [comment]
I'd be interested in tackling this

**Comment by afilhodaniel** [comment]
@JuliaCBrown you have worked on this issue?

**Comment by JuliaCBrown** [comment]
@afilhodaniel No I've not. If your interested go for it.

**Comment by corinnaj** [comment]
Has anyone worked on this issue yet? If not, I'd be interested in fixing it.

**Comment by JTorr** [comment]
Is anyone working on this issue? I would like to pick it up, and I have a fix ready if no one else is working on this.

**Comment by Alys** [comment]
@corinnaj I'm sorry - we never replied to your question. It looks like no one was working on it before you, but @JTorr is interested now. @corinnaj Have you done any work on it? If so, you'd be welcome to do a pull request. Othe

**Comment by Alys** [comment]
ugh, misclick.

... Otherwise, @JTorr could take it up.

**Comment by corinnaj** [comment]
@JTorr I started to work on it, but if you already have a fix ready, go for it.

**Comment by JTorr** [comment]
@corinnaj Sorry, didn't mean to step on any toes. I saw the "help welcome now" and thought it wasn't being worked on.

**Comment by JTorr** [comment]
@Alys I have a fix for the issue, but there is a failing test, and I'm not sure how it's related. I'll put up the pull request in the hopes that someone can help me out with that.

**Comment by JTorr** [comment]
There was a failing integration test when I ran it locally, but it passed the Travis CI run.

**Comment by JTorr** [comment]
A couple of notes on my pull request:
1) My code leaves the modal window open if no email/UUID is entered. If it would be better to close it and redirect, like with a successful submission, let me know and I can make that change.
2) In Safari, I was unable to see the messages 'Invites Sent', etc. This was true both before and after my code change.
