### ISSUE TITLE
Chilling Frost skill freezes the streaks on challenge Dailies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7809]
Chilling Frost freezes streaks on Challenge Dailies.

<strike>This is consistent with being able to edit the streaks on Dailies (necessary for recovering from unexpected crons), but not consistent with the policy that skills can't be used to affect challenge tasks. Perhaps we didn't change this when API v3 was being built due to just an oversight (I didn't think of it until cTheDragons asked about it). I'm pretty much on the fence about whether it should affect challenge tasks or not - perhaps slightly on the side of not affecting them. What do others think?</strike>

The skill should be changed so that it does NOT freeze the streak for Challenge Dailies.

**Comment by khipkin** [comment]
I agree that it skills should not affect challenge dailies.

**Comment by paglias** [comment]
I think we just forgot to exclude challenge dailies from the skill

**Comment by librarianmage** [comment]
If this should be changed, I can do it!

**Comment by Alys** [comment]
Yes, let's change it. Chilling Frost should NOT freeze the streaks on Dailies.

@MathWhiz Thanks! When this is ready to be merged, I'd appreciate it if you could remind me that the Socialites and Wiki Wizards should be informed about this.

**Comment by khipkin** [comment]
@Alys All dailies or just challenge dailies?

**Comment by MathWhiz** [comment]
Challenge dailies, if I'm not mistaken

**Comment by crookedneighbor** [comment]
Definitely challenge dailies.

**Comment by librarianmage** [comment]
Please remove "in progress" tag, as I am no longer working on this.

**Comment by Alys** [comment]
@MathWhiz Thanks for letting us know!

Labels updated. I've also cleaned up some of the comments and edited the top post a bit to clarify the fix.

**Comment by Lyqst** [comment]
Hi, I'd like to work on this oldie

**Comment by Alys** [comment]
@Lyqst Thank you! I've marked it as in progress for you. Post here if you have questions or run into trouble.
