### ISSUE TITLE
Cannot find module 'ini'

### ISSUE THREAD

**Issue by bussiere** [HabitRPG/habitica#781]
bussiere@ubuntu:~/workspace/todo/habitrpg$ node server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bussiere/workspace/todo/habitrpg/node_modules/nconf/lib/nconf/formats.js:8:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

bussiere@ubuntu:~/workspace/todo/habitrpg$ npm install
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/browserify/1.17.3
npm http GET https://registry.npmjs.org/derby-i18n/0.0.1
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/derby-i18n/0.0.1
npm http 304 https://registry.npmjs.org/browserify/1.17.3
npm http GET https://registry.npmjs.org/buffer-browserify
npm http GET https://registry.npmjs.org/syntax-error
npm http GET https://registry.npmjs.org/console-browserify
npm http GET https://registry.npmjs.org/deputy
npm http GET https://registry.npmjs.org/commondir
npm http GET https://registry.npmjs.org/nub
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/http-browserify
npm http GET https://registry.npmjs.org/vm-browserify
npm http GET https://registry.npmjs.org/crypto-browserify
npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/socket.io/0.9.13
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/es5-shim
npm http GET https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/hooks/0.2.1
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ansi-color
npm http GET https://registry.npmjs.org/cookie/0.0.4
npm http GET https://registry.npmjs.org/racer-util/0.0.2
npm http 200 https://registry.npmjs.org/commondir
npm http 200 https://registry.npmjs.org/buffer-browserify
npm http 200 https://registry.npmjs.org/syntax-error
npm http GET https://registry.npmjs.org/commondir/-/commondir-0.0.1.tgz
npm http GET https://registry.npmjs.org/buffer-browserify/-/buffer-browserify-0.0.5.tgz
npm http GET https://registry.npmjs.org/syntax-error/-/syntax-error-0.0.0.tgz
npm http 200 https://registry.npmjs.org/console-browserify
npm http GET https://registry.npmjs.org/console-browserify/-/console-browserify-0.1.6.tgz
npm http 200 https://registry.npmjs.org/deputy
npm http GET https://registry.npmjs.org/deputy/-/deputy-0.0.4.tgz
npm http 200 https://registry.npmjs.org/nub
npm http GET https://registry.npmjs.org/nub/-/nub-0.0.0.tgz
npm http 200 https://registry.npmjs.org/vm-browserify
npm http GET https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.1.tgz
npm http 200 https://registry.npmjs.org/crypto-browserify
npm http GET https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-0.2.1.tgz
npm http 200 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http 200 https://registry.npmjs.org/http-browserify
npm http GET https://registry.npmjs.org/http-browserify/-/http-browserify-0.1.11.tgz
npm http 200 https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/detective/-/detective-0.2.1.tgz
npm http 200 https://registry.npmjs.org/socket.io/0.9.13
npm http GET https://registry.npmjs.org/socket.io/-/socket.io-0.9.13.tgz
npm http 200 https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/socket.io-client/-/socket.io-client-0.9.11.tgz
npm http 200 https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/node-uuid/-/node-uuid-1.3.3.tgz
npm http 200 https://registry.npmjs.org/hooks/0.2.1
npm http GET https://registry.npmjs.org/hooks/-/hooks-0.2.1.tgz
npm http 200 https://registry.npmjs.org/es5-shim
npm http GET https://registry.npmjs.org/es5-shim/-/es5-shim-2.0.8.tgz
npm http 200 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/debug/-/debug-0.7.2.tgz
npm http 200 https://registry.npmjs.org/cookie/0.0.4
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.0.4.tgz
npm http 200 https://registry.npmjs.org/racer-util/0.0.2
npm http GET https://registry.npmjs.org/racer-util/-/racer-util-0.0.2.tgz
npm http 200 https://registry.npmjs.org/ansi-color
npm http GET https://registry.npmjs.org/ansi-color/-/ansi-color-0.2.1.tgz
npm http 200 https://registry.npmjs.org/commondir/-/commondir-0.0.1.tgz
npm http 200 https://registry.npmjs.org/buffer-browserify/-/buffer-browserify-0.0.5.tgz
npm http 200 https://registry.npmjs.org/syntax-error/-/syntax-error-0.0.0.tgz
npm http 200 https://registry.npmjs.org/console-browserify/-/console-browserify-0.1.6.tgz
npm http 200 https://registry.npmjs.org/deputy/-/deputy-0.0.4.tgz
npm http 200 https://registry.npmjs.org/connect
npm http 200 https://registry.npmjs.org/nub/-/nub-0.0.0.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-2.7.4.tgz
npm http 200 https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.1.tgz
npm http 200 https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-0.2.1.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http 200 https://registry.npmjs.org/uglify-js
npm http 200 https://registry.npmjs.org/http-browserify/-/http-browserify-0.1.11.tgz
npm http GET https://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz
npm http 200 https://registry.npmjs.org/detective/-/detective-0.2.1.tgz
npm http 200 https://registry.npmjs.org/socket.io-client/-/socket.io-client-0.9.11.tgz
npm http 200 https://registry.npmjs.org/socket.io/-/socket.io-0.9.13.tgz
npm http 200 https://registry.npmjs.org/node-uuid/-/node-uuid-1.3.3.tgz
npm http 200 https://registry.npmjs.org/hooks/-/hooks-0.2.1.tgz
npm http 200 https://registry.npmjs.org/es5-shim/-/es5-shim-2.0.8.tgz
npm http 200 https://registry.npmjs.org/debug/-/debug-0.7.2.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.0.4.tgz
npm http 200 https://registry.npmjs.org/racer-util/-/racer-util-0.0.2.tgz
npm http 200 https://registry.npmjs.org/ansi-color/-/ansi-color-0.2.1.tgz
npm http 200 https://registry.npmjs.org/connect/-/connect-2.7.4.tgz
npm http 200 https://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/base64-js/0.0.2
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/concat-stream/0.0.8
npm http 200 https://registry.npmjs.org/base64-js/0.0.2
npm http GET https://registry.npmjs.org/base64-js/-/base64-js-0.0.2.tgz
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 200 https://registry.npmjs.org/concat-stream/0.0.8
npm http GET https://registry.npmjs.org/concat-stream/-/concat-stream-0.0.8.tgz
npm http 200 https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/policyfile/-/policyfile-0.0.4.tgz
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 200 https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/base64id/-/base64id-0.1.0.tgz
npm http 200 https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/redis/-/redis-0.7.3.tgz
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 https://registry.npmjs.org/base64-js/-/base64-js-0.0.2.tgz
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-0.0.1.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.1.1.tgz
npm http 200 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/esprima/-/esprima-0.9.9.tgz
npm http 200 https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/qs/-/qs-0.5.1.tgz
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.22.tgz
npm http 200 https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/formidable/-/formidable-1.0.11.tgz
npm http 200 https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http 200 https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http 200 https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/send/-/send-0.1.0.tgz
npm http 200 https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 200 https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 200 https://registry.npmjs.org/concat-stream/-/concat-stream-0.0.8.tgz
npm http 200 https://registry.npmjs.org/policyfile/-/policyfile-0.0.4.tgz
npm http 200 https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/uglify-js/-/uglify-js-1.2.5.tgz
npm http 200 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/active-x-obfuscator/-/active-x-obfuscator-0.0.1.tgz
npm http 200 https://registry.npmjs.org/base64id/-/base64id-0.1.0.tgz
npm http 200 https://registry.npmjs.org/redis/-/redis-0.7.3.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.4.2.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.1.1.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-0.0.1.tgz
npm http 200 https://registry.npmjs.org/esprima/-/esprima-0.9.9.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.5.1.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.22.tgz
npm http 200 https://registry.npmjs.org/formidable/-/formidable-1.0.11.tgz
npm http 200 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/ws/-/ws-0.4.25.tgz
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http 200 https://registry.npmjs.org/send/-/send-0.1.0.tgz
npm http 200 https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 200 https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 200 https://registry.npmjs.org/uglify-js/-/uglify-js-1.2.5.tgz
npm http 200 https://registry.npmjs.org/active-x-obfuscator/-/active-x-obfuscator-0.0.1.tgz
npm http 200 https://registry.npmjs.org/ws/-/ws-0.4.25.tgz
npm http 200 https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.4.2.tgz
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.0.4.tgz
npm http 200 https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.6.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.0.4.tgz
npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.6.tgz
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http 200 https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz
npm http 200 https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/tinycolor/-/tinycolor-0.0.1.tgz
npm http 200 https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/options/-/options-0.0.3.tgz
npm http 200 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http 200 https://registry.npmjs.org/tinycolor/-/tinycolor-0.0.1.tgz
npm http 200 https://registry.npmjs.org/options/-/options-0.0.3.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-0.6.1.tgz

> ws@0.4.25 install /home/bussiere/workspace/todo/habitrpg/node_modules/racer/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/bussiere/workspace/todo/habitrpg/node_modules/racer/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory`/home/bussiere/workspace/todo/habitrpg/node_modules/racer/node_modules/socket.io-client/node_modules/ws/build'
npm WARN unmet dependency /home/bussiere/workspace/todo/habitrpg/node_modules/nconf requires async@'0.1.x' but will load
npm WARN unmet dependency /home/bussiere/workspace/todo/habitrpg/node_modules/async,
npm WARN unmet dependency which is version 0.2.6
derby-i18n@0.0.1 node_modules/derby-i18n

lodash@1.0.1 node_modules/lodash

moment@2.0.0 node_modules/moment

browserify@1.17.3 node_modules/browserify
├── nub@0.0.0
├── commondir@0.0.1
├── console-browserify@0.1.6
├── vm-browserify@0.0.1
├── crypto-browserify@0.2.1
├── optimist@0.3.7 (wordwrap@0.0.2)
├── buffer-browserify@0.0.5 (base64-js@0.0.2)
├── http-browserify@0.1.11 (concat-stream@0.0.8)
├── deputy@0.0.4 (mkdirp@0.3.5)
├── syntax-error@0.0.0 (esprima@0.9.9)
└── detective@0.2.1 (esprima@0.9.9)

racer@0.3.14 node_modules/racer
├── ansi-color@0.2.1
├── cookie@0.0.4
├── racer-util@0.0.2
├── debug@0.7.2
├── hooks@0.2.1
├── node-uuid@1.3.3
├── es5-shim@2.0.8
├── socket.io@0.9.13 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3)
├── uglify-js@2.2.5 (optimist@0.3.7, source-map@0.1.22)
├── connect@2.7.4 (fresh@0.1.0, pause@0.0.1, cookie-signature@0.0.1, buffer-crc32@0.1.1, bytes@0.2.0, cookie@0.0.5, formidable@1.0.11, qs@0.5.1, send@0.1.0)
└── socket.io-client@0.9.11 (xmlhttprequest@1.4.2, uglify-js@1.2.5, ws@0.4.25, active-x-obfuscator@0.0.1)
bussiere@ubuntu:~/workspace/todo/habitrpg$ ls
CHANGELOG.md  Makefile  README.md            locales     node_modules  public     src     test  views
LICENSE       Procfile  config.json.example  migrations  package.json  server.js  styles  ui
bussiere@ubuntu:~/workspace/todo/habitrpg$ mv config.json.example config.json  
bussiere@ubuntu:~/workspace/todo/habitrpg$ node server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bussiere/workspace/todo/habitrpg/node_modules/nconf/lib/nconf/formats.js:8:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Swizz** [comment]
Try : 'npm install ini'

**Comment by lefnire** [comment]
`node --version` ? Wanna make sure you're on 8.x

**Comment by bussiere** [comment]
i've done npm install ini

i'am on v0.10.3
and now i get :: 
module.js:340
    throw err;
          ^
Error: Cannot find module 'derby-auth/node_modules/nodemailer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at sendEmail (/home/bussiere/workspace/todo/habitrpg/server.js:39:26)
    at process.<anonymous> (/home/bussiere/workspace/todo/habitrpg/server.js:63:5)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)

**Comment by wizonesolutions** [comment]
Looks like you should just do

```
cd <your_clone_path>
rm -rf node_modules
npm install
```

**Comment by lefnire** [comment]
also downgrade to 0.8.x, Derby (and many other node modules) don't work on
0.10.x yet

**Comment by bussiere** [comment]
thanks

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
