### ISSUE TITLE
Delimiters

### ISSUE THREAD

**Issue by artemisclyde** [HabitRPG/habitica#7812]
Hya! So I'm currently trying to give my tasks some kind of order. For example I seperate my habits in 2 sections being 'important' and 'fun'. 'important' contains things such as cleaning my flat, getting my university [stuff] done and further on. 'fun' contains things such as skating for a bit since I want to get back to it or practising guitar. So that works fine for me, but I want to state the following:

I think it would be a good idea to be able to create real delimiters in both habits and dailies. In habits, you can currently create a habit and cross out the positive and the negative button, making it a habbit you can't click. Since this is just a trick and may be fixed at some point, I'd wish for a real delimiter to put inbetween my tasks.

Tell me what you think / if this might be an option in the future :)

![share_temp](https://cloud.githubusercontent.com/assets/16636453/17002331/083ea058-4ecb-11e6-83e7-c9021154f1bb.png)

**Comment by Alys** [comment]
Hi @artemisclyde! I think it's a nice idea and it might be something that could be added in future, but feature requests are best done at Help > Request a Feature from the Habitica website's menu. We use GitHub just for bug reports. I'm closing this now, but if you want to create a feature request, you can include the link to this issue in it.

Also, as a note, I've edited your message here to replace a swear word with "[stuff]". Habitica's [Community Guidelines](https://habitica.com/static/community-guidelines) apply to our GitHub issues as well (and also our Trello board and our wiki), for the comfort of any Habitica players that need to interact with us at those other websites. If you'd like to edit your message to choose a different word, that would be fine!

**Comment by Alys** [comment]
Note that we have no plans to prevent you from turning off both plus and minus buttons on Habits. That's a useful option that's used by many players to display delimiters, notes, quotes, etc, so we recognise it as a feature. :)
