### ISSUE TITLE
Deleting account and signing up back up with same email hangs Habitica

### ISSUE THREAD

**Issue by Lupison** [HabitRPG/habitica#7813]
General Info
- UUID: d1083a06-5e76-4b62-a026-ce050e93125e
- Browser: Chrome (Win), Silk (Kindle)
- OS: Windows 7, Kindle
### Description

[//]: # I deleted my account and signed right back up with the same email/password.  This worked on the computer I was currently working on (Computer A).  However, when I attempted (next day) to access my account through another browser/machine (Computer B and/or Kindle C), Habitica hung.  I could not go to any other page on Habitica, it just hung trying to get to my Tasks. I saw the current Tip and and the spinning load sign.

**Comment by Alys** [comment]
I've responded to this in the Report a Bug guild where you made your first post about it.
