### ISSUE TITLE
Sudden Death

### ISSUE THREAD

**Issue by pocketkey** [HabitRPG/habitica#7815]
### General Info
- UUID: cc3c7720-6887-4bc0-af95-7bcb73839a6c
- Browser: Chrome
- OS: Windows 7 Professional x64
### Description

I woke up this morning and checked Habitica, only to find that I had died somehow over night. I checked my party, thinking the quest may have already started, but it didn't. I checked the chat and no damage was done overnight. All my dailies were finished yesterday and still remain with a streak of 1 or more. Even if I didn't do any of my dailies, it would only cause me 18.8 damage, not a full 50/50. Another thing to note is that I am fairly certain I was at 50 health about 9 hours ago.

**Comment by Alys** [comment]
@pocketkey I'm sorry about this! In case you don't know, you can use [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) to recover from the unfair damage.

Technical details:

We have Amplitude logs that show:
- Jul 21, 2016 5:10:16 am UTC : a "navigate" event, health 49
- an eleven hour gap between sessions
- Jul 21, 2016 4:04:15 pm UTC : a "navigate" event, health 0
- Jul 21, 2016 4:04:16 pm UTC : cron
- Jul 21, 2016 4:04:21 pm UTC : death

From pocketkey's account: `"lastCron": "2016-07-21T16:04:15.488Z"`

The previous cron was at 2016-07-20 07:01:09 UTC. Those two cron's in pocketkey's time zone were at 2016-07-20 00:01:09 and 2016-07-21 09:04:15. CDS is 0.

I've confirmed that all Dailies were completed, all have streaks of 1 or more, and there was no quest damage (the most recent quest damage, according to the party log, was at 2016-07-20 22:29:03 UTC).

I can't see any reason for cron to have caused health to be 0.

**Comment by Alys** [comment]
@pocketkey Did you change parties not too long before the unexpected damage? If so, it was probably this bug: https://github.com/HabitRPG/habitrpg/issues/7653
In brief, you might have still been in a quest in the party you left.

There's no evidence of that now, but if the quest has finished already, I wouldn't expect to see evidence.

If that's what happened, you should be safe from unexpected damage now.

**Comment by pocketkey** [comment]
@Alys Yeah I didn't know you could change the Character Values. :) Thanks. And I did actually switch parties right before it happened. Thank you.
