### ISSUE TITLE
collection quest progress message for zero items should be "... found no [item names]"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7816]
_This is something that was discussed in Aspiring Socialites 45 days ago. The messages are still there if anyone wants to review the conversation (search for "found nothing")._

Currently, for collection quests, on any days when you find no items, the quest progress message is `[person's name] found nothing`

We'd like it changed to `[person's name] found no [item name(s)]` (for example, "Alys found no Moonstones" or "Alys found no Blue Fins and no Fire Coral").

The reasons are:
- It would help when troubleshooting quests (an admin could grep through the party log for "found .. Moonstones" and be sure to find all messages from that quest). 
- It might also help new players understand what's going on; if a quest starts amongst players with low perception, they could easily not find anything for the first couple of messages, and "found no Moonstones" is probably more meaningful than "found nothing" - they will already have seen the term "Moonstones" in the quest description and so will have some idea what it's talking about.

**Comment by JuliaCBrown** [comment]
I would like to tackle this as well if that is alright.

**Comment by Alys** [comment]
@JuliaCBrown Sorry for not replying earlier! If you're still interested, it would be great if you'd work on this! Ask here if you have any questions or run into any trouble.

**Comment by abatula** [comment]
@JuliaCBrown are you still interested in working on this? If not, I can take a shot at it.

**Comment by JuliaCBrown** [comment]
@abatula Go for it. I just started a new job so I have no free time :(

**Comment by abatula** [comment]
Ok, I'll look into this one. Good luck with the new job! I hope you get your free time back soon.
