### ISSUE TITLE
api.amplitude.com bad checksum POST Error

### ISSUE THREAD

**Issue by audiolion** [HabitRPG/habitica#7817]
General Info
- UUID: 236e74bc-986d-41ad-9fa1-d4842ad72334
- Browser: Chrome 51.0.2704.103 (64-bit)
- OS: macOS 10.11.5 (El Capitan)
### Description

On every page load and while a page is left open I am getting console errors related to `bad checksum` responses from a `400 POST` to `api.amplitude.com`.
### Request Headers

```
POST / HTTP/1.1
Host: api.amplitude.com
Connection: keep-alive
Content-Length: 117781
Cache-Control: max-age=0
Origin: https://habitica.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: */*
Referer: https://habitica.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
```
### Response Headers

```
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=UTF-8
Date: Fri, 22 Jul 2016 03:24:48 GMT
Server: TornadoServer/3.2.2
Content-Length: 12
Connection: keep-alive
```
### Response

```
bad checksum
```
### Request Form Data

[lpaste of json](http://lpaste.net/5426471593998024704)
Some notes, there is a huge amount of repeated data, though it seems each repeat corresponds to separate XHR requests made on the page, it is just a lot of the requests return the same data?

Another note is the end of the paste [line #4441](http://lpaste.net/5426471593998024704#line4441) which provides the checksum used
#### Console Errors

![Console Errors](http://imgur.com/PJRe7HB.jpg)

Specifically the red errors.
#### Unrelated

Are we aware of the moment.zone() deprecation and the delivering of non-https static content on https connections?

**Comment by khipkin** [comment]
Re your unrelated section: yes and yes. :+1:

**Comment by audiolion** [comment]
hey we both go to RIT 😃

**Comment by khipkin** [comment]
@audiolion whaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaat

**Comment by Alys** [comment]
I haven't seen this reported for a long time so I'm closing this.
