### ISSUE TITLE
Drop Frequency

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#782]
We've been debating back and forth about the drop frequency, so I figured I would post it here and start getting some outside feedback.

Personally, despite knocking off tons of tasks each day, many of them orange and even a few red, I haven't gotten a single drop since we implemented the system, so I am inclined to think that we should adjust things. Other people have gotten drops, and like the system as-is.

Here are some of the current ideas being thrown around!
1. When rewards and streaks are implemented, drops will be incorporated into that. 
   PRO: Will be easy to incorporate into that system, and will be a good motivator for people to have streaks.
   CON: That system is quite some time away. We need a stop-gap. We've made it so that drop chance never goes below 1% even for blues and greens, but I think we need more (I may be wrong)!
2. Increase the percentages of eggs being dropped, but not the percentages of potions! Makes the stochastic method more effective, since people will actually be seeing drops (which not everyone is yet), but it won't render the tokens completely irrelevant because you still need a hatching potion to hatch the egg
   PROS:
   a) be more fun, because people are getting more stuff,
   b) be more motivating, because people will get an egg and want to complete more of their tasks to find a hatching potion to hatch it,
   c) generate more revenue, because people will want to buy hatching potions to hatch all the eggs that they are getting!
   CONS: 
   a) the number of pop-up windows could get overwhelming in the future once things like quests are added
   b) people who don't want to buy potions and aren't getting them in drops might get annoyed by egg build-up
3. Make an egg drop automatically at certain levels - there is already a guaranteed egg drop at level 4, so maybe add one at level 10, 20, 30, etc.
   (IMPORTANT SIDE NOTE: All users who were already above level four should have gotten an automatic egg drop when the drop system was implemented, but this may not have happened. I did not get an egg. Did anyone else?)
   PROS:
   Same as #2, although to a lesser extent, therefore not as overwhelming.
   CONS: 
   a) Is this enough?
   b) Is tying egg drop to level problematic for the system?

Personally, I am in favor of option 3. What does everyone else think? How has the drop system been working for you guys?

And did everyone who was already over level four get an automatic egg when the system was implemented?

**Comment by lefnire** [comment]
very good. I linked this ticket from http://community.habitrpg.com/node/99

**Comment by JellyBean22** [comment]
I agree, especially with 3.
Also, as mentioned, I am above level 4 too but have yet to get an egg drop (have gotten five potions though)

**Comment by wildcate** [comment]
I've had an egg drop (though not the automatic first one on implementation) and two base potions, despite doing quite a bunch of tasks including some very, very red ones. It's a tricky question really - and like so many things in Habit, it will never be deemed fair all across the board.

I think tying an automatic egg drop (or maybe an automatic potion drop) to certain levels would even out things a little - when one knows that there will be an egg at level 20, missing out on the chance drops is not so bad. For me, it does act as some extra motivation that there might be an egg - yes, I could just buy one, but I sort of like the drops better. Also tying them to streaks might be a good thing once they are implemented.

Nr. 2 is, I think, the suggestion most apt to build frustration, so I would not like to see that one implemented.

**Comment by lemoness** [comment]
So far it seems like
1. Having eggs at set levels seems popular! What levels would those be?
2. The automatic egg drop for people over level 4 did not work.
3. Tying drops to streaks and rewards should definitely happen.... in the
   future.

I'm still not sure that the percentage isn't too small.... 1% as a base is
just really, really low.

**Comment by wildcate** [comment]
Regarding the set levels... probably not too many, so it still is an incentive. Maybe every 7 levels? Starting with lv 4 - so 4, 11, 18, ... and so on. (Am I the only one who feels that leveling up is still really easy, btw?)

And yes, 1% as a base is very low, but the question is how much the base increases for red tasks and really red tasks. If for a longtime list lounger task it would increase to up to 20%, that's much different from going up to, say, 2 or 3%. We don't want loads of egg drops from normal tasks, especially if someone works off about 20 "fresh" ones a day, but increasing the chance significantly for really old items might add extra incentive to get them done as well.

**Comment by lemoness** [comment]
Hm. Maybe every 8 levels (since it starts at 4, and 8 is a multiple)?
So level 4, 12, 20, 28...
I also feel like I level up very quickly, but I think it's because I have
the lv 6 sword.

Apparently the highest it can get is 25%, so that's pretty high. I don't
know. I just still haven't gotten a single drop despite doing a bunch of
yellow, orange, and red activities everyday, but I seem to be the only
person.

**Comment by Shaners** [comment]
I'd just keep it to levels 10, 15, 20, 25, 30 or 10, 20, 30, 40 to simplify things unless you wanted to semi obscure which I don't see much of a point to doing.

**Comment by lemoness** [comment]
I guess it might keep people a little more on their toes if it's not a
round number? I kind of like the fact that it lends significance to
normally insignificant levels. Plus that leaves the nice round levels free
for enabling other features.

But 10, 20, 30 etc is okay with me, as well! It all depends on how everyone
else feels.

**Comment by wildcate** [comment]
That was one of the reasons I suggested the "weird" numbers. It wouldn't even need to be evenly spaced, there could be drops after 6 levels, then after 8, then after 7... I think it would be more of a surprise that way, thus also keeping folks motivated. Semi-obscure is nice! (I think so, at least.)

**Comment by kriscrat** [comment]
Yes, I agree.  Semi random is super motivating, even if it's not truly random, it will feel like it to many users. Maybe spread them out a bit more as the levels get higher. 

From my Android phone on T-Mobile. The first nationwide 4G network.

-------- Original message --------

**Comment by lefnire** [comment]
We definitely want random, if only perceived. The point of drops is
stochastic rewards. What say we to upping the % as a stopgap? 5?

**Comment by lemoness** [comment]
Let's give it a try for a week, and see how it works. If we find it's
overwhelming, it's easy to scale it back!

**Comment by lefnire** [comment]
Bailey just mentioned she actually had some eggs in her inventory, just wasn't notified of the drop. Will investigate

**Comment by Mihakuu** [comment]
Not eggs. potions. with no notification, I only found them because I was checking out the menus.

**Comment by lemoness** [comment]
None in my inventory except the ones I bought with tokens :/

**Comment by wildcate** [comment]
None here, either.

**Comment by Mihakuu** [comment]
What I think I've experienced is that whenever I do get a drop the site is shocked that it actually happened that it crashes before the pop up loads and after refresh the item is already in my inventory so it doesn't find the need to inform me.

**Comment by lemoness** [comment]
(_laughing quietly_)

**Comment by lemoness** [comment]
GOT MY FIRST DROP! Very exciting :D

**Comment by wizonesolutions** [comment]
Drop the presses!

**Comment by lemoness** [comment]
;p

**Comment by AdrienLemaire** [comment]
I know the thread is old, but it's still open :)

It seems that recently only 1 drop can occur per day.  Any reason why ? I knock off between 15 and 20 tasks a day, but I only got 1 potion per day over the last week (the eternal base/white/desert)

![eggs](http://i.imgur.com/VfUYmIl.png)

A bit frustrating :)

**Comment by lefnire** [comment]
May frustration beget action, [thusly is open source](https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L123). In the mean time, I'll take a peak when I can

**Comment by AdrienLemaire** [comment]
oh ok, limit should be 2. Maybe I just got unlucky then :)

**Comment by Shaners** [comment]
This can probably be closed as well.
