### ISSUE TITLE
Unsaved tags appear in list of tags to apply and can't be moved without reload

### ISSUE THREAD

**Issue by zmbc** [HabitRPG/habitica#7820]
General Info
- UUID: d814e580-fa5c-49e3-a40e-edc225329740
- Browser: Chrome 51
- OS: Windows 7
### Description

When I'm editing tags and create a new one and haven't saved it yet, it already appears in the list of tags to apply to a To-Do. When I select this option,  I get this error:

"tagId" must be a valid UUID corresponding to a tag belonging to the user.

As I understand it, the problem here is that the tag should not be appearing as an option until it has been saved.
#### Console Errors

https://habitica.com/api/v3/tasks/8ec9bc5d-a0ea-41d0-9c63-bd2c69efa0e9/tags/4bb3dc20-e43c-4c3d-9463-8e036d78915a?userV=1583 Failed to load resource: the server responded with a status of 400 (Bad Request)

---

**edit by Alys:**

The fix for this should also fix https://github.com/HabitRPG/habitrpg/issues/7806 or if that's not possible, https://github.com/HabitRPG/habitrpg/issues/7806 should be reopened.

**Comment by Alys** [comment]
The "save" button in the tags section is badly named. A new tag is saved to your account as soon as you click the "add" button after typing its name. The "save" button just closes the tag editing screen. You'll notice that the error message you describe occurs even after clicking the save button.

However as soon as something causes a sync (e.g., saving some other change to a task or manually clicking the sync button), you can use the new tag. I'd guess that the bug happens because the website hasn't yet fully caught up to the fact that there's a new tag.

A similar problem occurs if you try to change the position of a new tag, after you've added and "saved" but before you've synced.

We should probably make the "save" button do a sync.

**Comment by zmbc** [comment]
That makes sense, and perfectly explains the behavior I was seeing. Given that the "Save" button is more of a "get me out of edit mode" button, wouldn't it make more sense if the "add" button initiated a sync? Otherwise the issue will still exist while remaining in edit mode.

I'm a little busy at the moment, but I may take a stab at a pull request for this if I get around to it.

**Comment by Alys** [comment]
Fair point! Note though I was just guessing, so it might turn out to be something else. You're welcome to work on it if you wish!

**Comment by khipkin** [comment]
It's super misleading that things get saved before you finish (and confirm) creation.  Saving tags/tasks/todos feels like it should be a confirmation that you want the changes you made to stick around.  Having them stick around before that confirmation is awkward.  And when you create tasks/todos with the setting to show options, a sync will save and close the new task/todo when you've barely started making it, which is annoying.

**Comment by Alys** [comment]
Saving of tasts is out of scope for this issue (there's another issue for
tasks auto-closing, and most changes to tasks are only saved manually).
Editing tags is a simple thing, with mistakes being easy to correct, so I
don't think it matters that auto-saving happens.

**Comment by Alys** [comment]
Note also this related problem:  "When trying to move a new tag directly after creating and saving it, I get the error message "No tag item was found with given id." Once I've reloaded the page in my browser, everything works fine again." https://github.com/HabitRPG/habitrpg/issues/7614

**Comment by ashes999** [comment]
+1 I ran into this today, good to see it's already on GitHub

**Comment by JSchneidler** [comment]
I'll try this if nobody else is currently on it.

**Comment by Alys** [comment]
@JSchneidler Thanks, please do!

**Comment by zmbc** [comment]
Thanks @JSchneidler!

**Comment by Alys** [comment]
I've added this to the top post:

The fix for this should also fix #7806 or if that's not possible, #7806 should be reopened.

**Comment by HiccupinGminor** [comment]
Has this been solved? Unfortunately I'm still getting the 

> "tagId" must be a valid UUID corresponding to a tag belonging to the user.

error popup when I try to apply a new tag that I've created (and saved) to anything. A full refresh before applying works fine.

 I'm happy to try to investigate and fix myself if no one else is looking into this.

**Comment by Alys** [comment]
@JSchneidler How are you going with this? Would you like to keep working on it? If you have other commitments that are taking up your time, we completely understand, and @HiccupinGminor could take it over.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this issue might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Tags now behave differently, so I am closing this ticket. However, if something similar happens again, we should open a new ticket to examine the new code.
