### ISSUE TITLE
New Party Loading Text

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7825]
It would be fun to have the text that displays when you are loading a party be more flavorful.

Possible text:

"Your party is being summoned. Please wait..."

Open to other ideas! Maybe we could even have a couple different ones?

**Comment by audiolion** [comment]
Are you saying instead of this message?

![party loading message](http://imgur.com/RVcQSas.jpg)

If so, that seems fine

**Comment by lemoness** [comment]
Yes!

**Comment by citrusella** [comment]
Can ones be suggested here? I have ideas. XD

**Comment by audiolion** [comment]
@citrusella absolutely please offer suggestions 😄

**Comment by citrusella** [comment]
_flakes out_

Ideas (all with the followup of "please wait..."):
- "Your party is coming in from battle."
- "Your party is gathering."
- "Your party is materializing."
- "Your party is searching for scrolls."

I'm not sure these are all great, and there's one on the tip of my tongue that I just can't come up with, but maybe you'll think these are good (or they'll spawn other ideas...

**Comment by ghost** [comment]
Suggestion: can we have several strings like in case of loading screen hints?

**Comment by khipkin** [comment]
I love this entire thread! :grinning: Another idea: "Your party is counting their loot!"

**Comment by khipkin** [comment]
Also, I would like to work on this.

**Comment by Alys** [comment]
A Tavern comment from Over WHAT hill?  :)

**Apropos of nothing, I'm enjoying seeing the different messages that sometimes replace "Your party is loading!" "Coming in from battle" is very good, but I think I like "materializing" even better! Whoever thought of this: great idea!.**
