### ISSUE TITLE
update blog links on habitica.com footer and front page header; add new Developer link to footer

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7826]
Currently on the habitica.com's footer, there's a link to "Blog" for http://blog.habitrpg.com/
and there's another link to it on the header navigation bar at https://habitica.com/static/front

Both those links should be changed so that the text is "Tumblr".

A new link should be added just before both of them, called "Blog" with the URL https://habitica.wordpress.com/

Also, in the footer, under the "Developer" header, add a link to http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths with the text "Guidance for Blacksmiths".

**Comment by audiolion** [comment]
Accidentally made my first PR with the changes I had in my other branch, whoops!
