### ISSUE TITLE
Tried to sign up, e-mail simultaneously already taken yet not registered?

### ISSUE THREAD

**Issue by Jcatgrl** [HabitRPG/habitica#783]
I tried to sign up, but when I put in my usual username for sign-ups (the same my username here) and my e-mail, it told me that the username and e-mail were already taken. Unfazed, I tried to sign in, figuring that I had made an account and forgotten about it (after all, it's happened before). It then told me that there was no user with that username. Now I'm getting a little worried, so I click "forgot password" and enter my e-mail. That's when it tells me that it's not a registered e-mail. Anybody else getting these kinds of contradictions?

**Comment by lefnire** [comment]
see https://github.com/lefnire/habitrpg/issues/669 - try again in a bit, if still an issue i'll restart the server. the issue is #165

**Comment by Jcatgrl** [comment]
Okay, thanks.
