### ISSUE TITLE
Consider using a different CA, e.g. Let's Encrypt, instead of Comodo.

### ISSUE THREAD

**Issue by gregory-marton** [HabitRPG/habitica#7830]
Habitica's https certificate is signed by Comodo group, which has a problematic history:
https://en.wikipedia.org/wiki/Comodo_Group

It's easy and free to use Let's Encrypt instead (or one of many other more honest providers):
https://letsencrypt.org/

Most users would not notice the change (which is actually part of the problem... :-p ).

Please consider doing so? I would love to not need to trust Comodo anymore.

**Comment by paglias** [comment]
A blog post by someone who setup Let's Encrypt on Elastic Beanstalk https://go-to-hellman.blogspot.com/2015/11/using-lets-encrypt-to-secure-elastic.html

**Comment by librarianmage** [comment]
Would a blacksmith be able to change this?

**Comment by Alys** [comment]
@MathWhiz  Good question to ask!

No, this is something for admins to do. It would require changing Habitica's server certificate.

**Comment by TheHollidayInn** [comment]
@SabreCat are and will discuss this further offline since it deals with devops and not the code base. My experience with Let's Encrypt has been great so far and we will probably move in that direction.
