### ISSUE TITLE
UUID: f0e222a3-02f7-447e-934d-b4b26164ac66, can't participate in quests

### ISSUE THREAD

**Issue by weehobbit4** [HabitRPG/habitica#7831]
General Info
- UUID: f0e222a3-02f7-447e-934d-b4b26164ac66,
- Browser:  Chrome & Firefox
- OS: 
### Description

I am not able to participate in any quests. I am added to them via my party, but none of my actions seem to effect anything and I don't receive any rewards once the quest is complete. Please help!

**Comment by audiolion** [comment]
hey, to not muddle up our github issue tracker with what might be non-code related bugs we ask that you post in the ["Report a Bug"](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac) guild first, if we can't help you from there we will ask you to create a ticket here.

Thanks!

**Comment by Alys** [comment]
@weehobbit4 It's possible that the quest owner started the quest before you were able to accept the invitation. Alternatively, if you were resting in the inn, you wouldn't make any progress on the quest.

There's no quest running now in your party so I can't investigate immediately but I can if necessary if this happens again.

The next time a quest invitation appears, click the "accept" button as soon as you see it. Then go to the Social > Party page on the website and look in the list of participants - it should say that you have accepted. If you did click "accept" but don't appear as an accepted participant, go to Help > Report a Bug from the website's menu and describe the problem there.

If you are listed as a participant and the quest starts, make sure you're not resting in the inn. (Unless of course you aren't able to do most of your Dailies! Then resting is good.) Each morning, when you use Habitica for the first time that day, go to Social > Party and click the "fetch recent messages" button, then look for a message about your progress on the quest. If you don't see one, report it at Help > Report a Bug.

If you would like more information about quests, you can read about them on the wiki at http://habitica.wikia.com/wiki/Quests
If you have any questions, go to Help > Ask a Question from the website's menu.
