### ISSUE TITLE
No clickable link to old-news static page

### ISSUE THREAD

**Issue by Hus274** [HabitRPG/habitica#7832]
### Description

I was looking to open the old news (https://habitica.com/static/old-news) link to see the update that I accidentally clicked through here and had a hard time getting to the old-news page on the static website. From what I could see, neither the static website nor the links below include one to the old news page. Would this be something worth changing? I think it would make sense to add a link to the bottom of a users habitica page to access the old news, maybe under the Blog link in the company section at the bottom of the page?

Having a link on the static website to access the page would make sense I think too.

**Comment by khipkin** [comment]
If you go to Settings->Site, there's a "Show Bailey" button that lets you view the recent news again, but I can't find any other links to Bailey, old or new.  I agree that adding at least one link to the static page would be useful.

**Comment by Alys** [comment]
When I do "show Bailey" and then click on Bailey, the window that opens has a link to old news at the bottom. Is that not there for you?

**Comment by Alys** [comment]
But despite that, a link to news on the site might be nice.

**Comment by Hus274** [comment]
It is, I just didn't know that that existed until khipkin posted above.

**Comment by ESWAT** [comment]
One solution would be to put a link in the Settings dropdown. See the bottom of this screenshot:

![screen shot 2016-08-04 at 18 30 51](https://cloud.githubusercontent.com/assets/65468/17420585/a83dcbf4-5a71-11e6-823a-dd4b23cc835d.png)

If someone wants to confirm that this would be a good solution to merge in, I can add this and link it to https://habitica.com/static/old-news

**Comment by khipkin** [comment]
@ESWAT Hmm I think maybe that dropdown is already super long as-is.  But I'm not sure where else to put it... Maybe next to / instead of the "Show Bailey" button?

**Comment by Hus274** [comment]
Why not put it in the footer where we have all the other links? That was the first place I went to look for it as a user.

**Comment by paglias** [comment]
Yeah I think the footer is the best place for it. Feel free to make a PR

**Comment by librarianmage** [comment]
Is anyone working on this? If not, I can do it.

**Comment by paglias** [comment]
@MathWhiz feel free to do it! thank you!
