### ISSUE TITLE
Nothing but blank page in Opera for Android

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7834]
Sorry, didn't have a chance to investigate it, but when I tried to open Habitica in Opera for Android some minutes ago, there was absolutely nothing - just blank space, no window title, no error message - which didn't feel right.

I've experienced this on two different devices, one of which had never been used to open  the site before.

Added: Oh, forgot to mention, that now it's OK, so the issue is only a feedback about something that has been solved already - just in case you may need the info

**Comment by GitHubSphinx** [comment]
Oh, forgot to mention, that now it's OK, so the issue is only a feedback about something that has been solved already - just in case you may need the info

**Comment by crookedneighbor** [comment]
There was a problem with the deploy. Good now. Thanks for letting us know.

**Comment by crookedneighbor** [comment]
Here's the technical details of what happened: http://devs.habitica.com/outage-july-26-2016-post-mortem/

**Comment by ghost** [comment]
@crookedneighbor thanks for the details!

Psst I don't think you've actually wanted to link http://devs.habitica.com/outage-july-26-2016-post-mortem/babeljs.io/ in the blog post :-)

**Comment by crookedneighbor** [comment]
Thanks for catching that! Updated.
