### ISSUE TITLE
Pets grown into Mounts but still display as Pets

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7836]
Hi! This is about a few of my pets that have grown into mounts. They display on the 'Mounts' page, but they are still displaying as pets (as in not faded out) on the "Pets" page. Eg I have a White Bear Cub showing but I also have a White Bear mount and I can click on both to be displayed as my pet + mount. I definitely have not hatched a new White Bear Cub, and I've logged in and out, cleared my cache, etc. Same thing happening for my Skeleton Wolf and Desert Panda. Wondering if this will have an effect when I do want to hatch new pets - I'm working towards the Triad Bingo badge!

FYI the rest of my pets and mounts are fine, just these few.

This be my user ID: 468ccaf8-a6ea-4c89-a419-24559520b8f3
I've recently upgraded my system from Windows 7 to Windows 10, using Chrome on both. I also use the mobile app on Android (Nexus 5x). The same issue happens across all of my browsers and devices, even before and after I upgraded my desktop OS.

**Comment by paglias** [comment]
@thealia sorry for the delay, is this an issue or it solved itself after some time?

**Comment by ghost** [comment]
@paglias I ended up hatching new pets to "rewrite" the ones that I mentioned, so I legit have those pets now. Still don't know what I did to make it buggy the first time, but all's cool, thanks :)
