### ISSUE TITLE
APIDoc value types should be capitalized

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7837]
Many of the params in the APIDoc comments show types with all lowercase letters, like `{string}`, when they should be `{String}`. `{uuid}` should be stylized as `{UUID}`.

**Comment by audiolion** [comment]
ill tentatively say I will do this unless someone else who wants to help contribute for the first time posts here requesting to do it.

**Comment by crookedneighbor** [comment]
It can also be done a little at a time, so if you want to claim a particular file, go for it.

**Comment by paglias** [comment]
Hmm honestly I think I prefer everything lowercase

Il 27 lug 2016 7:19 PM, "Blade Barringer" notifications@github.com ha
scritto:

**Comment by audiolion** [comment]
@paglias If we want to be consistent and clear that we are returning native Javascript objects we should follow how [types are defined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#Fundamental_objects) in js which have the first letter capitalized for native object types.

**Comment by paglias** [comment]
Well, we're returning JSON which is a text format not executable code

**Comment by audiolion** [comment]
so why not label everything JSON or string?

I think it comes down to, do we want to label it as what `typeof json.key` would return or what the native constructor is

**Comment by crookedneighbor** [comment]
APIDoc uses capitalized versions and I think we should match that. Even though it's JSON that's coming back, we're still getting Strings, Booleans, Numbers, etc. They're not all Strings. 

If you feel strongly about the lowercase version, that's fine, but then they should _all_ be lowercase.

**Comment by audiolion** [comment]
yeah I will convert either way, I guess the issue is we dont have a standard right now with the mixing of upper and lower, [apidoc apiParam](http://apidocjs.com/#param-api-param) is capitalized in their docs

**Comment by paglias** [comment]
I just think that keeping everything lowercase will make maintenance easier
and is less error prone. But if you prefer to have the uppercase first
letter I'm okay with that

Il 27 lug 2016 10:45 PM, "Ryan Castner" notifications@github.com ha
scritto:
