### ISSUE TITLE
Disappearing gems

### ISSUE THREAD

**Issue by pqhunter** [HabitRPG/habitica#7841]
General Info
- UUID: 0298735e-b2e1-4720-a605-4f4a00c70338
- Browser: Chrome
- OS: Andorid 
### Description

I just rebirthed (lvl 120). Before my rebirth I had 17 gems but now I only have 9. I  think the system still charged me for the 8 gems that it takes for anyone between levels 50 and 99 to rebirth, even though I was level 120 at the time.  I would really like my gems back. Thanks for the help.

**Comment by Alys** [comment]
Sorry about the delay on this! I've given you 8 gems.

Our Amplitude data shows that the Orb of Rebirth was used once for free on Jul 28, 2016 2:38:53 am UTC and a second time for 8 gems on Jul 28, 2016 2:38:59 am UTC. Your level was listed as 120 both times.

I don't yet know what caused that.

**Comment by SiGhTfOrbACQ** [comment]
I have had the same issue happen twice now to me - I can't quite figure it out. It seems to happen when I level up. I definately charges you, and you get the gems. But upon leveling up - the gems I purchase disappear. Is there logs to see what happened?

I am level 33; and I don't know about the rebirth thing yet.

**Comment by Alys** [comment]
The website's code has been changed since this was logged so the code for Rebirth is different now and I'm closing this.
