### ISSUE TITLE
Seasonal Shop shouldn't display "broken" equipment

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7843]
General Info
- UUID: 7f14ed62-5408-4e1b-be83-ada62d504931
- Browser: Vivaldi
- OS: Windows 10
### Description

When you purchase a gear item from the Seasonal Shop, it disappears. If you lose a current Seasonal Shop gear item to zeroing out your Health or to using the Orb of Rebirth, though, the item then appears on the page, faded out. You can click it, and be informed that you already own the item and need to buy it with Gold instead of Gems.

This is confusing. If you can't buy a thing from the Shop, it shouldn't show up on the page at all.

Some things to keep in mind while fixing this:
- Currently we have a banner that displays in the event that you've used an Orb of Rebirth, which explains how to get those items back. That may need to be modified to show up if you have any "broken" Seasonal Shop items, even if you don't have any Rebirth achievements.
- This is a separate concern from the possibility of not removing these items during a Rebirth at all. That can be changed, and this fixed, independently.
#### Console Errors

None

**Comment by Hus274** [comment]
I can look into this

**Comment by Hus274** [comment]
Ok this should be the last one then: #7852 

Let me know if there's anything else that should be done here to finish this one out!
