### ISSUE TITLE
Habits with large history cause "Request entity too large" errors

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7846]
A Habit that's used very frequently develops a large history and can cause "Request entity too large" errors when the player tries to keep using the task.

We found one such task today with about 700 entries for this month and 1600 for the previous month (before that preening had been happening). There were about 2440 history entries in all.

The error stopped happening when I set the history to an empty array (with the player's permission).

We could do special preening for huge history entries, although that's problematic since we promise that history will be kept for a certain time.

Might not be a priority since it might not happen often. This is the first time I've seen it.

**Comment by Alys** [comment]
We could also perhaps adjust the API to send back fewer/no history entries when the plus/minus buttons are clicked. @crookedneighbor commented in the Bug guild:

"My guess is that if it's very old, we're probably sending back the entire history of the task in the update call (even though it has no effect on the update)"

**Comment by crookedneighbor** [comment]
We just need to adjust the client side update method to not send the history as part of the update call. Same thing was happening when editing groups because we were sending the chat array as part of the update.

**Comment by paglias** [comment]
PRs are welcome. When someone works on this they should also check that all the fields sent to the server are actually useful

**Comment by rbreu** [comment]
I'm looking into this. I can reproduce the error with 2600 history entries.
