### ISSUE TITLE
Update email route should check that proposed email is not already being used

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7847]
https://github.com/HabitRPG/habitrpg/blob/7c579bf850402ac43c146002e475b9baac4f66a2/website/server/controllers/api-v3/auth.js#L521-L543

There's a unique index on that field, so it's causing a 500 when the route is hit with an email that already exists in the system.

**Comment by cching0L2** [comment]
If nobody is working on this ticket, I would like to take a look

**Comment by paglias** [comment]
@cching0L2 feel free to go ahead and do it!
