### ISSUE TITLE
purchasing armor

### ISSUE THREAD

**Issue by Amyndrael** [HabitRPG/habitica#785]
Hi,

I purchased leather armor for 30g, closed the window, and reopened it. the money was gone, and I had no armor.

**Comment by lefnire** [comment]
let's follow up here: https://github.com/lefnire/habitrpg/issues/233

**Comment by Amyndrael** [comment]
thanks. the restore function worked for me.

~Jacob Done
JD Candidate - Class of 2014
ASU Sandra Day O'Connor College of Law
jacob.done@asu.edu

"Tantum Eruditi Sunt Liberi" - Epictetus
