### ISSUE TITLE
[API] POST with Content-Length redirect to /500.html

### ISSUE THREAD

**Issue by lexa** [HabitRPG/habitica#786]
This issue appear when using POST message to update task. If request header contain "Content-Length" field then response is redirect to /500.html page, but not return proper json answer. 

Example using curl:

```
curl -X POST  -H "Content-Type:application/json" \
-H "Content-Length: 0" \
-H 'x-api-user: {user-key}' \
-H 'x-api-key: {api-key}' 
https://habitrpg.com/api/v1/user/task/productivity/up 
```

I belive that denotation length of request should not affect API behaviour.

**Comment by wizonesolutions** [comment]
You don't need `Content-Length`. Make sure you use `--compressed` in your `curl` invocation though.

**Comment by wizonesolutions** [comment]
Actually, you've tried using the plugin API with the full API syntax.

From the wiki: `curl -X POST -H "Content-Type:application/json" -d '{"apiToken":"{TOKEN}"}' localhost:3000/v1/users/{UID}/tasks/productivity/up`

Not headers — you pass it in the data.

**Comment by lexa** [comment]
The library which i use for http request always adds "Content-length" header in any post request, this does not turn off, and i can't switch to another library. Moreover i belive that adding "Content-length:0" should not affect http server behavior. 

I don't understand what do you mean by "Actually, you've tried using the plugin API with the full API syntax." . In my example uses full API with one additional header. I'm not mixing full API and Extension API.

**Comment by wizonesolutions** [comment]
Yeah, you're right. Probably the only thing you are missing is `--compressed`. It really will fail without that.

**Comment by switz** [comment]
I'll take a look into this. It has nothing to do with `--compressed` (well, you do need it, but that's not why it's failing here).

**Comment by wizonesolutions** [comment]
lexa: Try changing it to `Accept: application/json` instead of
`Content-Type` (or sending that as well). That helped me with a `DELETE`
error I was getting. @arscan have you gotten weird 500s?

**Comment by arscan** [comment]
Since you aren't posting any content in the body, you probably should remove the Content-Type header.  When I have that header, I get this error on my locally running server:

```
Error: invalid json, empty body
    at Object.exports.error (/home/rob/Projects/habitrpg/node_modules/express/node_modules/connect/lib/utils.js:55:13)
    at IncomingMessage.module.exports (/home/rob/Projects/habitrpg/node_modules/express/node_modules/connect/lib/middleware/json.js:71:29)
    at IncomingMessage.EventEmitter.emit (events.js:93:17)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socket.ondata (http.js:1786:22)
    at TCP.onread (net.js:404:27)
```

When I removed it, it seemed to work just fine.

**Comment by arscan** [comment]
Seems like the appropriate way to handle this in connect is actively being discussed: https://github.com/senchalabs/connect/issues/415

Regardless, if you are not sending anything in the body, I think the best course of action is to remove that Content-Type header, as that's a lie ;-)

**Comment by arscan** [comment]
...or if its easier, just put in "{}" in the body, as that's valid json (which will change the content-length, of course).

**Comment by paglias** [comment]
This doesn't seem to be an HabitRPG problem and it's well discussed in the post linked by @arscan
