### ISSUE TITLE
Fix super long error output when test fails in Travis build

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#7861]
I'm not sure why, but lately my builds have been throwing the same error over and over again, sometimes running for more than 45 minutes.

For example, [this build](https://travis-ci.org/HabitRPG/habitrpg/builds/147853560) only stopped because the output file exceeded the limit of 4MB, with over 80k lines of output.  And this only happened after more than 48 minutes.

It's just this failure over and over again:

> 'build:dev' errored after 28 s
> Error in plugin 'run-sequence(test:karma)'
> Message:
>     Command failed: /bin/sh -c NODE_ENV=test  npm run test:karma

I think we should limit the number of retries for running karma tests to prevent this from happening again and hogging TravisCI resources.

**Comment by crookedneighbor** [comment]
I don't think this is a problem with Karma. Pretty sure that the same crazy output will happen when _any_ of the test suites fail. 

Changing title to "Fix crazy long error output when test fails in Travis build"

**Comment by crookedneighbor** [comment]
My hunch is the problem is in gulp.

**Comment by paglias** [comment]
When running some tests as standalone commands like `gulp test:api-v3:integration` there's no super long output... it's one more clue the problem is with gulp

**Comment by SabreCat** [comment]
I still see overlong output even when running individual tests that fail. Not _as_ long as otherwise, but still enough to scroll the actual failing tests out of buffer in my terminal session. I've been resorting to running tests with `| tee testlog.txt` and paging through that output to find what actually went wrong.

**Comment by khipkin** [comment]
The actual error in my super-long output from above was a simple syntax error, followed by many karma retries.  I've had similar super-long TravisCI runs since then for various root causes, all with endless retries of karma.

Shouldn't the build skip all remaining checks once one fails?  Why is it still trying after errors are detected?

**Comment by crookedneighbor** [comment]
It is not by design.

**Comment by crookedneighbor** [comment]
Oooh! I think this happens when the server crashes.

**Comment by khipkin** [comment]
Ohhhh good idea!!!

**Comment by SabreCat** [comment]
Would an ordinary test assertion failure crash the server? Because I get the zillion-line spew even when the site itself runs fine, if there's a failing test.

**Comment by librarianmage** [comment]
None of my tests seem to crash the server, but a few of them have run over an hour, and only the top 5% is useful information

**Comment by paglias** [comment]
Bumped priority to medium

**Comment by khipkin** [comment]
It seems like whenever a test fails, that test's test suite gets rerun recursively forever.

[this build](https://travis-ci.org/HabitRPG/habitrpg/builds/156625146): **(49 min 5 sec)**
-  after the test suite with the failed test:
  -  `npm ERR! Failed at the habitica@3.35.0 test:common script 'mocha test/common --recursive'`
-  and then these messages over and over:
  -  `'test' errored after 48 s`
  -  `Error in plugin 'run-sequence(test:common)'`

[this build](https://travis-ci.org/HabitRPG/habitrpg/builds/155522869): **(49 min 6 sec)**
-  after failed test:
  -  `Error: Command failed: /bin/sh -c NODE_ENV=test  mocha test/api/v3/unit --recursive`
-  and then these messages over and over:
  -  `'build:dev' errored after 2.35 min`
  -  `Error in plugin 'run-sequence(test:api-v3:unit)'`

[this build](https://travis-ci.org/HabitRPG/habitrpg/builds/157452243): **()**
-  after failed test:
  -  `Error: Command failed: /bin/sh -c NODE_ENV=test  mocha test/api/v3/integration --recursive`
-  and then these messages over and over:
  -  `'test' errored after 7 min`
  -  `Error in plugin 'run-sequence(test:api-v3:integration)'`

**Comment by khipkin** [comment]
However, if the build fails because of linting errors, it just stops and says the build failed:

[this build](https://travis-ci.org/HabitRPG/habitrpg/builds/157471241):  **(5 min 6 sec)**
-  `npm ERR! Failed at the habitica@3.38.0 lint script 'eslint .'.`

[this build](https://travis-ci.org/HabitRPG/habitrpg/builds/157397424):  **(5 min 11 sec)**
-  `npm ERR! Failed at the habitica@3.38.0 lint script 'eslint .'.`

[this build](https://travis-ci.org/HabitRPG/habitrpg/builds/157306542):  **(6 min 11 sec)**
-  `npm ERR! Failed at the habitica@3.38.0 lint script 'eslint .'.`
