### ISSUE TITLE
Weird wolf head thing

### ISSUE THREAD

**Issue by Legoguy41** [HabitRPG/habitica#7867]
General Info
- UUID: ce6fa251-fed2-4023-b752-9a4c5d106c9d
- Browser: Firefox
- OS: ???
### Description

[//](#): # When I went to the quest shop, the wolf head shown in front of Ian the quest shop guy showed for a frame before it disappeared. (I assume this was not intentional.) It then reappeared and roared (like it is supposed to do, I assume) and then the animation looped.
#### Console Errors

I do not know how to see the Console, so I do not know of any errors in the console..

**Comment by Ozzystrasza** [comment]
I don't know if that behavior is intentional or not, but I see what you are saying. The wolf head blinks once then appears again with the full animation. For me it's happening in every iteration of the loop.

**Comment by Legoguy41** [comment]
That's what is happening to me too, but I couldn't find a good way to describe it.

**Comment by SabreCat** [comment]
I'd always thought that was intentional--the ghosty wolf shape flickering into visibility. But it's awkward enough that I can see how it'd read as an error. Thoughts @lemoness ?

**Comment by lemoness** [comment]
I think it was intentional at the time, but the animation would probably look better without it!

**Comment by khipkin** [comment]
I think the [help welcome now] tag can be removed from this, since a PR is almost approved to close the issue.

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]

**Comment by Ozzystrasza** [comment]
For some reason this is happening again.

**Comment by khipkin** [comment]
There seem to be 2 copies of the gif in the repo:

![image](https://cloud.githubusercontent.com/assets/5641207/20047230/20f334aa-a480-11e6-8729-4fc95f85e400.png)

The first one has the flicker, and the second one does not.  It's possible that after the seasonal shop stuff got removed, the first one was used by mistake?

**Comment by SabreCat** [comment]
Huh. The /sprites one is the one used in production, while /img/project_files is a reference copy. I'm... not sure how just changing the /img/project_files version ever fixed the issue! I'll overwrite the production copy.
