### ISSUE TITLE
No indication of which audio theme is selected

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7869]
General Info
- UUID: N/A
- Browser: Vivaldi
- OS: Windows 10
### Description

We now have six different audio themes, plus the "Off" status--enough that it can be easy to lose track of which one is which. There's no indication of what your current setting is when you drop down the speaker icon. The current status should be bolded, or have a bullet or icon indicating it's the present setting.
#### Console Errors

N/A

**Comment by ESWAT** [comment]
Looking into this.
