### ISSUE TITLE
Losing HP and connectivity

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#787]
I am being told I am offline. Checked internet connectivity, and nothing was wrong, so I cannot gain XP currently. I switched from chrome to firefox to see if it was the browser. I lost extra HP, so it is not syncing well, I guess.

**Comment by ghost** [comment]
update, refreshed on chrome and my HP went down again. It is still telling me I am offline, and I cannot even buy a potion or check anything off.

**Comment by lefnire** [comment]
@faerieafterdark can you try on beta.habitrpg.com? you can use https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#restoring-your-avatar-stats-items-accidental-death-etc to restore your stats for the time being, hit me up with beta.habit results

**Comment by ghost** [comment]
Hi, I restored my HP and beta is working for me. Thanks for your help!

**Comment by lefnire** [comment]
I honestly think it's the recent surge of traffic causing 165 & data issues (we got a recent big push from France). I'd say use beta.habit as your primary until we get 165 fixed

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
