### ISSUE TITLE
Bare Bones Cake has irregular shape compared to other cakes (and cakes as a whole have irregular shape compared to other food)

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7882]
General Info
- Browser: Firefox 47.0.1
- OS: Windows 7
### Description

Last night, I realized the Bare Bones Cake was a little taller than all the other cakes and was told to report it here. The difference is slight (and due to the room made for the smoke). Looking again this morning, I also noticed the cakes overall are all shorter than other things that display in the food column. These differences in height are most abundantly obvious because of the number of items bubble, which is conspicuously off. I'm sure the Bare Bones vs. other cakes is unintended, but I'm unsure about the cakes overall vs. the food...

**Comment by tricksyfox** [comment]
Do you think you could post some screenshots? I "ate" all my cake.

**Comment by citrusella** [comment]
I ate the cake, too, in a moment of "oops, I meant to keep that", or I would post screenshots. (I didn't at the time because my computer was being finicky, but it's better now... but of course, now I don't have the cake...)

**Comment by tricksyfox** [comment]
I guess we can't screenshot our cake and eat it, too!

Anybody else still have theirs?

**Comment by khipkin** [comment]
Here's all the cake I still have! (I'm a hoarder.  Halp.)

![image](https://cloud.githubusercontent.com/assets/5641207/17758363/abbef226-64bc-11e6-901b-fb7e60449891.png)

**Comment by citrusella** [comment]
I forgot I had a testing account, so here's an image of the three heights of foods together in one row:

![Chocolate cake, Bare Bones cake, Chocolate Bar](https://cloud.githubusercontent.com/assets/14182450/17909033/bd897e7a-6950-11e6-926c-d461b7e57331.png)

I also note the above image seems to show a few other cakes with slightly-off heights? (Most specifically, the strawberry one.)

**Comment by thebat137** [comment]
Seems like a similar issue to #7968 --- another case of the icon size/shape being mismatched with others in the same class.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
This should no longer be a problem with the new sprites, but if it is, we can open a new ticket.
