### ISSUE TITLE
Date bug in Todo item

### ISSUE THREAD

**Issue by nurgasemetey** [HabitRPG/habitica#7884]
General Info
- UUID: 20f56644-a84a-4fad-892b-0b43987f5d59
- Browser: Firefox 48
- OS: Linux Mint 18
### Description

Guys,

I created Todo item with "08/08/2016" as due date, then I completed task. Generally, I analyze my activity by downloading my data. I noticed that the item I created showed it's due date as "07/08/2016". 

After I changed item's due date to "09/08/2016". Now exported data showed me that todo item have its due date as "08/08/2016".

Here are the pictures:

![Image of Yaktocat](http://i.imgur.com/MvIsEFT.png)
![Image of Yaktocat](http://imgur.com/R94qQnz.png)
![Image of Yaktocat](http://imgur.com/WeD4kVY.png)

With regards

**Comment by paglias** [comment]
@nurgasemetey you should consider that dates are stored using the UTC time zone, if you adjust the date for your own time zone is it still wrong?

**Comment by nurgasemetey** [comment]
@paglias really I must check it. Thanks
