### ISSUE TITLE
Bad sync with tomato.es

### ISSUE THREAD

**Issue by tellezhector** [HabitRPG/habitica#789]
tomato.es gives you a 15m break after 4 tomateos.

After 5 mnutes of this long break, HabitRPG extension keeps taking your lifepoints!

I have died too many times because of this.

**Comment by StanLindsey** [comment]
This is a known bug at this stage; check out the habitrpg-chrome board; 
https://github.com/lefnire/habitrpg-chrome/issues?sort=updated&state=open 

specifically these issues;

https://github.com/lefnire/habitrpg-chrome/issues/60
https://github.com/lefnire/habitrpg-chrome/issues/59

Cheers =D

**Comment by tellezhector** [comment]
Oh! My bad, I couldn't find something related so I thought I was being helpful. Next time I'll be a little more careful. Thank you very much. I love the app!

Sent via the HTC Vivid™, an AT&T 4G LTE smartphone

----- Reply message -----
