### ISSUE TITLE
v3: Cannot create todo with tags

### ISSUE THREAD

**Issue by nurgasemetey** [HabitRPG/habitica#7891]
General Info
- UUID: 20f56644-a84a-4fad-892b-0b43987f5d59
- Browser: Firefox 48
- OS: Linux Mint 18
### Description

Guys,

I want to create todo with tags but it seems that it your API allows only without tags.

I can create todo by doing this:

``` js
var payload = {
    "date" : todoDate.toISOString(),
    "text" : "Push-ups",
    "priority": 1.5,
    "attribute": "str",
    "type": "todo"
  };
```

But when I add tags field like this:

``` js
var payload = {
    "date" : todoDate.toISOString(),
    "text" : "Push-ups",
    "tags": ["7d616bfa-76a2-4123-9a5c-1cd5455b207f"],
    "priority": 1.5,
    "attribute": "str",
    "type": "todo"
  };
```

It responds me with following message:

``` js
"{"success":false,"error":"BadRequest","message":"todo validation failed","errors":[{"message":"Invalid uuid.","path":"tags","value":"[Ljava.lang.Object;@32006254"}]}"
```

However I have this tag:

![Image of Yaktocat](http://imgur.com/Fn9Pld3.png)

What I am missing here?

**Comment by paglias** [comment]
@nurgasemetey the error message that you got shows `[Ljava.lang.Object;@32006254"}]` as the UUID value that was supplied instead of a plain string, are you sure that it got serialized correctly before being sent to the server?

**Comment by nurgasemetey** [comment]
@paglias it seem so.  You are correct. Following is working now.

```
var payload = {
    "date" : todoDate.toISOString(),
    "text" : "Push-ups",
    "tags": "7d616bfa-76a2-4123-9a5c-1cd5455b207f",
    "priority": 1.5,
    "attribute": "str",
    "type": "todo"
  };
```

However now, task will be created with only one tag. :smile:

**Comment by paglias** [comment]
@nurgasemetey well that happens because you're not passing anymore an array but a single string. Have you tried sending a JSON-serialized array of tags?

**Comment by paglias** [comment]
@nurgasemetey I've just tried and if you serialize correctly the multiple tags in an array of strings the task gets created correctly. What's happening is that your payload is not being sent correctly

**Comment by paglias** [comment]
I've closed the issue but if you have any other question feel free to ask

**Comment by nurgasemetey** [comment]
Yeah, I tried in another client and I was able to add tags. It seems that Google Apps Script incorrectly serializes array. Sorry for interruption.

**Comment by kurokirasama** [comment]
hello, so we can't add multiple tags with google app scripts?
