### ISSUE TITLE
Polyfill Proxy in tests to throw errors for undefined chai property assertions

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#7895]
Cha now supports throwing errors on undefined properties https://github.com/chaijs/chai/pull/721

IE writing

```
expect(foo).to.exists;
```

Will fail because the property should be `exist`

However, it requires Proxies (available in Node 6). Until we can upgrade to Node 6, we should see if we can polyfill Proxy in tests to get this behavior.

**Comment by paglias** [comment]
Maybe https://github.com/tvcutsem/harmony-reflect

**Comment by crookedneighbor** [comment]
Looks like the PR I mentioned has been merged in, but is slated for the 4.0.0 release.

**Comment by paglias** [comment]
Waiting for 4.0 release

**Comment by lemoness** [comment]
Is this still something that needs to be done?

**Comment by paglias** [comment]
Yes, it's something that would be nice to have and it's not on hold anymore but very low priority

**Comment by lemoness** [comment]
I've updated the labels on this issue!
