### ISSUE TITLE
Reset doesn't remove gear

### ISSUE THREAD

**Issue by arscan** [HabitRPG/habitica#79]
I gave myself a bunch of points when in "anonymous" mode when first looking at the site, just to see what would happen.  When I signed up for an account, all the playing around that I did previously carried into my account.  That would be fine if the reset worked properly, but apparently the store items that I "bought" weren't removed when I reset.  So I have a level 1 guy with some pretty sweet gear.

**Comment by arscan** [comment]
...and unfortunately, I can't create a new character unless I use a different email address, which I probably won't bother doing.

**Comment by lefnire** [comment]
for now, just kill your character to start over, it's a work in progress

**Comment by arscan** [comment]
Ah, didn't know that I could do that.  Done, thanks.  I'll leave this open since it probably should be fixed eventually.

**Comment by lefnire** [comment]
Yep, def. needs to be fixed.

**Comment by lefnire** [comment]
fixed
