### ISSUE TITLE
Android stopped working after update 

### ISSUE THREAD

**Issue by Olia1** [HabitRPG/habitica#7905]
- sorry for posting in the wrong section, but I can't figure out how to post an issue at the android section from my phone. 
- I have updated the app to version 0.33.1, and the app has stopped working. It crashes about 2 sec after opening it. 
- tech details :
  Android 5.1.1

**Comment by crookedneighbor** [comment]
I've opened an issue for you on the android repo: https://github.com/HabitRPG/habitrpg-android/issues/598

You can click subscribe on that issue to follow the progress.
