### ISSUE TITLE
Progress graph improperly sized

### ISSUE THREAD

**Issue by weedleeedle** [HabitRPG/habitica#7907]
General Info
- UUID: 1dafa79b-7d21-4751-ab5d-215c1c5fcc45
- Browser: Firefox 48
- OS: Windows 10
### Description

![capture](https://cloud.githubusercontent.com/assets/11594471/17742654/64ee2ac0-644d-11e6-8dfc-4f08af26c753.PNG)
When opening up a progress graph of any given daily/habit, it's impossible to see the very end of the graph, normally the last couple days. This may be related to the fact that I have two monitors, and this problem only occurs on the smaller one.

**Comment by librarianmage** [comment]
Related: #6679

**Comment by librarianmage** [comment]
@Alys should this be fixed after the client redesign, if it is still a problem?

**Comment by Alys** [comment]
@MathWhiz Yes, good point, thanks. I'm putting this on hold.

**Comment by lemoness** [comment]
We've temporarily removed this feature to revisit and improve it, so I'm closing this ticket for now.
