### ISSUE TITLE
Completed Dailies and Tasks do not damage Boss

### ISSUE THREAD

**Issue by jrenee25** [HabitRPG/habitica#7909]
General Info
- UUID: 37635d5f-c9cb-4842-8c86-2a0be1263afa
- Browser: Chrome 52.0.2743.116 m
- OS: Windows 7 Ent
- Group (Party) ID: 73d7f036-cf6a-49cf-9e29-6462f023aad0
### Description

I completed all of my tasks and dailies yesterday, but when I logged in this morning and looked at the party chat (group ID 73d7f036-cf6a-49cf-9e29-6462f023aad0), I saw this: "JennB attacks Magical Axolotl for 0.0 damage. Magical Axolotl attacks party for 0.0 damage."

How is this possible? If I left items undone, then I would have done damage to my party, but it looks like I didn't get credit for the items I completed. 
#### Console Errors

There are no console errors to report.

**Comment by jrenee25** [comment]
This happened again today. Here is the message I got when I logged into the party chat: "JennB attacks Task Flotsam for 0.0 damage. Task Flotsam attacks party for 0.0 damage. -2 minutes ago"

**Comment by Alys** [comment]
For the record, here is my reply to JennB's first report of this when they posted the same report to the Report a Bug guild:
"JennB : I have not seen that before that I recall. It's weird. I have looked into it to some extent but haven't found any explanation. If it happens again PLEASE tell us!"

@JennB, for this second quest, can you please tell me which party member started the quest? I want to look up their data to compare the exact start time of the quest with your cron time (assuming they force-started the quest which is likely in a party of that size).

**Comment by jrenee25** [comment]
I'm so sorry - I didn't see your response in the "Report a Bug" guild until this morning.

I believe both quests were started by EmanonSuomynona (8cb48592-37f4-4925-a1fd-9b030f6d8619).

**Comment by Alys** [comment]
We've identified that this happens due to problems that cause cron to fail part way through, such as tasks with large history arrays / VersionErrors. @TheHollidayInn is working on concurrency fixes that should help.
