### ISSUE TITLE
Opening a Challenge description jumps to the top of the page

### ISSUE THREAD

**Issue by tricksyfox** [HabitRPG/habitica#7914]
General Info
- UUID: 90e5c4f2-d5d9-4472-ab2c-19041ee2218d
- Browser: Chrome
- OS: OS X Yosemite

Description
On the website, when I click on a challenge to open up its description, I get jumped back to the top of the page and have to scroll down to where it's opened. This isn't an issue when things are near the top, but it can get tiresome when you're further down!

Note from Alys in the Bug guild:
That will almost certainly be a side-effect of this fix: Scroll to top when changing pages - Pull Request #7880 for this issue: Opening Time Traveler page via click on Mystic Hourglass should scroll to top (also other pages, e.g., Pets, Mounts, etc) - Issue #4326. That's my fault not the person's who coded the fix: I specifically said it should apply to all pages.

**Comment by Alys** [comment]
Thanks @tricksyfox.

I've marked this as important because it will be extremely annoying when you're trying to view challenges far down the list and it affects potentially every user.

**Comment by Ozzystrasza** [comment]
I will try to fix this.
