### ISSUE TITLE
Character appears too high in avatar on profile when no pet or mount is equipped

### ISSUE THREAD

**Issue by esmanning** [HabitRPG/habitica#7916]
General Info
- UUID: 809d8b43-07a1-49ab-9bb5-ad3ba461688d
- Browser: Firefox
- OS: OS X El Capitan
### Description

With no pet or mount equipped, my avatar character appears higher up in the profile version of my avatar than on my header, so that the profile version looks like it's floating above the ground.

![screen shot 2016-08-20 at 3 57 55 pm](https://cloud.githubusercontent.com/assets/15826763/17833766/c7662d52-66f4-11e6-859e-bb12dbf9a828.png)

**Comment by Alys** [comment]
Confirmed. Equipping and dequipping a pet shows this clearly.

**Comment by khipkin** [comment]
Wow that's super bizarre. Good catch!

**Comment by khipkin** [comment]
Suggestion: [entry level coding]

**Comment by Alys** [comment]
I haven't looked at the code myself so I can't be sure it's entry level, but @khipkin is probably right so I'll mark it as that. If any new contributors start this but find it troublesome, you're welcome to ask questions here in the issue!

**Comment by AndrewPomorski** [comment]
Hi, I can tackle this one.

**Comment by Alys** [comment]
@AndrewPomorski Thank you!

**Comment by jakers1776** [comment]
Is this still an issue?

**Comment by Alys** [comment]
It is still happening. @AndrewPomorski are you still working on it?

If it turns out to be not an easy fix, requiring changing only a small amount of code, we might leave this until we do an upcoming website improvement project.

**Comment by kristian-welsh** [comment]
I can't find this issue on the live site, was this fixed?

**Comment by Caryyon** [comment]
I also was unable to reproduce. Has this issue been fixed or should I keep digging?

**Comment by SabreCat** [comment]
Reproduced it just now in the Tavern. If you look carefully as you click different profiles, you will see it come up, ~but it's not reproducible by toggling one's own mount and viewing one's own profile.~

![image](https://cloud.githubusercontent.com/assets/4501321/21244413/21cfb2a0-c2e3-11e6-9644-506acc65ce6c.png)

~I suspect it may be a difference between whether the user's equipped mount is `null` vs. `undefined`, or something similarly arbitrary.~ Ignore that. It's whether or not there's a pet equipped. Like in the issue title. `>.<`

**Comment by Alys** [comment]
Equipping and dequipping a pet still shows this problem in your own avatar.

**Comment by SabreCat** [comment]
Edited my post to strike out my fail.

**Comment by khwj** [comment]
@Alys 
Is @AndrewPomorski still working on this? If not I'd like to take this task.
