### ISSUE TITLE
Orb of Rebirth: change to cost 6 gems, not remove any equipment

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7917]
Now that long-term players have so much equipment, using the Orb of Rebirth results in far too much gear to buy back and is unfair to users who have already bought cross-class previous-season gear using gems. We've decided to fix this by stopping the Orb of Rebirth from removing any equipment at all, and make it cost slightly less.

After this change goes live, we will announce it in a Bailey message. The message will also say that if anyone who used Rebirth in the past is not happy that they lost their gear, they can post to the Report a Bug guild to ask that they be given their gear back, and we'll do that for them. Any gold they've already spent can be regained with [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values).

For those players who want to repurchase all their gear, after this change is live, we will start creating a new gem-purchasable item, probably called "Empty the Armory" which will cost probably 2 gems and will remove all gear (possibly excluding free gear). It will need to not introduce the bug reported in https://github.com/HabitRPG/habitrpg/issues/7662

So, the actions for this issue are:

**For the contributor who works on this:**
- [x] Change the cost of the Orb of Rebirth to 6 gems.
- [x] Change the Orb of Rebirth so that it does not remove any equipment (delete old code rather than commenting it out even if you think we might reuse it later).
- [x] Change all tests as required.
- [x] Write new tests if required (might not be needed).

**Actions for staff/admins:**
- [x] Write the Bailey message.
- [x] Save a list of all players who have the achievement for the **original** Orb of Rebirth so that they can get the Empty the Armory achievement too (see comment from Lemoness below).
- [x] Create an issue for Empty the Armory and advertise to contributors
  - [x] Include a note that issue #7662 must not occur.
  - [x] Include a link to the version of the code base from just before this issue was resolved so that any old code can be easily referred back to.
  - [x] The Empty the Armory achievement should be immediately given to all players who used the **original** Orb of Rebirth. 
- [x] Ask wiki editors to update the wiki.
- [x] Inform Socialites.

This change has been approved by @lemoness

**Comment by lemoness** [comment]
A follow-up: when we make this change, we should also award the badge
for Empty the Armory (or final name) to everyone who used the
original Rebirth already. The badge will later be made generally available
when we finish the new feature.

**Comment by Alys** [comment]
I've updated the top post with two action items for the Empty the Armory achievement being given to Rebirthers.

**Comment by lemoness** [comment]
I've listed the need for an Empty the Armory badge on Trello to assist with
this issue.

**Comment by cching0L2** [comment]
I would like to tackle this issue if nobody else is interested

**Comment by Alys** [comment]
@cching0L2 That would be great, thank you! You're welcome to comment here if you have any questions or if you run into trouble.

**Comment by cching0L2** [comment]
I saw some pull requests with a checklist progress ("7 out of 12" etc.).  Should I open a pull request as long as I've made some progress, and let admins checkoff the checklists?

**Comment by crookedneighbor** [comment]
If you're stuck and need help, feel free to open a PR that is a work in progress. If you're not stuck, it would be better to wait and open the PR when you're done.

**Comment by citrusella** [comment]
I'm not sure if this is the right time or place to ask (since it's largely a "curiosity" sort of question for something that's listed as going to get a new issue), but would Empty the Armory be available free under the same circumstances (lvl 100) as free rebirth? (i.e. to replicate the feel of current post-100 rebirth--someone could empty the armory and then start a new adventure) Or would it always cost two gems (or whatever it ends up costing)?

I was just sitting and watching this issue, but my curiosity got the better of me, so I just had to ask. XP

**Comment by lemoness** [comment]
Very good question! It should be free after level 100 as well, to replicate
the previous Rebirth experience.

**Comment by taldin** [comment]
Heh, that's a different way of solving the problem of 'equipment on Orb of Rebirth is too long to display'..... I approve of this issue!  (having just used an Orb for round 3, and the only thing I've bought are  a set of Wolf Ears...I know, priorities!)

**Comment by Alys** [comment]
reopening so that admins don't forget to do the tasks for them, listed in the top post. I'll start handling them now.

**Comment by lemoness** [comment]
It appears that we haven't yet awarded the Empty the Armory badge to everyone who did the old version of Rebirth! The badge art isn't quite finished yet, so perhaps we should download a list of all the users who need to get that badge when we first introduce it, before other people start using the new version of Rebirth.

**Comment by Alys** [comment]
@lemoness I captured a list of all the players who had the Rebirth achievement just before this change went live, and I'm keeping it to give them the Empty the Armory achievement once it's been created. An action item for that exists in https://github.com/HabitRPG/habitrpg/issues/7991
