### ISSUE TITLE
show quest progress notification when completing task

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7922]
If the player is participating in an active boss quest (i.e., not while the quest is in the invitation stage), when a Daily or To-Do is completed or a positive Habit is clicked, there should be a notification of how much boss damage has been just been obtained (from `party.quest.progress.up`). Suggested wording: "+12.3 damage to boss"

When in an active collection quest, if the player has just found a quest drop (`party.quest.progress.collectedItems`), there should be a notification of that. Suggested wording: "+1 quest item found".

We need to decide on the colour of the notification. If no other suggestions are made, I suggest using the same green as for the drop notifications.

This feature was requested by @lemoness

**Comment by lemoness** [comment]
This is linked to this issue as well: https://github.com/HabitRPG/habitrpg/issues/7928

**Comment by tricksyfox** [comment]
Can the item notifications also show the item image, like other drops do?
What colors do we have in use right now?

Green - Item Drop
Yellow - gold/silver
Purple - XP
Red - Health
Blue - Mana

...So maybe quest stuff should be orange?

**Comment by Alys** [comment]
Orange is typically an indicator of errors, warnings, or other bad/semi-bad things so it's not ideal for a positive message.

**Comment by gambtho** [comment]
leave it as is -- or?

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]

**Comment by Alys** [comment]
This was implemented in https://github.com/HabitRPG/habitica/pull/7951
