### ISSUE TITLE
Customizing avatar ears crashes app

### ISSUE THREAD

**Issue by RinnaB** [HabitRPG/habitica#7923]
I purchased ears for my avatar with gems, and they did not show up on my avatar. Now every time that I click on the ears, the program crashes and shuts down.

**Comment by crookedneighbor** [comment]
Is this on the [iOS app](https://github.com/HabitRPG/habitrpg-ios), the [Android app](https://github.com/HabitRPG/habitrpg-android), or on the website?

**Comment by RinnaB** [comment]
This is on iOS

**Comment by Alys** [comment]
@RinnaB Can you please report this through the app developer through Menu > About > Report a Bug? That will send useful debugging information about your phone to him. No personal details from your phone will be included. 

You do need to have the email app configured in your phone for that to work. If that's a problem, comment again here and we'll give you alternate ways of reporting it (that option is the easiest and best though).
