### ISSUE TITLE
API does not allow admin to delete or flag private posts

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#7925]
### Description

Version 3 of the API does not allow administrative users to delete or flag posts found in private groups (such as parties), even if the post has been flagged by a group member. The route returns "Group not found or you don't have access."

The trouble appears to be that we don't pass the `optionalMembership` option to the `getGroup` call used to fetch the group before deleting a message from it. Given there's a check a few lines later that allows only the message creator or an admin to perform the delete, should `optionalMembership: true` be sent here?
#### Console Errors

`{"success":false,"error":"NotFound","message":"Group not found or you don't have access."}`

**Comment by crookedneighbor** [comment]
Working on this.
