### ISSUE TITLE
Farewell Page on Logout

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7927]
When a user logs out, they should have a customized farewell page that advertises the mobile apps.  It should include pictures of the two mobile apps, buttons that link to the App Store and Google Play Store, and text such as "Heading out? Take Habitica on-the-go! Can't wait to see you again soon."

**Comment by librarianmage** [comment]
I can work on this!

**Comment by librarianmage** [comment]
My idea for implementation:

After logging out, users are redirected to a page (/static/farewell ?) instead of /static/front. This way, people can look at it for longer and click the links, and it won't suddenly disappear.

**Comment by crookedneighbor** [comment]
This should wait and be done as part of the redesign project.

**Comment by lemoness** [comment]
We will need designs for this before it can be implemented. I'm adding a new "status: on hold - designs needed" label.

**Comment by kimiannalena** [comment]
Is this still an issue? I'd like to come up with a design.

**Comment by SabreCat** [comment]
This looks like a feature that, in the event that we decide to embark upon it, would be tracked on the internal project board rather than the outstanding issues tracker. Closing.
