### ISSUE TITLE
Re-Roll doesn't provide feedback or avoid double-submits

### ISSUE THREAD

**Issue by willross33** [HabitRPG/habitica#793]
1. I paid money to buy tokens.
2. I clicked Re-Roll.
3. I clicked Re-Roll again because the UI hadn't responded and I assumed my first click had been lost.
4. I noticed that I was down 8 tokens.

Not optimal.

**Comment by lefnire** [comment]
Did the Reroll work at all after second time? What's your user id I'll give
you our more tokens

**Comment by willross33** [comment]
The re-roll did work after the second time.

I don't know if it worked after the first time; the re-roll dialog was still up and I didn't think to close it and check.
It is entirely possible that it worked the first time and I just didn't realize.

username: wross

**Comment by wc8** [comment]
I almost re-rolled twice, thinking the first one didn't take, but I happened to think to check first. 
Hence this suggestion: [Feedback on Spending Tokens](https://trello.com/c/1H9muPdK)
It could probably avoid some future tickets regarding lost tokens, failed purchases if users had a clear notification after clicking something that spent tokens. "Re-roll applied" or "Re-roll applied, 4 tokens spent" for example.

**Comment by lefnire** [comment]
@willross33 increased your tokens. I think these are actually two bugs: (1) large actions still taking a long time to processes (batch update issues I'm working on), and (2) page rewrite issues futzing with modal-closing scripts. In the past the transaction was more obvious, but those two issues make it less obvious. Then there's @wc8's suggestion which will help too. so 2 bugs, 1 feature request. Sorry guys! Anyway, you should be good for now @willross33

**Comment by willross33** [comment]
Oh yeah that's a few more tokens!

Thanks for the ultra fast support.

Those fixes sound about right. Keep up the good work -- I frickin' love this app!!
