### ISSUE TITLE
Change Default tags to match types, not times of day

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7933]
The default tags on the website, "morning", "afternoon", and "evening", have not been intuitive. Instead, we'd like to change them to match the categories created when setting up the mobile app:

Work
Exercise
Health + Wellness
School
Teams
Chores
Creativity

The default tasks should then each be pre-tagged with one of these corresponding tags, both on mobile and on the website, so that the user has a functioning tag system already set up.

**Comment by librarianmage** [comment]
I can do this!

**Comment by librarianmage** [comment]
Would you like emoji with them?

**Comment by lemoness** [comment]
My impulse would be to say yes, but I'm not sure if they'll show up correctly in the app. @vIiRuS, any insights?

**Comment by librarianmage** [comment]
@lemoness using the text won't work, but using the actual characters will

**Comment by lemoness** [comment]
In that case, go ahead!

**Comment by Alys** [comment]
Actually I'm not sure the emoji characters will be a good idea because they display differently (sometimes very differently) in different platforms. The text emoji we use are standardised across all official Habitica platforms and I'd really like to encourage people to use them instead. The text emoji won't work yet on the mobile apps in the tag names, but I expect they will in future. I suggest that we use tags with no emoji for now and add the text emoji later when the apps support it.

**Comment by Alys** [comment]
Further to that: We've had people in the past complaining about changes in emoji appearance when we switched emoji libraries. I think they are also likely to complain if their tags look different on the mobile app compared to the website. Using text emoji (or no emoji) prevents that.

**Comment by lemoness** [comment]
Very good points. Let's hold off until tag names support text emoji, then.

**Comment by DrStrangepork** [comment]
Only commit `a719e39` is valid

**Comment by librarianmage** [comment]
@DrStrangepork I was going to work on it 😔 (It's okay)

**Comment by Alys** [comment]
@DrStrangepork Before you start work on an issue, it's a good idea to first read through the comments to see if anyone else is working on it, and if there are recent comments indicating that they are, then it's best that you leave it to them. If you ever see an issue where the comments are old, it's okay to ask if the person is still working on the issue. 

It's also best to comment on any issue before you start work, even on issues that aren't in progress. That helps to prevent anyone else starting work on it too and it gives the admins a chance to give you advice about the issue if necessary or to ask you to not proceed if something has come up that means the issue should not be resolved yet.

Please see "Ways to Help" > "Website" in [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) for more information.

**Comment by DrStrangepork** [comment]
I apologize for jumping in. I was using this to validate my local install and just ran with it. I'll be nicer in the future. :frowning:
