### ISSUE TITLE
blocking a user should cause them to rest in the inn

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7935]
The [API](https://habitica.com/apidoc/) (see also [on the wiki](http://habitica.wikia.com/wiki/Application_Programming_Interface)) has a route for blocking a user, which prevents them using Habitica in any way. The route should also cause the user to be resting in the inn ("sleeping").  (EDIT: the API `block` route is not related to this issue. See one of my comments below for details.)

Unblocking the user should NOT stop them resting in the inn. 

This is being done so that non-malicious users who need to be blocked for various reasons do not suffer unfair damage when they are later unblocked.

**Comment by khipkin** [comment]
@Alys When would non-malicious users need to be blocked?  As part of the RPG aspect of the game?

**Comment by Alys** [comment]
Never for gaming reasons. If a [child under 13](http://habitica.wikia.com/wiki/Children_Using_Habitica) uses Habitica without parent/guardian consent, we have a legal obligation to block them until permission is received. Or a user's account might be used inappropriately by a housemate or child, who then starts posting bad messages. Things like that. Rare cases, but when the user isn't at fault, they and their party mates shouldn't suffer damage.

**Comment by Alys** [comment]
My original post was wrong - the code for blocking a user from using the site is not in the API (the `block` route was badly described and I've fixed it in https://github.com/HabitRPG/habitrpg/commit/9981f450c0d49d499989f8eaf87661e9f7cd4454 ).

The code for blocking a user from using the site is:

```
$ git grep hero.auth.blocked
test/api/v3/integration/hall/PUT-hall_heores_heroId.test.js:70:    expect(hero.auth.blocked).to.equal(true);
website/server/controllers/api-v3/hall.js:172:    if (updateData.auth && _.isBoolean(updateData.auth.blocked)) hero.auth.blocked = updateData.auth.blocked;
website/views/options/social/hall.jade:70:                input(type='checkbox', ng-model='hero.auth.blocked')
```

**Comment by gambtho** [comment]
Thanks for the very quick and kind responses -- I'll get my local environment working better before submitting future PRs.   Corrected version of this one on the way (assuming it passes CI)
