### ISSUE TITLE
"Forgot Password" should not immediately change your password

### ISSUE THREAD

**Issue by sambokai** [HabitRPG/habitica#7936]
After clicking on the "Forgot Password" button and entering your email on habitica.com you immediately receive this email: 

> Password for `your username` has been reset to `random password`
> 
> Important! Both username and password are case-sensitive -- you must enter both exactly as shown here. We recommend copying and pasting both instead of typing them.
> 
> Log in at https://habitica.com. After you have logged in, head to https://habitica.com/#/options/settings/settings and change your password.

There should be a link that allows you to reset the password if desired. the way it is now people who have your email address can reset your password even if they do not have access to your email account.

there should be at least a warning in the email that says "if you did not initiate this password reset please contact our support team"

**Comment by Alys** [comment]
@onlineshrekjr We have related suggestions in https://github.com/HabitRPG/habitrpg/issues/4499 so I'm going to close this issue, but you're welcome to add comments to that one if you wish.

**Comment by Alys** [comment]
I have deleted a comment that I made in 2016 because it contained sambokai's original username and they emailed me to ask for it to be deleted. The rest of the comment said this:

> We have related suggestions in https://github.com/HabitRPG/habitica/issues/4499 so I'm going to close this issue, but you're welcome to add comments to that one if you wish.
