### ISSUE TITLE
Private Messages (PMs) should be exportable from Inbox

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7939]
The Social > Inbox screen needs an option for exporting all PMs in an easy-to-read format.

I suggest that the exported file be an HTML page so that the formatting from markdown can be retained (exporting as markdown itself isn't so good because many players won't have an easy way to display it). However other suggestions are welcome.

There should also be a note to explain that if the player wants to export their messages in a code-friendly format (JSON or XML) they should use the Data > Export Data > User Data options.

That Data > Export Data screen should also have a brief message saying that private messages can be exported in a readable format from the Inbox.

**Comment by akortesmaa** [comment]
I'd like to give this one a try!

**Comment by Alys** [comment]
@Althenis Thank you! If you have any questions or run into trouble, just ask here!
