### ISSUE TITLE
HabitRPG freezed

### ISSUE THREAD

**Issue by TheRise88** [HabitRPG/habitica#794]
The page is not responding anymore. Cannot edit tasks, cannot delete them, cannot flag them. Cannot find my inventory, stable and market anymore. Since two days everything is completely stuck. Tried to access from different devices, and both logging in as standard user and beta user. 
Critical thing: I'm realizing I was somewhat dependent on habitrpg since I'm not doing much work since Sunday :S

Anyone experiencing the same issue??

**Comment by wc8** [comment]
Try beta.habitrpg.com
See #427 & #787 for more instructions

Note: possibly related to #619 and #769

**Comment by SamPearson** [comment]
Same issue here; My account (name: spizzo, id: b19c741d-1afd-4f1f-bb8c-88f7a7aec703) has all tasks locked into the state they were in on saturday or sunday night. Clicking unfinished tasks will not mark them grey or add xp/gold to my character. I cannot edit habits, dailies, todos, or rewards. Attempting to modify the character via the restore tool doesn't affect the character. 

Same behavior is showing on beta.habitrpg.com as well as www.

Possibly related, I now have a ton of unnamed entries in the habits column.

**Comment by mkirmes** [comment]
Same issue as SamPearson, stuck on stats from Sunday night.
Not the behavior described from #427, #787, 
Also seems different from #769.

bug both on beta & normal, in Firefox and Chrome (on Windows 7 & 8), different laptops, also in private mode.

Firebug says:
TypeError: t[n] is null
...ion"==typeof e[e.length-1]&&(t=e.pop()),this._sendOp("unshift",e,t)}},insert:{ty...
HQ5bLe...dhBQ.js (Line 3)

TypeError: t[n] is null
...ion"==typeof e[e.length-1]&&(t=e.pop()),this._sendOp("unshift",e,t)}},insert:{ty...
HQ5bLe...dhBQ.js (Line 3)

Chrome's console again is a lot more wordy in its description, so I'll post a screenshot that's missing only the last two lines.
![chrome-console](https://f.cloud.github.com/assets/3756758/360221/b8ff4434-a185-11e2-8764-4e740c54e0af.jpg)

The empty grey entries in the habit column are increasing with each page reload (a new ones gets added each time).(Thankfully, I caught that early, by now that would involve too much counting).

Hope that info helps.

**Comment by lefnire** [comment]
Ok, we have Websockets on beta.habit - can someone try that one again?

**Comment by mkirmes** [comment]
While I have no idea what websockets are, it does work on beta now.

EDIT: and now also again on normal habit.

**Comment by SamPearson** [comment]
Verifying that it's working for me on beta.habit as well. Grey habits were present but could be deleted.

**Comment by lefnire** [comment]
what whaaaat! we're live on prod with websockets, is anyone here experiencing this issue any more?

**Comment by lefnire** [comment]
@mkirmes that JS dump will be _most_ helpful. I'm hoping websockets will stop-gap the issue while I diagnosing the underlying cause, and those errors will help me a ton. Thanks

**Comment by SamPearson** [comment]
Looks good on production, nice job.

**Comment by DevonOrxi** [comment]
Same issue here... But then it came back today and my lv 8 character was dead.

My user is Hariel Cid   (b025b30e-373f-4324-96ff-400a4ecd85be)

**Comment by TheRise88** [comment]
@TheOneAndTrueAcid you can go to settings->danger zone->restore

**Comment by TheRise88** [comment]
Also for me the issue is not persisting. Great job!! =)

**Comment by lefnire** [comment]
ok, i'm gonna knock this down to `important` unless it comes up again - i'll keep it open for now while i investigate the underlying cause

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
