### ISSUE TITLE
automatic purging (deletion) of older private messages (PMs) by cron

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7940]
When a player's inbox contains more than 50 messages, the older ones should be purged to bring the total number down to 50. For a subscriber, the limit should be 200, not 50.

This should be done by cron.

The Inbox should have a clear statement at the top and bottom of the messages describing this deletion feature, telling the player how many messages they have, and also pointing out that they can use the export feature (https://github.com/HabitRPG/habitrpg/issues/7939) if they want to keep old messages.

Any PR that implements this can't be merged until https://github.com/HabitRPG/habitrpg/issues/7939 is merged [EDIT: it's merged now]  and proved working in production. It might also be wise to wait until some subscription problems are fixed because we don't want subscribers to lose messages if there are any problems with their subscription that cause their limit to drop to 50.

Before this is merged, we should make sure the players have a decent amount of notice via at least one Bailey message several days in advance. We should probably display a message in the inbox in advance (e.g., the same message described above but saying that the automatic deletion will be starting soon). When it goes live, there should be another Bailey message.

NB: This feature is intended to reduce database space usage and to improve performance for individual players (the website is slower if the player has a lot of messages in their inbox).

**Comment by khipkin** [comment]
For subscribers, I think there should be a grace period after their subscription ends so they have some time to export their PMs (or delete a bunch of them themselves).

**Comment by Alys** [comment]
I've taken this off hold now that https://github.com/HabitRPG/habitrpg/issues/7939 has been done.

**Comment by Alys** [comment]
Ah, actually, I've just read this note of mine from the top post:
"It might also be wise to wait until some subscription problems are fixed because we don't want subscribers to lose messages if there are any problems with their subscription that cause their limit to drop to 50."
I'm still in favour of that, now that I've remembered it. I'm putting this back on hold temporarily while we think about it.

**Comment by lemoness** [comment]
Is this something that we can open up yet?

**Comment by Alys** [comment]
We'd need to reimplement the PM export option first, and also ideally fix that subscription problem since recovering unfairly deleted PMs would be nightmarish.

**Comment by TheHollidayInn** [comment]
@paglias Can this be added or fixed by your Inbox updates?

**Comment by paglias** [comment]
Yeah, once we move the messages outside the collection this won't be needed anymore so I'm going to close it
