### ISSUE TITLE
optional feedback in account deletion confirmation screen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7942]
When a player goes to Settings > Site to delete their Habitica account, they are given a confirmation modal. The modal should contain a textarea for **optional** feedback about Habitica (e.g., what they didn't like, why they decided to stop using it).

The API route ("Delete an authenticated user's account") should also accept an optional feedback message.

The feedback should be emailed to admin@habitica.com. It does not need to be stored in the database.

The words describing the textarea should ask if the player would like to give any feedback, should emphasise that it's optional, and should say that it can be in whichever language the player feels comfortable with (does not have to be English).

**Comment by khipkin** [comment]
Suggestion: [help welcome now] --> [in progress]
