### ISSUE TITLE
Notifications / Notification Modals no longer work.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#7946]
General Info
- UUID: `f9c89bba-abf8-4f20-a974-cf1550ff603f`
- Browser: Chrome 52.0.2743.116 m
- OS: Windows 7
### Description

I've noticed that recently (maybe since #7588?) Party Up and Party On achievements don't spawn achievement modals anymore.  I've seen this behavior both in local testing and on the main site.
#### Console Errors

None.

**Comment by SabreCat** [comment]
There may be something broader going on with modals. I just got a level up but didn't see the modal, despite not having the "don't show popup" preference on.

**Comment by khipkin** [comment]
Earlier today, I got a premature level up modal, and I had no points to allocate.  Then, after checking off a few more dailies, I actually leveled up and got another modal; the second time, I actually had a point to assign to a trait.

**Comment by khipkin** [comment]
Notifications that still seem to work normally:
- Streak

**Comment by habitrpguser** [comment]
I wrote the following post in the "Report a Bug" guild, and @SabreCat asked me to add it here:

> Aaaand one more challenge bug: Is it just me overlooking things, or don't we get any notification about winning challenges anymore? (Website, not app, not mobile.) I know there was [a known bug about getting the wrong notifications](https://github.com/HabitRPG/habitrpg/issues/7716), which was closed 23 days ago. But that's not what I mean. I won two challenges since then and didn't see any notification.

I hope this helps! (If someone else confirms this, the challenge bug label should probably be added to this issue, too.)

**Comment by crookedneighbor** [comment]
Figured out the party achievements problem. We're now setting those on the server https://github.com/HabitRPG/habitrpg/pull/6907

But never updated the client to account for that.  Since the party page refreshes when joining or inviting new users, the party achievement logic never gets hit.

**Comment by crookedneighbor** [comment]
Personally, I don't think it's worth working on until after the redesign unless it's a super simple fix.

**Comment by crookedneighbor** [comment]
Are we sure that it's all notifications? I've only experienced it with the party up and party on achievements.

**Comment by khipkin** [comment]
Based on what @habitrpguser said above, it's also challengeWon notifications.

The only notifications I've actually seen in the last while are streaks and level ups, so I'm not sure about the rest.

**Comment by khipkin** [comment]
I'm currently working on this... not sure how it's going to turn out, since I haven't had my local setup running for a while. 😝

**Comment by librarianmage** [comment]
@khipkin How are you doing on this?

**Comment by Alys** [comment]
I'm putting this on hold until after the new website is released. It's likely to either be fixed then or have new code that will need to be worked on.

**Comment by lemoness** [comment]
I'm closing this issue because if there are still issues with those modals, they will have a different cause and need a new ticket.
