### ISSUE TITLE
Just randomly died

### ISSUE THREAD

**Issue by rawbherb** [HabitRPG/habitica#796]
I just leveled up yesterday, and I had 45 health today, but when I went to Habitrpg it gave me a game over screen! Has this been a common problem?

-I was CLOSE to dying before I levelled up. Would that have anything to do with it?
-Is there any way to get my armor/level back? :$

**Comment by lefnire** [comment]
Follow up on https://github.com/lefnire/habitrpg/issues/777 . I'm diagnosing currently, most likely case is using multiple computers
