### ISSUE TITLE
editing a challenge task deletes participants checklists

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7962]
This is not confirmed yet but there is a report in the Report a Bug guild indicating that when a challenge creator edits a challenge's Daily or To-Do, any checklist items that the participants added are deleted permanently.

If someone could test this to confirm it, that would be really helpful! I can't because I have limited internet access today.

I'm marking this as critical priority because players trust their data to the checklists. If the bug is confirmed, the dev whose fix is merged will get the Hammer of Bug-Crushing. 

We should strongly consider disabling the ability for challenge owners to edit Dailies and To-Dos until this is fixed.

**Comment by SabreCat** [comment]
Confirmed on a local test. Changing e.g. the title of a challenge Daily or To-Do wipes out all participants' checklists on those tasks.

**Comment by Alys** [comment]
Thanks @SabreCat 

We need either a fix asap or to turn of the ability to edit tasks (editing Habits and Rewards would be okay). What you do think about that idea?

**Comment by khipkin** [comment]
[This line](https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/task.js#L115) may be the problem.

**Comment by SabreCat** [comment]
@khipkin: I just saw that myself, but I don't think so. That line lists what fields _should_ be specific to the user's instance of the challenge task, instead of coming from the challenge itself. (`value` is also one, but that's protected somewhere else.) Hmm--are notes etc. also getting overridden on challenge edit? Will test that.

**Comment by SabreCat** [comment]
Notes persist fine through a challenge update. So it is specific to checklists...

**Comment by SabreCat** [comment]
Fix is in https://github.com/HabitRPG/habitrpg/commit/294681c140a279714709944dd550f1568270b892, @crookedneighbor is working on adding tests.
