### ISSUE TITLE
In Market, price for gems is horizontally misaligned with other prices

### ISSUE THREAD

**Issue by thebat137** [HabitRPG/habitica#7968]
Browser: Firefox (Build identifier: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0)
OS: Debian Linux (Sid)

What it says in the title --- the gem price (20 gold) is slightly higher than the other prices in the same section (fortify, rebirth, key, messages).  Trivial, but it looks slightly sloppy.

**Comment by Alys** [comment]
We're in the planning stages for a website improvement project which will fix problems like that, so I'm closing this now, but thank you for mentioning it! 
We have a guild now for telling us about bugs, which you might find more convenient. You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac). It's recommended that bugs be posted there first and if a GitHub issue is needed, we'll let you know.

**Comment by thebat137** [comment]
Didn't realize the Bugs Guild was the preferred posting location now, not just the "easiest".  Thanks for the heads-up, I'll go there in the future.
