### ISSUE TITLE
show/hide header doesn't move up/downwards the content

### ISSUE THREAD

**Issue by Dayde** [HabitRPG/habitica#797]
While showing/hiding the header the content doesn't stick to the top of the page (it needs refreshing the whole page).

While it is not really a problem when hiding, the header is overlapping the content when showing it.

This bug was experienced on google-chrome, ubuntu 12.10.
![hiding](https://f.cloud.github.com/assets/1503452/361183/2fa39d62-a1bb-11e2-8a5b-0f09321586d9.png)
![showing](https://f.cloud.github.com/assets/1503452/361184/2fbd48f2-a1bb-11e2-83c1-4003d218f488.png)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
