### ISSUE TITLE
Regularly get large pink pop-up "An error has occurred: Unexpected error) in browser

### ISSUE THREAD

**Issue by jjmcgaffey** [HabitRPG/habitica#7974]
General Info
- UUID: 8f0f2f48-73b0-4b27-a95a-40603cc919e7
- Browser: Firefox on Android - possibly also on Windows (10/7), not sure.
- OS: Android 5.x, 6.0.1
### Description

I mostly use the app, on Android. On the rare occasion I go to the website, I usually get a bunch of pop-ups - little 2-line things, in blues and greens, telling me about earned/lost mana, XP, health. And for some time (several months at least) now, I've also gotten a huge pink pop-up, 10-20 lines, that starts "An error has occurred (bunch of text) Unexpected error (more text)". It usually moves up and disappears pretty quickly, like the little pop-ups.

Possibly pertinent information: I thought the pink pop-up appeared every time I went on the website; since I reported it in the Report a Bug guild, and have been checking the website more often to see if a solution helped, I now think it appears only when I get a major pop-up as well - Bailey, a quest starting or ending, or a streak notification. Another possibly pertinent fact: some months ago, I got annoyed by being notified of leveling up on both the app and the website (I had just used Orb of Rebirth and was leveling fast!), and checked the checkbox for "don't show this any more". The streak notification has the same checkbox, none of the others do. Since then I have not been notified of leveling up in either place, and I can't figure out how to turn it back on. Closing the browser won't help; this is even a new phone, total new start.

I  _think_ I have seen the pink pop-ups in Firefox on Windows (7/10) as well. But right now I'm not seeing them, so reporting it only for Firefox on Android. Per request in Report a Bug, I have cleared cache and cookies in the browser; it made no difference. 

I don't currently have a screenshot of the error. I'll add one as soon as it shows up again and I remember to capture it.
#### Console Errors

It's hard to get at the console on the mobile browser, best I can do is screenshots.
https://www.dropbox.com/s/06y6uv5nsfr3z44/2016-09-01%2016.59.49.jpg?dl=0
https://www.dropbox.com/s/c0ylq92r1xc32n3/2016-09-01%2017.00.03.jpg?dl=0

**Comment by paglias** [comment]
I've searched in the logs but couldn't find any error linked to @jjmcgaffey 's UUID

**Comment by Alys** [comment]
@jjmcgaffey Clearing the cache isn't likely to help. Did you try using the red button at https://habitrpg-beta.herokuapp.com/static/clear-browser-data and then clearing cookies after that (**before** logging back in to Habitica)? I'm not at all sure that will help either but it's worth trying.

A lot of those messages from the console don't seem related to Habitica so I'm wondering if you have onne or more extensions installed on all the browsers that you've had this problem on. Do you have a browser with no extensions at all that you can use Habitica on for a while?

You can turn the level-up notifications on and off at Settings > Site but I wouldn't expect that to make any difference unless the errors correspond with every level-up you have.

You have a notification in your account for winning a challenge, and we do have a bug at the moment where those aren't shown, but the notification is dated 2016-09-07T05:12:15.992Z so it's unlikely to be related (too recent).

**Comment by Alys** [comment]
Here are the two screenshots from the top post, because the zoom option on the Dropbox interface isn't working well for me:

![2016-09-01 16 59 49](https://cloud.githubusercontent.com/assets/1495809/18309139/40589796-753b-11e6-859c-3cbac0935aab.jpg)
![2016-09-01 17 00 03](https://cloud.githubusercontent.com/assets/1495809/18309140/405f3790-753b-11e6-8caa-faf5783ab1eb.jpg)

**Comment by Alys** [comment]
About 48 hours ago, BrianTerrible (663f8e76-c1d5-4ef8-8ce4-a8c6c7c44313) posted the message below to the Bug guild. It might be related. I'm asking Brian about extensions. The English translations of the error messages were inserted by me from Google Translate.

"Hello, I just got an error prompt by opening the main page of Habitica. Checking the console, it seems that there are some HTTP 500 responses, probably for some web service query. The console output follows:"

```
O elemento <source> não possui o atributo “src”. Falha no carregamento da mídia.habitica.com
Houve falha no carregamento para todas as alternativas de mídia. Pausa no carregamento.habitica.com
[ The element does not have the "src" attribute. Failed to load mídia.habitica.com 
Failed loading for all media alternatives. Pause at carregamento.habitica.com ]

"Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
y/<@https://habitica.com/app-212ad8bf.js:43:12517
w.authenticate@https://habitica.com/app-212ad8bf.js:47:3878
@https://habitica.com/app-212ad8bf.js:47:5106
i@https://habitica.com/app-212ad8bf.js:7:17123
c@https://habitica.com/app-212ad8bf.js:7:15519
i@https://habitica.com/app-212ad8bf.js:7:17123
Tb/j.$injector<@https://habitica.com/app-212ad8bf.js:7:15169
g@https://habitica.com/app-212ad8bf.js:7:16758
i@https://habitica.com/app-212ad8bf.js:7:17092
ic/this.$get</</<@https://habitica.com/app-212ad8bf.js:8:8731
na/<@https://habitica.com/app-212ad8bf.js:8:3065
x@https://habitica.com/app-212ad8bf.js:6:24324
na@https://habitica.com/app-212ad8bf.js:8:3049
r@https://habitica.com/app-212ad8bf.js:7:29520
b@https://habitica.com/app-212ad8bf.js:7:28568
a/<@https://habitica.com/app-212ad8bf.js:6:30790
wd/this.$get</j.prototype.$eval@https://habitica.com/app-212ad8bf.js:9:16677
wd/this.$get</j.prototype.$apply@https://habitica.com/app-212ad8bf.js:9:16911
a@https://habitica.com/app-212ad8bf.js:6:30748
i@https://habitica.com/app-212ad8bf.js:7:17123
xa/g@https://habitica.com/app-212ad8bf.js:6:30667
xa@https://habitica.com/app-212ad8bf.js:6:30977
wa@https://habitica.com/app-212ad8bf.js:6:30200
@https://habitica.com/app-212ad8bf.js:11:1047
o.Callbacks/j@https://habitica.com/app-212ad8bf.js:3:26970
o.Callbacks/k.fireWith@https://habitica.com/app-212ad8bf.js:3:27788
.ready@https://habitica.com/app-212ad8bf.js:3:29580
I@https://habitica.com/app-212ad8bf.js:3:29750
"app-212ad8bf.js:43:12289

Houve falha no carregamento para todas as alternativas de mídia. Pausa no carregamento.habitica.com
O elemento <source> não possui o atributo “src”. Falha no carregamento da mídia.habitica.com
Houve falha no carregamento para todas as alternativas de mídia. Pausa no carregamento.habitica.com

[ Failed loading for all media alternatives. Pause at carregamento.habitica.com 
The <source> does not have the "src" attribute.
 Failed to load mídia.habitica.com failed in loading for all media alternatives. 
Pause at carregamento.habitica.com ]

Object { data: Object, status: 500, headers: tc/<(), config: Object, statusText: "Internal Server Error" }app-212ad8bf.js:45:27965
.responseError()app-212ad8bf.js:45
j()app-212ad8bf.js:9
k/<()app-212ad8bf.js:9
wd/this.$get</j.prototype.$eval()app-212ad8bf.js:9
wd/this.$get</j.prototype.$digest()app-212ad8bf.js:9
wd/this.$get</j.prototype.$apply()app-212ad8bf.js:9
s()app-212ad8bf.js:8
v()app-212ad8bf.js:8
a()app-212ad8bf.js:8

Object { data: Object, status: 500, headers: tc/<(), config: Object, statusText: "Internal Server Error" }app-212ad8bf.js:45:27965
.responseError()app-212ad8bf.js:45
j()app-212ad8bf.js:9
k/<()app-212ad8bf.js:9
wd/this.$get</j.prototype.$eval()app-212ad8bf.js:9
wd/this.$get</j.prototype.$digest()app-212ad8bf.js:9
wd/this.$get</j.prototype.$apply()app-212ad8bf.js:9
s()app-212ad8bf.js:8
v()app-212ad8bf.js:8
a()
```

**Comment by jjmcgaffey** [comment]
Yes - the red button clearing was what I meant. The only add-ons I have on the mobile browser are the video codec that comes automatically, and the Console add-on I put in to see the console - which was after I first reported this in Report a Bug. 

Ok, found and put back my level-up notifications (thank you!). And the instant I did so, I got a bunch of pop-ups including the pink one - here

https://www.dropbox.com/s/gbw7xb0mjry6q3y/2016-09-07%2017.08.37.png?dl=0

and the "won a challenge" notification. So again associated with a notification. And yes, that win was just recently (and I'd had another win, after this started but well before now, which didn't change anything).

**Comment by jjmcgaffey** [comment]
Right. So today I went back on the website, and I see from my message above that it was 8 days ago the last time I went. I got 8 small pop-ups telling me I had 282 21-day streaks (that is, all of them said the same number, the latest one). Then I got 8 large pink pop-ups; and when I'd gotten rid of those, I had to dismiss the streak notification (the big white box) 8 times. Hmm. This is not what it was doing before - has something changed in the streak notification code? - but might give a clue about the pink pop-ups, too.

**Comment by Alys** [comment]
Copied from the Report a Bug guild in case it's related (although it's could just be coincidence, and you were right to post it to the guild!):

"Another no-damage-to-boss report; I'm shown as taking part in the quest (which started yesterday), but although I've (obviously) cronned today, there's no message about me dealing damage. Several other participants have. ??"

**Comment by librarianmage** [comment]
With the new redesign, I'm no longer seeing any error messages of that type anymore. Has this been fixed?

**Comment by jjmcgaffey** [comment]
Apparently - and I hadn't been getting them for quite a while before the latest redesign. Sorry, I don't remember when they stopped.
