### ISSUE TITLE
Quest progress icon mobile issues

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica#7981]
General Info
- UUID: 8cce502f-a91c-40c2-b782-687759c6da0a
- Browser: Firefox
- OS: Android
### Description

The Quest Progress icon isn't very mobile friendly. Tapping on the icon simply loads the Party page, without ever displaying the quest progress information. In contrast, the Sync button shows the "Sync" popup while the page is syncing. One solution could be to display the amount of damage/drops alongside the icon, similar to the counts for gems/gold/silver.

On a less important note, the icon looks a little out of place in the mobile website since it is in the same row as the buttons that are lighter colored and surrounded by rounded rectangles (see below). The icon could be moved to be in the same row as the gem/gold/silver counts.

![2016_09_07_22 31 54](https://cloud.githubusercontent.com/assets/279805/18335174/4d0577c4-754b-11e6-87ae-f5a7a8eba188.png)

**Comment by Alys** [comment]
Definitely things we'd want to fix but best done in an upcoming website improvement project so I'm marking this as on hold. Thanks for noticing those problems!

**Comment by lemoness** [comment]
This is no longer relevant.
