### ISSUE TITLE
Lost Party Members

### ISSUE THREAD

**Issue by Gooseus** [HabitRPG/habitica#799]
Hey Tyler, we used to have 6 member in our party and as of yesterday we suddenly had 4.  Has a party limit been instituted or was there a glitch?  Both of the other members who were dropped are apparently no longer in a party.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
