### ISSUE TITLE
quest progress icon does not appear until some progress exists

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7990]
When you're on an active quest (or have not rejected an invitation to a pending quest), if you have not yet made any progress towards the quest today, the quest progress icon does not appear in the menu bar. It only appears after you've accumulated some boss damage or found at least one collection quest item.

This isn't a big problem for boss quests because you make progress as soon as you complete a task (including positive Habits), but for collection quests it could be hours before you find an item and it looks like a bug that the icon does not exist when you know that your quest is running.

Relevant code: https://github.com/HabitRPG/habitrpg/blob/f496a6b0c75645aa38f76600d357e291f80d4f50/website/client/js/controllers/menuCtrl.js#L37 and https://github.com/HabitRPG/habitrpg/blob/f496a6b0c75645aa38f76600d357e291f80d4f50/website/client/js/controllers/menuCtrl.js#L40

**Comment by abatula** [comment]
I can work on this if no one else has started.

**Comment by Alys** [comment]
@abatula Thank you! Comment here if you have questions or run into trouble!

**Comment by abatula** [comment]
Would you prefer the `hasQuestProgress` function to return true if the user is on a quest, regardless of any quest progress, or should there be a second function (maybe `isOnQuest`) to check if they are on a quest at all? That would leave `hasQuestProgress` in case some aspect of the site needs to know if there is progress and not just that the user is on the quest.

**Comment by crookedneighbor** [comment]
The hasQuestProgress function can be removed. All we need is a simple `ng-if="user.party.quest.key"`

**Comment by abatula** [comment]
By using `ng-if='user.party.quest.key'`, the progress icon shows up after accepting the quest but before it has started. It also starts calculating boss damage as soon I invite my party to the quest (even if it hasn't started). Is that desired behavior on the part of the quest? It is not calculated damage for the entire day, it starts from 0 when I invite the party to a new quest. I attached an image where you can see the quest isn't started but there is already pending damage.

![bossquest](https://cloud.githubusercontent.com/assets/2165770/18454178/e949c950-7910-11e6-80cb-ce8ccb401637.png)

I am guessing that the icon should not show up until the quest has actually started, correct? The damage calculation I am also guessing is either OK, or should be a different pull request.

**Comment by crookedneighbor** [comment]
You are right. It should not appear until the quest has actually started.

**Comment by abatula** [comment]
I've been looking at the code for a while, and I've come up with two options:
1. Get access to the `quest.active` attribute of the party
   - Like here: https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/quests.js#L173 
   - I'm not sure how to get the party group passed into `hasQuestProgress()`, or even if that's a good idea
2. Add a similar `active` attribute to the user's party quest information 
   - A boolean, similar to RSVPNeeded https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/user/schema.js#L393
   - This would make it easy to check if a user is on an active quest
     - Would also avoid confusing an accepted quest for an active quest, as was the problem with using `user.party.quest.key`
   - This would cause issues with any quests that are active when the code is first implemented, as it would only be set to `True` when they start the new quest
     - A work-around could be to also set the `active` status to true if there is quest progress (as `hasQuestProgress()` currently determines it. This would fix all user's `quest.active` attribute as soon as they make progress on the current quest, and could be removed from the code in the future when it is no longer needed (after all users have been updated or finished their quest.)

I think option 2 might be the better solution, but I wanted to make sure everyone else agreed before I tried to implement it. Or see if I'm missing a better third option.

**Comment by crookedneighbor** [comment]
IMO this isn't worth working on the old client now that work has started on the new client.

**Comment by abatula** [comment]
I wondered about that when all the files I was working with got moved to `client-old`. Unless someone says any differently, I will work on another issue while the new client is in progress.

**Comment by lemoness** [comment]
Quest progress is handled differently now, so I am closing this ticket.
