### ISSUE TITLE
Migrate from Jade to Pug

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7992]
Jade doesn't exist anymore due to a legal issue with it's name (see here https://github.com/pugjs/pug/issues/2184 for more info).

The new name is [Pug](https://pugjs.org/api/getting-started.html)

We should migrate to it unless we decide to ditch server side templating in the redesign (I'd like at least to do some preprocessing of templates). Note that there are breaking changes.

Regarding linting, to avoid problems with Vue we're going to use double quotes for all attributes in Pug (attr="content")

**Comment by crookedneighbor** [comment]
The only reason I haven't done this yet is because pug does not have a stable release yet. (At least, the last time I checked) 2.0.0-beta6 is the current version.

**Comment by paglias** [comment]
I got confused because Express now suggests to use Pug. Anyway yes beta-6 is still the latest release

**Comment by crookedneighbor** [comment]
Yeah. In theory it should be stable. But I'd prefer to not pin to a beta release.

**Comment by paglias** [comment]
https://github.com/pugjs/pug-lint can be used to lint Pug files and find things that needs to be changed from Jade

**Comment by crookedneighbor** [comment]
I'm :+1: on linting

**Comment by lemoness** [comment]
Is this still something that needs to be done?
