### ISSUE TITLE
Remove v2 code from /common/script

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#7993]
- Some ops/fns/... were only used in v2 and can be removed (client only code must stay for now)
- Some ops return different data if `req.v2 === true`, that code can be removed

**Comment by khipkin** [comment]
Why on hold?

**Comment by paglias** [comment]
@khipkin I wanted to check that all the stuff wasn't used on the client, I've removed the `on hold` status

**Comment by khipkin** [comment]
Okay cool. :smile: I would be interested in tackling this.

**Comment by paglias** [comment]
@khipkin sure! It's a bit boring and probably just removing code, but if you want to do it go ahead :)

**Comment by khipkin** [comment]
A bunch of files in common/script/ops contain the following comment:
`// TODO used only in client, move there?`

Do you want me to deal with this too?

**Comment by paglias** [comment]
@khipkin no, client only code should stay where it's. We'll remove it with the redesign but for now it's needed and doesn't make sense to spend time to move it to a client that'll be rewritten
