### ISSUE TITLE
npm install habitrpg?

### ISSUE THREAD

**Issue by pfraces** [HabitRPG/habitica#8]
Have you planned to offer habitrpg from npm for easy local installations?

**Comment by lefnire** [comment]
naw, doesn't really lend itself to that - it's an app, not a module. It's pretty simple to setup, I might throw in an INSTALL.txt later, but

```
git clone git@github.com:lefnire/habitrpg.git
cd habitrpg
npm install
node server.js
```

**Comment by pfraces** [comment]
>   it's an app, not a module

Good point, and installing is easy enough. Sorry
