### ISSUE TITLE
Calling /down on a daily task via the API causes XP and GP loss, not HP loss

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#800]
To begin with, I have 35.6 HP:

```
$ hrpg status
Hark, Paul Fenwick! (Lv 9)

HP: 35.6 / 50
XP: 216.5 / 250
GP: 55 | SP: 18 | CP: 96
```

I'm using a tweaked `hrpg` to clear daily tasks...

```
$ hrpg clear daily
Ouch. Taking damage for Anki...
$VAR1 = {
          'exp' => '211.5',
          'delta' => '-0.637113726072727',
          'lvl' => 9,
          'hp' => '35.6',
          'gp' => '54.5524439562129'
        };
```

Note that my XP and GP have gone _down_, but my HP is the same.

Expected behaviour: I take damage when I `/down` a daily task via the API. Calling `/down` on habits works just fine.  (I haven't tested with TODOs.)

Even better: Tasks clear (and damage the user) without needing to visit the website.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
