### ISSUE TITLE
Post Redesign Cleanup

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#8000]
The redesign will happen in the `develop` branch so the old client will stay as long as it's not complete, after it's we'll have to do a bit of cleanup.

This list is not complete, we'll probably add new items:
- [ ] Remove Bower (and relative code, post install scripts, ...)
- [ ] Remove unused assets
- [ ] Remove common code that was only used on the client (and relative tests)
- [ ] Remove `/dist`
- [ ] Remove old Grunt tasks no longer used
- [ ] Remove old client tests (integration and unit)
- [ ] Remove test/server_side, test/migrations
- [ ] Remove all exceptions to /tests and /common from .eslintignore
- [ ] /test/content -> test/common/content
- [ ] Remove browserify's code and dependency
- [ ] Remove /common/dist if we manage to put spritesmith into the build step (anyway remove the generated js)
- [ ] Remove /common/public
- [ ] Remove unused npm packages (https://github.com/depcheck/depcheck)
- [ ] update npm deps
- [ ] devDeps vs deps in package.json

**Comment by librarianmage** [comment]
How much of this is still needed/uncomplete?
