### ISSUE TITLE
Pre Redesign Steps

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#8001]
- [x] Move `/common` to `/common/website`
- [x] Move `/website/client` to `/website/client-old`
- [x] Create `/website/client` directory for new client (add to nodemonignore, ... and add eslint)
- [x] Expose `/website/client` at `/new-app` but hidden it with dev only middleware (for the beginning)

**Comment by crookedneighbor** [comment]
^ I'm working on `/common/` to `/common/website`

**Comment by paglias** [comment]
Working on `/website/client` -> `/website/client-old`

**Comment by khipkin** [comment]
Not sure how this whole "Projects" feature works on GitHub, but I think this can be moved out of "In Progress".
