### ISSUE TITLE
Big List of Redesign To-Dos

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#8003]
So we don't forget.
- [x] HTML 5 History
- [ ] members modal on front page and related urls (list here https://github.com/HabitRPG/habitica/pull/9025)
- [x] PORT /static/user/auth/local/reset-password-set-new-one before deleting old client files 
- [ ] i18n cache browser script
- [x] upgrade bootstrap and bootstrap-vue
- [ ] perf stable
- [x] mobile version
- [x] use color vars everywhere not #ssss values
- [ ] Remove shop_xxx sprites for gear and use transform: scale(RATIO)
- [ ] Add link to palette PDF in colors.scss
- [ ] analyze with `npm run build --report`
- [x] boostrap remove unused files? if SCSS not used remove it
- [x] remove unused i18n strings
- [ ] common/i18n: do not run _.template all the times, once is enough to compile the string
- [ ] e2e tests
- [x] axios vs vue-resource
- [x] Loading screen
- [ ] Splash screen for unsupported browser (and with JS disabled)
- [x] Remove `/static/front` redirect
- [x] All assets in one place (currenty website/client-old, website/assets, website/client and website/static - used only in the new client side)
- [ ] all transpiled and built files in a single places (static assets but also babel transpiled files, ...)
- [ ] decide if we need babel-polyfill (added to support Promise in PhantomJS and IE). Since it's pretty big we should just pick what is really necessary like Promise, ... Or use babel-runtime but it doesn't support external libraries like Vuex but only files that go through Babel. Should look into https://cdn.polyfill.io/v2/docs/features/
- [ ] JS split into app.js and vendor.js, do the same for CSS?
- [ ] common: remove user wrapping, do not load everything at once but only necessary modules
- [ ] i18n: separate build for each locale? if possible remove unused strings (https://github.com/oliviertassinari/i18n-extract) for example FAQs, community guidelines, .. everything not used in the app
- [ ] css: remove unused rules? (https://github.com/purifycss/purifycss-webpack-plugin, https://github.com/giakki/uncss) stylelint?
- [ ] moment: do not load all locales when loading with webpack
- [ ] css do not load unnecessary sprites (the large one is only used on the front page and on Bailey announcements)
- [ ] optimize images
- [x] lodash: import only used modules and not full module?
- [ ] remove comments from built css and html
- [ ] do not build prod client in postinstall if not in production
- [x] tree shaking with webpack2
- [x] yarn
- [ ] babili for minification and babel-env
- [ ] refactor mixins
- [ ] unhandled rejections for promises
- [ ] move analytics to server where possible
- [ ] handle errors in common code
- [ ] home page inline css and assets

**Comment by librarianmage** [comment]
Has this list been updated?

**Comment by paglias** [comment]
No but most things are still todo, let's keep this, I'll try to clean it up and split into multiple issues in a few days
