### ISSUE TITLE
Participant joins challenge, then creator adds more tasks -> new tasks aren't tagged

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#8004]
If a challenge creator adds new tasks to the challenge after participants have already joined, those tasks appear in the participants' tasks lists and have the megaphone symbol, but aren't tagged with the challenge tag.

Possible **workaround** until this bug gets fixed: The creator should make sure that the participants know that new tasks were added (for example by messaging them), and should tell them that they should look at the challenge and see which tasks are new, and that they should then find those tasks in their own task lists and tag them with the challenge tag themselves.

This bug was already described in issue #7449 , but since that issue was mainly about a different bug, I'm creating this separate issue.

The bug happened to me yesterday on the website in Chrome on Windows. It also happened to @Altariel3 who wrote [this comment](https://github.com/HabitRPG/habitrpg/issues/7449#issuecomment-222882546) on Jun 1, 2016:

> I am also experiencing this error for challenges that I joined, that I don't own. If a task is added after I joined the challenge than the challenge tag isn't associated with the task.
> 
> user ID: be317a32-c027-4032-bbd5-25ccb21eb912
> Browser: Google Chrome Version 50.0.2661.102 m
> OS: Windows 10, 64-bit

Many challenge owners write in their challenge description _"New tasks will be added later!"_ or similar, and then the participants click the tag occasionally and look for those new tasks - but because of the bug, they don't find them now because they aren't tagged correctly. And having to message every challenge participant and explain the bug and the workaround to them whenever you add a new task to a challenge is a lot of work. So this is a rather inconvenient bug.

**Comment by cincospenguinos** [comment]
I can probably do this one. Is it alright if I take it?

**Comment by Alys** [comment]
@cincospenguinos Yes, thank you!  Comment here if you have any questions.

**Comment by librarianmage** [comment]
@cincospenguinos Are you still working on this?

**Comment by lemoness** [comment]
I've updated the labels on this issue.
