### ISSUE TITLE
Players should be able to flag their own messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8005]
Currently, it is not possible to flag a message that you posted.

It should be possible. (E.g., when hiding posts you made in response to a user who has revealed themself as under-aged.)

This is probably an easy matter of just removing an `if` clause from the code so I'm marking this as entry level coding.

**Comment by crookedneighbor** [comment]
For the person working on this, I believe there is both a client side and a server side component to this.

**Comment by cincospenguinos** [comment]
Is someone already working on this? Is it cool if I do it?

**Comment by Alys** [comment]
@cincospenguinos It's all yours! Thank you!
