### ISSUE TITLE
Deleted tags are not removed from tasks

### ISSUE THREAD

**Issue by JSchneidler** [HabitRPG/habitica#8008]
General Info
- UUID: b1f8093a-76b7-4f80-95ce-5c00bec74c0a
- Browser: Firefox 48.0
- OS: Ubuntu 16.04
### Description

When a tag is assigned to a task and that tag is then deleted, the task still contains a reference to the deleted tag. This causes tasks to falsely display the tagged icon even if they have no existing tags. Once deleted, the tag cannot be removed from the task either.
#### Steps to reproduce:
1. Create task "test task"
2. Create tag "test tag" and save changes
3. Assign tag "test tag" to task "test task" and save changes
4. Delete tag "test tag", save changes.
#### Expected results:

Icon notifying that "test task" is tagged should disappear, tag id should be removed from corresponding entry in db.
#### Actual results:

Icon notifying that "test task" is tagged remains. In database, "test task" contains reference to the id of the deleted tag.

**Comment by Alys** [comment]
Can you please click the sync button on the top right of the website (the double curved arrows icon) and tell us if that causes the tag icon to be removed from the task?

It does when I tested this and also the database did not contain reference to the ID of the deleted tag (it was removed even before I did the sync).

If you can confirm that syncing fixes this for you, then all we need to do is force a sync after tag editing is finished, which we can add to https://github.com/HabitRPG/habitrpg/issues/7820

**Comment by JSchneidler** [comment]
Yes, I should have mentioned syncing does fix it. That sounds good, I'll include the fix in a PR for #7820.

**Comment by Alys** [comment]
I'm closing this since we have https://github.com/HabitRPG/habitrpg/issues/7820
