### ISSUE TITLE
Purchasing items disables item comments until refreshing

### ISSUE THREAD

**Issue by UnicornTamer** [HabitRPG/habitica#801]
1. Hover over an item's comments, works fine
2. Purchase an item
3. Hover over another item's comments, they don't show
4. Refresh, they work again

Chrome Version 26.0.1410.63
Mac OS X: Version 10.8.2

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
