### ISSUE TITLE
Party Members Disappear from Website Header

### ISSUE THREAD

**Issue by Impendingdoom777** [HabitRPG/habitica#8011]
@Alys  
![habitica](https://cloud.githubusercontent.com/assets/22186177/18498782/d4ab59e8-79fe-11e6-9ef5-b78abcd7f0af.jpg)

General Info
- UUID: 
- Browser: 
- OS: 
#### Console Errors

User:Hey guys, I added a new person to my party, but now all of their avatars have disappeared from the bar. All I see is myself. How do I get my friends back lol

Alys :Have you tried reloading the website? A reload is a good thing to try before reporting any problem. Comment here again if that doesn't help. No need to post if it does.

User:Yes, I have reloaded, logged out, and closed the tab, but no results :(

Alys: Can you please show us a screenshot of what you see (you can upload it to any file or photo sharing site and put the link here, or email it to admin@habitica.com and mark it attention Alys)? Also tell us which browser you're using on which platform (Windows, Linux, etc).

User: Sent Screen Shot https://docs.google.com/drawings/d/1Sbk0D3AliXjRleQwyXe0nuQEVqxOA7TtR5I7GS0xQuY/edit    and I'm using Windows.

Alys: Odd. You're definitely still in your party. Can you please take a screenshot of the party page, especially showing the list of members in the left-hand column?

User: Sent Screen shot https://docs.google.com/drawings/d/1cePVUEGF3UroHGiPzvF2xijq6Xce18UIAHkxx0mCQr4/edit

Alys: I'm sorry, I don't know what's causing your website header to not show your party members! We'll need to investigate that properly. Can you please report it in a new issue on GitHub? You can copy in your messages from here and the links to the screenshots. 

9/25/16 Hey guys! I am having the same problem that I always have when I add a new member to my party. All of my party's avatars disappear and I can only see me. I'm using windows and firefox, but I also tried chrome. The change didn't fix it. I have tried logging out, closing the tab, and closing the window. 

Here is a screen shot of both my screen now and my party. screen shot of party https://docs.google.com/drawings/d/1Mr3XEWvNKuL3UnES5sdVrA2utFE4WT1e_oKm35GrUKw/edit?usp=sharing -a day ago+1            

Screen now https://docs.google.com/drawings/d/1-MxjwRfH_S4BZ31oAyiGtQv7uEw-VUnWRQy0F2O2hT0/edit?usp=sharing -a day ago+1

**Comment by paglias** [comment]
@Impendingdoom777 can you tell us when the problem started to appear?

**Comment by paglias** [comment]
Also, I'd try to log out and then login

**Comment by Impendingdoom777** [comment]
I have tried logging out and back in. It started up on September 12th sometime between 10 P.M. and 12 A.M. Central time

**Comment by paglias** [comment]
@Impendingdoom777 can you give a look at Chrome's console to see if there's any error? Ctrl+Shift+J

**Comment by Impendingdoom777** [comment]
Ok that was actually the problem. It will not show up on firefox, but when I used chrome I can see them.

**Comment by paglias** [comment]
@Impendingdoom777 okay, try clearing your cache and following the istruction at https://habitica.com/static/clear-browser-data while on Firefox

**Comment by Impendingdoom777** [comment]
I have recently added two more people into my party and the issue is happening again. This time this previous fix didn't help.

**Comment by paglias** [comment]
Have you tried clearing the cache? Also you should tell us if there are any errors in the browser console (instructions above)

**Comment by Impendingdoom777** [comment]
I have tried clearing my cache, but that did not help it. This is what the ctrl+shift+j command brought up https://docs.google.com/drawings/d/1VXTHgD8WnR-5garz6kINESPovVRNlb8Ha15xq9iwZ8o/edit?usp=sharing

**Comment by Alys** [comment]
@Impendingdoom777 Can you please add your User ID to this issue? You can get it from Settings > API on the website. "Settings" is the gear-shaped icon. Also, would you mind editing your original post to replace "Tech Support" with my name please? Those comments were made by me, and having my name there clarifies that, might help in future if we need to refer back to this issue and remember who said what, and is not impersonal.

@paglias There's another report of this in the Bug guild from Dan Blakeslee (d554d21e-2fab-43d6-8deb-71663cdc8a7f). I've asked them to post here.

**Comment by Impendingdoom777** [comment]
d554d21e-2fab-43d6-8deb-71663cdc8a7f
I have updated the comment.

**Comment by paglias** [comment]
@Alys The fact that it happens only on the header and the console error makes me think it's something on the client side. I'm not sure why it's happening though

**Comment by Alys** [comment]
@Impendingdoom777 Can you turn off all extensions in your browser and see if that makes a difference? This is only temporary while we work out if an extension might be causing the problem. Alternatively, open Habitica in incognito mode or private mode, if you have your extensions set to not be active in that mode.

**Comment by Impendingdoom777** [comment]
@Alys I did both. Unfortunately, it did not fix the problem.

**Comment by paglias** [comment]
Your party members have your same problem?

Il 27 set 2016 21:38, "Impendingdoom777" notifications@github.com ha
scritto:

**Comment by Impendingdoom777** [comment]
@paglias No their accounts all display the party members

**Comment by sudoct** [comment]
UUID: 5f2ffd68-41e4-4e0e-9c3a-ed9d7ed035aa
Browser: Google Chrome
OS: Mac OS 10.9.5

I had tried Mozila Firefox, Opera and Safari, it does not work in any browser.
I hope that you can fix the problem ASAP. Thanks.

**Comment by Impendingdoom777** [comment]
Has there been any breakthroughs recently?

**Comment by paglias** [comment]
@Impendingdoom777 no, i'm sorry :/ We cannot find out what's going on. Can you try changing the party members ordering from the party page?

**Comment by Impendingdoom777** [comment]
THIS BUG IS FIXED I logged in on another computer and my party showed up. I then refreshed the page on my home computer and the party reappeared.

**Comment by Alys** [comment]
@kikitan99  Are you still unable to see the party members in your header?

**Comment by librarianmage** [comment]
Is this still an issue?
