### ISSUE TITLE
To-Dos not saving Due Date changes

### ISSUE THREAD

**Issue by rosstavo** [HabitRPG/habitica#8012]
General Info
- UUID: 5c2b354c-d5f1-4f54-8ab0-52136fe70309
- Browser: Chrome 52
- OS: OS X El Capitan
### Description

When adding or editing a To-Do task, the due date does not save.

While editing the task, the new due date will appear as expected alongside the task name at the top, and the field will be populated, but when I confirm my edit, the due date disappears from beside the name, and the due date field is empty when I attempt to re-edit.

I also have a To-Do that already has a due date on it, so I attempted to change the date on this task, but my changes were not saved, and the task retained its old date.
#### Console Errors

None

**Comment by ShulamitLH** [comment]
I'm having the exact same problem. I have tried to change the due-date of a to-do, and it won't change.

**Comment by paglias** [comment]
Confirmed, we'll try to fix this very soon, sorry about it!
