### ISSUE TITLE
in party members box, link and underlining are inconsistent 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8016]
As reported by DStroyer (8e2cbccd-d576-4db1-9672-03cd6d2d71d7) in the Report a Bug guild:

**In the party window, inside "Members", only the name of the user is linked with clickMember(member._id, true), but not the (XX HP) part, however the whole string is underlined and looks like a link. Clicking on the HP value doesn't do a thing, that was confusing for me until I saw the clickMember() thing.**

This could be fixed by either reducing the underlining to be only the person's name, or by making all of the underlined text clickable.

**Comment by AndrewPomorski** [comment]
Hello, I'd like to try and fix this one. Is that alright? :)

**Comment by Alys** [comment]
@AndrewPomorski That would be great, thank you!

**Comment by AndrewPomorski** [comment]
I've got everything up and running. I should be done soon.

**Comment by RussWilkie** [comment]
Is this still an issue?

**Comment by Alys** [comment]
@RussWilkie Yes

**Comment by RussWilkie** [comment]
@Alys Would it be cool if I give it a shot?

**Comment by khipkin** [comment]
@AndrewPomorski Are you still working on this?

**Comment by Alys** [comment]
@AndrewPomorski If you're still working on this, let us know how it's going in the next day. If you've run out of free time for it, that's fine - we know how that goes! :) We'll let @RussWilkie take it on if you're not still available for it.

**Comment by Alys** [comment]
@RussWilkie If you'd like to take this on, please do!

**Comment by RussWilkie** [comment]
@Alys Fixed it, how would I go about submitting my changes? Do I just push it or do you guys want a snippet of the modified code?

**Comment by khipkin** [comment]
@RussWilkie Push your changes to your fork of the repository and then [create a pull request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by RussWilkie** [comment]
Not seeing my addition to the list of pull requests so I'm not sure if my pull request went through successfully. If not I'll attempt another pull request.

**Comment by khipkin** [comment]
Hmm I'm not seeing it either.

**Comment by Alys** [comment]
@RussWilkie I saw email notifications for a couple of commits you'd made, but we do need a pull request. Does the link that @khipkin provided help (https://help.github.com/articles/creating-a-pull-request/ )? Let us know if something's going wrong with that or if the instructions aren't clear.

**Comment by RussWilkie** [comment]
@Alys @khipkin Hello, thanks! I made the pull request again and it went through:

https://github.com/HabitRPG/habitica/pull/8155
