### ISSUE TITLE
Javascript: Volume calculator from width, length and depth

### ISSUE THREAD

**Issue by Egretta** [HabitRPG/habitica#8019]
hi experts! 

I don't know is this a right section to ask your help, but i could'nt find better place too.
So, i need to create an online calculator from these inputs: width, length and height, and display the answer in **m³.** The length and width measurs are in meters, the height (this is a tricky part) in centemeters. 

Found the base of that code from internet and modified a bit. [look into jsfiddle ](https://jsfiddle.net/Gallex/0L8s0ngg/). Basically it does what i need – calculates the sum from three values (first two are in meters, third in centemeters), but i would like it to be more simpler. I don’t want “select options” at the end of a height (thickness) field. this value: 

```
..else if(select_val == "meter"){
    result = result/100;
    $("#answer").text(result).append(" m<sup>3</sup>");;...

```

must have programmed into code by default! 
please help me to simplify that code! or maybe you can provide more elegant solution?

my english is not good, but i still hope you understood my request

**Comment by crookedneighbor** [comment]
This is not the appropriate place to ask for help with this. If you'd like some Habitican's help, try asking in one of the developer focused guilds on the site.

**Comment by Egretta** [comment]
could you guide me (provide a link) to right place?

**Comment by crookedneighbor** [comment]
Here's a list of the public guilds in Habitica: https://habitica.com/#/options/groups/guilds/public

You might be interested in the [developers guild](https://habitica.com/#/options/groups/guilds/e655bb46-96ec-4d8b-b40d-f195063904c8) or the [JavaScript guild](https://habitica.com/#/options/groups/guilds/349a36c3-66f3-4bf8-91b6-475056d9b6bb)
