### ISSUE TITLE
Item purchase didn't subtract any gold

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#802]
Today I purchased the Sword. I think I did see the pop-up that it cost me money (I didn't check money right away). But a bit later, I noticed I still had the same amount of gold, even though now I only have the option to buy an Axe, so the order did go through.
Maybe relevant: I had both the beta and normal server open at the same time while this happened, and I think I was using the beta server at the time.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
