### ISSUE TITLE
Slow Refresh in Vivaldi

### ISSUE THREAD

**Issue by jtgithub2016** [HabitRPG/habitica#8020]
General Info
- UUID: e44e6069-2e30-49cf-ab49-db41d3134045
- Browser: Vivaldi
- OS: Windows 7
### Description

I've done enough damage to kill the monster in my party's quest, and I've taken damange.  I've since created to dos, completed to dos, cast spells for my party, and the party page doesn't seem to be updating, so it shows the Rat King as still alive.

![image](https://cloud.githubusercontent.com/assets/18677807/18557969/b5b245aa-7ba3-11e6-8da0-3b585bedae48.png)

**Comment by paglias** [comment]
@jtgithub2016 is the chat updated? Also, what happens if you reload the page?

**Comment by Alys** [comment]
@jtgithub2016 The database shows more recent messages than that, and the quest has finished. What happens when you click the button just under the chat box on the far right?

**Comment by Alys** [comment]
Ah, actually, looking at timestamps, you cronned at about the same time that you posted this issue. Had the party page been open in your browser for a while before then? It might just be that it hadn't been synced recently and so hadn't picked up the latest changes. Does that sound likely?

**Comment by jtgithub2016** [comment]
Well, I got it updated, so I guess we're okay on that front.  I also see
that a third party member (not just me and Shioki) did more than 20 points
of damage to the team, which is something I hadn't noticed before.  So I
guess it's sort of a miracle any of us lived.

Thanks again.

**Comment by Alys** [comment]
Thanks for letting us know! If you notice any other odd behaviour, drop in to the Report a Bug guild and tell us about it there. That's usually faster for you and it also lets us see some information about your account immediately. You can get to it from the website's Help menu.
