### ISSUE TITLE
link to information about pet food preferences to make feeding easier

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8023]
On the Pets page, at the top of the food box (just below where it says "Food and Saddles", there should be a link to the wiki page that describes which foods are liked by which pets. The page's URL is http://habitica.wikia.com/wiki/Food_Preferences

The text could be something like:

[Learn about your pet's food preferences.](http://habitica.wikia.com/wiki/Food_Preferences)

Other suggestions welcome since that's a bit bland.

**Comment by Ozzystrasza** [comment]
Suggestion:
[Not sure what to feed your pet? Click here](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by salaxander** [comment]
I'd love to tackle this issue :) Let me know if that's alright!

**Comment by khipkin** [comment]
"Not sure what to feed your pet? Click here to learn more."

**Comment by Alys** [comment]
@salaxander Please do! Thanks!

**Comment by salaxander** [comment]
@Alys Got things up and running locally! Just taking some time to familiarize myself with the codebase :) I'll update when I've made some progress

Thanks!!

**Comment by jakers1776** [comment]
Is this still an open issue? I'd love to add a page if nobody has solved it yet.

**Comment by Alys** [comment]
@salaxander How are you going with this?

**Comment by 32gits** [comment]
I would love to do this as well if I could. I am in an open source class and picked Habitica as my project I want to contribute to. If not this then hopefully another minor change in the next couple weeks. I keep getting beat to the punch!

**Comment by TheJadeFox** [comment]
Awww....What **does** my pet like to eat?

[Awww....What **does** my pet like to eat?](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by supercat14** [comment]
What about:[ What will my pet **eat**?](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by TheJadeFox** [comment]
[The secret to what food your pet really likes](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by TheJadeFox** [comment]
[The _Secret_ to what food your pet really likes](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by TheJadeFox** [comment]
[The **_Secret**_ to what food your pet really likes](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by TheJadeFox** [comment]
I like the last won the best but you could also give a heads up ....

**Spoiler alert** : [Which foods go best with which pets?](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by cmorr7** [comment]
"Best cuisines for your little mean things"

**Comment by tt-rasm** [comment]
Is this still being worked on? If not, I'd like to tackle it.

**Comment by Alys** [comment]
@Tallestthomas Thanks! It's yours now.

@lemoness Do you have a preference for the wording?

I think my favourite is [Awww....What **does** my pet like to eat?](http://habitica.wikia.com/wiki/Food_Preferences)

**Comment by lemoness** [comment]
I think "What does my pet like to eat?" is best, though I'd remove the "Awww" section.

**Comment by TheJadeFox** [comment]
Thanks!  😊

**Comment by tt-rasm** [comment]
@Alys Awesome, I'll get on it in a bit, going with the "What does my pet like to eat?" wording

**Comment by TheHollidayInn** [comment]
Fixed via #8268
