### ISSUE TITLE
"String 'classBonusText' not found." message on Stats page

### ISSUE THREAD

**Issue by scbaker** [HabitRPG/habitica#8026]
Hovering over the "Class Bonus" tooltip on the stats page results in a "String 'classBonusText' not found." error message:

![image](https://cloud.githubusercontent.com/assets/11615786/18590539/19ec7910-7be4-11e6-8285-36b351867ade.png)

**Comment by khipkin** [comment]
I'm not seeing this issue. 😕 _(edit: on the live site)_

**Comment by khipkin** [comment]
Also, @scbaker, did you notice this issue on the live site or on your local install?

**Comment by crookedneighbor** [comment]
I've reproduced this.

**Comment by scbaker** [comment]
This is on the live site.  I don't have a local install.  Another member (akirassasin) also reported it in the Bug report guild about 4 hours ago.

edit: 
Searching the GitHub repository suggests that the reason the website can't find classBonusText is indeed because it isn't defined anywhere.  I get zero results.

It's also kind of weird that this tooltip says "This item matches your class, so it gets an additional 1.5 stat multiplier," the same as the tooltips on the class equipment.  Is that what it's supposed to say?

If not, I wonder if the stats page is somehow pulling a variable from one of the gear files instead of the stats file?  Things called "classBonus" exist in the various gear JSON files, as well as a function in the statServices JS files.

**Comment by Ozzystrasza** [comment]
This happens for me too. And I agree with @scbaker that it's weird to show that message for the bonus tooltip. That's the same message that shows on the items that give the bonus, I believe it's showing there unintentionally.

**Comment by SabreCat** [comment]
The trouble is here: https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/stats/mixins.jade#L11

The mixin constructs a tooltip with `classBonus` as the heading, and `classBonusText` as the content, but the latter doesn't exist.

**Comment by crookedneighbor** [comment]
Pretty sure this was my bad. I'll fix it.

**Comment by scbaker** [comment]
Although this is now working, just wanted to note that the top part of the tooltip is still showing the "This item matches your class, so it gets an additional 1.5 stat multiplier" message from the equipment page instead of calling up the classEquipBonus string from the code linked by @crookedneighbor.
