### ISSUE TITLE
lost todos

### ISSUE THREAD

**Issue by kriscrat** [HabitRPG/habitica#803]
I randomly lost a bunch of Todos.  As far as I can tell, all the ones I've added in the last week or so are gone.  Is there any way to restore them?  I had some stuff for work saved in the notes.  :/

**Comment by lefnire** [comment]
can you name one? the exact text, so i can do a mongo search?

**Comment by kriscrat** [comment]
I have long titles,  but I'll try! 

S 4/14 act training

D 4/15 4:30 Amelia c/t/prep

From my Android phone on T-Mobile. The first nationwide 4G network.

-------- Original message --------

**Comment by lefnire** [comment]
can you try now on beta.habitrpg.com? I pushed the above commit which restores missing tasks. It's issue with habit since the dawn of time, but I thought we'd solved it so I previously moved it to the cron function (meaning your tasks should have been restored tomorrow morning, but that's not acceptable obviously). I made a backup of the database in case we need to revert anything.

Now, I noticed in the database that you have multiple hundreds of tasks. I'm not sure how well derby can handle that many dynamic bindings in the html (since each task has multiple bindings per, as well as multiple model listeners). How do things perform on your end?

**Comment by kriscrat** [comment]
Yaaaaay!  thank you.  

All of my tasks have reappeared in both beta.habitrpg.com and habitrpg.com.  They have appeared at the bottom instead of at the top, but I can handle moving them around.  

I am not sure how many tasks I have, but that seems right!  Things perform well enough most of the time.  I LOVE having my crazy todo list in game form!  Things do get laggy sometimes, and I have to refresh to reconnect frequently.  Would it help if I cleared my completed tasks?

**Comment by lefnire** [comment]
Ok, made one final edit. Double check that everything is kosher, and then yes - I'd recommend clearing completed. Over time I'll be moving as many dynamic bindings out to static bindings as is functional, but at present most things int eh interface are dynamic bindings. A single task has about 4-5 bindings, plus 4-5 listeners - multiply that by 300, and every click or drag could cause some major slowness (on the client side only, so as long as you're not experiencing too much pain then :+1: ) Clearing your completed should help with that.

You must be stoked for tags, lol!

**Comment by Shaners** [comment]
Oh wow didn't realize I had about 153 completed tasks clogging things up. Cleared them and now I can drag Todos around to rearrange them. Previously it would just hang there forever when click dragged in chrome but worked fine in firefox so I just thought it wasn't supported for chrome... 

How hard would it be to implement an archive completed tasks button? This feature might remove all your completed tasks from the main interface and store them the be read somewhere in the profile. Could include name of task, details, creation date, priority, and completion date. I was kind of sad to see them all go so I saved them into into a text file!

**Comment by ghost** [comment]
Having an archive of completed tasks, that doesn't do any binding would be nice :+1:

**Comment by lefnire** [comment]
The easier temporary solution for now will be to remove all dynamic
bindings (save Title) on the "completed" task templates, then I'll
implement the recommended.

**Comment by kriscrat** [comment]
I am! I work multiple jobs, so I use a code for each and H for home so I know what to ignore when.  A possible future feature idea: ability to hide certain categories of todos, so when I'm at job1, I could filter to see only tasks for job1. 

From my Android phone on T-Mobile. The first nationwide 4G network.

-------- Original message --------

**Comment by lefnire** [comment]
https://trello.com/card/tags-categories/50e5d3684fe3a7266b0036d6/43

**Comment by kriscrat** [comment]
gorgeous!
