### ISSUE TITLE
Advanced Options collapse setting not working

### ISSUE THREAD

**Issue by ZeekDaGeek** [HabitRPG/habitica#8033]
General Info
- UUID: 57fb0d85-dbcd-474d-923c-e32d95a704b6
- Browser: Google Chrome
- OS: Windows 10
### Description

The "Advanced Options in tasks start collapsed" option seemed to be bugged. Mine is disabled (unchecked) and yet when I _CREATE_ a new TODO "Advanced Options" is always collapsed. Editing a TODO seems to properly default to expanded.

**Comment by imwangpan** [comment]
me too.
Browser: Google Chrome
OS: Windows 10
