### ISSUE TITLE
Collection quest progress sparkle does not update without sync or page refresh

### ISSUE THREAD

**Issue by thebat137** [HabitRPG/habitica#8038]
### General Info
- UUID: dea8a9e8-c084-438a-9a14-7fe96a73fd0a
- Browser: Firefox ESR 45.3.0
- OS: Debian Linux
### Description

(Copied from the bug guild, as requested by @Alys.)

I love the new quest progress sparkle thing. However, it seems like it's falling prey to that common page update issue --- sometimes it does not update until I hit the sync button or reload the page in my browser.

This morning I did a few tasks and collected 3 items for my current collection quest (according to the sparkle).  Then I did a whole bunch more tasks at various points during the day, but the sparkle kept telling me I'd only collected 3 items.  I thought that was weird, so I refreshed the page, and then it told me I had 24 items.  None of my other character attributes (gold, experience, mana, drops, etc.) seemed to be failing to update, although party/guild chat messages do also seem to require me to click the ""Fetch Recent Messages" button.  I don't know if that's related or not.  The problem does seem to have continued all day, though --- I can still replicate it now by doing a few tasks, seeing the lack of change in my reported quest progress, and then refreshing and seeing a change.

Anyway, thanks for adding the sparkle.  It is really great!

**Comment by Alys** [comment]
A second report of this from cTheDragons (bc10ec41-4213-4482-bbb8-558e3c3ea8d5):
"The damage icon in the toolbar does not always report correctly particular for collection quests. IF I look at the DDT now it states I have found 4 items for today for my quest, but on the toolbar is 3. This is despite checking items off on the website only today."

**Comment by thebat137** [comment]
Yeah, I forgot to mention that all of my activity when I was seeing this problem was through the website, no app use involved.  Also, it does seem like at least the first few tasks of the day (and possibly occasional others, not sure) will register without manual sync --- when I checked off my first couple tasks this morning, the quest sparkle showed up without manual sync, indicating that I'd found 1 item.  But subsequent finds didn't show up until I synced manually.  So it's not a completely consistent failure to update ever, it must only fail under some specific conditions.

**Comment by Alys** [comment]
To anyone working on this, note @khipkin's suggestion in https://github.com/HabitRPG/habitrpg/issues/8046#issuecomment-248515835 that these two issues might be caused by the user's party object not having the most recent data (that's not confirmed but it sounds like a good place to start looking).

**Comment by thebat137** [comment]
I just finished my collection quest (Golden Knight Part 1) and started a boss quest (Golden Knight Part 2).  I don't seem to be seeing the problem occurring with this new quest.  I also seem to recall that I wasn't seeing it with the boss quest I was doing before Golden Knight Part 1.  So I think it's possible that the problem may be restricted to collection quests (as the coincidence of my report and cTheDragons' report might seem to suggest).

**Comment by crookedneighbor** [comment]
It is only collection quests.

**Comment by thebat137** [comment]
Just noticed something interesting today.  My party started a new collection quest this morning, and, as has been usual, the progress sparkle wasn't updating (or even appearing) even though I got the little green popups saying that I'd collected quest items.  But then I cast a party-effect spell (Intimidating Gaze), and all of a sudden the progress sparkle popped up and showed the correct number of collected items (as verified by a page refresh afterwards).  This seems to me (in my vast ignorance of the underlying code) like it might help confirm the connection to outdated party object data?

**Comment by Yutsuten** [comment]
Is someone working on it? I'll would like to try fixing it.

**Comment by Alys** [comment]
@mateus-etto It's all yours. Thank you! Comment here if you have questions.

**Comment by Yutsuten** [comment]
@Alys I found 2 ways to solve this, one of them is harder to do, and requires an http request. The easier and fastest one is to increment the _user.party.quest.progress.collectedItems_ when a quest item was found.
For now I'll PR the easier and fastest solution. If that isn't enough, please tell me how I could make an http request through the API to get the updated value of _collectedItems_ from the server.
