### ISSUE TITLE
E2E tests for new client

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#8039]
They're excluded from `npm test`.

We also have to decide whether to use Nightwatch (we're having problems running it on TravisCI) or Protractor.

Anyway it doesn't makes sense to write them until the UI is ready.

**Comment by lemoness** [comment]
Has this been addressed already?

**Comment by paglias** [comment]
Not yet

**Comment by librarianmage** [comment]
Should this still be on hold?

**Comment by paglias** [comment]
Yes because we haven't decided what to test

**Comment by Alys** [comment]
copying from https://github.com/HabitRPG/habitica/issues/7698 (now closed):

"Re-Enable End to End Tests 
The helper file in test/e2e/helper.js may need to be adjusted."
20 June 2016

**Comment by Alys** [comment]
related: https://github.com/HabitRPG/habitica/issues/9276

**Comment by Alys** [comment]
When we're ready for e2e tests to be written, @kartikadur has suggested that it be done for this Dailies sorting bug: https://github.com/HabitRPG/habitica/issues/9582#issuecomment-367226321

**Comment by paglias** [comment]
I'm removing nightwatch and related deps for now (they're outdated anyway)

**Comment by paglias** [comment]
Closing this for now as we don't plan on adding e2e tests for now
