### ISSUE TITLE
Equiment not showing on Avatar

### ISSUE THREAD

**Issue by kinggre** [HabitRPG/habitica#8042]
Equipment, when selected, does not show up on my daughter's avatar.  Her email is kbsbpp@gmail.com.  

She is able to customize the avatar (shirts, hair, etc.) as well as choose mounts and pets.  But, when selecting any equipment (weapons, armor, etc.), it does not display.

<img width="847" alt="screen shot 2016-09-20 at 11 06 37 am" src="https://cloud.githubusercontent.com/assets/16153595/18676103/7bb91338-7f22-11e6-8084-2f7bc44c98b3.png">

**Comment by paglias** [comment]
@kinggre from your screenshot it looks like the Costume feature is enabled. That means that while you daughter is in fact equipped with the items for the game purposes (damage calculation...) they won't show on the avatar. 

The items shown on the avatar can be selected in the Costume section in the right side of the screen. If you don't want to use a costume and simply have all the equipped items shown on the avatar, untick the "Use Costume" checkbox
