### ISSUE TITLE
health in party doesn't reflect actual health.

### ISSUE THREAD

**Issue by hcorion** [HabitRPG/habitica#8046]
General Info
- UUID: 48794933-9b73-4b05-8efd-f44fde5aedf3
- Browser: Google Chrome Version 55.0.2866.0 canary (64-bit)
- OS: Windows 10 64-bit build 14393
### Description

As shown in the picture below, the displayed health in my party is not the same as my health. I did just level up and got my health reset. Just a cosmetic change, not super important.
![habitica-bug](https://cloud.githubusercontent.com/assets/9814000/18694641/9b0adfda-7f60-11e6-9f99-43105f21172a.png)

**Comment by khipkin** [comment]
I think that maybe this issue and #8038 are caused by the user's party object not having the most recent data.

**Comment by khipkin** [comment]
Another example of weird partial-party-sync behavior: 
![image](https://cloud.githubusercontent.com/assets/5641207/20397372/7854d9b2-acb7-11e6-9b38-8fa4077d3330.png)

**Comment by paglias** [comment]
That's a bug because with real time chat when you get a system message the party get synced and so it should update the quest status. not sure why it doesn't.

**Comment by SabreCat** [comment]
Quest readouts seem to lag behind updates in general. When you start a quest, it can take a hard refresh before the invite list is replaced by the active quest data, for instance.

**Comment by khipkin** [comment]
I commented on #7697 since it's more immediately relevant there.
