### ISSUE TITLE
Issue with wrong pets being displayed

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8049]
General Info
- UUID: d0e00de7-81e0-43b9-90ef-6ba794dbc40a
- Browser: Chrome
- OS: OS X

Description:
My pet section is showing pets that I don't have. In reality I only have the basic pets although more rare pets are being displayed now. When I equip one of the pets that appear there now it shows in my browser but on my phone it shows up as a pet that I actually have. My display picture is also messed up in browser.

Pictures:

http://i.imgur.com/ZmvOiwY.png

http://imgur.com/V4xIhh1

Thanks!

**Comment by crookedneighbor** [comment]
Please refresh. It should be fixed now.

**Comment by vikingmomo** [comment]
I tried that, it doesn't work.

**Comment by ghost** [comment]
Thanks!
