### ISSUE TITLE
Choosing a class after using Orb of Rebirth costs gems

### ISSUE THREAD

**Issue by Merave1** [HabitRPG/habitica#8053]
General Info
- UUID: User ID: 7583232e-3233-4ce6-81de-8ac8b67f9a4b
- Browser: Firefox
- OS: Window 7
### Description

I've tried to choose a class after using the Orb of Rebirth to re-birth. It let me choose one (Healer) but took 3 Gems. Can't understand what happened because the first time one chooses a class it's supposed to be free.

**Comment by Alys** [comment]
@Merave1 I'm looking into this and there do seem to be odd things in the logs for your account around that time, which I'll write up here, but firstly, did you notice anything unusual about Habitica on the day that you chose your class, especially around the time of the class change itself. For example, were you experiencing any unusual slowness, or red error message notifications, or any kinds of actions that you took being duplicated, or being undone, or did you see two notifications about being able to choose a class, or did you have any trouble logging in or remaining logged in? Anything at all that seemed wrong or exceptional, apart from the class change costing gems?

**Comment by Merave1** [comment]
I get red error messages most of my days in habitica (I usually refresh the page when it happens). I selected the Enable Class System option but nothing happened so I had to click it again. This page appeared where I have to select my class and clicked the healer. It disappeared and I went to my Task page to start buying my old Healer Equipment. Then appeared again a page to select my class (I guess it didn't registrate my class) so I had to click the healer option again. 
Sometimes it takes the site some time to get that I clicked on something so I'm used to it. I usually just use "fix character values"

**Comment by Alys** [comment]
@Merave1 Thanks very much for those details! That matches what I'm seeing in the logs. I've just given you 3 gems.

---

Technical details for admins and devs (Merave1, you can ignore the rest of this post if you wish to, although you're welcome to ask questions about it if you're curious!):

I can't replicate the bug in my own test account but in the Amplitude logs for Merave1's account there's clear signs of it, although I don't think it's directly related to the Rebirth or class change code specifically. 

The Rebirth happened at Jul 30, 2016 6:43:30 pm UTC, with gemCost 0. There's no signs of that going wrong in any way.

There are two recent "change class" events, one at Sep 22, 2016 1:55:12 pm UTC and the other seven minutes later at Sep 22, 2016 2:02:45 pm UTC. Both listed the following data identically:
- Platform: Web
- Class before class change: Warrior
- class chosen: Healer
- acquireMethod: Gems & gemCost: 3 (FYI, from my test, that data is always reported even when the cost is zero; I've logged https://github.com/HabitRPG/habitrpg/issues/8057 to help us better track gem loss)

More importantly, there's MANY login events shown in Amplitude ([e.g.](https://amplitude.com/app/132025/activity/search?userId=7583232e-3233-4ce6-81de-8ac8b67f9a4b&eventData=eyJ1dWlkIjoiM2RiYzlhMjYtODBjZC0xMWU2LWEyNDYtMjIwMDBhMWYwNmE3IiwiZXZlbnRJZCI6NzYwMzcwNDE0LCJjbGllbnRFdmVudFRpbWUiOiIyMDE2LTA5LTIyIDE0OjAyOjQ1LjgyMTAwMCIsIm1heFNlcnZlclVwbG9hZFRpbWUiOiIyMDE2LTA5LTIzVDA2OjEzOjEzLjg2OFoiLCJjdXJyZW50UGFnZSI6MCwiZGF0ZSI6bnVsbH0)):

![image](https://cloud.githubusercontent.com/assets/1495809/18813207/7bc7ccd6-8335-11e6-946b-0a804bd355a8.png)

![image](https://cloud.githubusercontent.com/assets/1495809/18813215/c3534f26-8335-11e6-959f-66fd38ba6fd2.png)

That frequency of logins continues back for many days. I suspect it's related to the frequent red error messages that Merave1 is getting.

**Comment by Alys** [comment]
@Merave1 I'd like us to work on stopping those red error messages you get so often - you shouldn't have to suffer through that and it will probably cause other problems for you. Could you please click on Settings (the gear-shaped icon on the top right of the website) and then on "Log out". Then log back in. lf you see more than one red error message in the next day after that, please tell us! There are other things we can try after that.

If you're familiar with using your browser's JavaScript console / Developer console, I'd like to know what errors appear there before you log out, but don't worry about that if you don't know how to access it. If we need it later, we'll explain then how to access it.

**Comment by Merave1** [comment]
Since doing what you've suggested (the proper log out instead of just closing my browser), things are way better. Haven't had a red message in the last two days :) Sometime it takes the sign a few seconds to register whatever action I take but it's fine. I don't mind that.

Was waiting with this answer to be sure the red messages didn't came back... Couldn't believe it at first :)

So simple a solution - Thank you!

**Comment by Alys** [comment]
@Merave1 Fantastic! Thanks for testing that and reporting back!
