### ISSUE TITLE
Glyphicons not compatible with open-source license

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica#8059]
From http://glyphicons.com/license/

"You must not: [...] include icons in open-source projects, since this license is not compatible with most of the open-source licenses"

**Comment by crookedneighbor** [comment]
That's weird because glyphicons are included in Bootstrap, if I recall. 

In any case, we're not going to be using glyphicons in the redesign project.

**Comment by Alys** [comment]
FYI @veeeeeee 

Thank you @mandyzhou!

**Comment by paglias** [comment]
From what I remember the icons we're using are a special distribution of
Glyphicons made specifically for Bootstrap

Il 24 set 2016 17:37, "Alys" notifications@github.com ha scritto:

**Comment by crookedneighbor** [comment]
^ sounds accurate to me.

**Comment by paglias** [comment]
The Bootstrap site states that

> Halflings are normally not available for free, but their creator has made them available for Bootstrap free of cost. As a thank you, we only ask that you include a link back to Glyphicons whenever possible.

And the Glyphicons one that

> License for GLYPHICONS Halflings in Bootstrap
> 
> GLYPHICONS Halflings font is also released as an extension of a Bootstrap www.getbootstrap.com for free and it is released under the same license as Bootstrap. While you are not required to include attribution on your Bootstrap-based projects, I would certainly appreciate any form of support, even a nice Tweet is enough. Of course if you want, you can say thank you and support me by buying more icons on GLYPHICONS.com.
