### ISSUE TITLE
Spam prevention - prevent a player from posting too many chat messages in a short time

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8060]
We want the Tavern, guild, and party chats to have a timed limit preventing people from posting many messages in a row. It should allow only X posts per Y time, with a rolling window, where X and Y are specified as environment variables or constants (constants might be fine because we probably won't want to change this often).

Moderators are exempt. We might also want to exempt Socialites of a high enough level, so perhaps make an exemption for all players who have `contributor.level` greater than perhaps 3 (moderators are level 8). Specify that number as a constant or environment variable.

Any coder who wants to work on this is welcome to post here to claim it, but please do that only if you can start now and finish ideally in a couple of weeks. Please give a progress report after a week so your claim doesn't expire.

FYI @lemoness

**Comment by colingm** [comment]
@Alys Hey I was wondering if I could work on this. Any idea what would be preferred for X and Y?

**Comment by lemoness** [comment]
Right now, let's make the limit 2 posts in 1 minute. Those variables should
be easy to change in the future, though, if we find that it isn't working
out.

Also, a point that we'll need to consider is how deleted posts are handled.
For example, if I post a message, realize it has a typo, delete it, and
repost with the typo fixed, is that considered one message, or two? In my
opinion, ideally it wouldn't count deleted messages against you, but if
that's a difficult thing to program, we should leave it for the second
iteration of this feature.

**Comment by Alys** [comment]
Something I really should have put in the top post: 

Before the fix for this issue is merged,  a fix for this issue needs to have been completed and proved correct:
https://github.com/HabitRPG/habitrpg/issues/8066 "Enter/Return key should not post chat messages"

Otherwise people will have their chat ability limited due to no fault of their own.

**Comment by colingm** [comment]
@lemoness I will change the X and Y to match 2 posts in one minute. My current implementation doesn't count deleted messages against you, I will make sure to triple check that just to make sure. 
@Alys It doesn't seem like that one has been claimed yet. I can look at seeing if I have time to claim that one as well.
