### ISSUE TITLE
Automatic muting (revoking of chat privileges) for players who attempt to post a slur

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8062]
Related to the [swearword blocker](https://github.com/HabitRPG/habitrpg/issues/8061):

When a user attempts to post a slur that violates the Terms of Service, a notification should be sent to moderators and the user should have `flags.chatRevoked` set to `true` so that they cannot make any posts until moderators have determine whether or not the user needs to be blocked.

This is only for slurs, not for less offensive swearwords.

Any coder who wants to work on this is welcome to post here to claim it, but please do that only if you can start now and finish ideally in a couple of weeks. Please give a progress report after a week so your claim doesn't expire.

FYI @lemoness

**Comment by abatula** [comment]
It looks like no one is working on this. If that's the case, I can start on it.

**Comment by khipkin** [comment]
This seems to be related to #4403

**Comment by abatula** [comment]
I haven't heard back on this, should I try working on it or is it still being discussed?

**Comment by Alys** [comment]
So sorry @abatula , yes, please start! Thanks for asking again!

Because this will use some of the same words as the [swearword blocker](https://github.com/HabitRPG/habitrpg/issues/8061) and might have similar code, you might like to post here with your ideas for how you want to implement this so that we can check that the two issues aren't going to conflict.

**Comment by abatula** [comment]
I've done some brainstorming on this, let me know if my understanding/ideas area correct.
- The swearword blocker issue will provide a function to check for swearwords (not part of this pull request)
- This issue should add a method (e.g. `checkForSlur`) to check if a blocked message contains a slur
- If it finds a slur, it should set the user's `chatRevoked` flag to true and message the moderators (probably both in a `muteUser` function).

By "the moderators", should the message be sent to the guild leader? Everyone listed as a moderator in Habitica? Is there an existing function to message the moderators, or should I write one?

Would `website/server/models/user/methods.js` be an appropriate place for the `muteUser` function?

**Comment by Alys** [comment]
@abatula From my point of view, what you've described sounds reasonable. @crookedneighbor or @paglias Do you want to comment on the functions described?

The moderators are any player who has `contributor.admin` set to true (that's the list of staff and mods that appears under the chat box in the Tavern). Guild leaders are not considered moderators and should not be included.

Moderators are already notified when a player flags a post, so you could reuse that code for this. The code sends an email to some mods and sends a message to a private Slack channel that mods use - both of those things would be good for this new feature.

**Comment by abatula** [comment]
I have some [psuedo/skeleton code](https://github.com/HabitRPG/habitica/compare/develop...abatula:8062_automatic_muting) up for the two functions (`muteUser` and `checkForSlur`. I'll keep playing with it, but let me know if I'm going in the wrong direction anywhere.

**Comment by abatula** [comment]
I have a semi-working template for preventing posting of blacklisted words: [code](https://github.com/HabitRPG/habitica/compare/develop...abatula:8062_automatic_muting) 

I moved most of the checking to the chat api, as it seemed to fit better there. Right now it:
1. Goes through an array of blacklisted words to see if any are found
   - I do some _basic_ string manipulation to prevent matching partial words and also prevent not matching if there is punctuation on either side of the word. 
2. Prevents the chat from posting, and gives the user an error telling them that they used inappropriate language

It does not yet:
- Email the mods
- Permanently remove chat privileges
- Do a particularly good job of looking for blocked words.

I'll keep working on this, but let me know if there are issues with anything I've done so far.

I can also open a WIP pull request if that is easier than referencing the code changes.

**Comment by khipkin** [comment]
@abatula If you want more than just general feedback on your code, I think you should open a WIP pull request.  (Just my opinion.) That way, people can do full reviews of your code, or just put comments on specific lines.  Also, that will keep the issue from getting clogged up with implementation details that might not end up being part of your finished PR.
