### ISSUE TITLE
Optional moderator approval for chat posts from all new users

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8063]
We want to have a setting to temporarily turn off the ability of new users to post before allowed to do so by a moderator. This would be very helpful in situations where a single user (or several trolls) tries to make many accounts in a row to dodge a ban and spam chat.

Details:
1. All existing users are always allowed to post.
2. Under normal conditions, all new users are allowed as soon as they've created an account (just as they can now) BUT:
3. There should be a flag (an environment variable?) that mods can use to cause every new user account to be unable to post until a mod enables posting for that user. Mods could turn on that flag when a troll keeps creating new accounts. Mods would turn the flag off later when they believed that the troll might have moved on.
4. When a user who is not yet allowed to post tries to post, their message appears in the chat area but visible only to mods (and it's sent to mods in an email). There'd be an icon on the message that mods could use to make the message visible to everyone and to enable normal posting for that user. This behaviour would occur only while the flag was turned on.

EDIT 2021-11-10: One possible solution is in https://github.com/HabitRPG/habitica/pull/12499 but note the comments there from paglias!

**Comment by khipkin** [comment]
@Alys Wouldn't this overwhelm the moderators relatively quickly once the flag was turned on?

**Comment by crookedneighbor** [comment]
An alternative to this would be to require people to verify their email before granting chat permissions. I would much prefer that option.

**Comment by Alys** [comment]
@khipkin This would be used only in situations where one or more trolls or spammers were repeatedly making new accounts to get around a ban. In one time when that happened with just one person making a few accounts, it took me two hours of solid effort to keep blocking them and finding and deleting their messages before they stopped. If it were a group of people, or one person who continued longer, it would be far more overwhelming. Reviewing new messages and allowing them through would be faster and much less stressful.

@crookedneighbor I don't think that would be a sufficient barrier. Email addresses are easy to obtain and can be verified quickly.

**Comment by khipkin** [comment]
@Alys Ohhhhhhh did you mean that only new accounts made after the flag was set would be moderated like this?? I thought you meant all new accounts made after _the feature was added_. :facepalm:

**Comment by Alys** [comment]
@khipkin Ah yes, I was not clear enough! Definitely just when the flag is set, not all the time. :) I'll adjust the top post. Thank you for querying it!

**Comment by cching0L2** [comment]
Looks like a fun yet challenging issue... if nobody's tackling it can I take a look?

**Comment by Alys** [comment]
@cching0L2 Thanks, please do! Comment here if you have questions or find any problems.

**Comment by cching0L2** [comment]
Sorry about the delay.  Have been pretty busy and finally have time now to work on this issue.
A quick question, by "chat", do you mean Tavern only, or within all guilds

**Comment by Alys** [comment]
@cching0L2 No worries about the delay - thanks for coming back to it! Chat in this case is the Tavern and all guilds and the user's party and private messages.

**Comment by cching0L2** [comment]
I have been thinking about how to link the visibility of a message to the user's account's creation time.

Since the ability to post is linked to a user, my first thought was to put a flag in the user object, and check on that flag to determine if we should show a user's post or not.  However, inside a group, the user object made available controller is the logged in user's object, and does not say anything about the message's author's information.  

But if we link messages to user, say, storing the uuid of author, we will need to query the user every time we are trying to display a message, to see if this user is allowed to post or not.  This would be pretty heavy.  

Any suggestions? 

P.S. I typed off the top of my head, not sure if I'm explaining myself well.  Please feel free to ask more questions if I didn't make myself clear.

@Alys

**Comment by MathWhiz** [comment]
@cching0L2 Did you ever get an answer to your questions?

@Alys

**Comment by Alys** [comment]
@cching0L2 I'm really sorry! We never answered you. :(  If you're still interested in this issue, we'd love you to keep working on it - just let us know if you are.

Probably the easiest way to hide a new message that should be visible to only mods is to set the message's `flagCount` to 5. That mimics the effect of a message being flagged by a moderator, which automatically hides the message from players who aren't mods/staff. Even if we end up not re-using the flagCount field for this, a new field could be added to the message schema for hiding in a similar way to how flagged messages are hidden.

**Comment by lemoness** [comment]
@cching0L2 After some discussion, because this issue is pretty high-priority, we've decided to tackle it internally, but thank you for volunteering! I hope that you'll continue to check out other tickets.

**Comment by TheHollidayInn** [comment]
For new users, are we assuming users created in the last day? two days? 

Should this only be for public guilds?

**Comment by lemoness** [comment]
I'm discussing this with the mod team.

**Comment by lemoness** [comment]
We'd like this to apply to all users who have created an account in the past day, and this should only apply for messages in the Tavern and Public Guilds. It should not apply to messages in Private Guilds, Group Plans, or Parties.

**Comment by lemoness** [comment]
Slight addendum --  If applying this retroactively would make the code more complex to implement, we can just make it apply going forward from the moment it's enabled, and then if we start having issues where people already made accounts, we can modify the feature as-needed based on our real-world experiences. 

It's also been brought up that we might want to be able to vary the length of the time period to which it applies retroactively (for example, if a big group of trolls joined three days ago, but didn't descend on the Tavern until today, etc), which would make the feature more complex, so we may want to just do the simpler version first.

Do you have a preference?

**Comment by TheHollidayInn** [comment]
Hmmmm. I can create two settings: 
 - a setting to enable the blocking of chat for new users
 - a setting to set the age of new users to be blocked (eg. 1 day old, 2 day old, etc).

Does that sound correct?

**Comment by lemoness** [comment]
That seems good to me! The first setting is higher-priority than the second.

**Comment by Alys** [comment]
After a mod discussion, we've decided that there should be a change to this point from the top post: _"When a user who is not yet allowed to post tries to post, their message appears in the chat area but visible only to mods "_
The desired behaviour now is that the message should be visible to mods and to the user themself (but still not visible to any other user).

In addition, the user and mods should see a message on the post saying something like:
"Your message is awaiting approval by the moderators and is currently not visible to anyone except you. Moderators are actively monitoring new messages to approve them as quickly as possible. This is a temporary measure to protect the community due to a high volume of spam posts."
That's just a draft; mods are still working to improve it. I'll post here when it's finalised.

**Comment by Alys** [comment]
Just noting here that I've made some edits to the top post and also removed some old comments, with all relevant information from them being added to the top post. This is just to make the issue easier to parse. I'm checking with the mods about some other details and will post again here when final decisions have been reached.

**Comment by Alys** [comment]
This is on hold until https://github.com/HabitRPG/habitica/issues/10851 has been created, because that shadow-muting feature will form the basis of this optional mod approval feature.

**Comment by deilann** [comment]
With everything that's going on, I think this is more of a priority. And now that shadow-muting is already implemented, it should be easier to implement. I'm starting work on this tonight, but I am moving soon, so it may not be completed as fast as I'd like.

**Comment by shanaqui** [comment]
@deilann Just checking in whether you're still interested in working on this! Let me know, or I'll go ahead and set it back to help wanted in about seven days. :)

**Comment by shanaqui** [comment]
I've marked this as help wanted again!

**Comment by Alys** [comment]
I've removed some old comments that didn't contain any information that's still relevant. I've marked it as in progress because I'm experimenting with a simple initial solution for this.

**Comment by SabreCat** [comment]
@Alys It's been more than a year--still thinking of doing anything with this one?

**Comment by Alys** [comment]
Sorry, I should have changed the labels on this ages ago. My "simple solution" had a large bug and I never had time to fix it. I'm putting this back to help wanted. 

Anyone who picks it up might want to look at https://github.com/HabitRPG/habitica/pull/12499 and the comment that paglias wrote there for how to fix the bug. Or you can work on your own solution!
