### ISSUE TITLE
Enter/Return key should not post chat messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8066]
Currently, when typing a message in the Tavern, guilds, or party, hitting the keyboard's Enter key will post the message. This causes users who aren't familiar with this behaviour to post multiple messages when they meant to post only one.

**This should be changed so that Enter does nothing but make a new line (as Shift-Enter does now).**

This is important because we want to introduce an anti-spam limit on posts (https://github.com/HabitRPG/habitrpg/issues/8060) and we don't want users to accidentally exceed the limit by posting messages when they don't mean to.

Users who want to use keyboard controls to post messages can do Tab-Enter or Tab-Space (Tab moves focus to the send button and Enter or Space "clicks" the button). This behaviour must keep working. We can inform the Socialites about that so that they can share it to people who aren't happy with the removal of the Enter key's function.

(We could change Shift-Enter so that it posts the message, but many users are already used to using Shift-Enter to insert line breaks, so I personally think that changing that isn't a good idea at the moment. Perhaps a few months after Enter stops posting messages we could consider making Shift-Enter post them.)

Any coder who wants to work on this is welcome to post here to claim it, but please do that only if you can start now and finish ideally in a couple of weeks. Please give a progress report after a week so your claim doesn't expire.

FYI @lemoness

**Comment by crookedneighbor** [comment]
I think I logged an issue about this already. My suggestion was to use ctrl/cmd + enter to send, like Github. (I believe I've already implemented that bit)

**Comment by crookedneighbor** [comment]
Actually, you opened the issue https://github.com/HabitRPG/habitrpg/issues/4460

**Comment by Hus274** [comment]
I can take a look into this one.

**Comment by Hus274** [comment]
Submitted a pull request removing the send chat by clicking enter functionality.
