### ISSUE TITLE
separate drop eggs from quest eggs in the Inventory > Market page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8067]
_This should be worked on during the website redesign or afterwards, not now._

From a discussion in the Tavern:

On the [Inventory > Market](https://habitica.com/#/options/inventory/drops) page, in the Market section where you can buy items, all eggs are listed in one section, with the introductory text "Get these items faster with Gems if you don't want to wait for them to drop..." This implies that quest eggs will drop.

I think the best way to clarify this is to have one section for the non-quest eggs, with the same introductory text that's there now, and a separate section for quest eggs, with text explaining they will never drop and that they can be obtained by either buying them or repeating the quest.

**Comment by librarianmage** [comment]
The Inventory does not display this introductory text anymore; should it be closed?
