### ISSUE TITLE
Store Exact Completion Date for Dailies

### ISSUE THREAD

**Issue by markwk** [HabitRPG/habitica#8070]
The habitica-user-data.json file does not store the user action update data on dailies. Instead what we have is the cron update data for dailies. This leads to some rather stage data export since we lose the timestamp of user input. I understand that a certain amount of preening is necessary for performance and database management. That said, I don't think we should delete this user history data or, in fact, fail to store it for a certain period. I propose storing maybe a month (or week) worth of data for non-subscribers and maybe a bit longer for subscribers. 

This change will lead to much better data that can be used for personal study and for broader community research on when people log their dailies and habits. This could create some very interesting data science research as well. In some ways this is a follow on to #8069.  

Look forward to hearing thoughts on this. Thanks.

**Comment by Alys** [comment]
Normally we ask that feature requests are placed in Trello, which you can access through Help > Request a Feature from the habitica.com menu. However since you're a dev, I'm guessing you want to work on this feature yourself, so I think it can stay here while it's discussed, but please be aware that if it turns out to not be possible for it to be implemented in the short term, we might close this and have it moved to Trello.

I think you're asking about two separate features here (correct me if I'm wrong):
- recording the timestamp of when you marked a Daily as completed
- keeping task history

History is already preserved for at least two months. [Task History Compression](http://habitica.wikia.com/wiki/Task_History_Compression) on the wiki gives details. It can't really be stored longer than it already is to limit resource usage.

I can see that knowing what time you completed Dailies could be of interest in some cases, for example, tracking how efficiently you proceed through your morning routine.

**Comment by paglias** [comment]
I agree that storing the exact completion date for dailies would be a good idea, it could also help debugging problems with cron. @markwk  If you want to work on this there's code to be changed in website/common/script/ops/scoreTask and website/server/libs/cron

**Comment by paglias** [comment]
I've changed the title of the issue to reflect that it's only about dailies history. You can see the history for your tasks at https://oldgods.net/habitrpg/habitrpg_user_data_display.html

**Comment by markwk** [comment]
Thanks for the comments and guidance @Alys and @paglias. Very helpful places to start. It might be awhile before I can dig in. My main concern was that as a tracker habitica exports fail to give me back an accurate history of my usage. This makes it hard to mashup data across tools to see productivity, life, etc. in a broader storyline. 

Anyways, I'm not that great with node but I'll see what I can gather. Assuming certain changes like these can be implemented there would be an interesting place for my data science work on how users interact with the technologies like Habitica and how their logs reflect progress in building habit / task / dailies into routines like a morning routine.

**Comment by librarianmage** [comment]
@markwk Do you have any progress?

**Comment by TheHollidayInn** [comment]
I believe this is the line to investigate and write a test for: https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/cron.js#L304

**Comment by markwk** [comment]
@MathWhiz No luck jumping in on this one. Crazy client work past month.

**Comment by vincecampanale** [comment]
@markwk @TheHollidayInn @MathWhiz I'd be happy to give this a shot if that's okay with you guys.

**Comment by TheHollidayInn** [comment]
Sounds good. I updated my link to reflect the file change.

**Comment by vincecampanale** [comment]
Hi all, 

Do we want to have a new section in the "Dailies History" which essentially looks like the "Habit History" data? Am I just writing a couple lines to store the data in the database or am I responsible for displaying it in the User Data page as well? 

Could someone point me to the code that defines how the habits are stored in the database (so I can apply that to dailies), as well as the code that displays the habit data on the user data page? 

Thanks!

**Comment by librarianmage** [comment]
@vincecampanale From what has been said before, this is what needs to be changed / have tests updated for: https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/cron.js#L305

The model for all tasks is here: https://github.com/HabitRPG/habitica/blob/develop/website/server/models/task.js

**Comment by librarianmage** [comment]
@vincecampanale Are you still working on this? If not, can this not be marked in progress?

**Comment by vincecampanale** [comment]
Nope, sorry, not working on this any more either.

**Comment by lemoness** [comment]
Is this something that we still want @paglias? If not, I'll close this ticket.

**Comment by Alys** [comment]
I'd still like the completion date-time for dailies to be stored, for the player's own information and to help with debugging. It's still low priority though.

**Comment by lemoness** [comment]
I've updated the labels on this ticket!

**Comment by LulaV14** [comment]
Hi, can I help with this?

**Comment by lemoness** [comment]
@LulaV14 Absolutely! Thank you so much. Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by librarianmage** [comment]
Hello @LulaV14! How are you doing with this Issue?

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by LulaV14** [comment]
Hi @MathWiz and @lemoness 
I'm so sorry for the long delay. I had some issues and didn't have much time.
I know you've been having this issue open for a long time, so maybe if I can have a week or two now that I have time to finally close it?

**Comment by librarianmage** [comment]
@LulaV14 Oh, I don't think that will be a problem.

**Comment by lemoness** [comment]
@LulaV14 - That will work great! Thank you very much. We look forward to seeing the fix.
