### ISSUE TITLE
Allow moderators to unflag a post that they have flagged

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8078]
On the website, moderators no longer have the ability to unflag a message that they previously flagged.

When a non-moderator flags a chat post, they are not allowed to flag it again; if they try to, they see a notification saying "you have already flagged this message". That's correct behaviour for non-moderators.

However moderators are also seeing that notification, which is not correct. A moderator should always be able to click on the flag icon to bring up the flag confirmation screen. This is because that screen contains the button that allows a moderator to unflag the post, which they need to do sometimes even when they were the ones to flag it.

This is purely a client code change, not an API change (I have confirmed that the API does allow a moderator to unflag a post they flagged). I'd prefer that this didn't wait for the upcoming website improvement project because it's a useful feature that helps with moderation and because I think the change should be quite a simple one (just putting an exception in the code for users who have `contributor.level` greater than 7).

**Comment by crookedneighbor** [comment]
It should be for people who have the admin property, actually. (Amounts to the sane thing)
