### ISSUE TITLE
Cannot start fresh install of habitrpg

### ISSUE THREAD

**Issue by sirhopcount** [HabitRPG/habitica#8079]
I have created a docker image for HabitRPG but I cannot start an instance because it crashes with the following error:

```
habitica-app_1    | [14:23:42] Finished 'semantic-ui' after 35 ms
habitica-app_1    | fs.js:951
habitica-app_1    |   return binding.readdir(pathModule._makeLong(path), options.encoding);
habitica-app_1    |                  ^
habitica-app_1    | 
habitica-app_1    | Error: ENOENT: no such file or directory, scandir '/src/habitica/website/build'
```

You can find the full error log, Dockerfile, directory listing, etc in this gist:

https://gist.github.com/sirhopcount/68e7d1c4213a1c2f30dea373c96e594b

If you need any more information please let me know.

**Comment by paglias** [comment]
@sirhopcount can you try creating a website/build directory?

**Comment by sirhopcount** [comment]
Yes, that fixed the problem, thanks for the help.

Before you close this issue could you please point me to the docs regarding the configuration file. Most documentation and examples I found just copy the example file without editing it and I assume the error I'm in running into now is related to the configuration: 

```
/src/habitica/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
```

(I followed the "Setting up Habitica Locally" guide just copied the example configuration with editing it)

There are also allot of feature I do not plan to use (I saw options for integration with facebook, paypall, amazon, etc) and was wondering if I can simple remove the from the configuration or that they are mandatory.

**Comment by paglias** [comment]
Everything that's in the example configuration must stay, otherwise the server won't start but they're all placeholder values, they won't activate anything. Regarding the error you see is because we recently merged some changes that require new config options. You can copy the missing values from the config.json.example in the develop branch
