### ISSUE TITLE
drop notifications are not being received by some players

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8082]
In the Report a Bug guild, three players have reported not seeing drop notifications over the past couple of days, although they have been receiving drops (I've confirmed this with `lastDrop.count`). This isn't usually a common report there or in the Tavern so I believe it is a new bug.

CheerfulGeek (76c23037-2aa9-4ab8-9cba-c78ad6f114e6) - "I first noticed it either yesterday or the end of the day Tuesday, I forget which"

Gumnos (43e2413a-f440-43c8-b96c-85b93024488c) - "has something changed/broken with the drop system? I usually get ~10 drops daily but haven't gotten notification of any drops for ~2 days. I've been watching it pretty closely since I'm just short some honey to obtain Beast Master for the 4th time"

Barefoot Fyodor (fae5709d-1a31-4141-a990-c87b8be7a10f)  - " I haven't been getting any drops for a while now" (no details about how long it's been happening)

However I am getting drop notifications so it's not happening for everyone (Vivaldi on Linux). I've asked them to tell me which browsers they're using.

**Comment by paglias** [comment]
I think the code for drops was changed to be server side only in the last few days, it could be the source of this bug

**Comment by paglias** [comment]
Actually the code has been server side for a long time but there's been some change to make it truly random

**Comment by Alys** [comment]
In case this helps, I've been getting notifications for eggs and potions and food, so it's not dependent on the type of drop.

**Comment by paglias** [comment]
There was a bug that prevented drop from showing for users not in a quest. Fixed in https://github.com/HabitRPG/habitrpg/commit/c3843cae80ff4b2a6dc1bd6686c4b121b352ad62

When it's deployed this'll be fixed

**Comment by paglias** [comment]
Deploying the fix right now, should be online in max 30m
