### ISSUE TITLE
"Notificiation not found" message and unknown hp loss

### ISSUE THREAD

**Issue by Raoulbarclay** [HabitRPG/habitica#8083]
General Info
- UUID: a2d7435c-245b-4e47-a99f-ba98d60888d0
- Browser: Firefox
- OS: Win8

Description

Hi, I had this issue when i logged in - [image](https://1drv.ms/i/s!AqiSzcHPXQ_nggeOqH80FvwopPXf) - I lost some hp (one isn't from the missed taks), I got this "notification not found" message, and the "quest completed" popup from the lvl15 quest appeared again, although I completed it the day before. Something similar happened a few days ago, when I tried to add a new skill point: I lost hp, I got the notification and my lvl went back.

**Comment by khipkin** [comment]
@Raoulbarclay Did you notice if there were any error messages in your browser's console?

(For reference, here's an article containing instructions about how to access the console on Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console)

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Closing. We can reopen if this still happens.
