### ISSUE TITLE
Redmine integration

### ISSUE THREAD

**Issue by joshuacox** [HabitRPG/habitica#8084]
I would really like to see integration with [Redmine](http://www.redmine.org/)

Ideally I'd like to earn XP for completing tasks

but initially i'd go for issues assigned to me showing up in my todo list 

Any ideas?   I would gladly chip in on some of the work, but I'm a year long user of this project without any dev time (on HabitRPG specifically), so I admit I am not equipped to really think out how it should be done, but I do know a bit of ruby (and I'm a long time user of redmine as well)  and I could probably grind out a significant amount of the hard work here.

**Comment by Alys** [comment]
@joshuacox Habitica uses GitHub primarily for bugs, with feature requests being stored on Trello. You can get to Trello through Help > Request a Feature from the website's menu and then there's instructions for how to choose the correct card - search through that for "integrations" to get to the right place for this suggestion.

At this time, an integration is probably best done as a third-party tool that uses both Habitica's and Redmine's API, but if you'd like to learn about Habitica's source code see [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) on the wiki. Any code that was submitted into Habitica's code base would need to be JavaScript.

If you would like to create a third-party tool, there'd be no objections to that! It could be [featured on the wiki](http://habitica.wikia.com/wiki/Extensions,_Add-Ons,_and_Customizations) when completed. Join the Aspiring Comrades guild, if you haven't already, for discussions with other third-party devs and Habitica's admins.
