### ISSUE TITLE
Wrong lost equipment shown in rewards after death until page reload

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#8085]
The last two times I died, I noticed that I got notifications that I lost my "Royal Robes" and my "Winter-lit Staff" - but the two new equipment items that appeared in the Rewards column were two different items with different prices (a pair of ears - I think cat ears -, and a different staff which I don't remember). After reloading the page, however, the right items (the "Royal Robes" and "Winter-lit Staff") were shown.

This happened on a desktop with Windows in Chrome.

This is probably a minor bug. It definitely doesn't bother me. (It might be more serious if people could click on the reward to buy the equipment back before reloading the page. But usually that can't happen because people lose all their gold with death, too.) I'm just reporting this bug for the coders (after searching for similar open issues and finding none). You don't need to answer me any time soon, or at all.

Happy bugfixing!

**Comment by crookedneighbor** [comment]
Hmm. I think this is my fault. I'll fix it.
