### ISSUE TITLE
Avatars covered up by header at md size, 979px - 768px

### ISSUE THREAD

**Issue by b9chris** [HabitRPG/habitica#8089]
The avatars at the top of the screen get covered up by the header at what's typically the md-size on Bootstrap, 979-768px. At level 9 and below it means it's just cut off and broken looking, but level 10 and above after taking a character class it loses your health bar entirely.

Easier to just see it - here's the broken one at the top, and then one I messed with in Chrome Dev Tools to show the health bar got covered up below (increased some height and padding).

http://imgur.com/a/8ZEtP

Happy to fix this if I get the green light from team to do so. I'd add a media query or 3 to prevent this and keep it clean.

General Info
- UUID: 3453f276-65dd-4736-ace5-28d5ab484957
- Browser: Chrome
- OS: Windows 10

**Comment by SabreCat** [comment]
Sure, go for it!

**Comment by b9chris** [comment]
Dunno if this is the right place to ask this, but should I be concerned that all the relevant styles appear to be in "/client-old"?

**Comment by SabreCat** [comment]
@b9chris: Those are what's used on the site at present. What's going into `/client` is a rewrite of the site frontend that we're working on!

That does mean that a fix here will likely become irrelevant once the rewrite's finished. So if it looks like it'll require a great deal of effort on your part, it may not be worth your time! Your call.

**Comment by SirIntellegence** [comment]
What is the status of this? It makes it rather hard for me to check my health on my screen.

**Comment by b9chris** [comment]
To be clear my Pull Request/patch for this issue is attached, so I'm just waiting for approval from the team to merge it into the code. Then this will be Fixed.

Sooo.... can I persuade someone to take a look and if happy, merge it? It's basically a one-liner.
