### ISSUE TITLE
Ignore lib in .gitignore

### ISSUE THREAD

**Issue by wizonesolutions** [HabitRPG/habitica#809]
Do we still need to not ignore this for nodejitsu or did you figure out how to run `make`?

**Comment by lefnire** [comment]
we can remove. the `require('coffeescript')` would make it run just fine on nodejitsu anyway

**Comment by wizonesolutions** [comment]
Hmm then people would have to `make` before it'd work in dev? Would we update Running Locally?

**Comment by lefnire** [comment]
no. this makes sure you don't need lib at all:

```
require('coffee-script') // remove intermediate compilation requirement
require('./src/server').listen(process.env.PORT || 3000, process.env.IP || '0.0.0.0');
```

if you want lib for some reason (eg, when debugging without sourcemaps on local), you run `make` and replace `src/server` with `lib/server`. I was uploading the `make`'d lib/ directory along with the app up to nodejitsu before, so i removed it from .gitignore. well now with `require('coffee-script')` that's unnecessary, so we can .gitignore it

**Comment by wizonesolutions** [comment]
ah I see. well that's this one. I'll probably open another one for having an nconf var to alter the behavior when I get tired of this :P 

ok will do this...next time.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
