### ISSUE TITLE
Finding Habitica on GitHub

### ISSUE THREAD

**Issue by spdale** [HabitRPG/habitica#8090]
General Info
- UUID: 8fe24168-e547-4f24-a46e-2dddc0266ca2
- Browser: Chrome
- OS: All
### Description

Hi there. Just a quick little thing. When you go to GitHub and search for Habitica, this repo doesn't show up immediately in the search. You instead have to search HabitRPG which is a little confusing for a noob like myself. It's probably not possible to rename the repo (considering that other APIs probably reference "habitrpg"), but to get it to show up in the search results, it may help to include the word "Habitica" in the description (the word on its own instead of just the hyperlink).

Thanks!

**Comment by paglias** [comment]
Repo renamed https://github.com/HabitRPG/habitica :)
