### ISSUE TITLE
Doesn't work on iPhone 4

### ISSUE THREAD

**Issue by dmuth** [HabitRPG/habitica#81]
Howdy,

I love the site, and it works great on my desktop machine, but doesn't seem to work on my iPhone 4 in either Safari or Chrome.

I can log in and view my lists, but the page seems to be constantly reloading, as indicated by the spinning pinwheel in the menu bar.  I cannot mark any task as complete, either.

Is there an issue with the site itself, or are there any workarounds that anyone can suggest?

Thanks!

**Comment by lefnire** [comment]
what about now? was it #91?

**Comment by dmuth** [comment]
Currently unable to test.  The site is currently loading slowly, and I am unable to log in due to the "greyed out button" and "disconnected" issues in the login box.

When the site becomes more stable I'll be happy to test again.

**Comment by dmuth** [comment]
The site is a little more stable so I just logged on. Unfortunately, the same problem is happening.  The spinning "whell" in the menu bar just keeps going continuously.

That said, the "offline - reconnect" message is no longer appearing for me on the iPhone.

**Comment by weperience** [comment]
I tested it right now on an iPhone 4, iPhone 4S and iPad 3rd gen.
1. Dailies and Todos work just fine. 
2. Habits and Rewards don't work
3. Alerts like Exp-Gain aren't displayed

The spinner ist still active because of the constant connection from the site to the server, which it indicates. That's nothing to worry about.

**Comment by horusofoz** [comment]
Can anyone advise if this is still happening? 

I'm not aware of any work specifically aimed at resolving this bug but I believe there has been revisions to the code in that time that may have impacted.

**Comment by dmuth** [comment]
Yep.   Still does the "spinning pinwheel in the top menu bar" thing for Safari on my iPhone 4.

But now there's a new bonus: None of the plus buttons or checkboxes work on my iPhone either.

**Comment by horusofoz** [comment]
Can anyone advise if this is still happening?

Again we've had some signification changes which could have impacted this.

**Comment by horusofoz** [comment]
Appears no further instances. Closing ticket.
