### ISSUE TITLE
Hall of Heroes needs better link to item paths

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8100]
For admins, the Hall of Heroes used to contain a filtered link to all possible item paths, which we could use as a reference when awarding items to users. However, now it has changed to the API's output of the content file, which is difficult to navigate. 

We should have an easy-to-read reference to all the item paths in the game.

**Comment by Hus274** [comment]
I can take a look into this.

**Comment by Hus274** [comment]
While I'm working on this, something like this might help to mitigate the issue and make the file slightly more readable. https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en

**Comment by Hus274** [comment]
@lemoness It's sort of the same idea, I've simply reduced it down the the key values and removed all the unnecessary data, but what do you think about this? It's definitely easier to parse with the formatter I've listed above. Here's a couple screen shots:

### All Condensed

![screen shot 2016-10-05 at 5 33 52 pm](https://cloud.githubusercontent.com/assets/17734753/19136534/2bca7eaa-8b22-11e6-8e84-3f253a9712a7.png)

### Food

![screen shot 2016-10-05 at 5 34 05 pm](https://cloud.githubusercontent.com/assets/17734753/19136535/2de1f588-8b22-11e6-9108-d0e79f5fb57f.png)

### Quest

![screen shot 2016-10-05 at 5 34 17 pm](https://cloud.githubusercontent.com/assets/17734753/19136537/300d0b54-8b22-11e6-83e5-3c3f5a945b05.png)

### Mystery

![screen shot 2016-10-05 at 5 34 28 pm](https://cloud.githubusercontent.com/assets/17734753/19136538/3235c8c6-8b22-11e6-8ee9-28fbded69556.png)

And then without a formatter it still just looks like a massive block of text:

### Without a JSON Formatter

![screen shot 2016-10-05 at 5 35 31 pm](https://cloud.githubusercontent.com/assets/17734753/19136548/3f654a3a-8b22-11e6-862b-e0b648263f74.png)

**Comment by Hus274** [comment]
@Alys @crookedneighbor if you have any thoughts about the above feel free to let me know!

**Comment by crookedneighbor** [comment]
Well, the important part for the mods is to know the exact path needed to add the item to the user. So while that looks nice, it doesn't actually provide the information needed for the mods.

**Comment by lemoness** [comment]
It would also be nice if we did not need to use a JSON formatter to have it
be readable.

**Comment by Hus274** [comment]
That makes sense. What about something more like this? I've included the keys at the top to easily find a section with ctrl+f and then you can copy and paste a line into the item path field. I also kept a split between mystery and gear even though the path is the same just to make them easier to find.

### Top:

![screen shot 2016-10-07 at 4 45 58 pm](https://cloud.githubusercontent.com/assets/17734753/19208333/b5386f44-8cad-11e6-999d-cffd2a323c6b.png)

### Gear:

![screen shot 2016-10-07 at 4 45 49 pm](https://cloud.githubusercontent.com/assets/17734753/19208332/b52ba8f4-8cad-11e6-8b48-df44dde7c287.png)

I can add more of the keys in (like what's equipped and current mount etc.) if that's desired as well.

**Comment by Hus274** [comment]
No json formatter required :)

**Comment by Alys** [comment]
@Hus274 That looks good! Although for the gear, the paths that exist in the user's account are like these:

```
items.gear.owned.head_special_0
items.gear.equipped.head_special_0
items.gear.costume.head_special_0
```

and we'd occasionally have need for all three varieties. To make the list shorter though, we could display the `owned` ones and have a comment about using `equipped` or `costume` - those two are rarely needed

**Comment by crookedneighbor** [comment]
We also need what value they should be. I.e., gear items and mounts are booleans, while pets and quests and eggs are numbers.

**Comment by Hus274** [comment]
I've created a pull request for this addressing the comments listed above. There are screenshots attached to the pull request to show the new formatting and design.
