### ISSUE TITLE
A New Habitica Chrome Extension

### ISSUE THREAD

**Issue by spdale** [HabitRPG/habitica#8101]
General Info
- UUID: 8fe24168-e547-4f24-a46e-2dddc0266ca2
- Browser: Chrome
- OS: macOS
### Description

Hi there. I'm new-ish to the coding community and wanted to try to make a Google Chrome Extension. So I made a simple extension that launches Habitica in a new tab. It just adds a convenient button to get to Habitica faster. 
Check out the extension: https://chrome.google.com/webstore/detail/habitica/kaioddlknfmbibclnlnmbgjajbacgnab
Here's my repository on GitHub: https://github.com/sdale28/habitica-extension

I totally get that there is already an official Chrome extension. This is just a launcher. 

Maybe someone will find it helpful!

**Comment by Alys** [comment]
Cool! You might like to join the Aspiring Comrades guild and post about it there - that's where third-party devs hang out and you'd be most welcome there! You could also post about it in the Wizards of the Wiki guild to ask that a wiki page be created for it (we have a page for all the third-party tools we know about).

We use this repo's issues just for tracking bugs, so I'm going to close this now, but we'll see your posts in those guilds!

**Comment by spdale** [comment]
Okay great. Thanks @Alys!
