### ISSUE TITLE
gemCost is incorrect when buying items for gems from the Seasonal Shop

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8115]
Below is a screenshot from Amplitude showing our analytics data for a purchase of (I believe) an item from the Seasonal Shop. It's listed as a gem purchase which is correct, but the `gemCost` is wrong (it looks like it's displaying the `value`, which is the gold cost). The gemCost should be 1 or 2 gems, depending on item. I haven't investigated this at all but I think that's what's going on.

![image](https://cloud.githubusercontent.com/assets/1495809/19234508/7d3e1434-8f2f-11e6-9e2a-f00254605cc4.png)

**Comment by dumindux** [comment]
I will work on this issue :)
