### ISSUE TITLE
No user found (API)

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#812]
Hi,

When trying to run a curl request, it always return the same thing:

```
$ curl -X GET --compressed -H 'Content-Type:application/json' -H 'x-api-user: {<my user id}' -H 'x-api-key: {<my api key>}' https://habitrpg.com/api/v1/user/
{"err":"No user found."}% 
```

So basically, only this command works for me:

```
$ curl -X GET --compressed -H 'Content-Type:application/json' https://habitrpg.com/api/v1/status
{"status":"up"}% 
```

Any idea why ? Issue is related to #542, which I don't have enough permissions to re-open.

Thanks for your help

**Comment by switz** [comment]
Hm, no one else seems to be having this issue anymore. If I remember correctly, the issue had to do with `findById` in the motif queries. But, I believe we removed all of those. So… @lefnire, have any ideas?  

If you don't mind sharing your user id, I can test out your account locally and see what's up.

**Comment by AdrienLemaire** [comment]
Well I mind a bit if you cannot reset my keys.. Anybody could do anything on my lists ^^ Will send you a private message

EDIT: I cannot send you a private message. Please let me know if you can reset my keys afterwards, and I wiill share them

**Comment by switz** [comment]
You don't have to share your API key, just your user id.

**Comment by AdrienLemaire** [comment]
sure :) 84497c76-4028-4dd5-8403-69b4f5b12575

**Comment by lefnire** [comment]
Copied / pasted the command, putting in your id & api key (got api key from
database). Returning the user just fine. You sure you have the right API
key? Maybe you caught the server on a down swing? Can you try again, if if
no cigar I'll up this to "important" & revisit when I can

**Comment by switz** [comment]
+1 from me. Looks a-ok from here.

**Comment by AdrienLemaire** [comment]
Still getting "No user found" :(

I thought it might be a problem with zsh, but escaping the brackets, or testing from a bash shell returns the same result as well. Also tested from a seedbox in another country, and getting the same error... 

PS: you should really hash the api key in your database ^^

EDIT: I cannot reopen my own ticket once you close it

**Comment by switz** [comment]
Please ensure you have no extra whitespace around your api key and user id. If you can join IRC, I may be able to help you a bit easier. We're on freenode at #habitrpg. http://webchat.freenode.net/

I don't really believe encrypting the API key is necessary at the moment. If you're truly concerned, please go ahead and open another issue thread and we can have a serious discussion about it.

**Comment by AdrienLemaire** [comment]
thanks for the good support on IRC. My problem was that I let the brackets around my keys. Issue closed

**Comment by switz** [comment]
I've gone ahead and updated the wiki to make this clearer. https://github.com/lefnire/habitrpg/wiki/API
