### ISSUE TITLE
Ctrl/Command + Enter doesn't send chat message as expected

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8122]
According to reports in the guild and my own experience, Ctrl/Command + Enter doesn't send chat message as expected after the latest Bailey's announcement.

Platforms mentioned: Win10, Linux. 
Browsers: Chrome, Firefox

Linking this issue to #8066 and #8096

**Comment by rachelkachel** [comment]
For the record, Command + Enter works for me (both Chrome and Firefox on Mac).

**Comment by habitrpguser** [comment]
Is the fix "live" already? I just "cleaned" my browser (deleted cookies, cache, other browser data) and restarted it, and Ctrl + Enter still doesn't work for me. (Windows 10, Chrome.)

**Comment by paglias** [comment]
No it's not live yet
