### ISSUE TITLE
Collection quests wrongly state that drops cannot be seen

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#8123]
General Info
- UUID: 30983c37-52c3-415d-977c-38af6c7db91c
### Description

The quest details of collection quests states: "_To collect items, do your positive tasks. Quest items drop just like normal items; however, you won't see the drops until the next day, then everything you've found will be tallied up and contributed to the pile._" However, that is no longer true, as the quest progress icon in the top right now shows the pending number of items to be collected on the next nightly cron.

**Comment by DrStrangepork** [comment]
I can fix the code if someone can correct the text of the quest details. I'm not sure what the proper description should be stated. Here's a start:

_To collect items, do your positive tasks. Quest items drop just like normal items; you can monitor your quest item drops by hovering over the quest progress icon._

**Comment by crookedneighbor** [comment]
That's good enough for me. Open the PR and we'll have someone refine the text if need be.

**Comment by DrStrangepork** [comment]
#8148 is merged and deleted, so closing ticket
