### ISSUE TITLE
Some challenge updates don't reach participants

### ISSUE THREAD

**Issue by Luzino** [HabitRPG/habitica#8126]
General Info
- UUID: 972637e2-e89f-4a2d-a0c5-3a64df5998de
- Browser: Opera
- OS: Win 7 X64 professional
### Description

I'm participating in the tavern ["Pets - Collect Them All" challenge](https://habitica.com/#/options/groups/challenges/d67ef27b-5f7d-4322-aff6-2bebe6fa48ac) and one pet added as a to-do later in the challenge while I was already a participant doesn't appear as a to-do on my personal list. 
Dewines and Alys checked and told me I was missing the snail to-do. Dewines also confirmed that at least one other member and the challenge owner are missing the snail to-do as well.
Other updates to the challenge have reached me.
I don't think this is related to my browser/computer, as I can't see the snail to-do on the android app, either.
#### Console Errors

Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at s.zone (https://habitica.com/app-fd09b953.js:36:2232)
    at Object.authenticate (https://habitica.com/app-fd09b953.js:48:11861)
    at Object.<anonymous> (https://habitica.com/app-fd09b953.js:48:13082)
    at Object.i [as invoke](https://habitica.com/app-fd09b953.js:7:17125)
    at Object.c [as $get](https://habitica.com/app-fd09b953.js:7:15521)
    at Object.i [as invoke](https://habitica.com/app-fd09b953.js:7:17125)
    at https://habitica.com/app-fd09b953.js:7:15171
    at g (https://habitica.com/app-fd09b953.js:7:16758)
    at Object.i [as invoke](https://habitica.com/app-fd09b953.js:7:17092)
    at D.instance (https://habitica.com/app-fd09b953.js:8:8733)

**Comment by Alys** [comment]
@Luzino I have given you the Snail To-Do, but please check it and post here if there's anything wrong with it.

Also post here if you notice any problems sorting your To-Dos (you should not have any as a result of the change I made, but I'm mentioning it just in case I'm mistaken; you might also have had sorting problems from other causes).

As soon as I can make time, I'll do the same for the other participants for any tasks they are missing.

**Comment by Luzino** [comment]
@Alys Unfortunately the Snail To-Do is not showing for me. I disabled all browser add-ons to make sure it's not being blocked by something, but it's not there. I cleared my cache and tried again - nothing. Then I checked via the android app and it's not showing there, either.
The order of my to-dos seems the same as before and sorting works.

**Comment by Alys** [comment]
Ugh, sorry, I see what I did wrong. Please sync and look for it again now, and I'll just delete this rather useless Snail To-Do from my own list. :)

**Comment by Luzino** [comment]
And there it is - top of the list. Even including its correct challenge tag! Thank you. :)

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Probably. If we don't yet have success/failure checking and  failed updates
being repeated, then this bug can still occur.

**Comment by TheHollidayInn** [comment]
Just a note on this, to fix we should do:
1. Remove duplicate data and sync with the challenge when we can
2. Move processing to a worker via a queue system. I have a Kafka PR out now that should help with this.

**Comment by TheHollidayInn** [comment]
Have we had any recent reports on this?

**Comment by TheHollidayInn** [comment]
Feel free to reopen with user reports. Closing for now.
