### ISSUE TITLE
Some pages prevent oauth through Google and Facebook

### ISSUE THREAD

**Issue by devnuhl** [HabitRPG/habitica#8127]
General Info
- UUID: 
- Browser: Chrome (53)
- OS: Windows 10 (1607)
### Description

It would seem that there are pages on the site from which you cannot authenticate. /static/plans being at least one of them.
![error 400 oauth2 error 1 - google chrome 2016-10-12 11 26 11](https://cloud.githubusercontent.com/assets/1120006/19318607/0197c80c-906f-11e6-9d59-5aa92a1b71fe.png)
### Update from @paglias

The solution here is to always redirect to the same page when logging in so we don't have to track which URLs can be used for login, and adding one entry for the settings page for when trying to add Google authentication to an existing account.

This is going to affect Facebook by Februrary / March 2018

**Comment by crookedneighbor** [comment]
@viirus

**Comment by phillipthelen** [comment]
Added all static pages I could find.

**Comment by paglias** [comment]
There's no way to whitelist the whole domain?

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by paglias** [comment]
Yes, this still happens when a query string is in the url. The fix should be to tell hello.js to always redirect the Google popup to the login page

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by Alys** [comment]
This also happens if a user is sent a URL such as https://habitica.com/user/settings/subscription and clicks on it when they're not already logged in. The redirection URL causes Google Login to fail. Because we send URLs like that to users who are asking how to cancel their subscription (often when the user is also asking for a refund), it's a bit of a sensitive case. I'm increasing the priority to important.

**Comment by librarianmage** [comment]
@Alys Do you mean the actual site, or the staging one?

**Comment by Alys** [comment]
Whoops. *cough* Nothing to see here. Thanks MathWhiz. :yellow_heart:

**Comment by librarianmage** [comment]
No problem ;)

**Comment by Alys** [comment]
This also happens when trying to add Google authentication to an existing account.

**Comment by paglias** [comment]
The solution here is to always redirect to the same page when logging in so we don't have to track which URLs can be used for login, and adding one entry for the settings page for when trying to add Google authentication to an existing account.

**Comment by TheHollidayInn** [comment]
I'll take this issue.

**Comment by paglias** [comment]
Facebook is implementing the same security issues in 2-3 months from now
