### ISSUE TITLE
Pet system is not Locked after using the Orb of Rebirth

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8132]
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 37.0.2178.43
Windows 10 32-bit
## Description

Reported as per @Alys instructions
After using the Orb of Rebirth my pet was automatically unequipped. However I am able to do all things with my pets and mounts as before except receive drops. This is the case with App (Android v) and Website client.

Things tested:

| Action | Web | Android App |
| --- | --- | --- |
| Creating New Pet | Yes | Yes |
| Feeding Pet | Yes | Yes |
| Feeding a Pet Till Mount | Yes | Yes |
| Equipping Avatar With Pet | Yes | Yes |
| Equipping Avatar With New Mount | Yes | Yes |

I assume even though the Pet system is locked, players still should receive rewards from Pet Quests.

**Comment by Alys** [comment]
@lemoness just checking: Do we still want the Orb of Rebirth to lock the Pets and Mounts features until they are unlocked at level 3 (as for a new user)? I personally think yes - I think locking of features is one of the fun things about Rebirth.

**Comment by lemoness** [comment]
Yes, no need to change that :)

**Comment by TheHollidayInn** [comment]
@Alys Where is the current logic that locks the pet features for users before they are level 3? I'm not seeing the code, and on my local install, I am able to use the pet features before level 3.

**Comment by MathWhiz** [comment]
Maybe the "Pet blocking" feature is implemented as "No drops, no pets"?

**Comment by SabreCat** [comment]
Did we ever actually lock people out of even accessing the Pet/Mount pages? We even have a Justin visit when you first go there, saying that after level 3 you get to do such and such.

**Comment by TheHollidayInn** [comment]
Yea, I don't think we are blocking the access at all. Should I just hide the tabs if they are under level 3 or do we want some sort of server side check?

**Comment by SabreCat** [comment]
My vote is that this is not an issue and can be closed.

**Comment by TheHollidayInn** [comment]
Don't we still want to lock pet access at level 3 though?

**Comment by SabreCat** [comment]
No, we never have and I haven't yet heard an argument as to why we should start. A brand new user can receive a pet as part of a seasonal event, for example; why shouldn't they be allowed to go use it?

**Comment by TheHollidayInn** [comment]
I'm not sure, but @alys comment seems to imply they want pets locked :P

**Comment by SabreCat** [comment]
My read is that @Alys and @lemoness were operating from a mistaken assumption that these features used to be locked pre-level-3 when in fact they weren't ("Do we still want", "no need to change that")--so maybe best to hold off a decision until they clarify, haha.

EDIT: The text that appears when you first visit the Pets page is indeed a little misleading on this count:

> This is the Stable! After level 3, you can hatch pets using eggs and potions. When you hatch a pet in the Market, it will appear here! Click a pet's image to add it to your avatar. Feed them with the food you find after level 3, and they'll grow into powerful mounts.

That implies that you can't hatch pets pre-level-3, when in fact you can, you just won't find eggs and potions to hatch anything with from ordinary drops. So if nothing else, the text needs tweaking. Depending on what A & L say, we can update the ticket to specify which direction to go (actually lock down these features, or make the text more accurate).

**Comment by lemoness** [comment]
That's correct for me, at least -- I assumed that the status quo locked up
those features.

**Comment by Alys** [comment]
Same here. I was judging by the way the feature was described in-site, and assumed it had changed inadvertently during the API upgrade.

Good point about the pets for new users from special events.

I'd be okay with just making the site's text more accurate if we don't want to change the behaviour.

**Comment by librarianmage** [comment]
A suggested text change:

> This is the Stable! After level 3, you ~~can hatch pets using eggs and potions~~ will start to gather eggs and potions. When you hatch a pet in the Market, it will appear here! Click a pet's image to add it to your avatar. Feed them with the food you find after level 3, and they'll grow into powerful mounts.

**Comment by Alys** [comment]
@MathWhiz Try this:

> This is the Stable! After reaching level 3, you will gather pet eggs and hatching potions as you complete tasks. When you hatch a pet in the Market, it will appear here! Click a pet's image to add it to your avatar. Feed them with the food you find after level 3, and they'll grow into powerful mounts.

Submit a PR with a screenshot and nag me until I've merged it. :)
