### ISSUE TITLE
Party page does not display after creation 

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8133]
## General Info

User Id: bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 37.0.2178.43
Windows 8.1 32-bit
## Description

Click Invite friends another time, the system states creating party with wait icon but never lands on the party page. Had to do a manual party refresh to see the party page.

**Comment by Alys** [comment]
I've just tested this on Chrome on Ubuntu 16.04 and I couldn't replicate the problem.

@cTheDragons Are you able to test again on the same browser? I'm hoping it was just a temporary glitch. If it does still happen on Opera, do you have another browser you can repeat the test on?

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by lemoness** [comment]
I don't believe it is. We can always reopen this if someone can replicate it.
