### ISSUE TITLE
8f9110b4-50d7-446b-a142-0c6ca0cb5029;  Safari 10.0; OS X 10.11.6; I just tried to buy Nov. 2015 backgrounds, and was charged 15 gems.  Only two of the three backgrounds have been unlocked.  Help!!  

### ISSUE THREAD

**Issue by Efox917** [HabitRPG/habitica#8134]
General Info
- UUID: 
- Browser: 
- OS:

**Comment by Alys** [comment]
@Efox917 I'm closing this because I'll handle it in the Report a Bug guild from your report there. That guild is the best place to report problems and you don't need to log an issue in GitHub unless we ask you to (only done for complex problems that need investigation).
