### ISSUE TITLE
No notification ticker for insufficient Gold purchase of Spooky Sparkle

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8137]
General Info
- UUID: N/A
- Browser: Chrome
- OS: Windows 10
### Description

For most items, if you attempt to buy them but have insufficient Gold for the purpose, you get a "Not enough Gold" notification in the corner. If you try to buy Spooky Sparkles without having 15 Gold at hand, however, the notification just lands in the JS console with no end-user visible display.
#### Console Errors

> app-9d4806b2.js:8 b: Not Enough Gold
>    at Object.b.exports [as buySpecialSpell](https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:45:19116)
>    at Object.buySpecialSpell (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:48:9841)
>    at j.b.purchase (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:50:8929)
>    at g (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:9:4029)
>    at e (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:10:12078)
>    at j.$eval (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:9:16681)
>    at j.$apply (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:9:16916)
>    at HTMLButtonElement.<anonymous> (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:10:12139)
>    at HTMLButtonElement.dispatch (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:4:6398)
>    at HTMLButtonElement.r.handle (https://habitrpg-staging.herokuapp.com/app-9d4806b2.js:4:3173)(anonymous function) @ app-9d4806b2.js:8

**Comment by paglias** [comment]
It probably needs to be wrapped in code that handles notifications

Il 13 ott 2016 21:41, "Sabe Jones" notifications@github.com ha scritto:
