### ISSUE TITLE
language of flagger should be recorded to moderator slack

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8140]
When a post is flagged, information about the post and about the person who flagged it is posted to the moderator's slack channel. That information should be adjusted to include the language that the flagger uses in Habitica (their `preferences.language` setting).

This is because we sometimes see posts being flagged when no violation has occurred and we want to find out if specific translations of the flag button and confirmation screen are giving players the wrong understanding of what the flag button does.

The user that flagged the post is passed in here: https://github.com/HabitRPG/habitica/blob/8a8bab4be1b0f8259fd4b89c04802d25b37ab456/website/server/controllers/api-v3/chat.js#L285-L290

It should be a matter of just adjusting this line: https://github.com/HabitRPG/habitica/blob/8a8bab4be1b0f8259fd4b89c04802d25b37ab456/website/server/libs/slack.js#L31

_Thanks to @crookedneighbor for the information about the code._

_A note to anyone curious: We moderators are not annoyed about these incorrect flags; we're just trying to improve the flag information so that players understand the feature better. Also, if a player is ever not sure whether a post should flagged or not, it's best to flag it and let moderators decide. The [Community Guidelines](https://habitrpg.com/static/community-guidelines) do say that flagging inappropriately is a violation of the Guidelines, but we invoke that clause only when it's clear that an incorrect flag has been made with deliberate bad intent._

**Comment by Gitmanda** [comment]
Could I take this one?  It is truly entry-level, and so am I :)

**Comment by crookedneighbor** [comment]
Go for it.

**Comment by Alys** [comment]
@Gitmanda I hate to do bait-and-switch :) but I was going to update this issue to ask that the message sent to slack also includes the language of the person who made the flagged post. That will help moderators work out if a person's use of a bad word might be just because they are not familiar with English. If you'd like to include that in your pull request for this issue, that would be great but if you'd rather not, we can make a new issue later.

You're welcome to comment here if you have questions or run into trouble!

**Comment by Gitmanda** [comment]
I was going to comment to ask if I should also modify test/api/v3/unit/libs/slack.js.  So this actually sends a message to a Slack channel?  That would explain why I wasn't able to test it by playing around with my local installation...

I could take some more time to figure out where to get the profile of the person who made the flagged post, or you could make that one a separate issue and give more entry-level coders a shot.  If the latter, I could have a pull request in for the initial part of this very soon.

**Comment by Alys** [comment]
@Gitmanda Yes, please do modify `test/api/v3/unit/libs/slack.js` to update the tests for this new feature.

We'll make a separate issue for including the language of the person who made the flagged post.

**Comment by ToppleTheNun** [comment]
Has any traction been made on this issue? If not, I'd like to start work on this.

**Comment by Gitmanda** [comment]
I'm sorry, I have the code, I just haven't committed because I need to update the tests.

**Comment by ToppleTheNun** [comment]
Duly noted. Thanks for the update!

**Comment by Gitmanda** [comment]
Ok, what do I do about the fact that it fails tests even with my changes stashed?  I get 1 passing, 4 failing with mocha test/api/v3/unit/libs/slack.js.  The failures are the same with or without my changes to test/api/v3/unit/libs/slack.js and website/server/libs/slack.js.

**Comment by Alys** [comment]
@Gitmanda Make sure your config.json file is identical to the example one (with the exception of anything that you know must be different - usually there's no need for differences though). If that doesn't fix the problem with the tests, we'll need to know details about what's going wrong. For example, you can paste the full output from the tests into a [gist](https://gist.github.com/) and put the link to it here.

**Comment by Gitmanda** [comment]
It all passed under 'npm test'.  I think it was because I didn't supply a Slack URL with 'mocha test/api/v3/unit/libs/slack.js'.
