### ISSUE TITLE
allow moderators to send a private message (PM) to any user - ignore opt-out / blocking

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8142]
A moderator (anyone with `contributor.admin` set to true) should be able to send a PM to any player, even if the player has opted out of receiving PMs.

In the player's inbox, the on-hover text that explains the opt out feature must state that it does not prevent mods from sending them PMs.

The moderator should also be able to send a PM if the player has blocked the mod. Note that this should not be done by preventing the player from blocking the mod because the player might have blocked them before they became a mod.  Instead, this should be done by simply ignoring the block if the person sending the PM is a mod.

In the profile screen that you see when you click on a player's name, the on-hover text for the block button at the top right should state that it will have no effect if the player is a mod now or becomes a mod in future.

_FYI, this is because moderators sometimes need to contact players with important information, often for the player's own benefit (e.g., to explain that the player had to have their chat permissions temporarily removed and to describe what the player can do to have the permissions restored)._

**Comment by jakers1776** [comment]
How can I help?

**Comment by Alys** [comment]
@jakers821 Thanks for asking! If you don't yet have the Habitica website installed on your PC, the instructions in [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) will let you do that. That page also contains a link near the top to the Guidance for Blacksmiths page, which will give you an overview of Habitica's technologies and other useful information. Once you have Habitica set up locally, post again here if this issue is still available and then you can start work on it. If you have any trouble installing Habitica that the wiki page doesn't help with, post to the Aspiring Coders guild.

**Comment by khipkin** [comment]
@jakers821 For reference, the Aspiring Coders guild is [here](https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f). Good luck! 😺

**Comment by jakers1776** [comment]
Alright just got it running locally. What can I do now?

**Comment by Alys** [comment]
@jakers821 The way I start investigating issues is to look at the feature on the website that needs to change, find text there that I can grep for in the source code to track down the file that produces the client-side view of the feature (note that grepping for user-visible text will show you the "locales" files that contain translatable text, so from there you'd find the "key" for the text and grep for that key to find the relevant source code file). Then follow through the logic in that file and grep for the names of methods that are called to find other relevant files. It can take a while at first but it helps you build up a feeling for how the code fits together. You can also approach it from the API - look through the API documentation at https://habitica.com/apidoc/ to find the relevant calls, grep in the code base for them to find the files to modify. See how you go with that and ask here if you have any questions or run into any problems with working out how to implement this change.

**Comment by jakers821** [comment]
Will try that and see what I come up with.

**Comment by jakers821** [comment]
Alright today was too busy tomorrow I will look.

**Comment by jakers821** [comment]
Going to set it up from start to finish and try again.

**Comment by jakers1776** [comment]
I just rebuilt it but every time I enter:

npm start

It hangs at this:

Done, without errors.
[22:38:48] Finished 'grunt-build:dev' after 9.12 s

I cleaned the cash and reinstalled every part of npm but no luck. What do you think?

**Comment by Alys** [comment]
@jakers821 That sounds correct. It's not hanging, the server is just waiting to be used. Do you see "info: Express server listening on port 3000" and "info: Connected with Mongoose" within the recent output? If so, it's probably fine. Please see the "Run Habitica" section in http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally -- it sounds like you're up to step 5 so continue from step 6.

If you've been using those instructions and you're finding that they're not as helpful as they can be, you can edit them to include anything you've learnt while following the process.

**Comment by jakers1776** [comment]
I keep running it locally and find varying degrees of success. I have destroyed and remade vagrant a few times but the biggest problem I run into is my computer crashing. Is 1 core and 4Gb of memory enough for vagrant?

**Comment by Alys** [comment]
@jakers821 I'm not sure. If you keep getting crashes when running only vagrant, then it might not be. You could try installing it directly onto your PC.

**Comment by jakers1776** [comment]
Alright, now I have it running reliably on my laptop.

**Comment by Alys** [comment]
@jakers821 How are you going with this? Do you have any questions for us or need any advice?

If real life things have happened that mean you no longer have time for this, just let us know and we'll open it up to someone else. We completely understand about how that can happen!

**Comment by Alys** [comment]
@jakers821 I've marked this as "help welcome now" again so that someone else can take it up, however if you have time to work on it before someone else has claimed it, comment again here.

Everyone else: Feel free to comment here to claim this if you'd like to work on it.

**Comment by jerell-mendoza** [comment]
Hi @Alys, I'd like to try to work on this issue.

**Comment by Alys** [comment]
@jerellmendoodoo Thank you! Comment here if you have questions or problems.

**Comment by jerell-mendoza** [comment]
@Alys, sorry haven't been able to work on this in a looong time. I think you can just open it up to others to work on this.

**Comment by Alys** [comment]
@jerellmendoodoo No worries! Thanks very much for letting us know!

**Comment by mczuchnowski** [comment]
@Alys I'd like to contribute to this one.

**Comment by Alys** [comment]
@mczuchnowski Thanks! It's yours.

**Comment by Alys** [comment]
Labels updated.

**Comment by Alys** [comment]
@Tressley @lemoness The technical work required for this issue has been done (thanks @TheHollidayInn !) so mods/staff can PM users who have blocked the mod/staff or opted out of PMs in general. I'm reopening this and marking it as "needs design" for the user interface changes, which could be something like this:

In the profile screen that you see when you click on a player's name, the on-hover text for the block button at the top right should state that it will have no effect if the player is a mod now or becomes a mod in future.

_FYI, this is because moderators sometimes need to contact players with important information, often for the player's own benefit (e.g., to explain that the player had to have their chat permissions temporarily removed and to describe what the player can do to have the permissions restored)._
