### ISSUE TITLE
challenge owner can't change Reward value when editing challenge

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8144]
When a player creates a challenge they can add a Reward to it and change the Reward's value to any number (this is correct behaviour).

However when they try to edit the challenge and edit that Reward, they are not able to adjust the value. They should be able to.

Note that this applies to editing the challenge itself, not to editing the copy of the Reward that appears in their own personal task list. The value of their own copy of the Reward must remain uneditable.

**Comment by JTorr** [comment]
@Alys Just to clarify...you're referring to the `rewards` that show up under `tasksOrder`, and not to the `prize` (number of gems). Is that right?

Example showing `prize` versus `rewards`:

```
 {
     "prize": 0,
     "tasksOrder": {
       "rewards": [
         "uuid-of-challenge-reward"
       ]
   }
```

**Comment by Alys** [comment]
@JTorr Yes, that's correct.

**Comment by dumindux** [comment]
I will take up this task

**Comment by Alys** [comment]
@dumindux Thank you! Comment here if you have questions.

**Comment by dumindux** [comment]
@Alys In the element where we edit the price of reward, there is a ng-if, 

> ng-if='task.type=="reward" && !task._edit.challenge.id'

Here  !task._edit.challenge.id' part causes this element to hide during editing. Any ideas on how to fix this? Is it ok to remove this part? Will it break any other section?.

Thanks.

**Comment by Alys** [comment]
@dumindux Removing it might be okay - I'd need to look through the code and test it to be sure, but I won't really have time for that for a while. However you can try it in your local install and see if it works! Git will make it easy to revert if it doesn't work.

This is the expected behaviour for Rewards from challenges:
- when the challenge owner creates the challenge, they can change the value of a Reward
- when the challenge owner edits the challenge, they can change the value of a Reward
- when a moderator edits the challenge, they can change the value of a Reward (a moderator is any user who has `contributor.admin` set to true -- you'll find mentions of that in other code related to challenges, but ask if you have questions)
- no other user is able to edit a challenge
- when the challenge owner has joined a challenge, they are not able to change the value of the challenge's Reward in their own personal tasks list
- when any other user (including any moderators) have joined a challenge, they are not able to change the value of the challenge's Reward in their own personal tasks list

**Comment by dumindux** [comment]
@Alys I looked in to this as you suggested. Removing "!task._edit.challenge.id" also allows the challenge rewards to be edited in tasks section which is wrong. So I think we need to find a condition which becomes true in editing section but becomes false in tasks section.

**Comment by TheHollidayInn** [comment]
This is fixed.
