### ISSUE TITLE
buying zero gems for a gift with PayPal produces InternalServerError

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8145]
On the gem gift screen, it's possible to attempt to purchase gems as a gift for another player without first entering the number of gems (i.e., to try to give zero gems). This produces an ugly error message when using PayPal (below). For Amazon, it allows you to click through to the Amazon site and for Stripe, it allows you to enter your credit card details, but both of those results are also wrong for a value of zero gems.

**The desired behaviour is that you should not be able to click on the "purchase" button until you have entered a number of gems.**

Steps to reproduce for the PayPal case (reported by Laurens van Riel, be51405a-b3c0-41f6-8f99-3e6af962d99f, in the Report a Bug guild):

**Start**:
On the page "Send gift to <username>" I got to this page from my tasks page, by clicking on a party member and then clicking the gift button.

**Actions**:
- Leaving the amount of gems on standard value=0
- Selecting the option "Purchase"
- Clicking the PayPal button.

**Result**:
White page with the text
`{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}`

**Comment by crookedneighbor** [comment]
The API should also reject the request.

**Comment by akortesmaa** [comment]
I can work on this.
