### ISSUE TITLE
No Quest Reward for Dilatory Distress Part 1

### ISSUE THREAD

**Issue by lizgzil** [HabitRPG/habitica#8146]
My party and I didn't receive any rewards for completing the quest 'Dilatory Distress, Part 1 Message in a Bottle'.

On our party chat log it states 'All items found! Party has received their rewards', but it seems no one got anything. There was no pop-up in browser.

It'd be great if there was anything you can do. Many thanks!

Group ID: 640299d4-ef15-4671-869f-9be11a54ed5a

My user ID: 9143735f-b5ec-4cc6-a917-92d11fff83b5

**Comment by Alys** [comment]
I've given the achievement and rewards to you. Reload if you don't see them. Please tell me if they don't appear after that.

If this happens again, or if you experience any other bugs, please go to Help > Report a Bug from the habitica.com website's menu (or Guilds > Report a Bug on the mobile app). That's the best place for bug reports now. It's rare that a GitHub issue is needed and if one is, we'll let you know about that in the guild.
