### ISSUE TITLE
Finished Find the Lair of the Wyrm Task and didn't unlock quest's part 3

### ISSUE THREAD

**Issue by ea247** [HabitRPG/habitica#8147]
General Info
- UUID:  4361d560-8856-4216-8d31-102130deff33
- Browser: Chrome and Edge
- OS: Windows
### Description

I finished the Find the Lair of the Wyrm quest, but it's not showing up as a badge and thus not letting me unlock the next part of the quest. This has never happened before.

**Comment by Alys** [comment]
I've given the achievement and rewards to you. Reload if you don't see them. Please tell me if they don't appear after that.

If this happens again, or if you experience any other bugs, please go to Help > Report a Bug from the habitica.com website's menu (or Guilds > Report a Bug on the mobile app). That's the best place for bug reports now. It's rare that a GitHub issue is needed and if one is, we'll let you know about that in the guild.

**Comment by ea247** [comment]
Hi,

Sorry for posting on the wrong place. When I googled it, it sent me to
GitHub.

Unfortunately, it doesn't seem to have worked. I still don't have a badge
or have unlocked the next part.

Thanks for your help,
Katherine

**Comment by Alys** [comment]
So sorry! Try now?

**Comment by ea247** [comment]
Woohoo! It's all good now.

Thanks. :)
