### ISSUE TITLE
moderators can't edit challenge tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8149]
This issue relates to editing the tasks belonging to a challenge itself (i.e., in the challenge's own page under Social > Challenge). It does not relate to editing any copies of challenge tasks that are added to any player's own list when the player joins a challenge.

Moderators must be able to edit a challenge to change or add or delete any of the challenge's tasks, in the same way that the owner of the challenge can.

Currently, moderators can't do this - they receive the error "Tasks belonging to a challenge can only be edited by the leader."

A moderator is defined as anyone with `contributor.admin` set to true.

An easy way to find the code that needs to be changed for this is to search for `onlyChalLeaderEditTasks`. You'll find code like this:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/controllers/api-v3/tasks.js#L1344

Instead of using a leader ID check, the `canModify` method could be used:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/challenge.js#L75-L77

Note there's no need to change the `onlyChalLeaderEditTasks` string to make it say that mods can edit too. It's best to leave it as it is now for simplicity. Mods don't edit challenge tasks often enough for it to matter that the message is a little inaccurate and we'd typically inform the challenge owner that we've done it.

_FYI for anyone curious: Moderators occasionally need to edit challenges if the challenge owner has put a swear word or other inappropriate content into one of the challenge's tasks, or under other rare special circumstances. Under normal circumstances, they do not edit other player's challenges._

**Comment by eopuntia** [comment]
Is it okay if I look into this?

**Comment by Alys** [comment]
@estln Please do, thanks!

Comment here if you have questions or find any problems.

**Comment by eopuntia** [comment]
@Alys Will do!

**Comment by eopuntia** [comment]
@Alys Some unexpected schoolwork has come up and I'm having difficulty setting up habitica on my computer, so I don't think I'm going to be able to fix it after all. Sorry about that.

**Comment by Alys** [comment]
@estln That's okay! Real-life work has to come first. Thanks very much for letting us know!

**Comment by tribblx** [comment]
Hi @Alys , I've started looking into this issue to get familiar with the code-base, and think I'm close to seeing what's going on here, I think I can get a PR out soon.

**Comment by tribblx** [comment]
@Alys do you have any advice for testing this?  Trying to figure out what the best way to mock an admin would be?

**Comment by crookedneighbor** [comment]
@btribble Are you talking about manual testing or programatic testing?

If manual testing, your local instance should have a `Make Admin` button in the footer.

If programatic testing, you can use the pass and update object when generating a user for integration tests to make them an admin. See: https://github.com/HabitRPG/habitica/blob/a4fd687510160fc54e5730266f4f921f63f49c53/test/api/v3/integration/chat/POST-groups_id_chat_id_clear_flags.test.js#L23

**Comment by tribblx** [comment]
ohhh both very helpful, thanks @crookedneighbor

**Comment by librarianmage** [comment]
Should this be marked as In Progress?

**Comment by Alys** [comment]
I've added this to the top post:

An easy way to find the code that needs to be changed for this is to search for `onlyChalLeaderEditTasks`. You'll find code like this:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/controllers/api-v3/tasks.js#L1344

Instead of using a leader ID check, the `canModify` method could be used:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/challenge.js#L75-L77

**Comment by flhat** [comment]
I've got a PR for this one.

**Comment by Alys** [comment]
@BlkStormy Awesome, thanks!

Labels updated.

**Comment by Alys** [comment]
I'm doing a bit of work on this, adding to @BlkStormy's PR.
