### ISSUE TITLE
API fails to return JSON when an egg or potion drops

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#815]
This one's a little bit a hard to reproduce, since drops are random, but since the API has no way to signal when an egg or potion drop, it gets confused and returns HTML and not JSON (possibly as part of an error page, but I need to add more diagnostics to HabitRPG.pm to find out) when an `/up` route is called that results in a drop.

The ideal solution to this is to add a field to the JSON returns in the API which signals that a drop has occurred, but an acceptable workaround is to simply make sure valid JSON is returned regardless of drop status.

This issue results in pjf/WebService-HabitRPG#32 (Malformed JSON Stream) downstream.

**Comment by switz** [comment]
Yeah, this is definitely an issue. Thanks for bringing it up.

**Comment by paglias** [comment]
This shouldn't be an issue anymore with the rewrite
