### ISSUE TITLE
"No input data" message on the monitor from minimosd-extra board running under FW V889

### ISSUE THREAD

**Issue by sergeykorn** [HabitRPG/habitica#8158]
Minimosd board connected to Telemetry2 port on PIXHAWK Flight controller gives "No input data" message. After pushing the reset button on the board, the screen updates and shows relevant content for a second or so and then goes back to the "No input data" message.

![image](https://cloud.githubusercontent.com/assets/22900995/19580200/c98b1a1a-96f2-11e6-9850-fcdbf002d03a.png)

![image](https://cloud.githubusercontent.com/assets/22900995/19580222/e48bbe6e-96f2-11e6-9c22-e00f9040de88.png)

General Info
- UUID: couldn't find UUID ))))
- Browser: N/A
- OS: N/A

**Comment by crookedneighbor** [comment]
I don't think you intended to open this issue on the Habitica Github repo. Closing now, but re-open if I'm wrong.

**Comment by sergeykorn** [comment]
Looks like I'm lost here ))
