### ISSUE TITLE
Can't add webhook

### ISSUE THREAD

**Issue by E-Fir** [HabitRPG/habitica#8159]
hi!

always get strange error:
http 400 {"success":false,"error":"BadRequest","message":"User validation failed","errors":[{"message":"Path `url` is required.","path":"url"}]}

while other methods works fine

code:

$.ajax({
  url: 'https://habitica.com/api/v3/user/webhook',
  type: 'POST',
  data: JSON.stringify({
    "enabled": true, // default
    "url": "http://psygel.com/?habitica=1",
    "label": "My Webhook",
    "type": "taskActivity", // default
    "options": {
      "created": false, // default
      "updated": false, // default
      "deleted": false, // default
      "scored": true // default
    }
  }),
  dataType: 'json',
  cache: false,
  beforeSend: function(xhr){
    xhr.setRequestHeader('x-api-user', 'b919f165-1a4a-4cf6-a65f-a38a9f678f0d');
    xhr.setRequestHeader('x-api-key',  '***');
  },
  success: function (data) {
    console.log(data)
  },
  error: function (data) {
    console.log("error: " + data)
  }
});

Alys from Report a Bug guild say to post bug here

**Comment by crookedneighbor** [comment]
You need to add `contentType: 'application/json'` under `dataType: 'json'`, otherwise it sends the body param as a string instead of as JSON data.

**Comment by E-Fir** [comment]
thanx alot!!
