### ISSUE TITLE
Weekly items don't stay checked off

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#816]
I have two weekly items that need to be done sometime before Sunday each week, so I set them to be due on Sunday. Unfortunately, when I check them off any time before Sunday, the checkmarks disappear within a day, and when Sunday rolls around I get docked HP! 

This happened even when my day start was set to 0.

(I've restored my stats, but the problem persists.)

**Comment by wizonesolutions** [comment]
Hmm yeah I don't think the system has a concept of early completion.
@lefnire maybe only day-relevant dailies should be zeroed out?

**Comment by lefnire** [comment]
yeah, no early-completion feature currently. I added as a checklist item on the "repeat every n days" [Trello card](https://trello.com/card/repeat-every-n-days-weekly-monthly/50e5d3684fe3a7266b0036d6/108), but for now just have to make sure to tick it on Sunday instead. You still get points for ticking non-due dailies, however

**Comment by lemoness** [comment]
Got it!

**Comment by wc8** [comment]
Closing, since the suggestion was moved to Trello.
