### ISSUE TITLE
I have Enchanted Armoire enabled, but I haven't ever received the Ultimate Gear Achievement yet

### ISSUE THREAD

**Issue by novaakpatrik** [HabitRPG/habitica#8160]
General Info
- UUID: b836294e-73fa-4b40-9afb-d44f43094db6
- Browser: Chrome
- OS: Windows 10
### Description

Currently I'm level 6, but I'm pretty sure that the Armoire was enabled to me since level 1. Thinking it is a regular thing to buy, I was saving my gold for it. After I purchased it I had to brag about it to my friends. But then one of them told me that it is really impossible for me to have it enabled so early and without the achievement.

**Comment by Alys** [comment]
We're currently running randomised tests where some players receive the Armoire when they create their account and others receive it after getting the Ultimate Gear achievement. You were randomly assigned to the group that get the Armoire early.

We actually have a guild within Habitica now for faster reporting of problems and faster fixes or advice. You can get to it from Help > Report a Bug from the website's menu and Guilds > Report a Bug from the mobile app. One advantage of it is that we can see your User ID there and so can often resolve your problem as soon as we've seen your first message.

I think there might be information somewhere on the internet suggesting that this GitHub repository is the best place to report minor problems, so we'll want to change that. Can you please tell us where you found any advice to create an issue here?

**Comment by novaakpatrik** [comment]
As I was googling info it also returned some issue here on github regarding the Armoire. And I assumed I'm on the right place to report an issue.

**Comment by Alys** [comment]
@novaakpatrik Thanks for that!  I've realised that our instructions in the new issue template don't actually mention the bug guild yet! I thought we'd added that but clearly not - our mistake. I'll fix that.
