### ISSUE TITLE
cron does not run when _cronSignature is permanently not set to NOT_RUNNING

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8163]
When cron starts, it adjusts the user's document to set `_cronSignature`  to the user's UID. When cron ends, it sets the value of `_cronSignature` to `NOT_RUNNING`. This is correct behaviour and is used to prevent cron running more than once at the same time.

However if something stops cron from completing (e.g., a timeout or other error), then `_cronSignature` is never reset to `NOT_RUNNING`. This prevents the user from being able to use Habitica in any way - they are not able to log in, or load the website if they are already logged in, or access their account in the mobile app.

In the past few days, we've had emails from three users affected by this. I've done a search in the database and found another 57 users affected by it, with last loggedin dates ranging from 2016-07-15 to today (for today, I checked that they weren't actually in the middle of a real cron). 16 of those users had last loggedin dates of 2016-10-19T17:31 to 2016-10-19T17:33, so they were probably affected by the CPU spike we had then ([ref for admins](https://habitica.slack.com/archives/server-health/p1476898552000013)). Another 3 users had dates of 2016-10-23T00:10 and 2016-10-23T00:11, correlating with today's server alarms ([admin ref](https://habitica.slack.com/archives/server-health/p1477181591000058)).

I've fixed all those users by setting their `_cronSignature` to `NOT_RUNNING` so they can all log in again, although I expect that some have given up trying. :(  I also made them all be resting in the inn so they won't take damage from missed Dailies.

_EDIT 2017-02-01:_
**The desired fix is that instead of setting `_cronSignature` to the User ID, set it to the current datetime, and then allow cron to run if the value is more than an hour old.**

<strike>We should adjust cron so that either it's impossible for `_cronSignature` to ever be left in an inappropriate state (might not be possible to make the code that robust) or it can recognise when it should run even though `_cronSignature` isn't set to NOT_RUNNING. Perhaps instead of setting `_cronSignature` to the User ID, we could set it to the current datetime, and then allow cron to run if the value is more than, say, an hour old. Other suggestions are welcome of course. :)</strike>

**Comment by Alys** [comment]
I'm seeing this happen more and more, and I haven't seen any reports of it happening again immediately after I've fixed it so I don't think it's caused by any specific problems in players accounts. I.e., it could be more or less random due to currently unexplained timeouts during cron. Obviously we should work out what's causing that and fix it but that might not be easy.

If there's no complaints or better ideas in a day, I'll mark this as help welcome for my suggestion at the end of the top post ("Perhaps instead of setting _cronSignature to the User ID, we could set it to the current datetime, and then allow cron to run if the value is more than, say, an hour old.")

**Comment by KyleVerma** [comment]
Hello. I'd like to take a shot at closing this issue.

One question: is there no worry about a cron still running after an hour?

**Comment by Alys** [comment]
@KyleVerma Thank you!! 

To be honest, it could probably be as little as a few minutes to stop this problem from occurring. Cron really should be over pretty quickly. Anything more than 5 minutes might be too long. I recommend using a variable to hold the time period and then we can adjust it easily if we need to.
