### ISSUE TITLE
Laggy text in iOS and OSX (performance issue?)

### ISSUE THREAD

**Issue by thaenor** [HabitRPG/habitica#8164]
I've noticed that using Habiticia on iPhone and Safari, while writing a post in the tavern or the party chat, it's laggy and the input takes a while to respond. This makes writing a post somewhat annoying experience. Since other players have reported this too (and I've tried logging out, clearing cache and whatnot). I believe this may be a performance issue worth looking into.

I've tried this on Windows/Chrome and I haven't noticed this issue.

**Comment by Alys** [comment]
@thaenor Bugs are best reported through the Help > Report a Bug guild, and I can see you've done that so I'm closing this. There is usually no need to create a GitHub issue unless an admin advises you of that in the Bug guild.

Please see this comment and the ones below it for information about this problem: https://github.com/HabitRPG/habitica/issues/6462#issuecomment-249178348
