### ISSUE TITLE
Tasks for only select days do not become "coloured" by custom day start, but by roll over in date.

### ISSUE THREAD

**Issue by NinKenDo64** [HabitRPG/habitica#817]
For example. I have my custom day beginning at 5am. I have a bunch of tasks due on Thursdays, which are not due Wednesday. However, on Thursday 00:00, these tasks become coloured, rather than greyed out, as they should be, given that my "Wednesday" is, in a sense, still going.

I'm unsure of whether the now coloured tasks are ignored at 5am, or are considered incomplete and therefore penalised, as I have not tested this, but either way, it's confusing when a bunch of tasks I'm not supposed to be doing yet are suddenly coloured in, or tasks that are still assigned to "Wednesday" are greyed out before the custom day start.

**Comment by lefnire** [comment]
fixed by https://github.com/lefnire/habitrpg/pull/811 . will go out in next production push
