### ISSUE TITLE
When I cancel Paypal's automatic renewal, I lose my subscription

### ISSUE THREAD

**Issue by DeveloperHuang** [HabitRPG/habitica#8183]
I became an annual subscribe through Paypal a few months ago,and last month I canceled Paypal's automatic renewal. I found out that I had lost my subscribed status because i can't Buy Gems with Gold

My Habitica user id:ceb60e62-ffe1-436d-94e3-44d8884740cf

**Comment by crookedneighbor** [comment]
Please email your original receipt to admin@habitica.com

**Comment by Alys** [comment]
@DeveloperHuang I'm closing this issue because you've already reported it in the Report a Bug guild and you sent an email based on my response to you there. The bug guild is the best place to report any problem first, and you only need to open a GitHub issue if a moderator asks you to.
