### ISSUE TITLE
Back and Body Accessory battle gear don't add to user's equipment stats / attributes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8185]
When you equip a Back Accessory or Body Accessory as Battle Gear, your attributes aren't boosted by the item's stats (see screenshot below).

_[Guesswork in this paragraph.]_ This is presumably because stats-boosting accessories have only recently been created and the code for calculating and displaying attributes might not take those item types into account. If so, a fix is probably simple: replicate what's been done for the other equipment types. However this might be an opportunity to improve the code to avoid it handling each equipment type individually.

![image](https://cloud.githubusercontent.com/assets/1495809/19992724/1d0c2982-a28c-11e6-8803-e6666c98fa8d.png)

**Comment by Hus274** [comment]
I can take a look into this one!

**Comment by SabreCat** [comment]
Fixed in eaaab35 and de070a4. However, @Hus274's PR includes a bunch more refactoring still worth considering, so no need to close the request.
