### ISSUE TITLE
Participant joins challenge, then creator adds more tasks with Notes -> new user tasks don't get Notes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8189]
If a challenge creator edits the challenge to add a new task and at the same time adds a note to the task, the existing challenge participants get a copy of the new task but with the note missing. The desired behaviour is that when a new task is added to a challenge, the notes field should appear in the users' copies of the task.

Any participants who join the challenge after the new task has been added do receive the notes (that is correct behaviour).

Note that this is NOT referring to the situation where a challenge creator edits an EXISTING task in the challenge's edit screen to add a note to it. In that case the note should NOT be copied to the tasks that are already owned by the participants because the participants might have already added their own notes. I believe this feature works correctly (but have not tested it recently) - it's probably the code for that which is causing the bug for new tasks.

Related issue: https://github.com/HabitRPG/habitica/issues/8004 "Participant joins challenge, then creator adds more tasks -> new tasks aren't tagged"

**Comment by TheHollidayInn** [comment]
@Alys You are correct. My fix only syncs on first adding. The note sync needs to happen when a users has never had the task. 

The logic I added in my PR also needs to go here: https://github.com/HabitRPG/habitica/blob/develop/website/server/models/challenge.js#L119 .

I will fix this during the week if no one beats me to it.

**Comment by majestic-owl448** [comment]
has this been solved?

**Comment by TheHollidayInn** [comment]
Nope! Would you like to fix it?

**Comment by majestic-owl448** [comment]
At the moment I'm in vacation, and I will be for a couple of weeks, if no
one will have approached this issue I could try when I will return

Il venerdì 17 novembre 2017, Keith Holliday <notifications@github.com> ha
scritto:

**Comment by TheHollidayInn** [comment]
@Ieahleen would you still like to take this on?

**Comment by majestic-owl448** [comment]
I don't think I have the time or the ability needed...

2018-01-12 19:22 GMT+01:00 Keith Holliday <notifications@github.com>:

**Comment by TheHollidayInn** [comment]
No worries! Let us know if you want to work on anything else in the future :D

**Comment by TheHollidayInn** [comment]
Hmm. Actually, testing this locally and the scenario seems to work:
1. User is a member of a challenge, leader adds a task with notes, user get task with notes
2. Challenge has tasks, user joins, user get notes of tasks.

**Comment by Alys** [comment]
Confirmed. This bug no longer happens (or it happens intermittently but we can reopen if needed).
