### ISSUE TITLE
There is no music when I enable the music option in Google Chrome.

### ISSUE THREAD

**Issue by Viscerim** [HabitRPG/habitica#8191]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
The audio themes don't have music. They are sound effects when you click on tasks, obtain achievements, etc. More details here: http://habitica.wikia.com/wiki/Audio

We have a guild within Habitica for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). For questions about Habitica features, you can go to Help > Ask a Question on the website (or Guilds > The Newbies Guild on the app; it's not just for new users). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.
