### ISSUE TITLE
Reset Account does not remove attribute points or past stats

### ISSUE THREAD

**Issue by Pexpy** [HabitRPG/habitica#8199]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 4352e75b-0c23-4aa0-b64c-ea82543aa2a3
  * Browser: Firefox 49.0.2
  * OS: Windows 7

### Description
[//]: # I wanted to start using Habitica again after leaving it for a year with a mostly clean slate. Reset Account seemed like the best option to purge everything except years past collectibles. My level has reset however I still have 41 points allocated to Intelligence that shouldn't be there.

My historic exp stats have also not been wiped (The graph that shows up when you click on the graph in the Exp Bar).

I leveled up to 10 to test whether I still gained further attribute points, using Fix Character Values to set to 9 and then made a Habit to level to 10. (I did not.)

I then used Reset Account again. My account reset and then stayed at level 10. I also got a quest tracker for +3 Items for a quest neither me or my party were not on (Dish Disaster) - the party has been defunct for a year.

Group ID: 3918426d-5a0a-42bf-8247-737e890fe32d

I would upload images but I'm only getting the 'Something went really wrong, and we can’t process that file. ' error.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
We have the problem with Reset not unassigning attribute points recorded at https://github.com/HabitRPG/habitica/issues/6482 so I'm going to close this issue. If you'd like to follow the progress of the fix, there's a subscribe button in the right hand column of the issue page.

I've removed the old quest information from your account.

We actually have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.

We actually have a guild within Habitica now for faster reporting of problems and faster fixes or advice. You can get to it from Help > Report a Bug from the website's menu and Guilds > Report a Bug from the mobile app. One advantage of it is that we can see your User ID there and so can often resolve your problem as soon as we've seen your first message.

I think there might be information somewhere on the internet suggesting that this GitHub repository is the best place to report minor problems, so we'll want to change that. Can you please tell us where you found any advice to create an issue here?

**Comment by Pexpy** [comment]
Heya, thanks.

I just remember using this from a year ago when I reported on another issue and got here by browser history. Wasn't aware you had more systems in place since.

**Comment by Pexpy** [comment]
Oh, and would that be the place to go to to fix my account - theres other little things like Perfect Day badges.

I would just Delete Account instead but I've got a good few subscriber items I'd rather not lose.
