### ISSUE TITLE
Estimated Completion Time

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#82]
_wc8: for now, see here: [Importance, Priority, Duration/Difficulty, Deadlines](https://trello.com/c/4C8w1z5h)_
Each daily or todo should have an estimated completion time. If you match the time you actually did the task but if you didn't match the time you didn't do the task properly and you will gain less EXP. This forces people to really think about how time something should take.

**Comment by wc8** [comment]
Hm... I kind of like durations/estimates, but at least in some cases, finishing a task faster should be rewarding. 
EDIT: maybe this could be covered by the Up/Down feature.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization.
