### ISSUE TITLE
Cactus Skeleton Army (Duplicate Bug)

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#820]
Today I happily hatched myself a beautiful skeleton cactus. I then tried to make it my active pet, so that it could gaze endearingly at all of my Party Members with its cold, dead eyes.

Unfortunately, no matter how fervently I clicked, nothing happened. My loyal gold dragon refused to give up her spot at my side. Moreover, it turned out I could make NONE of my other pets into my new active pet. And when I refreshed and opened the stable again, I was shocked to find not one but THREE skeleton cactuses staring out at me! So adorable, but so definitely a bug.

As the icing on the cake, the "Stable" tab is offset from the rest of the tabs :/

**Comment by lefnire** [comment]
Oh man! Definitely a bug, how about now with new layout? And can you select
your pet yet?

**Comment by Shaners** [comment]
First paragraph was great :)

**Comment by lefnire** [comment]
That Lemon, she's a writer in a previous life :)

**Comment by lemoness** [comment]
Or in this one ;p Thanks, guys!

The bug is solved by the new layout, but I do have some issues with how it
is currently presented; I'm going to make a post about that later today in
the other thread.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
