### ISSUE TITLE
list of subscription plans is wrong

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8209]
At Site > Subscription, the 1-month plan occurs three times, once with a listed charge of $48:

![image](https://cloud.githubusercontent.com/assets/1495809/20245047/e7c2dfa6-a9e2-11e6-8ec2-ba88a2af8a8a.png)

.

The same incorrect text appears when you give someone a subscription:

![image](https://cloud.githubusercontent.com/assets/1495809/20245066/3848855c-a9e3-11e6-872d-c4dcc8deb960.png)

**Comment by crookedneighbor** [comment]
@thehollidayinn is this because of the changes you've made?

**Comment by paglias** [comment]
Yes, it's probably related to https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/index.js#L2680-L2687
