### ISSUE TITLE
Authentication parameters in url instead of headers

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#821]
Hello,

Would it be difficult to allow a syntax as follow ?

```
curl https://<user-id>:<api-key>@habitrpg.com/api/v1/user/tasks?type=habit
```

This is the syntax adopted on other API, eg Github.
I request this feature in order to be able to pull HabitRPG data in my [hubble dashboard](https://github.com/jaymedavis/hubble) (it does not accept custom headers for the url to pull atm)

Thanks for considering it :)

**Comment by negue** [comment]
So should we accept this kind of authentication? Or close it?

**Comment by paglias** [comment]
Maybe we should allow this as query parameters

**Comment by Alys** [comment]
I'm very much against putting passwords (such as the API token) in URLs. URLs are stored in browser history, web server logs, etc and can be sniffed in transit. It's very insecure. 

The uuid and token gives full access to your account, which means that anyone finding them can read all your private information (including messages from other users!) and can delete your entire account. I understand that some users might be willing to accept this risk, but there will also be many non-technical users who don't understand the risk and it would not be responsible to allow them to unwittingly expose themselves to it.

Even if we ensured that the users using such a URL had understood and accepted the risk, it would still be exposing the private messages that other users had sent to them (and those other users might not have chosen to accept this risk).

The ideal situation is for applications that don't understand custom headers to be modified to understand them, or for alternative applications to be used. I realise that this is not always possible, but I don't think that's reason enough to add an insecure feature to our site.

Hence I'm closing this. It can be reopened if it's still desired but I strongly recommend against that.
