### ISSUE TITLE
pet and mount names are not being translated

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8210]
In the Pets and Mounts pages, the colour (`potion`) and breed (`egg`) of a pet or a mount are not translated, even though translations exist in the locales files for many languages. See screenshot below.

The problem seems to lie within these bits of code:

https://github.com/HabitRPG/habitica/blob/9aa4b8aa64ccdfa3af4a6832cc3dded4b102b73e/website/common/locales/en/pets.json#L74-L75

https://github.com/HabitRPG/habitica/blob/9aa4b8aa64ccdfa3af4a6832cc3dded4b102b73e/website/common/script/content/stable.js#L35-L42

The `(locale)` part in the strings (first link) doesn't seem to be taking effect.

----

### What to do if you notice this for your language:

We know that this issue affects all languages so you do NOT need to comment below or report it anywhere else. When this is fixed, the fix will work for all languages at once.

----

![image](https://cloud.githubusercontent.com/assets/1495809/20245170/529c94f8-a9e7-11e6-83c0-e53c9e4e0227.png)

**Comment by Alys** [comment]
The forgotten screenshot:

![image](https://cloud.githubusercontent.com/assets/1495809/20245170/529c94f8-a9e7-11e6-83c0-e53c9e4e0227.png)

**Comment by khipkin** [comment]
I thought that the "(locale)" strings in the json files was just meant to act as a reminder to also localize the parameters before passing them in.  Are they actually supposed to cause additional code to run?

**Comment by paglias** [comment]
It's meant to specify the language that should be used for the translation

**Comment by lynxlynxlynx** [comment]
That's a pretty unfortunate design, as we have to remind translators all the time to leave tags alone. This would then be an exception.

**Comment by Alys** [comment]
@lynxlynxlynx No, translators are not meant to modify the `(locale)` part of the tags (nor any other parts). It's handled by code. See the `eggNotes` strings in `content.json` for examples. In those, `(locale)` has never been modified for any language but the translations work.
