### ISSUE TITLE
Some mount image backgrounds are not transparent

### ISSUE THREAD

**Issue by mchlltt** [HabitRPG/habitica#8215]
General Info
  * UUID: 804ca182-f16c-4ff5-b115-d73cdba94935
  * Browser: Chrome
  * OS: Windows 7

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

First off -- this is unlikely to be a priority, since it's noticeable to me because I sometimes use extensions that change pages' backgrounds colors ([Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) or Stylish themes), but I wanted to point out that some mount images are not transparent on the Mounts page and instead have white backgrounds. I've discovered that the issue is that these mounts are shown via [this group of sprites](https://github.com/HabitRPG/habitica/tree/develop/website/assets/sprites/spritesmith/stable/mounts/icon), of which about has 10-20% have non-transparent backgrounds (e.g., [this image](https://github.com/HabitRPG/habitica/blob/develop/website/assets/sprites/spritesmith/stable/mounts/icon/Mount_Icon_FlyingPig-Zombie.png).)

If, as it appears to me, solving this issue would only require all affected sprites to have their backgrounds removed and reuploaded, I'd be happy to take care of this.

This shows an example of what the Stable page looks like to me: 
![image](https://cloud.githubusercontent.com/assets/15218445/20277790/a46f1230-aa67-11e6-933c-807bfeb95cd3.png)

This shows which all sprites have white backgrounds currently. ([via](https://habitica.com/spritesmith-main-11-b1637069.png))
![image](https://cloud.githubusercontent.com/assets/15218445/20277395/f96e8b82-aa65-11e6-961e-c150223f0cf1.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
N/A

**Comment by Alys** [comment]
Could you modify just one mount and do a PR for it and we'll get an Artisan to make sure there's nothing wrong? Then you'd be free to add them all to the PR, without concern that your time might be wasted.

**Comment by crookedneighbor** [comment]
FYI, this is just for the mount icon image (that is displayed on the mount page), not the one used for the mount itself.

**Comment by mchlltt** [comment]
Yes, apologies for not specifying this.
