### ISSUE TITLE
Automatic guild leader transfer not working as intended

### ISSUE THREAD

**Issue by Dewines** [HabitRPG/habitica#8222]
If a guild leader leaves their guild or deletes their Habitica account, the leadership used to transfer automatically to the guild member who had been in the guild longest. However, during the last major update to Habitica, the guild members are no longer displayed in the order of joining. This means that now, when a guild leader leaves the guild, the leadership is automatically passed to a totally random member, even if they only joined Habitica a few days ago.

I noticed that this had happened when a new player had become the leader of a small guild after the original leader left the guild. Because it was so small and because it was a guild I was watching for an answer to a question I had posted there, I saw that someone new had taken over, despite other players having been in the guild much longer.

In the case I observed, it wasn't important because the guild had never got off the ground, but it could be a problem if the same thing happened in a busy, well-established guild. The guild leader has the power to throw people out of the guild, which presumably also throws them out of any guild challenges!

My suggested solution would be that whenever a guild leader leaves the guild or deletes their account, the leadership is automatically passed to an account called something like @NoLeader which would be under the control of one or more mods. This would a) prevent the guild falling into the hands of someone who didn't want it and who might not even realise they are now leader and b) will make it much easier for @Alys and the Habitican Pirates to spot a leaderless guild and do something about it. This has been discussed on the relevant Trello card, but I've just realised that as the automatic transfer is not working as originally intended, this is rather more urgent than a possible future improvement.

------

_edit by Alys:_ A similar problem exists for challenges: when a challenge owner deletes their account, the challenge should become marked as not having an owner so that we can easily find it and close or adopt it.

**Comment by Alys** [comment]
I agree that automatic transfer of guild leadership is no longer desirable, not only because a randomly selected leader can be bad, but also because the Pirate Cove guild has good processes in place to help guilds find a suitable new leader, and those processes would work better if automatic leadership changes weren't made (e.g., an automatically-assigned new leader can mask the fact that a guild has been effectively leaderless for a long time).

I think the feature should work the same way for public guilds, private guilds, and parties, for code consistency and to reduce player confusion.

If leadership was passed to a mod-owned account, that account would have to be made a member of the guild. That's not a problem for public guilds, but it's concerning for private guilds and parties because moderators try to avoid peeking into private groups unless it's essential (which is very rare).

From that point of view, it might be better to allow guilds to become literally leaderless. The group's `leader` field would be empty, and when that occurred, the website and mobile app would display a message explaining what had happened and giving instructions about how to have a new leader chosen. For private groups, any discussion about the new leader could occur outside the group and a database admin could assign a new leader without needing to see the group's chat or description. (The disadvantage is that non-admin moderators would not be able to select a new leader, but they couldn't do that anyway if the new leader didn't appear in the list of 30 members visible on the website, at least until we fix that problem too.)

However having no `leader` value might be a breaking change for the API.

Opinions welcome!

**Comment by Dewines** [comment]
That is a good point about mods gaining access to a private guild or party. I hadn't thought of that because I'd only considered the problem from the point of view of public guilds. 

If having no leader value might be a problem from the programming angle, would it be possible to have some sort of dummy account called @NoLeader that no one actually has access to but as far as the code is concerned is a person? If that makes sense?

**Comment by Alys** [comment]
Oh, yes, of course, we could create a NoLeader account, set up its profile to explain what it is, and then randomise the password if we wanted to be sure mods couldn't use it to access private groups.

It would be a smaller code change to add that account to the group and set the leader to it than to allow guilds to have no leader.

Unless there's other suggestions or objections in the next couple of days, I'll mark this as Help Welcome for that solution.

**Comment by cmajames** [comment]
Any sort of dummy account feels like a security hazard. Random passwords aren't sufficient to guarantee 'no access'; something else in the code would have to do that. @Alys, are NPC accounts secure in this fashion?

**Comment by crookedneighbor** [comment]
I agree that having an actual account to represent `NoLeader` is not the way to go. The code should just be adjusted to handle the case where there is not a leader (IE, provide dummy values for the fields that get populated for the user in the group).

`NPC` users, the ones with the black background on their names, are real users, not bots, who backed the original kickstarter project.

**Comment by Alys** [comment]
So to summarise so far, the desired fix for this is that when a guild leader leaves the guild or deletes their Habitica account:
- Remove the current code that automatically chooses a new leader
- Make the guild's `leader` attribute be an empty string or null or some other non-UUID value or possibly a placeholder UUID that doesn't correspond to a real account - **decision needed**
- In the guild's page:
  - Adjust the "guild leader" text on the left-hand column to contain an explanatory message
  - If the guild has a `leaderMessage` (the text that appears in a box above the chat text entry box) then the leader name section of that box should also contain the explanatory message
- The explanatory message should be something like this: "This guild does not have a leader." We might add instructions for finding one. (_Talk to the Pirate Cove? Report it in the Bug guild? Sit tight and wait for a mod/Pirate to contact the guild?_)
- **Suggestion**: Send a message to the moderator Slack. The mods could then start the process for finding a new leader. That might affect the instructions we put in the explanatory message.
- **Suggestion**: If the guild is set to allow challenges to be created by only the guild leader, change that setting. I think this will be most useful and friendly for the guild members. The new leader could change it back again if they wanted to.

For the case where a guild leader edits the guild to select a new leader before leaving, no changes are needed. That's working as desired. 

Comments / disagreements welcome!

@vIiRuS Will the iOS and Android apps need to be changed to cope with a guild having no player specified in its `leader` attribute? If anyone is using an old version of the app, will the absence of a leader cause a crash or serious error, or just result in the leader section of the app looking odd? How the apps behave might control how we indicate the no-leader status in the database.

**Comment by citrusella** [comment]
@Alys I'm no vIiRuS, but for the end user, the Android app only *displays* the leader's name if there's a leader message. Of course, this may have no bearing on how the app processes no leader in ways one *can't* see, but I felt like mentioning it anyhow?

**Comment by Alys** [comment]
@citrusella Oh, thank you! That's good to know. I've logged a request to add the leader's name: https://github.com/HabitRPG/habitica-android/issues/666

**Comment by Alys** [comment]
A similar problem exists for challenges: when a challenge owner deletes their account, the challenge should become marked as not having an owner so that we can easily find it and close or adopt it.

I've updated the top post to include this note.

**Comment by veeeeeee** [comment]
Our current understanding is that this process now is being handled through GuildBot and the Pirate Cove. Should this issue remain open? @Alys

**Comment by Alys** [comment]
@veeeeeee yes, @cTheDragons 's GuildBot process is working well for guild leaderships. If you're happy for that to be the approved way to handle this issue, then I think this could be closed.

For challenges, https://github.com/HabitRPG/habitica/pull/11798 caused "no owner" to be displayed on orphaned challenges, which is good.
