### ISSUE TITLE
buying gems with gold gives two notifications when language is not 'en'

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8227]
If you set your language to some of the non-English languages and then go to the Market to buy a gem with gold, you receive two notifications for `+1 gem`, one in your chosen language and then after a short delay, another one in English:

![image](https://cloud.githubusercontent.com/assets/1495809/20452491/a51d3958-ae56-11e6-82d6-a3199da10001.png)

I've tested a few languages and it happens with only those that have a translation for the `plusOneGem`  text that is different than the English version. For example, it happens with German and French, but not with `en_GB`, `en@pirate`, or `zh_TW` all of which still use the default text: `"plusOneGem": "+1 Gem"`

**Comment by khipkin** [comment]
Possible [translations] issue?

**Comment by lynxlynxlynx** [comment]
Since I was looking at gems: This is the plusOneGem string in the "purchase" API call. Quite interesting, as it is also the only user besides a test.

**Comment by mjackson714** [comment]
I can work on this

**Comment by mjackson714** [comment]
If no one has claimed it

**Comment by Alys** [comment]
@mjackson714 Thank you! Please do.

**Comment by sjyn** [comment]
I was able to get the bug to be reproduced. To do this, I had to "trick" habitica into thinking it was purchasing gems.

In the file `/website/common/script/ops/purchase.js` you need to change

```javascript
let type = _.get(req.params, 'type');
let key = _.get(req.params, 'key');
```
to

```javascript
let type = 'gems';
let key = 'gem';
```
and comment out or remove the lines

```javascript
    if (!user.purchased || !user.purchased.plan || !user.purchased.plan.customerId) {
      throw new NotAuthorized(i18n.t('mustSubscribeToPurchaseGems', req.language));
    }

    if (user.stats.gp < convRate) {
      throw new NotAuthorized(i18n.t('messageNotEnoughGold', req.language));
    }

    if (user.purchased.plan.gemsBought >= convCap) {
      throw new NotAuthorized(i18n.t('reachedGoldToGemCap', {convCap}, req.language));
    }
```
(this will break all other purchasing I believe)
In `/website/client-old/js/services/userServices.js` I changed (around line `378`)

```javascript
          $http({
            method: "POST",
            url: 'api/v3/debug/add-ten-gems',
          })
          .then(function(response) {
            Notification.text('+10 Gems!');
            sync();
          })
```
to

```javascript
          $http({
            method: "POST",
            url: 'api/v3/debug/add-ten-gems',
          })
          .then(function(response) {
            var type = 'gems';
            var key = 'gem';
            callOpsFunctionAndRequest('purchase', 'purchase', "POST", type + '/' + key, {});

            Notification.text('+10 Gems!');
            sync();
          })
```
After making these changes and switching my language to French, I could click the `+10 gems` button and have the error occur

**Comment by myoshuGO** [comment]
@mjackson714 @Alys I would like to work on this. It's ok for you if I try to fix this?

**Comment by Alys** [comment]
@myoshuGO Thank you! Please go ahead!
