### ISSUE TITLE
URLs in challenge titles are rendered as links

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#8228]
General Info
  * Browser: Chrome 54, 64bit 
  * OS: Windows 7

### Description
If a link (i.e. https://github.com) is used in the challenge's title, when you click on the link in the challenge name (for example in the challenge list or in challenges section of a guild), the link opens the URL and not the challenge. Potential problem: if the title of a challenge is just an URL, probably there would be no way to access the challenge.

### Screenshots
_(cursor was hidden by the screenshot software, see descriptions)_
- Cursor on the URL part of the title
![1](https://cloud.githubusercontent.com/assets/6122017/20481871/b9aa786a-afe9-11e6-9262-5e7cccfd7016.PNG)

- Cursor on the non-URL part of the title
![2](https://cloud.githubusercontent.com/assets/6122017/20481895/d97e4e96-afe9-11e6-8d7b-e8cad20ad6eb.png)

**Comment by crookedneighbor** [comment]
This is expected behavior for the markdown parsing. I recommend putting the link in the challenge description instead.

**Comment by Alys** [comment]
One problem though would be that if the challenge creator uses nothing but a link in the title, they can't then get into the challenge to edit it or close it, if the challenge title always points to the off-site URL.

However I can't replicate this link behaviour in Chrome (albeit on a Linux box). When I hover over the exercism.io link, the browser's status bar does act as if my mouse is on a link to that site, but if I click there, I'm taken to the challenge's page.

@Atomk Can you confirm that actually clicking on `http://exercism.io/` does takes you to that website?

Guild URL for anyone else who might want to test: 
https://habitica.com/#/options/groups/guilds/e655bb46-96ec-4d8b-b40d-f195063904c8

**Comment by Deebster** [comment]
On Chrome/Windows 10 I see the link as reported, but single-clicking both on and after the url goes to the Habitica link.

Middle-clicking or going via the right-click context menu does (unsurprisingly) go to the embedded link.

**Comment by crookedneighbor** [comment]
I would argue that the markdown parser is acting as intended. If we don't want it to behave that way, we should require that titles not contain urls or not render them as markdown.

**Comment by Alys** [comment]
Agreed. As long as single-clicking the link opens the challenge page, the behaviour is correct.

Allowing all markdown in the challenge title is good.

**Comment by Atomk** [comment]
@Alys sorry for the late response, thanks to @Deebster I figured out that this behaviour happens if I click on the challenge title with the center mouse button (the mouse wheel) which is a shortcut for "open in a new tab", using the primary mouse button everything works properly.
I'm so used to open links this way I didn't even notice, sorry. I guess everything is okay then :)

**Comment by Alys** [comment]
@Atomk No worries, I understand about being in that habit! Thanks for letting us know!

**Comment by cTheDragons** [comment]
Hi all! Just adding to the conversation, a full url is not required to render the inability to open a challenge by either by left or right mouse clicking the link. In the [The Renaissance Man](https://habitica.com/#/options/groups/guilds/08a6022c-f62e-4672-bdfc-0050b3ab3d83) there is a couple of challenges called diy.org. Left or right mouse clicking the links in the challenge box left of the guild chat causes the user to open the site diy.org.

The only way to open the challenge is to 
+ [Join the Guild](https://habitica.com/#/options/groups/guilds/08a6022c-f62e-4672-bdfc-0050b3ab3d83)
+ Go to [Social => Challenges](https://habitica.com/#/options/groups/challenges)
+ Search for the challenge and click on the links there.

Considering that owner here did not realise putting two words with a dot in between would render it to url, should we at least warn future challenge owners of creating challenges with a link (or what can be considered as a link). Or just force to put a space in between?

Here is the link ids for the challenges in questions
+ [Challenge 1](https://habitica.com/#/options/groups/challenges/15bd551e-71be-4861-8fe1-45688b914458)
+ [Challenge 2](https://habitica.com/#/options/groups/challenges/84309a79-9a12-48d2-b3cc-bae7cefd9b71)


## General Info
Opera 42.0.2393.85
Windows 10 32-bit
