### ISSUE TITLE
Android app won't sync with HabitRPG web

### ISSUE THREAD

**Issue by andrew84** [HabitRPG/habitica#823]
Hey guys!

I love what you've done with HabitRPG, and I especially love the LifeRPG port you've made to Android! It's super-cool, and I especially love the new style you've put on some of the graphics, while keeping others the same.

I've paid for the premium feature pack of LifeRPG, but I can't get the android client to sync to HabitRPG, despite it being one of the features. When I copy in my user and app key it just seems to hang, and eventually I have to force-quit the app to restart it.

I'd really love any insights you might have here.  I've made a video of my attempts here: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by wizonesolutions** [comment]
LifeRPG isn't provided by HabitRPG. I'd ask them.

**Comment by lefnire** [comment]
Yeah, that app is not affiliated with HabitRPG. Pretty frustrating too, they made a replica of our site (without using the website's API, and not giving credit) and then branded themselves with "LifeRPG", an already trademarked name (a competitor to Habit). See my [rant here](https://play.google.com/store/apps/details?id=com.eikosol.liferpg&reviewId=Z3A6QU9xcFRPSGYxSGZRSFY2YUpYU2kyR3FSVzVkMm44NmV3LWFYblY5ME52aVZIb2NxU3YxaF9jRExLUmNOb2NpRENwUFgzVS1JcENjcEQtbmNJWkw0M0E), and the real LifeRPG [here](http://www.reddit.com/r/liferpg)

**Comment by andrew84** [comment]
Oh! But there's clearly provisions for hooking into HabitRPG in the app. You can see them in the video I linked to.

**Comment by heyimzsa** [comment]
I think this is a troll, hence the video being 'never going to give you up'
—

**Comment by pjf** [comment]
Pretty sure Rick Astley would lose HP if he ever let you down, or deserted you. ;)

**Comment by wizonesolutions** [comment]
Someone's got a strange sense of humour.

And by someone, I mean @andrew84 (notwithstanding @pjf :P).
