### ISSUE TITLE
Experience (XP) gain not shown when reaching a new level

### ISSUE THREAD

**Issue by afino** [HabitRPG/habitica#8232]
General Info
  * UUID: e6350942-4808-4b1b-8abe-99d646f608d9
  * Browser: Vivaldi 1.5.658.42 (based on Chromium)
  * OS: Windows 7 Professional 64 Bit

### Description

Whenever you grow to a new level after you completed/checked a task, your XP gain for this task is NOT displayed with the other messages in the upper right corner. All other messages show up (health gain, gold, mana, found items), but not the XP gain. That's a pity, because it makes it rather difficult to reconstruct how many XP you gained for that last task that you completed, which can be quite demotivating.

I've documented this with screenshots for 28 levels, so it is reproduceable (and is annoying every time). Here's the link to my latest [screenshot](http://flopages.de/habitica/level-up-xp-gain.jpg)

**Comment by 32gits** [comment]
I would like to tackle this as my first contribution

**Comment by khipkin** [comment]
@32gits Just some advice from another contributor, but you should wait to start on this until a staff member confirms it as a desired change.  No one wants their efforts to go to waste!  You can find some issues that are ready to be worked in if you look at the "Help Wanted" labeled issues.

**Comment by 32gits** [comment]
Cool thanks

**Comment by Alys** [comment]
@khipkin Thanks!

I'm marking this as on hold because we're planning some improvements to the website that might affect how the notifications work.

**Comment by librarianmage** [comment]
Is this still an issue? If so, should it still be on hold?

**Comment by Alys** [comment]
I'm closing this because we have this issue now: https://github.com/HabitRPG/habitica/issues/9339
It's not exactly the same thing but it's close enough and once it's fixed, if there's still a problem we can reopen this issue or make a new one.
