### ISSUE TITLE
Incorrect text for read older news on 'New Stuff by Bailey' Page.

### ISSUE THREAD

**Issue by Hus274** [HabitRPG/habitica#8233]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
The New Stuff By Bailey pop up looks like it has incorrect text at the bottom currently. Looks like there's a possible missing translation for 'newsArchive'

<img width="902" alt="screen shot 2016-11-23 at 6 17 17 am" src="https://cloud.githubusercontent.com/assets/17734753/20565081/f1892950-b144-11e6-8fe2-7de3f06f2640.png">

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by khipkin** [comment]
This is a known issue, and @Alys already removed the broken link in https://github.com/HabitRPG/habitica/commit/ab4c8b0a468a094d957a6e9b93d99268e5208089.  The issue is currently being tracked in #5365 and #8216.

**Comment by Alys** [comment]
@Hus274 Thanks for letting us know though! I'm going to leave this issue open so it's more visible to anyone else who might want to report it.

**Comment by Alys** [comment]
Text has been deleted.
