### ISSUE TITLE
"Progress until next NaN/NaN" is showing in User > Profile (Daily Checkin Incentives)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8235]
On the User > Profile page, the Daily Checkin Incentives progress shows as "Progress until next NaN/NaN":

![image](https://cloud.githubusercontent.com/assets/1495809/20595229/dcc5c6d6-b284-11e6-9ab3-44cd8bf30a60.png)

**Comment by TheHollidayInn** [comment]
Is this just on your account or do you have reports from others, @Alys ?

**Comment by 32gits** [comment]
My profile on the website is fine, but my local build is showing NaN/NaN.

**Edit:**
Also in relation, it might be good to add a "+1 Check-In" to the debug menu.

**Comment by Alys** [comment]
There was a report from someone else, and it was happening on both my accounts. It's not happening today on my accounts (I have "Progress until next 1/2").

**Comment by Alys** [comment]
"Progress until next NaN/NaN" appears when `loginIncentives` is less than 2 (i.e., for all new users from now on until after their second cron).

**Comment by TheHollidayInn** [comment]
@Alys Okay, I think I know the issue then. Thanks! I'll post a fix later today.
