### ISSUE TITLE
Unable to successfully run 'npm install'

### ISSUE THREAD

**Issue by 32gits** [HabitRPG/habitica#8236]
OS: Ubuntu 16.04 LTS

### Description

Every time I try to run `npm install` I get the following output:

```
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

I've also tried with the newer versions of node and npm. I have updated my config.json and package.json with the latest files in the GitHub source code.

**Comment by gruentee** [comment]
I'm experiencing the same issue.

```
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/package/host/localhost/nodejs-6.9.1/bin/node" "/package/host/localhost/nodejs-6/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Comment by paglias** [comment]
You have to installare NPM >= 3.10.10

Il 24 Nov 2016 22:17, "Constantin" <notifications@github.com> ha scritto:

**Comment by gruentee** [comment]
@paglias OK, thanks. I'll update and try again.

**Comment by 32gits** [comment]
@paglias I've tried with npm v4, do I specifically need 3.10.10?

**Comment by paglias** [comment]
NPM 4 is okay. 3.10.8 and 3.10.9 have a bug that prevent it from working

Il 24 Nov 2016 23:20, "32gits" <notifications@github.com> ha scritto:

**Comment by 32gits** [comment]
@paglias this is not closed. like I said, I've tried with npm4 already.

**Comment by paglias** [comment]
Sorry, can you try pulling the latest changes from GitHub and cleaning your npm cache? We build Habitica on Linux multiple times a day and it works fine

**Comment by 32gits** [comment]
I was able to fix this issue. I thought I had updated my branch properly, but then followed these steps in [Using Habitica Git](http://habitica.wikia.com/wiki/Using_Habitica_Git) and it worked while running nodejs 7 and npm 4:

---
Rebase Branch 
====================

When you want to update your local branch, you need to rebase it from the upstream branch. Let's update develop:
```
git checkout develop
git fetch upstream
git rebase upstream/develop
git push  # to update your fork in GitHub
```
---
It now sees fsevents as an optional dependency and ignores the error:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.15 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by JalanshMunshi** [comment]
@paglias 
Running `npm i` pops the `EBADPLATFORM` error.
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```
I fetched the latest code after the MongoDB update and then executed `npm i`. It seems that my system is not considering `fsevents` to be an optional dependency, in spite of optional being set to `true` in `package-lock.json`. 

I tried the steps mentioned above. `npm` strongly advised me to not clean cache. The node and npm versions are also 12 and 6 respectively. And fore some reason, the [build](https://github.com/JalanshMunshi/habitica/runs/880734849) is also failing for my develop branch on my repo.

```
npm ERR! get-func-name not accessible from chai

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-07-17T06_32_38_656Z-debug.log
##[error]Process completed with exit code 1.
```

What can I do to fix this? My system is Ubuntu 18.04. Ubuntu and Windows are present in parallel on my dualboot system. However, the local install was working perfectly fine earlier and I don't think my OS could be an issue here. What do you think?

**Comment by paglias** [comment]
Hmm the build is passing correctly here on Github Actions using Linux and it seems that your develop branch has diverged from the one here 
<img width="636" alt="Schermata 2020-07-17 alle 12 07 45" src="https://user-images.githubusercontent.com/589911/87775338-37480280-c826-11ea-9233-837e9de39d33.png">

I would try to hard reset your branch to match the one here (if you don't have any pending change - depending on how it was setup `git fetch && git reset --hard upstream/develop` should work), delete `node_modules` both at the top level and under `website/client` and try to reinstall

**Comment by paglias** [comment]
Let me know how that goes @JalanshMunshi , if it still doesn't work I'd try to also delete `package-lock.json` and reinstall everything

**Comment by JalanshMunshi** [comment]
@paglias Hard reset worked like a charm! :smiley: 

One question. I should fix the merge conflicts in package-lock.json and commit it, right? I always get conflicts in that file and that leads to a lot of `git rebase --continue` commands pushing the commits to my develop branch.

**Comment by paglias** [comment]
@JalanshMunshi good question, unfortunately package-lock.json seems to get generated differently based on the OS, npm version, ... so my suggestion would be to either use the generated one from the upstream branch (so don't delete it but simply run `npm i` and it should use the existing one) otherwise I'd probably try not to commit changes to it at all, so as soon as you've run `npm i` I'd remove the changes to package-lock.json

**Comment by paglias** [comment]
In general as long as there have been no changes to dependencies (a new dependency or a major upgrade), package-lock.json should not change

**Comment by JalanshMunshi** [comment]
Alright, got it! Thanks!
