### ISSUE TITLE
Todo checklist not editable

### ISSUE THREAD

**Issue by gruentee** [HabitRPG/habitica#8238]
General Info
  * UUID: 43bc1fee-4ba0-4924-8968-43cfc2ee57c9
  *  Browser: Firefox and Chromium
  * OS: Linux

### Description
A checklist is not editable anymore, once created. 
After clicking the "toggle checklist button" a click on the "Add checklist" button has no effect and produces the console errors shown in attached logs.

![auswahl_021](https://cloud.githubusercontent.com/assets/923759/20648462/1e7ce95e-b4a8-11e6-9d61-a039c8e49b36.png)
![auswahl_022](https://cloud.githubusercontent.com/assets/923759/20648464/1ec267f4-b4a8-11e6-8866-e49bca0813e5.png)

#### Console Errors
Firefox 50.0

```
"Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
z/<@https://habitica.com/app-8eeffbdc.js:36:16413
w.authenticate@https://habitica.com/app-8eeffbdc.js:49:10595
@https://habitica.com/app-8eeffbdc.js:49:11823
i@https://habitica.com/app-8eeffbdc.js:7:17928
c@https://habitica.com/app-8eeffbdc.js:7:16324
i@https://habitica.com/app-8eeffbdc.js:7:17928
Tb/j.$injector<@https://habitica.com/app-8eeffbdc.js:7:15974
g@https://habitica.com/app-8eeffbdc.js:7:17563
i@https://habitica.com/app-8eeffbdc.js:7:17897
ic/this.$get</</<@https://habitica.com/app-8eeffbdc.js:8:9483
na/<@https://habitica.com/app-8eeffbdc.js:8:3817
x@https://habitica.com/app-8eeffbdc.js:6:25110
na@https://habitica.com/app-8eeffbdc.js:8:3801
r@https://habitica.com/app-8eeffbdc.js:7:30325
b@https://habitica.com/app-8eeffbdc.js:7:29373
a/<@https://habitica.com/app-8eeffbdc.js:6:31576
wd/this.$get</j.prototype.$eval@https://habitica.com/app-8eeffbdc.js:9:17443
wd/this.$get</j.prototype.$apply@https://habitica.com/app-8eeffbdc.js:9:17677
a@https://habitica.com/app-8eeffbdc.js:6:31534
i@https://habitica.com/app-8eeffbdc.js:7:17928
xa/g@https://habitica.com/app-8eeffbdc.js:6:31453
xa@https://habitica.com/app-8eeffbdc.js:6:31763
wa@https://habitica.com/app-8eeffbdc.js:6:30986
@https://habitica.com/app-8eeffbdc.js:11:1778
o.Callbacks/j@https://habitica.com/app-8eeffbdc.js:3:27711
o.Callbacks/k.fireWith@https://habitica.com/app-8eeffbdc.js:3:28529
.ready@https://habitica.com/app-8eeffbdc.js:3:30321
I@https://habitica.com/app-8eeffbdc.js:3:30491
"  app-8eeffbdc.js:36:15999
Error: a._edit is undefined
L@https://habitica.com/app-8eeffbdc.js:48:20117
g@https://habitica.com/app-8eeffbdc.js:9:4793
b/</e@https://habitica.com/app-8eeffbdc.js:10:12833
wd/this.$get</j.prototype.$eval@https://habitica.com/app-8eeffbdc.js:9:17443
wd/this.$get</j.prototype.$apply@https://habitica.com/app-8eeffbdc.js:9:17677
b/<@https://habitica.com/app-8eeffbdc.js:10:12892
o.event.dispatch@https://habitica.com/app-8eeffbdc.js:4:7090
o.event.add/r.handle@https://habitica.com/app-8eeffbdc.js:4:3900
  app-8eeffbdc.js:8:25945
```
Chromium 54.0.2840.100 (64-bit)

```
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at t.zone (https://habitica.com/app-8eeffbdc.js:36:16413)
    at Object.authenticate (https://habitica.com/app-8eeffbdc.js:49:10604)
    at Object.<anonymous> (https://habitica.com/app-8eeffbdc.js:49:11825)
    at Object.i [as invoke] (https://habitica.com/app-8eeffbdc.js:7:17930)
    at Object.c [as $get] (https://habitica.com/app-8eeffbdc.js:7:16326)
    at Object.i [as invoke] (https://habitica.com/app-8eeffbdc.js:7:17930)
    at https://habitica.com/app-8eeffbdc.js:7:15976
    at g (https://habitica.com/app-8eeffbdc.js:7:17563)
    at Object.i [as invoke] (https://habitica.com/app-8eeffbdc.js:7:17897)
    at D.instance (https://habitica.com/app-8eeffbdc.js:8:9485)
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
TypeError: Cannot set property 'checklist' of undefined
    at a.L [as addChecklist] (app-8eeffbdc.js:48)
    at g (app-8eeffbdc.js:9)
    at e (app-8eeffbdc.js:10)
    at a.$eval (app-8eeffbdc.js:9)
    at a.$apply (app-8eeffbdc.js:9)
    at HTMLButtonElement.<anonymous> (app-8eeffbdc.js:10)
    at HTMLButtonElement.dispatch (app-8eeffbdc.js:4)
    at HTMLButtonElement.r.handle (app-8eeffbdc.js:4)
```

**Comment by Alys** [comment]
Those console log messages are just warnings, not errors, and you can ignore them.

To add a new checklist item, put your cursor in the final item then hit enter on the keyboard. Sorry it's not obvious! We're intending to make it clearer.

We have guilds within Habitica now for faster ways of getting help. If you have questions about how  to use features in Habitica, you can go to Help > Ask a Question on the website (or Guilds > The Newbies Guild on the app; it's not just for new users). If you find a bug, you can report it at Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that in the Report a Bug guild.

**Comment by gruentee** [comment]
@Alys, thanks for the quick response. 

> Those console log messages are just warnings, not errors, and you can ignore them.

This applies for the deprecation warnings, but the last one (`TypeError`) is indeed one, isn't it?
It is thrown when clicking on the "Add check list button" after toggling off (hiding) the checklist items in edit mode. 

> To add a new checklist item, put your cursor in the final item then hit enter on the keyboard. Sorry it's not obvious! We're intending to make it clearer.

I agree, this is not obvious at all and should be changed.

**Comment by Alys** [comment]
Yes, sorry, I missed the TypeError message, which is an error, not a warning. It won't occur when we improve how the checklists are presented. I expect we won't show the button to add a checklist when a checklist has already been added.
