### ISSUE TITLE
extra, misaligned paw print for Royal Purple pets (from Daily Check-In Incentives hatching potions)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8239]
When you have hatched one pet with a Royal Purple hatching potion, the line of paw prints contains 10 paws (should be 9) and one is misaligned.

It's also inconsistent with how the other Magic Potion pets are displayed. They don't show paw prints unless you own potions to create new pets - that was added in https://github.com/HabitRPG/habitica/pull/7911

![image](https://cloud.githubusercontent.com/assets/1495809/20651635/833cce18-b534-11e6-9550-e59ec292c78f.png)

----

#### What to do if this happens to you:

We know that this happens to all players equally so you do **not** need to comment here. When it's fixed, the fix will appear automatically on you Pets page.

**Comment by Alys** [comment]
In my personal opinion, removing the extra, misaligned paw print is more important than making the hiding/showing of the prints consistent with the other Magic Potion pets. We're going to keep on getting questions and bug reports in the Tavern, Newbies, and Bug guilds while the misaligned print is there.

**Comment by SabreCat** [comment]
Fixed in c7039bc9ea51b. Misplaced close parenthesis :p
