### ISSUE TITLE
Incorrect amount of pets found

### ISSUE THREAD

**Issue by FiXato** [HabitRPG/habitica#824]
The avatar overlay shows "0/90 pets found" even though I do have a base fox as clearly shown in the avatar:
![HabitRPG-0_pets_found](https://f.cloud.github.com/assets/4342/381096/23b6559a-a5d9-11e2-85d9-078ae3140ab1.png)

**Comment by lefnire** [comment]
gah, rookie programmer 0-index mistake. will go out with next push
