### ISSUE TITLE
Logging in with Chrome gives anonymous user

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#825]
A few people are able to log in with other browsers just fine, but when they log in with Chrome they get the demo account. See https://github.com/lefnire/habitrpg/issues/818 for more details. 

What's happening technically is the user's `auth` property is skipped on login, and they're getting a demo account with an empty `auth = {}`. This is very strange behavior, and since Chrome is our most common browser statistically, I need to fix this ASAP

**Comment by lefnire** [comment]
For people experiencing this issue, can you try clearing your cache / cookies to see if it fixes it?

**Comment by stefanknapen** [comment]
Cleared everything from past week, didn't help.

**Comment by stefanknapen** [comment]
And it works indeed in Safari

**Comment by lefnire** [comment]
This seems to be happening to a lot of people. The only reason this could possibly be happening is a busted session, which would be held in cookies (you may have to clear "for all time" - or use a tool like Web developer toolbar to clear for the domain). If that's not fixing it, I dare say - I honestly don't know where to look :/

**Comment by lefnire** [comment]
woops

**Comment by kaedwards1447** [comment]
I use Chrome and am having this issue too. I tried clearing my cache and history and it did not fix the issue. =/

**Comment by PiNotEqual3** [comment]
Same here. If I switch from one PC to another I need to login again. Maybe it is a session problem?

**Comment by lefnire** [comment]
I'm finding most people who followed up via email - they say clearing cache & cookies "for all time" solved the issue.  Can y'all try that?

**Comment by kaedwards1447** [comment]
I tried that and it did not work for Chrome. It works fine on Firefox and I've been using that instead.

**Comment by lefnire** [comment]
Just to be sure, you definitely did delete cookies "for all time"? (or the
default selection) only reason I beat the horse is it would make sense if
it's a cookie issue, but I can't think of what could possibly be the issue
if not

**Comment by kaedwards1447** [comment]
I did. I tried re-deleting them a few times to be sure and no such luck. =( Sorry...

**Comment by PiNotEqual3** [comment]
Problem is solved for me. Thank you!

**Comment by Natanji** [comment]
Posting here because I (perhaps?) have the same probem, I opened Issue #865. I cannot login in _any_ browser, not Chrome nor Firefox, but I have a logged-in session on my laptop with Firefox that behaves in a weird was (see issue #865), which is hopefully reopened soon.
HabitRPG even tells me that the username is not registered, but I can login just fine on the community page/forums! So this must be some error in HabitRPG. Maybe the database got messed up a little? I know there was some news about database problems when I registered.

**Comment by lefnire** [comment]
The community site & main site logins are different. Community site is a
Drupal database, main site is a custom MongoDB database. Sucks, we're
working on that. With your logged in session ,can you give me your user id?
(user -> settings -> api)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
