### ISSUE TITLE
Unicode Character "Trigram for Heaven" (\u2630) does not display on the website

### ISSUE THREAD

**Issue by benwurth** [HabitRPG/habitica#8250]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 41b74b13-2c23-4241-bd33-ba74bb4c7bf0
  * Browser: Chrome 54
  * OS: Mac OSX Yosemite

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
The unicode character "Trigram for Heaven" (\u2630) does not display on the website on elements that are using the "Lato" font:
<img width="119" alt="screen shot 2016-12-02 at 6 29 33 pm" src="https://cloud.githubusercontent.com/assets/2358786/20856189/f632ed6c-b8bd-11e6-9a89-c4b210d2d437.png">
When I use the developer tools to style the element with Helvetica the buttons display as intended:
<img width="111" alt="screen shot 2016-12-02 at 6 29 52 pm" src="https://cloud.githubusercontent.com/assets/2358786/20856202/1959bfd2-b8be-11e6-9503-f8d25ea76c7c.png">

**Comment by lynxlynxlynx** [comment]
Works fine here (but not a mac). Lato is taken directly from google fonts. Are you forcing any user styles through the browser?

**Comment by NoxiousPluK** [comment]
Works fine here too on Chrome 54.0.2840.99 m (64-bit) but Windows 10.

When I check the developer tools, it reports Lato aswell.

Can you try setting it (using developer tools) to !important to test?

Based on http://www.wastedpotential.com/solved-google-web-fonts-not-displaying-on-some-macs/ (old but possible still an issue).

**Comment by benwurth** [comment]
I figured out what the issue was. I had the TypeKit version of Lato installed locally on my machine which (apparently) does not support certain Unicode characters. The Google Font style sheet always pulls the local version of fonts before their CDN fonts and so it was using my local Lato.

As this is a Google Font problem, I'm not sure how you can fix it on your end. I'm going to go ahead and close this issue.

**Comment by NoxiousPluK** [comment]
Then adding !important might work for a force-pull? It seems to work for some people :)

**Comment by benwurth** [comment]
I did try adding !important but it did not work for me. Uninstalling my local font did, though.

**Comment by Alys** [comment]
We're part way through a project to make some improvements to the website so it's likely that this problem won't be around for long.
