### ISSUE TITLE
moderator Hall bug: adjusting a previously-blocked user causes them to rest in the inn

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8254]
When a moderator uses Social > Hall, they have extra features there for modifying user accounts (e.g., to give pets or gems). When they use those features to make any change to a user's account, if the user has ever been blocked in the past, the change that the moderator makes causes the user to be resting in the inn (not blocked, just resting).

This is because of this code: https://github.com/HabitRPG/habitica/blob/9aa4b8aa64ccdfa3af4a6832cc3dded4b102b73e/website/server/controllers/api-v3/hall.js#L180-L183

The code should be checking if auth.blocked is true, not if it's a boolean (which can also mean false).

The test should be changed too: https://github.com/HabitRPG/habitica/blob/9aa4b8aa64ccdfa3af4a6832cc3dded4b102b73e/test/api/v3/integration/hall/PUT-hall_heores_heroId.test.js#L43
It shouldn't be checking blocking + sleep at the same time as the other changes.

I suggest that the tests should be:
+ Block a user > They become blocked and asleep.
+ Unblock a user > The stop being blocked. They remain asleep.
+ Change contributor level, balance, ads > Those items change. The user is not blocked. The user is not asleep.

_(FYI for anyone curious: The "ads" code and associated user data are left over from a time when we had small ads on the site pointing to things like books about productivity. There are no plans to reintroduce ads.)_

**Comment by crookedneighbor** [comment]
:+1:

**Comment by mdakan** [comment]
I'm interested in fixing this.

**Comment by Alys** [comment]
@mylesdakan Thank you!

**Comment by mdakan** [comment]
@Alys For your third bullet point, is it possible the user would already be asleep? Would that cause a problem for this test?

**Comment by Alys** [comment]
Ah, good question. In the tests you can control the user's state so you could make sure they were/weren't asleep first, as appropriate, then run the code to simulate the actions being tested.
