### ISSUE TITLE
Blank messages can be posted to chat

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#8255]
### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

I posted this to the Report a Bug guild:

> "The Android app allows blank messages to be posted to chat (well, it posts a blank message if you post a space). Should that be reported via the app? (The website doesn't allow a message with only a space in it to post to a chat... though it does allow a message with nothing but `&nbsp;`.)"

I tested it out after seeing a blank message in the Tavern this morning; the app won't post a message if you leave the field blank but will post a blank message if it includes a space character. This doesn't happen on the website (except in the case I mentioned above with `&nbsp;`). I don't know if it also happens on the iOS app.

@Alys replied to me with this:

> "@citrusella, the serving wench : It's probably best that we prevent blank messages being posted in the API, then they're fixed for all interfaces, including third-party tools, so that means we'd make an issue on the normal GitHub repo instead of reporting in the app. Would you like to copy your message and this reply to GitHub? If not, I'll do it later."

**Comment by Hus274** [comment]
I can take a look into making this change.
