### ISSUE TITLE
Daylies one day behind? (GMT + 0)

### ISSUE THREAD

**Issue by themenniss** [HabitRPG/habitica#826]
I've been making use of the repeat function for my daylies but it appears to be one day behind. It's currently 0740 GMT on Tuesday and, whilst they've updated (didn't loose any hit points w00t), they are consistently showing the daylies for the day before (Monday). It has been doing the same thing all weekend. I don't know how long this as been the case.

Cheers.

**Comment by joe-jordan** [comment]
Also seeing this in GMT+1 (British Summer Time). Sunday worked for me, but ran again on Monday, and today (Tuesday) is Monday's dailys.

**Comment by rm909** [comment]
Should be the same issue as #822 ?

**Comment by joe-jordan** [comment]
not sure - OP at #822 claims dailys were _not reset_, mine here were reset and I had to enter Sunday's twice (I think - sometimes habit doesn't finish AJAX-syncing my checks before I close the tab, so it may have been one very long day.)

**Comment by wizonesolutions** [comment]
Let's keep the older issue open.
