### ISSUE TITLE
sprites in Cornucopia Mystery Item Set are misaligned

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8274]
The sprites for the Cornucopia mystery items are misaligned (head_mystery_201611 and weapon_mystery_201611).

When used in Habitica, they look like this:
![bad](http://i.imgur.com/PAAQTYJ.png)

But they should look like this:
![good](http://vignette2.wikia.nocookie.net/habitrpg/images/9/91/Promo_mystery_201611.png/revision/latest?cb=20161123070157)

I.e., In Habitica, the hat is too far to the left and the weapon covers up too much of the avatar's face.

**Comment by padm0** [comment]
Hello! I'd like work on this!

**Comment by TheHollidayInn** [comment]
@padm0 Go for it!

**Comment by padm0** [comment]
<img width="212" alt="after" src="https://cloud.githubusercontent.com/assets/24511511/21083787/f50790c8-bfac-11e6-95e4-3430829e409e.png">
<img width="168" alt="before" src="https://cloud.githubusercontent.com/assets/24511511/21083788/f508491e-bfac-11e6-85cb-4cd5da3c5051.png">

**Comment by padm0** [comment]
Before:
