### ISSUE TITLE
On iPad, a single press of backspace in any chat/pm window results in slowly deleting entire post

### ISSUE THREAD

**Issue by foxnsocks** [HabitRPG/habitica#8275]
New this week, at least to me. I did just update to ios 10.1.1, but I also usually compose in notepad and paste into chat because of fatal lag so I may not have noticed. This is on safari on iPad - I use the phone app (android) but web on desktop and toy devices.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
The website isn't currently supported on mobile devices. If this same problem happens in future it will be from a different cause so I'm closing this. We can open a new one if needed. 

Thanks @MathWhiz for finding all these. :)
