### ISSUE TITLE
pixels missing in broad Bloodred Robes (armor_special_fallRogue)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8289]
There are pixels missing in broad Bloodred Robes (armor_special_fallRogue).
As reported by JuniperGrove in the Report a Bug guild:

"while the "slim body" version of the vampire hunter rogue outfit is fine... the "broad" version does this thing where it shows a shirt pixel. Honestly I just pretended it was earrings, and its possible no one noticed because I'm betting the hood covers it, but I just thought ya'll should know."

![image](https://68.media.tumblr.com/14502cfc2782d1f2b28e000b3f47e421/tumblr_oi3ofhGoOd1rumsgeo1_1280.png)

**Comment by padm0** [comment]
I'd like to work on this!

**Comment by TheHollidayInn** [comment]
Go for it!
