### ISSUE TITLE
Data Display

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#83]
_wc8: Vote [Enhanced Graphs](https://trello.com/c/wYKm5cS5)_
Maybe add different ways to view the data besides just a line graph? Plus I honestly think it may deserve a separate page unto itself. Something like this http://d3js.org/ ?

**Comment by lefnire** [comment]
will add d3 later

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.
