### ISSUE TITLE
Allow API clients that don't support compression

### ISSUE THREAD

**Issue by arscan** [HabitRPG/habitica#830]
The API requires that the http client supports compression -- if the client doesn't pass an Accept-Encoding header with an appropriate value the request is denied with a nonspecific error (404).

While I appreciate the fact that its preferable to compress all responses, I don't think that it is worth the trouble to deny clients that don't say they support compression.  For those that haven't ever dealt with an API w/this restriction (I personally haven't), its very frustrating when first getting started.  You have to explicitly pass a flag in curl to make it work, and you can't use the popular Request library in node (without adding the header manually and piping results to a gzip library).

At the moment, I'm trying to get the API to work with Hubble -- see https://github.com/jaymedavis/hubble/pull/18#issuecomment-16483334

I can "fix" their application, but I have a feeling this will come up over and over.

I'd propose a PR on this, but I don't want to mess with the routing because this may affect the web app (and not just the api)... and I just don't have enough experience with express.

Thoughts?  If this is convention today (and I just haven't ran into it anywhere), then please point out examples.  

Thanks!

**Comment by switz** [comment]
I'll implement this tomorrow. I guess we should just check the header:

It's as simple as changing some express middleware

``` coffeescript
(req, res, next) ->
  # check compress header or parameter
  if req.headers['dont_compress']
    next()
  else
    express.compress()(req,res,next)
```

**Comment by arscan** [comment]
Thanks for looking into this. I'm confused because express.compress() should only compress if the client sent the accept-encoding header, and just pass through the response otherwise. I suspect it has something to do with another handler messing things up.

**Comment by arscan** [comment]
Unfortunately this a known issue in the gzippo static file compression module: https://github.com/tomgco/gzippo/issues/47

And more unfortunately, it looks like the maintainer of that module is somewhat MIA.

Removing that middleware fixes this issue. Is there a reason why this is being used over the built-in compress that comes with express/connect?

**Comment by switz** [comment]
Yeah, we should switch off of gzippo. It was the best, but it's not maintained anymore.

**Comment by lefnire** [comment]
Any forseeable Derby issues here?

**Comment by arscan** [comment]
Awesome.  Is there anything you'd like me to test?

**Comment by switz** [comment]
Nope, it's totally separate from Derby and runs directly through express middleware.

**Comment by arscan** [comment]
This was actually brought up in a thread that both of you were involved in.  The guy said reverting to 0.1.7 worked for him, but that broke for me (and it broke for someone else too). 

https://github.com/codeparty/derby/issues/171#issuecomment-12635700

**Comment by arscan** [comment]
Sooo, its now magically working on a fresh copy of the develop branch that I cloned locally (`curl localhost:3000/api/v1/status` no longer throws a 404).  I can't get it to replicate the error.  I'm guessing one of the modules updated behind the scenes that fixed the error, but I'm not seeing anything obvious.  Either that or I'm crazy and did something on my local machine without realizing it.

Its still not working on the live or beta site for me though.

**Comment by switz** [comment]
Yeah, this is also working for me locally, but failing on the server. I'll keep looking into it.

**Comment by switz** [comment]
The previous PR did not fix it. But I was able to reproduce the issue locally. I'll keep you updated.

**Comment by switz** [comment]
@lefnire So here's what I've found. gzippo is most definitely currently causing this issue for some reason, even though it shouldn't be. My suggestion is to move all static file hosting and gzipping to nginx. It will be more efficient and less load on the node process anyway. We shouldn't even have that line in there if nginx is already handling all of our static files.

**Comment by arscan** [comment]
That sounds like an ok path from my perspective. We just need to make sure that the server works w/out nginx in front of it "out of the box" for those running locally (all the paths are set up, etc).  Not having compression is fine though... if people are running local instances with any real load then they can handle that themselves.

**Comment by switz** [comment]
Yeah, we'll be sure to do that. It's as simple as sticking it in an

``` coffee
app.configure 'development', ->
  # do stuff

```

block

**Comment by lefnire** [comment]
I'm down if it fixes the problem. IIRC (not in front of a computer) our
only static route currently in use is static/front, the others can be
deleted. Gotta double check though. But as per rob, there a way to handle
this for local clones without nginx?
