### ISSUE TITLE
Scrolling while a modal opens displaces the modal

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8301]
* Browser: Safari

### Description
If you happen to be scrolling when a modal opens, it scrolls halfway off of your screen and gets stuck. Furthermore, all the button links align with their original positions, not their displaced images, so you have to hunt around the screen to find them. 

Example:

![screen shot 2016-12-21 at 12 48 56 pm](https://cloud.githubusercontent.com/assets/3494081/21405946/d684b7ba-c77d-11e6-97ac-bb583b6ec3b8.png)

**Comment by TheHollidayInn** [comment]
I believe this is fixed in the new site or is not applicable anymore.

**Comment by lemoness** [comment]
I haven't noticed it recently, so I'm closing this for now!
