### ISSUE TITLE
Party page does not update after accepting an invitation to a new party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8303]
From Andrea the Goblin Cleaver (35dd6e3e-f660-4d74-b254-d541e33a70c4) in the Report a Bug guild:

"not sure if its a bug or my browser, but here is what happened: I was in a party, I was invited to another. I accepted the invitation. It still showed me as being a member of my old party, I clicked leave party, that worked but now I have no party and no invitation."

My response (which is a bit of an assumption but I think it likely):

"What I think would have happened is that you were removed from your original party and your acceptance of the invitation was recorded, putting you into the new party, but the website didn't update correctly and made it look as if you were still in your old party. When you clicked leave party, it caused you to leave the new party."

I haven't had time to try to duplicate this so I'm not sure if this is exactly what happens or if it happens every time. However it's disruptive enough to be worth investigating, and to fix if we can even if it doesn't happen every time.

**Comment by khipkin** [comment]
This sounds like a side effect of the party not being kept up to date. Do party leave API requests not include a party id? That would be useful for validation that weird things like this can't happen.

**Comment by JoshSears** [comment]
Is this issue still in need of investigation?  I just started, and was looking for entry level coding issues, however I found this.  I don't mind looking at it, trying to reproduce it, but I don't necessarily want to ask for it to be assigned.

**Comment by TheHollidayInn** [comment]
Feel free to look into it if you would like. There is a broadcast event in the group service that would help solve this. Although, we are redoing the front end and this will be fix during that process.

**Comment by JoshSears** [comment]
Ok, I will get started on testing at least...  See if I can reliably reproduce the issue.  I will post tests/results on here when I have something.

**Comment by JoshSears** [comment]
Conducted some tests for trying to receive/accept an invite while still in another group.  10 tests, no positive results.  Can attach tests if need be.

Tomorrow, I will look into the group service.  However, I was unable to replicate getting an invitation to a user that was in a party already.  Unless Andrea meant in "I was in a party, I was invited to another" that she had quit the orig party first, then got the invitation.  From Alys' response, I had something similar occur with the first test (not reflecting correct party count or other members).  Will work further on it tomorrow.

Edit: Removed test details to shorten post.

**Comment by JoshSears** [comment]
@TheHollidayInn : Could you elaborate more on the broadcast event you mentioned (how it could solve)? 

 I used the Google console find the file you referred to, and opened the code to look through it.  Tried to reproduce the error by bouncing a user back and forth between parties.  Never got an attempt where the old party still populated the screen.  Also tried to click accept and leave before the page refreshed (also tried leave and accept).  Was unable to replicate the problem.

Maybe this prob is larger than I am able to bite off as a rookie blacksmith, but I am in it to win it!

**Comment by TheHollidayInn** [comment]
So, when you accept a new party request, everything is updated? I have reproduced this bug in a while.

Basically, you will have to use Angular's `$rootscope.$broadcast` to request a sync https://github.com/HabitRPG/habitica/blob/develop/website/client-old/js/services/groupServices.js#L131. You can also update the party via the Promise return from getting a party in the PartyCtrl: https://github.com/HabitRPG/habitica/blob/develop/website/client-old/js/services/groupServices.js#L143.

I could definitely go into more detail and explain if you are unfamiliar with the concept/our odd cache hack doesn't make sense. But, this problem will not be in the redesign that is coming soon. So I highly recommend not putting more than an hour or two into this. Most of the issue is our old Angular 1.2 way of syncing data mixed with some cache hacks.

**Comment by JoshSears** [comment]
Everytime I have accepted a new party request, the whole page gets updated - Habitica Tip screen, then "building your party", then the screen appears updated - after hitting the accept button - both when the party screen only has the invitation message, or if the invitation message is just above the rest of the party page.

**Comment by Alys** [comment]
It sounds like this bug is so intermittent that it's very hard to reproduce and not common enough to affect many people. I think it's best if we let this be fixed by the website redesign project. @Dagrik Thank you for your investigation into it! I'm sorry it turned out to not be reproducable!

**Comment by librarianmage** [comment]
Is this still an issue, with the redesign?

**Comment by lemoness** [comment]
I haven't seen reports, but if we need to we can always reopen this or make a new ticket!
