### ISSUE TITLE
Open new tasks in edit mode doesn't work with new task editing modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8304]
_edit by Alys 2017-01-21:_

The fix needed for this is that when the "Add Multiple" option is being used, the user's preference option for "Open new tasks in edit mode" should be ignored.

----

From Rachel Ann (7b9c41d3-6d21-4168-9dfd-e0c2489df8ff) in the Report a Bug guild (confirmed by me):

"**The new edit modal doesn't seem to work with the setting "Open new tasks in edit mode". It has no checkbox, just the move-to-top, cancel, save, and delete buttons. I have to save it or cancel and then click edit. So I've turned that setting off for now, and it works fine, but it's an extra step I didn't use to have to do. (Also for consideration: if that gets fixed, how will it work with the "Add multiple" option?)**"

Here's a screenshot showing at the bottom, one task created by itself, and then three tasks created together - this is how they appear as soon as they are created:

![image](https://cloud.githubusercontent.com/assets/1495809/21413719/1c44f6c6-c845-11e6-8340-f3c4bc90cb8a.png)

Rachel Ann's question about the "Add multiple" option is a good one. I guess we should fix this for the case where you're creating one task at a time (i.e., as soon as the task is created, the edit modal opens). For the case where you're creating multiple tasks, the "Open new tasks in edit mode" setting should probably be ignored (i.e., the tasks are created with no attempt to open any of them in edit mode). Other suggestions welcome but I think this would be least confusing.

## What to do if this happens to you:

There is no need to comment here nor report it in the Report a Bug guild because we know this affects everyone. We recommend turning off the "Open new tasks in edit mode" setting from [Settings > Site](https://habitica.com/#/options/settings/settings) until this is fixed.

**Comment by citrusella** [comment]
This is still happening for remaining tasks in bulk adding.

entreprayneur (a0ed8f8a-7748-4e6b-92c3-9ad79c094762) said in the Report a Bug guild 2016/12/30 at 12:37:53 EST (GMT -5):

> Hello. I am experiencing a constant bug. When adding multiple tasks on web, they submit but only one task editor pop-up appears for the first task in series. Then, once saved, the remaining tasks i had added in the series are all toggled for edit (show check and X mark) and do not show any pop-up editor. I've recreated this issue on my account several times. Help?

**Comment by Alys** [comment]
I've added this to the top post to make it easier for potential coders to see what needs to be done:

The fix needed for this is that when the "Add Multiple" option is being used, the user's preference option for "Open new tasks in edit mode" should be ignored.


Although opposing opinions are welcome. :) Other admins can change my edit if they wish.

**Comment by SabreCat** [comment]
Client/UI issue. Placing on hold for the frontend redesign.

**Comment by librarianmage** [comment]
I don't see an option for this anymore on the Settings page. Is this still desired?

**Comment by citrusella** [comment]
I see no reason they'd theoretically want to remove the option on purpose unless it just wasn't feasible with the new site.

But then I'm not them. (And also biased because I like/used the option.)

**Comment by SabreCat** [comment]
I think now that we have the quick-add fields at the top of the task columns again, this could be re-implemented. (Before the quick-adds were restored, you always got the edit popup when adding tasks anyway.)

**Comment by lemoness** [comment]
So actually, we don't need a setting for this. Quick-add doesn't work this way, but adding a new task with advanced mode by clicking the green (+) always opens the task in edit mode. So the feature is already accessible for any task type from the task page, and you can choose if you want to open in edit mode or not on a task-by-task basis without changing your settings.

**Comment by citrusella** [comment]
...I didn't realize those even functioned differently! :worried: I even went so far as to hide the green plus in one of the styles I'm working on because I figured the features were the same regarding opening an edit window! \*goes to consider the merits of un-hiding that*
