### ISSUE TITLE
Task left in odd setting when cancelling editing with ESC / Escape Key

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8308]
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 42.0.2393.85
Windows 10 32-bit

## Description

+ Edit Task.
+ Press ESC key to cancel Task.
+ Task is left in "old edit mode"((as per image below) where you need to press save (tick) for it to return to checkbox like other tasks.

![taskleftineditmode](https://cloud.githubusercontent.com/assets/14116069/21419851/4ecb391e-c87e-11e6-93db-8f7c813169cc.png)

**Comment by Alys** [comment]
The first half of this comment: https://github.com/HabitRPG/habitica/issues/8321#issuecomment-269494056 might be relevant to this issue (calling the cancelTaskEdit function).

**Comment by TheHollidayInn** [comment]
Yea, I believe adding this will solve both issues: http://stackoverflow.com/questions/8363802/bind-a-function-to-twitter-bootstrap-modal-close

The angular way though.

**Comment by declanramsay** [comment]
I'd like to fix this (and the sister issue #8321)

**Comment by Alys** [comment]
@thelucideffect Thanks very much! Can you please comment briefly on the other issue to say that you're working on it so that no one else claims it?
