### ISSUE TITLE
Completion of Dailies, Todo's, and Habits no longer gives gold or XP. 

### ISSUE THREAD

**Issue by Aericson1** [HabitRPG/habitica#831]
Yesterday I was running dangerously- only 15 HP left and four red tasks threatening to do me in. I completed all four red tasks before the night was over, and as I went to bed my list of Todo's and Dailies looked nice and peaceful. 

I tried logging into my account in the morning- error. No big deal. 

I tried logging onto my account in the afternoon, and I was dead. Behind the message I could see that the four red tasks were back, as if I had never clicked them off. 

Not a huge deal, I can just restore my account. 
I went to restore, and restored the approximate HP, equiptment, level, gold, and XP that I could recall. I was back, everything seemed saved.

But now when I complete tasks I get no XP or Gold for completing them. My habits are the same, except I do still lose HP if I complete a negative habit.

Any ideas? I have tried running HabitRPG in an incognito window, logging in an out etc, still no luck getting tasks to generate gold and XP.

**Comment by lefnire** [comment]
marking as crit, will look into when I can

**Comment by Aericson1** [comment]
I appreciate it, 
Thanks!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
