### ISSUE TITLE
group plans Habits and Rewards cannot be edited in Group Tasks List screen ("Save and Close" not functional)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8311]
When I create a Habit or a Reward in a Group Plan that I'm a leader of, I cannot edit it because the "Save and Close" button is not functional. I can make changes to the task's attributes but clicking the save button has no effect (the edit modal remains open and if I cancel it with the cancel button or by hitting ESC, the changes are not saved). This also applies to Habits and Rewards that were created several days ago.

Dailies and To-Dos don't have this bug.

This is a new bug; it wasn't happening during the testing period before Group Plans were released.

This was first reported by MuMind (81385353-52cd-4f46-b424-007c49a00950) in the Report a Bug guild:

"Can't remove negative button from Group Plan habit. On web the Save & Close button doesn't save or close. On Android it just doesn't actually remove the negative button."

**Comment by Alys** [comment]
This was first reported by MuMind (81385353-52cd-4f46-b424-007c49a00950) in the Report a Bug guild:

"Can't remove negative button from Group Plan habit. On web the Save & Close button doesn't save or close. On Android it just doesn't actually remove the negative button."

**Comment by Alys** [comment]
The same applies to Rewards. I'm updating the title and top post to reflect that.

To-Dos and Dailies don't have this bug.

**Comment by dbarnett** [comment]
Is the issue on Android also tracked (or related to the checklist issue)?

**Comment by Alys** [comment]
@dbarnett On the Android app, there's no way yet to manage group plans so this issue wasn't relevant to it. I'm guessing that "On Android it just doesn't actually remove the negative button" refers to an attempt to edit the task in the player's own task list. Regardless, I don't think any further fixes are needed for this issue.

**Comment by dbarnett** [comment]
Right, I had claimed the task and attempted to edit it from there. You're saying editing group tasks there is a separate feature request? There wasn't any related error message or anything, just looked like it saved when I clicked "Save & Close" and had no effect.

**Comment by Alys** [comment]
Only the group leader can edit certain aspects of group plan tasks, such as  the +- buttons. The leader needs to do that in the Group Tasks List tab in the guild or party's page.

**Comment by dbarnett** [comment]
K, so I guess the app UI needs to reflect that better.

Unfortunate, though. For all the expense of group plans, there are still a lot of limitations in practice.

**Comment by Alys** [comment]
@dbarnett The group plans are designed to allow the group leader to have strict control over the tasks. It's a deliberate feature, not a limitation, that you can't edit the copies of the tasks in your own task lists.
