### ISSUE TITLE
Party Up and Party On achievements are missing text

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8312]
_From thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a) in the Report a Bug guild:_

I was just looking at my achievements list and I noticed that the hovertext for the "Party Up" and "Party On" achievements seems to be missing. Hovering over the icons just says "Party Up/partyUpText not found" and "Party On/partyOnText not found" (where the slash in those quotes is meant to represent a linebreak). I have received the Party Up achievement, but not the Party On achievement, so the problem seems to be independent of awarded/not awarded status.

_From Cequinne (a9b44f7f-08b3-4ecb-97c2-d2855eed4e20):_

Hovering over the "Party Up" and "Party On" achievement badges shows "String 'partyUpText' not found" or "String 'partyOnText' not found" respectively in the description.

**Comment by khipkin** [comment]
The string names got reverted in [this commit](https://github.com/HabitRPG/habitica/commit/ea24eeb0199a687115da0224b64b62c57629aea2#diff-040152bf2f4ce00a01ce5aa334f0851f).

**Comment by TheHollidayInn** [comment]
Eh, sorry. This was definitely my fault. Thanks for fixing it.
