### ISSUE TITLE
Background of task editing modal is white if you double-click the task

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8315]
**UPDATE**: The issue occurs when you double-click the task to edit it instead of clicking the pencil icon, regardless of browser/platform.

---

In the Report a Bug guild, derpderp (a7d65869-2f12-433a-a111-b4811ab89555) has told us that when editing a task, the background is always white and there is no highlighting to indicate which buttons have been selected (e.g., for due days, difficulty, etc) - see screenshot below. No browser extensions were installed.

This seems to be a problem with Edge, Internet Explorer, and Safari. derpderp writes "the white background persists for me across different browsers (edge, internet explorer) and 3 different computers (all running windows). I asked a friend to check their Habitica, and they reported the same thing: white background with no highlights of days or difficulty. They are on the latest Mac OS on Safari."

I can't replicate this on Chrome or Firefox on Linux.

It's possible that the method of applying the background colour and button highlights isn't supported by all browsers.

![white](https://s30.postimg.org/8vgl8dpkx/snip_20161223002119.png)

## What to do if this happens to you

We know this happens equally to everyone, so you do not need to comment here or report it elsewhere. 

You can avoid this problem by clicking on the pencil icon when you want to edit a task, instead of double-clicking on the task.

**Comment by blatherwock** [comment]
I'm running Chrome Version 55.0.2883.95 (64-bit) on Mac OS X El Capitan (10.11.6). If I click the edit icon I get the correct yellow background and button highlights, but if I double click on the task to open the popup I get the white background and no button highlights.
<img width="600" alt="screen shot 2016-12-27 at 16 48 53" src="https://cloud.githubusercontent.com/assets/1683023/21509194/bc6ec542-cc54-11e6-90bf-1a428f40804c.png">

Looks like the div directly inside 'modal-content' in the working case has the following classnames: "modal-content task-modal todo uncompleted difficulty-easy color-neutral" while in the non-working case has "modal-content task-modal "

**Comment by SabreCat** [comment]
Good elaboration, @blatherwock! I will update the issue title, which will help people recognize the workaround of clicking the pencil icon.

**Comment by beejunk** [comment]
I can confirm the white background appears on Firefox 50 (Ubuntu Linux) when using the double-click method described by @blatherwock.

**Comment by FedyuninV** [comment]
Chrome 55.0.2883.87 on Windows 10 (x64) - white background on double click. Does anyone got correct color by double click?

**Comment by TheHollidayInn** [comment]
Double click is currently not passing the taskStatus: https://github.com/HabitRPG/habitica/blob/2da0a1e88c115300dd70bd73e1f489b53348b6cc/website/client-old/js/controllers/tasksCtrl.js#L72 . That is causing this issue:

Here is the function for reference: https://github.com/HabitRPG/habitica/blob/2da0a1e88c115300dd70bd73e1f489b53348b6cc/website/client-old/js/controllers/tasksCtrl.js#L59

**Comment by beejunk** [comment]
I will work on this issue, if nobody else is currently working on it.

**Comment by SabreCat** [comment]
Sounds good @beejunk!
