### ISSUE TITLE
add "Save & Close" and "Cancel" buttons to the top of the task edit screen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8316]
As described in https://github.com/HabitRPG/habitica/issues/8307, now that task editing is done in a modal, reaching the "Save & Close" and "Cancel" buttons requires scrolling to the bottom, which is especially inconvenient on small screens or when the tags and advanced options are expanded.

We should add "Save & Close" and "Cancel" buttons at the top of the modal (as well as having them at the bottom).

My personal suggestion is to add the two buttons in a horizontal row at the top right of the modal, however other suggestions are welcome.

I believe this is definitely worth doing now for usability, but we're currently rewriting the website's front end to make many significant improvements, so it's not worth putting too much time into making the buttons look perfect. I think a quick fix now for usability would be fine.

**Comment by maximumtiu** [comment]
Hi, I'd like to take a crack at this one!

**Comment by Alys** [comment]
@megantiu Thank you!
