### ISSUE TITLE
Can't Remove Ended Challenge Tasks on Firefox or Chrome

### ISSUE THREAD

**Issue by janetmango** [HabitRPG/habitica#8317]
UUID:  d075dca7-01ed-4666-ae2d-22feef18c7bc
Browsers:  Firefox and Chrome
OS: Windows 10

Since the new edit task console, I can't remove broken challenge tasks.  I click the broken challenge link and the task goes blank (picture attached).  When I click Save or Cancel it returns to normal.

When I click the edit task button, the edit task console opens. But if I click Remove task button, nothing happens. (picture attached).
![habitica edit task console](https://cloud.githubusercontent.com/assets/9999741/21498912/101c0e94-cbff-11e6-9b41-3ad195c8db30.png)
![habitica broken challenge link](https://cloud.githubusercontent.com/assets/9999741/21498913/101da6dc-cbff-11e6-9c99-30a4a7d04e11.png)

**Comment by Alys** [comment]
That's a known problem and we have a fix for it already, which will be deployed in a day or two.
