### ISSUE TITLE
Health replenishes on accidental level up

### ISSUE THREAD

**Issue by justindoran** [HabitRPG/habitica#832]
When I was on the edge of leveling (but with only 10hp left) I accidentally clicked a daily task, which leveled me up. When I clicked it again, my XP went down to -10 but my health replenished itself. I'm guessing the "undo" feature--which I didn't use--might not have created this problem, but unclicking the daily task does. My expectation was that I would lose the XP, level down, and lose the health. But I just lost the XP.

**Comment by wizonesolutions** [comment]
I'd say that's probably what undo is for. You can use the "Restore"
function for now in situations like that if you remember about what your
stats were.

**Comment by lefnire** [comment]
i'll fix later :)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
