### ISSUE TITLE
Users checked off tasks during christmas but they were not recorded 

### ISSUE THREAD

**Issue by joshuabowers2** [HabitRPG/habitica#8320]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: b907f1dc-34da-4670-a313-0ff2979bda40
 c8267fab-c248-43ec-bc5f-953a071f4788
  * Browser: 
  * OS: 

### Description
Two users in my party completed all of their dailies on christmas day, however when they looged in the next day to check damage, none was dealt to the boss and instead they both received full damage against their characters. This caused one of them to die, and lose their helmet, and it increased the regen meter on the boss. Their user IDS are b907f1dc-34da-4670-a313-0ff2979bda40 c8267fab-c248-43ec-bc5f-953a071f4788

I'm guessing it is because they used the app and not the site? Myself and another party member had no problems that day.

Party Name: Clan Bowers

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
@joshuabowers2 I've seen that you've reported this in the Report a Bug guild, so we'll handle it there. Reporting tasks in two places can lead to double handling, which can cause problems. The Report a Bug guild is the best place to report any bug. We'll always let you know if it needs to be copied elsewhere.
