### ISSUE TITLE
Can't dismiss task edit modal by clicking outside of it

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8321]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Many modals can be canceled by clicking in the grayed-out space behind them to return to the original screen. This is not the case for the new task editing modal, forcing the user to hunt for the small "Cancel" button ~at the bottom, which is likely scrolled out of sight to begin with~. Enabling a quick bailout via a click in the outer unused area would be great for usability.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None

**Comment by Alys** [comment]
Clicking outside the modal should have exactly the same effect as clicking the cancel button - i.e., it's important that the edit mode is completely cancelled, rather than leaving the task in the task list  in a semi-editing state (as described in https://github.com/HabitRPG/habitica/issues/8308).

**Comment by TheHollidayInn** [comment]
To add to @Alys 's comment. This function needs to be called when outside the modal is clicked: https://github.com/HabitRPG/habitica/blob/develop/website/client-old/js/services/taskServices.js#L277 .

To allow for clicking outside to cancel, just remove the backdrop property here: https://github.com/HabitRPG/habitica/blob/develop/website/client-old/js/services/taskServices.js#L274 . Then, added a listener to call the function above.

**Comment by declanramsay** [comment]
Working on this and its sister issue #8308
