### ISSUE TITLE
Challenge owners cannot delete challenge tasks

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8322]
### General Info
* bc10ec41-4213-4482-bbb8-558e3c3ea8d5
* Opera 42.0.2393.85
* Windows 10 32-bit

### Description

You can't delete tasks in a challenge once they are already added. (The trash can no longer exists either in view or edit mode). Because of this, if you accidental put extra tasks in, you need to re-enter the challenge from scratch.

**Comment by Alys** [comment]
I'm pretty sure this is a new bug. It probably appeared in the past couple of days, otherwise we'd have heard about it before now.

Anyone got any ideas about the cause from any recent code changes?

**Comment by TheHollidayInn** [comment]
I'll fix this.
