### ISSUE TITLE
"undefined" notification when marking tasks complete and possibly from other actions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8324]
As reported by Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) in the Report a Bug guild:

"While checking my due dailies, at the one before last, got 'undefined' among the floating notifications. Thought I'd snap a picture just in case. [below]
(I'm not sure all the notifications are from one task, I ticked off several in succession.)"

I've seen this myself occasionally but never got around to reporting it or to working out what caused it.

![image](http://savepic.net/8733713.png)

**Comment by TheHollidayInn** [comment]
I believe this an issue with our http interceptors and notification parsers for Angular.

**Comment by Alys** [comment]
In that case, we should probably leave it to be fixed by the site redesign. I think it's worth leaving open though so we don't get duplicate reports. Opposing opinions welcome though. :)

**Comment by khipkin** [comment]
@TheHollidayInn Why do you think that is the cause?

**Comment by TheHollidayInn** [comment]
@khipkin Basically, we have notifications that display damage returned in a notifications array on the api response object. On Angular, we have interceptors and a notification ctrl that reads these notifications. There is something off on the timing.

**Comment by Alys** [comment]
Another report from Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) is below. This time it seems to be not from marking a task completed, although perhaps it was just slow to display from an earlier task completion - I wouldn't normally expect that delay though.

"I've got another "undefined". Was participating in the gem lottery, and noticed the broken challenge icon today, clicked it, read about the winner, chose to delete the tasks (it only had this habit with no + or -). And that floated up: http://savepic.net/8796192.png
Not that it does any harm, but maybe this will help catch other undefined's."

![](http://savepic.net/8796192.png)

It's probably still worth waiting for the website improvement project to fix this.

**Comment by librarianmage** [comment]
I haven't seen these in awhile; are they still a thing?

**Comment by Alys** [comment]
Closing. We can reopen if this still happens.
