### ISSUE TITLE
After registering via facebook I can only login via facebook and I basically don't have a password

### ISSUE THREAD

**Issue by Neputin** [HabitRPG/habitica#833]
After registering via facebook I can only login via facebook and I basically don't have a password. There should be a feature that would allow me to change my password.

**Comment by lefnire** [comment]
Facebook login doesn't tie passwords to accounts (like, in principle).  We
have "combining accounts" in the queue if you want both facebook & normal
login combined https://github.com/lefnire/derby-auth/issues/16, but it's a
semi low-prio at this point

**Comment by paglias** [comment]
I left another ticket about this opened
