### ISSUE TITLE
when no audio theme is chosen, do not try to find mp3 files (Server logs errors for failure to find /assets/audio/off/*.mp3)

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8333]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Server logs show a number of 404 errors similar to the following:

>2016-12-29T18:11:05.580Z - warn: NotFound: Not found.
>    at NotFoundMiddleware (/var/app/current/website/transpiled-babel/middlewares/notFound.js:6:8)
>    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
>    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:312:13)
>    at /var/app/current/node_modules/express/lib/router/index.js:280:7
>    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:330:12)
>    at next (/var/app/current/node_modules/express/lib/router/index.js:271:10)
>    at SendStream.error (/var/app/current/node_modules/serve-static/index.js:121:7)
>    at emitOne (events.js:96:13)
>    at SendStream.emit (events.js:188:7)
>    at SendStream.error (/var/app/current/node_modules/send/index.js:275:17)
>    at SendStream.onStatError (/var/app/current/node_modules/send/index.js:392:12)
>    at onstat (/var/app/current/node_modules/send/index.js:674:26)
>    at FSReqWrap.oncomplete (fs.js:123:15) method=GET, originalUrl=/assets/audio/off/Plus_Habit.mp3, host=habitica.com, x-real-ip=172.31.11.125, x-forwarded-for=91.125.93.250, 45.79.106.117, 172.31.11.125, accept-encoding=gzip, user-agent=okhttp/3.4.1, x-habitica-lb=Yes, x-forwarded-port=443, x-forwarded-proto=https, , httpCode=404, isHandledError=true

Note the URL of /assets/audio/off/Plus_Habit.mp3. If audio is `off`, we shouldn't be sending requests for an mp3 file at all.

**Comment by ramblinjan** [comment]
Is there a specific set of repro steps for this? If I run client locally via Mac OSX setups it doesn't result in any 404s with audio off.

**Comment by toddmedema** [comment]
Unable to repro on my computer on Habitica.com (Chrome 55.0.2883.95 on OS X)

**Comment by Alys** [comment]
This bug is still happening on the production server. Here's a recent log file record:

172.31.57.74 - - [26/Jan/2017:02:58:46 +0000] "GET /assets/audio/off/Daily.mp3 HTTP/1.1" 404 82 "-" "okhttp/3.4.1" "60.123.123.123"

I cannot get the 404 error to show up in my local install and I don't know why, bug the bug still exists.

**Comment by yugensoft** [comment]
Is this error still current?

**Comment by SabreCat** [comment]
Not seeing anything in today's logs. Will close for now!

**Comment by Alys** [comment]
This is still happening.

172.31.61.177 - - [15/Apr/2017:11:44:12 +0000] "GET /assets/audio/off/ToDo.mp3 HTTP/1.1" 404 82 "-" "okhttp/3.4.1" "188.207.110.211"

**Comment by SabreCat** [comment]
Likely client side issue. Pausing for the frontend redesign.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by librarianmage** [comment]
I checked the console, and didn't see any errors.

**Comment by lemoness** [comment]
I'm going to close this for now, but it can always be reopened if necessary.
