### ISSUE TITLE
Refused to display https://www.facebook.com/dialog/oauth.... in a frame because it set 'X-Frame-Options' to 'DENY'.

### ISSUE THREAD

**Issue by Adagio-cantabile** [HabitRPG/habitica#8335]
General Info
  * UUID: 140384ec-0082-4e51-8077-dbd84160ed62
  * Browser: Chrome 55.0.2883.95 (64-bit)
  * OS: OSX 10.11.4

### Description
When I opened the console, I found an error saying 
`Refused to display 'https://www.facebook.com/dialog/oauth/?client_id=128307497299777&response_t…com%2F%22%2C%22scope%22%3A%22basic%22%7D&scope=public_profile&display=none' in a frame because it set 'X-Frame-Options' to 'DENY'.`

The complete url after decoding is 
`https://www.facebook.com/dialog/oauth/?client_id=128307497299777&response_type=token&redirect_uri=https://habitica.com/&state={"client_id":"128307497299777","network":"facebook","display":"none","callback":"_hellojs_bn87scrj","state":"","redirect_uri":"https://habitica.com/","scope":"basic"}&scope=public_profile&display=none`

The page says `There was a problem with the parameters of the request. Redirect URI is not valid`

The requesting parameters seem incorrect.

**Comment by paglias** [comment]
Are you using any particular extension?

**Comment by Adagio-cantabile** [comment]
Yes, I'm using a socks 5 proxy, after I turn it off, the error message is gone. Seems that's the problem.
