### ISSUE TITLE
incorrect $9 option appears in list of subscription options

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8336]
As reported by cTheDragons in the Report a Bug guild:

When gifting a subscription for the month there are two options .
1 for $5 Per month
1 for $9 Per Month

The $9 option should not appear there.

It's likely that this also occurs (and should also be fixed) when buying a subscription for yourself.

**Comment by TheHollidayInn** [comment]
I merged in a fix for this. I think it hasn't been deployed yet: https://github.com/HabitRPG/habitica/pull/8327

**Comment by Alys** [comment]
Ah, sorry. I should have checked. :(
