### ISSUE TITLE
Difficulties does not highlight after saving (Web)

### ISSUE THREAD

**Issue by SirLouen** [HabitRPG/habitica#8339]
General Info
  * UUID: 99ccbddd-9e2c-42b1-a04c-78185183ed25
  * Browser: 
* In Google Chrome 55 I can highlight but after saving it doesnt appear highlighted
* In Firefox 50, I cannot even highlight by selecting a difficulty.
* In Opera 42, same as Chrome, I can highlight but after saving it doesnt appear highlighted
  * OS: Windows 10

### Description
This only happens in Web, in Mobile it works correctly:
When I click into a task or daily or Habit, and select a difficulty and then press Save, the go back to the task, and the difficulty I selected before, doesn't appear highlighted.

#### Console Errors
I cant find any error in the console

Before:
http://image.prntscr.com/image/e03c1271bc654dd496e288fe1d4ac8d2.png
After
http://image.prntscr.com/image/12f5f083e0944c5aa97b7925ff0d8e3b.png

#### Tests:
If tried creating a new task after setting it to difficulty "easy", then checking that it is not highlighted after saving, and then completing it and it reports 24 silver
Second test: creating a new task and doing the same with difficulty hard, reports 4 gold 91 silver

This means that difficult is saved in DB, so it might be just a view issue

Third test: Creating a new task, after that setting to Hard, and after that reopening it, and saving without touching the difficulty setting.  Reports 4 gold 91 silver. 

Conclusion: Is a view issue, system is missing to introduce class="active" when loading the Task info modal.

**Comment by citrusella** [comment]
Did you double click the task instead of using the edit button? This seems like it's part of this bug: #8315

**Comment by SirLouen** [comment]
Exactly, double clicked. I did not noticed it was not the whole modal result expected.
I've tried now the pencil edit button, and its completely different modal, background with the same background as the task, and I didn't noticed before but all selectors are not active regardless they where activated before.

It can be closed and merged with #8315
