### ISSUE TITLE
Subscribe page needs text describing how to give a gift subscription

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8341]
I've seen several people ask how to give gift subscriptions. They go to the Settings > Subscription page and try to find the option there. Occasionally they even buy a subscription for themself, thinking that they'll then be able to give it to someone else.

To fix this, the Settings > Subscription page (https://habitica.com/#/options/settings/subscription ) needs a sentence explaining that you can give a subscription to someone else by clicking on their avatar in the party header or their name in any chat area to see their profile, then at the bottom left click on the gift box icon.

@lemoness Do you have any preference for the wording used or the exact position on the [Settings > Subscription page](https://habitica.com/#/options/settings/subscription)?

**Comment by lemoness** [comment]
Something like "Want to gift a subscription to someone?

1. Open their profile! You can do this by clicking on their avatar in your
party header, or by clicking on their name in chat.

2. Click on the gift icon in the bottom left of their profile.

3. Select "subscription" and enter your payment information.

Thanks for supporting Habitica!"

**Comment by mleah** [comment]
I'd like to take a look at this issue.  Anything else I need to know or any reason to wait on starting?

**Comment by Alys** [comment]
@mleah Thanks! Please start whenever you're ready. 

I think the best location for it might be on the left hand side of the page under the Benefits information, but we might change our minds on that once we've seen what it looks like (apologies in advance if that happens!). I don't think there's anything else you'd need to know.
