### ISSUE TITLE
Middle click to open in new tab doesn't work

### ISSUE THREAD

**Issue by jepler** [HabitRPG/habitica#835]
I often use middle-click to visit links in a new tab, which is a configuration option in Firefox.  However, on the habitrpg game page this does not work on the links at the bottom, such as the Community/Submit Bug link.
(FF 20.0 on Linux here)

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
