### ISSUE TITLE
on-hover notes on tasks do not update after you edit the notes, until a sync occurs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8352]
When you edit the notes on a task, close the editing window, and then hover over the task to view the notes, the changes you have just made to the notes do not appear (even though the changes were saved - you can confirm that by opening the edit screen again). You have to sync before the changes will appear in the on-hover notes view.

I think this is a recent change because I've seen it reported only in the past few days (two or three times though and I've confirmed it now). Possibly it started when the new edit modal was introduced.

**Comment by declanramsay** [comment]
It seems like there might be an issue with the saving mechanism, where the task is switched to the new values contained in task._edit but not properly set - hence the update but the old value remains bound. I'd be pretty keen to take on fixing this, if that's ok?

**Comment by declanramsay** [comment]
Actually, on further inspection, it looks like the binding for the taskPopover in the task view was using one-time binding syntax, removing that solved the problem :)
