### ISSUE TITLE
Default tasks should be tagged with appropriate default tags

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8360]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

When a user first signs up, they have some sample tasks "Productive Work," "Eat Junk Food", etc., as well as a set of sample tags "Work," "Exercise," and so on. But the sample tasks don't have the sample tags applied to them, so if the user experimentally filters on one of the tags, everything disappears. It would make sense for "Productive Work" to be tagged "Work", "Eat Junk Food" to be tagged with "Health + Wellness", and "Take the Elevator / Stairs" to be tagged with "Exercise." (Dunno if any tags would be appropriate for "Join Habitica"...)

**Comment by MathWhiz** [comment]
Perhaps it could go under "Creativity"?

**Comment by librarianmage** [comment]
I can work on this!

**Comment by librarianmage** [comment]
This is what I'm planning to add:

* Productive Work -> Work, School, Chores
* Eat Junk Food -> Health + Wellness
* Take the Elevator Stairs -> Health + Wellness, Exercise

Does that make sense?
