### ISSUE TITLE
Not possible to open challenges in a new tab from main Challenges list

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8362]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

When navigating most of Habitica, links work like links anywhere else on the Web: you can click them to navigate to that view within your current browser tab/window, or right-click (or similar shortcut) and open it in a new tab or window. This doesn't work, however, for the links to individual Challenges on the Challenges page. Mousing over the link doesn't preview a URL, and right-clicking doesn't provide options for opening the link. 

It's not clear why this should be the case; clicking the link does open a specific URL (`/#/options/groups/challenges/UUID`). And the lack of new-tab ability greatly slows down workflows involving work with several Challenges in sequence, such as monthly updating of the Take This archives in the Library of Tasks and Challenges guild.

I've tried using the Edit button in the individual Challenge, too, but it has the same trouble.

**Comment by librarianmage** [comment]
I can work on this!

**Comment by librarianmage** [comment]
I fear that I will have to drop this, as this area is rather complex and I am rather inexperienced with Angular. I am sorry :(.

**Comment by Alys** [comment]
@MathWhiz That's okay! Thank you for letting us know!

**Comment by krolov** [comment]
Hello!
I can work on this task.

**Comment by Alys** [comment]
@krolov Thanks! Comment here if you have questions or run into trouble.

**Comment by krolov** [comment]
Just want to update, that I still on this task

**Comment by Alys** [comment]
@krolov I'm putting this on hold because we're most of the way through a project to improve the website, which might make this issue irrelevant, or at least will change that code that needs to be modified to fix it.

**Comment by lemoness** [comment]
We've made many changes to the website, and this doesn't appear to be an issue any more. I'm closing this ticket, but if you feel that it should be reopened for any reason, please feel free to leave a comment!
