### ISSUE TITLE
Lunar Battle 2 

### ISSUE THREAD

**Issue by squirrel7** [HabitRPG/habitica#8363]
General Info
  * UUID: 109c76c6-fb20-446b-99f3-28bb1414b3fd
  * Browser: Chrome
  * OS: Windows 7

### Description
I am in a party of two, and both members have received the first 2 lunar battle scrolls. I have completed Lunar Battle 1 twice, and Lunar Battle 2 once. I cannot do the second Lunar Battle 2 scroll because it says that I have to complete Lunar Battle 1 before I can do that and it does not recognize that I have done it. My achievement list shows that I have completed LB2 one time, but does not list LB1 at all. The other member of my party (UUID b1193786-4f34-47ab-be50-48d2bad1202d) shows LB1 x2 and LB2 x1 in the achievement list.

**Comment by Alys** [comment]
This has been handled in the Report a Bug guild so I'm closing this. The quest wasn't completed recently so I don't think it's an example of the fixed quest bug.
