### ISSUE TITLE
purchases of backgrounds are not shown in Amplitude

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8365]
I can't find any records in Amplitude of my account purchasing backgrounds. We need this information to help troubleshoot bugs.

I tested on the production website by buying first a single background then a set. UUID 3e595299-3d8a-4a10-bfe0-88f555e4aa0c

**Comment by librarianmage** [comment]
What is "Amplitude"?

**Comment by Alys** [comment]
It's for tracking things like which purchases a user makes, when they cron and with what stats, when they die, etc. Very helpful for resolving bugs. `git grep -i amplitude` in the repository's root directory shows where amplitude code is. Thanks for asking - I should have explained.

**Comment by wangjames** [comment]
Is Amplitude is correctly tracking purchases for everything else except backgrounds?

**Comment by cailinglu** [comment]
I can work on this one :)

**Comment by cailinglu** [comment]
Should hair, skin, and shirt purchases also be sent to Amplitude?

**Comment by TheHollidayInn** [comment]
I would like that! Pretty much anything purchased with Gems would be nice to see.

**Comment by librarianmage** [comment]
Should this be marked as in progress?

**Comment by Alys** [comment]
Yes, thanks!

**Comment by SabreCat** [comment]
OK, I'm sorry to have let a bunch of contributor development go on about this without clarifying the issue...

Some Gem purchase data is going through OK. Purchases of Market items like quests, hatching potions, and food, are all still being recorded as expected. But for some reason items you buy with Gems outside of the Market, like backgrounds, skin and hair colors, and so on, are not being recorded. I.e., this block of code is not running the way it should: https://github.com/HabitRPG/habitica/blob/98c019a0b658df1fb5f0c6db5b09b379d6cb58e2/website/common/script/ops/unlock.js#L101-L109 We can see in our analytics data that purchases tagged "customization" have not been recorded in some time.

That's what needs fixing--we don't need to add new tracking so much as get the existing tracking working in all cases again.

**Comment by SabreCat** [comment]
For those who have Amplitude access and want to see this data, the path is

Create Chart >
Event Segmentation >
"acquire item" event
where acquireMethod = Gems
grouped by (whatever)

**Comment by librarianmage** [comment]
Are you still working on this, @caillu?

**Comment by cailinglu** [comment]
@MathWhiz not working on this currently. I think I was doing it incorrectly before.

**Comment by Alys** [comment]
labels updated

@caillu Thanks for letting us know!
