### ISSUE TITLE
Dates under task data and XP data are not entirely visible.

### ISSUE THREAD

**Issue by zerom1** [HabitRPG/habitica#8369]
General Info
  * UUID: f298bb5d-78a1-4c05-b948-49ad1eae29bb
  * Browser: Chrome 55.0.2883.87 m
  * OS: Windows 10 Family x64

### Description

Hi everyone, I've been using Habitica for a month and I noticed something. When looking at the data of any particular task or of the XP level (the yellow bar), the dates are not displayed properly. There seems to be no space for the first digit, the one at the far bottom... I'm French so I'm using the dd/MM/yyyy format, and I'm talking about the web display, using Chrome on a 15 inches computer.

Here are two examples : the display of XP data, and the display of task data. In both cases, you'll be able to see it's displaying the switch between 2016 and 2017. Don't forget I'm using European format.
![one](https://snag.gy/ucWbRa.jpg)
![two](https://snag.gy/MvqGp1.jpg) 
Please forgive my mouse-drawing skills...

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
This doesn't happen in my browser, so it might be browser specific. If anyone else can reproduce it, please post here.

**Comment by librarianmage** [comment]
Should this be closed? The graphs are currently being considered (IIRC).
