### ISSUE TITLE
Site does not work if facebook.com is unreachable

### ISSUE THREAD

**Issue by Julienoune** [HabitRPG/habitica#837]
Hello guys,

I'm behind a proxy filter at my work and I've got this error message : 
Failed to load resource https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fhabitrpg.com&l…ount&show_faces=false&width=100&action=like&font=arial&layout=button_count

Apparently it seems to block all the action on the site.

It's does not work since yesterday.

Windows Seven, chrome user.

Cheers all.

Julien

**Comment by lefnire** [comment]
Shouldn't be the case, Facebook login and registration is just used for
storing an identifier in the database. Can you try clearing cache and
cookies for all time for habitrpg? Or different browser?

**Comment by StanLindsey** [comment]
@Julienoune - Is this issue still occurring?

**Comment by Julienoune** [comment]
Hi Stan,

no this issue only occured during a couple of days.
it is no longer a problem

Thanks

Julien

Skype : julien-gerard
Mobile : +687 932149
