### ISSUE TITLE
"Blessing" spell isn't working

### ISSUE THREAD

**Issue by MercuryChaos** [HabitRPG/habitica#8370]
General Info
  * UUID: ba9920a5-b079-4db8-ad25-f47bb81d2f5f
  * Browser: Chrome
  * OS: Windows 7, Mac OS Sierra

### Description
 When I cast the "Blessing" spell, it doesn't have any effect on the other members of my party - it only helps me. I also get an notification from the website (the red bubble in the upper right-hand corner) that says something like "BOSS_DAMAGE is not a valid enum value for path 'type'" (I can't copy and paste because it disappears when I click it.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None.

**Comment by Alys** [comment]
@MercuryChaos That's a side-effect of this bug: https://github.com/HabitRPG/habitica/issues/8338  (I've just updated the title to make it contain "BOSS_DAMAGE", so you wouldn't have noticed it if you'd searched for that issue - sorry about that).

You weren't affected by that bug but one of your party mates was. I've cleared the problem for them. 

Can you please try again now and tell us if it works or not?

**Comment by MercuryChaos** [comment]
It doesn't seem to be - the party member who I'm pretty sure you're referring to still has their health stuck at 15. Also, my party members' HP is no longer displaying in the guild sidebar where everyone's username is listed. It just says "( HP)".

**Comment by Alys** [comment]
That HP problem is a new known tbug: https://github.com/HabitRPG/habitica/issues/8376
It should be fixed the next time we deploy changes to the website (probably within a day or two). Lets wait until that's happened before we proceed with this issue, since it's too hard to work out what's going on when you can't easily see your party's HP values. Sorry about this. :(

**Comment by lynxlynxlynx** [comment]
Btw, blessing just worked in our party. Someone cast it and I got healed.

**Comment by SabreCat** [comment]
Great! I'll close this for now, but feel free to reopen if you see any similar trouble.
