### ISSUE TITLE
Quest button labels do not match quest instructions

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#8371]
### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
Quest instructions read:

> Clicking "Invite" will send an invitation to your party members. When all members have accepted or denied, the quest begins. See status under Social > Party.

But the buttons are labeled "Cancel" and "Start Quest"

**Comment by Alys** [comment]
Good point, thanks! I think the button should be "Invite" because there's already confusion over starting quests. Perhaps even "Invite party to quest" - there's room for a long button.

Opinions, anyone?

**Comment by citrusella** [comment]
Does the button say different things depending on whether it's a multi-member party or a single-member one?

**Comment by Alys** [comment]
Hmmmm. I believe it does not, but it should! It definitely says "Start quest" on a multi-member party. It would be good to say that on a solo party but "Invite party to quest" otherwise.

**Comment by DrStrangepork** [comment]
I will look into the single/multi-member party issue and report back.

**Comment by DrStrangepork** [comment]
When the sole member of a party starts a quest, the button says "Start Quest".

-----
However, when not yet in a party, the buttons "Start a Party with your friends!" and "Invite Friends Now" open the "Name your new party!" popup, and on that popup I see a condensed blue button with no text:
```
<button type="submit" class="btn btn-primary btn-block ng-binding"></button>
```

- Hitting this button with no invite fields filled out results in an error message.
- Hitting this button with invite(s) that results in an error message (bad email, bad UID, etc) results in the party being created, however then hitting Close returns you to the "Start a Party with your friends!" screen, and hitting the Sync button does not change this, so there is no indication you are in a party unless you refresh the browser. The "Start a Party with your friends!" and "Invite Friends Now" buttons still open the "Name your new party!" popup, but any attempts there to invite players results in the error popup "<red !> Already in a party, try refreshing."
- After refreshing, the party is there, and hitting the "Invite Friends Now" button now opens the same invitation popup, but now the blue button is labeled "Send Invitations":
```
<button type="submit" class="btn btn-primary btn-block ng-binding">Send Invitations</button>
```

Not sure if all that is related, but it may be good to know if the "Start" button on the popup should have different text depending on whether party has 1 or 2+ members.

**Comment by DrStrangepork** [comment]
So should the instructions be changed from "Invite" to "Start Quest"?

**Comment by librarianmage** [comment]
This appears to have been fixed.
