### ISSUE TITLE
task columns are too thin in small windows on some browsers

### ISSUE THREAD

**Issue by toddmedema** [HabitRPG/habitica#8372]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 6a60aecd-4aa9-4365-ae16-6775ad8b9e98
  * Browser: Chrome
  * OS: Mac

### Description
The website was doing just fine on the free version, but something about upgrading to a subscriber broke the website when I have my browser window take up 1/2 my MacBook Pro screen (960px) wide. See screenshot below - essentially, it knows it should only try to fit two columns in 960px, but the two columns are squished to half the window, as if it's trying to fit all four....

<img width="955" alt="screen shot 2017-01-05 at 10 13 02 pm" src="https://cloud.githubusercontent.com/assets/775657/21706374/a50eb05a-d394-11e6-908f-9c97214ae3e7.png">

#### Console Errors
```js
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitica.com" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)
```

**Comment by IronWalnut** [comment]
I am having this same problem on Windows where it only uses half the available space in the 2x2 layout. Today is the first time I'm noticing this, it was fine last night.

Attached a screen capture to demonstrate as well as a console warning.
![capture](https://cloud.githubusercontent.com/assets/12644611/21721906/4cc02cf8-d3f8-11e6-8ea5-767da57c3e93.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12644611/21721939/6b3b054a-d3f8-11e6-8810-8a12abc2ad4a.PNG)

**Comment by Alys** [comment]
@toddmedema This shouldn't have come from you buying a subscription (thanks for that by the way!). Subscriptions don't adjust how the website displays, although we do have a temporarily subscription-related bug at the moment - those "claim" buttons on the tasks shouldn't be there and they show only for subscribers, so maybe that's related.

Those error messages come from a browser extension so the extension might be causing the layout problem, or it might be unrelated. If unrelated, the errors don't look like anything too worrying.

Please close and reopen your browser and if that doesn't fix it, disable all extensions temporarily (or if you prefer, open Habitica in an incognito window with no extensions enabled). Also check that you're accessing the site using https://habitica.com with no "www." in the URL.

Please tell us how that goes. 

@IronWalnut The warning message isn't related and can be ignored. Please also try with all extensions turned off. If that doesn't help tell us if you're a subscriber.

**Comment by IronWalnut** [comment]
I tried again with two different browsers (Firefox & Edge with no extensions enabled) and same issue. I am also not a subscriber. Again, weirdly enough this only appears to effect the 2x2 layout. The full screen (4x1) and very small screen (1x4) appear to be working normally.

Edge:
![capture2](https://cloud.githubusercontent.com/assets/12644611/21723166/6e911270-d3fd-11e6-8a5c-8435508a2ad0.PNG)

Firefox:
![capture](https://cloud.githubusercontent.com/assets/12644611/21723171/73262fe6-d3fd-11e6-95b4-951bae1eac13.PNG)

**Comment by TheHollidayInn** [comment]
Are the other two tasks lists missing or just stacked under?

**Comment by IronWalnut** [comment]
Oh my mistake I should have been more specific. The other two boxes are stacked underneath in my screenshots. It appears that the 2x2 layout is only using half the available width of that space. As I expand & contract my window size the box width DOES shift, but only uses half the space on this particular layout.

**Comment by haleyrc** [comment]
I'm encountering this same issue. Specifically it breaks in the 768-991px range, which seems to be missing a CSS rule to update the width of the task-column elements to 50%.

**Comment by citrusella** [comment]
This is happening on Firefox (50.0.2) for me as well, and I've had my window at this size before without it doing it. They used to take up the whole space when in the "grid/quadrant" sort of layout.

**Comment by Alys** [comment]
I can replicate this on Firefox on Ubuntu Linux. When the browser window gets small enough for the To-Dos and Rewards to move under the Habits and Dailies, they do move as they are supposed to, but the columns then do not become wider (they should).

I can't replicate on Chrome but it might be OS specific for Chrome.

**Comment by Alys** [comment]
I'm renaming this issue from "UI Bug: breaks when window is 1/2 Macbook Pro screen (subscriber)" to "task columns are too thin in small windows on some browsers"

**Comment by librarianmage** [comment]
I am also having this problem (Win 10, Chrome 55.0.2883.87 m (64-bit))
