### ISSUE TITLE
party page's list of members no longer shows HP

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8376]
The list of members on the party page should show each member's HP. It currently does not. In the screenshot below, you can see the blank space before "HP" where the health should go.

This almost certainly happened in [Release v3.66.1 Group Plans for Parties](https://github.com/HabitRPG/habitica/releases/tag/v3.66.1) or in the release after it (3.66.2 probably; it's not on the releases page yet).

![image](https://cloud.githubusercontent.com/assets/1495809/21729051/3ed70e74-d441-11e6-8533-f467799f5d41.png)

**Comment by brightbold** [comment]
**Thank you** for fixing this regression, @TheHollidayInn! This feature is really helpful for healers so I'm glad it looks like we'll have it back shortly.

**Comment by TheHollidayInn** [comment]
No problem, since I am the on that broke it :P.
