### ISSUE TITLE
NYE (and assume Valentine) Card  is hard coded.

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8379]
## Description

The website code that displays New Years cards in the shop is definitely hard coded to show/hide them. I am assuming it is also the same with the Valentine card. 

Could you please adjust the API so the card is unable to be used outside these times.

Could you please adjust the Content Data to show if the card is available. This will allow Comrades  to show  the cards at the correct time in their applications.

Thanks

**Comment by SabreCat** [comment]
I actually committed a change to do that, but had to revert it because our own native mobile apps don't support sending cards to party members yet. @vIiRuS

**Comment by Alys** [comment]
I'm closing this in favour of https://github.com/HabitRPG/habitica/issues/9697 which is for a generic fix for a range of similar problems.
