### ISSUE TITLE
Failiure to install npm correctly

### ISSUE THREAD

**Issue by brianhoping** [HabitRPG/habitica#8383]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 
  * Browser: Google [Chrome]
  * OS: Windows 10 64 bit

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

I'm an aspiring blacksmith and I'm trying to setup Habitica locally on my 64bit windows 10 laptop but i'm failing to install npm correctly even though I have the correct Node and npm versions.

![image](https://cloud.githubusercontent.com/assets/10646137/21749846/821dfc62-d55c-11e6-8d44-4a8cb3ab3492.png)

When I skip ahead and try to launch the server, I get the following errors:

![image](https://cloud.githubusercontent.com/assets/10646137/21749852/9c3bc43a-d55c-11e6-8cd5-a333d09d2e6e.png)

![image](https://cloud.githubusercontent.com/assets/10646137/21749859/bbb865ca-d55c-11e6-901f-d97e0fe673ed.png)

Any help would be greatly appreciated, thanks.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by TheHollidayInn** [comment]
You need to run mongod in a separate terminal first
