### ISSUE TITLE
Add Habitica app to F-Droid store

### ISSUE THREAD

**Issue by Coehill** [HabitRPG/habitica#8384]
Continuation of [this issue](https://github.com/HabitRPG/habitica/issues/5562):
________________________________

F-droid is the leading app store exclusively for Free and Open Source Software for Android. It would be the most natural thing in the world for Habitica, built as FOSS from the start, to be available there.

I want to use the app, but I don't want to connect my phone (my pocket computer that knows everything about me and a lot about my friends) to Google. Today that means that I can't use the app, because Google Play Store is the only place to get it.

Here is the information on how to submit an app to F-droid: https://f-droid.org/contribute/

I really hope you will be able to do this soon! Then you will also make Habitica known among a lot of people in the open source (development) community.

Thank you!

**Comment by Alys** [comment]
In case anyone else is seeing this and is curious about the state of it, please follow the issue that @DistantParadox linked to at the top of his comment.

@DistantParadox It's always best to add comments to an existing issue rather than make a new one. That keeps all notes about the issue in one place.

**Comment by mandyzhou** [comment]
I see @DistantParadox has already found it, but for anyone else who sees this, there's [a more up-to-date discussion in the Android app's repository](https://github.com/HabitRPG/habitica-android/issues/194) than in the issue linked above.

**Comment by Coehill** [comment]
@Alys @mandyzhou Thanks, I realized my mistake soon after posting, which is why I closed the issue.
