### ISSUE TITLE
Prizes

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#839]
it's kind of like having a habit/daily linked to a specific reward
like if i take the stairs 5 times then i earn a cookie (and the cookie thing will stay until i checked that i received my reward)
and if i were to take the stairs 10 times but i never recieved my first cookie then it would say that i have 2 cookies
you would be able to set a "Prize" and amount of times you do a Habit/Daily until you get your prize

**Comment by wildcate** [comment]
Something similar has been discussed in #560 a while ago, and the discussion was moved to trello.
