### ISSUE TITLE
FaceBook Pixel isn't firing correctly - delete it

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8390]
From jmcook (06faccc5-5f69-453c-9a9d-0eeed865985c) in the Report a Bug guild:

"**It looks like the FaceBook Pixel isn't firing correctly. I'm using the 'Facebook Pixel Helper' Chrome extension. This doesn't affect anyone, except the companies marketing team.**"

I haven't done anything to verify or investigate this.

FYI: definition of [The Facebook Pixel](https://en-gb.facebook.com/business/help/651294705016616)

**Comment by SabreCat** [comment]
The pixel can probably be removed. We had thought it might have some more sophisticated referrer tracking than we currently had implemented, but as far as I've heard, that's not the case. @lemoness, has the Facebook analytics been valuable for you?

**Comment by lemoness** [comment]
Unfortunately, it didn't turn out to provide the analytics that we had
hoped. I think we can remove it.

**Comment by librarianmage** [comment]
I can remove it!
