### ISSUE TITLE
Progress graph: Date problems

### ISSUE THREAD

**Issue by waahto** [HabitRPG/habitica#8395]
Not that they're consistently unintuitive but that they're inconsistently unintuitive.

FWIW, 1, 2 and 3 are habits, 4, 5 are dailies.

![screen shot 2017-01-11 at 14 48 59](https://cloud.githubusercontent.com/assets/16896115/21849215/52b182b0-d80d-11e6-849a-474fbcd75f2c.png)
**1** Why do I have three points on a graph that spans a single day? Are they based on the actual time I did them? My guess here is that they're most likely not.

![screen shot 2017-01-11 at 14 48 44](https://cloud.githubusercontent.com/assets/16896115/21849218/52b25e1a-d80d-11e6-80b8-77c12eba647c.png)
**2** Why is it first skipping days and then doubles the ninth and skips tenth. I'm 100% sure I've done my pushups every day :)

![screen shot 2017-01-11 at 14 48 29](https://cloud.githubusercontent.com/assets/16896115/21849217/52b23688-d80d-11e6-9932-e7260c3d4f60.png)
**3** Same as previous.

![screen shot 2017-01-11 at 14 49 19](https://cloud.githubusercontent.com/assets/16896115/21849214/52888482-d80d-11e6-8fcc-362a403de521.png)
**4** Why is this looking so normal?

![screen shot 2017-01-11 at 14 49 10](https://cloud.githubusercontent.com/assets/16896115/21849216/52b19d40-d80d-11e6-84c1-1cec7c70f0d0.png)
**5** And this is not — but it goes back in time less than **2**.

There are plenty of ways on how to deal with this. Some ideas:
- If there's only 1 date in the history, make an exception and display a point instead of a line.
- If there are less than 8 dates, display them all
- If there are more than 8 dates, display n of them, spaced evenly. In general, it would do to display just 5 or 6 date values, 8 looks rather crowded. For example
  - 9 dates in history, display 6: 1, 3, 5, 7, 9, 11
  - 10 dates in history, display 5: 2, 4, 6, 8, 10
  - 13 dates in history, display 6: 1, 3, 5, 7, 9, 11, 13
  - 20 dates in history, display 5: ...

**Comment by librarianmage** [comment]
Semi-related issues:

* #7907 
* #5724 
* #6337 
* #3810
* #2948 
* #2516

**Comment by librarianmage** [comment]
Should this be closed, during the task value graph reimplementation?
