### ISSUE TITLE
gem gift message is missing most of the text

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8397]
When a player sends gems to another player, the recipient is supposed to see an inbox message saying:

`Hello [recipient's name], [sender's name] has sent you 2 gems!`

For example:

![image](https://cloud.githubusercontent.com/assets/1495809/21866165/ed10d710-d840-11e6-8f03-bf82155e2c30.png)

However the message currently says only this:

`2 gems!`

For example (one of these has an optional message entered by the sender):

![image](https://cloud.githubusercontent.com/assets/1495809/21866206/1d1d79b8-d841-11e6-8fd3-5dfa310b8f9a.png)

I.e., `Hello [recipient's name], [sender's name] has sent you` is no longer being inserted into the message. It should be.

**Comment by Moniarchy** [comment]
Hi! Can I take this issue?

**Comment by Alys** [comment]
@Moniarchy Yes, thank you!

**Comment by lynxlynxlynx** [comment]
Sounds like a regression from #8283.

**Comment by khipkin** [comment]
Looks like #8312 was not the only bug caused by string name regressions in [this commit](https://github.com/HabitRPG/habitica/commit/ea24eeb0199a687115da0224b64b62c57629aea2#diff-040152bf2f4ce00a01ce5aa334f0851f)...

**Comment by TheHollidayInn** [comment]
Yea, I think there is something with the line endings that is causing the difference to mess up.

**Comment by khipkin** [comment]
It's weird that the unit tests aren't catching these problematic regressions. That itself is a bad smell.

**Comment by Moniarchy** [comment]
Plugging away on this, also using this as a learning opportunity since I have not contributed here before so taking some time reading up on particular technologies in this stack/reading through the codebase. I want to be cognizant of the time I'm taking. Is there a particular timeframe I should try to have this complete by?

**Comment by lynxlynxlynx** [comment]
The only deadline is when someone else gets annoyed or excited enough to beat you to the punch.

**Comment by Alys** [comment]
@Moniarchy How are you going with this? Need any advice or have any questions for us?

**Comment by Moniarchy** [comment]
@Alys Hi! I've been overwhelmed with work so haven't fixed the code but I'm going to be working on it this evening. I think I pinpointed the problem a while ago but I stopped when I had a rebase problem. Anyway, look forward to a PR soon, thanks for all the patience.
