### ISSUE TITLE
Nonsense coupon code looks like it's accepted until payment process continues

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8398]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Habitica occasionally uses coupon codes to discount a subscription (most commonly extending the 20% discount normally reserved for year-long subscriptions to also apply to 6-month subscriptions). These are entered in a field at /#/options/settings/subscription . However, the coupon code field does not correctly validate the code before previewing the new price; the user only runs into an error when they attempt to proceed with the subscription. Sometimes (maybe only on Amazon Payments?) there is no error, but the subscription is created at full price.

The coupon code field should hit the Validate Coupon route https://habitica.com/apidoc/#api-Coupon-ValidateCoupon right away, so users aren't led on further than necessary by the bogus coupon codes we sometimes see flying around.

**Comment by madpink** [comment]
FYI - I submitted a coupon code for 20% off, it looked as though it was accepted, but I was charged the full amount

**Comment by TheHollidayInn** [comment]
@madpink Which payment processor did you use?

**Comment by madpink** [comment]
Amazon payments

**Comment by TheHollidayInn** [comment]
@SabreCat Amazon payments is what I mentioned in Slack.

**Comment by SabreCat** [comment]
Updated the ticket to mention users might not even see an error.

**Comment by cailinglu** [comment]
May I try solving this?

**Comment by TheHollidayInn** [comment]
Please!
