### ISSUE TITLE
Royal Purple Flying Pig Pet has white background near the tail instead of transparent

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8399]
The Royal Purple Flying Pig Pet has white background near the tail instead of being transparent:

![image](https://cloud.githubusercontent.com/assets/1495809/21869342/0e9e8108-d84f-11e6-877f-da542224d3cc.png)

For comparison, a Cotton-Candy Blue pig:

![image](https://cloud.githubusercontent.com/assets/1495809/21869359/2f378180-d84f-11e6-8ca2-c641666da558.png)

_(Thanks  to Aniksja for reporting this in the Report a Bug guild.)_

**Comment by Alys** [comment]
Anyone modifying the image would have to send a permissions email first as described in https://trello.com/c/eFz57Pqi/24-permissions

However if an Artisan modifies the image and a Blacksmith adds it to repository, the Blacksmith doesn't need to do the perrmissions email. 

I'm linking to this post from the [Pixels in Progress (Aspiring Artisans)](https://habitica.com/#/options/groups/guilds/a141a5b9-0d69-46cd-93e6-2b76f18bcc54) guild.

**Comment by librarianmage** [comment]
I can do this (I have already sent the permissions)
