### ISSUE TITLE
Refresh page, or re-establish socket.io when connection is lost

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#84]
Habit uses Socket.io to maintain persistence over real-time. If the server crashes and needs a restart, or if I push a fix - the session is broken between active clients and the server. The client flickers 'Disconnected' for a while, then when the server comes back online that message disappears - however, Socket hasn't made a _proper_ re-connection, and any changes made between the time the server came down, and the time the user refreshes the page are completely lost.

The first thing to fix of course, is the server crashing for any reason. But that's a work in progress, and often out of my hands (I'm using the bleeding-edge Derby). Second thing to fix is to announce when I'm restarting the server (Twitter?). The biggest fix, however, will be to automatically **refresh** the page when the server connection has been re-detected. Possibly upgrading Socket.io, as well?

**Comment by lefnire** [comment]
I'll make sure to tweet each deploy in the future, if I need to deploy before I can get an automated refresh in place. Follow me at @lefnire

**Comment by gemando** [comment]
So (if I understand you correctly) I can't do anything at the moment about the "offline" messages which keep appearing apart from not to change/log anything because it won't save, and just to refresh the page to check if it's back online?

**Comment by lefnire** [comment]
unfortunately, at present that is correct. I'm working on fixing this bug, and it's 99% a result of the huge [traffic surge](http://www.reddit.com/r/LifeProTips/comments/16o98k/lpt_turn_your_life_into_an_rpg_by_tracking_your/) from today - so once that dies down we should have breathing room. If you can't wait to use the app, I'd say [install on your machine](https://github.com/lefnire/habitrpg/wiki/Running-Locally) at present (it's pretty easy actually), but I'm keep you posted on this thread as progress is made.

**Comment by gemando** [comment]
Okay thank you. What difference will having it installed on my machine make? Will it just save my progress locally and then upload it to the main servers whenever they're online or does it run completely on my computer?

**Comment by lefnire** [comment]
yeah, it would be completely on your computer. it would work smoothly, but you're right you'd miss out on social stuff &  website integrations, so maybe just hang tight for now

**Comment by gemando** [comment]
Will do :)

**Comment by ancientcampus** [comment]
Idea for a temporary patch:
When the server goes down, instead of saying "Disconnected from server, click here to reconnect" up top, make the whole screen go grey or something. Make it clear to the user that their clicks won't be saved.

**Comment by blueskymonster** [comment]
If you want to give users a few minutes of heads up before you deploy a new version, there's this little service: http://informuser.com/

**Comment by ghost** [comment]
Could you store all the information being sent to the server in LocalStorage if there isn't a heartbeat from the server? That is, when the page detects the server being down (socket.io should send a 'disconnect' when it goes down), it will store whatever info you send to node.js in some form on LocalStorage. Then, have a heartbeat check happening on client side (just do a setTimeout() that asks for a simple message). If the heartbeat checks out, submit the stored data.

This might be totally off-base from what you want, but it's an idea. I don't know if Socket.io has this built in - been a few months since I've done work with it.

**Comment by lefnire** [comment]
Derby uses memory store for when there's no connection. It stores
everything in the current browser session and pushes changes once the
connection is re-established. It would take quite some effort to change
that to LocalStorage, if someone's willing to write the plugin I'd be down,
but I'm not available for that. See Racer

**Comment by lefnire** [comment]
this actually happens now, awesome. don't know if it was a recent racer release
