### ISSUE TITLE
Checked off daily not being recognised, streak on that daily reset on next day

### ISSUE THREAD

**Issue by Nerzenjaeger** [HabitRPG/habitica#8404]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 2aa635ed-8b07-414a-bb3e-d8480159c2c0
  * Browser: Google Chrome
  * OS: Windows 7

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

I checked off a Daily yesterday only to find my current streak on that daily task not recognised and being reset to 0. Is there a possibility to correct this? Maybe it's just a synchronisation issue?

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Yes, it will just be a sychronisation issue. At the end of each day, it's recommended to click the sync button on the website or mobile app and then check that all Dailies that should be completed are. Also, this might not be relevant to you but in case it is, if you have several Dailies that you can mark completed at once, it's best to pause between ticking each one to give the site or app a chance to sync. If you tick several tasks in quick succession, the site/app can't send the information to Habitica's server fast enough to keep up and sync errors can then happen. You can adjust streaks on your Dailies in the advanced options section of their edit forms.

By the way, we have a guild within Habitica for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. When you find a bug, you can start reporting it by putting a brief message there - just enough to explain the problem, optionally with a link to a screenshot from a file sharing or image sharing site if you think that helps. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, a moderator would advise you of that.
