### ISSUE TITLE
I have 410/380 experience, how can that be?

### ISSUE THREAD

**Issue by h-2** [HabitRPG/habitica#8409]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: h-2
  * Browser: Firefox 50.1.0
  * OS: FreeBSD 11

### Description

I have 410/380 experience, how can that be? Reloading doesn't help.
![screenshot](https://cloud.githubusercontent.com/assets/2996863/21955987/68e11292-da76-11e6-951d-e95363394bd6.png)

#### Console Errors

```
"Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
z/<@https://habitica.com/app-868f7cc6.js:36:16413
w.authenticate@https://habitica.com/app-868f7cc6.js:50:879
@https://habitica.com/app-868f7cc6.js:50:2107
i@https://habitica.com/app-868f7cc6.js:7:18055
c@https://habitica.com/app-868f7cc6.js:7:16451
i@https://habitica.com/app-868f7cc6.js:7:18055
Tb/j.$injector<@https://habitica.com/app-868f7cc6.js:7:16101
g@https://habitica.com/app-868f7cc6.js:7:17690
i@https://habitica.com/app-868f7cc6.js:7:18024
ic/this.$get</</<@https://habitica.com/app-868f7cc6.js:8:9483
na/<@https://habitica.com/app-868f7cc6.js:8:3817
x@https://habitica.com/app-868f7cc6.js:6:25193
na@https://habitica.com/app-868f7cc6.js:8:3801
r@https://habitica.com/app-868f7cc6.js:7:30452
b@https://habitica.com/app-868f7cc6.js:7:29500
a/<@https://habitica.com/app-868f7cc6.js:6:31659
wd/this.$get</j.prototype.$eval@https://habitica.com/app-868f7cc6.js:9:17443
wd/this.$get</j.prototype.$apply@https://habitica.com/app-868f7cc6.js:9:17677
a@https://habitica.com/app-868f7cc6.js:6:31617
i@https://habitica.com/app-868f7cc6.js:7:18055
xa/g@https://habitica.com/app-868f7cc6.js:6:31536
xa@https://habitica.com/app-868f7cc6.js:6:31846
wa@https://habitica.com/app-868f7cc6.js:6:31069
@https://habitica.com/app-868f7cc6.js:11:1778
o.Callbacks/j@https://habitica.com/app-868f7cc6.js:3:27783
o.Callbacks/k.fireWith@https://habitica.com/app-868f7cc6.js:3:28601
.ready@https://habitica.com/app-868f7cc6.js:3:30393
I@https://habitica.com/app-868f7cc6.js:3:30563
"  app-868f7cc6.js:36:15999
Connecting to Pusher.  app-868f7cc6.js:50:2952
```

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitica/issues/2433 for details of this bug.

By the way, we have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. When you find a bug, you can start reporting it by putting a brief message there - just enough to explain the problem, optionally with a link to a screenshot from a file sharing or image sharing site if you think that helps. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, a moderator would advise you of that.
