### ISSUE TITLE
Migrate to AngularJS

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#841]
Still open for discussion, but I'm leaning pretty heavily towards migrating to Angular. Derby was a good prototyping platform, and has gotten us this far - but it's a poor choice going forward. We're experiencing **far** too many debilitating, inexplicable bugs and they're compounding over time. The difficulty of E2E-testing Derby makes them even harder to manage. [refLists](https://github.com/lefnire/habitrpg/issues/634), [memory leaks](/lefnire/habitrpg/issues/165), un-clickability... I think a nail on the coffin in my mind is https://github.com/lefnire/habitrpg/issues/836 - I committed https://github.com/lefnire/habitrpg/commit/251890f to solve https://github.com/lefnire/habitrpg/issues/769, and while it solved it for some people, it caused the _exact_ problem for other people - it's like it inverted the bug for the Habit population. It shows how precarious and brittle our code is - how dangerous it is to touch any workaround-constructs we have. Eg, look at our "restore corrupt refLists" function  ([code](https://github.com/lefnire/habitrpg/blob/7f2d309eb527a41924c83e33fcb45cc1ae08ccc5/src/app/index.coffee#L22)) which salvages missing tasks from users lists. That's been there since the beginning as an emergency bandaid until I could revisit it. Many moons later, after thorough step-debugging to uncover Habit culprit code, there is none - but the bandaid is still required. We have this silly `startTxn() / commit()` hack-job [here](https://github.com/lefnire/habitrpg/blob/7f2d309eb527a41924c83e33fcb45cc1ae08ccc5/src/app/character.coffee#L125) since Derby [doesn't scale without it](https://github.com/codeparty/racer/issues/93) - but there's radio-silence on that thread. 

Alas, fun framework - great prototyping, but not ready for primetime. We'll keep the Express API in place, and once we have the mobile app released we'll have boilerplate Angular code to drop in. We'll continue using Racer in the Express routes for accessControl & querying convenience, and only remove that if we still find the memory leak exists. If this migration happens, it probably won't be for a good-long-while, since it's such a taxing task.

@switz @zakkain @toebu @SlappyBag and others, wondering your thoughts on all this

**Comment by switz** [comment]
Let's G+ hangout about this today.

**Comment by wizonesolutions** [comment]
What time you guys meeting? I'd be interested. Interested in Angular.

And just to drop this out in the open, has Meteor been considered? You'd get great support from them as a large app. They've got the $$$ :)

I know it probably has been and determined unneeded, but just curious.

**Comment by lefnire** [comment]
I think Meteor would be more difficult to retrofit. The database expects particular formats, so does Derby's. Since we already have our API communicating with the database in a certain fashion, and we're building the Angular mobile app to work with it - I think expanding that Angular code to the current /views/\* in the website would be easier. 

The other thing is Meteor's REST is not build on Express right? So to keep our current REST solution we'd have to have two servers running in parallel. 

Overall, while Meteor looks pretty bad ass, I think it would be more of a full-fledged overhaul, where an Angular migration (just due to our API / Mobile progress) would be more a shimmy-in

**Comment by wizonesolutions** [comment]
Meteor's off Mongo too, but I know what you're saying. And then you have to dogfood your own API, which is always good and will make it better.

The less retrofitting the better. See http://www.joelonsoftware.com/articles/fog0000000069.html (never rewrite) :)

**Comment by toebu** [comment]
You're right, Derby just has too many weird glitches. I'm definitely pro Angular!

**Comment by litenull** [comment]
Willing to kick on the website after we finish v1.

On Sat, Apr 20, 2013 at 10:47 PM, Tobias Leugger - Vibes <
notifications@github.com> wrote:

> You're right, Derby just has too many weird glitches. I'm definitely pro
> Angular!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/841#issuecomment-16711035
> .

## 

LP, Tomaž :)

**Comment by wizonesolutions** [comment]
@lefnire How did your sizing-up of Angular go?

**Comment by lefnire** [comment]
It actually seems to be pretty simple so far! it'll obviously take quite a long time, and devil's in the details - but just going through moving big boulders, most things seem to map 1-1. I'm working on converting a few Derby templates to Directives (modal dialog, herobox, etc) - which is less a direct mapping, but pretty simple besides. https://github.com/lefnire/habitrpg/tree/angularjs-rewrite - though there's nothing to see yet (most is unstaged changes at this point)

**Comment by wizonesolutions** [comment]
Sounds exciting! Is the process to run that branch locally still the same?
(Does running locally work?)

**Comment by lefnire** [comment]
@yangit's jumping in too. This is getting pretty serious, and will catalyze a better API for mobile syncing, including conflict resolution - so I think this is good to do in tandem with the mobile app. Angular, here we come!

**Comment by yangit** [comment]
Added readme.md
You can follow manual and run locally now.

**Comment by switz** [comment]
Just to push a reason why we might not want to move off of derby: Operational Transformation.

**Comment by lefnire** [comment]
OT is super handy for complex multi-user editing (gdocs, etc). In our case, there won't be any users competing for data changes. There will, however, but one user logged into many apps with potentially conflicting message. 

We're currently thinking of a very simple OT implementation, specific to the Habit schema, so that mobile, extensions, & web app can all send operations without clobbering each other. This will be required **anyway** for the mobile app not to clobber the web app's data, since we can't use Racer's OT with batch operations from the mobile app. So if we're gonna build it anyway, we can use it in the website. I'll ping you on G+ soon and we'll chat about it.

**Comment by ghost** [comment]
Perhaps also relevant to this is http://www.breezejs.com/

Perhaps not yet for HabitRPG in its current state but may have some functionality that proves useful

**Comment by Shaners** [comment]
I support the move to AngularJS because of this on their main page: "Write less code, go have beer sooner."

**Comment by yangit** [comment]
http://stackoverflow.com/questions/9682092/databinding-in-angularjs#answer-9693933
Here is a good explanation for all that odd bugs we were getting in the core of Derby.
To tackle current issues we have to reconsider a lot about how and when all those events handled. And we have to rewrite plenty of code anyway to manage racing conditions when a few events try to set same object while being out of sync.

**Comment by katowulf** [comment]
What's the status of the Angular.js migration? Already in progress? Still in planning? Could I be involved in the hangouts?

**Comment by lefnire** [comment]
see http://habitrpg.tumblr.com/post/51476277225/upcoming-features-bugs-update-user-survey , we're going to give the latest Derby 0.5 version a shot first - then if that still fails, fallback on Angular migration

**Comment by yangit** [comment]
I was doing it.
Now I'm doing habit-mobile.
Ping me if you have questions about it.

**Comment by lefnire** [comment]
As per my comment above. Derby 0.5 failed, Angular migration fallback commencing.

**Comment by caycefischer** [comment]
http://www.youtube.com/watch?v=WChTqYlDjtI

**Comment by yangit** [comment]
Tyler, I'm sorry not to be involved in this project. But want to throw some ideas.
API the way how it works on mobile is very easy to work with and does not leave any ambiguity on how to sync data (at any given moment only server has latest update).
The only thing which is not implemented is the way for server to push updated model to the client. That can be done via sockets. But it is not something crucial since we get latest update on each page refresh/action anyway.

I can only see one drawback here: After user clicked on the button we have to show him changes in the UI ASAP. And we need to get an updated model from server (since only server is eligible to apply persistent changes to model). So to make UI smooth we can apply local, non persistent changes which will be only be shown for 0.5-1 sec.
That code adds a little bit to complexity of the app.
What is good: any failure to make it properly or even to make it at all will only affect smoothness of UI. Not integrity of the data.

Another concern is that if we send full user object on every user action. For quick successive actions it might be a lot. But transformations/actions a queued and we only send them in batches, which means we only get one model update for no matter how many actions.
Batches are dispatched immediately _if there is no other batch being synced right now_.
So for one action we still get instant update.

**Comment by lefnire** [comment]
Thanks for the info Yan, I'll refer back to this soon as I start fiddling
with sync

**Comment by katowulf** [comment]
I would highly suggest utilizing [Firebase](http://www.firebase.com) to push updates to client. Scalable, lightning fast, and no server component needed for almost everything you do. Firebase offers an [angularFire](http://katowulf.thoughtbin.org/angularFire.js) lib that can sync clients with only a few lines of code.

I've recently started working part time for Firebase because I think it's such a game-changing product. I started as a consumer building my own apps. I think some of their offerings could really reduce your work load and server stack.

**Comment by lefnire** [comment]
I've had my eye on firebase for a very long time. I 100% plan to use that when building my next product.

Unfortunately I don't think it's gonna work well with Habit. We already have a database (which is a barrier), and since we bootstrapped on Derby it uses some unconventional mechanisms (like using UUIDs for `_id` instead of `Object_Id`s), and which also conforms to our API. So I think figuring out an effective import-to-Firebase approach might prove quite difficult. I do plan to sit down with it some weekend and see what it would entail, but my _initial_ hunch is "big barrier".

**Comment by katowulf** [comment]
Let me know how I can help. I'd be happy to work with you on either Angular.js or Firebase-related design issues as time permits.  katowulf at the gmail. We can skype any time.

**Comment by lefnire** [comment]
Actually, it might be good to just chat with you and pick your brain on
fire bass. maybe there is a feasibility that I'm completely missing having
not been well acquainted with the framework. I'll ping back soon

**Comment by lefnire** [comment]
A for effort, auto correct :-)

**Comment by katowulf** [comment]
[Curse you auto correct!](http://www.damnyouautocorrect.com/)

**Comment by lefnire** [comment]
Say it! say the D word!
