### ISSUE TITLE
Markdown in task-edit modal no longer works.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#8411]
![image](https://cloud.githubusercontent.com/assets/5641207/21959009/bc097c86-da6f-11e6-9ec7-4065cccd444e.png)

vs

![image](https://cloud.githubusercontent.com/assets/5641207/21959010/c5c01b54-da6f-11e6-84ae-b4e808a6c3a2.png)

**Comment by Alys** [comment]
Confirmed, thanks @khipkin!

For anyone who works on this:

We do want markdown and emoji to be enabled in the display of the title (i.e., in the part of that screenshot that appears between the "Save & Close" button and the "Add Checklist" button). The reason for having the title there is to allow you to review what it will look like before saving the task.

This should be a fairly simple matter of calling the standard markdown/emoji parsing routine for that piece of text.

We do not want markdown and emoji to be enabled in the "Title" edit field (i.e., the white field under the "Add Checklist" button is correct in the above screenshot).

**Comment by declanramsay** [comment]
I'd like to fix this.

**Comment by Alys** [comment]
@thelucideffect Thank you!
