### ISSUE TITLE
Some translation files are not pulled from Transifex (supposedly the ones uploaded there manually)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8415]
@paglias a report from a translator and your recent commit made me notice that translations of some files are not pulled from Transifex - supposedly the ones I used to test if it's possible to upload files to Transifex manually (my email from 11/26/26).

The files are:
- merch.json - added with https://github.com/HabitRPG/habitica/commit/fd7aedbff2ddf579e287900f7cacbf128a69d24f
- loginIncentives.json
- overview.json

I'm really sorry for interfering into this proccess. Could you please adjust the scripts used to pull the files to include the ones mentioned.

**Comment by paglias** [comment]
@GitHubSphinx thanks for the heads up, I've added them to my script, feel free to reach out whenever you see something is missing https://github.com/HabitRPG/habitica/commit/cddd0df4f2b08017b07e0ef2e3c1e3ef51a9c468
