### ISSUE TITLE
iPad login always fails first time

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#842]
When I login into beta or prod on my iPad using bobbyroberts99, it always kicks me back to Anonymous player as I'm trying to type in my password. I have to click "Register/Login" and on the 2nd try it allows me to finish typing my password and logs me in successfully.

Not a big deal, but it has happened several times and a search didn't find this issue so I thought that I'd mention it.

**Comment by lefnire** [comment]
try clearing cookies / cache "for all time" for habitrpg - lotta people experiencing this issue as a result of corrupt session storage.

**Comment by bobbyroberts99** [comment]
I deleted cookies and cleared history on my iPad (don't see "Clear Cache"). Still having the same problem.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
