### ISSUE TITLE
Searing Brightness affects challenge tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8423]
Skills are not meant to adjust the value of challenge tasks but when a Healer casts Searing Brightness, all their tasks are made less red, including challenge tasks.

The desired behaviour is that challenge tasks should not be affected by Searing Brightness.

**Comment by lynxlynxlynx** [comment]
I'll take a look.

**Comment by paglias** [comment]
@Alys is this a client side only effect or it's persisted to the database?

**Comment by Alys** [comment]
This is server-side. It persists to the database.

It's actually not client-side immediately. As soon as you click the Searing Brightness skill, your non-challenge tasks change colour but your challenge tasks don't. After a sync, your challenge tasks change colour too.

**Comment by lynxlynxlynx** [comment]
The bug is even worse, as it affects also other code (rebirth, reset, fortify).
