### ISSUE TITLE
"How to Report an Issue" issue needs updating ("Memorable" tag changed to "type: memorable")

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#8431]
Issue #2760 has a link to the "most common issues", which is all those tagged as "Memorable". This tag doesn't exist any more – it's been replaced by "type: memorable" – so the issue needs to be updated to link to the correct tag. [This](https://github.com/HabitRPG/habitica/issues?utf8=%E2%9C%93&q=label%3A%22type%3A%20memorable%22%20) is the search it should link to.

Alternatively, the contents of that issue could be moved into .github/CONTRIBUTING.md, so that anyone can submit a pull request if it needs updating rather than an admin having to do the work. I'm happy to make a pull request for that if that's a good idea?

**Comment by Alys** [comment]
@anowlcalledjosh Thanks very much for pointing that out! I've updated the link in that issue and also made some other changes that I've been meaning to for a while.

We'll keep it as an issue. It's rare that we need to make changes and when we do, it's faster for us to modify it by editing the issue than by doing a commit or by describing what needs to be changed to a contributor. Thank you for the offer though!
