### ISSUE TITLE
Check-in Incentives progress bar inconsistency

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8432]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

When you're in a stretch of Check-in Incentives that reward every 5 days, you'll first see "Progress until next 1/5" on the Profile page, then 2/5 and so on. Once you hit 5 and earn a reward, it'll show "Progress until next 5/10". The next day it'll be 1/5 again.

Reward days should probably show 0/5 instead of 5/10, for a sensible progression.

**Comment by TheHollidayInn** [comment]
This is the way I original displayed it, but was asked to change.

**Comment by SabreCat** [comment]
That's really odd. I understand why dropping to 0 could be off-putting, but having it be out of 10 one day and out of 5 the next is at least as puzzling as that.

**Comment by eastwood** [comment]
I'm happy to fix this for the team. Let me know if this is okay!

**Comment by SabreCat** [comment]
@eastwood: Go for it, with our thanks! Let us know if you need any help as you go.

**Comment by eastwood** [comment]
PR should be done pending review :)

**Comment by librarianmage** [comment]
The issue has been fixed; should this Issue be closed?
