### ISSUE TITLE
"Quest started" system message should use backticks.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#8445]
The quest-started message (added in #8107) is not wrapped in backticks, so it stands out from the other system messages:

![image](https://cloud.githubusercontent.com/assets/5641207/22169171/06f55024-df27-11e6-89db-e1cac1d16dc8.png)

**Comment by lynxlynxlynx** [comment]
While it looks odd, wouldn't the reverse be better? The way system messages/code tags are styled is just horrible imho. There was some discussion about this somewhere already, maybe #3553.

**Comment by Alys** [comment]
For now, we should keep consistency with the existing system messages. We're working on some improvements to the website's front-end and we can improve how they look as part of that. Good point though - there's definitely room for improvement in their appearance.

**Comment by lynxlynxlynx** [comment]
On a related note, the navbar notification you now get for it is without text. In other words, just the mini chat icon is displayed once you click to get the notification list.

**Comment by lynxlynxlynx** [comment]
On a related note, the navbar notification you now get for it is without text. In other words, just the mini chat icon is displayed once you click to get the notification list, instead of also the party name. Did anyone else see it?

**Comment by khipkin** [comment]
@lynxlynxlynx I've seen that once or twice, but I didn't notice when it happened.

Edit: the issue for the weird blank party notification is #8207.

**Comment by maximumtiu** [comment]
Hi, I'd like to take this one!

**Comment by SabreCat** [comment]
@megantiu Great, go for it! Let us know if you run into any difficulty.
