### ISSUE TITLE
Group members list not adjusting

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#845]
![21-Apr-13](https://f.cloud.github.com/assets/3129563/407031/d219368e-aad4-11e2-8045-11b370245d38.png)

After a member left he spot remains empty. Instead it should be made so that the remaining group members shift one spot to the left.

**Comment by lefnire** [comment]
fixed, will go out with next push (it's actually an invisible you, not your other party member - weird query subscription thing)
