### ISSUE TITLE
Subtask checkboxes not displayed on mobile

### ISSUE THREAD

**Issue by artemisclyde** [HabitRPG/habitica#8459]
As you can see in the image below, checkboxes are not displayed at my daily subtask. I can still click them and the tick will appear, but the boxes are missing.

**Device information:**
Phone: One Plus X
Android Version: 6.0.1
Habitica Version: 0.0.36 (148)

![photo_2017-01-27_19-07-42](https://cloud.githubusercontent.com/assets/16636453/22381994/1f497f2c-e4c4-11e6-8de2-633ad46578dd.jpg)

**Comment by paglias** [comment]
@artemisclyde this should be reported in the android repo https://github.com/HabitRPG/habitica-android
