### ISSUE TITLE
Desktop notifications nagging in unsupported browser

### ISSUE THREAD

**Issue by youve** [HabitRPG/habitica#8464]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 52d07da52d07da8-722d-499e-896e-837b5a47309f8-722d-499e-896e-837b5a47309f
  * Browser: Conkeror
  * OS: Arch Linux 4.9.6-1  x86_64
  * UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 conkeror/1.0.3

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
I use [Conkeror](http://www.conkeror.org), which is a minimalist browser, and desktop notifications are not supported except in the sense that the browser is Mozilla-based and I could extend it to add that functionality if I wanted to (but I don't). 

Every time I enter my party, it nags me to turn the desktop notifications on, and there's no button to say "No thank you". There's only a button to say "okay". I would like it to have buttons [No], [Bug me later], [Okay] so that I can stop being nagged to enable something that my browser doesn't support and that I would disable if it did.

In the Report a Bug guild, they said that it should recognise that my browser doesn't support it like it does for IE, but I think there's no way to definitively do that with user-agent checking for browser's like mine where the underlying framework is there that a person could theoretically have written an extension for but nobody has. Rather than adding exceptions for little browsers like conkeror, it would be better if there was a button I could push to let it know I don't want desktop notifications, whether my browser supports them or not.

Thanks

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by paglias** [comment]
@youve to check that the browser supports notifications we don't use the user agent but 
```
 if ('Notification' in window && window.Notification.permission === 'default') {
```

and it correctly returns false if `window.Notification` doesn't exist meaning that the Notification service isn't supported by the browser. And it's the suggested method to check for notification support by [MDN](https://developer.mozilla.org/it/docs/Web/API/notifiche) and across the web.

If we're missing something please let us know but otherwise I don't think there's much that we can do

**Comment by youve** [comment]
Hey, thanks for your help. What I was hoping for was that you would add something like this to the dialog:

![buttons](http://i.imgur.com/t5zGpkg.png)

I still think you should do that.

But you gave me the words I needed to fix the problem for myself -- googling "window.Notification.permission" was enough to help me figure out some other things to search for to find what I needed. I had to add about 50 lines of javascript to my rc file, but I was able to copy them from [these codesnippets](https://codegists.com/snippet/javascript/conkerorrcjs_webframp_javascript). Previously I hadn't been able to find something when I was searching -- this has been bothering me since at least July but I never really managed to make the time for fixing it beyond googling a bit here and there and noticing it would take more time to solve than I had available.

**Comment by paglias** [comment]
@youve glad you managed to get it working but I don't think we should implement the change. We respect the way the Notification is supposed to work and your problem seems to be due to some incorrect implementation at the browser level
