### ISSUE TITLE
Arrange Magic Potion pets in seasonal order

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8465]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

At the moment, pets and mounts hatched via Magic Hatching Potions are listed in the order they were introduced to the site. This comes out a bit awkward, with seasonally related pets widely separated from their peers, and the year-round Royal Purple pets at an arbitrary spot toward the bottom.

We should arrange these in seasonal order, starting with either Winter or Spring. The Royal Purple pets can go either at the top or bottom of the list (I can see pros/cons to both). All it should take is rearranging the order the potions are defined in `website/common/script/content/hatching-potions.js`.

**Comment by willira2** [comment]
Hi, mind if I take this one?

**Comment by SabreCat** [comment]
Go for it!

**Comment by TheHollidayInn** [comment]
We should consider how we will order these if we move content to the DB.

**Comment by khipkin** [comment]
@TheHollidayInn Maybe assign months/seasons to each potion and group based on that, then sort based on the year it was first added to the game?

**Comment by TheHollidayInn** [comment]
Exactly!

**Comment by rakesh-tirupathi** [comment]
Hi ! I am new to this And would love to contribute here. Can someone guide me on how to get started. Thanks.

**Comment by khipkin** [comment]
@rakesh-tirupathi This issue is already in progress by another contributor. However, are other issues ready for someone to take on! I suggest looking at issues labeled with ["Help Welcome Now"](https://github.com/HabitRPG/habitica/labels/status%3A%20issue%3A%20help%20welcome%20now)
