### ISSUE TITLE
"Freeze account" did not work

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#847]
I used the "freeze" option in the settings on Wednesday night, but I got a hefty health penalty when I returned to Habit today - seems like it did not work...

**Comment by lefnire** [comment]
Hm.... it works for me, as I've been traveling and logging in quite often
without losing HP. Wildcate you seem to experience many of the tickets,
what OS / browser do you use? Could you send me your user id?

**Comment by wildcate** [comment]
@lefnire I'm using Win7 with Firefox.
I toggled the "freeze" off and on again yesterday, and now it seems to work. Weird. Anyway, I'll send you my user ID per email so you can have a look at the ticket-magnet that's me ;)

**Comment by switz** [comment]
If you find that it's not working again paste this in your url bar before touching anything else:

```
javascript:alert(window.DERBY.app.model.get('_user.flags.rest'))
```

Chrome might remove the `javascript:` prefix, just type it back in. It should open an alert window with `true` if you have freeze enabled.
