### ISSUE TITLE
Challenge tag edit field appears when editing a saved challenge

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8472]
When editing a challenge that was created in the past, there's a field for editing the tag. That field should be removed because it is not permitted for the challenge owner to edit the tag after the challenge has been created.

We should also put a message on the challenge creation form to explain that the tag can't be edited after the challenge is saved. It should probably go just before the "More Info" tool tip link. It's important that the message also appears on the form you see just after you clone the challenge (it's almost certainly the same form but whoever adds this message should test that).

The API shouldn't need to be changed because it already prohibits changes to tags when editing challenges.

No change should be made to the form for creating a challenge because it's correct for the challenge owner to add a tag then.

_FYI we prohibit editing a tag in pre-existing challenge because tags are for the benefit of challenge participants. It would be confusing if the tag changed after a participant had joined the challenge._

**Comment by Alys** [comment]
We should also put a message on the challenge creation form to explain that the tag can't be edited after the challenge is saved. It should probably go just before the "More Info" tool tip link. It's important that the message also appears on the form you see just after you clone the challenge (it's almost certainly the same form but whoever adds this message should test that).

I'm editing the top post to insert this new paragraph.

**Comment by vincecampanale** [comment]
I'll take this one!

**Comment by librarianmage** [comment]
@vincecampanale Are you still working on this?

**Comment by vincecampanale** [comment]
Nope, all yours!

**Comment by lemoness** [comment]
Is this still happening, actually?

**Comment by librarianmage** [comment]
Just tested it, and yes, the "Short Name" field appears to be editable when
editing challenges, though it doesn't actually change when submitted.

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by TheHollidayInn** [comment]
I believe this is fixed here: https://github.com/HabitRPG/habitica/pull/9412

**Comment by librarianmage** [comment]
Yes, it was. Thanks for noticing!

**Comment by Alys** [comment]
I'm reopening this because the issue is happening again (the challenge edit form makes it look like you can edit the tag). Thanks to Texas Toland for reporting the bug and to citrusella for finding this old issue for us. :)
