### ISSUE TITLE
Task edit screen changes: move Dailies repeats out of Advanced Options; enlarge Notes; reduce spacings

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8474]
Following on from issue https://github.com/HabitRPG/habitica/issues/8307 "New Edit functions requires more scrolling on smaller screens" and from PR https://github.com/HabitRPG/habitica/pull/8456 "Added double columns to edit modal", there are some more changes we can make to the task edit screens:

For reference for the current edit modal, see the screenshot below.

- Give the task title near the top of the modal a smaller font size (maybe roughly halfway inbetween its current size and the size of the other text on the modal).
- For Dailies, move all of the Repeat options out of Advanced Options and into the standard options on the left-hand side. I.e., move the "Repeat" header and its dropdown menu; delete the redundant "Repeat Every" header and its fields. Test that change for both of the "Repeat Every" options.
- Increase the height of the Extra Notes field so that you can see one or two extra lines of text in it (i.e., see four or five lines in total without needing to scroll inside the box).
- Reduce vertical padding where possible. E.g., the amount of space that you can see above the Difficulty fields in the screenshot is too much. The space above Title and Tags is probably too much too (but if you make changes there, check what it looks like with and without a checklist). Space at the bottom of the modal (around the Save and Close buttons) can probably be reduced too.
- Remove the full-width vertical line above the bottom Save and Close buttons.
- Maybe remove the full-width vertical line below the checklist (but see what it looks like both with and without a checklist).

These changes will need to be tested for all four task types (includes Rewards) for:
- normal user tasks
- challenge tasks in the challenge edit screen
- Group Plans tasks in the Groups Tasks List screen (tell us if you don't know how to test there locally)

![image](https://cloud.githubusercontent.com/assets/1495809/22615747/803c73ba-eae7-11e6-81fb-a5aa5dcac974.png)

**Comment by marceloneil** [comment]
I made a couple edits, do you have any feedback @Alys?

![screenshot from 2017-02-05 16-43-42](https://cloud.githubusercontent.com/assets/6353492/22630158/65e52d46-ebc2-11e6-9b3c-73dd8e3d3ac6.png)

**Comment by Alys** [comment]
@marceloneil I like that! It looks good! Feel free to make a PR. Thanks!

**Comment by mandyzhou** [comment]
Given the new Repeatables feature, the edit screen for Dailies looks a little unbalanced and requires a lot of scrolling on smaller screens. Is there any way some elements could be moved/adjusted so that the edit screen is a bit more user-friendly on smaller screens? Maybe collapse some of the repeatables-related options/information by default?

**Comment by Alys** [comment]
@mandyzhou You're right that it's unbalanced and it would be nicer if neatened, but the staff developers are a good way through a project to make several improvements to the website's code, and so I think it's worth waiting for that to be done. Any changes made now would need to be redone later, or would already have been handled as part of the project.
