### ISSUE TITLE
Check-in Incentives popup should have an opt-out option

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8478]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Most repetitious pop-ups (like Level Up and Streak Achievement modals) have an option in site settings, mirrored on the popup itself, to disable them. This is not the case for Check-in Incentive notifications, however, which has proven to be a nuisance to users who aren't particularly interested in or motivated by those incentives. We should add another entry to the list of "Don't show popup" checkboxes at /#/options/settings/settings to disable the incentives modal.

**Comment by librarianmage** [comment]
Is this in progress?

**Comment by lemoness** [comment]
@SabreCat What's the status on this?

**Comment by SabreCat** [comment]
Ah, looks like the PR got abandoned but the status on the ticket wasn't changed. Updated!

**Comment by lemoness** [comment]
We're revamping how the modals are presented, so I'm closing this ticket for now.
