### ISSUE TITLE
Edited Tasks and Dailies not saving.

### ISSUE THREAD

**Issue by heyimzsa** [HabitRPG/habitica#848]
Today, I wanted to refine some of my tasks. I consolidated a few and changed titles, difficulty levels, and adding information into the text boxes. I walked away from my computer for about 30 minutes with the chrome browser open Habitrpg and when I came back all my changes disappeared 

I tried searching for a similar bug but nothing came up in the search. So my apologies if something similar has been said.

**Comment by wc8** [comment]
I do a page refresh a few seconds after my last change to make sure it was saved to the server.

**Comment by heyimzsa** [comment]
I just tried this and the changes stuck this time. Thanks
—
