### ISSUE TITLE
Timeouts in Amazon Payments test

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8482]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

In 50% or so of Travis CI builds, the integration test `payments : amazon #subscribeCancel success cancels a user subscription:` fails with `Error: timeout of 8000ms exceeded. Ensure the done() callback is being called in this test.` This makes it difficult to tell at a glance whether a given commit or PR is building clean. Given that each run of the API tests takes 15-20 minutes to complete, this issue can substantially delay the deploy process as we repeatedly restart the job hoping for a successful coin toss.

There must be some race condition in the cancel subscription process, or possibly a mishandled promise or callback. Time to hunt it down!

**Comment by paglias** [comment]
New test with similar timeouts

> payments : paypal #checkout success creates a purchase link:
