### ISSUE TITLE
API Issue: release of pets/mounts can give undue achievements

### ISSUE THREAD

**Issue by madpink** [HabitRPG/habitica#8497]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID:  b0413351-405f-416f-8787-947ec1c85199

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
Sending release to pets, mounts or both returns a success and grants achievements regardless of whether the user earned it. That is, even if the user has gotten 0 pets, the call will return a success and give the "Beast Master" achievement.

Sending "release-both" will give the user all 3 achievements regardless of how many pets and or mounts they've gotten.

**Comment by rakesh-tirupathi** [comment]
Hi guys! I would like to contribute to this. I am new to this, could any one please suggest how to get started and what needs to be done.
Thanks.

**Comment by Alys** [comment]
@rakesh-tirupathi Thank you!

Have a look at http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths for an introduction to coding for the website. It links off to a Setting Up Habitica Locally page which will help you create a local install for development and testing.  Post to the Blacksmith's guild if you need help (the wiki pages contain links).

After that it's just a matter of finding the code that releases the pets and mounts (https://habitica.com/apidoc/ will show you the command that's used and you can grep for that command in the code base) and then working out how the code needs to be changed. Let us know when you've got the local install working and are ready to start fixing this issue and then we'll change the issue's label to in progress.

**Comment by jerell-mendoza** [comment]
Hi @Alys, I've gotten the local instance set up and running after following the guide. Can I contribute to this issue? It'll be my first!

**Comment by Alys** [comment]
@rakesh-tirupathi Have you made a start on any code for this? If not, that's fine! We understand about real life getting in the way of coding. :) Let us know if you're not working on it yet and if you're not, @jerellmendoodoo can take it over.

**Comment by rakesh-tirupathi** [comment]
I am sorry @Alys, I am having troubles having the environment set up. ya
sure @jerellmendoodoo <https://github.com/jerellmendoodoo> can take over
this issue. I will let you know after setting up the local instance and i
will take up other tasks.

Thank you

**Comment by jerell-mendoza** [comment]
Hi, just as an update, I've fixed the issue and tested it locally through the UI and it appears to be working. Edited the releaseBoth, releaseMounts, releasePets .js files. I've read a bit through the wiki and I see that it's recommended that I write some unit tests regarding this? Is that a good next step?

**Comment by Alys** [comment]
@jerellmendoodoo unit tests would be good, thank you! Comment here if you'd like adviqe about them.

When the code is ready for use (or sooner if you have questions that require us to see it), commit it locally, then push the branch to your fork of the repository in GitHub, and then you'll seea button for making a pull request. Ask again if you need more details. :)

**Comment by jerell-mendoza** [comment]
Hi @Alys, I've created the unit tests and ran them and it's all looking good. I've followed your steps: commit locally, push to branch on my fork, and next I'll go and make the pull request. Thanks for all the help up till now, what happens next?

**Comment by SabreCat** [comment]
Fixed in #8545 .
