### ISSUE TITLE
All daily, habits, to-dos gone.

### ISSUE THREAD

**Issue by samuraipoet** [HabitRPG/habitica#85]
Hellow. I'm a very new user. I just started yesterday. Anyway, like the title says, everything is gone. My HP, EXP and gold seem to be correct, but nothing else is. Reloading the page doesn't help either. I don't know if it's related but I noticed this problem pretty soon after I installed the habitrpg chrome extension.

I'm on a mac, using chrome. if that helps. I've been using the facebook sign-in option. 

BTW, I backed the kickstarter yesterday, and I've loved using this so far. I hope I can continue to use it.

**Comment by lefnire** [comment]
There was pretty massive data corruption issue about 15m ago. Like, really bad :( :( I'm restoring to this morning. This won't happen again, I'm going to spend the next few days implementing a test harness.

**Comment by lefnire** [comment]
I'm sorry everyone :( :( send me your user ids via email and I'll give you bazillion tokens, and disable ads, and.. something, keep you on file for when I create something cool in the app

**Comment by PorkHat** [comment]
What time this morning? Did I lose all my progress? lol If so that's okay, I'm just glad you've made a cool ap and seem really dedicated. Thanks! 

Edit: I think I created my account around 8:00 AM but was tinkering with it all day.

**Comment by lefnire** [comment]
about 11p EST, sorry @PorkHat :( . PS, awesome name!

**Comment by PorkHat** [comment]
No worries, I made some mistakes while tinkering with it in teh first place. I'll still tell people it's a good ap :D

**Comment by lefnire** [comment]
y'all have had a wonderful response :) nobody's sewing me! Thanks for being cool about this guys. Subsequently, any non-trivial heroku pushes on my end will be prefaced by a proper test-suite run, so keeping #84 in mind everyone should be good to go

**Comment by PorkHat** [comment]
How come only some of my habits have progress options? I used my juicer like 4 times today and I clicked it 4 times but no progres bar. Woke up before 8:00 AM has a progress bar and it's only been clicked once. Should I open a new ticket for this?

**Comment by lefnire** [comment]
yeah, open a ticket for it. If it only has 'up', or only has 'down' - no progress bar (figuring out how to best handle that still). only works for items with up _and_ down

**Comment by samuraipoet** [comment]
Thanks Lefnire! I didn't expect a response so quickly. Just wanted to say again, I really do love the app.
