### ISSUE TITLE
User Validation

### ISSUE THREAD

**Issue by kantamablade** [HabitRPG/habitica#8504]
I'm sorry but I'm nowhere near being a techgeek. I can't find another way to report this issue.

On the app itself I'm getting "User Validation Failed" and on the website I'm getting this.
![screenshot 2017-02-22 12 42 20](https://cloud.githubusercontent.com/assets/25962066/23224692/5557a524-f8fd-11e6-9aeb-5f744f5d4b93.png)

**Comment by paglias** [comment]
@kantamablade thanks for the report. Can you post your user id (UUID) so we can investigate? You can find it in the app -> settings -> account details

When did the error started to appear?

**Comment by kantamablade** [comment]
I also get the "not connected to the Internet" error sporadically but that
one doesn't halt my activities like this validation one has. I can't get my
character out of the tavern or really access anything else since I'm not
validated.

The validation error only started a few hours ago but boy has it ever been
vexing.

**Comment by paglias** [comment]
@kantamablade can you try again to refresh the website now? It should be fixed. Let me know if it is not and sorry for the trouble

**Comment by kantamablade** [comment]
It's fixed on both website and app. Thank you kindly for your help! May we
all slay our Dailies and accomplish our glorious tasks of getting cute pets!
