### ISSUE TITLE
end date for cancelled subscription does not obey user's date format preference

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8506]
When a subscription has been cancelled, the end date (`purchased.plan.dateTerminated`) is displayed in the USA date format, instead of in the format chosen by the user at Settings > Site.

For example for user 98089587-1bbe-4de2-92d3-0bbe76513a3f (one of my accounts):

![image](https://cloud.githubusercontent.com/assets/1495809/23235458/4eb9cae0-f9a1-11e6-8944-1f295d4138d6.png)
```
    "purchased": {
        "plan": {
            .....
            "dateTerminated": "2017-03-02T00:00:00.000Z",
            .....
            }
       },
       "preferences": {
        ...
        "dateFormat": "dd/MM/yyyy",
```

**Comment by maximumtiu** [comment]
I've got what I believe to be a fix for this, but I'm having trouble simulating a subscription locally to confirm it. How would I go about doing that?

**Comment by TheHollidayInn** [comment]
You can either set up a test Stripe or Amazon account and edit your config.json or you can just add a subscription to the user via your local mongo db.
