### ISSUE TITLE
CSS spacing on "Purchase Gems" page

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8508]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 25f0d3d9-fab3-4ac3-b09a-fd03a9e9e9fa
  * Browser: Chrome 56.0.2924.87 (64-bit)
  * OS: Windows 10 (64-bit)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

The spacing for amazon, paypal, and use credit card is all screwed up. See attached image. 

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/

TypeError: Cannot read property '-1' of undefined
    at app-7b53cb96.js:49
    at j.$broadcast (app-7b53cb96.js:9)
    at Object.fn (app-7b53cb96.js:51)
    at j.$digest (app-7b53cb96.js:9)
    at a.$apply (app-7b53cb96.js:9)
    at HTMLAnchorElement.<anonymous> (app-7b53cb96.js:10)
    at HTMLAnchorElement.dispatch (app-7b53cb96.js:4)
    at HTMLAnchorElement.r.handle (app-7b53cb96.js:4)
(anonymous) @ app-7b53cb96.js:8

![rpg](https://cloud.githubusercontent.com/assets/22421733/23276416/cc3375ce-f9cf-11e6-8bed-4806baa118f8.png)

**Comment by eyelesbarrow** [comment]
Hi can I give this a try?

**Comment by Alys** [comment]
@eyelesbarrow Sure! Thank you! Comment here if you have questions or run into trouble.

**Comment by eyelesbarrow** [comment]
Hi I think I know how to do this. But I am having problems on locating this code as I am new to github. Any hints on where it is so I can do a PR? 
Thanks!

**Comment by ghost** [comment]
habitica<https://github.com/HabitRPG/habitica>/website<https://github.com/HabitRPG/habitica/tree/develop/website>/views<https://github.com/HabitRPG/habitica/tree/develop/website/views>/static/

________________________________

**Comment by Alys** [comment]
@eyelesbarrow A useful tip to finding the right code is to look for some unique text on the page near where you want to work. For this case, it might be "Subscribe using" or "Enter Coupon Code". You can use `git grep` to search in the repository for that (first `cd` to the top level directory of the repository - the directory that contains the `config.json` file):

`git grep "Subscribe using"`

In this case, that will show you the `locales` strings that are used for translations. For example:
`website/common/locales/en/settings.json:128:    "subscribeUsing": "Subscribe using",`

You can then do another search for the locales key (`subscribeUsing` from that example), and that will show you the actual code that uses that piece of text:

`git grep "subscribeUsing"`

Ignore all the locales strings that appear again. :) The code that you want to modify is probably near the code that you've found, or at least will give you further pointers to the right place.

**Comment by eyelesbarrow** [comment]
Hi @Alys thanks very much, you've been very helpful. I'm afraid what I have done is very simple right now and I do not think it is right yet (just an alignment). I'd like to continue working on this, if that's OK.

**Comment by Alys** [comment]
@eyelesbarrow Sure! That would be fine!

**Comment by TheHollidayInn** [comment]
@eyelesbarrow How is your progress on this issue? Do you need any direction?

**Comment by Alys** [comment]
@eyelesbarrow I'm closing this because we're most of the way through a project to change the website's front-end code and it's very likely that this issue will no longer happen afterwards. If it does, there'll be different code that will need to be modified to fix it, and we can reopen this then.
