### ISSUE TITLE
Fix Character Values allows values less than 1

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8512]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: e8277c2b-d1a0-47f8-9a08-31211ee578c8
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

The "Fix Character Values" feature on the Site page disallows decimal values for Level, which is correct, but it still allows you to fill in 0 or a negative number. Levels below 1 are not supported and could cause unexpected behavior with other features related to game statistics.

![image](https://cloud.githubusercontent.com/assets/4501321/23313664/43ee0ad4-fa84-11e6-92e0-b0b74bd6b28b.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None

**Comment by cailinglu** [comment]
If it's alright, I'll work on this one :)

**Comment by Alys** [comment]
@caillu Thanks, please do! Comment here if you have questions or run into trouble.
