### ISSUE TITLE
Exported data were messy code

### ISSUE THREAD

**Issue by Taotao120** [HabitRPG/habitica#8515]
Description
I exported my data earlier and found out the tasks were messy code, which were surposed to be Chinese.
![one](https://cloud.githubusercontent.com/assets/26052063/23355231/c37f1bca-fd0f-11e6-8564-0aa1a616e8dc.png)

General Info
  * UUID: 765630ed-09f1-4606-b6f9-d99c70a0ef10
  * Browser: Firefox
  * OS: Windows 10

**Comment by Alys** [comment]
@Taotao120 Could you please show us what your Habits look like in Habitica, if they aren't things that you want to keep private? We'd need just a screenshot of the Habits column, showing the task titles.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
@Taotao120 I'm closing this now but if you'd like more help, see the question from my previous post, and let us know if there's any other information you can give us. We'll still see your reply and can reopen this if necessary.

@MathWhiz Thanks!
