### ISSUE TITLE
Collecting multiple quest items for the same task

### ISSUE THREAD

**Issue by mohit-surana** [HabitRPG/habitica#8519]
General Info:
  * UUID: ca2a5138-d9d2-49ba-a882-f45581dff5cf 
  * Browser: Chrome Version 55.0.2883.95 (64-bit)
  * OS: macOS 10.12.3 (Sierra)

Description:
Quests that involve collecting quest items (eg. soaps in Attack of the Mundane, Part 1: Dish Disaster!) are not affected by drop caps(and they should not be).

But if you check off a Todo or a Daily -> Uncheck the same -> Recheck the task

Expected Behaviour:
+ Gold, XP, Quest item (with a chance)
- Gold, XP, Lose quest item had you gotten it
+ Gold, XP, Quest item (with a chance)
Top right corner should show 1 item collected.

Actual Behaviour:
+ Gold, XP, Quest item (with a chance)
- Gold, XP
+ Gold, XP, Another quest item (with a chance)
Top right corner shows 1 item but if you refresh, you see 2 items collected.

Yesterday, even though I got 6-7 quest items properly, the following method let me get 12 quest items.
I figured out a hack to max out my drop cap (don't curse me). Repeat check uncheck to max out drop cap for the day.
My logic: I'm not cheating on my tasks/dailies but just increasing the rate of item drops :P So it must be legit. But this should not work against quests.

Console Errors: Not applicable

**Comment by Alys** [comment]
Thank you for telling us but please see https://github.com/HabitRPG/habitica/issues/4626 in particular the first comment from me which explains this behaviour and why it's currently permitted.

We have a guild within Habitica for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. When you find a bug, you can start reporting it by putting a brief message there - just enough to explain the problem. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, a moderator would advise you of that.
