### ISSUE TITLE
Challenges filter shows only groups you are a member of - can't see joined challenges of guilds / parties you aren't in

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8520]
On the [Challenges](https://habitica.com/#/options/groups/challenges) page, the "Groups" list should show all the groups that you are a member of (that part is working) AND **it should show all the groups that you are not a member of but that contain challenges you are participating in** (that part is no longer working, although it used to; I do not know when it stopped working).

If showing the names of groups you are not a member of is too difficult or unreliable or slow, it would be good enough to show a generic item in the "Groups" list called something like "other groups" which, when ticked, would show challenges from groups that you aren't a member of. In fact, that might actually be better from the user's perspective - I'd be interested in other people's opinions about this. The player could still see which guild each challenge was in by viewing the challenge itself.

When the player first arrives at the Challenges page, all groups should be ticked by default (including the "other groups" item if we go with that idea).

The "All" and "None" buttons at the top of the filter box should tick / untick all of the group checkboxes (including the "other groups" box, if used). Note that we used to have a bug https://github.com/HabitRPG/habitica/issues/7763 that prevented the "All" button from ticking the checkboxes of groups you weren't a member of - we don't want that bug to return.

**Comment by rhdsmnd** [comment]
This seems to be working for me (Mozilla v51.0.1 on Windows 10).  Is there a specific platform/browser combination for which it's not working?

**Comment by Alys** [comment]
That's weird: it's working for me too now. I'm sure it wasn't the other day. It won't be a platform/browser thing. Maybe there's a certain circumstance in which it doesn't work?? Anyway, I'm sorry for wasting your time @rhdsmnd ! I'm closing this. If I can replicate the problem I'll reopen it.
