### ISSUE TITLE
I recieved 4 Zombie Hatching Potions instead of one for completing a Todo Task

### ISSUE THREAD

**Issue by Chillchamp** [HabitRPG/habitica#853]

**Comment by switz** [comment]
Hmm. This is going to be difficult to reproduce. Can you give us any more info? What you were doing before that, how long since your last refresh, and so on.

**Comment by Chillchamp** [comment]
I remember that I was marking 2 TODO tasks as done one shortly after another and also recieved a wolf egg. But not more... Hope that helps :)

**Comment by switz** [comment]
Thanks for the info. Seems to be an isolated incident. Let us know if it happens again.
