### ISSUE TITLE
Challenges that are expired that I can't delete!

### ISSUE THREAD

**Issue by junipernova** [HabitRPG/habitica#8532]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
A challenge I joined in December, a job hunting one, I want to delete since I got a job! I can't delete the tasks and dailies off my lists. The challenge link icon goes to nothing, there is no trash can icon to delete it, and when I try to delete it in the mobile app, I get the message "Network error" or something similar, can't remember the exact wording!

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Please see "Deleting a Challenge Task" on the wiki's [Challenges](http://habitica.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) page. There's a series of steps to try; step 7 will bring you to the Report a Bug guild if none of the others help.

That guild is the best place to report any problem. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.
