### ISSUE TITLE
Daily tasks do not become checked in web interface when updated via the API

### ISSUE THREAD

**Issue by pjf** [HabitRPG/habitica#854]
What happens:

When checking a daily task off via the API, the gold and XP rewards will appear immediately in the web interface, but the item does _not_ appear checked off.  (When the page is reloaded, it appears checked off fine.)

What should happen:

Tasks should appear checked off when they're changed by any means.

**Comment by switz** [comment]
Hm, I believe we stopped using subscriptions due to their costly nature. @lefnire any ideas?

**Comment by lefnire** [comment]
Stopped using subscriptions in what way?  Strange actually, this should be
working. See the scoreTask function of api.coffee:

```
# Set completed if type is daily or todo

existingTask.set 'completed', (direction is 'up') if /^(daily|todo)$/.test

existingTask.get('type')
```

could it be the regex test is failing? My first impression was that we are
setting the task object wholesale, which breaks nested object property
listeners in the view and requires a refresh or view.render(). However, we
are indeed setting the individual property with
existingTask.set('completed',...) so this should be working fine

**Comment by switz** [comment]
The test definitely passes because it is checked on refresh. Still no idea why the view binding isn't updating itself. Maybe changes that @zakkain made in the redesign?

**Comment by caycefischer** [comment]
Hmmm shouldn't be, I haven't changed anything in that part of the app's mechanics, as far as I know

**Comment by uvwxy** [comment]
When I tick a daily with my (unofficial ;)) android client, the box is not ticked in the browser. The streak counter appeared though.

It seems to me it's not updating everything ui-wise as it should.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
