### ISSUE TITLE
When editing a Challenge, tasks save instantly instead of awaiting Save

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8540]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

When you open a Challenge for editing, there are "Save" and "Cancel" buttons at the top, suggesting you've begun an editing session that will be finalized or rejected upon clicking one of those two. However, that appears only to apply to the miscellaneous fields at the top of the Challenge (description and so on)--if you manipulate the challenge tasks at all, those changes propagate instantly.

This was some embarrassment to me when I accidentally added a nonsense Habit to an official Habitica x Take This challenge, syncing it out to all ~4000 participants despite my attempting to cancel the action. :\

**Comment by Alys** [comment]
I've marked this as entry level coding because the easiest "fix" is to just as a sentence of explanation to the form, however feel free to override me and change it and make other suggestions!

I think changing the actual behaviour would be nightmare level coding. :)

**Comment by Alys** [comment]
I think changing the actual behaviour would be nightmare level coding. :)

**Comment by librarianmage** [comment]
Would the warning be best placed by [the Save/Cancel](https://github.com/HabitRPG/habitica/blob/develop/website/views/options/social/challenges.jade#L40) buttons?

**Comment by Alys** [comment]
@MathWhiz Yeah, I think that would work. Give it a try if you wish. Just wait a day or so to see if SabreCat disagrees with my assessment of the issue. :)

**Comment by librarianmage** [comment]
@Alys Oh, I wasn't planning on completing this, I was hoping to clarify

**Comment by teqnickels** [comment]
@Alys, I'd like to take this if it's ok.

**Comment by Alys** [comment]
@teqnickels Thank you! Comment here if you have questions or problems.

**Comment by teqnickels** [comment]
@Alys, I have a question regarding the description of the problem. _"However, that appears only to apply to the miscellaneous fields at the top of the Challenge (description and so on)--if you manipulate the challenge tasks at all, those changes propagate instantly."_

Is this in reference to editing items added to "habits", "dailies" or "to-dos"?

**Comment by SabreCat** [comment]
@teqnickels: That's correct! If anything's changed in the Habits, Dailies, To-Dos, or Rewards, those changes cannot be canceled via the Cancel button.

**Comment by teqnickels** [comment]
@SabreCat, I'm not seeing the problem for myself. I've created tasks. I attempted to edit those tasks. I've used the cancel button at the top to cancel my edit of those tasks and the cancel button at the bottom both, while I was in mid edit and after saving an edit. All those buttons seem to work just fine. Am I misunderstanding the problem or has it been fixed?

**Comment by librarianmage** [comment]
I believe the problem is that the "Save" and "Cancel" for the challenge (by
the title) doesn't stop the syncing of tasks when you add/delete/modify
them. For instance, when @SabreCat was working on the "Take This"
challenge, they accidentally added a habit, but when they tried to click
cancel on the challenge (believing it would prevent it from syncing to all
of the participants), it was already being sent to everyone who was
participating.

**Comment by SabreCat** [comment]
@teqnickels, @MathWhiz is correct. Here's detailed steps to reproduce:

1. Create a Challenge with any number of associated tasks.
2. Make sure that at least one user has joined the Challenge. (Creating it should have signed you up already, but you can double-check by syncing and seeing that the tasks show up in your list.)
3. Return to the Challenge and edit. Add a task. Then click Cancel instead of Save on the Challenge.
4. Sync. The added task appears in the joined users' task lists, even though the edit was ostensibly canceled.

@Alys's comment that a full fix would be "nightmare level" coding may be accurate; we'd need to hold all task adds, deletions, and edits in the user's local session and only publish them out to the database upon Save. We'd also want guardrails against the user clicking away and losing their edits, the "Are you sure you want to leave this page" alert seen on various sites. That's too much effort for now, given the frontend rewrite underway! Thus the idea of putting a warning label on that explains the behavior, instead.

**Comment by teqnickels** [comment]
@SabreCat Thanks for letting me look into this, unfortunately I have time constraints that have prevented me from moving forward. For the sake of not wasting your time, @silentsoundz is very interested in looking into this issue and so, I'm releasing this to give her the opportunity to do so. Thanks all!

**Comment by silentsoundz** [comment]
Hey all. Im silentsoundz I am a student at learners guild and would like to be a part of this project. I can look into the issue as soon as I get the go ahead.

**Comment by librarianmage** [comment]
@silentsoundz As @TeqNickels was already given the go-ahead, I am fairly
certain it is ok for you to start.

**Comment by silentsoundz** [comment]
I've been poking around with this issue. The save/cancel buttons only apply to the "challenge title" field and the "tag name" field. You cannot edit the "description" field once the challenge has been saved. I am thinking the warning label suggestion would be better placed in the tasks description. "New tasks will automatically save once entered." Or something to that effect.

**Comment by SabreCat** [comment]
@silentsoundz: What do you mean by "You cannot edit the 'description' field once the challenge has been saved"? I've edited Challenge descriptions on a regular basis for the Take This series, so I don't think that's accurate.

Having the warning label near the tasks area does make sense, though!

**Comment by silentsoundz** [comment]
@SabreCat correction it is the "Tag name" that cannot be edited. Sorry for the confusion. Once the challenge is made the order of the fields change.

**Comment by silentsoundz** [comment]
@SabreCat I am very new to Habitica and also very new to open source. Please advise on what the next steps are. Was the problem just needing a suggestion or should I do a pull request to fix this....

**Comment by SabreCat** [comment]
@silentsoundz All good! In Habitica's repo, the "help welcome now" label means we're looking for someone from the community to step up and address the issue. "in progress" means, as in your case, that someone has volunteered to take care of it. So the next step is indeed to submit a pull request!

Feel free to comment here if you have further questions; we're happy to help new open source contributors get started!

**Comment by silentsoundz** [comment]
thank you @SabreCat. Upon further Observation with this issue I was hoping to make a suggestion. there could be warning label.... or if the save and cancel buttons were placed below the challenge description and above the tasks. in their place a new button that says exit ( to take you out of edit mode) it might make things more clear.

**Comment by SabreCat** [comment]
@silentsoundz: Sure, OK. So long as the core matter is addressed--making it clear that "Cancel" will not stop any edits to tasks from going out--that could work!

**Comment by helenyau0** [comment]
hi @SabreCat, @silentsoundz has passed this issue on to me. I very much would like to take this challenge on, but I'm confused as to how you'd like to resolve the problem. Would you like to resolve this issue by adding a warning label below the cancel button warning those who create a challenge to not click "cancel" until they're done with their edits, or would you rather fix the cancel button so it will actually cancel?

**Comment by librarianmage** [comment]
My understanding of the issue is to create a message stating that clicking
the cancel button will not revert changes to the task list.

**Comment by helenyau0** [comment]
@Alys @SabreCat @MathWhiz Oh, I see :) What would you guys like the exact message to say? Also, would it be better to add the message inside all the task templates so when the user is creating the tasks they will see the warning right away?

**Comment by lemoness** [comment]
@SabreCat Is this still an issue with the new design?

**Comment by librarianmage** [comment]
I believe so

**Comment by lemoness** [comment]
@tressley you may want to take a look at this.

I'm updating the labels on this issue.

**Comment by TheHollidayInn** [comment]
I don't think this is an issue anymore. Tasks are added one at a time now.

**Comment by SabreCat** [comment]
Yeah, it's still a bit unfortunate that you can't put the Challenge in a "draft" state with multiple pending task edits, but the UI is no longer misleading in the way it was before.
