### ISSUE TITLE
Gain / Loss history

### ISSUE THREAD

**Issue by scroll** [HabitRPG/habitica#855]
It would be nice to be able to see why you gained gold / XP and why you lost life. Similar to how RPGs have combat logs : http://img.brothersoft.com/screenshots/softimage/h/hitsmode-261087-1247654735.jpeg

**Comment by heyimzsa** [comment]
+1
—

**Comment by wizonesolutions** [comment]
@scroll I use @pjf's `hrpg` client https://github.com/pjf/WebService-HabitRPG as a workaround. It has an `hrpg history` command that lets you see the plusses and minuses of individual habits/dailies/todos at least, though not stat histories (which I also want).

:+1:

**Comment by pjf** [comment]
That reminds me that I want to store extra stats on each task if you update them via hrpg. But yes, having a native interface for this would be amazing. :D

(Also, thanks to @wizonesolutions for the plug!)

**Comment by scroll** [comment]
Thanks @wizonesolutions. I will use this for now.

**Comment by paglias** [comment]
For experience there's a graph and also for each task, now. Only gold/life progress is missing
