### ISSUE TITLE
Dailies stay red even if they are done regularly.

### ISSUE THREAD

**Issue by scroll** [HabitRPG/habitica#856]
I am not sure how the colour of dailies is calculated, but I have few dailies which stay red even if I complete them every day. Is that the "correct" behaviour ? How is the colour calculated ?

**Comment by wizonesolutions** [comment]
They should get less red as you complete them as a streak and move towards yellow, green, blue in shades. That's what happens to mine at least.

**Comment by lefnire** [comment]
Exactly. So let's say you had a daily hit red, the you went 3 more days
without completing it. It would take 4 days of completing it to get out of
the red.

**Comment by scroll** [comment]
I see. I was under the impression it would turn green once it's completed.
