### ISSUE TITLE
columns on mount page are too narrow for Turtle flippers

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8560]
The "heads" of the Turtle mounts are wider than of the other mounts and the columns on the Mounts page haven't been sized to accommodate them neatly (see screenshot below).

This is probably just a simple CSS fix, but if for some reason it turns out to be at all complex, it would be best to leave this to be fixed in a website improvement project that we're part way through.

![image](https://cloud.githubusercontent.com/assets/1495809/23827922/ea4fdaa4-070b-11e7-928b-e1025465aed5.png)

**Comment by djw11192** [comment]
Hello @Alys.  I would like to work on this.  I am new to making open source contributions but would love to become involved in this project.

**Comment by Alys** [comment]
@djw11192 Thank you, that would be great! Comment here if you have questions or run into problems.

**Comment by SabreCat** [comment]
Should this instead be a pixelist fix to make properly sized icons for turtle heads instead of using their whole front sprite? @lemoness @beffymaroo

**Comment by beffymaroo** [comment]
That might be the easiest thing to do- if @lemoness agrees I can add that to the Pixel Art Trello and post it as an available claim. People tend to turn out mount heads pretty quickly. :)

**Comment by lemoness** [comment]
Yes, this should be handled by a pixelist!

**Comment by beffymaroo** [comment]
Okay, claim for re-doing the heads is on the Trello. Will update when they are done!

**Comment by beffymaroo** [comment]
Turtle Icons are ready, thanks to artisan Willow the Witty. Filenames should be correctly formatted. 

![mount_icon_turtle-base](https://cloud.githubusercontent.com/assets/9218855/24378619/6f0bd17e-12f8-11e7-99d9-70f5eb647337.png)
![mount_icon_turtle-cottoncandyblue](https://cloud.githubusercontent.com/assets/9218855/24378625/7762b270-12f8-11e7-9161-4fe9d6bda63d.png)
![mount_icon_turtle-cottoncandypink](https://cloud.githubusercontent.com/assets/9218855/24378627/7a7f077e-12f8-11e7-8b99-97c08e0cb62f.png)
![mount_icon_turtle-desert](https://cloud.githubusercontent.com/assets/9218855/24378635/81c26710-12f8-11e7-8180-aaf52a5af4dc.png)
![mount_icon_turtle-golden](https://cloud.githubusercontent.com/assets/9218855/24378645/8a0dc45a-12f8-11e7-91a1-1abe6acf71fe.png)
![mount_icon_turtle-red](https://cloud.githubusercontent.com/assets/9218855/24378649/8d4a3ff4-12f8-11e7-8eb2-6b01f11ae901.png)
![mount_icon_turtle-shade](https://cloud.githubusercontent.com/assets/9218855/24378653/8f62ff10-12f8-11e7-9a79-b20c5b7d22fa.png)
![mount_icon_turtle-skeleton](https://cloud.githubusercontent.com/assets/9218855/24378656/912c96f8-12f8-11e7-9d43-2d9c15d9fffb.png)
![mount_icon_turtle-white](https://cloud.githubusercontent.com/assets/9218855/24378658/9314eb32-12f8-11e7-9db3-3d09ea9febae.png)
![mount_icon_turtle-zombie](https://cloud.githubusercontent.com/assets/9218855/24378659/948226f6-12f8-11e7-9a5b-8d1f78bb8cbf.png)

**Comment by beffymaroo** [comment]
Artisan Willow the Witty has completed the Turtle Icons (Heads) - they can be found here: https://trello.com/c/j4qJevKQ/1-turtle-heads-by-willow-the-witty

I didn't upload them here directly because you lose the filename that way, and I've already given these the correctly formatted filenames needed for when they are implemented. :)

**Comment by kvsm** [comment]
Hi, I noticed these icons weren't added yet so I took the liberty of submitting a PR. Hope that's ok :)

**Comment by lemoness** [comment]
That's great! Thank you very much :)
