### ISSUE TITLE
limit party size to 30 members

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8561]
Currently, a party can have an unlimited number of members. This isn't good for performance and it can also give players a bad experience of Habitica for reasons related to accountability and interpersonal interactions.

We want parties to be limited to 30 members. However we don't want to immediately disadvantage the parties that are currently larger, so the limitation will be that you cannot invite new members when you already have 30 or more.

Parties that already have more than 30 can keep all their members. If they choose to remove members, they cannot add more until their member count is lower than 30.

Some suggestions for the code:
- 30 should be stored in a variable so it's easy to change later
- The API must enforce the limit. The API route is [https://habitica.com/api/v3/groups/:groupId/invite](https://habitica.com/apidoc/#api-Group-InviteToGroup)
- The limit must apply to ONLY parties, not public or private guilds.
   - There must be tests to prove that:
      - the limit applies to parties
      - the limit does not apply to public guilds
      - the limit does not apply to private guilds. (Also any other tests that are necessary of course.)
- The party's `memberCount` attribute can be used to find the current size of the party. The `memberCount` is not always accurate (https://github.com/HabitRPG/habitica/issues/7506) but for the purposes of this feature it will be close enough. (We'll be fixing the inaccurate memberCounts eventually, and any players negatively affected by an inaccurate count can get it fixed for their party by reporting it in the Report a Bug guild.)
- The party page should have a sentence stating that once a party has 30 or more members, no more can be invited. It should probably be placed under the "Members" header and "Invite Friends" button: ![image](https://cloud.githubusercontent.com/assets/1495809/23830033/4f0adcc4-074c-11e7-9f0a-83bc7da993d2.png)
- When the memberCount is 30 or greater, the "Invite Friends" button should not appear. The message described just above should be changed to say that because the party has more than 30 members, you can't invite more. It should explain that when the party size is less than 30, invitations will be possible again.

**Comment by Yutsuten** [comment]
Looks complicated, but can I try to do it?

**Comment by Alys** [comment]
@mateus-etto Sure! Thank you! Ask here if you run into problems. I think the actual code won't be too complex; there's just a few things to consider in it.

**Comment by Yutsuten** [comment]
Do I have to worry about translations? I have never worked with it...
And can I show the current value of _memberCount_ to the users?

I was thinking to put a message like this: 
``` JavaScript
"Your party currently have " + memberCount +
" members. The limit of members in a party is " + limitMembers +
". If there are " + limitMembers + " members or more, you cannot send more invitations."
```

**Comment by Alys** [comment]
@mateus-etto You don't need to worry about translations. In fact, we prefer that you don't edit any of the files under `website/common/locales` except for the ones in `website/common/locales/en` (don't even change the other English variants such as `en_GB`). All translation work is done in Transifex.

Yes, you can show memberCount to the users - that's a good idea. I like your wording, except the first "have" should be "has". :) 

I don't know if you were planning to do code exactly as you've written it there or if that was just for showing the text. In case you're not aware, we don't concatenate strings and variables exactly like that because it can make translations non-grammatical (e.g. for languages with a very different word order). Here's an example of how we do it:
https://github.com/HabitRPG/habitica/blob/21ad808cc163dd5f826e7ea8150413ebde2ed998/website/common/locales/en/settings.json#L118
https://github.com/HabitRPG/habitica/blob/21ad808cc163dd5f826e7ea8150413ebde2ed998/website/server/libs/payments.js#L320-L324

**Comment by Yutsuten** [comment]
@Alys Thank you for the answer, I didn't know that.

I have another question:
If the party currently have 29 of 30 members, the leader still can invite users, right? What is the expected behaviour if the leader invite 2 or more users in this situation?
1. The invitations fail completely. The success will happen only if 1 member is invited.
2. Only the first invitation is sent, but the another fails.
3. Both invitations are sent with no problem.

At this point, I see another problem: should I consider pending invitations? If there are 29 of 30 members and 1 pending invitation, should be possible to invite more?

**Comment by Alys** [comment]
Excellent questions! I hadn't thought of any of that!

The limit should apply to current members plus pending invites, so 29
members plus 1 invite means no more invitations can be sent.

When you try to invite more people at once than the limit allows, all
invitations fail completely.

**Comment by Yutsuten** [comment]
@Alys Got it. Now a more technical question:

I'm changing the _api.inviteToGroup_ "function" in the server and was able to get the number of current members on the party, the number of emails and UUIDs provided to invite, but I can't find a property with how many pending invitations currently exist in the party.

In the client (groupService,js) the value is in the _group.invites_, so I could easily take the number of invitations (_group.invites.length_), but how about in the server? I'm not finding it in its _group_ object...

For now I got it working with a limit of 2 members (easier to test) in the party and ignoring the number of current pending invitations.

**Comment by Alys** [comment]
Ah, yes, the number of invitations isn't stored anywhere. Each invitation is stored in the account of the player who was invited and when the party page loads, a search is done to find all of those players. The database has an index on that field so the search is fast. You could do a similar search to count the number of invitations.

I don't know off the top of my head where the code that searches for the invitations is, but if you can't find it ask here.
