### ISSUE TITLE
Users with lifetime subscriptions do not receive Jackalope mounts when joining a Group Plan

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8566]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Group plans were recently enhanced to give various extra benefits to their members, including individual subscriptions and an exclusive mount. However, the code currently bails out entirely if the user has a permanent free subscription (as given out to staff and other top-tier contributors). It should instead skip granting an individual subscription, but go ahead and award the Jackalope-RoyalPurple mount if the user does not have it already.

A migration has been run to give out these mounts for users previously affected by the issue, but it'd be nice not to have to do so again for any later lifetimers' benefit!

**Comment by veeeeeee** [comment]
Closing because it's not really a large pain point and we're happy to do this manually when a new lifetime subscriber is added.
