### ISSUE TITLE
Habits from Challenges and Group Plans should show counter reset frequency (uneditable)

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8571]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

The new counters on Habits cannot be edited if the task originates from a Challenge or a Group Plan; that is expected behavior. However, it would be valuable for a user to be able to _see_ the reset frequency. Two possibilities, both of which could be implemented:

* In the tooltip that currently just says "Counter", it could say "Counter (resets Xly)" with the appropriate interval for X. (This would apply in all cases, not just Challenge/Group tasks.)
* The Advanced Options in the task edit modal could show the selected frequency, but disabled for editing. (Just for Challenge/Group tasks.)

**Comment by Alys** [comment]
Oh good point! The same applies to Habits from Group Plans so I'm about to edit the title to mention them too.

**Comment by yugensoft** [comment]
Hi, I'm interested in helping and this issue looks like a good start. Can it be assigned to me? Cheers

**Comment by SabreCat** [comment]
@yugensoft: OK! Let us know here if any questions come up while you're working on it!

**Comment by yugensoft** [comment]
OK its done, I'll put up the pull request soon.
