### ISSUE TITLE
Check-in prize when you have all available prizes should have a special message

### ISSUE THREAD

**Issue by Qchristensen** [HabitRPG/habitica#8573]
_edit by Alys 2017-03-25:_

_The original bug report here by Qchristensen is below but has also been copied to the Android repo at https://github.com/HabitRPG/habitica-android/issues/732 - all work on the Android bug should be recorded there. The iOS version is at https://github.com/HabitRPG/habitica-ios/issues/447.  This issue is now for related changes to the website version of the check-in message._

On the website, when you have received the final check-in prize available so far, you are shown the modal in the screenshot below. It should have an additional message on it saying:
**"You have received all the Check-In prizes currently available! More will be added in the future."**

Note though that at some time in the future, we will stop adding new check-in prizes (ref: [Lemoness's comment below](https://github.com/HabitRPG/habitica/issues/8573#issuecomment-288570486)) and at that time the message will need to be changed, and we'll need a reminder about that.

So the actions needed for this issue are:
- [ ] Add a string to `website/common/locales/en/loginIncentives.json` containing the new message ("You have received all the Check-In prizes currently available! More will be added in the future.")
- [ ] Display that string on the modal below, probably just above the "Awesome" button but only when the user has received the last prize currently available.
   - The code that defines the prizes is in https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/loginIncentives.js -- i.e., you can use that content data and the user's `user.loginIncentives` count to determine if the user has just been given the final prize.
- [ ] Add this code comment to `website/common/script/content/loginIncentives.js` just below [this line](https://github.com/HabitRPG/habitica/blob/0ec293bd158a17e9c9f3763715fde22ad99d5080/website/common/script/content/loginIncentives.js#L227):
      `// When the final check-in prize is added here, change {string name} in website/common/locales/en/loginIncentives.json to say "You have received the final Check-In prize!". Confirm the message with Lemoness first.`
   - [ ] Replace {string name} with the name you chose for the string.
- [ ] Edit [this line](https://github.com/HabitRPG/habitica/blob/0ec293bd158a17e9c9f3763715fde22ad99d5080/website/common/script/content/loginIncentives.js#L229) in loginIncentives.js to fix the two "reference" typos (refence and refernce) if they haven't already been fixed by then. :)

![image](https://cloud.githubusercontent.com/assets/1495809/24246657/3d25cd54-1014-11e7-8bc1-afb3588117be.png)

----

_This is the original bug report by Qchristensen but it's being handed in the Android repo, not here, since it's for the Android app:_

  * Browser: Android App
  * OS: Android

When I checked-in for the 95th day in a row, I got a check-in prize (yay, go me!) and at the bottom, it informs me my next check-in prize will be at 0 days.  Expected behaviour is that the next prize would normally be at 100 days.  Screenshot attached:

[screenshot_20170316-062823](https://cloud.githubusercontent.com/assets/15902216/23997545/ce11870a-0aa5-11e7-95bd-cacd14e58983.png)

**Comment by citrusella** [comment]
I think the saddle is actually day 100? As it is, it's currently the last prize until they implement more, so it's probably saying zero because there's no more (though on the site, that counter until next doesn't display if the next prize doesn't exist yet). This probably should have been reported at the [Android issue list](https://github.com/HabitRPG/habitica-android/issues) (or using the in-app report button) so developers specific to that app might more easily see it.

**Comment by Alys** [comment]
Yes, the saddle is day 100, so this is a temporary problem because we haven't updated our content yet with the next set of prizes.

@lemoness This issue is very specific to the case where we get behind on keeping the check-in prizes updated. It won't be worth fixing if it's likely that this is the last time we'll get behind. What do you think about this - should the website and apps have code to cope with the case where new prizes haven't been deployed yet?

**Comment by Qchristensen** [comment]
Sorry, yes this was for day 100, not 95.  Also, re reporting in-app, I can't find a report a bug button.  The closest I could find was under help - how do I report a bug, it links to the main website which then links here.

Resolution for this would perhaps be to check when the next check-in prize is due, and if there isn't one at this stage, just don't display the "Your next prize..." line.  As I said originally, it's only a minor bug :)

Regards

Quentin.

**Comment by Alys** [comment]
@Qchristensen Sorry about the confusion with the bug reporting button! There definitely shouldn't be anything on the website that links directly here - can you tell us please where you found that link?

The bug reporting links should all point to the "Report a Bug" guild (available most easily from the website's Help menu, but also available on the app from Guilds > Public Guilds > Report a Bug).

**Comment by citrusella** [comment]
The Android Report a Bug button (that sends an email to the developers) should be on the "About" page of the app, by the way. :blush: (Just in case you need to use it sometime in the future.)

**Comment by lemoness** [comment]
So, at some point the Check-in Prizes will stop, possibly after around 500
or so. Will we run into the same issue at that time? If so, it's worthwhile
to get the code in.

**Comment by Alys** [comment]
For the case where there will never be more check-in prizes, we'd want a different message than the one needed to fix this bug, but it would be  the same code to display it, so yes, we should fix this now on all three platforms. When the final check-in prizes are added to the site, we can change the message at the same time (we should put a comment in the code now to remind us). I'll log issues for this for Android and iOS and update this issue to be for the website.

**Comment by Alys** [comment]
I've logged the Android issue here: https://github.com/HabitRPG/habitica-android/issues/732

I'll do some testing on a borrowed iPhone to see if something similar is needed for the iOS app.

@lemoness On the website, when you have received the final prize available so far, the modal below is what you see. Do you want us to add a message to it saying that there's no more prizes at the moment but that more will be added later? (In the far future when the prizes stop, we'll change that message to state that there's no more ever.)

![image](https://cloud.githubusercontent.com/assets/1495809/24246657/3d25cd54-1014-11e7-8bc1-afb3588117be.png)

**Comment by lemoness** [comment]
Yes, let's add the message there as well!

**Comment by Alys** [comment]
I've updated the top post in this issue to be specifically for the website. 

I've created a new issue for the same problem in the iOS app at https://github.com/HabitRPG/habitica-ios/issues/447

As mentioned above, the Android bug report is at https://github.com/HabitRPG/habitica-android/issues/732

**Comment by Yutsuten** [comment]
May I work on this issue?

**Comment by Alys** [comment]
@Yutsuten Yes, thanks!
