### ISSUE TITLE
Migrate API errors to apiMessages from i18n (no translations for developer-only messages)

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#8574]
https://github.com/HabitRPG/habitica/commit/939712ad1f8e8c8e228907b30844fcd3bb5dae51 introduced the `apiMessages` library  (https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/apiMessages.js) because we've decided that API messages aimed at developers will only be in English from now on.

We should migrate old translated messages to the new lib.

**Comment by madpink** [comment]
are you interested in this being multiple files from the outset, or lumping all the apiMessages into one and possibly splitting it out later?

Also, just to make sure I know what is involved before I volunteer, I believe that the tasks involved in this would be:

1. Copying all of the api messages into the new lib
2. Removing those same api messages from their current locations & translations
3. updating the appropriate pages to read from the apiMessages library

**Comment by paglias** [comment]
@madpink if we start adding all message maybe it's better to split into multiple files.

And the steps are okay, the important thing is not to remove anything used in the client side and to only move API messages meant for developers, so I'd start with things about `req.params.xxxxx must be ...` and similar

**Comment by SabreCat** [comment]
Re step 2, you would only need to remove them from the English translation files. Changes there will propagate to other languages via a scripted process we run.

**Comment by Alys** [comment]
I've increased the priority on this because as noted in https://github.com/HabitRPG/habitica/issues/10008#issuecomment-367126096 having excess strings is an accessibility issue that slows down the website.

**Comment by negue** [comment]
@paglias  @Alys 

Which error messages can be considered as developer-only messages? I'd select all errors messages which are checked if req.params exists but any others too? like if a group/task doesn't exist?

**Comment by paglias** [comment]
I'd say everything with req.something is a good start
