### ISSUE TITLE
Habit counters do not reset when you are resting in the inn

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8578]
When you are resting in the inn, the Habit counters don't reset. They should reset in the same way as when you are not resting in the inn.

Some relevant code:
- the [performSleepTasks](https://github.com/HabitRPG/habitica/blob/db9befde177c517abac419a1007e62e958f42437/website/server/libs/cron.js#L95) function, which is run when you're resting in the inn
- [the code that resets the Habit counters](https://github.com/HabitRPG/habitica/blob/db9befde177c517abac419a1007e62e958f42437/website/server/libs/cron.js#L320-L334)

**Comment by rohangokhale** [comment]
Forgive me if I'm off base, I've been getting familiarized with the code for only the past week or so. In the cron.js file, the function performSleepTasks never calls tasksByType.habits.forEach((task)... to reset the counters. Could the problem lie there?

**Comment by Alys** [comment]
@rohangokhale Yes, that's right! The code for resetting the counters needs to be called by that function. It would be best to move that code to its own function so that it can be called in both places without duplicating the code.
