### ISSUE TITLE
backgrounds Check-In prize has no name in the notification modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8580]
The check-in prize for your second day in Habitica is a set of backgrounds. When you're given that prize, the modal does not show the name of the prize:

![image](https://cloud.githubusercontent.com/assets/1495809/24066193/0e9db55c-0bbc-11e7-9449-2eedc1723d50.png)

It should show the name in a way similar to this:

![image](https://cloud.githubusercontent.com/assets/1495809/24066252/6d394b1c-0bbc-11e7-8094-6c6ca3798f87.png)

I expect that this is because the backgrounds aren't content in the same sense at the other prizes so the code can't fetch their name. 

One possible fix would be to hard-code a name into `website/common/script/content/loginIncentives.js` in a new field called something like `rewardName` (the value should be translatable of course). That field would be used for only the backgrounds (but could be reused in future if we needed to give a custom name to any other prizes). The code that inserts the name into the modal could first look for the `rewardName` and if it's not specified, it could then fetch the name from the content in the same way it currently does.

_After this is fixed for the website, we should test the Android and iOS apps to see if they pick up the fix automatically (I'm not sure whether the name lookup happens in the API or in the apps). Currently in the Android app, the backgrounds are described as "null"._

**Comment by citrusella** [comment]
Should it be noted that the equipment rewards don't seem to load the right name in Android either? The first (the thing in the bard set) actually reads armor_special_bardrobes (or something like that) instead of its actual equipment name. (Or at least it did on the account I just made to play around and look.)

**Comment by Alys** [comment]
@citrusella Ah, great point. I did notice that but it just didn't occur to me to report it :man_facepalming: It's a separate problem though and I've reported it here: https://github.com/HabitRPG/habitica-android/issues/708#issuecomment-287512698

**Comment by Yutsuten** [comment]
@Alys I would like to work on this issue, may I?

**Comment by Alys** [comment]
@Yutsuten Please do! Thanks!
