### ISSUE TITLE
multiple Group Plan To-Dos approved together don't give rewards automatically

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8582]
If a group plan member completes two or more To-Dos that require approval and the group leader approves them all at the same time, only one of the tasks is correctly handled in the member's task list (it gives XP, etc and disappears). The other approved tasks remain in the member's list and have to be marked completed again manually to make them give XP, etc and disappear.

Steps to reproduce:

1. Group leader creates two or more To-Dos in the group plan, all requiring approval.
2. Group member claims the To-Dos.
3. Member marks all To-Dos as complete (To-Dos correctly remain visible and are labelled as awaiting approval).
4. Leader approves all the tasks at the same time.
5. AFTER all are approved, the member syncs with these results:
   - The member sees notifications for XP, GP, etc for just one task.
   - Sometimes the member sees a "notification not found" error message.
   - Only one task disappears from the active To-Do list.
   - The remaining approved tasks are no longer marked as awaiting approval.
   - The member can tick the remaining approved tasks to gain the XP, etc and to make them disappear from the active list. (It should not be necessary for the member to do that.)

**Comment by Alys** [comment]
Stefano Black (51bfc474-433c-4886-bcdc-1bb9df2ece74) who first reported this issue in the Report a Bug guild says that it also happens for Habits and Dailies. I assume Rewards as well but I have not tested. I expect that the same fix would work for all task types.

**Comment by marceloneil** [comment]
I'll be working on this in my spare time, although I am pretty busy. If somebody else wants to work on this, feel free to.

**Comment by Yutsuten** [comment]
@marceloneil Are you still working on this issue? If its okay for you, I would like to work on it.

**Comment by marceloneil** [comment]
@Yutsuten I haven't found much time to work on it, so please take it :)

**Comment by Yutsuten** [comment]
@Alys Can you help me? I'm not being able to upgrade my party to group plan in my local Habitica...
I tried editing some values in the database but nothing works... :(

**Comment by Alys** [comment]
@Yutsuten Here's an example of the `purchased` object in a guild or party:
```
    "purchased": {
        "plan": {
            "customerId": "cus_ABCDEFG1234567",
            "dateCreated": "2017-03-10T22:06:59.684Z",
            "dateTerminated": null,
            "dateUpdated": "2017-03-10T22:06:59.684Z",
            "owner": "[User ID of the group's leader]",
            "paymentMethod": "Stripe",
            "planId": "group_monthly",
            "subscriptionId": "sub_1234ABCDEFGHIJ",
            "consecutive": {
                "trinkets": 0,
                "gemCapExtra": 0,
                "offset": 0,
                "count": 0
            },
            "mysteryItems": [],
            "gemsBought": 0,
            "extraMonths": 0,
            "quantity": 11
        }
    },
```


And in case it's useful, here's an example of a user's free subscription from a group plan:
```
    "purchased": {
        "plan": {
            "owner": "[User ID of the person who has the free subscription]",
            "additionalData": null,
            "nextBillingDate": null,
            "nextPaymentProcessing": null,
            "planId": "group_plan_auto",
            "customerId": "group-plan",
            "dateUpdated": "2017-03-12T08:12:50.423Z",
            "gemsBought": 25,
            "paymentMethod": "Group Plan",
            "extraMonths": 0,
            "dateTerminated": null,
            "lastBillingDate": null,
            "dateCreated": "2017-03-12T08:12:50.413Z",
            "mysteryItems": [
                "head_mystery_201703",
                "armor_mystery_201703"
            ],
            "consecutive": {
                "trinkets": 0,
                "offset": 0,
                "gemCapExtra": 0
            }
        }
    },
```

Ask again if you need anything else!
