### ISSUE TITLE
more tests are needed to ensure shouldDo performs correctly for all current Dailies repeat options

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8585]
We are adding new repeat options to Dailies so we need to be sure that the tests for the current options are thorough. This issue describes all the conditions that should be tested (not including tests for the new repeat behaviour, which will also be needed but they can be added with the new code).

Some of these tests will already exist but not all of them do. Please add any that I've missed or give any other comments you have.

The code for determining whether a Daily is due is in the `shouldDo` function in `website/common/script/cron.js`

When a Daily is due today but not yesterday or tomorrow:
- If the user's Custom Day Start time (CDS) is midnight and the current time is before midnight (i.e., it's not today yet), the Daily is not due.
- If the CDS is not midnight and the current time is between midnight and the CDS, the Daily is not due.
- If the current time is after the CDS but is not yet tomorrow, the Daily is due.
- If the CDS is not midnight and the current time is after midnight on tomorrow but before the CDS tomorrow, the Daily is due.
- If the CDS is not midnight and the current time is after the CDS tomorrow, the Daily is not due.
- If the CDS is midnight and the current time is tomorrow, the Daily is not due.

Tests for the Daily's Start Date:
- NB this assumes that the current time and CDS are such that the Daily would be due if the Start Date had an appropriate value.
- If the Start Date is before today, the Daily is due.
- If the Start Date is today, the Daily is due.
- If the Start Date is tomorrow, the Daily is not due.
- The Start Date is saved as a date-time in UTC but when it's converted to the user's time zone, we care about only the date portion (e.g., if the Start Date when coverted to the user's time zone is today at 9am, the Daily is due now even if the current time is not yet 9am).
- However in the above example, if the CDS is 10am, the Daily is not due now (it will be due after the current time passes 10am).

If the Daily uses the Every X Days repeat:
- it's due on the Start Date
- it's due X days after the Start Date
- it's due X*2 days after the Start Date
- but if X = 0:
   - it's not due on the Start Date
   - it's not due on the day before the Start Date
   - it's not due on the day after the Start Date
   - it's not due today

If the Daily uses the days of the week repeat:
- it's due on the days selected
- it's not due on the other days
- those should be tested with a CDS of midnight and a non-midnight CDS
- if no days of the week are selected:
   - it's not due on the Start Date
   - it's not due on the day before the Start Date
   - it's not due on the day after the Start Date
   - it's not due today

Can anyone see any cases I've missed for the current repeat behaviour?

**Comment by gracesusanchen** [comment]
Hi Alys, this is 'GraceS' on habitica : ), I would definitely be interested in picking this one up! I may need a bit of time to comb through all the test cases though.

The existing test cases are in /test/common/shouldDo.test.js, right? Are there any conventions for naming/structuring the test folder? Thanks ; ) your help is very appreciated!

**Comment by TheHollidayInn** [comment]
I would just follow the other tests as examples. You can run the test with `gulp:test:common` after adding `.only` to the describe function.

**Comment by Alys** [comment]
@gracesusanchen Thanks very much, it's yours! Comment again here if you have more questions.

**Comment by gracesusanchen** [comment]
Hi @Alys,

I think I now partly have my head wrapped around the code and how to test, here's a quick description of my understanding.

Of the three parameters of `shouldDo()`:
* `day` - is the current time in Date format, with timezone GMT
* `dailyTask` - the task we are checking if due
* `options`
  * `.dayStart` - is the CDS, a number between 0~24
  * `.timezoneOffset` - is the timezone, a number between -840~720

I think I will have a set of tests for each of your big bullet points, like this:

* Task due today only, not yesterday or tomorrow -> try combinations of timezone & CDS
* Task is due daily, testing Start Date -> try combinations of timezone & CDS
* Task is due every x days -> try different CDS
* Task is due certain days of the week -> try different CDS

Does this sound OK?

**Comment by Alys** [comment]
@gracesusanchen That sounds good to me!

**Comment by TheHollidayInn** [comment]
Some tests are commented out, so you will want to enable those. 

Also, you tests look good but here are few suggestions:
 1. All "not due" are separate tests. For example, not due yesterday is a test.
 2. You will want to have a test for every x day on a certain day
 3. The months have different options - every x days and on a certain date (not day).

**Comment by Alys** [comment]
This issue is for tests for just the current repeat options for Dailies (so not monthlies or other new repeats). I want us to get a solid set of tests for the existing behaviour before any new ones are introduced. Tests for new behaviour wouldn't pass with the current code, so they're best left to a different PR.

**Comment by gracesusanchen** [comment]
I have the PR ready, but two new tests added by me are failing for the same reason. I will try to explain below:

* Test case: When Start Date is today, CDS is midnight (`dayStart = 0`), but the current time is before midnight, the Daily Task should not be due.

In my test I am setting 
- `options.dayStart = 0` for midnight, 
- `task.startDate = new Date()` for Start Date of today's date
and the current time by changing the `day` value like this:

```
day = moment(day).startOf('day').add(1, 'hours').toDate();
```

When calculating the `startOfDayWithCDS`, the Start Date is computed to be today, as is the current time, so `shouldDo` returns true. We expect it to return false though : (

Feedback would be greatly appreciated!

Happy weekend : )

**Comment by SabreCat** [comment]
Reopening temporarily as the fix PR has been reverted. @gracesusanchen's PR does address this, we just need to straighten some things out before it can be incorporated!

**Comment by TheHollidayInn** [comment]
This was fixed in a different PR from me reverting us back to Zone.
