### ISSUE TITLE
Quest start has blank notification message

### ISSUE THREAD

**Issue by joedragons** [HabitRPG/habitica#8587]
General Info
  * UUID: 66902097-c79b-496f-acd9-b78cc5867b28
  * Browser: FF52.0.1 (and older, just upgraded this weekend)
  * OS: Windows 10

Description
I've been running thru the Lunar quests and noticed for each of them when the quest starts a blank notification message appears.  I believe this notification is associated with the quest start (e.g. "Your quest, Lunar Battle, Part 3: The Monstrous Moon, has started.") as my party log has no other messages at that time.

I hadn't noticed this before so it's possible that it's related to the Lunar quests, tho I believe the addition of quest start (and end) messages is fairly new and I'd been doing longer quests for a while, so the date is hard to gauge.

See attached, let me know if unclear.
![habiticablank](https://cloud.githubusercontent.com/assets/9559205/24088024/0c3d7392-0cfc-11e7-9e3d-1db3a9baf396.png)

**Comment by Alys** [comment]
Thanks for telling us! Very interesting about it being related to quest start messages. I've copied that information to https://github.com/HabitRPG/habitica/issues/8207 where we're tracking this issue. We hadn't 
noticed a correlation with quest messages before so this might give us a good boost to solving it!

BTW, the Help > Report a Bug guild is a good place to report even problems like this. We can advise you there if a GitHub report is needed and sometimes it's not, which can save you some time. :)

**Comment by joedragons** [comment]
@Alys NP.  I've watched the other issue, thanks for linking.  I searched "quest"; I see now I should have searched "notification"=)
I'm a QA/QE by trade so filing this took me no time at all.  However, I don't want to waste your or anyone elses time=9  I do feel screens are better for here, but other than that I can certainly stick to the guild.
