### ISSUE TITLE
"D is Undefined" Mystery Gift

### ISSUE THREAD

**Issue by ryanleesipes** [HabitRPG/habitica#8596]
General Info
  * UUID: f6057c63-a045-41c5-ba1d-2f993e4a4e42
  * Browser: Firefox 52.0.1
  * OS: Ubuntu 16.04

### Description
When opening two Mystery Gifts in my inventory (for being a subscriber) received the notification "D in Undefined". Can't tell if there is anything new in my inventory.

#### Console Errors
Wasn't ready for the error so did not capture console error or screenshot.

**Comment by Alys** [comment]
Please reload the website before clicking the Mystery Box. Your browser doesn't have all the information it needs yet.

We actually have a guild within Habitica for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). For general questions about Habitica features, you can go to Help > Ask a Question on the website (or Guilds > The Newbies Guild on the app; it's not just for new users).
The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.
