### ISSUE TITLE
the "Delete Completed" on-hover message needs to be changed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8598]
_<strike>I'm logging this initially for suggestion/discussion, but once a decision is made, a PR will be needed to change some text on the website (regardless of the exact decision).</strike>_

<strike>When you click the "Delete Completed" button in the To-Dos "Done" tab, completed To-Dos from Group Plans are **not** deleted. Is this what we want? It's consistent with To-Dos from active challenges (we definitely don't want them to be deleted because that would make it harder for the challenge owner to judge the challenge), but I'm not sure there's any need to keep completed Group Plans To-Dos and they'll build up over time. To-Dos that required approvals would already have been approved before they become marked as completed. I don't think that Group Plans leaders can see the members' completed To-Dos, so there's probably no point keeping them.</strike>

<strike>Are there any opposing viewpoints? In about a week, if no one has expressed a desire for completed Group Plans To-Dos to be kept, I'll mark this as help welcome for allowing them to be deleted.</strike>

At the bottom of the To-Dos "Done" tab, there's a "Delete Completed" button. The text that appears when you hover over that button needs to be changed. Currently it says "If you click the button below, all of your completed To-Dos and archived To-Dos will be permanently deleted. Export them first if you want to keep a record of them." That should be changed to something like:

"If you click the button below, all of your completed To-Dos and archived To-Dos will be permanently deleted, except for To-Dos from active challenges and Group Plans. Export them first if you want to keep a record of them."

**Comment by TheHollidayInn** [comment]
Completed todos get archived, correct? Why would we want to delete information? I think we should not delete todos.

**Comment by Alys** [comment]
There isn't exactly an archiving process; it's just that the completed To-Dos on the website don't show more than 30 (the most recently completed ones). All completed To-Dos are stored in the database in the same way as other tasks until deletion. We delete old completed To-Dos for performance and database space ([Task History Compression](http://habitica.wikia.com/wiki/Task_History_Compression) for details).

Regardless of that though, even if we never deleted completed To-Dos ourselves, we must still allow the users to delete them when they want to. For example, they might realise there were privacy or security concerns with some of their completed To-Dos.

**Comment by TheHollidayInn** [comment]
If we don't allow for deleting in challenge, we should not here either. Currently, the user's task is the only indication of approval for group leaders to verify that a member completed it. The task can be deleted if the group leader unassigns them.

**Comment by CutTheCode** [comment]
Hello, I would like to help with this, may I ask where the file contains this function: clearDoneTodos(), is located?

**Comment by Alys** [comment]
@CutTheCode Thanks! It's all yours!

The best way to find code is with the `git grep` command. Change into the root habitica directory in your local install (i.e., the directory that contains the `config.json` file) and then type `git grep clearDoneTodos`. You'll see search results from the entire code base.

Comment again here if you have any other questions or run into trouble.

**Comment by ghost** [comment]
@CutTheCode Hey, is there any progress?

**Comment by CutTheCode** [comment]
@shakhbulatgaz It's all done :)
