### ISSUE TITLE
Where'd Everything Go?

### ISSUE THREAD

**Issue by PorkHat** [HabitRPG/habitica#86]
First of all I really like the ap! I just signed up today and I was having a lot of fun with it. I set up my habits, todos, and dailies, checked some off as I completed them at the computer and it seemed to be going fine. Then I finished all the tasks I would be doing at the PC and got on with the rest of my day. That was probably around 11:15AM. I came back at around 7:00 PM and everything was gone. It said I was disconnected so I tried to reconnect but it wouldn't let me. I rebooted my PC, logged back in and it said that site maintainance was happening. Finally I logged back in and then it was the default items listed, not the ones I had entered this morning.

If it matters I logged in with Facebook. 

PS I just checked again before submitting this and still no dice.

**Comment by lefnire** [comment]
Check out #85. I'm terribly, terribly sorry - follow up there, and if there's anything I can provide for you hit me up. This won't happen again.

**Comment by lefnire** [comment]
(Fixed btw, I'm just leaving this open for a few days for people with the same question).

**Comment by coolandsmartrr** [comment]
Yeah, I just experienced the same kind of issue too.
I can't login, because the "Login" button after the username and password field is greyed out.
Could you please fix this please? I'm really pleased with the experience so far, and am eager to recommend it to others. I'd like to continue using this, because it already made a huge impact on my motivation; I cleaned up my room, something I hesitated to do for so long, and it looks vastly different.

**Comment by SSchuth14** [comment]
Just letting ya know that I had the same problem a few times already as well. I didn't lose everything, I think I started early enough for some of my stuff to save, but I definitely noticed (multiple times) exiting and then returning to find my progress for the last few hours gone. Don't mean for this to seem like a pile-on, I love everything else about HabitRPG! Just letting you know I had the issue as well.

**Comment by lefnire** [comment]
thanks @SSchuth14 , yeah it's a load issue from the reddit surge. Trying to figure out what specifically is causing it now

**Comment by RoricSD** [comment]
It happened to me twice today.
Now I have nothing but "Call Mom"
Part of the Reddit surge (sorry!)
Logged in from facebook

**Comment by Falala** [comment]
Aww, the same happened to me just now. I spent so long on it last night and was really motivated to actually get some stuff done today, but when I went to check my todos half of them weren't there. Same with the other columns as well :/ I don't mind re-entering stuff (if I can remember it all!) but before I do, @lefnire do you think it'd be better for me to just wait until the current issues are resolved? I'd rather not risk losing half my entries again.

**Comment by lefnire** [comment]
yep, definitely wait. we're getting really close

**Comment by Falala** [comment]
Awesome, thanks for the speedy reply!

**Comment by lefnire** [comment]
ok, #91 should be mostly fixed (read [comment at bottom](https://github.com/lefnire/habitrpg/issues/91#issuecomment-12408613)), follow up there
