### ISSUE TITLE
Progress and Edit button broken

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#860]
Today I noticed I can't see the progress graph any more on any of my goals. If I click on the button, nothing happens. Until a couple days ago, it was just fine.
Also, on some goals, the Edit button doesn't do anything.
And finally, I can't drag the goals any more.
I tried refreshing and hard refreshing, switching from beta server to normal, but that doesn't do anything. I'm on Chrome, Windows 7.

**Comment by lefnire** [comment]
Any Chrome Console javascript errors? Some people are experiencing
literally not being able to do anything, is that what you're experiencing -
or are these the specific actions you can't perform?

**Comment by ghost** [comment]
I can tick off my tasks just fine, and for some goals, the Edit button still works.
In the console, after reloading, I've got 10 errors. 9 of them are GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1400069289 (or some other numbers on the end for the other errors) rDIuukMx0rUjDTOPImTI4w.js:5. 1 is "Uncaught TypeError: Object #<Object> has no method 'set'" rDIuukMx0rUjDTOPImTI4w.js:6
After clicking on progress, I get "Uncaught ReferenceError: google is not defined" rDIuukMx0rUjDTOPImTI4w.js:20

**Comment by lefnire** [comment]
OK, you nailed it. I wouldn't have guessed that's the issue, I need to
merge SLaks/racer#master in with my dontPersist racer customizations, will
do in the next couple days

**Comment by ghost** [comment]
Ok, no idea what it all means, but I'm glad you figured it out :).

**Comment by lefnire** [comment]
done. can y'all test?

**Comment by lefnire** [comment]
actually, this isn't what i thought it was. Let's follow up on https://github.com/lefnire/habitrpg/issues/840 , this is dupe
