### ISSUE TITLE
cancelled subscriptions sometimes end early

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8600]
I've seen the subscription problem described below a few times now in recent weeks. We've had similar problems in the past but my feeling is the cause for this now is relatively new (e.g., a previous cause was from a negative extra_months value but that's been fixed now). So, I'm creating a new issue for this.

A user reported today that they cancelled their subscription and the end date was set too early.

This is their subscription data from 2017-03-25, before they cancelled:
```
    "purchased": {
        "plan": {
            "consecutive": {
                "trinkets": 0,
                "gemCapExtra": 0,
                "offset": 0,
                "count": 0
            },
            "mysteryItems": [],
            "gemsBought": 25,
            "extraMonths": 0,
            "customerId": "cus_.........",
            "dateCreated": "2017-03-08T18:52:20.051Z",
            "dateTerminated": null,
            "dateUpdated": "2017-03-08T18:52:20.051Z",
            "owner": "02026ad7-00c7-4b95-ae91-b060cd8a49ad",
            "paymentMethod": "Stripe",
            "planId": "basic_earned"
        }
    },
```

Their record in Stripe showed no payment problems and no record of the payment being reversed:
```
AMOUNT  DESCRIPTION                               PERIOD
$5.00   Subscription to Basic 1mo ($5.00/month)   2017/03/08 18:52 to 2017/04/08 18:52

cus_............................'s invoice for $5.00 was paid   2017/03/08 18:52:19
cus_............................ has a new invoice for $5.00    2017/03/08 18:52:19
```

This is their subscription cancellation event from the webserver logs:
`172.......... - - [27/Mar/2017:04:06:34 +0000] "GET /stripe/subscribe/cancel?_id=02026ad7-00c7-4b95-ae91-b060cd8a49ad&...... HTTP/1.1" 302 46 "https://habitica.com/" "browser description" "12.234.56.789"`

This is their subscription data from today, after they cancelled:

```
    "purchased": {
        "plan": {
            "consecutive": {
                "trinkets": 0,
                "gemCapExtra": 0,
                "offset": 0,
                "count": 0
            },
            "mysteryItems": [],
            "gemsBought": 25,
            "extraMonths": 0,
            "customerId": "cus_..............",
            "dateCreated": "2017-03-08T18:52:20.051Z",
            "dateTerminated": "2017-03-20T00:00:00.000Z",
            "dateUpdated": "2017-03-08T18:52:20.051Z",
            "owner": "02026ad7-00c7-4b95-ae91-b060cd8a49ad",
            "paymentMethod": "Stripe",
            "planId": "basic_earned"
        }
    },
```
Note the incorrect dateTerminated field, with the date set about a week in the past, and only twelve days after their subscription was created, despite the payment being for one month.

They are not in a guild or party with a group plan.

**Comment by TheHollidayInn** [comment]
It is possible that Stripe did not charge them for the full month. Stripe is able to dynamically adjust the price.

**Comment by Alys** [comment]
The information I found in Stripe lists the full $5 price so it did charge for the full month.

**Comment by JoelTheWriter** [comment]
A quick diagnosis. I'm pretty green, so possible I'm overlooking something.

From payments.js, line 427:
``` 
  let remaining = data.nextBill ? moment(data.nextBill).diff(new Date(), 'days', true) : defaultRemainingDays;
  if (plan.extraMonths < 0) plan.extraMonths = 0;
  let extraDays = Math.ceil(30.5 * plan.extraMonths);
  let nowStr = `${now.format('MM')}/${moment(plan.dateUpdated).format('DD')}/${now.format('YYYY')}`;
  let nowStrFormat = 'MM/DD/YYYY';

  plan.dateTerminated =
    moment(nowStr, nowStrFormat)
    .add({days: remaining})
    .add({days: extraDays})
    .toDate();
```
For the day, `nowStr` is using `dateUpdated` _(3/08 in this case)_. 

`remaining` is 12 _(04/08 - 03/27)_. 

(03/08 + 12) = 03/20 _(user's `dateTerminated`)_.

Seems as simple as changing `${moment(plan.dateUpdated).format('DD')}` to `${now.format('DD')}`. But there very well could be some reason _not_ to that I'm missing.

**Comment by Alys** [comment]
@JoelTheWriter It does seem to me that you're correct. `dateUpdated` should certainly not be used when calculating time remaining because it can be changed by events unconnected to the user's payments (for example, [cron changes it at the start of each month](https://github.com/HabitRPG/habitica/blob/c23062f87e706a80644d2db6f8d4dd3c4f85a917/website/server/libs/cron.js#L57)). Using `now` instead could not possibly be worse than using `dateUpdated`. I say go for it! Even if more fixes are needed later, this one fix now would improve the current situation.

**Comment by joe-salomon2** [comment]
@JoelTheWriter, are you still working on this?

**Comment by JoelTheWriter** [comment]
@joe-salomon apologies, I actually haven't gotten around to setting up my local install. If you (or someone else) would like to make this fix, feel free.

**Comment by Alys** [comment]
@JoelTheWriter No worries and thanks for letting us know! 

@joe-salomon We'll consider this to be yours unless you tell us otherwise (which you're welcome to do if you don't want to work on it!)

**Comment by joe-salomon2** [comment]
Awesome, I'm on it
