### ISSUE TITLE
New Card and Badge: Get Well

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8609]
We've got a new card and its associated badge ready to implement. :)

The image files and the information for the Market item and badge name can be found on this Trello card: they are not posted here directly in order to preserve the correctly-formatted filenames. :)

https://trello.com/c/W1lhmwEp/7-get-well-card-and-badge

**Comment by librarianmage** [comment]
I can do this! Would it be possible to do this in the same PR as #8610?

**Comment by librarianmage** [comment]
What text should I use for the card?

**Comment by beffymaroo** [comment]
The text for the badge and market item are in the body of the Trello card linked above. Same for the other cards/badges. :)

**Comment by librarianmage** [comment]
What I mean is, what text is there for the message?

**Comment by beffymaroo** [comment]
Ahhh. Good catch! I will compose the text and post it within the next day or so. Same for the other card/badge ticket. :)

**Comment by librarianmage** [comment]
Please let me know when the text is added!

**Comment by beffymaroo** [comment]
My apologies, the travel schedule of myself and some of the other staff delayed me from this task. I'll certainly post here and on the Congratulations card ticket when I have finalized text.

**Comment by librarianmage** [comment]
Thank you!

**Comment by librarianmage** [comment]
For the achievement image, should the filename be `achievement-getwellx2.png`?

**Comment by beffymaroo** [comment]
@MathWhiz The filename should be fine as-is, several other achievement image files have hyphens between words and the "2x" part is also consistent with the other achievements.

Here is the text that should be displayed when the card is opened by the recipient (again, these should be randomized possibilities).

1. Hope you feel better soon!
2. Take care! <3
3. You're in my thoughts!
4. Sorry you're not feeling your best!

**Comment by librarianmage** [comment]
@beffymaroo Yeah, I meant `2x`. I was mostly asking because with all of the other cards, the name of the achievement image matched the name of the card, which I think might be intentional.

**Comment by beffymaroo** [comment]
@MathWhiz Good point. Filename is now `achievement-getwell2x`
