### ISSUE TITLE
Unable to reorder items

### ISSUE THREAD

**Issue by cmaclell** [HabitRPG/habitica#861]
Normally I am able to drag and drop items to reorder them. However, as of yesterday I seem to be no longer able to reorder any of the list items (in any list). 

When I mouse over an item I still get the cursor symbol signifying that I can drag and drop, but when I click and drag it just highlights the text in my todo list items instead of moving / reordering the item.

**Comment by lefnire** [comment]
Any Chrome Console javascript errors you're seeing?

**Comment by Nolori** [comment]
I'm in the same boat. I just got this problem yesterday night. Everything worked fine until I leveled up to level 4 and bought a bunch of gear. (I don't know if the two are related, but that's when it happened.) I looked at the other threads and they seem to say that only the rewards tables aren't dragging properly for them, but I can't get anything to move. It just highlights text. I also still have the cursor in the four-way arrow, but it doesn't move the boxes. It also doesn't work for me on the splash page with the Anon character before you get signed in.

I've also gone ahead and deleted anything with a special character in it (including in the Clear Completed), and it still doesn't work. (Unless numbers count as special characters?) I've cleared my browser history and logged out and back in.

I'm on Win 7, Chrome 26.0 and Safari 5.1.7

Edit: I just learned where to check for errors, look at that! I've got the same one as cmaclell:

Uncaught TypeError: Object #<Object> has no method 'set' qJxZbRKubzHsBhJeXwKamQ.js:6

**Comment by cmaclell** [comment]
Yup, sorry I should have included this in the initial issue:

Uncaught TypeError: Object #<Object> has no method 'set'
qJxZbRKubzHsBhJeXwKamQ.js:6

**Comment by StanLindsey** [comment]
@cmaclell - is this still an occuring issue?

**Comment by cmaclell** [comment]
Seems to be working fine for me now.

**Comment by StanLindsey** [comment]
Cheers! Closing.
