### ISSUE TITLE
New Card and Badge: Congratulations! 

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8610]
We've got a new card and its associated badge ready to implement. :)

The image files and the information for the Market item and badge name can be found on this Trello card: they are not posted here directly in order to preserve the correctly-formatted filenames. :)

https://trello.com/c/ahqm9IFN/6-congratulations-card-and-badge

**Comment by librarianmage** [comment]
I can do this! Can I do it in the same PR as #8609?

**Comment by librarianmage** [comment]
What text should I use?

**Comment by Alys** [comment]
@MathWhiz This and the other two you've asked for are yours. Thanks! I personally feel that it would be fine to put them in the same PR, and no other admins have said otherwise yet, so give it a try. :)

**Comment by beffymaroo** [comment]
@MathWhiz Here are the possibilities for the text when the recipient opens the card. We'd like all five of them to be randomized in the manner of the Valentines and New Year's cards:

---
Congratulations on your success!

I'm so proud of you!

Well done!

A round of applause for you!

Bask in your well-deserved success!

---
Get Well card text is pending! Hopefully I'll have that to you within the next day or so.

**Comment by librarianmage** [comment]
Got it! Thank you!

**Comment by lemoness** [comment]
There has been a slight visual tweak to the congratulations card. The new one is here:
![inventory_special_congrats](https://cloud.githubusercontent.com/assets/3494081/26415653/41f867fe-4081-11e7-9fa0-56d30f8a7dcf.png)

**Comment by librarianmage** [comment]
@lemoness Do you have a direct link to the file? I believe GitHub compresses images.

**Comment by lemoness** [comment]
Yes, it's on Trello here: https://trello-attachments.s3.amazonaws.com/52e9d25cd467121630c6350d/52f73657fe2cc93e7b7bbd4a/63851070509373593b6ff0b409274ef9/inventory_special_congrats.png
