### ISSUE TITLE
Replace Current NPC Badge image

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8611]
The current image for the NPC badge is the same as the one for Warrior-Ultimate Gear. An artisan has created a new image for this achievement- it can be found here: 

https://trello.com/c/Z65N9dNA/13-updated-npc-badge-image

**Comment by librarianmage** [comment]
I can do this!

**Comment by savemeaspark** [comment]
I believe I have isolated the code for this and will be submitting an update momentarily. 👍
