### ISSUE TITLE
New Achievement and Badge: Completed Tutorial. 

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8612]
A new achievement and badge are ready to be implemented! This should be received when a player completes the tutorial after they sign up. The badge image and the name/mouseover text for the user achievement page can be found here: 

https://trello.com/c/Uz5cwCgk/15-completed-tutorial-badge

**Comment by CutTheCode** [comment]
Hello, I want to help with this and still trying to figure out what to do. This will be a basic achievement, right?

**Comment by khipkin** [comment]
@CutTheCode My guess would be yes.

**Comment by mczuchnowski** [comment]
Clarification needed: what does "complete the tutorial" actually mean? I see some tutorial- and tour-related fields in the schema, but they don't seem to change when I click around the site as a newly created user (all tutorial-related fields seem to be set to `true` right away after creating a new user). The badge kinda suggests a movie player and there are in fact some tutorial videos, but in the static part of the site.

**Comment by guyguy2001** [comment]
I believe this should not be "finished the 5 step tutorial", but "have seen all the tutorial snippets all over the site". The first option wouldn't have a sense of accomplishment, nor something you can work towards. But the second one makes the player search all over the site, and learn everything there is to it.

**Comment by librarianmage** [comment]
@CutTheCode Are you still planning on working on this?

**Comment by librarianmage** [comment]
> I believe this should not be "finished the 5 step tutorial", but "have seen all the tutorial snippets all over the site". The first option wouldn't have a sense of accomplishment, nor something you can work towards. But the second one makes the player search all over the site, and learn everything there is to it.

@beffymaroo or @lemoness, would you be able to clarify?

**Comment by lemoness** [comment]
I think that idea has potential! We'd just need to clarify where all the
tutorial pieces are. I'd like it to be a separate badge, though, because
part of this badge's purpose is to give users an easy win that introduces
them to the achievement system.

Regardless, this should be "on hold" until the redesign is finished, so I'm
updating that now.

**Comment by librarianmage** [comment]
Should this still be on hold?

**Comment by lemoness** [comment]
I've updated the labels on this issue!

**Comment by lemoness** [comment]
This will be revisited in the future after some additional tutorial changes, but I'm closing it for now until we decide what angle to take.
