### ISSUE TITLE
New Achievement and Badge: Joined a Challenge

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8613]
A new achievement and badge are ready to be implemented! This should be received when a player participates in their first Challenge. The badge image and the name/mouseover text for the user achievement page can be found here: 

https://trello.com/c/rBBuCJWR/2-joined-a-challenge-badge

**Comment by kvsm** [comment]
Can I pick this one up?

**Comment by Alys** [comment]
@kvsm Yes, thanks!

**Comment by kvsm** [comment]
Just rethinking the logic to simplify the implementation of this one:

- When a user joins a challenge, they should be awarded this achievement if they don't already have it.

Is that accurate? Any case where that doesn't hold?
