### ISSUE TITLE
New Achievement and Badge: Shared Avatar to Social Media

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8616]
A new achievement and badge are ready to be implemented! This should be received when uses the Share feature to share their avatar on social media. The badge image and the name/mouseover text for the user achievement page can be found here: 

https://trello.com/c/g5SjXob9/16-shared-avatar-on-social-media-badge

**Comment by cailinglu** [comment]
~~I can work on this one :)~~

~~But I'm not sure that it falls into any of the current achievement categories . . . I'm only positive it doesn't belong in the 'seasonal' category! Anyone else have an opinion?~~

Edit: Haven't made much progress on this one. If someone else wants to work on this, go right ahead!

**Comment by khipkin** [comment]
Seems like a basic achievement to me. :) it's not seasonal, and users can earn it at any time, so it's not special/rare/one-time-only.

**Comment by mczuchnowski** [comment]
Just to clarify: this should only apply to sharing via the AddThis plugin that resides on the foreground of the avatar (which by the way has some styling issues and bubbles up clicks to the avatar itself, toggling you between tasks and avatar settings) and ignore all the other sharing contexts, like footer and modals?

**Comment by bensenberner** [comment]
It looks as if the avatar sharing functionality has been removed, correct? When I hover over my avatar all I see is my name

**Comment by mczuchnowski** [comment]
@bensenberner you probably have some form of ad blocking which hides this button. I had to disable Ghostery and uBlock Origin to see this.

**Comment by lemoness** [comment]
We don't have this right now, so I'm closing this ticket until we decide how to to handle sharing again.
