### ISSUE TITLE
Money not being subtracted from purchases

### ISSUE THREAD

**Issue by jlawhorn** [HabitRPG/habitica#862]
I just bought several hundred gold worth of items without the gold being subtracted.

**Comment by lefnire** [comment]
does this still happen, or was it an isolated case?

**Comment by jlawhorn** [comment]
I haven't been able to duplicate. I have had similar bugs with hatching positions (I could use one potion on more than one egg), but not in the past month. It seems to have been related to the ajax not keeping up with the UI.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
