### ISSUE TITLE
New Achievements and Badges: Personalized X Tasks

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8621]
These new achievements and badges are ready to be implemented! These should be received when a player personalizes the number of tasks indicated by each badge. The badge images and the names/mouseover text for the user achievement page can be found here: 

https://trello.com/c/3emx3xCj/14-personalized-x-tasks-badges

**Comment by CutTheCode** [comment]
I would like to help with this

**Comment by kvsm** [comment]
Pardon my ignorance, but what does it mean to 'personalise' a task?

**Comment by khipkin** [comment]
I would also like clarification on this. For example: Does creating a task with values in optional fields count as "personalizing" a task?

**Comment by librarianmage** [comment]
Is this "create / edit" tasks?

**Comment by lemoness** [comment]
Yes, this happens when you create/edit a task!

**Comment by lemoness** [comment]
Note, though, that creating a task and then editing that same task does not count. They should count separate instances only.

**Comment by TNychka** [comment]
Hey! I can take a look at this!

**Comment by saraolson** [comment]
Staff are looking at implementing new user achievements, so we're putting this issue on hold for now.
