### ISSUE TITLE
Quest XP Reward Error

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8622]
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 25f0d3d9-fab3-4ac3-b09a-fd03a9e9e9fa
  * Browser: Chrome (latest)
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

If you complete a quest that puts your XP over leveling up it won't level you up until you complete another event.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

![bug](https://cloud.githubusercontent.com/assets/22421733/24486637/c3d19ce6-14d0-11e7-9583-452d7f851617.png)

**Comment by Alys** [comment]
Thank you but that is a known problem: https://github.com/HabitRPG/habitica/issues/2433

We have a guild within Habitica for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.
