### ISSUE TITLE
Bulk feeding Pets does not always deduct Milk.

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8624]
`SPOILERS AHEAD`

###  General Info
  * Browser: Opera
  * OS: Javascript using AJAX

### Description
When feeding pets through an API call, your food is not always deducted. I had 81 milk before I bulk feed all my Gen 1 White Type Pets. I now have 63 milks despite all my Gen 1 pets are feed.

#### Console Errors
No errors return!
They just like the food and grew into mounts.

**Comment by librarianmage** [comment]
Were you able to reproduce this, @cTheDragons?

**Comment by cTheDragons** [comment]
I haven't tried it since posting the bug report but yes, it was repeatable.

**Comment by bensenberner** [comment]
@cTheDragons 
- How many Gen 1 White Type pets did you have? I assume more than 18?
- What do you mean when you "bulk fed" them? Did you call the feed API many times in rapid succession? Would you mind posting a snippet of the code you used to perform the bulk feed?

**Comment by cTheDragons** [comment]
I had all of them available. So that is 9 in total. However I was feeding them only one at a time.

Regarding the Bulk Feed, yes I was calling the API multiple times. I have posted by (alpha) code in this [Repository](https://github.com/cTheDragons/Habitica-Bulk-Feed).

**Comment by cTheDragons** [comment]
Hi all! I have updated my code now, so you will need to view this [commit](https://github.com/cTheDragons/Habitica-Bulk-Feed/commit/fa7a0c4658436eef921dd1027e9167b82d186a45) to see the original. 

With the latest [code](https://github.com/cTheDragons/Habitica-Bulk-Feed) I have determine if you feed the pets in serial it works well. (Food is deducted as expected).

**Comment by lemoness** [comment]
@cTheDragons Hi there! Is this still an issue?

**Comment by cTheDragons** [comment]
I haven't tried it recently. My code now does everything serially which avoids it (though very slow). I could pull out old code and test if you wish.

**Comment by lemoness** [comment]
No, I think that's okay! I'll close it for now, but we can always reopen if needed.
