### ISSUE TITLE
*DELETE*

### ISSUE THREAD

**Issue by Paolo-Oliverio** [HabitRPG/habitica#8625]
*DELETE*

**Comment by Alys** [comment]
@Paolo-Oliverio Just as a note, in case you have other bugs in future, we have a guild within Habitica for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that. :)
