### ISSUE TITLE
approved Group Plans task gives XP,GP,MP, then subtracts it, then re-gives it

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8627]
When a complete Group Plan task requiring approval is approved, and the user who completed the task syncs, they see notifications for XP, GP, MP being given, then notifications for the same amounts being taken away, and then a third set of notifications for the same amounts being given again. They end up with the right stats but it looks buggy.

It's possible that this does not happen every time but in my recent testing it's been consistent.

Steps to reproduce:

1. Join a group plan
2. Claim a task requiring approval
3. Complete the task
4. Just before the leader approves the task, sync to be sure there's no pending notifications for XP, etc
4. Wait for the leader to approve the task
5. Sync. You'll see notifications for XP, GP, and MP being gained and at the same time notifications for the same amounts being lost.
6. Sync again. You'll see notifications for XP, GP, and MP being gained.

**Comment by Yutsuten** [comment]
I think it is related to #8582, I'll check it...

**Comment by Yutsuten** [comment]
I guess this issue can be closed now.
