### ISSUE TITLE
Cannot login using Firefox on Windows 7

### ISSUE THREAD

**Issue by DaveLillethun** [HabitRPG/habitica#8630]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: In which app is Settings->API? My browser? My OS? Neither seems to have it... Where is this?
  * Browser: Firefox 52.0.1
  * OS: WIndows 7 Professional SP1

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

I was able to log in and create an account find the other day using my work computer (Firefox on MacOS), but when I tried to log in from my main personal computer (Firefox on Windows 7), clicking on the "Enter Habitica" button on the main page doesn't do anything.

I am running Windows 7 Professional SP1 (all updates current as of 3/30/2017), and using Firefox 52.0.1 (latest version as of 3/30/2017). I disabled all add-ons on Firefox except LastPass (without which I couldn't log in to Haitica or GitHub) and I have no plugins except the two built-in ones (OpenH264 Video Codec and Widevine Content Decryption Module).

Reproduce:
1. Go to https://habitica.com/static/front
2. Click on "Enter Habitica" button (in the upper-right corner of the page)

Expected:
A login window would be displayed (or barring that, an error message saying why it's not working)

Actual:
Nothing happens.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

On page load, the following warning appear:
<source> element has no “src” attribute. Media resource load failed.  front
All candidate resources failed to load. Media load paused.  front

On "Enter Habitica" button click, no additional errors appear.

**Comment by paglias** [comment]
Can you try going to https://habitica.com/static/clear-browser-data and follow the instructions there? Let us know if it works afterwards

**Comment by DaveLillethun** [comment]
Hi Matteo,
That link did not help, but then I did a hard reset of all my Firefox
settings (basically setting it back fresh as if I had just downloaded it).
The full reset seemed to fix everything!

Thanks for your help.

- Dave



-----------
Dave L.

**Comment by Alys** [comment]
@DaveLillethun Thanks for letting us know!

If you experience any other bugs, please report them in the Report a Bug guild from Social > Guilds in the website and mobile apps, or from the website's Help menu. You can start reporting a bug there with a relatively brief message - just enough to explain the problem. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, you'd be advised of that by a moderator or staff member (Habiticans who have dark blue or purple names).
