### ISSUE TITLE
flagged chat messages need to remain visible to the person who posted them

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8639]
When a chat message is flagged by two players or by one moderator, the current behaviour is:
- the message is hidden from the player who posted it **(this needs to change)**
- the message remains visible to moderators
- the message is hidden from all other players

The desired behaviour is:
- **the message remains visible to the player who posted it**
- the message remains visible to moderators (as currently)
- the message is hidden from all other players (as currently)

The player who posted the message should see no indication that it has been flagged.

_FYI, this is a change that moderators have discussed and decided is desirable. In most cases, we'll be explaining to the poster that their message has been hidden from other users and explain why, as we do now. In rare cases though, it's best that the user doesn't realise their message is hidden._

**Comment by librarianmage** [comment]
I can take a look!

**Comment by Alys** [comment]
@MathWhiz Cool!
