### ISSUE TITLE
Login/Register pop up not working for non-Facebook users

### ISSUE THREAD

**Issue by ourania** [HabitRPG/habitica#864]
When clicking on the "Login/Register" button, the popup that comes up only has the option to login via Facebook.  Clicking on the Login or Register tab at the bottom of the popup does nothing and displays nothing.

![HabitRPG Gamify Your Life](https://f.cloud.github.com/assets/4263756/429876/51e52458-ae55-11e2-8e54-2cfc0529291e.png)

Refreshing does nothing. Tried on both Chrome and IE, doesn't work on either one.

Any tip for this? Is this a known issue?

**Comment by aopelts** [comment]
Same issue. Tried Safari, Chrome and Firefox.

**Comment by lefnire** [comment]
Oh shoot, the [component views](https://github.com/lefnire/derby-auth/blob/master/components/index.js) from derby-auth aren't being displayed! When I do a `git bisect`, it seems a change introduced after Unroll-Me/derby#master https://github.com/Unroll-Me/derby/commit/1ad8535015cc73ab1d30f466a692bb5f455a24cb is preventing derby-auth's library/component view inclusions (I can't figure out which commit). @SLaks, any thoughts jump to mind? Have the way library components are handled been changed in your derby fork?

**Comment by SLaks** [comment]
All of the commits after that are just pulled from codeparty/derby (except for the Windows path fix, which is unlikely to be causing this issue).

The merge commits are probably messing with your `bisect`.

I don't know what the problem might be.

**Comment by lefnire** [comment]
Noted. Kinda a bummer those folks keep their commits local and push weeks
later, makes it quite difficult to bisect. Anyway, thanks - will dig

**Comment by SilviaDGregorio** [comment]
Same, i cant login >_<

**Comment by lilgoldfox** [comment]
same, have tried multiple browers/machines. is there an alternate way to login?

**Comment by lefnire** [comment]
No other way in, and not a browser issue - recent Derby changes caused some
issues, and due to commit push staggering I'm having trouble isolating the
breaking changes. This is an emergency ticket and I'm working on it asap

**Comment by SLaks** [comment]
For now, you should probably revert to an older Derby (you can add a commit hash in `package.json`)

**Comment by lefnire** [comment]
https://github.com/lefnire/derby/commit/efe6980524af4520c44944a67668ea3d250b4769 . I wanted to revert to an older derby, but what happened is this. For yours and my changes, we push shortly after we commit. On their side, they often push many commits all in batch weeks after committing (they just kept them local till then). The problem then is the history isn't sequential in the way we've been working with the repo. It appeared there were some racer / derby changeset dependencies that were broken if I simply reverted to an older commit. Anyway, those are the changes that broke - I'll investigate soon

**Comment by SLaks** [comment]
Problems reverting to an older version may be coming from Tracks.

Try explicitly depending on a version of Tracks that doesn't include the async commits.

(and make sure Derby doesn't get its own copy)

**Comment by lefnire** [comment]
`"tracks": "git://github.com/Unroll-Me/tracks#master"` then? Looks like the issue was https://github.com/codeparty/derby/pull/249 after all!

**Comment by lefnire** [comment]
Phew, what perfect timing for @enjalot's PR. Life saver, we're back guys! Thanks for the suggestions @SLaks !

**Comment by ourania** [comment]
Thank you guys for working on this! Nice job! :Db
