### ISSUE TITLE
Automatic Allocation of attribute points cannot be switch on / off

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8641]
On the User > Stats page, the checkbox for turning Automatic Allocation on and off doesn't save the user's choice.

Steps to reproduce:

1. Use a database update command to set this: `"preferences.automaticAllocation": true`
2. Sync the website and confirm that the "Automatic Allocation" checkbox is on
3. Untick the "Automatic Allocation" checkbox.
4. Observer that a sync occurs (the blue sync line appears) and the checkbox is still unticked afterwards.
5. Use a database find command to see that your setting change was NOT saved - this is still showing: `"preferences.automaticAllocation": true`
6. Sync the website. Observer that the checkbox becomes ticked.

The same thing happens in the opposite direction:

1. Use a database update command to set this: `"preferences.automaticAllocation": false`
2. Sync the website and confirm that the "Automatic Allocation" checkbox is off
3. Tick the "Automatic Allocation" checkbox.
4. Observer that a sync occurs (the blue sync line appears) and the checkbox is still ticked afterwards.
5. Use a database find command to see that your setting change was NOT saved: `"preferences.automaticAllocation": false`
6. Sync the website. Observer that the checkbox becomes unticked.

I think this bug  was introduced in https://github.com/HabitRPG/habitica/commit/98c019a0b658df1fb5f0c6db5b09b379d6cb58e2 ("Upgrade lodash to v4 and lint more files") because I can replicate it in a local install with that commit but not with the one before it (https://github.com/HabitRPG/habitica/commit/ef02e595908bcafb9b15c95383a125293f636e69).

### What to do if this happens to you

Go to the [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac) guild (from Help > Report a Bug on the website or from the Guilds > Public Guilds on the mobile app) and state whether you want automatic allocation to be on or off. An admin will set that for you. If you need attribute points to be unallocated, say that as well.

**Comment by TNychka** [comment]
Is help still needed on this task? I'm available to give it a go if needed.

**Comment by Alys** [comment]
@TNychka Please go ahead! Thanks! It might turnout to be #rom something weird that lodash is doing so if you can't find a cause don't be afraid to ask questions.

**Comment by TNychka** [comment]
I've narrowed it down to something weird that lodash is doing. User.preference.automaticAllocation does not exist in users by default and It looks like when the set method is called, if the element doesn't already exist in the user's info, then it will not be created. So because User.preference.automaticAllocation doesn't exist, and lodash won't create it, the user autoAllocate preference is never set. 
I have a couple solutions I'm going to try out to see what works.

A little more info in case someone else wants to take a look:
Lodash _baseset.js at line 18 is where the allocation fails. probably at assignValue on 41. Will investigate further.

**Comment by TNychka** [comment]
@Alys , the pull request was merged. I assume I messed something up so it didn't auto close this issue, but this task is done. Just a heads up!
