### ISSUE TITLE
subscription page is inaccurate for cancelling Google Play and iTunes subscriptions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8642]
When a player has a subscription they created through Google Play or iTunes, it is not possible for them to cancel the subscription from inside Habitica. They have to go to Google Play or iTunes to cancel it there. 

However there is no indication of that when they visit the website's subscription page - what they see is in the screenshot below. If they click the cancel button, they get an error: `{"success":false,"error":"NotFound","message":"Not found."}`

The subscription screen must be changed so that if the user's `purchased.plan.paymentMethod` is `Google` or `Apple` then there is no "Cancel Subscription" button. In the place where the button was, there should be one of these messages (depending on whether they've used Google or Apple):

**Please go to the "My apps & games" > "Subscriptions" section of the Google Play Store app to cancel your subscription or to see your subscription's termination date if you have already cancelled it. This screen is not able to show you whether your subscription has been cancelled.**

**Please follow [Apple’s official instructions ] (https://support.apple.com/en-us/HT202039) to cancel your subscription or to see your subscription's termination date if you have already cancelled it. This screen is not able to show you whether your subscription has been cancelled.**

![image](https://cloud.githubusercontent.com/assets/1495809/24595030/fab343b0-1875-11e7-8201-cacb0cabac89.png)

**Comment by kvsm** [comment]
Ok if I take a shot at this? Shall I hold off until messages are finalised?

**Comment by Alys** [comment]
@kvsm You'd be welcome to start now! Thank you! If you get to the point when you're ready to do a pull request and we haven't finalised the words yet, post a message here asking us about it. Although even after you've done a pull request it's easy to update it with a wording change.

**Comment by kvsm** [comment]
Great, the work is already done so I will submit the PR later and leave it for review for the time being. :)

**Comment by kvsm** [comment]
Ok, submitted the PR. Just out of interest, it occurred to me that iTunes/Play must provide some kind of callback to let you know when a user subscribes - do they not do the same when they cancel?

**Comment by Alys** [comment]
@kvsm I've updated the top post to change the text for the Apple cancellation instructions. The Google text has not changed.
