### ISSUE TITLE
when ex-subscriber joins group plan, they lose Mystic Hourglasses and Mystery Items

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8643]
If a user has previously had a subscription and has unused Mystic Hourglasses or unclaimed Mystery Items, they lose them when they join a guild or party that has a group plan.

Steps to reproduce:

1. Give a user a gift subscription that terminates in the past. Example:
```
    "purchased": {
        "plan": {
            "quantity": 1,
            "extraMonths": 0,
            "gemsBought": 42,
            "mysteryItems": [
                "head_mystery_201703",
                "armor_mystery_201703"
            ],
            "consecutive": {
                "count": 12,
                "offset": 0,
                "gemCapExtra": 20,
                "trinkets": 4
            },
            "customerId": "Gift",
            "dateCreated": "2016-04-01T01:00:00.000Z",
            "dateUpdated": "2016-04-01T01:00:00.000Z",
            "dateTerminated": "2017-04-01T01:00:00.000Z"
        }
```
2. Ensure that:
   - the user has one or more Hourglasses (`purchased.plan.consecutive.trinkets`)
   - the user has unclaimed Mystery Items (`purchased.plan.mysteryItems`) 
3. Cause the user to cron, resulting in most of the subscription details being removed (cron recognises that the subscription is finished and needs to be terminated). Data like this remains (note that there's no `customerId`):
```
    "purchased": {
        "plan": {
            "paymentMethod": null,
            "planId": null,
            "customerId": null,
            "dateCreated": "2016-04-01T01:00:00.000Z",
            "dateUpdated": "2016-04-01T01:00:00.000Z",
            "dateTerminated": "2017-04-01T01:00:00.000Z",
            "consecutive": {
                "trinkets": 4,
                "gemCapExtra": 0,
                "offset": 0,
                "count": 0
            },
            "mysteryItems": [
                "head_mystery_201703",
                "armor_mystery_201703"
            ],
            "gemsBought": 0,
            "extraMonths": 0,
            "quantity": 1
        }
```
4. Observe that the `trinkets` and `mysteryItems` are still present (which is correct).
5. Invite the user to a guild that has a group plan and make the user accept.
6. Observe that `trinkets` are set to zero and `mysteryItems` are deleted (both incorrect):
```
    "purchased": {
        "plan": {
            "owner": "98089587-1bbe-4de2-92d3-0bbe76513a3f",
            "additionalData": null,
            "nextBillingDate": null,
            "nextPaymentProcessing": null,
            "planId": "group_plan_auto",
            "customerId": "group-plan",
            "dateUpdated": "2017-04-03T10:51:24.250Z",
            "paymentMethod": "Group Plan",
            "dateTerminated": null,
            "lastBillingDate": null,
            "dateCreated": "2017-04-03T10:51:24.247Z",
            "consecutive": {
                "trinkets": 0,
                "gemCapExtra": 0,
                "offset": 0,
                "count": 0
            },
            "mysteryItems": [],
            "gemsBought": 0,
            "extraMonths": 0,
            "quantity": 1
        }
```

Relevant code: 
1. the user model's [`isSubscribed` function](https://github.com/HabitRPG/habitica/blob/c23062f87e706a80644d2db6f8d4dd3c4f85a917/website/server/models/user/methods.js#L16-L21) correctly recognises that the user does not have a subscription because there's no `plan.customerId` 
2. the `addSubToGroupUser` function correctly [sets the **default** `plan` object to have no `trinkets` or `mysteryItems`](https://github.com/HabitRPG/habitica/blob/c23062f87e706a80644d2db6f8d4dd3c4f85a917/website/server/libs/payments.js#L91-L103)
3. that function then does **not** examine the user to see if they already have values for `trinkets` or `mysteryItems` -- this is where the fix is needed
4. that function overwrites the user's `plan` object with the default `plan` object

Step 3 could be done by adding an `else` block after [this `if` block](https://github.com/HabitRPG/habitica/blob/c23062f87e706a80644d2db6f8d4dd3c4f85a917/website/server/libs/payments.js#L109-L135), to allow overrides for `trinkets` and `mysteryItems`.

**Comment by CooperFLe** [comment]
New to the project and not sure how everything is put together yet. Still trying to figure out how everything works together. 

Wouldn't the solution to this just be pulling out the plan.merge() call from the if statement and putting after the if statement so it merges that data no matter what? 

I am not sure how to test to make sure this is a valid solution.

**Comment by Alys** [comment]
@CooperFLe Sure, if that's guaranteed to not change any behaviour for the case that's currently covered by the `if` statement.

**Comment by CooperFLe** [comment]
Sorry, this is my first time attempting to contribute to an open source project. Not sure if I did all of that right...

**Comment by joe-salomon2** [comment]
I'd like to tackle this issue if it's open.

**Comment by Alys** [comment]
@joe-salomon Thanks! Please go ahead. Comment here if you have any questions or run into trouble.

**Comment by joe-salomon2** [comment]
@Alys, are there any instances where you would not want to have previous values of Mystery Items or Hourglasses retained on a new group subscription?

**Comment by Alys** [comment]
@joe-salomon Never. When a player has Hourglasses or Mystery Items, they should always keep them.

**Comment by TheHollidayInn** [comment]
I'm pretty sure we have a unit test covering this. So, starting at the unit tests would be a good place.

**Comment by joe-salomon2** [comment]
Actually the unit tests didn't cover this case. I'll update the tests as well though.

**Comment by TheHollidayInn** [comment]
This is the test that checks: https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/unit/libs/payments/group-plans/group-payments-create.test.js#L445 .
