### ISSUE TITLE
Golden Rock Mount Sprite Fix

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8647]
The body sprite for the Golden Rock Mount currently has a stray pixel some distance from the rest of the body. The image attached to the Trello card linked below has been corrected to remove the stray pixel and has the correct filename.

https://trello.com/c/lduSl5jU/17-corrected-golden-rock-mount-body-sprite

**Comment by CooperFLe** [comment]
I'm working on this one :) Replaced the file, but the stray pixel is still present. Working on why right now.

**Comment by SabreCat** [comment]
Fixed in #8650, merged by way of one of our content branches.
