### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Natanji** [HabitRPG/habitica#865]
Hi,
I cannot login to HabitRPG from my Desktop computer. I was successfully logged in from my laptop and stay logged in there. I cleared cookies from the Desktop but that doesn't help. I don't get any kind of error message during login, but I'm simply stuck with the "Anonymous" test account and don't get into my own account. Firefox user here.

**Comment by lefnire** [comment]
see https://github.com/lefnire/habitrpg/issues/825 for the deets, you'll be the opposite browser swap. make sure your cookies are cleared "for all time"

**Comment by Natanji** [comment]
What do you mean, "opposite browser swap"?
I don't know what you mean by clearing cookies "for all time" (I cannot find such an option, but maybe that's because I'm on a localized version of Firefox). I selected all the cookies of habitrpg.com and deleted them. How is that not enough, and what do I have to do instead?

**Comment by lefnire** [comment]
can you try another browser and see what happens?

**Comment by Natanji** [comment]
Same thing. In Chrome it tells me that a user with that name doesn't exist. I can perfectly fine login with the username on the community site/forums though (it's Natanji, I also tried lowercase).

**Comment by Natanji** [comment]
Can someone please re-open this bug? It is _not_ fixed. I also get other weird behaviour: like the Login/Register button still being visible on my Laptop (where I am logged in), and no Party button (just reached level 3). It seems to me like my account was not properly registered; I registered while there were database problems, so could someone look into that and see if my account perhaps is in a weird half-created state right now?

**Comment by lefnire** [comment]
Closed this one because it's a duplicate of #825, not because it's solved.
I'll follow up there
