### ISSUE TITLE
avatar transformation buffs no longer give the caster an achievement (Snowball, Shiny Seed, Seafoam, Spooky Sparkles)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8658]
When you cast a [transformation buff](http://habitica.wikia.com/wiki/Transformation_Items) on a party member, both you and they are meant to get the associated achievement. As the Bailey message from 4/6/2017 says, "Throw a Shiny Seed at your friends and they will turn into a cheerful flower until their next cron! ... Plus, you and your pal will both receive the Agricultural Friends badge!"

However at the moment, only the person you are casting it on gets the achievement.

This applies to all four transformation buffs: 
- Shiny Seed (`shinySeed`)
- Spooky Sparkles (`spookySparkles`)
- Seafoam (`seafoam`)
- Snowball (`snowball`)

The relevant code starts here: https://github.com/HabitRPG/habitica/blob/13865bcf49ccb0f191dbc0495e20a7cc35db5a6e/website/common/script/content/spells.js#L271-L272

**Comment by mandyzhou** [comment]
The achievement descriptions also indicate that only the recipient of the transformation buff gets the achievement (e.g., "Got snowballed x times by party members."), so those descriptions would need to be updated as well (though is it possible that the current behavior is as intended, and there was an error in the Bailey announcement?).

**Comment by CooperFLe** [comment]
@mandyzhou I'm trying to find past announcements to see if they made similar announcements indicating the same intended behavior. I can't find any though, maybe @Alys can check to see?

**Comment by mandyzhou** [comment]
@CooperFLe Good idea to look at previous Bailey announcements! Here's what I've found (not all of the transformation item announcements mention the achievements):

10/6/2016 and 10/3/2014: "If you have Spooky Sparkles cast on you, you will receive the "Alarming Friends" badge!"

12/30/2016 and 12/31/2014: "Anyone hit with a snowball earns the Annoying Friends badge."

These seem to support my theory that the bug was in the latest Bailey announcement, not in the code.

**Comment by Alys** [comment]
Hmmm. I was sure the achievement used to be given to both caster and receiver but I might have been thinking of the greeting cards.

I'll ask Lemoness if she wants the Bailey or code changed. Sounds like it will probably be the Bailey.  On hold until I hear back since she has commitments this week. Thanks @CooperFLe and @mandyzhou !

**Comment by SabreCat** [comment]
I'm pretty sure the transformation items have only ever given the achievement to the target. It is indeed the greeting cards that work two-way. So the Bailey was in error. Certainly a possibility to change if we decide we want the two things to work similarly, though!

**Comment by Alys** [comment]
The Bailey message will be changed to the text below when the PR is deployed to the website (it might be in a few days). The wiki copy of the Bailey can be edited now. There's a screenshot in the PR: https://github.com/HabitRPG/habitica/issues/8679

"Throw a Shiny Seed at your friends and they will turn into a cheerful flower until their next cron! You can buy the Seeds in the <a href='/#/options/inventory/seasonalshop'>Seasonal Shop</a> for gold. Plus, they will receive the Agricultural Friends badge!"
