### ISSUE TITLE
Missing confirmation button for "Leave party" button

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#866]
Hey there,

I wanted to add a new guy to my party "Fitocraty". The browser didn't completely load the page, and just when I tried to click on the field to add the new user id, it clicked on the "Leave party" button.

I'm now out of the party I created, very stupid. A confirmation window would be very appreciated.

Thanks for your understanding
Cordially

**Comment by AdrienLemaire** [comment]
Edit: I got re-invited in the party by another member. I don't think there was any advantage to be the creator of the group (no management tools), so no harm done.

I know you guys are working hard and overbusied with other tasks, keep up the hard work :) Thank you very much !

**Comment by lefnire** [comment]
Yeah, party leader doesn't do anything just yet. Making a self note for
"confirm leaving party"

**Comment by paglias** [comment]
Fixed
