### ISSUE TITLE
Task Alias field is not visible in Rewards

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8668]
When you edit a Reward, you cannot see the Task Alias field. You should be able to see it (and modify it).

You can see the Task Alias field when editing Habits, Dailies, and To-Dos, so they are all working correctly.

The Task Alias field is part of the Advanced Options, so this bug has probably happened because all Advanced Options have been hidden for Rewards. If so, the fix would be to un-hide the Advanced Options heading and Task Alias field but hide all the other advanced options that aren't relevant for Rewards.

This applies only to tasks in the user's own tasks list. The Task Alias field should not be visible when editing a challenge task or a group plan task.

**Comment by iamakidilam** [comment]
Hello, I'm a newbie and would like to contribute to the project. For testing out the application, should I just create an account or is there any other way? Can anyone help me in setting up the stuffs?

**Comment by aldogint** [comment]
can i contribute to this issue?
