### ISSUE TITLE
Flying pig sprite overlaps with character

### ISSUE THREAD

**Issue by kevinalai** [HabitRPG/habitica#867]
I just got a cotton candy blue flying pig, and it's a bit higher on the screen than the other pets, in a way that overlaps a bunch more with my character sprite and weapon.
![flyingpig](https://f.cloud.github.com/assets/1063921/436667/8b2cc12e-b064-11e2-91d4-645794b16ffb.jpg)

I don't know if that's intentional, but it seems sort of strange that it's different from the other pets.

**Comment by lefnire** [comment]
It's intentional, since it's flying. We just need to do something about
sprite overlap. I think we're gonna do a second avatar-box redesign when we
hit mounts, in the near future

**Comment by Shaners** [comment]
Avatar box redesign discussions were happening around here: https://github.com/lefnire/habitrpg/issues/107#issuecomment-14367922
Feel free to add your opinion to the mix. I don't think we had a clear winner so We'll have to put up a poll at some point.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
