### ISSUE TITLE
New Groups Static Page Needed

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8674]
The static page that tells people about our paid group plan options is out of date, as can be seen here: https://habitica.com/static/plans

This page should be updated so that it tells people about the current group plans and lets them sign up for one, while also having places that they can learn more about family plans and enterprise plans.

Here is a template for the new page:

![image uploaded from ios](https://cloud.githubusercontent.com/assets/3494081/25058843/d5831af0-2132-11e7-8a2c-791cd762cb53.jpg)

The copy that should be included can be found on the main group plans page here: https://habitica.com/#/options/groups/group-plans

The enterprise plan button should send an email to vicky@habitica.com, and the family plan should collect email addresses in a .csv. Let me know if you need me to set up a form for the latter.

**Comment by yugensoft** [comment]
Can I take this on?

**Comment by Alys** [comment]
@yugensoft Sure! Thank you!

**Comment by yugensoft** [comment]
How should I deal with the existing Social->Group Plans menu link to https://habitica.com/#/options/groups/group-plans ? Shall I leave it as is, or make both Social->Group Plans and [Front]->Corporate Plans link go to the updated https://habitica.com/static/plans page?
Also should I rename the "Corporate Plans" tab text to "Group Plans"?

**Comment by yugensoft** [comment]
Also the "Get a group plan" button, which is "Create a new group" in the group-plans page, is using angular so this page won't be "static" anymore, so I need clarification on this.

**Comment by lemoness** [comment]
The Social > Group Plans menu link should still go to the in-game group
plans page. And yes, it should say "Group Plans" instead of "Corporate
Plans." Thanks so much for working on this ticket!

**Comment by Alys** [comment]
@yugensoft For this:

> Also the "Get a group plan" button, which is "Create a new group" in the group-plans page, is using angular so this page won't be "static" anymore, so I need clarification on this.

we might need to split up the Social > Group Plans page so that the second screen (the one where you can enter the details of your new guild) has a different URL. Then your button could link to it directly, assuming the user was already logged in, which I think is what Lemoness is wanting.

We should probably also put a note at the top of that page saying that it's for creating a NEW private guild, and that if the user wants to add a group plan to an existing private guild or party, they should go to that group and click it's "update" button. I've seen a few players confused about that and they create guilds they don't want. @lemoness Would that be okay? Would you like to suggest wording?

**Comment by lemoness** [comment]
I think that makes sense. Let's add the following sentence at the top of
the Social> Group Plans page:

"This page is for creating a brand-new Group Plan. To turn a previously
existing Private Guild into a Group Plan, simply go to your Guild and click
the "Upgrade" button in the upper left."

**Comment by yugensoft** [comment]
OK understood

**Comment by yugensoft** [comment]
I have 2 questions: what is meant by "Let me know if you need me to set up a form for the latter", does habitica have a google forms account or something?; and how should I deal with a click to the "Create a group" button on the static/plans page if the user is not logged in, e.g. should I make it go to authentication with a "after authentication redirect"?

**Comment by lemoness** [comment]
For the first question, Habitica can indeed set up an official Google form!

**Comment by yugensoft** [comment]
OK may Habitica please set that up then :)
As for the second question, I will proceed with the "authentication + redirect" solution unless interrupted. Everything else is done

**Comment by yugensoft** [comment]
Pull request is up, ready for review. 

The line https://github.com/yugensoft/habitica/blob/1e5c1400f089ccd489c545bc79a9d74b320901c6/website/views/static/plans.jade#L38 will have to be updated to match the google form when it is ready.

**Comment by lemoness** [comment]
The form for the link is here:
https://docs.google.com/forms/d/e/1FAIpQLSerMKkaCg3UcgpcMvBJtlNgnF9DNY8sxCebpAT-GHeDAQASPQ/viewform?usp=sf_link
Let me know if you encounter any issues with it!

**Comment by yugensoft** [comment]
OK it's done

**Comment by yugensoft** [comment]
Bump
