### ISSUE TITLE
negative clicks on group plans Habits are treated as positive clicks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8676]
When a player in a group plan claims a Habit that requires approval and clicks on the negative button, after approval has been given, the player is rewarded with XP, GP, etc and the Habit turns green, as if they'd clicked the positive button. This occurs for Habits that have both plus and minus buttons and for Habits with only minus buttons.

Steps to reproduce:
1. Group leader creates a Habit, sets it to have only the minus option and require approval. 
1. Leader assigns Habit to group member (or member claims it).
1. Member clicks the Habit's minus button. They see the usual notification that approval has been requested.
1. Leader approves the Habit.
1. Member syncs. They earn XP, GP, MP. The Habit turns green.

**Comment by yugensoft** [comment]
Can this be assigned to me?

**Comment by Alys** [comment]
@yugensoft Gladly! Thank you!

**Comment by yugensoft** [comment]
Hi, thanks for merging in my other issue PR, but please restore this one back to "help welcome", as didn't manage to work on it and I don't have time now, cheers.

**Comment by melarish** [comment]
What's the easiest way to apply a group plan in local? I found the purchased object in https://github.com/HabitRPG/habitica/issues/8677 but it seems mongo shell doesn't allow multi-line commands. is the only way to put that all on one line?

**Comment by melarish** [comment]
I could try adding a debug menu option to apply a group plan (in a separate ticket) - would that be okay and perhaps helpful to others?

**Comment by gwong5** [comment]
could @Moniarchy and i try our hands at this? or is this being worked on?
