### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by loldude101** [HabitRPG/habitica#868]
I searched for this issue but since I couldn't find an existing thread I am making my own. 

The issue of missing button has started a few days after the major design overhaul and at first I didn't think anything of it at the time but after a while I tried deleting caches/cookies to see if that will bring the old buttons back but nothing worked. When I hover over the "?" buttons it displays a check mark. This issue is consistent in my "Dailies", "Todos", and "Re-Roll" in "Rewards". 

I know I'm not alone in this matter. Is there anyways to fix this because it's now irritating me?

![27 28-Apr-13](https://f.cloud.github.com/assets/3129563/436693/7a0600b0-b067-11e2-9199-0e3a2a51a6cb.png)

~Thanks!

**Comment by lefnire** [comment]
assigning to @zakkain. It's unsupported unicode characters being used in the new design

**Comment by caycefischer** [comment]
Dang it that unicode is a real pain in the butt. @loldude101 what device/OS and browser are you using?

**Comment by loldude101** [comment]
I get this error when I browse the site from my iPhone, iPad, & Laptop from
anywhere (including home and school).

**Comment by JellyBean22** [comment]
#753 
Has been an issue for me for over a month now...
I'm not complaining! I'm just letting you guys know. I realise that it is by no means a priority :)

**Comment by lefnire** [comment]
All mobile devices I've tried, personally

**Comment by caycefischer** [comment]
FFF-

OK I'm going to find a webfont with good unicode support and end this for
good.

**Comment by StanLindsey** [comment]
This is happened my end as well. Even after force-refreshes.

**Comment by switz** [comment]
It's probably falling back on their devices to some font without those Unicode symbols. You might just have to add a common font at the end of the font-family.

**Comment by caycefischer** [comment]
There is no common system font that will suit us sadly (Android is mostly the culprit here, they don't have the common Arial MS Unicode), I'm going to use a custom symbol font (like fontello) as the common font for our icons.

**Comment by StanLindsey** [comment]
Its fine on my lubuntu machine, is apparent on my windows desktop. Can't we use a google webfont if not already? 

---

Posted From Mobile

**Comment by lefnire** [comment]
Yeah, I saw it in on windows 7, chrome and FF latest

**Comment by caycefischer** [comment]
We absolutely can, but the trick is finding one with the right unicode
support. So far, Deja Vu seems ​like the best bet—but we'd have to serve
the fonts ourselves. I'd prefer a hosted solution but google webfonts, by
and large, have pretty cruddy unicode support (case in point, we're
currently using Lato, which is a Google-hosted webfont and one of the
widest unicode supporting.)

**Comment by lefnire** [comment]
the more people i show habit and see this on their screen - the more i'm thinking this effects the majority of users. here's a quickfix i might deploy just to save our hides until we can get something working https://gist.github.com/lefnire/5528175, difference in appearance: http://gyazo.com/09740733f83eb14c854f66e4c9019745

**Comment by lefnire** [comment]
nope, same problem - i'm a shite csser

**Comment by switz** [comment]
Umm, the simple answer here?

``` css
.box {
  height: 10px;
  width: 10px;
  border: 1px solid #333;
}
```
