### ISSUE TITLE
achievements are sometimes invisible in the profile modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8686]
Sometime's a player's profile won't show the achievement badges. For example, the screenshot below was taken from a player who has these achievements:

```
    "achievements": {
        "ultimateGearSets": {
            "healer": false,
            "wizard": false,
            "rogue": false,
            "warrior": true
        },
        "challenges": [],
        "quests": {},
        "perfect": 2,
        "streak": 0
    }
```

![image](https://cloud.githubusercontent.com/assets/1495809/25178522/70c6f864-2549-11e7-9aa3-3c1a39472bf2.png)

All the examples I've seen of this have been with players who have only a few achievements but I've only seen a handful so that might be just a coincidence.

**Comment by khipkin** [comment]
Maybe the achievements code assumes some field on the user will be populated when it shouldn't? That would explain why this only seems to happen to users who have very new/empty accounts.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Has this been fixed?

**Comment by lemoness** [comment]
I haven't seen any instances of it, so I'm closing this ticket. We can always reopen in the future if necessary.
