### ISSUE TITLE
can't leave challenges from a private guild or party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8693]
If you join a private guild or party, then join a challenge in that group, then leave the group, you are then not able to leave the challenge.

It's because of [these two lines](https://github.com/HabitRPG/habitica/blob/91438aff904ed127bd8f60d349625da07ed2d16f/website/server/controllers/api-v3/challenges.js#L193-L194) in the API's `leaveChallenge` function, which prevent the challenge being left when you don't have permission to view the group. That's an important check to perform when you are joining a challenge but not when leaving a challenge you've been permitted to see in the past.

I suggest this bug be fixed by removing those two lines. I'll leave this as suggestion-discussion for a couple of days and then if there's no objections, mark it as help wanted.

**Comment by librarianmage** [comment]
Question: would this allow one to discover the ids of Challenges that they cannot normally see by attempting to remove themselves from random ids? I don't think that this would pose a security risk, but I was just wondering.

**Comment by Alys** [comment]
It would but I don't think it's important. The protections we have on viewing and controlling challenges will prevent them doing anything with the IDs. Good question though! It's always worth asking about possible security risks. I'd considered this when I logged the issue and should have written something about it then.

If others think it is a security risk, we could get around it by making these two error conditions return the same message:

    if (!challenge) throw new NotFound(res.t('challengeNotFound'));

    if (!challenge.isMember(user)) throw new NotAuthorized(res.t('challengeMemberNotFound'));

It's a little undesirable to have the second message not being accurate, but that's a lesser problem than users not being able to remove themselves from challenges from private groups that they've left. I see requests for help with that in the Bug guild regularly so it is something we need to fix.

**Comment by JoshSears** [comment]
@Alys If you believe its just the removal of those two lines, might I give it a go?  I would like to remove those in my local build, and then test.  Seems a simple enough fix....since you already found the problem!

**Comment by Alys** [comment]
@Dagrik That sounds great, thanks!

**Comment by JoshSears** [comment]
Tested first.  Problem was recreated successfully on first try, both in trying to keep the tasks and removing them as well.  Challenge on test acct was removed when challenge leader picked winner or deleted challenge.  Moving forward to test proposed fix.

**Comment by JoshSears** [comment]
Second test: Proposed fix.  Was able to leave a challenge after leaving a group.  If "Remove Tasks" was selected from leave option, challenge stayed displayed on the screen and the Join button is visible.  The join button gives and error and does not allow rejoining.  Upon reload, the challenge disappears.  The tasks are removed, however the Challenge Tag stayed present.  If "Keep Tasks" was selected, the challenge was removed immediately, and the tasks were kept on the task window.

@Alys , do we want to look into the task "refresh" immediately (remove itself) when "Remove Tasks" is clicked, just as it did when "Keep Tasks" is clicked?  Or move forward with this correction, since it fixes the core problem?

**Comment by JoshSears** [comment]
@Alys I will try to submit something this weekend with the fix, unless the differences noted need to be addressed.

**Comment by JoshSears** [comment]
PR submitted.
