### ISSUE TITLE
NaN Experience when you un-complete a task after Orb of Rebirth

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8695]
If you use an Orb of Rebirth and then while your Experience is still 0 and your level is still 1, if you untick a completed Daily or To-Do, your Experience becomes NaN:

![image](https://cloud.githubusercontent.com/assets/1495809/25313099/0bdd6530-286b-11e7-8e7d-341f393facfb.png)

![image](https://cloud.githubusercontent.com/assets/1495809/25313106/329f152e-286b-11e7-80a6-1b8f90df5bfa.png)

**The correct behaviour is that your Experience becomes a negative number. Your level will remain at 1.**

You can fix the problem by reloading, and your Experience will then be negative, as expected:
![image](https://cloud.githubusercontent.com/assets/1495809/25313453/80463df0-2872-11e7-8fdd-5560176b2a41.png)

_Reported by Kide (c37a4637-bb2b-4dea-a721-6df1e7571c46) in the Report a Bug guild._

EDIT 2017-06-24:

A related problem, reported by Donaithnen (189af1f9-6cba-4032-9a43-26880c1d6779) in the Report a Bug guild:

"When you use an Orb of Rebirth it takes you back to the Tasks page. If you then try to hit + on a Habit before doing anything else the message that pops up to say how much exp you got says "+NaN Exp". The gold part seems to work as expected. If you refresh the page it will then show that you did in fact get Exp, and any future clicks will show the proper value instead of the Not-a-Number error."

**Comment by MathWhiz** [comment]
Should it be negative?

**Comment by snowsignal** [comment]
I would love to get working on this! However, I was wondering where the script is that adds the experience. (I'm still figuring out the structure of this project)

**Comment by zachpanter** [comment]
habitica/website/common/script/ops/scoreTask.js

might be a good starting point!

**Comment by zachpanter** [comment]
The jade code initiating the change can be found at _habitica/website/views/shared/tasks/task_view/index.jade : lines 29-37_

and some of the javascript code that might be relevant is here:
_habitica/website/client-old/js/controllers/tasksCtrl.js: starting on both lines 41 and 134_

Hope that helps. I'll be taking a closer look after the workweek too!

**Comment by snowsignal** [comment]
Thank you!

**Comment by snowsignal** [comment]
Couldn't we have this problem fixed by removing the tick from the dailies when you use an orb of rebirth? Is there a specific reason why the orb of rebirth doesn't reset the dailies?

**Comment by Alys** [comment]
No, any Dailies you've already completed that day should stay completed. Dailies are typically things you do just once a day so if you've already done them before rebirthing, you shouldn't be made to do them again.

**Comment by Alys** [comment]
A related problem, reported by Donaithnen (189af1f9-6cba-4032-9a43-26880c1d6779) in the Report a Bug guild:

"When you use an Orb of Rebirth it takes you back to the Tasks page. If you then try to hit + on a Habit before doing anything else the message that pops up to say how much exp you got says "+NaN Exp". The gold part seems to work as expected. If you refresh the page it will then show that you did in fact get Exp, and any future clicks will show the proper value instead of the Not-a-Number error."

I've copied this to the top post.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment]
Is this still happening?

**Comment by Alys** [comment]
Both parts of this are fixed!
