### ISSUE TITLE
feature spike: kanban view.

### ISSUE THREAD

**Issue by awitherow** [HabitRPG/habitica#8696]
I would like to have a kanban view within habitica, specifically for my todo list, potentially also within dailies, as well as habits.

Theoretically speaking on an implementation idea now...

1. Object `todo` would have a new key value pair, something like `status`. It could be one of three string types: `'inbox', 'next', 'active', 'done'`.

2. `Todo List`visual column would have an extra icon-button next to the help view. Clicking it would open a 'kanban' view where the user could manage the tickets between columns provided (`'inbox', 'next', 'active', 'done'`).

3. Only todos (also potentially dailies, and habits) with the tag of `'active'` applied would do damage if not complete, but **extra damage** if not complete (to *reinforce the concept of not taking on too many things at a time*).

If anyone would like to pair with me on such a concept and integrate it into the application via PR, let me know! Would like to do this lean and beautiful.

**Comment by librarianmage** [comment]
This should probably be moved to the [Trello Board](https://trello.com/c/odmhIqyW/440-read-first-table-of-contents), where new features are discussed. The GitHub Issues area is generally for bug fixes and features that have been approved by the mods/admins.

**Comment by awitherow** [comment]
@MathWhiz great! Not clear to me how to add it as a ticket myself... I have added it as a feature improvement idea to https://trello.com/c/exaF7GiC/135-to-dos-v2-frozen-to-do-attack-to-do

**Comment by Alys** [comment]
@awitherow Thanks! That's a good card for it.

 We're part way through a project to improve the website so possible enhancements like this could be considered after that's finished.

**Comment by awitherow** [comment]
@Alys can you point me in the direction of some tickets I could help out with to speed up the potential future? :) 👍

**Comment by librarianmage** [comment]
Not @Alys, but here are some tips on how to search the [Issues](https://github.com/HabitRPG/habitica/issues) page:

* Issues that have the "[status: issue: help welcome now](https://github.com/HabitRPG/habitica/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+issue%3A+help+welcome+now%22)" label have been "accepted" for work
* Issues with the "[status: issue: in progress](https://github.com/HabitRPG/habitica/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+issue%3A+in+progress%22)" label have had a Habitican volunteer to work on it at some point
* Issues with the "[status: issue: on hold](https://github.com/HabitRPG/habitica/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+issue%3A+on+hold%22)" label are on hold until a future date (e.g. the website redesign)

Aside from these mutually exclusive labels, a couple other ones that may be useful are:

* [type: entry level coding](https://github.com/HabitRPG/habitica/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+entry+level+coding%22)
* [type: medium level coding](https://github.com/HabitRPG/habitica/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+medium+level+coding%22)

You can also combine labels in your search, such as:

* [status: issue: help welcome now + type: entry level coding](https://github.com/HabitRPG/habitica/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+issue%3A+help+welcome+now%22+label%3A%22type%3A+entry+level+coding%22)
* [status: issue: help welcome now + type: medium level coding](https://github.com/HabitRPG/habitica/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22status%3A%20issue%3A%20help%20welcome%20now%22%20label%3A%22type%3A%20medium%20level%20coding%22%20)

---

Best of luck with finding an Issue to take on! You can learn more [here](https://help.github.com/articles/searching-issues/)

**Comment by awitherow** [comment]
Awesome, thanks @MathWhiz .
