### ISSUE TITLE
Progression loss

### ISSUE THREAD

**Issue by Tryskel** [HabitRPG/habitica#870]
I became Level 2 saturday afternoon, and I see today that my status backed in time before the actions that permits me to leveling (HP 38/50, XP 140/150, lvl 1)

My todo list is up to date though, I kept access to the shop, and my character kept the Wooden Helmet I bought.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
