### ISSUE TITLE
iOS: app crashes when trying to add a reminder to a daily task

### ISSUE THREAD

**Issue by mareinna** [HabitRPG/habitica#8700]
### General Info
  * UUID: 4edd4865-3049-414b-a326-9747b3385ad8
  * Browser: iOS app v 1.7.2 (189)
  * OS: iOS for iPhone v 9.3.4

### Description
[//]: # Every time I try to add a reminder to a daily task in the iOS app, the app freezes, then crashes, and the reminder does not get saved. Posted to the "Report a Bug" guild, was asked to try uninstalling/reinstalling the app. Did that, it had no effect, problem persists. Old reminders are still active and working fine, I just can't save any new ones.

**Comment by librarianmage** [comment]
@mareinna You may want to send in the bug report to the email in the About -> Report a Bug area in the menu (if my memory serves me correctly), or in the HabitRPG/habitica-ios repository

**Comment by mareinna** [comment]
Thanks!

**Comment by paglias** [comment]
I'm closing because as pointed out by @MathWhiz these issues should go in the ios repo. Thanks!
