### ISSUE TITLE
Integration with todoist

### ISSUE THREAD

**Issue by antistic** [HabitRPG/habitica#871]
This would be pretty good, seeing as I'd much prefer using their todo system, and it's quite annoying having to enter tasks into more than one system.

Ideally I'd like it to monitor each task and treat them like habitrpg tasks, but if that's impossible they do have a "karma" system, and XP could be based on that. I do know they have an API.

**Comment by wizonesolutions** [comment]
Vote on Trello (and discuss there) :) https://trello.com/card/todoist/50e5d3684fe3a7266b0036d6/270
