### ISSUE TITLE
Push notifications are localized in the language of the sender

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#8718]
When push notifications are sent from p.e. a quest invitation, these are localized using the language of the sender and not the languages of the recipients.

**Comment by snowsignal** [comment]
I can work on this.

**Comment by Alys** [comment]
@JacksonCoder Thank you! Comment here if you have questions.

**Comment by librarianmage** [comment]
@JacksonCoder Are you still working on this?

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by lemoness** [comment]
@vIiRuS Is this still an issue?

**Comment by Alys** [comment]
It does still happen. I've updated the labels.
