### ISSUE TITLE
Changing the reset time of the Daily

### ISSUE THREAD

**Issue by zoukai957** [HabitRPG/habitica#872]
So I think this was a great idea and it sure has helped me alot but there seems to be one small bug in there. 
So it is working properly in the sense that if I change the time of the reset to past midnight I don't lose points if I don't complete a task by midnight... BUT if I have a daily to be not done on certain days, lets say sunday for example and it passes midnight on sunday the daily becomes something I have to do and I therefore lose points at the designated reset time.

For example...
Lets say I have a daily to eat pie everyday except on Sundays and I have a reset time of 2 in the morning. On sunday at midnight eating pie becomes something I have to do even though my reset time is 2 in the morning. I feel that these dailys should stay "don't have to do" until 2 in the morning if my reset time is set to 2 in the morning

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
