### ISSUE TITLE
clicking cancel subscription button twice causes subscription to terminate too early

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8721]
If you have a multi-month recurring subscription (3, 6, or 12 months) and **you click the cancel button twice instead of once**, the subscription terminates in one month instead of terminating at the end of the period you have paid for.

Steps to reproduce **correct** behaviour:

1. Create a 12 month subscription
2. Go to User Icon > Subscription
3. Click the cancel button and click the "ok" button on the connfirmation popup
4. Wait for the website to reload
5. Confirm that your subscription ends 12 months from today (correct behaviour)

Steps to reproduce **buggy** behaviour:

1. Create a 12 month subscription
2. Go to User Icon > Subscription
3. Click the cancel button and click the "ok" button on the confirmation popup
4. **Immediately** click the cancel button again and click "ok" again (i.e., **before** the website has reloaded)
5. Wait for the website to reload
6. Confirm that your subscription ends only 1 month from today (bug)

This could occur if the website is slow to reload and the user thinks that their first cancellation has not been successful.

<strike>One solution would be to disable the button after it has been clicked once. The disable has to last just until the page is reloaded because after the reload is finished it will be obvious that the subscription has been cancelled.</strike> EDIT: a better idea is below.

**Comment by Alys** [comment]
The same problem can also happen if you open the subscription screen in two tabs before you cancel the subscription. You can cancel it in one tab and be given the correct termination date (a year from today). You can then cancel it in the second tab and be given a new termination date of one month from today.

Disabling the button would not help in that situation so I think a better solution would be to adjust the server-side code that processes the cancellation so that it does not modify the subscription at all if the subscription already has a value for `purchased.plan.dateTerminated`.

I.e., if you attempt to cancel a subscription that already has a termination date, you would receive an error saying **"Your subscription has already been cancelled."**

If anyone has any better ideas for a solution, please post here!

**Comment by nnashwin** [comment]
I'd like to work on this.

**Comment by TheHollidayInn** [comment]
That would be great!

**Comment by librarianmage** [comment]
@ru-lai Are you still working on this?

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by lemoness** [comment]
@alys Do any of the descriptions in the original post need to be updated?

**Comment by Alys** [comment]
I've changed "Settings" to "User Icon" in the top post but everything else is still the same - I've just tested and it still works as described.
