### ISSUE TITLE
Task Re-Arranging Issues

### ISSUE THREAD

**Issue by SirLouen** [HabitRPG/habitica#8724]
* UUID: 99ccbddd-9e2c-42b1-a04c-78185183ed25
  * Browser: Chrome 57
  * OS: Windows 10 64bit 1704

### Description

I've found a bug in Habitica for a long time: When I arrange tasks click and dragging, regularly everything gets broken and tasks not only are not arranged but also sometimes they become disordered. 

To keep successfully re-arranging, I have to refresh (F5) and retry the rearranging process, and generally, it works. If I have to re-arrange like 6-7 tasks the probability of this bug/crash arising is about 90%. 

The best solution (at least for me) could be a button to arrange Tasks by the due date. Instead of having to manually rearrange tasks nearly every day this will solve this pain instantly. But since this is a feature, and this is only a bug report system, if at least the tasks could be manually re-arranged without crashes, or having to do two or three refreshes (F5) before having everything fully re-arranged, it would be great

#### Console Errors
No console errors found

**Comment by Alys** [comment]
We have this logged already in https://github.com/HabitRPG/habitica/issues/7645 and https://github.com/HabitRPG/habitica/issues/8500 so I'm closing this issue.

@SirLouen When you notice bugs, please report them first in the Report a Bug guild, which I can see you've already done for this one. As the new issue template here in GitHub says: "Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to." Following that advice prevents duplicate issues in GitHub,  and also saves your own time.

The website has a "Dated" tab for viewing To-Dos by due date.
