### ISSUE TITLE
currentPet remains even if tamed

### ISSUE THREAD

**Issue by madpink** [HabitRPG/habitica#8725]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: b0413351-405f-416f-8787-947ec1c85199
  * Browser: N/A
  * OS: Mac 10.12

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Pretty minor: Using the REST API, I fed a pet until it became a mount. It happened to be the pet currently chosen as "currentPet". Even though I no longer have this pet, it is still listed under ["items"]["currentPet"] and still is faithfully displayed at my avatar's side.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by librarianmage** [comment]
Hmm...

Relevant file: https://github.com/HabitRPG/habitica/blob/develop/website/common/script/ops/feed.js

Relevant code:
```javascript
function evolve (user, pet, req) {
  user.items.pets[pet.key] = -1;
  user.items.mounts[pet.key] = true;

  if (pet.key === user.items.currentPet) {
    user.items.currentPet = '';
  }

  return i18n.t('messageEvolve', {
    egg: pet.text(req.language),
  }, req.language);
}

module.exports = function feed (user, req = {}) {
  let pet = get(req, 'params.pet');
  let foodK = get(req, 'params.food');

// ... general errors removed

  let message;

  if (food.key === 'Saddle') {
    message = evolve(user, pet, req);
  } else {
    let messageParams = {
      egg: pet.text(req.language),
      foodText: food.text(req.language),
    };

    if (food.target === pet.potion || pet.type === 'premium') {
      userPets[pet.key] += 5;
      message = i18n.t('messageLikesFood', messageParams, req.language);
    } else {
      userPets[pet.key] += 2;
      message = i18n.t('messageDontEnjoyFood', messageParams, req.language);
    }

    if (userPets[pet.key] >= 50 && !user.items.mounts[pet.key]) {
      message = evolve(user, pet, req);
    }
  }

  user.items.food[food.key]--;

  return [
    userPets[pet.key],
    message,
  ];
};
```

Everything seems in order. Is there something that I am missing?

**Comment by librarianmage** [comment]
I would like to take care of this issue!

**Comment by SabreCat** [comment]
Sure! Did you spot what's going on, then?

**Comment by librarianmage** [comment]
Not yet, I was just requesting to fix it once I do so.

**Comment by librarianmage** [comment]
@madpink Can you attempt this again and post the output for each request? If possible, screenshots would also be greatly appreciated.

**Comment by madpink** [comment]
I tested again and it did not happen. At least part of the problem could've been the browser not fully refreshing... I will keep testing.

**Comment by librarianmage** [comment]
Hmm... as it hasn't been duplicated, should this just be marked as investigation needed?

**Comment by madpink** [comment]
I'm willing to admit that I think I got this one wrong. I tried multiple times and have not been able to repeat it... so is there a status for PEBKAC?

**Comment by Alys** [comment]
:-) I'll close it but we can reopen if it happens again.
