### ISSUE TITLE
group plan To-Do requiring approval does not age

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8730]
When your personal task list contains a group plan's To-Do that requires approval, the To-Do does not age (i.e., does not become more red each day that you don't complete it).

The correct behaviour is that the To-Do's value should become more negative at each cron, in the same way as any other To-Do.

This bug does not happen to a group plan To-Do that does not require approval, so it's likely caused by code related to approval. E.g., there might be code that stops completed group plan Dailies from doing damage if they haven't been approved before cron and that code might be inadvertently applied to To-Dos as well.

**Comment by thefridge111** [comment]
Hi, I wouldnt mind taking a look at this if someone can point me in the right direction!

**Comment by Bb2jake** [comment]
In scoreTask(), it does look like all group items requiring approval are stopped cold. Letting To-Dos through only so they can age appears to be straightforward. I can work on it, if you'd like.

**Comment by Alys** [comment]
@Bb2jake Thanks, please do!

**Comment by librarianmage** [comment]
Hello @Bb2jake! How are you doing with this issue?
