### ISSUE TITLE
From Forum, Kobnach: Incredible reduplicating lion egg

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#874]
http://community.habitrpg.com/content/bug-report-incredible-reduplicating-lion-egg#comment-310

> I'm not sure of the sequence of events, but I believe I recently had a lion egg drop. Some time after that, I had a base potion drop. Since I didn't yet have a base lion, I went to my inventory to put them together - and found 6 or 7 rows of lion eggs, plus the one panda cub egg I knew I had. My 3 potions displayed correctly. Thinking it was a display bug, I clicked on one of the lion eggs, and used the baase potion with it. Now I have 6 rows of lion eggs, plus one half row, and one on the row with the panda cub egg, for a total of 14 eggs.
> 
> Switching within the avatar screens didn't get rid of the phantom eggs; neither did closing the avatar screen (or having it time out, not sure which it was). Refreshing the browser window didn't help either.
> 
> Experimenting with the interface suggests it would be happy to let me poor a different potion over one of these extra lion eggs. I didn't do so - I'm waiting to use non-base potions until I have a better idea of the drop rate, and besides, I don't feel like I really own the extra lion eggs.
> 
> AFAIK, I only got one lion egg drop. I don't remember whether I looked at my inventory at the time. I knew I didn't have a base potion, so may not have looked. But if I had looked, I'm pretty sure I'd have noticed this if it started immediately when I got the drop, as seems likely.

**Comment by wc8** [comment]
Possibly related to #820

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
