### ISSUE TITLE
Clean up references to repo as HabitRPG/habitrpg

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#8741]
### General Info
  * UUID: 30983c37-52c3-415d-977c-38af6c7db91c

### Description
Remove references in the code to https://github.com/HabitRPG/habitrpg and replace them with https://github.com/HabitRPG/habitica

**Comment by DrStrangepork** [comment]
Yes, https://github.com/HabitRPG/habitrpg does redirect to https://github.com/HabitRPG/habitica, but it is good for consistency.

**Comment by signalsandnoises** [comment]
I'd like to try my hand at this. Is help welcome for this issue?

**Comment by DrStrangepork** [comment]
I've already submitted a PR for this issue
