### ISSUE TITLE
Error while signing up using google OAuth via an invitation

### ISSUE THREAD

**Issue by TheoSl93** [HabitRPG/habitica#8743]
### General Info
  * Browser: Chrome 58.0.3029.110 
  * OS: Windows 8.1
  * Task: sing up via invitation using Google

### Description
OAuth error while singing up via an invitation using a google account. The google authentication works fine in other screens. See attached:

![image](https://cloud.githubusercontent.com/assets/26006940/26265590/fb55c6d6-3ce1-11e7-956e-82fbba4ae299.png)

**Comment by paglias** [comment]
@TheoSl93 thanks! We're working on this and should have it working soon

**Comment by mdanlowski** [comment]
Hi! Today I have encountered a similar error when trying to register with google

- Chrome 60.0.3112.101 
- Windows 7
- Sign up with Google account **(no invitation)**

![image](https://user-images.githubusercontent.com/24384407/29749405-e38aecc4-8b2a-11e7-859d-7fa8eeb96e3f.png)

**Comment by paglias** [comment]
Hi @mdanlowski! Sorry about this, the problem has been harder to fix than expected. Can you signup with your email instead or signup with google from the front page and then get another invite? Thanks

**Comment by mdanlowski** [comment]
Sure :smile: I've registered with email; just wanted to help :+1:

**Comment by librarianmage** [comment]
Does this still happen?

**Comment by paglias** [comment]
No, it can still happen. For reference, the solution is to make sure the google popup always redirect to the login page

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by Alys** [comment]
We are working on this in https://github.com/HabitRPG/habitica/issues/8127 so I'm closing this issue.
