### ISSUE TITLE
Task tooltip flickers if it is multiline and being shown to the "left" from the link.

### ISSUE THREAD

**Issue by yangit** [HabitRPG/habitica#875]
See the video. Problem is with position:relative attribute of .task CSS class
http://www.youtube.com/watch?v=Dc0uaU-3FMw
Should be easy to fix but I'm not a CSS ninja.
It only applies when tooltip is shown to the left of the link and only if it has multiple lines.

I tried it under anguular-rewrite branch but it also applies to currently deployed habitrpg.com

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
