### ISSUE TITLE
negative check-ins until next prize

### ISSUE THREAD

**Issue by meganstrickland** [HabitRPG/habitica#8751]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: a46b60d0-0cec-4cc6-a272-9a5e6c9b474e
  * Browser: Firefox 53.0.3
  * OS: Windows 7 Pro (64-bit)

### Description
Yesterday, I got a check-in counter pop-up that said "Check-ins until your next prize: -1"

<img width="461" alt="habitica_negative_checkin_counter" src="https://cloud.githubusercontent.com/assets/3529967/26424043/d7c33946-409d-11e7-9bb0-02cc5e4e0dda.png">

Today, my check-in counter pop-up was back to normal. I think it said I had 8 check-ins until my next prize, though I don't remember for certain.

Lady Alys said to include that the account currently has ` "loginIncentives": 182`

#### Console Errors
None that I saw.

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by Alys** [comment]
I'm closing this. We can reopen if it still happens.
