### ISSUE TITLE
cancelling subscription fails if payments are already cancelled in PayPal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8757]
As reported in the Report a Bug guild by Gary (5dde66c1-3e47-4d23-bfa0-054178a2dff9):

"I can't cancel a subscription. It tells me 
    {"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}
It was a PayPal subscription.
.... I think this is because I have canceled the payment in PayPal."

So, when cancelling a PayPal subscription, our code needs to check for the condition where the payments have already been halted in PayPal and if so, only adjust the termination date instead of trying to cancel the payments again.

Note though that I haven't done any investigation to confirm that this is what's really happening.

**Comment by JoshSears** [comment]
Are we referring to the GetRecurringPaymentsProfileDetails.status = cancelled/suspended/expired?

https://developer.paypal.com/docs/classic/api/merchant/GetRecurringPaymentsProfileDetails_API_Operation_NVP/

**Comment by FrankieFabuloso** [comment]
If no one is working on this I'd love to take a look at it.

**Comment by JoshSears** [comment]
@FrankieFabuloso Just to clarify, I am not working on this currently.

**Comment by Alys** [comment]
@FrankieFabuloso Thank you! Please go ahead! :)

**Comment by lemoness** [comment]
Is this still an issue, and if so, is the fix still in progress?

**Comment by Alys** [comment]
I'm testing this. I've created a PayPal subscription and will cancel it in PayPal, but from memory, there's something about PayPal that causes subscription cancellation to fail within the first 24 hours, so I'm going to wait a day before finishing the test (might actually end up being a couple of days because I'm travelling internationally tomorrow).

**Comment by Alys** [comment]
When I cancelled my subscription in PayPal, the subscription in Habitica immediately became marked as cancelled, which is the desired behaviour.

However it's possible that this issue would still occur if the PayPal subscription were cancelled but the message didn't get back to Habitica. We could write code to handle the case where the user tries to cancel the subscription in Habitica when the PayPal ongoing payments had already been cancelled but Habitica hadn't realised that. I don't know how often that would occur. I'll leave it up to the staff as to whether this is worth doing. :)

**Comment by lemoness** [comment]
I'm going to close this for now, but if it becomes a larger problem it can be reopened!

**Comment by GiacomoLaw** [comment]
I'm having this issue - refunded via Paypal as it was an accidental purchase. However, clicking on cancelled gives me this error. I presume my subscription is cancelled though?

Thanks!

**Comment by majestic-owl448** [comment]
@GiacomoLaw : try writing in the Report a Bug guild inside Habitica. It is the only way that someone with the power to check would be able to take a look at your account
