### ISSUE TITLE
repeat settings for Dailies can take effect when they should be ignored

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8758]
Reported by Quilynn (f36d8801-177f-4a86-936e-35aead16c9ca)  in the Report a Bug guild:

'Okay so found something weird with the new options for repeating dailies. If I choose monthly in the drop-down menu, choose Day of the week and then select weekly again, the daily only shows as repeating weekly on certain days of the week. It also doesn't allow me to change the day of the week. It stays locked to the date of the start time. (This is hard to explain).

'So for instance, I have a daily that's set for "weekly" on every day of the week (so it could be just set for daily every 1 day and have the same effect). I was playing around with the options just to see what they did. I selected "monthly" and then "Day of the week". The start date was a Sunday, so it was now showing me "Repeats monthly every 1 months on the 3 Sunday". I went back to make it like it was, and now the "weekly" option is showing it only repeating on Sundays, every week. I tried to re-select the other 6 days of the week, but it wouldn't let me. It's locked into only Sundays because of what is selected in the "monthly" menu. The easy fix is just to go back into the monthly menu and change it back to "day of the month" and then go back into "weekly" which then does allow me to re-select the other 6 days. (Or just pressing the cancel button to undo my changes would work too).'

I haven't tried to replicate this but will later if no one else replicates it first.

**Comment by lordbug2000** [comment]
So, I was just able to replicate this bug on my account. If it is still open, I would like to look into this a little and try to fix it?

**Comment by Alys** [comment]
@lordbug2000 Please do! Thank you very much! Comment here if you have questions or run into trouble,

**Comment by lordbug2000** [comment]
So, I'm a little new to this, which file can I find the editTask() function in?

**Comment by Alys** [comment]
`git grep` is really good for this sort of thing. In your local install, go to the repository's top-level directory (the one that contains config.json) and do `git grep editTask`. You'll see all the code that uses editTask, and that tests it, and the point in the code that defines the function.

**Comment by lordbug2000** [comment]
Ok, Thanks

**Comment by lordbug2000** [comment]
It has become apparent to me that I still have some learning to do. I have experience with web design, but only in the basic languages (html, css, basic javascript, and php). I am going to have to read up on nodejs, and angular before I am capable of being much help.

**Comment by Alys** [comment]
@lordbug2000 No worries! Thanks very much for letting us know! You might like to join the Aspiring Blacksmiths guild, if you haven't already, so that you can chat to other devs about our code base.
