### ISSUE TITLE
Click being stolen by some CSS bug.

### ISSUE THREAD

**Issue by yangit** [HabitRPG/habitica#876]
http://youtu.be/pN5PtENATeM
Observe how half of the "Save & Close" button is clickable while other is not.

I need someone with good CSS abilities to fix it. 
It is under angular-rewrite branch.
@lefnire let me know who can help me with CSS.
Or I can try to do it myself, but I will not be very efficient.

**Comment by yangit** [comment]
More obvious version of same bug. The checkbox blocks part of the control.

![screen shot 2013-05-01 at 1 37 39 pm](https://f.cloud.github.com/assets/2031974/447920/52f106b2-b221-11e2-853f-331e146ff459.png)

**Comment by lefnire** [comment]
@zakkain is our CSS guru. IMO let's save some of that for later, just to
see how far along we can get on a functional prototype - though this one is
actually preventing functional use?

**Comment by switz** [comment]
Just set a height on the checkbox. It's filling out to 100% height. You can also add `pointer-events: none;` to the css.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
