### ISSUE TITLE
Pending boss damage cut off on small (e.g. mobile) screens

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8760]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
iOS Version: 10.3.1
Device: iPhone6.1

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When viewing the "pending damage to boss" popover on a small screen, the most important part of the message--the actual number--is cut off on the left-hand side.
![x-aqqdfqgkurm2fyi060z41yjg83hyysh_q4b9vbaeelxkusrjn_9ddicexrm5gt1mbr14tf92rsipinr8dgypo1t0hfcc9fdyvdqvmmvrqtqqjiuqjsnjwn0quhocblprm3-h_n2ugfpwyzrhpdtaisfno0cjl5twcyje2q9udv2pvfc7rhftwnqkaijiollcvw2zuud0dt-rmlyh2hy](https://cloud.githubusercontent.com/assets/4501321/26508824/ddc1182a-421b-11e7-9887-b0b2078f2408.jpg)
![wg7lhteg1lfsdm5fwcwllacjpptbctiqpuzbr5lgo08u582krkk8s8ej9mx3g5inkd84voolonaisku5esam-q-hpsloyhuhqplvxy8ruhlaedod5_d8uyftz9mrwckynpt3v0guf2gojzxjwrtqjgtmohum5dmq1killmeowtieoty-9s3qgj_scimucsmegrzqn_8fi3m8ph9fxgpfz](https://cloud.githubusercontent.com/assets/4501321/26508826/e1c693b4-421b-11e7-9555-029c67e86547.jpg)

This will likely be rendered moot by the frontend redesign, but there should be a way to clean this up in the meantime. Two possibilities:

* Make the popover position itself intelligently when there is insufficient space, possibly appearing to the right instead of below on screens like the above
* Restructure the string output so instead of "X pending damage to boss", it's "Pending damage to boss: X", which preserves the pertinent info even if the left side is cropped away

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

N/A

**Comment by noorudheen** [comment]
hi,
Iam an entry level programmer, would like to work on it.probably trying to restructure the string output.

**Comment by Alys** [comment]
@noorudheen Fantastic, thanks! Please go ahead and comment here if you have questions. I think restructuring the output is the best approach.

**Comment by nik-suri** [comment]
Hi,
I am also an entry level programmer and would like to help on this issue.

**Comment by Alys** [comment]
@RealDealNikhil @noorudheen I'm sorry but it's best that we put this on hold now. We're most of the way through a project to change the website's front-end code and this bug might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by nik-suri** [comment]
Ok, thanks for letting us know.

**Comment by regifr** [comment]
can I join this issues?

**Comment by regifr** [comment]
can I join this issues?
I think I got the solution for this
![screenshot_617](https://user-images.githubusercontent.com/30581795/28834930-f294ea16-770d-11e7-859f-93e9fcf8ec1c.png)

**Comment by regifr** [comment]
like this 
![screenshot_615](https://user-images.githubusercontent.com/30581795/28834381-47ec52b2-770c-11e7-86da-8e12e54376d6.png)

**Comment by SabreCat** [comment]
@regifr The issue is marked as on hold because the frontend is being completely redesigned (see yesterday's Bailey announcement). You can submit a PR if you'd like, but it's not likely to end up live for long.

**Comment by regifr** [comment]
I new in Habitica and Github. I like the contributing system in Habitica 😄
I want contribution to Habitica ~~so i search issues, and I see this issue~~
sorry if I have a mistake in the pull request, its my first PR

**Comment by SabreCat** [comment]
Closing this, no longer relevant under new client.
