### ISSUE TITLE
Skills are used more times than the ones reported in the party chat

### ISSUE THREAD

**Issue by StefanoTrv** [HabitRPG/habitica#8762]
When I started testing this bug I thought it was possible to use skills more times than the ones you should be allowed to by your current amount of mana. I couldn't prove nor disprove this problem, but I've found another problem. I'm pasting here the message I posted in the "Report a bug" guild:

> About the bug of skills being cast more times that the mana amount should allow to. First of all, I saw that my Ethereal Surge skill restored 14 MP. Then I clicked on it as many times as I could, until the "out of mana " message appeared. It was a total of 9 clicks (10 if you count the one which triggered the message). In the party chat there were 5 new messages (6 Ethereal Surge messages in total, if you include the one I used for testing). I monitored the mana bar of one of the members of my party, and it had 84 more mana than after testing the amount of mana restored by a single skill cast. That's more than 14*5=70, and if we want to take the decimals into consideration and approximate the amount of mana restored to 15, 15*5=75, which is still less than 84. 14*6, however, is exactly 84. These numbers would suggest that the skill has been cast one more time than what the party chat says, but I forgot to write down how mana I had before using the skill, so I can't say for sure if this is a problem with system messages or with skill casts.
However, this data asks for further investigation, so I would be grateful if someone else tried to test this bug. I will do it again in a few days, when I have replenished my mana bar.

Later, **@Il Mago Rosso** confirmed the bug with this message:

> @MegaDerf : I just experimented the same thing, 6 messages on the party chat of me casting an Ethereal Surge, but my party mates receiving 16*7=112MP...

Today I did some more tests, but this time everything worked properly. My mana bar, the ones of the other members of my party (I monitored the mana bar of two of them) and the number of messages in the party chat were all coherent with each other. Which means that I couldn't confirm nor disprove the initial problem I was trying to investigate, but there's definetly something that's not working as it should with the party chat messages.

My UUID: c946275f-09e6-4ac2-96e4-3308fd26d750

**Comment by Alys** [comment]
@TheHollidayInn is working on concurrency fixes that should help with this and several other similar issues so I'm closing this one.
