### ISSUE TITLE
Group Plan Tasks, specifically Dailies still show as required when removed from Group Plan Task List

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8764]
# General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 	45.0.2552.812
Windows 10 32-bit

# Description
When a task, that is already claimed, is removed from a group plan there is no visual change to state the task has been removed, and it is
a: no longer required
b: can now be deleted.

# Suggested Solution
All group tasks, instead of showing the delete trash can on the task, shows an icon similar to the challenge megaphone icon. (Maybe a different icon so it clear a group task not a challenge?)

When the task is deleted from the group task, the icon changes to delete icon.

Another alternative solution which will give better control, show an icon similar to the challenge tag removal (megaphone with cross through it). This will then give the user the option to remove all tasks that are no longer attached to the group plan or complete them.

**Comment by Alys** [comment]
I like this alternative: "Another alternative solution which will give better control, show an icon similar to the challenge tag removal (megaphone with cross through it). This will then give the user the option to remove all tasks that are no longer attached to the group plan or complete them."
Although I think that for consistency with challenges, the options should be remove all tasks that are no longer attached to the group plan or keep them normal user-owned tasks.

Note that the options would apply to only tasks that had been deleted in the group plan. There could be other tasks in the user's list that were still part of the group plan and those should not be affected by those removal options.

If there's no objections from anyone in a couple of days, I'll mark this as help welcome.

**Comment by SabreCat** [comment]
I believe this would be a client side fix, so best to pause this until the redesign is complete. If investigation suggests the majority of this would be server-side, though, I'd be happy to flip the label back.

**Comment by SabreCat** [comment]
Will be fixed by #12142. We now delete the child tasks when the origin task is deleted--unlike with Challenges, it doesn't make as much sense to leave them on the user lists in a detached state.
