### ISSUE TITLE
Strange bar under my statistisc and team.

### ISSUE THREAD

**Issue by dulcissimahabitica** [HabitRPG/habitica#8779]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)  - I was advised by @Alys to post here, so I am posting. 

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 83a315d8-48ef-4460-a0b8-94053d545238
  * Browser:  I use Mozilla Firefox 50.0.2. Tested it and the same issue occurs on Chrome 58.0.3029.110
  * OS: Win7

### Description
[//]: # Ok, I will just paste discussion from **Report a bug** guild in Habitica: 

Hi there. I dunno what happened, but after I've accepted some challenges for June and went back to Tasks page, the display got messed up. I've tried to adjust the resolution by scrolling with ctrl key, but it did not do much help. I use Mozilla Firefox 50.0.2 on Win7. Same issue occurs on Chrome 58.0.3029.110 Here is the screenshot from Mozilla: http://imgur.com/a/NwqyY

Alys: @dulcissima : Try to make the window wider if you can, or reduce the zoom size using your browser's zoom menu item. That will get rid of the scroll bar under the party header, which should fix it. 
dulcissima: @Alys I am already on fullscreen. And I said that I've tried to adjust zoom by trying ctrl &scroll - here is the resolution I get when the bar finally disappears: http://imgur.com/a/wahsv - can you read anything? Because I can't :( . I think statistics bar is far too wide.

Alys: @dulcissima : Please disable all browser extensions, even ones that don't appear to be related to Habitica, or if you prefer, load the site in an incognito / private window with all extensions disabled in incognito mode. If that doesn't make any difference, please report that as a new issue in GitHub because we'll need to do more investigation for it. Post in the GitHub issue that I asked you to report it there. 

I did that, disabled all Firefox extensions, restarted browser without them, opened Habitica and - guess what - the bar appeared :/ 
Here is the screenshot: http://imgur.com/a/sf4rr 

#### Console Errors
[//]: # (Include any JavaScript console errors here.) n/a

**Comment by librarianmage** [comment]
@Alys should this wait to see if it is still an issue after the client redesign?

**Comment by Alys** [comment]
@dulcissimahabitica I'm closing this because I know it will no longer be an issue after the client redesign that MathWhiz mentioned, which is not far away now. I'm sorry we couldn't work out what caused this!
