### ISSUE TITLE
Seeing pets in the stable

### ISSUE THREAD

**Issue by MagicMicky** [HabitRPG/habitica#878]
Hi.
Just reporting a small bug here. Even though I don't have any pets, I can see all of them in the stable. I thought it was normal, until I show my account to a friend and she tell me that she can't see them, except the one she has.
By the way, the screen where they are all displayed (with the Avatar, the inventory and other tabs) looks really smallish compared to my screen size, and you could benefit from that space (I have to scroll left to see all of them).
I'm level 5, and have no pet at all except one egg (looted at lvl 4).

**Comment by lefnire** [comment]
Both issues should be fixed now
