### ISSUE TITLE
notification menu closes when one notification is dismissed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8786]
We've had some complaints about how the new behaviour where the notification menu closes when you use the "clear" button (the "x") to remove one notification.

For example, from Dewines:

"on the website, the chat notification popup has started closing again every time you dismiss a notification. The popup should stay open so you can dismiss more than one guild at a time. I'm in a lot of guilds and some I only check once or twice a week, so it's a bit tedious if I have to keep opening the popup to dismiss the next guild I don't want to read right now."

**Comment by AndreGtz** [comment]
This needs to get fixed, it is so annoying to dismiss all alerts.
:+1:

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
This appears to have been fixed, with the new client.
