### ISSUE TITLE
Key to the Kennels returns user to Task page instead of Pets/Mounts page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8787]
After using Key to the Kennels, the user is returned to the Tasks page, which can be confusing since it's not related to the action they just took. A better result would be taking them to the Pets page if they released only Pets or Pets and Mounts, or taking them to the Mounts page if they released only Mounts. That would give good feedback that the Key had worked correctly.

This is not something we want a fix for yet. It can wait until our current website improvement project is finished, and in fact might even be made redundant by that project. I'm recording it now so we don't forget later if it is still relevant.

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by lemoness** [comment]
Right now, Key to the Kennels is on the list to restore. When we do, we can make sure as part of testing that feature, this doesn't happen, so we don't need this ticket.
