### ISSUE TITLE
Death sounds does not play when negative habit is clicked or cron damage is applied

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#8788]
_edit by Alys:_

When you click a minus Habit, the minus Habit sound should play. However if you die from a minus Habit or from damage taken from your Dailies at cron or from damage from a quest boss due to a party mate, then the Death sound should play. Currently it does not play.

**Comment by nik-suri** [comment]
Hi, I would like to help on this issue. Do you have any other pointers?

**Comment by Alys** [comment]
@RealDealNikhil Thanks! Comment here if you have questions or run into trouble. See the wiki's [Guidance for Bards](http://habitica.wikia.com/wiki/Guidance_for_Bards) page to learn how the audio files are set up in our code, and to find the file names for the audio files. You can use that information to find any code that already uses the Death audio files to see if there's bugs in it. It's also possible that the Death audio has just never been set up in the code, so in that case, you'd search for the code that processes Death (try `git grep -i death`) and work out where to best add the audio (using code for the other audio files as an example of how to do it).

**Comment by nik-suri** [comment]
I've been looking through the code base to understand how and when audio files are played. I see that, in tasksCtrl.js, when the negative habit is clicked, the "Minus_habit" sound is played. Do you want this sound to be replaced by the "Death" sound?

**Comment by Alys** [comment]
Ah no, sorry, we should have made this issue clearer. When you click a minus Habit, the minus Habit sound should play. However if you die from a minus Habit or from damage taken from your Dailies at cron (or from damage from a quest boss due to a party mate), then the Death sound should play.

I'm copying this information to the top post.

**Comment by nik-suri** [comment]
No worries. Thank you for clarifying!

**Comment by nik-suri** [comment]
Hi, I've gone through the code base and think that I've found the source of the error. However, my Habitica install has been delayed. I am stuck on creating a swapfile. When I try to run any of the swap commands such as "mkswap", "swapon", or "swapoff", bash gives me this error:
`-bash: swapon: command not found`
I am not sure what steps to take from here. From what I understand, swapfile commands should be pre-installed on my machine. Do you have any advice?

**Comment by SabreCat** [comment]
@RealDealNikhil: I haven't worked with those commands myself. However, a quick search on your error reveals [this Q&A](http://community.onion.io/topic/1397/swapon-command-doesn-t-exist-in-any-packages)--maybe that'll help you out?

**Comment by nik-suri** [comment]
@SabreCat Thanks for giving me this link. How did you create a swap file without running those commands?

**Comment by nik-suri** [comment]
@SabreCat Just in case it makes a difference, I am running on mac.

**Comment by SabreCat** [comment]
I've never needed to make a swap file, sorry! I start from [these steps](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Install_NodeJS_and_npm_for_Mac_OS_.2F_Linux_.2F_Unix) and have never had trouble with swap file size.

**Comment by nik-suri** [comment]
@SabreCat Okay, thank you for your help. I will try that.

**Comment by librarianmage** [comment]
Does this still happen?

**Comment by SabreCat** [comment]
Just gave it a quick test locally. Game-over sound plays OK when wiping oneself out on minus Habits!
