### ISSUE TITLE
New PressKit Screenshot

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8789]
There is a new screenshot to add to the PressKit! It should replace the old task list screenshot.

**Comment by lemoness** [comment]
<img width="1440" alt="screenshotsample6-6" src="https://user-images.githubusercontent.com/3494081/26851565-15cfc70a-4ac0-11e7-8dc2-6edc75046f6c.png">

**Comment by librarianmage** [comment]
I can do this!

**Comment by TheHollidayInn** [comment]
Thanks!
