### ISSUE TITLE
do not delete challenge tasks when a challenge is closed / deleted

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8793]
Currently, when a challenge is closed or deleted, the tasks belonging to that challenge are deleted. Note that I'm referring to the challenge's own copies of its tasks, not the tasks that were given to each participant.

We want to change that so that the challenge's own copies of its tasks are never deleted. That probably just means changing this line:
https://github.com/HabitRPG/habitica/blob/67318177a2347666b0a2fdedc5af0e763a2b5079/website/server/models/challenge.js#L310
and associated tests, if any, but whoever works on this should check that nothing else needs to be done.

This is partly needed for https://github.com/HabitRPG/habitica/issues/8790 but also will have benefits by itself (e.g., to help with bug fixing when challenge cloning fails - an admin can retrieve lost tasks) and so can be done immediately.

**Comment by kvsm** [comment]
Tagging this for later - I'll give someone else a chance to claim it first. :)

**Comment by kvsm** [comment]
Ok, I'll pick this one up since no-one else has. I'm in a position to start on #8790 but I think it makes sense to get this in place first.

**Comment by lemoness** [comment]
@kvsm - Hi there! Just checking in -- what's the status of this fix?

**Comment by lemoness** [comment]
This is now open for someone else to jump in!

**Comment by TheHollidayInn** [comment]
@paglias @Alys did we decide to not do this?

**Comment by Alys** [comment]
Yes. I think the reason was that the challenge creator might have put personal details in the challenge tasks, and so if they later deleted their account and were an EU citizen, GDPR would bite us.
