### ISSUE TITLE
Data difference on different PCs.

### ISSUE THREAD

**Issue by the-archer** [HabitRPG/habitica#88]
I had used HabitPRG on a particular PC (I was signing in using facebook) and had made some changes. However, after using it on another PC and then coming back to the earlier one, the changes made on the second PC are not reflected here.
Sorry for my roundabout wording, please do ask if the issue is not clear.

EDIT : Thought I'd mention that I am using Firefox Sync to sync my data across the 2 PCs.

**Comment by jacalata** [comment]
There was a database error about 7 hours ago that lost all changes made for the day - probably the changes you made on the second PC were in that set that got lost 
(see https://github.com/lefnire/habitrpg/issues/85)

**Comment by lefnire** [comment]
yeah, #85 - nothing specific about different machines, follow up there
