### ISSUE TITLE
Randomization for finding pet & potions on daily cards seems wrong

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#880]
Hello,

Right now, I can create a task in dailies, then just check/uncheck it until I find something.
No gold/hp lost or won, but I can get 100% of chance to find a pet or a potion for each of my dailies.

I actually realized that issue when after finding a pet, and refreshing my page, the task got unchecked, and by checking it again, I lost my pet (not found again).

Shouldn't the random value for finding a pet/potion associated to each card in Dailies be set for a day, and not every time it gets unchecked ?

Thanks for looking at it
Cordially

**Comment by Shaners** [comment]
Were you able to get more than 2 drops in a day by using this method?

**Comment by AdrienLemaire** [comment]
I guess I didn't. If it's one drop per list per day, then it‘s good after all :)

**Comment by Shaners** [comment]
This little area tracks how many drops you've gotten in a day and won't give you anymore if you've already gotten 2:
https://github.com/lefnire/habitrpg/blob/master/src/app/scoring.coffee#L22
So even if you do cheat you the max items you'll be able to get is 2 per day.

**Comment by AdrienLemaire** [comment]
Thank you :) Closing the thread then
