### ISSUE TITLE
some quests have incorrect unlock conditions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8801]
_As reported in the Report a Bug guild by Il Mago Rosso:_

**In the quests section, even if I own the quest but I'm not the right level to use it, it says `You must be level 15 to buy this quest!`, when instead I own the quest but I must be at least level 15 to use the quest.**

**Also, I think that having the gold purchasable quests say `To earn this quest, complete Terror in the Taskwoods, Part 2: Finding the Flourishing Fairies`. is misleading, shouldn't it be to buy this quest?**

I agree with both points. 

For the first, the wording could be changed to "... level 15 to buy or use ...." . See `mustLvlQuest` in `website/common/locales/en/quests.json`

For the second, see `unlockByQuesting` in the same file but note that it is correct for most quests so it shouldn't be changed. Instead we'd need a new string for the case where you aren't given a quest scroll automatically.

A similar issue is at https://github.com/HabitRPG/habitica/issues/8329 but I'm reporting this one separately since it needs different fixes.

**Comment by lemoness** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Fixed in the new website. When you try to use the scroll that you own by clicking on the scroll's "Invite Party to Quest" button, you see a red snackbar notification saying "You must be level 15 to begin this quest."
