### ISSUE TITLE
banned words in a chat post should be listed in the error message

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8812]
When a player posts a message that contains banned words (swear words, etc) to the Tavern, their post isn't made and they see a `bannedWordUsed` message advising them to rewrite it. 

The message should list the inappropriate words that they used.

I suggest it be displayed like this (where "word1" and "word2" are the bad words) but other ideas are welcome:

_Oops! Looks like this post contains a swearword, religious oath, or reference to an addictive substance or adult topic ("word1", "word2"). Habitica has users from all backgrounds, so we keep our chat very clean. Feel free to edit your message so you can post it!_

**Comment by redloste** [comment]
Hi there! If there's no one working on this yet, I'd like to help.

**Comment by TheHollidayInn** [comment]
Go for it!

**Comment by redloste** [comment]
Hi! Unfortunately, I do believe that I have to drop this issue. Stuff is coming up, and I don't think that I can tackle this one at this point. Thanks, though, for the opportunity. Cheers!

**Comment by Alys** [comment]
@UnstoppableVelocity No worries! We totally understand. Thanks very much for letting us know!

**Comment by pineapple-joe** [comment]
Hey, 
I'd like to help solve this issue if no one else is on it already.
