### ISSUE TITLE
Option to disable health loss for not completing dailies

### ISSUE THREAD

**Issue by Gmk1212** [HabitRPG/habitica#882]
Can there be an option added to not lose health for not completing dailies?

For example, I have nowhere to put "take out the trash" because this isn't done daily but it's something I don't like to do so I give myself points for doing it.

I don't like the idea of being forced to complete my dailies. I like this game because I'm rewarding myself for doing things I don't want to do.

For now, I'll move everything over to the habits section, but that will make that column too long and it looks pretty stupid to have an empty column. The items I'm moving over don't fit habits, either.

**Comment by uvwxy** [comment]
Have you tried setting the daily to "once a week"? You can select on which weekdays you want to complete your daily.

**Comment by ghost** [comment]
I'd like to see an optional punishment for dailies too. What if I'm visiting someone in the weekend and I had dailies in that weekend I can only complete at home (This happens regularly).

**Comment by heyimzsa** [comment]
I remember that in the fourm they show a way around it for the time being. http://community.habitrpg.com/content/vanilla-habitrpg-tips-tricks

**Comment by lefnire** [comment]
Well, a very simple workaround right now is User -> Settings -> Temporarily
Freeze Account. This will prevent HP loss on dailies. Soon we'll replace
this with the actual Inn / Tavern, which requires a minimum 24h stay and
you can "check out" any time after. But that will remain a proper
workaround if you don't want HP loss, just rest in the Inn indefinitely

**Comment by wizonesolutions** [comment]
Hmm, I just use habits for things I don't have to do on particular days. If the column's empty, the column's empty (...but mine isn't).

Maybe a hide column button (think I saw an issue for this) would be the solution though.

**Comment by StanLindsey** [comment]
Yeah, I'm with @wizonesolutions - If its not something you do daily/regularly then see if setting it as a Habit will help you out. 

Now that we have the tavern fixing some of the other comments here, I'll close this.
