### ISSUE TITLE
API should accept false as well as null for due date for To-Dos

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8820]
As described in https://github.com/HabitRPG/habitica-ios/issues/136 and https://github.com/HabitRPG/habitica-ios/issues/292 , once a due date has been set for a To-Do, you can't remove it because of an issue with Reskit. 

The API currently allows the due date to be unset with a `null` value.

**The API should be changed to also allow a To-Do's due date to be unset with a `false` value** (in addition to still being unset with a null value).

**Comment by snowsignal** [comment]
I can work on this one. I think I have a better understanding of the code to be modified this time around.

**Comment by paglias** [comment]
Not sure this is a good idea or it'll work correctly with Mongoose. I think the fix should be on the iOS' side not in the API

**Comment by Alys** [comment]
I've updated the two issues in the iOS repo to indicate that the suggested idea of changing the API is no longer desired.

@JacksonCoder Thanks for being willing to work on it. I hope you can find another issue you're interested in!
