### ISSUE TITLE
system messages in party chat should  not be flaggable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8824]
Currently, it's possible for any party member to flag a system message. We've decided that it should not be possible (see https://github.com/HabitRPG/habitica/issues/7767#issuecomment-308279239 for reasons).

System messages are those that display quest progress message and skill casts. The `uuid` is `system`:
```
        {
            "id": "a1c7c737-6cba-439e-8674-261492d0dd3f",
            "text": "`Cantras casts Tools of the Trade for the party.`",
            "timestamp": 1496812063560,
            "likes": {},
            "flags": {},
            "flagCount": 0,
            "uuid": "system"
        },
```
The changes desired are:
- On the website, remove the flag button from system messages.
- On the iOS app, remove the flag menu option from system messages. https://github.com/HabitRPG/habitica-ios/issues/472
- On the Android app, remove the flag menu option from system messages. https://github.com/HabitRPG/habitica-android/issues/785

Also, **after** the iOS and Android apps have been updated [EDIT: the Android app has been done], the API changes below should be done (along with the website change if it's not been done by then):

- In the API, prevent [groups/:groupId/chat/:chatId/flag](https://habitica.com/apidoc/#api-Chat-FlagChat) being used on system messages. 
- If you try to use it, the error message should be something like "You cannot flag a system message. If you need to report a violation of the [Community Guidelines](https://habitica.com/static/community-guidelines) related to this message, please email a screenshot and explanation to Lemoness at leslie@habitica.com".
- The email address in the error message should **not** be hard-coded but should use the `EMAILS.COMMUNITY_MANAGER_EMAIL` environment variable (use `git grep COMMUNITY_MANAGER_EMAIL` to find how that's done).
- Tests for the new API functionality.

I'm putting this on hold for now. There's not much point doing just the website front-end change at the moment since we'll be releasing new front-end website code soon and we can make the change during its development or after its release. We'll take it off hold when the app changes are done.

**Comment by pcvonz** [comment]
Hey, I'd like to help out with this. I'll dig into it a little tonight.

**Comment by lemoness** [comment]
@pcvonz  Thank you very much! Let us know if you have any questions.

I've updated the labels on this issue.

**Comment by pcvonz** [comment]
I removed the report flag from the website and made the API return an error if a system message is flagged, the commit is [here](https://github.com/pcvonz/habitica/commit/39de88ace19844cd24d232b2f0620f86657ec33c).

[This test](https://github.com/HabitRPG/habitica/blob/a28aea65f88e8847b824e82553faaa9aa055942b/test/api/v3/integration/chat/POST-groups_id_chat_id_clear_flags.test.js#L77) now fails. Should I rewrite it so it tests if flagging a system message throws an error?

Let me know if I'm tackling this the right way. Still relatively new to the project 😄
