### ISSUE TITLE
Add FAQ to Press Kit

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#8827]
Based on the volume of interview requests that Habitica receives, we've decided to implement a FAQ section on the Press Kit. All of the text can be found here: https://docs.google.com/document/d/17Ys40wZOkP4kSUDHE3aQN8Ayaxz5Wpkryg3lcbn5BUc/edit?usp=sharing

This should appear towards the bottom of the press kit page, below the images.

The "Marketing/Social Media Inquiries" section of the contact page should also be changed to link to the Press Kit page, since it will have my email at the bottom.  (I notice that the Report a Bug link also needs to be changed from GH to the Report A Bug Guild.)

Let me know if there are any questions!

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Should this be added with #9143? If so, I can do this.

**Comment by lemoness** [comment]
Yes, it should! Thank you very much.

**Comment by librarianmage** [comment]
Can this be marked as in progress?

**Comment by Alys** [comment]
labels updated

**Comment by librarianmage** [comment]
Thanks!
