### ISSUE TITLE
QRCode Generation for api/user tokens

### ISSUE THREAD

**Issue by uvwxy** [HabitRPG/habitica#883]
I think it would be great to be able to display a QR code containing the api/user tokens for mobile device/client setup. This would make the setup process a lot easier.

What do you think?

**Comment by heyimzsa** [comment]
I'm glad you jumped right on the suggestion given by the reviewer of the android app. I think it's a good idea as well. However, I would rather see it used as a calling card for party invites.

**Comment by zoebeagle** [comment]
Could we use something like this? http://www.onextrapixel.com/2011/10/12/build-your-own-qr-code-generator-with-google-chart-api/

**Comment by zoebeagle** [comment]
Or maybe even easier... https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl=USERIDHERE&choe=UTF-8&chld=L

Replace USERIDHERE with your User ID or API Token... can also change the size (in pixels) if needed.

**Comment by uvwxy** [comment]
That should be the simplest solution. @zoebeagle

**Comment by wizonesolutions** [comment]
@lefnire what are your thoughts on this? Someone on IRC (@MagicMicky) was asking.

**Comment by lefnire** [comment]
Sorry I'm so out of this loop guys. I wouldn't know how to set it up, and not personal dev prio since we're working on auth API for our own mobile purposes. If you can get it working in the repo and shown on the API tab or some such, PR me

**Comment by lefnire** [comment]
sorry, didn't see the PR! great job @MagicMicky. merged
