### ISSUE TITLE
"Repeat Every" button is wrong for "Monthly" repeat frequency in Dailies edit form

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8831]
In the Daily edit form, when you select the "monthly" frequency, the "Repeat Every" button doesn't change from what it was previously ("Weeks" in the image below). It should change to be "Months".

It does change correctly when you select "daily", "weekly", or "yearly".

![image](https://user-images.githubusercontent.com/1495809/27387568-faedd0a8-5690-11e7-8e1d-00a542e91eba.png)

**Comment by pouyio** [comment]
Hi! (first time contributing to a project so sorry in advance 🙃)

I have a question, I cloned the project and fixed this issue, but tests aren't passing, and weren't passing *before* my changes anyway.

Should I try to fix them before creating the PR?

**Comment by SabreCat** [comment]
@pouyio Tests unrelated to the fix in question, whose status doesn't change after adding the fix, can be ignored in most cases. There are a few tests that misbehave in some environments at the moment, and until we can get those things ironed out, we'll get the odd false test failure.

**Comment by SabreCat** [comment]
That said, if you _want_ to correct some of those weird failing tests, you're more than welcome to! :D But best to put that on a separate PR if it bears no connection to the other substance of the PR.
