### ISSUE TITLE
Habit counters should be set to zero by Orb of Rebirth (not for challenges or group plans)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8834]
When you use the Orb of Rebirth, it should set the counters for all your own Habits to zero. This will be consistent with how the streaks of Dailies are reset to zero.

Habit streaks should NOT be reset to zero for any Habits that are part of active Challenges or are from Group Plans (also consistent with Rebirth's affects on Dailies).

_EDIT 2019-11-16: The two points above might already be done. The coder who woks on this might want to test Rebirth on their local install before starting to investigate the code._

The `rebirthPop` text string should be adjusted to match:

https://github.com/HabitRPG/habitica/blob/020726f6f83030cc087dac27679eb17b0ce544f6/website/common/locales/en/rebirth.json#L24

Currently it says:
"... Your streaks will be removed except from challenge tasks. ..."
That should be changed to something like this:
"... Your streaks will be removed except from tasks belonging to active Challenges and Group Plans. ..."
Note that "Challenges" and "Group Plans" should be capitalised as shown.

The `rebirthAdvList3` string also mentions streaks but it's not currently used so it doesn't need to be changed.

_Thanks to cTheDragons for noticing this._

**Comment by alexanderqchen** [comment]
Hi! I'm new to contributing to Habitica and practical programming in general. Would this be something I can handle? I'm kind of lost with all the files and don't really know where anything is yet, but I'd be glad to help in any way I can!

**Comment by Alys** [comment]
@alexanderqchen We'd be happy for you to try this! You can comment here if you run into trouble or have questions.

To start with, I'd search through all the files to find those that have "Rebirth" in their name (case-insensitive; e.g., `find . -iname \*rebirth\*` on Linux/Unix/BSD/MacOS) and also use `git grep -i rebirth` to find any files that contain code about Rebirth. On *nix, you could use `git grep -i rebirth | grep -v /locales/` to remove the files that contain texts in different languages, to make the other files easier to see.  That should let you find the code where Rebirth happens. In that code, you'll see what it does to reset the streaks for Dailies, and you could do something sort of similar for Habits.

**Comment by alexanderqchen** [comment]
Got it. I'll try my best!

**Comment by alexanderqchen** [comment]
@Alys The counters now should work as you have described. However, I was not able to test habits that are part of group plans because when I tried to make a group, it asked me for payment. Is there any way to test groups?

Additionally, when I run `npm test`, there are about 80000 errors, even on the develop branch.

What should I do from here?

**Comment by Alys** [comment]
@alexanderqchen I'm really sorry we never replied to this. :(  Are you still interested in working on it? If so comment here and I'll give you information about how to set up a group plan locally.

**Comment by lemoness** [comment]
Added labels!

**Comment by alexanderqchen** [comment]
@Alys Hi again! Don't worry about it! I've been really busy with classes anyways, but I will have free time in a couple weeks, so I'm still interested in working on this.

**Comment by Alys** [comment]
@alexanderqchen  Thanks so much! When you're ready, to set up a group plan on a guild or party, see the "Creating Test Data" section in [Using Your Local Install to Modify Habitica%27s Website and API](http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API). The information there about adding a group plan is new so if you have any problems with it, please tell us!

**Comment by beffymaroo** [comment]
@alexanderqchen Are you still working on this issue? Please let us know!  Thank you.

**Comment by alexanderqchen** [comment]
Hi @beffymaroo ! I apologize for my lack of communication, but I no longer be working on this issue.

**Comment by beffymaroo** [comment]
@alexanderqchen That's totally fine, thank you for letting us know!

**Comment by citrusella** [comment]
Are there any parts of this that still need doing? It looks like the text ([rebirthAdvList3](https://github.com/HabitRPG/habitica/blob/020726f6f83030cc087dac27679eb17b0ce544f6/website/common/locales/en/rebirth.json#L8) and *maybe* [rebirthPop](https://github.com/HabitRPG/habitica/blob/020726f6f83030cc087dac27679eb17b0ce544f6/website/common/locales/en/rebirth.json#L24)?) might still need changing, but the behavior appears to work the way this issue describes needing done (I snooped around the code, then put my test account in a challenge (it was already in a group plan with an assigned habit) and rebirthed it just to confirm).

**Comment by Alys** [comment]
@citrusella So when you rebirthed, the streaks / counts on your Habits were all set to zero, except for Habits from Challenges and Group Plans?

If so, then no, sounds like there's nothing else to be done.

Regarding those two text strings, my opinion is that they don't need to be changed because the counters on Habits are referred to as streaks, but if I've missed anything or you disgree for other reasons, please post here!

I'm closing this now for efficiency but I'll reopen if text changes are needed. :)

**Comment by citrusella** [comment]
Yes, my group plan habit stayed +1 and my challenge habit stayed +5/-5. (When I looked at the code I didn't see anything about group plan tasks specifically, but the site does ignore them in terms of streak resetting, so...) I don't really think the text change is all that important, personally (unless it's important to mention group plans alongside challenges? \*shrug*), but I asked about it because it was mentioned in the original report/post.

**Comment by Alys** [comment]
Ah! I had missed something: mentioning Group Plans as well as Challenges, thank you. :)

.... Which is actually MENTIONED in the top post in this issue. The post that I wrote. :laughing: 

I'm reopening this and I'm about to edit the top post to explain what still needs to be done.

**Comment by citrusella** [comment]
If I get the same behavior on my local install, does that mean only the string needs updating? (If so, I could do this pretty quick right now...)

**Comment by Alys** [comment]
@citrusella Sure, go for it! Thanks. :)
