### ISSUE TITLE
future Start Date for a Daily does not appear in the Next Due Dates list

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8838]
If you set a Daily's Start Date to be in the future and use the "Daily", "Monthly", or "Yearly" repeat type, then the start date does not appear in the "Next Due Dates" (see example below).

The same problem does not occur for the "Weekly" repeat type.

![image](https://user-images.githubusercontent.com/1495809/27536577-bfc4f1e8-5a67-11e7-9114-972edd071cda.png)

_Thanks to Il Mago Rosso for reporting this in the Report a Bug guild._

**Comment by bwrightson** [comment]
@Alys First-time contributor. I took a look at this code and it seems reasonable to fix. Can I work on this?

**Comment by bwrightson** [comment]
@Alys Checking in!

**Comment by Alys** [comment]
@bwrightson So sorry we didn't reply! Yes, if you'd like to look into this, please do.

**Comment by lemoness** [comment]
This is not currently relevant because we don't display those in the new site, so we're closing this for now, but we can always reopen it in the future.
