### ISSUE TITLE
"monthly" Dailies cannot be set to "Day of the Week"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8839]
When editing a Daily's repeat settings, if you select the "Monthly" repeat frequency, and try to change to "Day of the Week", the console log shows the error "TypeError: e.map is not a function"

If you save your change and then go back into the edit form, you see that the setting has reverted to "Day of the Month".

**Comment by TheHollidayInn** [comment]
Does this PR fix this issue: https://github.com/HabitRPG/habitica/pull/8835?

**Comment by Alys** [comment]
Yes, the bug has been fixed.
