### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by TheAesthete** [HabitRPG/habitica#884]
When trying to register (not through facebook) from front page the 'Register' button vanishes as soon as text is input, preventing registration. 
There is also no text around it saying what is meant to be input into each of the four boxes... I don't know if that was intentional. 
Using latest version of IE9.

**Comment by lefnire** [comment]
Can you try using a different browser? Chrome or Firefox? Derby doesn't
play very well with IE9

**Comment by TheAesthete** [comment]
Not sure if I have another browser on that machine, just checked on the one I'm using now and looks like some tinkering is going on - I'll check this evening.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
