### ISSUE TITLE
API - Get challenges for a group does not allow `party` or `habitrpg` 

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8849]
## Description

Unable to call 
`https://habitica.com/api/v3/challenges/groups/:groupId`
with the groupIds of `party` or `habitrpg` 

This is inconsistent with several of the group routes, such as `https://habitica.com/api/v3/groups/:groupId`

**Comment by Alys** [comment]
FYI for any contributors working on this, the "habitrpg" value for the group ID is an alias for the Tavern. Looking in the API code for the group route that cTheDragons provided will show you code that can be copied to make this fix.

**Comment by melarish** [comment]
Looking at this. Trying to get back into contributing! At least the local setup runs smoothly now 👍 

Does this affect any part of the UI or only when you call the api directly?

**Comment by SabreCat** [comment]
@melarish: This should be API-only; we could update the frontend to use the fixed route, but frontend changes are on hold at the moment. So correcting this on the backend should be sufficient!

**Comment by melarish** [comment]
It doesn't look like there's tests for 'GET challenges/groups/:groupId' party or tavern challenges right now? I can see public/private guild and 'official challenge is present' in GET-challenges_group_groupid.test.js. Shall I do those first or would that be a different ticket?

**Comment by TheHollidayInn** [comment]
What do you mean by do those first, @melarish? Adding test and features for getting party challenges and habitica challengers would fix this issue.

**Comment by melarish** [comment]
Oh, I mean you can test either by UUID or the 'party'/'habitrpg' alias. I'm assuming getting challenges by group UUID works already? But it isn't tested as far as I can see. I'll add that test too
