### ISSUE TITLE
Take some cues/ideas from ProgressQuest?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#885]
I've recently come across ProgressQuest again, a fairly silly "game" that you basically let run and your character just does his/her own thing.

I was wondering perhaps some of these ideas could be incorporated into HabitRPG, but based on tasks completed rather than a progress bar you get the idea.

Or perhaps some other things you can use from it as inspiration, I don't know, but figured it might give you some ideas.

Website: http://www.progressquest.com/
Web based version: http://www.progressquest.com/play/

**Comment by cleave29** [comment]
Hmm, that would be cool.

**Comment by deilann** [comment]
Possibly move to Trello?
