### ISSUE TITLE
Negative experience points

### ISSUE THREAD

**Issue by pixellatez** [HabitRPG/habitica#886]
My experience bar has been displayed as full with a negative number showing for about a day or so (eg -43/200) I tried refreshing as well as an alternate device. Only been using for a week but loving it so far!!

![image](https://f.cloud.github.com/assets/4333669/460371/cf21b1a8-b41c-11e2-8275-8fd5a61d3aaa.png)

**Comment by pixellatez** [comment]
No longer an issue :)

**Comment by lefnire** [comment]
Wait whaaaat? did latest update fix this?

**Comment by pixellatez** [comment]
Not entirely sure. I noticed the change around the same time that I also saw the tavern option. I waited until today to see if anyone else would report something similar and didn't see anything but when I checked just now (been in and out all day) it was changed. I figured someone fixed something....
