### ISSUE TITLE
Cannot read property 'leader' of undefined in Group Plan Guild

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8862]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 7f14ed62-5408-4e1b-be83-ada62d504931
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When I visit a Guild I'm in with a free indefinite Group Plan (it's for Habitica staff, so it's not associated with actual payments), the JS console logs several `TypeError: Cannot read property 'leader' of undefined`. The group ID is acd1d6a1-8d77-4f1c-9210-eb73a572b337.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

![image](https://user-images.githubusercontent.com/4501321/28079328-80fca7f4-662d-11e7-9dad-b54601f51bed.png)

**Comment by Alys** [comment]
This also happens with normal group plans, possibly when the subscription has ended (so it could be related to a payment method not being there). I've been noticing it for days but forgetting to report it. It doesn't seem to do any harm.
