### ISSUE TITLE
cancel subscription message is incorrect for free subscriptions from group plans

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8874]
When you have a free subscription from a group plan, the Settings > Subscription page displays this error message just below the blue "Subscribed" box:
`String 'cancelSubInfoGroup Plan' not found.`

It should show instead show a message explaining that the owner of the Group Plan can cancel the Group Plan by going to the guild or party that contains the plan, clicking on the "Payment Details" tab, and then clicking on the "cancel" button. We fairly often see questions from plan owners about how to cancel and they're often looking in the Subscription page for that option, so having the message there would be helpful.

~@lemoness This will require website changes. Do you want this fixed before the website improvement project is finished or should it wait?~ EDIT: this is ready to be worked on

Thanks to DudleyPippin (dbe40e7b-e9b6-48b1-8fc4-124ab64239e2) for reporting this in the Report a Bug guild!

**Comment by lemoness** [comment]
@alys It should wait!

**Comment by Alys** [comment]
labels updated

**Comment by Alys** [comment]
I'm working on this.
