### ISSUE TITLE
problems with hitting enter in chat messages due to name mentions

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8875]
_This issue might not be needed because it might disappear once our website improvement project is finished but I'm recording it here since we now know about it. Thanks to citrusella, the serving wench for reporting it! The words below are hers._ 

Trying to press enter on the website breaks/doesn't work when in a block of text it considers a mention (particularly if there's no trailing space after the mention). Even if there's no actual name suggestion for it to select. In fact, that's probably the most bugged. If there's a name suggestion and/or the name is typed out already, it flops back and forth between the first letter after @ and the end of the mention each time enter is pressed (until it eventually somehow gets into a place in the message where enter works, though that might not always happen), but if there's nothing to suggest/select, it goes back to the first letter after @ and just... stays there no matter how many times you press enter. The workaround is to add a space after something the site considers a mention before using enter, but maybe that might not always be preferable? I dunno. 0_o Seemed weird so I figured I should report it.

**Comment by lemoness** [comment]
Is this still happening?

**Comment by Alys** [comment]
This no longer happens when I test for it. We can reopen this if anyone else notices it.
