### ISSUE TITLE
loading screen tip 27 needs to be changed from describing "yesterdailies" to Record Yesterday's Activity

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8876]
As mentioned by Guy Geva in the Bug guild, the loading screen tip 27 describes how to create [yesterdailies](http://habitica.wikia.com/wiki/Dailies#Yester-Dailies): "Make late-night Dailies refer to the night before (such as “flossed last night”) so you can check them off in the morning."
It's still sort of relevant but much less than it used to be. 

Lemoness says it would be nice to change it to explain about Record Yesterday's Activity instead.

Wording suggestions welcome.

**Comment by librarianmage** [comment]
Would something like "Record late-night Dailies in the morning using the Record Yesterday's Activity" work?

Also, once the wording is worked out, I can replace the text.

**Comment by SabreCat** [comment]
The tip can be broader in focus than that, methinks. Perhaps:

"Did a Daily yesterday, but forgot to check it off? Don't worry! You'll have a chance to record what you did before starting your new day."

@lemoness @beffymaroo any thoughts on the above?

**Comment by adbrandau** [comment]
@SabreCat I think your suggestion is about perfect. 

The only thing I would suggest is mentioning function i.e. 

"Did a Daily yesterday, but forgot to check it off? Don't worry! You'll have a chance to record what you did before starting your new day **with Record Yesterday's Activity**"

**Comment by tiazahmd** [comment]
Hey guys, new to coding. Would love to help out with these minor fixes. Can you guide me on where I can find the appropriate files to modify for this? Also, for future reference, would you suggest how to dig these up etc. and contribute?

**Comment by SabreCat** [comment]
@tiazahmd: For updating text like this, you'll want to edit the English language locale files in `website/common/locales/en`. To find the specific string, I suggest using GitHub's search feature for relevant keywords (say, "late-night Dailies" here), or `git grep` on the command line!

**Comment by SabreCat** [comment]
Feel free to hop in to the [Aspiring Blacksmiths Guild](https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f) for a whole community of folks helping one another contribute to Habitica code.

**Comment by tiazahmd** [comment]
@SabreCat I was actually pointed to here from the Guild. So do I create a pull request for the file?

**Comment by SabreCat** [comment]
@tiazahmd Absolutely! Then we'll take a look and get it merged in if all's well.

**Comment by tiazahmd** [comment]
@SabreCat which branch do you use for submissions?

**Comment by MathWhiz** [comment]
Develop is the branch that all submissions branch off of.

**Comment by librarianmage** [comment]
@SabreCat Shouldn't this be closed?

**Comment by SabreCat** [comment]
@MathWhiz Yup, thanks! Must not have had the right "fixes" line in the PR.
