### ISSUE TITLE
Gear that grants no bonus shouldn't say it gives 1.5x

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8888]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

There's a confusing bit of text that can appear on starter class equipment that gives no bonus:

![image](https://user-images.githubusercontent.com/4501321/28430417-1a25624e-6d46-11e7-9974-096a2fd11ade.png)

Note "Confers no benefit." followed immediately by a blurb about 1.5x stat bonus. Experienced users will know that 1.5 x 0 is 0, but this is unlikely to make sense to anyone who's not familiar with the ins and outs of Habitica classes and battle gear. Perhaps "no benefit" items should skip the class bonus blurb?

**Comment by LunarGem** [comment]
Would someone like me to try this? I'm almost done with another PR, I could try this little one, too.

**Comment by Alys** [comment]
@LunarGem I'm sorry but it's best that this issue isn't done at the moment. The changes needed are purely in the client-side code, and we're most of the way though a project to rewrite that code, so any work done on this now would have to be re-done later. I'm putting this on hold until that project is finished. If you'd like to work on it then, you'd be welcome to!

**Comment by LunarGem** [comment]
@Alys Ah, ok!

**Comment by lemoness** [comment]
We've made many changes to the new website, so this doesn't appear to be an issue any more. I'm closing this ticket, but if you feel that it should be reopened for any reason, please feel free to leave a comment!
