### ISSUE TITLE
challenge tasks become untagged

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8892]
Sometimes tasks belonging to an active challenge will become untagged, without the task owner removing the tags.

I have not been able to replicate this bug but I've seen a few reports of it, notably from shanaqui. I'm logging this to help us gather data and investigate.

I suspect (but have no evidence yet) that this can happen when a challenge is edited and that it only affects the challenge owner's copies of the tasks. If so, it might be related to https://github.com/HabitRPG/habitica/issues/7449

I've confirmed shanaqui's most recent report of it, for two of the challenges that they own. Their own copies of the tasks became untagged. The tasks of other participants weren't affected. Both challenges had been edited after creation.

FYI, this tool by cTheDragons is helpful for investigating challenge bugs: [Challenge Data Tool](http://oldgods.net/habitica/cTheDragons/challenge.html). It collates information about the challenge and all its tasks, including task edit dates.

**Comment by lemoness** [comment]
Have we seen any recent reports of this issue?

**Comment by Alys** [comment]
Not recently. The issue to stop a challenge creator automatically joining a challenge is being worked on, and that will remove some reports similar to this, making it easier to identify if this does occur for people other than the creator. I'm closing this for now but will reopen it once we have a new confirmed report of it.
