### ISSUE TITLE
mana notifications are shown to users under level 10

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8893]
Under some circumstances, a player below level 10 can see a notification showing that mana has been removed. Mana should be invisible to the player until they reach level 10 and choose a class (not visible if they opt out of the class system).

I don't yet know what triggers the notification but I've just rebirthed so I'll watch for it.

This was reported by _Meakuel (4382653f-4dbe-4f0f-84dd-6127c8a6b466) in the Report a Bug guild: "I saw the message "-12 Mana". I am still not level 10 and this time it was the website version." They'd previously reported gaining mana on the Android app (https://github.com/HabitRPG/habitica-android/issues/793).

EDIT:

It seems that the mana notification appears when mana is removed, rather than when it's given. That would be a good place to start investigating what fix is needed.

**Comment by Neromaru** [comment]
As first thing that comes to my mind is to show mana but for characters whose level is below 10 set to 0

**Comment by Alys** [comment]
@Neromaru Before level 10, mana hasn't been introduced to the player yet, so they shouldn't see anything at all about it because it's confusing.

Admittedly, we don't do a good job of explaining mana when they reach level 10, but that might change in future.

**Comment by LunarGem** [comment]
@Alys If anyone wanted some user-focused language rewritten I could probably tackle that.

**Comment by Alys** [comment]
@LunarGem Best to wait for the current website code redesign project to be finished, but maybe after that. Thank you for offering!

**Comment by LunarGem** [comment]
This still on hold?

**Comment by lemoness** [comment]
The redesign is done, but I'm not sure that this is still happening. Have we had any recent reports?

**Comment by Alys** [comment]
I can't repllicate it. Closing. We can reopen if needed.

**Comment by fentie** [comment]
@Alys for what it's worth I think I encountered this bug just a few days ago:

```
@Fentie Hm, weird, I'll keep an eye out for more reports of this one.

Fentie (8f4a567a-038c-4c48-9941-fea2dc1d2845): "I signed into the mobile app this
morning and completed the RYA popup, resulting in some damage. When I later 
pulled up the web client, when the activity refreshed, I got notifications for gold/xp/etc,
plus the damage, and a notice of lost Mana. I don't think the mana notification should
have appeared since I don't yet have a mana bar."
```

**Comment by Alys** [comment]
@fentie Thank you! I've reopened this issue and adjusted the labels and top post.
