### ISSUE TITLE
Translators suggest minor changes to some locale strings

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#8917]
As noted and/or suggested by translators, some strings may benefit from slight changes:

Key - Suggestion - Reasoning
- [ ] enterprisePlansEmailSubject - should better be static as suggested by @mokovec - confirmed by @SabreCat https://github.com/HabitRPG/habitica/pull/8729#issuecomment-318910450
- [ ] deleteSocialAccountText & incorrectDeletePhrase - need token (variable) for DELETE - translators shouldn't translate this keyword as suggested by @Alys 
- [ ] noSudoAccess -  it will be better to have it static - because it's easy for translators to misunderstand the message (because the message is so cryptic) as suggested by @Alys 
- [ ] userItemsNotEnough - may be rephrased into *You do not have enough <%= type =%>* - as suggested by @Alys 
- [x] armorArmoireYellowPartyDressNotes - doesn't need the "Yellow Party Dress: " beginning - every other hairbow set items are directly starting by "you're perceptive / strong / smart..."

**Comment by pgoswami3** [comment]
@GitHubSphinx, I'd like to work on this issue & this would be my first open source contribution in the community.

**Comment by SabreCat** [comment]
@pgoswami3 Go for it, with our thanks! Be sure to comment here or in [the Aspiring Blacksmiths Guild](https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f) if you need assistance as you get started.

**Comment by pgoswami3** [comment]
Re:
@SabreCat 
1 & 3: I didn't get the "should better be static" part. Does it mean that the key should be taken out from the groups.json so that Transifex don't translate that part and hardcode to the jade file?

@Alys 
2. deleteSocialAccountText & incorrectDeletePhrase: Alys, can you please give me a little bit insight/relatable thread # on this one? Btw when I tried to delete my account with a wrong password, it didn't prompt/alert me with any message; is that a normal behavior? 

4 & 5: All good.

**Comment by SabreCat** [comment]
@pgoswami3: Re 1 & 3: Correct! I think you'll find those aren't even part of the Pug files; rather, they're in server code only. (If you do find them on the client somewhere, drop a comment here. I'd be curious where and why, hah)

**Comment by librarianmage** [comment]
@pgoswami3 Are you still working on this?

**Comment by pgoswami3** [comment]
@MathWhiz , Go ahead, all yours.

**Comment by librarianmage** [comment]
Thank you, but I'm not planning on working on this right now.

**Comment by lemoness** [comment]
I've updated the labels on this issue.

**Comment by perkyguy** [comment]
For my first contribution to this project, I took a stab at this issue. Since the In Progress label got removed, I figured it was up for grabs, and  I submitted a PR, #9297

**Comment by SabreCat** [comment]
Great, thanks @perkyguy !

**Comment by perkyguy** [comment]
@SabreCat , I didn't put in my UUID, if I still can, here it is e8be8049-ac14-401f-89ff-ce0aaa3445b4

**Comment by LunarGem** [comment]
I'm wondering faintly if "the potato issue" falls under this one...

**Comment by Alys** [comment]
The potato issue (https://github.com/HabitRPG/habitica/issues/3571) has a fair bit of discussion in it and seemed complex, so probably best to keep it separate from this issue. Although it looks like we settled on a fairly simple fix, so I'll update that issue's top post to try to enliven interest in it - thanks for the prompt, LunarGem! @perkyguy you don't need to consider the potato issue here. :)

**Comment by alfill** [comment]
Excuse me, a string "theseAreYourTasks": "These are your <%= taskType %>" in the tasks.json file better to be static, otherwise, I can't translate and it looks ugly - https://snag.gy/vBj9nH.jpg
