### ISSUE TITLE
I want to filter dailies by those active on a certain day

### ISSUE THREAD

**Issue by wizonesolutions** [HabitRPG/habitica#893]
I realized that on some of my dailies I need clearer daily goals to motivate myself to do them and not have to figure out what I was doing after a few days. So I wanted to plan the night before and use the comments fields to input my goals.

But I can't see at a glance which dailies will be active tomorrow. I could just go through them all and update the goals whenever I check them off (instead of all at once), but I'd like to do it all at once if possible.

I envision this working as follows:
1. A day filter bar appears at the top of the daily list, or maybe a cog appears that reveals it when clicked (to save space)
2. It's a drop-down: "show dailies due on [day dropdown]"
3. I pick a day
4. Interface hides all tasks not due on that day. This doesn't affect daily coloring, simply visibility.
5. A message appears telling me I am currently filtering dailies, and has an X to back out.

Then I can go through and edit comments, and then I can hit the X and come back to normality.

If someone can tell me an implementation strategy I might be able to take a stab.

**Comment by StanLindsey** [comment]
I foresee an extension to the tags interface working with this. E.g. bringing up the @tomorrow tag shows you what is going to be happening tomorrow. 

Ideally you'd also want to be able to bring up @tuesday or@friday as well for any tagged or tasks dated for this week. 

Smart-tags.

**Comment by heyimzsa** [comment]
The new tags have been implemented. Maybe you can tag them By days of the week?

**Comment by wizonesolutions** [comment]
I don't want to manually tag them...not worth it. But @SlappyBag's idea is pretty solid and would work for me.

**Comment by StanLindsey** [comment]
I'm actually going to have a bash at this tomorrow. I think it would be really handy and is definitely do-able.

**Comment by wc8** [comment]
This is: https://trello.com/c/HzlNeTQB right?
