### ISSUE TITLE
Blank task page even after clearing tags/search

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#8936]
### General Info
  * UUID: bb089388-28ae-4e42-a8fa-f0c2bfb6f779
  * Browser: Chrome
  * OS: Windows 10

### Description
Sometimes when I return to the task page, it's empty. Clearing tags and the search box don't restore my tasks; only refreshing the page completely. It seems to happen at random; I can't trigger it to occur, and I can't identify a pattern. Reporting per Alys' request. :)

It did once throw a "502  - Web server received an invalid response while acting as a gateway or proxy server" error at the same time. Alys noted that I'd been buying gems with gold at the time, maybe clicking too fast; I had the Habitica Magic Wand extension active, and that was buying gems/applying actions whenever I reloaded the page. However, de-activating it didn't prevent the blank task list from reoccurring, so it's currently re-enabled.

Also spotted Lalaitha and Ameera NM mention a possibly related issue in the Tavern:
Ameera NM: Hey guys! My Dailies aren't loading , today. How can I fix this? 
Lalaitha: Ameera NM are you on the website? Try refreshing the page. It has happened a few times to me this week, too, but refreshing/reloading the website fixes it.

(Refreshing didn't fix it for Ameera NM, so it may not have been the same issue.)

#### Console Errors
N/a?

**Comment by Alys** [comment]
This might be a purely client-side problem but it seems to have started very recently so it might instead be related to some server changes that have been made recently.

It was also reported in the Report a Bug guild 6 hours before now by AnariaLaurelin (436ddc93-cd2c-4fc0-aeba-3af6a1621c41):
"occasionally when I click Tasks from another page on the site all my tasks disappear unless I reload the page! Thank you for looking into this!"

**Comment by Alys** [comment]
Interestingly, Ameera NM (520d1298-afa5-4760-a28e-84c3eb778cd9) who is mentioned in shanaqui's message has also posted this to the Report a Bug guild, indicating that the problem was on both app and website (which points towards server problems):

"Hello! My Dailies on the Android App aren't loading. Tried refreshing it several times & I've even logged in the website but no avail. Thanks for helping :)"

I've checked both Ameera NM's and AnariaLaurelin's Dailies (without looking at task titles or notes) and they both have Dailies with `isDue` set to true.

**Comment by Lalaitha** [comment]
I have had the same issue for some days now. Only on the website, though.
When it happens, I have usually had a tag selected before I go to a guild. When returning to the task page, it appears empty. Deselecting the tag does not help, only a complete reload, as Shanaqui mentions.

![screenshot](http://i.imgur.com/cUdeBFF.png)

**Comment by shanaqui** [comment]
I can add that I don't usually select tags at all, so it's probably not to do with tags!

**Comment by majestic-owl448** [comment]
ID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
Display Name: Il Mago

It happened to me also, it has started after mid July, not sure exactly time it happened for the first time, but I'm sure it wasn't happening before that time.

When I return to the tab I have the task page open the tab reload or sync on it's own but no task is loaded, the only way is to use F5 to have tasks back! The sync button doesn't make them appear again. I use Google Chrome.

**Comment by lemoness** [comment]
Is this still happening to people?

**Comment by Lalaitha** [comment]
I haven't had any issues with it for at least a month. :)

**Comment by Alys** [comment]
Thanks @Lalaitha ! I haven't seen any reports of it either.
