### ISSUE TITLE
Timezone/cron issue despite Habitica picking up new timezone

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#8944]
[//]: # 
### General Info
  * UUID: bb089388-28ae-4e42-a8fa-f0c2bfb6f779
  * Browser: Google Chrome
  * OS: Windows 10

### Description

On the 9th, I went from Belgium (UTC+2) to the UK (UTC+1). I updated the time on all my devices, and am reasonably sure I refreshed Habitica. What's more, when I checked in settings, it shows the correct timezone (UTC+1), and my day start is still midnight. However, I've been cronning just after eleven (both times I noticed were 11.30, but that's probably just the first time I interacted with the site after 11). The first day I just put down to timezones, even though I was pretty sure I'd refreshed and updated things; the second day makes no sense, as Habitica shows my current timezone.

Yesterday, I actually cronned twice -- at eleven, and then again at midnight. My check-in counter went up, and I received damage, although the RYA pop-up I got was empty of tasks.

Reporting per Alys' instructions! :)

#### Console Errors
N/a

**Comment by shanaqui** [comment]
I've also now noticed I have lost all my streaks through this, including challenge streaks.

**Comment by Alys** [comment]
After talking with @TheHollidayInn about cron time zone issues I'm more certain this is an example of #9415 so I'm closing this in favour of that issue.
