### ISSUE TITLE
Custom Icon to items

### ISSUE THREAD

**Issue by sylvain5477** [HabitRPG/habitica#895]
Give us the possibility to add small image/icon to tasks (Todos, Dailies, Habits and Rewards) to make it more lively.
Maybe only 64x64 icon so that it would not eat to much space.

**Comment by heyimzsa** [comment]
I like this idea. I would be able to assign icons to differentiate between different types of habits.

**Comment by StanLindsey** [comment]
Added to Trello - check the ticket [here](https://trello.com/c/ECi4RD7d)
