### ISSUE TITLE
one day missing from nextDue field in every-day Dailies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8970]
The problem below was reported in the Report a Bug guild by Il Mago Giallo (c073342f-4a65-4a13-9ffd-9e7fa5410d6b), who I'm asking to subscribe to this issue's notifications so that we can ask further questions if needed.

**"some of my dailies due every day have as next due dates: 20/08/2017, 22/08/2017, 23/08/2017... Aug 21st is missing**
**I have added alysthisone [to the notes] on a couple that I've seen doing so. for now seems that challenge tasks dont have this issue, but tasks created by myself do"**

Here's one example with the text field removed: 
```
{
    "_id": "f450cb25-d7a4-4a50-8b49-977b70d44ae6",
    "isDue": true,
    "userId": "c073342f-4a65-4a13-9ffd-9e7fa5410d6b",
    "updatedAt": "2017-08-19T19:06:35.983Z",
    "createdAt": "2017-08-14T20:27:44.734Z",
    "reminders": [],
    "group": { "approval": { "requested": false, "approved": false, "required": false }, "assignedUsers": [] },
    "challenge": {},
    "attribute": "str",
    "priority": 0.1,
    "value": 4.759112700885761,
    "tags": [],
    "notes": "alysthisone",
    "type": "daily",
    "checklist": [],
    "collapseChecklist": false,
    "completed": true,
    "history": [
        {
            "date": 1502779362960,	// 	UTC: 2017-08-15 06:42:42
            "value": 0
        },
        {
            "date": 1502864594445,	// 	UTC: 2017-08-16 06:23:14
            "value": 1
        },
        {
            "date": 1502951181118,	// 	UTC: 2017-08-17 06:26:21
            "value": 1.9747
        },
        {
            "date": 1503035145267,	// 	UTC: 2017-08-18 05:45:45
            "value": 2.9253562257358428
        },
        {
            "date": 1503118916599,	// 	UTC: 2017-08-19 05:01:56
            "value": 3.853133245658556
        }
    ],
    "yesterDaily": true,
    "nextDue": [
        "2017-08-19T22:00:00.000Z",
        "2017-08-21T22:00:00.000Z",
        "2017-08-22T22:00:00.000Z",
        "2017-08-23T22:00:00.000Z",
        "2017-08-24T22:00:00.000Z",
        "2017-08-25T22:00:00.000Z"
    ],
    "weeksOfMonth": [],
    "daysOfMonth": [],
    "streak": 5,
    "repeat": {
        "su": true,
        "s": true,
        "f": true,
        "th": true,
        "w": true,
        "t": true,
        "m": true
    },
    "startDate": "2017-08-15T20:27:26.000Z",
    "everyX": 1,
    "frequency": "weekly",
    "__v": 10
}
```

Cron details:
```
{
    "_id": "c073342f-4a65-4a13-9ffd-9e7fa5410d6b",
    "profile": {
        "name": "Il Mago Giallo"
    },
    "preferences": {
        "dayStart": 0,
        "timezoneOffset": -120,
        "sleep": false,
        "timezoneOffsetAtLastCron": -120
    },
    "lastCron": "2017-08-19T05:01:55.323Z",
    "auth": {
        "timestamps": {
            "loggedin": "2017-08-19T05:01:55.323Z",
            "created": "2016-01-28T19:00:35.789Z"
        }
    },
    "_cronSignature": "NOT_RUNNING",
}
```

I've posted this to the Bug guild to get further information:

"Can you please pick any one of those Dailies and edit it to change the repeat schedule in some way (doesn't matter how), then save it, then edit it again to put back the correct repeat settings, and also put some different text into the notes for that specific Daily so I can find it again. I want to see if changing the repeat settings and then changing them back again forces the nextDue field to be updated correctly.
For the other Dailies, if you can, I'd really appreciate it if you didn't change them at all and then when the missing day arrives, post either here or on that issue to tell us whether they appear as due or not due."

**Comment by Alys** [comment]
The problem fixed itself, I think probably when the next cron ran. Here's the current nextDue section for the Daily above:
```
    "nextDue": [
        "2017-08-20T22:00:00.000Z",
        "2017-08-21T22:00:00.000Z",
        "2017-08-22T22:00:00.000Z",
        "2017-08-23T22:00:00.000Z",
        "2017-08-24T22:00:00.000Z",
        "2017-08-25T22:00:00.000Z"
    ],
```

However we still don't know what caused the dates to be omitted.

**Comment by lemoness** [comment]
We don't currently display this, but can reopen if it becomes necessary.
