### ISSUE TITLE
Connection error (both browser and app and through mobile internet)

### ISSUE THREAD

**Issue by Maxx115** [HabitRPG/habitica#8979]
I have tried a lot, but nothing seems to work. I have used both Chrome and Microsoft Edge. The app doesnt work either, through my internet at home and mobile. I cant provide any User-Informations as I cant access any. While searching I havent seen any similar issue or a notice of the servers being down.
![unbenannt](https://user-images.githubusercontent.com/30586848/29570019-8a5be05a-8755-11e7-9bcd-3a50db342a82.png)
EDIT:
Just now I was able to log in again. Sort of at least. The app and website are displaying the content again, but very unstable and I cant log in the website through my google account.
User-ID: 5b9b20ee-346b-426b-bb89-79c093a0df99

**Comment by ehSistemas** [comment]
Me too

**Comment by nikipound** [comment]
I'm having the same issue on Firefox with Windows 10 where I am unable to connect. I've been able to use my Android (Device: quark, Android Version: 23, AppVersion: Veresion 1.1.6 (1926)) and iOS apps only sporadically, but I keep getting messages reading, "Connection Error: You are not connected to the internet."

**Comment by deilann** [comment]
Same issue

**Comment by Maxx115** [comment]
At least I now know I am not alone. I was trying all I could already, reinstalled the app, cleared the browser history and cache and so on. I gueass now we have to wait until someone of the dev´s will notice it.

Also it seems to be completely down again.

**Comment by itsasooz** [comment]
Am also getting the 502 error issue: First with the entire page, then page partially loaded before one of the dialog bubbles returned the error.  Currently getting fully-loading page with much slower progress than normal.  

EDIT: And back to the 502 bubbles.  I will leave the page alone and hope it's just getting really popular.

**Comment by Maxx115** [comment]
Update: It seems to work fine now. I still dont know the reason, but it seems to be fine now.

**Comment by Alys** [comment]
There were problems with the server but they have been fixed now. We're sorry about the trouble!
