### ISSUE TITLE
Changes don't stay after closing window

### ISSUE THREAD

**Issue by nrstarr** [HabitRPG/habitica#898]
Frequently, whatever changes I've made in a session (added tasks, checked off dailies, anything) don't save when I refresh or open a new window - I'm back to exactly where I was before. It's sometimes accompanied by an "Offline - Reconnect" window that won't go away, but not always, and I don't have any issues with internet connectivity. I'm getting better results on beta.habitrpg.com (saw it recommended elsewhere on github) but it's still not perfect.

If it helps, I'm on Safari 5.1.7, Mac OS 10.7.5.

**Comment by switz** [comment]
Your best bet is to **always** refresh right before making any changes. The longer you leave the app open, the more likely it is to disconnect from the server and never send over it's changes. Let me know if it still is giving you issues.
