### ISSUE TITLE
IOS Habitica App not registering party

### ISSUE THREAD

**Issue by sushi-study** [HabitRPG/habitica#8982]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: b347cb46-eff5-41b0-9290-3d6355d374d6
  * Browser: any + ios app
  * OS: 

### Description
On the IOS Habtica App,Habitica is not registering that I am in a party. I joined a party around 5 days ago, and it would show up on the "Party" tab in the app. Earlier, I saw that the app is telling me to join a party (like I was not in a party anymore). When I am on the website, it shows my party.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Can you please report that to the app developers through the app's Menu > About > Report a Bug button? 

This GitHub repo is for the website, not the iOS app, although if you ever do have bugs with the website, the best place to report them is in the Report a Bug guild (see the comments in the new issue form here for more details).
