### ISSUE TITLE
can't get it working on localhost

### ISSUE THREAD

**Issue by pfraces** [HabitRPG/habitica#9]
Mongodb is running and the derby-todos example works as expected
log: http://gist.github.com/3954505

**Comment by lefnire** [comment]
Woops, sorry @pfraces - forgot to mention. HabitRPG uses profile configuration variables (including database URI which is causing the above crash). This so I can keep the code open source while using sensitive variables in the application. On Heroku those variables are set via `heroku config:set KEY1=VALUE1`, on localhost those variables are set in ~/.profile or ~/.bashrc.

These should be the necessary variables:
FACEBOOK_KEY, FACEBOOK_SECRET, NODE_DB_URI (eg, mongodb://localhost/habitrpg)
Anywhere there's `process.env` in the code, you'll need that variable set if it doesn't provide a default
