### ISSUE TITLE
Moderator Tool: Option to prevent new users from posting messages

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9008]
It would be nice to have a setting to temporarily turn off the ability of new users to post before allowed to do so by a moderator. This would be very helpful in situations where a single user (or several trolls) tries to make many accounts in a row to dodge a ban and spam chat.

Possible implementation:
1. All existing users are allowed to post.
2. Under normal conditions, all new users are allowed to post BUT:
3. There's a flag that mods can use that causes every new user account to be unable to post until a mod enables posting for that user. Mods only turn on that flag when a troll keeps creating new accounts.
4. When a user who is not yet allowed to post tries to post, their message appears in the chat area but visible only to mods (and it's sent to us in an email). There's an icon on the message that mods can use to make the message visible to everyone and to enable normal posting for that user.

There have been several times in the past when this feature would have been incredibly useful.

**Comment by Alys** [comment]
Duplicate. ;)  https://github.com/HabitRPG/habitica/issues/8063

I'm adjusting that old issue to contain some adjustments from this new one.
