### ISSUE TITLE
Bug in pet selection.

### ISSUE THREAD

**Issue by tellezhector** [HabitRPG/habitica#902]
Here is how to reproduce the bug:

-Select a pet (by example: Base Lion)
-Select a pet that is a modified version of the previous (by example: Shadow Lion)

Current behavior: You have no pet as companion.
Expected behavior: You should have the second pet as companion.

**Comment by StanLindsey** [comment]
Confirmed my end. Thanks for that @bloodyvesp. Looks like some sort of toggle behaviour is apparently - @lefnire & @switz will know more. 

Labled this issue as bug, minor, interface & pets.

**Comment by switz** [comment]
Found the issue, working on fixing it.

**Comment by tellezhector** [comment]
Woow! 
That was really fast. 

Thank you very much and happy coding :)

**Comment by switz** [comment]
Tested on https://beta.habitrpg.com as working. If you could validate, that would be great! Thank you.

**Comment by StanLindsey** [comment]
@switz is a ninja.

Works my end.

**Comment by tellezhector** [comment]
Validated. It works on https://beta.habitrpg.com (y)

**Comment by AndreCaseyScott** [comment]
There is a new bug in pet selection, similar but different than the one mentioned. Felt it would be best to reopen this one versus creating a new issue ticket for...an issue with pet selection.

When you go into the stable to change your pets, nothing happens. Meaning, when you select, lets say, the Zombie Panda, your active pet stays as the Base Wolf and does not switch to the Zombie Panda.

This only happens on Beta server (I tested Prod too, works fine), and I believe I have found the issue. In a recent commit (develop branch), all the Beta coffeescript files were changed to require "lodash" from "underscore". https://github.com/lefnire/habitrpg/commit/1596808c25bc20a3f152b7e09da8ef28bb56cdc9

I also noticed this error in Chrome Console: " Uncaught TypeError: Object function n(e){return e&&"object"==typeof e&&!yr(e)&&Kn.call(e,"**wrapped**")?e:new B(e)} has no method 'findWhere' "

After a quick search, it seems that LoDash does not support the .findWhere method, unless you are using the Underscore Compat version, suggesting ".find" instead. https://github.com/bestiejs/lodash/issues/206

And other Underscore->LoDash conversions have been made (specifically line 9, with "findWhere" being changed to "any"). https://github.com/lefnire/habitrpg/commit/60a4ce5888c3d5f8ecb2b6a392934d84606112bc

I do not have a development setup currently, and have no way to test an exact solution. My hunch is that replacing "findWhere" with "find" (or "any", like in that other commit) in "src/app/pets.coffee" will solve the error. Hopefully this is specific enough that one of the devs with it already setup can test/fix it in 2secs flat. ^_^

**Comment by lefnire** [comment]
now _THAT_ is how you report a bug! javascript errors, commit log browsing, and code file hunches. Bravo @onduhray, that helps so much!

**Comment by AndreCaseyScott** [comment]
thanks! glad it was helpful ^_^ maybe one of these days I'll get my dev setup for github and fix the bugs myself. At least I can be as helpful as possible until then. 

Thanks for being so responsive! :D

**Comment by lefnire** [comment]
hit me with your user id, you did the leg-work enough we'll consider it fixing this bug. [badge + gear](http://habitrpg.tumblr.com/post/51082061058/whats-with-the-downtime) (when the gear comes out, we have it designed but not yet coded in the system)

**Comment by switz** [comment]
open source ftw!

**Comment by AndreCaseyScott** [comment]
Awesome! Thanks :D 
73fad769-a194-4655-aefe-08bc7cb3dc39

**Comment by lefnire** [comment]
added badge & gems, see if thats' √ . will add gear one it's in, thanks again!

**Comment by AndreCaseyScott** [comment]
All good! No, thank you for creating such an awesome service that makes people want to make it better! I will try and fix some more, to cement me earning that badge ;)
