### ISSUE TITLE
When adding tasks to an existing challenge, they are not tagged

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#9029]
### General Info
  * UUID: bb089388-28ae-4e42-a8fa-f0c2bfb6f779
  * Browser: Chrome
  * OS: Windows 10

### Description
When I edit a challenge to add a new task, the new tasks aren't given the challenge tag for me or for other participants (checked on Ehlyah's account, 9c4776eb-7330-465b-85cc-e4ccef6c1ad1). The challenge in question is [this one](https://habitica.com/#/options/groups/challenges/52fbaf92-be04-43d5-9158-302c5cb4fd73). 

Even if I add the tasks via the staging site and deliberately select the correct tag (note that the challenge tag doesn't seem to be applied by default on the staging site when you create a new task in a challenge), the tag is not applied. 

This is a particular problem with this challenge because I'm going to be adding tasks to this challenge frequently over the next few days/weeks, and people might well want to filter by the tag (I certainly do). It's also an issue for challenges which involve adding discussion questions as people read a book/watch a series/etc.

Alys said this bug isn't currently reported and asked me to post here.

**Comment by Alys** [comment]
@shanaqui Just to confirm, this happens in the current production habitica.com site as well as the staging site, right?

**Comment by shanaqui** [comment]
Yep, tested on both to see if it'd be fixed on the staging site, but it isn't.

**Comment by Alys** [comment]
@shanaqui I'm sorry, this bug was reported before so I'm closing this one. My bad.
https://github.com/HabitRPG/habitica/issues/8004
