### ISSUE TITLE
VersionError prevents quest from ending (participants received rewards but quest was not removed from party)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9031]
If a VersionError occurs when a party's `group` object is being saved, it can leave a quest in an inconsistent state.

The report below from Gumnos (43e2413a-f440-43c8-b96c-85b93024488c) in the Report a Bug guild describes a quest that should have ended normally but didn't. From the user's description and from what I've seen in the data I have access to, it looks like all of Habitica's code for ending the quest did execute except that the final `group.save();` didn't work, meaning that the participants' accounts were updated to indicate that the quest had finished (they were given the rewards and had the quest data from from their own `party` objects) but the party itself didn't have the quest data removed. 

Loggly shows a VersionError for what I believe was the event that should have saved the change to the party.

Gumnos's words are in bold and I've added comments in italics.

**Just had a weird quest experience (Mandrill/monkey quest) where my lvl 98 warrior did a one-shot kill on the boss (repeated use of Brutal Smash).**

_I confirmed in Amplitude that enough damage had been done to kill the boss (health 400). There was a non-resting cron at 2017-09-08 08:36:56 UTC with a progressUp of 429.6083716046._

**It completed the quest and my party received the eggs as spoils.**

_Gumnos posted later to say that they're pretty sure the normal quest completion modal appeared. I confirmed that one quest participant had three eggs and the other had three Monkey pets. I'm confident they were received from that specific quest because they were at the end of the `item.pets` and `items.eggs` objects (which indicates that they'd most likely been added after all other eggs/pets). The previous pet quests had been Horse, Whale, and Seahorse, and the Monkey items can be seen after all of those eggs/pets. The participants have only one achievement for the Monkey quest._

**I attempted to start another quest, but couldn't because it for some reason the system thought we were still on a quest. Checking the Party page showed we were still on the Mandrill quest (the boss still had an almost-full health bar, likely just the couple points of damage done by the other person in my party).**

_This is consistent with the database still containing the data from that quest._

**Completing additional tasks didn't show the little "compass" in the top right where pending damage appears, so it was like I was simultaneously on the quest but unable to do damage. To start another quest, I had to abort the Mandrill quest that was "in progress" . Upon doing that, the Mandrill quest appeared back in my inventory such that I could attempt it again, even though I'd already completed it.**

_That's all consistent with the participants' quest data being correctly removed from their own accounts._

The party ID is 3a50e305-96c9-47bb-8e5e-91cae9c6f30f and here are all of the chat entries that relate to the quest:
```
	{
		"id": "01c5b85a-bc72-4bae-9f73-54190ec7c4e8",
		"text": "`Gumnos aborted the party quest Monstrous Mandrill and the Mischief Monkeys.`",
		"timestamp": 1504887628066, //      UTC: 2017-09-08 16:20:28
		"flagCount": 0
	},
	{
		"id": "4b925c87-f506-45b9-b3b2-41f88fcbb3a9",
		"text": "`XxxAnotherPlayerXxx attacks Monstrous Mandrill for 14.6 damage.` `Monstrous Mandrill attacks party for 0.0 damage.`",
		"timestamp": 1504859816363, //      UTC: 2017-09-08 08:36:56
		"flagCount": 0
	},
	{
		"id": "5914f3fc-c7a4-43d3-9425-475ee4031880",
		"text": "`Your quest, Monstrous Mandrill and the Mischief Monkeys, has started.`",
		"timestamp": 1504806236380, //      UTC: 2017-09-07 17:43:56
		"flagCount": 0,
	   "_meta": {
			"participatingMembers": "[another player], 43e2413a-f440-43c8-b96c-85b93024488c"
		}
	},
```

Here's the [VersionError from Loggly](https://habitica.loggly.com/search#terms=43e2413a-f440-43c8-b96c-85b93024488c&from=2017-09-07T00%3A00%3A00.000Z&until=2017-09-08T09%3A00%3A00.000Z&source_group=):
```
2017-09-08 18:36:57.054
tag:Winston-NodeJS
logtype:json
http:
contentType:application/json
json:
httpCode:500
isHandledError:false
level:error
message:Error
    at model.wrappedPointCut [as save] (/usr/src/habitrpg/node_modules/mongoose/lib/services/model/applyHooks.js:109:29)
    at model._callee10$ (/usr/src/habitrpg/website/transpiled-babel/models/group.js:1172:26)
    at tryCatch (/usr/src/habitrpg/node_modules/regenerator-runtime/runtime.js:65:40)
	[snip]
POST
originalUrl:/api/v3/cron?userV=83427
timestamp:2017-09-08T08:36:57.054Z
fullError:
message:No matching document found for id "3a50e305-96c9-47bb-8e5e-91cae9c6f30f"
name:VersionError
stack:Error
    at model.wrappedPointCut [as save] (/usr/src/habitrpg/node_modules/mongoose/lib/services/model/applyHooks.js:109:29)
    at model._callee10$ (/usr/src/habitrpg/website/transpiled-babel/models/group.js:1172:26)
    at tryCatch (/usr/src/habitrpg/node_modules/regenerator-runtime/runtime.js:65:40)
	[snip]
headers:
	accept:application/json, text/plain, */*
	accept-encoding:gzip, deflate, br
	accept-language:en-US,en;q=0.8
	connection:Keep-Alive
	content-length:0
	host:habitica.com
	max-forwards:10
	origin:https://habitica.com
	referer:https://habitica.com/
	x-api-user:43e2413a-f440-43c8-b96c-85b93024488c
	x-arr-log-id:8ca407cd-a8a9-44a3-bfab-dd237ff797fb
	x-original-url:/api/v3/cron?userV=83427
	[snip]
```

**Comment by TheHollidayInn** [comment]
I'm pretty sure my chat PR fixes this. I'll link it.

**Comment by beffymaroo** [comment]
@TheHollidayInn In this still in progress, or should it be closed?

**Comment by paglias** [comment]
This should be fixed now that the Chat is in its own model
