### ISSUE TITLE
when I logon to habitica I get a white screen, apparently a white modal covers all the site with high z-index

### ISSUE THREAD

**Issue by dataf3l** [HabitRPG/habitica#9048]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment]
Please go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there. Does that help?

**Comment by dataf3l** [comment]
This was the old version, I think the new version behaves differently
