### ISSUE TITLE
password reset process fails if a user's email address has upper-case letters

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9059]
If a user's email address in Habitica contains any upper-case letters, when they use the password reset form, their account is not given a value for `auth.local.passwordResetCode` and they do not receive a password reset email. This happens even if they enter their email address into the reset form using the exact case that it's stored in in Habitica.

If their email address in their account is changed to all lower case, the password reset form works correctly, no matter whether they enter their email address into the form in the same case as it's stored in Habitica or a different case.

This looks like the code to be changed:
https://github.com/HabitRPG/habitica/blob/136947169b466ed02b12a151c4576c791154a069/website/server/controllers/api-v3/auth.js#L563-L564
The find command should be case-insensitive and the `toLowerCase` won't be needed.

**Comment by matchajune** [comment]
Hello!

What is the current status of this issue? I am very interested in tackling this issue and would like to get confirmation to proceed.

Thanks!

**Comment by Alys** [comment]
@matchajune Thank you for asking! However @outofthisworld has actually submitted a PR so a fix is underway. Hopefully you can find another issue that you're interested in though! 

@outofthisworld It's a good idea to post on an issue before you start work on it to avoid any chance of two people working on the same problem at once. :) It also gives admins a chance to give any information that might not be in the PR yet or to advise you to hold off if we realise that the issue is no longer suitable for working on (that can happen with some of the older issues especially). Have a look at [Using Your Local Install to Modify Habitica's Website and API](http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) for some other tips. I'm marking this issue as in progress now, for your fix. Thanks for submitting it!

**Comment by Alys** [comment]
This issue is open again for someone to work on it. @matchajune If you're still interested, comment here and we'll mark it as in progress for you. If you're busy now with other work, that's fine and then someone else can pick this up. :)

**Comment by matchajune** [comment]
I will take it!! Thank you so much!

**Comment by Alys** [comment]
Awesome, thanks @matchajune!

**Comment by matchajune** [comment]
Hey @Alys ,

I submitted a solution for this issue. I went about the solution a little bit differently than suggested in the initial comment. I explained my thoughts in the pull request and would love your feedback. I look forward to your response!

**Comment by paglias** [comment]
The code looks good so I'm fine merging this but I'll wait before adding the tested and approved tag if @Alys has any remaining concern

**Comment by Alys** [comment]
@paglias Thanks! I've commented in the PR.
