### ISSUE TITLE
Cannot create new tag

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#906]
I cannot create a new tag from the task edition interface (I guess this is normal), and I cannot create a new tag from the form below my avatar.

When I type a new tag and click "add", nothing happens in the page and the web console says "TypeError: [object Object] is not an Array".

**Comment by lefnire** [comment]
ah i see, somehow the initial `user.tags` is being set to an object rather than an array. I'm running a migration script and this should be fixed, i don't know why that first blank tag is showing up, but that's the issue right there

**Comment by lefnire** [comment]
i'm going to leave this open for a bit, but the problem should be solved now. new users get a default tag setup, so they're ok - existing users have the migration fix, so they should be good - just wanna make sure no existing users still experience the problem

**Comment by Eusebius** [comment]
Looks good for me now.

**Comment by MercuryChaos** [comment]
I'm having a similar problem - can't add tags via the task edit screen, and I don't see anywhere else to add them. I tried clearing my browser cache and it did nothing.

**Comment by lefnire** [comment]
click edit next to tags at the top, then add a new one there
https://www.evernote.com/shard/s17/sh/09d223f5-f26b-430c-b5a2-c75c29a64b60/a7c1e84e83f12837fe3427b90c976f93-
will make more obvious later / add from edit screen, but needed to
roll
with v1

**Comment by MercuryChaos** [comment]
Okay, I can see it now. Thanks.
