### ISSUE TITLE
VersionError during cron might cause entire cron to fail - non-fatal error handling needed?

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9068]
In the Report a Bug guild, TNoth (2a791021-b07e-4046-ba3b-474f76e9d2e0) said "I am currently in a quest and when I logged on today, it did not show any damage inflicted on the boss." I confirmed that the quest portion of cron had not run. Loggly shows a VersionError during that cron: `No matching document found for id "f813fa26-bca2-48e5-bee0-e2a7303ff7b9"`. That uid is for one of TNoth's Dailies. I'm guessing the VersionError might have caused cron to stop? If so, it would be good if errors occurring within cron did not prevent cron's other actions from taking place.

**Comment by TheHollidayInn** [comment]
The issue is that when saving the user with all the new cron data, mongo rejects the save. The issue is that notifications is in an array and modified in parallel with the read notifications route.

The first solution should be to move the notifications off of the user.

**Comment by Alys** [comment]
But wouldn't that cause a VersionError for the player's User ID? The VersionError in this case specifies a task ID.

**Comment by TheHollidayInn** [comment]
Ah, I missed that. Then this is related to the task history or task checklists. The checklist error happens during task saving/editing, so I am leaning towards that to be inspected.

**Comment by Alys** [comment]
@TheHollidayInn is working on concurrency fixes that should help with this.
