### ISSUE TITLE
API should block purchase of high-level basic class equipment until low-level gear is bought

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9071]
Currently, the API allows you to purchase any of the basic class-specific gear, regardless of whether you've bought lower-level pieces. For example, using the API you can buy the Warrior's Golden Sword before you've bought the Warrior's Training Sword.

The API should prevent this.

**Comment by matchajune** [comment]
Hello @Alys !

Just want to confirm if anyone is working on this before I take it.

Thanks!!

**Comment by Alys** [comment]
@matchajune Thank you! It's all yours. :) Comment here if you have questions or run into trouble.
