### ISSUE TITLE
All Items are gone

### ISSUE THREAD

**Issue by PaulFreund** [HabitRPG/habitica#908]
I crated a few tags (upper left corner under the status bar ) and removed them after that. Now all my items ( tasks, habits, dailys ) are gone. There are no error messages in the chrome console and reloading / relogin didn't help.

**Comment by lefnire** [comment]
what's your user id

**Comment by PaulFreund** [comment]
9eb8c612-9b98-45e4-9a50-eb92683972db

**Comment by lefnire** [comment]
Hmm, all your tasks are still there - what happens on a refresh? I'll test
locally in a bit

**Comment by PaulFreund** [comment]
On a refresh unfortunately nothing happens, no fast flashing and then the items vanish, they are just not there. I logged in with chrome private mode to see if it is anything thats stored locally but same thing there. Thanks for working on this so fast!

**Comment by switz** [comment]
@lefnire, might this have to do with refLists => arrays?

**Comment by lefnire** [comment]
Ahh, you found a good bug. If a filter is deleted but applied, you can
never un-apply it. I just removed the filter for you, and i'm going to fix
the bug now

**Comment by lefnire** [comment]
Ok, it was indeed being handled properly... I think you may have just
gotten hit on a bad connection time. I'm going to close this and if it
comes up again re-open, you should be sorted now though

**Comment by PaulFreund** [comment]
Great, but are there good bugs :D? Unfortunately I can't log in anymore, my login name is no longer recongized, any ideas?

**Comment by lefnire** [comment]
hmm, some server issues, I apologize... try again?

**Comment by lefnire** [comment]
i might recommend using beta.habitrpg.com primarily, it's got fewer users so is typically more stable

**Comment by PaulFreund** [comment]
:) Thanks for fixing this! Now I can finally be productive again^^. I'd use the beta version but I most enjoy the party feature and none of my friends uses the beta. Thanks for this great idea, It really helped me to get a bunch of things done.

**Comment by switz** [comment]
The beta runs off of the same database. You can play on beta with your friends running on the main site.

**Comment by PaulFreund** [comment]
Oh, good to know! I didn't know about the beta feature until now, you could probably announce it somewhere so more people can consider it ( I also think it can help you developing with more tesers ). I'll try it
