### ISSUE TITLE
add confirmation step to "begin" button for quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9083]
Quest owners sometimes click the "Begin" button on a quest before party members have had a chance to accept/reject the invitation because they don't understand what the button is for.

We want to add a confirmation screen that displays this text:
**"Are you sure? Only X of your Y party members have joined this quest! Quests start automatically when all players have joined or rejected the invitation."**
where X and Y are replaced by appropriate numbers.

The buttons on the confirmation screen should be **"Not yet"** and **"Start Now"**

_The Android and iOS versions of this issue are https://github.com/HabitRPG/habitica-android/issues/804 and https://github.com/HabitRPG/habitica-ios/issues/487_

**Comment by SSKUltra** [comment]
I could work on this once the habitica local is fit for contribution.

**Comment by Alys** [comment]
@SSKUltra Would you still like to work on this? If so, we'd love you to - let us know and we'll mark this as in progress. Local installs should work now but if you run into any problems, as in the Aspiring Blacksmiths guild.

**Comment by SSKUltra** [comment]
@Alys I would love to work on this right away. Thanks for the update.

**Comment by lemoness** [comment]
@SSKUltra Thank you so much! We're excited to see your fix.

**Comment by SSKUltra** [comment]
**Update on the issue**
@Alys and @lemoness, I have made changes to the code to fix this issue. Local testing seem to work fine, so I have submitted a PR.
