### ISSUE TITLE
Question: lost HP when all dailies completed

### ISSUE THREAD

**Issue by katowulf** [HabitRPG/habitica#909]
Hello!

I completed all my dailies yesterday, but when I came in today I lost 10HP. 

Do the habits or todo items cause me to lose HP at some point? Is the algorithm basic enough to explain it, so that I can determine if I'm seeing a bug or an expected behavior? (feel free to point me to some area of code if the calculations are centralized).

Cheers,

**Comment by StanLindsey** [comment]
This is a bug, dailys are the only things that hurt you automatically. Unless you are using and extension which would  hurt you and then used the website afterwards. Do you use the chrome extension or any others?

**Comment by katowulf** [comment]
I'm not using any extensions for Habit, although I am using Chrome on 64bit Windows 7.

![image](https://f.cloud.github.com/assets/959972/472419/cbabb358-b731-11e2-9d0b-9cd93b6be530.png)

Is there any debugging I could turn on to help troubleshoot?

**Comment by StanLindsey** [comment]
Hit F12 and go to the console tab. See if there is anything there. I doubt there will be till the same time tomorrow. 

Let us know if the same thing happens tomorrow or if it was a one off. To get your 10HP back to go Settings > Danger Zone > Restore to set yourself to where you should be. 

Thanks again.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
