### ISSUE TITLE
Cannot Get Past the "New Stuff" Announcement Popup Dialog

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#9095]
I can't figure out how to get to the Report a Bug guild from my browser; the entire website is obscured and I can't even scroll past. Feel free to redirect this bug as appropriate.

### General Info
  * UUID: Cannot get to the page with the information
  * Browser: Internet Explorer 11
  * OS: Windows 7 SP1 x64 EN-US

### Description
I cannot get to any part of the website except for the first two paragraphs of the "9/28/2017 - HABITICA'S WEBSITE LEVELS UP!" announcement.

When I go to Habitica, I see a checklist of things and a prompt asking if I've done them yesterday. I click the button to proceed and then I see the first screenshot. I see the second screenshot after trying to scroll down.

#### Console Errors
See the screenshot.
![1](https://user-images.githubusercontent.com/1581929/31003904-fd3334ac-a4a6-11e7-8b43-e0824c0450e8.png)
![2](https://user-images.githubusercontent.com/1581929/31003902-fd2c3eb8-a4a6-11e7-98fb-d93e73175ef2.png)
![3](https://user-images.githubusercontent.com/1581929/31003903-fd2e25d4-a4a6-11e7-99ab-571e9af06d36.png)

**Comment by citrusella** [comment]
I think that's a known issue with multiple modals popping up at once right now. I believe you can dismiss Bailey's message (until the next refresh, the equivalent of "tell me later") by clicking anywhere in the non-news part of the page. It's not a fix, but it might be a doable workaround.

**Comment by Zian** [comment]
Thanks for the tip; it worked for me.
