### ISSUE TITLE
API allows a user to block themself from sending PMs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9097]
The API route `/api/v3/user/block/[userid]` allows a user to specify their own User ID for blocking. 

It should be changed so that it throws an error when you try to block yourself.

**Comment by pineapple-joe** [comment]
Hey, can I handle this issue?

**Comment by Alys** [comment]
@borisabramovich86 Yes, thank you!

**Comment by pineapple-joe** [comment]
Hey,
should the error message be something that exists,
or do I add a new message?
And if so, how to I go about doing it, with the i18n translation and all?

**Comment by lemoness** [comment]
The error message should read "You can't block yourself!" I'll let one of the devs chime in about the way to make it translatable.

**Comment by Alys** [comment]
Add the string to the appropriate file in locales/en/ and the translators
will handle the rest in transifex.
