### ISSUE TITLE
Account Constantly Resetting

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#910]
For all of yesterday and today, my connection to Habit has been going haywire. Every time I update and then navigate away or refresh, it erases most if not all of my new info. The issue seems to derive from the fact that it keeps saying "Offline - Reconnect".... every thirty seconds. 

None of my other websites are having any trouble, so it's not my internet. It's pretty frustrating - I spent fifteen minutes last night trying to update my dailies, and eventually I just had to go to bed with them unchecked and restore in the morning :/

Thanks!

**Comment by lemoness** [comment]
...And half of the time, pictures don't even load? 

Seriously, what is going on?

**Comment by switz** [comment]
Try using https://beta.habitrpg.com - my connection has been fine... so what browser and OS are you using?

**Comment by lemoness** [comment]
Beta does it too. Bizarre. Maybe it is my internet, somehow? But all my other sites have been working fine.

I'm using Safari, my mac is 10.6.8....

**Comment by lemoness** [comment]
...aaaaand now when I try to refresh, it gives me a 500 Internal Service Error nginx/1.3.15.... I can't even click on things.

**Comment by switz** [comment]
If you get a 500 Internal Error, the application is most likely in the process of restarting. I'll look into zero downtime restarts.

**Comment by lefnire** [comment]
May be too many subscriptions at this point (now with tavern). i'm going to
look into setting party subscription as just fetch, instead of subscribe.
@lemoness, are you in a party?

**Comment by lemoness** [comment]
Yes - three people total.

**Comment by lefnire** [comment]
can you give it a show now?

**Comment by lemoness** [comment]
A little better, but still having issues on and off.

I talked to a party member, and he said it also affects him, but not as
frequently as it has been affecting me...

**Comment by lemoness** [comment]
Also - I just lost a potion because of this, which made me realize that the
Restore button doesn't have an option for potions and eggs :/

**Comment by StanLindsey** [comment]
Note: The restore button shouldn't have an option for potions & eggs. 

Which means the bugs losing token based purchases need to be fixed!

**Comment by lefnire** [comment]
And to email me if you lost token-purchaseables, I'll restore you

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
