### ISSUE TITLE
problems with autoallocation of stats

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9107]
From Destan53 (380a5fa2-0938-4cc1-8357-89acf2d7e503) in the Report a Bug guild:
"I think that the automatic allocation of attribute points isn't working, previous to the change of the site I had the mode of "Distribute attribute points evenly", but last night after the changes I went up one level, and the attribute point that should've gone to Constitution went to Strength instead, as you have suggested I've refreshed the site (multiple times), but nothing happened and the attribute point is still in Strenght. Any recomendations about this?"

**Comment by TNychka** [comment]
@Alys I'm willing to take a look at this.

~Quick question first, do we know that this was unintended? I would interpret Distribute attribute points evenly as sending a point to each of the in repeating order ie str -> con -> int -> per ->str -> con -> int ... ect.~

~The other interpretation I have is that all stats should be leveled to the same value by lowest priority and ties split randomly. ie str: 1, con: 10, int: 11, per: 5 the point would go to str until it was equal with per ie. str: 5, con: 10, int: 11, per: 5 at which point the stat allocation would become random between str and per.~

I will investigate to see what it is currently doing.
Edit: Strikethrough no longer relevant content.

**Comment by TNychka** [comment]
Currently, it looks like it assigns to the lowest valued stat
```case 'flat': {
      let stats = pick(statsObj, splitWhitespace('con str per int'));
      return invert(stats)[min(values(stats))];
    }
```
I can investigate further to see if this is the case. Is there any way I can get Destan53's user.preferences.allocationMode ? That would help in debugging. If it is flat then we have an issue if it is not (and is corrupt or some other value) then the issue is elsewhere as automatically allocating to str is expected behavior.

**Comment by TNychka** [comment]
Actually it looks like it defaults to 
```
    default: {
      return 'str';
    }
``` 
maybe their preference was not set? That would explain the behavior. Will investigate more.

**Comment by lemoness** [comment]
@TNychka Thanks for tackling this! 

I've updated the labels on this issue.

**Comment by TNychka** [comment]
@lemoness no problem, but I will need Destan53's user.preferences.allocationMode before I can proceed further.

**Comment by Alys** [comment]
@TNychka Destan53's current value of  user.preferences.allocationMode is taskbased but it might have been different when this issue was logged.

**Comment by TNychka** [comment]
Silly question: How do I change the allocationMode through the client? I can change it through the database or api no problem, but I can't do it through the client. When I turn automatic allocation on it defaults to taskBased, and I'm pretty sure all desktop client tasks default to strength. That would explain what is happening.

**Comment by TNychka** [comment]
@alys Cannot reproduce: classbased, taskbased, and flat all perform exactly as they should. I can see some other causes behind this however
- All modes default to str if something goes wrong. Maybe something went wrong?
- **What I assume the real issue is:** There is no method client side to select allocationMode. Mode defaults to taskbased when automaticAllocation is activated. All tasks default to strength. Basically as it stands: anyone who activates automaticAllocation will only ever get stats in strength.

I suggest that the last point is the real issue, and should probably be opened as a new issue.

**Comment by TNychka** [comment]
Second comment, why is there no way to set a task type on desktop? I know on mobile I can set int/per/con/str on a task. Should there be an issue for this too? Or is this planned functionality.

**Comment by Alys** [comment]
@TNychka Thanks very much for the investigation! It sounds like this was a once-off bug or a misunderstanding, or a bug that's already been fixed by other changes. I'm closing this but we can reopen it if we notice it happening again. I've added a mention in your tier notes in Habitica that you helped by investigating this.

It's a known problem that the current website doesn't have the correct interface for selecting allocation mode. I think one of the staff might be working on it, but if not, Lemoness or other staff will make a new issue for it. If you're interested in working on that yourself, post on this issue and I'll make sure the staff know about your post, but don't actually start work until you see a go-ahead reply, in case it is already being fixed.

> why is there no way to set a task type on desktop? I know on mobile I can set int/per/con/str on a task. 

Setting an attribute on each task is supposed to be possible only if you've selected the correct allocation mode. I think the mobile apps incorrectly allow you to set the attribute no matter what allocation mode has been chosen. It's not possible on the website either because it's not possible to select the appropriate allocation mode or because that interface element was forgotten/put on hold temporarily, or both. :) We'll look into that once the allocation modes can be chosen.

Thanks again for all the investigation and recommendations here!
