### ISSUE TITLE
api/v3/i18n/browser-script 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by ResamVi** [HabitRPG/habitica#9119]
I've got a local install of Habitica running with the website loading except for the text.

![screenshot from 2017-10-01 20-36-01](https://user-images.githubusercontent.com/6261556/31057835-6753c4b6-a6e9-11e7-9617-873a388e85a9.png)

With the following steps:
`npm start`
`npm run client:dev`
`using chrome on http://localhost:8080`

After visiting localhost:8080 the console logs the following message

`[HPM] Error occurred while trying to proxy request /api/v3/i18n/browser-script from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

In the browser console I get the following error:
`GET http://localhost:8080/api/v3/i18n/browser-script 504 (Gateway Timeout)`

This error occurs in this file
`http://localhost:8080/static/home` 

and i seems to be this line
```html
<script type='text/javascript' src='/api/v3/i18n/browser-script'></script>
```
I am using Debian Stretch and Google Chrome.
What seems to be the problem?

**Comment by paglias** [comment]
are you able to access `http://localhost:3000//api/v3/i18n/browser-script`

**Comment by ResamVi** [comment]
`localhost:3000` doesn't work at all. So trying `http://localhost:8080/api/v3/i18n/browser-script` just yields this text page:
`Error occured while trying to proxy to: localhost:8080/api/v3/i18n/browser-script`

`http://localhost:8080//api/v3/i18n/browser-script` 
points to your "Sometimes even the bravest adventurer gets lost." error page.

**Comment by ResamVi** [comment]
Okay, I got it to work.
What I mistakenly did was using `npm start` to compile and then `Ctrl+c` to kill the process afterwards and use `npm run client:dev` instead. But it suffices to use `npm start` and  navigate to localhost:3000.
