### ISSUE TITLE
API Docs broken

### ISSUE THREAD

**Issue by josher19** [HabitRPG/habitica#9125]
### General Info
  * UUID: 176ad08e-df92-4d19-94ba-23fe8a87ae9a
  * Browser: Latest Chrome & Firefox: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
  * OS: MacOS X 10.12

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
API Docs broken.

When going to https://habitica.com/apidocs/ get 404 Error and message:

```
{"success":false,"error":"NotFound","message":"Not found."}
```

#### HTTP Response Headers

```
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
ETag: W/"3b-zI2ygB3A5OSlt0Atu6+COA"
Vary: Accept-Encoding
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key,x-client
Date: Mon, 02 Oct 2017 18:32:06 GMT
Content-Length: 59
```

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
GET https://habitica.com/apidoc/ 404 (Not Found)

Text displayed in browser:
```
{"success":false,"error":"NotFound","message":"Not found."}
```

**Comment by AlexCaranha** [comment]
It's broken since September 29, 2017.

**Comment by paglias** [comment]
I've just committed a fix for this, it'll go live with the next deployment
