### ISSUE TITLE
Duplicated equipment in list

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9127]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
  * OS: macOS 10.12.6 (16G29)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
In the Task page, there is a list of equipments that you can buy. The seasonal ones are duplicated in my list.
![screen shot 2017-10-02 at 19 52 20](https://user-images.githubusercontent.com/3428149/31103126-d49d49bc-a7ab-11e7-84e7-e60bdc677d30.png)

**Comment by lemoness** [comment]
Thank you for reporting this! The good news is that this was due to a one-off bug with the migration, so you can simply unpin them and it shouldn't happen again. I'm closing this ticket, but it can always be reopened if something happens to change this.
