### ISSUE TITLE
Better usability for applying tags

### ISSUE THREAD

**Issue by Worky** [HabitRPG/habitica#913]
I can't completely remove tags from quests i tagged accidentally. Once i tag them, it's permanent and the only thing i can do is to change tagging category. Could it be possible to add this feature too?

**Comment by lefnire** [comment]
have you control-clicked the tag in the task edit screen?

**Comment by Worky** [comment]
Damm. How did i not think of that!

Delete this thread or better throw it into the Abyss!

**Comment by lefnire** [comment]
naw, we need to improve its usability. not the ideal adding method currently, but was easier to implement short-term.  i'll keep this open for reference

**Comment by paglias** [comment]
Is this still a bug?
