### ISSUE TITLE
Bug with Tooltip in Choose class modal

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9132]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
  * OS: macOS 10.12.6 (16G29)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
![choose-class-modal](https://user-images.githubusercontent.com/3428149/31107192-192ed18e-a7c7-11e7-90d2-2c64b05d887d.gif)

Don't know if its related, but this error is in my console:
![screen shot 2017-10-02 at 23 20 26](https://user-images.githubusercontent.com/3428149/31107372-59706a86-a7c8-11e7-8794-34d8efbaf60e.png)

**Comment by rholinshead** [comment]
I'm interested in taking this issue, but what is the desired UX here? Should the black-box tooltip appear on hover and the text below the "Opt Out" label not ever be shown? I noticed it has both classes `d-none` and `d-inline-block` which both use `!important` for their `display` attribute... 

I can think of two options here:
- Remove the black-box tooltip completely
- Remove the text below 'Opt Out' completely

What do you think @lemoness ?

**Comment by lemoness** [comment]
@rholinshead Thank you very much for working on this issue! I'm tagging our designer @tressley who can help you come up with a good UX solution. 

I've updated the labels on this ticket.

**Comment by Tressley** [comment]
@rholinshead -- Thanks for taking a look at this! Let's remove the tooltip, but keep the text at the bottom. You can see reference the design here:

![image](https://user-images.githubusercontent.com/2686586/32106314-4af6b87c-baf9-11e7-8932-77066a3d6c9c.png)

**Comment by rholinshead** [comment]
@Tressley just wondering if you've had a chance to review the PR that addresses this?

**Comment by Tressley** [comment]
@rholinshead -- Looks good to me!
