### ISSUE TITLE
Undefined as Description

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9133]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
  * OS: macOS 10.12.6 (16G29)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When you don't have a description, your About section is `undefined` we should have something like `This user doesn't have a description yet` or just a blank section

![screen shot 2017-10-02 at 23 10 59](https://user-images.githubusercontent.com/3428149/31107220-4ff966c0-a7c7-11e7-81cc-9da2ff7873e3.png)

**Comment by lemoness** [comment]
The wording that should be used is "This Habitican hasn't added a description." and it should be in italics.

**Comment by librarianmage** [comment]
@lemoness Should a message saying "This Habitican hasn't added a photo." be used under the photo section if a photo hasn't been added?

**Comment by lemoness** [comment]
@MathWhiz Yes, I think that's very reasonable!

**Comment by pineapple-joe** [comment]
Hey, can I work on this one?

**Comment by Alys** [comment]
@borisabramovich86 Sure! Thanks!
