### ISSUE TITLE
Customize avatar modal doesn't highlight correct section

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9134]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
  * OS: macOS 10.12.6 (16G29)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When i select a different section in the customize avatar modal, the color of the sections doesn't change. It doesn't highlight the section i'm in. I don't know if that's suppose to happen, but it seems like that's the expect behaviour 

In this screenshot i'm in the Skin section, not the body section (the body icon is the one purple)

![screen shot 2017-10-02 at 23 17 33](https://user-images.githubusercontent.com/3428149/31107328-182a51cc-a7c8-11e7-86ef-558b1e89d544.png)

**Comment by lemoness** [comment]
This is due to an issue with our SVGs.

**Comment by Alys** [comment]
This looks to me like it's been fixed. Closing.
