### ISSUE TITLE
A-Z Sort should be based on species

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9135]
When sorting by A-Z in the Stable, the sort is applied to the leading color name rather than then animal name. This means all the Base animals are first, and it is a less useful metric than it should be.

**Comment by thefridge111** [comment]
I can take a look at this if noone else is. Should be simple enough to implement.

**Comment by Alys** [comment]
@thefridge111 Thanks! Please do!

**Comment by thefridge111** [comment]
I've had a PR out on this for a few weeks now without any feedback or movement, is there something I missed that I need to do?

**Comment by SabreCat** [comment]
@thefridge111 No, we're just buried in PRs at the moment, on top of a pretty big issue backlog. ^^; We've done some process tweaking this week, so it should be a little better going forward!

**Comment by thefridge111** [comment]
Ok! I'll take a peek at that backlog and see if theres anything I can pick off!

**Comment by lemoness** [comment]
Awesome! We look forward to seeing more fixes from you :)
