### ISSUE TITLE
There is no way to change class after closing the modal

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9142]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
  * OS: macOS 10.12.6 (16G29)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
The modal says that `you can enable class at any time under User -> Stats` but with the new design i couldn't find it.

![screen shot 2017-10-03 at 12 05 03](https://user-images.githubusercontent.com/3428149/31132414-1dc7cd24-a833-11e7-8167-d3647a3784a5.png)

**Comment by Alys** [comment]
@luanmuniz When you have questions about where to find things on the new site or how to do something, please go to Help > Ask a Question to ask there.

When you've found a bug, please report it at Help > Report a Bug. If we need you to copy it to GitHub, a moderator or staff member will advise you there, but almost always that's not necessary.

You can change class (or enable the class system) at User Icon > Settings. I'll check for incorrect text describing that and fix it - thanks for the pointer.
