### ISSUE TITLE
PressKit page is broken

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9143]
The presskit page on the new website is broken, see https://habitica.com/static/press-kit.

There are some issues in the code that prevent it from working

Code like this

```
img.img-rendering-auto.press-img(:src="`assets/images/presskit/${category}/${img}.png`")
```

won't work because for webpack urls to work they cannot use computed properties. So either define them manually or move everything to `/website/static` and then link the images as `/static/${pathToImageInStaticFolder}`

Also there are some files in `client/assets/images/presskit` that aren't images, in particular a `.zip` and a `.mp4`. Those should go into `website/static`

**Comment by librarianmage** [comment]
I have experience with the press kit page, so I can work on it.

**Comment by Alys** [comment]
@MathWhiz Thank you!
