### ISSUE TITLE
Merchandise page is broken

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9144]
The presskit page on the new website is broken, see https://habitica.com/static/merch.

There are some issues in the code that prevent images from showing up.
Code like this

```
iimg(v-if='merchant.logo' :src="`~assets/images/merch/${merchant.key}-logo.png`")
```

won't work because for webpack urls to work they cannot use computed properties. So either define them manually or move everything to `/website/static` and then link the images as `/static/${pathToImageInStaticFolder}`

**Comment by tim1234ltp** [comment]
I would like to help with this issue. Even though I only have experience with Bootstrap but not Vue, I will try my best with this issue.

**Comment by SabreCat** [comment]
Thanks, @tim1234ltp! Be sure to comment here or in the Aspiring Blacksmiths guild if you need any help.

**Comment by tim1234ltp** [comment]
Just posted my PR.
