### ISSUE TITLE
Remove user wrapping from common code

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9146]
`user.{fns/ops}...` is not used anymore by the new client so the code for it can be removed: there are some tests that still use the wrapping code and an occurence in the code itself.

**Comment by lemoness** [comment]
@paglias Is this still an issue?

**Comment by TheHollidayInn** [comment]
Yes, it is here: https://github.com/HabitRPG/habitica/blob/35b92f13a31c7eadd24219419f8da9a407c499f7/website/common/script/index.js#L231
