### ISSUE TITLE
Leaving Challenge has misleading buttons

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9149]
When you leave a running challenge, the pop up that asks  if you want to delete the tasks lets you click  "Okay" or "Cancel". Instead, these buttons should say "Keep" and "Remove".

**Comment by librarianmage** [comment]
I can do this!

**Comment by Alys** [comment]
@MathWhiz Go for it!

If you need to add new locales strings, can you give them long names something like `tasksKeep`, rather than short names like `keep`? Grepping the code base for all uses of a string's key is a nightmare when the key is a single common word. :)
