### ISSUE TITLE
I managed to get negative XP and negative gold.

### ISSUE THREAD

**Issue by stephanschielke** [HabitRPG/habitica#915]
![2013-05-08 21_16_50-habitrpg _ gamify your life](https://f.cloud.github.com/assets/401815/479462/2ee24de6-b814-11e2-9d86-11599b0273f1.png)

It happend after the daily "Day Start". I am using the chromium extension and tomatoes.
I am using different browsers (same browsertype but different locations).

It is nearly impossible to level up right now. The XP bar is full as you can see in the screenshot. I can't buy stuff in the store.

I am dead soon :-(

**Comment by lefnire** [comment]
Sort yourself out temporarily using Options -> Settings -> Danger Zone -> Restore (just set Exp & GP to something sensical), as a short term.  Follow up for when we make progress on https://github.com/lefnire/habitrpg/issues/838 (this is duplicate)
