### ISSUE TITLE
Accessibility Issue: Zoom Level

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9150]
We received the following report:

"Thank you for all your work on the new site. It certainly looks very smart and up to date. I do need to report a bug though that unfortunately is a show stopper for me. I am partially sighted and use large fonts and zoomed screens. This worked perfectly with the old site but the new site does not (yet) adjust to my zoom level, so I am unable to easily see all my habits/tasks or scroll through my party members on the top banner."

**Comment by lemoness** [comment]
Has this been fixed?

**Comment by Alys** [comment]
When I zoom in using my browser's zoom feature, the website in its current state behaves well and the font size increases as expected. The navigation menu fails because the User Icon becomes inaccessible but @TheHollidayInn is fixing that in a separate piece of work. :heart:

**Comment by Alys** [comment]
But if anyone is still experiencing this accessibility issue or any others we do want to hear about it! Commenting in the [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac) guild might be the the best way to report it.
