### ISSUE TITLE
Stable Count Incorrect

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9151]
We've received the following report:

"In the Stable, my count of how many pets I have no longer counts ones I have turned to mounts. I should have 46/90 pets. I now show 39/90 I currently have 7 pets turned to mounts that are greyed out."

**Comment by trvrfrd** [comment]
I've got a simple fix for this working locally, happy to open a PR if no one else is working on it!

**Comment by Alys** [comment]
@trvrfrd Thanks, please do!

**Comment by LunarGem** [comment]
Oh, I thought that was the intended behavior. I use it to count which holes I have so I can get my Triad Bingo. Should this be the correct behavior or am I just taking advantage of a bug? :)

**Comment by lemoness** [comment]
@LunarGem Hah, very clever. It's not the correct behavior, so it's definitely still a fix that needs to be made.
