### ISSUE TITLE
Streamline +create [task/habit/dailiy]

### ISSUE THREAD

**Issue by TheJoeSchr** [HabitRPG/habitica#9156]
The new style is really cumbersome with the "+create" button. 
I understand you want to know which kind of entity I want to create so you can pop up the specific modal, but I think a + button on each list would be better. Now I have to do 2 clicks to add a task. I like to add a lot of task at once, as quickly as possible, so I can move on with my day. This is now really cumbersome. Even better would be the old text input above each list, with multiple entries, than open up a batch of modals to edit it or even better parse it like the suggestion on the trello board.

thx for all your hard work!

**Comment by JoeSchr** [comment]
#

**Comment by paglias** [comment]
@JoeSchr we're working on a better design for this, it should be out in a few weeks!
