### ISSUE TITLE
Dropped items disappeared

### ISSUE THREAD

**Issue by ra100** [HabitRPG/habitica#916]
After completing task/habit, I found egg, another time I found hatching potion. I should have 1xEgg 2xPotions in my inventory. But I can see there only 1P, I tried to refresh.
And some tasks are back uncompleted after refresh. I used habitrpg in Opera before, now I'm trying Chrome, but still that same.

**Comment by lemoness** [comment]
This is the same issue that I have been having in https://github.com/lefnire/habitrpg/issues/910.

**Comment by stormyhearted** [comment]
I'm having this issue as well, and I am also using Chrome. It's also refusing to allow me to check in at the tavern- every refresh and I'm back out.

**Comment by ra100** [comment]
And I've just lost 2 eggs today, after drop, I've checked inventory, and it was empty :(

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
