### ISSUE TITLE
Internal watch failed

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#9166]
```

root@ubuntu:~/habitica# npm start

> habitica@4.2.1 start /root/habitica
> gulp run:dev

[08:26:03] Using gulpfile ~/habitica/gulpfile.js
[08:26:03] Starting 'nodemon'...
[08:26:03] Finished 'nodemon' after 70 ms
[08:26:03] Starting 'browserify'...
[08:26:03] Starting 'prepare:staticNewStuff'...
[08:26:04] Finished 'prepare:staticNewStuff' after 895 ms
[08:26:04] [nodemon] 1.11.0
[08:26:04] [nodemon] to restart at any time, enter `rs`
[08:26:04] [nodemon] watching: *.*
[08:26:04] [nodemon] starting `node ./website/server/index.js`
(node:1595) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2017-10-06T08:26:17.287Z - info: Express server listening on port 3000
2017-10-06T08:26:17.324Z - info: Connected with Mongoose.
[08:26:22] [nodemon] Internal watch failed: watch /root/habitica/website/assets/img/project_files/designs/unprocessed/wizard/final/3a151098-8c3d-11e2-9b2d-b1fa78c39718.png ENOSPC
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.2.1 start: `gulp run:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the habitica@4.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-06T08_26_22_472Z-debug.log
root@ubuntu:~/habitica# ^C
root@ubuntu:~/habitica#

```

**Comment by ghost** [comment]
And my logfile is like that.
`
root@ubuntu:~/habitica# cat /root/.npm/_logs/2017-10-06T08_26_22_472Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.4.2
3 info using node@v6.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.2.1~prestart: habitica@4.2.1
6 info lifecycle habitica@4.2.1~start: habitica@4.2.1
7 verbose lifecycle habitica@4.2.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.2.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/habitica/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle habitica@4.2.1~start: CWD: /root/habitica
10 silly lifecycle habitica@4.2.1~start: Args: [ '-c', 'gulp run:dev' ]
11 silly lifecycle habitica@4.2.1~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.2.1~start: Failed to exec start script
13 verbose stack Error: habitica@4.2.1 start: `gulp run:dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid habitica@4.2.1
15 verbose cwd /root/habitica
16 verbose Linux 4.4.0-93-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v6.11.4
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.2.1 start: `gulp run:dev`
22 error Exit status 1
23 error Failed at the habitica@4.2.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by ghost** [comment]
Had to do some modifications to my server, fixed.

**Comment by joe307bad** [comment]
I think I am running into this issue. Could you elaborate on how you fixed it?

**Comment by YogiGG** [comment]
+1
