### ISSUE TITLE
Installion seems to be stuck 

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#9167]
I installed habitica on my ubuntu 16.04 server, everything seems to be good, but after running npm start it seems to be stuck.
![image](https://user-images.githubusercontent.com/31951743/31270016-5845d7ca-aa8b-11e7-881a-ceb6be1bbba5.png)
Been like this for 10 minutes now.

**Comment by paglias** [comment]
It doesn't seem to be stuck, the server is running (Express server listening...), can you open localhost:3000?

**Comment by ghost** [comment]
Thanks for reply.
It returns me this error: `{"success":false,"error":"Error","message":"ENOENT: no such file or directory, stat '/root/habitica/dist-client/index.html'"}
`

**Comment by paglias** [comment]
@gkua ok that means the server is running correctly, now you should open a new terminal window or tab (without closing the current one or stopping the process) and run `npm run client:dev`, wait for that process to finish the first compilation (it takes some time) then you'll have the API accessible at `localhost:3000` while the website is accessible at `localhost:8080`.

We're working on updating the docs for setting up habitica locally. Let me know if you have more questions.

**Comment by ghost** [comment]
Is it possible to run provess even after after closing ssh? Tried nohup but seems to be no luck

**Comment by paglias** [comment]
@gkua I don't use ssh to run Habitica, sorry :( Maybe @SabreCat knows something

**Comment by TheHollidayInn** [comment]
Are you asking how to run multiple process after connecting to your server?

I'd recommend using docker compose if you are doing a remote server. But, you can just open multiple terminals, ssh into your server from each terminal, then run the server on one connection, and the client on the other. This will give you control without throwing process to the background.

**Comment by SabreCat** [comment]
Yeah, I just use multiple SSH terminals, that works out easiest. (I sometimes have upwards of 5 open... one for Webpack, one for server, one for grepping stuff, one for vim, one root XD)

**Comment by ghost** [comment]
I meant running the processes when closing ssh client eg (putty)
Example: open up 2 instances of ssh
Do npm start and on other instance npm run client:dev and close the putty’s
Right now id i close them, the processes stop aswell.

**Comment by SabreCat** [comment]
Oh, I see. You might be able to run them in a screen tab or something? I wouldn't advise it, though, as you do sometimes need to restart them manually (e.g. when changing locale strings, for `npm start`), and you get valuable debug information out of them as well (the `npm run client:dev` session will show you syntax errors if it ever fails to recompile).

**Comment by ghost** [comment]
Thanks for quick reply.
Yeah, i agree with your answer.
So.. let me be more clear, i have a desicated server where i connect to and host it on there, not on my local machine.
So basically, right now if i close the putty connection, it ends the npm processes aswell, is there a workaround about this? I agree, you would need to manually restart it sometimes, eg when changing something, but right now it acts like its on my local server, by that i mean whenever i close the putty connection, npm processes terminate aswell.

**Comment by SabreCat** [comment]
@gkua Yup, I use a remote server for Habitica dev too. There are various ways to run background processes on Ubuntu, but I just tried `screen` and it worked just fine: https://uisapp2.iu.edu/confluence-prd/pages/viewpage.action?pageId=115540034

**Comment by ghost** [comment]
Thanks, ill check it
