### ISSUE TITLE
Notification Dropdown Showing with Scroll Bars

### ISSUE THREAD

**Issue by IronWalnut** [HabitRPG/habitica#9173]
### General Info
  * Browser: Google Chrome
  * OS: Windows 10

### Description
[//]: # Notification area shows with scrollbars instead of expanding to correct size. This happens when I have none/one/several notifications.

![untitled](https://user-images.githubusercontent.com/12644611/31343743-7d51d3fc-acde-11e7-9536-48ce7da63464.png)

![untitled2](https://user-images.githubusercontent.com/12644611/31343794-abe55b1c-acde-11e7-99db-07b476c02588.png)

**Comment by maurnoc** [comment]
Hello @IronWalnut. If no one is currently looking into this, I will push a correction to fix the scroll/visible issue.

**Comment by IronWalnut** [comment]
Thanks! I think you guys have done a great job at cleaning up the new GUI since it launched.

**Comment by lemoness** [comment]
@maurnoc Thanks for your help! We look forward to seeing your PR.

**Comment by joedragons** [comment]
I also noticed this today on the quest details before a purchase as well.  I'm curious if the fix will be general or specific to this.  I can provide a screen if desired.
Both occur for me in FF if it helps (also Windows 10).

**Comment by maurnoc** [comment]
@joedragons  Could you please post a screen shot? I will try to fix the issue later today.

**Comment by joedragons** [comment]
@maurnoc Here's a screenshot of the bundle, but it also occurs with the individual quests.  Let me know if you need more details.  Thanks for the reply and help=)

![habiticarevampfeedback16](https://user-images.githubusercontent.com/9559205/31449879-0e739436-ae76-11e7-8dce-e664b5e73b21.png)

**Comment by maurnoc** [comment]
Thank you. I pushed the changes to my teams branch. I am currently waiting for them to test it to make sure I did not miss anything.

**Comment by joedragons** [comment]
@maurnoc thanks for the fix and the other PR=)
