### ISSUE TITLE
Tag filters out all of my actions, then disappears!

### ISSUE THREAD

**Issue by Sean31** [HabitRPG/habitica#918]
Hey all,
I created a "Spanish" tag to cover a chunk of my school work, but it filtered out all of my tasks (including the tagged Spanish one) and then (more importantly), disappeared, so I can't un-apply or delete the tag. Now all of my todos and dailies and habits are gone. D= Ayudame?
Edit: Incidentally, this prevents me from adding any new tasks as well (even if they are tagged with "Spanish"), or more likely they are just immediately filtered out.

**Comment by lefnire** [comment]
woops, didn't mean to close. got to beta.habitrpg.com and click the "clear filters" button to the right of filters, see if this sorts you out (it will deploy to production in a couple hours, and yes they use the same database).

This is a short term solution, deleting tags _should_ be then deleting user.filters.{tagId} and removing from the individual tasks, but it seems it's not happening

**Comment by Sean31** [comment]
It works! Thanks so much, and good luck on your other work!

**Comment by lefnire** [comment]
ok, i think I solved this bit in https://github.com/lefnire/habitrpg/commit/eea9a2129f7269bc254482e365db31440c8c2d15
