### ISSUE TITLE
Using FIx Character Values to adjust stats temporarily makes the website append not add

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9180]
Using FIx Character Values to increase your gold by a certain number temporarily makes the website **append** that number to your gold balance, not **add** it. To replicate the bug:

1. Go to User Icon > Settings > Fix Character Values
2. Adjust your gold to have any non-zero value (e.g. 42).
3. Click "Save & Close".
4. Go to your task list and click a positive Habit.
5. Observe your gold balance: the gold you just earned has been **appended** to your gold balance, not **added** to it. E.g., if you earned 1.5 gold, your balance will change from 42 to 421.5  (it should be 43.5)
6. Click a positive Habit again.
7. Your gold balance drops to zero.
8. Reload the website. Your gold balance goes back to what it should be (e.g., about 45).

Examining my values in the database during that test showed that my actual gold balance was always correct in my account; it's just a display issue in the website.

Something similar happens for Experience and presumably other stats.

**Comment by LulaV14** [comment]
Hi @Alys and @lemoness, may I try to fix this issue?
I've already setup the environment in my local computer, and currently I'm investigating about how the error is happening and which components are involved in the process.

**Comment by Alys** [comment]
@LulaV14 Please do! Thank you! Comment here if you have questions or run into trouble.

**Comment by LulaV14** [comment]
I've already sent the PR :)!
