### ISSUE TITLE
Gifting message is repeated

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9187]
When you send a gift with a message, if you go to send another gift to a different user, the same message is already in the modal and the same gem amount is already selected. You should start with a blank message box and gem amount.

**Comment by shinning91** [comment]
Taking a look at this now

**Comment by Alys** [comment]
@shinning91 Thanks!

**Comment by librarianmage** [comment]
@shinning91 Hello! How are you doing with this?

**Comment by shinning91** [comment]
@MathWhiz Hi, unfortunately I doesn't have time to complete this issue. If you are interested with it you can take over.

**Comment by lemoness** [comment]
@shinning91 Thank you for letting us know! 

I've updated the labels on this ticket.
