### ISSUE TITLE
"Check out of Inn" Banner

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9188]
We need to add the following banner to the Tasks page and the Party page when you're resting in the inn, to enable you to easily check out of the inn without leaving the page that you're on.

<img width="1416" alt="screen shot 2017-10-13 at 6 51 22 pm" src="https://user-images.githubusercontent.com/3494081/31571436-99b9f404-b047-11e7-9efa-837dfd8313af.png">

The designs for this feature are available in Zeplin. The person who volunteers to work on this feature should let us know an email address that we can use to invite them to our Zeplin, where they'll find all the information that they need to build the banner. Feel free to ask questions here!

**Comment by daniel-234** [comment]
Hi @lemoness, I am looking to make my first contribution to open source projects. Do you think I could start working on this task?

**Comment by Alys** [comment]
@daniel-234 Thanks! Please go ahead. Comment here if you have questions or run into problems.

**Comment by daniel-234** [comment]
Hi @Alys, as @lemoness wrote, I would need all the information to build the banner, which seems it's available on Zeplin. Can I get access to it? Thanks!

**Comment by Alys** [comment]
@daniel-234 Send your email address to admin@habitica.com and include this issue's URL in your message so we know what it's about.

**Comment by majestic-owl448** [comment]
If #5232 is implemented the wording will need to be changed as then the tasks will change in value

**Comment by Alys** [comment]
@leahleen - excellent point, good catch! I've updated https://github.com/HabitRPG/habitica/issues/5232

**Comment by librarianmage** [comment]
@daniel-234 Hello! How are you doing with this issue?

**Comment by daniel-234** [comment]
Hi @MathWhiz, sorry for not getting back to you earlier on this issue. Unfortunately I have been busy with other work and haven't been able to progress with it. Please, feel free to reassign it.

**Comment by Alys** [comment]
@daniel-234 Thanks for letting us know! I've updated the labels.

As a note for the next person who wants to work on this, the exact wording shown in the screenshot won't be used because the fix for https://github.com/HabitRPG/habitica/issues/5232 will be going live soon. I.e., your tasks WILL change colour while you are Resting in the Inn.

Maybe this?
"You are currently checked into the Inn. Your Dailies won't damage you and you won't make progress towards Quests. | Resume Damage."
@lemoness ?

**Comment by lemoness** [comment]
Looks good to me!

**Comment by joedragons** [comment]
Noticed today with the banner on when I was completing things that the notifications were coming in under the now pushed down header.
I'll make a note to eventually report in the guild and/or see if there's an open github issue but I recalled this ticket so posting here as well/to start.

![habiticarevampfeedback28](https://user-images.githubusercontent.com/9559205/38768509-0a5c5c32-3fc3-11e8-8ed1-814777bc5696.png)

**Comment by paglias** [comment]
@joedragons the issue you're looking for is #10169

**Comment by joedragons** [comment]
@paglias Thank you sir=) UPDATE: Bleh I can't read >.<

**Comment by paglias** [comment]
Actually that hasn't been fixed yet :)
