### ISSUE TITLE
Repeat Field CSS not updating real-time

### ISSUE THREAD

**Issue by StanLindsey** [HabitRPG/habitica#919]
Not sure if this is related to what we worked on the other day Tyler but changing a dailies repeat appears to toggle all of them and then becomes un-toggleable. 

By clicking you are actually changing the repeats but the buttons don't highlight in response to your clicks.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
