### ISSUE TITLE
Front page is missing Facebook (etc.) metadata

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9192]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

We received a report in email that site metadata is empty for Habitica since the redesign, leading to social shares looking like this:

![image](https://user-images.githubusercontent.com/4501321/31577413-89a26632-b0d3-11e7-8b7d-94e0f50ee0bf.png)

We should add back tags for the major platforms so shares of the site include relevant info! The reporting user provided this example code (we can use similar, but the image for one will need to be changed):

```
Sample Code:
<meta property="og:url" content="https://habitica.com" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Habitica: Gamify Your Life" />
<meta property="og:description" content="Habitica is a free habit-building and productivity app that treats your real life like a game. With in-game rewards and a strong social network to inspire you, Habitica can help you achieve your goals." />
<meta property="og:image" content="http://habitica.com/your-image-path/image.png" />

Note: image should be 1200x630 for best results. More info here: https://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit
```

**Comment by ganes1410** [comment]
can i try this?

**Comment by SabreCat** [comment]
@ganes1410 Absolutely! Post here or in the Aspiring Blacksmiths Guild if you need a hand with anything.

**Comment by ganes1410** [comment]
while setting up **node** and **npm** are not installed inside the vagrant machine

**Comment by Alys** [comment]
@ganes1410 Can you look back through the output of the installation process
from the start and show us the first errors that appear? If you don't still
have the output, do `vagrant destroy` then start again from step 6 in the
“vagrant" section in
http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally . Also see
"Prepare for Troubleshooting" in the same page.

**Comment by lemoness** [comment]
@ganes1410 Hi there! Just checking in -- how is this fix going?

**Comment by ganes1410** [comment]
i have one doubt.where do i get the image that needs to linked in the meta tag

**Comment by supertassu** [comment]
There has been no progress on this for a while, can I take it? Thanks.

**Comment by TheHollidayInn** [comment]
@ganes1410 Would you like to continue working on this? Sorry we missed your question.

@Tressley do you have an image we can use for the Facebook meta data.

@supertassu Since we didn't answer ganes, let's see if they want to work on it before we pass it off. We also have other issues we would love your help on while we wait.

**Comment by Tressley** [comment]
@TheHollidayInn -- Try this one!
![fb-meta-habitica](https://user-images.githubusercontent.com/2686586/35454236-32d73dea-029b-11e8-8949-9252d5c4875a.png)

**Comment by TheHollidayInn** [comment]
Thanks!

**Comment by ganes1410** [comment]
@TheHollidayInn  sorry , i am not working on this anymore

**Comment by TheHollidayInn** [comment]
No worries!

**Comment by amandaducrou** [comment]
Is this issue still occurring?

![screen shot 2018-02-01 at 3 45 44 pm](https://user-images.githubusercontent.com/6693909/35663033-025467ee-0767-11e8-88fd-d544407166e4.png)

**Comment by SabreCat** [comment]
Looks like the issue as reported is fixed, but it might be cool to get @Tressley's suggested image in there for fancification!

**Comment by theIsaacLim** [comment]
Should I work on this?
I'm planning to make my first contribution to Habitica and I think this would make a good first issue. I'll add @Tressley 's image.

**Comment by Tressley** [comment]
@theIsaacLim --Go for it!

**Comment by Alys** [comment]
I've modified the labels on this issue ("in progress")

**Comment by theIsaacLim** [comment]
I've just finished my first Github issue!
Whoo!
https://github.com/HabitRPG/habitica/pull/10193
