### ISSUE TITLE
Server errors + tons of requests

### ISSUE THREAD

**Issue by jspivack** [HabitRPG/habitica#92]
A lot of the time when pulling up habitrpg.com I'll get a blank page with just "Internal Server Error", and other times I'll get an amazon AWS error page that says "Application Error, if you are the developer please check your error log"

I also noticed that a TON of XHR requests are being sent on page load/task submit when the page loads correctly (read: hundreds of requests). These issues could be related?

Edit: it could be about 50/50 that the page loads correctly vs reaching an error page. I've noticed I sometimes get 503 errors on XHR requests too.

**Comment by lefnire** [comment]
see #91. Let's close this one and follow up there

**Comment by jspivack** [comment]
Cool thanks. Congrats on getting Reddited
