### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ) 

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#920]
and users can't interact with the page at all. only happens when `process.env.NODE_ENV=='production'`, so both sites are set to `development` right now (obviously **not** optimal). Looks like some mini / concat issue - my hunch was Browserify, but again that's frozen at 1.17.3. I've narrowed it down to `store.query.expose...` that causes it - any exposed paths, any arguments, any function body. This happens even in minimal Derby example apps.

Something in derby/node_modules or racer/node_modules as far as I can tell. I did `git bisect` on habit's codebase, as well as Unroll-Me/derby & SLaks/racer , but didn't find anything there, so I assume nested module somewhere

**Comment by lefnire** [comment]
@SLaks might want to be aware of this for Unroll-Me. Same situation as the `model.uuid()` bug - aka, not a Racer issue as far as I can tell, but may effect you nonetheless

**Comment by SLaks** [comment]
At Unroll.me, we had a similar issue that turned out to be a bug in UglifyJS (the minifier used by Racer).

https://github.com/mishoo/UglifyJS2/issues/153

`store.query.expose` is tricky; it sends the body of the function (from `toString()`) to the client, which evals it to create the client-side query.

**Comment by lefnire** [comment]
sure enough, pinning 2.3.1 (previous Uglify version) fixed the issue. As always, you are my hero @SLaks!

**Comment by SLaks** [comment]
BTW, you can avoid this kind of issue in the future by using `npm shrinkwrap` to fix your dependency versions.

You can then use `npm outdated` to check for new versions and manually upgrade (and test) one dependency at a time.

**Comment by lefnire** [comment]
Great. I think I'll check into doing that from now on, getting our Chef
setup to use that
