### ISSUE TITLE
private messages (PMs) in inbox can't be flagged / reported

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9204]
When a player receives an inappropriate private message, they need to be able to flag it to alert moderators in the same way they can flag a message in a guild.

_edit 2018-04-18: Code for some (perhaps most) of the features below exists from work done in https://github.com/HabitRPG/habitica/pull/9761 . Any contributor working on this should investigate the existing code before creating new code. The "Report" link on the PMs doesn't exist so your first action might be to add / enable that (check to see if it's in the vue code but commented out) - that might then help you test for the rest of the features._

Features required:
- [ ] Each PM should have a "Report" link and the same icon that you can see next to "Report" in guild messages. 
   - [ ] That **includes** PMs sent by the player themself - they must be able to flag their own PMs (e.g., when needing to report both sides of a conversation to moderators).
- [ ] Clicking on the Report link will give the same confirmation screen that you see when you flag a guild message.
- [ ] After any PM is flagged, it should contain a permanent notice something like "You have reported this message to moderators." 
   - [ ] That permanent notice should appear as soon as the flag has been **successfully** saved to the database and the report to the mods has been **successfully** sent. 
   - [ ] It should not appear if those actions have failed.
   - [ ] If those actions fail, the user should see an error message (e.g., a red snackbar notification, that disappears after a few seconds) so that they know they need to try to flag the PM again.
   - [ ] It should not be necessary to reload or sync the website to see the permanent notice.
- [ ] A flagged PM should remain visible (if the player doesn't want to see it, they can delete it).
- [ ] When a PM is flagged, the same actions should occur to report it to mods as when a guild message is flagged: 
   - [ ] an email should be sent to the same recipients as for guild messages
   - [ ] a notification should be sent to the moderator's slack channel. For reporting posts in guilds/parties/Tavern, that notification contains the phrase "flagged a message", but for PMs, the notification should contain the phrase "flagged a PM". The "flagged a message" text for guilds/parties/Tavern should be changed to "flagged a group message" to make it clearer to mods that it's not a PM.
   - [ ] the notifications in the slack channel need to make it clear who posted the message - see below for details
- It is not necessary to allow a player to unflag a PM. If there's demand for that, we can add it later.

----

_The material below has been taken from feedback about https://github.com/HabitRPG/habitica/pull/9761. It's probably still relevant for this issue. Please ask if any of this isn't clear!_

The notifications in the slack channel need to make it clear who posted the message. The screenshot below shows the **same** message flagged twice - once by the person who wrote the message and once by the person who received it. When the person who posted it flagged it ("Black Goblin, Go!"), it looks like the message had been written by the recipient ("ALittleYellowSpider"). Below the screenshot is the matching data from the two player's inbox objects.

![img](https://screenshotscdn.firefoxusercontent.com/images/fc7be42a-5170-41e1-8a60-694322184964.png)

**From the inbox of the recipient:**
```
"cc710462-4a08-4a45-9ed5-985dba9e08b4": {
	"id": "cc710462-4a08-4a45-9ed5-985dba9e08b4",
	"text": "Alys testing PM flagging:  Black Goblin, Go! is writing this message to ALIttleYellowSpider.",
	"timestamp": 1515496466366,
	"likes": {},
	"flags": {
		"3e595299-3d8a-4a10-bfe0-88f555e4aa0c": true
	},
	"flagCount": 1,
	"uuid": "98089587-1bbe-4de2-92d3-0bbe76513a3f", // *********** this is the person who sent the message ***********
	"contributor": {
		"admin": false
	},
	"backer": {},
	"user": "Black Goblin, Go!", // *********** this is the person who sent the message ***********
	"sort": 183
}
```

**From the inbox of the person who sent the message:**
```
"bbf3e017-685d-4820-9e95-d6837681ed15": {
	"sent": true,   // *********** this field does not exist in the recipient's copy of the message so this is how you can tell whether it's being flagged by the recipient or the sender ***********
	"id": "bbf3e017-685d-4820-9e95-d6837681ed15",
	"text": "Alys testing PM flagging:  Black Goblin, Go! is writing this message to ALIttleYellowSpider.",
	"timestamp": 1515496466371,
	"likes": {},
	"flags": {
		"98089587-1bbe-4de2-92d3-0bbe76513a3f": true
	},
	"flagCount": 1,
	"uuid": "3e595299-3d8a-4a10-bfe0-88f555e4aa0c", // *********** this is the recipient ***********
	"contributor": {
		"level": 7,
		"text": "Test",
		"contributions": "This is Alys's second account.",
		"admin": false
	},
	"backer": {},
	"user": "ALittleYellowSpider", // *********** this is the recipient ***********
	"sort": 34
}
```

**Comment by Alys** [comment]
I've marked this as help welcome.

**Comment by Alys** [comment]
labels updated

**Comment by pcvonz** [comment]
I can take a look into this over the weekend.

**Comment by Alys** [comment]
@pcvonz Thank you! Comment here if you have questions.

**Comment by lemoness** [comment]
@pcvonz Hi there! How is this going?

**Comment by pcvonz** [comment]
Sorry for not responding sooner! I just started a new job and haven't had time to look into this.

**Comment by Alys** [comment]
Thanks for letting us know! I've marked this as help wanted.

**Comment by Alys** [comment]
~I'm reopening this for feedback on PR https://github.com/HabitRPG/habitica/pull/9761. Below are the features from the top post of this issue. I've added comments from the testing I did on that PR, and I've also added a few new points.~

_EDIT: I've moved relevant material from this comment to the top post._

**Comment by Alys** [comment]
I've edited the top post to indicate what needs to be done for this issue and I've deleted some old comments that didn't have any relevant content in them. This issue is open for a contributor to work on it.

**Comment by Alys** [comment]
As a note to myself: after the PR for this has gone live, I should make a minor change to the https://mandrillapp.com/templates/code?id=flag-report-to-mods-with-comments template to remove the "... If ..._DISPLAY_NAME is unspecified..." notes. It won't be urgent and won't need to be coordinated with the release.
