### ISSUE TITLE
sprite glitches: images become mixed up after a content deploy containing new images

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9205]
When a content deploy contains new images, the website displays the wrong images until it's reloaded. We know about this and are intending to fix it but I thought I should report it here for completeness and because Riverstone has reported this delightful example of it from her party header. :)

![sprite glitch](https://vignette.wikia.nocookie.net/habitrpg/images/2/20/New_party_member.png/revision/latest?cb=20171017102432)

**Comment by lemoness** [comment]
This has been fixed!

It's a lovely image though <3
