### ISSUE TITLE
Quest Purchase Menu Showing with Scroll Bars

### ISSUE THREAD

**Issue by maurnoc** [HabitRPG/habitica#9206]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * Browser: Chrome 
  * OS: Windows 

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Error was mention in bug #9173. When purchasing quests, unneeded scroll bars appear.  
![image](https://user-images.githubusercontent.com/6641002/31678753-1616a2a2-b33d-11e7-845e-1b4de81f089a.png)
This bug is fixed and I will submit a pull request soon. 

[//]: # (Include any JavaScript console errors here.)

**Comment by joedragons** [comment]
I see this is closed, but I noticed the PR is not merged, so in case interested I noticed this as well today on quest picking.  See attached.  I can file another ticket if desired.

![habiticarevampfeedback20](https://user-images.githubusercontent.com/9559205/32529833-af3805f8-c408-11e7-9d79-4e951a21ee9a.png)
