### ISSUE TITLE
Replace raw HTML internal hyperlinks with router links

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9209]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

From @paglias in our internal bug tracking doc:

> I’ve noticed that sometimes we use `<a href="..."></a>` to link internal pages, we shouldn’t do that as it causes a full reload of the website. We should only use the `router-link` component.

Example of a hardcoded `href` we could get rid of: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/appFooter.vue#L16

Example of a proper `router-link`: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/appFooter.vue#L37

**Comment by hardikjain29** [comment]
I could pick this up, if no one else is?

**Comment by paglias** [comment]
@hardikjain29 thanks! The only thing, do not change links that use `target="_black"` as those are okay as `<a>` tags

**Comment by cezarypiatek** [comment]
@hardikjain29  If you don't mind I have already commited fixed to my fork. I'm preparing PR

**Comment by hardikjain29** [comment]
@cezarypiatek Ohh sure, go ahead! :D
