### ISSUE TITLE
Server errors appear as blank red bar

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9213]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If an error is returned from the server for an action, the client tries to display a notification, but it has no content. So you just get an uninformative red stripe that flies up through your notifs.

To reproduce locally, start the client and server as usual (`npm run client:dev` and `npm start` in separate terminal sessions). Load your tasks page. Then stop the server (^C the `npm start`) and check off a task. You'll see the empty error blob appear briefly.

**Comment by LulaV14** [comment]
Hi @SabreCat, can I give it a try?
I'm just having a little trouble looking for how is the Task calling the notifications? And where should I look for the error handler in the client section?

**Comment by SabreCat** [comment]
The task doesn't so much call the notification as make changes to the user, which are then picked up by the notification watch: https://github.com/HabitRPG/habitica/blob/ee82f5a774363455228f7e467618997ed5ba8ed1/website/client/components/notifications.vue#L230-L233 But there's potential to run into an error during this try/catch https://github.com/HabitRPG/habitica/blob/3377f8a916f607248a7fb7928333e2a46a121306/website/client/components/tasks/task.vue#L462-L467 or when trying to hit the API route at https://github.com/HabitRPG/habitica/blob/3377f8a916f607248a7fb7928333e2a46a121306/website/client/components/tasks/task.vue#L488 .

This is the generic client error handler: https://github.com/HabitRPG/habitica/blob/ee82f5a774363455228f7e467618997ed5ba8ed1/website/client/app.vue#L175-L179 - given we look for `notification.text` for displaying error messages here https://github.com/HabitRPG/habitica/blob/7e1ae6a571cc5806dd7589deb3ed8b89f731f663/website/client/components/snackbars/notification.vue#L6 , maybe `error.response.data.message` is not the right path to get the text from?

**Comment by lemoness** [comment]
@LulaV14 - Hi there! How is this fix going?

**Comment by LulaV14** [comment]
HI @lemoness I'm so sorry for the long delay. I had some issues and didn't have much time but now I do.
May I have a week or so, to have this for the end of next week maybe?

**Comment by lemoness** [comment]
@LulaV14 Thanks for checking in! That will work great.
