### ISSUE TITLE
Popup suppression on pet hatching and mount raising is broken

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9214]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The user settings page includes checkboxes for "don't show popup when hatching a pet" and "don't show popup when raising a pet into a mount". However, these don't seem to have any effect on display of modals when performing these actions. Pet hatching always shows a modal, and mount raising never does. The modals should appear or not per the respective checkboxes.

**Comment by LunarGem** [comment]
I could probably try to poke with this, I've been messing with the modals while doing my other fixes. At the very least I could try to find the area of the code where the problem is.

**Comment by Alys** [comment]
@LunarGem Thanks!

**Comment by lemoness** [comment]
@LunarGem - Hi there! How is this fix going?

**Comment by LunarGem** [comment]
Haven't started it. Someone else can take this.

**Comment by Alys** [comment]
@LunarGem Thanks for letting us know!

I've changed the label back to Help Wanted.
