### ISSUE TITLE
Unallocated points message redirects incorrectly

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9217]
In the notification dropdown menu, if you click the message that says "You have x unallocated points" after you level up, it erroneously takes you to Profile. Instead, it should take you to Stats.

**Comment by rkojima** [comment]
I could take a look at this!

**Comment by Alys** [comment]
@rkojima Thanks heaps! Ask here if you have questions.

**Comment by rkojima** [comment]
@Alys Hi, so I'm trying to test this out in my local install, but whenever I level up, I don't receive a message. I do receive the point and can allocate them. Is there something wrong with my local environment?

**Comment by Alys** [comment]
@rkojima Make sure your test account is above level 10 and has chosen a class (not opted out of the class system). Post again here if that doesn't help.

**Comment by rkojima** [comment]
@Alys Ok thanks! Will check it out

**Comment by rkojima** [comment]
I think this is a side bug, but it seems that whenever I click the unallocated points notification and exit the modal without allocating points, clicking on the notification will not take me to the modal again. If I navigate away from the current page by clicking any of the nav-links at the top, or refresh the page, clicking on the notification will let me go to the modal page.

**Comment by rkojima** [comment]
So it seems like the bug happens when you open the notification, click on one of the other tabs (profile or achievements), exit out without allocating any points to your stats, navigating to a different page without refreshing (tasks, inventory, shops, etc.,), and then clicking the notification again.

**Comment by rkojima** [comment]
It also seems like when you click on the "member-details" class first (i.e. the health, mana, and experience on the left hand side, as well as the avatar picture), exit out of that (while staying on any of the tabs on the modal page), then click on the unallocated points notification, then it won't go to the stats tab in the modal page, but rather the last tab you were on before you exited out of the modal page.

**Comment by majestic-owl448** [comment]
now this is working correclty I thing, it opens the profile with the stats tab open and doesn't redirect the page below

**Comment by lemoness** [comment]
I'm also unable to replicate. Closing now, but we can reopen if there are
other incidents.
