### ISSUE TITLE
Fixes for Task Option Menus

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9220]
The option menus in task edit mode have the following two issues:

1. They should close when you click away from them.

2. One should automatically close when you open a different one:

<img width="357" alt="screen shot 2017-10-17 at 6 20 00 pm" src="https://user-images.githubusercontent.com/3494081/31696699-e0f3d7ea-b367-11e7-956a-e55b948cc2eb.png">

**Comment by shivasheeshyadav** [comment]
@lemoness I would like to work on this issue. Please assign it to me.

**Comment by Alys** [comment]
@shivasheeshyadav Thank you! it's yours. Comment here if you have questions or find problems.

**Comment by TheHollidayInn** [comment]
@paglias Is this being fixed in your upcoming updates?

**Comment by paglias** [comment]
@TheHollidayInn I can do this as well!

**Comment by TheHollidayInn** [comment]
Looks like this was fixed in the previous PR.
