### ISSUE TITLE
Shouldn't view others' check-ins

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9221]
The check-in bar should not display in other people's profiles, since you can only see your own check-ins. Currently, it displays as an empty bar. 

<img width="236" alt="screen shot 2017-10-17 at 6 33 59 pm" src="https://user-images.githubusercontent.com/3494081/31697029-dabcf526-b369-11e7-83f3-c13075ef4847.png">

Of course, you should still be able to view it on your own profile.

**Comment by Alys** [comment]
Is there a reason we hide the number of check-ins now? It's no more of a privacy invasion than the date you joined, and it was terribly useful for Socialites to see it to help with all the questions and "bug" reports about check-in incentives. :)

**Comment by lemoness** [comment]
My understanding was that other users could never see a user's check-in incentives, since the concern was that people didn't want a certain number of check-ins when compared to log-in date to become a valued metric when assessing someone to be in a Party (for example), particularly since the check-ins aren't accurate for longer-term users. who were active before the check-ins started. However, I'm open to discussion on the issue! 

I'm marking this as "suggestion/discussion" while we talk it over.

**Comment by shanaqui** [comment]
My impression was that at least some users were actually in favour of having the check-ins show so they could assess regularity of check-ins when party recruiting. It's a valuable way of seeing whether someone's playing style matches up with the goals of a given party -- if regular checking in is that important to a given party, the leader will notice someone isn't doing it _anyway_ and then kick people out. It would seem to avoid issues by having that stat visible.

**Comment by Alys** [comment]
I don't recall any reports of unfair treatment from the old site because of the visibility of the check-in count, although maybe it's not the sort of problem a player would report.

Longer-term users aren't really penalised any more because the check-ins have been around for 300+ days.

With the Bug guild being so busy at the moment, I'd really like the Socialites to still be able to give accurate assistance for Check-In incentive "bug" reports. We've had two or three of them just in the past day.

**Comment by lemoness** [comment]
Okay! In that case, should I edit this ticket to make it about fixing the
check-in functionality, or close it and make a new one?

**Comment by Alys** [comment]
@lemoness I think closing this and making a new one would be clearest.
