### ISSUE TITLE
Markdown and emoji in Tags on Task Edit doesn't work

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9223]
When editing tasks, the tags that appear in the tag selection option dropdown do not display markdown correctly. 
<img width="138" alt="screen shot 2017-10-17 at 6 48 18 pm" src="https://user-images.githubusercontent.com/3494081/31697368-00da0c92-b36c-11e7-9ca6-ef65afe52557.png">

_Edit by Alys 2018-01-23_:
This is the current incorrect appearance of the tag section of the task edit form. Emoji and markdown should be parsed in the part that displays the tags already chosen and in the edit screen for changing the chosen tags:

![screenshot_2018-01-23_08-16-23](https://user-images.githubusercontent.com/1495809/35247330-b76939ec-0015-11e8-815b-f16837be5f6b.png)

**Comment by omguhh** [comment]
I will check this :)

**Comment by Alys** [comment]
@omguhh Thank you! Ask here if you have any problems.

Note that you might notice or be told about certain specific emoji not being displayed, while other emoji do work. That's a separate problem that's being investigated in https://github.com/HabitRPG/habitica/issues/9128 . For this issue, all you need to do is get markdown and some emjoi working. The :melior: emoji would be the best one for testing - it's Habitica's custom emoji so if it works, it's a sign that the code is using Habitica's own markdown/emoji library correctly. https://github.com/HabitRPG/habitica-markdown-emoji

If you have questions about any of that, or any of it doesn't seem to match what you're seeing in the code base, comment here. I haven't actually looked into how markdown is done in the new site's code yet so I'm only assuming that it will be using the https://github.com/HabitRPG/habitica-markdown-emoji library as the old site was. :)

**Comment by Alys** [comment]
A correction to my previous post:  The library that the new website uses is https://www.npmjs.com/package/habitica-markdown . For example, in website/client/directives/markdown.js you'll see `import habiticaMarkdown from 'habitica-markdown';`

The `habitica-markdown` library makes use of the https://github.com/HabitRPG/habitica-markdown-emoji library that I mentioned before, and so `habitica-markdown-emoji` doesn't need to be specified directly anywhere in the website's code.

**Comment by omguhh** [comment]
Hey @Alys , thanks so much for the links and resources, I really appreciate it :D 
I'll try to get 
> For this issue, all you need to do is get markdown and some emjoi working. 

this done for you!

**Comment by mitten** [comment]
I commented more extensively over in [#9128](https://github.com/HabitRPG/habitica/issues/9128), but thought I'd cross-reference the gist of it here, in case it's related.

The tldr; is that some emoji which do not appear properly when typed by themselves magically appear when typed directly next to another emoji. This makes me think it's not a library problem, but something else. I posted a set of screenshots in the other comment to illustrate.

**Comment by TheHollidayInn** [comment]
I believe the issue here is that the checklists are input fields in the Edit modal. I'm not sure markdown can be rendered as the value of an input field.

**Comment by paglias** [comment]
When editing the items we can just display the text instead of using the markdown directive, or not?

**Comment by Alys** [comment]
In case it's not clear from the issue, the problem is emoji in tags within the task edit form:

![screenshot_2018-01-23_08-12-58](https://user-images.githubusercontent.com/1495809/35247209-45e7b8c0-0015-11e8-8088-234134653ca5.png)

I'll add that screenshot to the top post since the tag form has changed since this issue was logged.

It's true that emoji aren't displayed as images within the checklist when you're editing the task, but that's okay since it's an edit form - you want to see the text representations in that case. I.e., this is fine:
![screenshot_2018-01-23_08-14-46](https://user-images.githubusercontent.com/1495809/35247258-77b9639e-0015-11e8-9269-6bce993d4135.png)

**Comment by Alys** [comment]
Sorry, here's a more complete screenshot showing the issue. Emoji (and markdown) should be parsed in both parts of the tag section in the task edit form.

![screenshot_2018-01-23_08-16-23](https://user-images.githubusercontent.com/1495809/35247330-b76939ec-0015-11e8-815b-f16837be5f6b.png)

**Comment by TheHollidayInn** [comment]
Ohhhh. That's much easier. I'll fix that.
