### ISSUE TITLE
Scheduled To-dos remain at top

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9225]
When you switch you To-do list from the 'Active' view to the 'Scheduled' view and back again, all To-dos with dates remain at the top of the list in due date order instead of returning to their original (manual) sort order. Refreshing the page puts them back in their proper positions, but they should return to their original sort order immediately.

**Comment by SimplyComplexable** [comment]
I'm looking at this one.

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by SimplyComplexable** [comment]
@lemoness There is an active PR for this. Not sure if that means it should have a different label, but just FYI.

**Comment by paglias** [comment]
This seems to be fixed now
