### ISSUE TITLE
Can't Unequip Mustaches

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9227]
Although we recently fixed the issue where you couldn't unequip beards, there is still an issue where you can't unequip mustaches. They should have a "none" option that can be used to unequip them.

**Comment by Alys** [comment]
Sorry lemoness, I added Mustaches to the Glasses and Ears issue (https://github.com/HabitRPG/habitica/issues/9216) a few hours ago, but I forgot to remove it from the bug document. :(  They'll all need similar fixes and the beards option will be a good way of seeing how to do it.
