### ISSUE TITLE
Subscriber Gift Box not visible for non-Subscribers with unclaimed Mystery Items

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9228]
We've received this bug report: "The Mystery Item gift box doesn’t appear in Inventory > Items > Special if you are not a current subscriber, even if you have Mystery Items that you can still claim."

**Comment by SimplyComplexable** [comment]
I'll look at this one.

**Comment by lemoness** [comment]
@SimplyComplexable Thank you very much! Let us know if you have any questions.

I've updated the labels on this issue.

**Comment by SimplyComplexable** [comment]
Is there a way I can add a mystery item to my inventory?

**Comment by Alys** [comment]
@SimplyComplexable In your test account, set this data:
```
            "purchased.plan.mysteryItems": [
                "armor_mystery_201710",
                "head_mystery_201710"
            ],
```    

Here's a full list of all the items you can put in it (as many as you want can go in at once):

"armor_mystery_201402", "armor_mystery_201405 armor_mystery_201406 armor_mystery_201407 armor_mystery_201408 armor_mystery_201409 back_mystery_201402 back_mystery_201404 headAccessory_mystery_201404 headAccessory_mystery_201409 head_mystery_201402 head_mystery_201405 head_mystery_201406 head_mystery_201407 head_mystery_201408 back_mystery_201410 armor_mystery_201410 head_mystery_201411 weapon_mystery_201411 armor_mystery_301404 eyewear_mystery_301404 head_mystery_301404 weapon_mystery_301404 eyewear_mystery_301405 headAccessory_mystery_301405 head_mystery_301405 shield_mystery_301405 head_mystery_201412 armor_mystery_201412 head_mystery_201501 armor_mystery_201501 weapon_mystery_201502 headAccessory_mystery_201502 armor_mystery_201503 eyewear_mystery_201503 armor_mystery_201504 back_mystery_201504 weapon_mystery_201505 head_mystery_201505 armor_mystery_201506 eyewear_mystery_201506 back_mystery_201507 eyewear_mystery_201507 head_mystery_201508 armor_mystery_201508 head_mystery_201509 armor_mystery_201509 headAccessory_mystery_201510 back_mystery_201510 head_mystery_201511 armor_mystery_201511 head_mystery_201512 armor_mystery_201512 head_mystery_201601 shield_mystery_201601 head_mystery_201602 back_mystery_201602 head_mystery_201603 armor_mystery_201603 head_mystery_201604 armor_mystery_201604 head_mystery_201605 armor_mystery_201605 head_mystery_201606 armor_mystery_201606 head_mystery_201607 armor_mystery_201607 head_mystery_201608 back_mystery_201608 head_mystery_201609 armor_mystery_201609 head_mystery_201610 armor_mystery_201610 head_mystery_201611 weapon_mystery_201611 head_mystery_201612 armor_mystery_201612 armor_mystery_201403 headAccessory_mystery_201403 shield_mystery_201701 eyewear_mystery_201701 head_mystery_201702 back_mystery_201702 head_mystery_201703 armor_mystery_201703 back_mystery_201704 armor_mystery_201704 armor_mystery_301703 eyewear_mystery_301703 head_mystery_301703 armor_mystery_301704 head_mystery_301704 shield_mystery_301704 body_mystery_201705 head_mystery_201705 armor_mystery_201707 head_mystery_201707 shield_mystery_201708 weapon_mystery_201708 back_mystery_201706 body_mystery_201706"
