### ISSUE TITLE
Profile Information - website not saving

### ISSUE THREAD

**Issue by gooddevil70** [HabitRPG/habitica#923]
I am able to update these sections but the confirmation button is nonexistent as clicking it makes no difference and the icon is a small dot.

![image](https://f.cloud.github.com/assets/4393964/486885/74b64d76-b93c-11e2-8386-57be3bc87cb4.png)

**Comment by wizonesolutions** [comment]
I get this too. I can't update my website (I can, but it reverts).

**Comment by lefnire** [comment]
enter a website, hit `<enter>` . I'll make things clearer

**Comment by wizonesolutions** [comment]
yeah that worked. I retract my comment.

**Comment by lefnire** [comment]
ah, i'm able to replicate. markig up

**Comment by wizonesolutions** [comment]
Actually, am I only supposed to be able to add one? Only one seems to stick.

**Comment by DanielTheBard** [comment]
^ Are we only supposed to add one? When I add a second website, it shows both of them. But if I check my profile or refresh, it only shows the most recently added website.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by AdrienLemaire** [comment]
Bug can be reopen, I can't save a website.

**Comment by lefnire** [comment]
we should probably delete the websites feature, since you can add adhoc lists in markdown to your blurb

**Comment by AdrienLemaire** [comment]
I see.. I'll do a pull request then, I guess it's just removing a few jade lines of code

**Comment by paglias** [comment]
Se may remove then also from groups so

**Comment by lefnire** [comment]
before merging this we're going to want to warn users and give htem enough time to copy over their websites to their blurbs. I'll work on getting out an announcement

**Comment by AdrienLemaire** [comment]
@paglias Ok, I'll remove website from groups in that pull request.

@lefnire wouldn't it be better to write a script that moves all websites data to the end of the blurbs directly in mongodb ?

**Comment by lefnire** [comment]
@Fandekasp brilliant! Why didn't I think of that. Cool, I'll write that script (unless you get to it first) when I merge this

**Comment by AdrienLemaire** [comment]
I'll give it a try (need to learn about mongodb lol)

**Comment by lefnire** [comment]
Check out some of the ./migrations samples

**Comment by AdrienLemaire** [comment]
It took me quite a lot of time, but I think I wrote a good migration script now.

Tested on develop: 

![migration](https://f.cloud.github.com/assets/260983/1538990/bce6c0b0-4cfa-11e3-813f-8ef2fe7d5a2a.png)

@lefnire you can review and merge
