### ISSUE TITLE
Due until Completed, X times every Y intervals

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica#9231]
Copied from #6941 

If we are trying to implement use cases like

* Cleaning bathrooms once every month
* Replacing your home air filter once every three months
* Getting a free credit check once every four months

I feel like a better representation would be creating "blocks" of time in which the daily is active until the period passes, after which the damage is dealt. It might not look like a significant change, but it would keep each period the same length and would allow use cases like

* Water plants thrice per week
* Exercise 10 times per month

There could also be a completion display, like how To-Dos with checklists are displayed.

---

Images:

Basic Daily (Repeat 1x a week on Sundays)
------------------------------------------------------
![img_201709022120240](https://user-images.githubusercontent.com/12386291/30000092-4cf59354-9025-11e7-82ea-db107d134131.jpg)

Basic Daily w/ Due Until Completed (Repeat 1x a week on Sundays)
-------------------------------------------------------------------------------------
![img_201709022120241](https://user-images.githubusercontent.com/12386291/30000094-4cf7f9be-9025-11e7-88d7-cadfb6277484.jpg)

X Intervals since Completion (7 days since completion) #6941 
---------------------------------------------------------------------
![img_201709022120242](https://user-images.githubusercontent.com/12386291/30000095-4cf8b07a-9025-11e7-830f-607ea2bcc34d.jpg)

X Intervals since Completion w/ Due Until Completed (7 days since completion)
--------------------------------------------------------------------------------------------------
![img_201709022120243](https://user-images.githubusercontent.com/12386291/30000093-4cf7dbb4-9025-11e7-8ded-f2a7e981d696.jpg)

X Times Y Intervals (1 time every week)
-------------------------------------------------
![img_201709022120244](https://user-images.githubusercontent.com/12386291/30000096-4cf94bde-9025-11e7-9f84-4acf84e3d394.jpg)

**Comment by librarianmage** [comment]
@SabreCat Since I'm planning on working on them in tandem, is it okay that I combined them into one?

**Comment by SabreCat** [comment]
Sure, thanks!

**Comment by librarianmage** [comment]
@Sabrecat I was thinking about how this best be implemented on the client,
and I was wondering: should the designs be created first?

**Comment by lemoness** [comment]
@MathWhiz Yes, that's probably for the best if you don't mind waiting. We've got quite a lot of designs to implement at the moment, but this one is on our list!

**Comment by librarianmage** [comment]
Darn. Well, I can wait!

**Comment by tricksyfox** [comment]
@MathWhiz I just want to say that I am SUPER excited that you're working on this and look forward to it being implemented!!

**Comment by librarianmage** [comment]
@tricksyfox Well, I'll try my best!

**Comment by Jboucherie** [comment]
I see @MathWhiz wanted to work on this, but apparently there was a blocker involved that stopped work on it until August of last year, after which there was no more discussion.

I am interested in the last listed feature, and would like to more or less repeat it just so I'm clear on the requirements:
Sunday the task appears to be completed during the week as Green.
Throughout the week, no damage or change occurs in the task.
Saturday(at the rollover to Sunday), damage is dealt.
Sunday the task appears to be completed during the week, and is now Yellow.
Thursday the task is completed, and removed from the list.
Sunday the task appears to be completed during the week, and is now Green.

Is this correct? If so, I would be willing to take on this particular aspect of this ticket as a contributor.

**Comment by Alys** [comment]
@Jboucherie Thank you for being willing to work on it! This has the "on hold - needs design" label which means that designs for the user interface elements are needed before work can commence (@Tressley ).

**Comment by tricksyfox** [comment]
@Alys Are the UI designs something that help is needed on, or is it already in progress elsewhere?

**Comment by Alys** [comment]
@tricksyfox The designs will be done by @Tressley

**Comment by veeeeeee** [comment]
Hi folks! We're holding off on assigning designs to @Tressley until we have the chance to review our approach to group plans. We'd like to approach all the different use cases for tasks in a holistic fashion, and since group plans' assigning/task claiming mechanic touches on this as well, it should wait for the more thorough examination. Thanks for your interest, though--it has definitely been noted!

**Comment by MeanderingCode** [comment]
@veeeeeee I am deeply interested in group tasks management, and it seems there are a few issues at hand around the design of them. I am just starting to scratch at the surface. Is there a place where design discussions are happening? I would like to participate.

**Comment by veeeeeee** [comment]
@MeanderingCode Thanks for the inquiry! We solicit input from group plans users via email and are always open to hearing additional thoughts via that channel. If you get in touch with us over at admin@habitica.com, we can include you in the testing and feedback on some of the changes we've been working on.

**Comment by MeanderingCode** [comment]
Email sent!

**Comment by veeeeeee** [comment]
We're now tracking feature requests via [Google Form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform), so we're closing this issue to reduce duplication of effort.
