### ISSUE TITLE
Enchanted Armoire messages lack flavor

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9233]
The flavor messages for the Encanted Armoire have been lost in favor of a new bland message. Instead, the messages should be:

"You wrestled the Enchanted Armoire and gained [AMOUNT] experience. Take that!"

"You found [FOOD]. Who put that in here?"

"You found [EQUIPMENT]! Amazing!"

**Comment by spacenate** [comment]
Hello Lemoness!

I have reviewed Guidance for Blacksmiths, Setting up Habitica Locally, and joined Aspiring Blacksmiths. Is it okay if I start working on a PR for this issue?

**Comment by SabreCat** [comment]
@spacenate Go for it, with our thanks!

Note that the relevant i18n strings already exist: https://github.com/HabitRPG/habitica/blob/1df8668d382486763c61530329534e373cd897a7/website/common/locales/en/messages.json#L37-L39 We just need to show them again!

**Comment by spacenate** [comment]
@SabreCat Excellent, thanks for the lead on the i18n strings :)

**Comment by citrusella** [comment]
For what it's worth (I took a look at the PR but felt weird commenting right on it), I'm pretty sure the "you gained experience" bubble appeared as its own separate notification on the old site, i.e.

[-100 Gold]
[+53 Experience]  
[You wrestle with the Armoire and gain Experience. Take that!]

As opposed to the style of the food and equipment notifications, which were essentially the way the equipment screenshot looks in the PR (barring style issues/changes), with the text on the right and the image on the left.

**Comment by spacenate** [comment]
Ah okay, thank you! I will try two separate notifications for experience gains.

**Comment by Tressley** [comment]
@citrusella @spacenate -- We definitely want to keep the Armoire's "drop" and flavor in the same notification. I'm trying to reduce how many snacks we show. 😛 

![image](https://user-images.githubusercontent.com/2686586/31890972-f73f0fbe-b7d2-11e7-80db-ca51f1b517f5.png)

So the stack would be:
[-100 Gold]
[You wrestle with the Armoire and gain Experience. Take that! +53 EXP]

**Comment by librarianmage** [comment]
@spacenate How are you doing with this?

**Comment by spacenate** [comment]
Whoooops, being forgetful I am afraid! I need to get my Habitica dev env working again, and then I will take a look for any final todos on this PR.

**Comment by spacenate** [comment]
Okay, I think I have completed all remaining todos in my PR for this issue 👍

**Comment by spacenate** [comment]
@lemoness bump

**Comment by librarianmage** [comment]
You'll want to @ someone other than me. I can't accept PRs
