### ISSUE TITLE
Can't interact with the site at all; everything below avatar is gone!

### ISSUE THREAD

**Issue by ccrawrlol** [HabitRPG/habitica#924]
https://pbs.twimg.com/media/BJxGmHQCcAAfREl.jpg:large

This is what I see when I log on. Tried logging on/off & f5 but nothing!

 I believe it all started when I made tags. My profile was perfectly fine the day I made them but when I logged the next day, everything was gone. 

Clicking on my avatar does nothing but hovering shows the basic popup. Same when hovering over my party members.  For some reason Bailey popups still works.

Here is my ID f74538b8-6476-4887-8377-b116d1ff2a17

**Comment by lefnire** [comment]
both beta and production?

**Comment by lefnire** [comment]
actually, found it - fixing

**Comment by lefnire** [comment]
should be fixed now, can you log in and click delete on one of those rogue tasks?

**Comment by lefnire** [comment]
re-open if still a problem
