### ISSUE TITLE
add tests for the summary field for Guilds and Challenges

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9245]
Tests are needed for the new summary field in Guilds and Challenges:

- [ ] creating a challenge through the API with NO summary provided - summary should equal challenge.name (necessary to ensure backwards compatibility for existing third-party tools)
- [ ] creating a guild through the API with NO summary provided - summary should equal group.name (necessary to ensure backwards compatibility for existing third-party tools)
- [ ] creating a challenge with a summary provided - summary should be correct
- [ ] creating a guild with a summary provided - summary should be correct
- [ ] maybe others?

Tests for the maximum length of the summmary field will be added in https://github.com/HabitRPG/habitica/issues/9244

**Comment by Alys** [comment]
labels updated

**Comment by calasada** [comment]
As for task one, isn't it doing that here: https://github.com/HabitRPG/habitica/blob/506275c30e1a0953d5d447913d4f642d7feb1723/website/server/models/challenge.js#L60-L62
Maybe i'm in the wrong part of the code, it's my first time looking at this project.

**Comment by Alys** [comment]
Yes, that's the code that performs that action but our automated test suite needs a test to ensure that code always performs correctly. :) 

Have a look at http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API if you'd like to read about the tests.

**Comment by haydenbetts** [comment]
I would like to work on this.  Because I'm new, would it be ok if I first submitted a pr with just one of these tests at first so I can get some feedback?

**Comment by Alys** [comment]
@haydenbetts That would be fine! It's a good idea when you're not sure about your approach. Thank you for taking this on! Comment here or on your PR if you have questions or run into trouble.

**Comment by haydenbetts** [comment]
Hi @Alys! I've finished the tests 1,3, and 4 from your original issue post. I have written test 2, but it does not seem to be passing. Can you take a look at it to see if it is written correctly: [test 2](https://github.com/haydenbetts/habitica/blob/f1c262911eb1276cb3b18d2e7fe8878f412ed4ea/test/api/v3/integration/groups/POST-groups.test.js#L118) 

If it is written, correctly, and there is a problem with the guild model, I can take a look at that. I just want to be sure before starting bc that seems like a big project!

**Comment by Alys** [comment]
@haydenbetts It might be because [the code](https://github.com/HabitRPG/habitica/blob/f4d021ab8c1ee093611a506d82bcbe2c53fd059c/website/server/models/group.js#L142-L154) that gives a default value to the summary does so when the guild is fetched from the database and so it might not get triggered by that test. That's a bit of a guess though and could be totally wrong. Would you like to submit a PR with your work so far in it, including the failing test? That way we can see what the Travis CI build makes of it.

**Comment by librarianmage** [comment]
@haydenbetts How are you doing with this? Do you still need some help?

**Comment by haydenbetts** [comment]
Hi @MathWhiz. I haven't looked at this for a while. Feel free to take this up!

**Comment by Alys** [comment]
I've labelled this as help wanted. Anyone who wants to work on it might like to look at @haydenbetts partial pull request at https://github.com/HabitRPG/habitica/pull/9329

@haydenbetts comment here if you change your mind and would like to continue with this! @MathWhiz of course you're welcome to comment if you do want to take it on. :)
