### ISSUE TITLE
prevent typing a private message to a player who has blocked you / opted out of PMs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9247]
On the Messages screen (shown below), when the player that you're trying to send a message to has blocked you or has opted out of all private messages, then there should be no "send" button or new message field at the bottom of the screen. Instead, there should be a statement that you can't message that person (use the `notAuthorizedToSendMessageToThisUser` locale string, which already exists: "You can't send a message to this player because they have chosen to block messages.").

However, mods/staff should always see the send button and the text field, regardless of whether the user has opted out or blocked the mod, because a partial fix for https://github.com/HabitRPG/habitica/issues/8142 allows mods/staff to PM all users regardless of blocking. Moderators and staff can be recognised in the code by `anyone with contributor.admin` being set to `true`.

![image](https://user-images.githubusercontent.com/1495809/31851140-db78939e-b6a2-11e7-8577-c1f1658df579.png)

_edit:_

I've logged https://github.com/HabitRPG/habitica/issues/9989 for a similar issue: "prevent typing a private message to a player who has deleted their account"
It could be either worked on at the same time as this issue, or after this issue is fixed, https://github.com/HabitRPG/habitica/issues/9989 could be fixed by reusing most of the new code.

### Note
Some work towards fixing this issue was already made in https://github.com/HabitRPG/habitica/pull/10878 and can be used as a starting point.

**Comment by Alys** [comment]
labels updated

**Comment by eric-horvat** [comment]
I'll give this a go

**Comment by Alys** [comment]
@eric-horvat Cool, thanks! Comment here if you have questions or find problems.

**Comment by librarianmage** [comment]
@Alys How should this issue affect https://github.com/HabitRPG/habitica/issues/8142?

**Comment by Alys** [comment]
@MathWhiz ha, great point! Thank you! It depends a lot on which issue is finished first.:)  I'll update the top post to include some words about that.  I've added a note to your Hall of Heroes entry to recognise your recent large efforts in assessing issues as a partial contribution to Tier 7.

**Comment by librarianmage** [comment]
Aww, thanks :D

**Comment by MathWhiz** [comment]
@eric-horvat How are you doing with this?

**Comment by librarianmage** [comment]
@Alys as with #8142, should this be put on hold until designs are made, or is that unnecessary?

**Comment by Alys** [comment]
I've edited the top post to update it for the new status of the mods/staff change.

@eric-horvat I'm marking this as help welcome but if you're still interested in working on it, comment here and I'll set it back to in progress for you.

@Tressley Do you want to do a small bit of design for the work described in the first paragraph in the top post here?

**Comment by supertassu** [comment]
Can I give this a go?

**Comment by TheHollidayInn** [comment]
Definitely!

**Comment by Alys** [comment]
@supertassu How are you going with this? Do you have any questions for us or need any advice? Or if real-life has got in the way and you no longer have any free time, just let us know! We understand what that's like. :)

**Comment by Alys** [comment]
I've logged https://github.com/HabitRPG/habitica/issues/9989 for a similar issue: "prevent typing a private message to a player who has deleted their account"
It could be either worked on at the same time as this issue, or after this issue is fixed, https://github.com/HabitRPG/habitica/issues/9989 could be fixed by reusing most of the new code.

**Comment by supertassu** [comment]
Hey,

I have some IRL stuff so can't work on this anymore. Sorry.

**Comment by JosephMarotta** [comment]
Going to try and fix this

**Comment by Alys** [comment]
@JosephMarotta Thanks! Let us know here if you have any questions!

**Comment by Tressley** [comment]
We have updated designs on how to handle this usecase.

![image](https://user-images.githubusercontent.com/2686586/49447979-dd580d80-f7a5-11e8-860b-84d81b60f567.png)

**Comment by akmaekki** [comment]
Can I work on this issue?

**Comment by Alys** [comment]
@akmaekki sure, thanks!

**Comment by akmaekki** [comment]
I have a question regarding this issue. When the user opens opens the modal for chat messages, see screenshot below, (e.g. user clicks on the avatar of another user in the party) a request is done to members/:memberId like `http://localhost:8080/api/v4/members/789cb00c-3018-4cf2-8d3c-3db667aa57ef`.

To fix this issue, I want to know if the other user blocked me. Currently this information, which is located in the array `inbox.blocks`, is not being sent in the request above. Therefore I would consider adding this field to the variable `publicFields` of [index.js](https://github.com/HabitRPG/habitica/blob/develop/website/server/models/user/index.js). Would this be the "best" approach?

![image](https://user-images.githubusercontent.com/17971153/68502690-56d36800-0261-11ea-97e8-2d81e39d52c2.png)

**Comment by librarianmage** [comment]
I think that being able to know everyone that a person is blocking would have some concerning uses.

**Comment by Alys** [comment]
From a moderation point of view, we wouldn't want a player's full block list appearing in the data that anyone can see for that member, so adding the entire `inbox.blocks` to `publicFields` isn't the best approach - thanks for asking about it though!

It would certainly be acceptable from a moderation point of view if partial contents of `inbox.blocks` was in `publicFields`, if that helps (and if the staff don't veto it for technical reasons). For example, if my account contains this:
```
    "inbox": {
        "newMessages": 0,
        "blocks": [
            "11111111-3d8a-4a10-bfe0-111111111111",
            "22222222-ca6d-4c03-8261-222222222222"
        ],
    },
```
and player 11111111-3d8a-4a10-bfe0-111111111111 went to send me a PM, then it would be okay if the members call for my account included `"inbox.blocks": ["11111111-3d8a-4a10-bfe0-111111111111"]`

However that might not be the easiest approach.

One important thing is that when you've viewing a player's profile screen, you don't need to know right then whether you can PM a player or not. For example, the fix for this issue shouldn't remove the messages icon from that screen since the player viewing the screen would still need to use the icon to see any prior conversations. The only time you need to know whether you can send a message to a player is when you're in the inbox with a conversation open for that player.

**Comment by akmaekki** [comment]
Thank you for your replies!

I think you are right to not unnecessarily reveal too much information. In this case, I would suggest to add a method called e.g. `didUserBlockme` similar to method `blockUser` in [profile.vue](https://github.com/HabitRPG/habitica/blob/develop/website/client/src/components/userMenu/profile.vue)

But this would necessitate extending the API with another endpoint. I think this would be the most transparent solution, but also involve more effort (which is not a problem for me).

**Comment by akmaekki** [comment]
Note to myself:
Ok, now I figured out, how I can solve this issue elegantly. Use '/members/:toUserId/objections/:interaction' => Links related to issue is:

- https://github.com/HabitRPG/habitica/pull/8755/files?file-filters%5B%5D=.js
- https://github.com/HabitRPG/habitica/pull/8206

**Comment by shanaqui** [comment]
Hi @akmaekki! Are you still interested in working on this one? If so, please let me know!

**Comment by shanaqui** [comment]
I'll set this back to help wanted since there was no reply. :)

**Comment by veeeeeee** [comment]
This appears to have been fixed. We can reopen if that's not the case.

**Comment by Alys** [comment]
I'm reopening this because it's still (or once again?) possible to type a message to a player who has blocked you or who has opted out of PMs.

**Comment by Alys** [comment]
I've deleted some old comments that were just requests to work on this issue and related conversation (nothing important for solving this issue).

**Comment by Tressley** [comment]
@Alys -- I'm unable to replicate this issue. Is it still happening?

**Comment by Alys** [comment]
No, it's been fixed. Closing. Thanks @Tressley
