### ISSUE TITLE
challenge creator should not automatically join their own challenge

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9248]
Currently, when you create a challenge, you are automatically made a participant.

This should be changed. A challenge creator should not automatically join their own challenge. They should become a participant only when/if they choose to click the "Join" button.

----

_Here are the reasons (just FYI; this is not important for implementing this change):_
- _If you don't yet have the achievement for joining a challenge and you create a challenge in the new website, the achievement pops up in the middle of the challenge creation flow (after filling out the challenge details but before you add tasks), which is disruptive and confusing. You could argue that a person shouldn't be creating challenges until they joined one, but some users might._
- _Users who've created a challenge sometimes ask if it's okay for them to leave the challenge. They worry that it will end or damage the challenge. If they weren't automatically a participant, it would be clear they could leave._
- _There's probably quite a few cases where challenge leaders don't want to be a participant so forcing them to join and then leave is just extra work for them (e.g., they have to remove their copy of the challenge's tag). For the cases where the leader does want to be a participant, they can easily do that by just clicking "join"._
- _Leaders will no longer have excess tasks in their own list if go through a few iterations of adding / deleting challenge tasks before the challenge is ready for use._

**Comment by Alys** [comment]
labels updated

**Comment by hydeenoble** [comment]
Hey, I am not 100% familiar with the stack used, but i would like to look into this. can I?

**Comment by Alys** [comment]
@hydeenoble Please do, thanks! It's not a bad first issue because it involves removing code rather than adding it. :)

If you haven't yet seen [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) and the pages it links to, they'll help you get familiar with our tech and how to make a local install. Comment here if you have questions or run into trouble.

**Comment by Alys** [comment]
@hydeenoble How are you going with this? Do you have any questions for us or need any advice? Or if real-life has got in the way and you no longer have any free time, just let us know! We understand what that's like. :)

**Comment by hydeenoble** [comment]
@Alys Apologies, I have been dealing with alot lately, I no longer have any free time. Thanks for understanding.

**Comment by Feywood** [comment]
Oh, can I do it?

**Comment by shanaqui** [comment]
Am I a pushy wife? Yes I am a pushy wife. Cannot code myself, so I set Lisa on everything I want fixed. 😈

**Comment by Alys** [comment]
@hydeenoble No worries at all, thanks for telling us!

@Feywood All yours, thanks! :)

**Comment by lemoness** [comment]
@Feywood Hi there! How is progress going on this fix? Let us know if you have any questions.

**Comment by Feywood** [comment]
Ok I'll be honest, I forgot about this one. I mixed it up in my head with a different issue that'd been claimed by someone else before I got to and well.
Anyhow, I have now had a look and while I have managed to find where the async joinChallenge pushes the challenge onto joiners (in challengeDetail.vue), I don't yet see where this is happening for the creator/leader. Still looking, though.

**Comment by kawunngg** [comment]
is this still wip? i noticed as a creator i'm "in the challenge", but without having the tasks in my list. i guess this is so i have the challenge in the "my challenges"-list. if i want to participate in the challenge myself i have to first leave and then rejoin to get the tasks into my list which is a bit annoying too...

**Comment by shanaqui** [comment]
It's still in progress, @Feywood hasn't pushed anything yet; the no tasks thing isn't her solution. You might want to actually report it in Report a Bug. The end idea is that the creator will create the challenge and there will be no participants as a default; the creator can then join like anyone else.

**Comment by beffymaroo** [comment]
@Feywood Please let us know if you are still working on this issue. Thank you!

**Comment by Feywood** [comment]
Still trying on this one!

**Comment by beffymaroo** [comment]
@Feywood Thanks for the update!

**Comment by beffymaroo** [comment]
@Feywood How is this fix going? Since it's been about a month, please update us when you have a moment. Thank you!

**Comment by Feywood** [comment]
Hi beffy, it's clearly not going. I'm going to have to drop this one. Sorry!

**Comment by paglias** [comment]
Working on this one

**Comment by paglias** [comment]
@Alys should this change be applied when cloning a challenge as well?

**Comment by Alys** [comment]
Yes, also when cloning. Good catch!
