### ISSUE TITLE
error messages disappear too quickly ("username or password is incorrect", swearword / slur warning)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9249]
When you're logging in but enter the wrong details, you see the message below but it's in a red notification that disappears in just one or two seconds - far too quickly for you to be able to read it.

This needs to be displayed in a more useful way. Even a JavaScript alert would be better (e.g., as a quick fix until a more elegant solution could be done). It would be okay if the red notification was also displayed at the same time.

_"Uh-oh - your username or password is incorrect. Make sure your username or email is typed correctly. You may have signed up with Facebook, not email. Double-check by trying Facebook login. If you forgot your password, click 'Forgot Password'."_

This bit of code is relevant:
website/server/controllers/api-v3/auth.js line 259:    if (!isValidPassword) throw new NotAuthorized(res.t('invalidLoginCredentialsLong'));

----

_edit: As mentioned below, this is another message that disappears too quickly:_

- the message you see when you've tried to post a swearword to the Tavern (https://github.com/HabitRPG/habitica/pull/9253#issuecomment-338515399 )

**Comment by Alys** [comment]
Labels updated.

I've marked it as "good first issue" since my suggested quick fix would be simple, but that label should be removed if the quick fix isn't considered suitable.

**Comment by TheGameFreak720** [comment]
I would like to help. What do I need to know in order to help?

**Comment by AugustoEMoreira** [comment]
I'm actually working on this bug, i just need to test befores make an push.
Can you confirm if docker image is working?

**Comment by Alys** [comment]
@AugustoEMoreira I'll mark this as in progress for you. It's best to comment on an issue when you start on it. You might also want to describe your approach here so that we can advise you about whether it's suitable (for example, making all notifications stay visible for longer would not be the best fix because the gold/experience/etc ones need to disappear quickly). If you're having trouble with your docker install, post about it to the Aspiring Blacksmiths guild and people will help you there.

@TheGameFreak720 Sorry about that but thank you for offering!

**Comment by AugustoEMoreira** [comment]
> It's best to comment on an issue when you start on it.

I'm sorry for that.

> You might also want to describe your approach here so that we can advise you about whether it's suitable (for example, making all notifications stay visible for longer would not be the best fix because the gold/experience/etc ones need to disappear quickly).

Well, apparently the problem is in the one transition that you guys are using to all modal, so if we split it maybe will work

**Comment by Alys** [comment]
Other messages that disappear too quickly and that could be considered along with the password message:
- the message you see when you've tried to post a swearword to the Tavern (https://github.com/HabitRPG/habitica/pull/9253#issuecomment-338515399 )

**Comment by Alys** [comment]
@AugustoEMoreira How are you going with this? Do you have any questions or need any advice?

**Comment by TheHollidayInn** [comment]
All message timers are handled in one place, so I'm not sure the separate issues are needed.

**Comment by librarianmage** [comment]
Hello @AugustoEMoreira! How are you doing with this?

**Comment by Alys** [comment]
@AugustoEMoreira  I've marked this as Help Wanted again, but if you'd still like to work on it, let us know.

I'm also about to adjust the title to make it more generic:
"error messages disappear too quickly ("username or password is incorrect", swearword / slur warning)"


Depending on how the fix for this issue goes, we might want to consider using  a different speed (perhaps intermediate between slow and fast) for other kinds of notifications. Here's some feedback from Vikte (d1018c63-3481-4c8d-8340-04db9ab32bd0) in the Report a Bug guild:
"Not sure if it counts as a bug, but I can't think of other place to tell about it - when I buy something from the enchanted armoire, the notification about what I got is displayed way too shortly and I often end up not knowing what I got."

**Comment by khipkin** [comment]
I can work on the simple alert() fix as a temporary solution for the failed auth and the swearword/slur cases.

**Comment by Alys** [comment]
@khipkin Thanks, that would be great!

However we should have cleaned up this issue - it was logged in more detail in https://github.com/HabitRPG/habitica/issues/10031 (for a wider range of error messages) however that then became a bit more complex because the login and registration pages need different handling than the error messages for other purposes.

So, for THIS issue, the temporary JavaScript alert solution should be used for these messages:
- posted a swear word
- posted a slur
- "messageGroupChatSpam": "Whoops, looks like you're posting too many messages! Please wait a minute and try again. The Tavern chat only holds 200 messages at a time, so Habitica encourages posting longer, more thoughtful messages and consolidating replies. Can't wait to hear what you have to say. :)"

If you'd like to do JavaScript alerts for those, that would be great! It's a rapid way to make important error messages more visible (later we can provide a more attractive solution using a modal if we decide to do that). Thank you!

**Comment by shanaqui** [comment]
_edit by Alys: the problem described in this comment has been logged at https://github.com/HabitRPG/habitica/issues/10256_

When someone has their chat permissions revoked, they shouldn't be able to PM another user. This is handled correctly and the PM doesn't go through, but it _appears_ to have done so until refresh on the user's end, as in this screenshot:

![image](https://user-images.githubusercontent.com/8144640/37987419-0d6ec764-31f6-11e8-908e-4c1a515d9731.png)

That can be quite confusing and probably better behaviour would be for it to generate an error message and *not* appear to send.

The error message that does appear is non-specific, and particularly given that the PM appears to have been sent, we might benefit from a specific notification that you can't PM when you have had your chat permissions suspended. Otherwise, users might think that they can still PM and then be confused when they find that after a refresh, the apparently sent message has disappeared.

**Comment by beffymaroo** [comment]
@khipkin Are you still working on this issue? Please let us know when you have a chance. Thank you!

**Comment by Alys** [comment]
@shanaqui I've copied the information from your comment to a new issue because it can be worked on separately than this one: https://github.com/HabitRPG/habitica/issues/10256 "prevent typing a private message when your chat privileges have been revoked"

**Comment by khipkin** [comment]
@beffymaroo Sorry, no. Couldn't get my local install working.

**Comment by beffymaroo** [comment]
@khipkin Thanks for the update! I'm changing this back to "help wanted" for now, but you're welcome to pick it back up if you find time before someone else claims it.
