### ISSUE TITLE
Party page "Start a Quest" chooses one scroll to be the default, even when you don't own it

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9250]
If you go to the Party page and click "Start a Quest", the quest modal that appears always has the Feral Dust Bunnies quest as the default, even when you don't own that scroll. Screenshot below shows this.
 [EDIT: It can be any scroll including ones you don't own.] 

I suggest that the default content in the centre part of that screen should always be a message saying something like "Select a quest scroll from the left or go to Shops > Quests to buy one". 

My personal feeling is that having any quest selected by default is confusing, even one that you do own. When I first used that new screen, I thought it wasn't giving me a choice of which scrolls to use - I didn't notice the section on the left at first.

Also, if you own many scrolls, having any quest selected by default is unlikely to be helpful - not much chance it will be the one you want.
If you're new to Habitica and do own only one scroll, even having that selected by default might not be the best approach because it doesn't give you any indication that other scrolls can be obtained.

![image](https://user-images.githubusercontent.com/1495809/31856299-e8511196-b700-11e7-8f9c-b25b58f83555.png)

**Comment by citrusella** [comment]
When I open the start a quest button, mine defaults to Egg Hunt (I own neither the dust bunnies nor the egg hunt at this point in time, though I've completed both). Is that a different "flavor" of this, or something different?

**Comment by Alys** [comment]
Ah, interesting! Almost certainly the same problem. 

When you have never owned a quest scroll, your account's list of owned scrolls has no mention at all of that type of scroll. When you own 1 scroll, your account's list contains that scroll type with a value of 1 (unsurprisingly). When you use that scroll, your list contains that scroll type with a value of 0 (i.e., the scroll type is still included in the list).  I'm _guessing_ that this bug might happen if the code to display the default quest looks at your list and picks the first or last item in it, regardless of whether that item has a value greater than zero.

If that guess is true, it's an easy fix if we want one of your owned quests to be selected by default, however I'm still in favour of not having one selected by default at all. I think it's clearer if there's a message there explaining briefly how to select and buy scrolls.

**Comment by lemoness** [comment]
I agree that we'll need an empty state with a clear message. @tressley this is something to add to your list of designs!

**Comment by Alys** [comment]
Another report, this time for a different quest so I've edited the issue title.
"If I’m on my party page and click “invite party to quest”, it brings up the modal and suggests “Find the Cub”. When I say okay, I get a taunting message that I don’t own that quest!" -- Fox_town

**Comment by librarianmage** [comment]
Mine defaulted to the Ram Quest, which I had.

**Comment by Tressley** [comment]
Here's the empty state for when a Quest isn't selected: https://zpl.io/VO09k4Q

**Comment by saraolson** [comment]
this is no longer an issue since the UI to start a quest has been updated
