### ISSUE TITLE
too many base potions

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#926]
I imagine this is very very very low on the priority list, but I have way more than 10 base potions available.  Will there be more need for them in the future (roosters)?  Could I trade them for a better potion?  Thanks.

**Comment by lefnire** [comment]
Yeah, I'm mulling on what to do with excess. Possibilities are trading for
gold or tokens, low sell-value sort of thing. Want to make a UI quick-fix
soon so it's x10 on one potion instead of showing 10 (and laid out in table
form)

**Comment by cleave29** [comment]
I think those sound like good ideas.
Cool, thanks!

**Comment by lefnire** [comment]
also likely to do with https://github.com/lefnire/habitrpg/issues/901

**Comment by lemoness** [comment]
Speaking of potion layout - why do multiple eggs display horizontally, and multiple potions display vertically? They should be the same, no?

Personally, I like the horizontal better, since it stretches the page less.

**Comment by lefnire** [comment]
Inventory layout is quite accidental & buggy, we really need to give it a
proper fix'n

**Comment by lefnire** [comment]
let's follow up on #901, duplicate
