### ISSUE TITLE
Issue when sorting by Hatchable

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9264]
We've received the following bug report from Scribbler (78a53f0e-415e-439e-be14-8db6078ca5ef): “This is a minor bug, but when viewing my stable sorted by “hatchable”, the aquatic sorts incorrectly to the beginning of the bear cub row, that way offsetting the whole row compared to the other rows. Based on the other rows, it should sort between Floral and Ember. It is a pet that I’ve turned into a mount, but haven’t created a new pet for yet, so it’s the sort of grayed out or dimmed version, so maybe that distinction is messing with the sorting. Since we already have a visual indication, I should think it should sort the same way as the pets we have.” User screenshot below:
<img width="571" alt="screen shot 2017-10-24 at 6 02 29 pm" src="https://user-images.githubusercontent.com/3494081/31975367-9423861c-b8e5-11e7-8d43-fc1c23250352.png">

**Comment by TheHollidayInn** [comment]
This no longer seems to be happening.
