### ISSUE TITLE
Both eggs and potions should hatch pets from Items

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9265]
When hatching pets from the Items page instead of using the new rapid hatch mode in the Stable, there is a bug. When you click on a hatching potion, it correctly highlights all the eggs that you can use it on and lets you click on an egg to hatch a pet. However, if you click on an egg, nothing happens. The same behavior should occur if you click on an egg: it should highlight all the possible potion combinations and let you click on one to hatch it.

**Comment by petmat** [comment]
Hi! I would like to take a look at this if it's ok.

**Comment by lemoness** [comment]
@petmat Thank you so much! Feel free to get started, and let us know if you have any questions.

I'm updating the labels on this issue.

**Comment by Alys** [comment]
@petmat How are you going with this? Do you have any questions for us or need any advice? Or if real-life has got in the way and you no longer have any free time, just let us know! We understand what that's like. :)

**Comment by petmat** [comment]
Sorry about the delay, yeah things have been crazy busy lately, but I was thinking about taking another look at this on the weekend if that's ok.

**Comment by Alys** [comment]
@petmat Sure! Thanks! :)
