### ISSUE TITLE
Duplicate Potions after Purchase from Market

### ISSUE THREAD

**Issue by Moltrain** [HabitRPG/habitica#927]
I bought 1 Golden Potion from the Market 2 days ago (5/08), then checked my inventory yesterday and I had 14 of them.

Might be related to <a href="https://github.com/lefnire/habitrpg/issues/901">#901</a> and/or <a href="https://github.com/lefnire/habitrpg/issues/926">#926</a>. Wasn't sure if the potion coming from the market would make a difference.

**Comment by lefnire** [comment]
definitely #901, lets' follow up there. I have a hunch of something
