### ISSUE TITLE
Move from PhantomJS to Chrome Headless for client tests

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9276]
PhantomJS is giving us a lot of problem due to the fact that it's using an outdated JS engine.

We should move to Chrome Headless for this.

In a PR that's currently in progress but that's going to be merged soon we had to disable unit tests because of this, so when this issue is fixed client tests should be enabled again by changing this line in package.json (under "scripts")

```
"test": "npm run lint && gulp test && gulp apidoc",
```

to 

```
"test": "npm run lint && gulp test && npm run client:unit && gulp apidoc",
```

Important links:
- https://github.com/HabitRPG/habitica/blob/develop/test/client/unit/karma.conf.js#L19
- https://github.com/karma-runner/karma-chrome-launcher
- https://github.com/HabitRPG/habitica/pull/9236/commits/50c156d9d047198a7fb9bffc90c6069bfb456f12

**Comment by Asuza** [comment]
I'd like to try this.

**Comment by Alys** [comment]
@Asuza Thank you! Please comment here if you have questions or find problems.

**Comment by Asuza** [comment]
Thanks, @Alys. I'm having a lot of trouble getting this working. I'm trying to use Docker (as mentioned here: http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Docker). I've removed the phantomjs karma modules and added the one I need for Chrome. I've installed puppeteer, and had it trying to launch Chrome inside the "web" container. However, after struggling with trying to get missing dependencies installed for Chrome to function, I went looking for another container to use.

I ended up changing the _Dockerfile_'s first line to be `FROM alekzonder/puppeteer:0.12.0`... but that didn't seem to work (my knowledge of Docker is limited). Despite removing phantomjs from _package.json_ and removing the _package-lock.json_, doing a `docker-compose up --build` is **still trying to install phantomjs**.

Any suggestions on what to try now?

**Comment by Alys** [comment]
@Asuza I'm afraid I'm not very familiar with Docker but some of the other admins are. Are you still having trouble with it?

**Comment by Asuza** [comment]
Yes, I still don't know what's going on. I will need to learn a lot more about Docker to get any further, so hopefully the other admins know exactly what the problem is.

**Comment by gilmoreg** [comment]
Has there been any progress on this? I'd really love to start writing tests for the client. Have you tried doing this without Docker? Would you like me to give it a shot?

**Comment by TheHollidayInn** [comment]
I have't tried running the tests in docker, but if you want to try to update phantomJs or replace the engine, that would be great.

**Comment by Asuza** [comment]
@gilmoreg, I think it should work [from my branch](https://github.com/HabitRPG/habitica/pull/9316) if only you can stop PhantomJS from installing.

**Comment by TheHollidayInn** [comment]
Oh, sorry! I didn't see you had a PR open

**Comment by gilmoreg** [comment]
@TheHollidayInn should I just adopt @Asuza 's changes to the package.json and Karma config in the PR I already have open (for an unrelated issue) or start a new one? 

I tried to run Habitica in Docker but I don't think my machine has enough RAM since I ran into the missing dependencies problem.

**Comment by TheHollidayInn** [comment]
A new one would be best, but if @Asuza is still working on this it would be better to assist in that PR:    https://github.com/HabitRPG/habitica/pull/9316

**Comment by gilmoreg** [comment]
@Asuza, I noticed that ```phantomjs-prebuilt``` is a dependency of ```screenshot-stream``` which is a dependency of ```pageres```. That module is used by the API for exporting the user avatar. So PhantomJS is going to be installed even if it isn't used for client testing. Does that help?

Also, there's an off chance you're dealing with cached layers in your Docker build. You might try cleaning up your images and building from scratch after changing something at a lower layer (like package.json, for instance).

**Comment by Alys** [comment]
related: https://github.com/HabitRPG/habitica/issues/8039

**Comment by Asuza** [comment]
@gilmoreg I don't understand Docker well enough to say for sure that I'm doing the correct things with it. Currently, I don't know when I'll have time to try to rebuild my containers for this fix, but it's been at the back of my mind. I'll let you know what happens if I have time to mess with it again soon.

**Comment by lemoness** [comment]
@Asuza Does that mean that you would like to give up your claim to this issue, at least for now?

**Comment by Asuza** [comment]
@lemomess, that's fine. I already spent a long time on it with no real progress.

**Comment by TheHollidayInn** [comment]
@Asuza have you tried setting up your environment without docker? Docker isn't required to fix this.

**Comment by kartikadur** [comment]
If the only thing required for this fix is changing from phantomJS to chromeHeadless and no one else has claimed it, I'd like to try. I kinda get antsy when unit tests are ignored.

**Comment by paglias** [comment]
@kartikadur go ahead!

**Comment by kartikadur** [comment]
For self future reference :)
+ [change phantomjs to chrome](https://blog.johnnyreilly.com/2017/08/karma-from-phantomjs-to-headless-chrome.html)
+ [travis chrome addon headless](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode)
+ [travis chrome addon](https://docs.travis-ci.com/user/chrome)
+ [headless chrome testing in docker](https://hackernoon.com/running-karma-tests-with-headless-chrome-inside-docker-ae4aceb06ed3)
+ [testing in headless env + some docker info](https://medium.com/@greg.arendse/testing-an-angular-cli-project-in-a-headless-environment-d85591f94613)
