### ISSUE TITLE
Issues with Class Change modal

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9279]
1. _This is the only part that needs a fix:_ 
**When changing classes, the Warrior should default to being selected. Otherwise, you can't actually see any of the class names or information.**

This is what we want the screen to look like as soon as it's opened (i.e, the same thing that you see now when you've clicked on the Warrior image):

![screenshot_2018-02-24_12-11-35](https://user-images.githubusercontent.com/1495809/36624513-e4feb346-195b-11e8-83e0-c0114a6e551b.png)

----

2. _This has been fixed:_ ~When changing class, if your own avatar is wearing anything that the sample avatars don’t wear, then your own gear shows up on the class change screen (e.g., the mage has a shield, the rogue has a collar):~

<img width="509" alt="screen shot 2017-10-26 at 4 58 53 pm" src="https://user-images.githubusercontent.com/3494081/32082227-078f6136-ba6f-11e7-8c25-e2ff61cfdcfc.png">

3. _This is now logged in its own issue_: ~The modal sometimes appears erroneously~
```
I was checking off my dailies and leveled up. It kicked me into the "Choose Your Class" screen. I figured it was just a glitch so I picked warrior (which I was anyways) and it charged me three gems like I voluntarily opted to change class and reset all my stats :-/
```

**Comment by Alys** [comment]
I've copied the point about the modal reappearing to a new issue to give it more visibility: https://github.com/HabitRPG/habitica/issues/9969

**Comment by Alys** [comment]
Point 2 from the initial post has been fixed elsewhere. I've edited the top post to cross that out, and also cross out point three that's now in its own high-priority issue.

**Comment by probaton** [comment]
I fieks! I was just going to check out how hard this was to do and then accidentally fixed it while I was debugging.

**Comment by Alys** [comment]
labels updated :)
