### ISSUE TITLE
Ability to buy eggs or potions after getting all the armor.

### ISSUE THREAD

**Issue by tellezhector** [HabitRPG/habitica#928]
After getting all the armor items I have no use for my gold pieces.

I know I could imagine custom prizes, but it is much more motivational to be able to get a pet.

Using tokens you can select what pet to buy or what potion to buy.
To keep it interesting it could be a random egg or potion for an elevated gold price. That way there is still a low probability of getting a new pet if you already have many (It decreases exponentially).

Something like playing on a roulette where the prize is a potion or a pet. And to play you need to pay an elevated gold price.

**Comment by lefnire** [comment]
also related: http://community.habitrpg.com/content/suggestion-gold-tokens-0

**Comment by wc8** [comment]
Closing for housekeeping, since it's probably best to follow-up on community site.
