### ISSUE TITLE
Make Challenge Owner's Name Clickable

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9283]
You need to be able to click the challenge owner's name to bring up their profile information. This is useful for lots of reasons -- seeing when they last logged in, sending them a direct message, etc.

**Comment by librarianmage** [comment]
Should this be marked as in progress, as #9308 has been proposed to fix this?

**Comment by Alys** [comment]
labels updated. Thanks @MathWhiz

**Comment by lemoness** [comment]
Did 9308 correctly fix this?

**Comment by Alys** [comment]
This hasn't been fixed and is open for a contributor to take up. There's an incomplete PR at https://github.com/HabitRPG/habitica/pull/9308 that might be usable as a basis for a fix but see paglias's comment in the PR.

**Comment by marvinrabe** [comment]
I can have a look at this.

**Comment by paglias** [comment]
@marvinrabe thanks!
