### ISSUE TITLE
Cannot leave a group with an active subscription

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9287]
If you try to leave a Group Plan that is not yours, you get the error “Cannot leave a group with an active subscription.” Normal users should not be able to add anyone to a Group Plan, but they should be able to leave one whenever they wish. There should, however, be a popup that says "Are you sure you want to leave this Group Plan?"

**Comment by TheHollidayInn** [comment]
We have to fix the member count on the groups that have this issue. It should only happen when there are two members in a group, but it is possible for more. I have fixed the cause of the issue though.

**Comment by lemoness** [comment]
Hm, why should it happen for two members? Or do you mean that only two-person Groups are affected?

**Comment by Alys** [comment]
I can't replicate this in staging so I'm closing it as fixed.
