### ISSUE TITLE
Guild content transfers

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9288]
If you start typing a chat message in a Guild and change Guilds through the notification pop up, not deleting the message, the text migrates to the next Guild. (It's possible that this only happens if you do this quickly.) This also sometimes happens with Guild Challenges.

**Comment by TheHollidayInn** [comment]
This should be fixed with the new lifecycle functions I have added: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/groups/group.vue#L436
