### ISSUE TITLE
All clicks seem to be ineffective

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#929]
I have been observing this since around 11:30/11:45 GMT on May 11th, on FF 20.0.1, Win7 (32bits).

Clicks on UI elements seem (almost) ineffective. Whenever a tick is to be displayed instead of a box, it is properly displayed. However, validated todos are not removed, no bonus/malus of any sort is recorded, tasks cannot be edited, profile cannot be accessed through clicking the avatar, task stats cannot be displayed, etc.
Web console does not show anything.

**Comment by lefnire** [comment]
i'm currently playing with some query subscription optimizations, this may be causing the issues. Can you try on beta.habitrpg.com? What's your user id, wanna test some stuff

**Comment by Eusebius** [comment]
My login is Eusebius.

I thought beta would be the unstable version? Should I use beta as my regular platform? Which platform should I report bugs from?

**Comment by lefnire** [comment]
No, not necessarily - just want to see how things work for you there by
comparison. A few fixed hit beta first, so we can kick it around before
pushing to prod. Also, because beta has fewer users, I often use it to test
how server performance effects model subscriptions.

So yeah, no need to make the switch necessary (some people have) - just
curious how it works right now compared

**Comment by lefnire** [comment]
ooo, your account shows a very interesting issue I need to fix. What i think is happening is you just have a lot of stuff. Obviously Habit needs to support that, but I think our dynamic bindings and model listeners are just crapping when a single click through a ton of listeners. For the short term, clear your completed todos (bottom of todo column -> completed -> clear), I'll look into cutting back / consolidating listeners

**Comment by wc8** [comment]
Experiencing almost this on beta a few clicks register. I am stuck in the inn. I cannot add tasks. Will follow up with debug suggestions later.

**Comment by Eusebius** [comment]
Glad to provide you with a marginal use case, then :-) I didn't know about the completed todo flushing. If the maneuver helps, maybe it could be automated (opt-in option in the settings?) or made more obvious.

Anyway, I'm "stuck" in both regular and beta, so I am unable to click the "complete" button either. :-\

**Comment by lefnire** [comment]
give beta a shot now, https://github.com/lefnire/habitrpg/commit/0421c2e61b77e2d2dc8debdaa57935f21f29e2a3

**Comment by Eusebius** [comment]
Now it looks fine on beta, thanks.

**Comment by lefnire** [comment]
kk, deploying to master. if either of you still experience after 10-15m on prod (takes a while to deploy), re-open ticket
