### ISSUE TITLE
Mod/Staff Names in Tavern should be Clickable

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9290]
The Tavern has a list of all the staff and mods in the side bar. You should be able to click each name of a mod/staff member to bring up their user profile. This is important because it ensures that users have a quick way to get in touch with staff and mods.

**Comment by EmilyOng** [comment]
👍

**Comment by lemoness** [comment]
@EmilyOng Thanks! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by librarianmage** [comment]
Hey @EmilyOng! How are you doing with this? Do you need any assistance?

**Comment by lemoness** [comment]
I've marked this as "help wanted"

**Comment by Hus274** [comment]
I can pick this one up.

**Comment by lemoness** [comment]
@Hus274 Thanks so much! Let us know if you have any questions.
