### ISSUE TITLE
@Username selection with keyboard arrow keys in drop-down mentions list in chat

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9291]
When tagging someone's name in chat, you can no longer select the person's name using arrow keys. Instead, you need to use the mouse. You should be able to use arrow keys to select someone's name.

**Comment by brianhall** [comment]
I'll take a stab at this one!

**Comment by lemoness** [comment]
@brianhall Thank you very much! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by librarianmage** [comment]
Hello @brianhall! How are you doing with this issue? Do you need any assistance?

**Comment by brianhall** [comment]
Hey there, @MathWhiz / @lemoness! I apologize, time got away from me here. I don't want to hold this up, so please feel free to reassign and I'll look for other issues when I get a chance. Sorry for the delay!

**Comment by lemoness** [comment]
Thanks for letting us know! I've marked this as "help wanted."

**Comment by jackcogdill** [comment]
Hey, I'd be happy to work on this.

**Comment by Alys** [comment]
@jackcogdill Thank you! Post here if you have questions.
