### ISSUE TITLE
Can't view Party modal after viewing Challenge participants

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9294]
If you attempt to view the Party member modal after having looked at a list of Challenge participants, the Challenge participants show up in the modal instead of Party members. This is only fixed on a refresh.

**Comment by klezt** [comment]
Hello @lemoness. I am new to this project but can I help with this?

**Comment by lemoness** [comment]
@klezt Absolutely! Thank you very much for helping out. Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by klezt** [comment]
@lemoness I have submitted a pull request with the bug fix (1 line of code) (pull request #9365), however it fails the Travis CI with error that I food is not currently available for purchase, which is unrelated to the bug fix. Do I need to make any changes?

**Comment by Alys** [comment]
@klezt Thanks for the PR! Those two errors are happening in all pull requests at the moment and they aren't related to your code as you say, so you don't need to worry about them. I think one of the staff has a change in progress to fix the tests. If you notice any more errors though, comment on the PR and we'll look into them.

**Comment by klezt** [comment]
@Alys This issue has been fixed, by applying the fix to client/components/header/index.vue. Therefore the PR was closed (bug fix in PR was in client/components/appHeader.vue that no longer exists), but this issue should be closed.
