### ISSUE TITLE
Reset does not lock down store items

### ISSUE THREAD

**Issue by ragnarkarlsson** [HabitRPG/habitica#93]
Whilst I used reset to wipe my account back to normal, my fresh character slate still has the option to buy Leather Armour, Sword 2 and Potion. I have only just started playing around with this but personally from a experience perspective would expect these to need unlocking when you roll a new char.

**Comment by hookang** [comment]
This is a bug stability issue.

**Comment by horusofoz** [comment]
Testing has showed that while store is not initially locked down, a refresh locks it back down again. 

Would a forced refresh following reset resolve the issue?

**Comment by horusofoz** [comment]
Closing as no response from user in a month.
