### ISSUE TITLE
Avatar label obscures Zzz

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#930]
On beta, I've noticed my avatar label now includes my level. My user name and level don't fit on one line so that the second line now covers almost all of the Zzz's that indicate I'm resting in the Inn. It also partly covers part of my avatar's head.

**Comment by bobbyroberts99** [comment]
![avatar](https://f.cloud.github.com/assets/4084120/491768/de76b1bc-ba57-11e2-80ea-eff3eb20f6f0.jpg)

Sorry, should have attached pic with original post.

**Comment by lefnire** [comment]
You can rename your character for the time being in Options -> Profile ->
Full Name

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
