### ISSUE TITLE
add "Copy As To-Do" to Tavern, guilds, party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9302]
The "Copy As To-Do" feature needs to be added back to **all** messages in the Tavern, all guilds, and the user's party. 

`website/client/components/chat/chatMessages.vue` is where you'd start looking into this; you'll see that there's already code there for it but it's been commented out because the copyAsTodo button wasn't working. The contributor who works on this would need to work out why and fix the problem. The feature was working on the old website so it's possible that the site's JavaScript code and/or API have support for it.

We do also want this feature to work for private messages in the Inbox, however that might need to be fixed in a different / more complex way. I'm not sure if that ever worked on the old website. If the contributor who works on this issue would like to fix it in the Inbox too, that would be great, but it's also okay if you just get it working in the Tavern, guilds, and party for now. We can open a new issue for the inbox later. If you don't get it working in the inbox, make sure that the copyAsTodo icon doesn't appear there.

**Comment by perkyguy** [comment]
I threw in a PR to handle the non-inbox side of this.

To get this working in the inbox, there are some complications that I found. I believe the main issue is how the modals are being handled. Whenever a modal is being shown, the one previous to it is hidden. However, when opening a child modal from a parent modal, the parent is hidden and it hides its child. This messes with the modal stack, and things get broken (but all of the data is there).

I may be wrong, or this may have been talked about previously (I'm new to developing for Habitica), just wanted to report on my findings.

**Comment by Alys** [comment]
@perkyguy That's great, thanks for giving those details, and for the PR!
