### ISSUE TITLE
Incorrect Heading margins and spacing

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#9303]
H1, H2, and H3's have incorrect spacing on various pages throughout the app.

**Current Implementation**
![image](https://user-images.githubusercontent.com/2686586/32107305-3243a76a-bafc-11e7-9b70-116767d4359d.png)

**Mock-up Fixes**
![image](https://user-images.githubusercontent.com/2686586/32107368-5a173bf8-bafc-11e7-92a5-5cfeb2a8d456.png)

**Comment by dnlup** [comment]
@Tressley created a [PR](https://github.com/HabitRPG/habitica/pull/9311) about it, Don't know if it fits your needs.

**Comment by lemoness** [comment]
I've updated the tags on this ticket.
