### ISSUE TITLE
Modals should open without being scrolled

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9307]
Often when long modals pop up, they're scrolled to the very bottom by default, like this:

<img width="533" alt="screen shot 2017-10-27 at 1 40 52 pm" src="https://user-images.githubusercontent.com/3494081/32124586-24485edc-bb1d-11e7-8dfe-abf0f8915283.png">

They should instead pop up with the top of the modal displaying, like this:

<img width="574" alt="screen shot 2017-10-27 at 1 40 55 pm" src="https://user-images.githubusercontent.com/3494081/32124559-0ffbd6e8-bb1d-11e7-90ea-1c8d925c322d.png">

**Comment by paglias** [comment]
Is this still an issue?

**Comment by SabreCat** [comment]
Doesn't look familiar to me. If anything they're sometimes placed too far down the screen so that downward scrolling is necessary when the modal _could_ fit on screen if it were placed higher!
