### ISSUE TITLE
Reload, frequently

### ISSUE THREAD

**Issue by Arkane-x6** [HabitRPG/habitica#931]
The page HabitRPG reload frequently.    It's uncomfortable.

_Sorry, very bad english ^.^_

**Comment by lefnire** [comment]
is this on mobile, or desktop? known issue for mobile, but if it's happening on desktop that's a new problem. did it just start happening for you, or has it been an on-going issue?

**Comment by Arkane-x6** [comment]
On desktop (i've not tried, on mobile). It did happening in few hours, for me and my friend too & 'dont know if is an on-going issue :/

**Comment by Arkane-x6** [comment]
On desktop (i've not tried, on mobile). It did happening in few hours, for me and my friend too & 'dont know if is an on-going issue :/

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
