### ISSUE TITLE
allocate always assigns to STR

### ISSUE THREAD

**Issue by dirtyreyes** [HabitRPG/habitica#9314]
curl https://habitica.com/api/v3/user/allocate -s -X POST -H "Content-Type:application/json" -H "x-api-key: ..." -H "x-api-user: ..." -d '{"stat":"int"}'

This assigns to STR. I can't seem to assign to anything but STR, and I've tried escaping characters and stuff like that.

**Comment by dirtyreyes** [comment]
Anything I can do to help at this point? It's easy to confirm this behavior.

**Comment by lemoness** [comment]
Is this still happening?

**Comment by dirtyreyes** [comment]
I quit Habitica because of all the bugs and moved to Todoist.
