### ISSUE TITLE
Cards (greetings, thank you, etc) should not have multiple Batch Buying (also gear, Backgrounds, Mystery Item sets, Rebirth, Fortify, Armoire)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9317]
Currently, when you buy a card to give to a party member, you're asked how many you want to buy.

That option shouldn't be available for cards because as soon as you've bought a card, you have to select the party member to give it to. It only makes sense to buy one card at a time.

For reference for new contributors, these are the cards that this issue refers to:
![image](https://user-images.githubusercontent.com/1495809/32140794-eda7205a-bcb8-11e7-8347-62107de71e9e.png)

**Comment by Alys** [comment]
labels updated

**Comment by ArthurFoucher** [comment]
Hi, first-time contributor here ! That sounds like something I could tackle, so I'll look into it if that's ok ?

**Comment by SabreCat** [comment]
@ArthurFoucher Sure! Go for it, with our thanks.

**Comment by ArthurFoucher** [comment]
It seems the same kind of things has already been done for the equipment type (https://github.com/HabitRPG/habitica/blob/develop/website/client/components/shops/buyModal.vue#L45-L47), but there's a `genericPurchase` boolean that may serve that exact purpose. I 'd like to use it to check if I should display the "How many to buy" part of the modal, instead of a more clunky `item.purchaseType !== "gear" && item.purchaseType !== "card"`. Can someone confirm that this is the right approach before I submit a PR ?

**Comment by lemoness** [comment]
@ArthurFoucher - I'm so sorry -- it looks like some wires got crossed, and one of our programmers looped this fix into a bigger change that he was working on. This is totally our fault! I hope that it isn't too discouraging. We definitely want you to keep contributing, though, so please check out any of the other issues in the "help wanted" tag. @Negue will also be happy to show you his PR if you have questions about how this ended up being implemented. Again, we are very sorry about the inconvenience.

**Comment by ArthurFoucher** [comment]
No worries, and yes if you could reference that PR here that would be great !

**Comment by negue** [comment]
@ArthurFoucher sorry it took so long to respond.

Your approach wasn't wrong, its just we have multiple item types which shouldn't / can't be purchased multiple times at once, so I created an array which contains all types:

https://github.com/HabitRPG/habitica/blob/b630485316ab5c19ac5aa9de2d3d813c60005b6f/website/client/components/shops/buyModal.vue#L288-L291

Added a simple method to check if the passed item-type is in it?
https://github.com/HabitRPG/habitica/blob/b630485316ab5c19ac5aa9de2d3d813c60005b6f/website/client/components/shops/buyModal.vue#L421-L426

And then show / hide the selection:
https://github.com/HabitRPG/habitica/blob/b630485316ab5c19ac5aa9de2d3d813c60005b6f/website/client/components/shops/buyModal.vue#L45
