### ISSUE TITLE
Lost a Tag

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#932]
One of my tags completely disappeared!! Fortunately, the items are still on my to-do list, but  it will be a drag to go through and relabel them all :/

**Comment by lefnire** [comment]
had it been in the system a while, safely with the other tags - or do you think it was one of those bad-connection times where the actions you performed (including creating the tag) went into space?

**Comment by lemoness** [comment]
In the system for like a day and a half, I think.... but to be fair, the
offline-reconnect bug has been hammering me hard (again). Could easily be
related.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
