### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by inverse** [HabitRPG/habitica#9324]
Is there a way to create new tasks, dailies, habits via keyboard shortcuts? If not could this be a feature request. 

I couldn't see any other ticket asking this.

**Comment by lemoness** [comment]
Hi Inverse! Feature requests like this generally go on Trello, not on Github, so I'm closing this ticket. You may be interested in this Trello card here: https://trello.com/c/vDYCrh16/13-add-new-parse-text-do-this-tag-hard-monday
