### ISSUE TITLE
"Tags" and "Repeats" and "Reset Streak" dropdowns within Tasks do not close on mouse-away

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9326]
When you open the "Tags" dropdown within task edit mode, the only way to close it is to click on the tags box again. It should behave like the other dropdowns and close when you mouse away. 

_edit by Alys 2017-12-30:_

The same problem exists for the "Repeats" dropdown in Dailies and the "Reset Streak" dropdown in Habits. The same fix is desired for all three dropdowns.

**Comment by LulaV14** [comment]
Hi @lemoness ! Can I help with this?

**Comment by lemoness** [comment]
@LulaV14 Yes, please! Thank you for volunteering. Let us know if you have any questions!

I've updated the labels on this ticket.

**Comment by iabrenne** [comment]
@lemoness and @LulaV14  ,

It looks like the same may issue may apply to the "Repeats" dropdown.  When editing a task, after user clicks on the repeats dropdown, only way to get out of it is to click on the repeats dropdown again. It does not disappear on mouseaway. 

Just wanted to point it out !  If you guys agree, perhaps both issues could be fixed :)

Thank you.

![image](https://user-images.githubusercontent.com/24214306/34344247-5688b6a2-e9a9-11e7-8598-b8032e75140d.png)

**Comment by Alys** [comment]
@iabrenne Great point, thank you! We definitely want the fix applied to that as well. I'll update the title of this issue.

**Comment by TNychka** [comment]
Hey I can take this

**Comment by Alys** [comment]
@TNychka Thanks! Go for it! :)

**Comment by beffymaroo** [comment]
@TNychka Are you still working on this/do you plan to work on it soon? Please let us know when you have a moment. Thank you.

**Comment by TNychka** [comment]
Sorry, I forgot about this. Something came up and I won't be able to work on this one anymore. Sorry

**Comment by beffymaroo** [comment]
Thank you for checking in, @TNychka ! No problem, I'll just change it back to Help Wanted.

**Comment by wwyl1234** [comment]
Hmm for tags, it looks like it can be fixed by change the code in user.vue (perhaps by removing line 506) or some CSS property needs to be added like mouseover and mouseout for the appropriate elements. And for the for the other dropdowns appears to be in the file taskModal.vue and tagpopup.vue.

**Comment by veeeeeee** [comment]
This is a behavior that is no longer desired--we want dropdowns to remain open unless expressly closed.
