### ISSUE TITLE
Warning about no notifications for Guilds with too many members

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9327]
For performance reasons, Guilds that have over 5000 members do not receive notifications. Those Guilds should have the following warning in them:

"This Guild is too big to receive notifications for performance reasons. Be sure to check back often for replies to your messages!"

The style of the design should be as follows, albeit with the updated copy:

<img width="965" alt="screen shot 2017-10-30 at 6 41 32 pm" src="https://user-images.githubusercontent.com/3494081/32203795-c8a2a12c-bda2-11e7-813d-4651e2a8bcfb.png">

If you'd like to work on this ticket, we'll invite you to our Zeplin so that you can get the specifics of implementing this design, so be sure to let us know which email address we should invite.

**Comment by splashofcrimson** [comment]
I'm still a beginner, but I would like to try working on this!

**Comment by lemoness** [comment]
@splashofcrimson Thank you very much! Let us know if you have any questions.

I've updated the labels on this issue.

**Comment by splashofcrimson** [comment]
@lemoness awesome! If you need my email, it's splashofcrimson@gmail.com

**Comment by lemoness** [comment]
Great! @Tressley will get you set up soon.

**Comment by Tressley** [comment]
@splashofcrimson -- You've been invited to our Zeplin project. Please let me know if you don't see the invite.

You can find the design specs here: https://zpl.io/aB19D7O

**Comment by librarianmage** [comment]
Hello @splashofcrimson! How are you doing with this issue?

**Comment by TheHollidayInn** [comment]
I'm pretty sure we aren't doing any notifications. And we should look into moving to queue/worker systems to offload performance.

**Comment by Alys** [comment]
The notifications here are the ones from `newMessages` in the user document, which appear in the drop-down from the notification icon in the website's header.

@splashofcrimson I'm marking this issue as help wanted again, but if you're still interested in working on it, comment here and I'll switch it back to in progress. :)
