### ISSUE TITLE
Dailies not enabled every day break streak counter

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#933]
If I have a daily not enabled on saturday its streak counter get resetted after friday and on sunday it restart from zero

**Comment by wizonesolutions** [comment]
Yeah, same here...non-daily ones don't seem to streak.

**Comment by wildcate** [comment]
That was part of the intended design - the streaks are there to help building daily habits, as an extra incentive not to drop it for one day inbetween because it has been going so well. 

It should probably be mentioned somewhere that this is the case, it's clearly confusing people :)

**Comment by mclois** [comment]
Well, some daily habits cannot be done on weekends (i.e. "remember to take lunch to job").

I could understand a streak to be reset when the scheduled days change, but as it is now, I know I will never get a 21 days streak on work-day habits :(

Not big deal, it's a great game anyway, but long streaks could be a cool extra-incentive.

**Comment by wildcate** [comment]
I hear you - most of my dailies are also weekday tasks...

**Comment by lefnire** [comment]
Bug (not intended) , will check out.

**Comment by wildcate** [comment]
Ah, that's nice - gives a better chance to the non-really-daily users of the dailies! (When we first discussed the streaks, it sounded as if it might only be possible for the everyday ones.) Thanks!

**Comment by lefnire** [comment]
should be fixed in https://github.com/lefnire/habitrpg/commit/92b178b4a41eb96e24449f1bef3e379e85590bae , if anyone has probs re-open
