### ISSUE TITLE
can't fairly judge challenges because of limit of 30 in participant drop-down

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9333]
When a challenge has more than 30 participants (which is common) it's not possible to see the progress of more than 30 of them using the "Select a Participant" dropdown. It should be possible to access a list of all challenge participants (even if it's paged in some way), and to click on every name on the list to view their challenge tasks.

(While you can use the CSV file for judging the challenge, that's not suitable for everyone because it's confusing and doesn't give the same understanding as the in-website visual view of the tasks.)

**Comment by Alys** [comment]
I've changed this issue's title and updated the top post to say this:

When a challenge has more than 30 participants (which is common) it's not possible to see the progress of more than 30 of them using the "Select a Participant" dropdown. It should be possible to access a list of all challenge participants (even if it's paged in some way), and to click on every name on the list to view their challenge tasks.

(While you can use the CSV file for judging the challenge, that's not suitable for everyone because it's confusing and doesn't give the same understanding as the in-website visual view of the tasks.)

**Comment by Alys** [comment]
I'm reopening this because I'm not sure it was meant to be closed. There isn't a full list of participants that lets you see all their progress.

**Comment by TheHollidayInn** [comment]
You can now search the member list, which isn’t the correct behavior. We won’t be loading all members at once.

**Comment by Alys** [comment]
closed because https://github.com/HabitRPG/habitica/issues/9828 is now being used for this issue
