### ISSUE TITLE
pinned Rewards on Tasks page need on-hover effect to show the pin/unpin icon

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9334]
In the Rewards column on the Tasks page, when you hover over any pinned Reward, the pin icon should become visible at the top of the Reward and you should then be able to click on it to unpin the item.

I.e., when you hover, currently you see this:

![image](https://user-images.githubusercontent.com/1495809/32250825-c874bb4e-bed9-11e7-97a9-e73d3753f2d0.png)

The desired effect is the same but with this icon added:

![image](https://user-images.githubusercontent.com/1495809/32251023-e15ff4d8-beda-11e7-91c0-b159b33c519e.png)

Clicking that icon will unpin the Reward and make it disappear from the Rewards column immediately.

**Comment by Alys** [comment]
labels updated

**Comment by klezt** [comment]
Hello @Alys I can deal with this issue.

**Comment by lemoness** [comment]
@klezt Thank you so much! Let us know if you have any questions.

I've updated the labels on this ticket.
