### ISSUE TITLE
Mount Master/Beast Master don't have popups

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9340]
When a user earns the Beast Master, Mount Master, and/or Triad Bingo badges, they don't get any kind of pop-up or confirmation. They also have to reload Habitica to even see the badges in their achievements section. The pop-up modal should happen as soon as they earn it, and the badge(s) should be visible immediately.

**Comment by LunarGem** [comment]
Isn't there already an issue for this?

**Comment by Alys** [comment]
@LunarGem I can't find one but if you see it, post its URL here and we'll close one of them. Thanks!

**Comment by LunarGem** [comment]
I think it's addressing the same problem as this one here: https://github.com/HabitRPG/habitica/issues/9214

**Comment by Alys** [comment]
Ah, no, not exactly the same. :) That one is the popup you see when you create one particular pet or mount. This issue is the achievement earned popup that you should always get when you first get beastmaster or mountmaster.

**Comment by LunarGem** [comment]
Ah. Okay! Got myself turned around a bit. :P

**Comment by TheHollidayInn** [comment]
For issue 1: did we ever have popups for these achievements? I'm not seeing them.

For issue 2: Do we have any way for users to earn this achievement now? Don't you have to use Keys to the Kennel?

**Comment by Alys** [comment]
I have a vague memory of popups for them. Not sure. They're just achievements though so did we have generic achievement popup code that they used? It would be nice to have a popup regardless.

The Beast Master and Mount Master achievements are given the first time you hatch all 90 standard pets and produce all 90 standard mounts. We definitely never had a popup for second, third, etc times. Keys to the Kennel isn't needed to get the achievement. (When you use KeysTTK, the count associated with each achievement is increased but that's all.)

**Comment by TheHollidayInn** [comment]
Okay, perfect. 

So I think I found how the achievement is awarded: https://github.com/HabitRPG/habitica/blob/c06d5107ac7e45fa1edfa803a2085e37633d6113/website/server/models/user/hooks.js#L228.

I think the achievement logic is spread out. I'm not sure why the increment is separate. 

But to solve this issue, I think it would be best to add a notification to the user notifications and check for it in our notifications.vue file.

**Comment by ResamVi** [comment]
Hey I can take on this issue - I'll give it the general achievement popup it lacks

**Comment by Alys** [comment]
@ResamVi Thanks! I've marked it as in progress for you.

**Comment by paglias** [comment]
I think this was fixed in https://github.com/HabitRPG/habitica/pull/11332
