### ISSUE TITLE
Incorrect Armoire Experience Notifications

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9341]
Some users are reporting that every time they click on the armoire, they get an incorrect experience notification. Here is one such report:

"The most recent one I saw went like this:
I click the armoire.
I get a message that I've gained experience, the amount being listed as "+14".
I get a message that I've spent 100 gold.
I get a message that I've gained experience, but now the amount is listed as "23" (without the plus sign, unlike the first case).
The actual amount of experience I gained was 14. This remained true after I reloaded the page."

**Comment by Alys** [comment]
I'm closing this. I believe it has been fixed. I can't replicate it in many tests. We can reopen if it happens again.
