### ISSUE TITLE
Problems with Guild Search in Japanese

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9344]
We've received the following report:

sky_y ( 7bb68622-379f-4bcd-a3a4-b341d3052247 ) 
In Japanese, the guild search in https://habitica.com/groups/discovery doesn't tokenize some Japanese query correctly.
For example, I know 4 groups in Japanese:
日本語話者の集会所/Japanese speaker's resthouse
Habitica 日本語訳 Team
小さい人たちの階段（ASD/ADHD/AS日本語用ギルド）
日本語話者/創作者向けギルド
They surely contain "日本" (meaning "Japan") in their titles, but a search query "日本" in https://habitica.com/groups/discovery hits only "日本語話者/創作者向けギルド".
Could it be fixed or should we (as Japanese communities) do some workaround?

Note from Alys: A related problem - search for this:
日本語訳
and you see two guilds. Remove the final character from the end of that search string and you see one guild.

**Comment by TheHollidayInn** [comment]
This should be fixed with my recent update on guild search.

**Comment by Alys** [comment]
Yes, this is fixed! :tada:   https://github.com/HabitRPG/habitica/pull/9575
