### ISSUE TITLE
Calendar can't be easily closed

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9346]
In task edit mode, you can't dismiss the calendar unless you select a day or cancel editing the task. You should be able to dismiss it by moving your mouse away.

**Comment by paglias** [comment]
@Tressley this should be by moving the away, with a button or clicking outside of it like other dropdowns?

**Comment by paglias** [comment]
@Tressley this should be by moving the away, with a button or clicking outside of it like other dropdowns?

**Comment by Tressley** [comment]
@paglias -- It should be when you click off of it. I'm not a fan of when you're no longer hovering it component as it has too many areas action close to edge of the object.

**Comment by Tressley** [comment]
I have noticed a bug where clicking off of the calendar does not close the calendar. That could be an issue causing the reports.

**Comment by paglias** [comment]
So there's definitely a bug here because the datepicker by default is closed automatically when clicking outside it but for some reason this isn't working when it's inside a modal
