### ISSUE TITLE
Skills Drawer requires 2 clicks to open

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9349]
To open up the action drawer containing the skills when you have it minimized on load, several users have reported that it needs 2 clicks the first time, although after that it always needs only one. One possibility is that some code has it set to "enabled" or "maximized" at the start and the first click "minimizes" it even though it already is minimized. Of course, there could also be other causes.

**Comment by paglias** [comment]
This seems to be due to some conflict between the local open state and the store state
