### ISSUE TITLE
Pinned Items misaligned

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9353]
Pinned items are not aligning to the grid properly when there are only two items in a row (ex. 2, 5, 8...)
<img width="574" alt="screen shot 2017-10-31 at 7 15 57 pm" src="https://user-images.githubusercontent.com/3494081/32257102-35904244-be70-11e7-9bb4-48ccf584bf07.png">

**Comment by rholinshead** [comment]
Hey @lemoness , can I grab this one? I'm assuming we just want the items to begin alignment from the left? Should be a quick fix :)

**Comment by lemoness** [comment]
@rholinshead Yes, they should be pressed to the left. Thank you for helping out!

I've updated the labels on this ticket.

**Comment by Tressley** [comment]
@rholinshead -- Are you part of our Zeplin project yet? If not, is there an email address I can send an invite your way?

I have an artboard in Zeplin to give you the specs for the correct positioning in the Rewards column.

**Comment by rholinshead** [comment]
@Tressley I'm not part of the Zeplin project yet but would like to join. My email is ryanholinshead @ hotmail.com . Btw, this does have an accepted PR with a fix for the alignment, it just needs to be merged by someone with correct permissions :)

**Comment by Tressley** [comment]
@rholinshead -- Zeplin invite sent!

**Comment by rholinshead** [comment]
@Tressley thanks for the invite. I'm able to see 12 screens but none of them appear to be showing the pinned items / Rewards column. Am I looking in the wrong place?

**Comment by Tressley** [comment]
@rholinshead -- My apologies. I exported to the wrong Zeplin project. 🙄 

You can now find the specs here: https://zpl.io/29NN0RA
