### ISSUE TITLE
Indicate that Orb of Rebirth is instant

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9354]
We need clearer text on the Orb of Rebirth indicating that it’s instant. Currently, the text on clicking the orb in the Market reads:

"Orb of Rebirth
Restart your character at Level 1 while retaining achievements, collectibles, equipment, and tasks with history."

It should read:

"Instantly restart your character at Level 1 while retaining achievements, collectibles, equipment, and tasks with history. This will take effect immediately."

**Comment by AmyMendelsohn** [comment]
Hi, this is my first time trying to contribute to habitica, and I'd like to try this.

**Comment by stephqwu** [comment]
@lemoness This is my first time contributing as well, hopefully this works!

**Comment by AmyMendelsohn** [comment]
Aw, okay, I see stephqwu already finished.

**Comment by lemoness** [comment]
@AmyMendelsohn Sorry about the confusion -- there are plenty of other tickets, though, if you're still interested in helping out :)

@stephqwu Thanks so much for helping! We really appreciate it. As a note, in the future it's best to post if you see a ticket that you want to claim to avoid the risk of two people tackling it at once :)
