### ISSUE TITLE
Floating Tooltip in Items

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9355]
If you use your last hatching potion of the type you have selected, this out-of-place tooltip popup doesn't go away until you refresh:

<img width="432" alt="screen shot 2017-10-31 at 7 23 24 pm" src="https://user-images.githubusercontent.com/3494081/32257222-0c72e334-be71-11e7-9a50-8690caeadf61.png">

**Comment by paglias** [comment]
Is this still an issue?

**Comment by Alys** [comment]
I don't recall it being reported recently. We can reopen if needed.
