### ISSUE TITLE
Skills show cut-off text

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9360]
When you go to apply a skill, e.g. Burst of Flames, the outline of the skill hover doesn't fit the content. It should only contain the title ("Burst of Flames"), but instead you can see a bit of the cut-off description.
<img width="238" alt="screen shot 2017-11-01 at 6 00 51 pm" src="https://user-images.githubusercontent.com/3494081/32304761-bf42705c-bf2e-11e7-8b4f-3e2e0fc40870.png">

**Comment by joedragons** [comment]
Looks good (Brutal Smash).  Thanks team!
