### ISSUE TITLE
Incorrect Divider in Food Quick Inventory

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9366]
No matter how many times you cycle through the food in the quick inventory, the item on the right-hand side is always separated out slightly. The idea is that there is a separation that loops around like a conveyor belt. So if you have 10 items, the separator only shows up between item 10 and item 1. Right now, it just separates out whichever item is on the right-hand side. 

We had envisioned it working more like the "Multiple Items" slider demo seen here: http://kenwheeler.github.io/slick/

The divider should only appear between the last item and the first item as a visual identifier that you're back to the beginning, and there should not be a gap.

The divider:
<img width="206" alt="screen shot 2017-11-01 at 9 42 34 pm" src="https://user-images.githubusercontent.com/3494081/32310156-b1e4f154-bf4d-11e7-8fd2-89a7ed1d42eb.png">

What it currently does:

<img width="542" alt="screen shot 2017-11-01 at 9 42 41 pm" src="https://user-images.githubusercontent.com/3494081/32310163-c7e4d424-bf4d-11e7-8388-a67706d7d5f7.png">

It should cycle through like this:

<img width="483" alt="screen shot 2017-11-01 at 9 42 50 pm" src="https://user-images.githubusercontent.com/3494081/32310183-e5f8bd0e-bf4d-11e7-93d2-3052f2ecece4.png">

**Comment by matchajune** [comment]
I will take this one as [#9638](https://github.com/HabitRPG/habitica/issues/9638#issuecomment-349195604) is related.

**Comment by lemoness** [comment]
Thank you! I've updated the labels on this ticket.
