### ISSUE TITLE
Food Quick Inventory Tooltip Persists

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9367]
<img width="601" alt="screen shot 2017-11-01 at 9 39 57 pm" src="https://user-images.githubusercontent.com/3494081/32310108-4ca867c6-bf4d-11e7-9f25-0fff2058b73b.png">
When you close the quick inventory after opening the pet food info, its tooltip remains on the screen.

**Comment by TheHollidayInn** [comment]
Is this still happening? Seems fixed to me on staging.

**Comment by Alys** [comment]
I'll reopen this if I see another report of it.
