### ISSUE TITLE
Back and body accessories don’t show in a player’s stats

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9369]
Back and body accessories don’t show in a player’s stats: 
<img width="623" alt="screen shot 2017-11-01 at 9 56 13 pm" src="https://user-images.githubusercontent.com/3494081/32310457-939ca7b2-bf4f-11e7-88b3-f64ef140667b.png">

**Comment by joedragons** [comment]
This works for me in Windows 10 Firefox, in case that helps.
From the title, I thought this meant stats total not tab, but now that I see the screen, I checked and the images are showing for me.

**Comment by TheHollidayInn** [comment]
This is working on prod. Feel free to open we have more reports.
