### ISSUE TITLE
Repeat on dailies doesn't work

### ISSUE THREAD

**Issue by dragusinb** [HabitRPG/habitica#937]
Choosing a day for the repeat function on dailies doesn't work

**Comment by wizonesolutions** [comment]
@dragusinb Try reloading and doing it again. Sometimes it doesn't work right when you create it, but after reloading the page it will.

**Comment by wizonesolutions** [comment]
And usually it secretly works (if you uncheck today you see the color change) but for some reason the day boxes don't reflect that.

**Comment by StanLindsey** [comment]
@lefnire - is this due to the code we change from an if to a toggle? One of the first days you were down in yee olde england?

**Comment by lefnire** [comment]
should work fine now, still having the same issues?

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by bobolous** [comment]
This still doesn't work for me. I have the exact same problem as described above. On a Daily that's not new (someone above said new Dailies were particularly vulnerable), I can click the days and they become a little brighter, but when click another day that I want it repeated the previously-selected day turns off again and I'm left with only one day selected. I have tried holding shift, control, etc, but I cannot select multiple days. Furthermore when I save the item the selection simply disappears.

I'm therefore unable to turn specify that work-related Dailies should only occur on weekdays. (Or indeed, I'm unable to specify that any Daily should recur only on any given day or days!)

**Comment by deilann** [comment]
@bobolous You actually deselect the days you want, and it should just be clicking -- no keyboard commands required. For work-related dailies, click Sa && Su -- don't click M-F.

Again, this is really old site architecture. I really don't understand why you're having so many Derby related problems.

**Comment by bobolous** [comment]
As in the post referenced above this was my mistake - I was trying to set Repeat days for an item imported from a Challenge, which is therefore locked to that challenge!

Maybe that inability to edit should be more obvious, though.

(I probably wouldn't have made the same mistake with most of my other Dailies as I knew (by experience) that I couldn't edit Challenge Dailies etc. But this Daily was from a Challenge in which it was the only item and I'd forgotten it was imported from there; I thought it was one of my own.)
