### ISSUE TITLE
Improving Market Copy during Grand Galas

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9370]
In the Market, the section for Equipment has this message for all four classes: "You already have all your class equipment! More will be released during the Grand Galas, near the solstices and equinoxes."

This is a little misleading during Grand Galas, because it appears even when you haven't yet purchased all of the currently available Grand Gala equipment from other classes, so you can't tell whether your unpurchased equipment is not shown because you are the wrong class to buy it (something that the Seasonal Shop handles with the new "lock" icon) or because it has to be purchased in the Seasonal Shop, rather than the main Market. And the reference in the Market to new equipment appearing at Grand Galas makes it more confusing if that equipment will only appear in the Seasonal Shop and never in the Market. 

Instead, we'd like the following copy:

No Grand Gala:

"You already have all this class equipment! More will be released during the Grand Galas, near the solstices and equinoxes."

During Grand Gala, class equipment still available:

"You already have all this class equipment! More gear is available right now in the (Seasonal Shop)." (Seasonal Shop should be linked).

During Grand Gala, no class equipment still available:

"You already have all this class equipment! More will be released during the next Grand Gala in several months."

**Comment by librarianmage** [comment]
Is this in progress?

**Comment by lemoness** [comment]
I've changed this status to "help wanted"!

**Comment by veeeeeee** [comment]
If #9362 is fixed first, it should handle this issue. However, given that this is a relatively straightforward change to copy, we are ok to move forward on this fix as an interim solution.

**Comment by adamfitzgibbon** [comment]
Does this require translations?

**Comment by Tressley** [comment]
Closing this issue as we believe the new content release changes address the string concerns.
