### ISSUE TITLE
Opening the party page makes too many requests

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9371]
Every time the party page is opened all these requests are made to the server:

<img width="461" alt="schermata 2017-11-02 alle 10 01 53" src="https://user-images.githubusercontent.com/589911/32317672-e1e1390a-bfb4-11e7-9cbf-14d87ff117cb.png">

There's an extra party request and one for the public guilds that shouln't be there at all

**Comment by gilmoreg** [comment]
I'm looking at this, the public guilds call is made when the ChallengeModal mounts (so you can attach a challenge to a Public Challenges if you have the gems). Unless there's a way to stop it from mounting until it is actually displayed that call will have to stay there.

The duplicate call to /api/v3/groups/party is due to the ChallengeModal dispatching the guilds:getGroup action in addition to Group. The obvious solution would seem to be to save the results of the API call in the store the first time and then fetch it from there afterwards. However I don't know the codebase well enough to know what side effects this might have, and I can't see that there are a lot of client side tests that would make it easier to change this confidently. Any thoughts?

**Comment by paglias** [comment]
> I'm looking at this, the public guilds call is made when the ChallengeModal mounts (so you can attach a challenge to a Public Challenges if you have the gems). Unless there's a way to stop it from mounting until it is actually displayed that call will have to stay there.

we can pass an option to ChallengeModal modal to prevent it from doing that request?

> The duplicate call to /api/v3/groups/party is due to the ChallengeModal dispatching the guilds:getGroup action in addition to Group. The obvious solution would seem to be to save the results of the API call in the store the first time and then fetch it from there afterwards. However I don't know the codebase well enough to know what side effects this might have, and I can't see that there are a lot of client side tests that would make it easier to change this confidently. Any thoughts?

I think the party is already saved into the store since the party member are always in the header. There aren't many tests indeed but if you want to give it a shot I can help you if you have any question

**Comment by gilmoreg** [comment]
Here's the code I think would be changed:
[https://github.com/HabitRPG/habitica/blob/develop/website/client/store/actions/guilds.js](https://github.com/HabitRPG/habitica/blob/develop/website/client/store/actions/guilds.js
)
```
export async function getGroup (store, payload) {
  let response = await axios.get(`/api/v3/groups/${payload.groupId}`);

  // @TODO: should we store the active group for modifying?
  // let guilds = response.data.data;
  // store.state.myGuilds = guilds;

  // @TODO: Populate wiht members, challenges, and invites

  return response.data.data;
}
```
There are already comments hinting this might be a good idea. The simplest thing would be to check if something is already stored, if not, make the API call, store and return it. My question would be, how would we know if the data was stale? Would that ever be a problem?

Or should this be left as is, always calling the API, and a separate action could be created that looks at the store and calls this method if nothing is there or if, somehow, we knew or suspected that the store data was stale?

Also, what is the relationship between guilds and parties? Are parties treated as a special case of a guild?

**Comment by paglias** [comment]
Guilds and parties are both groups but with some different fields, also one user can belong to one party but many guilds.

Regarding storing groups in the store: we only want to store the user party, the guilds should be loaded on demand as it happens now. The data should never be considered stale but clicking on Fetch Recent Messages in the chat page should fetch the entire group again

**Comment by gilmoreg** [comment]
Added PR #9546 to eliminate the second call to /api/v3/groups/party. If we don't want to store guilds I can't think of a way to eliminate that call, unless Vue has some method other than mounted() that only fires when the modal actually appears.

**Comment by paglias** [comment]
@gilmoreg for the other call can you have it fire only if the route is not on the party page? `this.$route` is the current route and it's available in all components so you should be able to check if we're on the party page
