### ISSUE TITLE
Cache the favicon file

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9372]
The favicon we're using is downloaded again any time you visit a new page, it should be cached

**Comment by jnes92** [comment]
Does the current version has a favicon ?
The current website (habitica.com) does not seem to have one attached. 
In my local environment on the latest development branch I also don´t see this file.

_(Btw. was looking for some small issue for getting started to contribute to habitica 👍 )_ 
Would it be fine to use a Webpack plugin/ some other 3rd party for this?

**Comment by paglias** [comment]
@jnes92 hmm you're right...

the site shows a favicon for me 
<img width="437" alt="schermata 2017-11-06 alle 12 42 56" src="https://user-images.githubusercontent.com/589911/32439690-12705ff4-c2f0-11e7-9d34-c9ea18aa0610.png">

but if you go to that url the result is a 404 error and no file exists in git.

So yeah it looks like we should add the file, using a webpack plugin is fine but we already have some plugins setup for files in the /website/client/assets file that get automatically cached if they are loaded through webpack. In this case we might want to add the file directly in the `index.html` thought so that we don't have to wait for the JS to load before showing the icon, in that case our webpack setup is not yet setup to cache those files

I'll get the icons and get back to you

**Comment by librarianmage** [comment]
A favicon PR has already been created here: https://github.com/HabitRPG/habitica/pull/9235

**Comment by paglias** [comment]
Ah I missed that, in that case @jnes92 it would be better to wait for us to merge that PR then you can work on the cache part :)

**Comment by Alys** [comment]
#9235 has been merged. @jnes92 are you still interested in working on caching? If so, we'd love your help!

**Comment by jnes92** [comment]
@Alys Yes, I would like to work on this one ! Thanks for notifying me. I will start it on the next weekend 👍

**Comment by librarianmage** [comment]
@paglias @Alys Should this be marked as in progress?

**Comment by beffymaroo** [comment]
@jnes92 Any updates on your work on this issue? Let us know when you have a chance. Thank you!

**Comment by flhat** [comment]
@beffymaroo Does this issue still exist?  I'm unable to reproduce locally.

**Comment by TheHollidayInn** [comment]
@BlkStormy can you post your network log to show the cached favicon?

**Comment by flhat** [comment]
@TheHollidayInn My bad on this, I realized that it wasn't actually caching when looking into it further.  I'm trying to see if I can pin this one down.

**Comment by flhat** [comment]
@TheHollidayInn Opening up a pull request on this now

**Comment by veeeeeee** [comment]
This is still desired. Hopefully the closed PR offers a helpful way forward to accelerate development on a solution.

**Comment by paglias** [comment]
Actually I just realized this has been fixed by a previous PR, it's not perfect but now the favicon is handled like all the other static files and cached for at least 1 week
