### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by dragusinb** [HabitRPG/habitica#938]
I think that the tooltips for health for example should explain how to get health as a reminder instead of simply saying "health". Just my 2 cents...

**Comment by wc8** [comment]
It might be good in the tooltip _to explain_ that numbers are rounded. Users seeing life with 0 health and no level-up with 240/240 XP often think it’s a bug.

**Comment by SabreCat** [comment]
It's especially odd that mousing over Health and Experience gives you a little ? pointer (at least in Windows), suggesting you can click for help, but clicking does nothing.

**Comment by deilann** [comment]
Agreed @SabreCat !

**Comment by paglias** [comment]
The ? pointer is gone now and I think that health mechanics are described in the tour
