### ISSUE TITLE
Feature request: disable drop system / drop notifications

### ISSUE THREAD

**Issue by goldaryn** [HabitRPG/habitica#939]
Hello, 
Been using habitrpg for a while and it's great. I'm currently running habitrpg locally with a build dated around 27 April. Recently restarted and I've just leveled to the point where I start getting drops. I am getting something drop on completion of every single task. This is becoming a major annoyance as I don't really care about drops as I'm trying to be productive. It's slowing my momentum to close a popup after every single time I do anything. 

So: 
1) Am I meant to be getting a drop after every single task? (Maybe this was resolved since) 
2) Please can we have an option to disable drops/disable notifications 
3) Failing that, can someone point me to a build that predates drops. 
Regards

**Comment by switz** [comment]
You should update your habitrpg. When we were developing, the random drop rate was much higher on a local machine. It has since been changed heavily.  

One fix that might work is to change your NODE_ENV to production.

**Comment by goldaryn** [comment]
I have updated to the latest develop and tested and indeed the drop rates are fixed. :sheepish:

Would I be correct in thinking that to change the NODE_ENV to production I need to change

git clone --recursive -b develop https://github.com/lefnire/habitrpg.git

to 

git clone --recursive https://github.com/lefnire/habitrpg.git

Thanks for a great piece of software, and all your help

**Comment by switz** [comment]
You shouldn't have to set your NODE_ENV as long as you updated develop. You should be good to go now!

**Comment by goldaryn** [comment]
Thanks!
