### ISSUE TITLE
Broken Megaphone Missing

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9392]
You can no longer tell from a task that the Challenge no longer exists, because the Challenge megaphone doesn’t look broken. The broken megaphone icon should be used. 

@Tressley can give you directions about how to get the icon for the broken megaphone.

**Comment by Tressley** [comment]
@lemoness -- We decided on not having a broken megaphone, but rather calling out the icon in red. Would we like to go back to the broken megaphone?

**Comment by Alys** [comment]
@Tressley I'd like it to go back to a broken megaphone for the sake of colour-blind people. Even if the broken colour is different enough to be distinguishable from the non-broken colour, it's going to be harder for them to learn what change to look for when they read about it in the Help guild. In contrast, if the icon image changes, then it will be obvious what they have to look for when they see any description of the icon.

**Comment by lemoness** [comment]
I think creating an alternate icon is probably pretty straightforward, and
then we can have it in red as well.

**Comment by Tressley** [comment]
Icon attached.
[broken-megaphone.svg.zip](https://github.com/HabitRPG/habitica/files/1532837/broken-megaphone.svg.zip)
