### ISSUE TITLE
Close Challenge Popup / modal appears erroneously

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9393]
When editing a Challenge after closing a previous Challenge, the Challenge close dialog pops up after saving the edits to the Challenge. This shouldn't happen.

**Comment by aalsehly86** [comment]
Hello @lemoness I can take care of this.

**Comment by lemoness** [comment]
@aalsehly86 Thank you so much! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by lemoness** [comment]
@aalsehly86 Hi there! How are things going with this fix?

**Comment by aalsehly86** [comment]
The @lemoness! I've submitted some changes to modal stack on PR #9545. I need you guys to test it and let me know please. Hopefully it will take care of this annoying issue because I saw some more users reporting it. Thanks!

**Comment by lemoness** [comment]
Hurrah, thanks for letting us know! We'll take a look at that PR as soon as we can :)
