### ISSUE TITLE
Remove extraneous Settings option

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9397]
The option "Tag list in tasks starts collapsed" should be removed from Settings, since it isn't applicable in the new design.

**Comment by rcmbal** [comment]
Complete newbie here: Would a complete removal of the option in the codebase and their localisations be sufficient or would there be a need of any replacement code?

If it's a matter of deleting the option, I'd like to tackle this task.

**Comment by Alys** [comment]
@rcmbal It's just deleting the option and associated code and locales/en/ string(s). I've marked this as in progress for you. Thank you! Comment here or on any PR you make if you have questions.
