### ISSUE TITLE
Selling items should be input, not dropdown

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9398]
When selling items, you should have an input that is analogous to the batch-buying, not a dropdown. When you click it, you should be able to type in the number that you want, and it should grey out automatically if you try to sell more than you have. The number that you're selling should also reset between items.

For comparison, this is the batch-buying input:

<img width="358" alt="screen shot 2017-11-03 at 6 38 09 pm" src="https://user-images.githubusercontent.com/3494081/32401119-30b5e69a-c0c6-11e7-838c-e4ac7f404067.png">

**Comment by librarianmage** [comment]
May I work on this?

**Comment by Alys** [comment]
@MathWhiz Yes, thank you!
