### ISSUE TITLE
Contributor Title Tooltip

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9400]
You should be able to hover over a contributor’s name tag in chat and see their contributor title (for example,  "Friend Artisan").

**Comment by Alys** [comment]
For whomever works on this:

The player's contributor title does not need to be extracted from the player's profile. Instead, it can be easily found in the chat message. Here's an example of a chat message made by a Tier 6 contributor:
```
        {
            "id": "c81171dd-8a93-4854-a12b-17ba528407cf",
            "text": "the player's message goes here",
            "timestamp": 1509786440177,
            "likes": { },
            "flags": {},
            "flagCount": 0,
            "uuid": "abcdef99-6e4d-48cf-b1ee-abcdeabcdef5",
            "contributor": {
                "text": "Socialite, Scribe, Linguistic Scribe",
                "level": 6,
                "contributions": "a bunch of notes go here",
                "admin": false
            },
            "backer": {},
            "user": "Player Name"
        },
```

The `contributor.text` field is what should appear when you hover over their name.

----

_Related to this, `contributor.level` is what should be used to select the colour and icon when displaying the player's name. The `user` field from the chat message is what should be used to display the player's name._
_I.e., for every chat message, the information about the person who posted it should be taken directly from the chat message - it should **not** be the latest data about the person from their profile. The player's name, title, and colour are historical information and are not updated in old chat messages when they are changed in the player's profile._
_I'm not sure if that's being done currently in the website's code, but it's how it should work. While you're working on making  `contributor.text` appear on hover, if you notice that the code for the player's name, colour, and icon is wrong, feel free to change it if you wish as part of your pull request, or if you prefer, leave it and we'll fix it in a different issue._

**Comment by librarianmage** [comment]
Will the chat message also include `backer` information, if it exists? Otherwise, the coloring of the chat names can't be determined by the chat message alone.

**Comment by librarianmage** [comment]
I can work on this!

**Comment by librarianmage** [comment]
Relevant code:

https://github.com/HabitRPG/habitica/blob/12fd79059b09f258bf9f7d54415180f03a2c8ba8/website/client/components/chat/chatMessages.vue#L25-L31

https://github.com/HabitRPG/habitica/blob/560d247c9b5a09e6f568798fe8382d887eaf34d5/website/client/mixins/styleHelper.js#L2-L17

**Comment by librarianmage** [comment]
Never mind, it is

**Comment by Alys** [comment]
@MathWhiz It's yours, thanks! Excellent question too - I hadn't thought about the NPCs. Thanks for finding out about that!
