### ISSUE TITLE
Action Drawer opened with top bar

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9402]
Clicking anywhere on the top bar of the action drawer on any page (such as the skills bar or quick inventory) should open or close it. You shouldn't have to move all the way to the tiny arrow in the right hand corner to interact with it.

**Comment by trvrfrd** [comment]
Any special steps to reproduce this? I'm able to click anywhere on the top bar of the action drawer and have it open and close as expected (except on the first click of the skills drawer as in #9349). Working as expected in both Firefox and Chrome.

**Comment by lemoness** [comment]
@trvrfrd Thank you for investigating this! It looks like this is actually a duplicate of the issue, so I'm closing this now.
