### ISSUE TITLE
Too-long checklist names break border

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9403]
If the name in a Checklist is too long, it will not be truncated and will cross the box's border. Instead, it should wrap automatically.

**Comment by TNychka** [comment]
I can cover this, I have a fix nearly done. Just to make sure I'm not missing anything, this should only be css changes in task.vue correct?

**Comment by librarianmage** [comment]
Should this be marked as in progress?

**Comment by TNychka** [comment]
Yep, https://github.com/HabitRPG/habitica/pull/9404

**Comment by joedragons** [comment]
Oi, just noticed this bug prevents move to top.  Looking forward to this fix, thanks!
/me goes and does some manual drag drop.
