### ISSUE TITLE
special characters in profile names cause chat message highlighting to fail (regex error)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9405]
If a player's name contains a closing bracket `)` and if a message to that player exists in any chat area, then a regular expression error happens when the player views the chat area and they are not able to see the message to them, or any messages that appear after it. This was reported by the player "Stay Whelmed :)" 7d8263bd-7b74-4d71-8da2-95ee147b14fe but I've replicated it with a test user.

Below is a screenshot of a party containing the test user when the user's name was set to `name with bracket :)`  Party chat contains a message saying `Hi @name with bracket :)` however as you can see in that screenshot, the message doesn't appear and the javascript console shows a regex error `SyntaxError: Invalid regular expression: /name with bracket :)([^w]|$){1}/: Unmatched ')'(…)`

![image](https://user-images.githubusercontent.com/1495809/32408855-c0c1ce04-c1eb-11e7-88f9-52ae827f14b9.png)

When I changed the test user's name to remove the bracket, the regex error stopped happening and the player was able to see all chat messages:

![image](https://user-images.githubusercontent.com/1495809/32408864-f3ba9fb6-c1eb-11e7-8628-dfc0055b9495.png)

This indicates that the regex error is happening when chat is being parsed to highlight all messages to the player. Special characters in the player's name should be escaped to allow the regex to work.

**Comment by pcvonz** [comment]
Hey, I can take a look at this one.

**Comment by lemoness** [comment]
@pcvonz Thank you very much! Let us know if you have any questions.

I've updated the labels on this issue.

**Comment by librarianmage** [comment]
Oops! Sorry @pcvonz, I forgot to ask here before submitting a PR yesterday.

**Comment by pcvonz** [comment]
@MathWhiz No worries! I'll find another issue.
