### ISSUE TITLE
Home Page Hangs at White Image of Logo in Internet Explorer 11

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#9407]
I can't reach the Report a Bug guild from the Habitica website; feel free to redirect this bug as necessary.

### General Info
  * UUID: Can't get it
  * Browser: Internet Explorer 11
  * OS: Windows 7 x64

### Description
When I go to https://habitica.com/, I see a purple screen and then nothing happens.

To reproduce the problem, launch Internet Explorer 11 and go to https://habitica.com/.

#### Console Errors
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: habitica.com
SCRIPT16389: Unspecified error.
File: habitica.com, Line: 1, Column: 1
HTML1300: Navigation occurred.
File: habitica.com
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: habitica.com, Line: 1, Column: 450
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: app.54985c80fc311ab97dda.js, Line: 1, Column: 896729

**Comment by Alys** [comment]
Zian, this is a good place for bugs when you can't get in to Habitica!

Please go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there, then reload the website using your browser's refresh button while you are holding down the "Control" or "Command" key on your keyboard. Does that help?

**Comment by Zian** [comment]
When I go to the aforementioned URL, I get the following console errors:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: clear-browser-data
HTML1300: Navigation occurred.
File: clear-browser-data
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: clear-browser-data, Line: 1, Column: 450
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: app.54985c80fc311ab97dda.js, Line: 1, Column: 896729


I already tried clearing the browser's cache and restarting the computer. I also tried pressing CTRL while clicking the refresh button.

**Comment by Zian** [comment]
Here's a screenshot:
![habit rpg purple screen of death](https://user-images.githubusercontent.com/1581929/32423015-d55f7380-c258-11e7-8b22-efb570221ce3.png)

**Comment by Alys** [comment]
See another report of this at https://github.com/HabitRPG/habitica/issues/9675

**Comment by paglias** [comment]
@Zian we've just been able to fix this issue finally and it'll go live in the next few hours. I'm not exactly sure when but by tomorrow the site will work on IE 11. Let me know if you have any other issue :)
