### ISSUE TITLE
Dailies and Todos don't hurt me and don't change color over time nor when clicked

### ISSUE THREAD

**Issue by lukyss** [HabitRPG/habitica#941]
Hi,
My dailies keep their color even after doing or not doing them repeatedly and I don't lose hp for the red ones.
My Todos also stopped chaning color and don't hurt me even though they are dark red.
Thanks for help

**Comment by StanLindsey** [comment]
Todos aren't suppoesd to hurt you, only dailies. 

Are you checked in to the inn?

**Comment by lukyss** [comment]
No, I am not checked in to the inn, though I will check that just to be
sure.
Todos aren't supposed to hut me? But they did hurt me until now.
Dne 13.5.2013 13:04 "Stan Lindsey" notifications@github.com napsal(a):

**Comment by StanLindsey** [comment]
To-Dos are supposed to degrade but never hurt you if you don't complete them. 

Very odd if they do. Confirm the inn and then I'll up the priority on this.

**Comment by lefnire** [comment]
@lukyss what's your habit user id?

**Comment by lukyss** [comment]
I wasn't checked to the inn.
My user id is 27d79a13-7705-438a-ba52-85a79146e67f.

**Comment by lefnire** [comment]
I tested your account locally, everything seemed to work just fine. Are you
still experiencing this issue now? Do you get any javascript errors in the
Chrome console? Also, which browser / OS do you use?

**Comment by lukyss** [comment]
I tried it and it works now.
Thanks for help.
And I just wanted to say that HabitRPG is a great idea, great job! ;)
