### ISSUE TITLE
Amazon subscription payments are being converted to gem payments

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9414]
Sometimes when a player attempts to use Amazon to buy a subscription, what actually happens is a $5 gem purchase. One example of a user's bug report is below.

The staff are already aware of this issue and are working on it but I'm opening this issue so that players affected by it can find out when it's been fixed. Note though that once this issue is closed, it might be a couple of days before the fix id deployed to the website. Deployments can be seen on the [Releases](https://github.com/HabitRPG/habitrpg/releases) page but I'll try to remember to add a final note to this issue when deployment has occurred - after that it will be safe to use Amazon for subscriptions again.

_"Just like last month, I tried using Amazon pay to purchase a 12-mo subscription and instead it went through as a $5 gem purchase. I am using the https://habitica.com/user/settings/subscription page which doesn't even have an option to buy gems, only varying lengths of subscriptions. When the Amazon window pops up, it doesn't have any item description or even an amount, so I have to actually make the purchase and then see that it is not what I chose on the subscription page when the email receipt comes (or I wouldn't keep doing this, I promise)."_

**Comment by TheHollidayInn** [comment]
This should be fixed by https://github.com/HabitRPG/habitica/pull/9562

**Comment by lemoness** [comment]
Was this actually fixed? Can this ticket be closed?

**Comment by Alys** [comment]
I haven't seen reports for ages. Closing.
