### ISSUE TITLE
cron runs too early after a time zone change

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9415]
There seems to be a new problem in the code in cron that is supposed to protect the user from an inappropriate cron when the user's time zone changes. Below are several reports that were made in the Report a Bug guild. I believe this is a relatively new problem because I don't recall it happening the last time the USA changes time zones. A few days ago, we also saw similar reports from European players.

AnneLine ( 16a107de-d519-43ce-8c30-8da5cbcbb237 ) :

And now Cron just ran again, (so at 11pm and 12 mindnight, PST) we have gone from 0/25 on the rage bar at 10:59PM to 'Rage 8.70 / 25' now -- and I have checked off all my dailies (and there are tons of them!) each time. I don't care about the mana, but it's creating a big problem with battling this monster if we are getting it enraged for no reason... although we have gotten a ton of extra (uh, unearned) credit toward defeating it... but I'm worried about what may happen when the others wake up tomorrow....

Thanks for any help you can give us!

luckat ( cb195030-0b6c-4fac-bc9b-1bbf298f3d4f ) :

Like a few others here, my Cron ran early today, probably because of Daylight Saving Time. It then ran again a few minutes later (when it was supposed to). It also had some of the wrong dailies to check off both times, and was missing some that should have been there (which is especially annoying in the case of challenge dailies). This is just like when this happened a couple weeks ago when I changed time zones (the double Cron and the wrong dailies to check off), except this time I know I was on Habitica on my computer after the time on it updated. In case it matters, I was only on Habitica on the iOS app on my phone both times Cron happened and between those two instances.

citrusella, the serving wench ( 2d6ef231-50b4-4a22-90e7-45eb97147a2c ) :

My cron either ran 1-2 hours late (no timezone change other than going back to standard time), or it didn't run (other than making some dailies that weren't due over the weekend blue) until I restarted my browser entirely. When it ran, I had two dailies in my RYA that were neither due today nor due yesterday AFAIK. They were grey in the RYA modal. Checking them off didn't check them for today, though, so... (I would have chalked this up to the "fall back" (or at least waited to see if it happened again) but it was just weird enough I felt like I should report.)

AnneLine ( 16a107de-d519-43ce-8c30-8da5cbcbb237 ) :

And on my pc (Chrome, stylish) my Cron also ran 15 minutes early. And managed to hit my party for about 4 units of damage which is serious given the tough boss we are battling....

japanese_goblin The Monster of Time-change is attacking us -- Come to our aid, valiant Bug Slayers!!!!

Amygp ( d8d19eb3-2a2b-48da-9867-c63828176faf ) :

On IOS, my CRON ran an hour early tonight. The time change was this morning so not sure why it was confused tonight. I will stay out of it until tomorrow morning to prevent issues.

Birkwelch ( 310aea01-13f5-4fb6-929e-be39d63e665b ) :

(@Alys) Related to the post you copied from the tavern - I was using the Android app when I first saw the RYA screen an hour before I expected - closed the app without using the RYA, went to the website, checked off my dailies there (I think I recall being able to do so without RYA on the website), then I believe cron ran when I did a resync/reload, then I went back to the app, checked out of the inn, noticed my previous days dailies were showing due again, checked them off in the app, and had another cron an hour later on the app. Sorry I didn't report it then or for any misremembered details, I was a bit flustered figuring out what was going on. But it may also be a problem with the app, or with switching back and forth between the app and website.

katieslug ( 4a99b99e-6d1d-439a-b3a6-23cc895f4411 ) :

iOS app is behaving strangely. Tonight (Sunday) before midnight it chroned, but it brought up Saturday?s dailies in the ?check off what you did yesterday? pop-up. So I did that, then my Sunday stuff all appeared and I checked it off again (because what I checked off during the day was now unchecked again). Then at midnight it chroned again, and again Saturday?s dailies popped up, even though it?s now Monday. Strange! I assume the two chrons are a glitch from the time change but I don?t know why Saturday?s dailies keep coming back. Also tonight my inventory started showing two of most of the eggs. Bear and cactus eggs are normal but all the other eggs are duplicated (like, same thing copied on two rows...dragon, 16, dragon, 16). When I hatch a pet, the number of eggs in the inventory goes down in one of the eggs but not its duplicate (so like dragon, 16, dragon, 15). Potions are normal.

Nephren-Ka ( d07b61e8-236c-4002-99de-262fc0a9e5ae ) :

I just had a major mess up which clicked my life down to 37 even though I did everything... at 11pm the system thought it was 12 pm and changed, I assume it didn't sync up with the daylight savings here so I clicked off the things I did, because it would not let me click it normally and had to through there, however ONE thing did not show up on there to click which I was just coming to click. Plus it had things up which were not even due to click. I clicked what I did do. Which were what was due. And I couldn't click one which wasn't there so I lost life. Then at 12 pm right now I come back to see what things I can get done right now (early Monday), and ALL the dailies for Sunday came up as not done, Sunday is my big list of dailies, and I was like "arg I did all these" all so I clicked them off... but there were things not due which were even grey showing up and I saw no reason to click those, in fact some that showed up didn't even make sense since my rent isn't due until next month now (and already did it a few days ago when it was)... so I didn't click that right now and I lost life again. :( I'm slightly OC and I try REALLY hard not to lose even a single life point. I don't know what happened, or if it will happen again. Or what I'm suppose to do if it does. I don't want to click things which were not even due. I'm very confused. :(

 
 Alys ( d904bd62-da08-416b-a816-ba797c9ee265 ) :

 copying from the Tavern for my reference so I can look into this when I get home: Birkwelch ( 310aea01-13f5-4fb6-929e-be39d63e665b ): @supermouse35 Some people (including myself) were hit by a bug that caused cron to happen twice due to the time change. I think it is dependent on if you happen to login between when it would have been your new day and when it is now.

**Comment by librarianmage** [comment]
Possibly related:

* https://github.com/HabitRPG/habitica/issues/8944
* https://github.com/HabitRPG/habitica/issues/8828

What are your thoughts, @Alys?

**Comment by Alys** [comment]
Yeah, could be related. At the very least it's good to have them all linked together. Thanks MathWhiz!

**Comment by librarianmage** [comment]
No problem!

**Comment by TheHollidayInn** [comment]
Adding for notes, a good way to address this issue would be to add unit tests for daylight savings time around this new-ish function `https://github.com/HabitRPG/habitica/blob/4618fd8954a7c3f4d4fc486ce25536a61de6349c/website/server/models/user/methods.js#L196`. Now that the code is abstracted from the cron middle ware, we can probably add more tests as well. I'll take this up if no one claims it soon.
