### ISSUE TITLE
Local Installation: dist-client error

### ISSUE THREAD

**Issue by splashofcrimson** [HabitRPG/habitica#9421]
Hey, I'm having trouble with my local installation of habitica. I was able to get everything running without errors, but when I navigate to localhost:8080, I get the error: ERR_CONNECTION_REFUSED, and when I navigate to localhost:3000, I get the error: 
{
success: false,
error: "Error",
message: "ENOENT: no such file or directory, stat 'C:\home\habitica\dist-client\index.html'"
}

Could someone please guide me in the right direction? I can provide other applicable information when necessary.

Relevant information:
Operating System: Windows
Methods: Installing Habitica directly onto my laptop

**Comment by librarianmage** [comment]
Did you wait for the webpack to compile? Once `npm run client:dev` starts, it will take a bit before you can actually run the site.

**Comment by splashofcrimson** [comment]
@MathWhiz  Ok, I waited for around ten minutes, and I was hit by a long series of errors "Expected linebreaks to be 'LF' but found 'CRLF'. I suspect it would be relate to the fact that I'm running a windows PC, but when I run git config core.autocrlf, it is indeed true. Did i set this up incorrectly?

**Comment by librarianmage** [comment]
Did you commit all of your files before running the server?

**Comment by librarianmage** [comment]
Did the errors say which files were messed up?

**Comment by splashofcrimson** [comment]
Here's a screenshot of the errors I'm getting. I haven't committed anything before running the server, is that something I was supposed to do?

![image](https://user-images.githubusercontent.com/26318707/32470452-f02d9598-c325-11e7-9ef4-2035c93a667d.png)

**Comment by librarianmage** [comment]
Oh, no, I was just asking that in case the errors were happening due to an
edit

**Comment by librarianmage** [comment]
Should `autocrlf` be true? Shouldn't all of the lines end with LF?

**Comment by splashofcrimson** [comment]
I set 'autocrlf' to false, and I'm still getting the same errors. I'll try restarting my PC and running everything again.

**Comment by librarianmage** [comment]
You might want to pull again

**Comment by splashofcrimson** [comment]
Ok! So I fetched from upstream and updated my local repo, and everything seems to be updated. Still same errors regardless of my autocrlf setting, but now I'm getting this new message at the end. Progress? (By the way, thank you for helping!)

![image](https://user-images.githubusercontent.com/26318707/32470884-8490dcfc-c328-11e7-9155-820d688928ff.png)

**Comment by librarianmage** [comment]
No problem! It seems like your problem is a bit more difficult than expected. Does the actual website work now?

**Comment by splashofcrimson** [comment]
Yes! It works!!! The error's still there though, I'd presume I'd need to fix that before submitting any pull requests.

**Comment by librarianmage** [comment]
I would think so. Maybe the git config will fix that for you?

**Comment by kartikadur** [comment]
In your case ESLINT (the linting code) is throwing the errors, nothing wrong with the codebase as far as the screencaps show. The [eslint: linebreak-style](https://eslint.org/docs/rules/linebreak-style) rule is enforcing a check for `LF`.

> ... the default behavior of git on Windows systems is to convert LF linebreaks to CRLF when checking out files, but to store the linebreaks as LF when committing a change. This will cause the linebreak-style rule to report errors if configured with the "unix" setting, because the files that ESLint sees will have CRLF linebreaks. If you use git, you may want to add a line to your .gitattributes file to prevent git from converting linebreaks in .js files:<sup>1</sup>
> ```javascript
> *.js text eol=lf
> ```
 
If your local code files are stored with `crlf` instead of `lf` then as a temporary solution create a `.gitattributes` file with the above code at `~/website/` (or higher). Then list the `.gitattributes` file in `.gitignore` so it doesn't get added to the master repo. 

Or you can change it so that your files are stored locally with `lf` line endings. Only problem here is that you may have to re-clone a local repo for the errors to go away.

This should solve your problem.

1 [eslint: linebreak-style: ESLINT Rules](https://eslint.org/docs/rules/linebreak-style)
2 [GitAttributes File: git-scm](https://git-scm.com/docs/gitattributes)
3 [GitAttributes File Location: stackoverflow](https://stackoverflow.com/a/28027656)
4 [Git LineEndings: git-help](https://help.github.com/articles/dealing-with-line-endings/)

**Comment by splashofcrimson** [comment]
Edit: Never mind, it worked for a good 15 - 20 minutes, but I'm getting the same error again.

My .gitattributes file is indeed there, I put it in the habitica folder (above the website folder):

![image](https://user-images.githubusercontent.com/26318707/32585512-c56dc95c-c4cb-11e7-8189-0daa97181819.png)


inside the .gitattributes file:

![image](https://user-images.githubusercontent.com/26318707/32585400-45b28e00-c4cb-11e7-8422-c6a25b368995.png)

My autocrlf setting is still false globally, and I followed all the instructions in one of the linked tutorials:
https://help.github.com/articles/dealing-with-line-endings/

Here's a screencap of the errors (Although I believe they're still the exact same as before):
![image](https://user-images.githubusercontent.com/26318707/32585444-83aec6d8-c4cb-11e7-81b0-e3bb8e537eae.png)

Thanks again for all the help, I'm so sorry my computer is being so stubborn.

**Comment by kartikadur** [comment]
Yeah it is still the eslint stuff. something (possibly your IDE) might be reverting your code files to `crlf` line endings?

You could try setting your line endings in your IDE. I use vscode and it allows me to set the line endings per file. what IDE are you using?

edit: Another option is to turn off the eslint: linebreak-style rule for the duration where you lint and run the code. You can turn it on after/ when commiting the repo.

**Comment by kartikadur** [comment]
I managed to get rid of the eslint: linebreak-style errors, this solution worked for me.
Leaving a solution in case anyone else stumbles here. 

_note: the `end of line` settings have to be in place before the repo is cloned locally in either case_

This works for me as I prefer unix style line endings even though I use a windows machine:
+ delete local repo clone
+ reinstall git with the line endings conversion as 'checkout as-is, Unix-style line endings'
+ clone repo

_alternative solution:_ 
+ place a `.gitattributes` file with the lines `*.js text eol=lf` and `*.vue text eol=lf` in the root folder
+ checkout/clone the repo again

**Comment by paglias** [comment]
@kartikadur thanks for the investigation, going to close the issue
