### ISSUE TITLE
Loading Page Tips

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9423]
Here are the new tips that should display under the loading screen. 

Tip #1. Check tasks on the go with the Habitica mobile apps.
Tip #2. Click any equipment to see a preview, or equip it instantly by clicking the star in its upper-left corner!
Tip #3. Use emoji to quickly differentiate between your tasks.
Tip #4. Use the # sign before a task name to make it really big!
Tip #5. It’s best to use skills that cause buffs in the morning so they last longer.
Tip #6. Hover over a task and click the dots to access advanced task controls, such as the ability to push tasks to the top/bottom of your list. 
Tip #7. Some backgrounds connect perfectly if Party members use the same background. Ex: Mountain Lake, Pagodas, and Rolling Hills.
Tip #8. Send a Message to someone by clicking their name in chat and the clicking the envelope icon at the top of their profile!
Tip #9.  Use the filters + search bar in the Inventories, Shops, Guilds, and Challenges to quickly find what you want. 
Tip #10. You can win gems by competing in Challenges. New ones are added every day!
Tip #11. Having more than four Party members increases accountability!
Tip #12. Add checklists to your To-Dos to multiply your rewards!
Tip #13.  Click “Filters” on your task page to make an unwieldy task list very manageable!
Tip #14. You can add headers or inspirational quotes to your list as Habits with no (+/-).
Tip #15. Complete all the Masterclasser Quest-lines to learn about Habitica’s secret lore.
Tip #16. Click the link to the Data Display Tool in the footer for valuable insights on your progress.
Tip #17. Use the mobile apps to set reminders for your tasks.
Tip #18. Habits that are just positive or just negative gradually “fade” and return to yellow.
Tip #19. Boost your Intelligence Stat to gain more experience when you complete a task.
Tip #20. Boost your Perception Stat to get more drops and gold.
Tip #21. Boost your Strength Stat to do more boss damage or get critical hits.
Tip #22. Boost your Constitution Stat to lessen the damage from incomplete Dailies.
Tip #23. Reach level 100 to unlock the Orb of Rebirth for free and start a new adventure!
Tip #24. Have a question? Ask in the Habitica Help Guild!
Tip #25. The four seasonal Grand Galas start near the solstices and equinoxes.
Tip #26. An arrow to the right of someone’s name means they’re currently buffed.
Tip #27. Did a Daily yesterday, but forgot to check it off? Don't worry! With Record Yesterday's Activity, you'll have a chance to record what you did before starting your new day.
Tip #28. Set a Custom Day Start under User Icon > Settings to control when your day restarts.
Tip #29. Complete all your Dailies to get a Perfect Day Buff that increases your stats!
Tip #30. You can invite people to Guilds, not just Parties.
Tip #31. Check out the pre-made lists in the Library of Tasks and Challenges Guild for example tasks.
Tip #32. Lots of Habitica’s code, art, and writing is made by volunteer contributors! Head to the Aspiring Legends Guild to help.
Tip #33. Check out The Bulletin Board Guild for news about Guilds, Challenges, and other player-created events - and announce your own there!
Tip #34. Occasionally re-evaluate your tasks to make sure they’re up-to-date!
Tip #35. Users who are part of a Group Plan gain the ability to assign tasks to other users in that Group for extra task management and accountability.

The design is as-follows:
<img width="721" alt="screen shot 2017-11-16 at 4 34 22 pm" src="https://user-images.githubusercontent.com/3494081/32923379-20fee532-caec-11e7-966d-8620aefd76ad.png">

Whoever would like to tackle this should post with their email so that @Tressley can invite them to our contributor Zeplin!

**Comment by mandyzhou** [comment]
For Tip #26, the arrow indicating a buff is now on the player's name's right, not left.

**Comment by lemoness** [comment]
Good catch, thank you! I'm editing this now.

**Comment by lemoness** [comment]
The design is now finished for this issue, and it's ready to claim!

**Comment by lemoness** [comment]
I've updated the labels on this ticket.
