### ISSUE TITLE
Group Plans Tasks Show Edit Modal in Task Board

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9427]
In Group Plans, when editing a task title assigned to yourself from your taskboard, it allows you to save the edit and displays the new text for .5 sec before reverting to original title. You can edit successfully from the Group task board. Editing the title is supposed to be blocked from the personal taskboard, so we should disable the field in the modal.

**Comment by majestic-owl448** [comment]
This is an issue also for challenges tasks. I can edit title, dates, difficulty, but then the changes revert soon after. Is also this fixed by @TheHollidayInn fix?

**Comment by Alys** [comment]
@Ieahleen It's not fixed by that fix but we have it recorded here: https://github.com/HabitRPG/habitica/issues/9391
