### ISSUE TITLE
Enchanted Armoire "all items found" popup too early

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9431]
The pop-up that appears when you've bought all the Enchanted Armoire items telling you that you've found all the pieces of equipment is appearing too early. It also appears repeatedly. The popup should only appear when you've actually found all of the pieces in the Enchanted Armoire.

**Comment by TheHollidayInn** [comment]
I think this may have been related to: https://github.com/HabitRPG/habitica/pull/9463 where basically on the client side, the user received an item thus completing armoire, but on the server they did not.

**Comment by Alys** [comment]
That makes sense. I've not seen it reported recently. We can reopen if needed.
