### ISSUE TITLE
Tags list does not scroll

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9434]
The tags list in the task creation/edit dialog does not scroll. This means that if the user has a lot of tags, they're unable to select/deselect the tags at the top of the tags list, because they're displayed off-screen.

**Comment by TheHollidayInn** [comment]
This looks fixed to me. The modal seems to now grow as you have more tags.

**Comment by Alys** [comment]
Confirmed okay for me in staging and I have a lot of tags.
