### ISSUE TITLE
Monthlies inaccurate?

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9435]
We've received a user report that they created two Dailies and set them to repeat monthly on the same day of the month, but when they checked them off, they both showed up as "Due" the next day.

**Comment by Alys** [comment]
Might be related to this: https://github.com/HabitRPG/habitica/issues/9200

**Comment by TheHollidayInn** [comment]
Do we have any more reports of this? If not, we should probably close this and try the start date fix, because that error would definitely cause this issue.

**Comment by Alys** [comment]
I'm pretty sure now this is the same as #9200 so I'm closing this as a dupllicate.

If it turns out to be different, that will be easier to identify when 9200 is fixed.
