### ISSUE TITLE
Persistent Incorrect Due Dates

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9436]
If you create a task with a due date set for that same day, the task is labeled "Due a few seconds ago". If you then change the due date, the task is still labeled the same way. In order for the task to be labeled correctly (like "Due in 3 days"), you have to clear the due date, save changes, assign the correct date and save again (or refresh the page).

**Comment by paglias** [comment]
Going to work on this

**Comment by paglias** [comment]
Fixed in #9442
