### ISSUE TITLE
When registering from the home page cannot press Enter to submit the form

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9439]

**Comment by Gabomfim** [comment]
does somebody know where is the home page code at?

**Comment by paglias** [comment]
https://github.com/HabitRPG/habitica/blob/develop/website/client/components/static/home.vue

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitica/pull/9452/commits/6b1a893d6ae7c7d948000a43d7789f9cd7571df4
