### ISSUE TITLE
[unused]Pixel Art Thread: Crafting & Custom Gear

### ISSUE THREAD

**Issue by StanLindsey** [HabitRPG/habitica#944]
[Now unused, check #943]

Due to #107 becoming fairly unwieldy we're splitting it into a number of different threads based on the feature the art is intended for.

This is the thread for the upcoming Crafting System as well as custom gear. 
Discussion to be held [on Trello](https://trello.com/card/crafting/50e5d3684fe3a7266b0036d6/279)

There are also threads for:

Mounts - #942 
Classes - #943 
Quests - #945 
Miscellaneous - #946

**Comment by lemoness** [comment]
Some potential art by @Shaners

Gem colors.... but because of the gem/token switch, I think we shouldn't use these. We'll just confuse people :( 
https://f.cloud.github.com/assets/2374703/320196/dc46b9bc-9920-11e2-84ad-70ea50eedf1c.png

Shane also made these items which I think would be perfect - gold dust, acid, and coal/shade ash.

![dlstuff](https://f.cloud.github.com/assets/3494081/498850/c6b0daa0-bc21-11e2-9300-0eab038d59cb.png)

**Comment by StanLindsey** [comment]
Re: Crafting. I couldn't find a Trello card for it but the plan is to at a later point expand the pet/mount system with gear drops and crafting.

**Comment by lefnire** [comment]
We should all chat about that one, I'm unfamiliar. I remember quests will drop items, and potentially normal tasks drop crafting material - combined to create a special item. Unofficial feature than you and I were talking about offline. But unfamiliar with this pets & mounts gear bit

**Comment by StanLindsey** [comment]
I only used pets & mounts as a comparison to what we already have - otherwise its exactly as you say; "normal tasks drop crafting material - combined to create a special item"

I mostly wanted to create a placeholder for it - I don't foresee this thread being very active right now.

**Comment by lefnire** [comment]
Ah, my bad!

**Comment by StanLindsey** [comment]
@Shaners - it would work exactly how pets and mounts work now. Instead of an egg you get for example leather, and stash enough to turn them into an armour piece. (similar to feeding a pet to turn them into a mount).

That said - although myself and tyler have semi-hashed this out its 1. A long way off due to other priorities and 2. always up for discussion. 

This is more of a placeholder for a system I think is 99% sure to go in at some point. I do need to clarify the system we have at the moment though.

**Comment by StanLindsey** [comment]
Well its possible to evolve into alchemy & enchantments. Atm view the pets system as already a crafting system for pets. 

I think we're going to add gear specifically to be crafted and keep the gold-store as is. The gold store is fantastic as the free starter gear due to its low skill ceiling and easy communication. This is a feature going in after classes & quests. So I this is (rightly so) much more of a discussion thread until then.

**Comment by StanLindsey** [comment]
Sorry didn't really add much. In my eyes the first crafting system will have drops of leather, iron and cloth that when combined create the specific items towards a gear set. Designed mostly with classes in mind.

We could expand this into enchantments in that you craft your armour with enchantment items that give it modifiers etc.

Also like the idea of alchemy for potions/buffs etc.

**Comment by lefnire** [comment]
Shall we create a crafting trello? Pretty pie-in-the-sky at present, we
could get some input from out-n-about, and leave this ticket for art

**Comment by StanLindsey** [comment]
A lot of is pretty pie in the sky as other features are definitely a priority over this. Due to that the design isn't 100% fleshed out and I hadn't even thought of expansion into alchemy etc. One of the important things is that the systems are simple and communicated well. I think we could totally have these systems in place if the mechanics and visual design supported it. 

That said: Moving to [Trello](https://trello.com/card/crafting/50e5d3684fe3a7266b0036d6/279)

**Comment by Shaners** [comment]
Maybe the first cooking item could be Sky Pie?

###### Deleted previous messages

**Comment by Awesumounk** [comment]
How about crafting scrolls? A potion used on paper could turn into a scroll?

**Comment by lemoness** [comment]
@Awesumounk This GH thread is no longer in use. For feature requests, please use Trello :)
