### ISSUE TITLE
Group Plans -- Incorrect Assigned Users Count

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9444]
I have a Group Plan task that is assigned to me and one other person in the Group, but it says "Assigned to you and 2 others." It's a three-person group, so it's either counting me twice, or erroneously thinks that the third member of the Group Plan has been assigned to the task.

**Comment by Alys** [comment]
As a note for anyone investigating this:
The bug is almost certainly that the group leader is being counted twice so I'd recommend starting to look into it there.

**Comment by TheHollidayInn** [comment]
Fixed in this commit: https://github.com/HabitRPG/habitica/pull/9437/commits/5ea06a22a0e4439d27a4ec7464cb9ee7e9a8ef28
