### ISSUE TITLE
Can't remove Group Plan user

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9445]
As the leader of a Group Plan, you are currently unable to remove an unwanted user from your Group Plan. It produces the error "no such subscription" as well as the following in the developer console:

[Error] TypeError: null is not an object (evaluating 'this.partyMembers.map')
members — 2.9b6c295f2feab413449c.js:5699
get — vue.runtime.esm.js:3040
evaluate — vue.runtime.esm.js:3147
(anonymous function) — vue.runtime.esm.js:3432
a — questDetailsModal.vue:1:462
_render — vue.runtime.esm.js:4407
r — vue.runtime.esm.js:2697
get — vue.runtime.esm.js:3040
wi — vue.runtime.esm.js:3029
At — vue.runtime.esm.js:2701
init — vue.runtime.esm.js:4003
l — vue.runtime.esm.js:5442
u — vue.runtime.esm.js:5378
h — vue.runtime.esm.js:5513
u — vue.runtime.esm.js:5418
(anonymous function) — vue.runtime.esm.js:5936
_update — vue.runtime.esm.js:2579
r — vue.runtime.esm.js:2697
get — vue.runtime.esm.js:3040
run — vue.runtime.esm.js:3117
It — vue.runtime.esm.js:2883
(anonymous function) — vue.runtime.esm.js:1785
it — vue.runtime.esm.js:1706
promiseReactionJob

	rt (vendor.7ae272c2c1386c8b8bff.js:6:6553)
	nt (vendor.7ae272c2c1386c8b8bff.js:6:6469)
	et (vendor.7ae272c2c1386c8b8bff.js:6:6335)
	_render (vendor.7ae272c2c1386c8b8bff.js:6:45409)
	r (vendor.7ae272c2c1386c8b8bff.js:6:10973)
	get (vendor.7ae272c2c1386c8b8bff.js:6:40483)
	wi (vendor.7ae272c2c1386c8b8bff.js:6:40405)
	At (vendor.7ae272c2c1386c8b8bff.js:6:10997)
	init (vendor.7ae272c2c1386c8b8bff.js:6:41989)
	l (vendor.7ae272c2c1386c8b8bff.js:6:51497)
	u (vendor.7ae272c2c1386c8b8bff.js:6:51126)
	h (vendor.7ae272c2c1386c8b8bff.js:6:52095)
	u (vendor.7ae272c2c1386c8b8bff.js:6:51241)
	(anonymous function) (vendor.7ae272c2c1386c8b8bff.js:6:55872)
	_update (vendor.7ae272c2c1386c8b8bff.js:6:44241)
	r (vendor.7ae272c2c1386c8b8bff.js:6:10963)
	get (vendor.7ae272c2c1386c8b8bff.js:6:40483)
	run (vendor.7ae272c2c1386c8b8bff.js:6:41208)
	It (vendor.7ae272c2c1386c8b8bff.js:6:12423)
	(anonymous function) (vendor.7ae272c2c1386c8b8bff.js:6:6813)
	it (vendor.7ae272c2c1386c8b8bff.js:6:6638)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (74a83f0d-4ed3-4ef0-9cd8-0a6d0422225b, line 0)
[Error] Unhandled Promise Rejection: Error: Request failed with status code 404
	(anonymous function) (vendor.7ae272c2c1386c8b8bff.js:6:111585)
	promiseReactionJob

It's possible that this issue is related to the problem preventing users from leaving Group Plans: https://github.com/HabitRPG/habitica/issues/9287

**Comment by TheHollidayInn** [comment]
I think this has been fixed in my other PR. I can' replicate on the latest develop.

**Comment by librarianmage** [comment]
@TheHollidayInn Has this been fixed?

**Comment by TheHollidayInn** [comment]
I'm pretty sure. Closing until we get a new report.
