### ISSUE TITLE
Incorrect mana reported

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9446]
We've received the following bug report:

"Reported this previously but was told it was probably a sync issue, so I tested it on my dailies (which are easier to keep track of than my many habits which can have more than one click a day. Refreshed twice (waiting for everything to fully load each time) before ticking off dailies. Total mana at the start (having refreshed twice to be sure) was 331. I checked off 17 dailies and my mana read as 427. Hit refresh and my mana level dropped to 417. Refreshed again and it stayed at that lower level. I still have 17 dailies checked off. Have now done the rough math with a calculator and 417 is probably the right amount as all daily tasks are easy & I'm on buffed INT of 234. So, the issue possibly seems to be with it initially showing me as having accrued more mana than I actually have, and then correcting it on refresh. I'm on Windows 10 and using the website in Chrome. I know I saw a previous mention to someone's task history causing issues. I've been a subscriber for a while now, so my history is probably pretty lengthy."

**Comment by intirb** [comment]
FWIW, I have noticed a similar issue with gold, but the issue seems to go away if you allow the webpage to fully load in between each click (basically, don't click the dailies off too fast).  If you click too fast, it seems to me that Habitica sometimes reverses the rewards for a particular daily but fails to uncheck the daily.

**Comment by Alys** [comment]
I'm going to close this because it sounds like a sync error and we haven't seen other similar reports that can't be ascribed to sync errors. Also we've made changes to improve the task history situation, which should help.
