### ISSUE TITLE
Checklist Sorting Issue - Wrong Checklist Deleted

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9447]
At least on Firefox, there is a checklist sorting bug that occurs when you move a checklist item up, and then, without saving, delete an item that used to be above it but is now below it. We've had a report that this causes 

Here is how to replicate:
Add items A, B, C, D, E to checklist (in that order).
Move item E to the second slot, so that you have the sequence AEBCD.
Delete item C
You should then have AEBD, but instead C remains and B has been deleted. (We also received a report that this sometimes caused E to jump back down to the bottom, so that you get ABDE.)

**Comment by TheHollidayInn** [comment]
This has been fixed with the addition of Vue Draggable :D
