### ISSUE TITLE
Include number in a particular string for translation

### ISSUE THREAD

**Issue by apiekarska** [HabitRPG/habitica#9451]
### General Info
  * Type: Translations
  * Language: Polish (probably other too)

### Description
There is a string (groups.json/charactersRemaining) saying "characters remaining" and on the site it displays as e.g. "250 characters remaining". The best translation in Polish would be "pozostało 250 znaków" (literally "remaining 250 characters") which needs the number to be included in the string. Can we have the "<%= number %>" placeholder in that string?
For reference see: https://www.transifex.com/habitrpg/habitrpg/translate/#pl/groupsjson/120309129

**Comment by AlyxMoon** [comment]
This would be my first attempt at helping with the project so I need to familiarize myself with the code, but I'm happy to give this a shot!

**Comment by lemoness** [comment]
@AlyxMoon Thank you so much! Let us know if you have any questions.

I've adjusted the labels on this ticket.
