### ISSUE TITLE
Group plan tasks display incorrectly on small views

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9453]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: N/A
  * Browser: Chrome and Safari
  * OS: Windows 10 and Mac somethingsomething

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When a user has a Group Plan task claimed, it shows up with a small additional bar noting how many group members have the task assigned and the text "Remove Claim" for giving up the task. If the screen size is such that the task column narrows to the point where these two pieces of text collide, the "Remove Claim" link falls outside of the div:

![image](https://user-images.githubusercontent.com/4501321/32619973-f203ec6e-c541-11e7-8f74-114ca6d8c47b.png)

![image](https://user-images.githubusercontent.com/4501321/32619986-fe75c076-c541-11e7-8997-3bbb52a92d0d.png)

It should simply create a new line within the gray ribbon instead of spilling into other sections of the task column.

**Comment by TheHollidayInn** [comment]
I believe this was fixed by our task and mobile style updates. 

<img width="244" alt="screen shot 2018-01-15 at 11 43 34 am" src="https://user-images.githubusercontent.com/1253400/34955285-5b60d132-f9e9-11e7-966c-672089caa536.png">

**Comment by SabreCat** [comment]
Ah yeah, this was addressed in some fixes I did a while ago. Funny of me to have authored the ticket, then worked on the fix, and not linked the two XD
