### ISSUE TITLE
Updates to the Quest Section on the Group Detail Page

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9455]
We have some new upcoming style updates to the Quest page to address some confusion about whether or not people are participating in a Quest and to make the Quest text more prominent. I've attached the screenshots to this ticket, but whoever will be tackling this ticket will need to be added to our Zeplin by @Tressley so that they can get all the details about spacing etc. For that reason, if you're interested in helping out with this, be sure to let us know which email we should invite!

Here are the screenshots for the various states.

<img width="363" alt="screen shot 2017-11-09 at 2 17 32 pm" src="https://user-images.githubusercontent.com/3494081/32632516-cc5a3d62-c558-11e7-925c-74c0648daec2.png">

<img width="359" alt="screen shot 2017-11-09 at 2 18 16 pm" src="https://user-images.githubusercontent.com/3494081/32632555-ed657620-c558-11e7-8967-b22a11daacaf.png">

<img width="482" alt="screen shot 2017-11-09 at 2 19 28 pm" src="https://user-images.githubusercontent.com/3494081/32632608-1abd04da-c559-11e7-8824-dfb2185c846e.png">

<img width="475" alt="screen shot 2017-11-09 at 2 20 56 pm" src="https://user-images.githubusercontent.com/3494081/32632655-453db11e-c559-11e7-8f8e-ab2c6353fde9.png">

**Comment by librarianmage** [comment]
When a user is in a quest, should the "Leave Party" button be greyed out? Then it's obvious that they need to leave the quest first.

**Comment by lemoness** [comment]
That's a question for @Tressley!

**Comment by TheHollidayInn** [comment]
I think we need member declined with quest not started. I believe it would probably just be like "Quest - Member Invite pending" except it doesn't have the accept/reject and it is with lower opacity.

**Comment by Alys** [comment]
@TheHollidayInn is working on this.

![img_20171205_164515839](https://user-images.githubusercontent.com/1495809/33632753-a69105a0-d9dc-11e7-81b9-59795103aa8c.jpg)

**Comment by Tressley** [comment]
Pulling the help wanted tag off of this as I intend to refresh these designs before we handle them internally.

**Comment by Alys** [comment]
I've added the "status: on hold - needs design" label so that this issue has a status but if that's bad, tell me!

**Comment by CuriousMagpie** [comment]
Closing per @Tressley's comment that @negue fixed this a while back!

#12793
