### ISSUE TITLE
Quest Completionist achievement should not require quests to be completed in order

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9461]
As reported by Tex Geoffiamson in the Report a Bug guild and as confirmed by Lemoness, there is a bug with how you achieve the "Quest Completionist" achievement ("Completed all sixteen quests in the Masterclasser Quest Series and solved the mystery of the Lost Masterclasser!").

With our current code the achievement is only assessed when Masterclasser Part 4 is assessed: https://github.com/HabitRPG/habitica/blob/0e2b80ef2edec85b978ecac85f18aa41a97ce3bc/website/server/models/group.js#L776-L801

The correct behaviour to get the achievement is that you must complete all 16 quests, BUT you should be able to do them in any order. 

Steps to Reproduce:
   - Party member A completes "Stoïkalm Calamity, Part 1: Earthen Enemies"
   - Party members A & B complete 14 other Masterclasses prerequisite quests other then "Sto?kalm Calamity, Part 1: Earthen Enemies" and "The Mystery of the Masterclassers, Part 4: The Lost Masterclasser"
   - Party members A & B complete "The Mystery of the Masterclassers, Part 4: The Lost Masterclasser"
   - Party member B completes "Stoïkalm Calamity, Part 1: Earthen Enemies"

Current Behavior:
   - ONLY Party members A has "Quest Completionist: Masterclasser Series"

Expected Behavior:
   - Party members A & B has "Quest Completionist: Masterclasser Series"

For anyone who works on this, you can set up appropriate test user accounts without completing all the quests manually by setting the data below in each account in your local install's database. Leave out one of these achievements to make a test account that hasn't yet done all the quests before "The Mystery of the Masterclassers, Part 4".
```
"achievements.quests": {
	"dilatoryDistress1": 1,
	"dilatoryDistress2": 1,
	"dilatoryDistress3": 1,
	"mayhemMistiflying1": 1,
	"mayhemMistiflying2": 1,
	"mayhemMistiflying3": 1,
	"stoikalmCalamity1": 1,
	"stoikalmCalamity2": 1,
	"stoikalmCalamity3": 1,
	"taskwoodsTerror1": 1,
	"taskwoodsTerror2": 1,
	"taskwoodsTerror3": 1,
	"lostMasterclasser1": 1,
	"lostMasterclasser2": 1,
	"lostMasterclasser3": 1,
},
```

## What to do if this bug happens to you

**Anyone who has completed all 16 quests and doesn't have the  "Quest Completionist" achievement can post to the Report a Bug guild to have the achievement given to them.** Please do NOT post to this issue to request that. It's easier for us and faster for you if you post to the Report a Bug guild.

**Comment by Alys** [comment]
Labels updated. I've marked this as important priority because it's going to affect more and more people in the near future as they complete old quests to get the achievement, and the sooner this is fixed, the fewer manual fixes we'll have to do when they report the bug.

After the fix goes live, admins will have to run a migration to ensure that all players who've earned the achievement have been given it. The contributor who works on this issue does not have to worry about that at all, but it would be helpful to us if you could remind us of it when you submit your PR. :)

**Comment by librarianmage** [comment]
So instead, it should check when any of the quests are completed? Would it make sense to add a "series" key to the quest data?

**Comment by AlyxMoon** [comment]
Since nobody has commented it doesn't seem like anyone has grabbed this to work on yet. I'd be happy to try and get this fixed.

**Comment by Alys** [comment]
Oh darn, I meant to reply! Yes, MathWhiz is correct, it should check when
any of the quests have been completed. I like MathWhiz's idea of a `series`
key so that the quest IDs don't need to be hardcoded.

MathWhiz did you want to work on it since you were looking into it already
or are you ok for Allister to take it on?

**Comment by librarianmage** [comment]
@Alys I am fine with @AlyxMoon taking over. I just like to provide some thoughts.

**Comment by Alys** [comment]
@AlyxMoon It's all yours, thank you! Comment here if you have questions.

**Comment by AlyxMoon** [comment]
@Alys While I thought I had the changes working on my system, I can't get the tests passing in Travis CI (but can on my system) and don't understand the testing well enough to figure things out. I figure it best to assume the problem is with me, not the tests.

Rather than continue making a mess of things with my PR's, I think it best if I give somebody else a chance to work on it instead.

**Comment by librarianmage** [comment]
@AlyxMoon Currently the tests have been very iffy, so I think that you could still push your PR and have someone else check.

**Comment by Alys** [comment]
@AlyxMoon You're doing fine with this! I'm commenting more in the PR since that's where the new test code is defined but as a general note, @MathWhiz is correct that the tests can be iffy. It's not uncommon for them to time out or have other problems that aren't connected to the changes. Admins can restart the tests when they fail for unexpected reasons.

**Comment by librarianmage** [comment]
@AlyxMoon How are you doing on this?

**Comment by lemoness** [comment]
I'm adjusting the labels on this ticket to show that it is now ready to claim!

**Comment by Hus274** [comment]
I can look into this.

**Comment by Alys** [comment]
@Hus274 Thanks! Labels updated.

**Comment by Alys** [comment]
As a note to admins: When the fix for this goes live to production (not just staging), we should search the users to find all those who completed all mmasterclasses quests and give the achievement to any that don't have it yet. I've marked this "notify helpers" to remind me to do something about it after it's closed.

**Comment by SabreCat** [comment]
Something is still going on with this. We still get a fair number of reports of the issue in Report a Bug Guild. Maybe it's just parallel update issues like with quest invites not getting cleared correctly, though?

**Comment by Alys** [comment]
Yeah, i suspect it's from a different cause now. It's logged at https://github.com/HabitRPG/habitica/issues/10398
