### ISSUE TITLE
Column titles "nl.app.*"

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#947]
Today I noticed the titles of the 4 columns were changed. So, instead of "Habits", it now says "nl.app.habits", and it's the same for the other columns (nl.app.dailies, nl.app.todos, nl.app.rewards). I've encountered this only on Chrome on the beta channel, not on Firefox or the normal site. There are no errors in the console.

**Comment by lefnire** [comment]
We're in the midst of translations, that bit means the key hasn't been
provided for yet. @slappybag will rescue us!

**Comment by switz** [comment]
I'll send a pull request to `derby-i18n` to just show "dailies" instead of "nl.app.dailies".

**Comment by lefnire** [comment]
there a way to make it fall back on "en" for keys it can't find in the
current language?

**Comment by switz** [comment]
Yeah, it should. Not sure why it's not. I'll debug a bit.

**Comment by switz** [comment]
Hmm, I set my locale to Netherlands and language to Dutch and it's falling back to English properly.

Tyler, can you merge the nl translations into master? Or do you want me to?

**Comment by lefnire** [comment]
I shall leave this to you kind sir, as you're closer to the situation

**Comment by StanLindsey** [comment]
the nl folder should have an english json file in there until a translator comes in to update it? Meaning the keys are filled but are currently translated to english?

**Comment by switz** [comment]
This is happening because the keys don't exist for those words on the develop branch. It's only happening on beta.habit. This should be sorted out shortly anyway.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by paglias** [comment]
Translations are still not ported
