### ISSUE TITLE
Possible Tasks Page Style Bugs

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9471]
We've received this report but have been unable to replicate it. However, it may be happening on a small screen. "The numbers of my stats are partially obscured by members of my party and i am unable to see the entirety of the drop down menu. my view is cut off under the entry for "stats" when i mouse over the portion of the menu that allows me to change my avatar background or check my messages."

**Comment by TheHollidayInn** [comment]
Closing issue because it is vague and older.
