### ISSUE TITLE
Sorting stable by name,causes to list all animals

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#9477]
Using the `A-Z` sort just lets all animals to be listed, which breaks the `show more / less` workflow

**Comment by lemoness** [comment]
@Tressley How would you like to handle this?

**Comment by beffymaroo** [comment]
@Tressley Can you update about what might be needed here? Thanks!

**Comment by Tressley** [comment]
If A-Z is selected, we can hide the Show More/Less button since it's listing all options. If that is not the intended behavior, then the bug is the rows not collapsing as they should.

**Comment by HerrMoriden** [comment]
is this still an issue ? would like to work on this

**Comment by Tressley** [comment]
@HerrMoriden -- Yes, this is still an issue. I've marked it as in progress for you. Feel free to comment here if you have any questions.

**Comment by shanaqui** [comment]
@HerrMoriden Hi! Same on this issue -- can you let us know you're still working on it? If not/if we don't hear back, I'll mark it as Help Wanted again!

**Comment by shanaqui** [comment]
Marked as Help Wanted again since we received no reply.

**Comment by adamfitzgibbon** [comment]
This looks like it was already fixed, at least on web. Can anyone confirm?

**Comment by Tressley** [comment]
@adamfitzgibbon -- This does not look to have been fixed. The behavior of the A-Z sort should mirror the experience of the other options, i.e. It should also use the expand and collapse functionality.

If you're interested in taking this on, just drop a comment and I'll assign it your way. 👍🏻

**Comment by adamfitzgibbon** [comment]
@Tressley Oh ok, from the above I thought the ideal functionality was to hide the "See more" without it being collapsed. If we want it to work with the "See more" I can take that on!

**Comment by adamfitzgibbon** [comment]
Fixed in #14304
