### ISSUE TITLE
Profile Modal has overlapped styling issues

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9480]
We've received several reports that in the Profile modal, there is not enough space between the right edge of the avatar image and the left edge of the name/level/health/experience/mana column, which causes the image to up partly covered by the data column. We've received one report that this seems to happen only in Firefox, not Chrome and doesn't seem to be affected by browser window size, but another report that it only happened on a very small screen.

**Comment by TheHollidayInn** [comment]
I can see this happening on a small screen, but that would be smaller than my 13 inch mac, which I believe is tablet size? Maybe @Tressley can give us some thoughts or I can just let the avatar stack on top of the health at the tablet break point.

**Comment by lemoness** [comment]
@TheHollidayInn @Tressley Has this been fixed?

**Comment by Tressley** [comment]
@lemoness -- I don't think that this is still an issue. I believe @TheHollidayInn fixed this issue during our Retreat?

**Comment by TheHollidayInn** [comment]
I think I may have :P I haven't seen any reports of this issue on the email or bug guild.

**Comment by lemoness** [comment]
Closing for now - we can reopen if this happens again!
