### ISSUE TITLE
Unallocated Attribute Point notification causes page to disappear

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9482]
If you click "You have 1 unallocated Attribute Point(s)" under your notifications and exit out of the modal, the body of the page disappears so that all you can see are the toolbar, header, and footer. This is the case on Firefox at the least.

**Comment by LunarGem** [comment]
I think this is because the link to open the profile doesn't have a fall back page. When the modal is closed, there's nothing behind it, so nothing is shown. Do we want it to fall back to the task page or the last viewed page under this circumstance?

**Comment by mandyzhou** [comment]
I don't know if a fall back page is what is needed, because the benefit of a modal is that it doesn't interrupt your workflow, and exiting out of it should get you back to exactly where you were previously.
