### ISSUE TITLE
Hover Description for Items sticks to corner

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9483]
On the Items page, sometimes the hover description for the Items clips to the top left corner of the page and covers the avatar. This has been reported to happen on Chrome, and may possibly happen on other browsers as well. 
<img width="618" alt="screen shot 2017-11-14 at 6 43 25 pm" src="https://user-images.githubusercontent.com/3494081/32816091-f611fc8c-c96b-11e7-9e88-c662565e01e7.png">

**Comment by paglias** [comment]
@lemoness is this happening on staging too? Might have been fixed by the upgrade there

**Comment by lemoness** [comment]
Has not been tested on staging.

**Comment by joedragons** [comment]
I suspect this is a dup of this: https://github.com/HabitRPG/habitica/issues/9456

**Comment by paglias** [comment]
I'm closing this but if you notice it again leave a comment here!
