### ISSUE TITLE
QR code should be removed and URL redirected to "static" member profile URL

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9488]
This issue should be taken off hold when https://github.com/HabitRPG/habitica/issues/9487 has been resolved.

QR Codes are used for `GET /qr-code/user/:memberId` -- I.e., they are used for URLs such as https://habitica.com/qr-code/user/d904bd62-da08-416b-a816-ba797c9ee265

Those URLs should redirect to the "static" member profile page which will be implemented in https://github.com/HabitRPG/habitica/issues/9487

There's already some support in the code base for the qr-code URL (below). The existing tests should be enabled by removing the `x` from `xdescribe` and any other necessary tests and code should be added.
```
$ git grep qr-code
test/api/v3/integration/qrcodes/GET-qrcodes_user.test.js:9:xdescribe('GET /qr-code/user/:memberId', () => {
test/api/v3/integration/qrcodes/GET-qrcodes_user.test.js:17:    await expect(user.get('/qr-code/user/invalidUUID')).to.eventually.be.rejected.and.eql({
test/api/v3/integration/qrcodes/GET-qrcodes_user.test.js:25:    let url = `http://localhost:${API_TEST_SERVER_PORT}/qr-code/user/${user._id}`;
test/helpers/api-integration/requester.js:36:      if (route.indexOf('/email') === 0 || route.indexOf('/export') === 0 || route.indexOf('/paypal') === 0 || route.indexOf('/amazon') === 0 || route.indexOf('/stripe') === 0 || route.indexOf('/qr-code') === 0) {
website/server/controllers/top-level/qrcodes.js:5:  url: '/qr-code/user/:memberid',
website/server/middlewares/notFound.js:16:  '/qr-code',
```

EDIT 2020-03-14: The desired fix is to remove all program code that references QR codes, including text strings from the English (en) locales files, if any. See comments for more details.

**Comment by Alys** [comment]
Labels updated.

**Comment by Alys** [comment]
Are QR codes still meant to be a thing?

There's still a little support in the code for them, although not in any way that would allow them to work. 
```
$ git grep qr-code
test/api/v3/integration/qrcodes/GET-qrcodes_user.test.js:9:xdescribe('GET /qr-code/user/:memberId', () => {
test/api/v3/integration/qrcodes/GET-qrcodes_user.test.js:17:    await expect(user.get('/qr-code/user/invalidUUID')).to.eventually.be.rejected.and.eql({
test/api/v3/integration/qrcodes/GET-qrcodes_user.test.js:25:    const url = `http://localhost:${API_TEST_SERVER_PORT}/qr-code/user/${user._id}`;
test/helpers/api-integration/requester.js:43:      || route.indexOf('/qr-code') === 0
website/server/controllers/top-level/qrcodes.js:5:  url: '/qr-code/user/:memberid',
website/server/middlewares/notFound.js:16:  '/qr-code',

$ git grep qrcode
$
[no results for "qrcode"]
```

I'm guessing that code should be removed.

I'm changing this from on hold (since the blocker issue has been closed) to suggestion-discussion.

**Comment by veeeeeee** [comment]
As we have removed them from the mobile apps for a while, I think we should go ahead and remove the code.

**Comment by sau226** [comment]
Have 2 questions regarding this issue:
* Is this issue still open, or did the issue status get out of sync with the actual issue progression?
* If this issue is still actually open, are you wanting the /qr-code/ route (e.g. from the sample in the first post) to no longer exist along with the removal of all other QR code related content, or instead if you just want the QR code content sans redirect to get removed?

**Comment by CuriousMagpie** [comment]
@sau226 This issue is still open--we would like to have all  the /qr-code/ route removed along with all other QR-code related content. Basically a clean-up issue--are you interested in taking it on?

**Comment by sau226** [comment]
@CuriousMagpie Sure, I'd be happy to take a peek and remove all of the QR code related things if you don't need any redirects/other work on top of that for this issue. If so, please flag me as having taken this issue.

**Comment by CuriousMagpie** [comment]
@sau226 Awesome! Thanks a bunch, I know it's not real exciting coding, but it is really helpful for us.

**Comment by sau226** [comment]
@CuriousMagpie Thanks for assigning me this issue. 

I've had a go at making a PR but it looks like a GitHub actions workflow requires a maintainer approval before it runs - is there any way you could go ahead and have someone approve the workflows to run, pending your complete review process?

**Comment by Alys** [comment]
@sau226 It shouldn't be necessary to run an actions workflow for you to make a PR.  If you haven't already seen our wiki docs about coding for Habitica, see [Setting up Habitica Locally](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally) (the "Fork and Clone Habitica" section will show you a good way for setting up your local repo), and [Using Your Local Install to Modify Habitica%27s Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) (the "Submitting your Change for Review in a Pull Request" section may help you create a PR but the rest of it is likely to be of interest too).

If that doesn't help, can you give us more detail about what you're wanting to use a GitHub actions workflow for?

**Comment by sau226** [comment]
@Alys Thanks for getting back to me.

Your repo has a configuration that automatically runs various CI tests via GitHub actions when a PR is opened/pushed to (https://github.com/HabitRPG/habitica/blob/develop/.github/workflows/test.yml). This code was added by "paglias" to replace Travis CI for running tests a while ago.

Because it is obviously wise to run CI tests before reviewing/deploying a change, and I am a first time contributor, someone with write access to the repo would have to click a button to allow the tests to run via GitHub actions and for their status (pass/fail) to reflect on the PR. My request was to have someone go and give that approval pending a PR review.

Hopefully that helps.

**Comment by Alys** [comment]
@sau226 Ah I see, you're referring to this notice in https://github.com/HabitRPG/habitica/issues/9488: 

"1 workflow awaiting approval
First-time contributors need a maintainer to approve running workflows."

I've clicked the approve button.
