### ISSUE TITLE
Inventory/Stable Tabs not visible

### ISSUE THREAD

**Issue by AvalonAwoken** [HabitRPG/habitica#949]
My friend (Chrome) was unable to view the Inventory and Stable tabs from the party and profile screens.  I (Safari) tried to reproduce the error, and while entering and exiting different tabs, saw them disappear.  My problem resolved itself upon refresh, but his persists.

Thanks.

**Comment by lefnire** [comment]
what we've found:

@switz:

> I loaded up habit today to find a ton of missing assets. I couldn't see my character (and neither could anyone else).
> 
> $ sudo tail -f error.log
> 2013/05/13 19:55:06 [crit] 808#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 809#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 809#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 808#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 808#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 808#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 809#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 809#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 808#0: accept4() failed (24: Too many open files)
> 2013/05/13 19:55:06 [crit] 808#0: accept4() failed (24: Too many open files)
> 
> Looks like we need to set a higher ulimit either in nginx or at the linux level. A reboot solved the issue for now.

I'm going to be jumping into this asap

**Comment by lefnire** [comment]
@AvalonAwoken I fixed the issue caused by my previous comment, which should have solved the issue. re-open if still an issue

**Comment by Evangelineway** [comment]
@lefnire 
Hello, this sounds like a problem I am having. I am using Chrome as well. Should I explain what's happening here or create a new issue?

**Comment by lefnire** [comment]
@Evangelineway what level are you? Inventory (and its subtabs) don't unlock till lvl 4

**Comment by Evangelineway** [comment]
@lefnire 
Oh, my apologies, I am not there yet. I was confused because I stumbled upon the "Show Classes Tour" button under Settings, which took me to those tabs. Thank you!
