### ISSUE TITLE
API route for Key to the Kennels missing checks to see if user is eligible

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9491]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Via cTheDragons in the Report a Bug Guild:

> The API Call https://habitica.com/api/v3/user/release-both does not check if the user has all the pets and mounts for Standard (Gen 1) before awarding Triad Bingo. It also does not charge gems if the uers does not have all the pets and mounts for Standard (Gen 1).

**Comment by librarianmage** [comment]
Relevant code:

https://github.com/HabitRPG/habitica/blob/d4881cb73aecb5c0ab3293321d39625321172f16/website/server/controllers/api-v3/user.js#L1436-L1483

https://github.com/HabitRPG/habitica/blob/d4881cb73aecb5c0ab3293321d39625321172f16/website/common/script/ops/releaseBoth.js#L9-L85
