### ISSUE TITLE
Vivaldi - Stripe modal prevents scroll

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9493]
If you try to purchase gems/subscription via Stripe while using Vivaldi, you can't scroll upwards on the screen once you've chosen and dismissed a payment method. You have to close the screen and re-open it, or refresh.

**Comment by TheHollidayInn** [comment]
This seems to be fixed on Staging.

**Comment by paglias** [comment]
I don't have anything against Vivaldi but I don't think we should focus on fixing issues with a browser that's used by maybe a few thousands people worldwide. Supporting Firefox/Edge/Chrome and Safari covers 99.9% of people and is already difficult

**Comment by Alys** [comment]
I use Vivaldi but do tend to agree with paglias that we can't necessarily make fixes for any glitches it might have (although I've found it to be a reliable browser myself).

Fortunately as TheHollidayInn says, this seems to be fixed. :) I can't replicate it in production.
