### ISSUE TITLE
Can buy locked quests from Rewards column

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9494]
We've received the following report in relation to the new Mystery of the Masterclassers gem-purchasable quest line. "I bought the first quest in the line (but haven't started doing it yet) and pinned the other three to my rewards column for later. I noted that I was not able to buy quests 2-4 in the shop (this is another case where an explanatory "You can't buy this yet" popup upon clicking would be nice rather than just nothing happening). But just for fun, I tried to buy quest 2 from my rewards column and it worked. It wasn't just a sync glitch, either -- I clicked refresh and I'm still down 500 gold and up one Mystery of the Masterclassers Part 2 scroll. Since my party is currently on another quest, I'm not able to check whether I can actually start it, but I was able to get to the point of clicking "invite", and everything seemed to work normally, so it seems that I actually do have the scroll."

**Comment by Alys** [comment]
To any contributor who works on this: The fix required for this is purely client-side. We already have https://github.com/HabitRPG/habitica/issues/8530 logged for changes to the API.

**Comment by TheHollidayInn** [comment]
This was fixed by https://github.com/HabitRPG/habitica/blob/develop/website/client/components/tasks/column.vue#L598
