### ISSUE TITLE
Preview incorrectly shows two-handed weapon AND shield

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9495]
If you try to change your costume while wearing a shield and try to equip a two-handed weapon (or vice-versa), the preview shows your Avatar wearing both. There is no message or other warning that it's a two-handed weapon, but you are not able to equip my Avatar as it appears in the preview. (Note that this is separate from but related to https://github.com/HabitRPG/habitica/issues/8441). The preview should not show both a two-handed weapon and a shield at the same time.

**Comment by matchajune** [comment]
@lemoness @Alys Hello! Permission to take this issue?

**Comment by Alys** [comment]
@matchajune Yes! Thank you! Comment here if you have questions.
