### ISSUE TITLE
large user profile images stretch out of the profile modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9496]
As reported by tr1p (34850a08-5663-4a89-80e5-c7b47d337dcb) in the Report a Bug guild:

"Photos in user modals can grow out of the modal. Some photos are huuuuuge, it looks weird."

Example (using a [Wikipedia commons image](https://en.wikipedia.org/wiki/Sunset#/media/File:Sunset_2007-1.jpg)):

![image](https://user-images.githubusercontent.com/1495809/32863698-13ca32a2-caa8-11e7-84c4-64cb9c3e304a.png)

Labels updated as "on hold - needs design". @Tressley

**Comment by Tressley** [comment]
I don't think this is Needs Design as much as needs max-width/scaling on the image and image container.

**Comment by Alys** [comment]
labels updated
