### ISSUE TITLE
Opt-out of pet hatching pop-up does not work

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9499]
The setting to not show popups when hatching a pet does not work correctly.

**Comment by TheHollidayInn** [comment]
Is this option currently appearing? I'm not seeing it.

**Comment by Alys** [comment]
"Don't show popup when hatching a pet" at User Icon > Settings.

**Comment by TheHollidayInn** [comment]
Thanks :D

**Comment by TheHollidayInn** [comment]
I've fixed this in a separate issue that also included mounts. https://github.com/HabitRPG/habitica/pull/9882
