### ISSUE TITLE
Predicition(Warning Mathematical)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#95]
_by wc8: Vote here [Progress Prediction](https://trello.com/c/hwB9jetA)_
The system should bet against you for a certain number of gold. This ofcourse will come from your previous habit track record. The system will try to predict whether you will do your task,daily, or habit. This is long term and highly mathematical but totally doable.

**Comment by FuelTheJet** [comment]
I would just like to know what exactly are you looking for it to achieve with this?

**Comment by ghost** [comment]
Not sure yet just want to do it

**Comment by FuelTheJet** [comment]
Do you have a practical idea that this could be used for? I would like to help, although I can't really do anything until I have some idea as to what purpose it would serve.

**Comment by hookang** [comment]
Added to Master Feature List #169. Closed for Organization. Still not sure how to use it? Gambling maybe?

**Comment by ghost** [comment]
Yes it is the system gambling against you but this would require machine learning which I am not sure is possible in with Javascript

**Comment by wc8** [comment]
See Trello card: https://trello.com/c/hwB9jetA

**Comment by ghost** [comment]
@wc8 this is a  prediction model not gambling and now I remember the original idea. Predictions for everyone as a whole. The program will learn about you and predict whether you fail or succeed no gambling. It gives a success rate for the week.

**Comment by wc8** [comment]
I will update the card.

**Comment by wc8** [comment]
So #69 would be a computer challenge ("roulette"), and this one is more of a progress predictor, right?
 I'll create separate cards.

**Comment by ghost** [comment]
@wc8 exactly

**Comment by wc8** [comment]
If/when you get a chance to check out the Trello [card:](https://trello.com/c/hwB9jetA), let me know if I captured the idea.

**Comment by ghost** [comment]
@wc8 https://github.com/lefnire/habitrpg/issues/95# was successfully captured, would you like to name https://github.com/lefnire/habitrpg/issues/95#? Name is Progress Predictions.
