### ISSUE TITLE
Put Earnable Quests back in Quest Shop

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9501]
Earnable Quests (Feral Dust Bunnies and Basi-list) need to be put back in the Quest Shop, with an explanation for how you can earn them. (FYI, they were removed in commit 7a6bf8b8702871e13b8572d8f5a2083a760c3d49 because the shop hadn't been set up to display them correctly.) 

----
edit 2020-02-07: Any contributor interested in working on this should read all the comments as some contain important information about how this issue is to be fixed.

**Comment by Alys** [comment]
@Tressley for designs

**Comment by Tressley** [comment]
As a note Feral Bust Bunnies price will go to 1 Gem and Basi-List price will go to 100G since these are our "mini-quests."

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitica-android/issues/1103 describes how this is handled in the Android app

**Comment by Tressley** [comment]
Zeplin artboard for updated item designs: https://zpl.io/VQ7Z8mR

**Comment by Alys** [comment]
@Tressley Is this ready for a contributor to work on it? If so, I'll add the "help wanted" label.

**Comment by Alys** [comment]
Is that Zeplin link pointing to the correct screen? It does show quest scrolls but also other items and doesn't show how the explanations should appear. The first time I used the link, zeplin showed me an error, so maybe its got itself screwed up somewhere. :)

**Comment by Tressley** [comment]
@Alys -- Yes, this is the correct artboard. Is the link working now? If not, here's a screenshot in the meantime. The bottom row contains the examples for earned quests. The other examples are the various states for items in The Market and other shops.

![image](https://user-images.githubusercontent.com/2686586/73939090-b1a74a80-48b6-11ea-840e-4e19a6c6edb6.png)

These designs will be used for when the quests haven't been earned, with the bottom part containing the proper explanation for how you can earn them. Once they've been earned, the quests should be able to be purchased from The Market for the prices outlined above. Feral Dust-Bunnies will cost 1 gem, Basi-List will cost 100 gold.

**Comment by Alys** [comment]
@Tressley Awesome, thanks for all the details! I've updated the top post to tell contributors to be sure to read all comments. Yes, the zeplin link works for me now.

For any contributor working on this:

- The text to display is taken from `unlockCondition.text` in the quest's data as shown in the two snippets below.
- Changes will be needed to that data to adjust the price.
- For the Dust Bunnies quest, the `unlockCondition.condition` value is ` party invite` which isn't an accurate description, but that piece of data might not have any impact on how the quest scroll is handled or displayed so you might not need to change it - if you're getting the correct behaviour on your local install without changing that value, then it's okay to leave it as it is.

https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/common/script/content/quests.js#L1065-L1075

https://github.com/HabitRPG/habitica/blob/257a52cba1712f4fbc5b0265fd03dbd4fe1a1afe/website/common/script/content/quests.js#L2236-L2246

**Comment by Tressley** [comment]
@Alys — Discussed this with the team today and we’re just going to have Habitica staff tackle it!

**Comment by Alys** [comment]
Oh, okay. I've added the in progress label.

**Comment by SabreCat** [comment]
We're going to tackle the style updates separately--the main issue fix is done and on its way live.

**Comment by SabreCat** [comment]
Per some discussion today, we are missing one piece that'd count for full implementation of this--some text on the Basi-List item that describes how to earn it without spending Gold. Re-opening until we have that in.

**Comment by Tressley** [comment]
Zeplin designs are here for new item layout: https://zpl.io/VQ7Z8mR

**Comment by paglias** [comment]
This is now live

**Comment by Alys** [comment]
Just to check... Is it correct that the shop doesn't use the small bottom banner like in the two mockups below? I.e., it was decided that that would not be done?

![image](https://user-images.githubusercontent.com/1495809/82748047-3379a000-9de2-11ea-9947-108e17c280ee.png)

![image](https://user-images.githubusercontent.com/1495809/82748054-47250680-9de2-11ea-955f-7d1bd5dcb97c.png)

Here's what it's like in production now:

![image](https://user-images.githubusercontent.com/1495809/82748088-8e12fc00-9de2-11ea-8526-cc17ce4ce6a8.png)

**Comment by Tressley** [comment]
@Alys -- The goal of the first pass was to re-add the quests that could be earned. When we plan for a second pass we'll include the introduction of unlock text in the banner, rather than the price.
