### ISSUE TITLE
Silver tier Guilds use wrong color

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9511]
Silver tier Guilds erroneously use the bronze color for their number in the crest. They should use their silver color.

**Comment by librarianmage** [comment]
Offending code:

https://github.com/HabitRPG/habitica/blob/03a09b75465e644ceb81401d1a46127f118b5bce/website/client/components/groups/publicGuildItem.vue#L6-L11

**Comment by kartikadur** [comment]
I'd like to claim this if no one has opted to work on it.

**Comment by Alys** [comment]
@kartikadur Thank you for offering but it's in progress. We should have changed the labels. Sorry about that!

**Comment by kartikadur** [comment]
@Alys thanks for the update
