### ISSUE TITLE
Incorrect badge for Guilds with 100 members

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9512]
Guilds with exactly 100 members seem to have a misaligned number in the Guilds list and are missing their badge, both there and in the Guild's "member list" box inside the Guild itself.

**Comment by librarianmage** [comment]
Offending code:

https://github.com/HabitRPG/habitica/blob/03a09b75465e644ceb81401d1a46127f118b5bce/website/client/components/groups/publicGuildItem.vue#L6-L11
