### ISSUE TITLE
Rewards should be allowed to have decimal values

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9513]
It should be possible to set a Reward's value to have decimal points. E.g., it's allowed to create a Reward that costs 1.75 gold.

However when you try to do that on the new website, it doesn't allow decimal points and tells you that you have to choose between nearest values of 1 and 2. That restriction should be removed.

**Comment by Alys** [comment]
labels updated

**Comment by Tressley** [comment]
Just noting that this should not go past two decimal places.
