### ISSUE TITLE
deleted Group Plan tasks don't disappear until after you reload the Group Plans page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9515]
As reported by liandri ( fcedf401-f9d3-4598-9bc0-58302221992b ) in the Report a Bug guild:

Group bug: habit doesn't go away after deleted

Steps to reproduce:
- 1 habit, unassigned
- Open, assign to self to avoid "Task not found" error
- Click delete 

Expected behavior: dialog closes, habit disappears from list 

Actual behavior: dialog closes, habit remains, still shows unassigned, no visible errors, no JS errors, habit is gone when I refresh

**Comment by Alys** [comment]
Labels updated.

I've copied the comment about the "task not found" error to https://github.com/HabitRPG/habitica/issues/9425

**Comment by TheHollidayInn** [comment]
This is a duplicate: https://github.com/HabitRPG/habitica/issues/9426
