### ISSUE TITLE
Missing pet and hatching potion

### ISSUE THREAD

**Issue by marlow-fawn** [HabitRPG/habitica#952]
A couple of days ago, I had a shade potion that I used on my dragon egg, and it worked like any normal pet would. However, the next when I went into my stable, the shadow-y dragon was missing, and instead I had the dragon egg back in my inventory. Today, I got a prompt for a shade hatching potion, but it never actually went to my inventory. Not sure what's going on, but hopefully you guys can look into it.

**Comment by lefnire** [comment]
will look into

**Comment by wc8** [comment]
http://community.habitrpg.com/content/pets I'll point the users here, but thought I'd add the link for reference.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
