### ISSUE TITLE
Boss Tooltip should show HP

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9522]
The tooltip when you hover over a Boss quest should show the Boss' total HP both on the Quest page and in the Rewards column. See the design below for an example of what it should look like.
<img width="341" alt="screen shot 2017-11-16 at 4 49 34 pm" src="https://user-images.githubusercontent.com/3494081/32923811-709b1e2e-caee-11e7-80ca-ac13b20b59a9.png">

**Comment by negue** [comment]
Currently the Boss Strength is shown as Difficulty. The only damage I could try to calculate would be http://habitica.wikia.com/wiki/Boss#Boss_Strength but there I'd need a  `dmg` variable.

@paglias @TheHollidayInn any idea / hint how get the boss damage ? maybe I've overseen it somewhere :/

**Comment by Alys** [comment]
I believe the requirement for this issue is to display the boss's Strength, as it used to be displayed on the original website.

The damage variable that that wiki page talks about is specific to each player's actions each day so it isn't needed for displaying generic information about the boss.

**Comment by lemoness** [comment]
Yes, we need to display the HP, not using the wiki page. See
Tressley's design.

**Comment by lemoness** [comment]
I've updated the title and OP of this ticket to make the requirements more clear.
