### ISSUE TITLE
Uncaught TypeError when opening news in android app

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica#9526]
When opening the static news page in the android app, we get an error which prevents the news from then showing up:

```
Uncaught TypeError: Cannot read property 'getItem' of null -- From line 1 of https://habitica.com/static/js/app.62240e39ec9dda0b234b.js
[INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'getItem' of null", source: https://habitica.com/static/js/app.62240e39ec9dda0b234b.js (1)
```

**Comment by paglias** [comment]
I thought the error was caused by the user not being logged in but I just tried to logout and open the new stuff static page and it renders correctly
