### ISSUE TITLE
newly sent messages can't be deleted from "Messages" inbox

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9530]
In the private messages inbox,  if you send a message and then immediately delete your copy of the message, the message is not actually deleted. It disappears from the right-hand side of the screen, but is still visible in the left-hand side, and then if you reload, you see that the message reappears on the right-hand side off the screen.

By examining my test account in Habitica's database, I confirmed that the message really was not deleted. (I.e., the fact that you can still see it is not just from a display caching issue.)

After you've reloaded the website, you can then delete the message successfully.

**Comment by lemoness** [comment]
Confirmed that this is still occurring.
