### ISSUE TITLE
pet hatching modal has too much whitespace

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9532]
From Praxis Arete ( 0ce6d43b-efa2-45a3-acaa-59daad7d658d ) in the Report a Bug guild:

"... after yesterday's changes: When you click the "paw print" icon in Stable to hatch a new pet, the confirmation popup for "hatch/cancel" is now off-size - too large, as though a big white margin has been added to the right hand side, with the normal content of the pop-up aligned at the left. (I think this is an artifact of the margins they added yesterday to the main pages, in at attempt to fix the header/alignment issues.)"

Confirmed in my own account (Vivaldi on Linux): 
![image](https://user-images.githubusercontent.com/1495809/32974948-51b0ba30-cc4e-11e7-86d5-5219b83beb72.png)

**Comment by thefridge111** [comment]
I can take a look at this if noone else is

**Comment by thefridge111** [comment]
is this related to #9559 ?

**Comment by Alys** [comment]
@thefridge111 Yes it might be the same bug. I'm marking them both as in progress. Thanks for taking this on! Comment here if you have questions.

**Comment by ghost** [comment]
I think I solved this. This code comes from the Hatch Pet modal on the Stable page. I don't know how to describe the pathway. I hope this is enough information. I can try to describe in more detail if someone tells me what information I need to provide.  

html body.modal-open div#app div.container-fluid div.sticky div.row div.col-12 div.row.stable div div#hatching-modal___BV_modal_outer_ div#hatching-modal.modal.fade.show.d-block div.modal-dialog.modal-md  
.modal-dialog {  
	max-width: 500px; **This should be 330 px**  
	margin: 30px auto;  
}

html body.modal-open div#app div.container-fluid div.sticky div.row div.col-12 div.row.stable div div#hatching-modal___BV_modal_outer_ div#hatching-modal.modal.fade.show.d-block div.modal-dialog.modal-md div.modal-content div#hatching-modal___BV_modal_body_.modal-body div.content
#hatching-modal .content {  
	text-align: center;  
	/* margin: 9px; */ **This should not be here**  
	/* width: 300px; */ **Nor should this**  
}

**Comment by thefridge111** [comment]
if you think you've got a solution feel free to take a crack at it @lmking I've been a little busier than I expected to be and havent had a chance to really dig into this yet

**Comment by ghost** [comment]
I should have noted that I am not a coder. I can identify problems and that's about it. As to making permanent changes to the code, I have absolutely no idea how to do that.

**Comment by thefridge111** [comment]
I finally have the time to take a look at this.. I'm actively working on it now, just trying to figure out how to get the pet hatching modal to be able to launch

**Comment by thefridge111** [comment]
@Alys are there some resources available for what documents I should be inserting in order to create pets that will hatch to test these modals? I cant seem to find any kind of 'schema' documentation in the wiki.

**Comment by Alys** [comment]
@thefridge111 You can use the debug menu in the footer of the website on your local install to give you test user gems and then you can buy eggs and hatching potions from the market.

**Comment by thefridge111** [comment]
@Alys For whatever reason the debug menu lets me do everything but modify the inventory, any idea why?

**Comment by Alys** [comment]
It's probably broken in the new website. If you'd like to log an issue for it, please do!

**Comment by thefridge111** [comment]
Hey @Alys while I had hoped to have time to get to this my life has become a little too hectic right now. I don't want to stop someone else from tackling this if they get the time or inclination. Feel free to change the labels and take me off this ticket.

**Comment by Alys** [comment]
@thefridge111 Thanks for letting us know!

**Comment by Alys** [comment]
This isn't happening for me on Firefox so I'm closing it. I haven't bothered testing on other browser since it's just a minor display issue but if anyone else still sees it, post here with the browser you're using and we'll reopen it.
