### ISSUE TITLE
invisible member names in party member modal when giving a card

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9534]
When you buy a card (birthday card, congratulations card, etc) to give it to a party member, the modal that shows the party members does not show their names:

![image](https://user-images.githubusercontent.com/1495809/32975242-1707bc78-cc51-11e7-8a71-e420bb680605.png)

**Comment by lemoness** [comment]
Is it perhaps white font?

**Comment by aalsehly86** [comment]
You're right @lemoness
