### ISSUE TITLE
hatching modal appears when feeding a pet

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9536]
The report below is from thebat137 ( dea8a9e8-c084-438a-9a14-7fe96a73fd0a ) in the Report a Bug guild. It might be just another case of modals reappearing inappropriately but I'm copying it here in case it's a separate problem. For now I'm labelling this as minor priority and needs investigation but we can up it's priority if we see more reports.

"I was feeding one pet when somehow the popup to hatch a different pet appeared, obscuring the pet I was trying to feed. I had a food item selected already and was unable to either put down the food item (which remained "stuck" to my cursor) or dismiss (or even click on) the popup. I managed to resolve the situation by giving the food item to a different pet, and then the popup also vanished. (I assume reloading or clicking away from the page would also have worked.) But it was kind of weird."

**Comment by aalsehly86** [comment]
@Alys this could be related to issue #9393 

Notice this behavior also happens with other modals as well.

![gems](https://user-images.githubusercontent.com/30061021/32986067-c2127050-cc96-11e7-94af-9b0f411a84ca.gif)

![hatch](https://user-images.githubusercontent.com/30061021/32986068-c225a6e8-cc96-11e7-80de-45484c8bbd54.gif)

**Comment by Alys** [comment]
> Notice this behavior also happens with other modals as well.

Yes, that's what I was referring to when I mentioned the other cases of modals reappearing inappropriately. This one seemed a bit different because the other modal couldn't be dismissed but I'm not certain this is a separate problem. It might just have been the changed cursor that prevented this from disappearing. Mostly I logged this in case it was the first report of an ongoing problem.

It's fine to ignore this until/unless we see other reports. If we don't after a while, we can close this.

**Comment by TheHollidayInn** [comment]
Another report

```
UserID: 9ae04082-7868-4042-b073-33b7a32cd573
Hello, every time I hatch a new (Quest-) pet, I get a 3rd, empty popup. The first asks me if I want to hatch the pet, the second shows me the hatched pet, and the third appears after clicking the "Onwards" button: ![empty popup](https://snag.gy/DakLdo.jpg)
```

**Comment by ghost** [comment]
+1, also experiencing this issue.

**Comment by veeeeeee** [comment]
This behavior is no longer occurring.
