### ISSUE TITLE
scroll bar mostly hidden in quest details participants list

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9537]
From Aerilita ( 3b724a41-48d3-4048-ae27-70b258cf5a72 ) in the Report a Bug guild:

"On the website in quest details the list of participants is positioned in such a way that its scrollbar is mostly hidden by the quest description in the middle. (I could scroll it with the mouse wheel though.)"
[to illustrate](https://pasteboard.co/GTWWdtC.gif)

I've confirmed that. In fact it's so well hidden on my browsers I didn't realise there was meant to be a visible scroll bar. :)

**Comment by pcvonz** [comment]
I can help with this!

**Comment by Alys** [comment]
Thanks @pcvonz ! I've marked this as in progress.
