### ISSUE TITLE
Glitchy HP/XP

### ISSUE THREAD

**Issue by katofrafters** [HabitRPG/habitica#954]
Today I pulled the site up on a work computer to check off some dailies and habits.  Noting that my XP was maybe a third full, I logged out.  Upon getting home I discovered that that XP had decreased back to hair of color at the end of the bar and the dailies completely unchecked.  Also I'd lost HP.  

This is the third time this has happened to me.  I've only been on the site for a week.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
