### ISSUE TITLE
ticking a task in Record Yesterday's Activity screen can mark it incomplete

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9541]
Under some circumstances (not yet known as far as I'm aware) it's possible for you to mark your Dailies complete (really complete with no sync errors) but then the next day you see the RYA screen with those Dailies appearing in it as if they weren't completed.

If you then mark the Dailies complete in the RYA screen, it actually UNcompletes them. I.e. the checkbox in RYA acts as a toggle for the actual state of the Dailies, no matter what state is shown in the RYA screen.

Both of those things are bugs but the second one is the worst because you take damage from Dailies that you have marked complete.  It's probably also easier to fix, especially since there could be more than one  cause of the first bug. If we can't easily work out what thing(s) cause the first one, a fix for the second one would be an improvement.

**Comment by TheHollidayInn** [comment]
Are we still getting reports of this? It would be helpful to start collecting examples so we can investigate.

**Comment by Alys** [comment]
This part might still happen, based on reports from users. It's really hard to tell though.
_"... it's possible for you to mark your Dailies complete (really complete with no sync errors) but then the next day you see the RYA screen with those Dailies appearing in it as if they weren't completed..."_

However that's not the main point of this issue, and I can't replicate this issue now by faking it using database update commands while the RYA screen is waiting for my input. I'm closing this. We can reopen it if we see verified reports.
