### ISSUE TITLE
Stable Image Loading Errors

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#9550]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

thebat137 ( dea8a9e8-c084-438a-9a14-7fe96a73fd0a ) 
In the stable, I'm getting weird little black bars showing up transiently. They seem to appear superimposed over or hovering below pet icons, and scrolling, hovering, and clicking around on the page will cause them to jump to a new location or disappear, and new ones to appear. I haven't worked out quite what triggers them. Here is an example:
black bars

https://lh3.googleusercontent.com/EKYnmZoBSeONGuz8n6m4A7Bc-QNj6lDy18PHWXGIwRYepJ8ENWE5ICHedwiUycyfjHWXjNKoPycOnxtKYpjGgJhTdOqo8lx7zI5bBOu6o1nacZ7mOBEhjlCoFYKHarXq-w7_JFs6XT5iCobKbEPv0FQoT1SBK4SHaC9PHob-ik0XHull77Z4YlFXzRZcha3dX1RgQqatr6HTKbCweXqZhjuujUt1OJoCYZMeHSpvuz7UmcamaC5BfKuX_92YcJkgE3ThOnbESuhGClCBL5O4euo_E0SE9qCr1zZdRBD2neJYT_joHdUGnu2EPU950GobTjPeekRQXGbaMa0WX0oqUjpx5kc-2NvToX3d4Lfm9hWo2tfAG722DsAnJcyQggZGlSm9SqkqX6Spj9QEcn1q1kjoi7OCjGb94hMdbs0_xONsp5nvflVhHPqaHRGs55R4kYsIPeKCglsg65b9tAeRNVVS6qA2PydeMAKuRcUpzwiqEtuh861RvkEMo-_jA7Ea4Q9L7nUHjPLpK8An18Fpe_gwYoU1vrKvb1K54gxD3pBzc7kQO0EVxPABZST7pGUSVgYNSJXXaOBuZdR2Y8ifJN0U21i896oc6ZEWGdSi7w=w251-h207-no

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

`18:05:42.334 TypeError: this.$refs.clickFoodInfo is undefined 1 3.a1d3eb1d45167be6d406.js:1:57074 [1546]/e.a.methods.mouseMoved https://habitica.com/static/js/3.a1d3eb1d45167be6d406.js:1:57074 n https://habitica.com/static/js/vendor.d09481509ca40eb0d853.js:6:1047 [1830]/i/<.on.mouseMoved https://habitica.com/static/js/3.a1d3eb1d45167be6d406.js:1:102001 s https://habitica.com/static/js/app.44ac19e70a04b8d9994e.js:1:417497 [1455]/e.a.bind/t.handleMouseMove< https://habitica.com/static/js/8.b0f9e6d4abd3be44feb5.js:6:96752 r https://habitica.com/static/js/vendor.d09481509ca40eb0d853.js:6:107620 c https://habitica.com/static/js/vendor.d09481509ca40eb0d853.js:6:107678 g https://habitica.com/static/js/vendor.d09481509ca40eb0d853.js:6:108108`

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Yes, I believe it is. We had this report in the Report a Bug guild earlier today from lava_rat (cb5afdee-9f22-490d-87a1-a11cdaff45de):

"on the Stable page, when I hover my mouse over my animals, these annoying black boxes keep appearing. They don't have any words on them. And it's really hard to get them to go away! I have to like wave my mouse around them. And several appear at once. It's annoying. So if it's possible, could you take care of that?"

I'm pretty sure I've seen it recently too.

**Comment by lemoness** [comment]
Is this still happening? I haven't encountered it recently.

**Comment by Alys** [comment]
I can't replicate it. We can reopen this if it's reported again.
