### ISSUE TITLE
Buying Cards Doesn't Give Notifications

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#9552]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

The Druid ( 68ce1251-d4a8-4ed6-ada4-f9ebea261d1e ) 
@TheHollidayInn I did hit the "select" button, but it still wasn't working. It did eventually register, but it was several minutes later. I've tried it on a different computer to see if it was an issue on my end, but it's still happening. It's that second grey popup with the grey "Buy" button that makes it especially confusing. It makes it seem like it hasn't worked. Refreshing deducted the gold, but doesn't give me any notification that the card has sent (though I assume it has, since it took the gold). And it happens even if I don't try to buy in bulk. This definitely does not seem like intended behavior.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by librarianmage** [comment]
Related Issues (cards):

* https://github.com/HabitRPG/habitica/issues/9484
* https://github.com/HabitRPG/habitica/issues/9534
* https://github.com/HabitRPG/habitica/issues/9317
* https://github.com/HabitRPG/habitica/issues/8379

**Comment by TheHollidayInn** [comment]
Yea, I believe this is a duplicate of #9484
