### ISSUE TITLE
Bailey's "newStuff" modal prevents Record Yesterday's Activity (RYA) screen being used

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9554]
If there's a Bailey message waiting for you to read it when your cron is due, the Bailey modal appears over the top of the Record Yesterday's Activity modal. When you click the Bailey's dismiss button, the RYA modal is also dismissed, meaning that you take damage for any uncompleted Dailies.

The correct behaviour should be _one_ of these:
1. Dismissing the Bailey modal does not dismiss the RYA screen.
2. The RYA screen appears over the top of the Bailey modal so that it can be used first.

@TheHollidayInn since you've done work on the modals, which do you think is best?

**Comment by TheHollidayInn** [comment]
I forgot to open the PR, but I have the fix: https://github.com/HabitRPG/habitica/pull/9555.

**Comment by Alys** [comment]
Fastest issue fix ever! :)
