### ISSUE TITLE
Test activates Daily on every (x) week on weekday fails due to year overflow

### ISSUE THREAD

**Issue by TNychka** [HabitRPG/habitica#9556]
I hope you don't mind me bypassing the guild, but I felt that it wouldn't be relevant there :)

[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
Jenkins build TEST="test:common" COVERAGE=true fails on `shouldDo Every X Weeks activates Daily on every (x) week on weekday:`

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Jenkins build: fails on PRs with unrelated changes. Personal PR examples below.
https://travis-ci.org/HabitRPG/habitica/jobs/304861404
https://travis-ci.org/HabitRPG/habitica/jobs/304860930

After investigating this is due to year overflow in calculations in cron.js line 141.
`let differenceInWeeks = moment(startOfDayWithCDSTime).week() - moment(startDate).week();`. Since the expected week startOfDayWithCDSTime is now in January 2018 the index resets to 0, and the result differenceInWeeks becomes negative and gets a different mod result. There is a simple fix to check if the result is negative and adjust accordingly (in the case of weekly add 52 to the negative difference). Associated Daily, weekly, monthly, yearly, ect should be verified as well. Should also add new tests to check this.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

```  503 passing (4s)

  6 pending

  1 failing

  1) shouldDo Every X Weeks activates Daily on every (x) week on weekday:

      AssertionError: expected false to equal true

      + expected - actual

      -false

      +true

      

      at Context.<anonymous> (test/common/shouldDo.test.js:649:68)
```

**Comment by TheHollidayInn** [comment]
Yep! you are fine to skip the guild. I just fixed this issue on release: https://github.com/HabitRPG/habitica/pull/9551. I'll merge it into devlop soon.
