### ISSUE TITLE
log Resting in the Inn in Amplitude

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9561]
When a user starts or stops resting in the inn, we want to have a record of it in Amplitude to help us troubleshoot bugs such as https://github.com/HabitRPG/habitica/issues/9558

The API route that starts/stops resting is `/api/v3/user/sleep`

https://github.com/HabitRPG/habitica/blob/4618fd8954a7c3f4d4fc486ce25536a61de6349c/website/server/controllers/api-v3/user.js#L709-L734

If you search for `analytics` in that file, you'll find other routes that already log to Amplitude, so that will give hints about how to do this.

The information recorded in Amplitude should make it clear whether the user is starting to rest in the inn or stopping resting.

**Comment by cailinglu** [comment]
I'd like to give this a try, if it's alright :)

**Comment by TheHollidayInn** [comment]
Thanks!
