### ISSUE TITLE
can't use Cards (greetings, thank you, etc) - second Buy modal appears

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9567]
As reported by Bee ( 47e17998-8096-40cd-aa4b-8b6270c98e11 ) in the Report a Bug guild:

"I tried to purchase 2 greeting cards to send to party members, and then it said to select a party member, so I did, and then it went to a box that looked like the purchase screen but it was all grayed out and I couldn't do anything."

EDIT 2017-12-15: The second modal is no longer greyed out.

Same thing happened when I tried it. After clicking the "Select" button in the "Select a Party Member" modal, that modal closes and you see this:

![image](https://user-images.githubusercontent.com/1495809/33123631-9794e0c2-cf72-11e7-8fc5-4d4f6a9b7726.png)

I'm marking this as important priority.

**Comment by Alys** [comment]
This is still happening (even in staging) except that the second buy modal is not greyed out. It makes it look as if the card was not successfully sent, so I'm keeping this labelled as an important priority.

**Comment by chandramaniadil** [comment]
One thing to be noted is that the coins were deducted after a long time, and the card was sent successfully. 
(cross-checked it from receiver's profile)

**Comment by TheHollidayInn** [comment]
@alys I think that is intended. After closing one modal it returns you to the previous to purchase again.

**Comment by chandramaniadil** [comment]
@TheHollidayInn that's the way it should be, but after sending the card there was no pop-up message confirming whether the card was sent or not.

**Comment by TheHollidayInn** [comment]
@chandramaniadil Agreed, that is a problem, but it is noted here #9484

**Comment by Alys** [comment]
As @TheHollidayInn  says above, this is intentional so I'm closing this. I'm marking it with the Memorable label so we can point users at it more easily if it's reported again.
