### ISSUE TITLE
Party page can display some Guild visuals

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9568]
From walrus62 ( 54665726-61fc-473f-8062-31a950a9ae11 ) in the Report a Bug guild:

"my party page on the website loaded as if it were a guild. It gave me the grassy background, a Summary with my [party] name inside (though I couldn't edit it), and removed quest information. Refreshing the page didn't work; I had to completely close my internet browser and reload Habitica."

After being asked if they were certain they were viewing the `/party` page:

"Yes I am sure, because it gave a 'guild summary' that had my party name in it, I could see my party name at the top where the guild/party name should be, and I could see my party chat. There was an 'Upgrade' button that linked to the Group Plans page, an 'Edit' button for me to edit my party description (which was how it should be) and I am not leader of anything else. It happened again just now, actually. If it happens again I will take a screenshot."

I've asked for more details about what walrus62 was doing just before going to the party page when it appeared like that and I'll update this issue if they can think of any specifics.

**Comment by Alys** [comment]
walrus62 says "I think it was after the task page, but I'll make note of it if it happens again."

**Comment by TheHollidayInn** [comment]
I'd say, let's close this until we get another report.
