### ISSUE TITLE
button in modal is white until focus is given to modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9577]
When a new player visits their party for the first time, they see this modal:

![image](https://user-images.githubusercontent.com/1495809/33220362-80517af0-d13f-11e7-8fd1-836eb04635eb.png)

The button is white so it can't be read, which is incorrect.

When you click on the modal, the correct colour is applied:

![image](https://user-images.githubusercontent.com/1495809/33220393-b3c7201a-d13f-11e7-963b-e3ebfce10353.png)

The desired behaviour is that the button has the correct colour as soon as the screen appears.

This might occur for other modals too.

**Comment by Alys** [comment]
labels updated

**Comment by AlyxMoon** [comment]
I'm happy to try fixing this.

**Comment by Alys** [comment]
@AlyxMoon Great, thanks!
