### ISSUE TITLE
"submi a bug" button

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#958]
Not a bug, but you can make the submi a bug button in rpg to open in a new tab instead of the same page.

**Comment by StanLindsey** [comment]
It should do? Works for me? What browser are you using?

**Comment by nikrage** [comment]
firefox

 -------- Оригинално писмо --------

От: Stan Lindsey notifications@github.com

Относно: Re: [habitrpg] "submi a bug" button (#958)

До: lefnire/habitrpg  

Изпратено на: Вторник, 2013, Май 14 19:01:50 EEST

It should do? Works for me? What browser are you using?

**Comment by lefnire** [comment]
yeah was a bug. browser-independent, but fixed now. @SlappyBag I wonder if Chrome just really good at fixing "woops" html :)

**Comment by StanLindsey** [comment]
Chrome is magic.
