### ISSUE TITLE
sorting Dailies in "All" filter causes "Due" filter to be applied

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9582]
As reported in the Report a Bug guild by Il Mago Azzurro (c073342f-4a65-4a13-9ffd-9e7fa5410d6b):

"Website, trying to reorder my dailies with the "All" filter active results in having the "Due" filter (the default one) activating everytime the page sync after I move something, I had to move only 2 things, but it was really longer than it should be..."

I've confirmed that in my account, although it didn't happen every time (just most of the time).

The correct behaviour is that when you are sorting Dailies using any of the All/Due/NotDue filters, the filter should never be changed automatically.

**Comment by kartikadur** [comment]
I'd like to work on this if it is still available.

**Comment by lemoness** [comment]
@kartikadur Thank you very much! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by kartikadur** [comment]
Is there anything that I should know before starting work on this issue?

**Comment by Alys** [comment]
@kartikadur I can't think of anything but if you come across anything that looks confusing or that seems it would benefit from additional comments, please do ask here!

**Comment by Aerilita** [comment]
I'm not sure if it's known, but in my recent experience switching back to "Due" also occurs after manually syncing (via the sync button), even if I don't try to move dailies at that point. I suspect it might be related.

**Comment by kartikadur** [comment]
@Aerilita they could be related. I think the code might be reverting to default functionality everytime the page re-renders on data change.

@Alys would it be beneficial to set data to the store in cases where the dropdown state needs to be remembered? and if so what would be the best way to do so? I know `$store` is used on other pages, I am unsure if it is implicit or vuex is being used in the background.

**Comment by Alys** [comment]
@kartikadur I'm sorry no one answered your question. :( I'm not familiar enough with the new website's vue code to comment on that. Are you still interested in working on this issue? If so, I'll check back to see if one of the staff can answer you.

**Comment by kartikadur** [comment]
@Alys I am still interested.

**Comment by paglias** [comment]
@kartikadur 

> @Alys would it be beneficial to set data to the store in cases where the dropdown state needs to be remembered? and if so what would be the best way to do so? I know $store is used on other pages, I am unsure if it is implicit or vuex is being used in the background.

which dropdown are you talking about?

The $store is a vuex feature that's available in all pages and the data stored there is persisted as long as the website remains open

**Comment by kartikadur** [comment]
@paglias, sorry, I meant the task/dailies/etc filter state not a dropdown state. Currently it resets to the default filter state. I am still trying to figure if the data object, computed property, or the watched function is responsible. 

I want to persist the filter state between renders and preliminary exploration indicated that the best bet was the vuex store feature.

**Comment by paglias** [comment]
Yeah the best way to persist data between renders is the vuex's $store

**Comment by kartikadur** [comment]
@paglias 
my vuejs devtools chrome extension indicates that there is no vuex store. In the code it seem like there is a proprietary store code. What would be the best way to access this store state?

**Comment by paglias** [comment]
@kartikadur you're totally right, sometime I forget we don't use Vuex (because it was incompatible with some of our code) but we use our own store that works more or less the same way except that it doesn't have mutations, only actions.

The code is in website/client/store

**Comment by kartikadur** [comment]
@paglias does this store still function similar to vuex, with the exception of mutations?

As far as I can tell the tasks / dailies / rewards etc are shown in `website/client/components/tasks/column.vue`

Is there a reason why `website/client/components/tasks/column.vue` page has access to all of the store user data? Or can I convert this to a thin / dumb component and create getters/actions for the store to be used in lifecycle methods? especially since there is this in the code
```javascript
    // @TODO refactor this so that filter functions aren't in data
```

**Comment by paglias** [comment]
You can refactor it if you want

**Comment by kartikadur** [comment]
@paglias thanks

**Comment by kartikadur** [comment]
`tasks:order` action in store/actions/tasks.js as far as I can tell only seems to reorder tasklists based on `user.tasksOrder` and returns it without altering the store. It is only used in column.vue and tasks.js and acts like a utility/lib function rather than a store mutator. Was there a reason to put it where it is now?

**Comment by TheHollidayInn** [comment]
I think it was just a misunderstanding. The taskOrder function should be a library function rather than a store mutator.

**Comment by kartikadur** [comment]
@TheHollidayInn thanks, thats good to know.

**Comment by kartikadur** [comment]
__update__ : I'm still working on this. Wrapping my head around existing code so I dont introduce new / reintroduce old bugs is taking slightly longer than anticipated. I should have a PR by this weekend.

**Comment by Alys** [comment]
I'm reopening this because it's still happening in our staging website, which contains PR #9898. In case this is relevant, in the Settings screen I have "Set Dailies default to 'due' tab" ticked.

**Comment by kartikadur** [comment]
@Alys could you check if it happens after toggling "set dailies default to 'due' tab" option once after the page has loaded and let me know if it still happens? Also how many dailies do you have in your dailies tab?

Most of the times I experienced this error, or similar errors, it happened the first time something was set/reset/loaded. By loading I mean when the frontend gets something from the backend API and the page does a rerender, similar to completed todos. So I assumed it might have something to do with the initial render cycle of Vuejs or something within the render cycles and watched elements of VueJs components. I'll check for a few more things in the meanwhile.

**Comment by Alys** [comment]
No worries. Here's tests I've just now performed:
- went to staging site using a test account that had no Dailies
- added three Dailies, all due today:
	- Daily called "3" is at the top
	- Daily called "2" is in the middle
	- Daily called "1" is at the bottom
- reloaded Tasks page
- went to User Icon > Settings
- turned on the setting for "Set Dailies default to 'due' tab"
- went to Tasks page
- clicked "All" filter for Dailies
- moved task 1 up to middle position (in between 2 and 3) - "All" filter stayed selected
- moved task 2 up to middle position (in between 1 and 3) - bug: "Due" filter became selected
- reloaded Tasks page
- clicked "All" filter for Dailies
- moved task 1 up to middle position (in between 2 and 3) - "All" filter stayed selected
- moved task 2 up to middle position (in between 1 and 3) - bug: "Due" filter became selected

If that's not the tests you wanted, I'm happy to do more. If you can outline tests step by step like that, it will ensure I do what you need.

**Comment by kartikadur** [comment]
Yeah thats a close approximation of the tests I performed too, though I didn't have the problem. Is the website for your test account run in development mode or production mode? Are you moving the second task before the page finishes reloading after the first task is moved? 

Maybe I need to account for something I am not seeing. In any case I'll check the code and look to rectifying this error.

Also can we mark this case for an e2e test when people start writing them eventually?

**Comment by Alys** [comment]
I believe the staging site runs in production mode. It certainly doesn't have the debug menu which I think it one of the primary differences between production and development mode.

Yes, I waited for a sync before moving the second task.

For e2e tests, we could create an issue with a checklist of all the features that need them. There might be one already, in which case I'll add this feature - that's a good idea! I'll look into it tonight.

**Comment by kartikadur** [comment]
The current version of code uses a watcher to change the filter to 'due' or 'all' based on user preference on the setting page. So everytime the page loads (initial load and subsequent reloads) the filter reverts to the user selected default value. Ideally this should happen only on first load and not subsequent reloads. This could be done using lifecycle methods (beforeCreate, created, beforeMount, etc.) or the router to run a method when vuejs routes from any other page to tasks page. While the former seems easier the latter seems more promising. Once I understand more I'll start working on the update. In the meanwhile if there are any suggestions or pointers let me know.

**Comment by kartikadur** [comment]
@paglias @TheHollidayInn I seem to be hitting a snag with component unit testing, are there any issues to using `vue-test-utils` package as a dev-dependency? Or are there alternatives currently being used?

@alys I found that the problem was happening because of the watcher, which was resetting the task filter on each reload/sync instead of only setting it when the component is first created/loaded. Hopefully this solution should work.

**Comment by paglias** [comment]
@kartikadur you can add that package if it's useful! Just do `npm i vue-test-utils`and commit the changes to package.json and package-lock.json to your branch

**Comment by kartikadur** [comment]
@paglias thanks
