### ISSUE TITLE
Mention Options Don't Refresh When Changing Guild

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#9587]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Aerilita ( 3b724a41-48d3-4048-ae27-70b258cf5a72 ) tier 1 Friend Socialite 
Minor issue Here's something I just noticed, no idea how long it's been around.
Visit a guild from notification (say, Aspiring Socialites).
Visit another guild from notification (in my case, Learn Mandarin).
Start replying to a post by typing @ at the beginning of the post editing field.
Names that appear belong to those who last posted in the previous guild, may not be members of the current guild (I got Alys, Cantras, Kent the Beginner etc, can't find them in Learn Mandarin chat, but their posts are last in Aspiring Socialites).
Doesn't persist after hard refresh, but is recreatable by going to a next notification (coincidentally, my next notification was from Report a bug guild, so when I started this post here, I typed @ and the list of suggestion contained users from Learn Mandarin).
Doesn't happen if I visit guilds from "My guilds" menu, but does happen if from some guild I move to Report a bug guild via Help->Report a bug.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by lemoness** [comment]
Labels updated.
