### ISSUE TITLE
Allow Account Linking (list manager?)

### ISSUE THREAD

**Issue by DerekC1990** [HabitRPG/habitica#96]
I'd like the ability to link accounts so that someone else can remotely add todos and such to my account and then when I finish the task I can check it off (also allowing me to delete/modify it in case necessary). I think the system should e-mail me when a new todo has been added to my list for me or something.

**Comment by wc8** [comment]
Maybe let them send the task as a "challenge" for one to accept. (Although I suppose you could always delete it.)
And/Or allow one to take on tasks from another person's public tasks in a party.
Maybe bonus points for accepting. Bigger points for completion by deadline.
This could appear as a Waiting For task in the sender's/sharer's list.

**Comment by hookang** [comment]
Email Account Syncing - Added to Master Feature List #169. Closed for Organization.

**Comment by wc8** [comment]
See these on Trello [Delegated Tasks](https://trello.com/c/kZdy2slG), Also [Email Sync](https://trello.com/c/hxt5ApKM)
