### ISSUE TITLE
Incorrect left and right margins on the page

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#9603]
Throughout the site, the content should be framed by ~24px on the left and right. These are commonly referred to as "gutters" in design/development. Below you can see an example of the incorrect alignment.

![image](https://user-images.githubusercontent.com/2686586/33393540-7c9c25fa-d50d-11e7-8a84-7688b1d1a8ac.png)

This touches on various areas of the site, primarily the Tasks page, Tavern, Guilds, and Party.

**Comment by Alys** [comment]
Since this is low priority, can we put it on hold until https://github.com/HabitRPG/habitica/issues/9538 is fixed? On small screens the extra 48 pixels could be enough to throw some users into the buggy situation where they can't use the User Icon menu.

**Comment by lemoness** [comment]
Yes, I'm okay with temporarily putting this on hold until that's resolved.

**Comment by lemoness** [comment]
That has been resolved, so this ticket is now available to be claimed!

**Comment by che-perez** [comment]
I want to work on this, but may I have more explanation of what it is that needs fixing?

**Comment by lemoness** [comment]
@tressley

**Comment by Tressley** [comment]
@che-perez -- Great! Let me see if I can help clarify. On a desktop browser, the site should have roughly ~24px (converted to the proper unit) padding as "gutters" on the left and right. In the screenshot above, you can see that the content below the header is not flush with the content in the header.

![image](https://user-images.githubusercontent.com/2686586/38138762-82eb1974-33fa-11e8-93af-22919611829b.png)

**Comment by adamfitzgibbon** [comment]
This hasn't been touched for a while, is it still an issue or was it fixed by the redesign?

**Comment by Tressley** [comment]
@adamfitzgibbon -- I don't believe that this has been fixed. Is this something you'd be interested in taking on?

**Comment by adamfitzgibbon** [comment]
Sure. Can I assume that the areas you mentioned (Tasks page, Tavern, Guilds, and Party) are the only areas I need to fix or do you know of other specific pages?

**Comment by adamfitzgibbon** [comment]
@Tressley I submitted a pull request, let me know if there are any additional pages and I'd be happy to add them in! Particularly of note: I couldn't find any problems with the Guilds pages so if you could point out what you mean on that one especially it would be greatly appreciated!

**Comment by Tressley** [comment]
@adamfitzgibbon -- Awesome! Thank you for your help on this. For the Guilds pages, I was referring to the right column's padding. This also touches Parties (Challenges seems to be correct in this case.)

![image](https://user-images.githubusercontent.com/2686586/67774182-489c7500-fa33-11e9-9ba9-1c131c2d86ef.png)

**Comment by adamfitzgibbon** [comment]
@Tressley Should both sides of the column have that 24px padding or just the right side? Also should I apply it to the header image? (if not, I think I may have in the parties page and will need to revert it)

**Comment by Tressley** [comment]
Both sides of the column. It doesn't need to be applied to the header image.
