### ISSUE TITLE
Improvements to Challenge Layout

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9619]
_edit by Alys: ignore the "Ends ..." text in the screenshots below and also ignore the comments below that discuss End Date and Start Date. Those new features will be added in https://github.com/HabitRPG/habitica/issues/9672._

Based on the feedback we've received from the community, we've made the following changes to the My Challenges/Discover Challenges lists that will need to be implemented. 

Old version:
<img width="587" alt="screen shot 2017-11-30 at 4 39 17 pm" src="https://user-images.githubusercontent.com/3494081/33462578-27bdd548-d5ed-11e7-8888-8dce8efc3fff.png">

New version:
<img width="1192" alt="screen shot 2017-11-30 at 4 33 45 pm" src="https://user-images.githubusercontent.com/3494081/33462605-48304946-d5ed-11e7-85a0-afeecbf1c593.png">

- More compact
- Shows clickable names of creator and Guild
- Adjustments to spacing/positioning
- Categories displayed

Currently the design includes End Dates, but that will be addressed in a separate issue, so anyone who works on that can disregard it for now. 

@Tressley will add whoever wants to work on this issue to our contributor Zeplin for all the specific implementation details, so you'll need to tell us which email we should invite!

**Comment by TheHollidayInn** [comment]
Are the heights in the new version supposed to match or no?

**Comment by Tressley** [comment]
@TheHollidayInn -- Our hope is that most of them will be within the same height. The version to the left is the edge case in which a Challenge has a title that wraps to two lines and max summary length. Most of them will look like the version to the right.

**Comment by lemoness** [comment]
We're also going to add a field for Start Dates, so I'm briefly putting this on hold while we add that to the design.

**Comment by Alys** [comment]
@lemoness The start dates and end dates won't be as easy to add as the other changes because they'll need changes to the API, challenge creation/edit form, tests, and maybe other code. In contrast, adding the guild name+link, creator link, and category display will require only edits to the file that displays the challenge, and they'll be useful immediately. Being able to access the profile for the owner and knowing which guild a challenge belongs to are much requested. Can we make those simple changes in this issue and create a new issue for the more complex work?

**Comment by shanaqui** [comment]
@lemoness @alys Agreed, we badly need the ability to PM the owner, and seeing the guild is also helpful. I think we need to have those done first and as soon as we can.

**Comment by lemoness** [comment]
Yes, I'm happy to segment this into two tickets!

**Comment by Alys** [comment]
I've taken this issue off hold, logged https://github.com/HabitRPG/habitica/issues/9672 for adding start and end dates and I've updated the top post to add this message at the top:

_edit by Alys: ignore the "Ends ..." text in the screenshots below and also ignore the comments below that discuss End Date and Start Date. Those new features will be added in #9672._

**Comment by melarish** [comment]
I'll work on this (my other in-progress ticket should be done shortly, pending a clarification). I'm already on the Zeplin project but can't see these screens (username: melarish)

**Comment by lemoness** [comment]
@melarish  Thank you very much!

@Tressley When you have a moment, could you add those screens?

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by Tressley** [comment]
@melarish -- Thanks for being patient. I've uploaded the art board to our Zeplin here: https://zpl.io/2EyKXn8

Feel free to add comments with any questions!

**Comment by melarish** [comment]
Hey all; I'm going on holiday for 3 weeks and haven't had the chance to work on this yet. If anyone wants to take over, feel free; if not, I'll resume once I get back!

**Comment by lemoness** [comment]
I've marked this issue as Help Wanted.

**Comment by marvinrabe** [comment]
I had a look at the challenge design and already improved the details page to match group detail design (pull request not yet created).

I can continue working on it if you want.

**Comment by paglias** [comment]
Go for it @marvinrabe !

**Comment by marvinrabe** [comment]
Any feedback?

<img width="1364" alt="preview" src="https://user-images.githubusercontent.com/515860/39484047-c72ca18c-4d74-11e8-94ae-1e6acd94dc4d.png">
