### ISSUE TITLE
"Block" button in User Profile should be an icon

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#9626]
**Current**
![image](https://user-images.githubusercontent.com/2686586/33492724-f5f97c02-d68b-11e7-87b1-8c94c46f9f04.png)

**Approved Design**
![image](https://user-images.githubusercontent.com/2686586/33492708-e8afb160-d68b-11e7-9440-6e68cc530107.png)

If you're interested in picking up this issue, please leave an email address to be invited to our Zeplin project.

**Comment by Tressley** [comment]
**Note:** The order of the buttons is incorrect as well. Should be easy enough to include in this issue.

**Comment by xXenithx** [comment]
I am fairly new to this project so bear with me as I am not entirely familiar with where everything goes.
I managed to come across an update with boostrap 4 stating glyphicon fonts are being dropped (that might be the issue I'm not entirley sure).

[Bootstrap 4 Migration](https://getbootstrap.com/docs/4.0/migration/#components)

Anyhow I switched to [Font Awesome](http://fontawesome.io/l)'s icons instead (only problem is you have to use your email to get a custom cdn url so I used mine just to see if it works). I managed to get the icon to work with these fonts. Though it does seem a little off center, I'll try to see if I can adjust it.

Let me know if this works!
My email is andybustos021@gmail.com
![screenshot-localhost 8080-2017-12-01-20-53-35](https://user-images.githubusercontent.com/4366997/33511613-f068bd4e-d6da-11e7-8171-aed8634780ef.png)
![screenshot-localhost 8080-2017-12-01-21-02-56](https://user-images.githubusercontent.com/4366997/33511617-0a53c410-d6db-11e7-9a69-6f295c3809e2.png)

**Comment by paglias** [comment]
hey @xXenithx thanks for the interest, we're using our own home made icons for the website. If you're interested in fixing this issue we'll get you access to them :)

**Comment by xXenithx** [comment]
@paglias Yeah I can definitely fix it for you. Am i using a cdn or just including the icons in the assets folder?

**Comment by paglias** [comment]
@xXenithx you should add the new icon, if it doesn't already exist into /website/client/assests/svg. I'm uploading it here in case it's not already in the repo 

[remove.svg.zip](https://github.com/HabitRPG/habitica/files/1525086/remove.svg.zip)

**Comment by xXenithx** [comment]
@paglias Okay they were in the svg directory my bad. I added both the remove and positive svg file to the modal. Let me know if this works for you!

![screenshot-localhost 8080-2017-12-03-14-01-38](https://user-images.githubusercontent.com/4366997/33529792-bc934d8c-d832-11e7-9828-c9c658eaaa76.png)
![screenshot-localhost 8080-2017-12-03-14-01-54](https://user-images.githubusercontent.com/4366997/33529798-cb7b0a92-d832-11e7-8075-a2c18e78484f.png)

**Comment by paglias** [comment]
@xXenithx that looks good! Can you open a PR with these changes?

**Comment by Tressley** [comment]
@xXenithx -- Great stuff! Just a couple of things I noticed.
- The icon is the incorrect color. It should be `#686274`.
- Icon needs to be tweaked so it is properly centered.

**Comment by xXenithx** [comment]
@Tressley Okay, changed the color of remove icon as well as the message icon (it looked darker than the rest). I've also did my best to center all buttons as much as possible. Hope this works!

![screenshot-localhost 8080-2017-12-04-09-47-00](https://user-images.githubusercontent.com/4366997/33564651-4803e232-d8d8-11e7-9be0-082e72e949f1.png)

**Comment by Tressley** [comment]
@xXenithx -- Color looks good! But it looks like the icon is being clipped at the top.

**Comment by xXenithx** [comment]
@Tressley Okay fixed the size of the icon.
![screenshot-2017-12-4 habitica](https://user-images.githubusercontent.com/4366997/33570781-2a463188-d8eb-11e7-9518-8272ceaa8dbd.png)

**Comment by Tressley** [comment]
@xXenithx -- Looks good to me!
