### ISSUE TITLE
Challenge Winner Text is misleading

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9629]
The Challenge winner declaration text implies that you can select more than one winner, which is not the case. It should say “Select a winner from the Challenge participants” and “Award Winner.” (Also, there should be some space between the winner’s name and “Selected”.)

**Comment by avirgil** [comment]
I can take a look at this, but it would be my first issue. :)

**Comment by TheHollidayInn** [comment]
Go for it :D

**Comment by avirgil** [comment]
Ok so I've fixed the first two issues in en and en_GB but how are text updates for other languages handled?

Also I can't for the life of me figure out where the winner's name and "Selected" appear. @lemoness can you clarify?

**Comment by Alys** [comment]
Thanks @avirgil !

Only the /en/ language should be edited in the repository. Other languages are handled in Transifex - see the _README_FIRST.md file in the locales directories for details. Can you reverse the changes to the en_GB files before creating a pull request? You can do that with `git checkout <path/to/file.json>`

**Comment by avirgil** [comment]
Will do, thanks. Does anyone have insight on the `Name "Selected"` part?

**Comment by lemoness** [comment]
The spacing question is something for @Tressley to answer!

**Comment by Alys** [comment]
The "selected" spacing part is no longer relevant so I'm closing this.
