### ISSUE TITLE
"Undefined" under header / due tasks are grey

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#963]
I've refreshed many times, but this is all I get. Server down or something else?

Mac 10.8.2, Safari 6
user: bobbyroberts99

![name002](https://f.cloud.github.com/assets/4084120/502750/628e5c44-bcb9-11e2-89cb-86d41c4028d7.jpg)

**Comment by lefnire** [comment]
Can you try now?

**Comment by bobbyroberts99** [comment]
I can see beta again but some of my dailies are greyed out (none should be) and all of my todos are greyed out too (none should be).

**Comment by lefnire** [comment]
Ok, the todos bit is a bug, fix being pushed right now. As for dailies - do
you have a custom dayStart set to after right now, and your daily is due
for today?

**Comment by lefnire** [comment]
ok, previous commit should address the second issue now. So, crossing my fingers, this issue should be fixed all around

**Comment by lefnire** [comment]
this should be fixed, re-open if anyone else has trouble
