### ISSUE TITLE
users can't add their own tags to challenge tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9639]
When you join a challenge, you should be able to edit your own copies of the challenge tasks to add your own tags to them.

Currently you cannot. When you open a challenge task for editing, if you click on the "Tags" drop-down in the edit form, nothing happens - the drop-down does not open. It should open and should allow you to select one or more of your tags (including other challenge tags).

I'm marking this important priority because this is seriously annoying for players who keep their tasks organised by tag.

**Comment by Alys** [comment]
labels updated

**Comment by TheHollidayInn** [comment]
This was my bad. I misread the Wiki for challenge access :(
