### ISSUE TITLE
scroll bar mostly hidden in quest selection list in party page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9640]
On the party page, when you want to start a new quest and you get the screen that lets you choose a scroll, the scrollbar is mostly hidden by the quest description in the middle.

![img](https://i.imgur.com/kLCrl8V.png)

This is similar to https://github.com/HabitRPG/habitica/issues/9537 and probably can be fixed in much the same way: https://github.com/HabitRPG/habitica/pull/9544

_Thanks to sonnet73 for reporting this in the Report a Bug guild._

Labels updated.

**Comment by cassidypignatello** [comment]
I can take this one if no one's working on it!

**Comment by paglias** [comment]
@cassidypignatello go ahead :)
