### ISSUE TITLE
Incorrect styles on Snack notifications

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#9648]
Current implementation of Snack notifications has many style issues.

- Positioning of the sprite should be centered
- If the line wraps, the container should grow accordingly. (There may be in an instance in which the string becomes three lines. In that case, we'll need to adjust the `font-size` and `line-height`.)

**Current**
![image](https://user-images.githubusercontent.com/2686586/33561841-c0208136-d8e1-11e7-88cd-2582004ba5c1.png)
![image](https://user-images.githubusercontent.com/2686586/33561949-05c45e4c-d8e2-11e7-995c-db73af4992f6.png)

**Designed**
![image](https://user-images.githubusercontent.com/2686586/33561863-d05fc4a8-d8e1-11e7-8de1-d13330a12e3c.png)
![image](https://user-images.githubusercontent.com/2686586/33561983-1bef33ea-d8e2-11e7-9dad-95f7e7812a85.png)
![image](https://user-images.githubusercontent.com/2686586/33563030-d4d1a3aa-d8e4-11e7-9674-0d64b613aecf.png)

If you are interested in working on this issue, please comment with an email address you would like invited to our Zeplin project.

**Comment by TheHollidayInn** [comment]
I think you should post examples of 2 and 3 lines because that affects the styles with respect to the icon.

**Comment by Tressley** [comment]
@TheHollidayInn -- Yeah, this was reported by SL to me, but there wasn't an accompanying screen. I've struggled to find a tooltip that uses three lines.

**Comment by TheHollidayInn** [comment]
Sounds good. If I find one, I'll post it here. :D

**Comment by marcusvmdomingos** [comment]
I think that would be a case for a three line notification without an icon:
![3-lines-notification](https://user-images.githubusercontent.com/28844427/34091757-d0b26f1c-e3a6-11e7-8b1f-778e37b97bd0.jpg)

The words fall out from the tooltip borders. Looked up for one with an icon, but I think there's none of it.

I can get this issue with the showed cases. And if some three line with icon comes up, I include in another commit or we open another issue.

Just say if I can take it, plz.

**Comment by TheHollidayInn** [comment]
Please feel free to take it :D

**Comment by marcusvmdomingos** [comment]
Oky doky.

**Comment by TheHollidayInn** [comment]
Looks like the PR was merged!
