### ISSUE TITLE
Update CSS fonts on Habitica homepage

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#9650]
Certain sections of the Habitica homepage are using the incorrect font. Should be using [Varela Round](https://fonts.google.com/specimen/Varela+Round) from Google Fonts.

**Existing**
![image](https://user-images.githubusercontent.com/2686586/33562356-1ffca84a-d8e3-11e7-91ae-9a7f79d53833.png)

**Designed**
![image](https://user-images.githubusercontent.com/2686586/33562383-2d5fa87a-d8e3-11e7-8a73-63a68258fc85.png)

If you are interested in working on this issue, please comment an email address to be invited to our Zeplin project.

**Comment by kartikadur** [comment]
I'd like to help, my email is kartikadur@gmail.com

**Comment by TheHollidayInn** [comment]
Thank you!

**Comment by paglias** [comment]
Is this new font only used in the home / static pages? In that case we should try not to load it in the app if possible

**Comment by Tressley** [comment]
@paglias -- Yes. This is only for use on the Static pages. I agree on not loading in the app to reduce load times.

**Comment by TheHollidayInn** [comment]
Do we use css imports for this? If so, can we just import from google font on the home page scoped css?

**Comment by paglias** [comment]
No, we load the Roboto font manually but we could use an import just for the home page

**Comment by TheHollidayInn** [comment]
Sounds good!

**Comment by Arsnael** [comment]
I could help on this one I think ! rene.cordier@gmail.com

**Comment by paglias** [comment]
@Arsnael go ahead, thanks!

**Comment by Arsnael** [comment]
@paglias great! I will wait to get an in invite to zeplin first to view the designs in question :)

**Comment by Arsnael** [comment]
Maybe no need to peek in the Zeplin design? Anyway, just a font... for home / static pages right? I will check it !

**Comment by Tressley** [comment]
@Arsnael -- Sorry for the delay! You should see your Zeplin invite shortly. Here's a link to the artboard once you're part of the project: https://zpl.io/awYokyM

**Comment by Arsnael** [comment]
@Tressley no problem ! I will check that thanks

**Comment by Arsnael** [comment]
@Tressley : work in progress but I have a question. Is it only just about the font as the issue says? Because on the Zeplin design it's clearly more than just a change of font... Some colors and spacings are different, and the signup form is quite different as well. Some texts or buttons are lightly different too. So is the task about having a final result as the design there? Or it's just about the font and the rest will be in an other task?

**Comment by Tressley** [comment]
@Arsnael -- You're right in this issue being specifically about the font. The other updates need to be recorded in a new GitHub issue. If you're interested in working on those updates, let me know!

**Comment by Arsnael** [comment]
@Tressley  : Maybe in the future I will ahah. But ok if it's just about the font, it will be done faster then.

**Comment by Arsnael** [comment]
@Tressley : let me know if it's alright!
