### ISSUE TITLE
[Suggestion] Move heavy files to another repository or LFS

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9654]
This repository is very Heavy. Maybe moving heavy files hat are not changed often to another repository can help a little. Files like:
- `website/static/audio` 
- `website/static/emails/images`
- `website/static/raw_sprites`
- `website/client/assets/svg`
- `website/client/assets/images`

Or maybe put them info `git LFS` so they don't take so much time when cloning the repository

**Comment by librarianmage** [comment]
More information: [Git Large File Storage](https://git-lfs.github.com/)

> Git Large File Storage (LFS) replaces large files such as audio samples, videos, datasets, and graphics with text pointers inside Git, while storing the file contents on a remote server like GitHub.com or GitHub Enterprise

**Comment by paglias** [comment]
I don't think moving those files to LFS is actually doable but I realized the repo is a bit big, so I'll keep this open for other solutions like removing old branches or if there are ways to compress the repo size

**Comment by luanmuniz** [comment]
@paglias Why isn't doable? Dependencies?

**Comment by paglias** [comment]
Sorry, I thought using LFS would have required more changes. It seems pretty simple overall but I haven't researched all the implications of this and it might be a problem for our deployment workflow but @SabreCat and @TheHollidayInn knows more about that than me so I'll wait for their comment

**Comment by lemoness** [comment]
@TheHollidayInn @paglias Is this still something that we want?

**Comment by paglias** [comment]
Don't have a strong opinion here, I don't feel like the repo has got so big to create problems, cloning is a one time op

**Comment by librarianmage** [comment]
While I like that it would increase the speed of cloning and fetching, as far as I can tell it would require everyone to install the LFS extension, though I could be wrong.

**Comment by beffymaroo** [comment]
Any updates on whether this issue should remain open?

**Comment by paglias** [comment]
I'm closing this as we won't be making this change any time soon

**Comment by SabreCat** [comment]
It would be nice to reduce the repo size for the purpose of our Docker install process. But we've got workarounds in place to keep that running smoothly despite the 2+ GB image size.
