### ISSUE TITLE
only one pinned item is shown in Microsoft Edge (and maybe one/some Internet Explorer versions)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9662]
In Internet Explorer, only one pinned item is visible in the Rewards column when multiple items have been pinned.

![image](https://user-images.githubusercontent.com/1495809/33583404-39dad328-d928-11e7-94b7-a4667509512a.png)

```
    "pinnedItems": [
        {
            "type": "armoire",
            "path": "armoire"
        },
        {
            "type": "potion",
            "path": "potion"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.weapon_wizard_1"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.armor_wizard_1"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.armor_special_winter2015Mage"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.armor_special_birthday2016"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.armor_special_birthday2017"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.head_wizard_1"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.head_special_winter2015Mage"
        }
    ]
```

**Comment by Alys** [comment]
It's possible that this bug occurred after this PR was deployed: https://github.com/HabitRPG/habitica/pull/9358/files

**Comment by TheHollidayInn** [comment]
Which IE is this? I was going through fixes for IE and in IE 11 you can see pinned items (although they do not form a grid yet)

**Comment by Alys** [comment]
Hmmm, might be just Edge. We've just received this bug report from Crashback (1f4faadf-d2cb-4fb5-994e-7d9bc0d0706a):
"I am experiencing an issue where all of my pinned rewards are stacked in one box, making it impossible to select and purchase them without going to the market. I'm using Windows 10 and Microsoft Edge."

I'm adjusting the title of this issue to mention Edge.

**Comment by TheHollidayInn** [comment]
Sounds good. I can test on both.

**Comment by TheHollidayInn** [comment]
This isn't happening to me on Edge anymore. Any recent reports?

**Comment by greekboy411** [comment]
I haven’t noticed it at all myself.

Sent from Mail for Windows 10

**Comment by negue** [comment]
Looks good on Egde. 👍 
On IE the Items just have one item per line. IE doesn't support `display: grid`. But its still usable.

I think we can close this.
