### ISSUE TITLE
changing guild leader gives no immediate feedback

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9670]
When you change a guild leader using the "Member List" feature, there's no feedback that the leader change has been successful (e.g., a notification saying "leader has been changed").

Also when you close the menu list, the original guild leader name has been removed from the guild (which is correct) but the new guild leader's name doesn't appear there until you reload the page (it should appear immediately with no need for a reload).

Also, the edit form for the guild should be changed to remove the drop-down menu for selecting a new guild leader.
Instead there should probably be a message saying something like this:
_To change the leader, close this form, click on the guild's "Member List" link, search for the name of the new leader, and select 'Promote to Leader" from that person's three-dots menu._
We're waiting on approval for inserting a message like that.

Finally, moderators and staff should be able to change a guild's leader. 

All of these points should also apply to parties, except that mods and staff should NOT be able to change the party's leader (unless they happen to be the original leader of course).

None of these points should apply to any guild or party that has a group plan. It should not be possible for anyone to change leader.

**Comment by Alys** [comment]
I've renamed this from "can't change guild leader" to "changing guild leader gives no immediate feedback" and I've edited the top post to say this:


When you change a guild leader using the "Member List" feature, there's no feedback that the leader change has been successful (e.g., a notification saying "leader has been changed").

Also when you close the menu list, the original guild leader name has been removed from the guild (which is correct) but the new guild leader's name doesn't appear there until you reload the page (it should appear immediately with no need for a reload).

Also, the edit form for the guild should be changed to remove the drop-down menu for selecting a new guild leader.
Instead there should probably be a message saying something like this:
_To change the leader, close this form, click on the guild's "Member List" link, search for the name of the new leader, and select 'Promote to Leader" from that person's three-dots menu._
We're waiting on approval for inserting a message like that.

Finally, moderators and staff should be able to change a guild's leader. 

All of these points should also apply to parties, except that mods and staff should NOT be able to change the party's leader (unless they happen to be the original leader of course).

None of these points should apply to any guild or party that has a group plan. It should not be possible for anyone to change leader.

**Comment by TheHollidayInn** [comment]
@Tressley what are your thoughts on this section:

```
Also, the edit form for the guild should be changed to remove the drop-down menu for selecting a new guild leader.
Instead there should probably be a message saying something like this:
To change the leader, close this form, click on the guild's "Member List" link, search for the name of the new leader, and select 'Promote to Leader" from that person's three-dots menu.
We're waiting on approval for inserting a message like that.
```

**Comment by Tressley** [comment]
@TheHollidayInn -- I discussed this with @Alys briefly. I don't think there's an issue with having it in both places. If users are still looking to change the Guild Leader from the Edit modal, we can have the searchable dropdown component and a users list. If a Guild Leader wants to "Promote User to Guild Leader" from the Members List, they can. I think the messaging actually makes it more confusing.

We could replicate this in Parties as well.

As for immediate feedback. The current implementation looks to be missing the "Guild Leader" badge attached to the name in the Members List. That would be enough visual confirmation after selecting "Promote to Guild Leader" from the options dropdown.
