### ISSUE TITLE
add Start Dates and End Dates to challenges

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9672]
As mentioned in https://github.com/HabitRPG/habitica/issues/9619 (see the screenshots and some of the comments), challenges are going to have Start Dates and End Dates. This is a placeholder issue that will be updated once the designs are finished and we have more details about how the dates will work - e.g., whether they are optional or mandatory; whether they are they display-only fields that the challenge owner can use as a visual indication of their plans for starting and closing the challenge or fields that control whether the challenge is visible / whether players can join.

FYI @lemoness @Tressley 
Labels updated.

**Comment by Alys** [comment]
It would be REALLY nice if the end date could be used to make the challenge's Dailies not due once that date is reached (e.g., automatically set the Dailies' `everyX` to zero. A common complaint is that a challenge has ended but the challenge owner hasn't closed it yet, so the Dailies keep damaging the participants or giving them rewards they haven't earned.

Or Dailies could be given an `endDate` field, which would be automatically populated from the challenge's end date at the time that the Dailies were created. A neater solution but requires changes to the Dailies code and schema too. It would also be useful for a player's own Dailies in some cases.

**Comment by Alys** [comment]
Or Dailies could be given an `endDate` field, which would be automatically populated from the challenge's end date at the time that the Dailies were created. A neater solution but requires changes to the Dailies code and schema too. It would also be useful for a player's own Dailies in some cases.

**Comment by lemoness** [comment]
I would also like to see a message sent to the owner of the Challenge the
day after the assigned End Date. That can be part of a different fix if
necessary.

Possible draft of message (with feedback/suggestions welcome):

"The end date of your Challenge NAME has arrived! Close and award your
Challenge from the Challenges Page now." Clicking on it would take you to
that Challenge page.

**Comment by librarianmage** [comment]
Would an end date for all Dailies be useful?

**Comment by Alys** [comment]
An end date for users' Dailies is certainly a requested feature! Some people ask for it so that they can keep Dailies that no longer need to be active (e.g., for pride or auditing).

There's a clear case to be made for some kind of automatic end to be implemented for Challenge Dailies for this issue, and I think end dates are the best option. It would be nice (and simpler) if the same thing was done for user and Group Plan Dailies.

**Comment by lemoness** [comment]
I also like the idea of end dates, because they're something that can be
broadly applied!

**Comment by SabreCat** [comment]
We're tracking odd little pending features like this on a project board, rather than in issue tickets, these days--but I will add this to a list of possible things for @CuriousMagpie to tackle when we'd like!
