### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by locked31** [HabitRPG/habitica#9675]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: e105422c-dc5c-4eb9-82bc-a18e491eef7d
  * Browser: Internet Explorer Ver. 11.0.9600.18838 
  * OS: Window 8.1 Enterprise

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Reddit post (shown below) and was directed here.

"Does anyone use Habitica with IE? We're required to use IE at work (not my choice) and after the UI update I've had to rely on the mobile app. All that shows up in the desktop browser is the flashing logo on a blue background. IE version 11.0.9600.18838 if that helps."

Reddit user "paglias" provided the link that led me here.  I'm not sure if I get stuck before or after login.  All I see is the pulsing Habitica griffin logo on a dark blue background.
#### Console Errors
[//]: # (Include any JavaScript console errors here.)

No errors shown.

**Comment by Alys** [comment]
Thanks @locked31 ! We have this reported at https://github.com/HabitRPG/habitica/issues/9407 so I'm closing this issue but I've copied a link to it from that one. If you'd like to subscribe to notifications whenever it's updated, click the subscribe button in the right-hand column of that issue.

**Comment by paglias** [comment]
@locked31 we've just fixed this! I'm not exactly sure when this will go live but in a few hours the site will load correctly on IE 11
