### ISSUE TITLE
snackbar notifications should not cover the navigation / menu bar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9678]
The snackbar notifications that appear at the top right corner of the website and then disappear after a few seconds should never cover the menu bar. They should start appearing just under the menu bar.

This is has been created for jostein s to work on this fix, based on their comment on this Trello card: https://trello.com/c/684Dv1py/320-in-game-notifications-quiet-notifications-bell-click-to-view-notifications

**Comment by josteins1** [comment]
Know some coding, never used github, but i'll give it a shot!

**Comment by josteins1** [comment]
@Alys 
Ok, so the
**./website/client/components/snackbars/notifications.vue**
height (today at 10px) need to be higher than the main navbar height (today at 56px)
**// ./website/client/components/header/menu.vue**
Some testing on the sourcecode on the webpage shows that an increase from 10px to 65 px leaves a nice result. However, I need access to [this tree](https://github.com/HabitRPG/habitica/blob/506275c30e1a0953d5d447913d4f642d7feb1723/website/client/components/snackbars/notifications.vue) to fix that (habitica/website/client/components/snackbars/notifications.vue)

**Comment by josteins1** [comment]
Cool. When should the commit come into effect on the website?

**Comment by josteins1** [comment]
Oops, still need to change the z value on snackbar to lower than the dropdown menues on header (notifications), sorry about this messy process..

**Comment by josteins1** [comment]
That should be all. Please let me know if/when this is implemented

**Comment by TheHollidayInn** [comment]
Hey @josteins1! Thanks for working on this. You will need to open a pull request from your branch on to our repo. It looks like you have been creating PRs onto your own repo. 

You may be able to create a PR from your develop to ours, but in general you will want to open a single PR with a branch on to our develop branch.

**Comment by josteins1** [comment]
thanks for the response @TheHollidayInn To be honest, I'm not quite shure what im doing here and it's my first experience with github. Just to clarify, is it safe If I delete my repo, fork again, do the changes, commit and then PR? So I can clean up this messy process all together

**Comment by Alys** [comment]
@josteins1 See [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally)
 and [Using Your Local Install to Modify Habitica's Website and API](http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API) for information about developing fixes for Habitica and submitting PRs.

**Comment by josteins1** [comment]
Not what I asked (this happen alot on Habiticas contributing end, is it an american thing? Don't try to be mean, it's just unusual to me), anyways here's the PR.

**Comment by TheHollidayInn** [comment]
You shouldn't need to delete, but it looks like you opened the PR correctly! Thanks :D We will review it.

**Comment by Alys** [comment]
@josteins1 The wiki page [Using Your Local Install to Modify Habitica's Website and API](http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica's_Website_and_API) has a section called "Submitting your Change for Review in a Pull Request" that takes you step by step through the process for creating a pull request, so that's why I linked you to it when you were asking how to do that. I was working from your original questions which were emailed to us all ("To be honest, I'm not quite shure what im doing here and it's my first experience with github. Just to clarify, i've PR my own repo, this is the fault right? Or that I PR twice? If I only affected my own repo, isn't it better to start over? I never did any big changes"). When you edit a comment here, we don't get an email with your new words in it, so if you change your questions, it's a good idea to make a new post.

That link and the other page also have other useful information (for example, it contains a tip about not editing comments).

Can you please add a screenshot to your pull request to show how the notifications work now on your local install?

**Comment by josteins1** [comment]
@Alys Oh I see, my bad. Photo added. I never worked offline, I simply tested by changing the code directly in chrome browser, but managed to snag a photo of that and edit it in the PR
