### ISSUE TITLE
Music/Sound Effects

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#968]
Hasn't been referenced since #76, I think, so I thought I would bring back the idea of music/sound effects in habitrpg. I think it there should definitely be some kind of button that enable/disables music and one for sfx, if sound was to be implemented.

https://soundcloud.com/daniel_medeiros-1/habitrpg-test-idea

Here's a little test idea I came up with. Ideally, I would like to sit down and plan out some better music but I think this is a decent idea of what I have in mind. 

Music-wise, there could be different themes that played according to where you were. Such as individual themes for the main page, stable, tavern, etc. And possibly a number of themes that cycled for the main page.

For sound effects, I was thinking to make different noises for things such as: checking off a daily/todo, spending gold on a reward, finding an egg/hatching potion, +/- sounds for habits, rerolling, using a health potion, hatching an egg, checking into the inn, etc.

Sound is a very important aspect of gamification. It can help immerse them and mentally reward them for their good work. I think that even little additions could be very beneficial to a number of users. I'm going to work on some more ideas whenever I have time and post them.

**::Update:: (1/26/14)**
# **Music & Sound Effects**
- **Sound Effects**
  - [First Sound Effect Ideas](https://soundcloud.com/daniel_medeiros-1/habitrpg-sfx-ideas-1)
  - [Updated Sound Effect Ideas](https://soundcloud.com/daniel_medeiros-1/habitrpg-sfx-updated)
- **Background Music**
  - [Tavern Music](https://soundcloud.com/daniel_medeiros-1/habitrpg-tavern-music-updated)
- **Themes**
  - [Death Screen](https://soundcloud.com/daniel_medeiros-1/death-music-idea-slower)
- **Boss Music**
- **Miscellaneous**
  - [HabitRPG Video Theme](https://soundcloud.com/daniel_medeiros-1/habitrpg-video-theme-idea-1)
  - [Background Music Test Idea](https://soundcloud.com/daniel_medeiros-1/habitrpg-test-idea)
  - [Boss Battle Music Idea](https://soundcloud.com/daniel_medeiros-1/habitrpg-boss-battle-idea-wip)

**Comment by lefnire** [comment]
We're mostly follow up at https://trello.com/card/music-sound-effects/50e5d3684fe3a7266b0036d6/18 at this point. After we fulfill the Kickstarter goals, we'll be tackling feature requests top to bottom by vote-count, which shows sound-effects a bit down the pike in priority. We actually have a ton of sound assets to work with from the CC BrowserQuest library we're using already for most our graphics, which will keep things consistent. It would appear
they didn't release their music (only their sounds), so your soundcloud bit could indeed come in handy - it's quite nice btw, great job!

**Comment by DanielTheBard** [comment]
Ah alright. Well when you get to adding it, if any custom sound or music is desired, I would be happy to create some more. Big fan of the program so I would love to help out.

And thank you!

**Comment by lefnire** [comment]
Stoked you chimed in with a song! Great stuff :) I'll ping you again when
the time comes, if that's ok

**Comment by DanielTheBard** [comment]
Absolutely. I'd love to help.

**Comment by DanielTheBard** [comment]
I got a work-in-progress for boss battle type music. Here it is at 120 bpm and 132 bpm. I originally wrote it for 120 and can't decide which I like better. Maybe, I should aim between them? 124/128?

https://soundcloud.com/daniel_medeiros-1/habitrpg-boss-battle-wip

https://soundcloud.com/daniel_medeiros-1/habitrpg-boss-battle-wip-1

**Comment by DanielTheBard** [comment]
Started trying to work on a possible tavern song but it grew into something too dark, I think. Maybe more suited for death music? https://soundcloud.com/daniel_medeiros-1/death-music-idea

Edit: Plus, a slower tempo version: https://soundcloud.com/daniel_medeiros-1/death-music-idea-slower

**Comment by DanielTheBard** [comment]
Redphoenix suggested making a theme song for the HabitRPG tutorial videos and such. Thoughts? https://soundcloud.com/daniel_medeiros-1/habitrpg-video-theme-idea

Edit: And here it is with some editing to clean it up and put it in stereo.
https://soundcloud.com/daniel_medeiros-1/habitrpg-video-theme-idea-1

**Comment by DanielTheBard** [comment]
Tavern music idea: 
https://soundcloud.com/daniel_medeiros-1/habitrpg-tavern-music

**Comment by DanielTheBard** [comment]
Been at work on sound effects tonight. Gonna consolidate and organize stuff in the first post.

**Comment by DanielTheBard** [comment]
Boom here they are: https://soundcloud.com/daniel_medeiros-1/habitrpg-sfx-updated
1. \+ Habit
2. \- Habit
3. Daily Complete
4. ToDo Complete
5. Reward Purchased
6. Chat Message
7. Achievement Unlocked (Maybe use this as Level Up)
8. Level Up Idea 1 (Probably not use)
9. Level Up Idea 2 (Maybe use this as Achievement Unlocked)
10. Item Drop

**Comment by CrazyPython** [comment]
What about speeding up the boss music as the day grows on, so your more stressed about your dailies?
