### ISSUE TITLE
Equipment name sorting should be alphabetical, not reverse alphabetical

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9682]
When Equipment in your Inventory is sorted by "Name" the sort is reverse alphabetical.
It should be alphabetical (not reverse).

When this is changed, it should NOT change the sort order when you're sorting by attribute (CON, etc). That sort order should have the items with the highest stats at the front.

**Comment by cassidypignatello** [comment]
I can take this one if it's all right!

**Comment by TheHollidayInn** [comment]
Go for it :D
