### ISSUE TITLE
Party members can't contribute to quest progression

### ISSUE THREAD

**Issue by fergatron** [HabitRPG/habitica#9689]
### General info

* UUID: aded2505-59b8-4a98-a16c-8c574829cc4c
* Browser: Chromium / Chrome
* OS: Fedora 27 / Windows 10

### Description

I'm having a problem with my active party members and quests. For some odd reason only one person is able to contribute to the progress of the active quest. No matter how many tasks other members complete nothing is contributed to completing the quest. I've tried two quests and it's the same result-- only one member displays as contributing.

#### Console Errors

No errors displayed.

**Comment by Alys** [comment]
When you experience bugs, the best place to report them is the [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac) guild. We use GitHub issues for problems that need code to be written. See the comments in the [new issue form](https://github.com/HabitRPG/habitica/issues/new) for more details.

In your party's current quest, the quest owner is the only participant. Either the owner or the party leader would have clicked the quest's "begin" button before anyone else had accepted the invitation. The quest owner or party leader can abort the quest. The quest owner will retain the scroll (even if it's the leader who clicks the abort button), and they can use it to re-send invitations to the quest. The quest's "begin" button should not be clicked until all active members of the party have had a chance to accept or reject the invitation (in the notification menu). In fact, if ALL party members accept or reject, the quest will begin automatically and there'll be no need for the "begin" button to be used - that button is only for use if some members don't respond promptly. If you or the quest owner or party leader have questions, you'd be welcome to ask in the "Habitica Help: Ask a Question" guild, which you can access from Guilds on the mobile app or from Help > Ask a Question on the website.
