### ISSUE TITLE
Negative XP / money possible

### ISSUE THREAD

**Issue by Celtis** [HabitRPG/habitica#969]
If you complete a task which causes you to level up and then untick the completed checkbox it removes the XP causing you to have a negative XP amount instead of downgrading the level. 

Negative money is also possible using this same method.

![image](https://f.cloud.github.com/assets/1991686/505878/ed714282-bd3a-11e2-8c15-1dd71f4d9de1.png)

**Comment by AdrienLemaire** [comment]
hmm my case is a bit more serious: I levelled up yesterday, then went to sleep, and this morning when refreshing my screen, I get:

![negative xp](http://i.imgur.com/NsYC203.png)

I was already having difficulties not to die, so I'm a bit disappointed seeing that.

**Comment by lefnire** [comment]
@Fandekasp yours is different, that's #720 . TMK is caused by accessing on multiple computers

**Comment by AdrienLemaire** [comment]
+1 I accessed habitrpg from my smartphone browser. Sorry about that.

**Comment by StanLindsey** [comment]
Don't apologise!

**Comment by paglias** [comment]
I left another bug open about this one

**Comment by Celtis** [comment]
Just a comment @paglias - but if you close issues due to duplication, could you leave a link to the other bug please? Otherwise I (and anyone else) have to search through to find the duplicate to see what's happening with it.

Thanks

**Comment by paglias** [comment]
Yes, @Celtis, you're right. It should be #663

**Comment by Celtis** [comment]
Thank you!
