### ISSUE TITLE
should redirect to Subscription page after creating subscription (PayPal and maybe others)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9690]
When you create a new subscription using PayPal, after the purchase is made, you are redirected to the tasks page (https://habitica.com/ ). You should be redirected to the User Icon > Subscription page (https://habitica.com/user/settings/subscription ) so that you can confirm that the subscription now exists, and learn that that page is where you can view your subscription information. 

This might also happen with other subscription payment methods (Stripe, Amazon) and should also be fixed for them.

**Comment by TheHollidayInn** [comment]
The issue is here: https://github.com/HabitRPG/habitica/blob/e4d006e5cdef1bac0b7704c2b9097b3250e0bc4b/website/server/controllers/top-level/payments/paypal.js#L65
