### ISSUE TITLE
issues with the drop-down that appears when @mentioning an other user

### ISSUE THREAD

**Issue by majestic-owl448** [HabitRPG/habitica#9694]
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Google Chrome Versione 62.0.3202.94 (Build ufficiale) (a 64 bit)
  * OS: Windows 7

### Description
I wrote this in Report a Bug guild and Alys directed me here.
_The list of tags doesn't disappear if you are adding a second mention and then delete the @. And it doesnt appear if you are adding a mention before an other one. But if you have a list of tags that don't want to go away and type before an other mention, then it goes away. If needs more explanation I will try, maybe with screenshots..._

So, issues with a second mention after first one (example `@Alys @Lemoness`)
 - first scenario: starting to type the second mention then changing idea and deleting the mention and the `@`, the list of names stay there hanging. It happens also if you click on a name in the list and then decide to delete it, the list reappear while deleting the letters and then stay there.
 - second scenario: you want to add a second mention before the first one (one of those posts in whichc you write to multiple people and then want to address the first paragraph also to someone else), the list of names doesn't appear.
A thing I noticed is that if you have the list of names hanging there and you type before an other mention, then it disappear.

### Note
For anyone wanting to work on this, most of the work was done in #10638 which was never merged but can be used as a good starting point.

**Comment by Alys** [comment]
labels updated

**Comment by dprice000** [comment]
I would like to take a try at this issue.

**EDIT:** Is there any difference between the old client and new client? Does the redesign affect this issues?

**Comment by TheHollidayInn** [comment]
Please do! This is an issue with the redesign, so there is no relation to the old client.

**Comment by beffymaroo** [comment]
@dprice809 Are you still working on this issue? Please let us know. Thank you!

**Comment by dprice000** [comment]
@beffymaroo  Sorry I am not working on this.

**Comment by beffymaroo** [comment]
@dprice809 Thank you for letting us know!

**Comment by legitmaxwu** [comment]
Hello, could I tackle this issue?

**Comment by TheHollidayInn** [comment]
Go for it!

**Comment by beffymaroo** [comment]
@legitmaxwu Are you still working on this issue? Let us know when you have a moment to check in. Thank you.

**Comment by legitmaxwu** [comment]
Hello, thanks for checking in on me! I submitted a pull request (linked above) and it is currently in review. In the PR thread, I resolved most of the issues but could not figure out a small problem which I described. The PR has been in "ready for review" state for quite a while.

I ended up taking a break from this but it's been some time, so I can pick it up again maybe?

**Comment by paglias** [comment]
I'm not able to reproduce this on Chrome

**Comment by paglias** [comment]
I've added a note at the beginning about the a PR containing most of the fixes that can be used as a starting point
