### ISSUE TITLE
prevent boss damage being cleared when a quest ends

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9698]
Currently, when a quest ends, `user.party.quest.progress.up` and `user.party.quest.progress.collectedItems` are set to zero for all party members.

This should no longer be done. Any quest progress that a player builds up should remain in their account until they go through cron.

This is partly to deal with https://github.com/HabitRPG/habitica/issues/3693 and partly to prevent players feeling unmotivated or disappointed when their quest progress disappears.

**Comment by Alys** [comment]
I'll do this.

**Comment by Alys** [comment]
I'm removing my claim from this. I'm sorry, I should have removed it some time ago. I ran out of time over Christmas and haven't had any spare time since.

**Comment by adamweldonjohnson** [comment]
@Alys is this the functionality handled in test/api/v3/unit/libs/cron.test.js on line 1028?

**Comment by Arsnael** [comment]
Yes I noticed that a few times as well with my party, a bit confusing. Can I look into it? :)

**Comment by Alys** [comment]
@Arsnael Sure, thank you!

**Comment by Arsnael** [comment]
Hi there ! Many cases I see there where user gets its progress being reset : 
* Quest is finished and user was part of the quest (standard case)
* Quest is started and user is not part of the quest 
* User rejects a quest
* Quest gets cancelled/aborted by owner
* User leaves current quest
* Cron

Except for the cron case, should all the other cases not reset the progress anymore? Or is there an exception?

**Comment by Alys** [comment]
I'm just considering options here not trying to give a final answer but it feels like the simplest option and the nicest one for the players would be if cron was the only thing that removed Quest progress.

What do others think?

**Comment by cTheDragons** [comment]
I agree, even it just the simplest to explain to users too. (Also then aligns with how buffs work).

There is a small case when the user leaves a quest or if the quest gets cancelled or aborted. However in both cases it might be nice to not do this. 

Will help with new users joining a party with a quest part way through, they at least keep the damage users have stored for the day. Similarly if a user is switching parties.

Thanks

**Comment by Arsnael** [comment]
Well I agree as well so I started fixing the issue with that angle of thinking. If anybody thinks it's not, he is free to speak his mind of course :)
