### ISSUE TITLE
problems switching Task column filters when Challenge tag (and other tag?) filters are in place

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9699]
_In the Report a Bug guild, AyrenneA (567b94b6-f829-4481-923b-2379b21eb41d) made these posts:_

I am unable to view Completed Challenge tasks in my To-Do list. I click on "Complete" and no tasks show up. Then when I try to click back to "Active," that doesn't work either. It's like the "Active" button is disabled at that point.

_I wrote: "Can you please reload the website while holding down the Control or Command key on your keyboard and post again here to say if the problem still occurs?"_

Yes, this still occurs, but not with all of my Challenges, so that's odd.

The 2nd part of this is that once I click on "Complete" to see completed Challenge tasks, then the "Active" button is disabled. The checkbox and text "These are your To-Dos" have also moved up in the column, into an odd spot (overlapping "Add a To-Do" text). I have to filter for a different tag or reload the webpage entirely to get the "Active" button working again.
![image](https://user-images.githubusercontent.com/1495809/33774581-b84e5f7a-dc09-11e7-94b0-7ead4fe8e29a.png)

_a couple of days later:_

Since I made the initial report, I have discovered that the buttons at the top of the task columns are disabled for me whenever a column is empty (habits, dailies, or to-dos). I first thought the problem was only with the to-do column.

Here's a new screenshot:
![image](https://user-images.githubusercontent.com/1495809/33774598-c417b766-dc09-11e7-8155-7571b5f0e738.png)

I have to refresh the webpage to get things working again.

The buttons that are disabled are the ones that say "All/Weak/Strong", "All/Due/Not Due", and "Active/Scheduled/Complete."

I am using Safari Version 10.1.2 (10603.3.8). Please let me know if you need any more details.

**Comment by Alys** [comment]
After posting that it occurred to me it could be an issue with an extension so I'll ask them to turn off all extensions.

**Comment by Alys** [comment]
_AyrenneA has replied with some excellent details about browsers this fails on:_

Here's what I have found on several computers/OS versions/browsers:

- OS X Yosemite (10.10.5)
   - **Safari Version 10.1.2 (10603.3.8)** I disabled all of the extensions that I have for Safari (ClickToFlash, Adblock Plus, and SafariRestore). **Problem still occurs.**
   - Google Chrome Version 63.0.3239.84 (Official Build) (64-bit) No problem found. Columns and buttons work just fine.
- Windows Vista Home Premium, Service Pack 1
   - **Google Chrome Version 49.0.2623.112 m** Has the same problem as Safari on my Mac - **buttons disabled for empty columns.**
- Windows 7 Professional, Service Pack 1
   - Google Chrome Version 63.0.3239.84 (Official Build) (64-bit) No problem found. Columns and buttons work just fine.
   - Internet Explorer 11 Habitica website did not load & I could not log in (not sure why).

I know I have some old software here, but I believe the version of Safari on my Mac is up to date, and I did not have this problem with the columns and buttons about a week ago, before the last major website update. I normally use Safari for Habitica.

**Comment by Alys** [comment]
The Internet Explorer problem will be this one: https://github.com/HabitRPG/habitica/issues/9407

I'm not sure we can support any browser on Windows Vista since Microsoft has ceased support for Vista.

We'll seek information from other Safari users to see if it's replicatable on similar systems. ([ref for admins](https://habitica.slack.com/archives/C02V10HPE/p1512908884000032))

**Comment by shanaqui** [comment]
User reports that this issue fixed itself quite a while ago and that this issue can be closed!
