### ISSUE TITLE
Customizeable Avatars

### ISSUE THREAD

**Issue by sreeragv89** [HabitRPG/habitica#97]
It would be more interesting if people could customize their avatar based on their likeness

**Comment by ericpgauth** [comment]
I second this! Maybe with avatars from different games or allow options to allow us to make them look like a character.

**Comment by therealnoidea** [comment]
That would be awesome and very motivational because the user has a direct connection to his character.

**Comment by racuna** [comment]
I think this is #77 and a little of #107. But is funny because this issue finish with 7 too.

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
See also request for [Custom Profile Picture](https://trello.com/c/lrIqemFX) and [this comment](https://github.com/lefnire/habitrpg/issues/181#issuecomment-12743635) and the reply following.
