### ISSUE TITLE
Bug with the Undo feature

### ISSUE THREAD

**Issue by Worky** [HabitRPG/habitica#970]
If you complete a task and then undo it and then do this 2 or 3 times in a row for the same task, it gets buggy and marks the task as complete but it does not give you XP and Gold. And if you undo after the bug takes effect then you lose XP and Gold cause the game thinks you haven't completed the task.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! But the undu feature stiil has to be ported, it will probably land in a few days
