### ISSUE TITLE
Unintended avatar item layering consequences (facial hair over the top of scarves, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9700]
Facial hair (beards and mustaches) appear over the top of scarves:

![img](http://i.imgur.com/AtDk9uI.png)
![img](http://i.imgur.com/JbUUvem.png)

This is actually working as expected because the scarves are Body Accessories, and facial hair has to appear on top because most Body Accessories are collars and sashes  which should not cover beards. However for the case of scarves, it looks like a bug.

I think I've also seen another combination of gear/avatar customisations that's technically correct but looks wrong, but I can't think of it right now.

I'm opening this low-priority suggestion-discussion issue partly so that we can point to it as a known bug when players ask about it, and partly in case we want to discuss changes to prevent problems like this.

**Comment by veeeeeee** [comment]
We'll accept this weirdness as a part of the slotting system on avatars, especially as the user can easily remove the avatar customisation that looks wrong.
