### ISSUE TITLE
incorrect active/disabled behaviour for "invite party to quest" button 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9701]
As reported by Conduit (a2eed704-33d9-4c2f-955c-f24af6653c72) in the Report a Bug guild:

"On the inventory page, when selecting a quest, the 'Invite Party to Quest' button is active on the quest overlay, even if the player does not meet the quest's eligibility criteria.
When clicking the Invite button a small, red message appears in the top-right corner to inform the player they do not meet the criteria and the Invite button greys-out.
However, selecting any other quest, or escaping the quest overlay (via keyboard or off-overlay click), leaves the invite button greyed-out until either selecting a different page and returning or reloading; the red eligibility message does not reappear when clicking the greyed-out button.
Presumably the button should recolour whenever a different quest is selected or, better yet, simply be tied to the player eligibility."

**Comment by Alys** [comment]
labels updated

**Comment by BradLugo** [comment]
I can take this. Is the intended design to initialize with the disabled button if they don't meet the quest's eligibility criteria or have the button enabled every time that component is shown

**Comment by TheHollidayInn** [comment]
Sounds good! I believe we want the button to be disabled if the user doesn't meet the requirements for the quest. Each modal would calculated based on the select quest. Sounds like there is an issue with the computed properties there or they aren't being used.

**Comment by beffymaroo** [comment]
@BradLugo Are you still working on this issue? Please let us know. Thank you!

**Comment by beffymaroo** [comment]
@BradLugo Since it's been about a month, I've changed this issue back to Help Wanted. If you come back and it's still available and you'd like to try again, let us know!

**Comment by probaton** [comment]
I can take a look at this. 

I was actually looking at fixing an issue where the start-a-quest modal always pre-selects the first alphabetical quest by key, without checking to see if you even still have the quest scroll. Clicking invite in that scenario has the result described in this ticket, so I might as well pick this up as well.

**Comment by probaton** [comment]
I'm starting to doubt my own sanity but I'm 99.928% certain that I posted comment on this issue about a week ago. I've been patiently awaiting a response but my comment just randomly disappeared after I refreshed for the umpteenth time. 

Anyway; I wanted to say that I don't mind taking a look at this. I already have a branch where I fixed the issue where the invite-to-quest dialog sometimes pre-selects a quest the user doesn't have any scrolls for. As I'm mucking around there anyway I might as well pick this up.

**Comment by paglias** [comment]
Go ahead!

**Comment by Alys** [comment]
@probaton Your sanity is fine. :) I have this in a GitHub email from 11 July:

_"I can take a look at this. I was actually looking at fixing an issue where the start-a-quest modal always pre-selects the first alphabetical quest by key, without checking to see if you even still have the quest scroll. Clicking invite in that scenario has the result described in this ticket, so I might as well pick this up as well."_

I don't see any indication of when it was deleted or whether it did actually appear in this issue's page for anyone but you. `shrug` Odd!

**Comment by probaton** [comment]
@Alys I was actually wondering whether I might have just forgotten to hit send (for an entire week) or something dumb like that. Your confirmation does wonders for my crippled ego.

**Comment by probaton** [comment]
I'm assuming this was apparent, but just in case it wasn't: I fixed it! I'm done fixing the issue described, as well as the little bonus-bug I mentioned earlier. If anyone could spare the time for a review, that'd be most appreciated.

**Comment by paglias** [comment]
@probaton I gave a look at the PR, I think there's a small issue, I've left a comment
