### ISSUE TITLE
Beast Master count of "0" is displayed (probably also for Mount Master and Triad Bingo)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9715]
When you have received the Beast Master achievement but have not yet released your pets, a "0" displays on the Beast Master badge. This is confusing to players who don't yet know that the count increments each time you release your pets. The preferred display is showing the number only when it's 1 or greater.

The same thing applies to the Mount Master and Triad Bingo achievements if they are also displaying a 0 before you've released your mounts / pets+mounts.

Some technical information for the coder who works on this:

When you've obtained the Beast Master achievement, this field in the user's document is `true`: `achievements.beastMaster`

Similarlly for Mount Master and Triad Bingo: `achievements.mountMaster` and `achievements.triadBingo`

When you've released your pets once, `achievements.beastMasterCount` is set to `1` (an integer)
When you've released your mounts once, `achievements.mountMasterCount` is set to `1`
When you've released both pets and mounts together, `achievements.triadBingoCount` is set to `1`

**Comment by TheHollidayInn** [comment]
Is this showing on the profile modal for the user on the achievements page?

**Comment by citrusella** [comment]
For what it's worth: I don't see it on others' profiles unless I'm on the app (and I don't see it on my own because I have a 1+ number).

**Comment by Alys** [comment]
Sorry, I should have logged this in the Android repo! I've moved it there: https://github.com/HabitRPG/habitica-android/issues/921
