### ISSUE TITLE
Windows - eslint error: Expected linebreaks to be 'LF' but found 'CRLF'

### ISSUE THREAD

**Issue by Clement134** [HabitRPG/habitica#9717]
### General Info
  * OS: Windows

### Description
Hello,

Like explained in the guild, I have an issue with line endings on Windows. After following the instructions on the [wiki](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Windows_Line_Endings), I have an error about line endings (Expected linebreaks to be 'LF' but found 'CRLF') when I run the command `npm test`.

After some investigation, I have found where does this error come from. In fact, line endings on the repository are LF, but if git option core.autocrlf is true (like explained in the wiki), git will automatically convert line endings to CRLF on checkout. After that, eslint report errors because it is configured for unix line endings (LF) and it found windows line endings (CRLF).

### Possible solution

Nowdays, many editors detect line endings and add line endings corresponding to those found on the file. So without the option core.autocrlf (the default is false), when checking out the repository, a windows user will get files with LF. After that eslint will not complain about wrong line endings and the user can modify the code (his editor will add LF line endings).

To ensure, no CRLF line endings are pushed to the repository, we can add a .gitattributes file to the repository (like explained in the [eslint documentation](https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems)).

### Console Errors
After running `npm test`: "Expected linebreaks to be 'LF' but found 'CRLF'"

**Comment by TheHollidayInn** [comment]
I've had the same issue. I had to ensure my git settings were correct when install to checkout as CRLF but to commit as LF. If you want to open a PR with the .gitattributes file, that would be great!

**Comment by Clement134** [comment]
Hello @TheHollidayInn , thanks for your reply,

I have open a PR for the .gitattributes file.
With CRLF linebreaks after checkout you didn't  have any eslint errors ?

**Comment by kartikadur** [comment]
@Clement134 I had a similar issue with eslint errors regarding 'LF' and 'CRLF' line endings. I have mentioned a solution in the discussion for issue #9421. Hope it helps.

**Comment by TheHollidayInn** [comment]
@Clement134 Thanks for the PR! I have had many issues, but with core.autocrlf set to true, the Git should revert to LF when committing.

**Comment by Clement134** [comment]
@kartikadur thanks for your help. I have already found the .gitattributes solution. And I think it could be easier for windows users if the .gitattributes is pushed to the repository.

@TheHollidayInn the problem when core.autocrlf is set to true, is the linebreaks errors with eslint, because the local repository contains CRLF after checkout.

**Comment by TheHollidayInn** [comment]
@Clement134 Ah, right, because you are running lint before commiting? I'm fine with never converting.

**Comment by Clement134** [comment]
@TheHollidayInn  Yes, I think it's a good practice to run linting and tests before commiting and pushing to the repository.
Never converting means that you want to push CRLF to the repository ?

**Comment by TheHollidayInn** [comment]
Eh, sorry. I just meant using the default from the repo. But creating a file would cause a need for conversion. The goal is definitely to have LF always.

**Comment by Clement134** [comment]
Ok, in this case, I totally agree with you.

In order to always have LF, we can create a .gitattributes in the repository (PR #9722), and edit the [wiki](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Windows_Line_Endings) to let windows users clone the repository with LF.
