### ISSUE TITLE
Leave Party Does Not Work

### ISSUE THREAD

**Issue by Aaern-the-Blunt** [HabitRPG/habitica#972]
When I try to leave my party, it does not do anything.

**Comment by lefnire** [comment]
how are things working now? It appears all you guys that were experiencing the party chat & leave issues were part of the same party, which somehow to got a `null` id. Additionally, many were part of multiple parties somehow, so it was basically alternating between the two parties which were visible on refresh. I thought a bunch of people were experiencing these issues, but it seems actually you were all part of the same corrupted party. It could be a fluke (which I fixed now by deleting the `null` id party), but I'll investigate further. If anyone experiences this issue that wasn't in a party with @Aaern-the-Blunt , re-open this ticket. (also re-open if still an issue)
