### ISSUE TITLE
only 30 members are shown in the member list for guilds

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9720]
Only 30 members are being shown in the member list for guilds. It's not possible to see more (scrolling doesn't load more automatically and there's no load more link/button).

It's also not possible to see other members by searching if they don't appear in the 30 shown. 

To replicate the bug:
1. Visit the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild which has 800 members.
2. Click the "Member List" box.
3. Scroll to the end of the list.
4. Observe the list stops. If you count the members shown, there's only 30.
5. Search for `ALittleYellowSpider` who is a member in that guild at the moment.
6. Observe that they don't appear.

I've made this a high priority because it makes it impossible in most cases to remove guild members, send messages to anyone who hasn't posted recently, or to have a free choice of a new guild leader.

**Comment by JonLim** [comment]
I'd like to take a crack at this, if that's alright, but am looking for a better way to replicate the scenario of 30+ users in a guild on a local install.

Are there clones of dummy dbs we can use?

**Comment by TheHollidayInn** [comment]
Hello! You are welcome to it. We don't have dummy dbs, but you don't need to create 30 users to test. 

- Try changing the limit in this function to 1 (or any other number) https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/members.js#L271
- Then you will need to update the get group members action to work like the challenge members https://github.com/HabitRPG/habitica/blob/develop/website/client/store/actions/members.js#L40
- Then you can add a load more button like the challenge members, and test the it loads your other members (after you have modified the limit)

**Comment by JonLim** [comment]
@TheHollidayInn Perfect, thanks for that!

I'll get started on this.
