### ISSUE TITLE
Check-in pop-up disappearing within a second after popping up 

### ISSUE THREAD

**Issue by lamelija** [HabitRPG/habitica#9721]
### General Info
  * UUID:  c00b4d2d-b57e-42b2-8581-36afed66e40f 
  * Browser:  Google Chrome, ver. 63.0.3239.84
  * OS:  Windows 10 Home 64-bit

### Description

Alys has asked me to create this issue and copy in our previous posts:

Likarona: "Recently I noticed that my pop-ups disappear before I can even read them. I'm on the web and using Google Chrome. When a new day starts there is always a small pop-up that after about 1 second disappears."

Alys: "Is it just that first popup each day that disappears too quickly or is it all the notifications you ever see? If it's just the first one, can you describe it as best you can? For example, is it large and white and appears in the middle of the screen, or coloured and off to one side? Do you see enough of it to tell us any other details?"

Likarona: "It is the usual small pop-up that appears when starting a new day, the check-in counter I believe it's called. It's small, white and appears in the middle of the screen. It has my characters picture and under it written the usual 'For checking in you get XY' and similar stuff. A similar thing happened when I purchased the last mage equipment, there was a big pop-up, as well in about the middle of the screen, with a white background and stuff written in it, but I've no idea what, for it disappeared within a second or so."

Alys: "When the popups disappear by themselves too quickly, does another popup appear that lets you read it then dismiss it? Do the too-fast popups then later reappear after that and allow you to read them?"

Likarona: "No, there is no second pop-up and no, they don't reappear later either. Once they're gone, they're gone :/"

Alys: "Are you using any browser extensions and Stylish themes that modify how Habitica works in any way? If so, can you disable them for a while to see if that helps? If you're not using any, or if disabling them still doesn't help after a day or two of testing, please tell us what browser you're using, including its version number, and what operating system your computer runs, including version."

Likarona: "No. I'm not using any extension that modify Habitica. I'm using Google Chrome, version 63.0.3239.84. My computer runs Windows 10 Home 64-bit."

Alys: "Tonight, when you finish using Habitica, I recommend that you mark all your due Dailies complete even if you haven't actually done them all (that will be helpful for this test). Then close all browser tabs that have Habitica open. Tomorrow morning, don't go to the usual Habitica URL. Instead, go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there, then when you see the Habitica login page, immediately reload the website using your browser's refresh button while you are holding down the "Control" or "Command" key on your keyboard. After you've done that log in, and then please post here to tell us whether it stops that check-in counter screen disappearing by itself."

Likarona: "Did as you said, twice for good measure. Yesterday the pop-up vanished within a second, today however it stayed for a little longer, for about 2 seconds."

**Comment by lamelija** [comment]
Update: the check-in pop-up seems to have reappeared. Yesterday it came up and stayed, today as well. As far as I can remember I haven't done anything special. I was checked at the inn though and I checked myself out yesterday, but I'm not sure if that is relevant.

**Comment by paglias** [comment]
thanks for the update @lamelija , I'll close the issue but if it happens again just comment here
