### ISSUE TITLE
Success message when the request fail

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9726]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Chrome Version 63.0.3239.84 (Official Build) (64-bit)
  * OS: macOS High Sierra 10.13.2 (17C88)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
I died and because of it i lost a equipment. But when i tried to buy it back i notice that my gold didn't lower. I got a success message, but no gold decrease.

Another point of concern is that the error says that i need to buy the lower version of that first, but what does that means? I don't have the option to buy another weapon beside that one.

![screen shot 2017-12-17 at 19 51 44](https://user-images.githubusercontent.com/3428149/34084266-415024d2-e364-11e7-9a7e-54397b85b769.png)
![screen shot 2017-12-17 at 19 51 38](https://user-images.githubusercontent.com/3428149/34084267-416dbc68-e364-11e7-97e7-40a79bd1d60b.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
```
buyGear.js:46 
Uncaught (in promise) t
httpCode: 401
message: "You need to purchase a lower level gear before this one.
"name: "t"
stack: "t: You need to purchase a lower level gear before this one.
at e.exports (https://habitica.com/static/js/app.f90cbdde95bd72948325.js:1:269284)
at e.exports (https://habitica.com/static/js/app.f90cbdde95bd72948325.js:1:239902)
at s (https://habitica.com/static/js/app.f90cbdde95bd72948325.js:1:607903)
at https://habitica.com/static/js/app.f90cbdde95bd72948325.js:1:610209
at r (https://habitica.com/static/js/vendor.892b09ff4ba641ec4054.js:17:97845)
at Generator._invoke (https://habitica.com/static/js/vendor.892b09ff4ba641ec4054.js:17:98890)
at Generator.t.(anonymous function) [as next] (https://habitica.com/static/js/vendor.892b09ff4ba641ec4054.js:17:98024)
at r (https://habitica.com/static/js/vendor.892b09ff4ba641ec4054.js:17:97845)
at e (https://habitica.com/static/js/vendor.892b09ff4ba641ec4054.js:17:98080)
at https://habitica.com/static/js/vendor.892b09ff4ba641ec4054.js:17:98403"
__proto__: t
```

**Comment by Alys** [comment]
We have this reported at https://github.com/HabitRPG/habitica/issues/9731#issuecomment-354382219 so I'm going to close this issue. Thanks for reporting it though! If you notice any other bugs, I recommend putting a brief report in the Report a Bug guild first because it's rare that a GitHub issue needs to be created.
