### ISSUE TITLE
Register with Google Button not working

### ISSUE THREAD

**Issue by SirLouen** [HabitRPG/habitica#9729]
[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 99ccbddd-9e2c-42b1-a04c-78185183ed25
  * Browser: Google Chrome  63.0.3239.84 (Build oficial) (64 bits)
  * OS: Windows 10 Latest Patch

### Description
[//]: #
In the 
https://habitica.com/user/settings/site

Register with Google Button:

401. That’s an error.
Error: invalid_client
The OAuth client was not found.

client_id=undefined
response_type=token
redirect_uri=https://habitica.com/
state={"network":"google","display":"popup","callback":"_hellojs_7pd7ilq6","state":"","redirect_uri":"https://habitica.com/","scope":"basic,email"}
scope=https://www.googleapis.com/auth/plus.me profile email

#### Console Errors
[//]: 
(Uncaught (in promise) {error: {…}, network: "google"}
Promise rejected (async)
S.async @ runtime.js:244
socialAuth @ 1.ae032c2c62f3e5090c09.js:7292
n @ vue.runtime.esm.js:187
click @ site.vue?d061:1
e @ vue.runtime.esm.js:1979
t._withTask.t._withTask @ vue.runtime.esm.js:1777

**Comment by Alys** [comment]
We have this reported at https://github.com/HabitRPG/habitica/issues/9460 so I'm closing this one as a duplicate. 

If you experience any other bugs, please report them in the Report a Bug guild, which you can reach from the Help menu on the website or the Guilds menu item on the mobile app. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. For more information, see the [new issue](https://github.com/HabitRPG/habitica/issues/new) form here (you can cancel without saving).
