### ISSUE TITLE
Equipment shop errors: some gear is mis-filed, some doesn't appear

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9731]
The Equipment shop is showing more problems than previously and I think it's a new bug from just the past few days.

Base and seasonal equipment for my current class appears correctly when that class is selected from the "Class" drop down.

Base and seasonal equipment for other classes also appears correctly when those classes are selected. BUT the base equipment also appears under "None" (it shouldn't appear there). 

Armoire gear that I've purchased and lost appears under "None" which is correct.

At least some other types of gear don't appear anywhere. For example, the Nameless Helm (head_special_2) doesn't appear anywhere after I've lost it.

There might be other problems too; I haven't done thorough tests.

This is high priority because you can't buy back items that don't appear there, and because any problems affecting seasonal gear are going to cause trouble when the Grand Gala starts this month.

**Comment by Alys** [comment]
In addition, from kawunngg (ce935e7f-00e6-44bc-a44a-5280553810f0) in the Report a Bug guild:

"i can see all equipment of the other classes without being able to buy it back (i know this is intended). i can pin the items to my reward column, and if i have enought gold, i even get the message 'you bought xyz' but i don't lose gold and don't get the items. same thing with equipment of my own class i should not be able to get because i have to buy the beginner items first."

**Comment by Alys** [comment]
fox_town says:
My gala gear is in my rewards column, but not in the market nor the seasonal shop?  Is that as intended? (User in the bug guild has unpinned something from their column and can't get it back, and I don't see a workaround.)
It's not under "None"

**Comment by kawunngg** [comment]
> At least some other types of gear don't appear anywhere. For example, the Nameless Helm (head_special_2) doesn't appear anywhere after I've lost it.

after resetting my account all equipment won in quests don't show and i don't see my crystal armor anymore, so i guess all the gear i would get with contribution tiers would not be visible. other things like my "take this" set or the unconventional armor and subscriber items are still there.

**Comment by Alys** [comment]
For the benefit of anyone working on this issue, I **think** the list of gear below will be sufficient to test all possibilities for lost equipment.  I've tried to choose a thorough selection that should test for all possibilities for code bugs, while not being too large to make testing difficult, but I might have missed an important example so if anyone can see anything that should be included, please comment here. Once this issue is sorted out, we can put the list into the wiki's Equipment page in an "Information for Developers" section to help with future testing.

Set a test account to be either Healer or Mage/WIzard (not Rogue or Warrior!), then set its entire collection of owned gear to be the object below, and then check that all of them appear in the Equipment section of the Shop for purchase with gold. While they should all _appear_, the ones for the class you are not playing should not be purchasable, and the basic gear (head_wizard_2, weapon_healer_4, etc) shouldn't be purchasable until you've bought the earlier ones in the series.

To do a completely thorough test, you should also set your test account to be a contributor of tier `4`, and then in addition to the `armor_special_1` contributor gear that's in the list below, you should also have the opportunity to buy `head_special_1` and `shield_special_1` contributor gear (i.e., **without** them being included in the object below!). However the bug that prevents that happening is logged at https://github.com/HabitRPG/habitica/issues/9179 and it's not critical since it affects a limited number of players and we can do a workaround for each of them when they tell us they're affected, so that specific bug wouldn't need to be fixed in this issue.

```

"items.gear.owned": {
	"armor_special_bardRobes":false, // Check-In Incentive
	"armor_special_candycane":false, // Seasonal Mage gear from first Grand Gala (no indication in name of season or year or class)
	"armor_special_finnedOceanicArmor":false, // gear from a gold-purchasable quest
	"armor_special_gaymerx":false, // free GaymerX gear
	"armor_special_snowflake":false, // Seasonal Healer gear from first Grand Gala (no indication in name of season or year or class)
	"armor_special_spring2015Healer":false, // Seasonal gear from previous year (name indicates class and season and year) 
	"armor_special_turkeyArmorBase":false, // gear given to all players at at special event
	"armor_wizard_1":false, // base Mage gear
	"armor_wizard_2":false, // base Mage gear
	"armor_wizard_3":false, // base Mage gear
	"armor_wizard_4":false, // base Mage gear
	"armor_wizard_5":false, // base Mage gear
	"back_special_takeThis":false, // Back Accessory from TakeThis challenge
	"back_special_wondercon_black":false, // Back Accessory from convention code
	"body_armoire_cozyScarf": false, // Armoire 
	"body_special_wondercon_black":false, // Body Accessory from convention code
	"eyewear_special_aetherMask":false, // eyewear from quest
	"eyewear_special_yellowTopFrame":false, // eyewear, which should actually be set to true automatically so this might never appear as buyable, which would be correct
	"headAccessory_mystery_201502":false, // Mystery Item
	"headAccessory_special_bearEars":false, // Ears that were bought from Avatar Customisation section, iirc
	"headAccessory_special_spring2016Healer":false, // Head Accessory; Seasonal gear from previous year (name indicates class and season and year) 
	"head_special_2":false, // from Legendary quest
	"head_special_nye":false, // gear given to all players at special event
	"head_special_springHealer":false, // Seasonal Healer gear from second Grand Gala (no indication in name of year)
	"head_wizard_1":false, // Base Mage gear
	"armor_special_1":false, // Contributor gear for Tier 2
	"shield_special_winter2018Healer":false, // Seasonal gear from current year
	"weapon_healer_1":false, // base Healer gear
	"weapon_healer_2":false, // base Healer gear
	"weapon_healer_3":false, // base Healer gear
	"weapon_healer_4":false, // base Healer gear
	"weapon_healer_5":false, // base Healer gear
	"weapon_healer_6":false, // base Healer gear
	"weapon_mystery_301404":false, // Mystery Item from the future
	"weapon_special_fall2017Mage":false, // Seasonal gear from previous year (name indicates class and season and year) 
	"weapon_special_springMage":false, // Seasonal gear from previous year (name indicates class and season) 
	"weapon_special_winter2018Mage":false, // Seasonal gear from current year
}
```

**Comment by Alys** [comment]
At least some of this is still broken. For example, when you try to buy this item:
`	"head_special_2":false, // from Legendary quest`
you see this in the Console:
`Unhandled promise rejection  Object { name: "t", httpCode: 401, message: "You need to purchase a lower level gear before this one.", stack: "" }`

**Comment by kawunngg** [comment]
i noticed it too: i could not buy the shaft of the dragon or the nameless helm, but the morningstar. but i did not have enough gold to try again yet and i wasn't sure if it was maybe just some kind of sync error.

**Comment by TheHollidayInn** [comment]
Do you need to buy head special 1 before 2? So then the error is just to show the console message to the user or are there different conditions for buying the head special 2 item?

**Comment by Alys** [comment]
No, you don't need to buy the `*_special_*` gear in order. Different pieces with names matching that pattern come from different sources (e.g., contributor rewards, quests). 

Once you've obtained a piece of equipment and then lost it due to death or reset (i.e., it's in your account with a value of `false`), then it should always be buyable with gold. These are the only exceptions:
- For class-specific gear, you must be the correct class before you can buy it.
- For non-seasonal class-specific gear, you do have to buy it in order.

**Comment by Alys** [comment]
This code is at fault for the "You need to purchase a lower level gear before this one" bug:

https://github.com/HabitRPG/habitica/blob/9545f692efdbea7ff4980c0c7ce20534585363e2/website/common/script/ops/buyGear.js#L40-L48

It should apply to all the items listed below but none others. Also note that the Rogue shields are zero-indexed like the weapons - that's currently not considered in the code either (i.e., you can probably buy `shield_rogue_1` before you have bought `shield_rogue_0`).

```
armor_healer_1	armor_healer_2	armor_healer_3	armor_healer_4	armor_healer_5
armor_rogue_1	armor_rogue_2	armor_rogue_3	armor_rogue_4	armor_rogue_5
armor_warrior_1	armor_warrior_2	armor_warrior_3	armor_warrior_4	armor_warrior_5
armor_wizard_1	armor_wizard_2	armor_wizard_3	armor_wizard_4	armor_wizard_5
head_healer_1	head_healer_2	head_healer_3	head_healer_4	head_healer_5
head_rogue_1	head_rogue_2	head_rogue_3	head_rogue_4	head_rogue_5
head_warrior_1	head_warrior_2	head_warrior_3	head_warrior_4	head_warrior_5
head_wizard_1	head_wizard_2	head_wizard_3	head_wizard_4	head_wizard_5
shield_healer_1	shield_healer_2	shield_healer_3	shield_healer_4	shield_healer_5
shield_rogue_0	shield_rogue_1	shield_rogue_2	shield_rogue_3	shield_rogue_4	shield_rogue_5	shield_rogue_6
shield_warrior_1	shield_warrior_2	shield_warrior_3	shield_warrior_4	shield_warrior_5
weapon_healer_0	weapon_healer_1	weapon_healer_2	weapon_healer_3	weapon_healer_4	weapon_healer_5	weapon_healer_6
weapon_rogue_0	weapon_rogue_1	weapon_rogue_2	weapon_rogue_3	weapon_rogue_4	weapon_rogue_5	weapon_rogue_6
weapon_warrior_0	weapon_warrior_1	weapon_warrior_2	weapon_warrior_3	weapon_warrior_4	weapon_warrior_5	weapon_warrior_6
weapon_wizard_0	weapon_wizard_1	weapon_wizard_2	weapon_wizard_3	weapon_wizard_4	weapon_wizard_5	weapon_wizard_6
```
