### ISSUE TITLE
Enchanted Arrmoire equipment lost to death doesn't automatically unpin when regained

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9746]
As reported by Il Mago Azzurro ( c073342f-4a65-4a13-9ffd-9e7fa5410d6b ) in the Report a Bug guild:

"when you have an Enchanted Armoire item pinned to rewards and you gain it when buying the EA, the pinned item doesn't unpin on its own"

labels updated

**Comment by SheepD** [comment]
I'd love to work on this issue

**Comment by Alys** [comment]
@SheepD Fantastic, thank you! Comment here if you have any questions or run into trouble.

**Comment by SheepD** [comment]
@Alys I'm having some problems replicating the bug locally in a reliable manner. so far i've tried purchasing the lost item on the rewards tab and from the shop, both operations unpin the item. maybe i'm missing something?

**Comment by Alys** [comment]
The bug occurs when you buy the item from the Enchanted Armoire rather than
buying it directly (i.e., you use the Armoire and just happen to be given
the item).
