### ISSUE TITLE
can't see exact date-time of guild/party chat messages (including system messages)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9748]
On the old website, when you hovered over the timestamp for a message in Tavern, guild, or party chat, you could see the exact date and time that the message was posted to the nearest second. This no longer happens in the new website but it is desirable.

For example, seeing exact times on system messages helps the players understand events related to buffs, cron, and quest damage.

It might also have benefits for group plans, for example if a leader wants to know exactly when a member has claimed a task.

Another reason why the exact date can matter, from Dewines:
"we really do need to be able to see the exact time for a variety of reasons. I now can't tell exactly which month someone posted in when I come to close challenges. Many of my challenges ask people to post in the relevant guild, but if someone posts early, I can't tell whether their post counts for the current challenge or whether it was an old post relating to the previous one."

**Comment by Alys** [comment]
It might also have benefits for group plans, for example if a leader wants to know exactly when a member has claimed a task.

Labels updated.

**Comment by Alys** [comment]
Another reason why the exact date can matter, from Dewines:

"we really do need to be able to see the exact time for a variety of reasons. I now can't tell exactly which month someone posted in when I come to close challenges. Many of my challenges ask people to post in the relevant guild, but if someone posts early, I can't tell whether their post counts for the current challenge or whether it was an old post relating to the previous one."

**Comment by Kiwilicious** [comment]
Noticed no one is on this. I'll take a look if that's fine.

**Comment by Alys** [comment]
@Kiwilicious Thank you! Please go ahead.

**Comment by beffymaroo** [comment]
@Kiwilicious Are you still working on this issue? Please let us know. Thank you!

**Comment by Kiwilicious** [comment]
Sorry, I forgot about this. If it's not yet fixed, I'm fine with someone
else taking it from here.
