### ISSUE TITLE
Site accessibility

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#975]
Maybe add a warning when going through maintenance or update. Server stability is very important. I missed to check half my habits and 2-3 dailies because I couldn't access the site yesterday.

**Comment by lefnire** [comment]
I'm going to work today on using a load-balancer to fall back on
beta.habitrpg when prod's not available

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
