### ISSUE TITLE
Can't view/join//edit/close/delete a challenge you own if you've left its private guild/party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9753]
When a user creates a challenge in a private guild or party and then leaves that group, they are still able to see the challenge under My Challenges or Discover Challenges (which is correct) but they are not able to open the challenge into its own page and so they can't use any of the features that should be available on that page (e.g., to close the challenge). When they try to view the challenge, they see the `challengeNotFound` message ("Challenge not found or you don't have access.")

This is because of code like this which checks to see if the user is able to see the group that the challenge is in:
https://github.com/HabitRPG/habitica/blob/3b4b459e6861fd5e1c1abc5471fff95007559ff1/website/server/controllers/api-v3/challenges.js#L502-L503
That code is correct for the case where the user is not the challenge owner, but it should be bypassed for the owner in both that location and probably everywhere else that we have code checking for group permissions.

**Comment by Userbane** [comment]
I would like to try my hand with this issue

**Comment by TheHollidayInn** [comment]
Please do!

**Comment by Userbane** [comment]
I've been getting errors, like the one shown below, on my local version (ver. 4.21.0).
Is this to be expected? If not, I may need help finding where "pushAll" is being used.


![screenshot 6](https://user-images.githubusercontent.com/18677516/35742084-635cc35e-0831-11e8-8aa6-b26246936ee8.png)

**Comment by paglias** [comment]
It looks like you're using mongodb 3.6 which we don't support yet

**Comment by Userbane** [comment]
Which version of mongo is currently supported?

**Comment by Userbane** [comment]
nvm the wikia says 3.4

**Comment by Alys** [comment]
@Userbane Let us know if the information about mongodb's version didn't help or if you have any other questions about this issue!

**Comment by Userbane** [comment]
It was the wrong version. I was using version 3.6 instead of the recommended 3.4.

Sent from my Windows Phone
________________________________

**Comment by Userbane** [comment]
So when I was trying to reproduce the bug, I found that I COULD view the challenge aswell as edit/close/delete, after I had left the party.


![screenshot 13](https://user-images.githubusercontent.com/18677516/36278434-bb6ccec2-128b-11e8-9232-d721252f234a.png)
![screenshot 16](https://user-images.githubusercontent.com/18677516/36278969-7b082f5a-128d-11e8-9495-b93721e2685d.png)
![screenshot 17](https://user-images.githubusercontent.com/18677516/36278498-e782ca52-128b-11e8-8a3e-8eb2be373b84.png)


I feel it is important to note that when this issue was opened, the latest release of habitica was 4.14.1.

**Comment by Userbane** [comment]
@Alys I'm going to have to give this issue up since I am unable to replicate the bug, I would have no idea if I had fixed the issue or not.

**Comment by Alys** [comment]
@Userbane I'm sorry about this! I meant to reply over the weekend and do some testing myself. It's possible that this has already been fixed by a PR that wasn't linked to this issue. I'll post more here when I've done some testing.

**Comment by Alys** [comment]
This has been fixed at some time in the past. @Userbane I'm sorry your time on it was wasted!

**Comment by Alys** [comment]
Reopening this because the bug exists again.

**Comment by Alys** [comment]
I'm working on this.
