### ISSUE TITLE
task wrapping does not occur in Internet Explorer 11 / IE11

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9754]
As reported in the Report a Bug guild by Zian (90145e45-71ca-4c83-8ecf-703e40ccdcda):

"The main text in dailies does not word wrap at all in IE11."

![screenshot_2017-12-30_10-33-06](https://user-images.githubusercontent.com/1495809/34450082-d24b2fee-ed4c-11e7-8925-ca33b2aa2b34.png)

**Comment by rkojima** [comment]
Hi @Alys, if this hasn't been fixed already, I could look into this!

**Comment by Alys** [comment]
@rkojima Thanks! Please do! Comment here if you have questions or run into trouble.

**Comment by rkojima** [comment]
Hmm I didn't realize that trying to get IE11 on OSX is pretty hard... Any suggestions?

**Comment by paglias** [comment]
Microsoft has free virtual machines that you can download to use IE11 or edge

**Comment by beffymaroo** [comment]
@rkojima Are you still working on this issue? Please let us know. Thank you!

**Comment by rkojima** [comment]
Hey sorry, I haven't been working on this. Will probably be best if you take me off this issue.

**Comment by beffymaroo** [comment]
@rkojima Thank you for letting us know!

**Comment by CurlyBraceTT** [comment]
May I take this? Got some experience resolving obscure IE bugs.

**Comment by paglias** [comment]
Go for it @CurlyBraceTt !

**Comment by CurlyBraceTT** [comment]
So, its about flex layout, seems like IE11 has some problems with it.

Possible solutions here:
https://stackoverflow.com/questions/35111090/text-in-a-flex-container-doesnt-wrap-in-ie11/35113633
Root issue I believe is here:
https://caniuse.com/#feat=flexbox

Will submit PR soon enough
