### ISSUE TITLE
"Discover Guilds" search function shouldn't deprioritise the most relevant results - suggested improvements to search mechanism

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9755]
_EDIT May 2018: Using a mongodb text index might be better than anything I wrote below. https://github.com/HabitRPG/habitica/issues/10242#issuecomment-386858117_

In https://github.com/HabitRPG/habitica/pull/9575/files, the guild search feature was changed from a phrase search to an `or` regex search.  We definitely still want that change because it fixed some troublesome search bugs and allowed for multi-keyword searches, but it has the disadvantage that if you search for the full, correct name of a guild, that guild can appear far down in the search results. For example, if you search for "bug" or "report bug", then the "Report a Bug" guild appears near the top of the results, but if you type "report a bug" into the search box, that guild appears far down the page.

There's a few ways we could improve this.

Firstly, stop words probably shouldn't be included in the search terms, so if you enter "report a bug", the regex search would be only `report|bug`. Stop words are likely to be implemented for quest shop sorting in https://github.com/HabitRPG/habitica/issues/9361 so we can presumably reuse that code.

Secondly, it would probably help if the full phrase that the user typed was used as one of the regex entries. So if you enter "report a bug", the regex search could actually be `report a bug|report|bug`.
Alternatively, the search results might be more useful if we did two separate searches with the results combined on the same page. The search results at the top would be from an exact phrase search for `report a bug` and the results under them would be from our current `or` regex search for `report|bug` (the full phrase wouldn't need to be included)
We could even get more tricky and do three searches: exact phrase, then an `and` regex search, then the current `or` regex search (i.e., you'd see first the "report a bug" guild, then you'd see any guilds that contained both "report" and "bug" in their texts, then you'd see guilds that contained either "report" or "bug" in their texts).
However we'd want to test to see if that returned results more slowly than it's worth - my feeling is that the improvement in quality of the results would be worth the slowness, especially if we could display the initial results while the later ones were still being found. We'd also want to make sure it didn't put too much extra load on the database, but as a guess, guild searches are probably not common enough for that to really matter.

In addtion, we should reduce multiple consecutive whitespace in the user's search terms to a single literal space. E.g., if you typed "report[space][space]a[tab]bug" the search would be done as if you'd typed "report[space]a[space]bug" (that would be important for the phrase search).
We should also change the current regex so that instead of `split(' ')` it splits on whitespace of any kind, with consecutive spaces treated as a single splitter - e.g., `split(/\s+/)`

Related to that, currently if the search term you enter is "report " (with a trailing space) your returned results are enormous because (I assume but have not tested) the regex is `report|` (note the trailing pipe). The same problem occurs with a leading space. Leading and trailing whitespace should be ignored when doing phrase searches and when splitting the search terms.

~I'm going to leave this open as suggestion-discussion for a few days and then if there's no complaints or better ideas, I'll mark it as help welcome.~

**Comment by Alys** [comment]
Something similar should be done for Challenges too, so we could implement the search code as a reusable function.

**Comment by Alys** [comment]
When a player has their language set to non-English, we should probably use their language's stopwords AND English stopwords for searching (since they could be searching for either language-specific guilds/challenges or guilds/challenges written in English).

**Comment by Alys** [comment]
It would also be helpful if matches to the name of the guild were prioritised more than matches to the description. For example, we currently have five guilds specifically about YouTube but if you put "YouTube" into the guild search, the list shows 38 guilds, most of which just happen to mention "YouTube" somewhere in the description. Big guilds like Life Hackers, Procrastinators, ADHDers dominate the list and the new guilds devoted to YouTube are right down at the bottom.

As well as making it hard to find a guild about YouTube, this adds to the problem of players creating a new guild for a topic that already has one.

_(Thanks to cTheDragons and Dewines for pointing this out; I've stolen many of Dewines words for this comment. :smile: )_

**Comment by cTheDragons** [comment]
Would it be better instead of searching the description but searching the summary and title only? There are many things in a guild description, most of which don't apply. For example I search witch and get Scholars as my first option, the first applicable guild is halfway down.

It should be noted that the pirate will be soon tackling the last of captains who have gone missing since the great change of Habitica. So all captains ~~leaders of guilds~~ should be well aware to update the summary by now. (Though it would be nice if they are displayed on the apps instead of the description when browsing - However the android only searches guilds by title only currently). 

It should be also noted that there has been a tool created to allow mass PM to all guild leaders who have failed to update their summary (and categories) that can be used by Admin.

**Comment by shanaqui** [comment]
It's worth noting that if you search for "Report a Bug", as we often ask people to do in admin inbox, it is far down the list below things like "Tabletop Gamers".

**Comment by bigsee** [comment]
I'm going to take a look at this, per the suggestion from @paglias [here](https://github.com/HabitRPG/habitica/issues/11304#issuecomment-671067945). I'll shout if I get stuck. :)

**Comment by Alys** [comment]
@bigsee great, thanks! I've marked it as in progress for you

**Comment by bigsee** [comment]
Quick update: just got back from holidays. I'm still on this. Will likely be spending some more time this weekend.
