### ISSUE TITLE
Hair Style, Bangs, and Flower should always have square box to show selected options

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9756]
In the Avatar Edit screens, when you first select one of the options for Flower or Bangs or Style (hairstyle), the item is correctly surrounded by a square box to show you which one you're using, like this:
![screenshot_2017-12-30_15-33-22](https://user-images.githubusercontent.com/1495809/34451604-c41c0b80-ed76-11e7-80c8-61bf705006c8.png)

However if you reload the website and then go back to that section of Avatar Edit, the item selected no longer has the square box (even though the selected item is still in use on your avatar). The desired behaviour is that there is always a square box around the Flower, Bangs, and Style that you are using.

The hair Color screen does not have this problem (the square box always correctly indicates which colour your hair is) so looking at its code might be a good way to work out what's wrong with the Flower, Bangs, and Style code.

**Comment by iabrenne** [comment]
May I please give this one a try? This would be my first contribution to Habitica :fearful: :smile:

**Comment by Alys** [comment]
@iabrenne Please do, thanks! Comment here if you have questions or find problems.
