### ISSUE TITLE
antidotes for avatar transformation buffs should not allow multiple purchases (salt, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9758]
When a [Transformation Item](http://habitica.wikia.com/wiki/Transformation_Items) such as Snowball is used on you, the antidote (e.g., Salt) appears in your Rewards column to buy with gold. That works correctly, however the buy modal gives you the option to buy multiples, which isn't helpful and will be confusing (e.g., makes the users think they can store salt for use later). 

The buy modal should not have the text "How many would you like to buy?" or the field for selecting a number.

I'm labelling this as high priority since people will be using it a lot at the moment.

**Comment by binary404** [comment]
i would like to work on it. i know some java, html, css and javscript

**Comment by TheHollidayInn** [comment]
Please do!

**Comment by lemoness** [comment]
@thecrazycoder01 Hi there! How is progress going on this ticket?

**Comment by Alys** [comment]
@thecrazycoder01 There'll be a transformation buff released soon so we'll want this fixed in the next week or so ideally, so I'm going to open this up for someone else to work on it, but if you have a fix part done already and would like to keep working on it, please comment here and I'll mark it in progress for you again.

**Comment by caleb-fung** [comment]
I would like to work on this. 

I've been testing out the Mongo file. I also have intermediate experience with component-based webdev (React, Angular, and Polymer) and Mongo.

**Comment by Alys** [comment]
@CalebFung Thank you! Comment here if you have questions.

Labels updated.
