### ISSUE TITLE
Error with proxy requests

### ISSUE THREAD

**Issue by Kiwilicious** [HabitRPG/habitica#9764]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
  * OS: Ubuntu 16.04 LTS

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
This issue is similar to issue #9119 with the login page looking exactly the same. `npm run client:dev` and `npm start` are running in separate terminal tabs.

Running `npm run client:dev` compiles fine but gives error messages
```
(node:31535) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
before compiling and
```
[HPM] Error occurred while trying to proxy request /api/v3/i18n/browser-script from localhost:8080 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
when accessing `localhost:8080` including reloads to the page. The console for chrome spits out this error ` http://localhost:8080/api/v3/i18n/browser-script 504 (Gateway Timeout)`. When doing any other action such as registering, an error pops up on the console and the `npm run client:dev` tab.

`localhost:3000` doesn't load at all. 

When running `npm start`, the following error message pops up and continously cycles through ports? every few seconds.
```
(node:30428) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at cb (net.js:1327:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2018-01-04T05:43:46.243Z - info: [Wed Jan 03 2018 21:43:46 GMT-0800 (PST)] [master:30422] worker:30428 disconnect! new worker:30439 fork
```

**Comment by paglias** [comment]
The problem seems to be this error 

```
Error: bind EADDRINUSE null:3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at cb (net.js:1327:16)
```

It means that another process on your computer is using the 3000 port so it cannot be used by Habitica. You should kill that process or change the port used by Habitica by changing the `config.json` file

I'm closing this issue since it doesn't seem a problem with our code but let me know if you still have problems
