### ISSUE TITLE
mobile website: Menu can't be scrolled down (can't acccess User Icon, sync button, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9768]
When viewing the website on a phone's browser, unless your phone screen is long, some of the menu entries can't be accessed. They don't appear on the screen and the menu can't be scrolled down to get to the hidden ones.

Here's a screenshot from Birkwelch (310aea01-13f5-4fb6-929e-be39d63e665b) who says "I have a Samsung J7 Galaxy Perx, and the issue occurs both in the Samsung internet browser and in Chrome. If you open the menu, I believe the user icon would show at the bottom, but you can't scroll down to see or reach it... instead, the tasks behind the menu scroll instead."

![Screenshot with menu open](https://i.imgur.com/oPbhz8x.png)

Here's what it's like on my phone:
![screenshot_20180106-082947](https://user-images.githubusercontent.com/1495809/34631475-42fd7c1e-f2bc-11e7-852e-598993a933b1.png)

Related to that, as a suggestion, the Gems, Gold, and Hourglasses could be hidden in the drop-down menu when using a mobile browser. It's kind of weird to see information like that in a menu. Perhaps on the mobile website they could be moved to the part of the header that's visible before you tap on the menu icon. On some phones, that would allow all menu items to be accessed without the need to scroll, so it would be a usability improvement for some people.

**Comment by lemoness** [comment]
I've updated the labels on this ticket!

@Tressley may want to weigh in on the discussion of the placements for gems, gold, and hourglasses.

**Comment by lemoness** [comment]
Is this still happening?

**Comment by Alys** [comment]
Yes, it's still not possible to get access to all of a menu on a small screen. An especially critical part is the log out entry - i.e., you can't log out of the website on a small device. This is troublesome because you might have logged in on someone else's device if you were trying to persuade them to use Habitica.

**Comment by probaton** [comment]
I don't mind taking a stab at this. Making the menu scrollable is pretty easy, let me know if you also want someone to take a look at moving menu items, either within the menu or out of it entirely.

**Comment by Alys** [comment]
@probaton thanks! Comment here if you have questions.
