### ISSUE TITLE
no search box in challenge Select a Participant drop-down member list

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9771]
On an active challenge, when you click the "Select a Participant" drop-down, the participant list that appears should have a search box at the top of it. Currently, the search box isn't displaying. 

I'm pretty sure this is a recent bug (just in the past month maybe?). It's possible that the search box is still there, just hidden by other interface elements.

For clarity, since there's three participant lists for challenges, this is the "Select a Participant" drop-down I'm referring to:
![select a participant](http://i.imgur.com/oK3qqSq.png)

&nbsp;

This is what the top of the list currently looks like:

&nbsp;
![top](http://i.imgur.com/z8CZP1N.png)

**Comment by citrusella** [comment]
As far as I know (at least unless something fixed it and then something re-broke), the dropdown there has always looked like that, with no visible search box. (I think I remember it being reported shortly after the redesign, or maybe even during the beta.)

**Comment by TheHollidayInn** [comment]
The search bar is hidden when you have 20+ users. The drop down needs.css to keep it below the field and/or we need to show less results.
