### ISSUE TITLE
Renewal of Dailes #2

### ISSUE THREAD

**Issue by Pacerparty** [HabitRPG/habitica#978]
I don't know how to update and reopen a closed issue so i open a new one.

Continuing from here: https://github.com/lefnire/habitrpg/issues/950

Update:
Ok, i just logged in (1 am here) and my dailies haven't renewed!
This is so  demotivating. And i did so many things today. :(

That means that still if i make any actions between 00:00 am and 4:59 am there is a problem.
I logged in Thursday around 2 am and did all my actions. I've set my day to change at 5 am. Now i logged in (Friday 1 am ) and my dailies weren't renewed. And the strange thing is i didn't lose any hp. As if game time has frozen.

**Comment by lefnire** [comment]
got it. re-opened that one, i'll close this one and post this info there
