### ISSUE TITLE
new Bailey message not appearing even after reload

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9785]
As reported in the Report a Bug guild by Anysia (db190b28-8ce5-422e-8076-d43a62a7b204):

Anysia: "I never get the current Bailey message, I?m always one behind. Today I got the one for the 4th even though, based on Habiticas Tumblr account, there should be a new message out. This has been happening since the redesign."

Alys: "If you reload the website using your browser's refresh button does that cause the new Bailey message to appear? If a simple reload doesn't, then does the new message appear if you hold down the 'Control' or 'Command' key on your keyboard while refreshing?"

Anysia: "No. Nothing makes it show up unless I dismiss the old message and then go into Settings and click Show Bailey. I'm using Safari 11.0.2 on Sierra OS (10.12.6)."

**Comment by TheHollidayInn** [comment]
The fix for this is in the Notifications PR now and is currently being tested internally.
