### ISSUE TITLE
sort problems in Dailies (not from tasksOrder errors)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9787]
We see quite a few comments like the ones below, although I can't reproduce this at all. This might be fixed by the fix for https://github.com/HabitRPG/habitica/issues/9582 but I'm recording it here to remind us to investigate it if it still happens after https://github.com/HabitRPG/habitica/issues/9582 is fixed.

----

Chandramani Adil (Auror) (58de0b72-3af8-4f2a-b9a1-f7d196b29757): "I am trying to arrange my dailies in all view, but after dropping a daily from one place to another the view automatically shifts to due tab, and dailies are getting swapped here and there. Please help me through this issue."

Alys: "We do have an issue logged to get that all/due filter problem fixed and I"m hoping that once that's done it will fix the sorting error. In the meantime, are you able to do any of the sorting in the due tab? Does that allow the sort order to stay the way you want it?"

Chandramani Adil (Auror): "sorting the dailies do not work on the due tab, rather after swapping refresh occurs and the intermediate dailies between the swaps too get their position changed."

----

CeeCee (1ecaee1e-8ea7-43b2-bf07-a280ef83fa7b): "when I'm trying to rearrange my daily list, after adding a new task, the whole practice has become a nightmare! If I try to move a task, sometime it drops down where I didn't drop it, some other task will me moved randomly as well, and sometimes, the other of several tasks at once will be totally messed up. If I try to move one task, I can end up fighting with 5 others, trying to get them back to where they should be, without even more trying to get involved! Please halp! D: (Using Windows 10, Firefox)"_

SabreCat: "As for the task ordering trouble, two things: (1) make sure you don't have any filters active (tags, "Scheduled" list of To-Dos, etc.) when you're moving things around. (2) Log in to the Task Adjustor at https://oldgods.net/habitica/task_adjustor.html ; copy any warnings it gives you here and we may be able to do some backend cleanup to make your tasks behave better."

CeeCee: "I can confirm that none of the filters are active when I'm trying to reshuffle my dailies. I logged in to the Task Adjuster, but I didn't see any warnings anywhere; I tried readjusting some tasks (they still jumped around and got jumbled), then checking again, but I still didn't spot any; either there aren't any warnings at all, or I need to do something specific in order to view them?"

Alys: "We do have a known problem with sorting Dailies in the "all" view switching you back to the "due" view and that seems to stop the sorting working properly. We have an issue logged to get that all/due switch fixed and I"m hoping that once that's done it will fix the sorting error. In the meantime, are you able to do any of the sorting in the due tab? Does that allow the sort order to stay the way you want it?"

CeeCee: "I have actually been doing ALL of my sorting in the "Due" tab and that's where things get crazy and jumbled. I noticed that in "All", "Due" AND "Not Due" it refreshes/syncs after every 2 dailies that I move (presumably this is intentional, though here, I can't be sure...), then switches me back to the "Due" tab as you mentioned, regardless of which tab I'm on. For science, I tried arranging my dailies in the "All" and "Not Due" tabs. Both did the refresh/switch back to "Due" thing, but neither jumbled my list; and quite frankly, simply scrolling back up to switch it back to "All/Not Due" is WAAAY less annoying than fighting with the jumbled mess on the "Due" tab. Is anyone else able to replicate this?"

----

Lemoness (7bde7864-ebc5-4ee2-a4b7-1070d464cdb0):

"Good (?) news -- My Dailies are being affected by one of the non-fixable [sorting] bugs right now! It's also causing the "jumps back to Due" bug: https://github.com/HabitRPG/habitica/issues/9582Details:
- Alys has already confirmed that this is not a case of the taskOrder bug
- I am on Safari
- This is occurring on both staging and prod
- This is happening both when I have tags and filters applied and when I do not
- Console is as follows:
```
[Warning] Deprecation warning: moment().zone is deprecated
	[snip usual unrelated moment error]
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (favicon.ico, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (favicon_192x192.png, line 0)
[Warning] The page at https://habitrpg-staging.herokuapp.com/ was allowed to display insecure content from http://i41.tinypic.com/2pyqlq8.png. (vendor.af6f36c7e39705b90de9.js, line 1)
```
Let me know if there are helpful things that I can test and questions that I can answer!

**Comment by TheHollidayInn** [comment]
Just to note, there are some Vue lifecycle methods that push the filters. Looking at the vue lifecycle methods in the userTask page would be a good start. 

Also, there may be some benefit to normalizing the data in that page and explicitly pushing through the different user scenarios, but this is a generic approach :P

**Comment by TheHollidayInn** [comment]
I believe this is related #9582

**Comment by Alys** [comment]
Chandramani Adil (Auror) reports:

"I discovered something really interesting about the bug which I recently reported here about the inability to reorder the dailies where reshuffling the dailies was not working the way it should, view automatically shifting to the due tab and dailies moving to random position. What I did was that I went to settings and unchecked the option **Set Dailies default to 'due' tab** and now I am able to shuffle dailies in all the three tabs with no problem."

**Comment by TheHollidayInn** [comment]
I've suggested this to a few users. I'm pretty sure the issue is with the lifecycle events and setting the due filter

**Comment by lemoness** [comment]
Are these still occurring?

**Comment by Alys** [comment]
I didn't recall seeing it at all frequently when I was doing the Bug guild on most days. Some (all?) of the problems could be due to various things that have been fixed relatively recently on the website and apps. It can be reopened if more reports occur.

(The unrelated tasksOrder sorting problems still happen, although rarely.)
