### ISSUE TITLE
attribute / stat points allocated before level 10

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9788]
In the Report a Bug guild, Orruzza Ogam Li (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) writes:

"Is it intended that now it's possible to allocate points at levels 1-9?
Before the redesign one got 10 points to allocate after reaching level 10, before it wasn't possible, I don't know if this is an intended change or not..."

I believe it's not intentional.

From other comments I've seen, the first 10 points might be allocated automatically sometimes? It might depend on which allocation method you have selected (probably from before the new website since you can't change it on the website now).

If no one jumps on this issue soon to sort it out, I'll do some investigation to clarify what's going wrong.

**Comment by majestic-owl448** [comment]
About this see also: https://github.com/HabitRPG/habitica/issues/6482#issuecomment-343167628
It's an experiment I did some times ago...

**Comment by TheHollidayInn** [comment]
This seems to have been fixed.
