### ISSUE TITLE
keyboard (tab button, etc) can no longer be used to complete tasks, buy Rewards

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9796]
_I have a feeling we have this recorded or being worked on elsewhere but I can't find it. If anyone knows it's a duplicate or in progress, please add a comment._

As described in the "Use of Tab" section in [Accessibility](http://habitica.wikia.com/wiki/Accessibility), the old website had more features that were accessible through the keyboard than the new one. citrusella, the serving wench wrote in the Report a Bug guild:

"Out of the things listed in the article, the elements for checking off a task/reward can't be tabbed onto."

"(For extra reference, they also can't be accessed using the "show numbers" command in my computer's stock speech recognition software (a command that displays the "number" of each selectable piece on a page for easy voice selection), which I believe uses the same logic for choosing what's selectable; I know in the past that "show numbers" did include the checkoffs/plus/minus/etc. (though it was unmanageable because there were too many in that case) but in the new interface there is very little of the task area available for selection that manner.)"

"The accessibility Trello card has had what feels like an uptick in people asking keyboard accessibility, so while it's not clear they've run into this change specifically, there's definitely demand for keyboard navigation, both for people who just want it and those who need it."

**Comment by Alys** [comment]
Note that allowing activiation of the task completion features using "show numbers" might be a better option than using tab, since that would require a LOT of tabbing in long task lists.

**Comment by kbdluv** [comment]
Throwing my vote in for making sure things play nice with Vimium.

"Mark as done" checkboxes are currently a `div>svg`. I'm no expert but I _think_ that wrapping the `svg` in a `<a>` might make it "visible" to Vimium as a link.

Thank you for Habitica and for considering keyboard accessibility important <3

**Comment by ianoxley** [comment]
Can I help out on this one please? I'd like to have a go at making clickable things into `<button>`'s and `<a>`'s, and maybe add some skip links to aid keyboard navigation.
