### ISSUE TITLE
when changing class, you can't see which class is which if you have an avatar transformation buff (Snowball, Shiny Seed, Seafoam, Spooky Sparkles) 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9798]
When you are affected by an avatar transformation buff (e.g., Snowball), and you try to change class, this happens unhelpfully:

![img](http://i.imgur.com/RCcwg0H.png)

What should happen is that the avatars you see are not affected by the buff.

**Comment by jzhou69** [comment]
Can I take this as a first issue? It seems setting `showVisualBuffs` to `false` when creating avatars from this page fixes the problem.

**Comment by Alys** [comment]
@jzhou69 That would be great, thank you! Comment here if you have questions or run into trouble.
