### ISSUE TITLE
Several Suggestions

### ISSUE THREAD

**Issue by the-economancer** [HabitRPG/habitica#98]
I've been working on something similar to this, but have lacked the expertise and time (or rather, I haven't made it a priority) to get it quite this far. Given my track record with completing projects like these, I feel I can pass on my ideas, since I doubt I'll get around to them.
I've browsed through a few suggestions, and from what I've seen these are "original", but forgive me if there are any that I've missed.

First, a library of tasks and rewards, compiled from other users, that you could search through and add to your own "character sheet" (or whatever you're calling the interface) would be helpful in giving people ideas for what they want to do. This would also be very useful in standardizing tasks and rewards between users for analytic purposes. It would also help users determine the appropriate price for certain common rewards (or at least, categories of rewards), as this price could be calculated as an average of what other users have set (preferably those of a similar level and with a similar number of tasks earning coins). 
In addition to this library, categorizing tasks and rewards would be beneficial for several purposes, including analysis (i'm an economics/math/data analysis geek, so obviously that's my first thought), and the possible implementation of a character classes. Categorization would most easily be accomplished in a user tagging system, and the library could be organized according to these either pre-defined, or user generated tags.
Speaking of classes...I noticed someone else had suggested this, and that it was being considered. Classes would obviously be related to types of tasks accomplished (fitness - warrior class, academic goals - a magic using type class, literary and musical tasks - bardic class, etc), these tasks being largely standardized via the library. Classes could then either be assigned based on what the user accomplishes, or alternatively, the user could select a class as a goal, and either earn extra experience for tasks associated with that class, or perhaps level the class separately (gaining standard character exp, as well as class exp). This has the advantage of making multi-classing a premium via tokens, if you want to go that route.
_deep breath_
Next up, and I'm sure this has been suggested somewhere, but an obvious feature would be quests based on to do's with dependencies. Users could create quests for themselves, or post challenges for others with reward values based on the difficulty, number of sub-tasks, and possibly adjusted for player levels. This would also permit "sponsored" quests, where companies/groups could post challenges/quests, and be featured somewhere on the character sheet or prominently on a quest page, for a fee of course.

I have a lot more ideas, many of them a bit more technical in nature. I'll wait for feedback on this tip-of-the-iceberg and to get more familiar with things before taking up too much more space.

**Comment by Nelmalih0** [comment]
I say +1 on adding tags to rewards so you can have different categories of rewards, it would be easier to handle if you have a lot of rewards

**Comment by horusofoz** [comment]
@the-economancer Can you agree that your recommendations fall under the following labels?
- Library of Habits/Dailys/Todos/Rewards anonymously crowd sourced from users' databases for the purpose of providing inspiration to other users. 
- Categorisation or tagging of tasks/rewards for analytical purposes and easy identification. See #48 and [Trello 43](https://trello.com/c/q7v02jAw).
- An RPG class system. This will be tightly linked to a skill system. See #195 and for my take see this [comment](https://github.com/lefnire/habitrpg/issues/195#issuecomment-12710155) in the thread.
- Quests. "[Incremental Quests](https://trello.com/c/Cld8EjME)", "[Cross Profile Challenges/Quests](https://trello.com/c/k0kSlT0Q)" and "[Community Challenges/Quest](https://trello.com/c/qRmRIYDd)". If you check out the [Trello Board](https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6) you'll see there are a few other related ideas.

With the above in mind it would seem adding a card to Trello for your idea of a library of tasks and rewards would ensure your suggestions are on "on the board". Once that card is up are you cool with this ticket being closed?

**Comment by the-economancer** [comment]
sure

**Comment by horusofoz** [comment]
@SlappyBag Can you please raise a Trello card for "Library of Habits/Dailys/Todos/Rewards anonymously crowd sourced from users' databases for the purpose of providing inspiration to other users." and reference this thread?

**Comment by StanLindsey** [comment]
https://trello.com/c/dwIeOjZQ
