### ISSUE TITLE
Click to clear a Daily or Habit or Todo does not work.

### ISSUE THREAD

**Issue by eri401** [HabitRPG/habitica#980]
When you click to clear any item, I should see a check mark beside the item and see some  changes in my health/experience/coins in my stats bar. For a Daily or Habit, the color of the item will often change and the Todo will clear from the list.

However, lately only the check mark appears but nothing else changes.  Meaning, there are no changes to my stats, the item colors, or the Todo list.   

Unclicking and retrying does not help.  Nor does refreshing the page. I usually take the hit and wait to try the following night.

**Comment by lefnire** [comment]
noted. Any Chrome Console javascript errors?

**Comment by eri401** [comment]
I don't know how to check for Chrome Console javascript errors.  Where should I look?

**Comment by PhilipHow** [comment]
https://developers.google.com/chrome-developer-tools/docs/console#opening_the_console

Keep that open while navigating around the site, checking Todos etc, and see if anything is shown.

Thanks for your help!

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
