### ISSUE TITLE
locked off-class-specific basic equipment shows wrong error message

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9800]
When you pin class-specific basic gear and then change class, and then try to buy the pinned gear from the Rewards column, you see the wrong error message. It says "This item is only available once you've purchased the previous items in sequence. Keep working your way up!"

It should say "This item is only available to a specific class. Change your class under the User icon > Settings > Character Build!",

_EDIT_: As @Ieahleen says in the comment below, this also happens in the Market and should be fixed there too.

![img](https://i.imgur.com/aSs8TWo.png)
The player who took that image was a Warrior (it's Rogue gear).

**Comment by majestic-owl448** [comment]
this happens also in the Market for items of other classes (Seasonal gear shows the correct message, the base equipment instead have this one)

this profile is an healer:
![image](https://user-images.githubusercontent.com/26656284/34905671-25e37730-f85e-11e7-9fec-fa73840b0f96.png)

**Comment by Alys** [comment]
Thanks @Ieahleen ! I missed that. I've updated the title and top post.

**Comment by harakuri** [comment]
Hey y'all, could I work on this one?

Thanks!

**Comment by Alys** [comment]
@kuriharak93 Please do, thanks! Comment here if you have questions or find problems!

**Comment by harakuri** [comment]
Hey @Alys, sorry I've been dragging my feet on this one. Pretty sure I know the issue -- guess I'm just not quite sure of the solution.

The issues comes from the [attributesPopover.js](https://github.com/HabitRPG/habitica/blob/develop/website/client/components/inventory/equipment/attributesPopover.vue#L5) in this code snippet:
``` 
 div(v-if='item.locked')
    h4.popover-content-title {{ `${$t('lockedItem')}` }}
    .popover-content-text(v-if='item.specialClass') {{ `${$t('classLockedItem')}` }}
    .popover-content-text(v-else) {{ `${$t('tierLockedItem')}` }}
    p
```
For most of the class-specific items, besides the seasonal ones, specialClass is not populated, so if it is locked it will end up showing the 'tierLockedItem' message.

There's a couple solutions that I've thought of (in order of what I think is most to least desirable):
- Pass the user object to the `attributesPopover.js` code so the user's class can be compared to the item.klass property
- Update the `specialClass` property of the item if it is locked and it is not the same as the user's class (not sure what the specialClass property is used for other than this check)
- Apply the specialClass property to all items from the beginning (if a class ever changes, every item would need to be updated)

Let me know what you think! In the mean-time, I'll see if I can get the first solution working -- just have to figure out how all the Vue stuff is working.

**Comment by Alys** [comment]
@kuriharak93 No worries, we understand that real life gets in the way. :)

I think you're right that comparing the user's class to the item class would be best, but I'm not strong on our Vue code. @TheHollidayInn or @paglias or @SabreCat what do you think?

**Comment by paglias** [comment]
@negue might have ideas too

**Comment by negue** [comment]
The `gear.locked` is set at https://github.com/HabitRPG/habitica/blob/develop/website/common/script/libs/shops.js#L107

`specialClass` is only set to seasonal gear, because the normal property `klass` get the value `special` which isn't any of the real user's class anymore.

for a short-term fix would be just to check if `item.klass` and `item.specialClass` (if existing) are not the same as `user.stats.class`

the long-term fix would be either set a `lockedType` that way its easier to find the right translation string - OR - merge the `klass`/`specialClass` situation

**Comment by Alys** [comment]
I'm closing this because it's not a problem right now because it's currently possible to buy off-class gear. Once we fix that bug, I'll see if this issue needs to be reopened.
