### ISSUE TITLE
mobile website: Stat Points can't be allocated (except for PER) because arrow buttons aren't visible

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9801]
On a small browser window such as in a mobile device, Stat Points can't be allocated to anything except Perception because the arrow buttons for the other Stats aren't visible:

![screenshot_2018-01-14_13-08-26](https://user-images.githubusercontent.com/1495809/34912405-460dae94-f92c-11e7-9e50-14f7b0d5f8cf.png)

I've put this on hold while I find out what the status is of adding a bulk allocation interface to the website.

**Comment by Alys** [comment]
I've put this on hold while I find out what the status is of adding a bulk allocation interface to the website.

**Comment by lemoness** [comment]
Is this still happening?

**Comment by Alys** [comment]
Yes, still as shown in the screenshot. It also occurs in PC browsers in a narrow window - that's the easiest way to test for it.
