### ISSUE TITLE
private messages inbox can't be opened

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9807]
I've seen a few reports from people saying they can't open the inbox on the website. The one below from Piti! (9226cae6-d852-45da-a51b-ec2c9cb759e6) has some specific details:

**Piti! wrote:** "After deleting 2-3 old inbox Messages, now I cannot open my inbox anymore (Edge Browser). Neither can I open the modal for writing PMs. (On my Android App everything works). (not urgent!)"

[_Note that I'm not sure if deleting messages is relevant - it might be a coincidence. Other reports haven't mentioned it. Also other reports have mentioned it happening in more than one browser so it might not be just Edge._]

**Alys wrote:** "Please try these things in order:
- Disable all browser extensions.
- Go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there.
- Reload the website using your browser's refresh button while you are holding down the "Control" or "Command" key on your keyboard.
- Open the Developer Console or JavaScript Console in your browser (instructions here).
- Clear the messages currently shown in the Console. There should be a trash can icon or other icon to clear them but if you can't find it easily, don't worry about doing this step - this is helpful for us but not essential.
- Try to open your inbox again. If anything appears in the Console, paste it into a message here (don't worry about neat formatting). If nothing appears, please tell us that.

Can you also try accessing your inbox on a different browser, if you have one installed? If that fails too, please tell us which browser it is, including its version number."

**Piti! wrote:** "Thank you @Alys for your hint about Clearing browser Cache. Done. Reload done. My inbox won't open on Edge browser. Habitica Webpage Shows the sync bar but doesnt open anything. Console F12 doesnt say anything. Trying to open PM, console says:

> TypeError: Unable to get property '$el' of undefined or null reference vendor.98d50355e51999638701.js (1,88031) { [functions]: , proto: { }, description: "Unable to get property '$el' of undefined or null reference", message: "Unable to get property '$el' of undefined or null reference", name: "TypeError", number: -2146823281, stack: "TypeError: Unable to get property '$el' of undefined or null reference at Anonymous function (https://habitica.com/static/js/app.893d7f899cf827b2516e.js:1:579735) at Anonymous function (https://habitica.com/static/js/vendor.98d50355e51999638701.js:1:88298) at it (https://habitica.com/static/js/vendor.98d50355e51999638701.js:1:88125)" }

----

Here's another report from PHOENIX ALEX (34f79f82-502c-4982-944d-079f74e7d294) but we don't have any more details:

"So I can't access to the Messages window at all. When I click on messages nothing happens. Tried reloading, changing browser, logging out and logging in, even restarting the pc. Nothing worked - what gives?"

**Comment by Alys** [comment]
Two more posts today, the first with a possible workaround!

monkiii (a8eaf70b-c913-42a6-87fe-8a35c068a489): "@Alys not sure what to look for in the JavaScript Console especially there seems to be no time stamp or, well I have no idea if I used the right thing. **But since I received a new message the problem seems to be solved**, in both browsers Chrome 63 and Firefox 57. I did nothing unusual, the only thing that could have solved the problem, apart from you did something, was to get a new message."

CinnamonBell (7ded02e8-4229-4ed4-85d0-19a738b5dfbd): "Unable to send messages to Party Members I go to their profile click the little message and it just closes the profile without having anything else happen. One of my other party members have reported this to me as well. I have tried to send messages with two different browsers. Both Google Chrome and Firefox."

**Comment by Alys** [comment]
monkiii's suggested fix worked for CinnamonBell. :)
_"@Alys Thank you so much! Yes it seems like the bug has been fixed on my end here, I'll ask my party member if she has any more issues and to see what is going on with it."_

The next time I see a report of this, I'll capture their inbox before and after I send them a PM, strip out the `text` fields (the ones containing the messages which should remain private and which I expect won't be directly related to this bug) and then see if I can work out why receiving a new PM fixes the problem. As a wild guess, I'm wondering if it's related to the sort order. Maybe the `sort` numbers can get out of sync if you delete one or more messages (some kind of Version Error or something like that  maybe?) and a new PM might make the inbox resort itself correctly. I really should have done that with CinnamonBell, if I'd been thinking clearly. :)

**Comment by tanelf** [comment]
Here's the output from the Chrome Developer Console when I tried to send a message to Alys (disabled extensions, reloaded site, and clicked on the message icon from Alys' profile):

TypeError: Cannot read property '$el' of undefined at https://habitica.com/static/js/app.893d7f899cf827b2516e.js:1:579760 at Array.<anonymous> (https://habitica.com/static/js/vendor.98d50355e51999638701.js:1:88300) at it (https://habitica.com/static/js/vendor.98d50355e51999638701.js:1:88129) at t.exports (https://habitica.com/static/js/vendor.98d50355e51999638701.js:6:135225) at g.(anonymous function) (https://habitica.com/static/js/vendor.98d50355e51999638701.js:6:89746) at Number.y (https://habitica.com/static/js/vendor.98d50355e51999638701.js:6:89604) at MessagePort.b (https://habitica.com/static/js/vendor.98d50355e51999638701.js:6:89626) rt @ vue.runtime.esm.js:1692 nt @ vue.runtime.esm.js:1683 et @ vue.runtime.esm.js:1672 (anonymous) @ vue.runtime.esm.js:1790 it @ vue.runtime.esm.js:1709 t.exports @ _invoke.js:5 g.(anonymous function) @ _task.js:35 y @ _task.js:21 b @ _task.js:25

**Comment by Alys** [comment]
I see that there's a fix for this being developed already, but in case it's helpful, we have another report with console logs from Piti! (9226cae6-d852-45da-a51b-ec2c9cb759e6) :

"Maybe further Information helps on the bug where PMs can't be opend.
Receiving new Messages doesn't help in my case.
I tried Internet Explorer aditionally. Console says:"

TypeError: Die Eigenschaft "substring" eines undefinierten oder Nullverweises kann nicht abgerufen werden. { [functions]: , proto: { }, description: "Die Eigenschaft "substring" eines undefinierten oder Nullverweises kann nicht abgerufen werden.", message: "Die Eigenschaft "substring" eines undefinierten oder Nullverweises kann nicht abgerufen werden.", name: "TypeError", number: -2146823281, stack: "TypeError: Die Eigenschaft "substring" eines undefinierten oder Nullverweises kann nicht abgerufen werden. at Anonymous function (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:777473) at re (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:97052) at s (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:776302) at t.prototype._render (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:6:10554) at r (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:92732) at Ci.prototype.get (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:6:5655) at Ci.prototype.run (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:6:6384) at Nt (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:94196) at Anonymous function (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:88298) at it (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:88125)", Symbol()_m.cnfg8vmglx3: undefined }

TypeError: Die Eigenschaft "$el" eines undefinierten oder Nullverweises kann nicht abgerufen werden. { [functions]: , proto: { [functions]: , proto: { }, message: "", name: "TypeError", Symbol()_m.cnfg8vmglx3: undefined }, description: "Die Eigenschaft "$el" eines undefinierten oder Nullverweises kann nicht abgerufen werden.", message: "Die Eigenschaft "$el" eines undefinierten oder Nullverweises kann nicht abgerufen werden.", name: "TypeError", number: -2146823281, stack: "TypeError: Die Eigenschaft "$el" eines undefinierten oder Nullverweises kann nicht abgerufen werden. at Anonymous function (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:581826) at Anonymous function (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:88298) at it (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:88125)", Symbol()_m.cnfg8vmglx3: undefined }

**Comment by TheHollidayInn** [comment]
Eh, the language is different, but I am seeing bits and pieces of the error I fixed :P

**Comment by TheHollidayInn** [comment]
Another issue (different but similar) has come up:

```
Piti!
UserID: 9226cae6-d852-45da-a51b-ec2c9cb759e6
The Inbox-message-problem-monkey is still alive. Now I get an error message on clicking 'messges' (edge browser). Sync bar shows but Message window/modal does not open. TypeError: Unable to get property 'substring' of undefined or null reference vendor.b9dbae6b9d38a904a42a.js (1,88031) { [functions]: , __proto__: { [functions]: , __proto__: { [functions]: , __proto__: { [functions]: , __proto__: null }, message: "", name: "Error" }, message: "", name: "TypeError" }, description: "Unable to get property 'substring' of undefined or null reference", message: "Unable to get property 'substring' of undefined or null reference", name: "TypeError", number: -2146823281, stack: "TypeError: Unable to get property 'substring' of undefined or null reference at Anonymous function (https://habitica.com/static/js/app.0b132edc7d3b41168eb5.js:1:935407) at re (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:97052) at s (https://habitica.com/static/js/app.0b132edc7d3b41168eb5.js:1:934236) at t.prototype._render (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:6:10554) at r (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:92732) at Ci.prototype.get (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:6:5655) at Ci.prototype.run (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:6:6384) at Nt (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:94196) at Anonymous function (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:88298) at it (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:88125)" }
```

**Comment by SabreCat** [comment]
@TheHollidayInn Should #9869 have closed this?

**Comment by TheHollidayInn** [comment]
No, but I pushed the commit here: https://github.com/HabitRPG/habitica/commit/7b026fa32cc2b2794fb9af40b0435863a0d9dbef

**Comment by paglias** [comment]
Was it deployed?

**Comment by TheHollidayInn** [comment]
Yea, that's from release.
