### ISSUE TITLE
Invite Friends > Share User ID menu items do not work

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9809]
The items in the "Share User ID" menu aren't working ("Facebook", "Twitter", "Copy User ID", etc).

Steps to reproduce:

1. Don't be in a party.
2. Click the "Invite Friends" button in the header.
3. Click "Share User ID".
4. Click on any of the items in the menu that appears. Nothing happens. No Console message.

**Comment by ghost** [comment]
I'm interested in working on this

**Comment by Alys** [comment]
@nowmeow Thanks! Comment here if you have questions.

**Comment by ghost** [comment]
@Alys Was the functionality for this feature ever created?  The look and toggle of this menu is present, but I can't find function.  I will start creating it, but I thought I'd ask.  It just seemed odd.

**Comment by TheHollidayInn** [comment]
No, the UI was meant to be hidden if it isn't :P

**Comment by Alys** [comment]
A related problem was reported in the Bug guild: "On the level up popup, when you click share to twitter or facebook, it shares the following link, which is broken: https://habitica.com/social/level-up"

@nowmeow Are you still interested in working on this? If you don't want to create all the code needed to implement sharing, then you could hide the share menu from the "Invite Friends" feature and the share link from the level-up popup.

**Comment by ghost** [comment]
@Alys 
Yes, I am still interested in working on this. Sorry for the ridiculous amount of time.

**Comment by ghost** [comment]
@Alys Sorry, but I have to pass on this issue.  I'm just not competent enough yet.  Hopefully in the future I will become a better contributor.  Enjoy the rest of your week, and sorry again for wasting time.

**Comment by Alys** [comment]
@ghost That's okay! Thank you for trying! And for letting us know. :)
