### ISSUE TITLE
new messages notifications for guilds sometimes don't take you to the guild

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9810]
Sometimes new message notifications for a guild won't take you to the guild. 

donotgogentle🌼🌷🌻 (65be576c-c412-41c7-a31f-94994c8c4fc6) reports:
"When I click on the Guilds from the drop down menu in the top right corner, sometimes I'm not actually taken to the Guild. Sometimes I am, but sometimes nothing happens when I click on the Guild name."

and later:

"Just had that issue of not being taken to a guild when clicking on it from the upper right dropdown. STAG, 10:58 am PST"
That's about five or six hours before the date of this issue and the guild is https://habitica.com/groups/guild/59f699a3-9d22-4d6d-b34a-8fcdf2ad1dac and I can't find anything in Loggly for that guild at that time so I think it's a client-side issue.

I thought we'd heard other reports like this but I can't find another issue about it.

**Comment by paglias** [comment]
This will be fixed in #9716

**Comment by mandyzhou** [comment]
In case it helps, I've noticed that when I click outside of the guild name, nothing happens, but when I aim directly at the letters, I'm taken to the guild.
