### ISSUE TITLE
filter screen is hideous in Group Plan's Task Board page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9817]
In a Group Plan's "Task Board" page, click the Filter button to see this:

![screenshot_2018-01-18_18-45-26](https://user-images.githubusercontent.com/1495809/35088526-d1ef379c-fc7f-11e7-9d30-5cc930b03762.png)

Thanks to Mark Ruzicka (72a98142-8a25-4051-9ac8-9c431c24d343) for reporting this.

**Comment by TheHollidayInn** [comment]
This is on a small screen, right?

**Comment by paglias** [comment]
No I've seen it happening on big screens too
