### ISSUE TITLE
two contributor reward modal strings should be merged into one

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9818]
We have these two strings in `website/common/locales/en/contrib.json` :
```
  "contribModal": "<%= name %>, you awesome person! You're now a tier <%= level %> contributor for helping Habitica. See",
  "contribLink": "what prizes you've earned for your contribution!",
```
and this code that uses them in `website/client/components/achievements/contributor.vue` :
```
| {{ $t('contribModal', {name: user.profile.name, level: user.contributor.level}) }}
a(:href="$t('conRewardsURL')", target='_blank') {{ $t('contribLink') }}
```

That's bad because translators can't do proper translations when a sentence is split into two strings, and because it causes words to be run on in the modal:

![screenshot_2018-01-18_19-30-16](https://user-images.githubusercontent.com/1495809/35090652-07a087aa-fc86-11e7-98b6-79e1ffbf4e98.png)

Those two strings should be merged into one and the Vue code changed to match.

@vIiRuS Will matching changes be needed in the iOS and/or Android apps? I.e., do the apps also use those strings to tell users about their new contributor tiers? If so, we should leave those two strings exactly as they are now and create a third string to merge the two texts into one. The website can use the third string. The apps can continue to use the two old strings until the apps have been updated. I can create app issues for this when the website has been changed. Please let me know if that will be needed.

_Thanks to Kent the Amateur (b82b7aa8-161f-4b02-aef9-4a319e47f7b2) for reporting this._

**Comment by kent12t** [comment]
Just adding on to this issue - so far I have never been notified on new contributor tier, so there's a chance only one string needs to be updated. :)

Edit: I'm on Android (App Version: 1.3.3)

**Comment by Kiwilicious** [comment]
Can I have a go at this issue?

**Comment by Alys** [comment]
@Kiwilicious Sure! Thanks! Post here if you have any questions.

**Comment by Kiwilicious** [comment]
@Alys Just took a look at it and if I understood correctly, the resulting code in `website/common/locales/en/contrib.json` as well as the other locales would have this format:

```
"contribModal": "<%= name %>, you awesome person! You're now a tier <%= level %> contributor for helping Habitica. See what prizes you've earned for your contribution!",
```

and the code in `website/client/components/achievements/contributor.vue` would look like:

```
| a(:href="$t('conRewardsURL')", target='_blank') {{ $t('contribModal', {name: user.profile.name, level: user.contributor.level}) }}
```

This would make the whole message a link unless we don't want that?

**Comment by Alys** [comment]
@Kiwilicious That's a good point, thanks for mentioning it. There's a couple of ways around this.

One is to put the URL into the string as HTML text like this:
`<%= name %>, you awesome person! You're now a tier <%= level %> contributor for helping Habitica. See <a href="http://....">what prizes you've earned for your contribution!</a>`
That's not ideal because the translators might accidentally delete some of the necessary punctuation in the link, but we'd use it if there weren't better options.

The other option, for this specific case, would be to actually keep using two strings but split them up better (something I hadn't thought of when I posted earlier).
```
 "contribModal": "<%= name %>, you awesome person! You're now a tier <%= level %> contributor for helping Habitica.",
  "contribLink": "See what prizes you've earned for your contribution!",
```
The entire `contribLink` message can then be a link and that would look okay.

With the current vue code that puts both messages on the same line, there'd still be a problem for RTL languages since (if I understand correctly) you'd read the contribLink string before the contribModal string. I think that could be fixed by putting a `br` between the two.

**Comment by Kiwilicious** [comment]
@Alys Agreed that the second option would be less confusing for others working with the code. I'll change the `contribModal` and `contribLink` to what you have as complete sentences:

```
"contribModal": "<%= name %>, you awesome person! You're now a tier <%= level %> contributor for helping Habitica.",
"contribLink": "See what prizes you've earned for your contribution!",
```

and add a break between the two sentences like so:

```
| {{ $t('contribModal', {name: user.profile.name, level: user.contributor.level}) }}
br
a(:href="$t('conRewardsURL')", target='_blank') {{ $t('contribLink') }}
```

Is this fine?

**Comment by Alys** [comment]
Sounds good! If you include a screenshot of the result in your PR we can give further feedback then if needed.

**Comment by Kiwilicious** [comment]
Could you direct me to the api endpoint for modifying contribution levels?

**Comment by Alys** [comment]
There's no API route for it. Admins do it in a special admin-only interface in the Hall. Use "Make Admin" in the Debug menu in the footer of your local install website to turn your account into an admin and then you can give tiers in the Hall to that account or any other.

**Comment by Kiwilicious** [comment]
Thanks for all the help and being patient. Posted a screenshot on the PR.
