### ISSUE TITLE
Orb of Rebirth does not adequately describe its effects

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9825]
The Orb of Rebirth's description screen does not list all of its effects. Currently it says:

"Instantly restart your character at Level 1 while retaining achievements, collectibles, equipment, and tasks with history. This will take effect immediately."

I suggest expanding it to something like this:

"Instantly restart your character as a Level 1 Warrior while retaining achievements, collectibles, and equipment. Your tasks and their history will remain but they will be reset to yellow. Your streaks will be removed except from challenge tasks. Your Gold, Experience, Mana, and the effects of all Skills will be removed. All of this will take effect immediately. For more information, see the wiki's [Orb of Rebirth](http://habitica.wikia.com/wiki/Orb_of_Rebirth) page."

That will give players a much more accurate description of the effects of Rebirth, which will prevent complaints like this recent one from Ree Godlevskiy in the Habitica Help guild:
**"I used an orb of rebirth now and it took all of my gold! That's robbery"**

I'll leave this as suggestion-discussion for a few days then we can mark it as help wanted.

**Comment by cassidypignatello** [comment]
I can grab this one!

**Comment by TheHollidayInn** [comment]
Thanks!
