### ISSUE TITLE
Stats Points allocation should not be available when the class system is locked / opted out

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9826]
Before a player unlocks the class system (at level 10) or when they have opted out of the class system, they should not see the Stat Points and Allocation method section at the bottom of the User Icon > Stats screen. I.e., these elements should be hidden:

![screenshot_2018-01-20_07-26-49](https://user-images.githubusercontent.com/1495809/35172440-736b6c6a-fdb3-11e7-8f26-e900a3c84cc0.png)

This is because Stat Points and the manual/automatic allocation methods are part of the class system.

For the benefit of anyone working on this, a player who has not yet unlocked the class system has this in their data:
`"flags.classSelected": false`

A player who has opted out of the class system has this:
`"preferences.disableClasses": true`

**Comment by Alys** [comment]
For the benefit of anyone working on this, a player who has not yet unlocked the class system has this in their data:
`"flags.classSelected": false`

A player who has opted out of the class system has this:
`"preferences.disableClasses": true`

**Comment by nmassaro** [comment]
May I work on this issue? :)

**Comment by majestic-owl448** [comment]
This issueoggef about two weeks ago is pretty similar: https://github.com/HabitRPG/habitica/issues/9788

**Comment by TheHollidayInn** [comment]
Go for it @nmassaro!

**Comment by Alys** [comment]
@Ieahleen they are related but they each need a fix in a different part of the code so it makes sense to do them separately. :)
