### ISSUE TITLE
challenge participants list should not contain "Promote to Leader"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9827]
Steps to show the bug:

1. View a Challenge that you own (or any challenge if you are a mod or staff).
2. Click on the "Participants" badge to the right of the Challenge's name.
3. Click on the three-dots menu for any participant.
4. Observe that it contains an entry for "Promote to Leader". That should not appear for Challenge participants.

It **should** appear when viewing the participants of a Guild or Party (if you are the leader or a mod/staff) so the fix for this Challenge issue should not stop that menu item appearing for groups.

**Comment by TheHollidayInn** [comment]
I believe this only happens if you are a mod/staff because the `isLeader` prop fails if the memberModal is not for a group. Either way, I'm adding a challenge check.

**Comment by Alys** [comment]
Ah, forgive me, I should have tested for the challenge owner case instead of just assuming! Thank you for the fix.
