### ISSUE TITLE
What about if we make it a PWA?

### ISSUE THREAD

**Issue by jlrg1992** [HabitRPG/habitica#9832]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  *I would like to start to work on it. But this would be my first time working in open source stuff.

### Description
[//]: # PWA it's said to be lighter than native apps.

**Comment by paglias** [comment]
Making Habitica a full PWA would be great but it's not a small task or something that can be done in one single step.

Having said that, we're happy to accept new PRs that make Habitica faster to load, more responsive, etc
