### ISSUE TITLE
Checklists on Challenge tasks should be private to the participant

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9834]
When a participant adds a checklist to a task from a Challenge, it should not be possible for the challenge owner or any other player to see the checklist. The checklist shouldn't appear in the CSV export file or in the "View Progress" screen.

The checklists can also be seen when using the API directly, which should also not be possible.

**Comment by Alys** [comment]
Because this is an "priority: important" issue, I'm going to ask the staff if they can fix it asap. If any contributor wants to work on this, you can comment here to ask as usual, but please be aware that there might be a delay of a day or two in our reply and we might say that it's already being fixed. If this does end up being a contributor fix, we'd like it to be done fairly quickly so we might ask for a progress report after a week if we haven't heard from you by then.

**Comment by Alys** [comment]
The checklists can also be seen when using the API directly, which should also not be possible.

**Comment by ghost** [comment]
To clarify, because it's not clear (to me) from the initial comment, what I was reporting was that the Challenge Data Tool is able to retrieve checklist information. It is not in the exported .csv nor viewable on Habitica (as far as I know).

**Comment by Alys** [comment]
Sorry, yes, I didn't write that clearly and should have included your report.

It's just the API that's allowing checklist data to be seen.
