### ISSUE TITLE
tasks page and other pages not loading correctly in Chrome, maybe other browsers

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9838]
I'm seeing a few reports in the Report a Bug guild like these ones, probably just since the most recent website deployment:

Intor (07b22cb3-57c3-42fa-8a31-471555d88003):
"I'm encountering a bug on the website, where if I'm opening up a window that I previously closed with habitica as the open tab, reopening it will cause the tasks page to be basically empty, but I can switch to a few other pages of the site just fine. Once clicked off the tasks section, it becomes un-clickable. Refreshing the tab seems to fix the issue, though. This issue only appeared the last couple days. I've only used Chrome on a windows 10 machine, so I'm not sure if the issue is unique to this system or is similarly experienced elsewhere."

sariahsue (0170a899-b611-4178-b8ca-cb38b76669b4): "Hi! I'm having a problem loading the site on Chrome right now. Safari and Firefox are both loading it just fine, but on Chrome it looks broken. Some of the icons are really huge, and most of it just isn't loading at all. I've already tried refreshing a bunch of times, and even quitting out of the browser, but it hasn't made any difference. I'm on a Mac. Chrome is version 63.0.3239.132."
Alys: "In Chrome, please go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there, then reload the website using your browser's refresh button while you are holding down the "Control" or "Command" key on your keyboard. After you've done that, please could you post again here to tell whether it helped or not?"
sariahsue: "Well, it sort of worked. The layout looks fine, but my tasks are gone. It goes straight from the party display to the links at the bottom. (The tasks weren't loading before, when the layout was messed up, either.) I think the problem is contained to the task page, though. Everything else seems normal."
I've asked sariahsue for console log messages.

**Comment by Alys** [comment]
Also other pages / menus, as sariahsue said in their first report. I'll post more when I see more.

**Comment by Alys** [comment]
Console log messages from sariahsue are below. I haven't yet gone through them to week out the parts that won't be relevant.

"Lots of things popped up. I hope you know what all that means, because I don't. (Except the slow network warning. That's probably normal for our internet connection. Ha ha.)"

moment.js:297 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/ Arguments: Error at g.zone (https://habitica.com/static/js/vendor.b9dbae6b9d38a904a42a.js:1:13202) at Object.<anonymous> (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:229738) at n (https://habitica.com/static/js/manifest.59eb62d368ec1faf227f.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:15617) at n (https://habitica.com/static/js/manifest.59eb62d368ec1faf227f.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:530288) at n (https://habitica.com/static/js/manifest.59eb62d368ec1faf227f.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:771847) at n (https://habitica.com/static/js/manifest.59eb62d368ec1faf227f.js:1:101) at Object.<anonymous> (https://habitica.com/static/js/app.86ba22754967b06e54b6.js:1:478171) w @ moment.js:297 (anonymous) @ moment.js:324 (anonymous) @ index.js:18 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:1090 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:31635 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:48968 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:25205 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:47901 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:20718 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:50230 n @ bootstrap 9193cfa3f3b3259b4f4f:54 window.webpackJsonp @ bootstrap 9193cfa3f3b3259b4f4f:25 (anonymous) @ app.86ba22754967b06e54b6.js:1 app.86ba22754967b06e54b6.js:23928 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/robotocondensed/v16/b9QBgL0iMZfDSpmcXcE8nPX2or14QGUHgbhSBV1Go0E.woff2 app.86ba22754967b06e54b6.js:23928 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/roboto/v18/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2 8.397f443b128af367c25c.js:6 Uncaught SyntaxError: Unexpected end of input vue-router.esm.js:1905 Error: Loading chunk 8 failed. at HTMLScriptElement.r (bootstrap 9193cfa3f3b3259b4f4f:103) s @ vue-router.esm.js:1905 (anonymous) @ vue-router.esm.js:1947 (anonymous) @ vue-router.esm.js:1768 (anonymous) @ vue-router.esm.js:1833 Promise rejected (async) (anonymous) @ vue-router.esm.js:1780 (anonymous) @ vue-router.esm.js:1801 (anonymous) @ vue-router.esm.js:1801 ft @ vue-router.esm.js:1800 (anonymous) @ vue-router.esm.js:1736 p @ vue-router.esm.js:1943 r @ vue-router.esm.js:1717 r @ vue-router.esm.js:1721 (anonymous) @ vue-router.esm.js:1718 (anonymous) @ vue-router.esm.js:1964 (anonymous) @ router.js:352 p @ vue-router.esm.js:1943 r @ vue-router.esm.js:1717 ct @ vue-router.esm.js:1725 ae.confirmTransition @ vue-router.esm.js:1972 ae.transitionTo @ vue-router.esm.js:1874 le.init @ vue-router.esm.js:2494 beforeCreate @ vue-router.esm.js:540 It @ vue.runtime.esm.js:2864 t._init @ vue.runtime.esm.js:4505 je @ vue.runtime.esm.js:4604 (anonymous) @ main.js:36 n @ bootstrap 9193cfa3f3b3259b4f4f:54 (anonymous) @ app.86ba22754967b06e54b6.js:50230 n @ bootstrap 9193cfa3f3b3259b4f4f:54 window.webpackJsonp @ bootstrap 9193cfa3f3b3259b4f4f:25 (anonymous) @ app.86ba22754967b06e54b6.js:1 app.86ba22754967b06e54b6.js:23928 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/roboto/v18/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2 habitica.com/:1 Mixed Content: The page at 'https://habitica.com/' was loaded over HTTPS, but requested an insecure image 'http://www.thesweetescape.net/blog/wp-content/uploads/2014/02/Read-All-the-Books.jpg'. This content should also be served over HTTPS. 2loggly.tracker.js:159 POST https://logs-01.loggly.com/inputs/undefined/tag/ClientJS 403 (Forbidden) track @ loggly.tracker.js:159 push @ loggly.tracker.js:146 o.onerror @ loggly.tracker.js:46 habitica.com/:1 Failed to load https://logs-01.loggly.com/inputs/undefined/tag/ClientJS: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://habitica.com' is therefore not allowed access. The response had HTTP status code 403. habitica.com/:1 The SSL certificate used to load resources from https://payments.amazon.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information. www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=347488693.1478326557&jid=353191414&_v=j66&z=551353630:1 GET https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=347488693.1478326557&jid=353191414&_v=j66&z=551353630 net::ERR_BLOCKED_BY_CLIENT Image (async) ta @ analytics.js:2 wc @ analytics.js:9 ba @ analytics.js:9 Sa @ analytics.js:14 Ha.D @ analytics.js:12 pc.send @ analytics.js:48 X.b.(anonymous function) @ analytics.js:25 Z.v @ analytics.js:55 Z.D @ analytics.js:54 N.N @ analytics.js:59 rc @ analytics.js:48 z @ analytics.js:48 (anonymous) @ analytics.js:59 (anonymous) @ analytics.js:59

**Comment by TheHollidayInn** [comment]
It sounds to me like opening Habitica from a Chrome History menu will open an older state of the site. This could possibly even be from chrome saving the local hash of our build files before a release.

**Comment by paglias** [comment]
The console errors seems to indicate a not working internet connection

**Comment by kartikadur** [comment]
I also see some SSL & CORS related warnings. Could be related to that as well, since Chrome (Google) is updating its security policies.

**Comment by paglias** [comment]
Have we had any report of this recently? Otherwise I'd close the issue since there doesn't seem to be anything actionable that we can do

**Comment by TheHollidayInn** [comment]
Closing for now. Feel free to repoen if another report.
