### ISSUE TITLE
Where is Bailey ?

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#984]
I haven't seen her in a couple of days, and I have to say I miss her. Was nice being able to see the latest release notes (btw if you bring her back, would be nice if we could have some sort of notifications for new notes, instead of having to check them manually)

**Comment by lefnire** [comment]
Bailey only shows up when there's site news. We haven't had any new features since the last time she appeared, she'll appear when the next feature release. Not sure I follow that last bit?
