### ISSUE TITLE
Group Plan task's "Assigned To" close button closes the entire task

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9840]
The close button shown below closes the entire Group Plan task edit screen instead of closing just the list of users.

Steps to reproduce:
1. Go to the "Task Board" screen for a Group Plan you own.
2. Create a new task.
3. Click the "None" button under the "Assigned To" label.
4. Click the "Close" button in the new screen that appears (i.e, the button shown below). Observe that the entire task edit screen closes. The desired behaviour is that only the list of users closes.

![screenshot_2018-01-21_15-56-17](https://user-images.githubusercontent.com/1495809/35191307-9ed3a44c-fec3-11e7-9d91-f4e7d989299d.png)

**Comment by razzlepdx** [comment]
I would like to take a stab at this!

**Comment by Alys** [comment]
@razzlepdx Thank you! Comment here if you have questions or run into trouble!

Labels updated.

**Comment by razzlepdx** [comment]
Wanted to pop in and say I'm still committed to finishing this, had a few bumps getting the local environment set up on my new laptop.  I hope to jump in this weekend and may have some questions then - sorry for the delay!

**Comment by Alys** [comment]
@razzlepdx I've just done a local install from scratch on a new linux machine and I made [a few small changes](http://habitica.wikia.com/index.php?title=Setting_up_Habitica_Locally&diff=120173&oldid=119837) to the [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) instructions. I don't know if they'll help you. I'm pretty keen to get it updated in other ways if needed, so let us know if you have any problems that the instructions don't solve.

**Comment by beffymaroo** [comment]
@razzlepdx How this fix going? Did you get the bumps in the local install worked out (see also Alys's comment)? Let us know when you have a moment. :)
