### ISSUE TITLE
raw code error message shown for various errors (e.g., sessionOutdated,  challenge not found, delete Group Plan tasks)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9841]
When a Group Plan task has been assigned to you and you try to delete it, you are correctly shown a red snack notification saying you can't do that, but the error message contains all of this text:
```
{ "success": false, "error": "NotAuthorized", "message": "Can't delete group tasks that are assigned to you." }
```
I.e., you see the json object not just the `message`

We should either make that message be formatted correctly, or (probably better) prevent anyone trying to delete active Group Plan task by not showing the delete buttons for them.

**Comment by citrusella** [comment]
Is it possible this "all of this text" thing is happening with all error messages? I've seen some people report they've seen it happen on certain errors, and I know I've seen it happening on "session is outdated" and "challenge not found or you don't have access" (and group not found) errors (and probably another but I'm blanking on what I thought it was... (I was mentally keeping track to make sure it wasn't only one or two)).

**Comment by Alys** [comment]
That's very possible! I've just tested with the "Your session is outdated" message (complete a Daily in one tab then try completing the same Daily in another tab) and it has the same bug. I'm changing this issue's title to make it more generic. Thanks @citrusella

**Comment by Alys** [comment]
@citrusella Ugh, sorry, you gave exactly the "session is outdated" example in your own post. `facepalm`  I have a headache. :)

**Comment by paglias** [comment]
This is probably partly due to https://github.com/HabitRPG/habitica/pull/9747

**Comment by LulaV14** [comment]
@Alys as @paglias said, is because of the PR I send that fixed just #9213 
I'm sorry I didn't checked for other type of error messages.
Maybe what we can do is catch the server errors so they can be a JSON that contains a ``message`` field, and then undo the changes from the PR I send?

EDIT: I may be able to fix it quickly, maybe I can send a PR tomorrow at end of day?

**Comment by paglias** [comment]
Can we just check if the error object has a message property and in that case use that for the notification? Most server errors have it

**Comment by TheHollidayInn** [comment]
I'm pretty sure the PR I linked fix this. I ran into this while creating the banned modal.

**Comment by LulaV14** [comment]
I'm still seeing this 😕 
![screen shot 2018-01-25 at 11 55 44 am](https://user-images.githubusercontent.com/1399744/35409406-f7e087e8-01c6-11e8-8dd2-3db5570defa8.png)

@paglias I can do that quick right now

**Comment by TheHollidayInn** [comment]
My PR hasn't been merged yet but we can reconcile with your new PR :)

**Comment by LulaV14** [comment]
Ohh okok I'm so sorry, I thought it was already merged.
I can close mine, 'cause I'm seeing yours and it does fixes other tickets apart from this issue right?

**Comment by paglias** [comment]
has this been fixed?

**Comment by Alys** [comment]
No, I saw an example of it today while editing a Challenge.

**Comment by paglias** [comment]
In progress in #8753
