### ISSUE TITLE
Tier colors and markers should show in names in private Messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9843]
In the Messages screen, the names of the players should show their tier colours and icons. At the moment, they are black text with no icons:

![screenshot_2018-01-21_17-01-05](https://user-images.githubusercontent.com/1495809/35191680-c65e66ba-fecc-11e7-9027-645cf4d63df5.png)

For example, my name in that screenshot should be formatted as it is in guild messages like this:
![screenshot_2018-01-21_17-02-42](https://user-images.githubusercontent.com/1495809/35191683-e0716c46-fecc-11e7-9878-7be3508bafb4.png)

_Thanks to citrusella, the serving wench for pointing this out._

**Comment by bricksroo** [comment]
I'd like to work on this issue, please.

**Comment by Alys** [comment]
@bricksroo Great, thank you! Comment here if you have questions.

**Comment by bricksroo** [comment]
@Alys I've got WIP fix for this, but have a question for you. The contributor info was not part of the inbox message data, which this PR adds for all new messages going forward. However, I'm not too sure how to go about fixing existing messages. That would need to be an edit to the DB, correct?

**Comment by Alys** [comment]
@bricksroo  You're right, we would need to edit the database to fix the old messages, but we won't worry about it. It's acceptable that older messages won't have the tier formatting. A migration would be slow and if anything went wrong, we might corrupt users' inboxes. Thanks for the PR!

**Comment by bricksroo** [comment]
Alright sounds good. Thanks!
