### ISSUE TITLE
exported CSV files from Challenges are wrong when a challenge participant has left the challenge

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9844]
Thanks to Anysia (db190b28-8ce5-422e-8076-d43a62a7b204) for reporting this in the Report a Bug guild, we've found that the exported CSV files from challenges can be wrong.

For any challenge where one or more participants have left the challenge, the exported task data for some or all of the remaining participants will be attributed to the wrong user. Some users' task data will not appear.at all.

This means that you currently cannot use the exported CSV files to accurately judge any challenge unless you are **certain** that no participants have ever left the challenge.

**Until this is resolved I recommend that challenge creators do not use the exported CSV files to judge challenges. If you can't get the data you need from the challenge's page in the website (which itself is difficult due to https://github.com/HabitRPG/habitica/issues/9828 and possibly other usability issues), then I recommend using the [Habitica Challenge Data Tool](https://oldgods.net/habitica/cTheDragons/challenge.html) created by @cTheDragons. From the testing I've done today, her tool is accurate and complete for all challenges.** 

I don't know how long this bug has existed or how many previous and current challenges have been affected. For challenges that have been closed, I'm afraid there is no way for admins to find out if the exported data was correct or not.

We realise that this bug has a significant negative effect on fair judging of challenges and we're really sorry about that.

----

## Technical Details

This is the code that's wrong:
https://github.com/HabitRPG/habitica/blob/9545f692efdbea7ff4980c0c7ce20534585363e2/website/server/controllers/api-v3/challenges.js#L547-L575
In particular, the code from the comment down is wrong. The assumption in that comment is incorrect.

When a user has joined a challenge and then later leaves the challenge, the challenge ID remains in the user's `challenges` array in their user document, but they do **not** have any tasks from the challenge in their tasks list. (In the future, PR https://github.com/HabitRPG/habitica/pull/9791 will prevent the ID being left in that array in most cases.) 
The code assumes that all users found by `User.find({challenges: challengeId})` will have tasks. When a user does not have tasks, all the exported data is attributed to the wrong users because of the way that `index` is assumed to always map to the right location in `resArray`. I.e., when a user in `resArray` does not have tasks, that user and all users following them in `resArray` will be assigned a different user's tasks.

The fix is to rewrite that block of code so that it correctly attributes all tasks to the right users in all situations.

## Examples of incorrect data

The effects of this bug can be seen in these examples of incorrect data for the challenge 10a945b6-5851-4b20-ae60-8d1e7a9af607 :

The first two lines in the exported CSV file are these:
```
07a1dd1e-effa-43d0-b1f9-99e5d97b9436,User1,"todo:**Read & Check off**: Consider joining some or all of the following challenges if you want to commit to more :tomato: per day:  :two::tomato:, :three::tomato:, :four::tomato:, :five::tomato:, :six::tomato:, and :seven::tomato:.",-12.647796380052213,,0,daily::one::tomato: done!,21.84625854495744,Did one 25 minute session of productive work today.,29,habit:Extra :tomato: done today!,0,"Completed more than the minimum :tomato: today. To be used with the following challenges: :one::tomato:, :two::tomato:, :three::tomato:, :four::tomato:, :five::tomato:, :six::tomato: & :seven::tomato:",0

13d384c3-c41f-496f-ac25-e64241e5dacb,User2,"todo:**Read & Check off**: Consider joining some or all of the following challenges if you want to commit to more :tomato: per day:  :two::tomato:, :three::tomato:, :four::tomato:, :five::tomato:, :six::tomato:, and :seven::tomato:.",1,,0,daily::one::tomato: done!,9.939702075972264,Did one 25 minute session of productive work today.,2,habit:Extra :tomato: done today!,0.493675,"Completed more than the minimum :tomato: today. To be used with the following challenges: :one::tomato:, :two::tomato:, :three::tomato:, :four::tomato:, :five::tomato:, :six::tomato: & :seven::tomato:",0
```

By comparing that data to data read directly from the database, I can see that:

In the first line, User ID 07a1dd1e-effa-43d0-b1f9-99e5d97b9436 corresponds to a player who has left the challenge (i.e., they have the ID in their `challenges` array but they do not have any challenge tasks). The task data listed in that first line actually belongs to the player whose name and User ID appear in the second line.

Similarly, the second line contains task data that belongs to the User ID in the third line, and (presumably) so on down the file (I stopped checking after the third/fourth line and then started again at the bottom).

The final two lines in the exported CSV file are these:
```
db190b28-8ce5-422e-8076-d43a62a7b204,Anysia,"todo:**Read & Check off**: Consider joining some or all of the following challenges if you want to commit to more :tomato: per day:  :two::tomato:, :three::tomato:, :four::tomato:, :five::tomato:, :six::tomato:, and :seven::tomato:.",1,,0,daily::one::tomato: done!,23.585687221291188,Did one 25 minute session of productive work today.,32,habit:Extra :tomato: done today!,0.39422091402709536,"Completed more than the minimum :tomato: today. To be used with the following challenges: :one::tomato:, :two::tomato:, :three::tomato:, :four::tomato:, :five::tomato:, :six::tomato: & :seven::tomato:",0

e1d43f13-4a7b-4188-8844-127b4f63c67c,AnotherUser
```
Following the same pattern as for the first few lines, the task data for the second-last line in the file actually belongs to the User ID in the final line. 

The final line contains no task data even though that user is a current participant in the challenge and does own tasks from the challenge.

**Comment by Alys** [comment]
Because this is an "priority: important" issue, I'm going to ask the staff if they can fix it asap. If any contributor wants to work on this, you can comment here to ask as usual, but please be aware that there might be a delay of a day or two in our reply and we might say that it's already being fixed. If this does end up being a contributor fix, we'd like it to be done fairly quickly so we might ask for a progress report after a week if we haven't heard from you by then.

**Comment by paglias** [comment]
I think there are two ways to fix this:

1. Convert the members array to a map `{user1Id: user1Data, user2Id: user2Data}` and then match the task to the user with `users[task.userId]` but with many users it'll be a very slow op that I'd prefer to avoid. Advantage would be that we could stop sorting the results in the query

2. Change the code here https://github.com/HabitRPG/habitica/blob/9545f692efdbea7ff4980c0c7ce20534585363e2/website/server/controllers/api-v3/challenges.js#L568-L571 to keep cycling through the results until the userid and task id matches. Right now the code only checks once if the task and user match and if they don't it just skip to the next user which doesn't work in this case when some users have no data at all

**Comment by paglias** [comment]
I've posted a PR with a possible fix but it should be first tested on the challenge linked by @Alys

**Comment by Alys** [comment]
For testing in a local install with our current `develop` code (NOT with PR #9791 merged in), you can create a challenge with one task, then have three users join it. Pick the user who has the **lowest** User ID when sorted alphnumerically and have that user leave the challenge.  For either **one** of the remaining users, complete the task so that it has a different value for that user. Click the challenge's export button and see if the data makes sense (compare the task value with the User IDs to make sure the right lines have the right data, ensure that there's no half-complete line at the bottom, check that the user who left the challenge doesn't appear in the CSV).

**Comment by paglias** [comment]
Hmm I wasn't able to replicate, I tried your process but got a correct CSV with and without my fix

**Comment by Alys** [comment]
Sorry, those exact test steps are failing to produce a bugged export file because it looks like the bug that does not remove the challenge ID from the user's `challenges` array does not occur all the time.

You can easily simulate the situation you need to test your fix though. Instead of this:
	"Pick the user who has the lowest User ID when sorted alphnumerically and have that user leave the challenge."
don't make that user join the challenge at all. Just push the challenge's ID into their `challenge` array.

You'll then have three users that appear to be challenge members when you do a search like `db.users.find({challenges: cid},{ _id:1 },{multi:true})` but only two users with challenge tasks.
