### ISSUE TITLE
Horizontal scroll on static pages

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9852]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
  * Browser: Google Chrome 63.0.3239.132 / Safari 11.0
  * OS: Ubuntu 17.04 / macOS High Sierra 10.13

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
On static pages (starting with `static/`), horizontal scrolling is always displayed, although it should not be.

![image](https://user-images.githubusercontent.com/4408379/35228868-e02d22a8-ffa2-11e7-9943-916d988d1c4d.png)

**Comment by TheHollidayInn** [comment]
Thanks for reporting and supplying a PR :D Which page is the screen shot from? I think we will want to update those images as well.

**Comment by lex111** [comment]
Any static page, in the screenshot https://habitica.com/static/features

**Comment by TheHollidayInn** [comment]
Yep! I see the issue. I just wanted to get the page so we can update the images with our new designs. Thanks :D

**Comment by lex111** [comment]
Any news?
