### ISSUE TITLE
Losing Health! Can't Check off Dailies! Feeling sad :(

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#986]
Over the past two days, I have been losing health despite valiantly completing dailies. I got down to 5 hp (just used restore for now). Two of my most damaging dailies have been grayed out for probably about the past two days as well so I haven't been able to check them off- could they be the issue? How to I fix them?

Oh, and now my streak for those two dailies is lost :(

Thank you so much!

**Comment by Gmk1212** [comment]
My dailies have greyed out for several days now.

**Comment by wc8** [comment]
To clarify, did they turn grey without you disabling the repeat? 
Grey (not due) is controlled via Edit > Repeat; each letter (S,M,T,W,T,F,S) toggles the day of the week the daily is due or not due. Are you unable to change this?
You should still be able to check them off when they are grey/not due.

**Comment by ghost** [comment]
I had never made any changes to these dailies before, and they were on for every day. I couldn't edit them when the problem started, but I just tried again today and it appears all the days of the week were unchecked and I can change them now. 
I missed a daily that was working yesterday, so I'm not sure if any health was deducted due specifically to the grayed out dailies, but I was losing health when they were gray previously (and nothing else should have been doing damage).

**Comment by lefnire** [comment]
due to http://habitrpg.tumblr.com/post/51082061058/whats-with-the-downtime, which we're working on presently

**Comment by ghost** [comment]
Good to know. Thanks so much! Wish I was a bit more tech-savvy so I could help.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
