### ISSUE TITLE
Registration error shows whole JSON object

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9864]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

### General Info
UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
Browser: Google Chrome 63.0.3239.132
OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
For example, if you simply click on a button without filling in the fields, the JSON object is displayed, rather than the usual (as a string) message.
![image](https://user-images.githubusercontent.com/4408379/35283253-d02a4004-0068-11e8-9d06-5b8e322b8a45.png)

**Comment by TheHollidayInn** [comment]
This issue is logged here: https://github.com/HabitRPG/habitica/issues/9841
