### ISSUE TITLE
Habits May Not Reset When Changing Custom Day Start

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#9865]
Euxaes
UserID: 74cb6f51-0481-4f8d-b27e-6ae0fc34229c
Hi, my habits that reset weekly on Mondays did not reset. I happened to adjust my cron last Sunday by an hour earlier before midnight, in order to finish off a boss and that my damage is higher than usual on that day hence the adjustment. My cron time is back to midnight now. I think that has something to do with the habits non-reset. I cannot update my habits because of this. For now I track them by paper. Can you please take a look? Thank you.

**Comment by lemoness** [comment]
Have there been any other reports of this?

**Comment by Alys** [comment]
I haven't seen any. This was likely caused by the user adjusting their Custom Day Start time to 11pm, which isn't recommended for most cases (as described in the wiki's [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) page) and/or from cron being delayed a day due to the change.
