### ISSUE TITLE
navigation / menu bar in header wraps onto two lines

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9874]
_This might be a duplicate; I thoiught we still had one open but I can't find it._

The navigation bar still wraps onto two lines on smaller windows / larger font/zoom sizes / longer values for Gold. This is from my laptop with a browser taking up the full screen width but with a sidebar open:

![screenshot_2018-01-25_21-33-34](https://user-images.githubusercontent.com/1495809/35386329-62e39e4a-0217-11e8-9966-19bff11f2a24.png)

**Comment by pollaro** [comment]
I've tried reproducing this, and I can't get it. I've added a subscription, added a ton of gold, zoomed.

**Comment by mandyzhou** [comment]
I can reproduce this by gradually resizing the window (instead of zooming).

**Comment by TheHollidayInn** [comment]
Our new nav bar seems to have fixed this.
