### ISSUE TITLE
Don't show advanced settings if it's not exists

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9876]
Depending on the conditions of the settings may be absent, then we need to hide the block with them.

![image](https://user-images.githubusercontent.com/4408379/35392196-2d5b40e0-01f2-11e8-812f-95c8436c30b5.png)

**Comment by lemoness** [comment]
@Tressley How would you like to handle this?

**Comment by beffymaroo** [comment]
@Tressley Any thoughts on this?

**Comment by Tressley** [comment]
Oh no! This one slipped through the cracks. For now I'd prefer we show it in a disabled state.

![image](https://user-images.githubusercontent.com/2686586/38894433-39e10ae4-425b-11e8-8122-881c61d6f74b.png)
