### ISSUE TITLE
Party's page improvement

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9877]
Small improvements in the design, you can accepts them? I showed on the screenshots.

Before:
![image](https://user-images.githubusercontent.com/4408379/35393041-dfeb7eee-01f4-11e8-9f62-d7016c6dbb62.png)

After:
![image](https://user-images.githubusercontent.com/4408379/35393052-e5d2998c-01f4-11e8-9559-ef616af701bd.png)

**Comment by paglias** [comment]
Positioning fixes look fine but we don't want to hide empty sections

**Comment by lex111** [comment]
Ok, then I'll do PR?

**Comment by TheHollidayInn** [comment]
Go for it!
