### ISSUE TITLE
Allow text wrapping on "I agree to follow the Community Guidelines" button

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9878]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
* UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
* Browser: Google Chrome 63.0.3239.132
* OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When the screen size is less than 1400 pixels, the text of the button goes beyond it

![image](https://user-images.githubusercontent.com/4408379/35393595-71b49ee0-01f6-11e8-8303-7862874554f2.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by paglias** [comment]
Maybe we should reposition the button? @Tressley

**Comment by TheHollidayInn** [comment]
Yea, I think it would be good if the button is a column and breaks to fit under the text.

**Comment by Tressley** [comment]
Yeah, for quick design fix, just center the text and then center the button under it.
