### ISSUE TITLE
Icon "Cost" on "Create Reward" modal is not vertically centered

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9879]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
* UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
* Browser: Google Chrome 63.0.3239.132
* OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

![image](https://user-images.githubusercontent.com/4408379/35394565-22909776-01f9-11e8-9469-e72376c3c19e.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by lex111** [comment]
![image](https://user-images.githubusercontent.com/4408379/35394678-67e5b586-01f9-11e8-9bba-5d865c72ecd0.png)

**Comment by paglias** [comment]
Thanks, fixed in https://github.com/HabitRPG/vuejs-datepicker/commit/21d4e43a14380d6c6b2821afdfaa3ab4c7b465fe and https://github.com/HabitRPG/habitica/commit/b76d731cee33816e188e880b6abad997d06c0cc2
