### ISSUE TITLE
Unhatchable, disappearing eggs

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#988]
The last two times I've gotten an egg drop, I've been unable to hatch it. I went to my inventory and clicked the egg, but no hatching potion menu appeared. 

Several minutes later, I manually reloaded the page (which I do frequently, due to glitchy synching), and the egg was gone. The XP for the task appears to have remained but I'm not 100% sure about this. I have verified that no pet was added to my stable and no hatching potion was consumed. 

I have gotten hatching potions during the same time period, and those seem to be added to my inventory correctly (figures, since I already have way too many of those and no eggs). 

I'm using Chrome on MacOS. I could try to replicate the no-potion-dropdown problem in another browser by buying a pet from the market, if that would help, but I can't easily test the problem with disappearing drops.

**Comment by lefnire** [comment]
ongoing critical issue for many people, trying desperately to solve. In the mean time what's your user id, I'll give you tokens to buy back your drops

**Comment by octern** [comment]
No worries, I've got tokens aplenty. I'll just wait to hear that the problem is solved! Thanks for looking into it.

**Comment by seajules** [comment]
I've had this same issue several times.  I've also had the issue that I could hatch an egg, but then couldn't find it in my stable.  When I hit refresh, that animal was gone.  I've had this happen with a fox egg, a dragon egg, a bear egg, and at least one cactus egg.

**Comment by octern** [comment]
When was the last time this happened to you? Today I got an egg drop that I was able to hatch normally.

**Comment by seajules** [comment]
I believe it was last week that this last happened to me.  Today, I also got an egg I was able to hatch and equip.

**Comment by heyimzsa** [comment]
This happened to me yesterday and the day before. I lost my golden fix right after hatching and also a red panda. I was able to recover the panda but was only able to get the golden potion back. 
—

**Comment by OlliePage** [comment]
I just got a lion egg, I clicked it with a desert potion..saw it in my stables. I went to equip it and it froze. I refreshed the page and had to re-tick two tasks I'd completed. I got the exp but not the lion egg :( Can you please revert that? Only that I'd been waiting for that egg for ages...sod's law eh?

if so: my user idea is: fb2c26cb-1072-4dad-a57f-d6b2aadc78a7

Thanks!

**Comment by seajules** [comment]
I just lost another fox.  I poured the potion on the egg, saw the fox in my stable, but when I tried to equip it, clicking did nothing.  I hit refresh, and my fox was missing.  Is there any way to get back any of the pets/eggs we've lost?

**Comment by seemar27** [comment]
The same has essentially happened to me.  I try to hatch my eggs and they refuse.  I've already had two potions disappear: skeleton and base.  My user ID is: 9630f255-c80c-4efa-84f3-10ead9ee1b7d
Thanks.

**Comment by wc8** [comment]
Possibly related to #765

**Comment by ellernock** [comment]
Seems to happen to me several times daily. UserID is. 8b799b3e-33c6-4953-8810-9a581a03d741.

**Comment by Ariadia** [comment]
I lost a panda egg first, but I thought it was because the site went offline immediately after the drop. I didn't worry about it too much then, since the server was going down, but yesterday I got a red potion and cactus egg, and hatched the cactus with a base potion, and today both are missing! I've even been logging out manually to try and keep from losing checked off items and pets. No visible errors pop up, my dropped and purchased items and progress just vanish. _sad_

I use chrome and chromium both to access habitrpg. UserID 52be296f-a60e-443e-becd-ad455011cb44

**Comment by lefnire** [comment]
If anyone here needs gems to buy back lost pets, say aye. Otherwise, follow http://habitrpg.tumblr.com/post/55792029689/bug-workarounds to avoid pet-loss

**Comment by Ariadia** [comment]
Aye, that would be nice. Making note of the workaround - thanks!

**Comment by lefnire** [comment]
@Ariadia gave you some gems

**Comment by seajules** [comment]
Aye.  I've also lost three potions just today: two white potions and one zombie.  User id: f8793188-b734-463c-8eff-087d5dad8c7d

**Comment by lefnire** [comment]
@seajules should be set

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
