### ISSUE TITLE
Inconsistent profile actions icons

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9880]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
* UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
* Browser: Google Chrome 63.0.3239.132
* OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
They vary in size and alignment.

![image](https://user-images.githubusercontent.com/4408379/35394839-cf6fc188-01f9-11e8-9632-a994f60be568.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by paglias** [comment]
The approved design is here https://github.com/HabitRPG/habitica/issues/9626 but we had this PR that seems to be merged that should have addressed this https://github.com/HabitRPG/habitica/pull/9667 @SabreCat was it ever merged into develop?

**Comment by SabreCat** [comment]
Yeah, that was merged ages ago!

**Comment by SabreCat** [comment]
Actually, derp. That PR reinstated the block button that was missing. Tweaking the alignment etc. could still be done.

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by jackmakesthings** [comment]
If this is still outstanding, I can work on it!

**Comment by Alys** [comment]
@jackmakesthings Thank you! 

Labels updated.
