### ISSUE TITLE
Dailies should have a checkbox for "Confirm that this Daily wasn't done before applying damage" for RYA

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9890]
_This was removed from the new website's design and we mentioned it in the initial flurry of bug reports but I can't find an issue for it. We can close this if it is a duplicate._

Dailies used to have a checkbox labelled "Confirm that this Daily wasn't done before applying damage". The default state was ticked, which meant that the Daily would appear in the Record Yesterday's Activity screen (RYA) each morning if it wasn't completed on the previous day. Unticking the checkbox prevented the Daily from appearing in RYA. More information is available on the wiki's [Dailies](http://habitica.wikia.com/wiki/Dailies#Record_Yesterday.27s_Activities) in the "Record Yesterday.27s Activities" section.

This feature should be brought back.

FYI @Tressley for designs.

**Comment by Joseph67843** [comment]
Is this the same as #9622 ?

**Comment by Alys** [comment]
Oh fer goodness sakes, I can't even find my own issues. :)  Thanks @Joseph98101 ! :)
