### ISSUE TITLE
Plan group modal issue

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9897]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
* UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
* Browser: Google Chrome 63.0.3239.132
* OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Upon a click on the "Create Your New Group" button on [this](https://habitica.com/group-plans) page, a modal window opens and the page scrolls to the very top (should not it be?)

![image](https://user-images.githubusercontent.com/4408379/35471615-ce5cea24-036f-11e8-926a-f4589ddcc424.png)

And we need to stylize checkboxes and radio buttons, now they are displayed in the usual way (browser 
 rendering).

![image](https://user-images.githubusercontent.com/4408379/35471642-36a5b89a-0370-11e8-9f3d-d9fca627be63.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by TheHollidayInn** [comment]
The scrolling seems right.

As for adding styles, we'd welcome that :D

**Comment by Kiwilicious** [comment]
If this issue is still open, I can style the checkbox and radio button.

**Comment by TheHollidayInn** [comment]
Go for it!

**Comment by Kiwilicious** [comment]
File at `/client/components/groups/groupPlan.vue`
Relevant SCSS at `/client/assets/scss/form.scss`
This is what I have currently with the original code commented out:
```
.form-group(v-if='type === "guild"')      
  .custom-control.custom-radio
    input.custom-control-input(type="radio", name="new-group-privacy", value="private", v-model="newGroup.privacy")
    label.custom-control-label {{ $t('inviteOnly') }}
  //- .radio
  //-   label
  //-     input(type='radio', name='new-group-privacy', value='private', v-model='newGroup.privacy')
  //-     | {{ $t('inviteOnly') }}
  .custom-control.custom-checkbox
    input.custom-control-input(type="checkbox", v-model="newGroup.leaderOnly.challenges")
    label.custom-control-label {{ $t('leaderOnlyChallenges') }}
  //- .checkbox
  //-   label
  //-     input(type='checkbox', v-model='newGroup.leaderOnly.challenges')
  //-     | {{ $t('leaderOnlyChallenges') }}
```
![screenshot from 2018-02-01 20-18-25](https://user-images.githubusercontent.com/20009133/35716352-4c2ff790-078d-11e8-9a78-acf47b94de7d.png)

The radio button is working fine but the checkbox input isn't registering the click. If I put a click handler on the input, it doesn't register. It does register if I put it on the parent div. Is there something I'm missing?

**Comment by paglias** [comment]
The checkbox input should have an id attribute and the label a for attribute with the same value of the input id
