### ISSUE TITLE
Password reset without confirmation

### ISSUE THREAD

**Issue by virgiliu** [HabitRPG/habitica#99]
If I reset the password no confirmation will be required from the user. This way someone can screw with somebody else by resetting their password if they know their email and they know they use it on habitrpg.

**Comment by lefnire** [comment]
yes, definitely working on that

**Comment by Andrew565** [comment]
I think I can work on this one, will look into it first chance I get.

**Comment by Andrew565** [comment]
I looked into this issue briefly, and it looks like the Habit app is relying on the mechanisms and templates from derby-auth for this. Is the derby-auth login template easy to change without requiring a change to derby-auth itself?

**Comment by lefnire** [comment]
i maintain derby-auth as well, and am quite liberal about pull-requests. I dare say, derby-auth was a bit of a quickie so if you feel up to it...

**Comment by hookang** [comment]
Added to Master List of Features - #169. Closed for Organization.

**Comment by wc8** [comment]
If this is something critical the developers will be addressing, should it be closed?

**Comment by lefnire** [comment]
i agree, this is more repo-oriented. flaw really

**Comment by horusofoz** [comment]
@lefnire Any updates on this ticket?

**Comment by lefnire** [comment]
Nothing yet, still putting out the server crits - this is high on the list,
but not for another week or so

**Comment by lefnire** [comment]
downgrading since you can now change your password, obviously still very important, but comparatively...

**Comment by lefnire** [comment]
https://github.com/lefnire/derby-auth/issues/28

**Comment by lefnire** [comment]
let's actually close this one and follow up there, since there a few derby-auth developers that may find interest in the conversation
