### ISSUE TITLE
STreaks keep breaking for no reason,,,

### ISSUE THREAD

**Issue by nextmike** [HabitRPG/habitica#990]
...
![capture](https://f.cloud.github.com/assets/2489918/521044/60baf5e4-bf61-11e2-8b03-e87a9222495c.png)

super frustrating....I hit refresh on the page and I not only lost a level but my streaks were broken.

**Comment by nextmike** [comment]
Notice all were reset except Reddit daily, no rhyme or reason as far as I can tell.  They should all be on Day 8 with the exception of Exercise.
![capture](https://f.cloud.github.com/assets/2489918/521050/fd487aa2-bf62-11e2-9e9a-13fbde3c935d.png)

**Comment by AranelS** [comment]
I get this, too.  Constantly.  (Every day for some of them.)  I explained it here:
https://github.com/lefnire/habitrpg/issues/985

**Comment by StanLindsey** [comment]
Going to close this thread and keep it in #985. 

We're working on it though guys. ;)
