### ISSUE TITLE
Add smart app banner to web site

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9901]
See more - https://github.com/ain/smartbanner.js

**Comment by lemoness** [comment]
@Tressley Is this something that we want to do?

**Comment by Tressley** [comment]
Yes! This is something we've discussed previously and is definitely a good idea for users trying to access Habitica via mobile (especially with the responsive issues.) Helps highlight our apps as well.

**Comment by lex111** [comment]
I would like to do it.

**Comment by lemoness** [comment]
@lex111 Thanks very much! Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by beffymaroo** [comment]
@lex111 Are you still working on this issue? Please let us know. Thank you!

**Comment by lex111** [comment]
@beffymaroo unfortunately, I have not worked on it yet, it seems that in the near future I will not be able to find the time, sorry :(

**Comment by beffymaroo** [comment]
@lex111 That's fine, thank you for the update!
