### ISSUE TITLE
add Task Alias field to all four task types

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9902]
Now that tasks have an "Advanced Settings" section again, the Task Alias feature can be returned. Details about that feature and a screenshot from the original website can be seen on the wiki's [Task Alias](http://habitica.wikia.com/wiki/Task_Alias) page, but in brief the feature involves:

- An `input` box for entering a small amount of text (a single-line field, not a textarea).
- A title/label for the field ("Task Alias" - stored in the `taskAlias` locales string).
- Placeholder text for the `input` box if that's appropriate/consistent with the new website's design ("your-task-alias-here" - the `taskAliasPlaceholder` locales string).
- A popover or tip or on-hover text or similar to explain what the field is for. This text is currently in two locales strings (`taskAliasPopover` and `taskAliasPopoverWarning`) but it's probably best to have a single popover/tip/whatever - if so, the `taskAliasPopoverWarning` string should be deleted and its text added to the end of `taskAliasPopover`. The text is "This task alias can be used when integrating with 3rd party integrations. Only dashes, underscores, and alphanumeric characters are supported. The task alias must be unique among all your tasks." and "WARNING: Changing this value will break any 3rd party integrations that rely on the task alias."

Those locales strings can be seen here:
https://github.com/HabitRPG/habitica/blob/028da1d6a9e1d64865dee8ab87289e121efbdd09/website/common/locales/en/tasks.json#L35-L38

This is waiting for designs for the new field (@Tressley ) but once that's done, the work required is:
- add the input field and texts
- add client-side validation to ensure only appropriate text is added (for details, see [Task Alias](http://habitica.wikia.com/wiki/Task_Alias) and the code below)
- save the data into the task - here's the relevant part of the task schema: https://github.com/HabitRPG/habitica/blob/028da1d6a9e1d64865dee8ab87289e121efbdd09/website/server/models/task.js#L44-L58

This should be done for all four task types (Habits, Dailies, To-Dos, and Rewards). For Rewards, the "Advanced Settings" section will need to be added.

The API already supports the Task Alias so the only changes needed are client-side.

**Comment by Tressley** [comment]
For this feature we're looking to introduce a "developer mode" toggle that will help align with more of the power-user/developer type requests we receive. This toggle will live on the API tab of Settings and allow power-users to enable the more advanced API-level controls while more common, daily users can still use a more streamlined interface.

![image](https://user-images.githubusercontent.com/2686586/53022925-3db42e00-342a-11e9-9eca-4571ff9cbb48.png)

![image](https://user-images.githubusercontent.com/2686586/53022989-5f151a00-342a-11e9-8c73-43ce42335abf.png)

**Comment by yagopessoa** [comment]
Hey there!

Just to get what's the idea. This "Task alias" feature will only be available for users that have "developer mode" active? Or these are two unrelated features ("task alias" and "developer mode")?

**Comment by Alys** [comment]
@yagopessoa Hi! :)

The "Task alias" feature will only be available for users who have "developer mode" active.

The "developer mode" feature doesn't exist yet so it would need to be created as part of the fix for this issue.

Post again if you're interested in working on this!

**Comment by yagopessoa** [comment]
@Alys got it! Sure, i'll be glad to work on this!

My e-mail is yagorp15@gmail.com in case you have any designs to share with me :)

**Comment by Alys** [comment]
@yagopessoa Thank you! I've marked it as in progress for you.

Pinging @Tressley in case there are designs to be shared.

**Comment by Tressley** [comment]
@yagopessoa -- I've invited you to our Zeplin project. You can find the artboard for adding the feature to tasks here: https://zpl.io/bPZ9vLA

**Comment by shanaqui** [comment]
@yagopessoa Hi there! Just checking in whether you're still interested in working on this issue. 

If we don't hear from you within a week, or you're not interested anymore, I'll mark this as help wanted again. :) No rush to complete a fix or anything, we're just making sure the issue doesn't go stale!

**Comment by yagopessoa** [comment]
@shanaqui Hello! Yeah, I started to work on this but in the past few days I'm struggling to find time to work on it. I'll try a little more, if thats ok, and then if I'm not being able to progress I'll let you guys know.

**Comment by shanaqui** [comment]
@yagopessoa Just checking in how it's going now! :)

**Comment by shanaqui** [comment]
Since it's been a week without reply, I'm changing this back to help wanted. Let us know if you'd like to pick it back up, if no one else wants to!

**Comment by citrusella** [comment]
So... I have *no idea* (yet) if I have the skill to take on something like this at present, but I wanted to ask this question even though I'm pretty sure it's not actually part of the issue (i.e. this issue is just about the alias field, which should appear *only if* developer mode (which would need to exist as part of this too) is on)... so... tangentially:

Is that "confirm before applying damage" line in the mockup-y screenshot above the same thing as the pre-redesign switch for whether or not a daily appears on RYA? Or does it refer to something else?

\*dives into the code to figure out what making the actual requested fix happen would entail*

**Comment by Tressley** [comment]
@citrusella -- That's just a mock-up artifact from previous discussions. You can ignore that. 😅

**Comment by citrusella** [comment]
Okay, fair. I just saw it and was like 👀

**Comment by citrusella** [comment]
Okay, still trying to figure out if I have the skill and not (yet?) claiming this (stepping through what would need to be done and seeing if I can follow how to do it before I potentially ask to do it in case I flake), but I noticed the alias strings referenced in the original post have been deleted from tasks.json. If they need to be added back as part of this, should they have the exact same text as they previously did? (Barring any changes suggested in the OP regarding consolidating strings, that is.)

**Comment by CuriousMagpie** [comment]
If it were me, I'd re-use the old text strings.

**Comment by Tressley** [comment]
This was added in #14262.
