### ISSUE TITLE
problems with changing language

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9904]
_I thought we had these bugs recorded already but I can't find issue(s) for them. This might be a duplicate though._

----

From Scea (9ae04082-7868-4042-b073-33b7a32cd573):
"if I change the language settings for the website, the site reloads but is still showing english menus and text. I need to do a manual refresh (F5) to get the german version of the site. And if I want to change back to English (I am doing this regularly to check the new translations), I need a double reload, too, before the website is showing the right language."

----

From Amystic (7edb4e21-9bac-41f8-9028-860cccd54008), who currently does have `"preferences.language": "en"`:

"... on the website, most of the interface is in hebrew (except some parts that are probably not translated yet)... despite my set language being english."

Response from katzalina:

"The website behaviour is a known bug, that will vanish if you reload the page... the website picks up your browser language on log-in, but reloading the page jogs it's memory :)"

**Comment by TheHollidayInn** [comment]
Is it similar or the same as this but with more browsers? https://github.com/HabitRPG/habitica/issues/9514

**Comment by Alys** [comment]
No, https://github.com/HabitRPG/habitica/issues/9514 is about how Firefox won't let the new setting be saved at all. In other browsers, the setting is saved but one or more manual reloads are needed for the website to pick up the change.

**Comment by Mahendran-Nadesan** [comment]
I'd like to work on this. May I?

**Comment by paglias** [comment]
Go ahead!

**Comment by beffymaroo** [comment]
@Mahendran-Nadesan Are you still working on this issue? Please let us know. Thank you!

**Comment by Mahendran-Nadesan** [comment]
Unfortunately I haven't looked at it much recently - I ran into errors after pulling the latest version. I seem to be missing some dependencies, but it's not obvious to me how to get them. I don't mind relinquishing this issue if someone else really wants it; if not, I'll try to fix my copy asap and work on the issue over the weekend!

**Comment by beffymaroo** [comment]
@Mahendran-Nadesan You're welcome to continue working on this! We're just doing a sweep to update in-progress issues is all. Thank you for responding!

**Comment by beffymaroo** [comment]
@Mahendran-Nadesan How is this fix going? Please update us when you have a moment. Thank you!

**Comment by paglias** [comment]
I'm going to give a shot at this
