### ISSUE TITLE
Task tag tooltip has incorrect margins

### ISSUE THREAD

**Issue by Tressley** [HabitRPG/habitica#9905]
The tooltip for displaying tags on a Task is being pushed down by an incorrect margin.
  * Browser: Chrome Version 64.0.3282.119 (Official Build) (64-bit), Firefox Quantum 58.0 (64-bit), Safari Version 11.0.2
  * OS: macOS High Sierra 10.13.2

![image](https://user-images.githubusercontent.com/2686586/35513966-beea5982-04d2-11e8-8a86-ff5f3fef527d.png)

**Comment by kartikadur** [comment]
I can look into this if no one else wants it.

**Comment by paglias** [comment]
@kartikadur thanks but there's an open PR here https://github.com/HabitRPG/habitica/pull/9910

**Comment by kartikadur** [comment]
@paglias no problem
