### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#991]
I have a to-do that had due date 17.05.2013 but nothing happened. I didn't lose hitpoints and the task is still on the list.

**Comment by wizonesolutions** [comment]
That's how it works. They become worth more over time. Due date doesn't do anything right now.

**Comment by StanLindsey** [comment]
Due date does tie into exporting to iCal. But other than that they have no functionality.

**Comment by lefnire** [comment]
Eventually we'll add some consequence or post-due
