### ISSUE TITLE
Avatar Image Not Updating After Death

### ISSUE THREAD

**Issue by Moltrain** [HabitRPG/habitica#992]
My character died yesterday and the message said I lost one piece of equipment (and a level). In the Rewards panel, the sword is available for purchase again (instead of the axe, which was there before the death), so I assume that's the piece I lost, but my avatar image is still carrying a sword.

**Comment by lefnire** [comment]
You're still wearing the training sword (weapon 0, it's kinda weird). That's a very subtle visual distinction between training sword & "Sword"
