### ISSUE TITLE
Armor idea

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#993]
Some people get the armor/weapons for the look, but you can make an option that turns off the armor stats so they get a harder gameplay.

**Comment by lefnire** [comment]
we'll be adding reward items to the inventory before adding the class system, meaning you can switch back to old gear if you want. go nakies at that time.

**Comment by paglias** [comment]
It's now possible to revert back to an older armor set

**Comment by Shaners** [comment]
I think this request is about having the armor displayed on the character but not receiving the stat bonus from said armor. Maybe a setting for hardcore mode? Some talk about a hardcore mode here: https://trello.com/c/k2MWBcxl/204-death-mechanic but it probably needs it's own trello card.

**Comment by wc8** [comment]
This (armor idea) seems related to the new [Costumes](https://trello.com/c/iY6A7nlX/336-costumes-armory-v2) card.

**Comment by wc8** [comment]
Link added to [Costumes](https://trello.com/c/iY6A7nlX). Follow-up there.
