### ISSUE TITLE
Tavern UI changes needed to match recent Guild and Party changes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9932]
In PR https://github.com/HabitRPG/habitica/pull/9892, changes were made to the Guild and Party pages. 

Those changes should also be made to the Tavern, where appropriate.  E.g., member list changes are not needed, changes to the buttons are.

_(Thanks to sonnet73 for pointing this out in the Report a Bug guild.)_

**Comment by theubermanishere** [comment]
I will be happy to work on this!

**Comment by Alys** [comment]
@theubermanishere thanks! Comment here if you have questions!

**Comment by beffymaroo** [comment]
@theubermanishere Are you still working on this issue? Please let us know. Thank you!

**Comment by dominictwlee** [comment]
If no one else is working on it, I'm happy to give it a go. I'll report back within a week.

**Comment by dominictwlee** [comment]
@Alys @beffymaroo Hi, just wanted to make sure I get the green light before I start working on this. Thanks!

**Comment by paglias** [comment]
Go ahead @dominictwlee !

**Comment by dominictwlee** [comment]
![tavern](https://user-images.githubusercontent.com/34794189/40543096-d316af84-601a-11e8-9933-cc0e518ec620.png)


@paglias Just wanted some clarifications on the actual changes that need to be made. Is this just a quick fix regarding the spacing as shown in the screenshot? Or do you also want the sidebar width to match the party page? Are the buttons in the party page also needed in the guild page?

**Comment by paglias** [comment]
Hmm @Alys is going to have more info about this

**Comment by Alys** [comment]
@dominictwlee It might be easiest if you look through the changes made in the PR linked from the top post, and the issue that the PR fixed, and if you're not sure if any of them should apply, ask us about them - will that help you work out what's needed?

**Comment by dominictwlee** [comment]
Yep that's fine, thanks!
