### ISSUE TITLE
"Delete Completed" To-Dos button should not appear in Challenge page or Group Plan Task Board

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9935]
The "Delete Completed" button for removing To-Dos should not appear in a Challenge's page:

![screenshot_2018-02-03_20-09-32](https://user-images.githubusercontent.com/1495809/35766151-218d8ccc-091e-11e8-9686-575bbe07c0b0.png)

Nor in the Task Board of a group with a Group Plan:
![screenshot_2018-02-03_20-10-39](https://user-images.githubusercontent.com/1495809/35766158-499bf29e-091e-11e8-9a84-22e96e6d89c6.png)

The only place it should appear in on the user's Task page when you click on the "Complete" tab for To-Dos (it currently does appear there correctly so that does not need to be changed).

**Comment by jj8huang** [comment]
I will work on it!

**Comment by theubermanishere** [comment]
I will be very happy to work on this issue. 😄

**Comment by jj8huang** [comment]
Is it preferred if I were to create a new clearCompletedTodosChallenges.vue file or if I do condition checking?

**Comment by Alys** [comment]
@jj8huang thanks for taking this on! Condition checking is commonly done and I suspect that will be the best solution here but that will depend on how it's currently implemented.

**Comment by TheHollidayInn** [comment]
If you want to extract this to a vue file, that is also good, but I don't think it would have `Challenges` as a sufix because this should only apply to the User's tasks.

**Comment by jj8huang** [comment]
Hi, thanks for the input! The reason for putting Challenges at the end is because it's specific to the Challenge section. Currently the vue file is a common component so if I were to make a new one, is there a recommended name in that case? Thanks again!

**Comment by TheHollidayInn** [comment]
Maybe I'm getting it confused :P I'd suggest just starting with the conditional to prevent showing for Group and Challenges to start then.

**Comment by lemoness** [comment]
@jj8huang Hi there! How is progress going on this ticket?

**Comment by jj8huang** [comment]
Hi, sorry for the delay. I should hopefully be done by the end of this weekend!

**Comment by jj8huang** [comment]
Hi, I won't be able to finish it until next weekend (something came up) if it is urgent you can reassign it and I understand, but I should definitely be good next weekend! Sorry about the inconvenience.

**Comment by lemoness** [comment]
@jj8huang Thank you for letting us know! I'll mark this as help wanted now, but you are welcome to reclaim in the future if nobody else does.

**Comment by srhboo** [comment]
I can take this on as a first contribution!

**Comment by Alys** [comment]
@srhboo Thank you! Post here if you have any questions.

**Comment by srhboo** [comment]
@Alys quick question! the info text ("completed to-dos are deleted...") should still appear right?

**Comment by Alys** [comment]
@srhboo Only on the user's own task list, not in the Challenge page or Group Plan Task Board. That's part of the bug although I neglected to mention that in this issue - thank you for asking!
