### ISSUE TITLE
Party name can be blank in the new message notification

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9937]
shanaqui reports that the name of their party was blank in one of the new chat message notifications they received (screenshot below). This is an intermittent error, not a constant one. They write:

"My party definitely has a name... 
Once the notification was cleared and then a new one generated, it had the name...
I cleared my notifications before I went to bed last night, so that one was generated when all my party accepted the quest so... at 23.30 GMT last night."  (that's about 12 hours before the creation time of this issue)

I happen to have raw data for their notifications that shows the same problem (the third item in the data below with the `null` name). This data was captured at 2017-02-03 10:11 UTC+10 (about 11 hours before this issue was created).
I also have data captured for shanaqui's notifications before that time showing a different notification for the same party, this time with the party name in it, so that's evidence that the missing party name is a current bug, not a side-effect of the notification migration that was performed a couple of days ago.

I haven't seen any other reports of this yet so I don't believe it happens very often. It could be related to parts of this old issue: https://github.com/HabitRPG/habitica/issues/8207 (e.g., "...sometimes the name never appears and the notification stays blank...")

```
{"_id":"bb089388-28ae-4e42-a8fa-f0c2bfb6f779","notifications":[
	{"id":"793c377f-2c44-4d51-84ee-322ade4e9bef","data":{"group":{"name":"The Beta Bug Guild","id":"5025264a-d4d5-40ab-bcde-efc0a0ebd5f7"}},"seen":true,"type":"NEW_CHAT_MESSAGE"},
	{"id":"c2823472-bbcb-43f5-8f6f-c21a73dd3c11","data":{"group":{"name":"The Legendary Book Club of Habitica","id":"170f8a17-8ce0-425c-8c31-eeb7e5ae7493"}},"seen":false,"type":"NEW_CHAT_MESSAGE"},
	{"id":"cb15320c-d857-48ca-a1ee-42c8520af172","data":{"group":{"name":null,"id":"64cff99b-9db0-4a82-8942-b4f12de2ad88"}},"seen":false,"type":"NEW_CHAT_MESSAGE"},
	{"id":"7c8e5e5d-6322-49c8-b800-e86aeb7d3e83","data":{"group":{"name":"Short-Term Goal Accountability","id":"59f699a3-9d22-4d6d-b34a-8fcdf2ad1dac"}},"seen":false,"type":"NEW_CHAT_MESSAGE"},
	{"id":"1de78315-84ae-4d50-93ed-a5ac36205448","data":{"group":{"name":"Tavern Challenge Overflow Chat","id":"e8e2f1ce-ae18-4cb1-8dd8-8e4adc59442f"}},"seen":false,"type":"NEW_CHAT_MESSAGE"},
	{"id":"f695c51c-45fe-4b04-9469-af4a9b743aad","data":{"group":{"name":"Report a Bug","id":"a29da26b-37de-4a71-b0c6-48e72a900dac"}},"seen":false,"type":"NEW_CHAT_MESSAGE"}
]}
```

![screenshot_2018-02-03_21-10-17](https://user-images.githubusercontent.com/1495809/35766723-14033de4-0929-11e8-8a9a-619a7a30eb75.png)

**Comment by paglias** [comment]
Mehh no idea how this could be happening. Anyway are the ids above correct @Alys ? Because a group with _id `cb15320c-d857-48ca-a1ee-42c8520af172` doesn't exist

**Comment by Alys** [comment]
The IDs were correct at the time I posted them. That data was copied directly from the output of a database search for shanaqui's notifications. The ID you're querying is the notification ID, isn't it?

**Comment by paglias** [comment]
Ah yeah, it was the notification id. Only thing that comes to my mind: were some of the messages about boss damage / other types of system messages?

**Comment by Alys** [comment]
The one that shanaqui reported was generated when all the party accepted the quest so it would have been the quest start system message.

Another two reports:


walrus62 (54665726-61fc-473f-8062-31a950a9ae11): "My Party Name decided not to show up in my Notification. [Picture.](https://snag.gy/bTI1Fo.jpg) I loaded a second tab and the notification wasn't there at all. I sync'd on the first tab but it didn't go away."

Kent the Apprentice (b82b7aa8-161f-4b02-aef9-4a319e47f7b2): "@walrus62 @Alys it happened to me as well. The first one happens when I still have an unread notif from my party then I go ahead and delete the party. It shows a blank party name. I think the second one occurs when I have read the party notification (by going to the party page) and go to another page. Then suddenly it appears. But this one I can't say for sure :)"

**Comment by paglias** [comment]
Posted a PR
