### ISSUE TITLE
I lost my catus zombie!

### ISSUE THREAD

**Issue by RibekkaBe** [HabitRPG/habitica#994]
Hello, I just got an hatching potion, and used it on my catus egg. 
Then the next time I updated the page my new pet just dissapeared and all life, points and dailies that I've done had were undone. Could somebody help me get my catus zombie back please?

**Comment by lefnire** [comment]
@RibekkaBe known issue, there's model.push / model.unshift issues i'm looking into - let's follow up at #952 to keep things organized. In the meantime, what's your user id, i'll give you tokens to buy back the potion / egg

**Comment by RibekkaBe** [comment]
Hi, 
wow, you respond fast!
I only need a hatching potion, I still have my egg :)
My user ID : (c336c106-03fc-4954-a611-e3cea91a87d5)
Thank you for your help! Love this game by the way! It's helping me getting me bachlor degree :) 
Ribekka

Date: Sun, 19 May 2013 07:57:19 -0700
FroHm: notifications@github.com
To: habitrpg@noreply.github.com
CC: bekka_90@msn.com
Subject: Re: [habitrpg] I lost my catus zombie! (#994)

@RibekkaBe known issue, there's model.push / model.unshift issues i'm looking into - let's follow up at #952 to keep things organized. In the meantime, what's your user id, i'll give you tokens to buy back the potion / egg

**Comment by lefnire** [comment]
woop, sorry for the delay - added the tokens now

**Comment by RibekkaBe** [comment]
I sorry for bottering you again, but I just recieved and cotton candy blue hatching potion, and zombie hatching potion in a row after x-ing my dailies. but then when I used the two hatching potions on a panda and a lio cub, the blue hatching panda dissapeard, but the zombie lion became visible in the stable. would you help me get back me blue panda? 
Ribekka

Date: Thu, 23 May 2013 04:49:44 -0700

**Comment by lefnire** [comment]
@RibekkaBe here's a shit-ton of gems to buy back pets. Unfortunately i don't have the bandwidth to keep up with these types of issues any other way, the only solution is to fix the memory leak and upgrade Racer, which I'm working on right now.
