### ISSUE TITLE
tour popover clipped by header, can't click end

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#995]
due to popover contained within header, which is `position: relative;`. need to re-jig a bunch of html & css to make hidden bailey appear properly to remove the `position: relative;` from the header. Critical because IIRC users can't interact with the game until they've clicked "end tour"
![munch_2013_05_18_140705 1](https://f.cloud.github.com/assets/195202/523061/f2c018d8-c08e-11e2-94db-a61b453fa4b1.png)

**Comment by SabreCat** [comment]
This can also happen when leveling up and getting a bubble regarding a newly unlocked feature. I saw it when I hit lv3 and got the tip about partying up--I needed to do a Ctrl-A and copy all the text on the page over to Notepad++ to read what it had to say!

**Comment by lefnire** [comment]
@zakkain any chance you could take a peek at this?

**Comment by caycefischer** [comment]
Curious. OK I'll check it out. Bailey might need to be re-positioned in some other way, it gets really crowded on mobile

**Comment by Aubec** [comment]
This issue is preventing me from being able to access habitrpg on my phone.  Any word on a solution in the works?  Thanks much!

**Comment by lefnire** [comment]
I haven't taken a look at it yet, I'll revisit after 0.5 upgrade if someone else hasn't tackled it. In the mean time, pinch-zooming out doesn't solve?

**Comment by caycefischer** [comment]
It might be a good idea to just disable the tour on mobile, for now... the layout is so different it probably wouldn't work great even if this initial error wasn't happening.

**Comment by Aubec** [comment]
Wow, thanks for getting back to me so quickly!  How do I disable the tour on my phone (the bottom of the tour bubble is blocked and I believe the end-tour button is there, but I'm not sure)?

Thanks again!

Jason Bourret, PhD, BCBA-D
Assistant Clinical Director
The New England Center for Children, Inc.
33 Turnpike Road, Southborough, MA 01772
Direct: (508) 658-7519
Phone: (508) 481-1015 ext. 3051
Fax: (508) 485-3421
www.necc.org

---

The information in this transmission is intended only for the person or entity to whom it is addressed and may contain confidential and/or privileged material. These materials are intended solely for the use of the intended recipient. If you are not the intended recipient, any use, distribution or disclosure of this transmission is prohibited. If you received this information in error, please notify the sender and properly dispose of the material.

---

**Comment by Aubec** [comment]
Thanks so much for the quick reply.  Unfortunately, pinch zooming isn't doing anything for me.  Zachary Kain also replied, suggesting turning the tutorial off but I believe the end-tutorial button is covered.

Thanks again.

P.S., Kudos on your work on this project.  As a behavior analyst, I devise motivational systems for a living and I'm excited to see what you've done with habitRPG.

Jason Bourret, PhD, BCBA-D
Assistant Clinical Director
The New England Center for Children, Inc.
33 Turnpike Road, Southborough, MA 01772
Direct: (508) 658-7519
Phone: (508) 481-1015 ext. 3051
Fax: (508) 485-3421
www.necc.org

---

The information in this transmission is intended only for the person or entity to whom it is addressed and may contain confidential and/or privileged material. These materials are intended solely for the use of the intended recipient. If you are not the intended recipient, any use, distribution or disclosure of this transmission is prohibited. If you received this information in error, please notify the sender and properly dispose of the material.

---

**Comment by lefnire** [comment]
pushed tour removal, will go out on next `chef-client` (~1h).

**Comment by lefnire** [comment]
Oh wow, a behavior analyst in our midst! Just so you know Jason, we're spitballing as we trudge along - we're just a bunch of bad-habit gamers, so please do shoot us any evidence-based advice for features / modifications you've got up your sleeves

**Comment by Aubec** [comment]
Hi Tyler,

Well, I'm just starting to scratch the surface of what you built, but it looks good so far.  I supervise doctoral students and I'm always on the lookout for ways to help keep them motivated to write and conduct research while they are in school and after they graduate.

I watched the introductory video on the site and I think you're right, the party system and recruiting a social community is a great idea.  I'm not sure how you have that aspect of things set up now, but one would expect that routing reinforcement through others (i.e., teaming up with friends and having other, trusted people report on your progress and performance) can eliminate cheating really push people to go the extra mile.  There's a site called Stickk (http://www.stickk.com/) that lets you set goals with other people and you can sign up to contribute money to a least-favorite organization (perhaps a political party you don't happen to like) if you don't meet your goals and you have to pick someone else to do the reporting to keep you honest.  That can be pretty punishing, but I think you'd get good bang for your buck arranging bonuses in a similar fashion.

There are also a ton of manipulations of reinforcement schedules you could play around with.  For example, variable or probabilistic reinforcement works better than reinforcing each instance of behavior (this is what keeps Vegas in the money).  You can also beef up effects by arranging probabilistic jackpots (i.e., occasionally the reward or punishment is doubled, tripled, etc... [think critical hits here]).

There are also ways to base reinforcement contingencies on past performance (i.e., bonuses for doing more of something you want this week than you did last week, or beating your 4-week average).  Keeping with the RPG theme, I could imagine earning prestige classes for remaining within the top 10% of historical performance for a period of time.

Anyway, sorry for talking your ear off.  At the end of the day, pragmatism rules and your data will tell you which ways of arranging rewards and punishers are most effective.  I've often thought it would be a blast to conduct research on how to best maximize motivation using a platform similar to what you've developed.  I've included a recent citation below that summarizes current knowledge on arranging rewards (unfortunately it's a chapter in a relatively expensive book, but it's there if you feel like delving into what academia has to say about the subject).

Best,

Jason

Arranging reinforcement contingencies in applied settings: Fundamentals and implications of recent basic and applied research.
DeLeon, Iser G.; Bullock, Christopher E.; Catania, A. Charles
Madden, Gregory J. (Ed); Dube, William V. (Ed); Hackenberg, Timothy D. (Ed); Hanley, Gregory P. (Ed); Lattal, Kennon A. (Ed), (2013). APA handbook of behavior analysis, Vol. 2: Translating principles into practice. , (pp. 47-75). Washington, DC, US: American Psychological Association, viii, 607 pp. doi: 10.1037/13938-003http://psycnet.apa.org/doi/10.1037/13938-003

Jason Bourret, PhD, BCBA-D
Assistant Clinical Director
The New England Center for Children, Inc.
33 Turnpike Road, Southborough, MA 01772
Direct: (508) 658-7519
Phone: (508) 481-1015 ext. 3051
Fax: (508) 485-3421
www.necc.org

---

The information in this transmission is intended only for the person or entity to whom it is addressed and may contain confidential and/or privileged material. These materials are intended solely for the use of the intended recipient. If you are not the intended recipient, any use, distribution or disclosure of this transmission is prohibited. If you received this information in error, please notify the sender and properly dispose of the material.

---

**Comment by lefnire** [comment]
an excellent post! thanks Jason. We've got some of those bits: the drop system (lvl 3, pets & potions) for randomization, and challenges for accountability (right on the horizon). But hearing those as known important approaches, we may have to double our efforts in those departments. We have our features bucketlist here https://trello.com/board/habitrpg/50e5d3684fe3a7266b0036d6, so with those mentions in mind some shuffling may be in order

**Comment by paglias** [comment]
Closing
