### ISSUE TITLE
Excess padding left and right on groups page

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9951]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
* UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
* Browser: Google Chrome 63.0.3239.132
* OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

![image](https://user-images.githubusercontent.com/4408379/35782227-073f6974-0a06-11e8-9eed-0b3e941ff95c.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by paglias** [comment]
I think this might actually be the desired effect but not sure, cc @Tressley

**Comment by Tressley** [comment]
@paglias -- The purple should extend to the edges. https://zpl.io/bJry1Db

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by Cappycot** [comment]
The easiest "tweak" would be to add
`margin-left: -1em;`
`margin-right: -1em;`
to the `.header` CSS section in `habitica/website/client/components/groups/groupPlan.vue`, but maybe there's a much more elegant fix?

**Comment by Cappycot** [comment]
The easiest "tweak" to this would probably be adding
`margin-left: -1em;`
`margin-right: -1em;`
to the `.header` section of the CSS code in `habitica/website/client/components/groups/groupPlan.vue`, but there's probably a much better solution somehow...
