### ISSUE TITLE
Discover Guilds search with special characters gives Internal Server Error

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9953]
When you go to the Discover Guilds page and search for `c++`, you see  an "Internal Server Error" red snackbar notification with this in the console: `Unhandled promise rejection  Error: Request failed with status code 500`

It's reproducable: every time I search for that term (or anything containing `++`), it happens and when I search for something else, it doesn't.

I'm assuming (but have not checked) that this is because the two `+` symbols are being interpreted as special characters. Any characters that might do that should be escaped before the search is performed.
Alternatively, if I'm wrong, whatever's causing this needs to be fixed in some other way. :)

**Comment by catalincodes** [comment]
My assumption, but I may be very wrong, is that it's trying to parse `c++` in the same way as it would parse `hello world` into search `hello+world`, which would then mean launch a query for `hello` AND `world`.

In this case when parsing `c++` it gets parsed into `c++`, which would then launch a query for `c` AND `(nothing)` AND `(error!)`.

The only contradiction is that searching for `c+` should trigger the same error, yet it returns all the guilds as a result.

**Comment by Alys** [comment]
Loggly error for the `c++` search:

`SyntaxError: Invalid regular expression: /c++/: Nothing to repeat`

**Comment by TheHollidayInn** [comment]
Eh, + is a special regex character, so we may just need to sanitize those searches. Or use the Javascript regex class.

**Comment by Hus274** [comment]
I can pick this up.

**Comment by Alys** [comment]
@Hus274 Thanks!
