### ISSUE TITLE
Creating an official Habitica challenge does not set "official" flag

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9955]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: N/A
  * Browser: Chrome (probably others as well tho)
  * OS: Windows (ditto)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Challenges contain the field `official`, which is a Boolean used to mark Challenges created and run by Habitica staff. The API sorts Challenges with `official: true` to the top of lists when fetched. However, the current UI for creating and editing Challenges does not include a way to set this flag. Instead, we give admins access to the "Habitica Official" category. This works for filtering the list of Challenges, but does not set the necessary flag to float them to the top.

~Two possible solutions:~

~1. When a Challenge gets the Habitica Official category added, also set the `official` flag to `true`. When it's removed, set the `official` flag to `false`.~
2. Deprecate the `official` field, and instead have the API sort Challenges with a category list including `habitica_official` to the top.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

N/A

**Comment by Alys** [comment]
Shall we go with the second option?
> Deprecate the `official` field, and instead have the API sort Challenges with a category list including `habitica_official` to the top.
That seems like the way to end up with the neatest code. We could add the `official` flag to the list of things that will be removed in the next version of the API. @paglias 

I'm marking this suggestion-discussion while we finalise this, but I'll put it back to help wanted in a few days if there's no objection (or sooner if there's agreement).

**Comment by SabreCat** [comment]
I do think that's the superior option of the two. Nice occasion to remove a tiny bit of data bloat.

**Comment by Alys** [comment]
Cool, I've set this to help wanted and edited the original post to strike-through the option we don't want.

As a note to whomever works on this: **The `official` field in the challenge schema should not be deleted because that would be a breaking change to the API. Instead it should just be ignored in the code. There's no need for us to remove the value of the flag from any existing challenges.**

FYI @paglias if you're keeping a list of changes to make in the next version of the API, `official` could be removed.

**Comment by Hus274** [comment]
I can take a look into this.
