### ISSUE TITLE
Joined and Owned Challenges should still appear in Discover, but annotated with status

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9956]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: N/A
  * Browser: All
  * OS: All

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Challenges the user owns or has joined do not appear in the Discover Challenges list. They were intended to, per designs for the page. They should be available in both My Challenges and Discover Challenges, but with appropriate labels based on their status:

![image](https://user-images.githubusercontent.com/4501321/35828183-392cb97c-0a84-11e8-9d7a-bc7fff44cd00.png)

Note there are several unimplemented elements above, but this issue is specifically about the "Owned" bubble. There should also be an a "Joined" bubble for relevant Challenges, but in green instead of the blue Joined uses.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

N/A

**Comment by Alys** [comment]
We have this PR: https://github.com/HabitRPG/habitica/pull/9535
It might be worth examining it to see if everything it currently does is still desirable.

**Comment by marvinrabe** [comment]
I will do this.

**Comment by Alys** [comment]
Thanks @marvinrabe ! I've changed this to in progress
