### ISSUE TITLE
Replace any remaining hardcoded English strings with I18N tokens

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#9958]
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

In the redesign, we ended up with a number of UI elements that used hardcoded English strings instead of translatable strings with `$t` calls. We've done some cleanup of this already, but there may still be some lingering examples in our .vue files. (If we do a thorough review and find they're all dealt with already, this can be closed!)

Related: #9210

**Comment by khipkin** [comment]
I would like to work on this! Also, looks like this issue still needs labels applied.

**Comment by paglias** [comment]
@khipkin go ahead!

**Comment by khipkin** [comment]
The 404.vue page contains this hard-coded message, with a TODO that I'm not sure how to address. Any ideas?

> <template lang="pug">
.row
  .col-12.text-center
    // @TODO i18n. How to setup the strings with the router-link inside?
    img.not-found-img(src='~assets/images/404.png')
    h1.not-found Sometimes even the bravest adventurer gets lost. 
    h2.not-found Looks like this link is broken or the page may have moved, sorry! 
    h2.not-found Head back to the <router-link to="/">Homepage</router-link> or <router-link :to="contactUsLink">Contact Us</router-link> about the issue.
</template>

**Comment by khipkin** [comment]
Should the copyright notice in the footer be localized?

**Comment by khipkin** [comment]
Should the starter tasks be localized?

**Comment by khipkin** [comment]
Does modifyInventory.vue need to be localized? If I understand/remember correctly, that is for dev purposes only.

**Comment by paglias** [comment]
@khipkin 

Regarding `router-link`, it won't work if you move that to i18n strings so in that case you'll have to split the string in multiple ones

Starting tasks: yes

modifyInventory / anything used by admins can be left in english, same for the copyright notice at the bottom

**Comment by lemoness** [comment]
I've updated the labels on this ticket.

**Comment by khipkin** [comment]
I don't think this is localizable:

> `Head back to the <router-link to="/">Homepage</router-link> or <router-link :to="contactUsLink">Contact Us</router-link> about the issue.`

Even if I localize the parts before, between, and after the router-link start/end tags, the ordering of the sentence fragments would not necessarily be preserved the same in all languages, so we can't just concatenate the individually localized strings. I would need to localize the entire string.

Maybe something like this could work instead:

> `You can: <router-link to="/">Return to the Homepage</router-link> or <router-link :to="contactUsLink">Contact Us about the issue</router-link>`

**Comment by paglias** [comment]
if something is too messy to localize I'd just skip it for now and we can come back to it later

**Comment by beffymaroo** [comment]
@khipkin Are you still working on this issue? Please let us know. Thank you!

**Comment by khipkin** [comment]
@beffymaroo Sorry, no. Couldn't get my local install working. I would still be interested in this though, if someone can help me get it working.

**Comment by Alys** [comment]
@khipkin We can help with that! In case you haven't noticed, there's new pages for most of the installation methods with updated details - see the links at the top of the main Setting Up Habitica Locally page. See if that helps, and if not, tell us  what's going wrong in the Aspiring Blacksmiths guild.

**Comment by beffymaroo** [comment]
@khipkin Were you able to make progress with your local install? Let us know if you're still interested in/working on this issue when you have a moment. Thank you!

**Comment by beffymaroo** [comment]
@khipkin It's been a while since we've heard from you so I'm putting "help wanted" back on this issue. If you'd like to reclaim it, just let us know!

**Comment by veeeeeee** [comment]
Is this still a useful ticket to keep open? Is there a way we can make it easier for a contributor to take on?

**Comment by SabreCat** [comment]
I'd suggest closing this one, myself. It should be more of a checkpoint for development to clean up any that you find in client code that you touch.
