### ISSUE TITLE
Move Links to Above Tavern

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#996]
It has become apparent that having Submit A Bug and Request a Feature on the side-bar is not enough; people aren't seeing them. As much as I love reciting "You should submit that bug by using the link to the left" like I took an arrow to the knee, we should probably move those two, along with the FAQ, to the top of the page, directly above the tavern box. 

You can make the size of the links smaller so it will look prettier, but please, please, PLEASE, my fingers are beginning to wear out.

Also, someone suggested that we change "Submit a Bug" to "Report a Problem", because some people are not sure whether or not what they are seeing "counts as a bug." (\* shrugs helplessly *)

**Comment by lefnire** [comment]
http://gyazo.com/356917a6d2d651165dfc55996a057d11 ?
