### ISSUE TITLE
Checkin Prizes Need Refresh

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#9966]
*Needs Confirmation*

I'll look into this soon, but logging this here in case anyone else knows:

MorganLeFlay
UserID: 4485e177-2203-4a07-b4e7-6ab5cda3ef60
Ahoy! I am updating an older bug that has since been deleted, and I don't entirely remember who I was interacting with!

My last complaint was that after I got my check-in items, I didn't see them in my inventory. Now I believe that I DID receive the items, but my web browser needed refreshing. It appears that clicking on the different overhead tabs (Tasks, Inventory, Shops, etc.) doesn't automatically refresh. So when I logged in later, the items were there. But because it was later that day, I assumed it was drops from completely tasks.

I came to this realization when I was expecting my Bardic Flute for one of the check ins and  did not see it in my inventory for quite some time, until I hit refresh a bunch of times and/or came back to Habitica later.

**Comment by lemoness** [comment]
Has this been confirmed?

I've updated the labels on this ticket.

**Comment by Alys** [comment]
I can't replicate it. When I get a login prize, I don't need to sync before I see it in my inventory. We can reopen this if it's reported again.
