### ISSUE TITLE
Probability of finding hatching potion bug

### ISSUE THREAD

**Issue by irigi** [HabitRPG/habitica#998]
When I check my daily as complete and change my mind and set it incomplete again, and then change my mind again and check it as complete, the probability of finding pet is still tested. By this "bug", I could produce infinitely many pets/hatching potions just by checking and unchecking my dailies.

**Comment by StanLindsey** [comment]
Yeah, we should only let that "roll" take place once and any subsequent completions of that task default to no drop.

**Comment by scroll** [comment]
But then if somebody checks it by accident and then unchecks it, then he loses the chance to get something from it.

**Comment by irigi** [comment]
@scroll : Sure, because he already used his chance to get something from it..

**Comment by scroll** [comment]
@irigi I was mostly talking from UX point of view. Misclicking happens. Maybe a prompt "Sure you finished this task?" is enough ?

**Comment by StanLindsey** [comment]
Maybe base it on the first click and store that if its unclicked.
