### ISSUE TITLE
three-dots menu should not be visible in "Copy as To-Do" modal

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9980]
_From Il Mago Azzurro (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) in the Report a Bug guild:_

"in the Copy message as todo it's possible to open the three dots menu of a task"

![screenshot_2018-02-10_20-55-31](https://user-images.githubusercontent.com/1495809/36061350-b7630a48-0ea4-11e8-9275-b5e290de6de0.png)

**Comment by hwdnoz** [comment]
Think I have a fix for this

**Comment by Alys** [comment]
This issue is open for other conntributors to work on. @howardnoz has done a partial fix in https://github.com/HabitRPG/habitica/pull/9981 which might be a good basis for a new PR.

**Comment by TheHollidayInn** [comment]
I don't think this is really a problem. The items don't do anything in context and the preview is correct. If we aren't getting many complaints, I'd prefer to leave this.

**Comment by paglias** [comment]
If we decide to fix this we just have to add another condition here https://github.com/HabitRPG/habitica/blob/develop/website/client/components/tasks/task.vue#L20

**Comment by TheHollidayInn** [comment]
I'm closing this for now. If others disagree, feel free to post.
