### ISSUE TITLE
Copy As To-Do for system messages shouldn't say "undefined"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9985]
When you use the Copy As To-Do feature on a system message (e.g., one of the red-on-white messages showing a player's quest progress), the To-Do's Note says:

`undefined wrote in [PartyName](https://habitica.com/groups/guild/12345678-8050-4253-1234567890abc)`

It should instead be phrased as:

`system message in [PartyName](https://habitica.com/groups/guild/12345678-8050-4253-1234567890abc)`

**Comment by Alys** [comment]
.... the To-Do's Note says:

`undefined wrote in [PartyName](https://habitica.com/groups/guild/12345678-8050-4253-1234567890abc)`

It should instead be phrased as:

`system message in [PartyName](https://habitica.com/groups/guild/12345678-8050-4253-1234567890abc)`

**Comment by Alys** [comment]
It would be good if this could be done before the World Boss is released because then there'll be system messages in the Tavern and so this feature is more likely to be used on system messages (e.g., by wiki editors making a To-Do to add the text of the message to the World Boss's page in the wiki).

**Comment by Alys** [comment]
@someoneigna Thanks for taking this on! I've marked it as in progress for you.
If you comment on an issue before you start, we can mark it then to avoid any chance of two people working on it at once. :)

I appreciate your quick fix for this one!

**Comment by someoneigna** [comment]
Oh yes, sorry. I had made the first commit when I remember I read that on the contributing guideline.
Sadly each time a rewrite the commit it gets appended to the pull request because of the link.
