### ISSUE TITLE
modals reappear after being closed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9986]
EDIT May 2018: New reports start here: https://github.com/HabitRPG/habitica/issues/9986#issuecomment-377483866

This has been a well-known problem for some time now but I've just realised we don't have an issue for it (unless I'm just not able to find it).

A modal will often re-open itself after you've closed it. We see a lot of reports of this each time there's a new Bailey message and it also happens for other modals. For example, create a challenge, then before you add any tasks, click on a party member to view their profile. When you close the profile screen, the challenge creation modal will reappear.

Sometimes the only way to get a modal to stop reappearing seems to be reloading the website. 

I'm marking this as a high priority since it's a significant annoyance, especially for the case of the Bailey messages. 

We do already have https://github.com/HabitRPG/habitica/issues/9969 for the class change modal reappearing, which is probably just one example of this bug, but I'm leaving it open too just in case it does need a separate fix (and it's definitely high priority since it can cause a user to waste gems).

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitica/issues/9531 for the hatching modal might be another example of this but could actually be a different bug since it's only a partial screen that reopens.

Maybe also https://github.com/HabitRPG/habitica/issues/9536

**Comment by Alys** [comment]
### When fixed, we should take https://github.com/HabitRPG/habitica/issues/9211 off hold.

**Comment by Alys** [comment]
Also https://github.com/HabitRPG/habitica/issues/9393 (the close challenge modal), with a potential fix at https://github.com/HabitRPG/habitica/pull/9545

**Comment by Alys** [comment]
Another example from CakeKnight (d8fc8d8b-a10f-416a-b089-587db2af9e4d):

"In a chat, If you press "copy message as to-do" and close the modal that pops up (pressing Close or clicking in another area on the page), then click on the avatar of another player and close it... The "copy message as to-do" reappears. I tried refreshing the page but the problem is still there, modals are weird :/"

**Comment by TheHollidayInn** [comment]
I'm pretty sure the issue here is we dismiss modals incorrectly sometimes. For example, we wil redirect to a page before closing a modal which breaks the modal stack. This issue will have to be addressed one by one for now.

**Comment by TheHollidayInn** [comment]
From Report a Bug Guild:

```
This does not happen with all popups. So far I've noticed it for Bailey, broken/ended challenges, "You won a challenge", and the Private Message modal. Reloading the page fixes it until I trigger one of the four malfunctioning popups again.
```

**Comment by someoneigna** [comment]
I will make a pr for this, we should be thorough and check every modal. 
It also happens with the "Copy As Todo -> Edit Party -> Copy as Todo" while being on Party screen.
And while being on Tasks with "View Party -> Click on Party member -> dismiss -> View party appears again".

**Comment by Alys** [comment]
There's a report below from Anysia (db190b28-8ce5-422e-8076-d43a62a7b204) that I _think_ might be related to this issue (possibly a modal opened itself with incorrect data in it). I can't reproduce this so I'm copying it here to record it and we can investigate it if it's still happening after the PR for this issue goes live. @someoneigna You can ignore this for now. I'm just using this issue to track it until/if we find evidence that it's not related. :)   
_"Went to clone a challenge this morning. After the first modal (with the title and description and whatnot) when I clicked create challenge it popped up with another modal that looks like a task but it was purple and said 'create string not found' or somesuch (the text was cut off). It did, in fact, clone the challenge, but I had to go find it in the guild I put it in in order to then edit the tasks. So. Something has changed between yesterday (when I cloned my last challenge) and today."_

**Comment by mbroshi** [comment]
This reproduces for me as follows
1. I'm on Tasks page
2. There's a new Bailey message
3. Click Dismiss
4. Edit an existing task
5. Click Save
Bailey announcement reappears.

**Comment by shanaqui** [comment]
At least one user is reporting this is still happening, both with the Dysheartener defeat message and with Bailey news items.

**Comment by Alys** [comment]
Another report, from jaolsn (04fd7a1a-1964-49c6-a2cb-59d2d231c7f6):
"After I close any one of the regular Habitca pop-up windows, a second window showing all of my character stats/profiles will pop-up every time."

(Sorry @shanaqui we should have reopened this from your report.)

**Comment by Alys** [comment]
Also just happened on my local install:
1. Create a challenge
2. Don't add task
3. Leave the challenge, choosing the option to remove all tasks
4. The challenge creation modal reappeared automatically

**Comment by Alys** [comment]
Another example reported today by loveroflibraries (2ce80a58-32fd-4275-a046-c9a84099b6f5):
"Every time I hit save after editing a task my profile pops up in front of my tasks page (like I have clicked on my avatar picture). It's not a major issue just annoying but thought I should report it in case it's a symptom of a bigger problem."
