### ISSUE TITLE
Checking that new passwords match is only performed on the second field

### ISSUE THREAD

**Issue by Widjet** [HabitRPG/habitica#999]
When you change your password, and when you first set a password on a new account, there are two fields to enter your (new) password, and you have to type the same password into both, which is a way of making sure you've typed your password in correctly.

The javascript validation of whether these passwords match is only processed when the second field is modified. So if you type 'password1' into the first field, then 'password2' into the second field, and afterwards modify the first field to say 'password2', the validation will incorrectly say that the two passwords do not match.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
